### PR TITLE
kubelet: more resilient node allocatable ephemeral-storage data getter

### LINKED ISSUE #99305: Cluster join fails due to insufficient ephemeral-storage
#### What happened:
`kubeadm join` on the new node fails sometimes. The following error appears in the log:
```
Feb 22 14:04:33 NEWHOST kubelet[7331]: W0222 14:04:33.866713    7331 predicate.go:113] Failed to admit pod etcd-NEWHOST_kube-system(13c2d55e88e08af2d946555ab67e9eab) - Unexpected error while attempting to recover from admission failure: preemption: error finding a set of pods to preempt: no set of running pods found to reclaim resources: [(res: ephemeral-storage, q: 104857600), ]
```

#### What you expected to happen:
`kubeadm join` on the new node succeeds every time

#### How to reproduce it (as minimally and precisely as possible):
Join a control plane node

#### Anything else we need to know?:
The node has over 40 GB of free space on its root partition.

I added some more logging to the following functions:
- `pkg/kubelet/cm/container_manager_linux.go`, `Start`
- `pkg/kubelet/lifecycle/predicate.go`, `GeneralPredicates`
- `pkg/kubelet/nodestatus/setters.go`, `MachineInfo`
- `pkg/kubelet/nodestatus/setters.go`, `ReadyCondition`
- `pkg/kubelet/preemption/preemption.go`, `HandleAdmissionFailure`
- `pkg/scheduler/framework/plugins/noderesources/fit.go`, `Filter`

It appears that the ephemeral storage is detected a bit too late:
```
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.599153    7331 setters.go:284] TRACE MachineInfo start
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.599202    7331 setters.go:334] TRACE MachineInfo got initialCapacity map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42191773696 scale:0} d:{Dec:<nil>} s: Format:BinarySI}]
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.599333    7331 setters.go:408] TRACE MachineInfo done, Capacity: map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42191773696 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:210 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}]
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.599357    7331 setters.go:409] TRACE MachineInfo done, Allocatable: map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42086916096 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:210 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}]
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.666348    7331 setters.go:527] TRACE capacity cpu: {i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.666413    7331 setters.go:527] TRACE capacity memory: {i:{value:42191773696 scale:0} d:{Dec:<nil>} s: Format:BinarySI}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.666425    7331 setters.go:527] TRACE capacity pods: {i:{value:210 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.666435    7331 setters.go:527] TRACE capacity ephemeral-storage: {i:{value:0 scale:0} d:{Dec:<nil>} s: Format:}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.673445    7331 setters.go:284] TRACE MachineInfo start
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.673490    7331 setters.go:334] TRACE MachineInfo got initialCapacity map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42191773696 scale:0} d:{Dec:<nil>} s: Format:BinarySI}]
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.673540    7331 setters.go:408] TRACE MachineInfo done, Capacity: map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42191773696 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:210 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}]
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.673563    7331 setters.go:409] TRACE MachineInfo done, Allocatable: map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42086916096 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:210 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}]
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.692186    7331 setters.go:284] TRACE MachineInfo start
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.692250    7331 setters.go:334] TRACE MachineInfo got initialCapacity map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42191773696 scale:0} d:{Dec:<nil>} s: Format:BinarySI}]
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.692306    7331 setters.go:408] TRACE MachineInfo done, Capacity: map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42191773696 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:210 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}]
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.692325    7331 setters.go:409] TRACE MachineInfo done, Allocatable: map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42086916096 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:210 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}]
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.743289    7331 setters.go:527] TRACE capacity cpu: {i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.743339    7331 setters.go:527] TRACE capacity memory: {i:{value:42191773696 scale:0} d:{Dec:<nil>} s: Format:BinarySI}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.743349    7331 setters.go:527] TRACE capacity pods: {i:{value:210 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.743362    7331 setters.go:527] TRACE capacity ephemeral-storage: {i:{value:0 scale:0} d:{Dec:<nil>} s: Format:}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.752328    7331 container_manager_linux.go:613] TRACE containerManagerImpl.Start
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.752381    7331 container_manager_linux.go:625] TRACE containerManagerImpl.Start, map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} ephemeral-storage:{i:{value:51384074240 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42191773696 scale:0} d:{Dec:<nil>} s: Format:BinarySI}]
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.772730    7331 setters.go:527] TRACE capacity cpu: {i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.772773    7331 setters.go:527] TRACE capacity memory: {i:{value:42191773696 scale:0} d:{Dec:<nil>} s: Format:BinarySI}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.772780    7331 setters.go:527] TRACE capacity pods: {i:{value:210 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.772786    7331 setters.go:527] TRACE capacity ephemeral-storage: {i:{value:0 scale:0} d:{Dec:<nil>} s: Format:}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.826100    7331 setters.go:284] TRACE MachineInfo start
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.826146    7331 setters.go:334] TRACE MachineInfo got initialCapacity map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} ephemeral-storage:{i:{value:51384074240 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42191773696 scale:0} d:{Dec:<nil>} s: Format:BinarySI}]
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.826353    7331 setters.go:408] TRACE MachineInfo done, Capacity: map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} ephemeral-storage:{i:{value:51384074240 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42191773696 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:210 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}]
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.826414    7331 setters.go:409] TRACE MachineInfo done, Allocatable: map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} ephemeral-storage:{i:{value:46245666740 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42086916096 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:210 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}]
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.846712    7331 predicate.go:225] TRACE nodeInfo.Allocatable &{MilliCPU:12000 Memory:42086916096 EphemeralStorage:0 AllowedPodNumber:210 ScalarResources:map[hugepages-1Gi:0 hugepages-2Mi:0]}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.846749    7331 predicate.go:226] TRACE nodeInfo.Requested &{MilliCPU:0 Memory:0 EphemeralStorage:0 AllowedPodNumber:0 ScalarResources:map[]}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.846845    7331 predicate.go:225] TRACE nodeInfo.Allocatable &{MilliCPU:12000 Memory:42086916096 EphemeralStorage:0 AllowedPodNumber:210 ScalarResources:map[hugepages-1Gi:0 hugepages-2Mi:0]}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.846854    7331 predicate.go:226] TRACE nodeInfo.Requested &{MilliCPU:0 Memory:0 EphemeralStorage:0 AllowedPodNumber:0 ScalarResources:map[]}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.846892    7331 predicate.go:225] TRACE nodeInfo.Allocatable &{MilliCPU:12000 Memory:42086916096 EphemeralStorage:0 AllowedPodNumber:210 ScalarResources:map[hugepages-1Gi:0 hugepages-2Mi:0]}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.846940    7331 predicate.go:226] TRACE nodeInfo.Requested &{MilliCPU:0 Memory:0 EphemeralStorage:0 AllowedPodNumber:0 ScalarResources:map[]}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.847005    7331 predicate.go:225] TRACE nodeInfo.Allocatable &{MilliCPU:12000 Memory:42086916096 EphemeralStorage:0 AllowedPodNumber:210 ScalarResources:map[hugepages-1Gi:0 hugepages-2Mi:0]}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.847014    7331 predicate.go:226] TRACE nodeInfo.Requested &{MilliCPU:0 Memory:0 EphemeralStorage:0 AllowedPodNumber:0 ScalarResources:map[]}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.847072    7331 predicate.go:225] TRACE nodeInfo.Allocatable &{MilliCPU:12000 Memory:42086916096 EphemeralStorage:0 AllowedPodNumber:210 ScalarResources:map[hugepages-1Gi:0 hugepages-2Mi:0]}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.847080    7331 predicate.go:226] TRACE nodeInfo.Requested &{MilliCPU:250 Memory:0 EphemeralStorage:0 AllowedPodNumber:0 ScalarResources:map[]}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.847160    7331 predicate.go:225] TRACE nodeInfo.Allocatable &{MilliCPU:12000 Memory:42086916096 EphemeralStorage:0 AllowedPodNumber:210 ScalarResources:map[hugepages-1Gi:0 hugepages-2Mi:0]}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.847177    7331 predicate.go:226] TRACE nodeInfo.Requested &{MilliCPU:450 Memory:0 EphemeralStorage:0 AllowedPodNumber:0 ScalarResources:map[]}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.866562    7331 predicate.go:225] TRACE nodeInfo.Allocatable &{MilliCPU:12000 Memory:42086916096 EphemeralStorage:0 AllowedPodNumber:210 ScalarResources:map[hugepages-1Gi:0 hugepages-2Mi:0]}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.866598    7331 predicate.go:226] TRACE nodeInfo.Requested &{MilliCPU:550 Memory:0 EphemeralStorage:0 AllowedPodNumber:0 ScalarResources:map[]}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.866620    7331 preemption.go:67] TRACE cannot admit etcd-NEWHOST, [Node didn't have enough resource: ephemeral-storage, requested: 104857600, used: 0, capacity: 0]
Feb 22 14:04:33 NEWHOST kubelet[7331]: W0222 14:04:33.866713    7331 predicate.go:113] Failed to admit pod etcd-NEWHOST_kube-system(13c2d55e88e08af2d946555ab67e9eab) - Unexpected error while attempting to recover from admission failure: preemption: error finding a set of pods to preempt: no set of running pods found to reclaim resources: [(res: ephemeral-storage, q: 104857600), ]
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.905188    7331 setters.go:527] TRACE capacity cpu: {i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.905231    7331 setters.go:527] TRACE capacity memory: {i:{value:42191773696 scale:0} d:{Dec:<nil>} s: Format:BinarySI}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.905239    7331 setters.go:527] TRACE capacity pods: {i:{value:210 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}
Feb 22 14:04:33 NEWHOST kubelet[7331]: E0222 14:04:33.905248    7331 setters.go:527] TRACE capacity ephemeral-storage: {i:{value:51384074240 scale:0} d:{Dec:<nil>} s: Format:BinarySI}
Feb 22 14:04:43 NEWHOST kubelet[7331]: E0222 14:04:43.789009    7331 setters.go:284] TRACE MachineInfo start
Feb 22 14:04:43 NEWHOST kubelet[7331]: E0222 14:04:43.789081    7331 setters.go:334] TRACE MachineInfo setting capacity to map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} ephemeral-storage:{i:{value:51384074240 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42191773696 scale:0} d:{Dec:<nil>} s: Format:BinarySI}]
Feb 22 14:04:43 NEWHOST kubelet[7331]: E0222 14:04:43.789183    7331 setters.go:408] TRACE MachineInfo done, Capacity: map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} ephemeral-storage:{i:{value:51384074240 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42191773696 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:210 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}]
Feb 22 14:04:43 NEWHOST kubelet[7331]: E0222 14:04:43.789234    7331 setters.go:409] TRACE MachineInfo done, Allocatable: map[cpu:{i:{value:12000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} ephemeral-storage:{i:{value:46245666740 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-1Gi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} hugepages-2Mi:{i:{value:0 scale:0} d:{Dec:<nil>} s: Format:BinarySI} memory:{i:{value:42086916096 scale:0} d:{Dec:<nil>} s: Format:BinarySI} pods:{i:{value:210 scale:0} d:{Dec:<nil>} s: Format:DecimalSI}]
```

/sig node storage

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20.4, commit e87da0bd6e03ec3fea7933c4b5263d151aafd07c
- Kernel (e.g. `uname -a`): 4.9.252-1.ph2

### LINKED ISSUE #102715: kubeadm join (control plane) consistently fails with CrashLoopBackOff
#### What happened:

When trying to join a second or sometimes third control plane node, `kubeadm join` fails with:

- something that looks like an etcd hangup ("Initial timeout of 40s passed")
- CrashLoopBackOff for one of the kube-apiserver pods

The k8s [docs](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#pods-in-runcontainererror-crashloopbackoff-or-error-state) suggest opening an issue here.

#### What you expected to happen:

Successful join op

#### How to reproduce it (as minimally and precisely as possible):

Here goes...

First to init the first control plane node (1 of 3 in an HA cluster).

```
kubeadm init --upload-certs --v 5 --config /tmp/custom.yaml
```

This is successful. Contents of `/tmp/custom.yaml`:

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.21.1

controllerManager:
  extraArgs:
    profiling: "false"
    tls-min-version: VersionTLS12
scheduler:
  extraArgs:
    tls-min-version: VersionTLS12
apiServer:
  extraArgs:
    tls-min-version: VersionTLS12
controlPlaneEndpoint: "kube-apiserver-xxxx.elb.xxxxxx.amazonaws.com:6443"

---

apiVersion: kubeadm.k8s.io/v1beta2
kubernetesVersion: v1.21.1
kind: InitConfiguration

certificateKey: xxxxxxxxxxxxxxxx
bootstrapTokens:
  - token: "5zb1it.xxxxxxxxxxxxxxxx"
    description: 'kubeadm bootstrap token'
```

Apply CNI plugin:

```
set -o pipefail
kubectl apply \ 
     --wait \ 
     -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
```

Looks fine at this point.  `kubectl get pod --namespace kube-system` shows all Running.

Next join 2nd control plane node:

```
kubeadm join --v 5 --config /tmp/custom.yaml
```

This seems to go off without a hitch also. The new node comes up as Ready and all new pods Running. Contents of `/tmp/custom.yaml` here:

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.21.1

controllerManager:
  extraArgs:
    profiling: "false"
    tls-min-version: VersionTLS12
scheduler:
  extraArgs:
    tls-min-version: VersionTLS12
apiServer:
  extraArgs:
    tls-min-version: VersionTLS12
controlPlaneEndpoint: "kube-apiserver-xxxx.elb.xxxxxx.amazonaws.com:6443"

---

apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration

discovery:
  bootstrapToken:
    token: "5zb1it.xxxxxxxxxxxxxxxx"
    apiServerEndpoint: "kube-apiserver-xxxx.elb.xxxxxx.amazonaws.com:6443"
    caCertHashes:
      - "sha256:xxxxxxxxxxxxxxxx"
controlPlane:
  certificateKey: xxxxxxxxxxxxxxxx
```

Now for the third, failing node: _same exact join command, same exact config_. It is really a replica node of the 2nd control plane node, and yet times out.

Output:

```
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[preflight] Running pre-flight checks before initializing the new control plane instance
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[download-certs] Downloading the certificates in Secret "kubeadm-certs" in the "kube-system" Namespace
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [ip-xx-xx-xx-179 kube-apiserver-xxxx.elb.xxxxxx.amazonaws.com kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 xx-xx-xx-179]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [ip-xx-xx-xx-179 localhost] and IPs [xx-xx-xx-179 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [ip-xx-xx-xx-179 localhost] and IPs [xx-xx-xx-179 127.0.0.1 ::1]
[certs] Generating "front-proxy-client" certificate and key
[certs] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[certs] Using the existing "sa" key
[kubeconfig] Generating kubeconfig files
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[check-etcd] Checking that the etcd cluster is healthy
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
[etcd] Announced new etcd member joining to the existing etcd cluster
[etcd] Creating static Pod manifest for "etcd"
[etcd] Waiting for the new etcd member to join the cluster. This can take up to 40s
[kubelet-check] Initial timeout of 40s passed.
```

Then going back to initial control node. Output of `kubectl get pod --namespace kube-system`:

```
NAME                                       READY   STATUS             RESTARTS   AGE
coredns-558bd4d5db-8th9k                   1/1     Running            0          40m
coredns-558bd4d5db-f8mvf                   1/1     Running            0          40m
etcd-ip-xx-xx-xx-109                      1/1     Running            0          40m
etcd-ip-xx-xx-xx-198                      1/1     Running            0          32m
kube-apiserver-ip-xx-xx-xx-109            1/1     Running            0          40m
kube-apiserver-ip-xx-xx-xx-179            0/1     CrashLoopBackOff   9          28m
kube-apiserver-ip-xx-xx-xx-198            1/1     Running            0          32m
kube-controller-manager-ip-xx-xx-xx-109   1/1     Running            1          40m
kube-controller-manager-ip-xx-xx-xx-179   1/1     Running            0          28m
kube-controller-manager-ip-xx-xx-xx-198   1/1     Running            0          32m
kube-proxy-jlp2l                           1/1     Running            0          32m
kube-proxy-pf2mh                           1/1     Running            0          28m
kube-proxy-xv4jv                           1/1     Running            0          40m
kube-scheduler-ip-xx-xx-xx-109            1/1     Running            1          40m
kube-scheduler-ip-xx-xx-xx-179            1/1     Running            0          28m
kube-scheduler-ip-xx-xx-xx-198            1/1     Running            0          32m
weave-net-7f5rw                            2/2     Running            0          32m
weave-net-fpqtd                            2/2     Running            0          28m
weave-net-pwlxd                            2/2     Running            1          38m
```

Uh-oh. So CrashLoopBackOff shows up and one etcd pod is missing completely.

#### Anything else we need to know?:

No.

#### Environment:
- Kubernetes version (use `kubectl version`): `version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: AWS EC2
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): `Linux ip-xx-xx-xx-109 5.4.0-1038-aws #40~18.04.1-Ubuntu SMP Sat Feb 6 01:56:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Network plugin and version (if this is a network-related bug): weave-net

### PR DESCRIPTION
**Pull request by jackfrancis**
#### What this PR does / why we need it:

This PR modifies the `GetCapacity` containerManager method that is used to derive allocatable ephemeral storage node data. This change adds a "just-in-time" cAdvisor call to gather rootfs storage data in case the containerManager runtime instance hasn't yet stored that data.

This change deals with a race that is documented in code here:

https://github.com/kubernetes/kubernetes/blob/v1.21.0/pkg/kubelet/cm/container_manager_linux.go#L245

In summary: (1) the containerManager is instantiated, and then (2) Starts; but, node info may have been gathered between steps 1 and 2 in some instances, which leads to outcomes in which the node data is missing ephemeral storage allocatable data. Additionally, that "incomplete" node representation is subject to being submitted to the apiserver during node registration, leading to further side-effects during cluster bootstrapping where the authoritative node data declares that it has zero allocatable ephemeral storage.

#### Which issue(s) this PR fixes:

Fixes #99305
Fixes #102715

#### Does this PR introduce a user-facing change?

```release-note
kubelet: wait for node allocatable ephemeral-storage data
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/cm/container_manager_linux.go [hunk 1]
```diff
@@ -1060,7 +1060,32 @@ func isKernelPid(pid int) bool {
 	return err != nil && os.IsNotExist(err)
 }
 
+// GetCapacity returns node capacity data for "cpu", "memory", "ephemeral-storage", and "huge-pages*"
+// At present this method is only invoked when introspecting ephemeral storage
```
Comment (jackfrancis) [inline pkg/kubelet/cm/container_manager_linux.go:1064]: Added this comment to emphasize the practical need to work harder to deliver ephemeral-storage data: This `GetCapacity` method is *only* called to get ephemeral storage data. See here where we refer to it when defining the set of `MachineInfo` setter functions:

https://github.com/kubernetes/kubernetes/blob/v1.21.0/pkg/kubelet/kubelet_node_status.go#L617

Those set of funcs are then assigned to the main kubelet instance:

https://github.com/kubernetes/kubernetes/blob/v1.21.0/pkg/kubelet/kubelet.go#L848

And then those status funcs are invoked every time kubelet sets the node status for a node:

https://github.com/kubernetes/kubernetes/blob/v1.21.0/pkg/kubelet/kubelet_node_status.go#L583

What's interesting here is that when we invoke `MachineInfo` with `GetCapacity()` as the `capacityFunc`, we see that we only use `capacityFunc` to derive ephemeral storage data, and nothing else:

https://github.com/kubernetes/kubernetes/blob/v1.21.0/pkg/kubelet/nodestatus/setters.go#L332

Thus, we should improve the resiliency/reliability of `GetCapacity()` to actually return real ephemeral storage allocatable data.

File: pkg/kubelet/cm/container_manager_linux.go [hunk 2]
```diff
@@ -1060,7 +1060,32 @@ func isKernelPid(pid int) bool {
...
 func (cm *containerManagerImpl) GetCapacity() v1.ResourceList {
+	// We store allocatable ephemeral-storage in the capacity property once we Start() the container manager
+	if _, ok := cm.capacity[v1.ResourceEphemeralStorage]; !ok {
+		// If we haven't yet stored the capacity for ephemeral-storage, we can fetch it directly from cAdvisor,
+		// with some retry tolerance in case it hasn't yet started
+		var ret v1.ResourceList
+		err := wait.PollImmediate(3*time.Second, 5*time.Minute, func() (bool, error) {
```
Comment (aramase) [inline pkg/kubelet/cm/container_manager_linux.go:1071]: Is this timeout based on test results? I'm curious how these retries work when the `--node-status-update-frequency` is 10s. Will retries here affect the kubelet status update for the node?

Comment (aramase) [reply pkg/kubelet/cm/container_manager_linux.go:1071]: I think the answer is the retries happen when the node is initialized the 1st time and shouldn't affect the kubelet periodic status update, but just checking 😄

Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go:1071]: Good question. `setNodeStatus(node)` is invoked in two paths:

1. When using `initialNode(ctx)` to get a "local" node object representation (i.e., not a node object representation as the cluster sees it by calling the apiserver GET node|LIST nodes endpoint)
  - `initialNode` is used in two places: (1) it is explicitly used when first registering itself with the apiserver (see `kubelet.registerWithAPIServer()` and (2) it is used as a fallback in various kubelet "get node" paths when the kubeclient is not yet setup, or when there's a transient error calling the apiserver using the kubeclient
2. In the various "update node status" flows, e.g., when a volume attachement/detachment reconciliation fires

A read through the code suggests that the regular node status update reconcilers are used by volume attachment/detachment only. I might be missing something though.

In any event, I think the interval and timeout in the retry loop is totally arbitrary at this point, totally open to tuning that.

File: pkg/kubelet/cm/container_manager_linux.go [hunk 3]
```diff
@@ -1060,7 +1060,34 @@ func isKernelPid(pid int) bool {
...
+				rootfs, err := cm.cadvisorInterface.RootFsInfo()
+				if err == nil {
+					for rName, rQuant := range cm.capacity {
+						ret[rName] = rQuant
+					}
+					ret[v1.ResourceEphemeralStorage] = cadvisor.EphemeralStorageCapacityFromFsInfo(rootfs)[v1.ResourceEphemeralStorage]
+					return true, nil
+				}
+				klog.Errorf("Unable to get rootfs data from cAdvisor interface")
+				return false, nil
```
Comment (rphillips) [inline pkg/kubelet/cm/container_manager_linux.go:1082]: One nit... Usually err is checked for not nil for errors, and the function returns early... IMO the logic should be reversed to take that into account.

It seems like ret should be assigned to cm.capacity, since it contains updated data. Perhaps it was an oversight?

Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go]: inverted the err checking for nil, checking for != nil first now

File: pkg/kubelet/cm/container_manager_linux.go [hunk 4]
```diff
@@ -1060,7 +1060,36 @@ func isKernelPid(pid int) bool {
...
+				}
+				ret[v1.ResourceEphemeralStorage] = cadvisor.EphemeralStorageCapacityFromFsInfo(rootfs)[v1.ResourceEphemeralStorage]
+				return true, nil
+			}
+			return false, nil
+		})
+		if err == nil {
+			return ret
+		}
+		klog.Infof("Unable to get ephemeral-storage data from cAdvisor")
```
Comment (pacoxu) [inline pkg/kubelet/cm/container_manager_linux.go:1091]: Should use `klog.InfoS`

File: pkg/kubelet/cm/container_manager_linux.go [hunk 5]
```diff
@@ -1060,7 +1060,36 @@ func isKernelPid(pid int) bool {
...
 
+// GetCapacity returns node capacity data for "cpu", "memory", "ephemeral-storage", and "huge-pages*"
+// At present this method is only invoked when introspecting ephemeral storage
 func (cm *containerManagerImpl) GetCapacity() v1.ResourceList {
+	// We store allocatable ephemeral-storage in the capacity property once we Start() the container manager
+	if _, ok := cm.capacity[v1.ResourceEphemeralStorage]; !ok {
+		// If we haven't yet stored the capacity for ephemeral-storage, we can fetch it directly from cAdvisor,
+		// with some retry tolerance in case it hasn't yet started
+		ret := v1.ResourceList{}
+		err := wait.PollImmediate(1*time.Second, 30*time.Second, func() (bool, error) {
```
Comment (cynepco3hahue) [inline pkg/kubelet/cm/container_manager_linux.go:1071]: does it mean that we can have here an additional delay during the node status update? Can we just do the same thing without introducing `wait.PollImmediate`?

Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go:1071]: Yes, it means that *if* the initial call to cAdvisor returns an error (or if `cm.cadvisorInterface` is nil, but I don't think that's actually possible in practice — I put it there to be more defensive).

My thinking is that there are edge cases where either cAdvisor isn't yet ready to report a sane response, and for 99% of those edge cases an additional retry or two will produce the desired outcome.

Are you concerned that there are going to be terminal edge cases where we delay node registrations by 30 seconds?

Comment (ehashman) [reply pkg/kubelet/cm/container_manager_linux.go:1071]: If I'm reading this right:

- This could block every time we call `GetCapacity`. Thus, as written this could delay node startup time up to 30s, and potentially block in other places where we didn't expect it to. I'm not sure this should block at all; how many attempts to read cadvisor do we want to make, realistically?
- In case of an error, we return an entirely empty resource list. But the bug is limited to ephemeral storage capacity being set wrong. Hence, I think this change should be limited to updating ephemeral storage capacity, and not return an empty resource list if that can't be found.
- A unit test could have potentially caught that accidental wipe of the rest of capacity info on error, so I suggest we add one as part of this PR.

/lgtm cancel

Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go:1071]: Happy to lean into UT here.

For clarity, this func is *only* invoked here:

https://github.com/kubernetes/kubernetes/blob/v1.21.0/pkg/kubelet/nodestatus/setters.go#L332

Returning an empty (important: not nil) fulfills the existing client usage expectations here:

https://github.com/kubernetes/kubernetes/blob/v1.21.0/pkg/kubelet/nodestatus/setters.go#L334

I can't answer the question about how many times to call cAdvisor. I can do some tests w/ the async + retry removed, just calling it once as a best effort and see if I can still detect the race condition outcome (node registered w/ zero ephemeral storage, thus blocking forward progress for static pod admission on kubeadm + etcd +2nd node scenario).

How does that sound?

(And yes, when this is all done, make sure I include a sane UT that captures the intent :) )

File: pkg/kubelet/cm/container_manager_linux.go [hunk 6]
```diff
@@ -1060,7 +1060,29 @@ func isKernelPid(pid int) bool {
 	return err != nil && os.IsNotExist(err)
 }
 
+// GetCapacity returns node capacity data for "cpu", "memory", "ephemeral-storage", and "huge-pages*"
+// At present this method is only invoked when introspecting ephemeral storage
 func (cm *containerManagerImpl) GetCapacity() v1.ResourceList {
+	// We store allocatable ephemeral-storage in the capacity property once we Start() the container manager
+	if _, ok := cm.capacity[v1.ResourceEphemeralStorage]; !ok {
```
Comment (jackfrancis) [inline pkg/kubelet/cm/container_manager_linux.go:1067]: @ehashman this modified implementation attempts a single "best effort" call to cAdvisor if ephemeral storage data is missing, which will cap any additional delays to node registration to the amount of time it takes to get a response from `cadvisorInterface.RootFsInfo()` (plus some additional accounting for ResourceList data construction in the successful data retrieval cases).

Also, rather than returning an empty ResourceList in the "failed to get data" case, we will simply return the capacity property, which mimics the current behavior.

**Comment by cynepco3hahue** [comment]
Thanks for the update.
/lgtm

**Comment by jackfrancis** [comment]
retest

File: pkg/kubelet/cm/container_manager_linux_test.go [hunk 7]
```diff
@@ -165,3 +171,69 @@ func TestSoftRequirementsValidationSuccess(t *testing.T) {
 	assert.NoError(t, err)
 	assert.True(t, f.cpuHardcapping, "cpu hardcapping is expected to be enabled")
 }
+
+func TestGetCapacity(t *testing.T) {
```
Comment (jackfrancis) [inline pkg/kubelet/cm/container_manager_linux_test.go:175]: cc @ehashman new UT

(thx!)

File: pkg/kubelet/cm/container_manager_linux.go (hunk 5 above)
Comment (ehashman) [reply pkg/kubelet/cm/container_manager_linux.go]: Interesting. This is feature gated. That feature is declared as part of https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/1029-ephemeral-storage-quotas/README.md which hasn't been updated since 1.16 when it went beta.

This to me seems like an issue with the current KEP implementation.

@kubernetes/sig-storage-misc @msau42 can you PTAL?

**Comment by ehashman** [comment]
@jackfrancis thanks for sharing that code reference... the TODO here and the feature flag make me think this is an incomplete enhancement that we should bring up with SIG Storage. Tagged above.

https://github.com/kubernetes/kubernetes/blob/cb303e613a121a29364f75cc67d3d580833a7479/pkg/kubelet/nodestatus/setters.go#L329-L338

**Comment by jackfrancis** [comment]
@ehashman thx, it will be good to hear sig-storage's take on this

My 2¢ is that standardizing all the "capacity" getters into a single interface, and to prefer the current ephemeral-storage getter as that interface, is orthogonal refactor work. I base that not on historical knowledge but just spending time in code here, so ymmv.

Also the feature-flag is there simply because ephemeral storage per se requires `LocalStorageCapacityIsolation` (beta since 1.10 it seems)

**Comment by msau42** [comment]
/assign @jingxu97 
to help review from storage side

File: pkg/kubelet/cm/container_manager_linux.go (hunk 6 above)
Comment (pacoxu) [inline pkg/kubelet/cm/container_manager_linux.go:1067]: Need we check the feature gate status here like below?
https://github.com/kubernetes/kubernetes/blob/5de1a754c8f875cacfa49b9c5ed63c6c35b7e9e5/pkg/kubelet/cm/container_manager_linux.go#L640-L649

File: pkg/kubelet/cm/container_manager_linux.go (hunk 1 above)
Comment (jingxu97) [reply pkg/kubelet/cm/container_manager_linux.go:1064]: so where cpu and memory is retrieved from?

File: pkg/kubelet/cm/container_manager_linux.go [hunk 8]
```diff
@@ -1060,7 +1060,29 @@ func isKernelPid(pid int) bool {
...
+		// If we haven't yet stored the capacity for ephemeral-storage, we can try to fetch it directly from cAdvisor,
+		if cm.cadvisorInterface != nil {
+			rootfs, err := cm.cadvisorInterface.RootFsInfo()
+			if err != nil {
+				klog.ErrorS(err, "Unable to get rootfs data from cAdvisor interface")
+				// If the rootfsinfo retrieval from cAdvisor fails for any reason, fallback to returning the capacity property with no ephemeral storage data
+				return cm.capacity
```
Comment (jingxu97) [inline pkg/kubelet/cm/container_manager_linux.go:1074]: what is the possible reason for it to fail? 
Is it better to retry here a few times instead of returning empty data?

File: pkg/kubelet/cm/container_manager_linux.go (hunk 5 above)
Comment (jingxu97) [reply pkg/kubelet/cm/container_manager_linux.go]: @ehashman thanks for raising it. We plan to evaluate this feature and make it GA next.

File: pkg/kubelet/cm/container_manager_linux.go (hunk 6 above)
Comment (jingxu97) [reply pkg/kubelet/cm/container_manager_linux.go:1067]: I see you had retry logic before and now remove it. So in your test, did you see any cases that cadvisor might not be initialized at this moment and return no data. If so, how much time typically we need to wait for it to be ready? Thanks!

Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go:1067]: In my tests I *did not* encounter cAdvisor not being ready (though I didn't run like 10,000 real-world simulations). So, I think in practice not retrying in a loop will work in a very high percentage of cases. And the edge case scenarios (expressed in unit tests) are essentially no-ops for a kubelet runtime, and functionally equivalent to what happens today.

By the way, as you probably figured out, I removed the retries based on prior review feedback.

File: pkg/kubelet/cm/container_manager_linux.go (hunk 8 above)
Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go:1074]: Failure conditions are the low likelihood that the root volume on the OS does not return a proper result when introspecting for available/allocatable storage (very rare I/O edge case and/or catastrophic OS failure) or a result of cAdvisor runtime being stuck in some way (not reproduced in practice.

tl;dr this should not happen, and in my real-world tests I have never seen it happen

File: pkg/kubelet/cm/container_manager_linux.go (hunk 1 above)
Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go:1064]: CPU and memory are stored in the containerManager instance's `capacity` property _when containerManager is instantiated_, right here:

https://github.com/kubernetes/kubernetes/blob/v1.21.0/pkg/kubelet/cm/container_manager_linux.go#L246

However, storage is _not_ stored at that time, which is why the race condition occurs, and why we may need to call it "just in time" during node info retrieval/node registration. (See this comment: https://github.com/kubernetes/kubernetes/blob/v1.21.0/pkg/kubelet/cm/container_manager_linux.go#L245)

CPU/memory info is gathered using another function, see here:

https://github.com/kubernetes/kubernetes/blob/v1.21.0/pkg/kubelet/nodestatus/setters.go#L296

there are 2 tl;dr points:

1. storage and CPU/memory are retrieved discretely, using individual code paths
2. CPU/memory is gathered immediately when the kubelet runtime starts, and has its own error handling (see code); storage is gathered a little later than CPU/memory, and thus node info events *may* occur before storage has been gathered, leading to node registrations with "0" allocatable ephemeral-storage.

This PR accomplishes the following:

If we detect that allocatable ephemeral-storage has not yet been gathered during a node info/node registration operation, we attempt to eagerly gather that storage data "just in time" in order to prevent registering a node with "0" allocatable ephemeral-storage.

Hope that makes sense!

File: pkg/kubelet/cm/container_manager_linux.go (hunk 8 above)
Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go:1074]: @cynepco3hahue @ehashman thoughts? Do we think a retry window of ~1-2 seconds is appropriate? (As well as the add'l go routine overhead that a async retry loop will require?)

Thx for the review @jingxu97!

**Comment by CecileRobertMichon** [comment]
+1 on moving forward with this change, the race condition it's fixing is causing a lot of transient failures on Cluster API + kubeadm (https://github.com/kubernetes/kubernetes/issues/99305) and is preventing us (cluster-api-provider-azure) from properly testing k8s 1.20+ in CI.

**Comment by ehashman** [comment]
> +1 on moving forward with this change, the race condition it's fixing is causing a lot of transient failures on Cluster API + kubeadm (#99305) and is preventing us (cluster-api-provider-azure) from properly testing k8s 1.20+ in CI.

Per https://github.com/kubernetes/kubernetes/pull/101882#discussion_r645877796 I don't know if this actually fixes any race conditions, and it seems to introduce a new one. Realistically, since this hasn't merged yet, it will probably miss the June cherry-pick window for 1.20 since the change needs to soak in CI first before backport.

File: pkg/kubelet/cm/container_manager_linux.go (hunk 8 above)
Comment (ehashman) [reply pkg/kubelet/cm/container_manager_linux.go:1074]: Per https://github.com/kubernetes/kubernetes/issues/99305#issuecomment-794926298 I think worrying that cadvisor won't be ready yet is a valid concern... cc @pacoxu

Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go:1074]: According to this PR (disclaimer: from 4 years ago!) it is not:

https://github.com/kubernetes/kubernetes/pull/48567

But we're also setting storage capacity differently right now than in that above PR. (Although, still not setting it in the same flow as CPU/memory).

It does not seem that cadvisor would return a "wrong" value, rather that it would fail to get storage data from the "/" volume and return an error.

File: pkg/kubelet/cm/container_manager_linux.go (hunk 6 above)
Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go:1067]: The feature gate check is in place before this method is invoked:

https://github.com/kubernetes/kubernetes/blob/v1.21.0/pkg/kubelet/nodestatus/setters.go#L332

Should we add the feature gate check inside the actual method itself as well?

File: pkg/kubelet/cm/container_manager_linux.go (hunk 8 above)
Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go:1074]: Thanks for normalizing everyone's work here @ehashman :)

I don't see how this PR, as-is, could introduce further race conditions. It is simply adding a novel "best effort" implementation of gathering storage data, doing it the exact same way we do it now during containerManager Start(). Without any retries, this won't *guarantee* that we get valid data, but in my tests it definitely reduces the occurence of "get node info" code flows that result in a node representation with zero allocatable ephemeral-storage data.

**Comment by jackfrancis** [comment]
>  it will probably miss the June cherry-pick window for 1.20 since the change needs to soak in CI first before backport.

No rush for this particular 1.20 cherry-pick window, let's get this right. (Obviously we do want to get a fix for these behaviors in before 1.20 goes out of support 😄)

File: pkg/kubelet/cm/container_manager_linux.go (hunk 8 above)
Comment (ehashman) [reply pkg/kubelet/cm/container_manager_linux.go:1074]: > I don't see how this PR, as-is, could introduce further race conditions

The race would be:

- we see the storage capacity isn't set
- underneath us, storage capacity gets set
- but we are not setting it atomically, so we check cadvisor here, and potentially overwrite it
- and, if we fail to check cadvisor here, but this was already set elsewhere, we end up overwriting it with a 0

Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go:1074]: Thanks for the detail! If I understand this correctly I believe this is being considered already:

https://github.com/kubernetes/kubernetes/blob/bcfe175c3dd756eba96b05457445a279c5f8a65a/pkg/kubelet/cm/container_manager_linux.go#L1076

No change is being made to the container manager's repesentation of storage capacity. We are doing a "best effort" poll of cAdvisor during the node "get storage capacity" flow *if the container manager does not (yet) have storage capacity data". We are doing that in a "best effort" way because we don't want to slow down kubelet bootstrapping operations (for example, by retrying node data gathering until storage is available). That "best effort" tactic is due to review comments here. Happy to consider a more definitive solution if slowing down kubelet bootstrapping is an option. I think this PR as-is is a reasonable trade off given the undesirable current behaviors (and the complexity of the kubelet bolognese around these parts 😄).

Comment (ehashman) [reply pkg/kubelet/cm/container_manager_linux.go:1074]: Checking this over again, it's probably fine because we're returning the pointer rather than a value on error.

File: pkg/kubelet/cm/container_manager_linux.go (hunk 6 above)
Comment (ehashman) [reply pkg/kubelet/cm/container_manager_linux.go:1067]: Yes, because a refactor might accidentally have something else call this.

https://github.com/kubernetes/kubernetes/blob/588d98440706e317ca0fcc5b510285caaf161e51/pkg/kubelet/cm/container_manager_linux.go#L640-L648

also has the feature flag.

File: pkg/kubelet/cm/container_manager_linux_test.go [hunk 9]
```diff
@@ -165,3 +171,69 @@ func TestSoftRequirementsValidationSuccess(t *testing.T) {
...
+	ephemeralStorageFromCapacity := int64(2000)
+	ephemeralStorageFromCadvisor := int64(8000)
```
Comment (ehashman) [inline pkg/kubelet/cm/container_manager_linux_test.go:177]: My main remaining concern is these two values being wildly different, and the possible knock-on effects it could have on the node. But, from what I've seen they're both retrieved via cadvisor in the exact same way, so barring some wacky cadvisor issue they should be the same quantity.

**Review by ehashman — COMMENTED** [review]
LGTM modulo the missing feature flag

File: pkg/kubelet/cm/container_manager_linux.go (hunk 6 above)
Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go]: Makes sense, done. (UT updated as well)

**Comment by jackfrancis** [comment]
@cynepco3hahue @ehashman @jingxu97 based on the incorporation of review feedback this PR is ready for final review

thank you!

**Comment by cynepco3hahue** [comment]
I think it polished enough.
/lgtm

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by jackfrancis** [comment]
@jingxu97 can you give this a final review? thx!

**Comment by jackfrancis** [comment]
Pinging folks again after a while

@cynepco3hahue @ehashman @jingxu97 is this ready for a final review and merge? Shall I rebase this on top of current master to get a more current test signal?

**Comment by jackfrancis** [comment]
@Random-Liu @dchen1107 @derekwaynecarr @yujuhong @sjenning @mrunalp @klueska can I kindly request a sig-node review/approval?

**Comment by jackfrancis** [comment]
@saad-ali @thockin @jsafrane @gnufied @msau42 @xing-yang can I kindly request a sig-storage review/approval?

File: pkg/kubelet/cm/container_manager_linux.go [hunk 10]
```diff
@@ -1060,7 +1060,31 @@ func isKernelPid(pid int) bool {
...
+				// and add ephemeral-storage
+				capacityWithEphemeralStorage := v1.ResourceList{}
+				for rName, rQuant := range cm.capacity {
+					capacityWithEphemeralStorage[rName] = rQuant
+				}
+				capacityWithEphemeralStorage[v1.ResourceEphemeralStorage] = cadvisor.EphemeralStorageCapacityFromFsInfo(rootfs)[v1.ResourceEphemeralStorage]
+				return capacityWithEphemeralStorage
+			}
+		}
+	}
```
Comment (jingxu97) [inline pkg/kubelet/cm/container_manager_linux.go:1087]: Before, to read cm.capacity, there is a read lock. The lock is no longer needed?

Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go:1087]: where is that read lock? I'm not aware of it

Comment (jingxu97) [reply pkg/kubelet/cm/container_manager_linux.go:1087]: not directly related to your change, but is it possible that cm.capacity is set while at the same time it is being retrieved?

File: pkg/kubelet/cm/container_manager_linux.go (hunk 6 above)
Comment (jingxu97) [reply pkg/kubelet/cm/container_manager_linux.go]: just confirm retry is not needed here? I still see some value of retrying in no inconsistent data will be returned from cadvisor?

File: pkg/kubelet/cm/container_manager_linux.go (hunk 10 above)
Comment (jingxu97) [reply pkg/kubelet/cm/container_manager_linux.go:1087]: > where is that read lock? I'm not aware of it

https://github.com/kubernetes/kubernetes/pull/48567#diff-c07d343a8d459721656cf7ddacda71506bde01a5cac288d15a4aba6bfc9a1cae

it got removed from here https://github.com/kubernetes/kubernetes/pull/59769/files

Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go:1087]: That is certainly possible (this change would definitely not change that behavior if that's permitted). The important thing is that this change doesn't mutate `cm.capacity` in any way. If the `capacity` field is not present at the time that this `GetCapacity` method is invoked, then we attempt (best-effort) to retrieve the storage capacity of the root filesystem manually, and if we are able, we return *that*.

Thanks for the review, hope that makes sense!

Comment (jingxu97) [reply pkg/kubelet/cm/container_manager_linux.go:1087]: the last thing I want to confirm retry is not needed here? I still see some value of retrying, especially if no inconsistent data will be returned from cadvisor?
What is the concern of retry?

Comment (jackfrancis) [reply pkg/kubelet/cm/container_manager_linux.go:1087]: If you read the prior thread history (I know it's long!) the concern was the possible startup delay added by doing retries in this boostrap code surface area, and any undesirable side-effects that may occur. Doing a cAdvisor lookup in this particular place is already imposing a very tiny delay, and any more was seen as too much risk.

The above was the review consensus as far as I interpreted it. I originally advocated for retries, but my tests without the retry proved that the particular symptom I was trying to fix was equivalently addresses without any retries.

**Comment by reylejano** [comment]
/milestone clear
Release Managers are cutting 1.23.0-rc.0 and creating the `release-1.23` branch

**Comment by dims** [comment]
@msau42 @xing-yang looks like there's a request for sig-storage folks to look/review this PR.

**Comment by jsafrane** [comment]
/assign @Random-Liu @sjenning
for approval

**Comment by jackfrancis** [comment]
@Random-Liu @sjenning can you kindly take a look at this PR for final approval/merge? thanks!

**Comment by jackfrancis** [comment]
Another issue related to what this PR does:

https://github.com/kubernetes/kubernetes/issues/108700

**Comment by pacoxu** [comment]
/check-cla
ping @mrunalp  @tallclair for approval

**Comment by jackfrancis** [comment]
gentle ping @mrunalp @tallclair

**Review by mrunalp — APPROVED** [review]

**Comment by jackfrancis** [comment]
looks like I need to rebase and adapt some UT stuff to deal w/ changes since my last commit, stand by @mrunalp @pacoxu

**Comment by jackfrancis** [comment]
Looks like I encountered https://github.com/kubernetes/kubernetes/issues/107414

/retest

**Comment by pacoxu** [comment]
/lgtm
There seems to be no further change from the last commit.

**Comment by jackfrancis** [comment]
> /lgtm
> There seems to be no further change from the last commit.

Yes, just had to clean up `gofmt` stuff after updating UT code to use replacement mock libraries introduced in the last few months. I'll try to retest my way through various flakes here. Thanks for your responsiveness!

**Comment by jackfrancis** [comment]
thx again @mrunalp for the approval merry-go-round 🙏

**Comment by pacoxu** [comment]
This was approved before the code freeze, but not merged for CI failures. 😂
@ehashman should this be included in 1.24?
