### PR TITLE
Check nodeInfo before ecache predicate

### LINKED ISSUE #63427: Panic during TestTaintNodeByCondition integration test
[Panic](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/61976/pull-kubernetes-integration/9691/) in the `TestTaintNodeByCondition` integration test in an seemingly unrelated PR https://github.com/kubernetes/kubernetes/pull/61976. 

```
panic: runtime error: invalid memory address or nil pointer dereference
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
/usr/local/go/src/runtime/panic.go:502 +0x229
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/meta.go:133
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/core/equivalence_cache.go:89 +0xc4
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go:512 +0x1de
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go:353 +0x19a
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:47 +0x96
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:43 +0x10b
```

@kubernetes/sig-scheduling-bugs

### PR DESCRIPTION
**Pull request by resouer**
**What this PR does / why we need it**:

There's chances during test when nodeInfo is nil which may cause ecache predicate fail with nil pointer.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #63427

**Special notes for your reviewer**:

Not sure how to reproduce the original issue yet. i.e. why and when `nodeInfo` will become nil in tests is not clear to me, that's why I label it as WIP.

cc @bsalamat who may have more inputs.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by k82cn** [comment]
> why and when nodeInfo will become nil in tests is not clear to me, that's why I label it as WIP.

The nodeInfo without node was created when node added into cache after pod bind.

**Comment by resouer** [comment]
@k82cn But I am not sure why this happen to `TestTaintNodeByCondition`? This block me to reproduce the case right now.

File: pkg/scheduler/core/equivalence_cache.go [hunk 1]
```diff
@@ -86,6 +87,12 @@ func (ec *EquivalenceCache) RunPredicate(
 ) (bool, []algorithm.PredicateFailureReason, error) {
 	ec.mu.Lock()
 	defer ec.mu.Unlock()
+
+	if nodeInfo == nil || nodeInfo.Node() == nil {
```
Comment (yastij) [inline pkg/scheduler/core/equivalence_cache.go]: @resouer - do we know why this is nil only sometimes ?

Comment (resouer) [reply pkg/scheduler/core/equivalence_cache.go]: I have some theory, but would like to verify it somehow tomorrow :/

**Comment by ravisantoshgudimetla** [comment]
> @k82cn Yeah, but I am not sure why this happen to TestTaintNodeByCondition. Or it may apply to other tests as well ...

It can happen to other tests as well. 
@resouer - The change seems non-destructive to me and worth pushing forward. Also this makes code much more defensive and less brittle.

File: pkg/scheduler/core/equivalence_cache.go [hunk 2]
```diff
@@ -86,6 +87,12 @@ func (ec *EquivalenceCache) RunPredicate(
...
+		// This may happen during tests.
+		return false, []algorithm.PredicateFailureReason{}, fmt.Errorf("nodeInfo is nil or node is invalid")
```
Comment (misterikkit) [inline pkg/scheduler/core/equivalence_cache.go]: I think this should return false, nil, fmt.Errorf(...), but I know that breaks tests today.

**Review by misterikkit — COMMENTED** [review]
/lgtm
this change seems perfectly reasonable to me.

File: pkg/scheduler/core/equivalence_cache.go (hunk 1 above)
Comment (bsalamat) [reply pkg/scheduler/core/equivalence_cache.go]: In some of our tests, nodeInfo.Node() is nil. It is expected.
