### PR TITLE
cpumanager: uncorecache alignment for odd integer cpus

### LINKED ISSUE #131610: Does the cpu static policy option of PreferAlignByUncoreCache only support even CPU counts?
### What happened?

When I assign an odd number of CPUs and less than a full uncorecache, this policy cannot assign the cpu properly. I do not know if this option only support even number CPU by design or it is a bug.

For example, 1core:2cpus, cache0: 0-8 cpus. If I assign 7cpus in the pod spec, `takePartialUncore` cannot take any cpus.

The below method only assign even number CPU during SMT enabled scenario.

https://github.com/kubernetes/kubernetes/blob/2ac0bdf360cf2529a3675c7012d0bf415e1051f3/pkg/kubelet/cm/cpumanager/cpu_assignment.go#L558-L579
 

### What did you expect to happen?

assign 7cpus in cache0.

### How can we reproduce it (as minimally and precisely as possible)?

cache0: 0-8 cpus, SMT enabled. And then using  `takePartialUncore` to acquire 7 cpus, it will fail.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.32
</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by wongchar**
#### What type of PR is this?
/kind bug
/kind cleanup

#### What this PR does / why we need it:

Fix for `prefer-align-cpus-by-uncorecache` CPUManager option that allows odd-integer cpu allocation for containers on SMT/hyperthreading enabled processors.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/131610

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4800-cpumanager-split-uncorecache
```

### CODE REVIEW

File: pkg/kubelet/cm/cpumanager/cpu_assignment.go [hunk 1]
```diff
@@ -556,13 +556,26 @@ func (a *cpuAccumulator) takeFullUncore() {
...
 	freeCPUs := a.details.CPUsInCores(freeCores.UnsortedList()...)
 
+	// when SMT/hyperthread is enabled, remove the last cpu if cpu requirement is an odd integer value
+	// and if the number of free virtual cpus are greater than the needed cpus
+	if a.numCPUsNeeded%2 != 0 && a.topo.CPUsPerCore() > 1 {
+		// sort the freeCPUs available
+		sortFreeCPUs := freeCPUs.List()
+		// if all threads are available on each core, remove the last free cpu to satisfy cpu requirement
+		if len(sortFreeCPUs) > a.numCPUsNeeded {
+			sortFreeCPUs = sortFreeCPUs[:freeCPUs.Size()-1]
```
Comment (ffromani) [inline pkg/kubelet/cm/cpumanager/cpu_assignment.go:579]: ok, we can enter here iff the accumulator is not satisfied after taking a full uncore group, so `freeCPUs.Size()` can't be < 1.
This seems to be covered by tests (line 1730 in the tests file) right?

File: pkg/kubelet/cm/cpumanager/cpu_assignment.go [hunk 2]
```diff
@@ -556,13 +556,26 @@ func (a *cpuAccumulator) takeFullUncore() {
...
 	// determine the M number of free cpus (virtual cpus) that correspond with the free cores
 	freeCores := a.details.CoresNeededInUncoreCache(numCoresNeeded, uncoreID)
 	freeCPUs := a.details.CPUsInCores(freeCores.UnsortedList()...)
 
+	// when SMT/hyperthread is enabled, remove the last cpu if cpu requirement is an odd integer value
+	// and if the number of free virtual cpus are greater than the needed cpus
+	if a.numCPUsNeeded%2 != 0 && a.topo.CPUsPerCore() > 1 {
+		// sort the freeCPUs available
+		sortFreeCPUs := freeCPUs.List()
+		// if all threads are available on each core, remove the last free cpu to satisfy cpu requirement
```
Comment (ffromani) [inline pkg/kubelet/cm/cpumanager/cpu_assignment.go]: What could be more helpful is a short comment to describe why the last core can be dropped, replacing or augmenting the current comment

File: pkg/kubelet/cm/cpumanager/cpu_assignment.go [hunk 3]
```diff
@@ -556,13 +556,26 @@ func (a *cpuAccumulator) takeFullUncore() {
...
+	// determine the number of cores needed whether SMT/hyperthread is enabled or disabled
+	numCoresNeeded := (a.numCPUsNeeded + a.topo.CPUsPerCore() - 1) / a.topo.CPUsPerCore()
 
 	// determine the N number of free cores (physical cpus) within the UncoreCache, then
 	// determine the M number of free cpus (virtual cpus) that correspond with the free cores
 	freeCores := a.details.CoresNeededInUncoreCache(numCoresNeeded, uncoreID)
 	freeCPUs := a.details.CPUsInCores(freeCores.UnsortedList()...)
 
+	// when SMT/hyperthread is enabled, remove the last cpu if cpu requirement is an odd integer value
+	// and if the number of free virtual cpus are greater than the needed cpus
```
Comment (ffromani) [inline pkg/kubelet/cm/cpumanager/cpu_assignment.go]: comments should preferably describe the why (see also line 572 below)

File: pkg/kubelet/cm/cpumanager/cpu_assignment.go [hunk 4]
```diff
@@ -556,13 +556,26 @@ func (a *cpuAccumulator) takeFullUncore() {
...
+	if a.numCPUsNeeded%2 != 0 && a.topo.CPUsPerCore() > 1 {
+		// sort the freeCPUs available
```
Comment (ffromani) [inline pkg/kubelet/cm/cpumanager/cpu_assignment.go]: ditto, feel free to merge or remove these comments

**Review by ffromani — COMMENTED** [review]
provisional LGTM. Some minor comments about comments (no pun intended). I will need to deep dive in the test code, but test cases seems to be sufficient for the scope of the change.

File: pkg/kubelet/cm/cpumanager/cpu_assignment.go (hunk 1 above)
Comment (wongchar) [reply pkg/kubelet/cm/cpumanager/cpu_assignment.go:579]: correct. Updated the comments, please let me know if still unclear

**Comment by ffromani** [comment]
/triage accepted
/priority important-longterm

during the KEP review we agreed this is needed for beta

File: pkg/kubelet/cm/cpumanager/cpu_assignment.go (hunk 1 above)
Comment (ffromani) [reply pkg/kubelet/cm/cpumanager/cpu_assignment.go:579]: thanks, the comment helps. If you resubmit, let's rephrase to help the reader to remember that
`if we are in this function, the accumulator is not satisfied after takeFullUncore, so freeCPUs.Size() can't be < 1`

File: pkg/kubelet/cm/cpumanager/cpu_assignment.go [hunk 5]
```diff
@@ -556,13 +556,28 @@ func (a *cpuAccumulator) takeFullUncore() {
...
 	freeCores := a.details.CoresNeededInUncoreCache(numCoresNeeded, uncoreID)
 	freeCPUs := a.details.CPUsInCores(freeCores.UnsortedList()...)
 
+	// when SMT/hyperthread is enabled and remaining cpu requirement is an odd integer value:
+	// sort the free CPUs that were determined based on the cores that have available cpus.
+	// if the amount of free cpus is greather than the cpus needed, we can drop the last cpu
+	// since the odd integer request will only require one out of the two free cpus that
+	// correspond to the last core
+	if a.numCPUsNeeded%2 != 0 && a.topo.CPUsPerCore() > 1 {
+		sortFreeCPUs := freeCPUs.List()
```
Comment (ffromani) [inline pkg/kubelet/cm/cpumanager/cpu_assignment.go:575]: question for my understanding:  I noticed that in this function we use naive integer sorting. We do here explicitly, and we do inside CoresNeededInUncoreCache, which is called only here in `takePartialUncore`. In other place, we sort cores according to clear topological reasons. Even if it is kinda of tangential, maybe you can comment about why naive integer sorting is sufficient here?

File: pkg/kubelet/cm/cpumanager/policy_static_test.go [hunk 6]
```diff
@@ -1679,6 +1679,169 @@ func TestStaticPolicyAddWithUncoreAlignment(t *testing.T) {
...
+				makeMultiContainerPod(
+					[]struct{ request, limit string }{}, // init container
+					[]struct{ request, limit string }{ // app container
+						{"5000m", "5000m"}, // full uncore cache worth of cpus
+					},
+				),
+				"with-single-container",
+			),
+			expCPUAlloc: true,
+			expCSet:     cpuset.New(8, 9, 10, 11, 12),
```
Comment (ffromani) [inline pkg/kubelet/cm/cpumanager/policy_static_test.go:1704]: these are taken from uncore 1, avoiding partially filled uncore 0 (follows)

File: pkg/kubelet/cm/cpumanager/policy_static_test.go [hunk 7]
```diff
@@ -1679,6 +1679,169 @@ func TestStaticPolicyAddWithUncoreAlignment(t *testing.T) {
...
+				makeMultiContainerPod(
+					[]struct{ request, limit string }{}, // init container
+					[]struct{ request, limit string }{ // app container
+						{"3000m", "3000m"},
+					},
+				),
+				"with-single-container",
+			),
+			expCPUAlloc: true,
+			expCSet:     cpuset.New(2, 3, 66),
```
Comment (ffromani) [inline pkg/kubelet/cm/cpumanager/policy_static_test.go:1727]: (continued) but these seems to come from uncore 0. this is because we can take the full reminder of a partially allocated uncore (size=8, 4 taken, 4 free, requested < free), vs previously we would have needed to spill over a different uncore group. Is my understanding right?

File: pkg/kubelet/cm/cpumanager/policy_static_test.go [hunk 8]
```diff
@@ -1679,6 +1679,169 @@ func TestStaticPolicyAddWithUncoreAlignment(t *testing.T) {
...
+				makeMultiContainerPod(
+					[]struct{ request, limit string }{}, // init container
+					[]struct{ request, limit string }{ // app container
+						{"4000m", "4000m"},
+					},
+				),
+				"with-single-container",
+			),
+			expCPUAlloc: true,
+			expCSet:     cpuset.New(4, 5, 68, 69),
```
Comment (ffromani) [inline pkg/kubelet/cm/cpumanager/policy_static_test.go:1774]: it fits in uncore group 0, and full-pcpus-only is not explicitly enabled. But SMT is. So why we allocate from uncore group 1, because we prefer even-allocation vs leaving a uncore group with odd-number of allocated cores. Right?
If so I'm thinking, but really, I'm wondering, if this behavior should be driven more by `full-pcpus-only` rather than SMT enablement or not. I'm specifically focusing on the _preference_ side. Regardless of the `full-pcpus-only` status, the cpumanager should allocate taking into account LLC boundaries (obviously with `PreferAlignByUnCoreCacheOption` enabled)

File: pkg/kubelet/cm/cpumanager/policy_static_test.go [hunk 9]
```diff
@@ -1679,6 +1679,169 @@ func TestStaticPolicyAddWithUncoreAlignment(t *testing.T) {
...
+				makeMultiContainerPod(
+					[]struct{ request, limit string }{}, // init container
+					[]struct{ request, limit string }{ // app container
+						{"11000m", "11000m"},
+					},
+				),
+				"with-single-container",
+			),
+			expCPUAlloc: true,
+			expCSet:     cpuset.New(2, 65, 66, 4, 5, 6, 7, 68, 69, 70, 71), // full uncore 1 and partial uncore 0
```
Comment (ffromani) [inline pkg/kubelet/cm/cpumanager/policy_static_test.go:1797]: fine, 1 full free uncore and allocate the rest from a partially allocated uncore.

File: test/e2e_node/cpumanager_test.go [hunk 10]
```diff
@@ -862,6 +951,135 @@ var _ = SIGDescribe("CPU Manager", ginkgo.Ordered, framework.WithSerial(), featu
 			})
 		})
 
+		// please avoid nesting `BeforeEach` as much as possible. Ideally avoid completely.
+		ginkgo.Context("SMT Alignment and distribution across NUMA", ginkgo.Label("smt-alignment", "prefer-align-cpus-by-uncore-cache"), func() {
```
Comment (ffromani) [inline test/e2e_node/cpumanager_test.go]: is the description right?

**Review by ffromani — COMMENTED** [review]
partial review, still need to process the e2e tests. No major issues but quite few questions inside, mostly for my understanding. I think we are in a good shape.

File: pkg/kubelet/cm/cpumanager/policy_static_test.go (hunk 8 above)
Comment (wongchar) [reply pkg/kubelet/cm/cpumanager/policy_static_test.go:1774]: Yes, this was my intention. If the application requires uncore cache alignment for performance uplift, it will be likely that SMT-misalignment will have some performance impact.

From user engagements, the desire is to get the benefit of uncore cache alignment and fullpcpus, without being restricted in CPU sizes (odd-integers). On SMT-enabled processors, users will want to deploy Guaranteed QoS containers of sizes 1 or 3 CPUs that aren't reliant on uncore alignment, mixed in with containers that will rely on uncore cache alignment and fullpcpus. Currently we do not have a way to enable features to specific containers since the features will apply to all Guaranteed QoS pods.

Current `prefer-align-cpus-by-uncore-cache` implementation and fullpcpus option prevent users to deploy mixed sizes (meaning odd-integer CPUs). This added fix helps to keep SMT and Uncore alignment by segregating odd-integer and even-integer container CPUs on different uncore caches as much as possible, while allowing "odd-integer CPU containers" to be in the mix.

File: pkg/kubelet/cm/cpumanager/policy_static_test.go (hunk 7 above)
Comment (wongchar) [reply pkg/kubelet/cm/cpumanager/policy_static_test.go:1727]: That's correct

- In the first mentioned case, 4 of 8 cpus of "uncore 0" are unallocatable. The requirement is 5 CPUs so the CPUs are all allocated from "uncore 1".
- In the second mentioned case, 4 of 8 cpus of "uncore 0" are unallocatable, and the requirement is 3 cpus which still fits on "uncore 0".

File: pkg/kubelet/cm/cpumanager/policy_static_test.go (hunk 8 above)
Comment (ffromani) [reply pkg/kubelet/cm/cpumanager/policy_static_test.go:1774]: ok, fair enough for now.

**Review by ffromani — COMMENTED** [review]
e2e tests look reasonnable. I think we can improve and expand, but I'd rather iterate over a starting point that add code to unmerged PR.

**Comment by ffromani** [comment]
the PR can be merged. let's run the final check using pre-merge jobs and we can move forward.

I think we should address these followup for beta scope:
1. nit: https://github.com/kubernetes/kubernetes/pull/131850#discussion_r2178037226
2. question/improvement: is integer sorting fine? https://github.com/kubernetes/kubernetes/pull/131850#discussion_r2178058256
3. review e2e test coverage, think about missing cases. The current coverage is minimal. I would encourage adding more cases (e.g. multiple containers)

**Comment by ffromani** [comment]
serial manager failure flakes addressed by https://github.com/kubernetes/kubernetes/pull/132811

**Comment by ffromani** [comment]
/lgtm

the pre-pull merge failures look irrelevant or known and addressed by open PR.
I will do another check before approve though.

File: pkg/kubelet/cm/cpumanager/cpu_assignment.go (hunk 5 above)
Comment (wongchar) [reply pkg/kubelet/cm/cpumanager/cpu_assignment.go:575]: added comment:
"we sort freeCPUs to ensure we pack virtual cpu allocations, meaning we allocate whole core's worth of cpus as much as possible to reduce smt-misalignment"

File: test/e2e_node/cpumanager_test.go (hunk 10 above)
Comment (wongchar) [reply test/e2e_node/cpumanager_test.go]: thanks for catching!

**Comment by wongchar** [comment]
@ffromani apologies for the delay, just returned from vacation. Believe I addressed all the added comments but let me know if I missed anything.
I'll add some more e2e test cases asap

File: pkg/kubelet/cm/cpumanager/cpu_assignment_test.go [hunk 11]
```diff
@@ -685,7 +685,7 @@ func TestTakeByTopologyNUMAPacked(t *testing.T) {
 			cpuset.New(1, 2, 3, 4, 5, 7, 8, 9, 10, 11),
 			1,
 			"",
-			cpuset.New(2),
+			cpuset.New(1),
```
Comment (ffromani) [inline pkg/kubelet/cm/cpumanager/cpu_assignment_test.go:688]: why this change?

**Comment by ffromani** [comment]
/lgtm

thanks @wongchar, this PR seems good enough to merge, we can move forward
I'll approve once CI is green and/or all errors have a plausible explanation. Let's see what CI tell us.

**Comment by ffromani** [comment]
`kubernetes-node-kubelet-serial-containerd` -> "ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - [e2-standard-2, nvidia-tesla-t4] features are not compatible for creating instance. "

**Comment by ffromani** [comment]
`kubernetes-node-kubelet-serial-cpu-manager` -> ```
E2eNode Suite: [It] [sig-node] CPU Manager [Serial] [Feature:CPUManager] when checking the CFS quota management can be disabled should not disable for guaranteed pod with exclusive CPUs assigned expand_more
E2eNode Suite: [It] [sig-node] CPU Manager [Serial] [Feature:CPUManager] when checking the CFS quota management can be disabled should not enforce with multiple containers only in the container with exclusive CPUs expand_more
E2eNode Suite: [It] [sig-node] CPU Manager [Serial] [Feature:CPUManager] when checking the CFS quota management can be disabled should not disable for guaranteed pod with exclusive CPUs assigned expand_more
E2eNode Suite: [It] [sig-node] CPU Manager [Serial] [Feature:CPUManager] when checking the CFS quota management can be disabled should not enforce with multiple containers only in the container with exclusive CPUs expand_more
```
known issue fixed by https://github.com/kubernetes/kubernetes/pull/132811

**Comment by ffromani** [comment]
/lgtm

will approve and merge once the last pending comment about the unit test change is addressed/answered

File: pkg/kubelet/cm/cpumanager/cpu_assignment_test.go (hunk 11 above)
Comment (wongchar) [reply pkg/kubelet/cm/cpumanager/cpu_assignment_test.go:688]: This was a test artifact from the original alpha PR that tests 1CPU on a monolithic uncore cache with hyperthreading enabled. 

I must have overlooked it because in the past I mistakenly assumed full-pcpus-only would be enabled whenever smt/hyperthreading was enabled with the uncore-cache alignment. See my previous comment: https://github.com/kubernetes/kubernetes/pull/131850#discussion_r2181081046

There was never a forced enablement with full-pcpus-only because the previous takePartialUncore worked for odd-interger cpu requests when SMT/hyperthreading was disabled. 

Looking back, without the ability to handle odd-integer CPUs on smt/hyperthread-enabled cases (the fix in this PR), the accumulator uses takeRemainingCPUs and is not sorted properly. This PR will fix odd-integer CPU allocations so that we still follow a "packed" method on split and monolithic uncore caches.

Comment (ffromani) [reply pkg/kubelet/cm/cpumanager/cpu_assignment_test.go:688]: fair enough, thanks for elaborating.

**Comment by ffromani** [comment]
/approve

all comments addressed, we can move forward. Let's watch how the test run goes and let's think about how to improve the coverage further, as discussed.
