### PR TITLE
Don't log irrelevant zone hints message on no endpoints

### LINKED ISSUE #132678: kube-proxy incorrectly logs "Ignoring same-zone topology hints" when there are no endpoints
### What happened?

We recently upgraded our EKS cluster from 1.32 to 1.33, and noticed an unusually high volume of logs coming from kube-proxy like this:
```
Ignoring same-zone topology hints for service since no hints were provided for zone
```

We have not enabled zone-aware routing or hints (either by .spec.trafficDistribution or by the older annotation) for any service and were surprised to see this log message. The service has no endpoints in the endpoint slice.

<details>
<summary> Example service YAML</summary>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: default
spec:
  clusterIP: 10.10.129.215
  clusterIPs:
  - 10.10.129.215
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

</details>

<details>
<summary> Example endpointslice YAML</summary>

```yaml
addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints: null
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-10-29T09:45:37Z"
  creationTimestamp: "2024-10-11T12:46:31Z"
  generateName: my-service-
  generation: 397
  labels:
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
  name: my-service-qwq6l
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: my-service
    uid: 2c3edd43-8041-4aa6-ac2b-8e5508d7c6ff
  resourceVersion: "5958818965"
  uid: b485a7f7-6363-4b5f-b3f2-d6eb394ac034
ports: null
```

</details>

Looking through [topology.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/topology.go#L195), it looks like we intend to log this line when all endpoints in the endpoint slice have zone hints, and the zone parameter is not empty. However, since we initialise allEndpointsHaveZoneHints to true then loop through the endpoints to set it to false, we will inadvertently log this line for any endpoint slices that are empty.

I think the simple fix is to exit `topologyModeFromHints` early and return an empty string if no endpoints are found. I am happy to contribute this patch

### What did you expect to happen?

I expect to not see this log line for empty endpoint slices

### How can we reproduce it (as minimally and precisely as possible)?

I have not tried it, but I presume you could create a service with no endpoints and see that kube-proxy logs this log line

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.33.1-eks-1fbb135
```

</details>

### Cloud provider

<details>
AWS/EKS 1.33.1
</details>

### OS version

<details>

Bottlerocket OS 1.41.0 (aws-k8s-1.33)

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by milesbxf**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

See https://github.com/kubernetes/kubernetes/issues/132678 - kube-proxy is currently logging erroneous messages about ignoring topology hints when an endpointslice is empty. This short circuits the function and returns the default traffic distribution if there are no endpoints.

#### Which issue(s) this PR is related to:

Fixes https://github.com/kubernetes/kubernetes/issues/132678

#### Does this PR introduce a user-facing change?

```release-note
Fixes 1.33 regression with spammy log messages
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by milesbxf** [comment]
cc. @danwinship as it looks like you last touched this code

**Comment by aojea** [comment]
This is called from https://github.com/kubernetes/kubernetes/blob/95bff1b249e048b7e36ae857d7478dd2ac05346a/pkg/proxy/topology.go#L44 so I wonder if we want to be also defensive there and return faster if there are no endpoints

/assign @danwinship

**Comment by danwinship** [comment]
Yeah, it would probably be good to just bail out of CategorizeEndpoints early if there aren't any endpoints.

But we should still fix `topologyModeFromHints`... Or at least, if it's going to give the wrong answer for 0 endpoints, we should document that, but it seems dumb to document it rather than fixing it.

File: pkg/proxy/topology.go [hunk 1]
```diff
@@ -153,6 +153,11 @@ func CategorizeEndpoints(endpoints []Endpoint, svcInfo ServicePort, nodeName str
 //     hinted for this node's zone, then it returns "PreferSameZone".
 //   - Otherwise it returns "" (meaning, no topology / default traffic distribution).
 func topologyModeFromHints(svcInfo ServicePort, endpoints []Endpoint, nodeName, zone string) string {
+	if len(endpoints) == 0 {
+		// traffic distribution is not applicable if there are no endpoints
```
Comment (danwinship) [inline pkg/proxy/topology.go]:
```suggestion
		// The code below assumes at least 1 endpoint; if there are no endpoints,
		// there are no hints.
```

**Review by danwinship — COMMENTED** [review]
Also, this needs an addition to the unit test in `topology_test.go`

**Comment by milesbxf** [comment]
Unit test added (thanks also for the clarification suggestion on the comment)

> Yeah, it would probably be good to just bail out of CategorizeEndpoints early if there aren't any endpoints.
> 
> But we should still fix `topologyModeFromHints`... Or at least, if it's going to give the wrong answer for 0 endpoints, we should document that, but it seems dumb to document it rather than fixing it.

Happy to add this too - what are the expected return values if there are no endpoints? Would `return nil, nil, nil, false` do the trick (empty endpoints, hasAnyEndpoints=false)?

**Comment by aojea** [comment]
/ok-to-test

please squash the commits , and you can add a separate commit with the `CategorizeEndpoints` changes

> what are the expected return values if there are no endpoints? Would return nil, nil, nil, false do the trick (empty endpoints, hasAnyEndpoints=false)?

those are named variables so you can just `return`

File: pkg/proxy/topology_test.go [hunk 2]
```diff
@@ -390,6 +390,13 @@ func TestCategorizeEndpoints(t *testing.T) {
 		clusterEndpoints: nil,
 		localEndpoints:   sets.New[string]("10.0.0.1:80"),
 		allEndpoints:     sets.New[string]("10.0.0.1:80"),
+	}, {
+		name:             "empty cluster endpoints when no service endpoints exist",
```
Comment (danwinship) [inline pkg/proxy/topology_test.go]: it's empty local endpoints too. I'd just say "no endpoints when no service endpoints exist"

File: pkg/proxy/topology_test.go [hunk 3]
```diff
@@ -390,6 +390,13 @@ func TestCategorizeEndpoints(t *testing.T) {
...
+		serviceInfo:      &BaseServicePortInfo{},
+		endpoints:        nil,
+		clusterEndpoints: sets.New[string](),
+		localEndpoints:   nil,
```
Comment (danwinship) [inline pkg/proxy/topology_test.go]: Ick. That's awkward that the test case ends up accidentally distinguishing "empty set" and "nil" (and therefore needs to know that we return an empty set for one and nil for the other here).

If you change the checking code to do:

```diff
@@ -408 +408 @@ func TestCategorizeEndpoints(t *testing.T) {
-                       if tc.clusterEndpoints == nil && clusterEndpoints != nil {
+                       if tc.clusterEndpoints == nil && len(clusterEndpoints) != 0 {
@@ -417 +417 @@ func TestCategorizeEndpoints(t *testing.T) {
-                       if tc.localEndpoints == nil && localEndpoints != nil {
+                       if tc.localEndpoints == nil && len(localEndpoints) != 0 {
```

then you can just have `clusterEndpoints: nil,` here

File: pkg/proxy/topology.go [hunk 4]
```diff
@@ -26,10 +26,12 @@ import (
...
 //
 //   - The service's usable Cluster-traffic-policy endpoints (taking topology into account, if
-//     relevant). This will be nil if the service does not ever use Cluster traffic policy.
+//     relevant). This will be nil if the service does not ever use Cluster traffic policy, or
+//     if the set of endpoints passed in is empty.
 //
 //   - The service's usable Local-traffic-policy endpoints. This will be nil if the
-//     service does not ever use Local traffic policy.
+//     service does not ever use Local traffic policy, or if the set of endpoints passed in is
+//     empty.
```
Comment (danwinship) [inline pkg/proxy/topology.go]: You don't need to change the documentation. It says it returns the "usable Cluster-traffic-policy endpoints" and "usable Local-traffic-policy endpoints", and obviously if there are no endpoints to begin with, then there won't be any usable ones.

(More generally, the short-circuit code here is explicitly intended to not change the observable behavior of the function, so we wouldn't expect it to require a documentation change.)

File: pkg/proxy/topology.go [hunk 5]
```diff
@@ -42,6 +44,12 @@ import (
 // Serving-Terminating endpoints (independently for Cluster and Local) if no Ready
 // endpoints are available.
 func CategorizeEndpoints(endpoints []Endpoint, svcInfo ServicePort, nodeName string, nodeLabels map[string]string) (clusterEndpoints, localEndpoints, allReachableEndpoints []Endpoint, hasAnyEndpoints bool) {
+
+	if len(endpoints) == 0 {
```
Comment (danwinship) [inline pkg/proxy/topology.go:45]: (kill the blank line before this)

**Review by danwinship — COMMENTED** [review]
looks good, just nitpicks

File: pkg/proxy/topology_test.go (hunk 3 above)
Comment (milesbxf) [reply pkg/proxy/topology_test.go]: Good catch - I decided to do away with the nil checks entirely and consistently make the test check for slice length, since that is the intent of the checks (and not whether something is nil or not)

**Comment by milesbxf** [comment]
> looks good, just nitpicks

Thanks - I think I've addressed everything here + squashed

File: pkg/proxy/topology.go [hunk 6]
```diff
@@ -26,7 +26,8 @@ import (
 // CategorizeEndpoints returns:
 //
 //   - The service's usable Cluster-traffic-policy endpoints (taking topology into account, if
-//     relevant). This will be nil if the service does not ever use Cluster traffic policy.
+//     relevant). This will be nil if the service does not ever use Cluster traffic policy, or
+//     if the set of endpoints passed in is empty.
```
Comment (danwinship) [inline pkg/proxy/topology.go]: revert this doc change too please. then it's good to go

**Review by danwinship — APPROVED** [review]

File: pkg/proxy/topology.go (hunk 6 above)
Comment (milesbxf) [reply pkg/proxy/topology.go]: Done

**Comment by aojea** [comment]
/lgtm

/test pull-kubernetes-e2e-gce

Does not look related

**Comment by runningman84** [comment]
It would be great to also have this included in the 1.33.x release because providers like AWS and other charges you for log messages. This issue will burn a lot of money for all customers... we got thousands of messages for this per minute even for small sized clusters...

**Comment by a7i** [comment]
Can we also cherry-pick this for 1.32?

**Comment by danwinship** [comment]
The bug shouldn't exist in 1.32... it was because of a change in 1.33.

**Comment by Rohlik** [comment]
The problem persists even on v1.35.5 (EKS) 😞:  
```
$ k logs -n kube-system  kube-proxy-4mdpd  | grep "Ignoring same-zone"| wc -l
17520
```

**Comment by danwinship** [comment]
@Rohlik if you believe you have a bug, please open a new issue. Comments on old closed PRs will just get lost.

(Note that whatever you are seeing, it is probably not actually the same bug as was fixed here, and you should provide more details of the exact message that is being logged; there are 3 different log messages that start with "Ignoring same-zone".)

**Comment by Rohlik** [comment]
@danwinship You were right, our spam from kube-proxy has different root cause, but it is already fixed in `main` - https://github.com/kubernetes/kubernetes/pull/136743.
