### PR TITLE
Remove PersistentVolumeLabel admission plugin

### LINKED ISSUE #124504: PersistentVolumeLabel admission blocks PVs on Azure + vSphere
### What happened?

In 1.30, the PersistentVolumeLabel admission plugin blocks creation of in-tree AzureDisk and vSphere PVs:

```
persistentvolumes "pvc-2d9b3999-f60d-4797-923f-210f1f75025d" is forbidden:
error querying AzureDisk volume pvc-2d9b3999-f60d-4797-923f-210f1f75025d:
unable to build Azure cloud provider for AzureDisk
```

The reason is that the cloud provider was removed (https://github.com/kubernetes/kubernetes/pull/122857), but the admission plugin still calls GetCloudProvider there, which fails: https://github.com/kubernetes/kubernetes/blob/646fbe6d0a3fa1a100d90a429f039324de9c8138/plugin/pkg/admission/storage/persistentvolume/label/admission.go#L285

### What did you expect to happen?

The PV should be admitted + created.

### How can we reproduce it (as minimally and precisely as possible)?

Enable PersistentVolumeLabel admission plugin. For example, when running local-up-cluster.sh:
```
ALLOW_PRIVILEGED=true ENABLE_ADMISSION_PLUGINS="NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,Priority,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,NodeRestriction,PersistentVolumeLabel" bash -x hack/local-up-cluster.sh
```

Create AzureDisk PV on _any_ 1.30 cluster, you don't need Azure cloud:

```
kubectl create -f <<EOF
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvol
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  azureDisk:
    diskName: test2.vhd
    diskURI: https://someacount.blob.core.windows.net/vhds/test2.vhd
EOF
```

### Anything else we need to know?

/sig storage
/priority important-soon

### Kubernetes version

<details>

Today's master
```console
$ kubectl version
Server Version: v1.31.0-alpha.0.24+9791f0d1f39f3f
```

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

_No response_

### Install tools

<details>
local-up-cluster.sh
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by jsafrane**
#### What type of PR is this?
/kind bug
/kind regression

#### What this PR does / why we need it:
Remove useless admission plugin.
    
* It has been deprecated for years.
* All in-tree cloud providers were removed, so the admission plugin does not have
      any way to get PV labels.
    * Since Azure and vSphere cloud providers are removed and this admission still tries to use them, this fixes #124504
* There is a replacement in https://github.com/kubernetes-sigs/cloud-pv-admission-labeler

```release-note
Action required: Removed admission plugin PersistentVolumeLabel. Please use https://github.com/kubernetes-sigs/cloud-pv-admission-labeler instead if you need a similar functionality.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: plugin/pkg/admission/storage/persistentvolume/label/admission.go [hunk 1]
```diff
@@ -205,18 +203,6 @@ func (l *persistentVolumeLabel) findVolumeLabels(volume *api.PersistentVolume) (
 			return nil, fmt.Errorf("error querying GCE PD volume %s: %v", volume.Spec.GCEPersistentDisk.PDName, err)
 		}
 		return labels, nil
-	case volume.Spec.AzureDisk != nil:
```
Comment (andrewsykim) [inline plugin/pkg/admission/storage/persistentvolume/label/admission.go:208]: With this PR and https://github.com/kubernetes/kubernetes/pull/124519, I suggest some removing the entire admission plugin. It has been deprecated for many releases and we published an external alternative https://github.com/kubernetes-sigs/cloud-pv-admission-labeler

**Review by andrewsykim — COMMENTED** [review]
/hold

Left a comment about deleting the admission plugin instead

File: plugin/pkg/admission/storage/persistentvolume/label/admission.go (hunk 1 above)
Comment (jsafrane) [reply plugin/pkg/admission/storage/persistentvolume/label/admission.go:208]: I did not know about https://github.com/kubernetes-sigs/cloud-pv-admission-labeler. I agree that removing the admission is the best way forward now.

**Comment by dims** [comment]
need to remove:
- https://github.com/kubernetes/kubernetes/blob/e798b9c269627a10291f36a88b4fa13f034ab57f/hack/make-rules/test-cmd.sh#L59

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/52617

**Comment by jsafrane** [comment]
hack/make-rules/test-cmd.sh updated.

@dims how do I re-generate docs/admin/kube-apiserver.md and similar docs?

**Comment by dims** [comment]
/hold cancel

( removing hold as we are now cleaning up per @andrewsykim 's comment `Left a comment about deleting the admission plugin instead` )

thanks @jsafrane
