### PR TITLE
Set session scanning to manual to avoid discovering all iSCSI devices…

### LINKED ISSUE #90982: Automatic session scanning discovers all iSCSI devices during login and can cause LUN assignment issues
**What happened**:
The issue stems from use cases were 1 initiator is used for multiple LUNs. Because of this, all of the LUNs are discovered and mapped on a node when it does its initial discovery / login via AttachDisk[1]. Because a pod never mounts the device on any of the other nodes, it is never removed.

[1] https://github.com/kubernetes/kubernetes/blob/release-1.18/pkg/volume/iscsi/iscsi_util.go#L279

In situations where LUN numbers can be reused, it’s possible to hit the below race condition where a new LUN reattaches to a faulty multipath device created for a previous LUN of the same number.

**What you expected to happen**:
Only the required LUN should be discovered and mounted.

**How to reproduce it (as minimally and precisely as possible)**:
Assume we start from an empty environment using Node A and B. An empty environment is not a requirement, it just makes it visually easier.

1) User A creates a PVC, the PV and LUN1 are dynamically provisioned and mounted by the pod on Node A. Node A does an iscsiadm login (in addition to other things) and scans for the scsi devices, adds them to the multipath devicemap and attaches to /dev/dm-XX.

2) User B creates a second PVC, the PV and LUN2 are dynamically provisioned and mounted by the pod on Node B. Node B does an iscsiadm login (in addition to other things) and scans for the scsi devices, adds them to the multipath devicemap and attaches to a /dev/dm-XX device. This process finds both LUN1 and LUN2 and creates multipath devicemaps and devices for both of them.

3) User A creates a PVC, the PV and LUN3 are dynamically provisioned and mounted by the pod on Node A. Node A is already logged in because of LUN1 so it just scans for the new LUN, adds it to a multipath devicemap and attaches to a /dev/dm-XX device.

At this point:
Node A knows about LUN1 and has it mounted and LUN3 and has it mounted
Node B knows about LUN1 and LUN2 but only has LUN2 mounted

4) User A deletes their first pod and PVC from Node A. This triggers an unmount and the flushing and removal of the multipath device and underlying block devices on Node A. This deletes LUN1 on the backend. Because the pod was only running on Node A, the unmount and removal procedures do nothing for the discovered LUN1 and its devices on Node B. The multipath device for LUN1 on Node B loses its paths and goes into a faulty state.

5) User C creates a PVC, the PV and LUN1 (reused number) are dynamically provisioned and mounted by the pod on Node B. Node B is already logged in because of LUN2 and it already knows about LUN1 as it was discovered when LUN2 came along. In this case, LUN1 is reattached to the old multipath device and block devices from the previously deleted LUN1. This is when we see the LUN assignment / remap warning:

Ex:
May  5 10:02:58 server kernel: sd 40:0:0:29: Warning! Received an indication that the LUN assignments on this target have changed. The Linux SCSI layer does not automatical

6) Kubernetes tries to mount the multipath device to its pod and, based on our testing, sees a variety of possible issues, depending on what kind of leftover data is visible. These range from fixable fsck file system issues, fsck failures and complete disk formatting failures.

The other primary issue we see is where there are PVC size mismatches and non fatal fsck fixes. If LUN1 was originally 1GB, the multipath and block devices reflect that. If the new PVC asked for 5GB, LUN1 is 5GB, but when it reconnects, the user only sees the previous 1GB devices. The reverse is also true where you could request 1GB and end up with the old 5GB block devices which results in formatting errors.

**Anything else we need to know?**:
The race condition is somewhat uncommon and depends on LUN number reuse and WWID stings. As the number of LUNs grow and as more servers are restarted for patching etc.. there will be a great and greater chance of people hitting this as churn occurs.

The other big issue which is independent of hitting the above race condition  is the performance impact and stability of the server. Having a few hundred extra devices is not ideal, but the bigger issue looks to be the constant failed i/o’s and multipathd path down checks for LUNs which have been removed and remapped.

**Environment**: kubernetes
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration: all
- OS (e.g: `cat /etc/os-release`): all
- Kernel (e.g. `uname -a`): all

### PR DESCRIPTION
**Pull request by mrobson**
… during login

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR sets node.session.scan to manual to avoid unused LUNs being discovered and mapped on a node when it does its initial login. If that happens, the devices are never removed.

**Which issue(s) this PR fixes**:
Fixes #90982

**Special notes for your reviewer**:
Some older iscsi package may not support node.session.scan - it was added here: https://github.com/open-iscsi/open-iscsi/pull/40

This will not negatively impact anyone and would log a warning letting them know.

**Does this PR introduce a user-facing change?**:
```
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```

```

### CODE REVIEW

**Comment by jsafrane** [comment]
/assign @bswartz 

Ben, can you please take a look? It's related to your commit https://github.com/kubernetes/kubernetes/commit/6d23d8edbba3680fd6da096faf6ed3a5f3e43000 (and its commit message).

**Comment by bswartz** [comment]
This approach is something I didn't know was possible. I will definitely do some testing of my own to see if this does what I think it does. If so, then we definitely want this change.

**Comment by mrobson** [comment]
Thanks @bswartz - I did some local testing but would appreciate the verification! You can also do it at the session level like: `iscsiadm -m session -r <session_id> -o update -n node.session.scan -v manual` but that just seemed overly complicated versus what's currently being done.

**Comment by humblec** [comment]
Yeah, the approach looks good to me. But lets wait for verification.

File: pkg/volume/iscsi/iscsi_util.go [hunk 1]
```diff
@@ -126,6 +126,13 @@ func updateISCSINode(b iscsiDiskMounter, tp string) error {
 			}
 		}
 	}
+
+	// setting node.session.scan to manual to handle https://github.com/kubernetes/kubernetes/issues/90982
+	out, err = execWithLog(b, "iscsiadm", "-m", "node", "-p", tp, "-T", b.Iqn, "-I", b.Iface, "-o", "update", "-n", "node.session.scan", "-v", "manual")
+	if err != nil {
+		// don't fail if iscsiadm fails or the version does not support node.session.scan - log a warning to highlight the potential exposure
+		klog.Warningf("iscsi: failed to update node with node.session.scan=manual, possible exposure to issue 90982: %v", out)
+	}
```
Comment (mrobson) [inline pkg/volume/iscsi/iscsi_util.go:135]: Now that I look at this again, if they're not using CHAP `!b.chap_session`, it will skip out before executing this which is not what we want. @jsafrane @bswartz @humblec - do you think keep it in updateISCSINode, before `!b.chap_session` or move it outside, right before `updateISCSINode` https://github.com/kubernetes/kubernetes/blob/release-1.18/pkg/volume/iscsi/iscsi_util.go#L345

**Comment by mrobson** [comment]
For completeness, here is the basic test I ran with 3 LUNs:

```
/iscsi/iqn.20...et1/tpg1/luns> cd /
/> ls
o- / ......................................................................................................................... [...]
  o- backstores .............................................................................................................. [...]
  | o- block .................................................................................................. [Storage Objects: 3]
  | | o- scsi_disk1 ....................................................... [/dev/vg_iscsi1/lv_iscsi1 (5.0GiB) write-thru activated]
  | | | o- alua ................................................................................................... [ALUA Groups: 1]
  | | |   o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  | | o- scsi_disk2 ....................................................... [/dev/vg_iscsi2/lv_iscsi2 (5.0GiB) write-thru activated]
  | | | o- alua ................................................................................................... [ALUA Groups: 1]
  | | |   o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  | | o- scsi_disk3 ...................................................... [/dev/vg_iscsi3/lv_iscsi3 (10.0GiB) write-thru activated]
  | |   o- alua ................................................................................................... [ALUA Groups: 1]
  | |     o- default_tg_pt_gp ....................................................................... [ALUA state: Active/optimized]
  | o- fileio ................................................................................................. [Storage Objects: 0]
  | o- pscsi .................................................................................................. [Storage Objects: 0]
  | o- ramdisk ................................................................................................ [Storage Objects: 0]
  o- iscsi ............................................................................................................ [Targets: 1]
  | o- iqn.2020-05.matt.redhat:target1 ................................................................................... [TPGs: 1]
  |   o- tpg1 ............................................................................................... [no-gen-acls, no-auth]
  |     o- acls .......................................................................................................... [ACLs: 1]
  |     | o- iqn.2020-05.matt.redhat:infra1 ....................................................................... [Mapped LUNs: 3]
  |     |   o- mapped_lun0 ............................................................................ [lun0 block/scsi_disk1 (rw)]
  |     |   o- mapped_lun1 ............................................................................ [lun1 block/scsi_disk2 (rw)]
  |     |   o- mapped_lun2 ............................................................................ [lun2 block/scsi_disk3 (rw)]
  |     o- luns .......................................................................................................... [LUNs: 3]
  |     | o- lun0 ................................................. [block/scsi_disk1 (/dev/vg_iscsi1/lv_iscsi1) (default_tg_pt_gp)]
  |     | o- lun1 ................................................. [block/scsi_disk2 (/dev/vg_iscsi2/lv_iscsi2) (default_tg_pt_gp)]
  |     | o- lun2 ................................................. [block/scsi_disk3 (/dev/vg_iscsi3/lv_iscsi3) (default_tg_pt_gp)]
  |     o- portals .................................................................................................... [Portals: 1]
  |       o- 0.0.0.0:3260 ..................................................................................................... [OK]
  o- loopback ......................................................................................................... [Targets: 0]
```

Preform current discovery / login steps, minus CHAP:
```
# iscsiadm -m discoverydb -t sendtargets -p 10.10.100.34:3260 -I default -o new
# iscsiadm -m discoverydb -t sendtargets -p 10.10.100.34:3260 -I default --discover
# iscsiadm -m node -p 10.10.100.34:3260 -T iqn.2020-05.matt.redhat:target1 -I default --login

Logging in to [iface: default, target: iqn.2020-05.matt.redhat:target1, portal: 10.10.100.34,3260] (multiple)
Login to [iface: default, target: iqn.2020-05.matt.redhat:target1, portal: 10.10.100.34,3260] successful.
```
All 3 LUNs are discovered:
```
# lsscsi
[5:0:0:0]    disk    LIO-ORG  scsi_disk1       4.0   /dev/sda
[5:0:0:1]    disk    LIO-ORG  scsi_disk2       4.0   /dev/sdb
[5:0:0:2]    disk    LIO-ORG  scsi_disk3       4.0   /dev/sdc
```

```
ls /dev/disk/by-path/
fc---lun-0  ip-10.10.100.34:3260-iscsi-iqn.2020-05.matt.redhat:target1-lun-0  pci-0000:00:04.0        pci-0000:00:05.0-part1   virtio-pci-0000:00:04.0-part1  virtio-pci-0000:00:05.0-part2
fc---lun-1  ip-10.10.100.34:3260-iscsi-iqn.2020-05.matt.redhat:target1-lun-1  pci-0000:00:04.0-part1  pci-0000:00:05.0-part2   virtio-pci-0000:00:05.0
fc---lun-2  ip-10.10.100.34:3260-iscsi-iqn.2020-05.matt.redhat:target1-lun-2
```

Logout
```
# iscsiadm -m node -T iqn.2020-05.matt.redhat:target1 -p 10.10.100.34:3260 -u

Logging out of session [sid: 4, target: iqn.2020-05.matt.redhat:target1, portal: 10.10.100.34,3260]
Logout of [sid: 4, target: iqn.2020-05.matt.redhat:target1, portal: 10.10.100.34,3260] successful.
```
All gone
```
# lsscsi

```
Preform discovery / login steps, minus CHAP, setting `node.session.scan` to `manual` before login :
```
# iscsiadm -m discoverydb -t sendtargets -p 10.10.100.34:3260 -I default -o new
# iscsiadm -m discoverydb -t sendtargets -p 10.10.100.34:3260 -I default --discover
# iscsiadm -m node -p 10.10.100.34:3260 -T iqn.2020-05.matt.redhat:target1 -I default -o update -n node.session.scan -v manual
# iscsiadm -m node -p 10.10.100.34:3260 -T iqn.2020-05.matt.redhat:target1 -I default --login
```
Empty
```
# lsscsi

```
Discover one LUN
```
# echo '0 0 0' > /sys/class/scsi_host/host6/scan
# lsscsi
[6:0:0:0]    disk    LIO-ORG  scsi_disk1       4.0   /dev/sda
```
Discover another LUN
```
# echo '0 0 2' > /sys/class/scsi_host/host6/scan
lsscsi
[6:0:0:0]    disk    LIO-ORG  scsi_disk1       4.0   /dev/sda
[6:0:0:2]    disk    LIO-ORG  scsi_disk3       4.0   /dev/sdb
```

File: pkg/volume/iscsi/iscsi_util.go (hunk 1 above)
Comment (jsafrane) [reply pkg/volume/iscsi/iscsi_util.go:135]: I'd move it on top of `updateISCSINode`, before `!b.chap_session`.

**Comment by bswartz** [comment]
I'm completed my initial tests and this does indeed seem to work as expected. Just need to make sure this is called on the write codepaths inside kubelet.

**Comment by bswartz** [comment]
> Thanks @bswartz - I did some local testing but would appreciate the verification! You can also do it at the session level like: `iscsiadm -m session -r <session_id> -o update -n node.session.scan -v manual` but that just seemed overly complicated versus what's currently being done.

Based on my understanding, there is no session until after you log in, and by the time you log in, it's too late to set this option, so that would not be a viable approach. Setting at the node level does seem to be exactly what we want though.

**Comment by mrobson** [comment]
> I'm completed my initial tests and this does indeed seem to work as expected. Just need to make sure this is called on the write codepaths inside kubelet.

@bswartz From the testing / reproducer we ran, the only time this appears to be an issue is when AttachDisk is called and there is no existing login. Login only occurs again when a server is drained (all pod removed triggering logout), rebooted or when a logout happens naturally when the last mount in use is removed.

**Comment by mrobson** [comment]
Yay, green! Moved the location to before the chap check @jsafrane @bswartz @humblec PTAL

**Comment by bswartz** [comment]
The "iscsiadm -o update" command will fail on Ubuntu and Debian because they don't support the "node.session.scan" config option yet. I see that the code handles that case properly by logging a warning.

**Comment by jsafrane** [comment]
/approve
Thanks a lot of for this PR!
