### PR TITLE
Use inner volume name instead of outer volume name for subpath directory

### LINKED ISSUE #61372: pvc volumes used with subPath volume mounts don't support reconstruction
**Fix status:**
- [x] fixed in master in https://github.com/kubernetes/kubernetes/pull/61373
- [x] fixed in release-1.10 branch in #61518, will be in 1.10.0
- [x] fixed in release-1.9 branch in #61519, will be in 1.9.7
- [x] fixed in release-1.8 branch in #61520, will be in 1.8.11
- [x] fixed in release-1.7 branch in #61521, will be in 1.7.16

In SubPath fixes, PR https://github.com/kubernetes/kubernetes/pull/61044 adds bind mount for subpaths. It uses `/var/lib/kubelet/pods/<uid>/volume-subpaths/<volumename>` as the path name. The volumename in this path is the container's mount volume name which is also called OuterVolumeSpecName in [operation_executor.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_executor.go#L476).

This becomes an issue for volume reconstruction when kubelet restarts. Volume [reconstruction](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler.go#L556) scans the volume directories and recover the InnerVolumeSpecName (which is used to construct pod volume paths). Volume reconstruction has not enough information to recover the OuterVolumeSpecName and figure out which volume it maps to. In case kubelet needs to clean up mounts (it happens when volume spec cannot be reconstructed), it will fail to clean up the subpaths because of lacking the OuterVolumeSpecName.

We think it is better to use InnerVolumeSpecName for volume subPath instead of OuterVolumeSpecName so that volume clean up can work. The issue we might have is that some users might already deploy a cluster with subpath might already [SubPath fix](https://github.com/kubernetes/kubernetes/pull/61044). If the users perform an in-place upgrade, since new version will use InnerVolumeSpecName which might have conflicts with some other older version's OuterVolumeSpecName among different volumes. This change requires clear documentation and communication with the users.

### PR DESCRIPTION
**Pull request by msau42**
**What this PR does / why we need it**:
Fixes volume reconstruction for PVCs with subpath

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #61372

**Special notes for your reviewer**:

**Release note**:

```release-note
ACTION REQUIRED: In-place node upgrades to this release from versions 1.7.14, 1.8.9, and 1.9.4 are not supported if using subpath volumes with PVCs.  Such pods should be drained from the node first.
```

### CODE REVIEW

**Comment by msau42** [comment]
/assign @jsafrane @jingxu97 
/cc @liggitt @gnufied @saad-ali 
@kubernetes/sig-storage-pr-reviews

**Comment by msau42** [comment]
This is ready to review.

I ran the new e2e tests against an old cluster to verify that they failed, and that the test cluster with the fix passes.  Currently running all subpath tests to test for regression.

File: test/e2e/storage/subpath.go [hunk 1]
```diff
@@ -307,6 +308,20 @@ var _ = utils.SIGDescribe("Subpath", func() {
 
 				testPodContainerRestart(f, pod, filePathInVolume, filePathInSubpath)
 			})
+
+			It("should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]", func() {
+				if curVolType == "hostPath" || curVolType == "hostPathSymlink" {
```
Comment (msau42) [inline test/e2e/storage/subpath.go]: There is one side issue here that hostpath volume plugin doesn't support reconstruction.  We probably need to figure out how to implement support for it otherwise the subpath bind mounts are not going to get cleaned up for hostpath volumes (although I still question why do you need to use subpath with hostpath volumes?).

Comment (gnufied) [reply test/e2e/storage/subpath.go]: regardless of reconstruction after newest bit of refactoring - `Teardown` should be called for all volume types that are not in use, including hostpaths. Shouldn't that cleanup subpaths too?

Comment (msau42) [reply test/e2e/storage/subpath.go]: Yes hostpath subpath is cleaned up in normal cases.  But in the reconstruction case, it is not.  And this PR won't fix that

Comment (msau42) [reply test/e2e/storage/subpath.go]: I think graceful pod delete should still work for hostpath.  Only forceful delete will fail, so this check can be removed.

File: pkg/kubelet/container/runtime.go [hunk 2]
```diff
@@ -470,6 +470,9 @@ type VolumeInfo struct {
 	// Whether the volume permission is set to read-only or not
 	// This value is passed from volume.spec
 	ReadOnly bool
+	// Inner volume name, which is the PV name if used, otherwise
+	// it is the same as the outer volume name.
```
Comment (jingxu97) [inline pkg/kubelet/container/runtime.go]: Maybe change outer volume name to "OuterVolumeSpecName" in the comment for consistency.

Comment (msau42) [reply pkg/kubelet/container/runtime.go]: done
