### PR TITLE
KEP-4781: Restarting kubelet does not change pod status

### LINKED ISSUE #100277: pod config readinessprobe, if kubelet restart,  pod temporarily report containerNotReady，this may lead to service not available
#### What happened:

pod config readinessprobe, if kubelet restart,  pod temporarily report containerNotReady，this may lead to service not available

#### What you expected to happen:

pod status not changed

#### How to reproduce it (as minimally and precisely as possible):

1. create a pod with readinessprobe, and wait for pod ready
2. restart kubelet, use kubectl watch pods

#### Anything else we need to know?:

when kubelet generateAPIPodStatus, will check probe cached status and worker state.
```golang
			var ready bool
			if c.State.Running == nil {
				ready = false
			} else if result, ok := m.readinessManager.Get(kubecontainer.ParseContainerID(c.ContainerID)); ok {
				ready = result == results.Success
			} else {
				// The check whether there is a probe which hasn't run yet.
				_, exists := m.getWorker(podUID, c.Name, readiness)
				ready = !exists
			}
			podStatus.ContainerStatuses[i].Ready = ready
```
when restart kubelet, probe cached status is not exist, now use worker exist value to set container ready status. This may lead a ready container to report  as not ready

```golang
      if w.containerID.String() != c.ContainerID {
		if !w.containerID.IsEmpty() {
			w.resultsManager.Remove(w.containerID)
		}
		w.containerID = kubecontainer.ParseContainerID(c.ContainerID)
		w.resultsManager.Set(w.containerID, w.initialValue, w.pod)
		// We've got a new container; resume probing.
		w.onHold = false
	}

```
and also during first probe, worker's containerID is not Exist, so worker will use initialValue to set result as first time.
it also lead to report container  as not ready

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19.8
- Cloud provider or hardware configuration: HuaweiCloud
- OS (e.g: `cat /etc/os-release`): CentOS 7.6
- Kernel (e.g. `uname -a`): 3.10
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by HirazawaUi**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:

Since KEP-4781 has been merged, we will advance this feature during the v1.35 cycle.

This "feature/bug fix" was proposed to prevent changes in pod status caused by kubelet restarts.

It introduces a feature gate named `ChangeContainerStatusOnKubeletRestart`. When the `ChangeContainerStatusOnKubeletRestart` feature gate is disabled, the pod status will not be changed upon kubelet restart. Users can opt out of this fix/behavior by enabling the `ChangeContainerStatusOnKubeletRestart `feature gate.

This is achieved by defaulting the `ContainerStatuses.Ready` and `ContainerStatuses.Started` fields to their pre-restart states and preventing the doProbe mechanism from setting initial values (which are Failure or Unknown) for the readiness and startup probes.

For detailed design, please refer to: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4781-kublet-restart-pod-status#design-details

#### Which issue(s) this PR is related to:

Fixes #100277

#### Does this PR introduce a user-facing change?

```release-note
Add the `ChangeContainerStatusOnKubeletRestart` feature gate. The feature gate defaults to disabled. When the feature gate is disabled, the kubelet does not change the pod status upon restart, and pods will not re-run startup probes after kubelet restart.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/4781
```

### CODE REVIEW

File: pkg/kubelet/prober/prober_manager.go
Comment (toVersus) [inline pkg/kubelet/prober/prober_manager.go:418]: Do we not need to take restartable init containers into account?

File: pkg/kubelet/prober/worker_test.go [hunk 1]
```diff
@@ -306,6 +307,9 @@ func TestInitialDelay(t *testing.T) {
 		})
 		m.statusManager.SetPodStatus(logger, w.pod, getTestRunningStatusWithStarted(probeType != startup))
 
+		// Set initial result for test to pass.
+		resultsManager(m, probeType).Set(testContainerID, w.initialValue, w.pod)
```
Comment (toVersus) [inline pkg/kubelet/prober/worker_test.go]: I think the behavior should remain the same when the kubelet hasn’t restarted. Why do we need to add setting the initial result in TestInitialDelay and TestFailureThreshold?

Comment (HirazawaUi) [reply pkg/kubelet/prober/worker_test.go]: After analyzing the code, it appears there was an issue with the branch condition. Adding this check happens to satisfy the branch condition, so it has been removed.

File: pkg/kubelet/prober/prober_manager.go
Comment (HirazawaUi) [reply pkg/kubelet/prober/prober_manager.go:418]: Great suggestion! We have now implemented code to handle restartable containers.

**Comment by jichangyun** [comment]
> > Please consider the scenario where "one pod contains multiple containers." It seems that this might not work very well.
> 
> I'd like to ask, based on which part of the code do you believe it doesn't work when a pod has multiple containers? I tested the scenario with multi-container pods using the latest code, and everything functioned normally. Could you provide some concrete and valid explanation to support your claim?

Either this is the cause, or I made a mistake.

pkg/kubelet/prober/prober_manager.go@UpdatePodStatus

This line "ready = !exists" will set the variable "ready" to "false". Even if the feature gate ChangeContainerStatusOnKubeletRestart is not enabled, it appears to cause the pod to become NotReady.

File: test/e2e_node/container_lifecycle_test.go [hunk 2]
```diff
@@ -6305,3 +6306,607 @@ var _ = SIGDescribe(feature.SidecarContainers, framework.WithSerial(), "Containe
...
+			}
+
+			// The grace period for kubelet startup is 10 seconds, so we wait here for 11 seconds.
+			time.Sleep(time.Second * 11)
+
+			stopCh := make(chan struct{})
+			errCh := make(chan error, 1)
+			go func() {
+				defer ginkgo.GinkgoRecover()
+				ticker := time.NewTicker(1 * time.Second)
```
Comment (ji-cy) [inline test/e2e_node/container_lifecycle_test.go]: Using the watch mechanism seems to be a better approach. The UpdatePodStatus function in the kubernetes\pkg\kubelet\prober\prober_manager.go file contains this line: `w.manualTriggerCh <- struct{}{}`, so another container in the same pod will quickly update its readiness result.

Comment (HirazawaUi) [reply test/e2e_node/container_lifecycle_test.go]: Good suggestion. Switched to using watch.

**Comment by jichangyun** [comment]
> > Either this is the cause, or I made a mistake.
> > pkg/kubelet/prober/prober_manager.go@UpdatePodStatus
> > This line "ready = !exists" will set the variable "ready" to "false". Even if the feature gate ChangeContainerStatusOnKubeletRestart is not enabled, it appears to cause the pod to become NotReady.
> > @HirazawaUi I think the above is the reason. On Saturday, I tried changing the line `if !podIsReady { *ready = false }` in the function setReadyStateOnKubeletRestart to `*ready = podIsReady`, and then it worked properly.
> 
> No, this is not a bug but an intentional design choice. This also does not cause any change in the pod’s status. During the first `syncPod` operation, the `exists` value returned by `m.getWorker(pod.UID, c.Name, readiness)` is always false, regardless of how many regular containers are in the pod—the result remains consistent.
> 
> Then, in `syncPod`, we execute `kl.probeManager.AddPod(ctx, pod)`, which initiates the probing process. This ensures that in the subsequent `syncPod` cycle, it will retrieve the probe workers that have already been added to the `probeManager`, allowing us to restore the previous behavior.
> 
> For more details on the design, please refer to the [Design Details](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4781-kublet-restart-pod-status#design-details) section in the KEP.
> 
> There, I have provided a detailed explanation of every aspect of this design and have also depicted the entire process with multiple flowcharts.


This code change clears up all my confusion. What prompted it, by the way?

```go
		if !*ready {
			if _, ok := m.readinessManager.Get(kubecontainer.ParseContainerID(containerStatus.ContainerID)); !ok {
Comment view				*ready = true
			}
		}
```

**Comment by HirazawaUi** [comment]
> This code change clears up all my confusion. What prompted it, by the way?

Because there exists a race condition between `syncPod` and `doProbe`, the triggering of `syncPod` is not solely initiated by the `proberManager`. When `syncPod` executes `UpdatePodStatus`, the pod may be in one of the following two states:

  * It has not yet been added to the readinessManager. In this case, we directly set the container status to Ready using `ready = !exists`.
  
  * It has been added to the `readinessManager`, but `doProbe` has not yet started execution. In this case, `ready = !exists` evaluates to false, which may cause us to incorrectly set the container status to false.

This serves as a mitigation for the second scenario, ensuring we can escape this race condition.

In container lifecycle code handling, race conditions can potentially occur anywhere, so we must be exceptionally careful. This potential for race conditions is also the reason why we cannot use the `podIsReady` variable derived from the `Conditions` handling as the standard for container health, as you suggested :)

File: pkg/kubelet/prober/prober_manager.go [hunk 3]
```diff
@@ -278,6 +281,10 @@ func (m *manager) isContainerStarted(pod *v1.Pod, containerStatus *v1.ContainerS
 		return result == results.Success
 	}
 
+	if !utilfeature.DefaultFeatureGate.Enabled(features.ChangeContainerStatusOnKubeletRestart) && containerStatus.Started != nil && *containerStatus.Started {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/prober/prober_manager.go:284]: so this will help not to re-run startup probes?

Comment (SergeyKanzhelev) [reply pkg/kubelet/prober/prober_manager.go:284]: if so - please mention it in release notes

File: test/e2e_node/container_lifecycle_test.go [hunk 4]
```diff
@@ -6304,3 +6305,630 @@ var _ = SIGDescribe(framework.WithNodeConformance(), framework.WithSerial(), "Co
 		})
 	})
 })
+
+var _ = SIGDescribe(framework.WithSerial(), "Not Change Container Status", framework.WithFeatureGate(features.ChangeContainerStatusOnKubeletRestart), func() {
```
Comment (SergeyKanzhelev) [inline test/e2e_node/container_lifecycle_test.go:6309]: is there any chance we can make it non-serial? Maybe filter by pod name in watcher

Comment (SergeyKanzhelev) [inline test/e2e_node/container_lifecycle_test.go:6309]: since the change introduces a small dependency to API server with probes, let's add some tests for static pods and for the kubelet in Standalone mode. In standalone mode the idea is to ensure that nothing is broken - there will be no ready state preservation. But we need to ensure that kubelet restart will not cause some panics in standalone mode.

Comment (HirazawaUi) [reply test/e2e_node/container_lifecycle_test.go:6309]: We can only choose serial tests because these cases all require restarting kubelet. If they were non-serial tests, they would disrupt other test cases.

Moreover, based on my observation, all tests requiring kubelet restarts are currently serial tests.

File: pkg/kubelet/prober/prober_manager.go (hunk 3 above)
Comment (HirazawaUi) [reply pkg/kubelet/prober/prober_manager.go:284]: Yes, it will skip the startup probe. I will document this in the release note.

File: test/e2e_node/container_lifecycle_test.go (hunk 4 above)
Comment (HirazawaUi) [reply test/e2e_node/container_lifecycle_test.go:6309]: Tests been added. Let's wait for the test results...

**Comment by HirazawaUi** [comment]
This test failure is unrelated to the current PR. It might be caused by changes made elsewhere. I have verified this test job in both directions in another PR and encountered the same errors.

**Comment by HirazawaUi** [comment]
An issue has been opened to track the test failures: https://github.com/kubernetes/kubernetes/issues/135041

File: test/e2e_node/container_lifecycle_test.go (hunk 4 above)
Comment (HirazawaUi) [reply test/e2e_node/container_lifecycle_test.go:6309]: The test cases have passed successfully.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

thank you for testing static pods
