### PR TITLE
Fix a flaky scheduler preemption e2e

### LINKED ISSUE #86068: [Flaky Test] [sig-scheduling] PreemptionExecutionPath runs ReplicaSets to verify preemption running path
**Which jobs are failing**:
gce-cos-k8sbeta-default

**Which test(s) are failing**:
PreemptionExecutionPath runs ReplicaSets to verify preemption running path

**Since when has it been failing**:

**Testgrid link**:
master:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&sort-by-flakiness=&include-filter-by-regex=Preemption

release 1.17: https://testgrid.k8s.io/sig-release-1.17-informing#gce-cos-k8sbeta-default

**Reason for failure**:
```
I1209 11:04:22.876] [BeforeEach] [sig-scheduling] PreemptionExecutionPath
I1209 11:04:22.876]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:264
I1209 11:04:22.876] [1mSTEP[0m: Finding an available node
I1209 11:04:22.876] [1mSTEP[0m: Trying to launch a pod without a label to get a node which can launch it.
I1209 11:04:22.876] [1mSTEP[0m: Explicitly delete pod here to free the resource it takes.
I1209 11:04:22.877] Dec  9 11:01:39.752: INFO: found a healthy node: test-1789b1211d-minion-group-h4jr
I1209 11:04:22.877] [It] runs ReplicaSets to verify preemption running path
I1209 11:04:22.877]   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:307
I1209 11:04:22.877] Dec  9 11:03:09.855: INFO: pods created so far: map[rs-pod1-2pmt5:{} rs-pod1-9lhzb:{} rs-pod1-k964d:{} rs-pod1-rkp8c:{} rs-pod1-zkqd8:{} rs-pod2-526h5:{} rs-pod2-gzm7k:{} rs-pod2-rljhp:{} rs-pod2-w5nfh:{} rs-pod3-4x9fq:{} rs-pod3-r7sgb:{} rs-pod3-v44ks:{} rs-pod3-xbs7b:{}]
I1209 11:04:22.877] Dec  9 11:03:09.855: INFO: length of pods created so far: 13
I1209 11:04:22.878] Dec  9 11:04:11.004: FAIL: Unexpected error:
I1209 11:04:22.878]     <*errors.errorString | 0xc0022e9db0>: {
I1209 11:04:22.878]         s: "replicaset \"rs-pod4\" never had desired number of .status.availableReplicas",
I1209 11:04:22.878]     }
I1209 11:04:22.878]     replicaset "rs-pod4" never had desired number of .status.availableReplicas
I1209 11:04:22.878] occurred
I1209 11:04:22.878] [AfterEach] [sig-scheduling] PreemptionExecutionPath
```

**Anything else we need to know**:
cc. @kubernetes/ci-signal 
/sig scheduling
/priority important-soon

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind flake
/sig scheduling
/cc @ahg-g @liggitt 

**What this PR does / why we need it**:

In the debugging PR (#86325), it turns out in the e2e cluster, sometimes the preemptor Pod can't finish the preemption logic within 1 minute. This PR optimize the logic of checking if the preemption behavior is happening from "check if the Pod is running" to "if the NominatedNodeName field has been set or the Pod is running". Moreover, the preemptor Pod doesn't need to be a ReplicaSet instead of a plain Pod, also the number of low priority Pods has been adjusted to the least necessity manner (it's because from the log, even plain RS Pods need ~45 secs to get them running, so reducing the RS replica number can help). Moreover, increase the timeout from 1 min to 2 mins.

**Which issue(s) this PR fixes**:

Fixes #86068.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by ahg-g — COMMENTED** [review]
thanks.

File: test/e2e/scheduling/preemption.go [hunk 1]
```diff
@@ -338,83 +339,78 @@ var _ = SIGDescribe("PreemptionExecutionPath", func() {
 		// prepare four ReplicaSet
```
Comment (liggitt) [inline test/e2e/scheduling/preemption.go]: nit, three replicasets now

File: test/e2e/scheduling/preemption.go [hunk 2]
```diff
@@ -338,83 +339,78 @@ var _ = SIGDescribe("PreemptionExecutionPath", func() {
...
+			Labels:            map[string]string{"name": "pod4"},
+			PriorityClassName: "p4",
+			NodeSelector:      map[string]string{"kubernetes.io/hostname": nodeHostNameLabel},
+			Resources: &v1.ResourceRequirements{
+				Requests: v1.ResourceList{fakecpu: resource.MustParse("500")},
+				Limits:   v1.ResourceList{fakecpu: resource.MustParse("500")},
+			},
+		}
+		preemptorPod := createPod(f, preemptorPodConf)
+		waitForPreemptingWithTimeout(f, preemptorPod, framework.PodGetTimeout)
```
Comment (liggitt) [inline test/e2e/scheduling/preemption.go]: This will return as soon as NominatedNodeName is set on the pod. that happens *before* preempted pods are deleted, which means that this will race with observing the additional rescheduled rs pods in podNamesSeen.

Shouldn't waitForPreemptingWithTimeout wait for `spec.nodeName` to be set instead?

File: test/e2e/scheduling/preemption.go [hunk 3]
```diff
@@ -338,83 +339,78 @@ var _ = SIGDescribe("PreemptionExecutionPath", func() {
...
 		framework.Logf("pods created so far: %v", podNamesSeen)
 		framework.Logf("length of pods created so far: %v", len(podNamesSeen))
 
 		// count pods number of ReplicaSet{1,2,3}, if it's more than expected replicas
 		// then it denotes its pods have been over-preempted
 		// "*2" means pods of ReplicaSet{1,2} are expected to be only preempted once
-		maxRSPodsSeen := []int{5 * 2, 4 * 2, 4}
+		maxRSPodsSeen := []int{1 * 2, 1 * 2, 1}
 		rsPodsSeen := []int{0, 0, 0}
 		for podName := range podNamesSeen {
```
Comment (liggitt) [inline test/e2e/scheduling/preemption.go]: also, this is pre-existing, but while we're here, accessing the podNamesSeen variable here is a data race with the accesses inside the informer handler. That will panic if detected by the go runtime. This shared map between threads needs to coordinate access (e.g. with a [sync.Map](https://golang.org/pkg/sync/#Map))

File: test/e2e/scheduling/preemption.go [hunk 4]
```diff
@@ -472,6 +468,33 @@ func createPauseRS(f *framework.Framework, conf pauseRSConfig) *appsv1.ReplicaSe
...
+	if len(namespace) == 0 {
+		namespace = f.Namespace.Name
+	}
+	pod, err := f.ClientSet.CoreV1().Pods(namespace).Create(initPausePod(f, conf))
+	framework.ExpectNoError(err)
+	return pod
+}
+
+// waitForPreemptingWithTimeout verifies if 'pod' is preempting within 'timeout', specifically it checks:
+// - if the 'status.NominatedNodeName' field of preemptor 'pod' has been set
```
Comment (liggitt) [inline test/e2e/scheduling/preemption.go]: if this is being used to block before we do the check on the preempted pods, we need to wait for spec.nodeName, see https://github.com/kubernetes/kubernetes/pull/86400/files#r359691588

File: test/e2e/scheduling/preemption.go [hunk 5]
```diff
@@ -338,83 +339,78 @@ var _ = SIGDescribe("PreemptionExecutionPath", func() {
...
+				Limits:   v1.ResourceList{fakecpu: resource.MustParse("500")},
+			},
+		}
+		preemptorPod := createPod(f, preemptorPodConf)
+		waitForPreemptingWithTimeout(f, preemptorPod, framework.PodGetTimeout)
 
 		framework.Logf("pods created so far: %v", podNamesSeen)
 		framework.Logf("length of pods created so far: %v", len(podNamesSeen))
 
 		// count pods number of ReplicaSet{1,2,3}, if it's more than expected replicas
```
Comment (liggitt) [inline test/e2e/scheduling/preemption.go]: even if we wait for spec.nodeName above (meaning sufficient pods were preempted), this still races with the replicationcontroller observing the preempted pod deletions and creating replacements. the `podNamesSeen` needs to tolerate that lag.

File: test/e2e/framework/replicaset/wait.go [hunk 6]
```diff
@@ -54,6 +55,12 @@ func WaitForReadyReplicaSet(c clientset.Interface, ns, name string) error {
 
 // WaitForReplicaSetTargetAvailableReplicas waits for .status.availableReplicas of a RS to equal targetReplicaNum
 func WaitForReplicaSetTargetAvailableReplicas(c clientset.Interface, replicaSet *appsv1.ReplicaSet, targetReplicaNum int32) error {
+	return WaitForReplicaSetTargetAvailableReplicasWithTimeout(c, replicaSet, targetReplicaNum, framework.PollShortTimeout)
+}
+
+// WaitForReplicaSetTargetAvailableReplicasWithTimeout waits for .status.availableReplicas of a RS to equal targetReplicaNum
+// with given timeout.
+func WaitForReplicaSetTargetAvailableReplicasWithTimeout(c clientset.Interface, replicaSet *appsv1.ReplicaSet, targetReplicaNum int32, timeout time.Duration) error {
```
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply test/e2e/framework/replicaset/wait.go]: true...

File: test/e2e/scheduling/preemption.go (hunk 1 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: done.

File: test/e2e/scheduling/preemption.go (hunk 2 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: I can't think of a good way except for adding a sleeping internal inbetween. As when the podNamesSeen equals to a number for the first time, we can't assert that it's a success - the number may increase which means an unnecessary preemption which is what this case wants to cover.

> Shouldn't waitForPreemptingWithTimeout wait for spec.nodeName to be set instead?

Updated.

File: test/e2e/scheduling/preemption.go (hunk 3 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: I'm using a buffered channel to resolve this. If extra pods (greater than 6) are signaled, it's also an error.

File: test/e2e/scheduling/preemption.go (hunk 4 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: done.

File: test/e2e/scheduling/preemption.go (hunk 5 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: resolved by the buffered channel.

**Comment by Huang-Wei** [comment]
Kindly ping @liggitt

File: test/e2e/scheduling/preemption.go [hunk 7]
```diff
@@ -307,8 +308,8 @@ var _ = SIGDescribe("PreemptionExecutionPath", func() {
 		}
 	})
 
-	ginkgo.It("runs ReplicaSets to verify preemption running path [Flaky]", func() {
-		podNamesSeen := make(map[string]struct{})
+	ginkgo.It("runs ReplicaSets to verify preemption running path", func() {
+		podNamesSeen := make(chan string, 6)
```
Comment (liggitt) [inline test/e2e/scheduling/preemption.go]: is there a downside to making this way oversized (e.g. 100)? I don't want to block adds

File: test/e2e/scheduling/preemption.go [hunk 8]
```diff
@@ -427,7 +425,7 @@ var _ = SIGDescribe("PreemptionExecutionPath", func() {
 		}
 		for i, got := range rsPodsSeen {
 			expected := maxRSPodsSeen[i]
-			if got > expected {
+			if got != expected {
 				framework.Failf("pods of ReplicaSet%d have been over-preempted: expect %v pod names, but got %d", i+1, expected, got)
 			}
```
Comment (liggitt) [inline test/e2e/scheduling/preemption.go]: should this be:
```
if got > expected {
  framework.Failf("pods of ReplicaSet%d have been over-preempted: expect %v pod names, but got %d", i+1, expected, got)
} else if got < expected {
  framework.Failf("pods of ReplicaSet%d have been under-preempted: expect %v pod names, but got %d", i+1, expected, got)
}
```

File: test/e2e/scheduling/preemption.go (hunk 4 above)
Comment (liggitt) [reply test/e2e/scheduling/preemption.go]: this still returns as soon as `len(pod.Status.NominatedNodeName) > 0`, which is too soon. we need to wait for the preempting pod to actually get scheduled (`len(pod.Spec.NodeName) > 0`)

File: test/e2e/scheduling/preemption.go (hunk 7 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: This's an additional gate to block the "under-preempted" case, but a little "brute forcing"... So no downside if we make it oversized.

File: test/e2e/scheduling/preemption.go (hunk 8 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: This is better.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/86400#discussion_r364332248 is still outstanding, lgtm otherwise

**Comment by Huang-Wei** [comment]
> [#86400 (comment)](https://github.com/kubernetes/kubernetes/pull/86400#discussion_r364332248) is still outstanding, lgtm otherwise

Resolved. PTAL.

File: test/e2e/scheduling/preemption.go [hunk 9]
```diff
@@ -327,94 +328,91 @@ var _ = SIGDescribe("PreemptionExecutionPath", func() {
...
+			},
+		}
+		preemptorPod := createPod(f, preemptorPodConf)
+		waitForPreemptingWithTimeout(f, preemptorPod, framework.PodGetTimeout)
 
 		framework.Logf("pods created so far: %v", podNamesSeen)
 		framework.Logf("length of pods created so far: %v", len(podNamesSeen))
 
+		time.Sleep(10 * time.Second)
+		close(podNamesSeen)
```
Comment (liggitt) [inline test/e2e/scheduling/preemption.go]: why close this? that creates a panic in the AddFunc

File: test/e2e/scheduling/preemption.go [hunk 10]
```diff
@@ -472,6 +472,32 @@ func createPauseRS(f *framework.Framework, conf pauseRSConfig) *appsv1.ReplicaSe
...
+
+// waitForPreemptingWithTimeout verifies if 'pod' is preempting within 'timeout', specifically it checks
+// if the 'spec.NodeName' field of preemptor 'pod' has been set.
+func waitForPreemptingWithTimeout(f *framework.Framework, pod *v1.Pod, timeout time.Duration) {
+	err := wait.Poll(2*time.Second, timeout, func() (bool, error) {
+		pod, err := f.ClientSet.CoreV1().Pods(pod.Namespace).Get(pod.Name, metav1.GetOptions{})
+		if err != nil {
+			return false, err
+		}
+		if len(pod.Spec.NodeName) > 0 {
```
Comment (liggitt) [inline test/e2e/scheduling/preemption.go]: hmm... if we want to make sure this actually triggered an eviction, I guess we should wait for both nominatedNodeName and nodeName:

```
if len(pod.Spec.NominatedNodeName) == 0 {
  // log no preemption triggered yet
  return false, nil
}
if len(pod.Spec.NodeName) == 0 {
  // log preemption not complete yet
  return false, nil
}
```

File: test/e2e/scheduling/preemption.go (hunk 9 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: If not closing it, the `for range podNamesSeen` loop will hang there waiting for the close.

It's like M producers (AddFunc) generating values, and one receiver says "ok, stop sending me more values". One solution is to close both controller and podNamesSeen here: (the `defer close(stopCh)` should also be adjusted):

```go
close(stopCh)
close(podNamesSeen)
```

Or the other option is to put the`for range podNamesSeen` loop into a goroutine:

```go
go podController.Run(stopCh)
defer func() {
	close(stopCh)
	close(podNamesSeen)
}()

...

maxRSPodsSeen := []int{1 * 2, 1 * 2, 1}
rsPodsSeen := []int{0, 0, 0}
go func() {
	for podName := range podNamesSeen {
		...
	}
}()

time.Sleep(10 * time.Second)
for i, got := range rsPodsSeen {
	...
}
```

WDTY?

File: test/e2e/scheduling/preemption.go (hunk 10 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: But the chances are "pod.Spec.NominatedNodeName" might be set and unset within our checking interval - only "pod.Spec.NodeName" is the final stable state.

Comment (liggitt) [reply test/e2e/scheduling/preemption.go]: ah, I didn't realize nominated node name got unset. ok.

File: test/e2e/scheduling/preemption.go (hunk 9 above)
Comment (liggitt) [reply test/e2e/scheduling/preemption.go]: how about:

1. make individual vars to hold counts per rs:
```
var rs1, rs2, rs3 int32
```

2. increment those directly in AddFunc
```
if strings.HasPrefix(podName, "rs-pod1") {
	atomic.AddInt32(&rs1, 1)
} else if strings.HasPrefix(podName, "rs-pod2") {
	atomic.AddInt32(&rs2, 1)
} else if strings.HasPrefix(podName, "rs-pod3") {
	atomic.AddInt32(&rs3, 1)
}
```

3. after doing the preemption and waiting for the preempting pod to be scheduled, wait until the counts match our expectations:

```
err := wait.Poll(time.Second, wait.TestForeverTimeout, func() (bool, error) {
  if rs1 < 2 {
    framework.Logf("waiting for rs1 to observe 2 pod creations, got %d", rs1)
    return false, nil
  } else if rs1 > 2 {
    return false, fmt.Errorf("rs1 had more than 2 pods created: %d", rs1)
  }

  if rs2 < 2 {
    framework.Logf("waiting for rs2 to observe 2 pod creations, got %d", rs2)
    return false, nil
  } else if rs2 > 2 {
    return false, fmt.Errorf("rs2 had more than 2 pods created: %d", rs2)
  }

  if rs3 < 1 {
    framework.Logf("waiting for rs3 to observe 1 pod creations, got %d", rs3)
    return false, nil
  } else if rs3 > 1 {
    return false, fmt.Errorf("rs3 had more than 1 pods created: %d", rs3)
  }
})
if err != nil {
  framework.Failf("failed pod observation expectations: %v", err)
}
```

Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: (3) might be problematic: suppose at time T1, all the conditions are satisfied, then we return and think it's a success. However, the chances are: at a later time T2, the backfilled pods (rs1, rs2, rs3) might be over-preempted, i.e. the pods number may exceed the expected ones.

The other way is to check only once after a fixed interval (10 seconds let's say). But either way is not perfect.

Comment (liggitt) [reply test/e2e/scheduling/preemption.go]: after 3 succeeds, waiting a fixed period (e.g. 5 seconds), then doing the check again to make sure nothing changed sounds fine

Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: SGTM will update. Thanks @liggitt.

Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: Updated. PTAL.

File: test/e2e/scheduling/preemption.go [hunk 11]
```diff
@@ -327,108 +329,119 @@ var _ = SIGDescribe("PreemptionExecutionPath", func() {
...
-				rsPodsSeen[1]++
-			} else if strings.HasPrefix(podName, "rs-pod3") {
-				rsPodsSeen[2]++
+		// count pods number of ReplicaSet{1,2,3}:
+		// - if it's more than expected replicas, it denotes its pods have been over-preempted
+		// - if it's less than expected replicas, it denotes its pods are under-preempted
+		// "*2" means pods of ReplicaSet{1,2} are expected to be only preempted once.
+		expectedRSPods := []int32{1 * 2, 1 * 2, 1}
+		err := wait.Poll(framework.Poll, framework.PollShortTimeout, func() (bool, error) {
+			for i, got := range podNamesSeen {
```
Comment (liggitt) [inline test/e2e/scheduling/preemption.go]:
```go
for i, got := range podNamesSeen {
  got := atomic.LoadInt32(&podNamesSeen[i])
```

File: test/e2e/scheduling/preemption.go [hunk 12]
```diff
@@ -327,108 +329,119 @@ var _ = SIGDescribe("PreemptionExecutionPath", func() {
...
 		}
-		for i, got := range rsPodsSeen {
-			expected := maxRSPodsSeen[i]
-			if got > expected {
-				framework.Failf("pods of ReplicaSet%d have been over-preempted: expect %v pod names, but got %d", i+1, expected, got)
+
+		// If logic continues to here, we should do a final check to ensure within a time period,
+		// the state is stable; otherwise, pods may be over-preempted.
+		time.Sleep(5 * time.Second)
+		for i, got := range podNamesSeen {
```
Comment (liggitt) [inline test/e2e/scheduling/preemption.go]:
```go
for i, got := range podNamesSeen {
  got := atomic.LoadInt32(&podNamesSeen[i])
```

File: test/e2e/scheduling/preemption.go (hunk 11 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: I changed it to:

```go
for i := 0; i < len(podNamesSeen); i++ {
    got := atomic.LoadInt32(&podNamesSeen[i])
```

File: test/e2e/scheduling/preemption.go (hunk 12 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: I changed it to:

```go
for i := 0; i < len(podNamesSeen); i++ {
    got := atomic.LoadInt32(&podNamesSeen[i])
```

**Comment by liggitt** [comment]
/lgtm
/approve
/hold for retesting to flush out any last minute flakes

per https://github.com/kubernetes/kubernetes/issues/86068#issuecomment-566226260 we had a ~10% flake rate before marking this flaky. I'd like to see ~20 test runs of pull-kubernetes-e2e-gce without this test failing before merging this

**Comment by Huang-Wei** [comment]
Thanks @liggitt for reviewing.

> per [#86068 (comment)](https://github.com/kubernetes/kubernetes/issues/86068#issuecomment-566226260) we had a ~10% flake rate before marking this flaky. I'd like to see ~20 test runs of pull-kubernetes-e2e-gce without this test failing before merging this

To confirm, I will manually run `/test pull-kubernetes-e2e-gce` 20 times, and ensure the preemption e2e doesn't fail in any of the runnings, correct?

**Comment by liggitt** [comment]
> To confirm, I will manually run `/test pull-kubernetes-e2e-gce` 20 times, and ensure the preemption e2e doesn't fail in any of the runnings, correct?

Exactly. sorry for the toil, but I want to make sure the test passes in the exact environment it was having trouble before. (note that I expect *other* currently flaky test failures will be encountered, I just want to make sure this particular test doesn't fail)

**Comment by Huang-Wei** [comment]
> Exactly. sorry for the toil, but I want to make sure the test passes in the exact environment it was having trouble before. (note that I expect _other_ currently flaky test failures will be encountered, I just want to make sure this particular test doesn't fail)

Np at all. I will do that.

**Comment by Huang-Wei** [comment]
Automatic CI test [0](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/86400/pull-kubernetes-e2e-gce/1216777029093953538/): pass (flaky test is "[sig-apps] DisruptionController should block an eviction until the PDB is updated to allow it")

/test pull-kubernetes-e2e-gce
/test pull-kubernetes-e2e-kind-ipv6

**Comment by Huang-Wei** [comment]
@liggitt I tried to test the flaky tests for 20 times (https://github.com/kubernetes/kubernetes/pull/86400#issuecomment-573809427) and they all get passed (failures of each are caused by other flakes)

So I'm gonna 
/hold cancel

**Comment by liggitt** [comment]
Thanks for the diligence and for the fix
