### PR TITLE
Flush conntrack state for removed/changed UDP Services

### LINKED ISSUE #19029: iptables kube-proxy could handle UDP backend changes better
I encountered a strange issue after opting-in to kube-proxy iptables support.

Steps to repro (I think):
1. Create a Service for a UDP port (say 8125; in my case, this was statsd)
2. Create pods that bind to this Service
3. Start a client Pod that uses the Service, e.g. via environment variable which specifies the VIP for the Service. This client writes a UDP packet to the Service every 10 seconds using the same socket (e.g. DialUDP is only called once)
4. Log in to the node. Use [ngrep](http://conntrack-tools.netfilter.org/) -q '' udp port 8125  to view the outgoing UDP traffic from the box to the service port. Observe that rewriting has occurred, and the packet is destined to one of the concrete endpoints specified in the Kubernetes model.
5. Delete that endpoint by, for example, killing the corresponding Pod which the client is communicating with
6. Observe that the Pod's IP no longer appears in endpoints (e.g. using kubectl)
7. BUG: Observe that ngrep continues to report that the packets are being rewritten to the old endpoint.
8. BUG (corollary): Observe that [conntrack](http://conntrack-tools.netfilter.org/) -L -d SERVICE_VIP shows that same socket being routed to the old endpoint.
9. WORKAROUND: Restart the client Pod, or have the client Pod call DialUDP each time it needs to send data.

The only solution i can see is that kube-proxy, when it rewrites iptables rules based on endpoints changes, needs to reset connections between local sockets and destroyed endpoints.

This didn't happen with the userspace kube-proxy, because kube-proxy was accepting the packets locally regardless of the endpoints, and would always use the latest endpoints information to forward the packet on.

Sorry for the long bug report, but I think it should be pretty clear by now if you've made it here. :)

### PR DESCRIPTION
**Pull request by freehan**
fixes: #19029

### CODE REVIEW

File: build/debian-iptables/Makefile [hunk 1]
```diff
@@ -18,7 +18,8 @@ IMAGE = debian-iptables
 TAG = v1
 
 build:
-	docker build -t gcr.io/google_containers/$(IMAGE):$(TAG) .
+	#docker build -t gcr.io/google_containers/$(IMAGE):$(TAG) .
```
Comment (freehan) [inline build/debian-iptables/Makefile]: i have revert this.

File: build/common.sh [hunk 2]
```diff
@@ -103,7 +103,8 @@ kube::build::get_docker_wrapped_binaries() {
           kube-apiserver,busybox
           kube-controller-manager,busybox
           kube-scheduler,busybox
-          kube-proxy,gcr.io/google_containers/debian-iptables:v1
+          #kube-proxy,gcr.io/google_containers/debian-iptables:v1
+          kube-proxy,gcr.io/mixia-kube/debian-iptables:v1
```
Comment (freehan) [inline build/common.sh]: i will revert this.

File: pkg/proxy/iptables/proxier.go [hunk 3]
```diff
@@ -552,6 +565,42 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+		}
+	}
+	return result
+}
+
+// refreshConnection deletes all service connections specified in the map to avoid hitting dead endpoints
+func (proxier *Proxier) refreshConnection(connectionMap map[string]proxy.ServicePortName) {
+	for endpoint, servicePortName := range connectionMap {
+		svcInfo := proxier.serviceMap[servicePortName]
+		if svcInfo.protocol == api.ProtocolUDP {
```
Comment (freehan) [inline pkg/proxy/iptables/proxier.go]: @ArtfulCoder suggest we delete all connections. Not only UDP ones.

Comment (ArtfulCoder) [inline pkg/proxy/iptables/proxier.go]: I don't have a strong opinion. We can leave it the way it is and let tcp stack take care of the cleanup.

**Comment by eparis** [comment]
Add the v1.2 milestone. Starting later today cherrypick-candidate will be removed from any PR that doesn't set the milestone.

File: pkg/proxy/iptables/proxier.go (hunk 3 above)
Comment (ArtfulCoder) [inline pkg/proxy/iptables/proxier.go]: The other thing is that just because an endpoint is removed doesn't imply that the pod is dead.
The tcp connection could still be active.
So we should probably only kill udp.

**Comment by freehan** [comment]
@googlebot  I signed it!

**Comment by freehan** [comment]
@k8s-bot test this please!

**Comment by freehan** [comment]
Ping @thockin

File: pkg/proxy/iptables/proxier.go [hunk 4]
```diff
@@ -491,12 +498,18 @@ func (proxier *Proxier) OnEndpointsUpdate(allEndpoints []api.Endpoints) {
 	// Remove endpoints missing from the update.
 	for name := range proxier.endpointsMap {
```
Comment (ArtfulCoder) [inline pkg/proxy/iptables/proxier.go]: do we handle the case : no endpoints deleted, but a service got deleted ?

File: pkg/proxy/iptables/proxier.go [hunk 5]
```diff
@@ -491,12 +498,18 @@ func (proxier *Proxier) OnEndpointsUpdate(allEndpoints []api.Endpoints) {
...
 		if !activeEndpoints[name] {
+			// record endpoints of unactive service to stale connections
```
Comment (ArtfulCoder) [inline pkg/proxy/iptables/proxier.go]: do we handle the case : no endpoints deleted, but a service got deleted ?

Comment (freehan) [inline pkg/proxy/iptables/proxier.go]: Good Catch! Added logic to clean up stale service connections

File: pkg/proxy/iptables/proxier.go [hunk 6]
```diff
@@ -552,6 +572,61 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+
+// deleteEndpointConnection deletes all udp service connections to specified endpoint in the map to avoid stale endpoints black hole traffic
+func (proxier *Proxier) deleteEndpointConnection(connectionMap map[endpointServicePair]bool) {
+	for epSvcPair := range connectionMap {
+		if svcInfo, ok := proxier.serviceMap[epSvcPair.servicePortName]; ok && svcInfo.protocol == api.ProtocolUDP {
+			endpointIP := strings.Split(epSvcPair.endpoint, ":")[0]
+			glog.V(2).Infof("Attempt to delete connection to service %s with natted destination %s", svcInfo.clusterIP.String(), endpointIP)
+			err := proxier.execConntrackTool("-D", "--orig-dst", svcInfo.clusterIP.String(), "--dst-nat", endpointIP, "-p", "udp")
+			if err != nil {
+				glog.Error("conntrack tool return with error: %v", err)
```
Comment (ArtfulCoder) [inline pkg/proxy/iptables/proxier.go]: should you say Errorf ?

File: pkg/proxy/iptables/proxier.go [hunk 7]
```diff
@@ -552,6 +572,61 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+	}
+}
+
+// deleteServiceConnection use conntrack-tool to delete udp connection specified by service ip
+func (proxier *Proxier) deleteServiceConnection(svcIPs []string) {
+	for _, ip := range svcIPs {
+		glog.V(2).Infof("Attempt to delete udp connection to service %s", ip)
+		err := proxier.execConntrackTool("-D", "--orig-dst", ip, "-p", "udp")
+		if err != nil {
+			glog.Error("conntrack tool return with error: %v", err)
```
Comment (ArtfulCoder) [inline pkg/proxy/iptables/proxier.go]: Errorf ?

**Comment by thockin** [comment]
I want this fix, but I'd rather patch it into 1.2.[123] when we have a little bit more confidence in it.  Removing from the milestsone.

**Comment by ravilr** [comment]
is this waiting on something?  with iptables proxy mode being the default in v1.2, and kube-dns being the only NS for pods with Clusterfirst policy, this could seriously affect dns resolutions in pods running on a v1.2 cluster, if kube-dns pods are restarted on node drain and similar occasions ?

File: pkg/util/slice/slice.go [hunk 8]
```diff
@@ -48,3 +48,13 @@ func ShuffleStrings(s []string) []string {
 	}
 	return shuffled
 }
+
+// StringInSlice checks if str is in slice s
+func StringInSlice(str string, s []string) bool {
```
Comment (thockin) [inline pkg/util/slice/slice.go]: API nits:

I would call this `HasString` and I would flip the args.  That way the caller says `slice.HasString(mySlice, str)`

File: pkg/util/slice/slice.go [hunk 9]
```diff
@@ -48,3 +48,13 @@ func ShuffleStrings(s []string) []string {
...
+	for _, v := range s {
```
Comment (thockin) [inline pkg/util/slice/slice.go]: minor optimization: this copies the string values.  If you use the index I think you save the copies.

```
for i := range s {
  is str == s[i]
```

File: pkg/proxy/iptables/proxier.go [hunk 10]
```diff
@@ -552,6 +572,61 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+	}
+}
+
+// deleteServiceConnection use conntrack-tool to delete udp connection specified by service ip
+func (proxier *Proxier) deleteServiceConnection(svcIPs []string) {
+	for _, ip := range svcIPs {
+		glog.V(2).Infof("Attempt to delete udp connection to service %s", ip)
+		err := proxier.execConntrackTool("-D", "--orig-dst", ip, "-p", "udp")
+		if err != nil {
+			glog.Errorf("conntrack tool return with error: %v", err)
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: nit: returned

File: pkg/proxy/iptables/proxier.go [hunk 11]
```diff
@@ -552,6 +572,61 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+				glog.Errorf("conntrack tool return with error: %v", err)
+			}
+		}
+	}
+}
+
+// deleteServiceConnection use conntrack-tool to delete udp connection specified by service ip
+func (proxier *Proxier) deleteServiceConnection(svcIPs []string) {
+	for _, ip := range svcIPs {
+		glog.V(2).Infof("Attempt to delete udp connection to service %s", ip)
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: nit: I would say "Deleting UDP connections to service IP %s".  "attempt" is not helpful

File: pkg/proxy/iptables/proxier.go [hunk 12]
```diff
@@ -552,6 +572,61 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+			glog.Errorf("conntrack tool return with error: %v", err)
+		}
+	}
+}
+
+//execConntrackTool executes conntrack tool using given paramters
+func (proxier *Proxier) execConntrackTool(parameters ...string) error {
+	conntrackPath, err := proxier.exec.LookPath("conntrack")
+	if err != nil {
+		return fmt.Errorf("Error looking for path of conntrack-tool: %v", err)
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: nit: s/conntrack-tool/conntrack/

File: pkg/proxy/iptables/proxier.go [hunk 13]
```diff
@@ -552,6 +572,61 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+	}
+	output, err := proxier.exec.Command(conntrackPath, parameters...).CombinedOutput()
+	if err != nil {
+		return fmt.Errorf("Conntrack command returns %s, error message: %v", output, err)
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: conntrack failed: %v, output: %s

File: pkg/proxy/iptables/proxier.go [hunk 14]
```diff
@@ -480,7 +490,11 @@ func (proxier *Proxier) OnEndpointsUpdate(allEndpoints []api.Endpoints) {
 			svcPort := proxy.ServicePortName{NamespacedName: types.NamespacedName{Namespace: svcEndpoints.Namespace, Name: svcEndpoints.Name}, Port: portname}
 			curEndpoints := proxier.endpointsMap[svcPort]
 			newEndpoints := flattenValidEndpoints(portsToEndpoints[portname])
+			removedEndpoints := getRemovedEndpoints(curEndpoints, newEndpoints)
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: move this inside the if below?

File: pkg/proxy/iptables/proxier.go [hunk 15]
```diff
@@ -552,6 +572,61 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
 	return utiliptables.Chain("KUBE-SEP-" + encoded[:16])
 }
 
+// getRemovedEndpointIPs returns the endpoint IPs that are missing in the new endpoints
+func getRemovedEndpoints(curEndpoints, newEndpoints []string) []string {
+	var result []string
+	epSet := sets.NewString(newEndpoints...)
+	for _, ep := range curEndpoints {
+		if epSet.Has(ep) {
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: don't you want the opposite of this?  If the new set DOESN'T have the ep it is removed.  Or am I misunderstanding this?

File: pkg/proxy/iptables/proxier.go [hunk 16]
```diff
@@ -552,6 +572,61 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
 	return utiliptables.Chain("KUBE-SEP-" + encoded[:16])
 }
 
+// getRemovedEndpointIPs returns the endpoint IPs that are missing in the new endpoints
+func getRemovedEndpoints(curEndpoints, newEndpoints []string) []string {
+	var result []string
+	epSet := sets.NewString(newEndpoints...)
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: suggest newSet as the name.

File: pkg/proxy/iptables/proxier.go [hunk 17]
```diff
@@ -552,6 +572,61 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
 	return utiliptables.Chain("KUBE-SEP-" + encoded[:16])
 }
 
+// getRemovedEndpointIPs returns the endpoint IPs that are missing in the new endpoints
+func getRemovedEndpoints(curEndpoints, newEndpoints []string) []string {
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: could this whole function be

```
return sets.NewString(curEndpoints).Difference(sets.NewString(newEndpoints))
```

File: pkg/util/slice/slice.go (hunk 8 above)
Comment (thockin) [inline pkg/util/slice/slice.go]: Need a robust unit test for this function

File: pkg/proxy/iptables/proxier.go (hunk 17 above)
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: Need a robust unit test for this function proving the polarity

File: pkg/proxy/iptables/proxier.go [hunk 18]
```diff
@@ -552,6 +572,61 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+			err := proxier.execConntrackTool("-D", "--orig-dst", svcInfo.clusterIP.String(), "--dst-nat", endpointIP, "-p", "udp")
+			if err != nil {
+				glog.Errorf("conntrack tool return with error: %v", err)
+			}
+		}
+	}
+}
+
+// deleteServiceConnection use conntrack-tool to delete udp connection specified by service ip
+func (proxier *Proxier) deleteServiceConnection(svcIPs []string) {
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: need a unit test for this with an injected exec that proves the right command gets executed

File: pkg/proxy/iptables/proxier.go (hunk 10 above)
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: If this actually fails ... then what?  We will lose track of the fact that we need to flush the connection.  Can we do better?

What if we set a conntrack mark and you could rectify-loop this?  You know the set of all UDP services.  Any UDP connection that has the mark and is not a known service could be flushed.

Maybe it's not necessary?  I would at least comment it so we know we considered it and decided not to do it.

File: pkg/proxy/iptables/proxier.go [hunk 19]
```diff
@@ -552,6 +572,61 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+	}
+	return result
+}
+
+type endpointServicePair struct {
+	endpoint        string
+	servicePortName proxy.ServicePortName
+}
+
+// deleteEndpointConnection deletes all udp service connections to specified endpoint in the map to avoid stale endpoints black hole traffic
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: This comment should be clearer.  Someting like 

```
// After a UDP endpoint has been removed, we must flush any pending conntrack entries to it, or else we
// risk sending more traffic to it, all of which will be lost (because UDP).
```

Maybe clarify the comment on the next func, too.

Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: Also comment that this assumes the Proxier mutex is held.

File: pkg/proxy/iptables/proxier.go [hunk 20]
```diff
@@ -552,6 +572,61 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+func (proxier *Proxier) deleteEndpointConnection(connectionMap map[endpointServicePair]bool) {
+	for epSvcPair := range connectionMap {
+		if svcInfo, ok := proxier.serviceMap[epSvcPair.servicePortName]; ok && svcInfo.protocol == api.ProtocolUDP {
+			endpointIP := strings.Split(epSvcPair.endpoint, ":")[0]
+			glog.V(2).Infof("Attempt to delete connection to service %s with natted destination %s", svcInfo.clusterIP.String(), endpointIP)
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: Same as other comment.  "attempt" is a waste

"Deleting UDP connections to service IP %s, endpoint IP %s"

File: pkg/proxy/iptables/proxier.go [hunk 21]
```diff
@@ -552,6 +572,61 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+			err := proxier.execConntrackTool("-D", "--orig-dst", svcInfo.clusterIP.String(), "--dst-nat", endpointIP, "-p", "udp")
+			if err != nil {
+				glog.Errorf("conntrack tool return with error: %v", err)
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: returned

Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: see below comment on what happens if this actually fails.

**Comment by thockin** [comment]
Looks OK but no tests!!

**Comment by thockin** [comment]
Needs a release note and I am flagging as a cherrypick-candidate for 1.2

Minhan, whats up with your CLA?

File: pkg/proxy/iptables/proxier.go (hunk 10 above)
Comment (freehan) [inline pkg/proxy/iptables/proxier.go]: Mark connections and delete them in a loop later sounds like a good idea. This also avoid noop conntrack deletes because there maybe no connections to the dead endpoint.

**Comment by freehan** [comment]
I signed it!

**Comment by freehan** [comment]
Will submit new one. Plus more tests.

**Comment by roberthbailey** [comment]
This PR will be considered for a cherry pick once it has merged into the master branch.

**Comment by freehan** [comment]
@thockin Ready for another round

File: pkg/proxy/iptables/proxier.go [hunk 22]
```diff
@@ -70,6 +71,8 @@ const kubeMarkMasqChain utiliptables.Chain = "KUBE-MARK-MASQ"
 // TODO(thockin): Remove this for v1.3 or v1.4.
 const oldIptablesMasqueradeMark = "0x4d415351"
 
+const noConnectionToDelete = "0 flow entries have been deleted"
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: nit: put this nearer to where it is used?  or wrap it in a util function near where it is used

File: pkg/proxy/iptables/proxier.go [hunk 23]
```diff
@@ -434,15 +439,21 @@ func (proxier *Proxier) OnServiceUpdate(allServices []api.Service) {
 		}
 	}
 
+	staleUDPService := sets.NewString()
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: nit for reading: Services (plural)

File: pkg/proxy/iptables/proxier.go [hunk 24]
```diff
@@ -552,6 +575,62 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+
+type endpointServicePair struct {
+	endpoint        string
+	servicePortName proxy.ServicePortName
+}
+
+// After a UDP endpoint has been removed, we must flush any pending conntrack entries to it, or else we
+// risk sending more traffic to it, all of which will be lost (because UDP).
+// This assumes the proxier mutex is held
+func (proxier *Proxier) deleteEndpointConnection(connectionMap map[endpointServicePair]bool) {
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: This should be Connections (plural)

File: pkg/proxy/iptables/proxier.go [hunk 25]
```diff
@@ -552,6 +575,62 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+	for epSvcPair := range connectionMap {
+		if svcInfo, ok := proxier.serviceMap[epSvcPair.servicePortName]; ok && svcInfo.protocol == api.ProtocolUDP {
+			endpointIP := strings.Split(epSvcPair.endpoint, ":")[0]
+			glog.V(2).Infof("Deleting connection to service IP %s, endpoint IP %s", svcInfo.clusterIP.String(), endpointIP)
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: s/connection/connections/

In fact maybe be more explicit and say "connection tracking state for"

File: pkg/proxy/iptables/proxier.go [hunk 26]
```diff
@@ -552,6 +575,62 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+			err := proxier.execConntrackTool("-D", "--orig-dst", svcInfo.clusterIP.String(), "--dst-nat", endpointIP, "-p", "udp")
+			if err != nil && !strings.Contains(err.Error(), noConnectionToDelete) {
+				// TO DO: Better handling for deletion failure. When failure occur, stale udp connection may not get flushed.
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: TODO

File: pkg/proxy/iptables/proxier.go [hunk 27]
```diff
@@ -552,6 +575,62 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+				// These stale udp connection will keep black hole traffic. Making this a best effort operation for now, since it
+				// is expensive to baby sit all udp connections to kubernetes services.
+				glog.Errorf("conntrack return with error: %v", err)
+			}
+		}
+	}
+}
+
+// deleteServiceConnection use conntrack-tool to delete udp connection specified by service ip
+func (proxier *Proxier) deleteServiceConnection(svcIPs []string) {
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: Connections

File: pkg/proxy/iptables/proxier.go [hunk 28]
```diff
@@ -552,6 +575,62 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+	for _, ip := range svcIPs {
+		glog.V(2).Infof("Deleting udp connection to service IP %s", ip)
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: this comment should be the same as whatever you decide for above, minus the endpoint bits.  I like "connection tracking state" because it is more obvious.

Also s/udp/UDP/

File: pkg/proxy/iptables/proxier.go [hunk 29]
```diff
@@ -552,6 +575,62 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+		err := proxier.execConntrackTool("-D", "--orig-dst", ip, "-p", "udp")
+		if err != nil && !strings.Contains(err.Error(), noConnectionToDelete) {
+			// TO DO: Better handling for deletion failure. When failure occur, stale udp connection may not get flushed.
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: TODO

File: pkg/proxy/iptables/proxier.go [hunk 30]
```diff
@@ -552,6 +575,62 @@ func servicePortEndpointChainName(s proxy.ServicePortName, protocol string, endp
...
+
+//execConntrackTool executes conntrack tool using given paramters
+func (proxier *Proxier) execConntrackTool(parameters ...string) error {
+	conntrackPath, err := proxier.exec.LookPath("conntrack")
+	if err != nil {
+		return fmt.Errorf("Error looking for path of conntrack: %v", err)
+	}
+	output, err := proxier.exec.Command(conntrackPath, parameters...).CombinedOutput()
+	if err != nil {
+		return fmt.Errorf("Conntrack command returns: %s, error message: %s", string(output), err)
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: s/returns/returned/

Maybe make the stdout a %q ?

**Comment by thockin** [comment]
Thanks!  just a bunch of nits left.  You can self-LGTM when done.

**Comment by thockin** [comment]
Don't forget a good release note!

**Comment by roberthbailey** [comment]
If we want to get this into 1.2.3 we should get the tests passing and get it merged into the master branch today.

**Comment by freehan** [comment]
@k8s-bot unit test this

**Comment by thockin** [comment]
I re-titled this for release notes

**Comment by zmerlynn** [comment]
@freehan: Please create a cherrypick PR for this tomorrow if possible, if you want this included in 1.2.3.

**Comment by zmerlynn** [comment]
I tried to create a cherrypick for this as well, and it's going to need some work:
```
+++ Conflicts detected:

UU build/common.sh
UU build/debian-iptables/Dockerfile
UU build/debian-iptables/Makefile
UU pkg/proxy/iptables/proxier.go

```

**Comment by freehan** [comment]
@zmerlynn Thanks for reminding!
