### PR TITLE
Fix volume remount on reboot

### LINKED ISSUE #51982: Volumes are not mounted after rebooting a node. (Effects Flexvolume/FC/ISCSI)
/kind bug

**What happened**:
Volumes used by pod are not getting mounted after rebooting a node. Effects Flexvolume/FC/ISCSI volume types. Pod goes into running state using local file system path.

**What you expected to happen**
Volume should be mounted and pod should not go into running state if the volume fails to attach.

**How to reproduce it (as minimally and precisely as possible)**:
Create a RS with Flexvolume/FC/ISCSI. Reboot the node. Volume would not be mounted after reboot.

**Anything else we need to know?**:
- Kubelet on a process restart avoids remounting the volume. The same code path is used on a node reboot and it avoids remounting the volume.
- GCE, AWS etc seems to be working by chance as the SPEC reconstruction fails when a volume is not mounted on reboot.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.6.9
- Cloud provider or hardware configuration**: Baremetal
- OS (e.g. from /etc/os-release): Centos 7.2
- Kernel (e.g. `uname -a`): 3.10.0-327.el7.x86_64

### PR DESCRIPTION
**Pull request by chakri-nelluri**
**What this PR does / why we need it**:
Check the mount is actually attached & mounted before marking actual state of world of Kubelet reconciler.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #51982  

**Special notes for your reviewer**:
Added explicit check to make sure volumes are attached and are mounted before marking the state in actual state of world.

**Release note**:
```release-note
Fix Flexvolume/FC/ISCSI volumes not being mounted after Node reboot.
```

### CODE REVIEW

File: pkg/kubelet/volumemanager/reconciler/reconciler.go [hunk 1]
```diff
@@ -462,6 +464,31 @@ func (rc *reconciler) reconstructVolume(volume podVolume) (*reconstructedVolume,
...
+				"AttachableVolumePlugin.NewAttacher failed for volume %q (spec.Name: %q) pod %q (UID: %q) with: %v",
+				uniqueVolumeName,
+				volumeSpec.Name(),
+				volume.podName,
+				pod.UID,
+				newAttacherErr)
+		}
+
+		var getDeviceMountPathErr error
+		deviceMountPath, getDeviceMountPathErr = attacher.GetDeviceMountPath(volumeSpec)
```
Comment (jingxu97) [inline pkg/kubelet/volumemanager/reconciler/reconciler.go]: For flex volume, what this will return?

Comment (chakri-nelluri) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: It returns the mount path where the volume is expected to be mounted.

File: pkg/kubelet/volumemanager/reconciler/reconciler.go [hunk 2]
```diff
@@ -521,17 +554,30 @@ func (rc *reconciler) updateStates(volumesNeedUpdate map[v1.UniqueVolumeName]*re
...
+					volume.deviceMountPath,
+					err)
 				continue
+			} else if !isNotMount {
+				err = rc.actualStateOfWorld.MarkDeviceAsMounted(volume.volumeName)
+				if err != nil {
+					glog.Errorf("Could not mark device is mounted to actual state of world: %v", err)
+					continue
+				}
+				glog.Infof("Volume: %v is mounted", volume.volumeName)
```
Comment (jingxu97) [inline pkg/kubelet/volumemanager/reconciler/reconciler.go]: I think we can put the check of mountpoint into reconstructVolume function. If it is not a mountpoint, fail to reconstruct volume directly. This way, no need to add deviceMountPath into the reconstructedVolume data structure

Comment (chakri-nelluri) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: Isn't it a odd place for doing a mount check? mount check has nothing to do with reconstruction right?

Comment (jingxu97) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: the reason for reconstruction is mainly because when kubelet restarts, we don't have the cached state information. If there are mounts left on the node, we should reconstruct it. But if we checked that the mounts no longer exist, we can ignore it without reconstructing the volume back to actual state, I think.

Comment (chakri-nelluri) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: Ok. It is infact then "reconstructActualStateofVolume". It would work, the only minor concern is failing reconstruction because a volume is not mounted. Volume is an object and mount is one of the intermediate states of volume. We are combining both.

Comment (jingxu97) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: yeah, the function name is not very clear. I am fine with changing it to reconstuctActualStateofVolume. We have to reconstruct the spec because it is needed in the actual state.

**Comment by jingxu97** [comment]
@chakri-nelluri After checking the code in other volume plugins for ConstructVolumeSpec, I am thinking we could follow the same way by calling  mounter.GetDeviceNameFromMount(), if no device is returned, constructVolumeSpec failed because it shows that the global mount path is no longer here. 
Does it make sense?

**Comment by chakri-nelluri** [comment]
@jingxu97 IMHO it would make sense for this to be part of the infra, rather than having each plugin do the same logic. Also the constructVolumeSpec by the name goes, it just a helper function to reconstruct the spec. Other plugins, my assumption are working by chance as they require to check the mount to construct the volume spec.

@saad-ali @rootfs @childsb any preference.

**Comment by ailusazh** [comment]
What about just comment out these lines of the code, as follows:
```
		//if volume.pluginIsAttachable {
		//	err = rc.actualStateOfWorld.MarkDeviceAsMounted(volume.volumeName)
		//	if err != nil {
		//		glog.Errorf("Could not mark device is mounted to actual state of world: %v", err)
		//		continue
		//	}
		//}
```
In this way, the reconciler in volumemanager will remount all the attachable volumes. And for the situation of just restart kubelet and didn't reboot the node , when reconciler try to remount, the method MountDevice in attacher and SetUp in mounter will check whether the dir is mounted, if already mounted, they will return nil and the mount volume operation will be succeed.

**Comment by dixudx** [comment]
> What about just comment out these lines of the code

@ailusazh They are useful. Just commenting out these lines will not help fix the remount issue, but may bring in other potential ones.

**Comment by ailusazh** [comment]
chakri-nelluri's fixed way considered more, but this will cause the unmounted volumes reattached, what abount reattach failed?

**Comment by ailusazh** [comment]
@dixudx, can you think of any specific potential problems?

**Comment by chakri-nelluri** [comment]
@ailusazh Even, if we just comment out that code, it will not to remount the same volume, as attach & remount are always kicked from the same operation.

The initial PR has a check just about this code block to verify whether the volume was actually mounted or not, before marking it mounted. On @jingxu97 initial feedback, we decided to fail the actual reconstructVolume call, in case a volume is not mounted.

**Comment by chakri-nelluri** [comment]
@ailusazh When attachdetach controller is enabled we would not reattach the volume. When attachdetach controller is disabled, volumes are reattached on node restart, which was always the case. The code does not change the behavior for Kubelet restart.

**Comment by jingxu97** [comment]
The logic behind reconstructing desired and actual state supposed be to in the following sequence 
1. When controller starts, reconstruct the desired state first by listing all the pods and their volumes.
2. After desired state is filled, reconstruct volume in actual state only if the volume is not in desired state, because controller might not have enough information to fully reconstruct the actual state. Only if the volume is no longer in desired state, reconstruct with partial information is ok because volume tear down does not really need the full information. The reconstruction process varies with different volume plugins, some might check mount points because they need this information, some don't. 

But because of another race condition issue related to node status update, the current code is not really implemented as above design. In the first round of syncState, even if the volume is in desired state, reconciler still tries to reconstruct the actual state with partial information. see code https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler.go#L394

I feel this is not good and cause the issue you are trying to fix here. I am thinking to use a separate cache to represent what is discovered from the disk instead of directly updating the actual state. I need to think through and have a proposal for it. 

@chakri-nelluri Your approach checks the global device mount path, but it is also possible that global device path exists, but bind mount is gone, I think. To fully solve this issue, we might also need to check the bind mount. 
For now I am ok with your change, just a small comment. Otherwise lgtm. It would be very nice if we could have an e2e test for it.

File: pkg/kubelet/volumemanager/reconciler/reconciler.go [hunk 3]
```diff
@@ -462,6 +462,42 @@ func (rc *reconciler) reconstructVolume(volume podVolume) (*reconstructedVolume,
 			newMounterErr)
 	}
 
+	deviceMountPath := ""
+	if attachablePlugin != nil {
```
Comment (jingxu97) [inline pkg/kubelet/volumemanager/reconciler/reconciler.go]: Could you add a comment for this part of checking?

Comment (jingxu97) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: Also move this part above the defination of volumeMounter?

Comment (chakri-nelluri) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: Ack

**Comment by ailusazh** [comment]
Understand, thank you for your explanation.

**Comment by ailusazh** [comment]
Just comment out the code will still cause the following issue:
> This is to prevent node status from being updated to empty for attachable volumes. This might happen because in the case that a volume is discovered on disk, and it is part of desired state, but is then quickly deleted from the desired state. If in such situation, the volume is not added to the actual state, the node status updater will not get this volume from either actual or desired state. In turn, this might cause master controller detaching while the volume is still mounted.

**Comment by rootfs** [comment]
cc @mtanino

**Comment by rootfs** [comment]
@chakri-nelluri @jingxu97 FC/iSCSI attach volumes in `WaitForAttach`, how is this function triggered during reconstruct?

**Comment by mtanino** [comment]
@chakri-nelluri @jingxu97 @rootfs 

At the v1.6.9 which is mentioned on the original bug report, FC and iSCSI didn't have attacher code, but on the latest master theses plugins have attacher.
If backport of this fix is necessary, we need to consider both cases.

**Comment by jingxu97** [comment]
@rootfs, I don't think waitForAttach is triggered in the process of reconstruct. It is only used during MountVolume oepration.

**Comment by jingxu97** [comment]
After checking the code again, I think this fix still has an issue.

For flexvolume, iscsi, or fc, currently the ConstructVolumeSpec function use fake information to fill in the the spec. So when attacher uses GetDeviceMountPath, it will construct the wrong path. So this check mount point will always fail. The result is that the volume will not be updated into the actual state no matter what. So the mount points will never be cleaned up in the situation that kubelet restarts and pod is deleted around the same time.

**Comment by chakri-nelluri** [comment]
@rootfs For FC & ISCSI construct volume spec constructions is filling in dummy information, but the mount paths are initially constructed using the spec information. I think it would be an issue. Can you check and see if we have the issues.
Flexvolume does not depend on any of the information in the actual spec, for mount path construction except the volume name. So, it works fine.

@jingxu97 Looking at the logic, irrespective of where we do the check, we should still have the same issue with FC & ISCSI.

**Comment by jingxu97** [comment]
@chakri-nelluri reconstruction process happens after the volume sets up, so dummy information is ok as long as it can tear down (unmount) correctly.

The check I mentioned is GetDeviceNameFromMount(), it uses a different way of getting the device mount path. It lists all the mount paths and find a matching one that has the same device with the bind mount. It is not constructed by the VolumeSpec which might has the wrong information.

**Comment by chakri-nelluri** [comment]
Thanks @jingxu97 for the insight. I see your point.

I have to test it out, but will it help if we check `isLikelyNotMountPoint(volume.mountpath)`?

**Comment by jingxu97** [comment]
@chakri-nelluri you mean  by checking isLikelyNotMountPoint(volume.mountpath) , the problem can be solved? 
Not really, I think. volume.mountpath is the bind mount path. The device mount path is different.

**Comment by ailusazh** [comment]
According to the code, device mount path mount first, then bind mount path mount. So is there a situation that bind mount path is a mount point and device mount path is not a mount point?

**Comment by chakri-nelluri** [comment]
@jingxu97 it works. If the actual device is not mounted, IsLikelyNotMountPath using bind mount path returns true(not mounted). Actually we use the same check in SetupAt/Teardown path.

I verified it rebooting the system. PTAL and let me know if you see any issues with this approach.

**Comment by jingxu97** [comment]
@chakri-nelluri, I see the point. So the solution is first checking the bind mount path. If it exists (indicates the global device mount path exist too), update the actual state. If bind mount no long exists (global mount might exist or not), don't update it to the actual state.  
I think it largely solve the problem. The only concern is that with this check, the global device mount might still exist. Attach_detach_controller will detach in this case since actual state does not has this volume so it will not be updated in VolumeInUser.

**Comment by jingxu97** [comment]
@chakri-nelluri I am ok with this change now. It would be nice if we could add some e2e test for this. THanks!

File: pkg/kubelet/volumemanager/reconciler/reconciler.go [hunk 4]
```diff
@@ -448,6 +448,19 @@ func (rc *reconciler) reconstructVolume(volume podVolume) (*reconstructedVolume,
 		uniqueVolumeName = volumehelper.GetUniqueVolumeNameForNonAttachableVolume(volume.podName, plugin, volumeSpec)
 	}
 
+	if attachablePlugin != nil {
+		if isNotMount, mountCheckErr := rc.mounter.IsLikelyNotMountPoint(volume.mountPath); mountCheckErr != nil {
```
Comment (ianchakeres) [inline pkg/kubelet/volumemanager/reconciler/reconciler.go]: @msau42 @jingxu97 @jsafrane - do you think that we need to use IsNotMountPoint here instead of IsLikelyNotMountPoint to avoid issues in the reconciler with respect to local volumes? For reference... https://github.com/kubernetes/kubernetes/pull/48402

Comment (jingxu97) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: @ianchakeres thanks for bring this up. I think we do need to consider this . But since IsNotMountPoint will list all the mounts, to reduce the overhead, maybe we can cache the mounts?

Comment (chakri-nelluri) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: @jingxu97 This particular check is for only attachable volumes and isLikelyNotMountPoint should work for attachable volumes. Do we still need it?

Comment (jingxu97) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: @chakri-nelluri  I first thought we should check the mount path for both attachable and non-attachable plugins. But in the current code workflow, if volume is not attachable, we only reconstruct if the the volume is not in desired state. So the reconstructed state will only be used by teardown operation (umount). So it is ok to not check the mount path exist or not. 
I am ok with this part of code. Thanks!

**Comment by chakri-nelluri** [comment]
@dchen1107 Please approve it when you get a chance. Thanks

**Comment by mtanino** [comment]
@chakri-nelluri 
just fyi, This PR doesn't have milestone tag. If the target is v1.8, milestone tag is required.

**Comment by chakri-nelluri** [comment]
Thanks @mtanino. Just requested @saad-ali to re-target.

**Comment by saad-ali** [comment]
@jdumars is it too late to get this in for 1.8.0? The associated bug (https://github.com/kubernetes/kubernetes/issues/51982) was mistakenly not tagged for 1.8.

**Comment by taherv** [comment]
We have a flexvol implementation for our storage device, and this bug fix is critical for our flexvol deliverable. Could we please please please have this for 1.8.
1.6 and 1.7 are also part of our customer base, what would it take to backport this fix to 1.6 and 1.7 ?

**Comment by spiffxp** [comment]
/assign @saad-ali 
for the `/approve`

I'm not sure why the bot is suggesting @dchen1107, saad's the only one listed in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/OWNERS

**Comment by jdumars** [comment]
@saad-ali this needs to get through today in order to ensure it makes 1.8

**Comment by chakri-nelluri** [comment]
We should cherrypick the fix to 1.6 & 1.7 releases too.

**Comment by chakri-nelluri** [comment]
@jingxu97 @saad-ali Please target it for 1.6 & 1.7 patch releases too. Thanks.

**Comment by saad-ali** [comment]
Marked as 1.7 cherry pick candidate. Once that's done we can do the same for 1.6

**Comment by saad-ali** [comment]
CC @wojtek-t, 1.7.x release manager for approval

**Comment by wojtek-t** [comment]
Cherrypick approved - cherrypick in https://github.com/kubernetes/kubernetes/pull/53368

**Comment by saad-ali** [comment]
Marked as 1.6 cherry pick candidate.
