### PR TITLE
kubelet: Sync completed pods until their containers have been terminated

### LINKED ISSUE #98718: Incorrect container status when pod exceeds activeDeadlineSeconds
**What happened**:
When pod exceeds `activeDeadlineSeconds` we find that,

```
status:
  containerStatuses:
  - containerID: cri-o://e3c8354c818791d37fb6fee96465075344ec2116f95edb5ddb3269d7d5d5f297
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:0415f56ccc05526f2af5a7ae8654baec97d4a614f24736e8eef41a4591f08019
    lastState: {}
    name: test
    ready: false
    restartCount: 0
    state:
      running:
        startedAt: "2021-02-01T12:29:17Z"
  message: Pod was active on the node longer than the specified deadline
  phase: Failed
  podIP: 10.128.2.23
  podIPs:
  - ip: 10.128.2.23
  qosClass: Burstable
  reason: DeadlineExceeded
  startTime: "2021-02-01T12:29:14Z"
  ```
The pod `phase` is correctly states `Failed` with the reason `DeadlineExceeded` but as you can see above the container state is still reported as `running` 

**What you expected to happen**:
Container state should be `Terminated` not `running` because pod has exceeded `activeDeadlineSeconds`

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
  apiVersion: v1
  kind: Pod
  metadata:
    name: test
  spec:
    activeDeadlineSeconds: 200
    terminationGracePeriodSeconds: 300
    containers:
    - args:
      - "600"
      command:
      - sleep
      image: docker.io/library/busybox
      imagePullPolicy: IfNotPresent
      name: test
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
```
Create the pod described above and wait till it exceeds listed `activeDeadlineSeconds`.  Then get the container status using,
`kubectl get -o yaml pod test | grep -A1000 '^status:'` 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `master` 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by gjkim42**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

This PR allows the kubelet to synchronize completed pods until their containers have been terminated.

If a pod was evicted, its `containerStatuses` were out of sync because `dispatchWork` did ignore works of the pods having completed.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/98718

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by gjkim42** [comment]
/cc @harche @rphillips @sjenning
Could you take a look at this? Thanks.

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -2022,8 +2022,9 @@ func (kl *Kubelet) dispatchWork(pod *v1.Pod, syncType kubetypes.SyncPodType, mir
 	}
 
 	// optimization: avoid invoking the pod worker if no further changes are possible to the pod definition
-	if podWorkerTerminal {
-		klog.V(4).Infof("Pod %q has completed, ignoring remaining sync work: %s", format.Pod(pod), syncType)
+	// (i.e. the pod has completed and its containers have been terminated)
+	if podWorkerTerminal && containersTerminal {
```
Comment (ehashman) [inline pkg/kubelet/kubelet.go:2026]: Could we get a unit test update to check for these cases?

**Comment by harche** [comment]
@gjkim42 Thanks for this PR. I did some testing, and while the PR seems to address the original issue I noticed a couple of things,

1. It takes a significant amount of time (about 5min in my testing) for the container status to change from `running` to `terminated` **after** pod phase has changed to `Failed` due to reason `DeadlineExceeded`. I am suspecting that's because my pod yaml has `terminationGracePeriodSeconds` set to [300](https://github.com/kubernetes/kubernetes/issues/98718#issue-800125055). 
```
 containerStatuses:
  - containerID: cri-o://235c3f643add7dbfc88fc3607918b652dabca435521a4e042bc27e61df6ff365
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:9f1c79411e054199210b4d489ae600a061595967adb643cd923f8515ad8123d2
    lastState: {}
    name: test
    ready: false
    restartCount: 0
    state:
      running:
        startedAt: "2021-02-05T09:26:31Z"
  message: Pod was active on the node longer than the specified deadline
  phase: Failed
  podIP: 10.85.0.44
  podIPs:
  - ip: 10.85.0.44
  - ip: 1100:200::2c
  qosClass: Burstable
  reason: DeadlineExceeded
  startTime: "2021-02-05T09:26:29Z"
```
and after a while the correct container state is reflected,
```
status:
  containerStatuses:
  - containerID: cri-o://235c3f643add7dbfc88fc3607918b652dabca435521a4e042bc27e61df6ff365
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:9f1c79411e054199210b4d489ae600a061595967adb643cd923f8515ad8123d2
    lastState: {}
    name: test
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: cri-o://235c3f643add7dbfc88fc3607918b652dabca435521a4e042bc27e61df6ff365
        exitCode: 137
        finishedAt: "2021-02-05T09:34:49Z"
        reason: Error
        startedAt: "2021-02-05T09:26:31Z"
  message: Pod was active on the node longer than the specified deadline
  phase: Failed
  podIP: 10.85.0.44
  podIPs:
  - ip: 10.85.0.44
  - ip: 1100:200::2c
  qosClass: Burstable
  reason: DeadlineExceeded
  startTime: "2021-02-05T09:26:29Z"
```
2. While the container state eventually changes to `terminated` the state.terminated.reason field shows `Error`. This could be misleading, but I am not sure if there is anything can be done about it. 
```
$ kubectl get -o yaml pod test3 | grep -A1000 '^status:'
status:
  containerStatuses:
  - containerID: cri-o://2637bcf1692585a4927d01cfa764b6f1b5902527c93c2f7ab2b8e6fb9326abfb
    image: docker.io/library/busybox:latest
    imageID: docker.io/library/busybox@sha256:9f1c79411e054199210b4d489ae600a061595967adb643cd923f8515ad8123d2
    lastState: {}
    name: test
    ready: false
    restartCount: 0
    state:
      terminated:
        containerID: cri-o://2637bcf1692585a4927d01cfa764b6f1b5902527c93c2f7ab2b8e6fb9326abfb
        exitCode: 137
        finishedAt: "2021-02-05T10:04:27Z"
        reason: Error
        startedAt: "2021-02-05T09:56:09Z"
  message: Pod was active on the node longer than the specified deadline
  phase: Failed
  podIP: 10.85.0.46
  podIPs:
  - ip: 10.85.0.46
  - ip: 1100:200::2e
  qosClass: Burstable
  reason: DeadlineExceeded
  startTime: "2021-02-05T09:56:07Z"
```

**Comment by gjkim42** [comment]
@harche Thanks for your comment.
> 1. It takes a significant amount of time (about 5min in my testing) for the container status to change from `running` to `terminated` **after** pod phase has changed to `Failed` due to reason `DeadlineExceeded`. I am suspecting that’s because my pod yaml has `terminationGracePeriodSeconds` set to [300](https://github.com/kubernetes/kubernetes/issues/98718#issue-800125055).
>
> ```
>  containerStatuses:
>   - containerID: cri-o://235c3f643add7dbfc88fc3607918b652dabca435521a4e042bc27e61df6ff365
>     image: docker.io/library/busybox:latest
>     imageID: docker.io/library/busybox@sha256:9f1c79411e054199210b4d489ae600a061595967adb643cd923f8515ad8123d2
>     lastState: {}
>     name: test
>     ready: false
>     restartCount: 0
>     state:
>       running:
>         startedAt: “2021-02-05T09:26:31Z”
>   message: Pod was active on the node longer than the specified deadline
>   phase: Failed
>   podIP: 10.85.0.44
>   podIPs:
>   - ip: 10.85.0.44
>   - ip: 1100:200::2c
>   qosClass: Burstable
>   reason: DeadlineExceeded
>   startTime: “2021-02-05T09:26:29Z”
> ```
Yes, it is because of `terminationGracePeriodSeconds`, I’ve confirmed it. However, isn’t it the expected behavior?

**Comment by gjkim42** [comment]
Regarding this, 
> 2. While the container state eventually changes to `terminated` the state.terminated.reason field shows `Error`. This could be misleading, but I am not sure if there is anything can be done about it.
> 
> ```
> $ kubectl get -o yaml pod test3 | grep -A1000 '^status:'
> status:
>   containerStatuses:
>   - containerID: cri-o://2637bcf1692585a4927d01cfa764b6f1b5902527c93c2f7ab2b8e6fb9326abfb
>     image: docker.io/library/busybox:latest
>     imageID: docker.io/library/busybox@sha256:9f1c79411e054199210b4d489ae600a061595967adb643cd923f8515ad8123d2
>     lastState: {}
>     name: test
>     ready: false
>     restartCount: 0
>     state:
>       terminated:
>         containerID: cri-o://2637bcf1692585a4927d01cfa764b6f1b5902527c93c2f7ab2b8e6fb9326abfb
>         exitCode: 137
>         finishedAt: "2021-02-05T10:04:27Z"
>         reason: Error
>         startedAt: "2021-02-05T09:56:09Z"
>   message: Pod was active on the node longer than the specified deadline
>   phase: Failed
>   podIP: 10.85.0.46
>   podIPs:
>   - ip: 10.85.0.46
>   - ip: 1100:200::2e
>   qosClass: Burstable
>   reason: DeadlineExceeded
>   startTime: "2021-02-05T09:56:07Z"
> ```

I agree that this could be misleading because the result of `kubectl get pods test` is as follows. I will check changing containerStatuses[*].state.terminated.reason to "Error" is intended behavior.

image

**Comment by harche** [comment]
> @harche Thanks for your comment.
> 
> > 1. It takes a significant amount of time (about 5min in my testing) for the container status to change from `running` to `terminated` **after** pod phase has changed to `Failed` due to reason `DeadlineExceeded`. I am suspecting that’s because my pod yaml has `terminationGracePeriodSeconds` set to [300](https://github.com/kubernetes/kubernetes/issues/98718#issue-800125055).
> > 
> > ```
> >  containerStatuses:
> >   - containerID: cri-o://235c3f643add7dbfc88fc3607918b652dabca435521a4e042bc27e61df6ff365
> >     image: docker.io/library/busybox:latest
> >     imageID: docker.io/library/busybox@sha256:9f1c79411e054199210b4d489ae600a061595967adb643cd923f8515ad8123d2
> >     lastState: {}
> >     name: test
> >     ready: false
> >     restartCount: 0
> >     state:
> >       running:
> >         startedAt: “2021-02-05T09:26:31Z”
> >   message: Pod was active on the node longer than the specified deadline
> >   phase: Failed
> >   podIP: 10.85.0.44
> >   podIPs:
> >   - ip: 10.85.0.44
> >   - ip: 1100:200::2c
> >   qosClass: Burstable
> >   reason: DeadlineExceeded
> >   startTime: “2021-02-05T09:26:29Z”
> > ```
> 
> Yes, it is because of `terminationGracePeriodSeconds`, I’ve confirmed it. However, isn’t it the expected behavior?

Yes it's the expected behaviour.

File: pkg/kubelet/kubelet.go (hunk 1 above)
Comment (gjkim42) [reply pkg/kubelet/kubelet.go:2024]: Updated tests.

File: pkg/kubelet/kubelet_test.go [hunk 2]
```diff
@@ -470,6 +470,133 @@ func TestSyncPodsDeletesWhenSourcesAreReadyPerQOS(t *testing.T) {
...
+				Phase: v1.PodFailed,
+				ContainerStatuses: []v1.ContainerStatus{
+					{
+						State: v1.ContainerState{
+							Running: &v1.ContainerStateRunning{},
+						},
+					},
+				},
+			},
+		},
```
Comment (gjkim42) [inline pkg/kubelet/kubelet_test.go:588]: This is the case of https://github.com/kubernetes/kubernetes/issues/98718.

**Comment by gjkim42** [comment]
> Regarding this,
> 
> > 2. While the container state eventually changes to `terminated` the state.terminated.reason field shows `Error`. This could be misleading, but I am not sure if there is anything can be done about it.
> > 
> > ```
> > $ kubectl get -o yaml pod test3 | grep -A1000 '^status:'
> > status:
> >   containerStatuses:
> >   - containerID: cri-o://2637bcf1692585a4927d01cfa764b6f1b5902527c93c2f7ab2b8e6fb9326abfb
> >     image: docker.io/library/busybox:latest
> >     imageID: docker.io/library/busybox@sha256:9f1c79411e054199210b4d489ae600a061595967adb643cd923f8515ad8123d2
> >     lastState: {}
> >     name: test
> >     ready: false
> >     restartCount: 0
> >     state:
> >       terminated:
> >         containerID: cri-o://2637bcf1692585a4927d01cfa764b6f1b5902527c93c2f7ab2b8e6fb9326abfb
> >         exitCode: 137
> >         finishedAt: "2021-02-05T10:04:27Z"
> >         reason: Error
> >         startedAt: "2021-02-05T09:56:09Z"
> >   message: Pod was active on the node longer than the specified deadline
> >   phase: Failed
> >   podIP: 10.85.0.46
> >   podIPs:
> >   - ip: 10.85.0.46
> >   - ip: 1100:200::2e
> >   qosClass: Burstable
> >   reason: DeadlineExceeded
> >   startTime: "2021-02-05T09:56:07Z"
> > ```
> 
> I agree that this could be misleading because the result of `kubectl get pods test` is as follows. I will check changing containerStatuses[*].state.terminated.reason to "Error" is intended behavior.
> 
> image

The code below sets `reason` to `Error`.
https://github.com/kubernetes/kubernetes/blob/25d5d657c717a1aa77df67803767c98a263ca1de/pkg/kubelet/dockershim/docker_container.go#L403-L415

I think setting `containerStatuses[*].state.terminated.reason` to `Error` is not a bug.

Perhaps we can discuss what should be the desired value of the `STATUS` field of the result of `kubectl get pods test`.

**Comment by harche** [comment]
> 
> The code below sets `reason` to `Error`.
> https://github.com/kubernetes/kubernetes/blob/25d5d657c717a1aa77df67803767c98a263ca1de/pkg/kubelet/dockershim/docker_container.go#L403-L415
> 
> I think setting `containerStatuses[*].state.terminated.reason` to `Error` is not a bug.
> 

I agree.

**Comment by sjenning** [comment]
xref https://github.com/kubernetes/kubernetes/pull/88440

**Review by harche — APPROVED** [review]
/lgtm

**Comment by gjkim42** [comment]
/assign @klueska
Could you take a look at and approve this?

**Comment by smarterclayton** [comment]
It looks like this partially regressed very short running pod behavior (create -> <short> -> delete -> <very long cleanup>).  That's because there's a race condition between the check done here and the PLEG - it's not safe for dispatchWork to check statusManager in podAndContainersAreTerminal because statusManager is out of date at the time the PLEG entry shows up.

We need to fix the fundamental problem that these two optimizations were aimed at, but we can't do that safely without synthesizing the podCache data from PLEG.  Ultimately the syncPod loop is the one responsible for this calculation and we need to fix the problems that led to us pulling logic outside of it.

https://github.com/kubernetes/kubernetes/pull/102025#issuecomment-843622820

This may have impacted the change, but it didn't actually solve it.  We'll be opening a new issue to address the root cause.
