### PR TITLE
not allowing "kubectl edit <resource>" when you got an empty list

### LINKED ISSUE #50147: kubectl edit panics when you have an empty list
Try running `kubectl edit ingress` and adding an ingress object, or an empty list, then exit the editor – it will panic like this:

```
panic: runtime error: index out of range

goroutine 1 [running]:
k8s.io/kubernetes/pkg/kubectl/cmd/util/editor.(*EditOptions).Run.func1(0x3b7f0f8, 0x0, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/editor/editoptions.go:237 +0xed2
k8s.io/kubernetes/pkg/kubectl/cmd/util/editor.(*EditOptions).Run(0xc420158400, 0x3a6c900, 0xc420239710)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/editor/editoptions.go:334 +0x731
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdEdit.func1(0xc420376480, 0xc420273ac0, 0x1, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/edit.go:99 +0x15b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc420376480, 0xc420273a50, 0x1, 0x1, 0xc420376480, 0xc420273a50)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:603 +0x22b
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420453b00, 0x8000101, 0x0, 0xffffffffffffffff)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:689 +0x339
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420453b00, 0xc420239710, 0x3a46140)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:648 +0x2b
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:39 +0xd5
main.main()
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:26 +0x22

```

I've also tried `kubectl edit ds`, and for the sake of experiment tried adding a Pod, then it failed rather gracefully with this message:
```
A copy of your changes has been stored to "/var/folders/zr/qjxvg8xn10nd06j2vflwtj880000gn/T/kubectl-edit-0133o.yaml"
error: no original object found for &unstructured.Unstructured{Object:map[string]interface {}{"apiVersion":"v1", "kind":"Pod", "metadata":map[string]interface {}{"namespace":"default"}}}
```
But when I tried to add a DaemonSet, it paniced.

I am not sure how we should fix, perhaps editing of lists isn't something a normal user is expected to do... Let's discuss.

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:
`kubectl edit` will panic when adding an empty list.

> panic: runtime error: index out of range

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50147

**Special notes for your reviewer**:
/assign @errordeveloper @mengqiy @janetkuo @fabianofranz
/cc @rootfs @soltysh @sttts

**Release note**:

```release-note
not allowing "kubectl edit <resource>" when you got an empty list
```

### CODE REVIEW

**Comment by mengqiy** [comment]
@dixudx Please add a test to prevent regression.

**Comment by dixudx** [comment]
@mengqiy The log msg [`no original object found for %#v`](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/util/editor/editoptions.go#L525-L527) is a little bit confusing for users. Actually it means that the resource you are editing used to be empty. @shiywang Could we modify it to be more explicit, such as `The resource you're editing used to be empty. Please use "kubectl create" instead of "kubectl edit"`.

/cc @errordeveloper

**Comment by dixudx** [comment]
@errordeveloper Would you please provide the yaml file you're using against panics. I'm unable to reproduce that when adding new testcases.

**Comment by shiywang** [comment]
> such as The resource you're editing used to be empty. Please use "kubectl create" instead of "kubectl edit".

I think `kubectl edit <kind>`  with an empty list only appear when `no resources found`, I was wondering why we prompt the error message at the beginning like`no resources found can not open editor...Please use "kubectl create" instead of "kubectl edit"..` instead of open an empty list with editor for users? 
@kubernetes/sig-cli-misc

File: pkg/kubectl/cmd/util/editor/editoptions.go [hunk 1]
```diff
@@ -391,7 +393,7 @@ func (o *EditOptions) visitToApplyEditPatch(originalInfos []*resource.Info, patc
 			}
 		}
 		if originalInfo == nil {
-			return fmt.Errorf("no original object found for %#v", info.Object)
+			return fmt.Errorf("no original object found")
```
Comment (shiywang) [inline pkg/kubectl/cmd/util/editor/editoptions.go]: why remove that ?

Comment (dixudx) [inline pkg/kubectl/cmd/util/editor/editoptions.go]: See [this bazel test](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/50205/pull-kubernetes-bazel/34592/).

This test passed on Mac. But failed due to this disordered string. Kind of weird that `%#v` produces different Go-syntax representation on Mac and Linux.

**Comment by liggitt** [comment]
> I think kubectl edit <kind> with an empty list only appear when no resources found, I was wondering why don't we prompt the error message at the beginning

I agree, I don't think we should open the editor with an empty list and let you create objects by adding them to an empty list.

**Comment by dixudx** [comment]
@shiywang @liggitt Updated. PTAL.

File: pkg/kubectl/cmd/testdata/edit/testcase-edit-from-empty/test.yaml [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+- Editing on empty resource list is forbidden
+expectedExitCode: 1
+steps:
+- type: request
+  expectedMethod: GET
+  expectedPath: /api/v1/namespaces/edit-test/configmaps
+  expectedInput: 0.request
+  resultingStatusCode: 200
+  resultingOutput: 0.response
+- type: edit
```
Comment (liggitt) [inline pkg/kubectl/cmd/testdata/edit/testcase-edit-from-empty/test.yaml]: I wouldn't have expected steps 1 or 2, just the error output

File: pkg/kubectl/cmd/util/editor/editoptions.go (hunk 1 above)
Comment (liggitt) [inline pkg/kubectl/cmd/util/editor/editoptions.go]: please restore this, more details about what was not found are useful

File: pkg/kubectl/cmd/util/editor/editoptions.go [hunk 3]
```diff
@@ -523,7 +522,7 @@ func (o *EditOptions) visitToPatch(
...
```
Comment (liggitt) [inline pkg/kubectl/cmd/util/editor/editoptions.go]: same here, please restore

File: pkg/kubectl/cmd/util/editor/editoptions.go [hunk 4]
```diff
@@ -159,6 +159,9 @@ func (o *EditOptions) Run() error {
 	edit := NewDefaultEditor(o.f.EditorEnvs())
 	// editFn is invoked for each edit session (once with a list for normal edit, once for each individual resource in a edit-on-create invocation)
 	editFn := func(infos []*resource.Info) error {
+		if infos == nil || len(infos) == 0 {
```
Comment (liggitt) [inline pkg/kubectl/cmd/util/editor/editoptions.go]: I'd rather do a length check prior to invoking editFn in `case NormalEditMode:` below

File: pkg/kubectl/cmd/util/editor/editoptions.go [hunk 5]
```diff
@@ -159,6 +159,9 @@ func (o *EditOptions) Run() error {
...
+			return fmt.Errorf("Editing on empty resource list is forbidden")
```
Comment (liggitt) [inline pkg/kubectl/cmd/util/editor/editoptions.go]: I'd use text more like "No resources found." or "Edit cancelled, no objects found."

**Comment by dixudx** [comment]
@shiywang @liggitt Updated. PTAL. Thanks.

File: pkg/kubectl/cmd/util/editor/editoptions.go [hunk 6]
```diff
@@ -159,6 +159,9 @@ func (o *EditOptions) Run() error {
 	edit := NewDefaultEditor(o.f.EditorEnvs())
 	// editFn is invoked for each edit session (once with a list for normal edit, once for each individual resource in a edit-on-create invocation)
 	editFn := func(infos []*resource.Info) error {
+		if infos == nil {
```
Comment (shiywang) [inline pkg/kubectl/cmd/util/editor/editoptions.go]: I don't think this is necessary. infos won't be `nil`

File: pkg/kubectl/cmd/util/editor/editoptions.go [hunk 7]
```diff
@@ -336,6 +339,9 @@ func (o *EditOptions) Run() error {
 		if err != nil {
 			return err
 		}
+		if len(infos) == 0 {
+			return fmt.Errorf("Edit cancelled, no objects found.")
```
Comment (shiywang) [inline pkg/kubectl/cmd/util/editor/editoptions.go]: prefer `return errors.New("edit cancelled, no objects found.")`

File: pkg/kubectl/cmd/util/editor/editoptions.go [hunk 8]
```diff
@@ -500,11 +506,7 @@ func getPrinter(format string) *editPrinterOptions {
 	}
 }
 
-func (o *EditOptions) visitToPatch(
-	originalInfos []*resource.Info,
-	patchVisitor resource.Visitor,
-	results *editResults,
-) error {
+func (o *EditOptions) visitToPatch(originalInfos []*resource.Info, patchVisitor resource.Visitor, results *editResults) error {
```
Comment (shiywang) [inline pkg/kubectl/cmd/util/editor/editoptions.go]: just style change right ? I remember previously it was only one line, and somebody just change to three lines, and now change it back. do we have a signature style in [coding-conventions.md](https://github.com/kubernetes/community/blob/master/contributors/devel/coding-conventions.md) to illustrate which way is better ?

Comment (dixudx) [inline pkg/kubectl/cmd/util/editor/editoptions.go]: @shiywang Just change the style. It looks weird to split into multiple lines.

File: pkg/kubectl/cmd/testdata/edit/testcase-edit-from-empty/test.yaml [hunk 9]
```diff
@@ -0,0 +1,17 @@
...
+  expectedInput: 1.original
```
Comment (liggitt) [inline pkg/kubectl/cmd/testdata/edit/testcase-edit-from-empty/test.yaml]: Does this test pass? I only expected a single step, no edit step. Also, remove the fixtures for the edit step if they are unused

File: pkg/kubectl/cmd/util/editor/editoptions.go (hunk 6 above)
Comment (liggitt) [inline pkg/kubectl/cmd/util/editor/editoptions.go]: Agree, the callers should ensure infos is good

File: pkg/kubectl/cmd/testdata/edit/testcase-edit-from-empty/test.yaml (hunk 9 above)
Comment (dixudx) [inline pkg/kubectl/cmd/testdata/edit/testcase-edit-from-empty/test.yaml]: @liggitt This test passed.

A single step may not work. 

> edit-from-empty, step 0: expected request step, got GET /api/v1/namespaces/edit-test/configmaps

File: pkg/kubectl/cmd/util/editor/editoptions.go (hunk 8 above)
Comment (errordeveloper) [inline pkg/kubectl/cmd/util/editor/editoptions.go]: I don't think we really split args onto separate lines anywhere, looked weird indeed.

**Comment by errordeveloper** [comment]
`/lgtm`

**Review by errordeveloper — APPROVED** [review]

**Comment by dixudx** [comment]
@fabianofranz @janetkuo @liggitt Needs your approval. Thanks.

File: pkg/kubectl/cmd/testdata/edit/testcase-edit-from-empty/test.yaml (hunk 9 above)
Comment (liggitt) [inline pkg/kubectl/cmd/testdata/edit/testcase-edit-from-empty/test.yaml]: a step with `type: edit` means that the editor is still being invoked with an empty list, which is not what we want.

Comment (liggitt) [inline pkg/kubectl/cmd/testdata/edit/testcase-edit-from-empty/test.yaml]: ah, the test isn't checking if there were extra steps in the testcase, so this was being ignored. remove the `edit` step and `testcase-edit-from-empty/1.original`

Comment (dixudx) [inline pkg/kubectl/cmd/testdata/edit/testcase-edit-from-empty/test.yaml]: @liggitt Updated. PTAL. Thanks.

**Comment by liggitt** [comment]
squash commits, then LGTM

**Comment by dixudx** [comment]
@liggitt Done. PTAL.

File: pkg/kubectl/cmd/testdata/edit/testcase-edit-from-empty/0.response [hunk 10]
```diff
@@ -0,0 +1,9 @@
+{
+    "apiVersion": "v1",
+    "items": [],
+    "kind": "List",
+    "metadata": {
+        "resourceVersion": "",
+        "selfLink": ""
+    }
+}
```
Comment (liggitt) [inline pkg/kubectl/cmd/testdata/edit/testcase-edit-from-empty/0.response]: just noticed this stub doesn't actually match what the API server returns for this API call. It should be an actual capture of an API response:
```
{
    "kind": "ConfigMapList",
    "apiVersion": "v1",
    "metadata": {
        "selfLink": "/api/v1/namespaces/default/configmaps",
        "resourceVersion": "252"
    },
    "items": []
}
```

Comment (dixudx) [inline pkg/kubectl/cmd/testdata/edit/testcase-edit-from-empty/0.response]: @liggitt Updated. PTAL.
