### PR TITLE
e2e network test for multiple protocol services on same port

### LINKED ISSUE #116314: e2e needed: Service port on other protocol should fail
see https://github.com/cilium/cilium/issues/9207

* A pod listens on port N, on both TCP and UDP.
* A service forwards to port N, *only* TCP.
* Accessing the service via UDP should fail.

### PR DESCRIPTION
**Pull request by aojea**
The test creates a Service exposing two protocols on the same port and a backend that replies on both protocols.

1. Test that Service with works for both protocol
2. Update Service to expose only the TCP port
3. Verify that TCP works and UDP does not work
4. Update Service to expose only the UDP port
5. Verify that TCP does not work and UDP does work

```release-note
NONE
```
Fixes: #116314

/sig network
/assign @thockin

I've verified it fails "correctly" against cilium , and solves the doubts about what is exacttly broken.

I was under the assumption that DNS services will not work, but is the contrary, the thing is that any port on Services will be forwarded independently of the protocol (that is kind of a huge relieve, isn't it? :) )

```
 [FAILED] [14.761 seconds]
[sig-network] Services [It] should serve endpoints on same port and different protocols
test/e2e/network/service.go:3622

  [FAILED] Unexpected connection to Service UDP port: <nil>
  In [It] at: test/e2e/network/service.go:3698 @ 03/07/23 16:15:37.749
```

### CODE REVIEW

**Review by thockin — COMMENTED** [review]
The extension to this is to have 2 pods, with *named* ports.  1 pod with "tcp-port" and 1 pod with "udp-port", and the service that has both defined.  It should route TCP traffic to the first pod and UDP to the second pod.

Harder to test (proving that it doesn't mess up is a numbers game) but I think this is a subtle distinction that is supposed to work.

/lgtm
/approve

**Comment by aojea** [comment]
somthing is wrong with the test, 👀

File: test/e2e/network/service.go [hunk 1]
```diff
@@ -3618,6 +3618,110 @@ var _ = common.SIGDescribe("Services", func() {
...
+			framework.Failf("failed to update Service %q: %w", serviceName, err)
+		}
+		err = testEndpointReachability(ctx, service.Spec.ClusterIP, 80, v1.ProtocolTCP, execPod, 30*time.Second)
+		if err == nil {
+			framework.Failf("Unexpected connection to Service TCP port: %v", err)
+		}
+		err = testEndpointReachability(ctx, service.Spec.ClusterIP, 80, v1.ProtocolUDP, execPod, 30*time.Second)
+		if err == nil {
+			framework.Failf("Unexpected connection to Service UDP port: %v", err)
+		}
```
Comment (aojea) [inline test/e2e/network/service.go:3718]: lol, copy paste error

**Comment by aojea** [comment]
```
FAIL: vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory TestRateLimitHealthcheck/etcd_down (3.50s)
    factory_test.go:308: healthcheck() mismatch want etcd down got etcd client connection not yet established
    factory_test.go:319: healthcheck() mismatch want etcd down got etcd client connection not yet established
    factory_test.go:319: healthcheck() mismatch want etcd down got etcd client connection not yet established
    --- FAIL: TestRateLimitHealthcheck/etcd_down (3.50s)
```

this is starting to show up much lately 👀

**Comment by aojea** [comment]
@thockin this time is the good one, latest failure were because of a linter problem

**Comment by aojea** [comment]
/assign @code-elinka 

this is a good one for review
