### PR TITLE
e2e: node: always declare testcase CPU requirements

### LINKED ISSUE #131769: [sig-node][CPU Manager][Failing test] When running non-guaranteed pods tests should let the container access all the online CPUs without a reserved CPUs set
### Failure cluster [6f1ebcdff366821299a0](https://go.k8s.io/triage#6f1ebcdff366821299a0)

https://storage.googleapis.com/k8s-triage/index.html?text=%20k8s.io%2Fkubernetes%2Ftest%2Fe2e_node%2Fcpumanager_test.go%3A193

##### Error text:
```
[FAILED] open /sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podd0214f4c_870d_45ee_b40d_80c9db363992.slice/cri-containerd-c7313a54b4850605025748a1cdafb98d9a0e2b4e3daa32780c3925d913e94b68.scope/cpuset.cpus.effective: no such file or directory
In [It] at: k8s.io/kubernetes/test/e2e_node/cpumanager_test.go:193 @ 05/10/25 04:34:45.956

```
#### Recent failures:
[5/14/2025, 11:16:36 AM ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks/1922581487371161600)
[5/14/2025, 10:21:35 AM ci-cgroupv1-containerd-node-e2e-serial-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cgroupv1-containerd-node-e2e-serial-ec2-eks/1922567646105047040)
[5/14/2025, 5:17:08 AM ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks/1922490889440071680)
[5/14/2025, 4:21:32 AM ci-cgroupv1-containerd-node-e2e-serial-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cgroupv1-containerd-node-e2e-serial-ec2-eks/1922477048048128000)
[5/13/2025, 11:16:34 PM ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks/1922400291655782400)

Image

/kind failing-test

/sig node

### LINKED ISSUE #131793: Failure cluster [fa6d20fe...] [sig-node] CPU Manager [Serial] [Feature:CPUManager] when running non-guaranteed pods tests should let the container access all the online non-exclusively-allocated CPUs when using a reserved CPUs set
Image

##### Error text:
```
[FAILED] Told to stop trying after 2.004s.
The phase of Pod non-gu-pod is Failed which is unexpected.
In [It] at: k8s.io/kubernetes/test/e2e_node/cpumanager_test.go:248 @ 05/10/25 03:11:11.376

```
#### Recent failures:
[5/15/2025, 2:43:42 AM ci-cgroupv2-containerd-node-e2e-serial-ec2](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cgroupv2-containerd-node-e2e-serial-ec2/1922905411820720128)
[5/15/2025, 2:41:41 AM ci-cgroupv2-containerd-node-arm64-e2e-serial-ec2](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cgroupv2-containerd-node-arm64-e2e-serial-ec2/1922904908642652160)
[5/15/2025, 1:33:16 AM ci-cgroupv2-containerd-node-arm64-al2023-e2e-serial-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cgroupv2-containerd-node-arm64-al2023-e2e-serial-ec2-eks/1922887506710237184)
[5/15/2025, 1:24:12 AM ci-kubernetes-node-arm64-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-arm64-ubuntu-serial/1922885493318488064)
[5/15/2025, 1:15:15 AM ci-kubernetes-node-swap-ubuntu-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-ubuntu-serial/1922883228318830592)

/kind failing-test

/sig node

### PR DESCRIPTION
**Pull request by ffromani**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:
Fixes cpumanager tests to always declare the CPU requirements of the test case, skipping if the machine can't provide

#### Which issue(s) this PR fixes:
Fixes #131793
Fixes #131769

#### Special notes for your reviewer:
https://github.com/kubernetes/kubernetes/pull/130274 rewrote the cpumanager tests assuming there are always at least 4 online CPUs, adding checks for the tests which require more.

We still have, and likely we will have for the time being, lanes which run on machines with 2 online CPUs.

Thus, every test which either reserve cpus (--reserved-cpus) or run pods with exclusive CPU allocation must declare the requisites and skip if the machine don't provide them.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by ffromani** [comment]
I have a followup PR to streamline the testcases preconditions check: I want to add more automation about computing the CPU requirments vs duplicating and having to set the information manually. But I think is best to first stop the bleeding with this PR and then improve later.

**Comment by ffromani** [comment]
unrelated failures:
```
E2eNode Suite: [It] [sig-node] Pod Level Resources [Serial] [Feature:PodLevelResources] Burstable QoS pod, no container resources expand_more 	14s
E2eNode Suite: [It] [sig-node] Pod Level Resources [Serial] [Feature:PodLevelResources] Burstable QoS pod, 1 container with resources expand_more 	12s
E2eNode Suite: [It] [sig-node] Pod Level Resources [Serial] [Feature:PodLevelResources] Guaranteed QoS pod, no container resources expand_more 	12s
E2eNode Suite: [It] [sig-node] Pod Level Resources [Serial] [Feature:PodLevelResources] Burstable QoS pod with container resources expand_more 	12s
E2eNode Suite: [It] [sig-node] Pod Level Resources [Serial] [Feature:PodLevelResources] Guaranteed QoS pod, 1 container with resources expand_more 	12s
E2eNode Suite: [It] [sig-node] Pod Level Resources [Serial] [Feature:PodLevelResources] Burstable QoS pod, no container resources expand_more 	10s
E2eNode Suite: [It] [sig-node] Pod Level Resources [Serial] [Feature:PodLevelResources] Burstable QoS pod with container resources expand_more 	10s
E2eNode Suite: [It] [sig-node] HugePages [Serial] [Feature:HugePages] when start the pod with the resources requests that contain multiple hugepages resources should set correct hugetlb mount and limit under the container cgroup expand_more 	1m31s
E2eNode Suite: [It] [sig-node] Pod Level Resources [Serial] [Feature:PodLevelResources] Guaranteed QoS pod, no container resources expand_more 	12s
E2eNode Suite: [It] [sig-node] Pod Level Resources [Serial] [Feature:PodLevelResources] Burstable QoS pod, 1 container with resources expand_more 	12s
E2eNode Suite: [It] [sig-node] Pod Level Resources [Serial] [Feature:PodLevelResources] Guaranteed QoS pod, 1 container with resources expand_more
```

it seems the PR is doing what is expected, cleaning up and finalizing

**Comment by ffromani** [comment]
/triage accepted
/priority important-soon

self-triaging issues is no longer frowned upon in sig-node, it seems.

File: test/e2e_node/cpumanager_test.go [hunk 1]
```diff
@@ -221,6 +230,12 @@ var _ = SIGDescribe("CPU Manager", ginkgo.Ordered, framework.WithSerial(), featu
 			cpuCount := 1
 			reservedCPUs := cpuset.New(0)
 
+			cpuReq := int64(cpuCount + reservedCPUs.Size() + 1)   // note the extra for the non-gu pod
```
Comment (esotsal) [inline test/e2e_node/cpumanager_test.go:233]: Suggestion: Create a utility function for this block, to avoid code duplication?

Comment (ffromani) [reply test/e2e_node/cpumanager_test.go:233]: thought about it. It seems the case of a code which seems repetitive but there are a bunch of subtle case that make generalization harder. I'll try to improve in my upcoming cleanup PR.

Comment (ffromani) [reply test/e2e_node/cpumanager_test.go:233]: example: some tests want to set reserved cpus; some not. Some test can reuse the node object, some tests needs to refresh it.

**Comment by ffromani** [comment]
image

**Comment by ffromani** [comment]
none of the failures is related to the new cpumanager tests

File: test/e2e_node/cpumanager_test.go [hunk 2]
```diff
@@ -166,6 +167,14 @@ var _ = SIGDescribe("CPU Manager", ginkgo.Ordered, framework.WithSerial(), featu
 		podMap = make(map[string]*v1.Pod)
 	})
 
+	ginkgo.JustBeforeEach(func(ctx context.Context) {
+		// the framework is initialized using an injected BeforeEach node, so the
+		// earliest we can do is to initialize the other objects here
+		localNode = getLocalNode(ctx, f)           // bootstrap
+		cpuDetails = cpuDetailsFromNode(localNode) // bootstrap
```
Comment (swatisehgal) [inline test/e2e_node/cpumanager_test.go:174]: Let's consolidate this just like we have done in other places:
```suggestion
		cpuDetails = cpuDetailsFromNode(getLocalNode(ctx, f)) // bootstrap
```

File: test/e2e_node/cpumanager_test.go [hunk 3]
```diff
@@ -263,20 +278,21 @@ var _ = SIGDescribe("CPU Manager", ginkgo.Ordered, framework.WithSerial(), featu
...
 		})
 
 		ginkgo.It("should allocate exclusively a CPU to a 1-container pod", func(ctx context.Context) {
 			cpuCount := 1
 
+			cpuReq := int64(cpuCount + reservedCPUs.Size())
+			cpuDetails = cpuDetailsFromNode(getLocalNode(ctx, f)) // avoid potentially costly updateKubeletConfigIfNeeded
+			if cpuDetails.Allocatable < cpuReq {
+				e2eskipper.Skipf("Skipping CPU Manager tests since the CPU allocatable %d < CPU request %d (online %d)", cpuDetails.Allocatable, cpuReq, onlineCPUs.Size())
+			}
```
Comment (swatisehgal) [inline test/e2e_node/cpumanager_test.go:294]: This seems to appear repeatedly, can we try to abstract into a helper like below?:

func skipIfInsufficientCPU(ctx context.Context, f *framework.Framework, cpuReq int64, onlineCPUs cpuset.CPUSet) bool

Comment (ffromani) [reply test/e2e_node/cpumanager_test.go:294]: ok since there is frequent request from reviewers, I'll extract a helper function

File: test/e2e_node/cpumanager_test.go [hunk 4]
```diff
@@ -221,6 +230,12 @@ var _ = SIGDescribe("CPU Manager", ginkgo.Ordered, framework.WithSerial(), featu
 			cpuCount := 1
 			reservedCPUs := cpuset.New(0)
 
+			cpuReq := int64(cpuCount + reservedCPUs.Size() + 1)   // note the extra for the non-gu pod
+			cpuDetails = cpuDetailsFromNode(getLocalNode(ctx, f)) // avoid potentially costly updateKubeletConfigIfNeeded
+			if cpuDetails.Allocatable < cpuReq {
+				e2eskipper.Skipf("Skipping CPU Manager tests since the CPU allocatable %d < CPU request %d (online %d)", cpuDetails.Allocatable, cpuReq, onlineCPUs.Size())
+			}
+
```
Comment (swatisehgal) [inline test/e2e_node/cpumanager_test.go:238]: WDYT about adding a Ginkgo By(...) description before each skip so it’s easier to trace the reason in test logs?

File: test/e2e_node/cpumanager_test.go (hunk 2 above)
Comment (ffromani) [reply test/e2e_node/cpumanager_test.go:174]: we will still to update `localNode` in some places. I'll still see if I can refactor this further

**Review by hashim21223445 — APPROVED** [review]

File: test/e2e_node/cpumanager_test.go (hunk 4 above)
Comment (ffromani) [reply test/e2e_node/cpumanager_test.go]: done!

**Comment by haircommander** [comment]
serial test failures seem legit @ffromani

**Comment by ffromani** [comment]
So I posted https://github.com/kubernetes/kubernetes/pull/131895 and it seems we see the same failures here. They seem indeed legit but unrelated to this change. I'll file an issue.

**Comment by ffromani** [comment]
> So I posted #131895 and it seems we see the same failures here. They seem indeed legit but unrelated to this change. I'll file an issue.

image

**Comment by ffromani** [comment]
@haircommander filed https://github.com/kubernetes/kubernetes/issues/131920

File: test/e2e_node/cpumanager_test.go [hunk 5]
```diff
@@ -163,16 +166,36 @@ var _ = SIGDescribe("CPU Manager", ginkgo.Ordered, framework.WithSerial(), featu
...
+			ginkgo.GinkgoHelper()
+			cpuReq := int64(val + reservedCPUs.Size()) // reserved CPUs are not usable, need to account them
+			// the framework is initialized using an injected BeforeEach node, so the
+			// earliest we can do is to initialize the other objects here
+			nodeCPUDetails := cpuDetailsFromNode(node)
+
+			msg := fmt.Sprintf("%v full CPUs (detected=%v requested=%v reserved=%v online=%v smt=%v)", cpuReq, nodeCPUDetails.Allocatable, val, reservedCPUs.Size(), onlineCPUs.Size(), smtLevel)
+			ginkgo.By("Checking if allocatable: " + msg)
+			if nodeCPUDetails.Allocatable < cpuReq {
+				e2eskipper.Skipf("Skipping CPU Manager test: not allocatable %s", msg)
```
Comment (bart0sh) [inline test/e2e_node/cpumanager_test.go:187]: Skipping tests can potentially hide issues. Would it make sense failing the tests instead and ensure that CI machines running CPU tests have enough CPUs? In this case if CI configuration is changed again, the tests would start failing immediately, which is a clear signal.

Comment (ffromani) [reply test/e2e_node/cpumanager_test.go:187]: True. Problem is: it's a very delicate balance and I can't find good answers.
Making the test fail will create a storm of red tests which we can't fix but removing the relevant groups from the test lanes. Which brings the question: why did we add these tests in these lanes in the first place?
1. if we want the little signal we can get, then doing as many tests as we can and skipping others seems the closest to the intent
2. if we want the full suite running, then we can't. So either bump the machine specs or remove the relevant tests from the lanes.

Comment (bart0sh) [reply test/e2e_node/cpumanager_test.go:187]: > Making the test fail will create a storm of red tests which we can't fix but removing the relevant groups from the test lanes.

I thought we can fix it by reverting test-infra changes that caused it.

Comment (ffromani) [reply test/e2e_node/cpumanager_test.go:187]: not sure we ever had test-infra changes which downsized the CI machines. 
But in general: can we just go and require bigger machines in CI? because this is ultimately the root cause (or, losing signal, remove the tests from CI runs).
