### PR TITLE
fix: run a test for requeueing with PreFilterResult correctly

### LINKED ISSUE #127087: PreFilterResult test in TestCoreResourceEnqueue isn't run
> The test case you added in test/integration/scheduler/queue_test.go will not be executed when enableSchedulingQueueHint is empty. And this test case will always fail regardless of whether we set it to true or false. 
https://github.com/kubernetes/kubernetes/blob/c86a2d6925a61ac181468b74f573518db1d645d2/test/integration/scheduler/queue_test.go#L325-L359
https://github.com/kubernetes/kubernetes/pull/122251#issuecomment-2325937664

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Currently, the test case `Pod rejected by the PreFilter of NodeAffinity plugin and Filter of NodeResourcesFit is requeued based on both plugins` isn't run.
This PR makes it run, and fixes some problem in the test.

#### Which issue(s) this PR fixes:

Fixes #127087

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/integration/scheduler/queue_test.go [hunk 1]
```diff
@@ -379,6 +376,10 @@ func TestCoreResourceEnqueue(t *testing.T) {
 	}
 
 	for _, tt := range tests {
+		if tt.enableSchedulingQueueHint == nil {
```
Comment (nayihz) [inline test/integration/scheduler/queue_test.go:379]: `if len(tt.enableSchedulingQueueHint) == 0` is better?

File: pkg/scheduler/backend/queue/scheduling_queue.go [hunk 2]
```diff
@@ -1139,6 +1144,34 @@ func (p *PriorityQueue) PodsInActiveQ() []*v1.Pod {
 
 var pendingPodsSummary = "activeQ:%v; backoffQ:%v; unschedulablePods:%v"
 
+// GetPod searches for a pod in the activeQ, backoffQ, and unschedulablePods.
+func (p *PriorityQueue) GetPod(name, namespace string) (pInfo *framework.QueuedPodInfo, ok bool) {
```
Comment (nayihz) [inline pkg/scheduler/backend/queue/scheduling_queue.go:1148]: It would be better to add unit test.

File: test/integration/scheduler/queue_test.go [hunk 3]
```diff
@@ -354,29 +351,30 @@ func TestCoreResourceEnqueue(t *testing.T) {
...
+				}
+
+				if pInfo.UnschedulablePlugins.Difference(sets.New(names.NodeAffinity, names.NodeResourcesFit)).Len() != 0 {
+					return fmt.Errorf("unexpected unschedulable plugin(s) is registered in pod1: %v", pInfo.UnschedulablePlugins.UnsortedList())
 				}
 
 				return nil
 			},
-			wantRequeuedPods: sets.New("pod1"),
+			enableSchedulingQueueHint: []bool{false, true},
```
Comment (nayihz) [inline test/integration/scheduler/queue_test.go:377]: no need for this line.
