### PR TITLE
CSI migration e2e: do not skip tests if metricsGrabber.HasRegisteredM…

### LINKED ISSUE #78050: Failing Test: sig-gcp#gke-gci tests are failing on diff due to PV leak
https://testgrid.k8s.io/sig-gcp-master#gci-gke

Example:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/1129457203518902274

```
Error: 13 leaked resources
+NAME                                                           LOCATION    LOCATION_SCOPE  SIZE_GB  TYPE         STATUS
+gke-e2e-78b8f9f547-fbb42-1bd45f0b-8f3f-4613-b4aa-0b8cc301ac90  us-west1-b  zone            2        pd-standard  READY
+gke-e2e-78b8f9f547-fbb42-34f5b859-4426-424f-b86d-a4509857aeb3  us-west1-b  zone            2        pd-standard  READY
+gke-e2e-78b8f9f547-fbb42-4d87c016-ca88-4354-a54f-8abfb2b7fdf3  us-west1-b  zone            2        pd-standard  READY
+gke-e2e-78b8f9f547-fbb42-70ac4e35-bd3a-4109-9f8d-bb8e878cb3bb  us-west1-b  zone            2        pd-standard  READY
+gke-e2e-78b8f9f547-fbb42-8217e3cf-ab8d-49b4-8c2e-072f9ab8a582  us-west1-b  zone            2        pd-standard  READY
+gke-e2e-78b8f9f547-fbb42-85b31105-8b73-4179-a8fb-51948d5c0036  us-west1-b  zone            2        pd-standard  READY
+gke-e2e-78b8f9f547-fbb42-9a67e721-c600-4ea8-a144-6cd185213129  us-west1-b  zone            2        pd-standard  READY
+gke-e2e-78b8f9f547-fbb42-bbcdb98b-37c9-4ec0-8ded-d50ff221c76e  us-west1-b  zone            2        pd-standard  READY
+gke-e2e-78b8f9f547-fbb42-d7a65484-e0bc-49e5-b6d9-5cf8fecafb88  us-west1-b  zone            2        pd-standard  READY
+gke-e2e-78b8f9f547-fbb42-e8e227cc-6f7d-4259-a50a-e726a94a9669  us-west1-b  zone            2        pd-standard  READY
+gke-e2e-78b8f9f547-fbb42-e9c18f68-d1b1-463d-8c03-ee9eefaef72b  us-west1-b  zone            2        pd-standard  READY
+gke-e2e-78b8f9f547-fbb42-ff40bfaf-af40-49d7-9901-f659442bdc41  us-west1-b  zone            2        pd-standard  READY
```

@msau42 @saad-ali

### PR DESCRIPTION
**Pull request by verult**
…aster() is true

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**: Removes PD leaks in PD test suites

**Which issue(s) this PR fixes**: Fixes https://github.com/kubernetes/kubernetes/issues/78050

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/assign @davidz627

### CODE REVIEW

File: test/e2e/storage/testsuites/volumes.go [hunk 1]
```diff
@@ -118,12 +118,11 @@ func (t *volumesTestSuite) defineTests(driver TestDriver, pattern testpatterns.T
 
 		// Now do the more expensive test initialization.
 		l.config, l.testCleanup = driver.PrepareTest(f)
+		l.intreeOps, l.migratedOps = getMigrationVolumeOpCounts(f.ClientSet, dInfo.InTreePluginName)
```
Comment (davidz627) [inline test/e2e/storage/testsuites/volumes.go]: why are we moving the metrics getting only for the `volumes.go` test suites? (this is being done in each of the test suits)

Comment (verult) [reply test/e2e/storage/testsuites/volumes.go]: Every other call is in the right place for some reason, i.e. after PrepareTest and before resource creation

The other reference to `getMigrationVolumeOpCounts` is inside a function that's always called in cleanup, after resource deletion
