### PR TITLE
e2e WaitForServiceEndpointsNum take into account the address family

### LINKED ISSUE #119927: Dual Stack tests are broken
### Which jobs are failing?

All the dual stack jobs

image

https://testgrid.k8s.io/sig-testing-kind#sig-network-kind,%20ipvs,%20dual,%20master

### Which tests are failing?

All dual stacks tests

### Since when has it been failing?

Since I modified this helper function to fix a flake https://github.com/kubernetes/kubernetes/pull/119798

### Testgrid link

https://testgrid.k8s.io/sig-testing-kind#sig-network-kind,%20ipvs,%20dual,%20master

### Reason for failure (if possible)

The function must consider only one IP family to verify the number of endpoints

### Anything else we need to know?

/assign

### Relevant SIG(s)

/sig network
/sig testing

### PR DESCRIPTION
**Pull request by aojea**
Since EndpointSlices can carry dual stack families, but Endpoints can only have one single family, the function must take this into account and only compare the addresses of the same family, otherwise it will always fail for Services with dual stack endoints, because the endpoint slices will have always twice addresses than the Endpoints.

/kind bug
/kind failing-test
/kind regression

Fixes #119927

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
> Kubernetes e2e suite: [It] [sig-storage] HostPath should give a volume the correct mode [LinuxOnly] [NodeConformance] expand_less	

failures is unrelated, this is good, the dual stack test pass now

/assign @liggitt @dims

**Comment by dims** [comment]
i like it. 

/approve
/lgtm

File: test/e2e/framework/util.go [hunk 1]
```diff
@@ -436,6 +436,13 @@ func WaitForServiceEndpointsNum(ctx context.Context, c clientset.Interface, name
 			return false, nil
 		}
 
+		// Endpoints are single family but EndpointSlices can have dual stack addresses,
+		// so we verify the number of addresses that matches the same family on both.
+		addressType := discoveryv1.AddressTypeIPv4
+		if expectNum > 0 && netutils.IsIPv6String(endpoint.Subsets[0].Addresses[0].IP) {
```
Comment (liggitt) [inline test/e2e/framework/util.go:442]: can Subsets or Addresses be zero-length and panic this?

Comment (aojea) [reply test/e2e/framework/util.go:442]: I can make this more resilient, is not straightforward to notice it

Comment (aojea) [reply test/e2e/framework/util.go]: done, wait for CI jobs to verify

**Comment by aojea** [comment]
> Kubernetes e2e suite: [It] [sig-network] Conntrack should be able to preserve UDP traffic when server pod cycles for a ClusterIP service expand_less	
/test pull-kubernetes-e2e-kind


> k8s.io/kubernetes/pkg/kubelet/cm: dra expand_less	3m0s
> {Failed;Failed;  === RUN   TestUnprepareResouces/should_timeout
> I0814 17:21:29.495010   43607 plugin.go:47] "Register new DRA plugin" name="test-cdi-device" endpoint="/tmp/dra2994399569/server.sock"
>     manager_test.go:1005: 
>         	Error Trace:	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/dra/manager_test.go:1005
>         	Error:      	An error is expected but got nil.
>         	Test:       	TestUnprepareResouces/should_timeout
> I0814 17:22:14.546518   43607 plugin.go:158] "DeRegister DRA plugin" name="test-cdi-device"
>     --- FAIL: TestUnprepareResouces/should_timeout (45.05s)
> ;=== RUN   TestUnprepareResouces
> --- FAIL: TestUnprepareResouces (45.07s)

/test pull-kubernetes-e2e-kind

**Comment by aojea** [comment]
```


k8s.io/kubernetes/pkg/kubelet/cm: dra expand_less | 3m0s
-- | --
{Failed;Failed;  === RUN   TestUnprepareResouces/should_timeout I0814 17:21:29.495010   43607 plugin.go:47] "Register new DRA plugin" name="test-cdi-device" endpoint="/tmp/dra2994399569/server.sock"     manager_test.go:1005:          	Error Trace:	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/dra/manager_test.go:1005         	Error:      	An error is expected but got nil.         	Test:       	TestUnprepareResouces/should_timeout I0814 17:22:14.546518   43607 plugin.go:158] "DeRegister DRA plugin" name="test-cdi-device"     --- FAIL: TestUnprepareResouces/should_timeout (45.05s) ;=== RUN   TestUnprepareResouces --- FAIL: TestUnprepareResouces (45.07s) ;}


```

do we have an issue to track this flake?

/retest

**Comment by aojea** [comment]
I can't see it failing in https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=TestUnprepareResouces 🤔 

@pacoxu @pohly  did you notice something with this unit test `TestUnprepareResouces` under `k8s.io/kubernetes/pkg/kubelet/cm: dra` ?

It failed twice in this PR that is completely unrelated

**Comment by pohly** [comment]
> did you notice something with this unit test TestUnprepareResouces under k8s.io/kubernetes/pkg/kubelet/cm: dra ?

Yes, and a PR is pending: https://github.com/kubernetes/kubernetes/pull/119709
