### PR TITLE
Address TestEtcdStoragePath flakes

### LINKED ISSUE #49423: TestEtcdStoragePath test failures
Seeing a variety of failures

Address already in use failures
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49117/pull-kubernetes-unit/42260/

Stack traces:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49168/pull-kubernetes-unit/42305/
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49168/pull-kubernetes-unit/42269/

Creation errors:
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/49219/pull-kubernetes-unit/42214/

### PR DESCRIPTION
**Pull request by enj**
- Wait for the master to be healthy
- Wait longer for the master to start
- Fail gracefully if starting the master panics

Signed-off-by: Monis Khan <mkhan@redhat.com>

```release-note
NONE
```

Fixes #49423

@kubernetes/sig-api-machinery-pr-reviews

### CODE REVIEW

File: test/integration/etcd/etcd_storage_path_test.go [hunk 1]
```diff
@@ -695,26 +701,35 @@ func startRealMasterOrDie(t *testing.T, certDir string) (*allClient, clientv3.KV
 				t.Log(err)
 			}
 
-			time.Sleep(100 * time.Millisecond)
+			time.Sleep(time.Second)
 		}
 	}()
 
-	if err := wait.PollImmediate(100*time.Millisecond, 10*time.Second, func() (done bool, err error) {
+	if err := wait.PollImmediate(time.Second, time.Minute, func() (done bool, err error) {
```
Comment (sttts) [inline test/integration/etcd/etcd_storage_path_test.go]: this is insane startup logic for a single test 😱  Compare cmd/kube-apiserver/app/testing/server_test.go.

**Comment by mml** [comment]
/unassign @erictune 
/assign @jpbetz 
cc @mml

File: test/integration/etcd/etcd_storage_path_test.go [hunk 2]
```diff
@@ -695,26 +701,35 @@ func startRealMasterOrDie(t *testing.T, certDir string) (*allClient, clientv3.KV
 				t.Log(err)
 			}
 
-			time.Sleep(100 * time.Millisecond)
+			time.Sleep(time.Second)
 		}
 	}()
 
-	if err := wait.PollImmediate(100*time.Millisecond, 10*time.Second, func() (done bool, err error) {
```
Comment (jpbetz) [inline test/integration/etcd/etcd_storage_path_test.go]: This both increases the total time to wait and decreases the rate of polling.

Why decrease the rate of polling? Won't this just mean there is more potential for this to take longer to run than it needs to?

File: test/integration/etcd/etcd_storage_path_test.go [hunk 3]
```diff
@@ -695,26 +701,35 @@ func startRealMasterOrDie(t *testing.T, certDir string) (*allClient, clientv3.KV
...
 		if obj == nil {
 			return false, nil
 		}
 		kubeClientConfig := kubeClientConfigValue.Load().(*restclient.Config)
-		kubeClient, err := kclient.NewForConfig(kubeClientConfig)
+		// make a copy so we can mutate it to set GroupVersion and NegotiatedSerializer
+		cfg := *kubeClientConfig
+		cfg.ContentConfig.GroupVersion = &schema.GroupVersion{}
+		cfg.ContentConfig.NegotiatedSerializer = kapi.Codecs
+		privilegedClient, err := restclient.RESTClientFor(&cfg)
```
Comment (jpbetz) [inline test/integration/etcd/etcd_storage_path_test.go]: Split the health check call logic into a separate function? It doesn't need to be inline here.

**Review by jpbetz — CHANGES_REQUESTED** [review]

File: test/integration/etcd/etcd_storage_path_test.go (hunk 1 above)
Comment (enj) [reply test/integration/etcd/etcd_storage_path_test.go]: It is a necessary evil to get into the guts of the master which are not exposed by the default testing bits (and its not like anyone else cares about direct etcd access).  This is completely based off of `TestAggregatedAPIServer`.

File: test/integration/etcd/etcd_storage_path_test.go (hunk 3 above)
Comment (enj) [reply test/integration/etcd/etcd_storage_path_test.go]: This cannot be split up because it uses `atomic.Value` which is not safe to copy.

File: test/integration/etcd/etcd_storage_path_test.go (hunk 2 above)
Comment (enj) [reply test/integration/etcd/etcd_storage_path_test.go]: > This both increases the total time to wait and decreases the rate of polling.

I attempt to start a very real-ish master, which can take longer to report healthy.  I felt like it was counterproductive to keep asking the master if it was healthy.  The total time only matters in cases where the master fails to start (meaning something else is broken).

> Why decrease the rate of polling? Won't this just mean there is more potential for this to take longer to run than it needs to?

Taking ~1 second longer isn't really an issue IMO (especially with parallel integration tests).

File: test/integration/etcd/etcd_storage_path_test.go (hunk 1 above)
Comment (sttts) [reply test/integration/etcd/etcd_storage_path_test.go]: not a blocker for this PR, just some observation.
