### PR TITLE
scheduler/framework/plugins/volumebinding: fix inaccurate log for when a volume is bound to a claim

### LINKED ISSUE #116012: Inaccurate log for when a volume is bound to a claim
### What happened?

This line reads as if the bound has already happened:

https://github.com/kubernetes/kubernetes/blob/3702411ef9d99e2fe186381474692fdb970a3b4c/pkg/scheduler/framework/plugins/volumebinding/binder.go#L578

But, if I read correctly, the bound happens immediately after:

https://github.com/kubernetes/kubernetes/blob/3702411ef9d99e2fe186381474692fdb970a3b4c/pkg/scheduler/framework/plugins/volumebinding/binder.go#L579

And there is even a wait for confirmation after:

https://github.com/kubernetes/kubernetes/blob/3702411ef9d99e2fe186381474692fdb970a3b4c/pkg/scheduler/framework/plugins/volumebinding/binder.go#L526-L529

### What did you expect to happen?

The log line to better describe the actual state and another log line at V(2) to confirm that the operation ended.

### How can we reproduce it (as minimally and precisely as possible)?

-

### Anything else we need to know?

_No response_

### Kubernetes version

all supported versions

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by tmilox**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

If applied, this commit will improve the accuracy of log when a volume is bound to a claim

#### Which issue(s) this PR fixes:

Fixes #116012

#### Does this PR introduce a user-facing change?

```release-note
Fix log line in scheduler that inaccurately implies that volume binding has finalized
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by TommyStarK** [comment]
Hello @alculquicondor, @msau42,

If I misunderstood your issue and the changes your are suggesting, please tell me and I will update this PR accordingly.

Best regards,

**Comment by alculquicondor** [comment]
I was first waiting for feedback from SIG Storage experts.

In general, it's better to wait for deliberation before opening a PR. This might be fine though.

File: pkg/scheduler/framework/plugins/volumebinding/binder.go [hunk 1]
```diff
@@ -575,14 +575,14 @@ func (b *volumeBinder) bindAPIUpdate(ctx context.Context, pod *v1.Pod, bindings
...
-		klog.V(2).InfoS("Claim bound to volume", "PVC", klog.KObj(binding.pvc), "PV", klog.KObj(binding.pv))
+		klog.V(2).InfoS("Updating PersistentVolume: binding to claim", "PVC", klog.KObj(binding.pvc), "PV", klog.KObj(binding.pv))
 		newPV, err := b.kubeClient.CoreV1().PersistentVolumes().Update(ctx, binding.pv, metav1.UpdateOptions{})
 		if err != nil {
 			klog.V(4).InfoS("Updating PersistentVolume: binding to claim failed", "PV", klog.KObj(binding.pv), "PVC", klog.KObj(binding.pvc), "err", err)
 			return err
 		}
 
-		klog.V(4).InfoS("Updating PersistentVolume: bound to claim", "PV", klog.KObj(binding.pv), "PVC", klog.KObj(binding.pvc))
+		klog.V(2).InfoS("Updating PersistentVolume: bound to claim", "PV", klog.KObj(binding.pv), "PVC", klog.KObj(binding.pvc))
```
Comment (msau42) [inline pkg/scheduler/framework/plugins/volumebinding/binder.go:585]: Do you want to bump the log level for the provisioning case at L594?

File: pkg/scheduler/framework/plugins/volumebinding/binder.go [hunk 2]
```diff
@@ -575,14 +575,14 @@ func (b *volumeBinder) bindAPIUpdate(ctx context.Context, pod *v1.Pod, bindings
 	for _, binding = range bindings {
 		klog.V(5).InfoS("bindAPIUpdate: binding PV to PVC", "pod", klog.KObj(pod), "PV", klog.KObj(binding.pv), "PVC", klog.KObj(binding.pvc))
 		// TODO: does it hurt if we make an api call and nothing needs to be updated?
-		klog.V(2).InfoS("Claim bound to volume", "PVC", klog.KObj(binding.pvc), "PV", klog.KObj(binding.pv))
+		klog.V(2).InfoS("Updating PersistentVolume: binding to claim", "PVC", klog.KObj(binding.pvc), "PV", klog.KObj(binding.pv))
```
Comment (msau42) [inline pkg/scheduler/framework/plugins/volumebinding/binder.go:578]: I think the only difference between this and the above log message is the pod. I think it's fine to combine into one.

**Comment by TommyStarK** [comment]
I do apologize. Always trying to find something I can contribute to, it's hard for newcomers. Your issue was detailed enough and it wasn't assigned. It won't happen again. I'll wait for deliberation and remain at disposal for any change.

File: pkg/scheduler/framework/plugins/volumebinding/binder.go (hunk 2 above)
Comment (TommyStarK) [reply pkg/scheduler/framework/plugins/volumebinding/binder.go]: I combined into one and tried to keep consistency.

File: pkg/scheduler/framework/plugins/volumebinding/binder.go (hunk 1 above)
Comment (TommyStarK) [reply pkg/scheduler/framework/plugins/volumebinding/binder.go]: I was following Aldo's suggestion, sorry if I misunderstood. Please do not hesitate to suggest a more appropriate log level/message

File: pkg/scheduler/framework/plugins/volumebinding/binder.go [hunk 3]
```diff
@@ -573,16 +573,15 @@ func (b *volumeBinder) bindAPIUpdate(ctx context.Context, pod *v1.Pod, bindings
...
 	// There is no API rollback if the actual binding fails
 	for _, binding = range bindings {
-		klog.V(5).InfoS("bindAPIUpdate: binding PV to PVC", "pod", klog.KObj(pod), "PV", klog.KObj(binding.pv), "PVC", klog.KObj(binding.pvc))
 		// TODO: does it hurt if we make an api call and nothing needs to be updated?
-		klog.V(2).InfoS("Claim bound to volume", "PVC", klog.KObj(binding.pvc), "PV", klog.KObj(binding.pv))
+		klog.V(2).InfoS("Updating PersistentVolume: binding to claim", "pod", klog.KObj(pod), "PV", klog.KObj(binding.pv), "PVC", klog.KObj(binding.pvc))
 		newPV, err := b.kubeClient.CoreV1().PersistentVolumes().Update(ctx, binding.pv, metav1.UpdateOptions{})
 		if err != nil {
-			klog.V(4).InfoS("Updating PersistentVolume: binding to claim failed", "PV", klog.KObj(binding.pv), "PVC", klog.KObj(binding.pvc), "err", err)
+			klog.V(4).InfoS("Updating PersistentVolume: binding to claim failed", "pod", klog.KObj(pod), "PV", klog.KObj(binding.pv), "PVC", klog.KObj(binding.pvc), "err", err)
```
Comment (alculquicondor) [inline pkg/scheduler/framework/plugins/volumebinding/binder.go:580]: Is this just a V(4) because the error is logged higher in the call stack as well?

File: pkg/scheduler/framework/plugins/volumebinding/binder.go [hunk 4]
```diff
@@ -573,16 +573,15 @@ func (b *volumeBinder) bindAPIUpdate(ctx context.Context, pod *v1.Pod, bindings
...
 			return err
 		}
 
-		klog.V(4).InfoS("Updating PersistentVolume: bound to claim", "PV", klog.KObj(binding.pv), "PVC", klog.KObj(binding.pvc))
+		klog.V(2).InfoS("Updating PersistentVolume: bound to claim", "pod", klog.KObj(pod), "PV", klog.KObj(binding.pv), "PVC", klog.KObj(binding.pvc))
```
Comment (alculquicondor) [inline pkg/scheduler/framework/plugins/volumebinding/binder.go:584]: @msau42 for my own understanding: what is the difference of the state of things at this point compared to line 747.

Is it worth logging both before and after calling `Update`? My gut feeling is that only after.

Comment (msau42) [reply pkg/scheduler/framework/plugins/volumebinding/binder.go:584]: There's a sequence of updates that happens on the PVC and PV objects to bind them together. The scheduler starts that sequence with this update, and then waits for the PV controller finishes the sequence. So L747 is when the PV controller has completed.

I think logging before could be a lower log level. The actual update will show up in api audit logs, and if there was an api server error, that would be returned here.

Comment (TommyStarK) [reply pkg/scheduler/framework/plugins/volumebinding/binder.go:584]: Should I set the log level of L577 to V(4) (the log before performing the update) ?

Comment (alculquicondor) [reply pkg/scheduler/framework/plugins/volumebinding/binder.go:584]: My main request is that the log line doesn't say "bound", as clearly the process didn't finish.

Logging in the scheduler makes it easy to debug, but we probably don't need both log lines. I also prefer only logging at V(2) after the Update call, but maybe we can be more explicit that there is more to come, as the process didn't finish at this point either, and it could be confusing to people oncall. What would be a good description @msau42?

Comment (msau42) [reply pkg/scheduler/framework/plugins/volumebinding/binder.go:584]: How about something like "Updated PersistentVolume with claim. Waiting for binding to complete"

File: pkg/scheduler/framework/plugins/volumebinding/binder.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/scheduler/framework/plugins/volumebinding/binder.go:580]: Can you verify what happens with the returned error?

File: pkg/scheduler/framework/plugins/volumebinding/binder.go (hunk 4 above)
Comment (TommyStarK) [reply pkg/scheduler/framework/plugins/volumebinding/binder.go]: Thank you @msau42, done in d70858bcc6a

File: pkg/scheduler/framework/plugins/volumebinding/binder.go (hunk 3 above)
Comment (TommyStarK) [reply pkg/scheduler/framework/plugins/volumebinding/binder.go:580]: According to the code, if an error occurs it will be returned to retry scheduling. It goes back to `handleBindingCycleError` in schedule_one.go.

https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go#L322-L349

Comment (alculquicondor) [reply pkg/scheduler/framework/plugins/volumebinding/binder.go:580]: Right, so ultimately it would be logged here https://github.com/kubernetes/kubernetes/blob/a5f59ccf37fabacf0339aeaf95b6929db7460f64/pkg/scheduler/schedule_one.go#L884

No need to increase the verbosity in this line.

File: pkg/scheduler/framework/plugins/volumebinding/binder.go (hunk 4 above)
Comment (alculquicondor) [reply pkg/scheduler/framework/plugins/volumebinding/binder.go]: It doesn't currently say: `Waiting for binding to complete`

Comment (alculquicondor) [reply pkg/scheduler/framework/plugins/volumebinding/binder.go]: Oops, I was looking at the wrong line

File: pkg/scheduler/framework/plugins/volumebinding/binder.go [hunk 5]
```diff
@@ -573,16 +573,15 @@ func (b *volumeBinder) bindAPIUpdate(ctx context.Context, pod *v1.Pod, bindings
 	// Do the actual prebinding. Let the PV controller take care of the rest
 	// There is no API rollback if the actual binding fails
 	for _, binding = range bindings {
-		klog.V(5).InfoS("bindAPIUpdate: binding PV to PVC", "pod", klog.KObj(pod), "PV", klog.KObj(binding.pv), "PVC", klog.KObj(binding.pvc))
 		// TODO: does it hurt if we make an api call and nothing needs to be updated?
-		klog.V(2).InfoS("Claim bound to volume", "PVC", klog.KObj(binding.pvc), "PV", klog.KObj(binding.pv))
+		klog.V(2).InfoS("Updating PersistentVolume: binding to claim", "pod", klog.KObj(pod), "PV", klog.KObj(binding.pv), "PVC", klog.KObj(binding.pvc))
```
Comment (alculquicondor) [inline pkg/scheduler/framework/plugins/volumebinding/binder.go:577]: Let's vert this back to V(5)

File: pkg/scheduler/framework/plugins/volumebinding/binder.go (hunk 3 above)
Comment (TommyStarK) [reply pkg/scheduler/framework/plugins/volumebinding/binder.go:580]: understood, I'll leave the PR as it is and wait for additional review/approval

File: pkg/scheduler/framework/plugins/volumebinding/binder.go (hunk 5 above)
Comment (TommyStarK) [reply pkg/scheduler/framework/plugins/volumebinding/binder.go:577]: sure thing, done in 5531295bf96

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

**Comment by alculquicondor** [comment]
Can you cherry pick to all supported versions? v1.24 and newer (I think we are a bit too late for the last v1.23 release)

**Comment by alculquicondor** [comment]
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md

**Comment by TommyStarK** [comment]
sure, I will, thanks Aldo.
