### PR TITLE
Fix race condition in cinder attach/detach

### LINKED ISSUE #19602: Cinder volume is detached from running pod.
There is a race between detaching a volume when an old pod is being destroyed and attaching the same volume to a new pod on the same node:

1. pod A happily uses a volume
2. pod A is deleted (and kubelet starts to clean up the stuff)
3. pod B starts, with the same volume (and kubelet starts to set it up...)

At this point, the volume is still attached to the node, kubelet is really slow when destroying it...

4. kubelet attaches the volume to the node, because pod B will need it. This does not do anything, because the volume is already attached there.
5. kubelet mounts the volume to pod B directory (which is OK)
6. kubelet unmounts the volume from pod A directory (again, OK)
7. kubelet detaches the volume from the node, because pod A is being destroyed. *This detaches the volume, while it's still mounted into pod B directory*
8. kubelet starts pod B containers -> problems.

There should be some usage counter, so kubelet just decreases "reference count'" at step 7 instead of detaching the volume. Similar approach is already present in AWS code.

@kubernetes/rh-storage

### PR DESCRIPTION
**Pull request by jsafrane**
Resolves https://github.com/kubernetes/kubernetes/issues/19602

Most of the changes are related to unit test. The real fix is in cinder.go. Similar change is needed in most of the volume plugins! Cinder seems to be the easiest to reproduce in real world, as it's the slowest to attach volumes (and thus the window of opportunity is the largest).

Also, I added some logs here and there to debug this issue easily next time.

### CODE REVIEW

**Comment by jsafrane** [comment]
@k8s-bot unit test this

**Comment by jsafrane** [comment]
@k8s-bot test this

**Comment by jsafrane** [comment]
@k8s-bot test this

File: pkg/volume/cinder/cinder_test.go [hunk 1]
```diff
@@ -55,20 +60,62 @@ func TestCanSupport(t *testing.T) {
...
-	err := os.RemoveAll(globalPath)
+	fakeDeviceName := getFakeDeviceName(c.plugin.host, c.pdName)
+	// unmount the bind-mount - should be fast
+	err := c.mounter.Unmount(globalPath)
+	if err != nil {
+		return err
+	}
+
+	// Cinder detach is slow...
+	//time.Sleep(fake.attachDetachDuration)
```
Comment (markturansky) [inline pkg/volume/cinder/cinder_test.go]: left over sleep statement.  I assume this helped you find the race?

Comment (jsafrane) [inline pkg/volume/cinder/cinder_test.go]: Indeed, it's a left over from debugging. It's not needed to reproduce the bug, I removed it.

File: pkg/volume/util.go [hunk 2]
```diff
@@ -148,3 +149,66 @@ func CalculateTimeoutForVolume(minimumTimeout, timeoutIncrement int, pv *api.Per
 func RoundUpSize(volumeSizeBytes int64, allocationUnitBytes int64) int64 {
 	return (volumeSizeBytes + allocationUnitBytes - 1) / allocationUnitBytes
 }
+
+// VolumeGuard may be (optionally) used by volume plugins to synchronize
+// SetUp and TearDown operation on the same volume. Most plugins are not
+// thread safe and bad things can happend, when they SetUp and TearDown
+// the same volume at the same time. With a VolumeGuard, they are thread safe.
+type VolumeGuard struct {
```
Comment (saad-ali) [inline pkg/volume/util.go]: This is very similar to [`pkg/util/keymutex/keymutex.go` ](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/gce_pd/gce_util.go) which is used for the same purpose for GCE PDs. It would make sense to reuse that code and modify it if needed.

Comment (jsafrane) [inline pkg/volume/util.go]: Thanks for finding this, I removed my `VolumeGuard` completely.

**Comment by jsafrane** [comment]
Rebased & removed custom `VolumeGuard` mutexes.

**Comment by saad-ali** [comment]
LGTM. Thanks for the fix @jsafrane. Please squash the commits and I'll add the LGTM label.

File: pkg/volume/cinder/cinder_test.go [hunk 3]
```diff
@@ -191,9 +236,123 @@ func TestPlugin(t *testing.T) {
...
 	err = deleter.Delete()
 	if err != nil {
 		t.Errorf("Deleter() failed: %v", err)
 	}
 }
+
+// Test a race when a volume is simultaneously SetUp and TearedDown
+func TestAttachDetachRace(t *testing.T) {
+	flag.Parse()
+	flag.Lookup("v").Value.Set("10")
```
Comment (jsafrane) [inline pkg/volume/cinder/cinder_test.go]: Oops, some debugging leftovers, removed from the final patch.

**Comment by jsafrane** [comment]
@saad-ali, I *can* squash them, but I actually prefer the way they are organized now. Small patches with clear purpose.

**Comment by markturansky** [comment]
@jsafrane clear to review, yes, and that is helpful.  But still a logical single commit that is easy to rollback if things go south.  Squashing before merging a PR is standard procedure.

**Comment by jsafrane** [comment]
Squashed

**Comment by markturansky** [comment]
Thanks, Jan.  I'll add LGTM, since @saad-ali said he would have done that after a squash.

File: pkg/volume/cinder/cinder.go [hunk 4]
```diff
@@ -35,11 +36,13 @@ import (
...
 // This is the primary entrypoint for volume plugins.
 func ProbeVolumePlugins() []volume.VolumePlugin {
-	return []volume.VolumePlugin{&cinderPlugin{nil}}
+	return []volume.VolumePlugin{&cinderPlugin{}}
 }
 
 type cinderPlugin struct {
 	host volume.VolumeHost
+	// Guarding SetUp and TearDown operations
+	volumeGuard keymutex.KeyMutex
```
Comment (markturansky) [inline pkg/volume/cinder/cinder.go]: Rename to "lock" or "mutex"?  I've seen those two names throughout the codebase. I've used both in the pv controllers, but should probably standardize on one.

I prefer "mutex" (since that's what the thing actually is) and I will be sure to change "lock" to "mutex" in the controllers as we refactor them.

Comment (markturansky) [inline pkg/volume/cinder/cinder.go]: Also, I'm looking at KeyMutex and this is the exact thing we need to stripe locks by pv/pvc name.

**Comment by jsafrane** [comment]
```
=== RUN   TestAttachDetachRace
I0121 15:37:58.424363   19808 cinder_test.go:301] Attaching volume
I0121 15:37:58.924502   19808 cinder_test.go:312] Detaching volume
==================
WARNING: DATA RACE
Write by goroutine 19:
  k8s.io/kubernetes/pkg/util/mount.(*FakeMounter).Mount()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/mount/fake.go:70 +0x3cc
  k8s.io/kubernetes/pkg/volume/cinder.(*cinderVolumeBuilder).SetUpAt()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/cinder/cinder.go:271 +0x10dd
  k8s.io/kubernetes/pkg/volume/cinder.(*cinderVolumeBuilder).SetUp()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/cinder/cinder.go:231 +0x7b
  k8s.io/kubernetes/pkg/volume/cinder.TestAttachDetachRace.func1()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/cinder/cinder_test.go:302 +0x74

Previous read by goroutine 18:
  k8s.io/kubernetes/pkg/util/mount.(*FakeMounter).IsLikelyNotMountPoint()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/mount/fake.go:95 +0x64
  k8s.io/kubernetes/pkg/volume/cinder.(*cinderVolumeCleaner).TearDownAt()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/cinder/cinder.go:328 +0x210
  k8s.io/kubernetes/pkg/volume/cinder.(*cinderVolumeCleaner).TearDown()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/cinder/cinder.go:321 +0x7b
  k8s.io/kubernetes/pkg/volume/cinder.TestAttachDetachRace()
      /workspace/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/cinder/cinder_test.go:313 +0x1479
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc
```

I'll add locks around but come on, it's fake mounter...

File: pkg/volume/cinder/cinder.go (hunk 4 above)
Comment (jsafrane) [inline pkg/volume/cinder/cinder.go]: renamed to `volumeLocks`.

**Comment by jsafrane** [comment]
@k8s-bot unit test this.

I hate jenkins:
> Unable to perform initial IP allocation check: unable to persist the updated service IP allocations: serviceipallocations "" cannot be updated: the provided resource version does not match

File: pkg/volume/cinder/cinder.go (hunk 4 above)
Comment (markturansky) [inline pkg/volume/cinder/cinder.go]: i don't see the change.  also, how about just `locks`?   `b.plugin.locks.LockKey(b.pdName)` ?

Comment (jsafrane) [inline pkg/volume/cinder/cinder.go]: Sorry, pushed now.

File: pkg/util/mount/fake.go [hunk 5]
```diff
@@ -37,20 +46,56 @@ type FakeAction struct {
...
 func (f *FakeMounter) Unmount(target string) error {
+	f.mutex.Lock()
+	defer f.mutex.Unlock()
+
 	newMountpoints := []MountPoint{}
 	for _, mp := range f.MountPoints {
 		if mp.Path != target {
 			newMountpoints = append(newMountpoints, MountPoint{Device: mp.Device, Path: mp.Path, Type: mp.Type})
+		} else {
+			glog.V(5).Infof("Fake mounter: unmouted %s from %s", mp.Device, target)
```
Comment (markturansky) [inline pkg/util/mount/fake.go]: This if/else is clear to me, but I'm wondering about the Go (and Kube) preference to un-indent control flow.  Is something like this better or worse for idiomatic Go?

```
for {
    if mp.Path != target {
        newMountpoints = append(newMountpoints, MountPoint{...})
        continue 
    }
    glog.V(5).Infof("logstatement")
}
```

I'm not saying to make this change.  This is an open question as to style and idiomatic Go that I'd like to understand better.

@pmorie @smarterclayton any pointers on stylistic preference?

File: pkg/volume/cinder/cinder.go [hunk 6]
```diff
@@ -309,37 +324,65 @@ func (c *cinderVolumeCleaner) TearDown() error {
...
 		return err
 	}
 	if notmnt {
+		glog.V(4).Infof("Nothing is mounted to %s, ignoring", dir)
 		return os.Remove(dir)
 	}
+
+	// Find Cinder volumeID to lock the right volume
+	// TODO: refactor VolumePlugin.NewCleaner to get full volume.Spec just like
+	// NewBuilder. We could then find volumeID there without probing MountRefs.
```
Comment (markturansky) [inline pkg/volume/cinder/cinder.go]: Tim has this same kind of TODO in kubelet's volume code:  https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumes.go#L216

Not for this PR, of course, but it's worth thinking about a solution.

File: pkg/volume/cinder/cinder.go [hunk 7]
```diff
@@ -309,37 +324,65 @@ func (c *cinderVolumeCleaner) TearDown() error {
...
+		return fmt.Errorf("directory %s is not mounted", dir)
+	}
+	c.pdName = path.Base(refs[0])
+	glog.V(4).Infof("Found volume %s mounted to %s", c.pdName, dir)
+
+	// lock the volume (and thus wait for any concurrrent SetUpAt to finish)
+	c.plugin.volumeLocks.LockKey(c.pdName)
+	defer c.plugin.volumeLocks.UnlockKey(c.pdName)
+
+	// Reload list of references, there might be SetUpAt finished in the meantime
```
Comment (markturansky) [inline pkg/volume/cinder/cinder.go]: if the lock is at the beginning of the function, would you still need to reload the list here?

File: pkg/volume/cinder/cinder.go (hunk 6 above)
Comment (jsafrane) [inline pkg/volume/cinder/cinder.go]: I think kubelet has whole VolumeSpec available when it creates cleaners, so it's fairly simple change. On the other hand, all the volume plugins needs to be updated with new `NewCleaner` signature.

File: pkg/volume/cinder/cinder.go (hunk 7 above)
Comment (jsafrane) [inline pkg/volume/cinder/cinder.go]: All the code before `LockKey(c.pdName)` is there to actually find `c.pdName`. That's why passing whole `VolumeSpec` to `NewCleaner()` would be **much** nicer - `c.pdName` is actually `VolumeSpec.Cinder.VolumeID`.

File: pkg/util/mount/fake.go (hunk 5 above)
Comment (pmorie) [inline pkg/util/mount/fake.go]: I have no personal preference on this matter of style and I'm sure both styles exist in the codebase.

Comment (smarterclayton) [inline pkg/util/mount/fake.go]: We prefer not to use elses when continues accomplish the same function.  We also prefer the "meat" of the loop to be at the end of the loop block and the checks before to invoke continue for exceptional cases:

```
for {
  ... find reasons to exit early
  if exceptionalCase {
    continue
  }
  ... whatever the point of the loop is
  b = append(b, ...)
}
```

Comment (markturansky) [inline pkg/util/mount/fake.go]: Thanks @smarterclayton.  That was my understanding, as well.  I've been asked in different PRs to drop `else` from many `if` statements and the flow still made sense.

**Comment by jsafrane** [comment]
Rebased

**Comment by markturansky** [comment]
LGTM.

Since @saad-ali also LGTM'd it, I will add the label.

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

Tests have been pending for 24 hours

**Comment by jsafrane** [comment]
@markturansky, I had to rebase and I lost LGTH label, can you please add it again?
