### PR TITLE
apps/StatefulSets: Garbage collector should be able to orphan ControllerRevisions too

### LINKED ISSUE #84982: Garbage collector should orphan ControllerRevisions created by Statefulset when deleteOptions.OrphanDependents is true
**What happened**:

- Create a stateful set
- Delete with propagationPolicy=Orphan
- ControllerRevisions owned by stateful set will be deleted

**What you expected to happen**:

ControllerRevisions owned by stateful set should be orphaned.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a stateful set
- Delete with propagationPolicy=Orphan
- Check controller revisions owned by this statefulset

**Anything else we need to know?**:

Same as https://github.com/kubernetes/kubernetes/issues/42639.
Before adopting controller revisions, we should check the deletion timestamp like [what DaemonSet does](https://github.com/kubernetes/kubernetes/blob/59aa8fd99e2e0c566310492185658d51f6343782/pkg/controller/daemon/update.go#L253-L267).

xref: https://github.com/kubernetes/kubernetes/pull/42938 https://github.com/kubernetes/kubernetes/pull/47084

### PR DESCRIPTION
**Pull request by cofyc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

Garbage collector should be able to orphan ControllerRevisions too. 

Right now when a stateful set is deleted by propagationPolicy=Orphan, the GC will orphan its controller revisions. However, controller revisions will be adopted by the deleted StatefulSet again. 
Later, controller revisions will be deleted by the GC. So it's not possible to keep the previous controller revisions. 

**Which issue(s) this PR fixes**:

Fixes #84982

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Garbage collector now can correctly orphan ControllerRevisions when StatefulSets are deleted with orphan propagation policy.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/controller/statefulset/stateful_set.go [hunk 1]
```diff
@@ -319,12 +321,9 @@ func (ssc *StatefulSetController) adoptOrphanRevisions(set *apps.StatefulSet) er
...
 	if hasOrphans {
-		fresh, err := ssc.kubeClient.AppsV1().StatefulSets(set.Namespace).Get(set.Name, metav1.GetOptions{})
-		if err != nil {
-			return err
-		}
-		if fresh.UID != set.UID {
-			return fmt.Errorf("original StatefulSet %v/%v is gone: got uid %v, wanted %v", set.Namespace, set.Name, fresh.UID, set.UID)
+		canAdoptErr := ssc.canAdoptFunc(set)()
+		if canAdoptErr != nil {
+			return fmt.Errorf("can't adopt ControllerRevisions: %v", canAdoptErr)
```
Comment (cofyc) [inline pkg/controller/statefulset/stateful_set.go]: StatefulSet does not use `ControllerRevisionControllerRefManager` [like DaemonSet](https://github.com/kubernetes/kubernetes/blob/59aa8fd99e2e0c566310492185658d51f6343782/pkg/controller/daemon/update.go#L253-L267) to manage controller revisions, so this is quick.

Maybe we can migrate to use ControllerRevisionControllerRefManager in the future?

**Review by janetkuo — APPROVED** [review]

**Comment by janetkuo** [comment]
/approve

Thanks, good catch!
Need someone else to review and lgtm.

**Comment by cofyc** [comment]
@janetkuo Thanks!

@soltysh @krmayankk can you take a look at?

**Comment by cofyc** [comment]
cc @enisoc can you take a look?

**Comment by cofyc** [comment]
/cc @enisoc 
Thanks!

**Comment by cofyc** [comment]
/cc @kow3ns
/cc @smarterclayton
can you take a look?

**Comment by cofyc** [comment]
@kubernetes/sig-apps-pr-reviews anyone can review this?

**Comment by cofyc** [comment]
resolved conflicts with https://github.com/kubernetes/kubernetes/pull/86801 and https://github.com/kubernetes/kubernetes/pull/87299

**Comment by cofyc** [comment]
@neolit123 can you help review this?

**Comment by neolit123** [comment]
@cofyc i check the PR quickly and this looks good to me, but this is an area of the code that i'm not familiar with.

you can try asking in the #sig-apps channel on slack for someone that can LGTM.
thanks.

**Comment by cofyc** [comment]
Thanks!

**Comment by cofyc** [comment]
ping @kubernetes/sig-apps-pr-reviews
can anyone review this?

File: pkg/controller/statefulset/stateful_set.go (hunk 1 above)
Comment (mortent) [reply pkg/controller/statefulset/stateful_set.go]: That sounds like a good idea. Can you create an issue on this?

**Review by mortent — APPROVED** [review]
/lgtm

File: pkg/controller/statefulset/stateful_set.go (hunk 1 above)
Comment (cofyc) [reply pkg/controller/statefulset/stateful_set.go]: sure, https://github.com/kubernetes/kubernetes/issues/88150
