### PR TITLE
CRI: Work around container create conflict.

### LINKED ISSUE #40443: Bugs in docker 1.11 may stop kubelet from creating containers in the docker-CRI implementation
Forked from #34289.

In some cases, when docker (1.11.2) fails to create a container, it will not release the "name" associated with the container. kubelet can never create a container with the same name again. This phantom container cannot be listed or removed. The only way to release the name is to restart the docker daemon.

```console
$ sudo docker run --name=foo --security-opt=foo:bar busybox
docker: Error response from daemon: Invalid --security-opt 2: "foo:bar".
See 'docker run --help'.
$ sudo docker run --name=foo busybox
docker: Error response from daemon: Conflict. The name "/foo" is already in use by container 3f7fae9d56619c67cf1baa85bab8e649ef344931ccae385b3cec809bf79fe829. You have to remove (or rename) that container to be able to reuse that name..
See 'docker run --help'.
$ sudo docker rm foo   
Error response from daemon: No such container: foo
$ sudo docker rm 3f7fae9d56619c67cf1baa85bab8e649ef344931ccae385b3cec809bf79fe829 
Error response from daemon: No such container: 3f7fae9d56619c67cf1baa85bab8e649ef344931ccae385b3cec809bf79fe829
```

The [deferred cleanup function](https://github.com/docker/docker/blob/v1.11.2/daemon/create.go#L75) relies on the container id lookup, but the id (not the name) [hasn't been registered](https://github.com/docker/docker/blob/v1.11.2/daemon/create.go#L92) at the time of the [failure](https://github.com/docker/docker/blob/v1.11.2/daemon/create.go#L83-L90). This relevant code was refactored in docker 1.12+ and the bug was fixed.

Pre-CRI kubelet embeds a random string into the container name, so it'll always recover in this situation (i.e., no naming conflict). Now kubelet uses deterministic names for containers, this become a problem. The container will never be created. @Random-Liu wrote a script to scan the kubelet-cri-serial build logs and found that about ~7% of the builds ran into this problem.

We've discussed several fixes and decided to add a workaround in the `dockershim` package (note that it's not in kubelet because this is caused by a docker bug)
1. create a container
2. if it fails due to naming conflict, try removing the container
3. if the removal request fails with a "No such container" response, try creating a container with a `_randomstring` suffix appended to the name.
When parsing the name, dockershim will have to check if this suffix exists and trim them before returning to kubelet.

/cc @dchen1107 @kubernetes/sig-node-bugs

### PR DESCRIPTION
**Pull request by Random-Liu**
Fixes https://github.com/kubernetes/kubernetes/issues/40443.

This PR added a random suffix in the container name when we:
* Failed to create the container because of "Conflict".
* And failed to remove the container because of "No such container".

@yujuhong @feiskyer 
/cc @kubernetes/sig-node-bugs

### CODE REVIEW

File: pkg/kubelet/dockershim/docker_container_test.go [hunk 1]
```diff
@@ -215,3 +216,69 @@ func TestContainerLogPath(t *testing.T) {
...
+		ds, fDocker, _ := newTestDockerService()
+
+		if test.createError != nil {
+			fDocker.InjectError("create", test.createError)
+		}
+		if test.removeError != nil {
+			fDocker.InjectError("remove", test.removeError)
+		}
+		name, err := ds.CreateContainer(sandboxId, config, sConfig)
+		assert.Equal(t, test.expectError, err)
```
Comment (yujuhong) [inline pkg/kubelet/dockershim/docker_container_test.go]: nit: print the test case description in these asserts .
```
assert.Equal(t, test.expectError, err, "TestCase: %s", desc)
```

File: pkg/kubelet/dockershim/naming.go [hunk 2]
```diff
@@ -92,7 +102,9 @@ func parseSandboxName(name string) (*runtimeapi.PodSandboxMetadata, error) {
 	name = strings.TrimPrefix(name, "/")
 
 	parts := strings.Split(name, nameDelimiter)
-	if len(parts) != 6 {
+	// Tolerate the random suffix.
+	// TODO(random-liu): Remove 7 field case when docker 1.11 is deprecated.
+	if len(parts) != 6 && len(parts) != 7 {
```
Comment (yujuhong) [inline pkg/kubelet/dockershim/naming.go]: What would happen to sandbox listing if more than two containers have the same name (but different random suffixes)? We should make sure we return the latest one.

File: pkg/kubelet/dockershim/helpers.go [hunk 3]
```diff
@@ -295,22 +296,30 @@ func getUserFromImageUser(imageUser string) (*int64, string) {
 // create a new container named FOO. To work around this, we parse the error
 // message to identify failure caused by naming conflict, and try to remove
 // the old container FOO.
+// Sometimes even removal may fail with "no such container" error. In that
+// case we have to create the container with a randomized name.
```
Comment (yujuhong) [inline pkg/kubelet/dockershim/helpers.go]: nit: add the issue number #40443 in the comment to give people more context.

File: pkg/kubelet/dockershim/docker_sandbox.go [hunk 4]
```diff
@@ -69,7 +69,9 @@ func (ds *dockerService) RunPodSandbox(config *runtimeapi.PodSandboxConfig) (str
 		return "", fmt.Errorf("failed to make sandbox docker config for pod %q: %v", config.Metadata.Name, err)
 	}
 	createResp, err := ds.client.CreateContainer(*createConfig)
-	recoverFromConflictIfNeeded(ds.client, err)
+	if err != nil {
+		createResp, err = recoverFromCreationConflictIfNeeded(ds.client, *createConfig, err)
```
Comment (yujuhong) [inline pkg/kubelet/dockershim/docker_sandbox.go]: Should we do this for regular container creation as well?

File: pkg/kubelet/dockershim/naming.go (hunk 2 above)
Comment (Random-Liu) [inline pkg/kubelet/dockershim/naming.go]: If the container is shown in `docker ps`, we will create container will increased attempt.
If the container is not shown in `docker ps`, we will randomize the container name again anyway.

File: pkg/kubelet/dockershim/helpers.go (hunk 3 above)
Comment (Random-Liu) [inline pkg/kubelet/dockershim/helpers.go]: Will do.

File: pkg/kubelet/dockershim/docker_sandbox.go (hunk 4 above)
Comment (Random-Liu) [inline pkg/kubelet/dockershim/docker_sandbox.go]: I think so.

File: pkg/kubelet/dockershim/docker_container_test.go (hunk 1 above)
Comment (Random-Liu) [inline pkg/kubelet/dockershim/docker_container_test.go]: The test case is printed at the beginning of the loop. :)

File: pkg/kubelet/dockershim/naming.go (hunk 2 above)
Comment (yujuhong) [inline pkg/kubelet/dockershim/naming.go]: Assume we have two containers `abc_randomstr1` and `abc_randomstr2`. Which one would `ListSandboxes` return?

Comment (Random-Liu) [inline pkg/kubelet/dockershim/naming.go]: I mean that according to the current logic, there is no way that kubelet will create 2 containers with the same name but different suffix. Just like we are sure that kubelet will not create 2 containers with the same attempt (if there is no such name conflict bug).

Comment (Random-Liu) [inline pkg/kubelet/dockershim/naming.go]: But we can add the check to make less assumption on kubelet.

File: pkg/kubelet/dockershim/docker_container_test.go (hunk 1 above)
Comment (yujuhong) [inline pkg/kubelet/dockershim/docker_container_test.go]: But it doesn't get printed in the failure message, which is usually what I look for :)

File: pkg/kubelet/dockershim/naming.go (hunk 2 above)
Comment (yujuhong) [inline pkg/kubelet/dockershim/naming.go]: I agree that this should not happen. Just wanted to know what the behavior would be in case it happens due to buggy code. I think kubelet sorts the containers by creation timestamp and go through the latest one first, so this should not be an issue anyway.

Comment (Random-Liu) [inline pkg/kubelet/dockershim/naming.go]: If there are 2 containers `abc_randomstr1` and `abc_randomstr2`. Both of them will be returned by list functions.

This will cause 2 containers with the same `Attempt` but different `ID`s being returned. This seems fine, because we mainly rely on container id and don't use `Attempt` that much.

This will cause:
* Wrong restart count. 
* New container can't create log path.

Comment (feiskyer) [inline pkg/kubelet/dockershim/naming.go]: From user's view, only latest container is shown. So I think here should not be a problem.

**Comment by feiskyer** [comment]
LGTM

**Comment by yujuhong** [comment]
Looks good overall, but let's add the same logic to regular (i.e., non-sandbox) container creation as well.

**Comment by yujuhong** [comment]
> Looks good overall, but let's add the same logic to regular (i.e., non-sandbox) container creation as well.

My mistake. I missed the first file where you did this.

/lgtm
/approve

**Comment by Random-Liu** [comment]
I've manually verified the PR by create a pod with bad security option. Now kubelet will try to recreate container with random suffix if it hits the creations conflict and "no such container" deletion error.

**Comment by yujuhong** [comment]
> I've manually verified the PR by create a pod with bad security option. Now kubelet will try to recreate container with random suffix if it hits the creations conflict and "no such container" deletion error.

Great!

**Comment by yujuhong** [comment]
> Great!

Let's monitor the tests to see if the fix is sufficient.
