### PR TITLE
Fix null pointer access in doPodResizeAction for kubeletonly mode

### LINKED ISSUE #116262: VPA panics in standalone kubelets
1. Start a standalone kubelet (not registered to an API server)

2. Manager construction short-circuits `Start()` here:

https://github.com/kubernetes/kubernetes/blob/253ab3eda71f250ad6692bb16f035cebaf0651c9/pkg/kubelet/status/status_manager.go#L186-L192

3. VPA state is never initialized here:

https://github.com/kubernetes/kubernetes/blob/253ab3eda71f250ad6692bb16f035cebaf0651c9/pkg/kubelet/status/status_manager.go#L195-L200

4. All pod syncs then panic on this line:

https://github.com/kubernetes/kubernetes/blob/a1b12e49eac237a37939642d0c3395008b9ab380/pkg/kubelet/kubelet.go#L2412

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x3b5f21f]
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).HandlePodAdditions(0xc00073c400, {0xc001816c00?, 0x27, 0x40})
  pkg/kubelet/kubelet.go:2412 +0x4df
```

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/issues/102884#issuecomment-1454089210_

cc @thockin @vinaykul
/sig node
/kind bug
/priority important-soon

### PR DESCRIPTION
**Pull request by vinaykul**
#### What type of PR is this?
/king bug
/kind failing-test

#### What this PR does / why we need it:
In kubelet-only mode, ResourceConfigForPod function in kubelet may return nil values for CPU quota if pod CPU limits are not set in burstable or be pods. This PR fixes NP access and limits computePodResizeAction and doPodResize from being invoked for static pods.

#### Which issue(s) this PR fixes: 

Fixes #116262

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by liggitt** [comment]
unfortunately, I don't have context to know the implications of making the stub implementation return errors (which impacts normal operation mode on Windows, I think), or whether it is correct to special-case static pods to short-circuit resize

/assign @thockin
for resize behavior
/assign @smarterclayton 
for opinion on static pod intersection
/assign @mmiranda96
for opinion on pkg/kubelet/cm/container_manager_stub.go changes and their impact on Windows

**Comment by SergeyKanzhelev** [comment]
First iteration on how this can be tested: https://github.com/kubernetes/kubernetes/pull/116551

**Comment by thockin** [comment]
I also lack the code context to review this, though it feels to me like an implicit invariant is being violated and this is patching up those places that made the assumption, rather than fixing the invariant?

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 1]
```diff
@@ -941,6 +951,7 @@ func (m *kubeGenericRuntimeManager) computePodActions(ctx context.Context, pod *
 			message = fmt.Sprintf("Container %s failed startup probe", container.Name)
 			reason = reasonStartupProbe
 		} else if utilfeature.DefaultFeatureGate.Enabled(features.InPlacePodVerticalScaling) &&
+			!types.IsStaticPod(pod) &&
```
Comment (liggitt) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:954]: it's _really_ hard to understand how this carve-out for static pods combines with ignoring resource changes and skipping the `restart = true` case above when InPlacePodVerticalScaling is enabled

At first glance, it looks like an update to a static pod manifest's resources which previously would have triggered a restart might now fall through to this case, get ignored because it's a static pod, and the container will be kept as is. Is that possible?

File: pkg/kubelet/cm/container_manager_stub.go [hunk 2]
```diff
@@ -96,11 +98,11 @@ func (cm *containerManagerStub) GetDevicePluginResourceCapacity() (v1.ResourceLi
 }
 
 func (m *podContainerManagerStub) GetPodCgroupConfig(_ *v1.Pod, _ v1.ResourceName) (*ResourceConfig, error) {
-	return nil, nil
+	return nil, fmt.Errorf("not implemented")
```
Comment (liggitt) [inline pkg/kubelet/cm/container_manager_stub.go:101]: I didn't realize these methods were just added for the VPA feature...

I agree it seems better to return errors instead of `nil, nil` which can easily cause panics, but the fact that windows is using this stub impl makes me wonder what error loops windows nodes will get caught in or log profusely over

**Comment by liggitt** [comment]
We're down to the wire on this feature, and I'm not confident in the operation of the kubelet with this feature gate enabled, even with the static pod carve-outs in this PR (e.g. https://github.com/kubernetes/kubernetes/pull/116504#discussion_r1134868462).

I'm not familiar enough with the source of all of things considered by computePodResizeAction and done by doPodResizeAction to understand if those would make sense to still do for static pods running in a kube-apiserver-connected kubelet. @thockin, @smarterclayton, can you weigh in?

**Comment by liggitt** [comment]
> I also lack the code context to review this, though it feels to me like an implicit invariant is being violated and this is patching up those places that made the assumption, rather than fixing the invariant?

if there's not a kubelet approver with context who can say whether this should apply to static pods or not, are we confident leaving this in for 1.27?

**Comment by vinaykul** [comment]
> > I also lack the code context to review this, though it feels to me like an implicit invariant is being violated and this is patching up those places that made the assumption, rather than fixing the invariant?
> 
> if there's not a kubelet approver with context who can say whether this should apply to static pods or not, are we confident leaving this in for 1.27?

I think we should be able to support resize for static pods as well. But it is a scenario I have not considered and tested for, so I'm hesitant to "wing it" especially without a way to repro the NPE you have in standalone kubelet scenario.

I tried it just out of curiosity, re-enabling static pods for `handlePodResourcesResize`,  `computePodResizeAction`, and `doPodResizeAction` to see if it works with the NP check and resizing a static pod with apiserver.  I cannot see the updates come through.

```golang
root@vbuild:~/go/src/k8s.io/master_k8s# ./cluster/kubectl.sh patch pod bpod3-127.0.0.1 --patch '{"spec":{"containers":[{"name":"ctr", "resources":{"requests":{"cpu":"300m"}}}]}}'
pod/bpod3-127.0.0.1 patched
root@vbuild:~/go/src/k8s.io/master_k8s# k get pod bpod3-127.0.0.1 -ojson | jq .spec.containers[0].resources
{
  "requests": {
    "cpu": "300m"
  }
}
...
  2584:	func (kl *Kubelet) handlePodResourcesResize(pod *v1.Pod) {
=>2585:		if pod.Status.Phase != v1.PodRunning {
  2586:			return
  2587:		}
  2588:		podResized := false
  2589:		for _, container := range pod.Spec.Containers {
  2590:			if len(container.Resources.Requests) == 0 {
(dlv) p pod.Spec.Containers[0].Resources.Requests
k8s.io/api/core/v1.ResourceList [
	"cpu": {
		i: (*"k8s.io/apimachinery/pkg/api/resource.int64Amount")(0x4000ece588),
		d: (*"k8s.io/apimachinery/pkg/api/resource.infDecAmount")(0x4000ece598),
		s: "100m",
		Format: "DecimalSI",}, 
]
(dlv) bt
0  0x0000000003ac58c8 in k8s.io/kubernetes/pkg/kubelet.(*Kubelet).handlePodResourcesResize
   at /root/go/src/k8s.io/master_k8s/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2585
1  0x0000000003abc2b8 in k8s.io/kubernetes/pkg/kubelet.(*Kubelet).SyncPod
   at /root/go/src/k8s.io/master_k8s/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1841
2  0x0000000003aff08c in k8s.io/kubernetes/pkg/kubelet.(*podWorkers).podWorkerLoop.func1
   at /root/go/src/k8s.io/master_k8s/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:1241
3  0x0000000003afdd10 in k8s.io/kubernetes/pkg/kubelet.(*podWorkers).podWorkerLoop
   at /root/go/src/k8s.io/master_k8s/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:1246
4  0x0000000003afb120 in k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1
   at /root/go/src/k8s.io/master_k8s/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:920
5  0x00000000000803d4 in runtime.goexit
   at /root/go/src/k8s.io/master_k8s/_output/local/.gimme/versions/go1.20.2.linux.arm64/src/runtime/asm_arm64.s:1172
(dlv) 
```

I prefer a defensive fix (static pods not supported with in-place resize for alpha, take an issue to fix in 1.28 and do it right with good unit/e2e test coverage) now because we are so close to code freeze rather than try to check in something that is not tested.

File: pkg/kubelet/cm/container_manager_stub.go (hunk 2 above)
Comment (vinaykul) [reply pkg/kubelet/cm/container_manager_stub.go:101]: Windows is not supported for alpha, we decided a while back that it is not alpha blocker. There is another PR that seeks to add support for Windows: https://github.com/kubernetes/kubernetes/pull/112599/files# , it needs some more work.
/cc @marosset

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 1 above)
Comment (vinaykul) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:954]: From observation, on manifest update (save), the pod remove/add happens much earlier.
```bash
  2473:	// HandlePodRemoves is the callback in the SyncHandler interface for pods
  2474:	// being removed from a config source.
=>2475:	func (kl *Kubelet) HandlePodRemoves(pods []*v1.Pod) {
  2476:		start := kl.clock.Now()
  2477:		for _, pod := range pods {
  2478:			kl.podManager.DeletePod(pod)
  2479:			if kubetypes.IsMirrorPod(pod) {
  2480:				kl.handleMirrorPod(pod, start)
(dlv) bt
0  0x0000000003ad70c0 in k8s.io/kubernetes/pkg/kubelet.(*Kubelet).HandlePodRemoves
   at /root/go/src/k8s.io/kubernetes-kubeletonly-crash/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2475
1  0x0000000003ad582c in k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoopIteration
   at /root/go/src/k8s.io/kubernetes-kubeletonly-crash/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2268
2  0x0000000003ad3fdc in k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoop
   at /root/go/src/k8s.io/kubernetes-kubeletonly-crash/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2205
3  0x0000000003acb5c8 in k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run
   at /root/go/src/k8s.io/kubernetes-kubeletonly-crash/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1560
4  0x0000000003b365fc in k8s.io/kubernetes/cmd/kubelet/app.startKubelet.func1
   at /root/go/src/k8s.io/kubernetes-kubeletonly-crash/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:1190
5  0x00000000000803d4 in runtime.goexit
   at /root/go/src/k8s.io/kubernetes-kubeletonly-crash/_output/local/.gimme/versions/go1.20.2.linux.arm64/src/runtime/asm_arm64.s:1172
(dlv) c
> k8s.io/kubernetes/pkg/kubelet.(*Kubelet).HandlePodAdditions() /root/go/src/k8s.io/kubernetes-kubeletonly-crash/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2393 (hits goroutine(211):1 total:1) (PC: 0x3ad6640)
  2388:		}
  2389:	}
  2390:	
  2391:	// HandlePodAdditions is the callback in SyncHandler for pods being added from
  2392:	// a config source.
=>2393:	func (kl *Kubelet) HandlePodAdditions(pods []*v1.Pod) {
  2394:		start := kl.clock.Now()
  2395:		sort.Sort(sliceutils.PodsByCreationTime(pods))
  2396:		if utilfeature.DefaultFeatureGate.Enabled(features.InPlacePodVerticalScaling) {
  2397:			kl.podResizeMutex.Lock()
  2398:			defer kl.podResizeMutex.Unlock()
(dlv) bt
0  0x0000000003ad6640 in k8s.io/kubernetes/pkg/kubelet.(*Kubelet).HandlePodAdditions
   at /root/go/src/k8s.io/kubernetes-kubeletonly-crash/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2393
1  0x0000000003ad5490 in k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoopIteration
   at /root/go/src/k8s.io/kubernetes-kubeletonly-crash/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2262
2  0x0000000003ad3fdc in k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoop
   at /root/go/src/k8s.io/kubernetes-kubeletonly-crash/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2205
3  0x0000000003acb5c8 in k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run
   at /root/go/src/k8s.io/kubernetes-kubeletonly-crash/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1560
4  0x0000000003b365fc in k8s.io/kubernetes/cmd/kubelet/app.startKubelet.func1
   at /root/go/src/k8s.io/kubernetes-kubeletonly-crash/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:1190
5  0x00000000000803d4 in runtime.goexit
   at /root/go/src/k8s.io/kubernetes-kubeletonly-crash/_output/local/.gimme/versions/go1.20.2.linux.arm64/src/runtime/asm_arm64.s:1172
(dlv) c
```

**Comment by mmiranda96** [comment]
I don't have much context on this, but if we're not supporting Windows for alpha then the code changes in `pkg/kubelet/cm/container_manager_stub` look ok.

Just for those changes,  
/lgtm

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 1 above)
Comment (liggitt) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:954]: I still think the `if` check on line 938 is incorrect if we're going to let static pods skip restart there because in-place is enabled, but exclude them from being handled here

If we're going to exclude static pods, can we do something like this:

```go
func canBeVerticallyScaled(pod *api.Pod) bool {
  if !utilfeature.DefaultFeatureGate.Enabled(features.InPlacePodVerticalScaling) {
    return false
  }
  if types.IsStaticPod(pod) {
    // TODO: ...
    return false
  }
  return true
}
```

and then use that in all three of these places:
```go
		if _, _, changed := containerChanged(&container, containerStatus); changed &&
			(!canBeVerticallyScaled(pod) || kubecontainer.HashContainerWithoutResources(&container) != containerStatus.HashWithoutResources) {
...
		} else if canBeVerticallyScaled(pod) && !m.computePodResizeAction(pod, idx, containerStatus, &changes) {
...
	// Step 7: For containers in podContainerChanges.ContainersToUpdate[CPU,Memory] list, invoke UpdateContainerResources
	if canBeVerticallyScaled(pod) {
...
```

Comment (dchen1107) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:954]: @vinaykul can you respond @liggitt's above comment?

Comment (vinaykul) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:954]: I just had a call with Clayton and he reconfirmed that static pods should not be updated via API. So excluding static pods is the correct thing to do. Let me take a closer look at your suggested change to see if I can fold the feature gate into such a function as it looks cleaner.

**Comment by thockin** [comment]
> if there's not a kubelet approver with context who can say whether this should apply to static pods or not, are we confident leaving this in for 1.27?

That's the question, innit?    @derekwaynecarr @mrunalp @SergeyKanzhelev @bobbypage - this whole feature is at risk of rollback.  Help?

I think we could get away with saying that static pods are explicitly not supported for now, but I'm not sure that solves the problem.  Are we OK with a gate which can disrupt more than its own feature?  It seems fair game to me, but not ideal, obv.

**Comment by bobbypage** [comment]
We discussed this today in SIG-Node meeting. The consensus in meeting is that VPA should not apply to static pods because the source of truth for static pods is the manifest stored on the disk. (xref: https://github.com/kubernetes/kubernetes/issues/116262#issuecomment-1468558194). There are two cases to consider:

1) stand-alone kubelet: In this case, the kubelet is running in standalone and not connected to the API server. VPA doesn't make sense as there is no API-sever to initiate resize
2) static pods with kubelet connected to api server. In this case, a mirror pod is created to represent the pod manifest stored on disk, but the mirror pod is intended to be "read only" and and not controlled via the api. 

So in both cases, it makes sense to ignore static pods for VPA.

**Comment by dchen1107** [comment]
> if there's not a kubelet approver with context who can say whether this should apply to static pods or not, are we confident leaving this in for 1.27?

We discussed at today's SIG Node, and here is what I preferred and SIG Node community agreed:

1) The source of the true for the static pods are those manifest files. I don't think VPA feature should apply to the static pods at the first place.
2) Non-standalone Kubelet mode, those static pods will have a corresponding mirror pods created. In this case, the scheduler can take the static pods / mirror pods into the consideration at the admission time. 
3) In standalone kubelet case, there is no mirror pods created; hence the pod admission will be only evaluated at node level as the last defense. 

With all 3 reasons, we think VPA should exclude the static pods. The intention of PR is correct. 

But I haven't figure out the root cause of the initial null point issue yet since none of us reproduce the issue.

**Comment by thockin** [comment]
The question is - who will take ownership for this PR review or make the call to back it out and try again next time?

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 1 above)
Comment (vinaykul) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: @liggitt I pushed a commit based on your suggested changes, it looks more obvious and cleaner now. PTAL.

Validating static pods with this PR:

  - Feature gate enabled, normal local cluster.
```bash
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# cat /var/run/kubernetes/static-pods/3Bpod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: bpod3
spec:
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 2
  containers:
  - name: ctr
    image: skiibum/testpod:qos
    imagePullPolicy: IfNotPresent
    command: ["tail", "-f", "/dev/null"]
    resources:
      requests:
        cpu: "100m"
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# k get pod bpod3-127.0.0.1 -ojson | jq .spec.containers[0].resources.requests
{
  "cpu": "100m"
}
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# k get pod bpod3-127.0.0.1 -ojson | jq .status.containerStatuses[0].resourcesAllocated
{
  "cpu": "100m"
}
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# k get pod bpod3-127.0.0.1 -ojson | jq .status.containerStatuses[0].resources
{
  "requests": {
    "cpu": "100m"
  }
}
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# 
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# cat /var/run/kubernetes/static-pods/3Bpod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: bpod3
spec:
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 2
  containers:
  - name: ctr
    image: skiibum/testpod:qos
    imagePullPolicy: IfNotPresent
    command: ["tail", "-f", "/dev/null"]
    resources:
      requests:
        cpu: "200m"
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# k get pod bpod3-127.0.0.1 -ojson | jq .spec.containers[0].resources
{
  "requests": {
    "cpu": "200m"
  }
}
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# k get pod bpod3-127.0.0.1 -ojson | jq .status.containerStatuses[0].resourcesAllocated
{
  "cpu": "200m"
}
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# k get pod bpod3-127.0.0.1 -ojson | jq .status.containerStatuses[0].resources
{
  "requests": {
    "cpu": "200m"
  }
}
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash#
```

  - Feature gate disabled, normal local cluster.
```bash
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# cat /var/run/kubernetes/static-pods/3Bpod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: bpod3
spec:
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 2
  containers:
  - name: ctr
    image: skiibum/testpod:qos
    imagePullPolicy: IfNotPresent
    command: ["tail", "-f", "/dev/null"]
    resources:
      requests:
        cpu: "200m"
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# 
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# k get pod bpod3-127.0.0.1 -ojson | jq .spec.containers[0].resources
{
  "requests": {
    "cpu": "200m"
  }
}
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# k get pod bpod3-127.0.0.1 -ojson | jq .status.containerStatuses[0].resourcesAllocated
null
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# k get pod bpod3-127.0.0.1 -ojson | jq .status.containerStatuses[0].resources
null
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# cat /var/run/kubernetes/static-pods/3Bpod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: bpod3
spec:
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 2
  containers:
  - name: ctr
    image: skiibum/testpod:qos
    imagePullPolicy: IfNotPresent
    command: ["tail", "-f", "/dev/null"]
    resources:
      requests:
        cpu: "250m"
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# k get pod bpod3-127.0.0.1 -ojson | jq .spec.containers[0].resources
{
  "requests": {
    "cpu": "250m"
  }
}
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# k get pod bpod3-127.0.0.1 -ojson | jq .status.containerStatuses[0].resourcesAllocated
null
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# k get pod bpod3-127.0.0.1 -ojson | jq .status.containerStatuses[0].resources
null
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash#
```

  - Feature gate enabled, kubeletonly local cluster.
```bash
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# cat /var/run/kubernetes/static-pods/3Bpod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: bpod3
spec:
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 2
  containers:
  - name: ctr
    image: skiibum/testpod:qos
    imagePullPolicy: IfNotPresent
    command: ["tail", "-f", "/dev/null"]
    resources:
      requests:
        cpu: "250m"
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# 
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# crictl ps
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID              POD
d06cf4835bc0a       254425ccdec9a       3 minutes ago       Running             ctr                 0                   d58670c526414       bpod3-127.0.0.1
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# 
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# cat /sys/fs/cgroup/cpu/kubepods/burstable/pod07f9b33c5aa6780ad184c1db155963fb/d06cf4835bc0af6f54d13379aa1e2453e72387e3ace0cb2f973673915c258fc4/cpu.shares 
256
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# 
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# cat /var/run/kubernetes/static-pods/3Bpod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: bpod3
spec:
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 2
  containers:
  - name: ctr
    image: skiibum/testpod:qos
    imagePullPolicy: IfNotPresent
    command: ["tail", "-f", "/dev/null"]
    resources:
      requests:
        cpu: "125m"
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# crictl ps
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID              POD
7890e9f519f0e       254425ccdec9a       15 seconds ago      Running             ctr                 0                   09250f693c922       bpod3-127.0.0.1
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# cat /sys/fs/cgroup/cpu/kubepods/burstable/podd8dd8ced76f957ad395b2e579d3d3e2d/7890e9f519f0ec097c55dffd12eabb7696f8d620039561840d8bea972499b82d/cpu.shares
128
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash#
```

  - Feature gate disabled, kubeletonly local cluster.
```bash
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# 
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# cat /var/run/kubernetes/static-pods/3Bpod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: bpod3
spec:
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 2
  containers:
  - name: ctr
    image: skiibum/testpod:qos
    imagePullPolicy: IfNotPresent
    command: ["tail", "-f", "/dev/null"]
    resources:
      requests:
        cpu: "200m"
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# crictl ps
CONTAINER           IMAGE               CREATED              STATE               NAME                ATTEMPT             POD ID              POD
8f7a5e9000ed8       254425ccdec9a       About a minute ago   Running             ctr                 0                   0e20db4eb61f8       bpod3-127.0.0.1
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# cat /sys/fs/cgroup/cpu/kubepods/burstable/pod0df8ebda9e77aef3325dcfe6985da39b/8f7a5e9000ed868b72a7c4dae93e82294007837b2d86856ca238a4e2de8d6f2c/cpu.shares 
204
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# 
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# cat /var/run/kubernetes/static-pods/3Bpod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: bpod3
spec:
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 2
  containers:
  - name: ctr
    image: skiibum/testpod:qos
    imagePullPolicy: IfNotPresent
    command: ["tail", "-f", "/dev/null"]
    resources:
      requests:
        cpu: "400m"
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# crictl ps
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID              POD
ebf36203349d4       254425ccdec9a       30 seconds ago      Running             ctr                 0                   7aa3c12e76e05       bpod3-127.0.0.1
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# cat /sys/fs/cgroup/cpu/kubepods/burstable/pod2d1ad7bae07eb09ebb126229f381519d/ebf36203349d467d5cab2f22d4110b1cfad4aa4a9988a7a03a6e057c994fac44/cpu.shares 
409
root@vbuild:~/go/src/k8s.io/kubernetes-kubeletonly-crash# 
```

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 3]
```diff
@@ -940,8 +960,7 @@ func (m *kubeGenericRuntimeManager) computePodActions(ctx context.Context, pod *
 			// If the container failed the startup probe, we should kill it.
 			message = fmt.Sprintf("Container %s failed startup probe", container.Name)
 			reason = reasonStartupProbe
-		} else if utilfeature.DefaultFeatureGate.Enabled(features.InPlacePodVerticalScaling) &&
-			!m.computePodResizeAction(pod, idx, containerStatus, &changes) {
+		} else if isInPlacePodVerticalScalingAllowed(pod) && !m.computePodResizeAction(pod, idx, containerStatus, &changes) {
```
Comment (liggitt) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:963]: also use `isInPlacePodVerticalScalingAllowed` on line 949

**Comment by liggitt** [comment]
no further comments from my side, needs a lgtm/approve from https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/OWNERS

**Comment by bobbypage** [comment]
/hold

I was able to repro the panic in a standalone node e2e, I would like to verify that this patch fixes the change in my local test, before we merge.

**Comment by bobbypage** [comment]
Tested locally with the patch applied and can confirm the test passes now (see https://github.com/kubernetes/kubernetes/issues/116262#issuecomment-1469062127).

/unhold
