### PR TITLE
bugfix: nodeport quota check failure result into failing to create a clusterip service

### LINKED ISSUE #97437: Creation of cluterip fails due to quota on nodeports
Having 2 services of type nodeports I do set a hard quota limiting services.nodeports to 0.
Then I'm failing to create clusterip service with error:
```
$ k create svc clusterip cip --tcp=1234:1234
Error from server (Forbidden): services "cip" is forbidden: exceeded quota: default-quota, requested: services.nodeports=0, used: services.nodeports=2, limited: services.nodeports=0
```
Do I understand right that the creation of clusterip service requires 0 services of nodeports, therefore in total, taking in account 2 already existed, I exceed the quota?
If so why clusterip requires 0 services of nodeports ?

Is it seems as a bug or there is some rationale behind?

**Environment**:
all k8s versions, any env including minikube

### PR DESCRIPTION
**Pull request by pacoxu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: default
spec:
  hard:
    services.nodeports: "0"
```
When quota is like above and there are already two nodeports service created before the quota creation.

```
$ k create svc clusterip cip --tcp=1234:1234
Error from server (Forbidden): services "cip" is forbidden: exceeded quota: default-quota, requested: services.nodeports=0, used: services.nodeports=2, limited: services.nodeports=0
```
This PR tries to fix this. As the created service is clusterip, it can be created as no quota is set for services, only for nodeport.

**Which issue(s) this PR fixes**:
Fixes #97437 and #73628 

**Special notes for your reviewer**:
Cherrypicks from #97319 to fix NodePort and LB problem as well. Thanks @uablrek for that commit.

To summarize the expectations:
live = current
NP = nodeport
LB = load balancer

Service hard quota | NP hard quota | LB hard quota | live Services count | live NP count | live LB count | create Service (ClusterIP) | create NP | create LB with NP | create LB with AllocateLBNodePorts=false 
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
None | 0 | None | 2 | 2 | 0 | **should success but failed** | expected fail | expected failed  |  **should success but failed**
2 | None | None | 3 | 0 | 0 | expected fail | expected fail | expected fail | expected fail 
4 | 2 | None | 4 | 2 | 0 | expected fail | expected fail | expected fail | expected fail 
4 | 2 | None | 5 | 1 | 0 | expected fail | expected fail | expected fail | expected fail 
4 | 2 | None | 3 | 2 | 0 | expected success | expected fail | expected fail |  **should success but failed**
4 | 2 | 1 | 3 | 2 | 1 | expected success | expected fail | expected fail | expected failed

Edited after https://github.com/kubernetes/kubernetes/pull/97451#issuecomment-750425082 comments. 

**Does this PR introduce a user-facing change?**:
```release-note
fix counting error in service/nodeport/loadbalancer quota check
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
None
```

### CODE REVIEW

**Comment by pacoxu** [comment]
/sig network
as it is related with service creations.

**Comment by yliaog** [comment]
please see discussions in the issue #73628

**Comment by pacoxu** [comment]
thanks.  @yliaog 

However, #97319 focus on LB and NodePorts, besides, #97437 focus on nodeports quota check results in that clusterip service cannot be created.
What @b10s  mentioned in #97437 is still a problem.
@uablrek  @thockin would you look into #97437 as well ? 

I think they are different indeed.

**Comment by uablrek** [comment]
> @uablrek @thockin would you look into #97437 as well ?

I focused on the problem introduced by Spec.AllocateLoadBalancerNodePorts which is a different problem. I realized that was not the problem described in #73628 but I did not have time for both at the time.

#97437 is clearly a duplicate of #73628 both will be fixed by this PR.

**Comment by aojea** [comment]
> > @uablrek @thockin would you look into #97437 as well ?
> 
> I focused on the problem introduced by Spec.AllocateLoadBalancerNodePorts which is a different problem. I realized that was not the problem described in #73628 but I did not have time for both at the time.
> 
> #97437 is clearly a duplicate of #73628 both will be fixed by this PR.

However, Services LoadBalancer quota depends on NodePort quota (at least meanwhile Lars  Spec.AllocateLoadBalancerNodePorts feature gate is disabled)
I think that the first line @pacoxu , Quotas (Services None, NodePort 0, LoadBalancer None) the expectaction is that LoadBalancer fails on create

**Comment by pacoxu** [comment]
> I think that the first line @pacoxu , Quotas (Services None, NodePort 0, LoadBalancer None) the expectaction is that LoadBalancer fails on create

I edited the table. 

@uablrek  I didn't realize that LB would include NodePort at the time. There is some overlap. We can fix it in one pr or separate PRs. Either is ok.

**Comment by uablrek** [comment]
@pacoxu Feel free to include my PR in this one if you like. My PR is very small in the code and the tests should not interfere.

But from a review point-of-view it might be better to have separate PRs.

I let you decide.

**Comment by pacoxu** [comment]
@uablrek  There's no conflicts and I cherry-picked your commits to this PR.

Hence, this PR can fix both issues that are mentioned in #97437 and  #73628

File: pkg/quota/v1/evaluator/core/services.go [hunk 1]
```diff
@@ -120,22 +120,36 @@ func (p *serviceEvaluator) Usage(item runtime.Object) (corev1.ResourceList, erro
...
 		// node port services need to count node ports
 		value := resource.NewQuantity(int64(ports), resource.DecimalSI)
 		result[corev1.ResourceServicesNodePorts] = *value
 	case corev1.ServiceTypeLoadBalancer:
-		// load balancer services need to count node ports and load balancers
-		value := resource.NewQuantity(int64(ports), resource.DecimalSI)
-		result[corev1.ResourceServicesNodePorts] = *value
+		// load balancer services need to count node ports. If creation of node ports
+		// is suspressed only ports with explicit NodePort values are counted.
+		if svc.Spec.AllocateLoadBalancerNodePorts == nil || *svc.Spec.AllocateLoadBalancerNodePorts == true {
```
Comment (aojea) [inline pkg/quota/v1/evaluator/core/services.go:132]: should we check for the featuregate?
` if utilfeature.DefaultFeatureGate.Enabled(features.ServiceLBNodePortControl) {`

Comment (pacoxu) [reply pkg/quota/v1/evaluator/core/services.go:132]: @aojea ,  if the feature gate is enabled, the `AllocateLoadBalancerNodePorts` must be not nil
If not enabled, we can check whether it is nil before checking it's true or false.

I think both are OK to me. 

However, checking the feature gate would be friendly to code reading. So I would like to check feature gate as you suggested.


```
		if feature.DefaultFeatureGate.Enabled(features.ServiceLBNodePortControl) &&
			*svc.Spec.AllocateLoadBalancerNodePorts == false {
			result[corev1.ResourceServicesNodePorts] = *portsWithNodePorts(svc)
		} else {
			value := resource.NewQuantity(int64(ports), resource.DecimalSI)
			result[corev1.ResourceServicesNodePorts] = *value
		}
```

or

```
		if svc.Spec.AllocateLoadBalancerNodePorts == nil || *svc.Spec.AllocateLoadBalancerNodePorts == true {
			value := resource.NewQuantity(int64(ports), resource.DecimalSI)
			result[corev1.ResourceServicesNodePorts] = *value
		} else {
			result[corev1.ResourceServicesNodePorts] = *portsWithNodePorts(svc)
		}
```

Comment (aojea) [reply pkg/quota/v1/evaluator/core/services.go]: the question is for someone like @liggitt ^^^

**Comment by aojea** [comment]
/lgtm
Adding Tim for the sig-network bits in addition to @yliaog 
/assign @thockin

**Comment by yliaog** [comment]
please add e2e test case in https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/resource_quota.go to demonstrate the fix works as described in the table in this pr.

File: pkg/quota/v1/evaluator/core/services.go [hunk 2]
```diff
@@ -127,14 +127,29 @@ func (p *serviceEvaluator) Usage(item runtime.Object) (corev1.ResourceList, erro
 		value := resource.NewQuantity(int64(ports), resource.DecimalSI)
 		result[corev1.ResourceServicesNodePorts] = *value
 	case corev1.ServiceTypeLoadBalancer:
-		// load balancer services need to count node ports and load balancers
-		value := resource.NewQuantity(int64(ports), resource.DecimalSI)
-		result[corev1.ResourceServicesNodePorts] = *value
+		// load balancer services need to count node ports. If creation of node ports
+		// is suspressed only ports with explicit NodePort values are counted.
```
Comment (thockin) [inline pkg/quota/v1/evaluator/core/services.go:133]: We should add to this - nodeports won't be allocated yet, so we can't simply count the actual values.  We need to look at the intent.

File: pkg/quota/v1/evaluator/core/services_test.go [hunk 3]
```diff
@@ -67,6 +72,7 @@ func TestServiceEvaluatorUsage(t *testing.T) {
 				corev1.ResourceServices:              resource.MustParse("1"),
 				generic.ObjectCountQuotaResourceNameFor(schema.GroupResource{Resource: "services"}): resource.MustParse("1"),
 			},
+			serviceLBNodePortControlEnabled: false,
 		},
 		"loadbalancer_ports": {
```
Comment (thockin) [inline pkg/quota/v1/evaluator/core/services_test.go:77]: Can you dup this case into a single port case and 2-port case?

File: pkg/quota/v1/evaluator/core/services_test.go [hunk 4]
```diff
@@ -93,11 +100,10 @@ func TestServiceEvaluatorUsage(t *testing.T) {
 				},
 			},
 			usage: corev1.ResourceList{
-				corev1.ResourceServices:              resource.MustParse("1"),
-				corev1.ResourceServicesNodePorts:     resource.MustParse("0"),
-				corev1.ResourceServicesLoadBalancers: resource.MustParse("0"),
+				corev1.ResourceServices: resource.MustParse("1"),
 				generic.ObjectCountQuotaResourceNameFor(schema.GroupResource{Resource: "services"}): resource.MustParse("1"),
 			},
+			serviceLBNodePortControlEnabled: false,
```
Comment (thockin) [inline pkg/quota/v1/evaluator/core/services_test.go:106]: you probably can leave this out when false

File: pkg/quota/v1/evaluator/core/services_test.go [hunk 5]
```diff
@@ -85,6 +91,7 @@ func TestServiceEvaluatorUsage(t *testing.T) {
 				corev1.ResourceServices:              resource.MustParse("1"),
 				generic.ObjectCountQuotaResourceNameFor(schema.GroupResource{Resource: "services"}): resource.MustParse("1"),
 			},
+			serviceLBNodePortControlEnabled: false,
 		},
 		"clusterip": {
```
Comment (thockin) [inline pkg/quota/v1/evaluator/core/services_test.go:96]: Can you dup this to a case with 2 ports, for completenesss

**Review by thockin — COMMENTED** [review]
Overall looks good - small comments

**Comment by pacoxu** [comment]
@thockin thanks for your comments and I fixed them.

@yliaog I add testcase in e2e test. 

However, the  feature gate is alpha so it is default disabled. 

TODO in 1.22+ after the feature gate is default true. The test case would like below. 
```
		// ServiceLBNodePortControl is alpha feature gate in 1.20, so add testcases later after it's default enabled
		ginkgo.By("Creating a LoadBalancer Service without NodePort")
		lbWithoutNodeports := newTestServiceForQuota("test-service-lb", v1.ServiceTypeLoadBalancer, true)
		lbWithoutNodeports, err = f.ClientSet.CoreV1().Services(f.Namespace.Name).Create(context.TODO(), lbWithoutNodeports, metav1.CreateOptions{})
		framework.ExpectNoError(err)
		err = f.ClientSet.CoreV1().Services(f.Namespace.Name).Delete(context.TODO(), lbWithoutNodeports.Name, metav1.DeleteOptions{})
		framework.ExpectNoError(err)
```

File: test/e2e/apimachinery/resource_quota.go [hunk 6]
```diff
@@ -100,23 +101,36 @@ var _ = SIGDescribe("ResourceQuota", func() {
...
+		framework.ExpectNoError(err)
+
+		ginkgo.By("Not allowing a LoadBalancer Service with NodePort to be created that exceeds remaining quota")
+		loadbalancer := newTestServiceForQuota("test-service-lb", v1.ServiceTypeLoadBalancer, false)
+		_, err = f.ClientSet.CoreV1().Services(f.Namespace.Name).Create(context.TODO(), loadbalancer, metav1.CreateOptions{})
+		framework.ExpectError(err)
+
 		ginkgo.By("Ensuring resource quota status captures service creation")
 		usedResources = v1.ResourceList{}
-		usedResources[v1.ResourceQuotas] = resource.MustParse(strconv.Itoa(c + 1))
```
Comment (yliaog) [inline test/e2e/apimachinery/resource_quota.go:109]: why removing the above?

File: test/e2e/apimachinery/resource_quota.go [hunk 7]
```diff
@@ -100,23 +101,36 @@ var _ = SIGDescribe("ResourceQuota", func() {
...
+		ginkgo.By("Creating a NodePort Service")
+		nodeport := newTestServiceForQuota("test-service-np", v1.ServiceTypeNodePort, false)
+		nodeport, err = f.ClientSet.CoreV1().Services(f.Namespace.Name).Create(context.TODO(), nodeport, metav1.CreateOptions{})
+		framework.ExpectNoError(err)
+
+		ginkgo.By("Not allowing a LoadBalancer Service with NodePort to be created that exceeds remaining quota")
+		loadbalancer := newTestServiceForQuota("test-service-lb", v1.ServiceTypeLoadBalancer, false)
+		_, err = f.ClientSet.CoreV1().Services(f.Namespace.Name).Create(context.TODO(), loadbalancer, metav1.CreateOptions{})
+		framework.ExpectError(err)
+
```
Comment (yliaog) [inline test/e2e/apimachinery/resource_quota.go:117]: please add the test case for the scenario described in the PR description:

"when nodeport quota usage exceeds the quota limit, cluster ip service should still be allowed if cluster ip service quota still has some left."

**Review by thockin — COMMENTED** [review]
super nits, will approve and lgtm when last touches are done

/approve

File: pkg/quota/v1/evaluator/core/services_test.go [hunk 8]
```diff
@@ -111,9 +135,28 @@ func TestServiceEvaluatorUsage(t *testing.T) {
...
 			usage: corev1.ResourceList{
-				corev1.ResourceServices:              resource.MustParse("1"),
-				corev1.ResourceServicesNodePorts:     resource.MustParse("1"),
-				corev1.ResourceServicesLoadBalancers: resource.MustParse("0"),
+				corev1.ResourceServices:          resource.MustParse("1"),
+				corev1.ResourceServicesNodePorts: resource.MustParse("1"),
+				generic.ObjectCountQuotaResourceNameFor(schema.GroupResource{Resource: "services"}): resource.MustParse("1"),
+			},
+		},
+		"nodeports_2_ports": {
```
[the remark this answers is not in the document]
Comment (pacoxu) [reply pkg/quota/v1/evaluator/core/services_test.go:143]: removed.

**Comment by liggitt** [comment]
this is ... curious ...

quota admission is supposed to ignore resources that are not being increased by the item being created/updated... if the value of the nodeport resource is computed to be zero for the service, it should have been allowed

/hold while I investigate at the quota logic layer

**Comment by liggitt** [comment]
> quota admission is supposed to ignore resources that are not being increased by the item being created/updated... if the value of the nodeport resource is computed to be zero for the service, it should have been allowed

Yeah, quota evaluation did not correctly handle an evaluator returning a resource list that mixed zero and non-zero usage. 

This fix would resolve the "new object not using quota'ed resource X is blocked by excess usage of resource X by existing objects":

```diff
diff --git a/staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go b/staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go
index 622c7bcfd50..fa6ec8ae781 100644
--- a/staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go
+++ b/staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go
@@ -510,7 +510,14 @@ func CheckRequest(quotas []corev1.ResourceQuota, a admission.Attributes, evaluat
 		}
 	}
 
-	if quota.IsZero(deltaUsage) {
+	// ignore items in deltaUsage with zero usage
+	for k, v := range deltaUsage {
+		if v.IsZero() {
+			delete(deltaUsage, k)
+		}
+	}
+	// if there is no remaining non-zero usage, short-circuit and return
+	if len(deltaUsage) == 0 {
 		return quotas, nil
 	}
```

We need an accompanying unit test that verifies this case (evaluator returns a mix of zero and non-zero usage, and zero usage is ignored).

The changes in this PR look reasonable as well (and resolve a separate bug with the service evaluator not computing node port usage correctly), but I think we should include both fixes.

**Comment by pacoxu** [comment]
@liggitt fix both per your comments and add simple UT for remove zeros.

File: pkg/quota/v1/evaluator/core/services.go [hunk 9]
```diff
@@ -120,22 +122,39 @@ func (p *serviceEvaluator) Usage(item runtime.Object) (corev1.ResourceList, erro
...
 	case corev1.ServiceTypeLoadBalancer:
-		// load balancer services need to count node ports and load balancers
-		value := resource.NewQuantity(int64(ports), resource.DecimalSI)
-		result[corev1.ResourceServicesNodePorts] = *value
+		// load balancer services need to count node ports. If creation of node ports
+		// is suppressed only ports with explicit NodePort values are counted.
+		// nodeports won't be allocated yet, so we can't simply count the actual values.
+		// We need to look at the intent.
+		if feature.DefaultFeatureGate.Enabled(features.ServiceLBNodePortControl) &&
+			*svc.Spec.AllocateLoadBalancerNodePorts == false {
```
Comment (liggitt) [inline pkg/quota/v1/evaluator/core/services.go:137]: make sure `svc.Spec.AllocateLoadBalancerNodePorts` is not nil here. This code also runs in the controller manager, so it is possible for the feature gate to be enabled in the controller manager and not in the API server

File: pkg/quota/v1/evaluator/core/services.go [hunk 10]
```diff
@@ -120,22 +122,39 @@ func (p *serviceEvaluator) Usage(item runtime.Object) (corev1.ResourceList, erro
 	// default service usage
 	result[serviceObjectCountName] = *(resource.NewQuantity(1, resource.DecimalSI))
 	result[corev1.ResourceServices] = *(resource.NewQuantity(1, resource.DecimalSI))
-	result[corev1.ResourceServicesLoadBalancers] = resource.Quantity{Format: resource.DecimalSI}
-	result[corev1.ResourceServicesNodePorts] = resource.Quantity{Format: resource.DecimalSI}
```
Comment (liggitt) [inline pkg/quota/v1/evaluator/core/services.go:124]: with the zero-amount fix in the quota component, I think these lines should be restored

File: pkg/quota/v1/evaluator/core/services.go [hunk 11]
```diff
@@ -120,22 +122,39 @@ func (p *serviceEvaluator) Usage(item runtime.Object) (corev1.ResourceList, erro
...
+	// check nodeport and load balancer only if the runtime svc is one of them.
 	switch svc.Spec.Type {
 	case corev1.ServiceTypeNodePort:
 		// node port services need to count node ports
 		value := resource.NewQuantity(int64(ports), resource.DecimalSI)
 		result[corev1.ResourceServicesNodePorts] = *value
 	case corev1.ServiceTypeLoadBalancer:
```
Comment (liggitt) [inline pkg/quota/v1/evaluator/core/services.go:131]: do we also need to count usage by HealthCheckNodePort?

Comment (pacoxu) [reply pkg/quota/v1/evaluator/core/services.go:131]: I'm not counting this yet. 
Should add 1 when `type is set to LoadBalancer and externalTrafficPolicy is set to Local`

Comment (aojea) [reply pkg/quota/v1/evaluator/core/services.go:133]: IMHO `HealthCheckNodePort` != `NodePort` , and as a user it may be confusing to have to consider them equal for quotas, but let's ask @thockin for his opinion

Comment (pacoxu) [reply pkg/quota/v1/evaluator/core/services.go:133]: It seems that HealthCheckNodePort is not taken into account in previous implementations. I'm not sure if we should count like below. 
```
diff --git a/pkg/quota/v1/evaluator/core/services.go b/pkg/quota/v1/evaluator/core/services.go
index ae5504a6eca..45b07526b59 100644
--- a/pkg/quota/v1/evaluator/core/services.go
+++ b/pkg/quota/v1/evaluator/core/services.go
func portsWithNodePorts(svc *corev1.Service) *resource.Quantity {
	count := 0
+	if svc.Spec.externalTrafficPolicy == api.ServiceExternalTrafficPolicyTypeLocal {
+		count++
+	}
	for _, p := range svc.Spec.Ports {
		if p.NodePort != 0 {
			count++
		}
	}
	return resource.NewQuantity(int64(count), resource.DecimalSI)
}

```

Comment (liggitt) [reply pkg/quota/v1/evaluator/core/services.go:133]: We probably want to backport this fix (at least the zero-value portion of it). Let's get this in as-is, then follow-up with including the health check node port in quota in a separate PR

File: staging/src/k8s.io/apiserver/pkg/quota/v1/resources.go [hunk 12]
```diff
@@ -215,15 +215,15 @@ func Difference(a []corev1.ResourceName, b []corev1.ResourceName) []corev1.Resou
 	return result
 }
 
-// IsZero returns true if each key maps to the quantity value 0
-func IsZero(a corev1.ResourceList) bool {
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/quota/v1/resources.go:219]: add the new RemoveZeros method, but leave this method alone (it could be used by other callers)

File: staging/src/k8s.io/apiserver/pkg/quota/v1/resources_test.go [hunk 13]
```diff
@@ -256,32 +256,45 @@ func TestContainsPrefix(t *testing.T) {
 	}
 }
 
-func TestIsZero(t *testing.T) {
+func TestRemoveZeros(t *testing.T) {
```
Comment (liggitt) [inline staging/src/k8s.io/apiserver/pkg/quota/v1/resources_test.go:259]: add TestRemoveZeros but leave TestIsZero as-is

**Comment by pacoxu** [comment]
Done. Restore IsZero and TestIsZero now. @liggitt

File: pkg/quota/v1/evaluator/core/services.go (hunk 11 above)
Comment (pacoxu) [reply pkg/quota/v1/evaluator/core/services.go:133]: OK, I will test HealthCheckNodePort behavior tomorrow. Nice catch.

File: pkg/quota/v1/evaluator/core/services.go [hunk 14]
```diff
@@ -122,20 +124,40 @@ func (p *serviceEvaluator) Usage(item runtime.Object) (corev1.ResourceList, erro
 	result[corev1.ResourceServices] = *(resource.NewQuantity(1, resource.DecimalSI))
 	result[corev1.ResourceServicesLoadBalancers] = resource.Quantity{Format: resource.DecimalSI}
 	result[corev1.ResourceServicesNodePorts] = resource.Quantity{Format: resource.DecimalSI}
+	// check nodeport and load balancer only if the runtime svc is one of them.
```
Comment (liggitt) [inline pkg/quota/v1/evaluator/core/services.go:127]: Drop this comment, since we're still setting both to zero normally. Also, go ahead and squash the commits so we don't remove and then re-add these lines in consecutive commits

**Comment by yliaog** [comment]
it would change nodeport quota behavior to add healthcheck nodeport, if needed, it should be added in a separate quota.

**Comment by liggitt** [comment]
> if needed, it should be added in a separate quota

I'm not sure that's correct... if the point of the quota is to limit a user's ability to consume node ports, then shouldn't the health port count?

**Comment by aojea** [comment]
> > if needed, it should be added in a separate quota
> 
> I'm not sure that's correct... if the point of the quota is to limit a user's ability to consume node ports, then shouldn't the health port count?

I think that it will be correct if the goal is to preserve the NodePort range and the intent is to limit the ports that a user can get from that range, i.e. 30000 - 32000.
However, I think that the goal is to control the number of `NodePorts` services used to expose applications ... `HealthCheckNodePort` are allocated automatically for `LoadBalancer` services if `ServiceExternalTrafficPolicy` = `Local`, maybe you can limit it with the LoadBalancer quota ?

File: pkg/quota/v1/evaluator/core/services.go (hunk 14 above)
Comment (pacoxu) [reply pkg/quota/v1/evaluator/core/services.go]: squashed.
@liggitt

Comment (pacoxu) [reply pkg/quota/v1/evaluator/core/services.go]: sorry for my careless。

**Comment by pacoxu** [comment]
> We probably want to backport this fix (at least the zero-value portion of it). Let's get this in as-is, then follow-up with including the health check node port in quota in a separate PR

need I cherry pick it to 1.20 or other old version？ @liggitt

**Comment by liggitt** [comment]
I would pick the zero portion of it to 1.17-1.20
