### PR TITLE
MESOS: fix ports mapping in case of discontinuous port ranges in mesos offer

### LINKED ISSUE #614: port mapping issue in k8sm scheduler
@jdef 
when there are multiple discontinuous port ranges in the mesos offer, the wildcard hostport mapping code doesn't always assigns a offer port to all the hostPort=0 in pod spec.

At https://github.com/kubernetes/kubernetes/blob/17defc7383914c1f52d30ab4a46e0992cbfc2bae/contrib/mesos/pkg/scheduler/podtask/port_mapping.go#L110, it is updating the copy of wildports array and at https://github.com/kubernetes/kubernetes/blob/17defc7383914c1f52d30ab4a46e0992cbfc2bae/contrib/mesos/pkg/scheduler/podtask/port_mapping.go#L103, the check fails in next iteration of offer port range always.

for example, when the offer has following port resource ranges (31005,31005), (31011,32000), and the pod spec has 2 container ports (and hostPort=0), and wildportmapping is on (by default),  only the first port gets a offer port in the mapping.

### PR DESCRIPTION
**Pull request by ravilr**
fixes https://github.com/mesosphere/kubernetes-mesos/issues/614
@jdef @sttts

### CODE REVIEW

**Comment by sttts** [comment]
@ravilr thanks for the PR. Can you describe in your commit msg what the actual bug was?

File: contrib/mesos/pkg/scheduler/podtask/port_mapping.go [hunk 1]
```diff
@@ -99,16 +99,16 @@ func wildcardHostPortMapping(t *T, offer *mesos.Offer) ([]HostPortMapping, error
 	remaining := len(wildports)
 	foreachRange(offer, "ports", func(bp, ep uint64) {
 		log.V(3).Infof("Searching for wildcard port in range {%d:%d}", bp, ep)
-		for _, entry := range wildports {
-			if entry.OfferPort != 0 {
+		for i := range wildports {
+			if wildports[i].OfferPort != 0 {
```
Comment (jdef) [inline contrib/mesos/pkg/scheduler/podtask/port_mapping.go]: I see the loop has been changed to avoid copying `wildports[i]` into `entry`. I'm not sure how/why this fixes the problem that you've identified because in the code (a) `entry` is copied into `mapping` via `append`, and; (b) we don't reference `wildports` after the loop completes.

Comment (ravilr) [inline contrib/mesos/pkg/scheduler/podtask/port_mapping.go]: see https://github.com/mesosphere/kubernetes-mesos/issues/614 and the new unit test case.
in https://github.com/kubernetes/kubernetes/blob/17defc7383914c1f52d30ab4a46e0992cbfc2bae/contrib/mesos/pkg/scheduler/podtask/port_mapping.go#L110 , the copy of the map value is being updated and in above line, it is expecting to hold that value in next outer loop iteration.

Comment (jdef) [inline contrib/mesos/pkg/scheduler/podtask/port_mapping.go]: I forgot to review foreachRange. That's why this change is important. The
change must be made to `wildports`, not a copy `entry`.

**Comment by jdef** [comment]
This is a really subtle bug. Thanks for tackling this @ravilr

**Comment by ravilr** [comment]
@sttts updated the commit message. PTAL.

**Comment by sttts** [comment]
@ravilr some nit: please wrap the lines according to http://chris.beams.io/posts/git-commit/

The content itself is good now.

**Comment by ravilr** [comment]
@sttts PTAL
