### PR TITLE
Fix error override when saveVolumeData occurs error

### LINKED ISSUE #80450: Error msg override when saveVolumeData fails
**What happened**:

Error msg override when saveVolumeData fails.
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_plugin.go#L443
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_plugin.go#L688

**What you expected to happen**:

return the right error.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by cwdsuzhou**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Fix error override when saveVolumeData occurs error

**Which issue(s) this PR fixes**:

Fixes #80450 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/volume/csi/csi_plugin.go [hunk 1]
```diff
@@ -440,9 +440,9 @@ func (p *csiPlugin) NewMounter(
 
 	if err := saveVolumeData(dataDir, volDataFileName, volData); err != nil {
 		klog.Error(log("failed to save volume info data: %v", err))
-		if err := os.RemoveAll(dataDir); err != nil {
-			klog.Error(log("failed to remove dir after error [%s]: %v", dataDir, err))
-			return nil, err
```
Comment (jsafrane) [inline pkg/volume/csi/csi_plugin.go]: Good catch, however, would it make sense to return `err` here (and below in NewBlockVolumeMapper)? Because that's why setup failed.

File: pkg/volume/csi/csi_plugin.go [hunk 2]
```diff
@@ -440,9 +440,9 @@ func (p *csiPlugin) NewMounter(
...
+		if removeErr := os.RemoveAll(dataDir); removeErr != nil {
+			klog.Error(log("failed to remove dir after error [%s]: %v", dataDir, removeErr))
+			return nil, removeErr
```
Comment (jsafrane) [inline pkg/volume/csi/csi_plugin.go]: Good catch, however, would it make sense to return err here (and below in NewBlockVolumeMapper)? Because that's why setup failed.

Comment (cwdsuzhou) [reply pkg/volume/csi/csi_plugin.go]: Thanks, maybe return `err` is better. 

I think we should return why it failed initially. I have resent the  PR, PTAL!

Comment (cwdsuzhou) [reply pkg/volume/csi/csi_plugin.go]: This pr would work when `saveVolumeData` failed but `RemoveAll` succeeded. Then we would return  `nil, nil`

This may cause panic since some of the callers do not care if the first returned value is `nil` or not, for example:

https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go:L1027

https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go:L590

**Comment by cwdsuzhou** [comment]
Thanks @jsafrane 

Should we cherry pick it to other release branches ?

**Comment by jsafrane** [comment]
No, this is IMO not a critical error.
