### PR TITLE
DRA: sharing claim sequentially test

### LINKED ISSUE #133209: Add DRA "supports sharing a claim sequentially" integration test
### Which jobs are flaking?

Triage board didn't catch this because it was down for a while, here's an example:

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/132942/pull-kubernetes-e2e-gce/1948461471599955968

```
[FAILED] schedule pod: Timed out after 80.001s.
expected pod to be pod is scheduled, got instead:
    <*v1.Pod | 0xc0014d2908>: 
```

### Which tests are flaking?

The "supports sharing a claim sequentially" test turned into a stress test at some point when we removed the limit of concurrent users of a claim. Now it depends on scheduling a lot of pods, which is obviously problematic due to unpredictable performance on larger jobs. It might have to be disabled or modified to not use that many pods - not a big loss in terms of coverage.

### Since when has it been flaking?

Probably since graduation to GA caused it to run in jobs like pull-kubernetes-e2e-gce.

### Testgrid link

_No response_

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig scheduling
/wg device-management

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

This used to be an E2E test, but it turned out to be too slow and unreliable and therefore got removed. As an integration test we have a bit better control over the environment, so it should be possible to avoid the same flakes.
    
Some of the slowness comes from pods entering backoff. Maybe this is an opportunity for future improvements.
    
To support this tests, the ResourceClaim controller is needed. The framework can start it on demand now, similar to how the scheduler was handled already.

#### Which issue(s) this PR is related to:

Fixes: https://github.com/kubernetes/kubernetes/issues/133209

#### Special notes for your reviewer:

Depends on https://github.com/kubernetes/kubernetes/pull/135664.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

File: test/e2e/dra/utils/deploy.go [hunk 1]
```diff
@@ -456,6 +460,10 @@ func (d *Driver) SetUp(tCtx ktesting.TContext, kubeletRootDir string, nodes *Nod
 		}
 	}
 
+	if !d.WithRealNodes {
+		return
```
Comment (bart0sh) [inline test/e2e/dra/utils/deploy.go:467]: This code would benefit from the comment explaining why we're stopping exactly at this point.

Comment (pohly) [reply test/e2e/dra/utils/deploy.go:467]: Added.
