### PR TITLE
Use Semantic.DeepEqual to compare DaemonSet template on updates

### LINKED ISSUE #43218: kubectl apply for DaemonSet and Deployment have different behavior with RollingUpdate
**Kubernetes version** (use `kubectl version`):
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-beta.3+coreos.0", GitCommit:"7013c674183a8b4ee3b3dd846f108e3a5575f4af", GitTreeState:"clean", BuildDate:"2017-03-13T19:57:10Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.0-beta.3+coreos.0", GitCommit:"7013c674183a8b4ee3b3dd846f108e3a5575f4af", GitTreeState:"clean", BuildDate:"2017-03-13T19:57:10Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: DigitalOcean
- **OS** (e.g. from /etc/os-release): 
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):
```
uname -a
Linux k8s-master-fra10-01 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- **Install tools**:
```
cargo
```
- **Others**:

**What happened**:
when I do:
```
kubectl apply -f deployment.yaml
```
it will run rolling update ONLY if there is a change. In case I do:
```
kubectl apply -f daemonset.yaml
```
Each time I run it - it will execute rolling update, which is misleading. 

**What you expected to happen**:
I would like to have consistent behavior for Deployment and DaemonSet 

**How to reproduce it** (as minimally and precisely as possible):
Create any DaemonSet with following:
```
piVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: bind
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        service: bind
        commit: e311f982eb769835ca75d942bd2fd0d9890776fb
    spec:
      nodeSelector:
          nodetype: "hss"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: "service"
                  operator: "In"
                  values: ["bind"]
              topologyKey: "kubernetes.io/hostname"
              namespaces: []
      containers:
      - env:
        - name: SERVICE_53_IGNORE
          value: '"true"'
        - name: TZ
          value: US/Pacific
        image: bind
        name: named
        resources:
          limits:
            memory: "150Mi"
          requests:
            memory: "40Mi"
      restartPolicy: Always
```

### PR DESCRIPTION
**Pull request by janetkuo**
Switch to `Semantic.DeepEqual` when comparing templates on DaemonSet updates, since we can't distinguish between `null` and `[]` in protobuf. This avoids unnecessary DaemonSet pods restarts. 

I didn't touch `reflect.DeepEqual` used in controller because it's close to release date, and the DeepEqual in the controller doesn't cause serious issues (except for maybe causing more enqueues than needed). 

Fixes #43218 

@liggitt @kargakis @lukaszo @kubernetes/sig-apps-pr-reviews

### CODE REVIEW

**Comment by liggitt** [comment]
Needs a test case submitting an update with [] against an existing object with null and verifying the generation doesn't bump

**Comment by liggitt** [comment]
Have you tested what the controller does when the daemonset and pods are semantically equal, but reflect.DeepEqual returns false? Just want to make sure it doesn't go crazy

File: pkg/registry/extensions/daemonset/strategy.go [hunk 1]
```diff
@@ -87,12 +87,12 @@ func (daemonSetStrategy) PrepareForUpdate(ctx genericapirequest.Context, obj, ol
...
 	// TODO: Any changes to a part of the object that represents desired state (labels,
 	// annotations etc) should also increment the generation.
-	if !reflect.DeepEqual(oldDaemonSet.Spec.Template, newDaemonSet.Spec.Template) {
+	if !apiequality.Semantic.DeepEqual(oldDaemonSet.Spec.Template, newDaemonSet.Spec.Template) {
 		newDaemonSet.Spec.TemplateGeneration = oldDaemonSet.Spec.TemplateGeneration + 1
 		newDaemonSet.Generation = oldDaemonSet.Generation + 1
 		return
 	}
-	if !reflect.DeepEqual(oldDaemonSet.Spec, newDaemonSet.Spec) {
+	if !apiequality.Semantic.DeepEqual(oldDaemonSet.Spec, newDaemonSet.Spec) {
```
Comment (kargakis) [inline pkg/registry/extensions/daemonset/strategy.go]: Open a separate issue to replace reflect.DeepEqual in all of the other registries

**Comment by liggitt** [comment]
```
W0317 18:17:15.973] 2 BUILD files not up-to-date.
I0317 18:17:16.074] 
I0317 18:17:16.074] Run ./hack/update-bazel.sh
I0317 18:17:16.074] FAILED   hack/make-rules/../../hack/verify-bazel.sh	5s
```

**Comment by janetkuo** [comment]
> Have you tested what the controller does when the daemonset and pods are semantically equal, but reflect.DeepEqual returns false?

DaemonSet controller never compares DaemonSet template against pod specs directly. In controller, we only compare labels / selectors to see if it's updated and we need to enqueue or not. Old DaemonSet template is compared against new DaemonSet template in the API server (strategy.go), during DaemonSet updates.

**Comment by ethernetdan** [comment]
@k8s-bot bazel test this
@k8s-bot verify test this

**Comment by ethernetdan** [comment]
@k8s-bot bazel test this

**Comment by ethernetdan** [comment]
bazel build gave different results this time, running a third time
@k8s-bot bazel test this

**Comment by janetkuo** [comment]
Updated bazel

**Comment by janetkuo** [comment]
@k8s-bot verify test this

File: pkg/registry/extensions/daemonset/strategy.go (hunk 1 above)
Comment (janetkuo) [inline pkg/registry/extensions/daemonset/strategy.go]: Filed #43402

**Comment by janetkuo** [comment]
> Needs a test case submitting an update with [] against an existing object with null and verifying the generation doesn't bump

The tests are added in #43406

**Comment by janetkuo** [comment]
@k8s-bot unit test this

**Comment by ethernetdan** [comment]
@lavalamp or @smarterclayton could you PTAL at this release blocker?

File: pkg/registry/extensions/daemonset/strategy.go [hunk 2]
```diff
@@ -87,12 +87,12 @@ func (daemonSetStrategy) PrepareForUpdate(ctx genericapirequest.Context, obj, ol
 	//
 	// TODO: Any changes to a part of the object that represents desired state (labels,
 	// annotations etc) should also increment the generation.
-	if !reflect.DeepEqual(oldDaemonSet.Spec.Template, newDaemonSet.Spec.Template) {
+	if !apiequality.Semantic.DeepEqual(oldDaemonSet.Spec.Template, newDaemonSet.Spec.Template) {
```
Comment (lavalamp) [inline pkg/registry/extensions/daemonset/strategy.go]: I thought when we were talking about this, you had said that there was a difference where nil vs [] meant different things. Will this fail to trigger on certain updates that it actually should trigger on?

Comment (janetkuo) [inline pkg/registry/extensions/daemonset/strategy.go]: The meaning was removed #43271 and therefore we need this change

Comment (lavalamp) [inline pkg/registry/extensions/daemonset/strategy.go]: awesome, thanks!
