### PR TITLE
Fix missing pod name for kubectl attach

### LINKED ISSUE #77604: Pod name is missing in suggested cmd usage when executing `kubectl attach`
**What happened**:
The pod name is missing in suggested cmd usage when executing `kubectl attach`:
```
# kubectl attach deployment/testpod
Defaulting container name to master.
Use 'kubectl describe pod/ -n default' to see all of the containers in this pod.
```

**What you expected to happen**:
The suggested cmd usage should be a complete cmd like the one got from `kubectl exec`
```
# kubectl exec testpod-f7675d6bd-th27z date
Defaulting container name to master.
Use 'kubectl describe pod/testpod-f7675d6bd-th27z -n default' to see all of the containers in this pod.
Wed May  8 15:22:25 UTC 2019
```
**How to reproduce it (as minimally and precisely as possible)**:
Use `kubectl attach` to attach any pod/deployment/service, the PodName will be missing in the suggested cmd usage like above.

**Anything else we need to know?**:
It works fine for kubectl < v1.12

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.13.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tnqn**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
The pod name is missing in suggested cmd usage when executing `kubectl attach`:
```
# kubectl attach deployment/testpod
Defaulting container name to master.
Use 'kubectl describe pod/ -n default' to see all of the containers in this pod.
```

The PodName is empty in func Complete as the attached Pod isn't populated yet, causing suggested cmd usage imcomplete. 
This patch renders PodName after it is populated.

**Which issue(s) this PR fixes**:

Fixes #77604

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by dixudx — APPROVED** [review]
/lgtm

File: pkg/kubectl/cmd/attach/attach.go [hunk 1]
```diff
@@ -189,7 +189,7 @@ func (o *AttachOptions) Complete(f cmdutil.Factory, cmd *cobra.Command, args []s
 		fullCmdName = cmdParent.CommandPath()
 	}
 	if len(fullCmdName) > 0 && cmdutil.IsSiblingCommandExists(cmd, "describe") {
-		o.SuggestedCmdUsage = fmt.Sprintf("Use '%s describe pod/%s -n %s' to see all of the containers in this pod.", fullCmdName, o.PodName, o.Namespace)
+		o.SuggestedCmdUsage = fmt.Sprintf("Use '%s describe pod/%%s -n %s' to see all of the containers in this pod.", fullCmdName, o.Namespace)
```
Comment (liggitt) [inline pkg/kubectl/cmd/attach/attach.go]: using SuggestedCmdUsage as a format string means that if fullCmdName or o.Namespace contain `%` characters, the output will be malformed

**Review by liggitt — COMMENTED** [review]
one comment on placing unknown content into a format string.

also, the same issue exists for exec, can we fix both commands in this PR?

File: pkg/kubectl/cmd/attach/attach.go (hunk 1 above)
Comment (tnqn) [reply pkg/kubectl/cmd/attach/attach.go]: Thanks for pointing this out. I checked Namespace is only allowed to be `[a-z0-9]([-a-z0-9]*[a-z0-9])?`, but can't be sure that fullCmdName won't contain `%`, it should be kubelet for most cases though. 
To avoid potential problem, I move the suggested usage formatting to where it could be done completely. The issue in exec is also addressed.
PTAL. Thanks!

**Comment by liggitt** [comment]
thanks

/lgtm
/approve
