### PR TITLE
Fix a bug that StatefulSet applies the revision incorrectly

### LINKED ISSUE #78420: The env of statefulset's container is incorrectly upgrade when deleting a pod and scaling the statefulset simultaneously
**What happened**:
After deleting a pod and scaling up the statefulset  with different valid envs in the same container simultaneously, then the output events of executing the command `kubectl describe sts <statefulset>` is below:
```
  Warning  FailedCreate      15s (x16 over 73s)  statefulset-controller  create Pod test-0 in StatefulSet test failed error: Pod "test-0" is invalid: spec.containers[0].env[0].valueFrom: Invalid value: "": may not be specified when `value` is not empty
``` 

**What you expected to happen**:
update successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a statefulset.  
apply this statefulset's yaml:
```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: test
  namespace: default
spec:
  serviceName: "test-demo"
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      hostNetwork: true
      containers:
      - name: sts
        env:
        - name: KEY1
          value: Value1
        image: bash:4.4
        command:
        - "/bin/sleep"
        - "36000"
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
```
After a while, execute `kubectl get pods`, and the pod is running
```shell
$ kubectl get pods
NAME     READY   STATUS              RESTARTS   AGE
test-0   1/1     Running             0          34s
```

2. prepare a new stateful's yaml, which a new env key and more replicas.
```yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: test
  namespace: default
spec:
  serviceName: "test-demo"
  replicas: 2
  template:
    metadata:
      labels:
        app: test
    spec:
      hostNetwork: true
      containers:
      - name: sts
        env:
        - name: KEY2
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: KEY1
          value: Value1
        image: bash:4.4
        command: 
        - "/bin/sleep"
        - "36000"
  updateStrategy:
    rollingUpdate:
      partition: 1
    type: RollingUpdate
```

3. delete the pod `test-0` and apply a new stateful's yaml
```shell
$ kubectl delete pod test-0 & kubectl apply -f statefulset2.yaml 
[1] 3580
pod "test-0" deleted
statefulset.apps/test configured
[1]+  Done                    kubectl delete pod test-0
```

4. describe the statefulset
```
$ kubectl describe sts test
Name:               test
Namespace:          default
CreationTimestamp:  Tue, 28 May 2019 15:09:31 +0800
Selector:           app=test
Labels:             app=test
Annotations:        kubectl.kubernetes.io/last-applied-configuration:
                      {"apiVersion":"apps/v1beta1","kind":"StatefulSet","metadata":{"annotations":{},"name":"test","namespace":"default"},"spec":{"replicas":2,"...
Replicas:           824633983536 desired | 1 total
Update Strategy:    RollingUpdate
  Partition:        824633984396
Pods Status:        0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app=test
  Containers:
   sts:
    Image:      bash:4.4
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sleep
      36000
    Environment:
      KEY2:      (v1:status.hostIP)
      KEY1:     Value1
    Mounts:     <none>
  Volumes:      <none>
Volume Claims:  <none>
Events:
  Type     Reason            Age                 From                    Message
  ----     ------            ----                ----                    -------
  Normal   SuccessfulCreate  8m8s                statefulset-controller  create Pod test-0 in StatefulSet test successful
  Warning  FailedCreate      15s (x16 over 73s)  statefulset-controller  create Pod test-0 in StatefulSet test failed error: Pod "test-0" is invalid: spec.containers[0].env[0].valueFrom: Invalid value: "": may not be specified when `value` is not empty
```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

### PR DESCRIPTION
**Pull request by tcmichael**
**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
I think the root cause of #78420 is that StatefulSet, which will be `json.Unmarshal` to, is not reset.
so that `ApplyRevision` makes the subfield `env` of `StatefulSet` has both field `valueFrom` and `value` that is invalid. 

**Which issue(s) this PR fixes**:

Fixes #78420

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tcmichael** [comment]
@liggitt

**Comment by liggitt** [comment]
thanks for the fix. this needs an accompanying unit test demonstrating the bug and that this fixes it

**Comment by tcmichael** [comment]
OK, I added a unit test.

File: pkg/controller/statefulset/stateful_set_utils.go [hunk 1]
```diff
@@ -344,6 +344,7 @@ func ApplyRevision(set *apps.StatefulSet, revision *apps.ControllerRevision) (*a
 	if err != nil {
 		return nil, err
 	}
+	clone.Reset()
 	err = json.Unmarshal(patched, clone)
```
Comment (krmayankk) [inline pkg/controller/statefulset/stateful_set_utils.go]: - The documentation(https://golang.org/pkg/encoding/json/#Unmarshal) doesn't mention, that that interface (`clone` here) needs to be initialized. The ideal unmarshal should use the patched and populate all fields in clone and , leave others to default value.
- also the clone := set.DeepCopy() at line 342 doesnt seem necessary since the next line is a read only operation(i know this is old code)

-One way to verify if this indeed fixes the problem, would be to use two versions of ApplyRevision, one without the reset and one with the reset and see that the first one always fails and the second one always passes, ideally i would checkin both tests, but at the very least we can validate if this is the right fix.

Comment (tcmichael) [reply pkg/controller/statefulset/stateful_set_utils.go]: * The interface needs to be initialized. Run simple program below:
```go
package main

import (
        "fmt"
        "encoding/json"
)

func main() {
        type demo struct {
                foo *int `json:"foo"`
        }
        bar := 1
        d := demo{foo: &bar}
        // if `json.Unmarshal` uses default value, d.foo == nil
        if err := json.Unmarshal([]byte("{}"), &d); err != nil {
                panic(err)
        }
        fmt.Println(*d.foo)
}
```
the program does not panic, and the output is 1

* Removed the `clone := set.DeepCopy()`

File: pkg/controller/statefulset/stateful_set_utils.go [hunk 2]
```diff
@@ -339,16 +339,16 @@ func newRevision(set *apps.StatefulSet, revision int64, collisionCount *int32) (
 // ApplyRevision returns a new StatefulSet constructed by restoring the state in revision to set. If the returned error
 // is nil, the returned StatefulSet is valid.
 func ApplyRevision(set *apps.StatefulSet, revision *apps.ControllerRevision) (*apps.StatefulSet, error) {
-	clone := set.DeepCopy()
```
Comment (liggitt) [inline pkg/controller/statefulset/stateful_set_utils.go]: retain the clone to pass to EncodeOrDie

**Comment by liggitt** [comment]
one comment, lgtm otherwise

**Comment by tcmichael** [comment]
@liggitt the pr is done, PTAL.

**Comment by tcmichael** [comment]
I am sorry that I did not pre-execute `verify-gofmt.sh` and I run `gofmt` instead of `gofmt -s`.
I modified my code.
@liggitt PTAL
