### PR TITLE
fix: kube-proxy EndpointSliceCache memory is leaked

### LINKED ISSUE #128928: kube-proxy: EndpointSliceCache memory is leaked
### What happened?

The kube-proxy which is using iptables mode occupies about 8G memory in a cluster of our production environment.
[root ~]$ kubectl top pod kube-proxy-22dcr -n kube-system
NAME               CPU(cores)   MEMORY(bytes)   
kube-proxy-22dcr   2127m        7935Mi          
[root ~]$
[root ~]$ kubectl top pod kube-proxy-s5nk6 -n kube-system
NAME               CPU(cores)   MEMORY(bytes)   
kube-proxy-s5nk6   521m         7931Mi          
[ root ~]$ 
[root ~]$ kubectl top pod kube-proxy-zhqnr -n kube-system
NAME               CPU(cores)   MEMORY(bytes)   
kube-proxy-zhqnr   389m         7933Mi          
[root ~]$ kubectl top pod kube-proxy-xsvn7 -n kube-system
NAME               CPU(cores)   MEMORY(bytes)   
kube-proxy-xsvn7   464m         7390Mi          
[ root ~]$ 
Clipboard_Screenshot_1732443822
Clipboard_Screenshot_1732443860

On the node, this is only about two thousand three hundred iptables rules.
[centos ~]# iptables-save | wc -l
2358
[centos ~]# 

And the number of pod and service in this cluster is less than 1000.
[root ~]$ kubectl get svc -A | wc -l
414
[root ~]$ kubectl get endpoints -A | wc -l
417
[ root ~]$ kubectl get pod -A | wc -l
831
[root ~]$ kubectl get endpointslices -A | wc -l
552
[root ~]$ 

Here are some results of the reproduction：
1， 
Clipboard_Screenshot_1732323625

2,
  HELP kubeproxy_sync_proxy_rules_endpoint_changes_total [ALPHA] Cumulative proxy rules Endpoint changes
  TYPE kubeproxy_sync_proxy_rules_endpoint_changes_total counter
kubeproxy_sync_proxy_rules_endpoint_changes_total 681443
  HELP kubeproxy_sync_proxy_rules_service_changes_total [ALPHA] Cumulative proxy rules Service changes
  TYPE kubeproxy_sync_proxy_rules_service_changes_total counter
kubeproxy_sync_proxy_rules_service_changes_total 1.363076e+06

### What did you expect to happen?

when the number of pod and service is less than 1000, the memory should not occupy so much memory (about 8G).

### How can we reproduce it (as minimally and precisely as possible)?

1, Create service and delete it repeatedly.
2, When creating service, the namespace name or service name should be different from all previously created.
Memory will slowly increase.

### Anything else we need to know?

_No response_

### Kubernetes version

v1.30

### Cloud provider

tke

### OS version
ubuntu2204

### PR DESCRIPTION
**Pull request by orange30**
fix: kube-proxy EndpointSliceCache memory is leaked
Signed-off-by: zhikuodu <duzhk@qq.com>

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
kube-proxy: EndpointSliceCache memory is leaked.

#### Which issue(s) this PR fixes:

Fixes #128928

#### Does this PR introduce a user-facing change?

```release-note
Fixed: kube-proxy EndpointSliceCache memory is leaked
```

### CODE REVIEW

**Comment by aojea** [comment]
/ok-to-test

can we please add an unit test?

**Comment by aojea** [comment]
@orange30 per example, a test in /pkg/proxy/endpointschangetracker_test.go that adds a service and an endpoint slice to the tracker and then deletes it should leave the internal structure empty

**Comment by orange30** [comment]
> @orange30 per example, a test in /pkg/proxy/endpointschangetracker_test.go that adds a service and an endpoint slice to the tracker and then deletes it should leave the internal structure empty

Thanks! I will add an unit test today.

**Comment by aojea** [comment]
@orange30 please add this one for the service cache too
```diff
diff --git a/pkg/proxy/servicechangetracker_test.go b/pkg/proxy/servicechangetracker_test.go
index e139d664824..af18ddafb94 100644
--- a/pkg/proxy/servicechangetracker_test.go
+++ b/pkg/proxy/servicechangetracker_test.go
@@ -900,3 +900,23 @@ func TestBuildServiceMapServiceUpdate(t *testing.T) {
                t.Errorf("expected healthcheck ports length 0, got %v", healthCheckNodePorts)
        }
 }
+
+func TestServiceCacheLeaks(t *testing.T) {
+       fp := newFakeProxier(v1.IPv4Protocol, time.Time{})
+
+       service := makeTestService("ns1", "svc1", func(svc *v1.Service) {
+               svc.Spec.Type = v1.ServiceTypeClusterIP
+               svc.Spec.ClusterIP = "172.16.55.4"
+               svc.Spec.Ports = addTestPort(svc.Spec.Ports, "p1", "UDP", 1234, 4321, 0)
+               svc.Spec.Ports = addTestPort(svc.Spec.Ports, "p2", "TCP", 1235, 5321, 0)
+       })
+       fp.addService(service)
+       if len(fp.serviceChanges.items) != 1 {
+               t.Errorf("Found %d items on the cache, 1 expected", len(fp.serviceChanges.items))
+       }
+
+       fp.deleteService(service)
+       if len(fp.serviceChanges.items) > 0 {
+               t.Errorf("Found %d items on the cache, 0 expected", len(fp.serviceChanges.items))
+       }
+}
```

File: pkg/proxy/endpointslicecache_test.go [hunk 1]
```diff
@@ -559,3 +559,74 @@ func (cmc *cacheMutationCheck) Check(t *testing.T) {
...
+			Name:     ptr.To("n1"),
+			Port:     ptr.To[int32](11),
+			Protocol: ptr.To(v1.ProtocolUDP),
+		}}
+	}
+
+	testCases := []struct {
+		name                 string
+		currEndpointSlices   []*discovery.EndpointSlice
+		haveEntryAfterDelete bool
```
Comment (aojea) [inline pkg/proxy/endpointslicecache_test.go:580]: where should this be true?

File: pkg/proxy/endpointslicecache_test.go [hunk 2]
```diff
@@ -559,3 +559,74 @@ func (cmc *cacheMutationCheck) Check(t *testing.T) {
...
+				if epSlice != nil {
+					fp.deleteEndpointSlice(epSlice)
+				}
+			}
+
+			fp.endpointsMap.Update(fp.endpointsChanges)
+
+			if result := (len(fp.endpointsChanges.endpointSliceCache.trackerByServiceMap) != 0); result != tc.haveEntryAfterDelete {
+				t.Errorf("expected result: %v, got: %v", tc.haveEntryAfterDelete, result)
+			}
```
Comment (aojea) [inline pkg/proxy/endpointslicecache_test.go:629]: it seems you can simplify this test, so you always check that there are no entries after the creation and deletion of the endpoint slice, so no need for ` tc.haveEntryAfterDelete`

File: pkg/proxy/endpointslicecache_test.go [hunk 3]
```diff
@@ -559,3 +559,74 @@ func (cmc *cacheMutationCheck) Check(t *testing.T) {
...
+		},
+	}
+
+	for _, tc := range testCases {
+		t.Run(tc.name, func(t *testing.T) {
+			fp := newFakeProxier(v1.IPv4Protocol, time.Time{})
+			fp.hostname = testHostname
+
+			for _, epSlice := range tc.currEndpointSlices {
+				if epSlice != nil {
```
Comment (aojea) [inline pkg/proxy/endpointslicecache_test.go:613]: when should this be nil?

**Comment by pohly** [comment]
/remove-wg device-management
/remove-sig apps
/remove-sig release
/remove-sig testing

I think some intermediate push accidentally touched additional files.

**Comment by orange30** [comment]
> Quote reply

yes, I am sorry!

File: pkg/proxy/endpointslicecache_test.go [hunk 4]
```diff
@@ -559,3 +560,66 @@ func (cmc *cacheMutationCheck) Check(t *testing.T) {
...
+			for _, epSlice := range tc.currEndpointSlices {
+				fp.addEndpointSlice(epSlice)
+			}
+			fp.endpointsMap.Update(fp.endpointsChanges)
+
+			for _, epSlice := range tc.currEndpointSlices {
+				fp.deleteEndpointSlice(epSlice)
+			}
+
+			fp.endpointsMap.Update(fp.endpointsChanges)
```
Comment (danwinship) [inline pkg/proxy/endpointslicecache_test.go:618]: (inconsistent whitespace between the two clauses; remove the blank line after the second loop)

**Review by danwinship — COMMENTED** [review]
just nitpicks

File: pkg/proxy/endpointslicecache.go [hunk 5]
```diff
@@ -144,6 +144,7 @@ func (cache *EndpointSliceCache) checkoutChanges() map[types.NamespacedName]*end
 		for name, sliceData := range esTracker.pending {
 			if sliceData.remove {
 				delete(esTracker.applied, name)
+				delete(cache.trackerByServiceMap, serviceNN)
```
[the remark this answers is not in the document]
Comment (aojea) [reply pkg/proxy/endpointslicecache.go:147]: nah, it seems to delete all the service map
```diff
diff --git a/pkg/proxy/endpointslicecache_test.go b/pkg/proxy/endpointslicecache_test.go
index 0281bed2455..54cae55dfb7 100644
--- a/pkg/proxy/endpointslicecache_test.go
+++ b/pkg/proxy/endpointslicecache_test.go
@@ -592,6 +592,13 @@ func TestEndpointSliceCacheClearedCorrectly(t *testing.T) {
                                makeTestEndpointSlice("ns1", "ep2", 2, initEndpointsPorts),
                        },
                },
+               {
+                       name: "two endpoint slices, same service",
+                       currEndpointSlices: []*discovery.EndpointSlice{
+                               makeTestEndpointSlice("ns1", "ep1", 1, initEndpointsPorts),
+                               makeTestEndpointSlice("ns1", "ep1", 2, initEndpointsPorts),
+                       },
+               },
                {
                        name: "two endpoint slices, different namespace",
                        currEndpointSlices: []*discovery.EndpointSlice{
@@ -623,3 +630,41 @@ func TestEndpointSliceCacheClearedCorrectly(t *testing.T) {
                })
        }
 }
+
+func TestSameServiceEndpointSliceCacheClearedCorrectly(t *testing.T) {
+
+       initEndpointsPorts := func(eps *discovery.EndpointSlice) {
+               eps.Endpoints = []discovery.Endpoint{{
+                       Addresses: []string{"1.1.1.1"},
+                       NodeName:  ptr.To(testHostname),
+               }}
+               eps.Ports = []discovery.EndpointPort{{
+                       Name:     ptr.To("n1"),
+                       Port:     ptr.To[int32](11),
+                       Protocol: ptr.To(v1.ProtocolUDP),
+               }}
+       }
+
+       currEndpointSlices := []*discovery.EndpointSlice{
+               makeTestEndpointSlice("ns1", "svc1", 1, initEndpointsPorts),
+               makeTestEndpointSlice("ns1", "svc1", 2, initEndpointsPorts),
+       }
+
+       fp := newFakeProxier(v1.IPv4Protocol, time.Time{})
+       fp.hostname = testHostname
+
+       for _, epSlice := range currEndpointSlices {
+               fp.addEndpointSlice(epSlice)
+       }
+       fp.endpointsMap.Update(fp.endpointsChanges)
+
+       // only delete the first endpoint slice
+       fp.deleteEndpointSlice(currEndpointSlices[0])
+
+       fp.endpointsMap.Update(fp.endpointsChanges)
+
+       if len(fp.endpointsChanges.endpointSliceCache.trackerByServiceMap) != 1 {
+               t.Errorf("expected: endpointSliceCache to have one entrie, got: endpointSliceCache has %d entries", len(fp.endpointsChanges.endpointSliceCache.trackerByServiceMap))
+       }
+
+}
```

we can only delete the serviceNN when there is no endpointslice referencing it, not just one of the slices is deleted ... please add these test cases too

**Comment by orange30** [comment]
@aojea @danwinship Please help to review again,thanks!

**Comment by aojea** [comment]
/approve

Final LGTM for Dan and/or Rob

/assign @danwinship @robscott

File: pkg/proxy/endpointslicecache.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (orange30) [reply pkg/proxy/endpointslicecache.go]: > data structure

The creation of the service may take approximately 1 second and a syscall to ipvs may need 50ms.The allocation of a new endpointSliceTracker struct may take only less than 1 ms. If we decide to change this data structure, it may require some additional time for the system to reach a stable state.
