### PR TITLE
e2e: wait for controller manager pod to be ready

### LINKED ISSUE #86318: [Flaky Test] In-tree Volumes: Error getting c-m metrics : the server could not find the requested resource
**Which jobs are flaking**:
- pull-kubernetes-e2e-gce
- ci-kubernetes-e2e-gci-gce

**Which test(s) are flaking**:

* [sig-storage] In-tree Volumes [Driver: hostPath] [Testpattern: Inline-volume (default fs)] subPath should support readOnly file specified in the volumeMount [LinuxOnly]
* [sig-storage] In-tree Volumes [Driver: emptydir] [Testpattern: Inline-volume (default fs)] subPath should support file as subpath [LinuxOnly]
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link] [Testpattern: Pre-provisioned PV (default fs)] volumes should allow exec of files on the volume
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: blockfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should support existing single file [LinuxOnly]
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-bindmounted] [Testpattern: Pre-provisioned PV (default fs)] volumes should store data
* [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Inline-volume (default fs)] volumes should store data
* [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Inline-volume (default fs)] subPath should be able to unmount after the subpath directory is deleted
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: tmpfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should be able to unmount after the subpath directory is deleted
* [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (default fs)] subPath should support existing directory
* [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Inline-volume (default fs)] subPath should support non-existent path
* [sig-storage] In-tree Volumes [Driver: hostPathSymlink] [Testpattern: Inline-volume (default fs)] subPath should support existing directories when readOnly specified in the volumeSource
* [sig-storage] In-tree Volumes [Driver: hostPath] [Testpattern: Inline-volume (default fs)] subPath should be able to unmount after the subpath directory is deleted
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: tmpfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should support existing directories when readOnly specified in the volumeSource
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link-bindmounted] [Testpattern: Pre-provisioned PV (default fs)] subPath should support existing single file [LinuxOnly]
* [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: block] [Testpattern: Pre-provisioned PV (ext3)] volumes should allow exec of files on the volume
* [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand Verify if offline PVC expansion works
* [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (ext3)] volumes should store data

**Testgrid link**:
- https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-default&width=5&include-filter-by-regex=In-tree&sort-by-flakiness=
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=In-tree&width=5&sort-by-flakiness=

**Reason for failure**:
Failure fetching metrics:
```
Dec 15 22:01:17.942: Error getting c-m metrics : the server rejected our request for an unknown reason (get pods kube-controller-manager-e2e-4fc8c5bbfe-674b9-master:10252)
...
Causes: [
                    {
                        Type: "UnexpectedServerResponse",
                        Message: "unknown",
                        Field: "",
                    },
                ],
```
```
Dec  4 20:06:05.021: Error getting Kubelet e2e-f19735d0af-674b9-minion-group-l4ln metrics: the server is currently unable to handle the request (get nodes e2e-f19735d0af-674b9-minion-group-l4ln:10250)
...
Causes: [
                    {
                        Type: "UnexpectedServerResponse",
                        Message: "Error trying to reach service: 'dial tcp 10.40.0.4:10250: i/o timeout'",
                        Field: "",
                    },
                ],
```

**Anything else we need to know**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?ci=0&pr=1&text=Error%20getting%20c-m%20metrics&job=pull-kubernetes-e2e-gce%24&test=sig-storage

This appears to have restarted abruptly around 2/11-2/12

/sig storage
/priority important-soon

### PR DESCRIPTION
**Pull request by aojea**
the getMetricsFromPod function tries to Get metrics from one pod,
however this pod may no be ready at that moment and it fails the
test.

We add a retry to wait for the pod to be ready,

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation

/kind failing-test
> /kind feature

/kind flake

**What this PR does / why we need it**:

    e2e: wait for controller manager pod to be ready
    
    The MetricsGrabber may use the controller-manager pod
    to gather metrics, however, it doesn't wait until
    it is ready to serve, failing the test if this is the
    case.
    
    We wait until the controller-manager pod is running
    before trying to get metrics from it.

**Which issue(s) this PR fixes**:

Fixes #86318

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: test/e2e/framework/metrics/metrics_grabber.go [hunk 1]
```diff
@@ -235,16 +238,26 @@ func (g *Grabber) Grab() (Collection, error) {
...
+	pollErr := wait.PollImmediate(5*time.Second, 2*time.Minute, func() (bool, error) {
+		rawOutput, err := client.CoreV1().RESTClient().Get().
+			Namespace(namespace).
+			Resource("pods").
+			SubResource("proxy").
+			Name(fmt.Sprintf("%v:%v", podName, port)).
+			Suffix("metrics").
+			Do(context.TODO()).Raw()
+		if err != nil {
+			if testutils.IsRetryableAPIError(err) {
```
Comment (aojea) [inline test/e2e/framework/metrics/metrics_grabber.go]: is this needed and catch current problem or we just should retry on error?

File: test/e2e/framework/metrics/metrics_grabber.go [hunk 2]
```diff
@@ -235,16 +238,26 @@ func (g *Grabber) Grab() (Collection, error) {
...
-	rawOutput, err := client.CoreV1().RESTClient().Get().
-		Namespace(namespace).
-		Resource("pods").
-		SubResource("proxy").
-		Name(fmt.Sprintf("%v:%v", podName, port)).
-		Suffix("metrics").
-		Do(context.TODO()).Raw()
-	if err != nil {
+func (g *Grabber) getMetricsFromPod(client clientset.Interface, podName string, namespace string, port int) (metrics string, err error) {
+	pollErr := wait.PollImmediate(5*time.Second, 2*time.Minute, func() (bool, error) {
```
Comment (aojea) [inline test/e2e/framework/metrics/metrics_grabber.go]: I made up the numbers based on the occurrence I've analyzed, feel free to suggest others

File: test/e2e/framework/metrics/metrics_grabber.go [hunk 3]
```diff
@@ -235,16 +238,26 @@ func (g *Grabber) Grab() (Collection, error) {
...
+			if testutils.IsRetryableAPIError(err) {
+				return false, nil
+			}
+			return false, err
+		}
+		metrics = string(rawOutput)
+		return true, nil
+	})
+	if pollErr != nil {
 		return "", err
```
Comment (neolit123) [inline test/e2e/framework/metrics/metrics_grabber.go]: `err` should be defined outside of the `wait.PollImmediate` block.

File: test/e2e/framework/metrics/metrics_grabber.go (hunk 1 above)
Comment (neolit123) [reply test/e2e/framework/metrics/metrics_grabber.go]: SGTM

Comment (neolit123) [reply test/e2e/framework/metrics/metrics_grabber.go]: although a question here is when this happens:
> the getMetricsFromPod function tries to Get metrics from one pod,
however this pod may no be ready at that moment and it fails the
test.

does `IsRetryableAPIError(err) == true`?

Comment (aojea) [reply test/e2e/framework/metrics/metrics_grabber.go]: is a 404, we need to retry always

File: test/e2e/framework/metrics/metrics_grabber.go (hunk 3 above)
Comment (aojea) [reply test/e2e/framework/metrics/metrics_grabber.go]: yeah, I think that we should return pollErr instead of err, I've updated the PR with that

File: test/e2e/framework/metrics/metrics_grabber.go (hunk 2 above)
Comment (liggitt) [reply test/e2e/framework/metrics/metrics_grabber.go]: I don't think it's a good idea to make this low-level helper method take up to 2 minutes to return. I'd rather see us stop using the GrabFromControllerManager() metrics collector in a way that will fail tests if the controller-manager pod isn't up at exactly that moment. That is not even guaranteed to be available in all environments.

An alternative would be to make the metrics grabber wait once for the k-c-m pod to be available in GrabFromControllerManager()

```diff
diff --git a/test/e2e/framework/metrics/metrics_grabber.go b/test/e2e/framework/metrics/metrics_grabber.go
index fdfd51f9997..ce41294cdbe 100644
--- a/test/e2e/framework/metrics/metrics_grabber.go
+++ b/test/e2e/framework/metrics/metrics_grabber.go
@@ -19,6 +19,7 @@ package metrics
 import (
        "context"
        "fmt"
+       "sync"
 
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
        "k8s.io/apimachinery/pkg/fields"
@@ -49,6 +50,8 @@ type Grabber struct {
        grabFromClusterAutoscaler bool
        masterName                string
        registeredMaster          bool
+
+       waitForControllerManagerReadyOnce sync.Once
 }
 
 // NewMetricsGrabber returns new metrics which are initialized.
@@ -160,6 +163,9 @@ func (g *Grabber) GrabFromControllerManager() (ControllerManagerMetrics, error)
        if !g.registeredMaster {
                return ControllerManagerMetrics{}, fmt.Errorf("Master's Kubelet is not registered. Skipping ControllerManager's metrics gathering")
        }
+       g.waitForControllerManagerReadyOnce.Do(func() {
+               // ... wait for pod to exist and be ready up to timeout ...
+       })
        output, err := g.getMetricsFromPod(g.client, fmt.Sprintf("%v-%v", "kube-controller-manager", g.masterName), metav1.NamespaceSystem, ports.InsecureKubeControllerManagerPort)
        if err != nil {
                return ControllerManagerMetrics{}, err
```

File: test/e2e/framework/metrics/metrics_grabber.go [hunk 4]
```diff
@@ -235,16 +237,23 @@ func (g *Grabber) Grab() (Collection, error) {
...
+			Suffix("metrics").
+			Do(context.TODO()).Raw()
+		if err != nil {
+			return false, nil
+		}
+		metrics = string(rawOutput)
+		return true, nil
+	})
+	if pollErr != nil {
+		return "", pollErr
```
Comment (neolit123) [inline test/e2e/framework/metrics/metrics_grabber.go]: this will always return "timeout waiting for condition..."

ideally the underlying error from the RESTClient call should be surfaced:
```
var err error
pollErr := wait.PollImmediate(5*time.Second, 2*time.Minute, func() (bool, error) {
.... err is set here
}
if pollErr != nil {
		return "", err
}
```

Comment (aojea) [reply test/e2e/framework/metrics/metrics_grabber.go]: will follow Jordan's suggestion, what do you think? his arguments sound very solid https://github.com/kubernetes/kubernetes/pull/88982/files#r389928479

Comment (neolit123) [reply test/e2e/framework/metrics/metrics_grabber.go]: if this long poll can be avoided it's better.

**Comment by aojea** [comment]
1/1
/test pull-kubernetes-e2e-kind
/test pull-kubernetes-e2e-gce

**Comment by liggitt** [comment]
/milestone v1.18

test-only change fixing [prominent flake](https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=Error%20getting%20c-m%20metrics)
