### PR TITLE
kubelet: check taint/toleration before accepting pods

### LINKED ISSUE #100408: Kubelet doesn't check taints
#### What happened:

The `GeneralPredicates` method doesn't check taints and tolerations.

https://github.com/kubernetes/kubernetes/blob/5ae856c36f2ea338a6f26301e368ef8331ef2e73/pkg/kubelet/lifecycle/predicate.go#L224

This is problematic in 2 scenarios:
- If the users bypass scheduler by setting a value in `.spec.nodeName`
- If the node restarts. The node would try to restart scheduled pods once it comes back up, even if it's not ready (has a not-ready taint).

#### What you expected to happen:

Kubelet to check taints and tolerations.

#### How to reproduce it (as minimally and precisely as possible):

1. Set a taint in a node.
2. Create a Pod with `.spec.nodeName` set to the Node above, without a matching toleration.

/sig node
/sig scheduling

### PR DESCRIPTION
**Pull request by gjkim42**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This PR adds taint/toleration check to kubelet(**_except for static pods_**)

Related PR: https://github.com/kubernetes/kubernetes/pull/100049

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/100408

#### Does this PR introduce a user-facing change?

```release-note
Kubelet now checks "NoExecute" taint/toleration before accepting pods, except for static pods.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by gjkim42** [comment]
Saved failed log

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101218/pull-kubernetes-e2e-kind/1383893810378969088
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101218/pull-kubernetes-e2e-kind-ipv6/1383893810399940608
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101218/pull-kubernetes-conformance-kind-ga-only-parallel/1383893810420912128
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101218/pull-kubernetes-e2e-gce-ubuntu-containerd/1383893810357997568/
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101218/pull-kubernetes-e2e-gce-100-performance/1383893810475438080

Maybe, static pods not setting proper toleration caused this.

**Comment by gjkim42** [comment]
Updated to check taint/toleration **except for static pods**

Alternative: Fix all static pods to set tolerations according to the node's taints

File: pkg/kubelet/lifecycle/predicate_test.go [hunk 1]
```diff
@@ -240,6 +241,64 @@ func TestGeneralPredicates(t *testing.T) {
...
+					Taints: []v1.Taint{
+						{Key: "bar", Effect: v1.TaintEffectNoExecute},
+					},
+				},
+				Status: v1.NodeStatus{Capacity: makeResources(10, 20, 32, 0, 0, 0).Capacity, Allocatable: makeAllocatableResources(10, 20, 32, 0, 0, 0)},
+			},
+			fits:    false,
+			wErr:    nil,
+			reasons: []PredicateFailureReason{&PredicateFailureError{tainttoleration.Name, tainttoleration.ErrReasonNotMatch}},
+			name:    "noexecute taint/toleration not match",
```
Comment (alculquicondor) [inline pkg/kubelet/lifecycle/predicate_test.go:300]: Add a test to check that a taint `PreferNoSchedule` doesn't prevent a Pod from running.

Comment (gjkim42) [reply pkg/kubelet/lifecycle/predicate_test.go]: Updated.

**Comment by alculquicondor** [comment]
release note should mention that static pods are exempt. lgtm otherwise (but I'm not a sig-node reviewer)

**Comment by gjkim42** [comment]
Updated the release note.

**Comment by gjkim42** [comment]
Ready to be reviewed.

**Comment by gjkim42** [comment]
@matthyx @ehashman 
Could you PTAL?

**Comment by gjkim42** [comment]
/assign @mrunalp 
Could you PTAL?

**Comment by gjkim42** [comment]
Resolved the conflict.

**Review by ehashman — COMMENTED** [review]
/lgtm

File: pkg/kubelet/lifecycle/predicate.go [hunk 2]
```diff
@@ -247,5 +250,16 @@ func GeneralPredicates(pod *v1.Pod, nodeInfo *schedulerframework.NodeInfo) ([]Pr
 		reasons = append(reasons, &PredicateFailureError{nodeports.Name, nodeports.ErrReason})
 	}
 
+	// Check taint/toleration except for static pods
+	if !types.IsStaticPod(pod) {
+		_, isUntolerated := corev1.FindMatchingUntoleratedTaint(nodeInfo.Node().Spec.Taints, pod.Spec.Tolerations, func(t *v1.Taint) bool {
+			// PodToleratesNodeTaints is only interested in NoSchedule and NoExecute taints.
+			return t.Effect == v1.TaintEffectNoSchedule || t.Effect == v1.TaintEffectNoExecute
```
Comment (liggitt) [inline pkg/kubelet/lifecycle/predicate.go:257]: NoSchedule shouldn't be considered by kubelet, only NoExecute, right?

File: pkg/kubelet/lifecycle/predicate.go [hunk 3]
```diff
@@ -247,5 +250,16 @@ func GeneralPredicates(pod *v1.Pod, nodeInfo *schedulerframework.NodeInfo) ([]Pr
...
+		})
+		if isUntolerated {
```
Comment (liggitt) [inline pkg/kubelet/lifecycle/predicate.go:259]: how does TolerationSeconds interact with this evaluation?

File: pkg/kubelet/lifecycle/predicate.go (hunk 2 above)
Comment (liggitt) [reply pkg/kubelet/lifecycle/predicate.go:257]: also, if Effect is unset, this should tolerate all effects, right?

**Comment by liggitt** [comment]
/hold

at first glance, this looks incompatible with the documented API for tolerations (kubelet rejecting a NoSchedule taint, handling of tolerations that don't set Effect, etc)

File: pkg/kubelet/lifecycle/predicate.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/kubelet/lifecycle/predicate.go:257]: `NoSchedule` means that a Pod is not scheduled or started in a node.
`NoExecute` means that a Pod is not scheduled or started in a node and that it's evicted if it's already in the node.

Then, both indicate that the Pod shouldn't be started. `NoExecute` has the additional effect of affecting running Pods.

AFAIK, taints always have an effect (tolerations might not).

File: pkg/kubelet/lifecycle/predicate.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/kubelet/lifecycle/predicate.go:259]: Any toleration (even with tolerationSeconds) applies to a taint at scheduling/startup time.

The `tolerationSeconds` is about delaying the eviction.

File: pkg/kubelet/lifecycle/predicate.go (hunk 2 above)
Comment (liggitt) [reply pkg/kubelet/lifecycle/predicate.go:257]: > NoSchedule means that a Pod is not scheduled or started in a node.

no, it explicitly means it's not scheduled to a node, but nodes submitted directly to the node without the scheduler are permitted:

```
	// Do not allow new pods to schedule onto the node unless they tolerate the taint,
	// but allow all pods submitted to Kubelet without going through the scheduler
	// to start, and allow all already-running pods to continue running.
	// Enforced by the scheduler.
	TaintEffectNoSchedule TaintEffect = "NoSchedule"
```

also, I think by rejecting the pod here, an already-running pod would be stopped if the kubelet restarted

Comment (alculquicondor) [reply pkg/kubelet/lifecycle/predicate.go:257]: Ah, it doesn't match the user documentation :/ https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ (at least it's not clear in this regard).

But since the API comment is clear, let's just check NoSchedule.

Comment (liggitt) [reply pkg/kubelet/lifecycle/predicate.go:257]: > But since the API comment is clear, let's just check NoSchedule.

NoExecute?

Comment (alculquicondor) [reply pkg/kubelet/lifecycle/predicate.go:257]: Oops, yes

Comment (liggitt) [reply pkg/kubelet/lifecycle/predicate.go:257]: That seems more reasonable to me, but would like a second from the node team.

Additionally, since this break passed tests as-is, we have a test gap that would allow breaking handling of NoSchedule taints. Please add a test that would have caught this to ensure the kubelet does not prevent admission of pods for that reason.

**Comment by gjkim42** [comment]
According to https://github.com/kubernetes/kubernetes/pull/101218#discussion_r627647206,
updated kubelet to only care about `NoExecute` taint/toleration.(ignore `NoSchedule`, it is considered by the scheduler)

Need sig-node's opinions
/assign @derekwaynecarr @mrunalp

**Comment by gjkim42** [comment]
rebased.

**Comment by gjkim42** [comment]
cc @mrunalp @derekwaynecarr 
Could you please take a look at this?

File: pkg/kubelet/lifecycle/predicate_test.go [hunk 4]
```diff
@@ -249,6 +250,80 @@ func TestGeneralPredicates(t *testing.T) {
 			reasons: []PredicateFailureReason{&PredicateFailureError{nodeports.Name, nodeports.ErrReason}},
 			name:    "hostport conflict",
 		},
+		{
```
Comment (ehashman) [inline pkg/kubelet/lifecycle/predicate_test.go:253]: Is there a way to add tests for the static pod case?

Comment (gjkim42) [reply pkg/kubelet/lifecycle/predicate_test.go:254]: Added.

**Comment by gjkim42** [comment]
@ehashman @mrunalp 
Could you PTAL?

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by matthyx** [comment]
@mrunalp could you approve?

**Comment by gjkim42** [comment]
/assign @dims

Could you approve this?

**Comment by gjkim42** [comment]
@mrunalp 
Could you take a look at this?
Also, IMO this one should be cherry-picked.

**Comment by Huang-Wei** [comment]
Some refactoring work about General(Predicates)Filter is WIP in https://github.com/kubernetes/kubernetes/pull/103934#issuecomment-900665567. I'd suggest this PR to rebase that one, and then it'd be easy to compose kubelet specific taint/toleration logic in this PR.

**Comment by gjkim42** [comment]
@Huang-Wei 
Thanks for informing me. I think that PR is WIP as you said, so let me wait for it to be merged before rebase it.

/hold

**Comment by dims** [comment]
this PR has been on hold for about 2 weeks. Can you please see how to unblock this by reviewing comments etc? or please close this out (Trying to declutter our open list of PRs)

**Comment by gjkim42** [comment]
This PR is waiting for https://github.com/kubernetes/kubernetes/pull/103934 to be merged.

**Comment by Huang-Wei** [comment]
@gjkim42 #103934 has been merged. You can rebase and proceed with this PR.

**Comment by gjkim42** [comment]
/assign @derekwaynecarr 

Could you PTAL?

This PR makes kubelet check NoExecute taint/toleration before admitting pods.

File: pkg/kubelet/lifecycle/predicate.go (hunk 3 above)
Comment (derekwaynecarr) [reply pkg/kubelet/lifecycle/predicate.go:283]: is there a reason we cant move this check inside `scheduler.AdmissionCheck` after it validates nodeports for example?

**Review by derekwaynecarr — CHANGES_REQUESTED** [review]
the logic and test looks good, but seems like it would be better to move the check inside scheduler.AdmissionFramework itself.  can you explain why that is not preferred in case I am missing something?

**Comment by derekwaynecarr** [comment]
caught up with author on slack.

>We found that kubelet should only care about NoExecute taint, and the scheduler should care about NoSchedule and NoExecute taint. So we decided to split taint validation logic into each component.

the above is reasonable to me.

/approve
/lgtm
