### PR TITLE
don´t run openapi spec with ConsistentListFromCache feature gate enabled

### LINKED ISSUE #121865: [Flaking Test][sig-network] ci-kubernetes-verify-master verify-openapi-spec
### Which jobs are flaking?

Verify Master - Master Blocking https://testgrid.k8s.io/sig-release-master-blocking#verify-master

### Which tests are flaking?

verify.openapi-spec

### Since when has it been flaking?

Inconsistently since 2 November. First failure (shown in testgrid) https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-verify-master/1719970042151440384

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#verify-master

### Reason for failure (if possible)

API Server is not becoming ready during `hack/make-rules/../../hack/verify-openapi-spec.sh`

### Anything else we need to know?

Relevant logs
```
+++ command: bash "hack/make-rules/../../hack/verify-openapi-spec.sh"
go version go1.21.4 linux/amd64
Downloading https://github.com/coreos/etcd/releases/download/v3.5.10/etcd-v3.5.10-linux-amd64.tar.gz succeed
etcd v3.5.10 installed. To use:
export PATH="/home/prow/go/src/k8s.io/kubernetes/third_party/etcd:${PATH}"
+++ [1113 21:08:56] Building go targets for linux/amd64
    k8s.io/kubernetes/cmd/kube-apiserver (static)
+++ [1113 21:11:10] Building go targets for linux/amd64
    k8s.io/kubernetes/cmd/kube-apiserver (static)
etcd --advertise-client-urls http://127.0.0.1:2379/ --data-dir /tmp/tmp.jwE2A0E5lK --listen-client-urls http://127.0.0.1:2379/ --log-level=warn 2> "/logs/artifacts/etcd.dd149c5e-01f1-4127-9f65-28eade1b4496.root.log.DEBUG.20231113-211118.287462" >/dev/null
Waiting for etcd to come up.
+++ [1113 21:11:18] On try 2, etcd: : {"health":"true","reason":""}
{"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"2","raft_term":"2"}}+++ [1113 21:11:19] Starting kube-apiserver
!!! [1113 21:11:50] Timed out waiting for apiserver:  to answer at https://127.0.0.1:8050/healthz; tried 30 waiting 1 between each
!!! [1113 21:11:50] Here are the last 10 lines from kube-apiserver (/tmp/update-openapi-spec.sh.IoKFHR/openapi-api-server.log)
!!! [1113 21:11:50] === BEGIN OF LOG ===
I1113 21:11:50.375973  288022 healthz.go:261] poststarthook/start-kubernetes-service-cidr-controller check failed: readyz
[-]poststarthook/start-kubernetes-service-cidr-controller failed: not finished
I1113 21:11:50.390824  288022 healthz.go:261] poststarthook/start-kubernetes-service-cidr-controller check failed: readyz
[-]poststarthook/start-kubernetes-service-cidr-controller failed: not finished
I1113 21:11:50.475803  288022 healthz.go:261] poststarthook/start-kubernetes-service-cidr-controller check failed: readyz
[-]poststarthook/start-kubernetes-service-cidr-controller failed: not finished
I1113 21:11:50.491708  288022 healthz.go:261] poststarthook/start-kubernetes-service-cidr-controller check failed: readyz
[-]poststarthook/start-kubernetes-service-cidr-controller failed: not finished
I1113 21:11:50.575548  288022 healthz.go:261] poststarthook/start-kubernetes-service-cidr-controller check failed: readyz
[-]poststarthook/start-kubernetes-service-cidr-controller failed: not finished
!!! [1113 21:11:50] === END OF LOG ===
+++ [1113 21:11:53] Clean up complete
+++ exit code: 1
+++ error: 1
[0;31mFAILED   verify-openapi-spec.sh	179s
```

### Relevant SIG(s)

/sig-testing

### PR DESCRIPTION
**Pull request by aojea**
/kind bug
/kind flake
Fixes #121865

```release-note
NONE
```

### CODE REVIEW

File: test/integration/controlplane/api_all_test.go [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+// Test verifies that the apiserver bootstrap does not regress when all feature
+// gates are enabled.
+// It acts as a sentinel using the integration framework timeouts, if this test fails
+// is an indication that any test on the integration is susceptible to fail because of
+// the apiserver not be able to bootstrap in time.
+// The existing timeouts are:
+// * 1 minute for apiserver to be ready
+// * 30 seconds for default namespace to be created
+// * 30 seconds for kubernetes.default service to be created
+func TestAllAPIsByDefault(t *testing.T) {
```
Comment (liggitt) [inline test/integration/controlplane/api_all_test.go:41]: was this test effective at flushing out the issue?

Comment (aojea) [reply test/integration/controlplane/api_all_test.go:41]: yes, is how I reproduced the problem locally, otherwise it was impossiblel to get those stack traces

**Comment by aojea** [comment]
let's get the flake fixed first

**Comment by aojea** [comment]
@liggitt should we wait for https://github.com/kubernetes/kubernetes/pull/123674 or just merge this?

**Comment by liggitt** [comment]
/milestone v1.30

fixes test flake, no change to generated openapi
