### PR TITLE
Fix loopback device lookup

### LINKED ISSUE #96888: Block devices are not torn down when /var/lib/kubelet is symlink
**How to reproduce it (as minimally and precisely as possible)**:
1. Make /var/lib/kubelet a symlink
    ```
    mkdir -p /tmp/data/kubelet
    ln -s  /tmp/data/kubelet /var/lib/kubelet
    ```

1. Run  kubelet
    ```
    hack/local-up-cluster.sh
    ```

1. Create a block PVC + a pod that uses it.
1. Delete the pod.

-> The pod is `Terminating` forever. In kubelet logs:
```
W1126 13:11:25.728798    4415 volume_path_handler_linux.go:61] couldn't find loopback device which takes file descriptor lock. Skip detaching device. device path: "/var/lib/kubelet/plugins/kubernetes.io/aws-ebs/volumeDevices/aws:/us-east-
1d/vol-0b1729094ca87a001/7e04362d-39c9-4417-874a-618d5c9a9924"
```

The reason is that `losetup -j /var/lib/kubelet/plugins/kubernetes.io/aws-ebs/volumeDevices/aws:/us-east-1d/vol-0b1729094ca87a001/7e04362d-39c9-4417-874a-618d5c9a9924` shows:
```
/dev/loop0: [0005]:53278 (/tmp/data/kubelet/plugins/kubernetes.io/aws-ebs/volumeDevices/aws:/us-east-1d/vol-0b1729094ca87a001/7e04362d-39c9-4417-874a-618d5c9a9924)
```

kubelet can't find `/var/lib/kubelet/plugins...` there, because losetup shows real path `/tmp/data/kubelet/plugins...`.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18

/sig storage
/priority important-soon

### PR DESCRIPTION
**Pull request by jsafrane**
In case `/var/lib/kubelet` is a symlink, `losetup -j <device in/var/lib/kubelet>` will show the device paths with symlinks fully evaluated.

Fix the routine that parses  `losetup -j` and expand symlinks in the path that we want to find there.

/kind bug

**Which issue(s) this PR fixes**:

Fixes #96888

**Does this PR introduce a user-facing change?**:

```release-note
Fixed cleanup of block devices when /var/lib/kubelet is a symlink.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by jsafrane** [comment]
Btw, I checked the rest of volume_path_handler_linux.go and the rest does not need symlink expansion.

File: pkg/volume/util/volumepathhandler/volume_path_handler_linux.go [hunk 1]
```diff
@@ -131,6 +131,12 @@ func parseLosetupOutputForDevice(output []byte, path string) (string, error) {
 		return "", errors.New(ErrDeviceNotFound)
 	}
 
+	// Fully expand any symlinks in the device path, losetup output has them expanded too
+	realPath, err := filepath.EvalSymlinks(path)
+	if err != nil {
+		return "", fmt.Errorf("failed to evaluate path %s: %s", path, err)
+	}
```
Comment (gnufied) [inline pkg/volume/util/volumepathhandler/volume_path_handler_linux.go:138]: should we instead call `losetup` on expanded path, so as if behaviour of losetup changes in future - we don't break anything?

Comment (jsafrane) [reply pkg/volume/util/volumepathhandler/volume_path_handler_linux.go:137]: I think evaluating paths before calling losetup is not useful. But I see your point, I added check for both `realPath` and original `path`, just in case.

Comment (gnufied) [reply pkg/volume/util/volumepathhandler/volume_path_handler_linux.go:137]: > I think evaluating paths before calling losetup is not useful.

Can you explain why is it not useful? Do you foresee any breakage? From very afar it sounds like it is better to pass expanded path to losetup and scan for only one path rather than two?

Comment (jsafrane) [reply pkg/volume/util/volumepathhandler/volume_path_handler_linux.go:137]: The initial concern was that losetup can change in the future and it may not expand symlinks in `losetup -j` output. So if it lists symlinks instead of evaluating them, we should check for the unevaluated path too.
