### PR TITLE
addon updater should not retry too many times - specs may be invalid

### LINKED ISSUE #10136: Flaky e2e test: Addon update should propagate add-on file changes (Failed 3 times in the last 30 runs. Stability: 90 %)
Master tracking issue: #9312 

Error message as follows (pretty uninformative - need to fix that):

/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/addon_update.go:321
Expected error:
    <*errors.errorString | 0xc208029760>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred

### PR DESCRIPTION
**Pull request by marekbiskup**
Fixes #10136  (error was found in production code, not in the test)

Risk of regression: small (e2e test passes; this is only retry on error; another retry is performed in 10 minutes, so cluster should recover even if these retries fail)

The patch is not so important for production code, but our e2e test fails because of a race condition (that may appear in production too)

### CODE REVIEW

File: test/e2e/addon_update.go [hunk 1]
```diff
@@ -181,7 +181,7 @@ spec:
 `
 
 var addonTestPollInterval = 3 * time.Second
-var addonTestPollTimeout = 3 * time.Minute
+var addonTestPollTimeout = 1 * time.Minute
```
Comment (marekbiskup) [inline test/e2e/addon_update.go]: rollback of my previous "fix".

**Comment by marekbiskup** [comment]
@zmerlynn , you reviewed the test code. Could you also be the first reviewer of this fix?

**Comment by marekbiskup** [comment]
@k8s-bot , please test it

**Comment by zmerlynn** [comment]
LGTM

**Comment by marekbiskup** [comment]
@k8s-bot test this please

**Comment by marekbiskup** [comment]
Investigating errors - may be patch-related. Do not merge.

**Comment by marekbiskup** [comment]
Indeed, failures are patch-related. The API server may be down and creating addons may fail. Retrying after 10 minutes is too late then.

Conclusion - we'd better retry more often, But it doesn't make any sense to retry a single execution of kube-addon-updater.sh than the interval between consecutive invocations of this script.
I'll modify the production code only a bit and update the test instead.

**Comment by marekbiskup** [comment]
Ready for review.
It blocks #10618, which blocks #10487, so it has become urgent.

File: cluster/saltbase/salt/kube-addons/kube-addon-update.sh [hunk 2]
```diff
@@ -266,6 +271,12 @@ function create-objects() {
     local -r file_paths=$2
     local file_path
     for file_path in ${file_paths}; do
+        # Remember that the file may have disappear by now
+        # But we don't want to check it here because
+        # such race concition may always happen after
```
Comment (zmerlynn) [inline cluster/saltbase/salt/kube-addons/kube-addon-update.sh]: *condition

**Comment by zmerlynn** [comment]
LGTM modulo nit. Needs rebase?

**Comment by marekbiskup** [comment]
rebased

**Comment by marekbiskup** [comment]
and typo fixed

**Comment by zmerlynn** [comment]
LGTM

**Comment by zmerlynn** [comment]
cc @alex-mohr @quinton-hoole for rubber stamps.

**Comment by zmerlynn** [comment]
(In case not immediately obvious, stamps quickly would be appreciated. This is at a bottom of a chain that goes #10237 -> #10618 -> #10487, and I can only chase so many LGTM/merges today.)

**Comment by zmerlynn** [comment]
@k8s-bot: retest this please

and kindly stop flaking on #10622, kthxbai.

**Comment by zmerlynn** [comment]
@k8s-bot: retest this please

**Comment by zmerlynn** [comment]
@k8s-bot: ok to test

**Comment by zmerlynn** [comment]
ONCALL VIOLATING PROCESS: After careful consideration, this is at the bottom of a chain of 3 PRs related to a heavily triaged issue, and all the PRs need some incremental soak time today, in advance of the holiday weekend. If you wish to take my badge for violating process, you may. Merging "to be blessed".
