### PR TITLE
quota controller fixes

### LINKED ISSUE #71450: ResourceQuota objects not refreshing anymore (while admission controller still working)
**What happened**

ResourceQuotas are configured in every namespace of a busy production cluster. At some point the following happened:

- "status:used" got inflated / was more than the sum of Requests in namespaces
- "status:hard" refused to get updated via applying new manifests - "spec:hard" was normally updated but "status:hard" was stuck.
- attempted deleting and recreating the ResourceQuota, and "status" remained empty {}.

Still, the main functionality of refusing to schedule new pods that exceeded current status:hard was still working.

**Remediation:**

killed controller-manager, as soon as another pod took the master lease and controllers started working, the issue got resolved.

My best guess is that there's some kind of deadlock in the ResourceQuota controller or in controller-manager in general.

**Environment**:
- k8s 1.10.9
- Cloud provider: VSphere on-premise
- OS: Ubuntu 16.04
- Kernel:  4.4.0-135

/kind bug
/sig apps api-machinery scheduling
(not sure what's the exact SIG for this)

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

Fixes a panoply of quota issues that are relevant now that we intend to quota based on discovery

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #71450

* Improves quota logging output around waiting for informers to resync
* Fixes an existing race condition in the quota test
* Generates a missing networkpolicies client so that all in-tree types actually have informers
* Updates quota status with hard limits even in the face of calculation errors (otherwise, a single calculation error would prevent quota status from ever reflecting limits, and ever enforcing anything in admission)
* Updates quota status with resources that could be calculated in the face of partial calculation errors (otherwise a calculation error on a single resource could prevent usage info for other resources from ever being populated, and block admission for those resources)
* Avoids rejecting admission based on missing usage info when the missing info isn't relevant (otherwise a single missing resource usage could block all resources addressed by that quota)
* Avoids deadlocks in quota resync
* Avoids letting quota evaluators use unsynced informers

**Does this PR introduce a user-facing change?**:
```release-note
* Fixed a potential deadlock in resource quota controller
* Enabled recording partial usage info for quota objects specifying multiple resources, when only some of the resources' usage can be determined.
```

### CODE REVIEW

File: pkg/controller/resourcequota/resource_quota_controller_test.go [hunk 1]
```diff
@@ -909,3 +924,253 @@ func TestAddQuota(t *testing.T) {
...
+		t.Fatalf("Expected quotacontroller.Sync to be running but it is blocked: %v", err)
+	}
+
+	// Simulate the discovery client returning an error
+	fakeDiscoveryClient.setPreferredResources(nil)
+	fakeDiscoveryClient.setError(fmt.Errorf("Error calling discoveryClient.ServerPreferredResources()"))
+
+	// Wait until sync discovers the change
+	time.Sleep(1 * time.Second)
+
```
Comment (yliaog) [inline pkg/controller/resourcequota/resource_quota_controller_test.go]: what about check expectSyncBlocked(...)?

File: pkg/controller/resourcequota/resource_quota_controller_test.go [hunk 2]
```diff
@@ -909,3 +924,253 @@ func TestAddQuota(t *testing.T) {
...
+		t.Fatalf("Expected quotacontroller.Sync to still be running but it is blocked: %v", err)
+	}
+
+	// Simulate the discovery client returning a resource the restmapper can resolve, but will not sync caches
+	fakeDiscoveryClient.setPreferredResources(unsyncableServerResources)
+	fakeDiscoveryClient.setError(nil)
+
+	// Wait until sync discovers the change
+	time.Sleep(1 * time.Second)
+
```
Comment (yliaog) [inline pkg/controller/resourcequota/resource_quota_controller_test.go]: similarly check expectSyncBlocked(...)

File: pkg/controller/resourcequota/resource_quota_controller.go [hunk 3]
```diff
@@ -423,24 +423,90 @@ func (rq *ResourceQuotaController) Sync(discoveryFunc NamespacedResourcesFunc, p
...
 		// Ensure workers are paused to avoid processing events before informers
 		// have resynced.
 		rq.workerLock.Lock()
 		defer rq.workerLock.Unlock()
 
-		// Perform the monitor resync and wait for controllers to report cache sync.
-		if err := rq.resyncMonitors(newResources); err != nil {
-			utilruntime.HandleError(fmt.Errorf("failed to sync resource monitors: %v", err))
-			return
+		// Once we get here, we should not unpause workers until we've successfully synced
```
Comment (yliaog) [inline pkg/controller/resourcequota/resource_quota_controller.go]: so if a resource (say from aggregated apiserver) somehow is discoverable, but not syncable, that will block resourcequota from working for all other resources, even though that particular problematic resource is not used anywhere for quota.

Comment (liggitt) [reply pkg/controller/resourcequota/resource_quota_controller.go]: that's true... this was copied from the GC controller, where the consequences of incomplete information are far worse (incorrect object deletion).

I think I can simplify this to just timeout the WaitForCacheSynced line and add logic to the quota evaluators to error if their listers are consulted before their backing informers are fully synced.

File: pkg/quota/v1/generic/evaluator.go [hunk 4]
```diff
@@ -33,15 +34,74 @@ import (
...
+// ListerFuncForResourceFunc knows how to provision a lister from an informer func.
+// The lister returns errors until the informer has synced.
 func ListerFuncForResourceFunc(f InformerForResourceFunc) quota.ListerForResourceFunc {
 	return func(gvr schema.GroupVersionResource) (cache.GenericLister, error) {
 		informer, err := f(gvr)
 		if err != nil {
 			return nil, err
 		}
-		return informer.Lister(), nil
+		synced := &atomic.Value{}
```
Comment (smarterclayton) [inline pkg/quota/v1/generic/evaluator.go]: why the more complex atomic.Value?  Why not close over a mutex?

File: pkg/controller/resourcequota/resource_quota_controller.go [hunk 5]
```diff
@@ -423,15 +424,14 @@ func (rq *ResourceQuotaController) Sync(discoveryFunc NamespacedResourcesFunc, p
...
-		klog.V(2).Infof("syncing resource quota controller with updated resources from discovery: %v", newResources)
-		oldResources = newResources
-
 		// Ensure workers are paused to avoid processing events before informers
 		// have resynced.
 		rq.workerLock.Lock()
 		defer rq.workerLock.Unlock()
 
+		// Something has changed, so track the new state and perform a sync.
+		klog.V(2).Infof("syncing resource quota controller with updated resources from discovery: %s", printDiff(oldResources, newResources))
```
Comment (smarterclayton) [inline pkg/controller/resourcequota/resource_quota_controller.go]: Put this under `if klog.V(2) { klog.Infof .. }` so we don't pay the diff cost always.

File: pkg/controller/resourcequota/resource_quota_controller.go [hunk 6]
```diff
@@ -440,9 +440,30 @@ func (rq *ResourceQuotaController) Sync(discoveryFunc NamespacedResourcesFunc, p
...
+	removed := sets.NewString()
+	for oldResource := range oldResources {
+		if _, ok := newResources[oldResource]; !ok {
+			removed.Insert(fmt.Sprintf("%+v", oldResource))
+		}
+	}
+	added := sets.NewString()
+	for newResource := range newResources {
+		if _, ok := oldResources[newResource]; !ok {
+			added.Insert(fmt.Sprintf("%+v", newResource))
```
Comment (smarterclayton) [inline pkg/controller/resourcequota/resource_quota_controller.go]: why `%+v`?

File: pkg/controller/resourcequota/resource_quota_controller.go [hunk 7]
```diff
@@ -423,15 +424,14 @@ func (rq *ResourceQuotaController) Sync(discoveryFunc NamespacedResourcesFunc, p
...
-		// Something has changed, so track the new state and perform a sync.
-		klog.V(2).Infof("syncing resource quota controller with updated resources from discovery: %v", newResources)
-		oldResources = newResources
-
 		// Ensure workers are paused to avoid processing events before informers
 		// have resynced.
 		rq.workerLock.Lock()
 		defer rq.workerLock.Unlock()
 
+		// Something has changed, so track the new state and perform a sync.
```
Comment (smarterclayton) [inline pkg/controller/resourcequota/resource_quota_controller.go]: How often do we even call this loop?

File: pkg/controller/resourcequota/resource_quota_controller.go [hunk 8]
```diff
@@ -437,8 +437,14 @@ func (rq *ResourceQuotaController) Sync(discoveryFunc NamespacedResourcesFunc, p
 			utilruntime.HandleError(fmt.Errorf("failed to sync resource monitors: %v", err))
 			return
 		}
-		if rq.quotaMonitor != nil && !controller.WaitForCacheSync("resource quota", stopCh, rq.quotaMonitor.IsSynced) {
+		// wait for caches to fill for a while (our sync period).
+		// this protects us from deadlocks where available resources changed and one of our informer caches will never fill.
+		// informers keep attempting to sync in the background, so retrying doesn't interrupt them.
+		// the call to resyncMonitors on the reattempt will no-op for resources that still exist.
+		// note that workers stay paused until we successfully resync.
```
Comment (smarterclayton) [inline pkg/controller/resourcequota/resource_quota_controller.go]: when we pause the workers, what's the actual implication for everyone above?  will admission block?

File: pkg/controller/resourcequota/resource_quota_controller.go [hunk 9]
```diff
@@ -437,8 +437,14 @@ func (rq *ResourceQuotaController) Sync(discoveryFunc NamespacedResourcesFunc, p
...
+		if rq.quotaMonitor != nil && !controller.WaitForCacheSync("resource quota", waitForStopOrTimeout(stopCh, period), rq.quotaMonitor.IsSynced) {
 			utilruntime.HandleError(fmt.Errorf("timed out waiting for quota monitor sync"))
+			return
```
Comment (smarterclayton) [inline pkg/controller/resourcequota/resource_quota_controller.go]: should we report more info in this utilruntime error?

File: pkg/controller/resourcequota/resource_quota_controller.go [hunk 10]
```diff
@@ -464,6 +470,19 @@ func printDiff(oldResources, newResources map[schema.GroupVersionResource]struct
...
 
+// waitForStopOrTimeout returns a stop channel that closes when the provided stop channel closes or when the specified timeout is reached
+func waitForStopOrTimeout(stopCh <-chan struct{}, timeout time.Duration) <-chan struct{} {
+	stopChWithTimeout := make(chan struct{})
+	go func() {
+		select {
+		case <-stopCh:
+		case <-time.After(timeout):
+		}
+		close(stopChWithTimeout)
```
Comment (smarterclayton) [inline pkg/controller/resourcequota/resource_quota_controller.go]: defer this, you could panic if time.After can't allocate.

File: pkg/controller/resourcequota/resource_quota_controller_test.go (hunk 2 above)
Comment (smarterclayton) [reply pkg/controller/resourcequota/resource_quota_controller_test.go]: won't that flake?  of course, time can flake.

File: pkg/controller/resourcequota/resource_quota_controller.go [hunk 11]
```diff
@@ -321,22 +322,25 @@ func (rq *ResourceQuotaController) syncResourceQuotaFromKey(key string) (err err
...
 	}
 	hardLimits := quota.Add(v1.ResourceList{}, resourceQuota.Spec.Hard)
 
+	errors := []error{}
+
 	newUsage, err := quota.CalculateUsage(resourceQuota.Namespace, resourceQuota.Spec.Scopes, hardLimits, rq.registry, resourceQuota.Spec.ScopeSelector)
 	if err != nil {
-		return err
+		// if err is non-nil, remember it to return, but continue updating status with any resources in newUsage
+		errors = append(errors, err)
```
Comment (smarterclayton) [inline pkg/controller/resourcequota/resource_quota_controller.go]: omg hard to believe we missed this

File: plugin/pkg/admission/resourcequota/controller.go [hunk 12]
```diff
@@ -703,8 +703,12 @@ func prettyPrintResourceNames(a []corev1.ResourceName) string {
 }
 
 // hasUsageStats returns true if for each hard constraint there is a value for its current usage
-func hasUsageStats(resourceQuota *corev1.ResourceQuota) bool {
+func hasUsageStats(resourceQuota *corev1.ResourceQuota, interestingResources []corev1.ResourceName) bool {
```
Comment (smarterclayton) [inline plugin/pkg/admission/resourcequota/controller.go]: ugh I can't believe we got away without this for so long

File: pkg/controller/resourcequota/resource_quota_controller.go (hunk 8 above)
Comment (liggitt) [reply pkg/controller/resourcequota/resource_quota_controller.go]: this is the controller, reconciliation would pause. this comment is not actually correct, it's left from the copy from the GC controller, where we do stay paused for safety

File: pkg/quota/v1/generic/evaluator.go (hunk 4 above)
Comment (liggitt) [reply pkg/quota/v1/generic/evaluator.go]: goal was to avoid permanently contending on informer.HasSynced() once it goes true, so this ratchets a local boolean to true in a threadsafe way

File: pkg/controller/resourcequota/resource_quota_controller.go (hunk 6 above)
Comment (liggitt) [reply pkg/controller/resourcequota/resource_quota_controller.go]: no reason, switched to %v

File: pkg/controller/resourcequota/resource_quota_controller.go (hunk 9 above)
Comment (liggitt) [reply pkg/controller/resourcequota/resource_quota_controller.go]: there's not a lot of detail to report here... the other logging adds info about what was not yet synced

File: pkg/controller/resourcequota/resource_quota_controller.go (hunk 7 above)
Comment (liggitt) [reply pkg/controller/resourcequota/resource_quota_controller.go]: every 30 seconds. 99% of the time, resources haven't changed, so we return on line 430

**Comment by liggitt** [comment]
comments addressed

File: pkg/quota/v1/generic/evaluator.go [hunk 13]
```diff
@@ -33,15 +34,74 @@ import (
 // InformerForResourceFunc knows how to provision an informer
 type InformerForResourceFunc func(schema.GroupVersionResource) (informers.GenericInformer, error)
 
-// ListerFuncForResourceFunc knows how to provision a lister from an informer func
+// ListerFuncForResourceFunc knows how to provision a lister from an informer func.
+// The lister returns errors until the informer has synced.
```
Comment (yliaog) [inline pkg/quota/v1/generic/evaluator.go]: nice to have a unit test for it

File: pkg/controller/resourcequota/resource_quota_controller_test.go (hunk 2 above)
Comment (liggitt) [reply pkg/controller/resourcequota/resource_quota_controller_test.go]: the point of this PR is that sync won't block...

File: pkg/quota/v1/resources.go [hunk 14]
```diff
@@ -211,6 +212,18 @@ func Intersection(a []corev1.ResourceName, b []corev1.ResourceName) []corev1.Res
 	return result
 }
 
+// Difference returns the list of resources resulting from a-b
+func Difference(a []corev1.ResourceName, b []corev1.ResourceName) []corev1.ResourceName {
```
Comment (smarterclayton) [inline pkg/quota/v1/resources.go]: This is a fairly expensive function - three map allocations and then the resource array.  Even though it's the error case this could be cheaper.

File: pkg/quota/v1/generic/evaluator.go [hunk 15]
```diff
@@ -33,15 +34,74 @@ import (
...
 	return func(gvr schema.GroupVersionResource) (cache.GenericLister, error) {
 		informer, err := f(gvr)
 		if err != nil {
 			return nil, err
 		}
-		return informer.Lister(), nil
+		synced := &atomic.Value{}
+		synced.Store(false)
+		return &protectedLister{
+			func() bool {
```
Comment (smarterclayton) [inline pkg/quota/v1/generic/evaluator.go]: Would probably prefer field identifiers here

**Comment by smarterclayton** [comment]
Just a couple of things.

File: pkg/quota/v1/resources.go (hunk 14 above)
Comment (liggitt) [reply pkg/quota/v1/resources.go]: rewrote with a single alloc (and rewrote `Intersection` to do a single alloc, and `Contains` to do zero allocs), and added tests

**Comment by liggitt** [comment]
comments addressed

File: pkg/quota/v1/resources.go [hunk 16]
```diff
@@ -201,13 +208,30 @@ func ContainsPrefix(prefixSet []string, item corev1.ResourceName) bool {
 
 // Intersection returns the intersection of both list of resources
```
Comment (yliaog) [inline pkg/quota/v1/resources.go]: deduped, and sorted

File: pkg/quota/v1/resources_test.go [hunk 17]
```diff
@@ -319,3 +320,93 @@ func TestIsNegative(t *testing.T) {
 		}
 	}
 }
+
+func TestIntersection(t *testing.T) {
```
Comment (yliaog) [inline pkg/quota/v1/resources_test.go]: is it worthwhile to test the new behavior in CalculateUsage?

File: plugin/pkg/admission/resourcequota/controller.go [hunk 18]
```diff
@@ -703,8 +703,12 @@ func prettyPrintResourceNames(a []corev1.ResourceName) string {
 }
 
 // hasUsageStats returns true if for each hard constraint there is a value for its current usage
```
Comment (yliaog) [inline plugin/pkg/admission/resourcequota/controller.go]: add comment about the new parameter interestingResources?

File: pkg/controller/resourcequota/resource_quota_controller.go [hunk 19]
```diff
@@ -320,22 +322,25 @@ func (rq *ResourceQuotaController) syncResourceQuotaFromKey(key string) (err err
 // syncResourceQuota runs a complete sync of resource quota status across all known kinds
 func (rq *ResourceQuotaController) syncResourceQuota(resourceQuota *v1.ResourceQuota) (err error) {
 	// quota is dirty if any part of spec hard limits differs from the status hard limits
-	dirty := !apiequality.Semantic.DeepEqual(resourceQuota.Spec.Hard, resourceQuota.Status.Hard)
+	statusLimitsDirty := !apiequality.Semantic.DeepEqual(resourceQuota.Spec.Hard, resourceQuota.Status.Hard)
```
[the remark this answers is not in the document]
Comment (liggitt) [reply pkg/controller/resourcequota/resource_quota_controller.go]: left from an earlier iteration that structured things differently, but the more specific variable name doesn't bother me

**Comment by tnozicka** [comment]
/hold
(just until you fix the verify job, so it doesn't spam with retests)

File: pkg/quota/v1/resources_test.go (hunk 17 above)
Comment (liggitt) [reply pkg/quota/v1/resources_test.go]: it's tested in `TestSyncResourceQuota`

**Comment by liggitt** [comment]
fixed bazel error, should be all set now

File: pkg/quota/v1/resources.go [hunk 20]
```diff
@@ -199,15 +206,32 @@ func ContainsPrefix(prefixSet []string, item corev1.ResourceName) bool {
...
-// Intersection returns the intersection of both list of resources
+// Intersection returns the intersection of both list of resources, deduped and sorted
 func Intersection(a []corev1.ResourceName, b []corev1.ResourceName) []corev1.ResourceName {
-	setA := ToSet(a)
-	setB := ToSet(b)
-	setC := setA.Intersection(setB)
-	result := []corev1.ResourceName{}
-	for _, resourceName := range setC.List() {
-		result = append(result, corev1.ResourceName(resourceName))
+	result := make([]corev1.ResourceName, 0, len(a))
```
Comment (tedyu) [inline pkg/quota/v1/resources.go]: Current code has complexity O(M*N)

Can we do this:
```
setA := ToSet(a)
for _, item := range b {
  if (setA.Has(item)) {
    result = append(result, item)
  }
}
```
The complexity is O(M+N).

File: pkg/quota/v1/resources.go [hunk 21]
```diff
@@ -199,15 +206,32 @@ func ContainsPrefix(prefixSet []string, item corev1.ResourceName) bool {
...
+		result = append(result, item)
 	}
+	sort.Slice(result, func(i, j int) bool { return result[i] < result[j] })
+	return result
+}
+
+// Difference returns the list of resources resulting from a-b, deduped and sorted
+func Difference(a []corev1.ResourceName, b []corev1.ResourceName) []corev1.ResourceName {
+	result := make([]corev1.ResourceName, 0, len(a))
+	for _, item := range a {
```
Comment (tedyu) [inline pkg/quota/v1/resources.go]: Can we do this:
```
setA := ToSet(a)
for _, item := range b {
  if (!setA.Has(item)) {
    result = append(result, item)
  }
}
```
Similar operation for finding elements from a which are not in b

The complexity is O(M+N)

File: pkg/quota/v1/resources.go (hunk 20 above)
Comment (liggitt) [reply pkg/quota/v1/resources.go]: I'm not opposed but would like to know the size at which the different becomes meaningful. Avoiding allocations is useful and iterating over small lists is not problematic.

Comment (tedyu) [reply pkg/quota/v1/resources.go]: This is my understanding:
without dynamic code (which switches algorithm according to input sizes), we should be prepared for large input sizes where performance becomes first concern (the additional memory is linear in input size).

If the input sizes are small, either approach is acceptable.

So I would opt for the version I proposed above.

Comment (tedyu) [reply pkg/quota/v1/resources.go]: We can change the return type of ResourceNames to map[corev1.ResourceName]struct{}.
This way, by the time Intersection is called, it has two Sets available - facilitating the above algorithms.
@liggitt 
What do you think ?
