### PR TITLE
check containerd as well as docker-containerd

### LINKED ISSUE #97565: docker-containerd have renamed to containerd, but EnsureDockerInContainer check not update
**What happened**:
docker-containerd have renamed to containerd, but EnsureDockerInContainer check not update,so it not work

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/container_manager_linux.go#L74
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/container_manager_linux.go#L843

**What you expected to happen**:
Is this check still needed？

**How to reproduce it (as minimally and precisely as possible)**:
no need

**Anything else we need to know?**:

**Environment**: 
- Kubernetes version (use `kubectl version`): 
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`): 
- Install tools: 
- Network plugin and version (if this is a network-related bug): 
- Others:

### PR DESCRIPTION
**Pull request by pacoxu**
**What type of PR is this?**
/kind bug
/sig node

**What this PR does / why we need it**:
- dockerd pidfile: dockerd option --pidfile can specify path to use for daemon PID file, pid file path is default "/var/run/docker.pid" . Refer to [docker options](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon:~:text=%2Dp%2C%20%2D%2Dpidfile%20string,for%20daemon%20PID%20file%20(default%20%22%2Fvar%2Frun%2Fdocker.pid%22)).
- docker-containerd is renamed to containerd in the new release of docker.
- containerd.pid is removed(https://github.com/moby/moby/issues/23069#issuecomment-222270659):  moby/moby#23069  when contained started separately with dockerd, dockerd can start with `--containerd` option to bind the socket. Then no PID for containerd. 

According to [EndOfLife Docker Versions](https://success.mirantis.com/article/maintenance-lifecycle#endoflifeeoldockerengineversions)
As the old version docker is not supported. So use the current default behavior.
- no containerd pid
- user containerd as process name

**Which issue(s) this PR fixes**:
Fixes #97565

**Special notes for your reviewer**:
However, this may be removed later as docker-shim is deprecated.

**Does this PR introduce a user-facing change?**:
```release-note
In the method that ensures that the docker and containerd are in the correct containers with the proper OOM score set up, fixed the bug of identifying containerd process.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

### CODE REVIEW

File: pkg/kubelet/cm/container_manager_linux.go [hunk 1]
```diff
@@ -69,14 +69,14 @@ import (
...
 
 const (
-	dockerProcessName     = "dockerd"
-	dockerPidFile         = "/var/run/docker.pid"
-	containerdProcessName = "docker-containerd"
-	containerdPidFile     = "/run/docker/libcontainerd/docker-containerd.pid"
-	maxPidFileLength      = 1 << 10 // 1KB
+	dockerProcessName = "dockerd"
+	dockerPidFile     = "/var/run/docker.pid"
+	containerdPidFile = "/run/docker/libcontainerd/docker-containerd.pid"
```
Comment (dims) [inline pkg/kubelet/cm/container_manager_linux.go:74]: is this still the location of the pid file?

Comment (pacoxu) [reply pkg/kubelet/cm/container_manager_linux.go:74]: AFAIK，the pid file is removed. however， I think we should check it for backward compatible.

File: pkg/kubelet/cm/container_manager_linux.go [hunk 2]
```diff
@@ -544,10 +544,10 @@ func (cm *containerManagerImpl) setupNode(activePods ActivePodsFunc) error {
 	return nil
 }
 
-func getContainerNameForProcess(name, pidFile string) (string, error) {
-	pids, err := getPidsForProcess(name, pidFile)
+func getContainerNameForProcess(names []string, pidFile string) (string, error) {
```
Comment (bartosh) [inline pkg/kubelet/cm/container_manager_linux.go:547]: What's the point to change type of the name parameter to slice if this function is called with only one process name?
```
cont, err := getContainerNameForProcess([]string{dockerProcessName}, dockerPidFile)
...
cont, err := getContainerNameForProcess([]string{dockerProcessName}, dockerPidFile)
```

Comment (pacoxu) [reply pkg/kubelet/cm/container_manager_linux.go:547]: @bartosh I want it would work for both 'containerd' and 'docker-containerd' in this case.

Comment (bartosh) [reply pkg/kubelet/cm/container_manager_linux.go:547]: @pacoxu Can you show where do you call getContainerNameForProcess with 'containerd' and 'docker-containerd'?

File: pkg/kubelet/cm/container_manager_linux.go [hunk 3]
```diff
@@ -69,14 +69,14 @@ import (
...
-	containerdPidFile     = "/run/docker/libcontainerd/docker-containerd.pid"
-	maxPidFileLength      = 1 << 10 // 1KB
+	dockerProcessName = "dockerd"
+	dockerPidFile     = "/var/run/docker.pid"
+	containerdPidFile = "/run/docker/libcontainerd/docker-containerd.pid"
+	maxPidFileLength  = 1 << 10 // 1KB
 )
 
 var (
+	containerdProcessNames = []string{"docker-containerd", "containerd"}
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/cm/container_manager_linux.go:79]: what version the switch happened? Are we still supporting Docker that far back?

Comment (pacoxu) [reply pkg/kubelet/cm/container_manager_linux.go:79]: @SergeyKanzhelev  I think it happened in docker-ce 17.11.
containerd started to run isolatedly after that version.

I have serverl clusters:
- docker 17.03 is using "docker-containerd"
- docker 18.09 & docker 19.03 & 20.10 are using "contained"

Even we don't support dockershim, the kubelet can communicate with containerd directly even we installed docker on the node as well. As I know, kubeadm will not drop all docker supports.

Comment (SergeyKanzhelev) [reply pkg/kubelet/cm/container_manager_linux.go:79]: makes sense. My sense was that it happened so long ago =). Thank you for confirming!

Comment (pacoxu) [reply pkg/kubelet/cm/container_manager_linux.go:79]: Another easy change on this would be just renaming it to `containerd` as the process name `docker-containerd` is so old.

Comment (SergeyKanzhelev) [reply pkg/kubelet/cm/container_manager_linux.go:79]: hm, looking at Docker support matrix, it looks like docker 17.03 is [not supported](https://success.mirantis.com/article/maintenance-lifecycle#endoflifeeoldockerengineversions:~:text=End%20of%20Life%20(EOL)%20Docker%20Engine%20Versions). So perhaps yes, simpler fix would be better

**Comment by pacoxu** [comment]
Thanks @SergeyKanzhelev , Fixed.

According to https://success.mirantis.com/article/maintenance-lifecycle#endoflifeeoldockerengineversions 
As the old version docker is not supported. Just change the processName here would be OK.

File: pkg/kubelet/cm/container_manager_linux.go (hunk 2 above)
Comment (pacoxu) [reply pkg/kubelet/cm/container_manager_linux.go]: per comments, changed process name only.

File: pkg/kubelet/cm/container_manager_linux.go [hunk 4]
```diff
@@ -71,8 +71,7 @@ import (
 const (
 	dockerProcessName     = "dockerd"
 	dockerPidFile         = "/var/run/docker.pid"
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/cm/container_manager_linux.go:73]: Maybe add a comment here that this is the best effort lookup as pid file may be overridden: https://docs.docker.com/engine/reference/commandline/dockerd/#daemon:~:text=%2Dp%2C%20%2D%2Dpidfile%20string,for%20daemon%20PID%20file%20(default%20%22%2Fvar%2Frun%2Fdocker.pid%22)

File: pkg/kubelet/cm/container_manager_linux.go [hunk 5]
```diff
@@ -841,7 +840,7 @@ func EnsureDockerInContainer(dockerAPIVersion *utilversion.Version, oomScoreAdj
 	type process struct{ name, file string }
 	dockerProcs := []process{{dockerProcessName, dockerPidFile}}
 	if dockerAPIVersion.AtLeast(containerdAPIVersion) {
-		dockerProcs = append(dockerProcs, process{containerdProcessName, containerdPidFile})
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/cm/container_manager_linux.go:844]: it is a good practice to explain the magic constants, even `""`. Maybe say that in many cases `containerd` is not started by docker and specified using [`--containerd` option](https://docs.docker.com/engine/reference/commandline/dockerd/) so there is no pid file available. See comment here: https://github.com/moby/moby/issues/23069#issuecomment-222270659

**Comment by pacoxu** [comment]
@SergeyKanzhelev  Thanks a lot. Appreciate your detailed research on backgrounds.
Updated the comments and the description of this PR.

**Comment by SergeyKanzhelev** [comment]
/lgtm

please update the release notes to something like this:

replace this:
> docker PID detection needs to check process name containerd instead of docker-containerd.

with this:
> In the method that ensures that the docker and containerd are in the correct containers with the proper OOM score set up, fixed the bug of identifying containerd process.

**Comment by pacoxu** [comment]
@SergeyKanzhelev  thanks. Updated

**Comment by pacoxu** [comment]
/retest
flake😓
