### PR TITLE
handle job complete update delayed event

### LINKED ISSUE #130103: Job controller's race condition - Pod finalizer removal and job uncounted status update should work in separate reconcile
### What happened?

Job controller accidentally created two pods even if the Job spec specifies in a busy cluster:

```
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 86400
  backoffLimit: 0
```

This is happening because when job controller is calculating the succeed pods, it's taking three inputs ([here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L892)):

1. The completion count from `Job.status.succeeded`
2. The existing succeed pods (if the finalizer is still present)
3. The uncounted completion count from `Job.status.uncountedTerminatedPods`

Due to the current implementation where the job controller is refreshing both (2) and (3) in the same reconcile/sync process:

> https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L1165-L1167

The job controller may miscount the succeeded pods when the watch event for (3) hasn't reach the controller. A delayed watch event is fairly likely to happened in a busy cluster.

### What did you expect to happen?

The better implementation should be handling the refreshing of (2) and (3) in separate reconcile process:

(1) in the 1st reconcile, job controller should only refresh `Job.status.uncountedTerminatedPods` while preserving the finalizers on the pods
(2) in the 2nd reconcile which is triggered by (1), job controller is safe to remove the finalizers from pods

### How can we reproduce it (as minimally and precisely as possible)?

Any trivial job with 1 completion on a busy cluster should be able to reproduce the issue

### Anything else we need to know?

_No response_

### Kubernetes version

All k8s versions I assume

### Cloud provider

Any

### OS version

Any

### Install tools

_No response_

### Container runtime (CRI) and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by kmala**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #130103

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug in Job controller which could result in creating unnecessary Pods for a Job which is already
recognized as finished (successful or failed).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/job/tracking_utils.go [hunk 1]
```diff
@@ -151,3 +151,26 @@ func isFinishedPodWithTrackingFinalizer(pod *v1.Pod) bool {
 	}
 	return (pod.Status.Phase == v1.PodFailed || pod.Status.Phase == v1.PodSucceeded) && hasJobTrackingFinalizer(pod)
 }
+
+type jobUIDCache struct {
```
Comment (mimowo) [inline pkg/controller/job/tracking_utils.go:155]: The implementation looks ok, but I would prefer to use some built-in primitives. Can we use the store as for expectations or backoffStore? Or sync.Map maybe?

File: pkg/controller/job/job_controller.go [hunk 2]
```diff
@@ -820,7 +828,6 @@ func (jm *Controller) syncJob(ctx context.Context, key string) (rErr error) {
 		}
 		return err
 	}
-
```
Comment (mimowo) [inline pkg/controller/job/job_controller.go:823]: nit: revert formatting changes to avoid distractions

File: pkg/controller/job/job_controller.go [hunk 3]
```diff
@@ -1304,6 +1316,7 @@ func (jm *Controller) trackJobStatusAndRemoveFinalizers(ctx context.Context, job
 		}
 		if jobFinished {
 			jm.recordJobFinished(jobCtx.job, jobCtx.finishedCondition)
+			jm.completedJobStore.add(jobCtx.job.UID)
```
Comment (mimowo) [inline pkg/controller/job/job_controller.go:1319]: This adds it regardless if completed successfully or failed. So, is there a similar issue for failed pods? 

What would be the pros & cons for accounting for succeeded & failed vs only succeeded?

If we want to account also for failed jobs then I would suggest to call it `finishedJobStore`.

**Review by mimowo — COMMENTED** [review]
Since the Job's final state is correct anyway, I'm wondering what is the practical impact of creating the unnecessary pod(s) :
1. performance hit due to creating the extra pod(s) occasionally
2. complicated debugging because it adds additional distraction? For example, some 3rd party e2e testing frameworks may flake because they would assume one pod, and require debugging why they flaked.

Intuitively I feel like (2.) is more relevant here, but maybe you have some data to back up (1.) is a problem too?

**Comment by kmala** [comment]
>Since the Job's final state is correct anyway, I'm wondering what is the practical impact of creating the unnecessary pod(s) 
> 1) performance hit due to creating the extra pod(s) occasionally
>2) complicated debugging because it adds additional distraction? For example, some 3rd party e2e testing frameworks may flake because they would assume one pod, and require debugging why they flaked.
Intuitively I feel like (2.) is more relevant here, but maybe you have some data to back up (1.) is a problem too?

Its mostly 2 and also this would impact the correctness of the application unless the application handles executing the same job twice with same parameters.

File: pkg/controller/job/job_controller.go (hunk 3 above)
Comment (kmala) [reply pkg/controller/job/job_controller.go]: Since the issue is because of race between the events missing and doesn't happen frequently, we won't observe for failed  jobs unless we have a lot of jobs constantly failing. Because of that we haven't observed for the failed jobs but based on the code it should be the same for it also.

**Comment by mimowo** [comment]
Since this PR is user-facing (fixing a bug) please add a release note, maybe something like:
```
Fix a bug in Job controller which could result in creating unnecessary Pods for a Job which is already
recognized as successful.
```

File: pkg/controller/job/job_controller_test.go [hunk 4]
```diff
@@ -2879,6 +2880,110 @@ func TestSingleJobFailedCondition(t *testing.T) {
...
+		schema.GroupVersionResource{Version: "v1", Resource: "pods"},
+		schema.GroupVersionKind{Version: "v1", Kind: "Pod"},
+		"default")
+	if err != nil {
+		t.Fatalf("Unexpected error when fetching pods %v", err)
+	}
+	// manually adding the just-created pod from fake clientset memory to informer cache because informer is not started.
+	// we are updating the pod status to succeeded which should update the job status to succeeded and remove the finalizer of the pod.
+	justCreatedPod := podList.(*v1.PodList).Items[0]
+	fmt.Printf("pod is %v\n", podList.(*v1.PodList).Items[0])
```
Comment (mimowo) [inline pkg/controller/job/job_controller_test.go:2919]: use t.Log

File: pkg/controller/job/job_controller.go (hunk 3 above)
Comment (mimowo) [reply pkg/controller/job/job_controller.go]: Would it be feasible to repro the bug for a filing job in the new unit test? Then we could parametrize the test with the status of the Pod, and we would have an evidence this is needed indeed, other than static code analysis.

File: pkg/controller/job/job_controller_test.go [hunk 5]
```diff
@@ -2879,6 +2880,110 @@ func TestSingleJobFailedCondition(t *testing.T) {
...
+
+	// add the updated pod from the fake clientset memory to informer cache because informer is not started.
+	podList, err = clientSet.Tracker().List(
+		schema.GroupVersionResource{Version: "v1", Resource: "pods"},
+		schema.GroupVersionKind{Version: "v1", Kind: "Pod"},
+		"default")
+	if err != nil {
+		t.Fatalf("Unexpected error when fetching pods %v", err)
+	}
+	fmt.Printf("pod is %v\n", podList.(*v1.PodList).Items[0])
```
Comment (mimowo) [inline pkg/controller/job/job_controller_test.go:2951]: nit use t.Log

File: pkg/controller/job/job_controller_test.go [hunk 6]
```diff
@@ -2879,6 +2880,110 @@ func TestSingleJobFailedCondition(t *testing.T) {
...
+		"default", "")
+	if err != nil {
+		t.Fatalf("Unexpected error when deleting pod to indexer %v", err)
+	}
+
+	err = jm.syncJob(ctx, testutil.GetKey(job1, t))
+	if err != nil {
+		t.Fatalf("Unexpected error when syncing jobs %v", err)
+	}
+	time.Sleep(time.Second)
```
Comment (mimowo) [inline pkg/controller/job/job_controller_test.go:2972]: IIUC this is need to give time to the Job controller to create the pod when there is a bug. Can you check if 100ms it enough to repro this reliably?

**Comment by mimowo** [comment]
> Its mostly 2 and also this would impact the correctness of the application unless the application handles executing the same job twice with same parameters.

I see, I think this would justify the fix, but IIUC this is not a regression, so unlikely to be cherry-picked.

cc @atiratree for additional review

File: pkg/controller/job/job_controller_test.go [hunk 7]
```diff
@@ -2879,6 +2880,110 @@ func TestSingleJobFailedCondition(t *testing.T) {
...
+	updatedPod := podList.(*v1.PodList).Items[0]
+	updatedPod.Status.Phase = v1.PodSucceeded
+	err = podIndexer.Add(&updatedPod)
+	if err != nil {
+		t.Fatalf("Unexpected error when adding pod to indexer %v", err)
+	}
+
+	// removing the just created pod from fake clientset memory inorder for the sync job to succeed if creating a new pod because of bug
+	// but the pod will remain inside informer cache
+	err = clientSet.Tracker().Delete(
```
Comment (atiratree) [inline pkg/controller/job/job_controller_test.go:2961]: This test does not fully show or explain where the race bug is and how we reproduce it. If we delete a pod in this place we simply reset the state to the beginning, since no updates to the job object have occurred (no working informers).

The bug claims the race occurs between setting the `Job.status.uncountedTerminatedPods` and the `Job.status.succeeded` AFAIK.

We need a proper test first (preferably E2E) and race cause analysis before accepting a fix.

Comment (kmala) [reply pkg/controller/job/job_controller_test.go:2961]: >If we delete a pod in this place we simply reset the state to the beginning, since no updates to the job object have occurred (no working informers).

We are not resetting the state because this delete doesn't update the informer cache. This delete is just made just so that we can successfully create a new pod(in case of bug) as its also created with the same name. 

>The bug claims the race occurs between setting the Job.status.uncountedTerminatedPods and the Job.status.succeeded AFAIK.

The bug is if the job controller has removed the finalizer for the pod and updated the job status to succeeded in a sync loop, but the next time controller runs sync loop for the job because of pod update event(removal of finalizer) after 1 sec which is hard coded. If the job completed update event is not yet received(delayed) during the second sync it would create a new pod. 

 >We need a proper test first (preferably E2E) and race cause analysis before accepting a fix.
 
we can't write e2e test from what i know because this is a race which needs specific event to be delayed. Please let me know if above comments doesn't clear your doubts regarding the unit test and cause of the issue.

Comment (atiratree) [reply pkg/controller/job/job_controller_test.go:2961]: > We are not resetting the state because this delete doesn't update the informer cache. This delete is just made just so that we can successfully create a new pod(in case of bug) as its also created with the same name.

> we can't write e2e test from what i know because this is a race which needs specific event to be delayed. Please let me know if above comments doesn't clear your doubts regarding the unit test and cause of the issue.

We don't need an e2e test if we can faithfully emulate the jobset reconciliation and pod changes. Which is not the case as far as I can see. The new pod creation should be blocked by `jobCtx.uncounted.succeeded` and thus we need to show where the gap is.

> The bug is if the job controller has removed the finalizer for the pod and updated the job status to succeeded in a sync loop, but the next time controller runs sync loop for the job because of pod update event(removal of finalizer) after 1 sec which is hard coded. If the job completed update event is not yet received(delayed) during the second sync it would create a new pod.

Can you please describe the status transitions and state of the cache in steps t0-tx? And which part is inconsistent/buggy?

And if the main problem is really that we haven't received a job update event in 1s when the cluster is congested, isn't this a wider problem and not just when we complete a job?

Comment (atiratree) [reply pkg/controller/job/job_controller_test.go:2961]: We could also explore creating E2E that reproduces the issue only with some probability. Just to test the thesis/fix without committing it to the code base.

Comment (mimowo) [reply pkg/controller/job/job_controller_test.go:2961]: Ok, I think I know understand the issue. Basically Job controller does the following:
1. update `status.uncountedTerminatedPods.succeeded`
2. remove finalizers from Pods (after removal the are no longer counted as newSuccedededPods
3. update `status.Succeeded`, clear `status.uncountedTerminatedPods.succeeded`, and add the "SuccessCriteriaMet" and "Complete" conditions

All of the above may happen in one sync, and result in enqueuing another sync. In that case, the next sync is computing the formula:

`jobCtx.succeeded = job.Status.Succeeded + int32(len(newSucceededPods)) + int32(len(jobCtx.uncounted.succeeded))`

Now, if the Job events are delayed vs Pod events, it may observe (events from 2. received, but event from 1. and 3. not), then we may observe: `job.Status.Succeeded=0`, `len(newSucceededPods))=0`, `len(jobCtx.uncounted.succeeded)=0`, resulting in Pod creation.

**I fully agree that the unit test is hard to read and interpret.** 

However, adding an e2e or integration test is tricky, because the next sync is delayed by 1s. So, you need to have the Job events delayed by 1s, while the Pod events are received within 1s. This is hard to make reproducible.

So, I would suggest to try to repro in integration test, but expose [syncJobBatchPeriod](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L63) setting it to 1ms. This will make it much more likely to reproduce. We also manipulate some other vars in the integration tests , like [here](https://github.com/kubernetes/kubernetes/blob/be32ca61a65c0a997396c10ca78487d6484dc735/test/integration/job/job_test.go#L262).

Let me know your thoughts @atiratree @kmala

Comment (kmala) [reply pkg/controller/job/job_controller_test.go:2961]: Thanks @mimowo the issue is exactly as you explained. I will try to write more comments to see if i can make the unit test better. I don't think changing [syncJobBatchPeriod](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L63) will help in this case as that is used how fast/slow we want to process an event but the issue when the event itself is delayed causing stale data in informer cache. I will check the other integration tests to see if its possible to write a test for this one.

Comment (mimowo) [reply pkg/controller/job/job_controller_test.go:2961]: > as that is used how fast/slow we want to process an event 

IIUC, the constant is rather used to determine the interval between Reconciles (syncs). So, if the event is delayed currently in informer by 500ms, you may never hit test failure (without modifying the constant), because the next reconcile will be after the event is propagated and the informer caches are updated. So, reducing the constant can make the integration test more sensitive to even shorter delays IIUC. At least worth trying imo.

Comment (kmala) [reply pkg/controller/job/job_controller_test.go:2965]: added the integration test and also added more comments to the unit test. Can you please review again?

File: test/integration/job/job_test.go [hunk 8]
```diff
@@ -4048,6 +4050,69 @@ func TestNodeSelectorUpdate(t *testing.T) {
 
 }
 
+// TestDelayedJobUpdateEvent tests that a Job that only executes one Pod even when
+// the job events are delayed. This test verfies the finishedJobStore is working
+// correctly and preventing from job controller creating a new pod if the job complete
+// even is delayed.
+func TestDelayedJobUpdateEvent(t *testing.T) {
```
Comment (mimowo) [inline test/integration/job/job_test.go:4057]: How often the test fails when executed locally without the fix? Also, how does the frequency of failing depend on `SyncJobBatchPeriod` from your experiments?

Comment (kmala) [reply test/integration/job/job_test.go:4057]: Since i am making sure the job event is always delayed, the test fails always without the code changes. The correlation between `SyncJobBatchPeriod` and the failure is that the job update events should be delayed by at least  `SyncJobBatchPeriod` for the failure to happen. If its more it always fails and if its less it never fails from my testing.

Comment (mimowo) [reply test/integration/job/job_test.go:4057]: I see, thanks to the transformer for the informer. Clever.

Comment (mimowo) [reply test/integration/job/job_test.go:4057]: TBH I like this test, in that case I would be in favor of even dropping the unit test which is very hard to read / understand. wdyt? Let me also ask @atiratree for opinion.

Would it be feasible to add the analogous integration test demonstrating the problem with the failed pod - unnecessary pod is not created in case of a job exceeding backoffLimit? This was also may ask in the other [comment](https://github.com/kubernetes/kubernetes/pull/130333#discussion_r1984568395).

Comment (kmala) [reply test/integration/job/job_test.go:4057]: yeah, i can work on adding a test for the failed pod. i understand the unit test is a bit hard to read for someone who doesn't have context and can remove it.

Comment (atiratree) [reply test/integration/job/job_test.go:4057]: +1 for dropping the unit test. The integration test shows the problem well.

I am for parametrizing this test and adding more cases (e.g. failed pod).

Regarding the implementation, I think we catch the problem too late (when the job finishes).


IIUIC, the race happens here

https://github.com/kubernetes/kubernetes/blob/047e4c8e56b5c6a0466e4f1f1fdeca7e9a8de3d6/pkg/controller/job/job_controller.go#L1355

and here

https://github.com/kubernetes/kubernetes/blob/047e4c8e56b5c6a0466e4f1f1fdeca7e9a8de3d6/pkg/controller/job/job_controller.go#L1382

Since, we can have partial updates, we could have extra pods created before we mark the job finished.  We depend on atomicity (which is missing) here

https://github.com/kubernetes/kubernetes/blob/047e4c8e56b5c6a0466e4f1f1fdeca7e9a8de3d6/pkg/controller/job/job_controller.go#L1597

and here

https://github.com/kubernetes/kubernetes/blob/047e4c8e56b5c6a0466e4f1f1fdeca7e9a8de3d6/pkg/controller/job/job_controller.go#L1875

So, even if the pods are still present and have not been deleted, we ignore them because they miss the finalizer.

The other status updates seem atomic to me.

There are couple of things that could be done to fix this:
- We could just update the informer cache/store directly once we receive a result from the update status call. This seem the most straightforward and easiest thing to do. But I am not sure if there isn't any race on the apiserver side as well (e.g. getting cache update first before the client result). And it is probably an anti-pattern to touch the store.
- We could wait in the sync handler until the store is synced. Which is also not great since we would be blocking the worker.
- Short circuit and remove the finalizers in the next sync once the cache gets updated.
- Store the uncounted pods in the variable locally and compare the values in each sync with the job status.

I like the short circuit option the best ATM.

@mimowo @kmala WDYT?

Comment (mimowo) [reply test/integration/job/job_test.go:4057]: @atiratree I'm still not sure there is another issue, I remember giving this a lot of thought in the past and I could not see, the issue with finished jobs I was aware of, but never thought it would surface on a live cluster. As it surfaced I think we should fix.. 

If you suspect there is another more generic issue, then it would be good to come up with a scenario which would be the basis for reproduction in integration tests. At this moment, it seems like static code analysis, and I think we already have mechanism to fix the delayed pod even propagation for removal of finalizers using the expectations mechanism by `expectedRmFinalizers`. This sounds like your option (4.).

So, I would prefer to go with a simple fix, like in the current PR, unless we confirm there is some more generic issue which can be fixed with a single approach.

Comment (atiratree) [reply test/integration/job/job_test.go:4057]: I would not expect this current issue to come up as well, but it seems that with a big number of objects it can happen. IMO, the expectations are not enough as we remove them right after the finalizer removal so it is basically the same gate.

> If you suspect there is another more generic issue, then it would be good to come up with a scenario which would be the basis for reproduction in integration tests. 

Agree, we can look into that - the fix should be testable.

Comment (kmala) [reply test/integration/job/job_test.go:4057]: I don't think this is expected to happen in regular clusters. The cause of the issue atleast in my case is etcd defrag causing the event to be delayed and when the watch connection for pods and jobs are to different etcd servers, then only jobs event would be dealyed during the defrag. Even in that situation there has to be many jobs running for the race to occur and there should be a defrag just when the job is completed update happens.
There is work in etcd for grpc health check but not sure when that would be released.

 >Short circuit and remove the finalizers in the next sync once the cache gets updated.
 The reason i didn't go with approach is it would require more code changes and also i think it can impact performance when running at scale i think as the job need to wait for additional sync to be marked succesful.

Comment (atiratree) [reply test/integration/job/job_test.go:4057]: Thanks for the details @kmala. I think there can be other causes than etcd. I will try to find some time to come up with a reproducer.

> The reason i didn't go with approach is it would require more code changes and also i think it can impact performance when running at scale i think as the job need to wait for additional sync to be marked succesful.

I think this should not be a big issue, even if we use the default queue backoff which starts at 1s. But in most of the cases, the delay should equal only to the apiserver roundtrip, which should be fast.

Comment (mimowo) [reply test/integration/job/job_test.go:4057]: >  expectations are not enough as we remove them right after the finalizer removal so it is basically the same gate.

Actually, we decrement the finalizer expectations only after we observe the actual [pod event](https://github.com/kubernetes/kubernetes/blob/83bb5d570580a3f477737fec5c24ba8fc3554264/pkg/controller/job/job_controller.go#L373). So, they keep "in memory" the expectation about the incoming event. I think this is conceptually the same as in the PR, but regarding the finished job.

> I will try to find some time to come up with a reproducer.

This would be great, I prefer to not add code, or risk slowing down the execution only based on static code analysis, because static code analysis can easily miss some details.

Comment (kmala) [reply test/integration/job/job_test.go]: added the integration test for failed pod and also removed the unit test.

**Comment by mimowo** [comment]
These look like unreleated flakes, retrying
/test pull-kubernetes-e2e-kind
/test pull-kubernetes-node-e2e-containerd

File: test/integration/job/job_test.go [hunk 9]
```diff
@@ -4048,6 +4050,157 @@ func TestNodeSelectorUpdate(t *testing.T) {
 
 }
 
+// TestDelayedJobSucceededUpdateEvent tests that a Job only creates one Pod even when
+// the job success events are delayed. This test verfies the finishedJobStore is working
+// correctly and preventing from job controller creating a new pod if the job success
+// even is delayed.
+func TestDelayedJobSucceededUpdateEvent(t *testing.T) {
```
Comment (mimowo) [inline test/integration/job/job_test.go:4057]: I would suggest to try combining these two tests. Pros:
- most of the testing code is the duplicated, I think the asserts on metrics we could drop even to make alignment easier
- when combined it is clear they are conceptually testing the same bugfix
- performance, we only need one API server to run both tests

**Comment by mimowo** [comment]
Updating the proposal to reflect the  fix is also covering the  failed jobs.
/release-note-edit
```release-note
Fix a bug in Job controller which could result in creating unnecessary Pods for a Job which is already
recognized as finished (successful or failed).
```

**Comment by mimowo** [comment]
/lgtm
/approve
But before we merge I would like to yet get a pass from @atiratree ,
/hold

**Comment by mimowo** [comment]
/test pull-kubernetes-e2e-gce
unrelated flake

**Comment by atiratree** [comment]
@kmala sorry for the delay, I will try to revisit this week.

**Comment by atiratree** [comment]
I could not reproduce other failures.

Thanks a lot for the patience and the fix @kmala

/hold cancel
/triage accepted
/priority important-longterm

**Review by hashim21223445 — APPROVED** [review]
