### PR TITLE
Don't run TestCleanup that requires etcd on non linux+amd64 platforms

### LINKED ISSUE #112412: [Failing Test] periodic-kubernetes-unit-test-ppc64le, k8s.io/kubernetes/test/e2e/framework/internal/unittests/cleanup
### Which jobs are failing?

periodic-kubernetes-unit-test-ppc64le

### Which tests are failing?

k8s.io/kubernetes/test/e2e/framework/internal/unittests/cleanup: TestCleanup

### Since when has it been failing?

Probably since it was merged in https://github.com/kubernetes/kubernetes/pull/111998

### Testgrid link

https://k8s-testgrid.appspot.com/ibm-unit-tests-ppc64le#Periodic%20unit%20test%20suite%20on%20ppc64le

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

The error from build log trace is:
```
 klog.go:874: ERROR Unable to remove endpoints from kubernetes service: StorageError: key not found, Code: 1, Key: /05ffbd08-d55c-4234-a474-890da0df1095/registry/masterleases/127.0.0.1, ResourceVersion: 0, AdditionalErrorMsg: 
```
Please go through the above job for complete build log.

### Relevant SIG(s)

/sig testing

### PR DESCRIPTION
**Pull request by aojea**
/kind flake

#### What this PR does / why we need it:

- skip etcd unit test `test/e2e/framework/internal/unittests/cleanup/cleanup_test.go` on non fully supported architectures, etcd only fully support linux + amd64 https://etcd.io/docs/v3.5/op-guide/supported-platform/#support-tiers

Fixes: #112412

```release-note
NONE
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @pohly @sttts 

we can split the PR and disable the test on the architecture in a separate PR if you want.

Stefan for approval/review of the apiserver changes

File: cmd/kube-apiserver/app/testing/testserver.go [hunk 1]
```diff
@@ -214,11 +214,13 @@ func StartTestServer(t Logger, instanceOptions *TestServerInstanceOptions, custo
 
 	s.ServiceClusterIPRanges = "10.0.0.0/16"
 	s.Etcd.StorageConfig = *storageConfig
-	s.APIEnablement.RuntimeConfig.Set("api/all=true")
```
Comment (aojea) [inline cmd/kube-apiserver/app/testing/testserver.go:217]: this was not overridden by the flags, so it has always all the apis enabled, at least this was always present on the RuntimeConfig

File: test/e2e/framework/internal/unittests/cleanup/cleanup_test.go [hunk 2]
```diff
@@ -30,6 +30,7 @@ import (
 
 	"k8s.io/klog/v2"
 	"k8s.io/klog/v2/ktesting"
+	kubeapiservertesting "k8s.io/kubernetes/cmd/kube-apiserver/app/testing"
```
Comment (aojea) [inline test/e2e/framework/internal/unittests/cleanup/cleanup_test.go:33]: I've tested the build time and it was similar

File: test/e2e/framework/internal/unittests/cleanup/cleanup_test.go [hunk 3]
```diff
@@ -122,7 +122,17 @@ func TestCleanup(t *testing.T) {
 	logger, _ := ktesting.NewTestContext(t)
 	klog.SetLogger(logger)
 
-	apiServer := testapiserver.StartAPITestServer(t)
+	// disable some options to save some during bootstrap
```
Comment (pohly) [inline test/e2e/framework/internal/unittests/cleanup/cleanup_test.go:125]: Nit:

```suggestion
	// Disable some options to save some time during bootstrap.
```

"time" was missing. I also prefer full sentences with a final stop, because then it is possible to extend comments later on without having to rewrite the existing sentence.

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by aojea** [comment]
the verify failure is legit

**Comment by aojea** [comment]
well, it ran in 50sec

> {"Time":"2022-09-13T11:23:42.053737287Z","Action":"output","Package":"k8s.io/kubernetes/test/e2e/framework/internal/unittests/cleanup","Output":"ok  \tk8s.io/kubernetes/test/e2e/framework/internal/unittests/cleanup\t50.844s\n"}

periodic job shows it is always over 1 min https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit&include-filter-by-regex=internal%2Funit&graph-metrics=test-duration-minutes

**Comment by pohly** [comment]
> the verify failure is legit

I do not fully understand the purpose of https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/.import-restrictions.

It caused https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112416/pull-kubernetes-verify/1569641920047616000 to fail:
```
E0913 11:41:08.721878  236628 main.go:44] Error: Failed executing generator: some packages had errors:
errors in package "k8s.io/kubernetes/test/e2e/framework/internal/unittests/cleanup":
the following imports did not match any allowed prefix:
  k8s.io/kubernetes/pkg/api/endpoints/testing
  k8s.io/kubernetes/pkg/api/persistentvolume
...
```

First, a unit test should be allowed to depend on other packages than the framework itself because it won't affect the usability of the framework. Do we need a different `.import-restrictions` for `internal/unittests`?

Second, I have the impression that import-boss only complains about *direct* dependencies, but not *indirect* dependencies. The effect is that test/e2e/framework could not depend on k8s.io/kubernetes/cmd/kube-apiserver/app/testing directly (if I remember correctly), but after moving the code which used it to https://github.com/kubernetes/kubernetes/blob/master/test/utils/apiserver/testapiserver.go it was suddenly okay to depend on it indirectly.

According to https://github.com/kubernetes/kubernetes/pull/80496 which introduced the file, the goal was apparently to limit dependencies to those that are fine for package under staging (i.e. only other packages that are also under staging). This goal is no longer applicable and as it stands now, `.import-restrictions` seems to cause more problems than it solves (like having to work around dependencies as in https://github.com/kubernetes/kubernetes/compare/cb3e1cf5c67e2b3bc967f88c0b40009172c99aa7..74b54597d82f291158df0b92e2d93fd9ffc8b4c5).

@aojea: what do you think about removing it entirely?

**Comment by aojea** [comment]
> @aojea: what do you think about removing it entirely?

agree

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by pohly** [comment]
/assign @sttts

For a minor change in test/utils/apiserver/testapiserver.go.

File: cmd/kube-apiserver/app/testing/testserver.go (hunk 1 above)
Comment (liggitt) [reply cmd/kube-apiserver/app/testing/testserver.go:217]: `api/all` is not the default, this enables all alpha and beta APIs as well

File: test/e2e/framework/internal/unittests/cleanup/cleanup_test.go (hunk 3 above)
Comment (liggitt) [inline test/e2e/framework/internal/unittests/cleanup/cleanup_test.go:125]: how much time do these save? unless it's significant, I'd prefer not to piece-mill disable default admission plugins and featurers

Comment (aojea) [reply test/e2e/framework/internal/unittests/cleanup/cleanup_test.go:125]: added in the commit some info

> Local tests on my computer shows an improvement from an average of 16 seconds,
with a +-0.5 marging error, to 12 seconds with the same error marging.

but you are right, this is not the main problem here, jobs that run on environments that are not able to boot an apiserver+etcd are not reliable and they have to be dimensioned accordingly ...

**Comment by aojea** [comment]
@pohly I just submitted only the change to avoid non amd64 architectures for etcd , please lgtm if you are fine with it

https://github.com/kubernetes/kubernetes/pull/112416#discussion_r972765898

**Comment by pohly** [comment]
Works for me. Saving some time would have been nice, too, but it's not required.

/lgtm
