### PR TITLE
/test: use a different image for hostname override e2e tests

### LINKED ISSUE #134737: failing test[sig-node] Override hostname of Pod [FeatureGate:HostnameOverride] [Beta] a pod with only hostnameOverride field will have hostnameOverride as hostname
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-kind-ipv6/1980349256950616064

https://github.com/kubernetes/kubernetes/compare/183e01c6f...e4fcafba6

https://testgrid.k8s.io/sig-release-master-blocking#kind-ipv6-master

/kind failing-test
/sig node

### PR DESCRIPTION
**Pull request by neolit123**
#### What this PR does / why we need it:

As discovered in ticket 134737 `hostname` is buggy on busybox
due to the musl backend that it uses. something in the /etc/hosts
that k8s generates trips its parser and it doesn't work properly
in the ipv6 tests.

To workaround that use an image that has a glibc backend,
so that the hostname command works.

#### Which issue(s) this PR is related to:

fixes https://github.com/kubernetes/kubernetes/issues/134737

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/common/node/pod_hostnameoverride.go [hunk 1]
```diff
@@ -44,7 +44,7 @@ func newTestPod(namespace string) *v1.Pod {
 				{
 					Name:    "test-pod-hostname-override",
 					Image:   imageutils.GetE2EImage(imageutils.Agnhost),
-					Command: []string{"sh", "-c", "echo $(hostname)';'$(hostname -f)';'"},
+					Command: []string{"sh", "-c", "'cat /etc/hosts'"},
```
Comment (neolit123) [inline test/e2e/common/node/pod_hostnameoverride.go]: `e2eoutput.TestContainerOutput` uses `gomega.ContainSubstring` so just cat-ing should be fine?
is IP family important to consider here?

```
	ginkgo.It("a pod with only hostnameOverride field will have hostnameOverride as hostname", func(ctx context.Context) {
		pod := newTestPod(f.Namespace.Name)
		hostnameOverride := "override-host"
		pod.Spec.HostnameOverride = &hostnameOverride
		output := []string{fmt.Sprintf("%s;%s;", hostnameOverride, hostnameOverride)}
		e2eoutput.TestContainerOutput(ctx, f, "hostnameOverride only", pod, 0, output)
	})

```

```
func TestContainerOutput(ctx context.Context, f *framework.Framework, scenarioName string, pod *v1.Pod, containerIndex int, expectedOutput []string) {
	TestContainerOutputMatcher(ctx, f, scenarioName, pod, containerIndex, expectedOutput, gomega.ContainSubstring)
}
```

**Comment by neolit123** [comment]
/retest

>E2eNode Suite: [It] [sig-node] MirrorPod when create a mirror pod without changes should successfully recreate when file is removed and recreated [NodeConformance] expand_more	2m4s
e2e.go: Node Tests expand_more

File: test/e2e/common/node/pod_hostnameoverride.go (hunk 1 above)
Comment (neolit123) [reply test/e2e/common/node/pod_hostnameoverride.go]: there is no `cat` in that image, but i replaced it with a `while` loop with `read`.

File: test/e2e/common/node/pod_hostnameoverride.go [hunk 2]
```diff
@@ -44,7 +44,7 @@ func newTestPod(namespace string) *v1.Pod {
 				{
 					Name:    "test-pod-hostname-override",
 					Image:   imageutils.GetE2EImage(imageutils.Agnhost),
-					Command: []string{"sh", "-c", "echo $(hostname)';'$(hostname -f)';'"},
+					Command: []string{"sh", "-c", "while IFS= read -r line; do echo \"$line\"; done < /etc/hosts"},
```
Comment (neolit123) [inline test/e2e/common/node/pod_hostnameoverride.go]: is this supposed to work on windows?

does agnhost supports `hostname -f` on windows? i.e. was the old test working on windows ipv4 as is?
in terms of the new diff, /etc/hosts is not a standard windows path. the hosts file on windows was somewhere under the system32 dir.

cc @HirazawaUi @marosset @claudiubelu

Comment (neolit123) [reply test/e2e/common/node/pod_hostnameoverride.go]: do we need to branch for OS here and do this on windows?
```
Command: ["cmd", "/c", "type c:\\windows\\system32\\drivers\\etc\\hosts"]
```

Comment (neolit123) [reply test/e2e/common/node/pod_hostnameoverride.go]: the KEP states:

> For Windows containers, we only set the container's hostname and do not create an /etc/hosts file for it (as we have previously made it clear that we do not create an /etc/hosts file for Windows containers).

so i would assume the feature HostnameOverride is not supported on Windows as it doesn't amend the Windows hosts file (which isn't /etc/hosts)?

https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/4762-allow-arbitrary-fqdn-as-pod-hostname/README.md

EDIT: or i may be misunderstanding here.
- the windows container receives an override hostname
- there is no /etc/hosts
- calling `hostname -f` from aghhosts works (somehow) so the e2e test worked on windows.

if that is the case we should be likely calling a Windows native way to get the hostname instead, like `hostname.exe`, but there is no `hostname.exe -f` support, AFAIK.

File: test/e2e/common/node/pod_hostnameoverride.go [hunk 3]
```diff
@@ -44,7 +44,7 @@ func newTestPod(namespace string) *v1.Pod {
 				{
 					Name:    "test-pod-hostname-override",
 					Image:   imageutils.GetE2EImage(imageutils.Agnhost),
```
Comment (aojea) [inline test/e2e/common/node/pod_hostnameoverride.go]:
```suggestion
					Image:   imageutils.GetE2EImage(imageutils.JessieDnsutils),
```

Just that, I do not feel is great to rely on parsing the etc hosts for this test, hostname exercises the userspace calls that lot of languages use and we found this bug in musl thanks to that ... so is not about passing the test is about detecting this incompatibilities

File: test/e2e/common/node/pod_hostnameoverride.go (hunk 2 above)
Comment (aojea) [reply test/e2e/common/node/pod_hostnameoverride.go]: let's switch just the image https://github.com/kubernetes/kubernetes/pull/134757/files#r2450537200

File: test/e2e/common/node/pod_hostnameoverride.go (hunk 3 above)
Comment (BenTheElder) [reply test/e2e/common/node/pod_hostnameoverride.go]: We really need to rename this at some point, Jessie is the code word for a particular version that is completely EOL, even the extended LTS is EOL ...

IMHO agnhost should rebase on Debian, those are both points for another PR, but if we're continuing to adopt this more widely we need to figure that out.

Comment (neolit123) [reply test/e2e/common/node/pod_hostnameoverride.go]: i will switch the image. the questions from above about windows support stand.

**Comment by neolit123** [comment]
updated with the jessy image.

/test pull-kubernetes-e2e-kind-ipv6

File: test/e2e/common/node/pod_hostnameoverride.go (hunk 3 above)
Comment (HirazawaUi) [reply test/e2e/common/node/pod_hostnameoverride.go]: I think we assuming that k8s e2e tests are Linux-based. If certain test cases need to run on Windows, the sig-windows should mark these cases when enabling windows e2e testing and address any related issues.

Comment (HirazawaUi) [reply test/e2e/common/node/pod_hostnameoverride.go]: Alternatively, we could also use `SkipIfNodeOSDistroIs` to skip the test when the node is a Windows node. However, the question remains whether we already actually use this logic now, considering that the same test exists in https://github.com/kubernetes/kubernetes/blob/1404757c5a8194659ddbc5e14a3d8a143d11086a/test/e2e_node/pod_hostnamefqdn_test.go, and so far no one has raised any issues about it not being suitable for Windows.

Comment (neolit123) [reply test/e2e/common/node/pod_hostnameoverride.go]: afaik, new features are automatically run in windows e2e. there is no opt in.

Comment (HirazawaUi) [reply test/e2e/common/node/pod_hostnameoverride.go]: I'm not sure if we currently have any windows-based e2e test jobs running. However, there is an ongoing PR discussing the `LinuxOnly` label for e2e test cases:
ref: https://github.com/kubernetes/kubernetes/pull/134413

No conclusion has been reached yet. If you're concerned about this test case failing on Windows, we could potentially add the `[LinuxOnly]` label to the current test case for now, until we determine the appropriate labeling strategy for such tests in the #134413 discussion.

Comment (neolit123) [reply test/e2e/common/node/pod_hostnameoverride.go]: there used to be a windows e2e presubmit using capz but i can't find it.

@marosset @claudiubelu @BenTheElder @aojea 

likely know more on this topic.

Comment (BenTheElder) [reply test/e2e/common/node/pod_hostnameoverride.go]: I don't know how current it is but I just triggered one, you can find all jobs with `/test` (no parameter) or else the config in test-infra.

I need to catch up on this linuxonly thread, I had not seen that one yet.

Comment (BenTheElder) [reply test/e2e/common/node/pod_hostnameoverride.go]: Please don't use SkipIfNodeOSDistroIs, I agree with @pohly's comment that we should remove this. I'm not clear if we're agreed yet on how to tag these going forward, let's leave it for now and revisit.

Comment (marosset) [reply test/e2e/common/node/pod_hostnameoverride.go]: `pull-kubernetes-e2e-capz-windows-master` is current and is the pull-request version of https://testgrid.k8s.io/sig-windows-signal#capz-windows-master

Comment (neolit123) [reply test/e2e/common/node/pod_hostnameoverride.go]: i can't find 'Override hostname of Pod' in the logs on the windows job.
i think that's because it has this focus:

```
'--ginkgo.focus=\[Conformance\]|\[NodeConformance\]|\[sig-windows\]|\[sig-apps\].CronJob|\[sig-api-machinery\].ResourceQuota|\[sig-scheduling\].SchedulerPreemption'
```

so it will not run these host override tests.

https://storage.googleapis.com/kubernetes-ci-logs/logs/ci-kubernetes-e2e-capz-master-windows/1981037549581242368/build-log.txt

**Comment by marosset** [comment]
It looks like the windows job passed
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134757/pull-kubernetes-e2e-capz-windows-master/1981072751577796608 I'm not sure why the prow job is reporting it failed :(

**Comment by neolit123** [comment]
IIUC, we are not testing this feature on windows (at least in this capz job) due to the ginkgo flags there.

https://github.com/kubernetes/kubernetes/pull/134757#discussion_r2453167822

File: test/e2e/common/node/pod_hostnameoverride.go (hunk 2 above)
Comment (marosset) [reply test/e2e/common/node/pod_hostnameoverride.go]: We do create a etc hosts file for windows (but at [c:\Windows\System32\drivers\etc\hosts](https://github.com/kubernetes/kubernetes/blob/ab7003f2e5faf917c41cbf9d3b351bda3b0789bd/pkg/kubelet/kubelet.go#L193) )

getContainerEtcHostsPath() selects this if `goos=windows` in the kubelet and then all of the rest of the code paths should work the same for Linux/Windows.

I'm not sure why the KEP says we don't create this?

Comment (neolit123) [reply test/e2e/common/node/pod_hostnameoverride.go]: that is my understand as well. historically the hosts file under system32 has been a  unix-like artifact, and the format is the same.

Comment (neolit123) [reply test/e2e/common/node/pod_hostnameoverride.go]: but for an e2e the hostname -f, which is currently used, will not work as that is posix(?). it might if there is a posix like hostname.exe from msys or something similar, that takes priority in PATH in the test image.

the image in this pr is called jessy (debian), so i don't think that's even a multi-os image to exercise the feature e2e cross-os.

Comment (neolit123) [reply test/e2e/common/node/pod_hostnameoverride.go]: i guess this highlights the point @SergeyKanzhelev brought up about the linux vs windows feature discrepancy. i personally think that a sig-windows +1 should be a blocker for all sig-node keps reviews, which i understand is a bandwidth problem too.

alt, the project could establish a policy that "all new kubelet features are unsupported on windows, unless sig-windows approved and opts-in", that might be easier. and if a feature is desired by windows users, they can contribute changes and also amend keps and e2e...which can ease the burden on sig-windows.

Comment (SergeyKanzhelev) [reply test/e2e/common/node/pod_hostnameoverride.go]: maintainers bandwidth, lack of knowledge, and lack of participation from SIG Windwos - all the factors. Especially with the much smaller user base

Comment (marosset) [reply test/e2e/common/node/pod_hostnameoverride.go]: CC @princepereira @sbangari who are more familiar with networking on Windows than I am

Comment (neolit123) [reply test/e2e/common/node/pod_hostnameoverride.go]: might be a good idea to enhance the PRR to ask some multi-os questions. e.g.

"is this supposed to work on both linux and windows and will there be tests for both?"

if "yes", but e2e were not implemented, then there is misalignment with the PRR.

the questionare type of mechanism is one way to approaching the problem.

Comment (SergeyKanzhelev) [reply test/e2e/common/node/pod_hostnameoverride.go]: > the questionare type of mechanism is one way to approaching the problem

PRR requirement like this goes oppose to https://docs.google.com/document/d/16GVggKO3sdpbOM5YNqnZPGyCR45UKAhF05s6GQdUPCw/. Any requirement to test on Windows assumes there is a stable Windows test lane. Assumption that all new features are not supported and needs to be explicitly tested later unblocks the faster progress

Please comment on the doc for feedback. I am still finishing up how exactly we want to implement it

Comment (neolit123) [reply test/e2e/common/node/pod_hostnameoverride.go]: i think i agree that by default new kubelet features should be unsupported on windows without +1 and engagement from sig win, that's what i proposed earlier.

but a PRR or a KEP template question will make it clear to all reviewers about the contributor stance and plan. right now, reading a KEP the multi-os support is unclear.

Comment (marosset) [reply test/e2e/common/node/pod_hostnameoverride.go]: we actually do have a jessie-dnsutils windows image :P
https://github.com/kubernetes/kubernetes/blob/master/test/images/jessie-dnsutils/Dockerfile_windows

I agree that having some explicit questions regarding applicability / feasibility for Windows support would be a good idea to have in the KEP or PRR template.

During the KEP authoring process is the best time to consider this and possibly then make the decision if Windows support is possible and then if it should be implemented as a separate KEP.
If there is no implementation OR testing differences needed I still think we shouldn't require a separate KEP to just enable the feature on Windows. If we need to implement platform specific logic (even for testing) then we could require separate KEPs

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

File: test/e2e/common/node/pod_hostnameoverride.go (hunk 2 above)
Comment (HirazawaUi) [reply test/e2e/common/node/pod_hostnameoverride.go]: > We do create a etc hosts file for windows (but at [c:\Windows\System32\drivers\etc\hosts](https://github.com/kubernetes/kubernetes/blob/ab7003f2e5faf917c41cbf9d3b351bda3b0789bd/pkg/kubelet/kubelet.go#L193) )
> 
> getContainerEtcHostsPath() selects this if `goos=windows` in the kubelet and then all of the rest of the code paths should work the same for Linux/Windows.
> 
> I'm not sure why the KEP says we don't create this?

My apologies, I assumed this fact without sufficient Windows background knowledge, and I didn’t verify the issue due to the lack of a Windows environment. I will revise the KEP in my spare time to remove this statement.
