### PR TITLE
Make selector immutable for v1beta2 deployment, replicaset and daemonset prior update

### LINKED ISSUE #50808: Controller selectors should be immutable after creation
**Background**
As part of the greater controller GA effort, we have removed defaulting `spec.selector` to `spec.template.labels` values in `apps/v1beta2` as the defaulting operation is semantically broken. In this issue, we propose to make `spec.selector` immutable after API object creation.

**Motivation**

1. Changing selectors leads to undefined behaviors - users are not expected to change the selectors
2. Having selectors immutable ensures they always match created children, preventing events such as accidental bulk orphaning
3. Having selectors mutable for GA is an immortal decision, which does not guarantee API backward compatibility

Immutability resolves some challenging issues that plague many teams for over a year e.g., #34292, and the current behavior for controllers with respect to selector mutations is undefined e.g., #26202.

In contrast, by making selectors immutable, validation ensures the selectors always match template labels of created children. This provides a risk-free, deterministic behavior to resolve the issue, and meet the general goal of declarative configuration.

We could **lift the immutability in future** after all controller types have well-defined behaviors (i.e., after GA). This provides ability to address new use cases while maintaining API backward compatibility. However, if we do not make selectors immutable prior to GA, we will have to live with mutable selectors for the lifetime of the v1 API and the controllers’ undefined behaviors until reasonable semantics are decided and implemented.

/kind bug
/sig apps
/sig api-machinery
@bgrant0607 @erictune @kow3ns @enisoc @janetkuo @foxish @liyinan926 
@liggitt @smarterclayton @kargakis @mikedanese

### PR DESCRIPTION
**Pull request by crimsonfaith91**
**What this PR does / why we need it**:
This PR ensures controller selector is immutable for deployment and replicaset prior update by ignoring any change to `Spec`.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50808

**Special notes for your reviewer**:
This will be a breaking change.

**Release note**:

```release-note
For Deployment, ReplicaSet, and DaemonSet, selectors are now immutable when updating via the new `apps/v1beta2` API. For backward compatibility, selectors can still be changed when updating via `apps/v1beta1` or `extensions/v1beta1`.
```

### CODE REVIEW

File: pkg/registry/extensions/deployment/strategy.go [hunk 1]
```diff
@@ -77,6 +77,13 @@ func (deploymentStrategy) PrepareForUpdate(ctx genericapirequest.Context, obj, o
 	oldDeployment := old.(*extensions.Deployment)
 	newDeployment.Status = oldDeployment.Status
 
+	// update is not allowed to set spec for v1beta2
+	// We assume API version is not v1beta2 if no RequestInfo is found
+	requestInfo, found := genericapirequest.RequestInfoFrom(ctx)
+	if found && requestInfo.APIVersion == "v1beta2" {
+		newDeployment.Spec = oldDeployment.Spec
```
Comment (crimsonfaith91) [inline pkg/registry/extensions/deployment/strategy.go]: @kow3ns @enisoc Perhaps `newDeployment.Spec.Selector = oldDeployment.Spec.Selector` is better.

File: pkg/registry/extensions/deployment/strategy.go [hunk 2]
```diff
@@ -77,6 +77,13 @@ func (deploymentStrategy) PrepareForUpdate(ctx genericapirequest.Context, obj, o
 	oldDeployment := old.(*extensions.Deployment)
 	newDeployment.Status = oldDeployment.Status
 
+	// update is not allowed to set spec for v1beta2
+	// We assume API version is not v1beta2 if no RequestInfo is found
+	requestInfo, found := genericapirequest.RequestInfoFrom(ctx)
+	if found && requestInfo.APIVersion == "v1beta2" {
```
Comment (crimsonfaith91) [inline pkg/registry/extensions/deployment/strategy.go]: For now, it affects only `v1beta2` API version. In future, we may need to change it to `v1` or have a range like greater than `v1beta1`.

**Review by kow3ns — CHANGES_REQUESTED** [review]
You can't clear the entire spec, this disallows all relevant changes to the API object. You might be able to clear the selector change. Is this the method that you discussed with @erictune?

**Comment by crimsonfaith91** [comment]
@kow3ns Yes - i suggested `newDeployment.Spec.Selector = oldDeployment.Spec.Selector` in another [comment](https://github.com/kubernetes/kubernetes/pull/50719#discussion_r133331140). I think we should not ignore all changes to `Spec`. Instead, we should limit it to `Spec.Selector`.

File: pkg/registry/extensions/deployment/strategy.go [hunk 3]
```diff
@@ -77,6 +77,14 @@ func (deploymentStrategy) PrepareForUpdate(ctx genericapirequest.Context, obj, o
 	oldDeployment := old.(*extensions.Deployment)
 	newDeployment.Status = oldDeployment.Status
 
+	// update is not allowed to set Spec.Selector for v1beta2
+	// we assume it is not v1beta2 if no API group and/or version is found in RequestInfo
+	// TODO(#50791): after v1beta1 is retired, move selector immutability check to validation codes
+	requestInfo, found := genericapirequest.RequestInfoFrom(ctx)
```
Comment (crimsonfaith91) [inline pkg/registry/extensions/deployment/strategy.go]: @erictune @kow3ns As discussed by person, i added a TODO for moving the check to validation codes after _v1beta1_ retires, and included the API group in the condition.

File: pkg/registry/extensions/daemonset/strategy_test.go [hunk 4]
```diff
@@ -31,3 +37,67 @@ func TestDefaultGarbageCollectionPolicy(t *testing.T) {
...
+	resolver := newTestRequestInfoResolver()
+
+	for _, test := range tests {
+		req, _ := http.NewRequest(test.method, test.url, nil)
+
+		apiRequestInfo, err := resolver.NewRequestInfo(req)
+		if err != nil {
+			t.Errorf("Unexpected error for url: %s %v", test.url, err)
+		}
+		if !apiRequestInfo.IsResourceRequest {
```
Comment (crimsonfaith91) [inline pkg/registry/extensions/daemonset/strategy_test.go]: @kow3ns 
After writing the unit test, i think we can leave out the API group when determining whether to ignore changes to `Spec.Selector`. The main reason is due to how `RequestInfo` works.

`IsResourceRequest` returns true for requests to API resources, like `/api/v1/...`, and false for non-resource endpoints like `/api`, `/healthz`, and `/swaggerapi`. In other words, something like `api/v1beta2/...` works, but not `/api/apps/v1beta2/...` (additional `apps` after `api`) or `/apps/v1beta2/...` (do not start with `api`).

Furthermore, we will have the silent ignore for `v1` in future, which will be `/api/v1/...` that works perfectly with how `RequestInfo` works. Moreover, `v1beta2` only exists for `apps` group, which does not justify verifying the API group.

WDYT?

File: pkg/registry/extensions/daemonset/strategy.go [hunk 5]
```diff
@@ -70,6 +70,14 @@ func (daemonSetStrategy) PrepareForUpdate(ctx genericapirequest.Context, obj, ol
 	// update is not allowed to set TemplateGeneration
 	newDaemonSet.Spec.TemplateGeneration = oldDaemonSet.Spec.TemplateGeneration
 
+	// update is not allowed to set Spec.Selector for v1beta2
+	// we assume it is not v1beta2 if no API version is found in RequestInfo
+	// TODO(#50791): after v1beta1 is retired, move selector immutability check to validation codes
+	requestInfo, found := genericapirequest.RequestInfoFrom(ctx)
+	if found && requestInfo.APIVersion == "v1beta2" {
```
Comment (crimsonfaith91) [inline pkg/registry/extensions/daemonset/strategy.go]: Refer this [comment](https://github.com/kubernetes/kubernetes/pull/50719/files#r133611825) for why checking API group may be unnecessary.

File: pkg/registry/extensions/daemonset/strategy_test.go (hunk 4 above)
Comment (enisoc) [inline pkg/registry/extensions/daemonset/strategy_test.go]: These controllers never existed in the groupless `/api/` prefix, so your test shouldn't expect those inputs to work. Specifically, you want to make sure that `/apis/extensions/v1beta1` allows mutation, and `/apis/apps/v1beta2` does not. If we decide to plan ahead for `/apis/apps/v1` you could test for that too, but I don't know if that's decided yet.

Comment (crimsonfaith91) [inline pkg/registry/extensions/daemonset/strategy_test.go]: @enisoc Good point! Thanks for the clarification. I will test for `/apis/extensions/v1beta1` and `/apis/apps/v1beta2`.

**Review by kow3ns — APPROVED** [review]

**Comment by crimsonfaith91** [comment]
@enisoc If everything looks good to you, feel free to LGTM. Thanks!

**Comment by enisoc** [comment]
I don't think this needs a release note, because it only affects apps/v1beta2 which is new in this release anyway.

/release-note-none

File: pkg/registry/extensions/daemonset/strategy_test.go [hunk 6]
```diff
@@ -31,3 +37,71 @@ func TestDefaultGarbageCollectionPolicy(t *testing.T) {
 		t.Errorf("DefaultGarbageCollectionPolicy() = %#v, want %#v", got, want)
 	}
 }
+
+func TestSelectorImmutability(t *testing.T) {
+	tests := []struct {
+		method                 string
```
Comment (enisoc) [inline pkg/registry/extensions/daemonset/strategy_test.go]: Since this test is only for updates, the method should be `"PUT"` for all cases, so you don't need to specify it for each case.

File: pkg/registry/extensions/daemonset/strategy_test.go [hunk 7]
```diff
@@ -31,3 +37,71 @@ func TestDefaultGarbageCollectionPolicy(t *testing.T) {
...
+		url                    string
+		oldSelectorLabels      map[string]string
+		newSelectorLabels      map[string]string
+		expectedAPIGroup       string
+		expectedAPIVersion     string
+		expectedSelectorLabels map[string]string
+	}{
+		{"GET", "/apis/apps/v1beta2/namespaces", map[string]string{"a": "b"}, map[string]string{"c": "d"}, "apps", "v1beta2", map[string]string{"a": "b"}},
```
Comment (enisoc) [inline pkg/registry/extensions/daemonset/strategy_test.go]: To make the URLs more realistic, use something like `"/apis/apps/v1beta2/namespaces/default/daemonsets/dsname"`.

File: pkg/registry/extensions/daemonset/strategy_test.go [hunk 8]
```diff
@@ -31,3 +37,71 @@ func TestDefaultGarbageCollectionPolicy(t *testing.T) {
...
+}
+
+func newDaemonSetWithSelectorLabels(selectorLabels *map[string]string) *extensions.DaemonSet {
+	return &extensions.DaemonSet{
+		ObjectMeta: metav1.ObjectMeta{
+			Name: "test",
+		},
+		Spec: extensions.DaemonSetSpec{
+			Selector: &metav1.LabelSelector{
+				MatchLabels:      *selectorLabels,
```
Comment (enisoc) [inline pkg/registry/extensions/daemonset/strategy_test.go]: It seems like `selectorLabels` doesn't need to be a pointer.

**Review by enisoc — COMMENTED** [review]
What's the plan to make sure we don't forget to do this for `apps/v1` if necessary?

**Comment by crimsonfaith91** [comment]
@enisoc Addressed most recent feedback. My bad - should have used "PUT" instead of "GET".

File: pkg/registry/extensions/daemonset/strategy_test.go [hunk 9]
```diff
@@ -31,3 +37,70 @@ func TestDefaultGarbageCollectionPolicy(t *testing.T) {
...
+func TestSelectorImmutability(t *testing.T) {
+	tests := []struct {
+		url                    string
+		oldSelectorLabels      map[string]string
+		newSelectorLabels      map[string]string
+		expectedAPIGroup       string
+		expectedAPIVersion     string
+		expectedSelectorLabels map[string]string
+	}{
+		{"/apis/apps/v1beta2/namespaces/default/daemonset/test-daemonset", map[string]string{"a": "b"}, map[string]string{"c": "d"}, "apps", "v1beta2", map[string]string{"a": "b"}},
```
Comment (enisoc) [inline pkg/registry/extensions/daemonset/strategy_test.go]: For full realism, the resource should be plural: `.../default/daemonsets/...`

**Comment by enisoc** [comment]
What's the plan to make sure we don't forget to do this for `apps/v1` if necessary? Did you decide not to address it in this PR?

File: pkg/registry/extensions/daemonset/strategy_test.go (hunk 9 above)
Comment (crimsonfaith91) [inline pkg/registry/extensions/daemonset/strategy_test.go]: sure!

File: pkg/registry/extensions/deployment/strategy_test.go [hunk 10]
```diff
@@ -78,3 +80,70 @@ func newDeployment(labels, annotations map[string]string) *extensions.Deployment
...
+func TestSelectorImmutability(t *testing.T) {
+	tests := []struct {
+		url                    string
+		oldSelectorLabels      map[string]string
+		newSelectorLabels      map[string]string
+		expectedAPIGroup       string
+		expectedAPIVersion     string
+		expectedSelectorLabels map[string]string
+	}{
+		{"/apis/apps/v1beta2/namespaces/default/deployment/test-deployment", map[string]string{"a": "b"}, map[string]string{"c": "d"}, "apps", "v1beta2", map[string]string{"a": "b"}},
```
Comment (enisoc) [inline pkg/registry/extensions/deployment/strategy_test.go]: I just remembered, Deployment already existed in `apps/v1beta1`, so we should add a test case to verify that remains mutable.

Comment (crimsonfaith91) [inline pkg/registry/extensions/deployment/strategy_test.go]: As discussed by person, there is only one `deploymentStrategy` that exists in `registry/extensions` as `extensions.Deployment` is internal version.

**Comment by crimsonfaith91** [comment]
In `PrepareForUpdate` method, `RequestInfoFrom()` function call will return `false` as second return value if returned `RequestInfo` object is nil. This will **NOT** happen in default namespace, which uses a constant namespace [key](https://github.com/kubernetes/apiserver/blob/master/pkg/endpoints/request/context.go#L56) named `iota` to [retrieve](https://github.com/kubernetes/apiserver/blob/master/pkg/endpoints/request/requestinfo.go#L233) the `RequestInfo` object.

As GVK are mandatory fields for API object spec, we can deduce that the information is available in the non-nil `RequestInfo` object. An integration test will be added to show this.

Note that `RequestInfoFrom()` function call returns an [interface](https://github.com/kubernetes/apiserver/blob/master/pkg/endpoints/request/context.go#L37) which is then convert to `{RequestInfo, bool}` via type assertion. For more information, search for keyword `FromContext` in this Golang [tutorial](https://blog.golang.org/context).

**Comment by crimsonfaith91** [comment]
In `PrepareForUpdate` method, `RequestInfoFrom()` function call will return `false` as second return value if returned `RequestInfo` object is nil. This will **NOT** happen in default namespace, which uses a constant namespace [key](https://github.com/kubernetes/apiserver/blob/master/pkg/endpoints/request/context.go#L56) named `iota` to [retrieve](https://github.com/kubernetes/apiserver/blob/master/pkg/endpoints/request/requestinfo.go#L233) the `RequestInfo` object.

As GVK are mandatory fields for API object spec (the REST URL must have GVK), we can deduce that the information is available in the non-nil `RequestInfo` object. An integration test will be added to show this.

Note that `RequestInfoFrom()` function call returns an [interface](https://github.com/kubernetes/apiserver/blob/master/pkg/endpoints/request/context.go#L37) which is then convert to `{RequestInfo, bool}` via type assertion. For more information, search for keyword `FromContext` in this Golang [tutorial](https://blog.golang.org/context).

File: pkg/registry/extensions/daemonset/strategy.go [hunk 11]
```diff
@@ -70,6 +70,16 @@ func (daemonSetStrategy) PrepareForUpdate(ctx genericapirequest.Context, obj, ol
 	// update is not allowed to set TemplateGeneration
 	newDaemonSet.Spec.TemplateGeneration = oldDaemonSet.Spec.TemplateGeneration
 
+	// Update is not allowed to set Spec.Selector for all groups/versions except extensions/v1beta1.
+	// RequestInfo will not be nil in default namespace, but we still have to check for it to prevent
+	// breaking storage registry TestUpdate() and TestScaleUpdate() unit tests. Refer this link for more info:
+	// https://github.com/kubernetes/kubernetes/pull/50719#issuecomment-323449792
+	// TODO(#50791): after v1beta1 is retired, move selector immutability check to validation codes
+	requestInfo, found := genericapirequest.RequestInfoFrom(ctx)
```
Comment (crimsonfaith91) [inline pkg/registry/extensions/daemonset/strategy.go]: @enisoc If the condition looks good to you, i will start writing integration test.

File: pkg/registry/extensions/deployment/strategy.go [hunk 12]
```diff
@@ -77,6 +77,16 @@ func (deploymentStrategy) PrepareForUpdate(ctx genericapirequest.Context, obj, o
 	oldDeployment := old.(*extensions.Deployment)
 	newDeployment.Status = oldDeployment.Status
 
+	// Update is not allowed to set Spec.Selector for all groups/versions except extensions/v1beta1.
+	// RequestInfo will not be nil in default namespace, but we still have to check for it to prevent
+	// breaking storage registry TestUpdate() and TestScaleUpdate() unit tests. Refer this link for more info:
+	// https://github.com/kubernetes/kubernetes/pull/50719#issuecomment-323449792
+	// TODO(#50791): after v1beta1 is retired, move selector immutability check to validation codes
+	requestInfo, found := genericapirequest.RequestInfoFrom(ctx)
+	if found && !(requestInfo.APIGroup == "extensions" && requestInfo.APIVersion == "v1beta1") {
```
Comment (enisoc) [inline pkg/registry/extensions/deployment/strategy.go]: Deployment also exists in `apps/v1beta1` so we should include that in the allowed list. Also add a test case for `apps/v1beta1` Deployment.

**Comment by crimsonfaith91** [comment]
@enisoc The namespace key `iota` is used by [WithNamespace](https://github.com/kubernetes/apiserver/blob/master/pkg/endpoints/request/context.go#L93) method, which is in turn used by [NewDefaultContext](https://github.com/kubernetes/apiserver/blob/master/pkg/endpoints/request/context.go#L79) method to create the `Context` object.

File: pkg/registry/extensions/deployment/strategy.go (hunk 12 above)
Comment (crimsonfaith91) [inline pkg/registry/extensions/deployment/strategy.go]: Got it!

Comment (crimsonfaith91) [inline pkg/registry/extensions/deployment/strategy.go]: I finally understood: Although `deploymentStrategy` only has one version (extensions), it does not mean `deployment` cannot have more than one version.

File: test/integration/deployment/deployment_test.go [hunk 13]
```diff
@@ -69,3 +70,50 @@ func TestNewDeployment(t *testing.T) {
 		t.Errorf("expected new ReplicaSet last-applied annotation not copied from Deployment %s", deploy.Name)
 	}
 }
+
+// TODO(juntee): add tests for selector immutability when apps/v1beta2 infomers and listers are available
```
Comment (crimsonfaith91) [inline test/integration/deployment/deployment_test.go]: @enisoc Thanks for your patient guidance last week! Some parts of the integration test are out.
I found out that integration tests are based on `extensions/v1beta1` version only. Current informers and listers support only the version too. I am not sure whether it is possible to add the integration test of `apps/v1beta2` version now, or there is a way to get over it.

I will spend some time to investigate about this, and get back to you by today.

**Comment by crimsonfaith91** [comment]
@enisoc After tracking down `WithRequestInfo` function, my conclusion is: `RequestInfo` object is created before `WithRequestInfo` function call, and a HTTP call **should** have the `RequestInfo` object if the REST URL path is correct. For all testing files, there is an explicit creation of the `RequestInfo` object via `NewRequestInfo` function.

However, i still lean towards necessity to define what it means to have no `RequestInfo` object. Should we make selector immutable or fall back to old behaviors when API group and version details are absent?

IMO, we should make selector immutable as future versions are more important. As `extensions/v1beta1` an `apps/v1beta1` will be retired in less than a year (around 2 - 3 releases), this problem will become irrelevant when we move the codes to validation.

File: test/integration/deployment/util.go [hunk 14]
```diff
@@ -87,6 +94,40 @@ func newDeployment(name, ns string, replicas int32) *v1beta1.Deployment {
 	}
 }
 
+// newDeployment returns a RollingUpdate Deployment with with a fake container image
+func newAppsV1beta2Deployment(name, ns string, replicas int32) *v1beta2.Deployment {
```
Comment (crimsonfaith91) [inline test/integration/deployment/util.go]: I have to create a new set of functions for `apps/v1beta2` so that i am able to test both `apps/v1beta2` and `extensions/v1beta1` versions accordingly.

File: test/integration/deployment/deployment_test.go [hunk 15]
```diff
@@ -69,3 +70,59 @@ func TestNewDeployment(t *testing.T) {
...
+	deploy, err = c.AppsV1beta2().Deployments(ns.Name).Update(appsV1beta2Tester.deployment)
+	if err != nil {
+		t.Fatalf("failed to update deployment %s: %v", deploy.Name, err)
+	}
+	if !reflect.DeepEqual(deploy.Spec.Selector.MatchLabels, oldSelectorLabels) {
+		t.Errorf("selector should NOT be changed for apps/v1beta2, expected: %v, got: %v", newSelectorLabels, deploy.Spec.Selector.MatchLabels)
+	}
+}
+
+func TestDeploymentSelectorMutability(t *testing.T) {
```
Comment (enisoc) [inline test/integration/deployment/deployment_test.go]: I think it's better to combine these functions because they're related. In integration tests there's a non-trivial time cost to set up the apiserver every time.

File: test/integration/deployment/util.go (hunk 14 above)
Comment (enisoc) [inline test/integration/deployment/util.go]: This and `deploymentAppsV1beta2Test` are not strictly necessary. You can use the extensions/v1beta1 client to create the Deployment, then test that you can update the selector through the extensions/v1beta2 client. You can then use the apps/v1beta2 client to Get() the same Deployment (remember it will auto-convert), and then use the apps/v1beta2 client to Update.

File: test/integration/replicaset/replicaset_test.go [hunk 16]
```diff
@@ -462,3 +523,47 @@ func TestUpdateLabelToBeAdopted(t *testing.T) {
...
+	replicaset, err := clientSet.AppsV1beta2().ReplicaSets(ns.Name).Update(rs)
+	if err != nil {
+		t.Fatalf("failed to update replicaset %s: %v", replicaset.Name, err)
+	}
+	if !reflect.DeepEqual(replicaset.Spec.Selector.MatchLabels, oldSelectorLabels) {
+		t.Errorf("selector should NOT be changed for apps/v1beta2, expected: %v, got: %v", oldSelectorLabels, replicaset.Spec.Selector.MatchLabels)
+	}
+}
+
+func TestRSSelectorMutability(t *testing.T) {
```
Comment (enisoc) [inline test/integration/replicaset/replicaset_test.go]: Combine into one function.

File: test/integration/replicaset/replicaset_test.go [hunk 17]
```diff
@@ -274,6 +320,21 @@ func createRSsPods(t *testing.T, clientSet clientset.Interface, rss []*v1beta1.R
 	}
 }
 
+func createAppsV1beta2RSsPods(t *testing.T, clientSet clientset.Interface, rss []*v1beta2.ReplicaSet, pods []*v1.Pod, ns string) {
```
Comment (enisoc) [inline test/integration/replicaset/replicaset_test.go]: As above, this shouldn't be necessary.

**Comment by enisoc** [comment]
If there is no RequestInfo found, I think we should default to allowing the selector to change.

According to your investigation, the RequestInfo should always exist for a request with a valid URL. Invalid request URLs should never make it all the way to this step (PrepareForUpdate). So the risk seems low that we will hit this case.

Nevertheless, if we are wrong, I would rather err on the side of failing to enforce immutability (reverting to old behavior) rather than on the side of unintentionally breaking users (who may rely on the old behavior) or panicking (because restarting the process will not help this).

**Comment by crimsonfaith91** [comment]
@enisoc Thanks for the explanation. It makes sense to retain old behavior when `RequestInfo` object is unavailable. We should not deliver a change that breaks compatibility of existing versions - backward compatibility is crucial.

> ... RequestInfo should always exist for a request with a valid URL ...
Ya, there is a function that parses the URL and fill each part of the URL into `RequestInfo` attributes.

File: test/integration/deployment/util.go (hunk 14 above)
Comment (crimsonfaith91) [inline test/integration/deployment/util.go]: Thanks for enumerating the steps. This is very important - I didn't know that it was possible to have an integration test without controllers and informers, and was not aware at all the version difference could be resolved by the steps.

File: pkg/registry/extensions/daemonset/strategy.go [hunk 18]
```diff
@@ -70,6 +70,16 @@ func (daemonSetStrategy) PrepareForUpdate(ctx genericapirequest.Context, obj, ol
 	// update is not allowed to set TemplateGeneration
 	newDaemonSet.Spec.TemplateGeneration = oldDaemonSet.Spec.TemplateGeneration
 
+	// Update is not allowed to set Spec.Selector for all groups/versions except extensions/v1beta1.
```
Comment (crimsonfaith91) [inline pkg/registry/extensions/daemonset/strategy.go]: sure! i removed the comment as it was not applicable anymore, but forgot to remove the comment link.

File: pkg/registry/extensions/deployment/strategy_test.go [hunk 19]
```diff
@@ -78,3 +80,72 @@ func newDeployment(labels, annotations map[string]string) *extensions.Deployment
...
+		oldSelectorLabels      map[string]string
+		newSelectorLabels      map[string]string
+		expectedAPIGroup       string
+		expectedAPIVersion     string
+		expectedSelectorLabels map[string]string
+	}{
+		{"/apis/apps/v1beta2/namespaces/default/deployments/test-deployment", map[string]string{"a": "b"}, map[string]string{"c": "d"}, "apps", "v1beta2", map[string]string{"a": "b"}},
+		{"/apis/extensions/v1beta2/namespaces/default/deployments/test-deployment", map[string]string{"a": "b"}, map[string]string{"c": "d"}, "extensions", "v1beta2", map[string]string{"a": "b"}},
+		{"/apis/apps/v1/namespaces/default/deployments/test-deployment", map[string]string{"a": "b"}, map[string]string{"c": "d"}, "apps", "v1", map[string]string{"a": "b"}},
+		{"/apis/extensions/v1beta1/namespaces/default/deployments/test-deployment", map[string]string{"a": "b"}, map[string]string{"c": "d"}, "extensions", "v1beta1", map[string]string{"c": "d"}},
```
Comment (crimsonfaith91) [inline pkg/registry/extensions/deployment/strategy_test.go]: Yes, you mentioned about this before, but i added the wrong version.

File: test/integration/deployment/deployment_test.go (hunk 15 above)
Comment (crimsonfaith91) [inline test/integration/deployment/deployment_test.go]: The time difference is within 5 seconds. As there is a way to resolve version difference, we should combine them into one function.

File: test/integration/replicaset/replicaset_test.go (hunk 17 above)
Comment (crimsonfaith91) [inline test/integration/replicaset/replicaset_test.go]: Yup!

File: test/integration/replicaset/replicaset_test.go (hunk 16 above)
Comment (crimsonfaith91) [inline test/integration/replicaset/replicaset_test.go]: Sure!

File: test/integration/deployment/deployment_test.go [hunk 20]
```diff
@@ -69,3 +71,60 @@ func TestNewDeployment(t *testing.T) {
...
+	}
+
+	// test to ensure apps/v1beta2 selector is immutable
+	deploymentAppsV1beta2, err := c.AppsV1beta2().Deployments(ns.Name).Get(updatedDeploymentAppsV1beta1.Name, metav1.GetOptions{})
+	if err != nil {
+		t.Fatalf("failed to get apps/v1beta2 deployment %s: %v", updatedDeploymentAppsV1beta1.Name, err)
+	}
+	deploymentAppsV1beta2.Spec.Selector.MatchLabels = newSelectorLabels
+	updatedDeploymentAppsV1beta2, err := c.AppsV1beta2().Deployments(ns.Name).Update(deploymentAppsV1beta2)
+	if err != nil {
```
Comment (enisoc) [inline test/integration/deployment/deployment_test.go]: Please add a TODO here to change this to expect an error after selector immutability is moved to validation. Reference the same issue as the TODOs above.

File: test/integration/deployment/deployment_test.go [hunk 21]
```diff
@@ -69,3 +71,60 @@ func TestNewDeployment(t *testing.T) {
...
+	if !reflect.DeepEqual(updatedDeploymentExtensionsV1beta1.Spec.Selector.MatchLabels, newSelectorLabels) {
+		t.Errorf("selector should be changed for extensions/v1beta1, expected: %v, got: %v", newSelectorLabels, updatedDeploymentExtensionsV1beta1.Spec.Selector.MatchLabels)
+	}
+
+	// test to ensure apps/v1beta1 selector is mutable
+	deploymentAppsV1beta1, err := c.AppsV1beta1().Deployments(ns.Name).Get(updatedDeploymentExtensionsV1beta1.Name, metav1.GetOptions{})
+	if err != nil {
+		t.Fatalf("failed to get apps/v1beta1 deployment %s: %v", updatedDeploymentExtensionsV1beta1.Name, err)
+	}
+	deploymentAppsV1beta1.Spec.Selector.MatchLabels = oldSelectorLabels
```
Comment (enisoc) [inline test/integration/deployment/deployment_test.go]: Instead of reusing the values of `oldSelectorLabels` and `newSelectorLabels`, always set `oldSelectorLabels` to the value returned from `Get()`, and also assign a new value of `newSelectorLabels` that you don't use anywhere else.

This makes the expected condition below more clear (do you expect to see the "new" or "old" value after the update attempt?) and helps to prevent accidental breakage of the test if someone else comes along and adds new test cases later.

File: test/integration/replicaset/replicaset_test.go [hunk 22]
```diff
@@ -462,3 +474,39 @@ func TestUpdateLabelToBeAdopted(t *testing.T) {
...
+		t.Errorf("selector should be changed for extensions/v1beta1, expected: %v, got: %v", selectorLabels, replicaset.Spec.Selector.MatchLabels)
+	}
+
+	// test to ensure apps/v1beta2 selector is immutable
+	rsV1beta2, err := clientSet.AppsV1beta2().ReplicaSets(ns.Name).Get(replicaset.Name, metav1.GetOptions{})
+	if err != nil {
+		t.Fatalf("failed to get apps/v1beta2 replicaset %s: %v", replicaset.Name, err)
+	}
+
+	replicasetV1beta2, err := clientSet.AppsV1beta2().ReplicaSets(ns.Name).Update(rsV1beta2)
```
Comment (enisoc) [inline test/integration/replicaset/replicaset_test.go]: I don't see where you try to set a new value for the selector.

File: test/integration/deployment/deployment_test.go (hunk 21 above)
Comment (crimsonfaith91) [inline test/integration/deployment/deployment_test.go]: Agreed. For the first two mutable cases, `oldSelectorLabels` is, in fact, not needed. Only the last immutable case requires `oldSelectorLabels`.

File: test/integration/replicaset/replicaset_test.go [hunk 23]
```diff
@@ -462,3 +474,41 @@ func TestUpdateLabelToBeAdopted(t *testing.T) {
...
+	rs.Spec.Template.Labels = newSelectorLabels
+	replicaset, err := clientSet.ExtensionsV1beta1().ReplicaSets(ns.Name).Update(rs)
+	if err != nil {
+		t.Fatalf("failed to update extensions/v1beta1 replicaset %s: %v", replicaset.Name, err)
+	}
+	if !reflect.DeepEqual(replicaset.Spec.Selector.MatchLabels, newSelectorLabels) {
+		t.Errorf("selector should be changed for extensions/v1beta1, expected: %v, got: %v", newSelectorLabels, replicaset.Spec.Selector.MatchLabels)
+	}
+
+	// test to ensure apps/v1beta2 selector is immutable
```
Comment (enisoc) [inline test/integration/replicaset/replicaset_test.go]: This also needs the TODO. Sorry for not specifying earlier.

Comment (crimsonfaith91) [inline test/integration/replicaset/replicaset_test.go]: No, it is my mistake for not specifying it. Your comment applies to all controllers.

**Comment by crimsonfaith91** [comment]
@smarterclayton Do you mind to approve this PR if everything looks good to you?

File: pkg/registry/extensions/daemonset/strategy.go [hunk 24]
```diff
@@ -70,6 +70,15 @@ func (daemonSetStrategy) PrepareForUpdate(ctx genericapirequest.Context, obj, ol
...
+	// If RequestInfo is nil, it is better to revert to old behavior (i.e. allow update to set Spec.Selector)
+	// to prevent unintentionally breaking users who may rely on the old behavior.
+	// TODO(#50791): after v1beta1 is retired, move selector immutability check to validation codes
+	requestInfo, found := genericapirequest.RequestInfoFrom(ctx)
+	if found && !(requestInfo.APIGroup == "extensions" && requestInfo.APIVersion == "v1beta1") {
+		newDaemonSet.Spec.Selector = oldDaemonSet.Spec.Selector
```
Comment (liggitt) [inline pkg/registry/extensions/daemonset/strategy.go]: is it better to silently drop mutation attempts or to fail them?

File: pkg/registry/extensions/replicaset/strategy_test.go [hunk 25]
```diff
@@ -141,3 +144,71 @@ func TestReplicaSetStatusStrategy(t *testing.T) {
...
+		{"/apis/apps/v1/namespaces/default/replicasets/test-replicaset", map[string]string{"a": "b"}, map[string]string{"c": "d"}, "apps", "v1", map[string]string{"a": "b"}},
+		{"/apis/extensions/v1beta1/namespaces/default/replicasets/test-replicaset", map[string]string{"a": "b"}, map[string]string{"c": "d"}, "extensions", "v1beta1", map[string]string{"c": "d"}},
+	}
+
+	resolver := newTestRequestInfoResolver()
+
+	for _, test := range tests {
+		req, _ := http.NewRequest("PUT", test.url, nil)
+
+		apiRequestInfo, err := resolver.NewRequestInfo(req)
```
Comment (liggitt) [inline pkg/registry/extensions/replicaset/strategy_test.go]: I don't think you need to go all the way back to parsing request info from urls in this test... just build a request info directly to test the various api groups

File: pkg/registry/extensions/daemonset/strategy.go (hunk 24 above)
Comment (crimsonfaith91) [inline pkg/registry/extensions/daemonset/strategy.go]: From my understanding, it is better to silently drop the mutation attempts. As pointed out by you in previous unfinished [PR](https://github.com/kubernetes/kubernetes/pull/50348), failing the mutation attempts via validation breaks tests of old versions. Hence, this PR is created to silently drop the mutation attempts.

Comment (crimsonfaith91) [inline pkg/registry/extensions/daemonset/strategy.go]: @kow3ns

File: pkg/registry/extensions/replicaset/strategy_test.go (hunk 25 above)
Comment (crimsonfaith91) [inline pkg/registry/extensions/replicaset/strategy_test.go]: A `RequestInfo` object is created via `NewRequestInfo` [function](https://github.com/kubernetes/apiserver/blob/master/pkg/endpoints/request/requestinfo.go#L103), which parses the URL. In other words, a URL is required to create a `RequestInfo` object.

File: pkg/registry/extensions/daemonset/strategy.go (hunk 24 above)
Comment (liggitt) [inline pkg/registry/extensions/daemonset/strategy.go]: > failing the mutation attempts via validation breaks tests of old versions. Hence, this PR is created to silently drop the mutation attempts.

this is not working against old versions... it's explicitly working against new API versions and enforcing different semantics. silently accepting an API request to change a field and not actually changing it seems wrong

Comment (liggitt) [inline pkg/registry/extensions/daemonset/strategy.go]: I suppose we already do similar things for fields like TemplateGeneration. Have you checked to see what tools like `kubectl apply` do if asked to apply a change to this field? I assume they keep re-sending a patch thinking they can update the value

Comment (crimsonfaith91) [inline pkg/registry/extensions/daemonset/strategy.go]: > this is not working against old versions... it's explicitly working against new API versions and enforcing different semantics. silently accepting an API request to change a field and not actually changing it seems wrong

Both this and previous PRs target new API versions. The previous PR breaks the old versions, but not this PR.

Comment (crimsonfaith91) [inline pkg/registry/extensions/daemonset/strategy.go]: >I suppose we already do similar things for fields like TemplateGeneration. Have you checked to see what tools like kubectl apply do if asked to apply a change to this field? I assume they keep re-sending a patch thinking they can update the value

Yes, `kubectl apply` will send the patch, but the update does not happen. We have to inform users about this change. Release note helps, but i think we should do more.

Comment (lavalamp) [inline pkg/registry/extensions/daemonset/strategy.go]: Silently dropping requests is a breaking API change, IMO.

I think if you want to do this you need to make the old version actually make the change.

Comment (kow3ns) [inline pkg/registry/extensions/daemonset/strategy.go]: @lavalamp v1beta1 doesn't drop the request, it continues to behave as normal. v1beta2 drops the request. It releases in 1.8.

File: pkg/registry/extensions/replicaset/strategy_test.go (hunk 25 above)
Comment (liggitt) [inline pkg/registry/extensions/replicaset/strategy_test.go]: build it directly to test the bits you are using here, e.g.:
```
&request.RequestInfo{
  APIGroup: "extensions",
  APIVersion: "v1beta1",
  Resource: "replicasets"
}
```

Comment (crimsonfaith91) [inline pkg/registry/extensions/replicaset/strategy_test.go]: sure!

File: pkg/registry/extensions/daemonset/strategy.go [hunk 26]
```diff
@@ -70,6 +70,15 @@ func (daemonSetStrategy) PrepareForUpdate(ctx genericapirequest.Context, obj, ol
 	// update is not allowed to set TemplateGeneration
 	newDaemonSet.Spec.TemplateGeneration = oldDaemonSet.Spec.TemplateGeneration
 
+	// Update is not allowed to set Spec.Selector for all groups/versions except extensions/v1beta1.
+	// If RequestInfo is nil, it is better to revert to old behavior (i.e. allow update to set Spec.Selector)
+	// to prevent unintentionally breaking users who may rely on the old behavior.
+	// TODO(#50791): after v1beta1 is retired, move selector immutability check to validation codes
+	requestInfo, found := genericapirequest.RequestInfoFrom(ctx)
+	if found && !(requestInfo.APIGroup == "extensions" && requestInfo.APIVersion == "v1beta1") {
```
Comment (liggitt) [inline pkg/registry/extensions/daemonset/strategy.go]: this might be clearer as a switch of the versions we expect:

```
if requestInfo, found := genericapirequest.RequestInfoFrom(ctx); found {
  groupVersion := schema.GroupVersion{Group: requestInfo.APIGroup, Version: requestInfo.APIVersion}
  switch groupVersion {
    case extensionsv1beta1.SchemeGroupVersion:
      // no-op for compatibility
    case appsv1beta2.SchemeGroupVersion:
      // disallow mutation of selector
      newDaemonSet.Spec.Selector = oldDaemonSet.Spec.Selector
    default:
      // error? panic? default to disallowing mutation?
  }
}
```

File: pkg/registry/extensions/deployment/strategy.go [hunk 27]
```diff
@@ -77,6 +77,16 @@ func (deploymentStrategy) PrepareForUpdate(ctx genericapirequest.Context, obj, o
 	oldDeployment := old.(*extensions.Deployment)
 	newDeployment.Status = oldDeployment.Status
 
+	// Update is not allowed to set Spec.Selector for all groups/versions except apps/v1beta1 and extensions/v1beta1.
+	// If RequestInfo is nil, it is better to revert to old behavior (i.e. allow update to set Spec.Selector)
+	// to prevent unintentionally breaking users who may rely on the old behavior.
+	// TODO(#50791): after v1beta1 is retired, move selector immutability check to validation codes
+	requestInfo, found := genericapirequest.RequestInfoFrom(ctx)
+	if found && !((requestInfo.APIGroup == "apps" || requestInfo.APIGroup == "extensions") &&
```
Comment (liggitt) [inline pkg/registry/extensions/deployment/strategy.go]: this would definitely be clearer as a switch of versions

File: pkg/registry/extensions/daemonset/strategy.go (hunk 26 above)
Comment (crimsonfaith91) [inline pkg/registry/extensions/daemonset/strategy.go]: Yes, this is clearer. For default case, we should not expect an error or a panic when preparing for an update operation. I had a discussion with @enisoc that we should fall back to old behavior when `RequestInfo` is not found. I think it also applies for the defaulting case (i.e., no-op).

Why we want to enumerate a case with no-op? I think this is better:
```
if requestInfo, found := genericapirequest.RequestInfoFrom(ctx); found {
  groupVersion := schema.GroupVersion{Group: requestInfo.APIGroup, Version: requestInfo.APIVersion}
  switch groupVersion {
    case appsv1beta2.SchemeGroupVersion:
      // disallow mutation of selector
      newDaemonSet.Spec.Selector = oldDaemonSet.Spec.Selector
  }
}
```

Comment (liggitt) [inline pkg/registry/extensions/daemonset/strategy.go]: > Why we want to enumerate a case with no-op? I think this is better

when v1 is added, you really want this to require a decision to be made about this behavior, rather than defaulting to allow mutation or disallow mutation

Comment (enisoc) [inline pkg/registry/extensions/daemonset/strategy.go]: Earlier, we agreed that we'd treat unknown versions (`default:` case) with the new behavior -- disallow mutation. Basically we want an explicit list of "legacy" versions (because we can make that list now and it will never change), and anything else defaults to the new behavior.

In this case, the the switch will only have one `case` and one `default` so it's basically an `if` statement. However, I agree that the general pattern of a switch makes sense; for example it will be clearer for Deployment where we'll list 2 legacy GroupVersions.

Comment (crimsonfaith91) [inline pkg/registry/extensions/daemonset/strategy.go]: Yes, but we can add the case at that moment (if the case requires an operation). Afaik, we have to make a change at that moment.

Comment (crimsonfaith91) [inline pkg/registry/extensions/daemonset/strategy.go]: @enisoc I think switch pattern is better too. However, as `DaemonSet` and `ReplicaSet` only have one legacy version, is it necessary to use the switch pattern?

Comment (enisoc) [inline pkg/registry/extensions/daemonset/strategy.go]: > when v1 is added, you really want this to require a decision to be made about this behavior

If there's a way to require this decision at compile time, I am definitely in favor. We can't return an error because the function signature doesn't allow it, so our only other option would be to panic. Then we would be relying on test coverage to check for mutating selectors in the new version.

If we have to rely on test coverage anyway, I would rather rely on tests being added at the point when this check moves to validation (after all legacy versions are removed). When we add the test to ensure the new validation triggers an error, that test will fail until we rip out this code.

Comment (liggitt) [inline pkg/registry/extensions/daemonset/strategy.go]: > Then we would be relying on test coverage to check for mutating selectors in the new version.

the default case gets hit whether or not you mutate a selector

File: pkg/registry/extensions/daemonset/strategy.go (hunk 24 above)
Comment (lavalamp) [inline pkg/registry/extensions/daemonset/strategy.go]: Ah, I misunderstood @liggitt's comment.

Comment (lavalamp) [inline pkg/registry/extensions/daemonset/strategy.go]: Is dropping the request in v1beta2 really better than returning an error? I don't think it is. Users that this breaks can go back to v1beta1.

Comment (liggitt) [inline pkg/registry/extensions/daemonset/strategy.go]: > Is dropping the request in v1beta2 really better than returning an error? I don't think it is. Users that this breaks can go back to v1beta1.

@smarterclayton raised the same concern in https://github.com/kubernetes/kubernetes/issues/50808#issuecomment-324734634

**Comment by xiang90** [comment]
@crimsonfaith91 

Why do we keep this immutable by ignoring users' inputs rather than returning an error when users try to modify immutable fields? I feel we should not do this. Silently dropping/modifying user input almost always cause unexpected result.

File: pkg/registry/extensions/daemonset/strategy.go (hunk 26 above)
Comment (enisoc) [inline pkg/registry/extensions/daemonset/strategy.go]: > the default case gets hit whether or not you mutate a selector

Ah, good point. So any attempt to update an object via that GroupVersion will panic? That sounds good to me then.

**Comment by enisoc** [comment]
@crimsonfaith91 Is there any reason we can't do this in `ValidateUpdate()` and make it a validation error only for certain versions? We pass the same `ctx` to that function so it should have the same `RequestInfo`.

**Comment by crimsonfaith91** [comment]
@enisoc Did you mean a change like this unfinished [PR](https://github.com/kubernetes/kubernetes/pull/50348)? The PR is closed as it breaks old API versions. This PR is created afterwards, introducing silent ignore of selector changes to prevent old API versions from breaking.

**Comment by enisoc** [comment]
@crimsonfaith91 Not exactly. I'm saying we can combine the approaches of that PR and this one and get the best of both: a true validation error that only happens when you use the new API version(s).

It would work like this:

1. Bring back `ValidateSelector()` #50348 but don't call it from `ValidateXxxUpdate()`.
1. In each controller's `Strategy.ValidateUpdate()`, use the `RequestInfo` from `ctx` to determine the version like you do in this PR.
1. Implement a `switch` on the version that calls `ValidateSelector()` directly from `Strategy.ValidateUpdate()` and appends the errors, only for `apps/v1beta2`.
1. For existing legacy versions, or if `RequestInfo` is not found, do *not* call `ValidateSelector()`.
1. As discussed above, panic for unknown versions so we will be forced to update this code when we add a new one.

**Comment by crimsonfaith91** [comment]
@enisoc Thank you for the very detailed step. The main reasons i initially changed `PrepareForUpdate` function were:
(1) misunderstood that the change has to be _before_ update
(2) validation should not be changed at all (i.e., silent ignore is the only way to go)
(3) most importantly, i didn't proactively search for the better `ValidateUpdate` function

I believe the new suggested way will work better. As soon as consensus reaches, i am confident to send out a PR within a few hours.

File: pkg/apis/extensions/validation/validation.go [hunk 28]
```diff
@@ -886,3 +887,14 @@ func ValidatePodSecurityPolicyUpdate(old *extensions.PodSecurityPolicy, new *ext
 	allErrs = append(allErrs, ValidatePodSecurityPolicySpec(&new.Spec, field.NewPath("spec"))...)
 	return allErrs
 }
+
+func ValidateSelectorImmutability(update *metav1.LabelSelector, old *metav1.LabelSelector) field.ErrorList {
```
Comment (xiang90) [inline pkg/apis/extensions/validation/validation.go]: why this func needs to return an error list?

**Comment by liggitt** [comment]
I think we have a reasonable place to do per-version validation and be able to return actual validation errors, which is good.

Let's resolve the question of total immutability vs orphaning prevention in https://github.com/kubernetes/kubernetes/issues/50808#issuecomment-324734027

File: pkg/apis/extensions/validation/validation.go [hunk 29]
```diff
@@ -886,3 +887,14 @@ func ValidatePodSecurityPolicyUpdate(old *extensions.PodSecurityPolicy, new *ext
...
+	allErrs := field.ErrorList{}
+	if update == nil || old == nil {
+		return allErrs
+	}
+	if !reflect.DeepEqual(update, old) {
+		allErrs = append(allErrs, field.Invalid(field.NewPath("spec").Child("selector"), update, "selector must not be changed after update"))
```
Comment (liggitt) [inline pkg/apis/extensions/validation/validation.go]: assuming the field path here isn't good, pass in the field path?

File: pkg/apis/extensions/validation/validation.go [hunk 30]
```diff
@@ -886,3 +887,14 @@ func ValidatePodSecurityPolicyUpdate(old *extensions.PodSecurityPolicy, new *ext
 	allErrs = append(allErrs, ValidatePodSecurityPolicySpec(&new.Spec, field.NewPath("spec"))...)
 	return allErrs
 }
+
+func ValidateSelectorImmutability(update *metav1.LabelSelector, old *metav1.LabelSelector) field.ErrorList {
+	allErrs := field.ErrorList{}
+	if update == nil || old == nil {
```
Comment (liggitt) [inline pkg/apis/extensions/validation/validation.go]: why is it considered ok if update == nil and old != nil?

File: pkg/registry/extensions/daemonset/strategy.go [hunk 31]
```diff
@@ -109,9 +112,27 @@ func (daemonSetStrategy) AllowCreateOnUpdate() bool {
...
+	if requestInfo, found := genericapirequest.RequestInfoFrom(ctx); found {
+		groupVersion := schema.GroupVersion{Group: requestInfo.APIGroup, Version: requestInfo.APIVersion}
+		switch groupVersion {
+		case extensionsv1beta1.SchemeGroupVersion:
+			// no-op for compatibility
+		case appsv1beta2.SchemeGroupVersion:
+			// disallow mutation of selector
+			allErrs = append(allErrs, validation.ValidateSelectorImmutability(obj.(*extensions.DaemonSet).Spec.Selector, old.(*extensions.DaemonSet).Spec.Selector)...)
+		default:
+			panic("unsupported group version for validate selector immutability")
```
Comment (liggitt) [inline pkg/registry/extensions/daemonset/strategy.go]: nit: make the error message clear this is an unexpected group that should be added to the switch, e.g.

`panic(fmt.Sprintf("unexpected group/version: %v", groupVersion))`

Comment (crimsonfaith91) [reply pkg/registry/extensions/daemonset/strategy.go]: Yes, this is clearer.

File: pkg/apis/extensions/validation/validation.go (hunk 30 above)
Comment (crimsonfaith91) [reply pkg/apis/extensions/validation/validation.go]: When an update is nil but another isn't, there should be an error.
When both updates are nil, there should be no error.

```
allErrs := field.ErrorList{}
if update == nil && old == nil {
	return allErrs
}
if !reflect.DeepEqual(update, old) { 
	allErrs = append(allErrs, field.Invalid(field.NewPath("spec").Child("selector"), update, "selector must not be changed after update"))
}
return allErrs
```

File: test/integration/deployment/deployment_test.go [hunk 32]
```diff
@@ -69,3 +73,76 @@ func TestNewDeployment(t *testing.T) {
...
+	updatedDeploymentAppsV1beta1, err := c.AppsV1beta1().Deployments(ns.Name).Update(deploymentAppsV1beta1)
+	if err != nil {
+		t.Fatalf("failed to update apps/v1beta1 deployment %s: %v", deploymentAppsV1beta1.Name, err)
+	}
+	if !reflect.DeepEqual(updatedDeploymentAppsV1beta1.Spec.Selector.MatchLabels, newSelectorLabels) {
+		t.Errorf("selector should be changed for apps/v1beta1, expected: %v, got: %v", newSelectorLabels, updatedDeploymentAppsV1beta1.Spec.Selector.MatchLabels)
+	}
+
+	// test to ensure apps/v1beta2 selector is immutable
+	// TODO(#50791): change this to expect an error after selector immutability codes are moved to validation
```
Comment (enisoc) [inline test/integration/deployment/deployment_test.go]: You can remove this now.

File: pkg/apis/extensions/validation/validation.go (hunk 29 above)
Comment (crimsonfaith91) [reply pkg/apis/extensions/validation/validation.go]: Sure! let's make `spec.selector` a parameter.

File: test/integration/deployment/deployment_test.go [hunk 33]
```diff
@@ -69,3 +73,76 @@ func TestNewDeployment(t *testing.T) {
...
+		&field.Error{
+			Type:  field.ErrorTypeInvalid,
+			Field: field.NewPath("spec").Child("selector").String(),
+			BadValue: &metav1.LabelSelector{
+				MatchLabels: newSelectorLabels,
+			},
+			Detail: "selector must not be changed after update",
+		},
+	}
+	expectedErrMessage := fmt.Sprintf("Deployment.apps \"%s\" is invalid: %v", name, expectedErrList.ToAggregate())
```
Comment (enisoc) [inline test/integration/deployment/deployment_test.go]: Instead of `\"%s\"` you can use `%q`.

File: test/integration/deployment/deployment_test.go [hunk 34]
```diff
@@ -69,3 +73,76 @@ func TestNewDeployment(t *testing.T) {
...
+	errMessage := fmt.Sprintf("%v", err)
+	if errMessage != expectedErrMessage {
```
Comment (enisoc) [inline test/integration/deployment/deployment_test.go]: You can just do `if err.Error() != ...`.

File: test/integration/deployment/deployment_test.go (hunk 33 above)
Comment (enisoc) [reply test/integration/deployment/deployment_test.go]: It's best not to be so specific when testing error messages. We don't want minor changes in the error message to break the test, especially since this is at the integration level.

Often we relax the error matching to things like `strings.Contains` to look for the error type and detail.

File: test/integration/deployment/deployment_test.go (hunk 34 above)
Comment (crimsonfaith91) [reply test/integration/deployment/deployment_test.go]: Thanks, this is more concise!

File: test/integration/deployment/deployment_test.go (hunk 33 above)
Comment (crimsonfaith91) [reply test/integration/deployment/deployment_test.go]: Make sense - I will test against error type and detail only using `strings.Contains`.

File: test/integration/deployment/deployment_test.go (hunk 32 above)
Comment (crimsonfaith91) [reply test/integration/deployment/deployment_test.go]: Ya, the codes already did so.

File: pkg/registry/extensions/daemonset/strategy.go [hunk 35]
```diff
@@ -109,9 +112,27 @@ func (daemonSetStrategy) AllowCreateOnUpdate() bool {
...
-	validationErrorList := validation.ValidateDaemonSet(obj.(*extensions.DaemonSet))
-	updateErrorList := validation.ValidateDaemonSetUpdate(obj.(*extensions.DaemonSet), old.(*extensions.DaemonSet))
-	return append(validationErrorList, updateErrorList...)
+	allErrs := validation.ValidateDaemonSet(obj.(*extensions.DaemonSet))
+	allErrs = append(allErrs, validation.ValidateDaemonSetUpdate(obj.(*extensions.DaemonSet), old.(*extensions.DaemonSet))...)
+
+	// Update is not allowed to set Spec.Selector for all groups/versions except extensions/v1beta1.
+	// If RequestInfo is nil, it is better to revert to old behavior (i.e. allow update to set Spec.Selector)
+	// to prevent unintentionally breaking users who may rely on the old behavior.
+	// TODO(#50791): after v1beta1 is retired, move selector immutability check to validation codes
```
[the remark this answers is not in the document]
Comment (crimsonfaith91) [reply pkg/registry/extensions/daemonset/strategy.go]: Ya, this will be more precise.

File: pkg/registry/extensions/daemonset/strategy.go [hunk 36]
```diff
@@ -109,9 +112,27 @@ func (daemonSetStrategy) AllowCreateOnUpdate() bool {
 
 // ValidateUpdate is the default update validation for an end user.
 func (daemonSetStrategy) ValidateUpdate(ctx genericapirequest.Context, obj, old runtime.Object) field.ErrorList {
-	validationErrorList := validation.ValidateDaemonSet(obj.(*extensions.DaemonSet))
-	updateErrorList := validation.ValidateDaemonSetUpdate(obj.(*extensions.DaemonSet), old.(*extensions.DaemonSet))
-	return append(validationErrorList, updateErrorList...)
+	allErrs := validation.ValidateDaemonSet(obj.(*extensions.DaemonSet))
```
[the remark this answers is not in the document]
Comment (crimsonfaith91) [reply pkg/registry/extensions/daemonset/strategy.go]: good point

File: pkg/apis/extensions/validation/validation.go (hunk 30 above)
Comment (crimsonfaith91) [reply pkg/apis/extensions/validation/validation.go]: I will remove this function and use `ValidateImmutableField()` from `k8s.io/apimachinery/pkg/api/validation` as suggested by enisoc.

File: test/integration/deployment/deployment_test.go [hunk 37]
```diff
@@ -130,19 +128,9 @@ func TestDeploymentSelectorImmutability(t *testing.T) {
...
-			Detail: "selector must not be changed after update",
-		},
-	}
-	expectedErrMessage := fmt.Sprintf("Deployment.apps \"%s\" is invalid: %v", name, expectedErrList.ToAggregate())
-	errMessage := fmt.Sprintf("%v", err)
-	if errMessage != expectedErrMessage {
-		t.Errorf("error message does not matched, expected: %v, got: %s", expectedErrMessage, errMessage)
+	expectedErrType := "Invalid value"
+	expectedErrDetail := "field is immutable"
+	if !strings.Contains(err.Error(), expectedErrType) || !strings.Contains(err.Error(), expectedErrDetail) {
```
Comment (crimsonfaith91) [inline test/integration/deployment/deployment_test.go]: Another way is to test the type and detail conditions separately.

```
if !strings.Contains(err.Error(), expectedErrType) {
    t.Errorf("error type does not match, expected type: %s, got: %s", expectedErrType, err.Error())
}

if !strings.Contains(err.Error(), expectedErrDetail) {
    t.Errorf("error message detail does not match, expected detail: %s, got: %s", expectedErrDetail, err.Error())
}
```

**Comment by liggitt** [comment]
a fix for the firewall e2e error merged to master, but the e2e tests don't seem to be running against the new commit... might need to rebase

**Comment by liggitt** [comment]
this is definitely worth a release note

**Comment by crimsonfaith91** [comment]
@liggitt i will write the release note. Do you mind to approve it? Thx.

**Comment by crimsonfaith91** [comment]
@smarterclayton Do you mind to approve this PR? Thanks!

**Comment by liggitt** [comment]
/lgtm
though I am not an approver on pkg/registry

**Comment by crimsonfaith91** [comment]
@liggitt Yup! i contacted Clayton for approval. :)
