### PR TITLE
kubeadm: improve the kubeconfig file validation phase

### LINKED ISSUE #79069: panic during `kubeadm init phase kubeconfig all`
```
kubeadm init phase kubeconfig all
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/admin.conf"
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/kubelet.conf"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x116df4b]

goroutine 1 [running]:
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.validateKubeConfig(0x1832c77, 0xf, 0x183d82d, 0x17, 0xc000080420, 0xc000284000, 0xc000285800)
        /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:242 +0x19b
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.createKubeConfigFileIfNotExists(0x1832c77, 0xf, 0x183d82d, 0x17, 0xc000080420, 0x0, 0x0)
        /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:263 +0x108
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.createKubeConfigFiles(0x1832c77, 0xf, 0xc00024a000, 0xc0001a9a60, 0x1, 0x1, 0x18e2dc0, 0xc0001a9a80)
        /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:122 +0x142
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.CreateKubeConfigFile(0x183d82d, 0x17, 0x1832c77, 0xf, 0xc00024a000, 0x8b9bee3c1af8801, 0xc0001a9b30)
        /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:95 +0xe2
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runKubeConfigFile.func1(0x17ad400, 0xc000358210, 0x0, 0x0)
        /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/kubeconfig.go:143 +0x1b7
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1(0xc00021d500, 0x0, 0x0)
        /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235 +0x11a
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll(0xc0000d5dd0, 0xc0001a9c78, 0x0, 0x0)
        /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:420 +0x6e
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run(0xc0000d5dd0, 0x29e6660, 0x0, 0x0, 0x1826a06, 0x4)
        /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:208 +0x14e
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).BindToCommand.func1.1(0xc000525680, 0x29e6660, 0x0, 0x0)
        /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:349 +0xeb
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000525680, 0x29e6660, 0x0, 0x0, 0xc000525680, 0x29e6660)
        /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:760 +0x2ae
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00011fb80, 0xc0000aa000, 0x1a811a0, 0xc0000aa008)
        /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2ec
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:794
k8s.io/kubernetes/cmd/kubeadm/app.Run(0x0, 0x918)
        /workspace/anago-v1.14.3-beta.0.37+5e53fd6bc17c0d/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50 +0x210
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:29 +0x33
```

**What happened**:
[kubeconfig] Using existing kubeconfig file: "/etc/kubernetes/kubelet.conf"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x116df4b]

**What you expected to happen**:
should pass OK, or return an message describing what's wrong.

**How to reproduce it (as minimally and precisely as possible)**:
run `kubeadm init phase kubeconfig all`

**Anything else we need to know?**:
My cluster failed due to expired certs, I followed https://stackoverflow.com/questions/56320930/renew-kubernetes-pki-after-expired to recover it, but /etc/kubernetes/bootstrap-kubelet.conf got MIA - so I copied it from another node. also /etc/kubernetes/admin.conf got missing, so I copied that from /root/.kube/config. after that I tried `kubeadm init phase kubeconfig all` which panics.

**Environment**:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)

- Cloud provider or hardware configuration:
bare-metal
- OS (e.g: `cat /etc/os-release`):
cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):
uname -a
Linux main.lan.davidkarlsen.com 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
kubeadm

- Network plugin and version (if this is a network-related bug):
calico
- Others:

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:
When a kubeconfig file is read from disk it may lack the
propper mapping between contexts and clusters.

In such a case the kubeconfig phase backend will panic,
without throwing a sensible error.

Add nil checks for a couple of map operations in
validateKubeConfig().

**Which issue(s) this PR fixes**:

Fixes #79069
xref https://github.com/kubernetes/kubeadm/issues/1382

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: fix a potential panic if kubeadm discovers an invalid, existing kubeconfig file
```

/priority backlog
/assign @fabriziopandini @rosti 
/kind bug
@kubernetes/sig-cluster-lifecycle-pr-reviews 
/hold

### CODE REVIEW

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go [hunk 1]
```diff
@@ -224,7 +224,13 @@ func validateKubeConfig(outDir, filename string, config *clientcmdapi.Config) er
 	expectedCtx := config.CurrentContext
 	expectedCluster := config.Contexts[expectedCtx].Cluster
 	currentCtx := currentConfig.CurrentContext
+	if config.Contexts[currentCtx] == nil {
```
Comment (yagonobre) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go]: Should it be `currentConfig`? Also, should we check the `config.Contexts[expectedCtx].Cluster` above?

**Review by yagonobre — COMMENTED** [review]
Thanks @neolit123

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go]: >Should it be currentConfig?  

yeah already sent a change.

> Also, should we check the config.Contexts[expectedCtx].Cluster above

its a file we just generated, so doesn't seem we need to.

**Review by rosti — APPROVED** [review]
Thanks @neolit123 !
/lgtm

**Review by yagonobre — COMMENTED** [review]
/lgtm

**Comment by neolit123** [comment]
/hold cancel
thanks

**Review by fabriziopandini — COMMENTED** [review]
@neolit123 many thanks for this fix!
/approve
/lgtm

Are U planning to back port this fix in older releases?
