### PR TITLE
Fix service health check node port leaks

### LINKED ISSUE #31757: Prevent leaking health check service node ports
If a service with the ESIPP annotation is created, a health check node port is allocated (and the value stored in an annotation).

If, subsequently, the following cases happen, we need to free the health check node port back to the NodePortAllocator.

a) Service is deleted
b) The HealthCheckNodePort annotation is deleted.
c) The ESIPP annotation is deleted.
d) Both annotations are deleted.

### PR DESCRIPTION
**Pull request by girishkalele**
Fixed #31757

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31990)

### CODE REVIEW

File: pkg/registry/service/rest.go [hunk 1]
```diff
@@ -157,7 +157,7 @@ func (rs *REST) Create(ctx api.Context, obj runtime.Object) (runtime.Object, err
 		}
 	}
 
-	if featuregate.DefaultFeatureGate.ExternalTrafficLocalOnly() && shouldCheckOrAssignHealthCheckNodePort(service) {
```
Comment (smarterclayton) [inline pkg/registry/service/rest.go]: Why remove the gate check?

File: pkg/registry/service/rest.go [hunk 2]
```diff
@@ -265,6 +275,97 @@ func (*REST) NewList() runtime.Object {
...
+	switch {
+	case !oldServiceHasHealthCheckNodePort && assignHealthCheckNodePort:
+		glog.Infof("Transition from Global LB service to OnlyLocal service")
+		if requestedHealthCheckNodePort > 0 {
+			// If the request has a health check nodePort in mind, attempt to reserve it
+			err := rs.serviceNodePorts.Allocate(int(requestedHealthCheckNodePort))
+			if err != nil {
+				errmsg := fmt.Sprintf("Failed to allocate requested HealthCheck nodePort %v:%v",
+					requestedHealthCheckNodePort, err)
+				el := field.ErrorList{field.Invalid(field.NewPath("ObjectMeta", "Annotations"),
```
Comment (smarterclayton) [inline pkg/registry/service/rest.go]: Fieldpaths should be for dominant external version name, "metadata", "annotations", etc.

Comment (girishkalele) [inline pkg/registry/service/rest.go]: Ok, will change the fieldpath to "annotations".

File: pkg/registry/service/rest.go (hunk 1 above)
Comment (girishkalele) [inline pkg/registry/service/rest.go]: The feature gate check already exists in that function being called (`shouldCheckOrAssignHealthCheckNodePort), so removed the redundant check here.

https://github.com/girishkalele/kubernetes/blob/master/pkg/registry/service/rest.go#L458

**Comment by girishkalele** [comment]
@smarterclayton Updated. PTAL.

File: pkg/registry/service/rest.go [hunk 3]
```diff
@@ -234,6 +234,16 @@ func (rs *REST) Delete(ctx api.Context, id string) (runtime.Object, error) {
 		}
 	}
 
+	if shouldCheckOrAssignHealthCheckNodePort(service) {
+		nodePort := apiservice.GetServiceHealthCheckNodePort(service)
+		if nodePort > 0 {
+			err := rs.serviceNodePorts.Release(int(nodePort))
+			if err != nil {
+				// these should be caught by an eventual reconciliation / restart
+				glog.Errorf("Error releasing service health check %s node port %d: %v", service.Name, nodePort, err)
```
Comment (smarterclayton) [inline pkg/registry/service/rest.go]: use `utilruntime.HandleError` anytime you eat an error (that allows us to plug in error shipping plugins and track them externally).  The default behavior is glog.Errorf so is exactly equal

**Comment by smarterclayton** [comment]
One comment

File: pkg/registry/service/rest.go [hunk 4]
```diff
@@ -342,6 +443,11 @@ func (rs *REST) Update(ctx api.Context, name string, objInfo rest.UpdatedObjectI
 		service.Status.LoadBalancer = api.LoadBalancerStatus{}
 	}
 
+	success, err := rs.healthCheckNodePortUpdate(oldService, service)
```
Comment (smarterclayton) [inline pkg/registry/service/rest.go]: Should this be feature gated?

**Comment by girishkalele** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/registry/service/rest.go, line 446 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31990#-KQg-Icrg7f5JUDHTBrp-r2-446:-KR5TXtjyP29qPNpeaxI:b-lf0b2o) ([raw file](https://github.com/kubernetes/kubernetes/blob/4e5d08a3a11ce9d626c03927fd6940ab3b869971/pkg/registry/service/rest.go#L446)):*
<details><summary><i>Previously, smarterclayton (Clayton Coleman) wrote…</i></summary>
> Should this be feature gated?
</details>
Good point - yes, I need to add feature gates to the new calls in Delete and Update.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31990)*

File: pkg/registry/service/rest.go (hunk 4 above)
Comment (girishkalele) [inline pkg/registry/service/rest.go]: Good point - yes, I need to add feature gates to the new calls in Delete and Update.

Comment (girishkalele) [inline pkg/registry/service/rest.go]: Actually, Delete already has the feature gate. healthCheckNodePortUpdate() internally has the feature gate check, but it is not complete, will fix that up.

File: pkg/registry/service/rest.go (hunk 2 above)
Comment (smarterclayton) [inline pkg/registry/service/rest.go]: Maybe github is broken but i don't see the change - should be `field.NewPath("metadata", "annotations")` in all these checks

File: pkg/registry/service/rest.go [hunk 5]
```diff
@@ -265,6 +276,97 @@ func (*REST) NewList() runtime.Object {
...
+	// Case 3. No change (Global ---stays--> Global) but prevent invalid annotation manipulations
+	//
+	//   Reject insertion of the "service.alpha.kubernetes.io/healthcheck-nodeport" annotation
+	//
+	// Case 4. No change (OnlyLocal ---stays--> OnlyLocal) but prevent invalid annotation manipulations
+	//
+	//   Reject deletion of the "service.alpha.kubernetes.io/healthcheck-nodeport" annotation
+	//   Reject changing the value of the healthCheckNodePort annotation
+	//
+	oldServiceHasHealthCheckNodePort := shouldCheckOrAssignHealthCheckNodePort(oldService)
```
Comment (girishkalele) [inline pkg/registry/service/rest.go]: Added missing feature gate check here.

File: pkg/registry/service/rest.go [hunk 6]
```diff
@@ -265,6 +276,97 @@ func (*REST) NewList() runtime.Object {
...
+			glog.Warningf("Attempt to insert health check node port annotation DENIED")
+			el := field.ErrorList{field.Invalid(field.NewPath("metadata", "annotations"),
+				apiservice.AnnotationHealthCheckNodePort, "Cannot insert healthcheck nodePort annotation")}
+			return false, errors.NewInvalid(api.Kind("Service"), service.Name, el)
+		}
+
+	case oldServiceHasHealthCheckNodePort && assignHealthCheckNodePort:
+		if _, ok := service.Annotations[apiservice.AnnotationHealthCheckNodePort]; !ok {
+			glog.Warningf("Attempt to delete health check node port annotation DENIED")
+			el := field.ErrorList{field.Invalid(field.NewPath("metadata", "annotations"),
```
Comment (girishkalele) [inline pkg/registry/service/rest.go]: Github not broken, it was me, I forgot to add that to the commit. Fixed now.

File: pkg/registry/service/rest.go [hunk 7]
```diff
@@ -234,6 +235,16 @@ func (rs *REST) Delete(ctx api.Context, id string) (runtime.Object, error) {
 		}
 	}
 
+	if shouldCheckOrAssignHealthCheckNodePort(service) {
+		nodePort := apiservice.GetServiceHealthCheckNodePort(service)
+		if nodePort > 0 {
+			err := rs.serviceNodePorts.Release(int(nodePort))
+			if err != nil {
+				// these should be caught by an eventual reconciliation / restart
+				utilruntime.HandleError(fmt.Errorf("Error releasing service health check %s node port %d: %v", service.Name, nodePort, err))
```
Comment (girishkalele) [inline pkg/registry/service/rest.go]: Changed to utilruntime.HandleError here.

**Comment by thockin** [comment]
ping @smarterclayton 1.4 blocker

**Comment by thockin** [comment]
Actually, I take that back, this should not block 1.4.0, the feature is alpha anyway, still..

File: pkg/registry/service/rest.go [hunk 8]
```diff
@@ -157,7 +158,7 @@ func (rs *REST) Create(ctx api.Context, obj runtime.Object) (runtime.Object, err
 		}
 	}
 
-	if featuregate.DefaultFeatureGate.ExternalTrafficLocalOnly() && shouldCheckOrAssignHealthCheckNodePort(service) {
+	if shouldCheckOrAssignHealthCheckNodePort(service) {
```
Comment (bprashanth) [inline pkg/registry/service/rest.go]: you have a comment below that I don't understand "Insert the newly allocated health check port as an annotation (plan of record for Alpha)", can you clarify it.

File: pkg/registry/service/rest.go [hunk 9]
```diff
@@ -157,7 +158,7 @@ func (rs *REST) Create(ctx api.Context, obj runtime.Object) (runtime.Object, err
...
 		var healthCheckNodePort int
 		var err error
 		if l, ok := service.Annotations[apiservice.AnnotationHealthCheckNodePort]; ok {
```
Comment (bprashanth) [inline pkg/registry/service/rest.go]: Doesn't `GetServiceHealthCheckNodePort` do this for you? maybe you just return an err and int32 as the distinction between "no node port specified" and "node port specified but couldn't parse".  What do we think should happen if user sets it to 0? currently we clobber it. Maybe we should throw an error instead? 

Leave it to you to do what you think is cleaner, just bringing it up because I observed duplicated code.

File: pkg/registry/service/rest.go [hunk 10]
```diff
@@ -265,6 +276,97 @@ func (*REST) NewList() runtime.Object {
...
+	//
+	// Case 4. No change (OnlyLocal ---stays--> OnlyLocal) but prevent invalid annotation manipulations
+	//
+	//   Reject deletion of the "service.alpha.kubernetes.io/healthcheck-nodeport" annotation
+	//   Reject changing the value of the healthCheckNodePort annotation
+	//
+	oldServiceHasHealthCheckNodePort := shouldCheckOrAssignHealthCheckNodePort(oldService)
+	oldHealthCheckNodePort := apiservice.GetServiceHealthCheckNodePort(oldService)
+
+	assignHealthCheckNodePort := shouldCheckOrAssignHealthCheckNodePort(service)
```
Comment (bprashanth) [inline pkg/registry/service/rest.go]: the name of this function is confusing and makes me think it's doing 2 different things. Can you clarify the name or add a comment above it. It returns a bool, so the shouldCheck part doesn't make sense to me.

File: pkg/registry/service/rest.go [hunk 11]
```diff
@@ -265,6 +276,97 @@ func (*REST) NewList() runtime.Object {
...
+			// If the request has a health check nodePort in mind, attempt to reserve it
+			err := rs.serviceNodePorts.Allocate(int(requestedHealthCheckNodePort))
+			if err != nil {
+				errmsg := fmt.Sprintf("Failed to allocate requested HealthCheck nodePort %v:%v",
+					requestedHealthCheckNodePort, err)
+				el := field.ErrorList{field.Invalid(field.NewPath("metadata", "annotations"),
+					apiservice.AnnotationHealthCheckNodePort, errmsg)}
+				return false, errors.NewInvalid(api.Kind("Service"), service.Name, el)
+			}
+			glog.Infof("Reserved user requested nodePort: %d", requestedHealthCheckNodePort)
```
Comment (bprashanth) [inline pkg/registry/service/rest.go]: Not sure if anything else uses Infof.V(2) in apiserver logs. If you open it up all you'll see is Http requests and latency traces. Suggest converting to V(4) everywhere in its currently V(2) in this pr.

File: pkg/registry/service/rest.go [hunk 12]
```diff
@@ -265,6 +276,97 @@ func (*REST) NewList() runtime.Object {
...
+				apiservice.AnnotationHealthCheckNodePort, "Cannot delete healthcheck nodePort annotation")}
+			return false, errors.NewInvalid(api.Kind("Service"), service.Name, el)
+		}
+		if oldHealthCheckNodePort != requestedHealthCheckNodePort {
+			glog.Warningf("Attempt to change value of health check node port annotation DENIED")
+			el := field.ErrorList{field.Invalid(field.NewPath("metadata", "annotations"),
+				apiservice.AnnotationHealthCheckNodePort, "Cannot change healthcheck nodePort during update")}
+			return false, errors.NewInvalid(api.Kind("Service"), service.Name, el)
+		}
+	}
```
Comment (bprashanth) [inline pkg/registry/service/rest.go]: it's useful to add a comment here saying this is the "normal" update path, i.e the else clause is what happens if i modify labels on a Service using esipp.

File: pkg/registry/service/rest.go [hunk 13]
```diff
@@ -265,6 +276,97 @@ func (*REST) NewList() runtime.Object {
...
+			glog.Infof("Freed health check nodePort: %d", oldHealthCheckNodePort)
+		}
+
+	case !oldServiceHasHealthCheckNodePort && !assignHealthCheckNodePort:
+		if _, ok := service.Annotations[apiservice.AnnotationHealthCheckNodePort]; ok {
+			glog.Warningf("Attempt to insert health check node port annotation DENIED")
+			el := field.ErrorList{field.Invalid(field.NewPath("metadata", "annotations"),
+				apiservice.AnnotationHealthCheckNodePort, "Cannot insert healthcheck nodePort annotation")}
+			return false, errors.NewInvalid(api.Kind("Service"), service.Name, el)
+		}
```
Comment (bprashanth) [inline pkg/registry/service/rest.go]: worth adding a comment that this is what happens in the normal Service update case when the feature is gated (so every service on aws, azure etc).

**Comment by bprashanth** [comment]
I'd really like a unittest for the big switch case you have, otherwise i see mostly nits. Would be good to get this for 1.4 because otherwise toggling the annotation will leak nodeports. I'll take a follow up for the unittests if you prefer.

**Comment by girishkalele** [comment]
Review status: 0 of 1 files reviewed at latest revision, 12 unresolved discussions.

---

*[pkg/registry/service/rest.go, line 161 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31990#-KQg-Icrg7f5JUDHTBrp-r3-161:-KRFezezevUAj6QatETv:b-u0n6xl) ([raw file](https://github.com/kubernetes/kubernetes/blob/02754547fbbc9110358763aa38a9d3770af691f4/pkg/registry/service/rest.go#L161)):*
<details><summary><i>Previously, bprashanth (Prashanth B) wrote…</i></summary>
> you have a comment below that I don't understand "Insert the newly allocated health check port as an annotation (plan of record for Alpha)", can you clarify it.
</details>
I had there to remind me it needs to turn into an API field instead of annotation for GA.

---

*[pkg/registry/service/rest.go, line 164 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31990#-KQg-Icrg7f5JUDHTBrp-r3-164:-KRFfrL6BJ-9T9QhOkFn:bwj18md) ([raw file](https://github.com/kubernetes/kubernetes/blob/02754547fbbc9110358763aa38a9d3770af691f4/pkg/registry/service/rest.go#L164)):*
<details><summary><i>Previously, bprashanth (Prashanth B) wrote…</i></summary>
> Doesn't `GetServiceHealthCheckNodePort` do this for you? maybe you just return an err and int32 as the distinction between "no node port specified" and "node port specified but couldn't parse".  What do we think should happen if user sets it to 0? currently we clobber it. Maybe we should throw an error instead? 
> 
> 
> 
> Leave it to you to do what you think is cleaner, just bringing it up because I observed duplicated code. 
</details>
Yes, I thought I couldn't use the existing `GetServiceHealthCheckNodePort` because this code runs in the rest request context and returns NewInternalErrors(). I wouldn't want to change the `GetServiceHealthCheckNodePort` function at this stage, too many callers around. Maybe a TODO, but this is going to change from annotation to a service object field for GA (I think).

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31990)*

**Comment by girishkalele** [comment]
Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions.

---

*[pkg/registry/service/rest.go, line 243 \[r2\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31990#-KQg-Icrg7f5JUDHTBrp-r2-243:-KRFgWIQjWyn_YbQGAES:bb6un1j) ([raw file](https://github.com/kubernetes/kubernetes/blob/4e5d08a3a11ce9d626c03927fd6940ab3b869971/pkg/registry/service/rest.go#L243)):*
<details><summary><i>Previously, smarterclayton (Clayton Coleman) wrote…</i></summary>
> use `utilruntime.HandleError` anytime you eat an error (that allows us to plug in error shipping plugins and track them externally).  The default behavior is glog.Errorf so is exactly equal
</details>
Done

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31990)*

**Comment by girishkalele** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/registry/service/rest.go, line 303 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31990#-KQg-Icrg7f5JUDHTBrp-r3-303:-KRFglCB7I_iQPr4CDL3:b-sw6jd1) ([raw file](https://github.com/kubernetes/kubernetes/blob/02754547fbbc9110358763aa38a9d3770af691f4/pkg/registry/service/rest.go#L303)):*
<details><summary><i>Previously, bprashanth (Prashanth B) wrote…</i></summary>
> the name of this function is confusing and makes me think it's doing 2 different things. Can you clarify the name or add a comment above it. It returns a bool, so the shouldCheck part doesn't make sense to me. 
</details>
Renamed to `serviceNeedsHealthCheckNodePort`.

---

*[pkg/registry/service/rest.go, line 319 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31990#-KQg-Icrg7f5JUDHTBrp-r3-319:-KRFgyA1AVFcNMavQ_m9:bxj60ro) ([raw file](https://github.com/kubernetes/kubernetes/blob/02754547fbbc9110358763aa38a9d3770af691f4/pkg/registry/service/rest.go#L319)):*
<details><summary><i>Previously, bprashanth (Prashanth B) wrote…</i></summary>
> Not sure if anything else uses Infof.V(2) in apiserver logs. If you open it up all you'll see is Http requests and latency traces. Suggest converting to V(4) everywhere in its currently V(2) in this pr. 
</details>
Good point - changed all glog.Infof to glog.V(4).Infof.

---

*[pkg/registry/service/rest.go, line 351 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31990#-KQg-Icrg7f5JUDHTBrp-r3-351:-KRFhYfhyUEBkdzmkOt9:b-8b11j9) ([raw file](https://github.com/kubernetes/kubernetes/blob/02754547fbbc9110358763aa38a9d3770af691f4/pkg/registry/service/rest.go#L351)):*
<details><summary><i>Previously, bprashanth (Prashanth B) wrote…</i></summary>
> worth adding a comment that this is what happens in the normal Service update case when the feature is gated (so every service on aws, azure etc). 
</details>
Added

---

*[pkg/registry/service/rest.go, line 366 \[r3\]](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31990#-KQg-Icrg7f5JUDHTBrp-r3-366:-KRFi2jd1552OlHE0W-q:b-8b11j9) ([raw file](https://github.com/kubernetes/kubernetes/blob/02754547fbbc9110358763aa38a9d3770af691f4/pkg/registry/service/rest.go#L366)):*
<details><summary><i>Previously, bprashanth (Prashanth B) wrote…</i></summary>
> it's useful to add a comment here saying this is the "normal" update path, i.e the else clause is what happens if i modify labels on a Service using esipp. 
</details>
Added

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31990)*

**Comment by bprashanth** [comment]
LGTM because I want to try and get this into the next beta so we can have test time (though it might be tight). Please send unittests pr as follow up. Looks like you addressed all @smarterclayton 's comments as well.

**Comment by bprashanth** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/31990#-:-KRFqsjweWKkBBSY0oEK:bnfp4nl)*

**Comment by girishkalele** [comment]
@bprashanth Yes, I will take the unittests as a follow-up PR to this one.
