### PR TITLE
Fix exclusive CPU allocations being deleted at container restart

### LINKED ISSUE #90303: Container cpuset lost, apparently due to race between PostStopContainer() and new container creation
**What happened**:
A container which had exclusive CPUs assigned to it (and an entry in /var/lib/kubelet/cpu_manager_state specifying those CPUs) was killed.  When it came back, it was using the default cpuset, and its entry in /var/lib/kubelet/cpu_manager_state was gone.

**What you expected to happen**:
It should have been given exclusive CPUs.

**How to reproduce it (as minimally and precisely as possible)**:

Create a pod/container with "guaranteed" QoS.  Determine the exclusive CPUs allocated to the container.  From the host, kill pid1 within the container.  ("kill -9" works.)  The container will restart within the existing pod, but it will be allocated cpus from the default cpuset (which will now include the CPUs that had been exclusively allocated to the container earlier).

**Anything else we need to know?**:

I added some instrumentation to kubelet.  What seems to be happening is this:

1) The container is killed (or dies).  Kubelet then immediately creates a new container and calls PolicyStatic.Allocate() to allocate exclusive CPUs for it.  This updates the entry in /var/lib/kubelet/cpu_manager_state (and the in-memory cache) which is mapped by podUID and container name, such that it contains the cpuset for the new container.

2) The InternalContainerLifecycle.PostStopContainer() code runs, which calls i.cpuManager.RemoveContainer(containerID).  This uses the containerID of the exited container to look up the podUID/container-name tuple, then deletes the cpuset entry from  /var/lib/kubelet/cpu_manager_state (and the in-memory cache).  But the entry that was deleted was actually the one for the *new* container.

3) Kubelet calls the CPU manager's AddContainer() function, which calls m.state.GetCPUSetOrDefault(string(p.UID), c.Name) to get the cpuset based on the podUID and container name of the new container.  The cpuset entry was erroneously deleted, so this returns the default cpuset, and the container which *should* have gotten exclusive CPUs ends up running on the default cpuset.

An solution suggested by @klueska is to delay calling cpuManager.RemoveContainer() until the whole pod is deleted.  This would preserve the CPU allocations.

An alternate solution also suggested by @klueska is to avoid calling cpuManager.RemoveContainer() from the container lifecycle code, but instead call removeStaleState() in the CpuManager.Allocate() function.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.1
- Cloud provider or hardware configuration:   x86, SMP
- OS (e.g: `cat /etc/os-release`):  CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-1062.1.2.rt56.1025.el7

### PR DESCRIPTION
**Pull request by cbf123**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

The expectation is that exclusive CPU allocations happen at pod
creation time. When a container restarts, it should not have its
exclusive CPU allocations removed, and it should not need to
re-allocate CPUs.

There are a few places in the current code that look for containers
that have exited and call CpuManager.RemoveContainer() to clean up
the container.  This will end up deleting any exclusive CPU
allocations for that container, and if the container restarts within
the same pod it will end up using the default cpuset rather than
what should be exclusive CPUs.

Removing those calls and adding resource cleanup at allocation
time should get rid of the problem.

**Which issue(s) this PR fixes**:

Fixes #90303

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fixes regression in CPUManager that caused freeing of exclusive CPUs at incorrect times 
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by klueska** [comment]
We had a long discussion about this here for context:
https://kubernetes.slack.com/archives/C0BP8PW9G/p1587155932390500

File: pkg/kubelet/cm/internal_container_lifecycle.go [hunk 1]
```diff
@@ -54,19 +54,18 @@ func (i *internalContainerLifecycleImpl) PreStartContainer(pod *v1.Pod, containe
 }
 
 func (i *internalContainerLifecycleImpl) PreStopContainer(containerID string) error {
-	if i.cpuManager != nil {
-		return i.cpuManager.RemoveContainer(containerID)
-	}
+	// We can't safely call i.cpuManager.RemoveContainer(containerID)
+	// here. Regular containers could be in the process of restarting, and
+        // RemoveContainer() would remove any allocated exclusive CPUs that the
```
Comment (klueska) [inline pkg/kubelet/cm/internal_container_lifecycle.go:59]: Can you fix the indenting here?

File: pkg/kubelet/cm/internal_container_lifecycle.go [hunk 2]
```diff
@@ -54,19 +54,18 @@ func (i *internalContainerLifecycleImpl) PreStartContainer(pod *v1.Pod, containe
...
 func (i *internalContainerLifecycleImpl) PostStopContainer(containerID string) error {
-	if i.cpuManager != nil {
-		err := i.cpuManager.RemoveContainer(containerID)
-		if err != nil {
-			return err
-		}
-	}
+	// We can't safely call i.cpuManager.RemoveContainer(containerID)
+	// here. Regular containers could be in the process of restarting, and
+        // RemoveContainer() would remove any allocated exclusive CPUs that the
```
Comment (klueska) [inline pkg/kubelet/cm/internal_container_lifecycle.go:67]: I wouldn't bother with this comment here. I know we used to have code here that called RemoveContainer(), but it's more confusing to see the comment out of context, than to not see it at all -- especially since there is no path for calling RemoveContainer() from any external hooks anymore.

I actually plan to go through the TopologyManager after this and remove it's callout as well -- thus removing the need for this hook injection altogether.

**Review by klueska — CHANGES_REQUESTED** [review]
Minor changes requested. However it would be nice to see a test or two added that trigger the bug before the change, but fix it after. That way regressions like this won't happen in the future.

**Comment by klueska** [comment]
This is a regression due to the refactoring of the CPUManager that happened as part of https://github.com/kubernetes/kubernetes/pull/87759/commits

As part of that refactoring, the CPUManager moved to a model where CPUs are now allocated across all containers at pod admission time. Since all CPUs are allocated at pod admission time, they can only properly be freed back to the shared pool at pod deletion time (or lazily after the pod is already gone).

In the old model, CPUs were allocated to each container as it came online (as part of a container pre-start-hook) so we were free to (and in fact required to) free them as each container exited (as part of a post-stop-hook). This is problematic in the new model, however, since CPUs are assumed to retain their assignment to a container for the lifetime of a pod (most importantly across container restarts that do not cause the pod to be recreated).

This patch updates the CPUManager to make sure that CPUs are only ever freed back to the shared pool a pod has been deleted. It does this by lazily calling the existing `removeStaleState()` function at appropriate times instead of directly calling `RemoveContainer()` at container exit. The `removeStaleState()` function itself walks through the CPUManager state and frees any CPUs not bound to actively running pods.

We now make this call at three locations in the code:
    (1) At the top of the `GetTopologyHints()` call, just before a new pod runs it's logic to generate hints for the TopologyManager. This ensures it will have access to any "newly" available CPUs from terminated pods when generating these hints.
    (2) At the top of the Allocate call, just before a new pod runs it's logic to allocate CPUs. This ensures it will have access to any "newly" available CPUs from terminated pods when performing new allocations.
    (3) Periodically, as part of the existing `reconcileState()` function. This guarantees that CPUs will be freed from terminated pods at least once per reconcile period (currently 10 seconds) in the case that no new pods enter the system and trigger the `removeStaleState()` function as part of `Allocate()`.

In theory, we don't need 2 when the `TopologyManager` is enabled because (1) and (2) are in the same synchronous loop. However, not all setups enable the `TopologyManager`, so it is required in both places for now. 

In the future we should consider adding a hook for pod deletion instead of doing the lazy cleanup as part of (1) and (2). We will likely always do the lazy cleanup as part of (3) however, just to make sure we we are always in a sane state.

File: pkg/kubelet/cm/internal_container_lifecycle.go (hunk 1 above)
Comment (cbf123) [reply pkg/kubelet/cm/internal_container_lifecycle.go:59]: oops...editor was set to use spaces instead of tabs.

File: pkg/kubelet/cm/cpumanager/cpu_manager_test.go [hunk 3]
```diff
@@ -40,6 +40,12 @@ import (
 	"k8s.io/kubernetes/pkg/kubelet/cm/topologymanager"
 )
 
+type mockSourcesReady struct{}
+
+func (s *mockSourcesReady) AddSource(source string) {}
+
+func (s *mockSourcesReady) AllReady() bool          { return false }
+
```
Comment (klueska) [inline pkg/kubelet/cm/cpumanager/cpu_manager_test.go:48]: There already exists a `sourcesReadyStub` you can use here instead of this.

**Comment by klueska** [comment]
Also, you should add a release note of:
```
Fixes regression in CPUManager that caused freeing of exclusive CPUs at incorrect times 
```
Even though this is not a user-facing change, we plan to backport this to the 1.18 branch, and having a release note in the original PR eases this process.

**Comment by klueska** [comment]
Also, I am adding a release note of:
```release-note
Fixes regression in CPUManager that caused freeing of exclusive CPUs at incorrect times 
```
Even though this is not a user-facing change, we plan to backport this to the 1.18 branch, and having a release note in the original PR eases this process.

File: pkg/kubelet/cm/cpumanager/cpu_manager_test.go (hunk 3 above)
Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager_test.go:48]: Removing this should fix your `gofmt` error in the `pull-kubernetes-verify` test as well.

Comment (cbf123) [reply pkg/kubelet/cm/cpumanager/cpu_manager_test.go:48]: sourcesReadyStub.AllReady() returns "true", which causes the new call to removeStaleState() to try to actually do stuff, which causes all sorts of grief

**Comment by cbf123** [comment]
Sorry for the noise...I messed up while trying to squash some commits and it took a few tries to get the commit list down to where it's supposed to be.

File: pkg/kubelet/cm/cpumanager/cpu_manager_test.go (hunk 3 above)
Comment (klueska) [reply pkg/kubelet/cm/cpumanager/cpu_manager_test.go]: I see. I'd rather not artifically turn off valid code paths that might uncover other underlying problems that are lurking though. 

Below is a diff to your current patch that deals with the issue you are seeing in a way that's more consistent with the rest of the tests in this file:

```
diff --git a/pkg/kubelet/cm/cpumanager/cpu_manager_test.go b/pkg/kubelet/cm/cpumanager/cpu_manager_test.go
index 7a6724d76c2..bd18b2c95eb 100644
--- a/pkg/kubelet/cm/cpumanager/cpu_manager_test.go
+++ b/pkg/kubelet/cm/cpumanager/cpu_manager_test.go
@@ -40,12 +40,6 @@ import (
 	"k8s.io/kubernetes/pkg/kubelet/cm/topologymanager"
 )

-type mockSourcesReady struct{}
-
-func (s *mockSourcesReady) AddSource(source string) {}
-
-func (s *mockSourcesReady) AllReady() bool { return false }
-
 type mockState struct {
 	assignments   state.ContainerCPUAssignments
 	defaultCPUSet cpuset.CPUSet
@@ -275,14 +269,14 @@ func TestCPUManagerAdd(t *testing.T) {
 				err: testCase.updateErr,
 			},
 			containerMap:      containermap.NewContainerMap(),
-			activePods:        func() []*v1.Pod { return nil },
 			podStatusProvider: mockPodStatusProvider{},
+			sourcesReady:      &sourcesReadyStub{},
 		}

-		mgr.sourcesReady = &mockSourcesReady{}
-
 		pod := makePod("fakePod", "fakeContainer", "2", "2")
 		container := &pod.Spec.Containers[0]
+		mgr.activePods = func() []*v1.Pod { return []*v1.Pod{pod} }
+
 		err := mgr.Allocate(pod, container)
 		if !reflect.DeepEqual(err, testCase.expAllocateErr) {
 			t.Errorf("CPU Manager Allocate() error (%v). expected error: %v but got: %v",
@@ -495,12 +489,13 @@ func TestCPUManagerAddWithInitContainers(t *testing.T) {
 			state:             state,
 			containerRuntime:  mockRuntimeService{},
 			containerMap:      containermap.NewContainerMap(),
-			activePods:        func() []*v1.Pod { return nil },
 			podStatusProvider: mockPodStatusProvider{},
+			sourcesReady:      &sourcesReadyStub{},
+			activePods: func() []*v1.Pod {
+				return []*v1.Pod{testCase.pod}
+			},
 		}

-		mgr.sourcesReady = &mockSourcesReady{}
-
 		containers := append(
 			testCase.pod.Spec.InitContainers,
 			testCase.pod.Spec.Containers...)
@@ -1031,14 +1026,14 @@ func TestCPUManagerAddWithResvList(t *testing.T) {
 				err: testCase.updateErr,
 			},
 			containerMap:      containermap.NewContainerMap(),
-			activePods:        func() []*v1.Pod { return nil },
 			podStatusProvider: mockPodStatusProvider{},
+			sourcesReady:      &sourcesReadyStub{},
 		}

-		mgr.sourcesReady = &mockSourcesReady{}
-
 		pod := makePod("fakePod", "fakeContainer", "2", "2")
 		container := &pod.Spec.Containers[0]
+		mgr.activePods = func() []*v1.Pod { return []*v1.Pod{pod} }
+
 		err := mgr.Allocate(pod, container)
 		if !reflect.DeepEqual(err, testCase.expAllocateErr) {
 			t.Errorf("CPU Manager Allocate() error (%v). expected error: %v but got: %v",
```

**Comment by haosdent** [comment]
Work for our cluster. For for a long term solution, 
+1 for what @klueska said 'adding a hook for pod deletion instead of doing the lazy cleanup'

Would like to see this bug fix backport to 1.18 as well

**Comment by klueska** [comment]
Yes, that is the plan to backport it. I am just waiting for Chris to address my final feedback, then I’ll approve it.

File: pkg/kubelet/cm/cpumanager/cpu_manager.go [hunk 4]
```diff
@@ -384,18 +387,14 @@ func (m *manager) reconcileState() (success []reconciledContainer, failure []rec
...
+				// was allocated.
 				_, _, err := m.containerMap.GetContainerRef(containerID)
 				if err == nil {
-					klog.Warningf("[cpumanager] reconcileState: skipping container; already terminated (pod: %s, container id: %s)", pod.Name, containerID)
-					err := m.RemoveContainer(containerID)
-					if err != nil {
-						klog.Errorf("[cpumanager] reconcileState: failed to remove container (pod: %s, container id: %s, error: %v)", pod.Name, containerID, err)
-						failure = append(failure, reconciledContainer{pod.Name, container.Name, containerID})
-					}
+					klog.Warningf("[cpumanager] reconcileState: ignoring terminated (pod: %s, container id: %s)", pod.Name, containerID)
```
[the remark this answers is not in the document]
Comment (cbf123) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:397]: Done.

File: pkg/kubelet/cm/cpumanager/cpu_manager_test.go (hunk 3 above)
Comment (cbf123) [reply pkg/kubelet/cm/cpumanager/cpu_manager_test.go]: Thanks for the test changes, applied.

**Comment by cbf123** [comment]
I think all comments have been addressed.

**Comment by hex108** [comment]
Could we cherry pick it to release-1.17? Thanks! @klueska @cbf123
