### PR TITLE
Enforce --max-pods in kubelet admission; previously was only enforced in scheduler

### LINKED ISSUE #20263: Kubelet should enforce maxPods
Was there some reason #5547 only added the checking to the scheduler, not Kubelet?

@gmarek

### LINKED ISSUE #24262: Broken test: [k8s.io] SchedulerPredicates [Serial] validates MaxPods limit number of pods that are allowed to run [Slow]
This isn't a flake, the test is just broken. Starting from here:

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-serial/1064/

https://console.cloud.google.com/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/1064/

```
14:41:13 
14:41:13 • Failure [289.101 seconds]
14:41:13 [k8s.io] SchedulerPredicates [Serial]
14:41:13 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:420
14:41:13   validates MaxPods limit number of pods that are allowed to run [Slow] [It]
14:41:13   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:266
14:41:13 
14:41:13   Not scheduled Pods: []api.Pod(nil)
14:41:13   Expected
14:41:13       <int>: 0
14:41:13   to equal
14:41:13       <int>: 1
14:41:13 
14:41:13   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:107
```

I guess maybe something dies while it is scheduling everything?

### PR DESCRIPTION
**Pull request by gmarek**
This is an ugly hack - I spent some time trying to understand what one NodeInfo has in common with the other one, but at some point decided that I just don't have time to do that.

Fixes #24262
Fixes #20263

cc @HaiyangDING @lavalamp

### CODE REVIEW

File: plugin/pkg/scheduler/algorithm/predicates/predicates.go [hunk 1]
```diff
@@ -775,6 +775,14 @@ func RunGeneralPredicates(pod *api.Pod, nodeName string, nodeInfo *schedulercach
...
 		return fit, err
 	}
+	// TODO(HaiyangDING): Make a proper fix for it.
+	allocatable := node.Status.Allocatable
+	allowedPodNumber := allocatable.Pods().Value()
+	if int64(len(nodeInfo.Pods()))+1 > allowedPodNumber {
+		return false,
+			newInsufficientResourceError(podCountResourceName, 1, int64(len(nodeInfo.Pods())), allowedPodNumber)
+	}
+
```
Comment (wojtek-t) [inline plugin/pkg/scheduler/algorithm/predicates/predicates.go]: What we should do is to insted of calling podFitsResourcesInternal above, call just PodFitsResources and remove it from here.
Then we can even remove podFitsResourcesInternal completely since it will not be used.

**Comment by gmarek** [comment]
@k8s-bot unit test this issue: #24680

File: plugin/pkg/scheduler/algorithm/predicates/predicates.go (hunk 1 above)
Comment (gmarek) [inline plugin/pkg/scheduler/algorithm/predicates/predicates.go]: It's not that easy. PodFitsResources is a NodeStatus method, which needs predicates.NodeInfo. I can *probably* create one from the things I have here, but it'd be as ugly as this.

Comment (wojtek-t) [inline plugin/pkg/scheduler/algorithm/predicates/predicates.go]: aah - ok. let's leave as it - I will fix that in my PR where I'm changing it :)
With https://github.com/kubernetes/kubernetes/pull/24598 - it should be easy to do :)

**Comment by gmarek** [comment]
cc @yujuhong

**Comment by yujuhong** [comment]
@gmarek, I don't think the failed kubelet unit tests have the allocatable resources set, and I guess that could be the problem. You should set the numbers for them like [this test](https://github.com/kubernetes/kubernetes/blob/8537095415abc77d8d6936f51da61b7cacfcedde/pkg/kubelet/kubelet_test.go#L2543).

**Comment by gmarek** [comment]
Yup - that's what I did:) I added you, as I'm modifying Kubelet tests.

**Comment by gmarek** [comment]
(Travis just doesn't work today)

**Comment by yujuhong** [comment]
> Yup - that's what I did:) I added you, as I'm modifying Kubelet tests.

Cool. The tests look good. I think we'll deprecate these tests soon (since they are tested in the predicate library) and replace them with one generic admission test.

File: plugin/pkg/scheduler/algorithm/predicates/predicates.go [hunk 2]
```diff
@@ -775,6 +775,14 @@ func RunGeneralPredicates(pod *api.Pod, nodeName string, nodeInfo *schedulercach
 	if !fit {
 		return fit, err
 	}
+	// TODO(HaiyangDING): Make a proper fix for it.
```
Comment (davidopp) [inline plugin/pkg/scheduler/algorithm/predicates/predicates.go]: I think the comment here should instead be exactly the same comment as the other place where we check max pods, namely

// TODO: move the following podNumber check to podFitsResourcesInternal when Kubelet allows podNumber check (See #20263).

**Comment by davidopp** [comment]
Since the release notes are generated from the PR title, I would suggest re-titling this PR to something like "enforce --max-pods in kubelet admission; previously was only enforced in scheduler"

Also, noting here that this PR fixes #20263.

File: plugin/pkg/scheduler/algorithm/predicates/predicates.go (hunk 2 above)
Comment (gmarek) [inline plugin/pkg/scheduler/algorithm/predicates/predicates.go]: Done.

**Comment by davidopp** [comment]
LGTM

@yujuhong said change to have Kubelet enforce --max-pods is OK

**Comment by gmarek** [comment]
@k8s-bot unit test this issue: #24704
