### PR TITLE
DRA: fix Pods in a scheduling gang sharing ResourceClaims

### LINKED ISSUE #137617: DRA scheduler plugin cannot fulfill gang scheduling with shared ResourceClaims
### What happened?

When two Pods are created in a gang where both Pods share the same ResourceClaim, the scheduler falls into an endless loop trying to schedule the Pods and never succeeds.

```
Events:
  Type     Reason            Age                          From               Message
  ----     ------            ----                         ----               -------
  Warning  FailedScheduling  2m21s (x2292168 over 7m21s)  default-scheduler  0/2 nodes are available: resource claim default/single-gpu is in the process of being allocated. no new claims to deallocate, preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.
```

### What did you expect to happen?

Both Pods schedule with the shared ResourceClaim.

### How can we reproduce it (as minimally and precisely as possible)?

Create a kind cluster:
```
kind build node-image --image kindest/node:latest
kind create cluster --image kindest/node:latest --config kind.yaml
```
<details>
<summary>kind.yaml</summary>

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiVersion: kubeadm.k8s.io/v1beta3
    apiServer:
        extraArgs:
          runtime-config: "scheduling.k8s.io/v1alpha2=true"
featureGates:
  GenericWorkload: true
  GangScheduling: true
```

</details>

Install a DRA driver:
```
helm upgrade --install dra-example-driver oci://registry.k8s.io/dra-example-driver/charts/dra-example-driver -n dra-example-driver --create-namespace
```

Create a ResourceClaim, PodGroup, and Pods in the PodGroup sharing the claim:
<details>
<summary>workload.yaml</summary>

```yaml
apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
  name: single-gpu
spec:
  devices:
    requests:
    - name: gpu
      exactly:
        deviceClassName: gpu.example.com
---
apiVersion: scheduling.k8s.io/v1alpha2
kind: PodGroup
metadata:
  name: podgroup
spec:
  schedulingPolicy:
    gang:
      minCount: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      resourceClaims:
        - name: claim
          resourceClaimName: single-gpu
      containers:
        - name: ctr
          image: ubuntu:22.04
          command: ["bash", "-c"]
          args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
          resources:
            claims:
              - name: claim
      schedulingGroup:
        podGroupName: podgroup
```
</details>

### Anything else we need to know?

Both Pods will schedule together if either of the following changes are made:
- Set the PodGroup's `spec.schedulingPolicy` to `basic: {}`
- Create separate ResourceClaims for each Pod instead of sharing (ResourceClaimTemplate).

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.35.1
Kustomize Version: v5.7.1
Server Version: v1.36.0-alpha.2.435+0009958799e560
```

</details>

### Cloud provider

<details>
Local kind cluster
</details>

### OS version

Kind node:
<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux kind-control-plane 6.17.0-1008-azure #8~24.04.1-Ubuntu SMP Mon Jan 26 18:35:40 UTC 2026 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

```
% kind version
kind v0.31.0 go1.26.1 linux/amd64
```
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
DRA Example Driver v0.2.1
</details>

### PR DESCRIPTION
**Pull request by nojnhuh**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

When gang-scheduled Pods share ResourceClaims, subsequent Pods in the gang after the first are blocked by the DynamicResources plugin in PreFilter due to the claim's allocation still being pending. The claim is expected to be pending in PreFilter for gang scheduling, so the scheduler should reuse that pending allocation and narrow down the nodes that can accommodate those subsequent Pods according to the pending allocation like it does for completed allocations in the non-gang scheduling case.

#### Which issue(s) this PR is related to:

Fixes #137617

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug preventing Pods sharing ResourceClaims from being scheduled with GangScheduling.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 1]
```diff
@@ -989,10 +1129,15 @@ func (pl *DynamicResources) Reserve(ctx context.Context, cs fwk.CycleState, pod
 				claim.Finalizers = append(claim.Finalizers, resourceapi.Finalizer)
 			}
 			claim.Status.Allocation = allocation
+			if pl.isGangScheduled(pod) {
+				ref := resourceapi.ResourceClaimConsumerReference{Resource: "pods", Name: pod.Name, UID: pod.UID}
+				pl.pendingReservations.addRef(claim.UID, ref)
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Shouldn't we log reservation here as well?

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 2]
```diff
@@ -1237,13 +1428,31 @@ func (pl *DynamicResources) bindClaim(ctx context.Context, state *stateData, ind
...
-		// non-conflict error if this isn't possible.
-		claim.Status.ReservedFor = append(claim.Status.ReservedFor, resourceapi.ResourceClaimConsumerReference{Resource: "pods", Name: pod.Name, UID: pod.UID})
+		// Add the pod to ReservedFor if not already present. With gang
+		// scheduling, a previous binding cycle may have already persisted
+		// this entry before the pod group was retried.
+		if !resourceclaim.IsReservedForPod(pod, claim) {
+			if isGangAllocator {
+				// The allocator writes all gang siblings' reservedFor
+				// entries in a single UpdateStatus to avoid N-1
+				// ResourceVersion conflicts from parallel sibling writes.
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Shall we call the `UpdateStatus` below only when there is a change?

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 3]
```diff
@@ -1199,6 +1362,21 @@ func (pl *DynamicResources) bindClaim(ctx context.Context, state *stateData, ind
...
+	// broadcasts the result, then return the updated claim directly —
+	// zero additional API calls from siblings.
+	if pl.isGangScheduled(pod) && allocation == nil {
+		if pl.pendingReservations.hasRef(claim.UID, pod.UID) {
+			result, err := pl.pendingReservations.waitForAllocator(claim.UID)
+			if err != nil {
+				return nil, fmt.Errorf("allocator failed for claim %s: %w", klog.KObj(claim), err)
+			}
+			logger.V(5).Info("reservation completed by allocator batch write", "claim", klog.KObj(result), "pod", klog.KObj(pod))
+			return result, nil
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Can we stop here? There are more things like binding conditions or `patchPodExtendedResourceClaimStatus` that may need to be called. Shouldn't the binding continue instead?

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 4]
```diff
@@ -134,16 +140,118 @@ type nodeAllocation struct {
...
+// Siblings block on a sync.Cond until the allocator broadcasts after its
+// write completes, then read the stored result claim directly — zero
+// additional API calls.
+type pendingReservations struct {
+	mu    sync.Mutex
+	items map[types.UID]*claimReservation
+}
+
+type claimReservation struct {
+	refs []resourceapi.ResourceClaimConsumerReference
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: In the context of ResourceClaim in PodGroup feature, is the plan to keep only pods here or PodGroups as well?

If the later, then won't we have exactly the same problem as we don't know when we remove the last pod?

If the former, why do we need ResourceClaimConsumerReference if we need to store only pods?

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 5]
```diff
@@ -1199,6 +1362,21 @@ func (pl *DynamicResources) bindClaim(ctx context.Context, state *stateData, ind
 
 	logger.V(5).Info("preparing claim status update", "claim", klog.KObj(state.claims.get(index)), "allocation", klog.Format(allocation))
 
+	// Gang scheduling optimization: the allocator writes all reservedFor
+	// entries in one UpdateStatus. Siblings block here until the allocator
+	// broadcasts the result, then return the updated claim directly —
+	// zero additional API calls from siblings.
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: I'm not certain that this optimization is worth the code and review complication. Once we have PodGroup ResourceClaims, registration will use a single entry anyway.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 6]
```diff
@@ -1199,6 +1362,21 @@ func (pl *DynamicResources) bindClaim(ctx context.Context, state *stateData, ind
...
+	if pl.isGangScheduled(pod) && allocation == nil {
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Why do we require the allocation to be empty? To be able to stop the binding process early (see my comment below)? If we'd continued the binding process for all pods, we'd skip allocation anyway once `RetryOnConflict` detects the allocation is already done.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 7]
```diff
@@ -134,16 +140,118 @@ type nodeAllocation struct {
...
+	draManager          fwk.SharedDRAManager
+	pendingReservations *pendingReservations
+}
+
+// isGangScheduled returns true when gang scheduling is enabled and the pod
+// belongs to a scheduling group. All new gang-specific logic must be gated
+// behind this helper so that pods without a SchedulingGroup are never
+// affected.
+func (pl *DynamicResources) isGangScheduled(pod *v1.Pod) bool {
+	return pl.fts.EnableGangScheduling && pod.Spec.SchedulingGroup != nil
```
Comment (macsko) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: What about pods referencing pod group with basic policy? Shouldn't we treat them consistently here?

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 8]
```diff
@@ -432,6 +543,23 @@ func (pl *DynamicResources) PreFilter(ctx context.Context, state fwk.CycleState,
 	numClaimsToAllocate := 0
 	s.informationsForClaim = make([]informationForClaim, claims.len())
 	for index, claim := range claims.all() {
+		// Gang scheduling works by waiting for all Pods in a gang to succeed
+		// through the Reserve phase, then binding all of the Pods. Since a
+		// claim's allocation is not recorded in [stateData.claims] until
+		// PreBind, we look for a pending allocation made in Reserve here to
+		// avoid blocking this Pod on waiting for the allocation to complete.
```
Comment (macsko) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:456]: I think we would also like to optimize for the basic policy, which still uses the pod group scheduling cycle, but doesn't require min count to proceed to binding. Hence, shared claims can still work with basic, but it would come with a significant performance penalty if we don't support them in DRA in the same way as gangs

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 5 above)
Comment (macsko) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Agree with @dom4ha that it would be better to avoid unnecessary optimization for now, unless it's really needed

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 9]
```diff
@@ -134,16 +140,118 @@ type nodeAllocation struct {
...
-	draManager     fwk.SharedDRAManager
+	enabled             bool
+	fts                 feature.Features
+	filterTimeout       time.Duration
+	bindingTimeout      time.Duration
+	fh                  fwk.Handle
+	clientset           kubernetes.Interface
+	celCache            *cel.Cache
+	draManager          fwk.SharedDRAManager
+	pendingReservations *pendingReservations
```
Comment (macsko) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: The scheduler plugins themselves should be stateless. However, we allow them to reference external managers, such as the DRA manager. Do we have any idea how to preserve the statelessness of this plugin?

Comment (macsko) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: @dom4ha What if we add a possibility to access pod group's CycleState from the pod's CycleState? This way, we could store pending reservations in the pod group's CycleState

Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: The problem is that we need to mutate information about other pods in async extension points - Binding/Unreserve - so we need synchronization which pod group's CycleState does not provide.

Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: > The scheduler plugins themselves should be stateless.

I think it mainly applies to the scheduling phase, but less to binding. IIRC the pod group scheduling cannot be started again until binding of all pods is complete, is that correct?

Comment (macsko) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: > so we need synchronization which pod group's CycleState does not provide.

But the CycleState can be treated as a storage, with synchronization on a plugin level.

> IIRC the pod group scheduling cannot be started again until binding of all pods is complete, is that correct?

Currently it's not this way, because we don't have a proper pod group queueing implemented. Now, the next pods from a pod group can be scheduled after the previous pod group scheduling cycle finished, i.e., when pods were assumed/reserved and went to the binding cycle.

Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: > But the CycleState can be treated as a storage, with synchronization on a plugin level.

So as you pointed out, contrary to Pods, PodGroups will be re-scheduled before binding completes, so new CycleState would be created.

I think it's fine to keep that information in the ResourceManager as it does not influence scheduling. Also during scheduler restarts it's ok for this information to get lost. If the api call was already performed, it the information can be recovered from there.

The only downside is that locking may include the api call, but only for the last pod that is unregistered, so I think it's acceptable. BTW, currently Unregister includes API calls and it's often a part of scheduling cycle, so reducing that to a single pod per PodGroup is already a win.

Comment (macsko) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: > So as you pointed out, contrary to Pods, PodGroups will be re-scheduled before binding completes, so new CycleState would be created.

I don't think that's a problem. This would solve the PreFilter rejection issue because the pods would see the allocation within the single scheduling cycle. Any pods added later would either schedule correctly or wait for the allocation to persist.

I don't have a strong opinion about using CycleState. I just wanted to bring this idea up.

> currently Unregister includes API calls and it's often a part of scheduling cycle, so reducing that to a single pod per PodGroup is already a win.

The API call is only sent during cleanup after PreBind, so it's already async.

Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: > I don't think that's a problem. This would solve the PreFilter rejection issue because the pods would see the allocation within the single scheduling cycle.

I see what you mean. If we consider only addressing the PreFilter problem (plus write optimization), then yes, but my impression was that we are rather preparing to address the problem of Unregister from https://github.com/kubernetes/kubernetes/pull/136989

My recommendation for this PR is to focus on addressing the PreFilter issue, so the first commit is completely sufficient to achieve that. Any further enhancements (commits) should be dropped and Unregister problem could solved in the mentioned PodGroup ResourceClaim PR (if needed at all, but will comment there)

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 5 above)
Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: I proposed to leave only the first commit as it addresses the issue and drop the second one.

Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: I dropped the second commit here. I'm still not sure though if poking this hole could introduce any bugs with existing usage of DRA+gang scheduling that the existing check for pending claims guards against.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 7 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Added a check to only enable this new behavior for gang-scheduled Pods.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 10]
```diff
@@ -439,9 +449,22 @@ func (pl *DynamicResources) PreFilter(ctx context.Context, state fwk.CycleState,
...
-				nodeSelector, err := nodeaffinity.NewNodeSelector(claim.Status.Allocation.NodeSelector)
+		allocation := claim.Status.Allocation
+		// Gang scheduling works by waiting for all Pods in a gang to succeed
+		// through the Reserve phase, then binding all of the Pods. Since a
+		// claim's allocation is not recorded in [stateData.claims] until
+		// PreBind, we look for a pending allocation made in Reserve here to
+		// avoid blocking this Pod on waiting for the allocation to complete.
+		if isGangScheduling && allocation == nil {
+			if pendingAllocation, found := pl.draManager.ResourceClaims().GetPendingAllocation(claim.UID); found {
+				allocation = pendingAllocation
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:459]: @pohly is that safe to use pending allocation for the rest of the scheduling process?

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:459]: Safe in which sense? It's read-only and won't get mutated, so reading from it is safe. Don't write to it.

Eventually it moves from "pending" to "stored in claim = assume cache" (on success), without changes. More interesting is the failure case: it then gets removed from "pending" and the claim needs to be allocated anew.

File: test/integration/dra/pod_group.go [hunk 11]
```diff
@@ -0,0 +1,92 @@
...
+			},
+			Spec: schedulingapi.PodGroupSpec{
+				SchedulingPolicy: schedulingapi.PodGroupSchedulingPolicy{
+					Gang: &schedulingapi.GangSchedulingPolicy{
+						MinCount: int32(numPods),
+					},
+				},
+			},
+		},
+		"basic": {
```
Comment (macsko) [inline test/integration/dra/pod_group.go]: Since this test also checks for basic policy, could you consider renaming it to testPodGroup and the entire file to pod_group_test.go?

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 7 above)
Comment (macsko) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: But why? We can have similar problems, but with basic policy, where we would just waste scheduling cycles (https://github.com/kubernetes/kubernetes/pull/137647#discussion_r2930982069). Could you check the `GenericWorkload` feature instead and doesn't assume it's working only for the gang scheduling?

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 12]
```diff
@@ -428,6 +429,15 @@ func (pl *DynamicResources) PreFilter(ctx context.Context, state fwk.CycleState,
 		return nil, fwk.NewStatus(fwk.Skip)
 	}
 
+	isGangScheduling := false
+	if pl.fts.EnableGangScheduling {
+		podGroup, err := pl.getPodGroup(pod)
+		if err != nil {
+			return nil, statusUnschedulable(logger, "cannot check if Pod is being gang scheduled", "pod", klog.KObj(pod))
+		}
+		isGangScheduling = podGroup != nil && podGroup.Spec.SchedulingPolicy.Gang != nil
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: It should be enough to check if PodGroup is referred by a pod and GenericWorkload is enabled. That means that scheduler will attempt to schedule multiple pods in one scheduling cycle. I think it's sufficient condition to trigger the relaxed logic and it covers GangScheduling case as well.
 
See the condition that triggers it https://github.com/kubernetes/kubernetes/blob/3b28911985ce3e0d96066657f67f998751f18ccf/pkg/scheduler/backend/queue/scheduling_queue.go#L935-L936

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 7 above)
Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: @nojnhuh if you follow https://github.com/kubernetes/kubernetes/pull/137647#discussion_r2946975247 this comment will be addressed as well.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 10 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:459]: I'm wondering in particular if this race condition becomes possible:
https://github.com/kubernetes/kubernetes/blob/d9659b36bfbfb9a57acd850b1fa47326c53a75d8/pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go#L185-L190

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 7 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Ah I misunderstood. Updated.

File: test/integration/dra/pod_group.go (hunk 11 above)
Comment (nojnhuh) [reply test/integration/dra/pod_group.go]: Done.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 12 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Updated.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 10 above)
Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:459]: Right now, pods which share the same unallocated ResourceClaim do not get scheduled concurrently. That's the "this mechanism" in the comment above.

If you are trying to change that, then think hard about the possible scenarios outlined in that comment.

Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:459]: Shall we track the number of pods sharing the allocation in inFlightAllocations then?

If the allocation wasn't persisted, we won't release it in-memory unless all PodGroup pods get Unreserved. If the allocation managed to be persisted, scheduler should learn about it in update and clean it up on PostFilter.

Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:459]: So you want to allow several in-flight pods which share the same ResourceClaim?

This is basically the alternative in that comment, with a small twist:

https://github.com/kubernetes/kubernetes/blob/d9659b36bfbfb9a57acd850b1fa47326c53a75d8/pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go#L192-L201

I think the "It removes the updated claim from the assume cache because of that." is wrong there, it should say "from the in-flight claims". Counting pods for which the claim is in-flight might prevent this. The devil's in the details...

Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:459]: Yes, counting should prevent that, so any of the pods can manage to allocate the claim and register PodGroup in ReservedFor.

Note that we don't remove a PodGroup from ReservedFor in Unregister anymore as it's unreliable. We perform cleanup in PostFilter instead, making sure there are no assigned nor assumed pods in the PodGroup (pending pods which could perform allocation between cycles.

Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:459]: I pushed a change to count how many pods are scheduling for a claim. The count is incremented after `SignalClaimPendingAllocation` and in PreFilter when we discover the pending claim. The count is decremented before `RemoveClaimPendingAllocation` and is not removed from in-flight unless no other scheduling pods are sharing it.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 13]
```diff
@@ -165,7 +168,7 @@ type claimTracker struct {
 	// problem:
 	// - Pod A and B get scheduled as above.
 	// - PreBind for pod A gets called first, then fails with a temporary API error.
-	//   It removes the updated claim from the assume cache because of that.
+	//   It removes the updated claim from the in-flight claims because of that.
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:172]: Whole comment needs to be rewritten, because we effectively change this mechanism. In particular the following sentence is no longer ture:

> If another pod needs the claim, the pod is treated as "not schedulable yet".

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 14]
```diff
@@ -445,9 +445,24 @@ func (pl *DynamicResources) PreFilter(ctx context.Context, state fwk.CycleState,
...
-				nodeSelector, err := nodeaffinity.NewNodeSelector(claim.Status.Allocation.NodeSelector)
+		allocation := claim.Status.Allocation
+		// Gang scheduling works by waiting for all Pods in a gang to succeed
+		// through the Reserve phase, then binding all of the Pods. Since a
+		// claim's allocation is not recorded in [stateData.claims] until
+		// PreBind, we look for a pending allocation made in Reserve here to
+		// avoid blocking this Pod on waiting for the allocation to complete.
+		if pl.isSchedulingPodGroup(pod) && allocation == nil {
+			if pendingAllocation, found := pl.draManager.ResourceClaims().GetPendingAllocation(claim.UID); found {
+				if err := pl.draManager.ResourceClaims().AddSharedClaimPendingAllocation(claim.UID, claim); err != nil {
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Isn't it enough to increment it on Reserve? What we care about is to not let two different pods go to binding without being aware that at least one of them is still trying to allocate the claim.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 15]
```diff
@@ -1023,8 +1043,24 @@ func (pl *DynamicResources) Unreserve(ctx context.Context, cs fwk.CycleState, po
...
 	logger := klog.FromContext(ctx)
 
+	schedulingPodGroup := pl.fts.EnableGenericWorkload && pod.Spec.SchedulingGroup != nil
+
 	// we process user claims here first, extendedResourceClaim if any is handled below.
 	for _, claim := range state.claims.allUserClaims() {
+		// Since several Pods may be sharing a claim with a pending reservation,
+		// make sure that we don't remove the reservation until the last Pod
+		// sharing it is Unreserved.
+		if schedulingPodGroup {
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]:
```suggestion
		if isSchedulingPodGroup(pod) {
```

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 16]
```diff
@@ -1023,8 +1043,24 @@ func (pl *DynamicResources) Unreserve(ctx context.Context, cs fwk.CycleState, po
 
 	logger := klog.FromContext(ctx)
 
+	schedulingPodGroup := pl.fts.EnableGenericWorkload && pod.Spec.SchedulingGroup != nil
+
 	// we process user claims here first, extendedResourceClaim if any is handled below.
 	for _, claim := range state.claims.allUserClaims() {
+		// Since several Pods may be sharing a claim with a pending reservation,
+		// make sure that we don't remove the reservation until the last Pod
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]:
```suggestion
		// make sure that we don't remove the pending allocation until the last Pod
```

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 17]
```diff
@@ -1023,8 +1043,24 @@ func (pl *DynamicResources) Unreserve(ctx context.Context, cs fwk.CycleState, po
...
+		// sharing it is Unreserved.
+		if schedulingPodGroup {
+			if err := pl.draManager.ResourceClaims().RemoveSharedClaimPendingAllocation(claim.UID, claim); err != nil {
+				logger.Error(err, "unreserve", "resourceclaim", klog.KObj(claim))
+				continue
+			}
+			if pl.draManager.ResourceClaims().HasSharedClaimPendingAllocation(claim.UID) {
+				logger.V(5).Info("Claim is still shared by other scheduling pods, not removing reservation", "claim", klog.KObj(claim), "uid", claim.UID, "resourceVersion", claim.ResourceVersion)
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]:
```suggestion
				logger.V(5).Info("Claim is still shared by other scheduling pods, not removing pending allocation", "claim", klog.KObj(claim), "uid", claim.UID, "resourceVersion", claim.ResourceVersion)
```

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 18]
```diff
@@ -1023,8 +1043,24 @@ func (pl *DynamicResources) Unreserve(ctx context.Context, cs fwk.CycleState, po
...
+				continue
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: doesn't make sense to continue

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 19]
```diff
@@ -1223,6 +1259,20 @@ func (pl *DynamicResources) bindClaim(ctx context.Context, state *stateData, ind
...
+				// make sure that we don't remove the reservation until the last Pod
+				// sharing it is Unreserved.
+				if pl.isSchedulingPodGroup(pod) {
+					if err := pl.draManager.ResourceClaims().RemoveSharedClaimPendingAllocation(claim.UID, claim); err != nil {
+						logger.Error(err, "unreserve", "resourceclaim", klog.KObj(claim))
+						continue
+					}
+					if pl.draManager.ResourceClaims().HasSharedClaimPendingAllocation(claim.UID) {
+						logger.V(5).Info("Claim is still shared by other scheduling pods, not removing reservation", "claim", klog.KObj(claim), "uid", claim.UID, "resourceVersion", claim.ResourceVersion)
+						continue
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: same here

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 20]
```diff
@@ -1223,6 +1259,20 @@ func (pl *DynamicResources) bindClaim(ctx context.Context, state *stateData, ind
 		}
 		if allocation != nil {
 			for _, claimUID := range claimUIDs {
+				// Since several Pods may be sharing a claim with a pending reservation,
+				// make sure that we don't remove the reservation until the last Pod
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]:
```suggestion
				// make sure that we don't remove the pending allocation until the last Pod
```

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 21]
```diff
@@ -1223,6 +1259,20 @@ func (pl *DynamicResources) bindClaim(ctx context.Context, state *stateData, ind
...
+				// sharing it is Unreserved.
+				if pl.isSchedulingPodGroup(pod) {
+					if err := pl.draManager.ResourceClaims().RemoveSharedClaimPendingAllocation(claim.UID, claim); err != nil {
+						logger.Error(err, "unreserve", "resourceclaim", klog.KObj(claim))
+						continue
+					}
+					if pl.draManager.ResourceClaims().HasSharedClaimPendingAllocation(claim.UID) {
+						logger.V(5).Info("Claim is still shared by other scheduling pods, not removing reservation", "claim", klog.KObj(claim), "uid", claim.UID, "resourceVersion", claim.ResourceVersion)
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]:
```suggestion
						logger.V(5).Info("Claim is still shared by other scheduling pods, not removing pending allocation", "claim", klog.KObj(claim), "uid", claim.UID, "resourceVersion", claim.ResourceVersion)
```

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 22]
```diff
@@ -207,6 +217,48 @@ func (c *claimTracker) RemoveClaimPendingAllocation(claimUID types.UID) (deleted
 	return found
 }
 
+func (c *claimTracker) AddSharedClaimPendingAllocation(claimUID types.UID, allocatedClaim *resourceapi.ResourceClaim) error {
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:242]: Can you add basic tests for it?

**Review by dom4ha — COMMENTED** [review]
Overall it looks good now.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 18 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Don't we want to avoid calling `RemoveClaimPendingAllocation` in this case?

Comment (dom4ha) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Yeah, I noticed that and wanted to suggest to incorporate this check into `RemoveClaimPendingAllocation` (renamed to `MaybeRemoveClaimPendingAllocation`), but eventually haven't suggested.

However I think it's worth doing to get rid of this `continue`

Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Ah, makes sense. I'll do that.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 14 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Do you mean we should only call `AddSharedClaimPendingAllocation` in one place for all allocated claims, like inside this branch? https://github.com/kubernetes/kubernetes/blob/3445f85dddd42ae811f29efcb3b4a90d1a255533/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go#L944

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 22 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:242]: Yep, added some tests.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 21 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Updated.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 20 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Updated.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 19 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Done.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 18 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Done.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 17 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Updated.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 16 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Updated.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 15 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Updated.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 14 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: I tried adding it there. Happy to move that if there's a better place.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 13 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:172]: Noted where the behavior is different for PodGroups here.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 23]
```diff
@@ -207,6 +239,48 @@ func (c *claimTracker) RemoveClaimPendingAllocation(claimUID types.UID) (deleted
...
+	newSharers := 1
+	value, loaded := c.inFlightAllocationSharers.LoadOrStore(claimUID, newSharers)
+	if loaded {
+		oldSharers := value.(int)
+		newSharers = oldSharers + 1
+		swapped := c.inFlightAllocationSharers.CompareAndSwap(claimUID, oldSharers, newSharers)
+		if !swapped {
+			// The value must have changed since we loaded
+			return fmt.Errorf("conflict adding in-flight allocation sharer for claim %s/%s, UID=%s", allocatedClaim.Namespace, allocatedClaim.Name, claimUID)
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:251]: It would be better to retry on conflict rather than fail, as it means that a pod will get back to the scheduling queue. It would be fine for pod-by-pod scheduling, but in case of PodGroup scheduling (for which this code is for), it means failing the whole PodGroup.

We don't have to fix it now, as in practice such a conflict can happen when binding of previous scheduling cycle failed. In sunny day scenario Reserve is called synchronously, so feel free to just file an issue.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 24]
```diff
@@ -207,6 +239,48 @@ func (c *claimTracker) RemoveClaimPendingAllocation(claimUID types.UID) (deleted
...
+	}
+	if !written {
+		// The value must have changed since we loaded
+		return fmt.Errorf("conflict removing in-flight allocation sharer for claim %s/%s, UID=%s", allocatedClaim.Namespace, allocatedClaim.Name, claimUID)
+	}
+	c.logger.V(5).Info("Removed share for in-flight claim", "claim", klog.KObj(allocatedClaim), "uid", claimUID, "version", allocatedClaim.ResourceVersion, "sharers", newSharers)
+	return nil
+}
+
+func (c *claimTracker) HasSharedClaimPendingAllocation(claimUID types.UID) bool {
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Should be unused now.

**Review by dom4ha — COMMENTED** [review]
The changes looks good, still need to review tests.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 25]
```diff
@@ -1223,7 +1261,17 @@ func (pl *DynamicResources) bindClaim(ctx context.Context, state *stateData, ind
 		}
 		if allocation != nil {
 			for _, claimUID := range claimUIDs {
-				if deleted := pl.draManager.ResourceClaims().RemoveClaimPendingAllocation(claimUID); deleted {
+				// Since several Pods may be sharing a claim with a pending
+				// allocation, make sure that we don't remove the pending
+				// allocation until the last Pod sharing it is Unreserved.
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]:
```suggestion
				// allocation until the last Pod sharing it is Bound or Unreserved.
```

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 26]
```diff
@@ -1025,9 +1051,21 @@ func (pl *DynamicResources) Unreserve(ctx context.Context, cs fwk.CycleState, po
 
 	// we process user claims here first, extendedResourceClaim if any is handled below.
 	for _, claim := range state.claims.allUserClaims() {
-		// If allocation was in-flight, then it's not anymore and we need to revert the
-		// claim object in the assume cache to what it was before.
-		if deleted := pl.draManager.ResourceClaims().RemoveClaimPendingAllocation(claim.UID); deleted {
+		// Since several Pods may be sharing a claim with a pending allocation,
+		// make sure that we don't remove the pending allocation until the last
+		// Pod sharing it is Unreserved.
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]:
```suggestion
		// Pod sharing it is Bound or Unreserved.
```

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 27]
```diff
@@ -932,6 +945,19 @@ func (pl *DynamicResources) Reserve(ctx context.Context, cs fwk.CycleState, pod
 			// updating the ResourceClaim status, we assume that reserving
 			// will work and only do it for real during binding. If it fails at
 			// that time, some other pod was faster and we have to try again.
+
+			if pl.isSchedulingPodGroup(pod) && claim.UID != state.claims.getInitialExtendedResourceClaimUID() {
+				// Inform the tracker that this pod still needs the pending
+				// allocation. Then PreBind can know whether or not it's safe to
```
Comment (dom4ha) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]:
```suggestion
				// allocation. Then PreBind or Unreserve can know whether or not it's safe to
```

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 25 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Updated.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 27 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Updated.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 26 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go]: Updated.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 24 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go]: Yep, removed.

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go (hunk 23 above)
Comment (nojnhuh) [reply pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:251]: Opened https://github.com/kubernetes/kubernetes/issues/137855 to track this.

File: staging/src/k8s.io/kube-scheduler/framework/listers.go [hunk 28]
```diff
@@ -106,13 +106,23 @@ type ResourceClaimTracker interface {
...
 	SignalClaimPendingAllocation(claimUID types.UID, allocatedClaim *resourceapi.ResourceClaim) error
-	// ClaimHasPendingAllocation answers whether a given claim has a pending allocation during the binding phase. It can be used to avoid
+	// GetPendingAllocation answers whether a given claim has a pending allocation during the binding phase. It can be used to avoid
 	// race conditions in subsequent scheduling phases.
-	ClaimHasPendingAllocation(claimUID types.UID) bool
-	// RemoveClaimPendingAllocation removes the pending allocation for the given ResourceClaim from the tracker if any was signaled via
-	// SignalClaimPendingAllocation(). Returns whether there was a pending allocation to remove. List() and the other accessors immediately
-	// stop reflecting the pending allocation in the results.
-	RemoveClaimPendingAllocation(claimUID types.UID) (deleted bool)
+	GetPendingAllocation(claimUID types.UID) (*resourceapi.AllocationResult, bool)
```
Comment (jackfrancis) [inline staging/src/k8s.io/kube-scheduler/framework/listers.go:111]: The removals of `ClaimHasPendingAllocation` and `RemoveClaimPendingAllocation` (and replacements w/ new, ~equivalent interface methods) can be easily cleaned up for CA 1.36. Both of these are implemented as "always return false" and are not ever actually actuated in the flow of CA code.

See relevant comments here:

- https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.35.0/cluster-autoscaler/simulator/dynamicresources/snapshot/snapshot_claim_tracker.go#L113-L114
- https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.35.0/cluster-autoscaler/simulator/dynamicresources/snapshot/snapshot_claim_tracker.go#L119-L120

I've filed this issue to do this pre-1.36 work:

- https://github.com/kubernetes/autoscaler/issues/9382

cc @towca @mtrqq

**Review by jackfrancis — APPROVED** [review]

File: test/integration/dra/pod_group.go [hunk 29]
```diff
@@ -0,0 +1,92 @@
...
+	schedulingapi "k8s.io/api/scheduling/v1alpha2"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	st "k8s.io/kubernetes/pkg/scheduler/testing"
+	"k8s.io/kubernetes/test/utils/ktesting"
+)
+
+func testPodGroup(tCtx ktesting.TContext) {
+	tCtx.Parallel()
+
+	numPods := 2
```
Comment (johnbelamaric) [inline test/integration/dra/pod_group.go]: Looks like we are only testing with exactly 2 pods and with minCount == 2. It may be helpful to have tests with more than 2 pods and with the number of pods > minCount to test for any logical errors.

Comment (nojnhuh) [reply test/integration/dra/pod_group.go]: Added a few more cases here.

**Review by johnbelamaric — COMMENTED** [review]
/approve
/lgtm

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 30]
```diff
@@ -961,6 +974,19 @@ func (pl *DynamicResources) Reserve(ctx context.Context, cs fwk.CycleState, pod
...
 			// that time, some other pod was faster and we have to try again.
+
+			if pl.isSchedulingPodGroup(pod) && claim.UID != state.claims.getInitialExtendedResourceClaimUID() {
+				// Inform the tracker that this pod still needs the pending
+				// allocation. Then PreBind or Unreserve can know whether or not
+				// it's safe to remove the pending allocation.
+				//
+				// Extended resources claims cannot be shared, so we never
+				// signal sharing for it.
+				if err := pl.draManager.ResourceClaims().AddSharedClaimPendingAllocation(claim.UID, claim); err != nil {
```
Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:985]: Is there a time-of-check to time-of-use race here?

- Pod A sets up the in-flight claim.
- Pod B notices the in-flight claim above, proceeds.
- Pod A fails to store the allocation result, removes the in-flight-claim.
- Pod B gets here and tries to do the `AddSharedClaimPendingAllocation`.

Depends on the definition and implementation of `AddSharedClaimPendingAllocation` - if it returns error, we are fine. Let's see...

Doesn't look like it does. I falls through to `return nil` when it cannot load the current value from the map.

File: staging/src/k8s.io/kube-scheduler/framework/listers.go [hunk 31]
```diff
@@ -106,13 +106,23 @@ type ResourceClaimTracker interface {
...
+	// SignalClaimPendingAllocation(). When a pending allocation is `shareable`, it removes the pending allocation only when
+	// no other pods are still using that pending allocation (per AddSharedClaimPendingAllocation and
+	// RemoveSharedClaimPendingAllocation). When a pending allocation is not shareable, it always removes the pending
+	// allocation as long as one exists. Returns whether there was a pending allocation and it was removed.
+	// List() and the other accessors immediately stop reflecting the pending allocation in the results.
+	MaybeRemoveClaimPendingAllocation(claimUID types.UID, shareable bool) (deleted bool)
+
+	// AddSharedClaimPendingAllocation increments the number of active sharers
+	// of the given ResourceClaim.
+	AddSharedClaimPendingAllocation(claimUID types.UID, allocatedClaim *resourceapi.ResourceClaim) error
```
Comment (pohly) [inline staging/src/k8s.io/kube-scheduler/framework/listers.go:122]: Isn't the UID also in `allocatedClaim`? Seems redundant.

What I am not seeing here is a statement that it "returns an error if the claim is not in flight".

File: pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go [hunk 32]
```diff
@@ -195,7 +213,21 @@ func (c *claimTracker) SignalClaimPendingAllocation(claimUID types.UID, allocate
...
+			if loggerV := c.logger.V(5); loggerV.Enabled() {
+				claim, found := c.inFlightAllocations.Load(claimUID)
+				if found {
+					claim := claim.(*resourceapi.ResourceClaim)
+					c.logger.V(5).Info("Claim is still shared by other pods, not removing in-flight claim", "claim", klog.KObj(claim), "uid", claimUID, "version", claim.ResourceVersion)
+				}
+			}
+			return false
+		}
+	}
```
Comment (pohly) [inline pkg/scheduler/framework/plugins/dynamicresources/dra_manager.go:229]: Another time-of-check to time-of-use race here?

- Pod A checks whether it can remove here, finds no other pod.
- Pod B increments the counter.
- Pod A proceeds to removing the claim.

**Review by pohly — COMMENTED** [review]
I'm not convinced that this is race-free. Sorry, didn't get to do a full review earlier.

The underlying problem is that the content of two different `SyncMaps` must be kept in sync without some shared lock. I don't think that can work.

The safe approach would be to introduce a single map which includes the counter and the in-flight-claim, then lock that entire map with a (read/write?) mutex while doing checks or modifications. Less performant, but probably doesn't matter.
