### PR TITLE
Fix error msg in kubectl config get-contexts

### LINKED ISSUE #29822: Kubectl config get-contexts missing new line in error message
When specifying an invalid output format, the error message and the table headers are printed on the same line, producing hard-to-read output:

```
➜  kubernetes git:(config-context-msg) ✗ ./kubectl config get-contexts -o yaml
--output yaml is not available in kubectl config get-contexts; reseting to default output formatCURRENT   NAME       CLUSTER    AUTHINFO   NAMESPACE
*         minikube   minikube   minikube
```

### PR DESCRIPTION
**Pull request by alexbrand**
Fixes #29822

### CODE REVIEW

File: pkg/kubectl/cmd/config/get_contexts.go [hunk 1]
```diff
@@ -69,7 +69,7 @@ func NewCmdConfigGetContexts(out io.Writer, configAccess clientcmd.ConfigAccess)
 				cmdutil.CheckErr(fmt.Errorf("output must be one of '' or 'name': %v", outputFormat))
 			}
 			if !supportedOutputTypes.Has(outputFormat) {
-				fmt.Fprintf(out, "--output %v is not available in kubectl config get-contexts; reseting to default output format", outputFormat)
+				fmt.Fprintf(out, "--output %v is not available in kubectl config get-contexts; reseting to default output format\n", outputFormat)
```
Comment (dims) [inline pkg/kubectl/cmd/config/get_contexts.go]: Can you please fix the typo "reseting" to "resetting" as well?

**Comment by alexbrand** [comment]
@dims Fixed typo. Good catch, thanks!

**Comment by janetkuo** [comment]
ok to test
