### PR TITLE
fix: concurrent map writes error in VolumeBinding plugin during Filter

### LINKED ISSUE #96772: concurrent map writes in VolumeBinding plugin during Filter
**What happened**:

`fatal error: concurrent map writes` during `Filter` phase from the `VolumeBinding` plugin when the `podVolumesByNode` is updated:

```
func (pl *VolumeBinding) Filter(ctx context.Context, cs *framework.CycleState, pod *v1.Pod, nodeInfo *framework.NodeInfo) *framework.Status {
        ...
	cs.Lock()
	state.podVolumesByNode[node.Name] = podVolumes
	cs.Unlock()
        ...
}
```

**What you expected to happen**:

Not crash.

**How to reproduce it (as minimally and precisely as possible)**:

I am suspecting that the issue is in the naive implementation of the `stateData`'s `Clone()` method:

```
func (d *stateData) Clone() framework.StateData {
	return d
}
```

Most likely the `CycleState` is cloned during filter phase, e.g. in the `addNominatedPods(...) ` called during `PodPassesFiltersOnNode(...)` in the `generic_scheduler.go`:

https://github.com/kubernetes/kubernetes/blob/809556517611e8bb78383a077d6f326c0fb355fa/pkg/scheduler/core/generic_scheduler.go#L388 

... and when `CycleState` is cloned during filtering, new mutex is created, but `stateData` is not cloned properly, this mean that potentially there are two or more different mutexes protecting the same `state.podVolumesByNode` map from writes.

**Anything else we need to know?**:
I think potential solution is to have mutex in the `stateData` or change the `stateData`'s `Clone()`.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.0
- Cloud provider or hardware configuration: not relevant
- OS (e.g: `cat /etc/os-release`): not relevant
- Kernel (e.g. `uname -a`): not relevant
- Install tools: not relevant
- Network plugin and version (if this is a network-related bug): not relevant
- Others: not relevant

/sig scheduling

### PR DESCRIPTION
**Pull request by lianghao208**
**What type of PR is this?**

/kind bug
/sig scheduling

**What this PR does / why we need it**:
this PR fix the issue #96772 mentioning concurrent map writes error in VolumeBinding plugin during Filter. The reason is framework.CycleState will be cloned e.g. when invoking addNominatedPods()

https://github.com/kubernetes/kubernetes/blob/809556517611e8bb78383a077d6f326c0fb355fa/pkg/scheduler/core/generic_scheduler.go#L388

when `CycleState` is cloned during filtering, new mutex is created, but `stateData` is not cloned, we should set a mutex lock in struct stateData to make sure using the same mutex when updating stateData.podVolumesByNode

**Which issue(s) this PR fixes**:

Fixes #96772

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Fixes a regression in 1.19 where concurrent map write can be encountered in the scheduler in the VolumeBinding plugin filter
```
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
no

### CODE REVIEW

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding.go [hunk 1]
```diff
@@ -53,6 +54,9 @@ type stateData struct {
 	// phase for each node
 	// it's initialized in the PreFilter phase
 	podVolumesByNode map[string]*scheduling.PodVolumes
+	// guards map podVolumesByNode in the Filter phase, as the method may be called
+	// in parallel
+	podVolumesByNodeMutex sync.Mutex
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/volumebinding/volume_binding.go:59]: We can make it simpy:

```suggestion
	sync.Mutex
```

And then call `stateData.lock()`.

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding.go [hunk 2]
```diff
@@ -53,6 +54,9 @@ type stateData struct {
 	// phase for each node
 	// it's initialized in the PreFilter phase
 	podVolumesByNode map[string]*scheduling.PodVolumes
+	// guards map podVolumesByNode in the Filter phase, as the method may be called
+	// in parallel
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/volumebinding/volume_binding.go:58]: We don't need to restrict the protection on `podVolumesByNode as technically it can protect any fields defined here, and also it can be prevent racing in Score().

Comment (lianghao208) [reply pkg/scheduler/framework/plugins/volumebinding/volume_binding.go:58]: Agree. How about remove this comment?

Comment (lianghao208) [reply pkg/scheduler/framework/plugins/volumebinding/volume_binding.go]: I have modified the comment

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding.go [hunk 3]
```diff
@@ -205,9 +208,9 @@ func (pl *VolumeBinding) Filter(ctx context.Context, cs *framework.CycleState, p
 		return status
 	}
 
-	cs.Lock()
+	state.Mutex.Lock()
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/volumebinding/volume_binding.go:211]:
```suggestion
	state.Lock()
```

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding.go [hunk 4]
```diff
@@ -205,9 +208,9 @@ func (pl *VolumeBinding) Filter(ctx context.Context, cs *framework.CycleState, p
...
 	state.podVolumesByNode[node.Name] = podVolumes
-	cs.Unlock()
+	state.Mutex.Unlock()
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/volumebinding/volume_binding.go:213]:
```suggestion
	state.Unlock()
```

File: pkg/scheduler/framework/plugins/volumebinding/volume_binding.go (hunk 3 above)
Comment (cofyc) [inline pkg/scheduler/framework/plugins/volumebinding/volume_binding.go]:
```suggestion
    // multiple goroutines call `Filter` on different nodes simultaneously and the `CycleState` may be duplicated, so we must use a local lock here
	state.Lock()
```

I would suggest adding the comment here explaining why we can't rely on `framework.CycleState`'s lock.

**Review by cofyc — COMMENTED** [review]
is it possible to add a test case for "concurrent map write" case?

**Comment by Huang-Wei** [comment]
> is it possible to add a test case for "concurrent map write" case?

@lianghao208 You can try to run related UT by providing `-race` to see if it's reproducible.

**Comment by Huang-Wei** [comment]
BTW: please update the problem analysis section later.

**Comment by lianghao208** [comment]
> 
> @lianghao208 You can try to run related UT by providing `-race` to see if it's reproducible.

@Huang-Wei I don`t think providing `-race` in UT volume_binding_test.go can reproduce it...

**Comment by lianghao208** [comment]
> is it possible to add a test case for "concurrent map write" case?

I think the reason `CycleState`  be duplicated is beacause `state.Clone()` is invoked during the preemption. I may need to add a UT case to simulate the preemption senario to see if it can be reproduce.

**Comment by Huang-Wei** [comment]
I re-think this issue a bit, adding a plugin-level mutex _may_ not be able to resolve this issue.

I will take another look tomorrow.

**Comment by lianghao208** [comment]
> I re-think this issue a bit, adding a plugin-level mutex _may_ not be able to resolve this issue.

@Huang-Wei
 I checked the related codes that updating the map podVolumesByNode, it only happened in Filter(). The concurrent Error happens because the `state.Clone()` is invoked during the preemption. `state` turns out to be deplicated but podVolumesByNode is still the original one, locking the old `state` can`t ganrentee the new `state` not being modified, WDYT?

**Comment by ahg-g** [comment]
This is a proper fix, the concurrent access happens because CycleState is cloned on `[addNominatedPods](https://github.com/kubernetes/kubernetes/blob/b2ecd1b3a3192fbbe2b9e348e095326f51dc43dd/pkg/scheduler/core/generic_scheduler.go#L388)`, and so different nodes may be operating on different CycleState concurrently (and so different locks), but the underlying plugin state is the same because we simply return [the reference on Clone](https://github.com/kubernetes/kubernetes/blob/b2ecd1b3a3192fbbe2b9e348e095326f51dc43dd/pkg/scheduler/framework/plugins/volumebinding/volume_binding.go#L59).

I would keep the patch simple and backport v.19

/hold
/lgtm
/approve

**Comment by ahg-g** [comment]
please fix the lint issue (indentation of the comment)

**Comment by lianghao208** [comment]
> please fix the lint issue 

@ahg-g  I just fix the lint issue, need to add /lgtm label again. What else do I need to do?

**Comment by Huang-Wei** [comment]
Given that VolumeBinding's clone() returns the pointer, so the embedded mutex can protect its data no matter Filter() is called on a nominated node or regular node. I think this PR is good to go. @cofyc WDYT, are you ok with the pure fix, or strongly prefer to add a test to produce the race?

**Comment by cofyc** [comment]
> Given that VolumeBinding's clone() returns the pointer, so the embedded mutex can protect its data no matter Filter() is called on a nominated node or regular node. I think this PR is good to go. @cofyc WDYT, are you ok with the pure fix, or strongly prefer to add a test to produce the race?

I'm ok with this pure fix. 

/approve

**Comment by Huang-Wei** [comment]
@ahg-g I guess it's too late to catch the 1.20 train. Let's wait for it to be merged in master(1.21)，and cherry pick to 1.20.1?

**Comment by lianghao208** [comment]
@Huang-Wei If this patch needs backport v.19 and v.20, do I need to submit PR to cherry pick?

**Comment by ahg-g** [comment]
sg, lets patch back to v1.9 and v1.20

**Comment by ahg-g** [comment]
actually we can set the milestone to get it merged since this is a critical bug

/milestone v1.20
/hold cancel

**Comment by ahg-g** [comment]
@lianghao208 once this is merged, please create a patch against the 1.19 branch, the follow command should automatically create one when this is merged:

`hack/cherry_pick_pull.sh upstream/release-1.19 96777`

**Comment by lianghao208** [comment]
> once this is merged, please create a patch against the 1.19 branch

@ahg-g  will do.

**Comment by Huang-Wei** [comment]
> @Huang-Wei If this patch needs backport v.19 and v.20, do I need to submit PR to cherry pick?

Yes, you can leverage `hack/cherry_pick_pull.sh` to achieve that.
