### PR TITLE
Fix endpoint reconciler failing to delete masterlease

### LINKED ISSUE #114049: Endpoints doesn't reconcile in some cases from instance that is shutting down
### What happened?

Hi,

At the time of shutdown process of an control-plane instance,   apiserver attemps to remove it's `master Lease-object` from etcd, and it may not find the lease-object in storage  if the leases already expire by the time APIServer attempts to delete it from storage [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/reconcilers/lease.go#L123) , in such cases it will error out [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/controller.go#L214) with following error depending on the k8s version it's on
```
controller.go:184] StorageError: key not found, Code: 1, Key: /registry/masterleases//172.18.100.37, 
```
because of this line [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/reconcilers/lease.go#L316) errors out to delete from storage 

And endpoint won't be reconciled during the shutdown process from behind the Kubernetes service backend. Due to this some clients may still attempt connecting to old instance for some period of time as kube-proxy won't update the endpoints until new controller reconciler loop from another instances kicks off and removes the old endpoint.

Example of  `connection refused` errors that clients experience on client applications because of the above issue 
 ```
no more retries error: unable to recognize \""/tmp/manifest.yaml\"": Get \""https://10.100.0.1:443/api?timeout=32s\"": dial tcp 10.100.0.1:443: connect: connection refused"",""object"":{""apiVersion"":""v1"",""count"":1,""eventTime"":null,""firstTimestamp"":""2022-11-09T22:25:21Z"",""involvedObject"":
```

### What did you expect to happen?

Given there can be potential cases where our shutdown can take longer or don't end gracefully, our shutdown process can be more resilient and tolerate errors from storage and continue with reconciling anyway IIUC,
so I propose a fix  [here]( https://github.com/kubernetes/kubernetes/blob/release-1.20/pkg/controlplane/reconcilers/lease.go#L299) , basically swallow/log this error when you have issues deleting a lease-object from storage and continue with reconciling to update endpoint object.

^^^ what this gives us is, incases when there was no expiry of `master-leaseobject` from `etcd`,  it will be a no-op and continue to work the way it is i.e remove it from storage successfully and then reconcile. But in cases of `master-lease object` from etcd  expires, it will fail to find the key in etcd like in this case but because of this potential fix(swallowing the error and logging it), it will continue to reconcile the endpoints and this code [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controlplane/reconcilers/lease.go#L204)  will have updated master endpoints from etcd anyway at the time of reconciliation and help keep endpoints behind K8s service up-to-date during the shutdown process and doesn't have to wait until next periodic reconciler/new instance controller reconciler loop kicks in.

If you like above proposed solution, I can submit a PR for this. Please let me know. Thank you.

### How can we reproduce it (as minimally and precisely as possible)?

1) Let clients continue to make new connections every sec to instance you are about to terminate
2)  Delay the shutdown process until `master-lease` object in etcd expires for a given instance
2) Let APIServer continue with shutdown down process so it fails with the error 
```
controller.go:184] StorageError: key not found, Code: 1, Key: /registry/masterleases//172.18.100.37, 
```
4) Check error in client logs saying ```connection refused``` because it was trying to connect to old instance (tcp dump may help here to help look at it clearly that it was making a  connection to IP/endpoint of old instance and failing because `connection refused` error at network layer.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>
1.20 and 1.23 I have seen this issue happening
```console
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-6d3986b", GitCommit:"d4be14f563712c4e1964fe8a4171ca353b6e7e1a", GitTreeState:"clean", BuildDate:"2022-07-20T22:07:15Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```
```
Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.12-eks-1558457", GitCommit:"5e45ab4a299ac2f7c64cbc46f285b535ee32bdb8", GitTreeState:"clean", BuildDate:"2022-10-06T21:29:14Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

But i think this may happen on any version as this part of the code hasn't been updated on master IIUC

</details>


### Cloud provider

<details>
AWS but can likely happen anywhere
</details>



### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by aojea**
Fixes: https://github.com/kubernetes/kubernetes/issues/114049

This is @wojtek-t 's + a regression test https://github.com/kubernetes/kubernetes/pull/114109

```release-note
Fix a regression with endpoint reconciler not being able to delete the apiserver lease on shutdown
```
This was introduced in https://github.com/kubernetes/kubernetes/pull/113686 so will need to be cherrypicked back to all releases that PR was cherrypicked.

/king bug
/kind regression
/sig api-machinery
/priority critical-urgent

/assign @wojtek-t  @liggitt @lavalamp @tallclair

### CODE REVIEW

**Comment by aojea** [comment]
```
stress ./reconcilers.test -test.run TestLease.*
5s: 132 runs so far, 0 failures
10s: 286 runs so far, 0 failures
15s: 441 runs so far, 0 failures
20s: 601 runs so far, 0 failures
25s: 755 runs so far, 0 failures
30s: 909 runs so far, 0 failures
35s: 1061 runs so far, 0 failures
```

**Comment by aojea** [comment]
https://github.com/kubernetes/kubernetes/pull/114109#issuecomment-1326634969
@kubernetes/release-managers

File: pkg/controlplane/reconcilers/lease_test.go [hunk 1]
```diff
@@ -22,63 +22,84 @@ https://github.com/openshift/origin/blob/bb340c5dd5ff72718be86fb194dedc0faed7f4c
...
 
 import (
+	"reflect"
+	"sort"
 	"testing"
+	"time"
 
+	"github.com/google/uuid"
 	corev1 "k8s.io/api/core/v1"
+	v1 "k8s.io/api/core/v1"
```
Comment (pacoxu) [inline pkg/controlplane/reconcilers/lease_test.go:32]:
```
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/api/core/v1"
```
dup

File: pkg/controlplane/reconcilers/lease_test.go [hunk 2]
```diff
@@ -22,63 +22,84 @@ https://github.com/openshift/origin/blob/bb340c5dd5ff72718be86fb194dedc0faed7f4c
...
+var _ Leases = &fakeLeases{}
 
-func (f *fakeLeases) SetKeys(keys []string) {
-	for _, ip := range keys {
-		f.keys[ip] = false
+func newFakeLeases(t *testing.T, s storage.Interface) *fakeLeases {
+	// TODO make NewLeases sanitize paths, though it is only used in one place
+	// pkg/controlplane/instance.go:268:       masterLeases, err := reconcilers.NewLeases(config, "/masterleases/", ttl)
+	// add a random prefix so we can reuse the etcd instance for subtests
+	base := "/" + uuid.New().String() + "/masterleases/"
```
Comment (wojtek-t) [inline pkg/controlplane/reconcilers/lease_test.go:70]: Smart - I was looking at the test for 3 minutes trying to understand why the tests are independent before I realized this line...

File: pkg/controlplane/reconcilers/lease_test.go [hunk 3]
```diff
@@ -22,63 +22,84 @@ https://github.com/openshift/origin/blob/bb340c5dd5ff72718be86fb194dedc0faed7f4c
...
-	return nil
-}
+var _ Leases = &fakeLeases{}
 
-func (f *fakeLeases) SetKeys(keys []string) {
-	for _, ip := range keys {
-		f.keys[ip] = false
+func newFakeLeases(t *testing.T, s storage.Interface) *fakeLeases {
+	// TODO make NewLeases sanitize paths, though it is only used in one place
+	// pkg/controlplane/instance.go:268:       masterLeases, err := reconcilers.NewLeases(config, "/masterleases/", ttl)
```
Comment (wojtek-t) [inline pkg/controlplane/reconcilers/lease_test.go:68]: I suggest removing this TODO - I don't think it will happen...

**Review by wojtek-t — COMMENTED** [review]
This is great - just some minor comments.
Please fix the verify test failures.

File: pkg/controlplane/reconcilers/lease_test.go (hunk 2 above)
Comment (aojea) [reply pkg/controlplane/reconcilers/lease_test.go:70]: this is how we do in the integration test :)

File: pkg/controlplane/reconcilers/lease_test.go (hunk 1 above)
Comment (aojea) [reply pkg/controlplane/reconcilers/lease_test.go:32]: yep

**Comment by wojtek-t** [comment]
Copying from @liggitt from the original PR

cc @kubernetes/release-managers  for visibility. We probably want to hold rc1 for this if we're not anticipating an rc2

/lgtm
/approve

**Comment by liggitt** [comment]
Thanks!

@pacoxu, will this get auto-picked to release-1.26?

For 1.22-1.25, hopefully this will cherry-pick cleanly

**Comment by dims** [comment]
@liggitt we are auto-ff-ing things from master to release-1.26 until we do the code thaw

**Comment by liggitt** [comment]
That's what I thought but I wanted to double check

File: pkg/controlplane/reconcilers/lease.go [hunk 4]
```diff
@@ -120,7 +120,8 @@ func (s *storageLeases) UpdateLease(ip string) error {
 
 // RemoveLease removes the lease on a master IP in storage
 func (s *storageLeases) RemoveLease(ip string) error {
-	return s.storage.Delete(apirequest.NewDefaultContext(), s.baseKey+"/"+ip, &corev1.Endpoints{}, nil, rest.ValidateAllObjectFunc, nil)
+	key := path.Join(s.baseKey, ip)
```
Comment (lavalamp) [inline pkg/controlplane/reconcilers/lease.go:123]: Can you avoid using path.Join for this? I know it's a pain but hiding the call to path.Clean is a problem. 

cc @tallclair

**Comment by lavalamp** [comment]
Thanks for fixing this!

File: pkg/controlplane/reconcilers/lease.go (hunk 4 above)
Comment (liggitt) [reply pkg/controlplane/reconcilers/lease.go:123]: at head, in a followup, sure. For backports, I don't think it's worth it. baseKey is hardcoded and IP is a stringified net.IP so it can't contain weird slash/space/backstep chars

Comment (lavalamp) [reply pkg/controlplane/reconcilers/lease.go:123]: Sounds good.
