### PR TITLE
Fix the job controller unit test for enforcing ActiveDeadlineSeconds

### LINKED ISSUE #110697: Flaky test TestSyncPastDeadlineJobFinished
### Which jobs are flaking?

pull-kubernetes-unit

### Which tests are flaking?

TestSyncPastDeadlineJobFinished

### Since when has it been flaking?

June 14th

### Testgrid link

https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=TestSyncPastDeadlineJobFinished&job=pull-kubernetes-unit

### Reason for failure (if possible)

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110638/pull-kubernetes-unit/1539289648939929600

```
=== FAIL: pkg/controller/job TestSyncPastDeadlineJobFinished/New_job_created_without_start_time_being_set (3.00s)
I0621 17:06:06.298308   54038 job_controller.go:190] Starting job controller
I0621 17:06:06.298379   54038 shared_informer.go:255] Waiting for caches to sync for job
I0621 17:06:06.298492   54038 shared_informer.go:262] Caches are synced for job
I0621 17:06:06.352546   54038 job_controller.go:504] enqueueing job default/job1
E0621 17:06:06.353048   54038 tracking_utils.go:109] "deleting tracking annotation UID expectations" err="couldn't create key for object default/job1: could not find key for obj \"default/job1\"" job="default/job1"
    job_controller_test.go:1892: Job failed to enforce activeDeadlineSeconds configuration. Expected condition with Reason 'DeadlineExceeded' was not found in {[] <nil> <nil> 0 0 0  nil <nil>}
    --- FAIL: TestSyncPastDeadlineJobFinished/New_job_created_without_start_time_being_set (3.00s)
```

### Anything else we need to know?

Probably after #110294

### Relevant SIG(s)

/sig apps

### PR DESCRIPTION
**Pull request by mimowo**
/sig apps

#### What type of PR is this?

/kind bug
/kind flake

#### What this PR does / why we need it:

The scenario leading to failures:
- the last `syncJob` invocation checks the condition for ActiveDeadlineSeconds and as `startTime`=`now`, the condition is not violated
- the test moves the clock by 1s
- the job controller enqueues another `syncJob` in one second, but the clock is never moved again
- as there is no another `syncJob`, there the condition is not checked again, and thus the condition is not added - the test fails

This commit ensures that the last enqueued sync is executed, thus triggering addition of the condition.

#### Which issue(s) this PR fixes:

Fixes #110697

#### Special notes for your reviewer:

- This is a follow up fix after https://github.com/kubernetes/kubernetes/pull/114876. Here is a post documenting that it remains an issue: https://github.com/kubernetes/kubernetes/pull/114876#issuecomment-1376859472. 
- It was tested with 1000 executions.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sathyanarays** [comment]
- the last syncJob invocation checks the condition for ActiveDeadlineSeconds and as startTime=now, the condition is not violated
- the test moves the clock by 1s
- the job controller enqueues another syncJob in one second, but the clock is never moved again

@mimowo , in the third event, `fakeClock.Now()` - `startTime` should be equal to 1. Why is the "DeadlineExceeded" condition not set?

**Comment by mimowo** [comment]
> 



> * the last syncJob invocation checks the condition for ActiveDeadlineSeconds and as startTime=now, the condition is not violated
> * the test moves the clock by 1s
> * the job controller enqueues another syncJob in one second, but the clock is never moved again
> 
> @mimowo , in the third event, `fakeClock.Now()` - `startTime` should be equal to 1. Why is the "DeadlineExceeded" condition not set?

The  `fakeClock.Now()` - `startTime`  condition is checked at first bullet point (before the clock is moved), here in code:
https://github.com/kubernetes/kubernetes/blob/3742d14998fc41dd8c086e8d44cf6b50023c831e/pkg/controller/job/job_controller.go#L784.
Then, the syncDuration is computed to 1s: https://github.com/kubernetes/kubernetes/blob/3742d14998fc41dd8c086e8d44cf6b50023c831e/pkg/controller/job/job_controller.go#L787.
Then, the clock is moved (in test code) and the `syncJob` is requeued, here: https://github.com/kubernetes/kubernetes/blob/3742d14998fc41dd8c086e8d44cf6b50023c831e/pkg/controller/job/job_controller.go#L789.
However, the clock is never moved again to trigger the function.

**Comment by sathyanarays** [comment]
It failed again in my machine. The details are as follows:

commit 78f2b1de33590990c7225126c68b345a9c2909c7

**Diff**
```
diff --git a/pkg/controller/job/job_controller_test.go b/pkg/controller/job/job_controller_test.go
index a341f3ff1db..87e9b54c31c 100644
--- a/pkg/controller/job/job_controller_test.go
+++ b/pkg/controller/job/job_controller_test.go
@@ -1916,6 +1916,7 @@ func TestPastDeadlineJobFinished(t *testing.T) {
                                if len(j.Status.Conditions) == 1 && j.Status.Conditions[0].Reason == "DeadlineExceeded" {
                                        return true, nil
                                }
+                               manager.clock.Sleep(200 * time.Millisecond)
                                return false, nil
                        })
                        if err != nil {
```
**Failure logs**
```
I0110 15:35:07.307710 2044955 job_controller.go:199] Starting job controller
I0110 15:35:07.307815 2044955 shared_informer.go:314] Waiting for caches to sync for job
I0110 15:35:07.307823 2044955 shared_informer.go:321] Caches are synced for job
I0110 15:35:07.308145 2044955 job_controller.go:516] enqueueing job default/job1
I0110 15:35:07.308552 2044955 job_controller.go:516] enqueueing job default/job1
I0110 15:35:07.308630 2044955 job_controller.go:516] enqueueing job default/job1
I0110 15:35:10.310488 2044955 job_controller.go:516] enqueueing job default/job2
I0110 15:35:10.310684 2044955 job_controller.go:516] enqueueing job default/job2
I0110 15:35:10.310704 2044955 job_controller.go:516] enqueueing job default/job2
I0110 15:35:10.310863 2044955 event.go:294] "Event occurred" object="default/job2" fieldPath="" kind="Job" apiVersion="" type="Warning" reason="DeadlineExceeded" message="Job was active longer than specified deadline"
E0110 15:35:10.310897 2044955 job_controller.go:551] syncing job: failed pod(s) detected for job key "default/job2"
I0110 15:35:10.310905 2044955 job_controller.go:516] enqueueing job default/job2
I0110 15:35:10.310910 2044955 job_controller.go:516] enqueueing job default/job2
I0110 15:35:10.310920 2044955 event.go:294] "Event occurred" object="default/job2" fieldPath="" kind="Job" apiVersion="" type="Warning" reason="DeadlineExceeded" message="Job was active longer than specified deadline"
--- FAIL: TestPastDeadlineJobFinished (3.30s)
    --- FAIL: TestPastDeadlineJobFinished/New_job_created_without_start_time_being_set (3.00s)
        job_controller_test.go:1923: Job failed to enforce activeDeadlineSeconds configuration. Expected condition with Reason 'DeadlineExceeded' was not found in {[] 2023-01-10 15:35:07 +0530 IST <nil> 0 0 0  &UncountedTerminatedPods{Succeeded:[],Failed:[],} 0xc0005ee72c}
FAIL
FAIL	k8s.io/kubernetes/pkg/controller/job	3.328s
FAIL
```

**Comment by mimowo** [comment]
> It failed again in my machine.

Can you try increasing the timeout to 5s and give some stats, how many fail out of 1000?

**Comment by sathyanarays** [comment]
> > It failed again in my machine.
> 
> @sathyanarays Can you try increasing the timeout to 5s and give some stats, how many fail out of 1000?

I stop at the first failure. I tried two iterations which failed at 26 and 39. Let me re-run for 5s timeout!

**Comment by sathyanarays** [comment]
I noticed in the failed instances, the status did not get updated even after completing reconcile loop. In such instances, I noticed that the expectations are not satisfied and the status update is skipped. I don't have much idea about how expectations work. But, I think they depend on real clock.

I faked the expectations for the controller and the tests seem to pass. The diff is as follows:

```
@@ -1838,6 +1838,10 @@ func TestPastDeadlineJobFinished(t *testing.T) {
        manager, sharedInformerFactory := newControllerFromClientWithClock(clientset, controller.NoResyncPeriodFunc, fakeClock)
        manager.podStoreSynced = alwaysReady
        manager.jobStoreSynced = alwaysReady
+       manager.expectations = FakeJobExpectations{
+               controller.NewControllerExpectations(), true, func() {
+               },
+       }
        ctx, cancel := context.WithCancel(context.Background())
        defer cancel()
        sharedInformerFactory.Start(ctx.Done())
```
I am not sure if it is fair to mock the expectations. Please let me know your thoughts!

**Comment by mimowo** [comment]
> > Can you try increasing the timeout to 5s and give some stats?
> 
> Tried. Increasing timeout doesn't change the outcome! The test failed.

I see can you share what are the expectations that are not satisfied? I have difficulty reproducing this locally.

The PR solves at least one scenario for failures and I have difficulty reproducing the issue with expectations, so maybe it makes sense to fix it in another PR. What do you think @alculquicondor ?

**Comment by alculquicondor** [comment]
the expectations check was introduced recently by #114905 @kannon92 

It looks like sometimes the pods might not be in the cache before the syncs run? In production, each pod creation would trigger a sync, so we are safe. In the unit test, it's safe to just fake expectations instead of creating pods.

Back to the original problem:

It looks like the test is failing because we calculate the timeout at t=0, but when we insert the item in the workqueue, it's already t=1. Another thing that in production wouldn't matter much. Ideally, we would advance the clock only when we know the item is in the workqueue already. We can actually check this by polling the size of the workqueue.

**Comment by sathyanarays** [comment]
> > Can you try increasing the timeout to 5s and give some stats?
> 
> Tried. Increasing timeout doesn't change the outcome! The test failed.

With 5 seconds timeout, 5 out of 1000 failed!

File: pkg/controller/job/job_controller_test.go [hunk 1]
```diff
@@ -1916,6 +1916,7 @@ func TestPastDeadlineJobFinished(t *testing.T) {
 				if len(j.Status.Conditions) == 1 && j.Status.Conditions[0].Reason == "DeadlineExceeded" {
 					return true, nil
 				}
+				manager.clock.Sleep(200 * time.Millisecond)
```
Comment (kannon92) [inline pkg/controller/job/job_controller_test.go:1919]: > This commit ensures that the last enqueued sync is executed, thus triggering addition of the condition.

Why does a sleep ensure a sync?

Comment (alculquicondor) [reply pkg/controller/job/job_controller_test.go:1919]: It doesn't, at least not immediately. We are essentially waiting for another full second, because that's how long we told the workqueue to wait for this job.

Comment (mimowo) [reply pkg/controller/job/job_controller_test.go]: Yes, I updated the PR to shift the clock by 1s in that case to trigger the syncJob almost immediately.

 I also investigated how to do this conditionally (by checking the manager's queue by `jm.queue.Len()` but it gives me 0 even after calling `AddAfter` so for now, I'm not sure how to add the 1s conditionally. Any idea @alculquicondor ?

File: pkg/controller/job/job_controller_test.go [hunk 2]
```diff
@@ -1838,6 +1838,10 @@ func TestPastDeadlineJobFinished(t *testing.T) {
 	manager, sharedInformerFactory := newControllerFromClientWithClock(clientset, controller.NoResyncPeriodFunc, fakeClock)
 	manager.podStoreSynced = alwaysReady
 	manager.jobStoreSynced = alwaysReady
+	manager.expectations = FakeJobExpectations{
+		controller.NewControllerExpectations(), true, func() {
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller_test.go:1842]: with this added, we don't need `setPodsStatuses` anymore. Please remove.

File: pkg/controller/job/job_controller_test.go [hunk 3]
```diff
@@ -1916,6 +1920,7 @@ func TestPastDeadlineJobFinished(t *testing.T) {
 				if len(j.Status.Conditions) == 1 && j.Status.Conditions[0].Reason == "DeadlineExceeded" {
 					return true, nil
 				}
+				manager.clock.Sleep(time.Second)
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller_test.go:1923]: is there a way to access the prequeue? https://github.com/kubernetes/kubernetes/issues/110697#issuecomment-1378760495

Comment (mimowo) [reply pkg/controller/job/job_controller_test.go:1923]: Does not seem to be exported, maybe by reflection.

Comment (alculquicondor) [reply pkg/controller/job/job_controller_test.go:1923]: Another idea: add `AddAt`, in addition to `AddAfter` to the `DelayingInterface`.

It's weird that we have to calculate the remaining time just to add it back to the current time here again:

https://github.com/kubernetes/client-go/blob/674e53a7cb8f1ea160ac4485ffc7582e1a790215/util/workqueue/delaying_queue.go#L179

Comment (mimowo) [reply pkg/controller/job/job_controller_test.go:1923]: AddAt sounds like a nice function, but would it help to fix the test, I guess it calls for another pr.

Comment (alculquicondor) [reply pkg/controller/job/job_controller_test.go:1923]: yes, it would, because we precisely set the time, instead of it being based on the current time in the clock in the workqueue.

Comment (alculquicondor) [reply pkg/controller/job/job_controller_test.go:1923]: I want to change the job_controller to call `AddAt`.

> I think the issue is that AddAfter can be called before or after we move the time in job_controller_test.

Exactly. The test fails when `AddAfter` is called after we move the time. This could still happen with `AddAt`, but since the time already passed, `AddAt` would just put it in the queue directly.

File: pkg/controller/job/job_controller_test.go (hunk 2 above)
Comment (mimowo) [reply pkg/controller/job/job_controller_test.go:1842]: Done

File: pkg/controller/job/job_controller_test.go (hunk 3 above)
Comment (mimowo) [reply pkg/controller/job/job_controller_test.go]: I see now, just pushed that change. PTAL.

Comment (mimowo) [reply pkg/controller/job/job_controller_test.go]: Ah, there are still flakes after this change, don't understand it yet, here is the example log with debugs:

```
3987463-=== RUN   TestPastDeadlineJobFinished/New_job_created_without_start_time_being_set
3987546-I0112 14:49:36.776560  772603 job_controller.go:199] Starting job controller
3987623-I0112 14:49:36.776578  772603 shared_informer.go:314] Waiting for caches to sync for job
3987712-I0112 14:49:36.776599  772603 shared_informer.go:321] Caches are synced for job
3987792-I0112 14:49:36.776677  772603 job_controller.go:516] enqueueing job default/job1
3987873-I0112 14:49:36.776753  772603 job_controller.go:678] "MYDEBUG syncJob starts" startTime="2023-01-12 14:49:36 +0100 CET"
3987993-I0112 14:49:36.776810  772603 job_controller.go:794] "MYDEBUG" past=false timeoutAt="2023-01-12 14:49:37 +0100 CET"
3988109-I0112 14:49:36.776980  772603 job_controller.go:542] "MYDEBUG before done" queue.Len()=0
3988198-I0112 14:49:36.776997  772603 job_controller.go:544] "MYDEBUG after done" queue.Len()=0
3988286-I0112 14:49:36.777010  772603 job_controller.go:516] enqueueing job default/job1
3988367-I0112 14:49:36.777017  772603 job_controller.go:678] "MYDEBUG syncJob starts" startTime="2023-01-12 14:49:36 +0100 CET"
3988487-I0112 14:49:36.777033  772603 job_controller.go:794] "MYDEBUG" past=false timeoutAt="2023-01-12 14:49:37 +0100 CET"
3988603-    job_controller_test.go:1910: Time before sleep: 2023-01-12 14:49:36 +0100 CET, 0
3988688-    job_controller_test.go:1912: Time after sleep: 2023-01-12 14:49:37 +0100 CET, 0
3988949-    job_controller_test.go:1925: Job failed to enforce activeDeadlineSeconds configuration. Expected condition with Reason 'DeadlineExceeded' was not found in {[] 2023-01-12 14:49:36 +0100 CET <nil> 1 0 0  &UncountedTerminatedPods{Succeeded:[],Failed:[],} 0xc000ace9ac}
3989219:--- FAIL: TestPastDeadlineJobFinished (3.10s)

```

Also tested, that after this change there are no flakes again if I move the clock by 1s.

I suspect that even if we add to the queue, but there is no time passage then the item is never picked up, but don't really understand it yet, so might be wrong.

Comment (mimowo) [reply pkg/controller/job/job_controller_test.go]: This is an example run with added sleep(200*time.Milliseconds), that would fail if not for the sleep. 

```
1579771-I0112 15:23:07.384932  784463 job_controller.go:213] Shutting down job controller
1579853-=== RUN   TestPastDeadlineJobFinished/New_job_created_without_start_time_being_set
1579936-I0112 15:23:07.485768  784463 job_controller.go:199] Starting job controller
1580013-I0112 15:23:07.485809  784463 shared_informer.go:314] Waiting for caches to sync for job
1580102-I0112 15:23:07.485824  784463 shared_informer.go:321] Caches are synced for job
1580182-I0112 15:23:07.485886  784463 job_controller.go:516] enqueueing job default/job1
1580263-I0112 15:23:07.485950  784463 job_controller.go:678] "MYDEBUG syncJob starts" startTime="2023-01-12 15:23:07 +0100 CET"
1580383-I0112 15:23:07.486003  784463 job_controller.go:794] "MYDEBUG" past=false timeoutAt="2023-01-12 15:23:08 +0100 CET"
1580499-I0112 15:23:07.486165  784463 job_controller.go:542] "MYDEBUG before done" queue.Len()=0
1580588-I0112 15:23:07.486183  784463 job_controller.go:544] "MYDEBUG after done" queue.Len()=0
1580676-I0112 15:23:07.486198  784463 job_controller.go:516] enqueueing job default/job1
1580757-I0112 15:23:07.486209  784463 job_controller.go:678] "MYDEBUG syncJob starts" startTime="2023-01-12 15:23:07 +0100 CET"
1580877-I0112 15:23:07.486228  784463 job_controller.go:794] "MYDEBUG" past=false timeoutAt="2023-01-12 15:23:08 +0100 CET"
1580993-    job_controller_test.go:1910: MYDEBUG Time before sleep: 2023-01-12 15:23:07 +0100 CET, 0
1581086-    job_controller_test.go:1912: MYDEBUG Time after sleep: 2023-01-12 15:23:08 +0100 CET, 0
1581178-I0112 15:23:07.486416  784463 job_controller.go:542] "MYDEBUG before done" queue.Len()=0
1581267-I0112 15:23:07.486445  784463 job_controller.go:544] "MYDEBUG after done" queue.Len()=0
1581355:    job_controller_test.go:1921: MYDEBUG Looping: 2023-01-12 15:23:08 +0100 CET, 0
1581438:    job_controller_test.go:1921: MYDEBUG Looping: 2023-01-12 15:23:08.2 +0100 CET, 0
1581523:    job_controller_test.go:1921: MYDEBUG Looping: 2023-01-12 15:23:08.4 +0100 CET, 0
1581608:    job_controller_test.go:1921: MYDEBUG Looping: 2023-01-12 15:23:08.6 +0100 CET, 0
1581693:    job_controller_test.go:1921: MYDEBUG Looping: 2023-01-12 15:23:08.8 +0100 CET, 0
1581778-I0112 15:23:08.487010  784463 job_controller.go:678] "MYDEBUG syncJob starts" startTime="2023-01-12 15:23:09 +0100 CET"
1581898-I0112 15:23:08.487069  784463 job_controller.go:796] "MYDEBUG" past=true timeoutAt="nil"
1581987-I0112 15:23:08.487170  784463 job_controller.go:542] "MYDEBUG before done" queue.Len()=0
1582076-I0112 15:23:08.487178  784463 job_controller.go:544] "MYDEBUG after done" queue.Len()=0
1582164-I0112 15:23:08.487258  784463 event.go:294] "Event occurred" object="default/job1" fieldPath="" kind="Job" apiVersion="" type="Warning" reason="DeadlineExceeded" message="Job was active longer than specified deadline"
1582382-I0112 15:23:08.487266  784463 job_controller.go:516] enqueueing job default/job1
1582463-I0112 15:23:08.487297  784463 job_controller.go:516] enqueueing job default/job1
1582544-I0112 15:23:08.487323  784463 job_controller.go:678] "MYDEBUG syncJob starts" startTime="2023-01-12 15:23:09 +0100 CET"
1582664-I0112 15:23:08.487373  784463 job_controller.go:542] "MYDEBUG before done" queue.Len()=0
1582753-I0112 15:23:08.487386  784463 job_controller.go:544] "MYDEBUG after done" queue.Len()=0
```
So it is clearly AddAt invoked with `"2023-01-12 15:23:08 +0100 CET"`, but it is invoked for some reason only once the time passes to 2023-01-12 15:23:09 +0100 CET

Comment (alculquicondor) [reply pkg/controller/job/job_controller_test.go]: But if AddAt is invoked with past the time, the item should be directly added to the workqueue.
Maybe there's something wrong with the `AddAt` implementation.

File: staging/src/k8s.io/client-go/util/workqueue/delaying_queue_test.go [hunk 4]
```diff
@@ -174,6 +174,44 @@ func TestAddTwoFireEarly(t *testing.T) {
...
+
+	q.AddAt(addedAtPast, now.Add(-50*time.Millisecond))
+	q.AddAt(addedAtNow, now)
+	q.AddAt(addedAtFuture, now.Add(50*time.Millisecond))
+
+	if err := waitForWaitingQueueToFill(q); err != nil {
+		t.Fatalf("unexpected err: %v", err)
+	}
+
+	if err := waitForAdded(q, 2); err != nil {
```
Comment (alculquicondor) [inline staging/src/k8s.io/client-go/util/workqueue/delaying_queue_test.go:194]: we shouldn't need to wait... the first two elements should be added synchronously, IIUC.

File: pkg/controller/job/job_controller_test.go (hunk 3 above)
Comment (mimowo) [reply pkg/controller/job/job_controller_test.go]: Ok, I think I understand now why AddAt does not solve the flakes (but the scenario is more subtle than for AddAfter). This is the scenario:
- Test: creates a job with ActiveDeadlineSeconds=1 and clock at 0
- Job: sets the job.Status.StartTime=0
- Job: enters pastActiveDeadline and calls AddAt(1)
- DelayingQueue: add the item to waitingForAddCh as it is still at 0 time: https://github.com/kubernetes/kubernetes/blob/01d44159157529f8354e475ec796712298ca6608/staging/src/k8s.io/client-go/util/workqueue/delaying_queue.go#L204
- DelayingQueue: peeks up the entry and inserts into waitingForQueue https://github.com/kubernetes/kubernetes/blob/a66aad2d80dacc70025f95a8f97d2549ebd3208c/staging/src/k8s.io/client-go/util/workqueue/delaying_queue.go#L245
- DelayingQueue: peeks up the entry from waitingForQueue and decides to create the timer, determines the timer for 1s: https://github.com/kubernetes/kubernetes/blob/a66aad2d80dacc70025f95a8f97d2549ebd3208c/staging/src/k8s.io/client-go/util/workqueue/delaying_queue.go#L229
- Test: move the clock to 1s
- DelayingQueue: create the timer for 1s, but the timer will write to the channel at 2: 
https://github.com/kubernetes/kubernetes/blob/a66aad2d80dacc70025f95a8f97d2549ebd3208c/staging/src/k8s.io/client-go/util/workqueue/delaying_queue.go#L240
- Issue: we never move the clock to 2, but it also explains why moving the clock to 2 in the test helps

The inner workings of the delaying_queue are sensitive to the time moving forward, because they create a new inner timer based on the time difference (exposing to similar issues as AddAfter). 

It isn't clear to me how to "fix" that, and if the effort is worth the gain, given we have a one-liner solution (or a workaround) of adding `manager.clock.Sleep(200ms)`. The only downside of this I can think of is that occasionally the test would take 1s longer, but it is probably less than 1% of runs.

File: staging/src/k8s.io/client-go/util/workqueue/delaying_queue.go [hunk 5]
```diff
@@ -180,6 +182,29 @@ func (q *delayingType) AddAfter(item interface{}, duration time.Duration) {
 	}
 }
 
+// AddAt adds the given item to the work queue at the given time, if the specified
```
[the remark this answers is not in the document]
Comment (mimowo) [reply staging/src/k8s.io/client-go/util/workqueue/delaying_queue.go:185]: Done

File: staging/src/k8s.io/client-go/util/workqueue/delaying_queue_test.go [hunk 6]
```diff
@@ -174,6 +174,44 @@ func TestAddTwoFireEarly(t *testing.T) {
...
+	}
+	gotFirst, _ := q.Get()
+	if !reflect.DeepEqual(addedAtPast, gotFirst) {
+		t.Errorf("expected %v, got %v", addedAtPast, gotFirst)
+	}
+	gotSecond, _ := q.Get()
+	if !reflect.DeepEqual(addedAtNow, gotSecond) {
+		t.Errorf("expected %v, got %v", addedAtNow, gotSecond)
+	}
+	fakeClock.Step(60 * time.Millisecond)
```
[the remark this answers is not in the document]
Comment (mimowo) [reply staging/src/k8s.io/client-go/util/workqueue/delaying_queue_test.go:205]: Done

File: staging/src/k8s.io/client-go/util/workqueue/delaying_queue_test.go [hunk 7]
```diff
@@ -174,6 +174,44 @@ func TestAddTwoFireEarly(t *testing.T) {
...
+
+	if err := waitForWaitingQueueToFill(q); err != nil {
+		t.Fatalf("unexpected err: %v", err)
+	}
+
+	if err := waitForAdded(q, 2); err != nil {
+		t.Fatalf("unexpected err: %v", err)
+	}
+	gotFirst, _ := q.Get()
+	if !reflect.DeepEqual(addedAtPast, gotFirst) {
```
[the remark this answers is not in the document]
Comment (mimowo) [reply staging/src/k8s.io/client-go/util/workqueue/delaying_queue_test.go:198]: Done

File: staging/src/k8s.io/client-go/util/workqueue/delaying_queue_test.go [hunk 8]
```diff
@@ -174,6 +174,44 @@ func TestAddTwoFireEarly(t *testing.T) {
...
+	addedAtNow := "addedAtNow"
+	addedAtFuture := "addedAtFuture"
+
+	q.AddAt(addedAtPast, now.Add(-50*time.Millisecond))
+	q.AddAt(addedAtNow, now)
+	q.AddAt(addedAtFuture, now.Add(50*time.Millisecond))
+
+	if err := waitForWaitingQueueToFill(q); err != nil {
+		t.Fatalf("unexpected err: %v", err)
+	}
```
[the remark this answers is not in the document]
Comment (mimowo) [reply staging/src/k8s.io/client-go/util/workqueue/delaying_queue_test.go:192]: Yes

File: staging/src/k8s.io/client-go/util/workqueue/delaying_queue_test.go (hunk 4 above)
Comment (mimowo) [reply staging/src/k8s.io/client-go/util/workqueue/delaying_queue_test.go:194]: Yes, done

File: pkg/controller/job/job_controller_test.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/controller/job/job_controller_test.go]: A potential solution would be to have a `clock.NewTimerAt`, but that deviates too much from the standard `time` package.


What we can do is to remove the `clock.Sleep(1s)` and only leave the 200ms increments. But we should probably also throw an error if the job fails before the 1s is completed.

And we can get rid of `AddAt`, if we can't guarantee its behavior.

File: pkg/controller/job/job_controller_test.go [hunk 9]
```diff
@@ -1737,10 +1741,6 @@ func TestPastDeadlineJobFinished(t *testing.T) {
 			if err := sharedInformerFactory.Batch().V1().Jobs().Informer().GetIndexer().Add(job); err != nil {
 				t.Fatalf("Failed to insert job in index: %v", err)
 			}
-			// This is needed because the fake clientset doesn't report created pods
-			// to the informer, leading to unsatisfied expectations in syncJob that prevent the controller from setting the final condition.
-			podIndexer := sharedInformerFactory.Core().V1().Pods().Informer().GetIndexer()
-			setPodsStatuses(podIndexer, job, 0, 1, 0, 0, 0)
 
 			var j *batch.Job
 			err = wait.PollImmediate(200*time.Microsecond, 3*time.Second, func() (done bool, err error) {
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller_test.go:1746]: You can get rid of the checks in lines 1756 to 1761 and put it inside the Poll, if `clock.Now()` is earlier than 1s.

Comment (mimowo) [reply pkg/controller/job/job_controller_test.go:1746]: Done

**Review by alculquicondor — APPROVED** [review]
/lgtm
/approve

This makes more sense now, given the limitations of the clock :smiley:
