### PR TITLE
Restart the init container to not be stuck in created state

### LINKED ISSUE #126440: `SyncPod` may fail to start a pod with init container if `RunContainerError` occurs and SidecarContainers is enabled
### What happened?

It was consistently observed in a testing environment that a node-critical pod failed to start. `Created container setup` event was present but `Started container setup` was missing(`setup` is an init container). Also the following error was present but strangely only once: 
```
init container &Container{Name:setup,...} start failed in pod ... : RunContainerError: error reading from server: EOF
```

After some digging it seemed `m.runtimeService.StartContainer` throwing an error matched the observations above.
https://github.com/kubernetes/kubernetes/blob/7a4c962341e6ccd89db6736911e7e3bc7dd5165d/pkg/kubelet/kuberuntime/kuberuntime_container.go#L277-L286

### What did you expect to happen?

Eventually the init container and the pod to start

### How can we reproduce it (as minimally and precisely as possible)?

The following tests in `pkg/kubelet/kuberuntime/kuberuntime_manager_test.go` recreate the problem by `fakeRuntime.InjectError("StartContainer", errors.New("any error"))` and show how depending on `features.SidecarContainers` the behavior is different. When the feature gate is enabled the last init container gets stuck in `CONTAINER_CREATED` and never gets started. Therefore the pod get's stuck and never progresses

```go

func TestASidecarContainersTrue(t *testing.T) {
	featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.SidecarContainers, true)
	expected := []*cRecord{
		{name: "init1", attempt: 0, state: runtimeapi.ContainerState_CONTAINER_CREATED},
	}
	singleInit(t, expected)
}

func TestASidecarContainersFalse(t *testing.T) {
	featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.SidecarContainers, false)
	expected := []*cRecord{
		{name: "init1", attempt: 0, state: runtimeapi.ContainerState_CONTAINER_CREATED},
		{name: "init1", attempt: 1, state: runtimeapi.ContainerState_CONTAINER_RUNNING},
	}
	singleInit(t, expected)
}

func singleInit(t *testing.T, finalCRecord []*cRecord) {
	ctx := context.Background()
	fakeRuntime, _, m, err := createTestRuntimeManager()
	assert.NoError(t, err)

	initContainers := []v1.Container{
		{
			Name:            "init1",
			Image:           "init",
			ImagePullPolicy: v1.PullIfNotPresent,
		},
	}
	containers := []v1.Container{
		{
			Name:            "foo1",
			Image:           "busybox",
			ImagePullPolicy: v1.PullIfNotPresent,
		},
		{
			Name:            "foo2",
			Image:           "alpine",
			ImagePullPolicy: v1.PullIfNotPresent,
		},
	}
	pod := &v1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			UID:       "12345678",
			Name:      "foo",
			Namespace: "new",
		},
		Spec: v1.PodSpec{
			Containers:     containers,
			InitContainers: initContainers,
		},
	}

	backOff := flowcontrol.NewBackOff(time.Second, time.Minute)

	// 0. should fail creating init container
	podStatus, err := m.GetPodStatus(ctx, pod.UID, pod.Name, pod.Namespace)
	assert.NoError(t, err)
	fakeRuntime.InjectError("StartContainer", errors.New("any error"))
	result := m.SyncPod(context.Background(), pod, podStatus, []v1.Secret{}, backOff)
	err = result.Error()
	fmt.Println(err)
	assert.Error(t, err)
	expected := []*cRecord{
		{name: initContainers[0].Name, attempt: 0, state: runtimeapi.ContainerState_CONTAINER_CREATED},
	}
	verifyContainerStatuses(t, fakeRuntime, expected, "start only the init container")

	// 2. sync multiple times and test for expected final cRecords
	for _ = range 10 {
		podStatus, err = m.GetPodStatus(ctx, pod.UID, pod.Name, pod.Namespace)
		assert.NoError(t, err)
		result = m.SyncPod(ctx, pod, podStatus, []v1.Secret{}, backOff)
		assert.NoError(t, result.Error())
		verifyContainerStatuses(t, fakeRuntime, finalCRecord, "syncing")
	}
}

func TestBSidecarContainersTrue(t *testing.T) {
	featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.SidecarContainers, true)
	expected := []*cRecord{
		{name: "init1", attempt: 0, state: runtimeapi.ContainerState_CONTAINER_EXITED},
		{name: "init2", attempt: 0, state: runtimeapi.ContainerState_CONTAINER_CREATED},
	}
	multipleInits(t, expected)
}

func TestBSidecarContainersFalse(t *testing.T) {
	featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.SidecarContainers, false)
	expected := []*cRecord{
		{name: "init1", attempt: 0, state: runtimeapi.ContainerState_CONTAINER_EXITED},
		{name: "init2", attempt: 0, state: runtimeapi.ContainerState_CONTAINER_CREATED},
		{name: "init2", attempt: 1, state: runtimeapi.ContainerState_CONTAINER_RUNNING},
	}
	multipleInits(t, expected)
}

func multipleInits(t *testing.T, finalCRecord []*cRecord) {
	ctx := context.Background()
	fakeRuntime, _, m, err := createTestRuntimeManager()
	assert.NoError(t, err)

	initContainers := []v1.Container{
		{
			Name:            "init1",
			Image:           "init",
			ImagePullPolicy: v1.PullIfNotPresent,
		},
		{
			Name:            "init2",
			Image:           "init2",
			ImagePullPolicy: v1.PullIfNotPresent,
		},
	}
	containers := []v1.Container{
		{
			Name:            "foo1",
			Image:           "busybox",
			ImagePullPolicy: v1.PullIfNotPresent,
		},
		{
			Name:            "foo2",
			Image:           "alpine",
			ImagePullPolicy: v1.PullIfNotPresent,
		},
	}
	pod := &v1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			UID:       "12345678",
			Name:      "foo",
			Namespace: "new",
		},
		Spec: v1.PodSpec{
			Containers:     containers,
			InitContainers: initContainers,
		},
	}

	backOff := flowcontrol.NewBackOff(time.Second, time.Minute)

	// 1. should  create the firs init container.
	podStatus, err := m.GetPodStatus(ctx, pod.UID, pod.Name, pod.Namespace)
	assert.NoError(t, err)
	result := m.SyncPod(context.Background(), pod, podStatus, []v1.Secret{}, backOff)
	assert.NoError(t, result.Error())
	expected := []*cRecord{
		{name: initContainers[0].Name, attempt: 0, state: runtimeapi.ContainerState_CONTAINER_RUNNING},
	}
	verifyContainerStatuses(t, fakeRuntime, expected, "start the first init container")

	// 2. finish first init and fail to start the second
	// Stop init container instance 0.
	sandboxIDs, err := m.getSandboxIDByPodUID(ctx, pod.UID, nil)
	require.NoError(t, err)
	sandboxID := sandboxIDs[0]
	initID0, err := fakeRuntime.GetContainerID(sandboxID, initContainers[0].Name, 0)
	require.NoError(t, err)
	fakeRuntime.StopContainer(ctx, initID0, 0)
	// Simulate StartContainer failure
	fakeRuntime.InjectError("StartContainer", errors.New("any error"))
	// Sync again.
	podStatus, err = m.GetPodStatus(ctx, pod.UID, pod.Name, pod.Namespace)
	assert.NoError(t, err)
	result = m.SyncPod(ctx, pod, podStatus, []v1.Secret{}, backOff)
	assert.Error(t, result.Error())
	expected = []*cRecord{
		{name: initContainers[0].Name, attempt: 0, state: runtimeapi.ContainerState_CONTAINER_EXITED},
		{name: initContainers[1].Name, attempt: 0, state: runtimeapi.ContainerState_CONTAINER_CREATED},
	}
	verifyContainerStatuses(t, fakeRuntime, expected, "finish first init and fail to start the second")

	// sync multiple times and test for expected final cRecords
	for _ = range 10 {
		podStatus, err = m.GetPodStatus(ctx, pod.UID, pod.Name, pod.Namespace)
		assert.NoError(t, err)
		result = m.SyncPod(ctx, pod, podStatus, []v1.Secret{}, backOff)
		assert.NoError(t, result.Error())
		verifyContainerStatuses(t, fakeRuntime, finalCRecord, "syncing")
	}
}
```

### Anything else we need to know?

The problem seems to stem from:
https://github.com/kubernetes/kubernetes/blob/7a4c962341e6ccd89db6736911e7e3bc7dd5165d/pkg/kubelet/kuberuntime/kuberuntime_container.go#L1015-L1018

There `kubecontainer.ContainerStateCreated` case get's skipped and the created container is expected to get started by the previous one by the following lines
https://github.com/kubernetes/kubernetes/blob/7a4c962341e6ccd89db6736911e7e3bc7dd5165d/pkg/kubelet/kuberuntime/kuberuntime_container.go#L1122
or
https://github.com/kubernetes/kubernetes/blob/7a4c962341e6ccd89db6736911e7e3bc7dd5165d/pkg/kubelet/kuberuntime/kuberuntime_container.go#L1171
But the provided tests show that this does not happen. Also if there is only one init container with `kubecontainer.ContainerStateCreated` the following logic should execute but won't
https://github.com/kubernetes/kubernetes/blob/7a4c962341e6ccd89db6736911e7e3bc7dd5165d/pkg/kubelet/kuberuntime/kuberuntime_container.go#L1215-L1219
because in this case this get's executed
https://github.com/kubernetes/kubernetes/blob/7a4c962341e6ccd89db6736911e7e3bc7dd5165d/pkg/kubelet/kuberuntime/kuberuntime_container.go#L1209-L1212

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by gjkim42**
#### What type of PR is this?

/kind regression
/kind bug

#### What this PR does / why we need it:
This restarts the init container if it is stuck in the created state, as it may have failed to start correctly.
This fixes a regression from https://github.com/kubernetes/kubernetes/pull/116429.

#### Which issue(s) this PR fixes:

Fixes #126440

#### Does this PR introduce a user-facing change?

```release-note
Fixed a regression in default 1.29 configurations with the SidecarContainers feature enabled, where init containers may fail to start due to a temporary container runtime failure.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/kuberuntime/kuberuntime_manager_test.go [hunk 1]
```diff
@@ -1170,6 +1170,17 @@ func TestComputePodActions(t *testing.T) {
 				ContainersToStart: []int{1},
 			},
 		},
+		"Restart the container if the container is in created state": {
```
Comment (toVersus) [inline pkg/kubelet/kuberuntime/kuberuntime_manager_test.go:1173]: I see, you're adding a test case here because the kubelet handles the Regular Containers [the same way](https://github.com/kubernetes/kubernetes/blob/00236ae0d73d2455a2470469ed1005674f8ed61f/pkg/kubelet/container/helpers.go#L89-L92).

**Review by toVersus — COMMENTED** [review]
The change looks good to me, but you're planning to include the E2E tests in this PR if we get the scenario that causes the issue and can turn it into a test, right?

**Comment by gjkim42** [comment]
> The change looks good to me, but you're planning to include the E2E tests in this PR if we get the scenario that causes the issue and can turn it into a test, right?

I intended to do that, but since it is difficult to simulate the temporary container runtime failure, fixing it with unit tests should be ok.

File: pkg/kubelet/kuberuntime/kuberuntime_container.go [hunk 2]
```diff
@@ -1084,7 +1084,8 @@ func (m *kubeGenericRuntimeManager) computeInitContainerActions(pod *v1.Pod, pod
 
 		switch status.State {
 		case kubecontainer.ContainerStateCreated:
-			// nothing to do but wait for it to start
+			// restart the container if it is stuck in the created state
+			changes.InitContainersToStart = append(changes.InitContainersToStart, i)
```
Comment (bart0sh) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go:1088]: Can you explain why container considered stuck if it's in the `ContainerStateCreated` state?

Comment (gjkim42) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:1088]: That is because of the old code that does nothing in the Created state.
I'll rephrase it.

Comment (bart0sh) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:1090]: It still looks to me like we're trying to unconditionally restart container if it's in the `ContainerStateCreated` state. Where this state is set? Where is it updated? Why is it `likely that the container runtime has failed to start the container` if the container is in this state?

/hold

Comment (gjkim42) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:1090]: This is a part of the main sync loop and
1. it checks the state
2. calls the CreateContainer
3. calls the StartContainer

in sequence with blocking manner (waiting for the result).

Therefore, if a container is in the Created state at step 1, it means that the container runtime has failed to StartContainer.

https://github.com/kubernetes/kubernetes/pull/126543/files#r1704785057
^
The regular containers behave in the same way.

Comment (bart0sh) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:1090]: It does. Thanks for the explanations!
/unhold

Comment (hshiina) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:1090]: This can cause the same issue as #123087 for init containers when `EventedPLEG` is enabled.

Container statuses evaluated here are updated asynchronously by PLEG. So, `ContainerStateCreated` could be seen when a container is starting normally especially with `EventedPLEG` enabled.
xref: https://github.com/kubernetes/kubernetes/pull/122778#issuecomment-1956910606

Comment (toVersus) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:1090]: Thanks for sharing! I see that the change to prevent Regular containers from restarting in the Created state when Evented PLEG is enabled will be made in https://github.com/kubernetes/kubernetes/pull/122778.

This PR fixes a regression in Generic PLEG caused by Sidecar Containers feature. We could either merge this PR first and then address the case for initContainers in https://github.com/kubernetes/kubernetes/pull/122778, or we could take a different approach. Based on the  https://github.com/kubernetes/enhancements/issues/3386#issuecomment-2309247626, it looks like there might be some progress with https://github.com/kubernetes/kubernetes/pull/122778 in near future too.

/cc @pacoxu

Comment (pacoxu) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:1090]: This addressed the problem of Generic PLEG. 

/lgtm
/approve

File: pkg/kubelet/kuberuntime/kuberuntime_container.go [hunk 3]
```diff
@@ -1084,7 +1084,10 @@ func (m *kubeGenericRuntimeManager) computeInitContainerActions(pod *v1.Pod, pod
```
Comment (liggitt) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go:1084]: computeInitContainerActions looks like a new code path only enabled when the SidecarContainers feature is enabled?

taking a step back, should we only take this new code path in pods which actually have made use of the sidecar feature? ideally, bugs in this new code path would only impact pods that have specifically opted into using the new sidecar feature, and all other pods would have their behavior stay the same.

File: pkg/kubelet/kuberuntime/kuberuntime_container.go (hunk 2 above)
Comment (ffromani) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:1090]: @gjkim42 if (and only if) you happen to resubmit, could you please add more of your comment https://github.com/kubernetes/kubernetes/pull/126543/commits/7e8ea57cc6ee29631e8a66cc521a48803a16cd14#r1724882374 in the code comment? I feel the github comment concisely and clearly describes the fix so it would be great to have it in the codebase and not lost in github review comments.

File: pkg/kubelet/kuberuntime/kuberuntime_container.go (hunk 3 above)
Comment (gjkim42) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:1084]: I would like to remove the old code path while updating the new one once the SidecarContainers feature reaches GA, since there is a lot of shared logic for the init container's actions.

File: pkg/kubelet/kuberuntime/kuberuntime_container.go (hunk 2 above)
Comment (gjkim42) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:1092]: resubmitted.

**Comment by ffromani** [comment]
/lgtm

only changed comment from the last LGTM

**Comment by gjkim42** [comment]
/assign @SergeyKanzhelev @smarterclayton 

Could you please take a look? 
This will resolve the regression where the init container could get stuck in the 'created' state due to a partial failure (successfully created but failed to start).

File: pkg/kubelet/kuberuntime/kuberuntime_container.go (hunk 3 above)
Comment (liggitt) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:1084]: > I would like to remove the old code path while updating the new one once the SidecarContainers feature reaches GA, since there is a lot of shared logic for the init container's actions.

The number one priority is to ensure that pods that didn't opt into the new feature are not impacted by bugs in the new code path. This is the second time the sidecar feature has regressed, so I think it's important to leave the old code path active for pods which have not opted in until the new code path has proven it works correctly over multiple releases.

Comment (gjkim42) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:1084]: I agree that it should have been implemented in that way, but it might be a bit late now since the sidecar wg is considering to promote this feature to GA in the next release...

cc @SergeyKanzhelev

Comment (liggitt) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:1084]: > it might be a bit late now since the sidecar wg is considering to promote this feature to GA in the next release...

I do not agree. The presence of a regression in this code path should make us hesitant to make this code path unconditional. Recovering compatibility for 1.29-1.31 should be our top priority. Reviewing these changes and closing test gaps should be our second priority. Promotion to GA should come after all of those.

Comment (gjkim42) [reply pkg/kubelet/kuberuntime/kuberuntime_container.go:1084]: ok, I'll create a PR for that to ensure that the minimize the impact of the new code path.

**Comment by gjkim42** [comment]
https://github.com/kubernetes/kubernetes/pull/127162
made a PR to fix the regression related to the regular init containers first.

still need this PR to fix the bug where restartable init containers can be stuck in the created state.

**Comment by gjkim42** [comment]
manually tested this PR with customized containerd (that fails to start container at first after 10s) and confirmed that this PR fixed this bug with regular and restartable init containers.

```
NAME                                   READY   STATUS     RESTARTS   AGE                                                                                                                            [3/1683]
fixed-k8s-regular-init-container       0/1     Init:0/1   0          7s               
fixed-k8s-restartable-init-container   0/2     Init:0/1   0          7s               
k8s-1.30-regular-init-container        0/1     Init:0/1   0          7s               
k8s-1.30-restartable-init-container    0/2     Init:0/1   0          7s               
NAME                                   READY   STATUS     RESTARTS   AGE              
fixed-k8s-regular-init-container       0/1     Init:0/1   0          9s               
fixed-k8s-restartable-init-container   0/2     Init:0/1   0          9s               
k8s-1.30-regular-init-container        0/1     Init:0/1   0          9s               
k8s-1.30-restartable-init-container    0/2     Init:0/1   0          9s               
NAME                                   READY   STATUS     RESTARTS   AGE              
fixed-k8s-regular-init-container       0/1     Init:0/1   0          12s              
fixed-k8s-restartable-init-container   0/2     Init:0/1   0          12s              
k8s-1.30-regular-init-container        0/1     Init:0/1   0          12s              
k8s-1.30-restartable-init-container    0/2     Init:0/1   0          12s              
NAME                                   READY   STATUS                   RESTARTS   AGE
fixed-k8s-regular-init-container       0/1     Init:RunContainerError   0          14s
fixed-k8s-restartable-init-container   0/2     Init:0/1                 0          14s
k8s-1.30-regular-init-container        0/1     Init:RunContainerError   0          14s
k8s-1.30-restartable-init-container    0/2     Init:0/1                 0          14s
NAME                                   READY   STATUS                   RESTARTS   AGE
fixed-k8s-regular-init-container       0/1     Init:0/1                 1          16s
fixed-k8s-restartable-init-container   0/2     Init:RunContainerError   0          16s
k8s-1.30-regular-init-container        0/1     Init:RunContainerError   0          16s
k8s-1.30-restartable-init-container    0/2     Init:RunContainerError   0          16s
NAME                                   READY   STATUS                   RESTARTS   AGE
fixed-k8s-regular-init-container       0/1     Init:0/1                 1          18s
fixed-k8s-restartable-init-container   1/2     PodInitializing          1          18s
k8s-1.30-regular-init-container        0/1     Init:RunContainerError   0          18s                                                                                                                      
k8s-1.30-restartable-init-container    0/2     Init:RunContainerError   0          18s
NAME                                   READY   STATUS                   RESTARTS   AGE
fixed-k8s-regular-init-container       0/1     Init:0/1                 1          20s
fixed-k8s-restartable-init-container   2/2     Running                  1          20s
k8s-1.30-regular-init-container        0/1     Init:RunContainerError   0          20s
k8s-1.30-restartable-init-container    0/2     Init:RunContainerError   0          20s
NAME                                   READY   STATUS                   RESTARTS   AGE
fixed-k8s-regular-init-container       0/1     Init:0/1                 1          22s
fixed-k8s-restartable-init-container   2/2     Running                  1          22s
k8s-1.30-regular-init-container        0/1     Init:RunContainerError   0          22s
k8s-1.30-restartable-init-container    0/2     Init:RunContainerError   0          22s
NAME                                   READY   STATUS                   RESTARTS   AGE
fixed-k8s-regular-init-container       0/1     Init:0/1                 1          24s
fixed-k8s-restartable-init-container   2/2     Running                  1          24s
k8s-1.30-regular-init-container        0/1     Init:RunContainerError   0          24s
k8s-1.30-restartable-init-container    0/2     Init:RunContainerError   0          24s
NAME                                   READY   STATUS                   RESTARTS   AGE
fixed-k8s-regular-init-container       0/1     PodInitializing          0          26s
fixed-k8s-restartable-init-container   2/2     Running                  1          26s
k8s-1.30-regular-init-container        0/1     Init:RunContainerError   0          26s
k8s-1.30-restartable-init-container    0/2     Init:RunContainerError   0          26s
NAME                                   READY   STATUS                   RESTARTS   AGE
fixed-k8s-regular-init-container       1/1     Running                  0          28s
fixed-k8s-restartable-init-container   2/2     Running                  1          28s
k8s-1.30-regular-init-container        0/1     Init:RunContainerError   0          28s
k8s-1.30-restartable-init-container    0/2     Init:RunContainerError   0          28s
```

```
$ k get nodes
NAME                 STATUS   ROLES           AGE     VERSION
kind-control-plane   Ready    control-plane   2m44s   v1.32.0-alpha.0.171+4363a8453cef12-dirty
kind-worker          Ready    <none>          2m33s   v1.30.4
kind-worker2         Ready    <none>          2m32s   v1.32.0-alpha.0.171+4363a8453cef12-dirty
```

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

this matches the behavior of a regular containers: https://github.com/kubernetes/kubernetes/blob/d28fca12944f12a778392147b862c24c48289544/pkg/kubelet/container/helpers.go#L89-L92

It was an interesting code digging to understand how it works. Thank you @gjkim42!
