### PR TITLE
Invalidate resource requirements on extended resources with only request set

### LINKED ISSUE #57276: Device manager only considers extended resource limits when allocating devices.
/kind bug
/sig node
/area hw-accelerators

**What happened**:
In `/pkg/kubelet/cm/deviceplugin/manager.go` devices are allocated from a function called `allocateContainerResources`. This function inspects only container resource limits, ignoring container resource requests. This is a usability problem because it is valid to omit limits for extended resources. If limit is omitted for a device resource, then the scheduler properly places the pod with respect to available node resources. However, the device manager never dispatches to the device plugin for that resource. The result is that the user application cannot access the requested device from inside the container.

**What you expected to happen**:
Following the documented behavior of extended resources, I expected that specifying a container resource request for a device would cause the device subsystem to properly configure access for my workload.

**How to reproduce it (as minimally and precisely as possible)**:
* Launch an alpha GKE cluster with GPU support enabled.
* Attempt to run any program that accesses the GPU from a container where the resource is specified in requests but omitted from limits.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8+
- Cloud provider or hardware configuration: device plugins enabled, devices available.

### PR DESCRIPTION
**Pull request by jiayingz**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubernetes/issues/57276

**Special notes for your reviewer**:

**Release note**:

```release-note
Returns an error for non overcommitable resources if they don't have limit field set in container spec.
```

### CODE REVIEW

File: pkg/apis/core/helper/helpers.go [hunk 1]
```diff
@@ -167,6 +167,7 @@ var overcommitBlacklist = sets.NewString(string(core.ResourceNvidiaGPU))
 func IsOvercommitAllowed(name core.ResourceName) bool {
 	return IsDefaultNamespaceResource(name) &&
 		!IsHugePageResourceName(name) &&
+		!IsExtendedResourceName(name) &&
```
Comment (ConnorDoyle) [inline pkg/apis/core/helper/helpers.go]: This predicate is technically correct but redundant since extended resources are by definition disjoint from default namespace resources. Probably we only need one of the two, but it would be helpful to add a comment saying why this was correct.

File: pkg/apis/core/validation/validation.go [hunk 2]
```diff
@@ -4366,13 +4366,13 @@ func ValidateResourceRequirements(requirements *core.ResourceRequirements, fldPa
...
 		if exists {
-			// For GPUs, not only requests can't exceed limits, they also can't be lower, i.e. must be equal.
+			// For non overcommitable resources, not only requests can't exceed limits, they also can't be lower, i.e. must be equal.
 			if quantity.Cmp(limitQuantity) != 0 && !helper.IsOvercommitAllowed(resourceName) {
 				allErrs = append(allErrs, field.Invalid(reqPath, quantity.String(), fmt.Sprintf("must be equal to %s limit", resourceName)))
 			} else if quantity.Cmp(limitQuantity) > 0 {
 				allErrs = append(allErrs, field.Invalid(reqPath, quantity.String(), fmt.Sprintf("must be less than or equal to %s limit", resourceName)))
 			}
-		} else if resourceName == core.ResourceNvidiaGPU {
+		} else !helper.IsOvercommitAllowed(resourceName) {
```
Comment (ConnorDoyle) [inline pkg/apis/core/validation/validation.go]: Good catch! :+1:

File: pkg/apis/core/helper/helpers.go (hunk 1 above)
Comment (vikaschoudhary16) [reply pkg/apis/core/helper/helpers.go]: Agree, comment makes more sense over redundant line of code.

Comment (jiayingz) [reply pkg/apis/core/helper/helpers.go]: Good catch! Removed.

File: pkg/apis/core/validation/validation.go (hunk 2 above)
Comment (jiayingz) [reply pkg/apis/core/validation/validation.go]: @ConnorDoyle do you have any suggestions on how we should roll out this API change? Can we first update the extended resource doc to document this side effect for 1.8 and 1.9 and mention our plan on invalidating this kind of resource spec in 1.10, and then have the validation logic take effect in 1.10?

**Comment by jiayingz** [comment]
/assign @davidopp @bsalamat 

Would like to get some opinions from the scheduling folks on this PR. In short, for extended resources introduced in 1.8, we clearly document that "Extended resources are only supported as integer resources and cannot be overcommitted" in its doc https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#extended-resources, but the current ValidateResourceRequirements check actually allows that only request field is set for extended resources and the current extended resource doc also implies that this kind of resource spec is allowed: "Extended resources cannot be overcommitted, so request and limit must be equal if both are present in a container spec." In this PR, I am thinking to change ValidateResourceRequirements logic to return an error for such resource spec to make it clear that extended resource doesn't allow overcommit, but this may break some existing pod specs that are formatted this way. Would like to get some opinions on whether we should leave the current validation logic as is and rely on the ER doc to communicate the fact that overcommit is not supported on ER, or we should consider to change the validation logic in a future release but document that plan now.

File: pkg/apis/core/validation/validation.go (hunk 2 above)
Comment (ConnorDoyle) [reply pkg/apis/core/validation/validation.go]: I think we should consider not making this change.

The semantics of resource requests are: a minimum amount provided to a container. There's no indication implied that bursting is allowed for arbitrary resources, although we allow it for cpu and memory and that is documented. Also, we do already disallow limit ≠ request in validation.

Could you outline the specific user benefit of the validation change? Then we can weigh it against the cost.

**Comment by ConnorDoyle** [comment]
Copying hidden reply from above:

> I think we should consider not making this change.
>
> The semantics of resource requests are: a minimum amount provided to a container. There's no indication implied that bursting is allowed for arbitrary resources, although we allow it for cpu and memory and that is documented. Also, we do already disallow limit ≠ request in validation.
>
> Could you outline the specific user benefit of the validation change? Then we can weigh it against the cost.

**Comment by bsalamat** [comment]
@jiayingz Scheduler uses "Requests" for scheduling and does not control overcommitment. It is up to the node/kubelet to allow a pod to use more resources, including ER, than requested. If kubelet does not allow overcommitment of ER, that will probably be enough for preventing pods from using more resources than requested.
I think the change in this PR generally makes sense, but as you mentioned, is not backward compatible and could break existing pods. So, we may want to rely on existing mechanisms that do not allow pods to consume more of ERs than requested.

**Comment by vikaschoudhary16** [comment]
I am unable to visualize a issue that we may hit if we skip this validation check. In CPU and memory case, it is required to put upper cap, before hand, using `Limits` because if we dont, any container may consume more than desired/disproportionate amount of these resource. On the contrary, with ER, Is it possible for a pod to consume more than allocated resources? I guess, NO.
Therefore, IMO, it should be safe to skip this change if i have not missed some use case.

**Comment by ConnorDoyle** [comment]
Related issue: #57276

File: pkg/apis/core/validation/validation.go [hunk 3]
```diff
@@ -4366,13 +4366,13 @@ func ValidateResourceRequirements(requirements *core.ResourceRequirements, fldPa
...
 		if exists {
-			// For GPUs, not only requests can't exceed limits, they also can't be lower, i.e. must be equal.
+			// For non overcommitable resources, not only requests can't exceed limits, they also can't be lower, i.e. must be equal.
 			if quantity.Cmp(limitQuantity) != 0 && !helper.IsOvercommitAllowed(resourceName) {
 				allErrs = append(allErrs, field.Invalid(reqPath, quantity.String(), fmt.Sprintf("must be equal to %s limit", resourceName)))
 			} else if quantity.Cmp(limitQuantity) > 0 {
 				allErrs = append(allErrs, field.Invalid(reqPath, quantity.String(), fmt.Sprintf("must be less than or equal to %s limit", resourceName)))
 			}
-		} else if resourceName == core.ResourceNvidiaGPU {
+		} else if !helper.IsOvercommitAllowed(resourceName) {
```
Comment (vishh) [inline pkg/apis/core/validation/validation.go]: Can we some unit tests for this?

**Comment by vishh** [comment]
As @jiayingz mentioned, extended resources are not expected to allow for overcommit to begin with until we have better Resource APIs that allow for expressing overcommit capabilities offered at the node level. I can't think of a use case for overcommit at the cluster level.
We made an error in documentation and we should fix both documentation and code.
I suspect the user base for extended resources is relatively small atm and so I hope such a breaking change won't impact a lot of users. We can offer an opt-out flag if needed to ease with the transition (I doubt it will be necessary though).

**Comment by vishh** [comment]
And as far as device plugin goes, since it does not support overcommit, it should require request to equal limits if it considers requests for allocations.

**Comment by vikaschoudhary16** [comment]
@vishh We tried to keep the API same and since in current behavior. `Requests` without `Limits` , though, is allowed, but IIUC, this is not the condition for overcommit. For overcommit, `Limits` must be greater than `Requests` and that is not allowed in current behavior. Therefore, in current code, overcommit is not allowed.  
What you want is, please correct me if i am wrong:
1. To keep [this check](https://github.com/kubernetes/kubernetes/pull/57170#discussion-diff-157575732R4375) from Jiyang's PR. This will ensure that limits are present.
2. revert my change is manager.go to use `Limits` only, as it was before.
3. Create a PR to fix documentation, which today says that limits are optional.

Thats fine too. Its just that we were not sure initially about changing the API behavior. Your point about a very small user base of ER, makes sense though. Please confirm if above three points is the way forward.

**Comment by vishh** [comment]
absence of limit typically means give me everything available on the node.
so today's behavior is enabling overcommit according to my understanding.
+1 on the plan proposed.

**Comment by ConnorDoyle** [comment]
Apologies for jumping the gun on the other PR. I assumed that we wouldn’t tolerate an incompatible API change, but after all should have waited for discussion to settle before proceeding.

Given that @vishh prefers to make the API change, the new plan makes sense. The compelling case for me is a future scenario where we have a way to specify scheduling properties of each resource. This would make the overcommit-ibility of a resource distinguishable from the use site in container specs and less implicit.

**Comment by bsalamat** [comment]
After reading @vishh's comments and given that backward compatibility is not a major concern (given the small number of users), this change LGTM.

/lgtm

**Comment by ConnorDoyle** [comment]
Would love to get this landed. I ran into https://github.com/kubernetes/kubernetes/issues/57276 myself again (!!!) since the other patch was reverted.
