### PR TITLE
fix node controller event uid issue

### LINKED ISSUE #29289: Node.metadata.uid != Event.involvedObject.uid for event of the same Node
event.involvedObject.uid seems incorrect as it contains  Node.metadata.name. other times  it is missing entirely.

Based on an [issue](https://github.com/ManageIQ/manageiq/issues/9600) reported in ManageIQ. (see [comment](https://github.com/ManageIQ/manageiq/issues/9600#issuecomment-233879235) for rest output)

### PR DESCRIPTION
**Pull request by adohe-zz**
Fix #29289. @smarterclayton ptal. This is not a very elegant fix, if we can use nodeName in log maybe we can set timedValue.Value to node.UID.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/29437)

### CODE REVIEW

File: pkg/controller/node/controller_utils.go [hunk 1]
```diff
@@ -304,7 +304,7 @@ func terminatePods(kubeClient clientset.Interface, recorder record.EventRecorder
 		if remaining < 0 {
 			remaining = 0
 			glog.V(2).Infof("Removing pod %v after %s grace period", pod.Name, grace)
-			recordNodeEvent(recorder, nodeName, api.EventTypeNormal, "TerminatingEvictedPod", fmt.Sprintf("Pod %s has exceeded the grace period for deletion after being evicted from Node %q and is being force killed", pod.Name, nodeName))
+			recordNodeEvent(recorder, nodeName, nodeUID, api.EventTypeNormal, "TerminatingEvictedPod", fmt.Sprintf("Pod %s has exceeded the grace period for deletion after being evicted from Node %q and is being force killed", pod.Name, nodeName))
```
Comment (smarterclayton) [inline pkg/controller/node/controller_utils.go]: We should add a test that ensures that these events are being correctly formed.

File: pkg/controller/node/rate_limited_queue.go [hunk 2]
```diff
@@ -29,6 +29,7 @@ import (
 // TimedValue is a value that should be processed at a designated time.
 type TimedValue struct {
 	Value     string
+	UID       string
```
Comment (smarterclayton) [inline pkg/controller/node/rate_limited_queue.go]: The queue is supposed to be generic, this would be better as interface{} with casts as necessary in the controller.

File: pkg/controller/node/controller_utils.go [hunk 3]
```diff
@@ -67,7 +67,7 @@ func cleanupOrphanedPods(pods []*api.Pod, nodeStore cache.Store, forcefulDeleteP
 
 // deletePods will delete all pods from master running on given node, and return true
 // if any pods were deleted.
-func deletePods(kubeClient clientset.Interface, recorder record.EventRecorder, nodeName string, daemonStore cache.StoreToDaemonSetLister) (bool, error) {
+func deletePods(kubeClient clientset.Interface, recorder record.EventRecorder, nodeName, nodeUID string, daemonStore cache.StoreToDaemonSetLister) (bool, error) {
```
Comment (smarterclayton) [inline pkg/controller/node/controller_utils.go]: We have the potential for delete-create-delete race in the node controller because we don't check uid.  Can you open an issue against the node controller that we need to precondition pod deletion against Pod uid?  There may be one open, but if not it's something that may be causing real problems today.

Comment (AdoHe) [inline pkg/controller/node/controller_utils.go]: Sure, I will do that.

File: pkg/controller/node/controller_utils.go (hunk 1 above)
Comment (AdoHe) [inline pkg/controller/node/controller_utils.go]: @smarterclayton I just noticed that we have already add such test cases [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/client/record/event_test.go#L104). So do we still need to add test case in node controller? If so I will do that.

File: pkg/controller/node/rate_limited_queue.go [hunk 4]
```diff
@@ -201,10 +203,11 @@ func (q *RateLimitedTimedQueue) Try(fn ActionFunc) {
 
 // Adds value to the queue to be processed. Won't add the same value a second time if it was already
 // added and not removed.
-func (q *RateLimitedTimedQueue) Add(value string) bool {
+func (q *RateLimitedTimedQueue) Add(value string, uid interface{}) bool {
```
Comment (cben) [inline pkg/controller/node/rate_limited_queue.go]: Comment above might need clarification whether "same value" is by value or by uid.
I see UniqueQueue does `if q.set.Has(value.Value) { return false }` where `.set` is a set of strings, so by value.
But then it's unclear what exactly "anything that can identify the value" means.
Also consider tests with non-1:1 correspondence of values and uids.

File: pkg/controller/node/nodecontroller.go [hunk 5]
```diff
@@ -367,14 +367,15 @@ func (nc *NodeController) Run(period time.Duration) {
 		defer nc.evictorLock.Unlock()
 		for k := range nc.zonePodEvictor {
 			nc.zonePodEvictor[k].Try(func(value TimedValue) (bool, time.Duration) {
-				remaining, err := deletePods(nc.kubeClient, nc.recorder, value.Value, nc.daemonSetStore)
+				uid, _ := value.UID.(string)
```
Comment (cben) [inline pkg/controller/node/nodecontroller.go]: Reading at this point, it's not clear what was put into `value`.
Consider naming this var `nodeUid` to clarify.
(same below line 392)

**Comment by cben** [comment]
Checked out 6da31ac9e09316909269947f3935a423ff43b051, built, run hack/local-up-cluster.sh.
Right after start, `get events` gives some node events — one is fixed but rest still have uid==name:
```
$ cluster/kubectl.sh get events -o json | jq '.items[] | [.involvedObject.kind, .involvedObject.uid, .message]' --compact-output
["Node","127.0.0.1","Starting kube-proxy."]
["Node","127.0.0.1","Starting kubelet."]
["Node","127.0.0.1","Node 127.0.0.1 status is now: NodeHasSufficientDisk"]
["Node","127.0.0.1","Node 127.0.0.1 status is now: NodeHasSufficientMemory"]
["Node","d301b962-5257-11e6-a1e2-68f728fac3ab","Node 127.0.0.1 event: Registered Node 127.0.0.1 in NodeController"]
["Node","127.0.0.1","Node 127.0.0.1 status is now: NodeReady"]
```
See https://gist.github.com/cben/43aa949104345928e9c2980eb574e5c4 for full events json.

**Comment by AdoHe** [comment]
@cben thanks for pointing out, I will take a deep look.

File: pkg/controller/node/controller_utils.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/controller/node/controller_utils.go]: This would be a test to verify the correct node UID was set, as long as
it's not unreasonably difficult to properly abstract.  If it's too complex
I'm fine with not including it.

**Comment by AdoHe** [comment]
@cben From the link you give, I can see that events generated by kubelet and kube-proxy still use nodeName as nodeUID, this is right, as uid is generated in server side.

**Comment by AdoHe** [comment]
@smarterclayton just update, ptal.

File: pkg/controller/node/controller_utils_test.go [hunk 6]
```diff
@@ -0,0 +1,138 @@
...
+		"TestNode03": {
+			name:      "TestNode03",
+			uid:       "33333",
+			eventType: api.EventTypeNormal,
+			reason:    "Started",
+			event:     "start",
+			expectUID: "33333",
+		},
+	}
+	recorder := NewFakeRecorder(len(table))
```
Comment (smarterclayton) [inline pkg/controller/node/controller_utils_test.go]: I guess I was expecting a test in node_controller_test.go that verified that a few of the scenarios we test generated an event into the fake recorder.  Is that too difficult to abstract in the current tests today?

**Comment by AdoHe** [comment]
@smarterclayton I just update this, ptal.

**Comment by AdoHe** [comment]
@k8s-bot test this issue: #IGNORE
