### PR TITLE
kubeadm: update embedded CA in kubeconfig files on renewal

### LINKED ISSUE #2027: kubeadm alpha certs renew fails to update CA in conf files
## What keywords did you search in kubeadm issues before filing this one?
'kubeadm alpha certs', 'certs renew', 'kubeadm alpha'

## Versions
1.16.4

**kubeadm version** (use `kubeadm version`): 1.16.4

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.16.4
- **Cloud provider or hardware configuration**: On premise
- **OS** (e.g. from /etc/os-release): CentOS 7
- **Kernel** (e.g. `uname -a`): 3.10.0-1062.4.3.el7.x86_64
- **Others**:

## What happened?
* I have created new CA's each for kubernetes and front-proxy tried to renew CA along with all underlying certificates.
* Ran ```kubeadm alpha certs renew <item>``` one by one for all certificates and conf files with the new CA in a separate --cert-dir.
* Certificates got signed by the new CA properly.
* CONF files got updated with correct client-certificate-data and client-key-data but incorrect or old certificate-authority-data.

## What you expected to happen?
CONF files must be updated with new CA (base64)content instead of the old CA.

## How to reproduce it (as minimally and precisely as possible)?
* Create new CA cert and key
* copy existing pki dir to a temp dir
* replace old CA in the temp dir with the NEW CA cert and key
* Run  ```kubeadm alpha certs renew <item>``` one by one for all certificates and conf files with the new CA along with --cert-dir=\< temp dir \>.
* backup existing certs
* replace all certs from temp dir to /etc/kubernetes/pki
* wait for API server to update or restart the control plane containers.
* alternatively, you can also decrypt the content of certificate-authority-data from admin.conf file and run openssl to match dates to validate the certs ```awk '/certificate-authority-data:/ {print $2}' admin.conf| base64 -d|openssl x509 -noout -dates``` and ```openssl x509 -in /etc/kubernetes/pki/ca.crt -noout -dates```

## Anything else we need to know
not related to #1518, #1361 has some ref but not solution

the problem is updating certs would work as long as one is not updating the CA itself not the other way round.

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:
While kubeadm does not support CA rotation,
the users might still attempt to perform this manually.
For kubeconfig files, updating to a new CA is not reflected
and users need to embed the new CA PEM manually.

On kubeconfig cert renewal, always keep the embedded CA
in sync with the one on disk.

Includes a couple of typo fixes.

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#2027

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: on kubeconfig certificate renewal, keep the embedded CA in sync with the one on disk
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

@kubernetes/sig-cluster-lifecycle-pr-reviews 
/assign @fabriziopandini 
/priority important-longterm

somewhere in between:
/kind bug
and
/kind feature

### CODE REVIEW

File: cmd/kubeadm/app/phases/certs/renewal/readwriter.go [hunk 1]
```diff
@@ -183,6 +199,12 @@ func (rw *kubeConfigReadWriter) Write(newCert *x509.Certificate, newKey crypto.S
 		return errors.Wrapf(err, "failed to marshal private key to PEM")
 	}
 
+	// Update the embedded CA in the kubeconfig file.
+	// This assumes that the user has kept the current context to the desired one.
+	clusterName := rw.kubeConfig.Contexts[rw.kubeConfig.CurrentContext].Cluster
+	cluster := rw.kubeConfig.Clusters[clusterName]
+	cluster.CertificateAuthorityData = pkiutil.EncodeCertPEM(rw.caCert)
```
Comment (rosti) [inline cmd/kubeadm/app/phases/certs/renewal/readwriter.go]: This looks a bit scary. Perhaps log the overwrite somewhere if the old and new bytes differ?
Other than that, it looks good to me.

/lgtm
/hold
for @fabriziopandini to TAL.

Comment (neolit123) [reply cmd/kubeadm/app/phases/certs/renewal/readwriter.go]: well we are using the same CA file for the renewal of certificates.
using a comparison first is fine, but it will not gain security benefits, only a performance benefit.

Comment (rosti) [reply cmd/kubeadm/app/phases/certs/renewal/readwriter.go]: Yep, I guess I am over paranoid here. It's fine like it is.

**Review by fabriziopandini — APPROVED** [review]
@neolit123 thanks for this PR!
I see no warm in refreshing CA while renewing certificates in the kubeconf files.
/hold cancel
/lgtm
