### PR TITLE
Stop controller when the stop channel is closed (when queue is empty and Pop is hanging)

### LINKED ISSUE #28158: Closing a stopChannel does not stop a controller
Let `ctrl` be a `Controller` returned by `framework.NewInformer()`. Following code does not stop the running controller:

```
stopCh := make(chan struct{})
go ctrl.Run(stopCh)

time.Sleep(time.Minute)
close(stopCh)
```

The controller is stuck in `k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).Pop()` call, where the channel is ignored. This clutters all stack dumps when unit tests are running in sequence (`go test -count 10000`) and make race detection crash ("limit on 8192 simultaneously alive goroutines is exceeded, dying").

Full stack trace of the waiting goroutine:

```
#   0x43511     sync.runtime_Syncsemacquire+0x201                                               /usr/local/Cellar/go/1.6.2/libexec/src/runtime/sema.go:241
#   0x138b53    sync.(*Cond).Wait+0xb3                                                      /usr/local/Cellar/go/1.6.2/libexec/src/sync/cond.go:63
#   0x3b91a7    k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).Pop+0xe7                                    /Users/mhb/src/gocode/src/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:399
#   0x3d0eb9    k8s.io/kubernetes/pkg/controller/framework.(*Controller).processLoop+0x79                           /Users/mhb/src/gocode/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:127
#   0x3d47de    k8s.io/kubernetes/pkg/controller/framework.(*Controller).(k8s.io/kubernetes/pkg/controller/framework.processLoop)-fm+0x2e   /Users/mhb/src/gocode/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:103
#   0x929339    k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1+0x59                                      /Users/mhb/src/gocode/src/k8s.io/kubernetes/pkg/util/wait/wait.go:86
#   0x9290ea    k8s.io/kubernetes/pkg/util/wait.JitterUntil+0xca                                        /Users/mhb/src/gocode/src/k8s.io/kubernetes/pkg/util/wait/wait.go:87
#   0x929001    k8s.io/kubernetes/pkg/util/wait.Until+0x51                                          /Users/mhb/src/gocode/src/k8s.io/kubernetes/pkg/util/wait/wait.go:49
#   0x3d0b8e    k8s.io/kubernetes/pkg/controller/framework.(*Controller).Run+0x25e                              /Users/mhb/src/gocode/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:103
```

### PR DESCRIPTION
**Pull request by ingvagabund**
Fixes: #28158

When a ``Pop`` function is invoked over empty queue, the control loop inside the functions is stacked indefinitely. In order to break the loop, introduce logic that waits for a signal to exit the loop.

Intention of the PR is not to handle situation where manipulation operations are invoked over closed queue. Intention is to break the indefinite loop.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/37137)

### CODE REVIEW

**Comment by ingvagabund** [comment]
@fraenkel @deads2k WDYT? Just checked the solution in my cluster capacity framework. No more hanging go routines. Need to check the remaining pieces of kubernetes how are they doing with the change before the PR is finished.

File: pkg/client/cache/delta_fifo.go [hunk 1]
```diff
@@ -132,6 +135,12 @@ var (
 	ErrZeroLengthDeltasObject = errors.New("0 length Deltas object; can't get key")
 )
 
+// Close the queue.
+func (f *DeltaFIFO) Close() {
+	f.closed = true
```
Comment (fraenkel) [inline pkg/client/cache/delta_fifo.go]: You are missing a lock here, otherwise there is no guarantee closed is published.

Comment (ingvagabund) [inline pkg/client/cache/delta_fifo.go]: Even if there is only one writer and the writer writes only once? In a sense, the ``f.closed`` is false until the ``Close()`` is called. Then it is true forever. The reader can read the ``f.closed`` set to false, then different goroutine calls ``Close()`` which sets the ``f.closed`` to true. Then the reader continues with the false even when it is true now. How does it differ from locking the variable? The critical section is reading the ``f.closed``. Once it is read it does not matter if it is changed right after the reading.

**Comment by ingvagabund** [comment]
@k8s-bot unit test this

File: pkg/client/cache/delta_fifo.go (hunk 1 above)
Comment (fraenkel) [inline pkg/client/cache/delta_fifo.go]: In your use case, the value is only ever written once which isn't the problem. The reader may never see true. Any number of goroutines can call Close(), but there is still no guarantee the true value is ever published. For a further explanation, see https://golang.org/ref/mem
The nice thing about Go is that they kept the model simple. If you want to publish a value between goroutines, use a channel or synchronization.

Comment (ingvagabund) [inline pkg/client/cache/delta_fifo.go]: Ahh, another good thing to know. Thanks for the explanation.

File: pkg/client/cache/delta_fifo.go [hunk 2]
```diff
@@ -404,6 +416,16 @@ func (f *DeltaFIFO) Pop(process PopProcessFunc) (interface{}, error) {
 	defer f.lock.Unlock()
 	for {
 		for len(f.queue) == 0 {
+			// When the queue is empty, invocation of Pop() is blocked until new item is enqueued.
```
Comment (deads2k) [inline pkg/client/cache/delta_fifo.go]: nicely structured.  this looks safe to me.

File: pkg/client/cache/fifo.go [hunk 3]
```diff
@@ -106,6 +112,10 @@ var (
 	_ = Queue(&FIFO{}) // FIFO is a Queue
 )
 
+func (f *FIFO) Close() {
```
Comment (deads2k) [inline pkg/client/cache/fifo.go]: Why isn't this performing a close action very similar to the delta fifo?

File: pkg/client/cache/delta_fifo.go [hunk 4]
```diff
@@ -118,6 +118,10 @@ type DeltaFIFO struct {
 	// purpose of figuring out which items have been deleted
 	// when Replace() or Delete() is called.
 	knownObjects KeyListerGetter
+
+	// indication the queue is closed
+	closed bool
```
Comment (deads2k) [inline pkg/client/cache/delta_fifo.go]: Can you add comments about why this isn't used to gate adds?  I'm assuming its because you don't consider it worth the lock acquisition, but I think its worth an explicit comment.

File: pkg/client/cache/controller.go [hunk 5]
```diff
@@ -86,6 +86,10 @@ func New(c *Config) *Controller {
 // Run blocks; call via go.
 func (c *Controller) Run(stopCh <-chan struct{}) {
 	defer utilruntime.HandleCrash()
+	go func() {
```
Comment (sttts) [inline pkg/client/cache/controller.go]: why no simple `defer c.config.Queue.Close()`?

File: pkg/client/cache/delta_fifo.go [hunk 6]
```diff
@@ -118,6 +118,10 @@ type DeltaFIFO struct {
...
+	closedLock sync.RWMutex
```
Comment (sttts) [inline pkg/client/cache/delta_fifo.go]: The RW part of the mutix is not used, is it?

File: pkg/client/cache/delta_fifo.go (hunk 2 above)
Comment (sttts) [inline pkg/client/cache/delta_fifo.go]: This means that we see all the queue data before the close actually has any effect? Moreover, as long as we feed the queue with new data, we will never see the close.

We need test cases for this.

Comment (sttts) [inline pkg/client/cache/delta_fifo.go]: To make it clear: seeing existing data in the queue before the close is fine. But being able to keep the queue full and ignoring the close is probably not fine.

Comment (sttts) [inline pkg/client/cache/delta_fifo.go]: As an alternative (maybe simpler than the `closed` field): put a tombstone into the queue.

Comment (lavalamp) [inline pkg/client/cache/delta_fifo.go]: IMO, closing a fifo means we stop putting items in the queue, we wait for the queue to be drained completely, and all goroutines to exit, and then we have finished stopping. Please don't shut down with items still in the queue, that will make it hard to deterministically test.

Comment (lavalamp) [inline pkg/client/cache/delta_fifo.go]: oh, I see, this only runs when the queue is empty. Hm.

File: pkg/client/cache/delta_fifo.go [hunk 7]
```diff
@@ -132,6 +136,14 @@ var (
 	ErrZeroLengthDeltasObject = errors.New("0 length Deltas object; can't get key")
 )
 
+// Close the queue.
+func (f *DeltaFIFO) Close() {
+	f.closedLock.Lock()
+	defer f.closedLock.Unlock()
+	f.closed = true
+	f.cond.Broadcast()
```
Comment (lavalamp) [inline pkg/client/cache/delta_fifo.go]: block until everything has exited. (or provide a way to do that.)

File: pkg/client/cache/delta_fifo.go (hunk 6 above)
Comment (lavalamp) [inline pkg/client/cache/delta_fifo.go]: I don't see why you need an additional lock.

File: pkg/client/cache/fifo.go [hunk 8]
```diff
@@ -33,6 +34,8 @@ type ErrRequeue struct {
 	Err error
 }
 
+var FIFOClosedError error = errors.New("DeltaFIFO: reading from closed queue")
```
Comment (lavalamp) [inline pkg/client/cache/fifo.go]: More general than delta fifo, ideally all the queues would support this.

File: pkg/client/cache/fifo.go (hunk 3 above)
Comment (lavalamp) [inline pkg/client/cache/fifo.go]: yes, please actually implement :)

File: pkg/client/cache/controller.go (hunk 5 above)
Comment (lavalamp) [inline pkg/client/cache/controller.go]: This is a `go` not a `defer` :)

File: pkg/client/cache/delta_fifo.go (hunk 4 above)
Comment (lavalamp) [inline pkg/client/cache/delta_fifo.go]: Yeah, this should gate adds, updates, deletes, and replaces.

File: pkg/client/cache/controller.go (hunk 5 above)
Comment (ingvagabund) [inline pkg/client/cache/controller.go]: With defer, the function would never got invoked. Here it is important to reach the ``<-stopCh`` and wait.

File: pkg/client/cache/delta_fifo.go (hunk 2 above)
Comment (ingvagabund) [inline pkg/client/cache/delta_fifo.go]: The entire PR is about getting out of the control loop when the queue is empty. It does not cover situations where the queue is not empty. I am leaving the non-empty queue case with all tests to be covered in different PR.

File: pkg/client/cache/fifo.go (hunk 3 above)
Comment (ingvagabund) [inline pkg/client/cache/fifo.go]: I did not consider this fifo to be important. But the implementation here is analogical. I'll clone it.

File: pkg/client/cache/fifo.go (hunk 8 above)
Comment (ingvagabund) [inline pkg/client/cache/fifo.go]: Not against that. Though, leaving it for another PR.

**Comment by ingvagabund** [comment]
Anyway, this PR is no longer valid as the fifo code has been moved to client-go.

**Comment by ingvagabund** [comment]
> Anyway, this PR is no longer valid as the fifo code has been moved to client-go.

I see, it is still under https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go

File: pkg/client/cache/delta_fifo.go (hunk 6 above)
Comment (ingvagabund) [inline pkg/client/cache/delta_fifo.go]: It is not, ``sync.Mutex`` is enough.

File: pkg/client/cache/delta_fifo.go (hunk 7 above)
Comment (ingvagabund) [inline pkg/client/cache/delta_fifo.go]: Not in scope of this PR.

File: pkg/client/cache/delta_fifo.go (hunk 6 above)
Comment (ingvagabund) [inline pkg/client/cache/delta_fifo.go]: Done

File: pkg/client/cache/delta_fifo.go (hunk 4 above)
Comment (ingvagabund) [inline pkg/client/cache/delta_fifo.go]: explicit commend added

File: pkg/client/cache/fifo.go (hunk 3 above)
Comment (ingvagabund) [inline pkg/client/cache/fifo.go]: Implemented as well

**Comment by ingvagabund** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by ingvagabund** [comment]
@deads2k @sttts @lavalamp @fraenkel PTAL

File: staging/src/k8s.io/client-go/tools/cache/delta_fifo.go [hunk 9]
```diff
@@ -404,6 +418,16 @@ func (f *DeltaFIFO) Pop(process PopProcessFunc) (interface{}, error) {
 	defer f.lock.Unlock()
 	for {
 		for len(f.queue) == 0 {
+			// When the queue is empty, invocation of Pop() is blocked until new item is enqueued.
+			// When Close() is called, the f.closed is set and the condition is broadcasted.
+			// Which causes this loop to continue and return from the Pop().
+			f.closedLock.Lock()
```
Comment (deads2k) [inline staging/src/k8s.io/client-go/tools/cache/delta_fifo.go]: nit: could this be pulled into a method for `IsClosed` so I don't have to pair locks when I'm reading this?

**Comment by deads2k** [comment]
Maybe I'm missing a detail of the implementation, but I don't see something that prevents adding to a closed FIFO.  That seems like a thing we'd want.

**Comment by deads2k** [comment]
lgtm otherwise

File: staging/src/k8s.io/client-go/tools/cache/delta_fifo.go (hunk 9 above)
Comment (ingvagabund) [inline staging/src/k8s.io/client-go/tools/cache/delta_fifo.go]: Done

**Comment by ingvagabund** [comment]
> Maybe I'm missing a detail of the implementation, but I don't see something that prevents adding to a closed FIFO. That seems like a thing we'd want.

This make sense for delete, replace and other operations as well. That is definitely something we need. Which will need a bunch of tests. Given this PR is mainly to escape from the stacked loop in `Pop` function, I have intentionally ignore that.

**Comment by fraenkel** [comment]
I would also be curious to see how much code may break once we return errors when closed. While it should be done, it is a change in behavior which may have fallout elsewhere.

**Comment by ingvagabund** [comment]
@k8s-bot gci gce e2e test this

**Comment by derekwaynecarr** [comment]
@deads2k @lavalamp -- any more comments on this?
