### PR TITLE
[Flaking test] [InPlacePodVerticalScaling] Fix Pod Resize deferred tests

### LINKED ISSUE #134458: [Flaking test] [InPlacePodVerticalScaling] Pod Resize deferred tests are flaking
https://storage.googleapis.com/k8s-triage/index.html?test=pod-resize-retry-deferred

Looks like they've been flaking for a while. I think its most likely an issue with the way the test is written than an issue with the feature.

### PR DESCRIPTION
**Pull request by Karthik-K-N**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:

This PR tries to fix the flake for tests verifying the Differed state in InPlacePodVerticalScaling feature.

Test output
```
STEP: Creating a kubernetes client @ 10/29/25 16:35:07.97
  I1029 16:35:07.970529 917444 util.go:414] >>> kubeConfig: /root/kubernetes/kind.conf
  STEP: Building a namespace api object, basename pod-resize-deferred-resize-tests @ 10/29/25 16:35:07.971
  STEP: Waiting for a default service account to be provisioned in namespace @ 10/29/25 16:35:07.979
  STEP: Waiting for kube-root-ca.crt to be provisioned in namespace @ 10/29/25 16:35:07.982
  I1029 16:35:07.987725 917444 pod_resize.go:701] Found 1 schedulable nodes
  STEP: Find node CPU resources available for allocation! @ 10/29/25 16:35:07.987
  I1029 16:35:07.990482 917444 pod_resize.go:1265] Found 9 pods on node 'kind-control-plane'
  I1029 16:35:07.990542 917444 pod_resize.go:706] Node 'kind-control-plane': NodeAllocatable MilliCPUs = 16000m. MilliCPUs currently available to allocate = 15050m.
  I1029 16:35:07.990555 917444 pod_resize.go:712] testPod1 initial CPU request is '7525m'
  I1029 16:35:07.990562 917444 pod_resize.go:713] testPod2 initial CPU request is '3762m'
  I1029 16:35:07.990567 917444 pod_resize.go:714] testPod3 initial CPU request is '940m'
  STEP: Create pod 'testpod1' that fits the node 'kind-control-plane' @ 10/29/25 16:35:07.99
  STEP: Create pod 'testpod2' that fits the node 'kind-control-plane' @ 10/29/25 16:35:10.004
  STEP: Create pod 'testpod3' that fits the node 'kind-control-plane' @ 10/29/25 16:35:12.015
  I1029 16:35:14.030184 917444 pod_resize.go:1265] Found 12 pods on node 'kind-control-plane'
  I1029 16:35:14.030248 917444 pod_resize.go:761] Node 'kind-control-plane': NodeAllocatable MilliCPUs = 16000m. MilliCPUs currently available to allocate = 2823m.
  I1029 16:35:14.030262 917444 pod_resize.go:767] testPod3 MilliCPUs after resize '8466m'
  I1029 16:35:14.030271 917444 pod_resize.go:771] testPod1 MilliCPUs after resize '1881m'
  STEP: Resize pod 'testpod3' that cannot fit node due to insufficient CPU @ 10/29/25 16:35:14.03
  STEP: Resize pod 'testpod1' to make enough space for pod 'testpod3' @ 10/29/25 16:35:16.043
  STEP: Verify pod 'testpod3' is resized successfully after pod resize 'testpod1' @ 10/29/25 16:35:16.049
```

#### Which issue(s) this PR is related to:
Fixes https://github.com/kubernetes/kubernetes/issues/134458

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Karthik-K-N** [comment]
@natasha41575 when time permits please take a look if this right approach. Thanks.

File: test/e2e/node/pod_resize.go [hunk 1]
```diff
@@ -743,24 +755,26 @@ func doPodResizeRetryDeferredTests(f *framework.Framework) {
...
 		framework.ExpectNoError(err, "failed to get CPU resources available for allocation")
+
 		framework.Logf("Node '%s': NodeAllocatable MilliCPUs = %dm. MilliCPUs currently available to allocate = %dm.",
 			node.Name, nodeAllocatableCPU2.MilliValue(), nodeAvailableCPU2.MilliValue())
 
-		testPod3CPUQuantity := resource.NewMilliQuantity(nodeAvailableCPU2.MilliValue()/4, resource.DecimalSI)
-		testPod3CPUQuantityResized := resource.NewMilliQuantity(nodeAvailableCPU2.MilliValue()+testPod1CPUQuantity.MilliValue()/4, resource.DecimalSI)
+		// Considering only these 3 pods consumed the resources, the nodeAvailableMilliCPU2 will be 18.75% (50%(testpod1)+25%(testpod2)+6.25%(testpod3))
+		// Resize the testpod3 to add current available resource + 75% of testpod1 resource, i.e 18.75% + 37.5%
+		testPod3CPUQuantityResized := resource.NewMilliQuantity(nodeAllocatableCPU2.MilliValue()+testPod1CPUQuantity.MilliValue()*3/4, resource.DecimalSI)
```
Comment (ajaysundark) [inline test/e2e/node/pod_resize.go]: this seem to misalign with the comment above? wouldn't allocatable + offset  cause the resize to be rejected as infeasible instead?

Comment (Karthik-K-N) [reply test/e2e/node/pod_resize.go]: If I understand correctly, we hit infeasible only when the request is greater than the total node allocatable.

Here for example

Total node available CPU: 100%
1. Pod 1: 50% of node available CPU
2. Pod 2: 25% of node available CPU
3. Pod 3: 6.25% of available CPU

Current available CPU : 18.75%

Resize Pod 3 which already has 6.25% of available CPU to include current available CPU (18.75%) + 75% of Pod 1 (75% of 50 = 37.5%)
So total Pod 3 requirement is 18.75% + 37.5% = 56.25%

Pod 3 requirement: 56.25%
Current available: 18.75%
Pod 3 already have: 6.25%

Required for Pod 3 to be running 31.25% hence its moves in to deffered state.

Resize Pod 1 to 1/4th from initial value.
Initial value 50% CPU
After 1/4th resize, Pod 1 need: 12.5%, Given back to node allocatable: 37.5%

This makes the Pod 3 from deffered state to Running.

Please let me know if I misunderstood anything.

Comment (ajaysundark) [reply test/e2e/node/pod_resize.go]: IMO, eliminating the confusing percentage structure of this test will make it more readable while also avoid floating point issues.

The goal of the test is simple: pod should be deferred, then after resize should fit the deferred pod again.

why not refine this as a cleaner 2-Pod test? split the nodeAvailable into 10parts.
1. Pod A: 6 parts
2. Pod B: 3 parts
Now Free: < 1 parts
3. Resize Pod B to 6 parts (wont fit, defer)
4. Resize Pod A to 2 parts (free up the 3 needed to fit the earlier deferred).
5. Verify before resizing to match expectations

This feels simpler to test the exact same test case. wdyt?

Comment (Karthik-K-N) [reply test/e2e/node/pod_resize.go]: Agree, I tried to refactor the existing test to fix the flake.
I have now updated the logic use only 2 pods and resize them according to the test expectations.
Please take a look when time permits. Thanks.

**Comment by Karthik-K-N** [comment]
Checking again with this test , if it fails or not yet fixed will debug this

/test pull-kubernetes-e2e-gce-serial

**Review by natasha41575 — COMMENTED** [review]
Thanks for the PR. 

I am a little confused about how is this change deflaking the test? It seems like the same test but just with a slightly different method of calculating CPU that each pod gets? Do you mind explaining a little more your analysis of the flake and how does this help?

**Comment by Karthik-K-N** [comment]
> Thanks for the PR.
> 
> I am a little confused about how is this change deflaking the test? It seems like the same test but just with a slightly different method of calculating CPU that each pod gets? Do you mind explaining a little more your analysis of the flake and how does this help?

Sure, Here is the debug info I have updated

https://github.com/kubernetes/kubernetes/issues/134458#issuecomment-3457597061

To summerize, Previously we used 3 pods and the available capacity was captured at the beginiing, During the Pod 3 creation some other tests pods used to be get cleaned up and provide the necessary resources to run Pod 3 where as we were expecting it be in deffered state.
With this change we are going with 2 pods and make sure it goes to deffered state.

**Comment by Karthik-K-N** [comment]
> @Karthik-K-N can you please either help fix the pull-kubernetes-e2e-gce-serial or figure out any other test lane that would run this test you fixed?

Hi @natasha41575 @SergeyKanzhelev there was an attempt to fix pull-kubernetes-e2e-gce-serial via [PR](https://github.com/kubernetes/kubernetes/pull/137822) but that was not successful, now we have similar test via pull-kubernetes-e2e-gce-cos-serial. I have run that and its passing. Please take a look when time permits, Thanks

**Review by natasha41575 — COMMENTED** [review]
I am so sorry that it took me so long to review this. I finally set aside some time today to take a look at it thoroughly.

- The code is clean and readable
- Simplifying from 3 pods down to 2 may indeed reduce the flakiness
- The conceptual model of dividing the node allocatable into 'parts' is easier to understand
- I ran this locally a few times, double checked all the log statements; they look good and it is passing on my kind cluster.

If any other deferred resize tests could benefit from similar updates, feel free to open a PR.
Thanks @ajaysundark for the initial reviews.

/lgtm

/assign @SergeyKanzhelev @tallclair 
for approval

**Comment by Karthik-K-N** [comment]
> I am so sorry that it took me so long to review this. I finally set aside some time today to take a look at it thoroughly.
> 
>     * The code is clean and readable
> 
>     * Simplifying from 3 pods down to 2 may indeed reduce the flakiness
> 
>     * The conceptual model of dividing the node allocatable into 'parts' is easier to understand
> 
>     * I ran this locally a few times, double checked all the log statements; they look good and it is passing on my kind cluster.
> 
> 
> If any other other deferred resize tests could benefit from similar updates, feel free to open a PR. Thanks @ajaysundark for the initial reviews.
> 
> /lgtm
> 
> /assign @SergeyKanzhelev @tallclair for approval

No Problem, Thanks for the review. Please let me know if there are any more issues I can help with.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve
