### PR TITLE
Discovery client retry when failed to discovery resrouces

### LINKED ISSUE #32308: Discovery client behaves poorly when TPR is unregistered
Split off from #32306, the thing that actually caused the flakes throughout the system (as opposed to just failing the TPR test) is 

```
&discovery.ErrGroupDiscoveryFailed{Groups:map[unversioned.GroupVersion]error{unversioned.GroupVersion{Group:"company.com", Version:"v1"}:(*errors.StatusError)(0xc82084c480)}}
```

(https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/32278/kubernetes-pull-build-test-e2e-gce/57833/)

Which I guess means that the discovery client got a list, but then the TPR was gone when it tried to get details?

This is not an emergency since we've marked the test flaky, but we should fix it.

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #32308

`ServerPreferredNamespacedResources()` fails if in the middle of its execution, the TPR e2e tests change the supported resources on the API server. This PR let the e2e test framework retry `ServerPreferredNamespacedResources()`.

cc @lavalamp

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33234)

### CODE REVIEW

**Comment by lavalamp** [comment]
Are you sure the test is the right place to fix this? Shouldn't it be fixed in the discovery client?

**Comment by caesarxuchao** [comment]
The discovery client returns the partial result with the errors recording which API groups fail. Caller can decide whether to retry the call, ignore the error, or return the error. The discovery client doesn't have the context.

**Comment by lavalamp** [comment]
This is a synchronization problem between the client and server. It doesn't make sense to force clients to do a retry loop. Basically there's no excuse for this call to ever fail IMO, short of things like the network is broken or the server goes down half way through.

I think if the discovery client fails to get group info, it should retry getting the list of groups. At least once.

Ideally we'd include a logical clock in both sources of discovery information so the client can at least tell if it is getting skewed data.

**Comment by derekwaynecarr** [comment]
Agree with @lavalamp

Also for TPR test scenarios, we need to also support the ability to vet
that the TPR type def even if deleted had its individual instances cleaned
up.  I think current flow for those tests would result in discovery not
returning the newly deleted TPR type, but we would not be able to verify
its instances were cleaned up?

**Comment by lavalamp** [comment]
I thought the TPR controller deleted everything when it removed the type
from the system? Maybe we should test that, but there shouldn't need to be
a test at the namespace controller level.

**Comment by caesarxuchao** [comment]
Updated to retry in the discovery client. PTAL. Thanks.

**Comment by caesarxuchao** [comment]
@lavalamp @derekwaynecarr mind taking another look? Thanks.

File: pkg/client/typed/discovery/discovery_client.go [hunk 1]
```diff
@@ -199,39 +199,42 @@ func IsGroupDiscoveryFailedError(err error) bool {
...
-		for _, apiResource := range apiResourceList.APIResources {
-			// ignore the root scoped resources if "namespaced" is true.
-			if namespaced && !apiResource.Namespaced {
+
+		for _, apiGroup := range serverGroupList.Groups {
+			preferredVersion := apiGroup.PreferredVersion
+			groupVersion := unversioned.GroupVersion{Group: apiGroup.Name, Version: preferredVersion.Version}
+			apiResourceList, err := d.ServerResourcesForGroupVersion(preferredVersion.GroupVersion)
+			if err != nil {
+				failedGroups[groupVersion] = err
```
Comment (lavalamp) [inline pkg/client/typed/discovery/discovery_client.go]: maybe try again from the top if this isn't the last try?

**Comment by lavalamp** [comment]
minor nits, otherwise lgtm

**Comment by caesarxuchao** [comment]
@lavalamp nits addressed. Also added one more test case. PTAL. Thanks.

**Comment by lavalamp** [comment]
LGTM
