### PR TITLE
Fix test "Pods should run through the lifecycle of Pods and PodStatus"

### LINKED ISSUE #99437: [Flake][sig-node] Pods should run through the lifecycle of Pods and PodStatus
#### Which jobs are flaking:
- ci-kubernetes-kind-e2e-parallel
- ci-kubernetes-e2enode-ubuntu2-k8sstable1-gkespec

#### Which test(s) are flaking:
Pods should run through the lifecycle of Pods and PodStatus

#### Testgrid link:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99345/pull-kubernetes-e2e-kind/1364771671973564416

#### Anything else we need to know:
- Triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=failed%20to%20see%20Pod%20pod-test%20in%20namespace&test=Pods%20should%20run%20through%20the%20lifecycle%20of%20Pods%20and%20PodStatus

/sig node

### PR DESCRIPTION
**Pull request by matthyx**
#### What type of PR is this?
/kind failing-test
/priority important-soon

#### What this PR does / why we need it:
Fix for flake "Pods should run through the lifecycle of Pods and PodStatus"

#### Which issue(s) this PR fixes:

Fixes #99437

#### Special notes for your reviewer:
There are 2 kind of errors:
* pods remain in `Pending` state on node-kubelet-orphans job, impossible to reproduce locally
  * add pod debug log on error to understand why
* sometimes pod status cannot be updated because of race condition
  * add `retry.RetryOnConflict` to the update like in other tests

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
/lgtm

ci-kubernetes-node-kubelet-orphans is not easy to test. It will be triggered every 12 hours.
https://github.com/kubernetes/test-infra/blob/a3ea3bc72638e8391429eafb7eb3ff3d63c035d5/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L174-L175

**Review by derekwaynecarr — APPROVED** [review]
/lgtm
/approve

**Comment by BenTheElder** [comment]
this is eligible for test-freeze IMO, but milestone-ing

File: test/e2e/common/node/pods.go [hunk 1]
```diff
@@ -22,6 +22,7 @@ import (
 	"encoding/json"
 	"fmt"
 	"io"
+	"k8s.io/client-go/util/retry"
```
Comment (BenTheElder) [inline test/e2e/common/node/pods.go:25]: nit: import grouping is wrong, this should be in the last group below

Comment (matthyx) [reply test/e2e/common/node/pods.go:25]: weird, this is how Goland added it...
