### PR TITLE
Fixed bug in TopologyManager with SingleNUMANode Policy

### LINKED ISSUE #83695: topology manager not behaving as expected in 1.16
**What happened**:
I think I'm seeing a problem with the topology manager.  I have two numa nodes, 22 cores per node.  Kubelet has "--cpu-manager-policy=static --topology-manager-policy=single-numa-node ", and when I try to create a simple pod with 3 cpus and 500Mi of RAM in the guaranteed class it fails.  Describing the pod gives "Resources cannot be allocated with Topology Locality", but I know there's lots of CPU and RAM available on both NUMA nodes.  I'm instrumenting the topology manager kubelet code, currently there's not enough debug logs to actually be able to tell what's going wrong.

**What you expected to happen**:
I expect the pod container to be created on one or the other numa node and get allocated exclusive CPUs (via the static policy) on that NUMA node, and be affined to those CPUs.

**How to reproduce it (as minimally and precisely as possible)**:
On a kubernetes node with multiple NUMA nodes, enable kubelet with static cpu manager policy and single-numa-node topology manager policy.  Try to create a basic pod with a single container in the guaranteed QoS class.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
sysadmin@controller-0 chris(keystone_admin)]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"archive", BuildDate:"2019-10-09T05:41:44Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
wildcat pass hardware, 22 cores per NUMA node, two NUMA nodes.  64GB RAM per NUMA node.

- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`): 3.10.0-957.21.3.el7.2.tis.x86_64

### PR DESCRIPTION
**Pull request by klueska**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This patch fixes an issue in the TopologyManager that wouldn't allow
pods to be admitted if pods were launched with the SingleNUMANode policy
and any of the hint providers had no NUMA preferences.

This is due to 2 factors:

1) Any hint provider that passes back a `nil` as its hints, has its hint
automatically transformed into a single {11 true} hint before merging

2) We added a special casing for the SingleNumaNodePolicy() in the
TopologyManager that essentially turns these hints into a
{11 false} anytime a {11 true} is seen.

The current patch reworks this logic so the that TopologyManager can
tell the difference between a "don't care" hint and a true "{11 true}"
hint returned by the hint provider. Only true "{11 true}" hints will be
converted by the special casing for the SingleNumaNodePolicy(), while
"don't care" hints will not.

This is a short term fix for this issue until we do a larger refactoring
of this code for the 1.17 release.

**Which issue(s) this PR fixes**:
Fixes #83695

**Does this PR introduce a user-facing change?**:

```release-note
Fixed a bug in the single-numa-node policy of the TopologyManager.  Previously, pods that only requested CPU resources and did not request any third-party devices would fail to launch with a TopologyAffinity error. Now they will launch successfully.
```

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
looks like the gofmt error is legit.

File: pkg/kubelet/cm/topologymanager/topology_manager_test.go [hunk 1]
```diff
@@ -196,7 +196,7 @@ func TestCalculateAffinity(t *testing.T) {
 			},
 			expected: TopologyHint{
 				NUMANodeAffinity: NewTestBitMask(numaNodes...),
-				Preferred:        true,
+				Preferred:        false,
```
Comment (klueska) [inline pkg/kubelet/cm/topologymanager/topology_manager_test.go]: These are actually the semantics we wanted all along.

**Comment by lmdaly** [comment]
After discussion with Kevin, we may have to revisit the the default hint stored in the future, but for now this fix is perfectly sufficient

**Comment by derekwaynecarr** [comment]
Thanks!

Please open a cherry-pick for 1.16 and ping me when ready.
