### PR TITLE
[flaky test] fix devicemanager TestDevicePluginReRegistrationProbeMode failed

### LINKED ISSUE #96908: [Flaky Test] //pkg/kubelet/cm/devicemanager/go_default_test:run_2_of_2
**Which jobs are flaking**:
bazel-test-master

**Which test(s) are flaking**:
//pkg/kubelet/cm/devicemanager/go_default_test:run_2_of_2

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#bazel-test-master

**Reason for failure**:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //pkg/kubelet/cm/devicemanager:go_default_test
-----------------------------------------------------------------------------
I1127 05:25:45.047731  215379 device_plugin_stub.go:142] Starting to serve on /tmp/mock1606454745037022410.sock
I1127 05:25:45.057478  215379 device_plugin_stub.go:142] Starting to serve on /tmp/mock1606454745054717131.sock
I1127 05:25:45.067977  215379 device_plugin_stub.go:238] ListAndWatch
E1127 05:25:45.070649  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin mock with error rpc error: code = Unavailable desc = transport is closing
I1127 05:25:45.079328  215379 device_plugin_stub.go:142] Starting to serve on /tmp/mock1606454745070838053.sock
I1127 05:25:45.087164  215379 device_plugin_stub.go:238] ListAndWatch
I1127 05:25:45.088887  215379 device_plugin_stub.go:272] Allocate, &AllocateRequest{ContainerRequests:[]*ContainerAllocateRequest{&ContainerAllocateRequest{DevicesIDs:[ADeviceId],},},}
E1127 05:25:45.092947  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin mock with error rpc error: code = Unavailable desc = transport is closing
I1127 05:25:45.096696  215379 device_plugin_stub.go:142] Starting to serve on /tmp/mock1606454745093025638.sock
I1127 05:25:45.130907  215379 device_plugin_stub.go:238] ListAndWatch
I1127 05:25:45.132196  215379 device_plugin_stub.go:259] GetPreferredAllocation, &PreferredAllocationRequest{ContainerRequests:[]*ContainerPreferredAllocationRequest{&ContainerPreferredAllocationRequest{AvailableDeviceIDs:[],MustIncludeDeviceIDs:[],AllocationSize:-1,},},}
E1127 05:25:45.135911  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin mock with error rpc error: code = Unavailable desc = transport is closing
I1127 05:25:45.136291  215379 fake_topology_manager.go:30] [fake topologymanager] NewFakeManager
I1127 05:25:45.136808  215379 fake_topology_manager.go:30] [fake topologymanager] NewFakeManager
W1127 05:25:45.137220  215379 manager.go:594] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
I1127 05:25:45.140778  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin095277315/device-plugin.sock
I1127 05:25:45.143199  215379 fake_topology_manager.go:30] [fake topologymanager] NewFakeManager
W1127 05:25:45.143567  215379 manager.go:594] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
I1127 05:25:45.144854  215379 plugin_manager.go:114] Starting Kubelet Plugin Manager
I1127 05:25:45.150082  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin819249798/device-plugin.sock
I1127 05:25:45.151700  215379 fake_topology_manager.go:30] [fake topologymanager] NewFakeManager
W1127 05:25:45.151921  215379 manager.go:594] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
I1127 05:25:45.156950  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin077505581/device-plugin.sock
I1127 05:25:45.157052  215379 device_plugin_stub.go:191] Deprecation file not found. Invoke registration
I1127 05:25:45.164156  215379 manager.go:408] Got registration request from device plugin with resource name "fake-domain/resource"
I1127 05:25:45.169437  215379 device_plugin_stub.go:238] ListAndWatch
I1127 05:25:45.186903  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin077505581/device-plugin.sock.new
I1127 05:25:45.186998  215379 device_plugin_stub.go:191] Deprecation file not found. Invoke registration
I1127 05:25:45.189419  215379 manager.go:408] Got registration request from device plugin with resource name "fake-domain/resource"
I1127 05:25:45.196192  215379 device_plugin_stub.go:238] ListAndWatch
I1127 05:25:45.207455  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin077505581/device-plugin.sock.third
I1127 05:25:45.207551  215379 device_plugin_stub.go:191] Deprecation file not found. Invoke registration
I1127 05:25:45.216424  215379 manager.go:408] Got registration request from device plugin with resource name "fake-domain/resource"
I1127 05:25:45.220033  215379 device_plugin_stub.go:238] ListAndWatch
E1127 05:25:45.228630  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Unavailable desc = transport is closing
E1127 05:25:45.228776  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Unavailable desc = transport is closing
I1127 05:25:45.228864  215379 fake_topology_manager.go:30] [fake topologymanager] NewFakeManager
E1127 05:25:45.229176  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Unavailable desc = transport is closing
I1127 05:25:45.234940  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin077505581/device-plugin.sock
I1127 05:25:45.235032  215379 device_plugin_stub.go:191] Deprecation file not found. Invoke registration
I1127 05:25:45.237502  215379 manager.go:408] Got registration request from device plugin with resource name "fake-domain/resource"
I1127 05:25:45.243370  215379 device_plugin_stub.go:238] ListAndWatch
I1127 05:25:45.252818  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin077505581/device-plugin.sock.new
I1127 05:25:45.252915  215379 device_plugin_stub.go:191] Deprecation file not found. Invoke registration
I1127 05:25:45.256615  215379 manager.go:408] Got registration request from device plugin with resource name "fake-domain/resource"
I1127 05:25:45.265191  215379 device_plugin_stub.go:238] ListAndWatch
I1127 05:25:45.273465  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin077505581/device-plugin.sock.third
I1127 05:25:45.273555  215379 device_plugin_stub.go:191] Deprecation file not found. Invoke registration
I1127 05:25:45.276665  215379 manager.go:408] Got registration request from device plugin with resource name "fake-domain/resource"
I1127 05:25:45.281857  215379 device_plugin_stub.go:238] ListAndWatch
E1127 05:25:45.287747  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Unavailable desc = transport is closing
E1127 05:25:45.287867  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Unavailable desc = transport is closing
E1127 05:25:45.289423  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Unavailable desc = transport is closing
I1127 05:25:45.290027  215379 fake_topology_manager.go:30] [fake topologymanager] NewFakeManager
I1127 05:25:45.293746  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin077505581/device-plugin.sock
I1127 05:25:45.293846  215379 device_plugin_stub.go:191] Deprecation file not found. Invoke registration
I1127 05:25:45.297271  215379 manager.go:408] Got registration request from device plugin with resource name "fake-domain/resource"
I1127 05:25:45.304811  215379 device_plugin_stub.go:238] ListAndWatch
I1127 05:25:45.321498  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin077505581/device-plugin.sock.new
I1127 05:25:45.321610  215379 device_plugin_stub.go:191] Deprecation file not found. Invoke registration
I1127 05:25:45.326368  215379 manager.go:408] Got registration request from device plugin with resource name "fake-domain/resource"
I1127 05:25:45.334582  215379 device_plugin_stub.go:238] ListAndWatch
I1127 05:25:45.345882  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin077505581/device-plugin.sock.third
I1127 05:25:45.345977  215379 device_plugin_stub.go:191] Deprecation file not found. Invoke registration
I1127 05:25:45.351284  215379 manager.go:408] Got registration request from device plugin with resource name "fake-domain/resource"
I1127 05:25:45.358952  215379 device_plugin_stub.go:238] ListAndWatch
E1127 05:25:45.368886  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Unavailable desc = transport is closing
E1127 05:25:45.369295  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Unavailable desc = transport is closing
I1127 05:25:45.370467  215379 fake_topology_manager.go:30] [fake topologymanager] NewFakeManager
E1127 05:25:45.370766  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Unavailable desc = transport is closing
I1127 05:25:45.375061  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin077505581/device-plugin.sock
I1127 05:25:45.375146  215379 device_plugin_stub.go:191] Deprecation file not found. Invoke registration
I1127 05:25:45.379000  215379 manager.go:408] Got registration request from device plugin with resource name "fake-domain/resource"
I1127 05:25:45.383428  215379 device_plugin_stub.go:238] ListAndWatch
I1127 05:25:45.391178  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin077505581/device-plugin.sock.new
I1127 05:25:45.391281  215379 device_plugin_stub.go:191] Deprecation file not found. Invoke registration
I1127 05:25:45.394611  215379 manager.go:408] Got registration request from device plugin with resource name "fake-domain/resource"
I1127 05:25:45.399425  215379 device_plugin_stub.go:238] ListAndWatch
I1127 05:25:45.407200  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin077505581/device-plugin.sock.third
I1127 05:25:45.407298  215379 device_plugin_stub.go:191] Deprecation file not found. Invoke registration
I1127 05:25:45.414612  215379 manager.go:408] Got registration request from device plugin with resource name "fake-domain/resource"
I1127 05:25:45.418845  215379 device_plugin_stub.go:238] ListAndWatch
E1127 05:25:45.424384  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Unavailable desc = transport is closing
E1127 05:25:45.424528  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Unavailable desc = transport is closing
E1127 05:25:45.425051  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Unavailable desc = transport is closing
I1127 05:25:45.427390  215379 fake_topology_manager.go:30] [fake topologymanager] NewFakeManager
W1127 05:25:45.427660  215379 manager.go:594] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
I1127 05:25:45.430337  215379 plugin_manager.go:114] Starting Kubelet Plugin Manager
I1127 05:25:45.432482  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin151853188/device-plugin.sock
I1127 05:25:45.436246  215379 device_plugin_stub.go:164] GetInfo
E1127 05:25:45.439735  215379 goroutinemap.go:150] Operation for "/tmp/device_plugin151853188/server.sock" failed. No retries permitted until 2020-11-27 05:25:45.937941568 +0000 UTC m=+1.094479632 (durationBeforeRetry 500ms). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /tmp/device_plugin151853188/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I1127 05:25:45.442921  215379 device_plugin_stub.go:238] ListAndWatch
I1127 05:25:45.452971  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin151853188/device-plugin.sock.new
E1127 05:25:46.433946  215379 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Canceled desc = grpc: the client connection is closing
I1127 05:25:46.446896  215379 device_plugin_stub.go:164] GetInfo
E1127 05:25:46.447263  215379 goroutinemap.go:150] Operation for "/tmp/device_plugin151853188/server.sock" failed. No retries permitted until 2020-11-27 05:25:47.447080785 +0000 UTC m=+2.603618893 (durationBeforeRetry 1s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /tmp/device_plugin151853188/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I1127 05:25:46.451383  215379 device_plugin_stub.go:164] GetInfo
I1127 05:25:46.455485  215379 device_plugin_stub.go:238] ListAndWatch
I1127 05:25:46.461114  215379 device_plugin_stub.go:238] ListAndWatch
I1127 05:25:46.468597  215379 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin151853188/device-plugin.sock.third
--- FAIL: TestDevicePluginReRegistrationProbeMode (1.04s)
    manager_test.go:223: 
        	Error Trace:	manager_test.go:223
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 2
        	Test:       	TestDevicePluginReRegistrationProbeMode
        	Messages:   	Devices of previous registered should be removed
I1127 05:25:46.474428  215379 fake_topology_manager.go:30] [fake topologymanager] NewFakeManager
E1127 05:25:46.505334  215379 manager.go:544] unexpected: unhealthyDevices and endpoints are out of sync
I1127 05:25:46.525706  215379 fake_topology_manager.go:30] [fake topologymanager] NewFakeManager
I1127 05:25:46.526291  215379 fake_topology_manager.go:35] [fake topologymanager] GetAffinity pod: 5532d3cf-972c-4b23-acb7-aedbd99eac0d container name:  
I1127 05:25:46.526526  215379 fake_topology_manager.go:35] [fake topologymanager] GetAffinity pod: 5532d3cf-972c-4b23-acb7-aedbd99eac0d container name:  
I1127 05:25:46.534916  215379 fake_topology_manager.go:35] [fake topologymanager] GetAffinity pod: e06661bc-2e81-4ae1-b671-e9f97e69bbea container name:  
I1127 05:25:46.541748  215379 fake_topology_manager.go:30] [fake topologymanager] NewFakeManager
I1127 05:25:46.542045  215379 fake_topology_manager.go:35] [fake topologymanager] GetAffinity pod: 9b379718-f72b-4c05-9bff-d54b4483f613 container name:  f78dc3c6-9cc4-456e-8cd8-88e90b836ffa
I1127 05:25:46.547467  215379 fake_topology_manager.go:35] [fake topologymanager] GetAffinity pod: 9b379718-f72b-4c05-9bff-d54b4483f613 container name:  57793332-2b3e-4cbf-b01f-ee8e3dd305bf
I1127 05:25:46.553218  215379 fake_topology_manager.go:35] [fake topologymanager] GetAffinity pod: 9b379718-f72b-4c05-9bff-d54b4483f613 container name:  80783646-5c50-4bbb-b64f-14f29d1351ce
I1127 05:25:46.559343  215379 fake_topology_manager.go:35] [fake topologymanager] GetAffinity pod: 9b379718-f72b-4c05-9bff-d54b4483f613 container name:  7e774d21-0355-43f9-908f-aef222512c9b
I1127 05:25:46.567402  215379 fake_topology_manager.go:30] [fake topologymanager] NewFakeManager
I1127 05:25:46.567627  215379 fake_topology_manager.go:35] [fake topologymanager] GetAffinity pod: 1dc10f8e-b8e6-4afb-9aae-9056682fbb9c container name:  
I1127 05:25:46.580479  215379 topology_hints.go:46] [devicemanager] Resource 'testdevice' does not have a topology preference
E1127 05:25:46.581214  215379 topology_hints.go:70] [devicemanager] Unable to generate topology hints: requested number of devices unavailable for 'testdevice': requested: 6, available: 4
I1127 05:25:46.581370  215379 topology_hints.go:61] [devicemanager] Regenerating TopologyHints for resource 'testdevice' already allocated to (pod _(fakePod), container fakeContainer)
E1127 05:25:46.581525  215379 topology_hints.go:57] [devicemanager] Resource 'testdevice' already allocated to (pod _(fakePod), container fakeContainer) with different number than request: requested: 4, allocated: 2
E1127 05:25:46.581748  215379 topology_hints.go:57] [devicemanager] Resource 'testdevice' already allocated to (pod _(fakePod), container fakeContainer) with different number than request: requested: 2, allocated: 4
I1127 05:25:46.596442  215379 topology_hints.go:96] [devicemanager] Resource 'testdevice' does not have a topology preference
I1127 05:25:46.596945  215379 topology_hints.go:111] [devicemanager] Regenerating TopologyHints for resource 'testdevice' already allocated to (pod _(fakePod))
E1127 05:25:46.597171  215379 topology_hints.go:119] [devicemanager] Unable to generate topology hints: requested number of devices unavailable for 'testdevice': requested: 6, available: 4
I1127 05:25:46.597302  215379 topology_hints.go:111] [devicemanager] Regenerating TopologyHints for resource 'testdevice' already allocated to (pod _(fakePod))
E1127 05:25:46.597438  215379 topology_hints.go:107] [devicemanager] Resource 'testdevice' already allocated to (pod _(fakePod)) with different number than request: requested: 4, allocated: 2
E1127 05:25:46.597550  215379 topology_hints.go:107] [devicemanager] Resource 'testdevice' already allocated to (pod _(fakePod)) with different number than request: requested: 2, allocated: 4
FAIL
```

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
Triage shows nothings (seems to not have updated data), but there are multiple failures in the job bazel-test-master.

- links to specific failures in spyglass appreciated

  * https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-master/1332184419200405504
  * https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/periodic-kubernetes-bazel-test-master/1330993756861632512

@kubernetes/ci-signal

### PR DESCRIPTION
**Pull request by JornShen**
**What type of PR is this?**
/kind bug
/kind flake

**What this PR does / why we need it**:

- How to reproduce it ?

```
go test -race -c ./pkg/kubelet/cm/devicemanager
stress ./devicemanager.test -test.run TestDevicePluginReRegistrationProbeMode   
```

- two modify place:
1.  start device plugin "device-plugin.sock" before starting pluginmanager

The origin problem is that the test start `pluginmanager` before starting device plugin "device-plugin.sock".
after pluginmanager start,  fswatcher in pluginmanager will listen `socketDir` 

https://github.com/fsnotify/fsnotify/blob/7f4cf4dd2b522a984eaca51d1ccee54101d3414a/inotify.go#L59

And also it will register the socket dir plugin later 

https://github.com/kubernetes/kubernetes/blob/fb02a59a6a10623b971107231b3c823fed6c43a8/pkg/kubelet/pluginmanager/pluginwatcher/plugin_watcher.go#L67

I add log to watch register event as fellow:
```
@@ -74,6 +87,7 @@ func (w *Watcher) Start(stopCh <-chan struct{}) error {
                        case event := <-fsWatcher.Events:
                                //TODO: Handle errors by taking corrective measures
                                if event.Op&fsnotify.Create == fsnotify.Create {
+                                       klog.Errorf("<-- go func(fsWatcher *fsnotify.Watcher)")
                                        err := w.handleCreateEvent(event)
                                        if err != nil {
                                                klog.Errorf("error %v when handling create event: %s", err, event)
@@ -142,6 +162,7 @@ func (w *Watcher) traversePluginDir(dir string) error {
                                Op:   fsnotify.Create,
                        }
                        //TODO: Handle errors by taking corrective measures
+                       klog.Errorf("<-- traversePluginDir -> handleCreateEvent")
                        if err := w.handleCreateEvent(event); err != nil {
                                klog.Errorf("error %v when handling create event: %s", err, event)
                        }

 func (w *Watcher) handleCreateEvent(event fsnotify.Event) error {
-       klog.V(6).Infof("Handling create event: %v", event)
+       klog.Errorf("Handling create event: %v", event)
 
        fi, err := os.Stat(event.Name)
        if err != nil {

@@ -194,7 +215,7 @@ func (w *Watcher) handlePluginRegistration(socketPath string) error {
        // a possibility that it has been deleted and recreated again before it is
        // removed from the desired world cache, so we still need to call AddOrUpdatePlugin
        // in this case to update the timestamp
-       klog.V(2).Infof("Adding socket path or updating timestamp %s to desired state cache", socketPath)
+       klog.Errorf("Adding socket path or updating timestamp %s to desired state cache", socketPath)
        err := w.desiredStateOfWorld.AddOrUpdatePlugin(socketPath)
        if err != nil {
                return fmt.Errorf("error adding socket path %s or updating timestamp to desired state cache: %v", socketPath, err)
```

if test success, the log will as fellow.
```
=== RUN   TestDevicePluginReRegistrationProbeMode
I1210 09:24:31.872465 1130377 fake_topology_manager.go:30] [fake topologymanager] NewFakeManager
W1210 09:24:31.872586 1130377 manager.go:602] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
I1210 09:24:31.873085 1130377 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin498043817/device-plugin.sock
E1210 09:24:31.873220 1130377 plugin_watcher.go:152] <--  traversePluginDir -> handleCreateEvent
E1210 09:24:31.873224 1130377 plugin_watcher.go:168] Handling create event: "/tmp/device_plugin498043817/device-plugin.sock": CREATE
E1210 09:24:31.873261 1130377 plugin_watcher.go:205] Adding socket path or updating timestamp /tmp/device_plugin498043817/device-plugin.sock to desired state cache
E1210 09:24:31.873271 1130377 plugin_watcher.go:152] <--  traversePluginDir -> handleCreateEvent
E1210 09:24:31.873273 1130377 plugin_watcher.go:168] Handling create event: "/tmp/device_plugin498043817/server.sock": CREATE
E1210 09:24:31.873279 1130377 plugin_watcher.go:205] Adding socket path or updating timestamp /tmp/device_plugin498043817/server.sock to desired state cache
I1210 09:24:31.873287 1130377 plugin_manager.go:114] Starting Kubelet Plugin Manager
I1210 09:24:31.874110 1130377 device_plugin_stub.go:164] GetInfo
E1210 09:24:31.874247 1130377 manager.go:315] sch: Registering Plugin fake-domain/resource at endpoint /tmp/device_plugin498043817/device-plugin.sock
E1210 09:24:31.874251 1130377 goroutinemap.go:150] Operation for "/tmp/device_plugin498043817/server.sock" failed. No retries permitted until 2020-12-10 09:24:32.374223872 +0800 CST m=+0.517294492 (durationBeforeRetry 500ms). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /tmp/device_plugin498043817/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
```
we can see the one register from socket `device-plugin.sock` 

if the test failed, the output as fellow
```
=== RUN   TestDevicePluginReRegistrationProbeMode
I1210 15:18:45.864453 1148592 fake_topology_manager.go:30] [fake topologymanager] NewFakeManager
W1210 15:18:45.864700 1148592 manager.go:602] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
E1210 15:18:45.866062 1148592 plugin_watcher.go:165] <--  traversePluginDir -> handleCreateEvent
E1210 15:18:45.867240 1148592 plugin_watcher.go:181] Handling create event: "/tmp/device_plugin658673309/device-plugin.sock": CREATE
E1210 15:18:45.867331 1148592 plugin_watcher.go:218] Adding socket path or updating timestamp /tmp/device_plugin658673309/device-plugin.sock to desired state cache
E1210 15:18:45.867380 1148592 plugin_watcher.go:165] <--  traversePluginDir -> handleCreateEvent
E1210 15:18:45.867400 1148592 plugin_watcher.go:181] Handling create event: "/tmp/device_plugin658673309/server.sock": CREATE
E1210 15:18:45.867481 1148592 plugin_watcher.go:218] Adding socket path or updating timestamp /tmp/device_plugin658673309/server.sock to desired state cache
I1210 15:18:45.867684 1148592 plugin_manager.go:114] Starting Kubelet Plugin Manager
E1210 15:18:45.867742 1148592 plugin_watcher.go:90] <--  go func(fsWatcher *fsnotify.Watcher)
E1210 15:18:45.867796 1148592 plugin_watcher.go:181] Handling create event: "/tmp/device_plugin658673309/device-plugin.sock": CREATE
E1210 15:18:45.868013 1148592 plugin_watcher.go:218] Adding socket path or updating timestamp /tmp/device_plugin658673309/device-plugin.sock to desired state cache
I1210 15:18:45.869102 1148592 device_plugin_stub.go:148] Starting to serve on /tmp/device_plugin658673309/device-plugin.sock
I1210 15:18:45.874331 1148592 device_plugin_stub.go:170] GetInfo
E1210 15:18:45.875066 1148592 goroutinemap.go:150] Operation for "/tmp/device_plugin658673309/server.sock" failed. No retries permitted until 2020-12-10 15:18:46.37491185 +0800 CST m=+0.578446851 (durationBeforeRetry 500ms). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /tmp/device_plugin658673309/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I1210 15:18:45.878416 1148592 device_plugin_stub.go:244] ListAndWatch
```
we can see device-plugin.sock register twice and this break the test's rhythm later and case the error. 

This is becase there are some interval between fswatch's `readEvents` and `traversePluginDir`. if socket `device-plugin.sock` created in this interval, it will register twice.

2. fix reconcile's field `handler` data race problem.

when I  change place 1, and rerun the stress.  And meet a race 
output as fellow:
```
=== RUN   TestDevicePluginReRegistrationProbeMode
I1210 15:46:16.502065 1153099 fake_topology_manager.go:30] [fake topologymanager] NewFakeManager
W1210 15:46:16.502308 1153099 manager.go:594] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
I1210 15:46:16.504720 1153099 device_plugin_stub.go:142] Starting to serve on /tmp/device_plugin187177318/device-plugin.sock
I1210 15:46:16.505182 1153099 plugin_manager.go:114] Starting Kubelet Plugin Manager
E1210 15:46:16.512303 1153099 goroutinemap.go:150] Operation for "/tmp/device_plugin187177318/server.sock" failed. No retries permitted until 2020-12-10 15:46:17.012208711 +0800 CST m=+0.582032894 (durationBeforeRetry 500ms). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /tmp/device_plugin187177318/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I1210 15:46:16.515055 1153099 device_plugin_stub.go:164] GetInfo
==================
WARNING: DATA RACE
Read at 0x00c0001f6990 by goroutine 39:
  runtime.mapaccess2_faststr()
      /usr/local/go/src/runtime/map_faststr.go:107 +0x0
  k8s.io/kubernetes/pkg/kubelet/pluginmanager/operationexecutor.(*operationGenerator).GenerateRegisterPluginFunc.func1()
      /opt/workspace/myspace/src/k8s.io/kubernetes/pkg/kubelet/pluginmanager/operationexecutor/operation_generator.go:95 +0x4de
  k8s.io/kubernetes/pkg/util/goroutinemap.(*goRoutineMap).Run.func1()
      /opt/workspace/myspace/src/k8s.io/kubernetes/pkg/util/goroutinemap/goroutinemap.go:115 +0x147

Previous write at 0x00c0001f6990 by goroutine 23:
  runtime.mapassign_faststr()
      /usr/local/go/src/runtime/map_faststr.go:202 +0x0
  k8s.io/kubernetes/pkg/kubelet/pluginmanager/reconciler.(*reconciler).AddHandler()
      /opt/workspace/myspace/src/k8s.io/kubernetes/pkg/kubelet/pluginmanager/reconciler/reconciler.go:96 +0xeb
  k8s.io/kubernetes/pkg/kubelet/pluginmanager.(*pluginManager).AddHandler()
      /opt/workspace/myspace/src/k8s.io/kubernetes/pkg/kubelet/pluginmanager/plugin_manager.go:123 +0x83
  k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.setupPluginManager()
      /opt/workspace/myspace/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager_test.go:268 +0x145
  k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.setupInProbeMode()
      /opt/workspace/myspace/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager_test.go:286 +0x15d
  k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.TestDevicePluginReRegistrationProbeMode()
      /opt/workspace/myspace/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager_test.go:178 +0x4d1
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1127 +0x202
```
It is obvious that field handler get from `getHandlers` is a reference. if we set it `AddHandler`, they will compete.

**Which issue(s) this PR fixes**:

Fix https://github.com/kubernetes/kubernetes/issues/96908

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by klueska** [comment]
I think @vpickard would probably know the right person to assign this to.

File: pkg/kubelet/cm/devicemanager/manager_test.go [hunk 1]
```diff
@@ -282,8 +282,8 @@ func setup(t *testing.T, devs []*pluginapi.Device, callback monitorCallback, soc
 
 func setupInProbeMode(t *testing.T, devs []*pluginapi.Device, callback monitorCallback, socketName string, pluginSocketName string) (Manager, <-chan interface{}, *Stub, pluginmanager.PluginManager) {
 	m, updateChan := setupDeviceManager(t, devs, callback, socketName)
-	pm := setupPluginManager(t, pluginSocketName, m)
 	p := setupDevicePlugin(t, devs, pluginSocketName)
+	pm := setupPluginManager(t, pluginSocketName, m)
```
Comment (klueska) [inline pkg/kubelet/cm/devicemanager/manager_test.go:286]: This change seems OK -- just curious if you know exactly why the order matters here.

File: pkg/kubelet/pluginmanager/reconciler/reconciler.go [hunk 2]
```diff
@@ -100,7 +100,11 @@ func (rc *reconciler) getHandlers() map[string]cache.PluginHandler {
 	rc.RLock()
 	defer rc.RUnlock()
 
-	return rc.handlers
+	var copyHandlers = make(map[string]cache.PluginHandler)
+	for pluginType, handler := range rc.handlers {
+		copyHandlers[pluginType] = handler
+	}
+	return copyHandlers
```
Comment (klueska) [inline pkg/kubelet/pluginmanager/reconciler/reconciler.go:107]: Can you explain why we need a copy here?

**Review by klueska — COMMENTED** [review]
I do not have full approval rights for this PR, but I can at least approve the changes in `cm` and point it at someone who can approve the changes in `pluginmanager`. Just have a few questions about it.

File: pkg/kubelet/cm/devicemanager/manager_test.go (hunk 1 above)
Comment (JornShen) [reply pkg/kubelet/cm/devicemanager/manager_test.go:286]: See the explain before.  Previous order may cause  device-plugin.sock add twice.  

one is from 
https://github.com/kubernetes/kubernetes/blob/970b532379b2b1d0b1352f960fd7f88f0726123e/pkg/kubelet/pluginmanager/pluginwatcher/plugin_watcher.go#L71-L80

another is from
https://github.com/kubernetes/kubernetes/blob/970b532379b2b1d0b1352f960fd7f88f0726123e/pkg/kubelet/pluginmanager/pluginwatcher/plugin_watcher.go#L119-L145

File: pkg/kubelet/pluginmanager/reconciler/reconciler.go (hunk 2 above)
Comment (JornShen) [reply pkg/kubelet/pluginmanager/reconciler/reconciler.go:107]: A data race. You can see my second modify place `fix reconcile's field handler data race problem.`.
Here we return reference of handler and release the lock which control the race of handler.
Support that one routine is use this reference of handler. The other routine use `AddHandler ` to set it. The lock does promise this kind race.

Comment (klueska) [reply pkg/kubelet/pluginmanager/reconciler/reconciler.go:107]: I don't have enough context on this part of the code to know if it is better to copy this or add proper locking around accessing it.

/cc @derekwaynecarr can hopeully find the right person to look at it.

File: pkg/kubelet/cm/devicemanager/manager_test.go (hunk 1 above)
Comment (klueska) [reply pkg/kubelet/cm/devicemanager/manager_test.go:286]: Makes sense. Thanks for clarifying

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve
