### PR TITLE
Exclude nodes from rolling update depending on tolerations

### LINKED ISSUE #118823: DaemonSet fails to scale down during the rolling update when `maxUnavailable=0`
### What happened?

I have a daemonset with the rolling update strategy. I have `maxSurge` parameter set to a non zero value [which means](https://github.com/openshift/kubernetes/blob/cb4b47e5ddfbaf7844237b2e2eb2b0acfed5f1b5/pkg/apis/apps/validation/validation.go#L394-L402) that the `maxUnavailable` parameter is set to `0`. When I replace the toleration in the daemonset's template spec from the one which helped me to be scheduled on the master node into any other toleration, I see the new pods still trying to be scheduled on the master nodes. The old pods from the tolerated nodes can be lucky enough to be recreated but only if they go before any pod from the intolerable node.

```
$ kubectl -n openshift-dns get ds dns-default -o yaml | yq .spec.updateStrategy
rollingUpdate:
  maxSurge: 10%
  maxUnavailable: 0
type: RollingUpdate

$ kubectl -n openshift-dns get ds dns-default -o yaml | yq .spec.template.spec.tolerations
- key: node-role.kubernetes.io/master
  operator: Exists
  
$ kubectl -n openshift-dns get pods  -o wide | grep dns-default
dns-default-6bfmf     2/2     Running   0          119m    10.129.0.40   ci-ln-sb5ply2-72292-qlhc8-master-2         <none>           <none>
dns-default-9cjdf     2/2     Running   0          2m35s   10.129.2.15   ci-ln-sb5ply2-72292-qlhc8-worker-c-m5wzq   <none>           <none>
dns-default-c6j9x     2/2     Running   0          119m    10.128.0.13   ci-ln-sb5ply2-72292-qlhc8-master-0         <none>           <none>
dns-default-fhqrs     2/2     Running   0          2m12s   10.131.0.29   ci-ln-sb5ply2-72292-qlhc8-worker-a-6q7hs   <none>           <none>
dns-default-lx2nf     2/2     Running   0          119m    10.130.0.15   ci-ln-sb5ply2-72292-qlhc8-master-1         <none>           <none>
dns-default-mmc78     2/2     Running   0          112m    10.128.2.7    ci-ln-sb5ply2-72292-qlhc8-worker-b-bpjdk   <none>           <none>

$ kubectl -n openshift-dns get ds dns-default -o yaml | yq .spec.template.spec.tolerations
- key: test-taint
  operator: Exists
  
$ kubectl -n openshift-dns get ds dns-default
NAME             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR
dns-default   3                 3                  3             1                       3                    kubernetes.io/os=linux 
  
$ kubectl -n openshift-dns get pods  -o wide | grep dns-default
dns-default-6bfmf     2/2     Running   0          124m    10.129.0.40   ci-ln-sb5ply2-72292-qlhc8-master-2         <none>           <none>
dns-default-76vjz     0/2     Pending   0          3m2s    <none>        <none>                                     <none>           <none>
dns-default-9cjdf     2/2     Running   0          7m24s   10.129.2.15   ci-ln-sb5ply2-72292-qlhc8-worker-c-m5wzq   <none>           <none>
dns-default-c6j9x     2/2     Running   0          124m    10.128.0.13   ci-ln-sb5ply2-72292-qlhc8-master-0         <none>           <none>
dns-default-fhqrs     2/2     Running   0          7m1s    10.131.0.29   ci-ln-sb5ply2-72292-qlhc8-worker-a-6q7hs   <none>           <none>
dns-default-lx2nf     2/2     Running   0          124m    10.130.0.15   ci-ln-sb5ply2-72292-qlhc8-master-1         <none>           <none>
dns-default-mmc78     2/2     Running   0          117m    10.128.2.7    ci-ln-sb5ply2-72292-qlhc8-worker-b-bpjdk   <none>           <none>

$ kubectl -n openshift-dns get pods dns-default-76vjz -o yaml | yq .spec.affinity.nodeAffinity
requiredDuringSchedulingIgnoredDuringExecution:
  nodeSelectorTerms:
    - matchFields:
        - key: metadata.name
          operator: In
          values:
            - ci-ln-sb5ply2-72292-qlhc8-master-0
```

### What did you expect to happen?

I don't expect the new pods to be scheduled on the nodes which are not tolerated by the new DamonSet's template spec. The daemonset controller should just delete the old pods from the nodes which cannot be tolerated anymore. The old pods from the nodes which can still be tolerated should be recreated according to the rolling update parameters.

### How can we reproduce it (as minimally and precisely as possible)?

On a Kubernetes cluster with 3 or more master node and 3 or more worker node (2 and 2 may be enough too, I guess):
- Create a DaemonSet which
   - has the rolling update strategy with `maxSurge=10%` and `maxUnavailable=0`
   - has a toleration of the master node role taint: `node-role.kubernetes.io/master`
- Wait until all the pods become ready
- Update the DaemonSet replacing `node-role.kubernetes.io/master` toleration with any other (even not existing).
- See the new pod trying to be scheduled on the master node and getting into `Pending` state

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
Kubernetes Version: v1.26.5+7d22122
Kubernetes Version: v1.27.2+b451817
```

</details>

### Cloud provider

<details>
Doesn't matter.
</details>

### OS version

<details>
Doesn't matter.
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRI-O
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Doesn't matter.
</details>

### PR DESCRIPTION
**Pull request by mochizuki875**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

In this PR, exclude `Nodes` from daemon pod updating if the `tolerations` of it  dose not match the `taints` of `Nodes`.
It will cause update stuck if we try to rolling update `DaemonSet` which has non zero `maxSurge` and dose not have `tolerations` matching `Nodes` `taints`.
It's because all `Nodes` running `Pods` belonging to the previous `DaemonSet` are included in the update, regardless of the `tolerations` of the new `DaemonSet`.

#### Which issue(s) this PR fixes:

Fixes #118823

#### Does this PR introduce a user-facing change?

```release-note
Revised the logic for DaemonSet rolling update to exclude nodes if scheduling constraints are not met.
This eliminates the problem of rolling updates to a DaemonSet getting stuck around tolerations.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/daemon/update.go [hunk 1]
```diff
@@ -172,6 +193,27 @@ func (dsc *DaemonSetsController) rollingUpdate(ctx context.Context, ds *apps.Dae
...
+				}
+
+				shouldRun, shouldContinueRunning := NodeShouldRunDaemonPod(node, ds)
+
+				// daemonset should not run pod on the node
+				if !shouldRun {
+					logger.V(5).Info("Exclude the node from daemon pod updating", "daemonset", klog.KObj(ds), "pod", klog.KObj(oldPod), "node", klog.KRef("", nodeName))
+
+					// daemonset should continue running pod on the node
+					if shouldContinueRunning {
```
Comment (atiratree) [inline pkg/controller/daemon/update.go:209]: The above comment applies even here for the available pods but it is more complicated.

First we should not keep the revision A pods running, or we will clutter nodes with our old pods. Eg just try to move a DS from a set of nodes Y to a set of nodes Z and you will have a DS tracking 3 pods even though 6 are running.

Secondly, due to our validation, maxUnavailable must be set to 0 when surge is enabled. But the problem is that is if you change scheduling constraints from set of nodes Y to a set of nodes Z and there is no intersection for these nodes, the application would not have a single available pod at a time and thus possibly disrupting some applications.

Thus we probably should delete these pods after all of the new pods have become available to preserve the availability (one of the ways would be to allow maxaUnavailable feature, but that is more complicated and probably deserves a KEP)

We could internally implement maxUnavailable=1, but that would still not work for eg a two node cluster where the daemonset would be active only on a single node.

IMO, best way to do it is decrementally delete the pods when "numberAvailable > desiredNumberScheduled" (in `rollingUpdate` function), ie we delete a single pod from an old set Y, when a new pod becomes available from a set Z.

File: pkg/controller/daemon/update_test.go [hunk 2]
```diff
@@ -117,6 +117,60 @@ func TestDaemonSetUpdatesPodsWithMaxSurge(t *testing.T) {
...
+	markPodsReady(podControl.podStore)
+
+	clearExpectations(t, manager, ds, podControl)
+	expectSyncDaemonSets(t, manager, ds, podControl, maxSurge, maxSurge, 0)
+	clearExpectations(t, manager, ds, podControl)
+	expectSyncDaemonSets(t, manager, ds, podControl, 0, 0, 0)
+	markPodsReady(podControl.podStore)
+
+	clearExpectations(t, manager, ds, podControl)
+	expectSyncDaemonSets(t, manager, ds, podControl, 0, maxSurge, 0)
```
Comment (atiratree) [inline pkg/controller/daemon/update_test.go:169]: so this would mean we got only 4 deletions, even though there should have been 5.

Can you please add tests that show a changing pods from a set of nodes Y to a set of nodes Z. Might be good to add some intersection between Y and Z for observing normal surge.

Eg you can test following transitions
- start DS on nodes Y
- move to nodes Z
- move to nodes Z+Y
- remove all tolerations = 0 pods running

I think this bug/feature fix requires an E2E test to show it is working properly and to show there are no extra pods hanging around after each of these transitions.

**Comment by atiratree** [comment]
@mochizuki875

File: pkg/controller/daemon/update.go [hunk 3]
```diff
@@ -162,6 +162,27 @@ func (dsc *DaemonSetsController) rollingUpdate(ctx context.Context, ds *apps.Dae
...
```
[the remark this answers is not in the document]
Comment (mochizuki875) [reply pkg/controller/daemon/update.go:178]: @atiratree 
OK, I'll fix like that.

File: pkg/controller/daemon/update.go (hunk 1 above)
Comment (mochizuki875) [reply pkg/controller/daemon/update.go:209]: @atiratree 
Thank you for your advice!

> IMO, best way to do it is decrementally delete the pods when "numberAvailable > desiredNumberScheduled" (in rollingUpdate function), ie we delete a single pod from an old set Y, when a new pod becomes available from a set Z.

I'll fix as you said.
However numberAvailable and desiredNumberScheduled seems to be calculated after evaluation of shouldRun.
If there are daemon pods on the node not matching the scheduling constraints, numberAvailable will not be incremented.

https://github.com/kubernetes/kubernetes/blob/97c7dbcd227ec253bb277a91575706fe30f519dc/pkg/controller/daemon/daemon_controller.go#L1174-L1190

So I think we need to fix the logic of updating DaemonSet status, right?

Comment (atiratree) [reply pkg/controller/daemon/update.go:209]: @mochizuki875  I think we can count all the values we need in situ. Also take a look if we can use `updatedDesiredNodeCounts` and maybe return additional values? Or if it makes more sense to count it in `rollingUpdate`. I mentioned `numberAvailable` and `desiredNumberScheduled` just for an illustration; and they do not have to match the status. There are more ways how to implement this.

Nevertheless, I would not change the status counting or updating logic, unless there is a good reason for it.

Comment (mochizuki875) [reply pkg/controller/daemon/update.go]: @atiratree 
Thank you for your comment.
I've fixed that.
Could you please check again?

File: pkg/controller/daemon/update.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (mochizuki875) [reply pkg/controller/daemon/update.go]: @atiratree 
I've fixed that.

File: pkg/controller/daemon/update_test.go (hunk 2 above)
Comment (mochizuki875) [reply pkg/controller/daemon/update_test.go]: I'll start working after the rollingUpdate fix is complete.

File: pkg/controller/daemon/update.go [hunk 4]
```diff
@@ -570,3 +614,35 @@ func (h historiesByRevision) Swap(i, j int) { h[i], h[j] = h[j], h[i] }
...
+}
+
+func getNumAvailablePod(ds *apps.DaemonSet, nodeToDaemonPods map[string][]*v1.Pod, now time.Time) int32 {
+
+	numAvailablePod := int32(0)
+
+	for _, pods := range nodeToDaemonPods {
+		for _, pod := range pods {
+
+			if podutil.IsPodReady(pod) && podutil.IsPodAvailable(pod, ds.Spec.MinReadySeconds, metav1.Time{Time: now}) && pod.ObjectMeta.DeletionTimestamp == nil {
```
Comment (atiratree) [inline pkg/controller/daemon/update.go:641]: I think we are only interested in one pod per node when checking the availability (similar to status).

File: pkg/controller/daemon/update.go [hunk 5]
```diff
@@ -570,3 +614,35 @@ func (h historiesByRevision) Swap(i, j int) { h[i], h[j] = h[j], h[i] }
...
+
+	if !shouldRun || !shouldContinueRunning {
+		return true, nil
+	}
+	return false, nil
+
+}
+
+func getNumAvailablePod(ds *apps.DaemonSet, nodeToDaemonPods map[string][]*v1.Pod, now time.Time) int32 {
+
```
Comment (atiratree) [inline pkg/controller/daemon/update.go:635]: please cut down the extra spaces like this one

File: pkg/controller/daemon/update.go [hunk 6]
```diff
@@ -172,6 +186,18 @@ func (dsc *DaemonSetsController) rollingUpdate(ctx context.Context, ds *apps.Dae
 				continue
 			default:
 				logger.V(5).Info("DaemonSet pod on node is out of date, this is a surge candidate", "daemonset", klog.KObj(ds), "pod", klog.KObj(oldPod), "node", klog.KRef("", nodeName))
+
+				shouldDeleteDaemonPod, err := dsc.checkShouldDeleteDaemonPod(nodeName, ds)
+				if err != nil {
+					return fmt.Errorf("Couldn't check daemon pod to delete for nodeName %q: %v", nodeName, err)
```
Comment (atiratree) [inline pkg/controller/daemon/update.go:192]: lint: error message starts with a lower case

File: pkg/controller/daemon/update.go [hunk 7]
```diff
@@ -172,6 +186,18 @@ func (dsc *DaemonSetsController) rollingUpdate(ctx context.Context, ds *apps.Dae
...
+				}
+
+				if shouldDeleteDaemonPod {
+					logger.V(5).Info("Daemon pod should be deleted from the node", "daemonset", klog.KObj(ds), "pod", klog.KObj(oldPod), "node", klog.KRef("", nodeName))
```
Comment (atiratree) [inline pkg/controller/daemon/update.go:196]:
```suggestion
					logger.V(5).Info("DaemonSet pod should be deleted from the node as it is not schedulable anymore", "daemonset", klog.KObj(ds), "pod", klog.KObj(oldPod), "node", klog.KRef("", nodeName))
```

File: pkg/controller/daemon/update.go [hunk 8]
```diff
@@ -570,3 +614,35 @@ func (h historiesByRevision) Swap(i, j int) { h[i], h[j] = h[j], h[i] }
 func (h historiesByRevision) Less(i, j int) bool {
 	return h[i].Revision < h[j].Revision
 }
+
+func (dsc *DaemonSetsController) checkShouldDeleteDaemonPod(nodeName string, ds *apps.DaemonSet) (bool, error) {
```
Comment (atiratree) [inline pkg/controller/daemon/update.go:618]: can we first try to do without this function and have the code duplicated first?  At this point it seems like a needless misdirection.

File: pkg/controller/daemon/update.go [hunk 9]
```diff
@@ -194,6 +220,24 @@ func (dsc *DaemonSetsController) rollingUpdate(ctx context.Context, ds *apps.Dae
...
+
+		diffAvailableAndDesired := int(getNumAvailablePod(ds, nodeToDaemonPods, now) - ds.Status.DesiredNumberScheduled)
+
+		if diffAvailableAndDesired < 0 {
+			diffAvailableAndDesired = 0
+		}
+		if numPodToDeletePod := len(shouldNotRunPodsToDelete); diffAvailableAndDesired > numPodToDeletePod {
+			diffAvailableAndDesired = numPodToDeletePod
+		}
+		if diffAvailableAndDesired > remainingSurge {
```
Comment (atiratree) [inline pkg/controller/daemon/update.go:234]: why do we need to consult remaining surge? We can delete these pods even when remainingSurge is 0. Because these pods are living on the extra non schedulable nodes...

File: pkg/controller/daemon/update_test.go (hunk 2 above)
Comment (atiratree) [reply pkg/controller/daemon/update_test.go]: @mochizuki875 I think it would be good to work on the test at the same time, as it can reveal bugs in the implementation

File: pkg/controller/daemon/update.go [hunk 10]
```diff
@@ -194,6 +220,24 @@ func (dsc *DaemonSetsController) rollingUpdate(ctx context.Context, ds *apps.Dae
 	// use any of the candidates we can, including the allowedNewNodes
 	logger.V(5).Info("DaemonSet allowing replacements", "daemonset", klog.KObj(ds), "replacements", len(allowedNewNodes), "maxSurge", maxSurge, "numSurge", numSurge, "candidates", len(candidateNewNodes))
 	remainingSurge := maxSurge - numSurge
+
+	if remainingSurge > 0 {
+
+		diffAvailableAndDesired := int(getNumAvailablePod(ds, nodeToDaemonPods, now) - ds.Status.DesiredNumberScheduled)
```
[the remark this answers is not in the document]
Comment (mochizuki875) [reply pkg/controller/daemon/update.go:226]: @atiratree 
Oh, thanks for letting me know!
Is it ok to make `updatedDesiredNodeCounts` return additional value `desiredNumberScheduled`?

File: pkg/controller/daemon/update.go [hunk 11]
```diff
@@ -570,3 +614,35 @@ func (h historiesByRevision) Swap(i, j int) { h[i], h[j] = h[j], h[i] }
...
 }
+
+func (dsc *DaemonSetsController) checkShouldDeleteDaemonPod(nodeName string, ds *apps.DaemonSet) (bool, error) {
+
+	node, err := dsc.nodeLister.Get(nodeName)
+	if err != nil {
+		return false, err
+	}
+
+	shouldRun, shouldContinueRunning := NodeShouldRunDaemonPod(node, ds)
```
[the remark this answers is not in the document]
Comment (mochizuki875) [reply pkg/controller/daemon/update.go:625]: @atiratree 
Thanks!
You're right and I'll fix it.

File: pkg/controller/daemon/update.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (atiratree) [reply pkg/controller/daemon/update.go:226]: yes, I think it should be fine

File: pkg/controller/daemon/update.go (hunk 9 above)
Comment (mochizuki875) [reply pkg/controller/daemon/update.go:234]: Oops, sorry!
I forgot to delete the implementation I wrote as a test...
I'll remove that.

File: pkg/controller/daemon/update.go [hunk 12]
```diff
@@ -570,3 +614,35 @@ func (h historiesByRevision) Swap(i, j int) { h[i], h[j] = h[j], h[i] }
...
+	}
+	return false, nil
+
+}
+
+func getNumAvailablePod(ds *apps.DaemonSet, nodeToDaemonPods map[string][]*v1.Pod, now time.Time) int32 {
+
+	numAvailablePod := int32(0)
+
+	for _, pods := range nodeToDaemonPods {
```
[the remark this answers is not in the document]
Comment (mochizuki875) [reply pkg/controller/daemon/update.go]: >  Can we count the pods there?
Thanks for your comment!
I've fixed that.

File: pkg/controller/daemon/update.go (hunk 4 above)
Comment (mochizuki875) [reply pkg/controller/daemon/update.go]: Now that I've changed that logic to count availableNumber in the surge loop, I don't think I need to worry anymore.

File: pkg/controller/daemon/update.go (hunk 6 above)
Comment (mochizuki875) [reply pkg/controller/daemon/update.go]: Sorry, I've fixed that.

File: pkg/controller/daemon/update.go (hunk 8 above)
Comment (mochizuki875) [reply pkg/controller/daemon/update.go]: OK, I've fixed that.

File: pkg/controller/daemon/update_test.go (hunk 2 above)
Comment (mochizuki875) [reply pkg/controller/daemon/update_test.go:189]: I've fixed that test case and added new case which dose what you suggested.

**Comment by mochizuki875** [comment]
@atiratree 
Sorry for the delay, I've fixed it according to your comment.
Could you please check again?

File: pkg/controller/daemon/update_test.go [hunk 13]
```diff
@@ -117,7 +121,190 @@ func TestDaemonSetUpdatesPodsWithMaxSurge(t *testing.T) {
...
+	err = manager.dsStore.Update(ds)
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	clearExpectations(t, manager, ds, podControl)
+	expectSyncDaemonSets(t, manager, ds, podControl, 2, 0, 0)
+	clearExpectations(t, manager, ds, podControl)
+	expectSyncDaemonSets(t, manager, ds, podControl, 0, 0, 0)
+	markPodsReady(podControl.podStore)
```
Comment (atiratree) [inline pkg/controller/daemon/update_test.go:257]: here it would be good to add readiness gradually - eg first add 1 to ready, then 2nd. Also better to have 3 nodes and add 1 ready and then 2 pods ready at the same time.

File: pkg/controller/daemon/update_test.go [hunk 14]
```diff
@@ -117,7 +121,190 @@ func TestDaemonSetUpdatesPodsWithMaxSurge(t *testing.T) {
...
+	if err != nil {
+		t.Fatalf("error creating DaemonSets controller: %v", err)
+	}
+	err = manager.dsStore.Add(ds)
+	if err != nil {
+		t.Fatal(err)
+	}
+
+	// Add four nodes with zone-y or zone-z taint
+	for i := 0; i < 4; i++ {
```
Comment (atiratree) [inline pkg/controller/daemon/update_test.go:220]: also as I suggested in https://github.com/kubernetes/kubernetes/pull/119317#discussion_r1272431930, might be worth to have more nodes and have some intersection between them

File: pkg/controller/daemon/update_test.go [hunk 15]
```diff
@@ -117,7 +121,190 @@ func TestDaemonSetUpdatesPodsWithMaxSurge(t *testing.T) {
...
+	expectSyncDaemonSets(t, manager, ds, podControl, 0, 0, 0)
+	markPodsReady(podControl.podStore)
+
+	clearExpectations(t, manager, ds, podControl)
+	expectSyncDaemonSets(t, manager, ds, podControl, 0, maxSurge, 0)
+	clearExpectations(t, manager, ds, podControl)
+	expectSyncDaemonSets(t, manager, ds, podControl, 0, 0, 0)
+}
+
+func TestDaemonSetUpdatesNodeIntersectionWithMaxSurge(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (mochizuki875) [reply pkg/controller/daemon/update_test.go:197]: @atiratree 
I agree that.
By the way, is `test/integration/daemonset/daemonset_test.go` the test code file to which the integration test cases should be added?

File: pkg/controller/daemon/update_test.go (hunk 14 above)
Comment (mochizuki875) [reply pkg/controller/daemon/update_test.go:220]: I'm not sure I fully understand what you're saying, but your suggesting test scenario in integration test would be something like that?

[step0] Prepare 6 Nodes with taint as below:
```
node-0, node-1
  Key: "zone-y", Effect: NoSchedule
node-2, node-3
  Key: "zone-z", Effect: NoSchedule
node-4, node-5  <- intersection between zone-y and zone-z
  Key: "common", Effect: NoSchedule
```

[step1] Create DaemonSet with these tolerations and expect 4 Pods to run.
```  
Key: "zone-y", Operator: Exists
Key: "common", Operator: Exists
```

[step2] Update DaemonSet with these tolerations and expect 4 Pods to run.
```
Key: "zone-z", Operator: Exists
Key: "common", Operator: Exists
```
	
[step3] Update DaemonSet with these tolerations and expect 6 Pods to run.
```  
Key: "zone-y", Operator: Exists
Key: "zone-z", Operator: Exists
Key: "common", Operator: Exists
```

[step4] Update DaemonSet with no toleration and expect 0 Pod to run.

Comment (atiratree) [reply pkg/controller/daemon/update_test.go:220]: yup, that should work for our use case - to see some of the pods to go without rescheduling

File: pkg/controller/daemon/update_test.go (hunk 15 above)
[the remark this answers is not in the document]
Comment (atiratree) [reply pkg/controller/daemon/update_test.go:197]: @mochizuki875 yes that should be the place

File: pkg/controller/daemon/update.go [hunk 16]
```diff
@@ -156,29 +158,75 @@ func (dsc *DaemonSetsController) rollingUpdate(ctx context.Context, ds *apps.Dae
...
 					candidateNewNodes = make([]string, 0, maxSurge)
 				}
 				candidateNewNodes = append(candidateNewNodes, nodeName)
 			}
 		default:
+			if podutil.IsPodAvailable(oldPod, ds.Spec.MinReadySeconds, metav1.Time{Time: now}) || podutil.IsPodAvailable(newPod, ds.Spec.MinReadySeconds, metav1.Time{Time: now}) {
+				availableNumber++
+			}
 			// we have already surged onto this node, determine our state
 			if !podutil.IsPodAvailable(newPod, ds.Spec.MinReadySeconds, metav1.Time{Time: now}) {
```
[the remark this answers is not in the document]
Comment (mochizuki875) [reply pkg/controller/daemon/update.go:231]: > Maybe it would look better if we make a isNewPodAvailable variable?

Thanks for your advice.
I think this variable can be incremented by the number of ready newPods or oldPods, so `isPodAvailable` is better than `isNewPodAvailable`.

File: pkg/controller/daemon/update_test.go (hunk 14 above)
Comment (mochizuki875) [reply pkg/controller/daemon/update_test.go]: OK, I've added the new integration test case.

**Comment by mochizuki875** [comment]
@atiratree 
My fix has done and I added new integration test case to check our use case.
Could you please check again?

File: test/integration/daemonset/daemonset_test.go [hunk 17]
```diff
@@ -1159,3 +1159,101 @@ func TestUpdateStatusDespitePodCreationFailure(t *testing.T) {
...
+	// Update DaemonSet with zone-z toleration
+	ds.Spec.Template.Spec.Tolerations = []v1.Toleration{
+		{Key: "zone-z", Operator: v1.TolerationOpExists},
+		{Key: "common", Operator: v1.TolerationOpExists},
+	}
+	_, err = dsClient.Update(ctx, ds, metav1.UpdateOptions{})
+	if err != nil {
+		t.Fatalf("Failed to update DaemonSet: %v", err)
+	}
+	validateDaemonSetPodsAndMarkReady(podClient, podInformer, 4, t)
```
Comment (atiratree) [inline test/integration/daemonset/daemonset_test.go:1235]: we should first check that we have 6 pods with `validateDaemonSetPodsActive` and then mark our pods ready

File: test/integration/daemonset/daemonset_test.go [hunk 18]
```diff
@@ -1159,3 +1159,101 @@ func TestUpdateStatusDespitePodCreationFailure(t *testing.T) {
...
+	validateDaemonSetStatus(dsClient, ds.Name, 4, t)
```
Comment (atiratree) [inline test/integration/daemonset/daemonset_test.go:1236]: IMO we should also check `UpdatedNumberScheduled` 

Nit: and maybe `NumberAvailable` even though it is the same as `NumberReady` in our case.

File: test/integration/daemonset/daemonset_test.go [hunk 19]
```diff
@@ -1159,3 +1159,101 @@ func TestUpdateStatusDespitePodCreationFailure(t *testing.T) {
...
+
```
Comment (atiratree) [inline test/integration/daemonset/daemonset_test.go:1237]: then we could list all the pods and double check they have correct expected tolerations after each update

File: pkg/controller/daemon/update_test.go (hunk 14 above)
Comment (atiratree) [reply pkg/controller/daemon/update_test.go]: @mochizuki875 thanks for moving it to the integration tests

File: pkg/controller/daemon/update.go [hunk 20]
```diff
@@ -140,10 +140,12 @@ func (dsc *DaemonSetsController) rollingUpdate(ctx context.Context, ds *apps.Dae
 	// * An old available pod is deleted if a new pod is available
 	// * No more than maxSurge new pods are created for old available pods at any one time
 	//
-	var oldPodsToDelete []string
+	var oldPodsToDelete []string          // these pods are already updated
+	var shouldNotRunPodsToDelete []string // these pods should not be scheduled on anymore
 	var candidateNewNodes []string
 	var allowedNewNodes []string
 	var numSurge int
+	var isPodAvailable int
```
[the remark this answers is not in the document]
Comment (mochizuki875) [reply pkg/controller/daemon/update.go:148]: Oh sorry, I misunderstood the meaning of [this](https://github.com/kubernetes/kubernetes/pull/119317#discussion_r1304372023).

File: pkg/controller/daemon/update.go [hunk 21]
```diff
@@ -194,6 +239,18 @@ func (dsc *DaemonSetsController) rollingUpdate(ctx context.Context, ds *apps.Dae
...
 	remainingSurge := maxSurge - numSurge
+
+	// decide the deletable number of pods that should not be scheduled anymore
+	// if the number of available pods is greater than the number of pods desired, we adopt the difference
+	deletablePodsNumber := isPodAvailable - desiredNumberScheduled
+	if deletablePodsNumber > 0 {
+		if shouldNotRunPodsToDeleteNumber := len(shouldNotRunPodsToDelete); deletablePodsNumber > shouldNotRunPodsToDeleteNumber {
+			deletablePodsNumber = shouldNotRunPodsToDeleteNumber
+		}
+		logger.V(5).Info("DaemonSet pod should be deleted from the node as it is not schedulable anymore", "daemonset", klog.KObj(ds), "deletablePodsNumber", deletablePodsNumber)
```
[the remark this answers is not in the document]
Comment (mochizuki875) [reply pkg/controller/daemon/update.go:250]: @atiratree 
I'll add the check if `shouldNotRunPodsToDelete` is empty, but is that enough for `deletablePodsNumber`?

https://github.com/mochizuki875/kubernetes/blob/9e41a1fdb1f560726baa05cd425a7e273a79670d/pkg/controller/daemon/update.go#L243-L246

> I think we should also log in a similar format we do above. So best is to iterate over oldPodsToDelete and construct pod obj argument.

Do you mean we should newly emit log for `oldPodsToDelete` like that, after `shouldNotRunPodsToDelete[:deletablePodsNumber]` is appended to `oldPodsToDelete`?

```go
	for _, podToDeleteName := range oldPodsToDelete {
		podToDelete, err := dsc.podLister.Pods(ds.Namespace).Get(podToDeleteName)
		if err != nil {
			return fmt.Errorf("couldn't get pod for podToDelete %q: %v", podToDeleteName, err)
		}
		logger.V(0).Info("DaemonSet pod should be deleted", "daemonset", klog.KObj(ds), "podToDelete", klog.KObj(podToDelete))
	}
```

File: pkg/controller/daemon/update.go [hunk 22]
```diff
@@ -162,6 +176,22 @@ func (dsc *DaemonSetsController) rollingUpdate(ctx context.Context, ds *apps.Dae
...
 				// the old pod isn't available, allow it to become a replacement
 				logger.V(5).Info("Pod on node is out of date and not available, allowing replacement", "daemonset", klog.KObj(ds), "pod", klog.KObj(oldPod), "node", klog.KRef("", nodeName))
+
+				node, err := dsc.nodeLister.Get(nodeName)
+				if err != nil {
+					return fmt.Errorf("couldn't get node for nodeName %q: %v", nodeName, err)
+				}
+
+				shouldRun, _ := NodeShouldRunDaemonPod(node, ds)
+				if err != nil {
```
[the remark this answers is not in the document]
Comment (mochizuki875) [reply pkg/controller/daemon/update.go:186]: Sorry, it's my mistake.

File: test/integration/daemonset/daemonset_test.go (hunk 17 above)
Comment (mochizuki875) [reply test/integration/daemonset/daemonset_test.go:1235]: @atiratree 
OK, I'll add that check.

Isn't expected numberPods of `validateDaemonSetPodsActive` 4 when first create DaemonSet with zone-y and common toleration?
(2 pods are on Zone Y nodes, 2 pods are on Common nodes)

And I found that expected numberPods of `validateDaemonSetPodsActive` is 7 when update DaemonSet with zone-z and common toleration.

It's because: 
- daemon_controller `manage()` creates a pod on each node where it should run and dosen't exist, regardless of `maxSurge`.
  - New 2 pods are created and Pending on Zone Z nodes
- `remainingSurge` will be calculated based on schedulable nodes in `rollingUpdate`
  - New 1 pod are created as surge  and Pending on Zone Common node
  - Old 2 pods on Zone Common nodes will remain existing and Running 
- Pods that violate scheduling constraints will be removed in `rollingUpdate` when `numAvailable > desiredNumberScheduled` is met. 
  - Old 2 pods on Zone Y nodes will remain existing and Running until other new pods become available after `validateDaemonSetPodsAndMarkReady`

What do you think about that?

File: pkg/controller/daemon/update.go (hunk 21 above)
[the remark this answers is not in the document]
Comment (atiratree) [reply pkg/controller/daemon/update.go:250]: I was just mentioning the cases where it logs, no need to add additional checks.

And I made a mistake we should iterate over shouldNotRunPodsToDelete after we change its size since oldPodsToDelete are already logged before (except the `!shouldRun` we added in this PR which should log as well).

File: test/integration/daemonset/daemonset_test.go (hunk 17 above)
Comment (atiratree) [reply test/integration/daemonset/daemonset_test.go:1235]: yup 4 when we create and a good explanation that we will have 7pods when we update the daemon set. Maybe you can write a short comment explaining this in the code?

**Comment by mochizuki875** [comment]
@atiratree
OK, I've fixed.
Could you please check again?

File: test/integration/daemonset/daemonset_test.go (hunk 18 above)
Comment (mochizuki875) [reply test/integration/daemonset/daemonset_test.go:1299]: @atiratree 
In order to check `UpdatedNumberScheduled`, I tried implementing `validateUpdatedNumberScheduled` with reference to `validateDaemonSetStatus`.

However staticcheck error has occured in `pull-kubernetes-linter-hints` and `pull-kubernetes-verify-strict-lint`...
It seems to be caused by using `wait.Poll` which is deprecated.
So I've used `wait.PollUntilContextTimeout` instead.

**Comment by mochizuki875** [comment]
@atiratree 
OK, I've fixed.
Could you please check again?

File: test/integration/daemonset/daemonset_test.go (hunk 18 above)
Comment (atiratree) [reply test/integration/daemonset/daemonset_test.go:1299]: ack, looks fine

File: test/integration/daemonset/daemonset_test.go [hunk 23]
```diff
@@ -356,6 +356,42 @@ func validateDaemonSetPodsActive(
...
+			t.Errorf("Pod %s has %d OwnerReferences, expected only 1", pod.Name, len(ownerReferences))
+		}
+		controllerRef := ownerReferences[0]
+		if got, want := controllerRef.Kind, "DaemonSet"; got != want {
+			t.Errorf("controllerRef.Kind = %q, want %q", got, want)
+		}
+		if controllerRef.Controller == nil || *controllerRef.Controller != true {
+			t.Errorf("controllerRef.Controller is not set to true")
+		}
+		for _, dsToleration := range ds.Spec.Template.Spec.Tolerations {
```
[the remark this answers is not in the document]
Comment (mochizuki875) [reply test/integration/daemonset/daemonset_test.go:380]: @atiratree 
Sorry I couldn't come up with good idea.
Since pod tolerations includes tolerations other than daemonset tolerations(ex `node.kubernetes.io/not-ready`), I think we need to check sequentially whether pod tolerations includes each daemonset toleration.

File: pkg/controller/daemon/update.go [hunk 24]
```diff
@@ -194,6 +226,24 @@ func (dsc *DaemonSetsController) rollingUpdate(ctx context.Context, ds *apps.Dae
...
+	// With maxSurge, the application owner expects 100% availability.
+	// When the scheduling constraint change from node A to node B, we do not want the application to stay
+	// without any available pods. Only delete a pod on node A when a pod on node B becomes available.
+	if deletablePodsNumber := numAvailable - desiredNumberScheduled; deletablePodsNumber > 0 {
+		if shouldNotRunPodsToDeleteNumber := len(shouldNotRunPodsToDelete); deletablePodsNumber > shouldNotRunPodsToDeleteNumber {
+			deletablePodsNumber = shouldNotRunPodsToDeleteNumber
+		}
+		for _, podToDeleteName := range shouldNotRunPodsToDelete[:deletablePodsNumber] {
+			podToDelete, err := dsc.podLister.Pods(ds.Namespace).Get(podToDeleteName)
+			if err != nil {
```
[the remark this answers is not in the document]
Comment (mochizuki875) [reply pkg/controller/daemon/update.go:239]: Should we focus only not found error?
Now update will be interrupted by `return fmt.Errorf` if some error occurs when get pod.
However I think we should not stop update by error for specific pod, so I've fix to emit error log and skip the pod.

File: pkg/controller/daemon/update.go [hunk 25]
```diff
@@ -162,6 +176,15 @@ func (dsc *DaemonSetsController) rollingUpdate(ctx context.Context, ds *apps.Dae
 			case !podutil.IsPodAvailable(oldPod, ds.Spec.MinReadySeconds, metav1.Time{Time: now}):
 				// the old pod isn't available, allow it to become a replacement
 				logger.V(5).Info("Pod on node is out of date and not available, allowing replacement", "daemonset", klog.KObj(ds), "pod", klog.KObj(oldPod), "node", klog.KRef("", nodeName))
+
+				node, err := dsc.nodeLister.Get(nodeName)
+				if err != nil {
+					return fmt.Errorf("couldn't get node for nodeName %q: %v", nodeName, err)
```
Comment (mochizuki875) [inline pkg/controller/daemon/update.go:182]: @atiratree 
[The same reason](https://github.com/kubernetes/kubernetes/pull/119317/files#r1316715032) when get pod, I've changed to emitting log and skip the node instead of `fmt.Errorf`.

File: pkg/controller/daemon/update.go (hunk 24 above)
[the remark this answers is not in the document]
Comment (atiratree) [reply pkg/controller/daemon/update.go:240]: we should skip when getting a not found  error, but we should fail for any other error

File: pkg/controller/daemon/update.go [hunk 26]
```diff
@@ -153,13 +155,35 @@ func (dsc *DaemonSetsController) rollingUpdate(ctx context.Context, ds *apps.Dae
...
 		case oldPod == nil:
 			// we don't need to do anything to this node, the manage loop will handle it
 		case newPod == nil:
 			// this is a surge candidate
 			switch {
 			case !podutil.IsPodAvailable(oldPod, ds.Spec.MinReadySeconds, metav1.Time{Time: now}):
+				node, err := dsc.nodeLister.Get(nodeName)
+				if err != nil {
+					logger.Error(err, "Couldn't get node for nodeName", "nodeName", nodeName)
+					continue
```
Comment (atiratree) [inline pkg/controller/daemon/update.go:180]: I think we should fail with error as before in these 3 instances, because we cannot produce a good decision when we cannot obtain a node object. The error would cause this to retry a moment later when for example a network situation would improve and we would get the node.

File: test/integration/daemonset/daemonset_test.go [hunk 27]
```diff
@@ -1159,3 +1212,117 @@ func TestUpdateStatusDespitePodCreationFailure(t *testing.T) {
...
+		node = newNode(fmt.Sprintf("node-%d", i), nil)
+		node.Spec.Taints = taints
+		_, err := nodeClient.Create(context.TODO(), node, metav1.CreateOptions{})
+		if err != nil {
+			t.Fatalf("Failed to create node: %v", err)
+		}
+	}
+
+	// Create DaemonSet with zone-y toleration
+	ds.Spec.Template.Spec.Tolerations = []v1.Toleration{
```
Comment (atiratree) [inline test/integration/daemonset/daemonset_test.go:1266]: can we please first create a variable for these tolerations?

File: test/integration/daemonset/daemonset_test.go [hunk 28]
```diff
@@ -1159,3 +1212,117 @@ func TestUpdateStatusDespitePodCreationFailure(t *testing.T) {
...
+	_, err := dsClient.Create(ctx, ds, metav1.CreateOptions{})
+	if err != nil {
+		t.Fatalf("Failed to create DaemonSet: %v", err)
+	}
+	defer cleanupDaemonSets(t, clientset, ds)
+	validateDaemonSetPodsActive(podClient, podInformer, 4, t)
+	validateDaemonSetPodsAndMarkReady(podClient, podInformer, 4, t)
+	validateDaemonSetStatus(dsClient, ds.Name, 4, t)
+	validateUpdatedNumberScheduled(ctx, dsClient, ds.Name, 4, t)
+	validateDaemonSetPodsTolerations(podClient, podInformer, ds.Spec.Template.Spec.Tolerations, t)
```
Comment (atiratree) [inline test/integration/daemonset/daemonset_test.go:1279]: and reference the variable here? So we do not have to mentally track what happened meanwhile to the DS object and can be sure what tolerations we are expecting.

File: test/integration/daemonset/daemonset_test.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (atiratree) [reply test/integration/daemonset/daemonset_test.go]: hm, I see. The problem with current solution is, that you cannot ask if it is missing some tolerations. I am seeing two possible solutions:
1. pass a test prefix and prefix all your tolerations with it. Then filter all tolerations with this prefix.
2. filter out all tolerations with `node.kubernetes.io` prefix and test no expected tolerations have it.

@mochizuki875 what do you think about these options?

File: pkg/controller/daemon/update.go (hunk 25 above)
Comment (atiratree) [reply pkg/controller/daemon/update.go]: I think it is preferable to keep the errors: please see https://github.com/kubernetes/kubernetes/pull/119317#discussion_r1320206492

File: pkg/controller/daemon/update.go (hunk 26 above)
Comment (mochizuki875) [reply pkg/controller/daemon/update.go:180]: Thanks, I'll let it fail as before.

File: test/integration/daemonset/daemonset_test.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (mochizuki875) [reply test/integration/daemonset/daemonset_test.go]: > that you cannot ask if it is missing some tolerations

@atiratree 
Sorry, I can't understand current problem...
I understand that the purpose is to ensure that all DaemonSet tolerations are granted to the daemon pods.
Now, we check whether `expectedTolerations` are included in daemon pods or not as below:

```go
		for _, expectedToleration := range expectedTolerations {
			isMatchToleration = false
			for _, podToleration := range pod.Spec.Tolerations {
				if expectedToleration == podToleration {
					isMatchToleration = true
					break
				}
			}
			if !isMatchToleration {
				t.Fatalf("Expected toleration of daemon pod(%s) includes %v, but found %v\n", pod.Name, expectedToleration, pod.Spec.Tolerations)
			}
		}
```

So I think we can check missing tolerations of daemon pod for `expectedTolerations`.
For example, in that case like `expectedTolerations` are not included daemon pods, test will fail and emit log.

```
DaemonSet toleration(expectedTolerations)
  Key: "zone-y", Operator: v1.TolerationOpExists
  Key: "common", Operator: v1.TolerationOpExists

daemon pod toleration
  Key: "common", Operator: v1.TolerationOpExists
```

Example of fail log:
```
daemonset_test.go:389: Expected toleration of daemon pod(foo-hr4wv) includes {zone-y Exists   <nil>}, but found [{common Exists   <nil>} {node.kubernetes.io/not-ready Exists  NoExecute <nil>} {node.kubernetes.io/unreachable Exists  NoExecute <nil>} {node.kubernetes.io/disk-pressure Exists  NoSchedule <nil>} {node.kubernetes.io/memory-pressure Exists  NoSchedule <nil>} {node.kubernetes.io/pid-pressure Exists  NoSchedule <nil>} {node.kubernetes.io/unschedulable Exists  NoSchedule <nil>}]
```

Is this not enough?

[the remark this answers is not in the document]
Comment (mochizuki875) [reply test/integration/daemonset/daemonset_test.go]: > that you cannot ask if it is missing some tolerations

@atiratree 
I understand the purpose is: 

1. Ensure that all DaemonSet tolerations are granted to the daemon pods 
2. Emit all missing tolerations as fail log if there are

Now, we can check whether `expectedTolerations` are included in daemon pods or not.
However, we can't emit all missing tolerations as fail log.

For example, in that case like `expectedTolerations` are not included daemon pods, test will fail and only one of missing tolerations is emitted as fail log.
```
DaemonSet toleration(expectedTolerations)
  Key: "zone-y", Operator: v1.TolerationOpExists
  Key: "zone-z", Operator: v1.TolerationOpExists
  Key: "common", Operator: v1.TolerationOpExists

daemon pod toleration
  Key: "common", Operator: v1.TolerationOpExists
```

Example of fail log:
(`{zone-z Exists   <nil>}` also should be emitted, but not)
```
daemonset_test.go:395: Expected toleration of daemon pod(foo-cqmj5) includes [{zone-y Exists   <nil>}], but found [{common Exists   <nil>} {node.kubernetes.io/not-ready Exists  NoExecute <nil>} {node.kubernetes.io/unreachable Exists  NoExecute <nil>} {node.kubernetes.io/disk-pressure Exists  NoSchedule <nil>} {node.kubernetes.io/memory-pressure Exists  NoSchedule <nil>} {node.kubernetes.io/pid-pressure Exists  NoSchedule <nil>} {node.kubernetes.io/unschedulable Exists  NoSchedule <nil>}]
```

So I've fixed to emit all missing tolerations as fail log like that.
```
daemonset_test.go:395: Expected toleration of daemon pod(foo-cqmj5) includes [{zone-y Exists   <nil>} {zone-z Exists   <nil>}], but found [{common Exists   <nil>} {node.kubernetes.io/not-ready Exists  NoExecute <nil>} {node.kubernetes.io/unreachable Exists  NoExecute <nil>} {node.kubernetes.io/disk-pressure Exists  NoSchedule <nil>} {node.kubernetes.io/memory-pressure Exists  NoSchedule <nil>} {node.kubernetes.io/pid-pressure Exists  NoSchedule <nil>} {node.kubernetes.io/unschedulable Exists  NoSchedule <nil>}]
```

How about that?

**Comment by mochizuki875** [comment]
@atiratree
Could you please check again?

File: test/integration/daemonset/daemonset_test.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (atiratree) [reply test/integration/daemonset/daemonset_test.go]: yes that is the main purpose, but we would like to also check that the following example also fails

```
DaemonSet toleration(expectedTolerations)
  Key: "zone-z", Operator: v1.TolerationOpExists
  Key: "common", Operator: v1.TolerationOpExists

daemon pod toleration
  Key: "zone-y", Operator: v1.TolerationOpExists
  Key: "zone-z", Operator: v1.TolerationOpExists
  Key: "common", Operator: v1.TolerationOpExists
```

This has an extra benefit that it will simplify the `validateDaemonSetPodsTolerations` function by using  cmp.diff or DeepEqual

**Review by atiratree — COMMENTED** [review]
@mochizuki875 two nits, but otherwise LGTM

File: pkg/controller/daemon/update.go [hunk 29]
```diff
@@ -171,6 +194,14 @@ func (dsc *DaemonSetsController) rollingUpdate(ctx context.Context, ds *apps.Dae
 				// no point considering any other candidates
```
Comment (atiratree) [inline pkg/controller/daemon/update.go:194]: hm, just noticed one thing: we should move this `numSurge >= maxSurge` check after the `!shouldRun` check bellow, since sunsetting nodes is not dependent on it and we can delete pods sooner

Comment (mochizuki875) [reply pkg/controller/daemon/update.go:194]: I think it makes sense, so I'll fix it.

File: test/integration/daemonset/daemonset_test.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (mochizuki875) [reply test/integration/daemonset/daemonset_test.go]: @atiratree 
OK, so I've taken your first idea and changed `validateDaemonSetPodsTolerations`.

> 1. pass a test prefix and prefix all your tolerations with it. Then filter all tolerations with this prefix.

**Comment by mochizuki875** [comment]
@atiratree 
I've reflected on your 3 comments and rebased old commits.

File: test/integration/daemonset/daemonset_test.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (atiratree) [reply test/integration/daemonset/daemonset_test.go]: great, thanks

File: pkg/controller/daemon/update.go [hunk 30]
```diff
@@ -153,24 +155,54 @@ func (dsc *DaemonSetsController) rollingUpdate(ctx context.Context, ds *apps.Dae
...
 		case newPod == nil:
 			// this is a surge candidate
 			switch {
 			case !podutil.IsPodAvailable(oldPod, ds.Spec.MinReadySeconds, metav1.Time{Time: now}):
+				node, err := dsc.nodeLister.Get(nodeName)
+				if err != nil {
+					return fmt.Errorf("couldn't get node for nodeName %q: %v", nodeName, err)
+				}
+				if shouldRun, _ := NodeShouldRunDaemonPod(node, ds); !shouldRun {
+					logger.V(5).Info("DaemonSet pod on node is not available and dose not match scheduling constraints, remove old pod", "daemonset", klog.KObj(ds), "node", nodeName, "oldPod", klog.KObj(oldPod))
```
Comment (soltysh) [inline pkg/controller/daemon/update.go:182]:
```suggestion
					logger.V(5).Info("DaemonSet pod on node is not available and does not match scheduling constraints, remove old pod", "daemonset", klog.KObj(ds), "node", nodeName, "oldPod", klog.KObj(oldPod))
```

**Review by soltysh — APPROVED** [review]
One nit, @atiratree has final tag
/assign @atiratree

File: pkg/controller/daemon/update.go (hunk 30 above)
Comment (mochizuki875) [reply pkg/controller/daemon/update.go]: @soltysh 
Sorry, it's a typo and I've fixed it.
Thanks!

**Comment by atiratree** [comment]
thanks for the work on the PR
/lgtm

**Comment by mochizuki875** [comment]
@atiratree 
I appreciate your many many advises and helps!

**Comment by atiratree** [comment]
@mochizuki875 would you mind cherry-picking this into 1.28, 1.27, 1.26 ,1.25? We have promoted the maxSurge feature to GA in 1.25 so it would be great to get the backports into all of these versions (https://github.com/kubernetes/kubernetes/pull/111194).

**Comment by mochizuki875** [comment]
@atiratree 
Thank you for your notification!
I'll do it:)

**Comment by atiratree** [comment]
thanks!

**Comment by mochizuki875** [comment]
- [x] v1.28: #120785
- [x] v1.27: #120786
- [ ] v1.26: WIP
- [ ] v1.25: WIP

**Comment by mochizuki875** [comment]
@atiratree 
OK, I've created PR for cherry-picking into four versions.

**Comment by atiratree** [comment]
thanks, let's wait for the tests and then we can tag them

**Comment by sftim** [comment]
Changelog suggestion
```markdown
Revised the logic for DaemonSet rolling update to exclude nodes if scheduling constraints are not met.
This eliminates the problem of rolling updates to a DaemonSet getting stuck around tolerations.
```

Further polish is welcome; I don't think I really understand the effect of the change from the current changelog entry.

**Comment by fsmunoz** [comment]
@sftim I'm picking your suggestion for the `alpha.1` draft PR, I was having some difficulties as well.

**Comment by mochizuki875** [comment]
@sftim 
Thank you for your suggestion!
That's make sense and I've fit it.
