### PR TITLE
kubeadm: the '--feature-gates' flag is deprecated and no-op for 'kubeadm upgrade apply/plan'

### LINKED ISSUE #3084: "can not mix '--config' with arguments" common issues about v1beta4 UpgradeConfiguration
When I try to upgrade the cluster using `kubeadm upgrade apply/plan --config upgrade.yaml` (master branch latest code), many flags can not be mixed but are not defined in the config file.

For example, an error will occur when you execute this command `kubeadm upgrade apply v1.30.0 --config upgrade.yaml --feature-gates EtcdLearnerMode=true`
```
can not mix '--config' with arguments [feature-gates]
To see the stack trace of this error execute with --v=5 or higher
```

Other commands and flags may have similar problems that must be checked carefully.

 I create this issue to discuss a solution. 

There are two ways to handle this:
1. Add these parameters to the corresponding config struct (`UpgradeConfiguration`)
2. Allow mixed use of these flags with `--config`

what do you think？@neolit123 @pacoxu 

We'd better fix this issue before the new version is released to reduce  the problems introduced by `v1beta4`

Similar with: https://github.com/kubernetes/kubernetes/pull/125779

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind bug
/kind cleanup

#### What this PR does / why we need it:
1. the `--feature-gates` flag is deprecated and no-op for `kubeadm upgrade apply/plan`
2. fix the bug that `--feature-gates` can not be mixed with `--config` for `kubeadm upgrade apply/plan` (not break user scripts in v1.31)
3. fix the bug that `--allow-missing-template-keys`, `--output` and `--show-managed-fields` can not be mixed with `--config` for `kubeadm upgrade plan`

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/3084

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: the `--feature-gates` flag is deprecated and no-op for `kubeadm upgrade apply/plan`, and it will be removed in a future release. The upgrade workflow is not designed to reconfigure the cluster. Please edit the 'featureGates' field of ClusterConfiguration which is defined in the kube-system/kubeadm-config ConfigMap instead.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/apis/kubeadm/validation/validation.go [hunk 1]
```diff
@@ -609,7 +609,9 @@ func isAllowedFlag(flagName string) bool {
 		kubeadmcmdoptions.NodeName,
 		kubeadmcmdoptions.KubeconfigDir,
 		kubeadmcmdoptions.UploadCerts,
+		kubeadmcmdoptions.FeatureGatesString,                                       // TODO: remove this line when --feature-gates flag is deprecated and dropped from "kubeadm upgrade apply/plan"
```
Comment (neolit123) [inline cmd/kubeadm/app/apis/kubeadm/validation/validation.go:612]: i think we should disable the flag too. i.e. if the user passes it, it should not do anything.
this aligns with the deprecation in 1.30 to not allow clusterconfig on upgrade.

File: cmd/kubeadm/app/cmd/upgrade/upgrade.go [hunk 2]
```diff
@@ -72,5 +75,7 @@ func addApplyPlanFlags(fs *pflag.FlagSet, flags *applyPlanFlags) {
 	fs.BoolVar(&flags.allowRCUpgrades, "allow-release-candidate-upgrades", flags.allowRCUpgrades, "Show release candidate versions of Kubernetes as an upgrade alternative and allow upgrading to a release candidate versions of Kubernetes.")
 	fs.BoolVar(&flags.printConfig, "print-config", flags.printConfig, "Specifies whether the configuration file that will be used in the upgrade should be printed or not.")
 	options.AddFeatureGatesStringFlag(fs, &flags.featureGatesString)
+	_ = fs.MarkDeprecated(options.FeatureGatesString, fmt.Sprintf("This flag is deprecated and will be removed in a future release. The upgrade workflow is not designed for reconfigure the cluster. "+
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/upgrade/upgrade.go:78]: if you agree with my prev comment we should also make this flag a no-op and mention that in the deprecation message.

we can remove it in the next release.
wuth the idea to not break user scripts right away.

Comment (neolit123) [reply cmd/kubeadm/app/cmd/upgrade/upgrade.go:78]: if you agree with the no-op part we should reflect it in the release note.

File: cmd/kubeadm/app/apis/kubeadm/validation/validation.go (hunk 1 above)
Comment (SataQiu) [reply cmd/kubeadm/app/apis/kubeadm/validation/validation.go:612]: It's no-op now. But we should not break user scripts, so just allow passing this flag with --config in v1.31, and remove it in v1.32

File: cmd/kubeadm/app/cmd/upgrade/upgrade.go (hunk 2 above)
Comment (SataQiu) [reply cmd/kubeadm/app/cmd/upgrade/upgrade.go]: Done

File: cmd/kubeadm/app/apis/kubeadm/validation/validation.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/apis/kubeadm/validation/validation.go:612]: agreed

**Review by neolit123 — COMMENTED** [review]
/triage accepted
/lgtm
/approve

thanks @SataQiu for fixing these problems.
