### PR TITLE
Use start times kubelet startup

### LINKED ISSUE #59524: Incorrect start times can cause heapster to not have CPU stats
/kind bug
/sig node
/priority important-soon

When HPA is supposed to upscale it is intermittently unable to calculate the number of desired replicas because of missing metrics
`$ kubectl describe hpa <hpa-name>`
`  3d            29s             80      horizontal-pod-autoscaler                       Warning         FailedGetResourceMetric         unable to get metrics for resource cpu: no metrics returned from heapster`
`  3d            29s             80      horizontal-pod-autoscaler                       Warning         FailedComputeMetricsReplicas    failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from heapster`

The kubelet was returning an invalid Start time for pods, containers, and the node:
`"podRef": {`
` "uid": "7efbdb50-0830-11e8-9e01-42010af0001e"`
`},`
`"startTime": "2018-02-07T09:53:05Z",`
`"containers": [`
`{`
` "startTime": "2018-02-07T09:53:05Z",`
` "cpu": {`
`  "time": "2018-02-07T09:53:03Z",`
` },`
` "memory": {`
`  "time": "2018-02-07T09:53:03Z",`
` },`
` "rootfs": {`
 `"time": "2018-02-07T09:53:03Z",`
 `},`
 `"logs": {`
 ` "time": "2018-02-07T09:53:03Z",`
 `},`
`},`

Here is the Heapster code that computes cpu usage rate (this is the metric for HPA): https://github.com/kubernetes/heapster/blob/release-1.4/metrics/processors/rate_calculator.go, which requires that the current and previous batch have the same start time.  A start time which changes often results in very few cpu metrics for heapster.

When cadvisor calculates the start time, it looks at the last time `cgroup.clone_children` was modified. https://github.com/google/cadvisor/blob/master/container/common/helpers.go#L56
This is an estimate, at best.  We recently changed cAdvisor to use docker's container creation time: https://github.com/google/cadvisor/pull/1806.
But we still need to get a real Pod, Node and system container Start time.

### PR DESCRIPTION
**Pull request by dashpole**
**What this PR does / why we need it**:
See the issue for why this is needed

It uses the time of the initialization of the stats provider as the kubelet's start time, and uses the boot time, obtained from the kernel as the node's start time.

**Which issue(s) this PR fixes**:
Fixes #59524

**Release note**:
```release-note
Fix bug in the Kubelet Summary API where the kubelet, or node start time could randomly reset.
```

/sig node
/kind bug
/priority important-soon

### CODE REVIEW

**Comment by yujuhong** [comment]
Are container start times also affected, and does this PR fix that?

**Comment by dashpole** [comment]
Those are fixed in https://github.com/google/cadvisor/pull/1806

**Comment by dashpole** [comment]
/close
for now

**Comment by filbranden** [comment]
LGTM, I think this is probably a better approach.

**Comment by dashpole** [comment]
This uses the LastTransitionTime of the pod's PodScheduled condition as the pod start time.  The kubelet updates the last transition time when it performs the first status update for a pod, which should be roughly the same time as the pod's cgroup is created.  The pod's cgroup is created only once during the pod's lifecycle, so it makes sense to use a condition that transitions to true only once.

It uses the time of the initialization of the stats provider as the kubelet's start time, and uses the boot time, obtained from the kernel as the node's start time.

File: pkg/kubelet/server/stats/summary.go [hunk 1]
```diff
@@ -40,7 +48,19 @@ var _ SummaryProvider = &summaryProviderImpl{}
 // NewSummaryProvider returns a SummaryProvider using the stats provided by the
 // specified statsProvider.
 func NewSummaryProvider(statsProvider StatsProvider) SummaryProvider {
-	return &summaryProviderImpl{statsProvider}
+	kubeletCreationTime := metav1.Now()
+	bootTime, err := util.GetBootTime()
+	if err != nil {
+		glog.Warningf("Error getting system boot time.  Node metrics will have an incorrect start time: %v", err)
+	}
+	// truncate bootTime to the second so it does not change when the kubelet restarts
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/server/stats/summary.go]: The uptime reported by the kernel is in seconds.  Time.Now() that we use as the kubelet start time has nanosecond precision.  We also collect the current time, and kernel uptime at different times, so there is likely a small difference between the measured "boot time" each time it is called because of nanosecond differences.

File: pkg/kubelet/util/util_unsupported.go [hunk 2]
```diff
@@ -40,3 +40,7 @@ func LockAndCheckSubPath(volumePath, subPath string) ([]uintptr, error) {
 // UnlockPath empty implementation
 func UnlockPath(fileHandles []uintptr) {
 }
+
+func GetBootTime() (time.Time, error) {
+	return time.Now(), fmt.Errorf("GetBootTime is unsupported in this build")
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/util/util_unsupported.go]: done

File: pkg/kubelet/stats/cadvisor_stats_provider.go [hunk 3]
```diff
@@ -374,3 +395,11 @@ func getCadvisorContainerInfo(ca cadvisor.Interface) (map[string]cadvisorapiv2.C
 	}
 	return infos, nil
 }
+
+func podMap(pods []*v1.Pod) map[string]*v1.Pod {
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/stats/cadvisor_stats_provider.go]: removed.

File: pkg/kubelet/stats/cadvisor_stats_provider.go [hunk 4]
```diff
@@ -114,7 +125,17 @@ func (p *cadvisorStatsProvider) ListPodStats() ([]statsapi.PodStats, error) {
...
 			podStats.Network = cadvisorInfoToNetworkStats("pod:"+ref.Namespace+"_"+ref.Name, &cinfo)
-			podStats.StartTime = metav1.NewTime(cinfo.Spec.CreationTime)
+			var startTime metav1.Time
+			for _, condition := range podStatus.Conditions {
+				if condition.Type == v1.PodScheduled && condition.Status == v1.ConditionTrue {
+					startTime = condition.LastTransitionTime
+				}
+			}
+			if startTime.IsZero() {
+				continue
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/stats/cadvisor_stats_provider.go]: added a log statement.

File: pkg/kubelet/stats/cadvisor_stats_provider.go [hunk 5]
```diff
@@ -114,7 +125,17 @@ func (p *cadvisorStatsProvider) ListPodStats() ([]statsapi.PodStats, error) {
 			// Special case for infrastructure container which is hidden from
 			// the user and has network stats.
 			podStats.Network = cadvisorInfoToNetworkStats("pod:"+ref.Namespace+"_"+ref.Name, &cinfo)
-			podStats.StartTime = metav1.NewTime(cinfo.Spec.CreationTime)
+			var startTime metav1.Time
+			for _, condition := range podStatus.Conditions {
+				if condition.Type == v1.PodScheduled && condition.Status == v1.ConditionTrue {
+					startTime = condition.LastTransitionTime
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/stats/cadvisor_stats_provider.go]: done

File: pkg/kubelet/stats/cadvisor_stats_provider.go [hunk 6]
```diff
@@ -47,6 +49,8 @@ type cadvisorStatsProvider struct {
 	resourceAnalyzer stats.ResourceAnalyzer
 	// imageService is used to get the stats of the image filesystem.
 	imageService kubecontainer.ImageService
+	// podManager is used to get pod metadata
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/stats/cadvisor_stats_provider.go]: done

File: pkg/kubelet/server/stats/summary.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (yguo0905) [reply pkg/kubelet/server/stats/summary.go]: I see. Maybe put this logic into GetBootTime()? I think it's natural for the caller to expect GetBootTime() to consistently return boot time with second precision.

[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/server/stats/summary.go]: done

File: pkg/kubelet/util/util_darwin.go [hunk 7]
```diff
@@ -0,0 +1,96 @@
...
+	"github.com/golang/glog"
+	"golang.org/x/sys/unix"
+)
+
+const (
+	// unixProtocol is the network protocol of unix socket.
+	unixProtocol = "unix"
+)
+
+func CreateListener(endpoint string) (net.Listener, error) {
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/util/util_darwin.go]: Moved to their own files.

**Comment by dashpole** [comment]
@yguo0905 I have addressed your comments.

File: pkg/kubelet/util/util_windows.go [hunk 8]
```diff
@@ -55,3 +56,15 @@ func GetAddressAndDialer(endpoint string) (string, func(addr string, timeout tim
...
 }
+
+var tickCount = syscall.NewLazyDLL("kernel32.dll").NewProc("GetTickCount64")
+
+// GetBootTime returns the time at which the machine was started, truncated to the nearest second
+func GetBootTime() (time.Time, error) {
+	currentTime := time.Now()
+	output, _, err := tickCount.Call()
+	if errno, ok := err.(syscall.Errno); !ok || errno != 0 {
+		return currentTime, err
```
Comment (yujuhong) [inline pkg/kubelet/util/util_windows.go]: Why returning the currentTime as the boot time on error?

File: pkg/kubelet/util/boottime_util_linux.go [hunk 9]
```diff
@@ -0,0 +1,36 @@
...
+
+	"golang.org/x/sys/unix"
+)
+
+// GetBootTime returns the time at which the machine was started, truncated to the nearest second
+func GetBootTime() (time.Time, error) {
+	currentTime := time.Now()
+	var info unix.Sysinfo_t
+	if err := unix.Sysinfo(&info); err != nil {
+		return currentTime, fmt.Errorf("Error getting system uptime: %s", err)
```
Comment (yujuhong) [inline pkg/kubelet/util/boottime_util_linux.go]: s/Error/error

Comment (yujuhong) [reply pkg/kubelet/util/boottime_util_linux.go]: Why returning the currentTime as the boot time on error?

File: pkg/kubelet/stats/cadvisor_stats_provider.go [hunk 10]
```diff
@@ -114,7 +125,19 @@ func (p *cadvisorStatsProvider) ListPodStats() ([]statsapi.PodStats, error) {
...
+				if condition.Type == v1.PodScheduled && condition.Status == v1.ConditionTrue {
+					startTime = condition.LastTransitionTime
+					break
+				}
+			}
+			if startTime.IsZero() {
+				glog.V(3).Infof("Unable to find the start time for pod: %+v", ref)
+				continue
+			} else {
+				podStats.StartTime = startTime
```
Comment (yujuhong) [inline pkg/kubelet/stats/cadvisor_stats_provider.go]: Don't need the `else` since you already have `continue` in line 137

**Review by yujuhong — COMMENTED** [review]
Talked to @dashpole offline.

The PR should work today, but there are a few caveats using the PodScheduled condition as the pod start time:

 * Scheduler sets that condition in most cases. There could be a long gap between the "scheduled" condition and the actual start time.
  *  Kubelet only sets the condition for pods that did not go through the scheduler (e.g., static pod, pods with pre-assigned node, etc) when it tries to update the status. The timestamp depends on when kubelet sends the first status update for the pod, which is an implementation detail that may change.

I'm okay with the PR since it fixes the issue today; we can always iterate and improve later. I'd suggest adding a test to catch regression if we decide to rely upon this condition.

File: pkg/kubelet/util/util_windows.go (hunk 8 above)
Comment (dashpole) [reply pkg/kubelet/util/util_windows.go]: Discussed offline.  Returning time.Time{} (the zero time) seems like the most obvious way to fail here.

File: pkg/kubelet/util/boottime_util_linux.go (hunk 9 above)
Comment (dashpole) [reply pkg/kubelet/util/boottime_util_linux.go]: done

File: pkg/kubelet/stats/cadvisor_stats_provider.go (hunk 10 above)
Comment (dashpole) [reply pkg/kubelet/stats/cadvisor_stats_provider.go]: done

**Comment by dashpole** [comment]
I removed the pod start time changes from this PR.  Ill fix those in a different PR, and hopefully find a better way than using the PodScheduled time.

**Comment by dims** [comment]
@dashpole do we need this for 1.12?

File: pkg/kubelet/util/util_windows.go [hunk 11]
```diff
@@ -112,3 +113,15 @@ func LocalEndpoint(path, file string) string {
 	}
 	return u.String() + "//./pipe/" + file
 }
+
+var tickCount = syscall.NewLazyDLL("kernel32.dll").NewProc("GetTickCount64")
+
+// GetBootTime returns the time at which the machine was started, truncated to the nearest second
+func GetBootTime() (time.Time, error) {
```
Comment (yujuhong) [inline pkg/kubelet/util/util_windows.go]: /cc @kubernetes/sig-windows-misc

**Review by yujuhong — COMMENTED** [review]
Looks good with some nits

File: pkg/kubelet/server/stats/summary.go [hunk 12]
```diff
@@ -40,7 +49,17 @@ var _ SummaryProvider = &summaryProviderImpl{}
 // NewSummaryProvider returns a SummaryProvider using the stats provided by the
 // specified statsProvider.
 func NewSummaryProvider(statsProvider StatsProvider) SummaryProvider {
-	return &summaryProviderImpl{statsProvider}
+	kubeletCreationTime := metav1.Now()
+	bootTime, err := util.GetBootTime()
+	if err != nil {
+		klog.Warningf("Error getting system boot time.  Node metrics will have an incorrect start time: %v", err)
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/server/stats/summary.go]: done

File: pkg/kubelet/server/stats/summary_sys_containers.go [hunk 13]
```diff
@@ -48,6 +50,9 @@ func (sp *summaryProviderImpl) GetSystemContainersStats(nodeConfig cm.NodeConfig
 		// System containers don't have a filesystem associated with them.
 		s.Logs, s.Rootfs = nil, nil
 		s.Name = sys
+		if !cont.startTime.IsZero() {
```
[the remark this answers is not in the document]
Comment (dashpole) [reply pkg/kubelet/server/stats/summary_sys_containers.go]: done

File: pkg/kubelet/util/util_windows.go (hunk 11 above)
Comment (feiskyer) [reply pkg/kubelet/util/util_windows.go]: cc @PatrickLang

File: pkg/kubelet/util/boottime_util_darwin.go [hunk 14]
```diff
@@ -0,0 +1,44 @@
...
+	"syscall"
+	"time"
+	"unsafe"
+
+	"golang.org/x/sys/unix"
+)
+
+// GetBootTime returns the time at which the machine was started, truncated to the nearest second
+func GetBootTime() (time.Time, error) {
+	output, err := unix.SysctlRaw("kern.boottime")
```
Comment (michmike) [inline pkg/kubelet/util/boottime_util_darwin.go]: does this call work on windows as well?

File: pkg/kubelet/util/util_windows.go (hunk 11 above)
Comment (michmike) [reply pkg/kubelet/util/util_windows.go]: @alinbalutoiu  can you also please take a look. the code looks good at a high level

Comment (alinbalutoiu) [reply pkg/kubelet/util/util_windows.go]: @michmike looks good to me, it is working fine as well.

Comment (michmike) [reply pkg/kubelet/util/util_windows.go]: excellent. thank you!
