### PR TITLE
Emit correct event when unbound delay binding claim is used by pod

### LINKED ISSUE #88229: No details given on PVC when WaitForFirstConsumer binding fails
**What happened**:
With a StorageClass with `volumeBindingMode= WaitForFirstConsumer`, it's not clear why a PVC is not bound when there is no available PV.

On Pod, there is a  clear event what's wrong:
```
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.
```

On the PVC side we get only this event:
```
  Type    Reason                Age                 From                         Message
  ----    ------                ----                ----                         -------
  Normal  WaitForFirstConsumer  2s (x26 over 6m4s)  persistentvolume-controller  waiting for first consumer to be created before binding
```

Note that the message says "waiting for first consumer'. But the pod already exists. The reason why it's not bound yet is that the StorageClass has no dynamic provisioning configured (`provisioner: kubernetes.io/no-provisioner`) and there are no free PVs to satisfy the claim.

**What you expected to happen**:
An event "1 node(s) didn't find available persistent volumes to bind" on the PVC.

### PR DESCRIPTION
**Pull request by cofyc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #88229 

**Special notes for your reviewer**:

examples: 

1, one pod

```
Events:
  Type    Reason                Age                From                         Message
  ----    ------                ----               ----                         -------
  Normal  WaitForFirstConsumer  20s (x6 over 87s)  persistentvolume-controller  waiting for first consumer to be created before binding
  Normal  WaitForPodScheduled        5s                 persistentvolume-controller  waiting for pod pod-0 to be scheduled
```

2, two pods

```
Events:
  Type    Reason                Age                  From                         Message
  ----    ------                ----                 ----                         -------
  Normal  WaitForFirstConsumer  92s (x6 over 2m39s)  persistentvolume-controller  waiting for first consumer to be created before binding
  Normal  WaitForPodScheduled        17s (x5 over 77s)    persistentvolume-controller  waiting for pod pod-0 to be scheduled
  Normal  WaitForPodScheduled        2s                   persistentvolume-controller  waiting for pods pod-1,pod-0 to be scheduled
```

**Does this PR introduce a user-facing change?**:

```release-note
Emit `WaitingForPodScheduled` event if the unbound PVC is in delay binding mode but used by a pod
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/controller/volume/persistentvolume/pv_controller_base.go [hunk 1]
```diff
@@ -126,10 +127,19 @@ func NewController(p ControllerParameters) (*PersistentVolumeController, error)
...
 	controller.podListerSynced = p.PodInformer.Informer().HasSynced
 	controller.NodeLister = p.NodeInformer.Lister()
 	controller.NodeListerSynced = p.NodeInformer.Informer().HasSynced
 
+	// This custom indexer will index pods by its PVC keys. Then we don't need
+	// to iterate all pods every time to find pods which reference given PVC.
+	if err := controller.podIndexer.AddIndexers(cache.Indexers{
+		pvcKeyIndex: indexByPVCKey,
+	}); err != nil {
+		klog.Warningf("adding indexer got %v", err)
```
Comment (jsafrane) [inline pkg/controller/volume/persistentvolume/pv_controller_base.go:140]: Why is the error not propagated to the caller?

File: pkg/controller/volume/persistentvolume/pv_controller.go [hunk 2]
```diff
@@ -320,7 +320,25 @@ func (ctrl *PersistentVolumeController) syncUnboundClaim(claim *v1.PersistentVol
 			// OBSERVATION: pvc is "Pending", will retry
 			switch {
 			case delayBinding && !pvutil.IsDelayBindingProvisioning(claim):
-				ctrl.eventRecorder.Event(claim, v1.EventTypeNormal, events.WaitForFirstConsumer, "waiting for first consumer to be created before binding")
+				reason := events.WaitForFirstConsumer
```
Comment (jsafrane) [inline pkg/controller/volume/persistentvolume/pv_controller.go:323]: Please put the eventing logic into a separate method, so syncUnboundClaim contains only the important if-then-else branches.

File: pkg/controller/volume/persistentvolume/pv_controller.go [hunk 3]
```diff
@@ -320,7 +320,25 @@ func (ctrl *PersistentVolumeController) syncUnboundClaim(claim *v1.PersistentVol
...
+					return err
+				}
+				if len(podNames) > 0 {
+					reason = events.BindingWithPod
+					if len(podNames) > 1 {
+						// Although only one pod is taken into account in
+						// volume scheduling, more than one pods can reference
+						// the PVC at the same time. We can't know which pod is
+						// used in scheduling, all pods are included.
+						message = fmt.Sprintf("binding with pods %s", strings.Join(podNames, ","))
```
Comment (jsafrane) [inline pkg/controller/volume/persistentvolume/pv_controller.go:336]: The message is not clear to me. User sees this:
```
waiting for first consumer to be created before binding
binding with the pod pod-0
```
And the PVC is still unbound. What is the PVC waiting for?

IMO, something like this would be more informative: "waiting for pod X to be scheduled".

File: pkg/controller/volume/persistentvolume/pv_controller_base.go (hunk 1 above)
Comment (cofyc) [reply pkg/controller/volume/persistentvolume/pv_controller_base.go]: I copied this snippet of code from ADC. The error wouldn't happen in practice but it makes code smell better if we propagate the error to the caller. I'll fix this.

File: pkg/controller/volume/persistentvolume/pv_controller.go (hunk 2 above)
Comment (cofyc) [reply pkg/controller/volume/persistentvolume/pv_controller.go]: done

File: pkg/controller/volume/persistentvolume/pv_controller.go (hunk 3 above)
Comment (cofyc) [reply pkg/controller/volume/persistentvolume/pv_controller.go]: it makes sense

Comment (cofyc) [reply pkg/controller/volume/persistentvolume/pv_controller.go]: I've also renamed the reason `BindingWithPod` to 'WaitingForPodScheduled`. The pod may be stuck in the scheduling queue for some reason. It's more correct to say the PVC is waiting for the Pod to be scheduled.

**Comment by jsafrane** [comment]
@msau42, any opinion? It looks good to me.

File: pkg/controller/volume/events/event.go [hunk 4]
```diff
@@ -30,5 +30,6 @@ const (
 	ProvisioningCleanupFailed = "ProvisioningCleanupFailed"
 	ProvisioningSucceeded     = "ProvisioningSucceeded"
 	WaitForFirstConsumer      = "WaitForFirstConsumer"
```
Comment (msau42) [inline pkg/controller/volume/events/event.go:32]: Can this be removed?

File: pkg/controller/volume/persistentvolume/pv_controller_base.go [hunk 5]
```diff
@@ -126,10 +127,19 @@ func NewController(p ControllerParameters) (*PersistentVolumeController, error)
 	controller.classLister = p.ClassInformer.Lister()
 	controller.classListerSynced = p.ClassInformer.Informer().HasSynced
 	controller.podLister = p.PodInformer.Lister()
+	controller.podIndexer = p.PodInformer.Informer().GetIndexer()
```
Comment (msau42) [inline pkg/controller/volume/persistentvolume/pv_controller_base.go:130]: Do we need to update https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go#L233 to add pod get/list/watch rbacs? I'm surprised we don't see any test failures?

File: pkg/controller/volume/events/event.go (hunk 4 above)
Comment (msau42) [reply pkg/controller/volume/events/event.go:32]: Nm I see it's still used. Can we also update this event message to be more clear that "first consumer" == pod?

File: pkg/controller/volume/persistentvolume/pv_controller_base.go (hunk 5 above)
Comment (cofyc) [reply pkg/controller/volume/persistentvolume/pv_controller_base.go:130]: It already has these rbacs

https://github.com/kubernetes/kubernetes/blob/0891f69f5ec27cdbcb6336ce3cfe6efdcc1d1e05/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go#L240

File: pkg/controller/volume/events/event.go (hunk 4 above)
Comment (cofyc) [reply pkg/controller/volume/events/event.go:32]: yes, it's still used to indicate that no pod is created to consume it. I suggest not changing it.
`WaitForFirstConsumer` is also used in storage class volume binding mode. When people see it in the event message, I think it's clear to them.
