### PR TITLE
block ephemeral container addition to static pods

### LINKED ISSUE #113935: Ephemeral container fails to be created for Static Pod
### What happened?

I created an ephemeral container for a Static Pod using the `kubectl debug` command. The command succeed.

```console
❯ kubectl debug --image=busybox --share-processes=true --target=kube-apiserver -n kube-system kube-apiserver-kind-control-plane -- sleep infinity
Targeting container "kube-apiserver". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
Defaulting debug container name to debugger-vgkn4.
```

The API server accepted the ephemeral container:
```console
❯ kubectl -n kube-system get pod kube-apiserver-kind-control-plane --output=jsonpath='{.spec.ephemeralContainers}'
[{"command":["sleep","infinity"],"image":"busybox","imagePullPolicy":"Always","name":"debugger-vgkn4","resources":{},"targetContainerName":"kube-apiserver","terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}]
```

However, the container is not created.

Its status is also not available:

```console
❯ kubectl -n kube-system get pod kube-apiserver-kind-control-plane --output=jsonpath='{.status.ephemeralContainerStatuses}'

```

### What did you expect to happen?

I expected one of these:

(a) the API server rejects the request to create an ephemeral container for a Static Pod
(b) kubelet creates the ephemeral container, and update the Static Pod's status sub-resource

### How can we reproduce it (as minimally and precisely as possible)?

Using a recent version of [docker engine](https://docs.docker.com/engine/install/), [kind](https://kind.sigs.k8s.io/docs/user/quick-start/)  v0.17 or newer, and [kubectl](https://kubernetes.io/docs/tasks/tools/#kubectl) v1.25.0 or newer, create a cluster and create an ephemeral container running `sleep infinity`. Since the ephemeral container is not running, the output of `grep` is 0. 

```
kind create cluster
kubectl debug --image=busybox --share-processes=true --target=kube-apiserver -n kube-system kube-apiserver-kind-control-plane -- sleep infinity
docker exec -it kind-control-plane ps -axw | grep --count "sleep infinity"
```

### Anything else we need to know?

The [Ephemeral Containers KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/277-ephemeral-containers/README.md) does not address Static Pods.

### Kubernetes version

<details>

```console
$ kubectl version --short
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.25.3
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
❯ docker exec -it kind-control-plane containerd --version
containerd github.com/containerd/containerd v1.6.9 1c90a442489720eec95342e1789ee8a5e1b9536f
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by xmcqueen**
added validation check to block the addition of an ephemeral container to a static pod and a test case

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Discussion is in the linked ticket below.  In short, ephemeral containers will silently not work when applied to static pods, and the pod spec on the disk is the authoritative definition of the pod - not the data in etcd.

#### Which issue(s) this PR fixes:

Fixes #113935 

#### Does this PR introduce a user-facing change?

```release-note
If a user attempts to add an ephemeral container to a static pod, they will get a visible validation error.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/apis/core/validation/validation.go [hunk 1]
```diff
@@ -4688,6 +4689,17 @@ func ValidatePodEphemeralContainersUpdate(newPod, oldPod *core.Pod, opts PodVali
 	allErrs = append(allErrs, validatePodMetadataAndSpec(newPod, opts)...)
 	allErrs = append(allErrs, ValidatePodSpecificAnnotationUpdates(newPod, oldPod, fldPath.Child("annotations"), opts)...)
 
+	// static pods don't support ephemeral containers #113935
+	v1PodOld := &v1.Pod{}
+	// TODO check for error below
+	// how to handle this error?!
+	// Its not appropriate to send it on to the user
+	// they can't fix it
+	corev1.Convert_core_Pod_To_v1_Pod(oldPod, v1PodOld, nil)
```
Comment (aojea) [inline pkg/apis/core/validation/validation.go:4698]: why do you need to convert? to use `types.IsMirrorPod`? no need, check  `ValidatePodSpecificAnnotationUpdates` , it already checks for mirror pod, just copy the logic

Comment (xmcqueen) [reply pkg/apis/core/validation/validation.go]: I remember why. I thought it best to use the `types.IsMirrorPod` since I thought it best to avoid c/p.  Its fixed now.  Thanks!

**Comment by xmcqueen** [comment]
I'm going to add some more unit tests too.

File: pkg/apis/core/validation/validation.go [hunk 2]
```diff
@@ -4688,6 +4688,14 @@ func ValidatePodEphemeralContainersUpdate(newPod, oldPod *core.Pod, opts PodVali
 	allErrs = append(allErrs, validatePodMetadataAndSpec(newPod, opts)...)
 	allErrs = append(allErrs, ValidatePodSpecificAnnotationUpdates(newPod, oldPod, fldPath.Child("annotations"), opts)...)
 
+	// static pods don't support ephemeral containers #113935
+	oldAnnotations := oldPod.Annotations
+	for k := range oldAnnotations {
+		if k == core.MirrorPodAnnotationKey {
+			allErrs = append(allErrs, field.Forbidden(fldPath.Child("annotations"), fmt.Sprintf("static pods (%q) do not support ephemeral containers", oldPod.ObjectMeta.GetName())))
```
Comment (xmcqueen) [inline pkg/apis/core/validation/validation.go:4695]: I'll put a break in right here too.

**Comment by aojea** [comment]
/assign @aojea @SergeyKanzhelev @liggitt @bobbypage 

assigning Jordan and I for context from the original issue, David and Sergey for sig-node

File: pkg/registry/core/pod/strategy_test.go [hunk 3]
```diff
@@ -1267,6 +1267,150 @@ func TestPodStrategyValidate(t *testing.T) {
...
+					},
+				},
+			},
+		},
+	}
+
+	// expect no errors
+	for _, tc := range test {
+		t.Run(tc.name, func(t *testing.T) {
+			if errs := EphemeralContainersStrategy.ValidateUpdate(genericapirequest.NewContext(), tc.newPod, tc.oldPod); len(errs) != 0 {
```
Comment (xmcqueen) [inline pkg/registry/core/pod/strategy_test.go:1333]: note these new test cases are using the EphemeralContainerStrategy

**Comment by aojea** [comment]
@xmcqueen you have some gomft errors

**Comment by xmcqueen** [comment]
@aojea squashed and fmt'd.  Thanks!

File: pkg/apis/core/validation/validation.go [hunk 4]
```diff
@@ -4688,6 +4688,15 @@ func ValidatePodEphemeralContainersUpdate(newPod, oldPod *core.Pod, opts PodVali
 	allErrs = append(allErrs, validatePodMetadataAndSpec(newPod, opts)...)
 	allErrs = append(allErrs, ValidatePodSpecificAnnotationUpdates(newPod, oldPod, fldPath.Child("annotations"), opts)...)
 
+	// static pods don't support ephemeral containers #113935
+	oldAnnotations := oldPod.Annotations
+	for k := range oldAnnotations {
```
Comment (aojea) [inline pkg/apis/core/validation/validation.go:4693]: this is a map[string]string you don't have to iterate
```
	if _, isMirror := annotations[core.MirrorPodAnnotationKey]; isMirror {
allErrs = append(allErrs, field.Forbidden(fldPath.Child("annotations"), fmt.Sprintf("static pods (%q) do not support ephemeral containers", oldPod.ObjectMeta.GetName())))
	}
```

Comment (xmcqueen) [reply pkg/apis/core/validation/validation.go:4693]: dang it. obvious

File: pkg/apis/core/validation/validation.go [hunk 5]
```diff
@@ -4688,6 +4688,11 @@ func ValidatePodEphemeralContainersUpdate(newPod, oldPod *core.Pod, opts PodVali
 	allErrs = append(allErrs, validatePodMetadataAndSpec(newPod, opts)...)
 	allErrs = append(allErrs, ValidatePodSpecificAnnotationUpdates(newPod, oldPod, fldPath.Child("annotations"), opts)...)
 
+	// static pods don't support ephemeral containers #113935
+	if _, ok := oldPod.Annotations[core.MirrorPodAnnotationKey]; ok {
+		allErrs = append(allErrs, field.Forbidden(fldPath.Child("annotations"), fmt.Sprintf("static pods (%q) do not support ephemeral containers", oldPod.ObjectMeta.GetName())))
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:4693]: the annotation check lgtm, and ValidatePodEphemeralContainersUpdate is *only* called when adding a new ephemeral container, so making this function stricter will not break any existing mirror pods that happened to have ephemeral containers added previously

If we do encounter a mirror pod, this error is not one of many field errors that can be "corrected", it means this pod is not eligible to have ephemeral containers added to it.

For that reason, I would probably return a solo forbidden error here instead of appending to `allErrs`, and would set the field path to `field.NewPath("")` rather than pointing at the annotation specifically

**Comment by xmcqueen** [comment]
Thanks @liggitt your last comment has been resolved.  This PR is ready for further review.

File: pkg/apis/core/validation/validation.go [hunk 6]
```diff
@@ -4688,6 +4688,11 @@ func ValidatePodEphemeralContainersUpdate(newPod, oldPod *core.Pod, opts PodVali
 	allErrs = append(allErrs, validatePodMetadataAndSpec(newPod, opts)...)
 	allErrs = append(allErrs, ValidatePodSpecificAnnotationUpdates(newPod, oldPod, fldPath.Child("annotations"), opts)...)
 
+	// static pods don't support ephemeral containers #113935
+	if _, ok := oldPod.Annotations[core.MirrorPodAnnotationKey]; ok {
+		return field.ErrorList{field.Forbidden(field.NewPath(""), fmt.Sprintf("static pods (%q) do not support ephemeral containers", oldPod.ObjectMeta.GetName()))}
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:4693]: shouldn't need to include the name here, returned errors should get wrapped in an overall error that includes the name

**Comment by aojea** [comment]
/lgtm

defer to node for final approval

/assign @bobbypage @derekwaynecarr

**Comment by sftim** [comment]
I'd changelog this as:
```markdown
Add a validation error if a user attempts to add an ephemeral container to a static pod.
```

**Comment by xmcqueen** [comment]
Who makes the changelog happen? I don't know how to get that going.

**Comment by endocrimes** [comment]
@xmcqueen It's generated automatically based on the release-note block in the PR.

You can edit them for other PRs with the [`release-node-edit` command](https://prow.k8s.io/command-help#release_note_edit) too.

**Comment by xmcqueen** [comment]
It looks like somebody beat me to it!  Thanks y'all

**Comment by xmcqueen** [comment]
This one needs an approval.  The [corresponding doc change](https://github.com/kubernetes/website/pull/37993) is already merged. We should get this merged.
