### PR TITLE
deflake a resource quota check for best-effort pods

### LINKED ISSUE #98856: [Flaky Test] [sig-api-machinery] ResourceQuota should verify ResourceQuota with best effort scope. [Conformance]
**Which jobs are flaking**: `ci-kubernetes-e2e-gci-gce`

**Which test(s) are flaking**: `ResourceQuota should verify ResourceQuota with best effort scope. [Conformance] `

**Testgrid link**: https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=ResourceQuota%20should%20verify%20ResourceQuota%20with%20best%20effort%20scope.

**Reason for failure**:
```
I0205 07:23:55.779] Feb  5 07:23:45.540: INFO: resource pods, expected 1, actual 0
I0205 07:23:55.780] Feb  5 07:23:47.532: INFO: resource pods, expected 1, actual 0
I0205 07:23:55.780] Feb  5 07:23:49.531: INFO: resource pods, expected 1, actual 0
I0205 07:23:55.780] Feb  5 07:23:51.530: INFO: resource pods, expected 1, actual 0
I0205 07:23:55.780] Feb  5 07:23:51.569: INFO: resource pods, expected 1, actual 0
I0205 07:23:55.780] Feb  5 07:23:51.570: FAIL: Unexpected error:
I0205 07:23:55.780]     <*errors.errorString | 0xc0001f61d0>: {
I0205 07:23:55.781]         s: "timed out waiting for the condition",
I0205 07:23:55.781]     }
I0205 07:23:55.781]     timed out waiting for the condition
I0205 07:23:55.781] occurred
I0205 07:23:55.781] 
I0205 07:23:55.781] Full Stack Trace
I0205 07:23:55.781] k8s.io/kubernetes/test/e2e/apimachinery.glob..func18.12()
I0205 07:23:55.781] 	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:818 +0x758
skipped 296 lines unfold_more
I0205 07:23:55.892] Latency metrics for node bootstrap-e2e-minion-group-lq17
I0205 07:23:55.892] Feb  5 07:23:55.673: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
I0205 07:23:55.892] STEP: Destroying namespace "resourcequota-7723" for this suite.
I0205 07:23:55.892] 
I0205 07:23:55.892] 
I0205 07:23:55.892] • Failure [39.134 seconds]
I0205 07:23:55.892] [sig-api-machinery] ResourceQuota
I0205 07:23:55.893] /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/framework.go:23
I0205 07:23:55.893]   should verify ResourceQuota with best effort scope. [Conformance] [It]
```

**Anything else we need to know**:

Triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=ResourceQuota%20should%20verify%20ResourceQuota%20with%20best%20effort%20scope

Spyglass: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1357587866661687296

/sig api-machinery

### PR DESCRIPTION
**Pull request by pacoxu**
**A small flake that failed continuously, but the frequency is only once a day.** 

### What type of PR is this?
/kind flake
/sig api-machinery

###  What this PR does / why we need it:
The changed timeout is for Line 1714
It seems that resource quota status/used updating is not that quick.

### Which issue(s) this PR fixes:
Fixes #98856

**Special notes for your reviewer**:
Try to fix it like #96265 for configmap check.
**Kubernetes Aggregated Failures link**: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=ResourceQuota%20should%20verify%20ResourceQuota%20with%20best%20effort%20scope
```
1 clusters of 7 failures out of 142149 builds from 2021/2/5 AM 8:00:31 to 2021/2/19 AM 7:31:33.
1 clusters of 8 failures (1 in last day) out of 133480 builds  from 2021/4/9上午8:00:14 to 2021/4/23下午3:23:54.
```

Another way to fix this may be https://github.com/kubernetes/kubernetes/issues/98856#issuecomment-775732623.
- add more concurrent namespace syncs or resource quota syncs.

**Does this PR introduce a user-facing change?**:
```release-note
None
```

### CODE REVIEW

File: test/e2e/apimachinery/resource_quota.go [hunk 1]
```diff
@@ -43,7 +43,7 @@ import (
 
 const (
 	// how long to wait for a resource quota update to occur
-	resourceQuotaTimeout = 30 * time.Second
```
Comment (pacoxu) [inline test/e2e/apimachinery/resource_quota.go:46]: only used in 
https://github.com/kubernetes/kubernetes/pull/98906/files#diff-e1a46008c4ddbb9f83858cb22ce56ca0f820b78142a1e8abbbb11aa59127a09bL1714 before

**Comment by yliaog** [comment]
/lgtm

any idea why it started to get flaky lately?
