### PR TITLE
fix get azure accounts timeout issue when there is no out-bound IP

### LINKED ISSUE #74190: A storageAccount API call blocks kubelet from becoming Ready when there isn't any outbound IP
**What happened**:
A storageAccount API call blocks kubelet from becoming Ready when there isn't any outbound IP, 1. eventually (after 10mins), the kubelet registers again... there is a call to the ARM API done by `azure_blobDiskController.go:70` which blocks for 10mins, before letting kubelet complete with its starting logic and making the node as `Ready`

details: https://github.com/kubernetes/cloud-provider-azure/issues/86

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.5
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/assign

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
make `getAllStorageAccounts` func happen only when there is create unmanaged disk request, for managed disk cluster, it's not necessary to make `getAllStorageAccounts` func run.

**Which issue(s) this PR fixes**:

Fixes #74190

Original issue: https://github.com/kubernetes/cloud-provider-azure/issues/86

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix get azure accounts timeout issue when there is no out-bound IP
```

/kind bug
/assign @feiskyer 
/priority important-soon
/sig azure

cc @djsly

### CODE REVIEW

File: pkg/cloudprovider/providers/azure/azure_blobDiskController.go [hunk 1]
```diff
@@ -436,7 +437,7 @@ func (c *BlobDiskController) getDiskCount(SAName string) (int, error) {
 }
 
 func (c *BlobDiskController) getAllStorageAccounts() (map[string]*storageAccountState, error) {
-	ctx, cancel := getContextWithCancel()
+	ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
```
Comment (feiskyer) [inline pkg/cloudprovider/providers/azure/azure_blobDiskController.go]: nit: add a const for the timeout instead of magic numbers.

**Comment by djsly** [comment]
Question, does the call to `getAllStorageAccounts` needs to be done at instantiation time ?

**Comment by andyzhangx** [comment]
> Question, does the call to `getAllStorageAccounts` needs to be done at instantiation time ?

yes, and it's for unmanaged disk which is corner scenario now, while for compatibility, I still keep it in the code. So is setting timeout as 1 min ok in your scenario?

**Comment by andyzhangx** [comment]
I have fixed @feiskyer 's comments, and will wait for @djsly 's reply, to make sure whether this PR is acceptable in tha `no outbound IP initiallly` scenario.

**Comment by djsly** [comment]
@andyzhangx if you are saying that there is no choice but to query the list of StorageAccount at initiation time, then I guess it's good.

**Comment by djsly** [comment]
I was looking at the code, and I see that the `accounts` property of the BlobDiskController isn't used at all in the azure.go. The bloc controller gets created `blobController, err := newBlobDiskController(common)` but not used until a `// create/attach/detach/delete blob based (unmanaged disks)` tasks is performed. 

```
type BlobDiskController struct {
	common   *controllerCommon
	accounts map[string]*storageAccountState
}
```

Couldnt the call to `accounts, err := c.getAllStorageAccounts()` be done on the first call of `create/attach/detach/delete blob`, like those public methods could be enhanced with a "isInitialized" and this would allow them to call `accounts, err := c.getAllStorageAccounts()` if it hasn't been initialized. Preventing the API call all together during the initialization of the Azure Cloud Provider object ?

Food for though...

**Comment by andyzhangx** [comment]
@djsly thanks for your code analysis, you are right:
`getAllStorageAccounts` func should only happen when there is create unmanaged disk request, for managed disk cluster, it's not necessary to make `getAllStorageAccounts` func run.

I have changed the code according to your request. PTAL, thanks.

File: pkg/cloudprovider/providers/azure/azure_blobDiskController.go [hunk 2]
```diff
@@ -217,6 +215,8 @@ func (c *BlobDiskController) deleteVhdBlob(accountName, accountKey, blobName str
 func (c *BlobDiskController) CreateBlobDisk(dataDiskName string, storageAccountType storage.SkuName, sizeGB int) (string, error) {
 	klog.V(4).Infof("azureDisk - creating blob data disk named:%s on StorageAccountType:%s", dataDiskName, storageAccountType)
 
+	c.initStorageAccounts()
```
Comment (djsly) [inline pkg/cloudprovider/providers/azure/azure_blobDiskController.go]: I haven't looked at the other BlobDisk operations (attach/detach/delete) but I'm assuming here that they cannot get called unless `CreateBlobDisk` was called

File: pkg/cloudprovider/providers/azure/azure_blobDiskController.go [hunk 3]
```diff
@@ -62,18 +62,16 @@ var (
...
-	// get accounts
-	accounts, err := c.getAllStorageAccounts()
-	if err != nil {
-		klog.Errorf("azureDisk - getAllStorageAccounts error: %v", err)
-		c.accounts = make(map[string]*storageAccountState)
-		return &c, nil
+func (c *BlobDiskController) initStorageAccounts() {
+	if c.accounts == nil {
+		// get accounts
+		accounts, err := c.getAllStorageAccounts()
```
Comment (djsly) [inline pkg/cloudprovider/providers/azure/azure_blobDiskController.go]: I do not see the logic where the timeout was reduced to 1min, do we still want to keep the 10mins timeout (knowing that the initial issue was solved differently) I will leave that decision to you two :)

File: pkg/cloudprovider/providers/azure/azure_blobDiskController.go (hunk 2 above)
Comment (andyzhangx) [reply pkg/cloudprovider/providers/azure/azure_blobDiskController.go]: yes, only `CreateBlobDisk` func could invoke `getAllStorageAccounts`

File: pkg/cloudprovider/providers/azure/azure_blobDiskController.go (hunk 3 above)
Comment (andyzhangx) [reply pkg/cloudprovider/providers/azure/azure_blobDiskController.go]: let's keep the original timeout, this issue is already resolved by moving `getAllStorageAccounts` to only invoked by `CreateBlobDisk`.

**Review by andyzhangx — COMMENTED** [review]
Thanks for @djsly 's suggestion, this is an old issue which should be fixed in earlier version. I will cherry pick to earlier version when this PR get merged.
/hold cancel

**Comment by djsly** [comment]
@andyzhangx , perfect! thanks for the cherry picks.

**Comment by djsly** [comment]
@andyzhangx, I will be building this locally, I have a setup ready to test in case you need some extra testing.

**Comment by andyzhangx** [comment]
@djsly thanks, actually I have already tested in unmanaged cluster, it  worked well.

File: pkg/cloudprovider/providers/azure/azure_blobDiskController.go [hunk 4]
```diff
@@ -62,18 +62,16 @@ var (
...
-	c := BlobDiskController{common: common}
-
-	// get accounts
-	accounts, err := c.getAllStorageAccounts()
-	if err != nil {
-		klog.Errorf("azureDisk - getAllStorageAccounts error: %v", err)
-		c.accounts = make(map[string]*storageAccountState)
-		return &c, nil
+func (c *BlobDiskController) initStorageAccounts() {
+	if c.accounts == nil {
```
Comment (feiskyer) [inline pkg/cloudprovider/providers/azure/azure_blobDiskController.go]: Are there any race conditions for it? maybe hold the operations within a lock?

Comment (andyzhangx) [reply pkg/cloudprovider/providers/azure/azure_blobDiskController.go]: @feiskyer good catch, while I think it does not matter since it's only get accounts(read), no write or update.

Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_blobDiskController.go]: Yep, but I think `c.accounts` may be called in different goroutines, so it's better to be hold by a lock.

Comment (andyzhangx) [reply pkg/cloudprovider/providers/azure/azure_blobDiskController.go]: ok, let me put a lock anyway for the sake of safety, thanks.

Comment (andyzhangx) [reply pkg/cloudprovider/providers/azure/azure_blobDiskController.go]: @feiskyer it's been fixed in the new commit

**Comment by djsly** [comment]
hello, I tested 1.13.3 + patch on a VM that doesn't have an outbound IP. We have a Standard ILB in k8s with a single frontend from the vnet's subnet. 

This time, there isn't any timeouts
```
t[78376]: I0220 17:10:09.032750   78376 azure_auth.go:58] azure: using managed identity extension to retrieve access token
t[78376]: I0220 17:10:09.032768   78376 azure_auth.go:69] azure: using System Assigned MSI to retrieve access token
t[78376]: I0220 17:10:09.032805   78376 azure.go:258] Azure cloudprovider (read ops) using rate limit config: QPS=25, bucket=200
t[78376]: I0220 17:10:09.032821   78376 azure.go:262] Azure cloudprovider (write ops) using rate limit config: QPS=10, bucket=100
t[78376]: I0220 17:10:09.032933   78376 azure.go:324] Azure cloudprovider using try backoff: retries=6, exponent=1.500000, duration=6, jitter=1.000000
t[78376]: I0220 17:10:09.032983   78376 server.go:525] Successfully initialized cloud provider: "azure" from the config file: "/etc/kubernetes/azure.json"
t[78376]: I0220 17:10:09.033003   78376 server.go:791] cloud provider determined current node name to be kn-default-2
```

I still have a problem where all my nodes are showing up as `NotReady` now after they updated with the `dirty` kubelet. I'll pursue the investigation

```
NAME           STATUS                     ROLES    AGE    VERSION
km0            Ready,SchedulingDisabled   master   43h    v1.13.3-dirty
km1            Ready,SchedulingDisabled   master   43h    v1.13.3-dirty
km2            Ready,SchedulingDisabled   master   43h    v1.13.3-dirty
kn-default-0   NotReady                   node     43h    v1.13.3-dirty
kn-default-1   NotReady                   node     26h    v1.13.3-dirty
kn-default-2   NotReady                   <none>   146m   v1.13.3-dirty
kn-infra-0     NotReady                   infra    43h    v1.13.3-dirty
kn-infra-1     NotReady                   infra    43h    v1.13.3-dirty
kn-infra-2     NotReady                   infra    43h    v1.13.3-dirty
```

**Comment by djsly** [comment]
ok the new call now that timesout after 10mins is: 

```
 78376 azure_dd.go:165] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-2, location: eastus2
```

**Comment by djsly** [comment]
```
result, err := az.VirtualMachineSizesClient.List(context.TODO(), az.Location)
                if err != nil || result.Value == nil {
                        klog.Errorf("failed to list vm sizes in GetVolumeLimits, plugin.host: %s, location: %s", plugin.host.GetHostName(), az.Location)
                        return volumeLimits, nil
                }
```

Problem here is that the source of the call is in k8s, not `azure.go`
```
./pkg/kubelet/nodestatus/setters.go:                    attachLimits, err := volumePlugin.GetVolumeLimits()
```

Can't we use instanceMetadata for this ?

I'm not sure yet, why the full list of VmSizes in a SubID is required.

```
// List lists virtual-machine-sizes available in a location for a subscription.
//
// location is the location upon which virtual-machine-sizes is queried.
```

**Comment by djsly** [comment]
so I now understand better how this works, Since the instance metadata doesn't provide the `MaxDataDiskCount` you get the list of all VM instance type possible in the SubID/Location and match the InstanceType of the current VM with the list to extract the `MaxDataDiskCount` ... 

I would try your timeout logic you initially wrote but I can't find the commit anymore, must have been squashed.  Do we know if the instance metadata team could augment the metadata with this information ?

**Comment by andyzhangx** [comment]
@djsly use this code for set timeout as 1 min:
```
ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
```
can we merge this PR first? @djsly

**Comment by djsly** [comment]
Sure this is good to go. I guess we will need to open another one for the issue with the 

`result, err := az.VirtualMachineSizesClient.List(context.TODO(), az.Location)`

I will leave that to your discretion to see if you prefer to manage two PRs with multiple cherry picks. 

Or if it would be best tackle all those issues within the same PR, since in the end all this work is related to Kubelet not starting in a timely fashion when there isn't any outbound IP

**Comment by djsly** [comment]
OK I tested the context.WithTimeout() on the VirtualMachineSizesClient API call and this seem to be the last long blocking call . You can see bellow that the node isn't registered for 15sec, until the first API call timesout. 

```
I0221 23:14:50.774027   22942 kubelet_node_status.go:278] Setting node annotation to enable volume controller attach/detach
belet[22942]: I0221 23:14:50.774066   22942 kubelet_node_status.go:326] Adding node label from cloud provider: beta.kubernetes.io/instance-type=Sta
belet[22942]: I0221 23:14:50.774077   22942 azure_zones.go:69] Availability zone is not enabled for the node, falling back to fault domain
belet[22942]: I0221 23:14:50.774085   22942 kubelet_node_status.go:337] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/zo
belet[22942]: I0221 23:14:50.774093   22942 kubelet_node_status.go:341] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/re
belet[22942]: W0221 23:14:50.774139   22942 setters.go:144] replacing cloudprovider-reported hostname of kn-default-3 with overridden hostname of k
...
...
belet[22942]: E0221 23:14:50.827380   22942 kubelet.go:2266] node "kn-default-3" not found
belet[22942]: E0221 23:14:50.927536   22942 kubelet.go:2266] node "kn-default-3" not found
belet[22942]: E0221 23:14:51.027770   22942 kubelet.go:2266] node "kn-default-3" not found
belet[22942]: E0221 23:14:51.127979   22942 kubelet.go:2266] node "kn-default-3" not found
belet[22942]: E0221 23:14:51.228213   22942 kubelet.go:2266] node "kn-default-3" not found
belet[22942]: E0221 23:14:51.328371   22942 kubelet.go:2266] node "kn-default-3" not found
...
...
...
belet[22942]: E0221 23:15:04.780600   22942 kubelet.go:2266] node "kn-default-3" not found
belet[22942]: E0221 23:15:04.880789   22942 kubelet.go:2266] node "kn-default-3" not found
belet[22942]: E0221 23:15:04.980982   22942 kubelet.go:2266] node "kn-default-3" not found
belet[22942]: E0221 23:15:05.066718   22942 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-3, location: eastu
belet[22942]: I0221 23:15:05.066768   22942 setters.go:736] Error getting volume limit for plugin kubernetes.io/aws-ebs
belet[22942]: I0221 23:15:05.066779   22942 setters.go:736] Error getting volume limit for plugin kubernetes.io/gce-pd
belet[22942]: I0221 23:15:05.066800   22942 kubelet_node_status.go:446] Recording NodeHasSufficientMemory event message for node kn-default-3
belet[22942]: I0221 23:15:05.066824   22942 kubelet_node_status.go:446] Recording NodeHasNoDiskPressure event message for node kn-default-3
belet[22942]: I0221 23:15:05.066838   22942 kubelet_node_status.go:446] Recording NodeHasSufficientPID event message for node kn-default-3
belet[22942]: I0221 23:15:05.066866   22942 kubelet_node_status.go:72] Attempting to register node kn-default-3
belet[22942]: I0221 23:15:05.067321   22942 server.go:459] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kn-default-3", UID:"kn-default
belet[22942]: I0221 23:15:05.067343   22942 server.go:459] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kn-default-3", UID:"kn-default
belet[22942]: I0221 23:15:05.067354   22942 server.go:459] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kn-default-3", UID:"kn-default
belet[22942]: E0221 23:15:05.081204   22942 kubelet.go:2266] node "kn-default-3" not found
belet[22942]: I0221 23:15:05.082542   22942 kubelet_node_status.go:75] Successfully registered node kn-default-3
```

**Comment by djsly** [comment]
also, before my patch, we can see that the calls were failing every 10mins (I'm guessing kubelet will keep retrying) and after I patched, on existing Nodes, the error messages is every ~15sec

```
Feb 21 19:28:23  kubelet[42192]: E0221 19:28:23.656890   42192 azure_dd.go:165] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 19:38:53  kubelet[42192]: E0221 19:38:53.679577   42192 azure_dd.go:165] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 19:49:23  kubelet[42192]: E0221 19:49:23.703875   42192 azure_dd.go:165] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 19:59:53  kubelet[42192]: E0221 19:59:53.725452   42192 azure_dd.go:165] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 20:10:23  kubelet[42192]: E0221 20:10:23.754637   42192 azure_dd.go:165] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 20:20:53  kubelet[42192]: E0221 20:20:53.788917   42192 azure_dd.go:165] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 20:31:23  kubelet[42192]: E0221 20:31:23.818574   42192 azure_dd.go:165] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 20:41:53  kubelet[42192]: E0221 20:41:53.840404   42192 azure_dd.go:165] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 20:52:23  kubelet[42192]: E0221 20:52:23.891879   42192 azure_dd.go:165] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:02:53  kubelet[42192]: E0221 21:02:53.917138   42192 azure_dd.go:165] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:13:23  kubelet[42192]: E0221 21:13:23.937846   42192 azure_dd.go:165] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:23:53  kubelet[42192]: E0221 21:23:53.957359   42192 azure_dd.go:165] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:34:23  kubelet[42192]: E0221 21:34:23.981998   42192 azure_dd.go:165] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2

Feb 21 21:38:07  kubelet[88761]: E0221 21:38:07.171911   88761 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:38:22  kubelet[88761]: E0221 21:38:22.191122   88761 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:39:22  kubelet[88761]: E0221 21:39:22.191373   88761 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:40:37  kubelet[88761]: E0221 21:40:37.212780   88761 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:41:52  kubelet[88761]: E0221 21:41:52.234522   88761 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:43:07  kubelet[88761]: E0221 21:43:07.254709   88761 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:44:22  kubelet[88761]: E0221 21:44:22.276533   88761 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:45:37  kubelet[88761]: E0221 21:45:37.300389   88761 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:46:52  kubelet[88761]: E0221 21:46:52.319842   88761 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:48:07  kubelet[88761]: E0221 21:48:07.348183   88761 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:49:22  kubelet[88761]: E0221 21:49:22.367277   88761 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:50:37  kubelet[88761]: E0221 21:50:37.392020   88761 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:51:52  kubelet[88761]: E0221 21:51:52.410877   88761 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:52:29  kubelet[97239]: E0221 21:52:29.759218   97239 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:52:44  kubelet[97239]: E0221 21:52:44.785222   97239 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:52:59  kubelet[97239]: E0221 21:52:59.802677   97239 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
Feb 21 21:53:59  kubelet[97239]: E0221 21:53:59.802780   97239 azure_dd.go:168] failed to list vm sizes in GetVolumeLimits, plugin.host: kn-default-1, location: eastus2
```

**Comment by feiskyer** [comment]
@djsly Thanks for validating this.

@andyzhangx Could you fix the issue within same PR? They are actually same issue, but just different APIs. And we need to cherry pick the changes to stable releases.

**Comment by andyzhangx** [comment]
@feiskyer @djsly pls review commit: https://github.com/kubernetes/kubernetes/pull/74191/commits/28a9aa8f806cebe35b22f42348ead90955b4d018

File: pkg/cloudprovider/providers/azure/azure_blobDiskController.go [hunk 5]
```diff
@@ -62,18 +62,19 @@ var (
...
-	if err != nil {
-		klog.Errorf("azureDisk - getAllStorageAccounts error: %v", err)
-		c.accounts = make(map[string]*storageAccountState)
-		return &c, nil
+	if c.accounts == nil {
+		// get accounts
+		accounts, err := c.getAllStorageAccounts()
+		if err != nil {
+			klog.Errorf("azureDisk - getAllStorageAccounts error: %v", err)
+			c.accounts = make(map[string]*storageAccountState)
```
Comment (feiskyer) [inline pkg/cloudprovider/providers/azure/azure_blobDiskController.go]: Keep c.accouts as nil here? or else, it won't try again on errors.

File: pkg/volume/azure_dd/azure_dd.go [hunk 6]
```diff
@@ -164,7 +165,9 @@ func (plugin *azureDataDiskPlugin) GetVolumeLimits() (map[string]int64, error) {
 	}
 
 	if vmSizeList == nil {
-		result, err := az.VirtualMachineSizesClient.List(context.TODO(), az.Location)
+		ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
+		defer cancel()
```
Comment (feiskyer) [inline pkg/volume/azure_dd/azure_dd.go]: Should we also add same timeout to getAllStorageAccounts?

File: pkg/volume/azure_dd/azure_dd.go [hunk 7]
```diff
@@ -164,7 +165,9 @@ func (plugin *azureDataDiskPlugin) GetVolumeLimits() (map[string]int64, error) {
 	}
 
 	if vmSizeList == nil {
-		result, err := az.VirtualMachineSizesClient.List(context.TODO(), az.Location)
+		ctx, cancel := context.WithTimeout(context.Background(), 60*time.Second)
```
Comment (feiskyer) [inline pkg/volume/azure_dd/azure_dd.go]: nit: define a consts for timeout, e.g. `listAPITimeout = 60*time.Second`

File: pkg/cloudprovider/providers/azure/azure_blobDiskController.go (hunk 5 above)
Comment (andyzhangx) [reply pkg/cloudprovider/providers/azure/azure_blobDiskController.go]: @feiskyer yes, won't try again on error, it would make new map and create new storage account(don't use existing accounts)

File: pkg/volume/azure_dd/azure_dd.go (hunk 6 above)
Comment (andyzhangx) [reply pkg/volume/azure_dd/azure_dd.go]: @feiskyer fixed.

**Review by feiskyer — COMMENTED** [review]
/lgtm

**Comment by djsly** [comment]
Thanks guys!
