### PR TITLE
CSI bug fixes for teardown, nodepublish probe, target path creation

### LINKED ISSUE #56817: CSI internal volume driver should probe external driver prior to NodePublish
/kind bug

**What happened**:
The internal csi driver called NodePublish without probing the external driver.

**What you expected to happen**:
Prior to calling NodePublish RPC, Kubernetes must probe the external driver for readiness.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a pod that uses a csi-backed volume.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by vladimirvivien**
**What this PR does / why we need it**:
This PR addresses several critical bug fixes in CSI including mounter teardown fix, create nodeprobe prior to mount, and pre-create target path.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #56817, #56815, #56813

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/volume/csi/csi_mounter.go [hunk 1]
```diff
@@ -121,6 +160,12 @@ func (c *csiMountMgr) SetUpAt(dir string, fsGroup *int64) error {
 		return err
 	}
 
+	if err := os.MkdirAll(dir, 0750); err != nil {
```
Comment (saad-ali) [inline pkg/volume/csi/csi_mounter.go]: If mount fails after this point, we should cleanup this directory before returning.

File: pkg/volume/csi/csi_mounter.go [hunk 2]
```diff
@@ -90,9 +109,29 @@ func (c *csiMountMgr) SetUpAt(dir string, fsGroup *int64) error {
...
+	// persist volume info data for teardown
+	volData := map[string]string{
+		volDataKey.specVolID:    c.spec.Name(),
+		volDataKey.volHandle:    csiSource.VolumeHandle,
+		volDataKey.driverName:   csiSource.Driver,
+		volDataKey.nodeName:     nodeName,
+		volDataKey.attachmentID: attachID,
+	}
+
+	if err := saveVolumeData(c.plugin, c.podUID, c.spec.Name(), volData); err != nil {
```
Comment (saad-ali) [inline pkg/volume/csi/csi_mounter.go]: We should do this immediately after `os.MkdirAll( ...)` below so that the `saveVolumeData` doesn't have to create a dir.

Also if the mount operation fails after this, we should cleanup the saved data. But we have to be careful, if the mount exists (maybe from a previous iteration), we need to make sure that we don't accidently delete data before it is unmounted.

File: pkg/volume/csi/csi_mounter.go [hunk 3]
```diff
@@ -164,10 +209,16 @@ func (c *csiMountMgr) TearDown() error {
 func (c *csiMountMgr) TearDownAt(dir string) error {
 	glog.V(4).Infof(log("Unmounter.TearDown(%s)", dir))
 
-	// extract driverName and volID from path
-	base, volID := path.Split(dir)
-	volID = kstrings.UnescapeQualifiedNameForDisk(volID)
-	driverName := path.Base(base)
+	// load volume info from file
+	dataDir := path.Dir(dir) // dropoff /mount at end
+	data, err := loadVolumeData(dataDir, volDataFileName)
```
Comment (saad-ali) [inline pkg/volume/csi/csi_mounter.go]: Where is this data deleted/cleaned up?

File: pkg/volume/csi/csi_mounter.go [hunk 4]
```diff
@@ -187,9 +238,7 @@ func (c *csiMountMgr) TearDownAt(dir string) error {
 		return err
 	}
 
-	err := csi.NodeUnpublishVolume(ctx, volID, dir)
-
-	if err != nil {
+	if err := csi.NodeUnpublishVolume(ctx, volID, dir); err != nil {
 		glog.Errorf(log("Mounter.Setup failed: %v", err))
 		return err
 	}
```
Comment (saad-ali) [inline pkg/volume/csi/csi_mounter.go]: We should make sure to delete the `volData` and delete the volume directory (that we created). But we have to be careful deleting the directory, we should test if it is a mount point or not. Basically do what `UnmountMountPoint(...)` does in https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/util.go#L98 but don't unmount, and just fail if not unmounted.

https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/util.go#L98

**Review by saad-ali — COMMENTED** [review]
Some comments about cleanup

**Comment by saad-ali** [comment]
ACK.  In progress
ETA: Friday, Dec 8, 2017
Risks:
* Low risk to k8s code base, since this is isolated to new CSI volume plugin which is flag gated. 
* Required bug fix for CSI plugin to fix issues on unmount.

File: pkg/volume/csi/csi_mounter.go (hunk 4 above)
Comment (vladimirvivien) [reply pkg/volume/csi/csi_mounter.go]: @saad-ali when I read this couple days ago I did not understand a word.... man, the power of rest.  Ok, will take care of this.

File: pkg/volume/csi/csi_mounter.go (hunk 2 above)
Comment (saad-ali) [reply pkg/volume/csi/csi_mounter.go]: We should do `saveVolumeData(...)` after `os.MkdirAll` but before `csi.NodePublishVolume` -- so that if a mount succeeds and then the operation fails immediately afterwards, we have enough to cleanup.

Can either move it now or create an issue to clean it up later.

File: pkg/volume/csi/csi_mounter.go [hunk 5]
```diff
@@ -164,10 +229,28 @@ func (c *csiMountMgr) TearDown() error {
...
-	driverName := path.Base(base)
+	// is dir even mounted ?
+	mounted, err := isDirMounted(c.plugin, dir)
+	if err != nil {
+		glog.Error(log("unmounter.Teardown failed while checking mount status for dir [%s]: %v", dir, err))
+		return err
+	}
+
+	if !mounted {
+		glog.V(4).Info(log("unmounter.Teardown skipping unmout, dir not mounted [%s]", dir))
```
Comment (saad-ali) [inline pkg/volume/csi/csi_mounter.go]: We maybe, just maybe, should not have this check. Consider if a SP backs a storage volume using the local root FS (for something like an `emptyDir` or `localStorage`. We can leave it as is, and add a TODO to revisit in the future.

Comment (zhangxiaoyu-zidif) [reply pkg/volume/csi/csi_mounter.go]: +1 should revert this check.

Comment (saad-ali) [reply pkg/volume/csi/csi_mounter.go]: Agreed. Please open an issue to track this and create a PR to remove this check. We must leave it up to the CSI driver to decide what tear down means.

CC @vladimirvivien @msau42

Comment (msau42) [reply pkg/volume/csi/csi_mounter.go]: PR #72008 is addressing this
