### PR TITLE
Only set worker to nil when the key exists.

### LINKED ISSUE #125332: Pod stuck at Running state due to unexpected skip of taint manager work
### What happened?

1、We shutdown the worker node that our pods is running on
2、A pod stays in Running state and never change again

### What did you expect to happen?

We expected the pod to be update to Terminating.

### How can we reproduce it (as minimally and precisely as possible)?

It is unlikely to be reproduced since we found the 'only possible' cause to be of ridiculously low probability.

### Anything else we need to know?

The pod is defined with tolerations as below, but doesn't seem to be a problem:
```
tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 2
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 2 
```
Strange log sequence was found in controller-manager's log
```
I0604 15:28:49.239218       1 timed_workers.go:113] Adding TimedWorkerQueue item dpa/infrastructure-0 at 2024-06-04 15:28:49.239118259 +0800 CST m=+252387.993120493 to be fired at 2024-06-04 15:28:51.239118259 +0800 CST m=+252389.993120493
......
I0604 15:28:51.240319       1 taint_manager.go:106] "NoExecuteTaintManager is deleting pod" pod="dpa/infrastructure-0"
I0604 15:28:51.259631       1 taint_manager.go:416] "Noticed pod deletion" pod="dpa/infrastructure-0"
I0604 15:28:51.259642       1 timed_workers.go:132] Cancelling TimedWorkerQueue item dpa/infrastructure-0 at 2024-06-04 15:28:51.259639403 +0800 CST m=+252390.013641637
......
I0604 17:38:00.725378       1 timed_workers.go:113] Adding TimedWorkerQueue item dpa/infrastructure-0 at 2024-06-04 17:38:00.725348125 +0800 CST m=+260139.479350359 to be fired at 2024-06-04 17:38:02.725348125 +0800 CST m=+260141.479350359
W0604 17:38:00.725393       1 timed_workers.go:118] Trying to add already existing work for &{NamespacedName:dpa/infrastructure-0}. Skipping.
......
```
We noticed that we had restarted the node once at arround 15:28, and that trigger the eviction of pod dpa/infrastructure-0 as expected. But when we shutdown the node again at arround 17:38, the taint manager skipped the work due to the same key found in workers map.
The controller manager was never restarted or changed leader.
The log is ridiculous, but after look at the code, we did find a way that a key stays in workers map after Cancelling:
```
func (q *TimedWorkerQueue) getWrappedWorkerFunc(key string) func(ctx context.Context, args *WorkArgs) error {
	return func(ctx context.Context, args *WorkArgs) error {
		err := q.workFunc(ctx, args)
		q.Lock()
		defer q.Unlock()
		if err == nil {
			// To avoid duplicated calls we keep the key in the queue, to prevent
			// subsequent additions.
			q.workers[key] = nil
		} else {
			delete(q.workers, key)
		}
		return err
	}
}
```
In this part of code generates a WorkerFunc that would be called in a work, taint manager will run q.workFunc to delete pod from apiserver, which would trigger a podUpdate and lead to CancelWork:
```
func (q *TimedWorkerQueue) CancelWork(key string) bool {
	q.Lock()
	defer q.Unlock()
	worker, found := q.workers[key]
	result := false
	if found {
		klog.V(4).Infof("Cancelling TimedWorkerQueue item %v at %v", key, time.Now())
		if worker != nil {
			result = true
			worker.Cancel()
		}
		delete(q.workers, key)
	}
	return result
}
```
If and only if CancelWork acquired the lock before WorkerFunc, the `q.workers[key]` won't be deleted as expected, but `q.workers[key] = nil` instead, and lead to later skip of work.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.3+77d8f59014e1f3-dirty", GitCommit:"77d8f59014e1f3ca907c1b4a4f57900539b88dc8", GitTreeState:"dirty", BuildDate:"2024-04-29T13:26:15Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.3+77d8f59014e1f3-dirty", GitCommit:"77d8f59014e1f3ca907c1b4a4f57900539b88dc8", GitTreeState:"dirty", BuildDate:"2024-04-29T13:23:44Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by ning0515**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
The TimedWorkerQueue is controlled by a mutex lock. Other go-routines that acquire the lock will remove the corresponding key from the map after the worker completes its task. If the lock is acquired here again right after the key has been deleted, the deleted key will be re-added to the queue with a value of nil. In special cases, this can lead to erroneous judgments.

The code to acquire a lock and delete a key is as follows:

https://github.com/kubernetes/kubernetes/blob/d8093cc40394b8e25a864576fe6a38306730d3cb/pkg/controller/tainteviction/timed_workers.go#L136C1-L150C2

```
func (q *TimedWorkerQueue) CancelWork(logger klog.Logger, key string) bool {
	q.Lock()
	defer q.Unlock()
	worker, found := q.workers[key]
	result := false
	if found {
		logger.V(4).Info("Cancelling TimedWorkerQueue item", "item", key, "time", time.Now())
		if worker != nil {
			result = true
			worker.Cancel()
		}
		delete(q.workers, key)
	}
	return result
}
```

#### Which issue(s) this PR fixes:

Fixes #125332

#### Special notes for your reviewer:
Sorry, as a new contributor, I might not be very familiar with the community rules. If there are any issues with my actions, please guide me. Thank you.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by macsko** [comment]
Could you add a test case that tests this behavior?

**Comment by ning0515** [comment]
> Could you add a test case that tests this behavior?

@macsko PTAL.

I have added a test for this case. To ensure that the delete operation occurs before `q.workers[key] = nil`, I used `time.Sleep` to successfully verify this. However, it seems that using only fakeClock cannot achieve this, so I added a channel to control the execution. I hope this doesn't make the test difficult to understand.

File: pkg/controller/tainteviction/timed_workers_test.go [hunk 1]
```diff
@@ -154,3 +154,39 @@ func TestCancelAndReadd(t *testing.T) {
...
+		}
+		wait = false
+		wg.Done()
+		return nil
+	})
+	now := time.Now()
+	then := now.Add(10 * time.Second)
+	fakeClock := testingclock.NewFakeClock(now)
+	queue.clock = fakeClock
+	queue.AddWork(context.TODO(), NewWorkArgs("1", "1"), now, now)
```
[the remark this answers is not in the document]
Comment (ning0515) [reply pkg/controller/tainteviction/timed_workers_test.go:180]: OK.   I noticed that the other tests in this file also do not use context in the `queue.AddWork`. I will modify them together.

File: pkg/controller/tainteviction/timed_workers_test.go [hunk 2]
```diff
@@ -154,3 +154,39 @@ func TestCancelAndReadd(t *testing.T) {
...
+	logger, _ := ktesting.NewTestContext(t)
+	queue.CancelWork(logger, NewWorkArgs("1", "1").KeyFromWorkArgs())
+	firstWorkerDelete <- true
+	<-firstWorkerDone
```
[the remark this answers is not in the document]
Comment (ning0515) [reply pkg/controller/tainteviction/timed_workers_test.go]: > The channel logic should be different. With the current behavior, we are not sure the `CancelWork` will be called **after** the worker ran.
> 
> ```go
> firstWorkerDispatched := make(chan struct{})
> cancelWorkDone := make(chan struct{})
> ...
> func(...) {
>   ...
>   if wait {
>     firstWorkerDispatched <- struct{}{}
>     <-cancelWorkDone
>   }
>   ...
> }
> ...
> <-firstWorkerDispatched
> queue.CancelWork(...)
> cancelWorkDone <- struct{}{}
> ```
> 
> I think, you also need to make sure to run the second `AddWork` after the first worker was finished (by using `GetWorkerUnsafe` probably).

After this optimization is completed：
```go
			if _, exists := q.workers[key]; exists {
				q.workers[key] = nil
			}
```
Once CancelWork is finished, the `queue.workers` will not change regardless of whether the first worker is done or not. I tried using `queue.TryLock()` and `GetWorkerUnsafe()` , but I couldn't determine if the first worker had finished. Therefore, I chose to add a `time.Sleep` to wait for the first worker to complete. I reviewed other tests and found that they also use `time.Sleep`. I'm not sure if this conforms to community standards.

[the remark this answers is not in the document]
Comment (macsko) [reply pkg/controller/tainteviction/timed_workers_test.go]: It's not a good idea just to sleep in tests. You can use `PollUntilContextTimeout` instead:

```go
wait.PollUntilContextTimeout(ctx, 100*time.Millisecond, wait.ForeverTestTimeout, true, func(ctx context.Context) (bool, error) {
	worker := queue.GetWorkerUnsafe("1/1")
	return worker == nil, nil
})
```

File: pkg/controller/tainteviction/timed_workers_test.go [hunk 3]
```diff
@@ -133,24 +137,64 @@ func TestCancelAndReadd(t *testing.T) {
...
+	queue.AddWork(ctx, NewWorkArgs("1", "1"), now, now)
+	<-firstWorkerDispatched
+	queue.CancelWork(logger, NewWorkArgs("1", "1").KeyFromWorkArgs())
+	cancelWorkDone <- struct{}{}
+	err := wait.PollUntilContextTimeout(ctx, 100*time.Millisecond, wait.ForeverTestTimeout, true, func(ctx context.Context) (bool, error) {
+		worker := queue.GetWorkerUnsafe(NewWorkArgs("1", "1").KeyFromWorkArgs())
+		return worker == nil, nil
+	})
+	if err != nil {
+		t.Fatal(err)
```
Comment (macsko) [inline pkg/controller/tainteviction/timed_workers_test.go:191]: Let's use `t.Errorf` with meaningful message

Comment (ning0515) [reply pkg/controller/tainteviction/timed_workers_test.go]: Done.  Thank you for your guidance.

**Comment by macsko** [comment]
Great!
/lgtm

**Comment by kerthcet** [comment]
/assign
Will take a look later.

File: pkg/controller/tainteviction/timed_workers.go [hunk 4]
```diff
@@ -108,7 +108,9 @@ func (q *TimedWorkerQueue) getWrappedWorkerFunc(key string) func(ctx context.Con
 		if err == nil {
 			// To avoid duplicated calls we keep the key in the queue, to prevent
 			// subsequent additions.
-			q.workers[key] = nil
+			if _, exists := q.workers[key]; exists {
```
Comment (kerthcet) [inline pkg/controller/tainteviction/timed_workers.go:111]: I'd like to argu about the necessary to `set nil` here, the stale state causes the bug in fact, what's the scenario behind? `Once the nodeTaint manager deletes the Pod, before calling the cancelWork, we'll have more workers to add?` Then we can skip them.
```
func (q *TimedWorkerQueue) AddWork(ctx context.Context, args *WorkArgs, createdAt time.Time, fireAt time.Time) {
// ...
	if _, exists := q.workers[key]; exists {
		logger.Info("Trying to add already existing work, skipping", "args", args)
		return
	}
}
```

Comment (ning0515) [reply pkg/controller/tainteviction/timed_workers.go:111]: @kerthcet 
I found the author's explanation in the first commit of the TaintEvictionController:
https://github.com/kubernetes/kubernetes/pull/40355/files#r100683994

I believe that this scenario is currently impossible because the `podUpdateQueue` itself ensures that a pod is only processed once at a time. Therefore, theoretically speaking, unless `tc.taintEvictionQueue.AddWork` is called multiple times by somebody, it is impossible for the same key to appear in the `taintEvictionQueue`. 

This design can be understood as a precaution by the author to prevent unexpected multiple calls (even though our analysis shows that this won't happen).

If you think it's necessary, I can delete both pieces of code below.
https://github.com/kubernetes/kubernetes/blob/2d0a4f75560154454682b193b42813159b20f284/pkg/controller/tainteviction/timed_workers.go#L127

https://github.com/kubernetes/kubernetes/blob/2d0a4f75560154454682b193b42813159b20f284/pkg/controller/tainteviction/timed_workers.go#L111

Comment (ning0515) [reply pkg/controller/tainteviction/timed_workers.go:111]: @kerthcet
I found the author's explanation in the first commit of the TaintEvictionController:
https://github.com/kubernetes/kubernetes/pull/40355/files#r100683994

I believe that this scenario is currently impossible because the podUpdateQueue itself ensures that a pod is only processed once at a time. Therefore, theoretically speaking, unless tc.taintEvictionQueue.AddWork is called multiple times by somebody, it is impossible for the same key to appear in the taintEvictionQueue.

This design can be understood as a precaution by the author to prevent unexpected multiple calls (even though our analysis shows that this won't happen).

If you think it's necessary, I can delete both pieces of code below.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/tainteviction/timed_workers.go#L127-L130

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/tainteviction/timed_workers.go#L108-L112

Comment (kerthcet) [reply pkg/controller/tainteviction/timed_workers.go:111]: Once workFunc processed, which means the pod is deleted, even we have more events called with `AddWorker`, it will fail in the `deletePodHandler` because Pod is not found, so I think it's fine to delete the key directly here.

Wrap the rare case again and again will make the code hard to read in the future I think, so let's just remove it.

Comment (ning0515) [reply pkg/controller/tainteviction/timed_workers.go]: @kerthcet  Done. PTAL.

**Review by kerthcet — COMMENTED** [review]
Right now, once workFunc triggered, the worker key will be deleted directly, then once pod deletion event comes in, it will not be added to the worker, but instead invoke the `cancelWorkWithEvent`, and since worker key not exist anymore, skipped.
/lgtm
/approve

Thanks @ning0515

**Comment by kerthcet** [comment]
Since not an urgent bug, I think no need to cherry-pick.
