### PR TITLE
e2e: Remove kubeadm-ism in DNS HostNetwork test

### LINKED ISSUE #114666: E2E test for for ExpandedDNSConfig has a kubeadm-ism
### Which jobs are flaking?

#112824 added an E2E test that assumes that a service named "kube-dns" exists in the "kube-system" namespace.  This is a kubeadm-ism, and the test fails if the cluster DNS is not configured the way kubeadm configures it.  

Although this E2E test isn't a conformance test, making it functional on non-kubeadm clusters would increase its utility for distributors that may wish to run this E2E test as a conformance test.  

### Which tests are flaking?

[sig-network] DNS HostNetwork should resolve DNS of partial qualified names for services on hostNetwork pods with dnsPolicy: ClusterFirstWithHostNet

### Since when has it been flaking?

Since we ran it on an OpenShift cluster.  https://github.com/openshift/kubernetes/pull/1432

### Testgrid link

_No response_

### Reason for failure (if possible)

The test makes assumptions about how the cluster DNS is configured.  

### Anything else we need to know?

The test uses `dnsPolicy: ClusterFirst` (not `dnsPolicy: None`), so it does not need to specify `dnsConfig.nameservers`, as far as I can tell.  Omitting `dnsConfig.nameservers` obviates the need to look up the service.  I believe that the service lookup was left in https://github.com/kubernetes/kubernetes/pull/112824 as an oversight during the development of the test when it was changed from specifying "None" to specifying "ClusterFirst": https://github.com/kubernetes/kubernetes/compare/5fcdde0a0a82b052bb67cd764150725f2ca73dd9..1098ff63f34673ef9eec06572cbfaf49cea93222

Cc: @gjkim42

### Relevant SIG(s)

/sig network

### PR DESCRIPTION
**Pull request by Miciah**
The "[sig-network] DNS HostNetwork should resolve DNS of partial qualified names for services on hostNetwork pods with dnsPolicy: ClusterFirstWithHostNet" test assumes that a service named "kube-dns" exists in the "kube-system" namespace.  This assumption is valid if the cluster was configured using kubeadm, but the assumption may be invalid otherwise.

As the test uses `dnsPolicy: ClusterFirst` (as opposed to `dnsPolicy: None`), it does not need to specify `dnsConfig.nameservers`.  Omitting `dnsConfig.nameservers` obviates the need to look up the service.

Follow-up to #112824.

* `test/e2e/network/dns.go`: Don't look up or use the "kube-dns" cluster IP address as it might not exist on clusters that were not configured using kubeadm.

#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

Makes the "[sig-network] DNS HostNetwork should resolve DNS of partial qualified names for services on hostNetwork pods with dnsPolicy: ClusterFirstWithHostNet" test functional on non-kubeadm clusters.  

#### Which issue(s) this PR fixes:

Fixes #114666.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
kube-dns is actually the legacy service name that is still in use in coredns and expected to be the default service name of the k8s dns privider. kubeadm follows the naming but is not where it originated.

https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#introduction

it becomes a question whether any dns server deployed on k8s should have its service named kube-dns. likely not, but this test is not in conformance(?) thus it targets internal k8s testing and not the wider external audience.

/sig network

File: test/e2e/network/dns.go [hunk 1]
```diff
@@ -559,11 +559,6 @@ var _ = common.SIGDescribe("DNS", func() {
 	})
 
 	ginkgo.It("should work with the pod containing more than 6 DNS search paths and longer than 256 search list characters", func(ctx context.Context) {
-		ginkgo.By("Getting the kube-dns IP")
-		svc, err := f.ClientSet.CoreV1().Services("kube-system").Get(ctx, "kube-dns", metav1.GetOptions{})
```
Comment (aojea) [inline test/e2e/network/dns.go:563]: @gjkim42 is ok to remove the Service ClusterIP for this test?
https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2595-expanded-dns-config

if is not possible, we can just add a Skip if the service Get returns ErrNotFound

Comment (gjkim42) [reply test/e2e/network/dns.go:563]: > As the test uses `dnsPolicy: ClusterFirst` (as opposed to `dnsPolicy: None`), it does not need to specify `dnsConfig.nameservers`. Omitting `dnsConfig.nameservers` obviates the need to look up the service.

This makes sense. I think it is ok to remove it.

**Comment by Miciah** [comment]
Sorry, forgot to gofmt...

**Review by gjkim42 — COMMENTED** [review]
Getting the kube-dns IP thing is an unnecessary part of this test. 
(I think I forgot to remove it after changing DNSPolicy from `None` to `ClusterFirst`.)

/lgtm

**Comment by aojea** [comment]
/lgtm
/approve

Thanks both for the quick response and the detailed explanations

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-ubuntu-gce-network-policies

this job runs the test ^^

**Comment by aojea** [comment]
> Kubernetes e2e suite: [It] [sig-network] DNS should work with the pod containing more than 6 DNS search paths and longer than 256 search list characters	

test is passing, the failing test is unrelated

> Kubernetes e2e suite: [It] [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for multiple CRDs of different groups [Conformance] expand_more	

/test pull-kubernetes-e2e-gce
