### PR TITLE
fix: adding padding the encoded docker auth field

### LINKED ISSUE #82147: docker-credential-desktop doesn't pad the auth field
**What happened**:

docker now provides a new favorite way to store the credentials with the variable credsStore in the file ~/.docker/config 

it it is set to desktop, which will be using the executable docker-credential-desktop whose source code is https://github.com/docker/docker-credential-helpers

docker-credential-desktop doesn't pad the auth field. 

So, if we use the command 

```
kubectl create secret generic regcred  --type=kubernetes.io/dockerconfigjson --from-file=.dockerconfigjson=~/.docker/config.json
```
k8s credential provider won't be able to decode the field because of the error

Failed to pull image "myrepo/myimage:tag": illegal base64 data at input byte

**What you expected to happen**:

Image pulled normally

**How to reproduce it (as minimally and precisely as possible)**:

open docker config file, and have credsStore set to desktop. 
Run docker login and then use the ~/.docker/plaintext-passwords.json to create a k8s dockerconfigjson secret, the error will directly show

**Anything else we need to know?**:
I wrote a patch that I will submit

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:38:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"
- Cloud provider or hardware configuration:
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631
- OS (e.g: `cat /etc/os-release`):
Mac
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by bbourbie**
The docker-credential-desk does not pad anymore the auth field.
it is then possible to have a not padded field.

this fix is to padded the field before encoding it.

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

It fixes a little bug

**Which issue(s) this PR fixes**:

Fixes #82147
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
No user-facing change

```release-note
k8s dockerconfigjson secrets are now compatible with docker config desktop authentication credentials files
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by bbourbie** [comment]
I registered myself to CLA, this comment is just to make k8s-ci-robot  and re-run the checks

**Comment by bbourbie** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

Re-run checks

**Comment by bbourbie** [comment]
I think my PR is ready.
I know the tests are still pending because the label /ok-to-test is missing.
Not sure what to do first, so I am assigning it to you.
/assign @erictune

**Comment by BenTheElder** [comment]
/remove-sig apps
/sig node
/sig auth
/priority important-soon
this probably (?) needs a short release note

**Comment by bbourbie** [comment]
I don't think my change made the test fail. 
let's re-run it to be sure.
/retest

**Comment by bbourbie** [comment]
```release-note
k8s dockerconfigjson secrets are compatible docker config desktop authentication credentials files
```

**Comment by bbourbie** [comment]
> /remove-sig apps
> /sig node
> /sig auth
> /priority important-soon
> this probably (?) needs a short release note

thank you. 
I added a release note.

File: pkg/credentialprovider/config.go [hunk 1]
```diff
@@ -282,6 +282,9 @@ func (ident DockerConfigEntry) MarshalJSON() ([]byte, error) {
 // decodeDockerConfigFieldAuth deserializes the "auth" field from dockercfg into a
 // username and a password. The format of the auth field is base64(<username>:<password>).
 func decodeDockerConfigFieldAuth(field string) (username, password string, err error) {
+	if i := len(field) % 4; i != 0 {
```
Comment (mattjmcnaughton) [inline pkg/credentialprovider/config.go]: From a first read, I'm not sure how `len(field) % 4 lets us know whether we need to add the padding or not.

Could you share more?

Also, perhaps this is an opportunity for a descriptive variable name? i.e.

```
shouldAddPadding := len(field) % 4 != 0
```

**Review by mattjmcnaughton — COMMENTED** [review]
Thanks for your pr!

Can you share more about if this will have any issues with credentials generated in the "old" manner? In other words, is this change backwards compatible?

Also, do you have a sense of how difficult it would be to add a unit test for this? This seems like important functionality to ensure works going forward.

File: pkg/credentialprovider/config.go (hunk 1 above)
Comment (bbourbie) [reply pkg/credentialprovider/config.go]: Thank you for your guidance. 
I pushed another MR. 
Let me know if more work is to be done

File: pkg/credentialprovider/config.go [hunk 2]
```diff
@@ -282,7 +282,14 @@ func (ident DockerConfigEntry) MarshalJSON() ([]byte, error) {
 // decodeDockerConfigFieldAuth deserializes the "auth" field from dockercfg into a
 // username and a password. The format of the auth field is base64(<username>:<password>).
 func decodeDockerConfigFieldAuth(field string) (username, password string, err error) {
+
+	// encoded base64 field length should be a multiple of 4 if it's correctly padded
+	// if not, let's add the padding character = to reach a multiple of 4
+	if PaddingLength := len(field) % 4; PaddingLength != 0 {
```
Comment (mattjmcnaughton) [inline pkg/credentialprovider/config.go]: Nit: In Golang, variables defined within the function follow camel case (i.e. `paddingLength`).

File: pkg/credentialprovider/config.go [hunk 3]
```diff
@@ -282,7 +282,14 @@ func (ident DockerConfigEntry) MarshalJSON() ([]byte, error) {
 // decodeDockerConfigFieldAuth deserializes the "auth" field from dockercfg into a
 // username and a password. The format of the auth field is base64(<username>:<password>).
 func decodeDockerConfigFieldAuth(field string) (username, password string, err error) {
+
+	// encoded base64 field length should be a multiple of 4 if it's correctly padded
```
Comment (mattjmcnaughton) [inline pkg/credentialprovider/config.go]: This comment is quite helpful.

Nit for the variable name - what if we did `s/paddingLength/paddingLengthToAdd`? (Ultimately up to you... this is a bit of personal preference).

**Review by mattjmcnaughton — COMMENTED** [review]
Thanks for the  updates and unit testing :)

Just small nits from me. Feel free to ping me when you make the changes and I can take another look / mark as "lgtm".

File: pkg/credentialprovider/config.go (hunk 2 above)
Comment (bbourbie) [reply pkg/credentialprovider/config.go]: Good catch, these are my first Golang lines of code and I didn't know that rule :)

File: pkg/credentialprovider/config.go (hunk 3 above)
Comment (bbourbie) [reply pkg/credentialprovider/config.go]: paddingLengthToAdd is better and makes it even more crystal clear what these lines are doing.

**Comment by bbourbie** [comment]
> @bbourbie: The following test **failed**, say `/retest` to rerun them all:
> 
> Test name	Commit	Details	Rerun command
> pull-kubernetes-bazel-test	[347e103](https://github.com/kubernetes/kubernetes/commit/347e103fc6d5c265e5fe8a4bd2189e26264683b5)	[link](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/82148/pull-kubernetes-bazel-test/1168592465381298180)	`/test pull-kubernetes-bazel-test`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=82148). [Your PR dashboard](https://gubernator.k8s.io/pr/bbourbie). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

/retest

**Comment by bbourbie** [comment]
@mattjmcnaughton thanks for having another look.

**Review by mattjmcnaughton — APPROVED** [review]
Congrats on your first go code :)

Marking lgtm providing this retains backwards compatibility. 

/lgtm

/test pull-kubernetes-kubemark-e2e-gce-big
/test pull-kubernetes-e2e-gce-100-performance
/lgtm

File: pkg/credentialprovider/config.go [hunk 4]
```diff
@@ -282,7 +282,14 @@ func (ident DockerConfigEntry) MarshalJSON() ([]byte, error) {
...
+	// if not, let's add the padding character = to reach a multiple of 4
+	if paddingLengthToAdd := len(field) % 4; paddingLengthToAdd != 0 {
```
Comment (liggitt) [inline pkg/credentialprovider/config.go]: if we do this, suggest this instead:
```
if (len(field) % 4) == 0 {
  // decode padded data
  decoded, err = base64.StdEncoding.DecodeString(field)
} else {
  // decode unpadded data
  decoded, err = base64.RawStdEncoding.DecodeString(field)
}
```

Comment (bbourbie) [reply pkg/credentialprovider/config.go]: I agree

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

/assign @deads2k 

After sign off from @deads2k , this should be good to go :)

**Comment by liggitt** [comment]
considerations for accepting this:
* "accept data we previously considered bad" seems likely to lead to more data of that nature, which will not work with old clusters in hard-to-understand ways
* the alternative is the data not working with *all* clusters in hard-to-understand ways
* the producer of the data we currently consider bad is the named owner of the format

/lgtm
/approve

**Comment by deads2k** [comment]
> considerations for accepting this:
> 
> * "accept data we previously considered bad" seems likely to lead to more data of that nature, which will not work with old clusters in hard-to-understand ways

I would accept this.  Question about downgrade though, does the community support downgrading clusters and nodes?

**Comment by liggitt** [comment]
> Question about downgrade though, does the community support downgrading clusters and nodes?

I was actually thinking of skew scenarios where a server at version N has kubelets at versions N, N-1, N-2 running against it. This change would allow the kubelet at version N to work, but not the N-1/N-2 ones.
