### PR TITLE
kubeadm: rework the FetchInitConfigurationFromCluster node flags

### LINKED ISSUE #3244: Regression when upgrading worker nodes using kubeadm v1.34.1: could not remove the CRI socket annotation from Node: not found
Starting with kubeadm 1.34 (specifically 1.34.1, we haven't tested 1.34.0 yet), we're experiencing issues trying to upgrade existing clusters.
When using kubeadm to upgrade the control-plane, the upgrade finishes without issues. However, when trying to upgrade the worker nodes (using `kubeadm upgrade node`), the upgrade fails with the following error message:

```
I0924 09:27:39.744620 1384202 patchnode.go:47] [patchnode] Removing the CRI socket annotation from Node "w1.k8s-test-1"
error: error execution phase kubelet-config: could not remove the CRI socket annotation from Node "w1.k8s-test-1": nodes "w1.k8s-test-1" not found
```

It looks like kubeadm is using the wrong hostname to annotate the node. In our setup, nodes are added to the cluster using the complete FQDN, while the hostname on the node itself is configured using the shorthands:

```
# kubectl get nodes
[...]
w1.k8s-test-1.my.tld   Ready    worker          343d   v1.33.1

# hostname
w1.k8s-test-1 # same as the contents of /etc/hostname

# hostname -A
w1.k8s-test-1.my.tld w1.k8s-test-1 w1.k8s-test-1 w1.k8s-test-1 # the FQDN is taken from the /etc/hosts file
```

Manually changing the node hostname, then executing the upgrade and changing it back afterwards works just fine without any issues. Additionally, this also never caused issues in previous upgrades (1.33.x and earlier).

My guess is that something changed with the release of 1.34, although I haven't had the time to pinpoint this to a specific change just yet.

For context, here's the complete log of the attempted upgrade using `--v=5`:

```
# kubeadm upgrade node --v=5
I0924 09:27:39.348452 1384202 node.go:171] assuming this is not a control plane node because "/etc/kubernetes/manifests/kube-apiserver.yaml" is missing
I0924 09:27:39.349232 1384202 envvar.go:172] "Feature gate default state" feature="InOrderInformers" enabled=true
I0924 09:27:39.349251 1384202 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
I0924 09:27:39.349261 1384202 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false
I0924 09:27:39.349272 1384202 envvar.go:172] "Feature gate default state" feature="ClientsAllowCBOR" enabled=false
I0924 09:27:39.349282 1384202 envvar.go:172] "Feature gate default state" feature="ClientsPreferCBOR" enabled=false
I0924 09:27:39.349323 1384202 cert_rotation.go:141] "Starting client certificate rotation controller" logger="tls-transport-cache"
[upgrade] Reading configuration from the "kubeadm-config" ConfigMap in namespace "kube-system"...
[upgrade] Use 'kubeadm init phase upload-config kubeadm --config your-config-file' to re-upload it.
I0924 09:27:39.369147 1384202 kubeproxy.go:55] attempting to download the KubeProxyConfiguration from ConfigMap "kube-proxy"
W0924 09:27:39.719771 1384202 configset.go:77] Warning: No kubeproxy.config.k8s.io/v1alpha1 config is loaded. Continuing without it: configmaps "kube-proxy" is forbidden: User "system:node:w1.k8s-test-1.my.tld" cannot get resource "configmaps" in API group "" in the namespace "kube-system": no relationship found between node 'w1.k8s-test-1.my.tld' and this object
I0924 09:27:39.719818 1384202 kubelet.go:73] attempting to download the KubeletConfiguration from ConfigMap "kubelet-config"
I0924 09:27:39.723790 1384202 initconfiguration.go:114] skip CRI socket detection, fill with the default CRI socket unix:///var/run/containerd/containerd.sock
I0924 09:27:39.724404 1384202 interface.go:432] Looking for default routes with IPv4 addresses
I0924 09:27:39.724416 1384202 interface.go:437] Default route transits interface "bond0"
I0924 09:27:39.725842 1384202 interface.go:209] Interface bond0 is up
I0924 09:27:39.725966 1384202 interface.go:257] Interface "bond0" has 3 addresses :[1.2.3.4/26 aaaa:bbbb::cccc:dddd/120 fe80::a:b:c:d/64].
I0924 09:27:39.725986 1384202 interface.go:224] Checking addr  1.2.3.4/26.
I0924 09:27:39.726002 1384202 interface.go:231] IP found 1.2.3.4
I0924 09:27:39.726019 1384202 interface.go:263] Found valid IPv4 address 1.2.3.4 for interface "bond0".
I0924 09:27:39.726033 1384202 interface.go:443] Found active IP 1.2.3.4 
[upgrade/preflight] Running pre-flight checks
I0924 09:27:39.726131 1384202 checks.go:498] running all checks
[upgrade/preflight] Skipping prepull. Not a control plane node.
[upgrade/control-plane] Skipping phase. Not a control plane node.
[upgrade/kubeconfig] Skipping phase. Not a control plane node.
W0924 09:27:39.737992 1384202 postupgrade.go:116] Using temporary directory /etc/kubernetes/tmp/kubeadm-kubelet-config1152807108 for kubelet config. To override it set the environment variable KUBEADM_UPGRADE_DRYRUN_DIR
[upgrade] Backing up kubelet config file to /etc/kubernetes/tmp/kubeadm-kubelet-config1152807108/config.yaml
W0924 09:27:39.742437 1384202 utils.go:69] The recommended value for "resolvConf" in "KubeletConfiguration" is: /run/systemd/resolve/resolv.conf; the provided value is: /etc/kubernetes/resolv.conf
[patches] Applied patch of type "application/strategic-merge-patch+json" to target "kubeletconfiguration"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
I0924 09:27:39.744620 1384202 patchnode.go:47] [patchnode] Removing the CRI socket annotation from Node "w1.k8s-test-1"
error: error execution phase kubelet-config: could not remove the CRI socket annotation from Node "w1.k8s-test-1": nodes "w1.k8s-test-1" not found
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:262
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:450
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade.newCmdNode.func1
        k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade/node.go:97
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.9.1/command.go:1015
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.9.1/command.go:1148
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.9.1/command.go:1071
k8s.io/kubernetes/cmd/kubeadm/app.Run
        k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:48
main.main
        k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        runtime/proc.go:283
runtime.goexit
        runtime/asm_amd64.s:1700
```

As mentioned before, this issue does not happen when upgrading control-plane nodes (which have similar hostname configurations) using both `kubeadm upgrade plan && kubeadm upgrade apply` (for the first control-plane node) and `kubeadm upgrade node` (for additional control-plane nodes). It only happens when this involves a regular worker node.

Has anyone else experienced this issue yet? Our cluster upgrades are automated using Ansible, so it's been the same tool calls and upgrade workflows for years - only now it's starting to cause issues.

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

The newControlPlane flag has been historically problematic, since
it implies that the function FetchInitConfigurationFromCluster
cannot handle the cases where a node is worker node but
we still want to fetch its NodeRegistrationOptions conditionally,
in cases such as "upgrade node" for workers.

To fix this issue, replace the flag newControlPlaneNode with
two new flags getNodeRegistration and getAPIEndpoint.

If getNodeRegistration is true, we fetch the NRO, and if
getAPIEndpoint is true, we fetch the API endpoint for
that node.

Additionally, rename skipComponentConfigs to getComponentConfigs
for consistency and flip its value accordingly everywhere.

#### Which issue(s) this PR is related to:

fixes https://github.com/kubernetes/kubeadm/issues/3244

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: fixed a bug where the node registration information for a given node was not fetched correctly during "kubeadm upgrade node" and the node name can end up being incorrect in cases where the node name is not the same as the host name.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
ext tests running
https://github.com/neolit123/kubeadm-test/actions/workflows/k8s-test-pr.yaml

File: cmd/kubeadm/app/cmd/upgrade/node.go [hunk 1]
```diff
@@ -209,7 +204,9 @@ func newNodeData(cmd *cobra.Command, nodeOptions *nodeOptions, out io.Writer) (*
 	// Fetches the cluster configuration
 	// NB in case of control-plane node, we are reading all the info for the node; in case of NOT control-plane node
 	//    (worker node), we are not reading local API address and the CRI socket from the node object
-	initCfg, err := configutil.FetchInitConfigurationFromCluster(client, nil, "upgrade", !isControlPlaneNode, false)
+	isNewNode := false
```
Comment (HirazawaUi) [inline cmd/kubeadm/app/cmd/upgrade/node.go]:
```suggestion
	isExistingNode := true
```
I believe this is the cause of kubernetes/kubeadm#3244. When upgrading a node, we need to obtain the node name and CRI socket through GetNodeRegistration, so this should be set to true.

File: cmd/kubeadm/app/cmd/upgrade/node.go [hunk 2]
```diff
@@ -209,7 +204,9 @@ func newNodeData(cmd *cobra.Command, nodeOptions *nodeOptions, out io.Writer) (*
 	// Fetches the cluster configuration
 	// NB in case of control-plane node, we are reading all the info for the node; in case of NOT control-plane node
```
Comment (HirazawaUi) [inline cmd/kubeadm/app/cmd/upgrade/node.go]: Additionally, the corresponding comments need to be updated accordingly.

File: cmd/kubeadm/app/util/staticpod/utils.go [hunk 3]
```diff
@@ -419,3 +419,18 @@ func DeepHashObject(hasher hash.Hash, objectToWrite interface{}) {
 	hasher.Reset()
 	fmt.Fprintf(hasher, "%v", dump.ForHash(objectToWrite))
 }
+
+// IsControlPlaneNode returns true if the kube-apiserver static pod manifest is present
+// on the host.
+func IsControlPlaneNode() bool {
```
Comment (HirazawaUi) [inline cmd/kubeadm/app/util/staticpod/utils.go:425]: I'm concerned that this detection method might not be reliable – determining whether the current node is a control plane node based solely on the presence of static Pod YAML files on the node.

I'm considering an alternative approach that would be more complex but also more reliable and secure. Since we only check whether `isControlPlaneNode` is true when `isExistingNode` is true, this means we could delay the check to determine if the node is a control plane node. Once `isExistingNode` is true, we can retrieve the Node object through the Node API, and finally determine whether the node is a control plane node based on that Node object.

File: cmd/kubeadm/app/cmd/upgrade/node.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/cmd/upgrade/node.go]: right, that makes the names of these comments not so appropriate yet again. i think i will make them more explicit ALA getNodeInfo, getAPIEndpoint.

File: cmd/kubeadm/app/util/staticpod/utils.go (hunk 3 above)
Comment (neolit123) [reply cmd/kubeadm/app/util/staticpod/utils.go:425]: this is actually the current way kubeadm is doing it in multiple places. i did not refactor all of them.
your suggestion might work, but feels like a separate effort that can be applied only on master.
IIRC, there were problems with that approach at some places because there was no client yet that can read Nodes. i could be wrong.

File: cmd/kubeadm/app/cmd/upgrade/node.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/cmd/upgrade/node.go]: done in https://github.com/kubernetes/kubernetes/compare/d90d0f7ccee1ffd8de534e1cd96d062f0c10857c..ed68c1ac63278edd27aba2769ce62b9153475308

File: cmd/kubeadm/app/util/staticpod/utils.go (hunk 3 above)
Comment (HirazawaUi) [reply cmd/kubeadm/app/util/staticpod/utils.go:425]: Make sense.

**Comment by neolit123** [comment]
/cc @SataQiu
please double check if you have a moment.

File: cmd/kubeadm/app/cmd/upgrade/diff.go [hunk 4]
```diff
@@ -106,7 +107,7 @@ func validateManifestsPath(manifests ...string) (err error) {
 }
 
 // FetchInitConfigurationFunc defines the signature of the function which will fetch InitConfiguration from cluster.
-type FetchInitConfigurationFunc func(client clientset.Interface, printer output.Printer, logPrefix string, newControlPlane, skipComponentConfigs bool) (*kubeadmapi.InitConfiguration, error)
+type FetchInitConfigurationFunc func(client clientset.Interface, printer output.Printer, logPrefix string, getNodeRegistration, getAPIEndpoint, skipComponentConfigs bool) (*kubeadmapi.InitConfiguration, error)
```
Comment (SataQiu) [inline cmd/kubeadm/app/cmd/upgrade/diff.go]:
```suggestion
type FetchInitConfigurationFunc func(client clientset.Interface, printer output.Printer, logPrefix string, getNodeRegistration, getAPIEndpoint, getComponentConfigs bool) (*kubeadmapi.InitConfiguration, error)
```

File: cmd/kubeadm/app/cmd/upgrade/diff_test.go [hunk 5]
```diff
@@ -44,7 +44,7 @@ func createTestRunDiffFile(contents []byte) (string, error) {
 	return file.Name(), nil
 }
 
-func fakeFetchInitConfig(client clientset.Interface, printer output.Printer, logPrefix string, newControlPlane, skipComponentConfigs bool) (*kubeadmapi.InitConfiguration, error) {
+func fakeFetchInitConfig(client clientset.Interface, printer output.Printer, logPrefix string, getNodeRegistration, getAPIEndpoint, skipComponentConfigs bool) (*kubeadmapi.InitConfiguration, error) {
```
Comment (SataQiu) [inline cmd/kubeadm/app/cmd/upgrade/diff_test.go]:
```suggestion
func fakeFetchInitConfig(client clientset.Interface, printer output.Printer, logPrefix string, getNodeRegistration, getAPIEndpoint, getComponentConfigs bool) (*kubeadmapi.InitConfiguration, error) {
```

File: cmd/kubeadm/app/cmd/upgrade/diff.go (hunk 4 above)
Comment (SataQiu) [reply cmd/kubeadm/app/cmd/upgrade/diff.go]: Is there any omission here? overall LGTM.

**Review by SataQiu — APPROVED** [review]

File: cmd/kubeadm/app/cmd/upgrade/diff.go (hunk 4 above)
Comment (neolit123) [reply cmd/kubeadm/app/cmd/upgrade/diff.go]: updated.
not sure what you mean by omission? this is jus a local func with the same signature so that it can be unit tested with real vs fakeFetchInitConfig.

File: cmd/kubeadm/app/cmd/upgrade/diff_test.go (hunk 5 above)
Comment (neolit123) [reply cmd/kubeadm/app/cmd/upgrade/diff_test.go]: updated.

https://github.com/kubernetes/kubernetes/compare/ed68c1ac63278edd27aba2769ce62b9153475308..b6afe986c625bdb8ccf5d2c2352cdb1d899707b5

**Comment by neolit123** [comment]
thanks for the reviews, i can send backports later today or tomorrow.

**Comment by saschagrunert** [comment]
Any reason to not cherry-pick this into 1.31? This version is still supported until 2025-10-28.

**Comment by HirazawaUi** [comment]
> Any reason to not cherry-pick this into 1.31? This version is still supported until 2025-10-28.

ref: https://github.com/kubernetes/kubeadm/issues/3244#issuecomment-3357923883
