### PR TITLE
Fix tests

### LINKED ISSUE #5496: TestSyncPodsDeletesWithNoPodInfraContainer is flaky
Seeing random failures.

```
I0316 00:07:11.888567   20733 kubelet.go:1288] probe success: bar2
--- FAIL: TestSyncPodsDeletesWithNoPodInfraContainer (0.00s)
	kubelet_test.go:110: expected []string{"list", "list", "list", "list", "inspect_container", "inspect_container", "stop", "create", "start", "inspect_container", "create", "start"}, got []string{"list", "list", "list", "stop", "create", "start", "inspect_container", "create", "start", "list", "inspect_container", "inspect_container"}
W0316 00:07:11.888986   20733 kubelet.go:1014] No ref for pod '1234'
W0316 00:07:11.889004   20733 kubelet.go:1014] No ref for pod '9876'
W0316 00:07:11.889395   20733 kubelet.go:1014] No ref for pod '1234'
W0316 00:07:11.889407   20733 kubelet.go:1014] No ref for pod '9876'
```

### PR DESCRIPTION
**Pull request by yifan-gu**
Fix https://github.com/GoogleCloudPlatform/kubernetes/issues/5496

Also fixed `verifyStringArrayEqualsAnyOrder`

@dchen1107 @vmarmol

### CODE REVIEW

**Comment by yifan-gu** [comment]
As for https://github.com/GoogleCloudPlatform/kubernetes/pull/5466
We need to sync two pods in parallel in this case. So I added a function to verify that docker calls are equal in an unordered way.

File: pkg/kubelet/kubelet_test.go [hunk 1]
```diff
@@ -136,23 +144,15 @@ func verifyStringArrayEquals(t *testing.T, actual, expected []string) {
...
-				}
-			}
-			if !found {
-				t.Errorf("Expected element %q not found in %#v", exp, actual)
-			}
-		}
-	}
-	if invalid {
-		t.Errorf("Expected: %#v, Actual: %#v", expected, actual)
+	var act, exp []string
```
Comment (vmarmol) [inline pkg/kubelet/kubelet_test.go]: Nice :)

**Comment by vmarmol** [comment]
Nice @yifan-gu! LGTM, will merge on green.
