### PR TITLE
 kubeadm: Validate only the first cert entry when external ca mode is used

### LINKED ISSUE #3011: When using a external rootCA that contains multiple certificates, kubeadm will fail validation.
### What happened?

We are deploying kubernetes using kubeadm using an external ca cert. This external ca cert contains multiple certificates. When kubeadm runs in external CA mode, kubeadm runs validation logic that compares the existing ca certificate file (` /etc/kubernetes/pki/ca.crt`) to the newly rendered 'dummy' kubeconfig that only contains the first certificate from `ca.crt`. The bytes are then compared & fails the check since they are different.

The `ca.crt` used within kubeconfig validation is read here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L292

The original `ca.crt` is read here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L257

The check is happening here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L268

### What did you expect to happen?

This check should only validate the first certificate from ca.crt if validation is only checking a single certificate within kubeconfig.

### How can we reproduce it (as minimally and precisely as possible)?

Create a ca.crt file that contains multiple certificates (example: `intermediary CA2` > `intermediary CA1` > `rootCA`). Run kubeadm in external CA mode. The kubeconfig that is rendered will only contain `Intermediary CA2` while the validation will check the `ca.crt` containing `intermediary CA2` > `intermediary CA1` > `rootCA` compared to kubeconfig containing only `intermediary CA2`

### Anything else we need to know?

In our use case, the `ca.crt` must contain multiple certificates as we have applications that use Kubernetes `Secret`'s of type `kubernetes.io/service-account-token`. This Secret contains the ca.crt. Applications that then use this ca.crt to communicate to the api server (example: python, openssl) will perform validation of the full certificate chain. It's not an issue within `curl` as curl only validates the first intermediary certificate.

### Kubernetes version

<details>
Kubernetes 1.23
</details>

### Cloud provider

<details>
Bare metal install
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


$ uname -a
Linux dal09-qz4-sr07-rk045-s30 5.15.0-1041-ibm-gt kubernetes/kubernetes#44-Ubuntu SMP Mon Aug 14 14:52:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### LINKED ISSUE #123101: When using a external rootCA that contains multiple certificates, kubeadm will fail validation.
### What happened?

We are deploying kubernetes using kubeadm using an external ca cert. This external ca cert contains multiple certificates. When kubeadm runs in external CA mode, kubeadm runs validation logic that compares the existing ca certificate file (` /etc/kubernetes/pki/ca.crt`) to the newly rendered 'dummy' kubeconfig that only contains the first certificate from `ca.crt`. The bytes are then compared & fails the check since they are different.

The `ca.crt` used within kubeconfig validation is read here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L292

The original `ca.crt` is read here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L257

The check is happening here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L268

### What did you expect to happen?

This check should only validate the first certificate from ca.crt if validation is only checking a single certificate within kubeconfig.

### How can we reproduce it (as minimally and precisely as possible)?

Create a ca.crt file that contains multiple certificates (example: `intermediary CA2` > `intermediary CA1` > `rootCA`). Run kubeadm in external CA mode. The kubeconfig that is rendered will only contain `Intermediary CA2` while the validation will check the `ca.crt` containing `intermediary CA2` > `intermediary CA1` > `rootCA` compared to kubeconfig containing only `intermediary CA2`

### Anything else we need to know?

In our use case, the `ca.crt` must contain multiple certificates as we have applications that use Kubernetes `Secret`'s of type `kubernetes.io/service-account-token`. This Secret contains the ca.crt. Applications that then use this ca.crt to communicate to the api server (example: python, openssl) will perform validation of the full certificate chain. It's not an issue within `curl` as curl only validates the first intermediary certificate.

### Kubernetes version

<details>
Kubernetes 1.23
</details>

### Cloud provider

<details>
Bare metal install
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


$ uname -a
Linux dal09-qz4-sr07-rk045-s30 5.15.0-1041-ibm-gt #44-Ubuntu SMP Mon Aug 14 14:52:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by astundzia**
/sig cluster-lifecycle

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
We are deploying kubernetes using kubeadm using an external ca cert file / external ca mode. This external ca cert file contains multiple certificates. When kubeadm runs in external CA mode, kubeadm runs validation logic that compares the entire existing ca certificate file (` /etc/kubernetes/pki/ca.crt`) to the newly rendered 'dummy' kubeconfig that only reads in the first certificate from `ca.crt`. The bytes are then compared & fails the check since they are different -- 1 contains 1+N certificates, the other only contains 1 certificate.

The `ca.crt` used within validation is read here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L292

The original `ca.crt` is read here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L257

The check is happening here:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L268

#### Which issue(s) this PR fixes:
Fixes kubernetes/kubeadm#3011

#### Does this PR introduce a user-facing change?
```YES```

```release-note
kubeadm: during the validation of existing kubeconfig files on disk, handle cases where the "ca.crt" is a bundle and has intermediate certificates. Find a common trust anchor between the "ca.crt" bundle and the CA in the existing kubeconfig on disk instead of treating "ca.crt" as a file containing a single CA.
```

### CODE REVIEW

**Comment by astundzia** [comment]
Working on adding the necessary EasyCLA auth with my org

**Comment by astundzia** [comment]
Tested on kubedm 1.23.X and `master`.

**Comment by astundzia** [comment]
EasyCLA completed

**Comment by astundzia** [comment]
Added some test cases where a ca.crt contains a rootCA + intermediary CA.

**Review by neolit123 — COMMENTED** [review]
thanks for the PR,
i will have a more detailed look next week.

i think such a change would need unit tests.
i will enable CI on the PR
/ok-to-test

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go [hunk 1]
```diff
@@ -264,8 +264,26 @@ func validateKubeConfig(outDir, filename string, config *clientcmdapi.Config) er
...
+	if err != nil {
+		return errors.Errorf("the kubeconfig file %q contains an invalid ca cert", kubeConfigFilePath)
+	}
+	// only fetch the first certificate in the cacert
+	currentCaCert := currentCaCerts[0]
+
+	// Parse the expected certificate authority data
+	expectedCaCerts, err := certutil.ParseCertsPEM(caExpected)
+	if err != nil {
+		return errors.Errorf("the expected base64 encoded ca cert %q could not be parsed as a pem", caExpected)
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:278]:
```suggestion
		return errors.Errorf("the expected base64 encoded CA cert %q could not be parsed as a PEM", caExpected)
```

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go [hunk 2]
```diff
@@ -264,8 +264,26 @@ func validateKubeConfig(outDir, filename string, config *clientcmdapi.Config) er
...
+	}
+
+	// only fetch the first certificate in the cacert. When this is read from file, only the first entry is considered
+	expectedCaCert := expectedCaCerts[0]
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:282]:
```suggestion
	// Only use the first certificate in the expected CA cert list
	expectedCACert := expectedCACerts[0]
```

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go [hunk 3]
```diff
@@ -264,8 +264,26 @@ func validateKubeConfig(outDir, filename string, config *clientcmdapi.Config) er
...
+
+	// Compare the current CA cert to the expected CA cert (which is only 1 entry).
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:284]:
```suggestion
	// Compare the current CA cert to the expected CA cert.
```

**Review by neolit123 — COMMENTED** [review]
i think the change is fine.
added minor nits around wording and naming of vars.

please add a unit test.

**Comment by astundzia** [comment]
Hey, thanks for the comments. I will address the comments & add a unit test this week. Thank you!

**Comment by neolit123** [comment]
/release-note-edit

```release-note
kubeadm: allow to validate "ca.crt" files that contain multiple certificates.
```

**Comment by neolit123** [comment]
> Hey, thanks for the comments. I will address the comments & add a unit test this week. Thank you!

@astundzia any updates?

**Comment by astundzia** [comment]
Hey, working with the dev who ran into this issue at work to get the correct test cases. Please give me a few more days to get some tests up.

**Comment by astundzia** [comment]
Added unit test, addressed comments. Please review when you get a chance. Thanks!

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go [hunk 4]
```diff
@@ -620,6 +618,20 @@ func TestValidateKubeconfigsForExternalCA(t *testing.T) {
 	// create a config with another server URL
 	configWithAnotherServerURL := setupdKubeConfigWithClientAuth(t, caCert, caKey, "https://4.3.2.1:4321", "test-cluster", "myOrg1")
 
+	// create a config with a ca cert containing multiple certificates
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go:621]:
```suggestion
	// create a config with a CA cert containing multiple certificates
```

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go [hunk 5]
```diff
@@ -620,6 +618,20 @@ func TestValidateKubeconfigsForExternalCA(t *testing.T) {
...
+	intermediateCaCert1, intermediateCaKey1 := certstestutil.SetupIntermediateCertificateAuthority(t, caCert, caKey)
+	intermediateCaCert2, intermediateCaKey2 := certstestutil.SetupIntermediateCertificateAuthority(t, intermediateCaCert1, intermediateCaKey1)
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go:623]:
```suggestion
	intermediateCACert1, intermediateCAKey1 := certstestutil.SetupIntermediateCertificateAuthority(t, caCert, caKey)
	intermediateCACert2, intermediateCAKey2 := certstestutil.SetupIntermediateCertificateAuthority(t, intermediateCACert1, intermediateCAKey1)
```

to use the proper camelCase for abbreviations

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go [hunk 6]
```diff
@@ -620,6 +618,20 @@ func TestValidateKubeconfigsForExternalCA(t *testing.T) {
...
+
+	var caCertBundle []*x509.Certificate
+	caCertBundle = append(caCertBundle, caCert, intermediateCaCert1, intermediateCaCert2)
+	caCertBytes, _ := pkiutil.EncodeCertBundlePEM(caCertBundle)
+
+	clusterName := "myOrg1"
+	multipleCaConfig := setupdKubeConfigWithClientAuth(t, intermediateCaCert2, intermediateCaKey2, "https://1.2.3.4:1234", "test-cluster", clusterName)
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go:630]:
```suggestion
	multipleCAConfig := setupdKubeConfigWithClientAuth(t, intermediateCaCert2, intermediateCaKey2, "https://1.2.3.4:1234", "test-cluster", clusterName)
```

File: cmd/kubeadm/app/util/certs/util.go [hunk 7]
```diff
@@ -43,6 +43,19 @@ func SetupCertificateAuthority(t *testing.T) (*x509.Certificate, crypto.Signer)
 	return caCert, caKey
 }
 
+// SetupIntermediateCertificateAuthority is a utility function for kubeadm testing that creates a
+// Intermediate CertificateAuthority cert/key pair
+func SetupIntermediateCertificateAuthority(t *testing.T, parentCert *x509.Certificate, parentKey crypto.Signer) (*x509.Certificate, crypto.Signer) {
+	caCert, caKey, err := pkiutil.NewIntermediateCertificateAuthority(parentCert, parentKey, &pkiutil.CertConfig{
+		Config: certutil.Config{CommonName: "kubernetes Intermediate CA"},
```
Comment (neolit123) [inline cmd/kubeadm/app/util/certs/util.go:50]:
```suggestion
		Config: certutil.Config{CommonName: "kubernetes intermediate CA"},
```

**Review by neolit123 — COMMENTED** [review]
added some more minor comments.
please keep the commit squashed to one.

a question that i have:

 i recall discussions that taking the first cert from a bundle maybe is arbitrary under certain conditions, we are already doing that in at least another location in the code base. but would it make more sense to compare entire bundles i.e. bundleCurrentCert1 == bundleExpCert1, undleCurrentCert2 == bundleExpCert12, ...

what do official specs say about that?

i don't think we should apply the change like that, but asking out of curiosity.
comparing only the first cert ensure we are comparing the CA root, supposedly, while intermediates follow and they can be perhaps different count between the current and expected.

**Comment by astundzia** [comment]
Hey, I will address comments and squash the commits. I added some additional tests to cover this scenario.

The Root Certificate Authority (Root CA) is the fundamental element of the trust model. In terms of certificate validation, it's possible to create a Certificate Authority (CA) bundle that doesn't include the Root CA. As long as the CA bundle and the leaf certificates can trace back to a common trust anchor (a CA), the issued certificate should be valid.

However, you're correct that I should compare more than just the first certificate. Let's consider this (convoluted) scenario:

We have a Certificate Authority chain that includes the Root CA, Intermediate CA1, and Intermediate CA2. At some point, we issue Intermediate CA3 from Intermediate CA1. In this case, we can have a `ca.crt` that includes Intermediate CA1 and Intermediate CA2. The trust chain must include all certificates tracing back to a common trust anchor, which in this case is Intermediate CA1. Certificates issued from Intermediate CA3 should validate against a bundle containing any of the following combinations: {Root CA, Intermediate CA1, Intermediate CA2}, {Root CA, Intermediate CA1}, or {Intermediate CA1}, as long as the trust chain can be resolved.

In this scenario, it would be beneficial to compare all the current `ca.crt` certificates against the expected CA certificate. As long as there's a match, a trust chain should be established.

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go [hunk 8]
```diff
@@ -675,7 +677,138 @@ func TestValidateKubeconfigsForExternalCA(t *testing.T) {
...
+		ClusterConfiguration: kubeadmapi.ClusterConfiguration{
+			CertificatesDir: pkiDir,
+		},
+		LocalAPIEndpoint: kubeadmapi.APIEndpoint{
+			BindPort:         1234,
+			AdvertiseAddress: "1.2.3.4",
+		},
+	}
+
+	// creates CA, write to pkiDir and remove ca.key to get into external CA condition
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go:725]:
```suggestion
	// Creates CA, write to pkiDir and remove ca.key to get into external CA mode
```

that's how we call it (mode) across docs
also capitalization

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go [hunk 9]
```diff
@@ -675,7 +677,138 @@ func TestValidateKubeconfigsForExternalCA(t *testing.T) {
...
+	intermediateCACert2, intermediateCAKey2 := certstestutil.SetupIntermediateCertificateAuthority(t, intermediateCACert1, intermediateCAKey1)
+
+	var caCertBundle []*x509.Certificate
+	caCertBundle = append(caCertBundle, caCert, intermediateCACert1, intermediateCACert2)
+	caCertBytes, _ := pkiutil.EncodeCertBundlePEM(caCertBundle)
+
+	clusterName := "myOrg1"
+
+	// Create a kube config and assign the CA data to the CA bundle, issued from root CA
+	multipleCAConfigRootCAIssuer := setupdKubeConfigWithClientAuth(t, caCert, caKey, "https://1.2.3.4:1234", "test-cluster", clusterName)
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go:739]: a good opportunity to fix this typo?
```suggestion
	multipleCAConfigRootCAIssuer := setupKubeConfigWithClientAuth(t, caCert, caKey, "https://1.2.3.4:1234", "test-cluster", clusterName)
```

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go [hunk 10]
```diff
@@ -675,7 +677,138 @@ func TestValidateKubeconfigsForExternalCA(t *testing.T) {
...
+		LocalAPIEndpoint: kubeadmapi.APIEndpoint{
+			BindPort:         1234,
+			AdvertiseAddress: "1.2.3.4",
+		},
+	}
+
+	// creates CA, write to pkiDir and remove ca.key to get into external CA condition
+	caCert, caKey := certstestutil.SetupCertificateAuthority(t)
+
+	// create a config with a CA cert containing multiple certificates
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go:728]:
```suggestion
	// Create a config with a CA cert containing multiple certificates
```

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go [hunk 11]
```diff
@@ -675,7 +677,138 @@ func TestValidateKubeconfigsForExternalCA(t *testing.T) {
...
+	// Create a kube config and assign the CA data to the CA bundle, issued from intermediate CA 2
+	multipleCAConfigIntermediateCA2Issuer := setupdKubeConfigWithClientAuth(t, intermediateCACert2, intermediateCAKey2, "https://1.2.3.4:1234", "test-cluster", clusterName)
+	multipleCAConfigIntermediateCA2Issuer.Clusters[clusterName].CertificateAuthorityData = caCertBytes
+
+	// create a config with a CA cert containing multiple certificates, omitting the root CA
+	var caCertBundleNoRootCA []*x509.Certificate
+	caCertBundleNoRootCA = append(caCertBundleNoRootCA, intermediateCACert1, intermediateCACert2)
+	caCertBytesNoRootCA, _ := pkiutil.EncodeCertBundlePEM(caCertBundleNoRootCA)
+
+	// Create a kube config and assign the CA data to the CA bundle, issued from intermediate CA 2,
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go:755]:
```suggestion
	// Create a kubeconfig and assign the CA data to the CA bundle, issued from intermediate CA 2,
```

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go [hunk 12]
```diff
@@ -675,7 +677,138 @@ func TestValidateKubeconfigsForExternalCA(t *testing.T) {
...
+
+	// Create a kube config and assign the CA data to the CA bundle, issued from intermediate CA 1
+	multipleCAConfigIntermediateCA1Issuer := setupdKubeConfigWithClientAuth(t, intermediateCACert1, intermediateCAKey1, "https://1.2.3.4:1234", "test-cluster", clusterName)
+	multipleCAConfigIntermediateCA1Issuer.Clusters[clusterName].CertificateAuthorityData = caCertBytes
+
+	// Create a kube config and assign the CA data to the CA bundle, issued from intermediate CA 2
+	multipleCAConfigIntermediateCA2Issuer := setupdKubeConfigWithClientAuth(t, intermediateCACert2, intermediateCAKey2, "https://1.2.3.4:1234", "test-cluster", clusterName)
+	multipleCAConfigIntermediateCA2Issuer.Clusters[clusterName].CertificateAuthorityData = caCertBytes
+
+	// create a config with a CA cert containing multiple certificates, omitting the root CA
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go:750]:
```suggestion
	// Create a config with a CA cert containing multiple certificates, omitting the root CA
```

trying to use consistent capitalization of comments within a function (or even file)

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go [hunk 13]
```diff
@@ -675,7 +677,138 @@ func TestValidateKubeconfigsForExternalCA(t *testing.T) {
...
+	multipleCAConfigNoRootCA.Clusters[clusterName].CertificateAuthorityData = caCertBytesNoRootCA
+
+	if err := pkiutil.WriteCertBundle(pkiDir, kubeadmconstants.CACertAndKeyBaseName, caCertBundleNoRootCA); err != nil {
+		t.Fatalf("failure while saving CA certificate: %v", err)
+	}
+
+	tests := map[string]struct {
+		filesToWrite  map[string]*clientcmdapi.Config
+		initConfig    *kubeadmapi.InitConfiguration
+		expectedError bool
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go:767]: all expected errors in this test are "false", i guess we should have at least one with "true"?

File: cmd/kubeadm/app/util/certs/util.go [hunk 14]
```diff
@@ -43,6 +43,19 @@ func SetupCertificateAuthority(t *testing.T) (*x509.Certificate, crypto.Signer)
...
 }
 
+// SetupIntermediateCertificateAuthority is a utility function for kubeadm testing that creates a
+// Intermediate CertificateAuthority cert/key pair
+func SetupIntermediateCertificateAuthority(t *testing.T, parentCert *x509.Certificate, parentKey crypto.Signer) (*x509.Certificate, crypto.Signer) {
+	caCert, caKey, err := pkiutil.NewIntermediateCertificateAuthority(parentCert, parentKey, &pkiutil.CertConfig{
+		Config: certutil.Config{CommonName: "kubernetes intermediate CA"},
+	})
+	if err != nil {
+		t.Fatalf("failure while generating intermediate CA certificate and key: %v", err)
```
Comment (neolit123) [inline cmd/kubeadm/app/util/certs/util.go:53]:
```suggestion
		t.Fatalf("Failure while generating intermediate CA certificate and key: %v", err)
```

test output messages should be capitalized unlike non-test errors

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go [hunk 15]
```diff
@@ -675,7 +677,138 @@ func TestValidateKubeconfigsForExternalCA(t *testing.T) {
...
+	caCertBundleNoRootCA = append(caCertBundleNoRootCA, intermediateCACert1, intermediateCACert2)
+	caCertBytesNoRootCA, _ := pkiutil.EncodeCertBundlePEM(caCertBundleNoRootCA)
+
+	// Create a kube config and assign the CA data to the CA bundle, issued from intermediate CA 2,
+	// CA is missing root CA certificate.
+	multipleCAConfigNoRootCA := setupdKubeConfigWithClientAuth(t, intermediateCACert2, intermediateCAKey2, "https://1.2.3.4:1234", "test-cluster", clusterName)
+	multipleCAConfigNoRootCA.Clusters[clusterName].CertificateAuthorityData = caCertBytesNoRootCA
+
+	if err := pkiutil.WriteCertBundle(pkiDir, kubeadmconstants.CACertAndKeyBaseName, caCertBundleNoRootCA); err != nil {
+		t.Fatalf("failure while saving CA certificate: %v", err)
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go:761]:
```suggestion
		t.Fatalf("Failure while saving CA certificate: %v", err)
```

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go [hunk 16]
```diff
@@ -264,10 +264,35 @@ func validateKubeConfig(outDir, filename string, config *clientcmdapi.Config) er
...
+	// Parse the current certificate authority data
+	currentCACerts, err := certutil.ParseCertsPEM(caCurrent)
+	if err != nil {
+		return errors.Errorf("the kubeconfig file %q contains an invalid CA cert", kubeConfigFilePath)
+	}
+
+	// Parse the expected certificate authority data
+	expectedCACerts, err := certutil.ParseCertsPEM(caExpected)
+	if err != nil {
+		return errors.Errorf("the expected base64 encoded CA cert %q could not be parsed as a PEM", caExpected)
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:276]: this would print the whole base64 string?
if so i think it should be at the end of the message:
```suggestion
		return errors.Errorf("the expected base64 encoded CA cert could not be parsed as a PEM:\n%q", caExpected)
```

generally users should not see this error as it would be a preparation error on our side - i.e. expected kubeconfig file was malformed. i think we already have tests for that.

**Review by neolit123 — COMMENTED** [review]
thanks for the detailed explanation!
yes, i think that the extended validation against all current CAs makes sense.

the logic and new tests SGTM.
i did another pass over the code, found some minor prior nits and also some new ones.

i think i might request another reviewer to have a quick look, in case we missed something.

**Comment by astundzia** [comment]
Hey, will get the comments addressed and a commit up in the next few days.

**Comment by neolit123** [comment]
> Hey, will get the comments addressed and a commit up in the next few days.

ok, note that code freeze for 1.30 is march 6th.

**Comment by neolit123** [comment]
> Hey, will get the comments addressed and a commit up in the next few days.

@astundzia do you have plans to finish this PR?

**Comment by astundzia** [comment]
Hey, apologies for the lack of commits here. I will try to get this merged in this week!

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go [hunk 17]
```diff
@@ -264,10 +264,35 @@ func validateKubeConfig(outDir, filename string, config *clientcmdapi.Config) er
...
+	for _, currentCACert := range currentCACerts {
+		// Compare the current CA cert to the expected CA cert.
+		// If the certificates match then a common trust anchor was found.
+		if currentCACert.Equal(expectedCACert) {
+			trustAnchorFound = true
+			break
+		}
 	}
+	if !trustAnchorFound {
+		return errors.Errorf("a kubeconfig file %q exists already but could not find trust anchor", kubeConfigFilePath)
```
[the remark this answers is not in the document]
Comment (astundzia) [reply cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:293]: Adjusted, `a kubeconfig file %q exists but does not contain a trusted CA in its current context's cluster. Total CA certificates found:`. I can reword if you think the trust anchor reference makes more sense, but I think most folks will see "trust anchor" and might be confused.

[the remark this answers is not in the document]
Comment (neolit123) [reply cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:293]: ok, please fix the rest of the comments.
also keep the commits squashed to 1. the bots found a merge commit so the PR cannot merge as is
`do-not-merge/contains-merge-commits`

**Comment by neolit123** [comment]
error is:
```
{"Time":"2024-06-28T18:06:14.02662057Z","Action":"output","Package":"k8s.io/kubernetes/cmd/kubeadm/app/phases# k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig [k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.test]
cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go:761:34: undefined: setupdKubeConfigWithClientAuth
cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go:765:43: undefined: setupdKubeConfigWithClientAuth
cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go:769:43: undefined: setupdKubeConfigWithClientAuth
cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go:779:30: undefined: setupdKubeConfigWithClientAuth
```
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/123102/pull-kubernetes-unit/1806748637615624192

File: cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go (hunk 13 above)
Comment (astundzia) [reply cmd/kubeadm/app/phases/kubeconfig/kubeconfig_test.go:789]: Added some negative tests. Reworked some additional logic. Will explain in more detail in a comment.

**Comment by astundzia** [comment]
Hey, I am working on this today, expect to have it up in an hour or so.

I redid a few things, and cleaned up some tests. Once I have it committed ill explain each test in diagrams for clarity.

**Comment by astundzia** [comment]
Sorry for the delay. Please review when you can.

I've reworked the tests, and accurately read in all certificates within kubeconfig.go. I also addressed your comments, but a fair amount changed that I am sure I have some bad formatting again.

Logically, the tests are as follows. This is the certificate chain used in the tests at a high level.


image



For the first 3 tests, there is this CA certificate being used:
image

Test 1. Build a config using a leaf cert issued from the RootCA

Test 2. Build a config using a leaf cert issued from Intermediate CA 1A

Test 3. Build a config using a leaf cert issued from Intermediate CA 2A



For the next two tests, I build a CA cert that looks like this:

image

Test 4. Build a config using a leaf cert issued from Intermediate CA 2B

Test 5. Build a config using a leaf cert issued from Intermediate CA 2A -- This should fail, it is issued from a different CA



For the next test, I wanted to make sure that something issued from a different CA still failed validation.

image

Test 6. Build a config using a leaf cert issued from Intermediate CA 2B -- This should fail, it is issued from a different CA & chain is invalid

**Comment by neolit123** [comment]
/retest
flaky test problem is tracked here
https://github.com/kubernetes/kubernetes/pull/123102

**Review by neolit123 — COMMENTED** [review]
thanks @astundzia 
i verified the changes a couple of times and this seems good to me.

/lgtm
/approve

/cc @SataQiu @carlory 
do you have any review comments on this?

**Comment by neolit123** [comment]
/release-note-edit

```release-note
kubeadm: during the validation of existing kubeconfig files on disk, handle cases where the "ca.crt" is a bundle and has intermediate certificates. Find a common trust anchor between the "ca.crt" bundle and the CA in the existing kubeconfig on disk instead of treating "ca.crt" as a file containing a single CA.
```

**Comment by neolit123** [comment]
> Sorry for the delay. Please review when you can.
> 
> I've reworked the tests, and accurately read in all certificates within kubeconfig.go. I also addressed your comments, but a fair amount changed that I am sure I have some bad formatting again.
> 
> Logically, the tests are as follows. This is the certificate chain used in the tests at a high level.

thanks for the detailed explanation, this helped me navigate the review!

**Comment by neolit123** [comment]
> /cc @SataQiu @carlory do you have any review comments on this?

forgot to put a hold. let's iterate in a new pr if needed.
