### PR TITLE
Fix for kube-proxy to wait for some duration for the node to be defined.

### LINKED ISSUE #37414: Race between kube-proxy start up and node registration
During kube-proxy bootstrap, kube-proxy retrieves node IP by accessing node object.
https://github.com/kubernetes/kubernetes/blob/release-1.5/cmd/kube-proxy/app/server.go#L464

Because kube-proxy is a static pod, kubelet may start kube-proxy before completing self registration. Hence kube-proxy may start up without knowing the correct node IP.

### PR DESCRIPTION
**Pull request by paulsubrata55**
**What type of PR is this?**
> /kind bug

**What this PR does / why we need it**:
Kube-proxy must atleast wait for some duration for the node to defined so that it can fetch the node IP. This node IP is currently used in ipvs proxier for the node-port services.

**Which issue(s) this PR fixes**:
Fixes #37414

**Does this PR introduce a user-facing change?**:
NONE

```release-note
Improvement in Kube-proxy. Kube-proxy waits for some duration for the node to be defined.
```

### CODE REVIEW

File: pkg/util/node/node.go [hunk 1]
```diff
@@ -106,17 +107,31 @@ func GetNodeHostIP(node *v1.Node) (net.IP, error) {
 }
 
 // GetNodeIP returns the ip of node with the provided hostname
+// If required, wait for the node to be defined.
 func GetNodeIP(client clientset.Interface, hostname string) net.IP {
 	var nodeIP net.IP
-	node, err := client.CoreV1().Nodes().Get(hostname, metav1.GetOptions{})
-	if err != nil {
```
Comment (JieJhih) [inline pkg/util/node/node.go]: I think it can try to get node at first.
If error then use ``ExponentialBackoff``.

Comment (paulsubrata55) [reply pkg/util/node/node.go]: Can't we avoid adding same piece of codes present inside `ExponentialBackoff`'s `func` for getting node and nodeIP here. I don't see any advantage of keeping them outside. `ExponentialBackoff` will execute the `func` without any delay for the 1st time and if it passes, it will break the loop the immediately.

**Comment by thockin** [comment]
This probably warrants a release note.  Can you please add something short?

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve

File: cmd/kube-proxy/app/server_others.go [hunk 2]
```diff
@@ -143,6 +143,9 @@ func newProxyServer(
 	nodeIP := net.ParseIP(config.BindAddress)
 	if nodeIP.IsUnspecified() {
 		nodeIP = utilnode.GetNodeIP(client, hostname)
+		if nodeIP == nil {
+			return nil, fmt.Errorf("unable to get node IP for hostname %s", hostname)
```
Comment (andrewsykim) [inline cmd/kube-proxy/app/server_others.go]: I'm wondering if this is technically a breaking change. Previously if `nodeIP` is nil, kube-proxy defaults to [127.0.0.1 as the node IP](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L282-L286) but now kube-proxy always exits with error instead of defaulting to local host.

Comment (andrewsykim) [reply cmd/kube-proxy/app/server_others.go]: Opened https://github.com/kubernetes/kubernetes/pull/84071 to preserve the original behavior but keep the retries for getting node object. PTAL :)
