### PR TITLE
fix delta fifo & various fakes for go1.5.1

### LINKED ISSUE #14138: Flake in controller framework test
```
E0917 14:23:44.991518   84561 reflector.go:206] /usr/local/go/src/runtime/asm_amd64.s:1696: Failed to watch *api.Pod: resource version in the future not supported by this fake
E0917 14:23:46.208306   84561 reflector.go:206] /usr/local/go/src/runtime/asm_amd64.s:1696: Failed to watch *api.Pod: resource version in the future not supported by this fake
E0917 14:23:47.208547   84561 reflector.go:206] /usr/local/go/src/runtime/asm_amd64.s:1696: Failed to watch *api.Pod: resource version in the future not supported by this fake
E0917 14:23:47.208700   84561 util.go:72] Recovered from panic: "sync: negative WaitGroup counter" (sync: negative WaitGroup counter)
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:66
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:54
/usr/local/go/src/runtime/asm_amd64.s:437
/usr/local/go/src/runtime/panic.go:423
/usr/local/go/src/sync/waitgroup.go:70
/usr/local/go/src/sync/waitgroup.go:95
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller_test.go:333
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:182
<autogenerated>:23
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:252
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:126
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:115
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:116
/usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96
/usr/local/go/src/runtime/asm_amd64.s:1696
--- FAIL: TestUpdate (2.00s)
panic: sync: WaitGroup is reused before previous Wait has returned [recovered]
        panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 50 [running]:
testing.tRunner.func1(0xc8203f8360)
        /usr/local/go/src/testing/testing.go:450 +0x171
sync.(*WaitGroup).Wait(0xc82040e420)
        /usr/local/go/src/sync/waitgroup.go:128 +0x114
k8s.io/kubernetes/pkg/controller/framework_test.TestUpdate(0xc8203f8360)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller_test.go:393 +0xb1c
testing.tRunner(0xc8203f8360, 0xfb67b0)
        /usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
        /usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0xbcbe90, 0xfb6780, 0x3, 0x3, 0xc82017f601)
        /usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc8200b9ee8, 0xc8200f0ea8)
        /usr/local/go/src/testing/testing.go:494 +0x70
main.main()
        k8s.io/kubernetes/pkg/controller/framework/_test/_testmain.go:64 +0x116

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0xfd0640)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/golang/glog.init.1
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 11 [chan receive]:
k8s.io/kubernetes/pkg/watch.(*Broadcaster).loop(0xc820111480)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/mux.go:166 +0x55
created by k8s.io/kubernetes/pkg/watch.NewBroadcaster
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/mux.go:72 +0x128

goroutine 13 [chan receive]:
k8s.io/kubernetes/pkg/watch.(*Broadcaster).loop(0xc820111600)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/mux.go:166 +0x55
created by k8s.io/kubernetes/pkg/watch.NewBroadcaster
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/mux.go:72 +0x128

goroutine 14 [semacquire]:
sync.runtime_Syncsemacquire(0xc82011c7a8)
        /usr/local/go/src/runtime/sema.go:237 +0x201
sync.(*Cond).Wait(0xc82011c798)
        /usr/local/go/src/sync/cond.go:62 +0x9b
k8s.io/kubernetes/pkg/client/cache.(*DeltaFIFO).Pop(0xc82011c780, 0x0, 0x0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/delta_fifo.go:290 +0xb2
k8s.io/kubernetes/pkg/controller/framework.(*Controller).processLoop(0xc8201207e0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:125 +0x44
k8s.io/kubernetes/pkg/controller/framework.(*Controller).(k8s.io/kubernetes/pkg/controller/framework.processLoop)-fm()
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96 +0x20
k8s.io/kubernetes/pkg/util.Until.func1(0xc820047f88)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:115 +0x4b
k8s.io/kubernetes/pkg/util.Until(0xc820047f88, 0x3b9aca00, 0xc8201629c0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:116 +0x53
k8s.io/kubernetes/pkg/controller/framework.(*Controller).Run(0xc8201207e0, 0xc8201629c0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96 +0x1c2
created by k8s.io/kubernetes/pkg/controller/framework_test.TestHammerController
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller_test.go:223 +0x3d4

goroutine 51 [chan receive]:
k8s.io/kubernetes/pkg/watch.(*Broadcaster).loop(0xc820408400)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/mux.go:166 +0x55
created by k8s.io/kubernetes/pkg/watch.NewBroadcaster
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/watch/mux.go:72 +0x128

goroutine 52 [sleep]:
time.Sleep(0x3b9aca00)
        /usr/local/go/src/runtime/time.go:59 +0xf9
k8s.io/kubernetes/pkg/util.Until(0xc820425f78, 0x3b9aca00, 0xc8202637a0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:117 +0x61
k8s.io/kubernetes/pkg/controller/framework.(*Controller).Run(0xc82027ba40, 0xc8202637a0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:96 +0x1c2
created by k8s.io/kubernetes/pkg/controller/framework_test.TestUpdate
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller_test.go:377 +0x874

goroutine 65 [sleep]:
time.Sleep(0x3b9aca00)
        /usr/local/go/src/runtime/time.go:59 +0xf9
k8s.io/kubernetes/pkg/util.Until(0xc82040c8e0, 0x3b9aca00, 0xc8202637a0)
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/util.go:117 +0x61
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).RunUntil
        /usr/local/google/home/mikedanese/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:144 +0x9a
FAIL    k8s.io/kubernetes/pkg/controller/framework      2.287s
```

@lavalamp @mvdan

### LINKED ISSUE #14617: Flake in pkg/controller/framework test under Go 1.5
Happens a few times every 100 runs.

```
--- FAIL: TestUpdate (2.00s)
        controller_test.go:328: observed transition "to" -> "from" for a-1-0
        controller_test.go:328: observed transition "to" -> "from" for b-1-1
```

```
--- FAIL: TestUpdate (2.00s)
        controller_test.go:328: observed transition "to" -> "missed the add event" for c-2-2
```

```
--- FAIL: TestUpdate (2.00s)
        controller_test.go:328: observed transition "missed the add event" -> "missed the add event" for c-1-2
```

As you can see, there seems to be some kind of race which results in unwanted transitions.

### PR DESCRIPTION
**Pull request by lavalamp**
Fixes #14617
Fixes #14138

@mvdan

### CODE REVIEW

File: pkg/watch/mux.go [hunk 1]
```diff
@@ -73,21 +75,42 @@ func NewBroadcaster(queueLength int, fullChannelBehavior FullChannelBehavior) *B
...
+func (functionFakeRuntimeObject) IsAnAPIObject() {}
+
+// Execute f, blocking the incoming queue (and waiting for it to drain first).
+// The purpose of this terrible hack is so that watchers added after an event
+// won't ever see that event, and will always see any event after they are
+// added.
+func (b *Broadcaster) blockQueue(f func()) {
+	var wg sync.WaitGroup
+	wg.Add(1)
+	b.incoming <- Event{internalRunFunctionMarker, functionFakeRuntimeObject(func() { defer wg.Done(); f() })}
```
Comment (mvdan) [inline pkg/watch/mux.go]: nit: split into multiple lines for readability?

File: pkg/watch/mux.go [hunk 2]
```diff
@@ -39,6 +39,8 @@ const incomingQueueLength = 25
 // Broadcaster distributes event notifications among any number of watchers. Every event
 // is delivered to every watcher.
 type Broadcaster struct {
+	// TODO: see if this lock is needed now that new watchers go through
+	// the incoming channel.
```
Comment (mvdan) [inline pkg/watch/mux.go]: If `stress` runs these tests 10,000 times without flakes, would you say this TODO is safe to remove?

Comment (mvdan) [inline pkg/watch/mux.go]: Ah, the involved tests are from another package.

**Comment by mvdan** [comment]
Thanks for the thorough fix!

File: pkg/watch/mux.go (hunk 2 above)
Comment (lavalamp) [inline pkg/watch/mux.go]: Basically I'm being lazzzzy here because I need to stop being lazzzzy about my PR reviews. :-(

File: pkg/watch/mux.go (hunk 1 above)
Comment (lavalamp) [inline pkg/watch/mux.go]: Sure.

**Comment by lavalamp** [comment]
huh, it looks like I broke other stuff. hm.

**Comment by mvdan** [comment]
Confirming that e414bc8128f392 fixes it, both with and without `-race`.

**Comment by lavalamp** [comment]
@mvdan Awesome, thanks for confirming.

**Comment by lavalamp** [comment]
oh I broke a test in cache. I'll have to fix it tomorrow.

**Comment by lavalamp** [comment]
Unfortunately my fix breaks some other use cases and I haven't had a chance to make it work every where yet.

**Comment by lavalamp** [comment]
OK, I believe I have handled all the cases now. I suspect that there's a further race, but will defer investigation, since this is no worse.

This potentially changes behavior for users that didn't wait for a sync before doing stuff. Not in a way that breaks unit tests, but if we see something weird in e2e, we'll be extra careful.

File: pkg/client/cache/delta_fifo.go [hunk 3]
```diff
@@ -199,6 +258,7 @@ func (f *DeltaFIFO) queueActionLocked(actionType DeltaType, obj interface{}) err
 		return KeyError{obj, err}
 	}
 	newDeltas := append(f.items[id], Delta{actionType, obj})
```
Comment (deads2k) [inline pkg/client/cache/delta_fifo.go]: I know its pre-existing, but can you add a comment indicating that this non-deterministic append (may or may not update `f.items[id]` is safe because access is locked and if `f.items[id]` is modified, it will be stomped before the function finishes.

File: pkg/client/cache/delta_fifo.go [hunk 4]
```diff
@@ -191,6 +213,43 @@ func (f *DeltaFIFO) AddIfNotPresent(obj interface{}) error {
...
+	// Do more sophisticated checks, or is this sufficient?
+	if _, ok := b.Object.(DeletedFinalStateUnknown); ok {
+		return a
+	}
+	return b
+}
+
 // queueActionLocked appends to the delta list for the object, calling
 // f.deltaCompressor if needed
 func (f *DeltaFIFO) queueActionLocked(actionType DeltaType, obj interface{}) error {
```
Comment (deads2k) [inline pkg/client/cache/delta_fifo.go]: Does go handle the `Lock()`, `Lock()`, `Unlock()`, `Unlock()` sequence how I'd want it to?  If so, trust of this function would be enhanced by locking and unlocking itself.  This being my first time in the code, I felt the need to chase it and make sure it was being used how I thought it was being used.

File: pkg/client/cache/delta_fifo.go [hunk 5]
```diff
@@ -191,6 +213,43 @@ func (f *DeltaFIFO) AddIfNotPresent(obj interface{}) error {
...
+	}
+	return deltas
+}
+
+// If a & b represent the same event, returns the delta that ought to be kept. Otherwise, nil.
+func isDup(a, b *Delta) *Delta {
+	if out := isDeletionDup(a, b); out != nil {
+		return out
+	}
+	// TODO: Detect other duplicate situations? Are there any?
```
Comment (deads2k) [inline pkg/client/cache/delta_fifo.go]: I don't know, but function godoc should indicate that its only catching the deletion dupes.

**Comment by deads2k** [comment]
Someone had fun writing this the first time

File: pkg/client/cache/delta_fifo.go [hunk 6]
```diff
@@ -310,51 +370,51 @@ func (f *DeltaFIFO) Pop() interface{} {
 func (f *DeltaFIFO) Replace(list []interface{}, resourceVersion string) error {
 	f.lock.Lock()
 	defer f.lock.Unlock()
+	keys := make(sets.String, len(list))
```
Comment (deads2k) [inline pkg/client/cache/delta_fifo.go]: No load factor?  I haven't sized maps in go, but this reads a little weird.

File: pkg/client/cache/delta_fifo.go [hunk 7]
```diff
@@ -310,51 +370,51 @@ func (f *DeltaFIFO) Pop() interface{} {
...
-				deletedObj = nil
-				if err != nil {
-					glog.Errorf("Unexpected error %v during lookup of key %v, placing DeleteFinalStateUnknown marker without object", err, k)
-				} else {
-					glog.Infof("Key %v does not exist in known objects store, placing DeleteFinalStateUnknown marker without object", k)
-				}
+		deletedObj, exists, err := f.knownObjects.GetByKey(k)
+		if err != nil || !exists {
+			deletedObj = nil
+			if err != nil {
```
Comment (deads2k) [inline pkg/client/cache/delta_fifo.go]: Two separate checks that each set `deletedObj` to `nil`.  If you want mutual exclusivity of messages (not sure why), the one level deep `else if` will still read nicer.

File: pkg/client/cache/delta_fifo.go [hunk 8]
```diff
@@ -310,51 +370,51 @@ func (f *DeltaFIFO) Pop() interface{} {
...
 		}
-		keySet.Insert(key)
+		return nil
 	}
 
 	// Detect deletions not already in the queue.
-	knownKeys := f.knownObjectKeys.ListKeys()
+	// TODO(lavalamp): This may be racy-- we aren't properly locked
+	// with knownObjects. Unproven.
+	knownKeys := f.knownObjects.ListKeys()
```
Comment (deads2k) [inline pkg/client/cache/delta_fifo.go]: Oh my.  I see it now and it scares me.  The behavior we observe will be influenced by the order of notification/updates from distinct `Stores` in distinct goroutines with distinct `ListerWatchers`?  That's what it looks like to me.  It seems like it would be unreliable.

**Comment by deads2k** [comment]
My head needs a rest.  I'll come back to it in a couple hours.

@lavalamp I'm particularly worried about this: https://github.com/kubernetes/kubernetes/pull/14881/files#r41506148.  Have I described the problem correctly or have I (hopefully) misunderstood the risk.

**Comment by mvdan** [comment]
> Someone had fun writing this the first time

I'm keeping that quote for later use.

**Comment by deads2k** [comment]
@brendandburns looks like you did the initial review in https://github.com/kubernetes/kubernetes/pull/5473, you might want to take a look.

**Comment by deads2k** [comment]
I haven't been able to reason why This would be safe: https://github.com/kubernetes/kubernetes/pull/14881#discussion_r41506148 .

@pmorie Can you help me feel better about it?

File: pkg/client/cache/delta_fifo.go (hunk 4 above)
Comment (lavalamp) [inline pkg/client/cache/delta_fifo.go]: No-- go mutexes are not re-entrant. The "locked" suffix on the name means that it shouldn't be called unless it's already locked. I added a comment.

File: pkg/client/cache/delta_fifo.go (hunk 6 above)
Comment (lavalamp) [inline pkg/client/cache/delta_fifo.go]: https://golang.org/pkg/builtin/#make

*shrug*

File: pkg/client/cache/delta_fifo.go (hunk 8 above)
Comment (lavalamp) [inline pkg/client/cache/delta_fifo.go]: I've haven't been able to repro it in a test, and this PR is a strict improvement, in that fewer races are possible.

**Comment by lavalamp** [comment]
@deads2k What do you think about getting this fix in and then worrying about the other potential races later? :)

**Comment by lavalamp** [comment]
@k8s-bot test this please

**Comment by deads2k** [comment]
> @deads2k What do you think about getting this fix in and then worrying about the other potential races later? :)

Can I get this comment: https://github.com/kubernetes/kubernetes/pull/14881#discussion_r41503292 to help me when I look again?

I'm willing to hold my nose and push the button, but given how heavily we rely on this code its worrisome (I have seen behind the curtain!).  How about an issue to resolve it?

File: pkg/client/cache/delta_fifo.go (hunk 3 above)
Comment (lavalamp) [inline pkg/client/cache/delta_fifo.go]: Sorry, I somehow totally missed this comment. But I don't understand what is non-deterministic about this. Getting a non-existing map element returns the zero value but it doesn't affect the map; see https://play.golang.org/p/0_tmN9pysk

**Comment by lavalamp** [comment]
@deads2k I filed #15746

File: pkg/client/cache/delta_fifo.go (hunk 3 above)
Comment (deads2k) [inline pkg/client/cache/delta_fifo.go]: It might have had a value, that's why check here https://github.com/kubernetes/kubernetes/pull/14881/files#diff-b32f14c6f3cce65061c1673064448839R268 and stomp here https://github.com/kubernetes/kubernetes/pull/14881/files#diff-b32f14c6f3cce65061c1673064448839R273 .

If there was a slice in the map that had enough capacity, the `append` would modify the existing map and `newDeltas` and `f.items[id]` would both point it.

If there wasn't a slice in the map or there wasn't enough capacity, the `append` would try to `realloc` and would `newDeltas` and `f.items[id]` would point to different locations and have different content.

**Comment by deads2k** [comment]
lgtm, just an optional nit about a comment.

File: pkg/client/cache/delta_fifo.go (hunk 3 above)
Comment (lavalamp) [inline pkg/client/cache/delta_fifo.go]: @deads2k That's not how append works-- it doesn't change the slice. It might change the memory the slice points to, but that's only important if someone else has a differently-sliced pointer to the same memory. Merely having a slice with enough capacity in the map is not enough to trigger a bug, because append doesn't change the slice that's stored in the map.

Compare: https://play.golang.org/p/mWvfcMX3mM
With: https://play.golang.org/p/aI6OSdMtPd

I don't have the bug the latter demonstrates for reasons beyond the scope of this one line-- we own the delta slice if it's in the map, we don't own it if it isn't. If I understand you correctly, though, your model of append would have printed out "[hi mom] [hi mom]", not "[hi] [hi mom]" for the first line, which is not the case. Did I misunderstand you?

Comment (deads2k) [inline pkg/client/cache/delta_fifo.go]: > If I understand you correctly, though, your model of append would have printed out "[hi mom] [hi mom]", not "[hi] [hi mom]" for the first line, which is not the case. Did I misunderstand you?

No.  I stand corrected.

**Comment by lavalamp** [comment]
Optimistically applying @deads2k's LGTM-- @deads2k, shout if you want something else. :)

**Comment by deads2k** [comment]
> Optimistically applying @deads2k's LGTM-- @deads2k, shout if you want something else. :)

@lavalamp nope, I meant it.  I don't have tagging power, but if you're feeling generous.... :)
