### PR TITLE
Validate container status in e2e pod status checks

### LINKED ISSUE #82445: [Tracking Issue] Ensure SIG-Networking Source Pod IP preservation test errors properly
Per PR [82420](https://github.com/kubernetes/kubernetes/pull/82420) the test `Kubernetes e2e suite [sig-network] Services should preserve source pod IP for traffic thru service cluster IP [LinuxOnly]` fails to error properly. One line of particular interest from that PR:

`
If you wonder why it does not fail on docker, that's because the test does not report the error correctly but fails the same way.
`

This issue is intended to track the discussion and resolution of making this test error properly so that it is useful to CI Signal

/sig networking
/cc @alejandrox1 @lachie83 @liggitt

### PR DESCRIPTION
**Pull request by saschagrunert**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

We now additionally check if the agnhost pods are ready before
marking the pod as running to increase the overall test stability.

**Which issue(s) this PR fixes**:

Fixes: https://github.com/kubernetes/kubernetes/issues/82445

**Special notes for your reviewer**:

Relates to: https://github.com/kubernetes/kubernetes/pull/82420

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig networking

### CODE REVIEW

File: test/e2e/framework/pod/resource.go [hunk 1]
```diff
@@ -35,6 +35,7 @@ import (
 	clientset "k8s.io/client-go/kubernetes"
 	podutil "k8s.io/kubernetes/pkg/api/v1/pod"
 	"k8s.io/kubernetes/pkg/client/conditions"
+	kubecontainer "k8s.io/kubernetes/pkg/kubelet/container"
```
Comment (neolit123) [inline test/e2e/framework/pod/resource.go]: noting that long term we should stop importing kubernetes/pkg in the framework.

Comment (saschagrunert) [reply test/e2e/framework/pod/resource.go]: Yes, we can try to bring up the error types into the CRI or stating repositories to enforce a uniform behavior around runtimes, which seems to diverge.

File: test/e2e/framework/pod/resource.go [hunk 2]
```diff
@@ -205,6 +206,17 @@ func podRunning(c clientset.Interface, podName, namespace string) wait.Condition
 		}
 		switch pod.Status.Phase {
 		case v1.PodRunning:
+			// Verify that all containers are running
+			for _, ctr := range pod.Status.ContainerStatuses {
+				state := ctr.State
+				if state.Waiting != nil && state.Waiting.Reason == kubecontainer.ErrRunContainer.Error() {
```
Comment (neolit123) [inline test/e2e/framework/pod/resource.go]: even if `state.Waiting` is non-nil, `state.Running` is what we really care about as per the function name.
can we get way with only checking `if state.Running == nil`?

also how about containers that have finished without error?

**Comment by fejta** [comment]
/uncc
/cc @timothysc 

Perhaps we should have an OWNERS file under pod?

File: test/e2e/framework/pod/resource.go (hunk 2 above)
Comment (saschagrunert) [reply test/e2e/framework/pod/resource.go]: Hm yeah I added this branch because returning an error will make the test fail earlier and not "only timeout". But I think we can just check for `Running == nil`, sure.

File: test/e2e/framework/pod/resource.go [hunk 3]
```diff
@@ -205,6 +205,15 @@ func podRunning(c clientset.Interface, podName, namespace string) wait.Condition
 		}
 		switch pod.Status.Phase {
 		case v1.PodRunning:
+			// Verify that all containers are running
```
Comment (timothysc) [inline test/e2e/framework/pod/resource.go]: I debate if this should be checked at this layer or if this is guaranteed by the kubelet to be true.  

/cc @kubernetes/sig-node-pr-reviews

**Review by timothysc — COMMENTED** [review]
/hold

File: test/e2e/framework/pod/resource.go (hunk 3 above)
Comment (saschagrunert) [reply test/e2e/framework/pod/resource.go]: The documentation says that at least one container needs to be running for the `PodRunning` phase, but not all of them:
https://github.com/kubernetes/kubernetes/blob/5823cfce76780efe5897429ea59ca55f268a3123/staging/src/k8s.io/api/core/v1/types.go#L2420-L2422

So from the current implementation perspective I would say that we have to still check every container to be running or terminated.

Comment (timothysc) [reply test/e2e/framework/pod/resource.go]: If 
> The documentation says that at least one container needs to be running for the PodRunning phase, but not all of them: 

is the declared state we should not be divergent from that guarantee.  

That said, I still don't think the behavior needs to be validated at this layer, unless there is a known issue.

Comment (alejandrox1) [reply test/e2e/framework/pod/resource.go]: @saschagrunert how is this check related to the error reported in https://github.com/kubernetes/kubernetes/issues/82445 ?

**Review by alejandrox1 — COMMENTED** [review]
/remove-area e2e-test-framework

File: test/e2e/framework/pod/resource.go (hunk 3 above)
Comment (saschagrunert) [reply test/e2e/framework/pod/resource.go]: It tries to report the "are all containers running" scenario correctly, which is currently not the case. I see the point of @timothysc, so I will check if we can verify it somewhat different...

**Comment by saschagrunert** [comment]
@timothysc, PTAL, I've found another solution. Big sorry for the delay.

**Review by timothysc — APPROVED** [review]
/lgtm 
/approve 

A lot cleaner, thanks.
