### PR TITLE
kubeadm: increase the timeout for cmd integration tests

### LINKED ISSUE #2197: slow running tests in cmd/kubeadm/test/cmd
there was a report in k/k that the tests in cmd/kubeadm/test/cmd are running for a long time:
https://github.com/kubernetes/kubernetes/pull/91366#issuecomment-648956868

> https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/91366/pull-kubernetes-integration/1275831207967330305
> === FAIL: cmd/kubeadm/test/cmd (0.00s)
> FAIL k8s.io/kubernetes/cmd/kubeadm/test/cmd 120.481s

/area test
/kind bug
/priority important-soon
/help

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:

The kubeadm command line integration tests normally run for <1 minute with a timeout of 2 minutes.
Increase the timeout to 4 minutes to ensure the tests pass when the infrastructure is under heavy load.

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#2197
refs https://github.com/kubernetes/kubernetes/issues/92360

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by neolit123** [comment]
the flakes on this PR seems unrelated to the flake we are trying to fix.
/retest

**Comment by neolit123** [comment]
/assign @BenTheElder 
PTAL, thanks

File: hack/make-rules/test-cmd.sh [hunk 1]
```diff
@@ -127,6 +127,8 @@ if [[ ${WHAT} == "" || ${WHAT} =~ .*kubeadm.* ]] ; then
   make all -C "${KUBE_ROOT}" WHAT=cmd/kubeadm
   # unless the user sets KUBEADM_PATH, assume that "make all..." just built it
   export KUBEADM_PATH="${KUBEADM_PATH:=$(kube::realpath "${KUBE_ROOT}")/_output/local/go/bin/kubeadm}"
+  # the tests should take around ~1 minute, but this ensures there is a higher timeout
+  export KUBE_TIMEOUT=--timeout=240s
   # invoke the tests
```
Comment (BenTheElder) [inline hack/make-rules/test-cmd.sh:132]: Instead of persist export here, we can just pass this to make the same way we pass WHAT
This should also ideally still have a user override if possible 🤔

Comment (RobertKielty) [reply hack/make-rules/test-cmd.sh:132]: Hi @neolit123 do you have time to implement @BenTheElder 's feedback? 

I would be happy to help out if help is wanted.

Comment (neolit123) [reply hack/make-rules/test-cmd.sh:132]: @RobertKielty
i'm no longer seeing /cmd/kubeadm/ test failures...are you still seeing them?
i'd prefer to keep the default timeout of 120s if we can, instead of making the change in this PR.

i had a question for @BenTheElder , but looks like i didn't post it.
would `make -C "${KUBE_ROOT}" test WHAT=k8s.io/kubernetes/cmd/kubeadm/test/cmd KUBE_TIMEOUT=--timeout=240s` just work here?

**Comment by neolit123** [comment]
oddly, i'm seeing more failures on the cmd/kubeadm/test/ tests, but they are not reported here:
https://testgrid.k8s.io/sig-release-master-blocking#integration-master

e.g. https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/92183/pull-kubernetes-integration/1282384125289828352
from https://github.com/kubernetes/kubernetes/pull/92183

@BenTheElder i have updated this change to pass KUBE_TIMEOUT to make:
```
  make -C "${KUBE_ROOT}" test \
    WHAT=k8s.io/kubernetes/cmd/kubeadm/test/cmd \
    # the tests should take less than 1 minute, but this ensures there is a higher timeout
    KUBE_TIMEOUT=--timeout=240s
```
please, take a look.
