### PR TITLE
Remove unnecessary error catch in scheduling failure

### LINKED ISSUE #121980: Not deleted from the cache in the handling of scheduling failures due to missing Node
### What happened?

The following tests are currently being passed. However, the correct name should be "nodes", not "node".
https://github.com/kubernetes/kubernetes/blob/ec5096fa869b801d6eb1bf019819287ca61edc4d/pkg/scheduler/scheduler_test.go#L328-L352

Fixing this will lead to the test failing.
```diff
$ git diff
diff --git a/pkg/scheduler/scheduler_test.go b/pkg/scheduler/scheduler_test.go
index b346046610b..e88d0030665 100644
--- a/pkg/scheduler/scheduler_test.go
+++ b/pkg/scheduler/scheduler_test.go
@@ -340,13 +340,13 @@ func TestFailureHandler_NodeNotFound(t *testing.T) {
                        name:             "node is deleted during a scheduling cycle",
                        nodes:            []v1.Node{*nodeFoo, *nodeBar},
                        nodeNameToDelete: "foo",
-                       injectErr:        apierrors.NewNotFound(v1.Resource("node"), nodeFoo.Name),
+                       injectErr:        apierrors.NewNotFound(v1.Resource("nodes"), nodeFoo.Name),
                        expectNodeNames:  sets.New("bar"),
                },
                {
                        name:            "node is not deleted but NodeNotFound is received incorrectly",
                        nodes:           []v1.Node{*nodeFoo, *nodeBar},
-                       injectErr:       apierrors.NewNotFound(v1.Resource("node"), nodeFoo.Name),
+                       injectErr:       apierrors.NewNotFound(v1.Resource("nodes"), nodeFoo.Name),
                        expectNodeNames: sets.New("foo", "bar"),
                },
        }
```

```console
$ go test -run 'TestFailureHandler_NodeNotFound$' ./pkg/scheduler
--- FAIL: TestFailureHandler_NodeNotFound (0.00s)
    --- FAIL: TestFailureHandler_NodeNotFound/node_is_deleted_during_a_scheduling_cycle (0.00s)
        node_tree.go:65: I1121 21:14:35.137431] Added node in listed group to NodeTree node="foo" zone=""
        node_tree.go:65: I1121 21:14:35.137476] Added node in listed group to NodeTree node="bar" zone=""
        schedule_one.go:989: I1121 21:14:35.137547] Unable to schedule pod, possibly due to node not found; waiting pod="default/test-pod" err="nodes \"foo\" not found"
        scheduling_queue.go:655: I1121 21:14:35.137572] Checking events for in-flight pod pod="default/test-pod" unschedulablePlugins=null inFlightEventsSize=0 inFlightPodsSize=0
        scheduling_queue.go:797: I1121 21:14:35.137584] Pod moved to an internal scheduling queue pod="default/test-pod" event="ScheduleAttemptFailure" queue="Unschedulable" schedulingCycle=0 hint=0 unschedulable plugins={}
        schedule_one.go:1068: I1121 21:14:35.137604] Updating pod condition pod="default/test-pod" conditionType="PodScheduled" conditionStatus="False" conditionReason="Unschedulable"
        scheduler_test.go:392: Unexpected nodes (-want, +got):   sets.Set[string](
            -   {"bar": {}},
            +   {"bar": {}, "foo": {}},
              )
FAIL
FAIL    k8s.io/kubernetes/pkg/scheduler 0.039s
FAIL
```

Perhaps the cause is here.
https://github.com/kubernetes/kubernetes/blob/ec5096fa869b801d6eb1bf019819287ca61edc4d/pkg/scheduler/schedule_one.go#L990

### What did you expect to happen?

Pass the unit test.

### How can we reproduce it (as minimally and precisely as possible)?

Please show above.

### Anything else we need to know?

_No response_

### Kubernetes version

None

### Cloud provider

None

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by utam0k**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

~~With apierrors, kind is plural. It is likely that these are not working well because they have not been made appropriate.~~
Remove unnecessary error catch in scheduling failure.

#### Which issue(s) this PR fixes:

Fixes #121980

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/schedule_one.go [hunk 1]
```diff
@@ -987,7 +987,7 @@ func (sched *Scheduler) handleSchedulingFailure(ctx context.Context, fwk framewo
 		logger.V(2).Info("Unable to schedule pod; no fit; waiting", "pod", klog.KObj(pod), "err", errMsg)
 	} else if apierrors.IsNotFound(err) {
 		logger.V(2).Info("Unable to schedule pod, possibly due to node not found; waiting", "pod", klog.KObj(pod), "err", errMsg)
-		if errStatus, ok := err.(apierrors.APIStatus); ok && errStatus.Status().Details.Kind == "node" {
+		if errStatus, ok := err.(apierrors.APIStatus); ok && (errStatus.Status().Details.Kind == "nodes" || errStatus.Status().Details.Kind == "node") { // Ususally `node` is used as the Kind, but `nodes` is also possible.
```
Comment (sanposhiho) [inline pkg/scheduler/schedule_one.go:990]: Looks really weird, please explain when which one is used. I'd like to seek a possible solution where only one kind is here.

**Review by sanposhiho — COMMENTED** [review]
/ok-to-test

**Review by sanposhiho — COMMENTED** [review]
/assign

File: pkg/scheduler/schedule_one.go (hunk 1 above)
Comment (utam0k) [reply pkg/scheduler/schedule_one.go:990]: At least, `apierrors` uses resource name(`nodes`) as a kind in `StatusError`.
https://github.com/kubernetes/kubernetes/blob/d61cbac69aae97db1839bd2e0e86d68f26b353a7/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L144-L156

I honestly don't know if there is room to plant StatusError from elsewhere.  `node` is nuanced enough that there may possibly be errors transmitted from user plug-ins, etc., which may not be needed.

Comment (sanposhiho) [reply pkg/scheduler/schedule_one.go:990]: I don't like "keep it because someone may use it" in general. We want to catch non-found errors from kube-apiserver, so if kube-apiserver emits errors with "nodes", then supporting "nodes" only should be enough.

File: pkg/scheduler/schedule_one.go [hunk 2]
```diff
@@ -987,7 +987,7 @@ func (sched *Scheduler) handleSchedulingFailure(ctx context.Context, fwk framewo
...
 			nodeName := errStatus.Status().Details.Name
```
Comment (sanposhiho) [inline pkg/scheduler/schedule_one.go:991]: Do we need this (L989-L1001) in the first place by the way? 🤔

Comment (sanposhiho) [reply pkg/scheduler/schedule_one.go:991]: Any thought? @kubernetes/sig-scheduling-approvers 

If Node is not found, the event handler should catch NodeDeleted event and remove Node from cache appropriately. I'm not sure if we have to remove Node from cache here (+ as this PR points out, this functionality hasn't been working until now, in the first place 😓 )

File: pkg/scheduler/schedule_one.go (hunk 1 above)
Comment (utam0k) [reply pkg/scheduler/schedule_one.go]: 👌 
d3def07550a

File: pkg/scheduler/schedule_one.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/scheduler/schedule_one.go:991]: I agree that this is unnecessary.
I traced the origin of this logic to here #56622 and #56261

I'm pretty sure we don't run into these problems anymore.

Comment (sanposhiho) [reply pkg/scheduler/schedule_one.go:991]: @utam0k can you change the PR to remove L989-L1001 based on this discussion?

Comment (utam0k) [reply pkg/scheduler/schedule_one.go]: Sure!
ad47cbac14b

**Comment by alculquicondor** [comment]
Failures look legit

**Comment by utam0k** [comment]
> Failures look legit

Ops.. I'll check them
