### PR TITLE
Fix for typecheck doesn't notice compile errors in test files

### LINKED ISSUE #125807: pull-kubernetes-typecheck doesn't notice compile errors in staging test files
_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/issues/125571#issuecomment-2198419708_

/sig testing
/area test
/kind bug

`pull-kubernetes-typecheck — Job succeeded.`
yet:
```
ERROR: staging/src/k8s.io/dynamic-resource-allocation/structured/namedresources/cel/compile.go:1: : # k8s.io/dynamic-resource-allocation/structured/namedresources/cel [k8s.io/dynamic-resource-allocation/structured/namedresources/cel.test]
ERROR: staging/src/k8s.io/dynamic-resource-allocation/structured/namedresources/cel/compile_test.go:127:14: undefined: Compiler (typecheck)
```

(I fixed this in that PR, but it should be reproducible by reintroducing a compile error in a test file like that)

### PR DESCRIPTION
**Pull request by dims**
List out explicitly all the staging repos as well so all the files under staging/ are "loaded" and we'll see problems if any. (This includes _test.go files).

With this patch, for example a bad edit in a test file will show up like this:
```
ERROR(darwin/arm64): /Users/davanum/go/src/k8s.io/kubernetes/staging/src/k8s.io/dynamic-resource-allocation/structured/namedresources/cel/compile_test.go:126:10: Compiler (variable of type *compiler) is not a type
ERROR(darwin/arm64): /Users/davanum/go/src/k8s.io/kubernetes/staging/src/k8s.io/dynamic-resource-allocation/structured/namedresources/cel/compile_test.go:126:8: c declared and not used
```

if say the edit was this:
```
diff --git a/staging/src/k8s.io/dynamic-resource-allocation/structured/namedresources/cel/compile_test.go b/staging/src/k8s.io/dynamic-resource-allocation/structured/namedresources/cel/compile_test.go
index bea913c81fc5..836a998e9dfa 100644
--- a/staging/src/k8s.io/dynamic-resource-allocation/structured/namedresources/cel/compile_test.go
+++ b/staging/src/k8s.io/dynamic-resource-allocation/structured/namedresources/cel/compile_test.go
@@ -123,6 +123,7 @@ attributes.stringslice["stringslice"].isSorted()`,
                },
        } {
                t.Run(name, func(t *testing.T) {
+                       var c Compiler
                        _, ctx := ktesting.NewTestContext(t)
                        result := Compiler.CompileCELExpression(scenario.expression, environment.StoredExpressions)
                        if scenario.expectCompileError != "" && result.Error == nil {
```

#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #125807

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

```
Co-authored-by: Tim Hockin <thockin@google.com>
```

### CODE REVIEW

File: test/typecheck/main.go [hunk 1]
```diff
@@ -197,6 +197,14 @@ func main() {
 
 	if len(args) == 0 {
 		args = append(args, "./...")
+		entries, err := os.ReadDir("./staging/src/k8s.io")
```
Comment (BenTheElder) [inline test/typecheck/main.go:200]: heh, another reason this tool won't be fully general

trying to think if there's a way to avoid hardcoding this, maybe we walk and discover all go modules?

Comment (BenTheElder) [reply test/typecheck/main.go:200]: (not to prioritize reuse, but to avoid missing anything)

**Comment by dims** [comment]
interesting errors we did not find before! because we don't run unit tests on all platforms

```
+++ Running case: verify.typecheck 
+++ working dir: /home/prow/go/src/k8s.io/kubernetes
+++ command: bash "hack/make-rules/../../hack/verify-typecheck.sh"
type-checking darwin/amd64
type-checking windows/amd64
type-checking windows/arm64
ERROR(windows/amd64): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/grpc_service_unix_test.go:30:7: could not import k8s.io/apiserver/pkg/storage/value/encrypt/envelope/testing/v2 (invalid package name: "")
type-checking linux/arm64
ERROR(windows/arm64): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/grpc_service_unix_test.go:30:7: could not import k8s.io/apiserver/pkg/storage/value/encrypt/envelope/testing/v2 (invalid package name: "")
type-checking linux/ppc64le
type-checking linux/s390x
type-checking linux/amd64
ERROR(linux/s390x): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/mount-utils/mount_linux_test.go:834:31: cannot use testCases[path].flags (value of type int64) as uint32 value in struct literal
type-checking linux/arm
type-checking darwin/arm64
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:40:17: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:40:32: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:40:77: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:40:92: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:43:83: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to fmt.Sprintf (overflows)
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:1221:83: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to fmt.Sprintf (overflows)
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:70:17: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:70:32: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:70:77: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:70:92: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:73:83: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to fmt.Sprintf (overflows)
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:75:83: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to fmt.Sprintf (overflows)
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:2845:17: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/component-base/logs/api/v1/types_test.go:99:48: cannot use math.MaxInt32 + 1 (untyped int constant 2147483648) as int value in argument to fmt.Sprintf (overflows)
ERROR(linux/arm): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/mount-utils/mount_linux_test.go:834:31: cannot use testCases[path].flags (value of type int64) as int32 value in struct literal
type-checking windows/386
type-checking linux/386
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:40:17: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:40:32: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:40:77: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:40:92: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:43:83: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to fmt.Sprintf (overflows)
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:1221:83: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to fmt.Sprintf (overflows)
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:70:17: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:70:32: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:70:77: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:70:92: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:73:83: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to fmt.Sprintf (overflows)
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:75:83: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to fmt.Sprintf (overflows)
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:2845:17: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/grpc_service_unix_test.go:30:7: could not import k8s.io/apiserver/pkg/storage/value/encrypt/envelope/testing/v2 (invalid package name: "")
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/component-base/logs/api/v1/types_test.go:99:48: cannot use math.MaxInt32 + 1 (untyped int constant 2147483648) as int value in argument to fmt.Sprintf (overflows)
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:40:17: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:40:32: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:40:77: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:40:92: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:43:83: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to fmt.Sprintf (overflows)
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:1221:83: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to fmt.Sprintf (overflows)
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:70:17: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:70:32: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:70:77: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:70:92: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:73:83: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to fmt.Sprintf (overflows)
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:75:83: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to fmt.Sprintf (overflows)
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go:2845:17: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to objs (overflows)
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/component-base/logs/api/v1/types_test.go:99:48: cannot use math.MaxInt32 + 1 (untyped int constant 2147483648) as int value in argument to fmt.Sprintf (overflows)
ERROR(linux/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/mount-utils/mount_linux_test.go:834:31: cannot use testCases[path].flags (value of type int64) as int32 value in struct literal
exit status 1

```

File: test/typecheck/main.go (hunk 1 above)
Comment (dims) [reply test/typecheck/main.go:202]: added a TODO, will hopefully get to it :)

**Comment by dims** [comment]
image

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

thanks dims!

File: staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go [hunk 2]
```diff
@@ -1,3 +1,6 @@
+// +build !arm
+// +build !386
```
Comment (BenTheElder) [inline staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go:2]: go fmt wants this done a little different with two modes, please gofmt

/lgtm-cancel

Comment (dims) [reply staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go]: Done!

**Comment by thockin** [comment]
I think there's a better way.

Like most go tools which expect pkg paths, the default here is './...' (or it could be '.').  We should leave that.  Instead:

```diff
diff --git a/hack/verify-typecheck.sh b/hack/verify-typecheck.sh
index af9585a1b2a..e3f064cc8f1 100755
--- a/hack/verify-typecheck.sh
+++ b/hack/verify-typecheck.sh
@@ -26,6 +26,17 @@ source "${KUBE_ROOT}/hack/lib/init.sh"
 cd "${KUBE_ROOT}"
 
 kube::golang::setup_env
+kube::util::require-jq
+
+if [[ $# == 0 ]]; then
+  # Doing it this way is MUCH faster than simply saying "all", and there doesn't
+  # seem to be a simpler way to express "this whole workspace".
+  packages=()
+  kube::util::read-array packages < <(
+      go work edit -json | jq -r '.Use[].DiskPath + "/..."'
+  )
+  set -- "${packages[@]}"
+fi
 
 ret=0
 TYPECHECK_SERIAL="${TYPECHECK_SERIAL:-false}"
```

I don't have time tonight, @dims - what do you think of this instead?  We do this in other scripts.

**Comment by thockin** [comment]
For each of these things - can't we fix the actual errors?  I see the Windows ones don't build because of missing equivalent packages.  Some of them look like unfortunate type mismatches between platforms, which could MAYBE be fixed?

**Comment by dims** [comment]
@thockin here are my notes

## grpc_service_unix_test.go

See the following which is linux only, so a reverence to `testing/v2` will not work https://github.com/kubernetes/kubernetes/blob/f00eee5a40dfd46ad2092df56f7a9f514f3d3997/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/testing/v2/kms_plugin_mock.go#L1-L2 
```
ERROR(windows/amd64): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/grpc_service_unix_test.go:30:7: could not import k8s.io/apiserver/pkg/storage/value/encrypt/envelope/testing/v2 (invalid package name: "")
type-checking linux/arm64
ERROR(windows/arm64): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/grpc_service_unix_test.go:30:7: could not import k8s.io/apiserver/pkg/storage/value/encrypt/envelope/testing/v2 (invalid package name: "")
ERROR(windows/386): /home/prow/go/src/k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/grpc_service_unix_test.go:30:7: could not import k8s.io/apiserver/pkg/storage/value/encrypt/envelope/testing/v2 (invalid package name: "")
```

## mount_linux_test.go

if you see the following, the `Flags` field of `unix.Statfs_t` is different in different architectures:
https://github.com/search?q=repo%3Agolang%2Fgo+%2Ftype+Statfs_t+struct%2F+language%3AGo&type=code&l=Go

Any suggestions?
https://github.com/kubernetes/kubernetes/blob/f00eee5a40dfd46ad2092df56f7a9f514f3d3997/staging/src/k8s.io/mount-utils/mount_linux_test.go#L834

## types_test.go

https://github.com/kubernetes/kubernetes/blob/f00eee5a40dfd46ad2092df56f7a9f514f3d3997/staging/src/k8s.io/component-base/logs/api/v1/types_test.go#L99-100

seems intentional, do we really want to fix?

## celcoststability_test.go and validation_test.go

Same with this bunch:
https://cs.k8s.io/?q=MaxInt64&i=nope&files=celcoststability_test%7Cvalidation_test&excludeFiles=&repos=kubernetes/kubernetes

seems intentional, do we really want to fix?

**Comment by dims** [comment]
> I don't have time tonight, @dims - what do you think of this instead? We do this in other scripts.

@thockin Done!

**Comment by BenTheElder** [comment]
TIL "go work edit", nice! I do think this could've been a follow up and right now we completely fail to type check staging ...

regarding fixing: these don't build as-is, and for most if not all I wouldn't expect e.g. KMS to work on windows and we don't build or support api-server on windows.

of these arm is probably the most unfortunate but we dropped it and it wouldn't have built without the tags either.

we don't actually care about 386, do we?

the mounter test we could put a helper for the mock in a test-only file for each architecture, but again I consider the build tag to be documenting the status quo and getting testing in place prevents further regressions.

File: hack/verify-typecheck.sh [hunk 3]
```diff
@@ -26,6 +26,17 @@ source "${KUBE_ROOT}/hack/lib/init.sh"
 cd "${KUBE_ROOT}"
 
 kube::golang::setup_env
+kube::util::require-jq
+
+if [[ $# == 0 ]]; then
+  # Doing it this way is MUCH faster than simply saying "all", and there doesn't
+  # seem to be a simpler way to express "this whole workspace".
+  packages=()
+  kube::util::read-array packages < <(
```
Comment (BenTheElder) [inline hack/verify-typecheck.sh:35]: @thockin this seems like something we should move to a utility in hack/lib/golang.sh ?

Comment (thockin) [reply hack/verify-typecheck.sh:35]: Arrays and functions don't always play nice together - you can't pass an array as an argument, for example.  I suppose we could do wrap it, but it's only used in a couple places

**Comment by thockin** [comment]
If we no longer support linux/386 and arm, should we remove them from the typecheck?  That still leaves us  with s390x, though

**Comment by thockin** [comment]
I think, other than the Windows ones, the 32 bit issues can be solved

**Comment by thockin** [comment]
@dims - I fixed the 32bit/64bit issues.  Almost all of them are because `const` values are assumed to be `int` unless otherwise noted.  With the below diff, typecheck passes in all of these directories.  PTAL:


```diff
diff --git a/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go b/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go
index fa704e289c6..3cf956b3880 100644
--- a/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go
+++ b/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/celcoststability_test.go
@@ -1,6 +1,3 @@
-//go:build !arm && !386
-// +build !arm,!386
-
 /*
 Copyright 2022 The Kubernetes Authors.
 
@@ -40,17 +37,19 @@ func TestCelCostStability(t *testing.T) {
 	}{
 		{name: "integers",
 			// 1st obj and schema args are for "self.val1" field, 2nd for "self.val2" and so on.
-			obj:    objs(math.MaxInt64, math.MaxInt64, math.MaxInt32, math.MaxInt32, math.MaxInt64, math.MaxInt64),
+			obj: objs(int64(math.MaxInt64), int64(math.MaxInt64), int32(math.MaxInt32), int32(math.MaxInt32),
+				int64(math.MaxInt64), int64(math.MaxInt64)),
 			schema: schemas(integerType, integerType, int32Type, int32Type, int64Type, int64Type),
 			expectCost: map[string]int64{
-				ValsEqualThemselvesAndDataLiteral("self.val1", "self.val2", fmt.Sprintf("%d", math.MaxInt64)): 11,
+				ValsEqualThemselvesAndDataLiteral("self.val1", "self.val2", fmt.Sprintf("%d", int64(math.MaxInt64))): 11,
 				"self.val1 == self.val6":                              5, // integer with no format is the same as int64
 				"type(self.val1) == int":                              4,
 				fmt.Sprintf("self.val3 + 1 == %d + 1", math.MaxInt32): 5, // CEL integers are 64 bit
 			},
 		},
 		{name: "numbers",
-			obj:    objs(math.MaxFloat64, math.MaxFloat64, math.MaxFloat32, math.MaxFloat32, math.MaxFloat64, math.MaxFloat64, int64(1)),
+			obj: objs(float64(math.MaxFloat64), float64(math.MaxFloat64), float32(math.MaxFloat32), float32(math.MaxFloat32),
+				float64(math.MaxFloat64), float64(math.MaxFloat64), int64(1)),
 			schema: schemas(numberType, numberType, floatType, floatType, doubleType, doubleType, doubleType),
 			expectCost: map[string]int64{
 				ValsEqualThemselvesAndDataLiteral("self.val1", "self.val2", fmt.Sprintf("%f", math.MaxFloat64)): 11,
@@ -1221,7 +1220,7 @@ func TestCelEstimatedCostStability(t *testing.T) {
 			// 1st obj and schema args are for "self.val1" field, 2nd for "self.val2" and so on.
 			schema: schemas(integerType, integerType, int32Type, int32Type, int64Type, int64Type),
 			expectCost: map[string]uint64{
-				ValsEqualThemselvesAndDataLiteral("self.val1", "self.val2", fmt.Sprintf("%d", math.MaxInt64)): 8,
+				ValsEqualThemselvesAndDataLiteral("self.val1", "self.val2", fmt.Sprintf("%d", int64(math.MaxInt64))): 8,
 				"self.val1 == self.val6":                              4, // integer with no format is the same as int64
 				"type(self.val1) == int":                              4,
 				fmt.Sprintf("self.val3 + 1 == %d + 1", math.MaxInt32): 5, // CEL integers are 64 bit
diff --git a/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/compilation_test.go b/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/compilation_test.go
index 34745a2758c..5f078e2f0df 100644
--- a/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/compilation_test.go
+++ b/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/compilation_test.go
@@ -1,6 +1,3 @@
-//go:build !arm && !386
-// +build !arm,!386
-
 /*
 Copyright 2021 The Kubernetes Authors.
 
diff --git a/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go b/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go
index 7d2cc1b296c..87a1faebd8d 100644
--- a/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go
+++ b/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation_test.go
@@ -1,6 +1,3 @@
-//go:build !arm && !386
-// +build !arm,!386
-
 /*
 Copyright 2021 The Kubernetes Authors.
 
@@ -70,12 +67,13 @@ func TestValidationExpressions(t *testing.T) {
 		// equality, comparisons and type specific functions
 		{name: "integers",
 			// 1st obj and schema args are for "self.val1" field, 2nd for "self.val2" and so on.
-			obj:    objs(math.MaxInt64, math.MaxInt64, math.MaxInt32, math.MaxInt32, math.MaxInt64, math.MaxInt64),
+			obj: objs(int64(math.MaxInt64), int64(math.MaxInt64), int32(math.MaxInt32), int32(math.MaxInt32),
+				int64(math.MaxInt64), int64(math.MaxInt64)),
 			schema: schemas(integerType, integerType, int32Type, int32Type, int64Type, int64Type),
 			valid: []string{
-				ValsEqualThemselvesAndDataLiteral("self.val1", "self.val2", fmt.Sprintf("%d", math.MaxInt64)),
+				ValsEqualThemselvesAndDataLiteral("self.val1", "self.val2", fmt.Sprintf("%d", int64(math.MaxInt64))),
 				ValsEqualThemselvesAndDataLiteral("self.val3", "self.val4", fmt.Sprintf("%d", math.MaxInt32)),
-				ValsEqualThemselvesAndDataLiteral("self.val5", "self.val6", fmt.Sprintf("%d", math.MaxInt64)),
+				ValsEqualThemselvesAndDataLiteral("self.val5", "self.val6", fmt.Sprintf("%d", int64(math.MaxInt64))),
 				"self.val1 == self.val6", // integer with no format is the same as int64
 				"type(self.val1) == int",
 				fmt.Sprintf("self.val3 + 1 == %d + 1", math.MaxInt32), // CEL integers are 64 bit
@@ -89,7 +87,8 @@ func TestValidationExpressions(t *testing.T) {
 			},
 		},
 		{name: "numbers",
-			obj:    objs(math.MaxFloat64, math.MaxFloat64, math.MaxFloat32, math.MaxFloat32, math.MaxFloat64, math.MaxFloat64, int64(1)),
+			obj: objs(float64(math.MaxFloat64), float64(math.MaxFloat64), float32(math.MaxFloat32), float32(math.MaxFloat32),
+				float64(math.MaxFloat64), float64(math.MaxFloat64), int64(1)),
 			schema: schemas(numberType, numberType, floatType, floatType, doubleType, doubleType, doubleType),
 			valid: []string{
 				ValsEqualThemselvesAndDataLiteral("self.val1", "self.val2", fmt.Sprintf("%f", math.MaxFloat64)),
@@ -2845,7 +2844,7 @@ func TestCELValidationLimit(t *testing.T) {
 	}{
 		{
 			name:   "test limit",
-			obj:    objs(math.MaxInt64),
+			obj:    objs(int64(math.MaxInt64)),
 			schema: schemas(integerType),
 			valid: []string{
 				"self.val1 > 0",
diff --git a/staging/src/k8s.io/component-base/logs/api/v1/types_test.go b/staging/src/k8s.io/component-base/logs/api/v1/types_test.go
index 52dd4f1c2ff..abf46f71e92 100644
--- a/staging/src/k8s.io/component-base/logs/api/v1/types_test.go
+++ b/staging/src/k8s.io/component-base/logs/api/v1/types_test.go
@@ -1,6 +1,3 @@
-//go:build !arm && !386
-// +build !arm,!386
-
 /*
 Copyright 2022 The Kubernetes Authors.
 
@@ -99,7 +96,7 @@ func TestVModule(t *testing.T) {
 			},
 		},
 		{
-			arg:         fmt.Sprintf("invalidint32=%d", math.MaxInt32+1),
+			arg:         fmt.Sprintf("invalidint32=%d", uint(math.MaxInt32+1)),
 			expectError: `parsing verbosity in "invalidint32=2147483648": strconv.ParseUint: parsing "2147483648": value out of range`,
 		},
 	}
diff --git a/staging/src/k8s.io/mount-utils/mount_linux_test.go b/staging/src/k8s.io/mount-utils/mount_linux_test.go
index 0bcc33fb433..3c0842b20b3 100644
--- a/staging/src/k8s.io/mount-utils/mount_linux_test.go
+++ b/staging/src/k8s.io/mount-utils/mount_linux_test.go
@@ -1,5 +1,5 @@
-//go:build (linux && amd64) || (linux && arm64)
-// +build linux,amd64 linux,arm64
+//go:build linux
+// +build linux
 
 /*
 Copyright 2014 The Kubernetes Authors.
@@ -32,6 +32,7 @@ import (
 	"time"
 
 	"github.com/stretchr/testify/assert"
+	"golang.org/x/exp/constraints"
 	"golang.org/x/sys/unix"
 	utilexec "k8s.io/utils/exec"
 	testexec "k8s.io/utils/exec/testing"
@@ -814,9 +815,15 @@ func TestFormatTimeout(t *testing.T) {
 	mu.Unlock()
 }
 
+// Some platforms define unix.Statfs_t.Flags differently.  Our need here is
+// pretty constrained, so some aggressive type-conversion is OK.
+func mkStatfsFlags[T1 constraints.Integer, T2 constraints.Integer](orig T1, add T2) T1 {
+	return orig | T1(add)
+}
+
 func TestGetUserNSBindMountOptions(t *testing.T) {
 	var testCases = map[string]struct {
-		flags        int64
+		flags        int32 // smallest size used by any platform we care about
 		mountoptions string
 	}{
 		"ro":            {flags: unix.MS_RDONLY, mountoptions: "ro"},
@@ -831,7 +838,8 @@ func TestGetUserNSBindMountOptions(t *testing.T) {
 	}
 
 	statfsMock := func(path string, buf *unix.Statfs_t) (err error) {
-		*buf = unix.Statfs_t{Flags: testCases[path].flags}
+		*buf = unix.Statfs_t{}
+		buf.Flags = mkStatfsFlags(buf.Flags, testCases[path].flags)
 		return nil
 	}
 
```

If you prefer I can push a different PR, or you can just cross-check me and patch this diff into this PR.

**Comment by dims** [comment]
> If you prefer I can push a different PR, or you can just cross-check me and patch this diff into this PR.

Done in this PR itself! added `Co-Authored-By` as well.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by dims** [comment]
Happy 4th of July @thockin !!

giphy-ezgif com-webp-to-gif-converter

**Comment by thockin** [comment]
:hotdog: :hamburger: :fireworks:

File: hack/verify-typecheck.sh (hunk 3 above)
Comment (BenTheElder) [reply hack/verify-typecheck.sh:35]: > Arrays and functions don't always play nice together - you can't pass an array as an argument, for example. I suppose we could do wrap it, but it's only used in a couple places

I don't see why calling this snippet would be any different? `kube::golang::read-packages packages` ?

> [...] but it's only used in a couple places

Yeah, but this seems likely to need updating at some point, it's a bit of a hack?

**Comment by BenTheElder** [comment]
> If we no longer support linux/386 and arm, should we remove them from the typecheck? That still leaves us with s390x, though

... This is a good question. We don't build for them anymore but downstream distros have been building for arm and we should consider the tradeoff in receiving fixes all the time / ecosystem damage.

I don't think we should check 386 anymore. S390x is another conversation ...

File: hack/verify-typecheck.sh (hunk 3 above)
Comment (thockin) [reply hack/verify-typecheck.sh:35]: I don't think it's a hack.  Go has a small number of syntaxes which indicate packages.  I don't know if there is a spec, per se, but other than the ones we all know ("example.com/path, ./path, and /... suffixes) there's a magic "all" pattern.  Last I asked there was no plan to add a magic pattern for "everything in this workspace", so  this is the way.

If you want to PR a function like `kube::golang::workspace_all()` I won't say no :)

**Comment by BenTheElder** [comment]
Our build still proclaims support for linux/386 and linux/arm for "supproted client platforms" IE kubectl.

I suspect linux/386 is of increasingly low utility but we'd have to determine that separately.

File: hack/verify-typecheck.sh (hunk 3 above)
Comment (BenTheElder) [reply hack/verify-typecheck.sh:35]: > I don't think it's a hack. Go has a small number of syntaxes which indicate packages. I don't know if there is a spec, per se, but other than the ones we all know ("example.com/path, ./path, and /... suffixes) there's a magic "all" pattern. Last I asked there was no plan to add a magic pattern for "everything in this workspace", so this is the way.

I meant that it feels slightly magical to jq `go work edit -json`, which isn't exactly a well-known data format (seems to be documented in https://go.dev/ref/mod#go-work-edit) and it seems likely this will get copy pasted a lot.


I started iterating here: https://github.com/kubernetes/kubernetes/pull/125964 and already found at two different implementations of this in tree already and three copy-pastes of this variation (including comments etc).

We can use `go list` to avoid pulling in jq (and checking for jq) at the expense of absolute paths.
