### PR TITLE
Kubelet TCP/HTTP probes: improve network resources utilization

### LINKED ISSUE #89898: Sometime Liveness/Readiness Probes fail because of net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
**What happened**:
In my cluster sometimes readiness the probes are failing. But the application works fine.
```
Apr 06 18:15:14 kubenode** kubelet[34236]: I0406 18:15:14.056915   34236 prober.go:111] Readiness probe for "default-nginx-daemonset-4g6b5_default(a3734646-77fd-11ea-ad94-509a4c9f2810):nginx" failed (failure): Get http://172.18.123.127:80/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

**What you expected to happen**:
Successful Readiness Probe.

**How to reproduce it (as minimally and precisely as possible)**:
We have few clusters with different workloads.
Only in cluster with big number of short living pods we have this issue.
But not on all nodes.
We can't reproduce this error on other our clusters (that have same configuration but different workload).
How i found the issue?
I deployed a daemonset:
```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: default-nginx-daemonset
  namespace: default
  labels:
    k8s-app: default-nginx
spec:
  selector:
    matchLabels:
      name: default-nginx
  template:
    metadata:
      labels:
        name: default-nginx
    spec:
      tolerations:
      - operator: Exists
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
```
Then i started to listen events on all pods of this daemonset.
After a couple of time i received next events:
```
Warning  Unhealthy  110s (x5 over 44m)  kubelet, kubenode20  Readiness probe failed: Get http://172.18.122.143:80/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Warning  Unhealthy  11m (x3 over 32m)  kubelet, kubenode10  Readiness probe failed: Get http://172.18.65.57:80/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
....
```
Those events where on ~50% of pods of this daemonset.

On the nodes where the pods with failed probes was placed, I collected the logs of kubelet.
And there was errors like:
```
Apr 06 14:08:35 kubenode20 kubelet[10653]: I0406 14:08:35.464223   10653 prober.go:111] Readiness probe for "default-nginx-daemonset-nkwkf_default(90a3883b-77f3-11ea-ad94-509a4c9f2810):nginx" failed (failure): Get http://172.18.122.143:80/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

I was thinking that sometimes the nginx in pod really response slowly.
For excluding this theory, I created a short script that curl the application in pod and store response time in a file:
```
while true; do curl http://172.18.122.143:80/ -s -o /dev/null -w  "%{time_starttransfer}\n" >> /tmp/measurment.txt; done;
```

I run this script on node where the pod is placed for 30 minutes and i get the following:
```
$ cat /tmp/measurment.txt | sort -u
0.000
0.001
0.002
0.003
0.004
0.005
0.006
0.007

$ cat /tmp/measurment.txt | wc -l
482670
```
There was `482670` measurements and the longest response time was `0.007`.

In logs of pod there are only message with response code 200 (from my requests and requests of readiness probes):
```
[06/Apr/2020:14:06:30 +0000] "GET / HTTP/1.1" 200 612 "-" "kube-probe/1.12" "-"
......
[06/Apr/2020:14:08:35 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.47.0" "-"
[06/Apr/2020:14:08:35 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.47.0" "-"
[06/Apr/2020:14:08:35 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.47.0" "-"
......
[06/Apr/2020:14:08:41 +0000] "GET / HTTP/1.1" 200 612 "-" "kube-probe/1.12" "-"
```
It means that part of probes are successful.

Then i stopped the curl script (because the big number of logs).
I waited while new error with failed probe appears in kubelet logs.
```
Apr 06 18:15:14 kubenode13 kubelet[34236]: I0406 18:15:14.056915   34236 prober.go:111] Readiness probe for "default-nginx-daemonset-4g6b5_default(a3734646-77fd-11ea-ad94-509a4c9f2810):nginx" failed (failure): Get http://172.18.123.127:80/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

And in logs of that pod with nginx I didn't find the request generated by this probe:
```
kubectl logs default-nginx-daemonset-4g6b5 | grep "15:15"
[06/Apr/2020:18:15:00 +0000] "GET / HTTP/1.1" 200 612 "-" "kube-probe/1.12" "-"
[06/Apr/2020:18:15:20 +0000] "GET / HTTP/1.1" 200 612 "-" "kube-probe/1.12" "-"
[06/Apr/2020:18:15:30 +0000] "GET / HTTP/1.1" 200 612 "-" "kube-probe/1.12" "-"
[06/Apr/2020:18:15:40 +0000] "GET / HTTP/1.1" 200 612 "-" "kube-probe/1.12" "-"
[06/Apr/2020:18:15:50 +0000] "GET / HTTP/1.1" 200 612 "-" "kube-probe/1.12" "-"
``` 

If I restart the kubelet - the error don't disappear.
Have someone any suggestions about this?

**Environment**:
- Kubernetes version: **1.12.1**
- Cloud provider or hardware configuration: ***hardware*
- OS (e.g: `cat /etc/os-release`): ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.15.0-66-generic
- Install tools:
- Network plugin and version (if this is a network-related bug): calico:v3.1.3

Seems like the problem appears in many different installations - https://github.com/kubernetes/kubernetes/issues/51096

/sig network

### PR DESCRIPTION
**Pull request by aojea**
/kind bug
/kind cleanup
/kind feature

#### What this PR does / why we need it:

For every connection created, the OS opens a socket and, once it finish it doesn't free all the resources immediately, it goes through a TIME-WAIT state (60 seconds by default).

Kubelet probes create short lived connections (usually less than 1 seconds), each of these connection allocate a socket, ephemeral port, conntrack entry, ... and it takes 60 seconds (TIME-WAIT) state to be freed.

This causes a problem at scale on systems that are already using a considerable amount of network resources, when there are a considerable number of probes at a high rate, they will be consuming a considerable amount of them. Since Kubernetes is a distributed system, it relies heavily on the network, and is common to reach the limits of the network resources with the users workloads.

In addition, the failures caused by the exhaustion of this network's resources are very difficult to troubleshoot, since the symptoms vary from failed probes, to connectivity issues with Services and Ingresses, controllers failing to reach apiserver, ...

In order to be more efficient on the kubelet, we can use the option SO_LINGER for each of the network probes to set the TIME-WAIT to 1 second. This is not a big problem since the probes use the connection just to check the status of the Pod, and the data transferred is relatively small.

Fixes #89898

```release-note
kubelet TCP and HTTP probes are more effective using networking resources: conntrack entries, sockets, ... 
This is achieved by reducing the TIME-WAIT state of the connection to 1 second, instead of the defaults 60 seconds. This allows kubelet to free the socket, and free conntrack entry and ephemeral port associated.
```

### CODE REVIEW

File: pkg/probe/tcp/tcp.go [hunk 1]
```diff
@@ -28,27 +29,25 @@ import (
...
-	return DoTCPProbe(net.JoinHostPort(host, strconv.Itoa(port)), timeout)
+type tcpProber struct {
+	dialer *net.Dialer
 }
 
-// DoTCPProbe checks that a TCP socket to the address can be opened.
-// If the socket can be opened, it returns Success
-// If the socket fails to open, it returns Failure.
-// This is exported because some other packages may want to do direct TCP probes.
-func DoTCPProbe(addr string, timeout time.Duration) (probe.Result, string, error) {
```
Comment (aojea) [inline pkg/probe/tcp/tcp.go:50]: this seems to be a legace thing ,I can't see it used anywhere

File: pkg/probe/util.go [hunk 2]
```diff
@@ -55,3 +57,17 @@ func findPortByName(container *v1.Container, portName string) (int, error) {
...
 }
+
+// ProbeDialer returns a dialer optimized for probes to avoid lingering sockets on TIME-WAIT state.
+// The dialer reduces the TIME-WAIT period to 1 seconds instead of the OS default of 60 seconds.
+// Ref: https://issues.k8s.io/89898
+func ProbeDialer() *net.Dialer {
+	dialer := &net.Dialer{
+		Control: func(network, address string, c syscall.RawConn) error {
+			return c.Control(func(fd uintptr) {
+				syscall.SetsockoptLinger(int(fd), syscall.SOL_SOCKET, syscall.SO_LINGER, &syscall.Linger{Onoff: 1, Linger: 1})
```
Comment (thockin) [inline pkg/probe/util.go:68]: Does this need to be guarded with Linux-only build tag?  I.e. does it work on Windows?

File: pkg/probe/http/http.go [hunk 3]
```diff
@@ -53,7 +53,9 @@ func NewWithTLSConfig(config *tls.Config, followNonLocalRedirects bool) Prober {
 			DisableKeepAlives:  true,
 			Proxy:              http.ProxyURL(nil),
 			DisableCompression: true, // removes Accept-Encoding header
+			DialContext:        probe.ProbeDialer().DialContext,
```
Comment (thockin) [inline pkg/probe/http/http.go:56]: Do we need to set `DialTLSContext` too?   We do support HTTPS via the "scheme" field

File: pkg/kubelet/prober/prober.go [hunk 4]
```diff
@@ -99,6 +94,21 @@ func (pb *prober) probe(ctx context.Context, probeType probeType, pod *v1.Pod, s
 		return results.Success, nil
 	}
 
+	// lazy initialize probes
```
Comment (thockin) [inline pkg/kubelet/prober/prober.go:97]: Are we confident there's no concurrent access to this type?  Maybe comment that?

File: pkg/probe/http/http_test.go [hunk 5]
```diff
@@ -364,48 +373,60 @@ func TestHTTPProbeChecker(t *testing.T) {
...
-			if health != test.health {
-				t.Errorf("case %d: expected %v, got %v", i, test.health, health)
-			}
-			if health != probe.Failure && test.health != probe.Failure {
-				if !strings.Contains(output, test.accBody) {
-					t.Errorf("Expected response body to contain %v, got %v", test.accBody, output)
+	for _, testHTTP := range tests {
+		for i, test := range testCases {
+			t.Run(fmt.Sprintf("%s-case-%2d", testHTTP.name, i), func(t *testing.T) {
+				server := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
```
Comment (thockin) [inline pkg/probe/http/http_test.go:362]: Can you comment on what, if anything, proves connection reuse?

File: pkg/kubelet/prober/scale_test.go [hunk 6]
```diff
@@ -0,0 +1,228 @@
...
+		FailureThreshold: 3,
+	}
+}
+
+// TCP sockets goes through a TIME-WAIT state (default 60 sec) before being freed.
+// Conntrack entries and ephemeral ports will be held for 60 seconds
+// despite the probe may have finished in less than 1 second.
+// It causes to run out of ephemaral ports if the rate of probes is higher than the
+// rate the OS recycles the ports used.
+// These tests verify that after certain period the probes keep working, if the probes
```
Comment (thockin) [inline pkg/kubelet/prober/scale_test.go:58]: I could do with some more commentary in the test to explain how this is being done.  It seems to be using kubelet infra to set up a bunch of fake pods and then letting the prober run on its natural cycle?  How long would that take to fail?

**Review by thockin — COMMENTED** [review]
Surprisingly not huge!

File: pkg/probe/util.go (hunk 2 above)
Comment (aojea) [reply pkg/probe/util.go:68]: yes, it does, it also fails in arm64 🙃 , I just saw it in the CI jobs

File: pkg/probe/http/http.go (hunk 3 above)
Comment (aojea) [reply pkg/probe/http/http.go:56]: The transport is smart, it uses the dial function to create the TCP connection and start the TLS handshake on top.
I've added a new combination on the tests for https and http

File: pkg/kubelet/prober/prober.go (hunk 4 above)
Comment (aojea) [reply pkg/kubelet/prober/prober.go:97]: yes, there are with the tcp dialer, let me bring this back, it seems I was over optimizing

File: pkg/probe/http/http.go (hunk 3 above)
Comment (aojea) [reply pkg/probe/http/http.go:56]: only one Dial is needed

File: pkg/probe/http/http_test.go (hunk 5 above)
Comment (aojea) [reply pkg/probe/http/http_test.go:362]: I'm not able to make it work, I will leave it for a follow up

File: pkg/kubelet/prober/scale_test.go [hunk 7]
```diff
@@ -0,0 +1,270 @@
...
+					case result = <-m.livenessManager.Updates():
+						probeType = "liveness"
+					case result = <-m.readinessManager.Updates():
+						probeType = "readiness"
+					case <-ctx.Done():
+						return
+					}
+					switch result.Result.String() {
+					case "Failure":
+						t.Errorf("Failure %s on contantinerID: %v Pod %v", probeType, result.ContainerID, result.PodUID)
```
Comment (aojea) [inline pkg/kubelet/prober/scale_test.go:161]: the test fails on failed probes

File: pkg/kubelet/prober/scale_test.go (hunk 6 above)
Comment (aojea) [reply pkg/kubelet/prober/scale_test.go:48]: see if now is more clear, the test is tricky because I can't get sockets usage or conntrack entries, as unit test should not run as root

File: pkg/probe/util.go (hunk 2 above)
Comment (aojea) [reply pkg/probe/util.go]: fixed

File: pkg/kubelet/prober/prober.go (hunk 4 above)
Comment (aojea) [reply pkg/kubelet/prober/prober.go]: I see, I wasn't understanding this correctly, all the workers share the same prober.
This will require to change that so each worker has its own probe, and not share the manager global probe

**Comment by aojea** [comment]
using http reuse breaks IPv6 network tests 🥲 

> /test pull-kubernetes-e2e-kind-ipv6

let's go with the linger option by now

**Comment by dcbw** [comment]
/lgtm

I was surprised to find out that kubelet apparently does all probes in a loop, not in parallel with each other (?)

```
probeLoop:
	for w.doProbe(ctx) {
		// Wait for next probe tick.
		select {
		case <-w.stopCh:
			break probeLoop
		case <-probeTicker.C:
		case <-w.manualTriggerCh:
			// continue
		}
	}
```

so I guess now we'll block for max 1 second in each Close() but before we could potentially block for CLOSE_WAIT time? (Unless I didn't read deeply enough and the socket is actually nonblocking...)

So yeah, 1 is better than 60. Only downside I can think of is that if the app is overloaded, and doesn't get around to answering the probe within 1s, then perhaps we'd get a failure when the app might have been able to finish sending or close in 5 seconds or something. But if not 1s then where...

**Comment by aojea** [comment]
last push to correct the test description , thanks to @qabpea for clarifying the details about how ephemeral allocation ports works

**Comment by aojea** [comment]
> pull-kubernetes-e2e-kind-ipv6 — Job failed.                     
[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/115143/pull-kubernetes-unit/1616160193853263872)

Kubernetes e2e suite: [It] [sig-apps] Deployment should validate Deployment Status endpoints [Conformance] 

> pull-kubernetes-unit	

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/115143/pull-kubernetes-unit/1616160193853263872

k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy: TestRoundTripSocks5AndNewConnection/proxied_without_auth_->_http expand_more	0s
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy: TestRoundTripSocks5AndNewConnection expand_more

/retest

**Comment by aojea** [comment]
> /lgtm
> 
> I was surprised to find out that kubelet apparently does all probes in a loop, not in parallel with each other (?)
> 
> ```
> probeLoop:
> 	for w.doProbe(ctx) {
> 		// Wait for next probe tick.
> 		select {
> 		case <-w.stopCh:
> 			break probeLoop
> 		case <-probeTicker.C:
> 		case <-w.manualTriggerCh:
> 			// continue
> 		}
> 	}
> ```
> 
> so I guess now we'll block for max 1 second in each Close() but before we could potentially block for CLOSE_WAIT time? (Unless I didn't read deeply enough and the socket is actually nonblocking...)
> 
> So yeah, 1 is better than 60. Only downside I can think of is that if the app is overloaded, and doesn't get around to answering the probe within 1s, then perhaps we'd get a failure when the app might have been able to finish sending or close in 5 seconds or something. But if not 1s then where...

the TIME-WAIT status doesn't block the userspace, that time is not influencing the probe.

If my reading is correctly there is one goroutine worker per Pod.Container.ProbeType, so each worker/probe run in parallel, they share the prober though, but doesn't seem to have contention there

The probes always poll in each tick of the time period, if the probe takes longer that the tick, it will be executed always in the next tick, is not going to pile up https://go.dev/play/p/18G2MqRGvtP

https://github.com/kubernetes/kubernetes/blob/02f893b6e28549a1008d4fc65c40990b87c07830/pkg/kubelet/prober/worker.go#L179-L190

**Comment by rphillips** [comment]
Kubelet has code to limit the [http response ](https://github.com/kubernetes/kubernetes/blob/76522eb1a339a95544523c1ed85da09f287f1ade/pkg/probe/http/http.go#L98) for the probe to 10KB. Can you add a test that responds with a ~11 KB payload to make sure this time-wait fix still works? It may, but the underlying code uses a limit reader, so perhaps we might have to add an additional ReadAll() to the probe to drain the receive buffer.

**Comment by aojea** [comment]
> Kubelet has code to limit the [http response ](https://github.com/kubernetes/kubernetes/blob/76522eb1a339a95544523c1ed85da09f287f1ade/pkg/probe/http/http.go#L98) for the probe to 10KB. Can you add a test that responds with a ~11 KB payload to make sure this time-wait fix still works? It may, but the underlying code uses a limit reader, so perhaps we might have to add an additional `ReadAll()` or `io.Copy(ioutil.Discard, resp.Body)` to the probe to drain the receive buffer.

excellent point, let me add it

**Comment by aojea** [comment]
@rphillips it sounds like the one you added here https://github.com/kubernetes/kubernetes/pull/82669?

do you want me to add some permutations of that?

**Comment by rphillips** [comment]
Totally forgot about that commit :) ... Please!

File: pkg/probe/dialer_windows.go [hunk 8]
```diff
@@ -0,0 +1,39 @@
...
+)
+
+// ProbeDialer returns a dialer optimized for probes to avoid lingering sockets on TIME-WAIT state.
+// The dialer reduces the TIME-WAIT period to 1 seconds instead of the OS default of 60 seconds.
+// Ref: https://issues.k8s.io/89898
+func ProbeDialer() *net.Dialer {
+	dialer := &net.Dialer{
+		Control: func(network, address string, c syscall.RawConn) error {
+			return c.Control(func(fd uintptr) {
+				syscall.SetsockoptLinger(syscall.Handle(fd), syscall.SOL_SOCKET, syscall.SO_LINGER, &syscall.Linger{Onoff: 1, Linger: 1})
```
Comment (SergeyKanzhelev) [inline pkg/probe/dialer_windows.go:34]: I hate that there is a big copy-paste just for this type mismatch. I wonder if this be changed with if/else to minimize code duplication and possibility to fail

File: pkg/probe/dialer_others.go [hunk 9]
```diff
@@ -0,0 +1,39 @@
...
+)
+
+// ProbeDialer returns a dialer optimized for probes to avoid lingering sockets on TIME-WAIT state.
+// The dialer reduces the TIME-WAIT period to 1 seconds instead of the OS default of 60 seconds.
+// Ref: https://issues.k8s.io/89898
+func ProbeDialer() *net.Dialer {
+	dialer := &net.Dialer{
+		Control: func(network, address string, c syscall.RawConn) error {
+			return c.Control(func(fd uintptr) {
+				syscall.SetsockoptLinger(int(fd), syscall.SOL_SOCKET, syscall.SO_LINGER, &syscall.Linger{Onoff: 1, Linger: 1})
```
Comment (SergeyKanzhelev) [inline pkg/probe/dialer_others.go:34]: looked on GitHub for examples of this: https://cs.github.com/?scopeName=All+repos&scope=&q=%26syscall.Linger

Most usage is setting Linger to `0`. I don't know implications of this, but why `1`?

File: pkg/kubelet/prober/scale_test.go [hunk 10]
```diff
@@ -0,0 +1,270 @@
...
+
+}
+
+func newProbe(handler v1.ProbeHandler) *v1.Probe {
+	return &v1.Probe{
+		ProbeHandler:     handler,
+		TimeoutSeconds:   1,
+		PeriodSeconds:    1,
+		SuccessThreshold: 1,
+		FailureThreshold: 3,
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/prober/scale_test.go:187]: why `3`? With `1` more chances to make it fail

File: pkg/kubelet/prober/scale_test.go [hunk 11]
```diff
@@ -0,0 +1,270 @@
...
+// that the ephemeral port is not exhausted.
+
+// The default port range on a normal Linux system has 28321 free ephemeral ports per
+// tuple srcIP,srcPort:dstIP:dstPort:Proto: /proc/sys/net/ipv4/ip_local_port_range 32768 60999
+// 1 pods x 600 containers/pod x 1 probes/container x 1 req/sec = 600 req/sec
+// 600 req/sec x 59 sec = 35400
+// The test should run out of ephemeral ports in less than one minute and start failing connections
+// Ref: https://github.com/kubernetes/kubernetes/issues/89898#issuecomment-1383207322
+
+func TestTCPPortExhaustion(t *testing.T) {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/prober/scale_test.go:62]: so much faking required =) Looks good though

File: pkg/kubelet/prober/scale_test.go (hunk 10 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/prober/scale_test.go:187]: oh, I see - it will fail on probe result, not the status update. This number doesn't matter than

File: pkg/kubelet/prober/scale_test.go (hunk 7 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/prober/scale_test.go:161]: nit: Can you make it an explicit comment in code? It was hard to understand when the test will fail.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

I don't know why 1 second was chosen, left the comment about it. Mechanics for sig node look good

File: pkg/probe/dialer_others.go (hunk 9 above)
Comment (thockin) [reply pkg/probe/dialer_others.go:34]: TIME_WAIT exists for a reason, but I don't think that reason is very important to us.  1 seems safer, but I could buy 0 if @aojea proves it out.  Maybe a comment here would help for future readers?

File: pkg/probe/dialer_windows.go (hunk 8 above)
Comment (thockin) [reply pkg/probe/dialer_windows.go:34]: Generics?  This doesn't feel important enough to make very complicated, to me.

File: pkg/probe/http/http.go (hunk 3 above)
Comment (thockin) [inline pkg/probe/http/http.go:56]: Comment that net/http is smart enough to use this if we don't spec the SSL function hook?

**Review by thockin — COMMENTED** [review]
Only requests for comments from me.

LGTM - very surgical

File: pkg/probe/dialer_others.go (hunk 9 above)
Comment (aojea) [reply pkg/probe/dialer_others.go:34]: 0 makes the connection to send a RST, is not a clean close http://www.serverframework.com/asynchronousevents/2011/01/time-wait-and-its-design-implications-for-protocols-and-scalable-servers.html

> SO_LINGER socket option to 0. This causes pending data to be discarded and the connection to be aborted with an RST rather than for the pending data to be transmitted and the connection closed cleanly with a FIN

a common metric to look for network problems is to check the amount of RST on the node, this will generate a lot of false positives, 1 seconds is enough for these connection

File: pkg/probe/dialer_windows.go (hunk 8 above)
Comment (aojea) [reply pkg/probe/dialer_windows.go:34]: I had the same feeling, this was the simplest solution I've found

File: pkg/kubelet/prober/scale_test.go (hunk 10 above)
Comment (aojea) [reply pkg/kubelet/prober/scale_test.go:187]: copy paste thing

File: pkg/kubelet/prober/scale_test.go (hunk 11 above)
Comment (aojea) [reply pkg/kubelet/prober/scale_test.go:62]: we can't use unit tests as root, that will be simpler 🤷

File: pkg/probe/http/http.go (hunk 3 above)
Comment (aojea) [reply pkg/probe/http/http.go:56]: sure

File: pkg/probe/dialer_others.go (hunk 9 above)
Comment (thockin) [reply pkg/probe/dialer_others.go:34]: comment here?

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve
/hold 

hold for @SergeyKanzhelev

File: pkg/probe/dialer_others.go (hunk 9 above)
Comment (aojea) [reply pkg/probe/dialer_others.go:34]: 👍

**Comment by aojea** [comment]
added comment on the choice for linger socket time https://github.com/kubernetes/kubernetes/pull/115143#discussion_r1083083365 and it removed the lgtm, removing the hold and waiting for final lgmt @SergeyKanzhelev 

/hold cancel

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
