### PR TITLE
Initialize flags to support extra flags

### LINKED ISSUE #81498: `flags` should be initialized for apparmor-loader
**What happened**:
docker image built from source doesn't work with below error message, 
```
# kubectl logs apparmor-loader-dcbvp -n apparmor
flag provided but not defined: -logtostderr
Usage: /usr/bin/loader [FLAG]... [PROFILE_DIR]...
Load the AppArmor profiles specified in the PROFILE_DIR directories.
  -poll duration
        Poll the directories for new profiles with this interval. Values < 0 disable polling, and exit after loading the profiles. (default -1ns)
```

run binary doesn't work either, 
```
# ./loader -logtostderr ./tmp/profile
flag provided but not defined: -logtostderr
Usage: ./loader [FLAG]... [PROFILE_DIR]...
Load the AppArmor profiles specified in the PROFILE_DIR directories.
  -poll duration
        Poll the directories for new profiles with this interval. Values < 0 disable polling, and exit after loading the profiles. (default -1ns)
```

**What you expected to happen**:
profile could be loaded successfully.

**How to reproduce it (as minimally and precisely as possible)**:
-  cd test/images
- make all WHAT=apparmor-loader
- create namespace 
- create DaemonSet with the built image
- check the log of the pod,
   kubectl logs apparmor-loader-dcbvp -n apparmor

**Anything else we need to know?**:
should init the flags in the source.

**Environment**:
- Kubernetes version (use `kubectl version`): latest
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): all
- Kernel (e.g. `uname -a`): all
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by chendave**
Signed-off-by: Dave Chen <dave.chen@arm.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
so that the steps in the README could work fine, and the logs could be print out as expected. 

**Which issue(s) this PR fixes**:

Fixes #81498

```release-note
NONE
```

### CODE REVIEW

File: test/images/apparmor-loader/loader.go [hunk 1]
```diff
@@ -44,6 +44,7 @@ const (
 )
 
 func main() {
+	klog.InitFlags(nil)
```
Comment (neolit123) [inline test/images/apparmor-loader/loader.go]: i believe the latest version of klog no longer needs this (k/k possibly hasn't moved to it yet).
but LGTM

/lgtm
/ok-to-test
