### PR TITLE
e2e_node: skip swap tests on cgroupv1

### LINKED ISSUE #125026: [Failing Test] ci-crio-cgroupv1-node-e2e-conformance (Swap Tests)
### Which jobs are failing?

master-informing:
- ci-crio-cgroupv1-node-e2e-conformance

### Which tests are failing?

- E2eNode Suite.[It] [sig-node] Swap [LinuxOnly] [NodeFeature:NodeSwap] [NodeConformance] with configuration QOS Best-effort
- E2eNode Suite.[It] [sig-node] Swap [LinuxOnly] [NodeFeature:NodeSwap] [NodeConformance] with configuration QOS Burstable
- E2eNode Suite.[It] [sig-node] Swap [LinuxOnly] [NodeFeature:NodeSwap] [NodeConformance] with configuration QOS Burstable with memory request equals to limit
- E2eNode Suite.[It] [sig-node] Swap [LinuxOnly] [NodeFeature:NodeSwap] [NodeConformance] with configuration QOS Guaranteed

### Since when has it been failing?

After https://github.com/kubernetes/kubernetes/pull/123557 was merged

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#ci-crio-cgroupv1-node-e2e-conformance

### Reason for failure (if possible)

```
{ failed [FAILED] cgroup v2 is required for swap
In [It] at: k8s.io/kubernetes/test/e2e_node/swap_test.go:73 @ 05/21/24 15:15:20.675
}
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by haircommander**
#### What type of PR is this?

/kind failing-test
#### Which issue(s) this PR fixes:

fixes https://github.com/kubernetes/kubernetes/issues/125026 

#### Does this PR introduce a user-facing change?

```release-note
none
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e_node/swap_test.go [hunk 1]
```diff
@@ -103,7 +106,9 @@ var _ = SIGDescribe("Swap", "[LinuxOnly]", nodefeature.Swap, func() {
 				pod := getSwapTestPod(f, qosClass, memoryRequestEqualLimit)
 				pod = runPodAndWaitUntilScheduled(f, pod)
 
-				gomega.Expect(isPodCgroupV2(f, pod)).To(gomega.BeTrueBecause("cgroup v2 is required for swap"))
+				if !isPodCgroupV2(f, pod) {
+					e2eskipper.Skipf("swap tests require cgroup v2")
+				}
```
Comment (iholder101) [inline test/e2e_node/swap_test.go:111]: Should we also skip under the `f.Context(framework.WithSerial()` context?

As opposed to the node conformance test, this will only run as part of the swap-conformance lanes, and perhaps it should be very visible when they fail instead of silently skipping? WDYT?

Comment (haircommander) [reply test/e2e_node/swap_test.go:111]: ah yeah good point. I'll fix that and add a note

**Comment by iholder101** [comment]
/lgtm
Thank you @haircommander!

**Comment by bart0sh** [comment]
/cc @SergeyKanzhelev @mrunalp @dims 
PTAL, this will make Sig-Node test grid much greener

**Comment by haircommander** [comment]
@iholder101 there are other test lanes failing because they're running serial on cgroupv1. I think until we go through the process of deprecating v1 we should skip these.

**Comment by haircommander** [comment]
@SergeyKanzhelev can you PTAL

**Comment by dims** [comment]
/approve
/lgtm

thanks @haircommander

**Comment by iholder101** [comment]
> @iholder101 there are other test lanes failing because they're running serial on cgroupv1. I think until we go through the process of deprecating v1 we should skip these.

Makes sense. Thank you @haircommander!
