### PR TITLE
Disable invalid test case from dns externalName e2e test

### LINKED ISSUE #50274: [upgrade test failure] DNS should provide DNS for ExternalName services - IP not in range
This e2e test is failing on several of the upgrade tests.

https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster
https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-master
https://k8s-testgrid.appspot.com/master-upgrade#gke-cvm-1.6-cvm-master-upgrade-master

/cc @kubernetes/sig-network-bugs 

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:488
Expected error:
    <*errors.StatusError | 0xc4240b2c80>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "Service \"dns-test-service-3\" is invalid: spec.clusterIP: Invalid value: \"127.1.2.3\": provided IP is not in the valid range",
            Reason: "Invalid",
            Details: {
                Name: "dns-test-service-3",
                Group: "",
                Kind: "Service",
                UID: "",
                Causes: [
                    {
                        Type: "FieldValueInvalid",
                        Message: "Invalid value: \"127.1.2.3\": provided IP is not in the valid range",
                        Field: "spec.clusterIP",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 422,
        },
    }
    Service "dns-test-service-3" is invalid: spec.clusterIP: Invalid value: "127.1.2.3": provided IP is not in the valid range
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:477
```

### PR DESCRIPTION
**Pull request by MrHohn**
**What this PR does / why we need it**:
[gke-gci-1.7-gci-master-upgrade-master](https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-master&sort-by-failures=) and [gke-gci-1.7-gci-master-upgrade-cluster-parallel](https://k8s-testgrid.appspot.com/master-upgrade#gke-gci-1.7-gci-master-upgrade-cluster-parallel&sort-by-failures=)
are still failing `[k8s.io] DNS should provide DNS for ExternalName services`.

Given that https://github.com/kubernetes/kubernetes/issues/35354 isn't fixed in 1.7, and the fix https://github.com/kubernetes/kubernetes/pull/46197 seems rather huge to be cherrypicked, I consider it is reasonable to remove the invalid testcase from 1.7 to stop multiple testsuites from bleeding.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: From #50274

**Special notes for your reviewer**:
I know this is not a great fix but am hoping this is acceptable :(
/assign @bowei @xiangpengzhao 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/dns.go [hunk 1]
```diff
@@ -464,26 +464,5 @@ var _ = framework.KubeDescribe("DNS", func() {
 		pod2 := createDNSPod(f.Namespace.Name, wheezyProbeCmd, jessieProbeCmd, true)
 
 		validateTargetedProbeOutput(f, pod2, []string{wheezyFileName, jessieFileName}, "bar.example.com.")
-
-		// Test changing type from ExternalName to ClusterIP
-		By("changing the service to type=ClusterIP")
```
Comment (xiangpengzhao) [inline test/e2e/dns.go]: I prefer just commenting this test case to removing it. And add one more comment to a) tell the reason why it is commented, b) put the issue link here c) say it will be uncommented in 1.8.

@MrHohn WDYT?

Comment (MrHohn) [reply test/e2e/dns.go]: Thanks for the comment! Yeah that sounds right to me, PTAL.

File: test/e2e/dns.go [hunk 2]
```diff
@@ -465,6 +465,8 @@ var _ = framework.KubeDescribe("DNS", func() {
 
 		validateTargetedProbeOutput(f, pod2, []string{wheezyFileName, jessieFileName}, "bar.example.com.")
 
+		/* Below test case is disabled for v1.7 k8s due to https://github.com/kubernetes/kubernetes/issues/35354.
+		   It is enabled for v1.8+ k8s where the fix is in place.
```
Comment (xiangpengzhao) [inline test/e2e/dns.go]: nit: "k8s" is not so necessary here. Anyway, it's OK as-is.

**Review by xiangpengzhao — COMMENTED** [review]
just a nit. I will lgtm for now. If you'd like to fix the nit, I'll lgtm again :)
/lgtm

File: test/e2e/dns.go (hunk 2 above)
Comment (MrHohn) [reply test/e2e/dns.go]: Sure, fixed the nit :)

**Comment by MrHohn** [comment]
@abgworrall for 1.7 approval

**Comment by abgworrall** [comment]
OK: this cherrypick only affects upgrade test results for the 1.8 release, so I'm putting on my @wojtek-t hat and approving it.
