### PR TITLE
Separate staging/publish and unstaging/unpublish logics for block

### LINKED ISSUE #73773: CSI block: Why is NodePublishVolume called in SetUpDevice?
**What happened**:
I'm doing a retroactive review of the CSI block implementation and I have a few questions:

Why are there 4 different paths that point to the same block device?  I see:
    * [global map path](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/volume/csi/csi_block.go#L55)
    * [staging target path](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/volume/csi/csi_block.go#L63)
    * [publish target path](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/volume/csi/csi_block.go#L70)
    * [pod path](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/volume/csi/csi_block.go#L77)

This seems like an unnecessary amount of redirection. Ideally, global map path == staging target path, and publish target path == pod path.  

Along the same lines, I see that publish target path is not a per pod path and `NodeStageVolume` and `NodePublishVolume` are called in the same SetUpDevice() function. This kind of makes the `NodePublish` call useless because it's just bind mounting the volume to another global location, which is what `NodeStage` already provides. This is also different from filesystem semantics, where NodeStage/Unstage is serialized per volume, and NodePublish/Unpublish is serialized per pod.

**What you expected to happen**:
Can we simplify this and try to align with how the filesystem semantics work?  The more intermediate steps we have, the more likely one of them is going to fail. Also each additional mount consumes kernel resources, and will make operations that need to list all mounts slower.

@kubernetes/sig-storage-bugs 
/assign @mkimuram @vladimirvivien @bswartz

### PR DESCRIPTION
**Pull request by mkimuram**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR changes staging/publish and unstaging/unpublish logics for block to be called from separate methods. Also, publish path is changed to per pod path from per volume path.

[Before]
- ```stageVolumeForBlock```: called from ```SetupDevice```
- ```publishVolumeForBlock```: called from ```SetupDevice```
- ```unstageVolumeForBlock```: called from ```TearDownDevice```
- ```unpublishVolumeForBlock```: called from ```TearDownDevice```
- publish path: ```plugins/kubernetes.io/csi/volumeDevices/publish/{pvname}```

[After]
- ```stageVolumeForBlock```: called from ```SetupDevice```
- ```publishVolumeForBlock```: called from ```MapDevice```
- ```unstageVolumeForBlock```: called from ```TearDownDevice```
- ```unpublishVolumeForBlock```: called from ```UnmapDevice```
- publish path:  ```plugins/kubernetes.io/csi/volumeDevices/publish/{pvname}/{podUid}```

Summary of discussion why this change needed is commented [here](https://github.com/kubernetes/kubernetes/issues/73773#issuecomment-462895942)

**Which issue(s) this PR fixes**:
Fixes #73773

**Special notes for your reviewer**:
/sig storage
@bswartz @msau42  @wongma7 @vladimirvivien 

**Does this PR introduce a user-facing change?**:
```release-note
All nodes need to be drained before upgrading Kubernetes cluster, because paths used for block volumes are changed in this release, so on-line upgrade of nodes aren't allowed. 
```

### CODE REVIEW

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 1]
```diff
@@ -883,14 +889,18 @@ func (og *operationGenerator) GenerateMapVolumeFunc(
...
-		// kubelet, so evaluate it on the host and expect that it links to a device in /dev,
-		// which will be available to containerized kubelet. If still it does not exist,
-		// AttachFileDevice will fail. If kubelet is not containerized, eval it anyway.
-		mounter := og.GetVolumePluginMgr().Host.GetMounter(blockVolumePlugin.GetPluginName())
-		devicePath, err = mounter.EvalHostSymlinks(devicePath)
-		if err != nil {
-			return volumeToMount.GenerateError("MapVolume.EvalHostSymlinks failed", err)
+		// For in-tree drivers, actual device is attached either in WaitForAttach or SetUpDevice,
+		// not in MapDevice below, so devicePath could be checked here.
+		if !isCSI {
```
Comment (mkimuram) [inline pkg/volume/util/operationexecutor/operation_generator.go]: @msau42 @wongma7 

Do you have any better ideas to handle this, so that operation_generator code doesn't need to care whether it is CSI?
We might make ```SetUpDevice``` for CSI return dummy device paht and make all driver resolve symlink from ```volumeMapPath``` below, but I'm not sure if it is better than current one.

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 2]
```diff
@@ -1096,11 +1116,18 @@ func (og *operationGenerator) GenerateUnmapDeviceFunc(
 			}
 		}
 
-		// Execute tear down device
-		unmapErr := blockVolumeUnmapper.TearDownDevice(globalMapPath, deviceToDetach.DevicePath)
+		// Execute unmap device
+		unmapErr := blockVolumeUnmapper.UnmapDevice(globalMapPath, deviceToDetach.DevicePath)
```
Comment (wongma7) [inline pkg/volume/util/operationexecutor/operation_generator.go]: should we call UnmapDevice in the per-pod UnmapVolume instead? Then what if we had all the in-tree plugins called og.blkUtil.UnmapDevice in their plugin.UnmapDevice, and CSI calls Unpublish in its plugin.UnmapDevice

File: pkg/volume/csi/csi_block.go [hunk 3]
```diff
@@ -248,22 +248,58 @@ func (m *csiBlockMapper) SetUpDevice() (string, error) {
...
+	accessMode := v1.ReadWriteOnce
+	if m.spec.PersistentVolume.Spec.AccessModes != nil {
+		accessMode = m.spec.PersistentVolume.Spec.AccessModes[0]
+	}
+
+	ctx, cancel := context.WithTimeout(context.Background(), csiTimeout)
+	defer cancel()
+
 	// Call NodePublishVolume
+	stagingPath := m.getStagingPath()
```
Comment (wongma7) [inline pkg/volume/csi/csi_block.go]: should this be getPublishPath? currently getPublishPath is unused

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 1 above)
Comment (wongma7) [reply pkg/volume/util/operationexecutor/operation_generator.go]: for csi, is the devicePath not the staging path returned by SetUpDevice (NodeStage)?

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 2 above)
Comment (mkimuram) [reply pkg/volume/util/operationexecutor/operation_generator.go]: Thank you for pointing it out.
This will be a big change, so I wanted to make an agreement before go ahead.

I will try implementing this way and update the commit.

File: pkg/volume/csi/csi_block.go (hunk 3 above)
Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: Staging path is used [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_block.go#L190) for publish call, it is due to [CSI spec](https://github.com/container-storage-interface/spec/blame/master/spec.md#L2030).

It's confusing, so I agree that we should change ```publishVolumeForBlock``` not to take ```stagingPath``` as an argument, and get it inside the function, as it is done for [```publishPath```](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_block.go#L172).

**Review by mkimuram — COMMENTED** [review]
@wongma7 

Thank you for your comment.
I will update the commit as suggested.

**Comment by mkimuram** [comment]
@wongma7 

Updated as suggested. PTAL

Note that ref-counting and releasing descriptor lock codes are also moved to CSI's ```UnmapDevice```, almost as they are. We might need to consider more to properly handle all cases including multiple pod mapping case.
(To get feed back early, I'm pushing this commit, after I only confirmed that this worked well with one pod mapping case.)

File: pkg/volume/csi/csi_block.go [hunk 4]
```diff
@@ -252,22 +252,66 @@ func (m *csiBlockMapper) SetUpDevice() (string, error) {
...
 	if err != nil {
 		return "", err
 	}
 
-	// Call NodePublishVolume
-	publishPath, err := m.publishVolumeForBlock(ctx, csiClient, accessMode, csiSource, attachment, stagingPath)
+	return "", nil
+}
+
+func (m *csiBlockMapper) MapDevice(devicePath, globalMapPath, volumeMapPath, volumeMapName string, podUID types.UID) error {
```
Comment (gnufied) [inline pkg/volume/csi/csi_block.go]: We are ignoring supplied `devicePath` parameter in this function and we only use return value of `NodePublish` as real device path. This may or may not be true and is a departure from previous version of this code and I am not sure if it is backward compatible change.  In old version of code - if `NodePublish` returned empty string then value returned by `WaitForAttach` was considered as canonical device path.

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 5]
```diff
@@ -1070,6 +1080,20 @@ func (og *operationGenerator) GenerateMapVolumeFunc(
 			return volumeToMount.GenerateError("MapVolume.MapDevice failed", mapErr)
 		}
 
+		// For CSI driver, devicePath should be checked here by checking symlink from
+		// {volumeMapPath}/{volName}.
```
Comment (gnufied) [inline pkg/volume/util/operationexecutor/operation_generator.go]: Why do we need to do this? Can we have `MapDevice` to return device path? For in-tree plugins it will simply return whatever was passed and for CSI it will return device path after publish.

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 6]
```diff
@@ -1070,6 +1080,20 @@ func (og *operationGenerator) GenerateMapVolumeFunc(
...
+			kvh, ok := og.GetVolumePluginMgr().Host.(volume.KubeletVolumeHost)
+			if !ok {
+				return volumeToMount.GenerateError("MapVolume type assertion error", fmt.Errorf("volume host does not implement KubeletVolumeHost interface"))
+			}
+			hu := kvh.GetHostUtil()
+			devicePath, err = hu.EvalHostSymlinks(filepath.Join(volumeMapPath, volName))
+			if err != nil {
+				return volumeToMount.GenerateError("MapVolume.EvalHostSymlinks failed", err)
+			}
+		}
```
Comment (gnufied) [inline pkg/volume/util/operationexecutor/operation_generator.go]: Also we need to fix when ASOW gets updated after node is staged etc. Currently both device is marked as mounted and volume is marked as mounted at the end. This needs to be split, how filesystem mounting is split.

**Review by gnufied — COMMENTED** [review]
I just reviewed mapdevice flow. I am yet to take a look at Unmap flow.

File: pkg/volume/volume.go [hunk 7]
```diff
@@ -181,6 +181,9 @@ type BlockVolumeUnmapper interface {
 	// If the plugin is non-attachable, this method detaches the volume
 	// from a node.
 	TearDownDevice(mapPath string, devicePath string) error
+
+	// UnmapDevice unmaps the block device path
+	UnmapDevice(globalUnmapPath, podDeviceUnmapPath, volName string, podUID types.UID) error
```
Comment (gnufied) [inline pkg/volume/volume.go]: I am thinking that we should call this function `UnmapPodDevice` or something like that - so as it is evident that this function is actually going to remove device/volume for the pod and not from global mount path.

File: pkg/volume/csi/csi_block.go (hunk 4 above)
Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: @gnufied 

Thank you for your coment.

Fixed by taking `devicePath` returned by `SetupDevice`.
(There's no acutal device at `devicePath` by the time that `SetupDevice` returns, however it would be safe.)

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 5 above)
Comment (mkimuram) [reply pkg/volume/util/operationexecutor/operation_generator.go]: Fixed by directly using the `publishPath` as `devicePath`. (With ignoring error for resolving symlink.)
I thought `publishPath` also need to be resolved for containerized kubelet, so I put this logic here.
However, this assumption won't be true. (I think that `publishPath` could be handled by containerized kubelet.)

Only downside by doing this will be failure in handling error for resolving symlink for in-tree driver.

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 6 above)
Comment (mkimuram) [reply pkg/volume/util/operationexecutor/operation_generator.go]: Fixe by moving  `MarkDeviceAsMounted` before `MapDevice`.

File: pkg/volume/volume.go (hunk 7 above)
Comment (mkimuram) [reply pkg/volume/volume.go]: Then, do we need to also change `MapDevice` to `MapPodDevice`?

If everyone agrees, I will go ahead and change them at once.

File: pkg/volume/csi/csi_block.go [hunk 8]
```diff
@@ -252,21 +252,70 @@ func (m *csiBlockMapper) SetUpDevice() (string, error) {
...
+		attachment, err = m.k8s.StorageV1().VolumeAttachments().Get(attachID, meta.GetOptions{})
+		if err != nil {
+			return errors.New(log("blockMapper.MapDevice failed to get volume attachment [id=%v]: %v", attachID, err))
+		}
+	}
+
+	//TODO (vladimirvivien) implement better AccessModes mapping between k8s and CSI
+	accessMode := v1.ReadWriteOnce
+	if m.spec.PersistentVolume.Spec.AccessModes != nil {
+		accessMode = m.spec.PersistentVolume.Spec.AccessModes[0]
```
Comment (tedyu) [inline pkg/volume/csi/csi_block.go]: Do we care about other elements in AccessModes (len(m.spec.PersistentVolume.Spec.AccessModes) > 1) ?

File: pkg/volume/csi/csi_block.go [hunk 9]
```diff
@@ -252,21 +252,70 @@ func (m *csiBlockMapper) SetUpDevice() (string, error) {
...
+	}
+
+	ctx, cancel := context.WithTimeout(context.Background(), csiTimeout)
+	defer cancel()
+
+	csiClient, err := m.csiClientGetter.Get()
```
Comment (tedyu) [inline pkg/volume/csi/csi_block.go]: It seems this can be lifted ahead of context.WithTimeout call (line 300).

File: pkg/volume/csi/csi_block.go [hunk 10]
```diff
@@ -252,21 +252,70 @@ func (m *csiBlockMapper) SetUpDevice() (string, error) {
...
 	if err != nil {
-		return "", err
+		return err
 	}
 
-	return publishPath, nil
-}
+	// Check that publishPath and devicePath matches
+	if publishPath != devicePath {
+		return errors.New(log("blockMapper.MapDevice failed because publishPath %q and devicePath %q doesn't match", publishPath, devicePath))
```
Comment (tedyu) [inline pkg/volume/csi/csi_block.go]: doesn't match -> don't match

File: pkg/volume/csi/csi_block.go [hunk 11]
```diff
@@ -331,31 +374,75 @@ func (m *csiBlockMapper) TearDownDevice(globalMapPath, devicePath string) error
...
+	// in UnmapDownDevice will fail in detaching device due to the refcnt on the loopback device.
+	err = blkUtil.DetachFileDevice(publishPath)
+	if err != nil {
+		return fmt.Errorf("blockMapper.UnmapDevice DetachFileDevice failed: %v", err)
+	}
+
+	ctx, cancel := context.WithTimeout(context.Background(), csiTimeout)
+	defer cancel()
+
+	csiClient, err := m.csiClientGetter.Get()
```
Comment (tedyu) [inline pkg/volume/csi/csi_block.go]: This can be lifted above line 429

File: pkg/volume/csi/csi_block.go (hunk 9 above)
Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: Thank you for your review and sorry for late response.

I confirmted `SetUpAt` and `TearDownAt` is calling `csiClientGetter.Get` before calling `WithTimeout`.
So, fixed as suggested.

File: pkg/volume/csi/csi_block.go (hunk 10 above)
Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: Fixed.

File: pkg/volume/csi/csi_block.go (hunk 11 above)
Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: Fixed.

File: pkg/volume/csi/csi_block.go (hunk 8 above)
Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: I agree that this should be imporved. 

But I think that this needs to be updated for both filesystem and block, in the same way.
(https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_mounter.go#L176)

So, this would be outside the scope of this PR.
Let's improve this in a separate PR.

File: pkg/volume/volume.go (hunk 7 above)
Comment (wongma7) [reply pkg/volume/volume.go]: Agree to rename. It's quite confusing because there is the UnmapDevice operation, UnmapDevice util function, and here the UnmapDevice method for BlockVolume plugins.

File: pkg/volume/csi/csi_block.go (hunk 4 above)
Comment (wongma7) [reply pkg/volume/csi/csi_block.go]: I don't follow, we don't use devicePath so should we set it to _? A short comment could explain that the plugin doesn't accept a devicePath because it cannot know the devicePath, i.e. whatever path on the node where the device actually exists, until after it has called NodePublish.

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 12]
```diff
@@ -1054,6 +1054,12 @@ func (og *operationGenerator) GenerateMapVolumeFunc(
 			klog.Infof(volumeToMount.GenerateMsgDetailed("MapVolume.WaitForAttach succeeded", fmt.Sprintf("DevicePath %q", devicePath)))
 
 		}
+		// For CSI driver, WaitForAttach returns attachment name as devicePath,
+		// not actual devicePath.
```
Comment (wongma7) [inline pkg/volume/util/operationexecutor/operation_generator.go]: can you also add a little note here to say that for CSI the devicePath is returned by the below SetUpDevice instead.

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 13]
```diff
@@ -1054,6 +1054,12 @@ func (og *operationGenerator) GenerateMapVolumeFunc(
...
+		var isCSI bool
+		if strings.HasPrefix(devicePath, "csi-") {
+			isCSI = true
+		}
 		// A plugin doesn't have attacher also needs to map device to global map path with SetUpDevice()
```
Comment (wongma7) [inline pkg/volume/util/operationexecutor/operation_generator.go]: I know this is outside your PR but since we are here re-evaluating the meaning of devicePath etc. as it gets passed through various functions, its meaning dependent on CSI vs non-CSI, can we reword or remove this comment. TBH I don't know what it means

**Review by wongma7 — COMMENTED** [review]
will do more thorough review soon, thanks and sorry for not looking at it for months!!

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 12 above)
Comment (wongma7) [reply pkg/volume/util/operationexecutor/operation_generator.go]: NVM, see comment below about the "// A plugin doesn't have attacher" comment. If we can clarify that comment then we don't need a duplicate comment above.

File: pkg/volume/csi/csi_block.go [hunk 14]
```diff
@@ -67,10 +68,10 @@ func (m *csiBlockMapper) getStagingPath() string {
 }
 
 // getPublishPath returns a publish path for a file (on the node) that should be used on NodePublishVolume/NodeUnpublishVolume
-// Example: plugins/kubernetes.io/csi/volumeDevices/publish/{pvname}
+// Example: plugins/kubernetes.io/csi/volumeDevices/publish/{pvname}/{podUid}
 func (m *csiBlockMapper) getPublishPath() string {
 	sanitizedSpecVolID := utilstrings.EscapeQualifiedName(m.specName)
-	return filepath.Join(m.plugin.host.GetVolumeDevicePluginDir(CSIPluginName), "publish", sanitizedSpecVolID)
```
Comment (wongma7) [inline pkg/volume/csi/csi_block.go]: shouldn't sanitizedSpecVolID be m.volumeID, not come from the PV name?

Comment (wongma7) [reply pkg/volume/csi/csi_block.go]: the spec says publish/stage should be idempotent per volumeID & m.volumeID is taken from PV volumeHandle

Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: Changed to use volumeID.

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 13 above)
Comment (mkimuram) [reply pkg/volume/util/operationexecutor/operation_generator.go]: Improved the comments.

File: pkg/volume/volume.go (hunk 7 above)
Comment (mkimuram) [reply pkg/volume/volume.go]: Renamed. Thank you for your explanation on the reason for rename.

**Review by mkimuram — COMMENTED** [review]
@wongma7 

Thank you for your review. PTAL

File: pkg/volume/csi/csi_block.go [hunk 15]
```diff
@@ -331,31 +373,96 @@ func (m *csiBlockMapper) TearDownDevice(globalMapPath, devicePath string) error
...
+		err := m.unstageVolumeForBlock(ctx, csiClient, stagingPath)
 		if err != nil {
 			return err
 		}
 	}
 
-	// Call NodeUnstageVolume
-	stagingPath := m.getStagingPath()
-	if _, err := os.Stat(stagingPath); err != nil {
+	dataDir := getVolumeDeviceDataDir(m.specName, m.plugin.host)
```
Comment (wongma7) [inline pkg/volume/csi/csi_block.go]: this change was just reverted :/ https://github.com/kubernetes/kubernetes/pull/83379

Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: Thank you for quickly letting me know it!

File: pkg/volume/csi/csi_block.go [hunk 16]
```diff
@@ -331,31 +373,96 @@ func (m *csiBlockMapper) TearDownDevice(globalMapPath, devicePath string) error
...
+	if _, err := os.Stat(publishPath); err != nil {
 		if os.IsNotExist(err) {
-			klog.V(4).Infof(log("blockMapper.TearDownDevice stagingPath(%s) has already been deleted, skip calling NodeUnstageVolume", stagingPath))
+			klog.V(4).Infof(log("blockMapper.UnmapPodDevice publishPath(%s) has already been deleted, skip calling NodeUnpublishVolume", publishPath))
 		} else {
 			return err
 		}
 	} else {
-		err := m.unstageVolumeForBlock(ctx, csiClient, stagingPath)
+		err := m.unpublishVolumeForBlock(ctx, csiClient, publishPath)
```
Comment (wongma7) [inline pkg/volume/csi/csi_block.go]: since we have changed publishPath and stagingPath, there might be a backwards-compatibility issue.

Previously, we created a symlink in the pod's volume directory to `plugins/kubernetes.io/csi/volumeDevices/publish/{pvname}`.
Now, we create a symlink in the pod's volume directory to `plugins/kubernetes.io/csi/volumeDevices/publish/{volumeID}/{podUID}`.

After an upgrade, we ask the plugin to unpublish `plugins/kubernetes.io/csi/volumeDevices/publish/{volumeID}/{podUID}` even if it, before the upgrade, published `plugins/kubernetes.io/csi/volumeDevices/publish/{pvname}`. So `plugins/kubernetes.io/csi/volumeDevices/publish/{pvname}` will be stuck in published state.

We may need to follow the symlink in the pod's volume directory to see if it links to the new path or the old path and call unpublish appropriately.

Comment (wongma7) [reply pkg/volume/csi/csi_block.go]: proper upgrade procedure you are supposed to drain the node first. So I'm not sure this is worth fixing.

File: pkg/volume/csi/csi_block.go [hunk 17]
```diff
@@ -331,31 +372,75 @@ func (m *csiBlockMapper) TearDownDevice(globalMapPath, devicePath string) error
...
+	publishPath := m.getPublishPath()
+	blkUtil := volumepathhandler.NewBlockVolumePathHandler()
+	// Search under globalMapPath dir if all symbolic links from pods have been removed already.
+	// If symbolic links are there, pods may still refer the volume.
+	refs, err := blkUtil.GetDeviceSymlinkRefs(publishPath, globalMapPath)
+	if err != nil {
+		return err
+	}
+	if len(refs) > 0 {
+		return fmt.Errorf("blockMapper.UnmapPodDevice The device %q is still referenced from other Pods %v", globalMapPath, refs)
```
Comment (wongma7) [inline pkg/volume/csi/csi_block.go]: this seems wrong, I thought we want to call NodeUnpublish every time we call UnmapDevice from the UnmapVolume operation.

File: pkg/volume/csi/csi_block.go (hunk 16 above)
Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: Good investigation!
Then, should we add a caution like below in release notes?

```
Before this release, staging path and publish path for CSI block volume were as follows:
- Staging path: plugins/kubernetes.io/csi/volumeDevices/staging/{pvname}
- Publish path: plugins/kubernetes.io/csi/volumeDevices/publish/{pvname}
In this release these are changed as follows:
- Staging path: plugins/kubernetes.io/csi/volumeDevices/staging/{volumeID}
- Publish path: plugins/kubernetes.io/csi/volumeDevices/publish/{volumeID}/{podUID}

As a result, upgrading Kubernetes cluster while any pods with CSI block volumes running on a node will cause these path inconsistent, which will lead failure in unstaging/unpublishing volume. 
Therefore, all nodes need to be drained before upgrading Kubernetes cluster.
```

Any improvements in wording are welcome.

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 18]
```diff
@@ -1316,31 +1316,18 @@ func (og *operationGenerator) GenerateUnmapDeviceFunc(
 		}
 
 		// The block volume is not referenced from Pods. Release file descriptor lock.
-		// This should be done before calling TearDownDevice, because some plugins that do local detach
-		// in TearDownDevice will fail in detaching device due to the refcnt on the loopback device.
-		klog.V(4).Infof("UnmapDevice: deviceToDetach.DevicePath: %v", deviceToDetach.DevicePath)
-		loopPath, err := og.blkUtil.GetLoopDevice(deviceToDetach.DevicePath)
+		// This should be done before calling UnmapDevice, because some plugins that do local detach
+		// in UnmapDownDevice will fail in detaching device due to the refcnt on the loopback device.
```
Comment (wongma7) [inline pkg/volume/util/operationexecutor/operation_generator.go]: should it be TearDownDevice instead of UnmapDownDevice/UnmapDevice

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 19]
```diff
@@ -1316,31 +1316,18 @@ func (og *operationGenerator) GenerateUnmapDeviceFunc(
...
+		err = og.blkUtil.DetachFileDevice(deviceToDetach.DevicePath)
```
Comment (wongma7) [inline pkg/volume/util/operationexecutor/operation_generator.go]: so for CSI, this call will do nothing, is that right. Since CSI did AttachFileDevice for each of its publish paths, rather than at the deviceToDetach.DevicePath...

File: pkg/volume/csi/csi_block.go (hunk 16 above)
Comment (wongma7) [reply pkg/volume/csi/csi_block.go]: Thanks, IMO it doesn't need to be too detailed about the specific paths, the last two sentences reminding people that nodes need to be drained else unpublish/unstage will fail should be enough.

File: pkg/volume/csi/csi_block.go (hunk 17 above)
Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: This is intended to avoid releasing descriptor lock by calling `DetachFileDevice`, if other pods are still using this device.

For CSI plugins that don't implement node stage/unstage, actual detach of the device from the node will happen in node unpublish. So, this kind of plugins requires descriptor lock to be released before calling node unpublish. 
(Releasing descriptor lock before calling `TearDownDevice`, or node unstage, in `GenerateUnmapDeviceFunc` is too late for such plugins. Actually, CSI rbd puglin doesn't work well with this code.)

And this code seems to be incorrect for CSI plugins that implement node stage/unstage, as you pointed out.

I started to think that we might need to move node unpublish to `TearDownDevice` if CSI plugins don't implement node stage/unstage. WDYT?

Comment (wongma7) [reply pkg/volume/csi/csi_block.go]: If a CSI plugin is capable of publishing the same volume ID to two different paths (MULTI_NODE) it must also be capable of unpublishing the same volume ID from them independently. The current code makes it so that if I NodePublish(vol-a, path-1) and NodePublish(vol-a, path-2), only one of NodeUnpublish(vol-a, path-1) and NodeUnpublish(vol-a, path-2) will ever be called, but I would expect both to be called eventually, and that's why I say something seems wrong.

I understand this logic is here because the file descriptor lock will prevent, for certain plugins, a NodeUnpublish(vol-a, path-x) from succeeding. I would rather see us change the file descriptor lock logic than move the unpublish call, because I think the way you have aligned CSI calls to operations makes the most sense still.

What if we put this code in operation generator's UnmapVolume (to before UnmapPodDevice is called) and removed it from operation generator's UnmapDevice?

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 19 above)
Comment (wongma7) [reply pkg/volume/util/operationexecutor/operation_generator.go]: NVM, we discussed more in detail above the purpose of DetachFileDevice.

File: pkg/volume/csi/csi_block.go (hunk 17 above)
Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: Thank you for your suggestion. I've changed as suggested. 
By this change, we don't need any special handlings in CSI codes for it.

Also, as we changed publish path, or `devicePath`,  to be per pod for CSI, we will be able to expect only one symlink to the `devicePath` for CSI driver in `unmapVolumeFunc`.
(On the other hand, in-tree driver would stack here if the same block volume is attached to multiple pods on the same node, until all the pods on the same node will be deleted (Unless devicePath become per pod, too.))

PTAL

Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: Ummm... With this code, number of symlinks won't be decremented because `UnmapPodDevice` isn't called, when more than one symlinks exist, as a result `UnmapPodDevice` will never be called for the above in-tree situation.

We might be able to move `UnmapBlockVolume` to `unmapVolumeFunc`  from driver's `UnmapPodDevice` to work around this, but I'm not sure this will be the right direction.

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 20]
```diff
@@ -1217,6 +1222,31 @@ func (og *operationGenerator) GenerateUnmapVolumeFunc(
...
+
+		// Search under globalUnmapPath dir if all symbolic links except this pod have been removed already.
+		// If number of symbolic links are more than one, another pods may still refer the volume.
+		refs, err := og.blkUtil.GetDeviceSymlinkRefs(devicePath, globalUnmapPath)
+		if err != nil {
+			return volumeToUnmount.GenerateError("UnmapVolume.GetDeviceSymlinkRefs check failed", err)
+		}
+		if len(refs) > 1 {
+			err = fmt.Errorf("The device %q is still referenced from other Pods %v", globalUnmapPath, refs)
+			return volumeToUnmount.GenerateError("UnmapVolume failed", err)
```
Comment (wongma7) [inline pkg/volume/util/operationexecutor/operation_generator.go]: we could DetachFileDevice only if len(refs) == 1 but still proceed to UnmapPodDevice if len(refs) > 1?

Comment (wongma7) [reply pkg/volume/util/operationexecutor/operation_generator.go]: No, that won't work. Continuing discussion in original thread...

File: pkg/volume/csi/csi_block.go (hunk 17 above)
Comment (wongma7) [reply pkg/volume/csi/csi_block.go]: > We might be able to move UnmapBlockVolume to unmapVolumeFunc from driver's UnmapPodDevice to work around this, but I'm not sure this will be the right direction.

I think something like this is the correct fix. Right now, it is implicitly required that every plugin must execute this block of code to put a symlink in globalMapPath: 
https://github.com/kubernetes/kubernetes/blob/8635f7a0b09301227470ca7c229fc1aab5458984/pkg/volume/util/util.go#L521
and them remove it later:
https://github.com/kubernetes/kubernetes/pull/74026/files#diff-c3acf7a7fec401d0a3cb4998088ee1e5R547

Instead of having this implicit requirement, and every plugin doing the same thing, we should move this logic outside of the plugin and into the operation_generator. The plugin implementation should not have to worry about the file lock or the globalMapPath, if we keep that logic isolated to operation_generator I think it will be much easier to understand.

Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: Thank you for your comment. I will go ahead and fix further.
Also, I found that descriptor lock is taken every time after map, so we should release it every time before map. (And, it could be inside map/unmap utility function.)

Comment (wongma7) [reply pkg/volume/csi/csi_block.go]: > Also, as we changed publish path, or devicePath, to be per pod for CSI, we will be able to expect only one symlink to the devicePath for CSI driver in unmapVolumeFunc.

Hmm I am having trouble following, which symlink do you mean? globalMapPath is still per-volume, not per-pod https://github.com/kubernetes/kubernetes/pull/74026/files#diff-ed824558531f8d1f616bc2f976266b64R53 and publishPath used to be per-volume, now it is per-pod. 

globalMapPath is per-volume and is for ref-counting via symlinks to publishPath/devicePath
publishPath is per-pod and is for 
- symlinking to pod mount path (e.g. /var/lib/kubelet/pods/{podUID}/volumes/{escapeQualifiedPluginName}/{outerVolumeSpecName}/) 
- locking (AttachFileDevice)

We lock the publishPath after CSI NodePublish.
a. if the publishPath is a symlink to another file, that file will be locked
b. if the publishPath is its own file, it will be locked

Now, let's say the same volume is NodePublished again to a different path.
a. if the publishPath is a symlink to another file, that file is already locked: no problem, idempotent
b. if the publishPath is its own file, it will be locked.

What do we do when one of the volume needs to be unmapped.
a. if the publishPath is a symlink to another file, we should not unlock it
b. if the publishPath is its own file, we should unlock it

How do we distinguish between case a and case b...

Comment (wongma7) [reply pkg/volume/csi/csi_block.go]: To summarize issue, the in-tree plugins could always safely assume that there is a 1:1 mapping between  volumeID and devicePath. But now there could be 1:many mapping between volumeID and devicePath.

Comment (wongma7) [reply pkg/volume/csi/csi_block.go]: also there is a case c where publishPath is a bind mount to a /dev/a. in which case I don't think there needs to be a lock on /dev/a at all because device will be busy and can't be detached.

I am not an expert on why the lock is here in the first place.

Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: I was only thinking about UnmapPodDevice call for CSI plugin is not blocked by current reference count logic. 

As you explained, we need to think about adding another logics:
  - To block calling node unpublish for CSI plugins that don't have unstage if the device is still in use,
  - To block calling node unstage for CSI plugins that have unstage if the device is still in use.

I've manually tested how loopback device works with bind mount and symlink. Please see below:

<details>

```
[Bind mount case]
1. Prepare files to be used
# dd if=/dev/zero of=/tmp/file1 bs=512 count=1
# mkdir /tmp/{publish,globalmap}
# touch /tmp/publish/pod1
# touch /tmp/publish/pod2

2. Prepare pseudo device file
# losetup /dev/loop0 /tmp/file1

3. Prepare pseudo published device
# mount --bind /dev/loop0 /tmp/publish/pod1
# mount --bind /dev/loop0 /tmp/publish/pod2

4. Prepare pseudo globalmap file
# ln -s /tmp/publish/pod1  /tmp/globalmap/pod1
# ln -s /tmp/publish/pod2  /tmp/globalmap/pod2

5. Check current status (Symlinks under globalmap path reference to different publish path.)
# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         0  0 /tmp/file1

# ls -l /tmp/publish/
total 0
brw-rw----. 1 root disk 7, 0 Oct  3 20:50 pod1
brw-rw----. 1 root disk 7, 0 Oct  3 20:50 pod2

# ls -l /tmp/globalmap/
total 0
lrwxrwxrwx. 1 root root 17 Oct  3 20:52 pod1 -> /tmp/publish/pod1
lrwxrwxrwx. 1 root root 17 Oct  3 20:53 pod2 -> /tmp/publish/pod2

6. Take descriptor lock
# losetup /dev/loop1 /tmp/publish/pod1
# losetup /dev/loop2 /tmp/publish/pod2

# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         0  0 /tmp/file1
/dev/loop1         0      0         0  0 /tmp/publish/pod1
/dev/loop2         0      0         0  0 /tmp/publish/pod2

7. Check that device can't be deleted before descriptor lock is released
# losetup -d /dev/loop0
# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         1  0 /tmp/file1
/dev/loop1         0      0         0  0 /tmp/publish/pod1
/dev/loop2         0      0         0  0 /tmp/publish/pod2

# losetup -d /dev/loop1
# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         1  0 /tmp/file1
/dev/loop2         0      0         0  0 /tmp/publish/pod2

# umount /tmp/publish/pod1
# ls -l /tmp/publish/
total 0
-rw-r--r--. 1 root root    0 Oct  3 20:50 pod1
brw-rw----. 1 root disk 7, 0 Oct  3 21:14 pod2

# losetup -d /dev/loop2
# losetup 

# umount /tmp/publish/pod2
# ls -l /tmp/publish/
total 0
-rw-r--r--. 1 root root 0 Oct  3 20:50 pod1
-rw-r--r--. 1 root root 0 Oct  3 20:50 pod2

8. Clean up
# rm -rf /tmp/file1 /tmp/publish/ /tmp/globalmap/


[Symlink case]
1. Prepare files to be used
# dd if=/dev/zero of=/tmp/file1 bs=512 count=1
# mkdir /tmp/{publish,globalmap}

2. Prepare pseudo device file
# losetup /dev/loop0 /tmp/file1

3. Prepare pseudo published device
# ln -s /dev/loop0 /tmp/publish/pod1 
# ln -s /dev/loop0 /tmp/publish/pod2

4. Prepare pseudo globalmap file
# ln -s /tmp/publish/pod1  /tmp/globalmap/pod1
# ln -s /tmp/publish/pod2  /tmp/globalmap/pod2

5. Check current status (Symlinks under globalmap path reference to different publish path.)
# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         0  0 /tmp/file1

# ls -l /tmp/publish/
total 0
lrwxrwxrwx. 1 root root 10 Oct  3 21:20 pod1 -> /dev/loop0
lrwxrwxrwx. 1 root root 10 Oct  3 21:20 pod2 -> /dev/loop0

# ls -l /tmp/globalmap/
total 0
lrwxrwxrwx. 1 root root 17 Oct  3 21:20 pod1 -> /tmp/publish/pod1
lrwxrwxrwx. 1 root root 17 Oct  3 21:20 pod2 -> /tmp/publish/pod2

6. Take descriptor lock
# losetup /dev/loop1 /tmp/publish/pod1
# losetup /dev/loop2 /tmp/publish/pod2

# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         0  0 /tmp/file1
/dev/loop1         0      0         0  0 /dev/loop0
/dev/loop2         0      0         0  0 /dev/loop0

7. Check that device can't be deleted before descriptor lock is released
# losetup -d /dev/loop0
# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         1  0 /tmp/file1
/dev/loop1         0      0         0  0 /dev/loop0
/dev/loop2         0      0         0  0 /dev/loop0

# losetup -d /dev/loop1
# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         1  0 /tmp/file1
/dev/loop2         0      0         0  0 /dev/loop0

# rm -f /tmp/publish/pod1
# ls -l /tmp/publish/
total 0
lrwxrwxrwx. 1 root root 10 Oct  3 21:20 pod2 -> /dev/loop0


# losetup -d /dev/loop2
# losetup 

# rm -f /tmp/publish/pod2
# ls -l /tmp/publish/
total 0

8. Clean up
# rm -rf /tmp/file1 /tmp/publish/ /tmp/globalmap/
```
</details>

Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: I'm thinking about making globalMap a bind mount instead of symlink and take descriptor lock for globalMap instead of devicePath (Then, it will be per pod lock, as well as ref count. Also, it will be idempotent).

If descriptor lock is taken to devicePath and CSI driver makes device available on publishPath as a symlink, we can't distinguish for which pod descriptor lock was taken, because losetup -j show the resolved path (Please see [Symlink case]'s step 6 in details sections of previous comment).

If we change globalMap to bind mount and take descriptor lock to it, we can see which descriptor lock is taken for which pod and who takes descriptor lock for the device (Please compare step 4 and step 6 in details sections of this comment and previous one).

[Current implementation]
````
                                    devicePath                            globalMap
                                   -------------                   ----------------------
1. actual device -- symlink    --> publishPath     <-- symlink --   glolbalMapPath/PodUID
2. actual device -- bind mount --> publishPath     <-- symlink --   glolbalMapPath/PodUID
3.                                 actual device   <-- symlink --   glolbalMapPath/PodUID
                                     ^--- descriptor lock
````

[This idea]
````
                                    devicePath                               globalMap
                                   -------------                       ----------------------
1. actual device -- symlink    --> publishPath     <-- bind mount --   glolbalMapPath/PodUID
2. actual device -- bind mount --> publishPath     <-- bind mount --   glolbalMapPath/PodUID
3.                                 actual device   <-- bind mount --   glolbalMapPath/PodUID
                                                                        ^--- descriptor lock
````

<details>

````
[Bind mount case]
1. Prepare files to be used
# dd if=/dev/zero of=/tmp/file1 bs=512 count=1
# mkdir /tmp/{publish,globalmap}
# touch /tmp/publish/pod1
# touch /tmp/publish/pod2

2. Prepare pseudo device file
# losetup /dev/loop0 /tmp/file1

3. Prepare pseudo published device
# mount --bind /dev/loop0 /tmp/publish/pod1
# mount --bind /dev/loop0 /tmp/publish/pod2

4. Prepare pseudo globalmap file
# touch /tmp/globalmap/{pod1,pod2}
# mount --bind /tmp/publish/pod1 /tmp/globalmap/pod1
# mount --bind /tmp/publish/pod2 /tmp/globalmap/pod2

5. Check current status (Symlinks under globalmap path reference to different publish path.)
# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         0  0 /tmp/file1

# ls -l /tmp/publish/
total 0
brw-rw----. 1 root disk 7, 0 Oct  4 12:33 pod1
brw-rw----. 1 root disk 7, 0 Oct  4 12:33 pod2

# ls -l /tmp/globalmap/
total 0
brw-rw----. 1 root disk 7, 0 Oct  4 12:33 pod1
brw-rw----. 1 root disk 7, 0 Oct  4 12:33 pod2

# findmnt | grep pod
├─/tmp/publish/pod1                   devtmpfs[/loop0] devtmpfs   rw,nosuid,seclabel,size=484564k,nr_inodes=121141,mode=755
├─/tmp/publish/pod2                   devtmpfs[/loop0] devtmpfs   rw,nosuid,seclabel,size=484564k,nr_inodes=121141,mode=755
├─/tmp/globalmap/pod1                 devtmpfs[/loop0] devtmpfs   rw,nosuid,seclabel,size=484564k,nr_inodes=121141,mode=755
└─/tmp/globalmap/pod2                 devtmpfs[/loop0] devtmpfs   rw,nosuid,seclabel,size=484564k,nr_inodes=121141,mode=755

6. Take descriptor lock
# losetup /dev/loop1 /tmp/globalmap/pod1
# losetup /dev/loop2 /tmp/globalmap/pod2

# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         0  0 /tmp/file1
/dev/loop1         0      0         0  0 /tmp/globalmap/pod1
/dev/loop2         0      0         0  0 /tmp/globalmap/pod2

# losetup -j /tmp/globalmap/pod1
/dev/loop1: [0005]:9426815 (/tmp/globalmap/pod1)
/dev/loop2: [0005]:9426815 (/tmp/globalmap/pod2)

# losetup -j /tmp/globalmap/pod2
/dev/loop1: [0005]:9426815 (/tmp/globalmap/pod1)
/dev/loop2: [0005]:9426815 (/tmp/globalmap/pod2)

7. Check that device can't be deleted before descriptor lock is released
# losetup -d /dev/loop0
# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         1  0 /tmp/file1
/dev/loop1         0      0         0  0 /tmp/globalmap/pod1
/dev/loop2         0      0         0  0 /tmp/globalmap/pod2


# losetup -d /dev/loop1
# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         1  0 /tmp/file1
/dev/loop2         0      0         0  0 /tmp/globalmap/pod2

# umount /tmp/globalmap/pod1
# ls -l /tmp/globalmap
total 0
-rw-r--r--. 1 root root    0 Oct  4 12:34 pod1
brw-rw----. 1 root disk 7, 0 Oct  4 12:40 pod2

# umount /tmp/publish/pod1
# ls -l /tmp/publish/
total 0
-rw-r--r--. 1 root root    0 Oct  4 12:33 pod1
brw-rw----. 1 root disk 7, 0 Oct  4 12:40 pod2

# losetup -d /dev/loop2
# losetup 

# umount /tmp/globalmap/pod2
# ls -l /tmp/globalmap
total 0
-rw-r--r--. 1 root root 0 Oct  4 12:34 pod1
-rw-r--r--. 1 root root 0 Oct  4 12:34 pod2

# umount /tmp/publish/pod2
# ls -l /tmp/publish/
total 0
-rw-r--r--. 1 root root 0 Oct  4 12:33 pod1
-rw-r--r--. 1 root root 0 Oct  4 12:33 pod2

8. Clean up
# rm -rf /tmp/file1 /tmp/publish/ /tmp/globalmap/


[Symlink case]
1. Prepare files to be used
# dd if=/dev/zero of=/tmp/file1 bs=512 count=1
# mkdir /tmp/{publish,globalmap}

2. Prepare pseudo device file
# losetup /dev/loop0 /tmp/file1

3. Prepare pseudo published device
# ln -s /dev/loop0 /tmp/publish/pod1 
# ln -s /dev/loop0 /tmp/publish/pod2

4. Prepare pseudo globalmap file
# ln -s /tmp/publish/pod1  /tmp/globalmap/pod1
# ln -s /tmp/publish/pod2  /tmp/globalmap/pod2

# touch /tmp/globalmap/{pod1,pod2}
# mount --bind /tmp/publish/pod1 /tmp/globalmap/pod1
# mount --bind /tmp/publish/pod2 /tmp/globalmap/pod2

5. Check current status (Symlinks under globalmap path reference to different publish path.)
# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         0  0 /tmp/file1

# ls -l /tmp/publish/
total 0
lrwxrwxrwx. 1 root root 10 Oct  4 12:44 pod1 -> /dev/loop0
lrwxrwxrwx. 1 root root 10 Oct  4 12:44 pod2 -> /dev/loop0

# ls -l /tmp/globalmap/
total 0
brw-rw----. 1 root disk 7, 0 Oct  4 12:44 pod1
brw-rw----. 1 root disk 7, 0 Oct  4 12:44 pod2

# findmnt | grep pod
├─/tmp/globalmap/pod1                 devtmpfs[/loop0] devtmpfs   rw,nosuid,seclabel,size=484564k,nr_inodes=121141,mode=755
└─/tmp/globalmap/pod2                 devtmpfs[/loop0] devtmpfs   rw,nosuid,seclabel,size=484564k,nr_inodes=121141,mode=755


6. Take descriptor lock
# losetup /dev/loop1 /tmp/publish/pod1
# losetup /dev/loop2 /tmp/publish/pod2

# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         0  0 /tmp/file1
/dev/loop1         0      0         0  0 /dev/loop0
/dev/loop2         0      0         0  0 /dev/loop0

# losetup /dev/loop1 /tmp/globalmap/pod1
# losetup /dev/loop2 /tmp/globalmap/pod2

# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         0  0 /tmp/file1
/dev/loop1         0      0         0  0 /tmp/globalmap/pod1
/dev/loop2         0      0         0  0 /tmp/globalmap/pod2

# losetup -j /tmp/globalmap/pod1
/dev/loop1: [0005]:9426815 (/tmp/globalmap/pod1)
/dev/loop2: [0005]:9426815 (/tmp/globalmap/pod2)

# losetup -j /tmp/globalmap/pod2
/dev/loop1: [0005]:9426815 (/tmp/globalmap/pod1)
/dev/loop2: [0005]:9426815 (/tmp/globalmap/pod2)


7. Check that device can't be deleted before descriptor lock is released
# losetup -d /dev/loop0
# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         1  0 /tmp/file1
/dev/loop1         0      0         0  0 /tmp/globalmap/pod1
/dev/loop2         0      0         0  0 /tmp/globalmap/pod2


# losetup -d /dev/loop1
# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         1  0 /tmp/file1
/dev/loop2         0      0         0  0 /dev/loop0

# umount /tmp/globalmap/pod1
# ls -l /tmp/globalmap
total 0
-rw-r--r--. 1 root root    0 Oct  4 12:45 pod1
brw-rw----. 1 root disk 7, 0 Oct  4 12:48 pod2

# rm -f /tmp/publish/pod1
# ls -l /tmp/publish/
total 0
lrwxrwxrwx. 1 root root 10 Oct  4 12:44 pod2 -> /dev/loop0

# losetup -d /dev/loop2
# losetup 

# umount /tmp/globalmap/pod2
# ls -l /tmp/globalmap
total 0
-rw-r--r--. 1 root root 0 Oct  4 12:45 pod1
-rw-r--r--. 1 root root 0 Oct  4 12:45 pod2

# rm -f /tmp/publish/pod2
# ls -l /tmp/publish/
total 0

8. Clean up
# rm -rf /tmp/file1 /tmp/publish/ /tmp/globalmap/
````
</details>

Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: @wongma7 

Changed as commented above (Please also see the details below, for how pathes look like when block volumes are mapped). I will work on further debugging and improvement, but I would appreciate it if you could also review the current code.

<details>

```
Events:
  Type     Reason                  Age        From                     Message
  ----     ------                  ----       ----                     -------
  Normal   Scheduled               <unknown>  default-scheduler        Successfully assigned default/pod001-block to 127.0.0.1
  Normal   SuccessfulAttachVolume  25s        attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-82051086-eb98-4dd0-941a-1512bc438278"
  Warning  FailedMapVolume         16s        kubelet, 127.0.0.1       MapVolume.MapBlockVolume failed for volume "pvc-82051086-eb98-4dd0-941a-1512bc438278" : device not found
  Normal   SuccessfulMountVolume   15s        kubelet, 127.0.0.1       MapVolume.MapPodDevice succeeded for volume "pvc-82051086-eb98-4dd0-941a-1512bc438278" globalMapPath "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-82051086-eb98-4dd0-941a-1512bc438278/dev"
  Normal   SuccessfulMountVolume   15s        kubelet, 127.0.0.1       MapVolume.MapPodDevice succeeded for volume "pvc-82051086-eb98-4dd0-941a-1512bc438278" volumeMapPath "/var/lib/kubelet/pods/c34639f6-0a8f-458f-bf8e-24a284788187/volumeDevices/kubernetes.io~csi"
  Normal   Pulled                  14s        kubelet, 127.0.0.1       Container image "k8s.gcr.io/busybox:1.24" already present on machine
  Normal   Created                 13s        kubelet, 127.0.0.1       Created container container001
  Normal   Started                 12s        kubelet, 127.0.0.1       Started container container001


# ls -l /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-82051086-eb98-4dd0-941a-1512bc438278/dev
total 0
brwxrwxrwx. 1 root disk 251, 80 Oct  5 00:37 c34639f6-0a8f-458f-bf8e-24a284788187

# ls -l /var/lib/kubelet/pods/c34639f6-0a8f-458f-bf8e-24a284788187/volumeDevices/kubernetes.io~csi
total 4
lrwxrwxrwx. 1 root root 175 Oct  5 00:37 pvc-82051086-eb98-4dd0-941a-1512bc438278 -> /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/0001-0009-rook-ceph-0000000000000001-3745bc30-e708-11e9-b798-0242ac110005/c34639f6-0a8f-458f-bf8e-24a284788187

# losetup | grep '/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-82051086-eb98-4dd0-941a-1512bc438278/dev'
/dev/loop7         0      0         0  0 /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-82051086-eb98-4dd0-941a-1512bc438278/dev/c34639f6-0a8f-458f-bf8e-24a284788187                                        0

# findmnt /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-82051086-eb98-4dd0-941a-1512bc438278/dev/c34639f6-0a8f-458f-bf8e-24a284788187
TARGET                                                                                                                                     SOURCE          FSTYPE   OPTIONS
/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-82051086-eb98-4dd0-941a-1512bc438278/dev/c34639f6-0a8f-458f-bf8e-24a284788187 devtmpfs[/rbd5] devtmpfs rw,seclabel,size=16460544

# lsblk | grep rbd5
rbd5   251:80   0    1G  0 disk 

# mount | grep /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-82051086-eb98-4dd0-941a-1512bc438278/dev/c34639f6-0a8f-458f-bf8e-24a284788187
devtmpfs on /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-82051086-eb98-4dd0-941a-1512bc438278/dev/c34639f6-0a8f-458f-bf8e-24a284788187 type devtmpfs (rw,seclabel,size=16460544k,nr_inodes=4115136,mode=755)
```

</details>

Comment (tedyu) [reply pkg/volume/csi/csi_block.go]: I am curious about the FailedMapVolume event shown above.
Did you find out the cause of it ?

Thanks

Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: Thank you for pointing it out.

I've found that this is due to the difference of losetup command's output depending on the arguments. I've fixed it in the latest commit. PTAL

(In the previous code, `AttachFileDevice` failed because `makeLoopDevice` failed to find the device just created.)

**Comment by mkimuram** [comment]
> Consider logging the err before it is overwritten (on next line).

Added a log for it. (Actually, this is a normal path, so I out dented this code to make it clearer.)

File: pkg/volume/util/volumepathhandler/volume_path_handler_linux.go [hunk 21]
```diff
@@ -93,14 +125,35 @@ func (v VolumePathHandler) RemoveLoopDevice(device string) error {
 	return nil
 }
 
-func parseLosetupOutputForDevice(output []byte) (string, error) {
+func parseLosetupOutputForDevice(output []byte, path string, exactMatch bool) (string, error) {
```
Comment (wongma7) [inline pkg/volume/util/volumepathhandler/volume_path_handler_linux.go]: I wouldn't mind 2 functions. Maybe parseLosetupAssociatedOutput... (-j) and parseLosetupFileOutput... (-f)

File: pkg/volume/csi/csi_block.go [hunk 22]
```diff
@@ -59,17 +58,15 @@ func (m *csiBlockMapper) GetGlobalMapPath(spec *volume.Spec) (string, error) {
 }
```
Comment (wongma7) [inline pkg/volume/csi/csi_block.go]: globalMapPath should be based on volumeID too, not pv name.

File: pkg/volume/util/volumepathhandler/volume_path_handler_linux.go (hunk 21 above)
Comment (mkimuram) [reply pkg/volume/util/volumepathhandler/volume_path_handler_linux.go]: Thank you for suggestion.

I was thinking about providing a way to call `DetachFileDevice` that can release descriptor lock regardless of how its backend path looks like (For example, to be used before calling `TearDownDevice` in `operationGenerator` to ensure no descriptor lock remains). However, we would rather avoid such a situation that needs force releasing locks (To do so, we might need to add a check if all descriptor lock is released before calling `UnmapDevice` so that there will be no descriptor lock).  So, let's change `DetachFileDevice` to release the path that exact matches, then we will no longer need the `exactMatch` flag, which is much simpler.

Also, I found that we might need to add to `MapPodDevice` and `UnmapPodDevice` implementations to all in-tree plugins that support block volume so that their device paths to be per pod (I'm thinking about making all in-tree plugins also bind mount their actual devices to per pod paths in `MapPodDevice`). Without them, descriptor lock won't work well for in-tree plugins for multi attaching the same volume case.

File: pkg/volume/csi/csi_block.go (hunk 22 above)
Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: @wongma7 

I tried to fix both `getVolumeDevicePluginDir` and `getVolumeDeviceDataDir` to be based on `volumeID`. However, in `NewBlockVolumeUnmapper`, `volumeID` is gotten by calling `loadVolumeData` with specifying `unmapper.specName`, or volName. So, at least, `getVolumeDeviceDataDir` won't be able to be based on `volumeID`.

Should we make only `getVolumeDevicePluginDir` based on `volumeID`, or keep the paths as they are?
I think that pv name and volumeID is 1:1, so this change won't be a mandatory. Then, we would be easier to debug the volume if we keep device and volume data under the same directory.

WDYT?

Comment (wongma7) [reply pkg/volume/csi/csi_block.go]: Why is pv name and volumeID 1:1? Can't PV name be anything? I assume that whoever wrote this code had a good reason to think pvname == volumeID but I am not so sure. I thought volumeID is supposed to be 1:1 with volumeHandle, not PV name?

Comment (wongma7) [reply pkg/volume/csi/csi_block.go]: It seems like variables are poorly named. "specVolID" is PV name. https://github.com/kubernetes/kubernetes/blob/39724859b524e345881eb8ef458f0d5a2f25bd9a/pkg/volume/csi/csi_mounter.go#L45 . This is not the same thing as `volume_id` in the CSI spec, that is volumeHandle?!

Comment (wongma7) [reply pkg/volume/csi/csi_block.go]: The issue I see is it's possible (but unlikely) for the same volume_id to be used by two different PVs, in which case there will be two globalMapPaths for the same `volume_id` meaning NodeStage may be called early.

I think you can keep the paths as they are to make this PR simpler, and you can leave the sorting out of paths as a follow-up for me...

File: pkg/volume/util/volumepathhandler/volume_path_handler_linux.go (hunk 21 above)
Comment (wongma7) [reply pkg/volume/util/volumepathhandler/volume_path_handler_linux.go]: Do we need the file descriptor lock at all if we are already bind mounting the path /dev/asdf to globalMapPath? It is getting complicated again with the in-tree vs csi case :(

Comment (mkimuram) [reply pkg/volume/util/volumepathhandler/volume_path_handler_linux.go]: The last commit will make in-tree driver also make use of per pod descriptor lock.
As you indicate, this is to just make descriptor lock to be per pod (ref count is already per pod), so if we remove descriptor lock logic, we can remove most of these codes.  

(I haven't tested enough, but just bind mounting device doesn't seem to prevent device from being detached, as loop back device do.)

@msau42 

Do you think that we should remove descriptor lock for simplicity? Or any good ideas to improve?

File: pkg/volume/csi/csi_block.go (hunk 22 above)
Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: @wongma7 

It seems that we have been using [`spec.Name()`](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/plugins.go#L472) as an ID for volume in [GetPodDeviceMapPath](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/gcepd/gce_pd_block.go#L178) in in-tree plugins. So, we should be able to use `m.specName` as CSI plugin's ID for volume.

The value of `m.specName` is like `pvc-82051086-eb98-4dd0-941a-1512bc438278`, so we won't need to sanitize it by calling `utilstrings.EscapeQualifiedName`.
Also, we should change the comment from `{pvname}` to `{specName}` to avoid confusion.

If you agree. I will change as so.

Comment (wongma7) [reply pkg/volume/csi/csi_block.go]: I agree 👍

Comment (wongma7) [reply pkg/volume/csi/csi_block.go]: While I am not enough of a linux pro to understand why it works, I tried the fd lock thing today and it works as described by the comment before AttachFileDevice. I will need to check if it still works for the new bind mounted case...

1. Start some nonsense container that periodically writes to the device
docker run --name test --device /dev/nvme2n3 nginx bash -c 'i=0; while true; do echo $i; ((i++)); echo $i > ./hello.txt; dd if=./hello.txt of=/dev/nvme2n3 bs=64 count=1; sleep 5; done'; docker rm test
2. Detach the device, then it will get:
dd: failed to open '/dev/nvme2n3': No such device or address
3. Attach a different device, it will resume writing to it. This is the problem the comment for the lock described.

If you setup a loop device to keep the fd open:

1. docker run --name test --device /dev/nvme2n3 nginx bash -c 'i=0; while true; do echo $i; ((i++)); echo $i > ./hello.txt; dd if=./hello.txt of=/dev/nvme2n3 bs=64 count=1; sleep 5; done'; docker rm test
2. sudo losetup -f --show /dev/nvme2n3
3. Detach the device, then it will get:
dd: failed to open '/dev/nvme2n3': No such device or address
4. Attach a different device, it will continue to get the above error.

**Comment by mkimuram** [comment]
@wongma7 

I've fixed reconstruction logic and now all tests pass. PTAL
I will squash the commit once, after you checked the changes.

We might need to further discuss:
- Whether we need descriptor lock at all (I hope that current implementation is still simple enough, though),
- Whether we should (and could) also make podDeviceMapPath a bind mount, instead of symlink
- Further refactoring, like renaming variables, paths and methods, in this PR.

File: pkg/volume/util/util.go [hunk 23]
```diff
@@ -500,28 +500,85 @@ func MakeAbsolutePath(goos, path string) string {
...
+
+	// Ensure that all file descriptor lock for the path is released.
+	lockPath, err := blkUtil.GetLoopDevice(filepath.Join(globalUnmapPath, string(podUID)))
+	if err != nil {
+		if err.Error() != volumepathhandler.ErrDeviceNotFound {
+			return fmt.Errorf("blkUtil.GetLoopDevice failed. globalUnmapPath:%s, podUID: %s: %v",
+				globalUnmapPath, string(podUID), err)
+		}
+	} else if len(lockPath) != 0 {
+		return fmt.Errorf("Descriptor lock for globalUnmapPath:%s, podUID: %s is still taken. Wait for another retry to release it",
```
Comment (wongma7) [inline pkg/volume/util/util.go]: How could this be possible if we just did DetachFileDevice in the lines above? What will be different in the next retry that it may succeed?

File: pkg/volume/csi/csi_block.go [hunk 24]
```diff
@@ -252,22 +247,66 @@ func (m *csiBlockMapper) SetUpDevice() (string, error) {
...
 	// Call NodeStageVolume
-	stagingPath, err := m.stageVolumeForBlock(ctx, csiClient, accessMode, csiSource, attachment)
+	_, err = m.stageVolumeForBlock(ctx, csiClient, accessMode, csiSource, attachment)
 	if err != nil {
 		return "", err
 	}
 
-	// Call NodePublishVolume
-	publishPath, err := m.publishVolumeForBlock(ctx, csiClient, accessMode, csiSource, attachment, stagingPath)
+	return m.getPublishPath(), nil
```
Comment (wongma7) [inline pkg/volume/csi/csi_block.go]: This is a little bit confusing. We NodeStage the volume to staging path but return publish path, which is currently empty, with the expectation that MapPodDevice will later NodePublish the volume there.

Comment (wongma7) [reply pkg/volume/csi/csi_block.go]: TBH I think it's fine, I don't want to refactor this again, but would appreciate some comments for future readers.

File: pkg/volume/csi/csi_block_test.go [hunk 25]
```diff
@@ -306,56 +330,41 @@ func TestBlockMapperMapDevice(t *testing.T) {
...
 	if err != nil {
-		t.Fatalf("mapper failed to create dummy file in devicePath: %v", err)
+		t.Fatalf("mapper failed to create dummy file in publishPath: %v", err)
 	}
 	if err := fd.Close(); err != nil {
-		t.Fatalf("mapper failed to close dummy file in devicePath: %v", err)
+		t.Fatalf("mapper failed to close dummy file in publishPath: %v", err)
 	}
 
 	// Map device to global and pod device map path
```
Comment (wongma7) [inline pkg/volume/csi/csi_block_test.go]: this test comment no longer accurate

**Comment by wongma7** [comment]
>  Whether we need descriptor lock at all (I hope that current implementation is still simple enough, though),

Yes, let's keep it. It works as intended from my testing. And it still works even when you create the lock on a bind mount of the original file instead of the original file itself e.g. /dev/nvme2n1. I.e. if I detach and re-attach a device it won't go to /dev/nvme2n1. If I DON'T create the lock, it does replace /dev/nvme2n1.

> Whether we should (and could) also make podDeviceMapPath a bind mount, instead of symlink

I recall some debates about using one or the other but don't know the details. So I am fine with keeping it as-is. Note we did change globalMapPath from symlink to bind mount.

> Further refactoring, like renaming variables, paths and methods, in this PR.
I think we are OK on this front. Left some comments. Overall, the code is much less confusing than before!

**Comment by wongma7** [comment]
/lgtm

Will let you do some squashing as you see fit.

I think we've achieved the goals from https://github.com/kubernetes/kubernetes/issues/73773#issuecomment-462895942

> Let's move the publish call back to MapDevice so that it is called per pod and not per volume. This is to be consistent with how NodePublish/Stage calls work for filesystem volumes. This may also require adding UnmapDevice to the BlockVolume interface

Done. Now Stage is in SetUpDevice and Publish is in MapPodDevice.

> We may need to clarify in the CSI spec the semantics around multi access on a single node.

We may still want to do this. But it doesn't block this PR. With per-pod publish/staging paths, it's up to the plugin to decide if it can handle "MULTI_NODE*" or not.

> We are unable to simplify the number of paths for now. globalMapPath and podPath are needed for Kubernetes to refcnt the number of pods using the device to gate the unstage call. The path returned by nodeStageVolume is not actually a device, it's a directory where a plugin keeps information about the device.
> It's a little odd that the Kubernetes refcnting mechanism is exposed into the plugin. Maybe that can be cleaned up later.

Done, we've pulled globalMapPath and podDeviceMapPath from outside the plugin code. We are effectively reversing https://github.com/kubernetes/kubernetes/pull/64094/files. CSI has staging and publish paths, kubernetes has globalMapPath and podDeviceMapPath. Responsibilities are clear. CSI plugin puts things in staging and publish paths. kubernetes puts things in globalMapPath (add/remove files as pods are added/removed) and podDeviceMapPath (expose CSI publish paths on it).

File: pkg/volume/util/util.go (hunk 23 above)
Comment (mkimuram) [reply pkg/volume/util/util.go]: I think that `MapBlockVolume` could be called more than once, so there would be a case that multiple descriptor locks are taken to the same `lockPath`, just for one volume-pod mapping. (I haven't actually hit this case, though.)

If above assumption is true, we might also need to return error if bindmount still exist after `UnmapDevice` for `globalUnmapPath` below this code, because bindmount could be created multiple times (On the other hand, symlink can't be created multiple times, so we won't need the same check for `podDeviceUnmapPath`).

File: pkg/volume/csi/csi_block.go (hunk 24 above)
Comment (mkimuram) [reply pkg/volume/csi/csi_block.go]: Thank you for pointing it out. I will add comments, here.

**Review by mkimuram — COMMENTED** [review]
@wongma7 

Thank you for your review and testing!
I will squash the commit and add some comments to the codes.

Also, please give me feedback on `UnmapBlockVolume` logic.

File: pkg/volume/csi/csi_block.go [hunk 26]
```diff
@@ -31,7 +31,6 @@ import (
 	"k8s.io/apimachinery/pkg/types"
 	"k8s.io/client-go/kubernetes"
 	"k8s.io/kubernetes/pkg/volume"
-	ioutil "k8s.io/kubernetes/pkg/volume/util"
 	utilstrings "k8s.io/utils/strings"
 )
```
Comment (msau42) [inline pkg/volume/csi/csi_block.go]: Can you add some comments at the top here that summarize the new high level sequence?

**Review by msau42 — COMMENTED** [review]
Thank you for working on these changes!

I want to make sure we test a real csi driver with these changes (not just hostpath). @davidz627 can you update the PD csi driver specs and enable block tests so we can test it with this change?

/assign @saad-ali

File: pkg/volume/util/util.go (hunk 23 above)
Comment (wongma7) [reply pkg/volume/util/util.go]: If the path is the same, i.e. a loop device already exists whose backing file is equal to the path, AttachFileDevice should no-op: https://github.com/kubernetes/kubernetes/blob/a3ccea9d8743f2ff82e41b6c2af6dc2c41dc7b10/pkg/volume/util/volumepathhandler/volume_path_handler_linux.go#L34. So we don't need to worry about that case.

Similarly, if the path is the same and you try to bind mount twice, wouldn't it error in MapBlockVolume?
mount --bind a b # 1st time
mount --bind a b # 2nd time, error?

**Comment by davidz627** [comment]
> @davidz627 can you update the PD csi driver specs and enable block tests so we can test it with this change?

https://github.com/kubernetes/kubernetes/pull/84312

File: pkg/volume/util/util.go (hunk 23 above)
Comment (mkimuram) [reply pkg/volume/util/util.go]: Thank you for your comment.

For bind mount, I've added a code to check if the path has already been bind mounted in `mapBindMountDevice`. So, it would be as safe as loop back device. 
However, IMHO, we don't take a lock between check and creation, so there could be a very small chance for creation logic to be called multiple times. 

And in such a situation, both `losetup` and `mount --bind` allow creating them every time, as seen below:

<details>

```
[losetup]
# losetup -f --show /dev/loop0 
/dev/loop1
# losetup -f --show /dev/loop0 
/dev/loop2
# losetup 
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE
/dev/loop0         0      0         0  0 /tmp/file1
/dev/loop1         0      0         0  0 /dev/loop0
/dev/loop2         0      0         0  0 /dev/loop0

[bind mount]
# touch /tmp/bindmount
# mount --bind /dev/loop0 /tmp/bindmount 
# mount --bind /dev/loop0 /tmp/bindmount 
# mount | grep /tmp/bindmount
devtmpfs on /tmp/bindmount type devtmpfs (rw,nosuid,seclabel,size=485080k,nr_inodes=121270,mode=755)
devtmpfs on /tmp/bindmount type devtmpfs (rw,nosuid,seclabel,size=485080k,nr_inodes=121270,mode=755)
```

</details>

Comment (wongma7) [reply pkg/volume/util/util.go]: Thanks for testing. operation_generator/executor should insulate us from multiple creations  happening concurrently but it doesn't hurt to have these checks.

Comment (mkimuram) [reply pkg/volume/util/util.go]: Good to hear that operation_generator/executor avoid such a concurrent call. Then, I agree to delete this unnecessary code.

**Comment by mkimuram** [comment]
@wongma7

I've added comments, fixed unit tests, and remove the redundant codes. PTAL

For unit test fix, let me explain a bit:
  - `MapPodDevice` no longer requires publishPath to be created before test, because it doesn't create symlink for the path,
  - Tests for `TearDownDevice` and `UnmapPodDevice` seemed to have tested without stagingPath and publishPath, so no NodeUnstage/NodeUnpblish wasn't called. Tests passed because initial state, or lack of the key, is regarded as called. (To test them properly, we should add the key before calling these methods and confirm that key doesn't exist after these methods are called).

**Comment by mkimuram** [comment]
Rebased with the latest master to reflect #84312 change. Thanks @davidz627 for updating CSI GCE pd driver.

**Comment by mkimuram** [comment]
@wongma7 @msau42 @saad-ali @davidz627 

All tests pass now including tests for newly added csi gce pd. PTAL

**Comment by bswartz** [comment]
I have tested this with my CSI driver and didn't detect any breakages.

**Comment by mkimuram** [comment]
@bswarz 

Thank you for your testing and reporting the result!

File: pkg/volume/csi/csi_block.go [hunk 27]
```diff
@@ -14,6 +14,55 @@ See the License for the specific language governing permissions and
...
+/*
+This file defines block volume related methods for CSI driver.
+CSI driver is responsible for staging/publishing volumes to their staging/publish paths.
+Mapping and unmapping of a device in a publish path to its global map path and its
+pod device map path are done by operation_executor through MapBlockVolume/UnmapBlockVolume
+(MapBlockVolume and UnmapBlockVolume take care for lock, symlink, and bind mount).
+
+Summary of block volume related CSI driver's methods are as follows:
+ - GetGlobalMapPath returns a global map path,
+ - GetPodDeviceMapPath returns a pod device map path and filename,
```
Comment (davidz627) [inline pkg/volume/csi/csi_block.go]: can you clarify what a `global map path` and `pod device map path and filename` are, or what they are used for

File: pkg/volume/csi/csi_block.go [hunk 28]
```diff
@@ -14,6 +14,55 @@ See the License for the specific language governing permissions and
...
+ - UnmapPodDevice calls CSI's NodeUnpublishVolume and unpublish a volume from its publish path,
+ - TearDownDevice calls CSI's NodeUnstageVolume and unstage a volume from its staging path.
+
+These methods are called by below sequences:
+ operation_executor    pkg/volume/csi     pkg/volume/util          ASW                 CSI (SP)
+ ------------------ -------------------- ----------------- ---------------------- ------------------
+   MountVolume
+          +--------> GetGlobalMapPath
+          +--------> SetupDevice ------------------------------------------------> NodeStageVolume
+          +-----------------------------------------------> MarkDeviceAsMounted
```
Comment (davidz627) [inline pkg/volume/csi/csi_block.go]: do we need this many dashes? It makes it hard to read on smaller screens

Comment (davidz627) [reply pkg/volume/csi/csi_block.go]: in general for this and the below "After successful MountVolume..." section I think it's better to not rely on formatting based on spacing as it can be difficult to read and may differ depending on dev configuration. Looks like this could probably just be simplified into a nested bulleted list type structure with the occasional arrow

File: pkg/volume/csi/csi_block.go [hunk 29]
```diff
@@ -51,34 +99,31 @@ type csiBlockMapper struct {
...
 func (m *csiBlockMapper) GetGlobalMapPath(spec *volume.Spec) (string, error) {
-	dir := getVolumeDevicePluginDir(spec.Name(), m.plugin.host)
+	dir := getVolumeDevicePluginDir(m.specName, m.plugin.host)
 	klog.V(4).Infof(log("blockMapper.GetGlobalMapPath = %s", dir))
 	return dir, nil
 }
 
 // getStagingPath returns a staging path for a directory (on the node) that should be used on NodeStageVolume/NodeUnstageVolume
-// Example: plugins/kubernetes.io/csi/volumeDevices/staging/{pvname}
+// Example: plugins/kubernetes.io/csi/volumeDevices/staging/{specName}
```
Comment (davidz627) [inline pkg/volume/csi/csi_block.go]: what is `specName`

File: pkg/volume/csi/csi_block.go [hunk 30]
```diff
@@ -252,22 +296,71 @@ func (m *csiBlockMapper) SetUpDevice() (string, error) {
...
+	_, err = m.stageVolumeForBlock(ctx, csiClient, accessMode, csiSource, attachment)
 	if err != nil {
 		return "", err
 	}
 
-	// Call NodePublishVolume
-	publishPath, err := m.publishVolumeForBlock(ctx, csiClient, accessMode, csiSource, attachment, stagingPath)
+	// In SetUpDevice, NodeStageVolume is called, but NodePublishVolume isn't,
+	// therefore, there will be no device available in publishPath, yet.
+	// However, GenerateMapVolumeFunc expects SetUpDevice to return the path that the device
```
Comment (davidz627) [inline pkg/volume/csi/csi_block.go]: this comment feels off - if the interface is expecting something that we can't provide, that feels a lot like we're putting logic in the wrong place.

File: pkg/volume/csi/csi_block.go [hunk 31]
```diff
@@ -252,22 +296,71 @@ func (m *csiBlockMapper) SetUpDevice() (string, error) {
...
+	// will appear (This is needed for some existing in-tree plugins).
+	// So, publishPath is returned here, even though it is not yet available.
+	return m.getPublishPath(), nil
+}
+
+func (m *csiBlockMapper) MapPodDevice() error {
+	// Get csiSource from spec
+	if m.spec == nil {
+		klog.Error(log("blockMapper.MapPodDevice spec is nil"))
```
Comment (davidz627) [inline pkg/volume/csi/csi_block.go]: comment applies throughout all code - please don't `klog` then return an `error` especially with different contexts. We should *only* return an error with all relevant context and let the top level callers log errors

File: pkg/volume/fc/fc.go [hunk 32]
```diff
@@ -416,8 +416,8 @@ func (b *fcDiskMapper) SetUpDevice() (string, error) {
 	return "", nil
 }
 
-func (b *fcDiskMapper) MapDevice(devicePath, globalMapPath, volumeMapPath, volumeMapName string, podUID types.UID) error {
-	return util.MapBlockVolume(devicePath, globalMapPath, volumeMapPath, volumeMapName, podUID)
+func (b *fcDiskMapper) MapPodDevice() error {
+	return nil
```
Comment (davidz627) [inline pkg/volume/fc/fc.go]: looks like most (many?) plugins have `nil` implementations for this. Should this be a separate interface that these plugins just don't implement? Something like `BlockVolumeMapper`

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 33]
```diff
@@ -1079,26 +1087,13 @@ func (og *operationGenerator) GenerateMapVolumeFunc(
...
-
-		// Take filedescriptor lock to keep a block device opened. Otherwise, there is a case
-		// that the block device is silently removed and attached another device with same name.
-		// Container runtime can't handler this problem. To avoid unexpected condition fd lock
-		// for the block device is required.
-		_, err = og.blkUtil.AttachFileDevice(devicePath)
+		resolvedDevicePath, err := hu.EvalHostSymlinks(devicePath)
 		if err != nil {
-			return volumeToMount.GenerateError("MapVolume.AttachFileDevice failed", err)
+			// For CSI plugin, device won't be available at devicePath until MapPodDevice is called,
```
Comment (davidz627) [inline pkg/volume/util/operationexecutor/operation_generator.go]: this may ignore real errors - could you instead do a check like `if !csi then evalhostsymlinks else do nothing`?

File: pkg/volume/util/volumepathhandler/volume_path_handler.go [hunk 34]
```diff
@@ -98,25 +103,105 @@ func (v VolumePathHandler) MapDevice(devicePath string, mapPath string, linkName
...
+	if isMountExist, checkErr := v.IsBindMountExist(linkPath); checkErr != nil {
+		return checkErr
+	} else if !isMountExist {
+		klog.Warningf("Warning: Unmap skipped because bind mount does not exist on the path: %v", linkPath)
+		// TODO: consider deleting empty file if it exists
+		return nil
+	}
+
+	// Unmount file
+	mounter := &mount.SafeFormatAndMount{Interface: mount.New(""), Exec: mount.NewOSExec()}
```
Comment (davidz627) [inline pkg/volume/util/volumepathhandler/volume_path_handler.go]: why are we making a new mounter here, seems fishy. Shouldn't we be using a mounter passed in from elsewhere that may have specific interface or exec? How will you unit test this

File: pkg/volume/util/volumepathhandler/volume_path_handler.go [hunk 35]
```diff
@@ -163,70 +247,42 @@ func (v VolumePathHandler) IsSymlinkExist(mapPath string) (bool, error) {
...
-// GetDeviceSymlinkRefs searches symbolic links under global map path
-func (v VolumePathHandler) GetDeviceSymlinkRefs(devPath string, mapPath string) ([]string, error) {
+// IsBindMountExist returns true if specified file exists and the type is device.
+// If file doesn't exist, or file exists but not device, return false with no error.
+// On other cases, return false with error from Lstat().
+func (v VolumePathHandler) IsBindMountExist(mapPath string) (bool, error) {
+	fi, err := os.Lstat(mapPath)
+	if err == nil {
+		// If file exits and it's device, return true and no error
+		if fi.Mode()&os.ModeDevice == os.ModeDevice {
```
Comment (davidz627) [inline pkg/volume/util/volumepathhandler/volume_path_handler.go]: is there no helper function to do this?

File: pkg/volume/util/volumepathhandler/volume_path_handler.go [hunk 36]
```diff
@@ -163,70 +247,42 @@ func (v VolumePathHandler) IsSymlinkExist(mapPath string) (bool, error) {
...
 }
 
-// GetDeviceSymlinkRefs searches symbolic links under global map path
-func (v VolumePathHandler) GetDeviceSymlinkRefs(devPath string, mapPath string) ([]string, error) {
+// IsBindMountExist returns true if specified file exists and the type is device.
+// If file doesn't exist, or file exists but not device, return false with no error.
+// On other cases, return false with error from Lstat().
+func (v VolumePathHandler) IsBindMountExist(mapPath string) (bool, error) {
+	fi, err := os.Lstat(mapPath)
+	if err == nil {
```
Comment (davidz627) [inline pkg/volume/util/volumepathhandler/volume_path_handler.go]: can we flip this logic for ease of reading?

```
if err != nil{
  error stuff
}
do other stuff
```

File: pkg/volume/util/volumepathhandler/volume_path_handler_linux.go [hunk 37]
```diff
@@ -47,6 +50,27 @@ func (v VolumePathHandler) AttachFileDevice(path string) (string, error) {
 	return blockDevicePath, nil
 }
 
+// DetachFileDevice takes a path to the attached block device and
+// detach it from block device.
+func (v VolumePathHandler) DetachFileDevice(path string) error {
+	loopPath, err := v.GetLoopDevice(path)
+	if err != nil {
+		if err.Error() == ErrDeviceNotFound {
+			klog.Warningf("DetachFileDevice: Couldn't find loopback device which takes file descriptor lock. device path: %q", path)
```
Comment (davidz627) [inline pkg/volume/util/volumepathhandler/volume_path_handler_linux.go]: logic in this func could be cleaned up a bit. For example I think this logs a warning and goes to the end of the function retuning `nil`. Is it supposed to just do nothing? It's unclear from the warning that this is ok (maybe it should say - "assuming file device already cleaned up" or osmething)

File: pkg/volume/util/volumepathhandler/volume_path_handler_linux.go [hunk 38]
```diff
@@ -47,6 +50,27 @@ func (v VolumePathHandler) AttachFileDevice(path string) (string, error) {
...
+		} else {
+			return err
+		}
+	} else {
+		if len(loopPath) != 0 {
+			err = removeLoopDevice(loopPath)
+			if err != nil {
+				return err
```
Comment (davidz627) [inline pkg/volume/util/volumepathhandler/volume_path_handler_linux.go]: add context for `err` when available

File: pkg/volume/util/volumepathhandler/volume_path_handler_linux.go [hunk 39]
```diff
@@ -93,16 +124,97 @@ func (v VolumePathHandler) RemoveLoopDevice(device string) error {
...
+func parseLosetupOutputForDevice(output []byte, path string) (string, error) {
 	if len(output) == 0 {
 		return "", errors.New(ErrDeviceNotFound)
 	}
 
-	// losetup returns device in the format:
-	// /dev/loop1: [0073]:148662 (/dev/sda)
-	device := strings.TrimSpace(strings.SplitN(string(output), ":", 2)[0])
+	// losetup -j {path} returns device in the format:
+	// /dev/loop1: [0073]:148662 (/dev/{globalMapPath}/{pod1-UUID})
```
Comment (davidz627) [inline pkg/volume/util/volumepathhandler/volume_path_handler_linux.go]: what is `globalMapPath`, isn't it different per volume/plugin? But in this case it's not even a parameter to func so its not clear what this is referring to

File: pkg/volume/util/volumepathhandler/volume_path_handler_linux.go [hunk 40]
```diff
@@ -93,16 +124,97 @@ func (v VolumePathHandler) RemoveLoopDevice(device string) error {
...
+			matched = scanner.Text()
+			break
+		}
+	}
+	if len(matched) == 0 {
+		return "", errors.New(ErrDeviceNotFound)
+	}
+	s = matched
+
+	device := strings.TrimSpace(strings.SplitN(s, ":", 2)[0])
```
Comment (davidz627) [inline pkg/volume/util/volumepathhandler/volume_path_handler_linux.go]: lot of magic numbers in this function. why are we splitting specifically with a max of 2 substrings but only taking the 0th? What is the 0th?

File: pkg/volume/util/volumepathhandler/volume_path_handler_linux.go [hunk 41]
```diff
@@ -93,16 +124,97 @@ func (v VolumePathHandler) RemoveLoopDevice(device string) error {
...
 	if len(device) == 0 {
 		return "", errors.New(ErrDeviceNotFound)
 	}
 	return device, nil
 }
+
+// FindGlobalMapPathUUIDFromPod finds {pod uuid} bind mount under globalMapPath
+// corresponding to map path symlink, and then return global map path with pod uuid.
+// ex. mapPath symlink: pods/{podUid}}/{DefaultKubeletVolumeDevicesDirName}/{escapeQualifiedPluginName}/{volumeName} -> /dev/sdX
+//     globalMapPath/{pod uuid} bind mount: plugins/kubernetes.io/{PluginName}/{DefaultKubeletVolumeDevicesDirName}/{volumePluginDependentPath}/{pod uuid} -> /dev/sdX
```
Comment (davidz627) [inline pkg/volume/util/volumepathhandler/volume_path_handler_linux.go]: these `{}` variables for example `{DefaultKubeletVolumeDevicesDirName}` are not discoverable in this scope - what are they referring to?

File: pkg/volume/util/volumepathhandler/volume_path_handler_linux.go [hunk 42]
```diff
@@ -93,16 +124,97 @@ func (v VolumePathHandler) RemoveLoopDevice(device string) error {
...
+		return false, err
+	}
+	klog.V(5).Infof("CompareBindMountAndSymlinks: devNumGlobal %s, devNumPod %s", devNumGlobal, devNumPod)
+	if devNumGlobal == devNumPod {
+		return true, nil
+	}
+	return false, nil
+}
+
+func getDeviceMajorMinor(path string) (string, error) {
```
Comment (davidz627) [inline pkg/volume/util/volumepathhandler/volume_path_handler_linux.go]: sidenote: I thought this PR was just splitting up `staging/publish` and `unstage/unpublish` for block - why am I seeing so much new functionality all over the place? It's not clear to mewhat this stuff is doing

**Review by davidz627 — COMMENTED** [review]
just a quick surface level 1st pass review. Overall comment is that this probably could benefit from being seperated into some smaller PRs. It's quite bulky right now and sometimes its not clear why certain changes are being made

**Comment by mkimuram** [comment]
@davidz627 

Thank you for your comment. I will re-organize the commits and explain the intention per commit.

**Comment by mkimuram** [comment]
@davidz627 

I've created #84625 to separate the commits and explain the intention of the code to each commit comment. This is still work in progress, because no logic change from this PR's version, so I will continue working on to change the code per your comments.

I hope that above PR at least answer to your two comments below:

> Overall comment is that this probably could benefit from being seperated into some smaller PRs.

> why am I seeing so much new functionality all over the place? It's not clear to mewhat this stuff is doing


I would appreciate it if you could suggest me how we separate it to small PRs. (Should it be per commit in #84625?)

**Comment by davidz627** [comment]
I don't really understand 100% what's happening enough to have suggestions on how to split this up into smaller PRs. It may be that the answer is it can't and some commit separation is helpful enough for review :) I'm just concerned since theres a lot of code moving around and it's not clear which parts are refactoring and which are net-new. The PR title says logic is being "seperated" but I see some completely new functions with significant logic. It might be worth seperating out the refactor into one PR where things just move around, and another PR for each of the issues that need to be fixed

**Comment by mkimuram** [comment]
@davidz627 

Thank you for your comment. 

I think that the last three commits in #84625 is actually separating the logic as described in the PR tittle, and other commits are prerequisite for it. So, let's split them into two, and split them more if needed.

**Comment by mkimuram** [comment]
Rebased again on top of #84747 after #84660 is merged. Waiting for #84747 to be merged.

@saad-ali 

Can this also be targeted to 1.17?  (Although, @jsafrane 's time zone is already midnight.) 

The last discussion for this PR is https://github.com/kubernetes/kubernetes/pull/84625#discussion_r345346651 . I'm pushing the latest version here, so that we can compare this PR and #84625 . I believe that this PR should be ready to be merged, if others agree.)

Any comments? @davidz627 @msau42 @jingxu97

**Comment by mkimuram** [comment]
Now #84747 is merged. I will rebase this PR with the latest master.

**Comment by mkimuram** [comment]
@saad-ali 

Rebased. Now it should be ready to be merged. PTAL

**Review by saad-ali — APPROVED** [review]
/lgtm
/approve
/milestone v1.17
