### PR TITLE
GCE: Read networkProjectID param

### LINKED ISSUE #48515: GCE: Project Id used for firewall mgmt instead of network project Id
In the GCE Cloudprovider package, firewall should be created in the project which contains the network.  Currently, the compute project Id is used. This is a broken feature of K8s 1.7.0.

### PR DESCRIPTION
**Pull request by nicksardo**
Fixes #48515 

/assign bowei

The first commit is the original PR cherrypicked. The master's kubelet isn't provided a cloud config path, so the project is retrieved via instance metadata. In the GKE case, this project cannot be retrieved by the master and caused an error.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

File: pkg/cloudprovider/providers/gce/gce.go [hunk 1]
```diff
@@ -479,6 +464,33 @@ func CreateGCECloud(config *CloudConfig) (*GCECloud, error) {
 	return gce, nil
 }
 
+func tryConvertToProjectNames(configProject, configNetworkProject string, service *compute.Service) (projID, netProjID string) {
+	projID = configProject
+	if isProjectNumber(projID) {
+		projName, err := getProjectID(service, projID)
+		if err != nil {
+			glog.Warningf("failed to retrieve project %v while trying to retrieve its name. err %v", projID, err)
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/gce.go]: [minor] log messages should be capitalized...

Failed

File: pkg/cloudprovider/providers/gce/gce.go [hunk 2]
```diff
@@ -564,6 +576,16 @@ func (gce *GCECloud) HasClusterID() bool {
...
 }
 
+// Project IDs cannot have a digit for the first characeter. If the id contains a digit,
+// then it must be a project number.
+func isProjectNumber(idOrNumber string) bool {
+	if len(idOrNumber) == 0 {
+		return false
+	}
+
+	return idOrNumber[0] >= '0' && idOrNumber[0] <= '9'
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/gce.go]: Shouldn't this actually parse to see it's a number? Why do we want to make the assumption it is in a particular format?

Comment (nicksardo) [reply pkg/cloudprovider/providers/gce/gce.go]: My original code from several months ago tried parsing it, but you suggested to go this route.

Comment (bowei) [reply pkg/cloudprovider/providers/gce/gce.go]: On second look, I was wrong, probably should parse it as a number, unless it's too big?
