### PR TITLE
fix the issue of losing the pending phase after a node restart.

### LINKED ISSUE #126650: Pod status phase misses Pending transition after node reboot
### What happened?

When a kubernetes node is rebooted, all the containers running on the node are terminated and then created & started over again. When the pod has a list of init containers runing, and if the init container takes a little bit time (longer than PLEG period), the pod is supposed to have `status.phase: Pending`, but instead, during the whole operation, `status.phase` is always `Running`.

This new behavior (always has `status.phase: Running`) started when "restartable init container" was [introduced][1]. After node reboots, all the regular init containers are started one by one, so `pendingInitialization` is supposed by larger than 0 (unless the init container is completed pretty fast that PLEG doesn't catch any running init container), and should report `Pending` phase. But the behavior has changed to check further whether there are any other regular containers that have started. In the case of node reboot, all the other regular containers are already terminated, and then considered as "yes, they have started", and then no longer reported as `Pending`.

I think this behavior change is unexpected, as that violates the [definition][2] of "Running":

> // PodRunning means the pod has been bound to a node and all of the containers have been started.
	// At least one container is still running or is in the process of being restarted.

None of the containers have been started, and they are not in the process of being started or restarted as init containers are still running.

[1]: https://github.com/kubernetes/kubernetes/blob/099a88370d017dacf16e67306ebcdec8394fae83/pkg/kubelet/kubelet_pods.go#L1675-L1685
[2]: https://github.com/kubernetes/kubernetes/blob/099a88370d017dacf16e67306ebcdec8394fae83/pkg/apis/core/types.go#L2871

### What did you expect to happen?

I expect that pods with init containers should transition into "Pending" when kubelet observed that its regular init container is still running and none of its main containers are started.

### How can we reproduce it (as minimally and precisely as possible)?

1. Launch a cluster with minikube:

```console
$ minikube start --nodes=2 --kubernetes-version=v1.30.3
```

2. Create the following pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: sleep
spec:
  restartPolicy: Always
  containers:
  - name: sleep
    image: busybox
    command:
    - sleep
    - infinity
  initContainers:
  - name: snap
    image: busybox
    command:
    - sleep
    - "10"
```

3. Log in the node and simulate "reboot"

```console
$ minikube ssh --node <node-which-runs-the-pod-above>
...
# systemctl stop kubelet
# docker stop $(docker ps -aq)
# systemctl start kubelet
```

4. Observe the pod status via:

```console
$ k get pods -w -o jsonpath='{$.status.phase}{"\n"}'
```

On 1.30.3, the output from 4 is `Running` constantly, while in previous kubernetes version (for e,g, v1.23.17), it will show "Pending" while the init container is still Running.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"30", GitVersion:"v1.30.3", GitCommit:"6fc0a69044f1ac4c13841ec4391224a2df241460", GitTreeState:"clean", BuildDate:"2024-07-16T23:48:12Z", GoVersion:"go1.22.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.30) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
None (minikube)
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by zhifei92**
#### What type of PR is this?
/kind bug
/sig node

#### What this PR does / why we need it:
The phase of the Pod should be 'Pending' when its regular init container is still running.
#### Which issue(s) this PR fixes:

Fixes #126650

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug where the pod(with regular init containers)'s phase was not pending when the regular init container had not finished running after a node restart.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kannon92** [comment]
We should really add a e2e test reproducing this behavior.

**Comment by bart0sh** [comment]
@zhifei92 This is a user-visible change. Please, provider a release note for it.

**Comment by zhouhaibing089** [comment]
/cc

Thanks! Regarding tests, I think a unit test in `pkg/kubelet/kubelet_pods_test.go` (there seemed to be a bunch existing `getPhase` tests) should be good enough.

**Comment by zhifei92** [comment]
sorry, I will add tests and release notes this week.

File: pkg/kubelet/kubelet_pods.go [hunk 1]
```diff
@@ -1673,11 +1674,12 @@ func getPhase(pod *v1.Pod, info []v1.ContainerStatus, podIsTerminal bool) v1.Pod
 	}
 
 	switch {
-	case pendingInitialization > 0 &&
+	case pendingRegularInitContainers > 0 ||
 		// This is needed to handle the case where the pod has been initialized but
 		// the restartable init containers are restarting and the pod should not be
 		// placed back into v1.PodPending since the regular containers have run.
-		!kubecontainer.HasAnyRegularContainerStarted(&spec, info):
+		(pendingRestartableInitContainers > 0 &&
```
Comment (matthyx) [inline pkg/kubelet/kubelet_pods.go:1681]: nit: I would move this line content to the case (line 1677) for clarity

**Comment by toVersus** [comment]
I reverted the commit (caf17db7d7ad9daa3398fd0989f086ecfd8daeac) that fixes the issue and ran the Node E2E test on my local machine, but the test passed even without the fix. I think we need to add a Node E2E test that consistently fails without the fix so we can be sure the issue is actually resolved.

```console
$ make test-e2e-node FOCUS="\[Serial\] Pods status phase" SKIP="\[Flaky\]|\[Slow\]"
(...)
Ran 1 of 655 Specs in 14.346 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 654 Skipped


Ginkgo ran 1 suite in 14.496754711s
Test Suite Passed
```

**Comment by toVersus** [comment]
I managed to reproduce the issue in the Node E2E tests. The restartable init container didn't really matter, so I took it out of the Pod spec. The key point was to restart the kubelet while the regular container was running (thanks for the detailed report @zhouhaibing089!).

With these changes, I confirmed that the Node E2E tests fail before the fix and pass after.

```diff
diff --git a/test/e2e_node/pod_status_test.go b/test/e2e_node/pod_status_test.go
index a7aacf4c3f9..31eb397775c 100644
--- a/test/e2e_node/pod_status_test.go
+++ b/test/e2e_node/pod_status_test.go
@@ -40,7 +40,6 @@ var _ = SIGDescribe(framework.WithSerial(), "Pods status phase", func() {

        ginkgo.It("should be pending during the execution of the init container after the node reboot", func(ctx context.Context) {
                init := "init"
-               restartableInit := "restartable-init"
                regular := "regular"

                podLabels := map[string]string{
@@ -59,19 +58,10 @@ var _ = SIGDescribe(framework.WithSerial(), "Pods status phase", func() {
                                                Name:  init,
                                                Image: busyboxImage,
                                                Command: ExecCommand(init, execCommand{
-                                                       Delay:    30,
+                                                       Delay:    10,
                                                        ExitCode: 0,
                                                }),
                                        },
-                                       {
-                                               Name:  restartableInit,
-                                               Image: busyboxImage,
-                                               Command: ExecCommand(restartableInit, execComma
nd{
-                                                       Delay:    300,
-                                                       ExitCode: 0,
-                                               }),
-                                               RestartPolicy: &containerRestartPolicyAlways,
-                                       },
                                },
                                Containers: []v1.Container{
                                        {
@@ -90,11 +80,13 @@ var _ = SIGDescribe(framework.WithSerial(), "Pods status phase", func() {
                client := e2epod.NewPodClient(f)
                pod = client.Create(ctx, pod)

-               ginkgo.By("Waiting for the regular init container to be started")
-               pod, err := waitForPodInitContainerStarted(ctx, f.ClientSet, pod.Namespace, pod
.Name, init, f.Timeouts.PodStart)
+               ginkgo.By("Waiting for the regular container to be started")
+               err := e2epod.WaitForPodContainerStarted(ctx, f.ClientSet, pod.Namespace, pod.N
ame, 0, f.Timeouts.PodStart)
                framework.ExpectNoError(err)
-               if pod.Status.Phase != v1.PodPending {
-                       framework.Failf("pod should be pending during the execution of the init
 container")
+               pod, err = client.Get(context.TODO(), pod.Name, metav1.GetOptions{})
+               framework.ExpectNoError(err)
+               if pod.Status.Phase != v1.PodRunning {
+                       framework.Failf("pod should be running before restarting the kubelet")
                }

                ginkgo.By("Getting the current pod sandbox ID")
```

Without the fix:

```console
$ make test-e2e-node FOCUS="\[Serial\] Pods status phase" SKIP="\[Flaky\]|\[Slow\]"
(...)
Summarizing 1 Failure:
  [FAIL] [sig-node] [Serial] Pods status phase [It] should be pending during the execution of the init container after the node reboot [sig-node, Serial]
  k8s.io/kubernetes/test/e2e_node/pod_status_test.go:124

Ran 1 of 655 Specs in 25.823 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 654 Skipped
```

With the fix:

```console
$ make test-e2e-node FOCUS="\[Serial\] Pods status phase" SKIP="\[Flaky\]|\[Slow\]"
(...)
Ran 1 of 655 Specs in 15.367 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 654 Skipped
```

File: test/e2e_node/pod_status_test.go [hunk 2]
```diff
@@ -0,0 +1,150 @@
...
+		pod, err = waitForPodInitContainerStarted(ctx, f.ClientSet, pod.Namespace, pod.Name, init, f.Timeouts.PodStart)
+		framework.ExpectNoError(err)
+		if pod.Status.Phase != v1.PodPending {
+			framework.Failf("pod should be pending during the execution of the init container after the node reboot")
+		}
+	})
+})
+
+// waitForPodInitContainerStarted waits for the given Pod init container to start, after a successful run of the startupProbe.
+func waitForPodInitContainerStarted(ctx context.Context, c clientset.Interface, namespace, podName, initContainer string, timeout time.Duration) (*v1.Pod, error) {
```
Comment (toVersus) [inline test/e2e_node/pod_status_test.go:137]: I think it's a bit strange that the `waitForPodInitContainerStarted()` function returns the Pod spec, given the name of the function. It might make more sense to add an Init container version of `e2epod.WaitForPodContainerStarted()` and then fetch the Pod spec with `client.Get()` afterward.

Comment (zhifei92) [reply test/e2e_node/pod_status_test.go:137]: Thank you very much for your careful review. There is indeed an issue with waitForPodInitContainerStarted.

Comment (zhifei92) [reply test/e2e_node/pod_status_test.go:137]: The reason the test may not have taken effect could be due to the following code, which should wait for the regular container to be started. In any case, I accept your suggestion, thank you very much.
> 		ginkgo.By("Waiting for the regular init container to be started")
>		pod, err := waitForPodInitContainerStarted(ctx, f.ClientSet, pod.Namespace, pod.Name, init, f.Timeouts.PodStart)

Comment (zhifei92) [reply test/e2e_node/pod_status_test.go]: > I think it's a bit strange that the `waitForPodInitContainerStarted()` function returns the Pod spec, given the name of the function. It might make more sense to add an Init container version of `e2epod.WaitForPodContainerStarted()` and then fetch the Pod spec with `client.Get()` afterward.

donw

File: test/e2e/framework/pod/wait.go [hunk 3]
```diff
@@ -809,6 +809,18 @@ func WaitForPodContainerStarted(ctx context.Context, c clientset.Interface, name
 	})
 }
 
+// WaitForPodInitContainerStarted waits for the given Pod init container to start, after a successful run of the startupProbe.
```
Comment (toVersus) [inline test/e2e/framework/pod/wait.go:812]: nit: Regular init containers can’t run startup probes, but restartable init containers can, so the comment isn’t entirely wrong. However, since the Sidecar containers feature is still in beta and this PR is focused on regular init containers, it might be better to remove the mention of the startup probe.

```suggestion
// WaitForPodInitContainerStarted waits for the given Pod init container to start.
```

**Review by toVersus — APPROVED** [review]
It's fine to wait until others have finished their reviews, but could you switch the order of the commits so that the E2E test addition comes first, followed by the code fix?"

**Comment by zhifei92** [comment]
> It's fine to wait until others have finished their reviews, but could you switch the order of the commits so that the E2E test addition comes first, followed by the code fix?"

Ok, I'll rebase this PR onto the latest state after PR[ #126860](https://github.com/kubernetes/kubernetes/pull/126860) is merged.

File: test/e2e/framework/pod/wait.go (hunk 3 above)
Comment (zhifei92) [reply test/e2e/framework/pod/wait.go:812]: agree

**Comment by toVersus** [comment]
> Ok, I'll rebase this PR onto the latest state after PR #126860 is merged.

If you're planning to cherry-pick this PR to an older Kubernetes version, it might be better not to split the PR. Adding the helper function in the same commit as the Node E2E test could simplify the cherry-pick process.

**Comment by zhifei92** [comment]
> > Ok, I'll rebase this PR onto the latest state after PR #126860 is merged.
> 
> If you're planning to cherry-pick this PR to an older Kubernetes version, it might be better not to split the PR. Adding the helper function in the same commit as the Node E2E test could simplify the cherry-pick process.
> 
> If you'd rather not touch the contents of the E2E framework in this PR, one option could be to temporarily add the helper function to `test/e2e_node/util.go` and cherry-pick to older Kubernetes versions, then move it to the E2E framework in a follow-up PR.

Your suggestion is to separate the WaitForPodInitContainerStarted into a single commit in this PR? Would it be okay to keep it as it is now?

**Comment by toVersus** [comment]
Sorry for the confusion. The only thing I'm concerned about is the order of the commits. Right now, I believe the commit order in this PR is roughly as follows:

1. Commit that fixes the issue
2. Addition of the Node E2E test

It seems more natural to first add the test that reproduces the issue, then add the commit that fixes the issue:

1. Add the Node E2E test (including WaitForPodInitContainerStarted)
2. Commit that fixes the issue

**Comment by zhifei92** [comment]
> I don't think we need to split the PR, so we can close #126860.

Done.Indeed, it was my misunderstanding.

**Comment by zhouhaibing089** [comment]
@kannon92: Thanks for being a reviewer for this PR. May I kindly ask for an update regarding this change?

**Comment by kannon92** [comment]
@matthyx can you help review? I don't have much context into restartable init containers so I don't feel comfortable reviewing that part of the node. I can help with the e2e test.

**Comment by matthyx** [comment]
> It's fine to wait until others have finished their reviews, but could you switch the order of the commits so that the E2E test addition comes first, followed by the code fix?"

Can you flip the order of commits as suggested pls?

**Comment by matthyx** [comment]
> @matthyx can you help review? I don't have much context into restartable init containers so I don't feel comfortable reviewing that part of the node. I can help with the e2e test.

the fix is fine, let's just reorder commits and I'll LGTM
@gjkim42 do you want to comment as well?

**Comment by zhifei92** [comment]
> Can you flip the order of commits as suggested pls?

done

File: test/e2e_node/pod_status_test.go [hunk 4]
```diff
@@ -0,0 +1,124 @@
...
+		}
+		preparePod(pod)
+
+		client := e2epod.NewPodClient(f)
+		pod = client.Create(ctx, pod)
+
+		ginkgo.By("Waiting for the regular container to be started")
+		err := e2epod.WaitForPodContainerStarted(ctx, f.ClientSet, pod.Namespace, pod.Name, 0, f.Timeouts.PodStart)
+		framework.ExpectNoError(err)
+		pod, err = client.Get(context.TODO(), pod.Name, metav1.GetOptions{})
```
Comment (bart0sh) [inline test/e2e_node/pod_status_test.go:82]:
```suggestion
		pod, err = client.Get(ctx, pod.Name, metav1.GetOptions{})
```

File: test/e2e_node/pod_status_test.go [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+		ginkgo.By("Restarting the kubelet")
+		restartKubelet()
+		gomega.Eventually(ctx, func() bool {
+			return kubeletHealthCheck(kubeletHealthCheckURL)
+		}, f.Timeouts.PodStart, f.Timeouts.Poll).Should(gomega.BeTrueBecause("kubelet should be started"))
+
+		ginkgo.By("Waiting for the regular init container to be started after the node reboot")
+		err = e2epod.WaitForPodInitContainerStarted(ctx, f.ClientSet, pod.Namespace, pod.Name, 0, f.Timeouts.PodStart)
+		framework.ExpectNoError(err)
+		pod, err = client.Get(context.TODO(), pod.Name, metav1.GetOptions{})
```
Comment (bart0sh) [inline test/e2e_node/pod_status_test.go:118]: the same here

Comment (zhifei92) [reply test/e2e_node/pod_status_test.go]: done, thx.

File: test/e2e_node/pod_status_test.go [hunk 6]
```diff
@@ -0,0 +1,124 @@
...
+		}, f.Timeouts.PodStart, f.Timeouts.Poll).Should(gomega.BeTrueBecause("kubelet should be started"))
+
+		ginkgo.By("Waiting for the regular init container to be started after the node reboot")
+		err = e2epod.WaitForPodInitContainerStarted(ctx, f.ClientSet, pod.Namespace, pod.Name, 0, f.Timeouts.PodStart)
+		framework.ExpectNoError(err)
+		pod, err = client.Get(ctx, pod.Name, metav1.GetOptions{})
+		framework.ExpectNoError(err)
+		if pod.Status.Phase != v1.PodPending {
+			framework.Failf("pod should be pending during the execution of the init container after the node reboot")
+		}
```
[the remark this answers is not in the document]
Comment (zhifei92) [reply test/e2e_node/pod_status_test.go]: done

File: pkg/kubelet/kubelet_pods.go [hunk 7]
```diff
@@ -1562,7 +1562,8 @@ func (kl *Kubelet) GetKubeletContainerLogs(ctx context.Context, podFullName, con
 // getPhase returns the phase of a pod given its container info.
 func getPhase(pod *v1.Pod, info []v1.ContainerStatus, podIsTerminal bool) v1.PodPhase {
 	spec := pod.Spec
-	pendingInitialization := 0
+	pendingRestartableInitContainers := 0
+	pendingRegularInitContainers := 0
```
Comment (gjkim42) [inline pkg/kubelet/kubelet_pods.go:1566]: Can you write a unit test for this problematic scenario?

File: pkg/kubelet/kubelet_pods.go [hunk 8]
```diff
@@ -1673,11 +1674,11 @@ func getPhase(pod *v1.Pod, info []v1.ContainerStatus, podIsTerminal bool) v1.Pod
 	}
 
 	switch {
-	case pendingInitialization > 0 &&
+	case pendingRegularInitContainers > 0 || (pendingRestartableInitContainers > 0 &&
 		// This is needed to handle the case where the pod has been initialized but
 		// the restartable init containers are restarting and the pod should not be
 		// placed back into v1.PodPending since the regular containers have run.
-		!kubecontainer.HasAnyRegularContainerStarted(&spec, info):
+		!kubecontainer.HasAnyRegularContainerStarted(&spec, info)):
```
Comment (gjkim42) [inline pkg/kubelet/kubelet_pods.go:1681]: or maybe we have to change this function?

to only return true if there is any regular container that is created or running but not terminated?

Comment (zhifei92) [reply pkg/kubelet/kubelet_pods.go:1681]: > or maybe we have to change this function?
> 
> to only return true if there is any regular container that is created or running but not terminated? (as the regular container may be in the terminated state after the node reboot while it hasn't started before)

https://github.com/kubernetes/kubernetes/blob/746f08a8da0a45e8b1a46362822db05cb11ed294/pkg/kubelet/container/helpers.go#L410-L412

Currently, relying solely on the function HasAnyRegularContainerStarted is indeed not sufficient，when `status.State.Running != nil || status.State.Terminated != nil` occurs and `HasAnyRegularContainerStarted `returns true, this is reasonable when the node has not been restarted. So do we have a way to determine whether the node has restarted?

Comment (gjkim42) [reply pkg/kubelet/kubelet_pods.go:1681]: I am ok with this change. This will correctly differentiate the initialization of init containers.

However, at the moment, I don't have a good way to differentiate the restarting restartable init containers from the initialization phase.

I'd prefer false Pending than false Running so I suggest you to change the `HasAnyRegularContainerStarted` to only return true when the regular container is in Running state.

If you are hesitating to change it, it's good to merge this as it is. I'll try to complement this by changing HasAnyRegularContainerStarted with the follow-up PR.

Comment (zhifei92) [reply pkg/kubelet/kubelet_pods.go:1681]: > I'd prefer false Pending than false Running so I suggest you to change the HasAnyRegularContainerStarted to only return true when the regular container is in Running state.

I prefer doing it this way currently, because, it is better for  unexpected  pod phase to occur during node restart than when the node is running normally.

>If you are hesitating to change it, it's good to merge this as it is. I'll try to complement this by changing HasAnyRegularContainerStarted with the follow-up PR.

ok，I will also pay attention to future improvements..

**Comment by gjkim42** [comment]
This will address the regression where a pod with a regular init container may incorrectly be marked as being in the Running phase.

We'll need to address the same issue for a pod with a restartable init container.

@zhifei92 
Could you add a unit test for TestPodPhaseXXX in kubelet_pods_test.go?

**Comment by zhifei92** [comment]
> TestPodPhaseXXX

Okay, the unit tests will be completed this week.

File: pkg/kubelet/kubelet_pods.go (hunk 7 above)
Comment (zhifei92) [reply pkg/kubelet/kubelet_pods.go:1566]: done

File: pkg/kubelet/kubelet_pods_test.go [hunk 9]
```diff
@@ -2626,6 +2626,102 @@ func TestPodPhaseWithRestartAlwaysRestartableInitContainers(t *testing.T) {
...
+				},
+			},
+			false,
+			v1.PodRunning,
+			"regular init container is succeeded, restartable init container and regular containers are both running",
+		},
+	}
+	featuregatetesting.SetFeatureGateDuringTest(t, utilfeature.DefaultFeatureGate, features.SidecarContainers, true)
+	for _, test := range tests {
+		statusInfo := append(test.pod.Status.InitContainerStatuses[:], test.pod.Status.ContainerStatuses[:]...)
```
Comment (gjkim42) [inline pkg/kubelet/kubelet_pods_test.go:2719]:
```suggestion
		statusInfo := test.pod.Status.InitContainerStatuses
		statusInfo := append(statusInfo, test.pod.Status.ContainerStatuses[:]...)
```

I think you have to fix the lint-error.

Comment (zhifei92) [reply pkg/kubelet/kubelet_pods_test.go:2719]: > I think you have to fix the lint-error.

There are a few instances of this lint error in other directories; we are only modifying the ones related to us this time

**Comment by SergeyKanzhelev** [comment]
@zhifei92  please squash commits. You may want to wait for more reviews before squashing though

File: pkg/kubelet/kubelet_pods.go [hunk 10]
```diff
@@ -1562,7 +1562,8 @@ func (kl *Kubelet) GetKubeletContainerLogs(ctx context.Context, podFullName, con
 // getPhase returns the phase of a pod given its container info.
 func getPhase(pod *v1.Pod, info []v1.ContainerStatus, podIsTerminal bool) v1.PodPhase {
 	spec := pod.Spec
-	pendingInitialization := 0
+	pendingRestartableInitContainers := 0
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kubelet_pods.go:1565]: as implemented it is hard to reason whether the new behavior can be disabled by turning the feature gate off. Can you please make logic more compartmentalized so we can reason about it easier from that perspective.

Comment (zhifei92) [reply pkg/kubelet/kubelet_pods.go:1565]: @SergeyKanzhelev I only encapsulated the restartable init containers. If other parts also need to do, I would be happy to do so. If you have any better suggestions, I appreciate your feedback. Thanks.

**Comment by zhifei92** [comment]
@SergeyKanzhelev @gjkim42 @matthyx please help to review this again, thanks.

File: test/e2e_node/pod_status_test.go [hunk 11]
```diff
@@ -0,0 +1,122 @@
...
+		gomega.Eventually(ctx, func() bool {
+			return kubeletHealthCheck(kubeletHealthCheckURL)
+		}, f.Timeouts.PodStart, f.Timeouts.Poll).Should(gomega.BeFalseBecause("kubelet should be stopped"))
+
+		ginkgo.By("Stopping the pod sandbox to simulate the node reboot")
+		err = rs.StopPodSandbox(ctx, podSandboxID)
+		framework.ExpectNoError(err)
+
+		ginkgo.By("Restarting the kubelet")
+		restartKubelet()
```
Comment (SergeyKanzhelev) [inline test/e2e_node/pod_status_test.go:110]: kubelet was stopped. Now you can use `startContainer`

File: test/e2e_node/pod_status_test.go [hunk 12]
```diff
@@ -0,0 +1,122 @@
...
+			return kubeletHealthCheck(kubeletHealthCheckURL)
+		}, f.Timeouts.PodStart, f.Timeouts.Poll).Should(gomega.BeTrueBecause("kubelet should be started"))
+
+		ginkgo.By("Waiting for the regular init container to be started after the node reboot")
+		err = e2epod.WaitForPodInitContainerStarted(ctx, f.ClientSet, pod.Namespace, pod.Name, 0, f.Timeouts.PodStart)
+		framework.ExpectNoError(err)
+		pod, err = client.Get(ctx, pod.Name, metav1.GetOptions{})
+		framework.ExpectNoError(err)
+		gomega.Expect(pod.Status.Phase == v1.PodPending).To(gomega.BeTrueBecause("pod should be pending during the execution of the init container after the node reboot"))
+	})
```
Comment (SergeyKanzhelev) [inline test/e2e_node/pod_status_test.go:121]: Can we get logs and confirm that the Init container actually run based on what is written to logs. Also I am not sure if log will contain the log from the previous execution as we deleted the sandbox. So make sure your check is actually validating properly that the init container run AFTER kubelet restart

File: test/e2e_node/pod_status_test.go [hunk 13]
```diff
@@ -0,0 +1,122 @@
...
+		gomega.Eventually(ctx, func() bool {
+			return kubeletHealthCheck(kubeletHealthCheckURL)
+		}, f.Timeouts.PodStart, f.Timeouts.Poll).Should(gomega.BeTrueBecause("kubelet should be started"))
+
+		ginkgo.By("Waiting for the regular init container to be started after the node reboot")
+		err = e2epod.WaitForPodInitContainerStarted(ctx, f.ClientSet, pod.Namespace, pod.Name, 0, f.Timeouts.PodStart)
+		framework.ExpectNoError(err)
+		pod, err = client.Get(ctx, pod.Name, metav1.GetOptions{})
+		framework.ExpectNoError(err)
+		gomega.Expect(pod.Status.Phase == v1.PodPending).To(gomega.BeTrueBecause("pod should be pending during the execution of the init container after the node reboot"))
```
Comment (SergeyKanzhelev) [inline test/e2e_node/pod_status_test.go:120]: Also check that the Pod will eventually fully start the Pod (i.e. init container will complete. sucessfully)

File: test/e2e_node/pod_status_test.go [hunk 14]
```diff
@@ -0,0 +1,122 @@
...
+	e2epod "k8s.io/kubernetes/test/e2e/framework/pod"
+	admissionapi "k8s.io/pod-security-admission/api"
+)
+
+var _ = SIGDescribe(framework.WithSerial(), "Pods status phase", func() {
+	f := framework.NewDefaultFramework("pods-status-phase-test-serial")
+	addAfterEachForCleaningUpPods(f)
+	f.NamespacePodSecurityLevel = admissionapi.LevelPrivileged
+
+	ginkgo.It("should be pending during the execution of the init container after the node reboot", func(ctx context.Context) {
```
Comment (SergeyKanzhelev) [inline test/e2e_node/pod_status_test.go:37]: Can you please add the same test with the sidecar container? So we will validate both types of init containers

Comment (SergeyKanzhelev) [reply test/e2e_node/pod_status_test.go:37]: I am also thinking whether we need to test various combination of sidecar being before the init container and the case when the sidecar is after the init container. In all these cases we should not lose the phase

File: pkg/kubelet/kubelet_pods.go [hunk 15]
```diff
@@ -1726,6 +1697,46 @@ func getPhase(pod *v1.Pod, info []v1.ContainerStatus, podIsTerminal bool) v1.Pod
 	}
 }
 
+// handleRestartableInitContainers handles restartable initialization containers.
+func handleRestartableInitContainers(spec v1.PodSpec, info []v1.ContainerStatus, unknown, running, waiting int) (int, int, int, int) {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kubelet_pods.go:1701]: code style: let's keep this inline and not as a separate function. All other loops are there and it just easier to understand what we do if it's all together

File: pkg/kubelet/kubelet_pods.go [hunk 16]
```diff
@@ -1673,11 +1644,11 @@ func getPhase(pod *v1.Pod, info []v1.ContainerStatus, podIsTerminal bool) v1.Pod
 	}
 
 	switch {
-	case pendingInitialization > 0 &&
+	case pendingRegularInitContainers > 0 || (pendingRestartableInitContainers > 0 &&
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/kubelet_pods.go:1647]: nit: this code is hard to understand as the bracket is hard to notice at first. Perhaps only keep the `pendingRegularInitContainers > 0 ||` on this line and other two conditions to after the comment

File: test/e2e_node/pod_status_test.go [hunk 17]
```diff
@@ -0,0 +1,122 @@
...
+
+		sandboxes, err := rs.ListPodSandbox(ctx, &runtimeapi.PodSandboxFilter{
+			LabelSelector: podLabels,
+		})
+		framework.ExpectNoError(err)
+		gomega.Expect(sandboxes).To(gomega.HaveLen(1))
+		podSandboxID := sandboxes[0].Id
+
+		ginkgo.By("Stopping the kubelet")
+		restartKubelet := stopKubelet()
```
Comment (SergeyKanzhelev) [inline test/e2e_node/pod_status_test.go:100]: Can you add a comment here on what exact stage we should restart the kubelet to test this? Do we need to restart while init container is still running?

File: test/e2e/framework/pod/wait.go [hunk 18]
```diff
@@ -809,6 +809,18 @@ func WaitForPodContainerStarted(ctx context.Context, c clientset.Interface, name
 	})
 }
 
+// WaitForPodInitContainerStarted waits for the given Pod init container to start.
+func WaitForPodInitContainerStarted(ctx context.Context, c clientset.Interface, namespace, podName string, initContainerIndex int, timeout time.Duration) error {
```
Comment (SergeyKanzhelev) [inline test/e2e/framework/pod/wait.go:813]: Not sure if we need it that specific. For example, `WaitForContainerRunning` allows to wait for any container to be running.

**Comment by SergeyKanzhelev** [comment]
It looks to me that the code in pkg/kubelet/kubelet_pods.go is correct. I left a few smaller comments all around. Thank you for waiting, I was too busy with KEP freeze reviews

**Comment by zhifei92** [comment]
> It looks to me that the code in pkg/kubelet/kubelet_pods.go is correct. I left a few smaller comments all around. Thank you for waiting, I was too busy with KEP freeze reviews

I completely understand. Thank you very much for taking the time to review.

File: pkg/kubelet/kubelet_pods.go (hunk 15 above)
Comment (zhifei92) [reply pkg/kubelet/kubelet_pods.go:1701]: > code style: let's keep this inline and not as a separate function. All other loops are there and it just easier to understand what we do if it's all together

This modification is due to your previous comment. I might not have fully understood the true intent behind the following statement.

> as implemented it is hard to reason whether the new behavior can be disabled by turning the feature gate off. Can you please make logic more compartmentalized so we can reason about it easier from that perspective.

File: test/e2e/framework/pod/wait.go (hunk 18 above)
Comment (zhifei92) [reply test/e2e/framework/pod/wait.go:813]: > Not sure if we need it that specific. For example, `WaitForContainerRunning` allows to wait for any container to be running.

`WaitForContainerRunning` indeed meets the requirement. However, there is a check for `started` in `getPhase`. Additionally, since we already have `WaitForPodContainerStarted`, adding a `WaitForPodInitContainerStarted` seems reasonable.

File: test/e2e_node/pod_status_test.go (hunk 14 above)
Comment (zhifei92) [reply test/e2e_node/pod_status_test.go:37]: > Can you please add the same test with the sidecar container? So we will validate both types of init containers

This PR can only fix the impact of regular init containers on the phase after a node restart. 

see comments:
https://github.com/kubernetes/kubernetes/pull/126653#discussion_r1740249454
https://github.com/kubernetes/kubernetes/pull/126653#discussion_r1740871387

File: test/e2e_node/pod_status_test.go (hunk 12 above)
Comment (zhifei92) [reply test/e2e_node/pod_status_test.go:121]: We can query the logs after the kubelet restart, which should work.

File: test/e2e_node/pod_status_test.go [hunk 19]
```diff
@@ -0,0 +1,140 @@
...
+
+		ginkgo.By("Waiting for the regular init container to be started after the node reboot")
+		err = e2epod.WaitForPodInitContainerStarted(ctx, f.ClientSet, pod.Namespace, pod.Name, 0, f.Timeouts.PodStart)
+		framework.ExpectNoError(err)
+
+		pod, err = client.Get(ctx, pod.Name, metav1.GetOptions{})
+		framework.ExpectNoError(err)
+		gomega.Expect(pod.Status.Phase == v1.PodPending).To(gomega.BeTrueBecause("pod should be pending during the execution of the init container after the node reboot"))
+
+		ginkgo.By("Get the logs of the init container after the kubelet restart")
```
Comment (toVersus) [inline test/e2e_node/pod_status_test.go:124]: There is a helper function available that can parse container logs to check if a restart has occurred, so it might be better to rewrite it as follows.

```go
		ginkgo.By("Parse the logs of the pod after the kubelet restart")
		results := parseOutput(ctx, f, pod)
		ginkgo.By("Analyzing results")
		initStartedTimeUnix, err := results.TimeOfLastStart(init)
		framework.ExpectNoError(err)
		initStartedTime := time.UnixMilli(initStartedTimeUnix)
		gomega.Expect(initStartedTime).Should(gomega.BeTemporally(">", kubeletRestartedTime),
			"The logs should contain the most recent occurrence of \"Starting\" output from init container after the kubelet restart")
```

File: test/e2e_node/pod_status_test.go [hunk 20]
```diff
@@ -0,0 +1,140 @@
...
+		}).DoRaw(ctx)
+		framework.ExpectNoError(err)
+		// The `container Starting` log is generated in ExecCommand.
+		expectedLog := fmt.Sprintf("%s Starting", init)
+		gomega.Expect(string(logs)).To(gomega.ContainSubstring(expectedLog), "The logs should contain the expected output from the init container after the kubelet restart")
+
+		ginkgo.By("Verifying that the pod fully starts")
+		err = e2epod.WaitForPodNameRunningInNamespace(ctx, f.ClientSet, pod.Name, pod.Namespace)
+		framework.ExpectNoError(err)
+	})
```
Comment (toVersus) [inline test/e2e_node/pod_status_test.go:139]: It might be a good idea to add a step to verify that the initContainer has successfully completed after the Pod reaches the Running state.

```go
		ginkgo.By("Verifying that the init container completed successfully")
		pod, err = client.Get(ctx, pod.Name, metav1.GetOptions{})
		framework.ExpectNoError(err)
		gomega.Expect(pod.Status.InitContainerStatuses[0].State.Terminated).NotTo(gomega.BeNil(), "init container should be terminated")
		gomega.Expect(pod.Status.InitContainerStatuses[0].State.Terminated.ExitCode).To(gomega.BeZero(), "init container should complete successfully")
```

File: pkg/kubelet/kubelet_pods_test.go [hunk 21]
```diff
@@ -2620,7 +2621,105 @@ func TestPodPhaseWithRestartAlwaysRestartableInitContainers(t *testing.T) {
...
+		},
+		Containers: []v1.Container{
+			{Name: "containerA"},
+		},
+		RestartPolicy: v1.RestartPolicyAlways,
+	}
+
+	tests := []struct {
+		pod           *v1.Pod
+		podIsTerminal bool
```
Comment (toVersus) [inline pkg/kubelet/kubelet_pods_test.go:2646]: nit: The test added this time only covers the case where `podIsTerminal: false`, so I think it's fine to explicitly pass false at line 2723.

File: pkg/kubelet/kubelet_pods_test.go [hunk 22]
```diff
@@ -2620,7 +2621,105 @@ func TestPodPhaseWithRestartAlwaysRestartableInitContainers(t *testing.T) {
...
+						runningState("containerX"),
+						runningState("containerY"),
+					},
+					ContainerStatuses: []v1.ContainerStatus{
+						stoppedState("containerA"),
+					},
+				},
+			},
+			false,
+			v1.PodPending,
```
Comment (toVersus) [inline pkg/kubelet/kubelet_pods_test.go:2681]: It feels odd to me that this test case results in a Pending state, but it's due to what's mentioned in https://github.com/kubernetes/kubernetes/pull/126653#discussion_r1737554335, right? If that's the case, adding a comment to explain the context might be helpful for future readers.

File: test/e2e_node/pod_status_test.go (hunk 20 above)
Comment (zhifei92) [reply test/e2e_node/pod_status_test.go:139]: Thank you, this looks great.

File: test/e2e_node/pod_status_test.go (hunk 19 above)
Comment (zhifei92) [reply test/e2e_node/pod_status_test.go:124]: Thank you, this looks great.

File: test/e2e_node/pod_status_test.go (hunk 20 above)
Comment (zhifei92) [reply test/e2e_node/pod_status_test.go:139]: Thank you for your suggestion, but I don't think it's necessary to do so. A pod running is certainly after the regular init container has completed.

Comment (toVersus) [reply test/e2e_node/pod_status_test.go:139]: Yes, but that's just our assumption, and we might break this behavior in the future. Since the main point of this test is the init container, I personally think it’s worth checking that it completes successfully after the Pod starts.
I don’t think it’d take much effort to add it here, but if you don’t think it’s necessary, I’ll leave it up to you.

Comment (zhifei92) [reply test/e2e_node/pod_status_test.go:139]: Thanks

File: pkg/kubelet/kubelet_pods_test.go (hunk 21 above)
Comment (zhifei92) [reply pkg/kubelet/kubelet_pods_test.go:2646]: The scenario here indeed will not have a `true` case.

File: pkg/kubelet/kubelet_pods_test.go (hunk 22 above)
Comment (zhifei92) [reply pkg/kubelet/kubelet_pods_test.go:2678]: The scenario is: before the node restarts, the regular container is in a non-running state due to some reason (such as an abnormal exit). After the node restarts, as long as the regular init container is running, the pod should be in a Pending state.

**Review by gjkim42 — COMMENTED** [review]
/lgtm

This fixes the issue where a pod with regular init containers cannot have the proper `Pending` phase upon its re-initialization after a node reboot.

This seems like a regression after the SidecarContainers feature.
@SergeyKanzhelev 
Do we need a cherry-pick for this?

**Comment by kannon92** [comment]
/hold

The serial test is failing for a reason related to your PR.

**Comment by gjkim42** [comment]
test/e2e_node/pod_status_test.go:97:19: undefined: stopKubelet

Looks like a real failure you need to fix this.
/lgtm cancel

File: test/e2e_node/pod_status_test.go [hunk 23]
```diff
@@ -0,0 +1,129 @@
...
+		podSandboxID := sandboxes[0].Id
+
+		// We need to wait for the pod to be Running before simulating the node reboot,
+		// to avoid any unintended effects from the previous init container state.
+		// Simulate node reboot by restarting the kubelet and the pod sandbox.
+		ginkgo.By("Stopping the kubelet")
+		startKubelet := stopKubelet()
+		gomega.Eventually(ctx, func() bool {
+			return kubeletHealthCheck(kubeletHealthCheckURL)
+		}, f.Timeouts.PodStart, f.Timeouts.Poll).Should(gomega.BeFalseBecause("kubelet should be stopped"))
```
Comment (bart0sh) [inline test/e2e_node/pod_status_test.go:100]: This was changed in https://github.com/kubernetes/kubernetes/pull/128576
```suggestion
		ginkgo.By("Stopping the kubelet")
		restartKubelet := mustStopKubelet(ctx, f)
```

Comment (zhifei92) [reply test/e2e_node/pod_status_test.go]: thanks

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

File: test/e2e/framework/pod/wait.go [hunk 24]
```diff
@@ -809,6 +809,18 @@ func WaitForPodContainerStarted(ctx context.Context, c clientset.Interface, name
...
+	conditionDesc := fmt.Sprintf("init container %d started", initContainerIndex)
+	return WaitForPodCondition(ctx, c, namespace, podName, conditionDesc, timeout, func(pod *v1.Pod) (bool, error) {
+		if initContainerIndex > len(pod.Status.InitContainerStatuses)-1 {
```
Comment (pohly) [inline test/e2e/framework/pod/wait.go:816]:
```suggestion
		if initContainerIndex >= len(pod.Status.InitContainerStatuses) {
```

Comment (pohly) [reply test/e2e/framework/pod/wait.go:816]: /approve

This is is minor, but IMHO worth simplifying. I'll let you decide when you want to do that.

/hold

Comment (SergeyKanzhelev) [reply test/e2e/framework/pod/wait.go:816]: it's a copy from `WaitForPodContainerStarted`. Let's fix them both later

/unhold
