### PR TITLE
Make kubelet touch iptables lock file during initialization

### LINKED ISSUE #47186: E2E gci-gce-serial kube-dns not coming up
gci-gce-serial has been failing since June 4th.

https://k8s-testgrid.appspot.com/release-master-blocking#gci-gce-serial&width=5

Seens a lot of different test failures that look like kube-system isn't coming up.

A bunch are looping on kube-dns not being ready.

```
I0607 21:11:47.198] Jun  7 21:11:47.198: INFO: The status of Pod kube-dns-2836479273-kr3f4 is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0607 21:11:47.199] Jun  7 21:11:47.198: INFO: The status of Pod kube-dns-2836479273-mk7q5 is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
I0607 21:11:47.199] Jun  7 21:11:47.198: INFO: The status of Pod kubernetes-dashboard-1971317102-1475c is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1210?log#log
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1208?log#log
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1209?log#log
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1207?log#log

Am diving into the kubelet logs to try to see what's going on and identify a SIG.

cc @kubernetes/kubernetes-release-managers

### PR DESCRIPTION
**Pull request by MrHohn**
Fixes #47186.

/assign @freehan @yujuhong 
cc @dchen1107 @Q-Lee 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -507,6 +507,16 @@ func NewMainKubelet(kubeCfg *componentconfig.KubeletConfiguration, kubeDeps *Kub
 	}
 	glog.Infof("Hairpin mode set to %q", hairpinMode)
 
+	// TODO(#36485) Remove this workaround once we fix the init-container issue.
+	// Touch iptables lock file, which will be shared among all containers.
+	f, err := os.OpenFile(utilipt.LockfilePath16x, os.O_CREATE, 0600)
+	if err != nil {
+		glog.Warningf("Failed to open iptables lock file: %v", err)
+	}
+	if err := f.Close(); err != nil {
```
Comment (ericchiang) [inline pkg/kubelet/kubelet.go]: If OpenFile returns and error `f` will be nil and this call will panic.

Comment (MrHohn) [inline pkg/kubelet/kubelet.go]: Thanks, done.

File: pkg/kubelet/kubelet.go [hunk 2]
```diff
@@ -507,6 +507,15 @@ func NewMainKubelet(kubeCfg *componentconfig.KubeletConfiguration, kubeDeps *Kub
 	}
 	glog.Infof("Hairpin mode set to %q", hairpinMode)
 
+	// TODO(#36485) Remove this workaround once we fix the init-container issue.
+	// Touch iptables lock file, which will be shared among all containers.
+	f, err := os.OpenFile(utilipt.LockfilePath16x, os.O_CREATE, 0600)
+	if f == nil || err != nil {
```
Comment (yujuhong) [inline pkg/kubelet/kubelet.go]: nit: don't think you'll need to check `f == nil` since you already checked `err != nil`

File: pkg/kubelet/kubelet.go [hunk 3]
```diff
@@ -507,6 +507,15 @@ func NewMainKubelet(kubeCfg *componentconfig.KubeletConfiguration, kubeDeps *Kub
 	}
 	glog.Infof("Hairpin mode set to %q", hairpinMode)
 
+	// TODO(#36485) Remove this workaround once we fix the init-container issue.
+	// Touch iptables lock file, which will be shared among all containers.
```
Comment (yujuhong) [inline pkg/kubelet/kubelet.go]: `Shared among all containers` or shared among all processes accessing the iptables?

Comment (MrHohn) [inline pkg/kubelet/kubelet.go]: Thanks, the latter seems more accurate. Applied.

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (MrHohn) [inline pkg/kubelet/kubelet.go]: Done.

**Comment by dchen1107** [comment]
/lgtm

I am going to manually merge this to stop serial test failures.
