### PR TITLE
Fix for preferred dualstack and required dualstack in winkernel proxier.

### LINKED ISSUE #136240: [KubeProxy-Windows] RequireDualStack Service intermittently misprogrammed in Windows kube-proxy
### What happened?

When creating a Service with ipFamilyPolicy: RequireDualStack or PreferredDualstack on Windows nodes, kube-proxy sometimes programs incorrect load balancers.

The issue manifests in two main ways:

1. Incorrect backend selection
    - IPv6 endpoints are sometimes programmed as backends for IPv4 VIPs
    - IPv4 endpoints are sometimes programmed as backends for IPv6 VIPs
    - This results in traffic blackholing or connection failures

2. Incorrect load balancer flags
   - IPv6-specific HNS flags are sometimes applied to IPv4 load balancers
   - IPv4 flags are sometimes applied to IPv6 load balancers
   - This causes inconsistent behavior and unexpected failures in datapath programming

These issues appear intermittent and are more frequently observed under:

- Endpoint updates
- Service updates
- Rapid pod churn 

### What did you expect to happen?

For a RequireDualStack Service:

- IPv4 VIPs should:
    - Use only IPv4 endpoints
    - Be programmed with IPv4-specific HNS flags

- IPv6 VIPs should:
    - Use only IPv6 endpoints
    - Be programmed with IPv6-specific HNS flags

The programming behavior should be deterministic and consistent, matching the dual-stack service semantics defined in the Kubernetes dual-stack KEP.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Windows cluster with:
    - Dual-stack networking enabled
    - Windows nodes using winkernel kube-proxy
2. Create a Service:
 
```
apiVersion: v1
kind: Service
metadata:
  name: test-dualstack-lb
spec:
  type: LoadBalancer
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app: test
  ports:
    - port: 80
      targetPort: 80
```
 
3. Deploy dual-stack pods with both IPv4 and IPv6 addresses
4. Trigger updates:
    - Scale pods up/down
    - Restart kube-proxy
    - Update endpoints or service annotations
5. Observe HNS load balancers and backend programming

### Anything else we need to know?

- This issue appears to be specific to Windows kube-proxy (winkernel).
- This issue violates the dual-stack contract defined in the Kubernetes dual-stack KEP.

### Kubernetes version

<details>

```console
All K8S versions
```

</details>

### Cloud provider

<details>
AKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by princepereira**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

This PR fixes dual-stack service handling in the Windows (winkernel) kube-proxy implementation by correctly separating IPv4 and IPv6 load balancer state.

Specifically, it updates the Windows proxier to:

- Correctly identify whether a Service VIP and its endpoints are IPv4 or IPv6
- Include an explicit isIPv6 dimension in the load balancer identifier, ensuring IPv4 and IPv6 load balancers are tracked independently
- Prevent incorrect reuse or collision of HNS load balancer policies between IPv4 and IPv6 services
- Properly support both PreferDualStack and RequireDualStack Service types during sync and reconciliation. The primary change in this PR is that, while the BaseServicePortInfo object already maintains IP-family–filtered lists of externalIPs and loadBalancerVIPs derived from service.Spec.ExternalIPs and service.Status.LoadBalancer.Ingress, the WinKernel service info previously re-extracted these values directly from the Service object without applying IP-family filtering. This led to incorrect behavior for dual-stack services. The updated implementation eliminates this duplication by sourcing the required information directly from BaseServicePortInfo instead of reprocessing the Service spec and status.

Without this change, the Windows kube-proxy may incorrectly mix IPv4 and IPv6 backends, fail to create required IPv6 load balancers, or reuse an existing IPv4 load balancer for IPv6 traffic. This results in broken or incomplete dual-stack behavior on Windows nodes.

By explicitly separating load balancer state per IP family, this PR enables correct, predictable dual-stack service programming on Windows, bringing winkernel behavior closer to Linux kube-proxy and unblocking dual-stack AKS / Windows scenarios.

#### Which issue(s) this PR is related to:
Fixes #136240
KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/563-dual-stack

#### Does this PR introduce a user-facing change?

```release-note
Fixed an issue in the Windows kube-proxy (winkernel) where IPv4 and IPv6 Service load balancers could be incorrectly shared, causing broken dual-stack Service behavior. The kube-proxy now tracks load balancers per IP family, enabling correct support for PreferDualStack and RequireDualStack Services on Windows nodes.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/proxy/winkernel/hns.go [hunk 1]
```diff
@@ -303,17 +305,17 @@ func (hns hns) deleteEndpoint(hnsID string) error {
...
 	if err != nil {
 		klog.V(2).ErrorS(err, "Error hashing endpoints", "endpoints", endpoints)
 		return loadBalancerIdentifier{}, err
 	}
 	if len(vip) > 0 {
-		return loadBalancerIdentifier{protocol: protocol, internalPort: internalPort, externalPort: externalPort, vip: vip, endpointsHash: hash}, nil
+		return loadBalancerIdentifier{protocol: protocol, internalPort: internalPort, externalPort: externalPort, vip: vip, endpointsHash: hash, isIPv6: isIpv6}, nil
 	}
-	return loadBalancerIdentifier{protocol: protocol, internalPort: internalPort, externalPort: externalPort, endpointsHash: hash}, nil
+	return loadBalancerIdentifier{protocol: protocol, internalPort: internalPort, externalPort: externalPort, endpointsHash: hash, isIPv6: isIpv6}, nil
```
Comment (prince-melvin) [inline pkg/proxy/winkernel/hns.go]: nit:
The return loadBalancerIdentifier{...} block is duplicated. Anyways the default value for vip is empty string?

Comment (princepereira) [reply pkg/proxy/winkernel/hns.go]: Addressed.

**Comment by danwinship** [comment]
(I wasn't really planning to review this, since I'm not terribly familiar with the winkernel code and winkernel PRs normally get reviewed/merged by SIG Windows people, right? I just skimmed the PR since you had pinged me explicitly.)
