### PR TITLE
Delete stale UDP conntrack entries that use hostPort

### LINKED ISSUE #59033: conntrack table for UDP to vanished pod not flushed
/kind bug

**What happened**:
1. A server pod exposes UDP host port.
2. A client sends packets to the server pod thru the host port. This creates a conntrack entry.
3. The server pod's IP changs due to whatever reason, such as pod gets recreated.
4. Due to the nature of UDP and conntrack, new request from the same client to the host port will keep hitting the stale conntrack entry.
5. Client observes traffic black hole.

**What you expected to happen**:
After recreation of the server pod (with the same host port), UDP packets reach the new server pod.

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: test-udp-server
  namespace: default
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-udp-server
      name: test-udp-server
    spec:
      hostNetwork: true
      containers:
      - image: SEE_DOCKERFILE
        name: test-udp-server
        ports:
          - name: udp
            containerPort: 8125
            hostPort: 8125
            protocol: UDP
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: REVISION
          value: "R1"
        command:
        - "bash"
        - "-c"
        - |
          set -x
          socat - UDP4-RECVFROM:8125,fork
        livenessProbe:
          exec:
            command:
            - "bash"
            - "-c"
            - |
              echo "Liveness probe: $(date)" | socat - UDP4-DATAGRAM:$(hostname -i):8125
          initialDelaySeconds: 60
          periodSeconds: 60
```

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-udp-client
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: test-udp-client
    spec:
      containers:
      - image: SEE_DOCKERFILE
        name: test-udp-client
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command:
        - "bash"
        - "-c"
        - |
          set -x
          socat - UDP4-DATAGRAM:$HOST:8125 < <(while true ; do echo "From $(hostname): $(date)"; sleep 1 ; done)
```

```
FROM debian:stretch

RUN apt-get -y update
RUN apt-get -y --no-upgrade install socat tcpdump
```

1. Create the above daemonset and deployment.
2. kubectl attach to the daemon pod on the same node as the client, see output
3. change revision in daemonset, kubectl apply it.
4. kubectl attach again, see no output.

**Environment**: GKE 1.8.x

### PR DESCRIPTION
**Pull request by prameshj**
**What this PR does / why we need it**:
This PR introduces a change to delete stale conntrack entries for UDP connections, specifically for udp connections that use hostPort. When the pod listening on that udp port get updated/restarted(and gets a new ip address), these entries need to be flushed so that ongoing udp connections can recover once the pod is back and the new iptables rules have been installed. 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #59033

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by prameshj** [comment]
signed the CNCF CLA

File: pkg/kubelet/network/hostport/hostport_manager.go [hunk 1]
```diff
@@ -150,6 +159,21 @@ func (hm *hostportManager) Add(id string, podPortMapping *PodPortMapping, natInt
 		// clean up opened host port if encounter any error
 		return utilerrors.NewAggregate([]error{err, hm.closeHostports(hostportMappings)})
 	}
+	isIpv6 := utilconntrack.IsIPv6(podPortMapping.IP)
+
+	// Remove conntrack entries just after adding the new iptables rules. Better to do this here than in Remove because
```
Comment (bowei) [inline pkg/kubelet/network/hostport/hostport_manager.go]: I'm find it a little hard to understand this comment. Maybe something like 
```
// Remove conntrack entries just after adding the new iptables rules. If the conntrack entry
// is removed along with the IP tables rule, it can be the case that the packets received by
// the client after IP table rule removal will create a new conntrack entry that will result in
//  blackhole of the traffic.
```

File: pkg/kubelet/network/hostport/hostport_manager_test.go [hunk 2]
```diff
@@ -25,6 +25,7 @@ import (
 	"github.com/stretchr/testify/assert"
 	"k8s.io/api/core/v1"
 	utiliptables "k8s.io/kubernetes/pkg/util/iptables"
+	utilexec "k8s.io/utils/exec"
```
Comment (bowei) [inline pkg/kubelet/network/hostport/hostport_manager_test.go]: don't rename packages unless it is necessary

**Comment by bowei** [comment]
/assign @dchen1107 

Please reassign as appropriate

File: hack/.golint_failures [hunk 3]
```diff
@@ -343,6 +343,7 @@ pkg/ssh
 pkg/util/bandwidth
 pkg/util/config
 pkg/util/configz
+pkg/util/conntrack
```
Comment (madhusudancs) [inline hack/.golint_failures]: Please fix the lint warnings by adding comments to the exported names instead of adding this package to the ignore file. I am worried that this package will stay here for ever if we don't fix this now and the fix is not that involved. See the lint failures and suggestions here: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/59286/pull-kubernetes-verify/75380/#verify-golint

**Review by madhusudancs — CHANGES_REQUESTED** [review]

**Comment by madhusudancs** [comment]
/lgtm

LGTM for the refactor, i.e. `pkg/proxy/util/conntrack*` → `pkg/util/conntrack/...`. Please wait for an LGTM from someone who knows kubelet and networking too.

**Review by madhusudancs — APPROVED** [review]

**Comment by freehan** [comment]
@squeed Probably make sense to adopt this fix to portmap?

**Comment by dchen1107** [comment]
cc/ @adityakali @kubernetes/goog-image for potential issues?

**Comment by adityakali** [comment]
IIUC this is invoking `conntrack` tool from host OS? Most distros do not have `conntrack` tool installed by default. Debian & Ubuntu doesn't have it and neither does COS (unless it is invoked from the [toolbox container](https://cloud.google.com/container-optimized-os/docs/how-to/toolbox)).
So unfortunately this will not help.

I will prefer if k8s does not add dependencies on specialized tools in the OS. Better option is to carry dependencies in a separate container similar to how it is done for mount utilities: [Proposal: containerized mount utilities in pods](https://github.com/kubernetes/community/pull/589).

File: pkg/kubelet/network/hostport/hostport_manager_test.go (hunk 2 above)
Comment (thockin) [reply pkg/kubelet/network/hostport/hostport_manager_test.go]: This one is pretty common

File: pkg/kubelet/network/hostport/hostport_manager.go [hunk 4]
```diff
@@ -45,6 +48,7 @@ type HostPortManager interface {
 
 type hostportManager struct {
 	hostPortMap map[hostport]closeable
+	conntrack   utilexec.Interface
```
Comment (thockin) [inline pkg/kubelet/network/hostport/hostport_manager.go]: call this `exec` or something - it's not about conntrack

**Review by thockin — COMMENTED** [review]
The joy of making better package boundaries is renaming things and fixing APIs!

I propose to:

rename `ClearUDPConntrackForIP` to `ClearToIP` and take "udp" as an argument.

rename `ExecConntrackTool` to `Exec`

rename `ClearUDPConntrackForPort` to `ClearToPort` and take "udp" as an argument

rename `ClearUDPConntrackForPeers` to `ClearToMappedIP` and take "udp" as an argument

These are not great (open to ideas) but a re a minimal API cleanup.  This pkg should probably eventually look more like iptables and ipvs - with a handle struct with methods, and maybe a more complete command syntax (or maybe just be transparent like iptables is).

**Review by thockin — COMMENTED** [review]
Also, please squash the main commits together, but you can leave BUILD and lint as their own

**Comment by prameshj** [comment]
Thanks for taking a look @thockin. I renamed the conntrack functions to the form ClearEntryFor* and added protocol as a parameter.
Squashed all changes into one commit, sorry could not separate out just the lint and BUILD changes.

**Comment by thockin** [comment]
`git rebase -i` is your friend :)  No problem for now, but I strongly encourage you (and everyone) to learn it :)

File: pkg/kubelet/network/hostport/hostport_manager.go [hunk 5]
```diff
@@ -150,6 +165,21 @@ func (hm *hostportManager) Add(id string, podPortMapping *PodPortMapping, natInt
 		// clean up opened host port if encounter any error
 		return utilerrors.NewAggregate([]error{err, hm.closeHostports(hostportMappings)})
 	}
+	isIpv6 := conntrack.IsIPv6(podPortMapping.IP)
```
Comment (thockin) [inline pkg/kubelet/network/hostport/hostport_manager.go]: For future work - we should move the IsIPv6() stuff to a more generic place.

File: pkg/kubelet/network/hostport/hostport_manager.go [hunk 6]
```diff
@@ -150,6 +165,21 @@ func (hm *hostportManager) Add(id string, podPortMapping *PodPortMapping, natInt
...
+
+	// Remove conntrack entries just after adding the new iptables rules. If the conntrack entry is removed along with
+	// the IP tables rule, it can be the case that the packets received by the node after iptables rule removal will
+	// create a new conntrack entry without any DNAT. That will result in blackhole of the traffic even after correct
+	// iptables rules have been added back.
+	if hm.execer != nil && hm.conntrackFound {
+		glog.Infof("Starting to delete udp conntrack entries: %v, isIPv6 - %v", conntrackPortsToRemove, isIpv6)
+		for _, port := range conntrackPortsToRemove {
+			err = conntrack.ClearEntryForPort(hm.execer, port, isIpv6, v1.ProtocolUDP)
```
Comment (thockin) [inline pkg/kubelet/network/hostport/hostport_manager.go]: sorry to nit-pick.  "Entry" should be "Entries" I think?

File: pkg/proxy/iptables/proxier.go [hunk 7]
```diff
@@ -682,7 +683,7 @@ func (proxier *Proxier) deleteEndpointConnections(connectionMap []proxy.ServiceE
 	for _, epSvcPair := range connectionMap {
 		if svcInfo, ok := proxier.serviceMap[epSvcPair.ServicePortName]; ok && svcInfo.Protocol() == api.ProtocolUDP {
 			endpointIP := utilproxy.IPPart(epSvcPair.Endpoint)
-			err := utilproxy.ClearUDPConntrackForPeers(proxier.exec, svcInfo.ClusterIP(), endpointIP)
+			err := conntrack.ClearEntryForIPPair(proxier.exec, svcInfo.ClusterIP(), endpointIP, v1.ProtocolUDP)
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: IPPair is not quite descriptive - I would assume it is client/dest pair but it's really a NAT record.  ClearEntriesForNAT() ?

File: pkg/util/conntrack/conntrack.go [hunk 8]
```diff
@@ -14,42 +14,53 @@ See the License for the specific language governing permissions and
...
 	return netIP != nil && netIP.To4() == nil
 }
 
+// IsIPv6String returns true if the given string is a valid ipv6 address
 func IsIPv6String(ip string) bool {
 	netIP := net.ParseIP(ip)
 	return IsIPv6(netIP)
 }
 
+func protoStr(proto v1.Protocol) string {
```
Comment (thockin) [inline pkg/util/conntrack/conntrack.go]: Why not just strings.ToLower() it and be done.  If the caller passes "ICMP", we should pass that thru to conntrack.

Comment (prameshj) [reply pkg/util/conntrack/conntrack.go]: Good point, done. i left the protoStr function as is, in case we want to add any checks in future.  Incorporated the other comments as well.

**Comment by prameshj** [comment]
I was trying to do a git rebase -i, but it was hard to isolate the BUILD and lint commits since there were some main files commits in between them as well. I will make sure I look into all options in the command. Thanks for reviewing the changes.

**Comment by dchen1107** [comment]
/lgtm 

Are you going to send me a following pr to install the binary through cloud_init for GCE? That is not a good way to use cloud_init, but I guess I can live with it as a temporary workaround for now since we already did this for cni binaries.

**Comment by prameshj** [comment]
@dchen1107 This is the PR to install the binary - https://github.com/kubernetes/kubernetes/pull/64640

**Comment by subrnath** [comment]
I am facing similar issue with TCP https://github.com/kubernetes/kubernetes/issues/82727

**Comment by AasthaRai95** [comment]
I am still facing the issue. I have a service which collects the syslogs and runs on udp port. As soon as I delete the pod I am expecting that conntrack entries should get deleted but it doesnt delete on delete or even on restart. I am using kubernetes version - 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:25:59Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:08:36Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
What could be the problem here?

**Comment by aojea** [comment]
hostPort depends on the runtime or plugin implementation, crio implements it in core and containerd use to rely in the cni portmap plugin

**Comment by AasthaRai95** [comment]
I didn't get you, could you please elaborate @aojea
