### PR TITLE
Fix UpdateSnapshot when Node is partially removed

### LINKED ISSUE #95124: Node Snapshot can become out-of-sync when Node is deleted before its Pods
/sig scheduling

**What happened**:

#93938 reverted an old behavior to ensure Pod information is not lost when Nodes are recreated without its Pods getting recreated. A ghost Pod is kep in `cache.nodes`

The problem is that we rely in this map for determining deleted Nodes when updating the snapshot in `cache.UpdateSnapshot`.

The good thing is that the nodeinfo's are cloned into the snapshot, so we shouldn't have nil pointer accesses. But we might lose a few cycles trying to schedule on nodes that are deleted

**How to reproduce it (as minimally and precisely as possible)**:

1. Have a node with a few pods.
2. Delete node without deleting pods.

Result: The snapshot still has the node.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18+

### PR DESCRIPTION
**Pull request by alculquicondor**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Fix Snapshot update when a Node is deleted before its Pods.

**Which issue(s) this PR fixes**:

Fixes #95124

**Special notes for your reviewer**:

This is an old bug that was reintroduced when #93938 reverted some behavior

**Does this PR introduce a user-facing change?**:

```release-note
Fix a regression in 1.19 in scheduler cache snapshot when a Node is deleted before its Pods
```

### CODE REVIEW

**Comment by alculquicondor** [comment]
/priority critical-urgent

/assign @Huang-Wei 

Sorry I missed this in the previous PR :(
We need to get this cherry picked down to 1.18

File: pkg/scheduler/internal/cache/cache.go [hunk 1]
```diff
@@ -256,7 +256,7 @@ func (cache *schedulerCache) UpdateSnapshot(nodeSnapshot *Snapshot) error {
 		nodeSnapshot.generation = cache.headNode.info.Generation
 	}
 
-	if len(nodeSnapshot.nodeInfoMap) > len(cache.nodes) {
+	if len(nodeSnapshot.nodeInfoMap) > cache.nodeTree.numNodes {
```
Comment (ahg-g) [inline pkg/scheduler/internal/cache/cache.go:259]: can you add a comment explaining that deleted nodes get removed from the tree but are kept in the cache until the pods are deleted, and hence here we check against the number of nodes in the tree not the cache.

Comment (ahg-g) [reply pkg/scheduler/internal/cache/cache.go:259]: also, document that the snapshot (both map and lists) only include nodes that are not deleted as of the time the snapshot was taken, and so nodeinfo.Node() is guaranteed not to be nil.

Comment (alculquicondor) [reply pkg/scheduler/internal/cache/cache.go:264]: Done. I amended.

**Comment by Huang-Wei** [comment]
Thanks @alculquicondor !

/unhold
