### PR TITLE
[scheduler] [test]: Fix PreferNominatedNode test

### LINKED ISSUE #105492: PreferNominatedNode integration test flakes
#### Which jobs are flaking:
Integration tests are sometimes flaking locally:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/105432/pull-kubernetes-integration/1445055277958172672
#### Which test(s) are flaking:
PreferNominatedNode
#### Reason for failure:
Once the node gets deleted, the nodelifecycle controller
is racing to update pod status and the pod deletion logic
is failing causing tests to flake.

Ultimately, we call testCtx.CleanUp() which cleans
the nodes and the pods involved the test namespace so
we are not going to leak any resources.

#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

#### Relevant SIG

/sig scheduling

/assign @chendave

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
#### What type of PR is this?

/kind flake
#### What this PR does / why we need it:
Once the node gets deleted, the nodelifecycle controller
is racing to update pod status and the pod deletion logic
is failing causing tests to flake. This commit moves
the testContext creation to within the test loop and deletes nodes,
namespace within the test loop. We don't explicitly call the node
deletion within the loop but the `testutils.CleanupTest(t, testCtx)`
call ensures that the namespace, nodes gets deleted.
#### Which issue(s) this PR fixes:

Fixes #105492

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
cc @Huang-Wei @alculquicondor @chendave

### CODE REVIEW

File: test/integration/scheduler/preemption_test.go [hunk 1]
```diff
@@ -1341,52 +1341,37 @@ func initTestPreferNominatedNode(t *testing.T, nsPrefix string, opts ...schedule
...
-		res  map[v1.ResourceName]string
+	defaultPodRes := &v1.ResourceRequirements{Requests: v1.ResourceList{
+		v1.ResourceCPU:    *resource.NewMilliQuantity(100, resource.DecimalSI),
+		v1.ResourceMemory: *resource.NewQuantity(100, resource.DecimalSI)},
 	}
-
 	tests := []struct {
 		name         string
-		nodes        []*nodeConfig
+		nodeNames    []string
```
Comment (alculquicondor) [inline test/integration/scheduler/preemption_test.go:1356]: It doesn't look like this change was necessary, was it?
