### PR TITLE
Skip terminal Pods with a deletion timestamp from the Daemonset sync

### LINKED ISSUE #118587: DaemonSet does not recreate failed pods when they have deletionTimestamp
/sig apps

When a terminal pod (Failed or Succeeded) has a deletionTimestamp it is ignored by DaemonSet and not recreated, because of this check: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemon_controller.go#L822-L824.

It was observed when working on what was isolated to Kubelet issue, that Kubelet would not force-delete pods in some scenarios: https://github.com/kubernetes/kubernetes/issues/118472. 

The below reproduction steps use the 1.27.2 version with affected kubelet by the bug:

1. create kind cluster using 1.27.2 with config in `kind-config.yaml`

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
```

```sh
kind create cluster --config kind-config.yaml --image kindest/node:v1.27.2
```

2. create daemonset with the following spec:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: issue-daemonset
 namespace: default
spec:
 selector:
   matchLabels:
     name: issue-label
 template:
   metadata:
     labels:
       name: issue-label
   spec:
     os:
       name: "windows"
     containers:
     - name: ubuntu
       image:  gcr.io/google-containers/ubuntu:14.04
       command: ["/bin/sleep"]
       args: ["infinity"]
```
```sh
kubectl create -f ds.yaml
```
Observe the pod is created but marked Failed as non-admissible:
```sh 
kubectl get pods -oyaml
``` 
```sh
  status:
    message: 'Pod was rejected: Failed to admit pod as the OS field doesn''t match
      node OS'
    phase: Failed
    reason: PodOSNotSupported
    startTime: "2023-06-09T09:04:54Z"
```
3. Stop kubelet on the worker node

```sh
docker exec kind-worker systemctl stop kubelet
```
After a while observe that a replacement pod to be created by DS
```sh
kubectl get pods
```
```sh
NAME                    READY   STATUS    RESTARTS   AGE
issue-daemonset-tvrfr   0/1     Pending   0          10s
```
Observe that a replacement pod is created, but remains Pending (as the kubelet is down)

4. Delete the pending pod
```sh
kubectl delete pods/issue-daemonset-tvrfr
```
Observe that the delete hangs as Kubelet is stopped, and the pod is pending.

5. Start Kubelet again 
```sh
docker exec kind-worker systemctl start kubelet
```

Observe, that the pod now transitions to the `Failed` phase, but the delete hangs.

**Issue**: DaemonSet does not recreate a failed pod, because it has the `deletionTimestamp`. 

Note: the behavior is tricky to reproduce on a healthy system, because then the pod is typically force-deleted by Kubelet soon after transitioning to `Failed` phase.

However, it was also suggested as a potential DS issue (see [comment](https://github.com/kubernetes/kubernetes/issues/118472#issuecomment-1579025614)), so opening the ticket to track the discussion.

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

/sig apps

If surge is disabled, the Daemonset currently waits for Pods to fully disappear from the apiserver before creating replacements. However, since k8s 1.22, Pods with a terminal phase (Failed, Succeeded) are guaranteed to not be holding any resources from a Node, and are safe to replace.

By skipping terminal Pods with a deletionTimestamp, the DS controller is able to create replacement Pods in the following scenarios:
- A buggy kubelet or Pod GC that is not able to delete the terminal Pod (example: #118472)
- A pod with finalizers

#### Which issue(s) this PR fixes:

Fixes #118587

#### Does this PR introduce a user-facing change?

```release-note
The Daemonset controller creates replacements for terminal Pods, which can appear during VM preemptions or when using Pod finalizers
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/daemon/daemon_controller_test.go [hunk 1]
```diff
@@ -2778,6 +2785,13 @@ func TestGetNodesToDaemonPods(t *testing.T) {
 			newPod("non-matching-owned-0-", "node-0", simpleDaemonSetLabel2, ds),
 			newPod("non-matching-orphan-1-", "node-1", simpleDaemonSetLabel2, nil),
 			newPod("matching-owned-by-other-0-", "node-0", simpleDaemonSetLabel, ds2),
+			func() *v1.Pod {
```
Comment (mimowo) [inline pkg/controller/daemon/daemon_controller_test.go:2788]: nit: I would suggest adding another `succeeded` pod for symmetry.

File: test/integration/util/util.go [hunk 2]
```diff
@@ -229,17 +231,31 @@ func CleanupTest(t *testing.T, testCtx *TestContext) {
...
-			pod.ObjectMeta.Finalizers = nil
-			_, err = cs.CoreV1().Pods(pod.Namespace).Update(context.TODO(), pod, metav1.UpdateOptions{})
+			t.Errorf("error while removing pod finalizers for %v: %v", klog.KObj(&p), err)
+		} else if pod != nil && len(pod.Finalizers) > 0 {
+			patchBytes, _ := json.Marshal(map[string]interface{}{
+				"metadata": map[string]interface{}{
+					"$deleteFromPrimitiveList/finalizers": pod.Finalizers,
+				},
+			})
+			_, err = cs.CoreV1().Pods(pod.Namespace).Patch(ctx, pod.Name, types.StrategicMergePatchType, patchBytes, metav1.PatchOptions{})
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply test/integration/util/util.go:256]: Because I was getting conflicts. I rewrote this as Patch instead doing retries.

File: pkg/controller/daemon/daemon_controller_test.go [hunk 3]
```diff
@@ -2757,18 +2757,25 @@ func TestGetNodesToDaemonPods(t *testing.T) {
 		if err != nil {
 			t.Fatal(err)
 		}
-		addNodes(manager.nodeStore, 0, 2, nil)
+		addNodes(manager.nodeStore, 0, 4, nil)
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/daemon/daemon_controller_test.go]: Leftover from a previous approach. Reverted.

File: pkg/controller/daemon/daemon_controller_test.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/controller/daemon/daemon_controller_test.go:2788]: added

File: test/integration/daemonset/daemonset_test.go [hunk 4]
```diff
@@ -275,9 +281,7 @@ func validateDaemonSetPodsAndMarkReady(
 ) {
```
Comment (atiratree) [inline test/integration/daemonset/daemonset_test.go:281]: might be worth it to pass and verify the number of expected terminalPods

File: pkg/controller/daemon/daemon_controller.go [hunk 5]
```diff
@@ -761,6 +761,12 @@ func (dsc *DaemonSetsController) getNodesToDaemonPods(ctx context.Context, ds *a
 	nodeToDaemonPods := make(map[string][]*v1.Pod)
 	logger := klog.FromContext(ctx)
 	for _, pod := range claimedPods {
+		if podutil.IsPodTerminal(pod) && pod.DeletionTimestamp != nil {
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/daemon/daemon_controller.go:764]: I'm not sure what are the alternatives you are suggesting.

A pod with a terminal phase (Succeeded or Failed) is not consuming any resources and is guranteed not to be restarted by kubelet anymore. It's as if the Pod no longer exists.

What could be the effect of keeping the label?

File: test/integration/daemonset/daemonset_test.go (hunk 4 above)
Comment (alculquicondor) [reply test/integration/daemonset/daemonset_test.go:281]: I don't think so. The controller should treat those pods as if they no longer exist. No point in checking how many there are IMO.

File: pkg/controller/daemon/daemon_controller.go [hunk 6]
```diff
@@ -761,6 +761,12 @@ func (dsc *DaemonSetsController) getNodesToDaemonPods(ctx context.Context, ds *a
...
+			// This Pod has a finalizer or is already scheduled for deletion by the
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/daemon/daemon_controller.go:765]: Done

File: pkg/controller/daemon/daemon_controller.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (atiratree) [reply pkg/controller/daemon/daemon_controller.go:764]: If the pod cannot be removed from etcd store for any reason, then the user can manually rollback to the old revision and resolve the finalizers and the semantics behind it. The finalizer might be set by other component(not owned by the user) and can signal holding of external resources. 

It is a very specific scenario, but It might be safer to keep the revision in case somebody needs it. Once the problematic pod is removed, the controller revision will be removed.

File: test/integration/daemonset/daemonset_test.go (hunk 4 above)
Comment (atiratree) [reply test/integration/daemonset/daemonset_test.go:281]: Yeah, there is no real need, since we are marking the pods as terminal. It would just make the intent of the assert function clearer.

Comment (alculquicondor) [reply test/integration/daemonset/daemonset_test.go:281]: I prefer to keep the diff as small as possible for cherry-picking purposes.

File: pkg/controller/daemon/daemon_controller.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/daemon/daemon_controller.go]: Added a boolean to the function so that these pods can be considered in the history.

File: test/integration/daemonset/daemonset_test.go (hunk 4 above)
Comment (atiratree) [reply test/integration/daemonset/daemonset_test.go:281]: ok

**Review by soltysh — APPROVED** [review]
/approve

**Comment by alculquicondor** [comment]
Cherry-picks:

1.27: #118911
1.26: #118912

I don't plan to cherry-pick below this version, given that it would depend on #118912, which we decided to only cherry-pick to 1.26
