### PR TITLE
Fix federated-image.tag written with empty string

### LINKED ISSUE #34575: federation-up is broken
It fails with:
```
error: yaml: line 17: mapping values are not allowed in this context
```

cc @kubernetes/sig-cluster-federation

### PR DESCRIPTION
**Pull request by shashidharatd**
**What this PR does / why we need it**: Fix federation-up

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #34575

**Special notes for your reviewer**: This issue is happening because there is no kubectl available now when we are trying to write federated-image.tag file. Instead of using kubectl we can use KUBE_GIT_VERSION to get the version.

**Release note**: `NONE`

``` release-note
```

@nikhiljindal @madhusudancs @colhom

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34898)

### CODE REVIEW

File: build/util.sh [hunk 1]
```diff
@@ -23,8 +23,15 @@ function kube::release::semantic_version() {
   # Client Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.2328+3c0a05de4a38e3", GitCommit:"3c0a05de4a38e355d147dbfb4d85bad6d2d73bb9", GitTreeState:"clean"}
   # and spits back the GitVersion piece in a way that is somewhat
   # resilient to the other fields changing (we hope)
-  ${KUBE_ROOT}/cluster/kubectl.sh version --client | sed "s/, */\\
-/g" | egrep "^GitVersion:" | cut -f2 -d: | cut -f2 -d\"
+  local GIT_VERSION=$(${KUBE_ROOT}/cluster/kubectl.sh version --client | sed "s/, */\\
+/g" | egrep "^GitVersion:" | cut -f2 -d: | cut -f2 -d\")
+
+  # In case kubectl not available
+  if [[ -z ${GIT_VERSION} ]]; then
```
Comment (madhusudancs) [inline build/util.sh]: @shashidharatd I have two concerns about this change.

1. Where are we calling this function before building `kubectl`? Shouldn't we fix the caller to have a `kubectl` built instead fixing it here?
2. Who supplies `$KUBE_GIT_VERSION`? In other words, what guarantees that it is set and it is set to the right values?

File: build/release.sh [hunk 2]
```diff
@@ -40,6 +40,8 @@ if [[ $KUBE_RELEASE_RUN_TESTS =~ ^[yY]$ ]]; then
   kube::build::run_build_command make test-integration
 fi
 
+kube::build::copy_output
```
Comment (madhusudancs) [inline build/release.sh]: @shashidharatd this looks reasonable to me.

Not entirely sure who is the right person to ping here for a final sanity check. 
@david-mcmahon, @jbeda could you please take a look at this or point to the right people?

**Comment by quinton-hoole** [comment]
Hopefully this will also fix #34898 
@ixdy , @colhom are you able to review this PR?  I don't know those bash scripts well enough to know whether this is the best way to fix the problem.

**Comment by colhom** [comment]
LGTM from me - That conditional block which writes the `federated-image.tag` file should have been between `copy-output` and `package-tarballs` all along. (I'm to blame for putting that block there in the first place). It relies on an output file from `copy-output` (kubectl), and produces a file which `package-tarballs` consumes (federated-image.tag).

Sanity rationale- If you look at the [kube::build::copy_output](https://github.com/kubernetes/kubernetes/blob/master/build/common.sh#L686) function, the only thing it is doing is selectively rsync'ing files from one location to another. (One of which is the `kubectl` binary).

**Review by ixdy — APPROVED** [review]

**Review by zmerlynn — APPROVED** [review]

**Comment by david-mcmahon** [comment]
LGTM

**Comment by madhusudancs** [comment]
@k8s-bot ok to test

**Comment by nikhiljindal** [comment]
@k8s-bot federation gce e2e test this
