### PR TITLE
Use rsync to probe for rsync ready

### LINKED ISSUE #34214: e2e flake: "Syncing sources to container" failed in PR builder
```
+++ [1006 00:35:19] Syncing sources to container
rsync: safe_read failed to read 1 bytes [sender]: Connection reset by peer (104)
rsync error: error in rsync protocol data stream (code 12) at io.c(276) [sender=3.1.1]
Makefile:239: recipe for target 'release' failed
make: *** [release] Error 1
Build step 'Execute shell' marked build as failure
```

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/34082/kubernetes-pull-build-test-e2e-gce/61951/

@kubernetes/test-infra-maintainers

### PR DESCRIPTION
**Pull request by jbeda**
We were using netcat to try and figure out when the rsync container is ready. Now we instead use rsync itself. I suspect that there was a race condition with some versions of Docker where it would accept connections and then close them during container start.

This fixes #34214 (I think)

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34257)

### CODE REVIEW

File: build/common.sh [hunk 1]
```diff
@@ -637,13 +625,13 @@ function kube::build::start_rsyncd_container() {
   # machines) we have to talk directly to the container IP.  There is no one
   # strategy that works in all cases so we test to figure out which situation we
   # are in.
-  if kube::build::probe_address 127.0.0.1 ${mapped_port}; then
+  if kube::build::rsync_probe 127.0.0.1 ${mapped_port}; then
     KUBE_RSYNC_ADDR="127.0.0.1:${mapped_port}"
-    sleep 0.5
+    #sleep 0.5
```
Comment (ixdy) [inline build/common.sh]: maybe just remove?

File: build/common.sh [hunk 2]
```diff
@@ -582,29 +582,17 @@ function kube::build::run_build_command_ex() {
...
+  local tries=20
   while (( ${tries} > 0 )) ; do
-    if ${netcat} -z "$1" "$2" 2> /dev/null ; then
+    if rsync "rsync://k8s@${1}:${2}/" \
+         --password-file="${LOCAL_OUTPUT_BUILD_CONTEXT}/rsyncd.password" \
+         &> /dev/null ; then
       return 0
     fi
     tries=$(( ${tries} - 1))
+    echo "."
```
Comment (ixdy) [inline build/common.sh]: maybe first echo "Waiting for rsync daemon"?

Comment (jbeda) [inline build/common.sh]: I'll just remove it.

**Comment by jbeda** [comment]
PTAL

File: build/common.sh [hunk 3]
```diff
@@ -582,26 +582,13 @@ function kube::build::run_build_command_ex() {
...
-    V=6 kube::log::info "netcat not installed, waiting for 1s"
-    sleep 1
-    return 0
-  fi
-
-  local tries=10
+  local tries=20
   while (( ${tries} > 0 )) ; do
-    if ${netcat} -z "$1" "$2" 2> /dev/null ; then
+    if rsync "rsync://k8s@${1}:${2}/" \
```
Comment (ixdy) [inline build/common.sh]: should there be a sleep between attempts?

Comment (jbeda) [inline build/common.sh]: There is -- we do 20 tries with a 0.1s sleep between each attempt.  The rsync command line is broken over a couple of lines so that might be confusing.

Comment (ixdy) [inline build/common.sh]: oh, github was hiding the sleep.

**Review by ixdy — APPROVED** [review]
