### PR TITLE
Use gsutil to upload test artifacts and console log to GCS

### LINKED ISSUE #13548: Uploading logs to GCS may break the whole run on Jenkins
In our scalability tests it sometimes happens that all tests are passing, but the run is marked red as "failure". This is because uploading logs to GCS sometimes failed with error:

    ---
    [Google Cloud Storage Uploader] Uploading: _artifacts/146.148.94.88:22-kubelet.log
    ERROR: [Google Cloud Storage Uploader] Exception while uploading files: exception uploading file

I've seen 2 examples during last 24 hours:
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/2319/
http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce-scalability/2325/

For now it's just misleading.

However, since scalability suite is now pretty stable, I would like to add it to list of projects that our merge bot requires to be green to merge anything. Unfortunately this looks like a blocker for it.

 Any thoughts how to fix that?

cc @kubernetes/goog-testing @quinton-hoole @ixdy

### PR DESCRIPTION
**Pull request by ixdy**
Automatically upload the console log and test artifacts and set a "latest build" file in GCS for all gce and gke-ci builds. At least partway fixes #13548.

This currently only supports the post-submit Jenkins projects; I need to figure out the best way to trigger this if something fails in build.sh as well.

### CODE REVIEW

**Comment by ixdy** [comment]
Should be ready for review now. @kubernetes/goog-testing

**Comment by ixdy** [comment]
https://goto.google.com/prkubekins/job/kubernetes-pull-build-test-e2e-gce/9925/ is a run where it actually uploaded things.

File: hack/jenkins/e2e.sh [hunk 1]
```diff
@@ -430,6 +469,8 @@ case ${JOB_NAME} in
           ${GCE_DEFAULT_SKIP_TESTS[@]:+${GCE_DEFAULT_SKIP_TESTS[@]}} \
           ${GCE_FLAKY_TESTS[@]:+${GCE_FLAKY_TESTS[@]}} \
           )"}
+    : ${JENKINS_GCS_LOGS_PATH:="gs://kubernetes-jenkins/logs"}
```
Comment (lavalamp) [inline hack/jenkins/e2e.sh]: Why don't we want this on for all of the tests?

File: hack/jenkins/e2e.sh [hunk 2]
```diff
@@ -28,6 +28,36 @@ set -o nounset
...
+    fi
+    local -r gcs_job_path="${JENKINS_GCS_LOGS_PATH}/${JOB_NAME}"
+    local -r gcs_build_path="${gcs_job_path}/${BUILD_NUMBER}"
+    local -r gcs_acl="public-read"
+    echo "Uploading to ${gcs_build_path}"
+    if [[ -n "${ARTIFACTS:-}" ]]; then
+      gsutil -m -q -o "GSUtil:use_magicfile=True" cp -a "${gcs_acl}" -r -c \
+        -z log,txt,xml "${ARTIFACTS}" "${gcs_build_path}/artifacts" || true
+    fi
+    # Remove ANSI escape sequences from the console log before uploading.
```
Comment (lavalamp) [inline hack/jenkins/e2e.sh]: I thought there was a setting to not output these in the first place-- can we turn that on instead?

File: hack/jenkins/e2e.sh [hunk 3]
```diff
@@ -28,6 +28,36 @@ set -o nounset
...
+    if [[ ! ${JENKINS_UPLOAD_TO_GCS:-} =~ ^[yY]$ ]]; then
+        return
+    fi
+    local -r gcs_job_path="${JENKINS_GCS_LOGS_PATH}/${JOB_NAME}"
+    local -r gcs_build_path="${gcs_job_path}/${BUILD_NUMBER}"
+    local -r gcs_acl="public-read"
+    echo "Uploading to ${gcs_build_path}"
+    if [[ -n "${ARTIFACTS:-}" ]]; then
+      gsutil -m -q -o "GSUtil:use_magicfile=True" cp -a "${gcs_acl}" -r -c \
+        -z log,txt,xml "${ARTIFACTS}" "${gcs_build_path}/artifacts" || true
```
Comment (lavalamp) [inline hack/jenkins/e2e.sh]: concerned about the || true, seems like we will have a hard time noticing if we skip things?

Comment (quinton-hoole) [inline hack/jenkins/e2e.sh]: See also https://github.com/kubernetes/kubernetes/issues/7778

Comment (ixdy) [inline hack/jenkins/e2e.sh]: This was intentional - we don't want failing gsutil uploads to fail the entire test run; see #13548.

**Comment by quinton-hoole** [comment]
@ixdy Needs a rebase.

File: hack/jenkins/e2e.sh (hunk 1 above)
Comment (ixdy) [inline hack/jenkins/e2e.sh]: wasn't sure if we also wanted all GKE builds uploaded, but I guess it's harmless enough.

File: hack/jenkins/e2e.sh (hunk 2 above)
Comment (ixdy) [inline hack/jenkins/e2e.sh]: we have a plugin which renders the colors on Jenkins, which is kinda nice.

File: hack/jenkins/e2e.sh (hunk 3 above)
Comment (ixdy) [inline hack/jenkins/e2e.sh]: added a comment noting such

**Comment by ixdy** [comment]
rebased and comments addressed, PTAL

**Comment by ixdy** [comment]
Actually, I may have a way of making this work for all of our builds, not just those that call e2e.sh. Standby for updates...

**Comment by ixdy** [comment]
OK, I've updated this PR with a new script rather than changing e2e.sh.

The basic usage is that we add another (series of) command(s) to all of the Jenkins jobs:
```shell
mkdir -p _tmp/ && curl -fsS --retry 3 -o _tmp/upload-to-gcs.sh "https://raw.githubusercontent.com/kubernetes/kubernetes/master/hack/jenkins/upload-to-gcs.sh" && source _tmp/upload-to-gcs.sh
```

Basically, we download this script and source it into the bash session running the test commands. This creates the function and installs a trap to automatically upload logs to GCS on exit.

We can thus use this with all of the Jenkins jobs, not just those running e2e.sh.

I also fixed the git commit environment variable.

**Comment by ixdy** [comment]
@k8s-bot test this please

**Comment by ixdy** [comment]
Improvements this has over the GCS Jenkins plugin:
* all files are gzipped before upload, which means they upload faster and use less space on GCS. (They're transparently unzipped when downloaded.)
* artifacts are uploaded in parallel rather than serially (should be faster esp. for builds like the scalability project)
* all files get a proper content-type set, rather than using the generic default
* all files can be viewed directly in the browser, rather than having to be downloaded first (e.g. compare [build-log.txt](https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/pr-logs/7c3434eca324bd212214cfae865209f488981d41/kubernetes-pull-build-test-e2e-gce/11816/build-log.txt), uploaded by the Jenkins plugin, vs [console-log.txt](https://pantheon.corp.google.com/m/cloudstorage/b/kubernetes-jenkins/o/pr-logs/7c3434eca324bd212214cfae865209f488981d41/kubernetes-pull-build-test-e2e-gce/11816/console-log.txt), uploaded by this script)
* the latest-build.txt file can be watched by other jobs to determine when a new build has completed

**Comment by wojtek-t** [comment]
Nice - waiting for this to be in.

File: hack/jenkins/upload-to-gcs.sh [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+    if [[ ! ${JENKINS_UPLOAD_TO_GCS:-} =~ ^[yY]$ ]]; then
+        return
+    fi
+    local -r artifacts_path="${WORKSPACE}/_artifacts"
+    local -r gcs_job_path="${JENKINS_GCS_LOGS_PATH}/${JOB_NAME}"
+    local -r gcs_build_path="${gcs_job_path}/${BUILD_NUMBER}"
+    local -r gcs_acl="public-read"
+    echo "Uploading to ${gcs_build_path}"
+    if [[ -d "${artifacts_path}" ]]; then
+      gsutil -m -q -o "GSUtil:use_magicfile=True" cp -a "${gcs_acl}" -r -c \
```
Comment (wojtek-t) [inline hack/jenkins/upload-to-gcs.sh]: Can we retry uploading in case of failure (e.g. 3 times)? This will make it more robust.

Same in other places.

File: hack/jenkins/upload-to-gcs.sh [hunk 5]
```diff
@@ -0,0 +1,75 @@
...
+  : ${JENKINS_GCS_LOGS_PATH:="gs://kubernetes-jenkins/logs"}
+fi
+
+: ${JENKINS_UPLOAD_TO_GCS:="y"}
+
+# Upload the build log and all test artifacts (under _artifacts) to GCS when
+# JENKINS_UPLOAD_TO_GCS is set to y.
+# We intentionally ignore gsutil errors since we don't want failed uploads to
+# fail the entire test run (#13548).
+function upload_logs_to_gcs() {
```
Comment (wojtek-t) [inline hack/jenkins/upload-to-gcs.sh]: is this references from somewhere?

Comment (krousey) [inline hack/jenkins/upload-to-gcs.sh]: Referenced in the trap command at the bottom. Jenkins will source this in and that trap command will execute it. See https://github.com/kubernetes/kubernetes/pull/14454#issuecomment-146390939 for more details.

**Comment by krousey** [comment]
@ixdy This looks good to me (as far as bash looks good). Care to comment on https://github.com/kubernetes/kubernetes/pull/14454#discussion_r41750878 ?

File: hack/jenkins/upload-to-gcs.sh (hunk 4 above)
Comment (ixdy) [inline hack/jenkins/upload-to-gcs.sh]: added retry loop. waiting for kubernetes-test-go to run again to see if it worked.

**Comment by krousey** [comment]
@ixdy This gets my LGTM. Feel free to add it when you're satisfied with the test results.

File: hack/jenkins/upload-to-gcs.sh [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+    {
+      echo "BUILD_NUMBER=${BUILD_NUMBER}"
+      echo "GIT_COMMIT=${GIT_COMMIT:-}"
+    } | gsutil -q -h "Content-Type:text/plain" -h "Cache-Control:private, max-age=0, no-transform" \
+      cp -a "${gcs_acl}" - "${gcs_job_path}/latest-build.txt" || continue
+    break  # all uploads succeeded if we hit this point
+  done
+}
+
+
```
Comment (wojtek-t) [inline hack/jenkins/upload-to-gcs.sh]: nit: remove one empty line

**Comment by wojtek-t** [comment]
lgtm

File: hack/jenkins/upload-to-gcs.sh (hunk 6 above)
Comment (ixdy) [inline hack/jenkins/upload-to-gcs.sh]: done

**Comment by ixdy** [comment]
After updating the Jenkins job to actually download from the correct branch (oops), it seems to be working correctly.

**Comment by ixdy** [comment]
self-added lgtm label per @krousey in https://github.com/kubernetes/kubernetes/pull/14454#issuecomment-148226816
