### PR TITLE
Fix rc scaler watch

### LINKED ISSUE #30469: [k8s.io] Load capacity [Feature:Performance] should be able to handle 30 pods per node {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-scalability/10044/

Failed: [k8s.io] Load capacity [Feature:Performance] should be able to handle 30 pods per node {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:197
creating rc load-small-rc-259
Expected error:
    <*errors.errorString | 0xc822827f30>: {
        s: "Error creating replication controller: Post https://104.154.115.112/api/v1/namespaces/e2e-tests-load-30-nodepods-1-gvc33/replicationcontrollers: net/http: TLS handshake timeout",
    }
    Error creating replication controller: Post https://104.154.115.112/api/v1/namespaces/e2e-tests-load-30-nodepods-1-gvc33/replicationcontrollers: net/http: TLS handshake timeout
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:297
```

Previous issues for this test: #26544 #26938 #27595 #30146

### LINKED ISSUE #30990: Pods from ReplicationController are sometimes not removed
I'm currently debugging failures from scalability suite.

It basically started failing on this run:
http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-e2e-gce-scalability/10148/

This suite is running WITHOUT garbage collector.

There are tens of failures like this one:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:197 deleting rc load-small-rc-46 Expected error: <*errors.errorString | 0xc8275da7c0>: { s: "error while waiting for pods to become inactive load-small-rc-46: timed out waiting for the condition", } error while waiting for pods to become inactive load-small-rc-46: timed out waiting for the condition not to have occurred /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:345
```

I'm also able to reproduce this problem from head on my local 100-node cluster.

We did some debugging of it and it seems that because of some reason, pods from some replication controllers are simply not being removed.
What happens is that:
1. we call: DeleteRCAndPods https://github.com/kubernetes/kubernetes/blob/master/test/e2e/load.go#L345
2. This should result in:
- scaling RC to 0
- waiting until all pods are gone
- removing replication controller

However, what happens (looking into logs) is that the first two doesn't happen, but replication controller is indeed removed. From RC logs (from some run):
```
I0819 11:12:44.621239       7 replication_controller.go:585] Finished syncing controller "e2e-tests-load-30-nodepods-1-ikyk3/load-small-rc-226" (5.195731ms)
I0819 11:17:30.168494       7 replication_controller.go:598] Replication Controller has been deleted e2e-tests-load-30-nodepods-1-ikyk3/load-small-rc-226
I0819 11:17:30.168508       7 replication_controller.go:585] Finished syncing controller "e2e-tests-load-30-nodepods-1-ikyk3/load-small-rc-226" (16.194�s)
```

The timing when it started happening matches exactly merge of #30670, but I don't know how this can affect it.

@caesarxuchao @lavalamp @gmarek 

http://kubekins.dls.corp.google.com:8080/view/Scalability/job/kubernetes-e2e-gce-scalability/10148/ is the good run to start debugging with

### PR DESCRIPTION
**Pull request by caesarxuchao**
**What this PR does / why we need it**:
The RC scaler uses Watch to monitor if the RC is scaled. The Watch was sent with resourceVersion=0, so the watch event it gets back starts from any point in the history, so the result is not valid.

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #

Probably will fix #30990
Fix #30469

**Special notes for your reviewer**:

This breaks the load test because the reaper doesn't actually wait until all the pods are gone before it deletes the RC.

I haven't run the node-100 test myself to verify it fixes the problem though.

cc @deads2k @smarterclayton @lavalamp

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31051)

### CODE REVIEW

File: pkg/kubectl/scale.go [hunk 1]
```diff
@@ -177,7 +177,11 @@ func (scaler *ReplicationControllerScaler) Scale(namespace, name string, newSize
 		return err
 	}
 	if waitForReplicas != nil {
-		watchOptions := api.ListOptions{FieldSelector: fields.OneTermEqualSelector("metadata.name", name), ResourceVersion: "0"}
+		latestRC, err := scaler.c.ReplicationControllers(namespace).Get(name)
```
Comment (caesarxuchao) [inline pkg/kubectl/scale.go]: Instead of issuing an extra Get, I can plumb the updated RC from ScaleCondition and ScaleSimple if the reviewers think it matters.

Comment (smarterclayton) [inline pkg/kubectl/scale.go]: That's probably the other reason - someone wanted to avoid making two calls.  I don't think the Get is a problem.

Comment (bprashanth) [inline pkg/kubectl/scale.go]: the way this function is written, it just guarantees that rc becomes stable, not that it stabilizes for this scale update. 
This get might be after the rc manager updates status with what you want. To actually see your update result you need to watch from the rv of your update (if you updated rv from 10->11, watch at 11). This still doesn't guarantee that you see *your* update result, because the rc manager could batch updates (i.e rv 11 is your update of replicas from 10 to 11, rv 12 is another update of replicas to 2000, rc manager can squash 11 and 2000 and start scaling to 2000 which you end up waiting for)

Comment (caesarxuchao) [inline pkg/kubectl/scale.go]: Agree. @bprashanth how about changing the polling condition like this:
``` go
if rc.Spec.Replicas != newSize {
    // the size is changed by other party, we don't need to wait for the change to complete.
    return true, nil
}
return rc.Status.ObservedGeneration >= rc.Generation && rc.Status.Replicas == rc.Spec.Replicas, nil
```

Comment (wojtek-t) [inline pkg/kubectl/scale.go]: Yeah - that SGTM.

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
Actually, this shouldn't help at all in my opinion.

Watch with RV=0 will return the initial version of the object:
1. This is what is called:
https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/cacher.go#L268
2. For initial events we call this:
https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/cacher.go#L283
3. Which in turn goes to this branch:
https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/watch_cache.go#L292

This means, that watch with RV=0 will work correctly.

So I'm pretty sure, this PR will not help at all.

@smarterclayton @caesarxuchao - thoughts?

**Comment by deads2k** [comment]
> This means, that watch with RV=0 will work correctly.
> 
> So I'm pretty sure, this PR will not help at all.
> 
> @smarterclayton @caesarxuchao - thoughts?

I think the watch is correct, but I'm ok with changing the condition to watch for stability based on generation.  Seems like the scaler still needs to return the object it updated though.  Otherwise the `.Get` could get the wrong generation.

**Comment by wojtek-t** [comment]
Actually, what I wrote above is correct, but is unrelated to the problem. I misread the code in scaler and I though that we are comparing generation of RC with the expected version (not with the one from the object).

So actually, I think that it will fix the problem.

Sorry, for confusion.

**Comment by caesarxuchao** [comment]
@deads2k FYI, my understanding of `RV=0` is that the watchCache will start serving from the resourceVersion that's currently in its store, which might have a delay from API server's resourceVersion. So you might get a peek into history if you start your watch with RV=0. So the scaler might observe a stable state of RC in the past, and mistakenly stops waiting. I think @wojtek-t agreed with this at last (judging by his last comment).

**Comment by wojtek-t** [comment]
Yup - initially I thought that the fact that with RV=0 we deliver additionally "current state from we start watching" as the first "Add" event matter, but it actually doesn't. So yeah - I agree that this fix should help.

**Comment by deads2k** [comment]
> So you might get a peek into history if you start your watch with RV=0. So the scaler might observe a stable state of RC in the past, and mistakenly stops waiting.

ok

**Comment by caesarxuchao** [comment]
```
FAIL!
Get rc {{range.items}}{{.metadata.name}}:{{end}}
  Expected: 
  Got:      busybox1:
(B
1361 hack/make-rules/test-cmd.sh
(B
```

This looks like a test flake. The RC from a previous test is not deleted. The flake shouldn't be caused by this change, because I only changed the scale logic which should only affect the pods.

**Comment by caesarxuchao** [comment]
@k8s-bot unit test this, issue #IGNORE

**Comment by wojtek-t** [comment]
@caesarxuchao - it seems that this happened again, so maybe it's related?

**Comment by caesarxuchao** [comment]
Yeah, I'll take another look.

**Comment by caesarxuchao** [comment]
I think the test fails because there is no event coming through the watch channel after the Get(). We do need to record the RV returned the Update().

File: pkg/kubectl/scale.go [hunk 2]
```diff
@@ -41,7 +41,7 @@ type Scaler interface {
 	Scale(namespace, name string, newSize uint, preconditions *ScalePrecondition, retry, wait *RetryParams) error
 	// ScaleSimple does a simple one-shot attempt at scaling - not useful on its own, but
 	// a necessary building block for Scale
-	ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) error
+	ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) (updatedResourceVersion string, err error)
```
Comment (wojtek-t) [inline pkg/kubectl/scale.go]: nit: please make results unnamed

File: pkg/kubectl/scale.go [hunk 3]
```diff
@@ -155,24 +158,25 @@ type ReplicationControllerScaler struct {
 	c client.Interface
 }
 
-func (scaler *ReplicationControllerScaler) ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) error {
+func (scaler *ReplicationControllerScaler) ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) (updatedResourceVersion string, err error) {
```
Comment (wojtek-t) [inline pkg/kubectl/scale.go]: nit: please make results unnamed

File: pkg/kubectl/scale.go [hunk 4]
```diff
@@ -227,24 +236,25 @@ type ReplicaSetScaler struct {
 	c client.ExtensionsInterface
 }
 
-func (scaler *ReplicaSetScaler) ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) error {
+func (scaler *ReplicaSetScaler) ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) (updatedResourceVersion string, err error) {
```
Comment (wojtek-t) [inline pkg/kubectl/scale.go]: nit: please make results unnamed

File: pkg/kubectl/scale.go [hunk 5]
```diff
@@ -294,24 +305,25 @@ type PetSetScaler struct {
 	c client.AppsInterface
 }
 
-func (scaler *PetSetScaler) ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) error {
+func (scaler *PetSetScaler) ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) (updatedResourceVersion string, err error) {
```
Comment (wojtek-t) [inline pkg/kubectl/scale.go]: nit: please make results unnamed

File: pkg/kubectl/scale.go [hunk 6]
```diff
@@ -345,25 +357,26 @@ type JobScaler struct {
 }
 
 // ScaleSimple is responsible for updating job's parallelism.
-func (scaler *JobScaler) ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) error {
+func (scaler *JobScaler) ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) (updatedResourceVersion string, err error) {
```
Comment (wojtek-t) [inline pkg/kubectl/scale.go]: nit: please make results unnamed

File: pkg/kubectl/scale.go [hunk 7]
```diff
@@ -411,27 +424,28 @@ type DeploymentScaler struct {
 }
 
 // ScaleSimple is responsible for updating a deployment's desired replicas count.
-func (scaler *DeploymentScaler) ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) error {
+func (scaler *DeploymentScaler) ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) (updatedResourceVersion string, err error) {
```
Comment (wojtek-t) [inline pkg/kubectl/scale.go]: nit: please make results unnamed

**Comment by wojtek-t** [comment]
Minor comments - other than that LGTM.

File: pkg/kubectl/scale.go (hunk 7 above)
Comment (lavalamp) [inline pkg/kubectl/scale.go]: I really disagree with this comment, actually. named return parameters are
self-documenting. No one is going to expect this to be a resource version
unless we make it a type (ideal, but too much work for this PR) or name it.

File: pkg/kubectl/scale.go [hunk 8]
```diff
@@ -41,7 +41,7 @@ type Scaler interface {
 	Scale(namespace, name string, newSize uint, preconditions *ScalePrecondition, retry, wait *RetryParams) error
 	// ScaleSimple does a simple one-shot attempt at scaling - not useful on its own, but
 	// a necessary building block for Scale
-	ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) error
+	ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) (string, error)
```
Comment (lavalamp) [inline pkg/kubectl/scale.go]: At the very least you need to name the return parameters here in the interface, where people will be looking for documentation!

**Comment by deads2k** [comment]
> I really disagree with this comment, actually. named return parameters are
> self-documenting. No one is going to expect this to be a resource version
> unless we make it a type (ideal, but too much work for this PR) or name it.

How about naming it in the interface, but not the impls?  That way people still get the benefit from things like content assist, but we don't get the accidental silent returns that come with named return values?

**Comment by wojtek-t** [comment]
>
How about naming it in the interface, but not the impls? That way people still get the benefit from things like content assist, but we don't get the accidental silent returns that come with named return values?

+100

**Comment by lavalamp** [comment]
I really don't think the bare returns are a big problem, either. But even
if you hate them, it's easy to name your return parameters and not use bare
returns...

**Comment by caesarxuchao** [comment]
> it's easy to name your return parameters and not use bare returns...

I think their point is the compiler won't help you if you use named return parameters.

**Comment by lavalamp** [comment]
I think I differ in that I think it's not hard to avoid the error without
the compiler's help.

**Comment by wojtek-t** [comment]
>
I think I differ in that I think it's not hard to avoid the error without
the compiler's help.

I think it's pretty easy - I did such mistake at least once, and fixed at least 2-3 of them in the past.

**Comment by caesarxuchao** [comment]
I think we should discourage silent return all the time. Can we keep the named results as they are this time? I do sympathize with @lavalamp's readability call, and there is no silent return in this PR.

**Comment by lavalamp** [comment]
This LGTM. I'm ok with removing the named parameters from the implementations if @wojtek-t really feels strongly but please leave them in the interface definition.

**Comment by wojtek-t** [comment]
I agree with the argument for having named parameters in the interface - yes, that makes perfect sense.

>
I do sympathize with @lavalamp's readability call, and there is no silent return in this PR.

I don't really agree with that. I think that most of such errors appear when someone comes and changes the existing function by adding a new return somewhere. It's pretty easy to miss such "silent return" then...

**Comment by wojtek-t** [comment]
@caesarxuchao - also note, that you are completely not using those names (other than for the documentation purposes). That's why I think that we should leave them only in the interface (and potentially add comments to implementations what do they return).

File: pkg/kubectl/scale.go [hunk 9]
```diff
@@ -155,24 +158,27 @@ type ReplicationControllerScaler struct {
 	c client.Interface
 }
 
-func (scaler *ReplicationControllerScaler) ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) error {
+// ScaleSimple does a simple one-shot attempt at scaling. It returns the
+// resourceVersion of the replication controller if the update is successful.
+func (scaler *ReplicationControllerScaler) ScaleSimple(namespace, name string, preconditions *ScalePrecondition, newSize uint) (string, error) {
```
Comment (caesarxuchao) [inline pkg/kubectl/scale.go]: @wojtek-t I removed the name of the output parameter and added the comment. PTAL. Thanks.

**Comment by wojtek-t** [comment]
@caesarxuchao - thanks a lot!!! LGTM

**Comment by wojtek-t** [comment]
I'm afraid this PR actually made things worse - see what is happening in: #31374 

I will try to look deeper into it

**Comment by wojtek-t** [comment]
It seems to be related to some special case, when we are calling "scale" with existing number of replicas. Looking into it - hopefully will debug in with next hour or so.

**Comment by caesarxuchao** [comment]
I took a quick look and didn't find any clue. I'll dig into it tomorrow if it's still there.

**Comment by wojtek-t** [comment]
@caesarxuchao - ok, so I understand the issue. The problem is that:
- we call scale from X replicas to X replicas (i.e. the without changing the number of replicas)
- that's doesn't result in any call to etcd (because object doesn't change), and thus we return RV of an object existing in etcd as the RV:
https://github.com/kubernetes/kubernetes/blob/master/pkg/storage/etcd/etcd_helper.go#L518
- as a result:
a) in some cases we get "Error too old" from watch, which in turn results in closing watch channel, which then results with "timed out waiting for %q to be synced" error
b) in other cases, we don't get any updates on RC (because there is no work to be done for RC and it doesn't change), which then results in exactly the same error

**Comment by wojtek-t** [comment]
I will try to send some PR to fix it.

**Comment by wojtek-t** [comment]
@caesarxuchao the PR #31421 seems to fix the problem (for now scalability seems to be back to green, but when I was running it locally, it seemed to work for me)

**Comment by caesarxuchao** [comment]
> a) in some cases we get "Error too old" from watch, which in turn results in closing watch channel, which then results with "timed out waiting for %q to be synced" error

@wojtek-t I don't follow this. Why would we get "error too old" if the listOptions.RV is set to the latest RV?

**Comment by wojtek-t** [comment]
>
@wojtek-t I don't follow this. Why would we get "error too old" if the listOptions.RV is set to the latest RV?

because if we don't update the object, the previous update (which we return in case of no-op update) can potentially be far in the past.

**Comment by caesarxuchao** [comment]
Yes, thanks for the explanation!

**Comment by lavalamp** [comment]
If needed, can get around that by doing a list with a field selector for
metadata.name. The list wrapper will give you an RV that is up-to-date and
watchable.

**Comment by wojtek-t** [comment]
I already fixed it. The bigger problem here was (b) (too old resource version was happening only from time to time). For to fix (b) calling watch actually won't work anyway.
