### PR TITLE
Ignore error when getting api-resources until it's ready

### LINKED ISSUE #113677: [Flake] test-cmd: run_kubectl_server_side_apply_tests
### Which jobs are flaking?

pull-kubernetes-integration: https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&include-filter-by-regex=%5BAa%5Dpply

ci-kubernetes-integration-master: https://testgrid.k8s.io/sig-release-master-blocking#integration-master&include-filter-by-regex=[Aa]pply&width=5

### Which tests are flaking?

run_kubectl_server_side_apply_tests

### Since when has it been flaking?

Unclear, shows up in flakes in triage history as far back as it goes

### Testgrid link

_No response_

### Reason for failure (if possible)

```
Apply failed with 1 conflict: conflict with "kubectl-client-side-apply" using v1: .metadata.labels.name
Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the apply
  command with the `--force-conflicts` flag.
* If you do not intend to manage all of the fields, please edit your
  manifest to remove references to the fields that should keep their
  current managers.
* You may co-own fields by updating your manifest to match the existing
  value; in this case, you'll become the manager if the other manager(s)
  stop managing the field (remove it from their configuration).
See https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts
error: unable to retrieve the complete list of server APIs: mygroup.example.com/v1alpha1: the server could not find the requested resource
```

### Anything else we need to know?

https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=conflict%20with%20%22kubectl-client-side-apply%22%20using%20v1%3A%20.metadata.labels.name

Representative failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107531/pull-kubernetes-integration/1589519927906144256

### Relevant SIG(s)

/sig api-machinery

/cc @apelisse

### PR DESCRIPTION
**Pull request by apelisse**
#### What type of PR is this?
/kind flake

#### Which issue(s) this PR fixes:
Fixes #113677

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
> /retest-required

`/retest` would be enough for such a scenario. `/retest-required` will re-run all tests and some already succeed.

**Comment by ardaguclu** [comment]
> > /retest-required
> 
> `/retest` would be enough for such a scenario. `/retest-required` will re-run all tests and some already succeed.

Thanks @pacoxu that is good to know because in OpenShift, it just runs failing ones :)

File: test/cmd/apply.sh [hunk 1]
```diff
@@ -477,7 +477,7 @@ __EOF__
   local tries=5
   for i in $(seq 1 $tries); do
       local output
-      output=$(kubectl "${kube_flags[@]:?}" api-resources --api-group mygroup.example.com -oname)
+      output=$(kubectl "${kube_flags[@]:?}" api-resources --api-group mygroup.example.com -oname || true)
```
Comment (aojea) [inline test/cmd/apply.sh:480]: this loops never fails now if the api group doesn't exist, I think you should add a check with a bool or the number of tries

Comment (ardaguclu) [reply test/cmd/apply.sh:480]: isn't the purpose not failing?, because this line already checks the string https://github.com/kubernetes/kubernetes/pull/113708/files#diff-46e80bcde84ba84b7739a9124ac5ff40986c2d4ee7122bd5e43bb69dd235795eR481

Comment (ardaguclu) [reply test/cmd/apply.sh:480]: you are right, there should be a verification if tries=5

Comment (aojea) [reply test/cmd/apply.sh:480]: 👍

Comment (apelisse) [reply test/cmd/apply.sh:480]: This is just waiting for the resource to be available, it will fail as soon as it leaves the loop with a rightful error as we're trying to apply a CR of that type?

Comment (aojea) [reply test/cmd/apply.sh:480]: oh, I see , thanks for the clarification and sorry for the noise

**Comment by aojea** [comment]
> /hold

/hold cancel

I was wrong 😓  holding it

/milestone v1.26

This was approved before code free, and is also fixing a test
