### PR TITLE
Escape stdout/stderr YAML-like elements for TAP output

### LINKED ISSUE #3094: Bad "YAMLish" in TAP results from e2e.go cause Jenkins to mark builds UNSTABLE
When things like monitoring.sh or pd.sh fail, their stderr tends to have stuff that needs to be escaped. We need to scan for non-printables and for the YAML special characters and escape them. (I keep meaning to get around to it, but it's kind of a harmless bug because the difference between UNSTABLE and FAILED is only that you have to click on the console logs to figure out what happened, versus seeing the fancy TAP results in the GUI.)

### PR DESCRIPTION
**Pull request by zmerlynn**
Fixes #3094

### CODE REVIEW

File: hack/e2e.go [hunk 1]
```diff
@@ -471,19 +472,44 @@ func finishRunning(stepName string, cmd *exec.Cmd) (bool, string, string) {
...
+// it. This escaping is crude (it masks all colons as something humans
+// will hopefully see as a colon, for instance), but it should get the
+// job done without pulling in a whole YAML package.
+func escapeOutput(s string) (out string) {
+	for _, r := range s {
+		switch {
+		case !strconv.IsPrint(r):
+			out += " "
+		case r == ':':
+			out += "\u02D0" // "ː", MODIFIER LETTER TRIANGULAR COLON
```
Comment (erictune) [inline hack/e2e.go]: "\ua789"  (modifier letter colon) may be visually closer

**Comment by erictune** [comment]
LGTM.  2/3 travis passing.
