### PR TITLE
Fix ImageVolume validation for empty reference in Pod templates

### LINKED ISSUE #135988: ImageVolume: Empty image.reference in Pod templates passes API validation but fails at runtime
### What happened?

When creating a Deployment or StatefulSet with an ImageVolume that has an empty `image.reference` field, the API validation passes, but Pod creation fails at runtime. This creates a confusing user experience where workloads appear to be created successfully but never produce running Pods

**Direct Pod creation correctly rejects empty reference:**

```
$ k apply -f pod-with-empty-ref.yaml
The Pod "test" is invalid: spec.volumes[0].image.reference: Required value
```

**But Deployment/StatefulSet incorrectly accepts it:**

```
$ k apply -f deployment-with-empty-ref.yaml
deployment.apps/test-imagevolume-empty-ref created  # Should have been rejected
```

The error only appears in Events when the ReplicaSet controller tries to create Pods:

```
Warning  FailedCreate  replicaset-controller  Error creating: Pod "..." is invalid:
  [spec.volumes[0].image.reference: Required value, ...]
```

### What did you expect to happen?

API validation should reject empty `image.reference` in Pod templates (Deployment, StatefulSet, DaemonSet, Job, etc.), not just in direct Pod creation.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a kind cluster with Kubernetes v1.35+:

```bash
$ kind create cluster --name test
```

2. Apply this Deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-imagevolume-empty-ref
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: busybox:1.36
        command: ["sleep", "3600"]
        volumeMounts:
        - name: img-vol
          mountPath: /data
      volumes:
      - name: img-vol
        image:
          reference: ""  # Empty
          pullPolicy: Always
```

3. Observe

```bash
$ k get deployment
NAME                         READY   UP-TO-DATE   AVAILABLE
test-imagevolume-empty-ref   0/1     0            0           # Never becomes ready

$ k describe rs -l app=test | grep -A5 Events
Events:
  Warning  FailedCreate  Error creating: Pod "..." is invalid:
    [spec.volumes[0].image.reference: Required value, ...]
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ k version
Client Version: v1.34.1
Kustomize Version: v5.7.1
Server Version: v1.35.0
```

</details>

### Cloud provider

<details>
kind (local)
</details>

### OS version

<details>

```console
$ uname -a
Darwin Junyas-MacBook-Pro.local 25.3.0 Darwin Kernel Version 25.3.0: Fri Dec  5 23:13:24 PST 2025; root:xnu-12377.80.260.0.1~42/RELEASE_ARM64_T8142 arm64
```

</details>

### Install tools

<details>
kind version
kind v0.31.0 go1.25.5 darwin/arm64
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by Okabe-Junya**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

- Fix a validation gap where empty `image.reference` in Pod templates (Deployment, StatefulSet, DaemonSet, Job, etc.) passes API validation but fails at runtime when the controller attempts to create Pods

#### Which issue(s) this PR is related to:

Fixes #135988

#### Special notes for your reviewer:

N/A

#### Does this PR introduce a user-facing change?

```release-note
Image volume validation now rejects empty `image.reference` fields in Pod templates (Deployment, StatefulSet, DaemonSet, Job, etc.).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Okabe-Junya** [comment]
/sig node
/cc sallyom
as a KEP author

File: pkg/apis/core/validation/validation.go [hunk 1]
```diff
@@ -9558,7 +9558,7 @@ func validateLinuxContainerUser(linuxContainerUser *core.LinuxContainerUser, fld
 
 func validateImageVolumeSource(imageVolume *core.ImageVolumeSource, fldPath *field.Path, opts PodValidationOptions) field.ErrorList {
 	allErrs := field.ErrorList{}
-	if opts.ResourceIsPod && len(imageVolume.Reference) == 0 {
+	if len(imageVolume.Reference) == 0 {
```
Comment (toVersus) [inline pkg/apis/core/validation/validation.go]: I'm not sure what the original intent was, but this was pointed out during the review of the PR that introduced KEP-4639 (https://github.com/kubernetes/kubernetes/pull/125660#discussion_r1681604440).

/cc @deads2k @saschagrunert

Comment (Okabe-Junya) [reply pkg/apis/core/validation/validation.go]: Thank you for sharing this context,

I also checked the original discussion and understand that allowing empty `reference` in Pod templates was intentional for flexibility

That said, I'm wondering if a validation warning (similar to null `labelSelector` in TopologySpreadConstraints) might be more appropriate than an error here. 

cf. 

https://github.com/kubernetes/kubernetes/blob/bf0e7b694f3a7355c200241825b6688ad391fae8/pkg/api/pod/warnings.go#L122-L124

Anyway, Happy to wait for the reply from deads2k, saschagrunert :)

Comment (saschagrunert) [reply pkg/apis/core/validation/validation.go]: I understand this was intentional in the original implementation, but I believe it's a validation gap that should be fixed. An empty image.reference has no valid use case, so it should always fail when kubelet tries to provision the volume.

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by Okabe-Junya** [comment]
/assign SergeyKanzhelev
for approval

(since you're in this PR)

File: pkg/apis/core/validation/validation.go (hunk 1 above)
Comment (liggitt) [reply pkg/apis/core/validation/validation.go]: /hold until @deads2k acks this switch, and this is switched to ratcheting validation... we already are plumbing opts down to here, so this could switch to an `AllowEmptyImageVolumeReference bool` in `PodValidationOptions` and be populated based on existing data in GetValidationOptionsFromPodSpecAndMeta

Comment (liggitt) [reply pkg/apis/core/validation/validation.go]: if we make this change, it looks like this is the only use of ResourceIsPod, so that should be removed as well to avoid confusion

**Review by medmes — APPROVED** [review]

**Comment by Okabe-Junya** [comment]
friendly ping @deads2k 
PTAL this when you have time, thank you!

File: pkg/apis/core/validation/validation.go (hunk 1 above)
Comment (deads2k) [reply pkg/apis/core/validation/validation.go]: In a world with mutating admission webhooks and mutating admission policy, why is it invalid for a replicaset to contain a volume without a reference that is injected at admission time when a pod is created?

Comment (liggitt) [reply pkg/apis/core/validation/validation.go]: The same logic could apply to pretty much any field under pod spec, right? We validate container.image is non-empty, even in replicaset... shouldn't image volume be consistent with that?

Comment (deads2k) [reply pkg/apis/core/validation/validation.go]: > We validate container.image is non-empty, even in replicaset... shouldn't image volume be consistent with that?

We do. It's injected so often I wish that particular one wasn't (versus other pod fields).  I'm willing to change this to be consistent, but image is one that is heavily injected/mutated.

This concept will come up again when we discuss embedded validation of one kind inside of another: is it a specifically versioned schema with all validation or a partial schema or a floating schema.

Going consistently restrictive rubs me a little the wrong way, but if you prefer consistency for this one: ok.

Comment (liggitt) [reply pkg/apis/core/validation/validation.go]: the validation on container.image is *very* relaxed, it just has to be present, so any kind of value that admission would expand/mutate (to resolve to a particular registry, or add default tags, or expand to add digest, etc) would also pass API validation on the unexpanded/unmutated value, which seems ~good

wholesale injection of a completely absent image name by admission seems pretty weird to me, but if you want to do that, you can put a placeholder value (`" "` or `"<injected>"` or whatever) in the field and it will still pass validation (just like container.image)

I think it's reasonable for us to validate the pod spec in a pod-creating object will pass the pod-level validation it will be subjected to

Comment (deads2k) [reply pkg/apis/core/validation/validation.go]: ok

Comment (SergeyKanzhelev) [reply pkg/apis/core/validation/validation.go]: /unhold

Comment (liggitt) [reply pkg/apis/core/validation/validation.go]: /hold

> /hold until [...] and this is switched to ratcheting validation... we already are plumbing opts down to here, so this could switch to an AllowEmptyImageVolumeReference bool in PodValidationOptions and be populated based on existing data in GetValidationOptionsFromPodSpecAndMeta
> 
> if we make this change, it looks like this is the only use of ResourceIsPod, so that should be removed as well to avoid confusion

Those bits still need to be applied... still needs ratcheting validation applied so that existing workload API objects with this field unset do not fail validation when updated

Comment (Okabe-Junya) [reply pkg/apis/core/validation/validation.go]: Thank you, got it,

Updated to use ratcheting validation in [d459062](https://github.com/kubernetes/kubernetes/pull/135989/commits/d45906288ad8c70d5c41b70adaaf939f4e9ad28b)

**Comment by Okabe-Junya** [comment]
(Will [rebase with fresh master, squash commits] if needed)

File: pkg/apis/core/validation/validation.go
Comment (liggitt) [inline pkg/apis/core/validation/validation.go:4458]: ResourceIsPod is unused now, so drop this field

Comment (liggitt) [reply pkg/apis/core/validation/validation.go:4458]: hmm... actually, it looks like it was added prior to this use for 4bbf611773d2ac064ecc04652450d04eb566defa, nevermind
