### PR TITLE
tests: Wait for pod to be removed on kubelet restarts with userns.idsPerPod

### LINKED ISSUE #137912: [Failing Test] user namespaces kubeconfig tests [LinuxOnly] [Feature:UserNamespacesSupport] [Serial]  Kubelet crashes on restart when idsPerPod changes with existing userns pods on disk
### Which jobs are failing?

`ci-node-crio-swap-serial`

### Which tests are failing?

```
[sig-node] user namespaces kubeconfig tests [LinuxOnly] [Feature:UserNamespacesSupport] [Serial] test config using userNamespaces.idsPerPod honors idsPerPod in userns pods
```

`k8s.io/kubernetes/test/e2e_node/user_namespaces_test.go:71`

### Since when has it been failing?

Observed in job run [2034607623600345088](https://gcsweb.k8s.io/gcs/kubernetes-ci-logs/logs/ci-node-crio-swap-serial/2034607623600345088/artifacts/e2-standard-2-fedora-coreos-43-20260301-3-1-gcp-x86-64-117cbc54/).

### Testgrid link

N/A

### Reason for failure (if possible)

> **Note:** The following analysis is AI-summarized from the linked CI logs and source code.

The kubelet fatally crashes during restart when `userNamespaces.idsPerPod` is changed and a pod created with the previous `idsPerPod` value still has its directory on disk.

**Failing log line** (from [kubelet.log](https://gcsweb.k8s.io/gcs/kubernetes-ci-logs/logs/ci-node-crio-swap-serial/2034607623600345088/artifacts/e2-standard-2-fedora-coreos-43-20260301-3-1-gcp-x86-64-117cbc54/kubelet.log)):
```
E0319 12:51:56.731779  8547 run.go:72] "command failed" err="failed to run Kubelet: failed to create kubelet:
  create user namespace manager: record pod mappings for existing pod \"5982517a-d29a-4eae-887d-773f1f8a0548\":
  wrong user namespace length 131072"
```

**Sequence of events:**

1. The test sets `userNamespaces.idsPerPod = 131072` (65536 × 2) and restarts the kubelet.
2. A pod with `hostUsers: false` is created. The kubelet allocates a user namespace mapping with `length = 131072` and persists it to the pod's `userns` file on disk.
3. The pod succeeds and the test deletes it.
4. The AfterEach restores the original kubelet config (default `idsPerPod = 65536`) and restarts the kubelet.
5. During initialization, `MakeUserNsManager()` scans existing pod directories on disk (`pkg/kubelet/userns/userns_manager.go:185-190`). It finds the not-yet-cleaned-up pod directory, reads its `userns` file (which has `length = 131072`), and calls `record()`.
6. `record()` (`pkg/kubelet/userns/userns_manager.go:242-243`) performs a strict equality check:
   ```go
   if length != m.userNsLength {
       return fmt.Errorf("wrong user namespace length %v", length)
   }
   ```
   This fails because `131072 != 65536`, and the error is fatal — the kubelet never starts.
7. The AfterEach times out after 120s waiting for the kubelet health check, and the test is marked as FAILED.

**Impact:** This also means that outside of tests, changing `idsPerPod` in a kubelet config and restarting the kubelet will crash the kubelet if any pods using the old value still have directories on disk. The strict check in `record()` does not account for pods that were created with a different `idsPerPod`.

### Additional context

- [Full CI job logs](https://gcsweb.k8s.io/gcs/kubernetes-ci-logs/logs/ci-node-crio-swap-serial/2034607623600345088/artifacts/e2-standard-2-fedora-coreos-43-20260301-3-1-gcp-x86-64-117cbc54/)
- [build-log.txt](https://gcsweb.k8s.io/gcs/kubernetes-ci-logs/logs/ci-node-crio-swap-serial/2034607623600345088/build-log.txt)

/kind failing-test
/sig node

### PR DESCRIPTION
**Pull request by rata**
The test starts the kubelet with a non-default setting for idsPerPod, runs a pod, deletes it, and then restarts the kubelet.

The issue is that the kubelet guarantees that no two pods userns mappings overlap (for security reasons). But we are not waiting for the pod to be removed from the kubelet, the deleteSync() call only waits for the API server to remove the pod.

So, the pod is on disk (and maybe even running!) when we restart the kubelet. As the previous configuration is incompatible with the new one after restart if pods are running, the kubelet failing is the right thing. We should just wait for the pod to be deleted from the kubelet before restarting it with an incompatible configuration.

So, this commit just changes the pod deleteion (before done in e2eoutput.TestContainerOutput() just waiting for the API server) to wait for the kubelet to delete the pod.

#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:

Fix a failing test.

#### Which issue(s) this PR is related to:

Fixes: #137912

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

cc @AkihiroSuda @giuseppe

### CODE REVIEW

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by AkihiroSuda — APPROVED** [review]
Thanks

File: test/e2e_node/user_namespaces_test.go [hunk 1]
```diff
@@ -88,8 +93,33 @@ var _ = SIGDescribe("user namespaces kubeconfig tests", "[LinuxOnly]", feature.U
 					RestartPolicy: v1.RestartPolicyNever,
 				},
 			}
-			expected := []string{strconv.FormatInt(customIDsPerPod, 10)}
-			e2eoutput.TestContainerOutput(ctx, f, "idsPerPod is configured correctly", pod, 0, expected)
+			podClient := e2epod.NewPodClient(f)
+			createdPod := podClient.Create(ctx, pod)
+			defer func() {
```
Comment (SergeyKanzhelev) [inline test/e2e_node/user_namespaces_test.go]: why doing it in defer? Can we wait for delete as part of a regular test flow so we are not required to understand the order of AfterEach and defers?

Comment (haircommander) [reply test/e2e_node/user_namespaces_test.go]: couldn't we also register this as an JustAfterEach? I think it's more idiomatic ginkgo and would take care of the defer. we could branch on whether createdPod was nil to skip in case the test is skipped before we create the pod.

Another option may be a DeferCleanup()

Comment (rata) [reply test/e2e_node/user_namespaces_test.go]: Sorry, I was sick. I switched it to `DeferCleanup()`, it has the advantage that if the test fails, the defer will run anyways and so the kubelet can be restarted.

@haircommander @SergeyKanzhelev thanks!

**Comment by rata** [comment]
@SergeyKanzhelev Addressed your comment, PTAL

File: test/e2e_node/user_namespaces_test.go [hunk 2]
```diff
@@ -88,8 +93,33 @@ var _ = SIGDescribe("user namespaces kubeconfig tests", "[LinuxOnly]", feature.U
 					RestartPolicy: v1.RestartPolicyNever,
 				},
 			}
-			expected := []string{strconv.FormatInt(customIDsPerPod, 10)}
-			e2eoutput.TestContainerOutput(ctx, f, "idsPerPod is configured correctly", pod, 0, expected)
+			podClient := e2epod.NewPodClient(f)
+			createdPod := podClient.Create(ctx, pod)
+			ginkgo.DeferCleanup(func(ctx context.Context) {
+				ginkgo.By("delete the pod")
+				podClient.DeleteSync(ctx, createdPod.Name, metav1.DeleteOptions{}, f.Timeouts.PodDelete)
```
Comment (SergeyKanzhelev) [inline test/e2e_node/user_namespaces_test.go]: let's pass delete option with grace period = 0 so it will be faster

File: test/e2e_node/user_namespaces_test.go [hunk 3]
```diff
@@ -88,8 +93,33 @@ var _ = SIGDescribe("user namespaces kubeconfig tests", "[LinuxOnly]", feature.U
...
+				// DeleteSync deletes the pod from the API server. But we need the
+				// pod to be completely removed from the node before we continue.
+				// This is needed because tempSetCurrentKubeletConfig's AfterEach
+				// will restart the kubelet with the original idsPerPod. If the pod
+				// directory is still on disk, the kubelet will fail to start.
+				waitForAllContainerRemoval(ctx, createdPod.Name, f.Namespace.Name)
```
Comment (SergeyKanzhelev) [inline test/e2e_node/user_namespaces_test.go]: the Pod will not be around after `DeleteSync`. Why we need this check?

File: test/e2e_node/user_namespaces_test.go [hunk 4]
```diff
@@ -88,8 +93,33 @@ var _ = SIGDescribe("user namespaces kubeconfig tests", "[LinuxOnly]", feature.U
...
+				// And wait for the pod on disk to be removed too.
+				podDir := filepath.Join(services.KubeletRootDirectory, kubeletconfigpaths.DefaultKubeletPodsDirName, string(createdPod.UID))
```
Comment (SergeyKanzhelev) [inline test/e2e_node/user_namespaces_test.go:112]: I really worried about this approach. Is the approach of having a finalizer on a Pod and wait for terminal status reported by the kubelet before setting finalizer work?

File: test/e2e_node/user_namespaces_test.go (hunk 2 above)
Comment (rata) [reply test/e2e_node/user_namespaces_test.go]: Added, thanks!

File: test/e2e_node/user_namespaces_test.go (hunk 3 above)
Comment (rata) [reply test/e2e_node/user_namespaces_test.go]: `DeleteSync()` just waits synchronously until the pod is deleted from the API server. It basically calls [WaitForPodNotFoundInNamespace](https://github.com/kubernetes/kubernetes/blob/bc15d50fd246bef83aa9b00fcc475d1959296294/test/e2e/framework/pod/pod_client.go#L239) that just does a [get](https://github.com/kubernetes/kubernetes/blob/bc15d50fd246bef83aa9b00fcc475d1959296294/test/e2e/framework/pod/wait.go#L674) in a loop until the API server returns nil. It's just a busy loop polling until the pod is not returned by the apiserver.

That is not enough, as we need to wait until the kubelet removes the pod dir. And that doesn't happen when the kubelet deletes the pod, as the [pod dir removal is left for the periodic cleanup](https://github.com/kubernetes/kubernetes/blob/bc15d50fd246bef83aa9b00fcc475d1959296294/pkg/kubelet/kubelet.go#L2583).

The approach I took is to use this existing helper, to wait until all containers are removed in the node first (`waitForAllContainerRemoval()` queries the runtime to check when that the containers were actually removed). Once that happens, wait until the pod directory is removed.

We can just wait until the pod directory is removed, without waiting for container removal, that should work anyways. It felt simpler to wait more "step by step", but we can remove this and just wait for the pod directory being removed.

File: test/e2e_node/user_namespaces_test.go (hunk 4 above)
Comment (rata) [reply test/e2e_node/user_namespaces_test.go:112]: Nope, I don't think that will help. A finalizer would hold the API server object alive until the kubelet reports terminal status, but as I mentioned in the previous comment, the kubelet deletes the pod but leaves the pod dir to be removed "lazily", in the next iteration of periodic cleanup function.

File: test/e2e_node/user_namespaces_test.go (hunk 3 above)
Comment (rata) [reply test/e2e_node/user_namespaces_test.go]: I've removed the `waitForAllContainerRemoval()` and just left the wait for the pod dir to be removed and updated the comment. Let me know what you think

**Review by rata — COMMENTED** [review]
@SergeyKanzhelev thanks, PTAL :)

**Comment by rata** [comment]
@SergeyKanzhelev friendly ping?

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve
