### PR TITLE
fix scheduler client construction from configuration files

### LINKED ISSUE #65483: Scheduler does not respect clientConnection of KubeSchedulerConfiguration in 1.11
/kind bug
/sig scheduling

**What happened**:
kube-scheduler `v1.11.0-rc.2` that is pointed to a `KubeSchedulerConfiguration` componentconfig file having
```yaml
clientConnection:
  kubeconfig: /var/lib/kube-scheduler/kubeconfig
```
ignores that it should use this kubeconfig file. Instead, it uses the in-cluster config (as `--kubeconfig` is neither provided).

**What you expected to happen**:
The kube-scheduler should respect the kubeconfig provided in the `KubeSchedulerConfiguration`.

**How to reproduce it (as minimally and precisely as possible)**:
Starting `hyperkube` image `v1.11.0-rc.2` with `/hyperkube scheduler --config=config.yaml --v=2` whereby the content of `config.yaml` looks like this:
```yaml
apiVersion: componentconfig/v1alpha1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /var/lib/kube-scheduler/kubeconfig
leaderElection:
  leaderElect: true
```
makes the scheduler logging `W0626 13:18:22.399724       1 options.go:269] Neither --kubeconfig nor --master was specified. Using default API client. This might not work.`

The exact same configuration as above works with `release-1.10` branch. Seems like abc8c98e35a291e03775cd4fc8808a33dc58b7d7 has introduced the behaviour. The kube clients are created [here](https://github.com/kubernetes/kubernetes/blob/release-1.11/cmd/kube-scheduler/app/options/options.go#L201) but the componentconfig file is loaded [later here](https://github.com/kubernetes/kubernetes/blob/release-1.11/cmd/kube-scheduler/app/options/options.go#L228).

/cc @sttts 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.0-rc.2

### PR DESCRIPTION
**Pull request by liggitt**
fixes #65483

clients were being constructed from options prior to loading the specified configuration file. this is a regression from 1.10 behavior.

/sig scheduling
/kind bug
/priority critical-urgent
/milestone v1.11

```release-note
fixes a regression in kube-scheduler to properly load client connection information from a `--config` file that references a kubeconfig file
```

### CODE REVIEW

File: cmd/kube-scheduler/app/options/options.go [hunk 1]
```diff
@@ -197,37 +197,37 @@ func (o *Options) Validate() []error {
 
 // Config return a scheduler config object
 func (o *Options) Config() (*schedulerappconfig.Config, error) {
+	c := &schedulerappconfig.Config{}
+	if err := o.ApplyTo(c); err != nil {
```
Comment (liggitt) [inline cmd/kube-scheduler/app/options/options.go]: we apply the options to the config *first*, then use the `c.ComponentConfig....` for the rest of the function

File: cmd/kube-scheduler/app/options/options_test.go [hunk 2]
```diff
@@ -0,0 +1,193 @@
...
+	"path/filepath"
+	"strings"
+	"testing"
+
+	"k8s.io/kubernetes/pkg/apis/componentconfig"
+)
+
+func TestSchedulerOptions(t *testing.T) {
+	// temp dir
+	tmpDir, err := ioutil.TempDir("", "scheduler-options")
```
Comment (ravisantoshgudimetla) [inline cmd/kube-scheduler/app/options/options_test.go]: q: Is it safe to assume that tempdir always exists especially when running in containers?

File: cmd/kube-scheduler/app/options/options_test.go [hunk 3]
```diff
@@ -0,0 +1,193 @@
...
+users:
+- name: default
+  user:
+    username: flag
+`, server.URL)), os.FileMode(0600)); err != nil {
+		t.Fatal(err)
+	}
+
+	// Insulate this test from picking up in-cluster config when run inside a pod
+	// We can't assume we have permissions to write to /var/run/secrets/... from a unit test to mock in-cluster config for testing
```
Comment (ravisantoshgudimetla) [inline cmd/kube-scheduler/app/options/options_test.go]: This is pretty clever!!

File: cmd/kube-scheduler/app/options/options_test.go (hunk 2 above)
Comment (liggitt) [reply cmd/kube-scheduler/app/options/options_test.go]: Many unit tests already do this, so yes

**Review by ravisantoshgudimetla — APPROVED** [review]
/lgtm

Thanks @liggitt.

File: cmd/kube-scheduler/app/options/options_test.go [hunk 4]
```diff
@@ -0,0 +1,193 @@
...
+			config, err := tc.options.Config()
+
+			// handle errors
+			if err != nil {
+				if tc.expectedError == "" {
+					t.Error(err)
+				} else if !strings.Contains(err.Error(), tc.expectedError) {
+					t.Errorf("expected %q, got %q", tc.expectedError, err.Error())
+				}
+				return
```
Comment (bsalamat) [inline cmd/kube-scheduler/app/options/options_test.go]: it would be better to `continue` instead of `return` here and below.

File: cmd/kube-scheduler/app/options/options_test.go [hunk 5]
```diff
@@ -0,0 +1,193 @@
...
+	"net/http/httptest"
+	"os"
+	"path/filepath"
+	"strings"
+	"testing"
+
+	"k8s.io/kubernetes/pkg/apis/componentconfig"
+)
+
+func TestSchedulerOptions(t *testing.T) {
```
Comment (bsalamat) [inline cmd/kube-scheduler/app/options/options_test.go]: Impressive! Thanks for writing the test.

**Review by bsalamat — APPROVED** [review]
Thanks a lot, @liggitt! I only have minor comment about the test, but it is not important and given the urgency of this fix, I approve it.

/lgtm

File: cmd/kube-scheduler/app/options/options_test.go (hunk 4 above)
Comment (liggitt) [reply cmd/kube-scheduler/app/options/options_test.go]: This is inside a t.Run function… returning continues to the next test case

Comment (bsalamat) [reply cmd/kube-scheduler/app/options/options_test.go]: Yes, you are right! I missed that it is inside t.Run.
Thanks again!
