### PR TITLE
Bug fix. Incoming UDP packets not reach newly deployed services

### LINKED ISSUE #31983: Incoming UDP packets not reach newly deployed services
Hi,

We have a device (router in this case) that sends long living stream of udp packets to our kubernetes cluster. We then create a service and pods that expose a node port to receive the incoming udp packets. However, packets were not reach our containers.

Further digging and found that because UDP packets already stream into our host (therefore conntrack entry already created) BEFORE our service is created (iptable rules added), the iptable rule didn't take effect. Since our UDP stream is long living, the conntrack entry never get timeout neither.

To workaround the issue, we have to stop the UDP stream for sometime after the service is created so that the conntrack entry times out. If we use "conntrack -D" to clear all entries after service is deployed also workaround the issue. 

Though it is the behavior of the linux iptable that new rules doesn't affect already existing connection, we are trying to see if kubernetes proxy have any config that can clear the related conntrack entries when a new service is deployed?

### PR DESCRIPTION
**Pull request by zreigz**
**What this PR does / why we need it**:

Incoming UDP packets not reach newly deployed services when old connection's state in conntrack is not cleared. When a packet arrives, it will not go through NAT table again, because it is not "the first" packet. The PR fix the issue

**Which issue this PR fixes** 
Fixes #31983
xref https://github.com/docker/docker/issues/8795

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32561)

### CODE REVIEW

**Comment by zreigz** [comment]
cc @kubernetes/sig-network

**Comment by zreigz** [comment]
cc @kubernetes/sig-network PTAL

**Comment by zreigz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32561)*

File: pkg/proxy/iptables/proxier.go [hunk 1]
```diff
@@ -1075,6 +1075,7 @@ func (proxier *Proxier) syncProxyRules() {
 				glog.V(4).Infof("Port %s was open before and is still needed", lp.String())
 				replacementPortsMap[lp] = proxier.portsMap[lp]
 			} else {
+
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: This is a dead line - remove

**Comment by thockin** [comment]
@k8s-bot ok to test

File: pkg/proxy/iptables/proxier.go [hunk 2]
```diff
@@ -1099,6 +1100,18 @@ func (proxier *Proxier) syncProxyRules() {
 				// Currently we only create it for loadbalancers (#33586).
 				writeLine(natRules, append(args, "-j", string(svcXlbChain))...)
 			}
+			// When a packet arrives, it will not go through NAT table again, because it is not "the first" packet.
+			// The solution is clearing the conntrack. Known issus:
+			// https://github.com/docker/docker/issues/8795
+			// https://github.com/kubernetes/kubernetes/issues/31983
+			if lp.protocol == "udp" {
+				glog.V(2).Infof("Deleting conntrack entries for udp connections")
+				err := proxier.execConntrackTool("-D", "-p", "udp", "--dport", strconv.Itoa(lp.port))
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: This doesn't only happen once - this is going to happen periodically, unless I am mis-readng.  I think you want to do this up around line 1077 (OpenLocalPort), when you know that this is a new nodePort, rather than a refresh.  You might also do it way at the end of this function when we close nodeports we don't want any more.

But even that is not 100% correct.  I think there's a bug here where, if the same nodeport were to be release and reused inside a single refresh loop it would fail.  I think that will self-repair, though.

**Comment by zreigz** [comment]
@thockin Done. I followed your comments and I've made necessary changes. I've tested it and works
PTAL

File: pkg/proxy/iptables/proxier.go [hunk 3]
```diff
@@ -1100,6 +1100,9 @@ func (proxier *Proxier) syncProxyRules() {
 				glog.V(4).Infof("Port %s was open before and is still needed", lp.String())
 				replacementPortsMap[lp] = proxier.portsMap[lp]
 			} else {
+				if lp.protocol == "udp" {
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: Please do this AFTER the port is successfully opened.

File: pkg/proxy/iptables/proxier.go [hunk 4]
```diff
@@ -1321,6 +1324,26 @@ func (proxier *Proxier) syncProxyRules() {
 		}
 	}
 	proxier.portsMap = replacementPortsMap
+	// Delete conntrack for all UDP entries
+	proxier.clearUdpConntrackForPort(0)
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: If there are any in-flight transactions, this is going to kill them.  Why are you doing this?

**Review by thockin — CHANGES_REQUESTED** [review]

**Comment by thockin** [comment]
ok for post 1.5.0

**Comment by dims** [comment]
Is this a real error or a flake?
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/32561/pull-kubernetes-unit/5897/

**Comment by dims** [comment]
moving this to post 1.5.0 == 1.6 :)

File: pkg/proxy/iptables/proxier.go (hunk 4 above)
Comment (zreigz) [inline pkg/proxy/iptables/proxier.go]: This is what I understood from your comment:
" ... You might also do it way at the end of this function when we close nodeports we don't want any more."

Now I removed it

File: pkg/proxy/iptables/proxier.go (hunk 3 above)
Comment (zreigz) [inline pkg/proxy/iptables/proxier.go]: Done

File: pkg/proxy/iptables/proxier.go [hunk 5]
```diff
@@ -1323,6 +1326,24 @@ func (proxier *Proxier) syncProxyRules() {
...
+// When a packet arrives, it will not go through NAT table again, because it is not "the first" packet.
+// The solution is clearing the conntrack. Known issus:
+// https://github.com/docker/docker/issues/8795
+// https://github.com/kubernetes/kubernetes/issues/31983
+func (proxier *Proxier) clearUdpConntrackForPort(port int) {
+	var err error = nil
+	glog.V(2).Infof("Deleting conntrack entries for udp connections")
+	if port > 0 {
+		err = proxier.execConntrackTool("-D", "-p", "udp", "--dport", strconv.Itoa(port))
+	} else {
```
Comment (thockin) [inline pkg/proxy/iptables/proxier.go]: We don't really need this fallback path any more - would be safer to just log.

**Review by thockin — APPROVED** [review]
I am going to LGTM and see if you can fix it before the bot merges it.  If not, please send a followup :)

File: pkg/proxy/iptables/proxier.go (hunk 5 above)
Comment (zreigz) [inline pkg/proxy/iptables/proxier.go]: Done

**Comment by zreigz** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32561)*

**Comment by thockin** [comment]
LGTM!

**Comment by zreigz** [comment]
Thanks

**Comment by zreigz** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/32561)*

**Comment by jfoy** [comment]
I'm confused - how is this different from #22573 ?

**Comment by bjoernhaeuser** [comment]
Will this be cherry-picked for 1.5.?

**Comment by thockin** [comment]
Given that 1.6 is freezing in O(weeks) we weren't planning on back-patching
to 1.5

**Comment by timchenxiaoyu** [comment]
why  TCP doesn't  this problem  ？
