### PR TITLE
fix dra flaky test on TestPlugin

### LINKED ISSUE #125221: [Flaking Test] ci-kubernetes-unit (error message's order sensitivity)
### Which jobs are flaking?

master-blocking:
- ci-kubernetes-unit

### Which tests are flaking?

k8s.io/kubernetes/pkg/scheduler/framework/plugins/dynamicresources.dynamicresources

### Since when has it been flaking?

It starts flaking today 30-05-2024
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1796131835290324992

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Reason for failure (if possible)

The test fail is `TestPlugin/too-many-translated-claim-parameters/prefilter`

This failure may be caused by the error message's order sensitivity.

The error message's order of Resource Classes `[default/my-resource-class default/other]` versus `[default/other default/my-resource-class]` is different.

```
{Failed;Failed;Failed;  === RUN   TestPlugin/too-many-translated-class-parameters/prefilter
    dynamicresources_test.go:1103: 
        	Error Trace:	/home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go:1221
        	            				/home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go:1103
        	Error:      	Not equal: 
        	            	expected: &framework.Status{code:1, reasons:[]string(nil), err:(*errors.errorString)(0xc00053d6b0), plugin:""}
        	            	actual  : &framework.Status{code:1, reasons:[]string(nil), err:(*errors.errorString)(0xc000b7b7f0), plugin:""}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -4,3 +4,3 @@
        	            	  err: (*errors.errorString)({
        	            	-  s: (string) (len=142) "multiple generated class parameters for ResourceClassParameters.example.com my-resource-class found: [default/my-resource-class default/other]"
        	            	+  s: (string) (len=142) "multiple generated class parameters for ResourceClassParameters.example.com my-resource-class found: [default/other default/my-resource-class]"
        	            	  }),
        	Test:       	TestPlugin/too-many-translated-class-parameters/prefilter
        --- FAIL: TestPlugin/too-many-translated-class-parameters/prefilter (0.00s)
```

### Anything else we need to know?

N/A

### Relevant SIG(s)

/sig node
/sig scheduling
@kubernetes/release-team-release-signal

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind flake
/kind regression

#### What this PR does / why we need it:

```
{Failed;Failed;Failed;  === RUN   TestPlugin/too-many-translated-class-parameters/prefilter
    dynamicresources_test.go:1103: 
        	Error Trace:	/home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go:1221
        	            				/home/prow/go/src/k8s.io/kubernetes/pkg/scheduler/framework/plugins/dynamicresources/dynamicresources_test.go:1103
        	Error:      	Not equal: 
        	            	expected: &framework.Status{code:1, reasons:[]string(nil), err:(*errors.errorString)(0xc0000236a0), plugin:""}
        	            	actual  : &framework.Status{code:1, reasons:[]string(nil), err:(*errors.errorString)(0xc0008c6240), plugin:""}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -4,3 +4,3 @@
        	            	  err: (*errors.errorString)({
        	            	-  s: (string) (len=142) "multiple generated class parameters for ResourceClassParameters.example.com my-resource-class found: [default/my-resource-class default/other]"
        	            	+  s: (string) (len=142) "multiple generated class parameters for ResourceClassParameters.example.com my-resource-class found: [default/other default/my-resource-class]"
        	            	  }),
        	Test:       	TestPlugin/too-many-translated-class-parameters/prefilter
        --- FAIL: TestPlugin/too-many-translated-class-parameters/prefilter (0.00s)
```

#### Which issue(s) this PR fixes:

Related to https://github.com/kubernetes/kubernetes/pull/124630 and https://github.com/kubernetes/kubernetes/pull/125204 

Fixes https://github.com/kubernetes/kubernetes/issues/125221

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go [hunk 1]
```diff
@@ -1055,6 +1055,13 @@ func (pl *dynamicResources) lookupClassParameters(logger klog.Logger, class *res
 		}
 		return parameters, nil
 	default:
+		sort.Slice(objs, func(i, j int) bool {
+			obj1, obj2 := objs[i].(*resourcev1alpha2.ResourceClassParameters), objs[j].(*resourcev1alpha2.ResourceClassParameters)
+			if obj1 == nil || obj2 == nil {
+				return false
+			}
+			return obj1.CreationTimestamp.Before(&obj2.CreationTimestamp)
+		})
```
Comment (carlory) [inline pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:1064]: should we sort it by name or creation timestamp?

Comment (carlory) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:1064]: pull-kubernetes-linter-hints:

```
ERROR: pkg/scheduler/testing/wrappers.go:1182:34: ST1016: methods on the same type should have the same receiver name (seen 1x "p", 7x "wrapper") (stylecheck)
ERROR: func (p *ClaimParametersWrapper) CreationTimestamp(t metav1.Time) *ClaimParametersWrapper {
ERROR:                                  ^
ERROR: pkg/scheduler/testing/wrappers.go:1248:34: ST1016: methods on the same type should have the same receiver name (seen 1x "p", 6x "wrapper") (stylecheck)
ERROR: func (p *ClassParametersWrapper) CreationTimestamp(t metav1.Time) *ClassParametersWrapper {
ERROR:      
```

the function follows the podwrapper style. https://github.com/carlory/kubernetes/blob/f3cca34c90b2a9bae89b646ac0751ef9c2b01a18/pkg/scheduler/testing/wrappers.go#L291.

**Comment by aojea** [comment]
does not look like a regression, does it?

we use the tags later to evaluate the quality of the releases and the project, so it is better to not use it here

/remove-label regression

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 1 above)
Comment (pohly) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:1064]: Name. The error message doesn't include the time stamp, so the sort order would still look random to a user.

Thanks for following up in the bug report!

/lgtm
/approve

**Comment by pohly** [comment]
/assign @Huang-Wei 

Follow-up to https://github.com/kubernetes/kubernetes/pull/124630.

File: pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go (hunk 1 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/dynamicresources/dynamicresources.go:1064]: Per offline discussion, it makes sense to keep the sorting in core logic.

**Review by Huang-Wei — COMMENTED** [review]
/approve
