### PR TITLE
flake: remove the error handler for cronjob integration test

### LINKED ISSUE #107198: Top flake: TestCronJobLaunchesPodAndCleansUp
##### Error text:
```
=== RUN   TestCronJobLaunchesPodAndCleansUp
I1222 07:55:48.781583  118818 apf_controller.go:218] NewTestableController "Controller" with serverConcurrencyLimit=600, requestWaitLimit=15s, name=Controller, asFieldManager="api-priority-and-fairness-config-consumer-v1"
I1222 07:55:48.781668  118818 apf_controller.go:769] No exempt PriorityLevelConfiguration found, imagining one
I1222 07:55:48.781682  118818 apf_controller.go:769] No catch-all PriorityLevelConfiguration found, imagining one
W1222 07:55:48.781748  118818 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W1222 07:55:48.781783  118818 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
I1222 07:55:48.781840  118818 services.go:51] Setting service IP to "10.0.0.1" (read-write).
I1222 07:55:48.781882  118818 instance.go:318] Node port range unspecified. Defaulting to 30000-32767.
I1222 07:55:48.781893  118818 instance.go:274] Using reconciler: 
I1222 07:55:48.783527  118818 instance.go:382] Could not construct pre-rendered responses for ServiceAccountIssuerDiscovery endpoints. Endpoints will not be enabled. Error: empty issuer URL
I1222 07:55:48.783705  118818 storage_factory.go:285] storing podtemplates in v1, reading as __internal from storagebackend.Config{Type:"", Prefix:"5fa6b0a5-fa6a-491c-b84b-79c4aa02c064", Transport:storagebackend.TransportConfig{ServerList:[]string{"http://127.0.0.1:2379"}, KeyFile:"", CertFile:"", TrustedCAFile:""
```

> E1223 01:12:00.153488  118776 job_controller.go:488] syncing job: tracking status: adding uncounted pods to status: Operation cannot be fulfilled on jobs.batch "foo-27337032": the object has been modified; please apply your changes to the latest version and try again
>    cronjob_test.go:159: Failed with error: syncing job: tracking status: adding uncounted pods to status: Operation cannot be fulfilled on jobs.batch "foo-27337032": the object has been modified; please apply your changes to the latest version and try again

#### Recent failures:
[2021/12/22 下午3:34:22 ci-kubernetes-integration-1-23](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-1-23/1473557044576391168)

/kind flake
/sig apps

### PR DESCRIPTION
**Pull request by pacoxu**
/kind flake
/sig apps

xref #107198
(release branches should be fixed as well, so cherry-picks are needed. )

/priority critical-urgent
This is currently the top 1 flake in CI.
- The flake started after #104799 was merged. #104799 tried to fix a problem of `conflict error`: "the object has been modified; please apply your changes to the latest version and try again".

But it seems the conflict error cannot be fully handled now.

https://github.com/kubernetes/kubernetes/blob/3f0a634ef78b6df33075e54b0f89e465e88049c4/pkg/controller/job/job_controller.go#L488-L494

> 		// If this was a conflict error, we expect a Job or Pod update event, which
>		// will add the job back to the queue. Avoiding the rate limited requeue
>		// saves an unnecessary sync.

```release-note
NONE
```

### CODE REVIEW

**Comment by pacoxu** [comment]
/test pull-kubernetes-integration 
to run pull-kubernetes-integration again. 

/test pull-kubernetes-unit 
for another flake 😓

File: test/integration/cronjob/cronjob_test.go [hunk 1]
```diff
@@ -156,7 +157,11 @@ func TestCronJobLaunchesPodAndCleansUp(t *testing.T) {
 
 	backupHandlers := runtime.ErrorHandlers
 	runtime.ErrorHandlers = append(runtime.ErrorHandlers, func(e error) {
-		t.Fatalf("Failed with error: %v", e)
+		if !apierrors.IsConflict(e) {
+			t.Fatalf("Failed with error: %v", e)
```
Comment (RyanAoh) [inline test/integration/cronjob/cronjob_test.go:161]: The error in https://github.com/kubernetes/kubernetes/issues/103607 is a confict error, too. If so, I think it would be better to simply remove this error handler.

Comment (pacoxu) [reply test/integration/cronjob/cronjob_test.go:161]: That's another choice. Either is ok to me.

- It seems that the ErrorHandlers were added for Conflict Error. 😂

Comment (pacoxu) [reply test/integration/cronjob/cronjob_test.go]: I updated the PR to remove it directly. It would be more clear.

**Review by RyanAoh — APPROVED** [review]

**Comment by liggitt** [comment]
it looks like https://github.com/kubernetes/kubernetes/pull/104799 was immediately picked to release branches as well, and we're seeing integration test failures there as well

**Comment by pacoxu** [comment]
> it looks like #104799 was immediately picked to release branches as well, and we're seeing integration test failures there as well

Yes. We may cherry-pick it to release branches once this is merged.

**Review by soltysh — APPROVED** [review]
/triage accepted
/lgtm
/approve
