### PR TITLE
Fix access to Kubernetes Service from inside Windows Pod when two ser…

### LINKED ISSUE #91912: Windows Kubeproxy doesn;t program SourceVip for LoadBalancer properly when multiple services has same nodeip backend
**What happened**:
In Overlay mode, When 2 service has the same backend node IP, the LB was not programmed correctly causing datapath issues.

**What you expected to happen**:
Service data path to work properly
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by sbangari**
…vices have same NodeIp as backend (Overlay)

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
In Overlay mode, when 2 services have the same Node IP as backend , the load balancer is programmed incorrectly in HNS with a wrong Source VIP. 

For a case when a remote endpoint (for Node IP) is already created in HNS, we are missing the logic to classify the remote endpoint as NodeIP/PublicIP.  We need to use the current windows worker node's IP as source VIP in the LB policy when remote endpoints are classified as NodeIP/PublicIP.

Fix: Classify the remote endpoint as NodeIP/PublicIP before plumbing the LB policy for cases where remote endpoint was previously created in HNS.

**Which issue(s) this PR fixes**:

Fixes #91912 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by JocelynBerrendonner** [comment]
LGTM

File: pkg/proxy/winkernel/proxier.go [hunk 1]
```diff
@@ -278,6 +278,24 @@ func newServiceInfo(svcPortName proxy.ServicePortName, port *v1.ServicePort, ser
 	return info
 }
 
+func (network hnsNetworkInfo) findProviderAddress(ip string) string {
```
Comment (madhanrm) [inline pkg/proxy/winkernel/proxier.go:281]: can you name this as , findRemoteSubnetProviderAddress

Comment (sbangari) [reply pkg/proxy/winkernel/proxier.go]: renamed the method

**Review by elweb9858 — APPROVED** [review]
lgtm

**Review by JocelynBerrendonner — APPROVED** [review]
lgtm

File: pkg/proxy/winkernel/proxier.go [hunk 2]
```diff
@@ -278,6 +278,24 @@ func newServiceInfo(svcPortName proxy.ServicePortName, port *v1.ServicePort, ser
...
+		_, ipNet, err := net.ParseCIDR(rs.destinationPrefix)
+		if err != nil {
+			klog.Fatalf("%v", err)
+		}
+		if ipNet.Contains(net.ParseIP(ip)) {
+			providerAddress = rs.providerAddress
+		}
+		if ip == rs.providerAddress {
+			providerAddress = rs.providerAddress
+		}
```
Comment (kumarvin123) [inline pkg/proxy/winkernel/proxier.go:293]: Can you break from the loop if you find the  PA?

**Review by kumarvin123 — APPROVED** [review]

**Review by Keith-Mange — APPROVED** [review]
