### PR TITLE
Deflake TestDevicePluginReRegistrationProbeMode: Devices of previous registered should be removed

### LINKED ISSUE #94547: [Flaky unit test] TestDevicePluginReRegistrationProbeMode: Devices of previous registered should be removed
**Which jobs are flaking**:

pull-kubernetes-bazel-test

**Which test(s) are flaking**:

TestDevicePluginReRegistrationProbeMode

**Testgrid link**:

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-bazel-test&include-filter-by-regex=pkg%2Fkubelet%2Fcm%2Fdevicemanager

**Reason for failure**:

```
=== RUN   TestDevicePluginReRegistrationProbeMode
I0904 23:07:54.382417 2813190 fake_topology_manager.go:29] [fake topologymanager] NewFakeManager
W0904 23:07:54.382652 2813190 manager.go:596] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
I0904 23:07:54.386357 2813190 plugin_manager.go:114] Starting Kubelet Plugin Manager
I0904 23:07:54.390968 2813190 device_plugin_stub.go:131] Starting to serve on /tmp/device_plugin394710885/device-plugin.sock
I0904 23:07:54.393796 2813190 device_plugin_stub.go:153] GetInfo
E0904 23:07:54.394527 2813190 goroutinemap.go:150] Operation for "/tmp/device_plugin394710885/server.sock" failed. No retries permitted until 2020-09-04 23:07:54.894365704 +0000 UTC m=+0.587686396 (durationBeforeRetry 500ms). Error: "RegisterPlugin error -- failed to get
 plugin info using RPC GetInfo at socket /tmp/device_plugin394710885/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I0904 23:07:54.401946 2813190 device_plugin_stub.go:227] ListAndWatch
I0904 23:07:54.408602 2813190 device_plugin_stub.go:131] Starting to serve on /tmp/device_plugin394710885/device-plugin.sock.new
E0904 23:07:55.390620 2813190 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Canceled desc = grpc: the client connection is closing
I0904 23:07:55.394203 2813190 device_plugin_stub.go:153] GetInfo
E0904 23:07:55.395579 2813190 goroutinemap.go:150] Operation for "/tmp/device_plugin394710885/server.sock" failed. No retries permitted until 2020-09-04 23:07:56.395409336 +0000 UTC m=+2.088730022 (durationBeforeRetry 1s). Error: "RegisterPlugin error -- failed to get pl
ugin info using RPC GetInfo at socket /tmp/device_plugin394710885/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I0904 23:07:55.402515 2813190 device_plugin_stub.go:153] GetInfo
I0904 23:07:55.407069 2813190 device_plugin_stub.go:227] ListAndWatch
I0904 23:07:55.410949 2813190 device_plugin_stub.go:227] ListAndWatch
I0904 23:07:55.416241 2813190 device_plugin_stub.go:131] Starting to serve on /tmp/device_plugin394710885/device-plugin.sock.third
    manager_test.go:222: 
        	Error Trace:	manager_test.go:222
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 2
        	Test:       	TestDevicePluginReRegistrationProbeMode
        	Messages:   	Devices of previous registered should be removed
--- FAIL: TestDevicePluginReRegistrationProbeMode (1.04s)
```

**Anything else we need to know**:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/94537/pull-kubernetes-bazel-test/1302014570960785409

Reproduce with https://godoc.org/golang.org/x/tools/cmd/stress:

```
go test -race -c ./pkg/kubelet/cm/devicemanager/
stress ./devicemanager.test -test.run TestDevicePluginReRegistrationProbeMode -test.v -test.count=1
12 runs so far, 0 failures

/tmp/go-stress-20200904T231110-342699477
=== RUN   TestDevicePluginReRegistrationProbeMode
I0904 23:11:13.794561 2816353 fake_topology_manager.go:29] [fake topologymanager] NewFakeManager
W0904 23:11:13.795803 2816353 manager.go:596] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
I0904 23:11:13.800094 2816353 plugin_manager.go:114] Starting Kubelet Plugin Manager
I0904 23:11:13.806929 2816353 device_plugin_stub.go:131] Starting to serve on /tmp/device_plugin419155337/device-plugin.sock
I0904 23:11:13.809650 2816353 device_plugin_stub.go:153] GetInfo
E0904 23:11:13.810351 2816353 goroutinemap.go:150] Operation for "/tmp/device_plugin419155337/server.sock" failed. No retries permitted until 2020-09-04 23:11:14.310106769 +0000 UTC m=+0.606335562 (durationBeforeRetry 500ms). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /tmp/device_plugin419155337/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I0904 23:11:13.815871 2816353 device_plugin_stub.go:227] ListAndWatch
I0904 23:11:13.821720 2816353 device_plugin_stub.go:131] Starting to serve on /tmp/device_plugin419155337/device-plugin.sock.new
E0904 23:11:14.805651 2816353 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Canceled desc = grpc: the client connection is closing
E0904 23:11:14.810124 2816353 goroutinemap.go:150] Operation for "/tmp/device_plugin419155337/server.sock" failed. No retries permitted until 2020-09-04 23:11:15.809963076 +0000 UTC m=+2.106191891 (durationBeforeRetry 1s). Error: "RegisterPlugin error -- failed to get plugin info using RPC GetInfo at socket /tmp/device_plugin419155337/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I0904 23:11:14.810222 2816353 device_plugin_stub.go:153] GetInfo
I0904 23:11:14.815461 2816353 device_plugin_stub.go:227] ListAndWatch
I0904 23:11:14.825621 2816353 device_plugin_stub.go:131] Starting 
…
31 runs so far, 1 failures
49 runs so far, 1 failures
^C
liggitt@liggitt:~/go/src/k8s.io/kubernetes$ more /tmp/go-stress-20200904T231110-342699477
=== RUN   TestDevicePluginReRegistrationProbeMode
I0904 23:11:13.794561 2816353 fake_topology_manager.go:29] [fake topologymanager] NewFakeManager
W0904 23:11:13.795803 2816353 manager.go:596] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
I0904 23:11:13.800094 2816353 plugin_manager.go:114] Starting Kubelet Plugin Manager
I0904 23:11:13.806929 2816353 device_plugin_stub.go:131] Starting to serve on /tmp/device_plugin419155337/device-plugin.sock
I0904 23:11:13.809650 2816353 device_plugin_stub.go:153] GetInfo
E0904 23:11:13.810351 2816353 goroutinemap.go:150] Operation for "/tmp/device_plugin419155337/server.sock" failed. No retries permitted until 2020-09-04 23:11:14.310106769 +0000 UTC m=+0.606335562 (durationBeforeRetry 500ms). Error: "RegisterPlugin error -- failed to get
 plugin info using RPC GetInfo at socket /tmp/device_plugin419155337/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I0904 23:11:13.815871 2816353 device_plugin_stub.go:227] ListAndWatch
I0904 23:11:13.821720 2816353 device_plugin_stub.go:131] Starting to serve on /tmp/device_plugin419155337/device-plugin.sock.new
E0904 23:11:14.805651 2816353 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Canceled desc = grpc: the client connection is closing
E0904 23:11:14.810124 2816353 goroutinemap.go:150] Operation for "/tmp/device_plugin419155337/server.sock" failed. No retries permitted until 2020-09-04 23:11:15.809963076 +0000 UTC m=+2.106191891 (durationBeforeRetry 1s). Error: "RegisterPlugin error -- failed to get pl
ugin info using RPC GetInfo at socket /tmp/device_plugin419155337/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I0904 23:11:14.810222 2816353 device_plugin_stub.go:153] GetInfo
I0904 23:11:14.815461 2816353 device_plugin_stub.go:227] ListAndWatch
I0904 23:11:14.825621 2816353 device_plugin_stub.go:131] Starting to serve on /tmp/device_plugin419155337/device-plugin.sock.third
I0904 23:11:15.815810 2816353 device_plugin_stub.go:153] GetInfo
I0904 23:11:15.817094 2816353 device_plugin_stub.go:153] GetInfo
I0904 23:11:15.822788 2816353 device_plugin_stub.go:227] ListAndWatch
I0904 23:11:15.823637 2816353 device_plugin_stub.go:227] ListAndWatch
E0904 23:11:15.823678 2816353 goroutinemap.go:150] Operation for "/tmp/device_plugin419155337/server.sock" failed. No retries permitted until 2020-09-04 23:11:17.823426357 +0000 UTC m=+4.119655152 (durationBeforeRetry 2s). Error: "RegisterPlugin error -- failed to get pl
ugin info using RPC GetInfo at socket /tmp/device_plugin419155337/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
    manager_test.go:222: 
        	Error Trace:	manager_test.go:222
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 2
        	Test:       	TestDevicePluginReRegistrationProbeMode
        	Messages:   	Devices of previous registered should be removed
--- FAIL: TestDevicePluginReRegistrationProbeMode (2.03s)
FAIL
```

/sig node

### PR DESCRIPTION
**Pull request by rphillips**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
There is a race when the GRPC server is coming up and the subsequent dial call for the unix socket. This fix waits within the stub with a retry to allow the server to start and the dial call to succeed.

```
=== RUN   TestDevicePluginReRegistrationProbeMode
I0904 23:07:54.382417 2813190 fake_topology_manager.go:29] [fake topologymanager] NewFakeManager
W0904 23:07:54.382652 2813190 manager.go:596] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
I0904 23:07:54.386357 2813190 plugin_manager.go:114] Starting Kubelet Plugin Manager
I0904 23:07:54.390968 2813190 device_plugin_stub.go:131] Starting to serve on /tmp/device_plugin394710885/device-plugin.sock
I0904 23:07:54.393796 2813190 device_plugin_stub.go:153] GetInfo
E0904 23:07:54.394527 2813190 goroutinemap.go:150] Operation for "/tmp/device_plugin394710885/server.sock" failed. No retries permitted until 2020-09-04 23:07:54.894365704 +0000 UTC m=+0.587686396 (durationBeforeRetry 500ms). Error: "RegisterPlugin error -- failed to get
 plugin info using RPC GetInfo at socket /tmp/device_plugin394710885/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I0904 23:07:54.401946 2813190 device_plugin_stub.go:227] ListAndWatch
I0904 23:07:54.408602 2813190 device_plugin_stub.go:131] Starting to serve on /tmp/device_plugin394710885/device-plugin.sock.new
E0904 23:07:55.390620 2813190 endpoint.go:107] listAndWatch ended unexpectedly for device plugin fake-domain/resource with error rpc error: code = Canceled desc = grpc: the client connection is closing
I0904 23:07:55.394203 2813190 device_plugin_stub.go:153] GetInfo
E0904 23:07:55.395579 2813190 goroutinemap.go:150] Operation for "/tmp/device_plugin394710885/server.sock" failed. No retries permitted until 2020-09-04 23:07:56.395409336 +0000 UTC m=+2.088730022 (durationBeforeRetry 1s). Error: "RegisterPlugin error -- failed to get pl
ugin info using RPC GetInfo at socket /tmp/device_plugin394710885/server.sock, err: rpc error: code = Unimplemented desc = unknown service pluginregistration.Registration"
I0904 23:07:55.402515 2813190 device_plugin_stub.go:153] GetInfo
I0904 23:07:55.407069 2813190 device_plugin_stub.go:227] ListAndWatch
I0904 23:07:55.410949 2813190 device_plugin_stub.go:227] ListAndWatch
I0904 23:07:55.416241 2813190 device_plugin_stub.go:131] Starting to serve on /tmp/device_plugin394710885/device-plugin.sock.third
    manager_test.go:222: 
        	Error Trace:	manager_test.go:222
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 2
        	Test:       	TestDevicePluginReRegistrationProbeMode
        	Messages:   	Devices of previous registered should be removed
--- FAIL: TestDevicePluginReRegistrationProbeMode (1.04s)
```

**Which issue(s) this PR fixes**:

Fixes #94547

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs

```

/cc @sjenning @liggitt

### CODE REVIEW

File: pkg/kubelet/cm/devicemanager/device_plugin_stub.go [hunk 1]
```diff
@@ -123,6 +123,9 @@ func (m *Stub) Start() error {
 		defer m.wg.Done()
 		m.server.Serve(sock)
```
Comment (rphillips) [inline pkg/kubelet/cm/devicemanager/device_plugin_stub.go:124]: m.server.Serve(sock) will block, so other forms of synchronization would be tricky.

File: pkg/kubelet/cm/devicemanager/device_plugin_stub.go [hunk 2]
```diff
@@ -123,6 +123,9 @@ func (m *Stub) Start() error {
...
 	}()
+
+	<-time.After(5 * time.Second)
```
Comment (liggitt) [inline pkg/kubelet/cm/devicemanager/device_plugin_stub.go:127]: rather than a hard wait that makes every test that calls this take five seconds longer, can we PollImmediate on the dial attempt until it succeeds (with a backstop timeout that returns the dial error encountered)?

Comment (rphillips) [reply pkg/kubelet/cm/devicemanager/device_plugin_stub.go]: Thank you for the review. Fixed!

**Comment by rphillips** [comment]
@sjenning and I collectively agreed on a 1 second interval... Let me know if you want anything different.

**Comment by sjenning** [comment]
/approve
@liggitt can you add lgtm 1s is good for the interval?

File: pkg/kubelet/cm/devicemanager/device_plugin_stub.go [hunk 3]
```diff
@@ -123,11 +124,18 @@ func (m *Stub) Start() error {
...
+	if err := wait.PollImmediate(1*time.Second, 10*time.Second, func() (bool, error) {
+		_, conn, err := dial(m.socket)
+		if err != nil {
+			return false, err
+		}
+		conn.Close()
+		return true, nil
+	}); err != nil {
 		return err
 	}
```
Comment (liggitt) [inline pkg/kubelet/cm/devicemanager/device_plugin_stub.go:137]: returning `false, err` will fail the poll immediately and not fix the flake. this should look more like this:

```suggestion
	var lastDialErr error
	wait.PollImmediate(1*time.Second, 10*time.Second, func() (bool, error) {
		var conn *net.Conn
		_, conn, lastDialErr = dial(m.socket)
		if lastDialErr != nil {
			return false, nil
		}
		conn.Close()
		return true, nil
	})
	if lastDialErr != nil {
		return lastDialErr
	}
```

**Comment by liggitt** [comment]
1s is fine, left a comment about how to handle the dial failure case

File: pkg/kubelet/cm/devicemanager/device_plugin_stub.go (hunk 3 above)
Comment (rphillips) [reply pkg/kubelet/cm/devicemanager/device_plugin_stub.go]: Updated. Thanks.

**Comment by liggitt** [comment]
```
compilepkg: error running subcommand: exit status 2
/bazel-scratch/.cache/bazel/_bazel_root/cae228f2a89ef5ee47c2085e441a3561/sandbox/linux-sandbox/1959/execroot/io_k8s_kubernetes/pkg/kubelet/cm/devicemanager/device_plugin_stub.go:131:24: cannot assign *grpc.ClientConn to conn (type *"net".Conn) in multiple assignment:
	*"net".Conn is pointer to interface, not interface
```

oops...

**Comment by rphillips** [comment]
@liggitt could you re-review... thank you!
