### PR TITLE
Fixes kubernetes/kubernetes#29271: accept prefixed namespaces

### LINKED ISSUE #29271: kubectl -n should support both `-n namespace/yournamespace` and `-n yournamespace`
## Summary

Because `kubectl get ns -o name` always return names with a prefix like `namespace/default`, it cannot be directly used to iterate over all namespaces to execute other commands.
## Version

I've compiled from source:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.0.661+d4ae9ca53dc88a-dirty", GitCommit:"d4ae9ca53dc88aa43c7b2fcc2a6aab1105746f0a", GitTreeState:"dirty", BuildDate:"2016-06-23T17:02:00Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.3.0-alpha.3-599-g2746284", GitCommit:"2fe486f", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.5.4", Compiler:"gc", Platform:"linux/amd64"}
```
## Details

Reviewing some scripts, I came across a usage of `kubectl` like this:

```
kubectl get ns -o jsonpath='{.items[*].metadata.name}'
```

That line fetches namespace names to later run in a `for` loop:

```
kubectl -n "${ns}" get pods -o json > "${ns}/pods.json"
```

That seemed to be a perfect use case for the `-o name` flag, but it can't be used without extra hacks to get rid of the `namespace/` prefix (FWIW, `kubectl -n namespace/default ...` is invalid).
## Proposed solution

Changing the current output of `kubectl get ns -o name` might not be possible or desirable, for this could impact existing users that rely on the output format.

If I'm wrong about the above limitation, than it would make sense to output just the name when `-o name` and there is a single resource type, while using the ideas introduced in #27379 to show the resource type  only when there is more than one type in the output, or when `--show-kind` is explicitly set.
### Example

Before:

``` console
$ kubectl get ns -o name
namespace/default
namespace/demo
```

After:

``` console
$ kubectl get ns -o name
default
demo
```

``` console
$ kubectl get ns -o name --show-kind
namespace/default
namespace/demo
```

``` console
$ kubectl get ns,svc -o name
namespace/default
namespace/demo
service/mysql
```

### PR DESCRIPTION
**Pull request by erhudy**
**What this PR does / why we need it**: `kubectl get namespaces -o name` outputs the names of all namespaces, prefixed with `namespaces/`. This changeset allows these namespace names to be passed directly back in to `kubectl` via the `-n` flag without reprocessing them to remove `namespaces/`.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #29271

**Special notes for your reviewer**:

**Release note**:

```NONE
```

### CODE REVIEW

File: pkg/kubectl/cmd/get.go [hunk 1]
```diff
@@ -178,6 +178,10 @@ func RunGet(f cmdutil.Factory, out, errOut io.Writer, cmd *cobra.Command, args [
 		return err
 	}
 
+	if strings.HasPrefix(cmdNamespace, "namespaces/") {
+		cmdNamespace = strings.Split(cmdNamespace, "/")[1]
```
Comment (liggitt) [inline pkg/kubectl/cmd/get.go]: TrimPrefix would be preferable, since splitting on `/` could accidentally allow accepting `namespaces/foo/bar` as `foo`

Comment (liggitt) [inline pkg/kubectl/cmd/get.go]: also, this should be done in `DefaultNamespace`, not in one specific command. the behavior of `-n ...` should be consistent

**Comment by liggitt** [comment]
cc @kubernetes/sig-cli-pr-reviews 

if `-n` accepted resource-qualified syntax, I'd sort of expect all of them to work... `namespace/foo`, `namespaces/foo`, `ns/foo`, etc.

File: pkg/kubectl/cmd/get.go (hunk 1 above)
Comment (xiangpengzhao) [inline pkg/kubectl/cmd/get.go]: Also, I'm afraid `cmdNamespace = strings.Split(cmdNamespace, "/")[1]` will cause a panic if `cmdNamespace` is specified to `namespaces/`.

Comment (xiangpengzhao) [inline pkg/kubectl/cmd/get.go]: @erhudy could you please add a test case to prove that?

File: pkg/kubectl/cmd/get_test.go [hunk 2]
```diff
@@ -269,6 +269,32 @@ func TestGetObjects(t *testing.T) {
...
+	pods, _, _ := testData()
+
+	f, tf, codec, _ := cmdtesting.NewAPIFactory()
+	tf.Printer = &testPrinter{}
+	tf.UnstructuredClient = &fake.RESTClient{
+		APIRegistry:          api.Registry,
+		NegotiatedSerializer: unstructuredSerializer,
+		Resp:                 &http.Response{StatusCode: 200, Header: defaultHeader(), Body: objBody(codec, &pods.Items[0])},
+	}
+	tf.Namespace = "namespaces/test"
```
Comment (xiangpengzhao) [inline pkg/kubectl/cmd/get_test.go]: Hmmm, I change this line to `tf.Namespace = "namespaces/"` and get a panic. See my comment above :)

```
--- FAIL: TestGetObjectsWithPrefixedNamespace (0.00s)
panic: Fail in goroutine after TestEdit has completed [recovered]
	panic: Fail in goroutine after TestEdit has completed

goroutine 452 [running]:
testing.tRunner.func1(0xc420385040)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x19d2000, 0xc42031fca0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
testing.(*common).Fail(0xc420385ad0)
	/usr/local/go/src/testing/testing.go:445 +0x116
testing.(*common).Errorf(0xc420385ad0, 0x1ccd96c, 0x25, 0xc4208a7b88, 0x4, 0x4)
	/usr/local/go/src/testing/testing.go:518 +0x83
k8s.io/kubernetes/pkg/kubectl/cmd.TestEdit.func5(0xc420af9e50, 0x44, 0x1)
	/home/cloud/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/edit_test.go:264 +0x203
k8s.io/kubernetes/pkg/kubectl/cmd/util.checkErr(0x2a90000, 0xc42031fc10, 0xc42092cf00)
	/home/cloud/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/helpers.go:178 +0x948
k8s.io/kubernetes/pkg/kubectl/cmd/util.CheckErr(0x2a90000, 0xc42031fc10)
	/home/cloud/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/util/helpers.go:119 +0x41
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdGet.func1(0xc420270480, 0xc42023b6e0, 0x2, 0x2)
	/home/cloud/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get.go:122 +0xad
k8s.io/kubernetes/pkg/kubectl/cmd.TestGetObjectsWithPrefixedNamespace(0xc420385040)
	/home/cloud/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/get_test.go:288 +0x455
testing.tRunner(0xc420385040, 0x1d4fdc0)
	/usr/local/go/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:697 +0x2ca
FAIL	k8s.io/kubernetes/pkg/kubectl/cmd	7.986s
make: *** [test] Error 1
```

**Review by xiangpengzhao — CHANGES_REQUESTED** [review]
please also fix the potential panic.

**Comment by erhudy** [comment]
Revised per feedback. The check has been revised to use `strings.TrimPrefix` instead of `strings.Split`, has been moved to the factory implementation, and two tests have been added there to validate the namespace.

Per the concern about the panic, I found that after the change to `strings.TrimPrefix`, specifying `-n namespaces/` would result in this somewhat cryptic error message:
```
	the namespace from the provided object "kube-system" does not match the namespace "". You must pass '--namespace=kube-system' to perform this operation.
```

Specifying `-n ''` did not have the same effect. I added an extra check in the factory implementation to return the simple error **namespace cannot be empty** if somebody passes `-n namespaces/`.

File: pkg/kubectl/cmd/util/factory_client_access.go [hunk 3]
```diff
@@ -451,7 +451,16 @@ func (f *ring0Factory) Resumer(info *resource.Info) ([]byte, error) {
 }
 
 func (f *ring0Factory) DefaultNamespace() (string, bool, error) {
-	return f.clientConfig.Namespace()
+	namespace, boolRetval, err := f.clientConfig.Namespace()
```
Comment (liggitt) [inline pkg/kubectl/cmd/util/factory_client_access.go]: hrmm... here be dragons... leaving an invalid value being returned from clientConfig.Namespace() is no good. for example, see this logic that checks whether the namespace was passed and should override:
```
func (config *DirectClientConfig) Namespace() (string, bool, error) {
	if config.overrides != nil && config.overrides.Context.Namespace != "" {
		// In the event we have an empty config but we do have a namespace override, we should return
		// the namespace override instead of having config.ConfirmUsable() return an error. This allows
		// things like in-cluster clients to execute `kubectl get pods --namespace=foo` and have the
		// --namespace flag honored instead of being ignored.
		return config.overrides.Context.Namespace, true, nil
	}
```

this has to go even deeper, probably into the Namespace() method, and/or possibly into the getContext() method. It's also an open question whether we should accept the `namespace/...` syntax everywhere (e.g. in kubeconfig files, etc) or just via the command-line `-n` flag

Comment (erhudy) [inline pkg/kubectl/cmd/util/factory_client_access.go]: My intent was just to allow it to be valid in `-n`. Would it be an acceptable compromise to throw a fatal error inside here if the result of the trim operation ends up being empty, since that's the only error condition?

Comment (liggitt) [inline pkg/kubectl/cmd/util/factory_client_access.go]: no, it really has to be handled deeper... in the case where they specify a "valid" value of `namespaces/foo`, `clientConfig.Namespace()` would return a value that would be invalid to use directly as a namespace.

Comment (erhudy) [inline pkg/kubectl/cmd/util/factory_client_access.go]: Okay, I will look at pushing it up to the client configuration.

Comment (shiywang) [inline pkg/kubectl/cmd/util/factory_client_access.go]: yes, and having a generic namespace trim function/logic would be good.

**Comment by erhudy** [comment]
Revised again to move the changes into client-go (intentionally only applying to overrides, i.e. supplied through `-n`, and not to the full configuration context).

**Comment by erhudy** [comment]
Pinging @liggitt and @xiangpengzhao for reconsideration.

**Comment by erhudy** [comment]
Pinging @liggitt @xiangpengzhao @smarterclayton @dchen1107 on this PR.

File: staging/src/k8s.io/client-go/tools/clientcmd/client_config.go [hunk 4]
```diff
@@ -296,12 +296,21 @@ func canIdentifyUser(config restclient.Config) bool {
 
 // Namespace implements ClientConfig
 func (config *DirectClientConfig) Namespace() (string, bool, error) {
-	if config.overrides != nil && config.overrides.Context.Namespace != "" {
+	// if an override is provided and it starts with namespaces/ (as generated by `kubectl get ns -o name`), strip it off
+	// (this is intentionally targeted towards interactive use only)
+	namespace := config.overrides.Context.Namespace
```
Comment (xiangpengzhao) [inline staging/src/k8s.io/client-go/tools/clientcmd/client_config.go]: should check `if config.overrides != nil` before this line, or you may get a panic.

File: staging/src/k8s.io/client-go/tools/clientcmd/client_config.go [hunk 5]
```diff
@@ -296,12 +296,21 @@ func canIdentifyUser(config restclient.Config) bool {
...
+	namespacesPrefix := "namespaces/"
+
+	if strings.HasPrefix(namespace, namespacesPrefix) {
+		namespace = strings.TrimPrefix(namespace, namespacesPrefix)
+	}
+
+	if config.overrides != nil && namespace != "" {
```
Comment (xiangpengzhao) [inline staging/src/k8s.io/client-go/tools/clientcmd/client_config.go]: then the condition `config.overrides != nil` can be removed here.

File: staging/src/k8s.io/client-go/tools/clientcmd/client_config_test.go [hunk 6]
```diff
@@ -526,3 +527,43 @@ func TestNamespaceOverride(t *testing.T) {
 
 	matchStringArg("foo", ns, t)
 }
+
+func TestNamespacePrefixStrip(t *testing.T) {
```
Comment (xiangpengzhao) [inline staging/src/k8s.io/client-go/tools/clientcmd/client_config_test.go]: Maybe the two test funcs can be in one single test func with multiple test cases. Anyway, this is ok as-is.

**Review by xiangpengzhao — CHANGES_REQUESTED** [review]

**Comment by erhudy** [comment]
@xiangpengzhao Revised to improve the nil check on `config.overrides`.

File: staging/src/k8s.io/client-go/tools/clientcmd/client_config.go [hunk 7]
```diff
@@ -296,12 +296,23 @@ func canIdentifyUser(config restclient.Config) bool {
 
 // Namespace implements ClientConfig
 func (config *DirectClientConfig) Namespace() (string, bool, error) {
-	if config.overrides != nil && config.overrides.Context.Namespace != "" {
```
Comment (liggitt) [inline staging/src/k8s.io/client-go/tools/clientcmd/client_config.go]: I think this should go even deeper, down into the flag binding itself. We really only want this special handling to apply to the namespace flag itself (not necessarily the override struct), and there are other configs (like DeferredLoadingClientConfig that make use of overrides that would miss any special logic here).

Essentially, we want the data in the overrides struct to be good, not need fixing up. That could be done with a transforming string flag that lets us strip the namespace prefix prior to the value getting stored in the overrides struct - see https://github.com/liggitt/kubernetes/commit/e2478d3fb7c51d2615d10a1134a967a25eed7365 as an example

**Comment by erhudy** [comment]
@liggitt Okay. I cherry-picked your commit onto my branch (to maintain your authorship) and then rewrote the tests so that they're testing values passed in via the `--namespace` flag.

File: staging/src/k8s.io/client-go/tools/clientcmd/overrides_test.go [hunk 8]
```diff
@@ -0,0 +1,55 @@
...
+		"nameSpace/foo":  "foo",
+		"ns/foo":         "foo",
+		"NS/foo":         "foo",
+		"namespaces/":    "namespaces/",
+		"namespace/":     "namespace/",
+		"ns/":            "ns/",
+	}
+
+	for before, after := range testData {
+		BindOverrideFlags(&ConfigOverrides{}, pflag.CommandLine, RecommendedConfigOverrideFlags(""))
```
Comment (liggitt) [inline staging/src/k8s.io/client-go/tools/clientcmd/overrides_test.go]: no need to use `pflag.CommandLine`, can just use a local `fs := &pflag.FlagSet{}`

Comment (liggitt) [inline staging/src/k8s.io/client-go/tools/clientcmd/overrides_test.go]: I'd recommend a local `overrides := &ConfigOverrides{}` as well, and check `overrides.Context.Namespace` rather than `pflag.CommandLine.GetString("namespace")`

**Comment by erhudy** [comment]
Waiting for https://github.com/kubernetes/kubernetes/issues/51692 to be fixed and then resubmitting.

**Comment by liggitt** [comment]
no further comments from me, would like LGTM from @kubernetes/sig-cli-pr-reviews since one of the commits is now made by me

**Comment by ericchiang** [comment]
Logic looks good and it looks like the earlier potential panics were fixed.

/lgtm
