### PR TITLE
Avoid propagating "search ." into containers /etc/resolv.conf

### LINKED ISSUE #112135: musl-based DNS resolution will break on v1.25.0 in certain configurations
### What happened?

This one involves systemd, DNS, musl, and Kubelet v1.25 😬 👷🏻 🔥 

Starting in v1.25.0, pods running on Kubelets on certain nodes with a FQDN hostname (more on that later) will not be able to resolve DNS queries if they're using musl (e.g. alpine:3.16.2, busybox, etc).

```
# OK
kubectl run debug -it --image docker.io/busybox:1.34.1 --rm=true -- wget www.google.com
kubectl run debug -it --image docker.io/busybox:1.34.1-uclibc --rm=true -- wget www.google.com
kubectl run debug -it --image docker.io/ubuntu:22.04 --rm=true -- /bin/sh -c "apt-get update; apt-get install -y wget & wget www.google.com"

# FAIL
kubectl run debug -it --image docker.io/busybox:1.34.1-musl --rm=true -- wget www.google.com
kubectl run debug -it --image docker.io/alpine:3.16.2 --rm=true -- wget www.google.com
```

Our story starts with systemd. Back in 2020, systemd [started populating](https://github.com/systemd/systemd/pull/17201/files) a "search ." in stub resolvers *if* it detected the hostname to be a FQDN (to solve a separate problem). Check for a static hostname with `hostnamectl`.

In https://github.com/kubernetes/kubernetes/pull/109441, a change was made to Kubelet to propagate that "search ." into pods (to solve a separate DNS problem). That change landed in `v1.25.0-alpha.1` and appears in `1.25.0`.

Unfortunatey, musl based DNS resolvers struggle with this "search ." EDIT: details in https://github.com/coreos/fedora-coreos-tracker/issues/1287#issuecomment-1232763947

### What did you expect to happen?

musl-based DNS resolvers (depite their other quirks) should continue to function 

### How can we reproduce it (as minimally and precisely as possible)?

To see if you have a suitable repro node, check your `/etc/resolv.conf` (likely a symlink to `/run/systemd/resolve/stub-resolv.conf`.

```
nameserver 127.0.0.53
options edns0 trust-ad
search .                        <--- this is populated by systemd if your hostname is a FQDN
```

Next, start a container (any CNI) that makes some use of musl resolvers. Confirm that starting in Kubelet v1.25.0, the container `/etc/resolv.conf` now includes the "search ." if it was present on the host.

```
kubectl run debug -it --image docker.io/alpine:3.16.2 --rm=true -- /bin/ash
```

```
search default.svc.cluster.local svc.cluster.local cluster.local .        <--- see this dot at the end
nameserver 10.3.0.10
options ndots:5
```

Try using musl-based DNS resolution.

```
apk update                    # FAILS
wget www.google.com  # FAILS
```

Note that `nslookup` **uses its own DNS resolver**, its not a reproducer. Note also that pod-to-pod traffic and outbound masquerade are fine too. This is not a masquerade problem.

```
nslookup www.google.com
Server:         10.3.0.10
Address:        10.3.0.10:53

Name:   www.google.com
Address: 2607:f8b0:4005:810::2004

Name:   www.google.com
Address: 142.250.189.164
```

Edit the `/etc/resolv.conf` in the container to remove the "." and your musl problems instantly disappear. Add the dot and they're back.

### Anything else we need to know?

I've been spelunking for a while.

* I can confirm this is not related to a specific CNI - flannel, Calico, and Cilium all reproduce the issue. Not networking related
* OpenShift is not affected. In 2021, RedHat folks noticed DNS "breaks" and reverted the systemd change on their OS https://github.com/openshift/okd-machine-os/pull/159

### Folks

cc @Miciah @vrutkovs

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
This isn't cloud provider specific. However, the most likely cases where folks use FQDN's are on-prem imo. So you're likely to see reports originating from there.
</details>

### OS version

<details>
```console
NAME="Fedora Linux"
VERSION="36.20220806.3.0 (CoreOS)"
```
</details>

### Install tools

<details>
This was found while preparing Typhoon's v1.25.0 release of Kubernetes v1.25.0
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd 1.6.6
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by dghubble**
Starting in Kubelet v1.25.0, on certain hosts (those with a FQDN hostname and recent systemd), a "search ." in `/etc/resolv.conf` will now propagate into containers (it did not before v1.25). This breaks musl-based DNS resolution (e.g. any alpine image) for Pods running on such nodes.

https://github.com/kubernetes/kubernetes/issues/112135 provides a lot of details. 

#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

~This reverts commit 5832b84200340344dc0a3e3a360375b3718aa8cd to fix a regression introduced in v1.25.0 (v1.25.0-alpha.1 to be specific). Without this change. alpine or other musl-based containers will fail DNS resolution on certain nodes (described in issue).~

Adapts https://github.com/kubernetes/kubernetes/pull/109441 to avoid propagating `search .` into containers `/etc/resolv.conf`

#### Which issue(s) this PR fixes:

Fixes #112135

#### Does this PR introduce a user-facing change?

```release-note
Fixes a 1.25 regression propagating hosts' `search .` into containers' `/etc/resolv.conf` which can fail DNS resolution
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

* Regression: https://github.com/kubernetes/kubernetes/pull/109441
* Bug Report: https://github.com/kubernetes/kubernetes/issues/112135
* Great details: https://github.com/coreos/fedora-coreos-tracker/issues/1287#issuecomment-1232763947 with packet capture
* Flagged to musl: https://www.openwall.com/lists/musl/2022/08/31/1

Historical:

* systemd change: https://github.com/systemd/systemd/pull/17201
* Host-level workaround: https://github.com/openshift/okd-machine-os/pull/159, https://github.com/poseidon/typhoon/pull/1224

### CODE REVIEW

**Comment by thockin** [comment]
```diff
			searches = []string{}
			for _, s := range fields[1:] {
				if s != "." {
-					s = strings.TrimSuffix(s, ".")
+					searches = append(searches, strings.TrimSuffix(s, "."))
				}
-				searches = append(searches, s)
			}
		}
```

**Comment by dghubble** [comment]
Agreed, https://github.com/kubernetes/kubernetes/pull/109441 seems to be trying to trying to prevent an empty entry. We could solve this differently than propagating "." and confusing musl. I'll update with your suggestion

**Comment by dghubble** [comment]
Updated title, description, and code/tests.

File: pkg/kubelet/network/dns/dns_test.go [hunk 1]
```diff
@@ -77,8 +77,8 @@ func TestParseResolvConf(t *testing.T) {
 		{"nameserver \t 1.2.3.4", []string{"1.2.3.4"}, []string{}, []string{}, false},
 		{"nameserver 1.2.3.4\nnameserver 5.6.7.8", []string{"1.2.3.4", "5.6.7.8"}, []string{}, []string{}, false},
 		{"nameserver 1.2.3.4 #comment", []string{"1.2.3.4"}, []string{}, []string{}, false},
-		{"search ", []string{}, []string{}, []string{}, false}, // search empty
-		{"search .", []string{}, []string{"."}, []string{}, false},
+		{"search ", []string{}, []string{}, []string{}, false},  // search empty
+		{"search .", []string{}, []string{}, []string{}, false}, // ignore lone dot
```
Comment (thockin) [inline pkg/kubelet/network/dns/dns_test.go:81]: Can you please add cases for "search . foo" -> ["foo"] and "search foo ." (same) and "search foo . bar" -> ["foo", "bar"].

Comment (thockin) [inline pkg/kubelet/network/dns/dns_test.go:81]: Can you please add cases for "search . foo" -> ["foo"] and "search foo ." (same) and "search foo . bar" -> ["foo", "bar"].

**Review by thockin — COMMENTED** [review]
Did you test this witrh a MUSL container?

File: pkg/kubelet/network/dns/dns_test.go (hunk 1 above)
Comment (dghubble) [reply pkg/kubelet/network/dns/dns_test.go:81]: added

Comment (dghubble) [reply pkg/kubelet/network/dns/dns_test.go:81]: added

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

/hold

In case @aojea or @danwinship or others want a look

**Comment by thockin** [comment]
if no NAK in a day or two, go ahead and remove hold

**Comment by dghubble** [comment]
I've not built a cluster from this PR. But I've fiddled with this a good bit to discover this 😢 . For my part, in [Typhoon](https://github.com/poseidon/typhoon/releases/tag/v1.25.0) I'm [working around it](https://github.com/poseidon/typhoon/pull/1224) by removing "search ." from hosts which works. I also found manually removing the "." from inside alpine (or similar) containers would fix them, as would removing ndots (undesired). And reverting to Kubelet v1.24.4 also fixed (bc the "." doesn't propagate). So I'm hopeful this is the thing!

**Comment by dghubble** [comment]
Can I get an ok to test?

**Comment by aojea** [comment]
+1

`search .` breaks compatibility, if there is an use case for it we should roll it as a new feature, this sounds like a good solution to me
/lgtm

**Comment by lucab** [comment]
I see the cherry-pick deadline for 1.25.1 is on 2022-09-09 (a week from now).
If this patch lands in `main` quickly within that timeframe, it would be good to aim the same fix at .1 too.

**Comment by aojea** [comment]
> I see the cherry-pick deadline for 1.25.1 is on 2022-09-09 (a week from now). If this patch lands in `main` quickly within that timeframe, it would be good to aim the same fix at 1.25.1 too.

> if no NAK in a day or two, go ahead and remove hold


/hold cancel

**Comment by lucab** [comment]
I proposed this for 1.25.1, cherry-pick at https://github.com/kubernetes/kubernetes/pull/112204.
