### PR TITLE
kubelet: fix containers not restarting when sidecar keeps running

### LINKED ISSUE #136910: Some crashed or OOMKilled containers fail to restart in v1.35
### What happened?

After upgrading Kubernetes from v1.34.2 to v1.35.0, we observed a scenario where a pod with multiple containers does not restart a crashed application container, leaving the pod in an Error state indefinitely.

This behavior was not observed on v1.34.2. Reverting the kubelet back to v1.34.2 causes the issue to disappear.

**Observed Behavior:**
The main container terminates but never restarts:
```
State:          Terminated
  Reason:       Error
  Exit Code:    2
  Started:      Tue, 27 Jan 2026 16:11:01 +0000
  Finished:     Tue, 10 Feb 2026 11:08:55 +0000
Ready:          False
Restart Count:  0
```

The sidecar container continues to run normally:
```
State:          Running
Started:        Tue, 27 Jan 2026 16:10:54 +0000
Ready:          True
Restart Count:  0
```

Pod conditions show:
```
Conditions:
  Type                        Status
  PodReadyToStartContainers   True
  Initialized                 True
  Ready                       False
  ContainersReady             False
  PodScheduled                True
```

No useful logs or errors appear in `kubectl describe pod` output, events, or `kubelet` logs.

**Notes:**
- This issue seems to only affect pods with more than one container
- We are unsure whether it's just pods with an `initContainer` or does it also apply to `container` sidecars
- Manually killing the process in the sidecar container or deleting the pod helps getting it back to working state

**Possibly related?**
- https://github.com/kubernetes/kubernetes/pull/134345

### What did you expect to happen?

Containers should reliably restart every time they crash.

### How can we reproduce it (as minimally and precisely as possible)?

The best way we found to reproduce this is by running a pod with 2 containers: an initContainer with `restartPolicy: Always` and an application container that we manually crash with `kill 1` command.
It might not work right first time, but we managed to reproduce this multiple times getting pods stuck in Error state that they never recover from automatically.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.35.0
Kustomize Version: v5.7.1
Server Version: v1.35.0
```

</details>

### Cloud provider

<details>

Doesn't seem to be related to any particular provider. We have this issue in on-prem and AWS clusters.

</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=4230.2.2
VERSION_ID=4230.2.2
BUILD_ID=2025-08-12-2231
SYSEXT_LEVEL=1.0
PRETTY_NAME="Flatcar Container Linux by Kinvolk 4230.2.2 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar.org/"
BUG_REPORT_URL="https://issues.flatcar.org"
FLATCAR_BOARD="amd64-usr"
CPE_NAME="cpe:2.3:o:flatcar-linux:flatcar_linux:4230.2.2:*:*:*:*:*:*:*"

$ uname -a
Linux ip-10-66-18-99 6.6.100-flatcar #1 SMP PREEMPT_DYNAMIC Tue Aug 12 21:47:31 -00 2025 x86_64 AMD EPYC 7R13 Processor AuthenticAMD GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

```console
$ crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.7.23
RuntimeApiVersion:  v1
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by george-angel**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:

When a pod has a sidecar (initContainer with restartPolicy: Always) with a
startupProbe, and one or more regular containers crash after a kubelet restart,
the kubelet fails to restart the regular containers. RestartCount stays at 0
indefinitely.

When ChangeContainerStatusOnKubeletRestart is disabled (the default since
v1.35), the prober worker skips seeding probe results for containers that
predate the kubelet restart. For a sidecar with a startupProbe this means
startupManager.Get() returns found=false permanently after the restart. In
computeInitContainerActions, the sidecar Running case checks the startup
manager result and breaks out early when found=false, never setting
podHasInitialized=true. computePodActions then returns early at the
!hasInitialized guard before it can add the crashed regular containers to
ContainersToStart.

Fix: when the gate is off and a restartable init container's startup probe is
being seeded for the first time after a kubelet restart, check the container's
Started field in the pod status. If Started=true, the sidecar had already
passed startup before the restart, so seed the startup manager with Success.
Readiness and liveness probes on sidecars are left unseeded, preserving the
behaviour of setReadyStateOnKubeletRestart.

#### Which issue(s) this PR is related to:

Fixes: https://github.com/kubernetes/kubernetes/issues/136910

#### Special notes for your reviewer:

The Started field in the pod status is set by setReadyStateOnKubeletRestart and
preserved across kubelet restarts, making it a reliable signal that the sidecar
had completed startup before the restart occurred. Using it here avoids any
dependency on probe worker timing relative to the sync loop.

A dedicated CI lane that runs with --feature-gates=ChangeContainerStatusOnKubeletRestart=false
was added via test-infra PR #36524 and is passing on this PR.

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug where, after a kubelet restart, regular containers in a pod with a
sidecar (initContainer with restartPolicy: Always) and a startupProbe failed
to restart after crashing. Affected pods remained stuck with RestartCount: 0
indefinitely.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

- [KEP-4781 ChangeContainerStatusOnKubeletRestart]: https://github.com/kubernetes/kubernetes/issues/134746

### CODE REVIEW

File: pkg/kubelet/prober/worker.go [hunk 1]
```diff
@@ -252,14 +252,23 @@ func (w *worker) doProbe(ctx context.Context) (keepGoing bool) {
...
 			if c.State.Running != nil {
 				containerStartTime := c.State.Running.StartedAt.Time
 				if !containerStartTime.IsZero() && containerStartTime.Before(kubeletRestartGracePeriod(w.probeManager.start)) {
 					isRestart = true
 				}
 			}
-			if !isRestart {
+
+			// For sidecars, always set the initial result even on restart
+			isSidecar := w.isInitContainer() &&
```
Comment (HirazawaUi) [inline pkg/kubelet/prober/worker.go]: This code appears twice in this function; we only need to declare the `isRestartableInitContainer` variable once.

File: test/e2e_node/container_lifecycle_test.go [hunk 2]
```diff
@@ -6931,4 +6931,112 @@ var _ = SIGDescribe(framework.WithSerial(), "Not Change Container Status", frame
...
+								InitialDelaySeconds: 1,
+								PeriodSeconds:       1,
+							},
+						},
+					},
+					Containers: []v1.Container{
+						{
+							Name:    "crasher",
+							Image:   defaultImage,
+							Command: []string{"sh", "-c", "sleep 5 && exit 1"},
```
Comment (HirazawaUi) [inline test/e2e_node/container_lifecycle_test.go]: Because we waited 11 seconds before restarting kubelet, the crasher container will begin restarting before kubelet restarts, which will invalidate our verification step since we only verify `status.RestartCount > 0`.

File: test/e2e_node/container_lifecycle_test.go [hunk 3]
```diff
@@ -6931,4 +6931,120 @@ var _ = SIGDescribe(framework.WithSerial(), "Not Change Container Status", frame
...
+								InitialDelaySeconds: 1,
+								PeriodSeconds:       1,
+							},
+						},
+					},
+					Containers: []v1.Container{
+						{
+							Name:  "crasher",
+							Image: defaultImage,
+							// 30s ensures the container is still running after the 11s pre-restart
```
Comment (HirazawaUi) [inline test/e2e_node/container_lifecycle_test.go]: Compared to waiting 30 seconds, perhaps executing kill 1 to terminate process 1 in the container would be better? It would be faster and doesn't require additional waiting/sleep time. We have a utility function for executing commands in containers that we can use.
https://github.com/kubernetes/kubernetes/blob/4a3d82268938cfddd24b0039e49b0a1f35f1527d/test/e2e/framework/pod/exec_util.go#L114

Comment (george-angel) [reply test/e2e_node/container_lifecycle_test.go]: That is so much better, I was looking for something we could do after kubelet restart rather then just waiting for it to be up. Thank you - pushed another commit.

**Comment by george-angel** [comment]
You are correct @HirazawaUi , I missed this. This is much better, thank you - I have pushed the changes.

File: test/e2e_node/container_lifecycle_test.go [hunk 4]
```diff
@@ -6931,4 +6931,107 @@ var _ = SIGDescribe(framework.WithSerial(), "Not Change Container Status", frame
...
+			restartKubelet := mustStopKubelet(ctx, f)
+			restartKubelet(ctx)
+
+			ginkgo.By("ensuring kubelet is healthy")
+			gomega.Eventually(ctx, func() bool {
+				return kubeletHealthCheck(kubeletHealthCheckURL)
+			}, f.Timeouts.PodStart, f.Timeouts.Poll).Should(gomega.BeTrueBecause("kubelet should be started"))
+
+			ginkgo.By("Triggering the crasher container to exit")
+			_, _, err = e2epod.ExecCommandInContainerWithFullOutput(f, pod.Name, "crasher", "touch", "/tmp/die")
```
Comment (HirazawaUi) [inline test/e2e_node/container_lifecycle_test.go]: Can't we terminate the main process in the container by using `kill 1`?

Comment (george-angel) [reply test/e2e_node/container_lifecycle_test.go]: I was getting test failures where I thought the kill signal might not be happening (getting lost), having the proc exit via a file flag felt more reliable, and did result in tests passing. I'm happy to revert to signal and test again.

Comment (HirazawaUi) [reply test/e2e_node/container_lifecycle_test.go]: If you are willing to give it a try, that would be great. I think it would be very useful to verify that the container will enter the running state after a restart, as this cannot be achieved with the existing logic. We only have five days left until the code freeze, so we need to speed up. If it’s not possible, please also let me know the reason.

Comment (george-angel) [reply test/e2e_node/container_lifecycle_test.go]: Please see CI log: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/137146/pull-kubernetes-node-kubelet-serial-change-container-status-on-kubelet-restart/2032342193506619392

I tested kill 1 on this commit: 90c6574992b

It fails the same way as kill -9 1 -- the crasher stays Running with restartCount: 0 and lastState: {} for the full 300s timeout across all three hosts (Ubuntu, COS x2).

The file trigger (touch /tmp/die) run passed: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/137146/pull-kubernetes-node-kubelet-serial-change-container-status-on-kubelet-restart/2030036632932978688

Happy to add the State.Running assertion after RestartCount > 0 as you suggested.

Comment (HirazawaUi) [reply test/e2e_node/container_lifecycle_test.go]: This is because the command you used to run the container does not capture the TERM signal. You can try running the container with the following command:
```
command: ["/bin/sh", "-c", "trap 'echo "Terminated by kill 1"; exit 0' TERM; sleep 3600 & wait $!"]
```

Comment (george-angel) [reply test/e2e_node/container_lifecycle_test.go]: That works, I have changed to the kill trigger, added State.Running check squashed the commits.

**Comment by HirazawaUi** [comment]
/lgtm
/assign @SergeyKanzhelev 
for approval

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve
