### PR TITLE
bandwidth: use regexp to handle tc output and add IPv6 support

### LINKED ISSUE #76064: Kubelet Bandwidth Limiting Not Working
**What happened**:
I tried to set up bandwidth limiting by booting a cluster with `kops`, which by default sets up kubenet. I used the annotations

    - kubernetes.io/egress-bandwidth: xM
    - kubernetes.io/ingress-bandwidth: xM

and then used `iperf3` to test the ingress and egress bandwidths, with no effect.

Does anyone know if this feature is still supported in kubenet? And if so what are the steps I need to take to boot a cluster that can use pod annotations to do tc shaping.

**What you expected to happen**:

Per [#2856](https://github.com/kubernetes/kubernetes/issues/2856) traffic shaping should be implemented on Kubenet as of 4/12/2018.   

**Anything else we need to know?**:

There are a lot of issues regarding traffic shaping not working. None have a concrete answer of how to get it to work on kubenet:
- [#2856](https://github.com/kubernetes/kubernetes/issues/2856)
- [#41471](https://github.com/kubernetes/kubernetes/issues/41471)

Relevant:
- [PR #11988]( https://github.com/kubernetes/kubernetes/pull/11988) I believe this is where it was first implemented.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11.8
- Cloud provider or hardware configuration: AWS

CC:
@mchang6137
@kubernetes/sig-network

### PR DESCRIPTION
**Pull request by chendotjs**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
1. fix newly-added 'chain N' and 'not_in_hw' output from 'tc filter show dev XXX'
2. use regexp to extract info we want from tc output, instead of splitting the output line

**Which issue(s) this PR fixes**:

Fixes #76064

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix a bug where kubenet fails to parse the tc output. 
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/util/bandwidth/linux.go [hunk 1]
```diff
@@ -75,13 +76,14 @@ func (t *tcShaper) nextClassID() (int, error) {
 		if len(line) == 0 {
 			continue
 		}
-		parts := strings.Split(line, " ")
 		// expected tc line:
 		// class htb 1:1 root prio 0 rate 1000Kbit ceil 1000Kbit burst 1600b cburst 1600b
-		if len(parts) != 14 {
-			return -1, fmt.Errorf("unexpected output from tc: %s (%v)", scanner.Text(), parts)
+		classShowMatcher := regexp.MustCompile(`class\shtb\s(1:\d+)\sroot.*rate\s`)
```
Comment (danwinship) [inline pkg/util/bandwidth/linux.go]: Why are you matching the "`root.*rate`" part too? Does that avoid some false positive? (If so maybe update the comment to indicate the kind of line you're trying to avoid matching too.)
Also, I'm not sure that using "`\s`" rather than just "` `" makes this any more generic/future-proof, and it makes it harder to read... (That applies throughout the patch.)
Also, you could make all of the `MustCompile` regexes be top-level variables so they only get compiled once rather than getting recompiled every time

File: pkg/util/bandwidth/linux.go [hunk 2]
```diff
@@ -322,13 +327,14 @@ func (t *tcShaper) GetCIDRs() ([]string, error) {
 			continue
 		}
 		if strings.Contains(line, "match") {
-			parts := strings.Split(line, " ")
 			// expected tc line:
 			// match <cidr> at <number>
-			if len(parts) != 4 {
-				return nil, fmt.Errorf("unexpected output: %v", parts)
+			cidrMatcher := regexp.MustCompile(`match\s([0-9a-f]{8}\/[[0-9a-f]{8}).*\s(\d+)`)
```
Comment (danwinship) [inline pkg/util/bandwidth/linux.go]: I'm not sure this is really an improvement over the old code. Also, it only handles IPv4 (the two hex strings are `{32}`, not `{8}` for IPv6; perhaps the test case should be updated for that). Also, there's no need to put `()`s around the `\d+` since you're not using it.

**Review by danwinship — COMMENTED** [review]
Definitely like the idea

File: pkg/util/bandwidth/linux.go (hunk 1 above)
Comment (chendotjs) [reply pkg/util/bandwidth/linux.go]: Since the code uses  command like `tc class add dev xxx parent 1: classid 1:x htb rate 1kbit` to add a new class where `rate` is an explicit parameter, so "`root.*rate`" ought to be matched explicitly. This is my primitive idea.
Other advice really make sense, thanks

File: pkg/util/bandwidth/linux.go (hunk 2 above)
Comment (chendotjs) [reply pkg/util/bandwidth/linux.go]: Currently IPv6 is not yet supported I suppose?   Because the code uses command like `tc filter add dev xxx protocol ip parent 1:0 prio 1 u32 match ip dst 1.2.3.4/32 flowid 1:2`, the SELECTOR after `match` is `ip`, not `ip6`

Comment (danwinship) [reply pkg/util/bandwidth/linux.go]: ah... `TestHexCIDR` and `TestAsciiCIDR` test IPv6 addresses and the old code would have matched either IPv4 or IPv6 so I assumed we cared. If not then I guess someone will fix this when they add IPv6 support here. (Although I don't know if anyone realized that the bandwidth code doesn't currently support IPv6. @khenidak do you know if this is being tracked?)

Comment (chendotjs) [reply pkg/util/bandwidth/linux.go]: I'm quite sure that IPv6 is not supported currently and I'll fix it.

**Comment by chendotjs** [comment]
PATL this PR if you get some time, it is somewhat large... @danwinship

**Comment by chendotjs** [comment]
/cc @johscheuer  @bowei 
PTAL, thanks

**Comment by chendotjs** [comment]
/cc @squeed @dixudx 
Could you help to review this if you get a chance?

File: pkg/util/bandwidth/linux.go [hunk 3]
```diff
@@ -315,25 +437,111 @@ func (t *tcShaper) GetCIDRs() ([]string, error) {
...
+		cidr, err := asciiCIDR(restoreCIDR)
+		if err != nil {
+			return nil, err
+		}
+		result = append(result, cidr)
 	}
+
 	return result, nil
 }
+func scanCommandOutput(cmdOutput []byte) []string {
```
Comment (johscheuer) [inline pkg/util/bandwidth/linux.go]: The method should be called `convertByteSliceToStringSlice` or something like this instead of `scanCommandOutput`

File: pkg/util/bandwidth/linux.go [hunk 4]
```diff
@@ -189,17 +302,25 @@ func (t *tcShaper) makeNewClass(rate string) (int, error) {
...
 
 func (t *tcShaper) Limit(cidr string, upload, download *resource.Quantity) (err error) {
+	isIPv6 := isIPv6CIDRString(cidr)
+	if isIPv6 {
+		return t.limitIPv4OrIPv6(cidr, upload, download, tcFilterIPv6Protocol, tcFilterIPv6Priority, u32MatchIPv6Protocol)
+	}
+	return t.limitIPv4OrIPv6(cidr, upload, download, tcFilterIPv4Protocol, tcFilterIPv4Priority, u32MatchIPv4Protocol)
+}
+
+func (t *tcShaper) limitIPv4OrIPv6(cidr string, upload, download *resource.Quantity, tcProtocol, priority, matchProtocol string) (err error) {
```
Comment (johscheuer) [inline pkg/util/bandwidth/linux.go]: Why not just `limit` or `limitCIDR` ?

File: pkg/util/bandwidth/linux.go [hunk 5]
```diff
@@ -169,6 +204,84 @@ func (t *tcShaper) findCIDRClass(cidr string) (classAndHandleList [][]string, fo
 	return classAndHandleList, false, nil
 }
 
+func (t *tcShaper) findIPv6CIDRClass(hexCIDR string, cmdOutput []byte) (classAndHandleList [][]string, found bool, err error) {
+	outputLines := scanCommandOutput(cmdOutput)
+
+	var slow, fast int = 0, 0
+	for slow < len(outputLines) && fast < len(outputLines) {
```
Comment (johscheuer) [inline pkg/util/bandwidth/linux.go]: Could you add a comment what the idea behind the `slow` and `fast` is ?

**Review by johscheuer — COMMENTED** [review]
Added some comments. Currently I'm wondering if some of the code duplication for IPv4 and IPv6 could be reduced by making the called methods more generic and  change the behaviour by different input e.g. `findIPv6CIDRClass /findIPv4CIDRClass`.

File: pkg/util/bandwidth/linux.go [hunk 6]
```diff
@@ -129,6 +149,10 @@ func asciiCIDR(cidr string) (string, error) {
 	return fmt.Sprintf("%s/%d", ip.String(), size), nil
 }
 
+func isIPv6CIDRString(cidr string) bool {
```
[the remark this answers is not in the document]
Comment (chendotjs) [reply pkg/util/bandwidth/linux.go]: I have used this function before but it doesn't function as expected. For cidr like `::ffff:1.2.3.4/128`, `net.IsIPv6CIDRString`  will treat it as an IPv4 address, while `tc` still use `ipv6` protocol and `ip6` filter.

This is the test that covers such case.
https://github.com/chendotjs/kubernetes/blob/3b30b38d05a9a7434d089959fd0475cf3a72f0d4/pkg/util/bandwidth/linux_test.go#L996

[the remark this answers is not in the document]
Comment (chendotjs) [reply pkg/util/bandwidth/linux.go]: The PR is updated as your suggestion, please take a look if you get time @johscheuer 
I'm afraid it would be to hard to read or maintain when mixing IPv4 and IPv6 together. The  judgement of whether a cidr is IPv6 is always necessary throughout the combined generic function.

**Comment by markyjackson-taulia** [comment]
Bug triage for 1.17 here with a gentle reminder that code freeze for this release is on November 18. Is this issue still intended for 1.17?

**Comment by chendotjs** [comment]
@markyjackson-taulia gonna add a commit these two days, there ought to be a  final decision next week

**Comment by chendotjs** [comment]
ping @dcbw 
Is this issue still intended for 1.17?

**Comment by chendotjs** [comment]
/assign @MrHohn @freehan 
ptal...

File: pkg/util/bandwidth/linux.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (andrewsykim) [reply pkg/util/bandwidth/linux.go]: Can we update kubernetes/utils to handle this scenario?

[the remark this answers is not in the document]
Comment (chendotjs) [reply pkg/util/bandwidth/linux.go]: IMO, `tc` matcher is a special scenario.

**Comment by markyjackson-taulia** [comment]
@MrHohn @freehan @chendotjs We are fast approaching code freeze on 11/14. Hopefully we can get this in 1.17?

File: pkg/util/bandwidth/linux.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (khenidak) [reply pkg/util/bandwidth/linux.go]: Shouldn't we file this against the golibrary itself? aren't we saying that`net.ParseCIDR(...)` is buggy?

[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/util/bandwidth/linux.go]: It's plausible to claim that `::ffff:1.2.3.4/128` is an IPv4 address, and it's plausible to claim that it's an IPv6 address. It depends why you're asking...

**Comment by markyjackson-taulia** [comment]
Circling back on this @chendotjs @MrHohn @freehan, code freeze is 11/14 and by 5 pm pst I need to make the call if this gets moved out of this milestone.

**Comment by markyjackson-taulia** [comment]
I have had no response to this and code freeze is tomorrow. I have to move this to milestone v1.18

**Comment by dcbw** [comment]
@chendotjs can you rebase to fix the conflict? thanks!

**Comment by chendotjs** [comment]
@dcbw commits have been rebased and squashed.

**Comment by jtslear** [comment]
Hello @danwinship and @dcbw, 
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. Is this PR still intended for milestone 1.18?

**Comment by jtslear** [comment]
Hello @danwinship and @dcbw,
Bug Triage team here for the 1.18 release. This is a friendly reminder that code freeze is scheduled for 5 March. We are waiting review on this PR, there's been no movement on this since mid January.

cc @kubernetes/sig-network-pr-reviews

**Comment by danwinship** [comment]
The IPv6 support here seems extremely complicated and I feel like it ought to be possible to simplify it *a lot*.

I would recommend just reverting back to the original version of the PR, addressing the non-IPv6-related comments, and resubmitting that, and then we can think about IPv6 support again later.

**Comment by chendotjs** [comment]
Truly thanks for your practical advice ! @danwinship
This pr has been reverted and follows the non-IPv6-related comments, ptal if you have time.
