### PR TITLE
Execute the Run function of kubelet, Remove invalid comments and remove run function

### LINKED ISSUE #110690: Execute the Run function of kubelet, no log output after failure
### What happened?

When running kubelet, if the Run function fails, the returned error has no output, and the cause of the error cannot be located.
https://github.com/kubernetes/kubernetes/blob/a9f83d839ec311ceaf4ef8ed35dbdfcff8ae0b3a/cmd/kubelet/app/server.go#L268

such as 
https://github.com/kubernetes/kubernetes/blob/a9f83d839ec311ceaf4ef8ed35dbdfcff8ae0b3a/pkg/kubelet/cm/cgroup_manager_linux.go#L278
After the error is returned, there is no position output, so the user cannot know the cause of the error.

But previous versions had log output
https://github.com/kubernetes/kubernetes/blob/938a3203c609d42b61512a55f42344ce1438f5a9/pkg/kubelet/cm/cgroup_manager_linux.go#L300

https://github.com/kubernetes/kubernetes/blob/938a3203c609d42b61512a55f42344ce1438f5a9/cmd/kubelet/app/server.go#L301

### What did you expect to happen?

Run the Run function, when there is an error exit, print the error log

### How can we reproduce it (as minimally and precisely as possible)?

Misconfigured cgroupRoot

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
root@e2e-control-plane:/#  kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:18:48Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}


```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Run the Run function, when there is an error exit, print the error log
#### Which issue(s) this PR fixes:

Fixes #110690

#### Does this PR introduce a user-facing change?

```release-note
Run kubelet, when there is an error exit, print the error log

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yangjunmyfm192085 — COMMENTED** [review]
/retest

**Review by yangjunmyfm192085 — COMMENTED** [review]
/cc @pohly 
Or we modify to the way as kube-apiserver?
such as:
https://github.com/kubernetes/kubernetes/blob/4f97d6c94215f3973b25742be3669ad5e9c4b2d4/cmd/kube-apiserver/apiserver.go#L34

File: cmd/kubelet/app/server.go [hunk 1]
```diff
@@ -265,7 +265,11 @@ HTTP server: The kubelet can also listen for HTTP and respond to a simple API
 			ctx := genericapiserver.SetupSignalContext()
```
Comment (pohly) [inline cmd/kubelet/app/server.go:265]: This seems odd. Why is the caller not printing the error when RunE returns it?

File: cmd/kubelet/app/server.go [hunk 2]
```diff
@@ -265,7 +265,11 @@ HTTP server: The kubelet can also listen for HTTP and respond to a simple API
...
 
 			// run the kubelet
-			return Run(ctx, kubeletServer, kubeletDeps, utilfeature.DefaultFeatureGate)
+			err = Run(ctx, kubeletServer, kubeletDeps, utilfeature.DefaultFeatureGate)
+			if err != nil {
+				klog.ErrorS(err, "Failed to run kubelet")
+			}
+			return err
```
Comment (pohly) [inline cmd/kubelet/app/server.go:272]: This seems odd. Why is the caller not printing the error when RunE returns it?

**Comment by pohly** [comment]
> Or we modify to the way as kube-apiserver?

Yes, making the main function more like in other commands would be the preferred solution. I don't remember why that wasn't already done.

File: cmd/kubelet/app/server.go (hunk 2 above)
Comment (yangjunmyfm192085) [reply cmd/kubelet/app/server.go:272]: I think the code is just made a judgment and did not print, 
```
	if err := command.Execute(); err != nil {
		return 1
	}
	return 0
```
But I noticed that this code has been modified again recently.

https://github.com/kubernetes/kubernetes/commit/7a5af811e7ef8c289865d9239b86dc4dde1e2ba2

@yxxhero, I noticed that the annotation describes
```
	// kubelet uses a config file and does its own special
	// parsing of flags and that config file. It initializes
	// logging after it is done with that. Therefore it does
	// not use cli.Run like other, simpler commands.
```
Is your modification correct?

Comment (pohly) [reply cmd/kubelet/app/server.go:272]: That comment should have been removed in https://github.com/kubernetes/kubernetes/commit/7a5af811e7ef8c289865d9239b86dc4dde1e2ba2 because clearly now kubelet does use cli.Run.

Originally, that comment was correct. InitLogs had to be called after flag parsing, and kubelet therefore couldn't use cli.run.

But that restriction has been lifted when allowing reconfiguration of the flush interval in 18bf5d23f122589e1ef24bb68e8c5f3662fe2467

Comment (pohly) [reply cmd/kubelet/app/server.go:272]: https://github.com/kubernetes/kubernetes/commit/7a5af811e7ef8c289865d9239b86dc4dde1e2ba2 cannot be backported to 1.24. In 1.24, adding error printing to https://github.com/kubernetes/kubernetes/blob/2a550bc1cdcbe5c47ba56b17a48598be9df40cb3/cmd/kubelet/kubelet.go#L56 is the best solution.

Comment (yangjunmyfm192085) [reply cmd/kubelet/app/server.go:272]: Yeah I think you are right, Let me take a look,thanks

**Review by yangjunmyfm192085 — COMMENTED** [review]
Due to the following modification, the issue that the main branch cannot print the log has been solved.
This pr is only used to delete invalid logs.
In the 1.24 branch I will take pohly's suggestion and resubmit pr to fix
https://github.com/kubernetes/kubernetes/commit/7a5af811e7ef8c289865d9239b86dc4dde1e2ba2

File: cmd/kubelet/kubelet.go [hunk 3]
```diff
@@ -36,11 +36,6 @@ import (
 
 func main() {
 	command := app.NewKubeletCommand()
-
-	// kubelet uses a config file and does its own special
-	// parsing of flags and that config file. It initializes
-	// logging after it is done with that. Therefore it does
-	// not use cli.Run like other, simpler commands.
```
Comment (pohly) [inline cmd/kubelet/kubelet.go:43]: Can you also eliminate the run function? It serves no purpose anymore.

Comment (pohly) [reply cmd/kubelet/kubelet.go:43]: And remove `command.SetGlobalNormalizationFunc(cliflag.WordSepNormalizeFunc)`?

That is done by cli.Run: https://github.com/kubernetes/kubernetes/blob/fa16bf8e121e9a9ce0a8b92d96a39c986152c484/staging/src/k8s.io/component-base/cli/run.go#L92

Comment (yangjunmyfm192085) [reply cmd/kubelet/kubelet.go:43]: I have updated. could you please take a look again, thanks? @pohly

**Review by pohly — APPROVED** [review]
/lgtm

**Review by yangjunmyfm192085 — COMMENTED** [review]
/triage accepted
/assign @mrunalp

**Review by mrunalp — APPROVED** [review]
