### PR TITLE
Fixes #65869 Do not listen insecurely if secure port is specified

### LINKED ISSUE #65869: external cloud-controller-manager listens insecurely by default
/kind bug

**What happened**:
When building a cloud-controller-manager using the pro-forma manifests, the cloud-controller ends up listening insecurely on port 10253 by default

**What you expected to happen**:

The documentation should explain what the cloud-controller-manager is doing on that port, and how to secure it - assuming it is required. 

I'd expect it wouldn't listen insecurely by default on all addresses 

**How to reproduce it (as minimally and precisely as possible)**:

All the manifests for the external cloud controllers detailed here 

https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/

do nothing with --port or --secure-port

The one I'm writing

https://github.com/brightbox/brightbox-cloud-controller-manager

using the same sort of manifest ends up listening insecurely on 0.0.0.0 on port 10253 unless I use '--port 0' to stop it.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-rc.1", GitCommit:"8745ea56e3f1f3ad20050c1762eb6ba6f7786675", GitTreeState:"clean", BuildDate:"2018-06-21T00:01:04Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-rc.1", GitCommit:"8745ea56e3f1f3ad20050c1762eb6ba6f7786675", GitTreeState:"clean", BuildDate:"2018-06-20T23:52:01Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
brightbox
- OS (e.g. from /etc/os-release):
Ubuntu 18.03 LTS
- Kernel (e.g. `uname -a`):
Linux srv-yywho 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
Kubeadm/terraform
- Others:

### PR DESCRIPTION
**Pull request by aruneli**
**What this PR does / why we need it:**
Make ccm not listen insecurely if secure port is specified 

**Which issue(s) this PR fixes:**
https://github.com/kubernetes/kubernetes/issues/65869

**Special notes for your reviewer:**

I have made it such that the insecure port will be turned off if the secure-port flag is used. Here is the new behavior with this PR.

1. By default, ccm only listens on secure port 10258
2. If secure port is set, only secure port is changed to new port
3. If only `--port` option is used, the ccm will listen on insecure port and default secure port (*current behavior*)
4. If both `--port` and `--secure-port` are provided, then current behavior is retained

```release-note
CCM server will not listen insecurely if secure port is specified
```

@stts @andrewsykim @jhorwit2 @wlan0 Please review

### CODE REVIEW

**Comment by wlan0** [comment]
Thanks for the PR @aruneli 

LGTM. Pulled the code and tested it.

@stts @andrewsykim @jhorwit2 Pls review as well.

**Comment by wlan0** [comment]
@aruneli There is a test failure. Pls fix

**Comment by aruneli** [comment]
I signed it

**Comment by aruneli** [comment]
I signed it

**Comment by jhorwit2** [comment]
@aruneli Please take a look at the failing integration tests. There's a panic due to something being nil it seems.

/check-cla

File: cmd/cloud-controller-manager/app/options/options.go [hunk 1]
```diff
@@ -44,13 +44,16 @@ import (
 	"k8s.io/kubernetes/pkg/api/legacyscheme"
 	"k8s.io/kubernetes/pkg/controller"
 	"k8s.io/kubernetes/pkg/master/ports"
+
 	// add the kubernetes feature gates
```
Comment (stewart-yu) [inline cmd/cloud-controller-manager/app/options/options.go]: IMO, we have given the comment in the next line, this blank line seems no need

**Review by stewart-yu — COMMENTED** [review]
I'm little confused about this PR, seems discard the 10253 port absolutly?

**Comment by stewart-yu** [comment]
Have you signed the CLA?

File: cmd/cloud-controller-manager/app/options/options.go (hunk 1 above)
Comment (aruneli) [reply cmd/cloud-controller-manager/app/options/options.go]: Fixed

**Comment by cheftako** [comment]
It looks like it will change the behavior of the CCM CLI. Before your change it would default to listening on port 10253 unless you explicitly turned off the port. With your change the server will not listen to that port (more secure) however that is a change. If the change was after the deprecation period, then the option would just be done away with. Before the deprecation period, I think it at least needs an action release note. I believe the deprecation was recent so we should make sure to have an action release note.

**Comment by wlan0** [comment]
Ping @foxish
