### PR TITLE
kubeadm: support automatic retry after failing to pull image

### LINKED ISSUE #1844: Retries for init images
/kind bug

I believe it is a bug that kubeadm init does not retry image pulling on a failed connection. Recently we ran a test, specifically @vivgoyal did that created 200 cluster-api clusters bootstrapped with kubeadm. 1% (2) of the clusters failed to `kubeadm init` during the image pull stage. A retry would likely have eliminated this failure case.

## Versions

I believe this affects all versions of kubeadm

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
kubeadm: support automatic retry after failing to pull image

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#1844

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: support automatic retry after failing to pull image
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/util/runtime/runtime.go [hunk 1]
```diff
@@ -151,20 +151,28 @@ func (runtime *DockerRuntime) RemoveContainers(containers []string) error {
...
+	var lastError error
+	for i := 0; i < constants.PullImageRetry; i++ {
+		out, err := runtime.exec.Command("crictl", "-r", runtime.criSocket, "pull", image).CombinedOutput()
+		if err == nil {
+			return nil
+		}
+		lastError = errors.Wrapf(err, "output: %s, error", string(out))
 	}
-	return nil
+	return lastError
```
Comment (aojea) [inline cmd/kubeadm/app/util/runtime/runtime.go]: do you need `lastError`?
it seems that you can return directly `return errors.Wrapf(err, "output: %s, error", string(out))`

File: cmd/kubeadm/app/preflight/checks_test.go [hunk 2]
```diff
@@ -780,6 +788,14 @@ func TestImagePullCheck(t *testing.T) {
...
 			func(cmd string, args ...string) exec.Cmd { return fakeexec.InitFakeCmd(&fcmd, cmd, args...) },
 			func(cmd string, args ...string) exec.Cmd { return fakeexec.InitFakeCmd(&fcmd, cmd, args...) },
+			func(cmd string, args ...string) exec.Cmd { return fakeexec.InitFakeCmd(&fcmd, cmd, args...) },
+			func(cmd string, args ...string) exec.Cmd { return fakeexec.InitFakeCmd(&fcmd, cmd, args...) },
+			func(cmd string, args ...string) exec.Cmd { return fakeexec.InitFakeCmd(&fcmd, cmd, args...) },
+			func(cmd string, args ...string) exec.Cmd { return fakeexec.InitFakeCmd(&fcmd, cmd, args...) },
+			func(cmd string, args ...string) exec.Cmd { return fakeexec.InitFakeCmd(&fcmd, cmd, args...) },
+			func(cmd string, args ...string) exec.Cmd { return fakeexec.InitFakeCmd(&fcmd, cmd, args...) },
+			func(cmd string, args ...string) exec.Cmd { return fakeexec.InitFakeCmd(&fcmd, cmd, args...) },
+			func(cmd string, args ...string) exec.Cmd { return fakeexec.InitFakeCmd(&fcmd, cmd, args...) },
```
Comment (neolit123) [inline cmd/kubeadm/app/preflight/checks_test.go]: this looks really silly, but it's not the fault of this PR.

File: cmd/kubeadm/app/preflight/checks_test.go [hunk 3]
```diff
@@ -761,10 +761,18 @@ func TestImagePullCheck(t *testing.T) {
 		CombinedOutputScript: []fakeexec.FakeAction{
 			// Test case1: pull only img3
 			func() ([]byte, []byte, error) { return nil, nil, nil },
-			// Test case 2: fail to pull image2 and image3
+			// Test case 2: fail to pull image2 and image3 (if the pull fails, it will be retried 5 times by default)
```
Comment (neolit123) [inline cmd/kubeadm/app/preflight/checks_test.go]: please format the comment like so:
```
// Test case 2: fail to pull image2 and image3
// If the pull fails, it will be retried 5 times (see PullImageRetry in constants/constants.go)
```

File: cmd/kubeadm/app/constants/constants.go [hunk 4]
```diff
@@ -181,6 +181,8 @@ const (
 	PatchNodeTimeout = 2 * time.Minute
 	// TLSBootstrapTimeout specifies how long kubeadm should wait for the kubelet to perform the TLS Bootstrap
 	TLSBootstrapTimeout = 2 * time.Minute
+	// PullImageRetry specifies how many times ContainerRuntime retries when pulling image failed
+	PullImageRetry = 5
```
Comment (neolit123) [inline cmd/kubeadm/app/constants/constants.go]: when we originally discussed this there were also comments about using exponential backoff.
i'm fine with using 5 retries, but let's see if anyone has more comments.

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-kind-ipv6 
unrelated failures, known flakes, PR is ok

**Review by neolit123 — COMMENTED** [review]
/approve

File: cmd/kubeadm/app/preflight/checks_test.go (hunk 2 above)
Comment (bart0sh) [reply cmd/kubeadm/app/preflight/checks_test.go]: may be something similar to [this](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/runtime/runtime_test.go#L74:L82) can reduce this noise.

File: cmd/kubeadm/app/util/runtime/runtime.go [hunk 5]
```diff
@@ -151,20 +151,28 @@ func (runtime *DockerRuntime) RemoveContainers(containers []string) error {
 
 // PullImage pulls the image
 func (runtime *CRIRuntime) PullImage(image string) error {
-	out, err := runtime.exec.Command("crictl", "-r", runtime.criSocket, "pull", image).CombinedOutput()
-	if err != nil {
-		return errors.Wrapf(err, "output: %s, error", string(out))
+	var err error
+	var out []byte
+	for i := 0; i < constants.PullImageRetry; i++ {
+		out, err = runtime.exec.Command("crictl", "-r", runtime.criSocket, "pull", image).CombinedOutput()
```
Comment (bart0sh) [inline cmd/kubeadm/app/util/runtime/runtime.go]: Ignoring errors here doesn't look good to me.

File: cmd/kubeadm/app/util/runtime/runtime.go [hunk 6]
```diff
@@ -151,20 +151,28 @@ func (runtime *DockerRuntime) RemoveContainers(containers []string) error {
...
+		if err == nil {
+			return nil
+		}
 	}
-	return nil
+	return errors.Wrapf(err, "output: %s, error", string(out))
```
Comment (bart0sh) [inline cmd/kubeadm/app/util/runtime/runtime.go]: string() call is not needed here.

**Review by yastij — COMMENTED** [review]
/lgtm
/hold

@bart0sh feel free to unhold

File: cmd/kubeadm/app/util/runtime/runtime.go (hunk 5 above)
Comment (yastij) [reply cmd/kubeadm/app/util/runtime/runtime.go]: it's not ignoring, it retries until it succeeds if it doesn't it logs the error. We can still log the error on each retry but I'm not sure if it's needed

File: cmd/kubeadm/app/util/runtime/runtime.go (hunk 6 above)
Comment (SataQiu) [reply cmd/kubeadm/app/util/runtime/runtime.go]: Thanks @bart0sh 
Updated!

**Comment by SataQiu** [comment]
@bart0sh @yastij @neolit123 Do you have time to look it again?

**Review by yastij — COMMENTED** [review]
/lgtm
/hold cancel
