### PR TITLE
StatefulSet: Respect ControllerRef

### LINKED ISSUE #36859: StatefulSets with the same selector interfere with each other
**What happened**:
When two statefulsets are created with the same labels, only one manages to come up.
This is caused by the same issue as https://github.com/kubernetes/kubernetes/issues/36855#issuecomment-260828249.

**What you expected to happen**:
Two StatefulSets should be created, instead, one was created, and another was unable to come up.

```
~ kubectl get pods --watch
NAME      READY     STATUS    RESTARTS   AGE
ss2-0     1/1       Running   0          7s
ss2-1     1/1       Running   0          6s
ss2-2     1/1       Running   0          4s
NAME      READY     STATUS    RESTARTS   AGE
ss1-0     0/1       Pending   0          1s
ss1-0     0/1       Pending   0         1s
ss1-0     0/1       ContainerCreating   0         1s
ss1-0     1/1       Running   0         2s
ss1-0     1/1       Terminating   0         2s
ss1-0     1/1       Terminating   0         2s
ss1-0     0/1       Pending   0         0s
ss1-0     0/1       Pending   0         0s
ss1-0     0/1       ContainerCreating   0         1s
ss1-0     1/1       Running   0         2s
ss1-0     1/1       Terminating   0         2s
ss1-0     1/1       Terminating   0         2s
```

**How to reproduce it** (as minimally and precisely as possible):

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ss1
spec:
  serviceName: "ss1"
  replicas: 3
  template:
    metadata:
      labels:
        app: ss
    spec:
      containers:
      - name: alpine
        image: alpine
        command: 
        - /bin/sleep
        - "1000000"
```

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ss2
spec:
  serviceName: "ss2"
  replicas: 3
  template:
    metadata:
      labels:
        app: ss
    spec:
      containers:
      - name: alpine
        image: alpine
        command: 
        - /bin/sleep
        - "1000000"
```

**What we should be doing**:

- Do not filter on the label selector to find the pods associated with a PetSet.

cc @kubernetes/sig-apps

### PR DESCRIPTION
**Pull request by enisoc**
**What this PR does / why we need it**:

This is part of the completion of the [ControllerRef](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/controller-ref.md) proposal. It brings StatefulSet into full compliance with ControllerRef. See the individual commit messages for details.

**Which issue this PR fixes**:

Fixes #36859

**Special notes for your reviewer**:

**Release note**:

```release-note
StatefulSet now respects ControllerRef to avoid fighting over Pods. At the time of upgrade, **you must not have StatefulSets with selectors that overlap** with any other controllers (such as ReplicaSets), or else [ownership of Pods may change](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/controller-ref.md#upgrading).
```
cc @erictune @kubernetes/sig-apps-pr-reviews

### CODE REVIEW

**Comment by kow3ns** [comment]
Reviewed 11 of 11 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/controller/statefulset/stateful_set.go, line 271 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42080#-Kdm1kDEIOuCdOEctTHX:-Kdm1kDEIOuCdOEctTHY:b-crz5y9) ([raw file](https://github.com/kubernetes/kubernetes/blob/eb95066be044617287f6bb45d56e77ba4e776e5e/pkg/controller/statefulset/stateful_set.go#L271)):*
> ```Go
> 	}
> 
> 	filter := func(pod *v1.Pod) bool {
> ```

you should use
```go
filter := func(pod *v1.Pod) bool {
        return isMember(set, pod)
}
```

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42080)*

File: pkg/controller/statefulset/stateful_set.go [hunk 1]
```diff
@@ -163,15 +180,41 @@ func (ssc *StatefulSetController) updatePod(old, cur interface{}) {
...
+			} else {
+				ssc.enqueueStatefulSet(set)
+			}
+		}
+	}
+
+	// If it has a ControllerRef, that's all that matters.
+	if curControllerRef != nil {
+		set, err := ssc.setLister.StatefulSets(curPod.Namespace).Get(curControllerRef.Name)
+		if err != nil {
```
Comment (smarterclayton) [inline pkg/controller/statefulset/stateful_set.go]: Technically you should be handling NotFound here, but I don't think there's a downside.

File: pkg/controller/statefulset/stateful_set.go [hunk 2]
```diff
@@ -163,15 +180,41 @@ func (ssc *StatefulSetController) updatePod(old, cur interface{}) {
...
+			utilruntime.HandleError(fmt.Errorf("Couldn't get StatefulSet %q in namespace %q: %v", curControllerRef.Name, curPod.Namespace, err))
```
Comment (smarterclayton) [inline pkg/controller/statefulset/stateful_set.go]: style: All error messages should start lowercase (`couldn't get StatefulSet ...`)

Comment (smarterclayton) [inline pkg/controller/statefulset/stateful_set.go]: Applies to all commits in this PR

File: pkg/controller/statefulset/stateful_set.go (hunk 1 above)
Comment (kargakis) [inline pkg/controller/statefulset/stateful_set.go]: Yeah, we usually just handle the `err == nil` case

Comment (enisoc) [inline pkg/controller/statefulset/stateful_set.go]: @smarterclayton @kargakis Can you elaborate? I'm not sure if you two are agreeing with each other or not.

Are you saying I should skip the call to `HandleError()` if `IsNotFound(err)` is true?

File: pkg/controller/statefulset/stateful_set.go (hunk 2 above)
Comment (enisoc) [inline pkg/controller/statefulset/stateful_set.go]: Done.

**Comment by enisoc** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/controller/statefulset/stateful_set.go, line 271 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42080#-Kdm1kDEIOuCdOEctTHX:-KdmQetB38VyPkDpek1q:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/eb95066be044617287f6bb45d56e77ba4e776e5e/pkg/controller/statefulset/stateful_set.go#L271)):*
<details><summary><i>Previously, kow3ns (Kenneth Owens) wrote…</i></summary><blockquote>

you should use
```go
filter := func(pod *v1.Pod) bool {
        return isMember(set, pod)
}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42080)*

File: pkg/controller/statefulset/stateful_set.go (hunk 1 above)
Comment (kargakis) [inline pkg/controller/statefulset/stateful_set.go]: Oh, I misread @smarterclayton. Usually in resource handlers we don't handle errors at all.

File: pkg/controller/statefulset/stateful_set.go [hunk 3]
```diff
@@ -49,13 +49,18 @@ const (
 	statefulSetResyncPeriod = 30 * time.Second
 )
 
+// ControllerKind contains the schema.GroupVersionKind for this controller type.
+var ControllerKind = apps.SchemeGroupVersion.WithKind("StatefulSet")
```
Comment (kargakis) [inline pkg/controller/statefulset/stateful_set.go]: unexport if you don't need it outside of the package

File: pkg/controller/statefulset/stateful_set.go [hunk 4]
```diff
@@ -142,15 +148,40 @@ func (ssc *StatefulSetController) Run(workers int, stopCh <-chan struct{}) {
...
+	// If it has a ControllerRef, that's all that matters.
+	if controllerRef := controller.GetControllerOf(pod); controllerRef != nil {
+		if controllerRef.Kind != ControllerKind.Kind {
+			// It's controlled by a different type of controller.
+			return
+		}
+		set, err := ssc.setLister.StatefulSets(pod.Namespace).Get(controllerRef.Name)
+		if err != nil {
+			// Don't log NotFound. That just means the GC will soon delete the Pod.
+			if !errors.IsNotFound(err) {
```
Comment (kargakis) [inline pkg/controller/statefulset/stateful_set.go]: The cache returns only 404s:
https://github.com/kubernetes/kubernetes/blob/77733c2afdcc4e85595e990d69d9b2765b1cf4e1/pkg/client/listers/apps/v1beta1/statefulset.go#L92
https://github.com/kubernetes/kubernetes/blob/77733c2afdcc4e85595e990d69d9b2765b1cf4e1/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L392

File: pkg/controller/statefulset/stateful_set.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/controller/statefulset/stateful_set.go]: In general, any place where we utilruntime.HandleError, we should ask "if the item is not found, can we just return without logging anything safely instead".  In some places that is obvious (resource was deleted, we don't need to do anything further), in others it is not (we have to handle deletion safely).

Comment (enisoc) [inline pkg/controller/statefulset/stateful_set.go]: In my case, I believe it's safe to do nothing if the error is NotFound. I was only intending to log transient errors, but @kargakis has reminded me elsewhere that this interface is backed by a cache that cannot fail for any reason other than NotFound. So, I plan to remove the call to HandleError in these cases.

Thanks for clarifying.

**Comment by kow3ns** [comment]
Reviewed 4 of 6 files at r3.
Review status: 13 of 15 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42080)*

**Comment by kow3ns** [comment]
Reviewed 2 of 6 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42080)*

**Comment by enisoc** [comment]
@k8s-bot bazel test this
@k8s-bot node e2e test this
@k8s-bot kops aws e2e test this

File: pkg/controller/statefulset/stateful_set.go [hunk 5]
```diff
@@ -153,16 +159,42 @@ func (ssc *StatefulSetController) Run(workers int, stopCh <-chan struct{}) {
...
 func (ssc *StatefulSetController) addPod(obj interface{}) {
 	pod := obj.(*v1.Pod)
-	glog.V(4).Infof("Pod %s created, labels: %+v", pod.Name, pod.Labels)
-	set := ssc.getStatefulSetForPod(pod)
-	if set == nil {
+
+	if pod.DeletionTimestamp != nil {
+		// on a restart of the controller manager, it's possible a new pod shows up in a state that
+		// is already pending deletion. Prevent the pod from being a creation observation.
+		ssc.deletePod(pod)
```
Comment (kargakis) [inline pkg/controller/statefulset/stateful_set.go]: We should only care for pods owned by stateful sets

File: pkg/controller/statefulset/stateful_set_control.go [hunk 6]
```diff
@@ -111,6 +112,12 @@ func (ssc *defaultStatefulSetControl) UpdateStatefulSet(set *apps.StatefulSet, p
 		}
 	}
 
+	// If the StatefulSet is being deleted, don't do anything other than updating
+	// status.
+	if set.DeletionTimestamp != nil {
+		return nil
```
Comment (kargakis) [inline pkg/controller/statefulset/stateful_set_control.go]: @kow3ns we should have a helper that would do just that - iterate over all pods and update the status accordingly.

Comment (kargakis) [inline pkg/controller/statefulset/stateful_set_control.go]: For now, it seems that this check is in the right place.

File: pkg/controller/statefulset/stateful_set.go (hunk 5 above)
Comment (enisoc) [inline pkg/controller/statefulset/stateful_set.go]: That check is done inside `deletePod()`. Is there a benefit to doing it before as well?

**Comment by kow3ns** [comment]
/lgtm

---

Reviewed 4 of 7 files at r4, 2 of 2 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/42080#-:-KeKi-ONsvSw1yGVKC8B:b-8ks5qa)*

File: pkg/controller/statefulset/stateful_set.go (hunk 5 above)
Comment (kargakis) [inline pkg/controller/statefulset/stateful_set.go]: Nvmd, it's fine.

**Comment by enisoc** [comment]
@k8s-bot node e2e test this
@k8s-bot gce etcd3 e2e test this
@k8s-bot cvm gke e2e test this
@k8s-bot gci gke e2e test this
@k8s-bot cvm gce e2e test this

**Comment by enisoc** [comment]
@k8s-bot kops aws e2e test this
@k8s-bot non-cri e2e test this
@k8s-bot gci gce e2e test this
@k8s-bot gce etcd3 e2e test this

**Comment by enisoc** [comment]
@kow3ns This just needs re-LGTM after some e2e fixes (see last couple commits) and rebases.
