### PR TITLE
Fix TestCreateWithNonExistentOwner

### LINKED ISSUE #30228: TestCreateWithNonExistentOwner {garbagecollector}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-test-go/15489/

Failed: TestCreateWithNonExistentOwner {garbagecollector}

```
garbage_collector_test.go:281: garbage collector queues drained
garbage_collector_test.go:283: expect pod test.pod.1 to be garbage collected
```

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #30228
As https://github.com/kubernetes/kubernetes/issues/30228#issuecomment-248779567 described, the GC did delete the garbage, it's the test logic failed. 
The test used to rely on `gc.QueuesDrained()`, which could return before the GC finished processing. It seems to be the only possible reason of the test failure. Hence, this PR changed the test to poll for the deletion of garbage.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33235)

### CODE REVIEW

**Comment by caesarxuchao** [comment]
@mml could you help review it?

File: test/integration/garbagecollector/garbage_collector_test.go [hunk 1]
```diff
@@ -278,15 +276,20 @@ func TestCreateWithNonExistentOwner(t *testing.T) {
 	stopCh := make(chan struct{})
 	go gc.Run(5, stopCh)
 	defer close(stopCh)
-	// wait for the garbage collector to drain its queue
-	if err := wait.Poll(10*time.Second, 120*time.Second, func() (bool, error) {
-		return gc.QueuesDrained(), nil
```
Comment (caesarxuchao) [inline test/integration/garbagecollector/garbage_collector_test.go]: I removed QueueDrained(). PTAL. Thanks.

File: test/integration/utils.go [hunk 2]
```diff
@@ -69,3 +73,19 @@ var Code409 = map[int]bool{409: true}
 var Code422 = map[int]bool{422: true}
 var Code500 = map[int]bool{500: true}
 var Code503 = map[int]bool{503: true}
+
+// WaitForPodToDisappear polls the API server if the pod has been deleted.
+func WaitForPodToDisappear(podClient coreclient.PodInterface, podName string, interval, timeout time.Duration) error {
+	return wait.PollImmediate(interval, timeout, func() (bool, error) {
+		_, err := podClient.Get(podName)
+		if err == nil {
```
Comment (lavalamp) [inline test/integration/utils.go]: nit: to be super safe this should probably check the UID just in case the pod was deleted and recreated with the same name. Probably not worth changing as that should be really rare, but maybe worth a TODO?

**Comment by lavalamp** [comment]
LGTM-- I'll let you decide if you want to fix the nit and apply the label.

File: test/integration/utils.go (hunk 2 above)
Comment (caesarxuchao) [inline test/integration/utils.go]: I'll be lazy this time. The function is used in integration tests and I expect the caller won't intentionally recreate the pod. UID can be added when it's needed.

**Comment by caesarxuchao** [comment]
Applying the label per comment. Thanks for reviewing it.
