### PR TITLE
rkt: Return `FinishedAt` for pod

### LINKED ISSUE #23887: `FinishedAt` in ContainerStateTerminated is not supported by rkt
Previous discussion in https://github.com/coreos/rkt/issues/1789

Missing `FinishedAt` caused 2 e2e tests to fail. But it seems no tests are testing the `Signal` field yet.

cc @kubernetes/sig-node @jonboulle @sjpotter @euank

### PR DESCRIPTION
**Pull request by euank**
This is implemented via touching a file on stop as a hook in the systemd
unit. The ctime of this file is then used to get the `finishedAt` time
in the future.
In addition, this changes the `startedAt` and `createdAt` to use the api
server's results rather than the annotations it previously used.

It's possible we might want to move this into the api in the future.

Fixes #23887

I did the following manual testing:

```
$ cat ./examples/output/exit-output.yml 
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: exit
  name: exit-output
spec:
  restartPolicy: Never
  containers:
    - name: exit
      image: busybox
      command: ["sh", "-c", "echo Exiting in 60; sleep 60; echo goodbye"]
$ kubectl create -f ./examples/exit/exit-output.yaml
$ # wait
$ kubectl describe pod exit-output | grep State -A 4
    State:      Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 19 Apr 2016 13:23:13 -0700
      Finished:     Tue, 19 Apr 2016 13:24:13 -0700
$ kubectl logs exit-output
Exiting in 60
goodbye
```

I double checked as well that the file at `/var/lib/kubelet/pods/$id/finished-$id` existed and looked as expected.

This is related to https://github.com/coreos/rkt/issues/1789#issuecomment-207111814 and follows https://github.com/kubernetes/kubernetes/pull/24367 + https://github.com/coreos/rkt/issues/2445

cc @jonboulle @iaguis @yifan-gu @kubernetes/sig-node

### CODE REVIEW

File: pkg/kubelet/rkt/rkt.go [hunk 1]
```diff
@@ -884,8 +925,10 @@ func (r *Runtime) preparePod(pod *api.Pod, pullSecrets []api.Secret) (string, *k
 	// TODO handle pod.Spec.HostPID
 	// TODO handle pod.Spec.HostIPC
 
+	markPodFinished := podFinishedMarkCommand(r.touchPath, r.runtimeHelper.GetPodDir(pod.UID), uuid)
```
Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: I think we can point out that for now we only have pod level finish time, but later we should support per app's finish time.

File: pkg/kubelet/rkt/mock_os/mockfileinfo.go [hunk 2]
```diff
@@ -0,0 +1,91 @@
+// Automatically generated by MockGen. DO NOT EDIT!
```
Comment (yifan-gu) [inline pkg/kubelet/rkt/mock_os/mockfileinfo.go]: How is this file generated?

File: pkg/kubelet/rkt/rkt.go [hunk 3]
```diff
@@ -128,12 +127,19 @@ type Runtime struct {
...
+	// used for a systemd Exec, which requires the full path.
+	touchPath string
 
 	versions versions
 }
 
 var _ kubecontainer.Runtime = &Runtime{}
 
+// Provide a hook for unit tests to override osStat with a mock implementation
+var osStat = os.Stat
```
Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: Can we leverage pkg/kubelet/container/os.go ?

File: pkg/kubelet/rkt/mock_os/mockfileinfo.go (hunk 2 above)
Comment (euank) [inline pkg/kubelet/rkt/mock_os/mockfileinfo.go]: `mockgen os FileInfo > mock_fileinfo/mockfileinfo.go`, happy to check-in a comment or `go:generate` for it, but I didn't see other examples of go generate and I don't expect this to change often (ever) because it's a go1 interface, not a k8 interface.

**Comment by yifan-gu** [comment]
LGTM

@k8s-bot OK to test.

cc @yujuhong for another pair of eyes.

**Comment by yifan-gu** [comment]
LGTM

cc @yujuhong @Random-Liu as this touches kubelet/docker code a bit as well.

File: pkg/kubelet/rkt/rkt.go [hunk 4]
```diff
@@ -1078,8 +1113,8 @@ func (r *Runtime) convertRktPod(rktpod *rktapi.Pod) (*kubecontainer.Pod, error)
 			// By default, the version returned by rkt API service will be "latest" if not specified.
 			Image:   fmt.Sprintf("%s:%s", app.Image.Name, app.Image.Version),
 			Hash:    containerHash,
-			Created: podCreated,
 			State:   appStateToContainerState(app.State),
+			Created: rktpod.CreatedAt,
```
Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: @euank Hmm, seems like the Created here has the unit of 'second', but rktPod.CreatedAt has the unit of 'nanosecond'.

Comment (euank) [inline pkg/kubelet/rkt/rkt.go]: Good call, though I'm pretty sure that field isn't read anywhere. I'll update it appropriately and also do a PR to remove it entirely separately.

Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: @euank SGTM.

**Comment by yifan-gu** [comment]
@euank LGTM after squash.

**Comment by yujuhong** [comment]
lgtm but rkt unit test failed :-)

**Comment by euank** [comment]
The unit test should be fixed (squashed in, it's just converting the mock created seconds to ns).

**Comment by yifan-gu** [comment]
The travis build doesn't complete?

**Comment by yujuhong** [comment]
> The travis build doesn't complete?

Yes, it's #24628 :-(

**Comment by yifan-gu** [comment]
@euank Need rebase?

**Comment by euank** [comment]
Rebased, should just need a lgtm

**Comment by euank** [comment]
Rebased again so travis would be happy and lost the lgtm :(
