### PR TITLE
Fixed gke auth update wait condition.

### LINKED ISSUE #50945: [e2e test failure] [sig-api-machinery] Aggregator Should be able to support the 1.7 Sample API Server using the current Aggregator
##### Error text:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/aggregator.go:65
creating cluster role wardler
Expected error:
    <*errors.StatusError | 0xc421134380>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "clusterroles.rbac.authorization.k8s.io \"wardler\" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:[\"flunders\"], APIGroups:[\"wardle.k8s.io\"], Verbs:[\"create\"]} PolicyRule{Resources:[\"flunders\"], APIGroups:[\"wardle.k8s.io\"], Verbs:[\"delete\"]} PolicyRule{Resources:[\"flunders\"], APIGroups:[\"wardle.k8s.io\"], Verbs:[\"deletecollection\"]} PolicyRule{Resources:[\"flunders\"], APIGroups:[\"wardle.k8s.io\"], Verbs:[\"get\"]} PolicyRule{Resources:[\"flunders\"], APIGroups:[\"wardle.k8s.io\"], Verbs:[\"list\"]} PolicyRule{Resources:[\"flunders\"], APIGroups:[\"wardle.k8s.io\"], Verbs:[\"patch\"]} PolicyRule{Resources:[\"flunders\"], APIGroups:[\"wardle.k8s.io\"], Verbs:[\"update\"]} PolicyRule{Resources:[\"flunders\"], APIGroups:[\"wardle.k8s.io\"], Verbs:[\"watch\"]} PolicyRule{NonResourceURLs:[\"*\"], Verbs:[\"get\"]}] user=&{pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:[\"selfsubjectaccessreviews\"], APIGroups:[\"authorization.k8s.io\"], Verbs:[\"create\"]} PolicyRule{NonResourceURLs:[\"/api\" \"/api/*\" \"/apis\" \"/apis/*\" \"/healthz\" \"/swaggerapi\" \"/swaggerapi/*\" \"/version\"], Verbs:[\"get\"]}] ruleResolutionErrors=[]",
            Reason: "Forbidden",
            Details: {
                Name: "wardler",
                Group: "rbac.authorization.k8s.io",
                Kind: "clusterroles",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 403,
        },
    }
    clusterroles.rbac.authorization.k8s.io "wardler" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["flunders"], APIGroups:["wardle.k8s.io"], Verbs:["create"]} PolicyRule{Resources:["flunders"], APIGroups:["wardle.k8s.io"], Verbs:["delete"]} PolicyRule{Resources:["flunders"], APIGroups:["wardle.k8s.io"], Verbs:["deletecollection"]} PolicyRule{Resources:["flunders"], APIGroups:["wardle.k8s.io"], Verbs:["get"]} PolicyRule{Resources:["flunders"], APIGroups:["wardle.k8s.io"], Verbs:["list"]} PolicyRule{Resources:["flunders"], APIGroups:["wardle.k8s.io"], Verbs:["patch"]} PolicyRule{Resources:["flunders"], APIGroups:["wardle.k8s.io"], Verbs:["update"]} PolicyRule{Resources:["flunders"], APIGroups:["wardle.k8s.io"], Verbs:["watch"]} PolicyRule{NonResourceURLs:["*"], Verbs:["get"]}] user=&{pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/aggregator.go:331
```
##### Failure cluster statistics:
1 tests failed,    11 jobs failed,    241 builds failed.
Failure stats cover 1 day time range '17 Aug 2017 22:57 UTC' to '18 Aug 2017 22:57 UTC'.
##### Top failed tests by jobs failed:

| Test Name | Jobs Failed |
| --- | --- |
| [sig-api-machinery] Aggregator Should be able to support the 1.7 Sample API Server using the current Aggregator | 11 |

##### Top failed jobs by builds failed:

| Job Name | Builds Failed | Latest Failure |
| --- | --- | --- |
| ci-kubernetes-e2e-gci-gke-multizone | 42 | [18 Aug 2017 22:02 UTC](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke-multizone/13432) |
| ci-kubernetes-e2e-gci-gke | 40 | [18 Aug 2017 22:00 UTC](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gke/13636) |
| ci-kubernetes-e2e-gke-multizone | 40 | [18 Aug 2017 22:11 UTC](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-multizone/14175) |

[Current Status](https://go.k8s.io/triage#42229f8b33f735ea0213)

### PR DESCRIPTION
**Pull request by cheftako**
Lookup whoami on gke using gcloud auth list.
Make sure we do not run the test on any cluster older than 1.7.

**What this PR does / why we need it**: Fixes issue with aggregator e2e test on GKE

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50945 

**Special notes for your reviewer**: There is a TODO, follow up will be provided when the immediate problem is resolved.

**Release note**: ```release-note
NONE
```

### CODE REVIEW

File: test/e2e/apimachinery/aggregator.go [hunk 1]
```diff
@@ -161,12 +166,21 @@ func TestSampleAPIServer(f *framework.Framework, image, namespaceName string) {
...
+		/*var name string
+		if subject.Kind == rbacv1beta1.ServiceAccountKind {
+			name = serviceaccount.MakeUsername(ns, subject.Name)
+		} else {
+			name = subject.Name
+		}
+		err := framework.WaitForAuthorizationUpdate(client.AuthorizationV1beta1(), name, "",
+			"create", schema.GroupResource{Group: "rbac.authorization.k8s.io", Resource: "clusterroles"}, true)
+		framework.ExpectNoError(err, "Failed to update authorization for '%v': %v", f.ClientSubject, err)*/
+		time.Sleep(10 * time.Second)
```
Comment (cheftako) [inline test/e2e/apimachinery/aggregator.go]: Its a guess. One of the reasons the TODO is there. We *should* be waiting to see the authorization update (the commented out code). However that was not seeing the change. Once we get 1.8 unblocked I will go back and work out why its not working.

File: test/e2e/apimachinery/aggregator.go [hunk 2]
```diff
@@ -161,12 +166,21 @@ func TestSampleAPIServer(f *framework.Framework, image, namespaceName string) {
...
 		// kubectl create clusterrolebinding user-cluster-admin-binding --clusterrole=cluster-admin --user=user@domain.com
-		framework.BindClusterRole(client.RbacV1beta1(), "cluster-admin", ns,
-			rbacv1beta1.Subject{Kind: rbacv1beta1.ServiceAccountKind, Namespace: ns, Name: "default"})
-		err := framework.WaitForAuthorizationUpdate(client.AuthorizationV1beta1(),
-			serviceaccount.MakeUsername(ns, "default"),
-			"", "get", schema.GroupResource{Group: "storage.k8s.io", Resource: "storageclasses"}, true)
-		framework.ExpectNoError(err, "Failed to update authorization: %v", err)
+		//subject := *f.ClientSubject
+		authenticated := rbacv1beta1.Subject{Kind: rbacv1beta1.GroupKind, Name: user.AllAuthenticated}
+		framework.Logf("WRF - setting permissions on %v.", authenticated)
```
Comment (cheftako) [inline test/e2e/apimachinery/aggregator.go]: Good call. Fixed.

File: test/e2e/framework/framework.go [hunk 3]
```diff
@@ -176,6 +179,25 @@ func getClientRepoConfig(src *restclient.Config) (dst *clientreporestclient.Conf
 	return dst
 }
 
+func (f *Framework) whoAmI() (*rbacv1beta1.Subject, error) {
+	if ProviderIs("gke") {
+		out, err := exec.Command("gcloud", "auth", "list", "--filter=status:ACTIVE", "--format=value(account)").CombinedOutput()
+		Logf("WRF:whoAmi error %v", err)
+		Logf("WRF:whoAmi %s", string(out))
```
Comment (lavalamp) [inline test/e2e/framework/framework.go]: Remove debug code (or make the message pretty).

File: test/e2e/framework/framework.go [hunk 4]
```diff
@@ -176,6 +179,25 @@ func getClientRepoConfig(src *restclient.Config) (dst *clientreporestclient.Conf
...
+		if err != nil {
+			return nil, err
+		}
+		name := string(out)
+		if strings.HasSuffix(name, ".iam.gserviceaccount.com") {
```
Comment (lavalamp) [inline test/e2e/framework/framework.go]: I feel like this is actually part of the username and shouldn't be stripped out? Otherwise there could be collisions?

@cjcullen @destijl

File: test/e2e/apimachinery/aggregator.go [hunk 5]
```diff
@@ -161,12 +166,20 @@ func TestSampleAPIServer(f *framework.Framework, image, namespaceName string) {
...
-			rbacv1beta1.Subject{Kind: rbacv1beta1.ServiceAccountKind, Namespace: ns, Name: "default"})
-		err := framework.WaitForAuthorizationUpdate(client.AuthorizationV1beta1(),
-			serviceaccount.MakeUsername(ns, "default"),
-			"", "get", schema.GroupResource{Group: "storage.k8s.io", Resource: "storageclasses"}, true)
-		framework.ExpectNoError(err, "Failed to update authorization: %v", err)
+		//subject := *f.ClientSubject
+		authenticated := rbacv1beta1.Subject{Kind: rbacv1beta1.GroupKind, Name: user.AllAuthenticated}
+		framework.BindClusterRole(client.RbacV1beta1(), "cluster-admin", ns, authenticated)
+		// TODO: cheftako - Get this working with whoami/ClientSubject & WaitForAuthorizationUpdate
+		/*var name string
```
Comment (lavalamp) [inline test/e2e/apimachinery/aggregator.go]: Can we maybe get a version of this PR with the dead code removed? Feels bad to check in commented out code even if it is temporary. Sometimes temporary is longer than we'd like... :)

File: test/e2e/apimachinery/aggregator.go [hunk 6]
```diff
@@ -33,7 +33,9 @@ import (
 	"k8s.io/apimachinery/pkg/runtime/schema"
 	"k8s.io/apimachinery/pkg/util/intstr"
 	"k8s.io/apimachinery/pkg/util/wait"
-	"k8s.io/apiserver/pkg/authentication/serviceaccount"
+	utilversion "k8s.io/kubernetes/pkg/util/version"
+	//"k8s.io/apiserver/pkg/authentication/serviceaccount"
```
Comment (lavalamp) [inline test/e2e/apimachinery/aggregator.go]: Omit unused (sorry to be a pain, but...)

File: test/e2e/framework/framework.go (hunk 3 above)
Comment (cheftako) [inline test/e2e/framework/framework.go]: Removed all "dead" code. It will be coming back once I get a chance to fix the TODO.

File: test/e2e/framework/framework.go (hunk 4 above)
Comment (cheftako) [inline test/e2e/framework/framework.go]: Removed all "dead" code. It will be coming back once I get a chance to fix the TODO. Will make sure this is correct once I can test with a service account.

File: test/e2e/apimachinery/aggregator.go (hunk 5 above)
Comment (cheftako) [inline test/e2e/apimachinery/aggregator.go]: Removed all "dead" code. It will be coming back once I get a chance to fix the TODO.

File: test/e2e/apimachinery/aggregator.go (hunk 6 above)
Comment (cheftako) [inline test/e2e/apimachinery/aggregator.go]: Removed all "dead" code. It will be coming back once I get a chance to fix the TODO.

File: test/e2e/apimachinery/aggregator.go [hunk 7]
```diff
@@ -161,12 +165,10 @@ func TestSampleAPIServer(f *framework.Framework, image, namespaceName string) {
...
-		framework.BindClusterRole(client.RbacV1beta1(), "cluster-admin", ns,
-			rbacv1beta1.Subject{Kind: rbacv1beta1.ServiceAccountKind, Namespace: ns, Name: "default"})
-		err := framework.WaitForAuthorizationUpdate(client.AuthorizationV1beta1(),
-			serviceaccount.MakeUsername(ns, "default"),
-			"", "get", schema.GroupResource{Group: "storage.k8s.io", Resource: "storageclasses"}, true)
-		framework.ExpectNoError(err, "Failed to update authorization: %v", err)
+		authenticated := rbacv1beta1.Subject{Kind: rbacv1beta1.GroupKind, Name: user.AllAuthenticated}
+		framework.BindClusterRole(client.RbacV1beta1(), "cluster-admin", ns, authenticated)
+		// TODO: cheftako - Get this working with whoami/ClientSubject & WaitForAuthorizationUpdate
+		time.Sleep(10 * time.Second)
```
Comment (lavalamp) [inline test/e2e/apimachinery/aggregator.go]: Is it possible to retry something until it starts working?

maybe you could issue a subject access review call to find out?

**Comment by lavalamp** [comment]
/lgtm
/approve

thanks for bearing with me.
