### PR TITLE
Made tests that create Horizontal Pod Autoscaler delete it after they are done.

### LINKED ISSUE #46847: Add an e2e test measuring the time it takes for HPA and CA to scale up after load increase
Currently the time it takes for HPA and CA to scale up after load increase is not measured at all, and this can lead to regressions that will be missed. This issue is about adding an e2e test that will prevent such regressions.

@wojtek-t @fgrzadkowski

### PR DESCRIPTION
**Pull request by wasylkowski**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #46847

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wasylkowski** [comment]
Ref: #46847

**Comment by wasylkowski** [comment]
@wojtek-t Friendly ping

File: test/e2e/autoscaling/horizontal_pod_autoscaling.go [hunk 1]
```diff
@@ -116,7 +116,8 @@ type HPAScaleTest struct {
 func (scaleTest *HPAScaleTest) run(name, kind string, rc *common.ResourceConsumer, f *framework.Framework) {
 	rc = common.NewDynamicResourceConsumer(name, kind, int(scaleTest.initPods), int(scaleTest.totalInitialCPUUsage), 0, 0, scaleTest.perPodCPURequest, 200, f)
 	defer rc.CleanUp()
-	common.CreateCPUHorizontalPodAutoscaler(rc, scaleTest.targetCPUUtilizationPercent, scaleTest.minPods, scaleTest.maxPods)
+	hpa := common.CreateCPUHorizontalPodAutoscaler(rc, scaleTest.targetCPUUtilizationPercent, scaleTest.minPods, scaleTest.maxPods)
```
Comment (wojtek-t) [inline test/e2e/autoscaling/horizontal_pod_autoscaling.go]: hpa seems unused here - please remove

File: test/e2e/common/autoscaling_utils.go [hunk 2]
```diff
@@ -491,6 +491,11 @@ func CreateCPUHorizontalPodAutoscaler(rc *ResourceConsumer, cpu, minReplicas, ma
...
 	}
-	_, errHPA := rc.framework.ClientSet.Autoscaling().HorizontalPodAutoscalers(rc.framework.Namespace.Name).Create(hpa)
+	hpa, errHPA := rc.framework.ClientSet.Autoscaling().HorizontalPodAutoscalers(rc.framework.Namespace.Name).Create(hpa)
 	framework.ExpectNoError(errHPA)
+	return hpa
 }
+
+func DeleteHorizontalPodAutoscaler(rc *ResourceConsumer, autoscalerName string) {
+	rc.framework.ClientSet.Autoscaling().HorizontalPodAutoscalers(rc.framework.Namespace.Name).Delete(autoscalerName, nil)
+}
```
Comment (wojtek-t) [inline test/e2e/common/autoscaling_utils.go]: please remove this funny red char at the end of line

**Review by wojtek-t — COMMENTED** [review]
Some minor comments.

**Comment by wojtek-t** [comment]
@k8s-bot ok to test

File: test/e2e/autoscaling/horizontal_pod_autoscaling.go (hunk 1 above)
Comment (wasylkowski) [inline test/e2e/autoscaling/horizontal_pod_autoscaling.go]: It is used. The next line accesses it :-)

Comment (wojtek-t) [inline test/e2e/autoscaling/horizontal_pod_autoscaling.go]: Sorry - I think I didn't see the next line at all....

File: test/e2e/common/autoscaling_utils.go (hunk 2 above)
Comment (wasylkowski) [inline test/e2e/common/autoscaling_utils.go]: I tried, but then gofmt complains. This funny red char means there is no EOL after the last line, and this is what gofmt expects.

**Comment by wasylkowski** [comment]
Made formatting fixes. @k8s-bot pull-kubernetes-bazel test this

File: test/e2e/common/autoscaling_utils.go (hunk 2 above)
Comment (wojtek-t) [inline test/e2e/common/autoscaling_utils.go]: But we don't have in other files. I think that is' because you're using some IDE - I don't have those if I'm using vim, and I'm pretty sure @gmarek have those sometimes when using some IDE.

Comment (wojtek-t) [inline test/e2e/common/autoscaling_utils.go]: BTW - it seems to be gone now.

**Comment by wasylkowski** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by wasylkowski** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by wasylkowski** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by wasylkowski** [comment]
@wojtek-t Ping
