### PR TITLE
kube-proxy node manager (take 2)

### LINKED ISSUE #9266: cloud-node-manager doesn't set Node IPs before kube-proxy expects them
#### What happened:

CAPZ tests building clusters against the k/k master branch have started to fail since https://github.com/kubernetes/kubernetes/pull/130837. In each test on the first control plane node, kube-proxy is blocked because the node does not yet have an IP address in its `status.addresses`:
```
E0714 23:43:34.151306       1 run.go:72] "command failed" err="host IP unknown; known addresses: [{Hostname capz-conf-52kbqe-control-plane-7ksnv}]"
```

And cloud-node-manager is blocked trying to resolve the IP of the kube-apiserver service:
```
F0714 23:39:30.939254       1 nodemanager.go:148] Failed to wait for apiserver being healthy: timed out waiting for the condition: failed to get apiserver /healthz status: Get "https://10.96.0.1:443/healthz": dial tcp 10.96.0.1:443: i/o timeout
```

#### What you expected to happen:

It seems that cloud-node-manager shouldn't be depending on a functional kube-proxy before setting Node IPs.

#### How to reproduce it (as minimally and precisely as possible):

Any CAPZ-based test using k/k artifacts from the past couple of days, e.g. https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/cloud-provider-azure-master-capz/1944789136837709824

#### Environment:

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by danwinship**
#### What this PR does / why we need it:
Re-push of #130837, with more care to exactly preserve backward-compatibility so as to fix https://github.com/kubernetes-sigs/cloud-provider-azure/issues/9266. (@aroradaman is busy and didn't have time to redo this before code freeze so I picked it up.)

> This carries the work done in https://github.com/kubernetes/kubernetes/pull/125382 consolidates and simplifies how kube-proxy deals and watches over Node objects.

(Note: initial push is just a straight revert with the bug, so I can confirm that there's an e2e available here that will demonstrate it.)

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/kind cleanup
/sig network
/area kube-proxy
/priority important-soon
/triage accepted

### CODE REVIEW

File: pkg/proxy/node.go [hunk 1]
```diff
@@ -109,3 +122,121 @@ func (n *NodeEligibleHandler) OnNodeDelete(node *v1.Node) { n.HealthServer.SyncN
...
+
+		nodeIPs, err = utilnode.GetNodeHostIPs(node)
+		if err != nil {
+			return false, nil
+		}
+
+		return true, nil
+	})
+
+	// For backward-compatibility, we keep going even if we didn't find a node or it
```
Comment (aroradaman) [inline pkg/proxy/node.go]: > // Note: NewNodeManager doesn't return any error if failed to retrieve NodeIPs.

But we are returning error in case of timeout here.

File: pkg/proxy/node.go [hunk 2]
```diff
@@ -109,3 +122,121 @@ func (n *NodeEligibleHandler) OnNodeDelete(node *v1.Node) { n.HealthServer.SyncN
...
+	n.onNodeChange(node)
+}
+
+// onNodeChange functions helps to implement OnNodeAdd and OnNodeUpdate.
+func (n *NodeManager) onNodeChange(node *v1.Node) {
+	nodeIPs, _ := utilnode.GetNodeHostIPs(node)
+
+	// We exit whenever there is a change in NodeIPs detected initially, and NodeIPs received
+	// on node watch event.
+	if !reflect.DeepEqual(n.nodeIPs, nodeIPs) {
```
Comment (aroradaman) [inline pkg/proxy/node.go:196]: note to myself: do we need to exit here? For cloud-providers the IP will be nil on bootstrap, it will trigger a pod restart..

File: pkg/proxy/node.go [hunk 3]
```diff
@@ -169,6 +119,15 @@ func newNodeManager(ctx context.Context, client clientset.Interface, resyncInter
...
+		// we only wait for PodCIDRs if NodeManager is configured with watchPodCIDRs
+		if watchPodCIDRs && len(podCIDRs) == 0 {
+			if len(node.Spec.PodCIDRs) > 0 {
+				podCIDRs = node.Spec.PodCIDRs
+			} else {
+				return false, nil
+			}
+		}
+
 		nodeIPs, err = utilnode.GetNodeHostIPs(node)
```
Comment (aroradaman) [inline pkg/proxy/node.go]: here instead of waiting for 30seconds we will wait for 5 minutes if node got PodCIDRs but NodeIPs are still not assigned, but I guess that would never happen.

File: pkg/proxy/node.go (hunk 1 above)
Comment (aroradaman) [reply pkg/proxy/node.go]: Ignore, the code was updated before I finished review.

Comment (danwinship) [reply pkg/proxy/node.go]: We only return an error if `watchPodCIDRs` is set and we can't fetch the PodCIDRs. (If `watchPodCIDRs` is set and we are able to fetch the PodCIDRs but not the NodeIPs, we _don't_ return an error; the unit test checks this.)

That should be compatible with the old behavior, where `waitForPodCIDR` would return an error if it timed out, but `getNodeIPs` would just return `nil`.

File: pkg/proxy/node.go (hunk 2 above)
Comment (danwinship) [reply pkg/proxy/node.go:196]: It's not going to be nil on bootstrap with _all_ cloud providers (or we would have failed e2e in the original PR). Just some cloud providers, in some deployment configurations.

For the linux proxiers, as long as the primary IP family doesn't change, we don't actually need to restart... we could just force a full resync, like on a topology change. (For winkernel, or for a primary IP family change on linux, we need a restart.)

File: pkg/proxy/node.go (hunk 3 above)
Comment (danwinship) [reply pkg/proxy/node.go]: podcidrs and nodeips are assigned by totally different controllers. I guess that could happen...

File: pkg/proxy/node.go (hunk 2 above)
Comment (danwinship) [reply pkg/proxy/node.go:196]: Oh, I didn't realize "restart on IP change" was new with NodeManager... I thought we did that before...

Comment (danwinship) [reply pkg/proxy/node.go:196]: oh, nodeIPs are also used with `--nodeport-addresses primary` (which is the default for nftables)

**Comment by danwinship** [comment]
/hold
I want @aojea to review this before re-merging

File: pkg/proxy/node.go (hunk 2 above)
Comment (danwinship) [reply pkg/proxy/node.go:196]: OK, I think we do eventually want the restart-on-nodeIP-change behavior, but maybe not a week before code freeze...

**Review by aroradaman — COMMENTED** [review]
/lgtm
I don't see any breaking change here 😄

**Comment by aojea** [comment]
_checking_

File: pkg/proxy/config/config_test.go [hunk 4]
```diff
@@ -457,3 +460,137 @@ func TestNewEndpointsMultipleHandlersAddRemoveSetAndNotified(t *testing.T) {
...
+	topologyLabels map[string]string
+}
+
+func (n *nodeTopologyHandlerMock) OnTopologyChange(topologyLabels map[string]string) {
+	n.topologyLabels = topologyLabels
+}
+
+// waitForInvocation waits for event handler to complete processing of the invocation.
+func waitForInvocation(invoked <-chan struct{}) error {
+	for {
```
Comment (aojea) [inline pkg/proxy/config/config_test.go]: this for loop is not really needed, the select blocks and both statement return

File: pkg/proxy/config/config.go [hunk 5]
```diff
@@ -483,3 +466,86 @@ func (c *ServiceCIDRConfig) handleServiceCIDREvent(oldObj, newObj interface{}) {
...
+func (n *NodeTopologyConfig) handleNodeEvent(obj interface{}) {
+	node, ok := obj.(*v1.Node)
+	if !ok {
+		utilruntime.HandleError(fmt.Errorf("unexpected object type: %v", obj))
+		return
+	}
+
+	topologyLabels := make(map[string]string)
+	if _, ok = node.Labels[v1.LabelTopologyZone]; ok {
+		topologyLabels[v1.LabelTopologyZone] = node.Labels[v1.LabelTopologyZone]
```
Comment (aojea) [inline pkg/proxy/config/config.go:518]: note to self, at the end we just pass the value of `v1.LabelTopologyZone`

File: pkg/proxy/node.go (hunk 2 above)
Comment (aojea) [reply pkg/proxy/node.go:196]: > OK, I think we do eventually want the restart-on-nodeIP-change behavior, but maybe not a week before code freeze...

we do restart on PodCIDR change https://github.com/kubernetes/kubernetes/pull/111344 because that is inmutable once set, we should restart only if the nodeIP changes after set, but remember we allow to go from one nodeIP to two nodeIPs,

File: pkg/proxy/node.go [hunk 6]
```diff
@@ -171,6 +155,17 @@ func (n *NodeManager) PodCIDRs() []string {
...
 
+// Node returns a copy of the latest node object, or nil if the Node has not yet been seen.
+func (n *NodeManager) Node() *v1.Node {
+	n.mu.Lock()
+	defer n.mu.Unlock()
+
+	if n.node == nil {
+		return nil
+	}
+	return n.node.DeepCopy()
```
Comment (aojea) [inline pkg/proxy/node.go:166]: are we mutating the node object somewhere?

File: pkg/proxy/config/config.go [hunk 7]
```diff
@@ -290,8 +287,7 @@ func NewNodeConfig(ctx context.Context, nodeInformer v1informers.NodeInformer, r
 
 	handlerRegistration, _ := nodeInformer.Informer().AddEventHandlerWithResyncPeriod(
 		cache.ResourceEventHandlerFuncs{
-			AddFunc:    result.handleAddNode,
```
Comment (aojea) [inline pkg/proxy/config/config.go:310]: you are removing the Add event handler, so is not really merging add an update

File: pkg/proxy/config/config.go [hunk 8]
```diff
@@ -321,32 +317,22 @@ func (c *NodeConfig) Run(stopCh <-chan struct{}) {
...
-		return
+		tombstone, ok := obj.(cache.DeletedFinalStateUnknown)
+		if !ok {
+			utilruntime.HandleError(fmt.Errorf("unexpected object type: %v", obj))
+			return
+		}
+		if node, ok = tombstone.Obj.(*v1.Node); !ok {
+			utilruntime.HandleError(fmt.Errorf("unexpected object type: %v", obj))
+			return
+		}
```
Comment (aojea) [inline pkg/proxy/config/config.go]: you only handle the new object on an Update, and presumable also for the Add, this is only needed for Deleted objects, does not seem needed here

File: pkg/proxy/node.go (hunk 2 above)
Comment (aojea) [reply pkg/proxy/node.go:196]: agree with Dan, let' not introduce new behaviors at this point

File: pkg/proxy/node.go (hunk 6 above)
Comment (aroradaman) [reply pkg/proxy/node.go:166]: This felt safe, we don't need to worry if the consumers are accidentally mutating the object.

File: pkg/proxy/config/config_test.go (hunk 4 above)
Comment (danwinship) [reply pkg/proxy/config/config_test.go]: ah, this got rewritten a few times in the earlier PR. the loop probably made more sense originally...

File: pkg/proxy/node.go (hunk 6 above)
Comment (danwinship) [reply pkg/proxy/node.go:166]: Not _currently_, no. Daman and I went back and forth on this a few times; I had argued that we should just document "you aren't allowed to modify the returned object", but he preferred the more future-proof/idiot-proof solution.

File: pkg/proxy/config/config.go (hunk 7 above)
Comment (danwinship) [reply pkg/proxy/config/config.go:310]: hm... it seems we don't have unit tests of this

File: pkg/proxy/node.go (hunk 6 above)
Comment (aojea) [reply pkg/proxy/node.go:166]: I do not have strong opinion, just was curious, I don't think is a performance problem in this case

File: pkg/proxy/config/config.go (hunk 7 above)
Comment (danwinship) [reply pkg/proxy/config/config.go:310]: (confirmed that the version of this without the AddFunc fails the new unit test)

File: pkg/proxy/node.go (hunk 6 above)
Comment (aojea) [reply pkg/proxy/node.go:166]: actually, think the informers return a reference to the informer cache, so if you mutate the object you are screwed ... deepcopy has a lot of performance implications, so this is ok meanwhile the object does not change much

**Comment by danwinship** [comment]
doh, sorry, just gofmt

**Comment by pacoxu** [comment]
/test pull-kubernetes-unit
for a known flake(tracked in https://github.com/kubernetes/kubernetes/issues/132995)
