### PR TITLE
JobInterationTest: Retry polling even if the client fails to obtain Jobs at once

### LINKED ISSUE #126950: Flaky TestSuccessPolicy/job_with_successPolicy_with_succeededCount;_job_has_SuccessCriteriaMet_and_Complete_conditions_even_if_some_indexes_remain_pending
### Which jobs are flaking?

pull-kubernetes-integration

### Which tests are flaking?

TestSuccessPolicy/job_with_successPolicy_with_succeededCount;_job_has_SuccessCriteriaMet_and_Complete_conditions_even_if_some_indexes_remain_pending

### Since when has it been flaking?

2024-09-27

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration

### Reason for failure (if possible)

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/120586/pull-kubernetes-integration/1828447614387884032

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig apps

### PR DESCRIPTION
**Pull request by tenzen-y**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

The `validateJobsPodsStatusOnlyWithTimeout` function causes fatal errors when the client fails to obtain Job objects even once. However, there are some situations where the client fails due to rate limiter restrictions, not timeouts like this test case:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/120586/pull-kubernetes-integration/1828447614387884032
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1828481333362429952

```shell
job_test.go:3973: Failed to get updated Job: client rate limiter Wait returned an error: context deadline exceeded
I0827 15:47:15.178118  112969 job_controller.go:239] "Shutting down job controller"
```

So, this PR allows us to retry polling until a specified timeout.

#### Which issue(s) this PR fixes:

Fixes #126950

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/integration/job/job_test.go [hunk 1]
```diff
@@ -3970,7 +3970,8 @@ func validateJobsPodsStatusOnlyWithTimeout(ctx context.Context, t testing.TB, cl
 	if err := wait.PollUntilContextTimeout(ctx, waitInterval, timeout, true, func(ctx context.Context) (bool, error) {
 		updatedJob, err := clientSet.BatchV1().Jobs(jobObj.Namespace).Get(ctx, jobObj.Name, metav1.GetOptions{})
 		if err != nil {
-			t.Fatalf("Failed to get updated Job: %v", err)
+			t.Logf("Failed to get updated Job: %v", err)
```
Comment (googs1025) [inline test/integration/job/job_test.go:3973]: hey! I wonder if this part would have the same potential issues.
```go
func validateJobStatus(ctx context.Context, t testing.TB, clientSet clientset.Interface, jobObj *batchv1.Job, wantStatus batchv1.JobStatus) {
	t.Helper()
	diff := ""
	if err := wait.PollUntilContextTimeout(ctx, waitInterval, wait.ForeverTestTimeout, true, func(ctx context.Context) (bool, error) {
		gotJob, err := clientSet.BatchV1().Jobs(jobObj.Namespace).Get(ctx, jobObj.Name, metav1.GetOptions{})
		if err != nil {
			t.Fatalf("Failed to get updated Job: %v, last status diff (-want,+got):\n%s", err, diff)
		}
		diff = cmp.Diff(wantStatus, gotJob.Status,
			cmpopts.EquateEmpty(),
			cmpopts.IgnoreFields(batchv1.JobStatus{}, "StartTime", "UncountedTerminatedPods", "CompletionTime"),
			cmpopts.IgnoreFields(batchv1.JobCondition{}, "LastProbeTime", "LastTransitionTime", "Message"),
		)
		return diff == "", nil
	}); err != nil {
		t.Fatalf("Waiting for Job Status: %v\n, Status diff (-want,+got):\n%s", err, diff)
	}
}
```

Comment (tenzen-y) [reply test/integration/job/job_test.go:3973]: Yes, that is potentially the same problem. But, I have never seen the flake test. So, I would like to ask @alculquicondor @mimowo if we should apply the same approach to other places at Job integration tests so that we can resolve potential issues.

Comment (mimowo) [reply test/integration/job/job_test.go:3973]: Actually, there are even more functions which use `PollUntilContextTimeout` for Jobs:  `validateJobCondition`, `waitForPodsToBeActive`. We also use this pattern directly in `TestElasticIndexedJob`. I think the reason that `validateJobsPodsStatusOnlyWithTimeout` failed is just timing / order of tests plays out. 

IIUC any potential request (GET / PATCH / LIST ...) may result in the error, this suggests to me we should bump the QPS / Burst params. I can see these are set to some very high numbers in some tests, examples: https://github.com/kubernetes/kubernetes/blob/c86a2d6925a61ac181468b74f573518db1d645d2/test/integration/kubelet/watch_manager_test.go#L46-L47
https://github.com/kubernetes/kubernetes/blob/c86a2d6925a61ac181468b74f573518db1d645d2/test/integration/volume/attach_detach_test.go#L331-L332

Comment (mimowo) [reply test/integration/job/job_test.go:3973]: If we don't want to bump the QPS I would suggest to apply this approach to all functions using `PollUntilContextTimeout` sending requests to Jobs.

Comment (tenzen-y) [reply test/integration/job/job_test.go:3973]: TBH, I'm ok with either approach (QPS vs retry).
But, I guess that the QPS approach does not resolve the root cause.
Because this may happen again once the QPS in other testing for other SIGs are increased higher than Job integrations, right?

Comment (mimowo) [reply test/integration/job/job_test.go:3973]: IIUC we have client configuration scoped to the Job tests: https://github.com/kubernetes/kubernetes/blob/c86a2d6925a61ac181468b74f573518db1d645d2/test/integration/job/job_test.go#L4354-L4355.

Comment (tenzen-y) [reply test/integration/job/job_test.go:3973]: Yes, that's true.
I wanted to say the situations where we increase the client QPS to 1000001, and then if the kubelet testing increases QPS to 1000002. In that case, we may face the same problem. WDYT?

Comment (mimowo) [reply test/integration/job/job_test.go:3973]: The integration tests create separate clients and API servers per test, so I don't see how they could influence each other.

Comment (tenzen-y) [reply test/integration/job/job_test.go:3973]: Let's ask @alculquicondor 's opinion.

Comment (alculquicondor) [reply test/integration/job/job_test.go:3973]: We can probably do both.

But for this change, there are certain scenarios where it doesn't make sense to retry and just fail, like when the job doesn't exist. But maybe we don't need to over optimize, as we expect the test to succeed.

/lgtm
/approve

Comment (tenzen-y) [reply test/integration/job/job_test.go:3973]: > We can probably do both.

That makes sense. In that case, I will try to open a PR to increase QPS and Burst parameters. 

> But for this change, there are certain scenarios where it doesn't make sense to retry and just fail, like when the job doesn't exist. But maybe we don't need to over optimize, as we expect the test to succeed.

That is a good point; I think that we may want to raise errors when the polling fits NotFound error, but I believe that we can introduce the optimization after we observe any testing problems.
