### PR TITLE
Fix rolling update daemonset bug in clock-skew scenario

### LINKED ISSUE #77203: RollingUpdate daemonset got stucked
**What happened**:

RollingUpdate daemonset got stucked, leaves a few pod not updated. 

Daemonset's status are as follows:
```yaml
status:
  currentNumberScheduled: 2
  desiredNumberScheduled: 2
  numberAvailable: 1
  numberMisscheduled: 0
  numberReady: 2
  numberUnavailable: 1
  observedGeneration: 12
  updatedNumberScheduled: 2
```

```
NAME           DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
foo-daemonset   2         2         2         2            1           <none>          3d2h
```

**What you expected to happen**:

All pods managed by daemonset upgrade succeed.

**How to reproduce it (as minimally and precisely as possible)**:
1. config minReadySeconds for deamonset
2. daemon-controller's clock time is a little slower than node. 

**Anything else we need to know?**:
related issue #41641 and pr #42097

**Environment**:
the latest k8s version also has this bug

### PR DESCRIPTION
**Pull request by DaiHao**
**What type of PR is this?**
>
> /kind bug

**What this PR does / why we need it**:
>
> Pod's Ready condition is managed by kubelet, which is related to node clock. When controller's clock is slower than node, we will found that IsPodAvailable function judges pod unavailable. Then daemonset lose the change to update its status.
In this commit, controller resync the DaemonSet after MinReadySeconds as a last line of defense to guard against clock-skew.

Related issue #41641

**Which issue(s) this PR fixes**:

Fixes #77203

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
enhance the daemonset sync logic in clock-skew scenario
```

### CODE REVIEW

**Comment by DaiHao** [comment]
PTAL @resouer @kargakis

**Comment by answer1991** [comment]
it's a critical bug in our production environment.

@zhangxiaoyu-zidif  PTAL

File: pkg/controller/daemon/daemon_controller.go [hunk 1]
```diff
@@ -1198,6 +1198,10 @@ func (dsc *DaemonSetsController) updateDaemonSetStatus(ds *apps.DaemonSet, nodeL
 		return fmt.Errorf("error storing status for daemon set %#v: %v", ds, err)
 	}
 
+	// Resync the DaemonSet after MinReadySeconds as a last line of defense to guard against clock-skew.
+	if ds.Spec.MinReadySeconds > 0 && numberReady != numberAvailable {
+		dsc.enqueueDaemonSetAfter(ds, time.Duration(ds.Spec.MinReadySeconds)*time.Second)
```
Comment (kargakis) [inline pkg/controller/daemon/daemon_controller.go]: In replica sets, we ended up adding a second here because of an issue with time in golang. See:
https://github.com/kubernetes/kubernetes/blob/b3ad4cd6b99a413cc6da8ded20b535dd224007f5/pkg/controller/replicaset/replica_set.go#L351
https://github.com/kubernetes/kubernetes/issues/39785#issuecomment-279959133

Comment (kargakis) [reply pkg/controller/daemon/daemon_controller.go]: Interesting; this is already a thing, see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemon_controller.go#L561).

Comment (DaiHao) [reply pkg/controller/daemon/daemon_controller.go]: https://github.com/kubernetes/kubernetes/blob/b3ad4cd6b99a413cc6da8ded20b535dd224007f5/pkg/controller/replicaset/replica_set.go#L621-L626

Comment (DaiHao) [reply pkg/controller/daemon/daemon_controller.go]: > Interesting; this is already a thing, see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemon_controller.go#L561).

But when controller's clock time is slower than node, pod is still unavailable after minReadySeconds. For example:
pod A is ready at 12:00:00  and reenqueue at 12:00:31;
controller's time is 12:00:30 when reenqueue event happens, so controller judge A unavailable. 
So it's nessasary to add  the defense.

Comment (DaiHao) [reply pkg/controller/daemon/daemon_controller.go]: > https://github.com/kubernetes/kubernetes/blob/b3ad4cd6b99a413cc6da8ded20b535dd224007f5/pkg/controller/replicaset/replica_set.go#L621-L626

daemon controller should give another chance to resync the DaemonSet in case of clock-skew, just like replicaset controller.

Comment (kargakis) [reply pkg/controller/daemon/daemon_controller.go]: /lgtm
/ok-to-test

**Comment by kargakis** [comment]
@kubernetes/sig-apps-pr-reviews needs an approval

**Comment by zhangxiaoyu-zidif** [comment]
ping @janetkuo

File: pkg/controller/daemon/daemon_controller.go [hunk 2]
```diff
@@ -1198,6 +1198,10 @@ func (dsc *DaemonSetsController) updateDaemonSetStatus(ds *apps.DaemonSet, nodeL
 		return fmt.Errorf("error storing status for daemon set %#v: %v", ds, err)
 	}
 
+	// Resync the DaemonSet after MinReadySeconds as a last line of defense to guard against clock-skew.
```
Comment (krmayankk) [inline pkg/controller/daemon/daemon_controller.go]: it would help to enhance this comment with a more detailed explanation of this issue. I am still not following how the nodes (on which pod is running)clock skew from controller nodes clock causes this ?

Comment (krmayankk) [reply pkg/controller/daemon/daemon_controller.go]: Seems like the reason would be this line https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemon_controller.go#L1174 ,  the reason from what i understand is 
1: kubelet marks the pod ready and changes LastTransitionTime
2: controller checks IsPodAvailable() and finds the pod unavailable since its diffing LastTransitionTime(set by kubelet) with time.Now which is controller time. Since controller is behind in clock, minreadySeconds is not satisfied and it marks unavailable even though minReadySeconds is satisfied

can one of you confirm if this is the right understanding of this issue @DaiHao @kargakis  ?
Also in this case when a pod is marked unavailable, why wont it be requeued ?

I think including all of this explanation will be helpful

Comment (DaiHao) [reply pkg/controller/daemon/daemon_controller.go]: see here. https://github.com/kubernetes/kubernetes/pull/77208#discussion_r279599055

Comment (DaiHao) [reply pkg/controller/daemon/daemon_controller.go]: > Seems like the reason would be this line https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemon_controller.go#L1174 , the reason from what i understand is
> 1: kubelet marks the pod ready and changes LastTransitionTime
> 2: controller checks IsPodAvailable() and finds the pod unavailable since its diffing LastTransitionTime(set by kubelet) with time.Now which is controller time. Since controller is behind in clock, minreadySeconds is not satisfied and it marks unavailable even though minReadySeconds is satisfied
> 
> can one of you confirm if this is the right understanding of this issue @DaiHao @kargakis ?
> Also in this case when a pod is marked unavailable, why wont it be requeued ?
> 
> I think including all of this explanation will be helpful

Your understanding is right. 
Pod's status do not change in the sync loop, controller mark it unavailable only in daemonset's status, but which is equal with its last status, so daemonset also not requeue.
see here. https://github.com/kubernetes/kubernetes/blob/b219272a76bb4ad752417e310b5b50a6e8dc55c0/pkg/controller/daemon/daemon_controller.go#L1107-L1117

**Review by janetkuo — APPROVED** [review]
