### PR TITLE
kube-proxy should infer the service IP family from the ClusterIP field

### LINKED ISSUE #86773: DualStack: Fail to deploy dualstack cluster, kube-proxy panics
**What happened**:
I deployed a dualstack cluster with a config file.
First, kube-controller-manager CrashLoopBackOff, 
because it add a default option --node-cidr-mask-size=24,
I deleted it from /etc/kubernetes/manifests/kube-controller-manager.yaml,
I think in dualstack mode, kube-controller-manager should ignore the --node-cidr-mask-size.
Then, kube-proxy CrashLoopBackOff, 
[root@master ~]# kubectl logs -f kube-proxy-jpnl6 -n kube-system
I0102 09:57:44.553192       1 node.go:135] Successfully retrieved node IP: 172.18.130.251
I0102 09:57:44.553270       1 server_others.go:172] Using ipvs Proxier.
I0102 09:57:44.553287       1 server_others.go:174] creating dualStackProxier for ipvs.
W0102 09:57:44.555671       1 proxier.go:420] IPVS scheduler not specified, use rr by default
W0102 09:57:44.556213       1 proxier.go:420] IPVS scheduler not specified, use rr by default
W0102 09:57:44.556278       1 ipset.go:107] ipset name truncated; [KUBE-6-LOAD-BALANCER-SOURCE-CIDR] -> [KUBE-6-LOAD-BALANCER-SOURCE-CID]
W0102 09:57:44.556303       1 ipset.go:107] ipset name truncated; [KUBE-6-NODE-PORT-LOCAL-SCTP-HASH] -> [KUBE-6-NODE-PORT-LOCAL-SCTP-HAS]
I0102 09:57:44.556606       1 server.go:571] Version: v1.17.0
I0102 09:57:44.557622       1 config.go:313] Starting service config controller
I0102 09:57:44.557654       1 shared_informer.go:197] Waiting for caches to sync for service config
I0102 09:57:44.557717       1 config.go:131] Starting endpoints config controller
I0102 09:57:44.557753       1 shared_informer.go:197] Waiting for caches to sync for endpoints config
W0102 09:57:44.560310       1 meta_proxier.go:106] failed to add endpoints kube-system/kube-scheduler with error failed to identify ipfamily for endpoints (no subsets)
W0102 09:57:44.560337       1 meta_proxier.go:106] failed to add endpoints kube-system/kube-dns with error failed to identify ipfamily for endpoints (no subsets)
W0102 09:57:44.560428       1 meta_proxier.go:106] failed to add endpoints kube-system/kube-controller-manager with error failed to identify ipfamily for endpoints (no subsets)
E0102 09:57:44.560646       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 29 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1682120, 0x27f9a40)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1682120, 0x27f9a40)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/pkg/proxy/ipvs.(*metaProxier).OnServiceAdd(0xc0003ba330, 0xc0001c3200)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/ipvs/meta_proxier.go:65 +0x2b
k8s.io/kubernetes/pkg/proxy/config.(*ServiceConfig).handleAddService(0xc0003352c0, 0x1869ac0, 0xc0001c3200)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:333 +0x82
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:198
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0xf, 0xc00031a1c0, 0x0)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:658 +0x218
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc000594dd8, 0xc000557610, 0xf)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00046b740)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000594f40, 0xdf8475800, 0x0, 0xc000686601, 0xc00009a240)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc000478100)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0003be840, 0xc000428580)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14be59b]

goroutine 29 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1682120, 0x27f9a40)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
k8s.io/kubernetes/pkg/proxy/ipvs.(*metaProxier).OnServiceAdd(0xc0003ba330, 0xc0001c3200)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/ipvs/meta_proxier.go:65 +0x2b
k8s.io/kubernetes/pkg/proxy/config.(*ServiceConfig).handleAddService(0xc0003352c0, 0x1869ac0, 0xc0001c3200)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:333 +0x82
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/controller.go:198
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0xf, 0xc00031a1c0, 0x0)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:658 +0x218
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc000594dd8, 0xc000557610, 0xf)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00046b740)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000594f40, 0xdf8475800, 0x0, 0xc000686601, 0xc00009a240)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc000478100)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0003be840, 0xc000428580)
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
created by k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/workspace/anago-v1.17.0-rc.2.10+70132b0f130acc/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g: `cat /etc/os-release`):
CentOS Linux release 7.7.1908 (Core)
- Kernel (e.g. `uname -a`):
Linux master 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- kubeadm init config file:
[kubeadm-conf.txt](https://github.com/kubernetes/kubernetes/files/4015490/kubeadm-conf.txt)

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug
/kind cleanup

> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

when dual-stack kube-proxy infers the service IP family from
the ClusterIP because, quoting Dan Winship

" IPFamily's semantics are odd and inconsistent, and its
  behavior and range of values may change in future releases, and
  so everyone is strongly discouraged from trying to interpret
  it, and should instead simply look at the service's ClusterIP
  or endpoints."

Since kube-proxy skip headless and externalname services we
can safely obtain the IPFamily from the ClusterIP field

**Which issue(s) this PR fixes**:

Fixes #86773

**Special notes for your reviewer**:

Services without ClusterIP, ClusterIP=None or ExternalName Type are skipped by kube-proxy
https://github.com/kubernetes/kubernetes/pull/91357#discussion_r431058024

**Does this PR introduce a user-facing change?**:

```release-note
kube-proxy, in dual-stack mode, infers the service IP family from the ClusterIP instead of using the Service.Spec.IPFamily field
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/proxy/metaproxier/meta_proxier.go [hunk 1]
```diff
@@ -214,16 +245,16 @@ func endpointsIPFamily(endpoints *v1.Endpoints) (*v1.IPFamily, error) {
...
-	address := subset.Addresses[0]
-	if len(address.IP) == 0 {
+	ip := net.ParseIP(subset.Addresses[0].IP)
+	if ip == nil {
 		return nil, fmt.Errorf("failed to identify ipfamily for endpoints (address has no ip)")
 	}
 
 	ipv4 := v1.IPv4Protocol
 	ipv6 := v1.IPv6Protocol
-	if utilnet.IsIPv6String(address.IP) {
```
Comment (aojea) [inline pkg/proxy/metaproxier/meta_proxier.go:224]: The problem with this approach is that this does not handle the case with invalid IPs because we are assuming: "if is not IPv6 then it has to be IPv4". 
We had a similar bug with the legacy endpoint controller and headless services, where ClusterIP=None, 
don't know if this is possible with the endpoints Address.IP field, maybe it was already validated?

**Comment by aojea** [comment]
tested locally with KIND and dual-stack
```Ran 6 of 5098 Specs in 120.899 seconds
SUCCESS! -- 6 Passed | 0 Failed | 0 Pending | 5092 Skipped
PASS
aojea@elder:~/go/src/k8s.io/kubernetes$ bazel-bin/test/e2e/e2e.test -context kind-kind -ginkgo.focus="DualStack" -ginkgo.skip="internal node ip" -num-nod
es 2
```

the skip is because kubelet without a cloud controller only reports one IP address, this was already discussed with sig-testing and are asking to remove that test from the e2e, but that's not relevant for this PR

**Comment by aojea** [comment]
/retest
known flakes

File: pkg/proxy/metaproxier/meta_proxier.go (hunk 1 above)
Comment (danwinship) [reply pkg/proxy/metaproxier/meta_proxier.go:224]: endpoint IPs will always be actual IPs, not `"None"`

File: pkg/proxy/metaproxier/meta_proxier.go [hunk 2]
```diff
@@ -98,6 +112,23 @@ func (proxier *metaProxier) OnServiceSynced() {
 	proxier.ipv6Proxier.OnServiceSynced()
 }
 
+// serviceIPFamily that returns IPFamily of service or error if
+// failed to identify the IP family.
+func serviceIPFamily(service *v1.Service) (*v1.IPFamily, error) {
```
Comment (danwinship) [inline pkg/proxy/metaproxier/meta_proxier.go:117]: I guess this needs to look at `IPFamily` as well (to deal with headless services), and needs to fall back rather than erroring out if neither `ClusterIP` nor `IPFamily` is usable. Basically, this should be the same as `endpointutil.IsIPv6Service` in https://github.com/kubernetes/kubernetes/pull/91399/commits/ad313391 and maybe we should put that somewhere they can share it?

**Comment by danwinship** [comment]
So I forgot to bring this up in the mailing list thread, but there's another bug in the metaproxier, which is that you can change a Service's IPFamily by moving it from `ClusterIP` to `ExternalName` and back to `ClusterIP`, and the metaproxier doesn't cope with that. Basically it should treat a `ClusterIP`→`ExternalName` Update as being a Delete, and a `ExternalName`→`ClusterIP` Update as being an Add. (Right? Because the actual proxiers will just ignore `ExternalName` services anyway.)

File: pkg/proxy/metaproxier/meta_proxier.go (hunk 2 above)
Comment (aojea) [reply pkg/proxy/metaproxier/meta_proxier.go:117]: that brings me one question, does kube-proxy need to care about headless or externalName service types?
I mean, does kube-proxy does something for a service that does not have the clusterIP set?

Comment (danwinship) [reply pkg/proxy/metaproxier/meta_proxier.go:117]: oh, duh, I was thinking "headless services still have endpoints so it needs to care", but that's wrong. I think you're right. You'll need to look through the code to confirm that

**Comment by aojea** [comment]
/hold

https://github.com/kubernetes/kubernetes/pull/91357#discussion_r430069812

Let me check better all possible combinations, implications, types of services, ...

**Comment by danwinship** [comment]
/retitle kube-proxy should infer the service IP family from the ClusterIP field

File: pkg/proxy/metaproxier/meta_proxier.go (hunk 2 above)
Comment (aojea) [reply pkg/proxy/metaproxier/meta_proxier.go:117]: heh, interesting exercise. check the stack trace :)

OnServiceAdd() -> OnServiceUpdate() -> proxier.serviceChanges.Update()

https://github.com/kubernetes/kubernetes/blob/323f34858de18b862d43c40b2cced65ad8e24052/pkg/proxy/iptables/proxier.go#L536-L548

proxier.serviceChanges.Update() -> serviceToServiceMap()

https://github.com/kubernetes/kubernetes/blob/323f34858de18b862d43c40b2cced65ad8e24052/pkg/proxy/service.go#L241-L262

serviceToServiceMap() -> utilproxy.ShouldSkipService()
	https://github.com/kubernetes/kubernetes/blob/323f34858de18b862d43c40b2cced65ad8e24052/pkg/proxy/service.go#L306-L313
	
utilproxy.ShouldSkipService() -> IsServiceIPSet()
	https://github.com/kubernetes/kubernetes/blob/323f34858de18b862d43c40b2cced65ad8e24052/pkg/proxy/util/utils.go#L148-L161

and  IsServiceIPSet()	
	https://github.com/kubernetes/kubernetes/blob/6a5f0e6eda5d4d736adaa2b3dd08c4366153bacf/pkg/apis/core/helper/helpers.go#L267-L271

File: pkg/proxy/metaproxier/meta_proxier.go [hunk 3]
```diff
@@ -62,33 +64,47 @@ func (proxier *metaProxier) SyncLoop() {
 
 // OnServiceAdd is called whenever creation of new service object is observed.
 func (proxier *metaProxier) OnServiceAdd(service *v1.Service) {
-	if *(service.Spec.IPFamily) == v1.IPv4Protocol {
-		proxier.ipv4Proxier.OnServiceAdd(service)
+	// if ClusterIP is "None" or empty, or ExternalName service skip proxying
+	svcName := types.NamespacedName{Namespace: service.Namespace, Name: service.Name}
+	if utilproxy.ShouldSkipService(svcName, service) {
```
Comment (danwinship) [inline pkg/proxy/metaproxier/meta_proxier.go:69]: Not sure the comment is needed... `ShouldSkipService` makes it pretty clear what's going on here

**Review by danwinship — COMMENTED** [review]
I had said before that we should deal with the case of a service changing to/from ExternalName as well, but it looks like we don't totally deal with that correctly even in the single-proxier case, and it ought to be done in `pkg/proxy/service.go` or `pkg/proxy/config/config.go`... So I think this is right

File: pkg/proxy/metaproxier/meta_proxier.go (hunk 3 above)
Comment (aojea) [reply pkg/proxy/metaproxier/meta_proxier.go:68]: removed

**Comment by aojea** [comment]
/retest
known issues

**Comment by aojea** [comment]
/retest
/hold cancel
tested locally with KIND and works

**Comment by aojea** [comment]
/close 

there is a new plan 😄 

https://github.com/kubernetes/enhancements/pull/1679

**Comment by danwinship** [comment]
> there is a new plan

but it doesn't change the need for this PR... in fact, the new plan involves killing off the `ipFamily` field (and replacing it with `ipFamilies`, but it will still be the case that kube-proxy ought to only be looking at `clusterIPs`, not `ipFamilies`)

**Comment by aojea** [comment]
> > there is a new plan
> 
> but it doesn't change the need for this PR... in fact, the new plan involves killing off the `ipFamily` field (and replacing it with `ipFamilies`, but it will still be the case that kube-proxy ought to only be looking at `clusterIPs`, not `ipFamilies`)

right, but I think is better waiting until the `clusterIPs` field is available

**Comment by danwinship** [comment]
/reopen
the plan from kubernetes/enhancements#1679 is not be implemented until 1.20, and this fixes a sometimes panic in 1.19

File: pkg/proxy/metaproxier/meta_proxier.go [hunk 4]
```diff
@@ -62,33 +64,44 @@ func (proxier *metaProxier) SyncLoop() {
 
 // OnServiceAdd is called whenever creation of new service object is observed.
 func (proxier *metaProxier) OnServiceAdd(service *v1.Service) {
-	if *(service.Spec.IPFamily) == v1.IPv4Protocol {
-		proxier.ipv4Proxier.OnServiceAdd(service)
+	svcName := types.NamespacedName{Namespace: service.Namespace, Name: service.Name}
+	if utilproxy.ShouldSkipService(svcName, service) {
```
Comment (danwinship) [inline pkg/proxy/metaproxier/meta_proxier.go:68]: Just make `ShouldSkipService` not take the `svcName` arg; it can just use `service.Namespace` and `service.Name` if it needs to log a message (which it normally doesn't). (And none of the other existing callers have a `NamespaceName` object in advance either.) (Also, userspace/proxier.go is redundantly re-logging the same message that `ShouldSkipService` logs, which you should fix too.) (So, one commit to fix the existing `ShouldSkipService` usage, then a second commit to use it in the metaproxier.)

Comment (aojea) [reply pkg/proxy/metaproxier/meta_proxier.go]: done

**Comment by anguslees** [comment]
Is this likely to be backported?

Currently, my k8s 1.18.4 kube-proxy immediately explodes with a null pointer deref, because the code before this PR tried to do `*(service.Spec.IPFamily)`

**Comment by aojea** [comment]
> Is this likely to be backported?
> 
> Currently, my k8s 1.18.4 kube-proxy (with ipvs and dualstack featureflag) immediately explodes with a null pointer deref, because the code before this PR tried to do `*(service.Spec.IPFamily)`

We have many discussion about this topic in the past, my take away is that for alpha features is preferred to not do backports, however, if we find a good reason I think it will be accepted. However, with the new dual-stack API changes and moving from `IPFamily` to `IPfamilies`, do you think is worth the effort?

**Comment by anguslees** [comment]
> for alpha features is preferred to not do backports

:+1: I agree with this principle.
