### PR TITLE
locking fix in vSphere cleanup function

### LINKED ISSUE #68336: `defer` in infinite loop
/kind bug
/sig release

`defer` call will never be execute.
https://github.com/kubernetes/kubernetes/blob/8e329f1c3cbb1354c27b6135990c5544f14d2a17/pkg/cloudprovider/providers/vsphere/vsphere_util.go#L301

### PR DESCRIPTION
**Pull request by wgliang**
**What this PR does / why we need it**:
fix bug that defer in infinite loop

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #68336

**Special notes for your reviewer**:

**Release note**:

```release-note
locking fix in vSphere cleanup function

The vSphere cloud provider has a cleanup function with a loop,
inside of which a write lock was intended to prevent races against
VM creation, but the usage of the sync.RWMutex type is incorrect,
plus is placed in a defer call so the locking is effectively
nonexistent.  This patch adds an anonymous function call inside
the loop to correctly handle acquiring the write lock with deferred
unlock to run at that function's completion, following the normal
golang lock/deferred-unlock pattern.
```

### CODE REVIEW

**Review by divyenpatel — APPROVED** [review]
/lgtm

**Review by tao12345666333 — APPROVED** [review]

**Comment by divyenpatel** [comment]
@wgliang we should get this merged on master earliest as this is the bug and cherry pick the change to prior releases.

**Comment by divyenpatel** [comment]
@liggitt Can you help with adding required labels to this PR to allow merging?

**Comment by wgliang** [comment]
@divyenpatel 
Ok, I'll cherry pick the change to prior releases.

File: pkg/cloudprovider/providers/vsphere/vsphere_util.go [hunk 1]
```diff
@@ -298,8 +297,9 @@ func (vs *VSphere) cleanUpDummyVMs(dummyVMPrefix string) {
 			continue
 		}
 		// A write lock is acquired to make sure the cleanUp routine doesn't delete any VM's created by ongoing PVC requests.
-		defer cleanUpDummyVMLock.Lock()
+		cleanUpDummyVMLock.Lock()
 		err = diskmanagers.CleanUpDummyVMs(ctx, vmFolder, dc)
+		cleanUpDummyVMLock.Unlock()
```
Comment (liggitt) [inline pkg/cloudprovider/providers/vsphere/vsphere_util.go]: If CleanUpDummyVMs panics, this will never unlock. Is there a reason not to `defer cleanUpDummyVMLock.Unlock()` immediately after locking?

Comment (wgliang) [reply pkg/cloudprovider/providers/vsphere/vsphere_util.go]: The cleanUpDummyVMLock.Lock() is in a loop and not return, so we can not use defer.

Comment (liggitt) [reply pkg/cloudprovider/providers/vsphere/vsphere_util.go]: A typical pattern is to make an inner function and call it immediately, so that defer can be used

**Comment by wgliang** [comment]
/ping @liggitt 
for approve of v.1,12

**Comment by liggitt** [comment]
the fix looks fine, but given this bug has existed since at least 1.8, I don't think it's of critical importance to add to the 1.12 milestone, which is limited to release blocker fixes.

**Comment by divyenpatel** [comment]
@liggitt 

This is critical bug fix for volume provisioning using SPBM Policy. If volumes are being created, while this clean up routine is deleting shadow/dummy VMs, Provisioning could fail. 

We should fix this locking in prior releases as well. May be due to very less adoption of SPBM based volume provisioning, this issue was never reported earlier.

**Comment by hogepodge** [comment]
/lgtm

Any issue that puts the system into an infinite loop, even if it is infrequently exercised, should be fixed in a release if possible. Support merging for the 1.12 release.

**Comment by tpepper** [comment]
I'm ok with this for 1.12.0 or 1.12.1, but defer to the SIG.

**Comment by dims** [comment]
looks like @hogepodge supported v1.12. adding labels

/priority critical-urgent 

(also this has no impact on anything other than vsphere)

**Comment by andrewsykim** [comment]
cc @frapposelli

**Comment by tpepper** [comment]
@kubernetes/cloud-provider-vsphere-maintainers please aspire to to higher quality commit messages during PR review.  This one gives almost zero indication of what's happening, without referring separately to info in https://github.com/kubernetes/kubernetes/issues/68336 and that connection only shows in the merge commit in the git history.

I would've found it much easier to follow if this was something like:

```
locking fix in vSphere cleanup function

The vSphere cloud provider has a cleanup function with a loop,
inside of which a write lock was intended to prevent races against
VM creation, but the usage of the sync.RWMutex type is incorrect,
plus is placed in a defer call so the locking is effectively
nonexistent.  This patch adds an anonymous function call inside
the loop to correctly handle acquiring the write lock with deferred
unlock to run at that function's completion, following the normal
golang lock/deferred-unlock pattern.

This incorrect locking resulted in XYZ impact observed when ABC conditions
are met.
```

**Comment by wgliang** [comment]
@tpepper 
Very accurate and detailed description. Thank you for your supplement.
