### PR TITLE
Use Patch instead of SSA for Pod Disruption condition

### LINKED ISSUE #118261: Pod Garbage collector fails to clean up  PODs from nodes that are not running anymore
### What happened?

This happened after upgrading to Kubernetes 1.26 from 1.24

The succession of events we have observed:
- Our workloads use HorizontalPodAutoscaler to scale up due to traffic increase
- Cluster Autoscaler provisions new nodes to accommodate the new replicas
- Traffic goes down
- HPA downsize replicas
- Cluster Autoscaler notices nodes under the threshold of usage and PODs can be accommodated into other nodes
- Nodes are drained and downscaled
- Kubernetes still reports PODs in a "Running" or "Terminating" state in the node that no longer exists
- Kubernetes control plane reports "Orphan pods" on its audit logs

### What did you expect to happen?

Kubernetes Garbage collector to clean up these PODs after the node is gone

### How can we reproduce it (as minimally and precisely as possible)?

Deploy the following yaml deployments into a K8s cluster 1.26 and terminate one of the nodes

(duplicated port key "containerPort + protocol")
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/component: deployment
spec:
  replicas: 100
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: nginx
      app.kubernetes.io/component: deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: nginx
        app.kubernetes.io/component: deployment
    spec:
      restartPolicy: Always
      containers:
        - name: nginx
          image: "nginx:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8080
              name: metrics
              protocol: TCP
```

(Duplicated environment variable. Set twice by mistake)
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-2
  labels:
    app.kubernetes.io/name: nginx-2
    app.kubernetes.io/instance: nginx-2
    app.kubernetes.io/component: deployment
spec:
  replicas: 100
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-2
      app.kubernetes.io/instance: nginx-2
      app.kubernetes.io/component: deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-2
        app.kubernetes.io/instance: nginx-2
        app.kubernetes.io/component: deployment
    spec:
      restartPolicy: Always
      containers:
        - name: nginx-2
          image: "nginx:latest"
          imagePullPolicy: IfNotPresent
          env:
            - name: MY_VAR
              value: value-1
            - name: MY_VAR
              value: value-2
```

### Anything else we need to know?

(Duplicated port error)
```json
{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1",
  "level": "RequestResponse",
  "auditID": "9d3c7dbf-f599-422b-866c-84d52f3b1a22",
  "stage": "ResponseComplete",
  "requestURI": "/api/v1/namespaces/app-b/pods/app-b-5894548cb-7tssd/status?fieldManager=PodGC\u0026force=true",
  "verb": "patch",
  "user":
    {
      "username": "system:serviceaccount:kube-system:pod-garbage-collector",
      "uid": "f099fed7-6a3d-4a3b-bc1b-49c668276d76",
      "groups":
        [
          "system:serviceaccounts",
          "system:serviceaccounts:kube-system",
          "system:authenticated",
        ],
    },
  "sourceIPs": ["172.16.38.214"],
  "userAgent": "kube-controller-manager/v1.26.4 (linux/amd64) kubernetes/4a34796/system:serviceaccount:kube-system:pod-garbage-collector",
  "objectRef":
    {
      "resource": "pods",
      "namespace": "app-b",
      "name": "app-b-5894548cb-7tssd",
      "apiVersion": "v1",
      "subresource": "status",
    },
  "responseStatus":
    {
      "metadata": {},
      "status": "Failure",
      "message": 'failed to create manager for existing fields: failed to convert new object (app-b/app-b-5894548cb-7tssd; /v1, Kind=Pod) to smd typed: .spec.containers[name="app-b"].ports: duplicate entries for key [containerPort=8082,protocol="TCP"]',
      "code": 500,
    },
  "requestObject":
    {
      "kind": "Pod",
      "apiVersion": "v1",
      "metadata":
        {
          "name": "app-b-5894548cb-7tssd",
          "namespace": "app-b",
        },
      "status":
        {
          "phase": "Failed",
          "conditions":
            [
              {
                "type": "DisruptionTarget",
                "status": "True",
                "lastTransitionTime": "2023-05-23T17:00:55Z",
                "reason": "DeletionByPodGC",
                "message": "PodGC: node no longer exists",
              },
            ],
        },
    },
  "responseObject":
    {
      "kind": "Status",
      "apiVersion": "v1",
      "metadata": {},
      "status": "Failure",
      "message": 'failed to create manager for existing fields: failed to convert new object (app-b/app-b-5894548cb-7tssd; /v1, Kind=Pod) to smd typed: .spec.containers[name="app-b"].ports: duplicate entries for key [containerPort=8082,protocol="TCP"]',
      "code": 500,
    },
  "requestReceivedTimestamp": "2023-05-23T17:00:55.648887Z",
  "stageTimestamp": "2023-05-23T17:00:55.652513Z",
  "annotations":
    {
      "authorization.k8s.io/decision": "allow",
      "authorization.k8s.io/reason": 'RBAC: allowed by ClusterRoleBinding "system:controller:pod-garbage-collector" of ClusterRole "system:controller:pod-garbage-collector" to ServiceAccount "pod-garbage-collector/kube-system"',
    },
}
```

(Duplicated env var error)
```json
{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1",
  "level": "RequestResponse",
  "auditID": "9ffc9212-3d74-4b86-98bb-5e6f0c5395b1",
  "stage": "ResponseComplete",
  "requestURI": "/api/v1/namespaces/app-a/pods/app-a-7b7ddc5874-c85hq/status?fieldManager=PodGC\u0026force=true",
  "verb": "patch",
  "user":
    {
      "username": "system:serviceaccount:kube-system:pod-garbage-collector",
      "uid": "f099fed7-6a3d-4a3b-bc1b-49c668276d76",
      "groups":
        [
          "system:serviceaccounts",
          "system:serviceaccounts:kube-system",
          "system:authenticated",
        ],
    },
  "sourceIPs": ["172.16.38.214"],
  "userAgent": "kube-controller-manager/v1.26.4 (linux/amd64) kubernetes/4a34796/system:serviceaccount:kube-system:pod-garbage-collector",
  "objectRef":
    {
      "resource": "pods",
      "namespace": "app-a",
      "name": "app-a-7b7ddc5874-c85hq",
      "apiVersion": "v1",
      "subresource": "status",
    },
  "responseStatus":
    {
      "metadata": {},
      "status": "Failure",
      "message": "failed to create manager for existing fields: failed to convert new object (app-a/app-a-7b7ddc5874-c85hq; /v1, Kind=Pod) to smd typed: errors:\n .spec.containers[name=\"app-a\"].env: duplicate entries for key [name=\"RABBITMQ_HOST\"]\n .spec.containers[name=\"app-a\"].env: duplicate entries for key [name=\"RABBITMQ_PORT\"]\n .spec.initContainers[name=\"db-migration\"].env: duplicate entries for key [name=\"RABBITMQ_HOST\"]\n .spec.initContainers[name=\"db-migration\"].env: duplicate entries for key [name=\"RABBITMQ_PORT\"]",
      "code": 500,
    },
  "requestObject":
    {
      "kind": "Pod",
      "apiVersion": "v1",
      "metadata":
        {
          "name": "app-a-7b7ddc5874-c85hq",
          "namespace": "app-a",
        },
      "status":
        {
          "phase": "Failed",
          "conditions":
            [
              {
                "type": "DisruptionTarget",
                "status": "True",
                "lastTransitionTime": "2023-05-23T17:00:55Z",
                "reason": "DeletionByPodGC",
                "message": "PodGC: node no longer exists",
              },
            ],
        },
    },
  "responseObject":
    {
      "kind": "Status",
      "apiVersion": "v1",
      "metadata": {},
      "status": "Failure",
      "message": "failed to create manager for existing fields: failed to convert new object (app-a/app-a-7b7ddc5874-c85hq; /v1, Kind=Pod) to smd typed: errors:\n .spec.containers[name=\"app-a\"].env: duplicate entries for key [name=\"RABBITMQ_HOST\"]\n .spec.containers[name=\"app-a\"].env: duplicate entries for key [name=\"RABBITMQ_PORT\"]\n .spec.initContainers[name=\"db-migration\"].env: duplicate entries for key [name=\"RABBITMQ_HOST\"]\n .spec.initContainers[name=\"db-migration\"].env: duplicate entries for key [name=\"RABBITMQ_PORT\"]",
      "code": 500,
    },
  "requestReceivedTimestamp": "2023-05-23T17:00:55.632119Z",
  "stageTimestamp": "2023-05-23T17:00:55.637338Z",
  "annotations":
    {
      "authorization.k8s.io/decision": "allow",
      "authorization.k8s.io/reason": 'RBAC: allowed by ClusterRoleBinding "system:controller:pod-garbage-collector" of ClusterRole "system:controller:pod-garbage-collector" to ServiceAccount "pod-garbage-collector/kube-system"',
    },
}
```

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.1", GitCommit:"e4d4e1ab7cf1bf15273ef97303551b279f0920a9", GitTreeState:"clean", BuildDate:"2022-09-14T19:49:27Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.4-eks-0a21954", GitCommit:"4a3479673cb6d9b63f1c69a67b57de30a4d9b781", GitTreeState:"clean", BuildDate:"2023-04-15T00:33:09Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

$ uname -a
Linux ip-x-x-x-x.region.compute.internal 5.15.108 #1 SMP Tue May 9 23:54:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
Cluster Autoscaler
</details>

### Container runtime (CRI) and version (if applicable)

<details>
ContainerD
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI: Cilium 1.11
CSI: AWS EBS CSI
</details>

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug
/kind regression

#### Which issue(s) this PR fixes:

Fixes #118261

#### Does this PR introduce a user-facing change?

```release-note
Fixed a regression in default configurations, which enabled PodDisruptionConditions by default, 
that prevented the control plane's pod garbage collector from deleting pods that contained duplicated field keys (env. variables with repeated keys or container ports).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/3329-retriable-and-non-retriable-failures
```

### CODE REVIEW

**Comment by mimowo** [comment]
For the record, failing integration test after https://github.com/kubernetes/kubernetes/pull/121103/commits/8e34a952ee6603b3eb0da8be2acf89fd6602fc67:
 https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121103/pull-kubernetes-integration/1711694973037973504.

**Comment by liggitt** [comment]
/kind regression

Thanks for the PR. Please include "Fixes a regression in default configurations in $version-that-enabled-disruption-condition-by-default ..."

**Comment by mimowo** [comment]
> Thanks for the PR. Please include "Fixes a regression in default configurations in $version-that-enabled-disruption-condition-by-default ..."

Sure, added to the release note.

**Comment by sfotony** [comment]
I believe we can for all providers except for EKS (but I'd have to check).

File: pkg/controller/podgc/gc_controller.go [hunk 1]
```diff
@@ -249,12 +249,12 @@ func (gcc *PodGCController) gcOrphaned(ctx context.Context, pods []*v1.Pod, node
...
-			WithStatus(v1.ConditionTrue).
-			WithReason("DeletionByPodGC").
-			WithMessage("PodGC: node no longer exists").
-			WithLastTransitionTime(metav1.Now())
+		condition := &v1.PodCondition{
+			Type:    v1.DisruptionTarget,
+			Status:  v1.ConditionTrue,
+			Reason:  "DeletionByPodGC",
+			Message: "PodGC: node no longer exists",
+		}
```
Comment (atiratree) [inline pkg/controller/podgc/gc_controller.go:257]: is this going to be changed back to SSA in the future? 

Are the other places that use SSA affected as well?

https://github.com/kubernetes/kubernetes/blob/0851995a61cb83645734183cb49250e0fc3b14a4/pkg/controller/disruption/disruption.go#L776

https://github.com/kubernetes/kubernetes/blob/0851995a61cb83645734183cb49250e0fc3b14a4/pkg/scheduler/framework/preemption/preemption.go#L366

File: pkg/controller/podgc/gc_controller_test.go [hunk 2]
```diff
@@ -749,12 +747,12 @@ func TestGCInspectingPatchedPodBeforeDeletion(t *testing.T) {
 
 			actions := client.Actions()
 
-			var patchAction clienttesting.PatchAction
+			var patchAction clienttesting.UpdateAction
```
Comment (atiratree) [inline pkg/controller/podgc/gc_controller_test.go:750]:
```suggestion
			var updateAction clienttesting.UpdateAction
```

File: pkg/controller/podgc/gc_controller_test.go [hunk 3]
```diff
@@ -856,9 +840,10 @@ func getDeletedPodNames(client *fake.Clientset) sets.String {
 func getPatchedPodNames(client *fake.Clientset) sets.String {
 	patchedPodNames := sets.NewString()
 	for _, action := range client.Actions() {
-		if action.GetVerb() == "patch" && action.GetResource().Resource == "pods" {
-			patchAction := action.(clienttesting.PatchAction)
-			patchedPodNames.Insert(patchAction.GetName())
+		if action.GetVerb() == "update" && action.GetResource().Resource == "pods" {
+			patchAction := action.(clienttesting.UpdateAction)
```
Comment (atiratree) [inline pkg/controller/podgc/gc_controller_test.go:844]:
```suggestion
			updateAction := action.(clienttesting.UpdateAction)
```

File: pkg/controller/podgc/gc_controller_test.go (hunk 2 above)
Comment (atiratree) [reply pkg/controller/podgc/gc_controller_test.go:750]: nit: not sure if we want to update the name of the test as well..

File: test/integration/podgc/podgc_test.go [hunk 4]
```diff
@@ -309,6 +309,146 @@ func TestTerminatingOnOutOfServiceNode(t *testing.T) {
...
+				t.Fatalf("Error '%v' while waiting for the pod '%v' to be terminating", err, klog.KObj(pod))
+			}
+			pod, err = cs.CoreV1().Pods(testCtx.NS.Name).Get(testCtx.Ctx, pod.Name, metav1.GetOptions{})
+			if err != nil {
+				t.Fatalf("Error: '%v' while updating pod info: '%v'", err, klog.KObj(pod))
+			}
+			_, gotDisruptionTarget := podutil.GetPodCondition(&pod.Status, v1.DisruptionTarget)
+			if diff := cmp.Diff(test.wantDisruptionTarget, gotDisruptionTarget, cmpopts.IgnoreFields(v1.PodCondition{}, "LastTransitionTime")); diff != "" {
+				t.Errorf("Pod %v has unexpected DisruptionTarget condition: %s", klog.KObj(pod), diff)
+			}
```
Comment (atiratree) [inline test/integration/podgc/podgc_test.go:444]: IMO we should check for a presence of `LastTransitionTime` so we do not omit it when we change back to SSA

File: test/integration/podgc/podgc_test.go [hunk 5]
```diff
@@ -309,6 +309,146 @@ func TestTerminatingOnOutOfServiceNode(t *testing.T) {
...
+			if err != nil {
+				t.Fatalf("Error %v, while creating pod: %v", err, klog.KObj(pod))
+			}
+			defer testutils.RemovePodFinalizers(testCtx.Ctx, testCtx.ClientSet, t, *pod)
+
+			pod.Status.Phase = test.phase
+			if _, err := testCtx.ClientSet.CoreV1().Pods(testCtx.NS.Name).UpdateStatus(testCtx.Ctx, pod, metav1.UpdateOptions{}); err != nil {
+				t.Fatalf("Error %v, while setting phase %v for pod: %v", err, test.phase, klog.KObj(pod))
+			}
+
```
Comment (atiratree) [inline test/integration/podgc/podgc_test.go:432]: can we comment on a reason here? For example `// getting evicted due to NodeName being "non-existing-node"`

File: pkg/controller/podgc/gc_controller.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/podgc/gc_controller.go:257]: There is also this place: https://github.com/kubernetes/kubernetes/blob/0851995a61cb83645734183cb49250e0fc3b14a4/pkg/controller/nodelifecycle/scheduler/taint_manager.go#L132.

I'm thinking about minimal fix for the issue reported by users. Certainly, in this PR it is going to be only PodGC. We may extend the scope based on user feedback or reviewers in follow up PRs. My hope is that after SSA is fixed we can revert this change. FYI @alculquicondor @liggitt for suggestion if this is the right approach.

File: pkg/controller/podgc/gc_controller_test.go (hunk 2 above)
Comment (mimowo) [reply pkg/controller/podgc/gc_controller_test.go:750]: I would say that its ok in the test. I think one could say update is a way to patch the pod here :)

File: pkg/controller/podgc/gc_controller_test.go (hunk 3 above)
Comment (mimowo) [reply pkg/controller/podgc/gc_controller_test.go]: Done

File: test/integration/podgc/podgc_test.go (hunk 5 above)
Comment (mimowo) [reply test/integration/podgc/podgc_test.go]: Actually, we don't need to do it in this test. Removed it, along with the phase and wantPhase options.

File: test/integration/podgc/podgc_test.go (hunk 4 above)
Comment (mimowo) [reply test/integration/podgc/podgc_test.go:430]: Done

File: pkg/controller/podgc/gc_controller_test.go (hunk 2 above)
Comment (mimowo) [reply pkg/controller/podgc/gc_controller_test.go]: I'm inclined to leave patchedPodNames also, because this would affect many tests, and I think it is better to keep the fix concise as it is intended for cherry-picking.

**Comment by mimowo** [comment]
@atiratree thank you for reviewing!

**Comment by dims** [comment]
issue is marked `priority/critical-urgent` and a `kind/regression`

/priority critical-urgent

File: test/integration/podgc/podgc_test.go (hunk 5 above)
Comment (mimowo) [reply test/integration/podgc/podgc_test.go]: Makes sense, added the comment, and as I was adding it I realized the whole section to create the node is not necessary :)

Comment (atiratree) [reply test/integration/podgc/podgc_test.go]: thanks for the update :)

**Comment by mimowo** [comment]
I'm thinking about switching this to use patch instead of update in this PR. StrategicMergePatch is used by kubelet to add conditions, and it seems to work ok. It will also mean smaller payloads. WDYT @atiratree @liggitt @apelisse @alculquicondor ?

**Comment by mimowo** [comment]
For the update to work I had to also add the update role. It's not relevant change if we go with patch, but might be good to do anyway.

**Comment by liggitt** [comment]
> I'm thinking about switching this to use patch instead of update in this PR. StrategicMergePatch is used by kubelet to add conditions, and it seems to work ok. It will also mean smaller payloads. WDYT @atiratree @liggitt @apelisse @alculquicondor ?

that makes sense to me

**Comment by mimowo** [comment]
> that makes sense to me

Thank you for the feedback. I have already switched to patch in the PR.

File: pkg/controller/podgc/gc_controller_test.go [hunk 6]
```diff
@@ -714,16 +714,16 @@ func TestGCInspectingPatchedPodBeforeDeletion(t *testing.T) {
 				Status: v1.PodStatus{
 					Phase: v1.PodFailed,
 					Conditions: []v1.PodCondition{
+						{
```
Comment (liggitt) [inline pkg/controller/podgc/gc_controller_test.go:717]: curious why this was required

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go [hunk 7]
```diff
@@ -311,7 +311,7 @@ func buildControllerRoles() ([]rbacv1.ClusterRole, []rbacv1.ClusterRoleBinding)
 			},
 		}
 		if utilfeature.DefaultFeatureGate.Enabled(features.PodDisruptionConditions) {
-			role.Rules = append(role.Rules, rbacv1helpers.NewRule("patch").Groups(legacyGroup).Resources("pods/status").RuleOrDie())
+			role.Rules = append(role.Rules, rbacv1helpers.NewRule("patch", "update").Groups(legacyGroup).Resources("pods/status").RuleOrDie())
```
Comment (liggitt) [inline plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go:314]: drop this if we stick with patch

**Review by liggitt — COMMENTED** [review]
using the same mechanism kubelet uses to update pod status conditions makes sense to me

File: pkg/controller/podgc/gc_controller_test.go (hunk 6 above)
Comment (liggitt) [reply pkg/controller/podgc/gc_controller_test.go:717]: (make sure this ordering change isn't flaky / non-deterministic)

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go (hunk 7 above)
Comment (mimowo) [reply plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go]: Done

File: pkg/controller/podgc/gc_controller_test.go (hunk 6 above)
Comment (dims) [reply pkg/controller/podgc/gc_controller_test.go:717]: nice marking as resolved!

File: pkg/controller/podgc/gc_controller.go (hunk 1 above)
Comment (liggitt) [reply pkg/controller/podgc/gc_controller.go:255]: all of the places that apply this condition using SSA and currently short-circuit their deletion if it fails have to be fixed and backported, or we have to disable the PodDisruptionConditions feature gate to restore them functioning properly

Comment (liggitt) [reply pkg/controller/podgc/gc_controller.go:255]: > Certainly, in this PR it is going to be only PodGC. We may extend the scope based on user feedback or reviewers in follow up PRs

I don't see the benefit of splitting the regression fix across multiple PRs. I think we should switch from SSA to SMP using the method in this PR in all places.

**Comment by liggitt** [comment]
hoisting https://github.com/kubernetes/kubernetes/pull/121103#discussion_r1362632637 since github is helpfully hiding that thread:

> all of the places that apply this condition using SSA and currently short-circuit their deletion if it fails have to be fixed and backported, or we have to disable the PodDisruptionConditions feature gate to restore them functioning properly
>
>> Certainly, in this PR it is going to be only PodGC. We may extend the scope based on user feedback or reviewers in follow up PRs
>
> I don't see the benefit of splitting the regression fix across multiple PRs. I think we should switch from SSA to SMP using the method in this PR in all places.

File: pkg/controller/podgc/gc_controller.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/controller/podgc/gc_controller.go:255]: Right, any delete operation is affected. Initially I was thinking that only deletions with gracePeriod=0 were affected, but that's not true.

I agree that we should fix in one PR.

**Comment by alculquicondor** [comment]
/hold
for fixing all usages of SSA for the disruption target condition

**Review by alculquicondor — COMMENTED** [review]
FWIIW: Existing code LGTM

**Comment by kmala** [comment]
Thanks for the fix. I was able to test and make sure that the changes help with the bug and the GC is able to clean up the pods.

**Comment by dims** [comment]
@alculquicondor @liggitt i only see one use of `PodConditionApplyConfiguration` that's already in this PR:
https://cs.k8s.io/?q=PodConditionApplyConfiguration&i=nope&files=&excludeFiles=_test%5C.go&repos=kubernetes/kubernetes

**Comment by liggitt** [comment]
@dims I think these are the other places:

https://github.com/kubernetes/kubernetes/blob/6d70013af571e389d19fb390eb7cb89dca41ae81/pkg/controller/disruption/disruption.go#L773-L782

https://github.com/kubernetes/kubernetes/blob/6d70013af571e389d19fb390eb7cb89dca41ae81/pkg/controller/nodelifecycle/scheduler/taint_manager.go#L131-L138

https://github.com/kubernetes/kubernetes/blob/6d70013af571e389d19fb390eb7cb89dca41ae81/pkg/scheduler/framework/preemption/preemption.go#L366-L374

**Comment by dims** [comment]
gotcha now i now what to look for! [grep.txt](https://github.com/kubernetes/kubernetes/files/12974099/grep.txt) shows the same spots using `rg --multiline --multiline-dotall "DisruptionTarget\).*ApplyStatus\("`

**Comment by mimowo** [comment]
In the last commit I move the other remaining places to SMP. PTAL. Two remarks:
1. First, no integration tests reproducing the issue for the other places. Seems enough to demonstrate the issue in one place (podgc).

2. In disruption.go we used to pass resource version. We didn't have any tests showing this is really needed and it does not seem needed. The potential race condition is when disruption controller decides to change the Status to False (after 2 min). Then, another controller in between Get by the disruption controller re-adds the condition with `Status=True` and new `LastTransitionTime`. As a result the pod might get deleted when the `DisruptionTarget` `Status=False` (just after being flipped by disruption.go). This scenario seems very unlikely, and with limited consequences. Let me know if we care, and in case we care there does not seem to be a way to pass resource version in PatchPodStatus, so probably I would need to use Update in this case. WDYT @liggitt @alculquicondor ?

File: pkg/scheduler/framework/preemption/preemption.go [hunk 8]
```diff
@@ -362,19 +356,19 @@ func (ev *Evaluator) prepareCandidate(ctx context.Context, c Candidate, pod *v1.
...
-					errCh.SendErrorWithCancel(err, cancel)
-					return
+				condition := &v1.PodCondition{
+					Type:    v1.DisruptionTarget,
+					Status:  v1.ConditionTrue,
+					Reason:  v1.PodReasonPreemptionByScheduler,
+					Message: fmt.Sprintf("%s: preempting to accommodate a higher priority pod", pod.Spec.SchedulerName),
+				}
+				newStatus := pod.Status.DeepCopy()
+				if apipod.UpdatePodCondition(newStatus, condition) {
```
[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/scheduler/framework/preemption/preemption.go:366]: Thanks for catching this! 

I think preemption.go already skipped if no update. I just pushed an update to skip the Patch in the two other places.

**Review by tzneal — APPROVED** [review]
/lgtm

File: pkg/scheduler/framework/preemption/preemption.go [hunk 9]
```diff
@@ -362,19 +356,19 @@ func (ev *Evaluator) prepareCandidate(ctx context.Context, c Candidate, pod *v1.
...
+					if err := util.PatchPodStatus(ctx, cs, victim, newStatus); err != nil {
+						klog.ErrorS(err, "Preparing pod preemption", "pod", klog.KObj(victim), "preemptor", klog.KObj(pod))
```
Comment (atiratree) [inline pkg/scheduler/framework/preemption/preemption.go:368]: what is the reason behind the log change?

**Comment by alculquicondor** [comment]
/retitle Use Patch instead of SSA for Pod Disruption condition

File: pkg/controller/nodelifecycle/scheduler/taint_manager.go [hunk 10]
```diff
@@ -127,16 +125,16 @@ func addConditionAndDeletePod(ctx context.Context, c clientset.Interface, name,
...
-			WithType(v1.DisruptionTarget).
-			WithStatus(v1.ConditionTrue).
-			WithReason("DeletionByTaintManager").
-			WithMessage("Taint manager: deleting due to NoExecute taint").
-			WithLastTransitionTime(metav1.Now()),
-		)
-		if _, err := c.CoreV1().Pods(pod.Namespace).ApplyStatus(ctx, podApply, metav1.ApplyOptions{FieldManager: fieldManager, Force: true}); err != nil {
-			return err
+		newStatus := pod.Status.DeepCopy()
+		if apipod.UpdatePodCondition(newStatus, &v1.PodCondition{
```
Comment (alculquicondor) [inline pkg/controller/nodelifecycle/scheduler/taint_manager.go:129]: Do `updated :=`.

Otherwise the indentation can be a bit confusing.

**Review by atiratree — COMMENTED** [review]
> In disruption.go we used to pass resource version. We didn't have any tests showing this is really needed and it does not seem needed. The potential race condition is when disruption controller decides to change the Status to False (after 2 min). Then, another controller in between Get by the disruption controller re-adds the condition with Status=True and new LastTransitionTime. As a result the pod might get deleted when the DisruptionTarget Status=False (just after being flipped by disruption.go). This scenario seems very unlikely, and with limited consequences. Let me know if we care, and in case we care there does not seem to be a way to pass resource version in PatchPodStatus, so probably I would need to use Update in this case. WDYT @liggitt @alculquicondor ?

Hard to guess a likelyhood of this happening, but if you have a number of pods with stale conditions for any reason and node drain is  triggered for example (processing large number of pods), then these pods could end up with wrong condition. It might be safer to use the update with resourceVersion.

File: pkg/scheduler/framework/preemption/preemption.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/framework/preemption/preemption.go:366]: Same suggestion to do `updated := apipod.UpdatePodCondition`

**Review by alculquicondor — COMMENTED** [review]
/approve
for scheduler

**Comment by alculquicondor** [comment]
> Hard to guess a likelyhood of this happening, but if you have a number of pods with stale conditions for any reason and node drain is triggered for example (processing large number of pods), then these pods could end up with wrong condition. It might be safer to use the update with resourceVersion.

I agree that it might be safer to use Update for that case.

File: pkg/scheduler/framework/preemption/preemption.go (hunk 9 above)
Comment (mimowo) [reply pkg/scheduler/framework/preemption/preemption.go:368]: mistake, that I took it from the pr which moved from patch to SSA a while back. didn't notice the message change. I will make it as on master

**Comment by mimowo** [comment]
> I agree that it might be safer to use Update for that case.

Makes sense, tentatively updated.

File: pkg/controller/nodelifecycle/scheduler/taint_manager.go (hunk 10 above)
Comment (mimowo) [reply pkg/controller/nodelifecycle/scheduler/taint_manager.go]: done

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Comment by dims** [comment]
/approve

would recommend Jordan's one last scan before removing hold

**Comment by liggitt** [comment]
> would recommend Jordan's one last scan before removing hold

yup, queued up, will do my absolute best to sweep today

File: pkg/controller/disruption/disruption.go [hunk 11]
```diff
@@ -770,16 +766,15 @@ func (dc *DisruptionController) syncStalePodDisruption(ctx context.Context, key
...
-	if _, err := dc.kubeClient.CoreV1().Pods(pod.Namespace).ApplyStatus(ctx, podApply, metav1.ApplyOptions{FieldManager: fieldManager, Force: true}); err != nil {
+	newPod := pod.DeepCopy()
+	updated := apipod.UpdatePodCondition(&newPod.Status, &v1.PodCondition{
+		Type:   v1.DisruptionTarget,
+		Status: v1.ConditionFalse,
+	})
+	if !updated {
+		return nil
+	}
+	if _, err := dc.kubeClient.CoreV1().Pods(pod.Namespace).UpdateStatus(ctx, newPod, metav1.UpdateOptions{}); err != nil {
```
Comment (liggitt) [inline pkg/controller/disruption/disruption.go:777]: why isn't this using SMP patch? doing an update with no resource version set in UpdateOptions can stomp other pod status changes made in the meantime

File: pkg/controller/nodelifecycle/scheduler/taint_manager.go [hunk 12]
```diff
@@ -127,16 +125,17 @@ func addConditionAndDeletePod(ctx context.Context, c clientset.Interface, name,
...
+		updated := apipod.UpdatePodCondition(newStatus, &v1.PodCondition{
+			Type:    v1.DisruptionTarget,
+			Status:  v1.ConditionTrue,
+			Reason:  "DeletionByTaintManager",
+			Message: "Taint manager: deleting due to NoExecute taint",
+		})
+		if updated {
+			if _, _, _, err := utilpod.PatchPodStatus(ctx, c, pod.Namespace, pod.Name, pod.UID, pod.Status, *newStatus); err != nil {
+				return err
+			}
```
Comment (liggitt) [inline pkg/controller/nodelifecycle/scheduler/taint_manager.go:138]: this bit lgtm

File: pkg/scheduler/framework/preemption/preemption.go [hunk 13]
```diff
@@ -362,19 +356,20 @@ func (ev *Evaluator) prepareCandidate(ctx context.Context, c Candidate, pod *v1.
...
+					Type:    v1.DisruptionTarget,
+					Status:  v1.ConditionTrue,
+					Reason:  v1.PodReasonPreemptionByScheduler,
+					Message: fmt.Sprintf("%s: preempting to accommodate a higher priority pod", pod.Spec.SchedulerName),
+				}
+				newStatus := pod.Status.DeepCopy()
+				updated := apipod.UpdatePodCondition(newStatus, condition)
+				if updated {
+					if err := util.PatchPodStatus(ctx, cs, victim, newStatus); err != nil {
+						klog.ErrorS(err, "Could not add DisruptionTarget condition due to preemption", "pod", klog.KObj(victim), "preemptor", klog.KObj(pod))
```
Comment (liggitt) [inline pkg/scheduler/framework/preemption/preemption.go:369]: why the switch away from `logger`?

Comment (mimowo) [reply pkg/scheduler/framework/preemption/preemption.go]: I made the change by reverting the old PR which transitioned from SMP to SSA, and didn't notice when resolving conflicts.  Fixed now.

File: plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go [hunk 14]
```diff
@@ -140,7 +140,7 @@ func buildControllerRoles() ([]rbacv1.ClusterRole, []rbacv1.ClusterRoleBinding)
...
```
[the remark this answers is not in the document]
Comment (mimowo) [reply plugin/pkg/auth/authorizer/rbac/bootstrappolicy/controller_policy.go:143]: In the current implementation this is needed for the update in the disruption. I will revert if we go with patch there.

File: pkg/controller/disruption/disruption.go (hunk 11 above)
Comment (mimowo) [reply pkg/controller/disruption/disruption.go:777]: The intention of using update here is to fail on conflicts. I describe the possible scenario here: https://github.com/kubernetes/kubernetes/pull/121103#pullrequestreview-1685540049.

Basically, if we don't check resource  version here, it is possible (but unlikely) the pod will be deleted when `DisruptionTarget=False`, if the disruption controller switches the status from True to False due to categorizing it as stale after 2min, and in this time another controller updates the condition (with new LastTransitionTime).

Comment (mimowo) [reply pkg/controller/disruption/disruption.go:777]: I double checked that the concurrent update of pod performed analogously as  in disraption.go fails. I used the following test:
```golang
func TestUpdateAfterPatch(t *testing.T) {
	testCtx := setup(t, "concurrent-updates")
	cs := testCtx.ClientSet
	pod := &v1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name: "testpod",
		},
		Spec: v1.PodSpec{
			Containers: []v1.Container{
				{
					Name:  "my",
					Image: "my",
				},
			},
		},
	}
	pod, err := cs.CoreV1().Pods(testCtx.NS.Name).Create(testCtx.Ctx, pod, metav1.CreateOptions{})
	if err != nil {
		t.Fatalf("Error %v, while creating pod: %v", err, klog.KObj(pod))
	}
	newStatus := pod.Status.DeepCopy()
	newStatus.Phase = v1.PodFailed
	if err := util.PatchPodStatus(testCtx.Ctx, cs, pod, newStatus); err != nil {
		t.Fatalf("Error %v, while patching pod (patch1): %v", err, klog.KObj(pod))
	}
	podNew2 := pod.DeepCopy()
	apipod.UpdatePodCondition(&podNew2.Status, &v1.PodCondition{
		Type:   v1.DisruptionTarget,
		Status: v1.ConditionFalse,
	})
	if _, err := cs.CoreV1().Pods(pod.Namespace).UpdateStatus(testCtx.Ctx, podNew2, metav1.UpdateOptions{}); err != nil {
		t.Fatalf("Error %v, while updating pod (update2): %v", err, klog.KObj(pod))
	}
}
```

This fails with ``Error Operation cannot be fulfilled on pods "testpod": the object has been modified; please apply your changes to the latest version and try again, while updating pod (update2): concurrent-updates02bbb0a7-c74f-42ef-a662-373f57ee19b0/testpod`.

So I think the current behavior reflects the sentiment of staying on the safe side expressed also in this [comment](https://github.com/kubernetes/kubernetes/pull/121103#issuecomment-1768951983).

Comment (mimowo) [reply pkg/controller/disruption/disruption.go:777]: I think that the updates performed by disraption.go should be exception, as they require 2min of the DisruptionTarget being stale. Because it is rare, and negative path (the other controlled to succeed with Patch, but fail with Delete), I think correctness might be more important than performance. Still, I'm ok with both approaches, just outlining the reasoning.

Comment (liggitt) [reply pkg/controller/disruption/disruption.go:777]: > Doing an update like this with no resourceVersion set in UpdateOptions

you're correct, the resourceVersion is in the pod being sent to the update, not in the UpdateOptions

having this controller fail safe and requeue in a conflict case sgtm

**Comment by liggitt** [comment]
thanks, changes lgtm, since this will be cherry-picked, go ahead and squash (rather than using the tide squash)

**Comment by dims** [comment]
/lgtm

@mimowo happy to lgtm again when you squash by hand

**Comment by mimowo** [comment]
> @mimowo happy to lgtm again when you squash by hand

Thanks, got the notification, I will soon.

**Comment by mimowo** [comment]
Ready, thank you all for reviewing 🎉

**Comment by liggitt** [comment]
thanks, go ahead and open the picks back to 1.26/1.27/1.28

**Comment by mimowo** [comment]
> thanks, go ahead and open the picks back to 1.26/1.27/1.28

Sure, opened:
- [1.28](https://github.com/kubernetes/kubernetes/pull/121379)
- [1.27](https://github.com/kubernetes/kubernetes/pull/121380)
- [1.26](https://github.com/kubernetes/kubernetes/pull/121381)

**Comment by sftim** [comment]
Changelog suggestion
```markdown
Fixed a regression in default configurations in that enabled PodDisruptionConditions by default, 
that then prevented the control plane's pod garbage collector from deleting pods that contained duplicated field keys (env. variables with repeated keys or container ports).
```

**Comment by mimowo** [comment]
> Changelog suggestion
> 
> ```
> Fixed a regression in default configurations in that enabled PodDisruptionConditions by default, 
> that then prevented the control plane's pod garbage collector from deleting pods that contained duplicated field keys (env. variables with repeated keys or container ports).
> ```

Thanks, applied the note, just rephrased slightly the first part. PTAL.
