### PR TITLE
check image present after pulled image with no error

### LINKED ISSUE #16147: get successfully pulled event when pull  non-exist image
I set a non-exist image in rc and watch event.
```
kubectl run my-nginx --replicas=2 --image=ngixn --port=80
kubectl get event -w
```
kubelet is supposed to throw failed pull event and actually we get failed pull event. But I noticed there is an "successfully pulled image" event.
```
3s          3s         1         my-nginx         ReplicationController                                       SuccessfulCreate   {replication-controller }   Created pod: my-nginx-tkigj
3s          3s         1         my-nginx-tkigj   Pod                                                         Scheduled          {scheduler }                Successfully assigned my-nginx-tkigj to 127.0.0.1
3s          3s         1         my-nginx-p70z0   Pod                                                         Scheduled          {scheduler }                Successfully assigned my-nginx-p70z0 to 127.0.0.1
3s          3s         1         my-nginx         ReplicationController                                       SuccessfulCreate   {replication-controller }   Created pod: my-nginx-p70z0
2s          2s         1         my-nginx-p70z0   Pod                     spec.containers{my-nginx}           Pulling            {kubelet 127.0.0.1}         pulling image "ngixn"
2s          2s         1         my-nginx-tkigj   Pod                     spec.containers{my-nginx}           Pulling            {kubelet 127.0.0.1}         pulling image "ngixn"
2s          2s         1         my-nginx-tkigj   Pod                     implicitly required container POD   Pulled             {kubelet 127.0.0.1}         Container image "beta.gcr.io/google_containers/pause:2.0" already present on machine
2s          2s         1         my-nginx-tkigj   Pod                     implicitly required container POD   Created            {kubelet 127.0.0.1}         Created with docker id d07e749fa273
2s          2s         1         my-nginx-tkigj   Pod                     implicitly required container POD   Started            {kubelet 127.0.0.1}         Started with docker id d07e749fa273
2s          2s         1         my-nginx-p70z0   Pod                     implicitly required container POD   Pulled             {kubelet 127.0.0.1}         Container image "beta.gcr.io/google_containers/pause:2.0" already present on machine
2s          2s         1         my-nginx-p70z0   Pod                     implicitly required container POD   Created            {kubelet 127.0.0.1}         Created with docker id 4fefe0069769
2s          2s         1         my-nginx-p70z0   Pod                     implicitly required container POD   Started            {kubelet 127.0.0.1}         Started with docker id 4fefe0069769
FIRSTSEEN   LASTSEEN   COUNT     NAME             KIND      SUBOBJECT                   REASON    SOURCE                MESSAGE
0s          0s         1         my-nginx-tkigj   Pod       spec.containers{my-nginx}   Failed    {kubelet 127.0.0.1}   Failed to pull image "ngixn": Error: image library/ngixn:latest not found
0s        0s        1         my-nginx-tkigj   Pod       spec.containers{my-nginx}   Back-off   {kubelet 127.0.0.1}   Back-off pulling image "ngixn"
0s        0s        1         my-nginx-p70z0   Pod       spec.containers{my-nginx}   Failed    {kubelet 127.0.0.1}   Failed to pull image "ngixn": Error: image library/ngixn:latest not found
0s        0s        1         my-nginx-p70z0   Pod       spec.containers{my-nginx}   Back-off   {kubelet 127.0.0.1}   Back-off pulling image "ngixn"
5s        0s        2         my-nginx-tkigj   Pod       spec.containers{my-nginx}   Back-off   {kubelet 127.0.0.1}   Back-off pulling image "ngixn"
5s        0s        2         my-nginx-p70z0   Pod       spec.containers{my-nginx}   Back-off   {kubelet 127.0.0.1}   Back-off pulling image "ngixn"
29s       0s        2         my-nginx-p70z0   Pod       spec.containers{my-nginx}   Pulling   {kubelet 127.0.0.1}   pulling image "ngixn"
29s       0s        2         my-nginx-tkigj   Pod       spec.containers{my-nginx}   Pulling   {kubelet 127.0.0.1}   pulling image "ngixn"
0s        0s        1         my-nginx-p70z0   Pod       spec.containers{my-nginx}   Pulled    {kubelet 127.0.0.1}   Successfully pulled image "ngixn"
0s        0s        1         my-nginx-p70z0   Pod       spec.containers{my-nginx}   Failed    {kubelet 127.0.0.1}   Failed to create docker container with error: no such image
21s       0s        2         my-nginx-tkigj   Pod       spec.containers{my-nginx}   Failed    {kubelet 127.0.0.1}   Failed to pull image "ngixn": Error: image library/ngixn:latest not found
25s       0s        3         my-nginx-tkigj   Pod       spec.containers{my-nginx}   Back-off   {kubelet 127.0.0.1}   Back-off pulling image "ngixn"
39s       0s        3         my-nginx-p70z0   Pod       spec.containers{my-nginx}   Pulling   {kubelet 127.0.0.1}   pulling image "ngixn"
32s       0s        2         my-nginx-p70z0   Pod       spec.containers{my-nginx}   Failed    {kubelet 127.0.0.1}   Failed to pull image "ngixn": Error: image library/ngixn:latest not found
35s       0s        4         my-nginx-tkigj   Pod       spec.containers{my-nginx}   Back-off   {kubelet 127.0.0.1}   Back-off pulling image "ngixn"
35s       0s        3         my-nginx-p70z0   Pod       spec.containers{my-nginx}   Back-off   {kubelet 127.0.0.1}   Back-off pulling image "ngixn"
45s       0s        4         my-nginx-p70z0   Pod       spec.containers{my-nginx}   Back-off   {kubelet 127.0.0.1}   Back-off pulling image "ngixn"

```

### PR DESCRIPTION
**Pull request by jiangyaoguo**
fixed #16147 
This is a hacky fix. Sometimes docker client PullImage failed with no error.

### CODE REVIEW

File: pkg/kubelet/dockertools/docker.go [hunk 1]
```diff
@@ -160,6 +160,10 @@ func (p dockerPuller) Pull(image string, secrets []api.Secret) error {
 
 		err := p.client.PullImage(opts, docker.AuthConfiguration{})
 		if err == nil {
+			// Sometimes PullImage failed with no error returned.
```
Comment (brendandburns) [inline pkg/kubelet/dockertools/docker.go]: Please differentiate between the `!exist` and `ierr != nil` cases, or just print the `ierr` into the error message

**Comment by jiangyaoguo** [comment]
@brendandburns PTAL

**Comment by brendandburns** [comment]
LGTM, thanks
