### PR TITLE
Fix scheduler cache inconsistency upon Pods with same name but different UIDs

### LINKED ISSUE #85726: Deleted pods may remain in scheduler cache and cause scheduling exception
**What happened**:
pod can't be removed from scheduler cache when be deleted,  logs in kube-scheduler is below:

I1128 16:41:50.819639   31593 leaderelection.go:344] lock is held by shaphicpra14907_64ccb0c5-aaa1-435d-a4b4-ead4bb3de63b and has not yet expired
I1128 16:41:50.819678   31593 leaderelection.go:240] failed to acquire lease kube-system/kube-scheduler
I1128 16:41:53.740234   31593 leaderelection.go:344] lock is held by shaphicpra14907_64ccb0c5-aaa1-435d-a4b4-ead4bb3de63b and has not yet expired
I1128 16:41:53.740365   31593 leaderelection.go:240] failed to acquire lease kube-system/kube-scheduler
I1128 16:41:57.734692   31593 leaderelection.go:245] successfully acquired lease kube-system/kube-scheduler
I1128 16:41:57.834958   31593 shared_informer.go:176] caches populated
E1128 16:42:11.731020   31593 eventhandlers.go:226] scheduler cache UpdatePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not added to scheduler cache, so cannot be updated
E1128 16:42:12.339189   31593 eventhandlers.go:226] scheduler cache UpdatePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not added to scheduler cache, so cannot be updated
E1128 16:42:12.345323   31593 eventhandlers.go:226] scheduler cache UpdatePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not added to scheduler cache, so cannot be updated
E1128 16:42:20.628894   31593 eventhandlers.go:226] scheduler cache UpdatePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not added to scheduler cache, so cannot be updated
E1128 16:42:20.632578   31593 eventhandlers.go:254] scheduler cache RemovePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not found in scheduler cache, so cannot be removed from it

**What you expected to happen**:

pod in scheduler cache can be deleted successfully when pod is deleted

**How to reproduce it (as minimally and precisely as possible)**:

main steps to reproduce this bug is these:
1. two scheduler run in leader-elect=true mode，schedulerA is the leader scheduler, and schedulerB is an assistant.
2. create pod1 with "namespace1/name1" and it runs on Node1
3. break down the network between schedulerB and kube-apiserver
4. delete pod1 and create pod2 with same name, ie "namespace1/name1" and pod2 been assigned to Node1 by schedulerA again.
5. turn off schedulerA and recover the network between schedulerB and kube-apiserver, and then schedulerB become the leader scheduler.
6. delete pod2. this time log in schedulerB will print this: 

E1128 16:42:11.731020   31593 eventhandlers.go:226] scheduler cache UpdatePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not added to scheduler cache, so cannot be updated
E1128 16:42:20.632578   31593 eventhandlers.go:254] scheduler cache RemovePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not found in scheduler cache, so cannot be removed from it

7. At this time, if I create a new pod3 with podAntiAffinity to pod1. the result is pod3 can't been assigned to Node1 because pod1 is still in schedulerB's scheduler cache.

**Anything else we need to know?**:

the reason of this bug is below:

since PR(https://github.com/kubernetes/kubernetes/pull/61069), podKey in scheduler cache use pod's UID instead of namespace/name
however, the key in SharedIndexInformer still use namespace/name
in this upper case, delete the pod and create a same name pod may be delivered as one update notification.( see disscusion： https://github.com/kubernetes/kubernetes/issues/83810)
scheduler received pod update notification and then print below log.

E1128 16:42:11.731020   31593 eventhandlers.go:226] scheduler cache UpdatePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not added to scheduler cache, so cannot be updated
 

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind bug
/sig scheduling
/priority important-soon

**What this PR does / why we need it**:

(This PR is taken over from #85910 due to its inactive activity)

The root cause is from API server which may combine a Delete and Add Pod event (the same Pod name) as a Update event:

(copied from original issue)

> since PR(#61069), podKey in scheduler cache use pod's UID instead of namespace/name
however, the key in SharedIndexInformer still use namespace/name
in this upper case, delete the pod and create a same name pod may be delivered as one update notification.( see disscusion： #83810)

**Which issue(s) this PR fixes**:

Fixes #85726.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
In a HA env, during the period a standby scheduler lost connection to API server, if a Pod is deleted and recreated, and the standby scheduler becomes master afterwards, there could be a scheduler cache corruption. This PR fixes this issue. 
```

### CODE REVIEW

**Comment by ahg-g** [comment]
wow, you would think that events are per pod as identified by its UID! It is surprising to me that a delete followed by add are merged because those are two different pods!

File: pkg/scheduler/eventhandlers.go [hunk 1]
```diff
@@ -243,6 +243,15 @@ func (sched *Scheduler) updatePodInCache(oldObj, newObj interface{}) {
 		return
 	}
 
+	// A Pod delete event followed by an immediate Pod add event may be merged
+	// into a Pod update event. In this case, we should invalidate the old Pod, and
+	// then add the new Pod.
+	if oldPod.UID != newPod.UID {
```
Comment (ahg-g) [inline pkg/scheduler/eventhandlers.go:249]: Why are we here? shouldn't we be here only if NodeName was set? it is not going to be set for the new pod, right?

Comment (Huang-Wei) [reply pkg/scheduler/eventhandlers.go:249]: It's described in #85726 in a HA setup and the author provided a detailed log. Basically it's like this:

- schedA as the master, schedB as the standby.
- testPod is scheduled to node1; schedA and schedB both gets that cached properly.
- shut down schedB.
- at the same time, testPod is deleted and then created - schedA works fine - 2 events (Delete and Add) get received, and the new testPod got scheduled (to node1 let's say).
- shut down schedA and start schedB.
- an interesting thing happens. schedB receives 1 Update event (instead of 2 events) on testPod. Because schedB only has the stale testPod's UID in place, and the internal scheduler `cache state` uses UID to check the Pod's presence, it throws an error and failed the update:
    ```
    E1128 16:42:11.731020 31593 eventhandlers.go:226] scheduler cache UpdatePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not added to scheduler cache, so cannot be updated
    ```
- this error is critical, as it means the stale testPod live in scheduler's cache (instead of the new testPod) is corrupted.
- deleting testPod doesn't help, as it cannot be deleted due to UID not found.
    ```
    E1128 16:42:20.632578 31593 eventhandlers.go:254] scheduler cache RemovePod failed: pod 3c6696c6-decb-4abd-a1d3-d891e032459d is not found in scheduler cache, so cannot be removed from it
    ```

**Comment by Huang-Wei** [comment]
> wow, you would think that events are per pod as identified by its UID! It is surprising to me that a delete followed by add are merged because those are two different pods!

If I understand https://github.com/kubernetes/kubernetes/issues/83810#issuecomment-541885957 correctly, it's the case.

File: pkg/scheduler/eventhandlers.go (hunk 1 above)
Comment (ahg-g) [reply pkg/scheduler/eventhandlers.go:249]: ah, ok, so testPod did get scheduled a second time already, and so it's NodeName is set and that triggers a proper update.

I was assuming that the new pod isn't scheduled yet, and so according to the [OnUpdate handler](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/controller.go#L264-L276) the update should change to a delete event on the cache and an add event on the queue, which make sense.

File: pkg/scheduler/eventhandlers_test.go [hunk 2]
```diff
@@ -346,3 +349,46 @@ func TestNodeConditionsChanged(t *testing.T) {
...
+				SchedulingQueue: schedulerQueue,
+			}
+			sched.addPodToCache(tt.oldObj)
+			sched.updatePodInCache(tt.oldObj, tt.newObj)
+			pod, err := sched.SchedulerCache.GetPod(tt.newObj.(*v1.Pod))
+			if err != nil {
+				t.Errorf("Failed to get pod from scheduler: %v", err)
+			}
+			if pod.UID != tt.newObj.(*v1.Pod).UID {
+				t.Errorf("Expected get pod UID %v, got %v", tt.newObj.(*v1.Pod).UID, pod.UID)
```
Comment (ahg-g) [inline pkg/scheduler/eventhandlers_test.go:390]:
```suggestion
				t.Errorf("want pod UID %v, got %v", tt.newObj.(*v1.Pod).UID, pod.UID)
```

File: pkg/scheduler/eventhandlers_test.go [hunk 3]
```diff
@@ -346,3 +349,46 @@ func TestNodeConditionsChanged(t *testing.T) {
...
+
+	tests := []struct {
+		name   string
+		oldObj interface{}
+		newObj interface{}
+	}{
+		{
+			name:   "test update pod with same uid",
+			oldObj: podWithPort("oldUID", nodeName, 80),
+			newObj: podWithPort("oldUID", nodeName, 8080),
```
Comment (ahg-g) [inline pkg/scheduler/eventhandlers_test.go:365]: this is not quite accurate test because the pod names are also different, but I think it is fine for the purpose of the test.

**Review by ahg-g — COMMENTED** [review]
looks good to me

File: pkg/scheduler/eventhandlers.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/scheduler/eventhandlers.go:249]: Is there a bug filled for kube-apiserver? I'm fine with dealing with it here for now.

**Review by alculquicondor — COMMENTED** [review]
/lgtm

File: pkg/scheduler/eventhandlers.go (hunk 1 above)
Comment (Huang-Wei) [reply pkg/scheduler/eventhandlers.go:249]: > Is there a bug filled for kube-apiserver?

I _prefer_ to believe it's a bug, but seems it's not the case from api's perspective, and I don't it can be "fixed" b/c the underlying DeltaFIFO queue is using namespace/name as the index.

File: pkg/scheduler/eventhandlers_test.go (hunk 3 above)
Comment (Huang-Wei) [reply pkg/scheduler/eventhandlers_test.go:365]: yes, let me update it.

File: pkg/scheduler/eventhandlers_test.go (hunk 2 above)
Comment (Huang-Wei) [reply pkg/scheduler/eventhandlers_test.go:390]: done.

**Comment by Huang-Wei** [comment]
@ahg-g comments addressed. PTAL.

**Comment by Huang-Wei** [comment]
Added a detailed release note.

**Comment by alculquicondor** [comment]
sg
