### PR TITLE
Fix index out of range if multiple default plugins are overridden

### LINKED ISSUE #103572: scheduler: index out of range
#### What happened:
Recent commit: https://github.com/kubernetes/kubernetes/pull/99582 import an issue when multiple custom plugin configured in scheduler config file,  and those plugins are default plugins too.

It was manipulating slice with index, but the slice is updated while index is not, which will cause the index out of range, see the exceptions listed below,

```
I0708 11:11:58.252251    6748 default_plugins.go:173] "Defaut plugin is explicitly re-configured and is overriding." plugin="InterPodAffinity"
panic: runtime error: slice bounds out of range [5:3]

goroutine 1 [running]:
k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta2.mergePluginSet(0xc00069d340, 0x7, 0x7, 0x0, 0x0, 0x0, 0xc0006a9080, 0x3, 0x8, 0x0, ...)
        /go/src/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta2/default_plugins.go:177 +0x979
k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta2.mergePlugins(0xc0003c2fc0, 0xc00042afc0, 0xc00067c0c0)
        /go/src/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta2/default_plugins.go:138 +0x1f3
k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta2.setDefaults_KubeSchedulerProfile(0xc00015cea0)
        /go/src/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta2/defaults.go:71 +0x4d
k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta2.SetDefaults_KubeSchedulerConfiguration(0xc00015b9e0)
        /go/src/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta2/defaults.go:123 +0xf3
k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta2.SetObjectDefaults_KubeSchedulerConfiguration(...)
        /go/src/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta2/zz_generated.defaults.go:55
k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta2.RegisterDefaults.func3(0x1ff0280, 0xc00015b9e0)
        /go/src/k8s.io/kubernetes/pkg/scheduler/apis/config/v1beta2/zz_generated.defaults.go:35 +0x3c
k8s.io/apimachinery/pkg/runtime.(*Scheme).Default(0xc0004d5880, 0x230ba38, 0xc00015b9e0)
        /go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:368 +0xb5
k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Decode(0xc0000d4780, 0xc00074d000, 0xff5, 0xff6, 0x0, 0x0, 0x0, 0xc0002febe0, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:168 +0x438
k8s.io/kubernetes/cmd/kube-scheduler/app/options.loadConfig(0xc00074d000, 0xff5, 0xff6, 0xff5, 0xff6, 0x0)
        /go/src/k8s.io/kubernetes/cmd/kube-scheduler/app/options/configfile.go:45 +0xc2

```
#### What you expected to happen:
config file should be handled properly without such exception

#### How to reproduce it (as minimally and precisely as possible):
override multiple default plugin in scheduler's config file.

#### Environment:
- Kubernetes version (use `kubectl version`): latest (1.22)
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): all
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/assign

### PR DESCRIPTION
**Pull request by chendave**
Commit1: Fix index out of range if multiple default plugins are overridden - https://github.com/kubernetes/kubernetes/issues/103572
Commit2: Revert https://github.com/kubernetes/kubernetes/pull/103327 

Signed-off-by: Dave Chen <dave.chen@arm.com>

/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/103572

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by chendave** [comment]
/cc @alculquicondor @SataQiu @liggitt 

Sorry for the defect, I know code freezing is coming and this is too rush to ask for review from you guys.

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go [hunk 1]
```diff
@@ -172,14 +169,18 @@ func mergePluginSet(defaultPluginSet, customPluginSet v1beta2.PluginSet) v1beta2
 			if customPlugin, ok := enabledCustomPlugins[defaultEnabledPlugin.Name]; ok {
 				klog.InfoS("Defaut plugin is explicitly re-configured and is overriding.", "plugin", defaultEnabledPlugin.Name)
```
Comment (Huang-Wei) [inline pkg/scheduler/apis/config/v1beta2/default_plugins.go:170]:
```suggestion
				klog.InfoS("Default plugin is explicitly re-configured and is overriding.", "plugin", defaultEnabledPlugin.Name)
```

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go [hunk 2]
```diff
@@ -148,19 +148,16 @@ func mergePlugins(defaultPlugins, customPlugins *v1beta2.Plugins) *v1beta2.Plugi
...
-type pluginIndex struct {
-	index  int
-	plugin v1beta2.Plugin
-}
-
 func mergePluginSet(defaultPluginSet, customPluginSet v1beta2.PluginSet) v1beta2.PluginSet {
 	disabledPlugins := sets.NewString()
-	enabledCustomPlugins := make(map[string]pluginIndex)
+	// replacedCustomPlugins is a set of plugins, each of them is default plugin as well.
+	replacedCustomPlugins := sets.NewString()
```
Comment (Huang-Wei) [inline pkg/scheduler/apis/config/v1beta2/default_plugins.go:154]: We can eliminate this by simply remove the entry from enabledCustomPlugins:

```diff
diff --git a/pkg/scheduler/apis/config/v1beta2/default_plugins.go b/pkg/scheduler/apis/config/v1beta2/default_plugins.go
index dd5cbb3ff10..dcdc79bb2d2 100644
--- a/pkg/scheduler/apis/config/v1beta2/default_plugins.go
+++ b/pkg/scheduler/apis/config/v1beta2/default_plugins.go
@@ -150,8 +150,6 @@ func mergePlugins(defaultPlugins, customPlugins *v1beta2.Plugins) *v1beta2.Plugi
 
 func mergePluginSet(defaultPluginSet, customPluginSet v1beta2.PluginSet) v1beta2.PluginSet {
 	disabledPlugins := sets.NewString()
-	// replacedCustomPlugins is a set of plugins, each of them is default plugin as well.
-	replacedCustomPlugins := sets.NewString()
 	enabledCustomPlugins := make(map[string]v1beta2.Plugin)
 	for _, disabledPlugin := range customPluginSet.Disabled {
 		disabledPlugins.Insert(disabledPlugin.Name)
@@ -170,7 +168,7 @@ func mergePluginSet(defaultPluginSet, customPluginSet v1beta2.PluginSet) v1beta2
 				klog.InfoS("Defaut plugin is explicitly re-configured and is overriding.", "plugin", defaultEnabledPlugin.Name)
 				// update the default plugin in place to preserve order
 				defaultEnabledPlugin = customPlugin
-				replacedCustomPlugins.Insert(customPlugin.Name)
+				delete(enabledCustomPlugins, defaultEnabledPlugin.Name)
 			}
 			enabledPlugins = append(enabledPlugins, defaultEnabledPlugin)
 		}
@@ -178,7 +176,7 @@ func mergePluginSet(defaultPluginSet, customPluginSet v1beta2.PluginSet) v1beta2
 
 	// append all the custom plugins which are not defined as default plugins.
 	for _, plugin := range customPluginSet.Enabled {
-		if !replacedCustomPlugins.Has(plugin.Name) {
+		if _, ok := enabledCustomPlugins[plugin.Name]; ok {
 			enabledPlugins = append(enabledPlugins, plugin)
 		}
 	}
```

Comment (chendave) [reply pkg/scheduler/apis/config/v1beta2/default_plugins.go:154]: thumb up,  this looks better!

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go (hunk 1 above)
Comment (chendave) [reply pkg/scheduler/apis/config/v1beta2/default_plugins.go]: Done

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go (hunk 2 above)
Comment (chendave) [reply pkg/scheduler/apis/config/v1beta2/default_plugins.go]: mark this as resolved, and amend the commit directly.

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go [hunk 3]
```diff
@@ -170,16 +165,20 @@ func mergePluginSet(defaultPluginSet, customPluginSet v1beta2.PluginSet) v1beta2
 			}
 			// The default plugin is explicitly re-configured, update the default plugin accordingly.
 			if customPlugin, ok := enabledCustomPlugins[defaultEnabledPlugin.Name]; ok {
-				klog.InfoS("Defaut plugin is explicitly re-configured and is overriding.", "plugin", defaultEnabledPlugin.Name)
+				klog.InfoS("Default plugin is explicitly re-configured and is overriding.", "plugin", defaultEnabledPlugin.Name)
```
Comment (alculquicondor) [inline pkg/scheduler/apis/config/v1beta2/default_plugins.go:168]: nit: `Default plugin is explicitly re-configured; overriding`

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go [hunk 4]
```diff
@@ -170,16 +165,20 @@ func mergePluginSet(defaultPluginSet, customPluginSet v1beta2.PluginSet) v1beta2
...
+				delete(enabledCustomPlugins, defaultEnabledPlugin.Name)
 			}
 			enabledPlugins = append(enabledPlugins, defaultEnabledPlugin)
 		}
 	}
 
-	enabledPlugins = append(enabledPlugins, customPluginSet.Enabled...)
+	// append all the custom plugins which are not defined as default plugins.
+	for _, plugin := range customPluginSet.Enabled {
+		if _, ok := enabledCustomPlugins[plugin.Name]; ok {
```
Comment (alculquicondor) [inline pkg/scheduler/apis/config/v1beta2/default_plugins.go:179]: Isn't this getting rid of repeated elements (if they are also default)?

**Comment by alculquicondor** [comment]
Also, make sure that there is a unit test that overrides more than one default. I think that would have been enough to trigger the bug you found?

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go (hunk 4 above)
Comment (chendave) [reply pkg/scheduler/apis/config/v1beta2/default_plugins.go:179]: I think so, here are three choices, 
- If there are repeated elements, accept the first one, and ignore others, this is what's this PR does, but we need to add some note somewhere.
- throw an exception here, and say the repeated elements are not allowed, which align with the logic when the framework are initialized.
- try to save the index of custom plugin somewhere and compare the index when appending the left custom plugins, so it will fail later during the framework instantiation (maybe a little dirty to achieve this.) 

second choices looks easier, what do you think?

**Comment by chendave** [comment]
> Also, make sure that there is a unit test that overrides more than one default.

Test case has already updated.

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go (hunk 4 above)
Comment (alculquicondor) [reply pkg/scheduler/apis/config/v1beta2/default_plugins.go:179]: I prefer the third option. Defaulting shouldn't validate.

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go (hunk 3 above)
Comment (chendave) [reply pkg/scheduler/apis/config/v1beta2/default_plugins.go]: Done

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go (hunk 4 above)
Comment (chendave) [reply pkg/scheduler/apis/config/v1beta2/default_plugins.go]: pls refer to the testcase "RepeatedCustomPlugin", the repeated custom plugin will be kept.

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go [hunk 5]
```diff
@@ -170,16 +172,23 @@ func mergePluginSet(defaultPluginSet, customPluginSet v1beta2.PluginSet) v1beta2
...
+				delete(enabledCustomPlugins, defaultEnabledPlugin.Name)
 			}
 			enabledPlugins = append(enabledPlugins, defaultEnabledPlugin)
 		}
 	}
 
-	enabledPlugins = append(enabledPlugins, customPluginSet.Enabled...)
+	// Append all the custom plugins which haven't replaced any default plugins.
+	// It's possible that there might be repeated custom plugins, these repeated plugins would be appended as well,
+	// so that it will be detected when the instantiation of scheduler framework and banned there.
```
Comment (Huang-Wei) [inline pkg/scheduler/apis/config/v1beta2/default_plugins.go:187]:
```suggestion
	// Note: duplicated custom plugins will still be appended here.
	// If so, the instantiation of scheduler framework will detect it and abort.
```

**Review by Huang-Wei — COMMENTED** [review]
Some nits. LGTM otherwise.

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go [hunk 6]
```diff
@@ -156,6 +156,8 @@ type pluginIndex struct {
 func mergePluginSet(defaultPluginSet, customPluginSet v1beta2.PluginSet) v1beta2.PluginSet {
 	disabledPlugins := sets.NewString()
 	enabledCustomPlugins := make(map[string]pluginIndex)
+	// replacedCustomPlugins is a set of index of plugins, which have replaced the default plugins.
+	replacedCustomPlugins := sets.NewInt32()
```
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/apis/config/v1beta2/default_plugins.go]: Done

File: pkg/scheduler/apis/config/v1beta2/default_plugins.go (hunk 5 above)
Comment (chendave) [reply pkg/scheduler/apis/config/v1beta2/default_plugins.go]: Done

**Comment by chendave** [comment]
@Huang-Wei  thanks for the comments!

**Review by alculquicondor — COMMENTED** [review]
/lgtm
/approve

Thanks!
