### PR TITLE
Dump stdin to a temporary file in kubectl replace --force

### LINKED ISSUE #11227: kubectl replace --force doesn't work with stdin input
Resource description is read 2 times (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubectl/cmd/replace.go#L135).
The second attempt fails (stdin is not "rewinded")
```
$ kubectl create -f examples/update-demo/nautilus-rc.yaml
$ sed 's/update-demo-kitten/update-demo-nautilus/g' examples/update-demo/kitten-rc.yaml | kubectl replace --force -f -
replicationcontrollers/update-demo-nautilus
read /dev/stdin: bad file descriptor
```
As a result the resource is deleted but not created again.

### PR DESCRIPTION
**Pull request by mwielgus**
Fixes #11227

### CODE REVIEW

File: pkg/kubectl/cmd/util/helpers.go [hunk 1]
```diff
@@ -406,3 +406,25 @@ func Merge(dst runtime.Object, fragment, kind string) (runtime.Object, error) {
...
 }
+
+// DumpReaderToFile writes all data from the given io.Reader to the specified file
+// (usually for temporary use).
+func DumpReaderToFile(reader io.Reader, filename string) error {
+	f, err := os.OpenFile(filename, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
+	if err != nil {
+		return err
+	}
+	data, err := ioutil.ReadAll(reader)
```
Comment (gmarek) [inline pkg/kubectl/cmd/util/helpers.go]: I have no idea if in go we worry about possible buffer overflows. If you know that we don't it's OK, otherwise please batch reads.

Comment (mwielgus) [inline pkg/kubectl/cmd/util/helpers.go]: We have `ioutil.ReadAll` in various places but OK, I will fix it.

Comment (gmarek) [inline pkg/kubectl/cmd/util/helpers.go]: Well - I wasn't reviewing other ones;) Thanks.
