### PR TITLE
[proxier/ipvs] Disable graceful termination for UDP traffic

### LINKED ISSUE #76664: ipvs UDP to garbage collect realServers
**What happened**:
We're running `syslog` pod behind `service` and sending logs via UDP to it.
It is k8s v1.13.3 with ipvs services.
When `syslog` pod gets restarted logs getting blackholed.
Simplified example on a node:
```
# ipvsadm -Ln | grep :514
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
UDP  192.168.127.89:514 lc
  -> 192.168.128.193:514          Masq    1      0          1
  -> 192.168.129.116:514          Masq    0      0          1
```
So, old pod had IP 192.168.129.116, new pod - 192.168.128.193.
Weight correctly forwards all new traffic to new pod, but there are some `InActConn` which are still sending traffic to non-existing IP:
```
# ipvsadm -Lnc | grep :514
IPVS connection entries
pro expire state       source             virtual            destination
UDP 04:24  UDP         192.168.127.89:44117 192.168.127.89:514 192.168.129.116:514
UDP 04:12  UDP         192.168.128.178:42898 192.168.127.89:514 192.168.128.193:514
```
Minimal value for UDP connection expiration is 1s:
`ipvsadm --set 0 0 1`
But logs are being sent at much faster rates, so these broken connections are never expire.
Issue introduced by
https://github.com/kubernetes/kubernetes/issues/71514
https://github.com/kubernetes/kubernetes/pull/71881
Looks like this supposed to keep old pod running, while there are still connections to it
```go
			// Delete RS with no connections
			// For UDP, ActiveConn is always 0
			// For TCP, InactiveConn are connections not in ESTABLISHED state
			if rs.ActiveConn+rs.InactiveConn != 0 {
```
But is there a reason to still keep these realServer entries, while old pod already cleaned up and no such IP exist?

**What you expected to happen**:
`kube-proxy` would cleanup all non-existing realServers from ipvs entries.

**How to reproduce it (as minimally and precisely as possible)**:
Repro steps are same as for host-port issue:
https://github.com/kubernetes/kubernetes/issues/59033

**Anything else we need to know?**:
sysctls are default:
```
net.ipv4.vs.expire_nodest_conn = 1
net.ipv4.vs.conn_reuse_mode = 0
net.ipv4.vs.conntrack = 1
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: on-premise
- OS (e.g: `cat /etc/os-release`): Debian 9
- Kernel (e.g. `uname -a`): 4.9.0-8-amd64
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by lbernail**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Disable graceful termination for non-TCP flows. The rational behind this is that with a high number of UDP connections (DNS or syslog for instance), stale UDP connections (to terminated/terminating backends) will be reused and fail (and if the load is high enough never expire).

This patch disables graceful termination for UDP. It is not perfect, but I believe it is much better. What happens is the following:
- UDP target pod becomes NotReady
- IP is removed from RealServers immediately
- Because of expire_nodest_conn any new packet reusing the port will generate a write error and the connection will be removed from the ipvs connection table (if the application retries it will be routed to an active pod)

**Which issue(s) this PR fixes**:
Fixes #76664

**Special notes for your reviewer**:
I think in addition to that we should set much more aggressive UDP timeouts (5s? instead of the default: 300s) and make it configurable with a flag for specific use-case (I haven't seen a use case for long lived udp "connections" with very low amount of traffic).

I'm not a big fan of `strings.ToLower(string(v1.ProtocolTCP))`. Any thoughts on this?

**Does this PR introduce a user-facing change?**:
```release-note
IPVS: Disable graceful termination for UDP traffic to solve issues with high number of UDP connections (DNS / syslog in particular)
```

/assign @m1093782566 
/sig network
/area IPVS

### CODE REVIEW

**Comment by m1093782566** [comment]
LGTM overall.

cc @andrewsykim for review.

File: pkg/proxy/ipvs/graceful_termination.go [hunk 1]
```diff
@@ -164,10 +166,10 @@ func (m *GracefulTerminationManager) deleteRsFunc(rsToDelete *listItem) (bool, e
...
 	for _, rs := range rss {
 		if rsToDelete.RealServer.Equal(rs) {
-			// Delete RS with no connections
-			// For UDP, ActiveConn is always 0
-			// For TCP, InactiveConn are connections not in ESTABLISHED state
-			if rs.ActiveConn+rs.InactiveConn != 0 {
+			// Delete TCP RS with no connections
+			// For other protocols, don't perform graceful termination
+			//   (existing connections will be deleted because sysctlExpireNoDestConn=1)
+			if rsToDelete.VirtualServer.Protocol == strings.ToLower(string(v1.ProtocolTCP)) && rs.ActiveConn+rs.InactiveConn != 0 {
```
Comment (andrewsykim) [inline pkg/proxy/ipvs/graceful_termination.go]: re: `strings.ToLower(string(v1.ProtocolTCP))`, v1.ProtocolTCP is mainly a type used by the Service API and is only applicable when comparing values in that resource. For comparing protocols from `VirtualServer`, we can probably use a separate constant for this.

Comment (andrewsykim) [reply pkg/proxy/ipvs/graceful_termination.go]: I personally think just `rsToDelete.VirtualServer.Protocol == "tcp"` is also fine, having a constant may not be necessary either :)

Comment (lbernail) [reply pkg/proxy/ipvs/graceful_termination.go]: I completely agree
I just changed it to "tcp"

File: pkg/proxy/ipvs/graceful_termination.go [hunk 2]
```diff
@@ -164,10 +164,10 @@ func (m *GracefulTerminationManager) deleteRsFunc(rsToDelete *listItem) (bool, e
 	}
 	for _, rs := range rss {
 		if rsToDelete.RealServer.Equal(rs) {
-			// Delete RS with no connections
-			// For UDP, ActiveConn is always 0
-			// For TCP, InactiveConn are connections not in ESTABLISHED state
-			if rs.ActiveConn+rs.InactiveConn != 0 {
+			// Delete TCP RS with no connections
+			// For other protocols, don't perform graceful termination
```
Comment (andrewsykim) [inline pkg/proxy/ipvs/graceful_termination.go]: Does this also apply for SCTP?

Comment (lbernail) [reply pkg/proxy/ipvs/graceful_termination.go]: I'm not familiar with SCTP so I chose to enable graceful termination for TCP only

I had a quick look at the protocol and it seems to include a handshake and a shutdown which should make connection tracking similar to TCP (so when a backend stops, the equivalent of a FIN is sent and the connection should be removed from the IPVS conntrack).

If you have a simple test scenario in mind I can look into it (the change is very simple we can simply do `rsToDelete.VirtualServer.Protocol != "udp"` instead)

Comment (andrewsykim) [reply pkg/proxy/ipvs/graceful_termination.go]: I'm not super familiar with it either, was more asking in case you knew :P. I think handling this on case-by-case basis makes sense. We can revisit if it's a problem for SCTP. Going to give another pass at this PR some time tomorrow :)

Comment (andrewsykim) [reply pkg/proxy/ipvs/graceful_termination.go]: I put more thought into this, and I _think_ to be safe, we should only follow this scenarios for protocols we know for sure run into issue (UDP). So `rsToDelete.VirtualServer.Protocol != "udp"` like you mentioned. Otherwise this could have unintended outcomes for sctp that we aren't aware of.

Comment (andrewsykim) [reply pkg/proxy/ipvs/graceful_termination.go]: i.e. don't change the behavior for sctp unless we have a good reason.

**Comment by bowei** [comment]
Is there a way to add a test?

**Comment by andrewsykim** [comment]
@bowei added some initial unit tests for graceful termination here https://github.com/kubernetes/kubernetes/pull/78088 :)

**Comment by jsravn** [comment]
Are you sure about `expire_nodest_conn`?  I thought because we set `conn_reuse_mode=0`, that flag has no effect - it is effectively 0.

File: pkg/proxy/ipvs/graceful_termination.go (hunk 2 above)
Comment (lbernail) [reply pkg/proxy/ipvs/graceful_termination.go]: Let's do that. Not sure how to test it but I'm pretty sure SCTP will have real connection tracking

**Comment by lbernail** [comment]
> Are you sure about `expire_nodest_conn`? I thought because we set `conn_reuse_mode=0`, that flag has no effect - it is effectively 0.

Yes, I thought that too, but it turns out the doc is either wrong or incomplete. I tested it and it works

**Comment by m1093782566** [comment]
/lgtm

Please squash the commits @lbernail

**Comment by lbernail** [comment]
> Please squash the commits @lbernail

Done
