### PR TITLE
Fix an accuracy issue of `scheduler_pending_pods` metric

### LINKED ISSUE #113945: Inaccurate metric scheduler_pending_pods{queue=gated|unschedulable}
### What happened?

With new alpha feature `PodSchedulingReadiness` enabled, the metric `scheduler_pending_pods{queue=gated|unschedulable}` becomes inaccurate.

### Case 1

- Create a Pod carrying a schedulingGate `foo`. The metrics look good:
```
scheduler_pending_pods{queue="gated"} 1
scheduler_pending_pods{queue="unschedulable"} 0
```
- Update the Pod by removing its schedulingGate `foo`. The metrics turn out to be:
```
scheduler_pending_pods{queue="gated"} 1
scheduler_pending_pods{queue="unschedulable"} -1
```

### Case 2

- Create a Pod carrying a schedulingGate `foo`, while also requesting excessive resource (e.g., 1000 cpus) . The metrics look good:
```
scheduler_pending_pods{queue="gated"} 1
scheduler_pending_pods{queue="unschedulable"} 0
```
- Update the Pod by removing its schedulingGate `foo`. The metrics turn out to be:
```
scheduler_pending_pods{queue="gated"} 1
scheduler_pending_pods{queue="unschedulable"} 0
```

### Case 3

- Create a Pod carrying a schedulingGate `foo`. The metrics look good:
```
scheduler_pending_pods{queue="gated"} 1
scheduler_pending_pods{queue="unschedulable"} 0
```
- Delete the Pod. The metrics turn out to be:
```
scheduler_pending_pods{queue="gated"} 1
scheduler_pending_pods{queue="unschedulable"} -1
```

### What did you expect to happen?

- in case1, the last step of metrics are expected to be:
```
scheduler_pending_pods{queue="gated"} 0
scheduler_pending_pods{queue="unschedulable"} 0
```
- in case 2, the metrics are expected to be:
```
scheduler_pending_pods{queue="gated"} 0
scheduler_pending_pods{queue="unschedulable"} 1
```
- in case 3, the metrics are expected to be:
```
scheduler_pending_pods{queue="gated"} 0
scheduler_pending_pods{queue="unschedulable"} 0
```

### How can we reproduce it (as minimally and precisely as possible)?

Described in `What happened?` section.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
v1.26.0-rc.0 or master (96fd7b1b50362858a621c03a16e21b71f64cfcbf)
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind bug
/sig scheduling

#### What this PR does / why we need it:

The metric `scheduler_pending_pods` becomes accurate if alpha feature `PodSchedulingReadiness` is enabled.

#### Which issue(s) this PR fixes:

Fixes #113945

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/3521-pod-scheduling-readiness
```

### CODE REVIEW

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 1]
```diff
@@ -888,20 +892,34 @@ func (u *UnschedulablePods) addOrUpdate(pInfo *framework.QueuedPodInfo) {
...
-		} else if !pInfo.Gated && u.unschedulableRecorder != nil {
+		} else if !gated && u.unschedulableRecorder != nil {
+			u.unschedulableRecorder.Dec()
+		}
+	}
+	delete(u.podInfoMap, podID)
+}
+
+// deletePod deletes a pod from the unschedulable podInfoMap.
+func (u *UnschedulablePods) deletePod(pod *v1.Pod) {
```
Comment (ahg-g) [inline pkg/scheduler/internal/queue/scheduling_queue.go:910]: why not just use this function everywhere? why do we need the other one?

Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go:910]: Because addToActiveQ() modifies the pInfo.gated in place, we need to pass the `gated` value in some cases like:

```go
	gated := pInfo.Gated
	if added, _ := p.addToActiveQ(pInfo); !added {
		return false
	}
	p.unschedulablePods.delete(pInfo, gated)
```

Comment (ahg-g) [reply pkg/scheduler/internal/queue/scheduling_queue.go:910]: Tracking the metric on each addition/deletion is concerning because it is easy to get wrong; ideally we should update the count (like ```metric.Set(len(podInfoMap))```); however, we don't have a separate map for the gated pods, so we are stuck with this approach for now I guess :(

But I still prefer to not have two functions, I made a suggestion how we can potentially do that.

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 2]
```diff
@@ -663,7 +666,7 @@ func (p *PriorityQueue) Delete(pod *v1.Pod) error {
 	if err := p.activeQ.Delete(pInfo); err != nil {
 		// The item was probably not found in the activeQ.
 		p.podBackoffQ.Delete(pInfo)
-		p.unschedulablePods.delete(pInfo)
+		p.unschedulablePods.deletePod(pod)
```
Comment (ahg-g) [inline pkg/scheduler/internal/queue/scheduling_queue.go:669]:
```
pInfo = p.unschedulablePods.get(pod)
p.unschedulablePods.delete(pod, pInfo != nil && pInfo.Gated)
```

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 3]
```diff
@@ -888,20 +892,34 @@ func (u *UnschedulablePods) addOrUpdate(pInfo *framework.QueuedPodInfo) {
 	u.podInfoMap[podID] = pInfo
 }
 
-// Delete deletes a pod from the unschedulable podInfoMap.
-func (u *UnschedulablePods) delete(pInfo *framework.QueuedPodInfo) {
+// delete deletes a podInfo from the unschedulable podInfoMap.
+// The `gated` parameter is used to figure out which metric should be decreased.
+func (u *UnschedulablePods) delete(pInfo *framework.QueuedPodInfo, gated bool) {
```
Comment (ahg-g) [inline pkg/scheduler/internal/queue/scheduling_queue.go:897]: since we are not using anything from pInfo, lets only pass the pod instead

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 1 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go:910]: > however, we don't have a separate map for the gated pods, so we are stuck with this approach for now I guess :(

indeed, an ideal way is just like you said, count the internal queue size and use it as the source of truth, call `metric.Set()` by the end of each operation to sync the metrics.

This will involve some non-trivial changes, but worth a follow-up.

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 3 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go:897]: done.

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 2 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go]: done. (tweaked a bit)

**Comment by ahg-g** [comment]
looks good, please squash.

**Comment by Huang-Wei** [comment]
> looks good, please squash.

@ahg-g squshed. PTAL.
