### PR TITLE
Fix queue hint for inter-pod anti-affinity

### LINKED ISSUE #134393: PodAffinity's QHint misses the scenario with existing pods' anti-affinity
### What happened?

/sig scheduling

The inter-pod affinity plugin is filtering out the nodes that have running pods with pod-anti-affinity that hates the pod being scheduled.
https://github.com/kubernetes/kubernetes/blob/849a82b727b1cc1e77b58149b3cacbfa5ada30fd/pkg/scheduler/framework/plugins/interpodaffinity/filtering.go#L427-L429

However PodAffinity's QHint only checks if a pending pod's anti-affinity hates a deleted pod, and doesn't check if a deleted pod's anti-affinity hates a pending pod.
https://github.com/kubernetes/kubernetes/blob/849a82b727b1cc1e77b58149b3cacbfa5ada30fd/pkg/scheduler/framework/plugins/interpodaffinity/plugin.go#L202-L207 

It causes the inter-pod affinity plugin to miss the pod/delete events that could make pending pods schedulable.

### What did you expect to happen?

PodAffinity's QHint checks _both_ if a pending pod's anti-affinity hates a deleted pod _and_ if a deleted pod's anti-affinity hates a pending pod.

### How can we reproduce it (as minimally and precisely as possible)?

.

### Kubernetes version

<details>

upstream

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by brejman**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

An existing pod with anti-affinity might prevent another pod from scheduling.
In case such pod is deleted, the pending pod should be requeued because the two pods no longer repel each other.

The reverse case is already handled, i.e. pending pod anti-affinity matches existing pod and that pod is deleted.

If the queue hint incorrectly skips the queue for some pod, the pod will eventually get queued anyway, but this can incur unnecessary delays.

#### Which issue(s) this PR is related to:

Fixes #134393

#### Does this PR introduce a user-facing change?

```release-note
Fixed queue hint for inter-pod anti-affinity in case deleted pod's anti-affinity matched the pending pod, which might have caused delays in scheduling.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/framework/plugins/interpodaffinity/plugin_test.go [hunk 1]
```diff
@@ -129,6 +129,12 @@ func Test_isSchedulableAfterPodChange(t *testing.T) {
 			oldPod:       st.MakePod().Node("fake-node").Label("service", "securityscan").Obj(),
 			expectedHint: fwk.Queue,
 		},
+		{
+			name:         "delete a pod with anti-affinity that matches scheduled pod",
```
Comment (macsko) [inline pkg/scheduler/framework/plugins/interpodaffinity/plugin_test.go]: Add a test for  "delete a pod with anti-affinity that doesn't match scheduled pod"

File: pkg/scheduler/framework/plugins/interpodaffinity/plugin.go
Comment (macsko) [inline pkg/scheduler/framework/plugins/interpodaffinity/plugin.go:176]: I see another gap in this func. Here, we check whether the pod had NodeName, but we should also check NominatedNodeName.

cc @sanposhiho

Comment (macsko) [reply pkg/scheduler/framework/plugins/interpodaffinity/plugin.go:176]: We do that in other plugins (e.g. NodeResourcesFit). Worth checking whether we missed similar thing in any other place

Comment (macsko) [reply pkg/scheduler/framework/plugins/interpodaffinity/plugin.go:176]: Potentially `isSchedulableAfterPodScaleDown` also needs to be fixed

**Review by macsko — COMMENTED** [review]
Nice work!

File: pkg/scheduler/framework/plugins/interpodaffinity/plugin_test.go (hunk 1 above)
Comment (brejman) [reply pkg/scheduler/framework/plugins/interpodaffinity/plugin_test.go]: Done

File: pkg/scheduler/framework/plugins/interpodaffinity/plugin.go [hunk 2]
```diff
@@ -220,15 +220,27 @@ func (pl *InterPodAffinity) isSchedulableAfterPodChange(logger klog.Logger, pod
 		return fwk.QueueSkip, nil
 	}
 
-	// Pod is deleted. Return Queue when the deleted pod matching the target pod's anti-affinity.
-	if !podMatchesAllAffinityTerms(antiTerms, originalPod) {
-		logger.V(5).Info("a scheduled pod was deleted but it doesn't match the target pod's anti-affinity",
-			"pod", klog.KObj(pod), "modifiedPod", klog.KObj(modifiedPod))
-		return fwk.QueueSkip, nil
+	// Pod is deleted. Return Queue when the deleted pod matching the target pod's anti-affinity or vice versa.
```
Comment (ania-borowiec) [inline pkg/scheduler/framework/plugins/interpodaffinity/plugin.go]:
```suggestion
	// Pod is deleted. Return Queue when the deleted pod matches the target pod's anti-affinity or vice versa.
```

File: pkg/scheduler/framework/plugins/interpodaffinity/plugin.go [hunk 3]
```diff
@@ -220,15 +220,27 @@ func (pl *InterPodAffinity) isSchedulableAfterPodChange(logger klog.Logger, pod
...
+			"pod", klog.KObj(pod), "originalPod", klog.KObj(originalPod))
+		return fwk.Queue, nil
+	}
+
+	originalPodAntiTerms, err := fwk.GetAffinityTerms(originalPod, fwk.GetPodAntiAffinityTerms(originalPod.Spec.Affinity))
+	if err != nil {
+		return fwk.Queue, err
+	}
+	if podMatchesAllAffinityTerms(originalPodAntiTerms, pod) {
+		logger.V(5).Info("a scheduled pod was deleted and the target pod matched the scheduled pod's anti-affinity. The pod may be schedulable now",
```
Comment (ania-borowiec) [inline pkg/scheduler/framework/plugins/interpodaffinity/plugin.go]:
```suggestion
		logger.V(5).Info("a scheduled pod was deleted and the target pod matches the deleted pod's anti-affinity. The pod may be schedulable now",
```

File: pkg/scheduler/framework/plugins/interpodaffinity/plugin.go [hunk 4]
```diff
@@ -220,15 +220,27 @@ func (pl *InterPodAffinity) isSchedulableAfterPodChange(logger klog.Logger, pod
...
+			"pod", klog.KObj(pod), "originalPod", klog.KObj(originalPod))
+		return fwk.Queue, nil
 	}
-	logger.V(5).Info("a scheduled pod was deleted and it matches the target pod's anti-affinity. The pod may be schedulable now",
-		"pod", klog.KObj(pod), "modifiedPod", klog.KObj(modifiedPod))
-	return fwk.Queue, nil
+
+	logger.V(5).Info("a scheduled pod was deleted but it doesn't match the target pod's anti-affinity",
```
Comment (ania-borowiec) [inline pkg/scheduler/framework/plugins/interpodaffinity/plugin.go]:
```suggestion
	logger.V(5).Info("a scheduled pod was deleted but it doesn't match the target pod's anti-affinity, nor vice versa",
```

File: pkg/scheduler/framework/plugins/interpodaffinity/plugin_test.go [hunk 5]
```diff
@@ -129,6 +129,18 @@ func Test_isSchedulableAfterPodChange(t *testing.T) {
...
 			expectedHint: fwk.Queue,
 		},
+		{
+			name:         "delete a pod with anti-affinity that matches pending pod",
+			pod:          st.MakePod().Name("p").Label("service", "securityscan").Obj(),
+			oldPod:       st.MakePod().Node("fake-node").PodAntiAffinityIn("service", "region", []string{"securityscan", "value2"}, st.PodAntiAffinityWithRequiredReq).Obj(),
+			expectedHint: fwk.Queue,
+		},
+		{
+			name:         "delete a pod with anti-affinity that doesn't match pending pod",
```
Comment (ania-borowiec) [inline pkg/scheduler/framework/plugins/interpodaffinity/plugin_test.go:139]: Can you please add one more case:
delete a pod which doesn't match pending pod's anti-affinity, and has anti-affinity that doesn't match pending pod

File: test/integration/scheduler/queueing/queue.go [hunk 6]
```diff
@@ -682,6 +682,54 @@ var CoreResourceEnqueueTestCases = []*CoreResourceEnqueueTestCase{
...
+		Name:          "Pod rejected by the InterPodAffinity plugin is requeued when deleting the existing pod that matches the target podAntiAffinity",
+		EnablePlugins: []string{names.InterPodAffinity},
+		InitialNodes:  []*v1.Node{st.MakeNode().Name("fake-node").Label("node", "fake-node").Obj()},
+		InitialPods: []*v1.Pod{
+			st.MakePod().Name("pod1").Label("anti1", "anti1").Container("image").Node("fake-node").Obj(),
+			st.MakePod().Name("pod2").Label("anti2", "anti2").Container("image").Node("fake-node").Obj(),
+		},
+		Pods: []*v1.Pod{
+			// - Pod3 and pod4 will be rejected by the PodAffinity plugin.
+			st.MakePod().Name("pod3").Label("anti1", "anti1").PodAntiAffinityExists("anti1", "node", st.PodAntiAffinityWithRequiredReq).Container("image").Obj(),
```
Comment (ania-borowiec) [inline test/integration/scheduler/queueing/queue.go:695]: The unit test uses PodAntiAffinityIn() and the integration test uses PodAntiAffinityExists(). Why is that? Is there any difference between these methods?

**Review by ania-borowiec — COMMENTED** [review]
Looks good, thanks!

File: test/integration/scheduler/queueing/queue.go (hunk 6 above)
Comment (brejman) [reply test/integration/scheduler/queueing/queue.go:695]: I used the setup of one of the other test cases to create this, so it's accidental and just follows the existing patterns.

Technically, for these particular test cases the specific selector isn't relevant as long as it does what it's supposed to do.

`Exists` only checks the label key, so it results in less setup code and may be easier to read.

Let me know if you'd prefer the selectors were consistent for these test cases.

File: pkg/scheduler/framework/plugins/interpodaffinity/plugin_test.go (hunk 5 above)
Comment (brejman) [reply pkg/scheduler/framework/plugins/interpodaffinity/plugin_test.go:139]: Done

File: test/integration/scheduler/queueing/queue.go (hunk 6 above)
Comment (ania-borowiec) [reply test/integration/scheduler/queueing/queue.go:695]: Thanks for checking that! Following existing patterns sounds good here

File: pkg/scheduler/framework/plugins/interpodaffinity/plugin.go
Comment (brejman) [reply pkg/scheduler/framework/plugins/interpodaffinity/plugin.go:176]: Addressed in a separate PR: https://github.com/kubernetes/kubernetes/pull/135392
