### PR TITLE
AWS kube-up: make the bootstrap script run every boot

### LINKED ISSUE #21150: AWS: Cannot restart master: kube-apiserver does not restart
The master does not recover after a `init 6` reboot (on AWS, though I do not think this is going to be specific to AWS).

The kube-apiserver container will not restart, because /srv/kubernetes already exists.

Docker reports:

```
c3e67dd38156c9465e462b98d399: mkdir /srv/kubernetes: file exists" statusCode=500
Feb 12 15:35:50 ip-172-20-0-9 docker[1075]: time="2016-02-12T15:35:50.170434251Z" level=error msg="Handler for POST /containers/{name:.*}/start returned error: Cannot start container 7f3d2b3f06104606170a74704d8b60c4d2788102e185378d4642dcbb0e6561ec: mkdir /srv/kubernetes: file exists"
Feb 12 15:35:50 ip-172-20-0-9 docker[1075]: time="2016-02-12T15:35:50.170773561Z" level=error msg="HTTP Error" err="Cannot start container 7f3d2b3f06104606170a74704d8b60c4d2788102e185378d4642dcbb0e6561ec: mkdir /srv/kubernetes: file exists" statusCode=500
Feb 12 15:37:06 ip-172-20-0-9 docker[1075]: time="2016-02-12T15:37:06.176202583Z" level=error msg="Handler for POST /containers/{name:.*}/start returned error: Cannot start container 886d815d0a97f0472ae11af1758d769c3e935a00caed1732d2661bafa538d2f8: mkdir /srv/kubernetes: file exists"
Feb 12 15:37:06 ip-172-20-0-9 docker[1075]: time="2016-02-12T15:37:06.176531406Z" level=error msg="HTTP Error" err="Cannot start container 886d815d0a97f0472ae11af1758d769c3e935a00caed1732d2661bafa538d2f8: mkdir /srv/kubernetes: file exists" statusCode=500
Feb 12 15:37:08 ip-172-20-0-9 docker[1075]: time="2016-02-12T15:37:08.167611209Z" level=error msg="Handler for POST /containers/{name:.*}/start returned error: Cannot start container 90a472aee1c49b1a1af3ef8c11ed0d957084fbc7a1c736fc9c8c3421a133ce8d: mkdir /srv/kubernetes: file exists"
Feb 12 15:37:08 ip-172-20-0-9 docker[1075]: time="2016-02-12T15:37:08.167960167Z" level=error msg="HTTP Error" err="Cannot start container 90a472aee1c49b1a1af3ef8c11ed0d957084fbc7a1c736fc9c8c3421a133ce8d: mkdir /srv/kubernetes: file exists" statusCode=500
```

kubelet reports:
```
Feb 12 15:34:19 ip-172-20-0-9 kubelet[697]: E0212 15:34:19.652832     697 manager.go:1873] Error running pod "kube-apiserver-ip-172-20-0-9.ec2.internal_kube-system(2b8b2367f8525bfac0d092ae46e475ae)" container "kube-apiserver": runContainer: API error (500): Cannot start container 52f9d1a0db82d02b8d4ddbda4ef3d386acbc25651a2058e2bdbce90461ba10c0: mkdir /srv/sshproxy: file exists
Feb 12 15:34:19 ip-172-20-0-9 kubelet[697]: E0212 15:34:19.653248     697 pod_workers.go:138] Error syncing pod 2b8b2367f8525bfac0d092ae46e475ae, skipping: failed to "StartContainer" for "kube-apiserver" with RunContainerError: "runContainer: API error (500): Cannot start container 52f9d1a0db82d02b8d4ddbda4ef3d386acbc25651a2058e2bdbce90461ba10c0: mkdir /srv/sshproxy: file exists\n"
Feb 12 15:34:19 ip-172-20-0-9 kubelet[697]: E0212 15:34:19.931076     697 manager.go:1873] Error running pod "kube-controller-manager-ip-172-20-0-9.ec2.internal_kube-system(d7378f1eda98a8da7d48ca8c21afa34f)" container "kube-controller-manager": runContainer: API error (500): Cannot start container fa5117bea72ce4fd9bc41509fda3b9d6a96267b215431ed52de69a79bab956fe: mkdir /srv/kubernetes: file exists
Feb 12 15:34:19 ip-172-20-0-9 kubelet[697]: E0212 15:34:19.931476     697 pod_workers.go:138] Error syncing pod d7378f1eda98a8da7d48ca8c21afa34f, skipping: failed to "StartContainer" for "kube-controller-manager" with RunContainerError: "runContainer: API error (500): Cannot start container fa5117bea72ce4fd9bc41509fda3b9d6a96267b215431ed52de69a79bab956fe: mkdir /srv/kubernetes: file exists\n"
```

This is with docker 1.8.3:

```
>  docker version
Client:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:39:44 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.3
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   f4bf5c7
 Built:        Mon Oct 12 05:39:44 UTC 2015
 OS/Arch:      linux/amd64
```

### PR DESCRIPTION
**Pull request by justinsb**
This is so we have the same behaviour as on GCE.

This also lets us change the bootstrap script or the config, which is
nice.  Instance data is immutable on AWS once it is booted.

Fix #21150

### CODE REVIEW

File: cluster/aws/templates/configure-vm-aws.sh [hunk 1]
```diff
@@ -34,7 +34,7 @@ ensure-packages() {
 }
 
 set-kube-env() {
-  local kube_env_yaml="${INSTALL_DIR}/kube_env.yaml"
+  local kube_env_yaml="/etc/kubernetes/kube_env.yaml"
```
Comment (brendandburns) [inline cluster/aws/templates/configure-vm-aws.sh]: Do we really want to hard code this?

Comment (brendandburns) [inline cluster/aws/templates/configure-vm-aws.sh]: (ok, I see below that we are just using a hard-coded directory...)

**Comment by brendandburns** [comment]
LGTM.
