### PR TITLE
fix(kubelet): convert V().Error() to V().Info() for verbosity-aware logging

### LINKED ISSUE #136027: Error-level logs incorrectly use verbosity levels
Currently, some components in Kubernetes have been migrated (or partially migrated) to [contextual logging](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/3077-contextual-logging/README.md). However, an incorrect pattern was introduced during the migration: Error-level logs are being called with verbosity methods (e.g., .V()).

The underlying package go-logr/logr, which contextual logging relies on, ignores the verbosity level when printing Error-level logs. For example, in the statement `logger.V(8).Error(nil, "Readiness probe already exists for container", "pod", klog.KObj(pod), "containerName", c.Name)`, the error log will be printed regardless of the verbosity level set.

This can lead to error log flooding, which may hinder users' ability to review normal logs for troubleshooting. More critically, according to the [Kubernetes logging policy](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md#what-method-to-use), logs should only be recorded when the information requires action from an administrator. This directly contradicts the practice of setting verbosity levels for Error logs, as administrators using the default logging level might miss these actionable errors. Therefore, these instances need to be fixed.

Using grep, I identified the following instances in the k/k repository where verbosity levels are incorrectly set for Error logs.
- [ ] /pkg/controller/garbagecollector https://github.com/kubernetes/kubernetes/pull/136040
```
./pkg/controller/garbagecollector/garbagecollector.go:363:			logger.V(5).Error(err, "error syncing item", "item", n.identity)
./pkg/controller/garbagecollector/graph_builder.go:225:		logger.V(4).Error(err, "unable to use a shared informer", "resource", resource, "kind", kind)
```
- [ ] /pkg/controller/resourcequota https://github.com/kubernetes/kubernetes/pull/136040
```
./pkg/controller/resourcequota/resource_quota_monitor.go:178:	logger.V(4).Error(err, "QuotaMonitor unable to use a shared informer", "resource", resource.String())
```
- [x] /pkg/controller/storageversionmigrator/ https://github.com/kubernetes/kubernetes/pull/136046
```
./pkg/controller/storageversionmigrator/storageversionmigrator.go:227:		logger.V(4).Error(err, "resource does not exist in our rest mapper", "gvr", gvr.String())
./pkg/controller/storageversionmigrator/storageversionmigrator.go:244:		logger.V(4).Error(errMonitor, "resource does not exist in GC", "gvr", gvr.String())
./pkg/controller/storageversionmigrator/storageversionmigrator.go:311:			logger.V(4).Error(err, "Unable to compare the resource version of the resource", "namespace", accessor.GetNamespace(), "name", accessor.GetName(), "gvr", gvr.String(), "accessorRV", accessor.GetResourceVersion(), "listResourceVersion", listResourceVersion, "error", err.Error())
./pkg/controller/storageversionmigrator/storageversionmigrator.go:361:			logger.V(4).Error(errPatch, "Failed to migrate the resource", "namespace", accessor.GetNamespace(), "name", accessor.GetName(), "gvr", gvr.String(), "reason", apierrors.ReasonForError(errPatch))
```
- [ ] ./pkg/controller/volume/ https://github.com/kubernetes/kubernetes/pull/136050
```
./pkg/controller/volume/selinuxwarning/selinux_warning_controller.go:458:			logger.V(4).Error(err, "failed to get SELinux label", "pod", klog.KObj(pod), "volume", mount)
./pkg/controller/volume/selinuxwarning/selinux_warning_controller.go:514:			logger.V(2).Error(err, "failed to get first pod for event", "pod", conflict.Pod)
```
- [ ] ./pkg/kubelet/volumemanager/  https://github.com/kubernetes/kubernetes/pull/136033
```
./pkg/kubelet/volumemanager/cache/desired_state_of_world.go:673:	logger.V(4).Error(err, "Please report this error in https://github.com/kubernetes/enhancements/issues/1710, together with full Pod yaml file")
./pkg/kubelet/volumemanager/cache/desired_state_of_world.go:688:		logger.V(4).Error(err, "failed to get CSI driver name from volume spec")
./pkg/kubelet/volumemanager/reconciler/reconstruct.go:188:		logger.V(4).Error(fetchErr, "Failed to get Node status to reconstruct device paths")
```

- [x] ./pkg/kubelet https://github.com/kubernetes/kubernetes/pull/136028
```
./pkg/kubelet/stats/helper.go:502:		logger.V(6).Error(err, "Unable to fetch pod log stats", "pod", klog.KRef(podNs, podName))
./pkg/kubelet/stats/helper.go:510:		logger.V(6).Error(err, "Unable to fetch pod etc hosts stats", "pod", klog.KRef(podNs, podName))
./pkg/kubelet/stats/cri_stats_provider.go:168:		logger.V(5).Error(err,
./pkg/kubelet/cm/devicemanager/plugin/v1beta1/client.go:107:			logger.V(2).Error(err, "Failed to close grpc connection", "resource", c.Resource())
./pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go:398:					logger.V(3).Error(err, "Failed to establish WatchResources stream, will retry")
./pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:431:			logger.V(5).Error(fmt.Errorf("failed to parse /proc/self/cgroup: %w", err), warn)
./pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:442:			logger.V(5).Error(err, warn)
./pkg/kubelet/lifecycle/handlers.go:85:			logger.V(1).Error(err, "Exec lifecycle hook for Container in Pod failed", "execCommand", handler.Exec.Command, "containerName", container.Name, "pod", klog.KObj(pod), "message", string(output))
./pkg/kubelet/lifecycle/handlers.go:93:			logger.V(1).Error(err, "HTTP lifecycle hook for Container in Pod failed", "path", handler.HTTPGet.Path, "containerName", container.Name, "pod", klog.KObj(pod))
./pkg/kubelet/lifecycle/handlers.go:101:			logger.V(1).Error(err, "Sleep lifecycle hook for Container in Pod failed", "sleepSeconds", handler.Sleep.Seconds, "containerName", container.Name, "pod", klog.KObj(pod))
./pkg/kubelet/lifecycle/handlers.go:152:		logger.V(1).Error(err, "HTTPS request to lifecycle hook got HTTP response, retrying with HTTP.", "pod", klog.KObj(pod), "host", req.URL.Host)
./pkg/kubelet/prober/prober_manager.go:197:				logger.V(8).Error(nil, "Startup probe already exists for container",
./pkg/kubelet/prober/prober_manager.go:209:				logger.V(8).Error(nil, "Readiness probe already exists for container",
./pkg/kubelet/prober/prober_manager.go:221:				logger.V(8).Error(nil, "Liveness probe already exists for container",
./pkg/kubelet/prober/prober.go:106:		logger.V(1).Error(err, "Probe errored", "probeType", probeType, "pod", klog.KObj(pod), "podUID", pod.UID, "containerName", container.Name, "probeResult", result)
./pkg/kubelet/metrics/collectors/cri_metrics.go:110:		logger.V(5).Error(err, "Descriptor not present in pre-populated list of descriptors", "name", m.Name)
./pkg/kubelet/pleg/generic.go:300:			g.logger.V(4).Error(err, "PLEG: Ignoring events for pod", "pod", klog.KRef(pod.Namespace, pod.Name))
./pkg/kubelet/allocation/allocation_manager.go:576:		logger.V(3).Error(err, "Failed to delete pod allocation", "podUID", uid)
```

### PR DESCRIPTION
**Pull request by thc1006**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This PR fixes incorrect usage of `logger.V(N).Error()` across the kubelet package. The go-logr package design causes `Error()` calls to bypass verbosity level checks entirely, meaning these logs are always printed regardless of the configured verbosity level.

This causes production log flooding and defeats the purpose of using verbosity levels.

#### Which issue(s) this PR fixes:

Fixes #136027

#### Special notes for your reviewer:

The linter check from https://github.com/kubernetes-sigs/logtools/pull/32 identified 21 instances across the kubelet package. This PR addresses all of them.

**Files modified (15 files, 21 instances):**
- `pkg/kubelet/allocation/allocation_manager.go`
- `pkg/kubelet/cm/devicemanager/plugin/v1beta1/client.go`
- `pkg/kubelet/cm/dra/plugin/dra_plugin_manager.go`
- `pkg/kubelet/images/pullmanager/metrics.go`
- `pkg/kubelet/kubelet.go`
- `pkg/kubelet/kuberuntime/kuberuntime_container_linux.go`
- `pkg/kubelet/lifecycle/handlers.go`
- `pkg/kubelet/metrics/collectors/cri_metrics.go`
- `pkg/kubelet/pleg/generic.go`
- `pkg/kubelet/prober/prober.go`
- `pkg/kubelet/prober/prober_manager.go`
- `pkg/kubelet/stats/cri_stats_provider.go`
- `pkg/kubelet/stats/helper.go`
- `pkg/kubelet/volumemanager/cache/desired_state_of_world.go`
- `pkg/kubelet/volumemanager/reconciler/reconstruct.go`

**Conversion patterns applied:**
- `V(N).Error(nil, "msg", ...)` → `V(N).Info("msg", ...)`
- `V(N).Error(err, "msg", ...)` → `V(N).Info("msg", ..., "err", err)`

#### Does this PR introduce a user-facing change?

```release-note
Fixed kubelet logging to properly respect verbosity levels. Previously, some debug/info messages using V().Error() would always be printed regardless of the configured log verbosity.
```

#### Additional documentation e.g., KEPs (Alarm Proposal Docs), usage docs, etc.:

N/A

/sig node
/area kubelet

### CODE REVIEW

**Comment by HirazawaUi** [comment]
> I don't know how SIG Node wants to split the fixes up, but IMHO all kubelet changes can be in one PR.

@pohly  I initially also intended to fix this issue by SIG. However, after examining the code, I found that some fixes need to be cherry-picked back to the version where the error was introduced, while others do not—because some have already caused actual user experience issues, whereas others do not affect users.

Therefore, I suggest that contributors split PRs based on whether they believe a cherry-pick is required (while ensuring PRs do not cross SIG boundaries).

Please refer to: https://github.com/kubernetes/kubernetes/issues/136027#issuecomment-3709976482

But you are more familiar with this domain than I am.

Do you think all fixes should be cherry-picked?

File: pkg/kubelet/images/pullmanager/metrics.go [hunk 1]
```diff
@@ -144,7 +144,7 @@ func (m *meteringRecordsAccessor) DeleteImagePulledRecord(imageRef string) error
 func (m *meteringRecordsAccessor) recordIntentsSize() {
 	intentsSize, err := m.sizeExposedPullRecordsAccessor.intentsSize()
 	if err != nil {
-		klog.V(4).ErrorS(err, "failed to read number of ImagePullIntents, can't update metric", "metricName", m.intentsSize.Name)
+		klog.V(4).InfoS("failed to read number of ImagePullIntents, can't update metric", "metricName", m.intentsSize.Name, "err", err)
```
Comment (pohly) [inline pkg/kubelet/images/pullmanager/metrics.go]: This is not a problem *yet*, but its clearer to explicitly treat this as an info log call, so 👍

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 2]
```diff
@@ -427,7 +427,7 @@ func checkSwapControllerAvailability(ctx context.Context) bool {
 		// memory.swap.max does not exist in the cgroup root, so we check /sys/fs/cgroup/<SELF>/memory.swap.max
 		cm, err := libcontainercgroups.ParseCgroupFile("/proc/self/cgroup")
 		if err != nil {
-			logger.V(5).Error(fmt.Errorf("failed to parse /proc/self/cgroup: %w", err), warn)
+			logger.V(5).Info(warn, "err", fmt.Errorf("failed to parse /proc/self/cgroup: %w", err))
```
Comment (pohly) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:430]: It's a bit odd that this wraps the error instead of using a custom message, but I can see why that is done here.

File: pkg/kubelet/kubelet.go [hunk 3]
```diff
@@ -3130,7 +3130,9 @@ func (kl *Kubelet) updateRuntimeUp() {
 	klog.V(4).InfoS("Container runtime status", "status", s)
 	klogErrorS := klog.ErrorS
 	if !kl.containerRuntimeReadyExpected {
-		klogErrorS = klog.V(4).ErrorS
+		klogErrorS = func(_ error, msg string, keysAndValues ...interface{}) {
+			klog.V(4).InfoS(msg, keysAndValues...)
+		}
```
Comment (pohly) [inline pkg/kubelet/kubelet.go]: Is it okay to ignore the error? Apparently yes, so let's replace with `logNotReady := klog.V(4).InfoS` and adapt the call sites accordingly.

That also fixes another problem with the anonymous function: stack unwinding is different when using it.

**Comment by thc1006** [comment]
@pohly

Thank you very much for your detailed review and valuable guidance.

**TL;DR:** I have addressed the feedback in the latest commit.

Regarding the `kubelet.go` change (discussion r2664594070):
- Removed the anonymous function wrapper pattern entirely
- Replaced with direct conditional branching using `klog.V(4).InfoS()` when runtime ready is not expected
- This resolves the stack unwinding issue you pointed out

I would be most grateful if you could kindly review the changes at your convenience.

**Comment by HirazawaUi** [comment]
> I would fix master by SIG and then determine during cherry-picking which individual lines really need to be updated on the target branch, while manually resolving the merge conflicts.

Alright, let me split these PRs by SIG, which, in fact, we have already done, and selectively cherry-pick parts of the PRs into the branches that introduced these issues (if we do need to cherry-pick selectively).

File: pkg/kubelet/images/pullmanager/metrics.go (hunk 1 above)
Comment (HirazawaUi) [inline pkg/kubelet/images/pullmanager/metrics.go]: These remaining log outputs that still use klog will be replaced with contextual logging in #135992. When making modifications, you should avoid conflicts with #135992.

Additionally, this PR should be merged after #135992 is merged, because follow-up fixes are still required for the part added in #135992 that introduces log levels for Error-level logs.

ref: https://github.com/kubernetes/kubernetes/pull/135992#discussion_r2661386925

**Comment by thc1006** [comment]
Thank you @HirazawaUi for the review feedback!

I've removed the changes to `pkg/kubelet/images/pullmanager/metrics.go` to avoid conflicts with #135992.

Commit: bc1f551db51

**Review by HirazawaUi — COMMENTED** [review]
/lgtm

**Comment by thc1006** [comment]
@HirazawaUi Thank you for the reminder!

I've analyzed all 13 files modified in this PR across the release branches. Here's the summary:

| Branch | Files with Bug | Notes |
|--------|---------------|-------|
| release-1.35 | 13 files | All files affected |
| release-1.34 | 13 files | All files affected |
| release-1.33 | 12 files | `dra_plugin_manager.go` not affected (V().Error was introduced in 1.34) |

I will create cherry-pick PRs for the currently maintained versions:

/cherry-pick release-1.35

**Comment by pohly** [comment]
That command doesn't work in the k/k repo. You have to use this script: https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh, docs in https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md

**Comment by ffromani** [comment]
just asking, does this work qualify for backport? do we deem this a regression AND one worth a backport?
