### PR TITLE
Fix a scheduler flaky e2e test

### LINKED ISSUE #53066: [downgrade test failure] SchedulerPredicates [Serial] validates resource limits of pods that are allowed to run [Conformance]
cc @kubernetes/sig-scheduling-test-failures 
cc @kubernetes/kubernetes-release-managers 

Seeing a failure on our downgrade test. Can someone please look at this?

https://k8s-testgrid.appspot.com/release-1.8-upgrade-skew#gke-1.8-1.7-downgrade-cluster

Example failure https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-gci-stable1-gci-stable2-downgrade-cluster/20#k8sio-schedulerpredicates-serial-validates-resource-limits-of-pods-that-are-allowed-to-run-conformance

Seeing timeouts on the downgrade test

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:222
Expected error:
    <*errors.errorString | 0xc4220f8090>: {
        s: "Error waiting for 8 pods to be running - probably a timeout: Timeout while waiting for pods with labels \"startPodsID=52f7cbb2-a2cb-11e7-b977-0a580a3c16f7\" to be running",
    }
    Error waiting for 8 pods to be running - probably a timeout: Timeout while waiting for pods with labels "startPodsID=52f7cbb2-a2cb-11e7-b977-0a580a3c16f7" to be running
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/predicates.go:208
```

### PR DESCRIPTION
**Pull request by bsalamat**
**What this PR does / why we need it**:
Makes a scheduler e2e test that verifies the resource limit predicate more robust.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #53066 

**Release note**:

```release-note
NONE
```

@kubernetes/sig-scheduling-pr-reviews

### CODE REVIEW

**Comment by bsalamat** [comment]
Please hold off reviewing this. It still needs some work.

**Comment by resouer** [comment]
@bsalamat Change looks good, I think we need to cherry pick this fix to 1.8. Please add a release note?

File: test/e2e/scheduling/predicates.go [hunk 1]
```diff
@@ -235,13 +234,32 @@ var _ = SIGDescribe("SchedulerPredicates [Serial]", func() {
...
+			framework.ExpectNodeHasLabel(cs, node.Name, "node", node.Name)
+			// Find allocatable amount of CPU.
 			allocatable, found := node.Status.Allocatable[v1.ResourceCPU]
 			Expect(found).To(Equal(true))
 			nodeToAllocatableMap[node.Name] = allocatable.MilliValue()
 			if nodeMaxAllocatable < allocatable.MilliValue() {
 				nodeMaxAllocatable = allocatable.MilliValue()
 			}
 		}
+		defer func() { // Remove added labels
```
Comment (resouer) [inline test/e2e/scheduling/predicates.go]: nits: move this comment above code.

Comment (bsalamat) [reply test/e2e/scheduling/predicates.go]: Done

**Comment by bsalamat** [comment]
@resouer Thanks for your quick review. I am not so confident that this PR addresses the problem we are seeing in #53066. I guess it does, but it is not easy for me to verify it by repeating what those downgrade tests do.

**Comment by spiffxp** [comment]
/hold
since @bsalamat asked that we not merge this yet

you can remove the hold with `/hold cancel`

@bsalamat you can also prefix your PR title with [wip] or WIP and the bot will apply a `do-not-merge/work-in-progress` label

**Comment by bsalamat** [comment]
/hold cancel

I verified that the test does what it intends to do. This PR is now ready to be merged.

**Comment by resouer** [comment]
@bsalamat I also test it in my local env and everything looks fine. Thanks!

**Comment by bsalamat** [comment]
BTW, @mml spoke to me today. He believes we should cherry pick this into 1.8 and also 1.7.

File: test/e2e/scheduling/predicates.go [hunk 2]
```diff
@@ -227,21 +226,49 @@ var _ = SIGDescribe("SchedulerPredicates [Serial]", func() {
...
 				nodeMaxAllocatable = allocatable.MilliValue()
 			}
 		}
+		// Clean up added labels after this test.
+		defer func() {
+			for nodeName := range nodeToAllocatableMap {
+				framework.RemoveLabelOffNode(cs, nodeName, "node")
+			}
+		}()
 		framework.WaitForStableCluster(cs, masterNodes)
```
Comment (k82cn) [inline test/e2e/scheduling/predicates.go]: Should we move this to the beginning of this test? I'm not sure whether some pending pod may impact the status of node.

File: test/e2e/scheduling/predicates.go [hunk 3]
```diff
@@ -227,21 +226,49 @@ var _ = SIGDescribe("SchedulerPredicates [Serial]", func() {
...
+	// 4. Create another pod with no affinity to any node that need 50% of the largest node CPU.
+	// 5. Make sure this additional pod is not scheduled.
 	It("validates resource limits of pods that are allowed to run [Conformance]", func() {
 		nodeMaxAllocatable := int64(0)
 
 		nodeToAllocatableMap := make(map[string]int64)
 		for _, node := range nodeList.Items {
+			nodeReady := false
+			for _, condition := range node.Status.Conditions {
+				if condition.Type == v1.NodeReady && condition.Status == v1.ConditionTrue {
```
Comment (k82cn) [inline test/e2e/scheduling/predicates.go]: How about the other status, e.g. network-unavailable?

Comment (kevin-wangzefeng) [reply test/e2e/scheduling/predicates.go]: IIRC, if a node is in network-unavailable, `condition.Status` will be changed into `v1.ConditionUnknonw`. The only corner case is that nodes are not immediately marked Unknown when they get unknown.

File: test/e2e/scheduling/predicates.go (hunk 2 above)
Comment (bsalamat) [reply test/e2e/scheduling/predicates.go]: Yes, I think it is better that way. Done.

File: test/e2e/scheduling/predicates.go (hunk 3 above)
Comment (bsalamat) [reply test/e2e/scheduling/predicates.go]: Generally, it should be OK for the test to fail in case nodes have issues like network error, etc. We don't expect nodes to be unhealthy in this test.

Comment (k82cn) [reply test/e2e/scheduling/predicates.go]: SGTM :).

File: test/e2e/scheduling/predicates.go [hunk 4]
```diff
@@ -254,51 +281,60 @@ var _ = SIGDescribe("SchedulerPredicates [Serial]", func() {
...
+					},
+				},
+				Affinity: &v1.Affinity{
+					NodeAffinity: &v1.NodeAffinity{
+						RequiredDuringSchedulingIgnoredDuringExecution: &v1.NodeSelector{
+							NodeSelectorTerms: []v1.NodeSelectorTerm{
+								{
+									MatchExpressions: []v1.NodeSelectorRequirement{
+										{
+											Key:      "node",
```
Comment (kevin-wangzefeng) [inline test/e2e/scheduling/predicates.go]: Nit: same as above, can be "kubernetes.io/hostname" here.

**Review by kevin-wangzefeng — COMMENTED** [review]
minor comments, thanks.

File: test/e2e/scheduling/predicates.go [hunk 5]
```diff
@@ -227,21 +226,49 @@ var _ = SIGDescribe("SchedulerPredicates [Serial]", func() {
...
+				if condition.Type == v1.NodeReady && condition.Status == v1.ConditionTrue {
+					nodeReady = true
+					break
+				}
+			}
+			if !nodeReady {
+				continue
+			}
+			// Apply node label to each node
+			framework.AddOrUpdateLabelOnNode(cs, node.Name, "node", node.Name)
```
[the remark this answers is not in the document]
Comment (bsalamat) [reply test/e2e/scheduling/predicates.go]: Good point. Done.

[the remark this answers is not in the document]
Comment (bsalamat) [reply test/e2e/scheduling/predicates.go]: oh well. Too late. It is already merged.

**Comment by resouer** [comment]
@bsalamat Oh, we also need to cherry pick this in 1.7 as discussed here: https://github.com/kubernetes/kubernetes/pull/53169#issuecomment-332996208, fired https://github.com/kubernetes/kubernetes/pull/53289 please review.

**Comment by davidopp** [comment]
Thanks for fixing this. Moving some of the e2e's to integration tests is useful, but it's important to keep some e2e's (and I think in most cases they can be fixed, with enough work), so I'm glad you fixed this!

**Comment by bsalamat** [comment]
The e2e to integration conversion that we did was mostly for priority functions, not predicates. Writing robust e2e tests for predicate functions is not hard, but some of our tests are a bit dated. We should improve them. This one was an example.

**Comment by mml** [comment]
@bsalamat, thanks for fixing this and for following up with the cherry-pick.
