### PR TITLE
fix race condition in kubelet's PodCertsManager

### LINKED ISSUE #133501: Race condition in kubelet's PodCertsManager might lead to memory leaks
### What happened?

Introduced in https://github.com/kubernetes/kubernetes/commit/4624cb9bb92186358e001be392e50e5d23b5cdd9, and only observable after enabling the `PodCertificateRequest` feature gate.

When https://github.com/kubernetes/kubernetes/blob/790393ae92e97262827d4f1fba24e8ae65bbada0/pkg/kubelet/kubelet.go#L2825 gets called, it queues PCRs for a given pod to be handled by a `podcertificate.Manager` instance.

However, if the queue keys for these PCRs get async-processed before https://github.com/kubernetes/kubernetes/blob/790393ae92e97262827d4f1fba24e8ae65bbada0/pkg/kubelet/kubelet.go#L2826 is called, the `podcertificate.Manager` will never again attempt to clear its internal state for these PCRs as kept in its `Manager.credStore` map.

### What did you expect to happen?

Kubelet's state gets cleaned for a given pod when the pod is removed.

### How can we reproduce it (as minimally and precisely as possible)?

Write a unit test that runs https://github.com/kubernetes/kubernetes/blob/790393ae92e97262827d4f1fba24e8ae65bbada0/pkg/kubelet/kubelet.go#L2822, expose the `podcertificate.Manager{}.credStore` variable, and observe what happens to the `credStore` variable when a cached PCR's state is supposed to get removed. Run a couple hundred times to make sure the race condition appears.

### Anything else we need to know?

Discussed at https://kubernetes.slack.com/archives/C05MW3382US/p1754992465556979

### Kubernetes version

<details>
1.34.0
</details>

### Cloud provider

<details>
any
</details>

### Install tools

_No response_

### Container runtime (CRI) and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by PersistentJZH**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix memory leaks  in kubelet's PodCertsManager.

#### Which issue(s) this PR is related to:
Fixes https://github.com/kubernetes/kubernetes/issues/133501

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by ArangoGutierrez — COMMENTED** [review]
/sig auth

**Comment by PersistentJZH** [comment]
/cc @sergeykanzhelev
hello, can help to review? thank you

**Comment by SergeyKanzhelev** [comment]
/assign @ahmedtd 

(the author of a linked PR that introduced this error)

File: pkg/kubelet/podcertificate/podcertificatemanager.go [hunk 1]
```diff
@@ -612,6 +612,16 @@ func (m *IssuingManager) TrackPod(ctx context.Context, pod *corev1.Pod) {
 // The pod worker will notice that the pod no longer exists and clear any
 // pending and live credentials associated with it.
 func (m *IssuingManager) ForgetPod(ctx context.Context, pod *corev1.Pod) {
+	// Immediately clean up credStore entries for this pod to prevent race conditions
+	m.lock.Lock()
+	for k := range m.credStore {
```
Comment (stlaz) [inline pkg/kubelet/podcertificate/podcertificatemanager.go:609]: this appears to be a copy-paste from the sync loop, see if you can extract it to a function

File: pkg/kubelet/podcertificate/podcertificatemanager.go [hunk 2]
```diff
@@ -612,6 +612,16 @@ func (m *IssuingManager) TrackPod(ctx context.Context, pod *corev1.Pod) {
 // The pod worker will notice that the pod no longer exists and clear any
 // pending and live credentials associated with it.
 func (m *IssuingManager) ForgetPod(ctx context.Context, pod *corev1.Pod) {
+	// Immediately clean up credStore entries for this pod to prevent race conditions
+	m.lock.Lock()
```
Comment (stlaz) [inline pkg/kubelet/podcertificate/podcertificatemanager.go:606]: In 99% of cases, a Lock() should immediately be followed by a deferred unlock. If the thread crashes anywhere through the below loop, it would cause a deadlock in all the other threads.

**Review by stlaz — CHANGES_REQUESTED** [review]

File: pkg/kubelet/podcertificate/podcertificatemanager.go (hunk 2 above)
Comment (aojea) [reply pkg/kubelet/podcertificate/podcertificatemanager.go:606]: that does not apply to golang, right?

File: pkg/kubelet/podcertificate/podcertificatemanager.go (hunk 1 above)
Comment (PersistentJZH) [reply pkg/kubelet/podcertificate/podcertificatemanager.go:609]: sure, added

File: pkg/kubelet/podcertificate/podcertificatemanager.go (hunk 2 above)
Comment (PersistentJZH) [reply pkg/kubelet/podcertificate/podcertificatemanager.go:606]: I think there is some slight risk in using m.lock.Unlock() directly here. I changed it to use defer in the new func cleanupCredStoreForPod(), which may be better ?

Comment (aojea) [reply pkg/kubelet/podcertificate/podcertificatemanager.go:606]: not argument about using defer ... I was only referring to the statement, AFAIK golang uses the runtime to handle goroutines, that are not directly related to threads, it was more a technical question since it got me thinking :)

Comment (stlaz) [reply pkg/kubelet/podcertificate/podcertificatemanager.go:606]: Every now and then, my old C-self comes out and makes me say things that don't directly apply to Go :slightly_smiling_face: I meant goroutines of course.

Comment (PersistentJZH) [reply pkg/kubelet/podcertificate/podcertificatemanager.go:606]: Haha, my first thought after reading this sentence was also that it refers to goroutines... 😄 Funny how whenever Golang comes up, goroutines always get accidentally called threads.

> In 99% of cases, a Lock() should immediately be followed by a deferred unlock. If the thread crashes anywhere through the below loop, it would cause a deadlock in all the other threads.

File: pkg/kubelet/podcertificate/podcertificatemanager.go [hunk 3]
```diff
@@ -608,11 +601,27 @@ func (m *IssuingManager) TrackPod(ctx context.Context, pod *corev1.Pod) {
...
+
 // ForgetPod queues the pod's podCertificate projected volume sources for processing.
 //
 // The pod worker will notice that the pod no longer exists and clear any
 // pending and live credentials associated with it.
 func (m *IssuingManager) ForgetPod(ctx context.Context, pod *corev1.Pod) {
+	// Immediately clean up credStore entries for this pod to prevent race conditions
+	m.cleanupCredStoreForPod(pod.Namespace, pod.Name, string(pod.UID))
+
+	// Queue projections for processing (this will be a no-op since pod is already removed from podManager)
```
Comment (stlaz) [inline pkg/kubelet/podcertificate/podcertificatemanager.go]: do we still need to enqueue projections for the pod?

File: pkg/kubelet/podcertificate/podcertificatemanager.go [hunk 4]
```diff
@@ -608,11 +601,27 @@ func (m *IssuingManager) TrackPod(ctx context.Context, pod *corev1.Pod) {
...
+	defer m.lock.Unlock()
+
+	for k := range m.credStore {
+		if k.Namespace == namespace && k.PodName == podName && k.PodUID == podUID {
+			delete(m.credStore, k)
+		}
+	}
+}
+
 // ForgetPod queues the pod's podCertificate projected volume sources for processing.
```
Comment (stlaz) [inline pkg/kubelet/podcertificate/podcertificatemanager.go]: We may want to update the doc for the function, too

File: pkg/kubelet/podcertificate/podcertificatemanager.go (hunk 3 above)
Comment (PersistentJZH) [reply pkg/kubelet/podcertificate/podcertificatemanager.go]: no, func queueAllProjectionsForPod() will handle this situation (it will return directly), so it is best to delete enqueue it here?

File: pkg/kubelet/podcertificate/podcertificatemanager.go (hunk 2 above)
Comment (aojea) [reply pkg/kubelet/podcertificate/podcertificatemanager.go:606]: :) nice conversation folks, sorry for polluting the thread

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve
