### PR TITLE
Disable the kubelet part of metrics collection in kubemark

### LINKED ISSUE #45038: Flag --gather-metrics-at-teardown isn't working for kubemark
We recently tried to enable e2e metrics gathering for our 100-node kubemark test (https://github.com/kubernetes/test-infra/pull/2587), but seems like it's not working (ref: http://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-100-gce/2464/artifacts/):
```
I0427 06:40:05.651] [1mSTEP[0m: Gathering metrics
I0427 06:40:05.651] W0427 06:40:05.558134    9446 metrics_grabber.go:74] Master node is not registered. Grabbing metrics from Scheduler and ControllerManager is disabled.
I0427 06:40:15.953] Apr 27 06:40:15.952: INFO: MetricsGrabber failed grab metrics. Skipping metrics gathering.
```

The reason could be due to using the wrong client, viz. talking with real master instead of kubemark master, but need to verify it.

cc @wojtek-t @gmarek

### PR DESCRIPTION
**Pull request by shyamjvs**
Fixes https://github.com/kubernetes/kubernetes/issues/45038

This should fix it, as we are just interested in getting the apiserver metrics from kubemark master.

cc @wojtek-t @gmarek

### CODE REVIEW

File: test/e2e/framework/framework.go [hunk 1]
```diff
@@ -325,7 +325,8 @@ func (f *Framework) AfterEach() {
 	if TestContext.GatherMetricsAfterTest {
 		By("Gathering metrics")
 		// TODO: enable Scheduler and ControllerManager metrics grabbing when Master's Kubelet will be registered.
-		grabber, err := metrics.NewMetricsGrabber(f.ClientSet, true, false, false, true)
+		collectKubeletMetrics := ! ProviderIs("kubemark")
+		grabber, err := metrics.NewMetricsGrabber(f.ClientSet, collectKubeletMetrics, false, false, true)
```
Comment (gmarek) [inline test/e2e/framework/framework.go]: why not inline !ProviderIs("kubemark") ?

Comment (shyamjvs) [inline test/e2e/framework/framework.go]: Thought it'd be easy to understand this way. Should I change it?

Comment (gmarek) [inline test/e2e/framework/framework.go]: Yes, please.

Comment (shyamjvs) [inline test/e2e/framework/framework.go]: Done. Made it clearer in the comment.

**Comment by shyamjvs** [comment]
@k8s-bot unit test this
@k8s-bot kubemark e2e test this
(seems like the base cluster failed to initialize)

**Comment by shyamjvs** [comment]
@k8s-bot unit test this
