### PR TITLE
Don't return CSI driver unregistration error

### LINKED ISSUE #74075: Unregistration error while registering a CSI driver
**What happened**:

We currently unregister the CSI driver if an error happens while registering it. Then, if another error happens, we return only the unregistration error.

The problem is that the user will only see the unregistration error if they check the registrar logs. This gives the  impression that it never tried to register the driver.

**What you expected to happen**:

The user should see the registration error instead.

**How to reproduce it (as minimally and precisely as possible)**:

* Try to install a CSI driver in a cluster where _CSINodeInfo_ and/or _CSIDriver_ CRDs are not created.
* Check registrar logs

/kind bug
/sig storage

CC @vladimirvivien, @msau42, @jsafrane

### PR DESCRIPTION
**Pull request by bertinatto**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR prevents the Kubelet from returning a CSI unregistration error if it happened during the registration phase.

This is what the user sees in the registrar logs when trying to install a CSI driver. This error happened because no `CSINodeInfo` and `CSIDriver` CRDs were created beforehand:

```
I0214 12:59:42.025030       1 main.go:111] Received GetInfo call: &InfoRequest{}
I0214 12:59:42.954549       1 main.go:121] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:false,Error:plugin registration failed with err: error uninstalling CSI driver from CSINodeInfo object error updating CSINodeInfo: timed out waiting for the condition; caused by: the server could not find the requested resource (get csinodeinfos.csi.storage.k8s.io ip-172-18-6-39.ec2.internal),}
E0214 12:59:42.954638       1 main.go:123] Registration process failed with error: plugin registration failed with err: error uninstalling CSI driver from CSINodeInfo object error updating CSINodeInfo: timed out waiting for the condition; caused by: the server could not find the requested resource (get csinodeinfos.csi.storage.k8s.io ip-172-18-6-39.ec2.internal), restarting registration container.
```

Note that the message states the error happened when **uninstalling** the driver.

After applying this PR:

```
I0214 12:36:29.014606       1 node_register.go:86] Starting Registration Server at: /registration/ebs.csi.aws.com-reg.sock
I0214 12:36:29.014772       1 node_register.go:93] Registration Server started at: /registration/ebs.csi.aws.com-reg.sock
I0214 12:36:29.344794       1 main.go:111] Received GetInfo call: &InfoRequest{}
I0214 12:36:30.616599       1 main.go:121] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:false,Error:plugin registration failed with err: error updating CSINodeInfo object with CSI driver node info: error updating CSINodeInfo: timed out waiting for the condition; caused by: the server could not find the requested resource (post csinodeinfos.csi.storage.k8s.io),}
E0214 12:36:30.616694       1 main.go:123] Registration process failed with error: plugin registration failed with err: error updating CSINodeInfo object with CSI driver node info: error updating CSINodeInfo: timed out waiting for the condition; caused by: the server could not find the requested resource (post csinodeinfos.csi.storage.k8s.io), restarting registration container.
```

The unregistration error can still be seen in the logs.

**Which issue(s) this PR fixes**:

Fixes #74075

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/sig storage
/assign @vladimirvivien
CC @jsafrane, @msau42

### CODE REVIEW

File: pkg/volume/csi/csi_plugin.go [hunk 1]
```diff
@@ -150,7 +150,6 @@ func (h *RegistrationHandler) RegisterPlugin(pluginName string, endpoint string,
 		klog.Error(log("registrationHandler.RegisterPlugin failed at CSI.NodeGetInfo: %v", err))
```
Comment (msau42) [inline pkg/volume/csi/csi_plugin.go]: Can we also remove this log statement?  I don't think we need to log an error that's going to get logged later in the stack.

Comment (bertinatto) [reply pkg/volume/csi/csi_plugin.go]: Done.

Comment (msau42) [reply pkg/volume/csi/csi_plugin.go]: sorry I meant remove the log of registerplugin err that we are returning

Comment (bertinatto) [reply pkg/volume/csi/csi_plugin.go]: Done. But note that this practice (log & return the err) is widely used in this package. I might clean this out in another PR if it's desirable.

Comment (msau42) [reply pkg/volume/csi/csi_plugin.go]: Thanks! Yes, I think we should clean up the rest of the package
