### PR TITLE
Pluginwatcher: Fix panic on failed startup

### LINKED ISSUE #70810: Serial suite is timing out
**Which jobs are failing**:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-serial

**Which test(s) are failing**:
should unmount if pod is force deleted while kubelet is down [Disruptive][Slow]

**Since when has it been failing**:
11/07/18 15:02

**Testgrid link**:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-serial

**Reason for failure**:
The test case stops and starts kubelet, and it seems like kubelet is unable to start again

**Anything else we need to know**:

/kind failing-test

### PR DESCRIPTION
**Pull request by RenaudWasTaken**
**What type of PR is this?**
/kind bug
@kubernetes/sig-node-bugs @kubernetes/sig-storage-bugs

**What this PR does / why we need it**: 
**Which issue(s) this PR fixes** : Fixes https://github.com/kubernetes/kubernetes/issues/70810

**Special notes for your reviewer**:
Implementation is as discussed in the issue.
cc @msau42 @yujuhong @saad-ali @figo 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 1]
```diff
@@ -178,7 +178,8 @@ func (w *Watcher) init() error {
 func (w *Watcher) traversePluginDir(dir string) error {
 	return w.fs.Walk(dir, func(path string, info os.FileInfo, err error) error {
 		if err != nil {
-			return fmt.Errorf("error accessing path: %s error: %v", path, err)
+			glog.Errorf("error accessing path: %s error: %v", path, err)
```
Comment (msau42) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Will this cause all of plugin registration to fail or will it continue to walk?  What kind of traversal ordering does this do?

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 2]
```diff
@@ -187,7 +188,9 @@ func (w *Watcher) traversePluginDir(dir string) error {
 				return fmt.Errorf("failed to watch %s, err: %v", path, err)
 			}
 		case mode&os.ModeSocket != 0:
+            w.wg.Add(1)
```
Comment (davidz627) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: since this waitgroup is waited for somewhere else, it is not clear what why we are blocking on this following gofunc and *where*. Could you add a comment for clarity

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go (hunk 1 above)
Comment (RenaudWasTaken) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: > What kind of traversal ordering does this do?

See [filepath.Walk](https://golang.org/pkg/path/filepath/#Walk): 
> The files are walked in lexical order, which makes the output deterministic but means that for very large directories Walk can be inefficient. Walk does not follow symbolic links.

> Will this cause all of plugin registration to fail or will it continue to walk?

No this will cause the traversePlugin function to ignore directories or files that can't be walked.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 3]
```diff
@@ -187,7 +188,9 @@ func (w *Watcher) traversePluginDir(dir string) error {
...
 			go func() {
+                defer w.wg.Done()
```
Comment (gnufied) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Is it me or the intendation looks out of place?

Comment (figo) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: not only you, the indent is indeed off.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go (hunk 2 above)
Comment (figo) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: @davidz627 this waitGroup is only used in `Stop()` function, i believe the only caller of this `Stop()` is `Start()` when traversePlugin failed.
no one should block on this waitGroup though, since it suppose to >0 when pluginWatcher is alive.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go (hunk 1 above)
Comment (figo) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: could we return a failure if it fail to access all dirs and files including root dir?

Comment (figo) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: we chat a little offline, i think we only need to return error when root dir access failed.

**Comment by RenaudWasTaken** [comment]
I've made it so that if the root plugin directory itself, and only the root directory, is not watchable/walkable it will prevent kubelet from starting.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go (hunk 2 above)
Comment (RenaudWasTaken) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Added a comment

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go (hunk 1 above)
Comment (RenaudWasTaken) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Fixed

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 4]
```diff
@@ -175,10 +175,17 @@ func (w *Watcher) init() error {
 }
 
 // Walks through the plugin directory discover any existing plugin sockets.
+// Goroutines started here will be waited for in Stop() before cleaning up.
+// Ignore all errors expect root dir not being walkable
```
Comment (figo) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: one minor thing, expect -> except root dir not walkable

Comment (RenaudWasTaken) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Fixed

**Comment by vladimirvivien** [comment]
@vishh  PTAL
Looking for approval so this can be merged.
