### PR TITLE
proxy/userspace: use waitgroups instead of sketchy atomic ops in testcases

### LINKED ISSUE #93904: [sig-network] TestTCPProxyUpdateDeleteUpdate flakes with "error connecting to server" error
**Which test(s) are flaking**:

TestTCPProxyUpdateDeleteUpdate

**Reason for failure**:

```
E0811 20:46:12.851363 2432471 proxysocket.go:98] Couldn't find an endpoint for testnamespace/echo:p: missing endpoints
E0811 20:46:12.851726 2432471 proxysocket.go:144] Failed to connect to balancer: missing endpoints
--- FAIL: TestTCPProxyUpdateDeleteUpdate (0.06s)
    proxier_test.go:181: error connecting to server: Get "http://127.0.0.1:42275/aaaaa": http: server closed idle connection
FAIL
```

This is flaking rarely enough that it is not caught by our CI jobs, which currently tolerate up to 2 unit test failures per run (!).

With that toleration removed in https://github.com/kubernetes/kubernetes/pull/93605, this flake has been seen (https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/93605/pull-kubernetes-bazel-test/1293275153643343872).

Reproducible with the following steps:

1. Build a test binary for the affected package:

```
go test -race -c ./pkg/proxy/userspace
```

2. Stress the affected test using the [stress](https://godoc.org/golang.org/x/tools/cmd/stress) tool:

```
stress ./userspace.test -test.run TestTCPProxyUpdateDeleteUpdate
```

5. Once failures are seen, look at the logs to see the details about the error:

```sh
ls -lat $TMPDIR/go-stress*
cat $TMPDIR/go-stress...<filename>
```

/sig network
cc @kubernetes/sig-network-test-failures

### PR DESCRIPTION
**Pull request by dcbw**
Instead of relying on atomic ops to increment/decrement at the right time
just use waitgroups to provide hard synchronization points.

Supercedes https://github.com/kubernetes/kubernetes/pull/93918

@liggitt @danwinship @kubernetes/sig-network-misc 

/kind cleanup
/kind failing-test
/kind flake

```release-note
NONE
```

Fixes https://github.com/kubernetes/kubernetes/issues/93904

### CODE REVIEW

File: pkg/proxy/userspace/proxier.go [hunk 1]
```diff
@@ -461,16 +467,20 @@ func (proxier *Proxier) addServiceOnPortInternal(service proxy.ServicePortName,
...
+	si.finished.Add(1)
 	proxier.serviceMap[service] = si
 
 	klog.V(2).Infof("Proxying for service %q on %s port %d", service, protocol, portNum)
-	go func(service proxy.ServicePortName, proxier *Proxier) {
+	go func() {
 		defer runtime.HandleCrash()
-		atomic.AddInt32(&proxier.numProxyLoops, 1)
+		defer si.finished.Done()
+		si.started.Done()
```
Comment (liggitt) [inline pkg/proxy/userspace/proxier.go:481]: what is blocking on `si.started.Wait()` intended to indicate? it doesn't mean sock.ProxyLoop() has been called yet... it means it's *about* to be called

**Comment by liggitt** [comment]
still seeing flakes with the stress test in the original issue...

```
--- FAIL: TestTCPProxyUpdateDeleteUpdate (0.01s)
    proxier_test.go:180: error connecting to server: Get "http://127.0.0.1:44739/aaaaa": EOF
```

File: pkg/proxy/userspace/proxier.go (hunk 1 above)
Comment (dcbw) [reply pkg/proxy/userspace/proxier.go:481]: @liggitt nor did waitForProxyLoop(,.., 1) mean it was started yet either... I think we just care that the goroutine is started, since sometimes that takes a while.

File: pkg/proxy/userspace/proxier.go [hunk 2]
```diff
@@ -68,6 +68,13 @@ type ServiceInfo struct {
 	stickyMaxAgeSeconds int
 	// Deprecated, but required for back-compat (including e2e)
 	externalIPs []string
+
+	// started is incremented when the service is created, and decremented
+	// when the service's socket beings accepting requests
```
Comment (danwinship) [inline pkg/proxy/userspace/proxier.go:73]: "begins"

File: pkg/proxy/userspace/proxier.go [hunk 3]
```diff
@@ -68,6 +68,13 @@ type ServiceInfo struct {
...
+	started *sync.WaitGroup
+	// finished is incremented when the service is created, and decremented
+	// when the service's socket shuts down
+	finished *sync.WaitGroup
```
Comment (danwinship) [inline pkg/proxy/userspace/proxier.go:77]: How heavyweight are WaitGroups? Given that this is only used for testing, not for ordinary functioning of the proxy.

**Review by danwinship — COMMENTED** [review]
Given that it's always `TestTCPProxyUpdateDeleteUpdate` that flakes, it seems likely that the flake must be happening in the _second_ connection attempt, since that's the part that's unique to this test.

Looking at one of the recent flakes:

```
E0811 20:10:25.430854      24 proxysocket.go:144] Failed to connect to balancer: missing endpoints
    proxier_test.go:181: error connecting to server: Get "http://127.0.0.1:39143/aaaaa": http: server closed idle connection
```

So it looks like the problem is that we need to wait for the `lb.OnEndpointsAdd(...)` to be processed, not just the `p.OnServiceAdd(...)`. (Well, also, the userspace proxy ought to not accept connections for Services with no Endpoints, but whatever.)

("server closed idle connection" is presumably a bad heuristic in `http.Client` that is just referring to the fact that the server (ie the userspace proxy) closed the connection on it as it was starting to write the request; `http.Client` is failing to consider that this happened on a brand new connection as opposed to a reused persistent connection, and so giving an incorrect error message.)

File: pkg/proxy/userspace/proxier.go (hunk 3 above)
Comment (liggitt) [reply pkg/proxy/userspace/proxier.go:77]: I had the same thought

File: pkg/proxy/userspace/proxier.go (hunk 1 above)
Comment (liggitt) [reply pkg/proxy/userspace/proxier.go:481]: > I think we just care that the goroutine is started, since sometimes that takes a while

I can't think of anything that would wait on si.started that wouldn't be flaky... the listener is already established before addServiceOnPortInternal returns, so there's no need to wait on si.started before sending requests to it... I think we should drop si.started and simplify `finished` to something like a channel we close

**Comment by knight42** [comment]
@danwinship I have investigated the flake a bit at https://github.com/kubernetes/kubernetes/pull/93918#issue-466563115, and I think the root cause is that the service was not deleted from the `LoadBalancerRR` before we added back the endpoint.

File: pkg/proxy/userspace/proxier.go (hunk 3 above)
Comment (dcbw) [reply pkg/proxy/userspace/proxier.go:77]: WaitGroup just uses atomic ops. Not significantly heavier weight IMO than the previous atomic ops stuff.

**Comment by dcbw** [comment]
> @danwinship I have investigated the flake a bit at [#93918 (comment)](https://github.com/kubernetes/kubernetes/pull/93918#issue-466563115), and I think the root cause is that the service was not deleted from the `LoadBalancerRR` before we added back the endpoint.

@knight42 is that because something is not waiting for the previous stuff to be cleaned up, before trying to re-add the new endpoint?

File: pkg/proxy/userspace/proxier.go (hunk 2 above)
Comment (dcbw) [reply pkg/proxy/userspace/proxier.go:73]: fixed

**Comment by dcbw** [comment]
> So it looks like the problem is that we need to wait for the `lb.OnEndpointsAdd(...)` to be processed, not just the `p.OnServiceAdd(...)`. (Well, also, the userspace proxy ought to not accept connections for Services with no Endpoints, but whatever.)

@danwinship Looking at it though, OnEndpointsAdd() doesn't do anything interesting. Just takes a lock and stuff some things into a map. With the waitgroups, addition and deletion of the endpoints should be a condition of the service info started/finished waitgroups too.

**Comment by dcbw** [comment]
@liggitt @danwinship how about now?

File: pkg/proxy/userspace/proxier.go (hunk 3 above)
Comment (liggitt) [reply pkg/proxy/userspace/proxier.go:77]: https://golang.org/src/sync/waitgroup.go?s=2022:2057#L43 looks a lot heavier, especially for something we are only using in a unit test

File: pkg/proxy/userspace/proxier.go [hunk 4]
```diff
@@ -509,6 +514,7 @@ func (proxier *Proxier) mergeService(service *v1.Service) sets.String {
 			if err := proxier.cleanupPortalAndProxy(serviceName, info); err != nil {
 				klog.Error(err)
 			}
+			info.finished.Done()
```
Comment (liggitt) [inline pkg/proxy/userspace/proxier.go:517]: can this be called more than once (sending `finished` negative)? if we `continue` above on line 510, do we miss calling this when we should?

File: pkg/proxy/userspace/proxier.go [hunk 5]
```diff
@@ -578,6 +586,7 @@ func (proxier *Proxier) unmergeService(service *v1.Service, existingPorts sets.S
 			klog.Error(err)
 		}
 		proxier.loadBalancer.DeleteService(serviceName)
+		info.finished.Done()
```
Comment (liggitt) [inline pkg/proxy/userspace/proxier.go:589]: similar question about being called more than once (sending the counter negative)

**Comment by liggitt** [comment]
> @liggitt @danwinship how about now?

I'm not familiar enough with the proxy sync flow to know whether these changes make sense, but I commented on a couple places that seemed weird

File: pkg/proxy/userspace/proxier.go (hunk 5 above)
Comment (dcbw) [reply pkg/proxy/userspace/proxier.go:589]: @liggitt in this case, cleanupPortalAndProxy() -> stopProxy() removes the ServiceInfo from the map and the waitgroup being called is a member of that ServiceInfo, so it cannot be called again. I thought about putting the finished closer to the map deletion, but we want to cover the loadbalancer cleanup too.

File: pkg/proxy/userspace/proxier.go (hunk 4 above)
Comment (dcbw) [reply pkg/proxy/userspace/proxier.go:517]: @liggitt I don't think 510 is an issue, because mergeService() is trying to update the proxy if the service changed. Line 510 means nothing changed so leave it as-is. If the service did change, and it's already in the map, it'll be removed (cleanupPortalAndProxy()) and then re-added with a new ServiceInfo/waitgroup by addServiceOnPortInternal()

**Comment by gianarb** [comment]
Hello!
Tomorrow is release day! Is this PR gonna make it on time? Should we move it to 1.20?
Thanks

**Comment by liggitt** [comment]
since this is addressing a long-lived test-only issue, it should be moved to 1.20

/milestone v1.20

**Comment by dcbw** [comment]
@liggitt would you mind running this latest iteration through your stress test to see if the issue is gone? Thanks!

**Comment by liggitt** [comment]
I'd like people to start building this toolset out themselves, so you should be able to run it. I put instructions for the stress test at https://github.com/kubernetes/kubernetes/issues/93904 (it's really simple to do). Let me know if you have any questions.

File: pkg/proxy/userspace/proxier.go (hunk 3 above)
Comment (liggitt) [reply pkg/proxy/userspace/proxier.go:77]: This comment is still outstanding

**Comment by dcbw** [comment]
> I'd like people to start building this toolset out themselves, so you should be able to run it. I put instructions for the stress test at #93904 (it's really simple to do). Let me know if you have any questions.

@liggitt thanks, didn't realize it was so easy :) It's gone through ~7000 iterations so far without failure, how many should I shoot for?

File: pkg/proxy/userspace/proxier.go (hunk 3 above)
Comment (dcbw) [reply pkg/proxy/userspace/proxier.go:77]: @liggitt We don't actually need waitgroup values > 1, so if you'd like though, I'm happy to move it to custom-rolled atomics and a busyloop for wait.

But I would disagree that watigroup add/done is heavy especially since there's no contention whatsoever when testcases are not running.

Comment (liggitt) [reply pkg/proxy/userspace/proxier.go:77]: for something used only by tests, I'd like the cost to be as close to zero for the production code as possible

**Comment by liggitt** [comment]
> @liggitt thanks, didn't realize it was so easy :) It's gone through ~30,000 iterations so far without failure, how many should I shoot for?

on master, it flakes immediately, so that sounds good:
```
219 runs so far, 4 failures
```

**Comment by dcbw** [comment]
@liggitt how about now? pushed a fixup that shows the change from WaitGroup to atomic ops. If that looks better I'll squash and update the commit message.

File: pkg/proxy/userspace/proxier.go (hunk 3 above)
Comment (dcbw) [reply pkg/proxy/userspace/proxier.go]: changed to use atomics for started/finished rather than waitgroups.

File: pkg/proxy/userspace/proxier.go [hunk 6]
```diff
@@ -465,12 +479,15 @@ func (proxier *Proxier) addServiceOnPortInternal(service proxy.ServicePortName,
...
+	go func() {
 		defer runtime.HandleCrash()
-		atomic.AddInt32(&proxier.numProxyLoops, 1)
+		wg.Done()
 		sock.ProxyLoop(service, si, proxier.loadBalancer)
-		atomic.AddInt32(&proxier.numProxyLoops, -1)
-	}(service, proxier)
+	}()
+	// Wait until the ProxyLoop goroutine has actually started
+	wg.Wait()
```
Comment (liggitt) [inline pkg/proxy/userspace/proxier.go:490]: I'm not sure why this is being added. Does this actually do anything other than slow down the return a little? This still can return before `sock.ProxyLoop` is called, which doesn't seem fundamentally different in nature from what it was doing before.

**Comment by liggitt** [comment]
> @liggitt how about now? pushed a fixup that shows the change from WaitGroup to atomic ops. If that looks better I'll squash and update the commit message. ~6000 stress iterations so far.

The atomic int operations look good. One comment on the remaining waitgroup in `proxier.go`.

I did not look at the test changes, I'll defer to a sig-network reviewer on whether they are correct / cover the desired functionality, but if stress is happy after O(1000) iterations, I'm happy from a CI signal perspective.

File: pkg/proxy/userspace/proxier.go (hunk 6 above)
Comment (dcbw) [reply pkg/proxy/userspace/proxier.go]: @liggitt yeah, I guess that doesn't need to be there; all we really care about is that the socket is open and the iptables rules have been added by openPortal(), so I removed that bit and squashed the fixup.

**Comment by liggitt** [comment]
thanks, if this passes the stress test now, it seems ready for a network reviewer and lgtm

**Comment by dcbw** [comment]
> thanks, if this passes the stress test now, it seems ready for a network reviewer and lgtm

@liggitt `41522 runs so far, 0 failures`

**Comment by liggitt** [comment]
@danwinship you want to do the review pass on the test updates and lgtm?

**Review by danwinship — COMMENTED** [review]
Commit message / PR title are now incorrect

File: pkg/proxy/userspace/proxier_test.go [hunk 7]
```diff
@@ -89,14 +88,60 @@ func waitForClosedPortUDP(p *Proxier, proxyPort int) error {
...
+
+	return svcInfo
+}
+
+func addServiceAndWaitForInfoIndex(t *testing.T, p *Proxier, servicePortName proxy.ServicePortName, service *v1.Service, idx int) *ServiceInfo {
+	p.OnServiceAdd(service)
+	return waitForServiceInfo(t, p, servicePortName, service, idx)
+}
+
+func addServiceAndWaitForInfo(t *testing.T, p *Proxier, servicePortName proxy.ServicePortName, service *v1.Service) *ServiceInfo {
```
[the remark this answers is not in the document]
Comment (dcbw) [reply pkg/proxy/userspace/proxier_test.go:131]: Fixed to just find the right ServicePort rather than indexes or whatever.

File: pkg/proxy/userspace/proxier_test.go [hunk 8]
```diff
@@ -267,12 +299,15 @@ func TestTCPProxy(t *testing.T) {
 	startProxier(p, t)
 	defer p.shutdown()
 
-	svcInfo, err := p.addServiceOnPort(service, "TCP", 0, time.Second)
-	if err != nil {
-		t.Fatalf("error adding new service: %#v", err)
-	}
+	svcInfo := addServiceAndWaitForInfo(t, p, service, &v1.Service{
```
[the remark this answers is not in the document]
Comment (dcbw) [reply pkg/proxy/userspace/proxier_test.go:302]: Done, in a second commit.

**Comment by dcbw** [comment]
@danwinship @liggitt PTAL thanks!
