### PR TITLE
Fix panic in attachDetachController

### LINKED ISSUE #71463: Panic in the AttachDetachController
**What happened**:
During investigation of  nil pointer dereference panic, i've found that [operationGenerator.GenerateDetachVolumeFunc](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go#L389) has an issue:

`operationGenerator.GenerateDetachVolumeFunc` don't check 1st return value of `volumePluginMgr.FindAttachablePluginByName`  to `nil`: 

```
                attachableVolumePlugin, err = og.volumePluginMgr.FindAttachablePluginByName(pluginName)
		if err != nil {
			return volumetypes.GeneratedOperations{}, volumeToDetach.GenerateErrorDetailed("DetachVolume.FindAttachablePluginBySpec failed", err)
		}
	}

	if pluginName == "" {
		pluginName = attachableVolumePlugin.GetPluginName()
	}

	volumeDetacher, err := attachableVolumePlugin.NewDetacher()
```
but [VolumePluginMgr.FindAttachablePluginByName](https://github.com/kubernetes/kubernetes/blob/fad23990cea2f883c98684fc2f2b600a3c1bdbd8/pkg/volume/plugins.go#L800) could return  `nil, nil`:

```
func (pm *VolumePluginMgr) FindAttachablePluginByName(name string) (AttachableVolumePlugin, error) {
	volumePlugin, err := pm.FindPluginByName(name)
	if err != nil {
		return nil, err
	}
	if attachablePlugin, ok := volumePlugin.(AttachableVolumePlugin); ok {
		return attachablePlugin, nil
	}
	return nil, nil
}
```

So, if `VolumePluginMgr.FindAttachablePluginByName()` finds plugin by name, but this plugin isn't a `AttachableVolumePlugin`, it will cause a nil pointer dereference panic in `volumeDetacher, err := attachableVolumePlugin.NewDetacher()`

**What you expected to happen**:
`operationGenerator.GenerateDetachVolumeFunc` should check `attachableVolumePlugin == nil`

**How to reproduce it (as minimally and precisely as possible)**:
Unfortunately, i can't reproduce it

**Anything else we need to know?**:
@liggitt advised to change `FindAttachablePluginByName` signature to `(plugin, bool, error)`

/kind bug

### PR DESCRIPTION
**Pull request by mshaverdo**
**What type of PR is this?**
 /kind bug

**What this PR does / why we need it**:
PR fixes panics in `operationGenerator.GenerateDetachVolumeFunc()` in rare case of `volumePluginMgr.FindAttachablePluginByName()` finds plugin by name, but this plugin isn't a `AttachableVolumePlugin`. See #71463 
Although it clarifies  to callers of  ` VolumePluginMgr.FindAttachablePluginByName()` what cases they are expected to handle.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #71463

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fixes possible panic during volume detach, if corresponding volume plugin became non-attachable
```

### CODE REVIEW

File: pkg/volume/plugins.go [hunk 1]
```diff
@@ -797,15 +797,18 @@ func (pm *VolumePluginMgr) FindAttachablePluginBySpec(spec *Spec) (AttachableVol
...
 	if err != nil {
-		return nil, err
+		return nil, false, err
 	}
 	if attachablePlugin, ok := volumePlugin.(AttachableVolumePlugin); ok {
-		return attachablePlugin, nil
+		return attachablePlugin, true, nil
 	}
-	return nil, nil
+	return nil, false, nil
```
Comment (gnufied) [inline pkg/volume/plugins.go]: I think we need not touch this method. Rather than relying on `false` return value from here, we should just rely on `nil` plugin check in affected code. This would keep the diff small and ensure consistency between different `FindXXXPlugin` functions.

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 2]
```diff
@@ -386,8 +392,13 @@ func (og *operationGenerator) GenerateDetachVolumeFunc(
...
 		}
-		attachableVolumePlugin, err = og.volumePluginMgr.FindAttachablePluginByName(pluginName)
-		if err != nil {
+
+		var ok bool
+		attachableVolumePlugin, ok, err = og.volumePluginMgr.FindAttachablePluginByName(pluginName)
+		if !ok {
+			if err == nil {
+				err = fmt.Errorf("plugin %s isn't a AttachableVolumePlugin", pluginName)
+			}
```
Comment (gnufied) [inline pkg/volume/util/operationexecutor/operation_generator.go]: I think it is simpler to just check for `nil`  `attachableVolumePlugin` in the code rather than introducing the boolean return.

**Comment by mshaverdo** [comment]
@gnufied @saad-ali 

> I think it is simpler to just check for nil attachableVolumePlugin in the code rather than introducing the boolean return.

Yes, it's simpler, lead to minimal diff and completely fix this bug.
But clients of `FindXXXXXXPluginBy(Name|Spec)` methods could be confused, and same bugs may  appear in future: first instinct is "if err == nil, then main return value is usable". 
I think, `return nil, nil` is counter-intuitive and leads to additional check to `plugin == nil` in case of nil-plugin is unusable, like in `operationGenerator.GenerateDetachVolumeFunc`. This approach is only useful if we have lot of cases with usable nil-plugin .

I've checked all usages of `FindXXXXXXPluginBy(Name|Spec)`:

| Method name | with unusable `nil` plugin | with usable `nil` plugin | 
|-------------------|--------------------------------|------------------------------|
| FindAttachablePluginByName | 3 | 1 |
| FindAttachablePluginBySpec | 10 | 0 |
| FindDeviceMountablePluginBySpec | 2 | 0 |
| FindDeviceMountablePluginByName | 1 | 0 |
| FindExpandablePluginBySpec | 4 | 0 |
| FindExpandablePluginByName | 0 | 0 |
| FindMapperPluginBySpec | 1 | 0 |
| FindMapperPluginByName | 2 | 0 |
| FindFSResizablePluginBySpec | 0 | 1 |
| FindFSResizablePluginByName | 0 | 0 |
|**total** | **23** | **2** |

So, current approach is useful in only **2** cases in k8s code, and leads to surplus checks and potential nill pointer dereference in **23** cases.
I think, it's better to rewrite this methods to return nil error only with usable (non-nil) plugin, and add special error check (smth like [os.IsNotExist(err error) bool](https://golang.org/pkg/os/#IsNotExist)):  it's better to use additional checks in rare cases, not in regular.

**Comment by liggitt** [comment]
if you want to pick this fix back to prior releases, doing the minimal fix first would be better.

I'd be supportive of a follow-up that changes the return values to make it clearer that there is a non-error case that does not return a usable plugin. As evidenced by the bug this is fixing, that is not always clear.

**Comment by mshaverdo** [comment]
@liggitt @gnufied @saad-ali
It seems it's better to fix this bug by one-line commit checking `attachableVolumePlugin == nil`, and rewrite `FindXXXXXXPluginBy(Name|Spec)` functions in separate PR

**Comment by mshaverdo** [comment]
@gnufied @saad-ali
I've changed PR to just fix panic, without changing signatures

**Comment by gnufied** [comment]
Can you add a release note about fixing possible panic when plugin is not found?

**Comment by mshaverdo** [comment]
@gnufied 
done

**Comment by mshaverdo** [comment]
@gnufied
Could you please help? This PR stuck in "Merging is blocked" somehow. What should i do to merge it?

**Comment by gnufied** [comment]
@mshaverdo it does not belong to 1.13 milestone, which is fine I think. A soon as master opens for general PR merges this will get merged. We will pick this for 1.13.1 and cherry-pick.

**Comment by saad-ali** [comment]
Now that this is merged. Let's get it cherry picked for 1.13.1
