### PR TITLE
Fix pod and container level swap metrics for CRI

### LINKED ISSUE #131915: Kubelet Swap metrics are missing
### What happened?

Kubelet's swap related metrics were introduced in https://github.com/kubernetes/kubernetes/pull/118865. However, these swap-related metrics are missing from `/metrics/resource` endpoint. Only node-level swap usage metrics are visible. The pod-level and container-level swap usage are available from `/stats/summary` endpoint, but no metrics are visible from `/metrics/resource`.

```
kubectl get --raw "/api/v1/nodes/<node>/proxy/metrics/resource" | grep -i swap
                    
# HELP node_swap_usage_bytes [ALPHA] Current swap usage of the node in bytes. Reported only on non-windows systems
# TYPE node_swap_usage_bytes gauge
node_swap_usage_bytes 3.4340864e+07 1747937814848

kubectl get --raw "/api/v1/nodes/<node>//proxy/stats/summary" | jq ".pods[] | select(.swap.swapUsageBytes > 0)"       

{
  "podRef": {
    "name": "oom-test-pod-stress-ng",
    "namespace": "default",
    "uid": "4bc5b67c-d750-47d4-a36a-5cec6190d752"
  },
  "containers": [
    {
      "name": "memory-eater",
      # ... omitted
      "swap": {
        "time": "2025-05-22T18:19:01Z",
        "swapAvailableBytes": 0,
        "swapUsageBytes": 33554432
      }
    }
  ],
  # omitted...
  "swap": {
    "time": "2025-05-22T18:18:50Z",
    "swapUsageBytes": 33554432
  }
}
```

### What did you expect to happen?

Container-level swap usage `container_swap_usage_bytes` and pod-level swap usage `pod_swap_usage_bytes` metrics should be available from `/metrics/resource` endpoint.

### How can we reproduce it (as minimally and precisely as possible)?

Create a node with swap enabled (https://kubernetes.io/blog/2025/03/25/swap-linux-improvements/#install-a-swap-enabled-cluster-with-kubeadm)

Get the swap metrics `kubectl get --raw "/api/v1/nodes/<node-name>/proxy/metrics/resource"

### Anything else we need to know?

The node is using ~~cadvisor~~ CRI for resource metrics.

Also happened for kind: https://github.com/kubernetes-sigs/kind/issues/3834

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.33.1
Kustomize Version: v5.6.0
Server Version: v1.33.1

$ kubelet --version
Kubernetes v1.33.1
```

</details>

### Cloud provider

<details>
GKE: v1.33.1
Node: n4-standard-4
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
GOOGLE_METRICS_PRODUCT_ID=26
KERNEL_COMMIT_ID=ce1882ff887f9f692176e3431dc39f7f79bf8c72
GOOGLE_CRASH_ID=Lakitu
VERSION=121
VERSION_ID=121
BUILD_ID=18867.90.23

$ uname -a
Linux gke-yuanwangyw-test-dev-pool-4756ad32-v354 6.6.87+ #1 SMP Sat May 10 09:40:07 UTC 2025 x86_64 INTEL(R) XEON(R) PLATINUM 8581C CPU @ 2.10GHz GenuineIntel GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>
containerd://2.0.4
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by yuanwang04**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixes the missing pod-level and container-level swap metrics from the CRI provider.

Swap metrics are introduced in https://github.com/kubernetes/kubernetes/pull/118865. For the CRI provider, the swap data is only scraped from the `listPodStatsPartiallyFromCRI` function. However, the resource metrics are scraped from the `ListPodCPUAndMemoryStats` function. This PR added the similar code changes to the `ListPodCPUAndMemoryStats` function so that the swap metrics can be reported correctly.

Also added the swap related metrics to the e2e test to assert these metrics exist.

#### Which issue(s) this PR fixes:

Fixes #131915

#### Special notes for your reviewer:
Also added the swap metrics to the e2e test suite

#### Does this PR introduce a user-facing change?

```release-note
Fixed the bug when swap related metrics were not available in `/metrics/resource` endpoint.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/stats/cri_stats_provider.go
Comment (ajaysundark) [inline pkg/kubelet/stats/cri_stats_provider.go:1]: Does it also need a `addCRIPodSwapUsage` method [here](https://github.com/kubernetes/kubernetes/pull/132065/files#diff-27608c014abc817b90c50f8bbca712d16caa731c5d12465435cde848c72c2dc9R293-R294)?

Comment (yuanwang04) [reply pkg/kubelet/stats/cri_stats_provider.go:1]: @iholder101 I don't see the Swap stats are being populated from the reference to [CRI's ListPodSandboxStats function](https://github.com/kubernetes/kubernetes/pull/132065/files/7076008e0da803a0b067f825bdbeed9fb74d5acc#diff-27608c014abc817b90c50f8bbca712d16caa731c5d12465435cde848c72c2dc9R241-R271). Do you remember if this is a limitation of the CRI that Swap related data have to be retrieved from the cadvisor / cgroup directly?

**Comment by yuanwang04** [comment]
@haircommander @kannon92 Could you help to review this PR? Thanks! I think we might also want to backport this fix to at least 1.33 so Swap can be monitored appropriately, cc @ajaysundark

File: pkg/kubelet/stats/cri_stats_provider.go [hunk 1]
```diff
@@ -771,6 +773,19 @@ func (p *criStatsProvider) makeContainerCPUAndMemoryStats(
...
+		if stats.Swap.SwapUsageBytes != nil {
+			result.Swap.SwapUsageBytes = &stats.Swap.SwapUsageBytes.Value
+		}
+		if stats.Swap.SwapAvailableBytes != nil {
+			result.Swap.SwapAvailableBytes = &stats.Swap.SwapAvailableBytes.Value
+		}
+	} else {
+		result.Swap.Time = metav1.NewTime(time.Unix(0, time.Now().UnixNano()))
+		result.Swap.SwapUsageBytes = uint64Ptr(0)
+		result.Swap.SwapAvailableBytes = uint64Ptr(0)
```
Comment (haircommander) [inline pkg/kubelet/stats/cri_stats_provider.go]: these could be set on line 747 and then updated if stats.Swap != nil, thus not requiring the else

File: pkg/kubelet/stats/cri_stats_provider.go
Comment (iholder101) [reply pkg/kubelet/stats/cri_stats_provider.go:1]: Hey there! Sorry for the late reply.

In https://github.com/kubernetes/kubernetes/pull/118865, I was adding a comment regarding that:

> Special notes for your reviewer:
>
> AFAICT, cadvisor is being used to fetch the metric data. If it is not available through cadvisor, it's possible to fallback into gathering CRI data. Unfortunately, it doesn't seem currently possible to do so ([here](https://github.com/kubernetes/kubernetes/blob/38222014c61f6c697975a50106315c131c638fe0/pkg/kubelet/stats/cri_stats_provider.go#L955)) since memory usage is not part of [the CRI-API](https://github.com/kubernetes/cri-api/blob/dbd34e39a27e1148206d9ad1d413ee3bcf001a54/pkg/apis/runtime/v1/api.pb.go#L8645). In follow-up work, I think it should be added as well, as I don't see a reason to why CRIs wouldn't be able to provide this information.

While this was true back then, a `swapUsage` struct is now [part of the CRI-API](https://github.com/kubernetes/cri-api/blob/7d025a3cd8e380d1a2512c457de8e1a4d6c2c6de/pkg/apis/runtime/v1/api.pb.go#L9778).

Therefore:

> Does it also need a addCRIPodSwapUsage method [here](https://github.com/kubernetes/kubernetes/pull/132065/files#diff-27608c014abc817b90c50f8bbca712d16caa731c5d12465435cde848c72c2dc9R293-R294)?

@ajaysundark, I think so, yes.

> Do you remember if this is a limitation of the CRI that Swap related data have to be retrieved from the cadvisor / cgroup directly?

Prior to my work, this wasn't part of the CRI-API. Now it is. I'm not aware of any further limitation.

@haircommander can you please confirm that CRIs are implementing the `swapUsage` API?

**Comment by iholder101** [comment]
> However, the resource metrics are scraped from the ListPodCPUAndMemoryStats function. This PR added the similar code changes to the ListPodCPUAndMemoryStats function so that the swap metrics can be reported correctly.

For the record, originally, I wasn't sure if swap should be considered as "CPU and memory" stats.
I wasn't aware that the `/metrics/resource/` endpoint relies solely on these.

If so, I think this is the right direction :+1: 
Thank you @yuanwang04!

**Comment by iholder101** [comment]
> @haircommander @kannon92 Could you help to review this PR? Thanks! I think we might also want to backport this fix to at least 1.33 so Swap can be monitored appropriately, cc @ajaysundark

I tend to think this should be possible, if we treat this as a bug fix.

**Review by hashim21223445 — APPROVED** [review]

File: pkg/kubelet/stats/cri_stats_provider.go
Comment (haircommander) [reply pkg/kubelet/stats/cri_stats_provider.go:1]: https://github.com/cri-o/cri-o/blob/155deb668c7b54a0bed35f2e091d4f3067c93208/internal/lib/stats/stats_server_linux.go#L328-L333 looks like CRI-O does, but to return those you'd need to turn on the CRI stats feature, so it doesn't OOTB

File: pkg/kubelet/stats/cri_stats_provider.go (hunk 1 above)
Comment (yuanwang04) [reply pkg/kubelet/stats/cri_stats_provider.go]: Done

File: pkg/kubelet/stats/cri_stats_provider.go
Comment (ajaysundark) [reply pkg/kubelet/stats/cri_stats_provider.go:1]: @haircommander Could you help me understand the status of the CRI stats provider. This feature still seems to be alpha: https://kubernetes.io/docs/reference/instrumentation/cri-pod-container-metrics/?

containerd doesn't seem to support swapUsage in stats yet. I raised a bug to follow-up on this: https://github.com/containerd/containerd/issues/12026.

**Comment by yujuhong** [comment]
Need a release note

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Comment by SergeyKanzhelev** [comment]
/release-note-edit
```release-note
Fixed the bug when swap related metrics were not available in `/metrics/resource` endpoint.
```

File: pkg/kubelet/stats/cri_stats_provider.go
Comment (haircommander) [reply pkg/kubelet/stats/cri_stats_provider.go:1]: CRI stats provider is used by default in containerd right now. there are two different halves of it. the legacy "partial" CRI stats (where the remainder are populated by cadvisor) vs the new (2371) full CRI stats. it's possible swap stats are only populated in the "full" case

**Comment by yuanwang04** [comment]
/retest

Error is from resource_quota test, seems irrelevant from this change
```
 I0625 21:26:18.631640 67863 resource_quota.go:1615] Unexpected error: 
      <*errors.StatusError | 0xc00203bb80>: 
      pods "terminating-pod" is forbidden: exceeded quota: quota-terminating, requested: pods=1, used: pods=1, limited: pods=1
      {
          ErrStatus: 
              code: 403
              details:
                kind: pods
                name: terminating-pod
              message: 'pods "terminating-pod" is forbidden: exceeded quota: quota-terminating,
                requested: pods=1, used: pods=1, limited: pods=1'
              metadata: {}
              reason: Forbidden
              status: Failure,
      }
  [FAILED] in [It] - k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:1615 @ 06/25/25 21:26:18.631
  ```
