### PR TITLE
in e2e test, when kubectl exec fails to find the container to run a command, it should retry

### LINKED ISSUE #26076: e2e flake: Pod Disks tests are very flaky
The following tests failed multiple times both in GCE and GKE suites:
```
Pod Disks should schedule a pod w/two RW PDs both mounted to one container
Pod Disks should schedule a pod w/ a RW PD shared between multiple containers
```
The error message is the same:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:271 Expected error: <*exec.ExitError | 0xc8207d7c60>: { ProcessState: { pid: 5426, status: 256, rusage: { Utime: {Sec: 0, Usec: 92000}, Stime: {Sec: 0, Usec: 16000}, Maxrss: 29244, Ixrss: 0, Idrss: 0, Isrss: 0, Minflt: 2153, Majflt: 0, Nswap: 0, Inblock: 0, Oublock: 0, Msgsnd: 0, Msgrcv: 0, Nsignals: 0, Nvcsw: 725, Nivcsw: 5, }, }, Stderr: nil, } exit status 1 not to have occurred
```

Logs:
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/5896
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/5899
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/5903
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gce-slow/5904

https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/4491
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/4495
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/4496
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/4497
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/4500
https://console.cloud.google.com/storage/browser/kubernetes-jenkins/logs/kubernetes-e2e-gke-slow/4503

### PR DESCRIPTION
**Pull request by rootfs**
fix #26076 
Without retrying upon "container not found" error, `Pod Disks` test failed on the following error:

``` console
[k8s.io] Pod Disks 
  should schedule a pod w/two RW PDs both mounted to one container, write to PD, verify contents, delete pod, recreate pod, verify contents, and repeat in rapid succession [Slow]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:271
[BeforeEach] [k8s.io] Pod Disks
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:108
STEP: Creating a kubernetes client
May 23 19:18:02.254: INFO: >>> TestContext.KubeConfig: /root/.kube/config

STEP: Building a namespace api object
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [k8s.io] Pod Disks
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:69
[It] should schedule a pod w/two RW PDs both mounted to one container, write to PD, verify contents, delete pod, recreate pod, verify contents, and repeat in rapid succession [Slow]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pd.go:271
STEP: creating PD1
May 23 19:18:06.678: INFO: Successfully created a new PD: "rootfs-e2e-11dd5f5b-211b-11e6-a3ff-b8ca3a62792c".
STEP: creating PD2
May 23 19:18:11.216: INFO: Successfully created a new PD: "rootfs-e2e-141f062d-211b-11e6-a3ff-b8ca3a62792c".
May 23 19:18:11.216: INFO: PD Read/Writer Iteration #0
STEP: submitting host0Pod to kubernetes
W0523 19:18:11.279910    4984 request.go:347] Field selector: v1 - pods - metadata.name - pd-test-16d3653c-211b-11e6-a3ff-b8ca3a62792c: need to check if this is versioned correctly.
STEP: writing a file in the container
May 23 19:18:39.088: INFO: Running '/srv/dev/kubernetes/_output/dockerized/bin/linux/amd64/kubectl kubectl --server=https://130.211.199.187 --kubeconfig=/root/.kube/config exec --namespace=e2e-tests-pod-disks-3t3g8 pd-test-16d3653c-211b-11e6-a3ff-b8ca3a62792c -c=mycontainer -- /bin/sh -c echo '1394466581702052925' > '/testpd1/tracker0''
May 23 19:18:40.250: INFO: Wrote value: "1394466581702052925" to PD1 ("rootfs-e2e-11dd5f5b-211b-11e6-a3ff-b8ca3a62792c") from pod "pd-test-16d3653c-211b-11e6-a3ff-b8ca3a62792c" container "mycontainer"
STEP: writing a file in the container
May 23 19:18:40.251: INFO: Running '/srv/dev/kubernetes/_output/dockerized/bin/linux/amd64/kubectl kubectl --server=https://130.211.199.187 --kubeconfig=/root/.kube/config exec --namespace=e2e-tests-pod-disks-3t3g8 pd-test-16d3653c-211b-11e6-a3ff-b8ca3a62792c -c=mycontainer -- /bin/sh -c echo '1740704063962701662' > '/testpd2/tracker0''
May 23 19:18:41.433: INFO: Wrote value: "1740704063962701662" to PD2 ("rootfs-e2e-141f062d-211b-11e6-a3ff-b8ca3a62792c") from pod "pd-test-16d3653c-211b-11e6-a3ff-b8ca3a62792c" container "mycontainer"
STEP: reading a file in the container
May 23 19:18:41.433: INFO: Running '/srv/dev/kubernetes/_output/dockerized/bin/linux/amd64/kubectl kubectl --server=https://130.211.199.187 --kubeconfig=/root/.kube/config exec --namespace=e2e-tests-pod-disks-3t3g8 pd-test-16d3653c-211b-11e6-a3ff-b8ca3a62792c -c=mycontainer -- cat /testpd1/tracker0'
May 23 19:18:42.585: INFO: Read file "/testpd1/tracker0" with content: 1394466581702052925

STEP: reading a file in the container
May 23 19:18:42.585: INFO: Running '/srv/dev/kubernetes/_output/dockerized/bin/linux/amd64/kubectl kubectl --server=https://130.211.199.187 --kubeconfig=/root/.kube/config exec --namespace=e2e-tests-pod-disks-3t3g8 pd-test-16d3653c-211b-11e6-a3ff-b8ca3a62792c -c=mycontainer -- cat /testpd2/tracker0'
May 23 19:18:43.779: INFO: Read file "/testpd2/tracker0" with content: 1740704063962701662

STEP: deleting host0Pod
May 23 19:18:44.048: INFO: PD Read/Writer Iteration #1
STEP: submitting host0Pod to kubernetes
W0523 19:18:44.132475    4984 request.go:347] Field selector: v1 - pods - metadata.name - pd-test-16d3653c-211b-11e6-a3ff-b8ca3a62792c: need to check if this is versioned correctly.
STEP: reading a file in the container
May 23 19:18:45.186: INFO: Running '/srv/dev/kubernetes/_output/dockerized/bin/linux/amd64/kubectl kubectl --server=https://130.211.199.187 --kubeconfig=/root/.kube/config exec --namespace=e2e-tests-pod-disks-3t3g8 pd-test-16d3653c-211b-11e6-a3ff-b8ca3a62792c -c=mycontainer -- cat /testpd1/tracker0'
May 23 19:18:46.290: INFO: error running kubectl exec to read file: exit status 1
stdout=
stderr=error: error executing remote command: error executing command in container: container not found ("mycontainer")
)
May 23 19:18:46.290: INFO: Error reading file: exit status 1
May 23 19:18:46.290: INFO: Unexpected error occurred: exit status 1
```

Now I've run this fix on e2e pd test 5 times and no longer see any failure

### CODE REVIEW

**Comment by saad-ali** [comment]
LGTM Thanks @rootfs

**Comment by ncdc** [comment]
`kubectl exec` won't work unless the pod is Running. How is it that the pod is Running but a container can't be found?

File: test/e2e/framework/framework.go [hunk 1]
```diff
@@ -477,6 +477,13 @@ func kubectlExecWithRetry(namespace string, podName, containerName string, args
 				continue
 			}
 		}
+		if err != nil {
```
Comment (ncdc) [inline test/e2e/framework/framework.go]: There's already a check for a non-nil error right before this. I would move the strings.Contains check you're adding into that block instead of adding another one, assuming we decide to keep this.

**Comment by saad-ali** [comment]
From @ncdc on `kubernetes-dev` Slack:
```
this is potentially because exec doesn’t yet support looking a pod up by uid

[2:13] 
the test creates, deletes, recreates the same pod name multiple times

[2:13] 
i think what’s happening is exec is finding the wrong pod while the old one is being torn down, maybe?

[2:14] 
we could change the test to vary the pod name each time through the loop

[2:15] 
this sets up the pod https://github.com/kubernetes/kubernetes/blob/master/test/e2e/pd.go#L179

it does assign it a name that includes a random uuid, but that is only ever set up once, outside of the for loop

[2:16] 
[...] i’d maybe suggest trying this instead of retrying exec on ‘container not found'
```

This indicates that the pod is being torn down right after `WaitForPodRunningSlow` succeeds and right before `WriteFileViaContainer`. Which is a symptom of the race conditions between orphan volumes loop and pod creation loop that were held together with glue.

This fix will mask the issue by retrying until the pod with the same name is recreated. But it does indicate that #26076 destabilized PD mount/unmount code.

To unblock the submit queue, I'll LGTM this.

I am working on kubelet volume manager that will fix the actual races, and along with that change, I will revert this change and verify the races are fixed and modify the tests further as needed.

**Comment by saad-ali** [comment]
@k8s-oncall Could you please manually merge this

File: test/e2e/framework/framework.go [hunk 2]
```diff
@@ -477,6 +477,13 @@ func kubectlExecWithRetry(namespace string, podName, containerName string, args
...
+			if strings.Contains(strings.ToLower(string(stdErrBytes)), "container not found") {
+				// Retry on "container not found" errors
+				Logf("Warning: kubectl exec encountered container not found.\nerr=%v\nstdout=%v\nstderr=%v)", err, string(stdOutBytes), string(stdErrBytes))
+				continue
```
Comment (ixdy) [inline test/e2e/framework/framework.go]: should there be a sleep before trying again?

Comment (saad-ali) [inline test/e2e/framework/framework.go]: Yes, there should

**Comment by saad-ali** [comment]
@rootfs could you address the open comments. In the meantime, we're going to move the tests to flaky (https://github.com/kubernetes/kubernetes/issues/26076)

**Comment by rootfs** [comment]
@saad-ali feedback addressed. Have seen pd test running 10 times for 3 hours without any failure

File: test/e2e/framework/framework.go [hunk 3]
```diff
@@ -476,6 +476,12 @@ func kubectlExecWithRetry(namespace string, podName, containerName string, args
 				Logf("Warning: kubectl exec encountered i/o timeout.\nerr=%v\nstdout=%v\nstderr=%v)", err, string(stdOutBytes), string(stdErrBytes))
 				continue
 			}
+			if strings.Contains(strings.ToLower(string(stdErrBytes)), "container not found") {
+				// Retry on "container not found" errors
+				Logf("Warning: kubectl exec encountered container not found.\nerr=%v\nstdout=%v\nstderr=%v)", err, string(stdOutBytes), string(stdErrBytes))
+				time.Sleep(2 * time.Second)
```
Comment (saad-ali) [inline test/e2e/framework/framework.go]: Sleep should happen for both "i/o timeout" and "container not found", no?

Comment (rootfs) [inline test/e2e/framework/framework.go]: I haven't seen any i/o timeout yet. If it happens, I am not sure timeout helps.

Comment (saad-ali) [inline test/e2e/framework/framework.go]: Ack

**Comment by saad-ali** [comment]
LGTM
