### PR TITLE
Prevent panic in 'kubectl exec' when redirecting stdout

### LINKED ISSUE #30290: panic during "kubectl exec" when redirecting stdout to a file
```
kubectl run --image=alpine sleep -- /bin/sh -c "sleep 10000"
kubectl exec -it sleep-1786222145-kukx6 -- ls -altr > out.txt
```

results in:

```
E0809 12:51:03.679435 27231 runtime.go:64] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
 /Users/dims/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:70
 /Users/dims/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:63
 /Users/dims/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:49
 /usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:472
 /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443
 /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:62
 /usr/local/Cellar/go/1.6.2/libexec/src/runtime/sigpanic_unix.go:24
 /Users/dims/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/unversioned/remotecommand/v3.go:75
 /usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_amd64.s:1998
 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal 0xb code=0x1 addr=0x20 pc=0x4d41ec]

goroutine 11 [running]:
 panic(0x17506a0, 0xc8200120c0)
 /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:481 +0x3e6
 k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
 /Users/dims/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x153
 panic(0x17506a0, 0xc8200120c0)
 /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
 k8s.io/kubernetes/pkg/client/unversioned/remotecommand.(*streamProtocolV3).handleResizes.func1(0xc820098f20)
 /Users/dims/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/unversioned/remotecommand/v3.go:75 +0xfc
 created by k8s.io/kubernetes/pkg/client/unversioned/remotecommand.(*streamProtocolV3).handleResizes
 /Users/dims/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/client/unversioned/remotecommand/v3.go:83 +0x44
```

Note that `kubectl exec -it sleep-1786222145-kukx6 -- ls -altr` works fine.

### PR DESCRIPTION
**Pull request by dims**
Just add some nil checks to make sure we don't trip over when
we redirect output from exec to a file.

Fixes #30290

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/30291)

### CODE REVIEW

File: pkg/client/unversioned/remotecommand/v3.go [hunk 1]
```diff
@@ -72,6 +72,9 @@ func (p *streamProtocolV3) handleResizes() {
 
 		encoder := json.NewEncoder(p.resizeStream)
 		for {
+			if p == nil || p.TerminalSizeQueue == nil {
```
Comment (caesarxuchao) [inline pkg/client/unversioned/remotecommand/v3.go]: How about checking `p==nil` at the beginning of handleResizes()?

Comment (dims) [inline pkg/client/unversioned/remotecommand/v3.go]: Good point. I was not sure if we lose this (ends up with nil) in the for loop. but definitely worth starting there

**Comment by dims** [comment]
@caesarxuchao Any idea why the release-note-label-needed was added here? PTAL. thanks!

**Comment by caesarxuchao** [comment]
`release-note-label-needed` is the default label, reviewer needs to remove it.

LGTM. Thanks!
