### PR TITLE
e2e storage: terminate worker quietly on test completion

### LINKED ISSUE #118602: [Failing Test] gce-cos-master-serial
### Which jobs are failing?

master-informing:

- gce-cos-master-serial

### Which tests are failing?

`Kubernetes e2e suite: [It] [sig-storage] PersistentVolumes-local Stress with local volumes [Serial] should be able to process many pods and reuse local volumes`

Screenshot from 2023-06-10 11-15-02

### Since when has it been failing?

2023-06-08 20:01:55 +0000 UTC

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial

### Reason for failure (if possible)

`
{ failed [FAILED] PV Create API error: Post "https://35.247.13.135/api/v1/persistentvolumes": context canceled
In [DeferCleanup (Each)] at: test/e2e/storage/persistent_volumes-local.go:534 @ 06/09/23 18:05:53.165
}
`

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig storage
cc @kubernetes/ci-signal

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

Once DeferCleanup for the worker goroutine is invoked, there's no need to continue doing anything anymore in that goroutine and it can return immediately, without reporting the "context canceled" error because there is no other reason for that.

#### Which issue(s) this PR fixes:
Fixes #118602

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

File: test/e2e/storage/persistent_volumes-local.go [hunk 1]
```diff
@@ -528,9 +529,15 @@ var _ = utils.SIGDescribe("PersistentVolumes-local ", func() {
 									continue
 								}
 								err = config.client.CoreV1().PersistentVolumes().Delete(backgroundCtx, pv.Name, metav1.DeleteOptions{})
+								if errors.Is(err, context.Canceled) {
+									continue
```
Comment (aojea) [inline test/e2e/storage/persistent_volumes-local.go:533]: should you return directly?

Comment (aojea) [reply test/e2e/storage/persistent_volumes-local.go:533]: we can iterate if necessary

/lgtm
