### PR TITLE
e2e: fix node conformance flake

### LINKED ISSUE #129955: [Flaky Test] [sig-node] Pods should support retrieving logs from the container over websockets [NodeConformance] [Conformance]
### Which jobs are flaking?

sig-release-master-blocking
- ci-crio-cgroupv1-node-e2e-conformance

### Which tests are flaking?

`E2eNode Suite.[It] [sig-node] Pods should support retrieving logs from the container over websockets [NodeConformance] [Conformance]`

### Since when has it been flaking?

[1/23/2025, 3:34:26 AM](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-crio-cgroupv1-node-e2e-conformance/1882187017517797376)
[1/26/2025, 4:00:31 AM](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cos-cgroupv1-containerd-node-e2e/1883281124474490880)
[2/1/2025, 7:16:15 AM](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-ec2-eks-al2023/1885504591236173824)
[2/2/2025, 11:40:46 PM](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-crio-cgroupv1-node-e2e-conformance/1886114867551670272)

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-crio-cgroupv1-node-e2e-conformance

### Reason for failure (if possible)

```
{ failed [FAILED] Unexpected websocket logs:
In [It] at: k8s.io/kubernetes/test/e2e/common/node/pods.go:672 @ 02/02/25 18:26:01.083
}
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by bart0sh**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

The test `Pods should support retriving logs from the container over websockets` flakes as it doesn't always wait until container is running and is able to produce expected output. Waiting for pod to be in the `Running` state is not enough as it doesn't always mean that [container is running](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase), it could also mean that the container is still starting.

This PR ensures that the container under test is running before trying to retrieve its logs.

#### Which issue(s) this PR fixes:

Fixes #129955

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/sig node

### CODE REVIEW

**Comment by haircommander** [comment]
/lgtm

makes sense to me!

File: test/e2e/common/node/pods.go [hunk 1]
```diff
@@ -638,7 +638,11 @@ var _ = SIGDescribe("Pods", func() {
 		})
 
 		ginkgo.By("submitting the pod to kubernetes")
-		podClient.CreateSync(ctx, pod)
+		pod = podClient.CreateSync(ctx, pod)
```
Comment (aojea) [inline test/e2e/common/node/pods.go:641]: I think we should modify `CreateSync` for wait for all containers running, so is what most of us assume,

Comment (bart0sh) [reply test/e2e/common/node/pods.go:641]: Yes, but not in this PR. Let's first see if it helps to get rid of flakes in this particular test. Agreed?
