### PR TITLE
Fix service account token projected volume validation

### LINKED ISSUE #121415: Service account token projected volume validation should call `validateLocalNonReservedPath` on the token path
> also call `validateLocalNonReservedPath` on `source.ClusterTrustBundle.Path` to catch paths the kubelet will reject (like absolute paths, paths containing backsteps, etc):

https://github.com/kubernetes/kubernetes/blob/f7cb8a5e8a860df643e143cde54d34080372b771/pkg/volume/util/atomic_writer.go#L252-L264

> configmap, secret, and downwardAPI already call this. projected token does not (@enj, can you open an issue to ratchet validate that as well)

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/pull/113374#discussion_r1365908487_

### PR DESCRIPTION
**Pull request by Taction**
#### What type of PR is this?

Add one of the following kinds:
/kind bug

#### What this PR does / why we need it:
Service account token projected volume validation should call validateLocalNonReservedPath on the token path.

#### Which issue(s) this PR fixes:

Fixes #121415

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by Taction** [comment]
Hello, I'm new here. It would take me some more time to figure out why e2e tests failed. Besides, who can help point out how to run k8s e2e tests locally or how to inspect what is wrong in the tests, any help would be appreciated.

File: pkg/api/pod/util.go [hunk 1]
```diff
@@ -353,6 +353,21 @@ func hasInvalidTopologySpreadConstraintLabelSelector(spec *api.PodSpec) bool {
 	return false
 }
 
+// hasNonLocalProjectedTokenPath return true if spec.Volumes have any entry with non-local projected token path
+func hasNonLocalProjectedTokenPath(spec *api.PodSpec) bool {
+	for _, volume := range spec.Volumes {
+		if volume.Projected != nil {
+			for _, source := range volume.Projected.Sources {
+				errs := apivalidation.ValidateLocalNonReservedPath(source.ServiceAccountToken.Path, nil)
```
Comment (liggitt) [inline pkg/api/pod/util.go:361]: this needs a `if source.ServiceAccountToken != nil` check

Comment (Taction) [reply pkg/api/pod/util.go:364]: Done.

**Comment by Taction** [comment]
@liggitt Thank you so much for the advice, it works!
