### PR TITLE
fix falky test pkg/registry/core/persistentvolume/storage TestUpdateStatus

### LINKED ISSUE #121752: falky test pkg/registry/core/persistentvolume/storage TestUpdateStatus
### Which jobs are flaking?

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Which tests are flaking?

pkg/registry/core/persistentvolume/storage TestUpdateStatus

### Since when has it been flaking?

unknown

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Reason for failure (if possible)

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121743/pull-kubernetes-unit/1721422670844661760

```
=== FAIL: pkg/registry/core/persistentvolume/storage TestUpdateStatus (0.23s)
    storage_test.go:215: unexpected object:   core.PersistentVolumeStatus{
          	Phase:                   "Bound",
          	Message:                 "",
          	Reason:                  "",
        - 	LastPhaseTransitionTime: s"2023-11-06 07:22:50 +0000 UTC",
        + 	LastPhaseTransitionTime: s"2023-11-06 07:22:51 +0000 UTC",
          }
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig storage

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

```
(⎈|kind-kind:N/A)➜  kubernetes git:(master) git checkout fix-121752
Switched to branch 'fix-121752'
Your branch is up to date with 'origin/fix-121752'.
(⎈|kind-kind:N/A)➜  kubernetes git:(fix-121752) go test -c -race pkg/registry/core/persistentvolume/storage/storage.go pkg/registry/core/persistentvolume/storage/storage_test.go -run ^TestUpdateStatus$
(⎈|kind-kind:N/A)➜  kubernetes git:(fix-121752) stress -p 10  ./storage.test -test.run ^TestUpdateStatus$
5s: 20 runs so far, 0 failures
10s: 48 runs so far, 0 failures
15s: 77 runs so far, 0 failures
20s: 105 runs so far, 0 failures
25s: 134 runs so far, 0 failures
30s: 164 runs so far, 0 failures
35s: 194 runs so far, 0 failures
40s: 219 runs so far, 0 failures
45s: 249 runs so far, 0 failures
50s: 277 runs so far, 0 failures
55s: 306 runs so far, 0 failures
1m0s: 333 runs so far, 0 failures
1m5s: 360 runs so far, 0 failures
^C
(⎈|kind-kind:N/A)➜  kubernetes git:(fix-121752)
```

#### Which issue(s) this PR fixes:

Fixes #121752

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by kadenlnelson — APPROVED** [review]

**Comment by carlory** [comment]
unrelated failed job because of pod got deleted unexpectedly      

/test pull-kubernetes-node-e2e-containerd

**Comment by RomanBednar** [comment]
I'm not sure the stress test shown would reveal the flake. I've tried to run it the same way locally without this patch and did not see it flaking:

```
$ stress -p 100  ./storage.test -test.run ^TestUpdateStatus$
5s: 0 runs so far, 0 failures
10s: 0 runs so far, 0 failures
15s: 0 runs so far, 0 failures
20s: 106 runs so far, 0 failures
25s: 158 runs so far, 0 failures
30s: 200 runs so far, 0 failures
35s: 244 runs so far, 0 failures
40s: 261 runs so far, 0 failures
45s: 316 runs so far, 0 failures
50s: 321 runs so far, 0 failures
55s: 358 runs so far, 0 failures
1m0s: 371 runs so far, 0 failures
1m5s: 372 runs so far, 0 failures
1m10s: 378 runs so far, 0 failures
1m15s: 408 runs so far, 0 failures
1m20s: 417 runs so far, 0 failures
1m25s: 445 runs so far, 0 failures
1m30s: 473 runs so far, 0 failures
1m35s: 476 runs so far, 0 failures
1m40s: 476 runs so far, 0 failures
1m45s: 477 runs so far, 0 failures
1m50s: 477 runs so far, 0 failures
1m55s: 495 runs so far, 0 failures
2m0s: 517 runs so far, 0 failures
```

File: pkg/registry/core/persistentvolume/storage/storage_test.go [hunk 1]
```diff
@@ -195,9 +196,8 @@ func TestUpdateStatus(t *testing.T) {
 			Name: "foo",
 		},
 		Status: api.PersistentVolumeStatus{
-			Phase: api.VolumeBound,
-			// Set the same timestamp as original PV so this won't get updated on phase change breaking DeepEqual() later in test.
-			LastPhaseTransitionTime: pvStartTimestamp,
+			Phase:                   api.VolumeBound,
+			LastPhaseTransitionTime: &metav1.Time{Time: pvStartTimestamp.Time.Add(time.Second)},
```
Comment (RomanBednar) [inline pkg/registry/core/persistentvolume/storage/storage_test.go:200]: Why would we need to add exactly 1 second drift here? I don't see how this would help with the flakes.

File: pkg/registry/core/persistentvolume/storage/storage_test.go [hunk 2]
```diff
@@ -210,6 +210,15 @@ func TestUpdateStatus(t *testing.T) {
 		t.Errorf("unexpected error: %v", err)
 	}
 	pvOut := obj.(*api.PersistentVolume)
+
+	if pvStartTimestamp.Equal(pvOut.Status.LastPhaseTransitionTime) {
+		t.Errorf("unexpected timestamp, expected %v, got %v", pvOut.Status.LastPhaseTransitionTime, pvStartTimestamp)
+	}
+
+	// reset timestamp to nil in order to compare the rest of the object
```
Comment (RomanBednar) [inline pkg/registry/core/persistentvolume/storage/storage_test.go:218]: Do we know how the drift was caused making the DeepEqual fail? I don't see it yet but removing the root cause would be better than trying to mask it.

File: pkg/registry/core/persistentvolume/storage/storage_test.go (hunk 1 above)
Comment (carlory) [reply pkg/registry/core/persistentvolume/storage/storage_test.go:200]: it is not related with this flake. it is used to test the new feature  which gate is on.

File: pkg/registry/core/persistentvolume/storage/storage_test.go (hunk 2 above)
Comment (carlory) [reply pkg/registry/core/persistentvolume/storage/storage_test.go:218]: the root cause is that the timestamp is updated due to the phase changed from pending.

the previous test is not correct even though its result is passed. If the execution process of test is beyond a certain threshold, it will fail.

File: pkg/registry/core/persistentvolume/storage/storage_test.go [hunk 3]
```diff
@@ -195,9 +196,8 @@ func TestUpdateStatus(t *testing.T) {
 			Name: "foo",
 		},
 		Status: api.PersistentVolumeStatus{
-			Phase: api.VolumeBound,
-			// Set the same timestamp as original PV so this won't get updated on phase change breaking DeepEqual() later in test.
```
Comment (carlory) [inline pkg/registry/core/persistentvolume/storage/storage_test.go:199]: @RomanBednar it's not correct.

**Comment by carlory** [comment]
> I'm not sure the stress test shown would reveal the flake. I've tried to run it the same way locally without this patch and did not see it flaking:

@RomanBednar sorry,  I paste a wrong command in description, please try the following command: 

```
(⎈|kind-kind:N/A)➜  kubernetes git:(master) go test -c -race pkg/registry/core/persistentvolume/storage/storage.go pkg/registry/core/persistentvolume/storage/storage_test.go -run ^TestUpdateStatus$
(⎈|kind-kind:N/A)➜  kubernetes git:(master) stress -p 10  ./storage.test -test.run ^TestUpdateStatus$

/var/folders/n6/33y75ytn36g38k2wnkb6lp8r0000gn/T/go-stress-20231123T212946-1738443952
W1123 21:29:50.011337   19919 logging.go:59] [core] [Channel #4 SubChannel #7] grpc: addrConn.createTransport failed to connect to {Addr: "localhost:51571", ServerName: "localhost:51571", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:51571: connect: connection refused"
--- FAIL: TestUpdateStatus (0.93s)
    storage_test.go:215: unexpected object:   core.PersistentVolumeStatus{
          	Phase:                   "Bound",
          	Message:                 "",
          	Reason:                  "",
        - 	LastPhaseTransitionTime: s"2023-11-23 21:29:49 +0800 CST",
        + 	LastPhaseTransitionTime: s"2023-11-23 21:29:50 +0800 CST",
          }
FAIL


ERROR: exit status 1

5s: 16 runs so far, 1 failures (6.25%)
```

File: pkg/registry/core/persistentvolume/storage/storage_test.go (hunk 2 above)
Comment (RomanBednar) [reply pkg/registry/core/persistentvolume/storage/storage_test.go:218]: Agree, the timestamp really updates due to phase change in this case but that's what I wanted to avoid. See the comment below.

**Comment by RomanBednar** [comment]
> @RomanBednar sorry, I paste a wrong command in description, please try the following command:

@carlory ah, I see. Testing showed the original issue and with my suggestion it's working fine. WDYT?

File: pkg/registry/core/persistentvolume/storage/storage_test.go (hunk 3 above)
Comment (carlory) [reply pkg/registry/core/persistentvolume/storage/storage_test.go:199]: @RomanBednar Do we  remove the getPhaseTranstitionTime func?

Comment (carlory) [reply pkg/registry/core/persistentvolume/storage/storage_test.go:199]: > @RomanBednar Do we remove the getPhaseTranstitionTime func?

please ignore this comment.

**Comment by carlory** [comment]
thanks for your review. @RomanBednar updated. please review again.

**Comment by carlory** [comment]
unrelated failed test

/test pull-kubernetes-unit

File: pkg/registry/core/persistentvolume/storage/storage_test.go [hunk 4]
```diff
@@ -17,12 +17,10 @@ limitations under the License.
 package storage
 
 import (
-	utilfeature "k8s.io/apiserver/pkg/util/feature"
-	featuregatetesting "k8s.io/component-base/featuregate/testing"
-	"k8s.io/kubernetes/pkg/features"
+	"context"
```
Comment (RomanBednar) [inline pkg/registry/core/persistentvolume/storage/storage_test.go:20]: Was the import ordering change intentional? Please remove if not.

Comment (carlory) [reply pkg/registry/core/persistentvolume/storage/storage_test.go:20]: Split imports into two parts, one for go built-in library.It follows the same style on imports as other package files. i.e. https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/persistentvolumeclaim/storage/storage_test.go

this changes is not related with this issue. if it's not accepted, I can remove it.

**Comment by carlory** [comment]
cc @pohly can you take a look? I'm not sure if this fix should be merged into 1.29?

**Comment by xmudrii** [comment]
> Whether this should go into 1.29 is a question for the release managers.

This is actually up to the Release Team Leads, not the Release Managers. :) cc @kubernetes/release-team-leads

**Comment by carlory** [comment]
/cc @msau42 

please take a look, thank you.

**Comment by carlory** [comment]
@RomanBednar @msau42  do we want to cherry-pick it into 1.29 once it's merged?

**Comment by pacoxu** [comment]
/priority important-soon
flake again in master blocking https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

ping @kubernetes/sig-storage-leads
