### PR TITLE
Don't store no-op updates in etcd.

### LINKED ISSUE #16076: Regression: identical writes to storage interface are not ignored
Historically, a write to etcd that did not change content (existing content == new content on CAS) would not result in a watch event.  At some point between last year and now, that changed, and identical object writes via the etcd storage result in multiple watch events.  This is bad for several reasons - bad controller loops can flood the event logs trying to write the same data, clients are unnecessarily taxed, etc.

Opening this to ensure it gets tracked down - we saw this in openshift/origin#5275.  This could be a 1.1 blocker.

UPDATE: Caused because we started serializing the resource version of the persisted object to the store, which we used to not do.  The version in the store was 1 off from the version we would write (because we return the resource version that someone should watch from), which meant that the objects were different as serialized.

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #16076

@lavalamp @smarterclayton

### CODE REVIEW

File: pkg/storage/etcd/etcd_helper.go [hunk 1]
```diff
@@ -558,6 +576,15 @@ func (h *etcdHelper) GuaranteedUpdate(ctx context.Context, key string, ptrToType
 			ttl = *newTTL
 		}
 
+		// Since update object may have a resourceVersion set, we need to clear it here.
+		if h.versioner != nil {
+			if err := h.versioner.UpdateObject(ret, meta.Expiration, 0); err != nil {
+				return errors.New("resourceVersion cannot be set on objects store in etcd")
+			}
+		} else {
+			return errors.New("couldn't access version without versioner")
```
Comment (wojtek-t) [inline pkg/storage/etcd/etcd_helper.go]: @smarterclayton @lavalamp - if we can do this, I will fix some failing tests; If you think that assuming versioner is incorrect, what do you think we should do?

File: pkg/storage/etcd/etcd_helper.go [hunk 2]
```diff
@@ -191,6 +191,23 @@ func (h *etcdHelper) Set(ctx context.Context, key string, obj, out runtime.Objec
 	if ctx == nil {
 		glog.Errorf("Context is nil")
 	}
+
+	version := uint64(0)
```
Comment (wojtek-t) [inline pkg/storage/etcd/etcd_helper.go]: BTW - Set() method is used only in tests. I'm happy to remove this method from the interface if you agree it's not needed.

File: pkg/storage/etcd/etcd_helper.go (hunk 1 above)
Comment (wojtek-t) [inline pkg/storage/etcd/etcd_helper.go]: Tests should be fixed now.

File: pkg/registry/generic/etcd/etcd_test.go [hunk 3]
```diff
@@ -339,6 +339,53 @@ func TestEtcdUpdate(t *testing.T) {
 
 }
 
+func TestNoOpUpdates(t *testing.T) {
+	server, registry := NewTestGenericEtcdRegistry(t)
```
Comment (liggitt) [inline pkg/registry/generic/etcd/etcd_test.go]: if possible, can we also have a test that inserts an old incorrect record (containing resourceVersion) into etcd, makes sure a no-op update is ignored, and an actual update is persisted?

File: pkg/registry/serviceaccount/etcd/etcd_test.go [hunk 4]
```diff
@@ -70,7 +70,7 @@ func TestUpdate(t *testing.T) {
 		// updateFunc
 		func(obj runtime.Object) runtime.Object {
 			object := obj.(*api.ServiceAccount)
-			// TODO: Update this serviceAccount
+			object.Secrets = []api.ObjectReference{api.ObjectReference{}}
```
Comment (liggitt) [inline pkg/registry/serviceaccount/etcd/etcd_test.go]: why was this needed?

File: pkg/storage/etcd/etcd_helper_test.go [hunk 5]
```diff
@@ -352,28 +352,11 @@ func TestSetWithVersion(t *testing.T) {
 	}
 }
 
-func TestSetWithoutResourceVersioner(t *testing.T) {
```
Comment (liggitt) [inline pkg/storage/etcd/etcd_helper_test.go]: why was this test removed?

File: pkg/registry/generic/etcd/etcd_test.go (hunk 3 above)
Comment (wojtek-t) [inline pkg/registry/generic/etcd/etcd_test.go]: Sorry - I'm afraid I don't understand:
- what do you mean by "inserts an old incorrect record (containing resourceVersion) into etcd"?
- actual updates are tested by a bunch of other tests, I don't think we need to test it here again

File: pkg/registry/serviceaccount/etcd/etcd_test.go (hunk 4 above)
Comment (wojtek-t) [inline pkg/registry/serviceaccount/etcd/etcd_test.go]: Without this, update of ServiceAccount was a no-op, and thus was ignored :)

File: pkg/storage/etcd/etcd_helper_test.go (hunk 5 above)
Comment (wojtek-t) [inline pkg/storage/etcd/etcd_helper_test.go]: Yes - as I wrote in another comment, I currently need to have versioner to clean the version. We need to decide whether we want to enforce having a versioner or just accept the fact that if we don't have versioner we can have resourceVersion stored in etcd. I think the former is better...
@smarterclayton @lavalamp for thoughts

File: pkg/registry/generic/etcd/etcd_test.go (hunk 3 above)
Comment (liggitt) [inline pkg/registry/generic/etcd/etcd_test.go]: All the other tests are testing updates against new records made with the current version which will not set resourceVersion in etcd. I want to make sure when this fix runs against an etcd containing old incorrect records which contain resourceVersion, we get correct update behavior

Comment (wojtek-t) [inline pkg/registry/generic/etcd/etcd_test.go]: Got it - makes sense (although in that case no-op update is not no-op so it will be performed). But having such test makes sense.

Comment (wojtek-t) [inline pkg/registry/generic/etcd/etcd_test.go]: Will add such test tomorrow.

File: pkg/registry/serviceaccount/etcd/etcd_test.go (hunk 4 above)
Comment (liggitt) [inline pkg/registry/serviceaccount/etcd/etcd_test.go]: ah. might want to make the objectreference contain a name... surprised it passed validation without it

File: pkg/registry/generic/etcd/etcd_test.go (hunk 3 above)
Comment (liggitt) [inline pkg/registry/generic/etcd/etcd_test.go]: > although in that case no-op update is not no-op so it will be performed

fair enough. I guess the first one would actually update, and correctly empty the `resourceVersion` in etcd, so a second update should be a true no-op, right?

Comment (wojtek-t) [inline pkg/registry/generic/etcd/etcd_test.go]: Yes - that should be the case.

File: pkg/registry/serviceaccount/etcd/etcd_test.go (hunk 4 above)
Comment (wojtek-t) [inline pkg/registry/serviceaccount/etcd/etcd_test.go]: it seems that we don't do any validation on ObjectReference (we only validate LocalObjectReference).

File: pkg/storage/etcd/etcd_helper.go (hunk 2 above)
Comment (smarterclayton) [inline pkg/storage/etcd/etcd_helper.go]: Let's open a follow up issue post 1.3 - I don't think we have to remove it now.

File: pkg/storage/etcd/etcd_helper.go [hunk 6]
```diff
@@ -191,6 +191,23 @@ func (h *etcdHelper) Set(ctx context.Context, key string, obj, out runtime.Objec
...
+			return errors.New("couldn't get resourceVersion from object")
+		}
+		if version != 0 {
+			// We cannot store object with resourceVersion in etcd, we need to clear it here.
+			if err := h.versioner.UpdateObject(obj, nil, 0); err != nil {
+				return errors.New("resourceVersion cannot be set on objects store in etcd")
+			}
+		}
+	} else {
+		return errors.New("couldn't access version without versioner")
```
Comment (smarterclayton) [inline pkg/storage/etcd/etcd_helper.go]: Hrm - isn't this a change in behavior?  We're failing now if you don't set a versioner, whereas before we just continued.  I'm not sure the check should be at this level - if we require versioner, we should fail earlier.  Would suggest not adding the else condition for now.

File: pkg/storage/etcd/etcd_helper.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/storage/etcd/etcd_helper.go]: See previous comment, would recommend not changing this for 1.2 (given how close we are) and instead doing it as a follow up.

Comment (wojtek-t) [inline pkg/storage/etcd/etcd_helper.go]: @smarterclayton - so IIUC, you suggest that "storing an object with resourceVersion in etcd if there is no versioner" (which means that we will have no-op updates), is better than "fail if there is no versioner" for now, right?

File: pkg/storage/etcd/etcd_helper.go [hunk 7]
```diff
@@ -558,6 +576,15 @@ func (h *etcdHelper) GuaranteedUpdate(ctx context.Context, key string, ptrToType
 			ttl = *newTTL
 		}
 
+		// Since update object may have a resourceVersion set, we need to clear it here.
+		if h.versioner != nil {
+			if err := h.versioner.UpdateObject(ret, meta.Expiration, 0); err != nil {
```
Comment (lavalamp) [inline pkg/storage/etcd/etcd_helper.go]: Is RV the only field like this? How about SelfLink, can we clear that too?

Comment (wojtek-t) [inline pkg/storage/etcd/etcd_helper.go]: We can, but then we can't use versioner for it. And since we will need to use meta.Accessor, then there is no need to use versioner at all. WDYT?

Comment (smarterclayton) [inline pkg/storage/etcd/etcd_helper.go]: That's a really big change right now....

Comment (wojtek-t) [inline pkg/storage/etcd/etcd_helper.go]: @smarterclayton - sorry, I'm afraid I don't understand.
You suggest leaving as is or changing (to not use versioner and just work on meta.Accessor)?

Comment (smarterclayton) [inline pkg/storage/etcd/etcd_helper.go]: I was suggesting making the smallest change possible for 1.2 - using
versioner and not resetting self link (I don't think we have evidence
self link is causing updates to not be no-op, but if we do then yes,
we have to fix it)

File: pkg/storage/etcd/etcd_helper.go (hunk 2 above)
Comment (wojtek-t) [inline pkg/storage/etcd/etcd_helper.go]: Filed https://github.com/kubernetes/kubernetes/issues/20963 for it.

File: pkg/storage/etcd/etcd_helper.go [hunk 8]
```diff
@@ -558,6 +576,16 @@ func (h *etcdHelper) GuaranteedUpdate(ctx context.Context, key string, ptrToType
...
+				return errors.New("resourceVersion cannot be set on objects store in etcd")
+			}
+		}
+		// TODO: If versioner is nil, then we may end up with having ResourceVersion set
+		// in the object and this will be incorrect ResourceVersion. We should fix it by
+		// requiring "versioner != nil" at the constructor level for 1.3 milestone.
+
```
Comment (wojtek-t) [inline pkg/storage/etcd/etcd_helper.go]: @smarterclayton - I browsed through the code, and basically there is no easy way to construct etcdHelper with nil versioner (all constructors set it to ApiObjectVersioner{}) and we don't have setters to change it.
So what do you think about fixing this TODO in a followup PR now?

File: pkg/registry/generic/etcd/etcd_test.go (hunk 3 above)
Comment (wojtek-t) [inline pkg/registry/generic/etcd/etcd_test.go]: Hmm - it seems that there is no easy way to store object with ResourceVersion set in etcd after my fixes.
I manually checked that it works as expected and added a TODO for it.

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please github issue: #IGNORE

File: pkg/storage/etcd/etcd_helper.go (hunk 8 above)
Comment (smarterclayton) [inline pkg/storage/etcd/etcd_helper.go]: That's fine

File: pkg/registry/generic/etcd/etcd_test.go (hunk 3 above)
Comment (smarterclayton) [inline pkg/registry/generic/etcd/etcd_test.go]: You can't use a fake storage interface to test?

Comment (wojtek-t) [inline pkg/registry/generic/etcd/etcd_test.go]: I can, but we don't have such, so this would make this change much bigger (it will take some time to implement it).

Comment (smarterclayton) [inline pkg/registry/generic/etcd/etcd_test.go]: We don't have a fake storage interface anymore?  ....

....

....

Ok.  Then it can wait for a follow up.

**Comment by wojtek-t** [comment]
I'm trying to understand the failure in integration tests...

**Comment by wojtek-t** [comment]
@smarterclayton @lavalamp - After few hours of debugging, to be honest I have no idea what is happening there.

The issue is in hack/test-cmd.sh and is related to Deployments (you should be able to easily reproduce this with running hack/test-cmd.sh). The issue is basically that Deployment is not updated correctly due to some reasons, but I'm seeing logs like this one (which I can't see without my change):

    E0210 14:24:00.895140     366 deployment_controller.go:386] Error syncing deployment: resource name may not be empty

I've spent few hours looking into it, but still have no idea what exactly is happening there (although it is definitely related to Deployments).
@nikhiljindal - since you are familiar with deployment_controller, maybe you can take a look into it?

**Comment by smarterclayton** [comment]
Will look later when I get back to being free.

**Comment by nikhiljindal** [comment]
Looking at the test logs, looks like the kubectl apply command for deployment-revision2 doesnt succeed
https://github.com/kubernetes/kubernetes/blob/master/hack/test-cmd.sh#L1119

```
kubectl apply -f hack/testdata/deployment-revision2.yaml "${kube_flags[@]}"
```

Not sure why

**Comment by nikhiljindal** [comment]
I debugged this with @janetkuo and the command that is failing is https://github.com/kubernetes/kubernetes/blob/master/hack/test-cmd.sh#L1129.

We found a bug in deployment controller which she is fixing. We are not sure why the test is not failing on HEAD. Will see if the fix gets the tests to pass here.

**Comment by janetkuo** [comment]
The bug we found earlier is just a false alarm. 

So far I can only tell that `Error syncing deployment: resource name may not be empty` is the possible cause of the failure. The `Update` of deployment failed and then caused the command to fail.

**Comment by nikhiljindal** [comment]
I dont know what the exact bug is but I was able to get ./hack/test-cmd.sh pass by changing the line here https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/deployment_controller.go#L684 to return existingNewRS instead of what Update() returns.

The update client code looks fine to me.

I am not sure why the issue came up with this PR. @wojtek-t Is your PR expected to affect Update behavior?

**Comment by smarterclayton** [comment]
The PR will *not* dispatch duplicate watch events, where before it
might (controllers were particularly vulnerable).  Someone developing
a controller might have miscalculated the exact event stream coming
out of a watch, because an event was sent twice instead of once, for
example. I would expect this change to expose more races or watch
gaps.  Can't speak to the exact issue until i get in front of a
computer.

File: pkg/storage/etcd/etcd_helper.go (hunk 7 above)
Comment (lavalamp) [inline pkg/storage/etcd/etcd_helper.go]: I'm fine with punting on a self link fix. That'd only be a problem with objects available from multiple URLs, and we won't have many for 1.2.

**Comment by lavalamp** [comment]
LGTM when the tests are all green.

**Comment by lavalamp** [comment]
@nikhiljindal That seems pretty weird-- can you dig in a bit more? Like what is the difference between the problematic and OK items that function returns?

**Comment by smarterclayton** [comment]
Lgtm as wel

**Comment by nikhiljindal** [comment]
The problematic item (replicaSet) only has the selfLink set. Everything else is blank.

**Comment by wojtek-t** [comment]
@nikhiljindal @janetkuo - can you please link the PR that is supposed to fix it?

**Comment by nikhiljindal** [comment]
I have exported the change that fixed it for me at https://github.com/kubernetes/kubernetes/pull/21054.

It is still not clear to me why your change breaks it in the first place.

You can maybe include that change in your PR as a temporary fix and verify that all tests pass.

cc @madhusudancs who might have an idea since he is working on replica sets.

**Comment by wojtek-t** [comment]
OK - I managed to finally debug it (thanks @nikhiljindal for PR that exposed the real issue).
BTW - this was "always there bug" - this change only exposed it to be more frequent.
I've already fix it - (lines 611-614 in etcd_helper.go)

@lavalamp @smarterclayton - PTAL

File: pkg/storage/etcd/etcd_helper.go [hunk 9]
```diff
@@ -580,7 +608,10 @@ func (h *etcdHelper) GuaranteedUpdate(ctx context.Context, key string, ptrToType
 		}
 
 		if string(data) == origBody {
-			return nil
+			// If we don't send an update, we simply return the currently existing
```
Comment (smarterclayton) [inline pkg/storage/etcd/etcd_helper.go]: Ah, yes.   Can you add a test case for this condition so we don't regress?

Comment (smarterclayton) [inline pkg/storage/etcd/etcd_helper.go]: I can't tell if you added one or not.

Comment (wojtek-t) [inline pkg/storage/etcd/etcd_helper.go]: No I didn't. I will add tomorrow.
@smarterclayton Are you fine with me self-applying "lgtm" label after adding a test?

**Comment by smarterclayton** [comment]
This is LGTM after one more test is added (for the update outputs empty), you can self apply.  Thanks for tracking this down!

File: pkg/storage/etcd/etcd_helper.go (hunk 9 above)
Comment (lavalamp) [inline pkg/storage/etcd/etcd_helper.go]: Yeah, a test for this would be good--subtle problem.

**Comment by lavalamp** [comment]
Yeah, self-LGTM after you add a test. Thanks for the fix!

**Comment by bgrant0607** [comment]
cc @madhusudancs

**Comment by wojtek-t** [comment]
I've just added test for the fix (returning non-empty object in case of no-up updates).
Will self-apply lgtm label on green (based on comments above).

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please github issue: #21188
