### PR TITLE
Fix for issue #22932 infinite pod restarts with CNI

### LINKED ISSUE #22932: Pods not starting on Kubernetes 1.2-beta.1 with CNI
We have been running a Kube cluster on 1.2-alpha.7 for quite a while with no problems.
Now trying to upgrade to Kube 1.2-beta.1 the pods end up in a restart loop and never come online.
The upgrade is done via a complete reinstall of OS and Kubernetes and the issue has been recreated several times by upgrading and downgrading between alpha.7 and beta-1

OS: Centos 7.2
Docker: 1.9.1
Kube version: 1.2-beta.1
CNI Provider: calico cni 1.1.0 / calicoctl: 0.17.0

kubectl --namespace=kube-system get pod -o wide

```
NAME                     READY     STATUS    RESTARTS   AGE       NODE
kube-dns-v10-0nh1i       3/4       Running   68         20m       srv07
kube-dns-v10-vfj6d       3/4       Running   60         20m       srv05
kube-registry-v0-m0or6   1/1       Running   44         20m       srv05
kube-ui-v5-gxs27         1/1       Running   197        20m       srv04
```

kubectl get events for one pod
```
 FirstSeen	LastSeen	Count	From			SubobjectPath			Type		Reason			Message
  ─────────	────────	─────	────			─────────────			────────	──────			───────
  11m		10m		5	{default-scheduler }					Warning		FailedScheduling	no nodes available to schedule pods
  10m		10m		1	{default-scheduler }					Normal		Scheduled		Successfully assigned kube-dns-v10-0nh1i to srv07
  10m		10m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Pulling			pulling image "gcr.io/google_containers/etcd:2.0.9"
  10m		10m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Pulled			Successfully pulled image "gcr.io/google_containers/etcd:2.0.9"
  10m		10m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Created			Created container with docker id 3efd24477ee2
  10m		10m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Started			Started container with docker id 3efd24477ee2
  10m		10m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Pulling			pulling image "gcr.io/google_containers/kube2sky:1.12"
  10m		10m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Pulled			Successfully pulled image "gcr.io/google_containers/kube2sky:1.12"
  10m		10m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Created			Created container with docker id f6ce0663c34b
  10m		10m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Started			Started container with docker id f6ce0663c34b
  10m		10m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Pulling			pulling image "gcr.io/google_containers/skydns:2015-10-13-8c72f8c"
  9m		9m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Pulled			Successfully pulled image "gcr.io/google_containers/skydns:2015-10-13-8c72f8c"
  9m		9m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Created			Created container with docker id bf3ecc042ffd
  9m		9m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Started			Started container with docker id bf3ecc042ffd
  9m		9m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Pulling			pulling image "gcr.io/google_containers/exechealthz:1.0"
  9m		9m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Pulled			Successfully pulled image "gcr.io/google_containers/exechealthz:1.0"
  9m		9m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Created			Created container with docker id 28a0783cf48f
  8m		8m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Started			Started container with docker id 28a0783cf48f
  8m		8m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Killing			Killing container with docker id bf3ecc042ffd: Need to kill pod.
  8m		8m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Killing			Killing container with docker id f6ce0663c34b: Need to kill pod.
  8m		8m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Killing			Killing container with docker id 28a0783cf48f: Need to kill pod.
  8m		8m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Killing			Killing container with docker id 3efd24477ee2: Need to kill pod.
  8m		8m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Created			Created container with docker id f37dd5c64348
  8m		8m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Started			Started container with docker id f37dd5c64348
  8m		8m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Created			Created container with docker id bf2c1a408754
  8m		8m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Started			Started container with docker id bf2c1a408754
  8m		8m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Created			Created container with docker id 0668fa66b8f7
  8m		8m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Started			Started container with docker id 0668fa66b8f7
  8m		8m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Created			Created container with docker id 739e3f9c828d
  7m		7m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Started			Started container with docker id 739e3f9c828d
  7m		7m		1	{kubelet srv07}		spec.containers{etcd}		Normal		Killing			Killing container with docker id f37dd5c64348: Need to kill pod.
  7m		7m		1	{kubelet srv07}		spec.containers{healthz}	Normal		Killing			Killing container with docker id 739e3f9c828d: Need to kill pod.
  7m		7m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Killing			Killing container with docker id bf2c1a408754: Need to kill pod.
  7m		7m		1	{kubelet srv07}		spec.containers{skydns}		Normal		Killing			Killing container with docker id 0668fa66b8f7: Need to kill pod.
  7m		7m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Created			Created container with docker id b208af539d35
  7m		7m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Started			Started container with docker id b208af539d35
  6m		6m		1	{kubelet srv07}		spec.containers{kube2sky}	Normal		Killing			Killing container with docker id b208af539d35: Need to kill pod.
```

journalctl -xn 200 -u kubelet  (kubelet running with -v=5)

I can't see anything weird in the logs for the API Server, Scheduler or Controller Manager

### PR DESCRIPTION
**Pull request by tobad357**
This fixes an [issue](https://github.com/kubernetes/kubernetes/issues/22932) when using CNI where the hash of a Container object will differ between creation and change checks due to the docker image exporting ports.
We make sure the Container generated in [DockerManager. podInfraContainerChanged](https://github.com/kubernetes/kubernetes/blob/bc62096ad5ea8ce15156b39cfd2333bc6f589905/pkg/kubelet/dockertools/manager.go#L805) uses the same logic as in [DockerManager. createPodInfraContainer](https://github.com/kubernetes/kubernetes/blob/bc62096ad5ea8ce15156b39cfd2333bc6f589905/pkg/kubelet/dockertools/manager.go#L1584) when it comes to adding Dockers own exported ports

Fixes #22932

### CODE REVIEW

**Comment by bgrant0607** [comment]
@tobad357 Please add a description of the problem and solution to the PR. Reference the original issue.
Notify relevant people.
cc @kubernetes/sig-network

**Comment by bgrant0607** [comment]
cc @dcbw @yifan-gu who touched this code

File: pkg/kubelet/dockertools/manager.go [hunk 1]
```diff
@@ -807,7 +807,7 @@ func (dm *DockerManager) podInfraContainerChanged(pod *api.Pod, podInfraContaine
 			glog.V(4).Infof("host: %v, %v", pod.Spec.SecurityContext.HostNetwork, networkMode)
 			return true, nil
 		}
-	} else {
+	} else if dm.networkPlugin.Name() != "cni" || dm.networkPlugin.Name() != "kubenet" {
```
Comment (bgrant0607) [inline pkg/kubelet/dockertools/manager.go]: This is always going to be true.

Comment (bgrant0607) [inline pkg/kubelet/dockertools/manager.go]: Please test without CNI also.

**Comment by bgrant0607** [comment]
cc @eparis

**Comment by bgrant0607** [comment]
ok to test

File: pkg/kubelet/dockertools/manager.go (hunk 1 above)
Comment (tobad357) [inline pkg/kubelet/dockertools/manager.go]: Argh, Fix for this coming shortly, copy paste error due to faulty rebase of upstream and rebuilding my build env. It should be &&

Comment (bgrant0607) [inline pkg/kubelet/dockertools/manager.go]: Needs to be `&&`, not `||`.

Please add a comment, similar to PR description

Comment (tobad357) [inline pkg/kubelet/dockertools/manager.go]: Sorry, A comment at the end of the PR or on the row changed?

**Comment by bgrant0607** [comment]
#20578 was cherrypicked by PR #22710

**Comment by bgrant0607** [comment]
@tobad357 Please squash

**Comment by tobad357** [comment]
@bgrant0607 Squashed

**Comment by bgrant0607** [comment]
If this merges soonish, I'm fine with cherrypicking it and cutting the release after the cherrypick.
cc @david-mcmahon @eparis @thockin

**Comment by eparis** [comment]
@dcbw can you take a look?

**Comment by ncdc** [comment]
If this gets merged ASAP, could you please plan to do a follow-up PR with a unit test for this?

**Comment by tobad357** [comment]
@ncdc shouldn't be a problem but will take a little while as got some other work  things that have to take priority
Only rushed to patch as need 1.2 in production :)

**Comment by thockin** [comment]
Interesting catch.  @freehan This re-raises the issue of the intersection of hostports and plugins.

LGTM

**Comment by dcbw** [comment]
Patch looks legit, but I'd rather consolidate creation of the api.Container for the podInfraContainer into a separate function so we don't have to sprinkle magic in different places.  How about something more like https://github.com/dcbw/kubernetes/commit/243007c6ac2c8bdaa45841c0035054ab8e21c01c ?

**Comment by dcbw** [comment]
@thockin yes, it does; and there's some discussion of that upstream in CNI already but that needs to move forward more.  I also looked into whether docker would expose ports even if net=none a while back and it wasn't exactly clear.

**Comment by thockin** [comment]
This change LGTM, and for expediency we should let it merge.  @dcbw your patch is a refinement of this, and also LGTM, and we can merge that to head only or even cherry-pick it to 1.2 later.

**Comment by dcbw** [comment]
@thockin OK, I'll open up an actual PR for my patch and rebase on this one after it gets merged then.

**Comment by tobad357** [comment]
@dcbw Your code looks much better for me. I had the same concern re sprinkling magic around but due to not knowing the code and the short timeframe I went with the one liner.
Thanks!

**Comment by thockin** [comment]
@bgrant0607 @eparis are cherry-pick procedures for 1.2 - same as previous releases?

**Comment by eparis** [comment]
get it merged, brian and I will get it picked to 1.2

**Comment by david-mcmahon** [comment]
Are we waiting for this PR for the 1.2.0 release?

**Comment by eparis** [comment]
I'm going to merge by hand and get prepped, in case brian wants it.

**Comment by bgrant0607** [comment]
Thanks @eparis

**Comment by bgrant0607** [comment]
Sorry, yes, @david-mcmahon @eparis, I do want to cherrypick this. Hopefully it's the last PR.

**Comment by bgrant0607** [comment]
Cherrypick has been merged.
