### PR TITLE
Fix computing of cpu nano core usage

### LINKED ISSUE #74667: Divide by zero panic in getContainerUsageNanocores
Kubelet panic with the following error:

```
panic: runtime error: integer divide by zero

goroutine 248 [running]:
k8s.io/kubernetes/pkg/kubelet/stats.(*criStatsProvider).getContainerUsageNanoCores(0xc000235560, 0xc00130ebc0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/stats/cri_stats_provider.go:548 +0x1a5
k8s.io/kubernetes/pkg/kubelet/stats.(*criStatsProvider).makeContainerStats(0xc000235560, 0xc00130ebc0, 0xc000cf4a20, 0xc0000b9800, 0xc0016d0fd8, 0xc000d330e0, 0x24, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/stats/cri_stats_provider.go:454 +0x259
k8s.io/kubernetes/pkg/kubelet/stats.(*criStatsProvider).ListPodStats(0xc000235560, 0x2e3628b, 0xc000235560, 0xc000ec0af0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/stats/cri_stats_provider.go:160 +0x85d
k8s.io/kubernetes/pkg/kubelet/server/stats.(*summaryProviderImpl).Get(0xc0002da8c0, 0xc000158d01, 0xc000ee4528, 0x1, 0x1)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/summary.go:86 +0x41f
k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).synchronize(0xc000371600, 0x413ee20, 0xc000902f00, 0xc000839ac0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go:241 +0x128
k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).Start.func2(0xc000371600, 0x413ee20, 0xc000902f00, 0xc000839ac0, 0xc000839ad0, 0x2540be400)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go:186 +0x60
created by k8s.io/kubernetes/pkg/kubelet/eviction.(*managerImpl).Start
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go:184 +0x1f9
```

The relevant lines are this: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/stats/cri_stats_provider.go#L547-L548

Basically, this value:

`nanoSeconds := stats.Cpu.Timestamp - cached.Timestamp`

can, in some conditins, be 0

**Environment**:
- Build from master ( v1.15.0-alpha.0.327+139a13d312b1b1 ):
- Cloud provider or hardware configuration: Azure
- OS: Windows Server 2019
- Others: Issue was observed while running conformance tests on Windows Clusters.

### PR DESCRIPTION
**Pull request by yujuhong**
CRI runtimes do not supply cpu nano core usage as it is not part of CRI
stats. However, there are upstream components that still rely on such
stats to function. The previous fix was faulty because the multiple
callers could compete and update the stats, causing
inconsistent/incoherent metrics. This change, instead, creates a
separate call for updating the usage, and rely on eviction manager,
which runs periodically, to trigger the updates. The caveat is that if
eviction manager is completley turned off, no one would compute the
usage.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #74667

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/kubelet/stats/cri_stats_provider.go [hunk 1]
```diff
@@ -541,27 +572,63 @@ func (p *criStatsProvider) makeContainerCPUAndMemoryStats(
...
+			// Cannot compute the usage now, but update the cached stats anyway
+			p.cpuUsageCache[id] = &cpuUsageRecord{stats: stats.Cpu, usageNanoCores: nil}
+			return nil, nil
+		}
+
+		newStats := stats.Cpu
+		cachedStats := cached.stats
+		nanoSeconds := newStats.Timestamp - cachedStats.Timestamp
+		if nanoSeconds <= 0 {
+			return nil, fmt.Errorf("zero or negative interval (%v - %v) ", cachedStats.Timestamp, newStats.Timestamp)
```
Comment (neolit123) [inline pkg/kubelet/stats/cri_stats_provider.go]: `(%v - %v) ", newStats.Timestamp, cachedStats.Timestamp)`

File: pkg/kubelet/stats/cri_stats_provider.go [hunk 2]
```diff
@@ -541,27 +572,63 @@ func (p *criStatsProvider) makeContainerCPUAndMemoryStats(
...
+		// Update cache with new value.
+		usageToUpdate := usageNanoCores
+		p.cpuUsageCache[id] = &cpuUsageRecord{stats: newStats, usageNanoCores: &usageToUpdate}
+
+		return &usageNanoCores, nil
+	}()
+
+	if err != nil {
+		// This should not happen. Log now to raise visiblity
+		klog.Errorf("failed updating cpu usage nano core: %v ", err)
```
Comment (neolit123) [inline pkg/kubelet/stats/cri_stats_provider.go]: extra space after `%v`

**Review by neolit123 — COMMENTED** [review]
thanks a lot for looking into this @yujuhong 
found a couple of minor nits.

i still have the concern that we have reduced precision on Windows, but let's see it it's not a problem.

@adelina-t do you think you will be able to test this patch by building a custom kubelet?

```
wget https://github.com/kubernetes/kubernetes/pull/74933.diff && git apply 74933.diff
KUBE_BUILD_PLATFORMS=windows/amd64 make all WHAT=cmd/kubelet
# result should be at '_output/local/bin/windows/amd64/kubelet.exe'
# 'git reset --hard HEAD' to remove the patch
```

**Review by michmike — APPROVED** [review]
/LGTM 
fix the couple of nits that were pointed out and this is good

**Comment by michmike** [comment]
/hold
remove once the nits are fixed

**Review by feiskyer — COMMENTED** [review]
Thanks for fixing the issue. LGTM

**Comment by adelina-t** [comment]
This LGTM. 

I'm currently (still ) running tests on this fix to see how it behaves. I would like another couple of runs on it to confirm it's ok.

@yujuhong , did you ran this one in gce ci ?

**Comment by benmoss** [comment]
Performance of the `/stats/summary` endpoint is pretty bad compared to Linux, but not sure if that's important. This does definitely fix the panic issue. Usage during the load test was consistently low.

Linux:
```
$ siege -r 50 -c10 10.74.41.135:10255/stats/summary
** SIEGE 4.0.4
** Preparing 10 concurrent users for battle.
The server is now under siege...
Transactions:                    500 hits
Availability:                 100.00 %
Elapsed time:                   5.88 secs
Data transferred:               7.68 MB
Response time:                  0.11 secs
Transaction rate:              85.03 trans/sec
Throughput:                     1.31 MB/sec
Concurrency:                    9.10
Successful transactions:         500
Failed transactions:               0
Longest transaction:            1.16
Shortest transaction:           0.09
```

Windows:
```
$ siege -r 50 -c10 10.74.41.136:10255/stats/summary
** SIEGE 4.0.4
** Preparing 10 concurrent users for battle.
The server is now under siege...
Transactions:                    500 hits
Availability:                 100.00 %
Elapsed time:                 100.14 secs
Data transferred:               1.36 MB
Response time:                  2.00 secs
Transaction rate:               4.99 trans/sec
Throughput:                     0.01 MB/sec
Concurrency:                   10.00
Successful transactions:         500
Failed transactions:               0
Longest transaction:            2.04
Shortest transaction:           1.25
```

**Comment by neolit123** [comment]
this is an actual bug in the logs:
https://github.com/kubernetes/kubernetes/pull/74933#discussion_r262341003

but other than that and unless there are objections by SIG Node, we are good to go here.
@kubernetes/sig-node-pr-reviews

File: pkg/kubelet/stats/cri_stats_provider.go (hunk 1 above)
Comment (yujuhong) [reply pkg/kubelet/stats/cri_stats_provider.go]: I was simply printing the interval "start to finish", but you made a point since this looks like a minus sign :-| 
Swapped the order.

File: pkg/kubelet/stats/cri_stats_provider.go (hunk 2 above)
Comment (yujuhong) [reply pkg/kubelet/stats/cri_stats_provider.go]: Done.

**Comment by yujuhong** [comment]
> @yujuhong , did you ran this one in gce ci ?

Our CI job tracks the master branch right now, so not yet. I manually tested and see no kubelet crash, and also `kubectl top pods` reporting meaningful numbers.

**Comment by adelina-t** [comment]
@yujuhong 

> Our CI job tracks the master branch right now, so not yet. I manually tested and see no kubelet crash, and also kubectl top pods reporting meaningful numbers.

Yeah, I was thinking manual runs :) I have jobs running as we speak, seeing consistent runs as well, but haven't seen logs.

**Comment by dashpole** [comment]
This should work well, and is as clean a way of implementing something like this as I think we will find.  Ill expand on @yujuhong comment above to document it here.

The eviction manager does not run if:

* The list of hard eviction thresholds is explicitly set to empty
* No soft eviction thresholds are set
* The feature gate --LocalStorageCapacityIsolation is explicitly disabled.

/lgtm

**Comment by yujuhong** [comment]
> Performance of the `/stats/summary` endpoint is pretty bad compared to Linux, but not sure if that's important. This does definitely fix the panic issue. Usage during the load test was consistently low.

@benmoss could you help file an issue about the performance for future reference? Thanks!


@dashpole thanks for reviewing. 

/hold cancel

**Comment by yujuhong** [comment]
> i still have the concern that we have reduced precision on Windows, but let's see it it's not a problem.

The reduced precision should not cause problems with the current interval (updating every 10s), but it's worth more investigation in the future. 
@neolit123 could you file an issue summarizing your findings, so that we can come back and look at them later? Thanks!

**Comment by neolit123** [comment]
> @neolit123 could you file an issue summarizing your findings, so that we can come back and look at them later? Thanks!

sure, here it is:
https://github.com/kubernetes/kubernetes/issues/74999

File: pkg/kubelet/stats/cri_stats_provider.go [hunk 3]
```diff
@@ -541,27 +572,63 @@ func (p *criStatsProvider) makeContainerCPUAndMemoryStats(
...
+		// Update cache with new value.
+		usageToUpdate := usageNanoCores
+		p.cpuUsageCache[id] = &cpuUsageRecord{stats: newStats, usageNanoCores: &usageToUpdate}
+
+		return &usageNanoCores, nil
+	}()
+
+	if err != nil {
+		// This should not happen. Log now to raise visiblity
+		klog.Errorf("failed updating cpu usage nano core: %v", err)
```
Comment (tedyu) [inline pkg/kubelet/stats/cri_stats_provider.go]: Should nil be returned in this case ?

**Comment by SleepyBrett** [comment]
Is this going to get cherry picked back into the 1.13 and others?

**Comment by mattjmcnaughton** [comment]
> Is this going to get cherry picked back into the 1.13 and others?

I think that's a good idea :) I answered in your issue.

**Comment by SleepyBrett** [comment]
Didn't seem to fix my problem on 1.14.1
