### PR TITLE
kubeadm: fix a bug where the static pod changes detection logic is inconsistent with kubelet

### LINKED ISSUE #2877: Kubeadm upgrade stuck in "Static pod: etcd-xxxx hash: xxxx" occasionally
### What happened?

We encountered this error when running kubeadm upgrade apply, the logs of kubeadm printed "Static pod: etcd-xxxx hash: xxxx" repeatedly till timeout.

### What did you expect to happen?

We were trying to keep some of the modifications in static pods' yaml while upgrading k8s. Our strategy is:
1. Keep a copy of original static pods' yaml in cluster using configmap when deploy the cluster.
2. When upgrading k8s, make a diff of current static pods' yaml and the saved copies in cluster, store them in yaml files.
3. Call "kubeadm upgrade apply" with param "--patches" to upgrade k8s components.
We suppose that these operations should work.

### How can we reproduce it (as minimally and precisely as possible)?

If the order of a map's fields are different between current static pods' yaml and the diff patch files, the problem will occur. e.g. if current etcd yaml has some annotations like:
metadata:
  annotations:
    field1: foo1
    field2: foo2
and the patch file we created is:
metadata:
  annotations:
    field2: foo2
    field1: foo1
the upgrade will stuck and failed.

### Anything else we need to know?

Since map is unordered in golang, we didn't expected this behavior of kubeadm.
By looking into the source code of kubeadm, we found the possible cause of this behavior, the current procedures of kubeadm upgrading static pods are as below(using etcd as an example):
1. Make a hash of current etcd yaml 
2. Make a new yaml and patch it if "--patches" exists
3. Compare if new yaml and old yaml are the same, if not, move new yaml to manifest and wait.
4. Repeatedly get pod hash from cluster, if the hash has changed, means the pod has upgraded successfully.
The problem of this process is, kubeadm uses DeepHashObject in pkg/util/hash to generate hash code, this hash method will sort the fileds, which means the two yaml files like above will leads to a same hash code. Meanwhile, when compare yaml files, kubeadm simply comprares the files' bytes instead, see in: https://github.com/kubernetes/kubernetes/blob/bc41f37e85dd67ddb69eaa9e4da530c3c72101d7/cmd/kubeadm/app/util/staticpod/utils.go#L352
In this case, kubeadm will replace the new yaml file to /etc/kubernetes/manifests, but the hash code of the pod won't make any difference.

### Kubernetes version

<details>

```console
$ kubeadm version
# v1.22.1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
kubeadm: fix a bug where the static pod changes detection logic is inconsistent with kubelet

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/2877

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: fix a bug where the static pod changes detection logic is inconsistent with kubelet
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/util/staticpod/utils_test.go [hunk 1]
```diff
@@ -630,6 +630,35 @@ spec:
...
+kind: Pod
+metadata:
+  labels:
+    tier: control-plane
+    component: etcd
+  name: etcd
+  namespace: kube-system
+spec:
+  containers:
+  - image: gcr.io/google_containers/etcd-amd64:3.1.11
```
Comment (carlory) [inline cmd/kubeadm/app/util/staticpod/utils_test.go:644]: value  of the image is not equal to other

Comment (SataQiu) [reply cmd/kubeadm/app/util/staticpod/utils_test.go:644]: IMO, the manifest is just for test purpose, so the value is irrelevant.

**Review by neolit123 — COMMENTED** [review]
/lgtm
