### PR TITLE
assignQuota checks if the underlying medium supports quotas and if so setting it

### LINKED ISSUE #107272: After kubelet restart, quota monitoring doesn't work for old pods.
### What happened?

The log below was added by myself to see the `GetMetrics` duration for empty dir.

> 12月 31 17:57:25 daocloud kubelet[726129]: I1231 17:57:25.254428  726129 volume_stat_calculator.go:141] Volume metrics for "data-test": %!s(float64=10.651979472)
> 12月 31 17:57:56 daocloud kubelet[726129]: I1231 17:57:56.013285  726129 volume_stat_calculator.go:141] Volume metrics for "data-test": %!s(float64=0.010684603)
> 12月 31 17:58:52 daocloud kubelet[726129]: I1231 17:58:52.068963  726129 volume_stat_calculator.go:141] Volume metrics for "data-test": %!s(float64=10.820351649)
> 12月 31 17:59:41 daocloud kubelet[726129]: I1231 17:59:41.360989  726129 volume_stat_calculator.go:141] Volume metrics for "data-test": %!s(float64=0.006106497)

I have two pods in the node and one is created after kubelet restart, the other was created before kubelet restarted.

```
12月 31 18:09:07 daocloud kubelet[726129]: I1231 18:09:07.905869  726129 quota_linux_common_impl.go:130] runXFSQuotaCommand /sbin/xfs_quota -t /tmp/mounts1045325910 -P/dev/null -D/dev/null -x -f /var/lib/kubelet -c quota -p -N -n -v -b 1048590
12月 31 18:09:07 daocloud kubelet[726129]: I1231 18:09:07.908269  726129 quota_linux_common_impl.go:137] runXFSQuotaCommand output "/dev/sdc                403992 9007199254740992 9007199254740992   00 [--------] /var/lib/kubelet\n"
12月 31 18:09:07 daocloud kubelet[726129]: I1231 18:09:07.909155  726129 quota_linux_common_impl.go:130] runXFSQuotaCommand /sbin/xfs_quota -t /tmp/mounts516467224 -P/dev/null -D/dev/null -x -f /var/lib/kubelet -c quota -p -N -n -v -i 1048590
12月 31 18:09:07 daocloud kubelet[726129]: I1231 18:09:07.910827  726129 quota_linux_common_impl.go:137] runXFSQuotaCommand output "/dev/sdc                500002          0          0   00 [--------] /var/lib/kubelet\n"
[root@daocloud ~]#
[root@daocloud ~]# time repquota -P /var/lib/kubelet -s -v
*** Report for project quotas on device /dev/sdc
Block grace time: 7days; Inode grace time: 7days
                        Space limits                File limits
Project         used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
volume1048591 --    790M 8388608T 8388608T          1001k     0     0
volume1048590 --    395M 8388608T 8388608T           501k     0     0
#0        --    364K      0K      0K           1271     0     0

*** Status for project quotas on device /dev/sdc
Accounting: ON; Enforcement: ON
Inode: #131 (2 blocks, 2 extents)

```
Two volumes above are for empty dir.
You can see the log above, `1048591` volume is not called quota_linux_common_impl.go and `1048590` volume is called by 
quota_linux_common_impl.go.

### What did you expect to happen?

Both empty dir should be monitored by quota as the quota monitoring as LocalStorageCapacityIsolationFSQuotaMonitoring is enabled and the pquota is enabled.

```
/dev/sdc /var/lib/kubelet xfs defaults,pquota 0 0
```

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: pod-test
  namespace: default
spec:
  containers:
  - args:
    - "100000"
    command:
    - sleep
    image: nginx:1.14.2
    imagePullPolicy: IfNotPresent
    name: nginx
    volumeMounts:
    - name: data-test
      mountPath: /data/test/
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "3Gi"
  volumes:
  - name: data-test
    emptyDir:
       sizeLimit: "2Gi"
```
Create a pod as above and run `seq -w 1 100000 | xargs -I {} sh -c 'mkdir -p z/{}/{}/{}/{} && echo xxx > z/{}/{}/{}/{}/{}'` under /data/test of the pod to generate about 1.9G data.

If we add some log/metrics for volume stats, we can see that the `stats` of the empty dir will cost only about 100ms or less to get the disk usage of this empty dir. If using `du` to get the disk usage of the folder above, it would cost about 10s.

Restart the kubelet.

We can see the disk-usage-stat is not using the quota.

If you create another pod like above, the new pod would use the quota and the old one is using `du` to get disk usage.

### Anything else we need to know?

N/A

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
vsphere
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

$ uname -a
# Linux daocloud 4.18.0-147.el8.x86_64 #1 SMP Wed Dec 4 21:51:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
calico
</details>

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:
Fixes #107272
LocalStorageCapacityIsolationFSQuotaMonitoring is enabled.
After kubelet restart, the quota monitoring revert to use `du` for empty-dir.

#### Does this PR introduce a user-facing change?
```release-note
None
```

### CODE REVIEW

**Comment by pacoxu** [comment]
flake for #100112

**Comment by pacoxu** [comment]
/cc @dashpole @RobertKrawitz 
For https://github.com/kubernetes/enhancements/issues/1029 who are the feature owner and reviewer.

**Comment by pacoxu** [comment]
/priority important-soon
not urgent as this is not a beta feature.(Currently, it is alpha feature.)
/triage accepted

File: pkg/volume/emptydir/empty_dir.go [hunk 1]
```diff
@@ -286,22 +288,30 @@ func (ed *emptyDir) SetUpAt(dir string, mounterArgs volume.MounterArgs) error {
...
+	return err
+}
+
+// assignQuota checks if the underlying medium supports quotas and if so, sets
+func (ed *emptyDir) assignQuota(dir string, mounterSize *resource.Quantity) error {
+	if mounterSize != nil {
+		// Deliberately shadow the outer use of err as noted
+		// above.
+		hasQuotas, err := fsquota.SupportsQuotas(ed.mounter, dir)
+		klog.V(4).InfoS("TODO emptyDir.SetUpAt", "dir", dir, "err", err, "hasQuotas", hasQuotas)
```
Comment (dashpole) [inline pkg/volume/emptydir/empty_dir.go:302]: Fix/remove TODO

**Review by dashpole — COMMENTED** [review]
/lgtm

File: pkg/volume/emptydir/empty_dir.go (hunk 1 above)
Comment (pacoxu) [reply pkg/volume/emptydir/empty_dir.go]: Fixed

**Comment by pacoxu** [comment]
/assign @saad-ali @thockin
@sig-storage-approvers for approval
