### PR TITLE
Fix credential test by setting `AlwaysVerify` policy

### LINKED ISSUE #135703: Failure cluster [c9b0c83e...] E2eNode Suite [It] [sig-node] [FeatureGate:KubeletEnsureSecretPulledImages] failure on cri-o
##### Error text:

E2eNode Suite [It] [sig-node] Ensure Credential Pulled Images pulling images with credentials [FeatureGate:KubeletEnsureSecretPulledImages] [Beta] [Serial] IfNotPresent pod with invalid PullSecret cannot access previously pulled private image

```
[FAILED] Expected
    <*v1.ContainerStateRunning | 0xc00102c120>: 
        startedAt: "2025-11-27T04:41:44Z"
to be nil
In [It] at: k8s.io/kubernetes/test/e2e/common/node/runtime.go:346 @ 11/27/25 04:41:45.91

```
#### Recent failures:
[12/10/2025, 5:11:54 AM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-kubelet-serial-cri-o/1998696817377677312)
[12/10/2025, 5:02:55 AM ci-kubernetes-node-swap-fedora-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-fedora-serial/1998694803851710464)
[12/10/2025, 12:52:52 AM ci-kubernetes-node-swap-fedora-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-fedora-serial/1998631888729673728)
[12/9/2025, 8:52:54 PM ci-kubernetes-node-swap-fedora-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-fedora-serial/1998571490194231296)
[12/9/2025, 5:10:54 PM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-kubelet-serial-cri-o/1998515622048174080)

/kind failing-test

/sig node

#### Useful info

This is only failing on CRI-O lanes.

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

The test expects unauthorized pods to be blocked from accessing cached private images, but the default policy (NeverVerifyPreloadedImages) allows access to any image previously pulled by the kubelet.

Configure the kubelet to use `AlwaysVerify` policy for this test, which enforces credential checks for all images regardless of pull history.

#### Which issue(s) this PR is related to:

Fixes https://github.com/kubernetes/kubernetes/issues/135703

#### Special notes for your reviewer:

Failing test:
```
E2eNode Suite: [It] [sig-node] Ensure Credential Pulled Images pulling images with credentials [FeatureGate:KubeletEnsureSecretPulledImages] [Beta] [Serial] Never pod without PullSecret cannot access previously pulled private image
```

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

File: test/e2e_node/image_credential_pulls.go [hunk 1]
```diff
@@ -44,6 +45,11 @@ var _ = SIGDescribe("Ensure Credential Pulled Images", func() {
 		var testImage string
 		var testSecret *v1.Secret
 		var testNode string
+
+		tempSetCurrentKubeletConfig(f, func(ctx context.Context, initialConfig *kubeletconfig.KubeletConfiguration) {
```
Comment (stlaz) [inline test/e2e_node/image_credential_pulls.go:49]: I'd rather this test was testing at least the default policy, if not all.

If that's not currently possible, can you file an issue so that we add these tests and assign myself to it? I suspect we'd just have to purge the directory that stores the records about image pulls.

Comment (SergeyKanzhelev) [reply test/e2e_node/image_credential_pulls.go:49]: > I'd rather this test was testing at least the default policy, if not all.

should we merge this to fix failing tests first? I am all for expanding the coverage, but keeping grid green is also important. If there is an easy path forward, it can wait, if not - then tracking it separately may be a good idea as you suggested.

Do you have issues with proposed?

Comment (stlaz) [reply test/e2e_node/image_credential_pulls.go:49]: /hold cancel
sgtm
