### PR TITLE
kube-proxy: fix duplicate port opening

### LINKED ISSUE #107170: Warning "Can't open port nodePort" on a fresh cluster setup with kubeadm
### What happened?

I've been following the official docs for kubeadm and how to set up a new cluster. The cluster is up and running but I noticed warning events when creating node port services:

```
can't open port "nodePort for default/abcde:5678-8080" (:31594/tcp4), skipping it
listen tcp4 :31594: bind: address already in use
```

However, the node port does work (I see the output when accessing node ip:nodeport). Might it be related to something else than Kubernetes?

### What did you expect to happen?

There is no such warning event.

### How can we reproduce it (as minimally and precisely as possible)?

Set up a fresh cluster with kubeadm and then create a service of nodeport type.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

</details>

### Cloud provider

<details>
Hetzner cloud
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux worker-3 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
cloud-init
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
cni=cilium
csi=hetzner
</details>

### PR DESCRIPTION
**Pull request by tnqn**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

When nodePortAddresses is not specified for kube-proxy, it tried to open the node port for a NodePort service twice, triggered by IPv4ZeroCIDR and IPv6ZeroCIDR separately. The first attempt would succeed and the second one would always generate an error log like below:

```
proxier.go:1605] "can't open port, skipping it" err="listen tcp4 :31915: bind: address already in use" port={Description:nodePort for default/nginx IP: IPFamily:4 Port:31915 Protocol:TCP}
```

This patch fixes it by ensuring nodeAddresses of a proxier only contain the addresses for its IP family.

#### Which issue(s) this PR fixes:

Fixes #107170

#### Does this PR introduce a user-facing change?

```release-note
Fixed duplicate port opening in kube-proxy when "--nodeport-addresses" is empty
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/proxy/iptables/proxier.go [hunk 1]
```diff
@@ -975,6 +975,16 @@ func (proxier *Proxier) syncProxyRules() {
 	if err != nil {
 		klog.ErrorS(err, "Failed to get node ip address matching nodeport cidrs, services with nodeport may not work as intended", "CIDRs", proxier.nodePortAddresses)
 	}
+	// nodeAddresses may contain dual-stack zero-CIDRs if proxier.nodePortAddresses is empty.
```
Comment (aojea) [inline pkg/proxy/iptables/proxier.go:978]: I see `GetNodeAddresses` returns 2 zero addresses

https://github.com/kubernetes/kubernetes/blob/6ce612ef65c6ac67a7f67a1c12eec970c05a6c6f/pkg/proxy/util/utils.go#L199-L205

can we have the same issue with dual stack services?

Comment (tnqn) [reply pkg/proxy/iptables/proxier.go:978]: For each Proxier, the patch removes the other zero address from `nodeAddresses`, so the two Proxiers can open their own ports without conflict. I have tested it:
```
tcp        0      0 0.0.0.0:31915           0.0.0.0:*               LISTEN      1756224/kube-proxy
tcp6       0      0 :::31915                :::*                    LISTEN      1756224/kube-proxy
```

File: pkg/proxy/iptables/proxier.go [hunk 2]
```diff
@@ -1438,7 +1448,6 @@ func (proxier *Proxier) syncProxyRules() {
 
 	// Finally, tail-call to the nodeports chain.  This needs to be after all
 	// other service portal rules.
-	isIPv6 := proxier.iptables.IsIPv6()
 	for address := range nodeAddresses {
 		// TODO(thockin, m1093782566): If/when we have dual-stack support we will want to distinguish v4 from v6 zero-CIDRs.
```
Comment (aojea) [inline pkg/proxy/iptables/proxier.go:1452]: heh, @thockin comment is spot on :smile:

File: pkg/proxy/iptables/proxier.go [hunk 3]
```diff
@@ -975,6 +975,16 @@ func (proxier *Proxier) syncProxyRules() {
 	if err != nil {
 		klog.ErrorS(err, "Failed to get node ip address matching nodeport cidrs, services with nodeport may not work as intended", "CIDRs", proxier.nodePortAddresses)
 	}
+	// nodeAddresses may contain dual-stack zero-CIDRs if proxier.nodePortAddresses is empty.
+	// Ensure nodeAddresses only contains the addresses for this proxier's IP family.
```
Comment (aojea) [inline pkg/proxy/iptables/proxier.go:979]: yeah, this is the problem, we are not filtering by the ip family, but I think that this should be extended for all the IPs, not only the zero ones ...

File: pkg/proxy/iptables/proxier.go [hunk 4]
```diff
@@ -975,6 +975,16 @@ func (proxier *Proxier) syncProxyRules() {
...
+	isIPv6 := proxier.iptables.IsIPv6()
+	for addr := range nodeAddresses {
+		if utilproxy.IsZeroCIDR(addr) && isIPv6 == netutils.IsIPv6CIDRString(addr) {
+			// if any of the addresses is zero cidr of this IP family, non-zero IPs can be excluded.
+			nodeAddresses = sets.NewString(addr)
+			break
+		}
```
Comment (aojea) [inline pkg/proxy/iptables/proxier.go:986]:
```suggestion
		if isIPv6 != netutils.IsIPv6CIDRString(addr) {
			// filter all the addresses that doesn't match the proxy IP family
			nodeAddresses.Delete(addr)
		}
```

File: pkg/proxy/iptables/proxier.go (hunk 3 above)
Comment (tnqn) [reply pkg/proxy/iptables/proxier.go:979]: https://github.com/kubernetes/kubernetes/blob/7846bbbda0ab921de47292b79722dc7a5420e7c8/pkg/proxy/iptables/proxier.go#L1292 
As the above code declares, `nodeAddresses` is supposed to contain single IP family only, which is true for most cases as `proxier.nodePortAddresses` has been filtered by IP family, so `GetNodeAddresses` returns single IP family only in that case:
https://github.com/kubernetes/kubernetes/blob/7846bbbda0ab921de47292b79722dc7a5420e7c8/pkg/proxy/iptables/proxier.go#L291-L292

The exception is when `proxier.nodePortAddresses` is empty, it returns dual-stack zero-CIDRs, as the new comment explains.

Comment (aojea) [reply pkg/proxy/iptables/proxier.go:979]: ah, great, I saw the comment explaining that but didn't find where those addresses were actually filtered
Thanks

File: pkg/proxy/iptables/proxier.go (hunk 1 above)
Comment (aojea) [reply pkg/proxy/iptables/proxier.go:978]: awesome

File: pkg/proxy/iptables/proxier.go (hunk 4 above)
Comment (aojea) [reply pkg/proxy/iptables/proxier.go:986]: scratch this comment https://github.com/kubernetes/kubernetes/pull/107413#discussion_r780471673

**Comment by aojea** [comment]
/lgtm
/approve
Thank you very much

**Comment by pacoxu** [comment]
We met this problem in 1.23.3. Do we have a plan to backport it to 1.23?

**Comment by aojea** [comment]
> We met this problem in 1.23.3. Do we have a plan to backport it to 1.23?

I think that qualifies, any volunteer?

**Comment by tnqn** [comment]
@pacoxu @aojea done. https://github.com/kubernetes/kubernetes/pull/108294

**Comment by rahulonmars** [comment]
This happened to us for 1.22 also. Would we be backporting it to 1.22 ?

**Comment by aojea** [comment]
> This happened to us for 1.22 also. Would we be backporting it to 1.22 ?

@tnqn or anybody feel free to submit a backport to 1.22 and assign it to me for reviewing

**Comment by tnqn** [comment]
@rahulonmars I checked the issue shouldn't happen for 1.22 release as it was introduced by https://github.com/kubernetes/kubernetes/commit/4c64008181f9a1653c685a754bb77621bc560e84. I'm also unable to reproduce it with v1.22.0. Could you share the logs you have with 1.22? It may be a different issue.

**Comment by sinharaksh1t** [comment]
> > @rahulonmars I checked the issue shouldn't happen for 1.22 release as it was introduced by [4c64008](https://github.com/kubernetes/kubernetes/commit/4c64008181f9a1653c685a754bb77621bc560e84). I'm also unable to reproduce it with v1.22.0. Could you share the logs you have with 1.22? It may be a different issue.
> 
> Ohh okay. Below are the kube-proxy logs:
> 
> ```
> E0719 06:41:44.333930       1 server.go:621] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
> E0719 06:41:44.405015       1 proxier.go:1234] can't open "nodePort for abc-system/ofc-conn:ofc-conn" (:30633/tcp), skipping this nodePort: listen tcp4 :30633: bind: address already in use
> E0719 06:41:44.406724       1 proxier.go:1234] can't open "nodePort for ingress-nginx/ingress-nginx-lb:https-web" (:443/tcp), skipping this nodePort: listen tcp4 :443: bind: address already in use
> E0719 06:41:44.407017       1 proxier.go:1234] can't open "nodePort for ingress-nginx/ingress-nginx-lb:udp-amon" (:8211/udp), skipping this nodePort: listen udp4 :8211: bind: address already in use
> E0719 06:41:44.407911       1 proxier.go:1234] can't open "nodePort for ingress-nginx/ingress-nginx-lb:http-web" (:80/tcp), skipping this nodePort: listen tcp4 :80: bind: address already in use
> E0719 06:41:49.334305       1 server.go:621] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
> E0719 06:41:54.334638       1 server.go:621] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
> E0719 06:41:59.334993       1 server.go:621] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
> E0719 06:42:04.335314       1 server.go:621] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
> E0719 06:42:05.857888       1 proxier.go:1234] can't open "nodePort for abc-system/ofc-conn:ofc-conn" (:30633/tcp), skipping this nodePort: listen tcp4 :30633: bind: address already in use
> E0719 06:42:05.859377       1 proxier.go:1234] can't open "nodePort for ingress-nginx/ingress-nginx-lb:https-web" (:443/tcp), skipping this nodePort: listen tcp4 :443: bind: address already in use
> E0719 06:42:05.859701       1 proxier.go:1234] can't open "nodePort for ingress-nginx/ingress-nginx-lb:udp-amon" (:8211/udp), skipping this nodePort: listen udp4 :8211: bind: address already in use
> E0719 06:42:05.860516       1 proxier.go:1234] can't open "nodePort for ingress-nginx/ingress-nginx-lb:http-web" (:80/tcp), skipping this nodePort: listen tcp4 :80: bind: address already in use
> ^[E0719 06:42:09.335599       1 server.go:621] starting metrics server failed: listen tcp 127.0.0.1:10249: bind: address already in use
> E0719 06:42:10.271301       1 proxier.go:1234] can't open "nodePort for abc-system/ofc-conn:ofc-conn" (:30633/tcp), skipping this nodePort: listen tcp4 :30633: bind: address already in use
> E0719 06:42:10.272850       1 proxier.go:1234] can't open "nodePort for ingress-nginx/ingress-nginx-lb:https-web" (:443/tcp), skipping this nodePort: listen tcp4 :443: bind: address already in use
> E0719 06:42:10.273213       1 proxier.go:1234] can't open "nodePort for ingress-nginx/ingress-nginx-lb:udp-amon" (:8211/udp), skipping this nodePort: listen udp4 :8211: bind: address already in use
> E0719 06:42:10.274306       1 proxier.go:1234] can't open "nodePort for ingress-nginx/ingress-nginx-lb:http-web" (:80/tcp), skipping this nodePort: listen tcp4 :80: bind: address already in use```
> 
> 
> 
> One of the node for rabbitmq was unable to come up (was in CrashLoopBackOff), checked the kubeproxy on the same node where rabbitmq was assigned, got the above errors in log.
> 
> It happened thrice for us on the same node. If it helps, we are testing out by replacing that node and trying cluster creation again. I'll let you know if that suceeds.
> ```

Were you able to resolve this issue? We're using 1.22 as well and I'm facing the exact same issue. Did replacing the node and trying cluster creation help?

Fwiw, this issue only happened when we switched to using arm shaped nodes for the new cluster.
