### PR TITLE
[DRA] Fix unexpected errors on ResourceClaim strategy update

### LINKED ISSUE #134961: ResourceClaim strategy test miss the unexpected error check
### What happened?

According to the comment https://github.com/kubernetes/kubernetes/pull/134615#discussion_r2475964555 by @mortent, the assertion in `pkg/registry/resource/resourceclaimtemplate/strategy_test.go` doesn't catch situations where Validate unexpectedly returns errors.

Since tc.expectValidationError is an empty string in this situation, it will pass. It should check that if tc.expectValidationError is an empty string, the length of errs should be zero.

After adding the suggestion, I found a couple of errors reported including immutable fields from DRAConsumableCapacity and DRADeviceBindingConditions.

After fixing the immutable fields, I further encounter the error of drop field test cases in DRADeviceBindingConditions and it seems that the drop field function is not implemented yet.

### What did you expect to happen?

```
Test assertion should detect unexpected error (tc.expectValidationError="" but len(errs) != 0)
```

### How can we reproduce it (as minimally and precisely as possible)?

Add

```diff
                        if errs := strategy.Validate(ctx, obj); len(errs) != 0 {
+                               if tc.expectValidationError == "" {
+                                       t.Fatalf("unexpected error: %v", errs[0])
+                               }
                                assert.ErrorContains(t, errs[0], tc.expectValidationError, "the error message should have contained the expected error message")
                                return
                        }
```

and run the unit test.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by sunya-ch**
- Fix unexpected error (immutable field, constraint validation)

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

    - Fix setting distinctAttribute=nil when DRAConsumableCapacity is disabled
    - Add must have no error check when no error expected in strategy test
    - Update test case that causes unexpected errors

~~This PR corrects the matchesAttribute of distinctAttributeConstraint to use value instead of pointer and remove the following missing drop field implementation test in ResourceClaim strategy on DeviceBindingConditions: drop-fields-binding-conditions, drop-fields-binding-conditions-disable-feature-gate, drop-fields-binding-conditions-disable-binding-conditions-feature-gate~~ -> No longer valid, rebased.

#### Which issue(s) this PR is related to:

Fixes https://github.com/kubernetes/kubernetes/issues/134961

#### Does this PR introduce a user-facing change?

```release-note
- Fix setting distinctAttribute=nil when DRAConsumableCapacity is disabled
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/registry/resource/resourceclaimtemplate/strategy_test.go [hunk 1]
```diff
@@ -475,15 +477,19 @@ func TestClaimTemplateStrategyCreate(t *testing.T) {
...
+				features.DRAConsumableCapacity: tc.consumableCapacity,
 			})
 			strategy := NewStrategy(mockNSClient)
 
 			obj := tc.obj.DeepCopy()
 			strategy.PrepareForCreate(ctx, obj)
 			if errs := strategy.Validate(ctx, obj); len(errs) != 0 {
+				if tc.expectValidationError == "" {
+					t.Fatalf("unexpected error: %v", errs[0])
+				}
```
Comment (pohly) [inline pkg/registry/resource/resourceclaimtemplate/strategy_test.go:492]: This is what triggered this whole change. I agree that it is a gap.

All of the `pkg/registry/resource/*/strategy_test.go` files have it (copy-and-paste...). I checked some other API groups. At least the ones I looked at were fine because they don't have test cases with validation errors and thus always expect no errors.

You are fixing `resourceclaim` and `resourceclaimtemplate`. `deviceclass` and `resourceslice` are fine, but `devicetaintrule` isn't - can you also fix that one?

File: pkg/registry/resource/resourceclaim/strategy.go [hunk 2]
```diff
@@ -237,6 +237,7 @@ func dropDisabledStatusFields(newClaim, oldClaim *resource.ResourceClaim) {
 	dropDisabledDRAResourceClaimDeviceStatusFields(newClaim, oldClaim)
 	dropDisabledDRAAdminAccessStatusFields(newClaim, oldClaim)
 	dropDisabledDRAResourceClaimConsumableCapacityStatusFields(newClaim, oldClaim)
+	dropDeviceBindingConditionsFields(newClaim, oldClaim)
```
Comment (pohly) [inline pkg/registry/resource/resourceclaim/strategy.go:240]: Can you put this into a separate PR?

**Review by pohly — CHANGES_REQUESTED** [review]

File: pkg/registry/resource/resourceclaim/strategy.go (hunk 2 above)
Comment (sunya-ch) [reply pkg/registry/resource/resourceclaim/strategy.go:240]: @pohly Sure. I separated here: https://github.com/kubernetes/kubernetes/pull/134964. Will rebase on it once it merges.

File: pkg/registry/resource/resourceclaimtemplate/strategy_test.go (hunk 1 above)
Comment (sunya-ch) [reply pkg/registry/resource/resourceclaimtemplate/strategy_test.go:492]: @pohly Sure. But could you please help point me out the line? In devicetaintrule, I don't see the same issue where we pass the error message contains empty message condition when there is an unexpected error.

File: pkg/registry/resource/resourceclaim/strategy.go (hunk 2 above)
Comment (pohly) [reply pkg/registry/resource/resourceclaim/strategy.go:240]: Why does this PR depend on dropping binding condition fields? I don't see the connection.

Comment (sunya-ch) [reply pkg/registry/resource/resourceclaim/strategy.go:240]: @pohly After fixing this test, the current test case on dropping those fields are fail (the fields remain).

For more details, there are two issues. First issue that this PR fixes is the unexpected error from validation that the test case try to change immutable field (allocation from objWithStatus to objWithDeviceBindingConditions). Without this fix, the test case passes because it has unexpected error and get pass (len(errs)>0 and error contains empty string).
After I change from `objWithStatus` to `obj`, it has no longer unexpected error but then fails from unexpected obj (fields remain) instead.

File: pkg/registry/resource/resourceclaimtemplate/strategy_test.go (hunk 1 above)
Comment (pohly) [reply pkg/registry/resource/resourceclaimtemplate/strategy_test.go:492]: Oh, it's only broken in my current branch for https://github.com/kubernetes/kubernetes/pull/134152! I updated the strategy_test.go there to make it more complete and copied the mistake. I'll fix it in my PR before it gets merged.

File: pkg/registry/resource/resourceclaim/strategy_test.go [hunk 3]
```diff
@@ -630,6 +651,9 @@ func TestStrategyCreate(t *testing.T) {
 			obj := tc.obj.DeepCopy()
 			strategy.PrepareForCreate(ctx, obj)
 			if errs := strategy.Validate(ctx, obj); len(errs) != 0 {
+				if tc.expectValidationError == "" {
+					t.Fatalf("unexpected error: %v", errs[0])
+				}
```
Comment (pohly) [inline pkg/registry/resource/resourceclaim/strategy_test.go:635]:
```suggestion
				if tc.expectValidationError == "" {
					t.Fatalf("unexpected error(s): %v", errs)
				}
				assert.Len(t, errs, 1, "exactly one error expected")
```

Same in the other place.

File: pkg/api/resourceclaimspec/util.go [hunk 4]
```diff
@@ -135,9 +135,16 @@ func dropDisabledDRAResourceClaimConsumableCapacityFields(new, old *resource.Res
...
 	}
 
-	for _, constaint := range new.Devices.Constraints {
-		constaint.DistinctAttribute = nil
+	// Need to drop the entry of DistinctAttribute
+	// Constraint cannot be nil for both MatchAttribute and DistinctAttribute
+	var newConstraints []resource.DeviceConstraint
+	for _, constraint := range new.Devices.Constraints {
+		// Add only MatchAttribute (Drop DistinctAttribute)
+		if constraint.MatchAttribute != nil {
```
Comment (mortent) [inline pkg/api/resourceclaimspec/util.go]: Why not just set DistinctAttribute to nil here? So what I suggested in https://github.com/kubernetes/kubernetes/pull/134615#discussion_r2475964555? This should work too, but it just seems more complicated.

File: pkg/registry/resource/resourceclaim/strategy_test.go [hunk 5]
```diff
@@ -1588,41 +1609,26 @@ func addSpecDevicesRequest(resourceClaim *resource.ResourceClaim, request string
...
-		r.FirstAvailable = []resource.DeviceSubRequest{
-			{
-				Name:            testRequest,
-				DeviceClassName: class,
-				AllocationMode:  resource.DeviceAllocationModeExactCount,
-				Count:           1,
-			},
-		}
-	}
+func modifySpecDeviceRequestWithCapacityRequests(resourceClaim *resource.ResourceClaim,
```
Comment (mortent) [inline pkg/registry/resource/resourceclaim/strategy_test.go:1608]: Nit: Would it be easier to have a separate function for adding the Distinct attribute? It is a bit hard to know what happens in function with calls like `modifySpecDeviceRequestWithCapacityRequests(obj, nil, true, false)`. Not critical though.

**Review by mortent — COMMENTED** [review]
Agree with the comments from Patrick. Just a few other comments. Thanks for fixing this.

File: pkg/registry/resource/resourceclaim/strategy.go (hunk 2 above)
Comment (pohly) [reply pkg/registry/resource/resourceclaim/strategy.go:240]: Which test case case is failing? What is it meant to ensure? Sounds to me like it wants to verify behavior that wasn't implemented, in which case you can remove it here and add it back in https://github.com/kubernetes/kubernetes/pull/134964.

File: pkg/api/resourceclaimspec/util.go (hunk 4 above)
Comment (sunya-ch) [reply pkg/api/resourceclaimspec/util.go]: @mortent It is failing on validation that if constraints in not nil, either matchAttribute or distinctAttribute must be set so I cannot just set distinctAttribute (it will say matchAttribute need to be set).

File: pkg/registry/resource/resourceclaim/strategy_test.go (hunk 3 above)
Comment (sunya-ch) [reply pkg/registry/resource/resourceclaim/strategy_test.go:635]: @pohly I tried applying it but it seems that they are a couple of test cases that have more than one error occurs.

For example, 
```
        	Error:      	"[metadata.namespace: Invalid value: "default": field is immutable spec: Invalid value: {"Spec":{"Devices":{"Requests":[{"Name":"req-0","Exactly":null,"FirstAvailable":[{"Name":"subreq-0","DeviceClassName":"class","Selectors":null,"AllocationMode":"ExactCount","Count":1,"Tolerations":null,"Capacity":null}]}],"Constraints":null,"Config":null}}}: field is immutable]" should have 1 item(s), but has 2
        	Test:       	TestStrategyUpdate/keep-fields-prioritized-list
        	Messages:   	exactly one error expected
--- FAIL: TestStrategyUpdate/keep-fields-prioritized-list (0.00s)
```

Also, for
- TestStrategyUpdate/drop-fields-prioritized-list (has 3)
-  TestStatusStrategyUpdate/keep-fields-admin-access-NonAdminNamespace (has 2)

The namespace one I can fix.

- metadata.namespace: Invalid value: "default" -->  I notice you have some object already defined. I will use that.

There is one case left that I'm not sure how to deal with.

```
        	Error:      	"[spec.spec.devices.requests[0]: Required value: exactly one of `exactly` or `firstAvailable` is required spec: Invalid value: {"Spec":{"Devices":{"Requests":[{"Name":"req-0","Exactly":null,"FirstAvailable":null}],"Constraints":null,"Config":null}}}: field is immutable]" should have 1 item(s), but has 2
        	Test:       	TestStrategyUpdate/drop-fields-prioritized-list
        	Messages:   	exactly one error expected
--- FAIL: TestStrategyUpdate/drop-fields-prioritized-list (0.00s)
```

immutable one is always there. I guess because this test case try to change the request spec.

File: pkg/registry/resource/resourceclaim/strategy.go (hunk 2 above)
Comment (sunya-ch) [reply pkg/registry/resource/resourceclaim/strategy.go:240]: @pohly I have removed three test cases (also added to the description) from resourceclaim test.

```
drop-fields-binding-conditions
drop-fields-binding-conditions-disable-feature-gate
drop-fields-binding-conditions-disable-binding-conditions-feature-gate
```

Now this PR is independent from https://github.com/kubernetes/kubernetes/pull/134964.

cc: @KobayashiD27

File: pkg/registry/resource/resourceclaim/strategy_test.go (hunk 3 above)
Comment (sunya-ch) [reply pkg/registry/resource/resourceclaim/strategy_test.go:635]: I have changed the expected error to []string instead for resourceclaimtemplate updatestrategy check.

File: pkg/registry/resource/resourceclaim/strategy_test.go [hunk 6]
```diff
@@ -152,39 +152,6 @@ var objWithAdminAccessInNonAdminNamespace = &resource.ResourceClaim{
 	},
 }
 
-var objStatusInNonAdminNamespace = &resource.ResourceClaim{
```
Comment (sunya-ch) [inline pkg/registry/resource/resourceclaim/strategy_test.go:155]: @pohly  I have removed this variable because it is only being used for `keep-fields-admin-access-NonAdminNamespace` test case. And I have to change to oldObj to `objInNonAdminNamespace ` instead to remove extra immutable error ( from updating allocation ). Is it okay? Or should I also change this test case structure to support multiple errors and add the immutable error entry instead?

```
        	Error:      	"[status.allocation.devices.results[0].adminAccess: Forbidden: admin access to devices requires the `resource.kubernetes.io/admin-access: true` label on the containing namespace status.allocation: Invalid value: {"Devices":{"Results":[{"Request":"req-0","Driver":"dra.example.com","Pool":"pool-0","Device":"device-0","AdminAccess":true,"Tolerations":null,"BindingConditions":null,"BindingFailureConditions":null,"ShareID":null,"ConsumedCapacity":null}],"Config":null},"NodeSelector":null,"AllocationTimestamp":null}: field is immutable]" should have 1 item(s), but has 2
        	Test:       	TestStatusStrategyUpdate/keep-fields-admin-access-NonAdminNamespace
        	Messages:   	exactly one error expected
```

File: pkg/registry/resource/resourceclaim/strategy_test.go (hunk 5 above)
Comment (sunya-ch) [reply pkg/registry/resource/resourceclaim/strategy_test.go:1608]: I separate a function to set the distinctAttribute as suggested.

File: staging/src/k8s.io/dynamic-resource-allocation/structured/internal/experimental/constraint.go [hunk 7]
```diff
@@ -96,25 +96,25 @@ func (m *distinctAttributeConstraint) matchesAttribute(attribute resourceapi.Dev
 	for _, attr := range m.attributes {
 		switch {
 		case attribute.StringValue != nil:
-			if attr.StringValue != nil && attribute.StringValue == attr.StringValue {
+			if attr.StringValue != nil && *attribute.StringValue == *attr.StringValue {
```
Comment (pohly) [inline staging/src/k8s.io/dynamic-resource-allocation/structured/internal/experimental/constraint.go:99]: This looks like another bug fix. Can it be merged in a separate PR with corresponding unit tests in that package?

File: pkg/api/resourceclaimspec/util.go (hunk 4 above)
Comment (sunya-ch) [reply pkg/api/resourceclaimspec/util.go]: @pohly Do I need to move this fix to a separate PR too?

Comment (pohly) [reply pkg/api/resourceclaimspec/util.go]: Maybe. It all depends on how you would describe it - is it really part of "Fix strategy test with unexpected error" (i.e. a fix in the test code) or is it fixing some Kubernetes feature?

Comment (sunya-ch) [reply pkg/api/resourceclaimspec/util.go]: @pohly This one is only for fixing strategy test. Can I keep it here?

File: staging/src/k8s.io/dynamic-resource-allocation/structured/internal/experimental/constraint.go (hunk 7 above)
Comment (sunya-ch) [reply staging/src/k8s.io/dynamic-resource-allocation/structured/internal/experimental/constraint.go:99]: @pohly I have created a separated PR with test cases here:
- https://github.com/kubernetes/kubernetes/pull/135022

@mortent I also copy the test cases in https://github.com/kubernetes/kubernetes/pull/134615 about distinctAttributes which you found this bug to the same PR.

File: pkg/api/resourceclaimspec/util.go (hunk 4 above)
Comment (pohly) [reply pkg/api/resourceclaimspec/util.go]: The PR description make it look like this PR is fixing a test, and only a test. But this here is a functional change of validation code, probably a bug fix in it? Isn't that something that needs to be described as one?

We can fix it here, I'm just looking for an accurate description.

File: pkg/registry/resource/resourceclaim/strategy_test.go (hunk 6 above)
Comment (pohly) [reply pkg/registry/resource/resourceclaim/strategy_test.go:155]: No preference from me either way.

File: pkg/api/resourceclaimspec/util.go (hunk 4 above)
Comment (sunya-ch) [reply pkg/api/resourceclaimspec/util.go]: @pohly I'm sorry. It is not only for fixing the test. It is also fixing the issue when we need to drop the field when the feature is disabled too. I have updated the description to `[DRA] Fix unexpected validation error on ResourceClaim strategy update` to cover the update fix. Is it acceptable?

Comment (mortent) [reply pkg/api/resourceclaimspec/util.go]: So I think the most important change in this PR is the change in this file. And the problem isn't a validation error, but that the `DistinctAttribute` field did not get dropped when the Consumable Capacity feature gate is disabled. So I would describe that in the title.

The description is a bit hard to follow, so could we update the language a bit? Also, since this fixes a but, we should add a proper release note.

Thanks for clarifying my original question here. I understand why the current logic is needed.

**Review by mortent — COMMENTED** [review]
Other than the title and the description of the PR, this looks good to me.

File: pkg/api/resourceclaimspec/util.go (hunk 4 above)
Comment (sunya-ch) [reply pkg/api/resourceclaimspec/util.go]: @mortent  Thank you. I have updated the description in the code, the PR commit to cover this point, and the release note.

Comment (pohly) [reply pkg/api/resourceclaimspec/util.go]: "Fix removing out DistinctAttribute constraints when DRAConsumableCapacity feature is disabled"

is the point I was looking for. Resolved as far as I am concerned.

**Review by pohly — APPROVED** [review]
/lgtm

File: pkg/api/resourceclaimspec/util.go (hunk 4 above)
Comment (liggitt) [reply pkg/api/resourceclaimspec/util.go]: We don't remove items from lists when dropping fields. If the item is not valid without that attribute, then a validation error disallowing the request with that invalid item is expected.

The goal of the field dropping is to make the API server behave as much as possible like an API server prior to introduction of the field, and erroring on the invalid item is what a previous version API server would do.

Comment (liggitt) [reply pkg/api/resourceclaimspec/util.go]: The code prior to this PR looks correct to me. A validation error when submitting an object with an item in a list which is invalid without the gate-disabled field is expected.

Comment (sunya-ch) [reply pkg/api/resourceclaimspec/util.go]: @liggitt  Thank you. I have updated to set the distinctAttribute to nil and expect validation error instead. I also separate the test case dropping with and without the distinctAttribute.

File: pkg/registry/resource/resourceclaim/strategy_test.go [hunk 8]
```diff
@@ -738,7 +743,7 @@ func TestStrategyUpdate(t *testing.T) {
 			},
 		},
 		"drop-fields-prioritized-list": {
-			oldObj:                obj,
+			oldObj:                objWithAdminAccessInNonAdminNamespace,
```
Comment (pohly) [inline pkg/registry/resource/resourceclaim/strategy_test.go]: Replacing `obj` makes the tests look really odd, as in "what does drop-fields-prioritized-list have to do with objWithAdminAccessInNonAdminNamespace?"

Is this change really necessary?

Comment (sunya-ch) [reply pkg/registry/resource/resourceclaim/strategy_test.go]: @pohly The thing that causes an issue is the namespace as the obj has namespace `kube-system` but the objWithPrioritizedList has namespace `default`. I believe that `default` namespace is for non-admin namespace testing. Can I just change objWithPrioritizedList's namespace to `kube-system` and use obj instead or should I create a new simple object with default namespace.

Comment (pohly) [reply pkg/registry/resource/resourceclaim/strategy_test.go]: The only difference between `obj` and `objWithPrioritizedList` should be the addition of prioritized list fields. The namespace needs to be the same. In general, `obj` should be the "base" object for all test cases. The only objects with non-default namespace should be the objects explicitly set up to test admin access.

 I don't know when this went sideways, but let's fix it now.

Comment (sunya-ch) [reply pkg/registry/resource/resourceclaim/strategy_test.go]: @pohly Thank you for confirming. I fixed the namespace.

File: pkg/registry/resource/resourceclaimtemplate/strategy_test.go [hunk 9]
```diff
@@ -815,11 +825,15 @@ func TestStrategyUpdate(t *testing.T) {
 			newObj.ResourceVersion = "4"
 
 			strategy.PrepareForUpdate(ctx, newObj, oldObj)
+			expectedErrLen := len(tc.expectValidationErrors)
 			if errs := strategy.ValidateUpdate(ctx, newObj, oldObj); len(errs) != 0 {
-				assert.ErrorContains(t, errs[0], tc.expectValidationError, "the error message should have contained the expected error message")
+				assert.Len(t, errs, expectedErrLen, "exact number of errors expected")
+				for i, expectErr := range tc.expectValidationErrors {
+					assert.ErrorContains(t, errs[i], expectErr, "the error message should have contained the expected error message")
+				}
```
Comment (pohly) [inline pkg/registry/resource/resourceclaimtemplate/strategy_test.go]:
```suggestion
				if assert.Len(t, errs, expectedErrLen, "exact number of errors expected") {
					for i, expectErr := range tc.expectValidationErrors {
						assert.ErrorContains(t, errs[i], expectErr, "the error message should have contained the expected error message")
					}
				}
```

Don't compare the elements unless the length is the same, it would panic the test.

**Review by pohly — CHANGES_REQUESTED** [review]
Almost there...

File: pkg/registry/resource/resourceclaimtemplate/strategy_test.go (hunk 9 above)
Comment (pohly) [reply pkg/registry/resource/resourceclaimtemplate/strategy_test.go]: /lgtm
/hold

Feel free to lift the hold. A panic is still going to show up as a test failures, just not as a nice one.

Comment (sunya-ch) [reply pkg/registry/resource/resourceclaimtemplate/strategy_test.go]: @pohly Thank you. Applied your suggestion.
