### PR TITLE
Node port udp fast test

### LINKED ISSUE #95315: missing a non-Slow, targetted UDP NodePort test  in the sig-network testing suite
**What happened**:

In CAPA clusters, NodePorts are disabled for UDP but not for TCP, so when testing, we see a small hole in coverage that was luckily caught by the `Conntrack` tests....   So, I noticed that we thus don't have a targetted ginkgo test for UDP + nodeports, but we do seem to have the Contract one, which I guess tests two things at once:

- UDP NodePort service works
- Conntrack can persist the service

We **do** have

```
should be able to change the type and ports of a service [Slow] [DisabledForLargeClusters]
```
but this test is obviously testing many other things as well.

So, would like to have a `should verify that NodePort services work with UDP` test....

**What you expected to happen**:

running the sig-network test suite, while skipping `Slow` with UDP not working would result in a test failure specific to  UDP and NodePorts.

**How to reproduce it (as minimally and precisely as possible)**:

Run the `sig-network` test suite, skip `Conntrack|Slow`, with a UDP firewall up - you'll see no relevant failures. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master

### PR DESCRIPTION
**Pull request by jayunit100**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

We don't have a non-"Slow" UDP node port smoke test

**Which issue(s) this PR fixes**

Fixes #95315

-->
```release-note
NONE
```

### CODE REVIEW

File: test/e2e/network/networking.go [hunk 1]
```diff
@@ -345,6 +346,31 @@ var _ = SIGDescribe("Networking", func() {
 			}
 		})
 
+		// canCreateNodePortService is a helper function to validate nodeport functionality is working at a baseline.
+		canCreateNodePortService := func(proto string, config *network.NetworkingTestConfig, port int) error {
+			e2enetwork.NewNetworkingTestConfig(f, true, false)
+			ginkgo.By(fmt.Sprintf("dialing(http) %v (node) --> %v:%v (nodeIP) and getting ALL host endpoints", config.NodeIP, config.NodeIP, port))
+			return config.DialFromNode(proto, config.NodeIP, config.NodeHTTPPort, config.MaxTries, 0, config.EndpointHostnames())
```
Comment (jayunit100) [inline test/e2e/network/networking.go:352]: fixing this now...

**Comment by aojea** [comment]
@spiffxp what is the `[Slow]` tag history and criteria?
does it still applies?

File: test/e2e/network/networking.go [hunk 2]
```diff
@@ -321,39 +333,83 @@ var _ = SIGDescribe("Networking", func() {
...
 			err = config.DialFromTestContainer("udp", config.ClusterIP, e2enetwork.ClusterUDPPort, config.MaxTries, config.MaxTries, config.EndpointHostnames())
 			if err != nil {
-				framework.Failf("failed dialing endpoint, %v", err)
+				framework.Failf("failed dialing endpoint (recovery), %v", err)
+			}
+		})
+
+		// canCreateNodePortService is a helper function to validate nodeport functionality is working at a baseline, supports http/udp,
+		// this was added so that we can separate testing of XYZ updates from just plain old XYZ nodeport service functioning.
+		canCreateNodePortService := func(proto string, config *e2enetwork.NetworkingTestConfig) error {
```
Comment (aojea) [inline test/e2e/network/networking.go:350]: for e2e too much abstraction is a pain for debugging test failures, I'd rather prefer to copy and paste, in terms of LOC it seems the same number

Comment (jayunit100) [reply test/e2e/network/networking.go:350]: Counterpoint - positive controls should be declarative, unique functionality (the experiment that the test is measuring) should be imperative.

But if you feel strongly I can back this out and copy the code .  Still making coffee so Brain isn't fully powered yet :)

Comment (aojea) [reply test/e2e/network/networking.go:350]: tell me that once you spend 1 week trying to deflake an e2e test and found that someone refactored the function without knowing that affected the test ;)
e2e should be simple enough that anybody with a minimum level is able to look at it and fix/add new ones, this is not adding much value compared to add the lines in each test.

Comment (jayunit100) [reply test/e2e/network/networking.go:350]: ok i assume that you feel strongly then on this one :)

**Comment by jayunit100** [comment]
> @spiffxp what is the `[Slow]` tag history and criteria?
> does it still applies?

Its slow `Slow` in a theoretical sense, because its always going to be the "worst case scenario" for maxTries, which currently is 40.  Ginkgo will tag it as "Slow Test" as well, but that doesn't really mean much because Ginkgo thinks everything is slow :) 

Keep in mind maxTries is O(n^2), bc its calculated as
 
```
	config.MaxTries = epCount*epCount + testTries
```

This is another one of those "large clusters are special" tags. In a kind cluster you won't see this as slow (its a 2 minute test)... but on a real cluster you'll rapidly see it devolve.

File: test/e2e/network/networking.go (hunk 2 above)
Comment (jayunit100) [reply test/e2e/network/networking.go]: ok updated to c/p version

**Comment by jayunit100** [comment]
flake : 34 tests failed, pods weren't coming up,

**Comment by aojea** [comment]
I think that we can just remove the tag `Slow` based on the feedback received in slack, can' t we?

https://github.com/kubernetes/community/blob/5b8655717dbd11ccde87e1769466f57565b3dbfa/contributors/devel/sig-testing/e2e-tests.md#kinds-of-tests


> [Slow]: If a test takes more than five minutes to run (by itself or in parallel with many other tests), it is labeled [Slow]. This partition allows us to run almost all of our tests quickly in parallel, without waiting for the stragglers to finish.

**Comment by jayunit100** [comment]
I don't think so -  it can be MUCH longer then 5 minutes if its running on a large cluster, i.e. you might estimate it could take an hour on a 100 node cluster ...  (10,000/60 ~ 150 minutes)
```
	config.MaxTries = epCount*epCount + testTries
```

**Comment by jayunit100** [comment]
So, 
```
epCount = # of nodes
``` 
so, 
```                    maxTries                 timeoutPerTry
totalTime = ---------------   *  
                       timeoutPerTry
timeoutPerTry=1 sec
maxTries=node^2
```
 implies that at 18 nodes, this function takes 5.4 minutes (`18*18/60=5.4`)...

**Comment by jayunit100** [comment]
ah , flake ? 

```
 Pods should be submitted and removed [NodeConformance] [Conformance] 
```

**Comment by aojea** [comment]
/lgtm
Nice investigation

**Review by spiffxp — APPROVED** [review]
/approve
/lgtm
