### PR TITLE
Fix unstable hack/update-codecgen.sh output

### LINKED ISSUE #16770: hack/update-codecgen.sh generating different output than verify-codecgen.sh at HEAD
From https://github.com/kubernetes/kubernetes/pull/16757#issuecomment-153537158 (which includes more details):

The output of the ugorji codecgen is varies depending on whether the dependencies' codecs have been generated. https://github.com/kubernetes/kubernetes/pull/16415 started deleting generating files before regenerating them, but without enforcing a dependency ordering.

My suggested fix is to define a dependency ordering in `hack/update-codecgen.sh` and follow the order when regenerating the files (after first deleting them). `hack/verify-codecgen.sh` will also need to be updated to match the same logic.

cc/ @lavalamp

### PR DESCRIPTION
**Pull request by wojtek-t**
FIx #16770

@lavalamp @timstclair

### CODE REVIEW

File: hack/verify-codecgen.sh [hunk 1]
```diff
@@ -45,6 +43,46 @@ function cleanup {
...
+number=${#generated_files[@]}
+for (( i=0; i<${number}; i++ )); do
+  visited[${i}]=false
+done
+result=""
+
+function depends {
+  file=${generated_files[$1]//\.generated\.go/.go}
+  deps=$(go list -f {{.Deps}} ${file} | tr "[" " " | tr "]" " ")
+  candidate=$(realpath ${generated_files[$2]//\.generated\.go/.go})
```
Comment (wojtek-t) [inline hack/verify-codecgen.sh]: It seems that realpath is not available in Travis. :(

Comment (wojtek-t) [inline hack/verify-codecgen.sh]: OK - I somehow worked around it.

**Comment by wojtek-t** [comment]
hmm - verify-godeps doesn't work for me at head

**Comment by wojtek-t** [comment]
@lavalamp @timstclair - can someone please explain me why it is trying to verify Godeps even if I'm not touching them?

**Comment by wojtek-t** [comment]
This is really annoying:

    diff -Naupr '--exclude=symlink' /home/travis/gopath/src/github.com/kubernetes/kubernetes/Godeps/_workspace/src/github.com/appc/cni/Godeps/_workspace/src/github.com/d2g/dhcp4/LICENSE /tmp/gopath.RSGMyR/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/appc/cni/Godeps/_workspace/src/github.com/d2g/dhcp4/LICENSE

Why it is even trying to compare:

    /home/travis/gopath/src/github.com/kubernetes/kubernetes/Godeps/_workspace/src/github.com/appc/cni/Godeps/_workspace/src/github.com/d2g/dhcp4/LICENSE

if we don't even have such directory in our Godeps?

File: hack/update-codecgen.sh [hunk 2]
```diff
@@ -41,6 +41,52 @@ function cleanup {
...
 trap cleanup EXIT
 
+# Sort all files in the dependency order.
+number=${#generated_files[@]}
+for (( i=0; i<${number}; i++ )); do
+  visited[${i}]=false
+done
+result=""
+
+function fullpath {
```
Comment (timstclair) [inline hack/update-codecgen.sh]: Does `readlink -f` not work? (http://stackoverflow.com/questions/17577093/how-do-i-get-the-absolute-directory-of-a-file-in-bash)

File: hack/update-codecgen.sh [hunk 3]
```diff
@@ -41,6 +41,52 @@ function cleanup {
...
+  for dep in ${deps}; do
+    if [[ ${candidate} = *${dep} ]]; then
+      dependsResult=true
+    fi
+  done
+}
+
+function tsort {
+  visited[$1]=true
+	local j=0
```
Comment (timstclair) [inline hack/update-codecgen.sh]: (nit) fix indentation

File: hack/update-codecgen.sh [hunk 4]
```diff
@@ -41,6 +41,52 @@ function cleanup {
...
+
+function depends {
+  file=${generated_files[$1]//\.generated\.go/.go}
+  deps=$(go list -f {{.Deps}} ${file} | tr "[" " " | tr "]" " ")
+  fullpath ${generated_files[$2]//\.generated\.go/.go}
+  candidate=$(dirname ${fullpathResult})
+  dependsResult=false
+  for dep in ${deps}; do
+    if [[ ${candidate} = *${dep} ]]; then
+      dependsResult=true
```
Comment (timstclair) [inline hack/update-codecgen.sh]: Can we use a return instead of a global here?

**Comment by wojtek-t** [comment]
@timstclair - I will address your comments in 2-3 hours. Can you please take a look at #16791 in the meantime - this is blocking this PR.

File: hack/update-codecgen.sh [hunk 5]
```diff
@@ -52,7 +98,9 @@ for generated_file in ${generated_files}; do
 	rm -f "${generated_file}"
 done
 
-for generated_file in ${generated_files}; do
+# Generate files in the dependency order.
+for current in ${index[@]}; do
```
Comment (timstclair) [inline hack/update-codecgen.sh]: Rather than sorting everything ahead of time, I think it might be simpler to just do something along the lines of:
```
while not done {
  for each ungenerated file {
    if file has no dependencies, generate it
  }
  if no files were generated, error
}
```

**Comment by timstclair** [comment]
Thanks for the fix!  I'm always wary of the use of bash arrays, can we at least try to deduplicate the common code between the verify & update scripts?

File: hack/update-codecgen.sh [hunk 6]
```diff
@@ -41,6 +41,52 @@ function cleanup {
 }
 trap cleanup EXIT
 
+# Sort all files in the dependency order.
+number=${#generated_files[@]}
+for (( i=0; i<${number}; i++ )); do
```
Comment (zmerlynn) [inline hack/update-codecgen.sh]: nit: no need for `$` on variables in `((`. (You're inconsistent here between `i` and `number`.

File: hack/update-codecgen.sh [hunk 7]
```diff
@@ -41,6 +41,52 @@ function cleanup {
...
+  visited[${i}]=false
+done
+result=""
+
+function fullpath {
+  pushd $(dirname $1) > /dev/null
```
Comment (zmerlynn) [inline hack/update-codecgen.sh]: nit: quote `"$1"`
nit: quote the entire `"$()"`

File: hack/update-codecgen.sh [hunk 8]
```diff
@@ -41,6 +41,52 @@ function cleanup {
...
+  fullpathResult="${PWD}/$(basename $1)"
+  popd > /dev/null
+}
+
+function depends {
+  file=${generated_files[$1]//\.generated\.go/.go}
+  deps=$(go list -f {{.Deps}} ${file} | tr "[" " " | tr "]" " ")
```
Comment (zmerlynn) [inline hack/update-codecgen.sh]: Please quote `"{{.Deps}}"` so that it doesn't look like a variable.

File: hack/update-codecgen.sh [hunk 9]
```diff
@@ -41,6 +41,52 @@ function cleanup {
...
+  fullpath ${generated_files[$2]//\.generated\.go/.go}
+  candidate=$(dirname ${fullpathResult})
```
Comment (zmerlynn) [inline hack/update-codecgen.sh]: nit: quote `"${fullpathResult}"`

File: hack/update-codecgen.sh [hunk 10]
```diff
@@ -41,6 +41,52 @@ function cleanup {
...
+    if [[ ${candidate} = *${dep} ]]; then
+      dependsResult=true
+    fi
+  done
+}
+
+function tsort {
+  visited[$1]=true
+	local j=0
+  for (( j=0; j<${number}; j++ )); do
```
Comment (zmerlynn) [inline hack/update-codecgen.sh]: Same complaint about `j` versus `number` above.

File: hack/update-codecgen.sh [hunk 11]
```diff
@@ -41,6 +41,52 @@ function cleanup {
...
+    if ! ${visited[${j}]}; then
+      depends $1 ${j}
```
Comment (zmerlynn) [inline hack/update-codecgen.sh]: quote ``"$1"`

File: hack/update-codecgen.sh [hunk 12]
```diff
@@ -41,6 +41,52 @@ function cleanup {
...
+      if ${dependsResult}; then
+        tsort $j
+      fi
+    fi
+  done
+	result="${result} $1"
+}
+for (( i=0; i<${number}; i++ )); do
```
Comment (zmerlynn) [inline hack/update-codecgen.sh]: Unnecessary `$`

File: hack/update-codecgen.sh [hunk 13]
```diff
@@ -52,7 +98,9 @@ for generated_file in ${generated_files}; do
 	rm -f "${generated_file}"
```
Comment (zmerlynn) [inline hack/update-codecgen.sh]: Gah, github isn't letting me open this on the right line, but on line 97 there's a bug:

> `for generated_file in ${generated_files}; do`

You converted `generated_files` to an array, but this syntax is now wrong.

File: hack/update-codecgen.sh (hunk 5 above)
Comment (zmerlynn) [inline hack/update-codecgen.sh]: Also, you want `"${index[@]}"` (because bash and expansion and quotes and sigh).

**Comment by eparis** [comment]
https://github.com/kubernetes/kubernetes/pull/16794 Will take care of the godeps issue....

File: hack/update-codecgen.sh (hunk 13 above)
Comment (wojtek-t) [inline hack/update-codecgen.sh]: Good catch - thanks!

File: hack/update-codecgen.sh (hunk 6 above)
Comment (wojtek-t) [inline hack/update-codecgen.sh]: done.

File: hack/update-codecgen.sh (hunk 2 above)
Comment (wojtek-t) [inline hack/update-codecgen.sh]: I tried using realpath, but it wasn't installed on travis.
I will try this.

File: hack/update-codecgen.sh (hunk 7 above)
Comment (wojtek-t) [inline hack/update-codecgen.sh]: done.

File: hack/update-codecgen.sh (hunk 8 above)
Comment (wojtek-t) [inline hack/update-codecgen.sh]: done.

File: hack/update-codecgen.sh (hunk 3 above)
Comment (wojtek-t) [inline hack/update-codecgen.sh]: done.

File: hack/update-codecgen.sh (hunk 10 above)
Comment (wojtek-t) [inline hack/update-codecgen.sh]: done

File: hack/update-codecgen.sh (hunk 11 above)
Comment (wojtek-t) [inline hack/update-codecgen.sh]: done

File: hack/update-codecgen.sh (hunk 12 above)
Comment (wojtek-t) [inline hack/update-codecgen.sh]: done

File: hack/update-codecgen.sh (hunk 5 above)
Comment (wojtek-t) [inline hack/update-codecgen.sh]: Added quotes.

Regarding the first comment - personally I don't think it will be simpler - we need to check if a file has dependencies anyway, so this will more-or-less be the same.

File: hack/update-codecgen.sh (hunk 9 above)
Comment (wojtek-t) [inline hack/update-codecgen.sh]: done

File: hack/update-codecgen.sh (hunk 4 above)
Comment (wojtek-t) [inline hack/update-codecgen.sh]: I tried to do something better - ptal.

**Comment by wojtek-t** [comment]
@timstclair - hopefully I applied all comments
PTAL

**Comment by wojtek-t** [comment]
Seems to work - @timstclair PTAL

File: hack/update-codecgen.sh [hunk 14]
```diff
@@ -41,6 +41,46 @@ function cleanup {
...
+  done
+  echo ${result}
+}
+
+function tsort {
+  visited[$1]=true
+  local j=0
+  for (( j=0; j<number; j++ )); do
+    if ! ${visited[${j}]}; then
+      if $(depends "$1" ${j}); then
```
Comment (timstclair) [inline hack/update-codecgen.sh]: Do you need the `$(...)` here? I think maybe you can just call a function in an if (I'm no bash expert though).

File: hack/update-codecgen.sh [hunk 15]
```diff
@@ -41,6 +41,46 @@ function cleanup {
...
+        tsort $j
+      fi
+    fi
+  done
+	result="${result} $1"
```
Comment (timstclair) [inline hack/update-codecgen.sh]: (nit) indentation

**Comment by timstclair** [comment]
What did you think about trying to deduplicate the logic in the 2 scripts? Maybe the verify scripts could just move all the generated files to a temporary location, call the update script, check for a diff, and put the temp files back?

File: hack/update-codecgen.sh (hunk 14 above)
Comment (wojtek-t) [inline hack/update-codecgen.sh]: I tried without it - it doesn't work.

File: hack/update-codecgen.sh (hunk 15 above)
Comment (wojtek-t) [inline hack/update-codecgen.sh]: Done.

**Comment by wojtek-t** [comment]
>
What did you think about trying to deduplicate the logic in the 2 scripts? Maybe the verify scripts could just move all the generated files to a temporary location, call the update script, check for a diff, and put the temp files back?

I agree in general. However, there are some differences - in particular we are using different godep, etc. So I think we should do it, but since this is blocking other PRs, I would prefer doing it in other PR.

**Comment by timstclair** [comment]
Sounds good, LGTM.

**Comment by erictune** [comment]
@wojtek-t you added `readlink -f` which is not a valid command on OS X.

**Comment by zmerlynn** [comment]
WTB: docker container that emulates standard OS X userland for testing.

**Comment by erictune** [comment]
Fixed with #17450
