### PR TITLE
Fix error message for non-existent namespace

### LINKED ISSUE #14293: API returns misleading error for creates in non-existent namespace
Attempting to create in a namespace that doesn't exist gives a misleading error:

```
kubectl create -f svc.json --namespace=foo --v=8

I0921 14:12:04.933759   30868 debugging.go:98] POST http://127.0.0.1:8080/api/v1/namespaces/foo/services
I0921 14:12:04.933777   30868 debugging.go:105] Request Headers:
I0921 14:12:04.933789   30868 debugging.go:108]     User-Agent: kubectl/v1.1.0 (linux/amd64) kubernetes/8431348
I0921 14:12:04.935208   30868 debugging.go:123] Response Status: 404 Not Found in 1 milliseconds
I0921 14:12:04.935239   30868 debugging.go:126] Response Headers:
I0921 14:12:04.935252   30868 debugging.go:129]     Content-Type: application/json
I0921 14:12:04.935265   30868 debugging.go:129]     Date: Mon, 21 Sep 2015 18:12:04 GMT
I0921 14:12:04.935278   30868 debugging.go:129]     Content-Length: 229
I0921 14:12:04.935302   30868 request.go:757] Response Body: {
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Service \"mock\" not found",
  "reason": "NotFound",
  "details": {
    "name": "mock",
    "kind": "Service"
  },
  "code": 404
}
I0921 14:12:04.936610   30868 helpers.go:141] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "Service \"mock\" not found",
  "reason": "NotFound",
  "details": {
    "name": "mock",
    "kind": "Service"
  },
  "code": 404
}]
F0921 14:12:04.936648   30868 helpers.go:95] Error from server: Service "mock" not found
```

If the error is caused by the admission controller rejecting creates in namespaces that do not exist, the message should indicate that

### PR DESCRIPTION
**Pull request by feihujiang**
Addresses #14293

### CODE REVIEW

**Comment by feihujiang** [comment]
@k8s-bot  test this please

File: plugin/pkg/admission/namespace/lifecycle/admission.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ func (l *lifecycle) Admit(a admission.Attributes) (err error) {
 		// in case of latency in our caches, make a call direct to storage to verify that it truly exists or not
 		namespaceObj, err = l.client.Namespaces().Get(a.GetNamespace())
 		if err != nil {
-			return admission.NewNotFound(a)
+			return errors.NewNotFound("Namespace", a.GetNamespace())
```
Comment (liggitt) [inline plugin/pkg/admission/namespace/lifecycle/admission.go]: only do this if the error from the namespace was a not found error, otherwise return a different error

**Comment by feihujiang** [comment]
@liggitt I updated according to your advice, please review.

File: plugin/pkg/admission/namespace/lifecycle/admission.go [hunk 2]
```diff
@@ -82,7 +82,13 @@ func (l *lifecycle) Admit(a admission.Attributes) (err error) {
 		// in case of latency in our caches, make a call direct to storage to verify that it truly exists or not
 		namespaceObj, err = l.client.Namespaces().Get(a.GetNamespace())
 		if err != nil {
-			return admission.NewNotFound(a)
+			if errors.IsNotFound(err) {
```
Comment (liggitt) [inline plugin/pkg/admission/namespace/lifecycle/admission.go]: I think we should do this, actually:
```
		namespaceObj, err = l.client.Namespaces().Get(a.GetNamespace())
		if err != nil {
			return admission.NewForbidden(a, err)
		}
```

Comment (liggitt) [inline plugin/pkg/admission/namespace/lifecycle/admission.go]: that includes the details about what is being forbidden, but includes the error from the namespace

**Comment by feihujiang** [comment]
@liggitt  Do we need to change "https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/namespace/exists/admission.go#L79" too?

**Comment by liggitt** [comment]
hmm, probably... @derekwaynecarr, opinion on which error you'd prefer to get back?

File: plugin/pkg/admission/namespace/lifecycle/admission.go (hunk 2 above)
Comment (feihujiang) [inline plugin/pkg/admission/namespace/lifecycle/admission.go]: Do we need to change "https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/namespace/exists/admission.go#L79" too?

Comment (derekwaynecarr) [inline plugin/pkg/admission/namespace/lifecycle/admission.go]: @brendandburns recently made a change to return a 404 when attempting to put something in a Namespace that does not exist.  I don't want to change that behavior to now return a Forbidden again.  I think the current code here is an improvement in that it tells you that the Namespace itself is not present.  The ```NamespaceExists``` plugin is deprecated but the same change should be made there.

**Comment by feihujiang** [comment]
@derekwaynecarr  @liggitt Updated based on your feed back, please review. And NamespaceExists plugin returns a 404 and namespace not found message when namespace does not exist, so we don't need to change it.

**Comment by liggitt** [comment]
lgtm

**Comment by feihujiang** [comment]
@k8s-bot  test this please
