### PR TITLE
unit tests: Fixes kubelet util unit tests for Windows

### LINKED ISSUE #117498: util_window_test.go doesn't import os/net
### Which jobs are failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1648849344847155200

### Which tests are failing?

``` 
# k8s.io/kubernetes/pkg/kubelet/util [k8s.io/kubernetes/pkg/kubelet/util.test]
pkg\kubelet\util\util_windows_test.go:211:12: undefined: os
pkg\kubelet\util\util_windows_test.go:230:2: undefined: os
pkg\kubelet\util\util_windows_test.go:231:13: undefined: net
pkg\kubelet\util\util_windows_test.go:233:17: undefined: net
✓  pkg/kubelet/userns (393ms)
WARN invalid TestEvent: FAIL	k8s.io/kubernetes/pkg/kubelet/util [build failed]
bad output from test2json: FAIL	k8s.io/kubernetes/pkg/kubelet/util [build failed]
``` 

### Since when has it been failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1648849344847155200
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1648668147974148096
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1648305599462510592
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1647943079375671296
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1647580687638728704

### Testgrid link

https://testgrid.k8s.io/sig-windows-signal#windows-unit-master

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig windows
/kind failing-test

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind failing-test
/sig windows
/sig testing

/priority important-soon
/milestone v1.28

#### What this PR does / why we need it:

The unit tests are currently failing due to missing imports. This PR addresses this issue.

Additionally, ``TestIsUnixDomainSocket`` expects an error to be raised by ``IsUnixDomainSocket`` if the file does not exist, but on Windows we do not raise such error.

This issue is addressed by ``Stat``-ing the file, and checking if the file exists or not. We're also handling the case in which the given ``filePath`` is a named pipe, returning ``false`` immediately, instead of trying to dial it as a Unix domain socket.

#### Which issue(s) this PR fixes:

Fixes #117498
Related: https://github.com/kubernetes/kubernetes/issues/51540

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/util/util_windows_test.go [hunk 1]
```diff
@@ -22,6 +22,8 @@ package util
 import (
 	"fmt"
 	"math/rand"
+	"net"
+	"os"
```
Comment (dcantah) [inline pkg/kubelet/util/util_windows_test.go:26]: Did this build previously? 😆

File: pkg/kubelet/util/util_windows.go [hunk 2]
```diff
@@ -165,6 +167,19 @@ func IsUnixDomainSocket(filePath string) (bool, error) {
 	// does NOT work in 1809 if the socket file is created within a bind mounted directory by a container
 	// and the FSCTL is issued in the host by the kubelet.
 
+	if _, err := os.Stat(filePath); err != nil {
+		// If the file does not exist, it cannot be a Unix domain socket.
+		if os.IsNotExist(err) {
+			return false, fmt.Errorf("File %s not found. Err: %v", filePath, err)
```
Comment (dcantah) [inline pkg/kubelet/util/util_windows.go:173]: Probably better to just wrap it. And nit on starting the error capitalized:

```suggestion
			return false, fmt.Errorf("file %s not found: %w", filePath, err)
```

File: pkg/kubelet/util/util_windows_test.go (hunk 1 above)
Comment (claudiubelu) [reply pkg/kubelet/util/util_windows_test.go:26]: Apparently not, since we have this issue open: https://github.com/kubernetes/kubernetes/issues/117498

Comment (dcantah) [reply pkg/kubelet/util/util_windows_test.go:26]: Ack, didn't see the referenced issue. Thanks!

File: pkg/kubelet/util/util_windows.go [hunk 3]
```diff
@@ -165,6 +167,19 @@ func IsUnixDomainSocket(filePath string) (bool, error) {
...
 	// and the FSCTL is issued in the host by the kubelet.
 
+	if _, err := os.Stat(filePath); err != nil {
+		// If the file does not exist, it cannot be a Unix domain socket.
+		if os.IsNotExist(err) {
+			return false, fmt.Errorf("file %s not found: %w", filePath, err)
+		}
+
+		// If it's a named pipe, it cannot be a Unix domain socket.
+		if e, ok := err.(*os.PathError); ok && e.Err == windows.ERROR_PIPE_BUSY {
```
Comment (bart0sh) [inline pkg/kubelet/util/util_windows.go:177]: How realistic is to have a named pipe in the directory with Unix domain sockets?

Comment (claudiubelu) [reply pkg/kubelet/util/util_windows.go:177]: Not realistic at all, named pipes on Windows don't have actual file paths, but they have a different path, with the format: ``\\ServerName\pipe\PipeName``

https://learn.microsoft.com/en-us/windows/win32/ipc/pipe-names

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Review by dcantah — APPROVED** [review]
/lgtm

**Comment by dims** [comment]
/approve

enough reviewers have looked at it. LGTM as well.
