### PR TITLE
kube-proxy: Fix NewProxyServer

### LINKED ISSUE #56238: cross-build: PR 56036 causing cross build failure
```
I1122 09:21:38.273] # k8s.io/kubernetes/cmd/kube-proxy/app
I1122 09:21:38.273] cmd/kube-proxy/app/server.go:221:36: too many arguments in call to NewProxyServer
I1122 09:21:38.273] 	have (*kubeproxyconfig.KubeProxyConfiguration, bool, bool, *"k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime".Scheme, string)
I1122 09:21:38.273] 	want (*kubeproxyconfig.KubeProxyConfiguration, bool, *"k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime".Scheme, string)
```

https://github.com/kubernetes/kubernetes/blob/4e2f5e2212b05a305435ef96f4b49dc0932e1264/cmd/kube-proxy/app/server_windows.go#L49

https://github.com/kubernetes/kubernetes/pull/56036
https://k8s-testgrid.appspot.com/sig-release-misc#cross-build&graph-metrics=test-duration-minutes
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-cross-build/3958

---
cc: @kubernetes/sig-network-bugs @kubernetes/sig-network-test-failures @m1093782566 @thockin 
/kind bug
/priority failing-test

### PR DESCRIPTION
**Pull request by thockin**
Different OSes need different args.  This is not a great fix, but better
than adding an arg to Windows which doesn't need it.

Fixes #56238

```release-note
NONE
```

### CODE REVIEW

File: cmd/kube-proxy/app/server_windows.go [hunk 1]
```diff
@@ -46,7 +46,11 @@ import (
 )
 
 // NewProxyServer returns a new ProxyServer.
-func NewProxyServer(config *proxyconfigapi.KubeProxyConfiguration, cleanupAndExit bool, scheme *runtime.Scheme, master string) (*ProxyServer, error) {
+func NewProxyServer(o *Options) (*ProxyServer, error) {
```
Comment (caseydavenport) [inline cmd/kube-proxy/app/server_windows.go]: Just double checking, but we're OK to have the "cleanup ipvs" flag (and maybe others) ignored on windows, rather than returning a "not supported" type error?

**Comment by caseydavenport** [comment]
status/approved-for-milestone

File: cmd/kube-proxy/app/server_windows.go (hunk 1 above)
Comment (thockin) [reply cmd/kube-proxy/app/server_windows.go]: I think that's the easiest path forward.  The flags are kind of a mess, and being cross-platform makes it 10x worse.  We need a more holistic answer

**Comment by thockin** [comment]
Our bots are so demanding.

**Comment by thockin** [comment]
All green but I don't see it in queue ?

**Comment by cblecker** [comment]
I see it in queue now, @thockin.
