### PR TITLE
Reduce event spam for function GenerateAttachVolumeFunc

### LINKED ISSUE #74988: Event spam in some storage Operation Generator functions
Seems like in some Operation Generator functions (I saw this in `GenerateAttachVolumeFunc` if an error is encountered in the "set up" part outside of the actual `AttachVolumeFunc` there is no rate limiting and the `GenerateAttachVolumeFunc` will be retried over and over hundreds of times a second. This causes significant event spam and can also slow down the controller.

/sig storage
/kind bug
/cc @msau42 @saad-ali @jingxu97 @verult 

**How to reproduce it (as minimally and precisely as possible)**:
Cause some long term error in lines:
https://github.com/davidz627/kubernetes/blob/f7a6b0a8602e02d67fabaa85458a94c0f14599a5/pkg/volume/util/operationexecutor/operation_generator.go#L305-L334
Observe function being retried without rate limiting.

### PR DESCRIPTION
**Pull request by mucahitkurt**
**What type of PR is this?**
/kind cleanup
/sig storage

**What this PR does / why we need it**:
Delete return type error of the function, expand the scope of generated function, delete generated events inside the function(these events will be produced when the generated function is run with rate limiting) to reduce the event spam caused by GenerateAttachVolumFunc.

**Which issue(s) this PR fixes**:
Fixes #74988

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Reduce event spam for AttachVolume storage operation
```

### CODE REVIEW

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 1]
```diff
@@ -291,57 +292,50 @@ func (og *operationGenerator) GenerateBulkVolumeVerifyFunc(
...
 
-		volumeToAttach.VolumeSpec = csiSpec
-	} else {
-		attachableVolumePlugin, err =
-			og.volumePluginMgr.FindAttachablePluginBySpec(volumeToAttach.VolumeSpec)
-		if err != nil || attachableVolumePlugin == nil {
-			eventRecorderFunc(&err)
-			return volumetypes.GeneratedOperations{}, volumeToAttach.GenerateErrorDetailed("AttachVolume.FindAttachablePluginBySpec failed", err)
+		// useCSIPlugin will check both CSIMigration and the plugin specific feature gate
+		if useCSIPlugin(og.volumePluginMgr, volumeToAttach.VolumeSpec) && nu {
```
Comment (mucahitkurt) [inline pkg/volume/util/operationexecutor/operation_generator.go]: I'm not sure about this if/else logic can be simplified like [this](https://gist.github.com/mucahitkurt/d6934c9a474ba3e862a1740c83cf23b9)

Comment (saad-ali) [reply pkg/volume/util/operationexecutor/operation_generator.go]: Seems reasonable to me. But I will let one of the CSI migration folks(@ddebroy @davidz627 @leakingtapan) verify.

**Review by saad-ali — APPROVED** [review]
/approve

LGTM
/assign @ddebroy @davidz627 @leakingtapan 
Will let the CSI migration folks^^^ do final LGTM

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 1 above)
Comment (ddebroy) [reply pkg/volume/util/operationexecutor/operation_generator.go]: SGTM too.

Comment (mucahitkurt) [reply pkg/volume/util/operationexecutor/operation_generator.go]: So, I'll simplify this

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 2]
```diff
@@ -291,57 +292,50 @@ func (og *operationGenerator) GenerateBulkVolumeVerifyFunc(
...
-	nu, err := nodeUsingCSIPlugin(og, volumeToAttach.VolumeSpec, volumeToAttach.NodeName)
-	if err != nil {
-		eventRecorderFunc(&err)
-		return volumetypes.GeneratedOperations{}, volumeToAttach.GenerateErrorDetailed("AttachVolume.NodeUsingCSIPlugin failed", err)
+	attachableVolumePluginName := unknownAttachableVolumePlugin
+	attachableVolumePlugin, err :=
+		og.volumePluginMgr.FindAttachablePluginBySpec(volumeToAttach.VolumeSpec)
+	if err == nil && attachableVolumePlugin != nil {
+		attachableVolumePluginName = attachableVolumePlugin.GetPluginName()
 	}
```
[the remark this answers is not in the document]
Comment (mucahitkurt) [reply pkg/volume/util/operationexecutor/operation_generator.go]: I'll add the comment, but I already deleted the error return type of this function.

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 3]
```diff
@@ -387,11 +376,19 @@ func (og *operationGenerator) GenerateAttachVolumeFunc(
...
+			}
+		}
+	}
+
 	return volumetypes.GeneratedOperations{
 		OperationFunc:     attachVolumeFunc,
 		EventRecorderFunc: eventRecorderFunc,
-		CompleteFunc:      util.OperationCompleteHook(util.GetFullQualifiedPluginNameForVolume(attachableVolumePlugin.GetPluginName(), volumeToAttach.VolumeSpec), "volume_attach"),
-	}, nil
+		CompleteFunc:      util.OperationCompleteHook(util.GetFullQualifiedPluginNameForVolume(attachableVolumePluginName, volumeToAttach.VolumeSpec), "volume_attach"),
```
Comment (leakingtapan) [inline pkg/volume/util/operationexecutor/operation_generator.go]: When CSI migration is enabled, the `volumeToAttach.VolumeSpec` will be the migrated CSI spec. However, with this change, it will be the original spec, since the migration logic is moved inside `attachVolumeFunc`. Im not sure if this is okay. Have you tested your change with CSI migration enabled? And can you check how is `CompleteFunc` is used?

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 1 above)
Comment (ddebroy) [reply pkg/volume/util/operationexecutor/operation_generator.go]: I was just speaking with @leakingtapan and he pointed out that @mkimuram raised some concerns around potential issues with handling reconstruction failures at https://github.com/kubernetes/kubernetes/pull/74844#discussion_r266272782 when he was thinking of switching from `FindAttachablePluginByName ` to `FindAttachablePluginBySpec`. @mkimuram would there be a similar concern here too with the proposed [simplification](https://gist.github.com/mucahitkurt/d6934c9a474ba3e862a1740c83cf23b9)

Comment (mucahitkurt) [reply pkg/volume/util/operationexecutor/operation_generator.go]: Thanks, @leakingtapan pointed out that discussion to me as an answer to my question in sig storage mailing list, when I checked the `GenerateAttachVolumeFunc` usage paths, I couldn't see the similar usage path(not setting the `volumeToAttach.VolumeSpec`).

I see the similar usage of my proposed simplification in [`GenerateMountVolumeFunc`](https://github.com/kubernetes/kubernetes/blob/990ee3c09c0104cc1045b343040fe76082862d73/pkg/volume/util/operationexecutor/operation_generator.go#L529). But usage scenarios can be different.

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 3 above)
Comment (mucahitkurt) [reply pkg/volume/util/operationexecutor/operation_generator.go]: Do you mean a non-automated test? I'm quite new to here, How can I do that kind of test?

Comment (leakingtapan) [reply pkg/volume/util/operationexecutor/operation_generator.go]: We don't have automated test for CSI migration yet. You will need to turn on `CSIMigration` feature flag along with driver specific flag eg. (CSIMigrationAWS) when creating the cluster. Then deploy the CSI driver and verify that it still works.

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 1 above)
Comment (mucahitkurt) [reply pkg/volume/util/operationexecutor/operation_generator.go]: @vladimirvivien opened an [issue](https://github.com/kubernetes/kubernetes/issues/75838) about the usage of find plugin by spec vs find plugin by name, and he also pointed out this function.

@vladimirvivien what do you think about my simplification? Thanks!

Comment (mucahitkurt) [reply pkg/volume/util/operationexecutor/operation_generator.go]: @ddebroy, @leakingtapan I'll rollback this simplification to make this PR go forward.

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 4]
```diff
@@ -291,57 +292,50 @@ func (og *operationGenerator) GenerateBulkVolumeVerifyFunc(
...
-		}
-	}
-
-	originalSpec := volumeToAttach.VolumeSpec
-	nu, err := nodeUsingCSIPlugin(og, volumeToAttach.VolumeSpec, volumeToAttach.NodeName)
-	if err != nil {
-		eventRecorderFunc(&err)
-		return volumetypes.GeneratedOperations{}, volumeToAttach.GenerateErrorDetailed("AttachVolume.NodeUsingCSIPlugin failed", err)
+	attachableVolumePluginName := unknownAttachableVolumePlugin
+	attachableVolumePlugin, err :=
```
Comment (vladimirvivien) [inline pkg/volume/util/operationexecutor/operation_generator.go]: Looking up the plugin by spec can return legitimate errors, specially in the case of `CSI` where the driver may not be ready or capable of supporting attachment at all.  Skipping the error seems to infer that this change would ignore the intent of the driver.

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 5]
```diff
@@ -291,57 +292,50 @@ func (og *operationGenerator) GenerateBulkVolumeVerifyFunc(
...
-		// The volume represented by this spec is CSI and thus should be migrated
-		attachableVolumePlugin, err = og.volumePluginMgr.FindAttachablePluginByName(csi.CSIPluginName)
-		if err != nil || attachableVolumePlugin == nil {
-			eventRecorderFunc(&err)
-			return volumetypes.GeneratedOperations{}, volumeToAttach.GenerateErrorDetailed("AttachVolume.FindAttachablePluginByName failed", err)
-		}
-
-		csiSpec, err := translateSpec(volumeToAttach.VolumeSpec)
+	attachVolumeFunc := func() (error, error) {
+		var attachableVolumePlugin volume.AttachableVolumePlugin
```
Comment (vladimirvivien) [inline pkg/volume/util/operationexecutor/operation_generator.go]: Variable `attachableVolumePlugin` seems to be shadowing the previous declaration (line 298).

**Review by vladimirvivien — COMMENTED** [review]
My major concern with this PR is that it is changing the return signature of `GenerateAttachVolumeFunc` to be different from all other methods in the interface, creating a one-of situation.  Are the other func generator methods not suffering from the same issue solved here?

**Comment by mucahitkurt** [comment]
@vladimirvivien I followed the same refactoring pattern that was applied for the `GenerateMountVolumeFunc` in [this PR](https://github.com/kubernetes/kubernetes/pull/71581), so this function(`GenerateMountVolumeFunc`) also is not returning error.

I also asked about this refactoring on the sig storage mailing list and [the answer](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kubernetes-sig-storage/y3Aa-svhfRk/0O_AsHErBAAJ) was `The operation generation should just construct the function to execute and not have an option to fail (should not return an error). That way the reconciler can be dumb and continue to execute multiple times per second. Any failure will happen when the operation is actually executed, and will be handled correctly by the exponential back off logic.`

I checked the other functions of the interface, the same event spam issue can be valid for the `GenerateMapVolumeFunc`, other functions just return errors and don't create events.

I'm not sure about the above answer about the returning error from those generator functions is valid for all of the methods of the interface `OperationGenerator`.

As far as I understand issues were open for the most painful ones.

> My major concern with this PR is that it is changing the return signature of GenerateAttachVolumeFunc` to be different from all other methods in the interface, creating a one-of situation. Are the other func generator methods not suffering from the same issue solved here?

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 5 above)
Comment (mucahitkurt) [reply pkg/volume/util/operationexecutor/operation_generator.go]: It's intentional, first one is used only to find the plugin name, second one is used then the generated function is executed(`FindAttachablePluginByName` or `FindAttachablePluginBySpec` will assign to this second variable).

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 4 above)
Comment (mucahitkurt) [reply pkg/volume/util/operationexecutor/operation_generator.go]: As far I understand if an error case occurred during the function generation, this error case(skipped one) will also trigger an error while the generated function is executed. And the expectation is handling those error while the execution of the generated function with a backoff policy.

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 5 above)
Comment (vladimirvivien) [reply pkg/volume/util/operationexecutor/operation_generator.go]: I see.

**Comment by vladimirvivien** [comment]
@mucahitkurt sounds like this refactoring has been gradually applied and eventually other methods will be changed to follow the same pattern.  I am good with that.  Thanks for clarifying.

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 6]
```diff
@@ -291,57 +292,50 @@ func (og *operationGenerator) GenerateBulkVolumeVerifyFunc(
...
-
-	originalSpec := volumeToAttach.VolumeSpec
-	nu, err := nodeUsingCSIPlugin(og, volumeToAttach.VolumeSpec, volumeToAttach.NodeName)
-	if err != nil {
-		eventRecorderFunc(&err)
-		return volumetypes.GeneratedOperations{}, volumeToAttach.GenerateErrorDetailed("AttachVolume.NodeUsingCSIPlugin failed", err)
+	attachableVolumePluginName := unknownAttachableVolumePlugin
+	attachableVolumePlugin, err :=
+		og.volumePluginMgr.FindAttachablePluginBySpec(volumeToAttach.VolumeSpec)
+	// It's ok to ignore the error, returning error is not expected from this function
```
Comment (davidz627) [inline pkg/volume/util/operationexecutor/operation_generator.go]: document this idea in the comment too: https://github.com/kubernetes/kubernetes/pull/75986/files#r277510187

Also are we only using this for the `attachableVolumePluginName` now, which we only use for the `CompleteFunc`? If so, can we move this code closer to the place where we use the `attachableVolumePluginName` - after the `attachVolumeFunc`

**Review by davidz627 — COMMENTED** [review]
Thanks for the change! Mostly LGTM

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 6 above)
Comment (mucahitkurt) [reply pkg/volume/util/operationexecutor/operation_generator.go]: Done. Thanks for the comment!

**Comment by davidz627** [comment]
/lgtm
Thanks for the fix!
