### PR TITLE
[PodLevelResourceManagers] CPU & Memory managers forward compatibility - Alpha

### LINKED ISSUE #137750: [failing-test]: dra upgrade tests are failing
##### Error text:
```
[FAILED] FATAL ERROR:
	all kubelet plugin proxies running: replicaset "dra-test-driver" never had desired number of .status.availableReplicas
In [BeforeEach] at: k8s.io/kubernetes/test/e2e/dra/utils/deploy.go:575 @ 03/14/26 06:50:12.848

```
#### Recent failures:
[3/14/2026, 8:10:53 AM ci-kind-dra-n-1](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kind-dra-n-1/2032791211479142400)
[3/14/2026, 2:10:46 AM ci-kind-dra-n-2](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kind-dra-n-2/2032700613191536640)
[3/14/2026, 2:10:45 AM ci-kind-dra-n-1](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kind-dra-n-1/2032700613078290432)
[3/14/2026, 1:08:48 AM ci-kind-dra-n-3](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kind-dra-n-3/2032685010166747136)
[3/12/2026, 12:37:58 PM ci-cloud-provider-aws-e2e-kubetest2](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cloud-provider-aws-e2e-kubetest2/2032133621090881536)

/kind failing-test

#### Analysis

**AI Analysis**

  ---
  Summary

  46 DRA tests failed, 23 passed. Every single failure has the same root cause:

  Root Cause: dra-test-driver ReplicaSet never becomes available

  All 46 test failures occur in BeforeEach at test/e2e/dra/utils/deploy.go:575 with one of two errors:
  1. replicaset "dra-test-driver" never had desired number of .status.availableReplicas (most failures)
  2. client rate limiter Wait returned an error: rate: Wait(n=1) would exceed context deadline (a few failures)

  The test driver pods can't start because the worker kubelets are crash-looping.

  Kubelet Errors (all 3 workers identical)

  Critical — causes kubelet crash-loop (1,315 restarts on kind-worker alone):

    │ CPU manager checkpoint corrupted — "could not restore state from checkpoint: checkpoint is corrupted, please drain this node and delete the CPU manager checkpoint file /var/lib/kubelet/cpu_manager_state before restarting Kubelet" │ cpu_manager.go:231 │

https://github.com/kubernetes/kubernetes/pull/134768#discussion_r2935673466

In the last two days the only change that seems to change anything around cpu_manager_state was the above. 

cc @KevinTMtz @pohly 

/sig node

### PR DESCRIPTION
**Pull request by KevinTMtz**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

With the new state version introduced in the Pod Level Resource Managers feature (https://github.com/kubernetes/kubernetes/pull/134768), we are effectively changing the checksum that a previous 1.35 Kubelet would write with the same information. So even if the feature gate is disabled, after doing a rollback, the checkpoint would have a different checksum than the one expected.

This PR enables forward compatibility by making the 1.36+ Kubelet write a state checkpoint (`CPUManagerCheckpointV2` for CPU manager and `MemoryManagerCheckpointV1` for Memory manager) as a 1.35 Kubelet would do, when the `PodLevelResourceManagers` feature is disabled. When the feature gate is enabled, we continue to use the newly added checkpoint versions (`CPUManagerCheckpointV3` for CPU manager and `MemoryManagerCheckpointV2` for Memory manager).

Refer to conversation from implementation: https://github.com/kubernetes/kubernetes/pull/134768#discussion_r2933867405.

Refer to slack conversation: https://kubernetes.slack.com/archives/C0409NGC1TK/p1773513656177019.

#### Which issue(s) this PR is related to:

Fixes #137750

#### Special notes for your reviewer:

N/A.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/5526-pod-level-resource-managers/README.md
```

### CODE REVIEW

File: pkg/kubelet/cm/cpumanager/state/checkpoint.go [hunk 1]
```diff
@@ -180,6 +190,7 @@ func (cp *CPUManagerCheckpointV2) VerifyChecksum() error {
 	hash := fnv.New32a()
 	_, _ = fmt.Fprintf(hash, "%v", object)
 	actualCS := checksum.Checksum(hash.Sum32())
+	fmt.Printf("VerifyChecksum cp=%#v\n  hash=%d\n  expected=%d\n", cp, actualCS, cp.Checksum)
```
Comment (kannon92) [inline pkg/kubelet/cm/cpumanager/state/checkpoint.go]: What do you want this code to do?

This looks like debug code printing to stdout rather than the kubelet logs. Should you use logger instead?

Comment (KevinTMtz) [reply pkg/kubelet/cm/cpumanager/state/checkpoint.go]: Since there is no way to actually generate a new checkpoint like the previous Kubelet version would do it, I have to simulate the process to test forward compatibility.

Comment (ffromani) [reply pkg/kubelet/cm/cpumanager/state/checkpoint.go]: this very line also seems a debug statement to me

Comment (KevinTMtz) [reply pkg/kubelet/cm/cpumanager/state/checkpoint.go]: Ah, I am sorry, this slipped while staging the changes, and later answered from my phone (thinking this comment was linked to the tests, hence my reply).

Comment (KevinTMtz) [reply pkg/kubelet/cm/cpumanager/state/checkpoint.go]: Removed that line.

**Review by kannon92 — COMMENTED** [review]
/lgtm

**Review by ffromani — COMMENTED** [review]
/approve
