### PR TITLE
Return a FitError when PreFilter fails with unschedulable status

### LINKED ISSUE #91904: Early filtering at PreFilter extension point
Update the semantics of ```PreFilter``` extension point to allow it to act as an early filtering stage. PreFilter can be used to reject pods before evaluating each node at the Filter extension point. This is useful to quickly reject unschedulable pods in cases that don't depend on the particular node (e.g., pod requesting unbound immediate PersistentVolumeClaims).

A non ```Success``` PreFilter gets converted to Error: https://github.com/kubernetes/kubernetes/blob/5dbe3e308af1598536cda3b785fb05b30505990f/pkg/scheduler/core/generic_scheduler.go#L398

We should change that and support proper rejection of the pod at PreFilter. The only acceptable unschedulable status for now should be  ```UnschedulableAndUnresolvable```.

/sig scheduling

### PR DESCRIPTION
**Pull request by ahg-g**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
PreFilter can return an unschedulable status, for example VolumeBinding plugin can return unschedulable at prefilter if any of the volumes with immediate VolumeBindingMode is not yet provisioned.

**Which issue(s) this PR fixes**:
Fixes #91904

-->
```release-note
NONE
```
/assign @Huang-Wei

### CODE REVIEW

**Comment by alculquicondor** [comment]
lgtm, but leaving it to @Huang-Wei

File: pkg/scheduler/core/generic_scheduler_test.go [hunk 1]
```diff
@@ -677,6 +677,43 @@ func TestGenericScheduler(t *testing.T) {
...
+				st.RegisterPreFilterPlugin(
+					"FakePReFilter",
+					st.NewFakePreFilterPlugin(framework.NewStatus(framework.Error, "injected error status")),
+				),
+				st.RegisterBindPlugin(defaultbinder.Name, defaultbinder.New),
+			},
+			nodes:         []string{"1", "2"},
+			pod:           &v1.Pod{ObjectMeta: metav1.ObjectMeta{Name: "test-prefilter", UID: types.UID("test-prefilter")}},
+			expectedHosts: nil,
+			wErr:          fmt.Errorf("prefilter plugin \"FakePreFilter\" failed for pod \"test-prefilter\": injected error status"),
```
Comment (Huang-Wei) [inline pkg/scheduler/core/generic_scheduler_test.go:715]:
```suggestion
			wErr:          fmt.Errorf(`prefilter plugin "FakePreFilter" failed for pod "test-prefilter": injected error status`),
```

File: pkg/scheduler/core/generic_scheduler.go [hunk 2]
```diff
@@ -253,23 +253,36 @@ func (g *genericScheduler) numFeasibleNodesToFind(numAllNodes int32) (numNodes i
...
+			// needed to avoid this copy.
+			allNodes, err := g.nodeInfoSnapshot.NodeInfos().List()
+			if err != nil {
+				return nil, nil, err
+			}
+			for _, n := range allNodes {
+				filteredNodesStatuses[n.Node().Name] = s
+			}
+			return nil, filteredNodesStatuses, nil
+		}
```
Comment (Huang-Wei) [inline pkg/scheduler/core/generic_scheduler.go:272]: nit, in terms of "indenting negative path":

```go
	if !s.IsSuccess() {
		if !s.IsUnschedulable() {
			return nil, nil, s.AsError()
		}
		// All nodes will have the same status. Some non trivial refactoring is
		// needed to avoid this copy.
		allNodes, err := g.nodeInfoSnapshot.NodeInfos().List()
		if err != nil {
			return nil, nil, err
		}
		for _, n := range allNodes {
			filteredNodesStatuses[n.Node().Name] = s
		}
		return nil, filteredNodesStatuses, nil
	}
```

**Review by Huang-Wei — COMMENTED** [review]
Thanks @ahg-g . Some nits.

File: pkg/scheduler/core/generic_scheduler.go (hunk 2 above)
Comment (ahg-g) [reply pkg/scheduler/core/generic_scheduler.go]: done

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 1 above)
Comment (ahg-g) [reply pkg/scheduler/core/generic_scheduler_test.go]: done

File: pkg/scheduler/core/generic_scheduler_test.go [hunk 3]
```diff
@@ -677,6 +677,43 @@ func TestGenericScheduler(t *testing.T) {
 			expectedHosts: nil,
 			wErr:          nil,
 		},
+		{
+			name: "test prefilter plugin returning Unschedulable status",
+			registerPlugins: []st.RegisterPluginFunc{
+				st.RegisterQueueSortPlugin(queuesort.Name, queuesort.New),
+				st.RegisterPreFilterPlugin(
+					"FakePReFilter",
```
[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/scheduler/core/generic_scheduler_test.go]: done

**Review by alculquicondor — COMMENTED** [review]
still lgtm

File: pkg/scheduler/core/generic_scheduler.go [hunk 4]
```diff
@@ -253,23 +253,37 @@ func (g *genericScheduler) numFeasibleNodesToFind(numAllNodes int32) (numNodes i
 // Filters the nodes to find the ones that fit the pod based on the framework
 // filter plugins and filter extenders.
 func (g *genericScheduler) findNodesThatFitPod(ctx context.Context, prof *profile.Profile, state *framework.CycleState, pod *v1.Pod) ([]*v1.Node, framework.NodeToStatusMap, error) {
+	filteredNodesStatuses := make(framework.NodeToStatusMap)
+
 	// Run "prefilter" plugins.
 	s := prof.RunPreFilterPlugins(ctx, state, pod)
 	if !s.IsSuccess() {
-		return nil, nil, s.AsError()
+		if !s.IsUnschedulable() {
```
Comment (Huang-Wei) [inline pkg/scheduler/core/generic_scheduler.go:261]: I rethink it a bit.

The primary benefit of returning a FitError (instead of Error) is to continue preemption. Given that current preemption logic doesn't proceed upon `UnschedulableAndUnresolvable` status:

https://github.com/kubernetes/kubernetes/blob/21953d15ea48972f20a8de29d58bd5ce6d913914/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L224-L228

(but we can argue that custom preemption plugin may proceed even with `UnschedulableAndUnresolvable` status)

So maybe we can optimize the logic here:

```go
if s.Code() == UnschedulableAndUnresolvable {
```

Comment (ahg-g) [reply pkg/scheduler/core/generic_scheduler.go:261]: Not only to execute preemption but also proper metric reporting, so I think we should keep it this way and optimize later the fact that all nodes will have the same status.

Comment (alculquicondor) [reply pkg/scheduler/core/generic_scheduler.go:261]: The question here is whether PreFilter plugins could return `Unschedulable`, as opposed to only `UnschedulableAndUnresolvable`.

I don't think we need to limit them.

Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler.go:261]: > so I think we should keep it this way and optimize later the fact that all nodes will have the same status.

That for sure has an improvement room, like simply using a `*` to represent all nodes.

> I don't think we need to limit them.

+1. I believe it's possible that some PreFilter plugin may return `Unschedulable` as well.
