### PR TITLE
Ginkgo update + stack fix

### LINKED ISSUE #82013: full stack trace in E2E testing incorrect (Ginkgo bug)
**What happened**:

Ginkgo no longer handles the `runtime.Stack()` from current Go correctly, which leads to broken output when using `e2e.test -ginkgo.trace`:
```  Full Stack Trace
=>  	/nvme/gopath/src/k8s.io/kubernetes/test/e2e/framework/util.go:1362 +0x112
=>  k8s.io/kubernetes/test/e2e/framework.ExpectNoError(...)
=>  	/nvme/gopath/src/k8s.io/kubernetes/test/e2e/framework/util.go:1356
  k8s.io/kubernetes/test/e2e/framework/log_test.glob..func1.4()
  	/nvme/gopath/src/k8s.io/kubernetes/test/e2e/framework/log/logger_test.go:49 +0xc9
  k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc00053ea20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  	/nvme/gopath/src/k8s.io/kubernetes/test/e2e/framework/log/logger_test.go:65 +0x1c8
  testing.tRunner(0xc00023ac00, 0x1aa7818)
  	/nvme/gopath/go/src/testing/testing.go:865 +0xc0
  created by testing.(*T).Run
  	/nvme/gopath/go/src/testing/testing.go:916 +0x35a
```

**What you expected to happen**:

The output should start with:
```
  k8s.io/kubernetes/test/e2e/framework/log_test.glob..func1.4()
  	/nvme/gopath/src/k8s.io/kubernetes/test/e2e/framework/log/logger_test.go:49 +0xc9
```

**How to reproduce it (as minimally and precisely as possible)**:

See `TestFailureOutput` in test/e2e/framework/log/logger_test.go.

**Anything else we need to know?**:

Steps to fix it:
- get https://github.com/onsi/ginkgo/pull/590 merged
- update Ginkgo in Kubernetes
- re-enabled the commented out test case in test/e2e/framework/log/logger_test.go
- update test cases in that file

/area e2e-test-framework

### PR DESCRIPTION
**Pull request by pohly**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

After merging
https://github.com/kubernetes/kubernetes/commit/259bb3bef5403daec1bbe44c2c9413ec17b52b6e#diff-eb7b79470992813ea1905e96c298b47b
ExpectEqual and some of the other wrappers logged the failure twice,
once inside the wrapper itself and once in the failure handler.
    
Logging the stack backtrace is useful because many assertions still
don't contain an explanation and therefore knowing where they occur is
crucial. Now all failures are logged with a "Full Stack Trace", not
just those with a wrapper. The stack is pruned to skip over wrapper
functions and removes Ginkgo internal functions to keep the stack
trace smaller.
    
Failures occurring in the wrappers were recorded as occurring in those
wrappers. Now the wrappers are skipped and the caller is recorded
instead.

Fixes: #82013

**Does this PR introduce a user-facing change?**:
```release-note
more complete and accurate logging of stack backtraces in E2E failures
```

### CODE REVIEW

**Comment by pohly** [comment]
This is WIP because Ginkgo 1.10.0 still isn't quite working correctly: https://github.com/onsi/ginkgo/pull/600

File: test/e2e/framework/log/logger.go [hunk 1]
```diff
@@ -59,6 +63,42 @@ func Fail(msg string, callerSkip ...int) {
...
+var codeFilterRE = regexp.MustCompile(`/github.com/onsi/ginkgo/`)
+
+// PrunedStack is a wrapper around debug.Stack() that removes information
+// about the current goroutine and optionally skips some of the initial stack entries.
+// With skip == 0, the returned stack will start with the caller of PruneStack.
+// From the remaining entries it automatically filters out useless ones like
+// entries coming from Ginkgo.
+//
+// This is a copy of https://github.com/onsi/ginkgo/blob/f90f37d87fa6b1dd9625e2b1e83c23ffae3de228/internal/codelocation/code_location.go#L25
+func PrunedStack(skip int) string {
```
Comment (oomichi) [inline test/e2e/framework/log/logger.go]: The original function name is PruneStack in ginkgo. I guess this name (with `d`) is intentional, right?
(I tried to search this name in ginkgo repo, and I missed that with the name)

Comment (pohly) [reply test/e2e/framework/log/logger.go]: I intentionally renamed it, because this version is simpler and returns the "pruned stack" instead of taking an arbitrary string and pruning it.

Comment (pohly) [reply test/e2e/framework/log/logger.go]: I added "This is a *modified* copy of PruneStack in ..."

File: test/e2e/framework/log/logger.go [hunk 2]
```diff
@@ -19,6 +19,9 @@ package log
 
 import (
```
[the remark this answers is not in the document]
Comment (pohly) [reply test/e2e/framework/log/logger.go]: I see. I've moved it and also some of the `util.go` functions that are only used in `log.go`. I also updated the comment in `framework/e2e/log/logger.go` to be more explicit.

File: test/e2e/framework/log/logger.go [hunk 3]
```diff
@@ -48,8 +51,9 @@ func Failf(format string, args ...interface{}) {
 // (for example, for call chain f -> g -> FailfWithOffset(1, ...) error would be logged for "f").
```
[the remark this answers is not in the document]
Comment (pohly) [reply test/e2e/framework/log/logger.go]: Done.

**Comment by pohly** [comment]
I found that the log unit test stopped working on September 1st, see fix in https://github.com/kubernetes/kubernetes/pull/82229

I'd like to get that merged for master and 1.16 before continuing here.

**Comment by pohly** [comment]
@oomichi: PR updated, all tests clean -> please have another look.

File: test/e2e/framework/log/logger.go [hunk 4]
```diff
@@ -14,7 +14,8 @@ See the License for the specific language governing permissions and
 limitations under the License.
 */
 
-// Package log should be removed after switching to use core framework log.
+// Package log will be removed after switching to use core framework log.
+// Do not make further changes here!
```
Comment (oomichi) [inline test/e2e/framework/log/logger.go]: +1 :-)

**Review by oomichi — COMMENTED** [review]
@pohly Thank you so much for this work!

/approve
/lgtm

**Review by alejandrox1 — APPROVED** [review]
This looks good!
/milestone v1.17
/priority backlog

**Comment by pohly** [comment]
@oomichi: I had to rebase to resolve a conflict in test/e2e/framework/BUILD, can you re-add your lgtm?

**Comment by alejandrox1** [comment]
mmm :thinking: 
/retest

**Comment by pohly** [comment]
"mmm" indeed. No output whatsoever from the failed job?

**Comment by chases2** [comment]
Hello, all!

I'm currently looking into why this isn't generating logs. So far I know:
- The job did actually run
- It actually seem to have emitted no logs (likely not a UI issue)

**Comment by pohly** [comment]
`make test` works locally, but isn't quite the same (no bazel).

**Comment by oomichi** [comment]
Thanks again

/lgtm

**Comment by pohly** [comment]
`bazel test --config=unit  //... -- -//build/... -//vendor/...` also worked locally.

**Comment by pohly** [comment]
... and the third attempt today produces output: https://prow.k8s.io/log?id=1176193418221588482&job=pull-kubernetes-bazel-test

**Comment by alejandrox1** [comment]
Just need a final approval
/assign @oomichi @timothysc @andrewsykim 
ptal

**Comment by alejandrox1** [comment]
Thank you @chases2 for taking a look at the failures

File: test/e2e/framework/log.go [hunk 5]
```diff
@@ -18,24 +18,88 @@ package framework
...
+// PrunedStack is a wrapper around debug.Stack() that removes information
+// about the current goroutine and optionally skips some of the initial stack entries.
+// With skip == 0, the returned stack will start with the caller of PruneStack.
+// From the remaining entries it automatically filters out useless ones like
+// entries coming from Ginkgo.
+//
+// This is a modified copy of PruneStack in https://github.com/onsi/ginkgo/blob/f90f37d87fa6b1dd9625e2b1e83c23ffae3de228/internal/codelocation/code_location.go#L25:
+// - simplified API and thus renamed (calls debug.Stack() instead of taking a parameter)
+// - source code filtering updated to be specific to Kubernetes
+func PrunedStack(skip int) string {
```
Comment (andrewsykim) [inline test/e2e/framework/log.go]: Anyway this can be consolidated with https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/ginkgowrapper/wrapper.go#L112?

Comment (pohly) [reply test/e2e/framework/log.go]: That may be useful, but I have no idea how that code is used and therefore would prefer to not touch it.

**Comment by oomichi** [comment]
@alejandrox1 
> Just need a final approval

This PR changes many files then we need approval by approver of root directory.
(I've put my best score on this already :-)

File: go.mod [hunk 6]
```diff
@@ -93,7 +93,7 @@ require (
 	github.com/mrunalp/fileutils v0.0.0-20160930181131-4ee1cc9a8058 // indirect
 	github.com/munnerz/goautoneg v0.0.0-20120707110453-a547fc61f48d
 	github.com/mvdan/xurls v1.1.0
-	github.com/onsi/ginkgo v1.8.0
+	github.com/onsi/ginkgo v1.10.1
 	github.com/onsi/gomega v1.5.0
```
Comment (timothysc) [inline go.mod]: Shouldn't this also be updated to 1.7.0 if you're making this change?

Comment (pohly) [reply go.mod]: It could get updated, but it's unrelated to the problem that this PR is solving and both projects are only loosely related, so Ginkgo 1.10.1 and Gomega 1.5.0 should be a valid combination.

Considering that both the Ginkgo and the Gomega update could cause issues, it might be safer to update them separately.

Comment (timothysc) [reply go.mod]: The releases we're clearly coordinated when looking at the commit history, please update gomega to ensure we are in lock step.

Comment (timothysc) [reply go.mod]: /hold

Comment (pohly) [reply go.mod]: > The releases we're clearly coordinated when looking at the commit history, please update gomega to ensure we are in lock step.

Okay, if that's preferred.

**Review by alejandrox1 — COMMENTED** [review]
/lgtm
/retest

/remove-sig cli
/remove-sig cloud-provider
/remove-sig cluster-lifecycle
/remove-area kubectl
/remove-area cloudprovider
/remove-area apiserver

File: go.mod (hunk 6 above)
Comment (pohly) [reply go.mod]: /hold cancel

Gomega updated, too. I also rebased.

**Review by timothysc — APPROVED** [review]
/approve

**Comment by timothysc** [comment]
/assign @liggitt  
^ requires approval for dep changes.

**Comment by alejandrox1** [comment]
@pohly could you try doing a `git commit --amend && git push -f origin ginkgo-stack-fix` to try and remove the needs-rebase label ? :thinking:

**Comment by pohly** [comment]
> could you try doing a git commit --amend && git push -f origin ginkgo-stack-fix to try and remove the needs-rebase label ?

Done. @alejandrox1 now you need to LGTM again.
