### PR TITLE
kubectl: a couple of edit fixes

### LINKED ISSUE #6926: edit is not properly printing validation errors
Opened a DC, trying to set hooks:

```
  1 # Please edit the object below. Lines beginning with a '#' will be ignored,
  2 # and an empty file will abort the edit. If an error occurs while saving this file will be
  3 # reopened with the relevant failures.
  4 #
  5 # %!s(func(runtime.Object) (string, error)=0x12fd00) mysql was not valid:
  6 # * required value
  7 #
```

Not sure if this is an artifact of the upstream edit, or of the rebase, but either way needs to be fixed.

### LINKED ISSUE #20078: Can't abort kubectl edit
I am running `kubectl edit` against an object.  I make a mistake, and it reopens (nice) with comments (nice).  I decide I don't want to edit, after all.  How do I abort?  In most scenarios, exiting without save or deleting all contents would trigger the process to abort.  Not so in kubectl.

### PR DESCRIPTION
**Pull request by 0xmichalis**
Fix some edit bugs:
- Reload the file in case of syntax errors
- Fix error format for validation errors
- Avoid looping in case of no changes or empty saves

Fixes https://github.com/kubernetes/kubernetes/issues/20078
Also fixes https://github.com/openshift/origin/issues/6926

@kubernetes/kubectl

### CODE REVIEW

**Comment by kargakis** [comment]
@janetkuo PTAL

File: pkg/kubectl/cmd/edit.go [hunk 1]
```diff
@@ -193,29 +204,20 @@ func RunEdit(f *cmdutil.Factory, out io.Writer, cmd *cobra.Command, args []strin
...
 
-			glog.V(4).Infof("User edited:\n%s", string(edited))
-			lines, err := hasLines(bytes.NewBuffer(edited))
-			if err != nil {
-				return preservedFile(err, file, out)
-			}
 			// Compare content without comments
 			if bytes.Equal(stripComments(original), stripComments(edited)) {
-				if len(results.edit) > 0 {
-					preservedFile(nil, file, out)
```
Comment (kargakis) [inline pkg/kubectl/cmd/edit.go]: This preservedFile call and the following are removed since they are redundant. We made no changes to the configuration or we did an empty save, there is no reason to preserve.

**Comment by janetkuo** [comment]
I tried it locally but #20078 still happens. The steps to reproduce:
```sh
$ kubectl create -f examples/extensions/deployment.yaml
$ kubectl edit -f examples/extensions/deployment.yaml
# Make a syntax error; for example, add a ":" to image name, then save the file.
# The modified file should be opened again with comments say that there's a syntax error. 
# Then quit without changing anything. Got stuck in the loop again. 
```

**Comment by kargakis** [comment]
> The modified file should be opened again with comments say that there's a syntax error.

The error is printed normally.

> Then quit without changing anything. Got stuck in the loop again.

Empty save works. Also fixing the error and saving ie. making no chage works. You are right about quiting w/o saving. I'll look at it.

**Comment by kargakis** [comment]
@janetkuo can you retest with the latest commit? It fixes the hotlooping problem when we try to quit. It's ugly though because it will also quit on subsequent saves with the same invalid changes but I think we can live with it.

**Comment by kargakis** [comment]
Squashed and rebased. @janetkuo PTAL, we need this as it contains a couple of edit bug fixes

**Comment by smarterclayton** [comment]
@k8s-bot test this github issue: #20655

**Comment by kargakis** [comment]
@janetkuo ping

**Comment by bgrant0607** [comment]
@kargakis Who worked on edit for Openshift? Could they review this?

**Comment by kargakis** [comment]
@smarterclayton 

or @deads2k since you picked this in Origin

**Comment by janetkuo** [comment]
Sorry for the delay; I'll take a look

File: pkg/kubectl/cmd/edit.go [hunk 2]
```diff
@@ -178,45 +185,52 @@ func RunEdit(f *cmdutil.Factory, out io.Writer, cmd *cobra.Command, args []strin
...
+				fmt.Fprintln(out, "Edit cancelled, no valid changes were saved.")
+				continue outter
+			}
 
 			// cleanup any file from the previous pass
 			if len(results.file) > 0 {
 				os.Remove(results.file)
 			}
 
-			glog.V(4).Infof("User edited:\n%s", string(edited))
```
Comment (janetkuo) [inline pkg/kubectl/cmd/edit.go]: Keep this log?

File: pkg/kubectl/cmd/edit.go [hunk 3]
```diff
@@ -178,45 +185,52 @@ func RunEdit(f *cmdutil.Factory, out io.Writer, cmd *cobra.Command, args []strin
...
+			edited, file, err = edit.LaunchTempFile(fmt.Sprintf("%s-edit-", os.Args[0]), ext, buf)
 			if err != nil {
 				return preservedFile(err, results.file, out)
 			}
+			if bytes.Equal(stripComments(editedDiff), stripComments(edited)) {
+				// Ugly hack right here. We will hit this either (1) when we try to
+				// save the same changes we tried to save in the previous iteration
+				// which means our changes are invalid or (2) when we exit the second
+				// time. The second case is more usual so we can probably live with it.
+				fmt.Fprintln(out, "Edit cancelled, no valid changes were saved.")
```
Comment (janetkuo) [inline pkg/kubectl/cmd/edit.go]: A TODO for a less hacky fix in the future?

File: pkg/kubectl/cmd/edit.go [hunk 4]
```diff
@@ -151,24 +150,32 @@ func RunEdit(f *cmdutil.Factory, out io.Writer, cmd *cobra.Command, args []strin
...
+		edit               = editor.NewDefaultEditor(f.EditorEnvs())
+		results            = editResults{}
+		original           = []byte{}
+		edited             = []byte{}
+		file               string
+	)
+
+outter:
+	for i := range objs {
+		obj := objs[i]
```
Comment (janetkuo) [inline pkg/kubectl/cmd/edit.go]: How about 
```go
for _, obj := range objs {
```

File: pkg/kubectl/cmd/edit.go [hunk 5]
```diff
@@ -151,24 +150,32 @@ func RunEdit(f *cmdutil.Factory, out io.Writer, cmd *cobra.Command, args []strin
...
+		// some bookkeeping
+		results.header.flush()
+		isError := false
```
Comment (janetkuo) [inline pkg/kubectl/cmd/edit.go]: Suggest that we put `isError` in `results`. Also suggest a better name, such as `invalid` or `containsError`.

**Comment by janetkuo** [comment]
A few comments

**Comment by janetkuo** [comment]
From user experience perspective, I'd expect when I edit a resource with some syntax error, it will reopen the file (ok) with the error message (ok); and then it should allow me to quit without saving (ok) as well as prevent me from saving the file without removing that syntax error (in this PR the save will complete with "Edit canceled" message). But I think this PR is good enough for now.

File: pkg/kubectl/cmd/edit.go (hunk 4 above)
Comment (kargakis) [inline pkg/kubectl/cmd/edit.go]: Ever since bugs like https://github.com/kubernetes/kubernetes/pull/18331 or https://github.com/kubernetes/kubernetes/pull/18321 I have stopped using this syntax when ranging over references:)

File: pkg/kubectl/cmd/edit.go (hunk 5 above)
Comment (kargakis) [inline pkg/kubectl/cmd/edit.go]: `isError` is an indication that there is an error. In both places where we set it to true we pass the error message in the header (https://github.com/kubernetes/kubernetes/pull/20481/files#diff-4179e22f3469dd57194a9cd510649296R245 and https://github.com/kubernetes/kubernetes/pull/20481/files#diff-4179e22f3469dd57194a9cd510649296R304). I can change it to `containsError`.

File: pkg/kubectl/cmd/edit.go (hunk 2 above)
Comment (kargakis) [inline pkg/kubectl/cmd/edit.go]: added back

File: pkg/kubectl/cmd/edit.go (hunk 3 above)
Comment (kargakis) [inline pkg/kubectl/cmd/edit.go]: ok

**Comment by kargakis** [comment]
@janetkuo all comments addressed

**Comment by kargakis** [comment]
unrelated flake
```
â€¢ Failure [54.571 seconds]
Deployment
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:68
  deployment should support rollback when there's replica set with no revision [It]
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:67

  Expected error:
      <*errors.StatusError | 0xc20844e300>: {
          ErrStatus: {
              TypeMeta: {Kind: "Status", APIVersion: "v1"},
              ListMeta: {SelfLink: "", ResourceVersion: ""},
              Status: "Failure",
              Message: "deployments.extensions \"nginx-deployment\" cannot be updated: the object has been modified; please apply your changes to the latest version and try again",
              Reason: "Conflict",
              Details: {
                  Name: "nginx-deployment",
                  Group: "extensions",
                  Kind: "deployments",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 409,
          },
      }
      deployments.extensions "nginx-deployment" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
  not to have occurred

  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:168
```

**Comment by kargakis** [comment]
@k8s-bot unit test this

**Comment by kargakis** [comment]
@k8s-bot test this issue: https://github.com/kubernetes/kubernetes/issues/21467
