### PR TITLE
Fix go lint failures in volume scheduling packages

### LINKED ISSUE #77084: Follow up of #75434: fix go lint failures
**What would you like to be added**:

**Why is this needed**:

https://github.com/kubernetes/kubernetes/pull/75434#discussion_r266350830

### PR DESCRIPTION
**Pull request by cofyc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

- pkg/controller/volume/persistentvolume/testing
- pkg/controller/volume/scheduling

**Which issue(s) this PR fixes**:

Fixes #77084 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/volume/persistentvolume/testing/testing.go [hunk 1]
```diff
@@ -37,7 +37,9 @@ import (
 	"k8s.io/kubernetes/pkg/features"
 )
 
-var VersionConflictError = errors.New("VersionError")
+// ErrVersionConflict is the error returned when resource version of requested
+// object conflicts with the object in storage.
+var ErrVersionConflict = errors.New("VersionError")
```
Comment (cofyc) [inline pkg/controller/volume/persistentvolume/testing/testing.go]: `golint: error var VersionConflictError should have name of the form ErrFoo`

File: pkg/controller/volume/persistentvolume/testing/testing.go [hunk 2]
```diff
@@ -299,12 +297,6 @@ func (r *VolumeReactor) getWatches(gvr schema.GroupVersionResource, ns string) [
 	return watches
 }
 
-func (r *VolumeReactor) ChangedSinceLastSync() int {
```
Comment (cofyc) [inline pkg/controller/volume/persistentvolume/testing/testing.go]: Duplicate function

File: pkg/controller/volume/scheduling/scheduler_assume_cache.go [hunk 3]
```diff
@@ -127,7 +127,8 @@ func (c *assumeCache) objInfoIndexFunc(obj interface{}) ([]string, error) {
 	return c.indexFunc(objInfo.latestObj)
 }
 
-func NewAssumeCache(informer cache.SharedIndexInformer, description, indexName string, indexFunc cache.IndexFunc) *assumeCache {
+// NewAssumeCache creates an assume cache for genernal objects.
+func NewAssumeCache(informer cache.SharedIndexInformer, description, indexName string, indexFunc cache.IndexFunc) AssumeCache {
```
Comment (cofyc) [inline pkg/controller/volume/scheduling/scheduler_assume_cache.go]: `exported func NewAssumeCache returns unexported type *scheduling.assumeCache, which can be annoying to use`
so I changed the function to return interface

File: pkg/controller/volume/scheduling/scheduler_assume_cache.go [hunk 4]
```diff
@@ -354,8 +355,9 @@ func pvStorageClassIndexFunc(obj interface{}) ([]string, error) {
 	return []string{""}, fmt.Errorf("object is not a v1.PersistentVolume: %v", obj)
 }
 
+// NewPVAssumeCache creates a PV assume cache.
 func NewPVAssumeCache(informer cache.SharedIndexInformer) PVAssumeCache {
-	return &pvAssumeCache{assumeCache: NewAssumeCache(informer, "v1.PersistentVolume", "storageclass", pvStorageClassIndexFunc)}
+	return &pvAssumeCache{NewAssumeCache(informer, "v1.PersistentVolume", "storageclass", pvStorageClassIndexFunc).(*assumeCache)}
```
Comment (cofyc) [inline pkg/controller/volume/scheduling/scheduler_assume_cache.go]: because it returns an interface now, we need to cast it to `*assumeCache`
note that we cannot use AssumeCache interface in `pvAssumeCache` struct because private functions of `assumeCache` are required in testing

File: pkg/controller/volume/scheduling/scheduler_assume_cache.go [hunk 5]
```diff
@@ -414,8 +416,9 @@ type pvcAssumeCache struct {
 	*assumeCache
 }
 
+// NewPVCAssumeCache creates a PVC assume cache.
 func NewPVCAssumeCache(informer cache.SharedIndexInformer) PVCAssumeCache {
-	return &pvcAssumeCache{assumeCache: NewAssumeCache(informer, "v1.PersistentVolumeClaim", "namespace", cache.MetaNamespaceIndexFunc)}
+	return &pvcAssumeCache{NewAssumeCache(informer, "v1.PersistentVolumeClaim", "namespace", cache.MetaNamespaceIndexFunc).(*assumeCache)}
```
Comment (cofyc) [inline pkg/controller/volume/scheduling/scheduler_assume_cache.go]: same as `NewPVAssumeCache`

File: pkg/controller/volume/scheduling/scheduler_assume_cache_test.go [hunk 6]
```diff
@@ -109,13 +109,13 @@ func TestAssumePV(t *testing.T) {
 
 	for name, scenario := range scenarios {
 		cache := NewPVAssumeCache(nil)
-		internal_cache, ok := cache.(*pvAssumeCache)
+		internalCache, ok := cache.(*pvAssumeCache)
```
Comment (cofyc) [inline pkg/controller/volume/scheduling/scheduler_assume_cache_test.go]: ` don't use underscores in Go names; var internal_cache should be internalCache`

File: pkg/controller/volume/persistentvolume/testing/testing.go [hunk 7]
```diff
@@ -219,21 +221,19 @@ func (r *VolumeReactor) React(action core.Action) (handled bool, ret runtime.Obj
 		if found {
 			klog.V(4).Infof("GetVolume: found %s", volume.Name)
 			return true, volume.DeepCopy(), nil
-		} else {
-			klog.V(4).Infof("GetVolume: volume %s not found", name)
-			return true, nil, fmt.Errorf("Cannot find volume %s", name)
 		}
+		klog.V(4).Infof("GetVolume: volume %s not found", name)
```
Comment (cofyc) [inline pkg/controller/volume/persistentvolume/testing/testing.go]: `if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)`
it applies to all `if else` cases

File: pkg/controller/volume/scheduling/scheduler_binder_fake.go [hunk 8]
```diff
@@ -18,7 +18,7 @@ package scheduling
 
 import "k8s.io/api/core/v1"
 
-type FakeVolumeBinderConfig struct {
+type fakeVolumeBinderConfig struct {
```
Comment (cofyc) [inline pkg/controller/volume/scheduling/scheduler_binder_fake.go]: unexported it then we don't need to comment it

File: pkg/controller/volume/scheduling/scheduler_binder_fake.go [hunk 9]
```diff
@@ -27,34 +27,34 @@ type FakeVolumeBinderConfig struct {
...
-	return &FakeVolumeBinder{
+func NewFakeVolumeBinder(config *fakeVolumeBinderConfig) SchedulerVolumeBinder {
+	return &fakeVolumeBinder{
 		config: config,
 	}
 }
 
-type FakeVolumeBinder struct {
-	config       *FakeVolumeBinderConfig
+type fakeVolumeBinder struct {
```
Comment (cofyc) [inline pkg/controller/volume/scheduling/scheduler_binder_fake.go]: unexported it then we don't need to comment it

File: pkg/controller/volume/scheduling/scheduler_binder_fake.go [hunk 10]
```diff
@@ -27,34 +27,34 @@ type FakeVolumeBinderConfig struct {
 	BindErr              error
 }
 
-// NewVolumeBinder sets up all the caches needed for the scheduler to make
+// NewFakeVolumeBinder sets up all the caches needed for the scheduler to make
 // topology-aware volume binding decisions.
-func NewFakeVolumeBinder(config *FakeVolumeBinderConfig) *FakeVolumeBinder {
-	return &FakeVolumeBinder{
+func NewFakeVolumeBinder(config *fakeVolumeBinderConfig) SchedulerVolumeBinder {
```
Comment (cofyc) [inline pkg/controller/volume/scheduling/scheduler_binder_fake.go]: return exported interface

**Comment by cofyc** [comment]
/assign @dims @fejta
for `hack/.golint_failures` approval
/assign @msau42 
for reviewing

File: pkg/controller/volume/scheduling/scheduler_assume_cache.go (hunk 4 above)
Comment (msau42) [reply pkg/controller/volume/scheduling/scheduler_assume_cache.go]: Hm can the unit tests do one more level of casting to get the 'assumeCache'?

Looking at L348, I'm not sure we need to copy private 'assumeCache' into the struct. It looks like we only use interface functions in the PV and PVC implementations

**Review by fejta — COMMENTED** [review]
/lgtm
/approve

File: pkg/controller/volume/scheduling/scheduler_assume_cache.go (hunk 4 above)
Comment (cofyc) [reply pkg/controller/volume/scheduling/scheduler_assume_cache.go]: > can the unit tests do one more level of casting to get the 'assumeCache'?

At before, I thought we need two variables to access pv/pvc)AssumeCache and assumeCache with which the code will be tedious, but I found in testing we didn't need to access private methods of (pv/pvc)AssumeCache.

It's a good idea. I pushed a new commit to address this: https://github.com/kubernetes/kubernetes/pull/77442/commits/4abd73048c35604a620a3cb6f68ffad6c42e3fe6
