### PR TITLE
fix nestedPendingOperations mount and umount parallel bug -- minimal change

### LINKED ISSUE #109047: kubelet nestedPendingOperations may leak operation lead same pv not to do mount or umount operation
### What happened?

on my scenes，create same cronjob use same sfs(the nfs storage on Huawei Cloud) type storage by pvc to do same training work. At the same time, a node will schedule many pods using the same pvc, and there will be many mount and umount tasks about this pvc executed at the same time. And we find all pods on a node at container creating state, because of waiting pvc to mount.
check log, we can't find any we can't find any operationExecutor.MountVolume started or failed log like "operationExecutor.MountVolume started for"

and also we check  volume_manager_total_volumes metrics, volume is add to dsw.
analyze code, if isExpectedError, kubelet not log any thing
``` golang 
// ignore nestedpendingoperations.IsAlreadyExists and exponentialbackoff.IsExponentialBackoff errors, they are expected.
func isExpectedError(err error) bool {
	return nestedpendingoperations.IsAlreadyExists(err) || exponentialbackoff.IsExponentialBackoff(err)
}
```
and operationExecutor will generate operation, add call pendingOperations Run, pendingOperations Run will check operation slice, to find whether has same operation exists, and if operation exist, will check operation's operationPending status, if equal true, means same operation now is excuting, and return AlreadyExists.
operationKey composed of volumeName, podName, nodeName
``` golang 
// MountVolume Func
// Avoid executing mount/map from multiple pods referencing the
// same volume in parallel
podName := nestedpendingoperations.EmptyUniquePodName

// TODO: remove this -- not necessary
if !volumeToMount.PluginIsAttachable && !volumeToMount.PluginIsDeviceMountable {
	// volume plugins which are Non-attachable and Non-deviceMountable can execute mount for multiple pods
	// referencing the same volume in parallel
	podName = util.GetUniquePodName(volumeToMount.Pod)
}

// TODO mount_device
return oe.pendingOperations.Run(
		volumeToMount.VolumeName, podName, "" /* nodeName */, generatedOperations)
```
so MountVolume operationKey {volumeName, EmptyUniquePodName,EmptyNodeName}, use EmptyUniquePodName to avoid executing mount/map from multiple pods referencing the same volume in parallel

``` golang 
// UnmountVolume Func
// All volume plugins can execute unmount/unmap for multiple pods referencing the
	// same volume in parallel
	podName := volumetypes.UniquePodName(volumeToUnmount.PodUID)

	return oe.pendingOperations.Run(
		volumeToUnmount.VolumeName, podName, "" /* nodeName */, generatedOperations)
```
soUnmountVolume operationKey {volumeName, podUID,EmptyNodeName}, because All volume plugins can execute unmount/unmap for multiple pods referencing the same volume in parallel

now see isOperationExists func, if previousOp.podName equals to EmptyUniquePodName  or current operation podName  equals to EmptyUniquePodName, will return podNameMatch, mount operation can find  umount operation or umount operation can find mount operation
``` golang 
// This is an internal function and caller should acquire and release the lock
func (grm *nestedPendingOperations) isOperationExists(key operationKey) (bool, int) {

	// If volumeName is empty, operation can be executed concurrently
	if key.volumeName == EmptyUniqueVolumeName {
		return false, -1
	}

	for previousOpIndex, previousOp := range grm.operations {
		volumeNameMatch := previousOp.key.volumeName == key.volumeName

		podNameMatch := previousOp.key.podName == EmptyUniquePodName ||
			key.podName == EmptyUniquePodName ||
			previousOp.key.podName == key.podName

		nodeNameMatch := previousOp.key.nodeName == EmptyNodeName ||
			key.nodeName == EmptyNodeName ||
			previousOp.key.nodeName == key.nodeName

		if volumeNameMatch && podNameMatch && nodeNameMatch {
			return true, previousOpIndex
		}
	}

	return false, -1
}
``` 

``` golang 
func (grm *nestedPendingOperations) Run(
	volumeName v1.UniqueVolumeName,
	podName volumetypes.UniquePodName,
	nodeName types.NodeName,
	generatedOperations volumetypes.GeneratedOperations) error {
	grm.lock.Lock()
	defer grm.lock.Unlock()

	opKey := operationKey{volumeName, podName, nodeName}

	opExists, previousOpIndex := grm.isOperationExists(opKey)
	if opExists {
		previousOp := grm.operations[previousOpIndex]
		// Operation already exists
		if previousOp.operationPending {
			// Operation is pending
			return NewAlreadyExistsError(opKey)
		}

		backOffErr := previousOp.expBackoff.SafeToRetry(fmt.Sprintf("%+v", opKey))
		if backOffErr != nil {
			if previousOp.operationName == generatedOperations.OperationName {
				return backOffErr
			}
			// previous operation and new operation are different. reset op. name and exp. backoff
			grm.operations[previousOpIndex].operationName = generatedOperations.OperationName
			grm.operations[previousOpIndex].expBackoff = exponentialbackoff.ExponentialBackoff{}
		}

		// Update existing operation to mark as pending.
		grm.operations[previousOpIndex].operationPending = true
		grm.operations[previousOpIndex].key = opKey
	} else {
		// Create a new operation
		grm.operations = append(grm.operations,
			operation{
				key:              opKey,
				operationPending: true,
				operationName:    generatedOperations.OperationName,
				expBackoff:       exponentialbackoff.ExponentialBackoff{},
			})
	}

	go func() (eventErr, detailedErr error) {
		// Handle unhandled panics (very unlikely)
		defer k8sRuntime.HandleCrash()
		// Handle completion of and error, if any, from operationFunc()
		defer grm.operationComplete(opKey, &detailedErr)
		return generatedOperations.Run()
	}()

	return nil
}
```  
because of isOperationExists, this mean if a volume now is excuting mount, a umount can't add to operations, and if a umount  now is excuting, a mount operation can't add to operations, but  multiple pods referencing the same volume can add multiple umount operation into operation, may lead operation leak.
```
t0 Operations: {umount, pvname, pod1, pending=true} {umount, pvname, pod2, pending=true}
t1 Operations: {umount, pvname, pod1, pending=false} {umount, pvname, pod2, pending=true}
t2 Operations: {mount, pvname, EmptyUniquePodName, pending=true} {umount, pvname, pod2, pending=true}
t3 Operations: {mount, pvname, EmptyUniquePodName, pending=false} {umount, pvname, pod2, pending=true}
t4 Operations: {umount, pvname, pod2, pending=true} {umount, pvname, pod2, pending=true}
t5 Operations: {umount, pvname, pod2, pending=false} {umount, pvname, pod2, pending=true}
t6 Operations: {umount, pvname, pod2, pending=true}
```
t0 two pod do umount volume operation
t1 pod1 umount failed,  update pending to false
t2 pod3 add, operation excuter add mount operation, will use index 0, override umount operation
t3 mount operation failed , update pending to false
t4 pod2 umount operation add, will find index 0, add override opertation, now ,we have two same umount operation, now we have two goroutines to do pod2 umount operations
t5 first goroutine pod2 umount failed, will update index 0 operation, update pending to false
t6 second goroutine pod2 umount success, will delete index 0 operation,
finally lead a umount opertion in cache, and this operation will lead all mount opeartion  return AlreadyExistsError, and not cause any csi call.

and i think there  exists some other scene can trigger this leak.

and also, when operation success, deleteOperation, will use tail element to replace, and may increase the probalility of occurrence. because isOperationExists will always pick first match one.
```
func (grm *nestedPendingOperations) deleteOperation(key operationKey) {
	// Assumes lock has been acquired by caller.

	opIndex := -1
	for i, op := range grm.operations {
		if op.key.volumeName == key.volumeName &&
			op.key.podName == key.podName &&
			op.key.nodeName == key.nodeName {
			opIndex = i
			break
		}
	}

	if opIndex < 0 {
		return
	}

	// Delete index without preserving order
	grm.operations[opIndex] = grm.operations[len(grm.operations)-1]
	grm.operations = grm.operations[:len(grm.operations)-1]
}
```

and also override  mechanism may lead exponentialBackOff invalid， for example mount and umount take turns to excute.

### What did you expect to happen?

pv can mount , pod can running

### How can we reproduce it (as minimally and precisely as possible)?

reproduce step:
create same cronjob that use same pvc(use csi sfs)
and csi driver restart periodic

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
1.23

### Cloud provider

<details>
HuaweiCloud
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
CSI

### PR DESCRIPTION
**Pull request by 249043822**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
We have committed the refactor version for nestedPendingOperations https://github.com/kubernetes/kubernetes/pull/109190,
but it is a big change and may bring unknown risks and would be landed for a long time, so I think we can use a smaller way to fix bug first, and promote a nice refactor in next step.
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/109047

#### Special notes for your reviewer:
/cc @jingxu97 @gnufied @Dingshujie 
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go [hunk 1]
```diff
@@ -244,21 +244,37 @@ func (grm *nestedPendingOperations) isOperationExists(key operationKey) (bool, i
...
+				return true, previousOpIndex
+			}
+			// nonExactMatch with no pending, set opIndex to the first nonExactMatch
+			// exactMatch can override opIndex to expected
+			if opIndex == -1 || (podNameExactMatch && nodeNameExactMatch) {
+				opIndex = previousOpIndex
+			}
 		}
 	}
+	if opIndex != -1 {
```
Comment (Dingshujie) [inline pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:275]:
``` go
return opIndex != -1, opIndex
```

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go [hunk 2]
```diff
@@ -759,6 +759,146 @@ func Test_NestedPendingOperations_Positive_Issue_88355(t *testing.T) {
...
+	grm := NewNestedPendingOperations(true /* exponentialBackOffOnError */)
+	volumeName := v1.UniqueVolumeName("test-volume")
+	podName1 := volumetypes.UniquePodName("pod1")
+	podName2 := volumetypes.UniquePodName("pod2")
+	podName3 := volumetypes.UniquePodName("pod3")
+	podName4 := EmptyUniquePodName
+	nodeName := EmptyNodeName
+	// delay after an operation is signaled to finish to ensure it actually
+	// finishes before running the next operation.
+	delay := 600 * time.Millisecond
```
Comment (Dingshujie) [inline pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go:841]: 600 Millisecond may be too long, we can use CompleteFunc 
``` go
operation1DoneCh := make(chan struct{})
completeFunc := func(c types.CompleteFuncParam) {
  operation1DoneCh <- struct{}{}
}
err1 := grm.Run(volumeName, podName1, nodeName /* nodeName */, volumetypes.GeneratedOperations{OperationFunc: errorFunc,CompleteFunc:  completeFunc ,OperationName: "umount"})
if err1 != nil {
}
<- operation1DoneCh
```

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go (hunk 1 above)
Comment (249043822) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go]: Done

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go (hunk 2 above)
Comment (249043822) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go]: Good point,  but `CompleteFunc ` is still called before `operationComplete`, so it could not guarantee that the last operation was complete.  Now I reduce the delay and split to a backoff delay, if there are other nice handlers, iI will refresh again. thanks

**Review by yangjunmyfm192085 — COMMENTED** [review]
/retest

**Review by yangjunmyfm192085 — COMMENTED** [review]
Maybe we have to wait for this pr to merge?
https://github.com/kubernetes/kubernetes/pull/110980

**Review by yangjunmyfm192085 — COMMENTED** [review]
/retest

**Comment by Dingshujie** [comment]
@kubernetes/sig-node-pr-reviews

**Comment by jingxu97** [comment]
@249043822 thank you for the PR!

Could you please compare your change and this WIP change I made before https://github.com/kubernetes/kubernetes/pull/109343/files? Thanks!

**Comment by 249043822** [comment]
> @249043822 thank you for the PR!
> 
> Could you please compare your change and this WIP change I made before https://github.com/kubernetes/kubernetes/pull/109343/files? Thanks!

@jingxu97 Yes, I have compared yet, maybe the change you committed could not meet the exact match first while has no pending operations,  the test cases as below which was provided by @Dingshujie 

t0 Operations: {umount, pvname2, pod2, mount, pending=true} {umount, pvname, pod1, pending=true} {umount, pvname, pod2, pending=true}
t1 Operations: {umount, pvname2, pod2, mount, pending=true} {umount, pvname, pod1, pending=false} {umount, pvname, pod2, pending=false} // two umount failed
t2 Operations: {umount, pvname2, pod2, mount, pending=true} {mount, pvname, EmptyUniquePodName, pending=true} {umount, pvname, pod2, pending=false} // add pvname mount
t3 Operations: {umount, pvname2, pod2, mount, pending=true} {mount, pvname, EmptyUniquePodName, pending=false} {umount, pvname, pod2, pending=false} // pvname mount failed
t4 Operations: {umount, pvname2, pod2, mount, pending=true} {umount, pvname, pod2, pending=true} {umount, pvname, pod2, pending=false} // pvname pod2 umount add
t5 Operations: {umount, pvname, pod2, pending=false} {umount, pvname, pod2, pending=true} // pvname2 umount success, replace index 0 with index 2, and delete index 2
t6 Operations: {umount, pvname, pod2, pending=true} // umount pod2 success, delete index 0

maybe in this case, also leak a operation can block pv mount

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go [hunk 3]
```diff
@@ -244,23 +244,36 @@ func (grm *nestedPendingOperations) isOperationExists(key operationKey) (bool, i
...
-			return true, previousOpIndex
+			// nonExactMatch pending first
+			if previousOp.operationPending {
+				return true, previousOpIndex
+			}
+			// nonExactMatch with no pending, set opIndex to the first nonExactMatch
+			// exactMatch can override opIndex to expected
+			if opIndex == -1 || (podNameExactMatch && nodeNameExactMatch) {
+				opIndex = previousOpIndex
+			}
```
Comment (gnufied) [inline pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:272]: There is another correctness issue I see here, if:

a. {pod1,vol1, umount} -> enqueued
b. {pod2, vol1, umount} -> enqueued
c. {pod1, vol1, umount, pending=false (fail} {pod2, vol1, umount, pending=true}
d. {pod3, vol1, mount} -> enqued

In step#d - mount operation replaces unmount operation in step#c at index-0. Whereas strictly speaking, mount function contract says, we should not call mount operation if any other operation on same volume is pending (even if it is happening on a different pod).

So correct me if I am wrong but this PR does not fixes that behavior. We could still call mount on same volume, while another pod is trying to unmount the volume and unmount operation is pending.

Comment (gnufied) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:272]: err - actually I think I was wrong. We do prefer pending operations first and hence we don't break that contract.

**Comment by gnufied** [comment]
So the only issue here is - we are going to be scanning entire `operations` here, but it may not be that big of a deal or we can handle that in a follow up PR.

/lgtm

**Comment by itroyano** [comment]
Hi @gnufied,
Any way to append the volume name and/or node name to the UniqueName to make it "more" unique?
In case it's a RWX volume that could be mounted and unmounted in parallel to/from multiple pods on multiple nodes.

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go [hunk 4]
```diff
@@ -759,6 +759,151 @@ func Test_NestedPendingOperations_Positive_Issue_88355(t *testing.T) {
...
+	// Assert
+	// operation4 override operation1 or operation3, and operation5 will override operation2,
+	// so finally, only operation4, operation1 or operation3 left
+	grm.(*nestedPendingOperations).lock.Lock()
+	defer grm.(*nestedPendingOperations).lock.Unlock()
+	l := len(grm.(*nestedPendingOperations).operations)
+	if l != 2 {
+		t.Errorf("NestedPendingOperations length should return 2, got: %v", l)
+	}
+}
```
Comment (gnufied) [inline pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go:905]: I don't think these tests exercise the bug under question correctly. They are passing without the changes into nestedpendingoperations file.

**Comment by gnufied** [comment]
@itroyano - Both mount and unmount operation already have volume name in their key and hence multiple mount operations on same volume can't proceed. 

We however do allow, multiple unmount operation on same volume to proceed (if they are being used by different pods) and that is by design.

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go (hunk 4 above)
Comment (249043822) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go:905]: @gnufied Actually ` grm.Run` would call isOperationExists to do the operations, so I think these tests cover these modifications

Comment (gnufied) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go:905]: I am not sure. I tried running the tests without incorporating any of the changes from nestedpending_operations file (that is the actual code change) and the test still pass. Am i missing something? Will tests fail in unpredictable manner without the change but do not reproduce the bug 100% of the time?

Comment (249043822) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go:905]: @gnufied okay, i see, will fix these tests in next push

File: pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go [hunk 5]
```diff
@@ -879,3 +879,141 @@ func waitChannelWithTimeout(ch <-chan interface{}, timeout time.Duration) error
...
+	if err5 != nil {
+		t.Errorf("NestedPendingOperations failed. Expected: <no error> Actual: <%v>", err5)
+	}
+	time.Sleep(delay)
+
+	// Assert
+	// operation4 override operation1 or operation3, and operation5 will override operation2,
+	// so finally, only operation4, operation1 or operation3 left
+	grm.(*nestedPendingOperations).lock.Lock()
+	defer grm.(*nestedPendingOperations).lock.Unlock()
```
[the remark this answers is not in the document]
Comment (249043822) [reply pkg/volume/util/nestedpendingoperations/nestedpendingoperations_test.go:1011]: @gnufied Done

**Comment by gnufied** [comment]
@249043822 can you cherry pick to 1.25, 1.24 and 1.23?

**Comment by 249043822** [comment]
> @249043822 can you cherry pick to 1.25, 1.24 and 1.23?

np
