### PR TITLE
Declare ipvs proxier beta in v1.9

### LINKED ISSUE #51602: Task tracker of IPVS beta
There are some work to be done in the follow-up of #46580, that is, help IPVS existing alpha.

- [x] GCE CI failures(#54916)

- [x] cross-node visit NodePort (#53393)

- [x] hairpin issue (#53775)

- [x] Using ipset doing snat and packet filtering and reduce iptables call(#54203).

- [x] automatically load `ip_vs_*` kernel modules. (#51874, #52003)

- [x] creating e2e test suite for IPVS in upstream CI (#52834).

- [x] ip cmd -> netlink bind/unbind IP address to/from dummy device(#51686)

- [x] rsync to HEAD of iptables(#51682, #52014)

- [x] enable flush batch API(#52015)

- [x] Fix TODOs in codes (#52403)

- [x] Bug report (#51694, #52330)

- [x] Default sync period(#51777)

 - [x] IPV6 support(#52935, #53120  and more...)

/cc @thockin @quinton-hoole @haibinxie

### PR DESCRIPTION
**Pull request by m1093782566**
**What this PR does / why we need it**:

This PR declares ipvs proxier beta - we have finished all tasks in IPVS proxier beta scope.

**Which issue(s) this PR fixes**:
Fixes #51602

**Special notes for your reviewer**:

**Release note**:

```release-note
Declare ipvs proxier beta
```

### CODE REVIEW

File: pkg/features/kube_features.go [hunk 1]
```diff
@@ -251,6 +251,7 @@ var defaultKubernetesFeatureGates = map[utilfeature.Feature]utilfeature.FeatureS
 	BlockVolume:                                 {Default: false, PreRelease: utilfeature.Alpha},
 	PVCProtection:                               {Default: false, PreRelease: utilfeature.Alpha},
 	ResourceLimitsPriorityFunction:              {Default: false, PreRelease: utilfeature.Alpha},
+	SupportIPVSProxyMode:                        {Default: false, PreRelease: utilfeature.Beta},
```
Comment (thockin) [inline pkg/features/kube_features.go]: So some flag gate is still required but it is not considered alpha, right?

Comment (m1093782566) [reply pkg/features/kube_features.go]: Yes, that's true. Any problems?

**Comment by enisoc** [comment]
Exception [approved](https://groups.google.com/forum/#!topic/kubernetes-milestone-burndown/pU-sDltAdtE).
