### PR TITLE
fix yaml decode issue

### LINKED ISSUE #33588: Kubectl 1.4 does not trim --- seperator
**Kubernetes version** (use `kubectl version`):
```
Client: 1.4.0
Server: 1.4.0
```

**Environment**:
- **Cloud provider or hardware configuration**: Any
- **OS** (e.g. from /etc/os-release): Any
- **Kernel** (e.g. `uname -a`): Any
- **Install tools**: Any

**What happened**:
 If I use a template with the `---` seperator, and if the line with the separator has trailing whitespace characters, then kubectl considers that to be the EOF instead of reading further. 

e.g. template 

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: testnginx
spec:
  replicas: 2
  selector:
    name: testnginx
  template:
    metadata:
      labels:
        name: testnginx
    spec:
      containers:
        - name: testnginx
          image: nginx
          ports:
            - containerPort: 80

---    

apiVersion: v1
kind: Service
metadata:
  name: testnginx
  labels:
    name: testnginx
    type: ui
spec:
  ports:
  - port: 8000
    targetPort: 80
  selector:
    name: testnginx
```

**What you expected to happen**:

It should not stop reading if there are trailing whitespace characters, it should just trim the separator line and ignore the whitespaces after the `---`.

This is how it worked until v1.3.0 kubectl version.

**How to reproduce it** (as minimally and precisely as possible):

Just use the template from above and you'll notice that it won't create the Service, but it'll create the Replication controller.

**Anything else do we need to know**:
This is on kubectl version 1.4.0

### PR DESCRIPTION
**Pull request by adohe-zz**
fix #33588

@janetkuo @smarterclayton ptal.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34297)

### CODE REVIEW

**Comment by AdoHe** [comment]
#34345 seems still some problem

File: pkg/util/yaml/decoder.go [hunk 1]
```diff
@@ -246,16 +246,28 @@ func (r *YAMLReader) Read() ([]byte, error) {
 			return nil, err
 		}
 
-		if string(line) == separator || err == io.EOF {
+		sep := len([]byte(separator))
+		if i := bytes.Index(line, []byte(separator)); i == 0 {
```
Comment (smarterclayton) [inline pkg/util/yaml/decoder.go]: nit: this should be HasPrefix since this is moderately performance sensitive.  Can you do a small follow up (or open an issue)?

Comment (AdoHe) [inline pkg/util/yaml/decoder.go]: sure, thanks @smarterclayton
