### PR TITLE
Fix kubelet panic when allocate resource for pod.

### LINKED ISSUE #119560: Kubelet panic when allocates device for pods.
### What happened?

It is suspected to be a concurrent bug of kubelet.

When we delete the last pod that requires GPU on the node and create two or more pods that require GPU at the same time, kubelet may panic on `allocateContainerResources` as following.

I think it's a concurrency issue.

1. Create a pod with GPU request, then kubelet will allocate resource for it. Kubelet try call device plugin to choose preferred device for it. **It will unlock the mutex!.** https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/devicemanager/manager.go#L984-L1006
2. Then we delete the last pod that requires GPU.
3. Create the second pod with GPU request, kubelet will allocate resource for it also. Kubelet will call `UpdateAllocatedDevices` to recalculate device (delete allocated device if pod deleted). It will update the **allocatedDevices** map of ManagerImpl, because of mutex is unlock by step 1. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/devicemanager/manager.go#L519-L543
4.  Kubelet continues with the first pod. If **allocatedDevices** has changed and GPU device is nil, kubelet will panic in the closure allocateRemainingFrom.

```
Jul 25 16:39:40 VM-253-55-tencentos kubelet[2957693]: W0725 16:39:40.980267 2957693 http2_server.go:568] [transport] transport: http2Server.HandleStreams failed to read frame: read unix /var/lib/kubelet/pod-resources/4246784729->@: read: connection reset by peer
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: panic: assignment to entry in nil map
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: goroutine 409 [running]:
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets.String.Insert(...)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: vendor/k8s.io/apimachinery/pkg/util/sets/string.go:51
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).devicesToAllocate.fun
c1(0xc001e8a540?)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/devicemanager/manager.go:720 +0x2d2
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).devicesToAllocate(0xc
0004520e0, {0xc002e00d50, 0x24}, {0xc004610db8, 0x7}, {0xc004610f10, 0xe}, 0x8, 0x200?)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/devicemanager/manager.go:784 +0x101b
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).allocateContainerReso
urces(0xc0004520e0, 0xc000bff9e0?, 0xc002e00d50?, 0x24?)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/devicemanager/manager.go:924 +0x347
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).Allocate(0xc0004520e0
, 0xc004194400, 0xc003902420)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/devicemanager/manager.go:400 +0x1f0
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*scope).allocateAlignedResources(
0x4607040?, 0xc003902580?, 0x50?)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/topologymanager/scope.go:145 +0x79
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*scope).admitPolicyNone(0x7f4693e
a23c8?, 0xc004194400)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/topologymanager/scope.go:133 +0x22c
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*containerScope).Admit(0xc000235e
a0, 0xc004194400)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/topologymanager/scope_container.go:49 +0x90
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*manager).Admit(0xc000793e70, 0xc
00099bee0)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/topologymanager/topology_manager.go:203 +0xaa
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).canAdmitPod(0xc000bd1800, {0xc002c7d0e0, 0
xe, 0x13}, 0xc004194400)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/kubelet.go:1995 +0x143
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).HandlePodAdditions(0xc000bd1800, {0xc0018c
4788?, 0x1, 0x1})
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/kubelet.go:2300 +0x29d
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoopIteration(0xc000bd1800, 0xc0002b61
20, {0x4dc8168, 0xc000bd1800}, 0xc001eea000, 0xc001eea060, 0xc0011d65a0)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/kubelet.go:2114 +0xb9b
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoop(0xc000bd1800, 0xc000056960?, {0x4
dc8168, 0xc000bd1800})
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/kubelet.go:2057 +0x2f7
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run(0xc000bd1800, 0x0?)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/kubelet.go:1461 +0x6d7
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: created by k8s.io/kubernetes/cmd/kubelet/app.startKubelet
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: cmd/kubelet/app/server.go:1188 +0xaa
```

### What did you expect to happen?

Don't panic.

### How can we reproduce it (as minimally and precisely as possible)?

Delete the last pod that requires GPU on the node and create two or more pods that require GPU at the same time.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubelet --version
Kubernetes v1.24.4
```

</details>

### Cloud provider

<details>
external
</details>

### OS version

<details>

```console
NAME="TencentOS Server"
VERSION="2.4"
ID="tencentos"
ID_LIKE="rhel fedora centos tlinux"
VERSION_ID="2.4"
PRETTY_NAME="TencentOS Server 2.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:tencentos:tencentos:2"
HOME_URL="https://cloud.tencent.com/product/ts"
```
</details>

### Install tools

NOOP

### Container runtime (CRI) and version (if applicable)

<details>
Containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

NOOP

### PR DESCRIPTION
**Pull request by payall4u**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix kubelet panic when allocate resource for pod.

#### Which issue(s) this PR fixes:

Fixes #119560 

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by gjkim42** [comment]
> Fixes #119560

I think it would be better to make a test to reproduce the bug and make sure it is fixed by this patch.

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 1]
```diff
@@ -631,13 +630,22 @@ func (m *ManagerImpl) devicesToAllocate(podUID, contName, resource string, requi
 		m.allocatedDevices[resource] = sets.NewString()
 	}
 
+	defer func() {
+		if err == nil {
+			if m.allocatedDevices[resource] == nil {
+				m.allocatedDevices[resource] = sets.NewString()
```
Comment (ffromani) [inline pkg/kubelet/cm/devicemanager/manager.go:636]: I think I'm missing something here. Which flows may possible set this to `nil`?
Once `allocatedDevices[resource]` is initialized, is never reset to nil explicitely and it's explicitely assigned only to the return value of `podDevices.devices()`, which can never be nil.

I for myself I like updating allocation once everything completed, but I'm wondering if this approach plays nice with the overall design (see comment at line 834-845). Perhaps we should review that part, but this is a much larger endeavour.

**Comment by bart0sh** [comment]
/triage accepted
/priority important-soon

@payall4u please provide release note

**Comment by payall4u** [comment]
> 

Done. I'm trying to write a unit test for the case.

**Comment by payall4u** [comment]
> /triage accepted /priority important-soon
> 
> @payall4u please provide release note

Done. I'm trying to write UT for this case.

**Comment by payall4u** [comment]
I add a unit test for the conflict between function `devicesToAllocate` and function `UpdateAllocatedDevices`.

In the master branch, the result is:
```
=== RUN   TestDevicesToAllocateConflictWithUpdateAllocatedDevices
I1009 09:41:32.999148   51633 stub.go:143] "Starting to serve on socket" socket="/var/folders/y7/sk_zl50j2zj424vyqqqbgy7h0000gn/T/mock1696815692997801000.sock"
I1009 09:41:32.999527   51633 fake_topology_manager.go:33] "NewFakeManager"
I1009 09:41:32.999629   51633 fake_topology_manager.go:55] "GetAffinity" podUID="podToAllocate" containerName="containerToAllocate"
I1009 09:41:33.000211   51633 stub.go:258] "GetPreferredAllocation" request="&PreferredAllocationRequest{ContainerRequests:[]*ContainerPreferredAllocationRequest{&ContainerPreferredAllocationRequest{AvailableDeviceIDs:[deviceId],MustIncludeDeviceIDs:[],AllocationSize:1,},},}"
--- FAIL: TestDevicesToAllocateConflictWithUpdateAllocatedDevices (0.00s)
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 108 [running]:
testing.tRunner.func1.2({0x103b430a0, 0x103dfc078})
	/opt/homebrew/opt/go/libexec/src/testing/testing.go:1545 +0x1c8
testing.tRunner.func1()
	/opt/homebrew/opt/go/libexec/src/testing/testing.go:1548 +0x360
panic({0x103b430a0?, 0x103dfc078?})
	/opt/homebrew/opt/go/libexec/src/runtime/panic.go:914 +0x218
k8s.io/apimachinery/pkg/util/sets.Set[...].Insert(0x103e3ef20?, {0x14000549a58, 0x1?, 0x1})
	/Users/lambda/Code/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets/set.go:50 +0x58
k8s.io/apimachinery/pkg/util/sets.String.Insert(...)
	/Users/lambda/Code/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets/string.go:40
k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).devicesToAllocate.func1(0x14000614630?)
	/Users/lambda/Code/kubernetes/pkg/kubelet/cm/devicemanager/manager.go:619 +0xec
k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).devicesToAllocate(0x14000698270, {0x1036800cb, 0xd}, {0x10368abb4, 0x13}, {0x10368cc2b, 0x14}, 0x1, 0x0?)
	/Users/lambda/Code/kubernetes/pkg/kubelet/cm/devicemanager/manager.go:683 +0xe08
k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.TestDevicesToAllocateConflictWithUpdateAllocatedDevices(0x14000589701?)
	/Users/lambda/Code/kubernetes/pkg/kubelet/cm/devicemanager/manager_test.go:1241 +0x648
testing.tRunner(0x14000583040, 0x103df5fe0)
	/opt/homebrew/opt/go/libexec/src/testing/testing.go:1595 +0xe8
created by testing.(*T).Run in goroutine 1
	/opt/homebrew/opt/go/libexec/src/testing/testing.go:1648 +0x33c
```

In the bugfix branch, result is:
```
=== RUN   TestDevicesToAllocateConflictWithUpdateAllocatedDevices
I1009 09:49:28.167885   55672 stub.go:143] "Starting to serve on socket" socket="/var/folders/y7/sk_zl50j2zj424vyqqqbgy7h0000gn/T/mock1696816168166239000.sock"
I1009 09:49:28.168174   55672 fake_topology_manager.go:33] "NewFakeManager"
I1009 09:49:28.168264   55672 fake_topology_manager.go:55] "GetAffinity" podUID="podToAllocate" containerName="containerToAllocate"
I1009 09:49:28.168827   55672 stub.go:258] "GetPreferredAllocation" request="&PreferredAllocationRequest{ContainerRequests:[]*ContainerPreferredAllocationRequest{&ContainerPreferredAllocationRequest{AvailableDeviceIDs:[deviceId],MustIncludeDeviceIDs:[],AllocationSize:1,},},}"
--- PASS: TestDevicesToAllocateConflictWithUpdateAllocatedDevices (0.00s)
PASS
```

It's look like that the problem has been fixed.

P.S. Sorry for late to deal here.

**Comment by ffromani** [comment]
thanks for keep working on this PR! I'll have another look ASAP. Let's make sure current e2e tests work fine.

**Comment by payall4u** [comment]
> failures need to be reviewed (I'll take care later), they are not necessarily blockers for this fix

Ok, thx.

**Comment by payall4u** [comment]
ping @ffromani

**Comment by payall4u** [comment]
ping @ffromani @klueska

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 2]
```diff
@@ -631,13 +630,22 @@ func (m *ManagerImpl) devicesToAllocate(podUID, contName, resource string, requi
...
 	}
 
+	defer func() {
+		if err == nil {
+			if m.allocatedDevices[resource] == nil {
+				m.allocatedDevices[resource] = sets.New[string]()
+			}
+			m.allocatedDevices[resource] = m.allocatedDevices[resource].Union(allocated)
+		}
+	}()
```
Comment (bart0sh) [inline pkg/kubelet/cm/devicemanager/manager.go:640]: @payall4u Can you explain how and why this PR fixes concurrent access to the `m.allocatedDevices` from `allocateContainerResources` and  `UpdateAllocatedDevices` ?

Comment (payall4u) [reply pkg/kubelet/cm/devicemanager/manager.go:640]: Sure. When call `callGetPreferredAllocationIfAvailable`, current goroutine when release the lock and call device plugin. 
If some call ListResource of resource server, devicemanager will recalculate the allocatedDevices map. It will remove some map entry if the resource has be released already.
https://github.com/kubernetes/kubernetes/blob/v1.28.0-beta.0/pkg/kubelet/apis/podresources/server_v1.go#L58

When return from `callGetPreferredAllocationIfAvailable`, the map entry is nil. So we shoud reinit the device set.

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 3]
```diff
@@ -616,7 +616,6 @@ func (m *ManagerImpl) devicesToAllocate(podUID, contName, resource string, requi
 	// Returns 'true' once no more devices need to be allocated.
 	allocateRemainingFrom := func(devices sets.Set[string]) bool {
 		for device := range devices.Difference(allocated) {
-			m.allocatedDevices[resource].Insert(device)
```
Comment (bart0sh) [inline pkg/kubelet/cm/devicemanager/manager.go:619]: Would reinitializing `m.allocatedDevices[resource]` here if it's nil help and, if it wouldn't, why?

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 2 above)
Comment (bart0sh) [reply pkg/kubelet/cm/devicemanager/manager.go:644]: I generally understood the idea, but it's still quite hard to grasp it. I agree with @ffromani, this code is asking for refactoring.

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 3 above)
Comment (payall4u) [reply pkg/kubelet/cm/devicemanager/manager.go:619]: I think it is helpful, and the unit test seems to be working well. 
However, the closure `allocateRemainingFrom` is doing too much here: updating both allocatedDevices and the temporary variable allocated. I perfer having the closure only keep the devices allocated on the way and then save the records into allocatedDevices at the end.
Either is fine, and I'd like to hear your thoughts on them.

Comment (payall4u) [reply pkg/kubelet/cm/devicemanager/manager.go:619]: It looks similar to the code below.
``` go
allocateRemainingFrom := func(devices sets.Set[string]) bool {
	if m.allocatedDevices[resource] == nil {
		m.allocatedDevices[resource] = sets.New[string]()
	}
	for device := range devices.Difference(m.allocatedDevices[resource]) {
		m.allocatedDevices[resource].Insert(device)
		allocated.Insert(device)
		needed--
		if needed == 0 {
			return true
		}
	}
	return false
}
```

Comment (bart0sh) [reply pkg/kubelet/cm/devicemanager/manager.go:619]: It looks more understandable, but I agree with you here.
However, I'd rather use some kind of locks to avoid this data race.

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 4]
```diff
@@ -544,7 +544,7 @@ func (m *ManagerImpl) UpdateAllocatedDevices() {
 
 // Returns list of device Ids we need to allocate with Allocate rpc call.
 // Returns empty list in case we don't need to issue the Allocate rpc call.
-func (m *ManagerImpl) devicesToAllocate(podUID, contName, resource string, required int, reusableDevices sets.Set[string]) (sets.Set[string], error) {
+func (m *ManagerImpl) devicesToAllocate(podUID, contName, resource string, required int, reusableDevices sets.Set[string]) (strings sets.Set[string], err error) {
```
Comment (bart0sh) [inline pkg/kubelet/cm/devicemanager/manager.go:547]: why do we need this?

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 3 above)
Comment (bart0sh) [reply pkg/kubelet/cm/devicemanager/manager.go:619]: do we still need this code below:
```
	// Needs to allocate additional devices.
	if m.allocatedDevices[resource] == nil {
		m.allocatedDevices[resource] = sets.New[string]()
	}
```

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 4 above)
Comment (payall4u) [reply pkg/kubelet/cm/devicemanager/manager.go:547]: It can be removed now 😁

**Comment by bart0sh** [comment]
@payall4u I don't think we still need this code on lines 629-632
```
	// Needs to allocate additional devices.
	if m.allocatedDevices[resource] == nil {
		m.allocatedDevices[resource] = sets.New[string]()
	}
```

**Comment by payall4u** [comment]
> @payall4u I don't think we still need this code on lines 629-632
> 
> ```
> 	// Needs to allocate additional devices.
> 	if m.allocatedDevices[resource] == nil {
> 		m.allocatedDevices[resource] = sets.New[string]()
> 	}
> ```

Right.

**Comment by payall4u** [comment]
Sorry, I need you to give it another review. @bart0sh

**Comment by payall4u** [comment]
ping @bart0sh

**Comment by bart0sh** [comment]
/lgtm
@payall4u sorry for the review delay, I was on vacation.

**Comment by payall4u** [comment]
Hi @bart0sh @SergeyKanzhelev 

How about fix this in 1.30 and cherry-pick to 1.29 ?

**Comment by bart0sh** [comment]
> How about fix this in 1.30 and cherry-pick to 1.29 ?

sounds good to me

**Comment by pacoxu** [comment]
/remove-lifecycle stale
/lgtm
/approve
/assign @mrunalp @SergeyKanzhelev 
for approval

**Comment by payall4u** [comment]
Ping @mrunalp @SergeyKanzhelev
