### PR TITLE
fix: parsing the patch directly

### LINKED ISSUE #133297: Failure TestSchedulerScheduleOne
##### Error text:
```
Failed
=== RUN   TestSchedulerScheduleOne/prebind_failed_with_status_code_error_(Queueing_hints_enabled:_true,_Async_API_calls_enabled:_false,_NominatedNodeNameForExpectation_enabled:_true)
    schedule_one_test.go:1084: Expected nominated node name "node1", got ""
--- FAIL: TestSchedulerScheduleOne/prebind_failed_with_status_code_error_(Queueing_hints_enabled:_true,_Async_API_calls_enabled:_false,_NominatedNodeNameForExpectation_enabled:_true) (0.30s)

=== RUN   TestSchedulerScheduleOne
--- FAIL: TestSchedulerScheduleOne (18.55s)

```
#### Recent failures:
[7/30/2025, 5:39:28 AM ci-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit/1950400728660971520)
[7/30/2025, 4:50:10 AM ci-kubernetes-unit-windows-master](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit-windows-master/1950388397763727360)
[7/30/2025, 4:10:08 AM ci-kubernetes-unit-ppc64le](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit-ppc64le/1950376820561940480)
[7/30/2025, 2:06:57 AM ci-kubernetes-unit-ppc64le](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit-ppc64le/1950346621065629696)
[7/30/2025, 1:50:07 AM ci-kubernetes-unit-windows-master](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit-windows-master/1950343098320031744)

/kind failing-test

Image

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

Parse the patch directly, not compute the updated object with the old one, in order to crash this possibility:

> Maybe the second cause is because the informer receives delayed update of a pod? Then, in second patch call, in PrependReactor it gets the old pod object (without NNN) and it overwrites previous updatedNominatedNodeName.
https://github.com/kubernetes/kubernetes/issues/133297#issuecomment-3144527137

#### Which issue(s) this PR is related to:

Fixes: #133297

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
/test pull-kubernetes-unit-windows-master

(The failure was not this test)

File: pkg/scheduler/schedule_one_test.go [hunk 1]
```diff
@@ -1110,13 +1108,16 @@ func TestSchedulerScheduleOne(t *testing.T) {
...
 						}
+						var once sync.Once
 						called := make(chan struct{})
 						stopFunc, err := eventBroadcaster.StartEventWatcher(func(obj runtime.Object) {
-							e, _ := obj.(*eventsv1.Event)
-							if e.Reason != item.eventReason {
-								t.Errorf("got event %v, want %v", e.Reason, item.eventReason)
-							}
-							close(called)
+							once.Do(func() {
```
Comment (macsko) [inline pkg/scheduler/schedule_one_test.go]: Is it possible to receive multiple events in this test?

File: pkg/scheduler/schedule_one_test.go [hunk 2]
```diff
@@ -1036,33 +1036,31 @@ func TestSchedulerScheduleOne(t *testing.T) {
...
-							marshalledPod, err := json.Marshal(pod)
-							if err != nil {
-								t.Fatalf("Failed to marshal the original pod %s/%s: %v", namespace, podName, err)
-							}
-							updated, err := strategicpatch.StrategicMergePatch(marshalledPod, patch, v1.Pod{})
-							if err != nil {
-								t.Fatalf("Failed to apply strategic merge patch %q on pod %#v: %v", patch, marshalledPod, err)
+							statusMap, ok := patchMap["status"]
+							if !ok {
+								return false, nil, nil
```
Comment (macsko) [inline pkg/scheduler/schedule_one_test.go]: This shouldn't happen. You could add an error log here

File: pkg/scheduler/schedule_one_test.go (hunk 1 above)
Comment (sanposhiho) [reply pkg/scheduler/schedule_one_test.go]: I don't remember exactly, but I guessed the previous me tried something and forgot cleaning up? I removed it and confirmed that the tests pass even after that.
