### PR TITLE
Mark volume as uncertain after Unmount* fails

### LINKED ISSUE #100182: NodeStage is not called after NodeUnstage error
#### How to reproduce it (as minimally and precisely as possible):

1. Run a pod that uses a CSI volume that supports NodeStage (such as Ceph RBD)
2. Delete the pod
3. The CSI driver times out when processing NodeUnstage call. It is un-staging the volume in the background and eventually succeeds. (Ceph RBD talks to the storage backed in NodeUnstage and there was some network disruption)
4. Create new pod that uses the same volume on the same node

#### What happened:
kubelet calls only NodePublish. Since the previous NodeUnstage did not succeed, it wrongly assumes that the volume is still NodeStaged.

#### What you expected to happen:
kubelet calls NodeStage + NodePublish, because it can't be sure if the volume is staged or not.
After NodeUnstage error, we should mark volumes as uncertain to make sure NodeStage is called after NodeUnstage returns error.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21

### PR DESCRIPTION
**Pull request by jsafrane**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Mark volume device / volume mount as uncertain after UnmountDevice / UnmountVolume operation fails, because kubelet can't be sure what's the actual state of the volume. Kubelet will then call MountDevice / SetUp to make sure the volume is fully mounted when a new pod wants to use the same volume.

Similarly, update Unmap* calls for block volumes.

#### Which issue(s) this PR fixes:
Fixes: #100182

#### Special notes for your reviewer:

* Added e2e test for NodeUnstage errors, which exercises the UnmountDevice error path.
* Both transient and final errors result in the mount marked as uncertain. IMO it's not safe to assume that a mount is usable even after UnmountVolume / UnmountDevice final error. Better to call SetUp / MountDevice again when the mount is needed.

#### Does this PR introduce a user-facing change?

```release-note
Fixed starting new pods after previous pod timed out unmounting its volumes.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by jsafrane** [comment]
I tried to add e2e tests for the block mode, but the mock driver does not support block volumes.

**Comment by jsafrane** [comment]
Ready for review (I tried to add e2e tests for block mode, but the mock driver does not support block)

cc @gnufied @msau42 @jingxu97 PTAL

File: test/e2e/storage/csi_mock_volume.go [hunk 1]
```diff
@@ -897,6 +897,128 @@ var _ = utils.SIGDescribe("CSI mock volume", func() {
...
+					{expectedMethod: "NodeUnstageVolume", expectedError: codes.OK},
+					{expectedMethod: "NodeStageVolume", expectedError: codes.OK},
+					{expectedMethod: "NodeUnstageVolume", expectedError: codes.OK},
+				},
+			},
+			{
+				name: "two pods: should call NodeStage after previous NodeUnstage final error",
+				expectedCalls: []csiCall{
+					{expectedMethod: "NodeStageVolume", expectedError: codes.OK},
+					{expectedMethod: "NodeUnstageVolume", expectedError: codes.InvalidArgument},
```
Comment (jingxu97) [inline test/e2e/storage/csi_mock_volume.go:932]: For InvalidArgument, do we need to mark as uncertain?

Comment (jsafrane) [reply test/e2e/storage/csi_mock_volume.go:932]: It's an example of a "final" response, where we can be reasonably sure that e.g. provisioning is not in progress. Not sure if we can apply the same logic to Unstage.

**Comment by jingxu97** [comment]
PR lgtm. just want to make sure other reviewers have a chance to take a look.

**Comment by gnufied** [comment]
Just planning to take a look today.

/hold

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 2]
```diff
@@ -1309,6 +1351,17 @@ func (og *operationGenerator) GenerateUnmapDeviceFunc(
...
+		// cases below. The volume is marked as fully un-mapped at the end of this function, when everything
+		// succeeds.
+		markDeviceUncertainErr := actualStateOfWorld.MarkDeviceAsUncertain(
+			deviceToDetach.VolumeName, deviceToDetach.DevicePath, globalMapPath)
+		if markDeviceUncertainErr != nil {
+			// On failure, return error. Caller will log and retry.
+			eventErr, detailedErr := deviceToDetach.GenerateError("UnmapDevice.MarkDeviceAsUncertain failed", markDeviceUncertainErr)
+			return volumetypes.NewOperationContext(eventErr, detailedErr, migrated)
+		}
+
```
Comment (gnufied) [inline pkg/volume/util/operationexecutor/operation_generator.go:1364]: I see that we are marking device as uncertain even before unstage operation has started. This means that if `TearDownDevice` fails for a reason that is final (i.e which tells us unstage never really started) - then volume will still be treated as uncertain and hence a full stage has to be performed to make the volume usable again. 

This seems very different from how we handled uncertain devices/volumes in other places.

File: pkg/volume/util/operationexecutor/operation_generator.go [hunk 3]
```diff
@@ -1208,6 +1231,25 @@ func (og *operationGenerator) GenerateUnmapVolumeFunc(
...
+			PodName:             volumeToUnmount.PodName,
+			PodUID:              volumeToUnmount.PodUID,
+			VolumeName:          volumeToUnmount.VolumeName,
+			OuterVolumeSpecName: volumeToUnmount.OuterVolumeSpecName,
+			VolumeGidVolume:     volumeToUnmount.VolumeGidValue,
+			VolumeSpec:          volumeToUnmount.VolumeSpec,
+			VolumeMountState:    VolumeMountUncertain,
+		}
+		markVolumeUncertainErr := actualStateOfWorld.MarkVolumeMountAsUncertain(markVolumeOpts)
+		if markVolumeUncertainErr != nil {
```
Comment (gnufied) [inline pkg/volume/util/operationexecutor/operation_generator.go:1247]: I think this could mean - if a pod running on a node has one or more of volume failing to unmount, then pod can still be deleted because volume is being marked as `uncertain` and hence `GetMountedVolumesForPod` won't find uncertain volumes?

Comment (jingxu97) [reply pkg/volume/util/operationexecutor/operation_generator.go:1247]: good point!

In current logic, pod will not be deleted though. GetMountedVolumesForPod will not find uncertain volumes, but it also check volumepaths from disk directly by calling getMountedVolumePathListFromDisk.

Now thinking this, for pod deletion, I am thinking a safer approach for GetMountedVolumesForPod should include uncertain state..?

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 2 above)
Comment (jingxu97) [reply pkg/volume/util/operationexecutor/operation_generator.go:1364]: another way is perform teardown first. In case of error returned, mark it as uncertain. In case of no error, mark it as unmounted.

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 3 above)
Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_generator.go:1247]: > n current logic, pod will not be deleted though. GetMountedVolumesForPod will not find uncertain volumes, but it also check volumepaths from disk directly by calling getMountedVolumePathListFromDisk.

yeah I don't trust `getMountedVolumePathListFromDisk` completely. Also, what happens if driver created no mount points but `unpublish` still failed?

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 2 above)
Comment (jsafrane) [reply pkg/volume/util/operationexecutor/operation_generator.go:1364]: I pointed out in the description of the PR, IMO it's not safe to assume that a mount is usable even after UnmountVolume / UnmountDevice final error. Better to call SetUp / MountDevice again when the mount is needed. It is a corner case already and one extra MountDevice / SetUp won't harm, especially if it's idempotent.

I am marking the volume as uncertain at the beginning, because unmapping the volume is a long process - see below - and it makes the error handling much easier.

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 3 above)
Comment (jsafrane) [reply pkg/volume/util/operationexecutor/operation_generator.go:1247]: Adding uncertain volumes to `GetMountedVolumesForPod` will run stats on them and could start pods. This needs to be smarter, perhaps extending only `podVolumesExist` to uncertain volumes.

**Comment by ibotty** [comment]
Anything blocking it?

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 3 above)
Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_generator.go:1247]: I am trying to remember - in which cases we don't want an uncertain volume to be added in  `GetMountedVolumesForPod`? This would potentially prevent a pod from being deleted in some cases - but may be that is a good thing?

Comment (jsafrane) [reply pkg/volume/util/operationexecutor/operation_generator.go:1247]: When kubelet waits for all volumes to be mounted, it calls `verifyVolumesMountedFunc`, which calls `volumemanager.getUnmountedVolumes()`, which then calls  `GetMountedVolumesForPod`. If uncertain volumes are returned from `GetMountedVolumesForPod`, kubelet will interpret it as the volumes are mounted and it will start the pod.

Comment (jingxu97) [reply pkg/volume/util/operationexecutor/operation_generator.go:1247]: we could have separate logic in these cases.
1. During pod start, when checking whether all volumes are already mounted, this check should not include uncertain volumes
2. During pod deletion, when checking whether volumes are unmounted, it should include uncertain volumes.

Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_generator.go:1247]: Yes I think that may work. I am thinking we should leave `GetMountedVolumesForPod` alone because it is also called from other places but may be introduce another function which would include uncertain and mounted volumes before allowing pod deletion.

Comment (jsafrane) [reply pkg/volume/util/operationexecutor/operation_generator.go:1247]: /lgtm cancel
This needs to be reworked as suggested above.

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 2 above)
Comment (gnufied) [reply pkg/volume/util/operationexecutor/operation_generator.go:1364]: I think my main concern is - other intree volume types do not benefit from being added to ASOW in uncertain state. Ideally all of `MountDevice` calls should be idempotent and hopefully nothing would break but it is somewhat of risky behaviour change and I am not sure if we have e2es that verify stuff like this. 

May be it is fine and may be - we will see some regressions.

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 3 above)
Comment (jsafrane) [reply pkg/volume/util/operationexecutor/operation_generator.go:1247]: I added `GetPossiblyMountedVolumesForPod` for the case when `podVolumesExist` needs to know when all volumes were really unmounted (and are not uncertain).
@gnufied @jingxu97, PTAL

**Comment by ehashman** [comment]
/hold cancel

since I think the hold has been addressed... on the node reviewer backlog

**Comment by jsafrane** [comment]
/hold
the test failures look genuine

```
Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link] [Testpattern: Pre-provisioned PV (block volmode)] volumeMode should fail to create pod by failing to mount volume [Slow]
Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link] [Testpattern: Pre-provisioned PV (block volmode)] volumeMode should fail to create pod by failing to mount volume [Slow]
Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link] [Testpattern: Pre-provisioned PV (block volmode)] volumeMode should fail to create pod by failing to mount volume [Slow]
Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link-bindmounted] [Testpattern: Pre-provisioned PV (block volmode)] volumeMode should fail to create pod by failing to mount volume 
Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link-bindmounted] [Testpattern: Pre-provisioned PV (block volmode)] volumeMode should fail to create pod by failing to mount volume [Slow]
Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link-bindmounted] [Testpattern: Pre-provisioned PV (block volmode)] volumeMode should fail to create pod by failing to mount volume [Slow]
Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: tmpfs] [Testpattern: Pre-provisioned PV (block volmode)] volumeMode should fail to create pod by failing to mount volumeKubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: tmpfs] [Testpattern: Pre-provisioned PV (block volmode)] volumeMode should fail to create pod by failing to mount volume
Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: tmpfs] [Testpattern: Pre-provisioned PV (block volmode)] volumeMode should fail to create pod by failing to mount volume
Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir] [Testpattern: Pre-provisioned PV (block volmode)] volumeMode should fail to create pod by failing to mount volume
Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir] [Testpattern: Pre-provisioned PV (block volmode)] volumeMode should fail to create pod by failing to mount volume
Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: blockfs] [Testpattern: Pre-provisioned PV (block volmode)] volumeMode should fail to create pod by failing to mount volume
Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: blockfs] [Testpattern: Pre-provisioned PV (block volmode)] volumeMode should fail to create pod by failing to mount volume
Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-bindmounted] [Testpattern: Pre-provisioned PV (block volmode)] volumeMode should fail to create pod by failing to mount volume 
Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-bindmounted] [Testpattern: Pre-provisioned PV (block volmode)] volumeMode should fail to create pod by failing to mount volume [Slow]

File: pkg/volume/util/operationexecutor/operation_generator.go (hunk 2 above)
Comment (jsafrane) [reply pkg/volume/util/operationexecutor/operation_generator.go:1364]: If any of the operation below fails (like `isDeviceOpened` check), the volume is still marked as mounted, while e.g. iscsi or FC volumes were already detached in `TearDownDevice`.  Therefore kubelet should mark it as uncertain. It is not related to CSI.

**Comment by jsafrane** [comment]
I added `PodRemovedFromVolume()` to ASW to have a way how DSW populator can see that a volume has been fully unmounted from a pod. `PodExistsInVolume`, which is used today, returns only fully mounted volumes and not the uncertain ones.

File: pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go [hunk 4]
```diff
@@ -278,12 +278,12 @@ func (dswp *desiredStateOfWorldPopulator) findAndRemoveDeletedPods() {
 			klog.V(4).InfoS("Pod still has one or more containers in the non-exited state and will not be removed from desired state", "pod", klog.KObj(volumeToMount.Pod))
 			continue
 		}
-		exists, _, _ := dswp.actualStateOfWorld.PodExistsInVolume(volumeToMount.PodName, volumeToMount.VolumeName)
+		removed := dswp.actualStateOfWorld.PodRemovedFromVolume(volumeToMount.PodName, volumeToMount.VolumeName)
 		var volumeToMountSpecName string
```
Comment (gnufied) [inline pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go:282]: so if volume was uncertain, this would result in volume being deleted from DSOW. Previously we did exact opposite:

> if volume mount was uncertain we should keep trying to mount the volume

which means if volume-mgr started mounting the volume and say first mount failed and volume entered uncertain state, then we do not remove the volume from DSOW until volume is correctly mounted.  Now we would basically abort potentially in-flight mount request and issue umount requests.  I am not sure which one is more correct.

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go [hunk 5]
```diff
@@ -681,6 +696,31 @@ func (asw *actualStateOfWorld) PodExistsInVolume(
...
+		return true
+	}
+
+	podObj, podExists := volumeObj.mountedPods[podName]
+	if podExists {
+		// if volume mount was uncertain we should keep trying to unmount the volume
+		if podObj.volumeMountStateForPod == operationexecutor.VolumeMountUncertain {
+			return false
+		}
+		if podObj.volumeMountStateForPod == operationexecutor.VolumeMounted {
```
[the remark this answers is not in the document]
Comment (gnufied) [reply pkg/kubelet/volumemanager/cache/actual_state_of_world.go:716]: reading this again - so basically we are saying if a volume is uncertain or mounted - then it is *not* removed from pod in the kubelet and hence can be removed from DSOW.  

Previously we prevented removal of uncertain volumes from DSOW, but since we not stop deletion of pods with uncertain volumes, may be it is fine.

File: pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go (hunk 4 above)
Comment (gnufied) [reply pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go:282]: I think it is fine.

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go [hunk 6]
```diff
@@ -110,6 +110,16 @@ type ActualStateOfWorld interface {
...
 
+	// PodRemovedFromVolume returns true if the given pod does not in the list of
+	// mountedPods for the given volume in the cache, indicating that the pod has
+	// fully unmounted it or it was never mounted.
+	// If a pod with the same unique name does not exist under the specified
+	// volume, true is returned.
+	// If a volume with the name volumeName does not exist in the list of
+	// attached volumes, true is returned indicating the given volume is not yet
+	// attached.
+	PodRemovedFromVolume(podName volumetypes.UniquePodName, volumeName v1.UniqueVolumeName) bool
```
Comment (gnufied) [inline pkg/kubelet/volumemanager/cache/actual_state_of_world.go:121]: typo in - "given pod does not exist"?

I would perhaps also add the context that - 

> If a volume is fully mounted or is in uncertain mount state for a pod, it is considered that pod still exists in volume manager's actual state of the world.

File: pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go [hunk 7]
```diff
@@ -278,12 +278,12 @@ func (dswp *desiredStateOfWorldPopulator) findAndRemoveDeletedPods() {
...
 		if volumeToMount.VolumeSpec != nil {
 			volumeToMountSpecName = volumeToMount.VolumeSpec.Name()
 		}
-		if !exists && podExists {
+		if removed && podExists {
 			klog.V(4).InfoS("Actual state does not yet have volume mount information and pod still exists in pod manager, skip removing volume from desired state", "pod", klog.KObj(volumeToMount.Pod), "podUID", volumeToMount.Pod.UID, "volumeName", volumeToMountSpecName)
```
Comment (gnufied) [inline pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go:287]: This is kind subtle behaviour change btw. Do we have tests for it? I think existing uncertain device and mount tests only cover setup or mount failures. Having said that - it might be tricky to test it, but it might be a good idea to have some coverage,

File: pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go (hunk 4 above)
Comment (jsafrane) [reply pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go:282]: > if volume mount was uncertain we should keep trying to mount the volume

We want to keep this behavior when a pod needs the volume. However, the change above is for deleted pods, where we want to "keep trying to **unmount** the volume". The mount may never succeed, because of timeouts or whatnot.

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go (hunk 6 above)
Comment (jsafrane) [reply pkg/kubelet/volumemanager/cache/actual_state_of_world.go:119]: Rephrased a bit, using your suggestion.

```
	// PodRemovedFromVolume returns true if the given pod does not exist in the list of
	// mountedPods for the given volume in the cache, indicating that the pod has
	// fully unmounted it or it was never mounted the volume.
	// If the volume is fully mounted or is in uncertain mount state for the pod, it is
	// considered that the pod still exists in volume manager's actual state of the world
	// and false is returned.
```

File: pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go (hunk 7 above)
Comment (jsafrane) [reply pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go:287]: Added an unit test. I had to refactor `findAndRemoveDeletedPods` tests a bit - there were two tests with identical initialization, I created a common function with it and added a third test.

File: pkg/kubelet/kubelet_volumes.go [hunk 8]
```diff
@@ -74,7 +74,7 @@ func (kl *Kubelet) ListBlockVolumesForPod(podUID types.UID) (map[string]volume.B
 // pods for the specified volume are mounted.
 func (kl *Kubelet) podVolumesExist(podUID types.UID) bool {
```
Comment (jingxu97) [inline pkg/kubelet/kubelet_volumes.go:75]: maybe also update the comments mentioning about uncertain volumes?

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go (hunk 6 above)
Comment (jingxu97) [reply pkg/kubelet/volumemanager/cache/actual_state_of_world.go:119]: how about name the function PodVolumeNotExist?

**Comment by gnufied** [comment]
The test failure might be a flake.  This looks good to me. 

/lgtm

**Comment by pacoxu** [comment]
/assign @random-liu
for approval from kubelet(sig-node)

**Comment by jsafrane** [comment]
pull-kubernetes-e2e-gce-storage-slow won't pass, I am fixing it in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/788

File: pkg/kubelet/kubelet_volumes.go (hunk 8 above)
Comment (jsafrane) [reply pkg/kubelet/kubelet_volumes.go:75]: Fixed

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go (hunk 6 above)
Comment (jsafrane) [reply pkg/kubelet/volumemanager/cache/actual_state_of_world.go:119]: I think it would be confusing with `PodExistsInVolume` - these two methods are not simple negation of each other. I intentionally chose a different name.

**Review by mrunalp — APPROVED** [review]

**Comment by timebertt** [comment]
Any chance we can backport this change?
We observed https://github.com/kubernetes/kubernetes/issues/100182 multiple times on v1.20 clusters.

**Comment by ankitjain28may** [comment]
Any updates, can we get to know if this is getting backported to 1.20 since we are facing a lot of such issues causing production downtimes?
