### PR TITLE
Ensure there is one running static pod with the same full name

### LINKED ISSUE #97722: Static pod should be updated by respecting terminationGracePeriodSeconds
**What happened**:
Let's say, I have a following sample static pod yaml,
<details>
<summary>Click to expand pod yaml</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  terminationGracePeriodSeconds: 60
  containers:
  - args:
    - -c
    - trap "sleep inf" SIGINT SIGTERM SIGHUP &&  nc -k -l -p 4444
    command:
    - /bin/sh
    image: docker.io/library/busybox:latest
    imagePullPolicy: IfNotPresent
    name: test
    ports:
    - name: test
      containerPort: 4444
      hostPort: 4444
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
```
</details>

I want to simulate the pod update, so we will change the container image tag from `latest` to `1.33.0`  
<details>
<summary>Click to expand modified pod yaml</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  terminationGracePeriodSeconds: 60
  containers:
  - args:
    - -c
    - trap "sleep inf" SIGINT SIGTERM SIGHUP &&  nc -k -l -p 4444
    command:
    - /bin/sh
    image: docker.io/library/busybox:1.33.0
    imagePullPolicy: IfNotPresent
    name: test
    ports:
    - name: test
      containerPort: 4444
      hostPort: 4444
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
```
</details>

When I replace the original pod yaml with the modified pod yaml in `/etc/kubernetes/manifests`, the original pod gets terminated and is replaced with the modified pod. 

But when the modified pod is coming up I see following errors in `pod describe` 

```bash
Events:
  Type     Reason                  Age                     From                                                                     Message
  ----     ------                  ----                    ----                                                                     -------
  Warning  FailedCreatePodSandBox  3m46s                   kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to add hostport mapping for sandbox k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0(26989e9ffecc95d4f51a18f35c1600d927dde37ff4d6fd58df64604f1225b1fc): cannot open hostport 4444 for pod k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0_: listen tcp4 :4444: bind: address already in use
  Warning  FailedCreatePodSandBox  3m44s                   kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to add hostport mapping for sandbox k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0(657a359cb276d5cbabddacddf63ced5e5ed048fbf89f4b6215745a0eea320037): cannot open hostport 4444 for pod k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0_: listen tcp4 :4444: bind: address already in use
  Warning  FailedCreatePodSandBox  3m41s                   kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to add hostport mapping for sandbox k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0(6cfd5725fbb489b58d63d3da18b5e84239abccb24e32cffdd0707d51e46abdc0): cannot open hostport 4444 for pod k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0_: listen tcp4 :4444: bind: address already in use
  Warning  FailedCreatePodSandBox  3m40s                   kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to add hostport mapping for sandbox k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0(92455c67bfccfe4b4e2eaddda734548c82763302497d4a6cdcb09aab7ab92183): cannot open hostport 4444 for pod k8s_test-testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal_default_6c0f8c4bc2e98440a0b11c77271868bd_0_: listen tcp4 :4444: bind: address already in use
```

This is happening because the original pod has `terminationGracePeriodSeconds` set to 60 seconds. So the original pod stays up for 60 seconds while the replace pod is also brought up causing the errors we see above. Ideally, the modified pod should not come up until the original pod is completely terminated. 

This behaviour is observed only with static pods. If I use the same pod yamls above to provision and update a regular pod I don't see any errors.

<details>
<summary> Click to see behaviour with regular pods </summary>

```bash
Events:
  Type    Reason          Age                  From                                                                     Message
  ----    ------          ----                 ----                                                                     -------
  Normal  Scheduled       <unknown>                                                                                     Successfully assigned default/test to testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal
  Normal  AddedInterface  2m47s                multus                                                                   Add eth0 [10.128.2.143/23]
  Normal  Pulled          2m46s                kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Container image "docker.io/library/busybox:1.33.0" already present on machine
  Normal  Killing         2m26s                kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Container test definition changed, will be restarted
  Normal  Created         86s (x2 over 2m46s)  kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Created container test
  Normal  Started         86s (x2 over 2m46s)  kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Started container test
  Normal  Pulled          86s                  kubelet, testclust1-c6sc4-worker-a-vd4hr.c.openshift-gce-devel.internal  Container image "docker.io/library/busybox:latest" already present on machine
```

</details>

**What you expected to happen**:
The static pod should be updated by respecting `terminationGracePeriodSeconds`

**How to reproduce it (as minimally and precisely as possible)**:
Take the original pod yaml and create the static pod. Then take the modified pod yaml to simulate the update. 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by gjkim42**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This PR ensures there is no more than one running static pod with the same full name so that static pods are able to be updated/deleted gracefully.

#### Which issue(s) this PR fixes:

Fixes #97722

#### Does this PR introduce a user-facing change?

```release-note
Respect grace period when updating static pods.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by gjkim42** [comment]
/assign @smarterclayton 

Made an alternative to #104031

**Comment by gjkim42** [comment]
/retest

I think kubelet-serial tests are broken

https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&job=pull-kubernetes-node-kubelet-serial

**Comment by rphillips** [comment]
@gjkim42 this PR is not fixing the issue for me... I am reproducing it with @liggitt's steps outlined: https://github.com/kubernetes/kubernetes/issues/104648#issue-981968741

**Comment by gjkim42** [comment]
@rphillips 

This PR is not directly relevant to #104648.
This PR fixes #97722 - kubelet allows two running static pods having the same full name and different uids which is not desirable.

#104648 is that kubelet ignores a recreation operation because an old static pod and a new static pod (with the same contents) have the same uid.
If we want to address #104648 by generating a new uid for the new static pod(which has the same full name as an old one), we also have to fix #97722. Without this PR, making two static pods having the same name and different uids is not safe.

File: pkg/kubelet/pod_workers.go [hunk 1]
```diff
@@ -664,6 +684,18 @@ func (p *podWorkers) UpdatePod(options UpdatePodOptions) {
 	}
 }
 
+// isConflictedPod returns true when there is a known pod with the same
+// fullname as pod
+func (p *podWorkers) isConflictedPod(pod *v1.Pod) bool {
```
Comment (endocrimes) [inline pkg/kubelet/pod_workers.go:689]:
```suggestion
func (p *podWorkers) isConflictingStaticPod(pod *v1.Pod) bool {
```

Lets help future folks and reduce the scope of the name a little

File: pkg/kubelet/pod_workers.go [hunk 2]
```diff
@@ -765,12 +797,18 @@ func (p *podWorkers) managePodLoop(podUpdates <-chan podWork) {
 			klog.ErrorS(err, "Error syncing pod, skipping", "pod", klog.KObj(pod), "podUID", pod.UID)
 
 		case update.WorkType == TerminatedPodWork:
+			klog.V(4).InfoS("Processing pod event done", "pod", klog.KObj(pod), "podUID", pod.UID, "updateType", update.WorkType)
```
Comment (endocrimes) [inline pkg/kubelet/pod_workers.go:800]: The processing hasn't completed yet, so this log becomes potentially quite misleading.

File: pkg/kubelet/pod_workers.go [hunk 3]
```diff
@@ -819,6 +857,44 @@ func (p *podWorkers) acknowledgeTerminating(pod *v1.Pod) PodStatusFunc {
 	return nil
 }
 
+// queueReservedWork queues a reserved work having the same full name as pod
```
Comment (endocrimes) [inline pkg/kubelet/pod_workers.go:860]: Can you add the why here? - It won't necessarily be immediately obvious to future readers of this code.

File: pkg/kubelet/pod_workers.go [hunk 4]
```diff
@@ -819,6 +857,44 @@ func (p *podWorkers) acknowledgeTerminating(pod *v1.Pod) PodStatusFunc {
...
+// and completes the previous pod. It returns true if there is a reserved work
+// else returns false
+func (p *podWorkers) queueReservedWork(pod *v1.Pod) bool {
```
Comment (endocrimes) [inline pkg/kubelet/pod_workers.go:863]:
```suggestion
func (p *podWorkers) queueWorkForConflictedStaticPod(pod *v1.Pod) bool {
```

This currently only applies to a small set of pods, lets avoid having a generic name that's easy to piggyback onto in the future without clear intent

File: pkg/kubelet/pod_workers.go [hunk 5]
```diff
@@ -620,12 +626,26 @@ func (p *podWorkers) UpdatePod(options UpdatePodOptions) {
...
+		fullname := kubecontainer.GetPodFullName(pod)
+		if p.isConflictedPod(pod) {
+			if pendingWork, exists := p.reservedWorkFullnames[fullname]; exists {
+				pendingPod := pendingWork.Options.Pod
+				if pendingPod.UID != uid {
+					klog.V(4).InfoS("Mark an outdated pod as finished", "pod", klog.KObj(pod), "podUID", pod.UID)
+					p.podSyncStatuses[pendingPod.UID].finished = true
+				}
+			}
+			klog.InfoS("Reserve a podWork for the conflicted pod", "pod", klog.KObj(pod), "podUID", pod.UID)
```
Comment (endocrimes) [inline pkg/kubelet/pod_workers.go:638]:
```suggestion
			klog.InfoS("Reserving work to update the conflicted pod", "pod", klog.KObj(pod), "podUID", pod.UID)
```

File: pkg/kubelet/pod_workers.go [hunk 6]
```diff
@@ -765,12 +797,18 @@ func (p *podWorkers) managePodLoop(podUpdates <-chan podWork) {
 			klog.ErrorS(err, "Error syncing pod, skipping", "pod", klog.KObj(pod), "podUID", pod.UID)
 
 		case update.WorkType == TerminatedPodWork:
+			klog.V(4).InfoS("Processing pod event done", "pod", klog.KObj(pod), "podUID", pod.UID, "updateType", update.WorkType)
+			if p.queueReservedWork(pod) {
+				if start := update.Options.StartTime; !start.IsZero() {
+					metrics.PodWorkerDuration.WithLabelValues("terminated").Observe(metrics.SinceInSeconds(start))
+				}
+				continue
```
Comment (endocrimes) [inline pkg/kubelet/pod_workers.go:805]: Add a comment explaining why we maintain the loop here?

**Review by endocrimes — CHANGES_REQUESTED** [review]

File: pkg/kubelet/pod_workers.go [hunk 7]
```diff
@@ -620,12 +626,26 @@ func (p *podWorkers) UpdatePod(options UpdatePodOptions) {
 	var podUpdates chan podWork
 	var exists bool
 	if podUpdates, exists = p.podUpdates[uid]; !exists {
+		fullname := kubecontainer.GetPodFullName(pod)
+		if p.isConflictedPod(pod) {
+			if pendingWork, exists := p.reservedWorkFullnames[fullname]; exists {
+				pendingPod := pendingWork.Options.Pod
+				if pendingPod.UID != uid {
+					klog.V(4).InfoS("Mark an outdated pod as finished", "pod", klog.KObj(pod), "podUID", pod.UID)
+					p.podSyncStatuses[pendingPod.UID].finished = true
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:635]: This isn't safe because there is no guarantee pendingPod.UID doesn't collide with a running pod (and any running pod can't be terminated early).

File: pkg/kubelet/pod_workers.go [hunk 8]
```diff
@@ -819,6 +857,44 @@ func (p *podWorkers) acknowledgeTerminating(pod *v1.Pod) PodStatusFunc {
...
+		return false
+	}
+
+	klog.V(4).InfoS("Queue reserved podWork to sync", "pod", klog.KObj(work.Options.Pod), "podUID", work.Options.Pod.UID)
+	podUpdates := p.podUpdates[pod.UID]
+	p.podUpdates[work.Options.Pod.UID] = podUpdates
+	p.podSyncStatuses[work.Options.Pod.UID].working = true
+	podUpdates <- work
+
+	delete(p.podUpdates, pod.UID)
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:879]: Since this is identical to complete terminating, I really didn't expect this to be here (but instead expected the chunk in managePodLoop to invoke this method, then invoke completeTerminating)

File: pkg/kubelet/pod_workers.go [hunk 9]
```diff
@@ -765,12 +797,18 @@ func (p *podWorkers) managePodLoop(podUpdates <-chan podWork) {
 			klog.ErrorS(err, "Error syncing pod, skipping", "pod", klog.KObj(pod), "podUID", pod.UID)
 
 		case update.WorkType == TerminatedPodWork:
+			klog.V(4).InfoS("Processing pod event done", "pod", klog.KObj(pod), "podUID", pod.UID, "updateType", update.WorkType)
+			if p.queueReservedWork(pod) {
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:801]: The usage of a method that returns a bool that is not named 'has*|should*' is a bit unusual.  I'm confused though - we need to wake up *another* worker (because the queued work isn't guaranteed to have our uid, in fact is very likely not to), so I expected this chunk to simply queue an action on another pod's work queue.  That implies that we start one work queue for every incoming uid, and for a given uid we may have updates for that uid be "no-ops" until the previous duplicate is freed.

Also, many pods can attempt to use the same full name, so I expected the reserved work for a pod name to be a list, not a single entry.  

Finally, if a pod is blocked long enough on shutdown I think a reason is going to have to be provided to pending pod status.  I'm a little uncomfortable about having that in this method, so it might simply be a new sync method (`syncWaitingPod`) or something provided to this method.

**Comment by gjkim42** [comment]
@smarterclayton @rphillips 

It seems that changing a static pod file is similar to force deleting a pod and making a new one immediately.
(They will make `podWorkers` have two pods with the same full name and the different uids.)

So, I think this change may change the behavior of the force deleting static pods.

i.e.
Without this change, force deleting a static pod will have kubelet recreate the static pod immediately.
However, with this change, force deleting a static pod will have kubelet wait for the old static pod to be deleted gracefully.

Not sure this is ok. Need your advice.

**Comment by smarterclayton** [comment]
> However, with this change, force deleting a static pod will have kubelet wait for the old static pod to be deleted gracefully.

The reason to allow static UID on static pods was mostly to ensure inline changes of pods didn't involve tearing them down, and possibly also to guarantee that you don't have two instances of the same pod running at the same time when using tsatic pods (I.e. if you update the static pod you want the old one stopped before the new one starts).

I believe we are working towards the following:

1. A user can ensure a static pod is updated but that the old instance is stopped before the new one is started (by having the same pod name / namespace)
2. A user can update a static pod with an incremental change efficiently.

Currently, this change would make 1 correct.  #104712 by itself would break 1.  The two changes together  would  makes 2 worse (because after that change ALL static pods involve full shutdown and full restart), but would potentially prevent users from making unsupported changes to pods accidentally (i.e. adding a new container to a pod).  I'm not sure yet whether we want to do #104712, but we definitely need to make this change.

**Comment by gjkim42** [comment]
> 1. A user can ensure a static pod is updated but that the old instance is stopped before the new one is started (by having the same pod name / namespace)

What I was trying to say is that making 1 correct would make a new side effect - we will not support force deleting static pods.

File: pkg/kubelet/pod_workers.go (hunk 9 above)
Comment (gjkim42) [reply pkg/kubelet/pod_workers.go]: > Finally, if a pod is blocked long enough on shutdown I think a reason is going to have to be provided to pending pod status. I'm a little uncomfortable about having that in this method, so it might simply be a new sync method (`syncWaitingPod`) or something provided to this method.

@smarterclayton 
Can you please elaborate on this? 
I am not sure where to call the method that sets a reason for the pending pod status.
Do we want to give such work to the pending pod's goroutine?

**Comment by gjkim42** [comment]
@smarterclayton 

> 2\. A user can update a static pod with an incremental change efficiently (add env var, change container image) without recreating the entire pod

@yujuhong (the original author of this implementation) said that
https://github.com/kubernetes/kubernetes/issues/6580#issuecomment-91079862

Updating static pods without recreating them has not been supported for a long ago (about many years).

File: pkg/kubelet/pod_workers.go [hunk 10]
```diff
@@ -620,12 +629,18 @@ func (p *podWorkers) UpdatePod(options UpdatePodOptions) {
 	var podUpdates chan podWork
 	var exists bool
 	if podUpdates, exists = p.podUpdates[uid]; !exists {
+		fullname := kubecontainer.GetPodFullName(pod)
+		if p.isConflictedStaticPod(pod) {
```
Comment (249043822) [inline pkg/kubelet/pod_workers.go:633]: only the same static pod， while it's SYNC work, it still enters this condition, that's not correct. so this condition maybe not enough

Comment (gjkim42) [reply pkg/kubelet/pod_workers.go:633]: Can you elaborate on this? Which condition do you think we need to add?

We are trying to ensure that there is only one running static pod with the same full name.

Comment (249043822) [reply pkg/kubelet/pod_workers.go:633]: this condition is if `p.knownPodFullnames[fullName]` already has the pod full name, it considers as conflict,  but with the same static pod, it still enter the process periodly for it's sync interval, so `p.reservedPodUIDsFullnames[fullname]` may store many unuseful uids.

Comment (gjkim42) [reply pkg/kubelet/pod_workers.go:633]: > but with the same static pod, it still enter the process periodly for it's sync interval,

I think the same(having the same uid) static pod cannot enter here twice. After a static pod enters here, podUpdates[uid] exists for the same pod, so we can't enter again for the same static pod.

Please let me know if I misunderstand.

Comment (249043822) [reply pkg/kubelet/pod_workers.go:633]: oh sorry, it's my mistake

File: pkg/kubelet/pod_workers.go [hunk 11]
```diff
@@ -637,8 +652,9 @@ func (p *podWorkers) UpdatePod(options UpdatePodOptions) {
 		}()
 	}
 
-	// dispatch a request to the pod worker if none are running
-	if !status.IsWorking() {
+	// dispatch a request to the pod worker if none are running and the pod is
+	// not reserved
+	if !status.IsWorking() && !status.IsReserved() {
```
Comment (249043822) [inline pkg/kubelet/pod_workers.go:657]: Does add ` !status.IsReserved()` here properly? Because if a new static pod with same full name comes,  status.reserved becomes true, then the old pod worker couldn't enter this condtion again, it would hinder managePodLoop

Comment (gjkim42) [reply pkg/kubelet/pod_workers.go:657]: An old static pod and a new static pod have different uids, and status is retrieved by the uid.
So old pod's `status.IsReserved` would false.

Comment (249043822) [reply pkg/kubelet/pod_workers.go:657]: Is it possible that while kubelet restart, the reserved becomes creating runtime pod, but the original running pod becomes reserved, but it's containers are still running and managePodLoop stop

Comment (gjkim42) [reply pkg/kubelet/pod_workers.go:657]: I've inspected this behavior. To summary, yes it is possible but it won't have managePodLoop stop.

When restarting the kubelet, a new static pod that should be reserved can enter the UpdatePod first. (in most cases)

However, there is no config for the old static pod but there is only an orphaned runtime pod that should terminate.
And, an orphaned runtime pod is considered a non-static pod so isConflictedStaticPod returns false for the old static pod and then the old static pod is being terminated.

When restarting kubelet, it is possible that two static pods with the same name can be running for a little while. (we may tolerate this...)
However, there is no deadlock.

**Comment by smarterclayton** [comment]
https://docs.google.com/document/d/1NJKYNgoXZKGS5la4MvGrB42-DNQSFf4JQkEcZRnrDzA/edit# covers some of the implications of the larger set of problems around static pods and restarts.  I think this fix is one of the necessary components in order to provide exclusion when someone doesn't use a UID (which removes the need for most people to use a UID)

**Comment by smarterclayton** [comment]
> Updating static pods without recreating them has not been supported for a long ago (about many years).

That comment is no longer correct - we indeed must support valid changes to static pods because we support static pods.

**Comment by gjkim42** [comment]
> https://docs.google.com/document/d/1NJKYNgoXZKGS5la4MvGrB42-DNQSFf4JQkEcZRnrDzA/edit#

I think i don't have an access to read this.

**Comment by gjkim42** [comment]
@smarterclayton 

It seems that force deleting static pods has not been supported at least since v1.21.0. I suspect that it has not been supported a long ago.

If we do
$ kubectl  delete pods STATIC_POD --force 
then it deletes the corresponding mirror pod, not the static pod.

To summary, this PR will not affect force deleting static pods.

**Comment by smarterclayton** [comment]
> To summary, this PR will not affect force deleting static pods in API server.

I was not referring to force deleting static pods in the API server.  I was referring to the act of deleting a static pod file, which is a "force delete" in the same fashion as the apiserver (the pod disappears from configuration).

File: pkg/kubelet/pod_workers.go [hunk 12]
```diff
@@ -882,6 +907,8 @@ func (p *podWorkers) completeTerminatingRuntimePod(pod *v1.Pod) {
 	delete(p.podUpdates, pod.UID)
 	delete(p.lastUndeliveredWorkUpdate, pod.UID)
 	delete(p.terminatingStaticPodFullnames, kubecontainer.GetPodFullName(pod))
+
+	p.dispatchReservedStaticPodWork(kubecontainer.GetPodFullName(pod))
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:911]: Setting this up at the end is confusing.  I would simply prefer to spawn a regular pod worker for every pod (even if it's conflicting), and then have the pod manage loop check for conflicts (if it is blocked, simply queue a notification) and also have the termination of a pod wake any components it was flushing.  That avoids the need to have dispatchReservedStaticPodWork and having pod work queues get managed in two places (I would prefer that only UpdatePod queue work, and managePodLoop only requeue others).

File: pkg/kubelet/pod_workers.go [hunk 13]
```diff
@@ -387,18 +394,20 @@ func newPodWorkers(
...
-		syncTerminatedPodFn:           syncTerminatedPodFn,
-		recorder:                      recorder,
-		workQueue:                     workQueue,
-		resyncInterval:                resyncInterval,
-		backOffPeriod:                 backOffPeriod,
-		podCache:                      podCache,
+		podSyncStatuses:                map[types.UID]*podSyncStatus{},
+		podUpdates:                     map[types.UID]chan podWork{},
+		lastUndeliveredWorkUpdate:      map[types.UID]podWork{},
+		terminatingStaticPodFullnames:  map[string]struct{}{},
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:400]: This map should be unnecessary if managePodLoop takes ownership of preventing duplicate starts - roughly at the top of the loop:

```
var hasStarted bool
for range podUpdates {
  if !hasStarted {
    if !p.allowPodStart(pod) { // calculates whether the pod can be started
      p.workQueue.Enqueue(pod.UID, /* some resync interval */)
      klog // log that we can't start yet consistent with other log statements in this loop
      continue
    }
    hasStarted = true
  }
}
```

File: pkg/kubelet/pod_workers.go [hunk 14]
```diff
@@ -626,6 +632,16 @@ func (p *podWorkers) UpdatePod(options UpdatePodOptions) {
 		// the channel is empty, so buffer of size 1 is enough.
 		podUpdates = make(chan podWork, 1)
 		p.podUpdates[uid] = podUpdates
+		fullname := kubecontainer.GetPodFullName(pod)
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:635]: This could belong inside isAllowedToStart

File: pkg/kubelet/pod_workers.go [hunk 15]
```diff
@@ -697,10 +729,21 @@ func calculateEffectiveGracePeriod(status *podSyncStatus, pod *v1.Pod, options *
...
+	var hasStarted bool
 	var lastSyncTime time.Time
 	for update := range podUpdates {
 		pod := update.Options.Pod
 
+		if !hasStarted {
+			if !p.isAllowedToStart(pod) {
+				p.workQueue.Enqueue(pod.UID, wait.Jitter(p.backOffPeriod, workerBackOffPeriodJitterFactor))
+				p.completeWorkQueueNext(pod.UID)
+				klog.V(4).InfoS("Pod update is reserved", "pod", klog.KObj(pod), "podUID", pod.UID)
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:741]: "Pod cannot start yet"

File: pkg/kubelet/pod_workers.go [hunk 16]
```diff
@@ -882,6 +922,8 @@ func (p *podWorkers) completeTerminatingRuntimePod(pod *v1.Pod) {
 	delete(p.podUpdates, pod.UID)
 	delete(p.lastUndeliveredWorkUpdate, pod.UID)
 	delete(p.terminatingStaticPodFullnames, kubecontainer.GetPodFullName(pod))
+
+	p.startNextStaticPod(kubecontainer.GetPodFullName(pod))
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:926]: Why is this needed now?  isAllowedToStart should be able to determine this by checking whether it's the first allowed pod in the list of pending.

File: pkg/kubelet/pod_workers.go [hunk 17]
```diff
@@ -387,18 +391,20 @@ func newPodWorkers(
...
-		recorder:                      recorder,
-		workQueue:                     workQueue,
-		resyncInterval:                resyncInterval,
-		backOffPeriod:                 backOffPeriod,
-		podCache:                      podCache,
+		podSyncStatuses:                    map[types.UID]*podSyncStatus{},
+		podUpdates:                         map[types.UID]chan podWork{},
+		lastUndeliveredWorkUpdate:          map[types.UID]podWork{},
+		terminatingStaticPodFullnames:      map[string]struct{}{},
+		startedPodUIDsByFullname:           map[string]types.UID{},
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:398]: You only need startedPodUIDsByFullname and can remove terminatingStaticPodFullnames.  IsPodForMirrorPodTerminatingByFullName now must calculate by checking startedPodUIDsByFullname, then checking the podSyncStatus for that UID and see whether it is both terminationRequested and ! terminated.

File: pkg/kubelet/pod_workers.go (hunk 14 above)
Comment (smarterclayton) [reply pkg/kubelet/pod_workers.go:635]: This whole chunk only applies for static pods (which means inside isAllowedToStart it's after the isStaticPod check)

File: pkg/kubelet/pod_workers.go [hunk 18]
```diff
@@ -626,6 +632,16 @@ func (p *podWorkers) UpdatePod(options UpdatePodOptions) {
 		// the channel is empty, so buffer of size 1 is enough.
 		podUpdates = make(chan podWork, 1)
 		p.podUpdates[uid] = podUpdates
+		fullname := kubecontainer.GetPodFullName(pod)
+		startedUID, started := p.startedPodUIDsByFullname[fullname]
+		if !started || startedUID == uid {
+			// we can start a pod
+			p.startedPodUIDsByFullname[fullname] = uid
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:639]: If this becomes only static pods, it should describe that it only applies to static pods.

**Comment by gjkim42** [comment]
@smarterclayton 
I think they are all done! Could you PTAL?

File: pkg/kubelet/pod_workers.go [hunk 19]
```diff
@@ -696,11 +710,70 @@ func calculateEffectiveGracePeriod(status *podSyncStatus, pod *v1.Pod, options *
...
+
+	var staticPodStarted bool
 	for update := range podUpdates {
 		pod := update.Options.Pod
 
+		if kubetypes.IsStaticPod(pod) {
+			if !staticPodStarted {
+				// try to start static pod
+				func() {
+					p.podLock.Lock()
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:760]: This needs to be a function, and IsStaticPod(pod) should be inside that function.

```
if p.allowPodStart(pod) {
```

```
func allowPodStart(pod) bool {
  if !kubetypes.IsStaticPod(pod) { 
     return true
  }
  ...
  p.podLock.Lock()
  ...
}
```

Comment (smarterclayton) [reply pkg/kubelet/pod_workers.go:760]: In general "if static pod" is an assumption that will change, so main code loops should be shielded from knowing about that.

File: pkg/kubelet/pod_workers.go [hunk 20]
```diff
@@ -734,10 +748,71 @@ func calculateEffectiveGracePeriod(status *podSyncStatus, pod *v1.Pod, options *
...
+
+// allowNextStaticPod allows next static pod to start for the given fullname
+func (p *podWorkers) allowNextStaticPod(fullname string) {
+	waitingToStartPods := p.waitingToStartStaticPodsByFullname[fullname]
+	if len(waitingToStartPods) == 0 {
+		return
+	}
+
+	p.startedStaticPodsByFullname[fullname] = waitingToStartPods[0]
+	p.waitingToStartStaticPodsByFullname[fullname] = waitingToStartPods[1:]
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:798]: I *think* we need to iterate through waitingToStartPods and remove any uid that is not in podSyncStatus, then take the one in the first position.

Also, can the current UID be started AND in be in the first waitingToStartPods position?  If so, we may also need to exclude that.

I'd like to see unit tests for allowPodStart that capture various uses cases and describe which aren't solved (in this PR).

File: pkg/kubelet/pod_workers.go [hunk 21]
```diff
@@ -734,10 +748,71 @@ func calculateEffectiveGracePeriod(status *podSyncStatus, pod *v1.Pod, options *
...
+		if uid == pod.UID {
+			// pod is already started
+			return true
+		}
+		return false
+	}
+
+	waitingToStartPods := p.waitingToStartStaticPodsByFullname[fullname]
+	if len(waitingToStartPods) == 0 {
+		return false
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:784]: If we are not waiting, shouldn't this be true?  "A static pod is allowed to start if there are no waiting static pods with that full name"?

File: pkg/kubelet/pod_workers.go (hunk 20 above)
Comment (smarterclayton) [reply pkg/kubelet/pod_workers.go:798]: (full branch coverage on these methods added for a `Test_allowPodStart`)

Comment (gjkim42) [reply pkg/kubelet/pod_workers.go]: > I'd like to see unit tests for allowPodStart that capture various uses cases and describe which aren't solved (in this PR).

done



> I _think_ we need to iterate through waitingToStartPods and remove any uid that is not in podSyncStatus, then take the one in the first position.
> 
> Also, can the current UID be started AND in be in the first waitingToStartPods position? If so, we may also need to exclude that during iteration.

They may be possible. And I think that it is not desirable to leave podWorkers in an inconsistent state(partially completed pod) at any time except inside of the podLock.

So, fixed podWorkers to be able to complete pod clearly.

File: pkg/kubelet/pod_workers.go [hunk 22]
```diff
@@ -936,7 +1031,24 @@ func (p *podWorkers) completeTerminated(pod *v1.Pod) {
 	}
 	delete(p.podUpdates, pod.UID)
 	delete(p.lastUndeliveredWorkUpdate, pod.UID)
-	delete(p.terminatingStaticPodFullnames, kubecontainer.GetPodFullName(pod))
+	if fullname, exists := p.podFullnames[pod.UID]; exists {
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:1034]: Is this chunk and the following the same?

Comment (smarterclayton) [reply pkg/kubelet/pod_workers.go:1034]: Why are you doing the logic to keep waitingToStartStaticPods in `complete*()` vs inside of `allowNextStaticPod()`?  Is there a reason to have it here?

File: pkg/kubelet/pod_workers.go [hunk 23]
```diff
@@ -375,9 +374,12 @@ type podWorkers struct {
 	// Tracks by UID the termination status of a pod - syncing, terminating,
 	// terminated, and evicted.
 	podSyncStatuses map[types.UID]*podSyncStatus
-	// Tracks when a static pod is being killed and is removed when the
-	// static pod transitions to the killed state.
-	terminatingStaticPodFullnames map[string]struct{}
+	// Tracks all full names for known pods
+	podFullnames map[types.UID]string
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:378]: It would be better to put the full name in the `podSyncStatus` struct vs having another map to maintain here (unless podFullnames has a different set than podSyncStatuses, which would be confusing and likely to cause issues).

**Comment by gjkim42** [comment]
@smarterclayton 
tested multiple updates during a graceful termination and fixed some codes.
fixed to finish not started static pod if it is no longer known.

Could you PTAL?

File: pkg/kubelet/pod_workers.go [hunk 24]
```diff
@@ -665,6 +675,13 @@ func (p *podWorkers) UpdatePod(options UpdatePodOptions) {
 		podUpdates = make(chan podWork, 1)
 		p.podUpdates[uid] = podUpdates
 
+		if kubetypes.IsStaticPod(pod) {
+			fullname := kubecontainer.GetPodFullName(pod)
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:679]: This is in `status.fullname`, shouldn't need to recalculate it.

File: pkg/kubelet/pod_workers.go [hunk 25]
```diff
@@ -665,6 +675,13 @@ func (p *podWorkers) UpdatePod(options UpdatePodOptions) {
 		podUpdates = make(chan podWork, 1)
 		p.podUpdates[uid] = podUpdates
 
+		if kubetypes.IsStaticPod(pod) {
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:678]: Since this chunk is about ensuring that static pods start in FIFO order, please add a comment to this chunk like:

```
// ensure that static pods start in the order they are received by UpdatePod
```

File: pkg/kubelet/pod_workers.go [hunk 26]
```diff
@@ -734,10 +751,75 @@ func calculateEffectiveGracePeriod(status *podSyncStatus, pod *v1.Pod, options *
...
+	if !kubetypes.IsStaticPod(pod) {
+		// TODO: Do we want to allow non-static pods with the same full name?
+		// Note that it may disable the force deletion of pods.
+		return true
+	}
+	p.podLock.Lock()
+	defer p.podLock.Unlock()
+	if !p.isStaticPodAllowedToStart(pod) {
+		p.workQueue.Enqueue(pod.UID, wait.Jitter(p.backOffPeriod, workerBackOffPeriodJitterFactor))
+		if status := p.podSyncStatuses[pod.UID]; status != nil {
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:766]: Instead of checking for nil, always use `ok` (there should never be a nil status)

```
if status, ok := p.podSyncStatuses[pod.UID]; ok {
  status.working = false
}
```

File: pkg/kubelet/pod_workers.go [hunk 27]
```diff
@@ -734,10 +751,75 @@ func calculateEffectiveGracePeriod(status *podSyncStatus, pod *v1.Pod, options *
...
+}
+
+// isStaticPodAllowedToStart returns true if there is no other started static
+// pod with the same full name and pod is the first static pod waiting to
+// start.
+func (p *podWorkers) isStaticPodAllowedToStart(pod *v1.Pod) bool {
+	fullname := kubecontainer.GetPodFullName(pod)
+	uid, started := p.startedStaticPodsByFullname[fullname]
+	if started {
+		if uid == pod.UID {
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:782]: This would be clearer if it was simply

```
return uid == pod.UID
```

File: pkg/kubelet/pod_workers.go [hunk 28]
```diff
@@ -734,10 +751,75 @@ func calculateEffectiveGracePeriod(status *podSyncStatus, pod *v1.Pod, options *
...
+	}
+	p.allowNextStaticPod(kubecontainer.GetPodFullName(pod))
+	return true
+}
+
+// isStaticPodAllowedToStart returns true if there is no other started static
+// pod with the same full name and pod is the first static pod waiting to
+// start.
+func (p *podWorkers) isStaticPodAllowedToStart(pod *v1.Pod) bool {
+	fullname := kubecontainer.GetPodFullName(pod)
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:779]: This method should take fullname and pod UID - we shouldn't be getting pod full name twice in the same loop

File: pkg/kubelet/pod_workers.go [hunk 29]
```diff
@@ -246,6 +245,8 @@ type podSyncStatus struct {
 	cancelFn context.CancelFunc
 	// working is true if a pod worker is currently in a sync method.
 	working bool
+	// fullname of the pod
+	fullname string
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:249]: `fullName`

File: pkg/kubelet/pod_workers.go (hunk 26 above)
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:766]: Actually, getting the syncStatus should be moved up to right after the lock:

```
defer p.podLock.Unlock()
status, ok := p.podSyncStatus[pod.UID]
if !ok {
  return false
}
if !p.isStaticPodAllowedToStart(pod.UID, status.fullName) {
  ...
  status.working = false
}
p.allowNextStaticPod(status.fullName)
return true
```

File: pkg/kubelet/pod_workers.go [hunk 30]
```diff
@@ -734,10 +751,75 @@ func calculateEffectiveGracePeriod(status *podSyncStatus, pod *v1.Pod, options *
...
+}
+
+// allowNextStaticPod allows next static pod to start for the given fullname
+func (p *podWorkers) allowNextStaticPod(fullname string) {
+	waitingPods := p.waitingToStartStaticPodsByFullname[fullname]
+	if len(waitingPods) == 0 {
+		return
+	}
+
+	p.startedStaticPodsByFullname[fullname] = waitingPods[0]
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:804]: This seems like it is in the wrong place - this method already knows what the started pod UID is, so the method should be taking `(fullName, uid)` just like `isStaticPodAllowedToStart` and you should be setting this to

```
p.startedStaticPodsByFullName[fullName] = uid
```

File: pkg/kubelet/pod_workers.go [hunk 31]
```diff
@@ -734,10 +751,75 @@ func calculateEffectiveGracePeriod(status *podSyncStatus, pod *v1.Pod, options *
...
+	p.waitingToStartStaticPodsByFullname[fullname] = waitingPods[1:]
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:805]: at this point you should be iterating through the list of waitingToStartStaticPods and removing all the duplicate items:

```
var waitingStaticPods []types.UID
for _, waitingUID := range p.waitingToStartStaticPodsByFullName {
  if waitingUID == uid {
    continue
  }
  if _, ok := p.podSyncStatus[waitingUID]; !ok {
    continue
  }
  waitingStaticPods = append(waitingStaticPods, waitingUID)
}
p.waitingToStartStaticPodsByFullName[fullName] = waitingStaticPods
```

That ensures that when allowNextStaticPod exits, both maps are fully up to date and any duplicates are purged

File: pkg/kubelet/pod_workers.go [hunk 32]
```diff
@@ -901,16 +980,32 @@ func (p *podWorkers) completeTerminatingRuntimePod(pod *v1.Pod) {
...
 		}
 		status.terminatedAt = time.Now()
 		status.finished = true
 		status.working = false
+
+		fullname := status.fullname
+		if p.startedStaticPodsByFullname[fullname] == pod.UID {
+			delete(p.startedStaticPodsByFullname, fullname)
+		}
+		l := 0
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:995]: This whole section can just be deleted if you perform this logic in https://github.com/kubernetes/kubernetes/pull/104743/commits/e77d81267795d914ef7ebab7e13c6a6baf986971#r720357165.  There should always be a pod worker for any "waiting fullname", and if there isn't that's a bug in pod worker lifecycle that has to get fixed.

File: pkg/kubelet/pod_workers.go [hunk 33]
```diff
@@ -947,6 +1040,25 @@ func (p *podWorkers) completeTerminated(pod *v1.Pod) {
 		}
 		status.finished = true
 		status.working = false
+
+		fullname := status.fullname
+		if p.startedStaticPodsByFullname[fullname] == pod.UID {
+			delete(p.startedStaticPodsByFullname, fullname)
+		}
+		l := 0
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:1048]: can be removed

File: pkg/kubelet/pod_workers.go [hunk 34]
```diff
@@ -1059,6 +1176,25 @@ func (p *podWorkers) removeTerminatedWorker(uid types.UID) {
 	delete(p.podSyncStatuses, uid)
 	delete(p.podUpdates, uid)
 	delete(p.lastUndeliveredWorkUpdate, uid)
+
+	fullname := status.fullname
+	if p.startedStaticPodsByFullname[fullname] == uid {
+		delete(p.startedStaticPodsByFullname, fullname)
+	}
+	l := 0
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:1184]: can be removed as per https://github.com/kubernetes/kubernetes/pull/104743/commits/e77d81267795d914ef7ebab7e13c6a6baf986971#r720358696

File: pkg/kubelet/pod_workers_test.go [hunk 35]
```diff
@@ -640,3 +652,85 @@ func TestKillPodNowFunc(t *testing.T) {
...
+		pod                                *v1.Pod
+		startedStaticPodsByFullname        map[string]types.UID
+		waitingToStartStaticPodsByFullname map[string][]types.UID
+		allowed                            bool
+	}{
+		{
+			// TODO: Do we want to allow non-static pods with the same full name?
+			// Note that it may disable the force deletion of pods.
+			desc:    "non-static pod",
+			pod:     newPod("test", "test"),
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers_test.go:668]: I expected a copy of this test that verifies if a static and non-static with different uids and the same full name start, both start (one extra test for "static then non-static" and one for "non-static then static" and both should be allowed)

File: pkg/kubelet/pod_workers_test.go [hunk 36]
```diff
@@ -640,3 +652,85 @@ func TestKillPodNowFunc(t *testing.T) {
...
+			if tc.waitingToStartStaticPodsByFullname != nil {
+				podWorkers.waitingToStartStaticPodsByFullname = tc.waitingToStartStaticPodsByFullname
+			}
+			if podWorkers.allowPodStart(tc.pod) != tc.allowed {
+				if tc.allowed {
+					t.Errorf("Pod should be allowed")
+				} else {
+					t.Errorf("Pod should not be allowed")
+				}
+			}
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers_test.go:733]: Add a new test condition here "if allowPodStart was true, the pods in waitingToStartStaticPodsByFullName[fullname] do not contain the UID of the pod, and all pod UIDs in waitingToStartStaticPodsByFullName[fullname] have valid podSyncStatus entries for their UID

File: pkg/kubelet/pod_workers.go (hunk 29 above)
Comment (smarterclayton) [reply pkg/kubelet/pod_workers.go:249]: Nm, it looks ilke we use `fullname` consistently everywhere else, so use `fullname` here.

File: pkg/kubelet/pod_workers_test.go (hunk 35 above)
Comment (gjkim42) [reply pkg/kubelet/pod_workers_test.go:668]: I am worried that they will result in a non-static pod and a mirror pod with the same full name in the apiserver so that we may not able to designate one of them - as all kubernetes APIs are based on name / namespace key.

(not sure even it is possible for apiserver(etcd) to allow two pods with the same full name)

File: pkg/kubelet/pod_workers.go [hunk 37]
```diff
@@ -734,10 +750,80 @@ func calculateEffectiveGracePeriod(status *podSyncStatus, pod *v1.Pod, options *
...
+	if started {
+		return startedUID == uid
+	}
+
+	waitingPods := p.waitingToStartStaticPodsByFullname[fullname]
+	if len(waitingPods) == 0 {
+		return true
+	}
+
+	return uid == waitingPods[0]
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:791]: I realized after reviewing this more that we need to integrate the cleanup logic into the ability to check the first start.  Because waiting cleanup happens on startup check vs task cleanup, we can collapse most of allowNextStaticPod into here and potentially remove that method altogether.

Roughly, when we check waitingPods here we want to find the first UID that exists, trim anything we skipped past.  I think at that point the bulk of maintenance that is currently in `allowNextStaticPod` can be moved into here.

Roughly:

```
waitingPods := p.waitingToStartStaticPodsByFullname[fullname]
if len(waitingPods) == 0 {
  p.startedStaticPodsByFullname[fullname] = uid
  return true
}
for i, waitingUID := range waitingPods {
  if _, ok := p.podSyncStatuses[waitingUID]; !ok {
    continue
  }
  p.waitingToStartStaticPodsByFullname[fullname] = waitingPods[i+1:]
  if waitingUID == uid {
    p.startedStaticPodsByFullname[fullname] = uid
    return true
  }
  return false
}
delete(p.waitingToStartStaticPodsByFullname, fullname)
p.startedStaticPodsByFullname[fullname] = uid
return true
```

This should guarantee that we trim any pods that are no longer waiting.  Does this make sense?

File: pkg/kubelet/pod_workers_test.go [hunk 38]
```diff
@@ -640,3 +652,200 @@ func TestKillPodNowFunc(t *testing.T) {
...
+			waitingToStartStaticPodsByFullname: map[string][]types.UID{
+				"foo_": {
+					types.UID("uid-1"),
+					types.UID("uid-0"),
+				},
+			},
+			allowed: false,
+		},
+		{
+			desc: "static pod if the static pod is the first pod waiting to start and clean up invalid waiting to start static pods entries",
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers_test.go:796]: With my proposed change up above we should split this into two tests, one that verifies tail is not cleaned up (because we trim the head instead), and one that verifies a non-existent pod that goes first fails (if you add that test before you add my change, I believe the current code will fail, showing that we need to do cleanup before we pick the first pod)

File: pkg/kubelet/pod_workers.go (hunk 37 above)
Comment (gjkim42) [reply pkg/kubelet/pod_workers.go]: seems fine. Done.

removed verifying the cleanup in `allowNextPodToStart` part as we don't care tail, is this ok?

File: pkg/kubelet/pod_workers_test.go (hunk 38 above)
Comment (gjkim42) [reply pkg/kubelet/pod_workers_test.go]: I think we don't have to verify tail is not cleaned up (we don't have to protect that logic by the test)

**Comment by smarterclayton** [comment]
This is lgtm, but would like one other reviewer to do a pass (@ehashman or someone who has been in this recently).

/approve

but giving the chance for one more set of eyes

**Comment by gjkim42** [comment]
/assign @ehashman 
For final review

**Comment by gjkim42** [comment]
/cc @ehashman @derekwaynecarr @Random-Liu 
Need final review from pod_worker maintainers :)

File: pkg/kubelet/pod_workers.go [hunk 39]
```diff
@@ -497,8 +501,19 @@ func (p *podWorkers) ShouldPodContentBeRemoved(uid types.UID) bool {
 func (p *podWorkers) IsPodForMirrorPodTerminatingByFullName(podFullName string) bool {
 	p.podLock.Lock()
 	defer p.podLock.Unlock()
-	_, ok := p.terminatingStaticPodFullnames[podFullName]
-	return ok
+	uid, started := p.startedStaticPodsByFullname[podFullName]
+	if !started {
+		return false
+	}
```
Comment (ehashman) [inline pkg/kubelet/pod_workers.go:507]: Is it not possible for a pod that hasn't been started to be terminating? I'm thinking of the edge case for a static pod that might be in the middle of setup (e.g. an initContainer) and gets removed before it reaches Running.

Maybe it could still be in `waitingToStartStaticPodsByFullname`?

File: pkg/kubelet/pod_workers.go [hunk 40]
```diff
@@ -766,10 +783,76 @@ func calculateEffectiveGracePeriod(status *podSyncStatus, pod *v1.Pod, options *
...
+	if !ok {
+		klog.ErrorS(nil, "Failed to get a valid podSyncStatuses", "pod", klog.KObj(pod), "podUID", pod.UID)
+		p.workQueue.Enqueue(pod.UID, wait.Jitter(p.backOffPeriod, workerBackOffPeriodJitterFactor))
+		status.working = false
+		return false
+	}
+	if !p.allowStaticPodStart(status.fullname, pod.UID) {
+		p.workQueue.Enqueue(pod.UID, wait.Jitter(p.backOffPeriod, workerBackOffPeriodJitterFactor))
+		status.working = false
+		return false
```
Comment (ehashman) [inline pkg/kubelet/pod_workers.go:806]: If a static pod is never allowed to start, what happens? It appears that we keep requeueing it forever. Is that possible?

File: pkg/kubelet/pod_workers.go [hunk 41]
```diff
@@ -933,16 +1013,17 @@ func (p *podWorkers) completeTerminatingRuntimePod(pod *v1.Pod) {
...
 	if status, ok := p.podSyncStatuses[pod.UID]; ok {
 		if status.terminatingAt.IsZero() {
 			klog.V(4).InfoS("Pod worker was terminated but did not have terminatingAt set, likely programmer error", "pod", klog.KObj(pod), "podUID", pod.UID)
 		}
 		status.terminatedAt = time.Now()
 		status.finished = true
 		status.working = false
+
+		if p.startedStaticPodsByFullname[status.fullname] == pod.UID {
+			delete(p.startedStaticPodsByFullname, status.fullname)
```
Comment (ehashman) [inline pkg/kubelet/pod_workers.go:1025]: I don't see `waitingToStartStaticPodsByFullname` getting cleared out anywhere when it's != 0... should that happen here or somewhere else?

File: pkg/kubelet/pod_workers_test.go [hunk 42]
```diff
@@ -682,3 +694,189 @@ func TestKillPodNowFunc(t *testing.T) {
...
+					fullname: "foo_",
+				},
+				"uid-1": {
+					fullname: "foo_",
+				},
+			},
+			waitingToStartStaticPodsByFullname: map[string][]types.UID{
+				"foo_": {
+					types.UID("uid-2"),
+					types.UID("uid-2"),
```
Comment (ehashman) [inline pkg/kubelet/pod_workers_test.go:851]: Is the same UID repeated here intentional?

File: pkg/kubelet/pod_workers_test.go (hunk 36 above)
Comment (ehashman) [reply pkg/kubelet/pod_workers_test.go:879]: Still need this added I think

File: test/e2e_node/mirror_pod_grace_period_test.go [hunk 43]
```diff
@@ -53,36 +56,61 @@ var _ = SIGDescribe("MirrorPodWithGracePeriod", func() {
...
-				pod, err := f.ClientSet.CoreV1().Pods(ns).Get(context.TODO(), mirrorPodName, metav1.GetOptions{})
-				framework.ExpectNoError(err)
-				if pod.Status.Phase != v1.PodRunning {
-					framework.Failf("expected the mirror pod %q to be running, got %q", mirrorPodName, pod.Status.Phase)
-				}
-				// have some pause in between the API server queries to avoid throttling
-				time.Sleep(time.Duration(200) * time.Millisecond)
-			}
+			ginkgo.By("wait for the mirror pod to be running for grace period")
+			gomega.Consistently(func() error {
```
Comment (ehashman) [inline test/e2e_node/mirror_pod_grace_period_test.go:70]: Shouldn't this be Eventually if we're waiting? Consistently checks that it's true every time and will fail on the first false if it's not.

File: pkg/kubelet/pod_workers.go (hunk 40 above)
Comment (gjkim42) [reply pkg/kubelet/pod_workers.go:806]: Yes, it is possible if the previous static pod is terminating forever, but I think we are ensuring that the termination requested pod terminates after `terminationGracePeriodSeconds`.

File: pkg/kubelet/pod_workers.go (hunk 41 above)
Comment (gjkim42) [reply pkg/kubelet/pod_workers.go:1025]: There can be more than one waiting to start static pods with the same full name.
So we can't clear `waitingToStartStaticPodsByFullname` here.

File: pkg/kubelet/pod_workers_test.go (hunk 42 above)
Comment (gjkim42) [reply pkg/kubelet/pod_workers_test.go:851]: Maybe I just wanted to make sure that invalid and redundant waiting pods are trimmed.

File: pkg/kubelet/pod_workers_test.go (hunk 36 above)
Comment (gjkim42) [reply pkg/kubelet/pod_workers_test.go:879]: I think this comment is outdated. 

We decided to trim any pods that are no longer waiting.
https://github.com/kubernetes/kubernetes/pull/104743#discussion_r722286946

**Comment by gjkim42** [comment]
@ehashman 
Could you PTAL again? Thanks!

**Review by ehashman — COMMENTED** [review]
Chatted with @smarterclayton about this, I think we should merge and get signal on this from CI ASAP.

Sorry for my delays on review!

/lgtm

**Comment by liggitt** [comment]
for anyone subscribed to this PR, a revert is proposed in #107734
