### PR TITLE
Fix: abort nominating a pod that was already scheduled to a node

### LINKED ISSUE #109236: Nominated node in cache didn't match Pod status
### What happened?

The scheduler cache entered a corrupted state where a Pod, according to the cache dump, was nominated to node A, while the status said it was nominated to node B.

This lead to unschedulable low priority pods due to the phantom pod in the nominator cache.

### What did you expect to happen?

The cache to match the Pod status

### How can we reproduce it (as minimally and precisely as possible)?

Setup: two nodes with all the resources used. A high priority pod comes in that is able to preempt at least one pod.

This might cause these sequence of events

1. Pod X doesn't fit, it gets nominated to `node-y` and added back to scheduling queue.
2. We start a second scheduling attempt for Pod X.
3. We get a Pod update for the `.status.nominatedPodName`. This puts the pod back into the scheduling queue.
4. The second scheduling attempt finishes and schedules the pod successfully in `node-y`
5. We start a third scheduling attempt for Pod X (due to 3)
6. We get a Pod update for the `.spec.nodeName`. This should have cleared the nominated node in the cache, but there is nothing currently there.
7. In the third scheduling attempt, the pod doesn't fit, so the scheduler nominates it to `node-z`. Nothing clears this nomination afterwards

Usually step 2 happens after 3, so everything works as expected. But in a busy cluster, 3 might be delayed.

### Anything else we need to know?

_No response_

### Kubernetes version

`1.21.9`

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

In some specific scenario described in https://github.com/kubernetes/kubernetes/issues/109236#issuecomment-1086246634, the scheduler cache might be left with a nominated Pod that in reality was already scheduled.

The fix is to check the informer cache right before nominating, inside the cache's lock.

/sig scheduling

#### Which issue(s) this PR fixes:

Fixes #109236

#### Special notes for your reviewer:

I still need to write a unit test for this

#### Does this PR introduce a user-facing change?

```release-note
Fixes a regression in 1.21 so kube-scheduler will not nominate a Pod that was already scheduled to a node
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/internal/queue/scheduling_queue_test.go [hunk 1]
```diff
@@ -892,6 +910,21 @@ func TestPriorityQueue_UpdateNominatedPodForNode(t *testing.T) {
 		t.Errorf("Unexpected diff after updating pods (-want, +got):\n%s", diff)
 	}
 
+	// Attempt to nominate a pod that was deleted from the informer cache.
+	// Nothing should change.
+	q.AddNominatedPod(deletedPodInfo, &framework.NominatingInfo{NominatingMode: framework.ModeOverride, NominatedNodeName: "node1"})
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/queue/scheduling_queue_test.go:915]: It's more like a "nonExistingPod".

If we do want to highlight it's a deleted pod, I'd suggest including it initially in the informer cache and then deleting it _explicitly_.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go [hunk 2]
```diff
@@ -892,6 +910,21 @@ func TestPriorityQueue_UpdateNominatedPodForNode(t *testing.T) {
...
+	if diff := cmp.Diff(q.PodNominator, expectedNominatedPods, cmp.AllowUnexported(nominator{}), cmpopts.IgnoreFields(nominator{}, "podLister", "RWMutex")); diff != "" {
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/queue/scheduling_queue_test.go:916]: nit: exact

```
cmp.AllowUnexported(nominator{}), cmpopts.IgnoreFields(nominator{}, "podLister", "RWMutex"))
```

to a variable.

**Review by Huang-Wei — COMMENTED** [review]
LGTM. Some nits.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:916]: let's do it after hot fix, I want to keep the cherry-pick size small

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go]: renamed

**Comment by alculquicondor** [comment]
All PRs updated. PTAL

**Comment by Huang-Wei** [comment]
Thanks @alculquicondor !

/lgtm
