### PR TITLE
[Sidecar Containers] Sidecar containers finish time needs to be accounted for in job controller

### LINKED ISSUE #124937: [Sidecar Containers] Sidecar containers finish time needs to be accounted for in job controller
### What happened?

Today the function `getFinishTimeFromContainers` (pkg/controller/job/backoff_utils.go) only account for the regular containers finish time,
presumably assuming that init containers have completed before before.
However, with the sidecar (restartable init) containers, sidecar containers will always finish later than
regular containers. And those needs to be accounted for the calculation.

/kind bug

### What did you expect to happen?

The sidecar finish time will be accounted when calculating the job's finish time.

### How can we reproduce it (as minimally and precisely as possible)?

Sidecar container with prolonged termination logic on a job will result in incorrect finish time reporting.

### Anything else we need to know?

/sig apps
/priority backlog
KEP: https://github.com/kubernetes/enhancements/issues/753

### PR DESCRIPTION
**Pull request by AxeZhan**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Today the function getFinishTimeFromContainers (pkg/controller/job/backoff_utils.go) only account for the regular containers finish time,
presumably assuming that init containers have completed before before.
However, with the sidecar (restartable init) containers, sidecar containers will always finish later than
regular containers. And those needs to be accounted for the calculation.
#### Which issue(s) this PR fixes:

Fixes #124937

#### Does this PR introduce a user-facing change?

```release-note
The sidecar finish time will be accounted when calculating the job's finish time.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
[KEP]: <https://github.com/kubernetes/enhancements/issues/753>
```

### CODE REVIEW

File: pkg/controller/job/backoff_utils.go [hunk 1]
```diff
@@ -183,18 +183,35 @@ func getFinishedTime(p *v1.Pod) time.Time {
...
+			status.State.Terminated.FinishedAt.Time.IsZero() {
+			return nil
+		}
+		return &status.State.Terminated.FinishedAt.Time
+	}
+
 	var finishTime *time.Time
 	for _, containerState := range p.Status.ContainerStatuses {
-		if containerState.State.Terminated == nil {
+		fTime := finishedTime(containerState)
```
Comment (mimowo) [inline pkg/controller/job/backoff_utils.go:196]: Could we maybe commonize more the code for Containers and InitContainers? 
Maybe a function could either update the finish time in-place or return the new value for a slice of containers.

File: pkg/controller/job/backoff_utils_test.go [hunk 2]
```diff
@@ -355,6 +355,27 @@ func TestGetFinishedTime(t *testing.T) {
 			},
 			wantFinishTime: defaultTestTime,
 		},
+		"Pod with init container and all containers terminated": {
```
Comment (mimowo) [inline pkg/controller/job/backoff_utils_test.go:358]: Maybe name the test to reflect the intention for testing sidecar containers, say 
"Pod with init container representing a sidecar container, all containers terminated"

**Review by mimowo — COMMENTED** [review]
LGTM overall

File: pkg/controller/job/backoff_utils.go (hunk 1 above)
Comment (AxeZhan) [reply pkg/controller/job/backoff_utils.go]: > Maybe a function could either update the finish time in-place

Hard to do that because finishTime passed to the function will be nil at first, thus not able to be updated.
But I think we can just use the old logic, with a combined slice of both containers and init containers?

File: pkg/controller/job/backoff_utils_test.go (hunk 2 above)
Comment (AxeZhan) [reply pkg/controller/job/backoff_utils_test.go:358]: Should we?
In a real cluster, I think only sidecar containers can be terminated after main containers terminated.
However, in code perspective, we don't check if a init container is a sidecar container here. We simply check all init container statuses, assuming normal init containers will terminate before main containers and do no harm to `finishTime`.
So as we don't care if a initContainer status belongs to a sidecar container, I think maybe to need to reflect the intention for testing sidecar containers?

Comment (mimowo) [reply pkg/controller/job/backoff_utils_test.go:358]: No strong view here. I think the code when an init container is stopped after the main container may look suspicious to some folks working on Job. Still, maybe reflecting this at the title of the PR is enough, so we can find out by looking at the lines history.

File: pkg/controller/job/backoff_utils.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/job/backoff_utils.go]: > Hard to do that because finishTime passed to the function will be nil at first, thus not able to be updated.
I see, good point, how about a function which would take the previous finish time and return the new, say:
`latestFinishTime(prevFinishTime, containers) *time.Time`?

> But I think we can just use the old logic, with a combined slice of both containers and init containers?

Combining the slices would work for me too, but it is an extra copy of memory, so maybe can explore the alternative with the function approach?

File: pkg/controller/job/backoff_utils_test.go (hunk 2 above)
Comment (AxeZhan) [reply pkg/controller/job/backoff_utils_test.go:361]: > I think the code when an init container is stopped after the main container may look suspicious to some folks working on Job. 

Yes, I agree...

I added comments to both UT and `getFinishTimeFromContainers`, I think this should be enough.

File: pkg/controller/job/backoff_utils.go (hunk 1 above)
Comment (AxeZhan) [reply pkg/controller/job/backoff_utils.go]: > latestFinishTime(prevFinishTime, containers) *time.Time

Yea, this could work.

File: pkg/controller/job/backoff_utils_test.go (hunk 2 above)
Comment (mimowo) [reply pkg/controller/job/backoff_utils_test.go:361]: sgtm

File: pkg/controller/job/backoff_utils.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/job/backoff_utils.go]: sgtm

File: pkg/controller/job/backoff_utils.go [hunk 3]
```diff
@@ -183,19 +183,24 @@ func getFinishedTime(p *v1.Pod) time.Time {
...
-		if containerState.State.Terminated.FinishedAt.Time.IsZero() {
+	finishTime := latestFinishTime(nil, p.Status.ContainerStatuses)
+	// We need to check InitContainerStatuses here also,
+	// because with the sidecar (restartable init) containers,
+	// sidecar containers will always finish later than regular containers.
+	return latestFinishTime(finishTime, p.Status.InitContainerStatuses)
+}
+
+func latestFinishTime(prevFinishTime *time.Time, cs []v1.ContainerStatus) *time.Time {
+	for _, containerState := range cs {
```
[the remark this answers is not in the document]
Comment (AxeZhan) [reply pkg/controller/job/backoff_utils.go:195]: Updated

**Review by mimowo — COMMENTED** [review]
/lgtm
/assign @alculquicondor 
/cc @atiratree

File: pkg/controller/job/backoff_utils.go [hunk 4]
```diff
@@ -183,12 +183,18 @@ func getFinishedTime(p *v1.Pod) time.Time {
...
-	for _, containerState := range p.Status.ContainerStatuses {
-		if containerState.State.Terminated == nil {
-			return nil
-		}
-		if containerState.State.Terminated.FinishedAt.Time.IsZero() {
+	finishTime := latestFinishTime(nil, p.Status.ContainerStatuses)
+	// We need to check InitContainerStatuses here also,
+	// because with the sidecar (restartable init) containers,
+	// sidecar containers will always finish later than regular containers.
+	return latestFinishTime(finishTime, p.Status.InitContainerStatuses)
```
Comment (gjkim42) [inline pkg/controller/job/backoff_utils.go:190]: How about checking the feature gate here to not break the existing behavior?

Comment (AxeZhan) [reply pkg/controller/job/backoff_utils.go:190]: I think if a sidecar container is already created, we should always take it into consideration. Regardless of whether the featuregate of the sidecar is enabled.

And for other init containers(not sidecar). I think this won't break the existing behavior as they will always terminate before the regular container.

Comment (SergeyKanzhelev) [inline pkg/controller/job/backoff_utils.go:190]: I would suggest to only check finish time of restartable init containers - otherwise we may change the current behavior for some Pod that behaves badly and reports incorrect finish time for the regular init container. I am mostly concerned of some badly written controllers that set this time to some random large value for the regular init containers.

Since sidecars are new, accounting for them is not supposed to break annything.

Comment (AxeZhan) [reply pkg/controller/job/backoff_utils.go]: > I am mostly concerned of some badly written controllers that set this time to some random large value for the regular init containers.

Well, I'm not aware of this... 
I added check in the second commit, let's wait for some reviews.

Comment (mimowo) [reply pkg/controller/job/backoff_utils.go]: I liked the simplicity of the previous solution, but I'm not very familiar with the sidecar containers yet.

> I am mostly concerned of some badly written controllers that set this time to some random large value for the regular init containers.

Would the container finish time, in case of sidecar containers, be set by a user-supplied controller? I think if the finish at time is set by kubelet then we could rely on this. 

cc @alculquicondor

Comment (alculquicondor) [reply pkg/controller/job/backoff_utils.go]: It is set by kubelet

File: pkg/controller/job/backoff_utils.go [hunk 5]
```diff
@@ -183,12 +184,29 @@ func getFinishedTime(p *v1.Pod) time.Time {
 }
 
 func getFinishTimeFromContainers(p *v1.Pod) *time.Time {
-	var finishTime *time.Time
-	for _, containerState := range p.Status.ContainerStatuses {
-		if containerState.State.Terminated == nil {
-			return nil
+	finishTime := latestFinishTime(nil, p.Status.ContainerStatuses, nil)
+	// We need to check InitContainerStatuses here also,
```
Comment (alculquicondor) [inline pkg/controller/job/backoff_utils.go:188]: the code doesn't look risky, but we should be consistent and check the feature gate to skip the additional calculations when the feature is disabled

Comment (SergeyKanzhelev) [reply pkg/controller/job/backoff_utils.go:188]: yes, most of cases it is. However there is almost no validation on consistency of statuses: https://github.com/kubernetes/kubernetes/pull/124918

Comment (alculquicondor) [reply pkg/controller/job/backoff_utils.go:188]: are you saying that the code i this PR is more risky than it appears?

File: pkg/controller/job/backoff_utils.go (hunk 4 above)
Comment (mimowo) [reply pkg/controller/job/backoff_utils.go]: I think we can simplify the code and check the InitContainers regardless of the `restartPolicy`. For safety, we just wrap with the `SidecarContainers` feature-gate check as suggested in https://github.com/kubernetes/kubernetes/pull/124942#discussion_r1608737775. 

This way we complicate the code only until the feature-gate is around. WDYT @alculquicondor @SergeyKanzhelev ?

Comment (SergeyKanzhelev) [reply pkg/controller/job/backoff_utils.go]: My only worry is to encounter some crazy controller like one that made me write this comment: https://github.com/kubernetes/kubernetes/pull/124918. Semantically I am all for not checking for `restartPolicy`. Breaking some barely supported scenario is what keeping me uneasy here

File: pkg/controller/job/backoff_utils.go (hunk 5 above)
Comment (SergeyKanzhelev) [reply pkg/controller/job/backoff_utils.go:188]: the only risk is for the crazy scenarios when some sort of virtual kubelet was setting some bad values for init containers and it used to be ignored before. This is why I suggest only add a logic for sidecars.

File: pkg/controller/job/backoff_utils.go (hunk 4 above)
Comment (alculquicondor) [reply pkg/controller/job/backoff_utils.go]: In that case, I agree with the current implementation that restricts the change to initContainers with restartPolicy: Always.

**Comment by AxeZhan** [comment]
Added check of feature gate to skip the additional calculations.

**Comment by alculquicondor** [comment]
Quick question: Is there any other component in Kubernetes that cares about the latest termination timestamp of a Pod?

**Comment by AxeZhan** [comment]
> Quick question: Is there any other component in Kubernetes that cares about the latest termination timestamp of a Pod?

Not sure about this. But I check the code, only find kubelet and job controller using this field `State.Terminated.FinishedAt`.
So only these two components should care about the latest termination.

**Comment by alculquicondor** [comment]
Wondering if the code for `getFinishTimeFromContainers(p *v1.Pod)` should be in some library package. But if no one else needs it, we can leave it under `pkg/controller/job`

File: pkg/controller/job/backoff_utils.go [hunk 6]
```diff
@@ -183,12 +186,32 @@ func getFinishedTime(p *v1.Pod) time.Time {
 }
 
 func getFinishTimeFromContainers(p *v1.Pod) *time.Time {
-	var finishTime *time.Time
-	for _, containerState := range p.Status.ContainerStatuses {
-		if containerState.State.Terminated == nil {
-			return nil
+	finishTime := latestFinishTime(nil, p.Status.ContainerStatuses, nil)
+	if !utilfeature.DefaultFeatureGate.Enabled(features.SidecarContainers) {
```
Comment (mimowo) [inline pkg/controller/job/backoff_utils.go:190]: Small non-blocking readability: I think it will be easier to follow if the Sidecar-specific logic to update the finishTime is inside the if.

**Review by mimowo — COMMENTED** [review]
/lgtm
one non-blocking nit
/assign @atiratree @alculquicondor

**Review by mimowo — COMMENTED** [review]
/lgtm
