### PR TITLE
fix grace period used for immediate evictions

### LINKED ISSUE #115819: kubelet: Evicted and force deleted pods get their full termination grace period when they should not
### What happened?

When pods are evicted, i.e. with a hard eviction, the grace period is intended to be `0s` (i.e. do not respect the pod's `terminationGracePeriodSeconds`). 

However, currently, evicted pods receive their full termination grace period seconds.

### What did you expect to happen?

The pod is evicted immediately and the termination grace period is not respected 

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy the following pod which has an ephemeral storage limit of 5Mi and uses `dd` to fill the disk

```
kind: Pod
apiVersion: v1
metadata:
  name: evictdiskpod
  labels:
    pod: evictdiskpod
spec:
  terminationGracePeriodSeconds: 60
  containers:
  - name: busybox
    image: k8s.gcr.io/e2e-test-images/nginx:1.14-2
    resources:
      limits:
        ephemeral-storage: 5Mi
    command: ["/bin/sh", "-c"]
    args:
      - |
        _term() {
            echo "Caught SIGTERM signal!"
            while true; do sleep 5; done
        }
        trap _term SIGTERM
        sleep 10
        dd if=/dev/zero of=file bs=1M count=10
        echo 'write done'
        while true; do sleep 5; done
```

2. Observe the pod's terminationGracePeriodSeconds was respected when it should've not been

In the logs:

```
# I added a debug print to include grace period here (it is zero)
Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.688802     275 eviction_manager.go:583] "Evicting pod" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734 message="Pod ephemeral local storage usage exceeds the total limit of containers 5Mi. " grace period=0


Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.688838     275 pod_workers.go:649] "Pod is being evicted by the kubelet, begin teardown" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734
Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.688937     275 pod_workers.go:906] "Processing pod event" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734 updateType=1
Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.688965     275 pod_workers.go:1026] "Pod worker has observed request to terminate" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734

# syncTerminatingPod has a grace period of 60 (unexpected since it should've been overridden to zero)

Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.688980     275 kubelet.go:1859] "syncTerminatingPod enter" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734 gracePeriod=60
Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.689132     275 kubelet.go:1891] "Pod terminating with grace period" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734 gracePeriod=60
Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.689171     275 kuberuntime_container.go:707] "Killing container with a grace period override" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734 containerName="busybox" containerID="containerd://71e017fbdc6de9cafc7aa136e2bb07c5d02891db21eacec0c6d358e46125ef1e" gracePeriod=60
Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.689193     275 kuberuntime_container.go:711] "Killing container with a grace period" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734 containerName="busybox" containerID="containerd://71e017fbdc6de9cafc7aa136e2bb07c5d02891db21eacec0c6d358e46125ef1e" gracePeriod=60
```

Full kubelet logs: https://gist.github.com/bobbypage/7ef6335c5ee69ef8ba363d6edf5854e9

### Anything else we need to know?

1. When pod ephemeral storage eviction is reached  `evictPod` is called with a zero grace period

https://github.com/kubernetes/kubernetes/blob/a25834cb5a16bbd6a9295aeb5d1621aa8a4cd407/pkg/kubelet/eviction/eviction_manager.go#L535

2. `evictPod` uses killPod and passes the zero grace period

https://github.com/kubernetes/kubernetes/blob/a25834cb5a16bbd6a9295aeb5d1621aa8a4cd407/pkg/kubelet/eviction/eviction_manager.go#L584-L591

3. Eventually the grace period is set here in pod worker

https://github.com/kubernetes/kubernetes/blob/a25834cb5a16bbd6a9295aeb5d1621aa8a4cd407/pkg/kubelet/pod_workers.go#L694-L700

4. `calculateEffectiveGracePeriod` is used to calculate the grace period. The `options.PodTerminationGracePeriodSecondsOverride` is set to zero (which originates from the eviction manager). This overrides the pod spec's grace period here (the comment mentions this case is for eviction manager):

https://github.com/kubernetes/kubernetes/blob/908803081fd4554d7cdb17cb77e5490c44ef7ab7/pkg/kubelet/pod_workers.go#L793-L800

5. But... the bug is that right after we check the grace period happened to be zero (`gracePeriod == 0`) and if it is we change it back pod spec's grace period, thus losing the `options.PodTerminationGracePeriodSecondsOverride`

https://github.com/kubernetes/kubernetes/blob/908803081fd4554d7cdb17cb77e5490c44ef7ab7/pkg/kubelet/pod_workers.go#L801-L805

and now the final grace period returned is the pod spec's grace period instead of the overriden grace period from the eviction manager. 

### Kubernetes version

Reproduced in 1.26.0

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by olyazavr**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Currently when evicting pods due to resource pressure, or when a pod's storage use has exceeded the configured ephemeral-storage resource limit, we use a grace period override of 0 during eviction which actually ends up allowing the pod's full configured grace period rather than performing an immediate eviction due to the logic [here](https://github.com/kubernetes/kubernetes/blob/227c2e7c2b2c05a9c8b2885460e28e4da25cf558/pkg/kubelet/pod_workers.go#L998-L1000)

In order to actually perform an immediate eviction we should instead use a grace period override of 1 in these cases.

This is the same as https://github.com/kubernetes/kubernetes/pull/119570 but rebased. I don't mind which of these is merged, we just really need this fix.

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/115819

#### Special notes for your reviewer:
There's a lot of discussion in the original PR around making additional changes to address force-deletes: https://github.com/kubernetes/kubernetes/pull/119570
I am of the same mind as the original author that this PR should remain scoped down to this eviction problem

#### Does this PR introduce a user-facing change?
```release-note
Fixes a bug where hard evictions due to resource pressure would let the pod have the full termination grace period, instead of shutting down instantly. This bug also affected force deleted pods. Both cases now get a termination grace period of 1 second.

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
None

### CODE REVIEW

**Comment by iholder101** [comment]
Hey @olyazavr! Thanks for this PR!

In the last version of this PR, @mrunalp [suggested](https://github.com/kubernetes/kubernetes/pull/119570#issuecomment-1773424422) to implement this in pod_workers.go, which I think is a good idea:
> Can't we fix this for all cases if we handle it in pod_workers.go? Something like:
> 
> ```
> diff --git a/pkg/kubelet/pod_workers.go b/pkg/kubelet/pod_workers.go
> index 20e8b493a8f..b90ccad3e5a 100644
> --- a/pkg/kubelet/pod_workers.go
> +++ b/pkg/kubelet/pod_workers.go
> @@ -981,10 +981,12 @@ func calculateEffectiveGracePeriod(status *podSyncStatus, pod *v1.Pod, options *
>         // enforce the restriction that a grace period can only decrease and track whatever our value is,
>         // then ensure a calculated value is passed down to lower levels
>         gracePeriod := status.gracePeriod
> +       overriden := false
>         // this value is bedrock truth - the apiserver owns telling us this value calculated by apiserver
>         if override := pod.DeletionGracePeriodSeconds; override != nil {
>                 if gracePeriod == 0 || *override < gracePeriod {
>                         gracePeriod = *override
> +                       overriden = true
>                 }
>         }
>         // we allow other parts of the kubelet (namely eviction) to request this pod be terminated faster
> @@ -992,12 +994,13 @@ func calculateEffectiveGracePeriod(status *podSyncStatus, pod *v1.Pod, options *
>                 if override := options.PodTerminationGracePeriodSecondsOverride; override != nil {
>                         if gracePeriod == 0 || *override < gracePeriod {
>                                 gracePeriod = *override
> +                               overriden = true
>                         }
>                 }
>         }
>         // make a best effort to default this value to the pod's desired intent, in the event
>         // the kubelet provided no requested value (graceful termination?)
> -       if gracePeriod == 0 && pod.Spec.TerminationGracePeriodSeconds != nil {
> +       if !overriden && gracePeriod == 0 && pod.Spec.TerminationGracePeriodSeconds != nil {
>                 gracePeriod = *pod.Spec.TerminationGracePeriodSeconds
>         }
>         // no matter what, we always supply a grace period of 1
> ```

@zcahana's [comment](https://github.com/kubernetes/kubernetes/pull/119570#issuecomment-1852694670) also clarifies how it solves the problem for force deletion as well
> Applying the fix to `pod_workers.go` will have the added benefit of solving this for force deleted pods, which too are stopped with their full `terminationGracePeriodSeconds` instead of "immediately" (see #108741, as well as [this comment](https://github.com/kubernetes/kubernetes/issues/115819#issuecomment-1432447916) in the original issue solved by this PR). While not explicitly in-scope for this PR, this could catch 2 (related) birds.

Would you consider bringing it into this PR?

**Comment by olyazavr** [comment]
@iholder101 done, and added a test for it

File: pkg/kubelet/pod_workers_test.go [hunk 1]
```diff
@@ -2382,3 +2382,52 @@ func Test_allowPodStart(t *testing.T) {
...
 	}
 }
+
+func Test_calculateEffectiveGracePeriod(t *testing.T) {
+	zero := int64(0)
+	two := int64(2)
+	five := int64(5)
+	thirty := int64(30)
+	// no overrides, use what's on the spec
+	pod := newNamedPod("1", "ns", "running-pod", false)
```
Comment (kannon92) [inline pkg/kubelet/pod_workers_test.go:2392]: Reading this, I see five tests in one. Could you refactor this to be in a table?

Comment (kannon92) [reply pkg/kubelet/pod_workers_test.go:2392]: Something like https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pod_workers_test.go#L1691?

**Comment by kannon92** [comment]
Please add a release note.

**Comment by rphillips** [comment]
+1 to fixing this.

/lgtm

**Comment by rphillips** [comment]
This PR might be too late for 1.30 though. We can plan for 1.31 and perhaps backport it.

**Comment by kannon92** [comment]
@kubernetes/milestone-maintainers could someone tag this as milestone 1.31?

I cannot. :(
