### PR TITLE
kubectl explain: ignore trailing period

### LINKED ISSUE #54891: kubectl explain: Ignore trailing period
As a frequent user of `kubectl explain` I propose we ignore the trailing period (`.`) character in the argument passed to this command:

* As long as argument is non-empty when trailing period is removed, I think it's safe
* You use `kubectl explain` by keep adding fields (e.g. `service`, then `service.spec`,  then `service.spec.ports` ...) so it's very easy to forget a trailing `.` at the end.
* When a user leaves the `.` at the end, kubectl gives a super weird cryptic error (see below)

```sh
$ kubectl explain  ingress.spec.rules.http.paths.
error: field "" does not exist
```

I believe ignoring the trailing period(s) will be more forgiving and increase user success with `kubectl explain`. 
@jbeda might have something to add.

/kind bug
/sig cli

### PR DESCRIPTION
**Pull request by nikhita**
Fixes #54891 

Ignores trailing period for kubectl explain i.e. `kubectl explain ingress.spec.rules.http.paths.` is valid and defaults to `kubectl explain ingress.spec.rules.http.paths`.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
cc @ahmetb @jbeda

**Comment by ahmetb** [comment]
Can you add some test cases if there are any matching tests?
Also I am not sure if the folks agree on the proposal, yet.

**Comment by spzala** [comment]
I tested the change and it works as such but as @ahmetb said, definitely adding a test is desired. On a side note, it may be a good idea to provide better error message than ignoring trailing period, as it can be an user error that some string value was missed to be specified after tailing period by user. So instead of ignoring trailing period, provide a better error message, for example, something like ```field "ingress.spec.rules.http.paths."``` doesn't exist instead of ```field "" does not exist```.  As @ahmetb mentioned the proposal of ignoring trailing period may need more discussion but adding a better error should be quick and safer. Thanks!

File: pkg/kubectl/explain/explain.go [hunk 1]
```diff
@@ -30,6 +30,10 @@ type fieldsPrinter interface {
 
 func splitDotNotation(model string) (string, []string) {
 	var fieldsPath []string
+
+	// ignore trailing period
+	model = strings.TrimSuffix(model, ".")
+
```
Comment (spzala) [inline pkg/kubectl/explain/explain.go]: I tested the change and it works as such but as @ahmetb said, definitely adding a test is desired. On a side note, it may be a good idea to provide better error message than ignoring trailing period, as it can be an user error that some string value was missed to be specified after tailing period by user. So instead of ignoring trailing period, provide a better error message, for example, something like field "ingress.spec.rules.http.paths." doesn't exist instead of field "" does not exist. As @ahmetb mentioned the proposal of ignoring trailing period may need more discussion but adding a better error should be quick and safer. Thanks!

**Comment by spzala** [comment]
https://github.com/kubernetes/kubernetes/pull/55134 - created with @nikhita  as co-author for a different solution approach as discussed in the issue. /cc @ahmetb Thanks!

**Comment by nikhita** [comment]
> Also I am not sure if the folks agree on the proposal, yet.

Sorry, should have waited a bit before creating a PR!

**Comment by nikhita** [comment]
@ahmetb @spzala @apelisse added tests. PTAL, thanks.

**Comment by ahmetb** [comment]
do you mind adding a test for `""` and `"."` cases too?

**Comment by apelisse** [comment]
Awesome! Small nit-picking, some of these tests could have gone into [field_lookup_test.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/explain/field_lookup_test.go), since that's where that particular feature lives. Can you maybe add one there?

**Review by spzala — COMMENTED** [review]
Agree with @apelisse suggestion on adding test in field_lookup_test.go :-) Thanks!

**Comment by nikhita** [comment]
@apelisse @spzala Added a test in `field_lookup_test.go`.

**Comment by apelisse** [comment]
/lgtm

Thank you @nikhita ! This went really well, I can't wait to review your next PR!

/hold

I'm putting it on hold since I want @monopole to validate the change to `visibile_to`. Please `/unhold` if it's fine. Thanks!

**Comment by nikhita** [comment]
@apelisse Thank you! :smile: 

@monopole @apelisse To give some more context, without the change in `visible_to`, bazel complains with:

```
W1109 10:42:39.925] ERROR: /workspace/k8s.io/kubernetes/pkg/kubectl/explain/BUILD:37:1: Target '//pkg/kubectl/cmd/testing:go_default_library' is not visible from target '//pkg/kubectl/explain:go_default_test'. Check the visibility declaration of the former target if you think the dependency is legitimate.
W1109 10:42:40.782] ERROR: Analysis of target '//pkg/kubectl/explain:go_default_test' failed; build aborted
```

File: pkg/kubectl/explain/explain_test.go [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+import (
+	"reflect"
+	"testing"
+
+	cmdtesting "k8s.io/kubernetes/pkg/kubectl/cmd/testing"
+)
+
+func TestSplitAndParseResourceRequest(t *testing.T) {
+	f, _, _, _ := cmdtesting.NewTestFactory()
+	mapper, _ := f.Object()
```
Comment (monopole) [inline pkg/kubectl/explain/explain_test.go]: minor nit - would be nice to contain scope of "f" with a small function, i.e.
mapper  := getMapper()
where getMapper hid f, the call to f.object, etc

File: build/visible_to/BUILD [hunk 3]
```diff
@@ -197,6 +197,7 @@ package_group(
         "//pkg/kubectl/cmd/auth",
         "//pkg/kubectl/cmd/resource",
         "//pkg/kubectl/cmd/set",
+        "//pkg/kubectl/explain",
```
Comment (monopole) [inline build/visible_to/BUILD]: It's a little strange, but not horrible, that something not in kubectl/cmd wants to depend on cmd_testing.

The main purpose of these rules is to draw a line between kubectl and the rest, not small bits withing kubectl.

**Review by monopole — COMMENTED** [review]
/unhold

File: build/visible_to/BUILD (hunk 3 above)
Comment (monopole) [reply build/visible_to/BUILD]: And thanks for the fix!

File: pkg/kubectl/explain/explain_test.go (hunk 2 above)
Comment (nikhita) [reply pkg/kubectl/explain/explain_test.go]: Done.

**Comment by apelisse** [comment]
/lgtm

Thanks!

**Comment by apelisse** [comment]
Actually, it needs your approval @monopole

**Comment by nikhita** [comment]
This didn't merge because the `do-not-merge/hold` label still exists.

Removing hold (as @monopole already tried this with `/unhold`)

/hold cancel
