### PR TITLE
[KEP-4639] Graduate image volume sources to beta

### LINKED ISSUE #130669: pull-kubernetes-node-e2e-containerd-alpha-features:  ImageVolume/Device Plugin test failed
### Which jobs are failing?

pull-kubernetes-node-e2e-containerd-alpha-features

### Which tests are failing?

Tests in the ImageVolume/Device Plugin

### Since when has it been failing?

This test job has previously been unstable due to various issues, and the failures caused by the current problem started from Mar 05 10:05:20.

### Testgrid link

https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-containerd-alpha-features

### Reason for failure (if possible)

message: 'Back-off pulling image "quay.io/crio/artifact:v1": ErrImagePull:
  failed to pull and unpack image "quay.io/crio/artifact:v1": number of layers
  and diffIDs don''t match: 1 != 0'

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Graduate the feature to beta, by:

- Allowing `subPath`/`subPathExpr` for image volumes
- Modifying the CRI to pass down the (resolved) sub path
- Adding outlined metrics

#### Which issue(s) this PR fixes:
Refers to https://github.com/kubernetes/enhancements/issues/4639

#### Special notes for your reviewer:
We can add an e2e test for the subpath feature when CRI-O supports it.
#### Does this PR introduce a user-facing change?

```release-note
Graduated image volume sources to beta:
  - Allowed `subPath`/`subPathExpr` for image volumes
  - Added kubelet metrics `kubelet_image_volume_requested_total`, `kubelet_image_volume_mounted_succeed_total` and `kubelet_image_volume_mounted_errors_total`
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
KEP: https://github.com/kubernetes/enhancements/issues/4639
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
@kubernetes/sig-node-pr-reviews PTAL

File: pkg/apis/core/types.go [hunk 1]
```diff
@@ -220,7 +220,6 @@ type VolumeSource struct {
 	// The types of objects that may be mounted by this volume are defined by the container runtime implementation on a host machine and at minimum must include all valid types supported by the container image field.
 	// The OCI object gets mounted in a single directory (spec.containers[*].volumeMounts.mountPath) by merging the manifest layers in the same way as for container images.
 	// The volume will be mounted read-only (ro) and non-executable files (noexec).
-	// Sub path mounts for containers are not supported (spec.containers[*].volumeMounts.subpath).
```
Comment (carlory) [inline pkg/apis/core/types.go:223]: A small suggestion:

```
Sub path mounts for containers are not supported (spec.containers[*].volumeMounts.subpath) before 1.33
```

File: pkg/kubelet/container/runtime.go [hunk 2]
```diff
@@ -472,6 +472,9 @@ type Mount struct {
 	Propagation runtimeapi.MountPropagation
 	// Image is set if an OCI volume as image ID or digest should get mounted (special case).
 	Image *runtimeapi.ImageSpec
+	// ImageSubPath is set if an image volume sub path should get mounted. This
+	// field is only required if the above Image is set.
```
Comment (carlory) [inline pkg/kubelet/container/runtime.go:476]: It is an optional field. It can be set only when the above Image is set.

File: pkg/kubelet/kubelet_pods.go [hunk 3]
```diff
@@ -296,13 +296,24 @@ func makeMounts(pod *v1.Pod, podDir string, container *v1.Container, hostName, h
...
 
+		subPath := mount.SubPath
+		if mount.SubPathExpr != "" {
+			subPath, err = kubecontainer.ExpandContainerVolumeMounts(mount, expandEnvs)
+
+			if err != nil {
+				return nil, cleanupAction, err
+			}
+		}
+
```
Comment (carlory) [inline pkg/kubelet/kubelet_pods.go:313]: Do we need to validate subpath for image volume like we do for other volumes?

```
if utilfs.IsAbs(subPath) {
	return nil, cleanupAction, fmt.Errorf("error SubPath `%s` must not be an absolute path", subPath)
}

err = volumevalidation.ValidatePathNoBacksteps(subPath)
if err != nil {
	return nil, cleanupAction, fmt.Errorf("unable to provision SubPath `%s`: %w", subPath, err)
}
```

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 4]
```diff
@@ -1350,7 +1350,9 @@ func (m *kubeGenericRuntimeManager) SyncPod(ctx context.Context, pod *v1.Pod, po
 		}
 
 		// NOTE (aramase) podIPs are populated for single stack and dual stack clusters. Send only podIPs.
-		if msg, err := m.startContainer(ctx, podSandboxID, podSandboxConfig, spec, pod, podStatus, pullSecrets, podIP, podIPs, imageVolumes); err != nil {
+		msg, err = m.startContainer(ctx, podSandboxID, podSandboxConfig, spec, pod, podStatus, pullSecrets, podIP, podIPs, imageVolumes)
+		incrementImageVolumeMetrics(err, spec.container, imageVolumes)
```
Comment (carlory) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:1354]: How do we identify the error type? The description of metrics tracks the number of failed image volume mounts. We can not say that all the errors are due to the image volume mount.

**Review by hashim21223445 — APPROVED** [review]

File: pkg/apis/core/types.go (hunk 1 above)
Comment (saschagrunert) [reply pkg/apis/core/types.go:223]: Added as suggested.

File: pkg/kubelet/kubelet_pods.go (hunk 3 above)
Comment (saschagrunert) [reply pkg/kubelet/kubelet_pods.go:313]: I'm not even sure if we need that validation at all. We already do those in 

https://github.com/kubernetes/kubernetes/blob/87fcae2bc765e4f752bcf7dfbd0c57f75ec751a3/pkg/apis/core/validation/validation.go#L2950-L2960

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 4 above)
Comment (saschagrunert) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:1354]: Yes, because we did not define any specific error. What we can state is that there was definitely no mount due to an error. At least that's how I interpreted it.

File: pkg/kubelet/container/runtime.go (hunk 2 above)
Comment (saschagrunert) [reply pkg/kubelet/container/runtime.go:476]: Is there anything you'd like to have changed here? :upside_down_face:

File: pkg/kubelet/kubelet_pods.go (hunk 3 above)
Comment (saschagrunert) [reply pkg/kubelet/kubelet_pods.go:313]: I'd say better safe than sorry, moved the validation down to also apply to the image volume part.

File: pkg/apis/core/types.go [hunk 5]
```diff
@@ -220,7 +220,7 @@ type VolumeSource struct {
...
+	// Sub path mounts for containers are not supported (spec.containers[*].volumeMounts.subpath) brefore 1.33.
```
Comment (carlory) [inline pkg/apis/core/types.go:223]: brefore --> before

File: pkg/kubelet/container/runtime.go (hunk 2 above)
Comment (carlory) [reply pkg/kubelet/container/runtime.go:476]: Sorry, I misread it and thought this field was required if the image was set.

File: pkg/kubelet/kubelet_pods.go (hunk 3 above)
Comment (carlory) [reply pkg/kubelet/kubelet_pods.go:313]: > I'm not even sure if we need that validation at all

```
// validatePathNoBacksteps makes sure the targetPath does not have any `..` path elements when split
//
// This assumes the OS of the apiserver and the nodes are the same. The same check should be done
// on the node to ensure there are no backsteps.
func validatePathNoBacksteps(targetPath string, fldPath *field.Path) field.ErrorList {
```

Comment (carlory) [reply pkg/kubelet/kubelet_pods.go:313]: I found the comment in the link you provided.

**Comment by carlory** [comment]
Only one nit, overall LGTM.

/lgtm 

Thank you!

**Comment by carlory** [comment]
Test the image volume feature to make sure it is working well.
/test pull-kubernetes-node-crio-cgrpv2-imagevolume-e2e

File: pkg/apis/core/types.go (hunk 5 above)
Comment (saschagrunert) [reply pkg/apis/core/types.go:223]: Thanks, fixed as suggested.

**Comment by pacoxu** [comment]
/test pull-kubernetes-node-crio-cgrpv2-imagevolume-e2e
Since https://github.com/containerd/containerd/pull/10579 was merged, can we create a new CI to run this with containerd
main branch?

**Comment by liggitt** [comment]
I think https://github.com/kubernetes/kubernetes/pull/130394 needs fixing before graduating to beta and allowing data into the field by default

**Comment by liggitt** [comment]
is there an e2e test exercising these volumes? I would have expected it to fail or explicitly require opting the e2e test namespace out of restricted mode before https://github.com/kubernetes/kubernetes/pull/130394 was fixed?

**Comment by saschagrunert** [comment]
> is there an e2e test exercising these volumes? 

We only have https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/image_volume.go right now, but with the recently merged containerd support we can extend based on what we have.

**Comment by kannon92** [comment]
Looking at those errors there may be some more cleanup needed in that presubmit.

Those don't seem to be flakes but the resizing feature should be excluded from this job.

**Comment by saschagrunert** [comment]
The suite is also using containerd 88bf19b21, which is not the latest `main`.

**Comment by saschagrunert** [comment]
Looks like containerd is not able to pull the image:
```
level=error msg="PullImage \"quay.io/crio/artifact:v1\" failed" error="rpc error: code = Unknown desc = failed to pull and unpack image \"quay.io/crio/artifact:v1\": number of layers and diffIDs don't match: 1 != 0"
```

File: test/e2e_node/image_volume.go [hunk 6]
```diff
@@ -47,7 +47,7 @@ var _ = SIGDescribe("ImageVolume", feature.ImageVolume, func() {
 	const (
 		podName             = "test-pod"
 		containerName       = "test-container"
-		validImageRef       = "quay.io/crio/artifact:v1"
+		validImageRef       = "quay.io/crio/artifact:v2"
```
Comment (saschagrunert) [inline test/e2e_node/image_volume.go:50]: Rebuilt the image using docker as regular container image. Should be now pull-able from containerd, too.

**Comment by saschagrunert** [comment]
> pull-kubernetes-node-e2e-containerd-alpha-features

https://github.com/kubernetes/test-infra/pull/34403

**Comment by saschagrunert** [comment]
> Those don't seem to be flakes but the resizing feature should be excluded from this job.

https://github.com/kubernetes/test-infra/pull/34403

File: test/e2e_node/image_volume.go (hunk 6 above)
Comment (carlory) [reply test/e2e_node/image_volume.go:50]: Is it possible to reuse the existing image or add a new image to `registry.k8s.io/e2e-test-images/` instead of hardcoding the image in the test code?

- https://github.com/kubernetes/kubernetes/blob/2a32b2137236fa7a5ede1ec391f55323a3485020/test/images

Comment (saschagrunert) [reply test/e2e_node/image_volume.go]: Yes, I'll change it to an already available image.

**Review by mikebrow — COMMENTED** [review]
looking good just a couple nits..

File: staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto [hunk 7]
```diff
@@ -248,13 +248,18 @@ message Mount {
...
+    // host_path should be unset. All image mounts are per feature definition
     // readonly. The kubelet does an PullImage RPC and evaluates the returned
     // PullImageResponse.image_ref value, which is then set to the
     // ImageSpec.image field. Runtimes are expected to mount the image as
     // required.
-    // Introduced in the OCI Volume Source KEP: https://kep.k8s.io/4639
+    // Introduced in the Image Volume Source KEP: https://kep.k8s.io/4639
     ImageSpec image = 9;
+    // Specific image sub path to be used, only necessary if the above image
+    // field is set. If the sub path does not exist in the image, then runtimes
```
[the remark this answers is not in the document]
Comment (mikebrow) [reply staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto:259]: assuming an empty image should not fail if subpath is nil, more or less exploring the meaning of two cases where subpath is nil, empty or populated image volume with nil (default?) subpath..

File: staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto [hunk 8]
```diff
@@ -248,13 +248,18 @@ message Mount {
...
-    // host_path should be unset. All OCI mounts are per feature definition
+    // host_path should be unset. All image mounts are per feature definition
     // readonly. The kubelet does an PullImage RPC and evaluates the returned
     // PullImageResponse.image_ref value, which is then set to the
     // ImageSpec.image field. Runtimes are expected to mount the image as
     // required.
-    // Introduced in the OCI Volume Source KEP: https://kep.k8s.io/4639
+    // Introduced in the Image Volume Source KEP: https://kep.k8s.io/4639
     ImageSpec image = 9;
+    // Specific image sub path to be used, only necessary if the above image
```
[the remark this answers is not in the document]
Comment (saschagrunert) [reply staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto:258]: Thanks, applied as suggested.

File: staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto [hunk 9]
```diff
@@ -248,13 +248,18 @@ message Mount {
     bool recursive_read_only = 8;
     // Mount an image reference (image ID, with or without digest), which is a
     // special use case for image volume mounts. If this field is set, then
-    // host_path should be unset. All OCI mounts are per feature definition
+    // host_path should be unset. All image mounts are per feature definition
     // readonly. The kubelet does an PullImage RPC and evaluates the returned
```
[the remark this answers is not in the document]
Comment (saschagrunert) [reply staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto:252]: Yep, added. :+1:

**Review by mikebrow — APPROVED** [review]
LGTM

File: staging/src/k8s.io/api/core/v1/types.go [hunk 10]
```diff
@@ -217,7 +217,7 @@ type VolumeSource struct {
 	// The types of objects that may be mounted by this volume are defined by the container runtime implementation on a host machine and at minimum must include all valid types supported by the container image field.
 	// The OCI object gets mounted in a single directory (spec.containers[*].volumeMounts.mountPath) by merging the manifest layers in the same way as for container images.
 	// The volume will be mounted read-only (ro) and non-executable files (noexec).
-	// Sub path mounts for containers are not supported (spec.containers[*].volumeMounts.subpath).
+	// Sub path mounts for containers are not supported (spec.containers[*].volumeMounts.subpath) before 1.33.
```
Comment (haircommander) [inline staging/src/k8s.io/api/core/v1/types.go:220]: if KAS has drifted from kubelet and the former supports but the latter doesn't yet is that an issue? the pod will fail at creation time I presume but is that UX alright? Anything we can do?

File: test/e2e_node/image_volume.go [hunk 11]
```diff
@@ -90,6 +92,17 @@ var _ = SIGDescribe("ImageVolume", feature.ImageVolume, func() {
 
 	}
 
+	verifyFileCOntents := func(podName, volumePath string) {
```
Comment (haircommander) [inline test/e2e_node/image_volume.go:95]: Contents* ?

File: pkg/apis/core/validation/validation_test.go [hunk 12]
```diff
@@ -7146,23 +7146,21 @@ func TestValidateVolumeMounts(t *testing.T) {
...
-		"name exists in volumeDevice":                      {{Name: "xyz", MountPath: "/bar"}},
-		"mountpath exists in volumeDevice":                 {{Name: "uvw", MountPath: "/mnt/exists"}},
-		"both exist in volumeDevice":                       {{Name: "xyz", MountPath: "/mnt/exists"}},
-		"rro but not ro":                                   {{Name: "123", MountPath: "/rro-bad1", ReadOnly: false, RecursiveReadOnly: ptr.To(core.RecursiveReadOnlyEnabled)}},
-		"rro with incompatible propagation":                {{Name: "123", MountPath: "/rro-bad2", ReadOnly: true, RecursiveReadOnly: ptr.To(core.RecursiveReadOnlyEnabled), MountPropagation: ptr.To(core.MountPropagationHostToContainer)}},
-		"rro-if-possible but not ro":                       {{Name: "123", MountPath: "/rro-bad1", ReadOnly: false, RecursiveReadOnly: ptr.To(core.RecursiveReadOnlyIfPossible)}},
-		"subPath not allowed for image volume sources":     {{Name: "image-volume", MountPath: "/image-volume-err-1", SubPath: "/foo"}},
-		"subPathExpr not allowed for image volume sources": {{Name: "image-volume", MountPath: "/image-volume-err-2", SubPathExpr: "$(POD_NAME)"}},
```
Comment (haircommander) [inline pkg/apis/core/validation/validation_test.go:7165]: possible to add new success cases for these?

Comment (saschagrunert) [reply pkg/apis/core/validation/validation_test.go:7165]: Yes, added 2 succeeding and one failure test case.

File: test/e2e_node/image_volume.go (hunk 11 above)
Comment (saschagrunert) [reply test/e2e_node/image_volume.go]: Fixed :+1:

File: staging/src/k8s.io/api/core/v1/types.go (hunk 10 above)
Comment (saschagrunert) [reply staging/src/k8s.io/api/core/v1/types.go:220]: If the API server allows the sub path but the kubelet not, then the kubelet will ignore it. 
If the kubelet supports the sub path but the runtime not, then the runtime will ignore it.

**Review by haircommander — APPROVED** [review]
LGTM

**Comment by saschagrunert** [comment]
/assign @liggitt 

Kindly requesting API review. We have 2 LGTMs from SIG Node now.

File: pkg/features/versioned_kube_features.go [hunk 13]
```diff
@@ -404,6 +404,7 @@ var defaultVersionedKubernetesFeatureGates = map[featuregate.Feature]featuregate
 
 	ImageVolume: {
 		{Version: version.MustParse("1.31"), Default: false, PreRelease: featuregate.Alpha},
+		{Version: version.MustParse("1.33"), Default: false, PreRelease: featuregate.Beta},
```
Comment (liggitt) [inline pkg/features/versioned_kube_features.go:407]: I see the validation change happening, so it makes sense to wait to default-enable until the next release.

I haven't followed the feature, what's the purpose behind promoting to beta but keeping disabled by default?

File: staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto [hunk 14]
```diff
@@ -248,13 +248,19 @@ message Mount {
...
     // required.
-    // Introduced in the OCI Volume Source KEP: https://kep.k8s.io/4639
+    // Introduced in the Image Volume Source KEP: https://kep.k8s.io/4639
     ImageSpec image = 9;
+    // Specific image sub path to be used from inside the image instead of it's
+    // root, only necessary if the above image field is set. If the sub path is
+    // not empty and does not exist in the image, then runtimes should fail and
+    // return an error.
+    // Introduced in the Image Volume Source KEP beta graduation: https://kep.k8s.io/4639
+    string image_sub_path = 10;
```
Comment (liggitt) [inline staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto:263]: Built-in volumes use something like this to specially safely handle subpaths - `subpather.SafeMakeDir(subPath, volumePath, perm)`

Does image_sub_path get safely handled by container runtimes like the built-in volume types?

File: pkg/features/versioned_kube_features.go (hunk 13 above)
Comment (saschagrunert) [reply pkg/features/versioned_kube_features.go:407]: That decision was made as part of the containerd support discussion: https://github.com/haircommander/enhancements-1/blob/edb4738bb0f5b7ee8a6021c51263ad0bde099fc8/keps/sig-node/4639-oci-volume-source/README.md#beta

Now, containerd has merged https://github.com/containerd/containerd/pull/10579 which is not part of any release yet. So I assume this still holds valid.

File: staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto (hunk 14 above)
Comment (saschagrunert) [reply staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto:263]: They need to, yes. CRI-O usually uses [filepath-securejoin](https://github.com/cyphar/filepath-securejoin) to guard cases like that.

Comment (mikebrow) [reply staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto:263]: agreed.. will do something similar in containerd..

**Comment by saschagrunert** [comment]
@liggitt PTAL again :)

**Comment by liggitt** [comment]
/approve
for API changes

**Comment by saschagrunert** [comment]
@kubernetes/sig-node-pr-reviews PTAL, I still need an LGTM from the SIG

File: staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto [hunk 15]
```diff
@@ -248,13 +248,19 @@ message Mount {
...
-    // readonly. The kubelet does an PullImage RPC and evaluates the returned
+    // host_path should be unset. All image mounts are per feature definition
+    // readonly (noexec). The kubelet does an PullImage RPC and evaluates the returned
     // PullImageResponse.image_ref value, which is then set to the
     // ImageSpec.image field. Runtimes are expected to mount the image as
     // required.
-    // Introduced in the OCI Volume Source KEP: https://kep.k8s.io/4639
+    // Introduced in the Image Volume Source KEP: https://kep.k8s.io/4639
     ImageSpec image = 9;
+    // Specific image sub path to be used from inside the image instead of it's
```
Comment (mrunalp) [inline staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto:258]:
```suggestion
    // Specific image sub path to be used from inside the image instead of its
```

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 4 above)
Comment (mrunalp) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:1354]: Can we define a CRI error for tracking image mount failures and propagate that? I think without that we can't clearly know which part of the pod startup is failing and how image mount is contributing to that.

File: staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto (hunk 15 above)
Comment (saschagrunert) [reply staging/src/k8s.io/cri-api/pkg/apis/runtime/v1/api.proto:258]: Yep, fixed as suggested :+1:

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 4 above)
Comment (saschagrunert) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: Yes, updated the implementation to work with a cri-api error. :+1:

File: test/e2e_node/image_volume.go [hunk 16]
```diff
@@ -90,6 +92,17 @@ var _ = SIGDescribe("ImageVolume", feature.ImageVolume, func() {
...
 
+	verifyFileContents := func(podName, volumePath string) {
+		ginkgo.By(fmt.Sprintf("Verifying the volume mount contents for path: %s", volumePath))
+
+		firstFileContents := e2epod.ExecCommandInContainer(f, podName, containerName, "/bin/cat", filepath.Join(volumePath, "data.json"))
+		gomega.Expect(firstFileContents).To(gomega.ContainSubstring("kitten.jpg"))
+
+		secondFileContents := e2epod.ExecCommandInContainer(f, podName, containerName, "/bin/cat", filepath.Join(volumePath, "etc", "os-release"))
+		gomega.Expect(secondFileContents).To(gomega.ContainSubstring("Alpine Linux"))
+
```
Comment (mrunalp) [inline test/e2e_node/image_volume.go:103]: nit: empty line

**Review by mrunalp — APPROVED** [review]
/lgtm

File: test/e2e_node/image_volume.go (hunk 16 above)
Comment (saschagrunert) [reply test/e2e_node/image_volume.go:103]: Thank you, I’ll do that in the follow-up!
