### PR TITLE
Let local node e2e return error.

### LINKED ISSUE #52665: `make test-e2e-node` should exit with non-zero exit code for test failure
Currently, `make test-e2e-node` always returns with 0 exit code no matter the test fails or not.

We should fix it to return non-zero exit code for test failure.

### PR DESCRIPTION
**Pull request by Random-Liu**
Fixes #52665

Let `make test-e2e-node` return error when it fails. Now it always returns exit code 0, whenever it fails or not.

@yguo0905 Could you help me review this?

Signed-off-by: Lantao Liu <lantaol@google.com>

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
LGTM

**Comment by yguo0905** [comment]
/lgtm
Do we have a associated issue?

**Comment by Random-Liu** [comment]
> Do we have a associated issue?

I could file one.

**Comment by Random-Liu** [comment]
Fixes #52665

File: hack/make-rules/test-e2e-node.sh [hunk 1]
```diff
@@ -138,7 +138,7 @@ if [ $remote = true ] ; then
     --delete-instances="$delete_instances" --test_args="$test_args" --instance-metadata="$metadata" \
     --image-config-file="$image_config_file" --system-spec-name="$system_spec_name" \
     2>&1 | tee -i "${artifacts}/build-log.txt"
-  exit $?
+  exit "${PIPESTATUS[0]}"
```
Comment (ixdy) [inline hack/make-rules/test-e2e-node.sh]: since `hack/lib/init.sh` sets `-o errexit` and `-o pipefail`, I'm not sure we even get to this line.

Comment (Random-Liu) [reply hack/make-rules/test-e2e-node.sh]: Good to know. Will change back then. :)

Comment (Random-Liu) [reply hack/make-rules/test-e2e-node.sh]: Done

**Comment by ixdy** [comment]
is there an associated issue?

**Comment by Random-Liu** [comment]
@ixdy Yeah https://github.com/kubernetes/kubernetes/issues/52665.

Thanks for reviewing! :)
