### PR TITLE
Don't return error when findmnt exits with error.

### LINKED ISSUE #21303: findmnt doesn't work on all distros
I can't run any containers with newest `hyperkube:v1.2.0-alpha.7`. I get the following error:

```
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Reason		Message
  ─────────	────────	─────	────			─────────────	──────		───────
  3m		3m		1	{default-scheduler }			Scheduled	Successfully assigned nginx-c2rdu to 127.0.0.1
  3m		1m		11	{kubelet 127.0.0.1}			FailedMount	Unable to mount volumes for pod "nginx-c2rdu_default(8dfd262c-d49e-11e5-bad9-bc305be02f04)": IsLikelyNotMountPoint("/var/lib/kubelet/pods/8dfd262c-d49e-11e5-bad9-bc305be02f04/volumes/kubernetes.io~secret/default-token-eorir"): file does not exist
  3m		1m		11	{kubelet 127.0.0.1}			FailedSync	Error syncing pod, skipping: IsLikelyNotMountPoint("/var/lib/kubelet/pods/8dfd262c-d49e-11e5-bad9-bc305be02f04/volumes/kubernetes.io~secret/default-token-eorir"): file does not exist
```

I'm using docker 1.9.1.

@bryk

### PR DESCRIPTION
**Pull request by fgrzadkowski**
Fixes #21303 

@luxas

### CODE REVIEW

**Comment by fgrzadkowski** [comment]
I pushed hyperkube from HEAD with this PR to `fgrzadkowski/hyperkube:fixed_findmnt`

**Comment by fgrzadkowski** [comment]
@k8s-bot test this please github issue: #19732

**Comment by luxas** [comment]
LGTM

FYI, this will overwrite: #21357
Maybe you could merge his patch and rebase this one (just to be kind). Your choice...

File: cluster/saltbase/salt/generate-cert/make-ca-cert.sh [hunk 1]
```diff
@@ -18,7 +18,7 @@ set -o errexit
 set -o nounset
 set -o pipefail
 
-if [ "${DEBUG}" == "true" ]; then
```
Comment (saad-ali) [inline cluster/saltbase/salt/generate-cert/make-ca-cert.sh]: What's the point of this if no default is specified?

File: cluster/saltbase/salt/generate-cert/make-ca-cert.sh [hunk 2]
```diff
@@ -18,7 +18,7 @@ set -o errexit
...
+if [ "${DEBUG:-}" == "true" ]; then
```
Comment (saad-ali) [inline cluster/saltbase/salt/generate-cert/make-ca-cert.sh]: What's the point of this if no default is specified?

File: pkg/util/mount/nsenter_mount.go [hunk 3]
```diff
@@ -176,10 +176,11 @@ func (n *NsenterMounter) IsLikelyNotMountPoint(file string) (bool, error) {
...
 	if err != nil {
-		glog.Errorf("Failed to nsenter mount, return file doesn't exist: %v", err)
-		// If the command itself is correct, then if we encountered error
-		// then most likely this means that the directory does not exist.
-		return true, os.ErrNotExist
+		glog.V(2).Infof("Failed findmnt command: %v", err)
+		// Different operating systems behave differently for paths which are not mount points.
+		// On older versions (e.g. 2.20.1) we'd get error, on newer ones (e.g. 2.26.2) we'd get "/".
+		// It's safer to assume that it's not a mount point.
+		return true, nil
```
Comment (saad-ali) [inline pkg/util/mount/nsenter_mount.go]: I'm a little concerned about all `findmnt` errors being swallowed. Can we target this such that only the exact error returned by older versions when path is not mount point results in the error getting swallowed? That way all other errors continue to be blocking, instead of resulting in unpredictable mount/unmount behavior.

File: cluster/saltbase/salt/generate-cert/make-ca-cert.sh (hunk 2 above)
Comment (luxas) [inline cluster/saltbase/salt/generate-cert/make-ca-cert.sh]: It's just that now the whole script fails because of that line, and says something like `unset variable DEBUG. Exiting...`.
This fixes so it debugs if the flag is set, otherwise not

Comment (saad-ali) [inline cluster/saltbase/salt/generate-cert/make-ca-cert.sh]: Got it.

File: pkg/util/mount/nsenter_mount.go (hunk 3 above)
Comment (fgrzadkowski) [inline pkg/util/mount/nsenter_mount.go]: There's no such thing as "exact error". The only signal we get is that bash command exits with 1.

btw. this used to be like this earlier (see https://github.com/kubernetes/kubernetes/pull/13446). For reasons I don't remember I changed it to few months ago to treat errors as `os.ErrNotExists`, but apparently didn't test it properly at that time.

We can consider checking version of `findmnt` or `util-linux` package, but that might be an overkill (how to do it, anyway?)

File: cluster/saltbase/salt/generate-cert/make-ca-cert.sh (hunk 2 above)
Comment (fgrzadkowski) [inline cluster/saltbase/salt/generate-cert/make-ca-cert.sh]: As @luxas suggest I'll wait for #21357 to be merged and revert change to this line.

**Comment by fgrzadkowski** [comment]
For some strange reason the was interrupted:
```
Received interrupt.  Running AfterSuite...
^C again to terminate immediately
```

I'll close and reopen PR.

File: pkg/util/mount/nsenter_mount.go (hunk 3 above)
Comment (saad-ali) [inline pkg/util/mount/nsenter_mount.go]: Sounds good. Thanks

**Comment by saad-ali** [comment]
LGTM

**Comment by fgrzadkowski** [comment]
This is fixing P1 issue for v1.2.
