### PR TITLE
deflake e2e: ensure pod with sidecars restarts in correct order after node reboot

### LINKED ISSUE #132930: Failure cluster [07b6cb95...]
##### Error text:
```
[FAILED] couldn't find restartable-init-2 Started, got
0) 2025-06-30 10:54:03.893 +0000 UTC init-1 Starting
1) 2025-06-30 10:54:03.898 +0000 UTC init-1 Started
2) 2025-06-30 10:54:03.901 +0000 UTC init-1 Delaying
3) 2025-06-30 10:54:08.904 +0000 UTC init-1 Exiting
4) 2025-06-30 10:54:16.641 +0000 UTC regular-1 Starting
5) 2025-06-30 10:54:16.645 +0000 UTC regular-1 Started
6) 2025-06-30 10:54:16.648 +0000 UTC regular-1 Delaying
7) 2025-06-30 10:54:20.451 +0000 UTC init-1 Starting
8) 2025-06-30 10:54:20.457 +0000 UTC init-1 Started
9) 2025-06-30 10:54:20.46 +0000 UTC init-1 Delaying
10) 2025-06-30 10:54:25.464 +0000 UTC init-1 Exiting
In [It] at: k8s.io/kubernetes/test/e2e_node/container_lifecycle_test.go:5533 @ 06/30/25 10:54:26.788

```
#### Recent failures:
[7/14/2025, 7:17:01 AM ci-kubernetes-node-kubelet-cgroupv2-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-kubelet-cgroupv2-serial-cri-o/1944627067370868736)
[7/14/2025, 6:53:00 AM ci-kubernetes-node-swap-fedora-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-fedora-serial/1944621027107540992)
[7/14/2025, 2:52:58 AM ci-kubernetes-node-swap-fedora-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-fedora-serial/1944560628324634624)
[7/13/2025, 10:52:59 PM ci-kubernetes-node-swap-fedora-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-fedora-serial/1944500229776609280)
[7/13/2025, 6:52:59 PM ci-kubernetes-node-swap-fedora-serial](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-node-swap-fedora-serial/1944439831463464960)

/kind flake

/sig node
xref: https://github.com/kubernetes/kubernetes/issues/131544
xref: https://github.com/kubernetes/kubernetes/pull/132811

### PR DESCRIPTION
**Pull request by toVersus**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

Deflake `[sig-node] [Feature:SidecarContainers] [Serial] when A node running restartable init containers reboots should restart the containers in right order with the proper phase after the node reboot` test.

The Pod phase transitioned to Running as soon as the `init-1` container completed. Because of that, the container logs were parsed before `restartable-init-2` had a chance to run, so the logs of both `restartable-init-2` and `init-3` were not captured, causing the test to fail. For more information, see https://github.com/kubernetes/kubernetes/issues/132930#issuecomment-3311419471.

While preparing this PR, I noticed that the test name says it ensures with the proper pod phase. However, as described in https://github.com/kubernetes/kubernetes/issues/132930#issuecomment-3311419471, the issue remains if a node running a Pod with multiple initContainers (including a restartable init container) is rebooted, the Pod phase transitions to Running immediately after the first init container completes. In other words, the Pod phase is not transitioning properly.

Since fixing this problem will require more time to work out the right approach without breaking the current behavior, how about we temporarily remove the phrase `with the proper phase` from the test name, create a separate issue to track the fix, and then restore the original test once the issue has been addressed? If that sounds reasonable, I’ll open the issue.

#### Which issue(s) this PR is related to:

Fixes #132930

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by toVersus** [comment]
This test failure is unrelated to this change and has already been reported in https://github.com/kubernetes/kubernetes/issues/133611.
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-integration/1969161296163115008

```console
k8s.io/kubernetes/test/integration: volumescheduling
{Failed  === RUN   TestVolumeBindingRescheduling
[-]poststarthook/start-service-ip-repair-controllers failed: not finished
[-]poststarthook/rbac/bootstrap-roles failed: not finished
[-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
[-]poststarthook/priority-and-fairness-config-producer failed: not finished
[-]poststarthook/bootstrap-controller failed: not finished
[-]poststarthook/start-kubernetes-service-cidr-controller failed: not finished
[-]poststarthook/start-service-ip-repair-controllers failed: not finished
[-]poststarthook/rbac/bootstrap-roles failed: not finished
[-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
[-]poststarthook/priority-and-fairness-config-producer failed: not finished
[-]poststarthook/start-kubernetes-service-cidr-controller failed: not finished
(...)
```

/retest

**Comment by toVersus** [comment]
The test failure is unrelated to this change and one of them are already reported in https://github.com/kubernetes/kubernetes/issues/131703. 
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-node-kubelet-serial-containerd/1969186800425504768

```
E2eNode Suite: [It] [sig-node] Device Plugin [Serial] [Feature:DevicePlugin] DevicePlugin [Serial] [Disruptive] Does not keep device plugin assignments across node reboots if fails admission (no pod restart, no device plugin re-registration)
{ failed [FAILED] device-plugin-errors-6333/device-plugin-test-0485ae70-00ac-46d5-8b21-ff4eef9278a8/device-plugin-test-0485ae70-00ac-46d5-8b21-ff4eef9278a8 failed admission, should not have devices registered
In [It] at: k8s.io/kubernetes/test/e2e_node/device_plugin_test.go:994 @ 09/20/25 00:19:47.566
}

E2eNode Suite: [It] [sig-node] Restart [Serial] [Slow] [Disruptive] Kubelet should correctly account for terminated pods after restart 
{ failed [FAILED] Failed to run sufficient restartNever pods, got 0 but expected 1
In [It] at: k8s.io/kubernetes/test/e2e_node/restart_test.go:181 @ 09/20/25 00:26:33.882
}
```

/test pull-kubernetes-node-kubelet-serial-containerd

**Comment by toVersus** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-node-swap-fedora-serial/1969186800517779456

```
E2eNode Suite: [It] [sig-node] Summary API [NodeConformance] when querying /stats/summary under pressure [Feature:KubeletPSI] [Serial] should report Memory pressure in PSI metrics
{ failed [FAILED] Timed out after 120.012s.
The function passed to Eventually failed at k8s.io/kubernetes/test/e2e_node/summary_test.go:441 with:
Expected
    <[]v1alpha1.PodStats | len:0, cap:0>: 
        []
to match elements: missing expected element summary-test-9773::memory-pressure-pod
In [It] at: k8s.io/kubernetes/test/e2e_node/summary_test.go:446 @ 09/20/25 01:24:08.289
}
```

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial/1969186800601665536

```
E2eNode Suite: [It] [sig-node] Device Plugin [Serial] [Feature:DevicePlugin] DevicePlugin [Serial] [Disruptive] Does not keep device plugin assignments across node reboots if fails admission (no pod restart, no device plugin re-registration)
{ failed [FAILED] device-plugin-errors-2912/device-plugin-test-cfdf9868-545a-4f90-beb9-6002dc67d12d/device-plugin-test-cfdf9868-545a-4f90-beb9-6002dc67d12d failed admission, should not have devices registered
In [It] at: k8s.io/kubernetes/test/e2e_node/device_plugin_test.go:994 @ 09/20/25 00:17:18.914
}
```

/test pull-kubernetes-node-swap-fedora-serial
/test pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial

**Comment by toVersus** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-node-swap-fedora-serial/1969225967079526400

```
E2eNode Suite: [It] [sig-node] Device Plugin [Serial] [Feature:DevicePlugin] DevicePlugin [Serial] [Disruptive] Does not keep device plugin assignments across node reboots if fails admission (no pod restart, no device plugin re-registration) 
```

/test pull-kubernetes-node-swap-fedora-serial
/test pull-kubernetes-node-kubelet-serial-containerd
/test pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial

**Comment by toVersus** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-node-swap-fedora-serial/1969269526155497472

```
E2eNode Suite: [It] [sig-node] Summary API [NodeConformance] when querying /stats/summary under pressure [Feature:KubeletPSI] [Serial] should report Memory pressure in PSI metrics
```

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial/1969269526260355072

```
E2eNode Suite: [It] [sig-node] Device Plugin [Serial] [Feature:DevicePlugin] DevicePlugin [Serial] [Disruptive] Does not keep device plugin assignments across node reboots if fails admission (no pod restart, no device plugin re-registration)
```

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-node-kubelet-serial-containerd/1969269526046445568

```
E2eNode Suite: [It] [sig-node] Device Plugin [Serial] [Feature:DevicePlugin] DevicePlugin [Serial] [Disruptive] Does not keep device plugin assignments across node reboots if fails admission (no pod restart, no device plugin re-registration)

E2eNode Suite: [It] [sig-node] MirrorPodWithGracePeriod when create a mirror pod and the container runtime is temporarily down during pod termination [NodeConformance] [Serial] [Disruptive] the mirror pod should terminate successfully
```



/test pull-kubernetes-node-swap-fedora-serial
/test pull-kubernetes-node-kubelet-serial-containerd
/test pull-kubernetes-cos-cgroupv2-containerd-node-e2e-serial

**Comment by toVersus** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-node-kubelet-serial-containerd/1969316096032903168

```
E2eNode Suite: [It] [sig-node] MirrorPodWithGracePeriod when create a mirror pod and the container runtime is temporarily down during pod termination [NodeConformance] [Serial] [Disruptive] the mirror pod should terminate successfully
```

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-node-swap-fedora-serial/1969316096179703808

```
E2eNode Suite: [It] [sig-node] Device Plugin [Serial] [Feature:DevicePlugin] DevicePlugin [Serial] [Disruptive] Can schedule a pod with a restartable init container [Feature:SidecarContainers]

E2eNode Suite: [It] [sig-node] Device Plugin [Serial] [Feature:DevicePlugin] DevicePlugin [Serial] [Disruptive] Does not keep device plugin assignments across node reboots if fails admission (no pod restart, no device plugin re-registration)

E2eNode Suite: [It] [sig-node] Device Plugin [Serial] [Feature:DevicePlugin] DevicePlugin [Serial] [Disruptive] can make a CDI device accessible in a container

E2eNode Suite: [It] [sig-node] OOMKiller [LinuxOnly] [NodeConformance] [Serial] multi process container The containers terminated by OOM killer should have the reason set to OOMKilled

E2eNode Suite: [It] [sig-node] Summary API [NodeConformance] when querying /stats/summary under pressure [Feature:KubeletPSI] [Serial] should report Memory pressure in PSI metrics

E2eNode Suite: [It] [sig-node] UserNamespaces [LinuxOnly] [Feature:UserNamespacesSupport] [Serial] when UserNamespacesSupport=false in the kubelet will fail to create a hostUsers=false pod

E2eNode Suite: [It] [sig-node] [Serial] Containers Lifecycle when The kubelet restarts when a Pod is initializing the long-running init container should not restart any completed init container, even after the completed init container statuses have been removed and the kubelet restarted

E2eNode Suite: [It] [sig-node] [Serial] Pods status phase should be pending during the execution of the init container after the node reboot
```

/retest

**Comment by toVersus** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-node-kubelet-serial-containerd/1969357536779833344

```
E2eNode Suite: [It] [sig-node] Device Plugin [Serial] [Feature:DevicePlugin] DevicePlugin [Serial] [Disruptive] Does not keep device plugin assignments across node reboots if fails admission (no pod restart, no device plugin re-registration)

E2eNode Suite: [It] [sig-node] MirrorPodWithGracePeriod when create a mirror pod and the container runtime is temporarily down during pod termination [NodeConformance] [Serial] [Disruptive] the mirror pod should terminate successfully
```

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-node-swap-fedora-serial/1969357536884690944

```
E2eNode Suite: [It] [sig-node] Summary API [NodeConformance] when querying /stats/summary under pressure [Feature:KubeletPSI] [Serial] should report Memory pressure in PSI metrics
```

/retest

**Comment by toVersus** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-node-swap-fedora-serial/1969398505734672384

```
E2eNode Suite: [It] [sig-node] Summary API [NodeConformance] when querying /stats/summary under pressure [Feature:KubeletPSI] [Serial] should report Memory pressure in PSI metrics
```

/retest

**Comment by toVersus** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-node-swap-fedora-serial/1969554075796115456

```
E2eNode Suite: [It] [sig-node] Device Plugin [Serial] [Feature:DevicePlugin] DevicePlugin [Serial] [Disruptive] Does not keep device plugin assignments across node reboots if fails admission (no pod restart, no device plugin re-registration)

E2eNode Suite: [It] [sig-node] Summary API [NodeConformance] when querying /stats/summary under pressure [Feature:KubeletPSI] [Serial] should report Memory pressure in PSI metrics
```

/retest

**Comment by toVersus** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-node-swap-fedora-serial/1969595290738495488

```
E2eNode Suite: [It] [sig-node] Device Plugin [Serial] [Feature:DevicePlugin] DevicePlugin [Serial] [Disruptive] Does not keep device plugin assignments across node reboots if fails admission (no pod restart, no device plugin re-registration)

E2eNode Suite: [It] [sig-node] Summary API [NodeConformance] when querying /stats/summary under pressure [Feature:KubeletPSI] [Serial] should report Memory pressure in PSI metrics
```

/retest

**Comment by toVersus** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-node-swap-fedora-serial/1969644142048841728

```
E2eNode Suite: [It] [sig-node] Summary API [NodeConformance] when querying /stats/summary under pressure [Feature:KubeletPSI] [Serial] should report Memory pressure in PSI metrics
```

/retest

**Comment by toVersus** [comment]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-node-swap-fedora-serial/1969670945392037888

/retest

**Comment by toVersus** [comment]
According to https://github.com/kubernetes/kubernetes/issues/134141, the Memory pressure in PSI metrics test always fails on Fedora OS. So it seems impossible to get the `pull-kubernetes-node-swap-fedora-serial` job to pass, no matter how many times it is retried.

I haven’t seen any failures of `[sig-node] [Feature:SidecarContainers] [Serial] when a node running restartable init containers reboots should restart the containers in the right order with the proper phase after the node reboot` other than https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/134173/pull-kubernetes-node-swap-fedora-serial/1969670945392037888 so far. Since many other tests are also failing, I think that failure may have a different cause.

File: test/e2e_node/container_lifecycle_test.go [hunk 1]
```diff
@@ -6016,9 +6016,9 @@ var _ = SIGDescribe(feature.SidecarContainers, framework.WithSerial(), "Containe
 			})
 			framework.ExpectNoError(err)
 
-			ginkgo.By("Waiting for the pod to run after re-initialization")
-			err = e2epod.WaitForPodRunningInNamespace(ctx, f.ClientSet, pod)
-			framework.ExpectNoError(err)
+			ginkgo.By("Verifying all containers are running")
```
Comment (natasha41575) [inline test/e2e_node/container_lifecycle_test.go]: nit: may be clearer if you change this to something like "Waiting for regular container to start running"

**Review by natasha41575 — COMMENTED** [review]
Since this PR is going to close the issue (as it should), can you file a separate issue as discussed in https://github.com/kubernetes/kubernetes/issues/132930#issuecomment-3312658126 to make sure we don't lose it? 

(Apologies if you already did and I missed it)

File: test/e2e_node/container_lifecycle_test.go (hunk 1 above)
Comment (toVersus) [reply test/e2e_node/container_lifecycle_test.go]: Done.

**Comment by toVersus** [comment]
> Since this PR is going to close the issue (as it should), can you file a separate issue as discussed in https://github.com/kubernetes/kubernetes/issues/132930#issuecomment-3312658126 to make sure we don't lose it?

I hadn’t opened an issue yet, so I’ve created one at https://github.com/kubernetes/kubernetes/issues/134232.

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

thank you!
