### PR TITLE
Fix attach command for InitContainers

### LINKED ISSUE #27540: Kubectl attach command doesn't work for InitContainters
Related issue https://github.com/kubernetes/kubernetes/issues/25818

### PR DESCRIPTION
**Pull request by sylwekb**
Added InitContainers to the things that GetContainer in attach.go has to look for to find a container to attach. Also test case added.

fixes #27540

### CODE REVIEW

**Comment by gitfred** [comment]
cc @smarterclayton

File: pkg/kubectl/cmd/attach.go [hunk 1]
```diff
@@ -167,7 +167,7 @@ func (p *AttachOptions) Run() error {
 		if err != nil {
 			return err
 		}
-		if pod.Status.Phase != api.PodRunning {
+		if pod.Status.Phase != api.PodRunning && (pod.Status.Phase == api.PodPending && len(pod.Spec.InitContainers) < 1) {
```
Comment (xiangpengzhao) [inline pkg/kubectl/cmd/attach.go]: use `len(pod.Spec.InitContainers) == 0)` instead of `len(pod.Spec.InitContainers) < 1)`?

File: pkg/kubectl/cmd/attach.go [hunk 2]
```diff
@@ -167,7 +167,7 @@ func (p *AttachOptions) Run() error {
...
 			return fmt.Errorf("pod %s is not running and cannot be attached to; current phase is %s", p.PodName, pod.Status.Phase)
```
Comment (xiangpengzhao) [inline pkg/kubectl/cmd/attach.go]: should also update the comment

File: pkg/kubectl/cmd/attach.go (hunk 1 above)
Comment (gitfred) [inline pkg/kubectl/cmd/attach.go]: ad. 1. no problem, I can change it

ad. 2. It will fail with `error: error executing remote command: error attaching to container: container not found ("<CONTAINTER_NAME>")`. Is that OK?

File: pkg/kubectl/cmd/attach.go (hunk 2 above)
Comment (gitfred) [inline pkg/kubectl/cmd/attach.go]: Did you mean error message? Yes you're right I will update it

Comment (xiangpengzhao) [inline pkg/kubectl/cmd/attach.go]: Yes, I typed a wrong word :sweat_smile:

File: pkg/kubectl/cmd/attach.go (hunk 1 above)
Comment (xiangpengzhao) [inline pkg/kubectl/cmd/attach.go]: I mean, it seems that the expression doesn't cover all the cases. 
cc @smarterclayton

Comment (smarterclayton) [inline pkg/kubectl/cmd/attach.go]: So in general we are not doing this for a lot of reasons (we are actively removing these tests).

Basically, @sttts has a PR that adds the right check - we get the pod and if it's in Succeeded or Failed we print an error, otherwise we leave the Kubelet to write the correct message

File: pkg/kubectl/cmd/attach.go [hunk 3]
```diff
@@ -233,6 +233,11 @@ func (p *AttachOptions) GetContainer(pod *api.Pod) api.Container {
 				return container
 			}
 		}
+		for _, container := range pod.Spec.InitContainers {
```
Comment (smarterclayton) [inline pkg/kubectl/cmd/attach.go]: This part is correct.

File: pkg/kubectl/cmd/attach.go (hunk 1 above)
Comment (sttts) [inline pkg/kubectl/cmd/attach.go]: https://github.com/kubernetes/kubernetes/pull/27359

Comment (gitfred) [inline pkg/kubectl/cmd/attach.go]: So should I change it to include conditions from https://github.com/kubernetes/kubernetes/pull/27359/files#diff-de6f7fc4d605130323893d0b7572045eR177 ? @sttts @smarterclayton ptal

Comment (smarterclayton) [inline pkg/kubectl/cmd/attach.go]: Yes, just those conditions.

**Comment by gitfred** [comment]
updated.

**Comment by sttts** [comment]
@k8s-bot ok to test

**Comment by sttts** [comment]
lgtm

**Comment by sttts** [comment]
@gitfred can you check whether you have signed the Google CLA with the email address used in the commit?

**Comment by gitfred** [comment]
@sttts it was different, changed it to proper one.
