### PR TITLE
Fix eviction dry-run

### LINKED ISSUE #76943: pods/eviction does not honor `dryRun: true`option
**What happened**:
The pods/eviction REST handler does not check options.DryRun, and actually evicts the pod

/sig api-machinery
/assign @apelisse 
/priority important-soon

The integration test for dry run skips all subresources. As part of fixing this, we should fix that test to exercise subresources. There are likely other subresources that do not wire up dry run

### PR DESCRIPTION
**Pull request by apelisse**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #76943

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Fixes a bug where dry-run is not honored for pod/eviction sub-resource.
```

/assign @liggitt

### CODE REVIEW

File: pkg/registry/core/pod/storage/eviction.go [hunk 1]
```diff
@@ -82,6 +83,14 @@ func (r *EvictionREST) New() runtime.Object {
 func (r *EvictionREST) Create(ctx context.Context, obj runtime.Object, createValidation rest.ValidateObjectFunc, options *metav1.CreateOptions) (runtime.Object, error) {
 	eviction := obj.(*policy.Eviction)
```
Comment (liggitt) [inline pkg/registry/core/pod/storage/eviction.go]: eviction.DeleteOptions can be nil, and this would npe

File: pkg/registry/core/pod/storage/eviction.go [hunk 2]
```diff
@@ -82,6 +83,14 @@ func (r *EvictionREST) New() runtime.Object {
...
 
+	// Propagate CreateOptions to eviction.Options, fail if they both exist and don't match.
+	if len(eviction.DeleteOptions.DryRun) != 0 && len(options.DryRun) != 0 && !reflect.DeepEqual(eviction.DeleteOptions.DryRun, options.DryRun) {
+		return nil, fmt.Errorf("conflicting body and header dry-run options, aborting: %v and %v", eviction.DeleteOptions.DryRun, options.DryRun)
+	}
+	if len(options.DryRun) != 0 {
+		eviction.DeleteOptions.DryRun = options.DryRun
```
Comment (liggitt) [inline pkg/registry/core/pod/storage/eviction.go]: This doesn't dryRun the PDB modification done in checkAndDecrement

**Comment by apelisse** [comment]
Updated, PTAL

**Comment by apelisse** [comment]
I'll cherry-pick this to the relevant branches (probably 1.13, 1.14)
