### PR TITLE
Wait until master IP is visible

### LINKED ISSUE #32789: Kubemark presubmit is sometimes failing without running a test and clear evidence of problems
I'm seeing the following failures of Kubemark in presubmit:
```
...
targetTags:
- k6k-e2e-agent-pr-22-0-minion
2016/09/14 11:21:27 e2e.go:439: Step 'up' finished in 5m2.14340139s
2016/09/14 11:21:27 e2e.go:437: Running: 'kubectl version --match-server-version=false'
Client Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.7-beta.0.11+9d45146efd432f", GitCommit:"9d45146efd432f4b27632f30c3a40150add10852", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2+", GitVersion:"v1.2.7-beta.0.11+9d45146efd432f", GitCommit:"9d45146efd432f4b27632f30c3a40150add10852", GitTreeState:"clean"}
2016/09/14 11:21:27 e2e.go:439: Step ''kubectl version --match-server-version=false'' finished in 214.236441ms
2016/09/14 11:21:27 e2e.go:437: Running: Stop kubemark
ERROR: (gcloud.compute.instances.delete) Some requests did not succeed:
 - The resource 'projects/k8s-jkns-pr-kubemark/zones/us-central1-f/instances/k6k-e2e-agent-pr-22-0-kubemark-master' was not found

ERROR: (gcloud.compute.disks.delete) Some requests did not succeed:
 - The resource 'projects/k8s-jkns-pr-kubemark/zones/us-central1-f/disks/k6k-e2e-agent-pr-22-0-kubemark-master-pd' was not found

ERROR: (gcloud.compute.firewall-rules.delete) Some requests did not succeed:
 - The resource 'projects/k8s-jkns-pr-kubemark/global/firewalls/k6k-e2e-agent-pr-22-0-kubemark-master-https' was not found
...
```

It calls stop-kubemark without clear reason.

Such failure are e.g. here:
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-kubemark-e2e-gce/153/console
http://kubekins.dls.corp.google.com:8081/job/kubernetes-pull-build-test-kubemark-e2e-gce/159/console

### PR DESCRIPTION
**Pull request by gmarek**
Hopefully fix #32789 (see: https://github.com/kubernetes/kubernetes/pull/33085#issuecomment-248322464)

It's a pretty far-fetched, but this might fix our GCE cluster startup problems. @mikedanese @fejta @wojtek-t

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33097)

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot test this, issue: https://github.com/kubernetes/kubernetes/issues/32366

File: cluster/gce/util.sh [hunk 1]
```diff
@@ -411,7 +411,21 @@ function create-static-ip() {
...
+      # successful operation - wait until it's visible
+      start="$(date +%s)"
+      while true; do
+        now="$(date +%s)"
+        # Timeout set to 15 minutes
+        if [ $((now - start)) -gt 900 ]; then
+          echo "Timeout while waiting for master IP visibility"
+          exit 2
+        fi
+        if cloud compute addresses describe "$1" --project "${PROJECT}" --region "${REGION}" >/dev/null 2>&1; then
```
Comment (gmarek) [inline cluster/gce/util.sh]: Done.
