### PR TITLE
Fix some scheduler metrics(pending_pods and schedule_attempts_total) are not recorded.

### LINKED ISSUE #87690: some scheduler metrics(pending_pods, schedule_attempts_total) was not recorded.
**What happened**:

two scheduler metrics, `pending_pods` and `schedule_attempts_total`, was not recorded in `v1.17.0`.

scheduler has some code for this already.  It seems to be a bug.

https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/metrics/metrics.go#L58-L63
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/metrics/metrics.go#L149-L155

**What you expected to happen**:

`pending_pods` and `schedule_attempts_total` was recorded

**How to reproduce it (as minimally and precisely as possible)**:

```shell
#
# Create the cluster locally
#
$ kind create cluster
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.17.0) 🖼
...
kubectl cluster-info --context kind-kind

#
# Create a pod being scheduled
#
$ kubectl run --restart=Never --image=busybox test echo hello
pod/test created

$ kubectl get pod
NAME   READY   STATUS      RESTARTS   AGE
test   0/1     Completed   0          15s

# portforward to scheduler
$ kubectl -n kube-system port-forward kube-scheduler-kind-control-plane 10251:10251
Forwarding from 127.0.0.1:10251 -> 10251
Forwarding from [::1]:10251 -> 10251

#
# In another terminal
#

# Confirm some scheduler metrics was recorded
$ curl -s http://localhost:10251/metrics
...
# HELP scheduler_binding_duration_seconds [ALPHA] Binding latency in seconds
# TYPE scheduler_binding_duration_seconds histogram
scheduler_binding_duration_seconds_bucket{le="0.001"} 0
...

# BUT, `pending_pods` and `schedule_attempts_total` was not recorded....
$ curl http://localhost:10251/metrics | grep pending_pods
______NO_OUTPUT!!__SOME_METRICS_SHOULD_BE_HERE_______
$ curl http://localhost:10251/metrics | grep schedule_attempts_total
______NO_OUTPUT!!__SOME_METRICS_SHOULD_BE_HERE_______
```

---
/king bug
/sig scheduling

### PR DESCRIPTION
**Pull request by everpeace**
**What type of PR is this?**

/kind bug
/sig scheduling

**What this PR does / why we need it**:

fix two scheduler metrics (`pending_pods` and `schedule_attempts_total`) are not recorded.

**Which issue(s) this PR fixes**:

Fixes #87690 

**Special notes for your reviewer**:

[`scheduler/metrics.{PodScheduleSuccesses, PodScheduleFailures, PodScheduleErrors}`](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/metrics/metrics.go#L58-L63) and [`scheduler/metrics.PendingPodsRecorders(ActivePods, UnschedulablePods, BackoffPods)`](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/internal/queue/scheduling_queue.go#L217-L224) seems to too early to be  initialized.

All the `k8s.io/component-base/metrics`'s metrics primitives are lazy metric.  So, calling `some_metric.With(labels)` before registration [returns `noop` metrics](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/metrics/gauge.go#L144-L146).

So I made mainly two modifications.

- move `scheduler/metrics.Registry()` before crerating scheduler queue
- delayed `PodScheduleSuccesses, PodScheduleFailures, PodScheduleErrors` metrics' initialization

**Does this PR introduce a user-facing change?**:

```release-note
fixed two scheduler metrics (pending_pods and schedule_attempts_total) not being recorded
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

none.

### CODE REVIEW

File: pkg/scheduler/scheduler_test.go [hunk 1]
```diff
@@ -21,6 +21,7 @@ import (
 	"errors"
 	"fmt"
 	"io/ioutil"
+	"k8s.io/kubernetes/pkg/scheduler/metrics"
```
Comment (skilxn-go) [inline pkg/scheduler/scheduler_test.go]: Wrong order of this import?

File: pkg/scheduler/scheduler.go [hunk 2]
```diff
@@ -599,10 +608,10 @@ func (sched *Scheduler) scheduleOne(ctx context.Context) {
 			// Pod did not fit anywhere, so it is counted as a failure. If preemption
 			// succeeds, the pod should get counted as a success the next time we try to
 			// schedule it. (hopefully)
-			metrics.PodScheduleFailures.Inc()
+			sched.podScheduleFailureCounter.Inc()
```
Comment (skilxn-go) [inline pkg/scheduler/scheduler.go]: Will it be better to call metrics. PodScheduleFailures() here instead of storing the counter in the scheduler?  Maybe we should keep scheduler and metrics decoupling?

Comment (everpeace) [reply pkg/scheduler/scheduler.go]: `PodScheduleFailures()` call causes `(*lazyMetric) IsCreated()` method and it get read lock([code](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/metrics/metric.go#L76-L80)).  So, calling `PodScheduleFailures()` each time increases overhead.  I think its trade-off.  Should we take decoupling or performance?

File: pkg/scheduler/scheduler_test.go (hunk 1 above)
Comment (everpeace) [reply pkg/scheduler/scheduler_test.go]: Thanks! I fixed.

File: pkg/scheduler/scheduler.go (hunk 2 above)
Comment (skilxn-go) [reply pkg/scheduler/scheduler.go]: Then how about just delay the initialize of scheduler/metrics.{PodScheduleSuccesses, PodScheduleFailures, PodScheduleErrors}. It can be moved to metrics.Register(), I guess.

1. Declare them and initialize them with `noop`.
2. Re-assign them to xxx.With() in metrics.Register().

WDYT

Comment (everpeace) [reply pkg/scheduler/scheduler.go]: ah, nice idea.  I'll do so.  Thanks for the idea.

File: pkg/scheduler/scheduler.go [hunk 3]
```diff
@@ -291,6 +291,8 @@ func New(client clientset.Interface,
 		nodeInfoSnapshot:               snapshot,
 	}
 
+	metrics.Register()
```
Comment (ahg-g) [inline pkg/scheduler/scheduler.go]: why moving this to here makes a difference?

**Review by ahg-g — COMMENTED** [review]
/cc @liu-cong 

We should back port this to 1.17

File: pkg/scheduler/metrics/metrics.go [hunk 4]
```diff
@@ -262,6 +265,9 @@ func Register() {
 			legacyregistry.MustRegister(metric)
 		}
 		volumeschedulingmetrics.RegisterVolumeSchedulingMetrics()
+		PodScheduleSuccesses = scheduleAttempts.With(metrics.Labels{"result": "scheduled"})
```
Comment (ahg-g) [inline pkg/scheduler/metrics/metrics.go]: instead of doing this, perhaps we should follow the pendingPods metric approach, define functions that return the metric (see lines 275-292)

File: pkg/scheduler/scheduler.go (hunk 3 above)
Comment (ahg-g) [reply pkg/scheduler/scheduler.go]: oh, because it has to be done before initializing the scheduling_queue

File: pkg/scheduler/metrics/metrics.go (hunk 4 above)
Comment (ahg-g) [reply pkg/scheduler/metrics/metrics.go]: ok, I guess we access those handlers directly in the scheduler, ok I guess this is fine.

**Comment by ahg-g** [comment]
Looking at v1.16 and v1.15, registering the metrics has always been done after creating the queue, I wonder why this is an issue now.

**Comment by liu-cong** [comment]
> We should back port this to 1.17

Isn't this a bug since the beginning so we need to backport to all applicable versions?

**Comment by ahg-g** [comment]
> > We should back port this to 1.17
> 
> Isn't this a bug since the beginning so we need to backport to all applicable versions?

Yes we do, I realized that this is a bug in 1.16 and 1.15 after I posted this.

**Comment by ahg-g** [comment]
I think commit https://github.com/kubernetes/kubernetes/commit/8da448dbe34ddcc64e943a06e4a8436e6ecc9204 is the main culprit, it switched the scheduler from Prometheus to k8s wrapper in 1.16, but didn't fix the registration.

Ok, so this fix must be backported to 1.17 and 1.16 (just backport the call to Register to happen earlier since the attempts metric doesn't exist in 1.16)

File: pkg/scheduler/scheduler.go (hunk 3 above)
Comment (everpeace) [reply pkg/scheduler/scheduler.go]: Yes, it is the reason.  I wanted to find a more essential & safe way to `Register` metric instances, though.

**Comment by everpeace** [comment]
Thanks for the quick review!!

/retest

**Comment by everpeace** [comment]
hmm, I'm not familiar with e2e test.  I believe that my change would not affect e2e.  I'm not sure what can I do other than /retest .

File: pkg/scheduler/metrics/metrics.go [hunk 5]
```diff
@@ -56,10 +56,13 @@ var (
 			StabilityLevel: metrics.ALPHA,
 		}, []string{"result"})
 	// PodScheduleSuccesses counts how many pods were scheduled.
+	// the metric will be initialized again in Register() to assure the metric is not no-op metric.
```
Comment (haosdent) [inline pkg/scheduler/metrics/metrics.go]: s/the metric/This metric/g

Comment (everpeace) [reply pkg/scheduler/metrics/metrics.go]: Thanks!  fixed.

**Review by draveness — COMMENTED** [review]
Thanks, please squash the commit.

/hold

**Comment by everpeace** [comment]
squashed. /unhold
