### PR TITLE
Delete remote endpoint if it has same ip as local endpoint in the system.

### LINKED ISSUE #137381: Windows: Seeing intermittent DNS issues on k8s > 1.30
### What happened?

When operating in environments with high pod churn rates—where pods are frequently created and terminated—and multiple services are configured to reference a single deployment, we observed that network connectivity on some of the pods is failing on windows nodes.

On the pods where we have network issue, tried to do DNS lookup by exec into the pods and it failed to resolve the DNS.

Attached are the logs on two windows nodes

[9a98.zip](https://github.com/user-attachments/files/25727718/9a98.zip)

[bf83.zip](https://github.com/user-attachments/files/25727725/bf83.zip)

### What did you expect to happen?

Network connectivity shouldn't break on windows pods and DNS resolution should succeed.

### How can we reproduce it (as minimally and precisely as possible)?

1.  Deploy kubernetes cluster with limited available IPs for pods on both Linux and Windows node.
2. Deploy Linux pods that consume almost all IPs.
3. Deploy service type LoadBalancer that refer to Linux pods, This will trigger kube-proxy to create Remote HNS endpoint on Windows. This Remote HNS endpoint will have Linux pod IP.
4. Scale down the Linux pods to 1.
5. Do multiple time scaling up and down.
6. Deploy windows deployment with multiple replicas and have multiple service referencing the deployment.
7. Scale down the windows pods to 1.
8. Perform the same operation multiple time (scaling up and down)
9. After few days we see that on few of the pods, if we do the nslookup, it fails to connect and resolve DNS.

### Anything else we need to know?

I was going through the below PR and want to check whether any regression caused the network connectivity issue. 
PR1: https://github.com/kubernetes/kubernetes/pull/135146
PR2: https://github.com/kubernetes/kubernetes/pull/133953
All our customers reported that, they are seeing intermittent network connectivity issues on K8S >1.30. 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
1.31 and higher versions
```

</details>

### Cloud provider

<details>
EKS

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
BuildNumber  Caption                                   OSArchitecture  Version
20348        Microsoft Windows Server 2022 Datacenter  64-bit          10.0.20348
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by princepereira**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

**Handling Stale Remote Endpoints When Local and Remote Endpoints Share the Same IP (getAllEndpointsByNetwork)**

On Windows Server 2019 and Windows Server 2022, within an L2Bridge network configuration, all pods across cluster nodes typically share the same pod subnet.

In scenarios where the subnet range is limited, or even when larger ranges are heavily utilized, IP address reuse can occur. For example, when a pod assigned an IP address (e.g., 10.0.0.1) is deleted, that IP may later be reassigned to a new pod on a different node immediately. In such cases, the CNI creates a new local endpoint for the reused IP.

However, the corresponding remote endpoint associated with the previously deleted pod may not yet have been cleaned up, as it could still be awaiting deletion signals. Because the IP is already reassigned locally, KubeProxy may inadvertently increase the reference count of the stale remote endpoint and delay its removal. This can result in both a local and a remote endpoint coexisting with the same IP address in HNS.

This duplication can lead to unintended behavior. For instance, when a pod using the reused IP attempts DNS resolution, traffic is load-balanced at the host port (particularly in non-DSR mode). After DNAT, the VFP rule may select the MAC address of the remote endpoint instead of the local pod. Since subsequent VFP processing interprets this as traffic destined for a remote endpoint, packets may be encapsulated and routed to an incorrect node rather than the appropriate DNS pod. This can ultimately cause DNS timeouts.

To address this issue, the fix prioritizes local endpoints. When a local endpoint is detected for an IP that also has a remote endpoint, the remote endpoint is marked for deletion and replaced by the local one. Additionally, any stale remote endpoints with duplicate IP addresses are systematically cleaned up using deleteAllRemoteEndpointsWithDupIP at the end of each syncProxyRules() cycle.

#### Which issue(s) this PR is related to:
Fixes #137381 

#### Does this PR introduce a user-facing change?

```release-note
Fixed stale remote HNS endpoint cleanup on Windows when a pod IP is reused across nodes in L2Bridge networks, preventing DNS timeouts caused by traffic being routed to the wrong node.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```
/sig windows
/sig network
/area kube-proxy

### CODE REVIEW

**Comment by smandhada16** [comment]
cc: @KlwntSingh for visibility

File: pkg/proxy/winkernel/hns.go [hunk 1]
```diff
@@ -142,22 +148,30 @@ func (hns hns) getAllEndpointsByNetwork(networkName string) (map[string]*(endpoi
...
-			if existingEp, ok := endpointInfos[ipConfig.IpAddress]; ok && isLocal {
-				// If the endpoint is already part of the queried endpoints map and is local,
-				// then we should not add it again to the map
-				// This is to avoid overwriting the remote endpoint info with a local endpoint.
-				klog.V(3).InfoS("Endpoint already exists in queried endpoints map; skipping.", "newLocalEndpoint", ep, "ipConfig", ipConfig, "existingEndpoint", existingEp)
-				continue
+			curEpIsLocal := uint32(ep.Flags&hcn.EndpointFlagsRemoteEndpoint) == 0
+
+			if existingEp, ok := endpointInfos[ipConfig.IpAddress]; ok {
+				if curEpIsLocal && !existingEp.isLocal {
```
Comment (daschott) [inline pkg/proxy/winkernel/hns.go:154]: nit: Would it be beneficial to add some logs here when we delete endpoints or add them to the dup map?

File: pkg/proxy/winkernel/hns.go [hunk 2]
```diff
@@ -172,7 +186,17 @@ func (hns hns) getAllEndpointsByNetwork(networkName string) (map[string]*(endpoi
 	}
 	klog.V(3).InfoS("Queried endpoints from network", "network", networkName, "count", len(endpointInfos))
 	klog.V(5).InfoS("Queried endpoints details", "network", networkName, "endpointInfos", endpointInfos)
-	return endpointInfos, nil
+	return endpointInfos, remoteEPsWithDupIP, nil
+}
+
+func (hns hns) deleteAllRemoteEndpointsWithDupIP(remoteEPsWithDupIP map[string]bool) {
+	for hnsID := range remoteEPsWithDupIP {
```
Comment (daschott) [inline pkg/proxy/winkernel/hns.go:193]: nit: This probably doesn't need to be a map of bools if we are only iterating over the IDs to pass them to a delete directly, could potentially save a tiny bit of memory by storing it in simpler flat 1-dimensional DS, but I don't consider this blocking.

**Review by daschott — APPROVED** [review]
Some very minor nitpicks, lgtm overall, thank you for adding test cases

File: pkg/proxy/winkernel/hns.go (hunk 1 above)
Comment (princepereira) [reply pkg/proxy/winkernel/hns.go:154]: We already have logs that print the same endpoint HNS ID in the `deleteAllRemoteEndpointsWithDupIP` function when invoking delete from HNS. Do you think it’s necessary to add logs here as well, given that it would duplicate the same information?

File: pkg/proxy/winkernel/hns.go (hunk 2 above)
Comment (princepereira) [reply pkg/proxy/winkernel/hns.go:193]: At the moment, we are only handling HNS IDs of remote endpoints, which can have either an IPv4 or an IPv6 address. In the future, if we decide to store both IPs for remote endpoints, similar to what we do for local endpoints, using an array-like data structure may result in duplicate IP entries when dealing with duplicate endpoints that contain two IPs. This could introduce additional complexity and require extra handling during delete operations.

That said, we do not expect a large number of duplicate endpoints in this scenario. Additionally, this issue is specific to L2Bridge networks (where there is a single, large pod subnet for the entire cluster) and is unlikely to occur in overlay clusters, which are more commonly used and where each node has a separate pod subnet.

Please share your thoughts on this. If you still feel that we should optimize for reduced space usage, we can consider using a slice, as it would not pose an issue in the current scenario.

Comment (daschott) [reply pkg/proxy/winkernel/hns.go:193]: No, that's fine, thank you, lgtm

File: pkg/proxy/winkernel/hns.go (hunk 1 above)
Comment (daschott) [reply pkg/proxy/winkernel/hns.go:154]: I saw this, but wasn't 100% sure it would be logged or if more logging would be necessary. LGTM, Thank you for confirming.

**Comment by princepereira** [comment]
> > Hi @princepereira. Thanks for your PR.
> > I'm waiting for a [kubernetes](https://github.com/orgs/kubernetes/people) member to verify that this patch is reasonable to test.
> 
> btw you should really [apply for k8s org membership](https://github.com/kubernetes/community/blob/main/community-membership.md#requirements)...

Sure @danwinship , I’m planning to apply.
Thanks for the suggestion and your consideration 🙂

**Comment by daschott** [comment]
@danwinship is it possible to apply the right milestone tag to be able to merge this, or do we need to wait for thaw? We have some users that are awaiting this fix which are currently on v1.34.

**Comment by princepereira** [comment]
/cc @dims 

Hi @dims,

Please take a look at the PR at your convenience.

Thanks,
Prince Pereira
