### PR TITLE
validate configuration of kube-proxy IPVS tcp,tcpfin,udp timeout

### LINKED ISSUE #88656: kube-proxy doesn't validate IPVS tcp, tcpfin and udp timeouts
**What happened**:

kube-proxy doesn't validate the configurable IPVS tcp, tcpfin and udp timeouts. 
For example, when kube-proxy starts with `--ipvs-tcp-timeout=900s --ipvs-udp-timeout=-1s`, it will always log a warning: `failed to configure IPVS timeouts: invalid argument` .

**What you expected to happen**:

kube-proxy should validate --ipvs-tcp-timeout, --ipvs-tcpfin-timeout, --ipvs-udp-timeout flag values at start.

**How to reproduce it (as minimally and precisely as possible)**:

add `--ipvs-tcp-timeout=900s --ipvs-udp-timeout=-1s` flags to kube-proxy

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by chendotjs**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

kube-proxy should validate --ipvs-tcp-timeout, --ipvs-tcpfin-timeout, --ipvs-udp-timeout flag values at start.

**Which issue(s) this PR fixes**:

Fixes #88656

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
validate kube-proxy flags --ipvs-tcp-timeout, --ipvs-tcpfin-timeout, --ipvs-udp-timeout
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/proxy/apis/config/validation/validation.go [hunk 1]
```diff
@@ -283,6 +284,24 @@ func validateKubeProxyNodePortAddress(nodePortAddresses []string, fldPath *field
 	return allErrs
 }
 
+func validateIPVSTimeout(config kubeproxyconfig.KubeProxyIPVSConfiguration, fldPath *field.Path) field.ErrorList {
```
Comment (aojea) [inline pkg/proxy/apis/config/validation/validation.go]: do we need to move it to an independent function?
Seems that the conntrack timeouts are validated in the same function
> config.TCPCloseWaitTimeout.Duration
> config.TCPEstablishedTimeout.Duration

File: pkg/proxy/apis/config/validation/validation.go [hunk 2]
```diff
@@ -283,6 +284,24 @@ func validateKubeProxyNodePortAddress(nodePortAddresses []string, fldPath *field
...
+	allErrs := field.ErrorList{}
+
+	if config.TCPTimeout.Duration < 0 {
+		allErrs = append(allErrs, field.Invalid(fldPath.Child("TCPTimeout"), config.MinSyncPeriod, "must be greater than or equal to 0"))
```
Comment (andrewsykim) [inline pkg/proxy/apis/config/validation/validation.go]: config.MinSyncPeriod -> config.TCPTimeout

File: pkg/proxy/apis/config/validation/validation.go [hunk 3]
```diff
@@ -283,6 +284,24 @@ func validateKubeProxyNodePortAddress(nodePortAddresses []string, fldPath *field
...
+	}
+
+	if config.TCPFinTimeout.Duration < 0 {
+		allErrs = append(allErrs, field.Invalid(fldPath.Child("TCPFinTimeout"), config.MinSyncPeriod, "must be greater than or equal to 0"))
```
Comment (andrewsykim) [inline pkg/proxy/apis/config/validation/validation.go]: config.MinSyncPeriod -> config.TCPFinTimeout

File: pkg/proxy/apis/config/validation/validation.go [hunk 4]
```diff
@@ -283,6 +284,24 @@ func validateKubeProxyNodePortAddress(nodePortAddresses []string, fldPath *field
...
+	}
+
+	if config.UDPTimeout.Duration < 0 {
+		allErrs = append(allErrs, field.Invalid(fldPath.Child("UDPTimeout"), config.MinSyncPeriod, "must be greater than or equal to 0"))
```
Comment (andrewsykim) [inline pkg/proxy/apis/config/validation/validation.go]: config.MinSyncPeriod -> config.UDPTimeout

File: pkg/proxy/apis/config/validation/validation.go (hunk 1 above)
Comment (lbernail) [reply pkg/proxy/apis/config/validation/validation.go]: I think it makes to have a function for this given the current way we validate the ipvs configuration

**Comment by lbernail** [comment]
Thanks @chendotjs !
Once the small typos mentioned by @andrewsykim are addressed we'll lgtm

**Comment by chendotjs** [comment]
Thanks @aojea for review. 
😅Typos are fixed, please take another look. @lbernail @andrewsykim

**Review by andrewsykim — COMMENTED** [review]
/lgtm
/priority important-soon

/assign @thockin

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve
