### PR TITLE
Fix the wrong localhost seccomp path of CRI

### LINKED ISSUE #55359: Dockershim doesn't consider seccomp profile root?
While auditing absolute/relative path behavior in the Kubelet, I came across this: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/helpers_linux.go#L61-L66

```
	if !strings.HasPrefix(seccompProfile, "localhost/") {
		return nil, fmt.Errorf("unknown seccomp profile option: %s", seccompProfile)
	}

	fname := strings.TrimPrefix(seccompProfile, "localhost/") // by pod annotation validation, name is a valid subpath
	file, err := ioutil.ReadFile(filepath.FromSlash(fname))
```

It looks like it just ignores the root directory altogether, and reads relative to the Kubelet's CWD.

/cc @tallclair @yujuhong @feiskyer

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:

Fix the wrong seccomp path comment.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #55359

**Special notes for your reviewer**:

**Release note**:

```release-note
Fix CRI localhost seccomp path in format localhost//profileRoot/profileName.
```

### CODE REVIEW

File: pkg/kubelet/dockershim/helpers_linux.go [hunk 1]
```diff
@@ -62,7 +62,8 @@ func getSeccompDockerOpts(seccompProfile string) ([]dockerOpt, error) {
 		return nil, fmt.Errorf("unknown seccomp profile option: %s", seccompProfile)
 	}
 
-	fname := strings.TrimPrefix(seccompProfile, "localhost/") // by pod annotation validation, name is a valid subpath
+	// get the full path of seccomp profile when prefixed with 'localhost/'.
+	fname := strings.TrimPrefix(seccompProfile, "localhost/")
```
Comment (mtaufen) [inline pkg/kubelet/dockershim/helpers_linux.go]: Not sure you end up with an absolute path here. `TrimPrefix` will cut the `/` too, and you're left with a path that has no leading `/`. From what I can tell, `filepath.FromSlash` does not add a leading `/`. https://play.golang.org/p/_A6DBoSG1V

Comment (feiskyer) [reply pkg/kubelet/dockershim/helpers_linux.go]: @mtaufen yep, it doesn't add a leading '/'. And there are indeed issues about seccomp path.

`localhost/` is missing because of following code:
https://github.com/kubernetes/kubernetes/blob/72a2b0be6959191587470616148afdf2235b04ef/pkg/kubelet/kuberuntime/helpers.go#L278-L282

will add a new commit to fix this.

**Comment by feiskyer** [comment]
@yujuhong @mtaufen Added a new commit to fix CRI localhost seccomp path in format `localhost//profileRoot/profileName`.

File: pkg/kubelet/dockershim/helpers_linux.go [hunk 2]
```diff
@@ -62,7 +62,8 @@ func getSeccompDockerOpts(seccompProfile string) ([]dockerOpt, error) {
...
 	file, err := ioutil.ReadFile(filepath.FromSlash(fname))
```
Comment (mtaufen) [inline pkg/kubelet/dockershim/helpers_linux.go]: Can we also add validation that `fname` is absolute, and return an error if it is not?

Comment (mtaufen) [reply pkg/kubelet/dockershim/helpers_linux.go]: something like this
```
import "path/filepath"
if !filepath.IsAbs(fname) {
    return nil, fmt.Errorf("seccomp profile path must be absolute, but got relative path %q", fname)
}
```

Comment (feiskyer) [reply pkg/kubelet/dockershim/helpers_linux.go]: @mtaufen Good catch. Will add.

**Comment by feiskyer** [comment]
ping @mtaufen  @dchen1107 Could you take a look at this PR?

File: pkg/kubelet/dockershim/helpers_linux_test.go [hunk 3]
```diff
@@ -55,26 +58,26 @@ func TestGetSeccompSecurityOpts(t *testing.T) {
 }
 
 func TestLoadSeccompLocalhostProfiles(t *testing.T) {
+	tmpdir, err := ioutil.TempDir("", "seccomp-local-profile-test")
+	assert.NoError(t, err)
```
Comment (mtaufen) [inline pkg/kubelet/dockershim/helpers_linux_test.go]: shouldn't this be a fatal error?
FYI style guide recommends against assert helpers for exactly this reason, they make it easy to write imprecise tests

File: pkg/kubelet/dockershim/helpers_linux_test.go [hunk 4]
```diff
@@ -55,26 +58,26 @@ func TestGetSeccompSecurityOpts(t *testing.T) {
...
+	defer os.RemoveAll(tmpdir)
+	testProfile := `{"foo": "bar"}`
+	err = ioutil.WriteFile(filepath.Join(tmpdir, "test"), []byte(testProfile), 0644)
+	assert.NoError(t, err)
```
Comment (mtaufen) [inline pkg/kubelet/dockershim/helpers_linux_test.go]: shouldn't this be a fatal error?
FYI style guide recommends against assert helpers for exactly this reason, they make it easy to write imprecise tests

File: pkg/kubelet/dockershim/helpers_linux_test.go [hunk 5]
```diff
@@ -55,26 +58,26 @@ func TestGetSeccompSecurityOpts(t *testing.T) {
...
 		expectErr:      false,
-	}, {
-		msg:            "Seccomp localhost/sub/subtest profile",
-		seccompProfile: "localhost/fixtures/seccomp/sub/subtest",
-		expectedOpts:   []string{`seccomp={"abc":"def"}`},
-		expectErr:      false,
 	}, {
 		msg:            "Seccomp non-existent",
-		seccompProfile: "localhost/fixtures/seccomp/non-existent",
+		seccompProfile: "localhost/" + filepath.Join(tmpdir, "fixtures/non-existent"),
```
Comment (mtaufen) [inline pkg/kubelet/dockershim/helpers_linux_test.go]: should have separate tests for does-not-exist and relative paths

File: pkg/kubelet/kuberuntime/helpers_test.go [hunk 6]
```diff
@@ -205,3 +207,100 @@ func TestGetImageUser(t *testing.T) {
 		assert.Equal(t, test.expectedImageUserValues.username, username, "TestCase[%d]", j)
 	}
 }
+
+func TestGetSeccompProfileFromAnnotations(t *testing.T) {
+	_, _, m, err := createTestRuntimeManager()
+	assert.NoError(t, err)
```
Comment (mtaufen) [inline pkg/kubelet/kuberuntime/helpers_test.go]: should this be fatal?

File: pkg/kubelet/kuberuntime/helpers_test.go [hunk 7]
```diff
@@ -205,3 +207,100 @@ func TestGetImageUser(t *testing.T) {
...
+
+	tests := []struct {
+		description     string
+		annotation      map[string]string
+		containerName   string
+		expectedProfile string
+	}{
+		{
+			description:     "no seccomp should return null",
```
Comment (mtaufen) [inline pkg/kubelet/kuberuntime/helpers_test.go]: Do you mean empty string, instead of "null"?

**Comment by yujuhong** [comment]
Do we have any documentation on seccomp + kubernetes, and what format is expected?

File: pkg/kubelet/dockershim/helpers_linux_test.go (hunk 3 above)
Comment (yujuhong) [reply pkg/kubelet/dockershim/helpers_linux_test.go]: I think the style guide recommends against useless error messages. In this case, you can still write
```go
require.NoError(t, err, "actual useful error message")
```
I personally don't think that's worse than
```go
if err != nil {
   t.Fatalf("actual useful error message: %s",  err)
}
```

Comment (mtaufen) [reply pkg/kubelet/dockershim/helpers_linux_test.go]: I don't have a very strong opinion on this. 
Some of the things assert libs do is very nice.
Probably the use of assert libs should be discussed in the community.
Until then, fine IMO if people do what they prefer.
Definitely not going to block this PR on it.

Comment (feiskyer) [reply pkg/kubelet/dockershim/helpers_linux_test.go]: @mtaufen thanks. I think both the `t.Fatal` and `assert.NoError` are accepted now in kubernetes. They are both existing in many packages.

**Comment by feiskyer** [comment]
> Do we have any documentation on seccomp + kubernetes, and what format is expected?

@yujuhong Seems not.  I think only [docker json format](https://docs.docker.com/engine/security/seccomp/) is refered now, and from the [design of seccomp feature](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/seccomp.md), the profile format is opaque to kubernetes.

> Since seccomp profile schemes may vary between container runtimes, we will treat the contents of profiles as opaque for now and avoid attempting to find a common way to describe them. It is up to the container runtime to be sensitive to the annotations proposed here and to interpret instructions about local profiles.

File: pkg/kubelet/dockershim/helpers_linux_test.go (hunk 5 above)
Comment (feiskyer) [reply pkg/kubelet/dockershim/helpers_linux_test.go]: ack

File: pkg/kubelet/kuberuntime/helpers_test.go (hunk 7 above)
Comment (feiskyer) [reply pkg/kubelet/kuberuntime/helpers_test.go]: yep, will change to empty string

**Comment by feiskyer** [comment]
@yujuhong @mtaufen  Addressed comments. PTAL

**Comment by yujuhong** [comment]
@feiskyer what's the expected format of the annotation value? Is it `localhost/<full path to profile>`, e.g., `localhost//foo/bar/profile`? Or is it `localhost/foo/bar/profile`?

**Comment by feiskyer** [comment]
@yujuhong The path in the kubernetes annotation is a relative path, and root directory is set by kubelet's `--seccomp-profile-root` option (default to `"/var/lib/kubelet/seccomp"`). We converted it to absolute path in CRI.

File: pkg/kubelet/dockershim/helpers_linux_test.go (hunk 3 above)
Comment (yujuhong) [reply pkg/kubelet/dockershim/helpers_linux_test.go]: s/assert/require

assert is not fatal and the test will continue.

File: pkg/kubelet/dockershim/helpers_linux_test.go (hunk 4 above)
Comment (yujuhong) [reply pkg/kubelet/dockershim/helpers_linux_test.go]: s/assert/require

File: pkg/kubelet/dockershim/helpers_linux_test.go [hunk 8]
```diff
@@ -55,26 +58,31 @@ func TestGetSeccompSecurityOpts(t *testing.T) {
...
+		msg:            "Seccomp localhost/test profile should return correct seccomp profiles",
+		seccompProfile: "localhost/" + filepath.Join(tmpdir, "test"),
 		expectedOpts:   []string{`seccomp={"foo":"bar"}`},
 		expectErr:      false,
 	}, {
-		msg:            "Seccomp localhost/sub/subtest profile",
-		seccompProfile: "localhost/fixtures/seccomp/sub/subtest",
-		expectedOpts:   []string{`seccomp={"abc":"def"}`},
-		expectErr:      false,
+		msg:            "Non-exist profile should return error",
```
Comment (yujuhong) [inline pkg/kubelet/dockershim/helpers_linux_test.go]: nit: s/Non-exist/Non-existent

File: pkg/kubelet/kuberuntime/helpers_test.go (hunk 6 above)
Comment (yujuhong) [reply pkg/kubelet/kuberuntime/helpers_test.go]: s/assert/require

**Comment by tallclair** [comment]
/unassign
defer to yuju & michael

File: pkg/kubelet/dockershim/helpers_linux_test.go (hunk 4 above)
Comment (feiskyer) [reply pkg/kubelet/dockershim/helpers_linux_test.go]: ack

File: pkg/kubelet/dockershim/helpers_linux_test.go (hunk 8 above)
Comment (feiskyer) [reply pkg/kubelet/dockershim/helpers_linux_test.go]: ack

**Comment by feiskyer** [comment]
@yujuhong Addressed comments. PTAL

**Comment by jberkus** [comment]
/priority critical-urgent

/remove-priority important-soon

adjusting priorities for code freeze
