### PR TITLE
scheduler: Add ctx param and error return to EnqueueExtensions.EventsToRegister()

### LINKED ISSUE #119323: scheduler: Add ctx param and error return to EnqueueExtensions.EventsToRegister()
### What would you like to be added?

The scheduling framework `EnqueueExtensions.EventsToRegister()` has recently been changed to return `[]ClusterEventWithHint` instead of `ClusterEvent[]`. Since we've broken API anyway, it seems fitting to add a ctx param and error return to it.

So, change

```
EventsToRegister() []ClusterEventWithHint
```

to

```
EventsToRegister(context.Context) ([]ClusterEventWithHint, error)
```

### context parameter

The primary motivation is to be able to use contextual values, such as [logging](https://github.com/kubernetes/kubernetes/pull/116884). This is particularly important in WebAssembly where tracing, debug or custom config can be passed contextually to the underlying runtime. `EventsToRegister()` is currently the only plugin extension widely used and missing context,

### error return

The primary motivation of this is to allow coherent behavior on error, or to prevent panics. It is true that a native scheduler plugin is unlikely to err or panic creating the list of functions. However, when implemented in WebAssembly, there could be errors invoking the function in the guest VM, and currently, we have to deal with these in an undefined fashion.

### PR DESCRIPTION
**Pull request by googs1025**
#### What type of PR is this?
/kind feature 
/kind cleanup

#### What this PR does / why we need it:
- add ctx param and error return to EnqueueExtensions.EventsToRegister()
    - example: https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/blob/main/scheduler/plugin/plugin.go#L152-L189 

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/119323

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
ACTION REQUIRED for custom scheduler plugin developers:
`EventsToRegister` in the `EnqueueExtensions` interface gets `ctx` in the parameters and `error` in the return values.
Please change your plugins' implementation accordingly.
```

```go
type EnqueueExtensions interface {
	Plugin
	// EventsToRegister returns a series of possible events that may cause a Pod
	// failed by this plugin schedulable. Each event has a callback function that
	// filters out events to reduce useless retry of Pod's scheduling.
	// The events will be registered when instantiating the internal scheduling queue,
	// and leveraged to build event handlers dynamically.
	// Note: the returned list needs to be static (not depend on configuration parameters);
	// otherwise it would lead to undefined behavior.
	//
	// Appropriate implementation of this function will make Pod's re-scheduling accurate and performant.
	EventsToRegister(context.Context) ([]ClusterEventWithHint, error)
}
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by sanposhiho** [comment]
/hold

The discussion has not yet concluded in the issue.

**Comment by googs1025** [comment]
> /hold
> 
> The discussion has not yet concluded in the issue.

OK, we can revise it again based on the final conclusion

**Comment by alculquicondor** [comment]
Don't wait for my review, but this needs a release note with `ACTION REQUIRED`

**Comment by googs1025** [comment]
> Don't wait for my review, but this needs a release note with `ACTION REQUIRED` for developers of scheduler plugins.

Got it. I modified the release-note on the PR. Is there anything else I need to do?

**Comment by sanposhiho** [comment]
/unhold

https://github.com/kubernetes/kubernetes/issues/119323#issuecomment-2231038566

**Comment by sanposhiho** [comment]
/release-note-edit
```release-note
ACTION REQUIRED for custom scheduler plugin developers:
`EventsToRegister` in the `EnqueueExtensions` interface gets `ctx` in the parameters and `error` in the return values.
Please change your plugins' implementation accordingly.
```

File: pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -379,10 +388,14 @@ var defaultQueueingHintFn = func(_ klog.Logger, _ *v1.Pod, _, _ interface{}) (fr
 	return framework.Queue, nil
 }
 
-func buildQueueingHintMap(es []framework.EnqueueExtensions) internalqueue.QueueingHintMap {
+func buildQueueingHintMap(ctx context.Context, es []framework.EnqueueExtensions) (internalqueue.QueueingHintMap, error) {
 	queueingHintMap := make(internalqueue.QueueingHintMap)
+	var allErrors []error
```
Comment (sanposhiho) [inline pkg/scheduler/scheduler.go:393]: nit: Let's just use a native `error` package

```go
	var returnErr error
	for _, e := range es {
		events, err := e.EventsToRegister(ctx)
		returnErr = errors.Join(returnErr, err)
```

File: pkg/scheduler/scheduler.go [hunk 2]
```diff
@@ -324,9 +325,17 @@ func New(ctx context.Context,
 
 	preEnqueuePluginMap := make(map[string][]framework.PreEnqueuePlugin)
 	queueingHintsPerProfile := make(internalqueue.QueueingHintMapPerProfile)
+	var allErrors []error
```
Comment (sanposhiho) [inline pkg/scheduler/scheduler.go:328]: ditto

File: pkg/scheduler/scheduler.go [hunk 3]
```diff
@@ -379,10 +388,14 @@ var defaultQueueingHintFn = func(_ klog.Logger, _ *v1.Pod, _, _ interface{}) (fr
 	return framework.Queue, nil
 }
 
-func buildQueueingHintMap(es []framework.EnqueueExtensions) internalqueue.QueueingHintMap {
+func buildQueueingHintMap(ctx context.Context, es []framework.EnqueueExtensions) (internalqueue.QueueingHintMap, error) {
```
Comment (sanposhiho) [inline pkg/scheduler/scheduler.go:391]: can you add one test case  to `Test_buildQueueingHintMap`, which an `EventsToRegister` returns error?

Comment (googs1025) [reply pkg/scheduler/scheduler.go:390]: done

File: pkg/scheduler/scheduler.go (hunk 2 above)
Comment (googs1025) [reply pkg/scheduler/scheduler.go]: done

File: pkg/scheduler/scheduler.go (hunk 1 above)
Comment (googs1025) [reply pkg/scheduler/scheduler.go]: done

File: pkg/scheduler/framework/interface.go [hunk 4]
```diff
@@ -379,7 +379,7 @@ type EnqueueExtensions interface {
 	// otherwise it would lead to undefined behavior.
 	//
 	// Appropriate implementation of this function will make Pod's re-scheduling accurate and performant.
-	EventsToRegister() []ClusterEventWithHint
+	EventsToRegister(context.Context) ([]ClusterEventWithHint, error)
```
Comment (sanposhiho) [inline pkg/scheduler/framework/interface.go:382]: 1. document what'll happen in case it returns errors.
2. eliminate a part: `needs to be static (not depend on configuration parameters)`. 
Rather, it should be OK that a plugin changes a behaviour based on configuration etc. NOT OK is a plugin changing a result after the scheduler starts (based on the cluster's state etc) because the scheduler evaluates it only once. @kubernetes/sig-scheduling-approvers Let me know if I'm missing something.

```go
	// When it returns an error, the scheduler fails to start.
	// Note: the returned list needs to be determined during a runtime,
	// and the scheduler only evaluates it once during start up.
	//
	// Appropriate implementation of this function will make Pod's re-scheduling accurate and performant.
	EventsToRegister(context.Context) ([]ClusterEventWithHint, error)
```

File: pkg/scheduler/scheduler_test.go [hunk 5]
```diff
@@ -1149,10 +1171,23 @@ func (*emptyEventPlugin) Filter(_ context.Context, _ *framework.CycleState, _ *v
 	return nil
 }
 
-func (pl *emptyEventPlugin) EventsToRegister() []framework.ClusterEventWithHint {
+func (pl *emptyEventPlugin) EventsToRegister(_ context.Context) ([]framework.ClusterEventWithHint, error) {
+	return nil, nil
+}
+
+// mockEventsToRegisterPlugin is a mock plugin that returns an error for EventsToRegister method
+type mockEventsToRegisterPlugin struct{}
```
Comment (sanposhiho) [inline pkg/scheduler/scheduler_test.go:1179]:
```suggestion
// errorEventsToRegisterPlugin is a mock plugin that returns an error for EventsToRegister method
type errorEventsToRegisterPlugin struct{}
```

File: pkg/scheduler/scheduler_test.go [hunk 6]
```diff
@@ -870,6 +876,19 @@ func Test_UnionedGVKs(t *testing.T) {
 				framework.StorageClass:          framework.All - framework.Delete,
 			},
 		},
+		{
+			name: "mock EventsToRegister plugin for test EventsToRegister method returns error",
```
Comment (sanposhiho) [inline pkg/scheduler/scheduler_test.go:880]:
```suggestion
			name: "one EventsToRegister returns an error",
```

File: pkg/scheduler/scheduler_test.go [hunk 7]
```diff
@@ -596,6 +597,7 @@ const (
 	fakeNode                       = "fakeNode"
 	fakePod                        = "fakePod"
 	emptyEventsToRegister          = "emptyEventsToRegister"
+	mockEventsToRegister           = "mockEventsToRegister"
```
Comment (sanposhiho) [inline pkg/scheduler/scheduler_test.go:600]:
```suggestion
	errorEventsToRegister           = "errorEventsToRegister"
```

File: pkg/scheduler/scheduler_test.go (hunk 6 above)
Comment (sanposhiho) [reply pkg/scheduler/scheduler_test.go:880]: And, can we move this error test scenario into `Test_buildQueueingHintMap` rather? 
`Test_UnionedGVKs` is a test focusing on UnionedGVKs, as the name tells.

File: pkg/scheduler/scheduler_test.go (hunk 7 above)
Comment (googs1025) [reply pkg/scheduler/scheduler_test.go]: done

File: pkg/scheduler/scheduler_test.go (hunk 6 above)
Comment (googs1025) [reply pkg/scheduler/scheduler_test.go]: oh, my bad. fixed

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

File: pkg/scheduler/scheduler_test.go [hunk 8]
```diff
@@ -738,7 +747,14 @@ func Test_buildQueueingHintMap(t *testing.T) {
...
 			})
 
-			got := buildQueueingHintMap(exts)
+			got, err := buildQueueingHintMap(ctx, exts)
+			if err != nil {
+				if tt.wantErr != nil {
+					cmp.Diff(tt.wantErr, err.Error())
+				} else {
+					t.Fatal(err)
+				}
```
Comment (sanposhiho) [inline pkg/scheduler/scheduler_test.go:756]: `cmp.Diff` doesn't do anything actually.

```suggestion
				if tt.wantErr != nil && tt.wantErr.Error() != err.Error() {
					t.Fatalf("unexpected error from buildQueueingHintMap: expected: %s, actual: %s, tt.wantErr, err)
				} 
				
				if  tt.wantErr == nil {
					t.Fatal("unexpected error from buildQueueingHintMap: %s, err)
				}
```

**Review by sanposhiho — COMMENTED** [review]
sorry, find another stuff at last minutes

**Comment by googs1025** [comment]
The ci test is a bit strange, the pull-kubernetes-kind-classic-dra test always fails. 
IMO, this pr should not involve this part of the change

```bash
Building node image ...
Building in container: kind-build-1721217145-2101744477
Image "dra/node:latest" build completed.
+ trap kind export logs "${ARTIFACTS}/kind"; kind delete cluster EXIT
+ kind create cluster --retain --config test/e2e/dra/kind-classic-dra.yaml --image dra/node:latest
ERROR: failed to create cluster: error reading file: open test/e2e/dra/kind-classic-dra.yaml: no such file or directory
+ kind export logs /logs/artifacts/kind
ERROR: unknown cluster "kind"
+ kind delete cluster
Deleting cluster "kind" ...
+ EXIT_VALUE=1
+ set +o xtrace
Cleaning up after docker in docker.
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/126113/pull-kubernetes-kind-classic-dra/1813537846141652992

**Comment by googs1025** [comment]
/assign @pohly /PTAL 
I found out this ci error from [here](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-kind-classic-dra) that it seems to be related to this [PR](https://github.com/kubernetes/kubernetes/pull/125488/files#diff-77efc70606713c5301a4f136e61d179dcbe7f20ef5cf822130aff33b59e3f3da).

**Comment by googs1025** [comment]
When I try to remove sig/node sig/storage, resubmitting PR still triggers

**Comment by googs1025** [comment]
@sanposhiho /PTAL Need /lgtm label to merge

When I try to remove sig/node sig/storage, resubmitting PR still triggers

**Comment by sanposhiho** [comment]
> The ci test is a bit strange, the pull-kubernetes-kind-classic-dra test always fails.


We can ignore it as it's not `Required` one.

File: pkg/scheduler/scheduler_test.go (hunk 8 above)
Comment (sanposhiho) [reply pkg/scheduler/scheduler_test.go:756]: @googs1025 you missed this.

**Comment by googs1025** [comment]
@sanposhiho need /lgtm tag thanks!

**Comment by sanposhiho** [comment]
@googs1025 https://github.com/kubernetes/kubernetes/pull/126113/files#r1680912531

File: pkg/scheduler/scheduler_test.go (hunk 8 above)
Comment (googs1025) [reply pkg/scheduler/scheduler_test.go]: fixed

**Comment by googs1025** [comment]
> @googs1025 https://github.com/kubernetes/kubernetes/pull/126113/files#r1680912531

done

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

**Comment by googs1025** [comment]
If a CI single test fails, will it not trigger automatic merging?

**Comment by sanposhiho** [comment]
We can ignore the dra one's failure. That's not required and this PR should be merged without that CI passes.

@pohly FYI for dra test failure. Looks like something goes wrong, not flaky.
> ERROR: failed to create cluster: error reading file: open test/e2e/dra/kind-classic-dra.yaml: no such file or directory
