### PR TITLE
kube-proxy avoid race condition using LocalModeNodeCIDR

### LINKED ISSUE #111321: kube-proxy in LocalModeNodeCIDR mode may cache stale Node.PodCIDR if the Node object is recreated
### What happened?

If `LocalModeNodeCIDR` is true, kube-proxy reads the `Node.PodCIDR` value and uses it to determine whether or not traffic is local to the Node.

In certain cases (e.g. when kube-proxy runs before the Node information has been completely updated), it is possible for kube-proxy to read and store a stale `PodCIDR` value. This will cause kube-proxy to route traffic incorrectly as the local traffic determination is no longer correct.

Note: PodCIDR is immutable once set but it is possible to delete and recreate the Node object to get into this state. (yes, this can happen)

/sig network

### What did you expect to happen?

kube-proxy should detect this state and reconfigure/restart with the newly updated `PodCIDR`.

### How can we reproduce it (as minimally and precisely as possible)?

Recreate the Node object with a different PodCIDR after kube-proxy has started on the Node.

### Kubernetes version

Impacts all current versions that support `LocalModeNodeCIDR`

### Cloud provider

<details>
Observed for GCE preemptible/spot VMs, but is a generic problem.
</details>

### PR DESCRIPTION
**Pull request by aojea**
Since kube-proxy in LocalModeNodeCIDR needs to obtain the PodCIDR assigned to the node it watches for the Node object.

However, kube-proxy startup process requires to have these watches in different places, that opens the possibility of having a race condition if the same node is recreated and a different PodCIDR is assigned.

Initializing the second watch with the value obtained in the first one allows us to detect this situation.
Fixes https://github.com/kubernetes/kubernetes/issues/111321

/kind bug

```release-note
fix a race condition in kube-proxy when using LocalModeNodeCIDR to avoid dropping Services traffic if the object node is recreated when kube-proxy is starting
```

### CODE REVIEW

**Comment by aojea** [comment]
/assign @danwinship @thockin 

Alternative to https://github.com/kubernetes/kubernetes/pull/118458

**Comment by aojea** [comment]
/retest
Kubernetes e2e suite: [It] [sig-node] Pods should run through the lifecycle of Pods and PodStatus [Conformance] expand_less

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by aojea** [comment]
/hold cancel

two eyes 👀  should be fair

Thanks

File: cmd/kube-proxy/app/server.go [hunk 1]
```diff
@@ -754,7 +756,7 @@ func (s *ProxyServer) Run() error {
 	nodeConfig := config.NewNodeConfig(currentNodeInformerFactory.Core().V1().Nodes(), s.Config.ConfigSyncPeriod.Duration)
 	// https://issues.k8s.io/111321
 	if s.Config.DetectLocalMode == kubeproxyconfig.LocalModeNodeCIDR {
-		nodeConfig.RegisterEventHandler(&proxy.NodePodCIDRHandler{})
+		nodeConfig.RegisterEventHandler(proxy.NewNodePodCIDRHandler(s.podCIDRs))
```
Comment (skmatti) [inline cmd/kube-proxy/app/server.go:759]: Does ProxyServer.Run() called always after ProxyServer.createProxier?. If the order is revered, then node controller might get initialized with nil podCIDRs?

Comment (aojea) [reply cmd/kube-proxy/app/server.go:759]: yeah, good question, the order is like that https://github.com/kubernetes/kubernetes/issues/111321#issuecomment-1568345649 

the problem is that we have a bit of a chaos right, we  do api queries on initialisation and configuration steps, and we end with these problems 🤷

Comment (skmatti) [reply cmd/kube-proxy/app/server.go:759]: Thanks for confirming @aojea
