### PR TITLE
provide active pods to cgroup cleanup

### LINKED ISSUE #42431: ci-kubernetes-node-kubelet broken since 16:00pm PST yesterday  (03/01)
https://k8s-testgrid.appspot.com/sq-blocking#node-kubelet
Only one green run out of the past 11 runs. 

Potential offenders:
https://github.com/kubernetes/kubernetes/compare/bce0718...5c168e2

/cc @kubernetes/sig-node-bugs 
@derekwaynecarr @smarterclayton @ncdc (saw you guys discussed this on sig-node slack)

### PR DESCRIPTION
**Pull request by derekwaynecarr**
**What this PR does / why we need it**:
This PR provides more information for when a pod cgroup is considered orphaned.  The running pods cache is based on the runtime's view of the world.  we create pod cgroups before containers so we should just be looking at activePods.

**Which issue this PR fixes**
Fixes https://github.com/kubernetes/kubernetes/issues/42431

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
opening this for the moment, but i think this should help the referenced flake.

**Comment by derekwaynecarr** [comment]
fyi @sjenning

**Comment by derekwaynecarr** [comment]
i need to send an update to this PR to probably not look at runningPods at all.

**Comment by vishh** [comment]
This is an interesting bug.

**Comment by vishh** [comment]
Running pods is confusing and we should probably not have that exposed within the kubelet object at all.
Ping once your get rid of using `Running Pods`. Otherwise this LGTM

**Comment by dashpole** [comment]
When implementing this for volumes, I found the best way to get the set of running pods is to get all pods from kl.podManager, and then check each pod's status from the status manger to see if they are terminated, which is what this PR does.  So this LGTM!

**Comment by dashpole** [comment]
Yeah, @vishh I am not even sure we need to use runningPods here.  But for the purpose of fixing flakes, this looks like the correct change.

**Comment by derekwaynecarr** [comment]
@vishh @dashpole -- updated.

**Comment by derekwaynecarr** [comment]
given the potential for flakes here, this should probably be a p0.

**Comment by vishh** [comment]
Should we bump the PR priority?

**Comment by dashpole** [comment]
We probably should.  Do we know if flakes related to this bug are blocking the SQ?  We may need to contact sq oncall to get this merged if the sq is blocked because of kubelet-node flakes related to this.

**Comment by derekwaynecarr** [comment]
i am not aware of anything blocking, but i can imagine this caused flakes depending on relationship between HandlePodCleanups and runtime cache skew.

**Comment by dashpole** [comment]
https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/

I thought we decided that "pod ran to completion" errors were likely due to this bug?  That is what the most recent flake was...

**Comment by derekwaynecarr** [comment]
i would like to see a green run before any merging of course.

**Comment by dashpole** [comment]
I wonder if runningPods is needed to handle static pods correctly?  Regardless, I would suggest leaving runningPods in for now, and we can figure out how to safely remove it later.

**Comment by yujuhong** [comment]
RunningPods were there just for some global cleanup tasks that (needs to know what containers are running but) usually are not latency sensitive, and would benefit from not hitting docker so frequently. For pod cgroup cleanup, you don't need this one.

**Comment by yujuhong** [comment]
> RunningPods were there just for some global cleanup tasks that (needs to know what containers are running but) usually are not latency sensitive, and would benefit from not hitting docker so frequently. For pod cgroup cleanup, you don't need this one.

To be clear, runningPods are the containers that are currently running on node. It doesn't represent what should be running on the node, and it could change anytime (since other components of kubelet can create containers) in parallel. I agree it could use a better name...

**Comment by derekwaynecarr** [comment]
debugging what is going on with the builds...

**Comment by derekwaynecarr** [comment]
@k8s-bot test this

**Comment by dashpole** [comment]
Looking at a couple kubelet logs, it seems like there is a bug with this.  I see about 100 `(pod_uid) is terminated, but pod cgroup sandbox has not been cleaned up` messages every 10 seconds.

**Comment by derekwaynecarr** [comment]
@dashpole -- yeah, i am not sure what is happening, i see no problem testing it locally.

**Comment by dashpole** [comment]
running locally now... ill see if i get a repro

**Comment by derekwaynecarr** [comment]
is heapster static pod?

**Comment by derekwaynecarr** [comment]
if so that would explain... testing static pods now as well

**Comment by dashpole** [comment]
This just failed for me locally.
`make test-e2e-node REMOTE=true DELETE_INSTANCES=true PARALLELISM=1 SKIP="" TEST_ARGS='--feature-gates=DynamicKubeletConfig=true' FOCUS="SimpleMount" RUN_UNTIL_FAILURE=false &> build-log.txt`

It reminds me of a problem I ran into with volume cleanup.
We say that a pod is "terminated" if it has `status == failed` or `status == succeeded`. However, RestartAlways containers will never reach this state.  So some pods can never be deleted if we are only allowed to delete it when it is "terminated".

See [what I did for volumes](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L141)

**Comment by derekwaynecarr** [comment]
i am confused why even a hack/local-up-cluster is not showing this same symptom both w/ and w/o static pods.

**Comment by derekwaynecarr** [comment]
hmm, i was testing a Restart=Never pod

**Comment by Random-Liu** [comment]
One concern about this PR. It seems that cgroup cleanup logic will only look at active pods with this PR.

However, when a pod is evicted, IIRC, it will be marked as `Failed` immediately. However, containers may still be running, and cgroups may got removed when containers are still running.

Is this a problem?

@derekwaynecarr @yujuhong @dashpole @vishh /cc @kubernetes/sig-node-bugs

**Comment by derekwaynecarr** [comment]
@Random-Liu -- its not quite right, we look at cgroupfs first to determine state.  activePods is then compared against cgroupfs to find the cgroups that should not exist.

**Comment by derekwaynecarr** [comment]
even if evicted, we still would want the cgroup force killed.

**Comment by vishh** [comment]
@Random-Liu @derekwaynecarr Pod cgroup deletion will fail if containers are still around. Cgroupfs will ensure that since `rmdir pod-cgroup` is expected to fail.

**Comment by vishh** [comment]
> is heapster static pod?

Nope. Heapster is a cluster service.

**Comment by Random-Liu** [comment]
> @Random-Liu -- its not quite right, we look at cgroupfs first to determine state. activePods is then compared against cgroupfs to find the cgroups that should not exist.
> even if evicted, we still would want the cgroup force killed.

@derekwaynecarr I don't quite what you said.

Pod to be evicted will be marked as `Failed` immediately
=> It will not be included in `activePods` even though containers are not killed yet
=> When you compare cgroupfs against active pods, you will not see the pod.
=> You will cleanup the cgroup of that pod even though there are still containers running.
=> These containers will be moved to the parent cgroups.

Will this cause any problem? If not, it should be fine.

**Comment by Random-Liu** [comment]
> Cgroupfs will ensure that since rmdir pod-cgroup is expected to fail.

I see. Then that makes sense to me.

**Comment by vishh** [comment]
@yujuhong 

> To be clear, runningPods are the containers that are currently running on node. It doesn't represent what should be running on the node, and it could change anytime (since other components of kubelet can create containers) in parallel. I agree it could use a better name...

Could this information be maintained in a separate module so that it is not exposed to the kubelet object?

**Comment by vishh** [comment]
https://github.com/kubernetes/kubernetes/pull/42585#issuecomment-284532732 makes sense. 

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L680 does not filter out pods that have been deleted, but have not reached a terminal state

**Comment by derekwaynecarr** [comment]
odd, so i was not able to repro w/ busybox running sleep, but i can repro w/ nginx.

will integrate @dashpole comment to see if that was the cause.  thanks.

**Comment by dashpole** [comment]
SimpleMount e2e_node test passed for me with the latest PR (and it failed before).

File: pkg/kubelet/kubelet_pods.go [hunk 1]
```diff
@@ -687,11 +687,7 @@ func (kl *Kubelet) podIsTerminated(pod *v1.Pod) bool {
 		// restarted.
 		status = pod.Status
 	}
-	if status.Phase == v1.PodFailed || status.Phase == v1.PodSucceeded {
-		return true
-	}
-
-	return false
+	return status.Phase == v1.PodFailed || status.Phase == v1.PodSucceeded || (pod.DeletionTimestamp != nil && notRunning(status.ContainerStatuses))
```
Comment (vishh) [inline pkg/kubelet/kubelet_pods.go]: @dashpole can we cleanup the volume code to use this active pod lister method instead? Not necessary for this PR

**Comment by derekwaynecarr** [comment]
Having one function for termination filtering is preferred

File: pkg/kubelet/kubelet_pods.go (hunk 1 above)
Comment (dashpole) [inline pkg/kubelet/kubelet_pods.go]: yes.  Nothing would give me more joy :)

**Comment by derekwaynecarr** [comment]
@k8s-bot gce etcd3 e2e test this
@k8s-bot gci gce e2e test this

**Comment by dashpole** [comment]
The GCI GCE failure is known: #42597

**Comment by dashpole** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by derekwaynecarr** [comment]
bot didnt apply tag from https://github.com/kubernetes/kubernetes/pull/42585#issuecomment-284567578 so I am applying to get this critical fix in queue.

File: pkg/kubelet/kubelet_pods.go (hunk 1 above)
Comment (yujuhong) [inline pkg/kubelet/kubelet_pods.go]: @derekwaynecarr your change to `podIsTerminated` may cause other race conditions (e.g., pod worker still trying to start new containers). Could you remove this? 

/cc @Random-Liu @dchen1107

Comment (dashpole) [inline pkg/kubelet/kubelet_pods.go]: This shouldn't have any effects during pod startup, as this change only makes a difference when the deletion timestamp is set.  I agree that we should do a more thorough review of what effects this could have, though.  In general, I think this is a better definition of podIsTerminated, as a pod that has been deleted, and has no containers running is definitely in a terminal state.
