### PR TITLE
Initial implementation of kube-dump.sh

### LINKED ISSUE #3500: Add dump command to kubectl
When a user report an issue on Kubernetes, we normally ask them to provide some outputs by running kubectl commands, such as kubectl get <resource>, kubectl describe <resource> etc. We ask for daemons' log from various nodes often. Sometimes the user has to reproduce the issue for us because the config is changed. Meanwhile the developer might spend a lot of time on debugging the issues on a deprecated version or mismatched client with server. 

I propose to add a dump command to kubectl, which collects related outputs, logs, from various components or related nodes, then generate a tarball and attach that to the issue.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Script which dumps state of Kubernetes cluster for debugging. Tested on GCE only. This is initial attempt to fix #3500.

### CODE REVIEW

**Comment by roberthbailey** [comment]
Assigning to @filbranden since he's likely to have some bash-style comments.

File: hack/kube-dump.sh [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+source "${KUBE_ROOT}/cluster/kube-env.sh"
+source "${KUBE_ROOT}/cluster/${KUBERNETES_PROVIDER}/util.sh"
+
+detect-project &> /dev/null
+
+echo "kube-dump.sh: Getting docker statuses on all nodes..."
+ALL_NODES=(${MINION_NAMES[*]} ${MASTER_NAME})
+for NODE in ${ALL_NODES[*]}; do 
+  echo "kube-dump.sh: Node $NODE:"
+  ssh-to-node $NODE '
```
Comment (filbranden) [inline hack/kube-dump.sh]: Double quotes:

```shell
  ssh-to-node "${node}" ' ...
```

File: hack/kube-dump.sh [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+    sudo docker ps -a
+    sudo docker images
+  '
+done
+echo
+
+echo "kube-dump.sh: Getting boundpods from etcd..."
+ssh-to-node $MASTER_NAME '
```
Comment (filbranden) [inline hack/kube-dump.sh]: Double quotes and also recommend always using `${...}` around variable names.

```shell
ssh-to-node "${MASTER_NAME}" ' ...

File: hack/kube-dump.sh [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+  ETCD_SERVER=`hostname -i`:4001
```
Comment (filbranden) [inline hack/kube-dump.sh]: Use `$(...)` syntax instead of backticks.

```
  ETCD_SERVER=$(hostname -i):4001
  for dir in $(etcdctl -C "${ETCD_SERVER}" ls /registry/nodes); do
    echo "kube-dump.sh: Dir ${dir}:"
    etcdctl -C "${ETCD_SERVER}" get "${dir}/boundpods"
  done
```

Also, do you need to connect to `$(hostname -i)`? Can't you just connect to `localhost` instead?

File: hack/kube-dump.sh [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
+# This script dumps debugging state of currently running Kubernetes cluster.
+
+KUBE_ROOT=$(dirname "${BASH_SOURCE}")/..
+
+echo "kube-dump.sh: Getting version..."
+${KUBE_ROOT}/cluster/kubectl.sh version
```
Comment (filbranden) [inline hack/kube-dump.sh]: Double quotes:

```shell
"${KUBE_ROOT}/cluster/kubectl.sh" version
```

File: hack/kube-dump.sh [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+echo
+
+echo "kube-dump.sh: Getting resources..."
+${KUBE_ROOT}/cluster/kubectl.sh get nodes,pods,rc,services,events -o json
```
Comment (filbranden) [inline hack/kube-dump.sh]: Same here.

**Comment by filbranden** [comment]
A few comments, looks good otherwise.

File: hack/kube-dump.sh (hunk 1 above)
Comment (jszczepkowski) [inline hack/kube-dump.sh]: Done.

File: hack/kube-dump.sh (hunk 2 above)
Comment (jszczepkowski) [inline hack/kube-dump.sh]: Done.

File: hack/kube-dump.sh (hunk 3 above)
Comment (jszczepkowski) [inline hack/kube-dump.sh]: I need hostname -i, etcdctl doesn't work with localhost.

File: hack/kube-dump.sh (hunk 4 above)
Comment (jszczepkowski) [inline hack/kube-dump.sh]: Done.

File: hack/kube-dump.sh (hunk 5 above)
Comment (jszczepkowski) [inline hack/kube-dump.sh]: Done.

**Comment by filbranden** [comment]
Looks good. May I ask you to squash your commits into a single one before the merge? (You can do that with `git rebase -i`). Thanks!

**Comment by jszczepkowski** [comment]
Done.
