### PR TITLE
kube-scheduler: fix empty lastTransitionTime in pod condition

### LINKED ISSUE #122164: PodScheduled lastTransitionTime null after scheduling gate removal
### What happened?

When a scheduling gated pod is ungated, the `PodScheduled` condition's `lastTransitionTime` is consistently null until the pod is scheduled:

```
"conditions": [
    {
        "lastProbeTime": null,
        "lastTransitionTime": null,
        "message": "0/5 nodes <elided>",
        "reason": "Unschedulable",
        "status": "False",
        "type": "PodScheduled"
    }
]
```

### What did you expect to happen?

Pods without a scheduling gate have the same `PodScheduled` condition but  `lastTransitionTime` is populated:

```
"conditions": [
    {
        "lastProbeTime": null,
        "lastTransitionTime": "2023-12-04T01:48:32Z",
        "message": "0/4 nodes <elided>",
        "reason": "Unschedulable",
        "status": "False",
        "type": "PodScheduled"
    }
]
```

### How can we reproduce it (as minimally and precisely as possible)?

Submit a pod with a scheduling gate. Observe that after removal of the gate, the `PodScheduled` pod condition.

### Anything else we need to know?

I uncovered this while using Kueue and the ProvisioningRequest feature. Since this is reproducible with just the scheduling gate, I think k/k is the right project for the issue.

### Kubernetes version

<details>

```console
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.3-gke.1203000", GitCommit:"28396c07d85d0131e4f94369f78a7dee01ca1e0c", GitTreeState:"clean", BuildDate:"2023-10-26T09:28:34Z", GoVersion:"go1.20.10 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
GCP
</details>

### OS version

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by lianghao208**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix null lastTransitionTime in pod condition when setting scheduling gate

#### Which issue(s) this PR fixes:

Fixes #122164

#### Does this PR introduce a user-facing change?

```release-note
Fix null lastTransitionTime in Pod condition when setting scheduling gate.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/registry/core/pod/strategy_test.go [hunk 1]
```diff
@@ -371,7 +371,10 @@ func TestWaitingForGatesCondition(t *testing.T) {
 				}
 			}
 
-			if diff := cmp.Diff(tt.want, got); diff != "" {
+			if got.LastTransitionTime.IsZero() && got.Type != "" {
```
Comment (alculquicondor) [inline pkg/registry/core/pod/strategy_test.go:374]: more like this:
```
if got.Type == "" {
  t.Errorf("Scheduled condition not found")
} else {
  check lastTransitionTimestamp
  check diff
}
```

Comment (lianghao208) [reply pkg/registry/core/pod/strategy_test.go:374]: In the former test cases `pod without .spec.schedulingGates` or `pod with feature disabled`, the `got.Type` will always be empty string as expected, no need to error out.
Only when got.Type is not empty, which indicates pod with .spec.schedulingGates and gate feature enabled, we need to check if lastTransitionTimestamp is null.

Comment (alculquicondor) [reply pkg/registry/core/pod/strategy_test.go:374]: ah, gotcha

/approve
/lgtm
/hold cancel

Comment (lianghao208) [reply pkg/registry/core/pod/strategy_test.go:374]: #122651 done

Comment (lianghao208) [reply pkg/registry/core/pod/strategy_test.go:374]: @alculquicondor I guess the /approve label was not added unless you send it directly on comment instead of review comment.

Comment (kerthcet) [reply pkg/registry/core/pod/strategy_test.go:374]: Strange, why this needs sig node approvers, I thought it's sig-apis.

**Comment by lianghao208** [comment]
@bart0sh I don't think this is related to sig node, are you able to remove the sig node label? Thanks.

**Comment by alculquicondor** [comment]
Please add a release note.

**Comment by alculquicondor** [comment]
/sig node

The OWNER of the package is clearly sig-node

**Comment by lianghao208** [comment]
> Please add a release note.

@alculquicondor This bug fix doesn't introduce any user-facing changes, is a release note still needed?

**Comment by AxeZhan** [comment]
> @alculquicondor This bug fix doesn't introduce any user-facing changes, is a release note still needed?

Although there're no api changes, pod condition after scheduling gate removed will change after this pr, and can be noticed by user. So I'm +1 with aldo for a release note.

**Comment by lianghao208** [comment]
> Although there're no api changes, pod condition after scheduling gate removed will change after this pr, and can be noticed by user. So I'm +1 with aldo for a release note.

@AxeZhan I see, release note added.

**Comment by lianghao208** [comment]
@sjenning Hi, can you move this forward? It needs a approval from sig node, thanks!

**Comment by lianghao208** [comment]
/assign @sjenning @dims @mrunalp 
For approval.
This PR has been submitted for a while, thanks for reviewing this.

**Comment by lianghao208** [comment]
To clarify, the OWNER of the pkg/registry/core/pod package is sig-node, even though this bug occured from scheduler, it still needs sig-node reviewers' approval.
@sjenning @dims @mrunalp
