### PR TITLE
Modified subpath configmap mount fails when container restarts

### LINKED ISSUE #68211: modified subpath configmap mount fails when container restarts
/kind bug

**What happened**:
When a container uses a configmap which is mounted with the `subPath` option, the configmap is changed and then the container (but not the pod) restarts the mounting of the configmap fails:

```
# mount a single file into a folder with preexisting data
        volumeMounts:
        - name: extra-cfg
          mountPath: /etc/puppetlabs/puppetdb/conf.d/extra.ini
          subPath: extra.ini
```

    # change something in the configmap
    kubectl edit extra-cfg
    kubectl exec podname kill 1
    kubectl describe podname

>   Warning  Failed   5s                kubelet, kworker-be-intg-iz2-bap006  Error: failed to start container "puppetdb": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/b9ffd644-af98-11e8-a05e-246e96748774/volume-subpaths/extra-cfg/puppetdb/2\\\" to rootfs \\\"/var/lib/docker/overlay2/c8790b7f3f690c1ef7a582672e2d153062ff6b4ed1ee21aab1158897310fd3d1/merged\\\" at \\\"/var/lib/docker/overlay2/c8790b7f3f690c1ef7a582672e2d153062ff6b4ed1ee21aab1158897310fd3d1/merged/etc/puppetlabs/puppetdb/conf.d/extra.ini\\\" caused \\\"no such file or directory\\\"\"": unknown

(The pod this happens on consists of multiple containers, I have not tested yet if it also happens in a single container pod.)

One has to delete the pod to fix the problem.

**Environment**:
  Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

coreos 1800.7.0
docker 18.03.1

### PR DESCRIPTION
**Pull request by fatedier**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
When a container uses a configmap which is mounted with the subPath option, the configmap is changed and then the container (but not the pod) restarts the mounting of the configmap fails.

Since #82784 is not active and not rebased, i submit this PR to continue this work or someone can provide another solution?

**Which issue(s) this PR fixes**:
Fixes #68211

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Fix an issue with container restarts using a modified configmap or secret subpath volume mount.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by fatedier** [comment]
The test case ` Variable Expansion should not change the subpath mount on a container restart if the environment variable changes` failed with this change.

It seems that `SubPathExpr` rely on this to ensure subpath mount not changed on a container restart. I'm not sure if it's appropriate.

**Comment by msau42** [comment]
> It seems that `SubPathExpr` rely on this to ensure subpath mount not changed on a container restart. I'm not sure if it's appropriate.

I'm open to changing that behavior to be consistent with configmap/secret update behavior. cc @jsafrane @kevtaylor for thoughts. I think the only consideration is that it's a conformance test so we would have to intentionally break it. There's probably a process for it.

**Comment by kevtaylor** [comment]
So the idea was always to preserve the original file mount when the container might fail and not restart on a new host location. If someone did alter the environment value in between you could consider this is quite an edge case and potentially intentional change, so relaxing it doesn't seem drastic.

**Comment by msau42** [comment]
/assign @johnbelamaric 
for conformance test question. Basically, this test case was enforcing a bit of a corner case to begin with. I can't think of a strong reason why we would want this current behavior, especially as we see this behavior as problematic for other volume types (not part of conformance atm)

**Comment by jsafrane** [comment]
I think I understand what's going on and this PR will fix it. I don't see issues in un-mounting stuff in `prepareSubpathTarget`. I am not sure about fixing the conformance tests though.

**Comment by johnbelamaric** [comment]
I agree that behavior does not need to be part of conformance. Presumably you'll update the e2e to test the new behavior. Let's leave that out of conformance and just leave it as a regular e2e.

File: test/e2e/storage/subpath.go [hunk 1]
```diff
@@ -125,5 +125,33 @@ var _ = utils.SIGDescribe("Subpath", func() {
 			}, privilegedSecurityContext)
 			testsuites.TestBasicSubpath(f, "configmap-value", pod)
 		})
+
+	})
+
+	ginkgo.Context("Pod restart", func() {
```
Comment (msau42) [inline test/e2e/storage/subpath.go:131]: nit: probably call this "container restart"

File: test/e2e/storage/subpath.go [hunk 2]
```diff
@@ -125,5 +125,33 @@ var _ = utils.SIGDescribe("Subpath", func() {
...
+
+		ginkgo.It("should verify that pod can restart successfully after configmaps changed", func() {
+			pod := testsuites.SubpathTestPod(f, "configmap-key", "configmap", &v1.VolumeSource{ConfigMap: &v1.ConfigMapVolumeSource{LocalObjectReference: v1.LocalObjectReference{Name: "my-configmap-to-modify"}}}, privilegedSecurityContext)
+			testsuites.SetInitCommandToTouchProbeFile(pod)
+			configmapModified := &v1.ConfigMap{ObjectMeta: metav1.ObjectMeta{Name: "my-configmap-to-modify"}, Data: map[string]string{"configmap-key": "configmap-modified-value"}}
+			testsuites.TestPodContainerRestart(f, pod, func() error {
+				if _, err := f.ClientSet.CoreV1().ConfigMaps(f.Namespace.Name).Update(context.TODO(), configmapModified, metav1.UpdateOptions{}); err != nil {
+					return err
+				}
+				time.Sleep(10 * time.Second)
```
Comment (msau42) [inline test/e2e/storage/subpath.go:152]: Since kubelet updates the configmap periodically, this has the potential to not be updated by the time the container restarts. Maybe a more reliable method would be to restart the container repeatedly until the modified data is detected?

**Comment by fatedier** [comment]
@msau42 I have updated the test case. Can you look at it when you have time?

**Comment by msau42** [comment]
/lgtm
/approve

Thank you! Can you also add a release note, that this fixes an issue with container restarts using a modified configmap or secret subpath volume mount?

**Comment by msau42** [comment]
/assign @johnbelamaric 
for removal of conformance test

**Comment by verult** [comment]
The e2e test started to flake: https://github.com/kubernetes/kubernetes/issues/100194

File: pkg/volume/util/subpath/subpath_linux.go [hunk 3]
```diff
@@ -108,9 +109,21 @@ func prepareSubpathTarget(mounter mount.Interface, subpath Subpath) (bool, strin
...
 	if !notMount {
-		// It's already mounted
-		klog.V(5).Infof("Skipping bind-mounting subpath %s: already mounted", bindPathTarget)
-		return true, bindPathTarget, nil
+		linuxHostUtil := hostutil.NewHostUtil()
+		mntInfo, err := linuxHostUtil.FindMountInfo(bindPathTarget)
+		if err != nil {
+			return false, "", fmt.Errorf("error calling findMountInfo for %s: %s", bindPathTarget, err)
+		}
+		if mntInfo.Root != subpath.Path {
```
Comment (silenceper) [inline pkg/volume/util/subpath/subpath_linux.go:117]: in my env, `/proc/self/mountinfo` like this , 
```
523 47 253:16 /kubelet/pods/d166411c-ea15-11eb-abc8-525400f80eae/volumes/kubernetes.io~configmap/extra-cfg/..2021_07_21_11_21_39.969349293/extra.ini /data/kubelet/pods/d166411c-ea15-11eb-abc8-525400f80eae/volume-subpaths/extra-cfg/test/0 rw,noatime shared:29 - xfs /dev/vdb rw,attr2,inode64,prjquota
```
mntInfo.Root is `/kubelet/pods/d166411c-ea15-11eb-abc8-525400f80eae/volumes/kubernetes.io~configmap/extra-cfg/..2021_07_21_11_21_39.969349293/extra.ini` 

is always not equal `subpath.Path`  because miss `/data` prefix.   

```
/dev/vdb       1000G   11G  989G   2% /data
```

Comment (silenceper) [reply pkg/volume/util/subpath/subpath_linux.go:117]: @fatedier 
I tested it and it is true. If kubelet mounts an extra data disk, it will cause the missing prefix of `mntInfo.Root`
