### PR TITLE
Fixing vSphere Volume plugin bugs

### LINKED ISSUE #26646: vSphere volume plugin bugs
- Scanning device after the hot attach of disk fails 
- Couldn't match device ID with UUID returned from AttachDisk()
- Unmount fails because of \040 for space encoding in mount path after datastore name
- DetachDisk() has to take volumePath(unique identifier) instead of diskID
- Scoping of err variable in AddDevice() call causes attachDisk() to fail later at mount instead of immediate failure
-  Volume attach disk with a non-existent caught as a failure at mount rather than attach

Fixed in #26658

### PR DESCRIPTION
**Pull request by abithap**
This PR fixes #26646 and targeted for 1.3

### CODE REVIEW

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 1]
```diff
@@ -567,7 +568,7 @@ func (vs *VSphere) AttachDisk(vmDiskPath string, nodeName string) (diskID string
 	// Attach disk to the VM
 	err = vm.AddDevice(ctx, disk)
 	if err != nil {
-		glog.V(3).Infof("Cannot add disk to the vm - %v", err)
+		glog.V(3).Infof("Cannot attach disk to the vm - %v", err)
```
Comment (pmorie) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: nit: log messages should start with lowercase.

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 2]
```diff
@@ -611,13 +612,30 @@ func getVirtualDiskUUID(newDevice types.BaseVirtualDevice) (string, error) {
 
 	if b, ok := vd.Backing.(*types.VirtualDiskFlatVer2BackingInfo); ok {
 		uuidWithNoHypens := strings.Replace(b.Uuid, "-", "", -1)
-		return uuidWithNoHypens, nil
+		uuidLowerCase := strings.ToLower(uuidWithNoHypens)
```
Comment (pmorie) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: You can just do `return strings.ToLower(uuidWithNoHyphens)`

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 3]
```diff
@@ -611,13 +612,30 @@ func getVirtualDiskUUID(newDevice types.BaseVirtualDevice) (string, error) {
...
 	}
 	return "", ErrNoDiskUUIDFound
 }
 
+func getVirtualDiskID(volPath string, vmDevices object.VirtualDeviceList) (string, error) {
+	for _, device := range vmDevices {
+		d := device.GetVirtualDevice()
+
+		if vmDevices.TypeName(device) == "VirtualDisk" {
+			if b, ok := d.Backing.(*types.VirtualDiskFlatVer2BackingInfo); ok && b.Parent != nil {
```
Comment (pmorie) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: It would be helpful for those not familiar w/ the vsphere API to say exactly what is being tested here.

File: pkg/volume/vsphere_volume/vsphere_volume.go [hunk 4]
```diff
@@ -280,7 +281,9 @@ func (v *vsphereVolumeUnmounter) TearDownAt(dir string) error {
 		return fmt.Errorf("directory %s is not mounted", dir)
 	}
 
-	v.volPath = path.Base(refs[0])
+	//replacing the \040 encoding with space
```
Comment (pmorie) [inline pkg/volume/vsphere_volume/vsphere_volume.go]: @abithap 

It's not clear to me where the space is being introduced (I read the comment in the issue you opened for this as well).  Could you elaborate?

File: pkg/volume/vsphere_volume/vsphere_volume_util.go [hunk 5]
```diff
@@ -123,18 +130,63 @@ func verifyDevicePath(diskUUID string) string {
 }
 
 func probeAttachedVolume() error {
-	executor := exec.New()
-	args := []string{"trigger"}
-	cmd := executor.Command("/usr/bin/udevadm", args...)
-	_, err := cmd.CombinedOutput()
+	var scsiPath = "/sys/class/scsi_host/"
+	var b bytes.Buffer
```
Comment (pmorie) [inline pkg/volume/vsphere_volume/vsphere_volume_util.go]: nit: suggest the block style for var here:

```go
var (
  scsiPath = "/sys/class/scsi_host"
  b,c bytes.Butter
  driverTypes = "mpt"
  scanVal = []byte("- - -")
)
```

File: pkg/volume/vsphere_volume/vsphere_volume_util.go [hunk 6]
```diff
@@ -123,18 +130,63 @@ func verifyDevicePath(diskUUID string) string {
 }
 
 func probeAttachedVolume() error {
```
Comment (pmorie) [inline pkg/volume/vsphere_volume/vsphere_volume_util.go]: Please add some doc comment here explaining what's going on for people not familiar w/ vsphere -- are brief description is OK.  Why does this method need to write out a file?

File: pkg/cloudprovider/providers/vsphere/vsphere.go (hunk 1 above)
Comment (abithap) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: fixed in the upcoming patch

File: pkg/cloudprovider/providers/vsphere/vsphere.go (hunk 2 above)
Comment (abithap) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: fixed in the upcoming patch

File: pkg/volume/vsphere_volume/vsphere_volume.go (hunk 4 above)
Comment (abithap) [inline pkg/volume/vsphere_volume/vsphere_volume.go]: volumePath eg: "[local] xxx.vmdk" provided to attach/mount has a space between [local] and vmdk name and it is encoded as \040 when returned by GetMountRefs(). Due to that unmount fails to match the given volume path. So we need to explicitly replace it to make it work.

File: pkg/volume/vsphere_volume/vsphere_volume_util.go [hunk 7]
```diff
@@ -123,18 +130,63 @@ func verifyDevicePath(diskUUID string) string {
...
-		glog.Errorf("error running udevadm trigger %v\n", err)
-		return err
+		glog.V(2).Infof("Error scanning attached vSphere volumes: %v", err)
+		return ErrProbeVolume
+	}
+	for _, file := range files {
+		b.WriteString(scsiPath)
+		b.WriteString(file.Name())
+		b.WriteString("/proc_name")
+		driverFile := b.String()
```
Comment (rootfs) [inline pkg/volume/vsphere_volume/vsphere_volume_util.go]: `WriteString` has error return that shouldn't be ignored. 
Why not `driverFile := scsiPath + file.Name() + "/proc_name"`? And same to `scanFile`?

File: pkg/volume/vsphere_volume/vsphere_volume_util.go [hunk 8]
```diff
@@ -123,18 +130,63 @@ func verifyDevicePath(diskUUID string) string {
...
+
+		// grep for 'mpt' in 'proc_name'
```
Comment (rootfs) [inline pkg/volume/vsphere_volume/vsphere_volume_util.go]: - Why udev trigger stop working?
- Is there any vSphere doc pointing to why only `mpt` is in `proc_name`?

File: pkg/volume/vsphere_volume/vsphere_volume_util.go [hunk 9]
```diff
@@ -123,18 +130,63 @@ func verifyDevicePath(diskUUID string) string {
...
+			c.Reset()
+		}
+		b.Reset()
 	}
+
 	glog.V(4).Infof("Successfully probed all attachments")
 	return nil
 }
 
+func grepFile(file string, pat []byte) int64 {
```
Comment (rootfs) [inline pkg/volume/vsphere_volume/vsphere_volume_util.go]: use regex

**Comment by rootfs** [comment]
@abithap Is it still WIP? What does it take to be complete?

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 10]
```diff
@@ -611,13 +612,30 @@ func getVirtualDiskUUID(newDevice types.BaseVirtualDevice) (string, error) {
...
-		return uuidWithNoHypens, nil
+		uuidLowerCase := strings.ToLower(uuidWithNoHypens)
+		return uuidLowerCase, nil
 	}
 	return "", ErrNoDiskUUIDFound
 }
 
+func getVirtualDiskID(volPath string, vmDevices object.VirtualDeviceList) (string, error) {
+	for _, device := range vmDevices {
+		d := device.GetVirtualDevice()
```
Comment (dagnello) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: this can be moved inside the if statement below

**Comment by abithap** [comment]
@rootfs I have marked it WIP because , after rebasing the code with the k8s master cloud provider is not getting initialized properly. Do you have any idea if there has been a change in config/initialization that went in that affects this?

File: pkg/volume/vsphere_volume/vsphere_volume_util.go (hunk 5 above)
Comment (abithap) [inline pkg/volume/vsphere_volume/vsphere_volume_util.go]: fixed in the upcoming patch

File: pkg/volume/vsphere_volume/vsphere_volume_util.go (hunk 7 above)
Comment (abithap) [inline pkg/volume/vsphere_volume/vsphere_volume_util.go]: fixed it

File: pkg/cloudprovider/providers/vsphere/vsphere.go (hunk 10 above)
Comment (abithap) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: done

**Comment by rootfs** [comment]
@abithap i don't run vsphere. What did you see in api-server and kubelet log? Do you have proper credentials set on the master and host?

File: pkg/volume/vsphere_volume/vsphere_volume_util.go (hunk 8 above)
Comment (abithap) [inline pkg/volume/vsphere_volume/vsphere_volume_util.go]: sometimes udev trigger wasn't scanning the devices attached.It was failing intermittently and volume mount failed with that. so I have to do this scan to get the uuid of attached devices.

**Comment by abithap** [comment]
@rootfs @pmorie made the changes , please take a look and let me know if there is something else to update.Thanks

File: pkg/volume/vsphere_volume/vsphere_volume_util.go [hunk 11]
```diff
@@ -122,19 +129,57 @@ func verifyDevicePath(diskUUID string) string {
...
 
+// scans storage devices and adds path in dev/disk/by-id
 func probeAttachedVolume() error {
-	executor := exec.New()
-	args := []string{"trigger"}
-	cmd := executor.Command("/usr/bin/udevadm", args...)
-	_, err := cmd.CombinedOutput()
+	var (
+		scsiPath   = "/sys/class/scsi_host/"
+		driverType = "mpt"
```
Comment (rootfs) [inline pkg/volume/vsphere_volume/vsphere_volume_util.go]: I am not sure if this works for VMs that use scsi controller other than LSI. Have you tested that? If it is not an easy fix, please make a note somewhere.

File: pkg/volume/vsphere_volume/vsphere_volume_util.go [hunk 12]
```diff
@@ -122,19 +129,57 @@ func verifyDevicePath(diskUUID string) string {
...
-		glog.Errorf("error running udevadm trigger %v\n", err)
-		return err
+		glog.V(2).Infof("Error scanning attached vSphere volumes: %v", err)
+		return ErrProbeVolume
+	}
+	for _, file := range files {
+		driverFile := scsiPath + file.Name() + "/proc_name"
+
+		// grep for 'mpt' in 'proc_name'
+		if total := grepFile(driverFile, []byte(driverType)); total != 0 {
```
Comment (rootfs) [inline pkg/volume/vsphere_volume/vsphere_volume_util.go]: another thought, what if you just scan all scsi bus as we did for fibre channel [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/fc/fc_util.go#L108)

**Comment by rootfs** [comment]
@abithap some comments. rest look to me.

File: pkg/volume/vsphere_volume/vsphere_volume_util.go (hunk 11 above)
Comment (abithap) [inline pkg/volume/vsphere_volume/vsphere_volume_util.go]: vSphere VMs uses LSI as default one , but I didn't get a chance to test it on other vms yet.

File: pkg/volume/vsphere_volume/vsphere_volume_util.go (hunk 12 above)
Comment (abithap) [inline pkg/volume/vsphere_volume/vsphere_volume_util.go]: @rootfs I tried to use the scsiHostRescan() that you pointed , it worked in the first attach disk scenario but the subsequent attach failed to rescan. the only difference is for first time it created a new scsi controller and attached a disk. Do you have any idea why its failing in the other cases?

Comment (abithap) [inline pkg/volume/vsphere_volume/vsphere_volume_util.go]: @roots never mind the above question. looks like my environment was in a weird state. It works fine now.

**Comment by abithap** [comment]
@rootfs addressed the comments and tested, works fine now. Please take a look. thanks

**Comment by rootfs** [comment]
LGTM 
@pmorie ?

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 13]
```diff
@@ -437,7 +438,7 @@ func (vs *VSphere) GetZone() (cloudprovider.Zone, error) {
 
 // Routes returns an implementation of Routes for vSphere.
```
Comment (pmorie) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: Can you add a comment with what the return value represents?

**Comment by pmorie** [comment]
@abithap I was wrong re: log messages.  AFAIK, they're fine to have begin with uppercase.  Sorry for the churn about that, but I wanted to come clean.  Feel free to change.

File: pkg/volume/vsphere_volume/vsphere_volume.go (hunk 4 above)
Comment (pmorie) [inline pkg/volume/vsphere_volume/vsphere_volume.go]: thanks -- can you put that information into a comment in the code?

**Comment by pmorie** [comment]
LGTM modulo a couple nits, fix up and I'll tag.  I'd love to see an E2E for vsphere sometime in a follow-up.

File: pkg/cloudprovider/providers/vsphere/vsphere.go (hunk 13 above)
Comment (abithap) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: done

File: pkg/volume/vsphere_volume/vsphere_volume.go (hunk 4 above)
Comment (abithap) [inline pkg/volume/vsphere_volume/vsphere_volume.go]: done

**Comment by abithap** [comment]
@pmorie addressed the comments. I will try to add the e2e for vSphere in future. thanks

File: pkg/volume/vsphere_volume/vsphere_volume.go [hunk 14]
```diff
@@ -280,7 +281,11 @@ func (v *vsphereVolumeUnmounter) TearDownAt(dir string) error {
 		return fmt.Errorf("directory %s is not mounted", dir)
 	}
 
-	v.volPath = path.Base(refs[0])
+	// space between datastore and vmdk name in volumePath is encoded as '\040' when returned by GetMountRefs().
+	// volumePath eg: "[local] xxx.vmdk" provided to attach/mount
+	// replacing \040 with space to match the actual volumePath
+	mountPath := strings.Replace(path.Base(refs[0]), "\\040", " ", -1)
```
Comment (pmorie) [inline pkg/volume/vsphere_volume/vsphere_volume.go]: Thanks a lot for adding this.

File: pkg/cloudprovider/providers/vsphere/vsphere.go [hunk 15]
```diff
@@ -642,13 +658,19 @@ func (vs *VSphere) DetachDisk(diskID string, nodeName string) error {
 		return err
 	}
 
+	diskID, err := getVirtualDiskID(volPath, vmDevices)
+	if err != nil {
+		glog.V(2).Infof("disk ID not found for %v ", volPath)
```
Comment (pmorie) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: This should be Warning instead of Info, don't you think?

File: pkg/volume/vsphere_volume/vsphere_volume_util.go [hunk 16]
```diff
@@ -122,18 +135,7 @@ func verifyDevicePath(diskUUID string) string {
...
-	cmd := executor.Command("/usr/bin/udevadm", args...)
-	_, err := cmd.CombinedOutput()
-	if err != nil {
-		glog.Errorf("error running udevadm trigger %v\n", err)
-		return err
-	}
-	glog.V(4).Infof("Successfully probed all attachments")
-	return nil
-}
+// scans storage devices and adds path in dev/disk/by-id
```
Comment (pmorie) [inline pkg/volume/vsphere_volume/vsphere_volume_util.go]: Not sure what this comment is relative to -- `verifyDevicePath`, perhaps?

**Comment by pmorie** [comment]
@abithap Just a couple more questions -- LGTM otherwise.

File: pkg/cloudprovider/providers/vsphere/vsphere.go (hunk 15 above)
Comment (abithap) [inline pkg/cloudprovider/providers/vsphere/vsphere.go]: changed it

File: pkg/volume/vsphere_volume/vsphere_volume_util.go (hunk 16 above)
Comment (abithap) [inline pkg/volume/vsphere_volume/vsphere_volume_util.go]: missed to remove it. fixed now

**Comment by goltermann** [comment]
@k8s-bot e2e test this issue: #IGNORE

**Comment by goltermann** [comment]
@k8s-bot e2e test this issue: #26210
