### PR TITLE
kubectl show node role if defined

### LINKED ISSUE #50010: kubectl does not show node role
/kind bug

**What happened**:
`kubectl get nodes` doesn't show role
```
kubectl get nodes -o wide
NAME                                           STATUS    AGE       VERSION   EXTERNAL-IP      OS-IMAGE                      KERNEL-VERSION
ip-172-20-101-111.eu-west-1.compute.internal   Ready     23h       v1.7.0    X.X.X.X          Debian GNU/Linux 8 (jessie)   4.4.65-k8s
ip-172-20-101-122.eu-west-1.compute.internal   Ready     23h       v1.7.0    X.X.X.X          Debian GNU/Linux 8 (jessie)   4.4.65-k8s
ip-172-20-48-148.eu-west-1.compute.internal    Ready     23h       v1.7.0    X.X.X.X          Debian GNU/Linux 8 (jessie)   4.4.65-k8s
ip-172-20-63-150.eu-west-1.compute.internal    Ready     23h       v1.7.0    X.X.X.X          Debian GNU/Linux 8 (jessie)   4.4.65-k8s
ip-172-20-68-226.eu-west-1.compute.internal    Ready     23h       v1.7.0    X.X.X.X          Debian GNU/Linux 8 (jessie)   4.4.65-k8s
ip-172-20-79-207.eu-west-1.compute.internal    Ready     23h       v1.7.0    X.X.X.X          Debian GNU/Linux 8 (jessie)   4.4.65-k8s
```

Workaround:
```
kubectl get nodes --selector=kubernetes.io/role=master
NAME                                           STATUS    AGE       VERSION
ip-172-20-101-122.eu-west-1.compute.internal   Ready     23h       v1.7.0
ip-172-20-48-148.eu-west-1.compute.internal    Ready     23h       v1.7.0
ip-172-20-79-207.eu-west-1.compute.internal    Ready     23h       v1.7.0

kubectl get nodes --selector=kubernetes.io/role=node
NAME                                           STATUS    AGE       VERSION
ip-172-20-101-111.eu-west-1.compute.internal   Ready     23h       v1.7.0
ip-172-20-63-150.eu-west-1.compute.internal    Ready     23h       v1.7.0
ip-172-20-68-226.eu-west-1.compute.internal    Ready     23h       v1.7.0
```
**What you expected to happen**:
According to #35901 and https://github.com/heptio/aws-quickstart/issues/61
```
kubectl get nodes
NAME                                           STATUS           AGE       VERSION
ip-172-20-101-111.eu-west-1.compute.internal   Ready,node       23h       v1.7.0
ip-172-20-101-122.eu-west-1.compute.internal   Ready,master     23h       v1.7.0
ip-172-20-48-148.eu-west-1.compute.internal    Ready,master     23h       v1.7.0
ip-172-20-63-150.eu-west-1.compute.internal    Ready,node       23h       v1.7.0
ip-172-20-68-226.eu-west-1.compute.internal    Ready,node       23h       v1.7.0
ip-172-20-79-207.eu-west-1.compute.internal    Ready,master     23h       v1.7.0
```

**How to reproduce it (as minimally and precisely as possible)**:
I just deployed a multi master kubernetes environment with kops:
```
kops create cluster --target terraform --name example.com --zones eu-west-1a,eu-west-1b,eu-west-1c --master-zones eu-west-1a,eu-west-1b,eu-west-1c --master-size t2.micro --node-size t2.micro --node-count 3
cd out/terraform
terraform apply
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
kubectl version --short
Client Version: v1.7.2
Server Version: v1.7.0
```
- Cloud provider or hardware configuration: AWS
- Install tools: kops, terraform

### PR DESCRIPTION
**Pull request by dixudx**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50010

**Special notes for your reviewer**:
/assign @justinsb @luxas @jbeda @philips
/cc @qrevel

**Release note**:

```release-note
kubectl show node role if defined
```

### CODE REVIEW

**Comment by dixudx** [comment]
@justinsb @philips @jbeda PTAL. Thanks.

**Comment by timothysc** [comment]
I can not approve this, someone from /cc @kubernetes/sig-cli-pr-reviews needs to

File: pkg/printers/internalversion/printers.go [hunk 1]
```diff
@@ -1176,6 +1181,20 @@ func printNode(obj *api.Node, options printers.PrintOptions) ([]metav1alpha1.Tab
 	return []metav1alpha1.TableRow{row}, nil
 }
 
+// findNodeRole returns the role of a given node, or "" if none found.
+// The role is determined by looking in order for:
+// * a node-role.kubernetes.io/master label
+// * a kubernetes.io/role label
+func findNodeRole(node *api.Node) string {
+	if _, ok := node.Labels[constants.LabelNodeRoleMaster]; ok {
+		return "master"
```
Comment (shiywang) [inline pkg/printers/internalversion/printers.go]: "Master"

File: pkg/printers/internalversion/printers_test.go [hunk 2]
```diff
@@ -825,6 +825,18 @@ func TestPrintNodeStatus(t *testing.T) {
 			},
 			status: "Unknown,SchedulingDisabled",
 		},
+		{
+			node: api.Node{
+				ObjectMeta: metav1.ObjectMeta{Name: "foo10", Labels: map[string]string{"node-role.kubernetes.io/master": "", "kubernetes.io/role": "node"}},
+			},
+			status: "Unknown,master",
```
Comment (shiywang) [inline pkg/printers/internalversion/printers_test.go]: Unknown,Master

File: pkg/printers/internalversion/printers_test.go [hunk 3]
```diff
@@ -825,6 +825,18 @@ func TestPrintNodeStatus(t *testing.T) {
...
+		},
+		{
+			node: api.Node{
+				ObjectMeta: metav1.ObjectMeta{Name: "foo11", Labels: map[string]string{"kubernetes.io/role": "node"}},
+			},
+			status: "Unknown,node",
```
Comment (shiywang) [inline pkg/printers/internalversion/printers_test.go]: Unknown,Node

**Comment by shiywang** [comment]
@kubernetes/sig-cli-maintainers

File: pkg/printers/internalversion/printers.go (hunk 1 above)
Comment (dixudx) [inline pkg/printers/internalversion/printers.go]: @shiywang Done. PTAL. Thanks.

**Comment by shiywang** [comment]
/lgtm
ping @kubernetes/sig-cli-maintainers  for approval

**Comment by dixudx** [comment]
ping @jbeda Need your approval. Thanks.

File: pkg/printers/internalversion/printers.go [hunk 4]
```diff
@@ -41,6 +41,7 @@ import (
 	"k8s.io/apimachinery/pkg/labels"
 	"k8s.io/apimachinery/pkg/runtime"
 	"k8s.io/apimachinery/pkg/util/sets"
+	"k8s.io/kubernetes/cmd/kubeadm/app/constants"
```
Comment (luxas) [inline pkg/printers/internalversion/printers.go]: This must not happen. Nothing in `pkg/` should depend on `cmd/kubeadm`
We must store the constant elsewhere, like https://github.com/kubernetes/kubernetes/pull/39112 tries to do
cc @jbeda @justinsb @philips

**Review by luxas — CHANGES_REQUESTED** [review]

File: pkg/printers/internalversion/printers.go (hunk 4 above)
Comment (justinsb) [inline pkg/printers/internalversion/printers.go]: This is a very painful user-facing regression.  Fixing the user-facing regression should take priority over package-bickering.

I agree it's not a good place for it, but by putting it somewhere where everyone can agree it shouldn't be then we're more likely to get a faster resolution, and it's less likely to end up just staying where it is :-)

Comment (sttts) [inline pkg/printers/internalversion/printers.go]: It is one constant. Copy it and put a comment where it is from. Otherwise this postpones the work of fixing the dependencies to later and delgates it to somebody else. Neither is good.

**Comment by dixudx** [comment]
@luxas @justinsb @sttts Updated. PTAL. Thanks.

File: pkg/printers/internalversion/printers.go (hunk 4 above)
Comment (justinsb) [inline pkg/printers/internalversion/printers.go]: That works :-)

**Comment by justinsb** [comment]
/lgtm

@shiywang do you want to approve?

**Comment by dixudx** [comment]
ping @justinsb @luxas @shiywang @sttts 
Rebase and revised since #49129 has been merged. PTAL. Thanks.

File: pkg/printers/internalversion/printers.go [hunk 5]
```diff
@@ -41,7 +41,6 @@ import (
 	"k8s.io/apimachinery/pkg/labels"
 	"k8s.io/apimachinery/pkg/runtime"
 	"k8s.io/apimachinery/pkg/util/sets"
-	"k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm"
```
Comment (dixudx) [inline pkg/printers/internalversion/printers.go]: @luxas @sttts @justinsb `cmd/kubeadm/app/apis/kubeadm/well_known_labels.go` is not used/referenced. Shall we delete this `well_known_labels.go` file?

Comment (justinsb) [inline pkg/printers/internalversion/printers.go]: Let's not do that - that is how the regression happened in the first place!  Let's get this all fixed up first...

Comment (justinsb) [inline pkg/printers/internalversion/printers.go]: Also, that's where - for better or worse - we decided to store the node role labels.  There was some corruption during the move, but we should fix it up from this point i.e. add the labels that were removed, put it into a `pkg` directory if we don't want to reference a `cmd` directory

File: pkg/printers/internalversion/printers.go [hunk 6]
```diff
@@ -60,7 +59,20 @@ import (
 	"k8s.io/kubernetes/pkg/util/node"
 )
 
-const loadBalancerWidth = 16
+const (
+	loadBalancerWidth = 16
+
+	// LabelNodeRoleMaster specifies that a node is a master
+	// It's copied over to here until it's merged in core: https://github.com/kubernetes/kubernetes/pull/39112
```
Comment (alexandercampbell) [inline pkg/printers/internalversion/printers.go]: Is this a TODO? If so, I would reference this pull request (#50438) and specify exactly what has to happen for the TODO to be executed.

File: pkg/printers/internalversion/printers.go [hunk 7]
```diff
@@ -1193,14 +1205,19 @@ func getNodeExternalIP(node *api.Node) string {
...
-	if role := node.Labels[kubeadm.NodeLabelKubeadmAlphaRole]; role != "" {
-		return role
+	if _, ok := node.Labels[LabelNodeRoleMaster]; ok {
+		return "Master"
+	}
+	if role := node.Labels[NodeLabelRole]; role != "" {
+		return strings.Title(role)
+	}
+	if role := node.Labels[NodeLabelKubeadmAlphaRole]; role != "" {
+		return strings.Title(role)
```
Comment (alexandercampbell) [inline pkg/printers/internalversion/printers.go]: Why `strings.Title`?

File: pkg/printers/internalversion/printers_test.go [hunk 8]
```diff
@@ -828,12 +828,30 @@ func TestPrintNodeStatus(t *testing.T) {
 		{
 			node: api.Node{
 				ObjectMeta: metav1.ObjectMeta{
+					Name:   "foo10",
+					Labels: map[string]string{"node-role.kubernetes.io/master": "", "kubernetes.io/role": "node", "kubeadm.alpha.kubernetes.io/role": "node"},
```
Comment (alexandercampbell) [inline pkg/printers/internalversion/printers_test.go]: Does specifying `["node-role.kubernetes.io/master"] = ""` mean the Node is a master? If so, why is the string left blank? I would expect to see "true" or similar.

File: pkg/printers/internalversion/printers.go (hunk 7 above)
Comment (dixudx) [inline pkg/printers/internalversion/printers.go]: @alexandercampbell To make first letter of words uppercase, such as "node" -> "Node".

File: pkg/printers/internalversion/printers.go (hunk 6 above)
Comment (dixudx) [inline pkg/printers/internalversion/printers.go]: Just copy from `cmd/kubeadm/app/apis/kubeadm/well_known_labels.go`. We should not use `cmd` packages in `pkg`.

File: pkg/printers/internalversion/printers_test.go (hunk 8 above)
Comment (dixudx) [inline pkg/printers/internalversion/printers_test.go]: I have the same confusion. PTAL [markmaster_test.go#L52](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/markmaster/markmaster_test.go#L52). Such annotation is not the only one.

I just follow this convention here.

File: pkg/printers/internalversion/printers.go (hunk 6 above)
Comment (smarterclayton) [inline pkg/printers/internalversion/printers.go]: Yes, pkgs in `cmd` can never be referenced from `pkg`.  @deads2k we should make sure there is an import rule for this.

File: pkg/printers/internalversion/printers_test.go (hunk 8 above)
Comment (justinsb) [inline pkg/printers/internalversion/printers_test.go]: You can have empty labels, and the value doesn't matter here ("reserved for future usage" perhaps?)

**Comment by justinsb** [comment]
/lgtm

@shiywang do you want to approve?

File: pkg/printers/internalversion/printers.go [hunk 9]
```diff
@@ -60,7 +59,20 @@ import (
 	"k8s.io/kubernetes/pkg/util/node"
 )
 
-const loadBalancerWidth = 16
+const (
+	loadBalancerWidth = 16
+
+	// LabelNodeRoleMaster specifies that a node is a master
+	// It's copied over to here until it's merged in core: https://github.com/kubernetes/kubernetes/pull/39112
+	LabelNodeRoleMaster = "node-role.kubernetes.io/master"
```
Comment (thockin) [inline pkg/printers/internalversion/printers.go]: Is there a doc somewhere else that clarifies why a boolean "is master" label (a valueless key) is better than the enum-ish "role" label below?

Comment (thockin) [inline pkg/printers/internalversion/printers.go]: I haven't been part of the discussion here, so I assume it has happened and I just need a catch-up.  why is this not a taint?  I don't like the idea of explicit roles, especially in a self-hosted world.  The "master" might be spread around the cluster.

Comment (luxas) [inline pkg/printers/internalversion/printers.go]: @philips @jbeda  ^

@thockin has been discussed in various forums, can see if I can dig something up; but basically it gives us the possibility to eventually easily support multiple well-known roles _for the same node_.
i.e. can be both master (`"node-role.kubernetes.io/master"`) and whatever else we might come up with.

Comment (thockin) [inline pkg/printers/internalversion/printers.go]: I just scanned #39112 - is it right to move ahead with this priority order while that is left unresolved?

**Comment by luxas** [comment]
So to clarify this:
 - `"kubeadm.alpha.kubernetes.io/role"` has been deprecated for _a long_ time and I'll remove it right after this PR merges. It is included here purely for the revert-style behavior of this PR
 - `"kubernetes.io/role"` was prior art, but allowed for only one role/node, which was stated insufficient, so
 - `"node-role.kubernetes.io/master"` is current best practice, and most deployments are using it now. This allows for multiple roles/node and has an empty value.

cc @kubernetes/sig-cluster-lifecycle-pr-reviews

File: pkg/printers/internalversion/printers.go (hunk 9 above)
Comment (luxas) [inline pkg/printers/internalversion/printers.go]: @thockin It's also used as a taint :)

Comment (justinsb) [inline pkg/printers/internalversion/printers.go]: Afaik a taint alone cannot guarantee that a pod ends up on a master node. So this is both the label and the taint. 39112 has been agreed, although we probably need the steering committee to get it merged.

As for delaying this further, this fixes a regression in kubectl where it does not identify the master. It is an annoying regression, having hit it in the real world.

File: pkg/printers/internalversion/printers.go [hunk 10]
```diff
@@ -1193,14 +1205,19 @@ func getNodeExternalIP(node *api.Node) string {
 
 // findNodeRole returns the role of a given node, or "" if none found.
 // The role is determined by looking in order for:
+// * a node-role.kubernetes.io/master label
 // * a kubernetes.io/role label
 // * a kubeadm.alpha.kubernetes.io/role label
-// If no role is found, ("", nil) is returned
 func findNodeRole(node *api.Node) string {
```
Comment (liggitt) [inline pkg/printers/internalversion/printers.go]: this seems like exactly the sort of special-casing we should not do, given the discussion in https://github.com/kubernetes/kubernetes/pull/39112 about nodes being able to have multiple roles. Wasn't the purpose of the selected label pattern to allow arbitrary roles, and multiple roles per node?

File: pkg/printers/internalversion/printers.go (hunk 9 above)
Comment (liggitt) [inline pkg/printers/internalversion/printers.go]: I thought the agreement was on a pattern for role labels, not special-casing one or two roles in kubectl, etc

File: pkg/printers/internalversion/printers.go (hunk 10 above)
Comment (justinsb) [inline pkg/printers/internalversion/printers.go]: I think you're right, but I think here we're still undoing the bad PRs that got us to this regression.

File: pkg/printers/internalversion/printers.go [hunk 11]
```diff
@@ -60,7 +59,20 @@ import (
...
+	// LabelNodeRoleMaster specifies that a node is a master
+	// It's copied over to here until it's merged in core: https://github.com/kubernetes/kubernetes/pull/39112
+	LabelNodeRoleMaster = "node-role.kubernetes.io/master"
+
+	// NodeLabelRole specifies the role of a node
+	NodeLabelRole = "kubernetes.io/role"
+
+	// NodeLabelKubeadmAlphaRole is a label that kubeadm applies to a Node as a hint that it has a particular purpose.
+	// Use of NodeLabelRole is preferred.
+	NodeLabelKubeadmAlphaRole = "kubeadm.alpha.kubernetes.io/role"
```
Comment (liggitt) [inline pkg/printers/internalversion/printers.go]: this is inverting the relationship between kubectl/apiserver and kubeadm... our printers don't special-case display of kubeadm labels

Comment (liggitt) [inline pkg/printers/internalversion/printers.go]: > "kubeadm.alpha.kubernetes.io/role" has been deprecated for a long time and I'll remove it right after this PR merges. It is included here purely for the revert-style behavior of this PR

let's not reintroduce it in this PR, then

Comment (liggitt) [inline pkg/printers/internalversion/printers.go]: opened #51173 as a follow-up

**Comment by Miyurz** [comment]
Which kubectl version will have this fix ? I don't see any in label yet.

**Comment by dixudx** [comment]
@Miyurz This fix and related #51173 have been merged into branch `v1.8.0-beta.0` and `v1.8.0-beta.1`. Will be released in `v1.8`.
