### PR TITLE
Clarify reconcile command documentation

### LINKED ISSUE #71185: `kubectl auth reconcile` auto-creates namespaces
**What happened**:

I noticed some surprising behavior of `kubectl auth reconcile`, which I'm not sure is intentional, but is very unexpected, in that `kubectl auth reconcile` will auto-create namespaces if it doesn't exist. This behavior does not seem to be documented anywhere.

For example, if I run:
```
kubectl auth reconcile --namespace my-namespace -f /tmp/my-role.yaml
```
against the following Role:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-role
rules:
- apiGroups:
  - ""
  resources:
  - pod
  verbs:
  - list
```

Then the namespace `my-namespace` gets created. This is confirmed when enabling logs in kubectl:

```
I1118 03:11:38.222982   89185 round_trippers.go:405] GET https://REDACTED/apis/rbac.authorization.k8s.io/v1/namespaces/my-namespace/roles/my-role 404 Not Found in 32 milliseconds
I1118 03:11:38.261152   89185 round_trippers.go:405] POST https://REDACTED/api/v1/namespaces 201 Created in 37 milliseconds
I1118 03:11:38.304245   89185 round_trippers.go:405] POST https://REDACTED/apis/rbac.authorization.k8s.io/v1/namespaces/my-namespace/roles 201 Created in 40 milliseconds
role.rbac.authorization.k8s.io/my-role reconciled
```

**What you expected to happen**:

`kubectl auth reconcile` is described in the CLI description as "preferred to 'apply' for RBAC resources so that proper rule coverage checks are done."

However, this cannot be used as a drop-in replacement for apply as it requires additional privileges on the client, and the behavior is not symmetrical when the namespaces do not exist. I would expect the command to fail if the namespace does not exist.

In the case of `kubectl apply` you simply get NotFound
```
$ kubectl apply -f /tmp/my-role.yaml --namespace non-existant-ns
Error from server (NotFound): error when creating "/tmp/bg.yaml": namespaces "non-existant-ns" not found
```

**Environment**:
- Kubernetes version (use `kubectl version`):

```
$ kubectl version --client -o yaml
clientVersion:
  buildDate: 2018-09-28T15:20:58Z
  compiler: gc
  gitCommit: 0ed33881dc4355495f623c6f22e7dd0b7632b7c0
  gitTreeState: clean
  gitVersion: v1.12.0
  goVersion: go1.11
  major: "1"
  minor: "12"
  platform: darwin/amd64
```

/sig cli
/sig auth

/kind bug

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

Clarifies how the `auth reconcile` command works

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #71185

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

File: pkg/kubectl/cmd/auth/reconcile.go [hunk 1]
```diff
@@ -59,6 +59,14 @@ var (
...
 
+		Missing objects are created, and the containing namespace is created for namespaced objects, if required.
+		
+		Existing roles are updated to include the permissions in the input objects,
+		and remove extra permissions if --remove-extra-permissions is specified.
+
+		Existing bindings are updated to include the subjects in the input objects,
+		and remove extra subjects if --remove-extra-subjects is specified.
+
 		This is preferred to 'apply' for RBAC resources so that proper rule coverage checks are done.`)
```
Comment (justinsb) [inline pkg/kubectl/cmd/auth/reconcile.go]: I know this is existing, but this sounds ominous - as if `apply` bypasses security checks?  Or that `apply` shouldn't be used with RBAC objects?
