### PR TITLE
Fix volume reconstruction in standalone mode

### LINKED ISSUE #116549: panic in updateReconstructedDevicePaths in standalone mode
### What happened?

Must be a result of https://github.com/kubernetes/kubernetes/pull/115268/

@jsafrane

When running kubelet in standalone mode got this panic:

```
E0313 20:39:03.702548 1312451 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 294 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3a186c0?, 0x684a380})
	vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x47ce9e?})
	vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x3a186c0, 0x684a380})
	/usr/local/google/home/skanzhelev/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/runtime/panic.go:884 +0x213
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).updateReconstructedDevicePaths(0xc00098e360)
	pkg/kubelet/volumemanager/reconciler/reconstruct_new.go:183 +0x8a
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).reconcileNew(0xc00098e360)
	pkg/kubelet/volumemanager/reconciler/reconciler_new.go:60 +0x99
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:154 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x42f56a5?, {0x4867b20, 0xc0010d1770}, 0x1, 0xc000298060)
	vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:155 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x5f5e100, 0x0, 0x1e?, 0x0?)
	vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:132 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:89
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).runNew(0xc00098e360, 0x42ef7f7?)
	pkg/kubelet/volumemanager/reconciler/reconciler_new.go:30 +0x9d
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).Run(0xc0009c3b00?, 0xc000298060?)
	pkg/kubelet/volumemanager/reconciler/reconciler_common.go:150 +0x55
created by k8s.io/kubernetes/pkg/kubelet/volumemanager.(*volumeManager).Run
	pkg/kubelet/volumemanager/volume_manager.go:285 +0x29d
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x33632ea]

goroutine 294 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x47ce9e?})
	vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x3a186c0, 0x684a380})
	/usr/local/google/home/skanzhelev/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/runtime/panic.go:884 +0x213
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).updateReconstructedDevicePaths(0xc00098e360)
	pkg/kubelet/volumemanager/reconciler/reconstruct_new.go:183 +0x8a
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).reconcileNew(0xc00098e360)
	pkg/kubelet/volumemanager/reconciler/reconciler_new.go:60 +0x99
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x30?)
	vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:154 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x42f56a5?, {0x4867b20, 0xc0010d1770}, 0x1, 0xc000298060)
	vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:155 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x5f5e100, 0x0, 0x1e?, 0x0?)
	vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:132 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	vendor/k8s.io/apimachinery/pkg/util/wait/backoff.go:89
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).runNew(0xc00098e360, 0x42ef7f7?)
	pkg/kubelet/volumemanager/reconciler/reconciler_new.go:30 +0x9d
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).Run(0xc0009c3b00?, 0xc000298060?)
	pkg/kubelet/volumemanager/reconciler/reconciler_common.go:150 +0x55
created by k8s.io/kubernetes/pkg/kubelet/volumemanager.(*volumeManager).Run
	pkg/kubelet/volumemanager/volume_manager.go:285 +0x29d
```

### What did you expect to happen?

No panic

### How can we reproduce it (as minimally and precisely as possible)?

run kubelet in standalone mode

### Anything else we need to know?

_No response_

### Kubernetes version

master branch

### Cloud provider

<details>
N/A
</details>

### OS version

<details>
N/A
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by jsafrane**
#### What type of PR is this?
/kind bug
/kind regression

#### What this PR does / why we need it:
Kubelet in standalone mode won't have kubeclient, it cannot get node.status and get devices from it. Such a kubelet cannot mount attachable volumes anyway.

#### Which issue(s) this PR fixes:

Fixes #116549

#### Special notes for your reviewer:
I checked other `kubeClient` usages in VolumeManager, it is the only place where the old reconstruction used check for nil: https://github.com/kubernetes/kubernetes/blob/e998b09bc4e1926c91115f2318f317faa61dbe19/pkg/kubelet/volumemanager/reconciler/reconstruct.go#L133-L138

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by vinaykul** [comment]
/lgtm

xref: https://github.com/kubernetes/kubernetes/issues/116549#issuecomment-1468122139

File: pkg/kubelet/volumemanager/reconciler/reconstruct_new.go [hunk 1]
```diff
@@ -180,6 +180,14 @@ func (rc *reconciler) cleanOrphanVolumes() {
...
 
+	if rc.kubeClient == nil {
+		// Skip reconstructing devicePath from node objects if kubelet is in standalone mode.
+		// Such kubelet is not expected to mount any attachable volume or Secrets / ConfigMap.
+		klog.V(2).InfoS("Skipped reconstruction of DevicePaths from node.status in standalone mode")
+		rc.volumesNeedDevicePath = nil
+		return
+	}
+
 	node, fetchErr := rc.kubeClient.CoreV1().Nodes().Get(context.TODO(), string(rc.nodeName), metav1.GetOptions{})
```
Comment (liggitt) [inline pkg/kubelet/volumemanager/reconciler/reconstruct_new.go:191]: There are three modes the kubelet can be in:
1. never talk to an API server (kubeClient is nil)
2. talk to an API server it is responsible for starting (kubeClient is non-nil, but API calls will fail until the kubelet starts its static pods)
3. talk to an API server someone else is responsible for starting (kubeClient is non-nil, API calls will ~eventually work if the kubelet just keeps on trying)

This PR is working to fix scenario 1.

In scenario 2, does `updateReconstructedDevicePaths()` block the kubelet from running the kube-apiserver container?

**Comment by liggitt** [comment]
/assign @msau42 
for review of standalone behavior here

File: pkg/kubelet/volumemanager/reconciler/reconstruct_new.go (hunk 1 above)
Comment (jsafrane) [reply pkg/kubelet/volumemanager/reconciler/reconstruct_new.go:191]: 2. should be tested in CI, because all `-kind-` jobs use static pods

In pull-kubernetes-e2e-kind I can see in [one of the kubelets](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/116577/pull-kubernetes-e2e-kind/1635605473094799360/artifacts/kind-control-plane/kubelet.log) there:

`
Mar 14 11:48:18 kind-control-plane kubelet[288]: I0314 11:48:18.354841     288 kubelet.go:1821] "Creating a mirror pod for static pod" pod="kube-system/kube-apiserver-kind-control-plane"
Mar 14 11:48:18 kind-control-plane kubelet[288]: I0314 11:48:18.354976     288 kubelet.go:1821] "Creating a mirror pod for static pod" pod="kube-system/kube-controller-manager-kind-control-plane"
...
`

Comment (liggitt) [reply pkg/kubelet/volumemanager/reconciler/reconstruct_new.go:191]: I didn't know if volume reconstruction took a different code path on restart of a kubelet with existing volume state on disk vs first-start

Comment (msau42) [reply pkg/kubelet/volumemanager/reconciler/reconstruct_new.go:191]: If the call fails here, it will still proceed with the rest of the volume manager reconciler: https://github.com/kubernetes/kubernetes/blob/a9008b502d32a5dbacf835adb040419bf31f5c04/pkg/kubelet/volumemanager/reconciler/reconciler_new.go#L60

The device path information is only needed for attachable volume types, which is not supported in standalone mode. It would still be good to test the reconstruction scenarios for the different scenarios.
