### PR TITLE
fix: predicates read nodes from scheduler cache

### LINKED ISSUE #75617: Scheduler: affinity predicates read nodes from informer cache instead of scheduler cache
**What happened**:
I recently saw an issue in which the scheduler hit this log line many times: 
https://github.com/kubernetes/kubernetes/blob/6f482974b76db3f1e0f5d24605a9d1d38fad9a2b/pkg/scheduler/algorithm/predicates/predicates.go#L1276

After some digging, it turns out that PodAffinityChecker has a `PodLister` and `NodeInfo`. The `PodLister` points at the scheduler's cache instance, while the `NodeInfo` points at a light wrapper around a `corelisters.NodeLister`.

https://github.com/kubernetes/kubernetes/blob/6f482974b76db3f1e0f5d24605a9d1d38fad9a2b/pkg/scheduler/factory/factory.go#L1329

In the scheduler, we use the cache to provide a globally consistent view of the cluster, even if that view is slightly out of date. Data read from the core `NodeInfo` may not have been processed by the scheduler cache yet. Letting data "skip ahead" like this can cause stale info to get persisted in the scheduler cache, and other subtle bugs.

While the original problem is not likely caused by this issue, I think it needs to be cleaned up to avoid potential bugs down the line.

**What you expected to happen**:
Predicates should only read state from the scheduler's cache in order to maintain consistency.

**How to reproduce it (as minimally and precisely as possible)**:
This was observed in a cluster with high rate of pod creation and node creation/deletion.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12.5
- Cloud provider or hardware configuration: GKE with preemptible nodes
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by draveness**
/kind bug
/priority important-soon

**What this PR does / why we need it**:

Predicates should read cache from scheduler cache instead of the informer to maintain consistency.

**Which issue(s) this PR fixes**:

Fixes #75617

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by draveness** [comment]
/sig scheduling

cc/ @misterikkit

**Comment by draveness** [comment]
/retest

Regards,
Draven

**Review by wgliang — APPROVED** [review]
/lgtm

**Comment by tallclair** [comment]
/approve
For pkg/kubelet changes

**Comment by draveness** [comment]
> /approve
> For pkg/kubelet changes

Thanks!

Kindly ping @ravisantoshgudimetla @misterikkit for approval.

File: pkg/scheduler/internal/cache/cache.go [hunk 1]
```diff
@@ -665,3 +665,16 @@ func (cache *schedulerCache) expirePod(key string, ps *podState) error {
 func (cache *schedulerCache) NodeTree() *NodeTree {
 	return cache.nodeTree
 }
+
+// GetNodeInfo returns cached data for the node 'id'.
+func (cache *schedulerCache) GetNodeInfo(nodeID string) (*v1.Node, error) {
+	cache.mu.Lock()
```
Comment (ravisantoshgudimetla) [inline pkg/scheduler/internal/cache/cache.go]: I think you just need a `RLock` here

Comment (ravisantoshgudimetla) [reply pkg/scheduler/internal/cache/cache.go]: Also, do we have any performance hit with this?

Comment (draveness) [reply pkg/scheduler/internal/cache/cache.go]: Comment has been addressed.

Did I use the wrong approach to run the scheduler perf tests? I followed the instructions in https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/test/integration/scheduler_perf/README.md, when I ran it in the master and this branch, and it gives warnings like this, but it seems like that there is a performance improvement.

```go
// master branch
$  ./test-performance.sh
...
Warning: pod scheduling throughput for 3k pods was slow for an interval... Saw an interval with very low (51) scheduling rate!PASS
ok  	k8s.io/kubernetes/test/integration/scheduler_perf	39.598s

// current branch
$  ./test-performance.sh
...
Warning: pod scheduling throughput for 3k pods was slow for an interval... Saw an interval with very low (79) scheduling rate!PASS
ok  	k8s.io/kubernetes/test/integration/scheduler_perf	37.803s
```

File: pkg/scheduler/factory/factory.go [hunk 2]
```diff
@@ -576,7 +579,7 @@ func (c *configFactory) getPluginArgs() (*PluginFactoryArgs, error) {
 		StatefulSetLister:              c.statefulSetLister,
 		NodeLister:                     &nodeLister{c.nodeLister},
 		PDBLister:                      c.pdbLister,
-		NodeInfo:                       &predicates.CachedNodeInfo{NodeLister: c.nodeLister},
+		NodeInfo:                       c.nodeInfo,
```
Comment (bsalamat) [inline pkg/scheduler/factory/factory.go]: Why not passing `schedulerCache`? It does not look correct to me to add `nodeInfo` to `configFactory`.

Comment (draveness) [reply pkg/scheduler/factory/factory.go]: I update the PR address the comment, but I noticed `configFactory` pass `podLister` instead of `schedulerCache` into `PluginFactoryArgs`, do I need to fix this too?

```go
func (c *configFactory) getPluginArgs() (*PluginFactoryArgs, error) {
	return &PluginFactoryArgs{
		PodLister:                      c.podLister, // could use c.schedulerCache
		ServiceLister:                  c.serviceLister,
		ControllerLister:               c.controllerLister,
		ReplicaSetLister:               c.replicaSetLister,
		StatefulSetLister:              c.statefulSetLister,
		NodeLister:                     &nodeLister{c.nodeLister},
		PDBLister:                      c.pdbLister,
		NodeInfo:                       c.schedulerCache,
		PVInfo:                         &predicates.CachedPersistentVolumeInfo{PersistentVolumeLister: c.pVLister},
		PVCInfo:                        &predicates.CachedPersistentVolumeClaimInfo{PersistentVolumeClaimLister: c.pVCLister},
		StorageClassInfo:               &predicates.CachedStorageClassInfo{StorageClassLister: c.storageClassLister},
		VolumeBinder:                   c.volumeBinder,
		HardPodAffinitySymmetricWeight: c.hardPodAffinitySymmetricWeight,
	}, nil
}
```

**Comment by draveness** [comment]
/retest

Regards,
Draven

File: pkg/scheduler/internal/cache/cache.go [hunk 3]
```diff
@@ -707,3 +707,16 @@ func (cache *schedulerCache) expirePod(key string, ps *podState) error {
 func (cache *schedulerCache) NodeTree() *NodeTree {
 	return cache.nodeTree
 }
+
+// GetNodeInfo returns cached data for the node 'id'.
+func (cache *schedulerCache) GetNodeInfo(nodeID string) (*v1.Node, error) {
```
Comment (bsalamat) [inline pkg/scheduler/internal/cache/cache.go]: nit: please rename `nodeID` to `name` or `nodeName`. ID may be confused with a node UID.

File: pkg/scheduler/internal/cache/interface.go [hunk 4]
```diff
@@ -110,6 +110,9 @@ type Cache interface {
 	// RemoveCSINode removes overall CSI-related information about node.
 	RemoveCSINode(csiNode *storagev1beta1.CSINode) error
 
+	// GetNodeInfo returns the node object with node id.
+	GetNodeInfo(nodeID string) (*v1.Node, error)
```
Comment (bsalamat) [inline pkg/scheduler/internal/cache/interface.go]: s/nodeID/nodeName/

**Review by bsalamat — COMMENTED** [review]
Looks good. Just a minor comment.

File: pkg/scheduler/factory/factory.go (hunk 2 above)
Comment (bsalamat) [reply pkg/scheduler/factory/factory.go]: We can consider that change too, but don't make that change in this PR.

**Comment by draveness** [comment]
> @bsalamat  Looks good. Just a minor comment.

Thanks, Bobby! Comments have been addressed, please take another look.

File: pkg/scheduler/factory/factory.go (hunk 2 above)
Comment (draveness) [reply pkg/scheduler/factory/factory.go]: I've opened an issue to track this potential change https://github.com/kubernetes/kubernetes/issues/79538

Comment (ahg-g) [reply pkg/scheduler/factory/factory.go]: shouldn't we also change NodeLister to use the scheduler's node cache as well?

Comment (draveness) [reply pkg/scheduler/factory/factory.go]: > shouldn't we also change NodeLister to use the scheduler's node cache as well?

We could do that in other PR if necessary.

Comment (ahg-g) [reply pkg/scheduler/factory/factory.go]: can you please explain why is it necessary to change NodeInfo to use the scheduler cache, but NodeLister may not be?

Comment (draveness) [reply pkg/scheduler/factory/factory.go]: > In the scheduler, we use the cache to provide a globally consistent view of the cluster, even if that view is slightly out of date. Data read from the core NodeInfo may not have been processed by the scheduler cache yet. Letting data "skip ahead" like this can cause stale info to get persisted in the scheduler cache, and other subtle bugs. https://github.com/kubernetes/kubernetes/issues/75617#issue-424410497


This PR is supposed to make the predicates read node info from scheduler cache, and updates `NodeLister` is irrelevant to this purpose, so I'd prefer to do it in another one.

Comment (ahg-g) [reply pkg/scheduler/factory/factory.go]: I am not asking to do it in this PR. What I am asking is whether or not the problem is limited to what the issue claims to be. Anyways, I will take a closer look and open another issue, thanks for doing this one.

Comment (draveness) [reply pkg/scheduler/factory/factory.go]: @ahg-g Thank you for your clarifying, we could track the related issue in #79538

**Review by bsalamat — APPROVED** [review]
/lgtm
/approve

Thanks, @draveness!

File: pkg/scheduler/internal/cache/cache.go (hunk 1 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/cache/cache.go]: FYI: the guide is at https://github.com/kubernetes/community/blob/master/contributors/devel/sig-scheduling/scheduler_benchmarking.md

File: pkg/scheduler/factory/factory.go (hunk 2 above)
Comment (ahg-g) [reply pkg/scheduler/factory/factory.go]: ok, I got a chance to look more into this, I think changing NodeLister to use the scheduler cache is more than a possible clean up issue, which #79538 declares to be.

NodeLister is used in [CalculateInterPodAffinityPriority](https://github.com/kubernetes/kubernetes/blob/38e8b8a9f65e66b779a0985e17868b036c1d601b/pkg/scheduler/algorithmprovider/defaults/register_priorities.go#L73) along with NodeInfo. NodeInfo now is not reading from the same source as NodeLister, and so potentially this change could have solved one thing, but caused another.

I opened #79629 to track this issue.
