### PR TITLE
Fix a panic for in-tree drivers that partialy support Block volume metrics

### LINKED ISSUE #101431: Add support for gathering BlockVolume metrics from in-tree storage drivers
#### What would you like to be added:

#97972 adds support for metrics from BlocMode volumes provided by CSI-drivers.

In-tree drivers can provide these metrics as well. At least the Capacity (size) of the block-device can be fetched with standard tools.

#### Why is this needed:

This makes it easier to test the changes from #97972 and can provide standard utilities that CSI-drivers can consume as well. An implementation should probably look like the `pkg/volume/metrics_statfs.go:NewMetricsStatFS()` call.

/sig storage
/assign nixpanic

### PR DESCRIPTION
**Pull request by nixpanic**
#### What type of PR is this?

/kind feature
/sig storage

#### What this PR does / why we need it:

#97972 added support for gathering metrics for Block volumes provided by CSI drivers. The current in-tree drivers that support Block volumes can return at least the Capacity of the block-device.

CSI drivers are currently not tested for metrics gathering in the e2e framework. Adding support for this in the in-tree drivers makes it possible to verify the functionality and prevent regressions.

#### Which issue(s) this PR fixes:

Fixes #101431

#### Special notes for your reviewer:

Block volume metrics detection is quite limited. Except for the Capacity (size of the volume), there is little that can be gathered with standard tools. The contents of a Block volume can not be inspected like a filesystem. In theory drivers could thin-provision (like a sparse file) volumes, and provide Used/Available in addition to the Capacity. However, this needs access and details knowledge of the storage platform, and can not be detected with standard tools.

#### Does this PR introduce a user-facing change?

```release-note
Some of the in-tree storage drivers indicate support for the MetricsProvider interface, but fail to configure this for BlockMode volumes. With a recent change, Kubelet will call GetMetrics() for BlockMode volumes, and the in-tree drivers that miss the support cause a Go panic. Now the in-tree storage drivers that support BlockMode volumes, will return the Capacity of the volume in the GetMetrics() call.
```

### CODE REVIEW

**Comment by nixpanic** [comment]
@gnufied, you expressed interest in adding a metrics test for BlockMode volumes, so assigning you already, before others have posted review comments.

/assign gnufied

**Comment by nixpanic** [comment]
The Azure jobs (not required to pass) seem to have failed due to something unrelated:
```
ProvisioningFailed: Failed to provision volume with StorageClass "azurefile-3090-kubernetes.io-azure-file-dynamic-sc-vv4t2": invalid option "enableLargeFileshares" for volume plugin kubernetes.io/azure-file
```

**Comment by andyzhangx** [comment]
> The Azure jobs (not required to pass) seem to have failed due to something unrelated:
> 
> ```
> ProvisioningFailed: Failed to provision volume with StorageClass "azurefile-3090-kubernetes.io-azure-file-dynamic-sc-vv4t2": invalid option "enableLargeFileshares" for volume plugin kubernetes.io/azure-file
> ```

https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/645 would fix the issue soon

**Comment by nixpanic** [comment]
/kind bug

Without this change, some of the in-tree storage drivers can cause a panic. See https://github.com/kubernetes/kubernetes/issues/101431#issuecomment-833262944 for more details.

**Comment by pohly** [comment]
> /kind bug
> 
> Without this change, some of the in-tree storage drivers can cause a panic. See [#101431 (comment)](https://github.com/kubernetes/kubernetes/issues/101431#issuecomment-833262944) for more details.

That should be mentioned in the release note section of the PR description.

File: pkg/volume/metrics_block.go [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+	if err != nil {
+		return metrics, err
+	}
+
+	return metrics, nil
+}
+
+// getBlockInfo updates metrics.Capacity from the "lsblk" output.
+func (mb *metricsBlock) getBlockInfo(metrics *Metrics) error {
+	args := []string{"--noheadings", "--bytes", "--output=SIZE", mb.device}
```
[the remark this answers is not in the document]
Comment (nixpanic) [reply pkg/volume/metrics_block.go]: Please have a look again. I have replaced the `lsblk` command with `os.Open()` and `.Seek()`. I expect that this is portable across different OSs.

**Comment by nixpanic** [comment]
/retest

I am trying to find out why fetching the metrics fail with a `UnexpectedServerResponse` (http 503). Nothing stands out in the logs to me, might be a timing issue?

**Comment by nixpanic** [comment]
/retest

It seems the failure is relatively common, and not introduced with this PR. Lots of runs at https://prow.k8s.io/?job=pull-kubernetes-e2e-gce-ubuntu-containerd have the same failure.

**Comment by SergeyKanzhelev** [comment]
does this PR suppose to fix panic my PR observes: https://github.com/kubernetes/kubernetes/pull/101719 ?

**Comment by nixpanic** [comment]
> does this PR suppose to fix panic my PR observes: #101719 ?

Yes, I expect it will!

```
panic(0x4235920, 0x7411320)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/kubernetes/pkg/volume/gcepd.(*gcePersistentDiskMapper).GetMetrics(0xc002e20ac0, 0x4b5b386, 0xf, 0x0)
	<autogenerated>:1 +0x32
k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).calcAndStoreStats(0xc002201140)
```

`gcePersistentDiskMapper` exposes the `MetricsProvider` interface, but does not set it up. Calling the `GetMetrics()` function causes the panic in that case. Several other in-tree drivers have the same problem.

If you are able to verify/test this PR, feedback would be much appreciated. Thanks!

**Comment by gnufied** [comment]
@nixpanic what happened to type assertion? why didn't that work - https://github.com/kubernetes/kubernetes/pull/97972/files#diff-29b95d3e0972ccf0fe5a9fc814db80cf3b39465008c13db8f0ececf231e840b2R113 ?

**Comment by nixpanic** [comment]
> @nixpanic what happened to type assertion? why didn't that work - https://github.com/kubernetes/kubernetes/pull/97972/files#diff-29b95d3e0972ccf0fe5a9fc814db80cf3b39465008c13db8f0ececf231e840b2R113 ?

Base types like `gcePersistentDisk` contain a `volume.MetricsProvider` already (see line 342):

https://github.com/kubernetes/kubernetes/blob/e8cf412e5ec70081477ad6f126c7f7ef7449109c/pkg/volume/gcepd/gce_pd.go#L330-L343

And the `gcePersistentDiskMapper` just extends it, without ever setting up a `GetMetrics()` function.

https://github.com/kubernetes/kubernetes/blob/e8cf412e5ec70081477ad6f126c7f7ef7449109c/pkg/volume/gcepd/gce_pd_block.go#L145-L148

So, `gcePersistentDiskMapper` is a `volume.MetricsProvider`, but with without `GetMetrics()`. That  makes the type-assertion pass, and calling the function panic.

File: pkg/volume/iscsi/iscsi.go [hunk 2]
```diff
@@ -161,12 +161,20 @@ func (plugin *iscsiPlugin) newBlockVolumeMapperInternal(spec *volume.Spec, podUI
...
 		exec:       exec,
 		deviceUtil: ioutil.NewDeviceHandler(ioutil.NewIOHandler()),
-	}, nil
+	}
+
+	blockPath, err := mapper.GetGlobalMapPath(spec)
+	if err != nil {
+		return nil, fmt.Errorf("failed to get device path: %v", err)
+	}
+	mapper.MetricsProvider = volume.NewMetricsBlock(blockPath + "/" + string(podUID))
```
Comment (gnufied) [inline pkg/volume/iscsi/iscsi.go:175]: I would perhaps use `filepath.Join` just to be safe and making sure it works on Windows.

File: pkg/volume/metrics_block.go [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+// the end.
+func (mb *metricsBlock) getBlockInfo(metrics *Metrics) error {
+	dev, err := os.Open(mb.device)
+	if err != nil {
+		return fmt.Errorf("unable to open device %q: %w", mb.device, err)
+	}
+	defer dev.Close()
+
+	end, err := dev.Seek(0, io.SeekEnd)
+	if err != nil {
```
Comment (gnufied) [inline pkg/volume/metrics_block.go:74]: Have you tested this to work on Windows btw?

**Comment by gnufied** [comment]
@nixpanic so it sounds like we need a `nil` check for `MetricsProvider` in the code where metrics are extracted? I think that while this PR may fix the panic but just to be safe against uninitialized `MetricsProvider` code - we should check for `nil` as well.

File: pkg/volume/iscsi/iscsi.go (hunk 2 above)
Comment (gnufied) [reply pkg/volume/iscsi/iscsi.go:175]: I meant this for everywhere else also.

File: pkg/volume/metrics_block.go (hunk 3 above)
Comment (gnufied) [reply pkg/volume/metrics_block.go:74]: oops I saw your response to @jsafrane above. Since I don't know anything about Windows, lets check with @jingxu97 or @andyzhangx ?

File: pkg/volume/iscsi/iscsi.go (hunk 2 above)
Comment (nixpanic) [reply pkg/volume/iscsi/iscsi.go:175]: Yes, of course, will do that!

File: pkg/volume/metrics_block.go (hunk 3 above)
Comment (andyzhangx) [reply pkg/volume/metrics_block.go:74]: I don't think this would work on Windows, since Windows usually use powershell or dos command for such command. Is it possible to add an empty implementation for Windows?

Comment (gnufied) [reply pkg/volume/metrics_block.go:74]: +1 to making two versions of this functions and providing a empty empty implementation for windows. Having said that, it would be weird if Windows did not support seeking a block device to the end via golang APIs. I could be wrong though and hence to be on safe side.

Comment (jingxu97) [reply pkg/volume/metrics_block.go:74]: found related information on os.seek for Windows
https://github.com/golang/go/issues/36019

seems it does not work if it is a directory handle. But not sure about this case.

**Comment by nixpanic** [comment]
> @nixpanic so it sounds like we need a `nil` check for `MetricsProvider` in the code where metrics are extracted? I think that while this PR may fix the panic but just to be safe against uninitialized `MetricsProvider` code - we should check for `nil` as well.

This is more difficult than expected :disappointed: Checking for `nil` of the `MetricsProvider` or the `GetMetrics()` function is not possible it seems. Using `reflect` inspired by #102054 (failed to use the pkg correctly) does not work either. Lots of testing with `reflect.Value` and it's functions did not provide me with a solution. A non-initialized MetricsProvider/GetMetrics() is not `nil`, but some invalid pointer.

Example of the testing in `pkg/kubelet/server/stats/volume_stat_calculator.go`:
```diff
@@ -127,7 +128,7 @@ func (s *volumeStatCalculator) calcAndStoreStats() {
        var ephemeralStats []stats.VolumeStats
        var persistentStats []stats.VolumeStats
        for name, v := range metricVolumes {
-               metric, err := v.GetMetrics()
+               metric, err := safeGetMetrics(v.GetMetrics)
                if err != nil {
                        // Expected for Volumes that don't support Metrics
                        if !volume.IsNotSupported(err) {
@@ -163,6 +164,15 @@ func (s *volumeStatCalculator) calcAndStoreStats() {
                PersistentVolumes: persistentStats})
 }
 
+func safeGetMetrics(gm func() (*volume.Metrics, error)) (*volume.Metrics, error) {
+       ref := reflect.ValueOf(gm)
+       if !ref.CanAddr() { // FAIL! All GetMetrics() functions, initialized or not, behave the same.
+               return nil, volume.NewNotImplementedError()
+       }
+
+       return gm()
+}
+
 // parsePodVolumeStats converts (internal) volume.Metrics to (external) stats.VolumeStats structures
 func (s *volumeStatCalculator) parsePodVolumeStats(podName string, pvcRef *stats.PVCReference, metric *volume.Metrics, volSpec v1.Volume) stats.VolumeStats {
 
```

So, without a solution to this, I am not able to make `calcAndStoreStats()` safe when drivers expose the `MetricsProvider` interface, but fails to provide a `GetMetrics()` function.

File: pkg/volume/metrics_block.go (hunk 3 above)
Comment (nixpanic) [reply pkg/volume/metrics_block.go:74]: While researching if `Seek()` works correctly for drives on Windows, I can add a `FIXME` note and skip the detection with a
```go
if runtime.GOOS == "winows" {
    // FIXME: it is uncertain how Windows handles Seek() for block devices
    return
}```

Is that acceptable too?

I am also wondering if it is even possible to provision volumes with `VolumeMode: Block` on Windows?

Comment (andyzhangx) [reply pkg/volume/metrics_block.go:74]: `VolumeMode: Block` is not supported yet on Windows, maybe return error directly for Windows?

Comment (nixpanic) [reply pkg/volume/metrics_block.go:74]: Thanks @andyzhangx , will return an error and leave a `TODO` comment.

File: pkg/volume/iscsi/iscsi.go (hunk 2 above)
Comment (nixpanic) [reply pkg/volume/iscsi/iscsi.go]: This is done with the latest revision.

File: pkg/volume/metrics_block.go (hunk 3 above)
Comment (nixpanic) [reply pkg/volume/metrics_block.go:80]: This is also done with the latest revision. (Return an error on Windows, not separated functions per OS.)

**Comment by gnufied** [comment]
> 
> So, without a solution to this, I am not able to make `calcAndStoreStats()` safe when drivers expose the `MetricsProvider` interface, but fails to provide a `GetMetrics()` function.

Hmm - we are running into golang limitations. :-) But this code has broken in past and somehow gets past review process and hence I think is in urgent need of fixing. 

I am thinking we should tweak the way we are embedding interfaces in volume plugin interface such that it is possible to query if `MetricsProvider` has been set. For example - `BlockVolume` interface can have an explicit function:

```golang
type BlockVolume interface {
	// GetGlobalMapPath returns a global map path which contains
	// bind mount associated to a block device.
	// ex. plugins/kubernetes.io/{PluginName}/{DefaultKubeletVolumeDevicesDirName}/{volumePluginDependentPath}/{pod uuid}
	GetGlobalMapPath(spec *Spec) (string, error)
	// GetPodDeviceMapPath returns a pod device map path
	// and name of a symbolic link associated to a block device.
	// ex. pods/{podUid}/{DefaultKubeletVolumeDevicesDirName}/{escapeQualifiedPluginName}/, {volumeName}
	GetPodDeviceMapPath() (string, string)
        // if MetricsProvider is set return it , otherwise nil
        GetMetricsProvider() MetricsProvider

	// MetricsProvider embeds methods for exposing metrics (e.g.
	// used, available space).
	MetricsProvider
}
```

This way, it should be possible to write code like:

```golang
	if v.GetMetricsProvider() != nil {
		fmt.Printf("name is: %s\n", g.GetMetrics())
	}
```

That is just one idea though, there could be other ways of solving this. But I *do* think - this code is bit fragile. :(

**Comment by nixpanic** [comment]
Thanks for the idea, @gnufied! Instead of `GetMetricsProvider()` I have added `SupportsMetrics()` which returns a `bool` with commit **Add SupportsMetrics() for Block-mode volumes**. Please have a look again and see if this addresses your concerns.

**Review by ehashman — COMMENTED** [review]
/priority important-longterm

Kubelet changes LGTM.

**Review by mrunalp — APPROVED** [review]
