### PR TITLE
Node status updater now deletes the node entry in attach updates...

### LINKED ISSUE #42438: kube-controller-manager spamming errors in log
kubernetes version: 1.5.3
platform: aws
deploy tool: kops

my master's **/var/log/kube-controller-manager.log**

is receiving this type of log:

```
I0302 21:51:11.715415       6 node_status_updater.go:74] Could not update node status. Failed to find node "ip-172-20-114-85.ec2.internal" in NodeInformer cache. <nil>
I0302 21:51:11.815662       6 node_status_updater.go:74] Could not update node status. Failed to find node "ip-172-20-114-85.ec2.internal" in NodeInformer cache. <nil>
I0302 21:51:11.915905       6 node_status_updater.go:74] Could not update node status. Failed to find node "ip-172-20-114-85.ec2.internal" in NodeInformer cache. <nil>
I0302 21:51:12.016217       6 node_status_updater.go:74] Could not update node status. Failed to find node "ip-172-20-114-85.ec2.internal" in NodeInformer cache. <nil>
I0302 21:51:12.116508       6 node_status_updater.go:74] Could not update node status. Failed to find node "ip-172-20-114-85.ec2.internal" in NodeInformer cache. <nil>
I0302 21:51:12.216725       6 node_status_updater.go:74] Could not update node status. Failed to find node "ip-172-20-114-85.ec2.internal" in NodeInformer cache. <nil>
I0302 21:51:12.316962       6 node_status_updater.go:74] Could not update node status ...
```

lots of times per second, this node "ip-172-20-114-85.ec2.internal" does not exist in the cluster anymore and is not shown if I ```kubectl get nodes```

shouldn't it be removed from status_updater?

### PR DESCRIPTION
**Pull request by verult**
… when node is missing in NodeInformer cache.

- Added RemoveNodeFromAttachUpdates as part of node status updater operations.

**What this PR does / why we need it**: Fixes issue of unnecessary node status updates when node is deleted.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #42438

**Special notes for your reviewer**: Unit tested added, but a more comprehensive test involving the attach detach controller requires certain testing functionality that is currently absent, and will require larger effort. Will be added at a later time.

There is an edge case caused by the following steps:
1) A node is deleted and restarted. The node exists, but is not yet recognized by Kubernetes.
2) A pod requiring a volume attach with nodeName specifically set to this node.

This would make the pod stuck in ContainerCreating state. This is low-pri since it's a specific edge case that can be avoided.

**Release note**:

```release-note
Fix log spam due to unnecessary status update when node is deleted.
```

### CODE REVIEW

File: pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go [hunk 1]
```diff
@@ -69,10 +69,10 @@ func (nsu *nodeStatusUpdater) UpdateNodeStatuses() error {
 			// reset flag statusUpdateNeeded back to true to indicate this node status
 			// needs to be updated again
 			glog.V(2).Infof(
-				"Could not update node status. Failed to find node %q in NodeInformer cache. %v",
+				"Could not update node status. Failed to find node %q in NodeInformer cache. Error: '%v'",
 				nodeName,
 				err)
-			nsu.actualStateOfWorld.SetNodeStatusUpdateNeeded(nodeName)
+			nsu.actualStateOfWorld.RemoveNodeFromAttachUpdates(nodeName)
```
Comment (jingxu97) [inline pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go]: I think you need to take different actions for nodeObj==nil and err != nil
When nodeObj==nil, it shows that API server does not have this object anymore, it should be safe to removeNode. But for err != nil, that indicates something wrong then retrieving the node object and node status updater should try it again.

Comment (verult) [inline pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go]: nodeLister.Get() returns nil object only when there's an error, and returns an error only when the object is nil. However I can add in as a safeguard against future changes.

**Comment by verult** [comment]
@k8s-bot ok to test

**Comment by msau42** [comment]
@k8s-bot ok to test

**Comment by jingxu97** [comment]
@k8s-bot ok to test

File: pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go (hunk 1 above)
Comment (jingxu97) [inline pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go]: The error is different if node does not exist errors.NewNotFound(v1.Resource("node"), name)
you can check the error type to determine whether it is because of node exist or not.

File: pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go [hunk 2]
```diff
@@ -64,14 +66,19 @@ func (nsu *nodeStatusUpdater) UpdateNodeStatuses() error {
 	nodesToUpdate := nsu.actualStateOfWorld.GetVolumesToReportAttached()
 	for nodeName, attachedVolumes := range nodesToUpdate {
 		nodeObj, err := nsu.nodeLister.Get(string(nodeName))
-		if nodeObj == nil || err != nil {
+		statusErr, isStatusError := err.(*errors.StatusError)
+		if isStatusError && statusErr.Status().Reason == metav1.StatusReasonNotFound {
 			// If node does not exist, its status cannot be updated, log error and
 			// reset flag statusUpdateNeeded back to true to indicate this node status
 			// needs to be updated again
```
Comment (saad-ali) [inline pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go]: nit: Update this comment.

File: pkg/volume/util/operationexecutor/operation_executor.go [hunk 3]
```diff
@@ -160,12 +160,16 @@ type ActualStateOfWorldAttacherUpdater interface {
...
 	RemoveVolumeFromReportAsAttached(volumeName v1.UniqueVolumeName, nodeName types.NodeName) error
 
 	// Unmarks the desire to detach for the specified volume (add the volume back to
-	// the node's volumesToReportedAsAttached list)
+	// the node's volumesToReportAsAttached list)
 	AddVolumeToReportAsAttached(volumeName v1.UniqueVolumeName, nodeName types.NodeName)
+
+	// Removes the given node from the record of attach updates. The node's entire
+	// volumesToReportAsAttached list is removed.
+	RemoveNodeFromAttachUpdates(nodeName types.NodeName) error
```
Comment (saad-ali) [inline pkg/volume/util/operationexecutor/operation_executor.go]: Since this operation does not apply to both attachdetach and volumemanager actual_state_of_the_world, just add it to the ASW interface in controller/volume/attachdetach/cache/actual_state_of_world.go instead. Then you don't need to put a noop version of the method in volumemanager/cache/actual_state_of_world.go

**Review by saad-ali — CHANGES_REQUESTED** [review]
A couple of comments.

**Comment by saad-ali** [comment]
Make sure to keep the 1.5 version in sync with any changes in this PR as well

File: pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go [hunk 4]
```diff
@@ -64,14 +66,19 @@ func (nsu *nodeStatusUpdater) UpdateNodeStatuses() error {
 	nodesToUpdate := nsu.actualStateOfWorld.GetVolumesToReportAttached()
 	for nodeName, attachedVolumes := range nodesToUpdate {
 		nodeObj, err := nsu.nodeLister.Get(string(nodeName))
-		if nodeObj == nil || err != nil {
+		statusErr, isStatusError := err.(*errors.StatusError)
+		if isStatusError && statusErr.Status().Reason == metav1.StatusReasonNotFound {
```
Comment (jingxu97) [inline pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go]: I think you can use error.IsNotFound() to check this

**Review by saad-ali — APPROVED** [review]

**Comment by saad-ali** [comment]
Make sure to fix the release note in your first comment on this page or change the release note label to no release note.

**Comment by verult** [comment]
@k8s-bot pull-kubernetes-kubemark-e2e-gce test this
