### PR TITLE
Fix seccomp PSP docker/default annotation handling

### LINKED ISSUE #95817: PSP seccomp needs annotations 'runtime/default' in 1.19.x
**What happened**:

In k8s 1.19.2

If the seccomp annotations of psp doesn't contain `runtime/default`, pod with seccomp annotations `seccomp.security.alpha.kubernetes.io/pod: 'docker/default` would not start with error:
```
pods "coredns-7b78847794-vzmmz" is forbidden: PodSecurityPolicy: unable to validate pod: [pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/coredns]: 
Forbidden: runtime/default is not an allowed seccomp profile. Valid values are docker/default]'
```

psp with `runtime/default` works
```
metadata:
  name: kube-system-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default, docker/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
```

psp without `runtime/default` doesn't work
```
metadata:
  name: kube-system-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
```

Is this due to https://github.com/kubernetes/kubernetes/pull/90948 ?

**What you expected to happen**:
In k8s 1.18, psp annotations without `runtime/default` works. I think in k8s 1.19, it should also work.

### PR DESCRIPTION
**Pull request by saschagrunert**
**What type of PR is this?**

/kind bug
/kind regression

**What this PR does / why we need it**:

With the graduation of seccomp to GA we automatically convert the deprecated seccomp profile annotation `docker/default` to
`runtime/default`. This means that we now have to automatically allow `runtime/default` if a user specifies `docker/default` and vice versa in an allowed PSP seccomp profile.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/95817

**Special notes for your reviewer**:

Has to be cherry-picked to release-1.19 branch.

**Does this PR introduce a user-facing change?**:

```release-note
Fixed a regression in 1.19 which prevented pods with `docker/default` seccomp annotations from being created in 1.19 if a PodSecurityPolicy was in place which did not allow `runtime/default` seccomp profiles.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
- KEP: https://github.com/kubernetes/enhancements/blob/d80faa7/keps/sig-node/20190717-seccomp-ga.md
```

### CODE REVIEW

File: pkg/security/podsecuritypolicy/seccomp/strategy.go [hunk 1]
```diff
@@ -67,6 +68,17 @@ func NewStrategy(pspAnnotations map[string]string) Strategy {
...
+			// the deprecated seccomp profile annotation `docker/default` to
+			// `runtime/default`. This means that we now have to automatically
+			// allow `runtime/default` if a user specifies `docker/default` and
+			// vice versa in a PSP.
+			if p == v1.DeprecatedSeccompProfileDockerDefault {
+				allowedProfiles[v1.SeccompProfileRuntimeDefault] = true
+			}
+			if p == v1.SeccompProfileRuntimeDefault {
+				allowedProfiles[v1.DeprecatedSeccompProfileDockerDefault] = true
+			}
```
Comment (liggitt) [inline pkg/security/podsecuritypolicy/seccomp/strategy.go:81]: would the meaning be clearer like this?

```suggestion
			if p == v1.DeprecatedSeccompProfileDockerDefault || p == v1.SeccompProfileRuntimeDefault {
				allowedProfiles[v1.SeccompProfileRuntimeDefault] = true
				allowedProfiles[v1.DeprecatedSeccompProfileDockerDefault] = true
			}
```

Comment (saschagrunert) [reply pkg/security/podsecuritypolicy/seccomp/strategy.go]: Probably, changed as suggested :+1:

**Comment by saschagrunert** [comment]
/test pull-kubernetes-node-e2e

```
…
I1029 13:12:03.005]     cluster/gce/gci/mounter
/usr/local/bin/entrypoint.sh: line 31:    17 Killed                  /usr/local/bin/runner.sh ./test-infra/jenkins/bootstrap.py --job="${JOB_NAME}" --service-account="${GOOGLE_APPLICATION_CREDENTIALS}" --upload="${BOOTSTRAP_UPLOAD_BUCKET_PATH}" "$@"
```
