### PR TITLE
Moves the DevicePlugin e2e_node test back to Serial

### LINKED ISSUE #60604: [job flake] kubelet-master
http://k8s-testgrid.appspot.com/sig-release-master-blocking#kubelet

looks like the job has multiple flaky tests :-\

/sig node
/priority failing-test
/kind bug
/status approved-for-milestone

cc @jdumars @jberkus 
@Random-Liu @yguo0905 @dashpole @yujuhong any clue :smirk: ?

### PR DESCRIPTION
**Pull request by jiayingz**
I forgot the fact that the DevicePlugin test itself restarts Kubelet
for testing purpose. Move that test back to Serial but constructs
a smaller test without kubelet restart that we may run during presubmit.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubernetes/issues/60604

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by yujuhong** [comment]
Can you create a separate PR to move the test back to serial first so that we can fix the test jobs?

**Comment by Random-Liu** [comment]
I'll approve first.
/approve.

File: test/e2e_node/device_plugin.go [hunk 1]
```diff
@@ -43,8 +43,56 @@ const (
...
+				node, err := f.ClientSet.CoreV1().Nodes().Get(framework.TestContext.NodeName, metav1.GetOptions{})
+				framework.ExpectNoError(err)
+				return numberOfDevices(node, resourceName)
+			}, 30*time.Second, framework.Poll).Should(Equal(devsLen))
+
+			By("Creating one pod on node with at least one fake-device")
+			podRECMD := "devs=$(ls /tmp/ | egrep '^Dev-[0-9]+$') && echo stub devices: $devs"
+			pod1 := f.PodClient().CreateSync(makeBusyboxPod(resourceName, podRECMD))
+			deviceIDRE := "stub devices: (Dev-[0-9]+)"
+			count1, devId1 := parseLogFromNRuns(f, pod1.Name, pod1.Name, 0, deviceIDRE)
```
Comment (BenTheElder) [inline test/e2e_node/device_plugin.go]: count1 is unused, this is why the jobs are breaking

Comment (jiayingz) [reply test/e2e_node/device_plugin.go]: Good catch! Thanks!

**Comment by yujuhong** [comment]
> Can you create a separate PR to move the test back to serial first so that we can fix the test jobs?

Please create a separate PR for adding the new test. Let's fix the test jobs first.

Also, please add a brief title for your commit.

/hold

**Comment by yujuhong** [comment]
Approved for milestone to fix the tests
