### PR TITLE
Change what is stored in DaemonSet history `.data`

### LINKED ISSUE #47008: Patching DaemonSet history to remove its controller ref always fails
Patching controllerrevision while adopt/orphan failed, because the `.data` field is immutable:

```console
$ kubectl patch controllerrevision newrelic-agent-1-3791983440 -p '{"metadata":{"ownerReferences":[{"$patch":"delete","uid":"4ee3f9c3-4a4c-11e7-8509-6
4510658e388"}],"uid":"4ee48463-4a4c-11e7-8509-64510658e388"}}'
The ControllerRevision "newrelic-agent-1-3791983440" is invalid: data: Invalid value: runtime.Unknown{TypeMeta:runtime.TypeMeta{APIVersion:"", Kind:""}, Raw:[]uint8{0x7b, 0x22, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3a, 0x7b, 0x22, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x3a, 0x6e, 0x75, 0x6c, 0x6c, 0x2c, 0x22, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x3a, 0x7b, 0x22, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x22, 0x6e, 0x65, 0x77, 0x72, 0x65, 0x6c, 0x69, 0x63, 0x22, 0x2c, 0x22, 0x74, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x22, 0x74, 0x65, 0x73, 0x74, 0x31, 0x22, 0x7d, 0x7d, 0x2c, 0x22, 0x73, 0x70, 0x65, 0x63, 0x22, 0x3a, 0x7b, 0x22, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x3a, 0x5b, 0x7b, 0x22, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x3a, 0x22, 0x6e, 0x67, 0x69, 0x6e, 0x78, 0x22, 0x2c, 0x22, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x50, 0x75, 0x6c, 0x6c, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0x3a, 0x22, 0x41, 0x6c, 0x77, 0x61, 0x79, 0x73, 0x22, 0x2c, 0x22, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x22, 0x61, 0x70, 0x70, 0x22, 0x2c, 0x22, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x3a, 0x7b, 0x7d, 0x2c, 0x22, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0x3a, 0x22, 0x2f, 0x64, 0x65, 0x76, 0x2f, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x6c, 0x6f, 0x67, 0x22, 0x2c, 0x22, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0x3a, 0x22, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x7d, 0x5d, 0x2c, 0x22, 0x64, 0x6e, 0x73, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0x3a, 0x22, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x46, 0x69, 0x72, 0x73, 0x74, 0x22, 0x2c, 0x22, 0x72, 0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0x3a, 0x22, 0x41, 0x6c, 0x77, 0x61, 0x79, 0x73, 0x22, 0x2c, 0x22, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x22, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x2d, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x22, 0x2c, 0x22, 0x73, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x3a, 0x7b, 0x7d, 0x2c, 0x22, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x72, 0x61, 0x63, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x22, 0x3a, 0x33, 0x30, 0x7d, 0x7d}, ContentEncoding:"", ContentType:"application/json"}: field is immutable
```

### PR DESCRIPTION
**Pull request by janetkuo**
**What this PR does / why we need it**: 
In DaemonSet history `.data`, store a strategic merge patch that can be applied to restore a DaemonSet. Only PodSpecTemplate is saved. 

This will become consistent with the data stored in StatefulSet history. 

Before this fix, a serialized pod template is stored in `.data`; however, seriazlized pod template isn't a `runtime.RawExtension`, and caused problems when controllers try to patch the history's controller ref. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #47008

**Special notes for your reviewer**: @kubernetes/sig-apps-bugs @erictune @kow3ns @kargakis @lukaszo @mengqiy 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
This is necessary for 1.7 because it ensures the data at rest will be consistent and not have to be updated in a future release (the design for statefulset helped us determine that we wanted to use a patch in the history data, not a full object).

File: pkg/controller/daemon/update.go [hunk 1]
```diff
@@ -295,23 +300,56 @@ func (dsc *DaemonSetsController) controlledHistories(ds *extensions.DaemonSet) (
...
-	err := json.Unmarshal(history.Data.Raw, &template)
-	return &template, err
+// ApplyHistory returns a specific revision of DaemonSet by applying the given history to a copy of the given DaemonSet
+func ApplyHistory(ds *extensions.DaemonSet, history *apps.ControllerRevision) (*extensions.DaemonSet, error) {
+	obj, err := scheme.Scheme.DeepCopy(ds)
+	if err != nil {
+		return nil, err
+	}
+	clone := obj.(*extensions.DaemonSet)
+	patched, err := strategicpatch.StrategicMergePatch([]byte(runtime.EncodeOrDie(patchCodec, clone)), history.Data.Raw, clone)
```
Comment (caesarxuchao) [inline pkg/controller/daemon/update.go]: Do you really need a patchCodec that knows the scheme? It looks like you only need a json encoder.

Comment (caesarxuchao) [inline pkg/controller/daemon/update.go]: (I want to avoid using api.Codecs as much as possible)

File: pkg/controller/daemon/update.go [hunk 2]
```diff
@@ -295,23 +300,56 @@ func (dsc *DaemonSetsController) controlledHistories(ds *extensions.DaemonSet) (
...
+	return clone, nil
 }
 
-func encodeTemplate(template *v1.PodTemplateSpec) ([]byte, error) {
-	return json.Marshal(template)
+// getPatch returns a strategic merge patch that can be applied to restore a Daemonset to a
+// previous version. If the returned error is nil the patch is valid. The current state that we save is just the
+// PodSpecTemplate. We can modify this later to encompass more state (or less) and remain compatible with previously
+// recorded patches.
+func getPatch(ds *extensions.DaemonSet) ([]byte, error) {
```
Comment (caesarxuchao) [inline pkg/controller/daemon/update.go]: Perhaps you can call [CreateTwoWayMergePatch](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go#L94) to create the patch.

File: pkg/controller/daemon/update.go (hunk 1 above)
Comment (janetkuo) [inline pkg/controller/daemon/update.go]: Updated to use `json.Marshal` instead

File: pkg/controller/daemon/update.go (hunk 2 above)
Comment (janetkuo) [inline pkg/controller/daemon/update.go]: This needs to be a replace patch, not a merge patch. We can get a merge patch and manually insert a `$patch: replace` to it, but that's manual too, and doesn't look better than current implementation.

Comment (kow3ns) [inline pkg/controller/daemon/update.go]: +1 CreateTwoWayMergePatch would require us to apply all patches in the history to get to a particular revision.

**Comment by lukaszo** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

File: pkg/controller/daemon/update.go [hunk 3]
```diff
@@ -294,24 +297,66 @@ func (dsc *DaemonSetsController) controlledHistories(ds *extensions.DaemonSet) (
...
+	}
+	return bytes.Equal(patch, history.Data.Raw), nil
 }
 
-func DecodeHistory(history *apps.ControllerRevision) (*v1.PodTemplateSpec, error) {
-	template := v1.PodTemplateSpec{}
-	err := json.Unmarshal(history.Data.Raw, &template)
-	return &template, err
+// ApplyHistory returns a specific revision of DaemonSet by applying the given history to a copy of the given DaemonSet
+func ApplyHistory(ds *extensions.DaemonSet, history *apps.ControllerRevision) (*extensions.DaemonSet, error) {
```
Comment (kargakis) [inline pkg/controller/daemon/update.go]: If this is used by kubectl, it should move in kubectl.

Comment (janetkuo) [inline pkg/controller/daemon/update.go]: Moved to kubectl

**Comment by janetkuo** [comment]
@mengqiy would you review the kubectl part?

**Comment by mengqiy** [comment]
Yes, I will review this soon.

File: pkg/kubectl/history.go [hunk 4]
```diff
@@ -26,17 +27,20 @@ import (
...
 	"k8s.io/kubernetes/pkg/apis/extensions"
+	extensionsv1beta1 "k8s.io/kubernetes/pkg/apis/extensions/v1beta1"
+	externalclientset "k8s.io/kubernetes/pkg/client/clientset_generated/clientset"
 	clientset "k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset"
 	"k8s.io/kubernetes/pkg/controller"
-	"k8s.io/kubernetes/pkg/controller/daemon"
 	deploymentutil "k8s.io/kubernetes/pkg/controller/deployment/util"
 	printersinternal "k8s.io/kubernetes/pkg/printers/internalversion"
 	sliceutil "k8s.io/kubernetes/pkg/util/slice"
+	"k8s.io/metrics/pkg/client/clientset_generated/clientset/scheme"
```
Comment (mengqiy) [inline pkg/kubectl/history.go]: I don't want kubectl to have dependency on this because of the kubectl extraction work.
Please check the comment below about how to get rid of it.

File: pkg/kubectl/history.go [hunk 5]
```diff
@@ -275,7 +278,29 @@ func controlledHistories(c clientset.Interface, ds *extensions.DaemonSet) ([]*ap
 		}
 		result = append(result, &history)
 	}
-	return result, nil
+	return ds, result, nil
+}
+
+// applyHistory returns a specific revision of DaemonSet by applying the given history to a copy of the given DaemonSet
+func applyHistory(ds *extensionsv1beta1.DaemonSet, history *appsv1beta1.ControllerRevision) (*extensionsv1beta1.DaemonSet, error) {
+	obj, err := scheme.Scheme.DeepCopy(ds)
```
Comment (mengqiy) [inline pkg/kubectl/history.go]: You can actually do something like:
```
func applyHistory(...) {
  versionedObj, err := api.Scheme.New(GroupVersionKind)
  dsBytes, err := json.Marshal(ds)
  patched, err := strategicpatch.StrategicMergePatch(dsBytes, history.Data.Raw, versionedObj)
  err = json.Unmarshal(patched, versionedObj)
  return clone, nil
}
```

Comment (janetkuo) [inline pkg/kubectl/history.go]: Replaced `scheme.Scheme.DeepCopy()` with `api.Scheme.New()`

File: pkg/kubectl/history.go (hunk 4 above)
Comment (janetkuo) [inline pkg/kubectl/history.go]: Done

File: pkg/kubectl/history.go [hunk 6]
```diff
@@ -18,6 +18,7 @@ package kubectl
 
 import (
 	"bytes"
+	"encoding/json"
```
Comment (mengqiy) [inline pkg/kubectl/history.go]: Use k8s json please.

**Review by mengqiy — COMMENTED** [review]
Sorry. One last comment. Other LGTM.

File: pkg/kubectl/history.go (hunk 6 above)
Comment (janetkuo) [inline pkg/kubectl/history.go]: Done

**Comment by mengqiy** [comment]
kubectl part LGTM

**Comment by janetkuo** [comment]
Updated bazel

File: pkg/kubectl/rollback.go [hunk 7]
```diff
@@ -249,55 +249,36 @@ func (r *DaemonSetRollbacker) Rollback(obj runtime.Object, updatedAnnotations ma
...
+			return "", err
+		}
 		content := bytes.NewBuffer([]byte{})
 		w := printersinternal.NewPrefixWriter(content)
-		printersinternal.DescribePodTemplate(toTemplate, w)
+		internalTemplate := &api.PodTemplateSpec{}
+		if err := v1.Convert_v1_PodTemplateSpec_To_api_PodTemplateSpec(&appliedDS.Spec.Template, internalTemplate, nil); err != nil {
+			return "", fmt.Errorf("failed to convert podtemplate while printing: %v", err)
+		}
+		printersinternal.DescribePodTemplate(internalTemplate, w)
```
Comment (kargakis) [inline pkg/kubectl/rollback.go]: Do we plan to have versioned describers at some point?

File: pkg/controller/daemon/update.go [hunk 8]
```diff
@@ -294,24 +295,44 @@ func (dsc *DaemonSetsController) controlledHistories(ds *extensions.DaemonSet) (
...
+	}
+	objCopy := make(map[string]interface{})
+	specCopy := make(map[string]interface{})
+
+	// Create a patch of the DaemonSet that replaces spec.template
+	spec := raw["spec"].(map[string]interface{})
+	template := spec["template"].(map[string]interface{})
+	specCopy["template"] = template
+	template["$patch"] = "replace"
+	objCopy["spec"] = specCopy
```
Comment (kargakis) [inline pkg/controller/daemon/update.go]: What else does spec has at this point except template?

File: pkg/controller/daemon/update.go (hunk 2 above)
Comment (kargakis) [inline pkg/controller/daemon/update.go]: Needs a unit test.

File: pkg/controller/daemon/update.go (hunk 8 above)
Comment (janetkuo) [inline pkg/controller/daemon/update.go]: For DaemonSet history we only care about template changes, and when rolling back, we only roll back templates

File: pkg/kubectl/rollback.go (hunk 7 above)
Comment (janetkuo) [inline pkg/kubectl/rollback.go]: I believe so.

**Comment by janetkuo** [comment]
Can someone LGTM this? I'd like to get this in ASAP

**Comment by kargakis** [comment]
/lgtm

Please follow-up with a getPatch unit test

**Comment by janetkuo** [comment]
/assign @pwittrock 

@pwittrock would you approve changes under `hack`? It's adding tests for `kubectl rollout ds` (cannot be tested in test/e2e since rollback is implemented client side).

**Comment by janetkuo** [comment]
Some other PRs depend on this one, and I should be approver of the files changed under `hack/` anyways. Manually applying tag to unblock.
