### PR TITLE
Normalize RepoTags before checking for match

### LINKED ISSUE #52110: 1.8 regression: Can't pull images from docker.io without explicit path on centos/fedora/rhel
https://github.com/kubernetes/kubernetes/pull/51751 bumped the vendored docker library and introduced a regression where pods with images that don't contain an explicit "docker.io/" repo path result in `ErrImagePull` failures.

```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sleep
    - "100"
  terminationGracePeriodSeconds: 0
  restartPolicy: Never
```

Results in the following error:
```
Failed to pull image "busybox": rpc error: code = Unknown desc = no such image: "docker.io/library/busybox:latest"
```

Pod gets `ErrImagePull`

`docker images` shows that the image has been pulled, though not by that name
```
$ docker images | grep busybox
docker.io/busybox                                      latest              d20ae45477cb        2 weeks ago         1.13 MB
```

Changing the image to `docker.io/busybox` in the pod spec corrects the issue.

I think the new code that is changing the behavior is somewhere in here
https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/docker/distribution/reference/normalize.go#L78-L98

`familiarizeName()` is a new function brought in by the bump.

If I checkout the commit before the bump, the problem does not occur.

@derekwaynecarr @DirectXMan12 @dashpole 

related: https://bugzilla.redhat.com/show_bug.cgi?id=1496630

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

on projectatomic-based docker, we get "docker.io/library/busybox:latest"
when someone uses an unqualified name like "busybox". Though when we
inspect, the RepoTag will still say "docker.io/busybox:latest", So
we have reparse the tag, normalize it and try again. Please see the
additional test case.

Signed-off-by: Andy Goldstein <andy.goldstein@gmail.com>

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

Fixes #52110

**Special notes for your reviewer**:

**Release note**:

```release-note
Fixes an issue pulling pod specs referencing unqualified images from docker.io on centos/fedora/rhel
```

### CODE REVIEW

File: pkg/kubelet/dockershim/libdocker/helpers.go [hunk 1]
```diff
@@ -60,6 +60,13 @@ func matchImageTagOrSHA(inspected dockertypes.ImageInspect, image string) bool {
 			// hostname or not, we only check for the suffix match.
 			if strings.HasSuffix(image, tag) || strings.HasSuffix(tag, image) {
 				return true
+			} else {
+				t, _ := dockerref.ParseNormalizedNamed(tag)
```
Comment (liggitt) [inline pkg/kubelet/dockershim/libdocker/helpers.go]: if this returns an error, we should continue, not ignore it

File: pkg/kubelet/dockershim/libdocker/helpers.go [hunk 2]
```diff
@@ -60,6 +60,13 @@ func matchImageTagOrSHA(inspected dockertypes.ImageInspect, image string) bool {
...
+				t2 := t.(dockerref.Tagged)
```
Comment (liggitt) [inline pkg/kubelet/dockershim/libdocker/helpers.go]: check the cast `t2, ok := t.(dockerref.Tagged)` and continue if !ok

File: pkg/kubelet/dockershim/libdocker/helpers.go [hunk 3]
```diff
@@ -60,6 +60,13 @@ func matchImageTagOrSHA(inspected dockertypes.ImageInspect, image string) bool {
...
+				normalizedTag := t2.String()
```
Comment (liggitt) [inline pkg/kubelet/dockershim/libdocker/helpers.go]: if normalizedTag is empty, continue

Comment (dims) [reply pkg/kubelet/dockershim/libdocker/helpers.go]: Done!

File: pkg/kubelet/dockershim/libdocker/helpers.go (hunk 2 above)
Comment (dims) [reply pkg/kubelet/dockershim/libdocker/helpers.go]: Done!

File: pkg/kubelet/dockershim/libdocker/helpers.go (hunk 1 above)
Comment (dims) [reply pkg/kubelet/dockershim/libdocker/helpers.go]: Done

**Comment by liggitt** [comment]
this LGTM, manually building/verifying now

**Comment by liggitt** [comment]
cc @miminar

**Comment by dims** [comment]
Duh, needed to fix gofmt

**Comment by Random-Liu** [comment]
Please add comment to explain why we are doing this, and link to corresponding K8s issue. I'm worried that we may forget why we are doing this in the future.

And we should also fix docker on centos to properly return image reference so as to get rid of this hack.

**Comment by dims** [comment]
@Random-Liu where in the commit message itself?

**Comment by Random-Liu** [comment]
@dims I mean in the code.

File: pkg/kubelet/dockershim/libdocker/helpers.go [hunk 4]
```diff
@@ -60,6 +60,22 @@ func matchImageTagOrSHA(inspected dockertypes.ImageInspect, image string) bool {
 			// hostname or not, we only check for the suffix match.
 			if strings.HasSuffix(image, tag) || strings.HasSuffix(tag, image) {
 				return true
+			} else {
+				t, err := dockerref.ParseNormalizedNamed(tag)
```
Comment (yujuhong) [inline pkg/kubelet/dockershim/libdocker/helpers.go]: Add a comment explaining what this code is doing and a TODO to remove the workaround after docker is fixed properly with a link to the issue.

Comment (liggitt) [reply pkg/kubelet/dockershim/libdocker/helpers.go]: actually, a follow up issue to do better-normalized comparisons in all cases would be good.. the existing prefix checks don't look generally correct to me

**Comment by liggitt** [comment]
verified on fedora 25 with docker 1.12.6-7 and all of the following pulled and ran as expected:
```
kubectl run --image busybox foo
kubectl run --image busybox:latest foo2
kubectl run --image docker.io/busybox foo3
kubectl run --image docker.io/busybox:latest foo4
kubectl run --image docker.io/library/busybox:latest foo5
kubectl run --image docker.io/library/busybox foo6
```

@derekwaynecarr @ncdc you have a 1.13.1 you want to test on?

**Comment by derekwaynecarr** [comment]
let me pull and check

**Comment by dims** [comment]
@derekwaynecarr @liggitt something with SHA too?

File: pkg/kubelet/dockershim/libdocker/helpers.go (hunk 4 above)
Comment (dims) [reply pkg/kubelet/dockershim/libdocker/helpers.go]: @liggitt yes, hoping @ncdc would be able to help with that. This is his PR effectively :)

**Comment by derekwaynecarr** [comment]
@runcom -- please see the issue in description.

**Comment by liggitt** [comment]
TestDevicePluginReRegistration flake
/retest

**Comment by derekwaynecarr** [comment]
I tested on Fedora 26

```
Installed Packages
docker-latest.x86_64                                                                               2:1.13-32.git27e468e.fc26          
```

```
$ docker info
Containers: 14
 Running: 6
 Paused: 0
 Stopped: 8
Images: 7
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: oci runc
Default Runtime: oci
Init Binary: /usr/libexec/docker/docker-init-latest
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker-latest/seccomp.json
 selinux
Kernel Version: 4.12.13-300.fc26.x86_64
Operating System: Fedora 26 (Workstation Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 19.48 GiB
Name: localhost.localdomain
ID: VP7V:3UZE:VKXX:UVWE:4M43:2MLI:E72F:4KIE:KC45:GEWG:RXRP:RCUX
Docker Root Dir: /var/lib/docker-latest
Debug Mode (client): false
Debug Mode (server): false
Username: derekwaynecarr
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
```

verified the following works as expected after this fix:

```
$ kubectl run -i -t busybox --image=busybox --restart=Never
```

File: pkg/kubelet/dockershim/libdocker/helpers.go [hunk 5]
```diff
@@ -60,6 +60,38 @@ func matchImageTagOrSHA(inspected dockertypes.ImageInspect, image string) bool {
 			// hostname or not, we only check for the suffix match.
 			if strings.HasSuffix(image, tag) || strings.HasSuffix(tag, image) {
 				return true
+			} else {
+				// TODO: We need to remove this hack when project atomic based
+				// docker distro(s) like  centos/fedora/rhel image fix problems on
```
Comment (Random-Liu) [inline pkg/kubelet/dockershim/libdocker/helpers.go]: double space.

**Comment by Random-Liu** [comment]
LGTM with one nit.

File: pkg/kubelet/dockershim/libdocker/helpers.go (hunk 5 above)
Comment (dims) [reply pkg/kubelet/dockershim/libdocker/helpers.go]: Thanks fixed.

**Comment by ncdc** [comment]
@dims thanks for carrying this forward

**Comment by sjenning** [comment]
verified fix CentOS 7.4.1708
```
# cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)
# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-55.gitc4618fb.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      c4618fb/1.12.6
 Built:           Thu Sep 21 22:33:52 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-55.gitc4618fb.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      c4618fb/1.12.6
 Built:           Thu Sep 21 22:33:52 2017
 OS/Arch:         linux/amd64
```
