### PR TITLE
ignore pods that are failed but controlled by a rc when start e2e tests

### LINKED ISSUE #10897: Cluster health check sometimes fails due to failed kibana-logging pods (Ginkgo timed out waiting for all parallel nodes to report back! )
On a healthy test cluster the health check looks like this:

```
2015/07/07 16:55:50 Running: Ginkgo tests
Setting up for KUBERNETES_PROVIDER="gce".
Project: kubernetes-jenkins-pull
Zone: us-central1-f
Running Suite: Kubernetes e2e suite
===================================
Random Seed: 1436313351 - Will randomize all specs
Will run 50 of 95 specs

Running in parallel across 15 nodes

P [PENDING]
Namespaces
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/namespace.go:119
  Delete ALL of 100 namespace in 150 seconds
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/namespace.go:118
------------------------------
SSSSSSSSS
------------------------------
[BeforeEach] Events
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/events.go:42
>>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace@4/.kube/config
[It] should be sent by kubelets and the scheduler about pods scheduling and running
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/events.go:134
STEP: creating the pod
```

On a failed cluster it looks like this:

```
2015/07/07 16:05:17 Running: Ginkgo tests
Setting up for KUBERNETES_PROVIDER="gce".
Project: kubernetes-jenkins-pull
Zone: us-central1-f

	 -------------------------------------------------------------------
	|                                                                   |
	|  Ginkgo timed out waiting for all parallel nodes to report back!  |
	|                                                                   |
	 -------------------------------------------------------------------

[1] >>> testContext.KubeConfig: /var/lib/jenkins/jobs/kubernetes-pull-build-test-e2e-gce/workspace@3/.kube/config
[1] INFO: Waiting up to 10m0s for all pods (need at least 0) in namespace 'kube-system' to be running and ready
[1] INFO: 9 / 60 pods in namespace 'kube-system' are running and ready (5 seconds elapsed)
[1] INFO: POD                      NODE                    PHASE   CONDITIONS
[1] INFO: kibana-logging-v1-0bgli  pull-e2e-2-minion-row7  Failed  []
[1] INFO: kibana-logging-v1-0ztda  pull-e2e-2-minion-row7  Failed  []
[1] INFO: kibana-logging-v1-2n6cv  pull-e2e-2-minion-row7  Failed  []

...

[15] INFO: 9 / 60 pods in namespace 'kube-system' are running and ready (600 seconds elapsed)
[15] INFO: POD                      NODE                    PHASE   CONDITIONS
[15] INFO: kibana-logging-v1-0bgli  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-0ztda  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-2n6cv  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-2wnx4  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-4zkhd  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-599zc  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-62j8f  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-62k1d  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-671fn  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-6g5ew  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-6vkj5  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-79z69  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-83ei9  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-8q9tq  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-8u2k6  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-9ayut  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-a0q9i  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-atxh9  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-bjj33  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-c7fxx  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-cof2b  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-d6dq9  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-dgwbv  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-e2cp7  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-fe6y5  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-glu1n  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-h0p4m  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-hs5ra  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-lnqdn  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-milbq  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-n9ltt  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-o0gt6  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-os70f  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-q20uk  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-rn2gl  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-sy69f  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-tg0tx  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-ti807  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-tqw6l  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-tt2dk  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-tya5y  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-u7pg7  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-uc4pp  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-uj1hv  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-uwt94  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-uy11c  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-va7dp  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-vo1sb  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-wxevp  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-x9vgd  pull-e2e-2-minion-row7  Failed  []
[15] INFO: kibana-logging-v1-zz91y  pull-e2e-2-minion-row7  Failed  []
```

### PR DESCRIPTION
**Pull request by caesarxuchao**
Put the statement in the title in another way, waitForPodsRunningReady() only checks the following 3 conditions:
(1) all pods are either "Running and Ready" or "Failed";
(2) the number or "Running and Ready" pods created by replication controllers are correct (replicaOk == replicas);
(3) All Failed pods are controlled by a replication controller.

fixes #10897

@quinton-hoole

### CODE REVIEW

**Comment by quinton-hoole** [comment]
LGTM!  ok-to-merge as soon as Jenkins GCE e2e passes.
Thanks @caesarxuchao 
Shippable is a flake - can be ignored, as this PR is purely e2e test code, which is not exercised by Shippable.

File: test/e2e/util.go [hunk 1]
```diff
@@ -281,11 +281,24 @@ func podRunningReady(p *api.Pod) (bool, error) {
 	return true, nil
 }
 
+// check if a Pod is controlled by a Replication Controller in the List
+func hasReplicationControllersForPod(rcs *api.ReplicationControllerList, pod api.Pod) bool {
+	for i, rc := range rcs.Items {
```
Comment (quinton-hoole) [inline test/e2e/util.go]: i is declared but not used.

**Comment by quinton-hoole** [comment]
Some compile errors: _output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/util.go:287: i declared and not used

**Comment by quinton-hoole** [comment]
@caesarxuchao you can ask k8s-bot to compile and test again once you've fixed compile errors.

File: test/e2e/util.go (hunk 1 above)
Comment (caesarxuchao) [inline test/e2e/util.go]: ah.. I tested it on e2e but then removed some Logf() and forgot about this..

**Comment by caesarxuchao** [comment]
@k8s-bot test this please

**Comment by quinton-hoole** [comment]
ok-to-merge

**Comment by quinton-hoole** [comment]
Fixes #10897
