### PR TITLE
dra: increase timeout in setupFakeDRADriverGRPCServer to prevent tests to flake

### LINKED ISSUE #121710: UT pkg/kubelet/cm/dra TestUnprepareResources/should_timeout flaking with stable golang version and Kubernetes master
### Which jobs are flaking?

[Failed-dra-test](https://prow.ppc64le-cloud.cis.ibm.net/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le/1720199237293051904)

### Which tests are flaking?

test ```TestUnprepareResources/should_timeout```

### Since when has it been flaking?

Since Oct 25th

### Testgrid link

_No response_

### Reason for failure (if possible)

stack trace:

```
{Failed;Failed;  === RUN   TestUnprepareResources/should_timeout
I1102 22:20:03.622379   47650 plugin.go:106] "Register new DRA plugin" name="test-cdi-device" endpoint="/tmp/dra608345482/server.sock"
    manager_test.go:1083: 
        	Error Trace:	/home/prow/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/cm/dra/manager_test.go:1083
        	Error:      	An error is expected but got nil.
        	Test:       	TestUnprepareResources/should_timeout
I1102 22:20:48.683925   47650 plugin.go:179] "DeRegister DRA plugin" name="test-cdi-device"
    --- FAIL: TestUnprepareResources/should_timeout (45.07s)
;=== RUN   TestUnprepareResources
--- FAIL: TestUnprepareResources (45.09s)
;}
```

### Anything else we need to know?

Test has been flaking with master golang as well.

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by tmilox**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

When running tests for the dynamic ressource allocation manager, a fake gRPC server is setup and in some cases a timeout greater than the default client timeout is used to ensure that when preparing/unpreparing ressources take longer than the default timeout an error is correctly raised.
A fix has already been merged aiming to fix #121710. However when the CI is doing some heavy lifting the additional 30ms used to test the timeout isn't enough as reported [here](https://github.com/kubernetes/kubernetes/pull/121774#issuecomment-1886259309).

#### Which issue(s) this PR fixes:

Fixes #121710

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by TommyStarK** [comment]
@charles-chenzz @bart0sh IMHO this test is flaky since too long. It seems when the CI is busy the 30ms timeout we used isn't enough. I increased it to one second hoping that now we shouldn't have any issues.

File: pkg/kubelet/cm/dra/manager_test.go [hunk 1]
```diff
@@ -117,7 +117,7 @@ func setupFakeDRADriverGRPCServer(shouldTimeout bool) (fakeDRAServerInfo, error)
 		driverName: driverName,
 	}
 	if shouldTimeout {
-		timeout := plugin.PluginClientTimeout + 30*time.Millisecond
+		timeout := plugin.PluginClientTimeout + time.Second
```
Comment (bart0sh) [inline pkg/kubelet/cm/dra/manager_test.go:120]: @TommyStarK Thank you for the PR! 
Just wondering if we can increase plugin.PluginClientTimeout instead of this. Can you remind me what was an initial purpose of using hardcoded addition?

**Comment by bart0sh** [comment]
@TommyStarK Can you provide a testgrid link to the failing CI ?

**Comment by TommyStarK** [comment]
> @TommyStarK Can you provide a testgrid link to the failing CI ?

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1745328588804067328

File: pkg/kubelet/cm/dra/manager_test.go (hunk 1 above)
Comment (charles-chenzz) [reply pkg/kubelet/cm/dra/manager_test.go:120]: I can't recall that we have consensus that hardcoded this. we were first setup a wrong testcase then @TommyStarK  address the wrong test case and start using this hardcoded to setup fake grpc server. That's all I can get in my mind

Comment (TommyStarK) [reply pkg/kubelet/cm/dra/manager_test.go:120]: If I recall correctly Kevin increased the hardcoded value because he experienced some timeouts. Here is the link towards his comment https://github.com/kubernetes/kubernetes/issues/117146

Comment (bart0sh) [reply pkg/kubelet/cm/dra/manager_test.go:120]: I'm still not sure I fully understand the purpose of additional hardcoded value. Is this something specific to the test? Where the delay comes from when the test is run in CI? If grpc calls take more time then we should increase `plugin.PluginClientTimeout`.

Comment (TommyStarK) [reply pkg/kubelet/cm/dra/manager_test.go:120]: me either, let's wait @klueska for having a better understanding

Comment (liggitt) [reply pkg/kubelet/cm/dra/manager_test.go:120]: this is trying to make the server take *just* over the length of time the client will wait before timing out. However, that is accomplished via a context with a deadline, which is not guaranteed to cancel at *precisely* the deadline... in a busy CI env the context cancel might happen quite a bit later than the deadline.

Timeout coordination at the millisecond level is not reliable in often-underresourced CI environments.

Expanding this to a second is a good short-term fix to stabilize this test (this is also flaking in 1.29 and 1.28 release branch runs and should be picked back).

**Comment by liggitt** [comment]
/lgtm
/approve

please open picks to release-1.29 and release-1.28
