### PR TITLE
Escape special characters in jsonpath field names.

### LINKED ISSUE #31984: Cannot select annotation key using jsonpath
I love using `kubectl ... -o jsonpath` but I cannot figure out how to print an annotation that contains a special character like `-` or `/` or `.`.  

This does not work:
`kubectl get pods tmp -o 'jsonpath={.metadata.annotations.kubernetes.io/created-by}{"\n"}'`
nor this:
`kubectl get pods tmp -o 'jsonpath={.metadata.annotations.kubernetes\.io\/created\-by}{"\n"}'`
nor this:
`kubectl get pods tmp -o 'jsonpath={.metadata.annotations}{["kubernetes.io/created-by"]}{"\n"}'`
nor this:
kubectl get pods tmp-1986694738-dhpx0 -o jsonpath="{\$['metadata']['annotations']['kubernetes.io/created-by']}"
(the last one should work according to what I can find about jsonPath, but doesn't, and anyhow is hard to get shell escaping right for.

  Need a way to quote a

### PR DESCRIPTION
**Pull request by jmcarp**
There may be a better way to do this, but this seemed like the simplest possible version.

Example: `{.items[*].metadata.labels.kubernetes\.io/hostname}`

[Resolves #31984]

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33901)

### CODE REVIEW

File: pkg/util/jsonpath/parser.go [hunk 1]
```diff
@@ -382,19 +382,21 @@ Loop:
 // parseField scans a field until a terminator
 func (p *Parser) parseField(cur *ListNode) error {
 	p.consumeText()
-	var r rune
+Loop:
 	for {
-		r = p.next()
-		if isTerminator(r) {
+		switch r := p.next(); {
```
Comment (brendandburns) [inline pkg/util/jsonpath/parser.go]: rather than do the labelled breaking, I'd introduce a new helper function:

```go
func advance(p *Parser) bool {
  switch r := p.next(); {
     ...
  }
}

...
for advance(p) {}
...
```

Comment (jmcarp) [inline pkg/util/jsonpath/parser.go]: Sounds good, made the change.

**Comment by brendandburns** [comment]
/lgtm

@k8s-bot ok to test.

**Comment by jmcarp** [comment]
@brendandburns: I see that the submit queue status check is still pending, but I don't see this PR in the queue at http://submit-queue.k8s.io/#/queue?prDisplay=33901&historyDisplay=33901. Do I need to do anything to get tests to run? Thanks!

**Comment by brendandburns** [comment]
@k8s-bot ok to test

**Comment by brendandburns** [comment]
@jmcarp sorry, I guess the bot doesn't like it when it's comment isn't the first thing on a line...

tests running now.

**Comment by brendandburns** [comment]
@k8s-bot verification test this Issue: IGNORE

There are no failures that I can see...

**Comment by jmcarp** [comment]
I took another look at the build output, and it looks like I just had to run `gofmt`. @brendandburns: if you can get the k8s bot to re-run tests, hopefully they'll pass this time!

**Comment by brendandburns** [comment]
Tests are green, LGTM!

**Comment by fejta** [comment]
@k8s-bot verify test this
