### PR TITLE
fix pod template spec validation missing in sts

### LINKED ISSUE #131761: topologySpreadConstraints are not correctly applied on StatefulSets
### What happened?

I'm using AWS EKS 1.31. I was doing some tests with `topologySpreadConstraints` and I've noticed that the API Server behaves differently on `Deployments` and `StatefulSets` objects.

Using this `test.yaml` YAML file:
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-without-enough-replicas-2
spec:
  selector:
    matchLabels:
      app: test
  replicas: 3
  template:
    metadata:
      labels:
        app: test
    spec:
      topologySpreadConstraints:
        - topologyKey: topology.kubernetes.io/zone
          # commented on purpose to trigger a failure
          # whenUnsatisfiable: DoNotSchedule
          maxSkew: 1
          labelSelector:
            matchLabels:
              app: test
      containers:
      - name: echo-server-container
        image: alpine
        command: ["sleep", "3600"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-without-enough-replicas-2
spec:
  selector:
    matchLabels:
      app: test
  replicas: 3
  template:
    metadata:
      labels:
        app: test
    spec:
      topologySpreadConstraints:
        - topologyKey: topology.kubernetes.io/zone
          # commented on purpose to trigger a failure
          # whenUnsatisfiable: DoNotSchedule
          maxSkew: 1
          labelSelector:
            matchLabels:
              app: test
      containers:
      - name: echo-server-container
        image: alpine
        command: ["sleep", "3600"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
```

When applied, I get a different response from both:
```bash
$ kubectl apply -f test.yaml
statefulset.apps/statefulset-without-enough-replicas-2 created
The Deployment "deployment-without-enough-replicas-2" is invalid: spec.template.spec.topologySpreadConstraints[0].whenUnsatisfiable: Unsupported value: "": supported values: "DoNotSchedule", "ScheduleAnyway"
```

After this, the `Deployment` has been rejected, as the fields are missing (correct), but the `StatefulSet` is accepted and unable to schedule pods, because `whenUnsatisfiable` field is missing:
```
Events:
  Type     Reason           Age                  From                    Message
  ----     ------           ----                 ----                    -------
  Warning  FailedCreate     41s (x15 over 2m3s)  statefulset-controller  create Pod statefulset-without-enough-replicas-2-0 in StatefulSet statefulset-without-enough-replicas-2 failed error: Pod "statefulset-without-enough-replicas-2-0" is invalid: spec.topologySpreadConstraints[0].whenUnsatisfiable: Unsupported value: "": supported values: "DoNotSchedule", "ScheduleAnyway"
```

### What did you expect to happen?

I expect the validation should behave similarly in both resources, rejecting the resource which lacks of required fields.

### How can we reproduce it (as minimally and precisely as possible)?

Apply this YAML file:
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-without-enough-replicas-2
spec:
  selector:
    matchLabels:
      app: test
  replicas: 3
  template:
    metadata:
      labels:
        app: test
    spec:
      topologySpreadConstraints:
        - topologyKey: topology.kubernetes.io/zone
          # commented on purpose to trigger a failure
          # whenUnsatisfiable: DoNotSchedule
          maxSkew: 1
          labelSelector:
            matchLabels:
              app: test
      containers:
      - name: echo-server-container
        image: alpine
        command: ["sleep", "3600"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-without-enough-replicas-2
spec:
  selector:
    matchLabels:
      app: test
  replicas: 3
  template:
    metadata:
      labels:
        app: test
    spec:
      topologySpreadConstraints:
        - topologyKey: topology.kubernetes.io/zone
          # commented on purpose to trigger a failure
          # whenUnsatisfiable: DoNotSchedule
          maxSkew: 1
          labelSelector:
            matchLabels:
              app: test
      containers:
      - name: echo-server-container
        image: alpine
        command: ["sleep", "3600"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.7
Kustomize Version: v5.5.0
Server Version: v1.31.7-eks-4096722
```

</details>

### Cloud provider

<details>
AWS EKS
</details>

### Install tools

_No response_

### Container runtime (CRI) and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by chengjoey**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
add pod spec validation for create sts

#### Which issue(s) this PR fixes:

Fixes #131761 #112609

#### Does this PR introduce a user-facing change?

```release-note
add podSpec validation for create StatefulSet
```

### CODE REVIEW

**Comment by adrianmoisey** [comment]
The failed tests seems to need fixing

**Comment by chengjoey** [comment]
> The failed tests seems to need fixing

done

File: pkg/apis/apps/validation/validation.go [hunk 1]
```diff
@@ -63,10 +63,8 @@ func ValidatePodTemplateSpecForStatefulSet(template *api.PodTemplateSpec, select
 				allErrs = append(allErrs, field.Invalid(fldPath.Child("metadata", "labels"), template.Labels, "`selector` does not match template `labels`"))
 			}
 		}
-		// TODO: Add validation for PodSpec, currently this will check volumes, which we know will
-		// fail. We should really check that the union of the given volumes and volumeClaims match
-		// volume mounts in the containers.
-		// allErrs = append(allErrs, apivalidation.ValidatePodTemplateSpec(template, fldPath)...)
+		// TODO: Add validation for PodSpec containers volumeMounts if volumeClaimTemplates are defined
+		allErrs = append(allErrs, apivalidation.ValidatePodTemplateSpec(template, fldPath, opts)...)
```
Comment (liggitt) [inline pkg/apis/apps/validation/validation.go]: Tightening validation here can only be done conditionally... we have to tolerate updates to existing statefulset objects that wouldn't pass this validation

I think that looks like:
1. adding an `SkipValidatePodTemplateSpec bool` option to `StatefulSetValidationOptions`
2. plumbing that from ValidateStatefulSetSpec down into this function
3. calling this line if and only if setOpts.SkipValidatePodTemplateSpec is false
4. in ValidateStatefulSet (for create), set SkipValidatePodTemplateSpec to false. in ValidateStatefulSetUpdate (for update), set SkipValidatePodTemplateSpec to true if and only if oldStatefulSet fails ValidatePodTemplateSpec

File: pkg/apis/core/validation/validation.go [hunk 2]
```diff
@@ -2928,6 +2928,9 @@ func ValidateVolumeMounts(mounts []core.VolumeMount, voldevices map[string]strin
 		if len(mnt.Name) == 0 {
 			allErrs = append(allErrs, field.Required(idxPath.Child("name"), ""))
 		}
+		if opts.AllowVolumeNotFoundInVolumeMounts && !IsMatchedVolume(mnt.Name, volumes) {
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go]: is there a way to avoid skipping this validation by having statefulset validation modify a temporary copy of the pod template spec being validated in the same way the controller will to inject the volumes that will be constructed?

sort of like  https://github.com/kubernetes/kubernetes/blob/ced19ffab59fdc346318d1d0152581a1f213c711/pkg/controller/statefulset/stateful_set_utils.go#L411-L435

File: pkg/apis/apps/validation/validation.go (hunk 1 above)
Comment (chengjoey) [reply pkg/apis/apps/validation/validation.go]: done

I got it, we should only validate the creation of sts, and tolerate the existing.

File: pkg/apis/core/validation/validation.go (hunk 2 above)
Comment (chengjoey) [reply pkg/apis/core/validation/validation.go]: done

File: pkg/apis/core/validation/validation.go [hunk 3]
```diff
@@ -4121,6 +4121,8 @@ type PodValidationOptions struct {
 	OldPodViolatesMatchLabelKeysValidation bool
 	// OldPod has invalid MatchLabelKeys in TopologySpreadConstraints against legacy(<v1.34) validation
 	OldPodViolatesLegacyMatchLabelKeysValidation bool
+	// Skip validating pod template spec, specifically for StatefulSet.
+	SkipValidatePodTemplateSpec bool
```
Comment (liggitt) [inline pkg/apis/core/validation/validation.go]: move this into the StatefulSetValidationOptions type, and plumb that options instance into ValidatePodTemplateSpecForStatefulSet where it is needed

File: pkg/apis/apps/validation/validation.go [hunk 4]
```diff
@@ -94,6 +94,49 @@ func ValidatePersistentVolumeClaimRetentionPolicy(policy *apps.StatefulSetPersis
...
+	}
+	for i := range currentVolumes {
+		if _, ok := claims[currentVolumes[i].Name]; !ok {
+			newVolumes = append(newVolumes, currentVolumes[i])
+		}
+	}
+	spec.Template.Spec.Volumes = newVolumes
+}
+
+func getPersistentVolumeClaims(spec *apps.StatefulSetSpec) map[string]api.PersistentVolumeClaim {
```
Comment (liggitt) [inline pkg/apis/apps/validation/validation.go]: I *think* we just need to return `[]string` with the claim names to add the volumes to the pod spec like we need to

File: pkg/apis/apps/validation/validation.go [hunk 5]
```diff
@@ -193,6 +238,9 @@ func ValidateStatefulSetUpdate(statefulSet, oldStatefulSet *apps.StatefulSet, op
 	setOpts := StatefulSetValidationOptions{
 		AllowInvalidServiceName: true, // serviceName is immutable, tolerate existing invalid names on update
 	}
+	// In order to tolerate the existing sts, we choose to skip the validation error of podTemplateSpec.
+	// TODO: pod template spec validation for statefulset update
+	opts.SkipValidatePodTemplateSpec = true
```
Comment (liggitt) [inline pkg/apis/apps/validation/validation.go]: this should look more like `if len(ValidateStatefulSetSpec(&oldStatefulSet.Spec, nil, opts, setOpts)) > 0 { opts.SkipValidatePodTemplateSpec = true }` so we only relax validation on update for things which already fail spec validation

File: pkg/apis/apps/validation/validation.go [hunk 6]
```diff
@@ -158,6 +201,8 @@ func ValidateStatefulSetSpec(spec *apps.StatefulSetSpec, fldPath *field.Path, op
 	if err != nil {
 		allErrs = append(allErrs, field.Invalid(fldPath.Child("selector"), spec.Selector, ""))
 	} else {
+		// update the template's volumes to include the volumes from the volumeClaimTemplates
+		updateStorageForStatefulSet(spec)
```
Comment (liggitt) [inline pkg/apis/apps/validation/validation.go]: don't mutate this in place ... _if_ we need to add in volumes for validation purposes to match what will get auto-added by the controller, do that by assigning to a new variable, deep-copying, and appending the fewest new volumes we need, something like this:

```go
templateToValidate := &spec.Template
if volumesToAddForTemplates(spec); len(volumesToAddForTemplates) > 0 {
  templateToValidate = templateToValidate.DeepCopy()
  templateToValidate.Spec.Volumes = append(templateToValidate.Spec.Volumes, ...)
}
allErrs = append(allErrs, ValidatePodTemplateSpecForStatefulSet(templateToValidate, selector, fldPath.Child("template"), opts)...)
```

Comment (chengjoey) [reply pkg/apis/apps/validation/validation.go]: done, and add some test cases for update

File: pkg/apis/apps/validation/validation.go [hunk 7]
```diff
@@ -63,10 +66,10 @@ func ValidatePodTemplateSpecForStatefulSet(template *api.PodTemplateSpec, select
 				allErrs = append(allErrs, field.Invalid(fldPath.Child("metadata", "labels"), template.Labels, "`selector` does not match template `labels`"))
 			}
 		}
-		// TODO: Add validation for PodSpec, currently this will check volumes, which we know will
-		// fail. We should really check that the union of the given volumes and volumeClaims match
-		// volume mounts in the containers.
-		// allErrs = append(allErrs, apivalidation.ValidatePodTemplateSpec(template, fldPath)...)
+		podSpecErrs := apivalidation.ValidatePodTemplateSpec(template, fldPath, opts)
+		if len(podSpecErrs) > 0 && !setOpts.SkipValidatePodTemplateSpec {
+			allErrs = append(allErrs, podSpecErrs...)
```
Comment (liggitt) [inline pkg/apis/apps/validation/validation.go]: check the boolean first to avoid doing work we'll throw away

```suggestion
		if !setOpts.SkipValidatePodTemplateSpec {
			allErrs = append(allErrs, apivalidation.ValidatePodTemplateSpec(template, fldPath, opts)...)
```

File: pkg/apis/apps/validation/validation.go [hunk 8]
```diff
@@ -94,6 +97,25 @@ func ValidatePersistentVolumeClaimRetentionPolicy(policy *apps.StatefulSetPersis
...
 }
 
+func volumesToAddForTemplates(spec *apps.StatefulSetSpec) []api.Volume {
+	if len(spec.VolumeClaimTemplates) == 0 {
+		return nil
+	}
+	newVolumes := make([]api.Volume, 0, len(spec.VolumeClaimTemplates))
+	for i := range spec.VolumeClaimTemplates {
+		claimName := spec.VolumeClaimTemplates[i].Name
+		newVolumes = append(newVolumes, api.Volume{
```
Comment (liggitt) [inline pkg/apis/apps/validation/validation.go]: This will incorrectly return volumes that overlap with already-present volumes in the pod spec

If the pod already defines volumes a,b,c, and the volumeClaimTemplates define c,d,e, this should just return []{d,e}. Otherwise, when we append, `c` will be duplicated and fail validation.

Add a unit test checking that scenario.

Comment (chengjoey) [reply pkg/apis/apps/validation/validation.go]: done

File: pkg/apis/apps/validation/validation.go [hunk 9]
```diff
@@ -158,7 +186,12 @@ func ValidateStatefulSetSpec(spec *apps.StatefulSetSpec, fldPath *field.Path, op
 	if err != nil {
 		allErrs = append(allErrs, field.Invalid(fldPath.Child("selector"), spec.Selector, ""))
 	} else {
-		allErrs = append(allErrs, ValidatePodTemplateSpecForStatefulSet(&spec.Template, selector, fldPath.Child("template"), opts)...)
+		templateToValidate := &spec.Template
+		if newVolumes := volumesToAddForTemplates(spec); len(newVolumes) > 0 {
```
Comment (liggitt) [inline pkg/apis/apps/validation/validation.go]: This looks really close. Thinking through some edge cases in ways that weird statefulsets could actually have worked previously, there's a few more scenarios:

1. user sets spec.template.spec.hostname to something invalid, gets overwritten by pod.Name in `initIdentity`, sts pods actually work
2. user sets spec.template.spec.subdomain to something invalid, gets overwritten by spec.ServiceName in `initIdentity`, sts pods actually work
3. user sets duplicate volume name definitions in the pod spec that overlap with volume template names, those get dropped in favor of the injected PVC volumes in `updateStorage`, sts pods actually work
4. user sets invalid volume definitions in the pod spec (for example, ones that define multiple volume sources) with names that overlap with volume template names, those get dropped in favor of the injected PVC volumes in `updateStorage`, sts pods actually work

That means we'll have to tweak this mutation for validation to be something like this:
```
templateToValidate := &spec.Template
if len(spec.Template.Spec.Subdomain) > 0 || len(spec.Template.Spec.Hostname) > 0 || len(spec.VolumeClaimTemplates) > 0 {
  templateToValidate = templateToValidate.DeepCopy()
  templateToValidate.Spec.Subdomain = "" // overwritten by controller to spec.ServiceName in initIdentity, don't validate
  templateToValidate.Spec.Hostname = "" // overwritten by controller to pod.Name in initIdentity, don't validate

  templateVolumes := volumesToAddForTemplates(spec)
  volumes := []api.Volume{}
  for _, v := range templateToValidate.Spec.Volumes {
    if _, ok := templateVolumes[v.Name]; !ok {
      // match controller behavior in updateStorage, drop volumes that overlap with template-defined volumes
      volumes = append(volumes, v)
    }
  }
  for _, v := range templateVolumes {
    volumes = append(volumes, v)
  }
  templateToValidate.Spec.Volumes = volumes
}
```

Make sure there's unit tests for those scenarios since they currently produce working statefulsets / statefulset pods, and need to make sure those continue to pass create validation.

File: pkg/apis/apps/validation/validation.go [hunk 10]
```diff
@@ -94,6 +96,32 @@ func ValidatePersistentVolumeClaimRetentionPolicy(policy *apps.StatefulSetPersis
 	return allErrs
 }
 
+func volumesToAddForTemplates(spec *apps.StatefulSetSpec) []api.Volume {
```
Comment (liggitt) [inline pkg/apis/apps/validation/validation.go]: See below comment, I think this needs to return volumes for all the VolumeClaimTemplates, and returning a map[name]volume will make it easier to use in the loop below

```suggestion
func volumesToAddForTemplates(spec *apps.StatefulSetSpec) map[string]api.Volume {
```

File: pkg/apis/apps/validation/validation.go (hunk 9 above)
Comment (chengjoey) [reply pkg/apis/apps/validation/validation.go]: done ,add some test cases(subdomain,hostname,volumes) for sts update/create

**Comment by liggitt** [comment]
/lgtm
/approve

Thanks for the improvement here and the tests!
