### PR TITLE
kubelet/network: report but tolerate errors returned from GetNetNS() v2

### LINKED ISSUE #42735: Kubelet CNI nsenter failure
**Kubernetes version** (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: Bare metal
- **OS** (e.g. from /etc/os-release): Ubuntu precise (12.04.4 LTS)
- **Kernel** (e.g. `uname -a`): 3.13.0-55-generic
- **Install tools**: N/A
- **Others**: N/A

**What happened**:

During an otherwise-normal rollingupdate for a replication controller, we see this error in the logs:

```
E0307 21:43:51.235958    3650 docker_manager.go:373] NetworkPlugin cni failed on the status hook for pod 'foo-r3rg5' - Unexpected command output nsenter: cannot open /proc/5875/ns/net: No such file or directory\n with error: exit status 1
```

**What you expected to happen**:

Expected that successful rollingupdate wouldn't generate error-level logs without an error-level problem -- trying to determine what the error-level problem is.

**How to reproduce it** (as minimally and precisely as possible):

During our prod upgrade of various services, this occurred during 3 out of 70 rollingupdates.

**Anything else we need to know**:

Perhaps this is the same general issue as #25281? But I couldn't find any references to the "Unexpected command output nsenter" variation seen above, thus filing separately.

### LINKED ISSUE #44307: Pods with hostNetwork=true cannot be removed (and generate errors) when using CNI
**Kubernetes version** (use `kubectl version`):
1.6.2 built from 1.6 branch at 85b9c963272248c0b88d06664e88eb3ef1645dfb

**Environment**:
- **Cloud provider or hardware configuration**: bare metal
- **OS** (e.g. from /etc/os-release): Ubuntu xenial
- **Kernel** (e.g. `uname -a`): Linux fab7-compute-1 4.4.0-70-generic #91-Ubuntu SMP Wed Mar 22 12:47:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: kubeadm
- **Others**:

**What happened**:
When using CNI, kubelet gets confused when pods have hostNetwork=true.
Kubelet displays errors such as:

    StopPodSandbox "3fa9fc1247bed768521abe54f730a71a7412f17e8026975902e99f56ea4fd73c" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "kube-proxy-cts6b_kube-system" network: CNI failed to retrieve network namespace path: Error: No such container: 3fa9fc1247bed768521abe54f730a71a7412f17e8026975902e99f56ea4fd73c

Deleting these pods will result in the pod hung in the Terminating state.

It appears that the tear down does not notice that CNI should not be invoked when hostNetwork=true but attempts to do so anyway.

**How to reproduce it** (as minimally and precisely as possible):
Create a pod, daemonset, or deployment with hostNetwork set to true in pod spec.

### PR DESCRIPTION
**Pull request by dcbw**
Runtimes should never return "" and nil errors, since network plugin
drivers need to treat netns differently in different cases. So return
errors when we can't get the netns, and fix up the plugins to do the
right thing.

Namely, we don't need a NetNS on pod network teardown. We do need
a netns for pod Status checks and for network setup.

V2: don't return errors from getIP(), since they will block pod status :(  Just log them.  But even so, this still fixes the original problem by ensuring we don't log errors when the network isn't ready.

@freehan @yujuhong 

Fixes: https://github.com/kubernetes/kubernetes/issues/42735
Fixes: https://github.com/kubernetes/kubernetes/issues/44307

### CODE REVIEW

**Comment by dcbw** [comment]
This PR effectively reverts https://github.com/kubernetes/kubernetes/pull/46739 and provides the same fixes as https://github.com/kubernetes/kubernetes/pull/43879 but hopefully doesn't cause flakes...

**Comment by dcbw** [comment]
@freehan @yujuhong rebased, PTAL thanks!

**Comment by cmluciano** [comment]
@dcbw Should this be marked as a bug fix for 1.7?

**Comment by dchen1107** [comment]
Reassign this to @freehan @yujuhong since they have the most context on this. 

https://github.com/kubernetes/kubernetes/issues/42735 is marked for 1.7.

**Review by freehan — COMMENTED** [review]
looks good overall.

File: pkg/kubelet/dockershim/docker_sandbox.go [hunk 1]
```diff
@@ -114,6 +136,7 @@ func (ds *dockerService) RunPodSandbox(config *runtimeapi.PodSandboxConfig) (str
 
 	// Do not invoke network plugins if in hostNetwork mode.
 	if nsOptions := config.GetLinux().GetSecurityContext().GetNamespaceOptions(); nsOptions != nil && nsOptions.HostNetwork {
+		ds.setNetworkReady(createResp.ID, true)
```
Comment (dcbw) [inline pkg/kubelet/dockershim/docker_sandbox.go]: @freehan Done!  Can you double-check my usage of named return variables and defer and pointers?

**Comment by dcbw** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

```
W0612 13:27:26.503] ERROR: (gcloud.compute.networks.create) Could not fetch resource:
W0612 13:27:26.503]  - Quota 'SUBNETWORKS' exceeded.  Limit: 150.0
W0612 13:27:26.503] 
W0612 13:27:26.592] 2017/06/12 13:27:26 util.go:131: Step './hack/e2e-internal/e2e-up.sh' finished in 1m6.462214156s
```

**Comment by freehan** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by freehan** [comment]
@yujuhong for /approve

**Comment by yujuhong** [comment]
/approve
based on @freehan's LGTM.

**Comment by dcbw** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this issue https://github.com/kubernetes/kubernetes/issues/36293

**Comment by dcbw** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this issue https://github.com/kubernetes/kubernetes/issues/47446

**Comment by warmchang** [comment]
1.6 branch doesn't contains this PR?
