### PR TITLE
Fixes dns autoscaling test flakes

### LINKED ISSUE #36457: [k8s.io] DNS horizontal autoscaling [Serial] [Slow] kube-dns-autoscaler should scale kube-dns pods when cluster size changed {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gci-gce-serial/303/

Failed: [k8s.io] DNS horizontal autoscaling [Serial] [Slow] kube-dns-autoscaler should scale kube-dns pods when cluster size changed {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns_autoscaling.go:109
Expected error:
    <*errors.errorString | 0xc420f44040>: {
        s: "timeout waiting 10m0s for cluster size to be 3",
    }
    timeout waiting 10m0s for cluster size to be 3
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns_autoscaling.go:106
```

### LINKED ISSUE #36569: [k8s.io] DNS horizontal autoscaling kube-dns-autoscaler should scale kube-dns pods in both nonfaulty and faulty scenarios {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-multizone/5370/

Failed: [k8s.io] DNS horizontal autoscaling kube-dns-autoscaler should scale kube-dns pods in both nonfaulty and faulty scenarios {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns_autoscaling.go:71
Expected error:
    <*errors.errorString | 0xc420b17ef0>: {
        s: "err waiting for DNS replicas to satisfy 8, got 9: timed out waiting for the condition",
    }
    err waiting for DNS replicas to satisfy 8, got 9: timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/petset.go:817
```

### PR DESCRIPTION
**Pull request by MrHohn**
Fixes  #36457 and fixes #36569.

#36457 is flake due to the 10 minutes timeout for scaling down cluster. Changes to use `scaleDownTimeout` from [test/e2e/cluster_size_autoscaling.go](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/cluster_size_autoscaling.go), which is 15 minutes.

The failure in #36569 is because we get the schedulable nodes number at the beginning of the test and assume it will not change unless we manually change the cluster size. But below logs indicate there may be nodes become ready after the test has begun. 

```
[BeforeEach] [k8s.io] DNS horizontal autoscaling
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns_autoscaling.go:71
Nov 10 00:36:26.951: INFO: Condition Ready of node jenkins-e2e-minion-group-x6w1 is false instead of true. Reason: KubeletNotReady, message: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR
STEP: Replace the dns autoscaling parameters with testing parameters
Nov 10 00:36:26.961: INFO: DNS autoscaling ConfigMap updated.
STEP: Wait for kube-dns scaled to expected number
Nov 10 00:36:26.961: INFO: Waiting up to 5m0s for kube-dns reach 8 replicas
...
Expected error:
      <*errors.errorString | 0xc420b17ef0>: {
          s: "err waiting for DNS replicas to satisfy 8, got 9: timed out waiting for the condition",
      }
      err waiting for DNS replicas to satisfy 8, got 9: timed out waiting for the condition
  not to have occurred
```

This fix puts the logic of counting schedulable nodes into the polling loop. By doing so, the test will have the correct expected replicas count even if schedulable nodes change in between.

@bowei @bprashanth

---

Updates: all `ExpectNoError(err)` are changed to `Expect(err).NotTo(HaveOccurred())`

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36600)

### CODE REVIEW

**Comment by MrHohn** [comment]
@k8s-bot cvm gke e2e test this, issue: #33388

File: test/e2e/dns_autoscaling.go [hunk 1]
```diff
@@ -96,54 +91,78 @@ var _ = framework.KubeDescribe("DNS horizontal autoscaling", func() {
...
+	data            map[string]string
+	nodesPerReplica float64
+}
+
+type getExpectReplicasFunc func(c clientset.Interface) int
+
+func getExpectReplicasFuncLinear(c clientset.Interface, nodesPerReplica float64) getExpectReplicasFunc {
+	return func(c clientset.Interface) int {
+		nodeCount := numOfSchedulableNodes(c)
+		return int(math.Ceil(float64(nodeCount) / nodesPerReplica))
```
Comment (bprashanth) [inline test/e2e/dns_autoscaling.go]: not testing the cores logic? or is that just harder to trigger

File: test/e2e/dns_autoscaling.go [hunk 2]
```diff
@@ -96,54 +91,78 @@ var _ = framework.KubeDescribe("DNS horizontal autoscaling", func() {
...
+	}
+}
+
+func numOfSchedulableNodes(c clientset.Interface) int {
```
Comment (bprashanth) [inline test/e2e/dns_autoscaling.go]: why put this in a fucntion when it's just taking len()?

File: test/e2e/dns_autoscaling.go [hunk 3]
```diff
@@ -207,14 +226,16 @@ func deleteDNSAutoscalerPod(c clientset.Interface) error {
...
 	var current int
+	expected := getExpected(c)
 	framework.Logf("Waiting up to %v for kube-dns reach %v replicas", timeout, expected)
 	condition := func() (bool, error) {
 		current, err = getDNSReplicas(c)
 		if err != nil {
 			return false, err
 		}
+		expected = getExpected(c)
 		if current != expected {
```
Comment (bprashanth) [inline test/e2e/dns_autoscaling.go]: what happens if a node goes NotReady during the test, do we surface the error clearly? I'm guessing the expected count will change because it relists nodes every invocation, and we will have some extra DNS pods in running for ~5m till the master deletes pods on NotReady nodes, so the test will probably time out. Ideally, an error message that tells us a node went notready/un-schedulable during the test would help.

File: test/e2e/dns_autoscaling.go [hunk 4]
```diff
@@ -207,14 +226,16 @@ func deleteDNSAutoscalerPod(c clientset.Interface) error {
 	return nil
 }
 
-func waitForDNSReplicasSatisfied(c clientset.Interface, expected int, timeout time.Duration) (err error) {
+func waitForDNSReplicasSatisfied(c clientset.Interface, getExpected getExpectReplicasFunc, timeout time.Duration) (err error) {
 	var current int
+	expected := getExpected(c)
 	framework.Logf("Waiting up to %v for kube-dns reach %v replicas", timeout, expected)
```
Comment (bprashanth) [inline test/e2e/dns_autoscaling.go]: why not log this in the condition func? otherwise we'll just get a few minuts of silence with no clarity into what the test is doing right.

**Review by bprashanth — COMMENTED** [review]
few nits, mostly LG

File: test/e2e/dns_autoscaling.go (hunk 3 above)
Comment (MrHohn) [inline test/e2e/dns_autoscaling.go]: This test will not timeout because it is not actually counting the running pods. Instead it just gets the replicas count from kube-dns deployment.

And because it is using the `GetReadySchedulableNodesOrDie()` function from framework, I think it does print out warning if a node is not ready, like below:
```
Nov 10 00:36:26.951: INFO: Condition Ready of node jenkins-e2e-minion-group-x6w1 is false instead of true.
```

File: test/e2e/dns_autoscaling.go (hunk 1 above)
Comment (MrHohn) [inline test/e2e/dns_autoscaling.go]: I considered the unit tests already cover that part. But yes, it would be better if we test that as well.

File: test/e2e/dns_autoscaling.go (hunk 2 above)
Comment (MrHohn) [inline test/e2e/dns_autoscaling.go]: Done.

File: test/e2e/dns_autoscaling.go (hunk 4 above)
Comment (MrHohn) [inline test/e2e/dns_autoscaling.go]: Done.

**Comment by MrHohn** [comment]
The re-pushed commit also tests the cores logic. The slow test passed on my cluster.

**Comment by MrHohn** [comment]
@bprashanth Do you have time to take a another look? It would be good to let this into 1.5.

**Comment by bprashanth** [comment]
Sorry for the delay, just fell off my radar

**Comment by bprashanth** [comment]
P2 to fix flake

**Comment by MrHohn** [comment]
@k8s-bot cvm gke e2e test this, issue: #36895

**Comment by MrHohn** [comment]
@k8s-bot gci gke e2e test this, issue: #36895

**Comment by MrHohn** [comment]
@bprashanth may need the milestone label

**Comment by MrHohn** [comment]
@k8s-bot gci gke e2e test this, issue: #36895

**Comment by bprashanth** [comment]
Bug fix, we can get it into 1.5 to save us the pain of debugging release tests for 1.6

**Comment by MrHohn** [comment]
Rebased.

**Comment by MrHohn** [comment]
@k8s-bot test this please

**Comment by MrHohn** [comment]
@bowei @bprashanth could anyone lgtm one more time? Just rebased `api` to `api/v1`.

**Comment by MrHohn** [comment]
@k8s-bot unit test this please

**Comment by dims** [comment]
@k8s-bot kubemark e2e test this

**Comment by saad-ali** [comment]
Does this need to be cherry-picked to 1.5? If so make sure to add `cherrypick-candidate` label

**Comment by MrHohn** [comment]
@saad-ali It would be good to cherry pick this to filter out the known flakes.

**Comment by saad-ali** [comment]
> @saad-ali It would be good to cherry pick this to filter out the known flakes.

This PR has merge conflicts, I will not pick it up in my batch cherry pick. Please prepare a separate cherry pick. See "About Cherrypicks" section in https://groups.google.com/forum/#!topic/kubernetes-dev/mvIXrgEyHPY for help.

**Comment by MrHohn** [comment]
>  Please prepare a separate cherry pick.

Sure, resolve conflicts and sent #37888
