### PR TITLE
tests: Check FQDN for external services on Windows

### LINKED ISSUE #90719: ExternalName tests are failing on Windows
**Which jobs are failing**:

sig-windows jobs: https://testgrid.k8s.io/sig-windows#aks-engine-azure-windows-master-staging

**Which test(s) are failing**:

[sig-network] Services should be able to change the type from ClusterIP to ExternalName [Conformance]
[sig-network] Services should be able to change the type from NodePort to ExternalName [Conformance]

**Since when has it been failing**:

It was a false positive until recently.

**Testgrid link**:

https://testgrid.k8s.io/sig-windows#aks-engine-azure-windows-master-staging

**Reason for failure**:

Partially Qualified Domain Names are not currently supported on Windows containers. The tests are checking PQDNs for validation.

The test was passing until recently because ``nslookup`` was still returning the exit code 0, even if the given DNS name was not found:

    [sig-network] Services
      should be able to change the type from NodePort to ExternalName [Conformance]
      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:597
    [BeforeEach] [sig-network] Services
      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:174
    STEP: Creating a kubernetes client
    Apr 28 21:24:38.587: INFO: >>> kubeConfig: /home/ubuntu/kube/config_200424
    STEP: Building a namespace api object, basename services
    STEP: Binding the e2e-test-privileged-psp PodSecurityPolicy to the default service account in services-2633
    STEP: Waiting for a default service account to be provisioned in namespace
    [BeforeEach] [sig-network] Services
      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:691
    [It] should be able to change the type from NodePort to ExternalName [Conformance]
      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:597
    STEP: creating a service nodeport-service with the type=NodePort in namespace services-2633
    STEP: Creating active service to test reachability when its FQDN is referred as externalName for another service
    STEP: creating service externalsvc in namespace services-2633
    STEP: creating replication controller externalsvc in namespace services-2633
    I0428 21:24:42.269902   57864 runners.go:190] Created replication controller with name: externalsvc, namespace: services-2633, replica count: 2
    I0428 21:24:45.471969   57864 runners.go:190] externalsvc Pods: 2 out of 2 created, 0 running, 2 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady
    I0428 21:24:48.472877   57864 runners.go:190] externalsvc Pods: 2 out of 2 created, 0 running, 2 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady
    I0428 21:24:51.473973   57864 runners.go:190] externalsvc Pods: 2 out of 2 created, 1 running, 1 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady
    I0428 21:24:54.474951   57864 runners.go:190] externalsvc Pods: 2 out of 2 created, 2 running, 0 pending, 0 waiting, 0 inactive, 0 terminating, 0 unknown, 0 runningButNotReady
    STEP: changing the NodePort service to type=ExternalName
    Apr 28 21:24:55.544: INFO: Creating new exec pod
    Apr 28 21:25:06.371: INFO: Running '/home/ubuntu/run_e2e/kubernetes/_output/dockerized/bin/linux/amd64/kubectl --server=https://kubetest-63c87972-83ef-11ea-ae60-024273197af3.westus2.cloudapp.azure.com --kubeconfig=/home/ubuntu/kube/config_200424 exec --namespace=services-2633 agnhost-pod -- /bin/sh -x -c nslookup nodeport-service'
    Apr 28 21:25:09.610: INFO: stderr: "+ nslookup nodeport-service\n*** kube-dns.kube-system.svc.cluster.local can't find nodeport-service: Non-existent domain\r\r\n"
    Apr 28 21:25:09.610: INFO: stdout: "Server:  kube-dns.kube-system.svc.cluster.local\r\nAddress:  10.0.0.10\r\n\r\n"
    STEP: deleting ReplicationController externalsvc in namespace services-2633, will wait for the garbage collector to delete the pods
    Apr 28 21:25:10.429: INFO: Deleting ReplicationController externalsvc took: 423.628373ms
    Apr 28 21:25:10.830: INFO: Terminating ReplicationController externalsvc pods took: 400.686463ms
    Apr 28 21:25:15.792: INFO: Cleaning up the NodePort to ExternalName test service
    [AfterEach] [sig-network] Services
      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:175
    Apr 28 21:25:16.230: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
    STEP: Destroying namespace "services-2633" for this suite.
    [AfterEach] [sig-network] Services
      /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:695
    â¢{"msg":"PASSED [sig-network] Services should be able to change the type from NodePort to ExternalName [Conformance]","total":2,"completed":2,"skipped":2913,"failed":0}

The issue was observed with an updated ``nslookup``, which doesn't return 0 if the given DNS name was not found.

**Anything else we need to know**:

/sig testing
/sig windows

### PR DESCRIPTION
**Pull request by claudiubelu**
**What type of PR is this?**

/kind failing-test

/sig testing
/sig windows

**What this PR does / why we need it**:

Windows does not support partially qualified domain names, which is why the test can fail.

Additionally, because nslookup may return 0 on Windows, even if the given DNS name was not found, this issue was not observed until recently. We're now checking stderr as well.

**Which issue(s) this PR fixes**:

Fixes #90719

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: test/e2e/framework/service/jig.go [hunk 1]
```diff
@@ -901,10 +901,15 @@ func (j *TestJig) checkNodePortServiceReachability(svc *v1.Service, pod *v1.Pod)
...
+	if framework.NodeOSDistroIs("windows") {
+		svcName = fmt.Sprintf("%s.%s.svc.%s", svcName, svc.Namespace, framework.TestContext.ClusterDNSDomain)
+	}
 	// Service must resolve to IP
-	cmd := fmt.Sprintf("nslookup %s", svc.Name)
-	_, err := framework.RunHostCmd(pod.Namespace, pod.Name, cmd)
-	if err != nil {
+	cmd := fmt.Sprintf("nslookup %s", svcName)
+	_, stderr, err := framework.RunHostCmdWithFullOutput(pod.Namespace, pod.Name, cmd)
+	if err != nil || strings.Contains(stderr, fmt.Sprintf("can't find %s", svcName)) {
```
Comment (oomichi) [inline test/e2e/framework/service/jig.go:912]: It is nice to add NOTE to explain why this stderr check is necessary.

**Review by oomichi — COMMENTED** [review]
just one small comment, and the change itself seems good for me.

/lgtm

**Review by oomichi — COMMENTED** [review]
Thanks for updating.

/lgtm

**Review by michmike — APPROVED** [review]
/lgtm
/approve

**Comment by michmike** [comment]
@andrewsykim or @oomichi , can you please review. we have a couple of failing tests due to this PR.
/assign @oomichi

File: test/e2e/framework/service/jig.go [hunk 2]
```diff
@@ -901,10 +901,17 @@ func (j *TestJig) checkNodePortServiceReachability(svc *v1.Service, pod *v1.Pod)
...
+	}
 	// Service must resolve to IP
-	cmd := fmt.Sprintf("nslookup %s", svc.Name)
-	_, err := framework.RunHostCmd(pod.Namespace, pod.Name, cmd)
-	if err != nil {
+	cmd := fmt.Sprintf("nslookup %s", svcName)
+	_, stderr, err := framework.RunHostCmdWithFullOutput(pod.Namespace, pod.Name, cmd)
+	// NOTE(claudiub): nslookup may return 0 on Windows, even though the DNS name was not found. In this case,
+	// we can check stderr for the error.
+	if err != nil || strings.Contains(stderr, fmt.Sprintf("can't find %s", svcName)) {
```
Comment (andrewsykim) [inline test/e2e/framework/service/jig.go:914]: This seems potentially error prone / flaky,  I'm curious why nslookup behavior is like this on Windows and if there's a more consistent way to check failure.

**Comment by oomichi** [comment]
@michmike I didn't realize that before.
Which testing job was failed due to this PR?
I'd like to see test log to investigate that.
I just put `hold` here temporary.

/hold
/retest

**Comment by claudiubelu** [comment]
> 
> 
> @michmike I didn't realize that before.
> Which testing job was failed due to this PR?
> I'd like to see test log to investigate that.
> I just put `hold` here temporary.
> 
> /hold
> /retest

All the sig-windows jobs has this issue. It was a false positive before because the exit code is 0 even if it failed, which was seen as "successfull", but actually checking it manually, it could be seen that there are errors sent to stderr. We've recently switched to nanoserver images, and we've included the bind-tools' ``nslookup`` since we needed it for some tests (nanoserver doesn't have it by default), and this ``nslookup`` properly returns an exit code != 0 on error, which is why you can see the tests failing here:

    https://testgrid.k8s.io/sig-windows#aks-engine-azure-windows-1903-master
    https://testgrid.k8s.io/sig-windows#aks-engine-azure-windows-master-containerd
    https://testgrid.k8s.io/sig-windows#aks-engine-azure-windows-master-staging

File: test/e2e/framework/service/jig.go (hunk 2 above)
Comment (claudiubelu) [reply test/e2e/framework/service/jig.go:914]: Windows and Linux commands behave quite differently, that is an already known fact. In this case, the Windows' ``nslookup`` doesn't have a return code, which means it will always be "succesful".

We've replaced it with bind-tools' ``nslookup`` which properly returns a non-zero value if the given DNS name is not found.

With this change here, we're trying to make sure that we properly fail the test for the Windows' ``nslookup`` by checking its stderr. Here's the output we're checking against:

    Apr 28 21:25:06.371: INFO: Running '/home/ubuntu/run_e2e/kubernetes/_output/dockerized/bin/linux/amd64/kubectl --server=https://kubetest-63c87972-83ef-11ea-ae60-024273197af3.westus2.cloudapp.azure.com --kubeconfig=/home/ubuntu/kube/config_200424 exec --namespace=services-2633 agnhost-pod -- /bin/sh -x -c nslookup nodeport-service'
    Apr 28 21:25:09.610: INFO: stderr: "+ nslookup nodeport-service\n*** kube-dns.kube-system.svc.cluster.local can't find nodeport-service: Non-existent domain\r\r\n"
    Apr 28 21:25:09.610: INFO: stdout: "Server:  kube-dns.kube-system.svc.cluster.local\r\nAddress:  10.0.0.10\r\n\r\n"

Comment (andrewsykim) [inline test/e2e/framework/service/jig.go:914]: Can we gate the `strings.Contains(stderr, fmt.Sprintf("can't find %s", svcName))` check to windows only?

Comment (claudiubelu) [reply test/e2e/framework/service/jig.go:914]: Done

File: test/e2e/framework/service/jig.go [hunk 3]
```diff
@@ -901,10 +901,17 @@ func (j *TestJig) checkNodePortServiceReachability(svc *v1.Service, pod *v1.Pod)
 // checkExternalServiceReachability ensures service of type externalName resolves to IP address and no fake externalName is set
 // FQDN of kubernetes is used as externalName(for air tight platforms).
 func (j *TestJig) checkExternalServiceReachability(svc *v1.Service, pod *v1.Pod) error {
+	// NOTE(claudiub): Windows does not support PQDN.
+	svcName := svc.Name
+	if framework.NodeOSDistroIs("windows") {
+		svcName = fmt.Sprintf("%s.%s.svc.%s", svcName, svc.Namespace, framework.TestContext.ClusterDNSDomain)
```
Comment (oomichi) [inline test/e2e/framework/service/jig.go:907]: Just a question.
Can we just change here to
```
svcName = fmt.Sprintf("%s.%s.svc.%s", svcName, svc.Namespace, framework.TestContext.ClusterDNSDomain)
```
without considering Linux or Windows?

This function is used in conformance tests as the corresponding issue says, and the conformance test requirements[1] contains `where possible, it does not depend on outputs that change based on OS (nslookup, ping, chmod, ls)`
That doesn't seems mandatory but it seems better to use the same testing way as possible.

[1]: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements

Comment (claudiubelu) [reply test/e2e/framework/service/jig.go:907]: Done

File: test/e2e/framework/service/jig.go [hunk 4]
```diff
@@ -901,10 +901,14 @@ func (j *TestJig) checkNodePortServiceReachability(svc *v1.Service, pod *v1.Pod)
 // checkExternalServiceReachability ensures service of type externalName resolves to IP address and no fake externalName is set
 // FQDN of kubernetes is used as externalName(for air tight platforms).
 func (j *TestJig) checkExternalServiceReachability(svc *v1.Service, pod *v1.Pod) error {
+	// NOTE(claudiub): Windows does not support PQDN.
+	svcName = fmt.Sprintf("%s.%s.svc.%s", svcName, svc.Namespace, framework.TestContext.ClusterDNSDomain)
```
Comment (oomichi) [inline test/e2e/framework/service/jig.go:905]: Need to change here to `svcName := fmt.Sprintf(... `

**Review by oomichi — COMMENTED** [review]
Thanks for updating

/lgtm

**Review by andrewsykim — COMMENTED** [review]
/approve
/lgtm
