### PR TITLE
Parallel pod management should not count old, broken pods for maxUnavailable budget

### LINKED ISSUE #137409: StatefulSet pod revisions not updated when MaxUnavailableStatefulSet enabled
### What happened?

I decided to open this issue after investigating https://github.com/stackabletech/trino-operator/issues/854.

The high level description of the problem is that the stateful set controller doesn't update the pods according to the latest STS revision and the pods are left crashlooping **if the first revision is faulty** and can never become available. This doesn't happen if the `MaxUnavailableStatefulSet` feature is disabled.

Unfortunately I cannot create a much simpler example, but I attach the relevant controller log messages below.

Based on these logs you can see that:

1. The Stackable Operator for Trino (`trino-op` from now on) creates two `StatefulSet` objects with a single replica. They both expose the same problem, so for simplicity, I will use only one of them from now on (`trino-coordinator-default`).
2. The initial revision of this sts is `trino-coordinator-default-5f5598d4c8`. This first STS  revision has a faulty command args  and can never become available.
3. The `trino-op` updates the sts rapidly to the revision `trino-coordinator-default-787556ff59`. Now the STS command args are correct and the pods should be able to become ready.
4. The pod created initially is never updated so it never becomes ready.

To summarize my understanding, the sts revision is never updated if the pod never becomes ready, and the pod doesn't become ready because it has an old revision.

In the logs you see that `currentRevision` is never the same as `updateRevision`:

```
I0304 15: 25:06.514308       1 stateful_set_control.go: 146]"StatefulSet revisions" statefulSet = "kuttl-test-distinct-turtle/trino-coordinator-default" currentRevision = "trino-coordinator-default-5f5598d4c8" updateRevision = "trino-coordinator-default-787556ff59"
```

### What did you expect to happen?

The pod should become ready according to the `updateRevision` of the sts.
Again, this was indeed the case until `MaxUnavailableStatefulSet` feature gate was enabled.

### How can we reproduce it (as minimally and precisely as possible)?

I can reproduce this bug using the `trino-op` but unfortunately I don't have a minimal example.

### Anything else we need to know?

Attached are the relevant kube controller logs.

[kobe-controller-logs.txt](https://github.com/user-attachments/files/25745670/kobe-controller-logs.txt)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.34.0
Kustomize Version: v5.7.1
Server Version: v1.35.1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="43 (Workstation Edition)"
RELEASE_TYPE=stable
ID=fedora
VERSION_ID=43
VERSION_CODENAME=""
PRETTY_NAME="Fedora Linux 43 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:43"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f43/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=43
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=43
SUPPORT_END=2026-12-02
VARIANT="Workstation Edition"
VARIANT_ID=workstation

$ uname -a
Linux fedora.fritz.box 6.18.13-200.fc43.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Feb 19 19:54:01 UTC 2026 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by soltysh**
#### What type of PR is this?
/kind bug
/kind regression
/sig apps

#### What this PR does / why we need it:
This change ensures that Parallel pod management in statefulset controller does not count unavailable, old pods during maxUnavailable calculation. This allows statefulset to continue rollout.

#### Which issue(s) this PR is related to:
Fixes #137409
KEP: https://github.com/kubernetes/enhancements/issues/961

#### Special notes for your reviewer:
/assign @atiratree 

#### Does this PR introduce a user-facing change?
```release-note
Fix a regression in kubernetes v1.35, where with a Parallel pod management policy unavailable pods from an older revision were incorrectly counted towards maxUnavailable budget. 
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
[KEP]: https://github.com/kubernetes/enhancements/issues/961
```

### CODE REVIEW

File: pkg/controller/statefulset/stateful_set_control.go [hunk 1]
```diff
@@ -769,9 +769,25 @@ func updateStatefulSetAfterInvariantEstablished(ctx context.Context, ssc *defaul
...
-	if unavailablePods >= maxUnavailable {
+	// For Parallel pod management, pods that are already unavailable AND on an old revision
+	// do not consume the maxUnavailable budget.
+	// For OrderedReady pod management this does not apply to preserve the existing
+	// sequential update behaviour.
+	effectiveUnavailable := unavailablePods
+	if set.Spec.PodManagementPolicy == apps.ParallelPodManagement {
+		unavailablePodsNeedingUpdate := 0
+		for target := len(replicas) - 1; target >= 0; target-- {
+			if isUnavailable(replicas[target], set.Spec.MinReadySeconds, now) &&
```
Comment (atiratree) [inline pkg/controller/statefulset/stateful_set_control.go]: I tested this locally, and it cuts down more replicas than needed when rolling out a new update to a sts, with e.g. 5 replicas and maxUnavailable=2. Could you please add a test to ensure we have similar multiple replica cases covered? 

We miss the terminating state of pods here. Basically we have to account for any occurrence of availability and termination in our replicas.

I think we need two values here:
- number of old revision terminating replicas above/equal to Partition
- maxUnavailable

If the number of these terminating replicas is above/equal to maxUnavailable, then unavailablePodsNeedingUpdate should be 0. If the number of these terminating replicas is less, we can allow for additional disruption up to maxUnavailable.

File: pkg/controller/statefulset/stateful_set_control.go [hunk 2]
```diff
@@ -769,9 +769,25 @@ func updateStatefulSetAfterInvariantEstablished(ctx context.Context, ssc *defaul
...
 
-	if unavailablePods >= maxUnavailable {
+	// For Parallel pod management, pods that are already unavailable AND on an old revision
+	// do not consume the maxUnavailable budget.
+	// For OrderedReady pod management this does not apply to preserve the existing
+	// sequential update behaviour.
+	effectiveUnavailable := unavailablePods
+	if set.Spec.PodManagementPolicy == apps.ParallelPodManagement {
+		unavailablePodsNeedingUpdate := 0
+		for target := len(replicas) - 1; target >= 0; target-- {
```
Comment (atiratree) [inline pkg/controller/statefulset/stateful_set_control.go]:
```suggestion
		for target := len(replicas) - 1; target >= updateMin; target-- {
```

we can move this check here

File: pkg/controller/statefulset/stateful_set_control_test.go [hunk 3]
```diff
@@ -1260,6 +1260,124 @@ func TestStatefulSetControlRollingUpdateWithMaxUnavailableInOrderedModeVerifyInv
...
+			unavailableOrdinals:   []int{0},
+			expectedPodsRemaining: 0,
+		},
+		{
+			name:                  "Parallel/3 replicas, highest-ordinal pod unavailable on old revision",
+			podManagementPolicy:   apps.ParallelPodManagement,
+			replicas:              3,
+			maxUnavailable:        intstr.FromInt32(1),
+			unavailableOrdinals:   []int{2},
+			expectedPodsRemaining: 2,
```
Comment (atiratree) [inline pkg/controller/statefulset/stateful_set_control_test.go]: the main issue here is that we do not consider what happens when terminating pods are return from kubelet in the next sync.

It would be nice to have tests that mix terminating pods and available pods at various ordinal positions in the sts + consider partition.

**Comment by soltysh** [comment]
I've added several more test cases compared to previous version which cover various types of unavailability (terminated and unavailable) and a mixed case as well. I believe the only missing bit is the partition, which I'll try to pick up first thing in the morning tomorrow.

File: pkg/controller/statefulset/stateful_set_control_test.go [hunk 4]
```diff
@@ -1260,6 +1260,281 @@ func TestStatefulSetControlRollingUpdateWithMaxUnavailableInOrderedModeVerifyInv
...
+				time.Now(),
+			); err != nil {
+				t.Fatal(err)
+			}
+
+			podsAfter, err := spc.podsLister.Pods(set.Namespace).List(selector)
+			if err != nil {
+				t.Fatal(err)
+			}
+			if len(podsAfter) != tc.expectedPodsRemaining {
```
Comment (atiratree) [inline pkg/controller/statefulset/stateful_set_control_test.go]: this check also needs to consider pods that are still stored, but have deletionTimestamp set

Comment (soltysh) [reply pkg/controller/statefulset/stateful_set_control_test.go]: Added a check which ensures that the only pods marked as terminated by the test setup have the deletion timestamp set.

File: pkg/controller/statefulset/stateful_set_control_test.go (hunk 3 above)
Comment (soltysh) [reply pkg/controller/statefulset/stateful_set_control_test.go]: Added tests for mixed unavailable and terminated pods. As well as for partitions.

File: pkg/controller/statefulset/stateful_set_control.go (hunk 2 above)
Comment (soltysh) [reply pkg/controller/statefulset/stateful_set_control.go]: Done.

File: pkg/controller/statefulset/stateful_set_control.go (hunk 1 above)
Comment (soltysh) [reply pkg/controller/statefulset/stateful_set_control.go]: I've done more tests and based on my testing I'm not seeing the behavior you're describing.

File: pkg/controller/statefulset/stateful_set_control_test.go (hunk 4 above)
Comment (atiratree) [reply pkg/controller/statefulset/stateful_set_control_test.go]: I think we need to remove these from `podsAfter`, because the original terminating pods still count against the disruption quota described by `maxUnavailable`. This may result in all of the pods being terminated during a new a rollout after a couple of syncs.

Comment (soltysh) [reply pkg/controller/statefulset/stateful_set_control_test.go]: @atiratree after looking at it more, I see your point. I've added separate commit resolving the terminating pods, to ensure those are treated as in-fligth transition pods, which should be properly counted towards maxUnavailable.

File: pkg/controller/statefulset/stateful_set_control_test.go [hunk 5]
```diff
@@ -1260,6 +1260,380 @@ func TestStatefulSetControlRollingUpdateWithMaxUnavailableInOrderedModeVerifyInv
...
+			podManagementPolicy: apps.ParallelPodManagement,
+			replicas:            5,
+			partition:           2,
+			maxUnavailable:      intstr.FromInt32(1),
+			unavailableOrdinals: []int{2},
+			makeUnavailable: func(spc *fakeObjectManager, set *apps.StatefulSet, ordinal int) error {
+				_, err := spc.setPodReadyCondition(set, ordinal, false)
+				return err
+			},
+			expectedPodsRemaining: 4,
```
Comment (atiratree) [inline pkg/controller/statefulset/stateful_set_control_test.go]: In a rare case when the lower index pods start misbehaving, this could cause unnecessary disruption: 

With maxUnavailable = 2

`0 (Unavailable) 1 (Unavailable) 2(good) 3(good)` 

We delete all 2 good pods and the availability drops to 0.

The former controller logic without the `maxUnavailable` feature had the same problem with

`0 (Unavailable) 1 (Good)`

which also causes a total disruption.

In this preexisting case, the advantage is that we can progress vs not progress instead of waiting for the 0 pod.

Unfortunately, the maxUnavailable feature multiplies this problem.

We have two options here:
- Say this is a continuation of the existing behavior (this should be at least be documented for the maxUnavailable feature). 
- Limit the disruption to 1, as before, so we can progress when we detect the first scenario (instead of 2).

TLDR: the PR currently fixes the https://github.com/kubernetes/kubernetes/issues/137409 regression, but possibly introduces a new one. Depending on how we want to interpret the issue mentioned above.

**Comment by carlory** [comment]
cc @Edwinhr716 @helayoty since they worked on the MaxUnavailable feature together

File: pkg/controller/statefulset/stateful_set_control.go [hunk 6]
```diff
@@ -756,41 +756,92 @@ func updateStatefulSetAfterInvariantEstablished(ctx context.Context, ssc *defaul
...
 			logger.V(4).Info("StatefulSet found unavailablePods, more than the allowed maxUnavailable",
 				"statefulSet", klog.KObj(set),
 				"unavailablePods", unavailablePods,
+				"unavailablePodsNeedingUpdate", unavailablePodsNeedingUpdate,
 				"maxUnavailable", maxUnavailable)
 		}
+		return &status, nil
+	}
+
+	if set.Spec.PodManagementPolicy == apps.ParallelPodManagement {
```
Comment (atiratree) [inline pkg/controller/statefulset/stateful_set_control.go:794]: +1 for branching the logic, it is quite clear what we are trying to achieve. And this will fix even the preexisting issue with maxUnavailable == 1 mentioned in https://github.com/kubernetes/kubernetes/pull/137666#discussion_r2933469830 (`0 (Unavailable) 1 (Good)`).

The only small issue is that this will change the behavior (disruption order). The good news is that we already sort of document this for the `ParallelPodManagement` policy : https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#parallel-pod-management 

> Parallel pod management tells the StatefulSet controller to launch or terminate all Pods in parallel, and to not wait for Pods to become Running and Ready or completely terminated prior to launching or terminating another Pod.

However the following sentence now also applies to `maxUnavailable == 1` .

> This can speed up updates but may result in Pods becoming ready out of order, which might not be suitable for applications requiring strict ordering.

The API types would also benefit from an update to make things clear. We can do this in a follow-up.

File: pkg/controller/statefulset/stateful_set_control.go [hunk 7]
```diff
@@ -756,41 +756,92 @@ func updateStatefulSetAfterInvariantEstablished(ctx context.Context, ssc *defaul
...
+		}
 
+		// Phase 2: delete additional available pods, limited by remaining budget,
+		// to always stay under the maxUnavailable.
+		remainingBudget := maxUnavailable - unavailablePods
+		for target := len(replicas) - 1; target >= updateMin && remainingBudget > 0; target-- {
+			pod := replicas[target]
+			if getPodRevision(pod) != updateRevision.Name &&
+				!isUnavailable(pod, set.Spec.MinReadySeconds, now) &&
+				!isTerminating(pod) {
```
Comment (atiratree) [inline pkg/controller/statefulset/stateful_set_control.go:825]: It is a bit confusing to invoke `isTerminating` twice here. I know we use `isUnavailable` elsewhere, so we could keep it for consistency here. But personally changing this to 

```suggestion
				podutil.IsPodAvailable(pod, minReadySeconds, metav1.Time{Time: now}) &&
				!isTerminating(pod) {
```

 would be easier to read for me.

Comment (atiratree) [reply pkg/controller/statefulset/stateful_set_control.go:825]: or with `isRunningAndAvailable`

File: pkg/controller/statefulset/stateful_set_control.go [hunk 8]
```diff
@@ -756,41 +756,92 @@ func updateStatefulSetAfterInvariantEstablished(ctx context.Context, ssc *defaul
...
+		// could spend the entire budget on good pods and never reach the already-
+		// unavailable pods at the bottom, causing total disruption >> maxUnavailable.
+		//
+		// Phase 1: delete pods that are already unavailable on the old revision.
+		// Always make sure to stay under the maxUnavailable budget.
+		deletedInPhase1 := 0
+		for target := len(replicas) - 1; target >= updateMin && deletedInPhase1 < maxUnavailable; target-- {
+			pod := replicas[target]
+			if getPodRevision(pod) != updateRevision.Name &&
+				isUnavailable(pod, set.Spec.MinReadySeconds, now) &&
```
Comment (atiratree) [inline pkg/controller/statefulset/stateful_set_control.go:806]: also applicable here

File: pkg/controller/statefulset/stateful_set_control.go [hunk 9]
```diff
@@ -756,41 +756,92 @@ func updateStatefulSetAfterInvariantEstablished(ctx context.Context, ssc *defaul
...
+	if set.Spec.PodManagementPolicy == apps.ParallelPodManagement {
+		// Two-phase deletion for Parallel mode avoids excessive disruption when some
+		// pods are already unavailable on the old revision. A single high-to-low loop
+		// could spend the entire budget on good pods and never reach the already-
+		// unavailable pods at the bottom, causing total disruption >> maxUnavailable.
+		//
+		// Phase 1: delete pods that are already unavailable on the old revision.
+		// Always make sure to stay under the maxUnavailable budget.
+		deletedInPhase1 := 0
+		for target := len(replicas) - 1; target >= updateMin && deletedInPhase1 < maxUnavailable; target-- {
```
Comment (atiratree) [inline pkg/controller/statefulset/stateful_set_control.go:803]: Just to be clear, with maxUnavailable = 1

`0 (Unavailable) 1 (Unavailable) 2 (Unavailable)  3(good) 4(good)`

We will first restart all the first 3 pods if they are old revision in immediate subsequent syncs. So the `maxUnavailable` is only applicable in a single sync here.

This is okay, I guess, because we are not worsening the unavailability. 

Could we remove the `maxUnavailable` check completely and delete all the failing pods at once to make our intent clear? Overall, it seems to me that, with `ParallelPodManagement`, deleting all of them at once should be expected.

However, there are scenarios where this could be surprising.

If you create a stateful set, for example with `replicas = 5` and `minReadySeconds == 60`. And then rollout a new revision in 20s, it will rollout/restart all pods at once. In the old implementation, there was a time window where the old pods could be ready for some time to take traffic, before the new pods came up .

Accounting for this scenario (e.g. check pod creationTimestamp and react only to crashloopbackoff and sustained unavailability) would make the logic more complicated again. @soltysh what are your thoughts on this?

At least, we really need the API+docs update.

File: pkg/controller/statefulset/stateful_set_control_test.go [hunk 10]
```diff
@@ -1260,6 +1260,424 @@ func TestStatefulSetControlRollingUpdateWithMaxUnavailableInOrderedModeVerifyInv
...
+			set, err := spc.setsLister.StatefulSets(set.Namespace).Get(set.Name)
+			if err != nil {
+				t.Fatal(err)
+			}
+
+			// IsPodAvailable checks lastTransitionTime, so for those cases where
+			// we rely on minReadySeconds we need to ensure that pod report it
+			// with appropriate higher value
+			if tc.minReadySeconds > 0 {
+				pastTime := time.Now().Add(-time.Duration(tc.minReadySeconds+60) * time.Second)
```
Comment (atiratree) [inline pkg/controller/statefulset/stateful_set_control_test.go:1616]: for the time operations, we could create a fake clock before we create the test cases

File: pkg/controller/statefulset/stateful_set_control.go (hunk 6 above)
Comment (soltysh) [reply pkg/controller/statefulset/stateful_set_control.go:794]: > The only small issue is that this will change the behavior (disruption order). The good news is that we already sort of document this for the `ParallelPodManagement` policy : https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#parallel-pod-management

Correct, we never stated what the disruption order is, we only stated it's "in parallel" :sweat_smile:. So I wasn't worried about that part, and at least we now have an easier to follow code.

> The API types would also benefit from an update to make things clear. We can do this in a follow-up.

I'm not quite sure I follow, which part of the API you want to update? I'm looking at https://github.com/kubernetes/kubernetes/blob/03779bbd00da25c7fcd03711ddfe466a3322e1d7/staging/src/k8s.io/api/apps/v1/types.go#L123-L133) and https://github.com/kubernetes/kubernetes/blob/03779bbd00da25c7fcd03711ddfe466a3322e1d7/staging/src/k8s.io/api/apps/v1/types.go#L228-L237 and based on my reading they are matching even the updated behavior.

File: pkg/controller/statefulset/stateful_set_control.go (hunk 7 above)
Comment (soltysh) [reply pkg/controller/statefulset/stateful_set_control.go]: I went with `isRunningAndAvailable`. Also, sounds like we should revise the helpers we have there, and potentially squash some of them together. I'll see what's possible in a followup.

File: pkg/controller/statefulset/stateful_set_control.go (hunk 9 above)
Comment (soltysh) [reply pkg/controller/statefulset/stateful_set_control.go]: Now I better understand what you meant with the API+docs update. For the answer I went reading through the KEP, which introduced this new field. Already in the first section https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/961-maxunavailable-for-statefulset/README.md#proposal you'll find this statement:
```
When the field is not specified, it will default to 1 to maintain previous 
behavior of rolling one pod at a time.
```
Which means, that with `maxUnavailable=1`, we basically want to keep behavior similar to `OrderedPodManagment`, so imo, let's keep it as is. 

> At least, we really need the API+docs update.

100% agree on that one.

File: pkg/controller/statefulset/stateful_set_control.go (hunk 8 above)
Comment (soltysh) [reply pkg/controller/statefulset/stateful_set_control.go]: Updated.

File: pkg/controller/statefulset/stateful_set_control_test.go (hunk 10 above)
Comment (soltysh) [reply pkg/controller/statefulset/stateful_set_control_test.go]: Done.

File: pkg/controller/statefulset/stateful_set_control_test.go [hunk 11]
```diff
@@ -1260,6 +1261,425 @@ func TestStatefulSetControlRollingUpdateWithMaxUnavailableInOrderedModeVerifyInv
...
+		},
+		{
+			name:                "Parallel/3 replicas, highest-ordinal pod ready but within minReadySeconds on old revision: pod gets deleted",
+			podManagementPolicy: apps.ParallelPodManagement,
+			replicas:            3,
+			maxUnavailable:      intstr.FromInt32(1),
+			minReadySeconds:     30,
+			unavailableOrdinals: []int{2},
+			makeUnavailable: func(spc *fakeObjectManager, set *apps.StatefulSet, ordinal int) error {
+				_, err := spc.setPodAvailable(set, ordinal, time.Now())
```
Comment (atiratree) [inline pkg/controller/statefulset/stateful_set_control_test.go]: we could move fakeClock one level up and reference it also here

File: pkg/controller/statefulset/stateful_set_control_test.go [hunk 12]
```diff
@@ -1260,6 +1261,425 @@ func TestStatefulSetControlRollingUpdateWithMaxUnavailableInOrderedModeVerifyInv
...
+		},
+		{
+			name:                "OrderedReady/3 replicas, highest-ordinal pod ready but within minReadySeconds on old revision blocks update",
+			podManagementPolicy: apps.OrderedReadyPodManagement,
+			replicas:            3,
+			maxUnavailable:      intstr.FromInt32(1),
+			minReadySeconds:     30,
+			unavailableOrdinals: []int{2},
+			makeUnavailable: func(spc *fakeObjectManager, set *apps.StatefulSet, ordinal int) error {
+				_, err := spc.setPodAvailable(set, ordinal, time.Now())
```
Comment (atiratree) [inline pkg/controller/statefulset/stateful_set_control_test.go]: and here

File: pkg/controller/statefulset/stateful_set_control.go (hunk 6 above)
Comment (atiratree) [reply pkg/controller/statefulset/stateful_set_control.go:794]: Regarding the API, I think we could mention the pod disruption behavior during updates that this PR introduces.

https://github.com/kubernetes/kubernetes/blob/03779bbd00da25c7fcd03711ddfe466a3322e1d7/staging/src/k8s.io/api/apps/v1/types.go#L233-L235

File: pkg/controller/statefulset/stateful_set_control.go (hunk 9 above)
Comment (atiratree) [reply pkg/controller/statefulset/stateful_set_control.go]: > Which means, that with maxUnavailable=1, we basically want to keep behavior similar to OrderedPodManagment, so imo, let's keep it as is.

Ack, I guess this PR change falls mostly under `Parallel` PodManagementPolicy then

> Could we remove the maxUnavailable check completely and delete all the failing pods at once to make our intent clear?

Could we please also resolve this? The `eletedInPhase1 < maxUnavailable` is not really useful IMO.

At least, we should update this comment:

> // Always make sure to stay under the maxUnavailable budget.

Because, we just ensure that we do not worsen the unavailability, not that we make sure to stay under the maxUnavailable budget.

File: pkg/controller/statefulset/stateful_set_control.go (hunk 6 above)
Comment (soltysh) [reply pkg/controller/statefulset/stateful_set_control.go:794]: Definitely.

File: pkg/controller/statefulset/stateful_set_control.go (hunk 9 above)
Comment (soltysh) [reply pkg/controller/statefulset/stateful_set_control.go]: > Could we please also resolve this? The `eletedInPhase1 < maxUnavailable` is not really useful IMO.

Agree, it definitely doesn't make the situation worse than it already is.

Comment (atiratree) [reply pkg/controller/statefulset/stateful_set_control.go]: for posterity, we might want to document the following case as well

> If you create a stateful set, for example with replicas = 5 and minReadySeconds == 60. And then rollout a new revision in 20s, it will rollout/restart all pods at once. In the old implementation, there was a time window where the old pods could be ready for some time to take traffic, before the new pods came up .

**Comment by atiratree** [comment]
Thanks!
/lgtm

**Comment by mengqiy** [comment]
@soltysh Do we have any plan to back port this fix to 1.35 and 1.36?
Or that is not an option due to this change is too big?

**Comment by liggitt** [comment]
I would not be in favor of backporting this

**Comment by soltysh** [comment]
> @soltysh Do we have any plan to back port this fix to 1.35 and 1.36? Or that is not an option due to this change is too big?

We've decided not to backport this, and instead disabled the functionality to off by default in previous releases.
