### PR TITLE
Fix volume size allocation in gcd_pd

### LINKED ISSUE #56081: GCE CreateVolume allocates in chunks of GiB incorrectly
GCE PDs are allocated in chunks of GBs (not GiB) but `CreateVolume` function incorrectly creates volume in chunks of GiB -  https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/gce_pd/gce_util.go#L86

cc @msau42 

/sig storage
@kubernetes/sig-storage-pr-reviews

### PR DESCRIPTION
**Pull request by edisonxiang**
**What this PR does / why we need it**:
GCE PDs are allocated in chunks of GBs not GiB but CreateVolume function incorrectly creates volume in chunks of GiB.  
1 GiB = 1024 * 1024 * 1024 Bytes
1 GB = 1000 * 1000 * 1000 Bytes

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #56081

**Special notes for your reviewer**:

**Release note**:

```release-note
Fixed dynamic provisioning of GCE PDs to round to the next GB instead of GiB
```

### CODE REVIEW

File: pkg/volume/gce_pd/gce_util.go [hunk 1]
```diff
@@ -194,7 +196,7 @@ func (gceutil *GCEDiskUtil) CreateVolume(c *gcePersistentDiskProvisioner) (strin
 		glog.Errorf("error getting labels for volume %q: %v", name, err)
 	}
 
-	return name, int(requestGB), labels, fstype, nil
+	return name, int(requestGiB), labels, fstype, nil
```
Comment (gnufied) [inline pkg/volume/gce_pd/gce_util.go]: Lets make sure that value returned by this function is read correctly by `Provision` function here - https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/gce_pd/gce_pd.go#L426 . Currently as it exists it will try to save a GB value back into GiB that will be wrong.

Comment (gnufied) [reply pkg/volume/gce_pd/gce_util.go]: Ah, I missed that you are creating both GB and GiB values out of requested size and returning GiB value back to caller. That works too I think.

Comment (edisonxiang) [reply pkg/volume/gce_pd/gce_util.go]: @gnufied Thanks your review.

Comment (davidz627) [reply pkg/volume/gce_pd/gce_util.go]: Would be worth renaming the variables GB here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/gce_pd/gce_pd.go#L405
and here:
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/gce_pd/gce_pd.go#L426

Comment (edisonxiang) [reply pkg/volume/gce_pd/gce_util.go]: @davidz627 Done, thanks.

**Comment by edisonxiang** [comment]
Hey @davidz627 @msau42 @gnufied PTAL, Thank you~

File: pkg/volume/gce_pd/gce_util.go (hunk 1 above)
Comment (msau42) [reply pkg/volume/gce_pd/gce_util.go]: I'm confused, why do we need to return GiB if we're allocating in GB?  Won't the size recorded in the PV be wrong then?

Comment (edisonxiang) [reply pkg/volume/gce_pd/gce_util.go]: Hi @msau42, Thanks your review. Does your suggestion is to remove [this line ](https://github.com/kubernetes/kubernetes/pull/56600/files#diff-6f726717375311cc43c305d7a65cf2a9R86) and return requestGB directly,  and replace "%dGi" with "%dG" in [this line](https://github.com/kubernetes/kubernetes/pull/56600/files#diff-f7811184a41099ebc39b015ff49f491bR426)?

Comment (gnufied) [reply pkg/volume/gce_pd/gce_util.go]: I think either thing works. Return the GB value and then get `resource.Quantity` out of it by doing `%dG`. That is what I originally suggested above.  Returning `GiB` and leaving `%dGi` works too, but I do think that may be returning GB and then parsing value back using `%dG` was better.

Comment (msau42) [reply pkg/volume/gce_pd/gce_util.go]: I don't think returning GiB is accurate.  requestGiB != requestGB in bytes.  The PV is going to have capacity larger than what was actually allocated.

So if there is no reason to return values in Gi, then I would recommend just returning GB.

Comment (edisonxiang) [reply pkg/volume/gce_pd/gce_util.go]: @msau42 @gnufied Done. Now it is return GB Directly. Thanks.

File: pkg/volume/util.go [hunk 2]
```diff
@@ -38,6 +38,13 @@ import (
 	"k8s.io/apimachinery/pkg/util/sets"
 )
 
+const (
+	// GiB is used by PV/PVC. 1 GiB = 1024 * 1024 * 1024 Bytes
+	VolumeSizeGiB = 1024 * 1024 * 1024
```
Comment (davidz627) [inline pkg/volume/util.go]: are we using this variable anywhere?

Comment (edisonxiang) [reply pkg/volume/util.go]: Yeah. A lot of places. Such as [this line](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/flocker/flocker_util.go#L76). If this bug fix is accepted, I am willing to submit another pr to fix [this issue](https://github.com/kubernetes/kubernetes/issues/56225) with @gnufied.

Comment (davidz627) [reply pkg/volume/util.go]: the line you linked is the one you changed to "volume.VolumeSizeGB." So I dont think the GiB constant is being used anywhere anymore in the current version of your PR.

**Review by msau42 — COMMENTED** [review]
/lgtm

Thanks for running the e2e tests too!

**Comment by msau42** [comment]
Does this need a release note, since we will now be provisioning GCE disks that are smaller than before?

**Comment by edisonxiang** [comment]
@msau42 Thanks your suggetion. Done.

**Comment by msau42** [comment]
Please squash your commits

**Comment by edisonxiang** [comment]
@msau42 Done, PTAL, Thanks.

File: pkg/volume/gce_pd/gce_util.go [hunk 3]
```diff
@@ -82,8 +82,8 @@ func (gceutil *GCEDiskUtil) CreateVolume(c *gcePersistentDiskProvisioner) (strin
 	name := volume.GenerateVolumeName(c.options.ClusterName, c.options.PVName, 63) // GCE PD name can have up to 63 characters
 	capacity := c.options.PVC.Spec.Resources.Requests[v1.ResourceName(v1.ResourceStorage)]
 	requestBytes := capacity.Value()
-	// GCE works with gigabytes, convert to GiB with rounding up
-	requestGB := volume.RoundUpSize(requestBytes, 1024*1024*1024)
+	// GCE PDs are allocated in chunks of GBs (not GiBs)
+	requestGB := volume.RoundUpSize(requestBytes, volume.GB)
```
Comment (gnufied) [inline pkg/volume/gce_pd/gce_util.go]: This is really tiny nit - but can we simply use `volume.RoundUpToGB` and remove that `reuestBytes` variable?

Comment (edisonxiang) [reply pkg/volume/gce_pd/gce_util.go]: @gnufied, done, Thanks.
