### PR TITLE
e2e storage: close all pending streams when proxy listener gets closed

### LINKED ISSUE #112126: Canary CSI snapshot tests are failing
### Which jobs are failing?

ci-kubernetes-csi-canary-test-on-kubernetes-master, [example](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-csi-canary-test-on-kubernetes-master/1564570330624692224)

### Which tests are failing?

[It] [sig-storage] CSI mock volume CSI Volume Snapshots [Feature:VolumeSnapshotDataSource] volumesnapshotcontent and pvc in Bound state with deletion timestamp set should not get deleted while snapshot finalizer exists
[It] [sig-storage] CSI mock volume CSI Volume Snapshots secrets [Feature:VolumeSnapshotDataSource] volume snapshot create/delete with secrets

### Since when has it been failing?

25-08-2022?

### Testgrid link

https://testgrid.k8s.io/sig-storage-csi-ci#canary-test-on-master

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

Looking at "volume snapshot create/delete with secrets" test, it finishes OK, but the "Cleaning up resources" freezes for ~30 minutes:

```
    STEP: Deleting storageclass csi-mock-volumes-53205mbx6 08/30/22 12:35:21.996
    STEP: Cleaning up resources 08/30/22 12:35:22.006
    STEP: deleting the test namespace: csi-mock-volumes-5320 08/30/22 13:07:03.001
```

After these 30 minutes, the test timeouts and kills API server and etcd a and everything fails miserably.

Stack trace from "Cleaning up resources", it's stuck at shutting down gRPC server:

```
sync.(*WaitGroup).Wait(0xc0032997d0?)
        /home/jsafrane/.gimme/versions/go1.19.linux.amd64/src/sync/waitgroup.go:139 +0x52 fp=0xc003a0b850 sp=0xc003a0b828 pc=0x25837b2
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).Stop.func1()
        vendor/google.golang.org/grpc/server.go:1709 +0x2e fp=0xc003a0b870 sp=0xc003a0b850 pc=0x3870f8e
k8s.io/kubernetes/vendor/google.golang.org/grpc.(*Server).Stop(0xc0005bba40)
        vendor/google.golang.org/grpc/server.go:1742 +0x382 fp=0xc003a0ba00 sp=0xc003a0b870 pc=0x3870e62
k8s.io/kubernetes/test/e2e/storage/drivers/csi-test/driver.stop(0x0?, 0x0?, 0x68c0da0?, 0x0?)
        test/e2e/storage/drivers/csi-test/driver/driver.go:174 +0xa5 fp=0xc003a0ba50 sp=0xc003a0ba00 pc=0x5e8b9e5
k8s.io/kubernetes/test/e2e/storage/drivers/csi-test/driver.(*CSIDriver).Stop(...)
        test/e2e/storage/drivers/csi-test/driver/driver.go:133
k8s.io/kubernetes/test/e2e/storage/drivers.(*mockCSIDriver).PrepareTest.func2()
        test/e2e/storage/drivers/csi.go:605 +0x52 fp=0xc003a0ba98 sp=0xc003a0ba50 pc=0x5ef0cb2
k8s.io/kubernetes/test/e2e/storage/drivers.(*mockCSIDriver).PrepareTest.func4()
        test/e2e/storage/drivers/csi.go:692 +0x25 fp=0xc003a0bab0 sp=0xc003a0ba98 pc=0x5ef0925
```

### Relevant SIG(s)

/sig storage

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

After updating gRPC in node-driver-registrar from v1.40.0 to v1.47.0 the
behavior of gRPC change in a way such that it no longer detected the
single-sided closing of the stream as a loss of connection. This caused gRPC in
the e2e.test to get stuck, possibly in a Read or Write for the HTTP stream
because those have neither a context nor a timeout.

Changing the connection handling so that all active connections are tracked in
the listener and closing them when the listener gets closed fixed this problem.

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/112126

#### Special notes for your reviewer:

That the fix works cannot be tested in pre-merge jobs. I verified locally that it worked by patching the node-driver-registrar version to "canary".

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

File: test/e2e/storage/drivers/proxy/portproxy.go [hunk 1]
```diff
@@ -85,53 +93,50 @@ func Listen(ctx context.Context, clientset kubernetes.Interface, restConfig *res
...
+						if c == nil {
+							klog.V(5).Infof("%s: trying to create a new connection #%d", prefix, connectionsCreated)
+							stream, err := dial(ctx, fmt.Sprintf("%s #%d", prefix, connectionsCreated), dialer, addr.Port)
+							if err != nil {
+								klog.Errorf("%s: no connection: %v", prefix, err)
+								return
+							}
+							// Make the connection available to Accept below.
+							klog.V(5).Infof("%s: created a new connection #%d", prefix, connectionsCreated)
+							c := &connection{
```
Comment (jsafrane) [inline test/e2e/storage/drivers/proxy/portproxy.go:128]: Won't this create a busy loop? Before this PR, there was a channel that would block until `Accept()` is called, now it seems `runForwarding()` calls `dial()` every `connectionPollInterval`, creating new connections / streams. Will `dial()` block?

Comment (pohly) [reply test/e2e/storage/drivers/proxy/portproxy.go:128]: > Won't this create a busy loop?

It will poll at a regular, small interval. That's less efficient than the previous approach with the channel (small delay between "new connection available" and "Accept returns"; periodic wakeups), but should be good enough.

Comment (pohly) [reply test/e2e/storage/drivers/proxy/portproxy.go:128]: `dial` only gets called when there are less than `maxConcurrentConnections` active connections, so this won't create connections continuously.

Comment (jsafrane) [reply test/e2e/storage/drivers/proxy/portproxy.go:128]: Is goal of the code to really create 10 connections and then wait for 1 of them to get Accepted? I can see it works, but I find it odd.

Comment (jsafrane) [reply test/e2e/storage/drivers/proxy/portproxy.go:128]: Maybe a comment there would help.

Comment (pohly) [reply test/e2e/storage/drivers/proxy/portproxy.go:128]: The old code did the same: establishing connections is a lengthy process and was prone to timeouts. To avoid that, the proxy establishes up to 10 connections that are ready to carry bytes back and forth immediately when something connects to the remote listen socket. I thought that was explained somewhere, but it isn't - will add it.

Comment (pohly) [reply test/e2e/storage/drivers/proxy/portproxy.go:139]: Done as comment for maxConcurrentConnections.

**Comment by pohly** [comment]
/retest

Job didn't start.

**Comment by xing-yang** [comment]
Should we backport this to 1.25?

**Comment by pohly** [comment]
We don't have any failing tests with 1.25, so no?
