### PR TITLE
Fix "make help" info

### LINKED ISSUE #46911: "make help" should update help info.
These two places should update:

- BUILD is not a valid target
```
BUILD
# Add rules for all directories in cmd/
#
# Example:
#   make kubectl kube-proxy
```

- help info is incorrect
```
bazel-build
# Build release tars with bazel
#
# Example:
# make bazel-release
```

BTW, `make help` was introduced in #29683. I don't know how many contributors know this. For me, whenever I forget the detail of some target, I just run `make help` and get what I want. It would be good to document it somewhere, e.g. https://github.com/kubernetes/community/blob/master/contributors/devel/development.md

/sig contributor-experience
/assign

### PR DESCRIPTION
**Pull request by xiangpengzhao**
**What this PR does / why we need it**:
fixes some incorrect help info

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #46911

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: hack/verify-govet.sh [hunk 1]
```diff
@@ -28,7 +28,7 @@ if [[ "$#" -gt 0 ]]; then
     ARGHELP="WHAT='$@'"
 fi
 
-echo "NOTE: $0 has been replaced by 'make vet'"
+echo "NOTE: $0 has been replaced by 'make vet'. Run 'make help' for help."
```
Comment (cblecker) [inline hack/verify-govet.sh]: This script's usage is changing in https://github.com/kubernetes/kubernetes/pull/45984, and this message is being removed. We don't need to modify it here.

File: hack/build-cross.sh [hunk 2]
```diff
@@ -22,7 +22,7 @@ set -o pipefail
 
 KUBE_ROOT=$(dirname "${BASH_SOURCE}")/..
 
-echo "NOTE: $0 has been replaced by 'make cross'"
+echo "NOTE: $0 has been replaced by 'make cross'. Run 'make help' for help."
```
Comment (cblecker) [inline hack/build-cross.sh]: I don't think we need to modify these lines, as the specific command is already being called out.

**Review by cblecker — COMMENTED** [review]
Good fix to the Makefile. Couple of comments on the hack script changes.

File: hack/verify-govet.sh (hunk 1 above)
Comment (xiangpengzhao) [inline hack/verify-govet.sh]: Will address. Thanks for pointing this out!

File: hack/build-cross.sh (hunk 2 above)
Comment (xiangpengzhao) [inline hack/build-cross.sh]: Since these hack scripts are deprecated, I was thinking to add the info to make contributors have a chance to know `make help` if they're still using these scripts. 

I also thought to remove the invocation of the specific command in the script to discourage contributors from using these scripts. `hack/test-integration.sh` has already done this. But I don't know if this will break something, e.g. some contributors might have their own scripts calling these scripts.

@cblecker, WDYT? If it's okay, I will send a new seperate PR to fix this.

Comment (cblecker) [inline hack/build-cross.sh]: That's exactly why these scripts haven't been removed.. there are possibly other scripts calling these, so that deprecation message is to let them know to change the workflow. If there isn't something to be gained by breaking those workflows, then we shouldn't.

**Comment by xiangpengzhao** [comment]
inline comments addressed. PTAL @cblecker

File: hack/test-integration.sh [hunk 3]
```diff
@@ -28,6 +28,6 @@ echo "The following invocation will run all integration tests: "
 echo '    make test-integration'
 echo
 echo "The following invocation will run a specific test with the verbose flag set: "
-echo '    make test-integration WHAT=./test/integration/pods KUBE_GOFLAGS="-v" KUBE_TEST_ARGS="-run ^TestPodUpdateActiveDeadlineSeconds$"'
+echo '    make test-integration WHAT=./test/integration/pods GOFLAGS="-v" TEST_ARGS="-run ^TestPodUpdateActiveDeadlineSeconds$"'
```
Comment (xiangpengzhao) [inline hack/test-integration.sh]: `KUBE_GOFLAGS` and `KUBE_TEST_ARGS` are used inside the scripts. We'd better let users use `GOFLAGS` and `TEST_ARGS` instead to pass params.

Comment (xiangpengzhao) [inline hack/test-integration.sh]: NOTE: `KUBE_TEST_ARGS` should be left as-is.

**Comment by cblecker** [comment]
@k8s-bot ok to test
/release-note-none

File: hack/test-integration.sh [hunk 4]
```diff
@@ -28,6 +28,6 @@ echo "The following invocation will run all integration tests: "
 echo '    make test-integration'
 echo
 echo "The following invocation will run a specific test with the verbose flag set: "
-echo '    make test-integration WHAT=./test/integration/pods KUBE_GOFLAGS="-v" KUBE_TEST_ARGS="-run ^TestPodUpdateActiveDeadlineSeconds$"'
+echo '    make test-integration WHAT=./test/integration/pods GOFLAGS="-v" KUBE_TEST_ARGS="-run ^TestPodUpdateActiveDeadlineSeconds$"'
```
Comment (cblecker) [inline hack/test-integration.sh]: Let's actually remove this for now. The bigger issue around GOFLAGS is being addressed in #46923 which includes some other needed changes. No need to do the same thing in two PRs.

Comment (xiangpengzhao) [inline hack/test-integration.sh]: Thanks @cblecker ! I didn't notice that PR. Addressed. PTAL

**Comment by cblecker** [comment]
/unassign @lavalamp 

ping @jbeda for `build/` approval

**Comment by cblecker** [comment]
/assign @jbeda
for approval

**Comment by xiangpengzhao** [comment]
lgtm removed due to rebasing.
@cblecker @jbeda PTAL

**Comment by xiangpengzhao** [comment]
Thanks @cblecker !

Also
/assign @thockin 
Hope either @jbeda or @thockin has cycle to approve this. Thanks!

**Comment by xiangpengzhao** [comment]
rebased. @cblecker PTAL. Thanks!

/assign @ixdy 
for approval as you are also build owners. Thanks!

**Comment by cblecker** [comment]
/lgtm
again :)

**Comment by xiangpengzhao** [comment]
Thanks for your help, @cblecker !

:)

**Comment by xiangpengzhao** [comment]
Hmm, the `/approve` doesn't work...

ref: #48163

cc @spxtr

**Comment by xiangpengzhao** [comment]
It works after my last comment. Amazing...

**Comment by ixdy** [comment]
The munger sometimes misses events; not sure if that's what happened here. @cjwagner

**Comment by cjwagner** [comment]
> The munger sometimes misses events; not sure if that's what happened here. @cjwagner
I think thats what happened here. The logs show no changed issues around that time and the behavior was correct once the PR was updated again.

**Comment by xiangpengzhao** [comment]
Thanks @cjwagner and @ixdy for clarification!
