### PR TITLE
[FG:InPlacePodVerticalScaling] Fixed the apiserver panic issue that occurred when adding a container during pod updates in the InPlacePodVerticalScaling scenario.

### LINKED ISSUE #127282: [FG:InPlacePodVerticalScaling] error on method="PUT" URI="/api/v1/namespaces/default/pods/XX?fieldManager=kubectl-replace&fieldValidation=Strict"
### What happened?

error on kubectl replace cmd : error: error when replacing "/tmp/t1.yaml": Put "https://localhost:6443/api/v1/namespaces/default/pods/high-priority?fieldManager=kubectl-replace&fieldValidation=Strict": stream error: stream ID 5; INTERNAL_ERROR; received from peer 

On api server logs : 
```
E0911 00:12:42.298940  214100 wrap.go:57] "apiserver panic'd" method="PUT" URI="/api/v1/namespaces/default/pods/high-priority?fieldManager=kubectl-replace&fieldValidation=Strict" auditID="d82cb6f9-3244-4002-8575-ffa99805d451"
http2: panic serving 127.0.0.1:44790: runtime error: index out of range [1] with length 1
goroutine 44578 [running]:
k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest.func1.1()
        k8s.io/apiserver/pkg/endpoints/handlers/finisher/finisher.go:105 +0xa5
panic({0x33a7b20?, 0xc00af7b950?})
        runtime/panic.go:770 +0x132
k8s.io/kubernetes/pkg/api/pod.MarkPodProposedForResize(0xc00a9c8488, 0xc00a9c8d88)
        k8s.io/kubernetes/pkg/api/pod/util.go:1238 +0x371
k8s.io/kubernetes/pkg/registry/core/pod.podStrategy.PrepareForUpdate({{0x7f6ce61f0518?, 0x5a45760?}, {0xc0077da860?, 0x145d6e5?}}, {0xa?, 0x35677e0?}, {0x3c62268?, 0xc00a9c8d88}, {0x3c62268, 0xc00a9c8488})
        k8s.io/kubernetes/pkg/registry/core/pod/strategy.go:110 +0xe9
k8s.io/apiserver/pkg/registry/rest.BeforeUpdate({0x3c9e980, 0xc000626520}, {0x3c88f40, 0xc007016b40}, {0x3c62268, 0xc00a9c8d88}, {0x3c62268, 0xc00a9c8488})
        k8s.io/apiserver/pkg/registry/rest/update.go:129 +0x243
k8s.io/apiserver/pkg/registry/generic/registry.(*Store).Update.func1({0x3c62268, 0xc00a9c8488}, {0xc00947d3b0?, 0x35f7afb?})
```

### What did you expect to happen?

api server return this error : The Pod "XXX" is invalid: spec.containers: Forbidden: pod updates may not add or remove containers 

### How can we reproduce it (as minimally and precisely as possible)?

1-start the cluster with FEATURE_GATE ENABLED (InPlacePodVerticalScaling)
2- create a pod with one container , for example : 
`apiVersion: v1
kind: Pod
metadata:
  name: high-priority
spec:
  containers:
  - name: high-priority
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
      limits:
        memory: "10Mi"
        cpu: "10m"
		`
3- try  to replace (without force) with ( + container) : 
`apiVersion: v1
kind: Pod
metadata:
  name: high-priority
spec:
  containers:
  - name: high-priority
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
      limits:
        memory: "10Mi"
        cpu: "10m"
  - name: high-priority-1
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    resources:
      requests:
        memory: "10Mi"
        cpu: "10m"
      limits:
        memory: "10Mi"
        cpu: "10m"`
kubectl --kubeconfig /var/run/kubernetes/admin.kubeconfig replace -f /tmp/t1.yaml  

**ERROR** : Put "https://localhost:6443/api/v1/namespaces/default/pods/high-priority?fieldManager=kubectl-replace&fieldValidation=Strict": stream error: stream ID 5; INTERNAL_ERROR; received from peer 

### Anything else we need to know?

using the master (commit : 139cc3c659dd1624f7a4bbcc3b07fda79539677a )

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: v1.31.0-beta.0.854+4cfdad0935cfb7-dirty
```

</details>

### Cloud provider

<details>
locally 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux 20231797-MARBT 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>
containerD
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by zhifei92**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Before upgrading a pod, the kube-apiserver validates the pod using strategy.ValidateUpdate. Adding or removing containers from the pod is deemed invalid. However, strategy.PrepareForUpdate(MarkPodProposedForResize is called) is invoked prior to strategy.ValidateUpdate, causing a panic when InPlacePodVerticalScaling is enabled.

#### Which issue(s) this PR fixes:

Fixes #127282

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/api/pod/util.go [hunk 1]
```diff
@@ -1231,6 +1231,10 @@ func hasInvalidLabelValueInAffinitySelector(spec *api.PodSpec) bool {
 }
 
 func MarkPodProposedForResize(oldPod, newPod *api.Pod) {
+	if len(newPod.Spec.Containers) != len(oldPod.Spec.Containers) {
```
Comment (bouaouda-achraf) [inline pkg/api/pod/util.go:1234]: why not iterate through a merged list of containers with a container name existing on both newPod.Spec.Containers and oldPod.Spec.Containers?  (instead of ignoring the rest of execution when len is not equal)

**Comment by bouaouda-achraf** [comment]
Should we consider adding a test case related to this issue? It could help catch it during a pipeline stage.

File: pkg/api/pod/util.go (hunk 1 above)
Comment (zhifei92) [reply pkg/api/pod/util.go:1234]: Since modifying the number of containers is not supported during pod updates, there is no need to perform any further operations if the lengths are unequal.

File: pkg/api/pod/util_test.go [hunk 2]
```diff
@@ -3047,6 +3047,207 @@ func TestMarkPodProposedForResize(t *testing.T) {
 	}
 }
 
+func TestMarkPodProposedForResizeWithUnexpectedContainers(t *testing.T) {
```
Comment (tallclair) [inline pkg/api/pod/util_test.go:3050]: The testcase function for this looks identical to the previous test. Unless I'm missing something, just add these test cases to `TestMarkPodProposedForResize`

Comment (zhifei92) [reply pkg/api/pod/util_test.go]: Indeed, thank you.

File: pkg/api/pod/util.go (hunk 1 above)
Comment (tallclair) [reply pkg/api/pod/util.go:1258]: Maybe add a comment to that effect?
```
// Update is invalid: ignore changes and let validation handle it
```

**Comment by knabben** [comment]
Hello @tallclair @zhifei92 
The code freeze is starting 02:00 UTC Friday November 8th 2024 (about 2 weeks from now), and while there is still time, we want to ensure that each PR has a chance to be merged on time. Just a gently reminder of the date since PR is progressing.
Thank you!

**Comment by zhifei92** [comment]
@tallclair Hi, can this PR be merged now?

File: pkg/api/pod/util.go (hunk 1 above)
Comment (tallclair) [reply pkg/api/pod/util.go:1258]: Can you add this comment? Then I'll track down an API review for you :)

File: pkg/api/pod/util_test.go [hunk 3]
```diff
@@ -3036,6 +3036,189 @@ func TestMarkPodProposedForResize(t *testing.T) {
 				},
 			},
 		},
+		{
+			desc: "the number of containers in the pod has decreased; no action should be taken.",
```
Comment (tallclair) [inline pkg/api/pod/util_test.go:3040]:
```suggestion
			desc: "the number of containers in the pod has increased; no action should be taken.",
```

File: pkg/api/pod/util_test.go [hunk 4]
```diff
@@ -3036,6 +3036,189 @@ func TestMarkPodProposedForResize(t *testing.T) {
...
+							Name:               "c2",
+							Image:              "image",
+							AllocatedResources: api.ResourceList{api.ResourceCPU: resource.MustParse("200m")},
+						},
+					},
+				},
+			},
+		},
+		{
+			desc: "the number of containers in the pod has increased; no action should be taken.",
```
Comment (tallclair) [inline pkg/api/pod/util_test.go:3138]:
```suggestion
			desc: "the number of containers in the pod has decreased; no action should be taken.",
```

**Comment by tallclair** [comment]
Please add the comment to the validation, and fix the test names.

File: pkg/api/pod/util.go (hunk 1 above)
Comment (zhifei92) [reply pkg/api/pod/util.go:1258]: > Maybe add a comment to that effect?

Sorry for missing this comment.

**Comment by tallclair** [comment]
/assign @thockin 
for api approval

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by zhifei92** [comment]
@tallclair Hi, this issue was found in v1.31, so does this PR need to be cherry-picked to v1.31?

**Comment by tallclair** [comment]
I don't think we usually backport fixes for alpha features, at least not for corner cases like this.

**Comment by zhifei92** [comment]
> I don't think we usually backport fixes for alpha features, at least not for corner cases like this.

get
