### PR TITLE
cpuPeriod was not reset

### LINKED ISSUE #73264: --cpu-cfs-quota-period should not have effect if feature gate CPUCFSQuotaPeriod is not enabled
**What happened**:
When run kubelet with "--cpu-cfs-quota-period 1000ms"  and without --feature-gates=CustomCPUCFSQuotaPeriod=true, kubelet would set cgroup cpu.cfs_period_us to 1000000, but make calculation based on a default value of 100000, this means if a pod has a limit of 100m, it would have a quota of 10000,  causing its limit set to 10m actually.

**What you expected to happen**:
If the cfs gate is not enabled, the "--cpu-cfs-quota-period" option should not take effect at all.

**How to reproduce it (as minimally and precisely as possible)**:
Start kubelet with "--cpu-cfs-quota-period 1000ms", and run a pod with limit set to some value, then the pod's runtime limit, which is only 10%.

**Anything else we need to know?**:
https://github.com/kubernetes/kubernetes/blob/9ce03717a90f9482436b85b512ee482374c57880/pkg/kubelet/cm/helpers_linux.go#L61-L63
The code above reset the period to default when calculating quota, but the runtime period is not reset.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by szuecs**
```release-note
fix #73264 cpuPeriod was not reset, but used as set via flag, although it was disabled via alpha gate
```

Signed-off-by: Sandor Szücs <sandor.szuecs@zalando.de>

### CODE REVIEW

File: pkg/kubelet/kuberuntime/helpers_linux.go [hunk 1]
```diff
@@ -49,7 +49,7 @@ func milliCPUToShares(milliCPU int64) int64 {
 }
 
 // milliCPUToQuota converts milliCPU to CFS quota and period values
-func milliCPUToQuota(milliCPU int64, period int64) (quota int64) {
+func milliCPUToQuota(milliCPU int64, period int64) (quota int64, p int64) {
```
Comment (dashpole) [inline pkg/kubelet/kuberuntime/helpers_linux.go]: IMO both inputting and returning the period seems strange.
Could we instead move the feature gate check to `kuberuntime_container_linux.go`, and pass the _actual_ period we are using to this function?

I.E.
```
if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.CPUCFSQuotaPeriod) {
    period = int64(m.cpuCFSQuotaPeriod.Duration / time.Microsecond)
} else {
    period = quotaPeriod
}
```

That way it is clear what the feature gate changes, and we avoid confusion from "set to X, and then reset to Y" confusion.

Comment (szuecs) [reply pkg/kubelet/kuberuntime/helpers_linux.go]: Thanks for the suggestion, makes much more sense.
I pushed a fix for the commented code.

**Comment by dashpole** [comment]
Looks much better!
/lgtm

**Comment by szuecs** [comment]
@dchen1107 or @dims could you review this fix please? 
Thanks!

**Comment by szuecs** [comment]
@yujuhong or @Random-Liu could you review this PR please, thanks!
