### PR TITLE
Fix test cases that may potentially cause a panic.

### LINKED ISSUE #130689: Fix TestWithAuditConcurrency unit tests
See related discussion https://github.com/kubernetes/kubernetes/pull/130359/files/d92c70b82693f3c974e63dcf7abd2d5068c0530c#r1976441804

_Originally posted by @aojea in https://github.com/kubernetes/kubernetes/pull/130359#discussion_r1987292559_

### PR DESCRIPTION
**Pull request by novahe**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:

Fixes #130689

#### Special notes for your reviewer:
In a test code block running in a goroutine, using the combination of `t.Errorf` and `return` better conforms to Go testing conventions.
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by novahe** [comment]
PTAL @aojea

File: pkg/client/tests/remotecommand_test.go [hunk 1]
```diff
@@ -123,7 +123,7 @@ func fakeServer(t *testing.T, requestReceived chan struct{}, testName string, ex
 
 		opts, err := remotecommand.NewOptions(req)
 		if err != nil {
-			t.Errorf("unexpected error %v", err)
+			t.Fatalf("unexpected error %v", err)
```
Comment (aojea) [inline pkg/client/tests/remotecommand_test.go:126]: this is running in a http handler , is t.Fatalf vald here?

Comment (aojea) [reply pkg/client/tests/remotecommand_test.go:126]: yes it is

**Comment by aojea** [comment]
/lgtm
/approve

/hold

holding, I like Patrick to take a look 
/assign @pohly

**Comment by aojea** [comment]
/assign @thockin 
for wide approval

**Review by thockin — COMMENTED** [review]
/approve
/hold

File: pkg/client/tests/remotecommand_test.go (hunk 1 above)
Comment (pohly) [reply pkg/client/tests/remotecommand_test.go:126]: "Works" in which sense?

This is functionally identical to `require.NoError(t, err)`, which is what was replaced here earlier in https://github.com/kubernetes/kubernetes/pull/130359/files/d92c70b82693f3c974e63dcf7abd2d5068c0530c#diff-4d42d246d1b76fdc923fe9200abd73d388eb62382f10e3edbe5196a883982657. By calling `t.Fatalf`, we are back where we started...

`go vet` doesn't complain about such a `t.Fatal` call here. The testify linter is stricter and points out the `require.NoError` call:

```
ERROR: pkg/client/tests/remotecommand_test.go:128:3: go-require: do not use require in http handlers (testifylint)
ERROR: 		require.NoError(t, err)
ERROR: 		^
```

But linters aren't perfect, so let's look at how this fails.

When I run this test so that it always calls `t.Fatal("fake error")` here, `testing.T.Fatal` kills the goroutine which handles the HTTP request via `runtime.Goexit`. This is probably not what we want.

It causes the test to fail, but in a weird way:
```
=== RUN   TestStream/error_(exec)
    remotecommand_test.go:127: fake error
    remotecommand_test.go:272: error (exec): expected error stream read "bail", got "error sending request: Post \"http://127.0.0.1:36437/testing?command=ls&command=%2F&output=1\": unexpected EOF"
```

When returning after `t.Error`, it becomes:
```
=== RUN   TestStream/error_(exec)
    remotecommand_test.go:123: fake error
    remotecommand_test.go:270: error (exec): expected error stream read "bail", got ""
```

Still one follow-up error, but a bit less noisy. I think this is better and relies less on implementation details of the http package. It seems to be fairly resilient against misbehaving http handlers, but better not count on it...

TLDR: don't use t.Fatal in http handlers.

Comment (pohly) [reply pkg/client/tests/remotecommand_test.go]: https://pkg.go.dev/testing#T.FailNow:

> FailNow must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test.

https://pkg.go.dev/testing#T.Fatal:

> Fatal is equivalent to Log followed by FailNow. 

This is what https://github.com/kubernetes/kubernetes/issues/130346 was about.

**Comment by novahe** [comment]
fixed, In a test code block running in a goroutine, using the combination of `t.Errorf` and `return` better conforms to Go testing conventions.

File: pkg/client/tests/remotecommand_test.go (hunk 1 above)
Comment (aojea) [reply pkg/client/tests/remotecommand_test.go]: thanks for clarifying, I was indeed surprised when I saw this since it is the same as before ... so maybe I thought it was worse than it is  ... I just got worried when I was modifying some code and the test was not failing when it was supposed to fail , but now I can see maybe there were more things and this was a red herring ... sorry about that

Comment (pohly) [reply pkg/client/tests/remotecommand_test.go]: > I was modifying some code and the test was not failing when it was supposed to fail , but now I can see maybe there were more things and this was a red herring

I was indeed a bit puzzled by that comment. `t.Fatal` should mark the test as failed reliably with `t.Error`, it's just the ensuing `t.FailNow` which doesn't quite work as expected. Probably something else was amiss.

**Review by pohly — APPROVED** [review]
/lgtm
