### PR TITLE
sched: fix a bug that a preemptor pod exists as a phantom

### LINKED ISSUE #102339: Scheduler occasionally has stale state and does not assign pods to nodes that could fit them
We have a Kubernetes cluster with version v1.19.7.  We have observed that sometimes the kubernetes scheduler does not schedule pods on nodes that are available for them, and the pods remain pending. We added some custom logs to the scheduler code and we were able to determine that when this happens, the scheduler thinks that there is a pod on the available node, even though that pod no longer exists in the cluster.

#### What happened:

From our debugging, here’s the sequence of events we have observed:

1. A pause pod P is running on an existing node N in a certain node pool. This pause pod exists simply to overprovision the node pool.
2. A new pod X, which takes up most of a node, preempts the pause pod P.
3. The new pod X is deleted as part of a scale down, before it is bound to node N.
4. The node N is removed from the cluster (either scaled down because of underutilization or preempted).
5. The scheduler removes the node N from the node tree.
6. Later, a new node is added to the cluster, with the same name N as the previous node. It could be in the same or different node pool.
7. The scheduler adds the new node N to the node tree.
8. The autoscaler (correctly) decides that a pending pod Y can be scheduled on the node N as it has the resources and taints to fit the pod.
9. The scheduler does not schedule the pod Y on the node N. From our debug logs, we discovered that in such cases, the scheduler thinks pod X is still on the node, even though the pod was never bound to the node, and the node has since been removed and re-added to the cluster ([this is where we added this log statement](https://github.com/kubernetes/kubernetes/blob/v1.19.7/pkg/scheduler/framework/plugins/noderesources/fit.go#L226)).

`CUSTOMLOG: Pod scaletest-5b9589-mbm4f requests 13000 cpu, 62277025792 memory (13000 cpu, 62277025792 memory). Node c-10-92-64-72.cloud.domain.com has 6 pods, 26161/15000 used/allocatable cpu, 135285178368/66375368704 used/allocatable memory. Pods in node: admin-namespace/node-problem-detector-cpk5f/00621b52-fc6e-4786-90d8-c9db3ed0877c,gcp-csi-namespace/csi-gce-pd-node-xt8c8/3d172e2b-572d-4497-8098-6e63c7002823,kube-system/kp-c-10-92-64-72.cloud.domain.com/b4af72c6-6306-4006-b8ee-03077312c8e2,admin-namespace/fluent-bit-node-omega-vswwn/82c144df-6b29-4d03-a79d-c1541d71f7a6,datadog-namespace/datadog-agent-zzl2m/7a79591f-5115-44ef-b980-b0fa6a051d40,mynamespace/podX/bb59f18d-7ad5-455e-a4e8-61525ac81f52. InsufficientResources?: Insufficient cpu,Insufficient memory`

From the node’s describe:

```
Non-terminated Pods:          (5 in total)
 Namespace         Name                              CPU Requests CPU Limits  Memory Requests Memory Limits AGE
 ---------         ----                              ------------ ----------  --------------- ------------- ---
 admin-namespace   fluent-bit-node-omega-vswwn       501m (3%)    1501m (10%) 818Mi (1%)      1074Mi (1%)   28m
 admin-namespace   node-problem-detector-cpk5f       0 (0%)       0 (0%)      0 (0%)          0 (0%)        28m
 kube-system       kp-c-10-92-64-72.cloud.domain.com 500m (3%)    500m (3%)   2Gi (3%)        2Gi (3%)      27m
 datadog-namespace datadog-agent-zzl2m               60m (0%)     10m (0%)    1Gi (1%)        64Mi (0%)     28m
 gcp-csi-namespace csi-gce-pd-node-xt8c8             0 (0%)       0 (0%)      0 (0%)          0 (0%)        28m
```

Notice that the rest of the pods on the node (according to kubectl describe) match what the scheduler thinks is on the node; only the last pod is different. It is present on the node according to the scheduler, but not according to kubectl describe.

10. Restarting the scheduler makes it so that the pod Y is correctly scheduled on node N.

#### What you expected to happen:
Pod to be scheduled on the node without needing to restart the scheduler.

#### How to reproduce it (as minimally and precisely as possible):
The issue might be hard to reproduce since it appears to be a race condition, but here are the steps based on what we have observed:

1. Have a cluster with pod preemption enabled.
2. Have a pod with a low priority scheduled on a node.
3. Have a pod with a high priority preempt the pod with the low priority (which, if still present, would be too large to allow the later pod to be scheduled).
4. Delete the high priority pod before it is actually scheduled on the node. We believe the nominated node name is set, but not the node name, but don’t have proof of this.
5. Delete the node from the cluster (this might be optional), then add it back in with the same name.
6. Have a new pod that can be scheduled on the node.

#### Anything else we need to know?:
Cluster Configuration
We are running our own deployment of Kubernetes v1.19.7 on GCP (not using GKE). It scales from 250 nodes to 1200 nodes (average around 600 nodes). Pod count ranges from 2k to 7k (average around 4.5k pods). We have two clusters with this setup, and we observe the issue in both.

Node Pool Configuration
We have different node pools (with multiple managed instance groups for each). Our node names are based on the node’s IP. With nodes scaling up and down in the cluster, node names are often reused, so it is common for a node to disappear from one node pool and eventually reappear in a different one.

Kube-Scheduler Configuration
The configuration of kube-scheduler is:
```
    --kubeconfig=/etc/kubernetes/scheduler-kubeconfig.yaml \
    --v=4 \
    --logtostderr=false \
    --skip-log-headers=true \
    --log-file=/srv/k8s/logs/scheduler.log \
    --address=0.0.0.0 \
    --leader-elect=true \
    --leader-elect-lease-duration 65s \
    --leader-elect-renew-deadline 60s \
    --kube-api-qps=100 \
```

Autoscaler Configuration
We run a version of the open-source [autoscaler](https://github.com/kubernetes/autoscaler). We also use pause pods with negative priority to enable faster scale up for some workloads. We have not seen the issue before we started using pause pods.

/sig scheduling
/cc @alculquicondor

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind bug
/kind regression
/sig scheduling

#### What this PR does / why we need it:

When recording the failure reason of an unschedulable Pod, it may be deleted physically elsewhere. In such case, we shouldn't proceed with updating nor update it in internal `nominatedPodMap` (if it's a preemptor that carries nomiantedNode); otherwise, we may see some unexpected behavior like #102339.

This issue surfaced since v1.19.

#### Which issue(s) this PR fixes:

Fixes #102339

#### Does this PR introduce a user-facing change?

```release-note
Fix a regression in 1.19+ that a preemptor pod may exist as a phantom in the scheduler.
```

### CODE REVIEW

File: pkg/scheduler/factory.go [hunk 1]
```diff
@@ -357,21 +357,21 @@ func MakeDefaultErrorFunc(client clientset.Interface, podLister corelisters.PodL
 		// Check if the Pod exists in informer cache.
 		cachedPod, err := podLister.Pods(pod.Namespace).Get(pod.Name)
 		if err != nil {
-			klog.InfoS("Pod doesn't exist in informer cache", "pod", klog.KObj(pod), "err", err)
-			return
+			return fmt.Errorf("pod doesn't exist in informer cache")
```
Comment (alculquicondor) [inline pkg/scheduler/factory.go:360]: Is the only error that the Lister report for not found? Otherwise, we can do

`fmt.Errorf("reloading pod from cache: %w", err)`

File: pkg/scheduler/scheduler.go [hunk 2]
```diff
@@ -356,7 +356,13 @@ func (sched *Scheduler) Run(ctx context.Context) {
 // recordSchedulingFailure records an event for the pod that indicates the
 // pod has failed to schedule. Also, update the pod condition and nominated node name if set.
 func (sched *Scheduler) recordSchedulingFailure(fwk framework.Framework, podInfo *framework.QueuedPodInfo, err error, reason string, nominatedNode string) {
-	sched.Error(podInfo, err)
+	// An error may be returned. For example, a Pod being deleted elsewhere or assigned a node name.
+	// In either case, we should return immediately; otherwise, the pod may be held inside
+	// scheduler queue as a phantom and cause unexpected behavior afterwards. (see #102339)
+	if err := sched.Error(podInfo, err); err != nil {
+		klog.InfoS(fmt.Sprintf("%v, abort adding it back to queue", err), "pod", klog.KObj(podInfo.Pod), "node", podInfo.Pod.Spec.NodeName)
```
Comment (alculquicondor) [inline pkg/scheduler/scheduler.go:363]: You have to adhere to this https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#remove-string-formatting-from-log-message

And you can include the error as part of the message https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#using-errors

I don't think we should include the node as a key.

**Review by alculquicondor — COMMENTED** [review]
Can we add a test?

File: pkg/scheduler/factory.go (hunk 1 above)
Comment (Huang-Wei) [reply pkg/scheduler/factory.go:360]: How about `fmt.Errorf("obtaining pod from cache: %w", err)`?

**Comment by Huang-Wei** [comment]
> Can we add a test?

It needs a precisely designed timing - the preemptor pod just starts its 2nd scheduling (i.e., .status.nominatedNodeName been set), and meanwhile it's deleted. Let me think about it.

File: pkg/scheduler/scheduler.go (hunk 2 above)
Comment (Huang-Wei) [reply pkg/scheduler/scheduler.go]: Probably we can change it to an error. Updated, PTAL.

Comment (alculquicondor) [reply pkg/scheduler/scheduler.go]: InfoS should be fine, but that's a nit.

**Comment by alculquicondor** [comment]
Maybe a test can be simulated at unit level? That should be fine. We just need to make sure there are no more regressions in the future.

File: pkg/scheduler/factory.go [hunk 3]
```diff
@@ -357,21 +357,21 @@ func MakeDefaultErrorFunc(client clientset.Interface, podLister corelisters.PodL
 		// Check if the Pod exists in informer cache.
 		cachedPod, err := podLister.Pods(pod.Namespace).Get(pod.Name)
 		if err != nil {
-			klog.InfoS("Pod doesn't exist in informer cache", "pod", klog.KObj(pod), "err", err)
-			return
+			return fmt.Errorf("obtaining pod from cache: %w", err)
```
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/factory.go:360]: Technically that's possible but quite rare. To keep it 100% away from the timing issue, we may have to verify if the pod exists inside nominatedPodMap#AddNominatedPod(), but sounds too much?

[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/scheduler/factory.go:360]: > Technically that's possible but quite rare. To keep it 100% away from the timing issue, we may have to verify if the pod exists inside nominatedPodMap#AddNominatedPod(), but sounds too much?

A race condition is a race condition, addressing that is never "too much" :) The original issue we are addressing is also "rare", but at scale becomes noticeable. We need to make sure that the pod exists while holding the queue lock.

[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/factory.go]: I compared the code with v1.18. In 1.18, we sort of immediately add the nominated node info (in preempt()), but it also has chances to be racing with a PodDelete event. (if the delete event occurs [after L410 and before L421](https://github.com/kubernetes/kubernetes/blob/v1.18.19/pkg/scheduler/scheduler.go#L410-L421)).

While since 1.19, we delayed the action to update the nominated node intentionally (#91535) to save one API update operation, and hence the racing issue is more noticeable.

To absolutely eliminate the racing issue, I revised the solution to introduce a `SafePodNominator` and add a UT. @ahg-g @alculquicondor PTAL.

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 4]
```diff
@@ -767,6 +767,8 @@ func newUnschedulablePodsMap(metricRecorder metrics.MetricRecorder) *Unschedulab
 // may be different than what scheduler has here. We should be able to find pods
 // by their UID and update/delete them.
 type nominatedPodMap struct {
+	// podAlive is a function to verify if the given pod is alive.
+	podAlive func(pod *v1.Pod) bool
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/queue/scheduling_queue.go:771]: Use a function over a field (like podLister), so tests that don't care about this can simply inject a dummy alwaysTrue function.

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 5]
```diff
@@ -767,6 +767,8 @@ func newUnschedulablePodsMap(metricRecorder metrics.MetricRecorder) *Unschedulab
 // may be different than what scheduler has here. We should be able to find pods
 // by their UID and update/delete them.
 type nominatedPodMap struct {
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/queue/scheduling_queue.go:769]: TODO: will rename it to nominator once we agree on the solution.

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 6]
```diff
@@ -844,6 +852,18 @@ func (npm *nominatedPodMap) UpdateNominatedPod(oldPod *v1.Pod, newPodInfo *frame
 // NewPodNominator creates a nominatedPodMap as a backing of framework.PodNominator.
```
Comment (alculquicondor) [inline pkg/scheduler/internal/queue/scheduling_queue.go:852]: We should mark this as deprecated, and eventually make all test use the real nominator.

After this change, which kind of tests still use this?

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 7]
```diff
@@ -844,6 +852,18 @@ func (npm *nominatedPodMap) UpdateNominatedPod(oldPod *v1.Pod, newPodInfo *frame
...
+		podAlive:           func(_ *v1.Pod) bool { return true },
+		nominatedPods:      make(map[string][]*framework.PodInfo),
+		nominatedPodToNode: make(map[types.UID]string),
+	}
+}
+
+// NewSafePodNominator creates a nominatedPodMap as a backing of framework.PodNominator.
+// Unlike NewPodNominator, it passes in a function to check if the pod is alive before
+// adding its nominatedNode info.
+func NewSafePodNominator(podAlive func(pod *v1.Pod) bool) framework.PodNominator {
```
Comment (alculquicondor) [inline pkg/scheduler/internal/queue/scheduling_queue.go:864]: can we make this accept the lister?

File: pkg/scheduler/internal/queue/scheduling_queue_test.go [hunk 8]
```diff
@@ -643,6 +644,46 @@ func TestPriorityQueue_NominatedPodsForNode(t *testing.T) {
...
+			podInfo: highPriorityPodInfo,
+			want:    false,
+		},
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			// Simulate that highPriNominatedPod gets deleted physically.
+			nominator := NewSafePodNominator(func(pod *v1.Pod) bool {
+				return pod.Name != highPriNominatedPodInfo.Pod.Name
```
Comment (alculquicondor) [inline pkg/scheduler/internal/queue/scheduling_queue_test.go:674]: Can we use the real method here?

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 6 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go:852]: Making this as deprecated sounds good.

Here are the tests using it:

```
pkg/scheduler/scheduler_test.go
834:		frameworkruntime.WithPodNominator(internalqueue.NewPodNominator()),

pkg/scheduler/core/extender_test.go
274:				runtime.WithPodNominator(internalqueue.NewPodNominator()),

pkg/scheduler/core/generic_scheduler_test.go
1000:				frameworkruntime.WithPodNominator(internalqueue.NewPodNominator()),
1063:		frameworkruntime.WithPodNominator(internalqueue.NewPodNominator()),
1096:		frameworkruntime.WithPodNominator(internalqueue.NewPodNominator()),
1170:				frameworkruntime.WithPodNominator(internalqueue.NewPodNominator()),
1332:				frameworkruntime.WithPodNominator(internalqueue.NewPodNominator()),
1435:		frameworkruntime.WithPodNominator(internalqueue.NewPodNominator()),
1521:				frameworkruntime.WithPodNominator(internalqueue.NewPodNominator()),

pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go
289:				frameworkruntime.WithPodNominator(internalqueue.NewPodNominator()),
1006:				frameworkruntime.WithPodNominator(internalqueue.NewPodNominator()),
1233:				frameworkruntime.WithPodNominator(internalqueue.NewPodNominator()),
1638:				frameworkruntime.WithPodNominator(internalqueue.NewPodNominator()),

pkg/scheduler/framework/runtime/framework_test.go
1482:			podNominator := internalqueue.NewPodNominator()
```

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 7 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go:864]: As I mentioned in https://github.com/kubernetes/kubernetes/pull/102498#discussion_r645053765, I tend of pass in a function rather than restraining it to a podLister, so callers (tests or other integrators) can easily build this.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 8 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:674]: Maybe not worth it - the real method appears bug-free, doesn't it?

```go
func(pod *v1.Pod) bool {
    _, err := c.informerFactory.Core().V1().Pods().Lister().Pods(pod.Namespace).Get(pod.Name)
    return err == nil
}
```

If you are concerned, I can write a test covering it.

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 7 above)
Comment (alculquicondor) [reply pkg/scheduler/internal/queue/scheduling_queue.go:864]: Tests should be using the prod behavior when possible.

File: pkg/scheduler/internal/queue/scheduling_queue_test.go (hunk 8 above)
Comment (alculquicondor) [reply pkg/scheduler/internal/queue/scheduling_queue_test.go:674]: Note that there is no unit test providing coverage for the nominator that we use in production. Someone could change the passed function and potentially break users.

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 6 above)
Comment (ahg-g) [reply pkg/scheduler/internal/queue/scheduling_queue.go:852]: why not just remove it in this PR?

Comment (alculquicondor) [reply pkg/scheduler/internal/queue/scheduling_queue.go:852]: I'd leave it for a 2nd PR just so that this PR is easier to port

Comment (ahg-g) [reply pkg/scheduler/internal/queue/scheduling_queue.go:852]: sg if we are planning to cherrypick.

File: pkg/scheduler/factory.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/scheduler/factory.go]: Thanks Wei, sounds good to me, but I agree with Aldo, lets make it straightforward and pass in the lister.

**Comment by Huang-Wei** [comment]
Updated to explicitly a podLister instead of a function, also the UT adheres to the prod behavior.

@ahg-g @alculquicondor To ease backporting, I will use a follow-up to cleanup the usage of NewPodNominator in the tests.

**Comment by ahg-g** [comment]
/lgtm
/approve
/hold

feel free to remove the hold

**Review by alculquicondor — COMMENTED** [review]
/hold cancel

Thanks!

**Comment by alculquicondor** [comment]
Please backport to all supported versions

**Comment by Huang-Wei** [comment]
Created 3 cherry-pick prs.
