### PR TITLE
Move govet verify into rest of verify*-.sh scripts

### LINKED ISSUE #2725: When go-vet fails it isn't neatly highlighted in the gubernator output
See:

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45603/pull-kubernetes-verify/29184/

For example. Lots of spurious "error" messages are highlighted, but the actual problem is hidden behind some skipped lines.

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Instead of having two govet scripts, consolidate them to into one and have both the Makefile and verify.sh scripts target the same script. This also will allow proper syntax highlighting and timing when the vet script is run as part of `make verify`.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/kubernetes/test-infra/issues/2725

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

/cc @fejta @rmmh

### CODE REVIEW

**Comment by cblecker** [comment]
@k8s-bot gce etcd3 e2e test this

File: hack/verify-govet.sh [hunk 1]
```diff
@@ -14,24 +14,36 @@
...
 set -o pipefail
 
 KUBE_ROOT=$(dirname "${BASH_SOURCE}")/..
+source "${KUBE_ROOT}/hack/lib/init.sh"
+
+cd "${KUBE_ROOT}"
+
+# This is required before we run govet for the results to be correct.
+# See https://github.com/golang/go/issues/16086 for details.
+make generated_files
```
Comment (rmmh) [inline hack/verify-govet.sh]: this feels fishy

File: Makefile [hunk 2]
```diff
@@ -341,7 +340,7 @@ vet:
 	@echo "$$VET_HELP_INFO"
 else
 vet:
```
Comment (rmmh) [inline Makefile]: let's make this depend on verify_generated_files too

**Comment by rmmh** [comment]
For context, #25978 by @thockin moved this out.

I'm not sure that the recursive make is the best/safest solution here.

File: hack/verify-govet.sh (hunk 1 above)
Comment (cblecker) [inline hack/verify-govet.sh]: Github doesn't show it, but I literally just moved `hack/make-rules/vet.sh` to `hack/verify-govet.sh` and changed the BASH_SOURCE line to have one less `/..`

**Comment by cblecker** [comment]
Hmm okay. The picture is becoming a bit clearer. Let me see what I can do.

**Comment by cblecker** [comment]
/cc @ixdy 
In tracing back some of the history here, the reason generated_files needs to be run first looks like a go issue with how vet works (something @ixdy opened an issue with the golang team about). I believe the way the way I've changed the scripts around should work in a bit of a safer way, and get us to the goals of:
- run steps like this using make so that eventually we can move away from committing generated files
- run go vet using the verify.sh script in CI, so that FAILED/SUCCESS and timing messages are put into the build log.

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
@k8s-bot kops aws e2e test this

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by cblecker** [comment]
From my testing PR (https://github.com/kubernetes/kubernetes/pull/46155):
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/46155/pull-kubernetes-verify/30855/
```
I0519 18:05:12.943] Verifying hack/make-rules/../../hack/verify-govet.sh
W0519 18:05:38.326] cmd/kube-proxy/app/conntrack.go:124: wrong number of args for format in Errorf call: 1 needed but 2 args
W0519 18:05:38.328] exit status 1
I0519 18:06:12.497] Makefile:343: recipe for target 'vet' failed
I0519 18:06:12.499] FAILED   hack/make-rules/../../hack/verify-govet.sh	60s
I0519 18:06:12.499] Verifying hack/make-rules/../../hack/verify-import-boss.sh
W0519 18:06:12.600] make[1]: *** [vet] Error 1
[..snip..]
I0519 18:19:52.709] Makefile:123: recipe for target 'verify' failed
W0519 18:19:52.809] make: *** [verify] Error 1
```

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by cblecker** [comment]
@rmmh @ixdy Is there a chance of this getting reviewed before code freeze (EOD 6/1)?

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by cblecker** [comment]
/assign @ixdy 
for approval :)

File: hack/make-rules/vet.sh [hunk 3]
```diff
@@ -25,8 +25,14 @@ cd "${KUBE_ROOT}"
 
 # This is required before we run govet for the results to be correct.
 # See https://github.com/golang/go/issues/16086 for details.
-make generated_files
-go install ./cmd/...
+# If called directly, exit.
+CALLED_FROM_MAIN_MAKEFILE=${CALLED_FROM_MAIN_MAKEFILE:-""}
+if [ "${CALLED_FROM_MAIN_MAKEFILE}" == "" ]; then
```
Comment (ixdy) [inline hack/make-rules/vet.sh]: I might've just done `if [[ -z "${CALLED_FROM_MAIN_MAKEFILE:-}" ]]; then` since it's shorter, but this is fine too.

File: hack/make-rules/vet.sh [hunk 4]
```diff
@@ -25,8 +25,14 @@ cd "${KUBE_ROOT}"
 
 # This is required before we run govet for the results to be correct.
```
Comment (ixdy) [inline hack/make-rules/vet.sh]: this comment probably needs to be updated - "This" no longer refers to anything.

File: hack/make-rules/vet.sh [hunk 5]
```diff
@@ -25,8 +25,14 @@ cd "${KUBE_ROOT}"
...
 # See https://github.com/golang/go/issues/16086 for details.
-make generated_files
-go install ./cmd/...
```
Comment (ixdy) [inline hack/make-rules/vet.sh]: ISTR the `go install` bit was important too, though I'm not sure if it still is. this is my main concern with this PR.

File: hack/make-rules/vet.sh (hunk 4 above)
Comment (cblecker) [inline hack/make-rules/vet.sh]: Yup, makes sense.

File: hack/make-rules/vet.sh (hunk 5 above)
Comment (cblecker) [inline hack/make-rules/vet.sh]: Reviewing that github issue, it looks like it still might be important, until at least Go 1.9

**Comment by cblecker** [comment]
@ixdy @rmmh Updated per comments. PTAL

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-cross test this
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by cblecker** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this

**Comment by fejta** [comment]
@k8s-bot pull-kubernetes-federation-e2e-gce test this
ref: #46827

**Comment by cblecker** [comment]
@ixdy rebased

File: hack/make-rules/vet.sh [hunk 6]
```diff
@@ -23,9 +23,16 @@ source "${KUBE_ROOT}/hack/lib/init.sh"
 
 cd "${KUBE_ROOT}"
 
+# If called directly, exit.
+if [ "${CALLED_FROM_MAIN_MAKEFILE:-""}" == "" ]; then
```
Comment (ixdy) [inline hack/make-rules/vet.sh]: nit: I think you might need to use `[[ ]]` for `==` to work? we generally prefer `[[ ]]` anyway.

Comment (cblecker) [inline hack/make-rules/vet.sh]: I verified it worked without, but cleaned it up anyways to stick with convention.
