### PR TITLE
Fetch metrics from controller manager & scheduler without `sync.Once`

### LINKED ISSUE #102865: [Failing Test] [sig-storage] ci-kubernetes-e2e-gci-gce-serial
#### Which jobs are failing:
ci-kubernetes-e2e-gci-gce-serial (gce-cos-master-serial)

#### Which test(s) are failing:
- Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create unbound pvc count metrics for pvc controller after creating pvc only 
- Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create unbound pv count metrics for pvc controller after creating pv only
- Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics should create prometheus metrics for volume provisioning and attach/detach
- Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create total pv count metrics for with plugin and volume mode labels after creating pv
- Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics should create prometheus metrics for volume provisioning errors [Slow]
- Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create none metrics for pvc controller before creating any PV or PVC
- Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create bound pv/pvc count metrics for pvc controller after creating both pv and pvc
- e2e.go: Test

#### Since when has it been failing:
2021-05-11 19:20:26 +0000 UTC

#### Testgrid link:
https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial

#### Reason for failure:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:526
Jun 14 15:15:06.169: Error getting c-m metricValues: error waiting for controller manager pod to expose metrics: timed out waiting for the condition; the server could not find the requested resource (get pods metrics-proxy:10257)
Unexpected error:
    <*errors.errorString | 0xc00322d500>: {
        s: "error waiting for controller manager pod to expose metrics: timed out waiting for the condition; the server could not find the requested resource (get pods metrics-proxy:10257)",
    }
    error waiting for controller manager pod to expose metrics: timed out waiting for the condition; the server could not find the requested resource (get pods metrics-proxy:10257)
occurred
```

#### Anything else we need to know:

/sig storage

### PR DESCRIPTION
**Pull request by mauriciopoppe**
#### What type of PR is this?

Add one of the following kinds:
/kind bug

Optionally add one or more of the following kinds if applicable:
/kind failing-test

#### What this PR does / why we need it:

Fixes an issue added in https://github.com/kubernetes/kubernetes/pull/101895 where metrics were only fetched once, `sync.Once` only wraps the part that checks that the required pods are in a ready state, next calls will skip checking that the required pods are in a ready state.

Ref: https://github.com/kubernetes/kubernetes/issues/102865

#### Which issue(s) this PR fixes:

Could fix https://github.com/kubernetes/kubernetes/issues/102865

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

/sig storage
/cc @pohly @aojea

### CODE REVIEW

**Comment by mauriciopoppe** [comment]
The test `ci-kubernetes-e2e-gci-gce-serial` that this PR attempts to solve is a CI test, I might need to check the results after it's merged

**Comment by aojea** [comment]
The sync.Once was solving a real bug, but it only should wrap the "wait for pods" ready call, the metrics are the ones that should be outside

File: test/e2e/framework/metrics/metrics_grabber.go [hunk 1]
```diff
@@ -245,24 +245,26 @@ func (g *Grabber) GrabFromControllerManager() (ControllerManagerMetrics, error)
 		return ControllerManagerMetrics{}, fmt.Errorf("kube-controller-manager: %w", MetricsGrabbingDisabledError)
 	}
 
-	var err error
-	var output string
 	podName := g.kubeControllerManager
-	g.waitForControllerManagerReadyOnce.Do(func() {
```
Comment (aojea) [inline test/e2e/framework/metrics/metrics_grabber.go:251]: we should keep the ReadyOnce but only with
```
		if readyErr := e2epod.WaitForPodsReady(g.client, metav1.NamespaceSystem, podName, 0); readyErr != nil {
```
inside.
And move the 
```
			output, lastMetricsFetchErr = g.getSecureMetricsFromPod(g.kubeControllerManager, metav1.NamespaceSystem, kubeControllerManagerPort)
```
out of the sync.Once

Comment (mauriciopoppe) [reply test/e2e/framework/metrics/metrics_grabber.go:251]: thanks, I moved the `WaitForPodsReady` request to be inside `sync.Once` however I kept the PollImmediate to make the call to get stats from the desired pod.

I was hesitant to add

```
			output, lastMetricsFetchErr = g.getSecureMetricsFromPod(g.kubeControllerManager, metav1.NamespaceSystem, kubeControllerManagerPort)
```

without a retry function because there's the chance that the request fails.

File: test/e2e/framework/metrics/metrics_grabber.go [hunk 2]
```diff
@@ -201,17 +201,26 @@ func (g *Grabber) GrabFromScheduler() (SchedulerMetrics, error) {
...
+	var output string
+	if metricsWaitErr := wait.PollImmediate(time.Second, time.Minute, func() (bool, error) {
+		output, lastMetricsFetchErr = g.getSecureMetricsFromPod(g.kubeScheduler, metav1.NamespaceSystem, kubeSchedulerPort)
+		return lastMetricsFetchErr == nil, nil
+	}); metricsWaitErr != nil {
+		err := fmt.Errorf("error waiting for kube-scheduler pod to expose metrics: %v; %v", metricsWaitErr, lastMetricsFetchErr)
+		return SchedulerMetrics{}, err
+	}
+
 	if err != nil {
```
Comment (aojea) [inline test/e2e/framework/metrics/metrics_grabber.go:224]: this `if err != nil ` is not needed now, it's checked in L210
https://github.com/kubernetes/kubernetes/pull/103806/files#diff-28a3131f96324063dd53e17270d435a3b0b3bd8f806ee0e33295929570eab209R210

File: test/e2e/framework/metrics/metrics_grabber.go [hunk 3]
```diff
@@ -246,23 +255,26 @@ func (g *Grabber) GrabFromControllerManager() (ControllerManagerMetrics, error)
...
+	var lastMetricsFetchErr error
+	if metricsWaitErr := wait.PollImmediate(time.Second, time.Minute, func() (bool, error) {
+		output, lastMetricsFetchErr = g.getSecureMetricsFromPod(g.kubeControllerManager, metav1.NamespaceSystem, kubeControllerManagerPort)
+		return lastMetricsFetchErr == nil, nil
+	}); metricsWaitErr != nil {
+		err := fmt.Errorf("error waiting for kube-controller-manager to expose metrics: %v; %v", metricsWaitErr, lastMetricsFetchErr)
+		return ControllerManagerMetrics{}, err
+	}
+
 	if err != nil {
```
Comment (aojea) [inline test/e2e/framework/metrics/metrics_grabber.go:278]: same here, you check err before

File: test/e2e/framework/metrics/metrics_grabber.go (hunk 2 above)
Comment (aojea) [reply test/e2e/framework/metrics/metrics_grabber.go:224]: you return if metricsWaitErr != nil

File: test/e2e/framework/metrics/metrics_grabber.go [hunk 4]
```diff
@@ -285,29 +297,28 @@ func (g *Grabber) GrabFromSnapshotController(podName string, port int) (Snapshot
...
-	output, err := g.getMetricsFromPod(g.client, podName, metav1.NamespaceSystem, port)
+	var output string
+	var lastMetricsFetchErr error
+	if metricsWaitErr := wait.PollImmediate(time.Second, time.Minute, func() (bool, error) {
+		output, lastMetricsFetchErr = g.getMetricsFromPod(g.client, podName, metav1.NamespaceSystem, port)
+		return lastMetricsFetchErr == nil, nil
+	}); metricsWaitErr != nil {
+		err = fmt.Errorf("error waiting for volume-snapshot-controller pod to expose metrics: %v; %v", metricsWaitErr, lastMetricsFetchErr)
+	}
 	if err != nil {
```
Comment (aojea) [inline test/e2e/framework/metrics/metrics_grabber.go:318]: maybe you want to make it consistent with the rest of the code and return directly in `metricsWaitErr != nil`?

File: test/e2e/framework/metrics/metrics_grabber.go (hunk 2 above)
Comment (mauriciopoppe) [reply test/e2e/framework/metrics/metrics_grabber.go:224]: thanks for catching this, I've updated all of these places :)

**Comment by aojea** [comment]
/assign @spiffxp 
/cc @pohly 
more on the metrics drama :smile: 
this should go into milestine 1.22
Thanks

**Comment by dims** [comment]
/approve
/lgtm
/hold
/milestone v1.22

@aojea @pohly @mauriciopoppe please feel to remove hold when ready.

**Comment by mauriciopoppe** [comment]
This is ready to be merged.
/hold cancel
