### PR TITLE
Fix double counting of IP addresses

### LINKED ISSUE #96416: Double counting in the IPAM
**What happened**:
With a /22 pod network and a /24 assigned to each node, a third node cannot get a pod CIDR if kube-controller-manager has ever been restarted.

**What you expected to happen**:
Once a third or fourth node joins, it gets a /24.

**How to reproduce it (as minimally and precisely as possible)**:
```
minikube start -n 3 --extra-config kubeadm.pod-network-cidr=10.244.0.0/22
sleep 10
minikube ssh -- sudo curl -sk https://127.0.0.1:10257/metrics --key /var/lib/minikube/certs/apiserver-kubelet-client.key --cert /var/lib/minikube/certs/apiserver-kubelet-client.crt | grep '^node_ipam'
minikube ssh -- sudo pkill -9 -ef kube-controller-manager
sleep 30
minikube ssh -- sudo curl -sk https://127.0.0.1:10257/metrics --key /var/lib/minikube/certs/apiserver-kubelet-client.key --cert /var/lib/minikube/certs/apiserver-kubelet-client.crt | grep '^node_ipam'
```

150% usage on the IPAM controller is not a good sign.

**Anything else we need to know?**:
During the creation of the rangeAllocator, Occupy() is called twice on the pod networks. The first time is before subscribing to the node informer. The second time is during the node informer callbacks because on subscribing it calls Add for all existing nodes.

I will submit a proposed fix shortly.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.2

### PR DESCRIPTION
**Pull request by hvenev-vmware**
The range allocator in pkg/controller/nodeipam/ipam/range_allocator.go
may call Occupy() on the same range twice:

1. Just before subscribing to the NodeInformer
2. From a callback given to the NodeInformer soon after registration

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes #96416

**Which issue(s) this PR fixes**:
Fixes #96416

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fixes a regression in 1.19 double-counting IP address in the IPAM allocator
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by hvenev-vmware** [comment]
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

**Comment by aojea** [comment]
nice catch
/ok-to-test
/triage-accepted
This will require a new unit test https://github.com/kubernetes/kubernetes/blob/45abbb041704e9ec8526f3e8bc8aa2f60eabae56/pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go#L741-L749

**Comment by hvenev-vmware** [comment]
Tests added. I ran the range allocator test without the fix and it failed.

File: pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go [hunk 1]
```diff
@@ -341,6 +343,77 @@ func TestCIDRSet_AllocationOccupied(t *testing.T) {
 	}
 }
 
+func TestDoubleOccupyRelease(t *testing.T) {
+	clusterCIDRStr := "10.42.0.0/16"
+	operations := []struct {
+		cidrStr     string
+		occupy      bool
```
Comment (aojea) [inline pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go:350]: I think that is a bit difficult to understand the test with a boolean, I mean, It's not clear at first sight that occupy=false means release(). Maybe use a string operation string that can take the values "occupy" or "release"?

File: pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go [hunk 2]
```diff
@@ -341,6 +343,77 @@ func TestCIDRSet_AllocationOccupied(t *testing.T) {
...
+		numOccupied int
+	}{
+		{
```
Comment (aojea) [inline pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go:353]: this runs sequential, add comments to explain what we expect at each step.
// allocate 1 subnet

File: pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go [hunk 3]
```diff
@@ -341,6 +343,77 @@ func TestCIDRSet_AllocationOccupied(t *testing.T) {
...
+			cidrStr:     "10.42.5.0/24",
+			occupy:      true,
+			numOccupied: 1,
+		},
+		{
```
Comment (aojea) [inline pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go:358]: // allocate another subnet

File: pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go [hunk 4]
```diff
@@ -341,6 +343,77 @@ func TestCIDRSet_AllocationOccupied(t *testing.T) {
...
+			cidrStr:     "10.42.9.0/24",
+			occupy:      true,
+			numOccupied: 2,
+		},
+		{
```
Comment (aojea) [inline pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go:363]: allocate an overlapping subnet ...

File: pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go [hunk 5]
```diff
@@ -341,6 +343,77 @@ func TestCIDRSet_AllocationOccupied(t *testing.T) {
...
+			cidrStr:     "10.42.8.0/22",
+			occupy:      true,
+			numOccupied: 5,
+		},
+		{
```
Comment (aojea) [inline pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go:368]: allocate an overlap subnet, should not increase the number of occupied

File: pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go [hunk 6]
```diff
@@ -341,6 +343,77 @@ func TestCIDRSet_AllocationOccupied(t *testing.T) {
...
+			cidrStr:     "10.42.9.0/24",
+			occupy:      true,
+			numOccupied: 5,
+		},
+		{
```
Comment (aojea) [inline pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go:373]: release one of the allocated subnets

File: pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go [hunk 7]
```diff
@@ -341,6 +343,77 @@ func TestCIDRSet_AllocationOccupied(t *testing.T) {
...
+			cidrStr:     "10.42.9.0/24",
+			occupy:      false,
+			numOccupied: 4,
+		},
+		{
```
Comment (aojea) [inline pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go:378]: release an previous deallocated subnet, should not decrease the number of occupied

File: pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go [hunk 8]
```diff
@@ -341,6 +343,77 @@ func TestCIDRSet_AllocationOccupied(t *testing.T) {
...
+			cidrStr:     "10.42.9.0/24",
+			occupy:      false,
+			numOccupied: 4,
+		},
```
Comment (aojea) [inline pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go:382]: add another case releasing a subnet that comprises more than 1 of the previous allocated ones

File: pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go [hunk 9]
```diff
@@ -341,6 +343,77 @@ func TestCIDRSet_AllocationOccupied(t *testing.T) {
...
+			a.Occupy(cidr)
+		} else {
+			a.Release(cidr)
+		}
+		if a.allocatedCIDRs != op.numOccupied {
+			t.Fatalf("Expected %d occupied CIDRS, got %d", op.numOccupied, a.allocatedCIDRs)
+		}
+	}
+
+	for i := 0; i < numAllocatable24s; i++ {
```
Comment (aojea) [inline pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go:404]: add comment here explaining that we are going to allocate the rest of the subnets, to fill the pool

File: pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go [hunk 10]
```diff
@@ -341,6 +343,77 @@ func TestCIDRSet_AllocationOccupied(t *testing.T) {
...
+		_, err := a.AllocateNext()
+		if err != nil {
+			t.Fatalf("Expected to be able to allocate %d CIDRS, failed after %d", numAllocatable24s, i)
+		}
+	}
+
+	_, err = a.AllocateNext()
```
Comment (aojea) [inline pkg/controller/nodeipam/ipam/cidrset/cidr_set_test.go:411]: comment explaining that, once it is full, it should fail to allocate a new one

File: pkg/controller/nodeipam/ipam/range_allocator_test.go [hunk 11]
```diff
@@ -486,12 +486,55 @@ func TestAllocateOrOccupyCIDRSuccess(t *testing.T) {
...
+		{
+			description: "no double counting",
+			fakeNodeHandler: &testutil.FakeNodeHandler{
+				Existing: []*v1.Node{
+					{
+						ObjectMeta: metav1.ObjectMeta{
+							Name: "node0",
+						},
+						Spec: v1.NodeSpec{
+							PodCIDRs: []string{"10.10.0.1/24"},
```
Comment (aojea) [inline pkg/controller/nodeipam/ipam/range_allocator_test.go:498]: 10.10.0.0/24

File: pkg/controller/nodeipam/ipam/range_allocator_test.go [hunk 12]
```diff
@@ -486,12 +486,55 @@ func TestAllocateOrOccupyCIDRSuccess(t *testing.T) {
...
+						},
+					},
+					{
+						ObjectMeta: metav1.ObjectMeta{
+							Name: "node1",
+						},
+						Spec: v1.NodeSpec{
+							PodCIDRs: []string{"10.10.2.1/24"},
```
Comment (aojea) [inline pkg/controller/nodeipam/ipam/range_allocator_test.go:506]: 10.10.2.0/24

File: pkg/controller/nodeipam/ipam/range_allocator_test.go [hunk 13]
```diff
@@ -517,13 +560,23 @@ func TestAllocateOrOccupyCIDRSuccess(t *testing.T) {
...
 			}
-			if err := allocator.AllocateOrOccupyCIDR(tc.fakeNodeHandler.Existing[0]); err != nil {
-				t.Errorf("%v: unexpected error in AllocateOrOccupyCIDR: %v", tc.description, err)
+		}
+
+		updateCount := 0
+		for _, node := range tc.fakeNodeHandler.Existing {
+			if node.Spec.PodCIDRs == nil {
+				updateCount++
 			}
```
Comment (aojea) [inline pkg/controller/nodeipam/ipam/range_allocator_test.go:569]: it will work the same with the previous code, no?
why iterating now?

Comment (hvenev-vmware) [reply pkg/controller/nodeipam/ipam/range_allocator_test.go:569]: I just wanted to make sure that all tests have exactly one node without assigned PodCIDRs.

Comment (hvenev-vmware) [reply pkg/controller/nodeipam/ipam/range_allocator_test.go:569]: The iteration is done because we now have more than one node, and the one that needs an address is not always `Existing[0]`.

**Comment by aojea** [comment]
/lgtm
Thanks
/assign @thockin @bowei 
for approval

File: pkg/controller/nodeipam/ipam/cidrset/cidr_set.go [hunk 14]
```diff
@@ -232,9 +232,11 @@ func (s *CidrSet) Release(cidr *net.IPNet) error {
 	s.Lock()
 	defer s.Unlock()
 	for i := begin; i <= end; i++ {
-		s.used.SetBit(&s.used, i, 0)
-		s.allocatedCIDRs--
-		cidrSetReleases.WithLabelValues(s.label).Inc()
+		if s.used.Bit(i) != 0 {
+			s.used.SetBit(&s.used, i, 0)
```
Comment (thockin) [inline pkg/controller/nodeipam/ipam/cidrset/cidr_set.go:236]: I hoped that this might return the old value of the bit, but alas no.

File: pkg/controller/nodeipam/ipam/cidrset/cidr_set.go [hunk 15]
```diff
@@ -232,9 +232,11 @@ func (s *CidrSet) Release(cidr *net.IPNet) error {
 	s.Lock()
 	defer s.Unlock()
 	for i := begin; i <= end; i++ {
-		s.used.SetBit(&s.used, i, 0)
-		s.allocatedCIDRs--
-		cidrSetReleases.WithLabelValues(s.label).Inc()
+		if s.used.Bit(i) != 0 {
```
Comment (thockin) [inline pkg/controller/nodeipam/ipam/cidrset/cidr_set.go:235]: This is really subtle - can I ask you for some comments in both of these blocks?

**Review by thockin — COMMENTED** [review]
/approve

File: pkg/controller/nodeipam/ipam/cidrset/cidr_set.go (hunk 15 above)
Comment (hvenev-vmware) [reply pkg/controller/nodeipam/ipam/cidrset/cidr_set.go:237]: Done.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by hvenev-vmware** [comment]
Will it be possible to merge this change in the 1.19 branch as well?

**Comment by aojea** [comment]
> Will it be possible to merge this change in the 1.19 branch as well?

sure, can you do the cherry pick?
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md

**Review by hasheddan — APPROVED** [review]
/milestone v1.20
