### PR TITLE
More carefully compose RequestURI for metrics request

### LINKED ISSUE #115200: The "API priority and fairness" test fails from sig-api-machinery TC suite when kube-apiserver not exposed directly
### What happened?

We faced an issue when executing one of the CNTT test case.

In our environment, the kube-apiserver not exposed directly, it can be reached via an nginx POD within the cluster which proxies the requests.
Client (running CNTT tests) => POD (running in the cluster, as proxy) => kube-apiserver
The kube-config configured properly to reach that endpoint:
```
clusters:
- cluster:
    server: https://x.y.z.73:8082/proxy/apiserver
...
```

Executing the sig_api_machinery test case, the "API priority and fairness  should ensure that requests can be classified by adding FlowSchema and PriorityLevelConfiguration" test case failed.

Execution
```
podman run -it --env-file ~/opnfv/env \
-v ~/opnfv/ca.pem:/home/opnfv/functest/ca.pem:Z \
-v ~/opnfv/config:/root/.kube/config:Z \
-v ~/opnfv/repositories.yml:/home/opnfv/functest/repositories.yml:Z \
-v ~/opnfv/results:/home/opnfv/functest/results:Z \
opnfv/functest-kubernetes-smoke:v1.23 run_tests -t sig_api_machinery
```

Results
```
[sig-api-machinery] API priority and fairness
  should ensure that requests can be classified by adding FlowSchema and PriorityLevelConfiguration
  /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/flowcontrol.go:56
[BeforeEach] [sig-api-machinery] API priority and fairness
  /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:185
STEP: Creating a kubernetes client
Jan 16 10:53:06.646: INFO: >>> kubeConfig: /root/.kube/config
STEP: Building a namespace api object, basename apf
W0116 10:53:06.701880      43 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Jan 16 10:53:06.702: INFO: Found PodSecurityPolicies; testing pod creation to see if PodSecurityPolicy is enabled
Jan 16 10:53:06.718: INFO: PSP annotation exists on dry run pod: "bcmt-ip-man-psp"; assuming PodSecurityPolicy is enabled
W0116 10:53:06.726164      43 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Jan 16 10:53:06.737: INFO: Found ClusterRoles; assuming RBAC is enabled.
STEP: Binding the e2e-test-privileged-psp PodSecurityPolicy to the default service account in apf-4666
STEP: Waiting for a default service account to be provisioned in namespace
STEP: Waiting for kube-root-ca.crt to be provisioned in namespace
[It] should ensure that requests can be classified by adding FlowSchema and PriorityLevelConfiguration
  /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/flowcontrol.go:56
STEP: creating a testing PriorityLevelConfiguration object
STEP: creating a testing FlowSchema object
STEP: waiting for testing FlowSchema and PriorityLevelConfiguration to reach steady state
Jan 16 10:54:07.937: FAIL: Unexpected error:
    <*errors.StatusError | 0xc002a8a280>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "the server could not find the requested resource",
            Reason: "NotFound",
            Details: {
                Name: "",
                Group: "",
                Kind: "",
                UID: "",
                Causes: [
                    {
                        Type: "UnexpectedServerResponse",
                        Message: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>",
                        Field: "",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    the server could not find the requested resource
occurred

Full Stack Trace
k8s.io/kubernetes/test/e2e/apimachinery.waitForSteadyState(0xc000a018c0, {0x7118f76, 0x16}, {0x712cc8e, 0x19})
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/flowcontrol.go:364 +0xed
k8s.io/kubernetes/test/e2e/apimachinery.glob..func11.1()
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/flowcontrol.go:71 +0x158
k8s.io/kubernetes/test/e2e.RunE2ETests(0x24c66d7)
        _output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:133 +0x697
k8s.io/kubernetes/test/e2e.TestE2E(0x0)
        _output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:136 +0x19
testing.tRunner(0xc00024c9c0, 0x735d430)
        /usr/local/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1306 +0x35a
[AfterEach] [sig-api-machinery] API priority and fairness
  /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:186
STEP: Collecting events from namespace "apf-4666".
STEP: Found 0 events.
```

From the nginx POD log which proxies the request towards the kube-apiserver, we can see the request received/answered as "open() "/usr/share/nginx/web/metrics" failed (2: No such file or directory)", so instead forwarding the "/metrics" towards the kube-apiserver the nginx proxy POD try to answer for that (of course can't).

nginx POD log
```
nginx: 172.30.110.4 - - [16/Jan/2023:12:57:38 +0000] "GET /proxy/apiserver/api/v1/namespaces/apf-928/configmaps?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dkube-root-ca.crt&resourceVersion=2309915&timeout=9m59s&timeoutSeconds=599&watch=true HTTP/1.1" 200 0 "-" "e2e.test/v1.23.13 (linux/amd64) kubernetes/592eca0 -- [sig-api-machinery] API priority and fairness should ensure that requests can be classified by adding FlowSchema and PriorityLevelConfiguration" "x.y.z.11"
nginx: 172.30.110.4 - - [16/Jan/2023:12:57:38 +0000] "POST /proxy/apiserver/apis/flowcontrol.apiserver.k8s.io/v1beta2/prioritylevelconfigurations HTTP/1.1" 201 405 "-" "e2e.test/v1.23.13 (linux/amd64) kubernetes/592eca0 -- [sig-api-machinery] API priority and fairness should ensure that requests can be classified by adding FlowSchema and PriorityLevelConfiguration" "x.y.z.11"
nginx: 172.30.110.4 - - [16/Jan/2023:12:57:38 +0000] "POST /proxy/apiserver/apis/flowcontrol.apiserver.k8s.io/v1beta2/flowschemas HTTP/1.1" 201 458 "-" "e2e.test/v1.23.13 (linux/amd64) kubernetes/592eca0 -- [sig-api-machinery] API priority and fairness should ensure that requests can be classified by adding FlowSchema and PriorityLevelConfiguration" "x.y.z.11"
nginx: 172.30.110.4 - - [16/Jan/2023:12:57:39 +0000] "GET /proxy/apiserver/apis/flowcontrol.apiserver.k8s.io/v1beta2/flowschemas/e2e-testing-flowschema HTTP/1.1" 200 896 "-" "e2e.test/v1.23.13 (linux/amd64) kubernetes/592eca0 -- [sig-api-machinery] API priority and fairness should ensure that requests can be classified by adding FlowSchema and PriorityLevelConfiguration" "x.y.z.11"
2023/01/16 12:57:39 [error] 15#15: *505 open() "/usr/share/nginx/web/metrics" failed (2: No such file or directory), client: 172.30.110.4, server: _, request: "GET /metrics HTTP/1.1", host: "x.y.z.73:8082"
nginx: 172.30.110.4 - - [16/Jan/2023:12:57:39 +0000] "GET /metrics HTTP/1.1" 404 146 "-" "e2e.test/v1.23.13 (linux/amd64) kubernetes/592eca0 -- [sig-api-machinery] API priority and fairness should ensure that requests can be classified by adding FlowSchema and PriorityLevelConfiguration" "x.y.z.11"
nginx: 172.30.110.4 - - [16/Jan/2023:12:57:39 +0000] "DELETE /proxy/apiserver/apis/flowcontrol.apiserver.k8s.io/v1beta2/flowschemas/e2e-testing-flowschema HTTP/1.1" 200 157 "-" "e2e.test/v1.23.13 (linux/amd64) kubernetes/592eca0 -- [sig-api-machinery] API priority and fairness should ensure that requests can be classified by adding FlowSchema and PriorityLevelConfiguration" "x.y.z.11"
nginx: 172.30.110.4 - - [16/Jan/2023:12:57:39 +0000] "DELETE /proxy/apiserver/apis/flowcontrol.apiserver.k8s.io/v1beta2/prioritylevelconfigurations/e2e-testing-prioritylevel HTTP/1.1" 200 176 "-" "e2e.test/v1.23.13 (linux/amd64) kubernetes/592eca0 -- [sig-api-machinery] API priority and fairness should ensure that requests can be classified by adding FlowSchema and PriorityLevelConfiguration" "x.y.z.11"
```

After the checking the code it seems the reason behind is here:
https://github.com/kubernetes/kubernetes/blob/817b9af22eb5a856c5d2bb02f57d5384a7b4cf2c/test/e2e/apimachinery/flowcontrol.go#L282
```
	resp, err := c.CoreV1().RESTClient().Get().RequestURI("/metrics").DoRaw(context.TODO())
```

https://github.com/kubernetes/kubernetes/blob/817b9af22eb5a856c5d2bb02f57d5384a7b4cf2c/staging/src/k8s.io/client-go/rest/request.go#L332
```
// RequestURI overwrites existing path and parameters with the value of the provided server relative URI.
func (r *Request) RequestURI(uri string) *Request {
...
```

the query not use the full path configured in the kube-config, it keeps only the IP:PORT and then add the /metrics. Which of course will fail.

Several other TCs executed without any issue. Maybe using other function like suffix can work as it didn't remove the /proxy/apiserver part of the URL just append the /metrics.

### What did you expect to happen?

The test case should executed successfully.

### How can we reproduce it (as minimally and precisely as possible)?

To avoid running all the test case within the sig-api-machinery, try this:

```
podman run -it --env-file ~/opnfv/env \
-v ~/opnfv/ca.pem:/home/opnfv/functest/ca.pem:Z \
-v ~/opnfv/config:/root/.kube/config:Z \
-v ~/opnfv/repositories.yml:/home/opnfv/functest/repositories.yml:Z \
-v ~/opnfv/results:/home/opnfv/functest/results:Z \
opnfv/functest-kubernetes-healthcheck:v1.23 /bin/bash
```

```
/usr/local/bin/e2e.test \
--test.timeout=24h0m0s \
--ginkgo.seed=1673863315 \
--ginkgo.noColor \
--ginkgo.slowSpecThreshold=5.00000 \
-kubeconfig /root/.kube/config \
-provider local \
-report-dir /home/opnfv/functest/results/sig_api_machinery \
-ginkgo.focus "API priority and fairness should ensure that requests can be classified by adding FlowSchema and PriorityLevelConfiguration" \
-non-blocking-taints is_control,is_edge \
-disable-log-dump true
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T10:49:13Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T10:42:57Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Openstack
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
$ uname -a
Linux cbis-sut1-control-01 4.18.0-372.9.1.el8.x86_64 #1 SMP Tue May 10 14:48:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
This PR changes the way the e2e test for API Priority and Fairness composes the Request for metrics, because the old way discarded the configured prefix.

#### Which issue(s) this PR fixes:

This addresses #115200 in the head of development, but that particular issue was raised on release 1.23.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/apimachinery/flowcontrol.go [hunk 1]
```diff
@@ -274,9 +275,14 @@ func createPriorityLevel(ctx context.Context, f *framework.Framework, priorityLe
 }
 
 func getPriorityLevelNominalConcurrency(ctx context.Context, c clientset.Interface, priorityLevelName string) (int32, error) {
-	resp, err := c.CoreV1().RESTClient().Get().RequestURI("/metrics").DoRaw(ctx)
+	req := c.CoreV1().RESTClient().Get()
+	reqURL := req.URL()
+	reqPathOrig := reqURL.EscapedPath()
+	reqPathMetrics := strings.TrimSuffix(reqPathOrig, "api/v1") + "metrics"
```
Comment (wojtek-t) [inline test/e2e/apimachinery/flowcontrol.go:281]: Let's add an explicit comment why you're doing those tricks - it didn't seem intuitive before reading the corresponding bug.

[Trimming api/v1 seems like it can break in the future, but I don't have a better way of doing it, so let's leave it].

Comment (MikeSpreitzer) [reply test/e2e/apimachinery/flowcontrol.go:284]: Thanks, I was indeed wondering if there is a better way to do it.

The force-push to aa0e28c870a adds a comment.

**Comment by MikeSpreitzer** [comment]
.. and the force-push to 1d199db03e0 fixes a typo in the new comment.

**Comment by wojtek-t** [comment]
/lgtm
/approve

Thanks!

File: test/e2e/apimachinery/flowcontrol.go (hunk 1 above)
Comment (liggitt) [reply test/e2e/apimachinery/flowcontrol.go:284]: `c.CoreV1().RESTClient().Get().AbsPath("/metrics").DoRaw(ctx)` would have been a cleaner way to do this. AbsPath honors any base prefix configured for the server, while overriding all the API-path portions of the request.

as a demonstration:

```go
	fmt.Println("no server prefix, RequestURI:", clientset.NewForConfigOrDie(config).CoreV1().RESTClient().Get().RequestURI("/metrics").URL())
	config.Host += "/base"
	fmt.Println("server prefix, RequestURI:", clientset.NewForConfigOrDie(config).CoreV1().RESTClient().Get().RequestURI("/metrics").URL())
	fmt.Println("server prefix, AbsPath:", clientset.NewForConfigOrDie(config).CoreV1().RESTClient().Get().AbsPath("/metrics").URL())
```
produces:
```sh
no server prefix, RequestURI: https://127.0.0.1:51840/metrics
server prefix, RequestURI: https://127.0.0.1:51840/metrics
server prefix, AbsPath: https://127.0.0.1:51840/base/metrics
```
