### PR TITLE
Fix GCE Cloud/Attach/Detach stability issues

### LINKED ISSUE #15382: Pod Disks should schedule a pod w/two RW PDs flake
Failed 2 times in the last 30 runs.

http://kubekins.dls.corp.google.com/view/Critical%20Builds/job/kubernetes-e2e-gce/8824/testReport/junit/%28root%29/Kubernetes%20e2e%20suite/Pod_Disks_should_schedule_a_pod_w_two_RW_PDs_both_mounted_to_one_container__write_to_PD__verify_contents__delete_pod__recreate_pod__verify_contents__and_repeat_in_rapid_succession/

/cc @saad-ali

### LINKED ISSUE #15978: GCE Cloudprovider `waitForOp` sometimes causes panics due to `invalid memory address or nil pointer dereference`.
While investigating #15382, I discovered that the `pkg/cloudprovider/providers/gce/gce.go:waitForOp(...)` method (copied below) sometimes causes panics due to `invalid memory address or nil pointer dereference`.

```GO
func waitForOp(op *compute.Operation, getOperation func() (*compute.Operation, error)) error {
	pollOp := op
	consecPollFails := 0
	for pollOp.Status != "DONE" {
		var err error
		time.Sleep(3 * time.Second)
		pollOp, err = getOperation()
		if err != nil {
			if consecPollFails == 2 {
				// Only bail if we've seen 3 consecutive polling errors.
				return err
			}
			consecPollFails++
		} else {
			consecPollFails = 0
		}
	}
	if pollOp.Error != nil && len(pollOp.Error.Errors) > 0 {
		return &googleapi.Error{
			Code:    int(pollOp.HttpErrorStatusCode),
			Message: pollOp.Error.Errors[0].Message,
		}
	}
	return nil

}
```
Error: `E1020 20:36:34.301927    3625 util.go:82] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)`

Stack trace indicates the culprit is this line:
```GO
	for pollOp.Status != "DONE" {
```

I'll fix this along with #15382. This method also has the potential to block indefinitely if there is a bad server response, so the fix should also fix the max amount of time to wait.

### PR DESCRIPTION
**Pull request by saad-ali**
- Fixes #15978: GCE Cloudprovider `waitForOp` sometimes causes panics due to `invalid memory address or nil pointer dereference`
  - Fixes a bug where anytime there is a GCE error doing a get poll operation call the code would panic due to `nil pointer dereference`. This affects all GCE calls.
- Fixes #15382: Pod Disks should schedule a pod w/two RW PDs flake
  - Instead of using operation manager to defer to pending detach operations, this change ensures that attach/detach operations for the same GCE PD are atomic. This prevents a whole host of nasty race conditions.

This must be cherry picked for v1.1.
CC @thockin @justinsb

### CODE REVIEW

File: pkg/cloudprovider/providers/gce/gce.go [hunk 1]
```diff
@@ -54,6 +54,9 @@ const (
 	gceAffinityTypeClientIP = "CLIENT_IP"
 	// AffinityTypeClientIPProto - affinity based on Client IP and port.
 	gceAffinityTypeClientIPProto = "CLIENT_IP_PROTO"
+
+	operationPollInterval        = 3 * time.Second
+	operationPollTimeoutDuration = 7 * time.Minute
```
Comment (alex-mohr) [inline pkg/cloudprovider/providers/gce/gce.go]: where does the 7 minutes come from?  what's the behavior if 7 minutes is reached and e.g. operation actually succeeds (or fails) after 8 minutes?

Comment (saad-ali) [inline pkg/cloudprovider/providers/gce/gce.go]: 7 minutes is an arbitrary cap that I set, based on the fact that I've seen some disk attach request take a few minutes to succeed. I'm fine with either lowering or raising it. But, I think the poll time must be capped: if there is a server side issue, for example, where the operation is never set to "DONE" we don't want this to block indefinitely (as the old code would do).

When the timeout is hit, the request fails with error, and it is up to the caller to determine what to do (GCE PD attach/detach will retry).

File: pkg/cloudprovider/providers/gce/gce.go [hunk 2]
```diff
@@ -245,45 +248,62 @@ func (gce *GCECloud) targetPoolURL(name, region string) string {
...
-	if pollOp.Error != nil && len(pollOp.Error.Errors) > 0 {
+
+	if opIsDone(op) {
+		return getErrorFromCompletedOp(op)
+	}
+
+	var pollOp *compute.Operation
+	var err error
+	return wait.Poll(operationPollInterval, operationPollTimeoutDuration, func() (bool, error) {
+		pollOp, err = getOperation()
```
Comment (cjcullen) [inline pkg/cloudprovider/providers/gce/gce.go]: Might be nice to at least log this error.

File: pkg/cloudprovider/providers/gce/gce.go [hunk 3]
```diff
@@ -245,45 +248,62 @@ func (gce *GCECloud) targetPoolURL(name, region string) string {
...
+		return fmt.Errorf("operation must not be nil")
 	}
-	if pollOp.Error != nil && len(pollOp.Error.Errors) > 0 {
+
+	if opIsDone(op) {
+		return getErrorFromCompletedOp(op)
+	}
+
+	var pollOp *compute.Operation
+	var err error
```
Comment (cjcullen) [inline pkg/cloudprovider/providers/gce/gce.go]: Is there any reason that these need to be declared outside and then closed over? Is it just a GC efficiency thing?

File: pkg/cloudprovider/providers/gce/gce.go [hunk 4]
```diff
@@ -1442,18 +1462,7 @@ func (gce *GCECloud) AttachDisk(diskName string, readOnly bool) error {
...
-		if err != nil {
-			return err
-		}
-		for _, disk := range instance.Disks {
-			if disk.Source == attachedDisk.Source {
-				// Disk is already attached, we're good to go.
-				return nil
-			}
-		}
+		return err
```
Comment (cjcullen) [inline pkg/cloudprovider/providers/gce/gce.go]: Was removing this intentional?

Comment (cjcullen) [inline pkg/cloudprovider/providers/gce/gce.go]: I see now it probably was.

File: pkg/cloudprovider/providers/gce/gce.go [hunk 5]
```diff
@@ -245,45 +248,62 @@ func (gce *GCECloud) targetPoolURL(name, region string) string {
 }
 
 func waitForOp(op *compute.Operation, getOperation func() (*compute.Operation, error)) error {
```
Comment (cjcullen) [inline pkg/cloudprovider/providers/gce/gce.go]: Could we just have `waitForOp` not take an operation? Or have `getOperation` be a `func(*compute.Operation) (*compute.Operation, error)`? Then you wouldn't have to check for nil in both places.

File: pkg/cloudprovider/providers/gce/gce.go (hunk 1 above)
Comment (alex-mohr) [inline pkg/cloudprovider/providers/gce/gce.go]: It's generally a violation of the GCE api contract for an operation to never go to DONE, but there are known edge cases where it can take 15-20 minutes or even more to get there.

Does the pd retry code handle the case where there's an already-pending operation to detach a disk and GCE returns an error creating a new operation to do the same thing?  If not, then retries may not be improving reliability.

Comment (saad-ali) [inline pkg/cloudprovider/providers/gce/gce.go]: > It's generally a violation of the GCE api contract for an operation to never go to DONE, but there are known edge cases where it can take 15-20 minutes or even more to get there.

I'm a big believer in defensive programming. Having a loop that can block indefinitely if the server returns the wrong thing or if there is a bug in the deserializer seems like a bad idea. I'm completely open to upping the limit to something very high... 30 minutes? Would you be ok with that?

> Does the pd retry code handle the case where there's an already-pending operation to detach a disk and GCE returns an error creating a new operation to do the same thing? If not, then retries may not be improving reliability.

The pd retry code would treat an already-pending operation as any other failure and would retry after some time. You're right that retries wouldn't improve reliability in that case. But they will eventually put the pod in a bad state, and generate events indicating that the pod is blocked because it is unable to attach the disk, because the attach timedout. Meaning the user eventually gets indication of what is going on, vs if this code blocked indefinitely the pod would be stuck forever in pending state, with no indication to the user what is happening.

File: pkg/cloudprovider/providers/gce/gce.go (hunk 2 above)
Comment (saad-ali) [inline pkg/cloudprovider/providers/gce/gce.go]: Added logging inside `getErrorFromCompletedOp`

File: pkg/cloudprovider/providers/gce/gce.go (hunk 3 above)
Comment (saad-ali) [inline pkg/cloudprovider/providers/gce/gce.go]: Nope, just a leftover from when error handling was being done outside. Changed it.

File: pkg/cloudprovider/providers/gce/gce.go (hunk 4 above)
Comment (saad-ali) [inline pkg/cloudprovider/providers/gce/gce.go]: Yep, intentional. If the disk is already attached, I want this to error out, and let the PD attach/detach code resolve it.

File: pkg/cloudprovider/providers/gce/gce.go (hunk 5 above)
Comment (saad-ali) [inline pkg/cloudprovider/providers/gce/gce.go]: Good idea, cleaned up.

File: pkg/cloudprovider/providers/gce/gce.go (hunk 1 above)
Comment (alex-mohr) [inline pkg/cloudprovider/providers/gce/gce.go]: Seems reasonable, thanks!  Given reasonable retry logic, 15 minutes seems fine.

File: pkg/cloudprovider/providers/gce/gce.go (hunk 2 above)
Comment (saad-ali) [inline pkg/cloudprovider/providers/gce/gce.go]: And logged this swallowed error.

**Comment by saad-ali** [comment]
Thanks for the feedback @cjcullen and @alex-mohr! PTAL

File: pkg/cloudprovider/providers/gce/gce.go [hunk 6]
```diff
@@ -244,47 +247,53 @@ func (gce *GCECloud) targetPoolURL(name, region string) string {
...
 	}
-	return nil
 
+	return nil
 }
 
 func (gce *GCECloud) waitForGlobalOp(op *compute.Operation) error {
-	return waitForOp(op, func() (*compute.Operation, error) {
+	return waitForOp(op, func(operationName string) (*compute.Operation, error) {
 		return gce.service.GlobalOperations.Get(gce.projectID, op.Name).Do()
```
Comment (cjcullen) [inline pkg/cloudprovider/providers/gce/gce.go]: This will now crash here if operation is nil. If you make the func `func(op *compute.Operation) (*compute.Operation, error)`, then waitForOp can be the only one that needs to check for nil. Then you'd also need to handle errors a little bit differently above (you would only want to assign the return value of `getOperation` to `pollOp` if `err` was nil).

Or you could do it the opposite way: Check for nil in each of the three `waitFor***Op()` functions. Then have waitForOp just be:
```
func waitForOp(getOperation func() (*compute.Operation, error)) error {
	op, err := getOperation()
	...
}
```

Comment (saad-ali) [inline pkg/cloudprovider/providers/gce/gce.go]: Whoops, I actually forgot to update `op.Name` to the new parameter `operationName`. The idea being that `waitFor...Op()` doesn't evaluate `op` therefore it doesn't need to do a nil check. Only `waitForOp()` does and it passes the `operationName` to the `getOperation()` function.

PTAL

**Comment by saad-ali** [comment]
@justinsb Could you review the volume changes please?

File: pkg/cloudprovider/providers/gce/gce.go [hunk 7]
```diff
@@ -244,48 +247,55 @@ func (gce *GCECloud) targetPoolURL(name, region string) string {
...
-			Message: pollOp.Error.Errors[0].Message,
+
+	if opIsDone(op) {
+		return getErrorFromCompletedOp(op)
+	}
+
+	opName := op.Name
+	return wait.Poll(operationPollInterval, operationPollTimeoutDuration, func() (bool, error) {
+		pollOp, err := getOperation(opName)
+		glog.Warningf("GCE poll operation failed: %v", err)
```
Comment (cjcullen) [inline pkg/cloudprovider/providers/gce/gce.go]:
```
if err != nil {
	glog.Warningf("GCE poll operation failed: %v", err)
}
```

File: pkg/cloudprovider/providers/gce/gce.go [hunk 8]
```diff
@@ -244,48 +247,55 @@ func (gce *GCECloud) targetPoolURL(name, region string) string {
...
+		return opIsDone(pollOp), getErrorFromCompletedOp(pollOp)
+	})
+}
+
+func opIsDone(op *compute.Operation) bool {
+	return op != nil && op.Status == "DONE"
+}
+
+func getErrorFromCompletedOp(op *compute.Operation) error {
```
Comment (cjcullen) [inline pkg/cloudprovider/providers/gce/gce.go]: This function is also used for non-completed ops. I'd call it getErrorFromOp, and leave a comment that the function will return nil if the op is nil or the op has no errors.

**Comment by cjcullen** [comment]
LGTM on the GCE cloudprovider stuff after my last 2 nits.

**Comment by saad-ali** [comment]
Thanks @cjcullen! I addressed the feedback and squashed the changes.

@justinsb please review the GCE volume changes when you get a chance. I'd like to get this in ASAP, since it is a 1.1 blocker. I've run overnight soak test and the changes make GCE volume attach/detach much more stable. Thanks

**Comment by brendandburns** [comment]
LGTM.

**Comment by alex-mohr** [comment]
Thanks for driving this Saad!

**Comment by saad-ali** [comment]
@alex-mohr No problem. Could you confirm if you ok with: `operationPollTimeoutDuration = 10 * time.Minute`? Or should we increase it to 30 minutes?

**Comment by alex-mohr** [comment]
@saad-ali Re: 10 minutes vs 30, if you have high confidence in the retry code handling simultaneous disk attach/detach operations correctly and that makes event handling better, 10 minutes should also work.  It's a persistent object in the GCE database that has a bunch of internal logic to drive it to completion (success or failure), so having multiple in flight at a time is unlikely to actually help and could even trigger less-tested code paths.  Your call, I'm fine with either.

**Comment by saad-ali** [comment]
I changed it to from 10 minutes to 30 minutes to be safe--since there are some operations that are known to take a very long time.

PTAL and add a re-add the LGTM label.

File: pkg/util/keymutex/keymutex.go [hunk 9]
```diff
@@ -0,0 +1,82 @@
...
+// Returns a new instance of a key mutex.
+func NewKeyMutex() KeyMutex {
+	return &keyMutex{
+		mutexMap: make(map[string]*sync.Mutex),
+	}
+}
+
+type keyMutex struct {
+	sync.RWMutex
+	mutexMap map[string]*sync.Mutex
```
Comment (lavalamp) [inline pkg/util/keymutex/keymutex.go]: what prevents this from growing forever?

Comment (saad-ali) [inline pkg/util/keymutex/keymutex.go]: Nothing. The map will track all the unique PDs seen by the kubelet during its runtime. However, I don't foresee this as being an issue unless someone is attaching/detaching millions of unique PDs (over the course of a a kubelet lifetime, which I'd guess is about a month for machine due to reboots required for patching), at which point they are likely to run in to GCE quota issues first.

**Comment by lavalamp** [comment]
@k8s-bot test this please

**Comment by lavalamp** [comment]
@k8s-bot unit test this please

File: pkg/util/keymutex/keymutex.go (hunk 9 above)
Comment (alex-mohr) [inline pkg/util/keymutex/keymutex.go]: FWIW, another time we decided that resource garbage collection wasn't important, it ended up biting us due to causing kubelet CPU usage to increase by 10% a day.

And if we make multiple such leak-100-bytes-per-pod-attempt decisions in various places, it'll become unworkable pretty quickly.

Is there a not-too-unreasonable fix for the leak?  File an issue or at least document the known-leaking behavior in comments?

Comment (saad-ali) [inline pkg/util/keymutex/keymutex.go]: Opened up #16305 to track this.
