### PR TITLE
Mark volume as in use even when node status didn't change

### LINKED ISSUE #72931: [sig-storage] unmount tests are failing in master-blocking and master-upgrade dashboards
**Which jobs are failing**:
- [sig-release-master-blocking#gce-cos-master-serial](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-serial)
- [sig-release-master-upgrade#gce-new-master-upgrade-cluster-new](https://testgrid.k8s.io/sig-release-master-upgrade#gce-new-master-upgrade-cluster-new)

**Which test(s) are failing**:
- [sig-storage] CSI Volumes [Driver: csi-hostpath-v0] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]
- [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]
- [sig-storage] CSI Volumes [Driver: pd.csi.storage.gke.io][Serial] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]

**Since when has it been failing**:
2019-01-15 (when they were added)

**Testgrid link**:
- [master-blocking](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/4554)
- [master-upgrade](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster-new/1966)

**Reason for failure**:
They all seem to be failing with:
```
Expected grep stdout to be empty (i.e. no mount found).
```

The failures seem to start with [commit 72895](https://github.com/kubernetes/kubernetes/commit/148248353b883f0dbbefa38100b675a7ed3ba587).

### PR DESCRIPTION
**Pull request by msau42**
**What type of PR is this?**
/kind bug
/kind test-failure

**What this PR does / why we need it**:
This PR marks volumes as in use even if the Node status didn't change.  This is important for kubelet restart when the Node may still have volumes mounted previously and VolumesInUse is still populated.

**Which issue(s) this PR fixes**:

Fixes #72931

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/kubelet/kubelet_node_status.go [hunk 1]
```diff
@@ -427,6 +427,13 @@ func (kl *Kubelet) tryUpdateNodeStatus(tryNumber int) error {
 	now := kl.clock.Now()
 	if utilfeature.DefaultFeatureGate.Enabled(features.NodeLease) && now.Before(kl.lastStatusReportTime.Add(kl.nodeStatusReportFrequency)) {
 		if !podCIDRChanged && !nodeStatusHasChanged(&originalNode.Status, &node.Status) {
+			// We must update the volumes in use even if no changes were made to the node
```
Comment (msau42) [inline pkg/kubelet/kubelet_node_status.go]: When do we set the Node status to ready?  I wonder if the test case still has a race condition.  When the test [restarts kubelet](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/test/e2e/storage/utils/utils.go#L239), it:
1. Waits for the Node to become ready.
2. Immediately checks the mounts on the node.

Could the node be set to ready before we mark the volume as in use and cleanup the mounts?

**Comment by msau42** [comment]
@kubernetes/sig-storage-pr-reviews 
@kubernetes/sig-node-pr-reviews

File: pkg/kubelet/kubelet_node_status.go (hunk 1 above)
Comment (wangzhen127) [reply pkg/kubelet/kubelet_node_status.go]: The node is set to ready on line 425 when kubelet decides that the node is ready. It is another setter ([ready condition setter](https://github.com/kubernetes/kubernetes/blob/92076f0d2e2409253d90c55c434035ef6b9bbcb6/pkg/kubelet/nodestatus/setters.go#L439)).

So if the node was ready before kubelet restarts, I think the node is still ready after kubelet restarts. Does this help?

**Review by wangzhen127 — COMMENTED** [review]
It seems that the tests pass?

File: pkg/kubelet/kubelet_node_status.go (hunk 1 above)
Comment (msau42) [reply pkg/kubelet/kubelet_node_status.go]: I discussed with @jingxu97. I missed one more step in the test case.  Before steps 1) and 2), the test also waits for the Pod API object [to be gone](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/test/e2e/storage/utils/utils.go#L240).  And that cannot happen until we've successfully unmounted the volume.  So there should not be a race condition in the test.

Comment (jingxu97) [reply pkg/kubelet/kubelet_node_status.go]: How about adding a few words in the comments like this

"We must mark the volumes as ReportedInUse in volume manager's dsw even if no changes were made to the node status (no volumes were added or removed from the VolumeInUse list in node status). The reason is that in case of kubelet restarts, dsw is repopulated and volume ReportedInUse would be set to false first. If no status update is needed here, it means that the volumes are already in the VolumeInUse list from the node status. We need to make sure to set those volumes in dsw as ReportedInUse to true. 
// This MarkVolumeReportedInUse cannot be performed in dsw directly because it does not have the access to the node object. This also cannot be populated on node status manager init because the volume may not have been added to dsw at that time.

Comment (msau42) [reply pkg/kubelet/kubelet_node_status.go]: Updated, ptal

**Comment by yujuhong** [comment]
Is it possible to add a unit test?

**Comment by msau42** [comment]
Yes good point

**Comment by msau42** [comment]
Added unit tests, this is ready for review again

**Comment by msau42** [comment]
One more thing to investigate is why this caused only csi volume tests to fail and not intree

File: pkg/kubelet/volumemanager/volume_manager_fake.go [hunk 2]
```diff
@@ -0,0 +1,99 @@
+/*
+Copyright 2018 The Kubernetes Authors.
```
Comment (jingxu97) [inline pkg/kubelet/volumemanager/volume_manager_fake.go]: Copyright 2019

Comment (msau42) [reply pkg/kubelet/volumemanager/volume_manager_fake.go]: fixed

File: pkg/kubelet/kubelet_node_status_test.go [hunk 3]
```diff
@@ -1029,6 +1030,213 @@ func TestUpdateNodeStatusWithLease(t *testing.T) {
...
+				nodestatus.VolumesInUse(kubelet.volumeManager.ReconcilerStatesHasBeenSynced,
+					kubelet.volumeManager.GetVolumesInUse),
+			}
+
+			kubeClient := testKubelet.fakeKubeClient
+			kubeClient.ReactionChain = fake.NewSimpleClientset(&v1.NodeList{Items: []v1.Node{*tc.existingNode}}).ReactionChain
+
+			// Update node status when node status is created.
+			// Report node status.
+			kubelet.updateRuntimeUp()
```
[the remark this answers is not in the document]
Comment (msau42) [reply pkg/kubelet/kubelet_node_status_test.go]: removed

File: pkg/kubelet/kubelet_node_status_test.go [hunk 4]
```diff
@@ -31,7 +31,7 @@ import (
 	"github.com/stretchr/testify/require"
 
 	cadvisorapi "github.com/google/cadvisor/info/v1"
-	"k8s.io/api/core/v1"
+	v1 "k8s.io/api/core/v1"
```
Comment (yujuhong) [inline pkg/kubelet/kubelet_node_status_test.go]: Don't need this change.

File: pkg/kubelet/kubelet_node_status.go [hunk 5]
```diff
@@ -26,7 +26,7 @@ import (
 
 	"k8s.io/klog"
 
-	"k8s.io/api/core/v1"
+	v1 "k8s.io/api/core/v1"
```
Comment (yujuhong) [inline pkg/kubelet/kubelet_node_status.go]: Remove the change

**Review by yujuhong — COMMENTED** [review]
Thanks for adding the tests! 
Looks good overall with some minor commetns.

File: pkg/kubelet/kubelet_node_status_test.go (hunk 4 above)
Comment (msau42) [reply pkg/kubelet/kubelet_node_status_test.go]: removed

File: pkg/kubelet/kubelet_node_status.go (hunk 5 above)
Comment (msau42) [reply pkg/kubelet/kubelet_node_status.go]: removed

**Comment by yujuhong** [comment]
@msau42 `pull-kubernetes-local-e2e-containerized` is not required. Let it fail :-)
