### PR TITLE
patch scale subresources inside guaranteedupdate loop

### LINKED ISSUE #89740: [Flaky Test] [sig-apps] ReplicationController should test the lifecycle of a ReplicationController
**Which jobs are flaking**:
- pull-kubernetes-e2e-gce
- pull-kubernetes-e2e-kind

**Which test(s) are flaking**:
- [sig-apps] ReplicationController should test the lifecycle of a ReplicationController

**Testgrid link**:
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce&include-filter-by-regex=ReplicationController%20should%20test&width=10
- https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind&include-filter-by-regex=ReplicationController%20should%20test&width=10

**Reason for failure**:
```
test/e2e/apps/rc.go:100
Apr  1 00:19:30.365: Failed to patch ReplicationControllerScale
Unexpected error:
    <*errors.StatusError | 0xc001505180>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "Operation cannot be fulfilled on replicationcontrollers \"rc-test\": the object has been modified; please apply your changes to the latest version and try again",
            Reason: "Conflict",
            Details: {
                Name: "rc-test",
                Group: "",
                Kind: "replicationcontrollers",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 409,
        },
    }
    Operation cannot be fulfilled on replicationcontrollers "rc-test": the object has been modified; please apply your changes to the latest version and try again
occurred
test/e2e/apps/rc.go:195
```

**Anything else we need to know**:
- test was introduced via https://github.com/kubernetes/kubernetes/pull/88588
- links to specific failures
  - https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88036/pull-kubernetes-e2e-kind/1245137431854845954
  - https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/89715/pull-kubernetes-e2e-gce/1245372983606775809/

- ref: https://github.com/kubernetes/kubernetes/pull/88588#issuecomment-607366847
>Choices are:
>
>- patch something the controller isn't messing with regularly (not sure what that would be)
>- properly handle optimistic concurrency by retrying in these cases, AND by not necessarily expecting the value we write to be there later

/assign @hh @BobyMCbobs 
/sig architecture
/area conformance
/sig apps
/priority important-soon
It's flaking, but not so bad as to show up in triage and flakes-latest.json. If it gets there I'll bump priority.

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Applies patches sent to scale subresources inside the guaranteedupdate loop, to ensure that a patch without a resourceVersion or uid precondition does not receive a 409 conflict error response.

Also adds test coverage for handling of notfound, uid and resourceVersion conflicts when patching scale subresources.

This matches the fix made for custom resource scale subresource handling done in https://github.com/kubernetes/kubernetes/pull/80572#issuecomment-517724451

**Which issue(s) this PR fixes**:
Fixes #89740

**Does this PR introduce a user-facing change?**:
```release-note
kube-apiserver: fixes scale subresource patch handling to avoid returning unnecessary 409 Conflict error to clients
```

/sig apps

### CODE REVIEW

File: pkg/registry/apps/deployment/storage/storage.go [hunk 1]
```diff
@@ -376,3 +347,62 @@ func scaleFromDeployment(deployment *apps.Deployment) (*autoscaling.Scale, error
...
+		return nil, err
+	}
+
+	// old scale -> new scale
+	newScaleObj, err := i.reqObjInfo.UpdatedObject(ctx, oldScale)
+	if err != nil {
+		return nil, err
+	}
+	if newScaleObj == nil {
+		return nil, errors.NewBadRequest(fmt.Sprintf("nil update passed to Scale"))
```
Comment (neolit123) [inline pkg/registry/apps/deployment/storage/storage.go:383]: (this is from the old code) the sprintf call can be omitted
(applies to the other object types's storage / storage_test)

File: pkg/registry/apps/deployment/storage/storage.go [hunk 2]
```diff
@@ -376,3 +347,62 @@ func scaleFromDeployment(deployment *apps.Deployment) (*autoscaling.Scale, error
...
+	if errs := autoscalingvalidation.ValidateScale(scale); len(errs) > 0 {
+		return nil, errors.NewInvalid(autoscaling.Kind("Scale"), deployment.Name, errs)
+	}
+
+	// validate precondition if specified (resourceVersion matching is handled by storage)
+	if len(scale.UID) > 0 && scale.UID != deployment.UID {
+		return nil, errors.NewConflict(
+			apps.Resource("deployments/scale"),
+			deployment.Name,
+			fmt.Errorf("Precondition failed: UID in precondition: %v, UID in object meta: %v", scale.UID, deployment.UID),
```
Comment (neolit123) [inline pkg/registry/apps/deployment/storage/storage.go:400]: should the error still begin with lower case here?
(applies to the other object types's storage / storage_test)

File: pkg/registry/apps/deployment/storage/storage_test.go [hunk 3]
```diff
@@ -451,3 +453,123 @@ func TestCategories(t *testing.T) {
...
+	storage, server := newStorage(t)
+	defer server.Terminate(t)
+	validObj := validNewDeployment()
+	resourceStore := storage.Deployment.Store
+	scaleStore := storage.Scale
+
+	defer resourceStore.DestroyFunc()
+	ctx := genericapirequest.WithNamespace(genericapirequest.NewContext(), namespace)
+
+	{
```
Comment (neolit123) [inline pkg/registry/apps/deployment/storage/storage_test.go:467]: these closures are not really needed, i guess?
(applies to the other object types's storage / storage_test)

**Review by neolit123 — COMMENTED** [review]
not sure why the bots pinged me here. :thinking:

File: pkg/registry/apps/deployment/storage/storage.go (hunk 2 above)
Comment (liggitt) [reply pkg/registry/apps/deployment/storage/storage.go:400]: I matched precondition error message format used elsewhere for consistency

File: pkg/registry/apps/deployment/storage/storage_test.go (hunk 3 above)
Comment (liggitt) [reply pkg/registry/apps/deployment/storage/storage_test.go:467]: I added the blocks to keep the helper function for each step local to avoid copy/paste reference errors

File: pkg/registry/apps/deployment/storage/storage.go (hunk 1 above)
Comment (liggitt) [reply pkg/registry/apps/deployment/storage/storage.go:383]: cleaned up

**Comment by deads2k** [comment]
Alright, in case other reviewers don't see it.  The store.Update func here https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L475 is taking a func that works kind of like `retryOnConflict` for the REST API.  If you don't get new input inside of that retry (what this PR does), you will always conflict.  If you do reget it and do not specify a precondition, the code will re-GET, and retry the update

/lgtm
