### PR TITLE
Inject SSH public key into CRI-O serial prow jobs

### LINKED ISSUE #24798: Issue with SSH key on k8s-infra-prow-build cluster for CRI-O nodes
**What happened**:

Every time we try to run CRI-O tests on the k8s-infra-prow-build cluster, SSH fails. Most recently:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107361/pull-kubernetes-node-kubelet-serial-crio-cgroupv1/1479158719756374016/#1:build-log.txt%3A327

```
W0106 18:45:27.531] I0106 18:45:27.530809    6869 ssh.go:120] Running the command ssh, with args: [-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o CheckHostIP=no -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o LogLevel=ERROR -i /workspace/.ssh/google_compute_engine core@35.203.133.173 -- sudo sh -c 'systemctl list-units  --type=service  --state=running | grep -e docker -e containerd -e crio']
W0106 18:45:27.942] E0106 18:45:27.942276    6869 ssh.go:123] failed to run SSH command: out: core@35.203.133.173: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
W0106 18:45:27.942] , err: exit status 255 
```

**What you expected to happen**:

Tests should successfully be able to ssh.

**How to reproduce it (as minimally and precisely as possible)**:

We've seen this every time we've tried to migrate CRI-O tests to this cluster, e.g. https://github.com/kubernetes/kubernetes/issues/102624 https://github.com/kubernetes/test-infra/pull/24591

I think there is an issue with the SSH key. We keep working around this by avoiding running CRI-O tests on this cluster. Can someone from SIG Infra help out?

**Please provide links to example occurrences, if any**:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107361/pull-kubernetes-node-kubelet-serial-crio-cgroupv1/1479158719756374016/#1:build-log.txt%3A327

**Anything else we need to know?**:

/sig node k8s-infra

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind failing-test

#### What this PR does / why we need it:

This allows using the `GCE_SSH_PUBLIC_KEY_FILE_CONTENT` placeholder to inject the public SSH key for running the tests.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/test-infra/issues/24798

#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by ehashman** [comment]
The tests appear to have worked without https://github.com/kubernetes/test-infra/pull/25735 landing. Is that actually a prereq for this PR?

**Comment by saschagrunert** [comment]
https://github.com/kubernetes/test-infra/pull/25754 should fix the test exclusion

**Comment by saschagrunert** [comment]
https://github.com/kubernetes/test-infra/pull/25754 merged, giving the tests another try

/test pull-kubernetes-node-kubelet-serial-crio-cgroupv1
/test pull-kubernetes-node-kubelet-serial-crio-cgroupv2

File: test/e2e_node/runner/remote/run_remote.go [hunk 1]
```diff
@@ -907,6 +910,35 @@ func parseInstanceMetadata(str string) map[string]string {
 	return metadata
 }
 
+func crioSerialInjectSSHPublicKey(path string, content []byte) []byte {
+	// Exclude non CRI-O serial tests
+	if !strings.HasSuffix(path, "/test-infra/jobs/e2e_node/crio/crio_serial.ign") &&
+		!strings.HasSuffix(path, "/test-infra/jobs/e2e_node/crio/crio_cgrpv2_serial.ign") {
```
Comment (ehashman) [inline test/e2e_node/runner/remote/run_remote.go:916]: This will only work on the serial jobs, but we have a number of other CRI-O presubmits we want to get working, and hardcoding one config path here is already kind of hacky, let alone 2. Can we factor out the constant and update this to

```suggestion
	if !strings.Contains(path, "/test-infra/jobs/e2e_node/crio/") {
```

File: test/e2e_node/runner/remote/run_remote.go [hunk 2]
```diff
@@ -907,6 +910,35 @@ func parseInstanceMetadata(str string) map[string]string {
...
+		return content
+	}
+
+	klog.Infof("Injecting SSH public key into CRI-O serial ignition")
+
+	const publicKeyEnv = "GCE_SSH_PUBLIC_KEY_FILE"
+	sshPublicKeyFile := os.Getenv(publicKeyEnv)
+	if sshPublicKeyFile == "" {
+		klog.Fatalf("Environment variable %s is not set", publicKeyEnv)
```
Comment (ehashman) [inline test/e2e_node/runner/remote/run_remote.go:925]: Please don't use `klog.Fatalf`, that's deprecated: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#replacing-fatal-calls

File: test/e2e_node/runner/remote/run_remote.go (hunk 1 above)
Comment (ehashman) [reply test/e2e_node/runner/remote/run_remote.go:916]: Looking this over, we might want to consider not restricting this to CRI-O, and instead checking an environment variable that we can configure in test-infra.

Comment (saschagrunert) [reply test/e2e_node/runner/remote/run_remote.go:916]: Good, we can do that by using an env variable in https://github.com/kubernetes/test-infra/pull/25764

File: test/e2e_node/runner/remote/run_remote.go (hunk 2 above)
Comment (saschagrunert) [reply test/e2e_node/runner/remote/run_remote.go:925]: Fixed :+1:

**Comment by saschagrunert** [comment]
> /test pull-kubernetes-node-crio-cgrpv2-e2e /test pull-kubernetes-node-crio-e2e /test pull-kubernetes-node-crio-cgrpv2-e2e-kubetest2 /test pull-kubernetes-node-crio-e2e-kubetest2

Oh, I think we should fix them afterwards as well :+1:

**Review by ehashman — COMMENTED** [review]
/approve
/lgtm
