### PR TITLE
Automated cherry pick of #62303 to release-1.10: Refactor subpath reconstruction tests to use util test

### LINKED ISSUE #62697: Test Failure : [sig-storage] Subpath [Volume type: gcePDPVC] should unmount if pod is gracefully deleted while kubelet is down [Disruptive][Slow]
## Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-04-16&sig=storage&test=%20should%20unmount%20if%20pod%20is%20gracefully%20deleted%20while%20kubelet%20is%20down

Has been consistently failing since 4/6. [Commit changes](https://github.com/kubernetes/kubernetes/compare/d4ded15f8...8eb156fe6)

@saad-ali can you please help triage?

/kind bug
/priority failing-test
/priority important-soon
/sig storage
/milestone 1.11
@kubernetes/sig-storage-bugs 

cc @jberkus @tpepper

/assign @saad-ali

### PR DESCRIPTION
**Pull request by msau42**
Cherry pick of #62303 to release-1.10: Refactor subpath reconstruction tests to use util test

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #62697

**Special notes for your reviewer**:
I had to do some manual merges because generic-persistent-volumes.go doesn't exist in 1.10.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MaciekPytel** [comment]
@msau42 This looks more like a refactor / cleanup than fixing some problem in tests. Can you add some context on why do we need to cherrypick?

**Comment by MaciekPytel** [comment]
/hold 
@msau42 How urgent is this? Are you ok with this waiting for 1.10.3? I'm freezing release branch for 1.10.2 today and there are a lot of critical cherry-picks going in today, so I'd rather postpone lower priority stuff.

Feel free to cancel hold if you think it needs to be included in 1.10.2 (it would need to be lgtm-ed today to make it in though).

**Comment by msau42** [comment]
Postponing is fine. I believe the upgrade tests will use head of the release branches

File: test/e2e/storage/utils/utils.go [hunk 1]
```diff
@@ -156,18 +156,26 @@ func TestKubeletRestartsAndRestoresMount(c clientset.Interface, f *framework.Fra
...
-func TestVolumeUnmountsFromDeletedPodWithForceOption(c clientset.Interface, f *framework.Framework, clientPod *v1.Pod, pvc *v1.PersistentVolumeClaim, pv *v1.PersistentVolume, forceDelete bool) {
+// forceDelete is true indicating whether the pod is forcefully deleted.
+func TestVolumeUnmountsFromDeletedPodWithForceOption(c clientset.Interface, f *framework.Framework, clientPod *v1.Pod, forceDelete bool, checkSubpath bool) {
 	nodeIP, err := framework.GetHostExternalAddress(c, clientPod)
 	Expect(err).NotTo(HaveOccurred())
 	nodeIP = nodeIP + ":22"
 
 	By("Expecting the volume mount to be found.")
-	result, err := framework.SSH(fmt.Sprintf("mount | grep %s", clientPod.UID), nodeIP, framework.TestContext.Provider)
+	result, err := framework.SSH(fmt.Sprintf("mount | grep %s | grep -v volume-subpaths", clientPod.UID), nodeIP, framework.TestContext.Provider)
```
Comment (davidz627) [inline test/e2e/storage/utils/utils.go]: should this only grep for volume-subpaths when checkSubpath is true?

File: test/e2e/storage/utils/utils.go [hunk 2]
```diff
@@ -182,6 +190,10 @@ func TestVolumeUnmountsFromDeletedPodWithForceOption(c clientset.Interface, f *f
 		err = c.CoreV1().Pods(clientPod.Namespace).Delete(clientPod.Name, &metav1.DeleteOptions{})
 	}
 	Expect(err).NotTo(HaveOccurred())
+
+	// Wait for pod to enter "Terminating state"
+	time.Sleep(30 * time.Second)
```
Comment (davidz627) [inline test/e2e/storage/utils/utils.go]: Can we use one of the fancy API Machinery wait functions here to wait for that specific condition. Like a wait.Until (not sure if thats the exact call)

File: test/e2e/storage/utils/utils.go [hunk 3]
```diff
@@ -194,22 +206,32 @@ func TestVolumeUnmountsFromDeletedPodWithForceOption(c clientset.Interface, f *f
 		// so wait some time to finish
 		time.Sleep(30 * time.Second)
 	}
+
 	By("Expecting the volume mount not to be found.")
-	result, err = framework.SSH(fmt.Sprintf("mount | grep %s", clientPod.UID), nodeIP, framework.TestContext.Provider)
+	result, err = framework.SSH(fmt.Sprintf("mount | grep %s | grep -v volume-subpaths", clientPod.UID), nodeIP, framework.TestContext.Provider)
```
Comment (davidz627) [inline test/e2e/storage/utils/utils.go]: ditto. should volume-subpaths always be here?

Comment (davidz627) [reply test/e2e/storage/utils/utils.go]: Also is there a specific reason we have the "-v" version flag?

File: test/e2e/storage/vsphere/persistent_volumes-vsphere.go [hunk 4]
```diff
@@ -178,7 +178,7 @@ var _ = utils.SIGDescribe("PersistentVolumes:vsphere", func() {
 		3. Verify that written file is accessible after kubelet restart
 	*/
 	It("should test that a file written to the vspehre volume mount before kubelet restart can be read after restart [Disruptive]", func() {
-		utils.TestKubeletRestartsAndRestoresMount(c, f, clientPod, pvc, pv)
+		utils.TestKubeletRestartsAndRestoresMount(c, f, clientPod)
```
Comment (davidz627) [inline test/e2e/storage/vsphere/persistent_volumes-vsphere.go]: A little confused here, if we're removing the pv, pvc from the spec, why does this PR not have any added code which creates PV and PVC somewhere else? Or was it unused to begin with

File: test/e2e/storage/utils/utils.go (hunk 3 above)
Comment (msau42) [reply test/e2e/storage/utils/utils.go]: -v means exclude the lines that match.  I think it is fine to exclude subpaths from the results because this line is only checking for regular mounts, not subpath mounts.

File: test/e2e/storage/vsphere/persistent_volumes-vsphere.go (hunk 4 above)
Comment (msau42) [reply test/e2e/storage/vsphere/persistent_volumes-vsphere.go]: Yeah, PVC/PV dependencies were removed in a different PR, but they didn't remove the variables from the arguments.

File: test/e2e/storage/utils/utils.go (hunk 2 above)
Comment (msau42) [reply test/e2e/storage/utils/utils.go]: Let me see if this is actually needed in the cherry pick, as this call was added in master originally but not backported here.

File: test/e2e/storage/utils/utils.go (hunk 3 above)
Comment (davidz627) [reply test/e2e/storage/utils/utils.go]: can we use `--invert-match` instead. I confused it with `-V` which is the `--version` flag

File: test/e2e/storage/vsphere/persistent_volumes-vsphere.go (hunk 4 above)
Comment (davidz627) [reply test/e2e/storage/vsphere/persistent_volumes-vsphere.go]: ack

File: test/e2e/storage/utils/utils.go (hunk 3 above)
Comment (msau42) [reply test/e2e/storage/utils/utils.go]: done

File: test/e2e/storage/subpath.go [hunk 5]
```diff
@@ -563,64 +567,7 @@ func testSubpathReconstruction(f *framework.Framework, pod *v1.Pod, forceDelete
...
-	Expect(result.Stdout).To(BeEmpty(), "Expected grep stdout to be empty (i.e. no mount found).")
-	framework.Logf("Volume unmounted on node %s", pod.Spec.NodeName)
-
-	By("Expecting the subpath volume mount not to be found.")
-	result, err = framework.SSH(fmt.Sprintf("cat /proc/self/mountinfo | grep volume-subpaths | grep %s", pod.UID), nodeIP, framework.TestContext.Provider)
-	framework.LogSSHResult(result)
-	Expect(err).NotTo(HaveOccurred(), "Encountered SSH error.")
-	Expect(result.Stdout).To(BeEmpty(), "Expected grep stdout to be empty (i.e. no subpath mount found).")
-	framework.Logf("Subpath volume unmounted on node %s", pod.Spec.NodeName)
+	utils.TestVolumeUnmountsFromDeletedPodWithForceOption(f.ClientSet, f, pod, forceDelete, true)
```
[the remark this answers is not in the document]
Comment (msau42) [reply test/e2e/storage/subpath.go]: done
