### PR TITLE
Retry pod update on version conflict error in e2e test.

### LINKED ISSUE #7013: e2e test pod update test flaw
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/pods.go#L304

This is wrong because something else could have updated the pod in the mean time, invalidating your resource version. (Specifically, kubelet writes statuses.) It should do a get/update loop that retries as long as it gets a conflict error.

@quinton-hoole to find an owner

### PR DESCRIPTION
**Pull request by ghost**
Fixes #7013.

### CODE REVIEW

File: test/e2e/pods.go [hunk 1]
```diff
@@ -289,29 +291,38 @@ var _ = Describe("Pods", func() {
...
+			return false, fmt.Errorf("Failed to update pod: %v", err)
+		}))
 
 		expectNoError(waitForPodRunning(c, pod.Name))
 
 		By("verifying the updated pod is in kubernetes")
 		pods, err = podClient.List(labels.SelectorFromSet(labels.Set(map[string]string{"time": value})), fields.Everything())
 		Expect(len(pods.Items)).To(Equal(1))
-		fmt.Println("pod update OK")
+		By("pod update OK")
```
Comment (roberthbailey) [inline test/e2e/pods.go]: Maybe a Logf here instead of By()?

File: test/e2e/pods.go [hunk 2]
```diff
@@ -289,29 +291,38 @@ var _ = Describe("Pods", func() {
 		pods, err := podClient.List(labels.SelectorFromSet(labels.Set(map[string]string{"time": value})), fields.Everything())
 		Expect(len(pods.Items)).To(Equal(1))
 
-		By("retrieving the pod")
-		podOut, err := podClient.Get(pod.Name)
-		if err != nil {
-			Fail(fmt.Sprintf("Failed to get pod: %v", err))
-		}
+		// Standard get, update retry loop
+		expectNoError(wait.Poll(time.Second*5, time.Minute*2, func() (bool, error) {
```
Comment (lavalamp) [inline test/e2e/pods.go]: No need to wait 5 whole seconds between each attempt, is there? Can we reduce this to every 500ms for up to 30s?

File: test/e2e/pods.go [hunk 3]
```diff
@@ -289,29 +291,38 @@ var _ = Describe("Pods", func() {
...
-		pod.ResourceVersion = podOut.ResourceVersion
-		pod.UID = podOut.UID
-		pod.Spec.Host = podOut.Spec.Host
-		pod, err = podClient.Update(pod)
-		if err != nil {
-			Fail(fmt.Sprintf("Failed to update pod: %v", err))
-		}
+			By("updating the pod")
+			value = "time" + value
+			pod.Labels["time"] = value
```
Comment (lavalamp) [inline test/e2e/pods.go]: This is very important to this pattern: You must make changes to the pod you got from get ("podOut") and resubmit that pod. Otherwise, you could unintentionally blow away changes made by someone else.

(Or something functionally equivilent like deep copy podOut over pod, but that's needless.)

File: test/e2e/pods.go (hunk 1 above)
Comment (quinton-hoole) [inline test/e2e/pods.go]: Agreed, done.

File: test/e2e/pods.go (hunk 2 above)
Comment (quinton-hoole) [inline test/e2e/pods.go]: Yup, good idea.  Will do.

File: test/e2e/pods.go (hunk 3 above)
Comment (quinton-hoole) [inline test/e2e/pods.go]: Agreed.  That's not what the original test did, so I tried to minimize changes.  But in retrospect I agree and I'll fix that.

**Comment by quinton-hoole** [comment]
All feedback addressed, and tidied up a few other related things hanging around from the previous version of this test.  PTAL @lavalamp

File: test/e2e/pods.go [hunk 4]
```diff
@@ -289,29 +291,33 @@ var _ = Describe("Pods", func() {
...
+			value = strconv.Itoa(time.Now().Nanosecond())
+			pod.Labels["time"] = value
+			pod, err = podClient.Update(pod)
+			if err == nil {
+				Logf("Successfully updated pod")
+				return true, nil
+			}
+			if errors.IsConflict(err) {
+				Logf("Conflicting update to pod, re-get and re-update: %v", err)
+				pod, err = podClient.Get((*pod).Name)
```
Comment (lavalamp) [inline test/e2e/pods.go]: Doing the update/get in this order gives an entire 5 seconds for someone to modify the pod and force you into another loop... I'd recommend changing the order back. :)

Comment (quinton-hoole) [inline test/e2e/pods.go]: Yes, sorry, and I just remembered I forgot to change the time periods.
Let me change those and get back to you.

**Comment by quinton-hoole** [comment]
OK, I reduced the retry interval to 500ms for 30s, and changed the code so that the first update attempt (which usually succeeds) uses the original return value of the Create call.  Only retries do another Get.  Hope you like it.  I could fairly easily be convinced to just do a Get before every Update to get rid of the "if" statement - but that would add a completely unnecessary API call in the most common case.

**Comment by lavalamp** [comment]
LGTM
