### PR TITLE
Fix installation and use of vendored godep

### LINKED ISSUE #58975: pull-kubernetes-verify: godep version bump broke build
Didn't see an issue for this.

Godep recently updated its version to v80. This broke several builds that directly `go get` godep, grabbing latest. https://github.com/tools/godep/commit/ce0bfadeb516ab23c845a85c4b0eae421ec9614b

/kind bug

cc @sttts @caesarxuchao @kubernetes/sig-api-machinery-bugs 

Example https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/58544/pull-kubernetes-verify/74168/

```
      !!! [0129 17:15:00] Expected godep v79, got godep v80 (linux/amd64/go1.9.1)
```

Here are some examples where we grab master:

```terminal
$ ag 'go get github.com/tools/godep'
vendor/github.com/tools/godep/Readme.md
18:$ go get github.com/tools/godep

vendor/github.com/tools/godep/Changelog.md
404:did a `go get github.com/tools/godep`.

hack/jenkins/verify-dockerized.sh
37:retry go get github.com/tools/godep && godep version

hack/jenkins/test-dockerized.sh
36:retry go get github.com/tools/godep && godep version

hack/jenkins/benchmark-dockerized.sh
36:retry go get github.com/tools/godep && godep version
```

### PR DESCRIPTION
**Pull request by cblecker**
**What this PR does / why we need it**:
Fixes the installation of the vendored godep to ensure that the binary ends up in the path when it's done.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #58975

**Special notes for your reviewer**:
It looks like this broke in https://github.com/kubernetes/kubernetes/pull/51766, but didn't matter because our pinned version was the same as the latest version (so we didn't notice). This fixes it in my local env -- hopefully it will in CI too.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

File: hack/jenkins/verify.sh [hunk 1]
```diff
@@ -32,6 +32,5 @@ export PATH=${GOPATH}/bin:${HOME}/third_party/etcd:/usr/local/go/bin:$PATH
 
 # Install a few things needed by the verification tests.
 command -v etcd &>/dev/null || ./hack/install-etcd.sh
-go get -u github.com/tools/godep
```
Comment (sttts) [inline hack/jenkins/verify.sh]: expected some more calls to `kube::util::ensure_godep_version` in the changed files above. All of them have that already but were overriding the ensure godep version?

Comment (cblecker) [reply hack/jenkins/verify.sh]: All of these `hack/jenkins/` scripts are trying to be smart and pre-load godep for you. However, on first use, we will run the ensure function to install it. We don't need it pre-loaded. The only script that didn't do this properly was `verify-godeps.sh` and I've added it there. Better to have the ensure function as close to the using script.

Comment (sttts) [reply hack/jenkins/verify.sh]: Alright. That's what I was hoping.

**Comment by sttts** [comment]
/lgtm

To stop the bleeding.

File: hack/lib/util.sh [hunk 2]
```diff
@@ -446,6 +446,9 @@ kube::util::ensure_godep_version() {
 
   kube::log::status "Installing godep version ${GODEP_VERSION}"
   go install ./vendor/github.com/tools/godep/
+  GP="$(echo $GOPATH | cut -f1 -d:)"
+  hash -r # force bash to clear PATH cache
+  PATH="${GP}/bin:${PATH}"
```
Comment (thockin) [inline hack/lib/util.sh]: I really don't think util scrips should be changing PATH like this.  It should be the caller's responsibilityt o make sure GOPATH/bin is in PATH

File: hack/verify-godeps.sh [hunk 3]
```diff
@@ -53,6 +29,9 @@ if ! [[ ${KUBE_FORCE_VERIFY_CHECKS:-} =~ ^[yY]$ ]] && \
   exit 0
 fi
 
+# Ensure we have the right godep version available
+kube::util::ensure_godep_version
```
Comment (thockin) [inline hack/verify-godeps.sh]: Why do we need this?  Both godep-restore.sh and godep-save.sh call this...

File: hack/lib/util.sh (hunk 2 above)
Comment (thockin) [reply hack/lib/util.sh]: https://github.com/kubernetes/kubernetes/pull/57600/files#diff-fa58360a7125fddab9491c80bb3f1a87

and

https://github.com/kubernetes/kubernetes/pull/57600/files#diff-85254102210f2a3edc79a4ae67a3448e

Comment (cblecker) [reply hack/lib/util.sh]: This was previously in the script, before your PR (#58975) to vendor godep. The issue is not just it being *in* the path, but also being at the *front* of the path so that we select it first. Note, we aren't exporting this, so it's not persistent past the end of the script.

File: hack/verify-godeps.sh (hunk 3 above)
Comment (cblecker) [reply hack/verify-godeps.sh]: The issue with that is that we create a new temporary gopath to restore/save the deps, and that GOPATH/bin won't ever be in the path, as it's in a randomly generated temp folder.

File: hack/lib/util.sh (hunk 2 above)
Comment (cblecker) [reply hack/lib/util.sh]: The other option I considered here was setting a temp GOBIN with a well-known location, then calling it directly. I opted for the option that was closer to the revert because this was blocking all presubmits triggered godep verification.

File: hack/verify-godeps.sh (hunk 3 above)
Comment (sttts) [reply hack/verify-godeps.sh]: > Why do we need this?

What is the issue with this call? Is it the "ensure" that you don't like? I.e. we could just check and complain, or install into a temporary dir.

File: hack/lib/util.sh (hunk 2 above)
Comment (sttts) [reply hack/lib/util.sh]: > It should be the caller's responsibilityt o make sure GOPATH/bin is in PATH

+1

**Comment by cblecker** [comment]
@thockin @sttts maybe #59210 is an alternative?

File: hack/verify-godeps.sh (hunk 3 above)
Comment (thockin) [reply hack/verify-godeps.sh]: It's disconnected from where it is being used, and it is already called in teh places where it is being used (or should be).

Comment (thockin) [reply hack/verify-godeps.sh]: @cblecker - not sure I understand your point.  Wherever we change GOPATH we should also change PATH
