### PR TITLE
Include unavailable apiservices in discovery response

### LINKED ISSUE #2254: Orphaned Service Catalog objects after Namespace deletion during Service Catalog API server outage
# Bug Report 

**What happened**:
During Service Catalog API server outage, namespace deletion proceeds without waiting for Service Catalog objects to finish their deletion.

**What you expected to happen**:
1. Namespace shouldn't proceed with deletion during Service Catalog outage. We may add Service Catalog finalizer to every namespace to achieve this.
2. Otherwise, when we reconcile Service Catalog object and detect that its parent namespace is missing, we should probably initiate its deletion?

**How to reproduce it (as minimally and precisely as possible)**:
1. Create namespace `ns1`
2. Create a `ServiceInstance` object in namespace `ns1`
3. Undeploy Service Catalog API server (you could simply set `replicas: 0` in the deployment)
4. Delete `ns1` namespace
5. Deploy Service Catalog API server
6. Namespace `ns1` is missing, but `ServiceInstance` object in this namespace still exists. In some cases, it is impossible to delete this object until you manually create `ns1` namespace again.

### PR DESCRIPTION
**Pull request by nilebox**
**What this PR does / why we need it**:
Include unavailable apiservices into `apis/` discovery endpoint response to fix namespace deletion https://github.com/kubernetes-incubator/service-catalog/issues/2254

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-incubator/service-catalog/issues/2254

**Special notes for your reviewer**:

**Release note**:

```release-note
kube-apiserver now includes all registered API groups in discovery, including registered extension API group/versions for unavailable extension API servers.
```

### CODE REVIEW

File: test/integration/examples/apiserver_test.go [hunk 1]
```diff
@@ -334,9 +337,7 @@ func TestAggregatedAPIServer(t *testing.T) {
 	// this is ugly, but sleep just a little bit so that the watch is probably observed.  Since nothing will actually be added to discovery
 	// (the service is missing), we don't have an external signal.
 	time.Sleep(100 * time.Millisecond)
-	if _, err := aggregatorDiscoveryClient.Discovery().ServerResources(); err != nil {
-		t.Fatal(err)
-	}
+	assertWardleUnavailableDiscoveryError(t, err)
```
Comment (nilebox) [inline test/integration/examples/apiserver_test.go]: The wardle API server was never available, because `Service` object is missing.
Kube-aggregator previously silently skipped unavailable API services in the `/apis` endpoint. With the new change, there is an error with details that are asserted in the `assertWardleUnavailableDiscoveryError` function.

File: test/integration/examples/apiserver_test.go [hunk 2]
```diff
@@ -334,9 +337,8 @@ func TestAggregatedAPIServer(t *testing.T) {
 	// this is ugly, but sleep just a little bit so that the watch is probably observed.  Since nothing will actually be added to discovery
 	// (the service is missing), we don't have an external signal.
 	time.Sleep(100 * time.Millisecond)
-	if _, err := aggregatorDiscoveryClient.Discovery().ServerResources(); err != nil {
-		t.Fatal(err)
-	}
+	_, err = aggregatorDiscoveryClient.Discovery().ServerResources()
+	assertWardleUnavailableDiscoveryError(t, err)
```
Comment (nilebox) [inline test/integration/examples/apiserver_test.go]: The wardle `APIService` was never available, because `Service` object is missing, which is referenced in the `APIService` object above:
```go
 			Service: &apiregistrationv1beta1.ServiceReference{
 				Namespace: "kube-wardle",
 				Name:      "api",
},
```
Kube-aggregator previously silently skipped unavailable API services in the `/apis` endpoint. With the new change, there is an error with details that are asserted in the `assertWardleUnavailableDiscoveryError` function (since `.Discovery().ServerResources()` now invokes `/apis/wardle.k8s.io/v1alpha1` endpoint that returns `503` error).

Comment (liggitt) [reply test/integration/examples/apiserver_test.go]: I think it's good to verify this error this way to make sure discovery reports it is incomplete in this case. once we verify this way, can we create the service pointing at `127.0.0.1:<wardlePort>` and make sure we get a successful discovery?

File: test/integration/examples/apiserver_test.go [hunk 3]
```diff
@@ -357,13 +359,32 @@ func TestAggregatedAPIServer(t *testing.T) {
...
-	if err != nil {
-		t.Fatal(err)
-	}
+	assertWardleUnavailableDiscoveryError(t, err)
 
 	// TODO figure out how to turn on enough of services and dns to run more
 }
 
+func assertWardleUnavailableDiscoveryError(t *testing.T, err error) {
+	if err == nil {
```
Comment (liggitt) [inline test/integration/examples/apiserver_test.go]: call `t.Helper()` to make sure failures report the line number where this was called

File: test/integration/examples/apiserver_test.go [hunk 4]
```diff
@@ -357,13 +359,32 @@ func TestAggregatedAPIServer(t *testing.T) {
 	// (the service is missing), we don't have an external signal.
 	time.Sleep(100 * time.Millisecond)
 	_, err = aggregatorDiscoveryClient.Discovery().ServerResources()
-	if err != nil {
-		t.Fatal(err)
-	}
+	assertWardleUnavailableDiscoveryError(t, err)
```
Comment (liggitt) [inline test/integration/examples/apiserver_test.go]: should be able to drop this if we create a Service object above

**Comment by liggitt** [comment]
this looks good to me, just the one comment on updating the integration test to test discovery in both failure and success cases, then squash down

File: test/integration/examples/apiserver_test.go (hunk 2 above)
Comment (liggitt) [reply test/integration/examples/apiserver_test.go]: actually, I'm not sure we have the network infrastructure here to use services

**Comment by liggitt** [comment]
this looks good to me as-is. the aggregated e2e test exercises discovery and aggregation more thoroughly. can you squash this down?

File: test/integration/examples/apiserver_test.go (hunk 2 above)
Comment (nilebox) [reply test/integration/examples/apiserver_test.go]: heh, your initial suggestion made me wonder if there was some magic trick to make such Service

**Comment by nilebox** [comment]
@liggitt awesome, will squash and then ping you.

**Comment by nilebox** [comment]
@liggitt commits squashed, please LGTM.

**Comment by nilebox** [comment]
@deads2k @lavalamp can you approve this pull request please?

**Comment by deads2k** [comment]
surprisingly painless.

/lgtm

**Comment by nilebox** [comment]
@liggitt can you cherry-pick this change to k8s 1.11 branch please? We need it to fix the issue https://github.com/kubernetes-incubator/service-catalog/issues/2254
