### PR TITLE
Wait for node authorizer graph to populate

### LINKED ISSUE #137179: [Flaking tests] k8s.io/kubernetes/test/integration/podcertificaterequests.podcertificaterequests
### Which jobs are flaking?

* [sig-release-master-blocking#integration-arm64-master](https://testgrid.k8s.io/sig-release-master-blocking#integration-arm64-master&exclude-non-failed-tests=)

### Which tests are flaking?

* [k8s.io/kubernetes/test/integration/podcertificaterequests.podcertificaterequests](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-arm64-master/2024291118509723648)

### Since when has it been flaking?

* First flaky: Fri, 06 Feb 2026 11:06:02 UTC
* Latest flaky: Sat, 21 Feb 2026 10:41:26 UTC

### Testgrid link

* [Testgrid](https://testgrid.k8s.io/sig-release-master-blocking#integration-arm64-master&exclude-non-failed-tests=)
* [Triage](https://storage.googleapis.com/k8s-triage/index.html?job=ci-kubernetes-integration-arm64-master$&test=k8s.io/kubernetes/test/integration/podcertificaterequests.podcertificaterequests)

### Reason for failure (if possible)

```
	F 2026-02-19 06:43:32 +0530 IST Failed
=== RUN   TestNodeRestriction/node1_can_create_PCR_for_pod_on_n...iting for /healthz to be ok...
--- FAIL: TestNodeRestriction (18.12s)

	F 2026-02-18 02:31:35 +0530 IST Failed
=== RUN   TestNodeRestriction/node1_can_create_PCR_for_pod_on_n...iting for /healthz to be ok...
--- FAIL: TestNodeRestriction (18.21s)

	F 2026-02-17 21:30:37 +0530 IST Failed
=== RUN   TestNodeAuthorization/node1_can_directly_get_pcr1
   ...ting for /healthz to be ok...
--- FAIL: TestNodeAuthorization (3.18s)

	F 2026-02-13 09:53:28 +0530 IST Failed
=== RUN   TestNodeRestriction/node1_can_create_PCR_for_pod_on_n...iting for /healthz to be ok...
--- FAIL: TestNodeRestriction (18.15s)

	F 2026-02-12 22:46:30 +0530 IST Failed
=== RUN   TestNodeRestriction/node1_can_create_PCR_for_pod_on_n...iting for /healthz to be ok...
--- FAIL: TestNodeRestriction (18.11s)


```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node
/kind flake
cc @kubernetes/release-team-release-signal

### PR DESCRIPTION
**Pull request by GunaKKIBM**
#### What type of PR is this?
/kind flake

Fixes #137179

The flake seen in the issue tagged, comes from [this line of code](https://github.com/kubernetes/kubernetes/blob/214ef42236333fc2152eeb0747a1e81fdbcd729d/plugin/pkg/auth/authorizer/node/node_authorizer.go#L231)

https://github.com/kubernetes/kubernetes/blob/214ef42236333fc2152eeb0747a1e81fdbcd729d/plugin/pkg/auth/authorizer/node/node_authorizer.go#L522 

Given that, the get against the PCR is being done immediately after create, the edge that needs to be established in the node authorizer graph may not be established, hence adding the timeout

### CODE REVIEW

File: test/integration/podcertificaterequests/podcertificate_integration_test.go [hunk 1]
```diff
@@ -506,7 +506,15 @@ func TestNodeAuthorization(t *testing.T) {
 	}
 
 	t.Run("node1 can directly get pcr1", func(t *testing.T) {
-		_, err := node1Client.CertificatesV1beta1().PodCertificateRequests("default").Get(ctx, "pcr1", metav1.GetOptions{})
+		// Getting the PCR could fail if there is lag in the node authorizer graph population.
+		// Poll until it succeeds.
+		err = wait.PollUntilContextTimeout(ctx, 1*time.Second, 15*time.Second, true, func(ctx context.Context) (bool, error) {
+			_, err = node1Client.CertificatesV1beta1().PodCertificateRequests("default").Get(ctx, "pcr1", metav1.GetOptions{})
+			if err != nil {
+				return false, nil
```
Comment (kishen-v) [inline test/integration/podcertificaterequests/podcertificate_integration_test.go:516]: We _may_ want to handle the error(?)

Comment (GunaKKIBM) [reply test/integration/podcertificaterequests/podcertificate_integration_test.go:516]: Yes, I updated the 4th argument passed here to false. Which basically leads to retry even if there is an error, if it is set to true, what happens is, if there is an error, it exits from the Polling immediately
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/wait/loop.go#L50

Comment (GunaKKIBM) [reply test/integration/podcertificaterequests/podcertificate_integration_test.go:516]: I have updated the error to be returned as well

File: test/integration/podcertificaterequests/podcertificate_integration_test.go [hunk 2]
```diff
@@ -494,7 +494,7 @@ func TestNodeAuthorization(t *testing.T) {
 
 	// Creating the PCR could fail if there is informer lag in the
 	// noderestriction logic.  Poll until it succeeds.
-	err = wait.PollUntilContextTimeout(ctx, 1*time.Second, 15*time.Second, true, func(ctx context.Context) (bool, error) {
```
Comment (GunaKKIBM) [inline test/integration/podcertificaterequests/podcertificate_integration_test.go:497]: When locally reproduced, I have seen the following flake, it is always good to retry even if there is an error
`   
podcertificate_integration_test.go:505: Unexpected error creating PodCertificateRequest: while retrieving pod "default/pod1" named in the PodCertificateRequest: pod "pod1" not found
    reflector.go:434: E0302 10:55:42.740287] Reflector stopped with error err="context canceled" type="*v1.Lease" reflector="pkg/controlplane/controller/apiserverleasegc/gc_controller.go:88"`

Comment (liggitt) [reply test/integration/podcertificaterequests/podcertificate_integration_test.go:497]: this change doesn't make sense to me ... there's no reason to always inject a 1-second delay

File: test/integration/podcertificaterequests/podcertificate_integration_test.go [hunk 3]
```diff
@@ -494,7 +494,7 @@ func TestNodeAuthorization(t *testing.T) {
...
+	err = wait.PollUntilContextTimeout(ctx, 1*time.Second, 15*time.Second, false, func(ctx context.Context) (bool, error) {
 		_, err = node1Client.CertificatesV1beta1().PodCertificateRequests("default").Create(ctx, pcr, metav1.CreateOptions{})
 		if err != nil {
```
Comment (liggitt) [inline test/integration/podcertificaterequests/podcertificate_integration_test.go:499]: log the error but return `false, nil` ... returning an error short-circuits the poll and exits

File: test/integration/podcertificaterequests/podcertificate_integration_test.go [hunk 4]
```diff
@@ -506,7 +506,15 @@ func TestNodeAuthorization(t *testing.T) {
 	}
 
 	t.Run("node1 can directly get pcr1", func(t *testing.T) {
-		_, err := node1Client.CertificatesV1beta1().PodCertificateRequests("default").Get(ctx, "pcr1", metav1.GetOptions{})
+		// Getting the PCR could fail if there is lag in the node authorizer graph population.
+		// Poll until it succeeds.
+		err = wait.PollUntilContextTimeout(ctx, 1*time.Second, 15*time.Second, false, func(ctx context.Context) (bool, error) {
+			_, err = node1Client.CertificatesV1beta1().PodCertificateRequests("default").Get(ctx, "pcr1", metav1.GetOptions{})
+			if err != nil {
+				return false, err
```
Comment (liggitt) [inline test/integration/podcertificaterequests/podcertificate_integration_test.go]: log the error but return `false, nil` ... returning an error short-circuits the poll and exits

File: test/integration/podcertificaterequests/podcertificate_integration_test.go (hunk 3 above)
Comment (GunaKKIBM) [reply test/integration/podcertificaterequests/podcertificate_integration_test.go:499]: If we return false, nil. we will fail to capture the error if it exists, although we may log it, ideally the expectation here seems to be that the tests should stop, if there is an error.
https://github.com/kubernetes/kubernetes/pull/137338/changes#diff-5152babce635008f11d253035944f7246f73905844c76e969d83411ab8da1d2cL504

File: test/integration/podcertificaterequests/podcertificate_integration_test.go (hunk 4 above)
Comment (GunaKKIBM) [reply test/integration/podcertificaterequests/podcertificate_integration_test.go]: Same reply as above. It's important that the error is captured. Btw, this is based on my understanding of https://github.com/kubernetes/kubernetes/blob/d3b9c54bd952117924fb0790f6989c0d30715b19/staging/src/k8s.io/apimachinery/pkg/util/wait/loop.go#L37

File: test/integration/podcertificaterequests/podcertificate_integration_test.go (hunk 2 above)
Comment (GunaKKIBM) [reply test/integration/podcertificaterequests/podcertificate_integration_test.go:497]: This test is failing because, when a Create happens, the node authorizer graph isn't updated, hence we have to wait, and in the PollUntilContextTimeout function, it returns as soon as a error is found, but ideally we want to retry creating even if there is an error the first time, because after a second or more, this call will succeed, but the PollUntilContextTimeout function doesn't provide a functionality where retry can happen even if an error is function. 


We can do two things here
- Set [immediate](https://github.com/kubernetes/kubernetes/blob/d3b9c54bd952117924fb0790f6989c0d30715b19/staging/src/k8s.io/apimachinery/pkg/util/wait/loop.go#L37) to false, to call the create function after 1 second
- Or add introduce the retry logic here itself. 
- Add a new function or optional to parameter to the PollUntilContextTimeout function itself, which enables retrying even if an error is found.

File: test/integration/podcertificaterequests/podcertificate_integration_test.go (hunk 3 above)
Comment (liggitt) [reply test/integration/podcertificaterequests/podcertificate_integration_test.go:499]: returning the error short circuits the loop and makes polling pointless

File: test/integration/podcertificaterequests/podcertificate_integration_test.go (hunk 2 above)
Comment (liggitt) [reply test/integration/podcertificaterequests/podcertificate_integration_test.go:497]: Keep the polling immediate to avoid introducing an unnecessary inevitable 1 second delay.

We can log the error if we want, but don't return it. That would surface the error in the test log, but preserves the point of the poll.

File: test/integration/podcertificaterequests/podcertificate_integration_test.go [hunk 5]
```diff
@@ -506,7 +506,15 @@ func TestNodeAuthorization(t *testing.T) {
 	}
 
 	t.Run("node1 can directly get pcr1", func(t *testing.T) {
-		_, err := node1Client.CertificatesV1beta1().PodCertificateRequests("default").Get(ctx, "pcr1", metav1.GetOptions{})
+		// Getting the PCR could fail if there is lag in the node authorizer graph population.
+		// Poll until it succeeds.
+		err = wait.PollUntilContextTimeout(ctx, 1*time.Second, 15*time.Second, false, func(ctx context.Context) (bool, error) {
```
Comment (liggitt) [inline test/integration/podcertificaterequests/podcertificate_integration_test.go]: keep the polling immediate

```suggestion
		err = wait.PollUntilContextTimeout(ctx, 1*time.Second, 15*time.Second, true, func(ctx context.Context) (bool, error) {
```

File: test/integration/podcertificaterequests/podcertificate_integration_test.go (hunk 2 above)
Comment (GunaKKIBM) [reply test/integration/podcertificaterequests/podcertificate_integration_test.go:497]: Apologies for dragging this conversation. IIUC, you are saying, we will log the error, but while failing, we will see, it failed because of timeout. But, we can debug with the logs, Am I right? 
I have updated the test considering your suggestion

File: test/integration/podcertificaterequests/podcertificate_integration_test.go [hunk 6]
```diff
@@ -506,7 +507,16 @@ func TestNodeAuthorization(t *testing.T) {
 	}
 
 	t.Run("node1 can directly get pcr1", func(t *testing.T) {
-		_, err := node1Client.CertificatesV1beta1().PodCertificateRequests("default").Get(ctx, "pcr1", metav1.GetOptions{})
+		// Getting the PCR could fail if there is lag in the node authorizer graph population.
+		// Poll until it succeeds.
+		err = wait.PollUntilContextTimeout(ctx, 1*time.Second, 15*time.Second, true, func(ctx context.Context) (bool, error) {
```
Comment (liggitt) [inline test/integration/podcertificaterequests/podcertificate_integration_test.go]:
```suggestion
		err := wait.PollUntilContextTimeout(ctx, 1*time.Second, 15*time.Second, true, func(ctx context.Context) (bool, error) {
```

File: test/integration/podcertificaterequests/podcertificate_integration_test.go [hunk 7]
```diff
@@ -506,7 +507,16 @@ func TestNodeAuthorization(t *testing.T) {
...
+			_, err = node1Client.CertificatesV1beta1().PodCertificateRequests("default").Get(ctx, "pcr1", metav1.GetOptions{})
```
Comment (liggitt) [inline test/integration/podcertificaterequests/podcertificate_integration_test.go]:
```suggestion
			_, err := node1Client.CertificatesV1beta1().PodCertificateRequests("default").Get(ctx, "pcr1", metav1.GetOptions{})
```

File: test/integration/podcertificaterequests/podcertificate_integration_test.go (hunk 2 above)
Comment (liggitt) [reply test/integration/podcertificaterequests/podcertificate_integration_test.go:497]: right
