### PR TITLE
Fixes getNestedMountpoints grouping

### LINKED ISSUE #112570: getNestedMountpoints may not group mountpoints correctly
### What happened?

``getNestedMountpoints`` [1] relies on ``sort.Strings`` to have all the mount points sorted and grouped. For example, the following strings are sorted in this exact order:

```
/dir/nested, /dir/nested-vol, /dir/nested.vol, /dir/nested/double, /dir/nested2
```

With the current implementation, ``getNestedMountpoints``, an incorrect set of nested directories would be returned. For example, if we add the ``nested-vol`` and ``nested.vol`` volume mounts into the ``TestGetNestedMountpoints/Unsorted Nested Pod`` test, we would get:

```
=== RUN   TestGetNestedMountpoints
    nested_volumes_test.go:232: Unsorted Nested Pod: unexpected nested directories created:
        expected: map[nested:{} nested-vol:{} nested.vol:{} nested2:{}]
             got: map[nested:{} nested-vol:{} nested.vol:{} nested/double:{} nested2:{}]
--- FAIL: TestGetNestedMountpoints (0.00s)
```

This is worse on Windows, where paths usually have backslashes instead (with no test changes):

```
=== RUN   TestGetNestedMountpoints
    nested_volumes_test.go:230: Unsorted Nested Pod: unexpected nested directories created:
        expected: map[nested:{} nested2:{}]
             got: map[nested:{} nested2:{} nested\double:{}]
--- FAIL: TestGetNestedMountpoints (0.02s)
```

[1] https://github.com/kubernetes/kubernetes/blob/64a38b165eceaf02d64cfb4605a95b66812b03bc/pkg/volume/util/nested_volumes.go#L33

// The previously found nested mountpoints.
// NOTE: We can't simply rely on sort.Strings to have all the mountpoints sorted and
// grouped. For example, the following strings are sorted in this exact order:

// The issue is a bit worse for Windows paths, since the \'s value is higher than /'s:
// \dir\nested, \dir\nested vol, \dir\nested-vol, \dir\nested\double, \dir\nested2
// Because of this, we should use a list of previously mounted mountpoints, rather than only one.

### What did you expect to happen?

``getNestedMountpoints`` should group mount points correctly.

### How can we reproduce it (as minimally and precisely as possible)?

```
git diff pkg/
diff --git a/pkg/volume/util/nested_volumes_test.go b/pkg/volume/util/nested_volumes_test.go
index f4f4add..e73730c 100644
--- a/pkg/volume/util/nested_volumes_test.go
+++ b/pkg/volume/util/nested_volumes_test.go
@@ -89,7 +89,7 @@ func TestGetNestedMountpoints(t *testing.T) {
                {
                        name:     "Unsorted Nested Pod",
                        err:      false,
-                       expected: sets.NewString("nested", "nested2"),
+                       expected: sets.NewString("nested", "nested2", "nested-vol", "nested.vol"),
                        volname:  "vol1",
                        pod: v1.Pod{
                                ObjectMeta: metav1.ObjectMeta{
@@ -106,6 +106,8 @@ func TestGetNestedMountpoints(t *testing.T) {
                                                                {MountPath: "/ignore2", Name: "vol5"},
                                                                {MountPath: "/dir", Name: "vol1"},
                                                                {MountPath: "/dir/nested2", Name: "vol3"},
+                                                               {MountPath: "/dir/nested-vol", Name: "vol6"},
+                                                               {MountPath: "/dir/nested.vol", Name: "vol7"},
                                                        },
                                                },
                                        },

```

### Anything else we need to know?

/kind bug

/sig windows

### Kubernetes version

Kubernetes master, Kubernetes v1.25 and older.

### Cloud provider

N/A

### OS version

N/A

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by claudiubelu**
#### What type of PR is this?

/kind bug
/sig windows

/priority important-soon

#### What this PR does / why we need it:

Currently, ``getNestedMountpoints`` sorts using ``sort.Strings``, which would sort the following strings in this exact order:

```
/dir/nested, /dir/nested-vol, /dir/nested.vol, /dir/nested/double, /dir/nested2
```

Because of this, ``nested/double`` is returned as well, even though it shouldn't have been. This issue is worse on Windows, where the path separator is typically the backslash.

This commit addresses this issue by checking if a nested mount point has been previously seen or not.

#### Which issue(s) this PR fixes:

Fixes #112570
Related: https://github.com/kubernetes/kubernetes/issues/51540

#### Does this PR introduce a user-facing change?

```release-note
Nested mountpoints are now group correctly on all cases.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by marosset** [comment]
@claudiubelu - can you add a release note? This can change behaviors for users.

**Comment by HeshamAboElMagd** [comment]
Hello @saad-ali ,  @claudiubelu . Release bug triage team here, just wanted to touch base with you for updates on this ticket.
Thanks!

File: pkg/volume/util/nested_volumes.go [hunk 1]
```diff
@@ -51,8 +51,14 @@ func getNestedMountpoints(name, baseDir string, pod v1.Pod) ([]string, error) {
...
+			// NOTE: We can't simply rely on sort.Strings to have all the mountpoints sorted and
+			// grouped. For example, the following strings are sorted in this exact order:
+			// /dir/nested, /dir/nested-vol, /dir/nested.vol, /dir/nested/double, /dir/nested2
+			// The issue is a bit worse for Windows paths, since the \'s value is higher than /'s:
+			// \dir\nested, \dir\nested-vol, \dir\nested.vol \dir\nested\double, \dir\nested2
+			// Because of this, we should use a list of previously mounted mountpoints, rather than only one.
+			prevNestedMPs := []string{}
 			// examine each mount point to see if it's nested beneath this volume
 			// (but skip any that are double-nested beneath this volume)
 			// For example, if this volume is mounted as /dir and other volumes are mounted
```
Comment (msau42) [inline pkg/volume/util/nested_volumes.go:64]: @joelsmith @jsafrane @sjenning  do you remember why we have this special case for double nested where we don't use the full path?

I thought it could have been related to supporting mounting a configmap/secret as file, but it doesn't seem like that's supported: https://github.com/kubernetes/kubernetes/issues/61545

File: pkg/volume/util/nested_volumes_test.go [hunk 2]
```diff
@@ -89,7 +89,7 @@ func TestGetNestedMountpoints(t *testing.T) {
 		{
```
Comment (msau42) [inline pkg/volume/util/nested_volumes_test.go:89]: This isn't related to your change, but can you add a test case for triple nested volumes?

File: pkg/volume/util/nested_volumes.go [hunk 3]
```diff
@@ -51,8 +51,14 @@ func getNestedMountpoints(name, baseDir string, pod v1.Pod) ([]string, error) {
 				return fmt.Errorf("invalid container mount point %v", myMountPoint)
 			}
 			myMPSlash := myMountPoint + string(os.PathSeparator)
-			// The previously found nested mountpoint (or "" if none found yet)
-			prevNestedMP := ""
+			// The previously found nested mountpoints.
+			// NOTE: We can't simply rely on sort.Strings to have all the mountpoints sorted and
```
[the remark this answers is not in the document]
Comment (claudiubelu) [reply pkg/volume/util/nested_volumes.go:55]: They're still sorted (L45), but now we're checking at L71-77 if that directory was seen already.

For example, let's say we have ``\dir\nested\foo``, ``\dir\nested2``, ``\dir\nested``. This will be sorted to ``\dir\nested``, ``\dir\nested2``, ``\dir\nested\foo``. Being the first one, ``\dir\nested`` is added to ``retval``. The second one, doesn't match any previous mountpoint (``\dir\nested2`` doesn't have the  ``\dir\nested\`` prefix), it is then added to ``retval``. FInally, ``\dir\nested\foo`` has the prefix ``\dir\nested\``, so it's skipped.

The sort is still useful, it still makes sure that ``\dir\nested\foo`` is sorted after ``\dir\nested``, which will mean that ``\dir\nested\foo`` will be treated as an already seen mountpoint.
