### PR TITLE
Fix kubectl timeout test flake in e2e/portforward

### LINKED ISSUE #20570: e2e flake: Port forwarding — kubectl timed out
From kubernetes-pull-build-test-e2e-gce run number 26528 (which ran against a documentation-only change):

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/portforward.go:156
Feb  3 18:41:38.226: kubectl timed out
```

### PR DESCRIPTION
**Pull request by ncdc**
Instead of using `kubectl logs -f` and waiting for it to terminate when the container/pod stopped,
switch to explicitly waiting for the pod to stop and then get the pod logs without -f to avoid
hanging.

Fixes #20570 #21332

cc @lavalamp @bprashanth

### CODE REVIEW

**Comment by ncdc** [comment]
I have run this in several continuous loops looking for flakes. I do hit some locally, but the "kubectl timed out" issue is now gone.

The flakes I am now seeing appear to be related to some strange issue where it appears that the infra container for the pftest pod doesn't get assigned an IP address. I'm seeing this with Docker 1.9.1 on Fedora 23. I'm hoping that this is just something specific to my F23 VM...

FWIW, here's what I see for a successful test in the Docker log:

```
docker[15523]: time="2016-02-19T16:37:28.335573525-05:00" level=debug msg="POST /containers/create?name=k8s_POD.6059dfa2_pfpod_e2e-tests-port-forwarding-n36vo_f9358df4-d750-11e5-8cb3-001c42de2c3c_cf6c88c3"
... [snip] ...
docker[15523]: time="2016-02-19T16:37:28.547158181-05:00" level=debug msg="Assigning addresses for endpoint k8s_POD.6059dfa2_pfpod_e2e-tests-port-forwarding-n36vo_f9358df4-d750-11e5-8cb3-001c42de2c3c_cf6c88c3's interface on network bridge"
... [snip] ...
docker[15523]: time="2016-02-19T16:37:28.640274089-05:00" level=debug msg="POST /containers/create?name=k8s_portforwardtester.eda5a681_pfpod_e2e-tests-port-forwarding-n36vo_f9358df4-d750-11e5-8cb3-001c42de2c3c_4ca4a810"
```

Also interesting about my local failure is that I don't see the log message about creating the portforwardtester container. It does get created, it starts, and it stops, but the log entries are missing. I don't know if journald is dropping messages or what's going on, but it is super strange.

File: test/e2e/portforward.go [hunk 1]
```diff
@@ -195,7 +187,16 @@ var _ = Describe("Port forwarding", func() {
 				Failf("Expected %q from server, got %q", e, a)
 			}
 
-			logOutput := runKubectlWithTimeout(wait.ForeverTestTimeout, "logs", fmt.Sprintf("--namespace=%v", framework.Namespace.Name), "-f", podName)
+			By("Waiting for the target pod to stop running")
+			framework.WaitForPodNoLongerRunning(pod.Name)
+
+			By("Retrieving logs from the target pod")
+			logOutput, err := getPodLogs(framework.Client, framework.Namespace.Name, pod.Name, "portforwardtester")
```
Comment (lavalamp) [inline test/e2e/portforward.go]: Does getPodLogs shell out to kubectl? That's the point of this test...

Comment (ncdc) [inline test/e2e/portforward.go]: No, it doesn't, but the point of these tests is to test that `kubectl port-forward` works. I don't think how the logs are retrieved really matters... do you?

**Comment by ncdc** [comment]
Re my "weird" flakes, I added removing all containers to each test iteration, and it's run with no errors for just over an hour. I'm thinking maybe I ran out of available IP addresses.

**Comment by lavalamp** [comment]
lgtm

**Comment by davidopp** [comment]
Removed LGTM label so @ncdc can incorporate #21650 into this PR.

**Comment by davidopp** [comment]
@ncdc please ping when you've updated te PR

**Comment by ncdc** [comment]
@davidopp @lavalamp ping :smile:

**Comment by davidopp** [comment]
LGTM

**Comment by lavalamp** [comment]
@k8s-oncall Please merge this manually
