### PR TITLE
kubelet: don't GC containers of deleted pods until all sources are ready

### LINKED ISSUE #27095: Restarting Kubelet restarts Successful Pods
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gce-serial/1453/

Failed: [k8s.io] SchedulerPredicates [Serial] validates MaxPods limit number of pods that are allowed to run [Slow] {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:282
Not scheduled Pods: []api.Pod(nil)
Expected
    <int>: 0
to equal
    <int>: 1
```

### PR DESCRIPTION
**Pull request by yujuhong**
Otherwise, kubelet may mistaken a pod being deleted and remove all its
containers, leading to potentially incorrect interpretation of the restart
policy (since kubelet sometimes relies on exited containers as checkpoints)

This fixes #27095

### CODE REVIEW

**Comment by yujuhong** [comment]
I don't like adding more dependencies between components. Suggestions are welcome.

**Comment by Random-Liu** [comment]
It seems that it won't be too hard to move `StartGarbageCollection` into kubelet.Run.
Just call `StartGarbageCollection` into kubelet.Run(), and add a new layer of starter goroutine checking source periodically and start garbage collector when all sources are ready. The change should also be minor.

**Comment by yujuhong** [comment]
Alternative solution:
```
func (kl *Kubelet) StartGarbageCollection() {
        go wait.Until(func() {
                if kl.sourcesReady.AllReady() {
                        if err := kl.containerGC.GarbageCollect(); err != nil {
                                glog.Errorf("Container garbage collection failed: %v", err)
                        }
                }
        }, ContainerGCPeriod, wait.NeverStop)

        go wait.Until(func() {
                if err := kl.imageManager.GarbageCollect(); err != nil {
                        glog.Errorf("Image garbage collection failed: %v", err)
                }
        }, ImageGCPeriod, wait.NeverStop)
}
```
Pros: 2-line change
Cons: This blocks the entire container garbage collection until all sources are ready.

Another option is to pass a new argument to indicate whether the sources area ready:
```
                        if err := kl.containerGC.GarbageCollect(kl.sourcesReady.AllReady()); err != nil {
                                glog.Errorf("Container garbage collection failed: %v", err)
                        }
```
Pros: GC functions partially even when not all sources are ready
Cons: unclean container runtime interface.

**Comment by Random-Liu** [comment]
Vote for option 2, which is cleaner than current PR and still support garbage collect before all sources are ready.

**Comment by Random-Liu** [comment]
@yujuhong Have you decided to go with option 1? If so, LGTM.

**Comment by yujuhong** [comment]
Let's go with option 2

File: pkg/kubelet/container/container_gc.go [hunk 1]
```diff
@@ -39,7 +39,7 @@ type ContainerGCPolicy struct {
 // Implementation is thread-compatible.
 type ContainerGC interface {
 	// Garbage collect containers.
-	GarbageCollect() error
+	GarbageCollect(allSourcesReady bool) error
```
Comment (ronnielai) [inline pkg/kubelet/container/container_gc.go]: Using boolean parameters in a public method is generally frowned upon. Just my 2 cents.

Comment (Random-Liu) [inline pkg/kubelet/container/container_gc.go]: @ronnielai This is just a quick fix for this. :)
This is definitely not what we want, but we are in code freeze, we've to fix it with as few code as possible. :)

Comment (yujuhong) [inline pkg/kubelet/container/container_gc.go]: We don't want to refactor the code extensively due to reason that @Random-Liu said. Making this part of the ContainerGCPolicy is even uncleaner, since the state changes dynamically (at least during kubelet startup).

**Comment by Random-Liu** [comment]
@yujuhong 
```
FAIL	k8s.io/kubernetes/pkg/kubelet/rkt [build failed]
```

**Comment by Random-Liu** [comment]
This time it's docker:
```
FAIL	k8s.io/kubernetes/pkg/kubelet/dockertools [build failed]
```

**Comment by yujuhong** [comment]
Oops....sorry. I expected the log to show me all the failures, but it didn't. Ran the unit test locally and passed.

File: pkg/kubelet/container/container_gc.go (hunk 1 above)
Comment (Random-Liu) [inline pkg/kubelet/container/container_gc.go]: @yujuhong Can we add a few comments here to explain why we add this and when are we going to remove it? Or link an issue.

**Comment by Random-Liu** [comment]
LGTM with a nit.

**Comment by yujuhong** [comment]
Done.

**Comment by Random-Liu** [comment]
@yujuhong Maybe we need some labels to mark this should be backported in v1.2?

**Comment by yujuhong** [comment]
@dchen1107, do we still accept cherry picks in v1.2?

**Comment by dchen1107** [comment]
We still accept the cherry picks in v1.2, but I don't think we need to cherrypick the fix for this particular issue since the issue only affects static pods with RestartPolicy:never.

**Comment by yifan-gu** [comment]
rkt changes LGTM

**Comment by lavalamp** [comment]
manual build cop merge
