### PR TITLE
fix comment alignment

### LINKED ISSUE #39215: append errors while releasing and adopting pods and replicasets during gc
pkg/controller/deployment/deployment_controller.go
pkg/controller/replicaset/replicaset.go

As part of PR https://github.com/kubernetes/kubernetes/pull/35676 , we found some issues that need to be fixed:-
- fix some formatting issues in the comments
- append errors when releasing and adopting both pods and replicasets

### PR DESCRIPTION
**Pull request by krmayankk**
fixes https://github.com/kubernetes/kubernetes/issues/39215

cc  @kargakis  @caesarxuchao

### CODE REVIEW

File: pkg/controller/deployment/deployment_controller.go [hunk 1]
```diff
@@ -465,13 +467,13 @@ func (dc *DeploymentController) classifyReplicaSets(deployment *extensions.Deplo
 				if !errors.IsNotFound(err) {
 					utilruntime.HandleError(err)
 				}
+				errlist = append(errlist, err)
```
Comment (kargakis) [inline pkg/controller/deployment/deployment_controller.go]: I think we should ignore 404 so move this in the if above. Same for pods.

**Comment by krmayankk** [comment]
@kargakis i fixed that part but the unit tests are still failing for replica_set controller. Will debug this further.

File: pkg/controller/deployment/deployment_controller.go [hunk 2]
```diff
@@ -464,14 +466,14 @@ func (dc *DeploymentController) classifyReplicaSets(deployment *extensions.Deplo
 				// If the RS no longer exists, don't even log the error.
 				if !errors.IsNotFound(err) {
 					utilruntime.HandleError(err)
```
Comment (kargakis) [inline pkg/controller/deployment/deployment_controller.go]: We can probably also remove this HandleError since the aggregate error will be logged or passed to HandleError if the deployment is about to be dropped out of the queue (see `func (dc *DeploymentController) handleErr(err error, key interface{})`)

File: pkg/controller/replicaset/replica_set.go [hunk 3]
```diff
@@ -599,6 +599,7 @@ func (rsc *ReplicaSetController) syncReplicaSet(key string) error {
 		cm := controller.NewPodControllerRefManager(rsc.podControl, rs.ObjectMeta, selector, getRSKind())
 		matchesAndControlled, matchesNeedsController, controlledDoesNotMatch := cm.Classify(pods)
 		// Adopt pods only if this replica set is not going to be deleted.
+		var errlist []error
```
Comment (kargakis) [inline pkg/controller/replicaset/replica_set.go]: Probably need to do this for the replication controller manager too

**Comment by kargakis** [comment]
@krmayankk ping

**Comment by krmayankk** [comment]
@kargakis sorry will address this this weekend

**Comment by krmayankk** [comment]
@kargakis this change is causing unit test for replica_set to fail
```
E0129 01:29:34.587205   35088 util.go:45] Metric for replicaset_controller already registered
--- FAIL: TestPatchPodFails (0.00s)
	replica_set_test.go:181: Unexpected number of creates.  Expected 2, saw 0
```
Need to debug this more

**Comment by kargakis** [comment]
> @kargakis this change is causing unit test for replica_set to fail

Hm, it seems that errors are deliberately ignored during adoption so that replica sets can continue and create new pods. It is probably fine to continue ignoring. @caesarxuchao thoughts?

**Comment by caesarxuchao** [comment]
I think continue ignoring adoption failure is ok. Adoption failure is not a hard failure, so RS should continue to create new pods.

**Comment by krmayankk** [comment]
@kargakis @caesarxuchao sounds good. then the only change in this PR will be aligning comments. I will change that. We should at least log the errors for adoption, or does HandleError already does that ?

**Comment by caesarxuchao** [comment]
> does HandleError already does that ?

I think so.

**Comment by krmayankk** [comment]
@kargakis please approve the minor comment alignment

File: pkg/controller/deployment/deployment_controller.go [hunk 4]
```diff
@@ -460,6 +460,8 @@ func (dc *DeploymentController) classifyReplicaSets(deployment *extensions.Deplo
 	}
 	cm := controller.NewReplicaSetControllerRefManager(dc.rsControl, deployment.ObjectMeta, deploymentSelector, getDeploymentKind())
 	matchesAndControlled, matchesNeedsController, controlledDoesNotMatch := cm.Classify(rsList)
+
+	var errlist []error
```
Comment (kargakis) [inline pkg/controller/deployment/deployment_controller.go]: This move is not necessary anymore.

**Comment by krmayankk** [comment]
@kargakis removed the unncessary move

**Comment by krmayankk** [comment]
@k8s-bot unit test this

**Comment by krmayankk** [comment]
@k8s-bot cvm gce e2e test this

**Comment by caesarxuchao** [comment]
My /approve is not effective. @madhusudancs could you help approve it, since the robot suggest you as the approver.
