### PR TITLE
Fix code coverage in build script on OS X.

### LINKED ISSUE #20223: KUBE_COVER=y doesn't work on Mac
Haven't had time to debug, but just recording here.

```
$ KUBE_COVER=y hack/test-go.sh pkg/api/meta
Running tests for APIVersion: v1,extensions/v1beta1,metrics/v1alpha1 with etcdPrefix: registry
+++ [0127 13:50:24] Saving coverage output in '/tmp/k8s_coverage/v1,extensions/v1beta1,metrics/v1alpha1/20160127-135024'
bash: -c: line 0: unexpected EOF while looking for matching `"'
bash: -c: line 1: syntax error: unexpected end of file
+++ [0127 13:50:24] Combined coverage report: /tmp/k8s_coverage/v1,extensions/v1beta1,metrics/v1alpha1/20160127-135024/combined-coverage.html
!!! Error in hack/test-go.sh:333
  'return ${test_result}' exited with status 1
Call stack:
  1: hack/test-go.sh:333 main(...)
Exiting with status 1
```

### PR DESCRIPTION
**Pull request by ConnorDoyle**
Fixes #20223

- Fixes code coverage in build script on BSD systems (including OS X).
- Supersedes #38536.

Successfully tested on two platforms:

```
Darwin <hostname> 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
```

```
Linux <hostname> 4.4.14-040414-generic #201606241434 SMP Fri Jun 24 18:36:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

cc @ixdy @mfanjie @balajismaniam @smarterclayton @soltysh

**Release note**:
```release-note
```

### CODE REVIEW

**Comment by ConnorDoyle** [comment]
@k8s-bot cri e2e test this

**Comment by ConnorDoyle** [comment]
@k8s-bot cri e2e test this

**Comment by ConnorDoyle** [comment]
@k8s-bot cri e2e test this

**Comment by ConnorDoyle** [comment]
Hit this flake issue in the cri e2e tests: https://github.com/kubernetes/kubernetes/issues/38556

**Comment by ConnorDoyle** [comment]
@k8s-bot cri e2e test this

File: hack/make-rules/test.sh [hunk 1]
```diff
@@ -263,6 +265,7 @@ runTests() {
           ${testargs[@]:+${testargs[@]}} \
         | tee ${junit_filename_prefix:+\"${junit_filename_prefix}-\$_pkg_out.stdout\"} \
         | grep \"${go_test_grep_pattern}\"" \
+          {} \
```
Comment (spiffxp) [inline hack/make-rules/test.sh]: the indentation here is misleading, any chance you can pull this back to make it clearer it's an arg to the wrapping `bash -c` instead of the final `grep`?

Comment (ConnorDoyle) [inline hack/make-rules/test.sh]: Sure, do you mean just to align it with the `|` character on the previous two lines?

Comment (ConnorDoyle) [inline hack/make-rules/test.sh]: or align with `bash` above?

Comment (ConnorDoyle) [inline hack/make-rules/test.sh]: There's also a mix of 2 and 4 space indentations going on here and elsewhere in the file. Which is the preferred style?

**Comment by ConnorDoyle** [comment]
@k8s-bot cri e2e test this

File: hack/make-rules/test.sh (hunk 1 above)
Comment (spiffxp) [inline hack/make-rules/test.sh]: I would defer to @ixdy for full bash style, but probably 2 spaces under bash, since it's a continuation of that command

Comment (ConnorDoyle) [inline hack/make-rules/test.sh]: Updated indentation

**Comment by ConnorDoyle** [comment]
NB: diff is a little larger now that it cleans up surrounding irregular indentation.

**Comment by ixdy** [comment]
/lgtm
Nice. This is a much cleaner fix than the one I'd originally written.

**Comment by thockin** [comment]
This broke `make test WHAT=local/path` - you use pkg, but it needs to be
prefixed with ${KUBE_GO_PACKAGE}

**Comment by ixdy** [comment]
@thockin are you running in coverage mode? this should only have affected the coverage codepath.

**Comment by ixdy** [comment]
also it's still using `${KUBE_GO_PACKAGE}`, as it had been previously.

**Comment by thockin** [comment]
hmm, it might be the OTHER PR that changed this file then.  I missed that
this was coverage mode...
