### PR TITLE
scheduler_perf: Add memory tracking to performance tests

### LINKED ISSUE #132306: scheduler_perf: Add Memory Tracking to Detect Memory Leaks
## What type of Issue is this?

/kind feature
/sig scheduling

## What this Issue does / why we need it:

This issue proposes adding memory tracking capabilities to `scheduler_perf` to detect memory leaks and regressions before they reach production.

### Background

The Kubernetes scheduler has experienced critical memory leaks in production:

- **#120622**: QHint inFlightPods memory leak
- **#111773**: Preemption strategy memory leak
- **#83895**: Work queue timer memory leak
- And your custom scheduler plugins?

These issues were discovered only after deployment to production, causing a significant operational impact. The variety of root causes (watch operations, preemption logic, queue timers, map cleanup) demonstrates the need for systematic memory tracking.

### Proposed Solution

Add memory tracking to `scheduler_perf` that monitors:

- **HeapMemoryInUse**: Current heap memory usage (MB)
- **GoroutineCount**: Number of active goroutines
- **MemoryGrowthRate**: Rate of memory increase (MB/min)

Frankly, what to monitor is debatable. I welcome your opinion.

PoC is https://github.com/utam0k/kubernetes/tree/scheduler-perf-memory/test/integration/scheduler_perf/memory/demo, and confirm PoC can detect #120622 case.

Here is the summary by PoC:

- **Workload**: 150,000 pods
- **Duration**: ~1.5 minutes

| Metric                     | Baseline    | Memory Leak | Difference         |
| -------------------------- | ----------- | ----------- | ------------------ |
| HeapMemoryInUse (Average)  | 4418 MB     | 4941 MB     | +523 MB (+11.8%)   |
| HeapMemoryInUse (Max)      | 6626 MB     | 7770 MB     | +1144 MB (+17.3%)  |
| MemoryGrowthRate           | 1946 MB/min | 2801 MB/min | +855 MB/min (+44%) |
| GoroutineCount (Average)   | 2,475       | 2,483       | +8 (+0.3%)         |
| GoroutineCount (Max)       | 3,015       | 3,221       | +206 (+6.8%)       |

### PR DESCRIPTION
**Pull request by utam0k**
#### What type of PR is this?

 
/kind feature
/sig scheduling

#### What this PR does / why we need it:

This PR adds memory tracking functionality to the scheduler performance tests to help detect memory leaks and monitor memory usage patterns during performance benchmarks.

#### Which issue(s) this PR is related to:

Fixes #132306
ref: https://github.com/kubernetes/kubernetes/pull/132523

#### Does this PR introduce a user-facing change?

```release-note
Add memory tracking to scheduler performance tests to help detect memory leaks and monitor memory usage patterns while running scheduler_perf
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by utam0k** [comment]
This is the example output.
https://gist.github.com/utam0k/82f9a989a07c49ac3bf33b34da68b202

File: test/integration/scheduler_perf/scheduler_perf.go [hunk 1]
```diff
@@ -1461,6 +1461,13 @@ func stopCollectingMetrics(tCtx ktesting.TContext, collectorCtx ktesting.TContex
...
 		return nil, fmt.Errorf("missing startCollectingMetrics operation before stopping")
 	}
+
+	for _, collector := range collectors {
+		if err := collector.stop(); err != nil {
+			tCtx.Errorf("op %d: failed to stop collector %T: %v", opIndex, collector, err)
+		}
+	}
+
 	collectorCtx.Cancel("collecting metrics, collector must stop first")
```
Comment (macsko) [inline test/integration/scheduler_perf/scheduler_perf.go]: The is a `collectorCtx.Cancel` which should force the runners termination. There is no need to add a `stop()` method.

File: test/integration/scheduler_perf/util.go [hunk 2]
```diff
@@ -640,3 +649,151 @@ func (tc *throughputCollector) collect() []DataItem {
...
+		resultLabels: resultLabels,
+		interval:     interval,
+		stopCh:       make(chan struct{}),
+	}
+}
+
+func (mc *memoryCollector) init() error {
+	mc.samples = nil
+	return nil
+}
```
Comment (macsko) [inline test/integration/scheduler_perf/util.go]: There is no need to reset the samples. The new `memoryCollector` instance is created each time.
```suggestion
func (mc *memoryCollector) init() error {
	return nil
}
```

File: test/integration/scheduler_perf/util.go [hunk 3]
```diff
@@ -640,3 +649,151 @@ func (tc *throughputCollector) collect() []DataItem {
...
+	return dataItems
+}
+
+func copyLabels(labels map[string]string) map[string]string {
+	copied := make(map[string]string, len(labels))
+	for k, v := range labels {
+		copied[k] = v
+	}
+	return copied
+}
```
Comment (macsko) [inline test/integration/scheduler_perf/util.go]: You can just use `maps.Clone()`

File: test/integration/scheduler_perf/util.go [hunk 4]
```diff
@@ -640,3 +649,151 @@ func (tc *throughputCollector) collect() []DataItem {
...
+				"Perc99":  item.values[int(math.Ceil(float64(len(item.values)*99)/100))-1],
+				"Average": sum / float64(len(item.values)),
+				"Max":     item.values[len(item.values)-1],
+			},
+			Unit: item.unit,
+		}
+		heapItem.Labels["Metric"] = item.metric
+
+		dataItems = append(dataItems, heapItem)
+	}
```
Comment (macsko) [inline test/integration/scheduler_perf/util.go]: The logic here is really scrambled. Could you refactor it somehow? Maybe expose body of the loop to a function and simply call it twice?

File: test/integration/scheduler_perf/util.go [hunk 5]
```diff
@@ -640,3 +649,151 @@ func (tc *throughputCollector) collect() []DataItem {
...
+
+	firstSample := mc.samples[0]
+	var lastSample memorySample
+	if length < 2 {
+		lastSample = firstSample
+	} else {
+		lastSample = mc.samples[length-1]
+	}
```
Comment (macsko) [inline test/integration/scheduler_perf/util.go]:
```suggestion
	lastSample := firstSample
	if length >= 2 {
		lastSample = mc.samples[length-1]
	}
```

File: test/integration/scheduler_perf/util.go [hunk 6]
```diff
@@ -640,3 +649,151 @@ func (tc *throughputCollector) collect() []DataItem {
...
+	growthItem := DataItem{
+		Labels: copyLabels(mc.resultLabels),
+		Data: map[string]float64{
+			"DurationSec": durationSec,
+			"InitialMB":   firstSample.heapInuseMB,
+			"FinalMB":     lastSample.heapInuseMB,
+		},
+		Unit: "MB/min",
+	}
+	growthItem.Labels["Metric"] = "memory_growth_rate"
```
Comment (macsko) [inline test/integration/scheduler_perf/util.go]: I don't understand this part. This just returns the initial, final and duration and doesn't show any rate.

File: test/integration/scheduler_perf/util.go [hunk 7]
```diff
@@ -640,3 +642,130 @@ func (tc *throughputCollector) collect() []DataItem {
...
+	goroutineValues := make([]float64, len(mc.samples))
+
+	for i, s := range mc.samples {
+		heapValues[i] = s.heapInuseMB
+		goroutineValues[i] = s.goroutineCount
+	}
+
+	dataItems := []DataItem{
+		mc.createMetricDataItem(heapValues, "MB", "heap_memory_usage"),
+		mc.createMetricDataItem(goroutineValues, "count", "goroutine_count"),
```
Comment (sanposhiho) [inline test/integration/scheduler_perf/util.go]: we already have goroutine leak detection in scheduler-perf?

Comment (sanposhiho) [reply test/integration/scheduler_perf/util.go]: https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler_perf/scheduler_perf.go#L1078-L1085

**Comment by sanposhiho** [comment]
Should we somehow implement it in the test framework side? like a goroutine leak detection.
https://github.com/kubernetes/kubernetes/blob/master/test/integration/framework/

cc @pohly

File: test/integration/scheduler_perf/util.go [hunk 8]
```diff
@@ -640,3 +642,130 @@ func (tc *throughputCollector) collect() []DataItem {
...
+	growthRateMBPerMin := 0.0
+	if durationMin > 0 {
+		growthRateMBPerMin = (lastSample.heapInuseMB - firstSample.heapInuseMB) / durationMin
+	}
+	growthItem := DataItem{
+		Labels: maps.Clone(mc.resultLabels),
+		Data: map[string]float64{
+			"GrowthRate": growthRateMBPerMin,
+		},
+		Unit: "MB/min",
```
Comment (sanposhiho) [inline test/integration/scheduler_perf/util.go:748]: should it be `/sec`? I'm not sure if all tests are running for a long enough time

File: test/integration/scheduler_perf/util.go [hunk 9]
```diff
@@ -640,3 +642,130 @@ func (tc *throughputCollector) collect() []DataItem {
...
+	return nil
+}
+
+func (mc *memoryCollector) run(tCtx ktesting.TContext) {
+	ticker := time.NewTicker(mc.interval)
+	defer ticker.Stop()
+
+	// Take initial sample
+	mc.collectSample()
+
```
Comment (sanposhiho) [inline test/integration/scheduler_perf/util.go]: nit: move to init()? (I know equivalent though

**Comment by pohly** [comment]
> Should we somehow implement it in the test framework side? like a goroutine leak detection.

I'm not aware of any other integration test which records metrics, so no?

File: test/integration/scheduler_perf/util.go (hunk 7 above)
Comment (utam0k) [reply test/integration/scheduler_perf/util.go]: I had forgotten about that. However, this is still worth it. Knowing the max of a running goroutine is important for more than just detecting leaks. Also, this detection apparently only checks the final state.

File: test/integration/scheduler_perf/util.go (hunk 8 above)
Comment (utam0k) [reply test/integration/scheduler_perf/util.go:748]: To be honest, I'm not sure... Well, I can convert seconds to minutes, and I'll use sec.

**Comment by sanposhiho** [comment]
> I'm not aware of any other integration test which records metrics, so no?

I was imagining, instead of metrics, just checking the initial -> final memory and detecting the memory leak. 
... but, on second thought, it looks difficult to determine a general threshold at which increased memory usage is considered a memory leak. So, yup, having it only in scheduler-perf and just record the memory usage as metrics might be the best for now

File: test/integration/scheduler_perf/util.go (hunk 7 above)
Comment (sanposhiho) [reply test/integration/scheduler_perf/util.go]: Do we really care about the max of running goroutines at the moment? There's many places running goroutines. Also, note that your code is tracking the whole goroutines, not only scheduler, but also for kube-apiserver etc because we run all in a single process. So, I probably wouldn't find it worthy, honestly.

Comment (sanposhiho) [reply test/integration/scheduler_perf/util.go]: like in your example output, it says 2312, but we cannot say it's too big or ok, right? And, say it's increased to 2500 after some change in the scheduler, it'd be difficult to say that increase is bad or not anyway.

Keep looking at the scheduler throughput and memory usage, while making sure there's no goroutine leak at least sounds like a good balance to me. 
To take it to the extreme, as long as the scheduler's throughput is ok and the memory usage isn't jumping too much, it should be ok to have too many goroutines, if that makes sense.  ...Yes, I know it's too extreme way to consider it though.

Comment (utam0k) [reply test/integration/scheduler_perf/util.go]: > Yes, I know it's too extreme way to consider it though.

Good point. You're right. I reconsidered, too. Let's turn it off.

Comment (utam0k) [reply test/integration/scheduler_perf/util.go]: @sanposhiho Updated. PTAL

Comment (sanposhiho) [reply test/integration/scheduler_perf/util.go]: I think you forgot pushing the commit

Comment (utam0k) [reply test/integration/scheduler_perf/util.go]: 🤦
Pushed

Comment (sanposhiho) [reply test/integration/scheduler_perf/util.go]: You mistakenly removed memory_growth_rate, not goroutine_count here?

https://github.com/kubernetes/kubernetes/compare/f0201ed15055465e318e16f0cfd92caa36c6536c..6acdd7ac50f8ce577002a2add5d75931a4ef4a94

File: test/integration/scheduler_perf/util.go [hunk 10]
```diff
@@ -640,3 +642,122 @@ func (tc *throughputCollector) collect() []DataItem {
...
+	samples      []memorySample
+	resultLabels map[string]string
+	interval     time.Duration
+	mu           sync.RWMutex
+}
+
+type memorySample struct {
+	timestamp      time.Time
+	heapInuseMB    float64
+	goroutineCount float64
```
Comment (sanposhiho) [inline test/integration/scheduler_perf/util.go]: no need anymore

**Review by sanposhiho — APPROVED** [review]
/lgtm
/approve

thanks!
