### PR TITLE
Switch to instance-level update APIs for Azure VMSS loadbalancer operations

### LINKED ISSUE #71594: Azure provider triggers VMSS manual upgrade which restarts all instances at the same time
**What happened**:

We have a v1.10.6 cluster hosted in Azure (deployed with https://github.com/Azure/acs-engine) using `VMSS`  for agent pool and we decided to change the VM Size of the VMSS instances for cost efficiency. The plan was:

 - Change the VMSS VM Size
 - Double the number of instances (the new instances being created with the new VM Size)
 - Drain the old instances
 - Upgrade the old instances to the new VM Size
 - Scale down to the original number of nodes

What actually appened:

 - We changed the VMSS VM Size
 - We doubled the number of instances
 - Kubernetes Azure cloudprovider triggered a `manualupgrade` of the VMSS leading to upgrading all the nodes not matching the new VM Size
 - All services hosted were down due to all the "old nodes" being stopped at the same time for Upgrade

Here the Azure audit log showing that the Service Principal used by the kubernetes cluster Azure provider triggered the manual upgrade:
```json
{
    "authorization": {
        "action": "Microsoft.Compute/virtualMachineScaleSets/manualupgrade/action",
        "scope": "/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/k8s4-EUW-dev-RG/providers/Microsoft.Compute/virtualMachineScaleSets/k8s4-euw-dev-agent-vmss"
    },
    "caller": "<SOME_ID>",
    "channels": "Operation",
    "claims": {
        "aud": "https://management.core.windows.net/",
        "iss": "https://sts.windows.net/<AZURE_TENANT_ID>/",
        "iat": "1543571495",
        "nbf": "1543571495",
        "exp": "1543575395",
        "aio": "42RgYPg3Vf3czm1PjRPl7kz8ZFs/EwA=",
        "appid": "<K8S_AZURE_SERVICE_PRINCIPAL>",
        "appidacr": "1",
        "http://schemas.microsoft.com/identity/claims/identityprovider": "https://sts.windows.net/<AZURE_TENANT_ID>/",
        "http://schemas.microsoft.com/identity/claims/objectidentifier": "<SOME_ID>",
        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "<SOME_ID>",
        "http://schemas.microsoft.com/identity/claims/tenantid": "<AZURE_TENANT_ID>",
        "uti": "dOjT0Ob3B0OV9ckOFFXjAQ",
        "ver": "1.0"
    },
    "correlationId": "c0ec14e9-0d68-4eed-ab97-6043a2dc50fd",
    "description": "",
    "eventDataId": "00263b46-028d-498b-9264-ba94e20c1b84",
    "eventName": {
        "value": "EndRequest",
        "localizedValue": "End request"
    },
    "category": {
        "value": "Administrative",
        "localizedValue": "Administrative"
    },
    "eventTimestamp": "2018-11-30T10:09:31.1754255Z",
    "id": "/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/k8s4-EUW-dev-RG/providers/Microsoft.Compute/virtualMachineScaleSets/k8s4-euw-dev-agent-vmss/events/00263b46-028d-498b-9264-ba94e20c1b84/ticks/636791693711754255",
    "level": "Informational",
    "operationId": "c0ec14e9-0d68-4eed-ab97-6043a2dc50fd",
    "operationName": {
        "value": "Microsoft.Compute/virtualMachineScaleSets/manualupgrade/action",
        "localizedValue": "Manual Upgrade Virtual Machine Scale Set"
    },
    "resourceGroupName": "k8s4-EUW-dev-RG",
    "resourceProviderName": {
        "value": "Microsoft.Compute",
        "localizedValue": "Microsoft.Compute"
    },
    "resourceType": {
        "value": "Microsoft.Compute/virtualMachineScaleSets",
        "localizedValue": "Microsoft.Compute/virtualMachineScaleSets"
    },
    "resourceId": "/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/k8s4-EUW-dev-RG/providers/Microsoft.Compute/virtualMachineScaleSets/k8s4-euw-dev-agent-vmss",
    "status": {
        "value": "Accepted",
        "localizedValue": "Accepted"
    },
    "subStatus": {
        "value": "Accepted",
        "localizedValue": "Accepted (HTTP Status Code: 202)"
    },
    "submissionTimestamp": "2018-11-30T10:09:50.1545164Z",
    "subscriptionId": "<AZURE_SUBSCRIPTION_ID>",
    "properties": {
        "statusCode": "Accepted",
        "serviceRequestId": "03abebf2-7aaf-4195-8e21-fb9c2f48a861"
    },
    "relatedEvents": []
}
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.10.6
- Cloud provider or hardware configuration: Azure

/kind bug

### LINKED ISSUE #75579: Long running operations may fail because of go-autorest bugs
**What happened**:

According to https://github.com/Azure/go-autorest/issues/357, the timeout set in context doesn't take effect and 15min is always used for long running operations.

We should upgrade the version of go-autorest to 11.1.2 or 11.3.2.

**What you expected to happen**:

Azure clients respect timeout set from context.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Cross refer https://github.com/kubernetes/test-infra/pull/11887.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/kind bug
/priority critical-urgent

### PR DESCRIPTION
**Pull request by feiskyer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

/kind bug

**What this PR does / why we need it**:

Previously, VMSS API doesn't support configurations for each instance. Hence, Azure cloud provider upgrades manually for all instances whenever loadbalancer backend pools need to be updated. This would cause all instances restarted if there're also some other VMSS model changes.

To fix this issue, the PR switches to instance-level update APIs for Azure VMSS loadbalancer operations. It also upgrades Azure SDK to v21.4.0.

**Which issue(s) this PR fixes**:

Fixes #71594

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Switch to instance-level update APIs for Azure VMSS loadbalancer operations
```

/sig azure
/kind bug
/priority important-soon

### CODE REVIEW

File: pkg/cloudprovider/providers/azure/azure_standard.go [hunk 1]
```diff
@@ -632,24 +632,24 @@ func (as *availabilitySet) getPrimaryInterfaceWithVMSet(nodeName, vmSetName stri
...
 		}
 
-		klog.Errorf("error: az.ensureHostInPool(%s), az.vmSet.GetPrimaryInterface.Get(%s, %s), err=%v", nodeName, vmName, vmSetName, err)
+		klog.Errorf("error: az.EnsureHostInPool(%s), az.vmSet.GetPrimaryInterface.Get(%s, %s), err=%v", nodeName, vmName, vmSetName, err)
 		return err
 	}
 
 	if nic.ProvisioningState != nil && *nic.ProvisioningState == nicFailedState {
-		klog.V(3).Infof("ensureHostInPool skips node %s because its primary nic %s is in Failed state", nodeName, *nic.Name)
+		klog.V(3).Infof("EnsureHostInPool skips node %s because its primary nic %s is in Failed state", nodeName, *nic.Name)
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_standard.go]: V(2) or warning log?

**Review by andyzhangx — COMMENTED** [review]
LGTM with little comments

File: pkg/cloudprovider/providers/azure/azure_standard.go (hunk 1 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_standard.go]: Should be warning.

**Comment by feiskyer** [comment]
@andyzhangx Addressed comments. PTAL

@brendandburns Since there're also vendor updates, could you help to have a look?

**Comment by feiskyer** [comment]
@kubernetes/dep-approvers Could you help to approve the dependency updates?

**Comment by cblecker** [comment]
We need to really look at this one carefully. This vendors a number of new packages, and adds nearly 60k LOC.

Will start looking once tests are passing.

/cc @liggitt 
/hold

**Comment by feiskyer** [comment]
> We need to really look at this one carefully. This vendors a number of new packages, and adds nearly 60k LOC.

Right, a lot of files are added automatically by hack/update-vendor.sh because of package upgrades.

**Comment by liggitt** [comment]
running hack/lint-dependencies.sh shows these new differences introduced in this PR:
```sh
github.com/ghodss/yaml
    pinned:    v0.0.0-20180820084758-c7ce16629ff4
    preferred: v1.0.0
github.com/gogo/protobuf
    pinned:    v0.0.0-20171007142547-342cbe0a0415
    preferred: v1.2.0
github.com/kr/pretty
    pinned:    v0.0.0-20140812000539-f31442d60e51
    preferred: v0.1.0
github.com/onsi/ginkgo
    pinned:    v1.6.0
    preferred: v1.7.0
github.com/onsi/gomega
    pinned:    v0.0.0-20190113212917-5533ce8a0da3
    preferred: v1.4.3
github.com/prometheus/client_golang
    pinned:    v0.9.2
    preferred: v0.9.3-0.20190127221311-3c4408c8b829
3c4408c8b829
google.golang.org/api
    pinned:    v0.0.0-20181220000619-583d854617af
    preferred: v0.3.1
google.golang.org/genproto
    pinned:    v0.0.0-20170731182057-09f6ed296fc6
    preferred: v0.0.0-20180817151627-c66870c02cf8
google.golang.org/grpc
    pinned:    v1.13.0
    preferred: v1.19.1
gopkg.in/check.v1
    pinned:    v0.0.0-20161208181325-20d25e280405
    preferred: v1.0.0-20180628173108-788fd7840127
```

These modules are now pinned to versions different than the minimal preferred version.
That means that without require directives, a different version would be selected, which means that consumers of our staging modules would be running different code than we build/test by default.

We need to know what the differences are for the transitive dependencies, and as much as possible, avoid introducing new gaps between our pinned and preferred versions.

**Comment by feiskyer** [comment]
@liggitt Do you know anyways to fix this? The full commands I'm using to update vendors are:

```
 hack/pin-dependency.sh github.com/Azure/azure-sdk-for-go v27.1.0
 hack/pin-dependency.sh github.com/Azure/go-autorest v11.6.1
 hack/pin-dependency.sh github.com/grpc-ecosystem/grpc-gateway v1.8.5
 hack/pin-dependency.sh github.com/golang/protobuf v1.3.1
 hack/update-vendor.sh
```

**Comment by liggitt** [comment]
> @liggitt Do you know anyways to fix this?

The only way is to continue bumping transitive dependencies and updating. The only two we have that are intentionally pinned to versions other than their preferred version are the golang.org/x/... ones, which are pinned to the go1.12 release branches.

Of course, the more things that get changed in this PR, the greater the chance for breakage. Between bumping fundamental things like the grpc and proto libraries , or not bumping them and publishing staging components that aren't tested with the versions consumers will use by default, neither option sounds great.

**Comment by liggitt** [comment]
trying this out locally, I ended up with 25 bumps of existing dependencies (ignoring golang.org/x/{net,sys,tools}, which we want to keep at go1.12 levels), and 24 new dependencies, before the transitive requirements settled down.

667 files changed, 160965 insertions(+), 77687 deletions(-)

**Comment by feiskyer** [comment]
Pined all the dependencies reported from `hack/lint-dependencies.sh`. After this, the new results of `hack/lint-dependencies.sh` is:

```sh
$ hack/lint-dependencies.sh
These modules are pinned to versions different than the minimal preferred version.
That means that without require directives, a different version would be selected.
The command to switch to the minimal preferred version is listed for each module.

golang.org/x/lint
    pinned:    v0.0.0-20181217174547-8f45f776aaf1
    preferred: v0.0.0-20190301231843-5614ed5bae6f
    hack/pin-dependency.sh golang.org/x/lint v0.0.0-20190301231843-5614ed5bae6f
golang.org/x/net
    pinned:    v0.0.0-20190206173232-65e2d4e15006
    preferred: v0.0.0-20190311183353-d8887717615a
    hack/pin-dependency.sh golang.org/x/net v0.0.0-20190311183353-d8887717615a
golang.org/x/oauth2
    pinned:    v0.0.0-20170412232759-a6bd8cefa181
    preferred: v0.0.0-20190226205417-e64efc72b421
    hack/pin-dependency.sh golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
golang.org/x/sync
    pinned:    v0.0.0-20181108010431-42b317875d0f
    preferred: v0.0.0-20190227155943-e225da77a7e6
    hack/pin-dependency.sh golang.org/x/sync v0.0.0-20190227155943-e225da77a7e6
golang.org/x/sys
    pinned:    v0.0.0-20190209173611-3b5209105503
    preferred: v0.0.0-20190312061237-fead79001313
    hack/pin-dependency.sh golang.org/x/sys v0.0.0-20190312061237-fead79001313
golang.org/x/tools
    pinned:    v0.0.0-20190313210603-aa82965741a9
    preferred: v0.0.0-20190328211700-ab21143f2384
    hack/pin-dependency.sh golang.org/x/tools v0.0.0-20190328211700-ab21143f2384
google.golang.org/api
    pinned:    v0.0.0-20181220000619-583d854617af
    preferred: v0.3.1
    hack/pin-dependency.sh google.golang.org/api v0.3.1
```

Note that `google.golang.org/api` is not using v0.3.1 because of compiling errors. Hence, the original version is still kept.

**Comment by feiskyer** [comment]
the tests are still failing now. @liggitt  @kubernetes/dep-approvers For such compile errors because of conflicted vendors, any suggested actions should I take?

**Comment by liggitt** [comment]
> Note that `google.golang.org/api` is not using v0.3.1 because of compiling errors. Hence, the original version is still kept.

That means all consumers of staging components will encounter the compile error. Half-upgrading the dependency graph doesn't seem tenable.

**Comment by liggitt** [comment]
> the tests are still failing now. @liggitt @kubernetes/dep-approvers For such compile errors because of conflicted vendors, any suggested actions should I take?

Were the compile errors in k/k code or under vendor?

A bump of a dependency this large with this many transitive requirements is hard to find good shared levels for. I'd suggest incrementally satisfying the individual things lint-dependencies.sh indicates need updating (except for `golang.org/x/{crypto,net,sys,text,tools}`), then once that is happy, try to resolve the compile errors in k/k code. If the errors are in vendor, we may need to open changes against upstream dependencies as well to get them to align.

**Comment by lavalamp** [comment]
I'd actually recommend identifying the leaf dependency changes, then make them 1 or 2 at a time in multiple PRs, so that if they break something and get rolled back, it will be more obvious what exactly happened.

(Actually my first recommendation--and I realize this won't be winning me any friends, sorry--would be just not doing this--is there any way these dependencies can be isolated to e.g. just the cloud-controller-manager or something like that?)

**Comment by liggitt** [comment]
> I'd actually recommend identifying the leaf dependency changes, then make them 1 or 2 at a time in multiple PRs, so that if they break something and get rolled back, it will be more obvious what exactly happened.

that's a good idea, but requires finding the target leaf versions and a steady compilable state first

> is there any way these dependencies can be isolated to e.g. just the cloud-controller-manager or something like that?

not as long as {kubelet,controller-manager,cloud-controller-manager} all depend on cloud providers, and we share a single vendor dir

**Comment by feiskyer** [comment]
> Were the compile errors in k/k code or under vendor?

The compile errors are coming from tests and vendored files.

**Comment by feiskyer** [comment]
Thanks everyone for helping on the reviews. Because of too many dependencies are updated with the original way, we have cut a [patch release](https://github.com/Azure/azure-sdk-for-go/releases/tag/v21.4.0) for Azure Go SDK. With Azure Go SDK v21.4.0, only package `github.com/Azure/azure-sdk-for-go` is required for the bug fix.

@liggitt Could you help to check the modules/vendors update again?

@andyzhangx PTAL for the Azure related changes.

**Comment by liggitt** [comment]
/approve
for vendor update

thanks for being flexible. sorry you encountered the dependency gridlock.

**Comment by feiskyer** [comment]
@liggitt Thanks for the awesome help. There's actually another issue (#75579) would require more dependencies updates, still looking for workarounds.

File: pkg/cloudprovider/providers/azure/azure_loadbalancer.go [hunk 2]
```diff
@@ -829,13 +829,13 @@ func (az *Cloud) reconcileLoadBalancer(clusterName string, service *v1.Service,
 
 			// Remove backend pools from vmSets. This is required for virtual machine scale sets before removing the LB.
 			vmSetName := az.mapLoadBalancerNameToVMSet(lbName, clusterName)
-			klog.V(10).Infof("EnsureBackendPoolDeleted(%s, %s): start", lbBackendPoolID, vmSetName)
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_loadbalancer.go]: why `vmSetName` is removed in the logging? and `vmSetName` is still used in the next statement.
```
err := az.vmSet.EnsureBackendPoolDeleted(service, lbBackendPoolID, vmSetName, lb.BackendAddressPools)
```

File: pkg/cloudprovider/providers/azure/azure_vmss.go [hunk 3]
```diff
@@ -779,217 +730,288 @@ func (ss *scaleSet) ensureHostsInVMSetPool(service *v1.Service, backendPoolID st
...
+	key := buildVmssCacheKey(nodeResourceGroup, ss.makeVmssVMName(ssName, instanceID))
+	defer ss.vmssVMCache.Delete(key)
+
+	// Update vmssVM with backoff.
+	ctx, cancel := getContextWithCancel()
+	defer cancel()
+	klog.V(2).Infof("EnsureHostInPool begins to update vmssVM(%s) with new backendPoolID %s", vmName, backendPoolID)
+	resp, err := ss.VirtualMachineScaleSetVMsClient.Update(ctx, nodeResourceGroup, ssName, instanceID, newVM)
+	if ss.CloudProviderBackoff && shouldRetryHTTPRequest(resp, err) {
+		klog.V(2).Infof("EnsureHostInPool update backing off vmssVM(%s) with new backendPoolID %s, err: %v", vmName, backendPoolID, err)
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_vmss.go]: klog.Errorf

File: pkg/cloudprovider/providers/azure/azure_vmss.go [hunk 4]
```diff
@@ -779,217 +730,288 @@ func (ss *scaleSet) ensureHostsInVMSetPool(service *v1.Service, backendPoolID st
...
+		retryErr := ss.UpdateVmssVMWithRetry(nodeResourceGroup, ssName, instanceID, newVM)
+		if retryErr != nil {
+			err = retryErr
+			klog.V(2).Infof("EnsureHostInPool update abort backoff vmssVM(%s) with new backendPoolID %s, err: %v", vmName, backendPoolID, err)
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_vmss.go]: klog.Errorf

File: pkg/cloudprovider/providers/azure/azure_vmss.go [hunk 5]
```diff
@@ -779,217 +730,288 @@ func (ss *scaleSet) ensureHostsInVMSetPool(service *v1.Service, backendPoolID st
...
+	key := buildVmssCacheKey(nodeResourceGroup, ss.makeVmssVMName(ssName, instanceID))
+	defer ss.vmssVMCache.Delete(key)
+
+	// Update vmssVM with backoff.
+	ctx, cancel := getContextWithCancel()
+	defer cancel()
+	klog.V(2).Infof("ensureBackendPoolDeletedFromNode begins to update vmssVM(%s) with backendPoolID %s", nodeName, backendPoolID)
+	resp, err := ss.VirtualMachineScaleSetVMsClient.Update(ctx, nodeResourceGroup, ssName, instanceID, newVM)
+	if ss.CloudProviderBackoff && shouldRetryHTTPRequest(resp, err) {
+		klog.V(2).Infof("ensureBackendPoolDeletedFromNode update backing off vmssVM(%s) with backendPoolID %s, err: %v", nodeName, backendPoolID, err)
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_vmss.go]: klog.Errorf

File: pkg/cloudprovider/providers/azure/azure_vmss.go [hunk 6]
```diff
@@ -779,217 +730,288 @@ func (ss *scaleSet) ensureHostsInVMSetPool(service *v1.Service, backendPoolID st
...
+		retryErr := ss.UpdateVmssVMWithRetry(nodeResourceGroup, ssName, instanceID, newVM)
+		if retryErr != nil {
+			err = retryErr
+			klog.V(2).Infof("ensureBackendPoolDeletedFromNode update abort backoff vmssVM(%s) with backendPoolID %s, err: %v", nodeName, backendPoolID, err)
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_vmss.go]: klog.Errorf

File: pkg/cloudprovider/providers/azure/azure_vmss.go [hunk 7]
```diff
@@ -779,217 +730,288 @@ func (ss *scaleSet) ensureHostsInVMSetPool(service *v1.Service, backendPoolID st
...
+		}
 	}
-	err = ss.updateVMSSInstances(service, ssName, vmInstanceIDs)
 	if err != nil {
-		return err
+		klog.V(2).Infof("ensureBackendPoolDeletedFromNode failed to update vmssVM(%s) with backendPoolID %s: %v", nodeName, backendPoolID, err)
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_vmss.go]: klog.Errorf

File: pkg/cloudprovider/providers/azure/azure_loadbalancer.go (hunk 2 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_loadbalancer.go]: oops, should be added back.

Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_loadbalancer.go]: should add back.

File: pkg/cloudprovider/providers/azure/azure_vmss.go (hunk 7 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_vmss.go]: fixed

File: pkg/cloudprovider/providers/azure/azure_vmss.go (hunk 4 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_vmss.go]: fixed

File: pkg/cloudprovider/providers/azure/azure_vmss.go (hunk 3 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_vmss.go]: Infof should be used here for consistency with other places.

File: pkg/cloudprovider/providers/azure/azure_vmss.go (hunk 5 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_vmss.go]: Infof should be used here for consistency with other places.

File: pkg/cloudprovider/providers/azure/azure_vmss.go (hunk 6 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_vmss.go]: fixed

**Comment by feiskyer** [comment]
@andyzhangx Addressed comments. PTAL

**Comment by feiskyer** [comment]
pull-kubernetes-e2e-aks-engine-azure passed now.

/hold cancel

**Review by andyzhangx — APPROVED** [review]
/lgtm

File: pkg/cloudprovider/providers/azure/azure_vmss.go [hunk 8]
```diff
@@ -44,6 +43,7 @@ var (
 	resourceGroupRE        = regexp.MustCompile(`.*/subscriptions/(?:.*)/resourceGroups/(.+)/providers/Microsoft.Compute/virtualMachineScaleSets/(?:.*)/virtualMachines(?:.*)`)
 	vmssNicResourceGroupRE = regexp.MustCompile(`.*/subscriptions/(?:.*)/resourceGroups/(.+)/providers/Microsoft.Compute/virtualMachineScaleSets/(?:.*)/virtualMachines/(?:.*)/networkInterfaces/(?:.*)`)
 	vmssMachineIDTemplate  = "/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Compute/virtualMachineScaleSets/%s/virtualMachines/%s"
+	vmssIPConfigurationRE  = regexp.MustCompile(`.*/subscriptions/(?:.*)/resourceGroups/(.+)/providers/Microsoft.Compute/virtualMachineScaleSets/(.+)/virtualMachines/(.+)/networkInterfaces(?:.*)`)
```
Comment (jim-minter) [inline pkg/cloudprovider/providers/azure/azure_vmss.go]: couldn't vmssNicResourceGroupRE be reused?

File: pkg/cloudprovider/providers/azure/azure_vmss.go [hunk 9]
```diff
@@ -569,58 +579,8 @@ func (ss *scaleSet) GetPrimaryInterface(nodeName string) (network.Interface, err
...
-	})
-
-	return result, exists, err
-}
-
-// getPrimaryNetworkConfiguration gets primary network interface configuration for scale sets.
-func (ss *scaleSet) getPrimaryNetworkConfiguration(networkConfigurationList *[]compute.VirtualMachineScaleSetNetworkConfiguration, scaleSetName string) (*compute.VirtualMachineScaleSetNetworkConfiguration, error) {
-	networkConfigurations := *networkConfigurationList
+// getPrimarynetworkInterfaceConfiguration gets primary network interface configuration for scale set virtual machine.
+func (ss *scaleSet) getPrimarynetworkInterfaceConfiguration(networkConfigurations []compute.VirtualMachineScaleSetNetworkConfiguration, nodeName string) (*compute.VirtualMachineScaleSetNetworkConfiguration, error) {
```
Comment (jim-minter) [inline pkg/cloudprovider/providers/azure/azure_vmss.go]: nit: capital 'N' in getPrimarynetworkInterfaceConfiguration

File: pkg/cloudprovider/providers/azure/azure_vmss.go [hunk 10]
```diff
@@ -648,121 +608,38 @@ func (ss *scaleSet) getPrimaryIPConfigForScaleSet(config *compute.VirtualMachine
...
 	if err != nil {
-		klog.Errorf("ss.getScaleSet(%s) for service %q failed: %v", vmSetName, serviceName, err)
 		return err
 	}
-	if !exists {
-		errorMessage := fmt.Errorf("Scale set %q not found", vmSetName)
-		klog.Errorf("%v", errorMessage)
-		return errorMessage
+
+	// Check scale set name:
```
Comment (jim-minter) [inline pkg/cloudprovider/providers/azure/azure_vmss.go]: Does this comment need updating?

File: pkg/cloudprovider/providers/azure/azure_vmss.go (hunk 8 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_vmss.go]: good catch. It could be used by replacing the value to `vmssIPConfigurationRE `

File: pkg/cloudprovider/providers/azure/azure_vmss.go (hunk 10 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_vmss.go]: oops, it should. the returned value is nil now if this check is true
