### PR TITLE
kubeadm: skip removing last etcd member in reset phase

### LINKED ISSUE #2144: kubeadm reset takes more than 50 seconds to retry deleting the last etcd member
Moving kubernetes/kubernetes#91143 over here:

Original issue by @tnqn :
> **What happened**:
> When using `kubeadm reset` to delete the last control-plane node of a highly available Kubernetes cluster or the only node of a single control-plane cluster, it always take more than 50 seconds in the `remove-etcd-member` phase with a lot of `Failed to remove etcd member` errors.
> It's impossible to remove the last/only member of an etcd cluster. There's no need to try/retry removing it as the etcd cluster will be destroyed in next phase, then a `reset` operation can finish in a few seconds, instead of nearly one minute.
> 
> ```
> I0515 04:22:38.005689    2780 etcd.go:250] etcd endpoints read from etcd: https://192.168.10.12:2379
> I0515 04:22:38.005712    2780 etcd.go:120] update etcd endpoints: https://192.168.10.12:2379
> I0515 04:22:38.005721    2780 local.go:109] [etcd] get the member id from peer: https://192.168.10.12:2380
> I0515 04:22:38.013476    2780 local.go:115] [etcd] removing etcd member: https://192.168.10.12:2380, id: 11188237867079222133
> {"level":"warn","ts":"2020-05-15T04:22:38.022-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
> I0515 04:22:38.022187    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
> {"level":"warn","ts":"2020-05-15T04:22:38.075-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
> I0515 04:22:38.075861    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
> {"level":"warn","ts":"2020-05-15T04:22:38.185-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
> I0515 04:22:38.185952    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
> {"level":"warn","ts":"2020-05-15T04:22:38.399-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
> I0515 04:22:38.399959    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
> {"level":"warn","ts":"2020-05-15T04:22:38.818-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
> I0515 04:22:38.818367    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
> {"level":"warn","ts":"2020-05-15T04:22:39.652-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
> I0515 04:22:39.653052    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
> {"level":"warn","ts":"2020-05-15T04:22:41.363-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
> I0515 04:22:41.363659    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
> {"level":"warn","ts":"2020-05-15T04:22:44.585-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
> I0515 04:22:44.585459    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
> {"level":"warn","ts":"2020-05-15T04:22:51.086-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
> I0515 04:22:51.086407    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
> {"level":"warn","ts":"2020-05-15T04:23:04.011-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
> I0515 04:23:04.011372    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
> {"level":"warn","ts":"2020-05-15T04:23:30.382-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
> I0515 04:23:30.382526    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
> W0515 04:23:30.382566    2780 removeetcdmember.go:61] [reset] failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members.Please manually remove this etcd member using etcdctl
> I0515 04:23:30.382577    2780 cleanupnode.go:57] [reset] Getting init system
> ```
> 
> **What you expected to happen**:
> `kubeadm reset` doesn't need to try/retry removing the only member of an etcd cluster to avoid unnecessary errors and reduce the execution time from one minute to a few seconds.
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> 1. Create a single control-plane node with `kubeadm init`
> 2. Delete the node with `kubeadm reset`
>    It will take more than 50 seconds in `remove-etcd-member` phase.
> 
> **Anything else we need to know?**:
> 
> **Environment**:
> 
> * Kubernetes version (use `kubectl version`): v1.18.2
> * Cloud provider or hardware configuration:
> * OS (e.g: `cat /etc/os-release`):
> * Kernel (e.g. `uname -a`):
> * Install tools:
> * Network plugin and version (if this is a network-related bug):
> * Others:

### LINKED ISSUE #91143: kubeadm reset takes more than 50 seconds to retry deleting the last etcd member
**What happened**:
When using `kubeadm reset` to delete the last control-plane node of a highly available Kubernetes cluster or the only node of a single control-plane cluster, it always take more than 50 seconds in the `remove-etcd-member` phase with a lot of `Failed to remove etcd member` errors. 
It's impossible to remove the last/only member of an etcd cluster. There's no need to try/retry removing it as the etcd cluster will be destroyed in next phase, then a `reset` operation can finish in a few seconds, instead of nearly one minute.
```
I0515 04:22:38.005689    2780 etcd.go:250] etcd endpoints read from etcd: https://192.168.10.12:2379
I0515 04:22:38.005712    2780 etcd.go:120] update etcd endpoints: https://192.168.10.12:2379
I0515 04:22:38.005721    2780 local.go:109] [etcd] get the member id from peer: https://192.168.10.12:2380
I0515 04:22:38.013476    2780 local.go:115] [etcd] removing etcd member: https://192.168.10.12:2380, id: 11188237867079222133
{"level":"warn","ts":"2020-05-15T04:22:38.022-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
I0515 04:22:38.022187    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
{"level":"warn","ts":"2020-05-15T04:22:38.075-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
I0515 04:22:38.075861    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
{"level":"warn","ts":"2020-05-15T04:22:38.185-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
I0515 04:22:38.185952    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
{"level":"warn","ts":"2020-05-15T04:22:38.399-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
I0515 04:22:38.399959    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
{"level":"warn","ts":"2020-05-15T04:22:38.818-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
I0515 04:22:38.818367    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
{"level":"warn","ts":"2020-05-15T04:22:39.652-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
I0515 04:22:39.653052    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
{"level":"warn","ts":"2020-05-15T04:22:41.363-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
I0515 04:22:41.363659    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
{"level":"warn","ts":"2020-05-15T04:22:44.585-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
I0515 04:22:44.585459    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
{"level":"warn","ts":"2020-05-15T04:22:51.086-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
I0515 04:22:51.086407    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
{"level":"warn","ts":"2020-05-15T04:23:04.011-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
I0515 04:23:04.011372    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
{"level":"warn","ts":"2020-05-15T04:23:30.382-0700","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-834a096e-d413-4552-b508-f192cb26956e/192.168.10.12:2379","attempt":0,"error":"rpc error: code = Unknown desc = etcdserver: re-configuration failed due to not enough started members"}
I0515 04:23:30.382526    2780 etcd.go:329] Failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members
W0515 04:23:30.382566    2780 removeetcdmember.go:61] [reset] failed to remove etcd member: etcdserver: re-configuration failed due to not enough started members.Please manually remove this etcd member using etcdctl
I0515 04:23:30.382577    2780 cleanupnode.go:57] [reset] Getting init system
```

**What you expected to happen**:
`kubeadm reset` doesn't need to try/retry removing the only member of an etcd cluster to avoid unnecessary errors and reduce the execution time from one minute to a few seconds.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a single control-plane node with `kubeadm init`
2. Delete the node with `kubeadm reset`
It will take more than 50 seconds in `remove-etcd-member` phase.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.18.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by tnqn**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
If this is the last etcd member of the cluster, it cannot be removed due to "not enough started members". Skip it as the cluster will be destroyed in the next phase, otherwise the retries with exponential backoff will take more than 50 seconds to proceed.

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubeadm/issues/2144

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: during "reset" do not remove the only remaining stacked etcd member from the cluster and just proceed with the cleanup of the local etcd storage.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/phases/etcd/local.go [hunk 1]
```diff
@@ -103,6 +103,14 @@ func RemoveStackedEtcdMemberFromCluster(client clientset.Interface, cfg *kubeadm
 		return err
 	}
 
+	// If this is the last etcd member of the cluster, it cannot be removed due to "not
+	// enough started members". Skip it as the cluster will be destroyed in the next phase.
+	etcdClientAddress := etcdutil.GetClientURL(&cfg.LocalAPIEndpoint)
+	if len(etcdClient.Endpoints) == 1 && etcdClient.Endpoints[0] == etcdClientAddress {
+		klog.V(1).Info("[etcd] This is the last etcd member of etcd cluster, skip removing it")
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/etcd/local.go:110]: please change to:
`klog.V(1).Info("[etcd] This is the only remaining etcd member in the etcd cluster, skip removing it")`

File: cmd/kubeadm/app/phases/etcd/local.go [hunk 2]
```diff
@@ -103,6 +103,14 @@ func RemoveStackedEtcdMemberFromCluster(client clientset.Interface, cfg *kubeadm
 		return err
 	}
 
+	// If this is the last etcd member of the cluster, it cannot be removed due to "not
+	// enough started members". Skip it as the cluster will be destroyed in the next phase.
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/etcd/local.go:107]: please change this to:
```
// If this is the last remaining stacked etcd member in the cluster, calling RemoveMember()
// it is not needed.
```

**Comment by neolit123** [comment]
in the PR description replace `NONE` with:
> kubeadm: during "reset" do not remove the only remaining etcd member from the cluster and just proceed with the cleanup of the local etcd storage

/cc @rosti @fabriziopandini 
/priority backlog

File: cmd/kubeadm/app/phases/etcd/local.go (hunk 1 above)
Comment (tnqn) [reply cmd/kubeadm/app/phases/etcd/local.go]: done, thanks.

File: cmd/kubeadm/app/phases/etcd/local.go (hunk 2 above)
Comment (tnqn) [reply cmd/kubeadm/app/phases/etcd/local.go]: done, thanks.

**Comment by tnqn** [comment]
@neolit123 thanks for your quick review and suggestion.

**Comment by neolit123** [comment]
/approve
/retest

/hold for review
/assign @rosti @ereslibre 
PTAL if possible.

File: cmd/kubeadm/app/phases/etcd/local.go [hunk 3]
```diff
@@ -103,6 +103,14 @@ func RemoveStackedEtcdMemberFromCluster(client clientset.Interface, cfg *kubeadm
 		return err
 	}
 
+	// If this is the only remaining stacked etcd member in the cluster, calling RemoveMember()
+	// is not needed.
+	etcdClientAddress := etcdutil.GetClientURL(&cfg.LocalAPIEndpoint)
+	if len(etcdClient.Endpoints) == 1 && etcdClient.Endpoints[0] == etcdClientAddress {
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/etcd/local.go:109]: we had a discussion in the kubeadm meeting about this:
- etcdClient.Endpoints is not a good way to check this because the user might have configured multiple endpoints, instead we should add a function there that returns `[]Members`:
https://github.com/kubernetes/kubernetes/blob/b339ed0e75c5815d49c5c4d118d4b9858b4babc4/cmd/kubeadm/app/util/etcd/etcd.go
- then if the list of members contains only a single member we can for-loop it's enpoints and see if one of them matches the `etcdClientAddress`

@tnqn 
please let me know if you have further questions.

/cc @fabriziopandini

Comment (tnqn) [reply cmd/kubeadm/app/phases/etcd/local.go]: @neolit123 thanks for the suggestion, updated, PTAL.

**Comment by neolit123** [comment]
thank you for the update @tnqn 
the change seems valid to me and it is going to be tested in periodic CI after the PR merges.
did you test it locally?

/lgtm
/retest

**Comment by tnqn** [comment]
@neolit123 Yes, I have tested it with single control-plane node and multiple control-plane nodes, each of which exposes an extra endpoint with port 12379.
```
# Reset first Node 192.168.10.17
I0520 20:35:36.368795    3911 etcd.go:101] etcd endpoints read from pods: https://192.168.10.12:2379,https://192.168.10.17:2379
I0520 20:35:36.377870    3911 etcd.go:249] etcd endpoints read from etcd: https://192.168.10.17:12379,https://192.168.10.17:2379,https://192.168.10.12:12379,https://192.168.10.12:2379
I0520 20:35:36.377961    3911 etcd.go:119] update etcd endpoints: https://192.168.10.17:12379,https://192.168.10.17:2379,https://192.168.10.12:12379,https://192.168.10.12:2379
I0520 20:35:36.387007    3911 local.go:125] [etcd] get the member id from peer: https://192.168.10.17:2380
I0520 20:35:36.402765    3911 local.go:131] [etcd] removing etcd member: https://192.168.10.17:2380, id: 2087161450696811275
I0520 20:35:36.431883    3911 local.go:136] [etcd] Updated etcd member list: [{k8s-01 https://192.168.10.12:2380}]

# Reset second (last) Node 192.168.10.12
I0520 20:35:00.143370    3390 etcd.go:101] etcd endpoints read from pods: https://192.168.10.12:2379,https://192.168.10.17:2379
I0520 20:35:00.159536    3390 etcd.go:249] etcd endpoints read from etcd: https://192.168.10.12:12379,https://192.168.10.12:2379
I0520 20:35:00.159562    3390 etcd.go:119] update etcd endpoints: https://192.168.10.12:12379,https://192.168.10.12:2379
I0520 20:35:00.170699    3390 local.go:116] [etcd] This is the only remaining etcd member in the etcd cluster, skip removing it
```

/retest

File: cmd/kubeadm/app/phases/etcd/local.go [hunk 4]
```diff
@@ -103,6 +103,22 @@ func RemoveStackedEtcdMemberFromCluster(client clientset.Interface, cfg *kubeadm
...
 
+	members, err := etcdClient.ListMembers()
+	if err != nil {
+		return err
+	}
+	// If this is the only remaining stacked etcd member in the cluster, calling RemoveMember()
+	// is not needed.
+	if len(members) == 1 {
+		etcdClientAddress := etcdutil.GetClientURL(&cfg.LocalAPIEndpoint)
+		for _, endpoint := range etcdClient.Endpoints {
```
Comment (fabriziopandini) [inline cmd/kubeadm/app/phases/etcd/local.go:114]: Should we check etcdClientAddress == member.clientURLs instead of relying on endpoints?

Comment (tnqn) [reply cmd/kubeadm/app/phases/etcd/local.go:114]: Thanks @fabriziopandini for the review.
`etcdutil.NewFromCluster` has read all etcd endpoints from etcd and the `etcdClient.Endpoints` are [got from ClientURLs of all members](https://github.com/etcd-io/etcd/blob/747ff75c96df87530bcd8b6b02d1160c5500bf4e/clientv3/client.go#L170-L181).
https://github.com/kubernetes/kubernetes/blob/2f38e1b130ea75704bf17316a9c5e89bb36e2d54/cmd/kubeadm/app/util/etcd/etcd.go#L113-L118

And currently the Member struct returned here has only a few information and doesn't have clientURLs: https://github.com/kubernetes/kubernetes/blob/2f38e1b130ea75704bf17316a9c5e89bb36e2d54/cmd/kubeadm/app/util/etcd/etcd.go#L254-L259
So checking `etcdClientAddress` in `etcdClient.Endpoints` should have the same result as your suggestion and doesn't require struct change?

Comment (fabriziopandini) [reply cmd/kubeadm/app/phases/etcd/local.go:114]: ok, given that the goal of this check is to check this is actually the last member in the cluster.

**Comment by tnqn** [comment]
@neolit123 this PR is still held, are we waiting for additional review?

**Comment by neolit123** [comment]
thanks for the updates.
/hold cancel
