### PR TITLE
fix warning when using CSI driver to expand volume

### LINKED ISSUE #119348: When expanding CSI PVC, Kubernetes mistakenly outputted a warning-level event
### What happened?

```
➜  / kubectl describe pvc pvc1
Name:          pvc1
Namespace:     default
StorageClass:  sc1
Status:        Bound
Volume:        pvc-89a59cdf-c8a0-4b66-b18a-55e08bbf3ba7
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: iscsi.csi.xsky.com
               volume.kubernetes.io/storage-provisioner: iscsi.csi.xsky.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      40Gi
Access Modes:  RWO
VolumeMode:    Block
Used By:       <none>
Events:
  Type     Reason                  Age                   From                                 Message
  ----     ------                  ----                  ----                                 -------
  Normal   Resizing                59m (x10 over 4h58m)  external-resizer iscsi.csi.xsky.com  External resizer is resizing volume pvc-89a59cdf-c8a0-4b66-b18a-55e08bbf3ba7
  Warning  ExternalExpanding       59m (x3 over 3h33m)   volume_expand                        waiting for an external controller to expand this PVC
  Normal   VolumeResizeSuccessful  59m (x10 over 4h58m)  external-resizer iscsi.csi.xsky.com  Resize volume succeeded
```

In the events , the PVC has been successfully resized, but a **warning-level** log is still printed.
And by checking the logs of kube-controller-manager, can see the following output.

```
I0715 18:02:04.836426       1 plugins.go:947] "FindExpandablePluginBySpec -> err" specName="pvc-89a59cdf-c8a0-4b66-b18a-55e08bbf3ba7" err="no volume plugin matched"
I0715 18:02:04.836448       1 expand_controller.go:290] "Waiting for an external controller to expand the PVC" pvcKey="default/pvc1" pvcUID=89a59cdf-c8a0-4b66-b18a-55e08bbf3ba7
I0715 18:02:04.836631       1 event.go:307] "Event occurred" object="default/pvc1" fieldPath="" kind="PersistentVolumeClaim" apiVersion="v1" type="Warning" reason="ExternalExpanding" message="waiting for an external controller to expand this PVC"
```

### What did you expect to happen?

Do not print events with warning level.

### How can we reproduce it (as minimally and precisely as possible)?

To expand a a CSI PVC, and then use "kubectl describe pvc" to view its events.
(I am using xsky CSI to expand pvc, but based on my understanding of Kubernetes code, this issue can occur with any CSI.)

### Anything else we need to know?

image
image

Based on Kubernetes v1.27.3, I added some logs in the func `FindPluginBySpec` located in `pkg/volume/plugins`. These logs printed all the plugins before expansion, and I noticed that kubernetes.io/csi was not among them.
In my understanding, it is normal for CSI to be absent from the plugins here because CSI expansion is scheduled through external-resizer instead of kube-controller-manager.
Therefore, there should not be any warning-level logs printed here either.

### Kubernetes version

v1.27.3 
(In version 1.18, the issue can also be reproduced)

### Cloud provider

<details>

</details>

### OS version

Linux debian-hk 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux

### Install tools

kind v0.20.0

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by hoyho**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
controller manager generates confusing warning event 
```
  Warning  ExternalExpanding       59m (x3 over 3h33m)   volume_expand                        waiting for an external controller to expand this PVC
```
This is caused by the plugin probing:
```
I0715 18:02:04.836426       1 plugins.go:947] "FindExpandablePluginBySpec -> err" specName="pvc-89a59cdf-c8a0-4b66-b18a-55e08bbf3ba7" err="no volume plugin matched"
```
However, existing in-tree storage driver mechanism should be replaced by CSI nowadays

#### Which issue(s) this PR fixes:
Fixes #119348

#### Special notes for your reviewer:
it will only ignore harmless **no volume plugin matched** error in `func FindPluginBySpec`

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by jsafrane** [comment]
> Fixes https://github.com/kubernetes/kubernetes/issues/119348

That issue complains about `"FindExpandablePluginBySpec -> err" specName="pvc-89a59cdf-c8a0-4b66-b18a-55e08bbf3ba7" err="no volume plugin matched"` being logged. This PR does not change it.

> However, existing in-tree storage driver mechanism should be replaced by CSI nowadays

The event "waiting for an external controller to expand this PVC" is actually message that a CSI driver and its external-resizer sidecar should expand this volume.

**Comment by hoyho** [comment]
> > Fixes #119348
> 
> That issue complains about `"FindExpandablePluginBySpec -> err" specName="pvc-89a59cdf-c8a0-4b66-b18a-55e08bbf3ba7" err="no volume plugin matched"` being logged. This PR does not change it.
> 
> > However, existing in-tree storage driver mechanism should be replaced by CSI nowadays

> The event "waiting for an external controller to expand this PVC" is actually message that a CSI driver and its external-resizer sidecar should expand this volume.

Yes, this event will still be there but will be a `EventTypeNormal` instead . What confuses our clients is this is a warning event which they think there's something wrong.
like:
```
  Warning  ExternalExpanding       59m (x3 over 3h33m)   volume_expand                        waiting for an external controller to expand this PVC
```

I would like to keep this log as you mentioned it broadcasts a message to user that a CSI driver and its external-resizer sidecar should expand this volume.

**Comment by huww98** [comment]
I wonder why `pkg/volumes/csi/csi_plugin.go` is not matched for CSI PV? I didn't expect the error "no volume plugin matched".

File: pkg/controller/volume/expand/expand_controller.go [hunk 1]
```diff
@@ -273,7 +273,7 @@ func (expc *expandController) syncHandler(ctx context.Context, key string) error
 	if err != nil || volumePlugin == nil {
 		msg := "waiting for an external controller to expand this PVC"
 		eventType := v1.EventTypeNormal
-		if err != nil {
+		if err != nil && !volumetypes.IsProbeInTreePluginErr(err) {
```
Comment (huww98) [inline pkg/controller/volume/expand/expand_controller.go:276]: I think we can just check this error in `FindExpandablePluginBySpec`, since it already can return `nil, nil` to indicate not-found condition.

File: pkg/volume/util/types/types.go [hunk 2]
```diff
@@ -177,6 +177,26 @@ func IsUncertainProgressError(err error) bool {
...
+	return &ProbeInTreePluginErr{msg: msg}
+}
+
+// IsProbeInTreePluginErr checks if given error is of type that indicates
+// can not find a matched in-tree plugin based on the volume spec
+func IsProbeInTreePluginErr(err error) bool {
+	var probPluginError *ProbeInTreePluginErr
+	return errors.As(err, &probPluginError)
+}
+
```
Comment (huww98) [inline pkg/volume/util/types/types.go:199]:
```
ErrNoPluiginMatched = errors.New("no volume plugin matched")
```

And just check it with `errors.Is()`

**Review by huww98 — CHANGES_REQUESTED** [review]
To answer my own question. CSI is simply not registered for expand_controller.

File: pkg/controller/volume/expand/expand_controller.go (hunk 1 above)
Comment (hoyho) [reply pkg/controller/volume/expand/expand_controller.go:276]: Looks good

**Review by huww98 — APPROVED** [review]
/lgtm

**Comment by hoyho** [comment]
/assign @gnufied 
@gnufied  PTAL thank you
