### PR TITLE
Using structured logging in scheduler framework runtime

### LINKED ISSUE #94697: Make use of structured logging in framework runtime
/sig scheduling
/kind cleanup

In `pkg/scheduler/framework/runtime/framework.go`, we use `klog.Error` with a message that wraps an error:

https://github.com/kubernetes/kubernetes/blob/0fd10997dfee0f9ec2c413004bf93d310d76c84b/pkg/scheduler/framework/runtime/framework.go#L400-L401

Instead, we should be using structured logging, like so:

```golang
err := satus.AsError()
klog.ErrorS(err, "Failed running PreFilter plugin", "plugin", pl.Name(), "pod", klog.KObj(pod))
return framework.AsStatus(fmt.Errorf("on prefilter plugin %s: %w", pl.Name(), err)
```

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Using structured logging in scheduler framework runtime

**Which issue(s) this PR fixes**:

Fixes #94697

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/scheduler/framework/runtime/framework.go [hunk 1]
```diff
@@ -432,10 +432,9 @@ func (f *frameworkImpl) RunPreFilterExtensionAddPod(
 		}
 		status = f.runPreFilterExtensionAddPod(ctx, pl, state, podToSchedule, podToAdd, nodeInfo)
 		if !status.IsSuccess() {
-			msg := fmt.Sprintf("error while running AddPod for plugin %q while scheduling pod %q: %v",
-				pl.Name(), podToSchedule.Name, status.Message())
-			klog.Error(msg)
-			return framework.NewStatus(framework.Error, msg)
+			err := status.AsError()
+			klog.ErrorS(err, "Failed running AddPod extension for PreFilter plugin", "plugin", pl.Name(), "pod", klog.KObj(podToSchedule))
```
Comment (chendave) [inline pkg/scheduler/framework/runtime/framework.go:436]: Is that accurate to say `AddPod` is an extension?

File: pkg/scheduler/framework/runtime/framework.go [hunk 2]
```diff
@@ -397,9 +397,9 @@ func (f *frameworkImpl) RunPreFilterPlugins(ctx context.Context, state *framewor
 			if status.IsUnschedulable() {
 				return status
 			}
-			msg := fmt.Sprintf("prefilter plugin %q failed for pod %q: %v", pl.Name(), pod.Name, status.Message())
-			klog.Error(msg)
-			return framework.NewStatus(framework.Error, msg)
+			err := status.AsError()
+			klog.ErrorS(err, "Failed running PreFilter plugin", "plugin", pl.Name(), "pod", klog.KObj(pod))
+			return framework.AsStatus(fmt.Errorf("prefilter plugin %q failed for pod \"%v/%v\": %w", pl.Name(), pod.Namespace, pod.Name, err))
```
Comment (chendave) [inline pkg/scheduler/framework/runtime/framework.go:402]: what's the point of coming up different error message for `klog` and `status`?

Comment (alculquicondor) [reply pkg/scheduler/framework/runtime/framework.go:402]: The klog error is to be displayed immediately, thus, it should have all the information necessary for debugging.

The status is to be returned, and will be eventually displayed in a k8s event (like when you do `kubectl describe pod`). And this error might be concatenated with more context as it moves up.

Fix now: Do not include the pod name in the status, as it will be redundant up the stack.

For debate: Is this the correct place to produce the klog? My thinking is that, the closer to the actual error is, the easier it is to debug. But then we have some repeated code. The alternative is to klog one level above (in scheduler.go). But then the errors wouldn't show in other binaries, such as cluster autoscaler or the descheduler. Thoughts @damemi @MaciekPytel ?

File: pkg/scheduler/framework/runtime/framework.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/scheduler/framework/runtime/framework.go:436]: It's ok: we are not saying "extension point". OTH, it doesn't add any useful information over `Failed running AddPod for PreFilter plugin`, so I prefer that.

File: pkg/scheduler/framework/runtime/framework.go [hunk 3]
```diff
@@ -432,10 +432,9 @@ func (f *frameworkImpl) RunPreFilterExtensionAddPod(
 		}
 		status = f.runPreFilterExtensionAddPod(ctx, pl, state, podToSchedule, podToAdd, nodeInfo)
 		if !status.IsSuccess() {
-			msg := fmt.Sprintf("error while running AddPod for plugin %q while scheduling pod %q: %v",
-				pl.Name(), podToSchedule.Name, status.Message())
-			klog.Error(msg)
-			return framework.NewStatus(framework.Error, msg)
+			err := status.AsError()
+			klog.ErrorS(err, "Failed running AddPod extension for PreFilter plugin", "plugin", pl.Name(), "pod", klog.KObj(podToSchedule))
+			return framework.AsStatus(fmt.Errorf("error while running AddPod for plugin %q while scheduling pod \"%v/%v\": %w", pl.Name(), podToSchedule.Namespace, podToSchedule.Name, err))
```
Comment (alculquicondor) [inline pkg/scheduler/framework/runtime/framework.go:437]: Do not use the word `error`, `failed`, etc, as we are already crafting an error, so it's redundant. And also no need to say the pod name, as said in the other thread.

Something like: `running AddPod on plugin %q: %w` is enough. Other information is to be added up or down in the call hierarchy, but please check that. As said earlier, we don't need the `podToSchedule` information, but we need the `podToAddd`.

Ultimately, this can be checked in the unit test.

**Review by alculquicondor — COMMENTED** [review]
Fix unit tests :)
This will also help verify what's the full output.

File: pkg/scheduler/framework/runtime/framework.go [hunk 4]
```diff
@@ -628,9 +626,8 @@ func (f *frameworkImpl) RunScorePlugins(ctx context.Context, state *framework.Cy
 		}
```
Comment (alculquicondor) [inline pkg/scheduler/framework/runtime/framework.go:626]: above: `errCh.SendErrorWithCancel(status.AsError(), cancel)`.

However, we should also preserve the plugin name so we can add it to `ErrorS`. But we can leave this for a followup, as part of #94695.

File: pkg/scheduler/framework/runtime/framework.go [hunk 5]
```diff
@@ -648,9 +645,8 @@ func (f *frameworkImpl) RunScorePlugins(ctx context.Context, state *framework.Cy
...
```
Comment (alculquicondor) [inline pkg/scheduler/framework/runtime/framework.go:645]: Let's make the Errorf construction above consistent with `runScorePlugin`. Use `%w`, like in #94695.

File: pkg/scheduler/framework/runtime/framework.go [hunk 6]
```diff
@@ -628,9 +626,8 @@ func (f *frameworkImpl) RunScorePlugins(ctx context.Context, state *framework.Cy
...
 	})
 	if err := errCh.ReceiveError(); err != nil {
-		msg := fmt.Sprintf("error while running score plugin for pod %q: %v", pod.Name, err)
```
Comment (alculquicondor) [inline pkg/scheduler/framework/runtime/framework.go:631]: `plugins`, until we can pinpoint the plugin name.

**Comment by damemi** [comment]
@alculquicondor I agree with your point in https://github.com/kubernetes/kubernetes/pull/94850#discussion_r490288038, having the error as close to where it occurs is best for consumers and I think it's up to those consumers to decide how they want to handle it to reduce redundancy (including scheduler.go)

File: pkg/scheduler/framework/runtime/framework.go [hunk 7]
```diff
@@ -648,9 +645,8 @@ func (f *frameworkImpl) RunScorePlugins(ctx context.Context, state *framework.Cy
 		}
 	})
 	if err := errCh.ReceiveError(); err != nil {
-		msg := fmt.Sprintf("error while running normalize score plugin for pod %q: %v", pod.Name, err)
-		klog.Error(msg)
-		return nil, framework.NewStatus(framework.Error, msg)
+		klog.ErrorS(err, "Failed running Normalize Score plugin", "pod", klog.KObj(pod))
```
Comment (alculquicondor) [inline pkg/scheduler/framework/runtime/framework.go:648]: `Normalize on Score plugins`

File: pkg/scheduler/framework/runtime/framework.go [hunk 8]
```diff
@@ -743,9 +738,9 @@ func (f *frameworkImpl) RunBindPlugins(ctx context.Context, state *framework.Cyc
 			continue
 		}
 		if !status.IsSuccess() {
-			err := fmt.Errorf("plugin %q failed to bind pod \"%v/%v\": %w", bp.Name(), pod.Namespace, pod.Name, status.AsError())
-			klog.Error(err)
-			return framework.AsStatus(err)
+			err := status.AsError()
+			klog.ErrorS(err, "Failed running Bind plugin", "plugin", bp.Name(), "pod", klog.KObj(pod))
+			return framework.AsStatus(fmt.Errorf("running bind plugin %q: %w", bp.Name(), err))
```
Comment (alculquicondor) [inline pkg/scheduler/framework/runtime/framework.go:743]: `running Bind plugins`. Capitalization applies for others too.

**Comment by SataQiu** [comment]
@alculquicondor It looks like the unit tests have passed :)

File: pkg/scheduler/framework/runtime/framework.go [hunk 9]
```diff
@@ -642,15 +639,14 @@ func (f *frameworkImpl) RunScorePlugins(ctx context.Context, state *framework.Cy
 		}
 		status := f.runScoreExtension(ctx, pl, state, pod, nodeScoreList)
 		if !status.IsSuccess() {
-			err := fmt.Errorf("normalize score plugin %q failed with error %v", pl.Name(), status.Message())
+			err := fmt.Errorf("normalize score plugin %q failed with error %w", pl.Name(), status.AsError())
```
Comment (alculquicondor) [inline pkg/scheduler/framework/runtime/framework.go:642]: let's make this error construction consistent with the previous parallelize. I'll let you decide which pattern is best for now. But avoid saying `error` in an error message.

**Review by alculquicondor — COMMENTED** [review]
/approve

/lgtm

For the future: do not amend commits so that it's easier to identify what the changes are since the last review. Once you PR is approved, the approver will ask you to amend.

Also I don't see any progress in #94695. Feel free to follow up with the contributor that volunteered to work on it and see if you can take it. If you want, of course :)
