### PR TITLE
Use local daemonset manifest for installing Nvidia drivers

### LINKED ISSUE #93187: [Failing Test] [sig-scheduling] [Feature:GPUDevicePlugin] run Nvidia GPU Device Plugin tests (ci-kubernetes-e2e-gce-device-plugin-gpu)
**Which jobs are failing**:

`gce-device-plugin-gpu-master (ci-kubernetes-e2e-gce-device-plugin-gpu)`

**Which test(s) are failing**:

`[sig-scheduling] [Feature:GPUDevicePlugin] run Nvidia GPU Device Plugin tests`

**Since when has it been failing**:

`07-17-20 02:31 CDT`

**Testgrid link**:

https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master

**Reason for failure**:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/nvidia-gpus.go:218
Jul 17 07:47:26.988: Timed out after 600.025s.
Expected
    <bool>: false
to be true
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/nvidia-gpus.go:169
```

**Anything else we need to know**:

/sig scheduling
/cc @kubernetes/ci-signal @kubernetes/sig-scheduling-misc 
/priority critical-urgent
/milestone v1.19

### PR DESCRIPTION
**Pull request by hasheddan**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

Updates sig-scheduling e2e Nvidia GPU tests to install drivers using
local manifest by default. Currently the DaemonSet is fetched from the
GoogleCloudPlatform/container-enginer-accelerators repo by default.
Using a local manifest allows for manually specifying the image
cos-gpu-installer image rather than always using latest. A remote
manifest can still be fetched by setting
NVIDIA_DRIVER_INSTALLER_DAEMONSET env var.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

**Which issue(s) this PR fixes**:

Fixes #93187 

**Special notes for your reviewer**:

We may want to move back to specifying `latest` for the `cos-gpu-installer` image, but this will allow us to do that as desired when we want to avoid issues like the one described in #93187. Currently we get the advantage of picking up any changes in https://github.com/GoogleCloudPlatform/container-engine-accelerators, but it appears that repo is primarily for the GKE scenario where the image can be preloaded:
Ref: https://github.com/GoogleCloudPlatform/container-engine-accelerators/blob/master/nvidia-driver-installer/cos/daemonset-preloaded.yaml
Ref: https://cloud.google.com/kubernetes-engine/docs/how-to/gpus#installing_drivers

Looking back at the commit that added the preloaded version (https://github.com/GoogleCloudPlatform/container-engine-accelerators/commit/4fd24fa94e5a392d7560dab3571d9af4441cc144) it seems that the only reason the `daemonset.yaml` manifest is still maintained there is because k/k tests are referencing it. Because the GCP repo is primarily meant for GKE, I think it likely makes more sense to maintain the manifest for testing a cluster created using `kube-up.sh` in the k/k repo. If there is strong desire to continue to consume from the GCP repo, I would be happy to open a PR to pin that image to `gcr.io/cos-cloud/cos-gpu-installer:v20200701` until the issue with the `latest` image is resolved. Other options could be:
- Merging this and then setting `NVIDIA_DRIVER_INSTALLER_DAEMONSET` if we want to switch back to using the remote manifest
- Modifying this PR to continue to use the remote by default, but then setting `NVIDIA_DRIVER_INSTALLER_DAEMONSET` in the job config that runs this test to point to a separate manifest that we maintain (that would look like the one included in this PR)

/cc @Huang-Wei @ahg-g @liggitt 
/sig scheduling
/milestone v1.19
/priority critical-urgent

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: test/e2e/scheduling/nvidia-gpus.go [hunk 1]
```diff
@@ -128,20 +129,26 @@ func getGPUsAvailable(f *framework.Framework) int64 {
 func SetupNVIDIAGPUNode(f *framework.Framework, setupResourceGatherer bool) *framework.ContainerResourceGatherer {
 	logOSImages(f)
 
+	ds := &appsv1.DaemonSet{}
```
Comment (Huang-Wei) [inline test/e2e/scheduling/nvidia-gpus.go:132]: nit: define a bare variable here:

```
var ds *appsv1.DaemonSet
```

and then assign the DaemonSet at L137 and L145.

File: test/e2e/testing-manifests/scheduling/nvidia-driver-installer.yaml [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+        - name: nvidia-install-dir-host
+          mountPath: /usr/local/nvidia
+        - name: vulkan-icd-mount
+          mountPath: /etc/vulkan/icd.d
+        - name: dev
+          mountPath: /dev
+        - name: root-mount
+          mountPath: /root
+      containers:
+      - image: "gcr.io/google-containers/pause:2.0"
```
Comment (Huang-Wei) [inline test/e2e/testing-manifests/scheduling/nvidia-driver-installer.yaml:79]: nit: we can use latest image `pause:3.2`

**Comment by hasheddan** [comment]
@Huang-Wei thanks for the review! Both updates have been made :+1:

**Comment by Huang-Wei** [comment]
/approve
/lgtm
from scheduling side

**Comment by hasheddan** [comment]
@liggitt would you mind giving this a look?

**Comment by liggitt** [comment]
/sig node

this looks ok as a workaround, can we keep an issue open/assigned to sig-node to resolve the issue with the test image?
