### PR TITLE
Fixes exited messages when leaderelection lost

### LINKED ISSUE #107665: kube-controller-manager yields whole stack trace when it loses leaderelection
### What happened?

kube-controller-manager yields whole stack trace when it loses leaderelection.

### What did you expect to happen?

kube-controller-manager to only log `leaderelection lost` and to exit (without logging 17K lines of stack trace that is not useful for anyone).

### How can we reproduce it (as minimally and precisely as possible)?

```
E0117 14:49:11.977837       1 leaderelection.go:361] Failed to update lock: resource name may not be empty
I0117 14:49:11.977913       1 leaderelection.go:278] failed to renew lease kube-system/kube-controller-manager: timed out waiting for the condition
F0117 14:49:11.978122       1 controllermanager.go:293] leaderelection lost
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000130001, 0xc03a3fef20, 0x4c, 0x143)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x6a66080, 0xc000000003, 0x0, 0x0, 0xc03b46c7e0, 0x68dd348, 0x14, 0x125, 0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:945 +0x191
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x6a66080, 0x3, 0x0, 0x0, 0x445b035, 0x13, 0x0, 0x0, 0x0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:733 +0x17a
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1456
k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func2()
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:293 +0x73
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0xc00032b8c0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:200 +0x29
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc00032b8c0, 0x4a824a0, 0xc000499100)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:210 +0x15d
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection.RunOrDie(0x4a824e0, 0xc00012e018, 0x4ab8720, 0xc001352f80, 0x37e11d600, 0x2540be400, 0x77359400, 0xc001352f60, 0x45c4378, 0x0, ...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:222 +0x9c
k8s.io/kubernetes/cmd/kube-controller-manager/app.Run(0xc000131528, 0xc0001140c0, 0xc00054b850, 0xc00018c530)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:285 +0x979
k8s.io/kubernetes/cmd/kube-controller-manager/app.NewControllerManagerCommand.func2(0xc00004cb00, 0xc000d39680, 0x0, 0x28)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:124 +0x2b7
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc00004cb00, 0xc000136010, 0x28, 0x2b, 0xc00004cb00, 0xc000136010)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00004cb00, 0x16cb1631aab94aa9, 0x6a65ce0, 0x406525)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/controller-manager.go:46 +0xe5

goroutine 18 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x6a66080)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:416 +0xd8

goroutine 107 [chan receive]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/dynamiccertificates.(*ConfigMapCAController).Run(0xc0007394a0, 0x1, 0xc0001140c0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:222 +0x365
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/dynamiccertificates.unionCAContent.Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/dynamiccertificates/union_content.go:104 +0xcb

goroutine 126 [select]:
k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc0006623c0)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:231 +0x405
created by k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.newDelayingQueue
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/delaying_queue.go:68 +0x185

goroutine 130 [select]:
k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.(*worker).start(0xc000354f00)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:154 +0x105
created by k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.init.0
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57
```

kube-controller-manager yields around 17K lines of stack trace (omitted in the above example).

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

v1.20.12

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by kkkkun**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/107665

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by MadhavJivrajani** [comment]
/remove-kind flake
/kind cleanup
/priority backlog
@pohly FYI, since you had commented on the issue.

File: cmd/kube-controller-manager/app/controllermanager.go [hunk 1]
```diff
@@ -275,7 +275,8 @@ func Run(c *config.CompletedConfig, stopCh <-chan struct{}) error {
 				run(ctx, startSATokenController, initializersFunc)
 			},
 			OnStoppedLeading: func() {
-				klog.Fatalf("leaderelection lost")
+				klog.ErrorS(nil, "leaderelection lost")
+				os.Exit(255)
```
Comment (pohly) [inline cmd/kube-controller-manager/app/controllermanager.go:279]: How quickly do you want to exit here?

Originally I had implemented JSON output handling so that `ErrorS` flushes buffered info messages automatically. @serathius later [removed that](https://github.com/kubernetes/kubernetes/pull/107035) because flushing also did an fsync, which caused a performance issue.

If you want to ensure that info messages are written, you have to add `klog.Flush` before `os.Exit`, but only if a (probably small) delay is acceptable.

Comment (kkkkun) [reply cmd/kube-controller-manager/app/controllermanager.go:280]: I met this case several time.  
When it crash, i think  the currect message is enough. It's not need print all groutines stack.
>If you want to ensure that info messages are written, you have to add klog.Flush before os.Exit, but only if a (probably small) delay is acceptable.

Added.

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by kkkkun** [comment]
/assign deads2k
/assign mikedanese
/assign sig-scheduling-maintainers

Could you please giva a approved ?

File: cmd/kube-controller-manager/app/controllermanager.go (hunk 1 above)
Comment (jiahuif) [reply cmd/kube-controller-manager/app/controllermanager.go:280]: Could you take a look at the official migration guide here?
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#replacing-fatal-calls

If we really need a Flush, then we are to add flush everywhere considering how many `klog.Fatalf` we had previously.

@serathius your input is greatly appreciated.

Comment (kkkkun) [reply cmd/kube-controller-manager/app/controllermanager.go]: > Could you take a look at the official migration guide here? https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#replacing-fatal-calls
> 
> If we really need a Flush, then we are to add flush everywhere considering how many `klog.Fatalf` we had previously.
> 
> @serathius your input is greatly appreciated.

Thanks. I fixed according to [#replacing-fatal-calls](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#replacing-fatal-calls)

Comment (pohly) [reply cmd/kube-controller-manager/app/controllermanager.go]: > If we really need a Flush, then we are to add flush everywhere considering how many klog.Fatalf we had previously.

The question is whether you *want* a Flush. Fatalf flushes for 10 seconds before exiting:
https://github.com/kubernetes/klog/blob/d78dad3276f1f4139a6614b08b02e4678d2c3393/klog.go#L1108-L1111

The migration guide doesn't cover that aspect; I don't know whether that was intentional or an oversight.

Comment (kkkkun) [reply cmd/kube-controller-manager/app/controllermanager.go]: May be in this we  do not need to add Flush before exit .   If need, we add a new PR ?

Comment (kkkkun) [reply cmd/kube-controller-manager/app/controllermanager.go]: > will ask around to see if that is intentional, or do we need to ma

@jiahuif  @pohly  Any update ?

Comment (pohly) [reply cmd/kube-controller-manager/app/controllermanager.go]: We'll discuss it in the [WG Structured Logging meeting](https://github.com/kubernetes/community/tree/master/wg-structured-logging#meetings) tomorrow.

Comment (pchan) [reply cmd/kube-controller-manager/app/controllermanager.go]: > I met this case several time. When it crash, i think the currect message is enough. It doesn't need to print all groutine stacks.
> 

The klog.Exit* APIs do exactly that [1]. It also does the flushing. However, this is not mentioned in the migration guide and may not be best practise. 

[1]
https://github.com/kubernetes/klog/blob/d78dad3276f1f4139a6614b08b02e4678d2c3393/klog.go#L1729-L1734

Comment (pohly) [reply cmd/kube-controller-manager/app/controllermanager.go]: @pchan: in the structured logging call today you said that `klog.Fatal` doesn't flush. But looking at the code I see a `timeoutFlush(10 * time.Second)` call before each `os.Exit`. What differs is the logic around stack traces.
Agreed? 

Our conclusion in the structured logging call was that flushing for a short amount of time before `os.Exit` may be useful and would mirror the old behavior better.

Several options exist for a `klog.Fatal` replacement:
```
klog:
var ExitFlushTimeout = 10 * time.Second

user code:
klog.ErrorS(...)
klog.FlushWithTimeout(klog.ExitFlushTimeout)
os.Exit(255)
```

Or a combined call:
```
klog.Errors(...)
klog.FlushAndExit(klog.ExitFlushTimeout, 255)
```

By requiring a timeout value in the API, users are encouraged to consider the implications (wait or exit immediately?). `klog.ExitFlushTimeout` could serve as default.

The rationale for having support for this in klog is that klog knows whether flushing is necessary. If it isn't, it can exit immediately.

I have not listed an alternative which combines logging with exit. Adding that would lead to the proliferation of different logging calls that we have right now and that we want to get away from.

Comment (pohly) [reply cmd/kube-controller-manager/app/controllermanager.go]: I have filed https://github.com/kubernetes/klog/issues/301.

As we have some people here who are working on the migration and/or own code which currently uses `klog.Fatal`, can we perhaps use this thread here to decide about the desired solution? See proposals above.

Comment (pohly) [reply cmd/kube-controller-manager/app/controllermanager.go]: I'd like to point out one advantage of a combined `klog.FlushAndExit`: if we use that consistently everywhere instead of `os.Exit`, then at some point we can really ban the usage of that function outside of `main` (https://github.com/kubernetes/kubernetes/issues/102231#issuecomment-1019041587).

/cc @sanposhiho

Comment (kkkkun) [reply cmd/kube-controller-manager/app/controllermanager.go]: > I'd like to point out one advantage of a combined `klog.FlushAndExit`: if we use that consistently everywhere instead of `os.Exit`, then at some point we can really ban the usage of that function outside of `main` ([#102231 (comment)](https://github.com/kubernetes/kubernetes/issues/102231#issuecomment-1019041587)).
> 
> /cc @sanposhiho

Wait you PR merged! 
If we want to change to klog.FlushAndExit. We should change everywhere by another PRs.

Comment (pchan) [reply cmd/kube-controller-manager/app/controllermanager.go]: > @pchan: in the structured logging call today you said that `klog.Fatal` doesn't flush. But looking at the code I see a `timeoutFlush(10 * time.Second)` call before each `os.Exit`. What differs is the logic around stack traces. Agreed?

Yes agree, apologies for the oversight.

> 
> Our conclusion in the structured logging call was that flushing for a short amount of time before `os.Exit` may be useful and would mirror the old behavior better.

One alternative viewpoint:

Is there anyone who would actually use that feature i.e., specify a timeout ? Unless there is an actual requirement somewhere, it looks to me that we are introducing another lever, that will most likely be not used and taken as the default. In this thread the requirement is to not have the stack trace, the Exit APIs fits the bill. Have just 2 APIs, Exit which flushes/exits and Fatal that does a stack trace on top of what Exit does and call it out in the migration guilde.

Comment (pohly) [reply cmd/kube-controller-manager/app/controllermanager.go]: >  the Exit APIs fits the bill

You mean `klog.Exitf` and friends? That is part of the old-style structured logging API. We need a replacement for that when migrating to structured logging, just as we need a replacement for `klog.Fatalf`.

Comment (pohly) [reply cmd/kube-controller-manager/app/controllermanager.go]: > So in here, we should exit by `klog.FlushAndExit(klog.ExitFlushTimeout, 1)` ?

Yes, that would be good.

> May be we need a new tag in klog and replace by kubernetes ?

I'll get to that as soon as possible. There's still https://github.com/kubernetes/klog/pull/297 pending, then klog should be ready for a new release.

Comment (kkkkun) [reply cmd/kube-controller-manager/app/controllermanager.go]: > I'll get to that as soon as possible. There's still [kubernetes/klog#297](https://github.com/kubernetes/klog/pull/297) pending, then klog should be ready for a new release.

Look forward to it!

Comment (pohly) [reply cmd/kube-controller-manager/app/controllermanager.go]: See https://github.com/kubernetes/kubernetes/pull/108725

**Review by pohly — APPROVED** [review]
/lgtm

**Comment by kkkkun** [comment]
The test cases is not change of this. 
Commit an issue
https://github.com/kubernetes/kubernetes/issues/108975
