### PR TITLE
Reduce the number of processes used in e2e to prevent unexpected OOM

### LINKED ISSUE #127996: [Flaking Test] [sig-node] PriorityPidEvictionOrdering [Slow] [Serial] [Disruptive] [NodeFeature:Eviction] should cause PIDPressure should eventually evict all of the correct pods
### Which jobs are flaking?

- ci-crio-cgroupv2-node-e2e-eviction
- ci-crio-cgroupv1-node-e2e-eviction
also
- pull-crio-cgroupv1-node-e2e-eviction
- pull-crio-cgroupv2-node-e2e-eviction

https://storage.googleapis.com/k8s-triage/index.html?test=PodAndContainerStatsFromCRI

### Which tests are flaking?

when we run containers with PodAndContainerStatsFromCRI=true or false.

- It] [sig-node] PriorityPidEvictionOrdering [Slow] [Serial] [Disruptive] [NodeFeature:Eviction] when we run containers with PodAndContainerStatsFromCRI=true that should cause PIDPressure should eventually evict all of the correct pods
- E2eNode Suite.[It] [sig-node] PriorityPidEvictionOrdering [Slow] [Serial] [Disruptive] [NodeFeature:Eviction] when we run containers with PodAndContainerStatsFromCRI=false that should cause PIDPressure should eventually evict all of the correct pods

### Since when has it been flaking?

years ago: https://github.com/kubernetes/kubernetes/issues/107804

### Testgrid link

https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-eviction and https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv2-node-e2e-eviction

### Reason for failure (if possible)

```
STEP: checking eviction ordering and ensuring important pods don't fail - k8s.io/kubernetes/test/e2e_node/eviction_test.go:770 @ 10/10/24 16:06:49.933
[FAILED] pod fork-bomb-container-with-high-priority-pod failed; expected Status.Reason to be Evicted, but got 
Expected
    <string>: 
to equal
    <string>: Evicted
In [It] at: k8s.io/kubernetes/test/e2e_node/eviction_test.go:803 @ 10/10/24 16:06:49.934
< Exit [It] should eventually evict all of the correct pods - k8s.io/kubernetes/test/e2e_node/eviction_test.go:628 @ 10/10/24 16:06:49.934 (56.174s)
> Enter [AfterEach] TOP-LEVEL - k8s.io/kubernetes/test/e2e_node/eviction_test.go:690 @ 10/10/24 16:06:49.934
STEP: deleting pods - k8s.io/kubernetes/test/e2e_node/eviction_test.go:701 @ 10/10/24 16:06:49.934
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by bitoku**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

[sig-node] PriorityPidEvictionOrdering [Slow] [Serial] [Disruptive] [NodeFeature:Eviction] should cause PIDPressure should eventually evict all of the correct pods
This test has been failing for long time.
According to the logs, fork-bomb-container-with-high-priority-pod is killed by OOM.
This PR reduces the number of processes to reduce overall memory usage.

https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-crio-cgroupv2-node-e2e-eviction/1882132155849510912

Failing test
```
[sig-node] PriorityPidEvictionOrdering [Slow] [Serial] [Disruptive] [NodeFeature:Eviction] [Feature:Eviction] when we run containers with PodAndContainerStatsFromCRI=false that should cause PIDPressure  [It] should eventually evict all of the correct pods [sig-node, Slow, Serial, Disruptive, NodeFeature:Eviction, Feature:Eviction]
k8s.io/kubernetes/test/e2e_node/eviction_test.go:583

  [FAILED] pod fork-bomb-container-with-high-priority-pod failed; expected Status.Reason to be Evicted, but got 
  Expected
      <string>: 
  to equal
      <string>: Evicted
  In [It] at: k8s.io/kubernetes/test/e2e_node/eviction_test.go:759 @ 01/22/25 18:42:56.728
```

crio log
```
Jan 22 18:42:55 tmp-node-e2e-5cd8ef3d-fedora-coreos-41-20250105-3-0-gcp-x86-64 crio[2582]: time="2025-01-22 18:42:55.268892336Z" level=debug msg="Response: &ContainerStatusResponse{Status:&ContainerStatus{Id:58e43ccbf6cccac462474da291076a4ff62652046c2044341e3758609f8a45e6,Metadata:&ContainerMetadata{Name:fork-bomb-container-with-high-priority-container,Attempt:0,},State:CONTAINER_EXITED,CreatedAt:1737571305703589375,StartedAt:1737571305768141407,FinishedAt:1737571374603134774,ExitCode:137,Image:&ImageSpec{Image:registry.k8s.io/e2e-test-images/busybox:1.36.1-1,Annotations:map[string]string{},UserSpecifiedImage:,RuntimeHandler:,},ImageRef:registry.k8s.io/e2e-test-images/busybox@sha256:a9155b13325b2abef48e71de77bb8ac015412a566829f621d06bfae5c699b1b9,Reason:OOMKilled,...
```

serial log
```
[  348.241165] Out of memory: Killed process 4758 (sh) total-vm:4660kB, anon-rss:384kB, file-rss:2176kB, shmem-rss:0kB, UID:0 pgtables:48kB oom_score_adj:1000
[  348.257300] Out of memory: Killed process 4758 (sh) total-vm:4660kB, anon-rss:384kB, file-rss:2176kB, shmem-rss:0kB, UID:0 pgtables:48kB oom_score_adj:1000
[  348.273171] Out of memory: Killed process 4816 (sh) total-vm:4404kB, anon-rss:128kB, file-rss:1316kB, shmem-rss:0kB, UID:0 pgtables:48kB oom_score_adj:1000
[  348.288908] Out of memory: Killed process 4818 (sh) total-vm:4404kB, anon-rss:128kB, file-rss:1316kB, shmem-rss:0kB, UID:0 pgtables:48kB oom_score_adj:1000
[  348.304721] Out of memory: Killed process 4819 (sh) total-vm:4404kB, anon-rss:128kB, file-rss:1316kB, shmem-rss:0kB, UID:0 pgtables:48kB oom_score_adj:1000
...
```

#### Which issue(s) this PR fixes:

Fixes #127996

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bitoku** [comment]
Looking at some successful and failed runs, it seems the cause of the failure is race condition of eviction and OOM.
Apparently there is a threshold at around 10,000+, and if the number of process is over 10,000 and the eviction is delayed for some reasons, it is oom-killed instead of being evicted.

Also `sh` is using memory compared to `sleep`, so I removed `while` loop in the pid consuming pod.
```
[ 6211.332268] Out of memory: Killed process 515098 (sh) total-vm:4628kB, anon-rss:380kB, file-rss:1332kB, shmem-rss:0kB, UID:0 pgtables:40kB oom_score_adj:1000
[ 6211.346696] Out of memory: Killed process 515210 (sh) total-vm:4632kB, anon-rss:384kB, file-rss:1332kB, shmem-rss:0kB, UID:0 pgtables:40kB oom_score_adj:1000
[ 6211.361578] Out of memory: Killed process 522931 (sh) total-vm:4640kB, anon-rss:392kB, file-rss:1332kB, shmem-rss:0kB, UID:0 pgtables:40kB oom_score_adj:1000
[ 6211.376067] Out of memory: Killed process 523987 (sleep) total-vm:4272kB, anon-rss:0kB, file-rss:668kB, shmem-rss:0kB, UID:0 pgtables:40kB oom_score_adj:1000
[ 6211.390876] Out of memory: Killed process 524022 (sleep) total-vm:4272kB, anon-rss:0kB, file-rss:484kB, shmem-rss:0kB, UID:0 pgtables:44kB oom_score_adj:1000
[ 6211.405937] Out of memory: Killed process 526211 (sleep) total-vm:4272kB, anon-rss:0kB, file-rss:544kB, shmem-rss:0kB, UID:0 pgtables:40kB oom_score_adj:1000
```

**Comment by SergeyKanzhelev** [comment]
test failed: pull-crio-cgroupv1-node-e2e-eviction 

Does it mean that test didn't work?

**Comment by bitoku** [comment]
Apparently it's no longer oom-killed, but other ordering issue appeared.

**Comment by kannon92** [comment]
/hold

Triggers a new test case (first one passed).

Let's make sure we don't have any flakes in three runs. And then we can merge and see how it behaves in the CI.

/assign @SergeyKanzhelev

**Comment by kannon92** [comment]
second one passes.

/test pull-crio-cgroupv1-node-e2e-eviction
/test pull-crio-cgroupv2-node-e2e-eviction

**Comment by kannon92** [comment]
/hold cancel

I think we should merge this.

File: test/e2e_node/eviction_test.go [hunk 1]
```diff
@@ -473,13 +473,13 @@ var _ = SIGDescribe("PriorityPidEvictionOrdering", framework.WithSlow(), framewo
 
 	highPriorityClassName := f.BaseName + "-high-priority"
 	highPriority := int32(999999999)
-	processes := 30000
+	processes := 5000
```
Comment (ffromani) [inline test/e2e_node/eviction_test.go:476]: thanks for the PR! I agree we should have this fix to restore some signal.

I would prefer to add a comment here (and to refer on line 482 below) about how you determined these numbers, which can probably be just a copypaste of your previous github comments.

The reason I'm asking is that keeping history is hard, keeping history from github issue/PR comments is extra hard.
