### PR TITLE
fix: Allow automatic ACR auth in private Azure clouds

### LINKED ISSUE #90412: Azure credential provider does not authenticate to ACR in all clouds
**What happened**:
An aks-engine cluster with a user assigned managed service cluster identity fails to authenticate to azure container registries in private clouds when the proper (acrpull) azure role assignments are in place and when there are no image pull secrets.

**What you expected to happen**:
The cluster should be able to authenticate and pull from an ACR hosted in the same azure cloud without needing additional pull secrets when the cluster identity has the proper acrpull azure role assignment, no matter which azure cloud it is operating in.

**How to reproduce it (as minimally and precisely as possible)**:
Assume you have a private azure cloud where every url ends with "my.cloud". That would mean the ACR suffix would be `.azurecr.my.cloud`. Let's pretend you have an ACR at `test.azurecr.my.cloud` and you try to deploy a pod in your cluster referencing the image `test.azurecr.my.cloud/helloworld:latest`. This will fail to pull when you have no image pull secrets.

**Anything else we need to know?**:
The problem stems from the following lines where expected ACR suffix domains are hardcoded:
https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/azure/azure_credentials.go#L49-L50

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.9
- Cloud provider or hardware configuration: Azure private
- OS: ubuntu 16.0.4
- Network plugin and version: Azure CNI

### PR DESCRIPTION
**Pull request by DavidParks8**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Provides a fix to allow a cluster in a private Azure cloud to authenticate to ACR in the same cloud.

**Which issue(s) this PR fixes**:
Fixes #90412

**Does this PR introduce a user-facing change?**:
NONE

```release-note
Provides a fix to allow a cluster in a private Azure cloud to authenticate to ACR in the same cloud.
```

### CODE REVIEW

File: pkg/credentialprovider/azure/azure_credentials.go [hunk 1]
```diff
@@ -203,6 +204,28 @@ func (a *acrProvider) Provide(image string) credentialprovider.DockerConfig {
...
+			for _, url := range containerRegistryUrls {
+				if url == customAcrSuffix {
+					hasBeenAdded = true
+					break
+				}
+			}
+
+			if !hasBeenAdded {
+				cred := &credentialprovider.DockerConfigEntry{
+					Username: a.config.AADClientID,
```
Comment (andyzhangx) [inline pkg/credentialprovider/azure/azure_credentials.go:222]: there is a security issue here:
if we support self defined ACR domain, e.g. `test.azurecr.my.cloud`, then service principal secret would be sent to that remote server. 
The reason why we use hardcoded domains is that we could always make sure the following 4 domains are owned by Azure:
https://github.com/kubernetes/kubernetes/blob/0c0984abdb17246b472e65f0fefee82637dd83e6/pkg/credentialprovider/azure/azure_credentials.go#L49-L50

Comment (DavidParks8) [reply pkg/credentialprovider/azure/azure_credentials.go:222]: The environment is fetched from ARM. Thus, the only acr endpoints used here will be the one returned by ARM. This needs to be allowed in order to support clouds with urls we are not allowed to expose publicly.

Comment (andyzhangx) [reply pkg/credentialprovider/azure/azure_credentials.go:222]: that sounds reasonable, thanks.

**Comment by andyzhangx** [comment]
pls fix the unit test failure:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //pkg/credentialprovider/azure:go_default_test
-----------------------------------------------------------------------------
=== RUN   Test
--- PASS: Test (0.00s)
=== RUN   TestParseACRLoginServerFromImage
--- FAIL: TestParseACRLoginServerFromImage (0.00s)
    azure_credentials_test.go:161: function parseACRLoginServerFromImage returns "" for image foo.azurecr.my.cloud/bar/image:version, expected "foo.azurecr.my.cloud"
FAIL
```
overall LGTM

**Comment by chewong** [comment]
@DavidParks8 Azure-related PR jobs should be fixed. Looks like for `pull-kubernetes-verify`, you are missing `"//vendor/github.com/Azure/go-autorest/autorest/azure:go_default_library"` in `pkg/credentialprovider/azure/BUILD`. Let me know if the jobs are still failing.

/assign @feiskyer

**Comment by DavidParks8** [comment]
@andyzhangx can I please get an official lgtm now that the flakey tests have passed? I will also need this change squash merged because I do not have merge rights. Thanks for your time!

**Comment by andyzhangx** [comment]
> @andyzhangx can I please get an official lgtm now that the flakey tests have passed? I will also need this change squash merged because I do not have merge rights. Thanks for your time!

can you squash the commits first? thanks

**Comment by DavidParks8** [comment]
Squashed.

**Review by andyzhangx — APPROVED** [review]
/lgtm
/approve

**Comment by andyzhangx** [comment]
BTW, this PR is for Azure stack, right? @DavidParks8

**Comment by DavidParks8** [comment]
The PR is for private Azure clouds, including Azure stack.

File: pkg/credentialprovider/azure/azure_credentials.go [hunk 2]
```diff
@@ -203,6 +204,28 @@ func (a *acrProvider) Provide(image string) credentialprovider.DockerConfig {
...
 			cfg[url] = *cred
 		}
+
+		// Handle the custom cloud case
+		// In clouds where ACR is not yet deployed, the string will be empty
+		if a.environment != nil && strings.Contains(a.environment.ContainerRegistryDNSSuffix, ".azurecr.") {
+			customAcrSuffix := "*" + a.environment.ContainerRegistryDNSSuffix
+			hasBeenAdded := false
+			for _, url := range containerRegistryUrls {
+				if url == customAcrSuffix {
```
Comment (feiskyer) [inline pkg/credentialprovider/azure/azure_credentials.go:214]: nit: it's better to use strings.EqualFold here, which is case-insensitivity

Comment (DavidParks8) [reply pkg/credentialprovider/azure/azure_credentials.go]: Fixed.

**Review by feiskyer — APPROVED** [review]
/lgtm
