### PR TITLE
Honor forceAllowCreate in service registry

### LINKED ISSUE #73759: Creating new object using kubectl --server-side apply fails
**What happened**:

When running `kubectl --server-side apply -f obj.yaml` the apiserver returns an error:
```
Error from server (NotFound): services "foo" not found
```
with obj.yaml being:
```
apiVersion: v1
kind: Service
metadata:
  name: foo
spec:
  selector:
    app: foo
  ports:
  - port: 80
    targetPort: http
```

**What you expected to happen**:

The object being created if not found.

**How to reproduce it (as minimally and precisely as possible)**:

- get etcd up `third_party/etcd/etcd`
- get apiserver up `mkdir -p /tmp/certs && hack/update-bazel.sh  && bazel run  //cmd/kube-apiserver:kube-apiserver -- --port=8090 --etcd-servers="http://localhost:2379" --cert-dir="/tmp/certs" --admission-control=MutatingAdmissionWebhook,ValidatingAdmissionWebhook,AlwaysAdmit --feature-gates ServerSideApply=true`
- run kubectl apply `kubectl --server-side apply -f obj.yaml` (built from master as well)

**Anything else we need to know?**:
Everything built directly from master

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by jennybuckley**
**What type of PR is this?**:
/kind bug
/sig api-machinery
/priority important-soon
cc @kwiesmueller @apelisse

**What this PR does / why we need it**:
Change the service registry to support create on update, if forceAllowCreate is true. forceAllowCreate is only true in server-side apply. This doesn't do the retry loop, but I think it's better than just failing. Also, the retry loop is already broken by the service custom storage, since it uses the updated object info provided only [once](https://github.com/kubernetes/kubernetes/blob/1a5e48e29d02537828634aac83847aba6aa17c6f/pkg/registry/core/service/storage/rest.go#L356) to create a service object to do its special logic on, then it creates a [new updated object info](https://github.com/kubernetes/kubernetes/blob/1a5e48e29d02537828634aac83847aba6aa17c6f/pkg/registry/core/service/storage/rest.go#L425) from that service object which always returns that same object and passes that into the retry loop, so if the retry loop fails once, it should be guaranteed to fail on each retry anyway. Basically, this PR will make the update retry situation any worse for services.

**Which issue(s) this PR fixes**:
Fixes #73759

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by kwiesmueller** [comment]
Was the test in apply_test.go failing before? If not, can we get a test that should have failed before to verify it is fixed (like an e2e/Integration test for the kubectl bug)

**Comment by apelisse** [comment]
> Was the test in apply_test.go failing before?

I think the test is reproducing the failure you had? So clearly it should have failed before.

**Comment by jennybuckley** [comment]
It did fail before, with the same "NotFound" error on create

File: pkg/registry/core/service/storage/rest.go [hunk 1]
```diff
@@ -337,6 +337,18 @@ func (rs *REST) healthCheckNodePortUpdate(oldService, service *api.Service, node
 func (rs *REST) Update(ctx context.Context, name string, objInfo rest.UpdatedObjectInfo, createValidation rest.ValidateObjectFunc, updateValidation rest.ValidateObjectUpdateFunc, forceAllowCreate bool, options *metav1.UpdateOptions) (runtime.Object, bool, error) {
 	oldObj, err := rs.services.Get(ctx, name, &metav1.GetOptions{})
 	if err != nil {
+		// Support create on update, if forced to.
+		if forceAllowCreate {
+			obj, err := objInfo.UpdatedObject(ctx, nil)
+			if err != nil {
+				return nil, false, err
+			}
+			createdObj, err := rs.Create(ctx, obj, createValidation, &metav1.CreateOptions{})
```
Comment (apelisse) [inline pkg/registry/core/service/storage/rest.go]: A couple of comments:
1. If this fails on a conflict (because of a race with another create), is it going to be retried by the update/patch handler?
2. You use an empty CreateOptions, are there any options from UpdateOptions that would need to be carried over?

Comment (apelisse) [reply pkg/registry/core/service/storage/rest.go]: > * If this fails on a conflict (because of a race with another create), is it going to be retried by the update/patch handler?

I guess my point is, how is this going to be different from a "regular" storage doing create on update.

Comment (jennybuckley) [reply pkg/registry/core/service/storage/rest.go]: 1. It won't be retried.
2. dry run definitely needs to be carried over. really good catch.

Comment (apelisse) [reply pkg/registry/core/service/storage/rest.go]: > 2. dry run definitely needs to be carried over. really good catch.

I didn't have dry-run in mind, but this would have been a nasty bug!

Comment (jennybuckley) [reply pkg/registry/core/service/storage/rest.go]: regarding 1, as far as I can tell, the retry loop is already broken by the service custom storage, since it uses the updated object info provided only [once](https://github.com/kubernetes/kubernetes/blob/1a5e48e29d02537828634aac83847aba6aa17c6f/pkg/registry/core/service/storage/rest.go#L356) to create service object to do its special logic on, then it creates a [new updated object info](https://github.com/kubernetes/kubernetes/blob/1a5e48e29d02537828634aac83847aba6aa17c6f/pkg/registry/core/service/storage/rest.go#L425) which always returns that same object and passes that into the retry loop, so if the retry loop fails once, it should be guaranteed to fail on each retry anyway. Basically, I don't think this PR will make the update retry situation any worse for services.

**Comment by lavalamp** [comment]
We should probably have a canonical way folks convert from update to create options. It's far too easy to not remember to copy over dry run. Can you file an issue?

/approve
