### PR TITLE
Switch from api.ObjectMetaFor to meta.Accessor in most of places

### LINKED ISSUE #23278: Introducing protobuf tags changes behavior api.ObjectMetaFor
After running protobuf generator some unit tests are not passing, e.g.: TestAnnotateObjectFromFile

I did some debugging and the issue is basically, that (at least in this particula case):
  api.ObjectMetaFor(&v1.Pod{})
returns:
  unexpected error: couldn't assign/convert *v1.ObjectMeta to *api.ObjectMeta

The reason for that is that:
https://github.com/kubernetes/kubernetes/blob/master/pkg/runtime/helper.go#L52

underlying is calling:
ConvertibleTo:
https://github.com/golang/go/blob/f2772a49353e09e4e00121ca4e538a3b3302a1de/src/reflect/type.go#L97

And the issue is that ConvertibleTo requires tags for all fields to be exactly the same:
https://github.com/golang/go/blob/f2772a49353e09e4e00121ca4e538a3b3302a1de/src/reflect/type.go#L1410

So we:
- either need to generate tags also for internal types
- review all usecases of ConvertibleTo in our code and change it to our custom code

I think the first one is much better.

@smarterclayton - thoughs?

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #23278

@smarterclayton @lavalamp

### CODE REVIEW

File: pkg/api/meta/meta.go [hunk 1]
```diff
@@ -321,16 +321,18 @@ func (resourceAccessor) SetResourceVersion(obj runtime.Object, version string) e
...
-	name            *string
-	generateName    *string
-	uid             *types.UID
-	apiVersion      *string
-	kind            *string
-	resourceVersion *string
-	selfLink        *string
-	labels          *map[string]string
-	annotations     *map[string]string
+	namespace         *string
```
Comment (lavalamp) [inline pkg/api/meta/meta.go]: Code paths that use this are slow, I seem to recall @smarterclayton going to some effort to prevent usage of this?

Comment (wojtek-t) [inline pkg/api/meta/meta.go]: I'm not explicitly calling genericAccessor anywhere. This is a fallback in case of non-internal object (for internal objects we will go to a different path).
So since in huge majority of cases it will be an internal object, we will not get here.
So this is WAI in my opinion (even though I'm changing it here).

**Comment by wojtek-t** [comment]
@smarterclayton - friendly ping

File: pkg/api/meta/meta.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/api/meta/meta.go]: We can implement the interface on external objects too if need be.  I'm wondering if we need a way to verify who is using external objects and where (something written to glog.v(5) whenever someone uses a metadata accessor on an external type)?

**Comment by smarterclayton** [comment]
Just the one question, otherwise LGTM.

**Comment by wojtek-t** [comment]
@smarterclayton - sorry - I was flying to US yesterday and didn't have time to fix this)
Will try to do this later today between meetings (adding this log should be pretty simple).

File: pkg/api/meta/meta.go (hunk 1 above)
Comment (wojtek-t) [inline pkg/api/meta/meta.go]: I added a log in Accessor() function in pkg/api/meta/meta.go

This is the place where we are creating genericAccessor, so I think this is the best place for it.

**Comment by wojtek-t** [comment]
@smarterclayton - comment applied

PTAL

**Comment by eparis** [comment]
I added the 'release-note' label so the bot I'm about to turn on won't get angry. If you do not believe this should be mentioned in the release notes please change the label to `release-note-none`
