### PR TITLE
rkt: Do not run rkt pod inside a pre-created netns when network plugin is no-op

### LINKED ISSUE #26540: rkt-coreos: can't create pod - invalid memory address or nil pointer dereference
I'm trying to create nginx pod

```yml
apiVersion: v1
kind: Pod
metadata:
  name: nginx22
  labels:
    name: nginx22
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
```

But i see errors in kubelet logs

```bash
journalctl -u kubelet
May 30 19:03:30 localhost kubelet[23446]: I0530 19:03:30.749428   23446 config.go:384] Receiving a new pod "nginx22_default(70b5ded4-2688-11e6-80f7-001e6776a094)"
May 30 19:03:30 localhost kubelet[23446]: I0530 19:03:30.749550   23446 kubelet.go:2604] SyncLoop (ADD, "api"): "nginx22_default(70b5ded4-2688-11e6-80f7-001e6776a094)"
May 30 19:03:30 localhost kubelet[23446]: I0530 19:03:30.749661   23446 kubelet.go:3591] Generating status for "nginx22_default(70b5ded4-2688-11e6-80f7-001e6776a094)"
May 30 19:03:30 localhost kubelet[23446]: I0530 19:03:30.750133   23446 secret.go:137] Setting up volume default-token-sr228 for pod 70b5ded4-2688-11e6-80f7-001e6776a094 at /var/lib/kubelet/pods/70b5ded4-2688-11e6-80f7-001e6776a094/volumes/kubernetes.io~secret/default-token-sr228
May 30 19:03:30 localhost kubelet[23446]: I0530 19:03:30.750286   23446 empty_dir.go:234] pod 70b5ded4-2688-11e6-80f7-001e6776a094: mounting tmpfs for volume wrapped_default-token-sr228 with opts [rootcontext="system_u:object_r:var_lib_t:s0"]
May 30 19:03:30 localhost kubelet[23446]: I0530 19:03:30.754423   23446 config.go:269] Setting pods for source api
May 30 19:03:30 localhost kubelet[23446]: I0530 19:03:30.754483   23446 secret.go:164] Received secret default/default-token-sr228 containing (3) pieces of data, 2220 total bytes
May 30 19:03:30 localhost kubelet[23446]: I0530 19:03:30.754425   23446 manager.go:422] Status for pod "nginx22_default(70b5ded4-2688-11e6-80f7-001e6776a094)" updated successfully: {status:{Phase:Pending Conditions:[{Type:Initialized Status:True LastProbeTime:{Time:{sec:0 nsec:0 loc:0x43b3b40}} LastTransitionTime:{Time:{sec:63600224610 nsec:0 loc:0x443fc40}} Reason: Message:} {Type:Ready Status:False LastProbeTime:{Time:{sec:0 nsec:0 loc:0x43b3b40}} LastTransitionTime:{Time:{sec:63600224610 nsec:0 loc:0x443fc40}} Reason:ContainersNotReady Message:containers with unready status: [nginx]} {Type:PodScheduled Status:True LastProbeTime:{Time:{sec:0 nsec:0 loc:0x43b3b40}} LastTransitionTime:{Time:{sec:63600224612 nsec:0 loc:0x443fc40}} Reason: Message:}] Message: Reason: HostIP:10.91.97.178 PodIP: StartTime:0xc821216fe0 InitContainerStatuses:[] ContainerStatuses:[{Name:nginx State:{Waiting:0xc821216fa0 Running:<nil> Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:nginx ImageID: ContainerID:}]} version:1 podName:nginx22 podNamespace:default}
May 30 19:03:30 localhost kubelet[23446]: I0530 19:03:30.754551   23446 atomic_writer.go:139] pod default/nginx22 volume default-token-sr228: write required for target directory /var/lib/kubelet/pods/70b5ded4-2688-11e6-80f7-001e6776a094/volumes/kubernetes.io~secret/default-token-sr228
May 30 19:03:30 localhost kubelet[23446]: I0530 19:03:30.754594   23446 kubelet.go:2617] SyncLoop (RECONCILE, "api"): "nginx22_default(70b5ded4-2688-11e6-80f7-001e6776a094)"
May 30 19:03:30 localhost kubelet[23446]: I0530 19:03:30.754654   23446 atomic_writer.go:154] pod default/nginx22 volume default-token-sr228: performed write of new data to ts data directory: /var/lib/kubelet/pods/70b5ded4-2688-11e6-80f7-001e6776a094/volumes/kubernetes.io~secret/default-token-sr228/..5985_30_05_19_03_30.932694936
May 30 19:03:30 localhost kubelet[23446]: I0530 19:03:30.754789   23446 rkt.go:1584] Container {Name:nginx Image:nginx Command:[] Args:[] WorkingDir: Ports:[{Name: HostPort:0 ContainerPort:80 Protocol:TCP HostIP:}] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-sr228 ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:Always SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
May 30 19:03:30 localhost kubelet[23446]: I0530 19:03:30.754824   23446 rkt.go:1150] Rkt starts to run pod: name "nginx22_default(70b5ded4-2688-11e6-80f7-001e6776a094)".
May 30 19:03:30 localhost kubelet[23446]: I0530 19:03:30.760264   23446 rkt.go:1127] Calling network plugin kubernetes.io/no-op to setup pod for nginx22_default(70b5ded4-2688-11e6-80f7-001e6776a094)
May 30 19:03:30 localhost kubelet[23446]: E0530 19:03:30.760377   23446 runtime.go:58] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
May 30 19:03:30 localhost kubelet[23446]: /var/lib/jenkins/workspace/kubernetes-build/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:52
May 30 19:03:30 localhost kubelet[23446]: /var/lib/jenkins/workspace/kubernetes-build/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/runtime/runtime.go:40
May 30 19:03:30 localhost kubelet[23446]: /usr/lib/go-1.6/src/runtime/asm_amd64.s:472
May 30 19:03:30 localhost kubelet[23446]: /usr/lib/go-1.6/src/runtime/panic.go:426
May 30 19:03:30 localhost kubelet[23446]: /usr/lib/go-1.6/src/runtime/panic.go:45
May 30 19:03:30 localhost kubelet[23446]: /usr/lib/go-1.6/src/runtime/sigpanic_unix.go:24
May 30 19:03:30 localhost kubelet[23446]: /var/lib/jenkins/workspace/kubernetes-build/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/rkt/rkt.go:1144
May 30 19:03:30 localhost kubelet[23446]: /var/lib/jenkins/workspace/kubernetes-build/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/rkt/rkt.go:1156
May 30 19:03:30 localhost kubelet[23446]: /var/lib/jenkins/workspace/kubernetes-build/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/rkt/rkt.go:1625
May 30 19:03:30 localhost kubelet[23446]: /var/lib/jenkins/workspace/kubernetes-build/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1900
May 30 19:03:30 localhost kubelet[23446]: /var/lib/jenkins/workspace/kubernetes-build/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:507
May 30 19:03:30 localhost kubelet[23446]: /var/lib/jenkins/workspace/kubernetes-build/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:171
May 30 19:03:30 localhost kubelet[23446]: /var/lib/jenkins/workspace/kubernetes-build/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:154
May 30 19:03:30 localhost kubelet[23446]: /var/lib/jenkins/workspace/kubernetes-build/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_workers.go:215
May 30 19:03:30 localhost kubelet[23446]: /usr/lib/go-1.6/src/runtime/asm_amd64.s:1998
May 30 19:03:30 localhost kubelet[23446]: I0530 19:03:30.823511   23446 rkt.go:1397] Rkt getting pods
May 30 19:03:30 localhost kubelet[23446]: W0530 19:03:30.827019   23446 rkt.go:1425] rkt: Cannot construct pod from unit file: pod is missing annotation io.kubernetes.pod.uid.

```

### PR DESCRIPTION
**Pull request by yifan-gu**
This fixed a panic where the returned pod network status is nil. (Fix #26540)

Also this makes lkvm stage1 able to run inside a user defined network, where the network name needs to be 'rkt.kubernetes.io'. A temporal solution to solve the network issue for lkvm stage1.

Besides, I fixed minor issues such as passing the wrong pod UID when cleaning up the netns file.

/cc @euank @pskrzyns @jellonek @kubernetes/sig-node 

I tested with no networkplugin locally, works fine. 

As a reminder, we need to document this in the release.https://github.com/kubernetes/kubernetes/issues/26201

### CODE REVIEW

**Comment by yifan-gu** [comment]
Going to e2e test this to make sure it doesn't cause regression.
@pskrzyns @jellonek feel free to cherry-pick and test the kvm-stage1, thank you!

**Comment by yifan-gu** [comment]
Will need to rebase after #26936

**Comment by yifan-gu** [comment]
Sorry, forgot to cc @dcbw who did the original work on this.

File: pkg/kubelet/rkt/rkt.go [hunk 1]
```diff
@@ -960,20 +971,27 @@ func (r *Runtime) generateRunCommand(pod *api.Pod, uuid, netnsName string) (stri
...
+		return nil
+	}
+
 	var teardownErr error
 	containerID := kubecontainer.ContainerID{ID: string(pod.UID)}
 	if err := r.networkPlugin.TearDownPod(pod.Namespace, pod.Name, containerID); err != nil {
 		teardownErr = fmt.Errorf("rkt: failed to tear down network for pod %s: %v", format.Pod(pod), err)
 	}
 
+	if r.networkPlugin.Name() == network.DefaultPluginName {
```
Comment (euank) [inline pkg/kubelet/rkt/rkt.go]: Duplicate check from 10 lines up.

Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: @euank Guess it's a safer practice :wink:

**Comment by yifan-gu** [comment]
e2e tests result seems sane
```
Summarizing 14 Failures:

[Fail] [k8s.io] Monitoring [It] should verify monitoring pods and all cluster nodes are available on influxdb using heapster. 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/monitoring.go:242

[Fail] [k8s.io] Services [It] should serve multiport endpoints from pods [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/service.go:1092

[Fail] [k8s.io] Pods [It] should not start app containers and fail the pod if init containers fail on a RestartNever pod 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:1006

[Fail] [k8s.io] DNS [It] should provide DNS for the cluster [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:204

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl run --rm job [It] should create a job from an image, then delete the job [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:1056

[Fail] [k8s.io] Kubectl client [k8s.io] Simple pod [It] should support inline execution and attach 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:359

[Fail] [k8s.io] Pods [It] should not start app containers if init containers fail on a RestartAlways pod 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:898

[Fail] [k8s.io] hostPath [It] should support subPath [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:1940

[Fail] [k8s.io] Pods [It] should invoke init containers on a RestartNever pod 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:710

[Fail] [k8s.io] DNS [It] should provide DNS for services [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/dns.go:204

[Fail] [k8s.io] Kubectl client [k8s.io] Kubectl cluster-info [It] should check if Kubernetes master services is included in cluster-info [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:480

[Fail] [k8s.io] Pods [It] should invoke init containers on a RestartAlways pod 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/pods.go:779

[Fail] [k8s.io] [HPA] Horizontal pod autoscaling (scale resource: CPU) [k8s.io] ReplicationController light [It] Should scale from 2 pods to 1 pod 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling_utils.go:284

[Fail] [k8s.io] [HPA] Horizontal pod autoscaling (scale resource: CPU) [k8s.io] ReplicationController light [It] Should scale from 1 pod to 2 pods 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling_utils.go:284

Ran 184 of 313 Specs in 1357.329 seconds
FAIL! -- 170 Passed | 14 Failed | 0 Pending | 129 Skipped 

Ginkgo ran 1 suite in 22m39.184721957s
```
(Note that most failures are init container tests)

File: pkg/kubelet/rkt/rkt.go [hunk 2]
```diff
@@ -920,10 +927,14 @@ func (r *Runtime) generateRunCommand(pod *api.Pod, uuid, netnsName string) (stri
 		runPrepared = append(runPrepared, "--no-overlay=true")
 	}
 
-	// Network namespace set up in kubelet; rkt networking not used
-	runPrepared = append(runPrepared, "--net=host")
+	// Apply '--net=host' to pod that is running on host network or inside a network namespace.
+	if kubecontainer.IsHostNetworkPod(pod) || r.networkPlugin.Name() != network.DefaultPluginName {
```
Comment (feiskyer) [inline pkg/kubelet/rkt/rkt.go]: A little question here. Does this means rkt running containers with `kubenet` network plugin in host network mode?

Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: @feiskyer So when `kubenet` or `cni` network plugin is used, we put `rkt run` in the netns created here. 
And the `rkt run` command itself does `rkt run --net=host`.

Comment (feiskyer) [inline pkg/kubelet/rkt/rkt.go]: @yifan-gu Thanks.

**Comment by pskrzyns** [comment]
@yifan-gu i checked and this fixes both https://github.com/kubernetes/kubernetes/issues/26081 and https://github.com/kubernetes/kubernetes/issues/26081. Thank you for fix

LGTM

File: pkg/kubelet/rkt/rkt.go (hunk 2 above)
Comment (dcbw) [inline pkg/kubelet/rkt/rkt.go]: There should really be a helper function for this since it (and its opposite) get used in so many places.

File: pkg/kubelet/rkt/rkt.go [hunk 3]
```diff
@@ -1543,16 +1574,9 @@ func (r *Runtime) KillPod(pod *api.Pod, runningPod kubecontainer.Pod, gracePerio
...
-		err := r.cleanupPodNetwork(&api.Pod{
-			ObjectMeta: api.ObjectMeta{
-				UID:       runningPod.ID,
-				Name:      runningPod.Name,
-				Namespace: runningPod.Namespace,
-			},
-		})
-		if err != nil {
+	// Clean up networking; use running pod details since 'pod' can be nil.
+	if pod != nil && !kubecontainer.IsHostNetworkPod(pod) {
```
Comment (dcbw) [inline pkg/kubelet/rkt/rkt.go]: Doens't this block ignore the comment just above?  'pod' can be nil here if a pod that's already been deleted from the API is now being cleaned up.  Shouldn't it be "if pod == nil"?  Also, cleanupPodNetworkFromServiceFile() already handles hostnetwork pods so we don't need that check.  Actually, I don't think we need any check here at all perhaps?  Just unconditionally do the cleanup.

Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: @dcbw good catch, thank you!

File: pkg/kubelet/rkt/rkt.go (hunk 2 above)
Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: @dcbw So there are 4 places:
```
kubecontainer.IsHostNetworkPod(pod) || r.networkPlugin.Name() != network.DefaultPluginName 

!kubecontainer.IsHostNetworkPod(pod) && r.networkPlugin.Name() != network.DefaultPluginName

kubecontainer.IsHostNetworkPod(pod) || r.networkPlugin.Name() == network.DefaultPluginName

kubecontainer.IsHostNetworkPod(pod) || r.networkPlugin.Name() == network.DefaultPluginName (same as above)

```

Not exactly the same or opposite. So I intend to keep there as they are.

Comment (euank) [inline pkg/kubelet/rkt/rkt.go]: It still captures the bottom three. I'm +1 on @dcbw's suggestion.

I think it's more readable with each of these becoming:

```
!isUsingRktNetwork || IsHostNetworkPod

!isUsingRktNetwork

isUsingRktNetwork

isUsingRktNetwork
```

where that helper function does the check of host network or default plugin.

Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: OK.

**Comment by yifan-gu** [comment]
Updated to address @dcbw @eunak 's comments.

File: pkg/kubelet/rkt/rkt.go [hunk 4]
```diff
@@ -1139,7 +1175,16 @@ func netnsPathFromName(netnsName string) string {
 // configured NetworkPlugin's setup function on it.
 // It returns the namespace name, configured IP (if available), and an error if
 // one occured.
+//
+// If the pod is running in host network or is running using the no-op plugin, then nothing will be done.
 func (r *Runtime) setupPodNetwork(pod *api.Pod) (string, string, error) {
+	glog.V(3).Infof("Calling network plugin %s to set up pod for %s", r.networkPlugin.Name(), format.Pod(pod))
```
Comment (euank) [inline pkg/kubelet/rkt/rkt.go]: nit, this log might make more sense after the noop check. Same for cleanup above.

File: pkg/kubelet/rkt/rkt.go [hunk 5]
```diff
@@ -2142,10 +2196,26 @@ func (r *Runtime) GetPodStatus(uid kubetypes.UID, name, namespace string) (*kube
 		}
 	}
 
-	// TODO(euank): this will not work in host networking mode
-	containerID := kubecontainer.ContainerID{ID: string(uid)}
-	if status, err := r.networkPlugin.GetPodNetworkStatus(namespace, name, containerID); err == nil {
-		podStatus.IP = status.IP.String()
+	// If we are running no-op network plugin, then get the pod IP from the rkt pod status.
+	if r.networkPlugin.Name() == network.DefaultPluginName {
```
Comment (euank) [inline pkg/kubelet/rkt/rkt.go]: This means that a host-network pod with a network plugin will still run `GetPodNetworkStatus` below even though we don't have a namespace, right?
That doesn't seem like the right behavior.

File: pkg/kubelet/rkt/rkt.go (hunk 4 above)
Comment (yifan-gu) [inline pkg/kubelet/rkt/rkt.go]: @euank I don't think showing the noop plugin really hurts?

Comment (euank) [inline pkg/kubelet/rkt/rkt.go]: I'm fine with either way. No problem.

**Comment by euank** [comment]
LGTM

**Comment by yifan-gu** [comment]
I am running e2e against this PR to make sure this works fine.

**Comment by yifan-gu** [comment]
E2E results are the same as https://github.com/kubernetes/kubernetes/pull/27015#issuecomment-224464915

**Comment by yifan-gu** [comment]
Rebased.
