### PR TITLE
federation-controller/clustercontroller: fix race when updating data

### LINKED ISSUE #49958: concurrent map writes by federation ClusterController
seen in https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/49919/pull-kubernetes-unit/44052/artifacts/junit_4c222743672c1e0f5982cb84c150211a71c8abdf_20170801-145439.stdout

```
fatal error: concurrent map writes

goroutine 1061 [running]:
runtime.throw(0x3a5abae, 0x15)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc427f4d308 sp=0xc427f4d2e8
runtime.mapassign(0x338bc60, 0xc4216f0c90, 0xc427f4d8b0, 0x0)
	/usr/local/go/src/runtime/hashmap.go:499 +0x667 fp=0xc427f4d3a8 sp=0xc427f4d308
k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterController).addToClusterSet(0xc42153c370, 0x39d6d20, 0xc427f4d890)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:121 +0x215 fp=0xc427f4d440 sp=0xc427f4d3a8
k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterController).UpdateClusterStatus(0xc42153c370, 0xc427f4de98, 0x18)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:168 +0xf07 fp=0xc427f4de40 sp=0xc427f4d440
k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterController).Run.func1()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:130 +0x2e fp=0xc427f4de88 sp=0xc427f4de40
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc42100e8a0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e fp=0xc427f4dec0 sp=0xc427f4de88
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc42100e8a0, 0x3b9aca00, 0x0, 0x180001, 0xc423c7c240)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd fp=0xc427f4df90 sp=0xc427f4dec0
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc42100e8a0, 0x3b9aca00, 0xc423c7c240)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d fp=0xc427f4dfc8 sp=0xc427f4df90
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc427f4dfd0 sp=0xc427f4dfc8
created by k8s.io/kubernetes/federation/pkg/federation-controller/cluster.(*ClusterController).Run
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/federation/pkg/federation-controller/cluster/clustercontroller.go:133 +0xfc
```

### PR DESCRIPTION
**Pull request by dqminh**
Fix #49958

Updates for ClusterController's maps were made without locking which can lead
to race conditions.

This change adds a RWMutex to protect the data. We lock and unlock them
whenever the data is accessed to make sure that we dont slow down too much

### CODE REVIEW

File: federation/pkg/federation-controller/cluster/clustercontroller_test.go [hunk 1]
```diff
@@ -150,3 +150,46 @@ func TestUpdateClusterStatusOK(t *testing.T) {
...
+
+	manager := newClusterController(federationClientSet, 5)
+
+	go func() {
+		for {
+			manager.UpdateClusterStatus()
+		}
+	}()
+
+	for i := 0; i < 42; i++ {
```
Comment (madhusudancs) [inline federation/pkg/federation-controller/cluster/clustercontroller_test.go]: 42 times in a unit test seems excessive. Can you please reduce this?

Comment (dqminh) [inline federation/pkg/federation-controller/cluster/clustercontroller_test.go]: reduce to 10. I think that would suffice.

**Comment by quinton-hoole** [comment]
Thanks @dqminh !
The PR looks good to me, although I have not done a thorough review.  @madhusudancs Is your review complete?  If so I will approve.

**Comment by madhusudancs** [comment]
@quinton-hoole yeah

/lgtm
/approve

**Comment by madhusudancs** [comment]
@k8s-bot ok to test
