### PR TITLE
CSI: Modify VolumeAttachment check to use Informer/Cache 

### LINKED ISSUE #84169: CSI VolumeAttachment slows pod startup time as # concurrent attaches increases
**What happened**:

A reporter testing their CSI driver at scale noticed issues:

Specifically they reported that the pod startup time is impacted by the number of concurrent CSI volume attachments in progress across a cluster.

According to the reporter, the pod start up time jumps from order of seconds (when there are a few volume attachments happening concurrently), to 1-2 minutes once there are >1300 concurrent volume attachments for pods using those attachments.

Similarly the reporter indicates that volume detach operations jump from order of seconds (when there are a few volume attach/detach operations happening concurrently), to 3-4 minutes once there are >1300 concurrent volume attachments.

The reporter mentioned that the slowness, once it is encountered, does not go away until the number of concurrent volume attaches is reduced below <500.

**What you expected to happen**:

Ideally, as the number of CSI volume attachments started in parallel increases the time it takes to start pods remains constant. We should identify the bottle necks and remove as many as possible.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

/sig storage
/sig scalability
/priority important-soon
CC @msau42

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by yuga711**
Change-Id: Ie70c8b6657c67eefbf13042f36d56ca84a2e42bb

**What type of PR is this?**
> /kind bug

**What this PR does / why we need it**:
Currently, for every attachedVolume, the CSI plugin in k8s requests API-server to fetch VolumeAttachement object (at a rate default 1 min interval). This is slow and also keeps the API server too busy serving these requests especially when there are 100's/1000's of volume in the cluster. 
The change here modifies the volumeAttachment check logic to use the the event based Infomers/listers. 

**Which issue(s) this PR fixes**:
Fixes #84169

**Special notes for your reviewer**:
The change was tested through a host-path CSI driver with 100 pods/PVCs. Verified the volumeAttachment checks are serviced faster. 

**Does this PR introduce a user-facing change?**:
NONE

```release-note
Fixes CSI volume attachment scaling issue by using informers.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by msau42** [comment]
There's a build failure in the test:
```
/b/f/w/pkg/volume/testing/testing.go:120:5: cannot use &fakeVolumeHost literal (type *fakeVolumeHost) as type volume.AttachDetachVolumeHost in assignment:
	*fakeVolumeHost does not implement volume.AttachDetachVolumeHost (missing VolumeAttachmentLister method)
```

**Comment by yuga711** [comment]
Some test failures here are due to fakeVolumeHost has not implemented a new method. Will fix it.

**Comment by humblec** [comment]
@yuga711 can you please share ,  how many volumes we tried to scale here to validate the fix ? I understand we did it against hostpath, but appreciated if you can share the details. Regardless the event based informers/listers.

File: pkg/controller/volume/attachdetach/reconciler/reconciler.go [hunk 1]
```diff
@@ -129,6 +129,9 @@ func (rc *reconciler) updateSyncTime() {
 	rc.timeOfLastSync = time.Now()
 }
 
+// This path seems to be issuing bulk-verify, but, the csi- logic is verifying one at a time?
```
Comment (humblec) [inline pkg/controller/volume/attachdetach/reconciler/reconciler.go:132]: iic, sequential processing after bulk verify is the behaviour as mentioned here https://github.com/kubernetes/kubernetes/issues/84169#issuecomment-545692734

File: pkg/volume/csi/csi_attacher.go [hunk 2]
```diff
@@ -197,8 +201,14 @@ func (c *csiAttacher) VolumesAreAttached(specs []*volume.Spec, nodeName types.No
 		}
 
 		attachID := getAttachmentName(volumeHandle, driverName, string(nodeName))
+		attach, err := c.plugin.volumeAttachmentLister.Get(attachID)
+		if (err == nil) {
```
Comment (humblec) [inline pkg/volume/csi/csi_attacher.go:205]: nit: we could avoid `( ..)` around this check :)

**Comment by yuga711** [comment]
> @yuga711 can you please share , how many volumes we tried to scale here to validate the fix ? I understand we did it against hostpath, but appreciated if you can share the details. Regardless, the event based informers/listers should improve the situation for sure.

Updated the PR description. In my testing, used 100 hostpath volumes.

File: pkg/controller/volume/attachdetach/reconciler/reconciler.go (hunk 1 above)
Comment (yuga711) [reply pkg/controller/volume/attachdetach/reconciler/reconciler.go]: Ack, thanks.

File: pkg/volume/csi/csi_attacher.go (hunk 2 above)
Comment (yuga711) [reply pkg/volume/csi/csi_attacher.go]: Done.

File: pkg/volume/csi/csi_attacher.go [hunk 3]
```diff
@@ -169,6 +169,10 @@ func (c *csiAttacher) waitForVolumeAttachmentInternal(volumeHandle, attachID str
 func (c *csiAttacher) VolumesAreAttached(specs []*volume.Spec, nodeName types.NodeName) (map[*volume.Spec]bool, error) {
 	klog.V(4).Info(log("probing attachment status for %d volume(s) ", len(specs)))
 
+	if c.plugin.volumeAttachmentLister == nil {
```
Comment (RaunakShah) [inline pkg/volume/csi/csi_attacher.go:172]: Any reason why this can't fall back on querying the API server if `c.plugin.volumeAttachmentLister` is nil?

File: pkg/volume/csi/csi_attacher.go [hunk 4]
```diff
@@ -197,8 +201,14 @@ func (c *csiAttacher) VolumesAreAttached(specs []*volume.Spec, nodeName types.No
 		}
 
 		attachID := getAttachmentName(volumeHandle, driverName, string(nodeName))
+		attach, err := c.plugin.volumeAttachmentLister.Get(attachID)
+		if err == nil {
```
Comment (RaunakShah) [inline pkg/volume/csi/csi_attacher.go:205]: How about changing this to `if err != nil ...` and moving the entire block of querying the API server inside that? That also unifies how `attached[spec]` is assigned and logging.

File: pkg/volume/csi/csi_attacher.go [hunk 5]
```diff
@@ -197,8 +201,14 @@ func (c *csiAttacher) VolumesAreAttached(specs []*volume.Spec, nodeName types.No
...
+			attached[spec] = attach.Status.Attached
+			continue
+		}
+		// volumeAttachment object is not found in the cache, get from the API server
 		klog.V(4).Info(log("probing attachment status for VolumeAttachment %v", attachID))
```
Comment (RaunakShah) [inline pkg/volume/csi/csi_attacher.go:210]: Can this log be moved to line 204?

**Comment by xing-yang** [comment]
Hi @yuga711, can you take a look of the CI failures?

File: pkg/volume/csi/csi_attacher.go (hunk 3 above)
Comment (yuga711) [reply pkg/volume/csi/csi_attacher.go:172]: Ack

File: pkg/volume/csi/csi_attacher.go (hunk 4 above)
Comment (yuga711) [reply pkg/volume/csi/csi_attacher.go:205]: did some refactoring here.

File: pkg/volume/csi/csi_attacher.go (hunk 5 above)
Comment (yuga711) [reply pkg/volume/csi/csi_attacher.go:210]: did some refactoring here.

**Comment by yuga711** [comment]
@xing-yang, Yes, have looked at the failure. I don't have a root cause yet. Planning to analyze again.
Really appreciate if anyone has leads looking at the failure and the code change.

**Comment by msau42** [comment]
verify job is failing due to gofmt
integration job is failing volume attach/detach tests, which seems related

File: pkg/volume/csi/csi_attacher.go [hunk 6]
```diff
@@ -197,8 +197,18 @@ func (c *csiAttacher) VolumesAreAttached(specs []*volume.Spec, nodeName types.No
 		}
 
 		attachID := getAttachmentName(volumeHandle, driverName, string(nodeName))
+		var attach *storage.VolumeAttachment
+		if c.plugin.volumeAttachmentLister != nil {
```
Comment (msau42) [inline pkg/volume/csi/csi_attacher.go:201]: Is the only time this is nil in unit tests?

File: pkg/volume/csi/csi_attacher.go [hunk 7]
```diff
@@ -197,8 +197,18 @@ func (c *csiAttacher) VolumesAreAttached(specs []*volume.Spec, nodeName types.No
...
+			attach, err = c.plugin.volumeAttachmentLister.Get(attachID)
+			if err == nil {
+				attached[spec] = attach.Status.Attached
+				continue
+			}
```
Comment (msau42) [inline pkg/volume/csi/csi_attacher.go:206]: Should we log the error?

File: pkg/volume/csi/csi_attacher.go [hunk 8]
```diff
@@ -197,8 +197,18 @@ func (c *csiAttacher) VolumesAreAttached(specs []*volume.Spec, nodeName types.No
...
+		}
+		// The cache lookup is not setup or the object is not found in the cache.
+		// Get the object from the API server.
 		klog.V(4).Info(log("probing attachment status for VolumeAttachment %v", attachID))
-		attach, err := c.k8s.StorageV1().VolumeAttachments().Get(context.TODO(), attachID, meta.GetOptions{})
+		attach, err = c.k8s.StorageV1().VolumeAttachments().Get(context.TODO(), attachID, meta.GetOptions{})
 		if err != nil {
```
Comment (msau42) [inline pkg/volume/csi/csi_attacher.go:212]: This isn't related to your change but I wonder if this logic is correct. If apiserver is temporarily down, then we mark the volume as detached? cc @jsafrane

File: pkg/volume/csi/csi_attacher.go [hunk 9]
```diff
@@ -197,8 +197,18 @@ func (c *csiAttacher) VolumesAreAttached(specs []*volume.Spec, nodeName types.No
 		}
 
 		attachID := getAttachmentName(volumeHandle, driverName, string(nodeName))
+		var attach *storage.VolumeAttachment
+		if c.plugin.volumeAttachmentLister != nil {
+			attach, err = c.plugin.volumeAttachmentLister.Get(attachID)
+			if err == nil {
+				attached[spec] = attach.Status.Attached
```
Comment (msau42) [inline pkg/volume/csi/csi_attacher.go:204]: From the discussion in https://github.com/kubernetes-csi/external-attacher/issues/215#issuecomment-601065201, we should only use the absence of the VolumeAttachment object to indicate that the volume is detached. If the `status.attached` is false, that could mean that we're in the process of attaching, and we probably don't want to mark it as detached here.  Same with L218.

Do we want to make the change in this PR or separately? 

Also can potentially be investigated separately, but is it possible to have a race where we're starting to Attach, but haven't created the VolumeAttachment object yet? Then this comes along and marks it as detached? AFIAK, the Attach operartion is launched as a separate go routine and we don't wait for it to complete before coming here.

cc @jsafrane

File: pkg/volume/csi/csi_attacher_test.go [hunk 10]
```diff
@@ -1559,6 +1559,7 @@ func newTestWatchPlugin(t *testing.T, fakeClient *fakeclient.Clientset) (*csiPlu
 		ProbeVolumePlugins(),
 		"fakeNode",
 		csiDriverLister,
+		nil,
```
Comment (msau42) [inline pkg/volume/csi/csi_attacher_test.go:1562]: Can you open another issue to track updating these unit tests to be able to work with informers?

File: pkg/volume/csi/csi_attacher.go (hunk 9 above)
Comment (jsafrane) [reply pkg/volume/csi/csi_attacher.go:204]: I think A/D controller calls `VolumesAreAttached` for volumes that are marked as attached. So in the worst case, A/D controller starts detach + `VolumesAreAttached` in parallel and `VolumesAreAttached` can mark the volume as detached earlier than `Detach()` would do.

Is it possible to attach, VolumesAreAttached, detach, attach a volume so quickly that the second attach succeeds before VolumesAreAttached evaluates the old attachment and considers it detached? As consequence, Attach would be called again and it succeeds immediately.

File: pkg/volume/csi/csi_attacher.go (hunk 7 above)
Comment (jsafrane) [reply pkg/volume/csi/csi_attacher.go:206]: Please handle NotFound error here - such volume is detached and we don't need logging (or we can use less serious logging level).

File: pkg/volume/csi/csi_attacher_test.go (hunk 10 above)
Comment (yuga711) [reply pkg/volume/csi/csi_attacher_test.go:1562]: Done. [Issue#91784](https://github.com/kubernetes/kubernetes/issues/91784)

File: pkg/volume/csi/csi_attacher.go (hunk 8 above)
Comment (jsafrane) [reply pkg/volume/csi/csi_attacher.go:212]: Yes, it looks suspicious. `NotFound` should be handled, because only that means the volume is detached. Any other error does not mean anything.

File: pkg/volume/csi/csi_attacher.go (hunk 6 above)
Comment (liggitt) [reply pkg/volume/csi/csi_attacher.go:201]: adding different test-only code paths doesn't seem like a good idea, especially if it makes unit tests behave significantly differently than real runs

File: pkg/volume/csi/csi_attacher.go [hunk 11]
```diff
@@ -197,8 +197,18 @@ func (c *csiAttacher) VolumesAreAttached(specs []*volume.Spec, nodeName types.No
...
+				continue
+			}
+		}
+		// The cache lookup is not setup or the object is not found in the cache.
+		// Get the object from the API server.
 		klog.V(4).Info(log("probing attachment status for VolumeAttachment %v", attachID))
-		attach, err := c.k8s.StorageV1().VolumeAttachments().Get(context.TODO(), attachID, meta.GetOptions{})
+		attach, err = c.k8s.StorageV1().VolumeAttachments().Get(context.TODO(), attachID, meta.GetOptions{})
```
Comment (liggitt) [inline pkg/volume/csi/csi_attacher.go:211]: are there any correctness implications if we get a stale attachment object here from the informer?

**Comment by saad-ali** [comment]
This is fine for a stop gap solution. Defaulting logic looks fine since reconciler will fix it self if volume is incorrectly thought to be not attached. And agreed with @msau42 that there is a potential race here. We should do a follow up 1) modifying the entire A/D controller to use the informer (for correctness), and 2) consider passing the informers as parameters to `Attach()`, etc. rather than `VolumeHost`(cleanup).

**Comment by msau42** [comment]
storage-slow timeout is being tracked by https://github.com/kubernetes/kubernetes/issues/92045

**Comment by yuga711** [comment]
@xing-yang was removed due to rebase. PTAL. Thanks.
@mikedanese - PTAL on kube-controller-manager changes. Thanks.

File: pkg/volume/csi/csi_plugin.go [hunk 12]
```diff
@@ -186,20 +187,26 @@ func (p *csiPlugin) Init(host volume.VolumeHost) error {
...
+		// set CSIDriverLister and volumeAttachmentLister
 		adcHost, ok := host.(volume.AttachDetachVolumeHost)
 		if ok {
 			p.csiDriverLister = adcHost.CSIDriverLister()
 			if p.csiDriverLister == nil {
 				klog.Error(log("CSIDriverLister not found on AttachDetachVolumeHost"))
 			}
+			p.volumeAttachmentLister = adcHost.VolumeAttachmentLister()
+			if p.volumeAttachmentLister == nil {
+				klog.Error(log("VolumeAttachmentLister not found on AttachDetachVolumeHost"))
```
[the remark this answers is not in the document]
Comment (jingxu97) [reply pkg/volume/csi/csi_plugin.go:199]: is this addressed

[the remark this answers is not in the document]
Comment (yuga711) [reply pkg/volume/csi/csi_plugin.go:199]: @jingxu97 Its not changed yet. Just to understand, did you encounter an issue or a failure with this?

[the remark this answers is not in the document]
Comment (jingxu97) [reply pkg/volume/csi/csi_plugin.go:199]: no, I just happen to check some changes in this area, and want to verify.
