### PR TITLE
Fix default scheduler crash if scheduler extender filter returns a not found node

### LINKED ISSUE #79640: Default scheduler crash if scheduler extender filter returns a not found node
**What happened**:
Default scheduler crash if scheduler extender filter returns a not found node

**What you expected to happen**:
Default scheduler just should consider the not found node as not an candidate, instead of crash itself (panic).

**How to reproduce it (as minimally and precisely as possible)**:
1. The cluster only have 1 node: 0.0.0.1
2. One scheduler extender (with nodeCacheCapable enabled) filter accidentally returns a candidate node: 0.0.0.2
3. Default scheduler recieved the candidate nodes: 0.0.0.2 from scheduler extender, but got below error:
```
I0702 03:17:12.628810       1 scheduler.go:453] Attempting to schedule pod: default/scheduler-test-77
I0702 03:17:13.253047       1 trace.go:81] Trace[1695146606]: "Scheduling default/scheduler-test-77" (started: 2019-07-02 03:17:12.6288148 +0000 UTC m=+18.926347501) (total time: 624.1957ms):
Trace[1695146606]: [47.6µs] [47.6µs] Computing predicates
Trace[1695146606]: [624.1802ms] [624.1326ms] Prioritizing
Trace[1695146606]: [624.1957ms] [15.5µs] END
E0702 03:17:13.253123       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/core/generic_scheduler.go:208
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/scheduler.go:278
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/scheduler/scheduler.go:457
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:1337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x3ced5f9]
```

The generic_scheduler.go:208 is SuggestedHost:  filteredNodes[0].Name:
```
	// When only one node after predicate, just use it.
	if len(filteredNodes) == 1 {
		metrics.SchedulingAlgorithmPriorityEvaluationDuration.Observe(metrics.SinceInSeconds(startPriorityEvalTime))
		metrics.DeprecatedSchedulingAlgorithmPriorityEvaluationDuration.Observe(metrics.SinceInMicroseconds(startPriorityEvalTime))
		return ScheduleResult{
			SuggestedHost:  filteredNodes[0].Name,
			EvaluatedNodes: 1 + len(failedPredicateMap),
			FeasibleNodes:  1,
		}, nil
	}
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by yqwang-ms**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
See issue #79640

**Which issue(s) this PR fixes**:

Fixes #79640

**Special notes for your reviewer**:
In future, we may should further improve the default scheduler tolerance to scheduler extender.

**Does this PR introduce a user-facing change?**:

```release-note
If scheduler extender filtered a not found node, current scheduling round for this pod will just be skipped.

```

### CODE REVIEW

File: pkg/scheduler/core/extender.go [hunk 1]
```diff
@@ -299,8 +299,14 @@ func (h *HTTPExtender) Filter(
 
 	if h.nodeCacheCapable && result.NodeNames != nil {
 		nodeResult = make([]*v1.Node, 0, len(*result.NodeNames))
-		for i := range *result.NodeNames {
-			nodeResult = append(nodeResult, nodeNameToInfo[(*result.NodeNames)[i]].Node())
+		for _, nodeName := range *result.NodeNames {
+			if node, ok := nodeNameToInfo[nodeName]; ok {
+				nodeResult = append(nodeResult, node.Node())
+			} else {
+				result.FailedNodes[nodeName] = fmt.Sprintf(
```
Comment (hex108) [inline pkg/scheduler/core/extender.go]: From the issue #79640, it seems that it is because the scheduler extender returns a node wrongly and the node is not passed by scheduler. It might be enough to add a log for it?

Comment (yqwang-ms) [reply pkg/scheduler/core/extender.go]: I also try to just add log for it, but by convension, seems no log is used in extender.go. 
So, I turn to return it as a failed node, which can also be easily exposed to users, that why extender returned candidates is skipped.

Comment (yqwang-ms) [reply pkg/scheduler/core/extender.go]: I also saw other simliar practice in this file, such as:
https://github.com/kubernetes/kubernetes/blob/b893a64b0e68d11db5959d5dd03af774ad3f02a3/pkg/scheduler/core/extender.go#L203

But it is for preemption, that needs all victims on a selected node to be preempted, so just return error is an easy way.
For filter, we can improve it by still picking other vaild candidates, because any one would be feasiable.

Comment (yqwang-ms) [reply pkg/scheduler/core/extender.go]: Hi @hex108 any suggestions? :)

Comment (hex108) [reply pkg/scheduler/core/extender.go]: `FailedNodes` will be displayed to users, and it is a little confused to display a node that does not exist. I think we need print the error message and fix it if there's cache inconsistency between default scheduler and extender.

For the `preemption`, it returns a error, and just log it finally at https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go#L307.

Comment (yqwang-ms) [reply pkg/scheduler/core/extender.go]: Thanks @hex108 
I updated the PR, please check again.
BTW, I found the preempt error is not logged acutally, so also fixed it.

**Review by hex108 — APPROVED** [review]
/lgtm

Could you please help squash the commits?

**Comment by yqwang-ms** [comment]
I am not authorized to merge this pull request, @hex108  could you please help to click the "squash and  merge" button? Such as
image

**Comment by hex108** [comment]
> I am not authorized to merge this pull request, @hex108 could you please help to click the "squash and merge" button? Such as
> image

You could squash the commits in your local machine and force push it to remote.

**Comment by yqwang-ms** [comment]
Thanks for the info, @hex108  ,I have force pushed, please check :)

**Comment by hex108** [comment]
/lgtm

Thanks!

**Comment by yqwang-ms** [comment]
Hi @Huang-Wei @k82cn could you please take a look at this small fix? Thanks!

**Comment by yqwang-ms** [comment]
Hi @hex108, I am not familar with the K8S PR process, could you please tell me what should I do to continue push this PR to approve?

**Comment by hex108** [comment]
> Hi @hex108, I am not familar with the K8S PR process, could you please tell me what should I do to continue push this PR to approve?

Wait for one of the approvers for approve. :)

**Comment by yqwang-ms** [comment]
Great! Thanks!

**Comment by yqwang-ms** [comment]
Hi @Huang-Wei @k82cn could you please take a look at this small fix when you free? :)
Or could you please tell me what should I do next?
Thanks again!

File: pkg/scheduler/core/extender.go [hunk 2]
```diff
@@ -299,8 +301,14 @@ func (h *HTTPExtender) Filter(
 
 	if h.nodeCacheCapable && result.NodeNames != nil {
 		nodeResult = make([]*v1.Node, 0, len(*result.NodeNames))
-		for i := range *result.NodeNames {
-			nodeResult = append(nodeResult, nodeNameToInfo[(*result.NodeNames)[i]].Node())
+		for _, nodeName := range *result.NodeNames {
```
Comment (goodluckbot) [inline pkg/scheduler/core/extender.go]: Got a few questions
1) If we have a few nodes returned by the extender and only one of them is not in the nodeNameToInfo map, will we want to return an error , or will we log the node and return the rest ?
2) when will the extender return a node not in the nodeNameToInfo map ?

Comment (yqwang-ms) [reply pkg/scheduler/core/extender.go]: @goodluckbot first thanks review :), let me explain one by one:

1. In the first stage, I think we can just return an error, and expect the inconsistency should can be reconciled by the extender.

- It is already much better than crash itself, then backoff retry which hurt the whole cluster.

- Besides, the rest filttered nodes may be also inconsistent (outdated compared with default scheduler), so just return an error is the most safe way.

- And even if we just return the rest, just logging is not enough, we need to tell outside (end user and extender) that "the default scheduler does not fully respect your descion, please aware."

   So, it seems need more things to do to be perfect, I perfer keep **improving** this in future PR, instead of inside this **hotfix** PR.

2. Basically, we should not make assumption on what result extender will return, because extender is not offical k8s code. And one k8s can run multiple extenders plus default scheduler, if one extender behaves badly (such as its code has some bugs), k8s should just ignore it, instead of crash the whole k8s itself.

Comment (goodluckbot) [reply pkg/scheduler/core/extender.go]: thanks @yqwang-ms  :)

File: pkg/scheduler/core/extender.go [hunk 3]
```diff
@@ -299,8 +301,14 @@ func (h *HTTPExtender) Filter(
...
+			if node, ok := nodeNameToInfo[nodeName]; ok {
+				nodeResult = append(nodeResult, node.Node())
```
Comment (Huang-Wei) [inline pkg/scheduler/core/extender.go]: With this PR, `len(nodeResult)` is not necessarily the same as `len(*result.NodeNames)`, so it'd good to change L303 to `nodeResult = make([]*v1.Node)`.

File: pkg/scheduler/core/extender.go [hunk 4]
```diff
@@ -299,8 +301,14 @@ func (h *HTTPExtender) Filter(
...
+			} else {
+				return nil, nil, fmt.Errorf(
+					"extender: %v claims a filtered node: %v but the node is not found in nodeNameToInfo map",
```
Comment (Huang-Wei) [inline pkg/scheduler/core/extender.go]:
```suggestion
					"extender %q claims a filtered node %q which is not found in nodeNameToInfo map",
```

File: pkg/scheduler/core/extender.go [hunk 5]
```diff
@@ -255,6 +255,8 @@ func convertToNodeNameToVictims(
 // Filter based on extender implemented predicate functions. The filtered list is
 // expected to be a subset of the supplied list. failedNodesMap optionally contains
 // the list of failed nodes and failure reasons.
+// It should return error if there's cache inconsistency between default scheduler and extender
+// so that some filtered nodes are missing from nodeNameToInfo.
```
Comment (Huang-Wei) [inline pkg/scheduler/core/extender.go]: We can just simply revise the paragraph to:

```
// Filter based on extender implemented predicate functions. The filtered list is
// expected to be a subset of the supplied list; otherwise the function returns an error.
// failedNodesMap optionally contains the list of failed nodes and failure reasons.
```

**Review by Huang-Wei — COMMENTED** [review]
Apologies for the late reply. Some comments below.

File: pkg/scheduler/core/extender.go (hunk 3 above)
Comment (yqwang-ms) [reply pkg/scheduler/core/extender.go]: NP, and thanks for your review. :)

For this comment, do you mean change to `nodeResult = make([]*v1.Node, 0)`, however, `len(nodeResult)` is **expected** to be the same as `len(*result.NodeNames)`, and in **common cases**, it is. Otherwise, it is a **rare** "exception", and we already returned an error for this.

So, **to optimize for most common cases**, we would better to still make a slice with an expect capacity for the following fast appending.

Is that ok?

File: pkg/scheduler/core/extender.go (hunk 4 above)
Comment (yqwang-ms) [reply pkg/scheduler/core/extender.go]: This is to align with preemption error message, do I also need to make simliar change for preemption code?  Such as:

```
		return nil, fmt.Errorf("extender: %v claims to preempt pod (UID: %v) on node: %v, but the pod is not found on that node",
			h.extenderURL, metaPod, nodeInfo.Node().Name)
	}

	return nil, fmt.Errorf("extender: %v claims to preempt on node: %v but the node is not found in nodeNameToInfo map",
```

File: pkg/scheduler/core/extender.go (hunk 5 above)
Comment (yqwang-ms) [reply pkg/scheduler/core/extender.go]: Thanks! Adjusted and pls check.

File: pkg/scheduler/core/extender.go (hunk 4 above)
Comment (Huang-Wei) [reply pkg/scheduler/core/extender.go]: That's fine. Just a nit.

File: pkg/scheduler/core/extender.go (hunk 3 above)
Comment (Huang-Wei) [reply pkg/scheduler/core/extender.go]: > For this comment, do you mean change to nodeResult = make([]*v1.Node, 0)

Yes, if the length is not fixed.

According to your comments that the length is fixed, and we return error upon mismatch. **_Technically_** we should do `nodeResult = make([]*v1.Node, len(*result.NodeNames))` to ensure `len` and `cap` inside the slice are the same, and use `nodeResult[i] = node.Node()`. (I recalled that I did a test and it showed a perf improvement).

Can you update the code, as well as L305 to L310, and make them squashed into one commit?

Comment (yqwang-ms) [reply pkg/scheduler/core/extender.go]: Thanks! Adjusted according to your suggestion, as well as L311 to L314, pls check
