### PR TITLE
kubectl: strict check for exec command

### LINKED ISSUE #1745: kubectl: check rule in exec command is insecurity
### What happened?

https://github.com/kubernetes/kubernetes/blob/b53b9fb5573323484af9a19cf3f5bfe80760abba/staging/src/k8s.io/kubectl/pkg/cmd/exec/exec.go#L208-L215

`kubectl exec -it resource asd asd asd -- bash` will be like `kubectl exec -it resource -- bash` but no error

This can lead to unexpected behavior of command with `--`

### What did you expect to happen?

raise error `error: exec [POD] [COMMAND] is not supported anymore.`

### How can we reproduce it (as minimally and precisely as possible)?

`kubectl exec -it resource asd asd asd -- bash`

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
v1.32.3
```

</details>

### Cloud provider

<details>
-
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by hunshcn**
kubectl: strict check for exec command

Re-open of #131353 which was closed due to inactivity.

Fix https://github.com/kubernetes/kubectl/issues/1745

The current implementation doesn't properly check for arguments between the resource name and the dash separator. This can lead to unexpected behavior when using commands like 'kubectl exec -it pod-0 bash -- run.sh', which should raise an error but doesn't.

This fix adds a check to ensure that when a dash separator (--) is used, there are no extra arguments between the resource name and the dash. If there are extra arguments, it will raise an error.

Changes:
- Only allow argsLenAtDash == 0 or == 1 (exactly one arg before --)
- Add test for extra args between pod and --
- Add test for flag-like args without dash separator

/kind bug

#### Does this PR introduce a user-facing change?
```release-note
Improve error reporting when invoking kubectl exec
```

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by ardaguclu** [comment]
Based on my analysis https://github.com/kubernetes/kubectl/issues/1745#issuecomment-3728575137, this will cause a regression and this command will not work anymore;

```
kubectl exec -it pod-test -c container-a -- echo "test"
```

Could you please add an integration test here https://github.com/kubernetes/kubernetes/blob/master/test/cmd/exec.sh to confirm that we keep the functionality.

**Comment by hunshcn** [comment]
@ardaguclu added

**Comment by ardaguclu** [comment]
/lgtm
/hold cancel
My previous assumption was wrong, there seems to be no problem here

File: test/cmd/exec.sh [hunk 1]
```diff
@@ -67,7 +67,27 @@ __EOF__
...
+spec:
+  containers:
+  - name: container-a
+    image: registry.k8s.io/pause:3.10.1
+  - name: container-b
+    image: registry.k8s.io/pause:3.10.1
+__EOF__
+
+  ### Test execute with pod and container before dash separator
+  output_message=$(! kubectl exec -it pod-test -c container-a -- echo "test" 2>&1)
```
Comment (ardaguclu) [inline test/cmd/exec.sh:84]: Why this has `!`?, don't we expect that this command execution succeed?

File: test/cmd/exec.sh [hunk 2]
```diff
@@ -67,7 +67,27 @@ __EOF__
...
+  kube::test::if_has_not_string "${output_message}" 'exec [POD] [COMMAND] is not supported anymore'
```
Comment (ardaguclu) [inline test/cmd/exec.sh]: I see the `if_has_not_string`s but shouldn't we also expect that succeeded `test` output?

File: test/cmd/exec.sh (hunk 1 above)
Comment (soltysh) [reply test/cmd/exec.sh:84]: This is known limitation (I doubt we have it written down anywhere 😭 ) of the current bash-based testing workflow. This allows us to ignore the error returned by kubectl in this case, without that, this line would terminate the test with an error.

File: test/cmd/exec.sh (hunk 2 above)
Comment (soltysh) [reply test/cmd/exec.sh]: Actually, this line isn't working as expected. I've tried this locally and when I change the kubectl invocation not to have `--`, like so: `kubectl exec -it pod-test -c container-a echo "test" 2>&1)` this then produced the expected error: 
```
error: exec [POD] [COMMAND] is not supported anymore. Use exec [POD] -- [COMMAND] instead See 'kubectl exec -h' for help and examples
```
but it wasn't properly caught by this test. That is because under the covers this function uses grep, and for grep to work correctly with special characters (like `[]`) in this case we need to escape them, with `\`. Currently grep treats `[POD]` as a regular expression matching a one a letter from that set. So the correct line should look like:
 

```suggestion
  kube::test::if_has_not_string "${output_message}" 'exec \[POD\] \[COMMAND\] is not supported anymore'
```

**Comment by soltysh** [comment]
/lgtm cancel
Once that one comment regarding tests is fixed @ardaguclu will tag the PR

**Comment by hunshcn** [comment]
done

**Comment by ardaguclu** [comment]
Thank you
/hold cancel
/lgtm
