### PR TITLE
kubelet: fix recording when pulling image did finish

### LINKED ISSUE #114903: pod_startup_latency_tracker doesn't track the lastFinishedPulling time
It can be observed in any kubelet log, just pick one from a random job in CI, per example

```sh
$ wget https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/114703/pull-kubernetes-e2e-gce/1608841379780235264/artifacts/e2e-022435249c-674b9-minion-group-gdj4/kubelet.log

$ grep tracker kubelet.log  | grep -v " firstStartedPulling=\"0001-01-01" | grep Observed
Dec 30 15:33:06.941831 e2e-022435249c-674b9-minion-group-gdj4 kubelet[8362]: I1230 15:33:06.941726    8362 pod_startup_latency_tracker.go:102] "Observed pod startup duration" pod="kube-system/metadata-proxy-v0.1-d59wc" podStartSLOduration=-9.223372025913092e+09 pod.CreationTimestamp="2022-12-30 15:32:56 +0000 UTC" firstStartedPulling="2022-12-30 15:32:58.409218371 +0000 UTC m=+2.180058389" lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC" observedRunningTime="2022-12-30 15:33:01.628463642 +0000 UTC m=+5.399303661" watchObservedRunningTime="2022-12-30 15:33:06.941684349 +0000 UTC m=+10.712524397"
Dec 30 15:33:13.374424 e2e-022435249c-674b9-minion-group-gdj4 kubelet[8362]: I1230 15:33:13.374400    8362 pod_startup_latency_tracker.go:102] "Observed pod startup duration" pod="kube-system/kube-dns-autoscaler-5f6455f985-n4pqn" podStartSLOduration=-9.223372017480421e+09 pod.CreationTimestamp="2022-12-30 15:32:54 +0000 UTC" firstStartedPulling="2022-12-30 15:33:07.759304457 +0000 UTC m=+11.530144475" lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC" observedRunningTime="2022-12-30 15:33:13.267182708 +0000 UTC m=+17.038022722" watchObservedRunningTime="2022-12-30 15:33:13.374355038 +0000 UTC m=+17.145195062"
Dec 30 15:33:13.375379 e2e-022435249c-674b9-minion-group-gdj4 kubelet[8362]: I1230 15:33:13.375359    8362 pod_startup_latency_tracker.go:102] "Observed pod startup duration" pod="kube-system/konnectivity-agent-gnc9k" podStartSLOduration=-9.223372029479458e+09 pod.CreationTimestamp="2022-12-30 15:33:06 +0000 UTC" firstStartedPulling="2022-12-30 15:33:09.258791695 +0000 UTC m=+13.029631711" lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC" observedRunningTime="2022-12-30 15:33:13.375009262 +0000 UTC m=+17.145849275" watchObservedRunningTime="2022-12-30 15:33:13.375317944 +0000 UTC m=+17.146157970"
```

The `lastFinishedPulling` time is always `0001-01-01 00:00:00 +0000`, that is the golang zero time IIRC.
In addition, when the image is already present, neither `firstStartedPulling` and `lastFinishedPulling` are set.

I think that the fix has to be something like this

```diff
diff --git a/pkg/kubelet/images/image_manager.go b/pkg/kubelet/images/image_manager.go
index 3fbec1f2b56..863e8ccfa98 100644
--- a/pkg/kubelet/images/image_manager.go
+++ b/pkg/kubelet/images/image_manager.go
@@ -134,6 +134,8 @@ func (m *imageManager) EnsureImageExists(ctx context.Context, pod *v1.Pod, conta
        if !shouldPullImage(container, present) {
                if present {
                        msg := fmt.Sprintf("Container image %q already present on machine", container.Image)
+                       m.podPullingTimeRecorder.RecordImageStartedPulling(pod.UID)
+                       m.podPullingTimeRecorder.RecordImageFinishedPulling(pod.UID)
                        m.logIt(ref, v1.EventTypeNormal, events.PulledImage, logPrefix, msg, klog.Info)
                        return imageRef, "", nil
                }
@@ -164,6 +166,7 @@ func (m *imageManager) EnsureImageExists(ctx context.Context, pod *v1.Pod, conta
 
                return "", imagePullResult.err.Error(), ErrImagePull
        }
+       m.podPullingTimeRecorder.RecordImageFinishedPulling(pod.UID)
```

but this means that we are lacking testing on these, feature, I'd expected to see at least 2 new tests in

`pkg/kubelet/util/pod_startup_latency_tracker_test.go`
`pkg/kubelet/images/image_manager_test.go`

/sig node
/kind bug
/help

/cc @bobbypage @azylinski

### PR DESCRIPTION
**Pull request by tmilox**
Signed-off-by: TommyStarK <thomasmilox@gmail.com>

#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Kubelet image manager wasn't recording when pulling the image did finish, it is now available for the pod_startup_latency_tracker.

#### Which issue(s) this PR fixes:

Fixes #114903 

#### Does this PR introduce a user-facing change?

```release-note
kubelet: fix recording issue when pulling image did finish
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by TommyStarK** [comment]
cc @aojea, a first draft to address the issue #114903, any feedback will be greatly appreciated (If you feel the approach is too naive please dont hesitate to tell me if you had something else in mind)

File: pkg/kubelet/images/image_manager_test.go [hunk 1]
```diff
@@ -153,20 +155,32 @@ func pullerTestCases() []pullerTestCase {
...
+	m.startedPullingRecorded = true
+}
 
-func (m *mockPodPullingTimeRecorder) RecordImageStartedPulling(podUID types.UID) {}
+func (m *mockPodPullingTimeRecorder) RecordImageFinishedPulling(podUID types.UID) {
+	m.finishedPullingRecorded = true
+}
 
-func (m *mockPodPullingTimeRecorder) RecordImageFinishedPulling(podUID types.UID) {}
+func (m *mockPodPullingTimeRecorder) Reset() {
```
Comment (aojea) [inline pkg/kubelet/images/image_manager_test.go:178]:
```suggestion
func (m *mockPodPullingTimeRecorder) reset() {
```

we don't need to export it, do we?

File: pkg/kubelet/images/image_manager_test.go [hunk 2]
```diff
@@ -201,7 +217,7 @@ func TestParallelPuller(t *testing.T) {
 
 	useSerializedEnv := false
 	for _, c := range cases {
-		puller, fakeClock, fakeRuntime, container := pullerTestEnv(c, useSerializedEnv)
+		puller, fakeClock, fakeRuntime, container, fakePodPullingTimeRecorder := pullerTestEnv(c, useSerializedEnv)
```
Comment (aojea) [inline pkg/kubelet/images/image_manager_test.go:220]: I think this should go inside the `t.Run` so it starts clean.

I also think that this way you don't need the reset

**Comment by aojea** [comment]
/ok-to-test

some comments but I think that this is good to cover from regressions, 
Thanks

File: pkg/kubelet/images/image_manager_test.go (hunk 2 above)
Comment (TommyStarK) [reply pkg/kubelet/images/image_manager_test.go:220]: I changed to `reset()`. 

When moving `pullerTestEnv` inside the `t.Run` it panics on `(*FakeRuntime).assertList` due to an invalid memory address or nil pointer dereference. 
I wonder if `pullerTestEnv` was called outside of `t.Run` for this reason, or it might be due to the loop ran inside the `t.Run` and the reset of `fakeRuntime.CalledFunctions` to `nil`, as each subtest is run in a separate goroutine.

Comment (aojea) [reply pkg/kubelet/images/image_manager_test.go:220]: do you have the entire stack trace?

Comment (TommyStarK) [reply pkg/kubelet/images/image_manager_test.go:220]:
```
--- FAIL: TestSerializedPuller (0.00s)
    --- FAIL: TestSerializedPuller/image_missing,_pull_if_not_present0 (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x21c95b0]

goroutine 81 [running]:
testing.tRunner.func1.2({0x24c0c00, 0x3731810})
	/usr/local/Cellar/go/1.19.4/libexec/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/usr/local/Cellar/go/1.19.4/libexec/src/testing/testing.go:1399 +0x39f
panic({0x24c0c00, 0x3731810})
	/usr/local/Cellar/go/1.19.4/libexec/src/runtime/panic.go:884 +0x212
k8s.io/kubernetes/pkg/kubelet/container/testing.(*FakeRuntime).assertList(0xc0005b4580, {0xc0001113d0, 0x1, 0x1}, {0xc00049e0e0, 0x2, 0x2})
	/Users/thomasmilox/perso/kubernetes/pkg/kubelet/container/testing/fake_runtime.go:141 +0x110
k8s.io/kubernetes/pkg/kubelet/container/testing.(*FakeRuntime).AssertCalls(0xc000116280?, {0xc0001113d0?, 0xc00004a0c0?, 0xc000600480?})
	/Users/thomasmilox/perso/kubernetes/pkg/kubelet/container/testing/fake_runtime.go:151 +0xc5
k8s.io/kubernetes/pkg/kubelet/images.TestSerializedPuller.func1(0x0?)
	/Users/thomasmilox/perso/kubernetes/pkg/kubelet/images/image_manager_test.go:260 +0x15c
testing.tRunner(0xc000103d40, 0xc00015e1e0)
	/usr/local/Cellar/go/1.19.4/libexec/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/usr/local/Cellar/go/1.19.4/libexec/src/testing/testing.go:1493 +0x35f
FAIL	k8s.io/kubernetes/pkg/kubelet/images	0.568s
FAI
```

Comment (TommyStarK) [reply pkg/kubelet/images/image_manager_test.go:220]: The nil pointer dereference comes from `fakeRuntime.T` used in `assertList()` which is nil here.
I could rewrite the function like this to avoid the `reset()`:
```go
func TestSerializedPuller(t *testing.T) {
	pod := &v1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name:            "test_pod",
			Namespace:       "test-ns",
			UID:             "bar",
			ResourceVersion: "42",
		}}

	cases := pullerTestCases()

	useSerializedEnv := true
	for _, c := range cases {
		for i, expected := range c.expected {
			t.Run(fmt.Sprintf("%s%d", c.testName, i), func(t *testing.T) {
				ctx := context.Background()
				puller, fakeClock, fakeRuntime, container, fakePodPullingTimeRecorder := pullerTestEnv(c, useSerializedEnv)
				fakeRuntime.CalledFunctions = nil
				fakeClock.Step(time.Second)
				fakeRuntime.T = t // just for debugging

				_, _, err := puller.EnsureImageExists(ctx, pod, container, nil, nil)
				fakeRuntime.AssertCalls(expected.calls)
				assert.Equal(t, expected.err, err)
				assert.Equal(t, expected.podPullingStartTimeShouldHaveBeenRecorded, fakePodPullingTimeRecorder.startedPullingRecorded)
				assert.Equal(t, expected.podPullingFinishTimeShouldHaveBeenRecorded, fakePodPullingTimeRecorder.finishedPullingRecorded)
			})
		}
	}
}
```
But then the test fails:
```
--- FAIL: TestSerializedPuller (0.00s)
    --- FAIL: TestSerializedPuller/image_missing,_unable_to_fetch2 (0.00s)
        /Users/thomasmilox/perso/kubernetes/pkg/kubelet/images/fake_runtime.go:141: AssertList: expected []string{"GetImageRef"}, got []string{"GetImageRef", "PullImage"}
        /Users/thomasmilox/perso/kubernetes/pkg/kubelet/images/image_manager_test.go:261: 
            	Error Trace:	/Users/thomasmilox/perso/kubernetes/pkg/kubelet/images/image_manager_test.go:261
            	Error:      	Not equal: 
            	            	expected: &errors.errorString{s:"ImagePullBackOff"}
            	            	actual  : &errors.errorString{s:"ErrImagePull"}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1,3 +1,3 @@
            	            	 (*errors.errorString)({
            	            	- s: (string) (len=16) "ImagePullBackOff"
            	            	+ s: (string) (len=12) "ErrImagePull"
            	            	 })
            	Test:       	TestSerializedPuller/image_missing,_unable_to_fetch2
```

Comment (TommyStarK) [reply pkg/kubelet/images/image_manager_test.go:220]: The nil pointer dereference comes from here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/testing/fake_runtime.go#L141
If I Add this to understand why the deep equality fails
```go
fakeRuntime.T = t
```
I got:
```
--- FAIL: TestParallelPuller (0.00s)
    --- FAIL: TestParallelPuller/image_missing,_unable_to_fetch (0.00s)
        /Users/thomasmilox/perso/kubernetes/pkg/kubelet/images/fake_runtime.go:141: AssertList: expected []string{"GetImageRef"}, got []string{"GetImageRef", "PullImage"}
        /Users/thomasmilox/perso/kubernetes/pkg/kubelet/images/image_manager_test.go:230: 
            	Error Trace:	/Users/thomasmilox/perso/kubernetes/pkg/kubelet/images/image_manager_test.go:230
            	Error:      	Not equal: 
            	            	expected: &errors.errorString{s:"ImagePullBackOff"}
            	            	actual  : &errors.errorString{s:"ErrImagePull"}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1,3 +1,3 @@
            	            	 (*errors.errorString)({
            	            	- s: (string) (len=16) "ImagePullBackOff"
            	            	+ s: (string) (len=12) "ErrImagePull"
            	            	 })
```
I will continue looking into it tomorrow but the order of `pullerTestCase` has to matter. I am obviously missing something here

Comment (aojea) [reply pkg/kubelet/images/image_manager_test.go:220]: it is best practice to have independent test cases , dependent test cases are harder to debug and read and easy to break

Comment (TommyStarK) [reply pkg/kubelet/images/image_manager_test.go:220]: Yes I agree, but I only focused on testing the tracking of the image pulling and didn't touch the existing scenarios. The outcome of some tests seems to be order dependant indeed. What would you recommend here ? staying with the reset handler ?

Comment (aojea) [reply pkg/kubelet/images/image_manager_test.go:220]: reset() works for me

The constructor inside t.Run doesn't panic for me

```diff
diff --git a/pkg/kubelet/images/image_manager_test.go b/pkg/kubelet/images/image_manager_test.go
index 4886828ba60..1ac1fc2816a 100644
--- a/pkg/kubelet/images/image_manager_test.go
+++ b/pkg/kubelet/images/image_manager_test.go
@@ -217,9 +217,9 @@ func TestParallelPuller(t *testing.T) {
 
        useSerializedEnv := false
        for _, c := range cases {
-               puller, fakeClock, fakeRuntime, container, fakePodPullingTimeRecorder := pullerTestEnv(c, useSerializedEnv)
-
                t.Run(c.testName, func(t *testing.T) {
+                       puller, fakeClock, fakeRuntime, container, fakePodPullingTimeRecorder := pullerTestEnv(c, useSerializedEnv)
+
                        ctx := context.Background()
                        for _, expected := range c.expected {
                                fakeRuntime.CalledFunctions = nil
@@ -248,9 +248,10 @@ func TestSerializedPuller(t *testing.T) {
 
        useSerializedEnv := true
        for _, c := range cases {
-               puller, fakeClock, fakeRuntime, container, fakePodPullingTimeRecorder := pullerTestEnv(c, useSerializedEnv)
 
                t.Run(c.testName, func(t *testing.T) {
+                       puller, fakeClock, fakeRuntime, container, fakePodPullingTimeRecorder := pullerTestEnv(c, useSerializedEnv)
+
                        ctx := context.Background()
                        for _, expected := range c.expected {
                                fakeRuntime.CalledFunctions = nil
@@ -308,13 +309,12 @@ func TestPullAndListImageWithPodAnnotations(t *testing.T) {
                        {[]string{"GetImageRef", "PullImage"}, nil, true, true},
                }}
 
-       useSerializedEnv := true
-       puller, fakeClock, fakeRuntime, container, fakePodPullingTimeRecorder := pullerTestEnv(c, useSerializedEnv)
-       fakeRuntime.CalledFunctions = nil
-       fakeRuntime.ImageList = []Image{}
-       fakeClock.Step(time.Second)
-
        t.Run(c.testName, func(t *testing.T) {
+               useSerializedEnv := true
+               puller, fakeClock, fakeRuntime, container, fakePodPullingTimeRecorder := pullerTestEnv(c, useSerializedEnv)
+               fakeRuntime.CalledFunctions = nil
+               fakeRuntime.ImageList = []Image{}
+               fakeClock.Step(time.Second)
                ctx := context.Background()
                _, _, err := puller.EnsureImageExists(ctx, pod, container, nil, nil)
                fakeRuntime.AssertCalls(c.expected[0].calls)
```

Comment (TommyStarK) [reply pkg/kubelet/images/image_manager_test.go:220]: Just to be sure our change does not introduce any problem in this area
Screenshot 2023-01-10 at 11 39 04

Comment (TommyStarK) [reply pkg/kubelet/images/image_manager_test.go]: Done in 10639a7963b

**Comment by SergeyKanzhelev** [comment]
Is there any user visible changes beyond the log? Briefly looking into code I see it is used beyond just kubelet.log. So I would expect this PR include some release notes explaining what bug is fixed (again, beyond just kubelet.log).

This value seems to be used in startup SLO and no tests were broken by https://github.com/kubernetes/kubernetes/pull/111772 (CC @pacoxu)

Originally this was introduced in https://github.com/kubernetes/kubernetes/pull/111930 (cc @azylinski) and it seems that the logic of duration calculation has no objections of finish time be zero and start time be Now. Should there be tests for this?

Also I am a bit on edge we will set the time for the containers with image pull policy `Never`. And for the error cases - should we include those values initialization for errors as well? Will those be used for SLO calculations? Will we be interested in how failing image pull slows down everything?

Overall code LGTM, but I really want questions above to be answered before merging or an issue created to investigate those.

**Comment by TommyStarK** [comment]
May I suggest a release not like: 
`image pulling: fix recording when pulling image did finish. The time of when pulling image is done was always equal to Go's zero date. The timestamp is now correctly set. In addition, when the image is already present, timestamps recording when pulling the image started and finished are set to Time.Now()` ?

If you validate the release note I will update the PR description to include it.

> Also I am a bit on edge we will set the time for the containers with image pull policy Never

Maybe I could update the condition to something `if the image is present and the policy isn't Never` ?

https://github.com/kubernetes/kubernetes/blob/10639a7963b31f43765d2abf53aa946fd1123bcc/pkg/kubelet/images/image_manager.go#L134-L145

**Comment by pacoxu** [comment]
> This value seems to be used in startup SLO and no tests were broken by #111772 (CC @pacoxu)

I only updated the event in #111772. The key issue of #111772 is that there is a waiting duration for the serialized pull image.

File: pkg/kubelet/images/image_manager.go [hunk 3]
```diff
@@ -134,6 +134,8 @@ func (m *imageManager) EnsureImageExists(ctx context.Context, pod *v1.Pod, conta
 	if !shouldPullImage(container, present) {
 		if present {
 			msg := fmt.Sprintf("Container image %q already present on machine", container.Image)
+			m.podPullingTimeRecorder.RecordImageStartedPulling(pod.UID)
+			m.podPullingTimeRecorder.RecordImageFinishedPulling(pod.UID)
```
Comment (pacoxu) [inline pkg/kubelet/images/image_manager.go:138]: Users may think this is a quick pulling, however, no pulling happened.

Is this by design?

**Comment by pacoxu** [comment]
/release-note-edit
```release-note
kubelet: fix recording issue when pulling image did finish
```

File: pkg/kubelet/images/image_manager.go (hunk 3 above)
Comment (pacoxu) [reply pkg/kubelet/images/image_manager.go:138]: If pod has multi-containers, we should add logic in RecordImageFinishedPulling like below:
```
diff --git a/pkg/kubelet/util/pod_startup_latency_tracker.go b/pkg/kubelet/util/pod_startup_latency_tracker.go
index 88a1b506f71..0376c67a4a8 100644
--- a/pkg/kubelet/util/pod_startup_latency_tracker.go
+++ b/pkg/kubelet/util/pod_startup_latency_tracker.go
@@ -136,7 +136,9 @@ func (p *basicPodStartupLatencyTracker) RecordImageFinishedPulling(podUID types.
                return
        }
 
-       state.lastFinishedPulling = p.clock.Now() // Now is always grater than values from the past.
+       if state.firstStartedPulling.IsZero() {
+               state.lastFinishedPulling = p.clock.Now() // Now is always greater than values from the past.
+       }
 }
```

Comment (TommyStarK) [reply pkg/kubelet/images/image_manager.go:138]: No it isn't by design, it was originally suggested by @aojea in the issue #114903

Comment (TommyStarK) [reply pkg/kubelet/images/image_manager.go:138]: I think the idea was to keep some consistency. Having the firstStartedPulling equals to lastFinishedPulling equals to Time.Now() made sense to me for image already present but I do agree with you it could be misunderstood and interpreted as a quick pulling when in fact nothing happened

Comment (pacoxu) [reply pkg/kubelet/images/image_manager.go:138]: If an empty date will make more misunderstanding, this is OK to me.

File: pkg/kubelet/images/image_manager_test.go [hunk 4]
```diff
@@ -34,8 +34,10 @@ import (
 )
 
 type pullerExpects struct {
-	calls []string
-	err   error
+	calls                                      []string
+	err                                        error
+	podPullingStartTimeShouldHaveBeenRecorded  bool
+	podPullingFinishTimeShouldHaveBeenRecorded bool
```
Comment (ruiwen-zhao) [inline pkg/kubelet/images/image_manager_test.go:40]: nit, suggesting: 

```
podPullingStartTimeShouldHaveBeenRecorded -> shouldRecordStartedPullingTime
podPullingFinishTimeShouldHaveBeenRecorded -> shouldRecordFinishedPullingTime
```

File: pkg/kubelet/images/image_manager_test.go [hunk 5]
```diff
@@ -153,20 +155,32 @@ func pullerTestCases() []pullerTestCase {
...
 
-type mockPodPullingTimeRecorder struct{}
+type mockPodPullingTimeRecorder struct {
+	startedPullingRecorded  bool
+	finishedPullingRecorded bool
+}
 
-func (m *mockPodPullingTimeRecorder) RecordImageStartedPulling(podUID types.UID) {}
+func (m *mockPodPullingTimeRecorder) RecordImageStartedPulling(podUID types.UID) {
+	m.startedPullingRecorded = true
```
Comment (ruiwen-zhao) [inline pkg/kubelet/images/image_manager_test.go:171]: would it make sense to guard the fields with locks, to avoid race condition, like fake_runtime? Ref: https://github.com/kubernetes/kubernetes/blob/10639a7963b31f43765d2abf53aa946fd1123bcc/pkg/kubelet/container/testing/fake_runtime.go#L115-L116

File: pkg/kubelet/util/pod_startup_latency_tracker_test.go [hunk 6]
```diff
@@ -141,6 +141,15 @@ kubelet_pod_start_sli_duration_seconds_count 1
 		fakeClock.Step(time.Millisecond * 100)
 		tracker.RecordImageFinishedPulling(podInit.UID)
 
+		podState, ok := tracker.pods[podInit.UID]
+		if !ok {
+			t.Errorf("expected to track pod: %s, but pod not found", podInit.UID)
+		}
+		if !podState.lastFinishedPulling.Equal(podState.firstStartedPulling.Add(time.Millisecond * 100)) {
+			t.Errorf("expected pod firstStartedPulling: %s and lastFinishedPulling: %s but got firstStartedPulling: %s and lastFinishedPulling: %s",
```
Comment (ruiwen-zhao) [inline pkg/kubelet/util/pod_startup_latency_tracker_test.go:149]: nit: `frozenTime` is effectively the same as `podState.firstStartedPulling`, but can we keep the error message consistent with the equal check? i.e.: 

```
t.Errorf("expected pod firstStartedPulling: %s and lastFinishedPulling: %s but got firstStartedPulling: %s and lastFinishedPulling: %s",
podState.firstStartedPulling, podState.firstStartedPulling.Add(time.Millisecond*100), podState.firstStartedPulling, podState.lastFinishedPulling)
```

File: pkg/kubelet/util/pod_startup_latency_tracker_test.go [hunk 7]
```diff
@@ -225,6 +234,19 @@ kubelet_pod_start_sli_duration_seconds_count 1
 		fakeClock.SetTime(frozenTime.Add(time.Second * 20))
 		tracker.RecordImageFinishedPulling(podInitializing.UID)
 
+		podState, ok := tracker.pods[podInitializing.UID]
+		if !ok {
+			t.Errorf("expected to track pod: %s, but pod not found", podInitializing.UID)
+		}
+		if !podState.firstStartedPulling.Equal(frozenTime.Add(time.Second * 10)) { // second and third image start pulling should not affect pod firstStartedPulling
+			t.Errorf("expected pod firstStartedPulling: %s but got firstStartedPulling: %s",
+				frozenTime.Add(time.Second*10), podState.firstStartedPulling)
```
Comment (ruiwen-zhao) [inline pkg/kubelet/util/pod_startup_latency_tracker_test.go:243]: same as above.

**Comment by SergeyKanzhelev** [comment]
> /release-note-edit
> 
> ```
> kubelet: fix recording issue when pulling image did finish
> ```

Can you please clarify in release notes how this is exposed to the customer. I understand there is some sort of duration metric that was miscalculated (beyond just kubelet.log)

**Comment by SergeyKanzhelev** [comment]
> > This value seems to be used in startup SLO and no tests were broken by #111772 (CC @pacoxu)
> 
> I only updated the event in #111772. The key issue of #111772 is that there is a waiting duration for the serialized pull image.

I thought the `m.podPullingTimeRecorder.RecordImageFinishedPulling(pod.UID)` was removed in the referred PR and now being restored back. Is the value not used in SLO calculation? I didn't dig deep, just confused

**Comment by TommyStarK** [comment]
@ruiwen-zhao, Thank you very much for the review, all your suggestions have been taken care of in dda229a93c8.

@SergeyKanzhelev, This is the original release note I suggested. Is it detailed enough ?

`image pulling: fix recording when pulling image did finish. The time of when pulling image is done was always equal to Go's zero date. The timestamp is now correctly set.`

I will look @pacoxu's suggestion to set an empty date  when image is already present if it is possible.

**Comment by pacoxu** [comment]
> > I only updated the event in #111772. The key issue of #111772 is that there is a waiting duration for the serialized pull image.
> 
> I thought the `m.podPullingTimeRecorder.RecordImageFinishedPulling(pod.UID)` was removed in the referred PR and now being restored back. Is the value not used in SLO calculation? I didn't dig deep, just confused

It seems to be a mistaken removal during rebasing.

**Comment by SergeyKanzhelev** [comment]
> > > I only updated the event in #111772. The key issue of #111772 is that there is a waiting duration for the serialized pull image.
> > 
> > 
> > I thought the `m.podPullingTimeRecorder.RecordImageFinishedPulling(pod.UID)` was removed in the referred PR and now being restored back. Is the value not used in SLO calculation? I didn't dig deep, just confused
> 
> It seems to be a mistaken removal during rebasing. My fault.

No worries. What worries me that no tests failed. It indicates that there is a feature that is not covered by tests and I want to understand what this feature is, what is the plan to cover it with tests, and how it is exposed to customers. Something like "SLO metrics are not calculated correctly". But with more details.

I dont think this should block the PR. I just want to make sure if there is a KEP tracking this feature, this KEP needs to be updated to make sure the test will be implemented.

**Comment by TommyStarK** [comment]
@pacoxu, I took your emoji as a yes and removed recording timestamps when image is present. If there is anything please don't hesitate.

Best,

**Comment by pacoxu** [comment]
Either is OK with me.
/lgtm
The current change is very clear to add the `RecordImageFinishedPulling` back.

**Comment by TommyStarK** [comment]
@pacoxu PR has been rebased

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm

**Comment by TommyStarK** [comment]
@SergeyKanzhelev I tried to contact kubelet approvers to move on on those PRs and avoid the lifecycle/stale label

**Comment by TommyStarK** [comment]
@derekwaynecarr any feedback from will be greatly appreciated

**Comment by derekwaynecarr** [comment]
thanks for the fix.

/approve
