### PR TITLE
GCE: Consume new config value for network project id

### LINKED ISSUE #48515: GCE: Project Id used for firewall mgmt instead of network project Id
In the GCE Cloudprovider package, firewall should be created in the project which contains the network.  Currently, the compute project Id is used. This is a broken feature of K8s 1.7.0.

### PR DESCRIPTION
**Pull request by nicksardo**
This PR will allow users to specify the network's project ID in gce.conf. If it's not specified, it will be filled with `ProjectID`.  This means that `network-project-id` is a required field for building a cluster on a shared VPC network. However, this means the field does not need to be specified for GKE clusters on non-shared networks. 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #
Fixes #48515

**Special notes for your reviewer**:
/assign @bowei @freehan 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

File: pkg/cloudprovider/providers/gce/gce.go [hunk 1]
```diff
@@ -456,6 +487,16 @@ func (gce *GCECloud) ProviderName() string {
...
 }
 
+// ProjectID returns the ProjectID corresponding to the project this cloud is in.
+func (g *GCECloud) ProjectID() string {
+	return g.projectID
+}
+
+// NetworkProjectID returns the ProjectID corresponding to the project this cluster's network is in.
+func (g *GCECloud) NetworkProjectID() string {
+	return g.projectID
```
Comment (freehan) [inline pkg/cloudprovider/providers/gce/gce.go]: networkProjectID?

Comment (freehan) [inline pkg/cloudprovider/providers/gce/gce.go]: also expose networkProjectNumber?
I do not see it is consumed anywhere.

Comment (nicksardo) [inline pkg/cloudprovider/providers/gce/gce.go]: Nice catch, thanks.

Yes, `projectNumber` and `networkProjectNumber` aren't used anywhere, but the idea was to make it clear to future authors that there is a difference between `number` and `ID`. I can take them out if you prefer it.
