### PR TITLE
Don't count unrelated volumes in scheduler predicate

### LINKED ISSUE #80352: MaxCSIVolumeCountPred allows only 16 unbound PVCs
**What happened**:

The [MaxCSIVolumeCountPred predicate](https://github.com/bertinatto/kubernetes/blob/b5dfcf357a358ae48591ed7fda39ff72791f7fbe/pkg/scheduler/algorithm/predicates/predicates.go#L100), now deprecated in favor of the new CSI predicate, is used as a base for EBS, GCEPD, Azure and Cinder predicates.

Recently it was [found out](https://github.com/kubernetes/kubernetes/pull/80247#issuecomment-512830032) that this predicate doesn't check whether the provisioner of an **unbound volume** is the one that it should be counting. As a result, these predicates always assume that an unbound volume is theirs, counting it towards the limit.

**How to reproduce it (as minimally and precisely as possible)**:

Create a pod with [more than 16](https://github.com/bertinatto/kubernetes/blob/b5dfcf357a358ae48591ed7fda39ff72791f7fbe/pkg/scheduler/algorithm/predicates/predicates.go#L110-L116) unbound volumes. The predicate will prevent the pod from being scheduled.

/sig storage
CC @jsafrane @gnufied

### PR DESCRIPTION
**Pull request by bertinatto**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

This PR changes the old volume limits predicates (now deprecated) so they don't count unrelated volumes.

**Which issue(s) this PR fixes**:

Fixes #80352

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig storage

### CODE REVIEW

File: pkg/scheduler/algorithm/predicates/predicates.go [hunk 1]
```diff
@@ -422,6 +425,19 @@ func (c *MaxPDVolumeCountChecker) filterVolumes(volumes []v1.Volume, namespace s
 				continue
 			}
 
+			scName := pvc.Spec.StorageClassName
+			storageClass, err := c.scInfo.GetStorageClassInfo(*scName)
+			if err != nil {
+				klog.V(4).Infof("Unable to look up StorageClass info for %s/%s, assuming PVC matches predicate when counting limits: %v", namespace, pvcName, err)
+				filteredVolumes[pvID] = true
```
Comment (bertinatto) [inline pkg/scheduler/algorithm/predicates/predicates.go]: I added this line to make it consistent with line 424 above, but IMO the volume shouldn't be counted here (nor if the PVC is not found, like it's done above).

I think it should only be counted after line 436 below, because until then there's no way to know that the volume belongs to the running predicate (that can be GCE, AWS, Azure, Cinder).

@jsafrane, can you take a look at this?

**Comment by jsafrane** [comment]
cc @msau42

File: pkg/scheduler/algorithm/predicates/predicates.go (hunk 1 above)
Comment (bertinatto) [reply pkg/scheduler/algorithm/predicates/predicates.go]: > Can we make pods with unbound PVCs with missing storage class unschedulable?

We can return the error and make the pod unschedulable in the node. 

This might be a problem after upgrade, e.g., when the node has a pod running whose volume has no SC, no new pods will be scheduled to it I guess.

File: pkg/scheduler/algorithm/predicates/predicates.go [hunk 2]
```diff
@@ -422,6 +425,19 @@ func (c *MaxPDVolumeCountChecker) filterVolumes(volumes []v1.Volume, namespace s
 				continue
 			}
 
+			scName := pvc.Spec.StorageClassName
+			storageClass, err := c.scInfo.GetStorageClassInfo(*scName)
```
[the remark this answers is not in the document]
Comment (bertinatto) [reply pkg/scheduler/algorithm/predicates/predicates.go]: Removed log

File: pkg/scheduler/algorithm/predicates/predicates.go [hunk 3]
```diff
@@ -422,6 +425,19 @@ func (c *MaxPDVolumeCountChecker) filterVolumes(volumes []v1.Volume, namespace s
 				continue
```
Comment (bertinatto) [inline pkg/scheduler/algorithm/predicates/predicates.go]: What about this, would be acceptable to make the pod unschedulable?

We currently fail if the PVC name is empty, but we count the volume if the PVC is invalid.

 I think counting this volume is not correct, since at this point we're not sure whether the volume belongs to the running predicate (i.e., it could be a EBS volume being counted by the GCEPD predicate).

File: pkg/scheduler/algorithm/predicates/predicates.go [hunk 4]
```diff
@@ -422,6 +425,17 @@ func (c *MaxPDVolumeCountChecker) filterVolumes(volumes []v1.Volume, namespace s
...
 			}
 
+			scName := pvc.Spec.StorageClassName
+			storageClass, err := c.scInfo.GetStorageClassInfo(*scName)
+			if err != nil || storageClass == nil {
+				continue
+			}
+
+			if !c.filter.MatchProvisioner(storageClass) {
+				klog.V(4).Infof("PVC %s/%s belongs to a different provisioner, skipping PVC", namespace, pvcName)
```
Comment (msau42) [inline pkg/scheduler/algorithm/predicates/predicates.go]: Bump to level 5 since this can be a normal occurrence.

File: pkg/scheduler/algorithm/predicates/predicates.go [hunk 5]
```diff
@@ -528,6 +542,13 @@ var EBSVolumeFilter = VolumeFilter{
 		return "", false
 	},
 
+	MatchProvisioner: func(sc *storagev1.StorageClass) (relevant bool) {
+		if sc.Provisioner == csilibplugins.AWSEBSInTreePluginName {
```
Comment (msau42) [inline pkg/scheduler/algorithm/predicates/predicates.go]: is migration handled correctly here?

File: pkg/scheduler/algorithm/predicates/predicates.go (hunk 3 above)
Comment (msau42) [reply pkg/scheduler/algorithm/predicates/predicates.go]: This was an error condition we added a while ago to handle the case where users may delete PVCs while Pods were still running and using them.  But now that we have StorageProtection, do we need this check?  cc @jsafrane

Comment (jsafrane) [reply pkg/scheduler/algorithm/predicates/predicates.go]: > This was an error condition we added a while ago to handle the case where users may delete PVCs while Pods were still running and using them

Hmm, scheduler ignores pods that are running. IMO this check covers users (and StatefulSets) creating Pods before PVCs.

Comment (msau42) [reply pkg/scheduler/algorithm/predicates/predicates.go]: My argument is that StorageProtection handles 1).  And scheduler prevents 2). If immediate binding, predicate fails. If delayed binding, we count further down.

Comment (jsafrane) [reply pkg/scheduler/algorithm/predicates/predicates.go]: PVC protection can be forced off, so scheduler can encounter a pod that refers to PVC that does not exist. If `filterVolumes` is counting running pods, I would suggest not to count the volume - user has broken something and miscalculations are IMO OK. If `filterVolumes` checks a newly scheduled pod, I'd return error and prevented the pod from scheduling.

Comment (bertinatto) [reply pkg/scheduler/algorithm/predicates/predicates.go]: I like this approach, it addresses my concern.

Comment (msau42) [reply pkg/scheduler/algorithm/predicates/predicates.go]: We don't strictly need separate behavior for counting separate pods vs to be scheduled pod. The volume binding predicate checks for bound pvcs

Comment (bertinatto) [reply pkg/scheduler/algorithm/predicates/predicates.go]: Hm, yeah, it does make sense for this predicate to only make the pod unschedulable because of volume limits; and leave the pvc binding checks for the volume binding predicate.

Updated the code, PTAL.

File: pkg/scheduler/algorithm/predicates/predicates.go [hunk 6]
```diff
@@ -418,9 +421,22 @@ func (c *MaxPDVolumeCountChecker) filterVolumes(volumes []v1.Volume, namespace s
...
-				// if the PVC is not found, log the error and count the PV towards the PV limit
-				klog.V(4).Infof("Unable to look up PVC info for %s/%s, assuming PVC matches predicate when counting limits: %v", namespace, pvcName, err)
-				filteredVolumes[pvID] = true
+				// If the PVC is invalid, We don't count the volume here because
+				// there's no guarantee that it belongs to the running predicate.
+				klog.V(4).Infof("Unable to look up PVC info for %s/%s, assuming PVC doesn't match predicate when counting limits: %v", namespace, pvcName, err)
+				continue
+			}
+
+			storageClass, err := c.scInfo.GetStorageClassInfo(*pvc.Spec.StorageClassName)
```
Comment (msau42) [inline pkg/scheduler/algorithm/predicates/predicates.go]: Should we check storageclass after VolumeName?  We only need to look at StorageClass for delayed binding case right?

Comment (bertinatto) [reply pkg/scheduler/algorithm/predicates/predicates.go]: Yeat, that's better. Updated

**Comment by bertinatto** [comment]
CC @gnufied

File: pkg/scheduler/algorithm/predicates/predicates.go [hunk 7]
```diff
@@ -299,6 +300,7 @@ type VolumeFilter struct {
 	// Filter normal volumes
 	FilterVolume           func(vol *v1.Volume) (id string, relevant bool)
 	FilterPersistentVolume func(pv *v1.PersistentVolume) (id string, relevant bool)
+	MatchProvisioner       func(sc *storagev1.StorageClass) (relevant bool)
```
Comment (jsafrane) [inline pkg/scheduler/algorithm/predicates/predicates.go]: Please add documentation

File: pkg/scheduler/algorithm/predicates/max_attachable_volume_predicate_test.go [hunk 8]
```diff
@@ -361,25 +362,25 @@ func TestVolumeCountConflicts(t *testing.T) {
...
+			test:         "missing PVC is not counted towards the PV limit",
 		},
 		{
 			newPod:       onePVCPod(EBSVolumeFilterType),
 			existingPods: []*v1.Pod{oneVolPod, twoDeletedPVCPod},
 			filterName:   EBSVolumeFilterType,
-			maxVols:      3,
-			fits:         false,
-			test:         "pod with missing two PVCs is counted towards the PV limit twice",
+			maxVols:      2,
```
Comment (jsafrane) [inline pkg/scheduler/algorithm/predicates/max_attachable_volume_predicate_test.go]: I miss some tests with unbound PVC and matching / non-matching StorageClass.

**Review by jsafrane — COMMENTED** [review]
looks good enough to me. @msau42, WDYT?

File: pkg/scheduler/algorithm/predicates/predicates.go (hunk 7 above)
Comment (bertinatto) [reply pkg/scheduler/algorithm/predicates/predicates.go]: Added

File: pkg/scheduler/algorithm/predicates/max_attachable_volume_predicate_test.go (hunk 8 above)
Comment (bertinatto) [reply pkg/scheduler/algorithm/predicates/max_attachable_volume_predicate_test.go]: Added tests for non-matching + invalid StorageClasses. The other tests are covering the matching use cases.

**Comment by bertinatto** [comment]
@jsafrane, @msau42: 

I addressed all your comments, PTAL. Let me know if there's anything else I should accommodate in this PR.

**Comment by jsafrane** [comment]
I am happy. @msau42, WDYT?

**Review by bsalamat — COMMENTED** [review]
/approve
