### PR TITLE
Check successfully assigned event message for both 1.10 and 1.11.

### LINKED ISSUE #62704: Failing Test : [sig-scheduling] SchedulerPredicates [Serial] validates that taints-tolerations is respected if not matching
## Triage results
https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=scheduling&test=validates%20that%20taints-tolerations%20is%20respected%20if%20not%20matchin

This test is currently failing in sig-release master-upgrade suite, This could potentially become release blocking if not addressed sooner. @aveshagarwal can you please triage this failure?

/kind bug
/priority failing-test
/priority important-soon
/sig scheduling
@kubernetes/sig-scheduling-bugs 

cc @jberkus @tpepper 

/assign @aveshagarwal

### PR DESCRIPTION
**Pull request by k82cn**
Signed-off-by: Da K. Ma <klaus1982.cn@gmail.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #62704 

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by k82cn** [comment]
@wojtek-t for comments :)

File: test/e2e/scheduling/events.go [hunk 1]
```diff
@@ -23,12 +23,15 @@ import (
...
+func scheduleSuccessEvent(ns, podName, nodeName string) func(*v1.Event) bool {
 	return func(e *v1.Event) bool {
 		return e.Type == v1.EventTypeNormal &&
 			e.Reason == "Scheduled" &&
 			strings.HasPrefix(e.Name, podName) &&
-			strings.Contains(e.Message, fmt.Sprintf("Successfully assigned %v to %v", podName, nodeName))
+			// Check event message for 1.11+ (1.11 included)
+			(strings.Contains(e.Message, fmt.Sprintf("Successfully assigned %v/%v to %v", ns, podName, nodeName)) ||
+				// Check event message for 1.10- (1.10 included)
+				strings.Contains(e.Message, fmt.Sprintf("Successfully assigned %v to %v", podName, nodeName)))
```
Comment (aveshagarwal) [inline test/e2e/scheduling/events.go]: Relying on message strings is always error prone (as the issue shows) as any message string can change anytime without knowing that the same string is being matched somewhere else.

Comment (k82cn) [reply test/e2e/scheduling/events.go]: yes, but this's enough for an e2e test.

Comment (resouer) [reply test/e2e/scheduling/events.go]: I will LGTM for this temporary fix. But it would be great if we can work out a change in scheduler to remove these string checks later.

Also @k82cn, could you please add a NOTE comment  on in scheduler.go to clarify that any change of this event message `Successfully assigned ...`  will affect scheduling e2e tests?

Comment (msau42) [reply test/e2e/scheduling/events.go]: Yeah I was checking for event strings in my e2e tests, and finally I removed them after having to fix the strings countless times after they changed.

Is it sufficient in this test to just check the pod.nodename field?

Comment (msau42) [reply test/e2e/scheduling/events.go]: It's also a challenge dealing with this string differences in upgrade/downgrade tests

Comment (k82cn) [reply test/e2e/scheduling/events.go]: > Is it sufficient in this test to just check the pod.nodename field?

Should be enough for e2e test, as we build cases in one namespace.

I'd like to follow the style of 1.10 in this PR, and enhance in other pr for upper version.

**Comment by AishSundar** [comment]
@MaciekPytel there was discussion in the slack release channel regarding CP this into 1.10. @k82cn can you let @MaciekPytel know whats needed here?
 /cc @MaciekPytel

**Comment by MaciekPytel** [comment]
/hold 
So it doesn't merge as soon as I add cherrypick-approved. It seems there is still some discussion going on in this PR. @k82cn @msau42 feel free to cancel hold at any time if you think this PR is ready for merging.

File: test/e2e/scheduling/events.go (hunk 1 above)
Comment (msau42) [reply test/e2e/scheduling/events.go]: As a short term test fix, this is fine.  Longer term, like @resouer mentioned, it's probably better for the test to not check for strings altogether.

Comment (k82cn) [reply test/e2e/scheduling/events.go]: Great! let's take cherrypick as cherrypick .

**Comment by k82cn** [comment]
/hold cancel

I'll open other PRs in main branch to handle it; and keep cherrypick as cherrypick :)
