### PR TITLE
Attempt to ensure entire resp body is read

### LINKED ISSUE #30975: Investigate whether we reuse connections after "429" error
From the recent runs of different scalability tests, I have a hypothesis that we are not reusing connections after "429" error is returned to the client.

Here is description of one tests that I've seen failed:
1. basically in 2000-node kubemark all watches were dropped at some point (that's a separate issue #30873 that is a bit unrelated here).
2. what happened next is that basically all watchers decided to do list + watch, and obvious a bunch of lists failed with 429 error (this is still expected). And we started retrying them.
 And this is still ok.
3. Since that point, apiserver started consuming ~30 cores (which also isn't completely unexpected).
4. But what IS unexpected to me, is that looking into profile ~70% of the CPU (which was ~20 cores) were spend in "doFullHandshake".
 And this is a bit strange to me.

 Do we do something specific on 429 errors (e.g. close the connection) so that we won't be able to reuse it in the future?
 Or do you have any other hypothesis, why we were mostly doing "full handshakes" at that time?

@krousey @lavalamp @caesarxuchao @kubernetes/sig-api-machinery

### PR DESCRIPTION
**Pull request by krousey**
**What this PR does / why we need it**: Enables the re-use of TCP connections when code fails to read the entire body of the response.

**Which issue this PR fixes**: fixes #30975 

**Special notes for your reviewer**:

This is a best effort approach. It only attempts to drain the body of the response if it's less than 1k. It seems like a reasonable barrier at which to give up and just use a new TCP connection.

cc: @wojtek-t @smarterclayton @lavalamp @kubernetes/sig-api-machinery

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31016)

### CODE REVIEW

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Comment by krousey** [comment]
As for the amount we should read, I believe [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/handlers.go#L135) is the body that is not being read in the 429 case:

```go
func tooManyRequests(req *http.Request, w http.ResponseWriter) {
	// "Too Many Requests" response is returned before logger is setup for the request.
	// So we need to explicitly log it here.
	defer httplog.NewLogged(req, &w).Log()

	// Return a 429 status indicating "Too Many Requests"
	w.Header().Set("Retry-After", RetryAfter)
	http.Error(w, "Too many requests, please try again later.", errors.StatusTooManyRequests)
}
```

So 42 bytes?

File: pkg/client/restclient/request.go [hunk 1]
```diff
@@ -821,9 +821,16 @@ func (r *Request) request(fn func(*http.Request, *http.Response)) error {
...
 
 		done := func() bool {
-			// ensure the response body is closed before we reconnect, so that we reuse the same
-			// TCP connection
-			defer resp.Body.Close()
+			// Ensure the response body is fully read and closed
+			// before we reconnect, so that we reuse the same TCP
+			// connection.
+			defer func() {
+				const maxBodySlurpSize = 2 << 10
```
Comment (smarterclayton) [inline pkg/client/restclient/request.go]: Would recommend instead:

```
io.Copy(ioutil.Discard, ioutil.LimitedReader{R: resp.Body, N: maxBodySlurpSize})
```

Do you need to check ContentLength -1 in this case?  OR just check for body nil.

Comment (krousey) [inline pkg/client/restclient/request.go]: -1 is when the length is unknown. I think I'll stick with this since it's equivalent, but doesn't require another object to be created.

Comment (krousey) [inline pkg/client/restclient/request.go]: You're right though... the -1 should not need to be explicitly checked since it satisfies the other condition. I just cribbed this from the standard lib.

Body should never be nil. Even if it's empty. The http package explicitly guarantees this.

Comment (smarterclayton) [inline pkg/client/restclient/request.go]: Using LimitedReader does not create an object if the compiler can determine it doesn't escape, which it should not in this case.

Comment (krousey) [inline pkg/client/restclient/request.go]: Fixed.

**Comment by wojtek-t** [comment]
LGTM - thanks

**Comment by wojtek-t** [comment]
That helped a lot for our scalability tests - thanks!

**Comment by krousey** [comment]
Glad it did. Could you quantify it? Just for my own curiosity.

**Comment by wojtek-t** [comment]
>
Glad it did. Could you quantify it? Just for my own curiosity.

I'm not able to give the exact number. However, after this change I'm not seeing "doFullHandshakes" in apiserver profiles at all (before depending on the run, the moment of the test, and some "luck" it was somewhere between 3% and 70%) :-) [in large 2000-node clusters]

I think that generally in a healthy cluster it doesn't matter - it was getting worse and worse when we started hitting some 429 in pretty loaded cluster, because then it resulted in "snawball effect".

**Comment by smarterclayton** [comment]
Do we fail tests automatically if they regress scalability, or just
manually?

**Comment by wojtek-t** [comment]
We have automatic tests, but currently they are not blocking merge-queue (basically because of: https://github.com/kubernetes/kubernetes/issues/29897)
