### PR TITLE
kubeadm: add required etcd certs to selfhosting api-server

### LINKED ISSUE #1281: Selfhosting pivoting fails when using --store-certs-in-secrets
`kubeadm alpha selfhosting pivot` (kubeadm v1.13.0-beta.2) fails when invoked with `--store-certs-in-secrets` with the following error message:

```bash 
[pivot] pivoting cluster to self-hosted
[self-hosted] Created TLS secret "ca" from ca.crt and ca.key
[self-hosted] Created TLS secret "apiserver" from apiserver.crt and apiserver.key
[self-hosted] Created TLS secret "apiserver-kubelet-client" from apiserver-kubelet-client.crt and apiserver-kubelet-client.key
[self-hosted] Created TLS secret "sa" from sa.pub and sa.key
[self-hosted] Created TLS secret "front-proxy-ca" from front-proxy-ca.crt and front-proxy-ca.key
[self-hosted] Created TLS secret "front-proxy-client" from front-proxy-client.crt and front-proxy-client.key
[self-hosted] Created secret for kubeconfig file "scheduler.conf"
[self-hosted] Created secret for kubeconfig file "controller-manager.conf"
[apiclient] Found 1 Pods for label selector k8s-app=self-hosted-kube-apiserver
timed out waiting for the condition
```

### PR DESCRIPTION
**Pull request by bart0sh**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Selfhosting pivoting fails when using --store-certs-in-secrets
as api-server fails to start because of missing etcd/ca and
apiserver-etcd-client certificates:
```
   F1227 16:01:52.237352 1 storage_decorator.go:57] Unable to create storage backend:
   config (&{ /registry [https://127.0.0.1:2379]
              /etc/kubernetes/pki/apiserver-etcd-client.key
              /etc/kubernetes/pki/apiserver-etcd-client.crt
              /etc/kubernetes/pki/etcd/ca.crt true 0xc000884120 <nil> 5m0s 1m0s}),
   err (open /etc/kubernetes/pki/apiserver-etcd-client.crt: no such file or directory)
```

Added required certificates to fix this.

Secret name for etc/ca certifcate has been converted to conform RFC-1123 subdomain
naming conventions to prevent this TLS secret creation failure:
```
    unable to create secret: Secret "etcd/ca" is invalid: metadata.name:
    Invalid value: "etcd/ca": a DNS-1123 subdomain must consist of lower
    case alphanumeric characters, '-' or '.', and must start and end with an
    alphanumeric character (e.g. 'example.com', regex used for validation is
    '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

Related issue: kubernetes/kubeadm#1281

**Special notes for your reviewer**:
This is a first commit of a series aiming to fix kubernetes/kubeadm#1281

**Does this PR introduce a user-facing change?**:
```release-note
kubeadm: fixed storing of etcd certificates in secrets required by kube-apiserver selfhosting pivoting
```

### CODE REVIEW

File: cmd/kubeadm/app/phases/selfhosting/selfhosting_volumes.go [hunk 1]
```diff
@@ -128,6 +129,40 @@ func apiServerCertificatesVolumeSource() v1.VolumeSource {
...
+								Key:  v1.TLSPrivateKeyKey,
+								Path: kubeadmconstants.EtcdCAKeyName,
+							},
+						},
+					},
+				},
+				{
+					Secret: &v1.SecretProjection{
+						LocalObjectReference: v1.LocalObjectReference{
+							Name: kubeadmconstants.APIServerEtcdClientCertAndKeyBaseName,
```
Comment (yagonobre) [inline cmd/kubeadm/app/phases/selfhosting/selfhosting_volumes.go]: Do you need to use strings.replace here as well?

File: cmd/kubeadm/app/phases/selfhosting/selfhosting_volumes.go [hunk 2]
```diff
@@ -294,5 +329,15 @@ func getTLSKeyPairs() []*tlsKeyPair {
 			cert: kubeadmconstants.FrontProxyClientCertName,
 			key:  kubeadmconstants.FrontProxyClientKeyName,
 		},
+		{
+			name: strings.Replace(kubeadmconstants.EtcdCACertAndKeyBaseName, "/", "-", -1),
+			cert: kubeadmconstants.EtcdCACertName,
+			key:  kubeadmconstants.EtcdCAKeyName,
+		},
+		{
+			name: kubeadmconstants.APIServerEtcdClientCertAndKeyBaseName,
```
Comment (yagonobre) [inline cmd/kubeadm/app/phases/selfhosting/selfhosting_volumes.go]: Same here

**Review by yagonobre — COMMENTED** [review]
Thanks @bart0sh 
I added a comment with a doubt.
Also it would be nice if we declare the volumes in a single place.

**Review by neolit123 — APPROVED** [review]
thanks for the fix @bart0sh 
we should have SUSE folks in the loop, because they had interest in maintaining the selfhosting pivot.
cc @Klaven @ereslibre 

/approve
/priority backlog

File: cmd/kubeadm/app/phases/selfhosting/selfhosting_volumes.go (hunk 1 above)
Comment (bart0sh) [reply cmd/kubeadm/app/phases/selfhosting/selfhosting_volumes.go]: no, we don't as certificate name doesn't contain '/'

File: cmd/kubeadm/app/phases/selfhosting/selfhosting_volumes.go (hunk 2 above)
Comment (bart0sh) [reply cmd/kubeadm/app/phases/selfhosting/selfhosting_volumes.go]: same thing - we only need to convert etcd/ca as it has '/' in the name.

**Review by yagonobre — APPROVED** [review]
/lgtm
/hold (just to suse folks have a chance to review it, but feel free to unhold)

**Review by ereslibre — APPROVED** [review]
LGTM
