### PR TITLE
Print grafana proxy address in kube-up.sh.

### LINKED ISSUE #4721: Incorrect grafana address printed by kube-up.sh
After starting kubernetes cluster on GCE with ./kube-up.sh, I cannot connect to grafana dashboard.

### PR DESCRIPTION
**Pull request by jszczepkowski**
Fixed grafana address print by kube-up.sh. Resolved #4721.

### CODE REVIEW

File: cluster/gce/util.sh [hunk 1]
```diff
@@ -868,7 +868,7 @@ function setup-monitoring-firewall {
   done
   if [[ ${grafana_host} != *"<"* ]]; then
```
Comment (zmerlynn) [inline cluster/gce/util.sh]: cc @vishh 

I found the title of this PR a title deceptive even if the change is cool, because it's not "fixing" the address, so much as changing it to go through the proxy.

I would remove lines 859-867. We already have "Wait for the monitoring dashboard to be online."

Comment (vishh) [inline cluster/gce/util.sh]: +1 to what @zmerlynn said. Since we don't use the grafana_host anymore, that logic can be deleted.

**Comment by vishh** [comment]
Thanks for the fix @jszczepkowski!!!!

File: cluster/gce/util.sh (hunk 1 above)
Comment (jszczepkowski) [inline cluster/gce/util.sh]: Done.

**Comment by jszczepkowski** [comment]
Comments applied.

**Comment by vishh** [comment]
LGTM
