### PR TITLE
fix TestCoSchedulinngWithPermitPlugin and test PermitPlugin

### LINKED ISSUE #88469: TestCoSchedulingWithPermitPlugin is flaky
**Which jobs are flaking**:

pull-kubernetes-integration

**Which test(s) are flaking**:

TestCoSchedulingWithPermitPlugin

**Testgrid link**:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88087/pull-kubernetes-integration/1231953671323914243

**Reason for failure**:

```
 framework_test.go:1332: test #1: Expected the waiting pod to be scheduled. error: timed out waiting for the condition
```

/sig scheduling

### PR DESCRIPTION
**Pull request by mateuszlitwin**
**What type of PR is this?**
/kind bug
/kind flake

**What this PR does / why we need it**:
After moving Permit() to the scheduling cycle test PermitPlugin should
no longer wait inside Permit() for another pod to enter Permit() and become waiting pod.
In the past this was a way to make test work regardless of order in
which pods enter Permit(), but now only one Permit() can be executed at
any given moment and waiting for another pod to enter Permit() inside
Permit() leads to timeouts.

In this change waitAndRejectPermit and waitAndAllowPermit flags make first
pod to enter Permit() a waiting pod and second pod to enter Permit()
either rejecting or allowing pod.

**Which issue(s) this PR fixes**:

Fixes #88469

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig scheduling

### CODE REVIEW

**Review by wgliang — COMMENTED** [review]
/ok-to-test

File: test/integration/scheduler/framework_test.go [hunk 1]
```diff
@@ -1326,39 +1329,47 @@ func TestCoSchedulingWithPermitPlugin(t *testing.T) {
...
+			t.Errorf("Error while creating the second pod: %v", err)
 		}
 
 		if test.waitReject {
-			if err = waitForPodUnschedulable(testCtx.clientSet, waitingPod); err != nil {
+			if err = waitForPodUnschedulable(testCtx.clientSet, podA); err != nil {
 				t.Errorf("test #%v: Didn't expect the waiting pod to be scheduled. error: %v", i, err)
 			}
-			if err = waitForPodUnschedulable(testCtx.clientSet, signallingPod); err != nil {
+			if err = waitForPodUnschedulable(testCtx.clientSet, podA); err != nil {
```
Comment (alculquicondor) [inline test/integration/scheduler/framework_test.go]: podB?

File: test/integration/scheduler/framework_test.go [hunk 2]
```diff
@@ -1326,39 +1329,47 @@ func TestCoSchedulingWithPermitPlugin(t *testing.T) {
...
 				t.Errorf("test #%v: Didn't expect the signalling pod to be scheduled. error: %v", i, err)
 			}
+			if (permitPlugin.waitingPod == podA.Name && permitPlugin.rejectingPod == podB.Name) ||
```
Comment (alculquicondor) [inline test/integration/scheduler/framework_test.go]: I think we don't need to check the internals

**Review by alculquicondor — COMMENTED** [review]
You can run integration tests like this:

```make test-integration WHAT=./test/integration/pods GOFLAGS="-v" KUBE_TEST_ARGS="-run ^TestPodUpdateActiveDeadlineSeconds$"```

File: test/integration/scheduler/framework_test.go (hunk 2 above)
Comment (mateuszlitwin) [reply test/integration/scheduler/framework_test.go]: I think it is useful to know if test passed because anticipated events happened. I can see why both pods could be scheduled or unscheduled for other reasons than one waiting and other allowing or rejecting resulting in false positives.

Comment (alculquicondor) [reply test/integration/scheduler/framework_test.go]: Ideally, we should be checking user-visible effects. For example, if a pod fails to schedule due to being rejected while waiting, then that message will be part of the scheduling failure event.

Capturing that is possible (example: https://github.com/kubernetes/kubernetes/pull/88526/files#diff-cdc3caeca8898a0c12df164e679baef3R598). But this can be done as a follow up if you wish to work on it. This is good for now, provided that we have experimental proof that it's working.

**Comment by alculquicondor** [comment]
@mateuszlitwin, were you able to do the 10 runs?

**Comment by alculquicondor** [comment]
/approve
As per https://github.com/kubernetes/kubernetes/issues/88469#issuecomment-594119220, the test didn't fail in 10+ runs

File: test/integration/scheduler/framework_test.go [hunk 3]
```diff
@@ -1326,31 +1323,42 @@ func TestCoSchedulingWithPermitPlugin(t *testing.T) {
 		permitPlugin.waitAndRejectPermit = test.waitReject
 		permitPlugin.waitAndAllowPermit = test.waitAllow
 
-		// Create two pods.
-		waitingPod, err := createPausePod(testCtx.ClientSet,
-			initPausePod(testCtx.ClientSet, &pausePodConfig{Name: "waiting-pod", Namespace: testCtx.NS.Name}))
+		// Create two pods. First pod to enter Permit() will wait and a second one will either
```
Comment (alculquicondor) [inline test/integration/scheduler/framework_test.go]: Add a TODO for making each case independent (not share a scheduler)

File: test/integration/scheduler/framework_test.go [hunk 4]
```diff
@@ -1309,6 +1306,8 @@ func TestCoSchedulingWithPermitPlugin(t *testing.T) {
 		waitReject bool
 		waitAllow  bool
 	}{
+		// TODO Separate these two subtests into two tests so they do not share the test scheduler.
```
Comment (alculquicondor) [inline test/integration/scheduler/framework_test.go]: That's not exactly what we want.
You could have a single `Test`, but just init the scheduler inside the loop.

**Review by alculquicondor — COMMENTED** [review]
/lgtm

/hold
for the nit if you have time to tackle it.

File: test/integration/scheduler/framework_test.go (hunk 4 above)
Comment (alculquicondor) [reply test/integration/scheduler/framework_test.go]: You can just leave the implementation details out of the TODO. Simply say: "make the subtests not share scheduler instances"
