### PR TITLE
flexvolume prober: trigger plugin init only for the relevant plugin

### LINKED ISSUE #58352: Automatic plugin discovery should trigger plugin init only for the relevant plugin (and not to all the existing plugins)
/kind bug

**What happened**:
When you update a specific plugin in the /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ kubernetes will trigger init to all the plugins in the  /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ directory.
For example if you have the IBM flexvolume plugin installed in /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ibm~ubiquity-k8s-flex/ubiquity-k8s-flex, and after a while you update this ubiquity-k8s-flex plugin then the automatic plugin discovery will trigger ubiquity-k8s-flex init, BUT it will also trigger init for all the other plugins in  /usr/libexec/kubernetes/kubelet-plugins/volume/exec directory.

**What you expected to happen**:
The automatic discovery should trigger init only to the specific plugin directory that was updated, and not to all the plugins in the k8s plugin directory.

BTW I discussed about it with Cheng Xing from google and he suggested to open this ticket.

**How to reproduce it (as minimally and precisely as possible)**:
install 2 different k8s plugin(not matter which plugin), then change add a file in the first plugin and you will see in the log that also the second plugin will get the init operation.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.8.4
- Cloud provider or hardware configuration: VM x86
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`):uname -a
Linux k8s-shay-v18-master 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
root@k8s-shay-v18-master:~# dpkg -l | grep kube
ii  kubeadm                             1.8.4-00                                   amd64        Kubernetes Cluster Bootstrapping Tool
ii  kubectl                             1.8.4-00                                   amd64        Kubernetes Command Line Tool
ii  kubelet                             1.8.4-00                                   amd64        Kubernetes Node Agent
ii  kubernetes-cni                      0.5.1-00                                   amd64        Kubernetes CNI

### PR DESCRIPTION
**Pull request by linyouchong**
**What this PR does / why we need it**:
The automatic discovery trigger init only to the specific plugin directory that was updated, and not to all the plugins in the flexvolume plugin directory.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #58352

**Special notes for your reviewer**:
NONE

Release note:
```release-note
flexvolume: trigger plugin init only for the relevant plugin while probe
```

### CODE REVIEW

**Comment by linyouchong** [comment]
/sig storage
@verult PTAL

File: pkg/volume/flexvolume/probe.go [hunk 1]
```diff
@@ -127,48 +140,87 @@ func (prober *flexVolumeProber) handleWatchEvent(event fsnotify.Event) error {
...
+				return nil
+			}
+			if len(parts) == 2 && executableName != parts[1] {
+				return nil
+			}
+			if parentInfo.IsDir() && parentBaseName[0] != '.' {
+				probeEvent := volume.ProbeEvent{
+					Op: volume.AddOrUpdate,
+				}
+				plugin, pluginErr := prober.factory.NewFlexVolumePlugin(prober.pluginDir, parentInfo.Name())
```
Comment (verult) [inline pkg/volume/flexvolume/probe.go]: Plugin should not be initialized inside the filesystem watch handler, for two reasons:

1. The handler has to be very light, and ideally it only provides a status update for the main Probe() goroutine to process. A heavy handler delays the processing of inotify events.
1. Typically multiple inotify events are triggered when a file is created or modified. This will cause a driver to be initialized multiple times.

**Review by verult — CHANGES_REQUESTED** [review]
Thanks a lot for the PR! My biggest concern is around how plugins are instantiated and how `Probe()` is implemented.

`Probe()` is called by the volume plugin manager to discover Flexvolume plugins, so the bulk of probing logic should be in here. Most of the heavy-lifting involving file operations should be in `Probe()`. This includes things like scanning the plugin directory and instantiating a probed plugin (`NewFlexVolumePlugin()` calls `Init()` on the Flexvolume driver, which ultimately executes the driver file and can take arbitrarily long depending on driver implementation). On the other hand, filesystem watcher handler should be kept fast, and I provided some justifications inline with the handler code.

File: pkg/volume/flexvolume/probe.go [hunk 2]
```diff
@@ -25,31 +25,26 @@ import (
...
 	factory         PluginFactory
 	fs              utilfs.Filesystem
+	probeAllNeeded  bool
+	eventsMap       map[string]volume.ProbeEvent
 }
 
-const (
-	// TODO (cxing) Tune these params based on test results.
-	// watchEventLimit is the max allowable number of processed watches within watchEventInterval.
-	watchEventInterval = 5 * time.Second
```
[the remark this answers is not in the document]
Comment (linyouchong) [reply pkg/volume/flexvolume/probe.go]: for two reasons:
1. `watchEventInterval ` is used in func `updateProbeNeeded()`, but `probeNeeded` is removed
2.  In my approach, we can't miss any event, because `probe()` will not scan the whole pluginDir except the first time it is invoked

File: pkg/volume/flexvolume/probe.go [hunk 3]
```diff
@@ -79,27 +74,44 @@ func (prober *flexVolumeProber) Init() error {
...
+	if prober.probeAllNeeded {
+		events, err := prober.probeAll()
+		prober.probeAllNeeded = false
+		return events, err
 	}
 
+	events = []volume.ProbeEvent{}
+	for k, event := range prober.eventsMap {
+		events = append(events, event)
+		delete(prober.eventsMap, k)
```
[the remark this answers is not in the document]
Comment (linyouchong) [reply pkg/volume/flexvolume/probe.go]: I think it is safe to do this in golang.
https://stackoverflow.com/questions/23229975/is-it-safe-to-remove-selected-keys-from-golang-map-within-a-range-loop

File: pkg/volume/plugins.go [hunk 4]
```diff
@@ -35,12 +35,22 @@ import (
 	"k8s.io/kubernetes/pkg/util/mount"
 )
 
+type Operation uint32
+type ProbeEvent struct {
+	Plugin     VolumePlugin // VolumePlugin that was added/updated/removed.
+	PluginName string
```
[the remark this answers is not in the document]
Comment (linyouchong) [reply pkg/volume/plugins.go]: if `Op` is `Remove`, `PluginName` will be set, and Plugin is nil

**Comment by linyouchong** [comment]
@verult fixed, PTAL

File: pkg/volume/flexvolume/probe.go [hunk 5]
```diff
@@ -127,48 +173,59 @@ func (prober *flexVolumeProber) handleWatchEvent(event fsnotify.Event) error {
...
+				return err
+			}
 		}
-	} else if eventOpIs(event, fsnotify.Create) {
-		if err := prober.addWatchRecursive(eventPathAbs); err != nil {
-			return err
+	}
+
+	// event about subdir of pluginDirAbs
+	if parentPathAbs == pluginDirAbs {
```
Comment (verult) [inline pkg/volume/flexvolume/probe.go]: If anything inside a driver directory changes, even if it's many levels of subdirectories in, the driver should re-initialize. With your logic, newly added subdirectories inside a driver directory won't be watched. I believe the existing logic already works, please correct me if I'm wrong.

File: pkg/volume/flexvolume/probe_test.go [hunk 6]
```diff
@@ -101,18 +98,17 @@ func TestProberAddDriver(t *testing.T) {
 	watcher.TriggerEvent(fsnotify.Create, fp)
 
 	// Act
-	updated, plugins, err = prober.Probe()
+	events, err = prober.Probe()
 
 	// Assert
-	assert.True(t, updated)
-	assert.Equal(t, 2, len(plugins)) // Number of plugins should not change.
+	assert.Equal(t, 0, len(events)) // Number of plugins should not change.
```
Comment (verult) [inline pkg/volume/flexvolume/probe_test.go]: Comment no longer applies

File: pkg/volume/flexvolume/probe_test.go [hunk 7]
```diff
@@ -169,49 +164,18 @@ func TestProberMultipleEvents(t *testing.T) {
 	}
 
 	// Act
-	updated, _, err := prober.Probe()
+	events, err := prober.Probe()
 
 	// Assert
-	assert.True(t, updated)
+	assert.Equal(t, 2, len(events))
```
Comment (verult) [inline pkg/volume/flexvolume/probe_test.go]: Shouldn't it be 1, since it's the same driver?

**Review by verult — CHANGES_REQUESTED** [review]
The bulk of the logic is good. Three themes in my comments:

- If there's a file change in any of the subdirectories of a driver directory (regardless of how nested it is), the driver should be re-initialized
- Keep locking to a minimum
- More unit tests for new functionality

File: pkg/volume/flexvolume/probe_test.go (hunk 7 above)
Comment (linyouchong) [reply pkg/volume/flexvolume/probe_test.go]: `initTestEnvironment(t)` create one driver

File: pkg/volume/flexvolume/probe.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (linyouchong) [reply pkg/volume/flexvolume/probe.go]: I thought for a long time, and can't find any remedy after missing some event. I think we only need to consider the normal situation, malicious attacks as a security issue should be resolved from a higher level.

File: pkg/volume/flexvolume/probe.go (hunk 5 above)
Comment (linyouchong) [reply pkg/volume/flexvolume/probe.go]: Yes, you are right.

**Comment by linyouchong** [comment]
@verult Thank you very much for your reviews, I learned a lot.
I have been fixed them, and PTAL!

**Comment by shay-berman** [comment]
Hello

what is the status of this PR?
on which k8s version its going to be merged?

thanks

File: pkg/volume/flexvolume/probe.go [hunk 8]
```diff
@@ -127,46 +157,93 @@ func (prober *flexVolumeProber) handleWatchEvent(event fsnotify.Event) error {
...
+	eventRelPathToPluginDir, err := filepath.Rel(pluginDirAbs, eventPathAbs)
+	if err != nil {
+		return err
+	}
+
+	// event inside specific driver dir
+	if len(eventRelPathToPluginDir) > 0 {
+		driverDirName := topDirName(eventRelPathToPluginDir)
+		driverDirAbs := filepath.Join(pluginDirAbs, driverDirName)
+		if len(driverDirAbs) > 0 {
```
Comment (verult) [inline pkg/volume/flexvolume/probe.go]: I don't think this check is necessary - pluginDirAbs always exists

File: pkg/volume/flexvolume/probe.go [hunk 9]
```diff
@@ -127,46 +157,93 @@ func (prober *flexVolumeProber) handleWatchEvent(event fsnotify.Event) error {
...
+			parts := strings.Split(driverDirName, "~")
```
Comment (verult) [inline pkg/volume/flexvolume/probe.go]: nit: Could you separate the logic to compute the path to the executable in a separate helper function? Easier to read that way

File: pkg/volume/flexvolume/probe_test.go [hunk 10]
```diff
@@ -38,81 +38,139 @@ func TestProberExistingDriverBeforeInit(t *testing.T) {
...
+	watcher.TriggerEvent(fsnotify.Remove, driverPath)
+
+	// Act
+	events, err = prober.Probe()
 
 	// Assert
-	assert.True(t, updated)
-	assert.Equal(t, 2, len(plugins)) // Number of plugins should not change.
+	assert.Equal(t, 1, len(events))
+	assert.Equal(t, volume.ProbeRemove, events[0].Op)
```
Comment (verult) [inline pkg/volume/flexvolume/probe_test.go]: I'm surprised `op` isn't `ProbeAddOrUpdate`, because the `driverPath` event is triggered last. If this is the case, maybe delete the executable, probe and test, delete the driver dir and probe again

File: pkg/volume/flexvolume/probe_test.go [hunk 11]
```diff
@@ -154,7 +211,37 @@ func TestRemovePluginDir(t *testing.T) {
 	assert.Equal(t, pluginDir, watcher.watches[len(watcher.watches)-1])
 }
 
-// Issue multiple events and probe multiple times. Should give true, false, false...
+// Issue an event to remove plugindir. New directory should still be watched.
+func TestNestedDriverDir(t *testing.T) {
+	// Arrange
+	_, fs, watcher, _ := initTestEnvironment(t)
+	// Assert
+	assert.Equal(t, 2, len(watcher.watches)) // 2 from initial setup
```
Comment (verult) [inline pkg/volume/flexvolume/probe_test.go]: nit: It's not necessary to test functions written in the test

File: pkg/volume/flexvolume/probe_test.go [hunk 12]
```diff
@@ -154,7 +211,37 @@ func TestRemovePluginDir(t *testing.T) {
 	assert.Equal(t, pluginDir, watcher.watches[len(watcher.watches)-1])
 }
 
-// Issue multiple events and probe multiple times. Should give true, false, false...
+// Issue an event to remove plugindir. New directory should still be watched.
+func TestNestedDriverDir(t *testing.T) {
```
Comment (verult) [inline pkg/volume/flexvolume/probe_test.go]: Thanks for adding this test!

**Review by verult — CHANGES_REQUESTED** [review]
The unit tests are great, most of the logic looks good

File: pkg/volume/flexvolume/probe_test.go [hunk 13]
```diff
@@ -38,81 +38,139 @@ func TestProberExistingDriverBeforeInit(t *testing.T) {
...
 	// Act
-	updated, plugins, err = prober.Probe()
+	events, err = prober.Probe()
+
+	// Assert
+	assert.Equal(t, 1, len(events))
+	assert.Equal(t, volume.ProbeAddOrUpdate, events[0].Op)
+	assert.NoError(t, err)
+
+	// Call probe again, should 0 event.
```
[the remark this answers is not in the document]
Comment (linyouchong) [reply pkg/volume/flexvolume/probe_test.go]: fixed

File: pkg/volume/flexvolume/probe.go [hunk 14]
```diff
@@ -60,8 +53,8 @@ func GetDynamicPluginProber(pluginDir string) volume.DynamicPluginProber {
 }
 
 func (prober *flexVolumeProber) Init() error {
-	prober.testAndSetProbeNeeded(true)
-	prober.lastUpdated = time.Now()
+	prober.testAndSetProbeAllNeeded(true)
```
[the remark this answers is not in the document]
Comment (linyouchong) [reply pkg/volume/flexvolume/probe.go]: fixed, `testAndSetProbeAllNeeded()` will be removed

File: pkg/volume/flexvolume/probe.go [hunk 15]
```diff
@@ -73,47 +66,84 @@ func (prober *flexVolumeProber) Init() error {
...
 
-	files, err := prober.fs.ReadDir(prober.pluginDir)
-	if err != nil {
-		return false, nil, fmt.Errorf("Error reading the Flexvolume directory: %s", err)
+	return prober.probeMap()
+}
+
+func (prober *flexVolumeProber) probeMap() (events []volume.ProbeEvent, err error) {
+	prober.mutex.Lock()
+	defer prober.mutex.Unlock()
```
[the remark this answers is not in the document]
Comment (linyouchong) [reply pkg/volume/flexvolume/probe.go]: TODO added

File: pkg/volume/flexvolume/probe.go [hunk 16]
```diff
@@ -127,46 +157,93 @@ func (prober *flexVolumeProber) handleWatchEvent(event fsnotify.Event) error {
...
+				return err
+			}
 		}
-		if err := prober.addWatchRecursive(pluginDirAbs); err != nil {
-			return err
+		return nil
+	}
+
+	// event of subdir of pluginDirAbs
+	if parentPathAbs == pluginDirAbs {
```
[the remark this answers is not in the document]
Comment (linyouchong) [reply pkg/volume/flexvolume/probe.go]: If a driver directory is created under pluginDir After  prober initialization, I think we should add a watch, according to the original code: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/flexvolume/probe.go#L146

File: pkg/volume/flexvolume/probe.go [hunk 17]
```diff
@@ -127,46 +157,93 @@ func (prober *flexVolumeProber) handleWatchEvent(event fsnotify.Event) error {
...
 
-	prober.updateProbeNeeded()
+	eventRelPathToPluginDir, err := filepath.Rel(pluginDirAbs, eventPathAbs)
+	if err != nil {
+		return err
+	}
+
+	// event inside specific driver dir
+	if len(eventRelPathToPluginDir) > 0 {
+		driverDirName := topDirName(eventRelPathToPluginDir)
```
[the remark this answers is not in the document]
Comment (linyouchong) [reply pkg/volume/flexvolume/probe.go]: good idea!

File: pkg/volume/flexvolume/probe.go (hunk 8 above)
Comment (linyouchong) [reply pkg/volume/flexvolume/probe.go]: yes, The check will be removed

File: pkg/volume/flexvolume/probe.go (hunk 9 above)
Comment (linyouchong) [reply pkg/volume/flexvolume/probe.go]: done!

File: pkg/volume/flexvolume/probe_test.go (hunk 10 above)
Comment (linyouchong) [reply pkg/volume/flexvolume/probe_test.go]: driverPath event will return fast, and will not trigger `updateEventsMap`
`
	// event of subdir of pluginDirAbs
	if parentPathAbs == pluginDirAbs {
		// dir is created in pluginDirAbs directly
		if eventOpIs(event, fsnotify.Create) {
			if err := prober.addWatchRecursive(eventPathAbs); err != nil {
				return err
			}
		}
		return nil
	}
`

**Comment by linyouchong** [comment]
@verult PR updated, PTAL, Thank you!

File: pkg/volume/flexvolume/probe.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (verult) [reply pkg/volume/flexvolume/probe.go]: OK, I'm guessing it's because `updateEventMap()` reads `probeAllNeeded`.

File: pkg/volume/flexvolume/probe.go (hunk 16 above)
[the remark this answers is not in the document]
Comment (verult) [reply pkg/volume/flexvolume/probe.go]: But it already does without this check: the check at line 193 (`if eventOpIs(event, fsnotify.Create)`) applies for a newly created driver directory, since the pluginDir is always under watch.

File: pkg/volume/flexvolume/probe_test.go (hunk 10 above)
Comment (verult) [reply pkg/volume/flexvolume/probe_test.go]: Gotcha. What if the driver directory gets renamed? The plugin name would change so we'd want to trigger an ProbeAddOrUpdate event. IMO it's safer to not return fast, what do you think?

File: pkg/volume/flexvolume/probe.go [hunk 18]
```diff
@@ -127,46 +157,78 @@ func (prober *flexVolumeProber) handleWatchEvent(event fsnotify.Event) error {
...
-		prober.testAndSetProbeNeeded(true)
-		prober.lastUpdated = time.Now()
-		prober.watchEventCount = 1
-	} else if prober.watchEventCount < watchEventLimit {
-		prober.testAndSetProbeNeeded(true)
-		prober.watchEventCount++
+// getExecutableName returns the executableName of a flex plugin
+func getExecutableName(driverDirName string) string {
+	parts := strings.Split(driverDirName, "~")
+	return parts[len(parts)-1]
```
Comment (verult) [inline pkg/volume/flexvolume/probe.go]: nit: You could also do the join here and return the abs path :)

File: pkg/volume/flexvolume/probe.go (hunk 16 above)
[the remark this answers is not in the document]
Comment (linyouchong) [reply pkg/volume/flexvolume/probe.go]: oh ,got it !

File: pkg/volume/flexvolume/probe_test.go (hunk 10 above)
Comment (linyouchong) [reply pkg/volume/flexvolume/probe_test.go]: I think we should trigger ProbeRemove event in 2 cases:
1. The driverDir is removed
2. The driver executable is removed
other case we should trigger ProbeAddOrUpdate event

Comment (verult) [reply pkg/volume/flexvolume/probe_test.go]: I'm OK with either this or the previous logic (only trigger ProbeRemove when executable is removed). If the dir is removed, the executable will be removed too. This logic would trigger two ProbeRemove events, which is OK.

**Comment by verult** [comment]
/lgtm

PTAL @chakri-nelluri @jingxu97 

@linyouchong we'll eventually need an e2e test to test the driver isolation behavior ([here](https://github.com/kubernetes/kubernetes/blob/27df7d184b2183bdccd5c7912032727c627c3517/test/e2e/storage/flexvolume.go#L265)). If you are interested, it'd be very helpful to add it either here or as a separate PR.

**Comment by linyouchong** [comment]
@verult I will add an e2e test as a separate PR.
Does this PR need to be squash?

**Comment by verult** [comment]
/assign @thockin 
for review of `pkg/volume/plugins.go`

**Comment by verult** [comment]
@linyouchong after the e2e test is added, please cherry-pick this to 1.8, 1.9, 1.10 as well (instructions [here](https://github.com/kubernetes/community/blob/master/contributors/devel/cherry-picks.md))

**Comment by linyouchong** [comment]
@verult ok, I am working on it

**Comment by shay-berman** [comment]
thanks for fixing this issue
i guess it will be part of k8s v1.11?

btw is the fix relevant only for flexvolume plugins or its generic for all plugins?

**Comment by verult** [comment]
Yep it'll be part of 1.11. @linyouchong any update on the e2e tests?

This is only relevant for Flexvolume - other plugins don't have a filesystem watch for scanning plugins

**Comment by linyouchong** [comment]
@verult I am very sorry for the delay, for some reason, I can't commit my test code right now.
May be one or two weeks later.

**Comment by linyouchong** [comment]
@verult, e2e test is added, PTAL
https://github.com/kubernetes/kubernetes/pull/66206
