### PR TITLE
Promote PodDisruptionBudget to policy/v1

### LINKED ISSUE #95083: Disruption controller handles PodDisruptionBudget with empty selector incorrectly
**What happened**:

[The disruption controller](https://sourcegraph.com/github.com/kubernetes/kubernetes@0f39af90ed39794ceea426aa0f77de67b1392308/-/blob/pkg/controller/disruption/disruption.go#L69-L101) that enforces _PodDisruptionBudgets_ interprets an empty label selector incorrectly—in conflict with how the API machinery treats such an empty selector—defeating attempts to cover all pods in a namespace with a _PDB_.

In a namespace with at least one pod running, create two _PodDisruptionBudgets_:
```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: inconseqential
spec:
  # NB: The "selector" field is absent.
  minAvailable: 1
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: total
spec:
  selector: {}
  minAvailable: 1
```
I named these "inconsequential" and "total" to clarify their intended interpretation and effect:
- _PDB_ "inconsequential" has no selector, and selects no pods.  
  Since [the `PodDisruptionBudget.Selector` field is optional](https://github.com/kubernetes/api/blob/master/policy/v1beta1/types.go#L34-L37), the validation procedure [allows its omission](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/pkg/apis/policy/validation/validation.go#L66).
- _PDB_ "total" has an empty selector, selecting all pods.  
  An empty selector—one that imposes no restricting constraints—[selects everything](https://sourcegraph.com/github.com/kubernetes/apimachinery@master/-/blob/pkg/apis/meta/v1/helpers.go#L38-L40).

[The disruption controller uses the _PDB_'s selector](https://sourcegraph.com/github.com/kubernetes/kubernetes@0f39af90ed39794ceea426aa0f77de67b1392308/-/blob/pkg/controller/disruption/disruption.go#L470-L485) to find pods covered by the budget. There, it mistakenly interprets [the `v1.Labels.Empty` function returning true as meaning that the selector covers no pods](https://sourcegraph.com/github.com/kubernetes/kubernetes@0f39af90ed39794ceea426aa0f77de67b1392308/-/blob/pkg/controller/disruption/disruption.go#L474-L476).
```go
sel, err := metav1.LabelSelectorAsSelector(pdb.Spec.Selector)
if sel.Empty() {
	return []*v1.Pod{}, nil
}
```
Note that [`labels.Selector.Empty`](https://sourcegraph.com/github.com/kubernetes/apimachinery@master/-/blob/pkg/labels/selector.go#L40-L41) means something different. Quoting the documentation:
> Empty returns true if this selector does not restrict the selection space.

That is, the empty label selector selects the universe. Adding restrictions—taking it from empty to populated—narrows its scope, selecting fewer target objects. The `labels.nothingSelector` returned by [`labels.Nothing`](https://sourcegraph.com/github.com/kubernetes/apimachinery@master/-/blob/pkg/labels/selector.go#L81-L84) is [_not_ empty](https://sourcegraph.com/github.com/kubernetes/apimachinery@master/-/blob/pkg/labels/selector.go#L72). It is as full as can be, with so many restrictions that no target can satisfy it. By contrast, the selector returned by [`labels.Everything`](https://sourcegraph.com/github.com/kubernetes/apimachinery@master/-/blob/pkg/labels/selector.go#L64-L67) is empty, because [it contains no restrictions](https://sourcegraph.com/github.com/kubernetes/apimachinery@master/-/blob/pkg/labels/selector.go#L265-L271).

Bringing this back to _PodDisruptionBudget_, a budget with no selector (`PodDisruptionBudget.Selector` is nil) uses `labels.Nothing`. A budget with a present but empty selector (`PodDisruptionBudget.Selector` is non-nil, but an empty map) uses `lables.Everything`. Even though `lables.Everything` is empty, that does not mean that it selects nothing. That means that it imposes no restrictions, and therefore selects the entire universe.

Looking at the _kubectl describe poddisruptionbudgets_ output, we can see this mistaken interpretation:
```
Name:           inconseqential
Namespace:      test
Min available:  1
Selector:       <unset>
Status:
    Allowed disruptions:  0
    Current:              0
    Desired:              1
    Total:                0
Events:
  Type    Reason  Age                From               Message
  ----    ------  ----               ----               -------
  Normal  NoPods  17s (x3 over 39s)  controllermanager  No matching pods found


Name:           total
Namespace:      test
Min available:  1
Selector:       <none>
Status:
    Allowed disruptions:  0
    Current:              0
    Desired:              1
    Total:                0
Events:
  Type    Reason  Age               From               Message
  ----    ------  ----              ----               -------
  Normal  NoPods  3s (x5 over 38s)  controllermanager  No matching pods found
```
Observe that _PDB_ "total" matches no pods, even though there are pods running in that namespace. Its selector is described as "\<none\>", which is how the API machinery's `v1.FormatLabelSelector` [shows a selector with no restrictions](https://sourcegraph.com/github.com/kubernetes/kubernetes/-/blob/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go#L173-L176). There, "none" means "nothing less than the universe".

**What you expected to happen**:

_PDB_ "total" defined above should have covered all the pods in the namespace, instead of none of them.

**How to reproduce it (as minimally and precisely as possible)**:

1. Choose a namespace with at least one running pod.
1. Create a _PodDisruptionBudget_ similar to "total" above, with its "selector" field set to an empty YAML sequence or JSON object (`{}`).
1. Inspect the _PodDisruptionBudget_'s status via _kubectl describe_ or _kubectl get poddisruptionbudget total --output=jsonpath='{.status.expectedPods}'_.
1. Observe that the "expected pods" count is zero, instead of the count of the pods running in the namespace (assuming use of the `PodDisruptionBudget.MinAvailable` field with an integer value).

**Anything else we need to know?**:
This code in the disruption controller came in with commit d60ba3c6e2b7d57441405a108fbfe2b8e38495cc as part of #25921. @davidopp noted in review twice (https://github.com/kubernetes/kubernetes/pull/25921#discussion_r70173015 and https://github.com/kubernetes/kubernetes/pull/25921#discussion_r70173627) that an empty selector matches everything. @mml responded (https://github.com/kubernetes/kubernetes/pull/25921#discussion_r70309635) that he was mimicking behavior from elsewhere, and that we'd trap empty selectors during validation, but as of today we don't. There's also [a comment in the code](https://github.com/kubernetes/kubernetes/pull/25921#discussion_r70309635) that clarifies that @mml intended an empty selector to select nothing, rather than everything.
> // If a PDB with a nil or empty selector creeps in, it should match nothing, not everything.

If we don't intend for _PDBs_ with empty selectors to be meaningful, we should make the `PodDisruptionBudget.Selector` field mandatory, and validate that it's not empty upon creation or update. See kubernetes/enhancements#904 for the latest graduation criteria for _PodDisruptionBudget_.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T21:51:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:  
  AWS EC2
- OS (e.g: `cat /etc/os-release`):  
```
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2605.4.0
VERSION_ID=2605.4.0
BUILD_ID=2020-09-14-1802
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2605.4.0 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`):  
  `Linux ip-10-3-2-117.us-east-2.compute.internal 5.4.65-flatcar #1 SMP Mon Sep 14 17:27:17 -00 2020 x86_64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz GenuineIntel GNU/Linux`
- Install tools:  
  _kops_
- Network plugin and version (if this is a network-related bug):  
  Calico version 3.15.3

### PR DESCRIPTION
**Pull request by mortent**
#### What type of PR is this?
/kind api-change
/kind feature

#### What this PR does / why we need it:
This promotes `PodDisruptionBudget` resource to `policy/v1` based on https://github.com/kubernetes/enhancements/issues/85 and detailed description in https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/85-Graduate-PDB-to-Stable

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/95083

#### Special notes for your reviewer:
This replaces an older PR at https://github.com/kubernetes/kubernetes/pull/81571. 

#### Does this PR introduce a user-facing change?

```release-note
The PodDisruptionBudget API has been promoted to policy/v1 with no schema changes. The only functional change is that an empty selector (`{}`) written to a policy/v1 PodDisruptionBudget now selects all pods in the namespace. The behavior of the policy/v1beta1 API remains unchanged. The policy/v1beta1 PodDisruptionBudget API is deprecated and will no longer be served in 1.25+.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/85-Graduate-PDB-to-Stable
```

### CODE REVIEW

File: pkg/apis/policy/install/install.go [hunk 1]
```diff
@@ -34,5 +35,6 @@ func init() {
 func Install(scheme *runtime.Scheme) {
 	utilruntime.Must(policy.AddToScheme(scheme))
 	utilruntime.Must(v1beta1.AddToScheme(scheme))
-	utilruntime.Must(scheme.SetVersionPriority(v1beta1.SchemeGroupVersion))
+	utilruntime.Must(v1.AddToScheme(scheme))
+	utilruntime.Must(scheme.SetVersionPriority(v1beta1.SchemeGroupVersion, v1.SchemeGroupVersion))
```
Comment (soltysh) [inline pkg/apis/policy/install/install.go:39]: v1 should always be before v1beta1

File: pkg/features/kube_features.go [hunk 2]
```diff
@@ -735,7 +735,7 @@ var defaultKubernetesFeatureGates = map[featuregate.Feature]featuregate.FeatureS
 	WindowsEndpointSliceProxying:                   {Default: false, PreRelease: featuregate.Alpha},
 	StartupProbe:                                   {Default: true, PreRelease: featuregate.GA, LockToDefault: true}, // remove in 1.23
 	AllowInsecureBackendProxy:                      {Default: true, PreRelease: featuregate.Beta},
-	PodDisruptionBudget:                            {Default: true, PreRelease: featuregate.Beta},
+	PodDisruptionBudget:                            {Default: true, PreRelease: featuregate.GA, LockToDefault: true},
```
Comment (soltysh) [inline pkg/features/kube_features.go:738]: I'd consider this bit in a separate commit.

File: staging/src/k8s.io/api/policy/v1/types.go [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+	DesiredHealthy int32 `json:"desiredHealthy" protobuf:"varint,5,opt,name=desiredHealthy"`
+
+	// total number of pods counted by this disruption budget
+	ExpectedPods int32 `json:"expectedPods" protobuf:"varint,6,opt,name=expectedPods"`
+}
+
+// +genclient
+// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
+// +k8s:prerelease-lifecycle-gen:introduced=1.5
+// +k8s:prerelease-lifecycle-gen:deprecated=1.22
```
Comment (soltysh) [inline staging/src/k8s.io/api/policy/v1/types.go:84]: Drop these, they are not needed.

File: staging/src/k8s.io/api/policy/v1/types.go [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+	// +optional
+	Spec PodDisruptionBudgetSpec `json:"spec,omitempty" protobuf:"bytes,2,opt,name=spec"`
+	// Most recently observed status of the PodDisruptionBudget.
+	// +optional
+	Status PodDisruptionBudgetStatus `json:"status,omitempty" protobuf:"bytes,3,opt,name=status"`
+}
+
+// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
+// +k8s:prerelease-lifecycle-gen:introduced=1.5
+// +k8s:prerelease-lifecycle-gen:deprecated=1.22
```
Comment (soltysh) [inline staging/src/k8s.io/api/policy/v1/types.go:102]: Ditto.

File: staging/src/k8s.io/api/policy/v1beta1/types.go [hunk 5]
```diff
@@ -84,6 +84,8 @@ type PodDisruptionBudgetStatus struct {
 // +k8s:prerelease-lifecycle-gen:introduced=1.5
 // +k8s:prerelease-lifecycle-gen:deprecated=1.22
 
+// DEPRECATED - This group version of PodDisruptionBudget is deprecated by policy/v1/PodDisruptionBudget. See
+// the release notes for more information.
```
Comment (soltysh) [inline staging/src/k8s.io/api/policy/v1beta1/types.go:88]: Not needed, this is handled by the above tags automatically.

**Review by soltysh — CHANGES_REQUESTED** [review]
I left you some initial comments, you're also missing necessary changes to `pkg/api/testing/defaulting_test.go` which you can see from unit-test failure from that package.

File: pkg/apis/policy/install/install.go (hunk 1 above)
Comment (mortent) [reply pkg/apis/policy/install/install.go:39]: So it seems like we should prefer v1beta1 now and then switch in the next release. Ref: https://github.com/kubernetes/kubernetes/pull/95718#discussion_r520969477

Comment (soltysh) [reply pkg/apis/policy/install/install.go:39]: Fair, we'll switch in the next release. Add a todo here.

File: staging/src/k8s.io/api/policy/v1beta1/types.go [hunk 6]
```diff
@@ -84,6 +84,8 @@ type PodDisruptionBudgetStatus struct {
 // +k8s:prerelease-lifecycle-gen:introduced=1.5
 // +k8s:prerelease-lifecycle-gen:deprecated=1.22
```
Comment (janetkuo) [inline staging/src/k8s.io/api/policy/v1beta1/types.go:85]: You can use this to indicate which API users should use instead 

```
// +k8s:prerelease-lifecycle-gen:replacement=policy,v1,PodDisruptionBudget
```

Comment (janetkuo) [inline staging/src/k8s.io/api/policy/v1beta1/types.go:85]: Should we announce deprecation in 1.21 since policy/v1. PodDisruptionBudget would be available?

File: staging/src/k8s.io/api/policy/v1/types.go (hunk 3 above)
Comment (janetkuo) [reply staging/src/k8s.io/api/policy/v1/types.go:84]: Good catch

File: staging/src/k8s.io/api/policy/v1beta1/types.go (hunk 5 above)
Comment (mortent) [reply staging/src/k8s.io/api/policy/v1beta1/types.go]: Removed

File: pkg/features/kube_features.go (hunk 2 above)
Comment (mortent) [reply pkg/features/kube_features.go]: I have removed this from the PR.

File: pkg/apis/policy/install/install.go (hunk 1 above)
Comment (mortent) [reply pkg/apis/policy/install/install.go:40]: Added a TODO here.

File: staging/src/k8s.io/api/policy/v1beta1/types.go (hunk 6 above)
Comment (mortent) [reply staging/src/k8s.io/api/policy/v1beta1/types.go:85]: Added.

File: staging/src/k8s.io/api/policy/v1/types.go (hunk 3 above)
Comment (mortent) [reply staging/src/k8s.io/api/policy/v1/types.go:84]: I get errors when I run the code gen if I remove these. Do you know if I need to make other changes to fix it? I'm still trying to understand why this happens.

File: staging/src/k8s.io/api/policy/v1/types.go [hunk 7]
```diff
@@ -0,0 +1,110 @@
...
+type PodDisruptionBudgetSpec struct {
+	// An eviction is allowed if at least "minAvailable" pods selected by
+	// "selector" will still be available after the eviction, i.e. even in the
+	// absence of the evicted pod.  So for example you can prevent all voluntary
+	// evictions by specifying "100%".
+	// +optional
+	MinAvailable *intstr.IntOrString `json:"minAvailable,omitempty" protobuf:"bytes,1,opt,name=minAvailable"`
+
+	// Label query over pods whose evictions are managed by the disruption
+	// budget.
```
[the remark this answers is not in the document]
Comment (liggitt) [reply staging/src/k8s.io/api/policy/v1/types.go:34]: I don't see the selector change proposed in https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/85-Graduate-PDB-to-Stable/README.md#fix-handling-of-empty-selector-in-disruption-controller implemented here

File: staging/src/k8s.io/api/policy/v1/types.go [hunk 8]
```diff
@@ -0,0 +1,110 @@
...
+// +k8s:prerelease-lifecycle-gen:introduced=1.5
+// +k8s:prerelease-lifecycle-gen:deprecated=1.22
+
+// PodDisruptionBudgetList is a collection of PodDisruptionBudgets.
+type PodDisruptionBudgetList struct {
+	metav1.TypeMeta `json:",inline"`
+	// +optional
+	metav1.ListMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`
+	Items           []PodDisruptionBudget `json:"items" protobuf:"bytes,2,rep,name=items"`
+}
```
[the remark this answers is not in the document]
Comment (mortent) [reply staging/src/k8s.io/api/policy/v1/types.go:110]: So can we update the version of Eviction since the v1beta1 is part of the pod API (which is GA)? We had a discussion around this in my previous PR to take PDB to GA: https://github.com/kubernetes/kubernetes/pull/81571#discussion_r318874136 and https://github.com/kubernetes/kubernetes/pull/81571#discussion_r318874373

[the remark this answers is not in the document]
Comment (liggitt) [reply staging/src/k8s.io/api/policy/v1/types.go:110]: We can't change the returned value of the subresource, and most subresources return a specific API type, which is why I thought we couldn't change it. 

The eviction subresource returns v1 Status however, so I *think* we can additionally accept a v1 Eviction type as long as we continue accepting v1beta1 Evictions as well (both v1 and v1beta1 would have to define conversions to the internal Eviction type).

We'd definitely need a test ensuring that both remained accepted.

[the remark this answers is not in the document]
Comment (mortent) [reply staging/src/k8s.io/api/policy/v1/types.go:106]: That makes sense. I've tried to look into this, and I'm struggling to see how we would handle this in the `PodExpansion` interface: https://github.com/kubernetes/kubernetes/blob/27c89b9aec73f66529a497910c460af2b25ab6dd/staging/src/k8s.io/client-go/kubernetes/typed/core/v1/pod_expansion.go#L33
I assume we can't add a separate function on the interface to handle the v1 version of the `Eviction`, so which type would we use here? Or should we be able to just keep the `v1beta1` type here and the `v1` version would be converted?

File: staging/src/k8s.io/api/policy/v1/types.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (mortent) [reply staging/src/k8s.io/api/policy/v1/types.go:34]: Yeah, I haven't done this yet. Just wanted to get the basics in place first. This is next on the list.

File: staging/src/k8s.io/api/policy/v1/types.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (liggitt) [reply staging/src/k8s.io/api/policy/v1/types.go:106]: > I assume we can't add a separate function on the interface to handle the v1 version of the `Eviction`

That's exactly what I'd do. I'd probably add EvictV1 and EvictV1beta1, document EvictV1 to only apply to 1.21+, and mark `Evict` as deprecated to poke people to explicitly select a version (but not remove it any time soon).

[the remark this answers is not in the document]
Comment (mortent) [reply staging/src/k8s.io/api/policy/v1/types.go:106]: Updated the PR so we can accept both v1 Eviction types and v1beta1 Eviction types. This is done by adding additional `pods/evictionv1` and `pods/evictionv1beta1` endpoints and updating the `PodExpansion` with corresponding functions. It also adds test to verify that all endpoints works.

File: pkg/registry/policy/poddisruptionbudget/strategy.go [hunk 9]
```diff
@@ -109,7 +111,8 @@ func (podDisruptionBudgetStatusStrategy) PrepareForUpdate(ctx context.Context, o
 
 // ValidateUpdate is the default update validation for an end user updating status
 func (podDisruptionBudgetStatusStrategy) ValidateUpdate(ctx context.Context, obj, old runtime.Object) field.ErrorList {
-	// TODO: Validate status updates.
-	return field.ErrorList{}
-	// return validation.ValidatePodDisruptionBudgetStatusUpdate(obj.(*policy.PodDisruptionBudget), old.(*policy.PodDisruptionBudget))
+	if requestInfo, found := genericapirequest.RequestInfoFrom(ctx); found && policyapiv1beta1.SchemeGroupVersion.Version == requestInfo.APIVersion {
```
[the remark this answers is not in the document]
Comment (mortent) [reply pkg/registry/policy/poddisruptionbudget/strategy.go]: This change is also in https://github.com/kubernetes/kubernetes/pull/98127, so I will those in here as soon as that PR is merged.

File: staging/src/k8s.io/api/policy/v1/types.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (mortent) [reply staging/src/k8s.io/api/policy/v1/types.go:34]: I have updated the PR with an attempt to address this, but I'm not sure it is correct. So my assumptions are:
 * We can't change the version of PDB used in the controller yet, since we want to update the API first and then only update the controller in the next release.
 * There will existing PDBs stored in etcd, so we also can't change the semantics of an empty selector in the internal type.

The result is that the conversion must happen in the v1 api as we convert between v1 and the internal type.

[the remark this answers is not in the document]
Comment (liggitt) [reply staging/src/k8s.io/api/policy/v1/types.go:34]: > There will existing PDBs stored in etcd, so we also can't change the semantics of an empty selector in the internal type.

etcd stores in v1beta1, not internal. I would expect to make adjustments in the `v1beta1 <-> internal` conversion

[the remark this answers is not in the document]
Comment (liggitt) [reply staging/src/k8s.io/api/policy/v1/types.go:34]: > We can't change the version of PDB used in the controller yet, since we want to update the API first and then only update the controller in the next release.

if you want to add a conformance test, the controller must use the v1 API (conformance tests must pass in clusters with no alpha/beta features or APIs enabled)

File: staging/src/k8s.io/api/policy/v1/types.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (liggitt) [reply staging/src/k8s.io/api/policy/v1/types.go:106]: Hmm... I was hoping `pods/eviction` could accept either `policy/v1` or `policy/v1beta1` Evictions. I can believe that would not play nicely with the apiserver decoding stack, though. And currently, we can only advertise once accepted version in discovery.

@deads2k @lavalamp, any thoughts on what we should do here? To my knowledge, this is the only subresource of a GA endpoint that accepts a beta version. That's unfortunate to advertise forever and have no graduation path (and I worry a little about how the beta subresource type will interact with the "stop serving deprecated beta types automatically" [changes](https://github.com/kubernetes/kubernetes/pull/99362)).

[the remark this answers is not in the document]
Comment (lavalamp) [reply staging/src/k8s.io/api/policy/v1/types.go:106]: We never had anyone need to change the version of a subresource yet. The plan of record from way back in the day was to permit clients to use the Accept: header to request the version they want to see the result in. We should probably be emiting a warning to clients calling this without specifying an accept header, because such clients would start getting something different if we flip to having v1 as the default.

I think we must continue to accept v1beta1 for quite some time.

[the remark this answers is not in the document]
Comment (liggitt) [reply staging/src/k8s.io/api/policy/v1/types.go:106]: > I think we must continue to accept v1beta1 for quite some time.

No disagreement there... this is actually a pretty unique resource that is write-only (doesn't support GET and the result of the write is a v1.Status object), so we could conceivably accept both v1beta1 and v1 Eviction objects.

The question is whether we think that subresource accepting both versions is a good thing to aim for, especially if it is likely to involve fixing up bits in the discovery and endpoint handling stack that have single-version fixed assumptions.

[the remark this answers is not in the document]
Comment (lavalamp) [reply staging/src/k8s.io/api/policy/v1/types.go:106]: Oh this is write-only, that's great!

Sadly I don't see any option other than supporting both for some amount of time? I don't think it's OK to abruptly break old clients.

File: staging/src/k8s.io/api/policy/v1/types.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (mortent) [reply staging/src/k8s.io/api/policy/v1/types.go:34]: That makes sense. I have updated the PR to handle conversion in v1beta1 and updated the controller to use the v1 api.

File: staging/src/k8s.io/api/policy/v1/types.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (mortent) [reply staging/src/k8s.io/api/policy/v1/types.go:106]: So do we want to provide separate endpoints for the different version of the Eviction resource as we currently have in this PR or do we want to see if we can have one endpoint that can accept both the v1 and v1beta1 versions?

If we want to use one endpoint, it seems like that will require changes that are substantial enough that we can't make Eviction v1 in 1.21. So do we want to back out the changes to the Eviction resource from this PR and take just PDBs to GA in 1.21, or do we push everything to 1.22. 1.22 is the automatic deprecation deadline for PDBs?

[the remark this answers is not in the document]
Comment (liggitt) [reply staging/src/k8s.io/api/policy/v1/types.go:106]: > So do we want to provide separate endpoints for the different version of the Eviction resource as we currently have in this PR or do we want to see if we can have one endpoint that can accept both the v1 and v1beta1 versions?

One endpoint that accepts both would be my preference.

> If we want to use one endpoint, it seems like that will require changes that are substantial enough that we can't make Eviction v1 in 1.21. So do we want to back out the changes to the Eviction resource from this PR and take just PDBs to GA in 1.21, or do we push everything to 1.22.

I'm fine with moving out work on promoting eviction to v1 to 1.22.

> 1.22 is the automatic deprecation deadline for PDBs?

That's when their deprecation period starts. It ends in 1.25 and we stop serving them then.

[the remark this answers is not in the document]
Comment (soltysh) [reply staging/src/k8s.io/api/policy/v1/types.go:106]: > I'm fine with moving out work on promoting eviction to v1 to 1.22.

I was told we can't GA from a deprecated version, and we'd need to go through a 2nd beta, isn't that true?

[the remark this answers is not in the document]
Comment (liggitt) [reply staging/src/k8s.io/api/policy/v1/types.go:106]: If 1.22 adds Eviction v1 and marks Eviction v1beta1 deprecated, that seems reasonable. Eviction v1beta1 is an oddball since it's a subresource of a v1 API, so I expect we'll have interesting things to iron out there anyway.

[the remark this answers is not in the document]
Comment (mortent) [reply staging/src/k8s.io/api/policy/v1/types.go:106]: I have backed out the changes for updating Eviction to v1.

[the remark this answers is not in the document]
Comment (liggitt) [reply staging/src/k8s.io/api/policy/v1/types.go:147]: thanks, can you make sure this discussion is captured in an issue associated with the KEP, so we can make sure this happens in 1.22?

[the remark this answers is not in the document]
Comment (mortent) [reply staging/src/k8s.io/api/policy/v1/types.go:147]: Added a comment on the tracking issue: https://github.com/kubernetes/enhancements/issues/85#issuecomment-791591925

File: pkg/registry/core/rest/storage_core.go [hunk 10]
```diff
@@ -111,7 +111,7 @@ func (c LegacyRESTStorageProvider) NewLegacyRESTStorage(restOptionsGetter generi
 	}
 
 	var podDisruptionClient policyclient.PodDisruptionBudgetsGetter
-	if policyGroupVersion := (schema.GroupVersion{Group: "policy", Version: "v1beta1"}); legacyscheme.Scheme.IsVersionRegistered(policyGroupVersion) {
+	if policyGroupVersion := (schema.GroupVersion{Group: "policy", Version: "v1"}); legacyscheme.Scheme.IsVersionRegistered(policyGroupVersion) {
 		var err error
 		podDisruptionClient, err = policyclient.NewForConfig(c.LoopbackClientConfig)
```
Comment (liggitt) [inline pkg/registry/core/rest/storage_core.go:116]: is a nil podDisruptionClient handled properly by eviction REST? if not, we expect policy/v1 to be enabled, so I would make this unconditional

File: pkg/registry/policy/poddisruptionbudget/strategy.go [hunk 11]
```diff
@@ -114,8 +114,8 @@ func (podDisruptionBudgetStatusStrategy) ValidateUpdate(ctx context.Context, obj
 	var apiVersion schema.GroupVersion
 	if requestInfo, found := genericapirequest.RequestInfoFrom(ctx); found {
 		apiVersion = schema.GroupVersion{
-			Group:   requestInfo.APIVersion,
-			Version: requestInfo.APIGroup,
+			Group:   requestInfo.APIGroup,
+			Version: requestInfo.APIVersion,
```
Comment (liggitt) [inline pkg/registry/policy/poddisruptionbudget/strategy.go:118]: this is exciting... can you add a unit test that would have caught this?

File: pkg/apis/policy/v1/doc.go [hunk 12]
```diff
@@ -0,0 +1,25 @@
...
+*/
+
+// +k8s:conversion-gen=k8s.io/kubernetes/pkg/apis/policy
+// +k8s:conversion-gen-external-types=k8s.io/api/policy/v1
+// +k8s:defaulter-gen=TypeMeta
+// +k8s:defaulter-gen-input=../../../../vendor/k8s.io/api/policy/v1
+
+// Package policy is for any kind of policy object.  Suitable examples, even if
+// they aren't all here, are policyv1.PodDisruptionBudget, PodSecurityPolicy,
+// NetworkPolicy, etc.
```
Comment (liggitt) [inline pkg/apis/policy/v1/doc.go:24]: suggest dropping the examples sentence, since PSP and NetworkPolicy won't end up here

File: staging/src/k8s.io/api/policy/v1/types.go [hunk 13]
```diff
@@ -0,0 +1,147 @@
...
+type PodDisruptionBudgetSpec struct {
+	// An eviction is allowed if at least "minAvailable" pods selected by
+	// "selector" will still be available after the eviction, i.e. even in the
+	// absence of the evicted pod.  So for example you can prevent all voluntary
+	// evictions by specifying "100%".
+	// +optional
+	MinAvailable *intstr.IntOrString `json:"minAvailable,omitempty" protobuf:"bytes,1,opt,name=minAvailable"`
+
+	// Label query over pods whose evictions are managed by the disruption
+	// budget.
```
Comment (liggitt) [inline staging/src/k8s.io/api/policy/v1/types.go:34]: Explicitly describe in documentation what `null` and `{}` selectors do. Also update the v1beta1 type documentation to indicate what `null` and `{}` selectors do.

It is extremely likely that some people will try to convert their v1beta1 PDB objects to v1 by simply changing the apiVersion, which will be unfortunate for them if the behavior of an empty selector changes.

File: staging/src/k8s.io/client-go/listers/policy/v1/poddisruptionbudget_expansion.go [hunk 14]
```diff
@@ -0,0 +1,73 @@
...
+// PodDisruptionBudgetNamespaceLister.
+type PodDisruptionBudgetNamespaceListerExpansion interface{}
+
+// GetPodPodDisruptionBudgets returns a list of PodDisruptionBudgets matching a pod.  Returns an error only if no matching PodDisruptionBudgets are found.
+func (s *podDisruptionBudgetLister) GetPodPodDisruptionBudgets(pod *v1.Pod) ([]*policy.PodDisruptionBudget, error) {
+	var selector labels.Selector
+
+	if len(pod.Labels) == 0 {
+		return nil, fmt.Errorf("no PodDisruptionBudgets found for pod %v because it has no labels", pod.Name)
+	}
```
Comment (liggitt) [inline staging/src/k8s.io/client-go/listers/policy/v1/poddisruptionbudget_expansion.go:45]: can't a v1 PDB with an empty selector match this?

File: staging/src/k8s.io/client-go/listers/policy/v1/poddisruptionbudget_expansion.go [hunk 15]
```diff
@@ -0,0 +1,73 @@
...
+	var pdbList []*policy.PodDisruptionBudget
+	for i := range list {
+		pdb := list[i]
+		selector, err = metav1.LabelSelectorAsSelector(pdb.Spec.Selector)
+		if err != nil {
+			klog.Warningf("invalid selector: %v", err)
+			continue
+		}
+
+		// Unlike the v1beta version, here we let an emty selector match everything.
```
Comment (liggitt) [inline staging/src/k8s.io/client-go/listers/policy/v1/poddisruptionbudget_expansion.go:61]:
```suggestion
		// Unlike the v1beta version, here we let an empty selector match everything.
```

File: staging/src/k8s.io/client-go/listers/policy/v1/poddisruptionbudget_expansion.go (hunk 14 above)
Comment (liggitt) [reply staging/src/k8s.io/client-go/listers/policy/v1/poddisruptionbudget_expansion.go:45]: actually, I'm pretty sure the v1beta1 version is incorrect here as well... a PDB selector could be expressed as a DoesNotExist selector, which could match pods without any labels

File: pkg/apis/policy/v1beta1/conversion.go [hunk 16]
```diff
@@ -0,0 +1,115 @@
...
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/conversion"
+	"k8s.io/kubernetes/pkg/apis/policy"
+)
+
+const (
+	pdbV1beta1Label = "pdb.kubernetes.io/deprecated-v1beta1-empty-selector-match"
+)
+
+func Convert_v1beta1_PodDisruptionBudget_To_policy_PodDisruptionBudget(in *v1beta1.PodDisruptionBudget, out *policy.PodDisruptionBudget, s conversion.Scope) error {
```
Comment (liggitt) [inline pkg/apis/policy/v1beta1/conversion.go:30]: It's simpler to call the generated auto-conversion method first, which will handle all of the boilerplate, then tweak the selector specifically.

Rather than trying to strip the deprecated v1beta1 label specifically, I _think_ we can do two mechanical transformations in each direction by seeing if the input selector is identical to a specific "all" or "none" selector, and translating that into a new specific selector. Something like this:

```go

var (
	internalMatchAllSelector  = &metav1.LabelSelector{}
	internalMatchNoneSelector = &metav1.LabelSelector{
		MatchExpressions: []metav1.LabelSelectorRequirement{{Key: pdbV1beta1Label, Operator: metav1.LabelSelectorOpExists}},
	}

	v1beta1MatchNoneSelector = &metav1.LabelSelector{}
	v1beta1MatchAllSelector  = &metav1.LabelSelector{
		MatchExpressions: []metav1.LabelSelectorRequirement{{Key: pdbV1beta1Label, Operator: metav1.LabelSelectorOpDoesNotExist}},
	}
)

func Convert_v1beta1_PodDisruptionBudget_To_policy_PodDisruptionBudget(in *v1beta1.PodDisruptionBudget, out *policy.PodDisruptionBudget, s conversion.Scope) error {
	if err := autoConvert_v1beta1_PodDisruptionBudget_To_policy_PodDisruptionBudget(in, out, s); err != nil {
		return err
	}

	switch {
	case apiequality.Semantic.DeepEqual(in.Spec.Selector, v1beta1MatchNoneSelector):
		// If the v1beta1 version has a non-nil but empty selector, it should be
		// selecting no pods, even when used with the internal or v1 api. We
		// add a selector that is non-empty but will never match any pods.
		out.Spec.Selector = internalMatchNoneSelector.DeepCopy()
	case apiequality.Semantic.DeepEqual(in.Spec.Selector, v1beta1MatchAllSelector):
		// If the v1beta1 version has our v1beta1-specific "match-all" selector,
		// swap that out for a simpler empty "match-all" selector for v1
		out.Spec.Selector = internalMatchAllSelector.DeepCopy()
	}
	return nil
}

func Convert_policy_PodDisruptionBudget_To_v1beta1_PodDisruptionBudget(in *policy.PodDisruptionBudget, out *v1beta1.PodDisruptionBudget, s conversion.Scope) error {
	if err := autoConvert_policy_PodDisruptionBudget_To_v1beta1_PodDisruptionBudget(in, out, s); err != nil {
		return err
	}

	switch {
	case apiequality.Semantic.DeepEqual(in.Spec.Selector, internalMatchNoneSelector):
		// If the internal version has our v1beta1-specific "match-none" selector,
		// swap that out for a simpler empty "match-none" selector for v1beta1
		out.Spec.Selector = v1beta1MatchNoneSelector.DeepCopy()
	case apiequality.Semantic.DeepEqual(in.Spec.Selector, internalMatchAllSelector):
		// If the internal version has a non-nil but empty selector, we want it to
		// select all pods. We make sure this happens even with the v1beta1 api by
		// adding a non-empty selector that selects all pods.
		out.Spec.Selector = v1beta1MatchAllSelector.DeepCopy()
	}
	return nil
}
```

**Comment by liggitt** [comment]
along with this, we'll want to:
1. merge a change to switch the existing e2e test to use the v1 API
2. follow-up with a change to switch that e2e test to be a conformance test

can you add a commit to this PR to switch the e2e test to use v1, and open a follow-up PR to promote the test to conformance (so we can make sure `pull-kubernetes-conformance-kind-ga-only-parallel` passes on it)?

File: pkg/registry/policy/poddisruptionbudget/strategy.go (hunk 11 above)
Comment (mortent) [reply pkg/registry/policy/poddisruptionbudget/strategy.go:118]: Yeah, I found this because of the unit test.

File: staging/src/k8s.io/client-go/listers/policy/v1/poddisruptionbudget_expansion.go (hunk 14 above)
Comment (mortent) [reply staging/src/k8s.io/client-go/listers/policy/v1/poddisruptionbudget_expansion.go]: Yeah, pods without labels don't actually work properly with PDBs, i.e. a pod without labels will not trigger a PDB reconcile. This is addressed in this PR by removing the check for empty labels in poddisruptionbudget_expansion.go. I also added additional integration tests to verify this behavior for both v1 and v1beta1.

File: staging/src/k8s.io/api/policy/v1/types.go (hunk 13 above)
Comment (mortent) [reply staging/src/k8s.io/api/policy/v1/types.go:34]: Updated.

File: pkg/apis/policy/v1beta1/conversion.go (hunk 16 above)
Comment (mortent) [reply pkg/apis/policy/v1beta1/conversion.go:43]: I have updated the code to first use the auto-conversion and then fix the selector. 

But I think we might need the functionality to strip only the v1beta1 label, since there might be situations we need to convert and the v1beta1 label is not the only element in the selector. Since the selector in PDBs is mutable, I think it would be possible to read a resource as v1beta1, add an additional label to the PDB, and then write it back. If so, we can't rely on the equality checks.

This situation covered by this test: https://github.com/kubernetes/kubernetes/pull/99290/files#diff-ac28b0c739c72c12d59ca4e60b5d43c82c582bc87a005258b2412332d7d72ac3R89.

**Comment by mortent** [comment]
@liggitt I have addressed/responded to the comments, and added a separate commit to move all e2e tests to use the v1 api.
I have created a PR to promote e2e tests to Conformance: https://github.com/kubernetes/kubernetes/pull/84740

File: pkg/apis/policy/v1beta1/conversion.go (hunk 16 above)
Comment (liggitt) [reply pkg/apis/policy/v1beta1/conversion.go:43]: > Since the selector in PDBs is mutable, I think it would be possible to read a resource as v1beta1, add an additional label to the PDB, and then write it back.

I don't think that's an expected use case. Selectors are expected to be completely set by the writer... see https://github.com/kubernetes/kubernetes/issues/92913 and https://github.com/kubernetes/kubernetes/pull/93901

With the all-or-nothing conversion as proposed in #discussion_r589092943, what is the behavior in the following scenarios:

1. empty v1beta1 -> non-empty v1 -> empty v1beta1
    1. `kubectl apply` v1beta1 version of a PDB with an empty selector (`{}`)
    2. `kubectl apply` v1 version of the same PDB with some other selector (`{"matchLabels":{"foo":"bar"}}`) - expect only foo=bar via v1 and v1beta1 on read
    3. `kubectl apply` v1beta1 version of a PDB with an empty selector again (`{}`) - expect no trace of `foo=bar`

2. non-empty v1beta1 -> empty v1 -> non-empty v1beta1
    1. `kubectl apply` v1beta1 version of a PDB with a non-empty selector (`{"matchLabels":{"foo":"bar"}}`) - expect only foo=bar via v1 and v1beta1 on read
    2. `kubectl apply` v1 version of the same PDB with an empty selector (`{}`) - expect no trace of foo=bar
    3. `kubectl apply` v1beta1 version of a PDB with a non-empty selector again (`{"matchLabels":{"foo":"bar"}}`) - expect only foo=bar via v1 and v1beta1 on read

File: staging/src/k8s.io/client-go/listers/policy/v1/poddisruptionbudget_expansion.go [hunk 17]
```diff
@@ -0,0 +1,69 @@
...
+type PodDisruptionBudgetListerExpansion interface {
+	GetPodPodDisruptionBudgets(pod *v1.Pod) ([]*policy.PodDisruptionBudget, error)
+}
+
+// PodDisruptionBudgetNamespaceListerExpansion allows custom methods to be added to
+// PodDisruptionBudgetNamespaceLister.
+type PodDisruptionBudgetNamespaceListerExpansion interface{}
+
+// GetPodPodDisruptionBudgets returns a list of PodDisruptionBudgets matching a pod.
+func (s *podDisruptionBudgetLister) GetPodPodDisruptionBudgets(pod *v1.Pod) ([]*policy.PodDisruptionBudget, error) {
```
Comment (liggitt) [inline staging/src/k8s.io/client-go/listers/policy/v1/poddisruptionbudget_expansion.go:40]: should this be fixed in staging/src/k8s.io/client-go/listers/policy/v1beta1/poddisruptionbudget_expansion.go as well?

```go
if len(pod.Labels) == 0 {
	return nil, fmt.Errorf("no PodDisruptionBudgets found for pod %v because it has no labels", pod.Name)
}
```

**Review by liggitt — COMMENTED** [review]
> Should I update https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go#L787 to list PDB as GA in this PR? I suspect this is why the conformance tests for PDBs fail when running with GA only.

Yes

File: pkg/apis/policy/v1beta1/conversion.go (hunk 16 above)
Comment (liggitt) [reply pkg/apis/policy/v1beta1/conversion.go:43]: for this to behave as expected, I think the selector field has to have patchStrategy=replace

```
diff --git a/staging/src/k8s.io/api/policy/v1/types.go b/staging/src/k8s.io/api/policy/v1/types.go
index 42eab54b3c8..904413203ad 100644
--- a/staging/src/k8s.io/api/policy/v1/types.go
+++ b/staging/src/k8s.io/api/policy/v1/types.go
@@ -34,8 +34,9 @@ type PodDisruptionBudgetSpec struct {
 	// budget.
 	// A nil selector will match no pods, while an empty selector will select
 	// all pods within the namespace.
+	// +patchStrategy=replace
 	// +optional
-	Selector *metav1.LabelSelector `json:"selector,omitempty" protobuf:"bytes,2,opt,name=selector"`
+	Selector *metav1.LabelSelector `json:"selector,omitempty" patchStrategy:"replace" protobuf:"bytes,2,opt,name=selector"`
 
 	// An eviction is allowed if at most "maxUnavailable" pods selected by
 	// "selector" are unavailable after the eviction, i.e. even in absence of
diff --git a/staging/src/k8s.io/api/policy/v1beta1/types.go b/staging/src/k8s.io/api/policy/v1beta1/types.go
index 87c827d342b..4a1d2fee596 100644
--- a/staging/src/k8s.io/api/policy/v1beta1/types.go
+++ b/staging/src/k8s.io/api/policy/v1beta1/types.go
@@ -36,8 +36,9 @@ type PodDisruptionBudgetSpec struct {
 	// A nil selector selects no pods. An empty selector also selects no pods, which
 	// is different than the normal behavior for selectors where an empty selector
 	// does not restrict the selection space.
+	// +patchStrategy=replace
 	// +optional
-	Selector *metav1.LabelSelector `json:"selector,omitempty" protobuf:"bytes,2,opt,name=selector"`
+	Selector *metav1.LabelSelector `json:"selector,omitempty" patchStrategy:"replace" protobuf:"bytes,2,opt,name=selector"`
 
 	// An eviction is allowed if at most "maxUnavailable" pods selected by
 	// "selector" are unavailable after the eviction, i.e. even in absence of
```

@apelisse @jpbetz - does that match your expectations? is there something similar that needs to be specified for server-side apply to treat this field as atomic, or is that the default?

Comment (liggitt) [reply pkg/apis/policy/v1beta1/conversion.go:43]: empty_v1beta1.yaml:
```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: empty-v1beta1
spec:
  minAvailable: 2
  selector: {}
```

nonempty_v1.yaml:
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: empty-v1beta1
spec:
  minAvailable: 2
  selector:
    matchLabels:
      foo: bar
```


setting patchStrategy=replace and using a new kubectl aware of the go type change works as expected:

```
$ kubectl apply -f empty_v1beta1.yaml 
$ kubectl get -f empty_v1beta1.yaml  -o yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
...
spec:
  minAvailable: 2
  selector: {}

$ kubectl apply -f nonempty_v1.yaml 
$ kubectl get -f nonempty_v1.yaml -o yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
...
spec:
  minAvailable: 2
  selector:
    matchLabels:
      foo: bar

$ kubectl apply -f empty_v1beta1.yaml 
$ kubectl get -f empty_v1beta1.yaml  -o yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
...
spec:
  minAvailable: 2
  selector: {}
```

using an old kubectl that doesn't have the go type change compiled in does not work:

```
$ kubectl-1.19 apply -f empty_v1beta1.yaml 
$ kubectl-1.19 get -f empty_v1beta1.yaml -o yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
...
spec:
  minAvailable: 2
  selector: {}

$ kubectl-1.19 apply -f nonempty_v1.yaml 
$ kubectl-1.19 get -f nonempty_v1.yaml -o yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
...
spec:
  minAvailable: 2
  selector:
    matchExpressions:
    - key: pdb.kubernetes.io/deprecated-v1beta1-empty-selector-match
      operator: Exists
    matchLabels:
      foo: bar

$ kubectl-1.19 apply -f empty_v1beta1.yaml 
$ kubectl-1.19 get -f empty_v1beta1.yaml -o yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
...
spec:
  minAvailable: 2
  selector: {}
```

@apelisse @jpbetz - it looks like we can't change patchStrategy or set patchStrategy=replace on new go types and have old kubectl clients client-side apply correctly?

Comment (liggitt) [reply pkg/apis/policy/v1beta1/conversion.go:43]: kubectl 1.19 sends `"Content-Type: application/merge-patch+json"` when applying to `policy/v1`:
```json
{
    "metadata": {
        "annotations":{
            "kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"name\":\"empty-v1beta1\",\"namespace\":\"default\"},\"spec\":{\"minAvailable\":2,\"selector\":{\"matchLabels\":{\"foo\":\"bar\"}}}}\n"
        }
    },
    "spec":{
        "selector":{
            "matchLabels":{"foo":"bar"}
        }
    }
}
```

kubectl build from this branch sends `"Content-Type: application/strategic-merge-patch+json"` when applying to `policy/v1`, and works properly:
```json
{
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"policy/v1\",\"kind\":\"PodDisruptionBudget\",\"metadata\":{\"annotations\":{},\"name\":\"empty-v1beta1\",\"namespace\":\"default\"},\"spec\":{\"minAvailable\":2,\"selector\":{\"matchLabels\":{\"foo\":\"bar\"}}}}\n"
        }
    },
    "spec":{
        "selector":{
            "matchLabels":{"foo":"bar"}
        }
    }
}
```

Comment (liggitt) [reply pkg/apis/policy/v1beta1/conversion.go:43]: I thought kubectl would read patch info from openapi and send strategic merge patches even on types it did not have compiled in

Comment (liggitt) [reply pkg/apis/policy/v1beta1/conversion.go:43]: fortunately, both old and new kubectl's behave like a champ with `apply --server-side`

File: test/e2e/apps/disruption.go [hunk 18]
```diff
@@ -27,6 +27,7 @@ import (
 
 	appsv1 "k8s.io/api/apps/v1"
 	v1 "k8s.io/api/core/v1"
+	policyv1 "k8s.io/api/policy/v1"
 	policyv1beta1 "k8s.io/api/policy/v1beta1"
```
[the remark this answers is not in the document]
Comment (mortent) [reply test/e2e/apps/disruption.go]: So I think the test failures in #84740 is primarily because the feature flag wasn't updated, so the disruption controller isn't running in those tests. I have updated this PR to address that and will also update #84740.
Another issue here is that some of the pdb e2e tests use the eviction API, which of course is not GA. So I will look at the tests being promoted to conformance in #84740 and make sure those doesn't rely on Eviction. But this means we still need to import `policyv1beta1 "k8s.io/api/policy/v1beta1"` here.

[the remark this answers is not in the document]
Comment (liggitt) [reply test/e2e/apps/disruption.go]: > Another issue here is that some of the pdb e2e tests use the eviction API, which of course is not GA. So I will look at the tests being promoted to conformance in #84740 and make sure those doesn't rely on Eviction. But this means we still need to import `policyv1beta1 "k8s.io/api/policy/v1beta1"` here.

ah, that makes sense for the import. I think we'll want to continue exercising the subresource in the test, there's little use for the PDB API otherwise

File: pkg/apis/policy/v1beta1/conversion.go (hunk 16 above)
Comment (liggitt) [reply pkg/apis/policy/v1beta1/conversion.go:43]: looks like kubectl doesn't send strategic merge patches for unknown types, even if the openapi schema indicates they are supported:

https://github.com/kubernetes/kubernetes/blob/4fccba9e068f31a562f753caf4b37959b4ef829a/staging/src/k8s.io/kubectl/pkg/cmd/apply/patcher.go#L120-L166

I'll open a separate issue to track that, but a fix there will be too late for this to take advantage of. Given that, I think you approach of stripping the deprecated beta label would work well as a default case for the v1beta1->internal conversion (if we don't exactly match one of the well-known selectors). I think we also need to do that check in v1->internal conversion so that when we switch etcd storage to v1 (and never hit this v1beta1 conversion code), we'll catch selectors like that.

Messing around with that in the last commit of https://github.com/liggitt/kubernetes/commits/PromotePDBsToGA seemed to work well.

Comment (seh) [reply pkg/apis/policy/v1beta1/conversion.go:43]: I thought this rang a bell with a problem in _kubecfg_ from two years ago. See https://github.com/bitnami/kubecfg/issues/259#issuecomment-522054301. The related discussion in the "sig-api-machinery" Slack channel starts [here](https://kubernetes.slack.com/archives/C0EG7JC6T/p1565969006291300).

File: staging/src/k8s.io/client-go/listers/policy/v1/poddisruptionbudget_expansion.go (hunk 17 above)
Comment (mortent) [reply staging/src/k8s.io/client-go/listers/policy/v1/poddisruptionbudget_expansion.go:40]: Yeah, I have updated it.

File: pkg/apis/policy/v1beta1/conversion.go (hunk 16 above)
Comment (mortent) [reply pkg/apis/policy/v1beta1/conversion.go:26]: Updated based on the suggested solution at https://github.com/liggitt/kubernetes/commits/PromotePDBsToGA

**Comment by mortent** [comment]
@liggitt The PR is updated and all tests are passing. The conformance tests also pass the `pull-kubernetes-conformance-kind-ga-only-parallel` job on https://github.com/kubernetes/kubernetes/pull/84740. 
I couldn't promote all tests I would have liked to conformance due to the dependencies on the Eviction API. We should make sure that is addressed when we GA Eviction.

**Comment by liggitt** [comment]
flake was https://github.com/kubernetes/kubernetes/issues/99979

**Comment by mortent** [comment]
Flake seems related to https://github.com/kubernetes/kubernetes/issues/96337

**Comment by liggitt** [comment]
flakes were #99911 and https://github.com/kubernetes/kubernetes/pull/94564

**Comment by liggitt** [comment]
integration flake is https://github.com/kubernetes/kubernetes/pull/98116#issuecomment-794256319

**Comment by wilsonehusin** [comment]
hey folks, 1.21 Release Notes team here -- want to check in and disambiguate this line:

> The only functional change is that an empty selector (`{}`) written to a policy/v1 PodDisruptionBudget now selects all pods in the namespace.

does this behavior warrant this note to be in [`ACTION REQUIRED` / Urgent Upgrade Notes](https://github.com/kubernetes/sig-release/blob/master/releases/release-1.21/release-notes/release-notes-draft.md#urgent-upgrade-notes)? I'm not too familiar with how `PodDisruptionBudget` works when given empty selector, and if this potentially creates side effect to end users on `v1beta1` -> `v1`, then we might want to surface this note 😄 

cc @mortent @liggitt

**Comment by liggitt** [comment]
no, there are no side effects to existing v1beta1 consumers
