### PR TITLE
IP validates if a string is a valid IP address 

### LINKED ISSUE #83095: glusterfs, heketi: failed to create volume: failed to update endpoint
**What happened**:
Creation of dynamic volume failed using Kubernetes plugin. 
Volume successfully created and mounted when created by heketi-cli. The problem is most probably on Kubernetes side.

**What you expected to happen**:
Dynamic volume created and bound successfully on Kubernetes. 

**How to reproduce it (as minimally and precisely as possible)**:
1) Prepare configuration to Heketi API and storage class
2) Install Jupyterhub using helm.

Secret:
apiVersion: v1
kind: Secret
metadata:
  name: heketi-secret
  namespace: default
type: "kubernetes.io/glusterfs"
data:
   key: Zfsfvddf1pbjEyMw==
---
Storage class:
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gfs-new
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://qpm-gluster01:8080"
  clusterid: "4f289422a2a7f083aefa1c6239653d98"
  restauthenabled: "true"
  restuser: "admin"
  secretNamespace: "default"
  secretName: "heketi-secret"
  volumetype: "replicate:2"

Jupyther hub PVC:
[root@qpm-k8s-master01 jupyterhub]# kubectl describe persistentvolumeclaims hub-db-dir 
Name:          hub-db-dir
Namespace:     default
StorageClass:  gfs-new
Status:        Pending
Volume:        
Labels:        app=jupyterhub
               chart=jupyterhub-0.8.2
               component=hub
               heritage=Tiller
               release=jhub
Annotations:   volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/glusterfs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    hub-6f94685b5d-qwnhf

**Anything else we need to know?**:
K8S error:

K8S Error:
Events:
  Type     Reason              Age                  From                         Message
  ----     ------              ----                 ----                         -------
  Warning  ProvisioningFailed  71s (x415 over 17h)  persistentvolume-controller  Failed to provision volume with StorageClass "gfs-new": failed to create volume: failed to update endpoint &Endpoints{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:glusterfs-dynamic-e759b6f9-deb1-4a31-b3fd-ad220e5c744d,GenerateName:,Namespace:default,SelfLink:,UID:,ResourceVersion:,Generation:0,CreationTimestamp:0001-01-01 00:00:00 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{gluster.kubernetes.io/provisioned-for-pvc: hub-db-dir,},Annotations:map[string]string{},OwnerReferences:[],Finalizers:[],ClusterName:,Initializers:nil,ManagedFields:[],},Subsets:[{[{qpm-gluster02  <nil> nil} {qpm-gluster01  <nil> nil}] [] [{ 1 TCP}]}],}: <nil>

Heketi log:
Sep 24 22:25:37 qpm-gluster01 systemd[1]: Started Heketi Server.
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: Heketi 8.0.0
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 Loaded ssh executor
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 GlusterFS Application Loaded
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 Started Node Health Cache Monitor
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: Listening on port 8080
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:47 Starting Node Health Status refresh
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:25:47 Check Glusterd service status in node qpm-gluster02
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] WARNING 2019/09/24 22:25:47 Failed to create SSH connection to qpm-gluster02:22: dial tcp 10.20.105.61:22: getsockopt:
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] ERROR 2019/09/24 22:25:47 /src/github.com/heketi/heketi/executors/cmdexec/peer.go:76: dial tcp 10.20.105.61:22: getsoc
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:47 Periodic health check status: node 4784bfe108b9bf66cc7f260dc950af2d up=false
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:25:47 Check Glusterd service status in node qpm-gluster01
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [cmdexec] DEBUG 2019/09/24 22:25:48 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Result: ● glusterd.service - GlusterFS, a clustered file-system server
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Active: active (running) since Tue 2019-09-24 22:25:46 CST; 2s ago
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Docs: man:glusterd(8)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Process: 14278 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, stat
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Main PID: 14280 (glusterd)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: CGroup: /system.slice/glusterd.service
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: ├─14280 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: ├─14361 /usr/sbin/glusterfsd -s qpm-gluster01 --volfile-id gv01.qpm-gluster01.gluster_data-brick01-gv01 -p /var/run/gluster/vols
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: └─14383 /usr/sbin/glusterfs -s localhost --volfile-id gluster/glustershd -p /var/run/gluster/glustershd/glustershd.pid -l /var/l
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Sep 24 22:25:46 qpm-gluster01 systemd[1]: Starting GlusterFS, a clustered file-system server...
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Sep 24 22:25:46 qpm-gluster01 systemd[1]: Started GlusterFS, a clustered file-system server.
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:48 Periodic health check status: node c75334aaccdd5f882f02de248a4eb39d up=true
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:48 Cleaned 0 nodes from health cache
Sep 24 22:27:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:27:37 Starting Node Health Status refresh
Sep 24 22:27:37 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:27:37 Check Glusterd service status in node qpm-gluster02
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: [cmdexec] DEBUG 2019/09/24 22:27:38 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Result: ● glusterd.service - GlusterFS, a clustered file-system server
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Active: active (running) since Tue 2019-09-24 22:21:20 CST; 1min 47s ago
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Docs: man:glusterd(8)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Process: 14241 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, stat
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Main PID: 14244 (glusterd)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: CGroup: /system.slice/glusterd.service
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: ├─14244 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
...skipping...
Sep 25 18:02:12 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 404.314µs
Sep 25 18:02:13 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/e7d5af97be44fb69a21c6843a08a4f47
Sep 25 18:02:13 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 47.059µs
Sep 25 18:02:14 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/e7d5af97be44fb69a21c6843a08a4f47
Sep 25 18:02:14 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 48.526µs
Sep 25 18:02:15 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/e7d5af97be44fb69a21c6843a08a4f47
Sep 25 18:02:15 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 947.302µs
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:02:16 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: Result: volume start: vol_55484bcd5ff2f73c76a1b732899bb08e: success
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [heketi] INFO 2019/09/25 18:02:16 Create Volume succeeded
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [asynchttp] INFO 2019/09/25 18:02:16 asynchttp.go:292: Completed job e7d5af97be44fb69a21c6843a08a4f47 in 5.788973955s
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/e7d5af97be44fb69a21c6843a08a4f47
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [negroni] Completed 303 See Other in 63.842µs
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [negroni] Started GET /volumes/55484bcd5ff2f73c76a1b732899bb08e
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 1.387158ms
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [negroni] Started GET /clusters/4f289422a2a7f083aefa1c6239653d98
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 279.552µs
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [negroni] Started GET /nodes/4784bfe108b9bf66cc7f260dc950af2d
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 933.614µs
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [negroni] Started GET /nodes/c75334aaccdd5f882f02de248a4eb39d
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 760.05µs
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [negroni] Started DELETE /volumes/55484bcd5ff2f73c76a1b732899bb08e
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [negroni] Completed 202 Accepted in 1.56933ms
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [asynchttp] INFO 2019/09/25 18:02:16 asynchttp.go:288: Started job 71c87662ae6a087cb822cebb22fb7889
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [heketi] INFO 2019/09/25 18:02:16 Started async operation: Delete Volume
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/71c87662ae6a087cb822cebb22fb7889
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 37.443µs
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:02:16 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: Result: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: <cliOutput>
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: <opRet>0</opRet>
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: <opErrno>0</opErrno>
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: <opErrstr/>
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: <snapList>
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: <count>0</count>
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: </snapList>
Sep 25 18:02:16 qpm-gluster01 heketi[33084]: </cliOutput>
Sep 25 18:02:17 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/71c87662ae6a087cb822cebb22fb7889
Sep 25 18:02:17 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 984.585µs
[root@qpm-gluster01 ~]# journalctl -u heketi
-- Logs begin at Tue 2019-09-24 22:25:31 CST, end at Wed 2019-09-25 18:02:27 CST. --
Sep 24 22:25:37 qpm-gluster01 systemd[1]: Started Heketi Server.
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: Heketi 8.0.0
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 Loaded ssh executor
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 GlusterFS Application Loaded
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 Started Node Health Cache Monitor
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: Listening on port 8080
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:47 Starting Node Health Status refresh
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:25:47 Check Glusterd service status in node qpm-gluster02
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] WARNING 2019/09/24 22:25:47 Failed to create SSH connection to qpm-gluster02:22: dial tcp 10.20.105.61:22: getsockopt:
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] ERROR 2019/09/24 22:25:47 /src/github.com/heketi/heketi/executors/cmdexec/peer.go:76: dial tcp 10.20.105.61:22: getsoc
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:47 Periodic health check status: node 4784bfe108b9bf66cc7f260dc950af2d up=false
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:25:47 Check Glusterd service status in node qpm-gluster01
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [cmdexec] DEBUG 2019/09/24 22:25:48 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Result: ● glusterd.service - GlusterFS, a clustered file-system server
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Active: active (running) since Tue 2019-09-24 22:25:46 CST; 2s ago
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Docs: man:glusterd(8)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Process: 14278 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, stat
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Main PID: 14280 (glusterd)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: CGroup: /system.slice/glusterd.service
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: ├─14280 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: ├─14361 /usr/sbin/glusterfsd -s qpm-gluster01 --volfile-id gv01.qpm-gluster01.gluster_data-brick01-gv01 -p /var/run/gluster/vols
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: └─14383 /usr/sbin/glusterfs -s localhost --volfile-id gluster/glustershd -p /var/run/gluster/glustershd/glustershd.pid -l /var/l
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Sep 24 22:25:46 qpm-gluster01 systemd[1]: Starting GlusterFS, a clustered file-system server...
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Sep 24 22:25:46 qpm-gluster01 systemd[1]: Started GlusterFS, a clustered file-system server.
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:48 Periodic health check status: node c75334aaccdd5f882f02de248a4eb39d up=true
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:48 Cleaned 0 nodes from health cache
Sep 24 22:27:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:27:37 Starting Node Health Status refresh
Sep 24 22:27:37 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:27:37 Check Glusterd service status in node qpm-gluster02
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: [cmdexec] DEBUG 2019/09/24 22:27:38 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Result: ● glusterd.service - GlusterFS, a clustered file-system server
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Active: active (running) since Tue 2019-09-24 22:21:20 CST; 1min 47s ago
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Docs: man:glusterd(8)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Process: 14241 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, stat
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Main PID: 14244 (glusterd)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: CGroup: /system.slice/glusterd.service
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: ├─14244 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
...skipping...
Sep 25 18:02:22 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 42.104µs
Sep 25 18:02:23 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:02:23 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:02:23 qpm-gluster01 heketi[33084]: Result: volume stop: vol_55484bcd5ff2f73c76a1b732899bb08e: success
Sep 25 18:02:23 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/71c87662ae6a087cb822cebb22fb7889
Sep 25 18:02:23 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 338.922µs
Sep 25 18:02:24 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/71c87662ae6a087cb822cebb22fb7889
Sep 25 18:02:24 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 1.116144ms
Sep 25 18:02:25 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/71c87662ae6a087cb822cebb22fb7889
Sep 25 18:02:25 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 724.84µs
Sep 25 18:02:26 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/71c87662ae6a087cb822cebb22fb7889
Sep 25 18:02:26 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 1.210774ms
Sep 25 18:02:27 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/71c87662ae6a087cb822cebb22fb7889
Sep 25 18:02:27 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 37.461µs
Sep 25 18:02:28 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/71c87662ae6a087cb822cebb22fb7889
Sep 25 18:02:28 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 27.736µs
Sep 25 18:02:29 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:02:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:02:29 qpm-gluster01 heketi[33084]: Result: volume delete: vol_55484bcd5ff2f73c76a1b732899bb08e: success
Sep 25 18:02:29 qpm-gluster01 heketi[33084]: [heketi] INFO 2019/09/25 18:02:29 Deleting brick 6af28af0e6eabac6e672d9efbc2d3316
Sep 25 18:02:29 qpm-gluster01 heketi[33084]: [heketi] INFO 2019/09/25 18:02:29 Deleting brick e199d4c88ca6fa987604176a12fa9db3
Sep 25 18:02:29 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/71c87662ae6a087cb822cebb22fb7889
Sep 25 18:02:29 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 326.536µs
Sep 25 18:02:29 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:02:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:02:29 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:02:29 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:02:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:02:29 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:02:30 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:02:30 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:02:30 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:02:30 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:02:30 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:02:30 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:02:30 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:02:30 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:02:30 qpm-gluster01 heketi[33084]: Result:   Logical volume "brick_6af28af0e6eabac6e672d9efbc2d3316" successfully removed
Sep 25 18:02:30 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/71c87662ae6a087cb822cebb22fb7889
Sep 25 18:02:30 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 562.671µs
Sep 25 18:02:30 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:02:30 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:02:30 qpm-gluster01 heketi[33084]: Result:   Logical volume "brick_e199d4c88ca6fa987604176a12fa9db3" successfully removed
Sep 25 18:02:30 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:02:30 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:02:30 qpm-gluster01 heketi[33084]: Result:        0
Sep 25 18:02:30 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:02:30 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:02:30 qpm-gluster01 heketi[33084]: Result:        0
[root@qpm-gluster01 ~]# journalctl -u heketi
-- Logs begin at Tue 2019-09-24 22:25:31 CST, end at Wed 2019-09-25 18:03:09 CST. --
Sep 24 22:25:37 qpm-gluster01 systemd[1]: Started Heketi Server.
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: Heketi 8.0.0
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 Loaded ssh executor
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 GlusterFS Application Loaded
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 Started Node Health Cache Monitor
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: Listening on port 8080
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:47 Starting Node Health Status refresh
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:25:47 Check Glusterd service status in node qpm-gluster02
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] WARNING 2019/09/24 22:25:47 Failed to create SSH connection to qpm-gluster02:22: dial tcp 10.20.105.61:22: getsockopt:
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] ERROR 2019/09/24 22:25:47 /src/github.com/heketi/heketi/executors/cmdexec/peer.go:76: dial tcp 10.20.105.61:22: getsoc
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:47 Periodic health check status: node 4784bfe108b9bf66cc7f260dc950af2d up=false
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:25:47 Check Glusterd service status in node qpm-gluster01
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [cmdexec] DEBUG 2019/09/24 22:25:48 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Result: ● glusterd.service - GlusterFS, a clustered file-system server
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Active: active (running) since Tue 2019-09-24 22:25:46 CST; 2s ago
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Docs: man:glusterd(8)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Process: 14278 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, stat
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Main PID: 14280 (glusterd)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: CGroup: /system.slice/glusterd.service
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: ├─14280 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: ├─14361 /usr/sbin/glusterfsd -s qpm-gluster01 --volfile-id gv01.qpm-gluster01.gluster_data-brick01-gv01 -p /var/run/gluster/vols
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: └─14383 /usr/sbin/glusterfs -s localhost --volfile-id gluster/glustershd -p /var/run/gluster/glustershd/glustershd.pid -l /var/l
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Sep 24 22:25:46 qpm-gluster01 systemd[1]: Starting GlusterFS, a clustered file-system server...
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Sep 24 22:25:46 qpm-gluster01 systemd[1]: Started GlusterFS, a clustered file-system server.
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:48 Periodic health check status: node c75334aaccdd5f882f02de248a4eb39d up=true
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:48 Cleaned 0 nodes from health cache
Sep 24 22:27:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:27:37 Starting Node Health Status refresh
Sep 24 22:27:37 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:27:37 Check Glusterd service status in node qpm-gluster02
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: [cmdexec] DEBUG 2019/09/24 22:27:38 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Result: ● glusterd.service - GlusterFS, a clustered file-system server
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Active: active (running) since Tue 2019-09-24 22:21:20 CST; 1min 47s ago
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Docs: man:glusterd(8)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Process: 14241 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, stat
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Main PID: 14244 (glusterd)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: CGroup: /system.slice/glusterd.service
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: ├─14244 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
...skipping...
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:09 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: Result: meta-data=/dev/mapper/vg_0698a82595cf974afcef3cccfa143966-brick_e8e2ba7d0e74e6224f94f7a7f58fa978 isize=512    agcount=8,
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: =                       sectsz=4096  attr=2, projid32bit=1
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: =                       crc=1        finobt=0, sparse=0
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: data     =                       bsize=4096   blocks=262144, imaxpct=25
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: =                       sunit=64     swidth=64 blks
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: naming   =version 2              bsize=8192   ascii-ci=0 ftype=1
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: log      =internal log           bsize=4096   blocks=2560, version=2
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: =                       sectsz=4096  sunit=1 blks, lazy-count=1
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: realtime =none                   extsz=4096   blocks=0, rtextents=0
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:09 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/949c6d10b4dabd35226b540acea1df52
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 53.775µs
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:09 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:09 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:09 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:09 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:09 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:09 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:09 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:09 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: [cmdexec] INFO 2019/09/25 18:03:09 Creating volume vol_6d948239054f70f44dbf39c0310671f4 replica 2
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:09 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:03:09 qpm-gluster01 heketi[33084]: Result: volume create: vol_6d948239054f70f44dbf39c0310671f4: success: please start the volume to access data
Sep 25 18:03:10 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/949c6d10b4dabd35226b540acea1df52
Sep 25 18:03:10 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 51.199µs
Sep 25 18:03:11 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/949c6d10b4dabd35226b540acea1df52
Sep 25 18:03:11 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 46.972µs
Sep 25 18:03:12 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/949c6d10b4dabd35226b540acea1df52
Sep 25 18:03:12 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 47.692µs
[root@qpm-gluster01 ~]# journalctl -u heketi
-- Logs begin at Tue 2019-09-24 22:25:31 CST, end at Wed 2019-09-25 18:03:30 CST. --
Sep 24 22:25:37 qpm-gluster01 systemd[1]: Started Heketi Server.
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: Heketi 8.0.0
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 Loaded ssh executor
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 GlusterFS Application Loaded
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 Started Node Health Cache Monitor
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: Listening on port 8080
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:47 Starting Node Health Status refresh
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:25:47 Check Glusterd service status in node qpm-gluster02
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] WARNING 2019/09/24 22:25:47 Failed to create SSH connection to qpm-gluster02:22: dial tcp 10.20.105.61:22: getsockopt:
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] ERROR 2019/09/24 22:25:47 /src/github.com/heketi/heketi/executors/cmdexec/peer.go:76: dial tcp 10.20.105.61:22: getsoc
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:47 Periodic health check status: node 4784bfe108b9bf66cc7f260dc950af2d up=false
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:25:47 Check Glusterd service status in node qpm-gluster01
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [cmdexec] DEBUG 2019/09/24 22:25:48 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Result: ● glusterd.service - GlusterFS, a clustered file-system server
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Active: active (running) since Tue 2019-09-24 22:25:46 CST; 2s ago
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Docs: man:glusterd(8)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Process: 14278 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, stat
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Main PID: 14280 (glusterd)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: CGroup: /system.slice/glusterd.service
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: ├─14280 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: ├─14361 /usr/sbin/glusterfsd -s qpm-gluster01 --volfile-id gv01.qpm-gluster01.gluster_data-brick01-gv01 -p /var/run/gluster/vols
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: └─14383 /usr/sbin/glusterfs -s localhost --volfile-id gluster/glustershd -p /var/run/gluster/glustershd/glustershd.pid -l /var/l
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Sep 24 22:25:46 qpm-gluster01 systemd[1]: Starting GlusterFS, a clustered file-system server...
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Sep 24 22:25:46 qpm-gluster01 systemd[1]: Started GlusterFS, a clustered file-system server.
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:48 Periodic health check status: node c75334aaccdd5f882f02de248a4eb39d up=true
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:48 Cleaned 0 nodes from health cache
Sep 24 22:27:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:27:37 Starting Node Health Status refresh
Sep 24 22:27:37 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:27:37 Check Glusterd service status in node qpm-gluster02
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: [cmdexec] DEBUG 2019/09/24 22:27:38 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Result: ● glusterd.service - GlusterFS, a clustered file-system server
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Active: active (running) since Tue 2019-09-24 22:21:20 CST; 1min 47s ago
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Docs: man:glusterd(8)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Process: 14241 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, stat
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Main PID: 14244 (glusterd)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: CGroup: /system.slice/glusterd.service
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: ├─14244 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
...skipping...
Sep 25 18:03:26 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 37.874µs
Sep 25 18:03:27 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:27 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:03:27 qpm-gluster01 heketi[33084]: Result: volume delete: vol_6d948239054f70f44dbf39c0310671f4: success
Sep 25 18:03:27 qpm-gluster01 heketi[33084]: [heketi] INFO 2019/09/25 18:03:27 Deleting brick e8e2ba7d0e74e6224f94f7a7f58fa978
Sep 25 18:03:27 qpm-gluster01 heketi[33084]: [heketi] INFO 2019/09/25 18:03:27 Deleting brick 4a1f48053a83f22e54494cb7dc2a9dd2
Sep 25 18:03:27 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/2ddcb67633e6765df215d766a3d6b06b
Sep 25 18:03:27 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 332.418µs
Sep 25 18:03:27 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:27 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:03:27 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:03:27 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:27 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:03:27 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:03:28 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:28 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:03:28 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:03:28 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:28 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:03:28 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:03:28 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/2ddcb67633e6765df215d766a3d6b06b
Sep 25 18:03:28 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 1.237352ms
Sep 25 18:03:28 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:28 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:03:28 qpm-gluster01 heketi[33084]: Result:   Logical volume "brick_e8e2ba7d0e74e6224f94f7a7f58fa978" successfully removed
Sep 25 18:03:28 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:28 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:03:28 qpm-gluster01 heketi[33084]: Result:   Logical volume "brick_4a1f48053a83f22e54494cb7dc2a9dd2" successfully removed
Sep 25 18:03:28 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:28 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:03:28 qpm-gluster01 heketi[33084]: Result:        0
Sep 25 18:03:28 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:28 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:03:28 qpm-gluster01 heketi[33084]: Result:        0
Sep 25 18:03:29 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:03:29 qpm-gluster01 heketi[33084]: Result:   Logical volume "tp_e6c2bab18eea73d91dc8b82a41f8cf20" successfully removed
Sep 25 18:03:29 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/2ddcb67633e6765df215d766a3d6b06b
Sep 25 18:03:29 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 51.186µs
Sep 25 18:03:29 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:03:29 qpm-gluster01 heketi[33084]: Result:   Logical volume "tp_4a1f48053a83f22e54494cb7dc2a9dd2" successfully removed
Sep 25 18:03:29 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:03:29 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:03:29 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:03:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:03:29 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:03:29 qpm-gluster01 heketi[33084]: [heketi] INFO 2019/09/25 18:03:29 Delete Volume succeeded
Sep 25 18:03:29 qpm-gluster01 heketi[33084]: [asynchttp] INFO 2019/09/25 18:03:29 asynchttp.go:292: Completed job 2ddcb67633e6765df215d766a3d6b06b in 15.398688681s
Sep 25 18:03:30 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/2ddcb67633e6765df215d766a3d6b06b
Sep 25 18:03:30 qpm-gluster01 heketi[33084]: [negroni] Completed 204 No Content in 44.008µs
[root@qpm-gluster01 ~]# journalctl -u heketi
-- Logs begin at Tue 2019-09-24 22:25:31 CST, end at Wed 2019-09-25 18:04:30 CST. --
Sep 24 22:25:37 qpm-gluster01 systemd[1]: Started Heketi Server.
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: Heketi 8.0.0
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 Loaded ssh executor
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 GlusterFS Application Loaded
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 Started Node Health Cache Monitor
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: Listening on port 8080
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:47 Starting Node Health Status refresh
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:25:47 Check Glusterd service status in node qpm-gluster02
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] WARNING 2019/09/24 22:25:47 Failed to create SSH connection to qpm-gluster02:22: dial tcp 10.20.105.61:22: getsockopt:
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] ERROR 2019/09/24 22:25:47 /src/github.com/heketi/heketi/executors/cmdexec/peer.go:76: dial tcp 10.20.105.61:22: getsoc
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:47 Periodic health check status: node 4784bfe108b9bf66cc7f260dc950af2d up=false
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:25:47 Check Glusterd service status in node qpm-gluster01
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [cmdexec] DEBUG 2019/09/24 22:25:48 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Result: ● glusterd.service - GlusterFS, a clustered file-system server
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Active: active (running) since Tue 2019-09-24 22:25:46 CST; 2s ago
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Docs: man:glusterd(8)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Process: 14278 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, stat
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Main PID: 14280 (glusterd)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: CGroup: /system.slice/glusterd.service
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: ├─14280 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: ├─14361 /usr/sbin/glusterfsd -s qpm-gluster01 --volfile-id gv01.qpm-gluster01.gluster_data-brick01-gv01 -p /var/run/gluster/vols
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: └─14383 /usr/sbin/glusterfs -s localhost --volfile-id gluster/glustershd -p /var/run/gluster/glustershd/glustershd.pid -l /var/l
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Sep 24 22:25:46 qpm-gluster01 systemd[1]: Starting GlusterFS, a clustered file-system server...
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Sep 24 22:25:46 qpm-gluster01 systemd[1]: Started GlusterFS, a clustered file-system server.
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:48 Periodic health check status: node c75334aaccdd5f882f02de248a4eb39d up=true
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:48 Cleaned 0 nodes from health cache
Sep 24 22:27:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:27:37 Starting Node Health Status refresh
Sep 24 22:27:37 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:27:37 Check Glusterd service status in node qpm-gluster02
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: [cmdexec] DEBUG 2019/09/24 22:27:38 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Result: ● glusterd.service - GlusterFS, a clustered file-system server
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Active: active (running) since Tue 2019-09-24 22:21:20 CST; 1min 47s ago
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Docs: man:glusterd(8)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Process: 14241 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, stat
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Main PID: 14244 (glusterd)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: CGroup: /system.slice/glusterd.service
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: ├─14244 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
...skipping...
Sep 25 18:04:26 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 37.624µs
Sep 25 18:04:27 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:04:26 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:04:27 qpm-gluster01 heketi[33084]: Result: volume delete: vol_b5e4543ce096afe05a4a840eff1f75dc: success
Sep 25 18:04:27 qpm-gluster01 heketi[33084]: [heketi] INFO 2019/09/25 18:04:26 Deleting brick 1b55942eec775bed13dd998d8603970d
Sep 25 18:04:27 qpm-gluster01 heketi[33084]: [heketi] INFO 2019/09/25 18:04:26 Deleting brick 0fb883071f2725dea564de4b2a997eca
Sep 25 18:04:27 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:04:27 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:04:27 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:04:27 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/1cf27e815c58cf0d35942ec349629fde
Sep 25 18:04:27 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 40.113µs
Sep 25 18:04:27 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:04:27 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:04:27 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:04:27 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:04:27 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:04:27 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:04:27 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:04:27 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:04:27 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:04:28 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:04:28 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:04:28 qpm-gluster01 heketi[33084]: Result:   Logical volume "brick_0fb883071f2725dea564de4b2a997eca" successfully removed
Sep 25 18:04:28 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:04:28 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:04:28 qpm-gluster01 heketi[33084]: Result:   Logical volume "brick_1b55942eec775bed13dd998d8603970d" successfully removed
Sep 25 18:04:28 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/1cf27e815c58cf0d35942ec349629fde
Sep 25 18:04:28 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 359.086µs
Sep 25 18:04:28 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:04:28 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:04:28 qpm-gluster01 heketi[33084]: Result:        0
Sep 25 18:04:28 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:04:28 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:04:28 qpm-gluster01 heketi[33084]: Result:        0
Sep 25 18:04:29 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:04:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:04:29 qpm-gluster01 heketi[33084]: Result:   Logical volume "tp_1b55942eec775bed13dd998d8603970d" successfully removed
Sep 25 18:04:29 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:04:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:04:29 qpm-gluster01 heketi[33084]: Result:   Logical volume "tp_c014cca72deab875e543b2c702e60de1" successfully removed
Sep 25 18:04:29 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/1cf27e815c58cf0d35942ec349629fde
Sep 25 18:04:29 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 850.294µs
Sep 25 18:04:29 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:04:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:04:29 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:04:29 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:04:29 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 25 18:04:29 qpm-gluster01 heketi[33084]: Result:
Sep 25 18:04:29 qpm-gluster01 heketi[33084]: [heketi] INFO 2019/09/25 18:04:29 Delete Volume succeeded
Sep 25 18:04:29 qpm-gluster01 heketi[33084]: [asynchttp] INFO 2019/09/25 18:04:29 asynchttp.go:292: Completed job 1cf27e815c58cf0d35942ec349629fde in 15.143158493s
Sep 25 18:04:30 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/1cf27e815c58cf0d35942ec349629fde
Sep 25 18:04:30 qpm-gluster01 heketi[33084]: [negroni] Completed 204 No Content in 37.995µs
[root@qpm-gluster01 ~]# journalctl -u heketi
-- Logs begin at Tue 2019-09-24 22:25:31 CST, end at Wed 2019-09-25 18:04:57 CST. --
Sep 24 22:25:37 qpm-gluster01 systemd[1]: Started Heketi Server.
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: Heketi 8.0.0
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 Loaded ssh executor
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 GlusterFS Application Loaded
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:37 Started Node Health Cache Monitor
Sep 24 22:25:37 qpm-gluster01 heketi[13903]: Listening on port 8080
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:47 Starting Node Health Status refresh
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:25:47 Check Glusterd service status in node qpm-gluster02
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] WARNING 2019/09/24 22:25:47 Failed to create SSH connection to qpm-gluster02:22: dial tcp 10.20.105.61:22: getsockopt:
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] ERROR 2019/09/24 22:25:47 /src/github.com/heketi/heketi/executors/cmdexec/peer.go:76: dial tcp 10.20.105.61:22: getsoc
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:47 Periodic health check status: node 4784bfe108b9bf66cc7f260dc950af2d up=false
Sep 24 22:25:47 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:25:47 Check Glusterd service status in node qpm-gluster01
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [cmdexec] DEBUG 2019/09/24 22:25:48 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Result: ● glusterd.service - GlusterFS, a clustered file-system server
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Active: active (running) since Tue 2019-09-24 22:25:46 CST; 2s ago
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Docs: man:glusterd(8)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Process: 14278 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, stat
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Main PID: 14280 (glusterd)
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: CGroup: /system.slice/glusterd.service
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: ├─14280 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: ├─14361 /usr/sbin/glusterfsd -s qpm-gluster01 --volfile-id gv01.qpm-gluster01.gluster_data-brick01-gv01 -p /var/run/gluster/vols
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: └─14383 /usr/sbin/glusterfs -s localhost --volfile-id gluster/glustershd -p /var/run/gluster/glustershd/glustershd.pid -l /var/l
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Sep 24 22:25:46 qpm-gluster01 systemd[1]: Starting GlusterFS, a clustered file-system server...
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: Sep 24 22:25:46 qpm-gluster01 systemd[1]: Started GlusterFS, a clustered file-system server.
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:48 Periodic health check status: node c75334aaccdd5f882f02de248a4eb39d up=true
Sep 24 22:25:48 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:25:48 Cleaned 0 nodes from health cache
Sep 24 22:27:37 qpm-gluster01 heketi[13903]: [heketi] INFO 2019/09/24 22:27:37 Starting Node Health Status refresh
Sep 24 22:27:37 qpm-gluster01 heketi[13903]: [cmdexec] INFO 2019/09/24 22:27:37 Check Glusterd service status in node qpm-gluster02
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: [cmdexec] DEBUG 2019/09/24 22:27:38 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster02:22 Command: /bin
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Result: ● glusterd.service - GlusterFS, a clustered file-system server
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Active: active (running) since Tue 2019-09-24 22:21:20 CST; 1min 47s ago
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Docs: man:glusterd(8)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Process: 14241 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, stat
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: Main PID: 14244 (glusterd)
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: CGroup: /system.slice/glusterd.service
Sep 24 22:27:38 qpm-gluster01 heketi[13903]: ├─14244 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
...skipping...
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: [negroni] Started GET /nodes/c75334aaccdd5f882f02de248a4eb39d
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 764.283µs
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: [negroni] Started DELETE /volumes/1146042f3ba2f7586c9630a6cd286b2e
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: [negroni] Completed 202 Accepted in 1.494867ms
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: [asynchttp] INFO 2019/09/25 18:04:59 asynchttp.go:288: Started job cab2f0a2e39ea0be3d5a44f5110df1d1
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: [heketi] INFO 2019/09/25 18:04:59 Started async operation: Delete Volume
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/cab2f0a2e39ea0be3d5a44f5110df1d1
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 35.251µs
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:04:59 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: Result: ● glusterd.service - GlusterFS, a clustered file-system server
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: Loaded: loaded (/usr/lib/systemd/system/glusterd.service; enabled; vendor preset: disabled)
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: Active: active (running) since Tue 2019-09-24 22:25:46 CST; 19h ago
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: Docs: man:glusterd(8)
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: Process: 14278 ExecStart=/usr/sbin/glusterd -p /var/run/glusterd.pid --log-level $LOG_LEVEL $GLUSTERD_OPTIONS (code=exited, stat
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: Main PID: 14280 (glusterd)
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: CGroup: /system.slice/glusterd.service
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: ├─14280 /usr/sbin/glusterd -p /var/run/glusterd.pid --log-level INFO
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: ├─14361 /usr/sbin/glusterfsd -s qpm-gluster01 --volfile-id gv01.qpm-gluster01.gluster_data-brick01-gv01 -p /var/run/gluster/vols
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: ├─35765 /bin/bash /var/lib/glusterd/hooks/1/create/post/S10selinux-label-brick.sh --volname=vol_1146042f3ba2f7586c9630a6cd286b2e
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: ├─35792 /usr/sbin/glusterfsd -s qpm-gluster01 --volfile-id vol_1146042f3ba2f7586c9630a6cd286b2e.qpm-gluster01.var-lib-heketi-mou
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: ├─35818 /usr/sbin/glusterfs -s localhost --volfile-id gluster/glustershd -p /var/run/gluster/glustershd/glustershd.pid -l /var/l
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: ├─35831 /usr/bin/python -Es /usr/sbin/semanage fcontext --add -t glusterd_brick_t -r s0 /var/lib/heketi/mounts/vg_dd6fade2c4f5e1
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: └─35838 /sbin/load_policy
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: Sep 24 22:25:46 qpm-gluster01 systemd[1]: Starting GlusterFS, a clustered file-system server...
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: Sep 24 22:25:46 qpm-gluster01 systemd[1]: Started GlusterFS, a clustered file-system server.
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: [heketi] INFO 2019/09/25 18:04:59 Periodic health check status: node c75334aaccdd5f882f02de248a4eb39d up=true
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: [heketi] INFO 2019/09/25 18:04:59 Cleaned 0 nodes from health cache
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: [cmdexec] DEBUG 2019/09/25 18:04:59 /src/github.com/heketi/heketi/pkg/utils/ssh/ssh.go:173: Host: qpm-gluster01:22 Command: /bin
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: Result: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: <cliOutput>
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: <opRet>0</opRet>
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: <opErrno>0</opErrno>
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: <opErrstr/>
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: <snapList>
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: <count>0</count>
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: </snapList>
Sep 25 18:04:59 qpm-gluster01 heketi[33084]: </cliOutput>
Sep 25 18:05:00 qpm-gluster01 heketi[33084]: [negroni] Started GET /queue/cab2f0a2e39ea0be3d5a44f5110df1d1
Sep 25 18:05:00 qpm-gluster01 heketi[33084]: [negroni] Completed 200 OK in 1.139606ms

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
CentOS Linux release 7.6.1810 (Core)
- Kernel (e.g. `uname -a`):
Linux qpm-k8s-master01 4.4.186-1.el7.elrepo.x86_64 #1 SMP Sun Jul 21 04:06:52 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
heketi.x86_64                        8.0.0-1.el7                @centos-gluster6
heketi-client.x86_64                 8.0.0-1.el7                @centos-gluster6

### PR DESCRIPTION
**Pull request by zouyee**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:

IP validates if a string is a valid IP address (either version 4 or 6)

**Which issue(s) this PR fixes**:

Fixes #83095

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
IP validates if a string is a valid IP address
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/volume/glusterfs/glusterfs.go [hunk 1]
```diff
@@ -974,6 +975,13 @@ func getClusterNodes(cli *gcli.Client, cluster string) (dynamicHostIps []string,
 	if len(dynamicHostIps) == 0 {
 		return nil, fmt.Errorf("no hosts found: %v", err)
 	}
+	// This should allow hostname or IP, See #4447.
+	for _, ipAddress := range dynamicHostIps {
```
Comment (aojea) [inline pkg/volume/glusterfs/glusterfs.go]: these IPs are obtained from 
```
ipaddr := dstrings.Join(nodeInfo.NodeAddRequest.Hostnames.Storage, "")
```

are those ips validated before they are added to the `Nodes`struct? do we need to validate them again if affirmative?

Comment (zouyee) [reply pkg/volume/glusterfs/glusterfs.go]: commit updated, PTAL

**Comment by zouyee** [comment]
@jsafrane PTAL

File: pkg/volume/glusterfs/glusterfs.go [hunk 2]
```diff
@@ -967,7 +968,13 @@ func getClusterNodes(cli *gcli.Client, cluster string) (dynamicHostIps []string,
 		if err != nil {
 			return nil, fmt.Errorf("failed to get host ipaddress: %v", err)
 		}
+
 		ipaddr := dstrings.Join(nodeInfo.NodeAddRequest.Hostnames.Storage, "")
+		// This should allow hostname or IP, See #4447.
+		ip := net.ParseIP(ipaddr)
```
Comment (jsafrane) [inline pkg/volume/glusterfs/glusterfs.go]: the comment just above says it can be hostname or IP, yet this line expects only IP. So what is correct here?

**Review by jsafrane — COMMENTED** [review]
To make sure I understand the issue, instead of "failed to create volume: failed to update endpoint <endpoint content>", now Kubernetes will show "Glusterfs ipAddress %s must be a valid IP address"?

File: pkg/volume/glusterfs/glusterfs.go (hunk 2 above)
Comment (humblec) [reply pkg/volume/glusterfs/glusterfs.go]: Yeah, that comment is wrong. Because we can not fill hostname to endpoint address field. It should be a valid IP address.

**Comment by humblec** [comment]
@zouyee `IP validates if a string is a valid IP address (either version 4 or 6)`. IP v6 is supported ONLY with latest gluster upstream version which is v6.0. Not available with `5.0` versions. so, this mention is wrong too.

**Comment by zouyee** [comment]
@humblec PTAL

File: pkg/volume/glusterfs/glusterfs.go [hunk 3]
```diff
@@ -967,7 +968,13 @@ func getClusterNodes(cli *gcli.Client, cluster string) (dynamicHostIps []string,
 		if err != nil {
 			return nil, fmt.Errorf("failed to get host ipaddress: %v", err)
 		}
+
```
Comment (humblec) [inline pkg/volume/glusterfs/glusterfs.go]: please remove this newline

**Review by humblec — APPROVED** [review]

File: pkg/volume/glusterfs/glusterfs.go [hunk 4]
```diff
@@ -968,6 +969,11 @@ func getClusterNodes(cli *gcli.Client, cluster string) (dynamicHostIps []string,
 			return nil, fmt.Errorf("failed to get host ipaddress: %v", err)
 		}
 		ipaddr := dstrings.Join(nodeInfo.NodeAddRequest.Hostnames.Storage, "")
+		// IP validates if a string is a valid IP address.
+		ip := net.ParseIP(ipaddr)
+		if ip == nil {
+			return nil, fmt.Errorf("Glusterfs ipAddress %s must be a valid IP address, (e.g. 10.9.8.7)", ipaddr)
```
Comment (humblec) [inline pkg/volume/glusterfs/glusterfs.go]: May be we can reword the error as "glusterfs server node ip address %s must be a valid IP address, (e.g. 10.9.8.7)"

**Comment by humblec** [comment]
@zouyee one more quick comment.

File: pkg/volume/glusterfs/glusterfs.go (hunk 4 above)
Comment (zouyee) [reply pkg/volume/glusterfs/glusterfs.go]: thanks, done!

**Comment by humblec** [comment]
@jsafrane any further comments from your side ?
