### PR TITLE
List pod list once to avoid timeout in Multi-AZ Clusters

### LINKED ISSUE #100705: Regression: Multi-AZ Clusters test timing out in big clusters
From https://github.com/kubernetes/kubernetes/pull/98699#issuecomment-810916947

After #98699, Multi-AZ Clusters tests in 1.19 and 1.20 started timing out as createBalancedPodForNodes is extremely inefficient in scale: for each node (out of 5k), it lists all pods in a cluster serially (each list takes ~5s), which translates to ~7 hours.

Optimizing this function by listing pods once and then in memory by Spec.NodeName

/kind bug
/priority critical-urgent
/sig scheduling

### PR DESCRIPTION
**Pull request by AliceZhang2016**
#### What type of PR is this?
/kind bug
/sig scheduling

#### What this PR does / why we need it:
In current `computeCPUMemFraction` function, it list all pods in cluster for each node to check if this pod is scheduled on the node. When there are lots of nodes and pods, it lead to timeout.
Therefore, we only list pods once, and stores the information that which pods are on the associated node.

#### Which issue(s) this PR fixes:

Fixes #100705 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/scheduling/priorities.go [hunk 1]
```diff
@@ -569,33 +573,44 @@ func createBalancedPodForNodes(f *framework.Framework, cs clientset.Interface, n
...
-			totalRequestedCPUResource += getNonZeroRequests(&pod).MilliCPU
-			totalRequestedMemResource += getNonZeroRequests(&pod).Memory
+	for _, pod := range allPods.Items {
+		nodeName := pod.Spec.NodeName
+		nodeNameToPodList[nodeName] = append(nodeNameToPodList[nodeName], &pod)
+	}
+	return nodeNameToPodList
+}
+
+func computeCPUMemFraction(cs clientset.Interface, node v1.Node, resource *v1.ResourceRequirements, nodeNameToPodList map[string][]*v1.Pod) (float64, float64, int64, int64) {
```
Comment (alculquicondor) [inline test/e2e/scheduling/priorities.go:598]: It looks like the `cs` parameter is not needed anymore.

Also, since this function refers to one node, you can just pass the list of pods instead of the whole map.

**Review by alculquicondor — COMMENTED** [review]
/approve

**Comment by alculquicondor** [comment]
cc @mborsz

File: test/e2e/scheduling/priorities.go [hunk 2]
```diff
@@ -569,33 +573,43 @@ func createBalancedPodForNodes(f *framework.Framework, cs clientset.Interface, n
...
 
 	return cleanUp, nil
 }
 
-func computeCPUMemFraction(cs clientset.Interface, node v1.Node, resource *v1.ResourceRequirements) (float64, float64, int64, int64) {
-	framework.Logf("ComputeCPUMemFraction for node: %v", node.Name)
-	totalRequestedCPUResource := resource.Requests.Cpu().MilliValue()
-	totalRequestedMemResource := resource.Requests.Memory().Value()
-	allpods, err := cs.CoreV1().Pods(metav1.NamespaceAll).List(context.TODO(), metav1.ListOptions{})
+func podListForEachNode(cs clientset.Interface, nodes []v1.Node) map[string][]*v1.Pod {
```
Comment (Huang-Wei) [inline test/e2e/scheduling/priorities.go:585]: We don't need to pass in `nodes`, right?

File: test/e2e/scheduling/priorities.go [hunk 3]
```diff
@@ -569,33 +573,43 @@ func createBalancedPodForNodes(f *framework.Framework, cs clientset.Interface, n
...
+	var nodeNameToPodList = make(map[string][]*v1.Pod)
```
Comment (Huang-Wei) [inline test/e2e/scheduling/priorities.go:586]: nit: IMO it's conventional to use `:=`:

```go
nodeNameToPodList := make(map[string][]*v1.Pod)
```

File: test/e2e/scheduling/priorities.go [hunk 4]
```diff
@@ -569,33 +573,43 @@ func createBalancedPodForNodes(f *framework.Framework, cs clientset.Interface, n
...
-			totalRequestedCPUResource += getNonZeroRequests(&pod).MilliCPU
-			totalRequestedMemResource += getNonZeroRequests(&pod).Memory
+	for _, pod := range allPods.Items {
+		nodeName := pod.Spec.NodeName
+		nodeNameToPodList[nodeName] = append(nodeNameToPodList[nodeName], &pod)
+	}
+	return nodeNameToPodList
+}
+
+func computeCPUMemFraction(node v1.Node, resource *v1.ResourceRequirements, podList []*v1.Pod) (float64, float64, int64, int64) {
```
Comment (Huang-Wei) [inline test/e2e/scheduling/priorities.go:598]:
```suggestion
func computeCPUMemFraction(node v1.Node, resource *v1.ResourceRequirements, pods []*v1.Pod) (float64, float64, int64, int64) {
```

As `XYZList` usually refer to a particular API type which is not simply a slice of XYZ.

**Comment by adtac** [comment]
LGTM apart from @Huang-Wei's review comments. Do we know if this was the root cause?

**Comment by alculquicondor** [comment]
@ahg-g can we set the milestone for this one?

**Comment by ahg-g** [comment]
I think the branch is closed, this needs to be cherry picked of we want it in 1.21.

File: test/e2e/scheduling/priorities.go [hunk 5]
```diff
@@ -569,33 +573,43 @@ func createBalancedPodForNodes(f *framework.Framework, cs clientset.Interface, n
...
-		if pod.Spec.NodeName == node.Name {
-			framework.Logf("Pod for on the node: %v, Cpu: %v, Mem: %v", pod.Name, getNonZeroRequests(&pod).MilliCPU, getNonZeroRequests(&pod).Memory)
-			// Ignore best effort pods while computing fractions as they won't be taken in account by scheduler.
-			if v1qos.GetPodQOS(&pod) == v1.PodQOSBestEffort {
-				continue
-			}
-			totalRequestedCPUResource += getNonZeroRequests(&pod).MilliCPU
-			totalRequestedMemResource += getNonZeroRequests(&pod).Memory
+	for _, pod := range allPods.Items {
+		nodeName := pod.Spec.NodeName
```
Comment (mborsz) [inline test/e2e/scheduling/priorities.go:592]: What if a given pod isn't scheduled yet?

Shouldn't we handle the case when pod.Spec.NodeName is empty, explicitly?

Comment (alculquicondor) [reply test/e2e/scheduling/priorities.go:592]: We are already effectively ignoring them when iterating the nodes.

**Comment by alculquicondor** [comment]
@AliceZhang2016 

Can you cherrypick to 1.21, 1.20 and 1.19? https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#initiate-a-cherry-pick

**Comment by AliceZhang2016** [comment]
@alculquicondor 
Here are three cherrypick PRs:
https://github.com/kubernetes/kubernetes/pull/101031
https://github.com/kubernetes/kubernetes/pull/101038
https://github.com/kubernetes/kubernetes/pull/101040
