### PR TITLE
print out verbose info for a scheduler e2e test

### LINKED ISSUE #74626: [Failing Test] [sig-scheduling] PreemptionExecutionPath runs ReplicaSets to verify preemption running path tests failing
**Which jobs are failing**:
- [sig-release-1.14-all/gke-cos-1.14-default](https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-default)

**Which test(s) are failing**:
- [[sig-scheduling] PreemptionExecutionPath runs ReplicaSets to verify preemption running path 29s](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-cos-k8sbeta-default/9490#sig-scheduling-preemptionexecutionpath-runs-replicasets-to-verify-preemption-running-path)

**Since when has it been failing**:
- since 2019-02-25 @ 4:15
- [Compared Commit Changes](https://github.com/kubernetes/kubernetes/compare/506e8dc9e...39dac9a88)

**Testgrid link**:
- [sig-release-1.14-all/gke-cos-1.14-default](https://testgrid.k8s.io/sig-release-1.14-all#gke-cos-1.14-default)

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:401
Expected
    <bool>: false
to equal
    <bool>: true
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/preemption.go:431
```

**Anything else we need to know**:

/kind failing-test
/priority important-soon
/sig scheduling
/milestone 1.14

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Reveal more clues to chase down root cause of #74626.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig scheduling
/assign @bsalamat

### CODE REVIEW

File: test/e2e/scheduling/preemption.go [hunk 1]
```diff
@@ -422,12 +422,27 @@ var _ = SIGDescribe("PreemptionExecutionPath", func() {
 		node, err = cs.CoreV1().Nodes().UpdateStatus(nodeCopy)
 		framework.ExpectNoError(err)
 
+		// print out existing priorities
```
Comment (bsalamat) [inline test/e2e/scheduling/preemption.go]: Could you please add a TODO to remove this after debugging is done?

**Review by bsalamat — COMMENTED** [review]
Thanks, Wei!

File: test/e2e/scheduling/preemption.go (hunk 1 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: Absolutely. Done.

Comment (misterikkit) [reply test/e2e/scheduling/preemption.go]: Actually I would prefer not to merge temporary code like this. Instead, how about we wrap it in a block like
```
 if CurrentGinkgoTestDescription().Failed { }
```
and move it to a `JustAfterEach` thingy?

ref http://onsi.github.io/ginkgo/#separating-creation-and-configuration-justbeforeeach

File: test/e2e/scheduling/preemption.go [hunk 2]
```diff
@@ -422,12 +422,28 @@ var _ = SIGDescribe("PreemptionExecutionPath", func() {
 		node, err = cs.CoreV1().Nodes().UpdateStatus(nodeCopy)
 		framework.ExpectNoError(err)
 
+		// TODO(Huang-Wei): remove this after #74626 is resolved
+		// print out existing priorities
+		priorityList, err := cs.SchedulingV1().PriorityClasses().List(metav1.ListOptions{})
+		if err != nil {
+			framework.Logf("Listing all priorities: %v", err)
```
Comment (misterikkit) [inline test/e2e/scheduling/preemption.go]: Should this log message be reworded to "Unable to list priorities"?

File: test/e2e/scheduling/preemption.go [hunk 3]
```diff
@@ -422,12 +422,28 @@ var _ = SIGDescribe("PreemptionExecutionPath", func() {
...
+		} else {
+			framework.Logf("Print out existing priorities")
```
Comment (misterikkit) [inline test/e2e/scheduling/preemption.go]: I think we should drop "Print out" from this log message.

**Comment by misterikkit** [comment]
Will the flaky test run on a pending PR, or only merged code?

**Comment by Huang-Wei** [comment]
@misterikkit only merged PR.

File: test/e2e/scheduling/preemption.go (hunk 1 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: Emm... As this will be removed right after resolving the issue. Maybe not worth adding extra logic?

File: test/e2e/scheduling/preemption.go (hunk 2 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: Sure.

File: test/e2e/scheduling/preemption.go (hunk 3 above)
Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: Done.

File: test/e2e/scheduling/preemption.go (hunk 1 above)
Comment (bsalamat) [reply test/e2e/scheduling/preemption.go]: I like Jonathan's idea. It is not really much additional logic. It is just a little bit of reorganization of the code. With that change, we could even leave the code and not remove it later.

Comment (Huang-Wei) [reply test/e2e/scheduling/preemption.go]: np, I will figure out. In that case, I don't need to comment it as "TODO", I suppose.

**Comment by Huang-Wei** [comment]
@bsalamat @misterikkit PTAL.

PS: [`JustAfterEach()`](https://github.com/onsi/ginkgo/pull/484) is only available in latest ginkgo release. Current k8s dependency is a little behind. I'd say not bother upgrading the vendor libs as `AfterEach()` also works for this case.

**Review by misterikkit — COMMENTED** [review]
/lgtm

**Review by bsalamat — COMMENTED** [review]
Thanks, @Huang-Wei and @misterikkit!

**Comment by Huang-Wei** [comment]
Thanks @bsalamat and @misterikkit !!
