### PR TITLE
kubelet: fix sandbox garbage collection

### LINKED ISSUE #42856: CRI: PodSandbox may be garbage collected early before it is ready
Forked from https://github.com/kubernetes/kubernetes/issues/42736#issuecomment-285268573. 

Currently, kuberuntime garbage collection can't distinguish just-created sandboxes from failed sandboxes. Especially when the time from sandbox creation to ready is longer than GC's minAge. In such cases, those sandboxes may be garbage collected early before they are ready.

Some ideas of solving this problem:

- runtime (e.g. dockershim) filter out those created-but-not-ready sandboxes from sandbox list
- introduce another sandbox state CREATED in CRI

cc @yujuhong @kubernetes/sig-node-bugs

### PR DESCRIPTION
**Pull request by feiskyer**
**What this PR does / why we need it**:

Currently, kuberuntime garbage collection can't distinguish just-created sandboxes from failed sandboxes. Especially when the time from sandbox creation to ready is longer than GC's minAge. In such cases, those sandboxes may be garbage collected early before they are ready.

This PR removes `sandboxMinGCAge` and only garbage collect sandboxes when 

* they are containing no containers at all
* and not the latest sandbox if it is belonging to an existing pod.

**Which issue this PR fixes** 

Fixes #42856.

**Release note**:

```release-note
NONE
```

cc @yujuhong @Random-Liu

### CODE REVIEW

**Comment by feiskyer** [comment]
@k8s-bot kops aws e2e test this

**Comment by feiskyer** [comment]
@k8s-bot kops aws e2e test this

**Comment by feiskyer** [comment]
ping @yujuhong @Random-Liu

**Comment by feiskyer** [comment]
ping @Random-Liu @yujuhong

**Comment by Random-Liu** [comment]
Will take a look tomorrow.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 1]
```diff
@@ -128,6 +130,18 @@ func (cgc *containerGC) removeOldestN(containers []containerGCInfo, toRemove int
 	return containers[:numToKeep]
 }
 
+// removeOldestNSandboxes removes the oldest toRemove sandboxes and returns the resulting slice.
+func (cgc *containerGC) removeOldestNSandboxes(sandboxes []sandboxGCInfo, toRemove int) []sandboxGCInfo {
+	// Remove from oldest to newest (last to first).
+	numToKeep := len(sandboxes) - toRemove
+	for i := numToKeep; i < len(sandboxes); i++ {
+		cgc.removeSandbox(sandboxes[i].id)
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: Why don't we log error here?

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 2]
```diff
@@ -252,39 +267,43 @@ func (cgc *containerGC) evictSandboxes(minAge time.Duration) error {
...
 	}
 
-	for _, sandbox := range evictSandboxes {
-		cgc.removeSandbox(sandbox)
+	for podUID, sandboxes := range evictSandboxes {
+		if cgc.isPodDeleted(podUID) {
+			// Remove all sandboxes if pod has been deleted.
+			cgc.removeOldestNSandboxes(sandboxes, len(sandboxes))
+		} else {
+			// Keep latest one if pod is still exist.
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: s/is still exist/still exists

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 3]
```diff
@@ -252,39 +267,43 @@ func (cgc *containerGC) evictSandboxes(minAge time.Duration) error {
...
+			cgc.removeOldestNSandboxes(sandboxes, len(sandboxes)-1)
+		}
 	}
+
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: nit: Unnecessary empty line.

File: pkg/kubelet/kuberuntime/kuberuntime_gc_test.go [hunk 4]
```diff
@@ -52,55 +68,49 @@ func TestSandboxGC(t *testing.T) {
 		remain      []int               // template indexes of remaining sandboxes
 	}{
 		{
-			description: "sandbox with no containers should be garbage collected.",
+			description: "sandboxes without containers for deleted pods should be garbage collected.",
 			sandboxes: []sandboxTemplate{
-				{pod: pods[0], state: runtimeapi.PodSandboxState_SANDBOX_NOTREADY},
+				makeGCSandbox(pods[2], 0, runtimeapi.PodSandboxState_SANDBOX_NOTREADY),
+				makeGCSandbox(pods[2], 0, runtimeapi.PodSandboxState_SANDBOX_READY),
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc_test.go]: Not sure whether we should remove READY sandbox. `SyncLoop` may be stopping the sandbox, too. This may introduce race that sandbox is stopped twice.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 5]
```diff
@@ -252,39 +267,43 @@ func (cgc *containerGC) evictSandboxes(minAge time.Duration) error {
 		return err
 	}
 
-	evictSandboxes := make([]string, 0)
-	newestGCTime := time.Now().Add(-minAge)
+	evictSandboxes := make(sandboxesByPodUID)
 	for _, sandbox := range sandboxes {
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: Why not skip running sandbox?

File: pkg/kubelet/kuberuntime/kuberuntime_gc_test.go [hunk 6]
```diff
@@ -34,6 +34,19 @@ func TestSandboxGC(t *testing.T) {
 	fakeRuntime, _, m, err := createTestRuntimeManager()
 	assert.NoError(t, err)
 
+	fakePodGetter := m.containerGC.podGetter.(*fakePodGetter)
+	makeGCSandbox := func(pod *v1.Pod, attempt uint32, state runtimeapi.PodSandboxState) sandboxTemplate {
+		if pod.Name != "deleted" {
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc_test.go]: Why not introduce an arguement to indicate whether to add the pod into pod getter?

File: pkg/kubelet/kuberuntime/kuberuntime_gc_test.go [hunk 7]
```diff
@@ -52,55 +68,49 @@ func TestSandboxGC(t *testing.T) {
...
-			containers: []containerTemplate{},
-			minAge:     time.Hour, // assume the test won't take an hour
-			remain:     []int{0},
-		},
-		{
 			description: "multiple sandboxes should be handled properly.",
 			sandboxes: []sandboxTemplate{
 				// running sandbox.
-				{pod: pods[0], attempt: 1, state: runtimeapi.PodSandboxState_SANDBOX_READY},
+				makeGCSandbox(pods[0], 1, runtimeapi.PodSandboxState_SANDBOX_READY),
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc_test.go]: I don't understand, why the `2` is not deleted here? We only keep the latest sandbox right?

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 8]
```diff
@@ -239,9 +253,10 @@ func (cgc *containerGC) evictContainers(gcPolicy kubecontainer.ContainerGCPolicy
 	return nil
 }
 
-// evictSandboxes evicts all sandboxes that are evictable. Evictable sandboxes are: not running
-// and contains no containers at all.
-func (cgc *containerGC) evictSandboxes(minAge time.Duration) error {
+// evictSandboxes evicts all sandboxes that are evictable. Evictable sandboxes are:
+// containing no containers at all and not the latest sandbox if it is belonging to
```
Comment (yujuhong) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: Reword a little bit to make this more clear:
```
// evictSandboxes remove all evictable sandboes. An evictable sandbox must
// meet the following requirements:
//   1. contains no containers.
//   2. belong to a non-existent (i.e., already removed) pod, or is not the
//      most recently created sandbox for the pod.
```

**Comment by yujuhong** [comment]
It's a shame because I actually like the original implementation which removes the podsandbox only when there are no associated containers in it. I think that'd be the right model as we *slowly* move away from using dead container bodies as tombstones.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 1 above)
Comment (feiskyer) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: There is already such log inside `cgc.removeSandbox`

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 5 above)
Comment (feiskyer) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: The new logic only keeps the latest sandbox for each pod, all other sandboxes (including running ones) should be removed.

File: pkg/kubelet/kuberuntime/kuberuntime_gc_test.go (hunk 4 above)
Comment (feiskyer) [inline pkg/kubelet/kuberuntime/kuberuntime_gc_test.go]: Yes, didn't notice this problem. Will update to omit the ready sandbox.

**Comment by feiskyer** [comment]
@Random-Liu @yujuhong Addressed comments. PTAL.

> It's a shame because I actually like the original implementation which removes the podsandbox only when there are no associated containers in it. I think that'd be the right model as we slowly move away from using dead container bodies as tombstones.

@yujuhong That's also my initial proposal,  but it needs a new sandbox state (and of course new sandbox APIs) to do that way, see [here](https://github.com/kubernetes/kubernetes/issues/42856#issuecomment-286012484). I think keeping  latest pod sandbox (in this PR) is better because it follows same logic as we do for container GC.

**Comment by feiskyer** [comment]
@k8s-bot cvm gce e2e test this

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 1 above)
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: I see.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 9]
```diff
@@ -253,9 +253,12 @@ func (cgc *containerGC) evictContainers(gcPolicy kubecontainer.ContainerGCPolicy
 	return nil
 }
 
-// evictSandboxes evicts all sandboxes that are evictable. Evictable sandboxes are:
-// containing no containers at all and not the latest sandbox if it is belonging to
-// an existing pod.
+// evictSandboxes remove all evictable sandboes. An evictable sandbox must
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: I believe this function is wrong.

For container garbage collection, what we are doing:
1) get `evictableContainers` (prune out running ones);
2) remove all or keep latest `evictableContainers` based on whether the pod is deleted.

I quite don't understand what the PR is doing now.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 10]
```diff
@@ -295,15 +313,15 @@ func (cgc *containerGC) evictSandboxes() error {
 	}
 
 	for podUID, sandboxes := range evictSandboxes {
-		if cgc.isPodDeleted(podUID) {
-			// Remove all sandboxes if pod has been deleted.
+		if cgc.isPodDeleted(podUID) || len(activeSandboxes[podUID]) > 0 {
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: 1) Why remove all sandboxes when there is active sandbox?
2) Are you sure `sandboxes` is "evictable sandboxes"?

**Review by Random-Liu — CHANGES_REQUESTED** [review]

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 10 above)
Comment (feiskyer) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: Sorry, this logic is actually wrong.

**Comment by feiskyer** [comment]
> For container garbage collection, what we are doing:
> 
> * get evictableContainers (prune out running ones);
> * remove all or keep latest evictableContainers based on whether the pod is deleted.

Yep, but sandboxes are slightly different: 

* sandboxes should not be removed if there are still containers belonging to it. 

Added a new commit, which changed the logic to:

* Get all sandboxes by podUID first, mark sandboxes as active which is ready or with containers
* Sort sandboxes by creation time
* Remove inactive sandboxes
    * remove all inactive sandboxes if pod has been removed
   * else, keep the latest one (regardless of its state)

@Random-Liu PTAL. Feel free to file a new PR if you have different opinions.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 9 above)
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: s/sandboes/sandboxes

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 11]
```diff
@@ -130,12 +132,15 @@ func (cgc *containerGC) removeOldestN(containers []containerGCInfo, toRemove int
...
-// removeOldestNSandboxes removes the oldest toRemove sandboxes and returns the resulting slice.
+// removeOldestNSandboxes removes the oldest inactive toRemove sandboxes and
+// returns the resulting slice.
 func (cgc *containerGC) removeOldestNSandboxes(sandboxes []sandboxGCInfo, toRemove int) []sandboxGCInfo {
 	// Remove from oldest to newest (last to first).
 	numToKeep := len(sandboxes) - toRemove
 	for i := numToKeep; i < len(sandboxes); i++ {
-		cgc.removeSandbox(sandboxes[i].id)
+		if !sandboxes[i].active {
+			cgc.removeSandbox(sandboxes[i].id)
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: If there is an active sandbox here, returning `sandboxes[:numToKeep]` doesn't make sense to me.

Although we don't use the return value, but the code may confuse people.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 12]
```diff
@@ -279,31 +298,26 @@ func (cgc *containerGC) evictSandboxes() error {
...
-		sort.Sort(sandboxByCreated(evictSandboxes[uid]))
+	for uid := range sandboxesByPod {
+		sort.Sort(sandboxByCreated(sandboxesByPod[uid]))
 	}
 
-	for podUID, sandboxes := range evictSandboxes {
+	for podUID, sandboxes := range sandboxesByPod {
 		if cgc.isPodDeleted(podUID) {
-			// Remove all sandboxes if pod has been deleted.
+			// Remove all evictable sandboxes if the pod has been removed.
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: Why not keeping the logic the same with container? I didn't see difference except that sandbox with containers is not evictable.

We could still generate an evictable sandboxes list, and use it here.

Comment (feiskyer) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: > In you comment, you said that "keep the latest one (regardless of its state)", but here I didn't see that.

I think you are reviewing an old commit. There is no such comment in latest commit.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 11 above)
Comment (feiskyer) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: Yep, will remove the return value

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 12 above)
Comment (feiskyer) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: > In you comment, you said that "keep the latest one (regardless of its state)", but here I didn't see that.

Sorry, it is in the previous comment. I mean the latest one should be kept, whether it is ready or not. And other active ones are also kept. Will make an update to the comment:

* remove all inactive sandboxes if pod has been removed
* else
  * keep active sandboxes
  * keep the latest sandbox whether it is active or not
  * remove other inactive sandboxes

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 13]
```diff
@@ -128,6 +132,18 @@ func (cgc *containerGC) removeOldestN(containers []containerGCInfo, toRemove int
 	return containers[:numToKeep]
 }
 
+// removeOldestNSandboxes removes the oldest inactive toRemove sandboxes and
+// returns the resulting slice.
+func (cgc *containerGC) removeOldestNSandboxes(sandboxes []sandboxGCInfo, toRemove int) {
+	// Remove from oldest to newest (last to first).
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: Is this `oldest to newest`? Seems to be newest to oldest...

And also the same question for the container remove function.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go [hunk 14]
```diff
@@ -252,38 +272,48 @@ func (cgc *containerGC) evictSandboxes(minAge time.Duration) error {
...
+		sort.Sort(sandboxByCreated(sandboxesByPod[uid]))
+	}
+
+	for podUID, sandboxes := range sandboxesByPod {
+		if cgc.isPodDeleted(podUID) {
+			// Remove all evictable sandboxes if the pod has been removed.
+			cgc.removeOldestNSandboxes(sandboxes, len(sandboxes))
+		} else {
+			// Keep latest one if the pod still exists.
+			cgc.removeOldestNSandboxes(sandboxes, len(sandboxes)-1)
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: Maybe explain that we don't need to keep the latest dead sandbox if there is an active one? Since this is different from container gc behavior.

File: pkg/kubelet/kuberuntime/kuberuntime_gc_test.go [hunk 15]
```diff
@@ -34,6 +34,19 @@ func TestSandboxGC(t *testing.T) {
 	fakeRuntime, _, m, err := createTestRuntimeManager()
 	assert.NoError(t, err)
 
+	fakePodGetter := m.containerGC.podGetter.(*fakePodGetter)
+	makeGCSandbox := func(pod *v1.Pod, attempt uint32, state runtimeapi.PodSandboxState, withPodGetter bool) sandboxTemplate {
+		if withPodGetter {
+			// initialize the pod getter, explicitly exclude deleted pod
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc_test.go]: Update the comment.

File: pkg/kubelet/kuberuntime/kuberuntime_gc_test.go [hunk 16]
```diff
@@ -52,50 +68,51 @@ func TestSandboxGC(t *testing.T) {
...
+				makeGCSandbox(pods[1], 0, runtimeapi.PodSandboxState_SANDBOX_NOTREADY, true),
+			},
+			containers: []containerTemplate{},
+			remain:     []int{0, 1},
+		},
+		{
 			description: "sandbox with containers should not be garbage collected.",
 			sandboxes: []sandboxTemplate{
-				{pod: pods[0], state: runtimeapi.PodSandboxState_SANDBOX_NOTREADY},
+				makeGCSandbox(pods[0], 0, runtimeapi.PodSandboxState_SANDBOX_NOTREADY, true),
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc_test.go]: s/true/false

Or else sandbox will not be removed because there is corresponding pod.

File: pkg/kubelet/kuberuntime/kuberuntime_gc_test.go [hunk 17]
```diff
@@ -52,50 +68,51 @@ func TestSandboxGC(t *testing.T) {
...
-			containers: []containerTemplate{},
-			minAge:     time.Hour, // assume the test won't take an hour
-			remain:     []int{0},
-		},
-		{
 			description: "multiple sandboxes should be handled properly.",
 			sandboxes: []sandboxTemplate{
 				// running sandbox.
-				{pod: pods[0], attempt: 1, state: runtimeapi.PodSandboxState_SANDBOX_READY},
+				makeGCSandbox(pods[0], 1, runtimeapi.PodSandboxState_SANDBOX_READY, true),
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_gc_test.go]: Should have another exit `pods[0]` to make sure we don't keep latest exit if there is a running one.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 13 above)
Comment (feiskyer) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: ACK. Would fix this.

File: pkg/kubelet/kuberuntime/kuberuntime_gc.go (hunk 14 above)
Comment (feiskyer) [inline pkg/kubelet/kuberuntime/kuberuntime_gc.go]: ACK

File: pkg/kubelet/kuberuntime/kuberuntime_gc_test.go (hunk 17 above)
Comment (feiskyer) [inline pkg/kubelet/kuberuntime/kuberuntime_gc_test.go]: ACK.

**Comment by feiskyer** [comment]
@Random-Liu Updated. PTAL.

**Review by Random-Liu — APPROVED** [review]

**Comment by feiskyer** [comment]
> @feiskyer Please keep an eye on the test grid to make sure this doesn't introduce flake. :)

Sure.
