### PR TITLE
Return "410 Gone" errors via watch stream when using watch cache

### LINKED ISSUE #25151: Watch cache regression: changes behavior of "resource version too old" error
When attempting to fetch a resource version that is too old, the behavior of watch (for both HTTP and web sockets) changed when watch cache was enabled.  The watch cache returns a 410 - without the watch cache, we return 200 and then write an "error" entry to the watch stream.  This broke a client that dependent on the watch behavior, and moreover is inconsistent with other errors we set in the registry.  Also, for watch over web sockets, most javascript clients will be unable to get at a 410 error from the connection, because browsers don't get access to the data.

We should restore the watch cache behavior to be consistent with the previous behavior as this is a regression in API semantics.

Resource without watch cache, watching too old:

```
$ curl ... "https:///oapi/v1/namespaces/clayton-dev/builds?watch=1&resourceVersion=1"
> GET /oapi/v1/namespaces/clayton-dev/builds?watch=1&resourceVersion=1 HTTP/1.1
> Accept: application/json, */*
> User-Agent: oc/v1.3.0 (darwin/amd64) kubernetes/2787678
> 
< HTTP/1.1 200 OK
< Cache-Control: no-store
< Transfer-Encoding: chunked
< Date: Wed, 04 May 2016 18:10:26 GMT
< Content-Type: text/plain; charset=utf-8
< Transfer-Encoding: chunked
< 
{"type":"ERROR","object":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"401: The event in requested index is outdated and cleared (the requested history has been cleared [4046756/2]) [4047755]","reason":"Expired","code":410}}
```

Resource with watch cache, watching too old:

```
$ curl ... "https:///apis/extensions/v1beta1/namespaces/clayton-dev/horizontalpodautoscalers?watch=1&resourceVersion=1"
> GET /apis/extensions/v1beta1/namespaces/clayton-dev/horizontalpodautoscalers?watch=1&resourceVersion=1 HTTP/1.1
> Accept: application/json, */*
> User-Agent: oc/v1.3.0 (darwin/amd64) kubernetes/2787678
> 
< HTTP/1.1 410 Gone
< Cache-Control: no-store
< Content-Type: application/json
< Date: Wed, 04 May 2016 18:08:25 GMT
< Content-Length: 146
< 
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"too old resource version: 1 (4034675)","reason":"Gone","code":410}
```

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #25151

This PR updates the API server to produce the same results when a watch is attempted with a resourceVersion that is too old, regardless of whether the etcd watch cache is enabled. The expected result is a `200` http status, with a single watch event of type `ERROR`. Previously, the watch cache would deliver a `410` http response.

This is the uncached watch impl:

```
// Implements storage.Interface.
func (h *etcdHelper) WatchList(ctx context.Context, key string, resourceVersion string, filter storage.FilterFunc) (watch.Interface, error) {
    if ctx == nil {
        glog.Errorf("Context is nil")
    }
    watchRV, err := storage.ParseWatchResourceVersion(resourceVersion)
    if err != nil {
        return nil, err
    }
    key = h.prefixEtcdKey(key)
    w := newEtcdWatcher(true, h.quorum, exceptKey(key), filter, h.codec, h.versioner, nil, h)
    go w.etcdWatch(ctx, h.etcdKeysAPI, key, watchRV)
    return w, nil
}
```

once the resourceVersion parses, there is no path that returns a direct error, so all errors would have to be returned as an `ERROR` event via the ResultChan().

### CODE REVIEW

File: pkg/storage/cacher.go [hunk 1]
```diff
@@ -455,6 +461,46 @@ func (lw *cacherListerWatcher) Watch(options api.ListOptions) (watch.Interface,
...
 }
 
+// cacherWatch implements watch.Interface to return a single error
+type errWatcher struct {
+	result chan watch.Event
+}
+
+func newErrWatcher(err error) *errWatcher {
+	// Create an error event
+	errEvent := watch.Event{Type: watch.Error}
```
Comment (smarterclayton) [inline pkg/storage/cacher.go]: I would probably be better if this could use apiserver.StatusForError.

Comment (smarterclayton) [inline pkg/storage/cacher.go]: But it's fine for here.

Comment (liggitt) [inline pkg/storage/cacher.go]: ah, I didn't know about `errToAPIStatus`... I'd like to keep this targeted for picking, can rework to expose and use errToAPIStatus (maybe moved to the api/errors package?) as a follow up

**Comment by lavalamp** [comment]
LGTM

**Comment by liggitt** [comment]
rebased

**Comment by wojtek-t** [comment]
LGTM - thanks!

**Comment by liggitt** [comment]
not sure what is going on with the tests... all tests hung with no results
@k8s-bot please test this #IGNORE

**Comment by liggitt** [comment]
rebased

**Comment by liggitt** [comment]
@k8s-bot unit test this issue #25349

**Comment by liggitt** [comment]
@k8s-bot unit test this issue #25037

**Comment by hongchaodeng** [comment]
The test flake doesn't look related to #25037.
Logs are [here](https://00e9e64bac1e3d65bed001bc8725639829404925db899f7e8d-apidata.googleusercontent.com/download/storage/v1_internal/b/kubernetes-jenkins/o/pr-logs%2Fpull%2F25369%2Fkubernetes-pull-test-unit-integration%2F25195%2Fbuild-log.txt?qk=AD5uMEvYDiq0ija4QO2e8dllyCPGTSenXc5vimi8PnxtTmAUJLYG7Gu6f9ZOyaIdsjLTeWlEiY_z3cL94Hm-Al4b0sMlHSj6iVdDU1N6QSU84CNUY-xV7LG2a-Eos2QGHXPDPZ4ZEBMR6wyBu-PUNB31FNzfPD8CQ5nel8CHnTflAAyv__qDVQU3kM_F6l9l30NsffZ2WdargbGELnhYjrAfl5h_4bP2C4kRiwSuGFZ_HkHOpt2lGXG4SDxIM2trktaH6LNSlgZli7DqqgCt2AjwHtdI3AoidAQ_Oz2CFcqTvhL5wxD46KBhFWwQ7RmGrkUB8EVCYTCHXtPHYAd2u_JZl4BsYR-rm8pHYUx0R1MMQ_1QD7OVnp2SgI26DPX7wVSD1aiYwrXdtu0kwhyRMYC9Pqrrseym2j1QW1D3WnYPWv-rym8bV6gT3ExFeHtO7hcv206zfKBo6VuCiTLLj4LRKWg8u9MNddx0I0r0MtZNCfRybKv4vR82OaBIrc2UW9gO3r3wTpBiXVNogwx-2mdSDyKM7BNVQT9_5ATJnhMude1lbzAG7jIE1D9lZEunHrOGUZxxBIauH6J6c25ZA0LuDCiQlhCVpbqfAMk-aG95zHeVzzb02itJBk1RoL2lGE1wIP_-Udn0YVEQiMKV0cRNi3p2Or3vEeQAbHwAXomYG2X_O-TzTkurQvuIgR5XKQQgD5RYFeHvMoUX9inUDe6d4IIJz_gWeWOMKUg8-_SHYyvqluJZVnAW7oaIUbvMqUi4dZPLMDC5Y-6Vk0D62ejXJebE83TBqjiMH8GItTSVwODjIHadmk1Wgx7dw0YBLybTOk_3v3ggUmgTli78cwohg9eyAkGeF-cFkclqoVIbCAuQyJNBGpIDrhITFlUB7ZnrsBAk_l4Q4WpbPYJf2MH6q8VdXHgX8dKdHb09AmP2V4Wazu4KP-c).

```Go
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xff3f77]

goroutine 581 [running]:
panic(0x21d0c00, 0xc8200120d0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
k8s.io/kubernetes/pkg/controller/framework.(*Controller).HasSynced(0x0, 0x463ec0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/controller.go:108 +0x47
k8s.io/kubernetes/pkg/controller/framework.(*sharedIndexInformer).HasSynced(0xc820019380, 0xa2e2ae)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/framework/shared_informer.go:161 +0x25
k8s.io/kubernetes/pkg/controller/framework.(SharedIndexInformer).HasSynced-fm(0xe00000028)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:100 +0x32
k8s.io/kubernetes/pkg/controller/endpoint.(*EndpointController).syncService(0xc820019440, 0xc8209ea960, 0x12)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:310 +0xf8
k8s.io/kubernetes/pkg/controller/endpoint.(*EndpointController).worker.func1(0xc820019440)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:299 +0xe3
k8s.io/kubernetes/pkg/controller/endpoint.(*EndpointController).worker(0xc820019440)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:300 +0x21
k8s.io/kubernetes/pkg/controller/endpoint.(*EndpointController).(k8s.io/kubernetes/pkg/controller/endpoint.worker)-fm()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:151 +0x20
k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc820d0c330)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:66 +0x4b
k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc820d0c330, 0x3b9aca00, 0x0, 0xc820112ba0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:67 +0x68
k8s.io/kubernetes/pkg/util/wait.Until(0xc820d0c330, 0x3b9aca00, 0xc820112ba0)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/util/wait/wait.go:47 +0x3e
created by k8s.io/kubernetes/pkg/controller/endpoint.(*EndpointController).Run
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controller/endpoint/endpoints_controller.go:151 +0x147
!!! Error in ./hack/test-integration.sh:58
  'KUBE_TEST_API_VERSIONS="$1" "${KUBE_OUTPUT_HOSTBIN}/integration" --v=${LOG_LEVEL} --max-concurrency="${KUBE_INTEGRATION_TEST_MAX_CONCURRENCY}" --watch-cache=true' exited with status 2
Call stack:
  1: ./hack/test-integration.sh:58 runTests(...)
  2: ./hack/test-integration.sh:83 main(...)
```

I'm more worried about there is some race or assumptions made in integration test.
