### PR TITLE
Make sure docker is properly shutdown before startup.

### LINKED ISSUE #21261: e2e flake: tests are failing on "All nodes should be ready" condition
I've seen a bunch of different failure, with number of tests failing due to:

     Feb 14 08:36:31.720: FAIL: All nodes should be ready after test,

The example failure is here:
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/21020/kubernetes-pull-build-test-e2e-gce/28512/build-log.txt
[but there were 5+ more today in different places & suites]

### PR DESCRIPTION
**Pull request by dchen1107**
Fix #21261, #20908, ...

Partially resolve some issue with #21523

### CODE REVIEW

File: cluster/saltbase/salt/supervisor/docker-checker.sh [hunk 1]
```diff
@@ -19,10 +19,21 @@
 # which in turn restarts docker.
 
 /etc/init.d/docker stop
+# Make sure docker gracefully terminated before start again
+while true; do
```
Comment (zmerlynn) [inline cluster/saltbase/salt/supervisor/docker-checker.sh]: This can be compressed to:
```
while pidof docker > /dev/null; do
  echo "waiting on clean docker shutdown"
  sleep 10
done
```

**Comment by dchen1107** [comment]
I merge this one manually to stop tons of flake issues.
