### PR TITLE
Fix flake on TestQuotaLimitService

### LINKED ISSUE #107273: Failure cluster [28311165...] Make integration test TestQuotaLimitService wait longer, to avoid flakes
##### Error text:
```
=== RUN   TestQuotaLimitService
I1230 00:54:57.057578  122720 controller.go:163] quota evaluator worker shutdown
I1230 00:54:57.057590  122720 controller.go:163] quota evaluator worker shutdown
I1230 00:54:57.057591  122720 controller.go:163] quota evaluator worker shutdown
I1230 00:54:57.057599  122720 controller.go:163] quota evaluator worker shutdown
I1230 00:54:57.057603  122720 controller.go:163] quota evaluator worker shutdown
W1230 00:54:57.058001  122720 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
I1230 00:54:57.058561  122720 apf_controller.go:218] NewTestableController "Controller" with serverConcurrencyLimit=600, requestWaitLimit=15s, name=Controller, asFieldManager="api-priority-and-fairness-config-consumer-v1"
I1230 00:54:57.058634  122720 apf_controller.go:769] No exempt PriorityLevelConfiguration found, imagining one
I1230 00:54:57.058647  122720 apf_controller.go:769] No catch-all PriorityLevelConfiguration found, imagining one
W1230 00:54:57.058679  122720 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W1230 00:54:57.058700  122720 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
I1230 00:54:57.058748  122720 services.go:51] Setting service IP to "10.0.0.1" (read-write).
I1230 00:54:57.058768  122720 instance.go:318] Node port range unspecified. Defaulting to 30000-32767.
I1230 00:54:57.058782  122720 instance.go:274] Using reco
```
#### Recent failures:
[2021/12/30 上午8:28:34 ci-kubernetes-integration-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1476348992219516928)

/kind failing-test

/kind flake

/sig api-machinery

### PR DESCRIPTION
**Pull request by jlsong01**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
A flake issue. It looks like APF is sometimes sending 429 responses, which is what is disrupting the initial discovery (and generally making the test take ~3 times as long as necessary).

We should update the test to run the quota controller and API requests with a user that APF will not throttle

#### Which issue(s) this PR fixes:

Fixes #107273

#### Special notes for your reviewer:
The flake issue can be reproduced easily with stress command on my local environment. 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

**Comment by jlsong01** [comment]
@aojea @SataQiu 
Hello. I am trying to fix the flake, could you please take a look at the PR? Thanks.

**Comment by aojea** [comment]
I think that the resource quota timeout has to be the same or greater than

https://github.com/kubernetes/kubernetes/blob/7c013c3f64db33cf19f38bb2fc8d9182e42b0b7b/test/integration/quota/quota_test.go#L489-L490

can you verify it? if true, we should add a comment or make both use the same constant to not drift in the future

**Comment by jlsong01** [comment]
According to the comments, the verification is in progress...  will update when verification is complete.

**Comment by jlsong01** [comment]
@aojea Hi, Thanks for your comments.

I have verified several cases with different resource quota timeout. According to the verification result, seems the proper timeout value may be set as 300s. 

Verification command: `stress ./quota.test -test.run TestQuotaLimitService`
Verification duration: 1 Hour

**Case 1**: resourceQuotaTimeout = 30 * time.Second
**Result**: 1h0m0s: 308 runs so far, 5 failures (1.62%)

**Case 2**: resourceQuotaTimeout = 60 * time.Second
**Result** : 1h0m0s: 526 runs so far, 6 failures (1.14%)

**Case 3**: resourceQuotaTimeout = 90 * time.Second
**Result:**: 1h0m0s: 479 runs so far, 4 failures (0.84%)

**Case 4**: resourceQuotaTimeout = 120 * time.Second
**Result:**: 1h0m0s: 543 runs so far, 8 failures (1.47%)

**Case 5**: resourceQuotaTimeout = 150 * time.Second
**Result:**:  1h0m0s: 775 runs so far, 9 failures (1.16%)

**Case 6**: resourceQuotaTimeout = 300 * time.Second
**Result:**: 1h0m0s: 313 runs so far, 0 failures

**Case 7**: resourceQuotaTimeout = 600 * time.Second
**Result:**: 1h0m0s: 429 runs so far, 0 failures

**Comment by jlsong01** [comment]
@aojea I do need your help to further proceed the PR.

I spent serveral hours digging into quota controller code but did not find the clew for this flake.

It was thought that for quota controller, two `worker` and `sync` may race for `workerLock.(R)Lock`, e.g. `sync` goroutine grab the Lock, and then `worker` has to wait until sync release the Lock. However, according to flake log: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1476348992219516928 , sync completed `I1230 00:55:03.626191  122720 resource_quota_controller.go:458] synced quota controller`, and the later 30s goroutine `sync` will not grab `workerLock`. But `ResourceQuotas` object was not updated in time(within timeout 10s).

1. I am wondering why `ResourceQuotas` object was not updated within 10s, but in 11s it was updated correctly(from the flake log)
2. How can we add a certain control on the test scenario to avoid race by design

**Comment by jlsong01** [comment]
The fix proposal:
1. set resource quota timeout the same as controller sync period: 30s
2. in `waitForQuota(),` set wait time as 3 minitues instead of 1 minute, in order to give more time for quota object update from api server

I have verified the above solution for 1 hour with the pervious method, and `Result: 1h0m0s: 488 runs so far, 0 failures`

**Comment by jlsong01** [comment]
@aojea Could you please take another look. Thanks.

**Comment by jlsong01** [comment]
I have re-verified this change for 1 hour stress test, and it passed.

@aojea PTAL, thanks

**Comment by aojea** [comment]
/ok-to-test
/lgtm
Thanks for working so hard on this
/assign @liggitt 
for approval

File: test/integration/quota/quota_test.go [hunk 1]
```diff
@@ -484,10 +486,10 @@ func TestQuotaLimitService(t *testing.T) {
 	if err != nil {
 		t.Fatalf("unexpected err: %v", err)
 	}
-	go resourceQuotaController.Run(ctx, 2)
+	go resourceQuotaController.Run(ctx, 1)
 
 	// Periodically the quota controller to detect new resource types
-	go resourceQuotaController.Sync(discoveryFunc, 30*time.Second, ctx.Done())
+	go resourceQuotaController.Sync(discoveryFunc, controllerSyncPeriod, ctx.Done())
```
Comment (liggitt) [inline test/integration/quota/quota_test.go:492]: if we're not adding/removing defined types (e.g. CRDs) in this test, this sync should have no effect, right? it's not clear to me why we're shortening this from happening every 30 seconds to happen every 5 seconds

File: test/integration/quota/quota_test.go [hunk 2]
```diff
@@ -355,10 +357,10 @@ func TestQuotaLimitedResourceDenial(t *testing.T) {
...
```
Comment (liggitt) [inline test/integration/quota/quota_test.go:363]: same question here... we're not adding/removing defined types (e.g. CRDs) in this test, so why do we care how often this sync happens?

File: test/integration/quota/quota_test.go [hunk 3]
```diff
@@ -124,10 +126,10 @@ func TestQuota(t *testing.T) {
...
```
Comment (liggitt) [inline test/integration/quota/quota_test.go:132]: same question here... we're not adding/removing defined types (e.g. CRDs) in this test, so why do we care how often this sync happens?

Comment (aojea) [reply test/integration/quota/quota_test.go:132]: I suggested that, I don't know how the quota controller works exactly, but I assumed this will make the test faster and allow to wait for the `resourceQuotaTimeout` 2 times the sync period ... it was more by intution

Comment (jlsong01) [reply test/integration/quota/quota_test.go:132]: Here is my understanding, please correct me if I am wrong.

This test need watch service object from api-server. When service create/update/delete event processing failed and do not re-queue somehow, we have to wait until next sync period(currently 30s). However, resourceQuotaTimeout is currently 10s, that may be insufficient in some flake case. So, sync period should be less than resourceQuotaTimeout, and we propose as the half of resourceQuotaTimeout.

Comment (liggitt) [reply test/integration/quota/quota_test.go:132]: this sync is about syncing new resource *types*, not resyncing resource instances. you can comment this line out entirely and the test still passes.

the only time this sync is relevant is if the initial discovery of resource types failed when initializing the controller:
```
		// do initial quota monitor setup.  If we have a discovery failure here, it's ok. We'll discover more resources when a later sync happens.
		resources, err := GetQuotableResources(options.DiscoveryFunc)
		if discovery.IsGroupDiscoveryFailedError(err) {
			utilruntime.HandleError(fmt.Errorf("initial discovery check failure, continuing and counting on future sync update: %v", err))
		} else if err != nil {
			return nil, err
		}
```

In that case, the quota controller continues starting up without surfacing an error, but is not actually functional. It has to wait for the next sync to run to actually discover the resource types that should be quotaed.

It is unexpected that this discovery lookup would fail since we're talking to a local server, so I dug in further. It looks like APF is *sometimes* sending 429 responses, which is what is disrupting the initial discovery (and generally making the test take ~3 times as long as necessary).

We should update the test to run the quota controller and API requests with a user that APF will not throttle

Comment (jlsong01) [reply test/integration/quota/quota_test.go:132]: I agree with your analysis.

A user `system:unsecured` was added with exempt priority level configuration, which should not throttle.

`controllerSyncPeriod` has been reverted into existing 30s.

File: test/integration/quota/quota_test.go (hunk 2 above)
Comment (jlsong01) [reply test/integration/quota/quota_test.go:388]: sync period has been reverted to 30s

File: test/integration/quota/quota_test.go (hunk 1 above)
Comment (jlsong01) [reply test/integration/quota/quota_test.go:558]: sync period has been reverted to 30s

**Review by jlsong01 — COMMENTED** [review]
A user system:unsecured was added with exempt priority level configuration, which should not throttle.

controllerSyncPeriod has been reverted into existing 30s.

File: test/integration/quota/quota_test.go [hunk 4]
```diff
@@ -449,6 +476,47 @@ func TestQuotaLimitService(t *testing.T) {
...
+				},
+			},
+		},
+		metav1.CreateOptions{})
+	if err != nil {
+		t.Errorf("creating flow schema should not have returned error: %v", err)
+	}
+
+	waitForFlowSchema(t, clientset, "testing-exempt-flowschema")
+
```
Comment (liggitt) [inline test/integration/quota/quota_test.go:519]: if we're running with the system privileged group, the existing default `exempt` flowschema should already exempt us from APF, right? I don't think we need these lines

Comment (jlsong01) [reply test/integration/quota/quota_test.go:519]: Originally I planned to use existing default exempt flowschema instead create a new one, but when I tried to correlate the new create user "system:unsecured" with  default exempt flowschema, it failed indicating exempt flowschema can not be modified.

So, either we should add a new flowschema, or use existing default exempt flowschema with the user "system:masters"

Comment (liggitt) [reply test/integration/quota/quota_test.go:519]: the existing exempt flowschema selects requests from the privileged group, which this test runs with now, right?

Comment (liggitt) [reply test/integration/quota/quota_test.go:519]:
```go
	MandatoryFlowSchemaExempt = newFlowSchema(
		"exempt",
		flowcontrol.PriorityLevelConfigurationNameExempt,
		1,  // matchingPrecedence
		"", // distinguisherMethodType
		flowcontrol.PolicyRulesWithSubjects{
			Subjects: groups(user.SystemPrivilegedGroup),
...
```

Comment (jlsong01) [reply test/integration/quota/quota_test.go]: Yeah, as you mentioned, we do not need add another excmpt flowschema. These lines have been removed.

I have run the test again and the output shows APF is selecting that expmpt flowschema as expected.

And one hour stress test has paased as well. Could you please take another look, thank you

**Comment by jlsong01** [comment]
Accoding to the discussion with @liggitt:

1. defaulting integration tests to a privileged user
2. in the few tests(e.g. TestStatus and TestAuthModeAlwaysDeny) that need an unprivileged user, specifically setting that up

Everything has been settled down. @liggitt PTAL, thanks

File: test/integration/quota/quota_test.go (hunk 3 above)
Comment (liggitt) [reply test/integration/quota/quota_test.go:131]: with the integration test user changes, I don't think the changes to this file are relevant any more. go ahead and revert the changes in this file

File: test/integration/framework/controlplane_utils.go [hunk 5]
```diff
@@ -176,7 +186,7 @@ func startAPIServerOrDie(controlPlaneConfig *controlplane.Config, incomingServer
```
Comment (liggitt) [inline test/integration/framework/controlplane_utils.go:186]: to make it easier for tests that need an unprivileged user, define an `UnprivilegedToken` package constant in this file (with a string `unprivileged-user` or something similar), and add an additional user to the `tokens` map above:

```diff
	tokens[privilegedLoopbackToken] = &user.DefaultInfo{
		Name:   user.APIServerUser,
		UID:    uuid.New().String(),
-		Groups: []string{user.SystemPrivilegedGroup},
+		Groups: []string{user.SystemPrivilegedGroup, user.AllAuthenticated},
	}
+	tokens[UnprivilegedToken] = &user.DefaultInfo{
+		Name:   "unprivileged",
+		UID:    uuid.New().String(),
+		Groups: []string{user.AllAuthenticated},
+	}
```

File: test/integration/framework/controlplane_utils.go [hunk 6]
```diff
@@ -80,8 +80,18 @@ func (alwaysAllow) Authorize(ctx context.Context, requestAttributes authorizer.A
 	return authorizer.DecisionAllow, "always allow", nil
 }
 
-// alwaysEmpty simulates "no authentication" for old tests
-func alwaysEmpty(req *http.Request) (*authauthenticator.Response, bool, error) {
+// unsecuredUser simulates requests to the unsecured endpoint for old tests
+func unsecuredUser(req *http.Request) (*authauthenticator.Response, bool, error) {
```
Comment (liggitt) [inline test/integration/framework/controlplane_utils.go:84]: only return the privileged unsecured user if the request didn't attempt to provide any authentication info. if req has an `Authorization` header, `return nil, false, nil`

File: test/integration/framework/controlplane_utils.go [hunk 7]
```diff
@@ -80,8 +80,18 @@ func (alwaysAllow) Authorize(ctx context.Context, requestAttributes authorizer.A
...
+	return &authauthenticator.Response{
+		User: &user.DefaultInfo{
+			Name:   "system:unsecured",
+			Groups: []string{user.SystemPrivilegedGroup, user.AllAuthenticated},
+		},
+	}, true, nil
+}
+
+// AlwaysEmpty simulates "no authentication" for old tests
+func AlwaysEmpty(req *http.Request) (*authauthenticator.Response, bool, error) {
```
Comment (liggitt) [inline test/integration/framework/controlplane_utils.go:94]: drop this function

File: test/integration/auth/auth_test.go [hunk 8]
```diff
@@ -553,6 +557,17 @@ func TestAuthModeAlwaysDeny(t *testing.T) {
...
+	// wrap any available authorizer
+	tokens := make(map[string]*user.DefaultInfo)
+	tokens[privilegedLoopbackToken] = &user.DefaultInfo{
+		Name:   user.APIServerUser,
+		UID:    uuid.New().String(),
+		Groups: []string{user.SystemPrivilegedGroup},
+	}
+	tokenAuthenticator := authenticatorfactory.NewFromTokens(tokens, controlPlaneConfig.GenericConfig.Authentication.APIAudiences)
+	// TestAuthModeAlwaysDeny need an unprivileged user, specifically setting that up
+	controlPlaneConfig.GenericConfig.Authentication.Authenticator = authenticatorunion.New(tokenAuthenticator, authauthenticator.RequestFunc(framework.AlwaysEmpty))
```
Comment (liggitt) [inline test/integration/auth/auth_test.go:570]: drop the custom authenticator here and set up the transport below to use the unprivileged user token:

```go
import (
...
  resttransport k8s.io/client-go/transport
...
)
...

transport := resttransport.NewBearerAuthRoundTripper(framework.UnprivilegedUserToken, http.DefaultTransport)
```

File: test/integration/controlplane/synthetic_controlplane_test.go [hunk 9]
```diff
@@ -191,6 +195,19 @@ func TestStatus(t *testing.T) {
...
+			// wrap any available authorizer
+			tokens := make(map[string]*user.DefaultInfo)
+			tokens[privilegedLoopbackToken] = &user.DefaultInfo{
+				Name:   user.APIServerUser,
+				UID:    uuid.New().String(),
+				Groups: []string{user.SystemPrivilegedGroup},
+			}
+			tokenAuthenticator := authenticatorfactory.NewFromTokens(tokens, tc.controlPlaneConfig.GenericConfig.Authentication.APIAudiences)
+			tc.controlPlaneConfig.GenericConfig.Authentication.Authenticator = authenticatorunion.New(tokenAuthenticator, authauthenticator.RequestFunc(framework.AlwaysEmpty))
+		}
```
Comment (liggitt) [inline test/integration/controlplane/synthetic_controlplane_test.go:210]: drop this and override the authenticator in initStatusForbiddenControlPlaneConfig instead to return an unprivileged user

File: test/integration/framework/controlplane_utils.go (hunk 5 above)
Comment (jlsong01) [reply test/integration/framework/controlplane_utils.go:202]: fixed

File: test/integration/framework/controlplane_utils.go (hunk 6 above)
Comment (jlsong01) [reply test/integration/framework/controlplane_utils.go]: fixed

File: test/integration/framework/controlplane_utils.go (hunk 7 above)
Comment (jlsong01) [reply test/integration/framework/controlplane_utils.go:105]: done

File: test/integration/auth/auth_test.go (hunk 8 above)
Comment (jlsong01) [reply test/integration/auth/auth_test.go]: done

File: test/integration/controlplane/synthetic_controlplane_test.go (hunk 9 above)
Comment (jlsong01) [reply test/integration/controlplane/synthetic_controlplane_test.go]: done

File: test/integration/controlplane/synthetic_controlplane_test.go [hunk 10]
```diff
@@ -141,6 +143,14 @@ func TestEmptyList(t *testing.T) {
 
 func initStatusForbiddenControlPlaneConfig() *controlplane.Config {
 	controlPlaneConfig := framework.NewIntegrationTestControlPlaneConfig()
+	controlPlaneConfig.GenericConfig.Authentication.Authenticator = authenticatorunion.New(
+		authauthenticator.RequestFunc(func(req *http.Request) (*authauthenticator.Response, bool, error) {
+			return &authauthenticator.Response{
+				User: &user.DefaultInfo{
+					Name: "unprivileged",
```
Comment (liggitt) [inline test/integration/controlplane/synthetic_controlplane_test.go:150]: include `Groups: []string{user.AllAuthenticated},`

File: test/integration/controlplane/synthetic_controlplane_test.go [hunk 11]
```diff
@@ -22,6 +22,9 @@ import (
 	"encoding/json"
 	"fmt"
 	"io/ioutil"
+	authauthenticator "k8s.io/apiserver/pkg/authentication/authenticator"
+	authenticatorunion "k8s.io/apiserver/pkg/authentication/request/union"
+	"k8s.io/apiserver/pkg/authorization/authorizerfactory"
```
Comment (liggitt) [inline test/integration/controlplane/synthetic_controlplane_test.go:27]: nit: group these imports with the k8s imports below

**Comment by liggitt** [comment]
two small tweaks, then lgtm

File: test/integration/controlplane/synthetic_controlplane_test.go (hunk 10 above)
Comment (jlsong01) [reply test/integration/controlplane/synthetic_controlplane_test.go:150]: done

File: test/integration/controlplane/synthetic_controlplane_test.go (hunk 11 above)
Comment (jlsong01) [reply test/integration/controlplane/synthetic_controlplane_test.go]: done

**Comment by liggitt** [comment]
/lgtm
/approve

comparing APF output from an integration test run on master:
* apf_controller.go log lines go from 63,771 → 20,389 (~70% reduction)
* catch-all policy log lines go from 139,540 → 6,844 (~95% reduction)

**Comment by aojea** [comment]
> comparing APF output from an integration test run on master:
> 
> * apf_controller.go log lines go from 63,771 → 20,389 (~70% reduction)
> * catch-all policy log lines go from 139,540 → 6,844 (~95% reduction)

:clap:

**Comment by liggitt** [comment]
(remaining integration tests that need their authenticator adjusted noted in https://github.com/kubernetes/kubernetes/issues/96647#issuecomment-1016546231)
