### PR TITLE
kubelet: poll after reloading logind conf

### LINKED ISSUE #133133: Kubelet shutdown manager not properly initialized due to race condition in systemd-logind configuration reloading
### What happened?

Observed error log 
`
kubelet.go:1667] "Failed to start node shutdown manager" err="node shutdown manager was unable to update logind InhibitDelayMaxSec to 30s (ShutdownGracePeriod), current value of InhibitDelayMaxSec (5s) is less than requested ShutdownGracePeriod"
`

And the shutdown inhibitor is not registered to the system so shutdown manager would not be in effect.

The bug seems to be a race condition between systemd-logind config reloading and getting the updated `InhibitDelayMaxSec`. The root cause is the reload command is signaled to systemd-logind with no waiting until the reload is complete.

I am thinking a low cost fix,  rather than properly implementing something to get the reload completion signal, is to just backoff wait up to 5 retries to get the new `InhibitDelayUSec` value

### What did you expect to happen?

Kubelet shutdown manager should work properly

### How can we reproduce it (as minimally and precisely as possible)?

Wrote a program trying to reproduce it

```go
package main

import (
        "fmt"
        "math/rand"
        "os"

        "github.com/godbus/dbus/v5"
)

const (
        logindConfDir = "/etc/systemd/logind.conf.d/"
        tempConfFile  = logindConfDir + "99-test-inhibit-delay.conf"
        logindService = "org.freedesktop.login1"
        logindObject  = dbus.ObjectPath("/org/freedesktop/login1")
)

func main() {
        // This program must be run as root to modify systemd config and call D-Bus methods.
        if os.Geteuid() != 0 {
                fmt.Println("This program must be run as root (sudo).")
                os.Exit(1)
        }

        neg, total := 0, 100000
        for i := 0; i < total; i++ {
                if test() {
                        neg++
                }
                if i%500 == 0 {
                        fmt.Printf("Tested %d times, reproduced the bug %d times\n", i, neg)
                }
        }
        fmt.Printf("Tested %d times, reproduced the bug %d times", total, neg)
}

func test() bool {
        newInhibitDelaySec := rand.Intn(100) + 15
        conn, err := dbus.SystemBus()
        if err != nil {
                fmt.Printf("Failed to connect to system D-Bus: %v\n", err)
                os.Exit(1)
        }
        defer conn.Close()

        if err := os.MkdirAll(logindConfDir, 0755); err != nil {
                fmt.Printf("Failed to create logind.conf.d directory: %v\n", err)
                os.Exit(1)
        }

        confContent := fmt.Sprintf("[Login]\nInhibitDelayMaxSec=%ds\n", newInhibitDelaySec)
        err = os.WriteFile(tempConfFile, []byte(confContent), 0644)
        if err != nil {
                fmt.Printf("Failed to write temporary config file: %v\n", err)
                os.Exit(1)
        }
        defer os.Remove(tempConfFile)

        obj0 := conn.Object("org.freedesktop.systemd1", dbus.ObjectPath("/org/freedesktop/systemd1"))
        obj1 := conn.Object(logindService, logindObject)

        call := obj0.Call("org.freedesktop.systemd1.Manager.KillUnit", 0, "systemd-logind.service", "all", 1)
        if call.Err != nil {
                fmt.Printf("Reload call failed: %v\n", call.Err)
                os.Exit(1)
        }
        variant, err := obj1.GetProperty("org.freedesktop.login1.Manager.InhibitDelayMaxUSec")
        if err != nil {
                fmt.Printf("Failed to get property: %v\n", err)
                os.Exit(1)
        }

        updatedInhibitDelayUSec, ok := variant.Value().(uint64)
        if !ok {
                fmt.Println("Failed to assert property type to uint64.")
                os.Exit(1)
        }

        expectedUSec := uint64(newInhibitDelaySec * 1_000_000)

        return expectedUSec != updatedInhibitDelayUSec
}
```

, which had pretty low reproduction rate (`Tested 80500 times, reproduced the bug 1 times/Tested 257500 times, reproduced the bug 4 times`) but on real cases, it should significantly higher because the kubelet is started during OS boot period and a lot of churns on systemd so the logind reload takes more time to take effect. 

### Anything else we need to know?

_No response_

### Kubernetes version

<details>
1.33 and earlier
```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by linxiulei**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR is related to:

Fixes #133133

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go [hunk 1]
```diff
@@ -191,15 +192,30 @@ func (m *managerImpl) start() (chan struct{}, error) {
...
+			}
+			return periodRequested <= updatedInhibitDelay, nil
+		})
 		if err != nil {
-			return nil, err
+			if !wait.Interrupted(err) {
+				return nil, err
+			}
+			if periodRequested > updatedInhibitDelay {
+				return nil, fmt.Errorf("node shutdown manager was unable to update logind InhibitDelayMaxSec to %v (ShutdownGracePeriod), current value of InhibitDelayMaxSec (%v) is less than requested ShutdownGracePeriod", periodRequested, updatedInhibitDelay)
```
Comment (ajaysundark) [inline pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go]: Could the final error message be more descriptive and mention retries attempted?

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go [hunk 2]
```diff
@@ -191,15 +192,30 @@ func (m *managerImpl) start() (chan struct{}, error) {
...
-		updatedInhibitDelay, err := m.dbusCon.CurrentInhibitDelay()
+		// The ReloadLogindConf() call is asynchronous so it might take a short period before logind finishes reloading its configuration.
+		backoff := wait.Backoff{
+			Duration: 100 * time.Millisecond,
+			Factor:   2.0,
+			Steps:    5,
+		}
+		var updatedInhibitDelay time.Duration
+		err = wait.ExponentialBackoff(backoff, func() (bool, error) {
+			// Read the current inhibitDelay again, if the override was successful, currentInhibitDelay will be equal to shutdownGracePeriodRequested.
```
Comment (ajaysundark) [inline pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:205]: Would it be valuable to log a warning before starting the backoff loop? This would make it easier to debug a delay in kubelet startup.

**Review by ajaysundark — COMMENTED** [review]
@linxiulei Thanks for your PR! 

Sadly we dont have metrics to capture failures or status of auxiliary managers like this in kubelet. Is it worth adding an error metric like `kubelet_shutdown_manager_failed_to_start` to ensure we dont fail silently?

cc @ndixita @dchen1107

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go (hunk 1 above)
Comment (linxiulei) [reply pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go]: Done

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go (hunk 2 above)
Comment (linxiulei) [reply pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:205]: Done

**Comment by linxiulei** [comment]
> Sadly we dont have metrics to capture failures or status of auxiliary managers like this in kubelet. Is it worth adding an error metric like `kubelet_shutdown_manager_failed_to_start` to ensure we dont fail silently?

It might be over-engineering to have a metric for one off failure? I found this bug with error log 

`kubelet.go:1667] "Failed to start node shutdown manager" err="node shutdown manager was unable to update logind InhibitDelayMaxSec to 30s (ShutdownGracePeriod), current value of InhibitDelayMaxSec (5s) is less than requested ShutdownGracePeriod"` 

which was pretty evident to me. WDYT?

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go [hunk 3]
```diff
@@ -191,15 +192,38 @@ func (m *managerImpl) start() (chan struct{}, error) {
...
+			}
+			return false, nil
+		})
 		if err != nil {
-			return nil, err
+			if !wait.Interrupted(err) {
+				return nil, err
+			}
+			if periodRequested > updatedInhibitDelay {
+				return nil, fmt.Errorf("node shutdown manager was timed out after %d attempts waiting for logind InhibitDelayMaxSec to update to %v, current value is %v", attempt, periodRequested, updatedInhibitDelay)
```
Comment (ajaysundark) [inline pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go]:
```suggestion
				return nil, fmt.Errorf("node shutdown manager was timed out after %d attempts waiting for logind InhibitDelayMaxSec to update to %v (ShutdownGracePeriod), current value is %v", attempt, periodRequested, updatedInhibitDelay)
```

**Comment by ajaysundark** [comment]
> @linxiulei: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> 
> Test name	Commit	Details	Required	Rerun command
> pull-kubernetes-unit-windows-master	[dc0203a](https://github.com/kubernetes/kubernetes/commit/dc0203a3d5590cee1d87e31381ce679dd6ee1059)	[link](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/133138/pull-kubernetes-unit-windows-master/1948160381075591168)	false	`/test pull-kubernetes-unit-windows-master`
> pull-kubernetes-unit	[3b074f8](https://github.com/kubernetes/kubernetes/commit/3b074f80c0af3e020aad1217f7640e3f2e9e8edd)	[link](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/133138/pull-kubernetes-unit/1948246887173722112)	true	`/test pull-kubernetes-unit`
> pull-kubernetes-node-e2e-containerd	[3b074f8](https://github.com/kubernetes/kubernetes/commit/3b074f80c0af3e020aad1217f7640e3f2e9e8edd)	[link](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/133138/pull-kubernetes-node-e2e-containerd/1948246887240830976)	true	`/test pull-kubernetes-node-e2e-containerd`
> [Full PR test history](https://prow.k8s.io/pr-history?org=kubernetes&repo=kubernetes&pr=133138). [Your PR dashboard](https://prow.k8s.io/pr?query=is%3Apr%20state%3Aopen%20author%3Alinxiulei). Please help us cut down on flakes by [linking to](https://git.k8s.io/community/contributors/devel/sig-testing/flaky-tests.md#filing-issues-for-flaky-tests) an [open issue](https://github.com/kubernetes/kubernetes/issues?q=is:issue+is:open) when you hit one in your PR.

Could you also handle these unit tests for your changes?

**Comment by linxiulei** [comment]
Windows unit test failure may be due to https://github.com/kubernetes/kubernetes/issues/133148, which had been fixed hours ago so the failure should be gone soon

**Comment by linxiulei** [comment]
@ajaysundark pull-kubernetes-unit-windows-master is flaky according to https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/pr-logs/directory/pull-kubernetes-unit-windows-master and not required for merge, so do you think we can skip it at the moment?

**Comment by ajaysundark** [comment]
/skip pull-kubernetes-unit-windows-master

Skipping this test because it is a known flake unrelated to the changes. See issue https://github.com/kubernetes/kubernetes/issues/133223.

**Comment by BenTheElder** [comment]
https://go.k8s.io/triage is a better way to assess flakiness, just looking at a presubmit jobs' pass/fail it may fail a lot because of the PRs being tested.

We can see that the CI equivilant isn't failing terribly often until recently:
https://storage.googleapis.com/k8s-triage/index.html?pr=1&job=ci-kubernetes-unit-windows

And similarly the vast majority of the failures are recent here:
https://storage.googleapis.com/k8s-triage/index.html?pr=1&job=pull-kubernetes-unit-windows-master

We should file bugs for those.

You don't actually have to `/skip` jobs that are not marked `Required`, this PR is not merging because it was after code freeze and has not had the milestone applied. It probably qualifies as a critical bufix though.

**Comment by linxiulei** [comment]
> this PR is not merging because it was after code freeze and has not had the milestone applied. It probably qualifies as a critical bufix though.

@BenTheElder thanks for your insights. Can you also please advise what process needed to make it mergeable for 1.34?

**Comment by BenTheElder** [comment]
I'd bring it to #release-management (edit: at https://slack.k8s.io) to discuss adding the milestone.

Technically SIG TLs have access to do this, but it's not used lightly (only critical bug fixes, test fixes that fix release-blocking issues are allowed after code freeze https://k8s.dev/release -- https://github.com/kubernetes/sig-release/blob/master/releases/release_phases.md#code-freeze) and I don't have enough context yet on this one.

cc @Vyom-Yadav 

Asked some questions on https://github.com/kubernetes/kubernetes/issues/133133

**Comment by dchen1107** [comment]
> I'd bring it to #release-management (edit: at https://slack.k8s.io) to discuss adding the milestone.
> 
> Technically SIG TLs have access to do this, but it's not used lightly (only critical bug fixes, test fixes that fix release-blocking issues are allowed after code freeze https://k8s.dev/release -- https://github.com/kubernetes/sig-release/blob/master/releases/release_phases.md#code-freeze) and I don't have enough context yet on this one.

I try not to abuse the system here, and ensure the release team has a consistent state. ;-)

> 
> cc @Vyom-Yadav
> 
> Asked some questions on #133133

**Comment by linxiulei** [comment]
@mrunalp @haircommander @SergeyKanzhelev , @Vyom-Yadav and I are looking for your approval before getting this merged for 1.34 besides @dchen1107 's approval. So can you please have a look on this?

**Comment by haircommander** [comment]
I go back and forth on this. Techincally speaking, I don't think this is critical enough to block the 1.34 release. but I do think sporadically not starting the node shutdown manager is bad, and the code fix is small. if it wasn't right after freeze, I'd say we merge in 1.35 and attempt to backport to 1.34. Maybe we wait on this until 1.34.0 comes out, but backport for 1.34.1 release? I would call it high priority but not critical.

File: pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go [hunk 4]
```diff
@@ -191,15 +192,38 @@ func (m *managerImpl) start() (chan struct{}, error) {
...
+			// Read the current inhibitDelay again, if the override was successful, currentInhibitDelay will be equal to shutdownGracePeriodRequested.
+			updatedInhibitDelay, err = m.dbusCon.CurrentInhibitDelay()
+			if err != nil {
+				return false, err
+			}
+			if periodRequested <= updatedInhibitDelay {
+				return true, nil
+			}
+			if attempt < backoff.Steps {
+				m.logger.V(2).Info("InhibitDelayMaxSec still less than requested, retrying", "attempt", attempt, "current", updatedInhibitDelay, "requested", periodRequested)
```
Comment (haircommander) [inline pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go]: V(2) seems a bit high to me. maybe 3 or 4?

**Comment by linxiulei** [comment]
@haircommander can you pls review? Thanks!
