### PR TITLE
Wait for terminating pods to be deleted

### LINKED ISSUE #71541: Flake: [sig-scheduling] SchedulerPredicates [Serial] validates MaxPods limit number of pods that are allowed to run [Slow]
**Which jobs are failing**: soak-gce-gci-1.13, others

**Which test(s) are failing**: [sig-scheduling] SchedulerPredicates [Serial] validates MaxPods limit number of pods that are allowed to run [Slow]

**Since when has it been failing**:

Rougly forever.  #63768 shows how this test was flaking back during the 1.11 cycle.  There's been no sudden increase in frequency, but a test that flakes roughly 1.5 times per hour needs looking into, and probably tweaking.

**Testgrid link**:

https://k8s-testgrid.appspot.com/sig-release-1.13-all#soak-gci-gce-1.13
https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-soak-gci-gce-beta/500

**Reason for failure**:

Most of the time, these flakes are timeouts.  However, sometimes they have other causes; see Triage link: https://storage.googleapis.com/k8s-gubernator/triage/index.html?date=2018-10-15&test=validates%20MaxPods%20limit%20number%20of%20pods%20that%20are%20allowed%20to%20run

**Anything else we need to know**:

This is part of a general effort to clean up our CI signal by eliminating longstanding, frequent flakes.

/kind flake
/priority important-longterm
/sig scheduling
attn:
@kubernetes/sig-scheduling-bugs 
@k82cn

### PR DESCRIPTION
**Pull request by alculquicondor**
**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:

Reduce flakiness of Scheduler Predicates E2E tests. The test needs a clean and stable cluster, so we need to wait for pods from previous tests to be deleted.

**Which issue(s) this PR fixes**:

Fixes #71541

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: test/e2e/scheduling/framework.go [hunk 1]
```diff
@@ -51,22 +54,57 @@ func WaitForStableCluster(c clientset.Interface, masterNodes sets.String) int {
...
 		}
 	}
 	pods.Items = filteredPods
 	return e2epod.GetPodsScheduled(masterNodes, pods)
 }
+
+// getDeletingPods returns whether there are any pods marked for deletion.
+func getDeletingPods(c clientset.Interface, ns string) []v1.Pod {
+	pods, err := c.CoreV1().Pods(ns).List(metav1.ListOptions{})
+	framework.ExpectNoError(err, "listing all pods in kube-system namespace while waiting for pods to terminate")
```
Comment (ahg-g) [inline test/e2e/scheduling/framework.go]: in all namespaces, not just kube-system

File: test/e2e/scheduling/framework.go [hunk 2]
```diff
@@ -51,22 +54,57 @@ func WaitForStableCluster(c clientset.Interface, masterNodes sets.String) int {
...
+		}
+		time.Sleep(wait)
+		deleting = getDeletingPods(c, metav1.NamespaceAll)
+	}
+}
+
+// getScheduledAndUnscheduledPods lists scheduled and not scheduled pods in the given namespace, with succeeded and failed pods filtered out.
+func getScheduledAndUnscheduledPods(c clientset.Interface, masterNodes sets.String, ns string) (scheduledPods, notScheduledPods []v1.Pod) {
 	pods, err := c.CoreV1().Pods(ns).List(metav1.ListOptions{})
 	framework.ExpectNoError(err, "listing all pods in kube-system namespace while waiting for stable cluster")
```
Comment (ahg-g) [inline test/e2e/scheduling/framework.go]: update this as well, listing pods in the given namespace.

File: test/e2e/scheduling/framework.go [hunk 3]
```diff
@@ -51,22 +54,57 @@ func WaitForStableCluster(c clientset.Interface, masterNodes sets.String) int {
...
 	return e2epod.GetPodsScheduled(masterNodes, pods)
 }
+
+// getDeletingPods returns whether there are any pods marked for deletion.
+func getDeletingPods(c clientset.Interface, ns string) []v1.Pod {
+	pods, err := c.CoreV1().Pods(ns).List(metav1.ListOptions{})
+	framework.ExpectNoError(err, "listing all pods in kube-system namespace while waiting for pods to terminate")
+	var deleting []v1.Pod
+	for _, p := range pods.Items {
+		if p.ObjectMeta.DeletionTimestamp != nil && !podTerminated(p) {
```
Comment (ahg-g) [inline test/e2e/scheduling/framework.go]: just to double check my understanding, we could remove the ```&& !podTerminted``` condition and we would still be ok, right?

Comment (damemi) [reply test/e2e/scheduling/framework.go]: could a pod have a deletiontimestamp set and not yet be in the succeeded/failed state? In that case it would still affect the pod counts

Comment (alculquicondor) [reply test/e2e/scheduling/framework.go]: I'm not entirely sure. I imagine different controllers (kubelet or apiserver) might update the fields or remove the pods at different times.

File: test/e2e/scheduling/framework.go (hunk 1 above)
Comment (alculquicondor) [reply test/e2e/scheduling/framework.go]: Done

File: test/e2e/scheduling/framework.go (hunk 2 above)
Comment (alculquicondor) [reply test/e2e/scheduling/framework.go]: Done
