### PR TITLE
Don't fail teardown if we can't delete the network

### LINKED ISSUE #34747: gke kube-down error blows up whole test run :'(
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke/17639 shows us trying to kube-down at the start and then blowing up when the cluster is not there.  No bueno.

```
All components are up to date.
... in gke:kube-down()
... in gke:detect-project()
ERROR: (gcloud.container.clusters.delete) Some requests did not succeed:
 - args: ['ResponseError: code=404, message=The resource "projects/k8s-jkns-e2e-gke-ci/zones/us-central1-f/clusters/jenkins-e2e" was not found.\nNo cluster named \'jenkins-e2e\' in k8s-jkns-e2e-gke-ci.']
   exit_code: 1
   message: ResponseError: code=404, message=The resource "projects/k8s-jkns-e2e-gke-ci/zones/us-central1-f/clusters/jenkins-e2e" was not found.
No cluster named 'jenkins-e2e' in k8s-jkns-e2e-gke-ci.
```

### PR DESCRIPTION
**Pull request by ixdy**
Fixes #34747.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34750)

### CODE REVIEW

File: cluster/gce/util.sh [hunk 1]
```diff
@@ -1362,7 +1362,7 @@ function kube-down() {
     "${NETWORK}-default-ssh" \
     "${NETWORK}-default-internal"  # Pre-1.5 clusters
   if [[ "${KUBE_DELETE_NETWORK}" == "true" ]]; then
-    delete-network
+    delete-network || true  # might fail if there are leaked firewall rules
```
Comment (ixdy) [inline cluster/gce/util.sh]: `delete-network` already does that.

**Comment by spxtr** [comment]
LGTM, may need manual merge

File: cluster/gce/util.sh (hunk 1 above)
Comment (ixdy) [inline cluster/gce/util.sh]: I should probably update the comment, since leaked VMs, routes, and other things will also prevent network deletion.

Basically, with the `gcloud` API it'll only delete the network if there are no resources in it. In the cloud console (web) it'll first delete anything in the network.

Comment (ixdy) [inline cluster/gce/util.sh]: @krzyzacy is working on a janitor to clean up leaked resources, so I'm not super worried about this.
