### PR TITLE
Check iscsi iface file for transport name

### LINKED ISSUE #27131: open-iscsi software iscsi initiator broken for non-default interfaces
open-iscsi software initiators are currently broken for non-`default` interfaces due to the fact that
the devicePath (in iscsi_util.go) is assumed to use the `/dev/disk/by-path/pci` prefixing scheme
for all interfaces not named `default`.  This causes waitForPathToExist to timeout after 10 seconds
since the device path that it is waiting for is not the `/dev/disk/by-path/ip`- prefixed path that is
created, resulting in host logging such as:

```
Jun 09 04:35:12 kube-node1 kubelet[1427]: E0609 04:35:12.736129    1427 kubelet.go:1780] Unable to mount volumes for pod "monitoring-influxdb-grafana-v3-cyict_kube-system(8749dff7-2dfb-11e6-a330-00163e0a0a01)": Could not attach disk: Timeout after 10s; skipping pod
```
or K8S event logs such as:

```
2016-06-08 21:25:27 -0700 PDT   2016-06-08 21:26:36 -0700 PDT   4         monitoring-influxdb-grafana-v3-hm0t5     Pod                                                       Warning   FailedMount         {kubelet 192.168.10.11}     Unable to mount volumes for pod "monitoring-influxdb-grafana-v3-hm0t5_kube-system(2a81fc54-2dfa-11e6-a330-00163e0a0a01)": Could not attach disk: Timeout after 10s
2016-06-08 21:25:27 -0700 PDT   2016-06-08 21:26:36 -0700 PDT   4         monitoring-influxdb-grafana-v3-hm0t5     Pod                                                       Warning   FailedSync          {kubelet 192.168.10.11}     Error syncing pod, skipping: Could not attach disk: Timeout after 10s
```

open-iscsi support for hardware transports was added in the following commit:

https://github.com/kubernetes/kubernetes/commit/6e46fa1fd4c6222993e4fb7d64fd694fdebb6f9c

In this commit, software iSCSI support was assumed to be done through only the use of the default
interface.  According to the documentation at https://github.com/open-iscsi/open-iscsi (Section 5.1.1)
both software and offload/hardware interfaces are intended to be configured using named interface
specifications and `default` is only a backwards-compatibility vehicle.  Configuration of `default`
cannot be done via the use of `/etc/iscsi/ifaces/default` as this approach is specifically forbidden in
the documentation:

```
Warning: Do not name a iface config file  "default" or "iser".
They are special value/file that is used by the iscsi tools for
backward compatibility. If you name a iface default or iser, then
the behavior is not defined.
```

Leaving this here to help others associate various failure modes with this issue and possible resolution:

In my case I am just learning and this is my first iSCSI deployment.  My initial error was that I was
receiving an `Invalid Initiatorname` message at discovery-time even though I had used
`/etc/iscsi/initiatorname.iscsi` to define a name.  This approach failed because I didn't realize that
iscsid needed to be bounced before it would pick up changes to that file.  I had defined a
custom `/etc/iscsi/ifaces/iface` specification and was using that to accomplish the task of setting
my initiator name.  I was able to unwind this mess and return to the use of `default` once I read
the code and understood what it was attempting to do.

### PR DESCRIPTION
**Pull request by anish**
When checking for tcp vs hardware transports, check actual iscsi iface file to see if we are using tcp as a transport, rather than relying on just the transport name of 'default'.

This fixes the open-iscsi software iscsi initiator for non-default interfaces.
fixes #27131

### CODE REVIEW

**Comment by anish** [comment]
@rootfs @mcumings

File: pkg/volume/iscsi/iscsi_util.go [hunk 1]
```diff
@@ -99,12 +100,22 @@ func (util *ISCSIUtil) MakeGlobalPDName(iscsi iscsiDisk) string {
 
 func (util *ISCSIUtil) AttachDisk(b iscsiDiskMounter) error {
 	var devicePath string
-	if b.iface == "default" {
+	var iscsiTransport string
+
+	out, err := b.plugin.execCommand("iscsiadm", []string{"-m", "iface", "-I", b.iface, "-o", "show"})
+	if err != nil {
+		glog.Errorf("iscsi: could not read iface %s error: %s", b.iface, string(out))
+		return err
```
Comment (rootfs) [inline pkg/volume/iscsi/iscsi_util.go]: add the above log info to `err` so we know where the problem comes from in kubectl output.

File: pkg/volume/iscsi/iscsi_util.go [hunk 2]
```diff
@@ -184,6 +195,17 @@ func (util *ISCSIUtil) DetachDisk(c iscsiDiskUnmounter, mntPath string) error {
 	return nil
 }
 
+func extractTransportname(ifaceOutput string) (iscsiTransport string) {
+	re := regexp.MustCompile(`iface.transport_name = (.*)\n`)
+	iscsiTransport = re.FindStringSubmatch(ifaceOutput)[1]
```
Comment (rootfs) [inline pkg/volume/iscsi/iscsi_util.go]: check for nil

File: pkg/volume/iscsi/iscsi_util_test.go [hunk 3]
```diff
@@ -86,11 +86,42 @@ func fakeFilepathGlob(devicePath string) (globs []string, err error) {
...
+		"# BEGIN RECORD 2.0-873\n" +
+			"iface.iscsi_ifacename = default\n" +
+			"iface.transport_name = cxgb4i\n" +
+			"iface.initiatorname = <empty>\n" +
+			"# END RECORD",
+		"# BEGIN RECORD 2.0-873\n" +
+			"iface.iscsi_ifacename = default\n" +
+			"iface.transport_name = <empty>\n" +
+			"iface.initiatorname = <empty>\n" +
+			"# END RECORD"}
```
Comment (rootfs) [inline pkg/volume/iscsi/iscsi_util_test.go]: and add a test without `iface.transport_name` in it

File: pkg/volume/iscsi/iscsi_util.go (hunk 2 above)
Comment (anish) [inline pkg/volume/iscsi/iscsi_util.go]: I left that out on purpose. As long as `iscsiadm` runs successfully, it will add a line for iface.transport_name on it's own even if none is specified. It is pretty much impossible for the regex to fail.

File: pkg/volume/iscsi/iscsi_util_test.go (hunk 3 above)
Comment (anish) [inline pkg/volume/iscsi/iscsi_util_test.go]: Left it out on purpose, based on the same reasoning as above

File: pkg/volume/iscsi/iscsi_util.go (hunk 1 above)
Comment (anish) [inline pkg/volume/iscsi/iscsi_util.go]: Will do

Comment (anish) [inline pkg/volume/iscsi/iscsi_util.go]: @rootfs kinda confused how to do this. The rest of the function just prints out with glog.Errorf and returns just the error

Comment (rootfs) [inline pkg/volume/iscsi/iscsi_util.go]: ok, let's make a separate PR to reformat these err

File: pkg/volume/iscsi/iscsi_util.go (hunk 2 above)
Comment (rootfs) [inline pkg/volume/iscsi/iscsi_util.go]: in case iscsiadm doesn't produce the output as expected, checking for nil survives a panic.

Comment (anish) [inline pkg/volume/iscsi/iscsi_util.go]: Fair enough, will handle it

**Comment by anish** [comment]
@rootfs updated per discussion

**Comment by rootfs** [comment]
LGTM

@mcumings do you have a chance to check out it?

**Comment by anish** [comment]
@rootfs @thockin can I get someone to kick off the tests please ?

**Comment by childsb** [comment]
@k8s-bot ok to test

**Comment by thockin** [comment]
@rootfs are you LGTM on this for final?

**Comment by rootfs** [comment]
@thockin @childsb yes LGTM, can you tag it?
