### PR TITLE
kube-proxy: fix confusing default value for healthz and metrics bind address, deprecate healthz-port and metrics-port flag

### LINKED ISSUE #88443: Fix confusing default for kube-proxy healthz bind address
**What would you like to be amended**:
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/ lists:

> `--healthz-bind-address` `0.0.0.0`     Default: `0.0.0.0:10256`
>
> The IP address for the health check server to serve on (set to `0.0.0.0` for all IPv4 interfaces and `::` for all IPv6 interfaces)

I'd like the default for that command line option to actually be `0.0.0.0`, so that the documentation looks right. Internally, the behavior (listen on `0.0.0.0:10256` unless `--healthz-bind-address` sets a different bind address) should stay the same even if the implementation is updated.

**Why is this needed**:
This was originally reported as a website defect (and proposed fix): https://github.com/kubernetes/website/pull/19213

/kind cleanup
/sig network
/sig docs
/priority backlog

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind bug
/kind cleanup
/kind deprecation

**What this PR does / why we need it**:
1. fix confusing default value for healthz and metrics bind address (make the flags consistent with the kube-proxy configuration file)
2. deprecate healthz-port and metrics-port flag
3. remove back-quoted strings from flag descriptions, because backquotes can cause the wrong flag type, please check pflag code for detail: https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/spf13/pflag/flag.go#L561-L580

```go
// UnquoteUsage extracts a back-quoted name from the usage
// string for a flag and returns it and the un-quoted usage.
// Given "a `name` to show" it returns ("name", "a name to show").
// If there are no back quotes, the name is an educated guess of the
// type of the flag's value, or the empty string if the flag is boolean.
func UnquoteUsage(flag *Flag) (name string, usage string) {
	// Look for a back-quoted name, but avoid the strings package.
	usage = flag.Usage
	for i := 0; i < len(usage); i++ {
		if usage[i] == '`' {
			for j := i + 1; j < len(usage); j++ {
				if usage[j] == '`' {
					name = usage[i+1 : j]
					usage = usage[:i] + name + usage[j+1:]
					return name, usage
				}
			}
			break // Only one back quote; use type name.
		}
	}
        ......
```

Before (bind-address type is 0.0.0.0, it is wrong):
```
Flags:
      --bind-address 0.0.0.0                         The IP address for the proxy server to serve on (set to 0.0.0.0 for all IPv4 interfaces and `::` for all IPv6 interfaces) (default 0.0.0.0)
      --healthz-bind-address 0.0.0.0                 The IP address for the health check server to serve on (set to 0.0.0.0 for all IPv4 interfaces and `::` for all IPv6 interfaces) (default 0.0.0.0:10256)
      --metrics-bind-address 0.0.0.0                 The IP address for the metrics server to serve on (set to 0.0.0.0 for all IPv4 interfaces and `::` for all IPv6 interfaces) (default 127.0.0.1:10249)
```

After (bind-address type is ip, it is ok):
```
Flags:
      --bind-address ip                              The IP address for the proxy server to serve on (set to '0.0.0.0' for all IPv4 interfaces and '::' for all IPv6 interfaces) (default 0.0.0.0)
      --healthz-bind-address ipport                  The IP address with port for the health check server to serve on (set to '0.0.0.0:10256' for all IPv4 interfaces and '[::]:10256' for all IPv6 interfaces). Set empty to disable. (default 0.0.0.0:10256)
      --metrics-bind-address ipport                  The IP address with port for the metrics server to serve on (set to '0.0.0.0:10249' for all IPv4 interfaces and '[::]:10249' for all IPv6 interfaces). Set empty to disable. (default 127.0.0.1:10249)

```

**Which issue(s) this PR fixes**:

Fixes #88443

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kube-proxy: deprecate `--healthz-port` and `--metrics-port` flag, please use `--healthz-bind-address` and `--metrics-bind-address` instead
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: cmd/kube-proxy/app/server.go [hunk 1]
```diff
@@ -165,16 +165,18 @@ func (o *Options) AddFlags(fs *pflag.FlagSet) {
...
 
-	fs.Var(utilflag.IPVar{Val: &o.config.BindAddress}, "bind-address", "The IP address for the proxy server to serve on (set to `0.0.0.0` for all IPv4 interfaces and `::` for all IPv6 interfaces)")
-	fs.Var(utilflag.IPVar{Val: &o.config.HealthzBindAddress}, "healthz-bind-address", "The IP address for the health check server to serve on (set to `0.0.0.0` for all IPv4 interfaces and `::` for all IPv6 interfaces)")
-	fs.Var(utilflag.IPVar{Val: &o.config.MetricsBindAddress}, "metrics-bind-address", "The IP address for the metrics server to serve on (set to `0.0.0.0` for all IPv4 interfaces and `::` for all IPv6 interfaces)")
+	fs.Var(utilflag.IPVar{Val: &o.config.BindAddress}, "bind-address", "The IP address for the proxy server to serve on (set to '0.0.0.0' for all IPv4 interfaces and '::' for all IPv6 interfaces)")
+	fs.Var(utilflag.IPPortVar{Val: &o.config.HealthzBindAddress}, "healthz-bind-address", "The IP address with port for the health check server to serve on (set to '0.0.0.0:10256' for all IPv4 interfaces and '[::]:10256' for all IPv6 interfaces). Set empty to disable.")
```
Comment (aojea) [inline cmd/kube-proxy/app/server.go]: Interestingly, IPPortVar is compatible with IP only so it's backward compatible, nice
> // Both IP and IP:port are valid.

File: cmd/kube-proxy/app/server.go [hunk 2]
```diff
@@ -165,16 +165,18 @@ func (o *Options) AddFlags(fs *pflag.FlagSet) {
 	fs.BoolVar(&o.CleanupIPVS, "cleanup-ipvs", o.CleanupIPVS, "If true and --cleanup is specified, kube-proxy will also flush IPVS rules, in addition to normal cleanup.")
 	fs.MarkDeprecated("cleanup-ipvs", "In a future release, running --cleanup will always flush IPVS rules")
 
-	fs.Var(utilflag.IPVar{Val: &o.config.BindAddress}, "bind-address", "The IP address for the proxy server to serve on (set to `0.0.0.0` for all IPv4 interfaces and `::` for all IPv6 interfaces)")
-	fs.Var(utilflag.IPVar{Val: &o.config.HealthzBindAddress}, "healthz-bind-address", "The IP address for the health check server to serve on (set to `0.0.0.0` for all IPv4 interfaces and `::` for all IPv6 interfaces)")
-	fs.Var(utilflag.IPVar{Val: &o.config.MetricsBindAddress}, "metrics-bind-address", "The IP address for the metrics server to serve on (set to `0.0.0.0` for all IPv4 interfaces and `::` for all IPv6 interfaces)")
+	fs.Var(utilflag.IPVar{Val: &o.config.BindAddress}, "bind-address", "The IP address for the proxy server to serve on (set to '0.0.0.0' for all IPv4 interfaces and '::' for all IPv6 interfaces)")
```
Comment (aojea) [inline cmd/kube-proxy/app/server.go]: The 

> set to '0.0.0.0' for all IPv4 interfaces and '::' for all IPv6 interfaces

is wrong https://github.com/kubernetes/kubernetes/issues/88458

but can be done in a followup

Comment (SataQiu) [reply cmd/kube-proxy/app/server.go]: Yeah, I think we need to work it out separately. That is a different problem!

File: cmd/kube-proxy/app/server.go (hunk 1 above)
Comment (thockin) [reply cmd/kube-proxy/app/server.go]: does `:port` work for "all interfaces" ?

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve
