### PR TITLE
Fix goroutine leaks in package `selectorspread`

### LINKED ISSUE #107360: goroutine leaks in TestSelectorSpreadScore
### What happened?

The ctx object ([line 399](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/selectorspread/selector_spread_test.go#L399)) is context.Background(). Thus, its Done() method returns a nil channel. Later, the nil channel is used to call `wait.BackoffUntil()` and `Reflector.ListAndWatch()` as their `stopCh` argument. The goroutines created in the two functions are leaked.  

### What did you expect to happen?

No goroutine leaks in TestSelectorSpreadScore().

### How can we reproduce it (as minimally and precisely as possible)?

Run TestSelectorSpreadScore()

### Anything else we need to know?

_No response_

### Kubernetes version

all versions after 97d40890d00acf721ecabb8c9a6fec3b3234b74b

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by mengjiao-liu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix goroutine leaks in TestSelectorSpreadScore.

In the for loop, after a test case has ended, the child goroutine should be terminated in time to release resources to avoid the problem of goroutine leakage.

#### Which issue(s) this PR fixes:

Fixes #107360

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/framework/plugins/selectorspread/selector_spread_test.go [hunk 1]
```diff
@@ -396,7 +396,8 @@ func TestSelectorSpreadScore(t *testing.T) {
 		t.Run(test.name, func(t *testing.T) {
 			nodes := makeNodeList(test.nodes)
 			snapshot := cache.NewSnapshot(test.pods, nodes)
-			ctx := context.Background()
+			ctx, cancel := context.WithCancel(context.Background())
```
Comment (denkensk) [inline pkg/scheduler/framework/plugins/selectorspread/selector_spread_test.go:399]: Thanks @mengjiao-liu 
Can you help refine other part of this file?
https://github.com/kubernetes/kubernetes/blob/ba82add41a06d1fceeaf01fc71d3d5da910c41d9/pkg/scheduler/framework/plugins/selectorspread/selector_spread_test.go#L656

Comment (mengjiao-liu) [reply pkg/scheduler/framework/plugins/selectorspread/selector_spread_test.go:399]: Okay, I'll check the other tests for this file.

Comment (mengjiao-liu) [reply pkg/scheduler/framework/plugins/selectorspread/selector_spread_test.go:399]: Updated.

Comment (kerthcet) [reply pkg/scheduler/framework/plugins/selectorspread/selector_spread_test.go:399]: Also help to refine other files like [`selector_spread_perf_test.go`](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/selectorspread/selector_spread_perf_test.go#L61) as landed under the same package. thanks.

Comment (mengjiao-liu) [reply pkg/scheduler/framework/plugins/selectorspread/selector_spread_test.go:399]: Updated. Thanks!

**Comment by denkensk** [comment]
/lgtm

Thanks @mengjiao-liu 
ping @Huang-Wei  for approve

**Comment by denkensk** [comment]
@alculquicondor
Could you give approve for this?
Thanks

**Review by alculquicondor — COMMENTED** [review]
Thanks!
/approve

**Comment by Huang-Wei** [comment]
> ping @Huang-Wei for approve

Apologize that it totally slipped in my radar. (ping me on slack next time if I don't respond)

It's a neat PR and thank @songlh for spotting it and @mengjiao-liu for fixing it!

I'm drafting a PR to fix all (_hopefully_) potential goroutine leaks (mostly in UT) in scheduler codebase.
