### PR TITLE
Prevent scheduler crashing in default preemption plugin

### LINKED ISSUE #101548: kube-scheduler crashes and restarts with panics in DefaultPreemption plugin
#### What happened:

Kubernetes 1.19 (confirmed with 1.19.7 and 1.19.10)

kube-scheduler crashes and restarts with the following errors in `default_preemption.go`. 

1. **panic: runtime error: index out of range [0] with length 0** 

The problem code is line 389.  When `victims` is nil or `victims.Pods` is empty, the error happens.  If we skip `GetPodPriority ` when it's nil or empty, the error is gone. 
```
387         victims := nodesToVictims[node]
388         // highestPodPriority is the highest priority among the victims on this node.
389         highestPodPriority := podutil.GetPodPriority(victims.Pods[0])
```

```
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
goroutine 1406 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1c9fde0, 0xc00748cf48)
 /usr/local/Cellar/go/1.16.2/libexec/src/runtime/panic.go:965 +0x1b9
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.pickOneNodeForPreemption(0xc007e3dbc0, 0x4, 0x4)
/Users/yuanchen/projects/aci/go/kubescheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:389 +0xd2c
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.SelectCandidate(0xc0086e0840, 0x4, 0x4, 0xc008235800, 0x2068138)
/Users/yuanchen/projects/aci/go/kubescheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:331 +0x85
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.(*DefaultPreemption).preempt(0xc000ac4b80, 0x20677d0, 0xc005849540, 0xc0085616e0, 0xc008235800, 0xc008561710, 0x2d80750, 0xc00820a8c0, 0x7f0937ef47d8, 0x30)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:135 +0x4bd
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.(*DefaultPreemption).PostFilter(0xc000ac4b80, 0x20677d0, 0xc005849540, 0xc0085616e0, 0xc0071543a8, 0xc008561710, 0x0, 0x0)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:83 +0xf1
k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*frameworkImpl).runPostFilterPlugin(0xc0002fd380, 0x20677d0, 0xc005849540, 0x7f0937a84040, 0xc000ac4b80, 0xc0085616e0, 0xc0071543a8, 0xc008561710, 0xc0084f3ab0, 0x5f5e100)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/runtime/framework.go:557 +0x87
```

2. **panic: runtime error: invalid memory address or nil poster dereference**

` 452   latestStartTime := util.GetEarliestPodStartTime(nodesToVictims[minNodes2[0]])`

The problem is `nodesToVictims[minNodes2[0]]` does not exist and returns nil sometimes. Simply skipping it won't solve the problem.  The scheduler will reach either line 456 or 341. 

```
456        klog.Errorf("earliestStartTime is nil for node %s. Should not reach here.", minNodes2[0])
```

`341     klog.Errorf("None candidate can be picked from %v.", candidates)`

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15706d7]
goroutine 1385 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1b448c0, 0x2d281b0)
/usr/local/Cellar/go/1.16.2/libexec/src/runtime/panic.go:965 +0x1b9
k8s.io/kubernetes/pkg/scheduler/util.GetEarliestPodStartTime(0x0, 0xc004d4d9e0)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/util/utils.go:56 +0x37
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.pickOneNodeForPreemption(0xc004d4d9e0, 0x4, 0x4)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:452+0x7a9
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.SelectCandidate(0xc0066e5180, 0x4, 0x4, 0xc0062f5000, 0x2068138)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:331 +0x85
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.(*DefaultPreemption).preempt(0xc000f9e880, 0x20677d0, 0xc004fa3340, 0xc0061b5290, 0xc0062f5000, 0xc0061b52c0, 0x2d80750, 0xc00603fc40, 0x7f6bcbc363f8, 0x30)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:135 +0x4bd
: k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.(*DefaultPreemption).PostFilter(0xc000f9e880, 0x20677d0, 0xc004fa3340, 0xc0061b5290, 0xc002523ac8, 0xc0061b52c0, 0x0, 0x0)
```

#### What you expected to happen:

The scheduler works without failures.

#### How to reproduce it (as minimally and precisely as possible):

When there are preemptions in a cluster. 

#### Environment:
- Kubernetes version (use `kubectl version`): v1.19.10 or v1.19.7
- Cloud provider or hardware configuration: bare metal 
- OS (e.g: `cat /etc/os-release`): centos 7 
- Kernel (e.g. `uname -a`):   Linux 5.4.77-7.el7pie #1 SMP Sat Nov 21 01:16:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by yuanchen8911**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

`FindCandidates` or `CallExtenders` in `defaultpreemption` plugin can return victim without pods (e.g., because of issues in Filter plugins or extenders). As a result, the scheduler will panic and crash when accessing an non-existing pod. This PR adds additional  checks to prevent it from crashing the scheduler.

#### Which issue(s) this PR fixes:

Fixes #101548 

#### Does this PR introduce a user-facing change?

```
NONE

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 1]
```diff
@@ -555,7 +559,15 @@ func pickOneNodeForPreemption(nodesToVictims map[string]*extenderv1.Victims) str
...
-	latestStartTime := util.GetEarliestPodStartTime(nodesToVictims[minNodes2[0]])
+
+	var (
+		victims         *extenderv1.Victims
+		found           bool
+		latestStartTime *metav1.Time
+	)
+	if victims, found = nodesToVictims[minNodes2[0]]; found {
+		latestStartTime = util.GetEarliestPodStartTime(victims)
+	}
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:570]: This is neater:

```go
var latestStartTime *metav1.Time
if victims, found := nodesToVictims[minNodes2[0]]; found {
	latestStartTime = util.GetEarliestPodStartTime(victims)
}
```

**Review by Huang-Wei — COMMENTED** [review]
As mentioned in https://github.com/kubernetes/kubernetes/issues/101548#issuecomment-828147610, I'd like to understand the root cause, and then come up with all defensive checking at once in this PR.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 1 above)
Comment (yuanchen8911) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: fixed it.

**Comment by yuanchen8911** [comment]
Note that there are test cases that return candidates with empty victims.  It makes the simple change `if fits && len(pods)  ==0` in `dryRunPreemption` fail the tests. 

```
--- FAIL: TestDryRunPreemption (0.11s)
    --- FAIL: TestDryRunPreemption/a_pod_that_fits_with_no_preemption (0.00s)
        default_preemption_test.go:1059: cycle 0: unexpected candidates (-want, +got):   []defaultpreemption.Candidate{
            - 	&defaultpreemption.candidate{victims: &v1.Victims{}, name: "node1"},
            - 	&defaultpreemption.candidate{victims: &v1.Victims{}, name: "node2"},
              }
    --- FAIL: TestDryRunPreemption/a_pod_that_fits_on_one_node_with_no_preemption (0.00s)
        default_preemption_test.go:1059: cycle 0: unexpected candidates (-want, +got):   []defaultpreemption.Candidate{
            - 	&defaultpreemption.candidate{victims: &v1.Victims{}, name: "node1"},
              }
```

**Comment by yuanchen8911** [comment]
@Huang-Wei updated the description and PR. PTAL!

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 2]
```diff
@@ -336,9 +336,13 @@ func dryRunPreemption(ctx context.Context, fh framework.Handle,
...
-			victims := extenderv1.Victims{
-				Pods:             pods,
-				NumPDBViolations: int64(numPDBViolations),
+			var victims extenderv1.Victims
+			// do not create victims without pods
+			if len(pods) != 0 {
+				victims = extenderv1.Victims{
+					Pods:             pods,
+					NumPDBViolations: int64(numPDBViolations),
+				}
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:345]: We should treat `len(pods) == 0` as an internal error, right? Why not just do `if status.IsSuccess() && len(pods) != 0` in L338?

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 3]
```diff
@@ -404,8 +408,14 @@ func CallExtenders(extenders []framework.Extender, pod *v1.Pod, nodeLister frame
 
 	var newCandidates []Candidate
 	for nodeName := range victimsMap {
+		// check if victims.Pods is empty
+		victims := victimsMap[nodeName]
+		if len(victims.Pods) == 0 {
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:413]: I'd prefer to run the check around L391: if an extender returns illegal result and `extender.IsIgnorable() == false`, return it as an error.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 2 above)
Comment (yuanchen8911) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:345]: That's my original version but the unit test failed as there are test cases that return empty victims with fit= true. Please see my comment. https://github.com/kubernetes/kubernetes/pull/101560#issuecomment-830683854

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 3 above)
Comment (yuanchen8911) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:413]: > I'd prefer to run the check around L391: if an extender returns illegal result and `extender.IsIgnorable() == false`, return it as an error.

Check the validness of `nodeNameToVictims `returned by `PrecessPreemption`  before L399?
```
for nodeName := range nodeNameToVictims {
	// check if victims.Pods is empty
 		victims := victimsMap[nodeName]
 		if len(victims.Pods) == 0 {
 		    delete(victims, nodeName)
 		 }
}  
```

Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:413]: before L399, like this:

```go
		for nodeName, victims := range nodeNameToVictims {
			if victims != nil && len(victims.Pods) != 0 {
				continue
			}
			if extender.IsIgnorable() {
				delete(nodeNameToVictims, nodeName)
				// klog....
				continue
			} else {
				return nil, framework.AsStatus(/* build an internal err */)
			}
		}
```

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 2 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:345]: yes, please update those tests.

Comment (yuanchen8911) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:345]: should  ` status.IsSuccess() && len(pods) == 0`  be considered an error or just ignored?

Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:345]: let's craft it as an internal error.

**Comment by yuanchen8911** [comment]
Updated the PR as suggested, please review it.  @Huang-Wei  Thanks!

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 4]
```diff
@@ -352,11 +352,14 @@ func dryRunPreemption(ctx context.Context, fh framework.Handle,
...
 				cancel()
 			}
-		} else {
-			statusesLock.Lock()
-			nodeStatuses[nodeInfoCopy.Node().Name] = status
-			statusesLock.Unlock()
+			return
+		}
+		if status.IsSuccess() && len(pods) == 0 {
+			status = framework.NewStatus(framework.Unschedulable, fmt.Sprintf("invalid victims on node %q returned by selectVictimsOnNode", nodeInfoCopy.Node().Name))
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:358]:
```suggestion
			status = framework.AsStatus(fmt.Errorf("invalid victims on node %q returned by selectVictimsOnNode", nodeInfoCopy.Node().Name))
```

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 5]
```diff
@@ -391,6 +394,18 @@ func CallExtenders(extenders []framework.Extender, pod *v1.Pod, nodeLister frame
 			}
 			return nil, framework.AsStatus(err)
 		}
+		// Check if the returned victims are valid.
+		for nodeName, victims := range nodeNameToVictims {
+			if victims != nil && len(victims.Pods) == 0 {
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:399]: Perfer `if victims == nil || len(victims.Pods) == 0` so that we can catch nil victims.

**Review by Huang-Wei — COMMENTED** [review]
Some nits. LGTM otherwise.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go [hunk 6]
```diff
@@ -1263,6 +1256,9 @@ func TestSelectBestCandidate(t *testing.T) {
 			offset, numCandidates := pl.getOffsetAndNumCandidates(int32(len(nodeInfos)))
 			candidates, _ := dryRunPreemption(context.Background(), fwk, state, tt.pod, nodeInfos, nil, offset, numCandidates)
 			s := SelectCandidate(candidates)
+			if s == nil || len(s.Name()) == 0 {
+				return
+			}
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:1261]: You can remove the first sub-test "No node needs preemption".

**Comment by yuanchen8911** [comment]
@ahg-g could you review it when you get a chance? Thanks.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go (hunk 6 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:1261]: Bump.

Comment (yuanchen8911) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:1251]: deleted the test case.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 7]
```diff
@@ -352,11 +352,14 @@ func dryRunPreemption(ctx context.Context, fh framework.Handle,
...
 				cancel()
 			}
-		} else {
-			statusesLock.Lock()
-			nodeStatuses[nodeInfoCopy.Node().Name] = status
-			statusesLock.Unlock()
+			return
+		}
+		if status.IsSuccess() && len(pods) == 0 {
+			status = framework.AsStatus(fmt.Errorf("invalid victims on node %q returned by selectVictimsOnNode", nodeInfoCopy.Node().Name))
```
Comment (xujyan) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:358]: Should the error msg be more explicit: should not happen: the pod fits with no victim pods? Same below.

Comment (yuanchen8911) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:358]: Does the error status (set in L358) indicate "it should not happen"?

**Comment by Huang-Wei** [comment]
/approve
leaving /lgtm to @ahg-g

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 7 above)
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:358]: right, be more explicit, like "expected at least one victim on node $q"

Comment (yuanchen8911) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Updated the error msg. as suggested.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 8]
```diff
@@ -391,6 +394,18 @@ func CallExtenders(extenders []framework.Extender, pod *v1.Pod, nodeLister frame
 			}
 			return nil, framework.AsStatus(err)
 		}
+		// Check if the returned victims are valid.
+		for nodeName, victims := range nodeNameToVictims {
+			if victims == nil || len(victims.Pods) == 0 {
+				if extender.IsIgnorable() {
+					delete(nodeNameToVictims, nodeName)
+					klog.Warningf("Ignoring victims without pods on node %q returned by extender", nodeName)
```
[the remark this answers is not in the document]
Comment (yuanchen8911) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: > warnings aren't recommended anymore, either error or info. In this case info probably fits better.

Changed it to `InfoS`.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 7 above)
Comment (yuanchen8911) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: > right, be more explicit, like "expected at least one victim on node $q"

Updated the error msg. as suggested.
