### PR TITLE
Fix cross-build

### LINKED ISSUE #52074: Cross build broken
After merging the following:

#51728
#51557

cross build broke.

### PR DESCRIPTION
**Pull request by derekwaynecarr**
**What this PR does / why we need it**:
The cross-build was broken by the following PRs:

https://github.com/kubernetes/kubernetes/pull/51728
https://github.com/kubernetes/kubernetes/pull/51557

This PR fixes the cross-build rather than revert them.

Fixes https://github.com/kubernetes/kubernetes/issues/52074

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
@liggitt -- lets rally around this pr to see where the problem was.

/assign @liggitt

**Comment by liggitt** [comment]
@cblecker, I'm surprised the cross-build bot didn't auto-test #51728... it changed platform-specific files. Did that get turned off?

File: pkg/kubelet/cadvisor/cadvisor_windows.go [hunk 1]
```diff
@@ -77,3 +77,7 @@ func (cu *cadvisorClient) WatchEvents(request *events.Request) (*events.EventCha
 func (cu *cadvisorClient) HasDedicatedImageFs() (bool, error) {
 	return false, nil
 }
+
+func (c *cadvisorUnsupported) GetFsInfoByFsUUID(uuid string) (cadvisorapiv2.FsInfo, error) {
```
Comment (liggitt) [inline pkg/kubelet/cadvisor/cadvisor_windows.go]: Should be cadvisorClient

**Comment by liggitt** [comment]
helpers_unsupported.go:26: undefined: unsupportedErr

**Comment by dims** [comment]
looks like a couple of more things need to be fixed 
```
I0907 05:19:35.388] 	*cadvisorClient does not implement Interface (missing GetFsInfoByFsUUID method)
I0907 05:19:35.388] pkg/kubelet/cadvisor/cadvisor_windows.go:81: undefined: cadvisorUnsupported
I0907 05:19:35.388] pkg/kubelet/cadvisor/helpers_unsupported.go:26: undefined: unsupportedErr
```

**Comment by derekwaynecarr** [comment]
Will fix up.

**Comment by liggitt** [comment]
builds and runs on darwin, will see if cross build is happy
/lgtm

**Comment by liggitt** [comment]
cross build passed, unit test failure is unrelated 
/retest

**Comment by WanLinghao** [comment]
@derekwaynecarr  I am confused that why function `NewImageFsInfoProvider()`  has two definitions in 
same package `cadvisor`.
Is that on purpose or just a mistake?
