### PR TITLE
Ignore EIO error in unmount path

### LINKED ISSUE #66868: Kubelet cannot unmount unreachable network volumes using XFS
/kind bug

**What happened**:
Kubelet failed to unmount volumes if the backend ISCSI volume is not available. This also applies to other network attached volumes.

**What you expected to happen**:
Kubelet should be able to unmount the volumes. A manual unmount works even when the backend network volume is not available.
**How to reproduce it (as minimally and precisely as possible)**:
Mount an ISCSI/network volume and disconnect/de-provision ISCSI target.

**Anything else we need to know?**:
XFS shuts down the filesystem due to I/O errors. Kubelet uses "stat" calls to figure out if it is a valid mount point or it is already unmounted. Stat calls fail with EIO and Kubelet never proceeds to unmount the volume.

**Environment**:
- Kubernetes version (use `kubectl version`):
Kubernetes 1.10.5
- Cloud provider or hardware configuration:
Bare metal
- OS (e.g. from /etc/os-release):
Centos 7.4
- Kernel (e.g. `uname -a`):
Linux appserv37 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
Manual bring up
- Others:

### PR DESCRIPTION
**Pull request by chakri-nelluri**
**What this PR does / why we need it**:
This PR ignores EIO in unmount path. XFS shuts down filesystem when the target is down and it returns EIO for the stat calls used in unmount path.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #66868

**Special notes for your reviewer**:
We already handle ESTALE & ENOTCONN errors in isCorruptedMnt Call. Adding EIO to that list covers the XFS shutdown case.

Also Flexvolume doesn't check for these errors in its current form. Updated Flexvolume code to handle it.

```release-note
Fix an issue where filesystems are not unmounted when a backend is not reachable and returns EIO.
```

### CODE REVIEW

**Comment by chakri-nelluri** [comment]
@msau42 @saad-ali @verult @linyouchong PTAL when you get a chance.

File: pkg/volume/flexvolume/detacher.go [hunk 1]
```diff
@@ -77,7 +84,7 @@ func (d *flexVolumeDetacher) UnmountDevice(deviceMountPath string) error {
 
 	// Flexvolume driver may remove the directory. Ignore if it does.
 	if pathExists, pathErr := util.PathExists(deviceMountPath); pathErr != nil {
-		return fmt.Errorf("Error checking if path exists: %v", pathErr)
+		return fmt.Errorf("Errorr checking if path exists: %v", pathErr)
```
[the remark this answers is not in the document]
Comment (chakri-nelluri) [reply pkg/volume/flexvolume/detacher.go]: Fixed it. Thanks @neolit123

**Comment by chakri-nelluri** [comment]
@jingxu97 PTAL when you get a chance. Thanks.

File: pkg/volume/flexvolume/unmounter.go [hunk 2]
```diff
@@ -44,13 +44,16 @@ func (f *flexVolumeUnmounter) TearDown() error {
...
+	pathExists, pathErr := util.PathExists(dir)
+	if !pathExists {
 		glog.Warningf("Warning: Unmount skipped because path does not exist: %v", dir)
 		return nil
 	}
 
+	if pathErr != nil && !util.IsCorruptedMnt(pathErr) {
+		return fmt.Errorf("Error checking path: %v", pathErr)
+	}
+
```
Comment (gnufied) [inline pkg/volume/flexvolume/unmounter.go]: I have been thinking about - https://github.com/kubernetes/kubernetes/issues/67132 too and I am wondering if it is sensible to allow call to `unmount` to flex driver when `ENOTCONN` is raised.  @nkkashyap why do you think it is sensible to allow unmount call even if volume is known to be corrupted?

Comment (chakri-nelluri) [reply pkg/volume/flexvolume/unmounter.go]: @gnufied for some filesystems this may be required. The unmount call from the flexvolume can always fail if it cannot unmount.

**Comment by chakri-nelluri** [comment]
@gnufied Please let me know if this looks good to get in. I want to merge it back to 1.10 & 1.11 releases.

**Comment by chakri-nelluri** [comment]
@ivan4th PTAL when you get a chance.
