### PR TITLE
kubeadm: more verbose unmount logic on "reset"

### LINKED ISSUE #2923: unmountKubeletDirectory should return err instead of nil if unmounting fails
https://github.com/kubernetes/kubernetes/blob/9e644106593f3f4aa98f8a84b23db5fa378900bd/cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go#L52

unmountKubeletDirectory currently returns nil if it encounters an error unmounting. However, runCleanupNode relies on this code to return an error if there's a problem so it doesn't wipe out the kubelet run directory. In this case, if there's an error unmounting since unmountKubeletDirectory returns nil, runCleanupNode will wipe out the kubelet run directory, including any mounted data that may be pointing to an NFS/persistent storage or something from the kubelet/pods directory.

/sig k8s-infra

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind bug
/kind feature

#### What this PR does / why we need it:

contains two commits, first one can be backported:
```
kubeadm: throw errors on unmount instead of warnings

Instead of warnings when syscall.Unmount() causes errors,
store all the errors in an aggregate. Abort the reset operation if
at least one unmount error was encountered.
```

```
kubeadm: add ResetConfiguration.UnmountFlags

Add new a v1beta4.ResetConfiguration.UnmountFlags field that
can be used to pass in Linux unmount2() flags such as MNT_FORCE.
Default value continues to be 0 - i.e. no flags.
```

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/2923
follow up on https://github.com/kubernetes/kubernetes/pull/120377

#### Special notes for your reviewer:
see long discussion in https://github.com/kubernetes/kubernetes/pull/120377

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: add better handling of errors during unmount when calling "kubeadm reset". When failing to unmount directories under "/var/run/kubelet", kubeadm will now throw an error instead of showing a warning and continuing to cleanup said directory. In such situations it is better for you to inspect the problem and resolve it manually, then you can call "kubeadm reset" again to complete the cleanup.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/hold let's wait for consensus
/uncc @chendave 
/cc @pacoxu 

cc @mowangdk @huww98

**Comment by neolit123** [comment]
> kubeadm: add better handling of errors during unmount when calling "kubeadm reset". When failing to unmount directories under "/var/run/kubelet", kubeadm will now throw an error instead of showing a warning and continuing to cleanup said directory. In such situations it is better for you to inspect the problem and resolve it manually, then you can call "kubeadm reset" again to complete the cleanup.

the release note is intentionally not including the addition of v1beta4 field. that will be done when we release the API.
maybe in 1.30 if we have enough time for all the remaining changes.

in case you are wondering about backports of the bug fix for error handling part to older versions of kubernetes. my vote is -1 to that because users have a workaround - manually unmount out of band. then call "reset" to cleanup. but if the maintainer quorum is to have a backport i can split this into two PRs and backport the bug fix only.

File: cmd/kubeadm/app/cmd/phases/reset/cleanupnode.go [hunk 1]
```diff
@@ -131,13 +135,7 @@ func runCleanupNode(c workflow.RunData) error {
...
 	absoluteKubeletRunDirectory, err := filepath.EvalSymlinks(kubeadmconstants.KubeletRunDirectory)
 	if err != nil {
-		klog.Warningf("[reset] Failed to evaluate the %q directory. Skipping its unmount and cleanup: %v\n", kubeadmconstants.KubeletRunDirectory, err)
-		return "", err
-	}
-	err = unmountKubeletDirectory(absoluteKubeletRunDirectory)
-	if err != nil {
-		klog.Warningf("[reset] Failed to unmount mounted directories in %s \n", kubeadmconstants.KubeletRunDirectory)
-		return "", err
+		return "", errors.Wrapf(err, "failed to evaluate the %q directory", kubeadmconstants.KubeletRunDirectory)
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/phases/reset/cleanupnode.go:138]: this was strange, better to have absoluteKubeletRunDirectory() only do the eval symlink.

File: cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go [hunk 2]
```diff
@@ -24,30 +24,34 @@ import (
...
 
-	"k8s.io/klog/v2"
+	"github.com/pkg/errors"
+
+	utilerrors "k8s.io/apimachinery/pkg/util/errors"
 )
 
 // unmountKubeletDirectory unmounts all paths that contain KubeletRunDirectory
-func unmountKubeletDirectory(absoluteKubeletRunDirectory string) error {
+func unmountKubeletDirectory(kubeletRunDirectory string) error {
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go]: just a argument rename to be less confusing.

File: cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go [hunk 3]
```diff
@@ -24,30 +24,34 @@ import (
...
+		if len(m) < 2 || !strings.HasPrefix(m[1], kubeletRunDirectory) {
 			continue
 		}
 		if err := syscall.Unmount(m[1], 0); err != nil {
-			klog.Warningf("[reset] Failed to unmount mounted directory in %s: %s", absoluteKubeletRunDirectory, m[1])
+			errList = append(errList, errors.Wrapf(err, "failed to unmount %s", m[1]))
 		}
 	}
-	return nil
+	return errors.Wrapf(utilerrors.NewAggregate(errList),
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go:73]: this whole return will be `nil` if `len(errList) == 0`

File: cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go [hunk 4]
```diff
@@ -24,30 +24,52 @@ import (
...
 	for _, mount := range mounts {
 		m := strings.Split(mount, " ")
-		if len(m) < 2 || !strings.HasPrefix(m[1], absoluteKubeletRunDirectory) {
+		if len(m) < 2 || !strings.HasPrefix(m[1], kubeletRunDirectory) {
 			continue
 		}
-		if err := syscall.Unmount(m[1], 0); err != nil {
-			klog.Warningf("[reset] Failed to unmount mounted directory in %s: %s", absoluteKubeletRunDirectory, m[1])
+		if err := syscall.Unmount(m[1], flagsToInt(flags)); err != nil {
+			errList = append(errList, errors.Wrapf(err, "failed to unmount %s", m[1]))
```
Comment (huww98) [inline cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go:70]:
```suggestion
			errList = append(errList, fmt.Errorf("failed to unmount %s: %w", m[1], err))
```
We will have stack trace below, maybe we don't need this `Wrapf` here

Comment (neolit123) [reply cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go:70]: we don't use %w and fmt.Errorf in kubeadm, intentionally

Comment (huww98) [reply cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go:70]: OK, that's a little bit strange. Then how about errors.WithMessagef ?

Comment (neolit123) [reply cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go:70]: if we only care about annotating the error, like in this case using WithMessage is more correct, i can update this.
FWIW, we do use consecutive Wraps all over kubeadm within a call stack, even if it is more accurate to put Wraps only in key locations.

Comment (neolit123) [reply cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go]: updated

**Review by huww98 — APPROVED** [review]

File: cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go [hunk 5]
```diff
@@ -24,30 +24,52 @@ import (
...
 		}
-		if err := syscall.Unmount(m[1], 0); err != nil {
-			klog.Warningf("[reset] Failed to unmount mounted directory in %s: %s", absoluteKubeletRunDirectory, m[1])
+		if err := syscall.Unmount(m[1], flagsToInt(flags)); err != nil {
+			errList = append(errList, errors.WithMessagef(err, "failed to unmount %s", m[1]))
 		}
 	}
-	return nil
+	return errors.Wrapf(utilerrors.NewAggregate(errList),
+		"encountered the following errors while unmounting directories in %s", kubeletRunDirectory)
```
Comment (pacoxu) [inline cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go:74]: Should we mention that user may umount using those Flags, or something like `retry after manually handling those errors`.

For v1beta4 added flags, should we mention the new flag in the error message in later version?

**Review by pacoxu — COMMENTED** [review]
Overall LGTM. 

Only a nit and a question about the error message(action item in message).

File: cmd/kubeadm/app/cmd/phases/reset/unmount_linux_test.go [hunk 6]
```diff
@@ -0,0 +1,65 @@
+//go:build linux
+// +build linux
+
+/*
+Copyright 2023 The Kubernetes Authors.
```
[the remark this answers is not in the document]
Comment (neolit123) [reply cmd/kubeadm/app/cmd/phases/reset/unmount_linux_test.go:5]: it's ok to have 2023 because the commit was authored in 2023. the PR may merge in 2025, for example.

File: cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go (hunk 5 above)
Comment (neolit123) [reply cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go:74]: we could add a mention about the UnmountFlags in kubeadm.ResetConfiguration in the error message after v1beta4 is released.

the release note here is quite explicit too i.e. don't unmount with kubeadm if you are getting errors.

Comment (pacoxu) [reply cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go:74]: It sounds like a small action item of v1beta4.

/lgtm

**Comment by neolit123** [comment]
pushed a small change here:
https://github.com/kubernetes/kubernetes/compare/a09509708c2ef09a521abbe37417d63a50c5cca5..f94c133122e8a7200d97a5255a4ac4e2ddaf17be

- use %q instead of %s for consistency with the rest of the reset code
- print the folder that is being unmounted with V(5)

File: cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go [hunk 7]
```diff
@@ -24,30 +24,55 @@ import (
...
 	for _, mount := range mounts {
 		m := strings.Split(mount, " ")
-		if len(m) < 2 || !strings.HasPrefix(m[1], absoluteKubeletRunDirectory) {
+		if len(m) < 2 || !strings.HasPrefix(m[1], kubeletRunDirectory) {
 			continue
 		}
-		if err := syscall.Unmount(m[1], 0); err != nil {
-			klog.Warningf("[reset] Failed to unmount mounted directory in %s: %s", absoluteKubeletRunDirectory, m[1])
+		klog.V(5).Infof("[reset] Unmounting %q", m[1])
+		if err := syscall.Unmount(m[1], flagsToInt(flags)); err != nil {
```
Comment (SataQiu) [inline cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go:72]: SGTM
we can move `flagsToInt(flags)` out of the for loop

Comment (neolit123) [reply cmd/kubeadm/app/cmd/phases/reset/unmount_linux.go]: updated

**Review by neolit123 — COMMENTED** [review]
thanks for the reviews. this is good to go.

/hold cancel

**Comment by neolit123** [comment]
looks like we have e2e failures after this PR.
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-discovery-latest
https://[storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-discovery-latest/1743498171742425088/artifacts/task-10-reset-log.txt](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-discovery-latest/1743498171742425088/artifacts/task-10-reset-log.txt)

the problem seems to be that if the /var/lib/kubelet directory does not exist we must skip unmouning completetely,
```
W0106 05:14:39.310000     273 removeetcdmember.go:106] [reset] No kubeadm config, using etcd pod spec to get data directory
I0106 05:14:39.310053     273 cleanupnode.go:66] [reset] Getting init system
[reset] Unmounting mounted directories in "/var/lib/kubelet"
lstat /var/lib/kubelet: no such file or directory
failed to evaluate the "/var/lib/kubelet" directory
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/reset.absoluteKubeletRunDirectory
	k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/reset/cleanupnode.go:138
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/reset.runCleanupNode
```

i will send a follow up fix.

**Comment by neolit123** [comment]
> i will send a follow up fix.

please review 
https://github.com/kubernetes/kubernetes/pull/122619
