### PR TITLE
scheduler: fix flaky test TestPreemptionRaces

### LINKED ISSUE #74931: Scheduler TestPreemptionRaces is flaky
**Which jobs are failing**:
[Presubmit tests](https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration)

**Which test(s) are failing**:
kubernetes/test/integration/scheduler.TestPreemptionRaces

**Since when has it been failing**:
Not exactly known. The flake rate is not high. That's probably why it has not received attention.

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration

**Reason for failure**:
Logs are currently unaccessible. Test grid returns an error when clicking on the failed instances.

**Anything else we need to know**:

/sig scheduling
/label help-wanted

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind bug
/kind flake
/sig scheduling
/priority important-soon
/assign @bsalamat 

**What this PR does / why we need it**:

In some cases, an Update event with no "NominatedNode" present is received right
after a node("NominatedNode") is reserved for this pod in memory.

If we go updating (delete and add) it, it actually un-reserves the node since
the newPod doesn't carry sped.status.nominatedNode.

In this case, during this time other low-priority pods have chances to take space which was reserved for the nominatedPod.

**Which issue(s) this PR fixes**:

Fixes #74931.

**Special notes for your reviewer**:

The flake is reproducible in my env and the above solution and analysis are given based on the real execution path. However, we can brainstorm a better solution following the same rationale.

BTW: actually it's more a bug. And the integration test was given impressively to reveal it :)

**Does this PR introduce a user-facing change?**:

```release-note
Fixed a scheduler racing issue to ensure low priority pods to be unschedulable on the node(s) where high priority pods have `NominatedNodeName` set to the node(s). 
```

### CODE REVIEW

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 1]
```diff
@@ -772,7 +772,16 @@ func (npm *nominatedPodMap) delete(p *v1.Pod) {
...
 
 func (npm *nominatedPodMap) update(oldPod, newPod *v1.Pod) {
-	// We update irrespective of the nominatedNodeName changed or not, to ensure
+	// In some cases, an Update event with no "NominatedNode" present is received right
+	// after a node("NominatedNode") is reserved for this pod in memory.
+	// If we go updating (delete and add) it, it actually un-reserves the node since
+	// the newPod doesn't carry sped.status.nominatedNode.
+	// In this case, during this time other low-priority pods have chances to take space which
+	// was reserved for the nominatedPod.
+	if len(oldPod.Status.NominatedNodeName) == 0 && len(newPod.Status.NominatedNodeName) == 0 {
```
Comment (bsalamat) [inline pkg/scheduler/internal/queue/scheduling_queue.go]: What you have found is an interesting case. The only problem is that a pod pointer could change in an update. If we bypass this update, we may not receive the new pointer.

Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go]: That's true. The good thing is that in both npm.delete() and npm.add(), we actually check whether pod.UID exists or not, rather than directly check the pointer's presence. And the idea of this change skips only one case which is both old and new pods don't have NominatedNodeName set.

Comment (bsalamat) [reply pkg/scheduler/internal/queue/scheduling_queue.go]: I understand, but with the existing logic, if a pod pointer is updated, this update function updates the pod pointer. This condition that you have added skips the pointer update. Your point is valid though that this skips only when both NominatedNodeNames are empty, which can be true only for pods that have just been nominated and we have not received their NominatedNode status update.
This may solve the problem, but it does not look great and feels like a hack to me. Let me think about a bit more and see if I can find a cleaner solution.

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 2]
```diff
@@ -772,7 +772,16 @@ func (npm *nominatedPodMap) delete(p *v1.Pod) {
 }
 
 func (npm *nominatedPodMap) update(oldPod, newPod *v1.Pod) {
-	// We update irrespective of the nominatedNodeName changed or not, to ensure
+	// In some cases, an Update event with no "NominatedNode" present is received right
+	// after a node("NominatedNode") is reserved for this pod in memory.
+	// If we go updating (delete and add) it, it actually un-reserves the node since
+	// the newPod doesn't carry sped.status.nominatedNode.
```
Comment (bsalamat) [inline pkg/scheduler/internal/queue/scheduling_queue.go]: s/sped.status.nominatedNode/Status.NominatedNodeName/

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 1 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go]: That's fair. We can brainstorm for a better solution.

File: pkg/scheduler/internal/queue/scheduling_queue.go [hunk 3]
```diff
@@ -772,10 +772,24 @@ func (npm *nominatedPodMap) delete(p *v1.Pod) {
...
+	// In some cases, an Update event with no "NominatedNode" present is received right
+	// after a node("NominatedNode") is reserved for this pod in memory.
+	// In this case, we need to keep reserving the NominatedNode when updating the pod pointer.
+	nodeName := ""
+	// We won't fall into below `if` block if the Update event represents:
+	// (1) NominatedNode info is added
+	// (2) NominatedNode info is updated
+	// (3) NominatedNode info is removed
+	if NominatedNodeName(oldPod) == "" && NominatedNodeName(newPod) == "" {
+		if nnn, ok := npm.nominatedPodToNode[oldPod.UID]; ok {
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/queue/scheduling_queue.go]: A neat way is `nodeName = npm.nominatedPodToNode[oldPod.UID]`. If oldPod.UID doesn't exist, a nil string is returned.

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 1 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go]: @bsalamat A new solution is proposed. PTAL.

File: pkg/scheduler/internal/queue/scheduling_queue.go (hunk 3 above)
Comment (bsalamat) [reply pkg/scheduler/internal/queue/scheduling_queue.go]: This change makes the logic more robust, but `nodeName` should not be initialized with empty string. It should be initialized by `NominatedNodeName(newPod)`. Otherwise, all usual updates would remove nominated pods.

Comment (Huang-Wei) [reply pkg/scheduler/internal/queue/scheduling_queue.go]: Initilizing `nodeName` as empty string should be good b/c in nominatedPodMap.add(), it checks if incoming nodeName is empty; if it is, it calls NominatedNodeName(p):

https://github.com/kubernetes/kubernetes/blob/314264aeafb94d4948a3f117bcc4382eba10dede/pkg/scheduler/internal/queue/scheduling_queue.go#L735-L746

Comment (bsalamat) [reply pkg/scheduler/internal/queue/scheduling_queue.go]: You are right.

**Review by bsalamat — COMMENTED** [review]
/lgtm

**Comment by KJTsanaktsidis** [comment]
This is in the 1.15.0-alpha3 changelog as:

> Fixed a scheduler racing issue to ensure low priority pods to be unschedulable on the node(s) where high priority pods have NominatedNodeName set to the node(s)

I believe I may have run into this issue with 1.13.7 on GKE. I was testing pod pre-emption based on priority, and to do so I made the following deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsdeploy
  namespace: connect-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bsdeploy
  replicas: 37
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bsdeploy
    spec:
      nodeName: gke-app-cluster-noautoscalev1-a3fc8c3b-vjt3
      priorityClassName: normal-workload-priority
      containers:
      - name: bs
        image: busybox
        command: [ '/bin/sleep', '10000000' ]
        resources:
          requests:
            cpu: 205m

```
i.e. binds 37 copies of `bsdeploy` to the node `gke-app-cluster-noautoscalev1-a3fc8c3b-vjt3` with class `normal-workload-priority` (set to 100) carefully calibrated to fill up it's available CPU.

I then deployed a daemonset (`consul-agent`) to my cluster with a higher priority class (1000). I see that the daemonset does actually pre-empt the `bsdeploy` pods - a bunch of them are terminated with an event:

```
  Normal  Preempted  95s   default-scheduler                                             by cluster-baseline/consul-agent-vlcr4 on node gke-app-cluster-noautoscalev1-a3fc8c3b-vjt3
```

However, the actual daemonset pod `consul-agent-vlcr4` is still unscheduled, even though the status on it has `nominatedNodeName` set to `gke-app-cluster-noautoscalev1-a3fc8c3b-vjt3` (i.e. where we want it to go). Instead, the deployment for `bsdeploy` keeps making more Pods, and they end up getting scheduled.

Is this evidence that perhaps this fix should be backported to 1.13/1.14 as well?

Thanks!

**Comment by KJTsanaktsidis** [comment]
Disregard the above... I figured out my issue was totally separate.

The issue was that I had my `bsdepoy` using `nodeName:` to put it on the node I wanted it to get evicted from.

What I think was happening was that:
  * New consul-agent pod of higher priority was created in etcd
  * Scheduler tries to put it somewhere, only place it can go is on the `gke-app-cluster-noautoscalev1-a3fc8c3b-vjt3` node (since it has to go everywhere)
  * Since that node is full, and the daemonset is higher priority, it tries to evict some stuff. It deletes some Pods of `bsdeploy` on `gke-app-cluster-noautoscalev1-a3fc8c3b-vjt3`, then sets `nominatedNodeName` on the daemonset pod to the node it should go to.
  * The deployment notices that one of it's Pods got deleted, so it makes another one
  * But the pod template has `nodeName` on it, so the new Pod actually just gets assigned to `gke-app-cluster-noautoscalev1-a3fc8c3b-vjt3` without going through the scheduler at all
  * When the scheduler tries again to schedule the daemonset, it can't, because the empty space from its eviction was actually already filled up by the replacement `bsdeploy` pod.

I fixed my test setup by using a node affinity on the desired node instead of directly setting `nodeName` in the template. Then everything works as expected.

So, maybe this change should be backported, maybe not, but definitely not for this reason :)

**Comment by liggitt** [comment]
@Huang-Wei @ahg-g should this be backported to 1.14? I can't tell how severe the bug being fixed is

**Comment by ahg-g** [comment]
I don't think this is that severe because even if the race happens, it means the pod will have to go through another round of scheduling and possibly preemption, so the pod will get scheduled eventually. Isn't that true @Huang-Wei?

But I don't mind if we decide to backport it.

**Comment by Huang-Wei** [comment]
> I don't think this is that severe because even if the race happens, it means the pod will have to go through another round of scheduling and possibly preemption, so the pod will get scheduled eventually. Isn't that true @Huang-Wei?

It's true.

@liggitt I'm fine with backporting it, but isn't 1.14 out of official supporting versions?

**Comment by liggitt** [comment]
> @liggitt I'm fine with backporting it, but isn't 1.14 out of official supporting versions?

ack, off by one error in real life :)
