### PR TITLE
Fix kube-proxy iptables startup: log but don't exit if ipv4 or ipv6 is not available

### LINKED ISSUE #133694: kube-proxy v1.34.* fails to start if ipv4 or ipv6 are unavailable
### What happened?

we started seeing timeout failures in our minikube kvm driver integration tests with kubernetes v1.34.*, whereas v1.33.4 does not have this specific problem

further looking into the kube-proxy code and changes made between k8s v1.33.4 and v1.34.*, i think i found the issue:
- introduced in https://github.com/kubernetes/kubernetes/pull/131534 - returning error if not both ipv4 and ipv6 work
- the issue is nicely explained in https://github.com/kubernetes/kubernetes/pull/132170, but i think not completely fixed

namely, in our kvm vm, we only use ipv4, which still makes the [NewDualStack()](https://github.com/kubernetes/kubernetes/blob/091f87c10bc3532041b77a783a5f832de5506dc8/cmd/kube-proxy/app/server_linux.go#L94) func call to fail and thus prevents kube-proxy from starting

```
$ minikube start --driver kvm2 --kubernetes-version v1.34.0-rc.1
😄  minikube v1.36.0 on Opensuse-Tumbleweed 20250820
✨  Using the kvm2 driver based on user configuration
👍  Starting "minikube" primary control-plane node in "minikube" cluster
🔥  Creating kvm2 VM (CPUs=2, Memory=6144MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.34.0-rc.1 on Docker 28.3.2 ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

```
$ kubectl get all -A
NAMESPACE     NAME                                   READY   STATUS             RESTARTS      AGE
kube-system   pod/coredns-66bc5c9577-4zdmb           0/1     Running            0             55s
kube-system   pod/etcd-minikube                      1/1     Running            0             61s
kube-system   pod/kube-apiserver-minikube            1/1     Running            0             60s
kube-system   pod/kube-controller-manager-minikube   1/1     Running            0             60s
kube-system   pod/kube-proxy-vmx7x                   0/1     CrashLoopBackOff   3 (13s ago)   55s
kube-system   pod/kube-scheduler-minikube            1/1     Running            0             61s
kube-system   pod/storage-provisioner                1/1     Running            1 (24s ago)   59s

NAMESPACE     NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP                  61s
kube-system   service/kube-dns     ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   60s

NAMESPACE     NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   daemonset.apps/kube-proxy   1         1         0       1            0           kubernetes.io/os=linux   60s

NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   0/1     1            0           60s

NAMESPACE     NAME                                 DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-66bc5c9577   1         1         0       55s
```

kube-proxy logs (verbose enabled):

```
$ kubectl logs -n kube-system daemonset.apps/kube-proxy
I0825 10:25:07.540743       1 server_linux.go:53] "Using iptables proxy"
I0825 10:25:07.540844       1 flags.go:64] FLAG: --bind-address="0.0.0.0"
I0825 10:25:07.540851       1 flags.go:64] FLAG: --bind-address-hard-fail="false"
I0825 10:25:07.540855       1 flags.go:64] FLAG: --boot-id-file="/proc/sys/kernel/random/boot_id"
I0825 10:25:07.540858       1 flags.go:64] FLAG: --cleanup="false"
I0825 10:25:07.540860       1 flags.go:64] FLAG: --cluster-cidr=""
I0825 10:25:07.540968       1 flags.go:64] FLAG: --config="/var/lib/kube-proxy/config.conf"
I0825 10:25:07.540976       1 flags.go:64] FLAG: --config-sync-period="15m0s"
I0825 10:25:07.540979       1 flags.go:64] FLAG: --conntrack-max-per-core="32768"
I0825 10:25:07.540982       1 flags.go:64] FLAG: --conntrack-min="131072"
I0825 10:25:07.540983       1 flags.go:64] FLAG: --conntrack-tcp-be-liberal="false"
I0825 10:25:07.540994       1 flags.go:64] FLAG: --conntrack-tcp-timeout-close-wait="1h0m0s"
I0825 10:25:07.540996       1 flags.go:64] FLAG: --conntrack-tcp-timeout-established="24h0m0s"
I0825 10:25:07.540998       1 flags.go:64] FLAG: --conntrack-udp-timeout="0s"
I0825 10:25:07.540999       1 flags.go:64] FLAG: --conntrack-udp-timeout-stream="0s"
I0825 10:25:07.541007       1 flags.go:64] FLAG: --detect-local-mode=""
I0825 10:25:07.541015       1 flags.go:64] FLAG: --feature-gates=""
I0825 10:25:07.541018       1 flags.go:64] FLAG: --healthz-bind-address="0.0.0.0:10256"
I0825 10:25:07.541020       1 flags.go:64] FLAG: --healthz-port="10256"
I0825 10:25:07.541022       1 flags.go:64] FLAG: --help="false"
I0825 10:25:07.541024       1 flags.go:64] FLAG: --hostname-override="kernel-6.6.102"
I0825 10:25:07.541026       1 flags.go:64] FLAG: --init-only="false"
I0825 10:25:07.541027       1 flags.go:64] FLAG: --iptables-localhost-nodeports="true"
I0825 10:25:07.541029       1 flags.go:64] FLAG: --iptables-masquerade-bit="14"
I0825 10:25:07.541031       1 flags.go:64] FLAG: --iptables-min-sync-period="1s"
I0825 10:25:07.541041       1 flags.go:64] FLAG: --iptables-sync-period="30s"
I0825 10:25:07.541091       1 flags.go:64] FLAG: --ipvs-exclude-cidrs="[]"
I0825 10:25:07.541099       1 flags.go:64] FLAG: --ipvs-min-sync-period="1s"
I0825 10:25:07.541100       1 flags.go:64] FLAG: --ipvs-scheduler=""
I0825 10:25:07.541102       1 flags.go:64] FLAG: --ipvs-strict-arp="false"
I0825 10:25:07.541103       1 flags.go:64] FLAG: --ipvs-sync-period="30s"
I0825 10:25:07.541105       1 flags.go:64] FLAG: --ipvs-tcp-timeout="0s"
I0825 10:25:07.541107       1 flags.go:64] FLAG: --ipvs-tcpfin-timeout="0s"
I0825 10:25:07.541108       1 flags.go:64] FLAG: --ipvs-udp-timeout="0s"
I0825 10:25:07.541109       1 flags.go:64] FLAG: --kube-api-burst="10"
I0825 10:25:07.541111       1 flags.go:64] FLAG: --kube-api-content-type="application/vnd.kubernetes.protobuf"
I0825 10:25:07.541113       1 flags.go:64] FLAG: --kube-api-qps="5"
I0825 10:25:07.541116       1 flags.go:64] FLAG: --kubeconfig=""
I0825 10:25:07.541117       1 flags.go:64] FLAG: --log-flush-frequency="5s"
I0825 10:25:07.541158       1 flags.go:64] FLAG: --log-json-info-buffer-size="0"
I0825 10:25:07.541162       1 flags.go:64] FLAG: --log-json-split-stream="false"
I0825 10:25:07.541179       1 flags.go:64] FLAG: --log-text-info-buffer-size="0"
I0825 10:25:07.541185       1 flags.go:64] FLAG: --log-text-split-stream="false"
I0825 10:25:07.541187       1 flags.go:64] FLAG: --logging-format="text"
I0825 10:25:07.541188       1 flags.go:64] FLAG: --machine-id-file="/etc/machine-id,/var/lib/dbus/machine-id"
I0825 10:25:07.541190       1 flags.go:64] FLAG: --masquerade-all="false"
I0825 10:25:07.541192       1 flags.go:64] FLAG: --master=""
I0825 10:25:07.541193       1 flags.go:64] FLAG: --metrics-bind-address="127.0.0.1:10249"
I0825 10:25:07.541196       1 flags.go:64] FLAG: --metrics-port="10249"
I0825 10:25:07.541220       1 flags.go:64] FLAG: --nodeport-addresses="[]"
I0825 10:25:07.541227       1 flags.go:64] FLAG: --oom-score-adj="-999"
I0825 10:25:07.541229       1 flags.go:64] FLAG: --pod-bridge-interface=""
I0825 10:25:07.541239       1 flags.go:64] FLAG: --pod-interface-name-prefix=""
I0825 10:25:07.541309       1 flags.go:64] FLAG: --profiling="false"
I0825 10:25:07.541326       1 flags.go:64] FLAG: --proxy-mode=""
I0825 10:25:07.541328       1 flags.go:64] FLAG: --show-hidden-metrics-for-version=""
I0825 10:25:07.541329       1 flags.go:64] FLAG: --v="7"
I0825 10:25:07.541332       1 flags.go:64] FLAG: --version="false"
I0825 10:25:07.541334       1 flags.go:64] FLAG: --vmodule=""
I0825 10:25:07.541336       1 flags.go:64] FLAG: --write-config-to=""
I0825 10:25:07.541395       1 feature_gate.go:385] feature gates: {map[]}
I0825 10:25:07.567918       1 loader.go:402] Config loaded from file:  /var/lib/kube-proxy/kubeconfig.conf
I0825 10:25:07.568217       1 shared_informer.go:349] "Waiting for caches to sync" controller="node informer cache"
I0825 10:25:07.568373       1 reflector.go:358] "Starting reflector" type="*v1.Node" resyncPeriod="15m0s" reflector="k8s.io/client-go/informers/factory.go:160"
I0825 10:25:07.568385       1 reflector.go:404] "Listing and watching" type="*v1.Node" reflector="k8s.io/client-go/informers/factory.go:160"
I0825 10:25:07.568469       1 round_trippers.go:527] "Request" verb="GET" url="https://control-plane.minikube.internal:8443/api/v1/nodes?fieldSelector=metadata.name%3Dkernel-6.6.102&limit=500&resourceVersion=0" headers=<
    Accept: application/vnd.kubernetes.protobuf, */*
    Authorization: Bearer <masked>
    User-Agent: kube-proxy/v1.34.0 (linux/amd64) kubernetes/ed3ccdb
 >
I0825 10:25:07.572145       1 round_trippers.go:632] "Response" status="200 OK" milliseconds=3
I0825 10:25:07.572419       1 reflector.go:436] "Caches populated" type="*v1.Node" reflector="k8s.io/client-go/informers/factory.go:160"
I0825 10:25:07.572520       1 round_trippers.go:527] "Request" verb="GET" url="https://control-plane.minikube.internal:8443/api/v1/nodes?allowWatchBookmarks=true&fieldSelector=metadata.name%3Dkernel-6.6.102&resourceVersion=1378&timeout=5m27s&timeoutSeconds=327&watch=true" headers=<
    Accept: application/vnd.kubernetes.protobuf, */*
    Authorization: Bearer <masked>
    User-Agent: kube-proxy/v1.34.0 (linux/amd64) kubernetes/ed3ccdb
 >
I0825 10:25:07.573009       1 round_trippers.go:632] "Response" status="200 OK" milliseconds=0
I0825 10:25:07.669348       1 shared_informer.go:356] "Caches are synced" controller="node informer cache"
I0825 10:25:07.669373       1 server.go:219] "Successfully retrieved NodeIPs" NodeIPs=["192.168.61.40"]
E0825 10:25:07.669440       1 server.go:256] "Kube-proxy configuration may be incomplete or incorrect" err="nodePortAddresses is unset; NodePort connections will be accepted on all local IPs. Consider using `--nodeport-addresses primary`"
I0825 10:25:07.680959       1 iptables.go:509] "Running" command="iptables" arguments=["-w","5","-S","POSTROUTING","-t","nat"]
I0825 10:25:07.682621       1 iptables.go:509] "Running" command="ip6tables" arguments=["-w","5","-S","POSTROUTING","-t","nat"]
I0825 10:25:07.685129       1 server_linux.go:104] "No iptables support for family" ipFamily="IPv6" error=<
    error listing chain "POSTROUTING" in table "nat": exit status 3: ip6tables v1.8.9 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
    Perhaps ip6tables or your kernel needs to be upgraded.
 >
E0825 10:25:07.685163       1 server.go:135] "Error running ProxyServer" err=<
    error listing chain "POSTROUTING" in table "nat": exit status 3: ip6tables v1.8.9 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
    Perhaps ip6tables or your kernel needs to be upgraded.
 >
E0825 10:25:07.685175       1 run.go:72] "command failed" err=<
    error listing chain "POSTROUTING" in table "nat": exit status 3: ip6tables v1.8.9 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
    Perhaps ip6tables or your kernel needs to be upgraded.
 >
```

inside vm:

```
# ip6tables -w 5 -S POSTROUTING -t nat
ip6tables v1.8.11 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.
```

```
# lsmod | grep ip
iptable_nat            12288  1
nf_nat                 57344  3 xt_nat,iptable_nat,xt_MASQUERADE
nf_defrag_ipv6         16384  1 nf_conntrack
nf_defrag_ipv4         12288  1 nf_conntrack
```

```
# modprobe ip6table_nat
modprobe: FATAL: Module ip6table_nat not found in directory /lib/modules/6.6.95
```

### What did you expect to happen?

kube-proxy to start normally

### How can we reproduce it (as minimally and precisely as possible)?

`minikube start --driver kvm2 --kubernetes-version v1.34.0-rc.2`

### Anything else we need to know?

i think [this](https://github.com/kubernetes/kubernetes/blob/091f87c10bc3532041b77a783a5f832de5506dc8/cmd/kube-proxy/app/server_linux.go#L88-L94) was probably an unintentional change, as it maps this NewDualStack() func call's return error directly to the platformCheckSupported() return err varable value and then bubbles up through the newProxyServer() and finally Run()

if we still want/need (i'm not 100% sure) to error but only if neither ipv4 nor ipv6 works, we could do something like:

```
diff --git a/cmd/kube-proxy/app/server_linux.go b/cmd/kube-proxy/app/server_linux.go
index 37c4da7bbbc..cdb10c49458 100644
--- a/cmd/kube-proxy/app/server_linux.go
+++ b/cmd/kube-proxy/app/server_linux.go
@@ -91,13 +91,14 @@ func (s *ProxyServer) platformCheckSupported(ctx context.Context) (ipv4Supported
 	if isIPTablesBased(s.Config.Mode) {
 		// Check for the iptables and ip6tables binaries.
 		var ipts map[v1.IPFamily]utiliptables.Interface
-		ipts, err = utiliptables.NewDualStack()
+		var errDS error
+		ipts, errDS = utiliptables.NewDualStack()
 
 		ipv4Supported = ipts[v1.IPv4Protocol] != nil
 		ipv6Supported = ipts[v1.IPv6Protocol] != nil
 
 		if !ipv4Supported && !ipv6Supported {
-			err = fmt.Errorf("iptables is not available on this host : %w", err)
+			err = fmt.Errorf("iptables is not available on this host : %w", errDS)
 		} else if !ipv4Supported {
 			logger.Info("No iptables support for family", "ipFamily", v1.IPv4Protocol, "error", err)
 		} else if !ipv6Supported {
```
i tested that change locally and it worked (ie, kube-proxy starts in our kvm vm)

(btw, this is on the main branch as well)

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: v1.34.0-rc.1
```

```console
$ kubectl version
Server Version: v1.34.0-rc.2
```

</details>

### Cloud provider

<details>
n/a
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME=Buildroot
VERSION=2025.02-dirty
ID=buildroot
VERSION_ID=2025.02
PRETTY_NAME="Buildroot 2025.02"

$ uname -a
Linux kernel-6.6.102 6.6.102 #1 SMP PREEMPT_DYNAMIC Mon Aug 25 06:58:39 UTC 2025 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
minikube with kvm driver (using kubeadm)
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by prezha**
#### What type of PR is this?

/kind bug
/kind regression
/sig network
/priority important-soon

#### What this PR does / why we need it:

similar to https://github.com/kubernetes/kubernetes/pull/132170, https://github.com/kubernetes/kubernetes/pull/131534 was not supposed to change kube-proxy's behavior, but instead of just logging, it will error out and exit if either ipv4 or ipv6 are unavailable

this pr aims to restore the original kube-proxy behavior and log but not exit if ipv4 or ipv6 are not available

#### Which issue(s) this PR is related to:

Fixes #133694

#### Does this PR introduce a user-facing change?

```release-note
Fixed regression introduced in v1.34.0-alpha.1 where the kube-proxy fails to start on an IP single-stack networking.
```

### CODE REVIEW

**Comment by dims** [comment]
cc @Vyom-Yadav @kubernetes/release-team-leads

**Review by BenTheElder — COMMENTED** [review]
/lgtm

thanks!

**Comment by BenTheElder** [comment]
flake in: k8s.io/apiserver/pkg/admission/plugin/policy: validating
https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/133695/pull-kubernetes-unit/1960097447065686016
/retest

File: cmd/kube-proxy/app/server_linux.go [hunk 1]
```diff
@@ -91,13 +91,14 @@ func (s *ProxyServer) platformCheckSupported(ctx context.Context) (ipv4Supported
...
+		ipts, errDS = utiliptables.NewDualStack()
 
 		ipv4Supported = ipts[v1.IPv4Protocol] != nil
 		ipv6Supported = ipts[v1.IPv6Protocol] != nil
 
 		if !ipv4Supported && !ipv6Supported {
-			err = fmt.Errorf("iptables is not available on this host : %w", err)
+			err = fmt.Errorf("iptables is not available on this host : %w", errDS)
 		} else if !ipv4Supported {
 			logger.Info("No iptables support for family", "ipFamily", v1.IPv4Protocol, "error", err)
```
Comment (aojea) [inline cmd/kube-proxy/app/server_linux.go]:
```suggestion
			logger.Info("No iptables support for family", "ipFamily", v1.IPv4Protocol, "error", errDS)
```

Comment (aojea) [reply cmd/kube-proxy/app/server_linux.go]: same in the log below, 

```
			logger.Info("No iptables support for family", "ipFamily", v1.IPv6Protocol, "error", errDS)
```

**Comment by aojea** [comment]
@danwinship it seems there is also another case in the kubelet that I think is wrong too https://github.com/kubernetes/kubernetes/pull/131534/commits/858b88bceefd170a1fddb3cccf35e6c0c50f4af0#r2299287570

should we completely revert https://github.com/kubernetes/kubernetes/pull/131534/commits/858b88bceefd170a1fddb3cccf35e6c0c50f4af0 ?

File: cmd/kube-proxy/app/server_linux.go (hunk 1 above)
Comment (prezha) [reply cmd/kube-proxy/app/server_linux.go]: good catch, thanks @aojea!
wanted to accept your suggestion, but got "There was an error trying to commit changes: Failed to submit suggested changes" from github :(
so i pushed another commit addressing your comment

**Comment by prezha** [comment]
> @danwinship it seems there is also another case in the kubelet that I think is wrong too [858b88b#r2299287570](https://github.com/kubernetes/kubernetes/commit/858b88bceefd170a1fddb3cccf35e6c0c50f4af0#r2299287570)
> 
> should we completely revert [858b88b](https://github.com/kubernetes/kubernetes/commit/858b88bceefd170a1fddb3cccf35e6c0c50f4af0) ?

i think there might be conflicts due to the previous partial reverse of [858b88b](https://github.com/kubernetes/kubernetes/commit/858b88bceefd170a1fddb3cccf35e6c0c50f4af0) in https://github.com/kubernetes/kubernetes/pull/132170

**Comment by Vyom-Yadav** [comment]
It took me a few seconds to notice what this PR is fixing, honestly, I'm not a big fan of declaring return variables in the function signature and then just doing a `return` (at least for go):

```go
func (s *ProxyServer) platformCheckSupported(ctx context.Context) (ipv4Supported, ipv6Supported, dualStackSupported bool, err error) {
...
return
```

I kind of think this is a code smell, and if it were returning the values separately, this might have been avoided. 

```go
return ipv4Supported, ipv6Supported, dualStackSupported, nil 
```

and so on. So I'd suggest changing it to follow that pattern. 

---

cc @danwinship @aojea Ref: https://github.com/kubernetes/kubernetes/pull/133695#issuecomment-3221949218, would the fix be this PR or a revert? (Feel free to add milestone to the relevant PRs/Reverts)

**Comment by Vyom-Yadav** [comment]
I think this should have a release note as well.

**Comment by prezha** [comment]
> I'm not a big fan of declaring return variables in the function signature and then just doing a `return` (at least for go)

i personally 100% agree, but given the timing around release, i wanted to keep the proposed change down to a bare minimum

since NewDualStack() func returned error is mostly ignored when called (defeating the intent to capture the error and at least log it), we should probably change the NewDualStack() to only log any error and do not return the error itself, and then let the caller decide what to do based on the retuned slice (length) or explicit bools, but that would be a bit bigger change that we can do as a follow up pr perhaps?

either way, i'm happy to create one - now or later

**Comment by prezha** [comment]
> I think this should have a release note as well.

i added the following to the issue description:
```
Fix regression introduced in v1.34.0-alpha.1 - where kube-proxy fails to start on a IP single-stack networking.
```
would that work, please?

**Comment by wendy-ha18** [comment]
> > I think this should have a release note as well.

> 
> i added the following to the issue description:
> 
> `Fix regression introduced in v1.34.0-alpha.1 - where kube-proxy fails to start on a IP single-stack networking.`
> would that work, please?

Hi @prezha , if you won't mind, could you please help to place your release note in the release note section in the bottom of PR template (view screenshot) :smiley:. It will help the release note tooling capture it in our final release note. 
image

You can view [here](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) for more guidance.

**Comment by aojea** [comment]
> #131534

nevermind, I misread, this other thing in the kubelet was already fixed by dan https://github.com/kubernetes/kubernetes/pull/132170

File: cmd/kube-proxy/app/server_linux.go [hunk 2]
```diff
@@ -91,17 +91,18 @@ func (s *ProxyServer) platformCheckSupported(ctx context.Context) (ipv4Supported
 	if isIPTablesBased(s.Config.Mode) {
 		// Check for the iptables and ip6tables binaries.
 		var ipts map[v1.IPFamily]utiliptables.Interface
-		ipts, err = utiliptables.NewDualStack()
+		var errDS error
+		ipts, errDS = utiliptables.NewDualStack()
```
Comment (danwinship) [inline cmd/kube-proxy/app/server_linux.go]: Don't need the separate declarations any more:

```golang
		ipts, errDS := utiliptables.NewDualStack()
```

File: cmd/kube-proxy/app/server_linux.go (hunk 1 above)
Comment (danwinship) [reply cmd/kube-proxy/app/server_linux.go]: Can you squash the changes together? Just fix it all locally in one commit on top of master and then `git push --force`

**Comment by danwinship** [comment]
> It took me a few seconds to notice what this PR is fixing, honestly, I'm not a big fan of declaring return variables in the function signature and then just doing a `return`

Yeah. The "declaring return variables in the signature" part is because otherwise the signature would just be `(bool, bool, bool, error)` which is incomprehensible. But you're right, we should still be explicit in the actual `return`.

**Comment by aojea** [comment]
@prezha please check last comment and see if you can get the commits squashed

**Comment by aojea** [comment]
alternative maintaining the author but squashing the comment and addressing Dan's comments https://github.com/kubernetes/kubernetes/pull/133711

File: cmd/kube-proxy/app/server_linux.go (hunk 2 above)
Comment (prezha) [reply cmd/kube-proxy/app/server_linux.go]: thanks Dan, pushed another commit to fix that

File: cmd/kube-proxy/app/server_linux.go (hunk 1 above)
Comment (prezha) [reply cmd/kube-proxy/app/server_linux.go]: yes, i've squashed all the commits into one

**Comment by prezha** [comment]
> Hi @prezha , if you won't mind, could you please help to place your release note in the release note section in the bottom of PR template (view screenshot) 😃. It will help the release note tooling capture it in our final release note.

thank you @wendy-ha18 for the pointers, i've changed the issue description and used the `release-note` section

File: cmd/kube-proxy/app/server_linux.go [hunk 3]
```diff
@@ -90,18 +90,17 @@ func (s *ProxyServer) platformCheckSupported(ctx context.Context) (ipv4Supported
 
 	if isIPTablesBased(s.Config.Mode) {
 		// Check for the iptables and ip6tables binaries.
-		var ipts map[v1.IPFamily]utiliptables.Interface
-		ipts, err = utiliptables.NewDualStack()
+		ipts, errDS := utiliptables.NewDualStack()
```
Comment (aojea) [inline cmd/kube-proxy/app/server_linux.go:93]: it seems this is safe https://go.dev/play/p/WQMPhJu4tq5

Comment (prezha) [reply cmd/kube-proxy/app/server_linux.go:93]: yeah, crossed my mind as well :)
based on the go [docs](https://go.dev/blog/maps#declaration-and-initialization):
> A nil map behaves like an empty map when reading, but attempts to write to a nil map will cause a runtime panic; don’t do that.

**Comment by aojea** [comment]
> cc @danwinship @aojea Ref: [#133695 (comment)](https://github.com/kubernetes/kubernetes/pull/133695#issuecomment-3221949218), would the fix be this PR or a revert? (Feel free to add milestone to the relevant PRs/Reverts)

/lgtm
/approve

I talked with Dan offline and we think this is more cointained and scoped that represent less risk for the release

@Vyom-Yadav per your comment above, we think this is a regression and we should get it in before the release, so applying milestone to include it 

/milestone v1.34

Thanks @prezha

**Comment by aojea** [comment]
> /retest

please log the job failing and the error in the retest so people can track it, sometimes it may be related to the PR, in this case it is not

>        	Error:      	Received unexpected error:
        	            	context deadline exceeded
        	Test:       	TestParamRef/ParamRefWithNameDenyNotFound
--- FAIL: TestParamRef/ParamRefWithNameDenyNotFound (6.25s)

**Comment by prezha** [comment]
> please log the job failing and the error in the retest so people can track it, sometimes it may be related to the PR, in this case it is not

thank you for letting me know, will do that next time

**Comment by prezha** [comment]
not sure how important it is, but it looks like the [changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.34.md#changelog-since-v1330) automation for v1.34.0, that came out about an hour ago, did not pick up this pr - perhaps it's a timing issue, as we pushed it yesterday - during the freeze period, and the changelog was [generated](https://github.com/kubernetes/kubernetes/commit/6dff95db7983bed3fc821e0c57431114310a9ca4) about eight hours ago, so maybe due to a non-standard/expected flow (but could still be incorrect)

another thing probably worth noting is that the v1.35.0-alpha.0 branch does not have this patch for [cmd/kube-proxy/app/server_linux.go](https://github.com/kubernetes/kubernetes/blob/v1.35.0-alpha.0/cmd/kube-proxy/app/server_linux.go), so we could potentially end up dropping it in v1.35 line

**Comment by Vyom-Yadav** [comment]
@prezha I'll manually add this tomorrow to the release notes

**Comment by prezha** [comment]
thanks @Vyom-Yadav !

regarding the other part, not sure if there's a process in place that will "forward-port" to v1.35.* or we need to apply the commit there too

**Comment by aojea** [comment]
> thanks @Vyom-Yadav !
> 
> regarding the other part, not sure if there's a process in place that will "forward-port" to v1.35.* or we need to apply the commit there too

it is already in master, f2170bc6c3d85e5fba50c75cac23aa79c1cbe827

**Comment by medyagh** [comment]
closes https://github.com/kubernetes/minikube/issues/21398#issuecomment-3215358001
