### PR TITLE
Unmount operation should not fail if volume is already unmounted

### LINKED ISSUE #37657: UnmountVolume failed for volume secret volume with "IsLikelyNotMountPoint(...): stat...no such file or directory"
In https://github.com/kubernetes/kubernetes/issues/37447 @yujuhong reported: 

> kubelet log is full of errors from the volume manager complaining about non-existent secrets:
> ```
> Nov 29 17:25:34 gke-test-cluster-1-default-pool-44d8ae2f-kpn9 kubelet[2228]: I1129 17:25:34.230648    2228 reconciler.go:188] UnmountVolume operation started for volume "kubernetes.io/secret/fee1aef7-b1ab-11e6-848f-42010a840181-default-token-r4hlp" (spec.Name: "default-token-r4hlp") from pod "fee1aef7-b1ab-11e6-848f-42010a840181" (UID: "fee1aef7-b1ab-11e6-848f-42010a840181").
> Nov 29 17:25:34 gke-test-cluster-1-default-pool-44d8ae2f-kpn9 kubelet[2228]: E1129 17:25:34.232112    2228 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/secret/fee1aef7-b1ab-11e6-848f-42010a840181-default-token-r4hlp\" (\"fee1aef7-b1ab-11e6-848f-42010a840181\")" failed. No retries permitted until 2016-11-29 17:27:34.232087714 +0000 UTC (durationBeforeRetry 2m0s). Error: UnmountVolume.TearDown failed for volume "kubernetes.io/secret/fee1aef7-b1ab-11e6-848f-42010a840181-default-token-r4hlp" (volume.spec.Name: "default-token-r4hlp") pod "fee1aef7-b1ab-11e6-848f-42010a840181" (UID: "fee1aef7-b1ab-11e6-848f-42010a840181") with: IsLikelyNotMountPoint("/var/lib/kubelet/pods/fee1aef7-b1ab-11e6-848f-42010a840181/volumes/kubernetes.io~secret/default-token-r4hlp"): stat /var/lib/kubelet/pods/fee1aef7-b1ab-11e6-848f-42010a840181/volumes/kubernetes.io~secret/default-token-r4hlp: no such file or directory
> ```
> /cc @kubernetes/sig-storage @saad-ali @jingxu97 to see what could've caused this.

This happened after kubelet restart.

We need to understand why this happens, if it is expected behavior or a bug.

CC @kubernetes/sig-storage

### PR DESCRIPTION
**Pull request by rkouj**
**What this PR does / why we need it**:
If the volume is already unmounted from the pod, another unmount operation should not fail.

fixes:  https://github.com/kubernetes/kubernetes/issues/37657

### CODE REVIEW

File: pkg/volume/aws_ebs/aws_ebs.go [hunk 1]
```diff
@@ -393,6 +393,10 @@ func (c *awsElasticBlockStoreUnmounter) TearDown() error {
 
 // Unmounts the bind mount
 func (c *awsElasticBlockStoreUnmounter) TearDownAt(dir string) error {
+	if _, err := os.Stat(dir); os.IsNotExist(err) {
```
Comment (saad-ali) [inline pkg/volume/aws_ebs/aws_ebs.go]: The behavior of most of the `TearDownAt(...)` method for most volumes is identical, and it is implemented correctly in the common `volume/util` file (See `UnmountPath(...)` in https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/util.go#L72). So instead of having it duplicated (with possible bugs like this, check all the existing `TearDownAt(...)` implementations, if they are not doing anything special/custom, just call the common util `UnmountPath(...)` method instead.

File: pkg/volume/host_path/host_path.go [hunk 2]
```diff
@@ -221,6 +222,10 @@ func (c *hostPathUnmounter) TearDown() error {
 
 // TearDownAt does not make sense for host paths - probably programmer error.
 func (c *hostPathUnmounter) TearDownAt(dir string) error {
+	if _, err := os.Stat(dir); os.IsNotExist(err) {
+		glog.Infof("The dir %v doesn't exist as it might have been unmounted by a previous unmount operation", dir)
+		return nil
+	}
 	return fmt.Errorf("TearDownAt() does not make sense for host paths")
```
Comment (gnufied) [inline pkg/volume/host_path/host_path.go]: Does it makes sense to print error here? Since teardown doesn't do anything anyways.

File: pkg/volume/quobyte/quobyte.go [hunk 3]
```diff
@@ -288,6 +288,10 @@ func (unmounter *quobyteUnmounter) TearDown() error {
 
 // We don't need to unmount on the host because only one mount exists
 func (unmounter *quobyteUnmounter) TearDownAt(dir string) error {
+	if _, err := os.Stat(dir); os.IsNotExist(err) {
+		glog.Infof("The dir %v doesn't exist as it might have been unmounted by a previous unmount operation", dir)
+		return nil
+	}
 	return nil
```
Comment (gnufied) [inline pkg/volume/quobyte/quobyte.go]: Same as HostPath perhaps.

File: pkg/volume/flocker/flocker.go [hunk 4]
```diff
@@ -421,6 +421,10 @@ func (c *flockerVolumeUnmounter) TearDown() error {
 
 // TearDownAt unmounts the bind mount
 func (c *flockerVolumeUnmounter) TearDownAt(dir string) error {
+	if _, err := os.Stat(dir); os.IsNotExist(err) {
+		glog.Infof("The dir %v doesn't exist as it might have been unmounted by a previous unmount operation", dir)
```
Comment (gnufied) [inline pkg/volume/flocker/flocker.go]: If we are going to use `Infof` here - we will be replacing one error message with another. It may be worth making this log only if log levels are higher?

File: pkg/volume/flocker/flocker.go [hunk 5]
```diff
@@ -421,6 +421,10 @@ func (c *flockerVolumeUnmounter) TearDown() error {
...
+		return nil
+	}
 	notMnt, err := c.mounter.IsLikelyNotMountPoint(dir)
```
Comment (gnufied) [inline pkg/volume/flocker/flocker.go]: If we see the code of `IsLikelyNotMountPoint` it looks like:

```
	// Check the directory exists
	if _, err = os.Stat(file); os.IsNotExist(err) {
		glog.V(5).Infof("findmnt: directory %s does not exist", file)
		return true, err
	}
``` 

So basically same check as being done here. Does it make sense to handle the returned error from the `IsLikelyNotMountPoint` check and log and return `nil` rather than doing this thing twice?

File: pkg/volume/aws_ebs/aws_ebs.go (hunk 1 above)
Comment (saad-ali) [inline pkg/volume/aws_ebs/aws_ebs.go]: You will also need to modify the `UnmountPath(...)` method. The very last line of the common `UnmountPath(...)` should be returning an error instead of `nil`, e.g. `return fmt.Errorf("Failed to unmount volume dir... volume will not be deleted")`. However UnmountPath and these implementations assume that the are running on a directory that was mounted to a different device, not bind mounts (`IsLikelyNotMountPoint(...)` doesn't work for bind mounts). So that sucks. AFAIK, `TearDownAt(...)` for attachable volumes is called to tear down bind mounts (global mount to pod mount). So we can either modify the `UnmountPath(...)` method to take a parameter and fork it's behavior based on if it is unmounting a bind mount or a device mount. Or even better, we can replace `IsLikelyNotMountPoint(...)` once and for all with a real `IsMountPoint()` implementation that looks at the mount table instead of comparing devices (we can talk about this in person, because it is a bigger project, but one that we'd like to do for other reasons anyway).

**Review by saad-ali — CHANGES_REQUESTED** [review]

File: pkg/volume/aws_ebs/aws_ebs.go (hunk 1 above)
Comment (rkouj) [inline pkg/volume/aws_ebs/aws_ebs.go]: Interested in the second approach. I'll start going through the code to make sense of what needs to be done.

**Comment by rkouj** [comment]
@saad-ali PTAL

I have changed the `TearDownAt()` implementations to point to the common UnmountPath() wherever the implementations are identical.

There are volume plugins that need a bit more investigation before making the change (plugins that have detach logic and count refs before performing the PR) and I can cover them in a separate PR.

TODO: to continue to figure out if we can get rid of first isLikelyNotMountPoint() call in UnmountPath()

**Comment by rkouj** [comment]
@k8s-bot kubemark e2e test this

File: pkg/util/mount/mount_linux.go [hunk 6]
```diff
@@ -160,10 +160,12 @@ func (*Mounter) List() ([]MountPoint, error) {
 
 // IsLikelyNotMountPoint determines if a directory is not a mountpoint.
 // It is fast but not necessarily ALWAYS correct. If the path is in fact
-// a bind mount from one part of a mount to another it will not be detected.
+// a bind mount from one part of a mount to another it will not be detected, unless
+// the source itself is a mount point.
```
Comment (saad-ali) [inline pkg/util/mount/mount_linux.go]: Let's leave the comment as is, the original version is more accurate.

**Review by saad-ali — CHANGES_REQUESTED** [review]
Minor comment, otherwise lgtm

File: pkg/util/mount/mount_linux.go (hunk 6 above)
Comment (rkouj) [inline pkg/util/mount/mount_linux.go]: Ack. Although the comment should involve something related to device names of the path and it's parent.

It's not immediately clear what the function does and it takes a while to understand why the bind mount check doesn't work and also why in some cases it does.

**Comment by rkouj** [comment]
@saad-ali PTAL

**Review by saad-ali — APPROVED** [review]
Thanks!

/lgtm
