### PR TITLE
Pod events fix

### LINKED ISSUE #137858: [InPlacePodVerticalScaling] Unnecessary ResizeCompleted event emitted when PLR FG is enabled
### What happened?

After I create a pod using a Kubernetes deployment in an empty Kind cluster, I see an in-place update event that seems unnecessary:

```bash
kubectl get events --watch -A

default              0s          Normal    ResizeCompleted           pod/hamster-deployment-57445548f6-r27rn          Pod resize completed: {"containers":[{"name":"hamster1","resources":{"requests":{"cpu":"10m","memory":"10Mi"}}},{"name":"hamster2","resources":{}},{"name":"hamster3","resources":{}}],"generation":1}
```

### What did you expect to happen?

I don't expect to see an in-place update after deploying the pod to the cluster.

### How can we reproduce it (as minimally and precisely as possible)?

```bash
KIND_VERSION="kindest/node:v1.35.0@sha256:452d707d4862f52530247495d180205e029056831160e22870e37e3f6c1ac31f"

kind create cluster --image=${KIND_VERSION} --config <(cat <<EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  "InPlacePodLevelResourcesVerticalScaling": true
  "NodeDeclaredFeatures": true
EOF
)
```

```yaml
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hamster
  name: hamster-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hamster
  template:
    metadata:
      labels:
        app: hamster
    spec:
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
      containers:
      - name: hamster1
        image: registry.k8s.io/pause:3.1
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
      - image: registry.k8s.io/pause:3.1
        name: hamster2
      - image: registry.k8s.io/pause:3.1
        name: hamster3
EOF
```

### Anything else we need to know?

* I don't have anything like Vertical Pod Autoscaler that should trigger in-place updates at any level (container or pod).
* related slack thread: https://kubernetes.slack.com/archives/C06FSK01BGU/p1773818099854269

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.35.1
Kustomize Version: v5.7.1
Server Version: v1.35.0
```

</details>

### Cloud provider

<details>
kind cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
$ uname -a
Linux 6.14.6-2-MANJARO #1 SMP PREEMPT_DYNAMIC Wed, 14 May 2025 14:56:34 +0000 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd://2.2.0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by ndixita**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

This PR has cherry-picked changes from https://github.com/kubernetes/kubernetes/pull/138045

When a pod is first created and goes through its first sync loop iteration, the actuated resources != allocated resources, because neither the containers nor pod cgroups have been set up yet. The pod-level resize in-progress check is erroneously reporting in this scenario that a resize is in progress; on the next sync loop iteration it corrects itself - however this results in an unnecessary ResizeCompleted event being emitted due to the status manager believing that the PodResizeInProgress condition has been flipped from true to false.

For container-level resize, we have a check to prevent this exact circumstance here: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L2198-L2200.

This PR adds an analogous check for pod-level resize, where a pod-level resize in-progress check reports false if none of the containers are running. I have confirmed the fix using the reproduction steps reported in https://github.com/kubernetes/kubernetes/issues/137858.

#### Which issue(s) this PR is related to:

Fixes https://github.com/kubernetes/kubernetes/issues/137858.

#### Special notes for your reviewer:

This was deemed important for 1.36 because it impacts every pod that is created with pod-level resources, and both features are now beta and enabled by default.

#### Does this PR introduce a user-facing change?

```release-note
Fix erroneously reporting a pod-level resize in progress on pod creation when InPlacePodLevelResourcesVerticalScaling is enabled.
```

/sig node

/priority important-soon

### CODE REVIEW

File: test/e2e/common/node/pod_level_resources_resize.go [hunk 1]
```diff
@@ -642,6 +643,40 @@ func doPodLevelResourcesMemoryLimitDecreaseTest(f *framework.Framework) {
...
+
+		containers := []podresize.ResizableContainerInfo{{
+			Name: "c1",
+		}}
+
+		ginkgo.By("creating and verifying pod")
+		testPod := createAndVerifyPodPLR(ctx, f, podClient, containers, originalPLR, true)
+
+		ginkgo.By("verifying no ResizeCompleted event was emitted")
+		events, err := f.ClientSet.CoreV1().Events(f.Namespace.Name).List(ctx, metav1.ListOptions{})
```
Comment (tallclair) [inline test/e2e/common/node/pod_level_resources_resize.go]:
```suggestion
		events, err := f.ClientSet.CoreV1().Events(f.Namespace.Name).Search(ctx, scheme.Scheme, testPod)
```

File: test/e2e/common/node/pod_level_resources_resize.go [hunk 2]
```diff
@@ -642,6 +643,40 @@ func doPodLevelResourcesMemoryLimitDecreaseTest(f *framework.Framework) {
...
+		framework.ExpectNoError(err, "failed to list events")
+
+		for _, event := range events.Items {
+			if event.InvolvedObject.UID == testPod.UID && event.Reason == "ResizeCompleted" {
```
Comment (tallclair) [inline test/e2e/common/node/pod_level_resources_resize.go]: nit: use the constant (also, you can drop the UID check with the search change above)
```suggestion
			if event.Reason == events.ResizeCompleted {
```

File: test/e2e/common/node/pod_level_resources_resize.go [hunk 3]
```diff
@@ -642,6 +643,40 @@ func doPodLevelResourcesMemoryLimitDecreaseTest(f *framework.Framework) {
...
+				framework.Failf("Unexpected ResizeCompleted event found for pod %s: %s", testPod.Name, event.Message)
+			}
+		}
+	})
```
Comment (tallclair) [inline test/e2e/common/node/pod_level_resources_resize.go:678]: We don't actually have any positive coverage of the ResizeCompleted event. Perform a resize after verifying the lack of event on create, and ensure that an event is emitted then.

**Review by tallclair — COMMENTED** [review]
Thanks for picking this up!

File: test/e2e/common/node/pod_level_resources_resize.go (hunk 3 above)
Comment (SergeyKanzhelev) [reply test/e2e/common/node/pod_level_resources_resize.go:678]: it is discouraged to have tests relying on Events since they are not guaranteed to be delivered. Perhaps we can discuss this coverage in a separate PR?

Comment (tallclair) [reply test/e2e/common/node/pod_level_resources_resize.go:678]: Sure, sounds good. Let's keep the negative test though, since that won't flake if the events fail to deliver.

File: test/e2e/common/node/pod_level_resources_resize.go [hunk 4]
```diff
@@ -642,6 +645,39 @@ func doPodLevelResourcesMemoryLimitDecreaseTest(f *framework.Framework) {
...
+		ginkgo.By("creating and verifying pod")
+		testPod := createAndVerifyPodPLR(ctx, f, podClient, containers, originalPLR, true)
+
+		ginkgo.By("verifying no ResizeCompleted event was emitted")
+		events, err := f.ClientSet.CoreV1().Events(f.Namespace.Name).SearchWithContext(ctx, scheme.Scheme, testPod)
+		framework.ExpectNoError(err, "failed to list events")
+
+		for _, event := range events.Items {
+			if event.Reason == kubeletevents.ResizeCompleted {
+				framework.Failf("Unexpected ResizeCompleted event found for pod %s: %s", testPod.Name, event.Message)
```
Comment (tallclair) [inline test/e2e/common/node/pod_level_resources_resize.go]: nit: include the full event in the failure message

Comment (ndixita) [reply test/e2e/common/node/pod_level_resources_resize.go]: Done

Comment (ndixita) [reply test/e2e/common/node/pod_level_resources_resize.go]: done
