### PR TITLE
Report actionable error when GC fails due to disk pressure

### LINKED ISSUE #71869: `failed to garbage collect required amount of images. Wanted to free 473842483 bytes, but freed 0 bytes`
**What happened**: I've been seeing a number of evictions recently that appear to be due to disk pressure:
```yaml
$$$ kubectl get pod kumo-go-api-d46f56779-jl6s2 --namespace=kumo-main -o yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: 2018-12-06T10:05:25Z
  generateName: kumo-go-api-d46f56779-
  labels:
    io.kompose.service: kumo-go-api
    pod-template-hash: "802912335"
  name: kumo-go-api-d46f56779-jl6s2
  namespace: kumo-main
  ownerReferences:
  - apiVersion: extensions/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: kumo-go-api-d46f56779
    uid: c0a9355e-f780-11e8-b336-42010aa80057
  resourceVersion: "11617978"
  selfLink: /api/v1/namespaces/kumo-main/pods/kumo-go-api-d46f56779-jl6s2
  uid: 7337e854-f93e-11e8-b336-42010aa80057
spec:
  containers:
  - env:
    - redacted...
    image: gcr.io/<redacted>/kumo-go-api@sha256:c6a94fc1ffeb09ea6d967f9ab14b9a26304fa4d71c5798acbfba5e98125b81da
    imagePullPolicy: Always
    name: kumo-go-api
    ports:
    - containerPort: 5000
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-t6jkx
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: gke-kumo-customers-n1-standard-1-pree-0cd7990c-jg9s
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-t6jkx
    secret:
      defaultMode: 420
      secretName: default-token-t6jkx
status:
  message: 'The node was low on resource: nodefs.'
  phase: Failed
  reason: Evicted
  startTime: 2018-12-06T10:05:25Z
```
Taking a look at `kubectl get events`, I see these warnings:
```
$$$ kubectl get events
LAST SEEN   FIRST SEEN   COUNT     NAME                                                                   KIND      SUBOBJECT   TYPE      REASON          SOURCE                                                         MESSAGE
2m          13h          152       gke-kumo-customers-n1-standard-1-pree-0cd7990c-jg9s.156e07f40b90ed91   Node                  Warning   ImageGCFailed   kubelet, gke-kumo-customers-n1-standard-1-pree-0cd7990c-jg9s   (combined from similar events): failed to garbage collect required amount of images. Wanted to free 473948979 bytes, but freed 0 bytes
37m         37m          1         gke-kumo-customers-n1-standard-1-pree-0cd7990c-jg9s.156e3127ebc715c3   Node                  Warning   ImageGCFailed   kubelet, gke-kumo-customers-n1-standard-1-pree-0cd7990c-jg9s   failed to garbage collect required amount of images. Wanted to free 473674547 bytes, but freed 0 bytes
```
Digging a bit deeper:
```yaml
$$$ kubectl get event gke-kumo-customers-n1-standard-1-pree-0cd7990c-jg9s.156e07f40b90ed91 -o yaml
apiVersion: v1
count: 153
eventTime: null
firstTimestamp: 2018-12-07T11:01:06Z
involvedObject:
  kind: Node
  name: gke-kumo-customers-n1-standard-1-pree-0cd7990c-jg9s
  uid: gke-kumo-customers-n1-standard-1-pree-0cd7990c-jg9s
kind: Event
lastTimestamp: 2018-12-08T00:16:09Z
message: '(combined from similar events): failed to garbage collect required amount
  of images. Wanted to free 474006323 bytes, but freed 0 bytes'
metadata:
  creationTimestamp: 2018-12-07T11:01:07Z
  name: gke-kumo-customers-n1-standard-1-pree-0cd7990c-jg9s.156e07f40b90ed91
  namespace: default
  resourceVersion: "381976"
  selfLink: /api/v1/namespaces/default/events/gke-kumo-customers-n1-standard-1-pree-0cd7990c-jg9s.156e07f40b90ed91
  uid: 65916e4b-fa0f-11e8-ae9a-42010aa80058
reason: ImageGCFailed
reportingComponent: ""
reportingInstance: ""
source:
  component: kubelet
  host: gke-kumo-customers-n1-standard-1-pree-0cd7990c-jg9s
type: Warning
```
There's actually remarkably little here. This message doesn't say anything regarding why ImageGC was initiated or why it was unable recover more space.

**What you expected to happen**: Image GC to work correctly, or at least fail to schedule pods onto nodes that do not have sufficient disk space.

**How to reproduce it (as minimally and precisely as possible)**: Run and stop as many pods as possible on a node in order to encourage disk pressure. Then observe these errors.

**Anything else we need to know?**: n/a

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.7-gke.11", GitCommit:"fa90543563c9cfafca69128ce8cd9ecd5941940f", GitTreeState:"clean", BuildDate:"2018-11-08T20:22:21Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GKE
- OS (e.g. from /etc/os-release): I'm running macOS 10.14, nodes are running Container-Optimized OS (cos).
- Kernel (e.g. `uname -a`): `Darwin D-10-19-169-80.dhcp4.washington.edu 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64`
- Install tools: n/a
- Others: n/a

/kind bug

### PR DESCRIPTION
**Pull request by drigz**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

When the image GC fails to free enough space due to disk pressure, the user-visible event it generates is misleading (see #71869) - the technical detail leads operators to suspect GC problems. This PR makes the message actionable by focusing on the disk pressure.

I had hoped to include the total disk space consumed by images that cannot be collected, to help operators quickly determine if disk pressure is caused by a large number of active images or by other files on the node, but this is blocked because the CRI API doesn't reveal the total disk use (depending on the runtime it has either the compressed or uncompressed space: #120698).

#### Which issue(s) this PR is related to:

Fixes #71869

#### Special notes for your reviewer:

See individual commits for a breakdown into:

1. add test for user-visible message
2. rephrase message to focus on disk usage (saves user from running df -h)

Regarding formatSize(): I considered using resource.NewQuantity but it wasn't clear how to round the size appropriately, and it can't generate non-whole numbers like `12.3 G`.

#### Does this PR introduce a user-facing change?
```release-note
When image garbage collection is unable to free enough disk space, the FreeDiskSpaceFailed warning event is now more actionable. Example: `Insufficient free disk space on the node's image filesystem (95.0% of 10.0 GiB used). Failed to free sufficient space by deleting unused images. Consider resizing the disk or deleting unused files.`
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

None - although I considered collecting the suggested fixes from #71869 (kill processes that are holding deleted files open, delete orphaned volumes, etc) I decided this would easily become crufty with irrelevant steps.

### CODE REVIEW

**Comment by drigz** [comment]
@haircommander I'm still figuring out how to manually test my kubelet change in a real cluster (just ran unit tests so far) but in the meantime, can you /ok-to-test this? Thanks in advance!

**Comment by drigz** [comment]
Looks like this exposes a bug where an error message is used as format string: (`%!o(MISSING)`)

```
Warning  FreeDiskSpaceFailed      24s    kubelet          Insufficient free disk space on the node's image filesystem (53.5% of 976.2 GiB used). Failed to free sufficient space by deleting unused images (429.0 MiB used for active images). Consider resizing the disk or deleting unused files.
  Warning  ImageGCFailed            24s    kubelet          Insufficient free disk space on the node's image filesystem (53.5%!o(MISSING)f 976.2 GiB used). Failed to free sufficient space by deleting unused images (429.0 MiB used for active images). Consider resizing the disk or deleting unused files.
```

Should be easy to fix by adding `"%s",` but is it WAI that both FreeDiskSpaceFailed and ImageGCFailed are generated in this case? 

I'm also unsure if the `XX.X GB used for active images` is adding value here since for containerd it's only the compressed size (https://github.com/containerd/containerd/issues/9261) and for other runtimes it's uncompressed size, but in both cases it's an underestimate, and the CRI API doesn't let us report the true size:

```
root@kind-control-plane:/# du -sh /var/lib/containerd/* | sort -h
[snip: small directories]
1.6M    /var/lib/containerd/io.containerd.metadata.v1.bolt
421M    /var/lib/containerd/io.containerd.content.v1.content
702M    /var/lib/containerd/io.containerd.snapshotter.v1.overlayfs
```

That said, if it's less than 0.1 * disk size it's still a pointer that "too many/big images" is not the cause, whereas if it's greater than 0.3 * disk size it might suggest "too many/big images" is the cause. But not sure there's a good way to suggest that in the error message...

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -1561,7 +1561,7 @@ func (kl *Kubelet) StartGarbageCollection() {
 			if prevImageGCFailed {
 				klog.ErrorS(err, "Image garbage collection failed multiple times in a row")
 				// Only create an event for repeated failures
-				kl.recorder.Eventf(kl.nodeRef, v1.EventTypeWarning, events.ImageGCFailed, err.Error())
+				kl.recorder.Eventf(kl.nodeRef, v1.EventTypeWarning, events.ImageGCFailed, "%s", err.Error())
```
Comment (kannon92) [inline pkg/kubelet/kubelet.go]: Why was this change added? Was the error not reported?

**Comment by kannon92** [comment]
/ok-to-test

Please sign the CLA.

Two of your commits have no author on it which may need to be fixed before merge.

File: pkg/kubelet/kubelet.go (hunk 1 above)
Comment (drigz) [reply pkg/kubelet/kubelet.go]: The ImageGCFailed event had the following format problem in its message: `53.5%!o(MISSING)f 976.2 GiB used` because the error contained a `%` character and was incorrectly used as a format string.

**Comment by drigz** [comment]
> Two of your commits have no author on it which may need to be fixed before merge.

Thanks, sorry for the noise, rookie error!

File: pkg/kubelet/images/image_gc_manager.go [hunk 2]
```diff
@@ -385,21 +385,28 @@ func (im *realImageGCManager) GarbageCollect(ctx context.Context, beganGC time.T
...
 		if freed < amountToFree {
-			err := fmt.Errorf("Failed to garbage collect required amount of images. Attempted to free %d bytes, but only found %d bytes eligible to free.", amountToFree, freed)
-			im.recorder.Eventf(im.nodeRef, v1.EventTypeWarning, events.FreeDiskSpaceFailed, err.Error())
-			return err
+			// This usually means the disk is full for reasons other than container
+			// images, such as logs, volumes, or other files. However, it could also
+			// be due to an unusually large number or size of in-use container images.
+			message := fmt.Sprintf("Insufficient free disk space on the node's image filesystem (%.1f%% of %s used). "+
+				"Failed to free sufficient space by deleting unused images. "+
+				"Consider resizing the disk or deleting unused files.",
```
Comment (kannon92) [inline pkg/kubelet/images/image_gc_manager.go]: I don't really think we should mention "resizing" the disk.

This is not that helpful to an end-user as in many cases it is not easy to "resize" a disk.

For fedora/fcos, I don't think it is possible to resize /var on an existing node.

If you are on a cloud instance, you could provision a new disk and remount but that is very different.

Anyway, maybe you could just suggest taking a look at other resources on this node as you mention in your comment.

Comment (drigz) [reply pkg/kubelet/images/image_gc_manager.go]: Someone called it out on the original issue ([comment](https://github.com/kubernetes/kubernetes/issues/71869#issuecomment-950114855)):

> I changed Node disk size from 10 GiB to 20GiB and error didn't appeard

which is why I added it here. However, it's implicit when you see an error like `95% of 10GB used` that you could just bump the disk size, so perhaps it's not needed.

> you could just suggest taking a look at other resources on this node

I'm assuming you mean the code comment here ("This usually means the disk is full for reasons other than container images, such as logs, volumes, or other files. However, it could also be due to an unusually large number or size of in-use container images."). I've changed to:

```
Investigate disk usage, as it could be used by active images, logs, volumes, or other data.
```

This strikes me as a necessary first step, and immediate mitigation is probably not the operator's priority because this is just a "warning".

Comment (kannon92) [reply pkg/kubelet/images/image_gc_manager.go]: Thanks! Lgtm.

Comment (drigz) [reply pkg/kubelet/images/image_gc_manager.go]: New message in https://github.com/kubernetes/kubernetes/pull/132578/commits/a1e19a0e6928d39b7a40707f4b8fc5af405baed6.

**Comment by drigz** [comment]
@kannon92 Thanks for the reviews! I think I just need the lgtm and/or approved label as the next step? Or should I wait for matthyx to review?

File: pkg/kubelet/images/image_gc_manager.go [hunk 3]
```diff
@@ -576,6 +583,31 @@ func (im *realImageGCManager) imagesInEvictionOrder(ctx context.Context, freeTim
...
+	case size < MiB:
+		return fmt.Sprintf("%.1f KiB", size/KiB)
+	case size < GiB:
+		return fmt.Sprintf("%.1f MiB", size/MiB)
+	case size < TiB:
+		return fmt.Sprintf("%.1f GiB", size/GiB)
+	default:
+		return fmt.Sprintf("%.1f TiB", size/TiB)
+	}
+}
```
Comment (bart0sh) [inline pkg/kubelet/images/image_gc_manager.go:609]: This API is looks too generic to be in this module. Can it be moved to more generic location?
Alternatively, can resource.Quantity.String() be used instead?

Comment (drigz) [reply pkg/kubelet/images/image_gc_manager.go:609]: I considered using resource.NewQuantity but it wasn't clear how to round the size appropriately, and it can't generate non-whole numbers like 12.3 G.

For such a short function I'd also argue "A little copying is better than a little dependency." - but I'm happy to move it to a util library if you can suggest where it should go, I'm not familiar enough with the codebase to guess myself.

Comment (bart0sh) [reply pkg/kubelet/images/image_gc_manager.go:609]: I'd probably put it into pkg/util, but I'm not sure it will be accepted. @liggitt WDYT?

**Comment by drigz** [comment]
@kannon92 Should I wait for input from Jordan on Ed's refactoring proposal? To me it seems like it's less important than improving the error message but I'm biased as I wrote the PR. Or should I look for lgtm/approval from you (and/or matthyx) and then treat the refactor as a followup?

Sorry to be annoying, I'm just hoping not to be the 8th assignee who gives up on the linked issue!

**Comment by drigz** [comment]
@matthyx Are you able to take a look at this PR? (71 lines) @kannon92 wrote "Lgtm" in https://github.com/kubernetes/kubernetes/pull/132578#discussion_r2173734944 but it's not clear to me if that applied to the whole PR and it doesn't unblock merge.

@bart0sh's comment doesn't seem like it should block merge to me as it's just a suggestion for a refactor that could also be done when a second consumer for the helper is added.

EDIT: I also have LGTM for the new error message on the issue: https://github.com/kubernetes/kubernetes/issues/71869#issuecomment-2992352482

File: pkg/kubelet/images/image_gc_manager.go [hunk 4]
```diff
@@ -385,21 +385,28 @@ func (im *realImageGCManager) GarbageCollect(ctx context.Context, beganGC time.T
 	}
 
 	// If over the max threshold, free enough to place us at the lower threshold.
-	usagePercent := 100 - int(available*100/capacity)
-	if usagePercent >= im.policy.HighThresholdPercent {
+	usagePercent := 100 - float64(available)*100/float64(capacity)
```
Comment (kannon92) [inline pkg/kubelet/images/image_gc_manager.go]: This seems suspect to me.

Why did you make this change?

Comment (kannon92) [reply pkg/kubelet/images/image_gc_manager.go]: It doesn't really make sense to convert available or capacity to float64 when they are integers.

Was there an issue with the type casting?

Comment (kannon92) [reply pkg/kubelet/images/image_gc_manager.go]: > This means any fractional portion is truncated, so a value like 69.9 becomes 69.

I think both are not right but am still curious why make the change here.

Comment (drigz) [reply pkg/kubelet/images/image_gc_manager.go]: Thank you for taking another look! The intent is to print a message like `95.0% of 10.0 GiB used`. To do that I need to keep the fractional element a little longer than the previous code, which truncated to `95` immediately.

The two casts are required to keep the fractional result: https://stackoverflow.com/a/20571539 (or https://go.dev/play/p/mpJAapjzYJf if you don't trust the SO answer)

I could also use:

`usagePercent := 100 - float64(available*100)/float64(capacity)`

or I could simplify the code and change the message:

 `95% of 10 GiB used`

Which do you prefer?

Comment (drigz) [reply pkg/kubelet/images/image_gc_manager.go]: If it helps, the previous int() cast didn't serve to truncate the fractional portion - it was already truncated by the int64 division - but to truncate to `int` before comparing to `im.policy.HighThresholdPercent`.

I guess that you're trying to convince yourself that this change to the message will not change the triggering logic of the GC through some weird truncation behavior. For example if the disk is >9PB, the numbers will be slightly truncated on conversion to float64 and the result could differ. But I recognize that this handwaving is not so compelling, so I'll restore the original integer division and reduce the precision of the error message.

Comment (kannon92) [reply pkg/kubelet/images/image_gc_manager.go]: Thanks!

Yea I just don't want a subtle difference to pop up.

File: pkg/kubelet/images/image_gc_manager.go (hunk 3 above)
Comment (kannon92) [reply pkg/kubelet/images/image_gc_manager.go:609]: I think this is fine for now and if there are more usage of it we can move it elsewhere.

**Review by kannon92 — COMMENTED** [review]
/lgtm

/assign @mrunalp @dchen1107 @SergeyKanzhelev

**Comment by kannon92** [comment]
It is code freeze this week (may already be), so this may not get in this cycle.

Sorry for the late review.

**Comment by kannon92** [comment]
Can you squash your commits?

**Comment by drigz** [comment]
> It is code freeze this week (may already be), so this may not get in this cycle.

NP, absolutely no rush on this item.

> Can you squash your commits?

Done, thanks!

File: pkg/kubelet/kubelet.go (hunk 1 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/kubelet.go]: let's use `kl.recorder.Event` instead then

File: pkg/kubelet/images/image_gc_manager.go [hunk 5]
```diff
@@ -391,15 +391,22 @@ func (im *realImageGCManager) GarbageCollect(ctx context.Context, beganGC time.T
...
-			err := fmt.Errorf("Failed to garbage collect required amount of images. Attempted to free %d bytes, but only found %d bytes eligible to free.", amountToFree, freed)
-			im.recorder.Eventf(im.nodeRef, v1.EventTypeWarning, events.FreeDiskSpaceFailed, err.Error())
-			return err
+			// This usually means the disk is full for reasons other than container
+			// images, such as logs, volumes, or other files. However, it could also
+			// be due to an unusually large number or size of in-use container images.
+			message := fmt.Sprintf("Insufficient free disk space on the node's image filesystem (%d%% of %s used). "+
+				"Failed to free sufficient space by deleting unused images. "+
+				"Investigate disk usage, as it could be used by active images, logs, volumes, or other data.",
+				usagePercent, formatSize(capacity))
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/images/image_gc_manager.go]: the formatting is great for human. Would user ever need an actual bytes value to compare with some metrics?

File: pkg/kubelet/images/image_gc_manager.go [hunk 6]
```diff
@@ -391,15 +391,22 @@ func (im *realImageGCManager) GarbageCollect(ctx context.Context, beganGC time.T
...
 		im.runPostGCHooks(remainingImages, freeTime)
 
 		if freed < amountToFree {
-			err := fmt.Errorf("Failed to garbage collect required amount of images. Attempted to free %d bytes, but only found %d bytes eligible to free.", amountToFree, freed)
-			im.recorder.Eventf(im.nodeRef, v1.EventTypeWarning, events.FreeDiskSpaceFailed, err.Error())
-			return err
+			// This usually means the disk is full for reasons other than container
+			// images, such as logs, volumes, or other files. However, it could also
+			// be due to an unusually large number or size of in-use container images.
+			message := fmt.Sprintf("Insufficient free disk space on the node's image filesystem (%d%% of %s used). "+
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/images/image_gc_manager.go:404]: let's keep the information on how much we believe we freed

Comment (drigz) [reply pkg/kubelet/images/image_gc_manager.go:404]: I have added `(XXX freed)` to the error as requested - but can I ask why? Under disk pressure the event is generated every five minutes, so this will either be:

- the majority of the time[1]: the node is in steady state, it'll say `(0 B freed)` because the same images are in-use as the last time it ran GC
- rarely: it'll either print the total compressed or uncompressed size of the images (ie underestimating the amount of freed space) that became unused since the last GC attempt, so somewhere between 0 and 15% of the disk size

I can't think of a case where this is useful, except perhaps for an experienced operator of a super-high-churn cluster who knows that every five minutes, hundreds of MB of images should become unused, so if they see this event with less than that, they deduce that somehow the churn rate of their cluster has changed.

I hope it doesn't seem petty to argue about this. I'm trying to make the error easier for inexperienced users to understand, and IMO adding `(0 B freed)` or `but freed 0 bytes` might make them think something is wrong with the GC when it's not.

[1]:  At least, every instance I found I Stack Overflow after checking the first 10 results had `but freed 0 bytes` or `but only found 0 bytes eligible to free`, which sounds very "broken" and I believe this is why people go down the "how can I debug the GC" rabbit hole

File: pkg/kubelet/images/image_gc_manager.go (hunk 5 above)
Comment (drigz) [reply pkg/kubelet/images/image_gc_manager.go]: Not sure if this question is for me or @kannon92 but I'll take a stab:

IIUC event messages are for humans to read and are normally batched by kubectl, so when the number varies over the different GC rounds every 5 minutes, it'll only show the latest one. But even if the user wants to know one of the following, there are better / more realistic ways for them to find it out, they both would be generated consistently regardless of whether the node is under disk pressure:

- how has my disk usage varied over time?
  - just check node-exporter metrics or similar
- how many images become unused each day?
  - check image GC text logs in the kubelet logs

I guess from the review comments from you and the other reviewer that this component suffers from Hyrum's Law, so if it's too dangerous to change an event description because someone intentionally keeps the node under disk pressure so they can parse this event and measure disk usage + GC history, then we should probably just close the linked issue as infeasible. I don't want to cause an outage for someone just to make one message more beginner-friendly...

**Comment by drigz** [comment]
/retest

Filed https://github.com/kubernetes/kubernetes/issues/133249 for the flake.

File: pkg/kubelet/images/image_gc_manager.go (hunk 6 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/images/image_gc_manager.go:404]: Amount freed is not super precise. So I agree with your reasoning. However I believe the ability to distinguish the difference of zero or non-zero sizes is important. It distinguish constant churn situation and kubelet "believes" it freed something (while runtime may be "broken") vs. there is nothing to free - every image is in-use.

File: pkg/kubelet/images/image_gc_manager.go (hunk 5 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/images/image_gc_manager.go]: I was mostly thinking of situation when user will notice a small increase in sizes from one log message to another. It will indicate something else is using memory. But yes, it feels like abusive use of a log message instead of finding the proper metric. This is why I think human-friendly value with the original value in brackets would be a good least-breaking alternative.

I am open to be convinced that this is not needed, reviewers, please comment

Comment (kannon92) [reply pkg/kubelet/images/image_gc_manager.go]: > hat this component suffers from Hyrum's Law

I don't think this applies here but I am worried about any changes that are not directly related to making the logs easier to read.

Plus it is subjective.

File: pkg/kubelet/kubelet.go (hunk 1 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/kubelet.go]: ping on this. There is an `Event` (without `f`) that can be used instead

Comment (drigz) [reply pkg/kubelet/kubelet.go]: Done, thanks for the ping and apologies for missing the comment the first time.

File: pkg/kubelet/images/image_gc_manager.go (hunk 5 above)
Comment (drigz) [reply pkg/kubelet/images/image_gc_manager.go]: > This is why I think human-friendly value with the original value in brackets would be a good least-breaking alternative.

I've changed to raw bytes for the "freed" message to reduce the delta and because I think "freed 0 bytes" is more readable than "0 B freed". The delta in the latest commit:

- **before**: `failed to garbage collect required amount of images. Wanted to free 473948979 bytes, but freed 0 bytes`
- **after**: `Insufficient free disk space on the node's image filesystem (95.0% of 10.0 GiB used). Failed to free sufficient space by deleting unused images (freed 0 bytes). Consider resizing the disk or deleting unused files.`

ie the changes are:
- replacing "wanted to free 473948979 bytes" with `95.0% of 10.0 GiB used`
  - IMO this is more readable because it maps to what the user knows from `df -h` and tells them _"your disk is almost full!"_, so I'd lean towards excluding the raw bytes number here but can restore it if you prefer
- replacing `but freed 0 bytes` with `(freed 0 bytes)`
  - not much change in readability as this is normally 0, I'm hoping the parens and removing "but" draw less attention from inexperienced users

LMK if you prefer `(95.0% of 10.0 GiB used)`, `(95.0% of 10.0 GiB used, wanted to free 473948979 bytes)`, or something else.

> I don't think this applies here but I am worried about any changes that are not directly related to making the logs easier to read.

Not sure I understand this. As I understand it, removing 9 digit numbers and the internals of the GC algorithm (wanted to free X, freed Y) are required to make the message more readable and convey the point _"your disk is almost full!"_. I believe these details make the user think the unused images / GC algorithm are to blame, which is not the case (GC worked as intended in this codepath).

But maybe I've misunderstood and you're referring to something other than the replacements above?

File: pkg/kubelet/images/image_gc_manager_test.go [hunk 7]
```diff
@@ -678,19 +678,45 @@ func TestGarbageCollectNotEnoughFreed(t *testing.T) {
...
+		makeImage(0, imageSize),
 	}
 
-	assert.Error(t, manager.GarbageCollect(ctx, time.Now()))
+	err := manager.GarbageCollect(ctx, time.Now())
+	require.Error(t, err)
+
+	// Check that a warning event was sent
+	expectedEvent := "Warning FreeDiskSpaceFailed Insufficient free disk space on the node's image filesystem" +
+		" (95% of 10.0 GiB used). Failed to free sufficient space by deleting unused images (freed 524288000 bytes)." +
```
Comment (bart0sh) [inline pkg/kubelet/images/image_gc_manager_test.go:712]: Would it make sense to use `imageSize` here instead of its hardcoded value?

File: pkg/kubelet/images/image_gc_manager.go (hunk 5 above)
Comment (kannon92) [reply pkg/kubelet/images/image_gc_manager.go]: I mean the full process of review. I think this is more focused now.

File: pkg/kubelet/images/image_gc_manager_test.go (hunk 7 above)
Comment (drigz) [reply pkg/kubelet/images/image_gc_manager_test.go:712]: I prefer to keep the assertions as close to the behavior the user will observe as possible, otherwise the test code ends up just duplicating the original implementation (including its bugs). This way it's obvious that large sizes are meant to be printed as long numbers with no commas and if someone changes the formatting directive, they'll have to change the expected result too.

File: pkg/kubelet/images/image_gc_manager.go (hunk 5 above)
Comment (drigz) [reply pkg/kubelet/images/image_gc_manager.go]: @SergeyKanzhelev Do you need any more info from me to choose between the options listed above? Or is the current (`Insufficient free disk space on the node's image filesystem (95.0% of 10.0 GiB used). Failed to free sufficient space by deleting unused images (freed 0 bytes). Consider resizing the disk or deleting unused files.`) fine?

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

once branch is opened we can take this. Thanks, I hope it will help people to be less confused by this log

**Comment by drigz** [comment]
> once branch is opened we can take this. Thanks, I hope it will help people to be less confused by this log

Thank you for taking the time to look at this - from this and other PRs I'm starting to get a taste of the complexity of what you have to review, so I appreciate it.
