### PR TITLE
Readable error message on the plugin configs of the removed plugins

### LINKED ISSUE #103478: scheduler: failed with unreadable error message with v1beta2 configuration
#### What happened:
Have a legacy scheduler config, upgrade to v1beta2 since we are at v1beta2 now, 

```
  plugins:
	...
    score:
      disabled:
        - name: InterPodAffinity
      enabled:
        - name: InterPodAffinity
          weight: 2
	...
  pluginConfig:  
  - args:
        apiVersion: kubescheduler.config.k8s.io/v1beta2
        resources:
        - name: hugepages
          weight: 1
      name: NodeResourcesLeastAllocated
```

scheduler failed to start with some unreadable raw data, 
```
profiles[0].pluginConfig[0].args: Invalid value: runtime.Unknown{TypeMeta:runtime.TypeMeta{APIVersion:"", Kind:""}, Raw:[]uint8{0x7b, 0x22, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3a, 0x22, 0x6b, 0x75, 0x62, 0x65, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x6b, 0x38, 0x73, 0x2e, 0x69, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x32, 0x22, 0x2c, 0x22, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x3a, 0x5b, 0x7b, 0x22, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x22, 0x68, 0x75, 0x67, 0x65, 0x70, 0x61, 0x67, 0x65, 0x73, 0x2d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x31, 0x22, 0x2c, 0x22, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x3a, 0x31, 0x7d, 0x5d, 0x7d}, ContentEncoding:"", ContentType:"application/json"}: has to match plugin args
Process 1130 has exited with status 1
```

#### What you expected to happen:
accurate and readable error message.

#### How to reproduce it (as minimally and precisely as possible):
config scheduler config like what has been said above.

#### Environment:
- Kubernetes version (use `kubectl version`): latest.
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): all
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig scheduling
/assign

### PR DESCRIPTION
**Pull request by chendave**
Several plugins are removed in the v1beta2, but the legacy scheduler
config would still have the plugin configs of those removed plugins.

It was throwing raw byte data when those plugin configs are still in
place which will hard to read and understand.

Fix it by checking the removed plugin config before the validation of
the plugin args.

Signed-off-by: Dave Chen <dave.chen@arm.com>

/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/103478

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig scheduling

### CODE REVIEW

**Comment by chendave** [comment]
/remove-kind api-change   (this should be just a validation)

/cc @ahg-g @alculquicondor

File: pkg/scheduler/apis/config/validation/validation.go [hunk 1]
```diff
@@ -249,6 +224,36 @@ func validatePluginConfig(path *field.Path, apiVersion string, profile *config.K
...
+	for i := range profile.PluginConfig {
+		pluginConfigPath := path.Child("pluginConfig").Index(i)
+		name := profile.PluginConfig[i].Name
+		args := profile.PluginConfig[i].Args
+		if seenPluginConfig.Has(name) {
+			errs = append(errs, field.Duplicate(pluginConfigPath, name))
+		} else {
+			seenPluginConfig.Insert(name)
+		}
+		if removed, removedVersion := isPluginRemoved(apiVersion, name); removed {
```
Comment (chendave) [inline pkg/scheduler/apis/config/validation/validation.go:241]: primarily,  this line is added to check the removed plugin.

File: pkg/scheduler/apis/config/validation/validation.go [hunk 2]
```diff
@@ -201,31 +201,6 @@ func validatePluginConfig(path *field.Path, apiVersion string, profile *config.K
...
-		if seenPluginConfig.Has(name) {
-			errs = append(errs, field.Duplicate(pluginConfigPath, name))
-		} else {
-			seenPluginConfig.Insert(name)
-		}
-		if validateFunc, ok := m[name]; ok {
-			// type mismatch, no need to validate the `args`.
-			if reflect.TypeOf(args) != reflect.ValueOf(validateFunc).Type().In(1) {
-				errs = append(errs, field.Invalid(pluginConfigPath.Child("args"), args, "has to match plugin args"))
-				return errs
```
Comment (alculquicondor) [inline pkg/scheduler/apis/config/validation/validation.go:218]: why not just remove this return? We simply shouldn't just return in API validation.

Comment (chendave) [reply pkg/scheduler/apis/config/validation/validation.go:218]: because the following couple of lines are calling the validation func to validate the args, will adjust the logic a little bit.

Comment (chendave) [reply pkg/scheduler/apis/config/validation/validation.go:218]: but I think it might still better to validate the plugin config after the validation of the removed plugins, what do you think?

File: pkg/scheduler/apis/config/validation/validation.go [hunk 3]
```diff
@@ -249,6 +224,34 @@ func validatePluginConfig(path *field.Path, apiVersion string, profile *config.K
...
+			errs = append(errs, field.Duplicate(pluginConfigPath, name))
+		} else {
+			seenPluginConfig.Insert(name)
+		}
+		if removed, removedVersion := isPluginRemoved(apiVersion, name); removed {
+			errs = append(errs, field.Invalid(pluginConfigPath, name, fmt.Sprintf("was removed in version %q (KubeSchedulerConfiguration is version %q)", removedVersion, apiVersion)))
+		} else if validateFunc, ok := m[name]; ok {
+			// type mismatch, no need to validate the `args`.
+			if reflect.TypeOf(args) != reflect.ValueOf(validateFunc).Type().In(1) {
+				errs = append(errs, field.Invalid(pluginConfigPath.Child("args"), args, "has to match plugin args"))
```
Comment (chendave) [inline pkg/scheduler/apis/config/validation/validation.go:244]: @alculquicondor removed the `return`  here.

File: pkg/scheduler/apis/config/validation/validation_test.go [hunk 4]
```diff
@@ -254,6 +254,12 @@ func TestValidateKubeSchedulerConfiguration(t *testing.T) {
 	goodConflictPlugins2.Profiles[0].Plugins.Score.Enabled = append(goodConflictPlugins2.Profiles[0].Plugins.Score.Enabled, config.Plugin{Name: "NodeResourcesMostAllocated", Weight: 2})
 	goodConflictPlugins2.Profiles[0].Plugins.Score.Enabled = append(goodConflictPlugins2.Profiles[0].Plugins.Score.Enabled, config.Plugin{Name: "RequestedToCapacityRatio", Weight: 2})
 
+	badPluginsConfig := validConfig.DeepCopy()
```
Comment (alculquicondor) [inline pkg/scheduler/apis/config/validation/validation_test.go:257]: nit: deprecatedPluginsConfig

**Review by alculquicondor — COMMENTED** [review]
/approve
/lgtm
/hold
in case you want to fix the nit

File: pkg/scheduler/apis/config/validation/validation_test.go (hunk 4 above)
Comment (chendave) [reply pkg/scheduler/apis/config/validation/validation_test.go]: yes, this sound better.

**Review by yangjunmyfm192085 — COMMENTED** [review]
/retest
