### PR TITLE
kubelet: devices: skip allocation for running pods

### LINKED ISSUE #118559: Running pods with devices are terminated if kubelet is restarted
### What happened?

In KubeVirt project, we now see a regression when running on Kubernetes `1.25.10 | 1.26.5 | 1.27.2`. If kubelet is restarted on a node, then all the existing and running workloads that use devices are terminated with `UnexpectedAdmissionError`:
```
Warning  UnexpectedAdmissionError  45s   kubelet            Allocate failed due to no healthy devices present; cannot allocate unhealthy devices devices.kubevirt.io/kvm, which is unexpected
Normal   Killing                   42s   kubelet            Stopping container compute
```
KubeVirt runs virtual machines inside pods and uses a device plugin to advertise e.g. `/dev/kvm` on the nodes.

Presumably, this PR changed the behavior: https://github.com/kubernetes/kubernetes/pull/116376
Original issue: https://github.com/kubernetes/kubernetes/issues/109595

### What did you expect to happen?

A potential restart of kubelet should not interrupt the running workloads.

### How can we reproduce it (as minimally and precisely as possible)?
with KubeVirt:

- run a KubeVirt VM
- `pkill kubelet`
- observe that the workload pod gets terminated

or with https://github.com/k8stopologyawareschedwg/sample-device-plugin

- make deploy
- make test-both
- pkill kubelet
- the pod gets restarted

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

This affects the 1.25.x, 1.26.x and 1.27.x branches.

1.25.10 | 1.26.5 | 1.27.2

</details>

### Cloud provider

<details>

N/A

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by ffromani**
#### What type of PR is this?

/kind bug
/kind regression

#### What this PR does / why we need it:
When kubelet initializes, runs admission for pods and possibly allocate requested resources. We need to distinguish between node reboot (no containers running) versus kubelet restart (containers potentially running).

Running pods should always survive kubelet restart. This means that device allocation on admission should not be attempted, because if a container requires devices and is still running when kubelet is restarting, that container already has devices allocated and working.
    
Thus, we need to properly detect this scenario in the allocation step and handle it explicitely. We need to inform the devicemanager about which pods are already running.

#### Which issue(s) this PR fixes:
Fixes #118559

#### Special notes for your reviewer:
Implements the first approach [proposed](https://github.com/kubernetes/kubernetes/issues/118559#issuecomment-1584636260) in [the thread](https://github.com/kubernetes/kubernetes/issues/118559#issuecomment-1584802420), so we make the devicemanager treat running pod differently.

This approach was chosen because it seems simpler to make self-contained and easier to backport.

The devicemanager already tracks (with the help of the checkpoint files) which containers got devices assigned to them, which by definition means these containers passed its admission. The missing bit is safely learning which container are already running when initializing, and for that we extend the [existing `buildContainerMapFromRuntime`](https://github.com/kubernetes/kubernetes/blob/v1.28.0-alpha.2/pkg/kubelet/cm/container_manager_linux.go#L567)

#### Does this PR introduce a user-facing change?
```release-note
Fixes regression causing running pods with devices to be terminated if kubelet is restarted
```

### CODE REVIEW

**Comment by ffromani** [comment]
DRAFT to illustrate the concept. Working on tests if the basic approach is OK.

**Comment by ffromani** [comment]
un-drafted to collect feedback from the lanes.

I'm still looking for a better way to learn if a pod is running, feedback is welcome.
Distinguish if a pod is currently running helps to fix both the node reboot scenario vs the kubelet restart scenario (restart everything vs restarting only the kubelet)

**Comment by ffromani** [comment]
TODO: fix/enhance the device plugin e2e tests

File: pkg/kubelet/cm/container_manager_linux.go [hunk 1]
```diff
@@ -563,16 +562,17 @@ func (cm *containerManagerImpl) Start(node *v1.Node,
...
-	containerMap := buildContainerMapFromRuntime(ctx, runtimeService)
 	err := cm.cpuManager.Start(cpumanager.ActivePodsFunc(activePods), sourcesReady, podStatusProvider, runtimeService, containerMap)
 	if err != nil {
 		return fmt.Errorf("start cpu manager error: %v", err)
 	}
 
 	// Initialize memory manager
 	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.MemoryManager) {
-		containerMap := buildContainerMapFromRuntime(ctx, runtimeService)
+		containerMap, _ := buildContainerMapAndRunningSetFromRuntime(ctx, runtimeService)
```
[the remark this answers is not in the document]
Comment (ffromani) [reply pkg/kubelet/cm/container_manager_linux.go:575]: This was done when resource managers were beta, so they could have been enabled independently from each other. Now that they are graduating to GA, it is wasteful at best. I think all the managers should use the same `containerMap`. But let's address this in a followup PR.

[the remark this answers is not in the document]
Comment (PiotrProkop) [reply pkg/kubelet/cm/container_manager_linux.go:575]: Thanks for the explanation.

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 2]
```diff
@@ -1040,3 +1060,25 @@ func (m *ManagerImpl) setPodPendingAdmission(pod *v1.Pod) {
 
 	m.pendingAdmissionPod = pod
 }
+
+func (m *ManagerImpl) checkContainerAlreadyRunning(podUID, cntName string) bool {
+	if m.sourcesReady.AllReady() {
+		// initialization done, let's stop any guessing
+		return false
+	}
```
Comment (swatisehgal) [inline pkg/kubelet/cm/devicemanager/manager.go:1068]: This doesn't seem right. Can you please clarify? IIUC, sources are reflective of readiness of kubelet configuration sources.  IIUC we should return with `false` if the sources are not ready i.e. if  `!m.sourcesReady.AllReady()` evaluates to true.

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 3]
```diff
@@ -1040,3 +1060,25 @@ func (m *ManagerImpl) setPodPendingAdmission(pod *v1.Pod) {
...
+
+	cntID, err := m.containerMap.GetContainerID(podUID, cntName)
+	if err != nil {
+		klog.V(4).InfoS("container not found in the initial map, assumed NOT running", "podUID", podUID, "containerName", cntName, "err", err)
+		return false
+	}
+
+	if !m.containerRunningSet.Has(cntID) {
```
Comment (Tusenka) [inline pkg/kubelet/cm/devicemanager/manager.go:1076]: So here you check that pod is not starting. Approved.
It a bit odd that Container Map return getContainerID return while RunninSet uses `has` function.
But it is ok that we need only check that the container is running.

**Review by Tusenka — APPROVED** [review]

**Review by swatisehgal — COMMENTED** [review]
This seems like a promising direction to me for the following reasons :

- The change is self contained and can be easily backported to the impacted versions.
-  We are already calling container runtime during  container manager initialization and passing it to CPU Manager and Memory Manager so doing that also for Device Manager makes sense.  I would like to understand @smarterclayton's [reservations](https://github.com/kubernetes/kubernetes/issues/118559#issuecomment-1584701843) in querying runtime to determine information about running pods.
- This seems like a good interim solution while we work towards the long term approach of admission with "no decision and retry later".

LGTM from me on the overall direction.

Let's add unit tests and e2e tests (fixing the device plugin e2e tests would be sufficient here IMO) to test the code changes made here.

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 2 above)
Comment (ffromani) [reply pkg/kubelet/cm/devicemanager/manager.go:1068]: Probably the name is misleading, or I should move this check in the calling site. The idea here is that this logic should be triggered only during initialization, so we should skip it alltogether once initialization is complete. Using `AllReady` is (AFAIK) the established way to check if initialization is still ongoing or not.

**Comment by ffromani** [comment]
/test pull-kubernetes-e2e-capz-windows

past failures don't look relevant

**Comment by ffromani** [comment]
also tagging @vasiliy-ul

**Comment by ffromani** [comment]
the windows lane failure seems unrelated (gonna file a flake about it) while the `node-serial-containerd` lane failures are addressed in https://github.com/kubernetes/kubernetes/pull/118754

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 4]
```diff
@@ -97,6 +98,15 @@ type ManagerImpl struct {
 
 	// pendingAdmissionPod contain the pod during the admission phase
 	pendingAdmissionPod *v1.Pod
+
+	// containerMap provides a mapping from (pod, container) -> containerID
+	// for all containers a pod. Used to detect pods running across a restart
```
Comment (vasiliy-ul) [inline pkg/kubelet/cm/devicemanager/manager.go:103]:
```suggestion
	// for all containers in a pod. Used to detect pods running across a restart
```

**Review by vasiliy-ul — COMMENTED** [review]
Looks promising. Thanks!

**Comment by ffromani** [comment]
> I think the strategy and e2e test outlined look good based on a quick pass.
> 
> It would be great if @klueska you can take primary review as I have had limited availability this week.
> 
> /assign @klueska

Thanks Derek for chiming in.
I'm currently working to add the test mentioned in the slack thread https://kubernetes.slack.com/archives/C0BP8PW9G/p1687286065476599?thread_ts=1687277001.458669&cid=C0BP8PW9G

I've also had offline conversations and it was pointed out to me that the proposed fix will still kill pods if the kubelet restarts when the container runtime is down. This is indeed true.

I tend to think this case is way less common than a kubelet restart and can be dealt with less urgency, but I'm open to suggestions here. I'll explore anyway how to deal with this futher case once the required e2e test is added.

**Review by Tusenka — APPROVED** [review]

**Comment by ffromani** [comment]
need to deep dive into the serial line failures - there's a fairly high chance they are not related to this PR

**Comment by ffromani** [comment]
@elezar may be interested in this PR and in the issue we want to fix

**Comment by elezar** [comment]
> @elezar may be interested in this PR and in the issue we want to fix

Thanks @ffromani, I'll have a look.

**Comment by bobbypage** [comment]
I left a couple small comments, but overall lgtm, thanks for adding the additional detailed tests.

/lgtm

File: pkg/kubelet/cm/helpers.go [hunk 5]
```diff
@@ -44,3 +51,33 @@ func hardEvictionReservation(thresholds []evictionapi.Threshold, capacity v1.Res
...
 }
+
+func buildContainerMapAndRunningSetFromRuntime(ctx context.Context, runtimeService internalapi.RuntimeService) (containermap.ContainerMap, sets.String) {
+	podSandboxMap := make(map[string]string)
+	podSandboxList, _ := runtimeService.ListPodSandbox(ctx, nil)
+	for _, p := range podSandboxList {
+		podSandboxMap[p.Id] = p.Metadata.Uid
+	}
+
+	runningSet := sets.NewString()
```
Comment (iholder101) [inline pkg/kubelet/cm/helpers.go:62]: According to the code-comments [1]:
```go
// Deprecated: use generic Set instead.
// new ways:
// s1 := Set[string]{}
// s2 := New[string]()
```

Would you mind switching to the generic Set that's not deprecated?

[1] https://github.com/kubernetes/apimachinery/blob/master/pkg/util/sets/string.go#L21

**Review by iholder101 — COMMENTED** [review]
Looks great, thanks @ffromani!

File: pkg/kubelet/cm/helpers.go (hunk 5 above)
Comment (ffromani) [reply pkg/kubelet/cm/helpers.go:62]: Done, thanks

Comment (ffromani) [reply pkg/kubelet/cm/helpers.go:62]: The PR adding the generic set was introduced in 1.26. I'd like to have this PR potentially and easily backportable down to 1.25, because the regression we are fixing was caused by another fix backported to 1.25. For this reason I prefer to use the deprecated (but still valid) syntax. If we want a different PR specific for 1.25 and use the generics in 1.26 and onwards, I'm open to that as well.

Comment (iholder101) [reply pkg/kubelet/cm/helpers.go:62]: Yeah, makes total sense.
We can also defer this to a follow-up after everything is backported.

Thanks a lot!

**Comment by swatisehgal** [comment]
/test pull-kubernetes-node-kubelet-serial-containerd
unrelated test failure

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 6]
```diff
@@ -277,11 +287,13 @@ func (m *ManagerImpl) checkpointFile() string {
 // Start starts the Device Plugin Manager and start initialization of
 // podDevices and allocatedDevices information from checkpointed state and
 // starts device plugin registration service.
-func (m *ManagerImpl) Start(activePods ActivePodsFunc, sourcesReady config.SourcesReady) error {
+func (m *ManagerImpl) Start(activePods ActivePodsFunc, sourcesReady config.SourcesReady, initialContainers containermap.ContainerMap, initialContainerRunningSet sets.String) error {
 	klog.V(2).InfoS("Starting Device Plugin manager")
 
 	m.activePods = activePods
 	m.sourcesReady = sourcesReady
+	m.containerMap = initialContainers
```
Comment (elezar) [inline pkg/kubelet/cm/devicemanager/manager.go:295]: Looking at the implementation, we don't ever seem to use `m.containerMap` and `m.containerRunningSet` separately. Does this mean that we should introduce a new type that encapuslates their relationship and the intent? The `checkContainerAlreadyRunning` method that is currently attached to the manager implementation could be directly attached to this type, for example.

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 7]
```diff
@@ -545,6 +557,15 @@ func (m *ManagerImpl) devicesToAllocate(podUID, contName, resource string, requi
 		}
 	}
 
+	// kubelet restart flow.
+	if !m.sourcesReady.AllReady() {
+		// if the container is reported running and it had a device assigned, things are already fine and we can just bail out
+		if needed == 0 && m.checkContainerAlreadyRunning(podUID, contName) {
```
Comment (elezar) [inline pkg/kubelet/cm/devicemanager/manager.go:563]: Question: Is the `needed == 0` check relevant here? We already error out above if this is not the case. Furthermore, would moving the
```
	if needed == 0 {
		klog.V(3).InfoS("no devices needed, nothing to do", "deviceNumber", needed, "resourceName", resource, "podUID", string(podUID), "containerName", contName)
		// No change, no work.
		return nil, nil
	}
``` 
below earlier in this function not achieve the same result, or are the additional checks required in any case?

**Review by elezar — COMMENTED** [review]
Thanks for the ping on this @ffromani.

I've added some comments and questions.

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 6 above)
Comment (ffromani) [reply pkg/kubelet/cm/devicemanager/manager.go:295]: This implementation stems form the original PoC. I kept it minimal (and somehow ugly) because wanted to validate the design and get feedback on it. If we agree this is a good way forward I think that yes, we should polish and probably rearrange the code per your suggestion.

File: pkg/kubelet/cm/helpers.go [hunk 8]
```diff
@@ -44,3 +51,33 @@ func hardEvictionReservation(thresholds []evictionapi.Threshold, capacity v1.Res
...
+	containerMap := containermap.NewContainerMap()
+	containerList, _ := runtimeService.ListContainers(ctx, nil)
+	for _, c := range containerList {
+		if _, exists := podSandboxMap[c.PodSandboxId]; !exists {
+			klog.InfoS("No PodSandBox found for the container", "podSandboxId", c.PodSandboxId, "containerName", c.Metadata.Name, "containerId", c.Id)
+			continue
+		}
+		podUID := podSandboxMap[c.PodSandboxId]
+		containerMap.Add(podUID, c.Metadata.Name, c.Id)
```
[the remark this answers is not in the document]
Comment (ffromani) [reply pkg/kubelet/cm/helpers.go:71]: absolutely. Circling back of https://github.com/kubernetes/kubernetes/pull/118635#discussion_r1252043938 this can be a good way to clean up the code.
I'll start a parallel and more polished branch while I wait to reach consensus about this direction (no approver commented yet)

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 7 above)
Comment (ffromani) [reply pkg/kubelet/cm/devicemanager/manager.go:563]: I was thinking to a case like pod mutated (resource request changed, e.g. adding a device) while kubelet is down (or restarting and not yet recovered from the apiserver, which is functionally the same case) but thinking more about it should not be possible to mutate the request without deleting/recreating the pod, not even with Vertical Pod Autoscaling.
I'll doublecheck this and simplify the flow if possible. Thanks for highlighting this.

**Comment by sdodson** [comment]
@klueska Can you take a look at approving this now that it's lgtm?

**Comment by ffromani** [comment]
@elezar howdy! as promised, here's the alternative take we discussed: https://github.com/kubernetes/kubernetes/pull/119151 - changes only in the first commit, tests are unaffected.

**Comment by ffromani** [comment]
/test pull-kubernetes-node-kubelet-serial-containerd

failed only the pod density test, which really seems unrelated

**Comment by ffromani** [comment]
```
{ failed [FAILED] CPU usage exceeding limits:
 node n1-standard-2-cos-stable-105-17412-101-37-a92d2f00:
 container "runtime": expected 95th% usage < 0.600; got 0.817
In [It] at: test/e2e_node/resource_usage_test.go:288 @ 07/03/23 10:45:42.462
}
```

**Comment by ffromani** [comment]
the density test needs further inspection, I'll file a bug about it.

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 7 above)
Comment (klueska) [reply pkg/kubelet/cm/devicemanager/manager.go:563]: I believe the check for `needed == 0` below can be pulled above this (removing the need to check it here).

File: pkg/kubelet/cm/helpers.go [hunk 9]
```diff
@@ -44,3 +51,33 @@ func hardEvictionReservation(thresholds []evictionapi.Threshold, capacity v1.Res
...
+			runningSet.Insert(c.Id)
+		}
+	}
+
+	return containerMap, runningSet
+}
+
+func isContainerStateRunning(state runtimeapi.ContainerState) bool {
+	return state == runtimeapi.ContainerState_CONTAINER_RUNNING
+}
```
Comment (klueska) [inline pkg/kubelet/cm/helpers.go:83]: I don' think this helper is necessary, it'a clearer to me if it is simply inlined.

That said, if we do what I suggested previously, and rack the full container object instead of just its running state, then this check would be done elsewhere anyway.

File: pkg/kubelet/cm/helpers.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (elezar) [reply pkg/kubelet/cm/helpers.go:71]: Looked at the other PR. Definitely cleans up the "Running" checks!

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 10]
```diff
@@ -97,6 +98,15 @@ type ManagerImpl struct {
...
 	pendingAdmissionPod *v1.Pod
+
+	// containerMap provides a mapping from (pod, container) -> containerID
+	// for all containers a pod. Used to detect pods running across a restart
+	containerMap containermap.ContainerMap
+
+	// containerRunningSet identifies which container among those present in `containerMap`
+	// was reported running by the container runtime when `containerMap` was computed.
+	// Used to detect pods running across a restart
+	containerRunningSet sets.String
```
Comment (klueska) [inline pkg/kubelet/cm/devicemanager/manager.go:109]: I'm normally not a huge fan of adding a one-off, special purpose list like this, but I don't see a good alternative other than to maybe turn this into a list of the full `runtimeapi.Container` objects. That way we can pull other information from these objects in the future if necessary.

**Comment by klueska** [comment]
In general, both the direction and the test coverage look good.

I have a small comment about my preference for not creating a one-off list to track the very special purpose set of running containers, but it is not-blocking.

I will approve this PR and put it in a holding state to give @ffromani a chance to consider what I have suggested. Otherwise, feel free to remove the hold.

/approve
/hold

**Comment by ffromani** [comment]
Thanks @klueska ! the check for `needed == 0` raised comments from more than a reviewer so it's worth me spending time on it and addressing the comments properly. I'll take some time to do that.

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 7 above)
Comment (ffromani) [reply pkg/kubelet/cm/devicemanager/manager.go:563]: We need to tread carefully here because the check with `needed == 0` was a source of troubles in the recent past. I'm adding better comments to explain the flow here, I think they are warranted. Furthermore, in the end we _can_ pull this check above indeed if we check `requested` (= the original allocation request) instead of `needed` (= the fixed allocation request considering the already allocated devices from the checkpoint file).

I think we can add a check here: https://github.com/kubernetes/kubernetes/blob/v1.28.0-alpha.4/pkg/kubelet/cm/devicemanager/manager.go#L772 and shortcircuit earlier, avoiding `devicesToAllocate an all its complexity entirely. I'm however deferring this work to another PR to avoid further complicate this fix.

File: pkg/kubelet/cm/helpers.go (hunk 9 above)
Comment (ffromani) [reply pkg/kubelet/cm/helpers.go:83]: After few days of consideration, I think we should _not_ rack the full container object:
1. I for myself I think we're doing a bit of a layering violation querying the runtime in `buildContainerMap`. Or at very least we should aim to reconsider/refactor, which is a bigger effort outside of the scope of this PR
2. I would like this fix to be easily backportable because we likely need to backport down to 1.25 (or at least enable it) so I'm aiming to keep the changes minimal.

For both these reasons I'm keeping the separate set, even though I agree is a bit uglier, and I'm gonna close https://github.com/kubernetes/kubernetes/pull/119151

**Comment by ffromani** [comment]
addressed all the pending comments, and clarified further the flow adding rationale for the checks and the order of checks. Giving the history around this code flow I think we can use more explicit docs to make the intent really clear, because the scenarios we need to handle are tricky. The actual code changes are minimal

**Comment by ffromani** [comment]
keeping the hold while I do the final verification step

**Comment by ffromani** [comment]
e2e-capz-windows  failure (unrelated):
```
Kubernetes e2e suite: [It] [sig-auth] ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]
``
node-e2e-containerd-serial-ec2 failure (unrelated):
```
E2eNode  Suite: [It] [sig-node] SystemNodeCriticalPod [Slow] [Serial]  [Disruptive] [NodeFeature:SystemNodeCriticalPod] when create a  system-node-critical pod  should not be evicted upon DiskPressure
```
node-kubelet-serial-containerd  failure ():
```
E2eNode Suite: [It] [sig-node] Density [Serial] [Slow] create a batch of pods latency/resource should be within limit when create 10 pods with 0s interval 
E2eNode Suite: [It] [sig-node] SystemNodeCriticalPod [Slow] [Serial] [Disruptive] [NodeFeature:SystemNodeCriticalPod] when create a system-node-critical pod should not be evicted upon DiskPressure
```

**Review by elezar — COMMENTED** [review]
Thanks for the additional work on cleaning up `devicesToAllocate` @ffromani.

LGTM from my side.

**Comment by vasiliy-ul** [comment]
> @xpivarc @vasiliy-ul @iholder101 hey folks, any chance to consume this fix in kubevirt CI before the merge? All relevant test pass, but a bit of extra care won't hurt I guess

I am not sure how to **quickly** test in the CI with custom kubelet. But I did some manual runs on a test cluster and I see that with this fix the workloads are not terminated on kubelet restart anymore.

**Comment by ffromani** [comment]
> > @xpivarc @vasiliy-ul @iholder101 hey folks, any chance to consume this fix in kubevirt CI before the merge? All relevant test pass, but a bit of extra care won't hurt I guess
> 
> I am not sure how to **quickly** test in the CI with custom kubelet. But I did some manual runs on a test cluster and I see that with this fix the kubevirt workloads are not terminated on kubelet restart anymore.

Thanks, this helps! We're running extra checks within my team and everything looks good indeed. I'm oriented towards unblocking the merge on main branch, to give time to other projects to consume builds and validate the fix, and once we're all reasonanbly happy start the backport process (vs just starting the backport right after the master branch merge)

**Comment by haircommander** [comment]
/lgtm

[the rational pieces](https://github.com/kubernetes/kubernetes/compare/71fdf75dc74d2705f687d75320233b8a5553b62b..c635a7e7d8362ac7c706680e77f7680895b1d517) are a great addition--I'm returning to you your tag

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 10 above)
Comment (ffromani) [reply pkg/kubelet/cm/devicemanager/manager.go:109]: Same considerations as per https://github.com/kubernetes/kubernetes/pull/118635#discussion_r1261023770 apply. TL;DR: this code reorganization is likely worthy, but deserves its own separate effort.

**Comment by ffromani** [comment]
due diligence on windows side

**Comment by ffromani** [comment]
/unhold

we got sufficient **additional** verification and testing that this PR fixes the issue and is not regressing on the node reboot scenario, as documented in the comments and after extra verification done within my team. I'll keep monitoring the lanes and continue working in this area.

Backports will be done but with a relatively slow pace, to allow ample time for other parties (e.g. kubevirt) to consume the merged code. In due time, I plan to backport to 1.27.z ("soon") then to 1.26.z and 1.25.z.

Thanks to everyone which reviewed, tested and contributed to this PR.
