### PR TITLE
Fix a preemption bug when pods are listed in pdb.Status.DisruptedPods 

### LINKED ISSUE #92475: Preemption logic on PDB violations
In one recent fix (#91986), we enhanced the preemption logic to respect `pdb.Status.DisruptedPods`. But there is a glitch:

https://github.com/kubernetes/kubernetes/blob/ef8380e6c0ada9ef682d2d3566cbb16b79445233/pkg/scheduler/core/generic_scheduler_test.go#L1486-L1502

- if we changed the DisruptedPods  in L1499 from "a" to "b", the test would fail
- it would also fail if we change the pods (i.e., []Pod{"b", "a"}) ordering in L1496~L1497

This is a problem we need to fix.

---

On the other hand, I'm thinking about the real semantics of `pdb.Status.DisruptedPods`. According to the docs, if a pod is matched by the "DisruptedPods" list, it denotes the pod is about to be evicted by API server as it at least has violated one disruption budget. Given this fact, IMO in scheduler preemption, we should treat this kind of pod as "nonViolating" in all cases - no matter the current `pdb.Status.DisruptionsAllowed` is negative or not. So that the scheduler would treat them as preemption candidates.

/sig scheduling

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind bug
/sig scheduling

**What this PR does / why we need it**:

- The first commit resolves the 1st problem mentioned in #92248 
- The second commit (will squash later) walks one step further to treat Pods listed in `pdb.Status.DisruptedPods` as "nonViolating" in any case.

**Which issue(s) this PR fixes**:

Fixes #92475

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
This PR is better being reviewed commit by commit. The 1st commit is a must. The 2nd commit is nice to have to resolve this 2nd concern I mentioned in the original issue.

File: pkg/scheduler/core/generic_scheduler.go [hunk 1]
```diff
@@ -936,15 +936,18 @@ func filterPodsWithPDBViolation(pods []*v1.Pod, pdbs []*policy.PodDisruptionBudg
...
 				}
+
+				// Existing in DisruptedPods means it has been processed in API server,
+				// we don't treat it as a violating case.
+				if _, exist := pdb.Status.DisruptedPods[pod.Name]; exist {
+					continue
+				}
+				// Only decrement the matched pdb when it's not in its <DisruptedPods>;
+				// otherwise we may over-decrement the budget number.
+				pdbsAllowed[i]--
```
Comment (ahg-g) [inline pkg/scheduler/core/generic_scheduler.go:947]: wouldn't this make the value go into the minus? I guess it doesn't matter if that happens, right?

**Review by ahg-g — COMMENTED** [review]
/lgtm

File: pkg/scheduler/core/generic_scheduler.go (hunk 1 above)
Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler.go:947]: Yes, pdbsAllowed[i] can be negative now.

Another style is like this:

```go
if pdbsAllowed[i] <= 0 {
    pdbForPodIsViolated = true
} else {
    pdbsAllowed[i]--
}
```

Not quite make a big difference I think :)
