### PR TITLE
kubeadm: ensure that etcd certs are rotated on apiserver upgrade

### LINKED ISSUE #2989: apiserver connection error does not give useful details
### What happened?

our kube-apiserver just started failing to start.. The log from containerd only says:
2023-12-16T07:35:01.426019865+01:00 stderr F }. Err: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid: current time 2023-12-16T06:35:01Z is after 2023-12-03T03:37:19Z"

we checked apiserver certs etc. -and they were all fine.
We finally checked etcd endpoint - and that had an old cert (which for some reason was not updated with kubeadm update

kubeadm certs check-expiration had the details - but IMHO kubeadm k8s update SHOULD look at certs expiration and renew them all - instead of only renewing etcd certs IF there's an update for it.

### What did you expect to happen?

a logmessage that told me which endpoint had the bad cert and details about cert.

We had updated using kubeadm and it renewed certs - but appearently it does not renew etcd certs - if there is no update of that component - which surprised us - as we thought it renewed all certs for cluster on upgrades :(

### How can we reproduce it (as minimally and precisely as possible)?

update via kubeadm so etcd certs are not being renewed and "adjust OS time" - so etcd certs are expired but rest are not.

### Anything else we need to know?

_No response_

### Kubernetes version

Server Version: v1.26.4

we'll update soon (above might have been fixed in newer version?)

### Cloud provider

Hetzner physical server

### OS version

Ubuntu 22.04

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Currently if etcd.yaml does not have a diff on "kubeadm upgrade" certificate renewal for it is also skipped.

Check if kube-apiserver.yaml needs an upgrade, if so and if cert renewal is not disabled, renew etcd's certs and restart its static pod.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/2989

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: during "upgrade" , if the "etcd.yaml" static pod does not need upgrade, still consider rotating the etcd certificates and restarting the etcd static pod if the "kube-apiserver.yaml" manifest is to be upgraded and if certificate renewal is not disabled.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/phases/upgrade/staticpods.go [hunk 1]
```diff
@@ -228,17 +240,34 @@ func upgradeComponent(component string, certsRenewMgr *renewal.Manager, waiter a
...
+	if equal && certsRenewMgr != nil {
+		fmt.Printf("[upgrade/staticpods] Restarting the %s static pod and backing up its manifest to %q\n",
+			component, backupManifestPath)
 
-	// Move the new manifest into the manifests directory
-	if err := pathMgr.MoveFile(newManifestPath, currentManifestPath); err != nil {
-		return rollbackOldManifests(recoverManifests, err, pathMgr, recoverEtcd)
-	}
+		// Move the old manifest into the old-manifests directory
+		if err := pathMgr.MoveFile(currentManifestPath, backupManifestPath); err != nil {
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/upgrade/staticpods.go:249]: having this second move seems sufficient to perform a quick pod restart of etcd it seems.

i checked with crictl ps multiple times;
- old container exits
- new container starts

i also tested by adding a few seconds timeout here (time.Sleep), but it resulted in a slow etcd pod restart and there was 20+ seconds downtime of e.g. `k get po -A`  not getting a response.

if for some reason the etcd pod does not properly restart here, once its serving cert expires the health check will restart it after 15 seconds. i could not reproduce such a scenario, because it always restarts after the two "moves" here.

File: cmd/kubeadm/app/phases/upgrade/staticpods.go [hunk 2]
```diff
@@ -453,11 +484,15 @@ func StaticPodControlPlane(client clientset.Interface, waiter apiclient.Waiter,
 		}
 	}
 
+	// Write the updated static Pod manifests into the temporary directory
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/upgrade/staticpods.go:487]: creating the kube-* component man ifests is now required before etcd upgrade wth performEtcdStaticPodUpgrade

**Review by neolit123 — COMMENTED** [review]
not a big fan of how this turned out, so ideas to improve it are welcome.

in terms of code clarity renewing a component certs even if the static pod YAML needs no change might be much cleaner.

- renew certs if certs renewal is enabled
- move new manifest in, move the old manifest to backup even if there is not YAML diff (this will trigger comp restart)
- wait for hash change only if there was an YAML diff 

this will make upgrade be used like a quick cert renew / backup / pod restart utility even if there are no manifest changes and i think the code will be cleaner than this current state of the PR. but the "always restart components" even if there is no upgrade might not be desired.

/cc @SataQiu @pacoxu
/uncc @chendave

**Comment by neolit123** [comment]
@SataQiu @pacoxu any thought about this?

**Comment by neolit123** [comment]
> Are there any known issues on the etcd certs rotation? If not, this would be quite safe. If yes, we should evaluate it.

not any that i know of.

**Comment by pacoxu** [comment]
> > Are there any known issues on the etcd certs rotation? If not, this would be quite safe. If yes, we should evaluate it.
> 
> not any that i know of.

Then, +1 for this.

Some other behaviors below makes me agree that the rotation is expected. 

1. `--certificate-renewal` is by default true 
2. kubespray uses `ubeadm_upgrade_auto_cert_renewal: true` as well
https://github.com/kubernetes-sigs/kubespray/blob/d7756d85ef59355aefcbea1306557dd5eab45aa6/roles/kubernetes/control-plane/tasks/kubeadm-upgrade.yml#L17C5-L17C26

**Comment by neolit123** [comment]
@SataQiu PTAL to see if you approve of the idea

**Comment by pacoxu** [comment]
/lgtm
/hold
for more review

**Comment by carlory** [comment]
LGTM cc @neolit123 @SataQiu

**Comment by neolit123** [comment]
i would to hear what @SataQiu has to say about this change

File: cmd/kubeadm/app/phases/upgrade/staticpods.go [hunk 3]
```diff
@@ -214,8 +222,12 @@ func upgradeComponent(component string, certsRenewMgr *renewal.Manager, waiter a
 		return err
 	}
 	if equal {
-		fmt.Printf("[upgrade/staticpods] Current and new manifests of %s are equal, skipping upgrade\n", component)
-		return nil
+		if !apiServerUpgrade {
+			fmt.Printf("[upgrade/staticpods] Current and new manifests of %s are equal, skipping upgrade\n", component)
+			return nil
+		}
+		fmt.Printf("[upgrade/staticpods] Current and new manifests of %s are equal, but %s will be upgraded\n",
```
Comment (SataQiu) [inline cmd/kubeadm/app/phases/upgrade/staticpods.go:229]: This may be confusing for users.
 If it's for debug purposes, it might be better to use `klog.V(4)` ?

File: cmd/kubeadm/app/phases/upgrade/staticpods.go (hunk 2 above)
Comment (SataQiu) [reply cmd/kubeadm/app/phases/upgrade/staticpods.go:487]: we'd better to add a some comment about this to prevent bugs caused by accidental code refactoring:
// As part of the design, this must be called before the below `performEtcdStaticPodUpgrade`

**Review by SataQiu — APPROVED** [review]
SGTM

File: cmd/kubeadm/app/phases/upgrade/staticpods.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/phases/upgrade/staticpods.go:249]: updated. i missed this optimization because of WIP refactors when i was working on the PR

File: cmd/kubeadm/app/phases/upgrade/staticpods.go (hunk 2 above)
Comment (neolit123) [reply cmd/kubeadm/app/phases/upgrade/staticpods.go:487]: decided to just add a comment for now.

**Comment by neolit123** [comment]
@SataQiu updated the PR after your review.

**Review by SataQiu — COMMENTED** [review]
/lgtm
/approve
