### PR TITLE
Fix kubelet certificate reload when connecting by IP address

### LINKED ISSUE #133001: Kubelet certificate not reloaded after replacement
### What happened?

I am running the kubelet with a custom TLS certificate, using:

```yaml
tlsCertFile: /etc/kubernetes/pki/kubelet.crt
tlsPrivateKeyFile: /etc/kubernetes/pki/kubelet.key
```

I am automatically rotating this certificate using OpenBao. After some time, I see an error about an expired certificate:

```
> kubectl logs -n kube-system kube-apiserver-node-0 
Error from server: Get "https://172.29.0.2:10250/containerLogs/kube-system/kube-apiserver-node-0/kube-apiserver": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2025-07-16T19:47:40Z is after 2025-06-30T23:08:51Z
```

However, the certificate on disk is still valid:

```
# openssl x509 -noout -text < /etc/kubernetes/pki/kubelet.crt 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            7a:7a:b8:8e:ca:dc:61:19:f8:a7:07:ce:35:1a:ed:86:79:e8:21:bb
        Signature Algorithm: ecdsa-with-SHA384
        Issuer: CN = Cerai kubelet CA
        Validity
            Not Before: Jul 13 19:54:43 2025 GMT
            Not After : Jul 20 19:55:13 2025 GMT
        Subject: CN = kubelet
```

It seems the kubelet is not reloading the changed certificate. Running `systemctl restart kubelet` fixes the issue temporarily (until the certificate expires again).

### What did you expect to happen?

I expect the kubelet to function correctly, as long as the certificate on disk is valid.

### How can we reproduce it (as minimally and precisely as possible)?

I haven't tested this reproducer yet, I will do that tomorrow. But I think the following should be sufficient:

1. Start the kubelet with `tlsCertFile`
3. Overwrite the certificate on-disk with a new certificate
4. Observe that the kubelet is still using the old certificate

### Anything else we need to know?

I'm happy to work on a fix for this.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.33.0
Kustomize Version: v5.6.0
Server Version: v1.33.1
```

</details>

### Cloud provider

<details>
Hetzner Cloud
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by kwohlfahrt**
#### What type of PR is this?

/kind bug

Note the issue is tagged as a feature, but certificate reloading for the kubelet was previously added in #124574, so I think this is better described as a bug.

#### What this PR does / why we need it:

Currently, the certificate reloading functions from the `ReloadKubeletServerCertificateFile` are not called. A clearer description is in [this issue comment](https://github.com/kubernetes/kubernetes/issues/133001#issuecomment-3209843823), but the summary is that `http.Server` does not call `GetCertificate` if certificate paths were passed to `ListenAndServeTLS` and the client connects by IP (and therefore does not use SNI).

#### Which issue(s) this PR is related to:

Fixes #133001 

#### Special notes for your reviewer:

I'm struggling to find a good way to test for the presence/absence of this bug, because `ListenAndServeKubeletServer` calls `os.Exit(1)` if the HTTPS server exits. There is also no easy way to shutdown the HTTPS server, or to pick a random port to serve on (for parallel testing).

I'm happy to refactor this code to allow testing, but would like to get a maintainer/reviewer's opinion on how to best do this - should it be an e2e test, or I change the function to `CreateKubeletServer`, and return the server for testing?

#### Does this PR introduce a user-facing change?

```release-note
kubelet: fixed reloading of kubelet server certificate files when they are changed on disk, and kubelet is dialed by IP address instead of DNS/hostname
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

N/A

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Are there any tests that should have failed, but didn't? Or new tests that you can write?

**Comment by zhangweikop** [comment]
@kwohlfahrt Thank you for debugging and fixing the issue.

I think using e2e test to covert this makes sense. 
I feel refactoring might not help much, since the logic still ultimately depends on the behavior of Go's tls.Server.

**Comment by SergeyKanzhelev** [comment]
> @kwohlfahrt Thank you for debugging and fixing the issue.
> 
> I think using e2e test to covert this makes sense. I feel refactoring might not help much, since the logic still ultimately depends on the behavior of Go's tls.Server.

We need to have some test here to catch a regression. @zhangweikop @kwohlfahrt if you will have troubles identifying the proper way to test it, please comment here

**Comment by kwohlfahrt** [comment]
@SergeyKanzhelev I've added a regression test. I've confirmed that the test fails before the fix is applied, and passes after. The test is labelled with `framework.WithSerial()`, because it changes and reloads the Kubelet config, I hope this is correct. Now that we have a test, IMO this is ready for review so I've removed the `[WIP]` tag as well.

I've also updated the release note as you requested on the issue, to clarify that the issue only occurs when the kubelet is dialed by IP, not hostname/DNS.

I've also rebased the fix onto 1.34, and tested that a kubelet built from that commit actually solves the original symptom (`kubectl logs` returns a certificate error), which it does.

File: test/e2e_node/kubelet_tls_test.go [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+	conn, err := tls.Dial("tcp", addr, &tls.Config{InsecureSkipVerify: true})
+	if err != nil {
+		return nil, err
+	}
+	defer conn.Close()
+
+	return conn.ConnectionState().PeerCertificates[0], nil
+}
+
+var _ = SIGDescribe("KubletTLS", framework.WithSerial(), func() {
```
Comment (SergeyKanzhelev) [inline test/e2e_node/kubelet_tls_test.go]: Mark it as NodeConformance

**Comment by kwohlfahrt** [comment]
@SergeyKanzhelev I think I've addressed all the comments and test/lint failures. Does anything else need to be done before this can be merged?

**Comment by aojea** [comment]
maybe sig auth should check also this?

/sig auth
/cc @enj @liggitt

**Comment by ibihim** [comment]
/assign @stlaz 

For Sig-AUTH review

**Comment by liggitt** [comment]
/sig api-machinery

secure serving cert reloading is on the boundary between auth an api-machinery, tagging for visibility

File: pkg/kubelet/server/server.go [hunk 2]
```diff
@@ -194,10 +194,17 @@ func ListenAndServeKubeletServer(
 
 	if tlsOptions != nil {
 		s.TLSConfig = tlsOptions.Config
-		// Passing empty strings as the cert and key files means no
-		// cert/keys are specified and GetCertificate in the TLSConfig
-		// should be called instead.
-		if err := s.ListenAndServeTLS(tlsOptions.CertFile, tlsOptions.KeyFile); err != nil {
+		certFile := tlsOptions.CertFile
```
Comment (stlaz) [inline pkg/kubelet/server/server.go]: I think a better place to clear the Cert/KeyFile would be at the spot where the `tlsConfig.GetCertificate()` function is being set: https://github.com/kubernetes/kubernetes/blob/e1773f1afd16d7e2d9e0cd9b2c853734abb76ea5/pkg/kubelet/kubelet.go#L913-L921

Here it may not be clear where `tlsOptions` come from, and if `tlsOptions.CertFile` and `tlsOptions.KeyFile` would also be returned in a `GetCertificate()` call.
On the other hand, if we clear these fields in the above mentioned code, all consumers should continue to use all of `Cert/KeyFile` and `config.GetCertificate()` for their serving configuration.

Comment (kwohlfahrt) [reply pkg/kubelet/server/server.go]: Yeah, I didn't do this initially because I thought it might be confusing to have `tlsOptions.CertFile` and `tlsOptions.KeyFile` set in `InitializeTLS`, and then unset again later in `NewMainKubelet`. But I agree it might be less error prone to unset them immediately.

I've added the change, (+ a rebase onto `master`)

**Comment by kwohlfahrt** [comment]
/retest

I'm pretty sure the failure is not from this PR, but from kubernetes/test-infra#35882

File: test/e2e_node/kubelet_tls_test.go [hunk 3]
```diff
@@ -0,0 +1,116 @@
...
+		t := ginkgo.GinkgoT()
+		ginkgo.BeforeEach(func(ctx context.Context) {
+			tempDir = t.TempDir()
+			oldCfg, err := getCurrentKubeletConfig(ctx)
+			framework.ExpectNoError(err)
+
+			certPath, keyPath, err := createCertAndKeyFiles(tempDir)
+			framework.ExpectNoError(err)
+
+			cfg := oldCfg.DeepCopy()
```
Comment (stlaz) [inline test/e2e_node/kubelet_tls_test.go]: use `ginkgo.DeferCleanup()` to get the old config back

File: pkg/kubelet/kubelet.go [hunk 4]
```diff
@@ -919,6 +919,13 @@ func NewMainKubelet(ctx context.Context,
 				}
 				return cert, nil
 			}
+
+			// GetCertificate is only preferred over the certificate files if
```
Comment (stlaz) [inline pkg/kubelet/kubelet.go]:
```suggestion
			// GetCertificate is only preferred over the certificate files by Golang TLS if
```

**Review by stlaz — COMMENTED** [review]
minor comments, lgtm

File: test/e2e_node/kubelet_tls_test.go (hunk 3 above)
Comment (kwohlfahrt) [reply test/e2e_node/kubelet_tls_test.go]: Done, I hope I understood this correctly. Now using `DeferCleanup` instead of `AfterEach` to restore the old config.

**Review by stlaz — APPROVED** [review]
/lgtm
/approve
