### PR TITLE
StatefulSet: Don't try to update immutable hostname/subdomain fields.

### LINKED ISSUE #51043: StatefulSet controller sets immutable fields of v1.PodSpec
Part of the cause of #48327 is that the StatefulSet controller attempts to set the v1.PodSpec .Hostname and v1.PodSpec.Subdomain fields. Though the alpha annotations corresponding to these fields were mutable, and the though the endpoints controller could create new endpoints based on the mutation of these fields, kubelet does not seem sensitive to their mutation, and mutation of the fields is not supported in the v1.PodSpec API object.

**BUG REPORT**:
 /kind bug

### PR DESCRIPTION
**Pull request by kow3ns**
**What this PR does / why we need it**: The StatefulSet controller no longer attempts to mutate "hostname" or "subdomain" fields of the "pod.spec" to enforce the network identity of Pods in a StatefeulSet. Since these fields are set upon creation and immutable thereafter setting the annotations is no longer necessary. 
fixes: #51043

### CODE REVIEW

File: pkg/controller/statefulset/stateful_set_utils.go [hunk 1]
```diff
@@ -181,12 +179,19 @@ func updateStorage(set *apps.StatefulSet, pod *v1.Pod) {
 	pod.Spec.Volumes = newVolumes
 }
 
+func initIdentity(set *apps.StatefulSet, pod *v1.Pod) {
+	updateIdentity(set, pod)
+	// Set these immutable fields only on initial Pod creation, not updates.
+	// Set hostname/subdomain in preparation for removal of the annotations.
```
Comment (enisoc) [inline pkg/controller/statefulset/stateful_set_utils.go]: This line of the comment is not applicable on this branch, since the annotations were already removed.

**Review by enisoc — APPROVED** [review]
LGTM overall, one nit.

**Comment by enisoc** [comment]
@kow3ns Random crazy idea: What if we continue to check whether the hostname/subdomain (fields) match our expectation, and if not, we delete the Pod? Basically a StatefulSet Pod in this state is broken anyway, and the controller's job is to repair them when they're broken.

**Comment by kow3ns** [comment]
@enisoc Possible to do, but probably unnecessary as the fields are immutable, and, if you came to 1.8.x by way of 1.7.x, you are already using the fields.

**Comment by enisoc** [comment]
Yes it's unnecessary on master. I was thinking about for the cherrypick into 1.7. The hostname/subdomain fields are part of the desired state that the controller wants to maintain. Should we give up on the Pod if those fields are immutable, or should we delete the Pod in order to make progress towards the desired state?

**Comment by kow3ns** [comment]
It requires some thought, you upgrade form 1.6 to 1.7, and all of a sudden you get an automatic rolling update across all of your stateful applications (assuming we do the safe thing and orchestrate the deletion trying to preserve availability where possible). If we warn users that the update has to be manually, prior to the upgrade, they can update applications individually, and safely, prior to performing the 1.6.x to 1.7.x upgrade.

**Comment by enisoc** [comment]
Even if we do this, I would still recommend that users do it themselves before upgrading. The scenario I'm hoping to mitigate is if the user fails follow the recommendation. Their StatefulSet will get into a broken state that the controller can choose to either try to fix (by deleting Pods) or do nothing (because deleting Pods could make things worse). This may be moot though, because making a change that starts to delete Pods is probably too scary to do in a patch release. That's why I prefaced it by saying it's a crazy idea. :)
