### PR TITLE
fix: Refactor TestFinalizerCleanup unit test by asserting job and pod informer state

### LINKED ISSUE #121652: TestFinalizerCleanup flakes for Job
### Which jobs are flaking?

pull-kubernetes-unit.
Example:  https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121393/pull-kubernetes-unit/1719392853026672640

### Which tests are flaking?

TestFinalizerCleanup:
https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=TestFinalizerCleanup

### Since when has it been flaking?

Not sure, likely since added in https://github.com/kubernetes/kubernetes/pull/119944/files

### Testgrid link

_No response_

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig apps

### PR DESCRIPTION
**Pull request by dejanzele**
#### What type of PR is this?

/kind failing-test
/kind flake
/sig apps

#### What this PR does / why we need it:

This PR attempts to fix the flaky unit test `TestFinalizerCleanup` in the `job_controller_test.go`.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/121652

#### Special notes for your reviewer:
A description on what causes the flaky behaviour is described in the following comment https://github.com/kubernetes/kubernetes/issues/121652#issuecomment-1806701661

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/job/job_controller_test.go [hunk 1]
```diff
@@ -5253,7 +5253,7 @@ func TestFinalizerCleanup(t *testing.T) {
 	defer cancel()
 
 	clientset := fake.NewSimpleClientset()
-	sharedInformers := informers.NewSharedInformerFactory(clientset, controller.NoResyncPeriodFunc())
+	sharedInformers := informers.NewSharedInformerFactory(clientset, controller.StaticResyncPeriodFunc(1*time.Second)())
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller_test.go:5256]: This is not what the production code does, so it might just hide other bugs.

However, in production we don't disable workers for job sync or orphan pods, which I think would have caught the "missing" Pod.

A more robust hint is to call `manager.expectations.SatisfiedExpectations` in the test, after creating the pod.

Comment (dejanzele) [reply pkg/controller/job/job_controller_test.go:5256]: Could you please link me to an example, as I am not fully familiar with this logic?

Comment (alculquicondor) [reply pkg/controller/job/job_controller_test.go:5256]: https://github.com/kubernetes/kubernetes/blob/36930f4cb605450ccbe3126caad365aa5f51267c/pkg/controller/job/job_controller.go#L773

This map simply tells you whether the event handler has seen all created pods.... Although, you might need to increment the counter before creating the Pod (this is normally done by syncJob).

https://github.com/kubernetes/kubernetes/blob/36930f4cb605450ccbe3126caad365aa5f51267c/pkg/controller/job/job_controller.go#L1535

Comment (mimowo) [reply pkg/controller/job/job_controller_test.go:5256]: I've done pattern matching and moved locally 
```
	// Start the Pod and Job informers.
	sharedInformers.Start(ctx.Done())
	sharedInformers.WaitForCacheSync(ctx.Done())
```
before `go manager.Run`, as in other unit tests. This seems to fix the issue, but I don't exactly know why.

Comment (dejanzele) [reply pkg/controller/job/job_controller_test.go:5256]: I tried doing something like:
```
	job := newJob(1, 1, 1, batch.NonIndexedCompletion)
	job, err = clientset.BatchV1().Jobs(job.GetNamespace()).Create(ctx, job, metav1.CreateOptions{})
	if err != nil {
		t.Fatalf("Creating job: %v", err)
	}

	key, err := controller.KeyFunc(job)
	if err != nil {
		t.Errorf("Unexpected error getting job key: %v", err)
	}
	if err := manager.expectations.ExpectCreations(logger, key, 1); err != nil {
		t.Errorf("Unexpected error setting creation expectations: %v", err)
	}

	// Create a Pod with the job tracking finalizer
	pod := newPod("test-pod", job)
	pod.Finalizers = append(pod.Finalizers, batch.JobTrackingFinalizer)
	pod, err = clientset.CoreV1().Pods(pod.GetNamespace()).Create(ctx, pod, metav1.CreateOptions{})
	if err != nil {
		t.Fatalf("Creating pod: %v", err)
	}

	if err := wait.PollUntilContextTimeout(ctx, 100*time.Millisecond, wait.ForeverTestTimeout, true, func(ctx context.Context) (bool, error) {
		return manager.expectations.SatisfiedExpectations(logger, key), nil
	}); err != nil {
		t.Errorf("Waiting for Job expecations to get satisfied: %v", err)
	}
```

But now after ~35s I get the following error:
```
I1114 15:51:42.267620   62752 shared_informer.go:311] Waiting for caches to sync for job
I1114 15:51:42.267638   62752 shared_informer.go:318] Caches are synced for job
--- FAIL: TestFinalizerCleanup (30.20s)
    job_controller.go:224: I1114 15:51:42.267370] Starting job controller
    controller_utils.go:224: I1114 15:51:42.367794] Setting expectations expectations={}
    controller_utils.go:196: I1114 15:51:42.367948] Controller still waiting on expectations expectations={}
    job_controller.go:554: I1114 15:51:42.368107] enqueueing job key="default/foobar"
    controller_utils.go:196: I1114 15:51:42.468142] Controller still waiting on expectations expectations={}
    controller_utils.go:196: I1114 15:51:42.573333] Controller still waiting on expectations expectations={}
    controller_utils.go:196: I1114 15:51:42.669239] Controller still waiting on expectations expectations={}
    controller_utils.go:196: I1114 15:51:42.771465] Controller still waiting on expectations expectations={}
    controller_utils.go:196: I1114 15:51:42.869245] Controller still waiting on expectations expectations={}
    controller_utils.go:196: I1114 15:51:42.968475] Controller still waiting on expectations expectations={}
    controller_utils.go:196: I1114 15:51:43.069376] Controller still waiting on expectations expectations={}
    controller_utils.go:196: I1114 15:51:43.169245] Controller still waiting on expectations expectations={}
    controller_utils.go:196: I1114 15:51:43.268136] Controller still waiting on expectations expectations={}
    controller_utils.go:196: I1114 15:51:43.368991] Controller still waiting on expectations expectations={}
    controller_utils.go:196: I1114 15:51:43.468583] Controller still waiting on expectations expectations={}
    controller_utils.go:196: I1114 15:51:43.569034] Controller still waiting on expectations expectations={}
    controller_utils.go:196: I1114 15:51:43.668552] Controller still waiting on expectations expectations={}
    controller_utils.go:196: I1114 15:51:43.768183] Controller s
```

Comment (dejanzele) [reply pkg/controller/job/job_controller_test.go:5256]: And if I try just setting the `ExpectedCreations` to 1 in the `TestFinalizerCleanup` case without a call to `SatisfiedExpectations`, I get this error:
```
I1114 16:26:50.771182   70807 shared_informer.go:311] Waiting for caches to sync for job
I1114 16:26:50.771248   70807 shared_informer.go:318] Caches are synced for job
--- FAIL: TestFinalizerCleanup (30.10s)
    job_controller.go:224: I1114 16:26:50.771018] Starting job controller
    controller_utils.go:224: I1114 16:26:50.871967] Setting expectations expectations={}
    job_controller.go:554: I1114 16:26:50.872239] enqueueing job key="default/foobar"
    job_controller.go:554: I1114 16:26:50.872292] enqueueing job key="default/foobar"
    controller_utils.go:241: I1114 16:26:50.872447] Lowered expectations expectations={}
    job_controller.go:554: I1114 16:26:50.872484] enqueueing job key="default/foobar"
    job_controller_test.go:5320: Waiting for Pod to get the finalizer removed: context deadline exceeded
FAIL
```

It correctly sees the expectation, creates the Pod, lowers the expectation, but the Pod informer does not have it in its cache.

Who is responsible for updating the Pod informer cache? I fail to understand what happens under load so it doesn't have it in the cache?

Comment (dejanzele) [reply pkg/controller/job/job_controller_test.go:5256]: > This is not what the production code does, so it might just hide other bugs.
> 
> However, in production we don't disable workers for job sync or orphan pods, which I think would have caught the "missing" Pod.
> 
> A more robust hint is to call `manager.expectations.SatisfiedExpectations` in the test, after creating the pod.

I see that when Kubernetes starts controllers, they have a `ResyncPeriod` - https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L584

What could happen if we use a `ResyncPeriod` in the test? @alculquicondor

Comment (alculquicondor) [reply pkg/controller/job/job_controller_test.go:5256]: Re @mimowo
We should wait for caches to sync before starting the manager regardless. It's a good practice to only start the workers once we know that the cache is fully in sync.

The `ResyncPeriod` it's supposed to be at least tens of minutes, not a short time. So effectively, it should be infinity for the test.

Comment (dejanzele) [reply pkg/controller/job/job_controller_test.go:5256]: Ok, makes sense.

Still I am lost where is the issue, do we need to write the test in a different way or there is a bug which causes the Informer cache to not have the Pod under load?

Comment (alculquicondor) [reply pkg/controller/job/job_controller_test.go:5256]: The function `addPod` is called by the informer cache itself after it has added the Pod. So if you see `Lowered expectations`, then it means that the Pod should be in the cache.

I'm not sure what we can be missing.

Comment (dejanzele) [reply pkg/controller/job/job_controller_test.go:5256]: It works somewhat better now, but it still fails once every ~300 test runs.
With the expectations, the `podStore` returns a pod but now occassionally it fails in this block https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L292-L295

`jm.resolveControllerRef(pod.Namespace, controllerRef)` returns nil and the function returns, so the creation is not observed and it fails in the poll loop in the test when waiting for the `manager.expectations.SatisfiedExpectations` to return true.

Comment (alculquicondor) [reply pkg/controller/job/job_controller_test.go:5256]: maybe a "brute force" approach is ok.... you have access to the listers, just make sure they are not empty before proceeding. I guess we can do the same for making sure the pod is in the lister, instead of using the expectations.

**Comment by dejanzele** [comment]
@alculquicondor 
I like the "brute force" approach a bit better because it is clearer to understand what goes on.

File: pkg/controller/job/job_controller_test.go [hunk 2]
```diff
@@ -5254,34 +5254,50 @@ func TestFinalizerCleanup(t *testing.T) {
 
 	clientset := fake.NewSimpleClientset()
 	sharedInformers := informers.NewSharedInformerFactory(clientset, controller.NoResyncPeriodFunc())
+
```
Comment (mimowo) [inline pkg/controller/job/job_controller_test.go:5257]: nit: I would suggest making the diff as clean as possible to focus on the issue

File: pkg/controller/job/job_controller_test.go [hunk 3]
```diff
@@ -5254,34 +5254,50 @@ func TestFinalizerCleanup(t *testing.T) {
...
+	// Initialize the controller with 0 workers to make sure the
+	// pod finalizers are not removed by the "syncJob" function.
+	go manager.Run(ctx, 0)
 
 	// Create a simple Job
 	job := newJob(1, 1, 1, batch.NonIndexedCompletion)
 	job, err = clientset.BatchV1().Jobs(job.GetNamespace()).Create(ctx, job, metav1.CreateOptions{})
 	if err != nil {
-		t.Fatalf("Creating job: %v", err)
+		t.Fatalf("Could not create Job: %v", err)
```
Comment (mimowo) [inline pkg/controller/job/job_controller_test.go:5276]: I think there is no need to change this, let's keep the diff minimal

File: pkg/controller/job/job_controller_test.go [hunk 4]
```diff
@@ -5254,34 +5254,50 @@ func TestFinalizerCleanup(t *testing.T) {
...
+	}
+
+	// Await for the Job to appear in the jobLister to ensure so that Job Pod gets tracked correctly.
+	if err := wait.PollUntilContextTimeout(ctx, 100*time.Millisecond, wait.ForeverTestTimeout, false, func(ctx context.Context) (bool, error) {
```
Comment (mimowo) [inline pkg/controller/job/job_controller_test.go:5280]: This should be very fast, so maybe we could lower the poll interval to 10ms?

File: pkg/controller/job/job_controller_test.go [hunk 5]
```diff
@@ -5254,34 +5254,50 @@ func TestFinalizerCleanup(t *testing.T) {
...
+		job, _ := manager.jobLister.Jobs(job.GetNamespace()).Get(job.Name)
+		return job != nil, nil
+	}); err != nil {
+		t.Errorf("Waiting for Job object to appear in jobLister: %v", err)
```
Comment (mimowo) [inline pkg/controller/job/job_controller_test.go:5284]:
```suggestion
		t.Fatalf("Waiting for Job object to appear in jobLister: %v", err)
```
I think if we continue the test we can get misleading error messages.

File: pkg/controller/job/job_controller_test.go [hunk 6]
```diff
@@ -5254,34 +5254,50 @@ func TestFinalizerCleanup(t *testing.T) {
...
 	}
 
 	// Create a Pod with the job tracking finalizer
 	pod := newPod("test-pod", job)
 	pod.Finalizers = append(pod.Finalizers, batch.JobTrackingFinalizer)
 	pod, err = clientset.CoreV1().Pods(pod.GetNamespace()).Create(ctx, pod, metav1.CreateOptions{})
 	if err != nil {
-		t.Fatalf("Creating pod: %v", err)
+		t.Fatalf("Could not create Pod: %v", err)
```
Comment (mimowo) [inline pkg/controller/job/job_controller_test.go:5292]: nit: I suggest to revert it

File: pkg/controller/job/job_controller_test.go [hunk 7]
```diff
@@ -5254,34 +5254,50 @@ func TestFinalizerCleanup(t *testing.T) {
...
+	}
+
+	// Await for the Pod to appear in the podStore to ensure that finalizer gets properly removed.
+	if err := wait.PollUntilContextTimeout(ctx, 100*time.Millisecond, wait.ForeverTestTimeout, false, func(ctx context.Context) (bool, error) {
+		pod, _ := manager.podStore.Pods(pod.GetNamespace()).Get(pod.Name)
+		return pod != nil, nil
+	}); err != nil {
+		t.Errorf("Waiting for Pod to appear in podLister: %v", err)
```
Comment (mimowo) [inline pkg/controller/job/job_controller_test.go:5300]:
```suggestion
		t.Fatalf("Waiting for Pod to appear in podLister: %v", err)
```

File: pkg/controller/job/job_controller_test.go [hunk 8]
```diff
@@ -5291,7 +5307,7 @@ func TestFinalizerCleanup(t *testing.T) {
 	})
 	_, err = clientset.BatchV1().Jobs(job.GetNamespace()).UpdateStatus(ctx, job, metav1.UpdateOptions{})
 	if err != nil {
-		t.Fatalf("Updating job status: %v", err)
+		t.Fatalf("Failed to update Job status: %v", err)
```
Comment (mimowo) [inline pkg/controller/job/job_controller_test.go:5310]: nit: imo, revert

File: pkg/controller/job/job_controller_test.go [hunk 9]
```diff
@@ -5305,7 +5321,6 @@ func TestFinalizerCleanup(t *testing.T) {
 	}); err != nil {
 		t.Errorf("Waiting for Pod to get the finalizer removed: %v", err)
 	}
-
```
Comment (mimowo) [inline pkg/controller/job/job_controller_test.go:5308]: revert, just to keep the diff minimal

**Review by mimowo — COMMENTED** [review]
Just some nits, thank you for fixing

File: pkg/controller/job/job_controller_test.go [hunk 10]
```diff
@@ -5254,34 +5254,50 @@ func TestFinalizerCleanup(t *testing.T) {
...
 	// Create a Pod with the job tracking finalizer
 	pod := newPod("test-pod", job)
 	pod.Finalizers = append(pod.Finalizers, batch.JobTrackingFinalizer)
 	pod, err = clientset.CoreV1().Pods(pod.GetNamespace()).Create(ctx, pod, metav1.CreateOptions{})
 	if err != nil {
-		t.Fatalf("Creating pod: %v", err)
+		t.Fatalf("Could not create Pod: %v", err)
+	}
+
+	// Await for the Pod to appear in the podStore to ensure that finalizer gets properly removed.
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller_test.go:5295]:
```suggestion
	// Await for the Pod to appear in the podStore to ensure that the pod exists when cleaning up the Job.
	// In a production environment, there wouldn't be these guarantees, but the Pod would be cleaned up
	// by the orphan pod worker, when the Pod finishes.
```

**Review by alculquicondor — COMMENTED** [review]
/approve
Leaving lgtm to @mimowo

**Comment by alculquicondor** [comment]
It looks like we just missed the test freeze, but IIUC, the freeze is about not adding new tests, not about not fixing existing ones.

@soltysh could you add to the milestone?

**Comment by soltysh** [comment]
> @soltysh could you add to the milestone?

discussed this in [#release-ci-signal](https://kubernetes.slack.com/archives/CN0K3TE2C/p1700056467876219) and the general sentiment is that this has rather low flake rate (once per 2-3 days), so this can easily wait until after the freeze

/label tide/merge-method-squash

File: pkg/controller/job/job_controller_test.go [hunk 11]
```diff
@@ -5284,6 +5291,16 @@ func TestFinalizerCleanup(t *testing.T) {
 		t.Fatalf("Creating pod: %v", err)
 	}
 
+	// Await for the Pod to appear in the podStore to ensure that the pod exists when cleaning up the Job.
+	// In a production environment, there wouldn't be these guarantees, but the Pod would be cleaned up
+	// by the orphan pod worker, when the Pod finishes.
+	if err := wait.PollUntilContextTimeout(ctx, 100*time.Millisecond, wait.ForeverTestTimeout, false, func(ctx context.Context) (bool, error) {
```
Comment (mimowo) [inline pkg/controller/job/job_controller_test.go:5297]: Let also use 10ms here, for the same reason.

File: pkg/controller/job/job_controller_test.go (hunk 9 above)
Comment (mimowo) [reply pkg/controller/job/job_controller_test.go:5308]: Can you also please handle this nit?

Comment (dejanzele) [reply pkg/controller/job/job_controller_test.go]: oh sorry @mimowo, this one slipped, should be fixed now
