### PR TITLE
Show the details on the failure of preemption

### LINKED ISSUE #97182: Need more info on why the preemption failed - real failed plugins are hidden
**What would you like to be added**:
I need more details on why a high priority pod cannot preempt other low priority pods to release room for scheduling.

**Why is this needed**:
The main scheduling can tell why a pod failed to schedule in the first place, but the status is silently ignored in the stage of preemption.

https://github.com/kubernetes/kubernetes/blob/ccd29ea264535fa2ef36cf4dfb004fed99c99fbf/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L629-L635

While the real failed plugin might be hidden, i.e. the main scheduling cycle report the status is "Insufficient cpu", but after removing all the low priority pods the real failed plugin for the preemption might be "pod affinity", "spreading" etc.

We need a way to tell why the preemption failed in the cluster, particularly,  the preemption result into a deadlock due to `UnschedulableAndUnresolvable` status and no way to schedule but useless looping.
 
/sig scheduling
/assign

### PR DESCRIPTION
**Pull request by chendave**
Since the filter status is missed for the phase of preemption, there will be no way to tell why the preemption failed for some reasons, and those reasons could be different with the status from the main scheduling process (the first failed plugin will hide other failures in the chain).

~The change fixes the gap by providing the following~
~- If the preemption is failed for the `FitError`, return the status as what main scheduling process does.~
~- For other failure, log warning message and provide info for root causing.~

This change provides verbose information based on the node status generated by during pod preemption, those information help us to diagnose the issue on why pod cannot be scheduled even after pod preemption.

Signed-off-by: Dave Chen <dave.chen@arm.com>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/97182

**Special notes for your reviewer**:
As a comparison, what we have in the log of scheduler if no candidate node is found after pod preemption, 

Before the change, 
```
I0108 14:50:27.057654    6311 scheduler.go:469] "Status after running PostFilter plugins for pod" pod="default/preemptor" status=&{code:2 reasons:[] err:<nil>}
```

After the change, 
```
I0108 14:48:25.316490    3390 scheduler.go:469] "Status after running PostFilter plugins for pod" pod="default/preemptor" status=&{code:2 reasons:[0/30 nodes are available: 10 Insufficient cpu, 20 node(s) didn't match pod affinity rules, 20 node(s) didn't match pod affinity/anti-affinity.] err:<nil>}
```

@alculquicondor  @ahg-g  @damemi  looking for someone who has bandwidth on this ;), thanks for your time in the advance!

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/sig scheduling

### CODE REVIEW

**Comment by chendave** [comment]
rebased

**Comment by ahg-g** [comment]
I will take a look

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 1]
```diff
@@ -578,6 +632,7 @@ func selectVictimsOnNode(
 	pod *v1.Pod,
 	nodeInfo *framework.NodeInfo,
 	pdbs []*policy.PodDisruptionBudget,
+	nodeStatuses *nodeToStatusMap,
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:635]: Instead of doing this, lets just return node status instead of the fit boolean. the caller then deals with the status as it sees fit.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 2]
```diff
@@ -60,6 +64,36 @@ type DefaultPreemption struct {
...
+		for k, v := range reasons {
+			reasonStrings = append(reasonStrings, fmt.Sprintf("%v %v", v, k))
+		}
+		sort.Strings(reasonStrings)
+		return reasonStrings
+	}
+	reasonMsg := fmt.Sprintf(NoNodeAvailableMsg+": %v.", f.NumAllNodes, strings.Join(sortReasonsHistogram(), ", "))
+	return reasonMsg
+}
+
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:96]: lets move FitError to framework/types.go and so we don't need to duplicate this code here.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 3]
```diff
@@ -214,8 +251,17 @@ func (pl *DefaultPreemption) FindCandidates(ctx context.Context, state *framewor
 		}
 		klog.Infof("from a pool of %d nodes (offset: %d, sample %d nodes: %v), ~%d candidates will be chosen", len(potentialNodes), offset, len(sample), sample, numCandidates)
 	}
-
-	return dryRunPreemption(ctx, pl.fh, state, pod, potentialNodes, pdbs, offset, numCandidates), nil
+	candidates, nodeStatus := dryRunPreemption(ctx, pl.fh, state, pod, potentialNodes, pdbs, offset, numCandidates)
+	// Build the PreemptionFitError only when there is no candidates could be found, and send it back to main scheduler process where it will tell the details on the reason
+	// why the pod is failed to find a node to scheduler even after the pod preemption.
+	if len(candidates) == 0 && len(nodeStatus) != 0 {
+		return candidates, &PreemptionFitError{
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:258]: Lets change `FindCandidates` to return three values, candidates, filteredNodesStatuses and error.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 4]
```diff
@@ -624,10 +681,14 @@ func selectVictimsOnNode(
 	// support this case for performance reasons. Having affinity to lower
 	// priority pods is not a recommended configuration anyway.
 	if status := fh.RunFilterPluginsWithNominatedPods(ctx, state, pod, nodeInfo); !status.IsSuccess() {
+		// `framework.Error` will not be included in the status map, this align with main scheduler process, log the warning
+		// message here and continue to check other `potentialNodes`.
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:685]: since we are not breaking on error like we do in generic_scheduler.go, I think we should add it to the map.

Comment (ahg-g) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:685]: in any case, this function should simply return status.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 3 above)
Comment (ahg-g) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:258]: this is just so external preemption plugins that use this interface can benefit from this info, but this is less critical for this PR.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 5]
```diff
@@ -654,20 +682,22 @@ func selectVictimsOnNode(
 	}
 	for _, p := range violatingVictims {
 		if fits, err := reprievePod(p); err != nil {
-			klog.Warningf("Failed to reprieve pod %q: %v", p.Name, err)
-			return nil, 0, false
+			message := fmt.Sprintf("Failed to reprieve violating pod %q: %v", p.Name, err)
+			finalStatus = framework.NewStatus(framework.Error, message)
+			return nil, 0, finalStatus
```
Comment (chendave) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:687]: previous logic is that if there is any error happen within `reprievePod`,  the bool `fits` that is returned is `false`, so I follow this logic to handle the `status` as well, but I think this is debatable, because we already found the candidate, the error we found  for such `reprieve` should not de-candidate this node. 

If you agree with my points here, I'd happy to post a follow up to add it.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 3 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: okay, I will take care it after this one.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 4 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 2 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Great suggestion!
Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 1 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Done

**Comment by chendave** [comment]
@ahg-g , thanks for the review! I hope all the  comments were addressed.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 6]
```diff
@@ -300,22 +313,33 @@ func (cl *candidateList) get() []Candidate {
 	return cl.items[:cl.size()]
 }
 
+// nodeToStatusMap is used to record node status.
+type nodeToStatus struct {
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:317]: we don't need this type, the mutex can be defined as a local variable inside dryRunPreemption.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 7]
```diff
@@ -300,22 +313,33 @@ func (cl *candidateList) get() []Candidate {
...
 	checkNode := func(i int) {
 		nodeInfoCopy := potentialNodes[(int(offset)+i)%len(potentialNodes)].Clone()
 		stateCopy := state.Clone()
-		pods, numPDBViolations, fits := selectVictimsOnNode(ctx, fh, stateCopy, pod, nodeInfoCopy, pdbs)
-		if fits {
+		pods, numPDBViolations, status := selectVictimsOnNode(ctx, fh, stateCopy, pod, nodeInfoCopy, pdbs)
+		nodeStatus.Lock()
+		nodeStatus.status[nodeInfoCopy.Node().Name] = status
+		nodeStatus.Unlock()
+		if status.Code() == framework.Success {
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:342]:
```suggestion
		if status.IsSuccess() {
```

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 8]
```diff
@@ -300,22 +313,33 @@ func (cl *candidateList) get() []Candidate {
...
 // candidates, ones that do not violate PDB are preferred over ones that do.
 func dryRunPreemption(ctx context.Context, fh framework.Handle,
 	state *framework.CycleState, pod *v1.Pod, potentialNodes []*framework.NodeInfo,
-	pdbs []*policy.PodDisruptionBudget, offset int32, numCandidates int32) []Candidate {
+	pdbs []*policy.PodDisruptionBudget, offset int32, numCandidates int32) ([]Candidate, framework.NodeToStatusMap) {
 	nonViolatingCandidates := newCandidateList(numCandidates)
 	violatingCandidates := newCandidateList(numCandidates)
 	parallelCtx, cancel := context.WithCancel(ctx)
-
+	nodeStatus := &nodeToStatus{
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:332]: I would name the variable nodeStatuses

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 9]
```diff
@@ -623,12 +651,12 @@ func selectVictimsOnNode(
 	// inter-pod affinity to one or more victims, but we have decided not to
 	// support this case for performance reasons. Having affinity to lower
 	// priority pods is not a recommended configuration anyway.
-	if status := fh.RunFilterPluginsWithNominatedPods(ctx, state, pod, nodeInfo); !status.IsSuccess() {
-		if status.Code() == framework.Error {
-			klog.Warningf("Encountered error while selecting victims on node %v: %v", nodeInfo.Node().Name, status.AsError())
+	if finalStatus = fh.RunFilterPluginsWithNominatedPods(ctx, state, pod, nodeInfo); !finalStatus.IsSuccess() {
+		if finalStatus.Code() == framework.Error {
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:655]: we probably don't need this, just return the status as is.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go [hunk 10]
```diff
@@ -125,6 +126,7 @@ func TestPostFilter(t *testing.T) {
 			wantResult: &framework.PostFilterResult{NominatedNodeName: "node1"},
 			wantStatus: framework.NewStatus(framework.Success),
 		},
+		// TODO:
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:129]: ?

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 11]
```diff
@@ -607,14 +631,18 @@ func selectVictimsOnNode(
...
+				finalStatus = framework.NewStatus(framework.Error, message)
+				return nil, 0, finalStatus
 			}
 		}
 	}
 
 	// No potential victims are found, and so we don't need to evaluate the node again since its state didn't change.
 	if len(potentialVictims) == 0 {
-		return nil, 0, false
+		message := fmt.Sprintf("No victims found on node %v for the preemptor pod %v", nodeInfo.Node().Name, pod.Name)
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:643]:
```suggestion
		message := fmt.Sprintf("No victims found on node %v for preemptor pod %v", nodeInfo.Node().Name, pod.Name)
```

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 5 above)
Comment (ahg-g) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:687]: lets keep it as is, this is an unexpected error, something really is off if this happens.

**Review by ahg-g — COMMENTED** [review]
Thanks, haven't looked at the tests yet.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go (hunk 10 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go:129]: hmm.... my bad.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 12]
```diff
@@ -93,6 +94,9 @@ func (pl *DefaultPreemption) PostFilter(ctx context.Context, state *framework.Cy
 
 	nnn, err := pl.preempt(ctx, state, pod, m)
 	if err != nil {
+		if _, ok := err.(*framework.FitError); ok {
+			return nil, framework.NewStatus(framework.Unschedulable, err.Error())
+		}
 		return nil, framework.AsStatus(err)
 	}
 	if nnn == "" {
```
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:103]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 13]
```diff
@@ -214,8 +218,17 @@ func (pl *DefaultPreemption) FindCandidates(ctx context.Context, state *framewor
 		}
 		klog.Infof("from a pool of %d nodes (offset: %d, sample %d nodes: %v), ~%d candidates will be chosen", len(potentialNodes), offset, len(sample), sample, numCandidates)
 	}
-
-	return dryRunPreemption(ctx, pl.fh, state, pod, potentialNodes, pdbs, offset, numCandidates), nil
+	candidates, nodeStatus := dryRunPreemption(ctx, pl.fh, state, pod, potentialNodes, pdbs, offset, numCandidates)
```
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 8 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 9 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go (hunk 10 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 11 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 14]
```diff
@@ -300,22 +313,33 @@ func (cl *candidateList) get() []Candidate {
...
+// nodeToStatusMap is used to record node status.
+type nodeToStatus struct {
+	status framework.NodeToStatusMap
+	sync.Mutex
+}
+
 // dryRunPreemption simulates Preemption logic on <potentialNodes> in parallel,
-// and returns preemption candidates. The number of candidates depends on the
-// constraints defined in the plugin's args. In the returned list of
+// returns preemption candidates and a status map which explain why pod cannot be scheduled to each node.
```
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 15]
```diff
@@ -214,8 +218,17 @@ func (pl *DefaultPreemption) FindCandidates(ctx context.Context, state *framewor
 		}
 		klog.Infof("from a pool of %d nodes (offset: %d, sample %d nodes: %v), ~%d candidates will be chosen", len(potentialNodes), offset, len(sample), sample, numCandidates)
 	}
-
-	return dryRunPreemption(ctx, pl.fh, state, pod, potentialNodes, pdbs, offset, numCandidates), nil
+	candidates, nodeStatus := dryRunPreemption(ctx, pl.fh, state, pod, potentialNodes, pdbs, offset, numCandidates)
+	// Build the FitError only when there is no candidates could be found, and send it back to main scheduler process where it will tell the details on the reason
+	// why the pod is failed to find a node to scheduler even after the pod preemption.
```
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 6 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:317]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 5 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:682]: ACK.

**Comment by chendave** [comment]
@ahg-g , thanks for all those great suggestion!

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 16]
```diff
@@ -607,14 +624,18 @@ func selectVictimsOnNode(
 		if corev1helpers.PodPriority(p.Pod) < podPriority {
 			potentialVictims = append(potentialVictims, p.Pod)
 			if err := removePod(p.Pod); err != nil {
-				return nil, 0, false
+				message := fmt.Sprintf("Failed to remove victim pod %v on node %v: %v", p.Pod.Name, nodeInfo.Node().Name, err.Error())
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:627]: `RunPreFilterExtensionRemovePod` seems to have already returned verbosed error info, I'd suggest simplifying the final message.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 17]
```diff
@@ -301,21 +314,25 @@ func (cl *candidateList) get() []Candidate {
...
+	var statusesLock sync.Mutex
 	checkNode := func(i int) {
 		nodeInfoCopy := potentialNodes[(int(offset)+i)%len(potentialNodes)].Clone()
 		stateCopy := state.Clone()
-		pods, numPDBViolations, fits := selectVictimsOnNode(ctx, fh, stateCopy, pod, nodeInfoCopy, pdbs)
-		if fits {
+		pods, numPDBViolations, status := selectVictimsOnNode(ctx, fh, stateCopy, pod, nodeInfoCopy, pdbs)
+		statusesLock.Lock()
+		nodeStatuses[nodeInfoCopy.Node().Name] = status
+		statusesLock.Unlock()
```
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:334]: We will save all the status for each of the node, and consume the status where it is needed, 
- populate a overall status and write in the log
- check whether a node fits after processing by `selectVictimsOnNode`

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 18]
```diff
@@ -578,9 +595,9 @@ func selectVictimsOnNode(
 	pod *v1.Pod,
 	nodeInfo *framework.NodeInfo,
 	pdbs []*policy.PodDisruptionBudget,
-) ([]*v1.Pod, int, bool) {
+) ([]*v1.Pod, int, *framework.Status) {
 	var potentialVictims []*v1.Pod
-
+	var finalStatus = framework.NewStatus(framework.Success)
```
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:600]: we need this because we need a status to be returned at line @639.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 19]
```diff
@@ -301,21 +314,25 @@ func (cl *candidateList) get() []Candidate {
...
 // candidates, ones that do not violate PDB are preferred over ones that do.
 func dryRunPreemption(ctx context.Context, fh framework.Handle,
 	state *framework.CycleState, pod *v1.Pod, potentialNodes []*framework.NodeInfo,
-	pdbs []*policy.PodDisruptionBudget, offset int32, numCandidates int32) []Candidate {
+	pdbs []*policy.PodDisruptionBudget, offset int32, numCandidates int32) ([]Candidate, framework.NodeToStatusMap) {
 	nonViolatingCandidates := newCandidateList(numCandidates)
 	violatingCandidates := newCandidateList(numCandidates)
 	parallelCtx, cancel := context.WithCancel(ctx)
-
+	var nodeStatuses = make(framework.NodeToStatusMap)
```
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 20]
```diff
@@ -93,8 +94,12 @@ func (pl *DefaultPreemption) PostFilter(ctx context.Context, state *framework.Cy
 
 	nnn, err := pl.preempt(ctx, state, pod, m)
 	if err != nil {
+		if _, ok := err.(*framework.FitError); ok {
+			return nil, framework.NewStatus(framework.Unschedulable, err.Error())
+		}
 		return nil, framework.AsStatus(err)
 	}
+	// This happens when the pod is not eligiable for preemption or extenders filtered all candidates.
```
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 16 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:627]: yes, that looks more neat.

**Comment by chendave** [comment]
@Huang-Wei thanks for the review!

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 17 above)
[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:334]: I missed this, I agree with Wei. This map will be used in FitError.FilteredNodesStatuses

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:600]: you can just return success at the end.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 21]
```diff
@@ -607,14 +624,17 @@ func selectVictimsOnNode(
 		if corev1helpers.PodPriority(p.Pod) < podPriority {
 			potentialVictims = append(potentialVictims, p.Pod)
 			if err := removePod(p.Pod); err != nil {
-				return nil, 0, false
+				finalStatus = framework.NewStatus(framework.Error, err.Error())
+				return nil, 0, finalStatus
```
Comment (ahg-g) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:628]:
```suggestion
				return nil, 0, framework.NewStatus(framework.Error, err.Error())
```

and the others below

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 17 above)
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:334]: > We will save all the status for each of the node

I guess we don't need successful entries, just like what the regular Filtering logic does.

[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 21 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Done

**Comment by chendave** [comment]
@ahg-g  @Huang-Wei  are you okay with this version? if so, I will squash the commits.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 22]
```diff
@@ -623,12 +641,8 @@ func selectVictimsOnNode(
 	// inter-pod affinity to one or more victims, but we have decided not to
 	// support this case for performance reasons. Having affinity to lower
 	// priority pods is not a recommended configuration anyway.
-	if status := fh.RunFilterPluginsWithNominatedPods(ctx, state, pod, nodeInfo); !status.IsSuccess() {
-		if status.Code() == framework.Error {
-			klog.Warningf("Encountered error while selecting victims on node %v: %v", nodeInfo.Node().Name, status.AsError())
-		}
-
-		return nil, 0, false
+	if finalStatus := fh.RunFilterPluginsWithNominatedPods(ctx, state, pod, nodeInfo); !finalStatus.IsSuccess() {
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:644]: nit: s/finalStatus/status/

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 23]
```diff
@@ -654,20 +668,19 @@ func selectVictimsOnNode(
...
 			numViolatingVictim++
 		}
 	}
 	// Now we try to reprieve non-violating victims.
 	for _, p := range nonViolatingVictims {
 		if _, err := reprievePod(p); err != nil {
-			klog.Warningf("Failed to reprieve pod %q: %v", p.Name, err)
-			return nil, 0, false
+			finalStatus := framework.NewStatus(framework.Error, err.Error())
+			return nil, 0, finalStatus
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:680]:
```suggestion
			return nil, 0, framework.NewStatus(framework.Error, err.Error())
```

File: pkg/scheduler/scheduler.go [hunk 24]
```diff
@@ -457,14 +457,17 @@ func (sched *Scheduler) scheduleOne(ctx context.Context) {
...
-		if fitError, ok := err.(*core.FitError); ok {
+		if fitError, ok := err.(*framework.FitError); ok {
 			if !fwk.HasPostFilterPlugins() {
 				klog.V(3).InfoS("No PostFilter plugins are registered, so no preemption will be performed")
 			} else {
 				// Run PostFilter plugins to try to make the pod schedulable in a future scheduling cycle.
 				result, status := fwk.RunPostFilterPlugins(ctx, state, pod, fitError.FilteredNodesStatuses)
 				if status.Code() == framework.Error {
 					klog.ErrorS(nil, "Status after running PostFilter plugins for pod", klog.KObj(pod), "status", status)
+				} else if status.Code() == framework.Unschedulable {
```
Comment (Huang-Wei) [inline pkg/scheduler/scheduler.go:468]: nit: I think we should also include `UnschedulableAndUnresovlable`, so:

```suggestion
				} else if status.IsUnschedulable() {
```

**Review by Huang-Wei — COMMENTED** [review]
Some nits. LGTM otherwise.

**Comment by Huang-Wei** [comment]
> @ahg-g @Huang-Wei are you okay with this version? if so, I will squash the commits.

Some nits above, you may squash the commits along with resolving them. Thanks.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 22 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Done

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 23 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: Done

File: pkg/scheduler/scheduler.go (hunk 24 above)
Comment (chendave) [reply pkg/scheduler/scheduler.go]: cool, updated!

**Comment by chendave** [comment]
commit squashed, nits addressed.

**Comment by Huang-Wei** [comment]
/lgtm
leaving /approve to @ahg-g .

File: pkg/scheduler/scheduler.go [hunk 25]
```diff
@@ -457,14 +457,17 @@ func (sched *Scheduler) scheduleOne(ctx context.Context) {
...
 			if !fwk.HasPostFilterPlugins() {
 				klog.V(3).InfoS("No PostFilter plugins are registered, so no preemption will be performed")
 			} else {
 				// Run PostFilter plugins to try to make the pod schedulable in a future scheduling cycle.
 				result, status := fwk.RunPostFilterPlugins(ctx, state, pod, fitError.FilteredNodesStatuses)
 				if status.Code() == framework.Error {
 					klog.ErrorS(nil, "Status after running PostFilter plugins for pod", klog.KObj(pod), "status", status)
+				} else if status.IsUnschedulable() {
+					// In case there is no node available after running of post filter plugins, the details could be found in the log.
+					klog.Warningf("Status after running PostFilter plugins for pod", "pod", klog.KObj(pod), "status", status)
```
Comment (ahg-g) [inline pkg/scheduler/scheduler.go:470]: the new logging framework doesn't support warnings (ErrorS and InfoS only), existing warning should be changed to either an error or info, and in this case it is info, so lets revert this change.

Comment (chendave) [reply pkg/scheduler/scheduler.go]: Good to know!  have reverted.

**Comment by ahg-g** [comment]
/lgtm
/approve 

Thanks!

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 3 above)
Comment (chendave) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: please see: https://github.com/kubernetes/kubernetes/pull/98129
