### PR TITLE
Propagate cotnext to avoid goroutine leak

### LINKED ISSUE #129908: Failure cluster [9b21fb6e...]: goroutine leak in k8s.io/kubernetes/test/integration.kubelet
##### Error text:
```
Failed
PASS
FAIL	k8s.io/kubernetes/test/integration/kubelet	71.460s

```

##### Stdout:
```
I0118 17:21:38.860959  112097 etcd.go:73] etcd already running at http://127.0.0.1:2379
PASS
E0118 17:22:50.158489  112097 etcd.go:236] "EtcdMain goroutine check" err=<
	found unexpected goroutines:
	[Goroutine 30115 in state IO wait, 1 minutes, with internal/poll.runtime_pollWait on top of the stack:
	internal/poll.runtime_pollWait(0x7f32dc337840, 0x72)
		/usr/local/go/src/runtime/netpoll.go:351 +0x85
	internal/poll.(*pollDesc).wait(0xc009e96f00?, 0xc007abc800?, 0x0)
		/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
	internal/poll.(*pollDesc).waitRead(...)
		/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
	internal/poll.(*FD).Read(0xc009e96f00, {0xc007abc800, 0x800, 0x800})
		/usr/local/go/src/internal/poll/fd_unix.go:165 +0x27a
	net.(*netFD).Read(0xc009e96f00, {0xc007abc800?, 0xc009181a70?, 0xc009181ac0?})
		/usr/local/go/src/net/fd_posix.go:55 +0x25
	net.(*conn).Read(0xc007a221c0, {0xc007abc800?, 0xc01061ec00?, 0xc007abc805?})
		/usr/local/go/src/net/net.go:189 +0x45
	crypto/tls.(*atLeastReader).Read(0xc0089863d8, {0xc007abc800?, 0x0?, 0xc0089863d8?})
		/usr/local/go/src/crypto/tls/conn.go:809 +0x3b
	bytes.(*Buffer).ReadFrom(0xc01063e638, {0x3e5b300, 0xc0089863d8})
		/usr/local/go/src/bytes/buffer.go:211 +0x98
	crypto/tls.(*Conn).readFromUntil(0xc01063e388, {0x3e58b40, 0xc007a221c0}, 0xc009181b30?)
		/usr/local/go/src/crypto/tls/conn.go:831 +0xde
	crypto/tls.(*Conn).readRecordOrCCS(0xc01063e388, 0x0)
		/usr/local/go/src/crypto/tls/conn.go:629 +0x3cf
	crypto/tls.(*Conn).readRecord(...)
		/usr/local/go/src/crypto/tls/conn.go:591
	crypto/tls.(*Conn).Read(0xc01063e388, {0xc003c58e40, 0x9, 0xc009181f50?})
		/usr/local/go/src/crypto/tls/conn.go:1385 +0x150
	io.ReadAtLeast({0x7f32dc43a720, 0xc01063e388}, {0xc003c58e40, 0x9, 0x9}, 0x9)
		/usr/local/go/src/io/io.go:335 +0x90
	io.ReadFull(...)
		/usr/local/go/src/io/io.go:354
	golang.org/x/net/http2.readFrameHeader({0xc003c58e40, 0x9, 0xc004cb9d80?}, {0x7f32dc43a720?, 0xc01063e388?})
		/home/prow/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x65
	golang.org/x/net/http2.(*Framer).ReadFrame(0xc003c58e00)
		/home/prow/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:501 +0x85
	golang.org/x/net/http2.(*serverConn).readFrames(0xc0016dd860)
		/home/prow/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:855 +0x98
	created by golang.org/x/net/http2.(*serverConn).serve in goroutine 30058
		/home/prow/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:978 +0x60a
	 Goroutine 30103 in state IO wait, 1 minutes, with internal/poll.runtime_pollWait on top of the stack:
	internal/poll.runtime_pollWait(0x7f32dc3373e0, 0x72)
		/usr/local/go/src/runtime/netpoll.go:351 +0x85
	internal/poll.(*pollDesc).wait(0xc009978800?, 0xc010732000?, 0x0)
		/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x27
	internal/poll.(*pollDesc).waitRead(...)
		/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
	internal/poll.(*FD).Read(0xc009978800, {0xc010732000, 0x1000, 0x1000})
		/usr/local/go/src/internal/poll/fd_unix.go:165 +0x27a
	net.(*netFD).Read(0xc009978800, {0xc010732000?, 0xc0101bda30?, 0xc0101bd9a0?})
		/usr/local/go/src/net/fd_posix.go:55 +0x25
	net.(*conn).Read(0xc0076cf060, {0xc010732000?, 0xc010419ce0?, 0xc010732005?})
		/usr/local/go/src/net/net.go:189 +0x45
	crypto/tls.(*atLeastReader).Read(0xc0086727b0, {0xc010732000?, 0x0?, 0xc0086727b0?})
		/usr/local/go/src/crypto/tls/conn.go:809 +0x3b
	bytes.(*Buffer).ReadFrom(0xc00d37f438, {0x3e5b300, 0xc0086727b0})
		/usr/local/go/src/bytes/buffer.go:211 +0x98
	crypto/tls.(*Conn).readFromUntil(0xc00d37f188, {0x3e58b40, 0xc0076cf060}, 0xc0101bda10?)
		/usr/local/go/src/crypto/tls/conn.go:831 +0xde
	crypto/tls.(*Conn).readRecordOrCCS(0xc00d37f188, 0x0)
		/usr/local/go/src/crypto/tls/conn.go:629 +0x3cf
	crypto/tls.(*Conn).readRecord(...)
		/usr/local/go/src/crypto/tls/conn.go:591
	crypto/tls.(*Conn).Read(0xc00d37f188, {0xc01073a000, 0x1000, 0x0?})
		/usr/local/go/src/crypto/tls/conn.go:1385 +0x150
	bufio.(*Reader).Read(0xc010729d40, {0xc004ed4c80, 0x9, 0xc00ce6b180?})
		/usr/local/go/src/bufio/bufio.go:241 +0x197
	io.ReadAtLeast({0x3e57320, 0xc010729d40}, {0xc004ed4c80, 0x9, 0x9}, 0x9)
		/usr/local/go/src/io/io.go:335 +0x90
	io.ReadFull(...)
		/usr/local/go/src/io/io.go:354
	golang.org/x/net/http2.readFrameHeader({0xc004ed4c80, 0x9, 0x89e4cb?}, {0x3e57320?, 0xc010729d40?})
		/home/prow/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:237 +0x65
	golang.org/x/net/http2.(*Framer).ReadFrame(0xc004ed4c40)
		/home/prow/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/frame.go:501 +0x85
	golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0101bdfa8)
		/home/prow/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:2498 +0xda
	golang.org/x/net/http2.(*ClientConn).readLoop(0xc010489c00)
		/home/prow/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:2377 +0x7c
	created by golang.org/x/net/http2.(*Transport).newClientConn in goroutine 30102
		/home/prow/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/transport.go:911 +0xdfb
	 Goroutine 30058 in state select, 1 minutes, with golang.org/x/net/http2.(*serverConn).serve on top of the stack:
	golang.org/x/net/http2.(*serverConn).serve(0xc0016dd860, {0x64, 0x1000, 0x1000, 0x40000, 0x1900000, 0x40000, 0x0, 0x37e11d600, 0x0, ...})
		/home/prow/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:987 +0x98f
	golang.org/x/net/http2.(*Server).serveConn(0xc00394a9a0, {0x3ea8ad8, 0xc01063e388}, 0xc010647af8, 0x0)
		/home/prow/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:566 +0xc19
	golang.org/x/net/http2.(*Server).ServeConn(...)
		/home/prow/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:425
	golang.org/x/net/http2.ConfigureServer.func1(0xc003c96b40, {0x3ea8ad8, 0xc01063e388}, {0x3e57e20, 0xc01061ec20}, 0x0)
		/home/prow/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:325 +0x165
	golang.org/x/net/http2.ConfigureServer.func2(0x358e200?, 0xc010647ea8?, {0x3e57e20?, 0xc01061ec20?})
		/home/prow/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:333 +0x35
	net/http.(*conn).serve(0xc00d66b440, {0x3e98840, 0xc004a24270})
		/usr/local/go/src/net/http/server.go:2000 +0x1213
	created by net/http.(*Server).Serve in goroutine 2381
		/usr/local/go/src/net/http/server.go:3360 +0x485
	]
 >
FAIL	k8s.io/kubernetes/test/integration/kubelet	71.460s
```

#### Recent failures:
[1/18/2025, 5:35:31 PM ci-kubernetes-integration-master](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-master/1880654907791380480)

/kind failing-test
/kind flake
/sig node

### PR DESCRIPTION
**Pull request by sivchari**
#### What type of PR is this?

/kind bug
/kind flake
/kind failing-test
/sig node

#### What this PR does / why we need it:

As far as I can see, this error seems to happen on http2 communication in golang.org/x/http. 
Thus, it passes the context to the all I/O waiting that could happen and communications instead of context.TODO(). As a result, when the test is finished, the all connection is canceled by context cancellation.
I think it will resolve the goroutine leak.
I'm welcome to teach me about other view of point, thanks.

#### Which issue(s) this PR fixes:

Fixes #129908 

#### Does this PR introduce a user-facing change?

```release-note

```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by ffromani** [comment]
/triage accepted
/priority backlog

at glance this seems a nice fix anyway

**Comment by haircommander** [comment]
/lgtm

this makes sense to me!

**Review by SergeyKanzhelev — APPROVED** [review]
/approve

File: test/integration/kubelet/watch_manager_test.go [hunk 1]
```diff
@@ -40,7 +40,10 @@ import (
 func TestWatchBasedManager(t *testing.T) {
 	testNamespace := "test-watch-based-manager"
 	server := kubeapiservertesting.StartTestServerOrDie(t, nil, framework.DefaultTestServerFlags(), framework.SharedEtcd())
-	defer server.TearDownFn()
+	t.Cleanup(server.TearDownFn)
+
+	ctx, cancel := context.WithCancel(context.Background())
+	t.Cleanup(cancel)
```
Comment (pohly) [inline test/integration/kubelet/watch_manager_test.go:46]: `k8s.io/kubernetes/test/utils/ktesting.Init` can be used to create a context which uses `t` for contextual logging and automatically gets canceled when the test is done.

**Review by pohly — COMMENTED** [review]
I would have done this a bit differently, but no need for a follow-up.

File: test/integration/kubelet/watch_manager_test.go [hunk 2]
```diff
@@ -66,7 +69,8 @@ func TestWatchBasedManager(t *testing.T) {
 	fakeClock := testingclock.NewFakeClock(time.Now())
 
 	stopCh := make(chan struct{})
-	defer close(stopCh)
+	t.Cleanup(func() { close(stopCh) })
```
[the remark this answers is not in the document]
Comment (sivchari) [reply test/integration/kubelet/watch_manager_test.go:72]: Make sense to me.

File: test/integration/kubelet/watch_manager_test.go (hunk 1 above)
Comment (sivchari) [reply test/integration/kubelet/watch_manager_test.go:46]: I've never known this library. How useful !
Thanks.
