### PR TITLE
DRA: Fix flaky integration test

### LINKED ISSUE #135422: Failure cluster [c4bff851...]
##### Error text:
```
Failed
=== RUN   TestDRA/all/PrioritizedListScoring/multi-claim
  Trace[1822381739]: ---"Snapshotting scheduler cache and node infos done" 0ms (05:06:46.006)
  Trace[1822381739]: ---"Computing predicates done" 356ms (05:06:46.363)
  Trace[1822381739]: ---"Prioritizing done" 0ms (05:06:46.363)
  Trace[1822381739]: [357.120466ms] [357.120466ms] END
        Timed out after 10.014s.
        Value for field 'Status.Allocation' failed to satisfy matcher.
        Expected
            <string>: AllocationResult
        to match fields: {
        .Devices.Results:
        	Expected
        	    <[]v1.DeviceRequestAllocationResult | len:1, cap:1>: 
        	        - device: device-1
        	          driver: testdra-all-prioritizedlistscoring-ztntq-worker-6.driver
        	          pool: worker-6
        	          request: req-1/subreq-0
        	to have exact elements with
        	    <[]*gstruct.FieldsMatcher | len:1, cap:1>: [
        	        {
        	            Fields: {
        	                "Request": <*matchers.EqualMatcher | 0xc00501b6a0>{
        	                    Expected: <string>"req-1/subreq-1",
        	                },
        	                "Driver": <*matchers.EqualMatcher | 0xc00501b6c0>{
        	                    Expected: <string>"testdra-all-prioritizedlistscoring-ztntq-worker-2.driver",
        	                },
        	                "Pool": <*matchers.EqualMatcher | 0xc00501b6e0>{
        	                    Expected: <string>"worker-2
```
#### Recent failures:
[2025/11/23 11:37:38 ci-kubernetes-integration-master](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-master/1992437259244146688)
[2025/11/22 22:40:53 ci-kubernetes-integration-master-s390x](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-master-s390x/1992241718245724160)
[2025/11/21 17:20:36 ci-kubernetes-integration-master](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-master/1991798794571747328)
[2025/11/21 01:06:51 ci-kubernetes-integration-master-s390x](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-master-s390x/1991553676266704896)
[2025/11/20 08:58:56 ci-kubernetes-integration-master-ppc64le](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-integration-master-ppc64le/1991308809577959424)

/kind failing-test

### PR DESCRIPTION
**Pull request by mortent**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
This fixes the flaky DRA integration test reported in https://github.com/kubernetes/kubernetes/issues/135422. It does this by preventing the Extended Resources test from allocating devices published by other tests.

#### Which issue(s) this PR is related to:
Fixes: #135422

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: test/integration/dra/dra_test.go [hunk 1]
```diff
@@ -783,12 +783,25 @@ func expectedAllocatedClaim(request string, nodeInfo nodeInfo) gtypes.GomegaMatc
...
+	class.Spec.Selectors = []resourceapi.DeviceSelector{{
+		CEL: &resourceapi.CELDeviceSelector{
+			Expression: fmt.Sprintf("device.driver == %q", driverName),
+		},
+	}}
+	c, err := tCtx.Client().ResourceV1().DeviceClasses().Create(tCtx, class, metav1.CreateOptions{FieldValidation: "Strict"})
 	tCtx.ExpectNoError(err, "create class")
+
+	slice := st.MakeResourceSlice("worker-0", driverName).Devices(device1)
+	createSlice(tCtx, slice.Obj())
```
Comment (pohly) [inline test/integration/dra/dra_test.go:799]: So this test really depends on allocating a device, i.e. it failed when ran in isolation because then there were no ResourceSlices from other tests?

Comment (mortent) [reply test/integration/dra/dra_test.go:799]: Yeah, it fails if these lines are removed.

Comment (pohly) [reply test/integration/dra/dra_test.go:799]: Just double-checking.

I wonder whether we can flush out such bugs more systematically: we would need to identify all tests in a unit test, then run `go test -run=<test>` one-by-one. Probably too complicated and expensive. We need to rely on developers doing that themselves as they write a new test.

**Review by pohly — APPROVED** [review]
/approve
