### PR TITLE
kubelet: Mark ready condition as false explicitly for terminal pods

### LINKED ISSUE #108594: Kubelet reports Ready=true for pod and containers conditions during kubelet level evictions
### What happened?

In 1.22+, when kubelet evicts a pod, it updates the pod status to api-server marking the pod phase as failed / succeeded. However, the kubelet continues to report Ready=true pod condition until the all of the containers are fully terminated by the container runtime. 

As a result, since the pod is still considered ready, external controllers (e.g. the endpoint controller), utilize the pod ready condition and will continue to send traffic to these pods marked in terminal phase. These pods are often not ready to serve traffic since they are in progress of being shutdown. 

This is regression from prior to 1.22, since prior to 1.22, kubelet did not send any pod/container conditions to the api-server for evicted pods. 

xref: https://github.com/kubernetes/kubernetes/issues/105358#issuecomment-932470027 for difference between kubelet status for evicted pods before and after 1.22

One of the areas where this issue manifests is with Kubelet graceful shutdown. In 1.22+, if a pod takes a long time to shutdown, during the entire shutdown process the kubelet will report Ready=true condition, and traffic will be sent to the pod. 

Additionally, If the node is shutdown before the pod fully terminates, the pod will be stuck in this state where Phase=Failed, but Ready=true. As a result, the pod will be seen incorrectly as ready by services and will be sent traffic (which the pod will likely be unable to handle due to either the pod being in progress of terminating or the node already being shutdown). 

I suspect this is issue not only for graceful shutdown, but for any type of kubelet initiated eviction. 

### What did you expect to happen?

Kubelet should maintain the same behavior as prior to 1.22. Kubelet should report Ready=false condition at the same time as marking Phase=Failed for evicted pods. Having pods in terminal phases (i.e. Failed / Succeeded), but Ready=true should not be a possible status update from kubelet to api-server. 

### How can we reproduce it (as minimally and precisely as possible)?

Create a 1.22+ cluster with the following kubelet configuration

```
shutdownGracePeriod: 120s
shutdownGracePeriodCriticalPods: 10s
```

Create the following pod (pod blocks SIGTERM and has 60s termination grace period)

```
curl -s https://gist.githubusercontent.com/bobbypage/5ef251d4d2224983472bde01c7620f6f/raw/term_pod.yaml | kubectl apply -f -
```

Trigger a graceful shutdown (either by actually shutting down machine or by sending message to dbus)

```
# on the node where term_pod is scheduled
sudo dbus-send --system /org/freedesktop/login1 org.freedesktop.login1.Manager.PrepareForShutdown boolean:true
```

Observe that the pod reports phase=Failed, but Ready=true for the entire 60s duration of shutdown

```
$ kubectl get pods test-term -o yaml | gh gist create
- Creating gist...
✓ Created gist
https://gist.github.com/3f75d5677e23d5a90cb5bff3bb4e2caa
```

```
# status reports Ready=true, but phase=Failed
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-03-08T19:23:21Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-03-08T19:23:23Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-03-08T19:23:23Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-03-08T19:23:21Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://2ceaa48f684dd1550bf67204a36caa6f5585e996881d5d0e232a1badd23c7cf5
    image: k8s.gcr.io/debian-base:v2.0.0
    imageID: k8s.gcr.io/debian-base@sha256:ebda8587ec0f49eb88ee3a608ef018484908cbc5aa32556a0d78356088c185d4
    lastState: {}
    name: main
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-03-08T19:23:23Z"
...
message: Pod was terminated in response to imminent node shutdown.
  phase: Failed
  reason: Terminated
```

Only after 60s (pod fully terminated), is condition Ready=false reported

```
# pod dump ~60s later
$ kubectl get pods test-term -o yaml | gh gist create
- Creating gist...
✓ Created gist
https://gist.github.com/bb16d400754ce885c263de4b8482f101
```

See the kubelet logs (full logs: https://gist.github.com/728df3b9c53ff3116bb4c2badbc1b34f)

```
# node shutdown kills the pod

Mar 08 19:24:47 kind-worker kubelet[202]: I0308 19:24:47.410550     202 nodeshutdown_manager_linux.go:316] "Shutdown manager killing pod with gracePeriod" pod="default/test-term" gracePeriod=60
Mar 08 19:24:47 kind-worker kubelet[202]: I0308 19:24:47.410710     202 pod_workers.go:638] "Pod is being removed by the kubelet, begin teardown" pod="default/test-term" podUID=94f28df9-3978-4eb8-b88f-7f3b5a0aab56
Mar 08 19:24:47 kind-worker kubelet[202]: I0308 19:24:47.410738     202 pod_workers.go:888] "Processing pod event" pod="default/test-term" podUID=94f28df9-3978-4eb8-b88f-7f3b5a0aab56 updateType=1
Mar 08 19:24:47 kind-worker kubelet[202]: I0308 19:24:47.410919     202 pod_workers.go:996] "Pod worker has observed request to terminate" pod="default/test-term" podUID=94f28df9-3978-4eb8-b88f-7f3b5a0aab56
Mar 08 19:24:47 kind-worker kubelet[202]: I0308 19:24:47.410984     202 kubelet.go:1719] "syncTerminatingPod enter" pod="default/test-term" podUID=94f28df9-3978-4eb8-b88f-7f3b5a0aab56
Mar 08 19:24:47 kind-worker kubelet[202]: I0308 19:24:47.411011     202 kubelet_pods.go:1429] "Generating pod status" pod="default/test-term"
Mar 08 19:24:47 kind-worker kubelet[202]: I0308 19:24:47.411108     202 kubelet_pods.go:1441] "Got phase for pod" pod="default/test-term" oldPhase=Running phase=Running
Mar 08 19:24:47 kind-worker kubelet[202]: I0308 19:24:47.411224     202 kubelet.go:1749] "Pod terminating with grace period" pod="default/test-term" podUID=94f28df9-3978-4eb8-b88f-7f3b5a0aab56 gracePeriod=60
Mar 08 19:24:47 kind-worker kubelet[202]: I0308 19:24:47.411337     202 event.go:294] "Event occurred" object="default/test-term" fieldPath="spec.containers{main}" kind="Pod" apiVersion="v1" type="Normal" reason="Killing" message="Stopping container main"
Mar 08 19:24:47 kind-worker kubelet[202]: I0308 19:24:47.411302     202 kuberuntime_container.go:718] "Killing container with a grace period override" pod="default/test-term" podUID=94f28df9-3978-4eb8-b88f-7f3b5a0aab56 containerName="main" containerID="containerd://2ceaa48f684dd1550bf67204a36caa6f5585e996881d5d0e232a1badd23c7cf5" gracePeriod=60
Mar 08 19:24:47 kind-worker kubelet[202]: I0308 19:24:47.411391     202 kuberuntime_container.go:722] "Killing container with a grace period" pod="default/test-term" podUID=94f28df9-3978-4eb8-b88f-7f3b5a0aab56 containerName="main" containerID="containerd://2ceaa48f684dd1550bf67204a36caa6f5585e996881d5d0e232a1badd23c7cf5" gracePeriod=60

# pod updated with Phase=Failed, Ready=true

Mar 08 19:24:47 kind-worker kubelet[202]: I0308 19:24:47.451647     202 status_manager.go:633] "Status for pod updated successfully" pod="default/test-term" statusVersion=3 status={Phase:Failed Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-03-08 19:23:21 +0000 UTC Reason: Message:} {Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-03-08 19:23:23 +0000 UTC Reason: Message:} {Type:ContainersReady Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-03-08 19:23:23 +0000 UTC Reason: Message:} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-03-08 19:23:21 +0000 UTC Reason: Message:}] Message:Pod was terminated in response to imminent node shutdown. Reason:Terminated NominatedNodeName: HostIP:192.168.10.2 PodIP:10.244.1.2 PodIPs:[{IP:10.244.1.2}] StartTime:2022-03-08 19:23:21 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:main State:{Waiting:nil Running:&ContainerStateRunning{StartedAt:2022-03-08 19:23:23 +0000 UTC,} Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:true RestartCount:0 Image:k8s.gcr.io/debian-base:v2.0.0 ImageID:k8s.gcr.io/debian-base@sha256:ebda8587ec0f49eb88ee3a608ef018484908cbc5aa32556a0d78356088c185d4 ContainerID:containerd://2ceaa48f684dd1550bf67204a36caa6f5585e996881d5d0e232a1badd23c7cf5 Started:0xc0004fe900}] QOSClass:BestEffort EphemeralContainerStatuses:[]}

# 60 seconds later, pod is updated with Phase=Failed, Ready=false

Mar 08 19:25:48 kind-worker kubelet[202]: I0308 19:25:48.274488     202 status_manager.go:633] "Status for pod updated successfully" pod="default/test-term" statusVersion=4 status={Phase:Failed Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-03-08 19:23:21 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-03-08 19:25:48 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [main]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-03-08 19:25:48 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [main]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-03-08 19:23:21 +0000 UTC Reason: Message:}] Message:Pod was terminated in response to imminent node shutdown. Reason:Terminated NominatedNodeName: HostIP:192.168.10.2 PodIP:10.244.1.2 PodIPs:[{IP:10.244.1.2}] StartTime:2022-03-08 19:23:21 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:main State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:137,Signal:0,Reason:Error,Message:,StartedAt:2022-03-08 19:23:23 +0000 UTC,FinishedAt:2022-03-08 19:25:47 +0000 UTC,ContainerID:containerd://2ceaa48f684dd1550bf67204a36caa6f5585e996881d5d0e232a1badd23c7cf5,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:k8s.gcr.io/debian-base:v2.0.0 ImageID:k8s.gcr.io/debian-base@sha256:ebda8587ec0f49eb88ee3a608ef018484908cbc5aa32556a0d78356088c185d4 ContainerID:containerd://2ceaa48f684dd1550bf67204a36caa6f5585e996881d5d0e232a1badd23c7cf5 Started:0xc001820c19}] QOSClass:BestEffort EphemeralContainerStatuses:[]}
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
n/a
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by bobbypage**
Terminal pods may continue to report a ready condition of true because
there is a delay in reconciling the ready condition of the containers
from the runtime with the pod status. It should be invalid for kubelet
to report a terminal phase with a true ready condition. To fix the
issue, explicitly override the ready condition to false for terminal
pods during status updates.

Signed-off-by: David Porter <david@porter.me>

#### Which issue(s) this PR fixes:

Fixes #108594

#### Does this PR introduce a user-facing change?

```release-note
Fixed a 1.22 regression kubelet issue that could result in invalid pod status updates to be sent to the api-server where pods would be reported in a terminal phase but also report a ready condition of true in some cases.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by bobbypage** [comment]
See https://github.com/kubernetes/kubernetes/pull/110257 where after lowering the pollInternval in the existing regression test for https://github.com/kubernetes/kubernetes/issues/108594 we were able to detect the invalid pod status update by kubelet of (phase=Failed, Ready=True).

File: pkg/kubelet/status/status_manager.go [hunk 1]
```diff
@@ -867,6 +867,16 @@ func mergePodStatus(oldPodStatus, newPodStatus v1.PodStatus, couldHaveRunningCon
 		}
 	}
 
+	// If the new phase is terminal, explicitly set the ready condition to false for v1.PodReady and v1.ContainersReady.
+	// It may take some time for kubelet to reconcile the ready condition, so explicitly set ready conditions to false if the phase is terminal.
+	// This is done to ensure kubelet does not report a status update with terminal pod phase and ready=true.
```
Comment (rata) [inline pkg/kubelet/status/status_manager.go:872]: For my future self, can we link to the github issue? What do you think?

**Comment by rphillips** [comment]
Great find!

**Comment by rphillips** [comment]
@bobbypage I'm testing this patch and terminating a pod. I still seeing the pod in ready status during the termination phase.

```
apiVersion: v1
kind: Pod
metadata:
  name: bash
spec:
  containers:
  - name: bash
    image: bash
    command:
    - bash
    - -c
    - "_term() { rm -f /tmp/ready ; sleep 30; exit 0; } ; trap _term SIGTERM; touch /tmp/ready ; while true; do echo \"hello\"; sleep 10; done"
  terminationGracePeriodSeconds: 30
  restartPolicy: Never
```

**Comment by bobbypage** [comment]
> @bobbypage I'm testing this patch and terminating a pod. I still seeing the pod in ready status during the termination phase.
> 
> ```
> apiVersion: v1
> kind: Pod
> metadata:
>   name: bash
> spec:
>   containers:
>   - name: bash
>     image: bash
>     command:
>     - bash
>     - -c
>     - "_term() { rm -f /tmp/ready ; sleep 30; exit 0; } ; trap _term SIGTERM; touch /tmp/ready ; while true; do echo \"hello\"; sleep 10; done"
>   terminationGracePeriodSeconds: 30
>   restartPolicy: Never
> ```

That should be expected. The PR doesn't change the semantics around reporting `ready=false` while a pod is terminating itself. The PR does *not* address https://github.com/kubernetes/kubernetes/issues/102537#issue-909658949 which is a separate issue and as discussed it's unclear if we want to change the behavior for that (xref: https://github.com/kubernetes/kubernetes/pull/110191#issuecomment-1142294392).

 The main change in behavior for the PR is that after this patch, kubelet will never report ready=true and a terminal phase (i.e. phase=Succeeded/Failed) during a status update. For example, the status update caught in the regression test here (https://github.com/kubernetes/kubernetes/pull/110257#issuecomment-1140115944) is something we want to prevent and ensure kubelet never reports such as invalids state to the api server. The general invariant is that ready=true should only be reported for non-terminal phases.

File: pkg/kubelet/status/status_manager.go (hunk 1 above)
Comment (bobbypage) [reply pkg/kubelet/status/status_manager.go:872]: good idea, added!

File: pkg/kubelet/status/generate.go [hunk 2]
```diff
@@ -69,6 +71,15 @@ func GenerateContainersReadyCondition(spec *v1.PodSpec, containerStatuses []v1.C
 		}
 	}
 
+	// If the pod phase is failed, explicitly set the ready condition to false for containers since they may be in progress of terminating.
```
[the remark this answers is not in the document]
Comment (bobbypage) [reply pkg/kubelet/status/generate.go:74]: It does and a previous PR ensured we only report terminal phase after containers are terminated. However, the status of the containers come from the runtime which can be out of date and stale, so kubelet should explicitly set  the readiness to false if the pod will be reported as terminal.

**Comment by 249043822** [comment]
/cc
From my testing, this change look good to me.

**Comment by bobbypage** [comment]
Pushed updated revision that includes update to node e2e test which includes a reproducer for #108594. Same test on master currently fails (see https://github.com/kubernetes/kubernetes/pull/110413) while the serial job is passing with this PR.

**Comment by bobbypage** [comment]
/assign @rphillips 

Ryan, can you PTAL again? Thanks!

**Comment by rphillips** [comment]
@bobbypage release note?

**Comment by bobbypage** [comment]
added release note, thanks!

**Review by mrunalp — APPROVED** [review]

**Comment by thockin** [comment]
xref https://github.com/kubernetes/kubernetes/pull/110255

This feels like a bandaid.  Consumers which do not handle terminal `Phase`s might see these Pods as "alive but not serving at the moment", when in fact they are gone and never coming back.

Consider what might have happened if this was done in the first place - we'd have EndpointSlices with potentially tons of "unready" endpoints (we track both ready and not).  It would not have been the same problem we actually had, but it would have been a slow-burning "leak".

It seems like the REAL fix is to a) document the pod lifecycle contract; and b) fix _all_ consumers.

That said, I guess we've had this problem FOREVER, right?  If you are examining pods and not handling Phase properly, this doesn't make you worse than you were before.

File: pkg/kubelet/status/generate.go [hunk 3]
```diff
@@ -69,6 +71,15 @@ func GenerateContainersReadyCondition(spec *v1.PodSpec, containerStatuses []v1.C
...
+	if podPhase == v1.PodFailed {
```
Comment (thockin) [inline pkg/kubelet/status/generate.go:75]: Why is this not also checking `PodSucceeded` ?  Should we leave a comment?

Comment (thockin) [reply pkg/kubelet/status/generate.go:75]: And why does this not call `generateContainersReadyConditionForTerminalPhase(podPhase)` ?

**Comment by bobbypage** [comment]
Thanks Tim! I agree with you, ideally clients should ignore terminal pods, and if the pod is terminal ignore the ready condition in the first place. We can't guarantee that all clients will do that though.

However, at least pre-1.22 (before this regression was introduced), clients could assume that terminal pods would always report ready=false, which is no longer the case. This PR aims to revert to that behavior and ensure kubelet never reports an "invalid" status update of `Phase=Terminal`, `Ready=True`. 

> That said, I guess we've had this problem FOREVER, right? If you are examining pods and not handling Phase properly, this doesn't make you worse than you were before.

Yup, this doesn't make it any worse for clients ignoring phases but rather brings back the guarantee that terminal pods will always report a ready status of false.

**Review by thockin — COMMENTED** [review]
/approve

I'm a big fan of leaving future-me clues.

We should move directories around so that podutil OWNERs don't need API approvers.

File: pkg/kubelet/status/generate.go (hunk 3 above)
Comment (bobbypage) [reply pkg/kubelet/status/generate.go:75]: > Why is this not also checking PodSucceeded ? Should we leave a comment?

PodSucceded is already handled above on line 66, see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/generate.go#L64-L70)

> And why does this not call generateContainersReadyConditionForTerminalPhase(podPhase) ?

I created that helper function to be used in `status_manager.go` to be able to handle either phase. I returned the condition directly inline here, since it's what done in the succeeded case above, but I agree with you, we can switch it to use the helper function as well.

**Comment by bobbypage** [comment]
/hold

to update based on feedback

File: pkg/kubelet/status/generate.go (hunk 3 above)
Comment (bobbypage) [reply pkg/kubelet/status/generate.go:71]: I updated, based on your feedback and reused `generateContainersReadyConditionForTerminalPhase` for both succeeded and failed cases, so the condition generation logic is in one place.

**Comment by bobbypage** [comment]
/unhold

Pushed an additional revision to fix suggestions [here](https://github.com/kubernetes/kubernetes/pull/110256#discussion_r892941368)

**Comment by thockin** [comment]
Assuming previous LGTM holds after minor changes:

/lgtm

**Comment by bobbypage** [comment]
Cherrypicks:

1.24 - https://github.com/kubernetes/kubernetes/pull/110479
1.23 - https://github.com/kubernetes/kubernetes/pull/110480
1.22 - https://github.com/kubernetes/kubernetes/pull/110481

File: pkg/kubelet/status/generate.go [hunk 4]
```diff
@@ -62,11 +64,12 @@ func GenerateContainersReadyCondition(spec *v1.PodSpec, containerStatuses []v1.C
 
 	// If all containers are known and succeeded, just return PodCompleted.
 	if podPhase == v1.PodSucceeded && len(unknownContainers) == 0 {
-		return v1.PodCondition{
-			Type:   v1.ContainersReady,
-			Status: v1.ConditionFalse,
-			Reason: PodCompleted,
-		}
+		return generateContainersReadyConditionForTerminalPhase(podPhase)
```
Comment (smarterclayton) [inline pkg/kubelet/status/generate.go:67]: Going back and looking through this, the `len(unknownContainers) == 0` above has me worried.

There are two phases in play - the apiserver phase, and the one the Kubelet tracks.  Setting phase to terminal on the apiserver is roughly the same outcome as deleting the pod - the kubelet should inexorably converge the actual pod state to stopped.  Likewise if the Kubelet observes a failure or evicts the pod, the phase should inexorably converge.  However, internal to the Kubelet status loop the phase should *match* the actual observed state of the pod containers, and so we should never be in a terminal state here without these containers being in some state we recognize (I think).

This is something I want to have laid out in the pod lifecycle clarification KEP so we can look at all the factors and eliminate my "shoulds" from above - it might be that the correct status when succeeded + > 1 unknown container = pod ready = false here, always.  But it's super subtle, and we need this sort of stuff in a clear top level doc, not in comment threads in a PR.   I'll add it to the list.
