### PR TITLE
BoundServiceAccountTokenVolume: fix InClusterConfig

### LINKED ISSUE #77651: BoundServiceAccountTokenVolume: kube-proxy doesn't reload ServiceAccount tokens
**What happened**:

This all happened in a `GKE 1.13.5-gke.10` alpha cluster.

1. `kube-proxy` stopped working and inspecting the logs showed messages like:
```
E0509 02:05:11.750695       6 reflector.go:125] k8s.io/client-go/informers/factory.go:132: Failed to list *v1.Service: Unauthorized
E0509 02:05:11.755213       6 reflector.go:125] k8s.io/client-go/informers/factory.go:132: Failed to list *v1.Endpoints: Unauthorized
```
2. Upon inspection of the kube-proxy Pod, I saw it was using the `BoundServiceAccountTokenVolume` feature. Notice that the expirationSeconds is 1 hour. This is exactly how much time kube-proxy was working correctly before it started throwing errors, which I confirmed from the logs.
```yaml
volumeMounts:                                                                                                                                                                                                                                                                                                                                                                                         
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount                                                                                                                                                     
      name: kube-api-access-7mbbq                                                                                                                                                                                  
      readOnly: true

volumes:
- name: kube-api-access-7mbbq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3600
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

3. Recreating the Pod (deleting and letting DaemonSet create it again) fixed the problem, which indicated that `kube-proxy` is not reloading the ServiceAccount token.

There could also be problems with other controllers.
I just didn't happen to stumble upon them.

**What you expected to happen**:

I would expect `kube-proxy` to work.
The observed behaviour is possibly due to `kube-proxy` not reloading the ServiceAccount token.

**How to reproduce it (as minimally and precisely as possible)**:

Generally, you need a K8s 1.13 Cluster with the BoundServiceAccountTokenVolume Feature Gate enabled. I will use GKE as this is the environment I was using when stumbling upon this.

1. Create a `GKE 1.13.5-gke.10` alpha cluster (public preview) (any 1.13 cluster should work).
2. Wait for 1 hour (confirm that kube-proxy's SA token expires in 3600 seconds).
3. SSH into the node and view kube-proxy logs: `cat /var/log/kube-proxy.log`

**Anything else we need to know?**:

This was reported in the Kubernetes Slack, in the #gke channel.
@mikedanese was very helpful, managed to reproduce the issue and has filed #77613 which could be a fix.

**Environment**:
- Kubernetes version (use `kubectl version`): 
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.5-gke.10", GitCommit:"f5949b3427099d4e410ef96d6e0fea3cd4794e10", GitTreeState:"clean", BuildDate:"2019-04-10T19:05:37Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: GKE 1.13.5-gke.10
- OS (e.g: `cat /etc/os-release`): 18.04.2 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`): 4.15.0-1029-gcp
- Install tools: GKE
- Network plugin and version (if this is a network-related bug): 
- Others:

### PR DESCRIPTION
**Pull request by mikedanese**
Missed this in https://github.com/kubernetes/kubernetes/commit/dba85e58deba and rest.Config is dropping BearerTokenFile path before the token source is created. This is causing InClusterConfig to not refresh tokens from disk.

:cry: :sob:

I'm thinking about how to get some test coverage here.

/kind bug
/sig auth

```release-note
NONE
```

Fixes https://github.com/kubernetes/kubernetes/issues/77651

### CODE REVIEW

**Comment by liggitt** [comment]
/lgtm
/approve

/hold
this desperately needs a test

**Comment by liggitt** [comment]
```
I0508 20:16:54.000] should handle in-cluster config [It]
I0508 20:16:54.000] test/e2e/kubectl/kubectl.go:616
I0508 20:16:54.000]
I0508 20:16:54.000] Expected an error to have occurred. Got:
I0508 20:16:54.000] <nil>: nil
```

I think we also need this to ensure the overridden command line `--token` trumps:
```diff
diff --git a/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go b/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
index 878e0df79f..eca82c2549 100644
--- a/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
+++ b/staging/src/k8s.io/client-go/tools/clientcmd/client_config.go
@@ -228,6 +228,7 @@ func (config *DirectClientConfig) getUserIdentificationPartialConfig(configAuthI
        // blindly overwrite existing values based on precedence
        if len(configAuthInfo.Token) > 0 {
                mergedConfig.BearerToken = configAuthInfo.Token
+               mergedConfig.BearerTokenFile = configAuthInfo.TokenFile
        } else if len(configAuthInfo.TokenFile) > 0 {
```

**Comment by mikedanese** [comment]
I'm headed down the path of creating a new test image and e2e for in cluster config. Feel free to stop me if you have any bright ideas.

File: test/e2e/auth/service_accounts.go [hunk 1]
```diff
@@ -410,4 +415,143 @@ var _ = SIGDescribe("ServiceAccounts", func() {
 			}
 		}
 	})
+
+	//It("should support InClusterConfig with token rotation [Slow]", func() {
+	It("should support InClusterConfig with token rotation", func() {
```
Comment (mikedanese) [inline test/e2e/auth/service_accounts.go]: This test works now but its slow (~10 minutes). It's pretty gross because I want it to run on non-alpha clusters. I could drop a bunch of stuff if we are ok with this only running in the alpha test suite.

Comment (mikedanese) [reply test/e2e/auth/service_accounts.go]: Also it will still be slow even if we only run it in the alpha suite, just way smaller.

Comment (liggitt) [reply test/e2e/auth/service_accounts.go]: I don't think we check feature gates in the e2e process (it's not even the same process as the apiserver)... typically we indicate non-default features with feature tags in the test description

**Comment by liggitt** [comment]
would it make sense to split the e2e test into its own commit? were you planning to pick the test back to 1.12/1.13/1.14 as well?

File: test/e2e/auth/service_accounts.go (hunk 1 above)
Comment (mikedanese) [reply test/e2e/auth/service_accounts.go]: Ya, fixed.

**Comment by liggitt** [comment]
the test is ugly, but I want coverage more than beauty at the moment. with the [Slow] and [Feature] tags, do we know what suite this will run in?

/lgtm
/approve
