### PR TITLE
Fix memory leak from not closing hcs containers

### LINKED ISSUE #78555: memory leak in Windows kubelet
**What happened**:
kubelet.exe's memory usage is increasing over time. When more pods are run, it increases even more.

**What you expected to happen**:
it should not keep increasing

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.0
- Cloud provider or hardware configuration: AKS
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
image009

### PR DESCRIPTION
**Pull request by benmoss**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Windows containers opened through `hcsshim.OpenContainer` need to be freed through `container.Close()` or they leak memory. This is a memory dump from a Windows kubelet I took with Go's pprof:
profile001

**Which issue(s) this PR fixes**:
Fixes #78555 

**Does this PR introduce a user-facing change?**:
```release-note
Fixes a memory leak in Kubelet on Windows caused by not not closing containers when fetching container metrics
```

/assign @feiskyer @PatrickLang 
/sig windows

Only thing worth noting is that I decided if for some reason `container.Close()` does error, to return the error rather than logging it and proceeding. Seems like something is substantially wrong if this happens.

### CODE REVIEW

**Comment by PatrickLang** [comment]
/milestone 1.15
This can be a big memory leak - reports of 4GB with a lot of stats requests with many containers running

**Comment by yujuhong** [comment]
/lgtm
/approve

We should cherry-pick this to 1.14. Can you add a release note? @benmoss thanks!

**Comment by benmoss** [comment]
Added a release note, was kinda unclear if it warranted one but yeah definitely people want to know if a release fixes a known issue :)

**Comment by yujuhong** [comment]
> Added a release note, was kinda unclear if it warranted one but yeah definitely people want to know if a release fixes a known issue :)

It's required if we want to patch 1.14, and I think we should :-)

File: pkg/kubelet/stats/cri_stats_provider_windows.go [hunk 1]
```diff
@@ -51,7 +51,9 @@ func (p *criStatsProvider) listContainerNetworkStats() (map[string]*statsapi.Net
 			klog.V(4).Infof("Failed to get statistics for container %q with error '%v', continue to get stats for other containers", c.ID, err)
 			continue
 		}
-
+		if err := container.Close(); err != nil {
```
Comment (mtaufen) [inline pkg/kubelet/stats/cri_stats_provider_windows.go]: Does this need to be part of the error handling path? E.g. if `container.Statistics()` gets an error, it looks like we'll skip closing the handle. 

Might better to use a defer (but if you do please test it to ensure `container` is tracked properly across loop iterations, I always have trouble remembering whether receivers are evaluated at defer time or return time).

Comment (yujuhong) [reply pkg/kubelet/stats/cri_stats_provider_windows.go]: Agree. We should probably defer after handling the error of OpenContainer (~ line 48).

Comment (benmoss) [reply pkg/kubelet/stats/cri_stats_provider_windows.go]: Ahh, quite true.

Comment (benmoss) [reply pkg/kubelet/stats/cri_stats_provider_windows.go]: @mtaufen @yujuhong I moved it to a private method so I could use `defer`, the only trouble is catching the `Close()` error in a defer is now sorta tricky. I used the `go.uber.org/multierr` package since it helps solve this problem nicely, and was already vendored but it's right now a transitive dependency for the project. I don't know if promoting it to a direct dependency is something people worry about. It looks like k8s largely follows the "ignore deferred errors" pattern today 😄.

Comment (benmoss) [reply pkg/kubelet/stats/cri_stats_provider_windows.go]: On second thought, and after seeing it triggers a new level of PR review to add that dep, I decided to go with a simpler approach that avoids the new dep :)

**Review by feiskyer — COMMENTED** [review]
/lgtm

thanks for the fix.

**Comment by PatrickLang** [comment]
leaving a breadcrumb - you can get pprof heap info proxied through apiserver

```
kubectl proxy &
http://localhost:8001/api/v1/nodes/$nodename/proxy/debug/pprof/heap
```
