### PR TITLE
[hack/verify-file-sizes.sh] Support Mac OS X

### LINKED ISSUE #124155: `hack/verify-file-sizes.sh` does not support Mac OS X
### What happened?

The `hack/verify-file-sizes.sh` script encounters an error when executed on Mac OS X because the `stat --printf=%s` option is not supported. The error message appears as follows:

```
ERROR: usage: stat [-FLnq] [-f format | -l | -r | -s | -x] [-t timefmt] [file ...]
```

### What did you expect to happen?

I expected the `hack/verify-file-sizes.sh` script to execute successfully.

### How can we reproduce it (as minimally and precisely as possible)?

Execute the `hack/verify-file-sizes.sh` command on macOS.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
$ uname -a
Darwin <name> 22.6.0 Darwin Kernel Version 22.6.0: Mon Feb 19 19:43:41 PST 2024; root:xnu-8796.141.3.704.6~1/RELEASE_ARM64_T8103 arm64
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by bells17**
#### What type of PR is this?

/kind bug
/sig testing

#### What this PR does / why we need it:

Enable the `hack/verify-file-sizes.sh` script to run successfully on Mac OS X.

#### Which issue(s) this PR fixes:

Fixes #124155

Ref: #121549

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: hack/verify-file-sizes.sh [hunk 1]
```diff
@@ -24,6 +24,22 @@ cd "${KUBE_ROOT}"
 # Files larger than 1MB need to be allowed explicitly.
 maxsize=$((1 * 1024 * 1024))
 
+run_stat() {
+    local file="$1"
+    case "$(uname -s)" in
+        Darwin)
+            stat -f %z "$file" | tr -d '\n'
```
Comment (carlory) [inline hack/verify-file-sizes.sh:31]: If this line works well on Linux, why not use it directly in Line 61?

Comment (bells17) [reply hack/verify-file-sizes.sh:31]: @carlory Thank you for your review.
Regarding the options for the stat command, I tried it on Linux, and here's what I found:

```
$ touch samplefile

$ stat -f %z samplefile | tr -d '\n'
stat: cannot read file system information for '%z': No such file or directory
  File: "samplefile"    ID: 0        Namelen: 255     Type: fuseblkBlock size: 1048576    Fundamental block size: 4096Blocks: Total: 59840624   Free: 18538697   Available: 18538697Inodes: Total: 744080125  Free: 741547880

$ stat --printf %z ./samplefile | tr -d '\n'
2024-04-03 03:25:17.374582976 +0000

$ stat --printf %s ./samplefile
0
```

As shown above, an error occurred with `stat -f %z`, so I am switching options and such depending on whether the environment is Linux or Mac OS X.

Comment (BenTheElder) [reply hack/verify-file-sizes.sh:31]: this sort of thing tends to cause problems because even on darwin you may have gnu coreutils installed, check e.g. when we require gnu-sed.

`wc -c < "$file"` would work portably

Comment (bells17) [reply hack/verify-file-sizes.sh]: @BenTheElder Thank you for your comment.
I have changed the implementation to use `wc -c < "$file"`. Please review it when you have time.

Just to be safe, I've attached the test results below after verifying the operation on both Mac OS X and Linux:

**Mac OS X**

```
echo "abc" > samplefile
size=$(wc -c < samplefile)
echo "size: $size"
for i in 3 4
do
  maxsize=$i
  if [ "${size}" -gt "$maxsize" ]; then
    echo "size is greater than maxsize"
  else
    echo "size is less than or equal to maxsize"
  fi
done
size:        4
size is greater than maxsize
size is less than or equal to maxsize
```

**Linux**

```
echo "abc" > samplefile
size=$(wc -c < samplefile)
echo "size: $size"
for i in 3 4
do
  maxsize=$i
  if [ "${size}" -gt "$maxsize" ]; then
    echo "size is greater than maxsize"
  else
    echo "size is less than or equal to maxsize"
  fi
done
size: 4
size is greater than maxsize
size is less than or equal to maxsize
```

Comment (BenTheElder) [reply hack/verify-file-sizes.sh]: also confirming:

this test took
this pr: 3s: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/124156/pull-kubernetes-verify/1781407536046411776
random PR without this change: 6s: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119589/pull-kubernetes-verify/1781378276028059648

so no performance issues

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

thanks!
