### PR TITLE
Fixed flaky test by changing get_object_assert -> wait_object_assert.

### LINKED ISSUE #89719: [Flaky Test] pull-kubernetes-integration / run_kubectl_apply_tests
**Which jobs are flaking**:
pull-kubernetes-integration
**Which test(s) are flaking**:
run_kubectl_apply_tests 
**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&include-filter-by-regex=run_kubectl_apply_tests&width=5

**Reason for failure**:
A test has a precondition that no pods should be up, but, previous test's deployment did not fully delete. As a result precondition check fails.

**Anything else we need to know**:
- links to go.k8s.io/triage appreciated
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=run_kubectl_apply_tests
- links to specific failures in spyglass appreciated

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88364/pull-kubernetes-integration/1245223371679993859
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/89760/pull-kubernetes-integration/1245616723650940928

### PR DESCRIPTION
**Pull request by ScrapCodes**
**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:
Fixes a flaky test by, changing a get_object_assert to wait_object_assert.
After a deployment is deleted, its' pods stick around for a while, as the cleanup is still in progress. When such a delete is followed by a get pod status, then it results in flaky behavior.

**Which issue(s) this PR fixes**:

Fixes #89719

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1249562981344219136

### CODE REVIEW

File: test/cmd/apply.sh [hunk 1]
```diff
@@ -165,7 +165,7 @@ __EOF__
 
   # same thing without prune for a sanity check
   # Pre-Condition: no POD exists
-  kube::test::get_object_assert pods "{{range.items}}{{${id_field:?}}}:{{end}}" ''
+  kube::test::wait_object_assert pods "{{range.items}}{{${id_field:?}}}:{{end}}" ''
```
Comment (liggitt) [inline test/cmd/apply.sh:168]: `kubectl delete pods` waits for pods to actually be deleted by default before returning... did you actually see flakes here?

File: test/cmd/apply.sh [hunk 2]
```diff
@@ -295,7 +295,7 @@ __EOF__
   kube::test::get_object_assert 'pods pod-c' "{{${id_field}}}" 'pod-c'
   # cleanup
   kubectl delete pod pod-a pod-c "${kube_flags[@]:?}"
-  kube::test::get_object_assert pods "{{range.items}}{{${id_field:?}}}:{{end}}" ''
+  kube::test::wait_object_assert pods "{{range.items}}{{${id_field:?}}}:{{end}}" ''
```
Comment (liggitt) [inline test/cmd/apply.sh:298]: `kubectl delete pods` waits for pods to actually be deleted by default before returning... did you actually see flakes here?

Comment (ScrapCodes) [reply test/cmd/apply.sh:298]: No, I was overzealous. So, I can get rid of these. The one above is a real flake.

File: test/cmd/apply.sh (hunk 1 above)
Comment (ScrapCodes) [reply test/cmd/apply.sh:168]: I was overzealous here too.

File: test/cmd/apply.sh (hunk 2 above)
Comment (ScrapCodes) [reply test/cmd/apply.sh]: I have updated the PR, to just fix this flaky test.
