### PR TITLE
Reintroduce CSI 0.3.x support in CSI Volume Plugin

### LINKED ISSUE #71228: CSI Upgrade Tests Failing for hostPath and gcePD
Quoted from: https://github.com/kubernetes/kubernetes/issues/65246#issuecomment-439708121

> Failing job
> https://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-new-master-upgrade-cluster
> 
> Failing Tests
> 
> [sig-storage] [Serial] CSI Volumes CSI plugin test using CSI driver: gcePD [Serial] should provision storage
> [sig-storage] [Serial] CSI Volumes CSI plugin test using CSI driver: hostPath [Serial] should provision storage
> Error
> https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-new-master-upgrade-cluster/2629
> 
> This is now 1.13 release blocking.

CSI v1.0.0 is only compatible with k8s >1.13
CSI v0.x is only compatible with k8s <1.12

Its probable that we will need to detect what version the k8s cluster is on in the test and deploy the "correct" version of the CSI Drivers for each version

/kind failing-test
/assign
/cc @AishSundar @jberkus @saad-ali @msau42 
/sig storage

### PR DESCRIPTION
**Pull request by saad-ali**
**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
PR https://github.com/kubernetes/kubernetes/pull/71020 removed support for CSI 0.x while adding support for CSI 1.x. This PR reintroduces support for CSI 0.x, so that Kubernetes can continue to support older CSI drivers.

/sig storage

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #71228

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
I suggest also adding e2e tests using the old drivers in 1.13

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 1]
```diff
@@ -246,9 +246,13 @@ func (m *ManagerImpl) GetWatcherHandler() watcher.PluginHandler {
 }
 
 // ValidatePlugin validates a plugin if the version is correct and the name has the format of an extended resource
-func (m *ManagerImpl) ValidatePlugin(pluginName string, endpoint string, versions []string) error {
+func (m *ManagerImpl) ValidatePlugin(pluginName string, endpoint string, versions []string, foundInDeprecatedDir bool) error {
 	klog.V(2).Infof("Got Plugin %s at endpoint %s with versions %v", pluginName, endpoint, versions)
 
+	if foundInDeprecatedDir {
+		return fmt.Errorf("device plugin socket was found in a directory that is no longer supported")
```
Comment (vishh) [inline pkg/kubelet/cm/devicemanager/manager.go]: Why fail with device plugins?

Comment (saad-ali) [reply pkg/kubelet/cm/devicemanager/manager.go]: Per https://github.com/kubernetes/kubernetes/pull/70494#issuecomment-439509841 the plugin directory is changing, and the old one will be deprecated. That PR moved all consumers (CSI and device plugin to the new dir). This PR makes an exception for CSI 0.x but does not change anything else (meaning device plugin and CSI 1.x drivers are still not permitted to use the old dir).

File: pkg/volume/csi/csi_client.go [hunk 2]
```diff
@@ -66,66 +68,172 @@ type csiClient interface {
...
+}
+
+func newCsiDriverClient(driverName csiDriverName) (*csiDriverClient, error) {
+	if driverName == "" {
+		return nil, fmt.Errorf("driver name is empty")
+	}
+
+	addr := fmt.Sprintf(csiAddrTemplate, driverName)
+	requiresV0Client := true
+	if utilfeature.DefaultFeatureGate.Enabled(features.KubeletPluginsWatcher) {
```
Comment (liggitt) [inline pkg/volume/csi/csi_client.go]: it's not obvious to me why client construction would care about how a driver was discovered... is this coupling incidental or inherent?

**Comment by saad-ali** [comment]
Hostpath CSI tests run as part of pull CI and are green.

I manually ran GCE PD CSI tests, and they are all green:

```
Ran 24 of 1919 Specs in 4412.483 seconds
SUCCESS! -- 24 Passed | 0 Failed | 0 Pending | 1895 Skipped PASS
```

Next I'm adding e2e tests using the old drivers in 1.13.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 3]
```diff
@@ -434,3 +442,20 @@ func dial(unixSocketPath string, timeout time.Duration) (registerapi.Registratio
 
 	return registerapi.NewRegistrationClient(c), c, nil
 }
+
+func (w *Watcher) foundInDeprecatedDir(socketPath string) bool {
+	if len(w.deprecatedPath) != 0 {
+		socketPath = strings.TrimSpace(socketPath)
+		deprecatedPath := strings.TrimSpace(w.deprecatedPath)
```
[the remark this answers is not in the document]
Comment (saad-ali) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: The existing code works fine. All the paths are generated programmaticlly not from end user, and should not contain any leading/trailing spaces. In this case, with the new code I added, I wanted to be extra defensive. The rest of the code should probably be more defensive too (but I want to minimize the scope of this PR).

[the remark this answers is not in the document]
Comment (liggitt) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: let's drop the space trimming here... transforming a path locally in a way inconsistent with how it is used elsewhere doesn't seem useful

[the remark this answers is not in the document]
Comment (saad-ali) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Will do.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 4]
```diff
@@ -235,6 +251,13 @@ func (w *Watcher) handleCreateEvent(event fsnotify.Event) error {
 		return w.handlePluginRegistration(event.Name)
 	}
 
+	if w.foundInDeprecatedDir(event.Name) {
```
[the remark this answers is not in the document]
Comment (saad-ali) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Good point, adding the check to `traversePluginDir(...)` as well.

File: pkg/kubelet/cm/devicemanager/manager.go [hunk 5]
```diff
@@ -246,9 +246,13 @@ func (m *ManagerImpl) GetWatcherHandler() watcher.PluginHandler {
 }
 
 // ValidatePlugin validates a plugin if the version is correct and the name has the format of an extended resource
-func (m *ManagerImpl) ValidatePlugin(pluginName string, endpoint string, versions []string) error {
+func (m *ManagerImpl) ValidatePlugin(pluginName string, endpoint string, versions []string, foundInDeprecatedDir bool) error {
 	klog.V(2).Infof("Got Plugin %s at endpoint %s with versions %v", pluginName, endpoint, versions)
 
+	if foundInDeprecatedDir {
```
[the remark this answers is not in the document]
Comment (saad-ali) [reply pkg/kubelet/cm/devicemanager/manager.go]: > this completely separate from the storage driver code, and just implements the same PluginHandler interface?

Correct.

> is the same plugin watcher used to feed events to both CSI and device manager PluginHandler impls? 

Yes.

> if so, doesn't the plugin dir change in 1.13 affect device plugins as well?

Yes, it does. Per the discussions https://github.com/kubernetes/kubernetes/pull/70494#issuecomment-439509841 the owners of device plugin code @vishh @jiayingz are ok with the change.

> what stage are device plugins at, and how many releases do we need to honor them in the v1.12 location?

 @vishh @jiayingz can probably answer this better then I can.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 6]
```diff
@@ -235,6 +251,13 @@ func (w *Watcher) handleCreateEvent(event fsnotify.Event) error {
...
+		for _, blacklistSubdir := range deprecatedDirSubpathBlacklist {
+			if strings.Contains(event.Name, blacklistSubdir) {
```
[the remark this answers is not in the document]
Comment (saad-ali) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: > do we have a more crisp definition of what we were protecting against

Specifically that the deprecated dir `{kubeletRootDir}/plugins/` was known to have multiple uses: for example, `{kubeletRootDir}/plugins/kubernetes.io/...` is known to be used to stage volume plugin mounts, which means that the plugin watcher was inadvertently scanning mounted volumes for sockets.  #69015 was ultimately closed by moving the socket plugin dir to it's own path `{kubeletRootDir}/plugins_registry/...`. But now that we are reintroducing the ability for the the deprecated dir to be used (albeit for only for CSI 0.x drivers) the issue comes up again. So the workaround is to black list the subdirs we know should not be scanned. And force new drivers to use the new dir.

I'll make the blacklisting more strict to handle this case.

File: pkg/volume/csi/csi_client.go (hunk 2 above)
Comment (saad-ali) [reply pkg/volume/csi/csi_client.go]: Before the kubelet device plugin registration mechanism existed (when CSI was alpha), the paths to sockets were deterministicly  generated based on driver name instead of discovered. If someone runs with kubelet plugin registration disabled, we fall back that that ancient mechanism way of finding the plugin.

File: pkg/volume/csi/csi_client.go [hunk 7]
```diff
@@ -113,14 +177,54 @@ func (c *csiDriverClient) NodeGetInfo(ctx context.Context) (
 	accessibleTopology map[string]string,
 	err error) {
 	klog.V(4).Info(log("calling NodeGetInfo rpc"))
+	if c.nodeV1ClientCreator != nil {
+		return c.nodeGetInfoV1(ctx, c.nodeV1ClientCreator)
```
Comment (msau42) [inline pkg/volume/csi/csi_client.go]: does the creator have to be an argument? it's already a field in the csiDriverClient struct

**Comment by msau42** [comment]
I've finished reviewing the csi volume plugin

File: pkg/volume/csi/csi_client.go (hunk 7 above)
Comment (saad-ali) [reply pkg/volume/csi/csi_client.go]: Good catch. Cleaning up.

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (vishh) [reply pkg/kubelet/cm/devicemanager/manager.go]: Device plugins haven't yet adopted the switch to using plugin watcher yet and we believe the risk very *very low* to make the switch to the new directory format.
However, given that this PR is supporting old plugin watcher implementation anyways for CSI, it might make sense to support for device plugins too just for the sake of consistency.

[the remark this answers is not in the document]
Comment (saad-ali) [reply pkg/kubelet/cm/devicemanager/manager.go]: Ok cool. I'll go ahead and remove the failure in this case then.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 8]
```diff
@@ -235,6 +253,9 @@ func (w *Watcher) handleCreateEvent(event fsnotify.Event) error {
 		return w.handlePluginRegistration(event.Name)
 	}
 
+	if w.containsBlacklistedDir(event.Name) {
```
Comment (liggitt) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: is there a reason we don't do this check at the top of the function? Are there types of updates that would exercise some of the code paths above and give spurious errors/warnings (stat errors, non-dir socket files that would trigger calls to handlePluginRegistration incorrectly, etc)?

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 9]
```diff
@@ -417,3 +440,37 @@ func dial(unixSocketPath string, timeout time.Duration) (registerapi.Registratio
 
 	return registerapi.NewRegistrationClient(c), c, nil
 }
+
+func (w *Watcher) containsBlacklistedDir(path string) bool {
+	if w.foundInDeprecatedDir(path) {
+		for _, blacklistSubdir := range deprecatedDirSubpathBlacklist {
+			if i := strings.Index(path, blacklistSubdir); i > -1 {
```
Comment (liggitt) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: was the `kubernetes.io` directory we wanted to avoid because of https://github.com/kubernetes/kubernetes/issues/69015 a direct child of the old plugins dir path? from what I could see in the issue description, it seemed to be. Is it possible to simplify this to something resembling `strings.HasPrefix(path, w.deprecatedPath+"/kubernetes.io/")`? It currently is looking for the blacklisted segment at any point in the directory tree, which is a bit unexpected.

**Comment by saad-ali** [comment]
Add E2E test to verify CSI 0.x. The tests are passing.

Unless there is any other feedback. This PR is ready to go.

File: test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpathplugin.yaml [hunk 10]
```diff
@@ -15,7 +15,7 @@ spec:
       hostNetwork: true
       containers:
         - name: driver-registrar
-          image: gcr.io/gke-release/csi-driver-registrar:v1.0.0-gke.0
+          image: gcr.io/gke-release/csi-driver-registrar:v1.0.1-gke.0
```
Comment (liggitt) [inline test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpathplugin.yaml]: what changed in this image?

File: test/e2e/testing-manifests/storage-csi/gce-pd/node_ds.yaml [hunk 11]
```diff
@@ -14,7 +14,7 @@ spec:
       serviceAccountName: csi-node-sa
       containers:
         - name: csi-driver-registrar
-          image: gcr.io/gke-release/csi-driver-registrar:v1.0.0-gke.0
+          image: gcr.io/gke-release/csi-driver-registrar:v1.0.1-gke.0
```
Comment (liggitt) [inline test/e2e/testing-manifests/storage-csi/gce-pd/node_ds.yaml]: what changed in this image?

**Comment by msau42** [comment]
csi volume plugin and e2es LGTM

File: pkg/volume/csi/csi_client.go (hunk 2 above)
Comment (liggitt) [reply pkg/volume/csi/csi_client.go]: ok

File: test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpathplugin.yaml (hunk 10 above)
Comment (msau42) [reply test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpathplugin.yaml]: Driver-registrar was erroneously still registering supporting "0.2" and "0.3" csi spec versions.
https://github.com/kubernetes-csi/driver-registrar/pull/74

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go (hunk 8 above)
Comment (saad-ali) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Good point moved.

File: pkg/kubelet/cm/devicemanager/manager.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (liggitt) [reply pkg/kubelet/cm/devicemanager/manager.go]: > However, given that this PR is supporting old plugin watcher implementation anyways for CSI, it might make sense to support for device plugins too just for the sake of consistency.

I agree with that, thanks. Make sure the deprecation of the old dir is prominently announced for both device plugins and csi plugins in 1.13 release notes.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go (hunk 9 above)
Comment (saad-ali) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: It is a direct child of `plugins/` will simplify.

File: pkg/kubelet/util/pluginwatcher/plugin_watcher.go [hunk 12]
```diff
@@ -190,8 +202,10 @@ func (w *Watcher) traversePluginDir(dir string) error {
 
 		switch mode := info.Mode(); {
 		case mode.IsDir():
-			if err := w.fsWatcher.Add(path); err != nil {
-				return fmt.Errorf("failed to watch %s, err: %v", path, err)
+			if !w.containsBlacklistedDir(path) {
```
Comment (liggitt) [inline pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: if this is using fileutil.Walk, should we do this to avoid recursing into the ignored dir and registering watchers on paths we're just going to ignore?

```
case mode.IsDir():
  if w.containsBlacklistedDir(path) {
    return fileutil.SkipDir
  }
  ...
```

Comment (saad-ali) [reply pkg/kubelet/util/pluginwatcher/plugin_watcher.go]: Done

**Comment by liggitt** [comment]
set release note to NONE, will need to fold in updates in the 1.13 release notes manually, along with a revision of the release note in https://github.com/kubernetes/kubernetes/pull/71020
