### PR TITLE
Detach the PD disk from the VM in some failure cases.

### LINKED ISSUE #2578: GCE PD is not detached after a failed mount
Repro:
  * Create a pod that attempts to mount a GCE PD that is mis-formatted
  * Delete the pod

Expected:
  * GCE PD should be detached

Observed:
  * GCE PD is not detached.

### PR DESCRIPTION
**Pull request by brendandburns**
Closes #2578

### CODE REVIEW

File: pkg/kubelet/volume/gce_pd/gce_pd.go [hunk 1]
```diff
@@ -151,6 +151,13 @@ type gcePersistentDisk struct {
 	legacyMode bool
 }
 
+func detachDisk(pd *gcePersistentDisk) {
```
Comment (thockin) [inline pkg/kubelet/volume/gce_pd/gce_pd.go]: Is it worth naming this something like detachDiskLogError() to differentiate it from the path in TearDown() which does not log the error but returns it.

**Comment by thockin** [comment]
LGTM, nit is optional

**Comment by brendandburns** [comment]
nit addressed.  ptal.
