### PR TITLE
e2e daemon set: better polling in CheckDaemonStatus

### LINKED ISSUE #128049: [Failing Test][sig-apps] Daemon set [Serial] should run and stop complex daemon [Conformance]
### Which jobs are failing?

- master-blocking:
Conformance-GCE-master-kubetest2

### Which tests are failing?

Kubernetes e2e suite.[It] [sig-apps] Daemon set [Serial] should run and stop complex daemon [Conformance]

### Since when has it been failing?

[Triage](https://storage.googleapis.com/k8s-triage/index.html?test=should%20run%20and%20stop%20complex%20daemon)
[12/10/2024, 09:31:42](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/e2e-ci-kubernetes-e2e-cos-gce-serial-canary/1844868409829888000)
[13/10/2024, 06:35:07](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-audit-kind-conformance/1845186257005580288)

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master%20-%20kubetest2

### Reason for failure (if possible)

```
{ failed [FAILED] error in daemon status. DesiredScheduled: 1, CurrentScheduled: 1, Ready: 0
In [It] at: k8s.io/kubernetes/test/e2e/apps/daemon_set.go:228 @ 10/14/24 04:45:13.179
}
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig app
@kubernetes/release-team-release-signal

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

As a quick fix for a flake, bceec5a3ffd6975105f95b08641e45644c0a6753 introduced polling with wait.Poll in all callers of CheckDaemonStatus.

This commit reverts all callers to what they were before (CheckDaemonStatus + ExpectNoError) and implements polling according to E2E best practices (https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/writing-good-e2e-tests.md#polling-and-timeouts):

- no logging while polling
- support for progress reporting while polling
- last but not least, produce an informative failure message in case of a timeout, including a dump of the daemon set as YAML

#### Which issue(s) this PR fixes:

Related-to: https://github.com/kubernetes/kubernetes/pull/128054/commits/bceec5a3ffd6975105f95b08641e45644c0a6753#r1799565485
Fixes: https://github.com/kubernetes/kubernetes/issues/128049

#### Special notes for your reviewer:

Here's what the failure message looks like after intentionally breaking the `desired == scheduled && scheduled == ready` check so that it never succeeds:
```
  [FAILED] Timed out after 300.001s.
  Expected daemon set to reach state where all desired pods are scheduled and ready. Got instead DesiredScheduled: 1, CurrentScheduled: 1, Ready: 1
      <*v1.DaemonSet | 0xc000e04008>: 
          metadata:
            annotations:
              deprecated.daemonset.template.generation: "1"
            creationTimestamp: "2024-10-15T08:17:36Z"
            generation: 1
            labels:
              daemonset-name: e2e-mpzll-daemon-set
            managedFields:
            - apiVersion: apps/v1
              fieldsType: FieldsV1
              fieldsV1:
                f:metadata:
                  f:annotations:
                    .: {}
                    f:deprecated.daemonset.template.generation: {}
                  f:labels:
                    .: {}
                    f:daemonset-name: {}
                f:spec:
                  f:revisionHistoryLimit: {}
                  f:selector: {}
                  f:template:
                    f:metadata:
                      f:labels:
                        .: {}
                        f:daemonset-name: {}
                    f:spec:
                      f:containers:
                        k:{"name":"app"}:
                          .: {}
                          f:image: {}
                          f:imagePullPolicy: {}
                          f:name: {}
                          f:ports:
                            .: {}
                            k:{"containerPort":9376,"protocol":"TCP"}:
                              .: {}
                              f:containerPort: {}
                              f:protocol: {}
                          f:resources: {}
                          f:securityContext: {}
                          f:terminationMessagePath: {}
                          f:terminationMessagePolicy: {}
                      f:dnsPolicy: {}
                      f:restartPolicy: {}
                      f:schedulerName: {}
                      f:securityContext: {}
                      f:terminationGracePeriodSeconds: {}
                  f:updateStrategy:
                    f:rollingUpdate:
                      .: {}
                      f:maxSurge: {}
                      f:maxUnavailable: {}
                    f:type: {}
              manager: e2e.test
              operation: Update
              time: "2024-10-15T08:17:36Z"
            - apiVersion: apps/v1
              fieldsType: FieldsV1
              fieldsV1:
                f:status:
                  f:currentNumberScheduled: {}
                  f:desiredNumberScheduled: {}
                  f:numberAvailable: {}
                  f:numberReady: {}
                  f:observedGeneration: {}
                  f:updatedNumberScheduled: {}
              manager: kube-controller-manager
              operation: Update
              subresource: status
              time: "2024-10-15T08:17:37Z"
            name: e2e-mpzll-daemon-set
            namespace: controllerrevisions-609
            resourceVersion: "349"
            uid: 8d49b768-bb53-4e79-a718-42359779e7df
          spec:
            revisionHistoryLimit: 10
            selector:
              matchLabels:
                daemonset-name: e2e-mpzll-daemon-set
            template:
              metadata:
                creationTimestamp: null
                labels:
                  daemonset-name: e2e-mpzll-daemon-set
              spec:
                containers:
                - image: registry.k8s.io/e2e-test-images/httpd:2.4.38-4
                  imagePullPolicy: IfNotPresent
                  name: app
                  ports:
                  - containerPort: 9376
                    protocol: TCP
                  resources: {}
                  securityContext: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
                dnsPolicy: ClusterFirst
                restartPolicy: Always
                schedulerName: default-scheduler
                securityContext: {}
                terminationGracePeriodSeconds: 30
            updateStrategy:
              rollingUpdate:
                maxSurge: 0
                maxUnavailable: 1
              type: RollingUpdate
          status:
            currentNumberScheduled: 1
            desiredNumberScheduled: 1
            numberAvailable: 1
            numberMisscheduled: 0
            numberReady: 1
            observedGeneration: 1
            updatedNumberScheduled: 1
  In [It] at: /nvme/gopath/src/k8s.io/kubernetes/test/e2e/apps/controller_revision.go:140 @ 10/15/24 10:22:37.908
```

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by pohly** [comment]
cc @aojea @soltysh

**Comment by mimowo** [comment]
LGTM 
I particularly like the dump at the end of polling. We could use the same approach for Job, I think it could help with debugging. cc @kaisoz @atiratree

**Comment by soltysh** [comment]
Unrelated failure. 
/test pull-kubernetes-unit

**Comment by soltysh** [comment]
> This commit reverts all callers to what they were before (CheckDaemonStatus + ExpectNoError) and implements polling according to E2E best practices (https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/writing-good-e2e-tests.md#polling-and-timeouts):

I will admit I wasn't aware of the exists of this doc - thank you, reading right after I finish with this PR :sweat_smile:

File: test/e2e/framework/daemonset/fixtures.go [hunk 1]
```diff
@@ -138,18 +140,20 @@ func checkDaemonPodStateOnNodes(ctx context.Context, c clientset.Interface, ds *
...
-		framework.Logf("error in daemon status. DesiredScheduled: %d, CurrentScheduled: %d, Ready: %d", desired, scheduled, ready)
-		return false, nil
-	}
+// CheckDaemonStatus ensures that eventually the daemon set has the desired
+// number of pods scheduled and ready. It returns a descriptive error if that
+// state is not reached in the amount of time it takes to start
+// pods. f.Timeouts.PodStart can be changed to influence that timeout.
+func CheckDaemonStatus(ctx context.Context, f *framework.Framework, dsName string) error {
+	return framework.Gomega().Eventually(ctx, framework.GetObject(f.ClientSet.AppsV1().DaemonSets(f.Namespace.Name).Get, dsName, metav1.GetOptions{})).
+		WithTimeout(f.Timeouts.PodStart).
```
Comment (soltysh) [inline test/e2e/framework/daemonset/fixtures.go:149]: Nit: but I'd probably move the timeout information to the caller, so that the fact this function doesn't check just once but waits up to timeout is more readable. Probably something we'll want to fix at some later time.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

File: test/e2e/framework/daemonset/fixtures.go (hunk 1 above)
Comment (pohly) [reply test/e2e/framework/daemonset/fixtures.go:149]: I agree and tried to address this with function documentation - but that's not ideal.

We don't have a good API pattern for optional function parameters. In e2epod, we ended up with lots of variants which just differ by the number and type of parameters. I think we should come up with something better, I just don't know yet what it is.

**Comment by pohly** [comment]
> LGTM I particularly like the dump at the end of polling. We could use the same approach for Job, I think it could help with debugging. 

e2epod got (partially) converted to this pattern when introducing some of the necessary helpers, but other areas haven't been touched. I agree that converting more code would be useful.

It's annoying that the dump includes the managed fields. I have been toying with the idea of stripping them out. On the other hand, someone might want to see them. :shrug:

**Comment by soltysh** [comment]
> It's annoying that the dump includes the managed fields. I have been toying with the idea of stripping them out. On the other hand, someone might want to see them. 🤷

Something like https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/printers/managedfields.go should help. But honestly, I'd just leave it there for debugging. I doubt it's that big of a deal printing them.

File: test/e2e/framework/daemonset/fixtures.go (hunk 1 above)
Comment (pohly) [reply test/e2e/framework/daemonset/fixtures.go:149]: Actually, e2epod has one such pattern: provide building blocks (get function, gomega matcher) and let the caller decide how to put them together.

In this case, the call could look like this:
```
gomega.Eventually(ctx, e2edaemonset.Get(f, ds)).[WithTimeout(...)].Should(e2edaemonset.HaveAllPodsReady)
```

Comment (pohly) [reply test/e2e/framework/daemonset/fixtures.go:149]: This is similar to the "return function for wait.Poll` approach from Antonio, except that it is for Gomega and more modular (getting the daemon set and assertions against it are separate).
