### PR TITLE
fix: don't use docker config cache if it's empty

### LINKED ISSUE #92326: Pulling Azure Container Registry image using Managed Service Identity may fail
**What happened**:
When Managed Service Identity (MSI) is used to pull images from Azure Container Registry (ACR), it may fail with `Failed to pull image "<redacted>.azurecr.io/<redacted>": rpc error: code = Unknown desc = Error response from daemon: Get https://<redacted>.azurecr.io/v2/<redacted>: unauthorized: authentication required` even though the MSI has reader access to the ACR. It will recover in 1-2 minutes.

**What you expected to happen**:
It should not have any unauthorized error.

**How to reproduce it (as minimally and precisely as possible)**:
1. run a k8s deployment using public docker image
2. immediately run a k8s deployment using ACR image
3. observe the error in get events
```
66s         Normal    Scheduled           Pod          Successfully assigned default/nginx-deployment-7fd6966748-txsdm to aks-agentpool-17585647-vmss000001
65s         Normal    Pulling             Pod          Pulling image "nginx:1.14.2"
61s         Normal    Pulled              Pod          Successfully pulled image "nginx:1.14.2"
58s         Normal    Created             Pod          Created container nginx
58s         Normal    Started             Pod          Started container nginx
66s         Normal    Scheduled           Pod          Successfully assigned default/nginx-deployment-7fd6966748-xmk6h to aks-agentpool-17585647-vmss000000
65s         Normal    Pulling             Pod          Pulling image "nginx:1.14.2"
61s         Normal    Pulled              Pod          Successfully pulled image "nginx:1.14.2"
58s         Normal    Created             Pod          Created container nginx
58s         Normal    Started             Pod          Started container nginx
66s         Normal    SuccessfulCreate    ReplicaSet   Created pod: nginx-deployment-7fd6966748-xmk6h
66s         Normal    SuccessfulCreate    ReplicaSet   Created pod: nginx-deployment-7fd6966748-txsdm
66s         Normal    SuccessfulCreate    ReplicaSet   Created pod: nginx-deployment-7fd6966748-bxb62
66s         Normal    ScalingReplicaSet   Deployment   Scaled up replica set nginx-deployment-7fd6966748 to 3
46s         Normal    Scheduled           Pod          Successfully assigned default/ubuntu-56b4744f8b-6mcpk to aks-agentpool-17585647-vmss000000
4s          Normal    Pulling             Pod          Pulling image "<redacted>.azurecr.io/<redacted>"
30s         Warning   Failed              Pod          Failed to pull image "<redacted>.azurecr.io/<redacted>": rpc error: code = Unknown desc = Error response from daemon: Get https://<redacted>.azurecr.io/v2/<redacted>: unauthorized: authentication required
30s         Warning   Failed              Pod          Error: ErrImagePull
16s         Normal    BackOff             Pod          Back-off pulling image "<redacted>.azurecr.io/<redacted>"
16s         Warning   Failed              Pod          Error: ImagePullBackOff
```

Kubelet log:
```
Jun 19 22:36:33 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:33.421665   29650 provider.go:124] Refreshing cache for provider: *credentialprovider.defaultDockerConfigProvider
Jun 19 22:36:33 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:33.422075   29650 config.go:137] looking for config.json at /var/lib/kubelet/config.json
Jun 19 22:36:33 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:33.422119   29650 config.go:137] looking for config.json at /config.json
Jun 19 22:36:33 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:33.422130   29650 config.go:137] looking for config.json at /.docker/config.json
Jun 19 22:36:33 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:33.422137   29650 config.go:137] looking for config.json at /.docker/config.json
Jun 19 22:36:33 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:33.422148   29650 config.go:107] looking for .dockercfg at /var/lib/kubelet/.dockercfg
Jun 19 22:36:33 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:33.422177   29650 config.go:107] looking for .dockercfg at /.dockercfg
Jun 19 22:36:33 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:33.422186   29650 config.go:107] looking for .dockercfg at /.dockercfg
Jun 19 22:36:33 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:33.422194   29650 config.go:107] looking for .dockercfg at /.dockercfg
Jun 19 22:36:33 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:33.422202   29650 provider.go:94] Unable to parse Docker config file: couldn't find valid .dockercfg after checking in [/var/lib/kubelet   /]
Jun 19 22:36:33 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:33.422210   29650 provider.go:124] Refreshing cache for provider: *azure.acrProvider
Jun 19 22:36:33 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:33.422232   29650 azure_credentials.go:189] try to provide secret for image docker.io/library/nginx
Jun 19 22:36:33 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:33.422244   29650 azure_credentials.go:194] image(docker.io/library/nginx) is not from ACR, skip MSI authentication
Jun 19 22:36:33 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:33.422262   29650 kuberuntime_image.go:47] Pulling image "nginx:1.14.2" without credentials
Jun 19 22:36:33 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:33.421975   29650 event.go:258] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"nginx-deployment-7fd6966748-xmk6h", UID:"128464dd-b9d3-4e54-a3f9-77d7af6e3be2", APIVersion:"v1", ResourceVersion:"158317", FieldPath:"spec.containers{nginx}"}): type: 'Normal' reason: 'Pulling' Pulling image "nginx:1.14.2"
Jun 19 22:36:37 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:37.096673   29650 kube_docker_client.go:345] Stop pulling image "nginx:1.14.2": "Status: Downloaded newer image for nginx:1.14.2"

Jun 19 22:36:54 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:54.067201   29650 event.go:258] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"ubuntu-56b4744f8b-6mcpk", UID:"d9d46d4b-7d40-4c10-82c4-07a36a788d7b", APIVersion:"v1", ResourceVersion:"158402", FieldPath:"spec.containers{ubuntu}"}): type: 'Normal' reason: 'Pulling' Pulling image "<redacted>.azurecr.io/<redacted>"
Jun 19 22:36:54 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:54.175261   29650 kubelet.go:1975] SyncLoop (housekeeping)
Jun 19 22:36:54 aks-agentpool-17585647-vmss000000 kubelet[29650]: E0619 22:36:54.310523   29650 remote_image.go:113] PullImage "<redacted>.azurecr.io/<redacted>" from image service failed: rpc error: code = Unknown desc = Error response from daemon: Get https://<redacted>.azurecr.io/v2/fundamental/test/manifests/v0.0.12: unauthorized: authentication required
Jun 19 22:36:54 aks-agentpool-17585647-vmss000000 kubelet[29650]: E0619 22:36:54.310655   29650 kuberuntime_manager.go:779] container start failed: ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: Get https://<redacted>.azurecr.io/v2/fundamental/test/manifests/v0.0.12: unauthorized: authentication required
Jun 19 22:36:54 aks-agentpool-17585647-vmss000000 kubelet[29650]: E0619 22:36:54.310682   29650 pod_workers.go:190] Error syncing pod d9d46d4b-7d40-4c10-82c4-07a36a788d7b ("ubuntu-56b4744f8b-6mcpk_default(d9d46d4b-7d40-4c10-82c4-07a36a788d7b)"), skipping: failed to "StartContainer" for "ubuntu" with ErrImagePull: "rpc error: code = Unknown desc = Error response from daemon: Get https://<redacted>.azurecr.io/v2/fundamental/test/manifests/v0.0.12: unauthorized: authentication required"
Jun 19 22:36:54 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:54.310974   29650 event.go:258] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"ubuntu-56b4744f8b-6mcpk", UID:"d9d46d4b-7d40-4c10-82c4-07a36a788d7b", APIVersion:"v1", ResourceVersion:"158402", FieldPath:"spec.containers{ubuntu}"}): type: 'Warning' reason: 'Failed' Failed to pull image "<redacted>.azurecr.io/<redacted>": rpc error: code = Unknown desc = Error response from daemon: Get https://<redacted>.azurecr.io/v2/fundamental/test/manifests/v0.0.12: unauthorized: authentication required
Jun 19 22:36:54 aks-agentpool-17585647-vmss000000 kubelet[29650]: I0619 22:36:54.311026   29650 event.go:258] Event(v1.ObjectReference{Kind:"Pod", Namespace:"default", Name:"ubuntu-56b4744f8b-6mcpk", UID:"d9d46d4b-7d40-4c10-82c4-07a36a788d7b", APIVersion:"v1", ResourceVersion:"158402", FieldPath:"spec.containers{ubuntu}"}): type: 'Warning' reason: 'Failed' Error: ErrImagePull
```
**Anything else we need to know?**:
When MSI is configured in kubelet and a non-ACR docker image is pulled, the code [here](https://github.com/kubernetes/kubernetes/blob/v1.15.10/pkg/credentialprovider/azure/azure_credentials.go#L194) will skip the MSI authentication flow and [return an empty docker registry cfg](https://github.com/kubernetes/kubernetes/blob/v1.15.10/pkg/credentialprovider/azure/azure_credentials.go#L213) assuming it's anonymous ACR auth. The resulting docker registry cfg is [cached in the credential provider](https://github.com/kubernetes/kubernetes/blob/v1.15.10/pkg/credentialprovider/provider.go#L120). So any image pull from ACR will use the staled docker registry cfg and got unauthorized authentication until the cache is refreshed

**Environment**:
- Kubernetes version (use `kubectl version`): 1.15.10
- Cloud provider or hardware configuration: AKS with MSI

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: don't use docker config cache is it's empty
In this PR
 - don't use docker config cache is it's empty
 - return empty docker config if it's using Managed Identity and image is not from ACR

**Which issue(s) this PR fixes**:

Fixes #92326

**Special notes for your reviewer**:
On a MSI enabled cluster, when non-ACR docker image is pulled first, the cache credential will only cache anonymous access credential, managed identity credential won't be fetched in the next 5min until cache expired.

**Does this PR introduce a user-facing change?**:

```release-note
fix: don't use docker config cache if it's empty
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

/kind bug
/assign @weinong  
/priority important-soon
/sig cloud-provider
/area provider/azure

### CODE REVIEW

**Comment by weinong** [comment]
add any unit tests?

**Comment by andyzhangx** [comment]
> add any unit tests?

@weinong done, PTAL

**Review by feiskyer — APPROVED** [review]
/lgtm

File: pkg/credentialprovider/provider.go [hunk 1]
```diff
@@ -90,8 +90,8 @@ func (d *CachingDockerConfigProvider) Provide(image string) DockerConfig {
 	d.mu.Lock()
 	defer d.mu.Unlock()
 
-	// If the cache hasn't expired, return our cache
-	if time.Now().Before(d.expiration) {
+	// If the cache hasn't expired, return our cache if cache is not empty
+	if time.Now().Before(d.expiration) && len(d.cacheDockerConfig) > 0 {
```
Comment (liggitt) [inline pkg/credentialprovider/provider.go:94]: this is problematic if `d.Provider.Provide` is expensive, and ends up returning an empty entry

Comment (andyzhangx) [reply pkg/credentialprovider/provider.go:94]: @liggitt what about add a new field(`useEmptyCache`) in `CachingDockerConfigProvider`,  it's `true` by default for aws, gce, and `false` for azure? and change following interface a little:
`Provide(image string) DockerConfig`  --> `Provide(image string) (DockerConfig, useEmptyCache)`

Comment (liggitt) [reply pkg/credentialprovider/provider.go:94]: rather than an interface change (lower layers should probably not be aware of a higher-level cache), an option in CachingDockerConfigProvider that defaults to current behavior seems ok.

```diff
diff --git a/pkg/credentialprovider/provider.go b/pkg/credentialprovider/provider.go
index 72a706b5c74..db283d63566 100644
--- a/pkg/credentialprovider/provider.go
+++ b/pkg/credentialprovider/provider.go
@@ -58,6 +58,10 @@ type CachingDockerConfigProvider struct {
        Provider DockerConfigProvider
        Lifetime time.Duration
 
+       // Cacheable is an optional function that returns true if the specific config should be cached.
+       // If nil, all configs are treated as cacheable.
+       Cacheable func(DockerConfig) bool
+
        // cache fields
        cacheDockerConfig DockerConfig
        expiration        time.Time
@@ -96,7 +100,10 @@ func (d *CachingDockerConfigProvider) Provide(image string) DockerConfig {
        }
 
        klog.V(2).Infof("Refreshing cache for provider: %v", reflect.TypeOf(d.Provider).String())
-       d.cacheDockerConfig = d.Provider.Provide(image)
-       d.expiration = time.Now().Add(d.Lifetime)
-       return d.cacheDockerConfig
+       config := d.Provider.Provide(image)
+       if d.ShouldCache == nil || d.ShouldCache(config) {
+               d.cacheDockerConfig = config
+               d.expiration = time.Now().Add(d.Lifetime)
+       }
+       return config
 }
```

then azure can set 
```go
Cacheable: func(d DockerConfig) bool { return len(d) > 0 }
```

Comment (andyzhangx) [reply pkg/credentialprovider/provider.go]: I just followed your instructions, PTAL, thanks!

File: pkg/credentialprovider/provider.go [hunk 2]
```diff
@@ -96,7 +100,10 @@ func (d *CachingDockerConfigProvider) Provide(image string) DockerConfig {
...
 
 	klog.V(2).Infof("Refreshing cache for provider: %v", reflect.TypeOf(d.Provider).String())
-	d.cacheDockerConfig = d.Provider.Provide(image)
-	d.expiration = time.Now().Add(d.Lifetime)
+	config := d.Provider.Provide(image)
+	if d.ShouldCache == nil || d.ShouldCache(config) {
+		d.cacheDockerConfig = config
+		d.expiration = time.Now().Add(d.Lifetime)
+	}
 	return d.cacheDockerConfig
```
Comment (liggitt) [inline pkg/credentialprovider/provider.go:108]:
```suggestion
	return d.config
```

Comment (andyzhangx) [reply pkg/credentialprovider/provider.go]: fixed, thanks.

File: pkg/credentialprovider/azure/azure_credentials_test.go [hunk 3]
```diff
@@ -96,6 +98,42 @@ func Test(t *testing.T) {
...
+		expectedCredsLength int
+	}{
+		{
+			desc: "return multiple credentials using Service Principal",
+			configStr: `
+    {
+        "aadClientId": "foo",
+        "aadClientSecret": "bar"
+    }`,
+			expectedCredsLength: 5,
```
Comment (weinong) [inline pkg/credentialprovider/azure/azure_credentials_test.go:114]: why does it return 5 credentials?

Comment (weinong) [reply pkg/credentialprovider/azure/azure_credentials_test.go:114]: oh i see it now

**Review by weinong — APPROVED** [review]
/lgtm
