### PR TITLE
Restore bootstrap in the background with fix to preserve kubeadm behavior

### LINKED ISSUE #68686: Kubelet does not launch static pods while waiting for bootstrapping
The kubelet currently blocks trying to attempt to get a bootstrap client before it starts its worker loops for running static pods, which means a static pod that provides functionality on a node that bootstrapping may need (talking to an HSM, calling out externally, providing a plugin for bootstrapping, or even running a control plane pod) is blocked.  There is no actual functionality in the Kubelet that depends on this (waiting for bootstrap has no use case value), it's just a historical legacy of how the code evolved.  As people start to leverage bootstrapping and rotation, it becomes more obvious how this doesn't work in practice.

In the long run we want bootstrap credentials to be pluggable and extensible so that an HSM or other trust store on the machine can deal with the problem.  Having secret key material for bootstrapping stored on disk that allows you to join a cluster is undesirable, and having a callout to make that flow less error prone is very desirable for both cloud and metal provisioned environments.

In addition, the bootstrapping and client cert rotation flows are slightly duplicated today - using the client cert to rotate itself means that when a client cert expires (very possible with quicker rotations if the api goes down for a period of time) the bootstrap credential is consulted - but that could be arbitrarily far in the future and means we tend to fail in those cases (bootstrap credential expired).  Since the long term desire is for bootstrap to be out of process, it would be better for us to continually go back to bootstrap on cert expiration rather than retrying our flow.

For 1.13, we should fix the kubelet to not pause when bootstrapping and instead delegate to the rotation flow to provide that credential.  This has the side effect of reducing duplicated code for procuring CSRs between the two code paths, and hiding the details of client cert acquisition inside of the cert manager so that future changes can allow call outs.

@awly @mikedanese as discussed this week, @kubernetes/sig-auth-misc / @kubernetes/sig-node-bugs, @liggitt because you and discussed this, @aaronlevy because we wanted to push allow static pods for bootstrap control planes in bootkube not to block when using bootstrapping kubelets..

### PR DESCRIPTION
**Pull request by smarterclayton**
This restores the revert of #69890 due to a failure in kubeadm.

fixes https://github.com/kubernetes/kubernetes/issues/68686

kubeadm depends on being able to give the kubelet a high powered cert as `--kubeconfig` on the master and expects the kubelet to rotate that cert.  For now, preserve the behavior, even though this doesn't improve security on the masters (being able to read root owned files off the master is not a critical part of our threat model).   Add comments and a test to ensure this is clearly required.

```release-note
When a kubelet is using --bootstrap-kubeconfig and certificate rotation, it no longer waits for bootstrap to succeed before launching static pods.
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
/assign @mikedanese 
cc @liggitt

**Comment by smarterclayton** [comment]
kubeadm passed https://gubernator.k8s.io/build/kubernetes-jenkins/pr-logs/pull/71174/pull-kubernetes-e2e-kubeadm-gce/15989/

**Comment by neolit123** [comment]
@smarterclayton 
could you please add a release note for the release note tool to pick this up.
the PR title would suffice.

File: cmd/kubelet/app/server.go [hunk 1]
```diff
@@ -771,6 +735,118 @@ func run(s *options.KubeletServer, kubeDeps *kubelet.Dependencies, stopCh <-chan
...
+		//    the file is present the client config will have no certs
+		// 3. If the client provides both and the kubeconfig is valid, we must ignore the bootstrap
+		//    kubeconfig.
+		// 4. If the client provides both and the kubeconfig is expired or otherwise invalid, we must
+		//    replace the kubeconfig with a new file that points to the cert dir
+		//
+		// The desired configuration for bootstrapping is to use a bootstrap kubeconfig and to have
+		// the kubeconfig file be managed by this process. For backwards compatibility with kubeadm,
+		// which provides a high powered kubeconfig on the master with cert/key data, we must
+		// bootstrap the cert manager with the contents of the initial client config.
```
Comment (neolit123) [inline cmd/kubelet/app/server.go]: thanks a lot working on this and the detailed comments!
do you think that kubeadm should move away from the high-powered kubeconfig model?

to me it feels like we are adding a workaround for something that kubeadm is doing.

will cc @luxas here, although not sure if he will have the time to take a look.

**Review by neolit123 — COMMENTED** [review]
@smarterclayton 
btw `pull-kubernetes-e2e-kubeadm-gce — Skipped`, not sure if it was actually skipped.
were you able to create a kubeadm setup locally for testing purposes?

**Comment by neolit123** [comment]
while there are kubeadm related topics for this PR, sig-node should give the final LGTM.

**Comment by mikedanese** [comment]
Thanks. Looking...

**Comment by timothysc** [comment]
/assign @fabriziopandini @liztio  

please review ^

File: cmd/kubelet/app/server.go (hunk 1 above)
Comment (smarterclayton) [reply cmd/kubelet/app/server.go]: For back compat we need to continue to support it.  I think kubeadm should be able to switch to setting bootstrap-kubeconfig equal to their high powered cert on masters, because all root file access on masters is powerful.  Then we could remove the need to support this case.

**Comment by smarterclayton** [comment]
You can see all kubeadm runs with https://gubernator.k8s.io/builds/kubernetes-jenkins/pr-logs/pull/71174/pull-kubernetes-e2e-kubeadm-gce/

The job won't trigger until my PR to test-infra merges (to detect changes to bootstrap code).  Also, because `skip_report: true` on the job, you can't see the status from the link (you have to look at the gubernator logs)

/test pull-kubernetes-e2e-kubeadm-gce

File: cmd/kubelet/app/server.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubelet/app/server.go]: we briefly discussed this today with @fabriziopandini and he had a proposal.

**Comment by neolit123** [comment]
> The job won't trigger until my PR to test-infra merges

pinged sig-testing about it.

**Comment by timothysc** [comment]
What's the risk of holding on this till 1.14?

**Comment by luxas** [comment]
Also just wanna point out that in v1.14 we should strive to not need the "workaround" for how kubeadm sets this up, but instead merge this PR _and_ a kubeadm patch so kubeadm isn't blocked on that a kubelet with no clientcert won't start static pods.

**Comment by smarterclayton** [comment]
We ready to merge this? 

@luxas once kubeadm is changed, I can submit the PR that removes the workaround for the old code path (although it's enough of a part of our API that we might need a formal deprecation period)

**Comment by liggitt** [comment]
+1 from me

**Review by luxas — APPROVED** [review]
I haven't reviewed this in detail, but I'm happy to proceed with this.
Re-adding the LGTM and putting this in the queue, and we'll follow this up in kubeadm.
/lgtm
