### PR TITLE
kubelet_running_pods shows number of pods that have a running pod sandbox

### LINKED ISSUE #99624: kubelet_running_pods metric includes Pending pods
#### What happened:
kubelet metric `kubelet_running_pods` should only count pods in `Running` state. But it incorrectly reports the sum of pods in `Running` + `Pending` state. 

#### What you expected to happen:
Only pods in `Running` state should be counted. 

#### How to reproduce it (as minimally and precisely as possible):
Create a pod with sample yaml to create a pod that stays in `Pending` state. 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod
spec:
  containers:
    - name: dummy-pod
      image: ubuntu
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  restartPolicy: Always 
```
Verify that pod we created is in `Pending` state,

```bash
$ kubectl get pod -A -o go-template='{{range .items}}{{if eq .spec.nodeName "testclustgt1-js74g-worker-a-smjc7"}}{{.status.phase}}{{"\n"}}{{end}}{{end}}'
Pending
Running
Running
Running
Running
Running
Running
Running
Running
Running
Running
Running
Running
Running
Running
```
```bash
$ kubectl get pod dummy-pod -o  go-template='{{.status.phase}}'
Pending
```
Now let's count the total number of pods using `kubectl`
```
$ kubectl get pod -A -o go-template='{{range .items}}{{if eq .spec.nodeName "testclustgt1-js74g-worker-a-smjc7"}}{{.status.phase}}{{"\n"}}{{end}}{{end}}' | wc -l 
15
```
Out of 15, 1 is in `Pending` and rest are in `Running` state.
```bash
kubectl get pod -A -o go-template='{{range .items}}{{if eq .spec.nodeName "testclustgt1-js74g-worker-a-smjc7"}}{{.status.phase}}{{"\n"}}{{end}}{{end}}'|grep Pending|wc -l 
1
```
```bash
$ kubectl get pod -A -o go-template='{{range .items}}{{if eq .spec.nodeName "testclustgt1-js74g-worker-a-smjc7"}}{{.status.phase}}{{"\n"}}{{end}}{{end}}'|grep Running|wc -l 
14
```
But the corresponding metric `kubelet_running_pods{node="testclustgt1-js74g-worker-a-smjc7"}` from Prometheus dashboard returns 15. 

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind documentation

#### What this PR does / why we need it:
To make it much clearer:

`Number of pods currently running`
to
`Number of pods that have a running pod sandbox`

#### Which issue(s) this PR fixes:
Fixes #99624

#### Special notes for your reviewer:
https://github.com/kubernetes/kubernetes/issues/99624#issuecomment-823412461
> IIRC, kubelet_running_pods is not intended to reflect the pod phase in the API server.
> 
> It is used to expose the kubelet internal state: how many pods have running containers in the container runtime, and mainly for debugging purpose.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

File: pkg/kubelet/metrics/metrics.go [hunk 1]
```diff
@@ -412,12 +412,13 @@ var (
...
 
-	// RunningPodCount is a gauge that tracks the number of Pods currently running
+	// RunningPodCount is a gauge that tracks the number of Pods currently  in running phase
+	// It is used to expose the kubelet internal state: how many pods have running containers in the container runtime, and mainly for debugging purpose.
 	RunningPodCount = metrics.NewGauge(
 		&metrics.GaugeOpts{
 			Subsystem:      KubeletSubsystem,
 			Name:           RunningPodsKey,
-			Help:           "Number of pods currently running",
+			Help:           "Number of pods currently in running phase",
```
Comment (Random-Liu) [inline pkg/kubelet/metrics/metrics.go:421]: IIUC, running_pods == pause container number >= pods with pause container number >= pods in running phase.

So "in running phase" doesn't seem to be accurate here.

Comment (pacoxu) [reply pkg/kubelet/metrics/metrics.go:421]: so running-pod number here is actually pause-container number？

Comment (pacoxu) [reply pkg/kubelet/metrics/metrics.go:421]: Updated

File: pkg/kubelet/metrics/metrics.go [hunk 2]
```diff
@@ -412,12 +412,13 @@ var (
...
 
-	// RunningPodCount is a gauge that tracks the number of Pods currently running
+	// RunningPodCount is a gauge that tracks the number of Pods currently with a running pause/sandbox container
+	// It is used to expose the kubelet internal state: how many pods have running containers in the container runtime, and mainly for debugging purpose.
 	RunningPodCount = metrics.NewGauge(
 		&metrics.GaugeOpts{
 			Subsystem:      KubeletSubsystem,
 			Name:           RunningPodsKey,
-			Help:           "Number of pods currently running",
+			Help:           "Number of pods currently with a running pause container",
```
Comment (derekwaynecarr) [inline pkg/kubelet/metrics/metrics.go:421]: The pause container is an implementation detail.  Containers may have running pod sandboxes with no corresponding pause container on the host.  For example, CRI-O avoids creation of a pause container when specific resources on the pod spec do not need to be shared among containers in the pod.

Can we update this text to say:

"Number of pods that have a running pod sandbox"

Thanks!

**Review by derekwaynecarr — CHANGES_REQUESTED** [review]
the pause container is an implementation detail.

we should reference the presence of a running pod sandbox instead.

File: pkg/kubelet/metrics/metrics.go (hunk 2 above)
Comment (pacoxu) [reply pkg/kubelet/metrics/metrics.go]: Thanks for the detailed explanation. It makes sense.

Updated. @derekwaynecarr

File: pkg/kubelet/metrics/metrics.go [hunk 3]
```diff
@@ -412,12 +412,13 @@ var (
 		[]string{"runtime_handler"},
 	)
 
-	// RunningPodCount is a gauge that tracks the number of Pods currently running
+	// RunningPodCount is a gauge that tracks the number of Pods currently with a running pause/sandbox container
```
Comment (ehashman) [inline pkg/kubelet/metrics/metrics.go:415]:
```suggestion
	// RunningPodCount is a gauge that tracks the number of Pods currently with a running sandbox
```

File: pkg/kubelet/metrics/metrics.go [hunk 4]
```diff
@@ -412,12 +412,13 @@ var (
...
+	// It is used to expose the kubelet internal state: how many pods have running containers in the container runtime, and mainly for debugging purpose.
 	RunningPodCount = metrics.NewGauge(
 		&metrics.GaugeOpts{
 			Subsystem:      KubeletSubsystem,
 			Name:           RunningPodsKey,
-			Help:           "Number of pods currently running",
+			Help:           "Number of pods that have a running pod sandboxr",
```
Comment (ehashman) [inline pkg/kubelet/metrics/metrics.go:421]:
```suggestion
			Help:           "Number of pods that have a running pod sandbox",
```

File: pkg/kubelet/pleg/generic_test.go [hunk 5]
```diff
@@ -702,7 +702,7 @@ kubelet_running_containers{container_state="unknown"} 2
 			name:        "test pod count",
 			metricsName: "kubelet_running_pods",
 			wants: `
-# HELP kubelet_running_pods [ALPHA] Number of pods currently running
+# HELP kubelet_running_pods [ALPHA] Number of pods that have a running pod sandboxr
```
Comment (ehashman) [inline pkg/kubelet/pleg/generic_test.go:705]:
```suggestion
# HELP kubelet_running_pods [ALPHA] Number of pods that have a running pod sandbox
```

**Comment by pacoxu** [comment]
Updated. Typo 😓

**Review by ehashman — APPROVED** [review]
/lgtm

**Comment by pacoxu** [comment]
/test pull-kubernetes-node-e2e-containerd
for CI hang
