### PR TITLE
Increase cache size for EndpointSlices.

### LINKED ISSUE #85342: Kube-proxies EndpointSlice WATCH restarts overloading control-plane
The regression is caused by two changes:
* Changes in reflector (https://github.com/kubernetes/kubernetes/pull/83520) which results in issuing LIST with RV="" (meaning it will go to etcd) on WATCH restarts caused by 410 (RV too old) errors

* Enabling EndpointSlice API without bumping the cache size for EndpointSlices (will be fixed in https://github.com/kubernetes/kubernetes/pull/85339). The default cache size is 100, which is not enough for resources that can change as rapidly as  EndpointSlice (to compare cache size for Endpoints, which EndpointSlices is replacing, was 10* # nodes), which results in WATCHes being terminated with 410 and then issuing heavy LISTs to restart them (see above). If you take into account that this happens on each node (kube-proxy is watching EndpointSlices) the burst in heavy LIST can effectively kill control-plane which we observe in scale tests.

Below the graphs showing exactly this situation in kubemark-5K test (last two runs failed in exactly the same way):

aiRRMgFfk4e
JgzXWBMXCpE

We hope that https://github.com/kubernetes/kubernetes/pull/85339 will fix the issue and make our tests passing. We're currently running the tests manually to confirm that.

/sig scalability
/milestone v1.17

### PR DESCRIPTION
**Pull request by mm4tt**
We're increasing the cache size for EndpointSlices to match the size for Endpoints (which EndpointsSlices are replacing).
This is to fix https://github.com/kubernetes/kubernetes/issues/85342

**What type of PR is this?**
/kind bug

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/sig scalability
/priority critical-urgent

/milestone 1.17
This is fixing a release blocking bug

### CODE REVIEW

File: pkg/registry/cachesize/cachesize.go [hunk 1]
```diff
@@ -36,6 +36,7 @@ func NewHeuristicWatchCacheSizes(expectedRAMCapacityMB int) map[schema.GroupReso
 	watchCacheSizes := make(map[schema.GroupResource]int)
 	watchCacheSizes[schema.GroupResource{Resource: "replicationcontrollers"}] = maxInt(5*clusterSize, 100)
 	watchCacheSizes[schema.GroupResource{Resource: "endpoints"}] = maxInt(10*clusterSize, 1000)
+	watchCacheSizes[schema.GroupResource{Resource: "endpointslices", Group: "discovery.k8s.io"}] = maxInt(10*clusterSize, 1000)
```
Comment (liggitt) [inline pkg/registry/cachesize/cachesize.go]: are these 1:1 with endpoints? I thought there were expected to be fewer of these. cc @robscott

Comment (mm4tt) [reply pkg/registry/cachesize/cachesize.go]: They are not, it's a one Endpoints object to many EndpointsSlice objects relation.
But what matters for the cache size is the number of updates which is roughly the same, i.e. for a single pod change there will be one Endpoints object update and also one EndpointSlice object update.

Comment (wojtek-t) [reply pkg/registry/cachesize/cachesize.go]: Yes - this cache is not number of objects, but number of recent changes (events) we keep.
Roughly 1:1 correspondence here is what we want.

**Comment by wojtek-t** [comment]
Adding milestone, given that it's clearly a regression in 1.17 (where EndpointSlice will become enabled by default).

File: pkg/registry/cachesize/cachesize.go (hunk 1 above)
Comment (thockin) [reply pkg/registry/cachesize/cachesize.go]: It seems problematic that this is fixed and open-coded.  Even *I* did not know to change this.

What can we do to make this automatic and heuristic rather than manual?

Comment (wojtek-t) [reply pkg/registry/cachesize/cachesize.go]: We should - I remember having an issue for it, but can't find it now. But yeah - it's in our backlog.
