### PR TITLE
Fail validation if container restart policy is 'Never' and resource resize restart policy isn't 'NotRequired'

### LINKED ISSUE #118674: warning or decline pod creation with RestartContainer resizePolicy  if the restartPolicy is Never
### What happened?

> Note: If the Pod's restartPolicy is Never, container's resize restart policy must be set to NotRequired for all Containers in the Pod.

https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/

This is already mentioned in the doc, but no warning or decline is shown when it happens.

### What did you expect to happen?

warning or decline 

/sig node

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-5
  namespace: qos-example
spec:
  restartPolicy: Never
  containers:
  - name: qos-demo-ctr-5
    image: docker.m.daocloud.io/library/nginx:1.14.2
    resizePolicy:
    - resourceName: cpu
      restartPolicy: NotRequired
    - resourceName: memory
      restartPolicy: RestartContainer
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"
```

### Anything else we need to know?

xref https://github.com/kubernetes/enhancements/issues/1287

### Kubernetes version

1.27

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by killshotrevival**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #118674

#### Special notes for your reviewer:
This is just a small check I have added, for validating the note we have in the Kubernetes website [here](https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/#:~:text=Note%3A%20If%20the%20Pod%27s%20restartPolicy%20is%20Never%2C%20container%27s%20resize%20restart%20policy%20must%20be%20set%20to%20NotRequired%20for%20all%20Containers%20in%20the%20Pod.)

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by kannon92** [comment]
You probably need a release note.

/sig node
/cc @pacoxu

**Comment by killshotrevival** [comment]
> You probably need a release note.
> 
> /sig node /cc @pacoxu

@kannon92 , can u please guide me to any documentation, on which I can follow, how to write release note. 🙏🏻  😃

**Comment by kannon92** [comment]
> > You probably need a release note.
> > /sig node /cc @pacoxu
> 
> @kannon92 , can u please guide me to any documentation, on which I can follow, how to write release note. 🙏🏻 😃

> #### Does this PR introduce a user-facing change?
> ```
> NONE
> ```

I think you can edit your PR description and add a release-note describing what you are adding. 

#### Does this PR introduce a user-facing change?
```
decline pod creation with RestartContainer resizePolicy if the restartPolicy is Never
```

For example.  I think this will be considered a breaking change so you may want to ask someone in api-review or sig-api-machinery if this would be allowed.  I think a warning would be a more user friendly change as you won't break existing users but you will at least mention that this behavior is not allowed.

**Comment by pacoxu** [comment]
The change LGTM and I prefer to get api reviewed by sig-node API reviewer or approver, and behavior confirmed by the VPA feature owner.

SIG Node API approvers @msau42 @smarterclayton @thockin, do you think this is needed?

File: pkg/apis/core/validation/validation_test.go [hunk 1]
```diff
@@ -6819,10 +6830,20 @@ func TestValidateResizePolicy(t *testing.T) {
 			},
 			true,
 			field.ErrorList{field.Duplicate(field.NewPath("field").Index(2), core.ResourceCPU)},
+			"Always",
+		},
+		"InvalidPolicyWithPodRestartPolicy": {
```
Comment (vinaykul) [inline pkg/apis/core/validation/validation_test.go:6835]: Just for completeness, could you please test cases for:
- cpu: RestartContainer, memory: NotRequired
- cpu: RestartContainer, memory: RestartContainer
- cpu: NotRequired, memory: NotRequired

**Review by vinaykul — CHANGES_REQUESTED** [review]
@pacoxu Thanks for spotting this issue :)
@killshotrevival Thanks for taking care of it! I have a few suggestions, please take a look.

**Comment by vinaykul** [comment]
/retitle Fail validation if container restart policy is 'Never' and resource resize restart policy isn't 'NotRequired'

File: pkg/apis/core/validation/validation.go [hunk 2]
```diff
@@ -3157,7 +3161,7 @@ func validateFieldAllowList(value interface{}, allowedFields map[string]bool, er
 }
 
 // validateInitContainers is called by pod spec and template validation to validate the list of init containers
-func validateInitContainers(containers []core.Container, regularContainers []core.Container, volumes map[string]core.VolumeSource, podClaimNames sets.String, fldPath *field.Path, opts PodValidationOptions) field.ErrorList {
+func validateInitContainers(containers []core.Container, regularContainers []core.Container, volumes map[string]core.VolumeSource, podClaimNames sets.String, fldPath *field.Path, opts PodValidationOptions, restartPolicy *core.RestartPolicy) field.ErrorList {
```
[the remark this answers is not in the document]
Comment (killshotrevival) [reply pkg/apis/core/validation/validation.go]: Hey @vinaykul , thanks for your review. I have update all your suggested changes, except this one.  Can you please elaborate a little more, that can help me understand ur concern a bit more, :) 
I have updated the test cases for the same, and they seem to work fine

**Comment by killshotrevival** [comment]
I am not very sure, why this 1 job is failing, I just renamed some variables, earlier it worked fine. I have also tested everything on my local too, 🤔

File: pkg/apis/core/validation/validation.go [hunk 3]
```diff
@@ -3068,13 +3068,17 @@ func validateResizePolicy(policyList []core.ContainerResizePolicy, fldPath *fiel
 		default:
 			allErrors = append(allErrors, field.NotSupported(fldPath, p.RestartPolicy, supportedResizePolicies.List()))
 		}
+
+		if *podRestartPolicy == core.RestartPolicyNever && p.RestartPolicy != core.NotRequired {
+			allErrors = append(allErrors, field.Invalid(fldPath, p.RestartPolicy, "Only NotRequired is allowed, if pod restartPolicy is Never"))
+		}
```
Comment (Tusenka) [inline pkg/apis/core/validation/validation.go:3074]: As I understand here, you add check that all the containers has restart policy "NotRequired" for the pod with policy "RestartNever".

**Review by Tusenka — APPROVED** [review]

**Review by Tusenka — APPROVED** [review]

**Review by Tusenka — COMMENTED** [review]
ok to test

File: pkg/apis/core/validation/validation.go [hunk 4]
```diff
@@ -3044,7 +3044,7 @@ func validatePullPolicy(policy core.PullPolicy, fldPath *field.Path) field.Error
 var supportedResizeResources = sets.NewString(string(core.ResourceCPU), string(core.ResourceMemory))
 var supportedResizePolicies = sets.NewString(string(core.NotRequired), string(core.RestartContainer))
 
-func validateResizePolicy(policyList []core.ContainerResizePolicy, fldPath *field.Path) field.ErrorList {
+func validateResizePolicy(policyList []core.ContainerResizePolicy, fldPath *field.Path, restartPolicy *core.RestartPolicy) field.ErrorList {
```
[the remark this answers is not in the document]
Comment (killshotrevival) [reply pkg/apis/core/validation/validation.go]: Done

File: pkg/apis/core/validation/validation.go [hunk 5]
```diff
@@ -3068,13 +3068,17 @@ func validateResizePolicy(policyList []core.ContainerResizePolicy, fldPath *fiel
...
+			allErrors = append(allErrors, field.NotSupported(fldPath, p.RestartPolicy, []string{string(core.NotRequired)}))
+		}
 	}
 	return allErrors
 }
 
 // validateEphemeralContainers is called by pod spec and template validation to validate the list of ephemeral containers.
 // Note that this is called for pod template even though ephemeral containers aren't allowed in pod templates.
-func validateEphemeralContainers(ephemeralContainers []core.EphemeralContainer, containers, initContainers []core.Container, volumes map[string]core.VolumeSource, podClaimNames sets.String, fldPath *field.Path, opts PodValidationOptions) field.ErrorList {
+func validateEphemeralContainers(ephemeralContainers []core.EphemeralContainer, containers, initContainers []core.Container, volumes map[string]core.VolumeSource, podClaimNames sets.String, fldPath *field.Path, opts PodValidationOptions, restartPolicy *core.RestartPolicy) field.ErrorList {
```
[the remark this answers is not in the document]
Comment (killshotrevival) [reply pkg/apis/core/validation/validation.go]: Done

File: pkg/apis/core/validation/validation.go [hunk 6]
```diff
@@ -3295,7 +3299,7 @@ func validateHostUsers(spec *core.PodSpec, fldPath *field.Path) field.ErrorList
 }
 
 // validateContainers is called by pod spec and template validation to validate the list of regular containers.
-func validateContainers(containers []core.Container, volumes map[string]core.VolumeSource, podClaimNames sets.String, fldPath *field.Path, opts PodValidationOptions) field.ErrorList {
+func validateContainers(containers []core.Container, volumes map[string]core.VolumeSource, podClaimNames sets.String, fldPath *field.Path, opts PodValidationOptions, restartPolicy *core.RestartPolicy) field.ErrorList {
```
[the remark this answers is not in the document]
Comment (killshotrevival) [reply pkg/apis/core/validation/validation.go]: Done

File: pkg/apis/core/validation/validation_test.go (hunk 1 above)
Comment (killshotrevival) [reply pkg/apis/core/validation/validation_test.go]: Done

**Comment by killshotrevival** [comment]
Hey @vinaykul, are there any other updates required from my side, that I can help with to clear out this PR

**Comment by pacoxu** [comment]
> The change LGTM and I prefer to get api reviewed by sig-node API reviewer or approver, and behavior confirmed by the VPA feature owner.
> 
> SIG Node API approvers @msau42 @smarterclayton @thockin, do you think this is needed?

This validation will fail old pod updates if the pod is already created with `restartPolicy:Never` and `resize.restartPolicy=RestartContainer`. Making it compatible with old-version storage is essential.

**Comment by msau42** [comment]
> This validation will fail old pod updates if the pod is already created with `restartPolicy:Never` and `resize.restartPolicy=RestartContainer`. Making it compatible with old-version storage is essential. So this is why we need confirmation from API reviewers/approvers.

It is ok to make validation breaking changes while a feature is still alpha. It does need a release note.

**Comment by thockin** [comment]
As long as it is staying Alpha, it's allowable, but I *would* do a release-note saying this.

**Review by pacoxu — APPROVED** [review]
/lgtm
Would you update the release note?

File: pkg/apis/core/validation/validation.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (vinaykul) [reply pkg/apis/core/validation/validation.go]: Please test this change with RestartPolicyNever (in addition to default restart policy) for a pod that has init containers and also by starting up an ephemeral container (kubectl debug command) to verify they continue to work well.

**Comment by vinaykul** [comment]
@killshotrevival Sorry for slow response, I recently started a new role and I have VERY limited bandwidth. Please see my response https://github.com/kubernetes/kubernetes/pull/118768#discussion_r1249152878 
Besides that it looks good.
/lgtm

**Comment by killshotrevival** [comment]
Hey @vinaykul, congratulations on the new role 😁.

File: pkg/apis/core/validation/validation.go [hunk 7]
```diff
@@ -3068,13 +3068,17 @@ func validateResizePolicy(policyList []core.ContainerResizePolicy, fldPath *fiel
 		default:
 			allErrors = append(allErrors, field.NotSupported(fldPath, p.RestartPolicy, supportedResizePolicies.List()))
 		}
+
+		if *podRestartPolicy == core.RestartPolicyNever && p.RestartPolicy != core.NotRequired {
+			allErrors = append(allErrors, field.Invalid(fldPath, p.RestartPolicy, "Only NotRequired is allowed, if pod restartPolicy is Never"))
```
Comment (thockin) [inline pkg/apis/core/validation/validation.go:3073]: the message needs to follow conventions (https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#validation)

```
"must be 'NotRequired' when `restartPolicy` is 'Never'"
```

File: pkg/apis/core/validation/validation_test.go [hunk 8]
```diff
@@ -6749,10 +6749,13 @@ func TestValidateResizePolicy(t *testing.T) {
...
 	type T struct {
-		PolicyList  []core.ContainerResizePolicy
-		ExpectError bool
-		Errors      field.ErrorList
+		PolicyList       []core.ContainerResizePolicy
+		ExpectError      bool
+		Errors           field.ErrorList
+		PodRestartPolicy core.RestartPolicy
 	}
+	// var PodRestartPolicy core.RestartPolicy
```
Comment (thockin) [inline pkg/apis/core/validation/validation_test.go:6757]: What are these lines?

File: pkg/apis/core/validation/validation_test.go [hunk 9]
```diff
@@ -6749,10 +6749,13 @@ func TestValidateResizePolicy(t *testing.T) {
...
+	// PodRestartPolicy = "Never"
 	testCases := map[string]T{
 		"ValidCPUandMemoryPolicies": {
 			[]core.ContainerResizePolicy{
```
Comment (thockin) [inline pkg/apis/core/validation/validation_test.go:6761]: It would be really nice to change this to use named fields in all cases - it's hard to read without.

If you do this, please do it as a separate commit BEFORE this one

File: pkg/apis/core/validation/validation_test.go [hunk 10]
```diff
@@ -6918,7 +6966,9 @@ func TestValidateEphemeralContainers(t *testing.T) {
 			},
 		}},
 	} {
-		if errs := validateEphemeralContainers(ephemeralContainers, containers, initContainers, vols, nil, field.NewPath("ephemeralContainers"), PodValidationOptions{}); len(errs) != 0 {
+		var PodRestartPolicy core.RestartPolicy
+		PodRestartPolicy = "Never"
```
Comment (vinaykul) [inline pkg/apis/core/validation/validation_test.go:6970]: Please exercise this for default (Always) and OnFailure as well.

File: pkg/apis/core/validation/validation_test.go [hunk 11]
```diff
@@ -7172,9 +7222,11 @@ func TestValidateEphemeralContainers(t *testing.T) {
 	},
 	}
 
+	var PodRestartPolicy core.RestartPolicy
+	PodRestartPolicy = "Never"
```
Comment (vinaykul) [inline pkg/apis/core/validation/validation_test.go:7226]: Same here. Please exercise this for default (Always) and OnFailure as well.

**Comment by vinaykul** [comment]
@killshotrevival Can you please update the description with the test logs for a pod with init container and exercising ephemeral (via kubectl debug) ? I think it is best to add E2E test case for this change. It can be added to test/e2e/node/pod_resize.go
/hold

**Comment by thockin** [comment]
I don't know about E2E for this micro feature. E2E is expensive.

**Comment by vinaykul** [comment]
> I don't know about E2E for this micro feature. E2E is expensive.
> […](#)

Fair.

@killshotrevival It is good enough to document in the description above the E2E testing done with a local cluster.

Perhaps use the spec below:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  restartPolicy: Never
  initCcontainers:
  - name: ic
    image: busybox
    command: ["sleep", "2"]
  containers:
  - name: c
    image: busybox
    command: ["tail", "-f", "/dev/null"]
    resizePolicy:
    - resourceName: cpu
      restartPolicy: NotRequired
    - resourceName: memory
      restartPolicy: RestartContainer
    resources:
      requests:
        memory: "100Mi"
        cpu: "50m"
```

The change should flag `spec.restartPolicy: Never` but allow `Always` and `OnFailure` values and allow creating ephemeral containers.

File: pkg/apis/core/validation/validation_test.go (hunk 9 above)
Comment (thockin) [reply pkg/apis/core/validation/validation_test.go]: You can do it as a new PR or just as a commit on this PR before this commit

**Comment by thockin** [comment]
/retest
Thanks!

/lgtm
/approve

**Comment by vinaykul** [comment]
@killshotrevival thanks for the fix. The two new strict lint failures can be part of another no-net-functionality-change PR
cc: @Jeffwan 
/unhold
