### PR TITLE
Propagate errors from DSW to pod events

### LINKED ISSUE #79794: Block volume used as filesystem in a pod does not give clear error message
When a raw block PV is used as a filesystem one in a pod (i.e. in pod.spec.containers[x].volumeMounts), kubelet correctly won't start the pod, but it does not give user any information why.

In pod events I can't see anything useful:

```
Events:
  Type     Reason                  Age                    From                                                 Message
  ----     ------                  ----                   ----                                                 -------
  Normal   Scheduled               9m13s                  default-scheduler                                    Successfully assigned volumemode-206/security-context-d213f352-cd45-48ca-bb28-268a24ec75f8 to ip-10-0-160-149.us-east-2.compute.internal
  Warning  FailedAttachVolume      9m11s (x3 over 9m12s)  attachdetach-controller                              AttachVolume.Attach failed for volume "pvc-6efadcf1-9e57-11e9-bf6d-0a9ea8760cec" : "Error attaching EBS volume \"vol-007031b5e356a6786\"" to instance "i-0daef3d471605cebf" since volume is in "creating" state
  Normal   SuccessfulAttachVolume  9m5s                   attachdetach-controller                              AttachVolume.Attach succeeded for volume "pvc-6efadcf1-9e57-11e9-bf6d-0a9ea8760cec"
  Warning  FailedMount             24s (x4 over 7m10s)    kubelet, ip-10-0-160-149.us-east-2.compute.internal  Unable to mount volumes for pod "security-context-d213f352-cd45-48ca-bb28-268a24ec75f8_volumemode-206(70902de5-9e57-11e9-bf6d-0a9ea8760cec)": timeout expired waiting for volumes to attach or mount for pod "volumemode-206"/"security-context-d213f352-cd45-48ca-bb28-268a24ec75f8". list of unmounted volumes=[volume1]. list of unattached volumes=[volume1 default-token-h4xcm]
```

The pod is `ContainerCreating` forever. It should get `Failed` with a clear message.

In kubelet logs I can see:
```
desired_state_of_world_populator.go:296] Error processing volume "volume1" for pod "security-context-d213f352-cd45-48ca-bb28-268a24ec75f8_volumemode-206(70902de5-9e57-11e9-bf6d-0a9ea8760cec)": Volume "volume1" has volumeMode "Block", but is specified in volumeMounts for pod "volumemode-206"/"security-context-d213f352-cd45-48ca-bb28-268a24ec75f8"
```

/sig storage
/kind bug
/priority important-soon

### PR DESCRIPTION
**Pull request by jsafrane**
**What this PR does / why we need it**:
Goal: tell users that pod cannot run because:
 - PVC does not exist
 - PVC is not bound
 - PVC uses a different volumeMode than the pod expects.
 - ...

The first two bullets are checked also by scheduler, but kubelet should report errors here too, in case a pod runs with a different scheduler or was scheduled manually.

I added list of errors for each pod to DesiredStateOfWorld (DSW), where DSW populator (DSWP) stores them and kubelet picks them up via `WaitForAttachAndMount` and creates pod event(s) from them.

I did not want to add errors to `dsw.volumesToMount`, because that would create `volumesToMount` entries with incomplete / erroneous volumes (e.g. PVC was not bound yet and we don't know unique volume name).

I hope I got the cleaning right - DSWP periodically checks all stored errors and removes those for deleted pods.

I cleaned some error messages on the way, so the events are nice and tidy (well, at least they're better than before, see below).

Natural extension would be to report also mount / set up errors from reconciler ((not part of this PR). By placing the list of errors to DSW, there is no way to pass errors from unmount / teardown (there is no entry in DSW for pods that are being torn down).

**Examples** (simulating narrow terminal window):

* PVC does not exist:

  ```
  Type     Reason       Age   From                Message
  ----     ------       ----  ----                -------
  Warning  FailedMount  9s    kubelet, 127.0.0.1  Unable to attach or mount volumes:
  error processing PVC default/myclaim: failed to fetch PVC from API server:
  persistentvolumeclaims "myclaim" not found. List of unmounted volumes=[vol]. List 
  of unattached volumes=[vol default-token-4pt45].
  ```

* PVC is not bound:
  ```
  Type     Reason       Age   From                Message
  ----     ------       ----  ----                -------
  Warning  FailedMount  4s    kubelet, 127.0.0.1  Unable to attach or mount volumes:
  error processing PVC default/myclaim: PVC is not bound. List of unmounted volumes=
  [vol]. List of unattached volumes=[vol default-token-4pt45]. 
  ```

* Wrong mode:
  ```
  Type     Reason                  Age   From                     Message
  ----     ------                  ----  ----                     -------
  Normal   SuccessfulAttachVolume  4s    attachdetach-controller  AttachVolume.Attach 
  succeeded for volume "mypv"
  Warning  FailedMount             4s    kubelet, 127.0.0.1       Unable to attach or
  mount volumes: volume vol has volumeMode Filesystem, but is specified in 
  volumeDevices. List of unmounted volumes=[vol default-token-4pt45]. List of 
  unattached volumes=[vol default-token-4pt45].
  ```

* Multiple errors:
  ```
  Type     Reason       Age   From                Message
  ----     ------       ----  ----                -------
  Warning  FailedMount  1s    kubelet, 127.0.0.1  Unable to attach or mount volumes: 
  error processing PVC default/myclaim2: failed to fetch PVC from API server: 
  persistentvolumeclaims "myclaim2" not found; error processing PVC default/myclaim: 
  failed to fetch PVC from API server: persistentvolumeclaims "myclaim" not found. 
  List of unmounted volumes=[vol vol2 default-token-5jpm2]. List of unattached 
  volumes=[vol vol2 default-token-5jpm2].
  ```

I might send every error as a separate event. Would it be too many events? Does 
`List of unmounted volumes=[vol vol2 default-token-5jpm2]. List of unattached 
  volumes=[vol vol2 default-token-5jpm2].` have any value?

**Which issue(s) this PR fixes**:
Fixes #79794
 
**Does this PR introduce a user-facing change?**:

```release-note
Errors from pod volume set up are now propagated as pod events.
```

/kind bug
/sig storage

@msau42 @jingxu97 @gnufied, PTAL

@mkimuram, I am afraid that checking for events in #79796 is the best we can do here.

### CODE REVIEW

File: pkg/kubelet/volumemanager/volume_manager.go [hunk 1]
```diff
@@ -375,9 +376,10 @@ func (vm *volumeManager) WaitForAttachAndMount(pod *v1.Pod) error {
 		}
 
 		return fmt.Errorf(
-			"timeout expired waiting for volumes to attach or mount for pod %q/%q. list of unmounted volumes=%v. list of unattached volumes=%v",
+			"failed to attach or mount for pod %q/%q: %s. List of unmounted volumes=%v, list of unattached volumes=%v.",
 			pod.Namespace,
 			pod.Name,
+			err,
```
Comment (mkimuram) [inline pkg/kubelet/volumemanager/volume_manager.go]: For readability in multiple errors case, would it be better to output errors after lists of volumes?
(It might be too much to add "List of errors=" before errors, though.)

File: pkg/kubelet/volumemanager/volume_manager.go [hunk 2]
```diff
@@ -402,6 +402,9 @@ func (vm *volumeManager) getUnattachedVolumes(expectedVolumes []string) []string
 // volumes are mounted.
 func (vm *volumeManager) verifyVolumesMountedFunc(podName types.UniquePodName, expectedVolumes []string) wait.ConditionFunc {
 	return func() (done bool, err error) {
+		if errs := vm.desiredStateOfWorld.PopPodErrors(podName); len(errs) > 0 {
+			return true, errors.New(strings.Join(errs, "; "))
```
Comment (gnufied) [inline pkg/kubelet/volumemanager/volume_manager.go]: should it return false from here?

File: pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go [hunk 3]
```diff
@@ -309,11 +318,12 @@ func (dswp *desiredStateOfWorldPopulator) processPodVolumes(
 			uniquePodName, pod, volumeSpec, podVolume.Name, volumeGidValue)
 		if err != nil {
 			klog.Errorf(
-				"Failed to add volume %q (specName: %q) for pod %q to desiredStateOfWorld. err=%v",
+				"Failed to add volume %s (specName: %s) for pod %q to desiredStateOfWorld: %v",
 				podVolume.Name,
 				volumeSpec.Name(),
 				uniquePodName,
 				err)
+			dswp.desiredStateOfWorld.AddErrorToPod(uniquePodName, err.Error())
```
Comment (gnufied) [inline pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go]: If for some reason if these errors were transient and volume eventually did get added to DSOW.. should we remove the errors from pod if `allVolumesAdded` is true in lin#343?

File: pkg/kubelet/volumemanager/volume_manager.go (hunk 2 above)
Comment (jsafrane) [reply pkg/kubelet/volumemanager/volume_manager.go]: It does not really matter, `wait.Poll` will report error in both cases.

File: pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go (hunk 3 above)
Comment (jsafrane) [reply pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go]: Good idea, I remove errors if `allVolumesAdded`.

File: pkg/kubelet/volumemanager/volume_manager.go (hunk 1 above)
Comment (jsafrane) [reply pkg/kubelet/volumemanager/volume_manager.go]: Ack, I reordered the messages as you suggest:

```
Events:
  Type     Reason       Age   From                Message
  ----     ------       ----  ----                -------
  Warning  FailedMount  1s    kubelet, 127.0.0.1  Unable to attach or mount 
volumes: unmounted volumes=[vol], unattached volumes=[vol default-token-p67zc]: 
error processing PVC default/myclaim: failed to fetch PVC from API server: 
persistentvolumeclaims "myclaim" not found
```

**Comment by gnufied** [comment]
Looks good to me. but I want @jingxu97 to have a look as well.

/lgtm
/hold

**Comment by gnufied** [comment]
/hold cancel

Assigning to @derekwaynecarr for approval

/assign @derekwaynecarr

File: pkg/kubelet/volumemanager/volume_manager_test.go [hunk 4]
```diff
@@ -124,9 +125,16 @@ func TestInitialPendingVolumesForPodAndGetVolumesInUse(t *testing.T) {
 	// delayed claim binding
 	go delayClaimBecomesBound(kubeClient, claim.GetNamespace(), claim.ObjectMeta.Name)
 
-	err = manager.WaitForAttachAndMount(pod)
+	err = wait.Poll(100*time.Millisecond, 1*time.Second, func() (bool, error) {
```
Comment (jingxu97) [inline pkg/kubelet/volumemanager/volume_manager_test.go]: without this wait.Poll, the test should be flaky?

**Comment by jingxu97** [comment]
just one thing since the error might be transient, for example, PVC is not created whey pod is created. But then PVC is added to desired state, but fail to attach/mount for other reason. When user see the events, will it cause some confusion on what is the reason that pod fails to start?

File: pkg/kubelet/volumemanager/volume_manager_test.go (hunk 4 above)
Comment (jsafrane) [reply pkg/kubelet/volumemanager/volume_manager_test.go]: Yes, because the PVC is bound after a short delay (see above) and the first few calls return error that the PVC is not bound yet.

**Comment by jsafrane** [comment]
I thinks that regular volume operation errors are reported as events too, so user will see say "PVC does not exist" and "SetUp failed: volume not found" events and should know where is the pod stuck at.

**Comment by jsafrane** [comment]
/assign @derekwaynecarr @tallclair 
for approval on sig-node side (`verifyVolumesMountedFunc` changes a bit).

File: pkg/kubelet/volumemanager/cache/desired_state_of_world.go [hunk 5]
```diff
@@ -412,3 +430,36 @@ func (dsw *desiredStateOfWorld) isDeviceMountableVolume(volumeSpec *volume.Spec)
 
 	return false
 }
+
+func (dsw *desiredStateOfWorld) AddErrorToPod(podName types.UniquePodName, err string) {
```
Comment (derekwaynecarr) [inline pkg/kubelet/volumemanager/cache/desired_state_of_world.go]: how big can this get?  is it possible for this to grow unbounded ?

**Review by derekwaynecarr — COMMENTED** [review]
have a question, once clarified, this is good from my side.

File: pkg/kubelet/volumemanager/cache/desired_state_of_world.go (hunk 5 above)
Comment (jsafrane) [reply pkg/kubelet/volumemanager/cache/desired_state_of_world.go]: Good question, errors are stored in `sets.String`, so it *can* grow if every error has a different text. I added a limit of 10, just in case there is a bug in the populator.

**Comment by derekwaynecarr** [comment]
thanks for bounding the set.

/approve
/lgtm
