### PR TITLE
devicemanager: do not leak empty TopologyInfo to TopologyManager

### LINKED ISSUE #112234: TopologyManager fails a Pod with AffinityError
### What happened?

A node with:

```
$ sudo grep ^topolo /var/lib/kubelet/config.yaml
topologyManager: true
topologyManagerPolicy: single-numa-node 
```

fails a pod that uses device plugin resources (empty but non-nil `TopologyHints`) :

```
...
Sep 05 00:35:14 node kubelet[1468778]: I0905 00:35:14.935079 1468778 server.go:142] "Got registration request from device plugin with resource" resourceName="sgx.intel.com/enclave"
Sep 05 00:35:14 node kubelet[1468778]: I0905 00:35:14.935212 1468778 handler.go:94] "Registered client" name="sgx.intel.com/enclave"
Sep 05 00:35:14 node kubelet[1468778]: I0905 00:35:14.939947 1468778 client.go:86] "State pushed for device plugin" resource="sgx.intel.com/enclave" resourceCapacity=0
Sep 05 00:35:14 node kubelet[1468778]: I0905 00:35:14.945504 1468778 client.go:86] "State pushed for device plugin" resource="sgx.intel.com/enclave" resourceCapacity=1
Sep 05 00:35:15 node kubelet[1468778]: I0905 00:35:15.429131 1468778 setters.go:310] "Updated capacity for device plugin" plugin="sgx.intel.com/enclave" capacity=1
...
...
Sep 05 00:40:55 node kubelet[1468778]: I0905 00:40:55.907739 1468778 scope_container.go:77] "TopologyHints" hints=map[sgx.intel.com/enclave:[]] pod="default/intelsgx-demo-job-m2r56" containerName="intelsgx-demo-job-1"
Sep 05 00:40:55 node kubelet[1468778]: I0905 00:40:55.907929 1468778 policy.go:86] "Hint Provider has no possible NUMA affinities for resource" resource="sgx.intel.com/enclave"
```

Our device plugin sends the following registration:
```
I0905 00:35:14.939438 1474973 server.go:106] Sending to kubelet[&Device{ID:sgx-enclave-0,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{},},}]
```

So we send an empty `TopologyInfo` which is interpreted as "no possible NUMA affinities":
https://github.com/kubernetes/kubernetes/blob/bcea98234f0fdc5ce4e976758977eec72b13bfd4/pkg/kubelet/cm/topologymanager/policy.go#L85-L89

How is this different from `nil` value?
https://github.com/kubernetes/kubernetes/blob/bcea98234f0fdc5ce4e976758977eec72b13bfd4/pkg/kubelet/cm/topologymanager/policy.go#L79-L83

### What did you expect to happen?

I can workaround the problem by sending `TopologyInfo: nil` but it's not [well documented](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#device-plugin-integration-with-the-topology-manager) how this is supposed to work. Can the two if's combined or should we updated the documentation?

### How can we reproduce it (as minimally and precisely as possible)?

My environment: a single-node k8s cluster w/ device plugin that does

### Anything else we need to know?

The node needs to run two kinds of pods: those that need/use topology single-numa-node  and pods that just use a device plugin resources that does not provide topologyhints.

### Kubernetes version

<details>

```console
$ kubectl version
clientVersion:
  buildDate: "2022-08-23T17:44:59Z"
  compiler: gc
  gitCommit: a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2
  gitTreeState: clean
  gitVersion: v1.25.0
  goVersion: go1.19
  major: "1"
  minor: "25"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2022-08-23T17:38:15Z"
  compiler: gc
  gitCommit: a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2
  gitTreeState: clean
  gitVersion: v1.25.0
  goVersion: go1.19
  major: "1"
  minor: "25"
  platform: linux/amd64
```

</details>

### Cloud provider

<details>
N/A (kubeadm single node cluster)
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
5.15.0-47-generic

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
intel SGX device plugin v0.24
</details>

### PR DESCRIPTION
**Pull request by mythi**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Device Plugins that wish to leverage the Topology Manager can send back a populated TopologyInfo struct as part of the device registration, along with the device IDs and the health of the device. TopologyInfo is converted to TopologyHints and used by TopologyManager to find the optimal/desired resource allocation for a Pod.

If a plugin sends an empty but non-nil instance of TopologyInfo for a resource, devicemanager passes it on as an empty instance of TopologyHint which is currently interpreted as "Hint Provider has no possible NUMA affinities for resource" which further means that pods requesting that resource will fail.

To not block device resources that pass TopologyInfo{Nodes:[]*NUMANode{}} from being used, interprete that as nil set of hints and not a []TopologyHint{}.

#### Which issue(s) this PR fixes:

Fixes #112234 

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/cm/devicemanager/topology_hints_test.go [hunk 1]
```diff
@@ -1006,6 +1006,7 @@ func getCommonTestCases() []topologyHintTestCase {
 				"testdevice": {
 					{ID: "Dev1"},
 					{ID: "Dev2"},
+					{ID: "Dev3", Topology: &pluginapi.TopologyInfo{Nodes: []*pluginapi.NUMANode{}}},
```
Comment (klueska) [inline pkg/kubelet/cm/devicemanager/topology_hints_test.go:1009]: This should also work for the following.
```
{ID: "Dev4", Topology: &pluginapi.TopologyInfo{Nodes: nil}},
```
Can you add this as a 4th test device, please?

File: pkg/kubelet/cm/devicemanager/topology_hints_test.go [hunk 2]
```diff
@@ -102,7 +102,7 @@ func TestGetTopologyHints(t *testing.T) {
 				return tc.expectedHints[r][i].LessThan(tc.expectedHints[r][j])
 			})
 			if !reflect.DeepEqual(hints[r], tc.expectedHints[r]) {
-				t.Errorf("%v: Expected result to be %v, got %v", tc.description, tc.expectedHints[r], hints[r])
+				t.Errorf("%v: Expected result to be %#v, got %#v", tc.description, tc.expectedHints[r], hints[r])
```
Comment (klueska) [inline pkg/kubelet/cm/devicemanager/topology_hints_test.go:105]: Is there a reason for adding the `#` here? None of these types implement the `GoStringer` interface.

Comment (mythi) [reply pkg/kubelet/cm/devicemanager/topology_hints_test.go:105]: With this change I was able to get:
```
topology_hints_test.go:105: Single Request, no alignment: Expected result to be []topologymanager.TopologyHint(nil), got []topologymanager.TopologyHint{}
```

without it I get:
```
topology_hints_test.go:105: Single Request, no alignment: Expected result to be [], got []
```

Comment (klueska) [reply pkg/kubelet/cm/devicemanager/topology_hints_test.go:105]: I guess its just to have more verbose output include the struct fields, etc?

File: pkg/kubelet/cm/devicemanager/topology_hints_test.go (hunk 1 above)
Comment (mythi) [reply pkg/kubelet/cm/devicemanager/topology_hints_test.go:1009]: added.

**Comment by fromanirh** [comment]
LGTM
(sorry I'm late to the party)
I wonder if a followup docs PR detailing the expectations could help - meaning, is the website the right place to document these developer informations?

File: pkg/kubelet/cm/devicemanager/topology_hints_test.go (hunk 2 above)
Comment (mythi) [reply pkg/kubelet/cm/devicemanager/topology_hints_test.go:105]: that was the intention. without the modification it's impossible to say why the test failed when I added `Dev3` alone

**Comment by fromanirh** [comment]
> > I wonder if a followup docs PR detailing the expectations could help - meaning, is the website the right place to document these developer informations?
> 
> @fromanirh see [kubernetes/website#36769](https://github.com/kubernetes/website/pull/36769)

thanks, I guess this can be a good start
