### PR TITLE
Make writing version.txt more resilient

### LINKED ISSUE #98989: etcd migrator: versions.txt getting corrupted in case of lack of disk space
#### What happened:

1. etcd/version.txt file was found 'empty'. It blocked running etcd in a fail loop with

```
 failed to parse etcd '<version>/<storage-version>' string from version.txt file contents '': malformed version file, expected <major>.<minor>.<patch>/<storage> but got
goroutine 1 [running]:
```

Before this issue: Data disk (etcd) run out of space due to [tmp files leak in etcd](https://docs.google.com/document/d/1O2o1IApHWmSioXG3fez4eVlUHOrXICYGNVIzaqNS0IQ/edit?resourcekey=0-e6Iywgdkol0uiVBAaV1oww#bookmark=id.mhhwhipsg70u).

#### What you expected to happen:

1. versions.txt be not corrupted. It should be updated: 
  - only when needed (infrequently)
  - safely (rename swap or writing on pre-allocated space)

2. defensive migrator script that runs etcd in case of the file not being found.

#### How to reproduce it (as minimally and precisely as possible):

Use whole space of etcd data disk and restart migrator+etcd when concurrent process is disk hungry. 

#### Anything else we need to know?:

Requires changes of this logic: 

This logic (file write) should not trigger if the minor version matches: 

https://github.com/kubernetes/kubernetes/blob/97d40890d00acf721ecabb8c9a6fec3b3234b74b/cluster/images/etcd/migrate/migrator.go#L92

The write itself: 
https://github.com/kubernetes/kubernetes/blob/97d40890d00acf721ecabb8c9a6fec3b3234b74b/cluster/images/etcd/migrate/data_dir.go#L144
should be defensive: 
  - Please notice that [ioUtil.WriteFile](https://golang.org/src/io/ioutil/ioutil.go?s=2579:2647#L69) truncates file before writing

#### Environment:
- Kubernetes version: 1.18
- Cloud provider or hardware configuration: GCE

### PR DESCRIPTION
**Pull request by wpedrak**
Writing file first truncate it and writes later on. During disk space pressure it may cause file to become empty. To mitigate above, we create file with new version first and then move it in place of old one (to make sure that disk space is available)

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
We need it as we want to avoid etcd to crash-loop with below message
```
 failed to parse etcd '<version>/<storage-version>' string from version.txt file contents '': malformed version file, expected <major>.<minor>.<patch>/<storage> but got
goroutine 1 [running]:
```

#### Which issue(s) this PR fixes:
Fixes #98989

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cluster/images/etcd/migrate/data_dir.go [hunk 1]
```diff
@@ -142,8 +146,18 @@ func (v *VersionFile) Read() (*EtcdVersionPair, error) {
 
 // Write creates or overwrites the contents of the version.txt file with the given EtcdVersionPair.
 func (v *VersionFile) Write(vp *EtcdVersionPair) error {
-	data := []byte(fmt.Sprintf("%s/%s", vp.version, vp.storageVersion))
-	return ioutil.WriteFile(v.path, data, 0666)
+	pvp, err := v.Read()
+	if err != nil {
+		return fmt.Errorf("failed to read old version file %s: %v", v.path, err)
```
Comment (wojtek-t) [inline cluster/images/etcd/migrate/data_dir.go:151]: Is this correct? Don't we write the file for the first time via this path too?

Comment (wojtek-t) [reply cluster/images/etcd/migrate/data_dir.go:151]: I think we should split this PR into two:
- the actual bug fix (that always writes next-file and renames)
- the optimization to write it only if its different

Comment (wpedrak) [reply cluster/images/etcd/migrate/data_dir.go:151]: > Is this correct? Don't we write the file for the first time via this path too?

It is not. Thanks for catching.

> I think we should split this PR into two:
> - the actual bug fix (that always writes next-file and renames)
> - the optimization to write it only if its different

Split seems reasonable, will keep first part in this PR and I'll submit rest in other.

File: cluster/images/etcd/migrate/data_dir.go [hunk 2]
```diff
@@ -142,8 +146,11 @@ func (v *VersionFile) Read() (*EtcdVersionPair, error) {
 
 // Write creates or overwrites the contents of the version.txt file with the given EtcdVersionPair.
 func (v *VersionFile) Write(vp *EtcdVersionPair) error {
-	data := []byte(fmt.Sprintf("%s/%s", vp.version, vp.storageVersion))
-	return ioutil.WriteFile(v.path, data, 0666)
+	err := ioutil.WriteFile(v.nextPath(), []byte(vp.String()), 0666)
```
Comment (mm4tt) [inline cluster/images/etcd/migrate/data_dir.go:149]: I think it would be worth adding a comment here explaining why we're doing it this particular way rather than the more straightforward old way

Comment (wpedrak) [reply cluster/images/etcd/migrate/data_dir.go:152]: done
