### PR TITLE
Capture conformance Behaviors in walk.go

### LINKED ISSUE #88918: conformance.yaml capturing comments not intended for conformance data
**What happened**:

The conformance.yaml file captures comments not intended to be part of the "Description" section in the Description section.

For example: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/docker_containers.go#L66-L67 should not be captured, but is populated in the Description in the conformance.yaml https://github.com/kubernetes/kubernetes/blob/master/test/conformance/testdata/conformance.yaml#L107-L108

Even TODOs get bundled into our conformance descriptions: 

https://github.com/kubernetes/kubernetes/blob/master/test/conformance/testdata/conformance.yaml#L796

https://github.com/kubernetes/kubernetes/blob/master/test/conformance/testdata/conformance.yaml#L805

**What you expected to happen**:

Only comments part of Description should be in the Description field.

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know?**:

/cc @johnbelamaric

### PR DESCRIPTION
**Pull request by Jefftree**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Capture conformance behaviors if they are defined in the comments section of a test. I will add the behaviors <-> tests linkage in a follow up PR

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

The `conformance.yaml` change fixes https://github.com/kubernetes/kubernetes/issues/88918. We were logging comments not part of the Description in the Description section.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

/assign @johnbelamaric 
/priority important-soon

### CODE REVIEW

File: test/conformance/walk.go [hunk 1]
```diff
@@ -292,23 +294,40 @@ func commentToConformanceData(comment string) *conformanceData {
...
+			continue
+		}
+		if sline := regexp.MustCompile("^Behaviors\\s*:\\s*").Split(line, -1); len(sline) == 2 {
+			curLine = "Behaviors"
+			continue
+		}
+
+		// Line has no header
+		if curLine == "Behaviors" {
+			if sline := regexp.MustCompile("^-\\s").Split(line,-1); len(sline) == 2 {
```
Comment (oomichi) [inline test/conformance/walk.go]: need to update here as
```
-			if sline := regexp.MustCompile("^-\\s").Split(line,-1); len(sline) == 2 {
+			if sline := regexp.MustCompile("^-\\s").Split(line, -1); len(sline) == 2 {
```

File: test/conformance/walk_test.go [hunk 2]
```diff
@@ -158,7 +158,16 @@ func TestCommentToConformanceData(t *testing.T) {
...
+		}, {
+			desc:     "Behaviors are read",
+			input:    "Testname: behaviors\nBehaviors:\n- should behave\n- second behavior",
+			expected: &conformanceData{TestName: "behaviors", Behaviors: []string{"should behave", "second behavior"}},
+		}, {
+			desc:     "Multiple behaviors are parsed",
+			input:    "Testname: behaviors2\nBehaviors:\n- first behavior\n- second behavior",
+			expected: &conformanceData{TestName: "behaviors2", Behaviors: []string{"first behavior", "second behavior"}},
 		},
+
```
Comment (oomichi) [inline test/conformance/walk_test.go]: unnecessary blank which is checked with pull-kubernetes-verify job as
```
--- ./test/conformance/walk_test.go.orig	2020-03-03 19:39:16.533483748 +0000
+++ ./test/conformance/walk_test.go	2020-03-03 19:39:16.533483748 +0000
@@ -167,7 +167,6 @@
 			input:    "Testname: behaviors2\nBehaviors:\n- first behavior\n- second behavior",
 			expected: &conformanceData{TestName: "behaviors2", Behaviors: []string{"first behavior", "second behavior"}},
 		},
-
 	}
```

**Review by oomichi — COMMENTED** [review]
/cc @oomichi

File: test/conformance/testdata/conformance.yaml [hunk 3]
```diff
@@ -42,9 +42,8 @@
   codename: '[k8s.io] Container Runtime blackbox test on terminated container should
     report termination message [LinuxOnly] as empty when pod succeeds and TerminationMessagePolicy
     FallbackToLogsOnError is set [NodeConformance] [Conformance]'
-  description: 'Name: Container Runtime, TerminationMessage, from log output of succeeding
```
Comment (oomichi) [inline test/conformance/testdata/conformance.yaml]: This change seems fine according to the corresponding e2e test code as https://github.com/kubernetes/kubernetes/blob/f52cbea102bb6ba9fe951cbf81e7dd4b48f95d9e/test/e2e/common/runtime.go#L249
The old description contained `Name:` part also, then the description seemed odd. New one seems correct.

**Review by oomichi — COMMENTED** [review]
Thanks for fixing the issue.

/lgtm

File: test/conformance/testdata/conformance.yaml (hunk 3 above)
Comment (Jefftree) [reply test/conformance/testdata/conformance.yaml]: I submitted a follow up PR for this https://github.com/kubernetes/kubernetes/pull/88923.

Some conformance headers had "Name" instead of "Testname" and were picked up as part of the description by the tooling.
