### PR TITLE
e2e node: fix kubelet service restart failure

### LINKED ISSUE #93323: ci-kubernetes-node-kubelet-serial-hugepages panics when restarting kubelet
**Which jobs are flaking**:

ci-kubernetes-node-kubelet-serial-hugepages

**Which test(s) are flaking**:

all

**Testgrid link**:

https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet-serial-gce-e2e-hugepages

**Reason for failure**:

```
I0721 23:42:19.157] goroutine 234 [running]:
I0721 23:42:19.158] k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00012c001, 0xc000ad2000, 0x4c7, 0x5f5)
I0721 23:42:19.158] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:996 +0xb8
I0721 23:42:19.158] k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x8c0a180, 0xc000000003, 0x0, 0x0, 0xc000c969a0, 0x899f312, 0x9, 0xe2, 0x0)
I0721 23:42:19.158] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:945 +0x19d
I0721 23:42:19.159] k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x8c0a180, 0x3, 0x0, 0x0, 0x5205d89, 0x3b, 0xc000f35ec0, 0x2, 0x2)
I0721 23:42:19.159] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:733 +0x17b
I0721 23:42:19.159] k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
I0721 23:42:19.159] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1456
I0721 23:42:19.159] k8s.io/kubernetes/test/e2e_node/services.(*server).start.func1(0xc000103f20, 0xc000c41730, 0xc000103f80, 0xc000c24000)
I0721 23:42:19.160] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/services/server.go:226 +0xb83
I0721 23:42:19.160] created by k8s.io/kubernetes/test/e2e_node/services.(*server).start
I0721 23:42:19.160] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/services/server.go:120 +0x316
I0721 23:42:19.160] 
I0721 23:42:19.160] goroutine 1 [chan receive, 2 minutes]:
I0721 23:42:19.161] testing.(*T).Run(0xc00087b440, 0x50ea35b, 0xb, 0x52ee1e0, 0x4cf696)
I0721 23:42:19.161] 	/usr/local/go/src/testing/testing.go:1091 +0x399
I0721 23:42:19.161] testing.runTests.func1(0xc00087b320)
I0721 23:42:19.161] 	/usr/local/go/src/testing/testing.go:1334 +0x78
I0721 23:42:19.161] testing.tRunner(0xc00087b320, 0xc00140fdd0)
I0721 23:42:19.161] 	/usr/local/go/src/testing/testing.go:1039 +0xdc
I0721 23:42:19.161] testing.runTests(0xc000b44460, 0x8a3c850, 0x1, 0x1, 0x0)
I0721 23:42:19.162] 	/usr/local/go/src/testing/testing.go:1332 +0x2a7
I0721 23:42:19.162] testing.(*M).Run(0xc001283000, 0x0)
I0721 23:42:19.162] 	/usr/local/go/src/testing/testing.go:1249 +0x1b7
I0721 23:42:19.162] k8s.io/kubernetes/test/e2e_node.TestMain(0xc001283000)
I0721 23:42:19.162] 	_output/local/go/src/k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:113 +0x17d
I0721 23:42:19.162] main.main()
I0721 23:42:19.163] 	/tmp/go-build866716313/b001/_testmain.go:42 +0x135
I0721 23:42:19.163] 
I0721 23:42:19.163] goroutine 19 [chan receive]:
I0721 23:42:19.163] k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x8c0a180)
I0721 23:42:19.163] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1131 +0x8b
I0721 23:42:19.163] created by k8s.io/kubernetes/vendor/k8s.io/klog/v2.init.0
I0721 23:42:19.164] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:416 +0xd6
I0721 23:42:19.164] 
I0721 23:42:19.164] goroutine 182 [chan receive]:
I0721 23:42:19.164] k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc000a399c0)
I0721 23:42:19.164] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x3a5
I0721 23:42:19.165] created by k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/logutil.NewMergeLogger
I0721 23:42:19.165] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x80
I0721 23:42:19.165] 
I0721 23:42:19.165] goroutine 82 [select, 2 minutes]:
I0721 23:42:19.165] k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.(*worker).start(0xc00042d040)
I0721 23:42:19.165] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:154 +0x100
I0721 23:42:19.166] created by k8s.io/kubernetes/vendor/go.opencensus.io/stats/view.init.0
I0721 23:42:19.166] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.opencensus.io/stats/view/worker.go:32 +0x57
I0721 23:42:19.166] 
I0721 23:42:19.166] goroutine 54 [chan receive]:
I0721 23:42:19.166] k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc00090ff60)
I0721 23:42:19.167] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x3a5
I0721 23:42:19.167] created by k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/logutil.NewMergeLogger
I0721 23:42:19.167] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x80
I0721 23:42:19.167] 
I0721 23:42:19.167] goroutine 185 [chan receive]:
I0721 23:42:19.168] k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/logutil.(*MergeLogger).outputLoop(0xc000a39b60)
I0721 23:42:19.168] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:173 +0x3a5
I0721 23:42:19.168] created by k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/logutil.NewMergeLogger
I0721 23:42:19.169] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/go.etcd.io/etcd/pkg/logutil/merge_logger.go:91 +0x80
I0721 23:42:19.169] 
I0721 23:42:19.169] goroutine 198 [syscall, 2 minutes]:
I0721 23:42:19.169] os/signal.signal_recv(0x0)
I0721 23:42:19.169] 	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
I0721 23:42:19.169] os/signal.loop()
I0721 23:42:19.169] 	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
I0721 23:42:19.170] created by os/signal.Notify.func1
I0721 23:42:19.170] 	/usr/local/go/src/os/signal/signal.go:127 +0x44
I0721 23:42:19.170] 
I0721 23:42:19.170] goroutine 212 [select]:
I0721 23:42:19.170] k8s.io/kubernetes/vendor/github.com/onsi/gomega/internal/asyncassertion.(*AsyncAssertion).match(0xc0011c8a40, 0x5ef4cc0, 0x8c368f8, 0x77359401, 0x0, 0x0, 0x0, 0x989680)
I0721 23:42:19.171] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:146 +0x2e1
I0721 23:42:19.171] k8s.io/kubernetes/vendor/github.com/onsi/gomega/internal/asyncassertion.(*AsyncAssertion).Should(0xc0011c8a40, 0x5ef4cc0, 0x8c368f8, 0x0, 0x0, 0x0, 0x5e94e00)
I0721 23:42:19.171] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/gomega/internal/asyncassertion/async_assertion.go:51 +0x81
I0721 23:42:19.171] k8s.io/kubernetes/test/e2e_node.glob..func28.3.2()
I0721 23:42:19.172] 	_output/local/go/src/k8s.io/kubernetes/test/e2e_node/hugepages_test.go:294 +0x148
I0721 23:42:19.172] k8s.io/kubernetes/test/e2e_node.glob..func28.3.6()
I0721 23:42:19.172] 	_output/local/go/src/k8s.io/kubernetes/test/e2e_node/hugepages_test.go:357 +0x68
I0721 23:42:19.172] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).runSync(0xc0000b8c60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I0721 23:42:19.172] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113 +0xa3
I0721 23:42:19.173] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*runner).run(0xc0000b8c60, 0x70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I0721 23:42:19.173] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:64 +0xcf
I0721 23:42:19.173] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes.(*SetupNode).Run(0xc0008ad030, 0x5e83e40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
I0721 23:42:19.174] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/setup_nodes.go:15 +0x64
I0721 23:42:19.174] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample.func1(0xc001493578, 0xc00142cd20, 0x5e83e40, 0xc0002d3880)
I0721 23:42:19.174] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:168 +0x168
I0721 23:42:19.174] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).runSample(0xc00142cd20, 0x0, 0x5e83e40, 0xc0002d3880)
I0721 23:42:19.175] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:209 +0x5ac
I0721 23:42:19.175] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec.(*Spec).Run(0xc00142cd20, 0x5e83e40, 0xc0002d3880)
I0721 23:42:19.175] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/spec/spec.go:138 +0xf2
I0721 23:42:19.175] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpec(0xc001472000, 0xc00142cd20, 0x0)
I0721 23:42:19.176] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:200 +0x10f
I0721 23:42:19.176] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).runSpecs(0xc001472000, 0x1)
I0721 23:42:19.176] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:170 +0x120
I0721 23:42:19.176] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run(0xc001472000, 0xc000851758)
I0721 23:42:19.177] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:66 +0x117
I0721 23:42:19.177] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).Run(0xc0002bbc70, 0x7f378c069bc8, 0xc00087b440, 0x50f03cb, 0xd, 0xc000b444c0, 0x2, 0x2, 0x5f4e340, 0xc0002d3880, ...)
I0721 23:42:19.177] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:62 +0x42b
I0721 23:42:19.178] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo.RunSpecsWithCustomReporters(0x5e8a780, 0xc00087b440, 0x50f03cb, 0xd, 0xc000b444a0, 0x2, 0x2, 0x2)
I0721 23:42:19.178] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:226 +0x217
I0721 23:42:19.178] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo.RunSpecsWithDefaultAndCustomReporters(0x5e8a780, 0xc00087b440, 0x50f03cb, 0xd, 0xc0013d8930, 0x1, 0x1, 0x1)
I0721 23:42:19.179] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:214 +0xad
I0721 23:42:19.179] k8s.io/kubernetes/test/e2e_node.TestE2eNode(0xc00087b440)
I0721 23:42:19.179] 	_output/local/go/src/k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:170 +0x459
I0721 23:42:19.179] testing.tRunner(0xc00087b440, 0x52ee1e0)
I0721 23:42:19.179] 	/usr/local/go/src/testing/testing.go:1039 +0xdc
I0721 23:42:19.179] created by testing.(*T).Run
I0721 23:42:19.180] 	/usr/local/go/src/testing/testing.go:1090 +0x372
I0721 23:42:19.180] 
I0721 23:42:19.180] goroutine 213 [chan receive, 2 minutes]:
I0721 23:42:19.180] k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).registerForInterrupts(0xc001472000, 0xc0014587e0)
I0721 23:42:19.180] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:223 +0xce
I0721 23:42:19.181] created by k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner.(*SpecRunner).Run
I0721 23:42:19.181] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go:60 +0x86
I0721 23:42:19.181] 
I0721 23:42:19.181] goroutine 245 [IO wait, 2 minutes]:
I0721 23:42:19.181] internal/poll.runtime_pollWait(0x7f37b4fe3ed8, 0x72, 0xffffffffffffffff)
I0721 23:42:19.181] 	/usr/local/go/src/runtime/netpoll.go:203 +0x55
I0721 23:42:19.182] internal/poll.(*pollDesc).wait(0xc00086d318, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
I0721 23:42:19.182] 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
I0721 23:42:19.182] internal/poll.(*pollDesc).waitRead(...)
I0721 23:42:19.182] 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
I0721 23:42:19.182] internal/poll.(*FD).Read(0xc00086d300, 0xc0009a6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
I0721 23:42:19.182] 	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
I0721 23:42:19.183] net.(*netFD).Read(0xc00086d300, 0xc0009a6000, 0x1000, 0x1000, 0xc0002fb1a0, 0xc001356da8, 0xc001356c38)
I0721 23:42:19.183] 	/usr/local/go/src/net/fd_unix.go:202 +0x4f
I0721 23:42:19.183] net.(*conn).Read(0xc000b54058, 0xc0009a6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
I0721 23:42:19.183] 	/usr/local/go/src/net/net.go:184 +0x8e
I0721 23:42:19.183] net/http.(*persistConn).Read(0xc0006b2b40, 0xc0009a6000, 0x1000, 0x1000, 0xc001356eb0, 0x4688e0, 0xc001356eb0)
I0721 23:42:19.183] 	/usr/local/go/src/net/http/transport.go:1825 +0x75
I0721 23:42:19.183] bufio.(*Reader).fill(0xc000270660)
I0721 23:42:19.183] 	/usr/local/go/src/bufio/bufio.go:100 +0x103
I0721 23:42:19.184] bufio.(*Reader).Peek(0xc000270660, 0x1, 0x2, 0x0, 0x0, 0xc000c25300, 0x0)
I0721 23:42:19.184] 	/usr/local/go/src/bufio/bufio.go:138 +0x4f
I0721 23:42:19.184] net/http.(*persistConn).readLoop(0xc0006b2b40)
I0721 23:42:19.184] 	/usr/local/go/src/net/http/transport.go:1978 +0x1a8
I0721 23:42:19.184] created by net/http.(*Transport).dialConn
I0721 23:42:19.184] 	/usr/local/go/src/net/http/transport.go:1647 +0xc56
I0721 23:42:19.184] 
I0721 23:42:19.185] goroutine 264 [select]:
I0721 23:42:19.185] net/http.(*persistConn).writeLoop(0xc0009c46c0)
I0721 23:42:19.185] 	/usr/local/go/src/net/http/transport.go:2277 +0x11c
I0721 23:42:19.185] created by net/http.(*Transport).dialConn
I0721 23:42:19.185] 	/usr/local/go/src/net/http/transport.go:1648 +0xc7b
I0721 23:42:19.185] 
I0721 23:42:19.185] goroutine 244 [syscall, 2 minutes]:
I0721 23:42:19.186] syscall.Syscall6(0xf7, 0x1, 0x11d1, 0xc001355b60, 0x1000004, 0x0, 0x0, 0xae, 0x65, 0x0)
I0721 23:42:19.186] 	/usr/local/go/src/syscall/asm_linux_amd64.s:41 +0x5
I0721 23:42:19.186] os.(*Process).blockUntilWaitable(0xc001122420, 0xc0010ebe10, 0xc0013daf00, 0x65)
I0721 23:42:19.186] 	/usr/local/go/src/os/wait_waitid.go:31 +0x98
I0721 23:42:19.186] os.(*Process).wait(0xc001122420, 0x0, 0x0, 0xc000c969a0)
I0721 23:42:19.186] 	/usr/local/go/src/os/exec_unix.go:22 +0x39
I0721 23:42:19.186] os.(*Process).Wait(...)
I0721 23:42:19.187] 	/usr/local/go/src/os/exec.go:125
I0721 23:42:19.187] os/exec.(*Cmd).Wait(0xc000978160, 0x0, 0x0)
I0721 23:42:19.187] 	/usr/local/go/src/os/exec/exec.go:507 +0x60
I0721 23:42:19.187] k8s.io/kubernetes/test/e2e_node/services.(*server).start.func1(0xc000ad47e0, 0xc000c96930, 0x0, 0x0)
I0721 23:42:19.188] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/services/server.go:163 +0x136c
I0721 23:42:19.188] created by k8s.io/kubernetes/test/e2e_node/services.(*server).start
I0721 23:42:19.188] 	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/services/server.go:120 +0x316
I0721 23:42:19.188] 
I0721 23:42:19.188] goroutine 246 [select, 2 minutes]:
I0721 23:42:19.188] net/http.(*persistConn).writeLoop(0xc0006b2b40)
I0721 23:42:19.189] 	/usr/local/go/src/net/http/transport.go:2277 +0x11c
I0721 23:42:19.189] created by net/http.(*Transport).dialConn
I0721 23:42:19.189] 	/usr/local/go/src/net/http/transport.go:1648 +0xc7b
I0721 23:42:19.189] 
I0721 23:42:19.189] goroutine 263 [IO wait]:
I0721 23:42:19.189] internal/poll.runtime_pollWait(0x7f37b4fe4098, 0x72, 0xffffffffffffffff)
I0721 23:42:19.189] 	/usr/local/go/src/runtime/netpoll.go:203 +0x55
I0721 23:42:19.190] internal/poll.(*pollDesc).wait(0xc00137a598, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
I0721 23:42:19.190] 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
I0721 23:42:19.190] internal/poll.(*pollDesc).waitRead(...)
I0721 23:42:19.190] 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
I0721 23:42:19.190] internal/poll.(*FD).Read(0xc00137a580, 0xc0014e6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
I0721 23:42:19.190] 	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
I0721 23:42:19.190] net.(*netFD).Read(0xc00137a580, 0xc0014e6000, 0x1000, 0x1000, 0x43b1cc, 0xc00009db70, 0x467ff0)
I0721 23:42:19.191] 	/usr/local/go/src/net/fd_unix.go:202 +0x4f
I0721 23:42:19.191] net.(*conn).Read(0xc000788238, 0xc0014e6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
I0721 23:42:19.191] 	/usr/local/go/src/net/net.go:184 +0x8e
I0721 23:42:19.191] net/http.(*persistConn).Read(0xc0009c46c0, 0xc0014e6000, 0x1000, 0x1000, 0xc000c254a0, 0xc00009dc70, 0x4086d5)
I0721 23:42:19.191] 	/usr/local/go/src/net/http/transport.go:1825 +0x75
I0721 23:42:19.191] bufio.(*Reader).fill(0xc000296de0)
I0721 23:42:19.191] 	/usr/local/go/src/bufio/bufio.go:100 +0x103
I0721 23:42:19.192] bufio.(*Reader).Peek(0xc000296de0, 0x1, 0x0, 0x0, 0x1, 0xc0010ad900, 0x0)
I0721 23:42:19.192] 	/usr/local/go/src/bufio/bufio.go:138 +0x4f
I0721 23:42:19.192] net/http.(*persistConn).readLoop(0xc0009c46c0)
I0721 23:42:19.192] 	/usr/local/go/src/net/http/transport.go:1978 +0x1a8
I0721 23:42:19.192] created by net/http.(*Transport).dialConn
I0721 23:42:19.192] 	/usr/local/go/src/net/http/transport.go:1647 +0xc56
I0721 23:42:19.192] 
I0721 23:42:19.192] goroutine 250 [IO wait, 2 minutes]:
I0721 23:42:19.193] internal/poll.runtime_pollWait(0x7f37b4fe3fb8, 0x72, 0xffffffffffffffff)
I0721 23:42:19.193] 	/usr/local/go/src/runtime/netpoll.go:203 +0x55
I0721 23:42:19.193] internal/poll.(*pollDesc).wait(0xc000a82a18, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
I0721 23:42:19.193] 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
I0721 23:42:19.193] internal/poll.(*pollDesc).waitRead(...)
I0721 23:42:19.193] 	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
I0721 23:42:19.194] internal/poll.(*FD).Read(0xc000a82a00, 0xc000ee1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
I0721 23:42:19.194] 	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
I0721 23:42:19.194] net.(*netFD).Read(0xc000a82a00, 0xc000ee1000, 0x1000, 0x1000, 0x43b1cc, 0xc001358b70, 0x467ff0)
I0721 23:42:19.194] 	/usr/local/go/src/net/fd_unix.go:202 +0x4f
I0721 23:42:19.194] net.(*conn).Read(0xc000b54868, 0xc000ee1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
I0721 23:42:19.194] 	/usr/local/go/src/net/net.go:184 +0x8e
I0721 23:42:19.195] net/http.(*persistConn).Read(0xc00087a5a0, 0xc000ee1000, 0x1000, 0x1000, 0xc000ef6720, 0xc001358c70, 0x4086d5)
I0721 23:42:19.195] 	/usr/local/go/src/net/http/transport.go:1825 +0x75
I0721 23:42:19.195] bufio.(*Reader).fill(0xc0000b9da0)
I0721 23:42:19.195] 	/usr/local/go/src/bufio/bufio.go:100 +0x103
I0721 23:42:19.195] bufio.(*Reader).Peek(0xc0000b9da0, 0x1, 0x0, 0x0, 0x1, 0xc000ef6600, 0x0)
I0721 23:42:19.195] 	/usr/local/go/src/bufio/bufio.go:138 +0x4f
I0721 23:42:19.195] net/http.(*persistConn).readLoop(0xc00087a5a0)
I0721 23:42:19.195] 	/usr/local/go/src/net/http/transport.go:1978 +0x1a8
I0721 23:42:19.196] created by net/http.(*Transport).dialConn
I0721 23:42:19.196] 	/usr/local/go/src/net/http/transport.go:1647 +0xc56
I0721 23:42:19.196] 
I0721 23:42:19.196] goroutine 251 [select, 2 minutes]:
I0721 23:42:19.196] net/http.(*persistConn).writeLoop(0xc00087a5a0)
I0721 23:42:19.196] 	/usr/local/go/src/net/http/transport.go:2277 +0x11c
I0721 23:42:19.196] created by net/http.(*Transport).dialConn
I0721 23:42:19.197] 	/usr/local/go/src/net/http/transport.go:1648 +0xc7b
```

### PR DESCRIPTION
**Pull request by cynepco3hahue**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation

/kind failing-test

> /kind feature
> /kind flake

**What this PR does / why we need it**:

Under e2e tests possible the situation when we restart the kubelet
number of times in the short time frame. When it happens the systemd
can fail the service restart with the `Failed with result 'start-limit-hit'.`
error.

To avoid this situation the code will reset the kubelet service start failures
on each call to the kubelet restart command.

**Which issue(s) this PR fixes**:

Fixes #93323

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Review by alejandrox1 — COMMENTED** [review]
Thank you for working on this catching this issue @cynepco3hahue !
/approve
/hold
for more sig node reviews

/cc @kubernetes/sig-node-test-failures

**Comment by alejandrox1** [comment]
/test pull-kubernetes-verify
wanna see if thats a flake

**Comment by cynepco3hahue** [comment]
@alejandrox1 Can we cancel the hold?

File: test/e2e_node/util.go [hunk 1]
```diff
@@ -387,7 +387,11 @@ func findRunningKubletServiceName() string {
 
 func restartKubelet() {
 	kubeletServiceName := findRunningKubletServiceName()
-	stdout, err := exec.Command("sudo", "systemctl", "restart", kubeletServiceName).CombinedOutput()
+	// reset the kubelet service start-limit-hit
+	stdout, err := exec.Command("sudo", "systemctl", "reset-failed", kubeletServiceName).CombinedOutput()
+	framework.ExpectNoError(err, "Failed to restart kubelet with systemctl: %v, %v", err, stdout)
```
Comment (odinuge) [inline test/e2e_node/util.go:392]: Maybe update the comment so it isn't equal to the one below, so debugging becomes easier?

Otherwise this i think er can get this merged! Thanks for catching!

Comment (cynepco3hahue) [reply test/e2e_node/util.go]: nice catch, done

**Review by odinuge — APPROVED** [review]
/lgtm
/hold cancel

Still need someone from release mgmt. to add this to 1.19 milestone if it should be merged before code thaw.

**Comment by alejandrox1** [comment]
and a quick heads up, it may take a bit for this to merge.
The 1.19 release delayed code thaw (thats when prs can merge into the master branch) https://groups.google.com/forum/#!topic/kubernetes-sig-release/FXlkBHexcfQ
But as soon as code thaw is back in place the ci bot will merge this
