### PR TITLE
Provide Flex volume metrics if the plugin supports.

### LINKED ISSUE #67400: Enable Flex Volume Drivers to support metrics
kind feature

**What happened**:
Currently there is no mechanism to report metrics as the flex plugins are not enabled to collect metrics. All flex volumes lack this feature as compared to in-tree/built-in drivers even though it is possible to collect such metrics for most of the plugins.

**What you expected to happen**:
Depending on the availability of the metrics from the mounted FS, flex plugins should allow to report metrics for the FS.

**How to reproduce it (as minimally and precisely as possible)**:
The default behavior that can be proved easily by just running a command similar to the following command on a node that is running a flex volume. This will show that there are no metrics collected for flex volumes.
kubectl proxy  
$curl 127.0.0.1:8001/api/v1/nodes/<IP>/proxy/stats/summary**

**Environment**:
- Kubernetes version (use `kubectl version`): 1.12
- Cloud provider or hardware configuration: local x86
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux KubeStorage 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
- Others:
/sig storage

### PR DESCRIPTION
**Pull request by brahmaroutu**
**What this PR does / why we need it**:
This PR enables metrics for Flex Drivers if the driver has the capability. By default metrics are not enabled on the driver but when the capability 'supportsMetrics' is set to true then this PR will allow to configure a fs stat metrics plugin to run metrics on the flex plugin.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #67400

**Special notes for your reviewer**:

**Release note**:

```release-note
Flex drivers by default do not produce metrics. Flex plugins can enable metrics collection by setting  the capability 'supportsMetrics' to true. Make sure the file system can support fs stat to produce metrics in this case.
```

### CODE REVIEW

File: pkg/volume/flexvolume/plugin.go [hunk 1]
```diff
@@ -177,6 +177,14 @@ func (plugin *flexVolumePlugin) newMounterInternal(spec *volume.Spec, pod *api.P
 		return nil, err
 	}
 
+	var metricsProvider volume.MetricsProvider
+	if plugin.capabilities.SupportsMetrics {
```
Comment (gnufied) [inline pkg/volume/flexvolume/plugin.go]: Is this accurate? Since flex is also used for ephemeral storage, any plugin that says it supports is going to default to statfs based implementation. The problem with that is - for ephemeral storage, the storage space could be shared with the host and hence statsfs likely will not return accurate information. Same as CSI, I am afraid this information has to come from plugin itself.

In fact - this is perhaps more applicable to flex than CSI because there are quite a bit of flex plugins that are used for ephemeral data/tokens etc.

Comment (gnufied) [reply pkg/volume/flexvolume/plugin.go]: cc @chakri-nelluri

Comment (chakri-nelluri) [reply pkg/volume/flexvolume/plugin.go]: @gnufied If the plugins like ephemeral storage cannot support, can we assume they won't return true for SupportsMetrics? With that assumption, the change LGTM.

Comment (chakri-nelluri) [reply pkg/volume/flexvolume/plugin.go]: We can extend this call to Flex driver, but given we are planning to phase out flex in favor of CSI, I would hold off extending it unless there is a real push asking for it.

Comment (gnufied) [reply pkg/volume/flexvolume/plugin.go]: okay, lets get this shipped. Does not sound like a blocker.

**Comment by gnufied** [comment]
I am just going to place temporary hold on the PR so as @chakri-nelluri has a chance to do a final review as  well. 

/hold

**Comment by chakri-nelluri** [comment]
Thanks @gnufied.
/LGTM

**Comment by brahmaroutu** [comment]
@saad-ali @gnufied can we please prioritize to merge this PR along with tests under 68018. I believe Milestone is not set.

**Comment by chakri-nelluri** [comment]
@saad-ali @msau42 Please set the milestone to 1.12.

**Comment by saad-ali** [comment]
> @saad-ali @msau42 Please set the milestone to 1.12.

Too late for 1.12. Past code freeze. Can consider for 1.13
