### PR TITLE
fix node notReady in first sync period after kubelet restart

### LINKED ISSUE #124397: After restart Kubelet, node will become notReady in first kubelet update period.
### What happened?

After restart Kubelet, node will become notReady in first kubelet update period.

node condition is :
```
  - lastHeartbeatTime: "2024-04-19T06:40:55Z"
    lastTransitionTime: "2024-04-19T06:40:55Z"
    message: container runtime status check may not have completed yet
    reason: KubeletNotReady
    status: "False"
    type: Ready
```

in kubelet's logs:
```
I0419 14:40:55.510166 1902465 setters.go:577] "Node became not ready" node="mjq-k8stestarsenalwork-1" condition={Type:Ready Status:False LastHeartbeatTime:2024-04-19 14:40:55.510127183 +0800 CST m=+5.226928586 LastTransitionTime:2024-04-19 14:40:55.510127183 +0800 CST m=+5.226928586 Reason:KubeletNotReady Message:container runtime status check may not have completed yet}
```

when go in to next period (default 10s), node status resume to Ready.

### What did you expect to happen?

Restart Kubelet should not make node status change to notReady.

### How can we reproduce it (as minimally and precisely as possible)?

Restart Kubelet, and watch node status for second
```
watch -n 1 'kubectl get no <node-name>'
```

### Anything else we need to know?

The root case maybe here:
When kubelet start, it will start two go routine, one detect runtime status, one check node status and update to APIServer;
detect runtime status:

in `updateRuntimeUp` it will update `lastBaseRuntimeSync`:
https://github.com/kubernetes/kubernetes/blob/bf07ef3950d80256cb366b035712b6d60b8a3f4c/pkg/kubelet/kubelet.go#L2909

in `kl.runtimeState.runtimeErrors` it will check runtimeStatus include `lastBaseRuntimeSync`:

https://github.com/kubernetes/kubernetes/blob/bf07ef3950d80256cb366b035712b6d60b8a3f4c/pkg/kubelet/runtime.go#L108

`kl.runtimeState.runtimeErrors` is one of the notReady setter func:
https://github.com/kubernetes/kubernetes/blob/bf07ef3950d80256cb366b035712b6d60b8a3f4c/pkg/kubelet/kubelet_node_status.go#L748

So if nodestatus execute before `updateRuntimeUp`, kubelet will update a node status with notReady condition:
https://github.com/kubernetes/kubernetes/blob/bf07ef3950d80256cb366b035712b6d60b8a3f4c/pkg/kubelet/kubelet.go#L1635-L1641
In kubelet starting,  both `syncNodeStatus` go routine and `fastStatusUpdateOnce` will be called before `updateRuntimeUp`,  so the first node status is notReady.

### Kubernetes version

In our cluster is v1.22.17, but I belive it can reproduce in latest version.

<details>

```console
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:47:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:42:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console

# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by AllenXu93**
fix nodeNotReady once after kubelet restart: execute updateRuntimeUp before syncNodeStatus

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When kubelet start, it will execute `kl.syncNodeStatus` to sync node status to APIServer, and one of the check is checking containerRuntime state.
But containerRuntime state update execute after `kl.syncNodeStatus`
https://github.com/kubernetes/kubernetes/blob/bf07ef3950d80256cb366b035712b6d60b8a3f4c/pkg/kubelet/kubelet.go#L1625-L1641

This PR will execute `kl.updateRuntimeUp()` before `kl.syncNodeStatus` .

#### Which issue(s) this PR fixes:

Fixes #124397

#### Does this PR introduce a user-facing change?

```release-note
Fix node report notReady with reason 'container runtime status check may not have completed yet' after Kubelet restart
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -1636,9 +1636,14 @@ func (kl *Kubelet) Run(updates <-chan kubetypes.PodUpdate) {
 		// Introduce some small jittering to ensure that over time the requests won't start
 		// accumulating at approximately the same time from the set of nodes due to priority and
 		// fairness effect.
-		go wait.JitterUntil(kl.syncNodeStatus, kl.nodeStatusUpdateFrequency, 0.04, true, wait.NeverStop)
+		go func() {
+			kl.updateRuntimeUp()
```
Comment (HirazawaUi) [inline pkg/kubelet/kubelet.go:1640]: Add a comment explaining why we need to execute `kl.updateRuntimeUp()` once.

**Comment by HirazawaUi** [comment]
Please provide a release-note for it as this is a user-facing change.

**Comment by aojea** [comment]
What do you think about using this approach instead https://github.com/kubernetes/kubernetes/issues/124397#issuecomment-2071700205 ?

File: pkg/kubelet/kubelet.go [hunk 2]
```diff
@@ -1636,7 +1636,13 @@ func (kl *Kubelet) Run(updates <-chan kubetypes.PodUpdate) {
...
 		// fairness effect.
-		go wait.JitterUntil(kl.syncNodeStatus, kl.nodeStatusUpdateFrequency, 0.04, true, wait.NeverStop)
+		go func() {
+			// Call updateRuntimeUp once before syncNodeStatus to make sure kubelet had already checked runtime state
+			// otherwise when restart kubelet, syncNodeStatus will report node notReady in first report period
+			kl.updateRuntimeUp()
+			wait.JitterUntil(kl.syncNodeStatus, kl.nodeStatusUpdateFrequency, 0.04, true, wait.NeverStop)
+		}()
+
 		go kl.fastStatusUpdateOnce()
```
Comment (aojea) [inline pkg/kubelet/kubelet.go:1646]: since we are doing this I prefer to put the goroutines in the right order https://github.com/kubernetes/kubernetes/issues/124397#issuecomment-2071700205

Comment (bart0sh) [reply pkg/kubelet/kubelet.go:1646]: @AllenXu93 please address above comment, thanks.

Comment (HirazawaUi) [reply pkg/kubelet/kubelet.go:1646]: There has been a lot of discussion on this issue in #124397, @aojea do you think the current behavior is reasonable or do we need to discuss it further?

Comment (aojea) [reply pkg/kubelet/kubelet.go:1646]: I'm fine with current solution and agree with the points expressed there, blocking on the updateRuntimeUp operation is the only safe way ... thanks for correct me

**Comment by aojea** [comment]
/lgtm
/assign @dchen1107 

Dawn this will improve the p99 percentiles on node startup as it seems there is a race that can postpone the node readiness by 10 seconds

> when go in to next period (default 10s), node status resume to Ready.

**Comment by dchen1107** [comment]
@aojea thanks for pointing out the overall improvement on the node startup latency even the original issue shouldn't cause any other disruption to the running workloads if there is any. cc/ @yujuhong @bobbypage for vis. 

/lgtm
/approve

**Comment by pacoxu** [comment]
/milestone v1.31
-  approved just before code freeze
