### PR TITLE
Fix GCE PD dynamic provisioning 1.9 upgrade test failure

### LINKED ISSUE #60766: [test failed] [1.10 upgrade]  Dynamic Provisioning DynamicProvisioner
the tests are failing in http://k8s-testgrid.appspot.com/sig-release-master-upgrade#gce-1.9-master-upgrade-master

/sig sig-storage
/priority failing-test
/priority critical-urgent
/kind bug
/status approved-for-milestone
/milestone v1.10

cc @jdumars @jberkus
/assign @saad-ali @childsb

### PR DESCRIPTION
**Pull request by verult**
**What this PR does / why we need it**: Fixes storage unit discrepancy between actual size and expected size for GCE PD dynamic provisioning tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #60766 

/sig storage
/assign @gnufied @jingxu97 
/cc @mbohlool 

Placing hold as 1.9 branch is currently frozen
/hold

### CODE REVIEW

File: test/e2e/storage/volume_provisioning.go [hunk 1]
```diff
@@ -640,6 +640,14 @@ var _ = SIGDescribe("Dynamic Provisioning", func() {
 				claimSize:    "2Gi",
 				expectedSize: "2Gi",
 			}
+			// gce or gke
+			if getDefaultPluginName() == "kubernetes.io/gce-pd" {
+				// using GB not GiB as e2e test unit since gce-pd returns GB,
+				// or expectedSize may be greater than claimSize.
+				test.claimSize = "2G"
+				test.expectedSize = "2G"
+			}
```
Comment (gnufied) [inline test/e2e/storage/volume_provisioning.go]: Does this matter - as long claimSize is greater than expected size? So when requesting 2Gi, I would assume we would allocated 3GB on GCE.

Comment (verult) [reply test/e2e/storage/volume_provisioning.go]: Then expected size has to be set to "3G", right? IMO the current approach is cleaner, and it matches the 1.10 version of the test

**Comment by verult** [comment]
Known test failure: https://github.com/kubernetes/kubernetes/issues/60870
/retest

**Comment by jberkus** [comment]
@saad-ali, @childsb we need one of you to approve this for the SIG.

**Comment by saad-ali** [comment]
Approved from sig-storage. Will leave it to @mbohlool to merge

**Comment by krzyzacy** [comment]
this probably need to wait till 1.9 build job to finish - https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-build-stable1/1484

**Comment by liggitt** [comment]
kubemark is green since #60940 merged
