### PR TITLE
Fix node label assignment for GCE k8s clusters.

### LINKED ISSUE #68372: Failing testsuite gce-device-plugin-gpu-1.11
This testsuite is failing or very flaky and blocking 1.11.3. 
Can someone triage the issue?

@yguo0905 @mindprince 
https://k8s-testgrid.appspot.com/sig-release-1.11-blocking#gce-device-plugin-gpu-1.11

### PR DESCRIPTION
**Pull request by vishh**
1. Do not set Accelerator Node labels on master node in GCE k8s clusters

2. Do not set Preemptible node label on master node unless the master node is explicitly set to be preemptible.

Fixes #68372

### CODE REVIEW

File: cluster/gce/config-default.sh [hunk 1]
```diff
@@ -177,6 +174,12 @@ HEAPSTER_MACHINE_TYPE="${HEAPSTER_MACHINE_TYPE:-}"
 # NON_MASTER_NODE_LABELS are labels will only be applied on non-master nodes.
 NON_MASTER_NODE_LABELS="${KUBE_NON_MASTER_NODE_LABELS:-}"
 
+if [[ "${PREEMPTIBLE_MASTER}" == "true" ]]; then
+    NODE_LABELS="${NODE_LABELS},cloud.google.com/gke-preemptible=true"
+elif [[ "${PREEMPTIBLE_NODE}" == "true" ]]; then
```
Comment (mindprince) [inline cluster/gce/config-default.sh]: The logic here seems to imply that preemptible master means that nodes are also preemptible. Is that correct? Otherwise, we need to handle the case where the master is preemptible but nodes are not (Though I don't know why would someone have such a setup).

**Review by rohitagarwal003 — APPROVED** [review]
/lgtm

File: cluster/gce/config-default.sh (hunk 1 above)
Comment (vishh) [reply cluster/gce/config-default.sh]: There is no master only node label variable and I'd like to avoid defining a new variable for such a corner case.

Comment (jiayingz) [reply cluster/gce/config-default.sh]: nit: perhaps add a comment here that we don't support PREEMPTIBLE_MASTER=true && PREEMPTIBLE_NODE=false settings here?

**Review by jiayingz — COMMENTED** [review]
/lgtm

**Comment by krzyzacy** [comment]
/priority critical-urgent
/milestone 1.12

/assign @tpepper 
let you to unhold
/hold

**Comment by BenTheElder** [comment]
[that passed but since nobody is in a rush at the moment, let's run again to confirm]
/test pull-kubernetes-e2e-gce-device-plugin-gpu

**Comment by jiayingz** [comment]
@vishh Do you want to cherry-pick this PR to 1.11 branch? Some recent 1.11 gpu test failures may be due to the same problem we saw before.

**Comment by vishh** [comment]
Sure - https://github.com/kubernetes/kubernetes/pull/69164

>
