### PR TITLE
Set the systemUUID for windows nodes

### LINKED ISSUE #75978: systemUUID is not set on Windows
**What happened**:
The windows kubelet does not set .status.nodeInfo.systemUUID on the node object. 

**What you expected to happen**:
The windows kubelet sets the systemUUID from `wmic csproduct get UUID`

**How to reproduce it (as minimally and precisely as possible)**:
Start the windows kubelet and check for UUID: 
```
kubectl get nodes -o json | jq '.items[]|[.metadata.name, .status.nodeInfo.systemUUID]'
```
**Anything else we need to know?**:
This will affect users running the out-of-tree vsphere CCM since that depends on the systemUUID, unlike the in-tree version. 

Also, looks like cAdvisor is the component responsible for providing the systemUUID so let me know if this issue needs to be moved to that repo.

**Environment**:
- Kubernetes version (use `kubectl version`):
Verified on 1.13.1 and 1.14
- Cloud provider or hardware configuration:
None
- OS (e.g: `cat /etc/os-release`):
Windows Server 2019

### PR DESCRIPTION
**Pull request by liyanhui1228**
**What type of PR is this?**

> /kind bug

**Which issue(s) this PR fixes**:

Fixes #75978

```release-note
NONE
```

### CODE REVIEW

File: pkg/kubelet/winstats/winstats.go [hunk 1]
```diff
@@ -103,9 +105,24 @@ func (c *StatsClient) WinContainerInfos() (map[string]cadvisorapiv2.ContainerInf
...
+// in here if it isn't provided by cadvisor.
 func (c *StatsClient) WinMachineInfo() (*cadvisorapi.MachineInfo, error) {
-	return c.client.getMachineInfo()
+	infos, err := c.client.getMachineInfo()
+	if err != nil {
+		return nil, err
+	}
+
+	if infos.SystemUUID == "" {
+		cmd := exec.Command("powershell.exe", "-Command", "(Get-CimInstance -Class Win32_ComputerSystemProduct).UUID")
```
Comment (yujuhong) [inline pkg/kubelet/winstats/winstats.go]: @PatrickLang @benmoss does this look okay to you?

File: pkg/kubelet/winstats/winstats.go [hunk 2]
```diff
@@ -103,9 +105,24 @@ func (c *StatsClient) WinContainerInfos() (map[string]cadvisorapiv2.ContainerInf
 }
 
 // WinMachineInfo returns a cadvisorapi.MachineInfo with details about the
-// node machine. Analogous to cadvisor MachineInfo method.
+// node machine. Run the powershell command to get the SystemUUID for Windows node
+// in here if it isn't provided by cadvisor.
 func (c *StatsClient) WinMachineInfo() (*cadvisorapi.MachineInfo, error) {
-	return c.client.getMachineInfo()
+	infos, err := c.client.getMachineInfo()
```
Comment (yujuhong) [inline pkg/kubelet/winstats/winstats.go]: Should the code be added `getMachineInfo` instead?

File: pkg/kubelet/winstats/winstats.go [hunk 3]
```diff
@@ -103,9 +105,24 @@ func (c *StatsClient) WinContainerInfos() (map[string]cadvisorapiv2.ContainerInf
...
+	if err != nil {
+		return nil, err
+	}
+
+	if infos.SystemUUID == "" {
```
Comment (yujuhong) [inline pkg/kubelet/winstats/winstats.go]: System UUID shoudln't change throughout the the lifetime of kubelet. Running in once and just return the in-memory copy should be sufficient.

In fact, I think this (fields not changing) applies to most of fields in MachineInfo too.  + @dashpole to confirm the whether that's the case :-)

File: pkg/kubelet/winstats/winstats.go (hunk 2 above)
Comment (dashpole) [reply pkg/kubelet/winstats/winstats.go]: +1 to adding it to getMachineInfo()

File: pkg/kubelet/winstats/winstats.go (hunk 3 above)
Comment (dashpole) [reply pkg/kubelet/winstats/winstats.go]: I believe the kubelet actually does caching _on top of_ what is returned by the stats library.  https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_getters.go#L357.  I think the library should fetch the whole thing on each call.

Comment (yujuhong) [reply pkg/kubelet/winstats/winstats.go]: You're right. I forgot that it's kubelet that cached this. Thanks!

File: pkg/kubelet/winstats/winstats.go (hunk 1 above)
Comment (benmoss) [reply pkg/kubelet/winstats/winstats.go]: With the in-tree vSphere cloud provider we had to switch from using `wmic csproduct get UUID` to `wmic bios get serialnumber`, since the former wasn't reflecting the value set by vSphere correctly. I'm not sure if this .NET function is the same as the `wmic` call, but I am getting it would be.

https://github.com/kubernetes/kubernetes/pull/74919

File: pkg/kubelet/winstats/winstats.go (hunk 2 above)
Comment (liyanhui1228) [reply pkg/kubelet/winstats/winstats.go]: Done.

File: pkg/kubelet/winstats/winstats.go (hunk 1 above)
Comment (liyanhui1228) [reply pkg/kubelet/winstats/winstats.go]: @benmoss Thanks for the information! I tried running the two commands on my windows vm and actually they are returning different result:
```
PS C:\windows\system32> (Get-CimInstance -Class Win32_ComputerSystemProduct).UUID
E6C8AC43-582B-3575-4E1F-6DA170888906

PS C:\windows\system32> wmic csproduct get UUID
UUID
E6C8AC43-582B-3575-4E1F-6DA170888906

PS C:\windows\system32> wmic bios get serialnumber
SerialNumber
GoogleCloud-43ACC8E62B5875354E1F6DA170888906
```
It looks like the first one is more closer to what we want in here. I'm also fine with using the `serialnumber` if that makes more sense. Any suggestions?

Comment (benmoss) [reply pkg/kubelet/winstats/winstats.go]: I think looking at this again we want to stick to UUID, I think the cloud providers can override this value if they need to

Comment (liyanhui1228) [reply pkg/kubelet/winstats/winstats.go]: Thanks Ben!

Comment (yujuhong) [reply pkg/kubelet/winstats/winstats.go]: It's not that big of deal since we only run this once during kubelet's lifetime, but running `wmic csproduct get UUID` directly probably slightly faster than calling out to `powershell.exec`.

Comment (liyanhui1228) [reply pkg/kubelet/winstats/winstats.go]: Good suggestion! Done.

**Comment by yujuhong** [comment]
Nice!
/lgtm
Will approve tomorrow if no one objects

File: pkg/kubelet/winstats/winstats.go (hunk 1 above)
Comment (rhockenbury) [reply pkg/kubelet/winstats/winstats.go]: `wmic csproduct get UUID` should be correct with regards to the vsphere provider. The in-tree vSphere cloud provider doesn't rely on `node.Status.NodeInfo.SystemUUID` anymore, and the out-of-tree vSphere cloud provider handles the UUID mapping - https://github.com/kubernetes/cloud-provider-vsphere/blob/master/pkg/cloudprovider/vsphere/util.go#L48

**Comment by yujuhong** [comment]
/approve
Thanks for fixing this!
