### PR TITLE
Keep discovery types unversioned when encoding them at endpoints that exists in release 1.1

### LINKED ISSUE #20824: v1.1 e2es running against v1.2 master: 'no kind "APIVersions" is registered for version "v1"'
**Kubectl client Kubectl api-versions should check if v1 is in available api versions [Conformance]**

*/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl.go:444 Expected error: <*errors.errorString | 0xc208641770>: { s: "Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.1-master-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://130.211.136.232 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.1-master-step1-deploy/workspace/.kube/config api-versions] [] error: Couldn't get available api versions from server: no kind \"APIVersions\" is registered for version \"v1\"\n [] 0xc208382fa0 exit status 1 true [0xc208627148 0xc208627168 0xc208627188] [0xc208627148 0xc208627168 0xc208627188] [0xc208627160 0xc208627180] [0x6d81a0 0x6d81a0] 0xc2082fb2c0}:\nCommand stdout:\n\nstderr:\nerror: Couldn't get available api versions from server: no kind \"APIVersions\" is registered for version \"v1\"\n\n", } Error running &{/jenkins-master-data/jobs/kubernetes-upgrade-gke-1.1-master-step1-deploy/workspace/kubernetes/platforms/linux/amd64/kubectl [kubectl --server=https://130.211.136.232 --kubeconfig=/var/lib/jenkins/jobs/kubernetes-upgrade-gke-1.1-master-step1-deploy/workspace/.kube/config api-versions] [] error: Couldn't get available api versions from server: no kind "APIVersions" is registered for version "v1" [] 0xc208382fa0 exit status 1 true [0xc208627148 0xc208627168 0xc208627188] [0xc208627148 0xc208627168 0xc208627188] [0xc208627160 0xc208627180] [0x6d81a0 0x6d81a0] 0xc2082fb2c0}: Command stdout: stderr: error: Couldn't get available api versions from server: no kind "APIVersions" is registered for version "v1" not to have occurred*

See http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.1-master-step4-e2e-old/ and http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GKE/job/kubernetes-upgrade-gke-1.1-master-step6-e2e-old/

Investigating...

cc @caesarxuchao

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fix #20824.

@smarterclayton could you take a look? I still have some unit tests to fix but want to first make sure this is the right way to go.

cc @ihmccreery @lavalamp

### CODE REVIEW

**Comment by smarterclayton** [comment]
Approach lgtm

File: pkg/api/serialization_test.go [hunk 1]
```diff
@@ -247,12 +251,15 @@ func TestUnversionedTypes(t *testing.T) {
...
+		versionDecodedObject := pair.EmptyCopy
 		// Make sure the versioned codec under test can decode
-		versionDecodedObject, err := runtime.Decode(testapi.Default.Codec(), unversionedJSON)
+		err = runtime.DecodeInto(testapi.Default.Codec(), unversionedJSON, versionDecodedObject)
 		if err != nil {
 			t.Errorf("%v: unexpected error: %v", obj, err)
 			continue
 		}
+		// DecodeInto will set the APIVersion to the version the object are registered with, which we don't care.
+		versionDecodedObject.GetObjectKind().SetGroupVersionKind(&unversioned.GroupVersionKind{})
```
Comment (caesarxuchao) [inline pkg/api/serialization_test.go]: @smarterclayton I observed calling `runtime.Decode()` and `runtime.DecodeInto()` on unversioned objects will return different results, `DecodeInto()` will set the APIVersion and Kind, while `Decode()` doesn't, is this expected?

**Comment by caesarxuchao** [comment]
Tests should be passing now. PTAL. Thank you.

File: pkg/api/register.go [hunk 2]
```diff
@@ -111,6 +111,15 @@ func AddToScheme(scheme *runtime.Scheme) {
 		&unversioned.APIGroup{},
 		&unversioned.APIResourceList{},
 	)
+
+	// Types registered here will be kept unversioned when they are encoded.
+	// It's for backward compatibility with release 1.1. clients.
+	Scheme.AddToKeepUnverioned(
```
Comment (smarterclayton) [inline pkg/api/register.go]: Should this only be for the legacy API group?  Because when we introduce extension servers I would like to fix this and require anyone connecting to a non core group to support both "" and "v1"?  As written this means all new 1.2 groups will also have to support empty apiVersion on their types.

Comment (smarterclayton) [inline pkg/api/register.go]: Also, typo in AddToKeepUnversioned

File: pkg/api/serialization_test.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/api/serialization_test.go]: Technically anything unversioned is not converted, and we don't clear the values automatically if you aren't converted.

I'm on the fence on whether we should clear those values - if it has no impact internally (because we don't read them) I'm disinclined to make other changes.

File: pkg/api/register.go (hunk 2 above)
Comment (caesarxuchao) [inline pkg/api/register.go]: We have extensions endpoints in release-1.1, so probably we need to set APIVersion to "" for all groups.

I'll fix the typo.

Comment (smarterclayton) [inline pkg/api/register.go]: What about all the other groups we introduced?

File: pkg/api/serialization_test.go (hunk 1 above)
Comment (caesarxuchao) [inline pkg/api/serialization_test.go]: Yeah, now I remember we've discussed this in 17922. It's fine I think.

File: pkg/api/register.go (hunk 2 above)
Comment (caesarxuchao) [inline pkg/api/register.go]: I'd rather making all of them "" until we have release-v2, than making some groups' endpoints return "" and some return "v1". What do you say?

Comment (smarterclayton) [inline pkg/api/register.go]: For some of the new groups there isn't likely to be a v2 group at the
same time Kube core API goes to v2.  And community extensions will
likely not upgrade at the same time.  I don't know that there *will*
be a real v2 for all groups at the same time.  So we could wait, but
that might be a long time.

Comment (caesarxuchao) [inline pkg/api/register.go]: Agree, waiting for v2 might take too long time. @smarterclayton, any suggestion on how to implement the different behavior for different groups? I can only think of very hacky implementation.

Comment (smarterclayton) [inline pkg/api/register.go]: We need to control serialization on the apiserver and deserialization on client impls.  For client impls, we want to tolerate both paths (which means we need these types registered in an API group as well as outside).  To control server side, I think it has to be something that we know about when we render them in the discovery handlers.  The handlers are rendered outside of a group today.  We would need to have a specific codec wrapper for stripping api group version info, and then use that particular codec in negotiate only for certain calls.

Comment (smarterclayton) [inline pkg/api/register.go]: So client impl is easier because we can extend this method to take a group/version and record that alongside the decision to remove the flag.  Server impl needs an explicit wrapper to fix discovery.

Comment (caesarxuchao) [inline pkg/api/register.go]: For the client side, can we tell people to use DecodeInto() when dealing with these discovery objects? DecodeInto() will tolerate both.

Comment (smarterclayton) [inline pkg/api/register.go]: We can for our clients yes (which is what triggered this).  For
external clients I suspect they wouldn't fail like this, but we could
document this in the API and announce that path.

**Comment by caesarxuchao** [comment]
@smarterclayton PTAL. Thanks. I'll add godoc and tests after you approve the approach.

**Comment by caesarxuchao** [comment]
@smarterclayton could you take another look? Thanks.

File: pkg/apiserver/apiserver.go [hunk 3]
```diff
@@ -250,7 +285,11 @@ func AddApisWebService(s runtime.NegotiatedSerializer, container *restful.Contai
 // Adds a service to return the supported versions, preferred version, and name
 // of a group. E.g., a such web service will be registered at /apis/extensions.
 func AddGroupWebService(s runtime.NegotiatedSerializer, container *restful.Container, path string, group unversioned.APIGroup) {
-	groupHandler := GroupHandler(s, group)
+	ss := s
+	if keepUnversioned(group.Name) {
```
Comment (smarterclayton) [inline pkg/apiserver/apiserver.go]: Comments with each of these and a test to verify no regression, approach looks fine

Comment (lavalamp) [inline pkg/apiserver/apiserver.go]: These are only the discovery endpoints, correct?

**Comment by lavalamp** [comment]
Yes, time for godoc & test

File: pkg/apiserver/apiserver.go (hunk 3 above)
Comment (caesarxuchao) [inline pkg/apiserver/apiserver.go]: Yes.

**Comment by caesarxuchao** [comment]
I've added godocs and a test. PTAL. Thanks.

**Comment by ihmccreery** [comment]
Ping @smarterclayton @caesarxuchao?

**Comment by caesarxuchao** [comment]
@smarterclayton could you take a pass? Thanks.

File: pkg/master/master_test.go [hunk 4]
```diff
@@ -256,6 +256,54 @@ func TestGetNodeAddresses(t *testing.T) {
...
+
+	// /api exists in release-1.1
+	resp, err := http.Get(server.URL + "/api")
+	if err != nil {
+		t.Errorf("unexpected error: %v", err)
+	}
+	apiVersions := unversioned.APIVersions{}
+	assert.NoError(decodeResponse(resp, &apiVersions))
+	assert.Equal(apiVersions.APIVersion, "")
+
```
Comment (lavalamp) [inline pkg/master/master_test.go]: /api/v1?

File: pkg/master/master_test.go [hunk 5]
```diff
@@ -256,6 +256,54 @@ func TestGetNodeAddresses(t *testing.T) {
 	assert.Equal([]string{"127.0.0.2", "127.0.0.2"}, addrs)
 }
 
+// Because we need to be backwards compatible with release 1.1, at endpoints
+// that exist in release 1.1, the responses should have empty APIVersion.
+func TestAPIVersionOfDiscoveryEndpoints(t *testing.T) {
```
Comment (lavalamp) [inline pkg/master/master_test.go]: Does this test fail without your changes?

File: pkg/master/master_test.go [hunk 6]
```diff
@@ -256,6 +256,54 @@ func TestGetNodeAddresses(t *testing.T) {
...
+	resp, err = http.Get(server.URL + "/apis/extensions/v1beta1")
+	if err != nil {
+		t.Errorf("unexpected error: %v", err)
+	}
+	resourceList := unversioned.APIResourceList{}
+	assert.NoError(decodeResponse(resp, &resourceList))
+	assert.Equal(resourceList.APIVersion, "")
+
+	// TODO: We don't have endpoints for other groups yet. We should verify they
+	// have correct (non-empty) APIVersion in the responses.
```
Comment (lavalamp) [inline pkg/master/master_test.go]: autoscaler/ should exist if you rebase.

File: pkg/master/master_test.go (hunk 5 above)
Comment (caesarxuchao) [inline pkg/master/master_test.go]: Yes. Before this PR, all discovery objects returned by server has "apiVersion" field equal to "v1".

**Comment by smarterclayton** [comment]
I have no additional comments

File: pkg/master/master_test.go (hunk 4 above)
Comment (caesarxuchao) [inline pkg/master/master_test.go]: Added.

**Comment by caesarxuchao** [comment]
@lavalamp I've addressed your comments. Can I get the label? Thanks.

File: pkg/master/master_test.go [hunk 7]
```diff
@@ -260,6 +260,79 @@ func TestGetNodeAddresses(t *testing.T) {
...
+	// /apis/autoscaling doesn't exist in release-1.1
+	resp, err = http.Get(server.URL + "/apis/autoscaling")
+	if err != nil {
+		t.Errorf("unexpected error: %v", err)
+	}
+	group = unversioned.APIGroup{}
+	assert.NoError(decodeResponse(resp, &group))
+	assert.Equal(group.APIVersion, "v1")
+
+	// apis/autoscaling/v1 exists in release-1.1
```
Comment (lavalamp) [inline pkg/master/master_test.go]: You mean, in release-1.2?

**Comment by lavalamp** [comment]
LGTM-- one nit you can fix if you see this before it merges.

File: pkg/master/master_test.go (hunk 7 above)
Comment (caesarxuchao) [inline pkg/master/master_test.go]: I meant to say it doesn't exist in 1.1. Sorry.

File: pkg/master/master_test.go [hunk 8]
```diff
@@ -260,6 +260,82 @@ func TestGetNodeAddresses(t *testing.T) {
...
+	// should be non-empty in the results returned by the server.
+	resp, err = http.Get(server.URL + "/apis/autoscaling")
+	if err != nil {
+		t.Errorf("unexpected error: %v", err)
+	}
+	group = unversioned.APIGroup{}
+	assert.NoError(decodeResponse(resp, &group))
+	assert.Equal(group.APIVersion, "v1")
+
+	// apis/autoscaling/v1 doesn't exist in release-1.1, so the APIVersion field
```
Comment (caesarxuchao) [inline pkg/master/master_test.go]: Comments are fixed. PTAL. Thanks.

Comment (caesarxuchao) [inline pkg/master/master_test.go]: Oh, I just saw you've applied the label. Thanks.
