### PR TITLE
kubeadm - fix local etcd grpc gateway

### LINKED ISSUE #910: etcd 3.2.x upgrade fails with `tls: bad certificate"; please retry.`
> etcd upgrade at HEAD is failing with `WARNING: 2018/06/11 19:24:21 Failed to dial 127.0.0.1:2379: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate"; please retry.`

initial hint was about SAN and CN fields in the generated certificates.

refs:
https://github.com/coreos/etcd/blob/master/CHANGELOG-3.2.md#security-authentication-1
https://github.com/coreos/etcd/blob/master/CHANGELOG-3.2.md#security-authentication-8
https://github.com/coreos/etcd/issues/8603
https://bugzilla.redhat.com/show_bug.cgi?id=1565762

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:
etcd 3.2 uses the server certificate as the client cert for the grpc
gateway, this updates the generation of the etcd server certificate to
add client usage to resolve the issue.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes/kubeadm/issues/910

**Release note**:
```release-note
NONE
```

### CODE REVIEW

File: cmd/kubeadm/app/phases/certs/certs.go [hunk 1]
```diff
@@ -377,7 +377,7 @@ func NewEtcdServerCertAndKey(cfg *kubeadmapi.MasterConfiguration, caCert *x509.C
 	config := certutil.Config{
 		CommonName: cfg.NodeRegistration.Name,
 		AltNames:   *altNames,
-		Usages:     []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
+		Usages:     []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth, x509.ExtKeyUsageClientAuth},
```
Comment (timothysc) [inline cmd/kubeadm/app/phases/certs/certs.go]: Could you log an issue against etcd and add a //TODO to fix this in the future.

**Review by timothysc — CHANGES_REQUESTED** [review]
/approve

**Review by luxas — APPROVED** [review]
/lgtm

As discussed in the SIG meeting, we're gonna do this as it's the way to go right now using the current etcd versions, but talk to the etcd team to improve this security-wise in the future. As Tim said, please do open an issue against coreos/etcd

**Comment by guillaumerose** [comment]
Do you have an update for the fix in etcd ? 

I'm looking at moving Docker Desktop from Kubernetes 1.10 to 1.11 and this certificate issue breaks the update process at the moment.
