### PR TITLE
E2E test to make sure controller does not crash because of nil volume spec

### LINKED ISSUE #49521: E2E for volume spec nil ptr issue
We should have an e2e to test issue #49418.  The test needs to delete a PVC while a pod is still using it, and then restart the controller manager.

/kind bug
/sig storage

### PR DESCRIPTION
**Pull request by davidz627**
Fixes #49521

Tests fix of issue referenced in #49418

### CODE REVIEW

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 1]
```diff
@@ -108,6 +109,107 @@ var _ = SIGDescribe("PersistentVolumes[Disruptive][Flaky]", func() {
...
+						ReadOnly: false,
+					},
+				},
+				Prebind: nil,
+			}
+			pv2, pvc2, err = framework.CreatePVPVC(c, pvConfig2, pvcConfig, ns, false)
+			Expect(err).NotTo(HaveOccurred())
+			framework.ExpectNoError(framework.WaitOnPVandPVC(c, ns, pv2, pvc2))
+
+			By("Attaching both PVC's to a single node")
```
Comment (msau42) [inline test/e2e/storage/persistent_volumes-disruptive.go]: single pod

File: test/e2e/framework/util.go [hunk 2]
```diff
@@ -3920,6 +3920,29 @@ func WaitForControllerManagerUp() error {
 	return fmt.Errorf("waiting for controller-manager timed out")
 }
 
+func CheckForControllerManagerHealthy() error {
+	var ps string
```
Comment (msau42) [inline test/e2e/framework/util.go]: Can you name this variable to what information you're getting out of 'docker ps'? Is it the PID?

File: test/e2e/framework/util.go [hunk 3]
```diff
@@ -3920,6 +3920,29 @@ func WaitForControllerManagerUp() error {
...
+	cmd := "sudo docker ps | grep k8s_kube-controller-manager | cut -d ' ' -f 1"
+	for start := time.Now(); time.Since(start) < 2*time.Minute; time.Sleep(5 * time.Second) {
```
Comment (msau42) [inline test/e2e/framework/util.go]: Can you make the 2 minutes configurable?

**Comment by davidz627** [comment]
addressed all comments

File: test/e2e/framework/util.go [hunk 4]
```diff
@@ -3920,6 +3920,30 @@ func WaitForControllerManagerUp() error {
...
+		result, err := SSH(cmd, GetMasterHost()+":22", TestContext.Provider)
+		if err != nil || result.Code != 0 {
+			// We don't necessarily know that it crashed, pipe could just be broken
+			LogSSHResult(result)
+		}
+		if result.Stdout != PID {
+			if PID == "" {
+				PID = result.Stdout
+			} else {
+				//its dead
```
Comment (msau42) [inline test/e2e/framework/util.go]: Can we log the different pids here

File: test/e2e/framework/util.go [hunk 5]
```diff
@@ -3920,6 +3920,30 @@ func WaitForControllerManagerUp() error {
...
 
+// CheckForControllerManagerHealthy checks that the controller manager does not crash within "duration"
+func CheckForControllerManagerHealthy(duration time.Duration) error {
+	var PID string
+	cmd := "sudo docker ps | grep k8s_kube-controller-manager | cut -d ' ' -f 1"
+	for start := time.Now(); time.Since(start) < duration; time.Sleep(5 * time.Second) {
+		result, err := SSH(cmd, GetMasterHost()+":22", TestContext.Provider)
+		if err != nil || result.Code != 0 {
+			// We don't necessarily know that it crashed, pipe could just be broken
+			LogSSHResult(result)
```
Comment (msau42) [inline test/e2e/framework/util.go]: If the SSH command failed, would that cause the pid check below to fail?

Comment (davidz627) [reply test/e2e/framework/util.go]: Ah yes, I think it would cause stdout to be empty and thus cause the check to fail. I will change the second case to an else if.

**Comment by davidz627** [comment]
comments addressed

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 6]
```diff
@@ -108,6 +109,107 @@ var _ = SIGDescribe("PersistentVolumes[Disruptive][Flaky]", func() {
...
+			diskName1, diskName2 string
+			err                  error
+			pvConfig1, pvConfig2 framework.PersistentVolumeConfig
+			pv1, pv2             *v1.PersistentVolume
+			pvc1, pvc2           *v1.PersistentVolumeClaim
+			clientPod            *v1.Pod
+		)
+
+		BeforeEach(func() {
+			framework.SkipUnlessProviderIs("gce", "gke")
```
Comment (msau42) [inline test/e2e/storage/persistent_volumes-disruptive.go]: I think we need to skip the test for gke because we will not be able to log into the master.

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 7]
```diff
@@ -108,6 +109,107 @@ var _ = SIGDescribe("PersistentVolumes[Disruptive][Flaky]", func() {
...
+			framework.SkipUnlessSSHKeyPresent()
+
+			By("Initializing first PD with PVPVC binding")
+			diskName1, err = framework.CreatePDWithRetry()
```
Comment (msau42) [inline test/e2e/storage/persistent_volumes-disruptive.go]: Under test/upgrades/storage/persistent_volumes.go, there's actually a createGCEVolume() method.  Maybe you can pull that out into volume_util.go and reuse it here.

File: test/e2e/storage/persistent_volumes-disruptive.go [hunk 8]
```diff
@@ -108,6 +109,107 @@ var _ = SIGDescribe("PersistentVolumes[Disruptive][Flaky]", func() {
...
+					},
+				},
+				Prebind: nil,
+			}
+			pv2, pvc2, err = framework.CreatePVPVC(c, pvConfig2, pvcConfig, ns, false)
+			Expect(err).NotTo(HaveOccurred())
+			framework.ExpectNoError(framework.WaitOnPVandPVC(c, ns, pv2, pvc2))
+
+			By("Attaching both PVC's to a single pod")
+			//create a node that attaches both pvcs
```
Comment (msau42) [inline test/e2e/storage/persistent_volumes-disruptive.go]: comment is redundant

File: test/e2e/framework/util.go [hunk 9]
```diff
@@ -3920,6 +3920,30 @@ func WaitForControllerManagerUp() error {
...
+// CheckForControllerManagerHealthy checks that the controller manager does not crash within "duration"
+func CheckForControllerManagerHealthy(duration time.Duration) error {
+	var PID string
+	cmd := "sudo docker ps | grep k8s_kube-controller-manager | cut -d ' ' -f 1"
+	for start := time.Now(); time.Since(start) < duration; time.Sleep(5 * time.Second) {
+		result, err := SSH(cmd, GetMasterHost()+":22", TestContext.Provider)
+		if err != nil || result.Code != 0 {
+			// We don't necessarily know that it crashed, pipe could just be broken
+			Logf("kube-controller-manager unreachable at %v", time.Since(start))
+			LogSSHResult(result)
```
Comment (msau42) [inline test/e2e/framework/util.go]: If SSH always fails, then this function is going to return success.

Comment (davidz627) [reply test/e2e/framework/util.go]: I guess a compromise must be made here. Maybe if the SSH fails a certain amount of times we call it a failure? But if it fails just once at some point we might not want to infer a controller-manager failure because it could just be networking issues. What do you think would be a reasonable way to approach this?

Comment (msau42) [reply test/e2e/framework/util.go]: Did you actually see the SSH fail during your testing?  I wouldn't expect it to.

Comment (davidz627) [reply test/e2e/framework/util.go]: No I've never seen it fail. Just a thought. Should I just have it count as a failure?

File: test/e2e/framework/util.go [hunk 10]
```diff
@@ -3920,6 +3920,30 @@ func WaitForControllerManagerUp() error {
...
+// CheckForControllerManagerHealthy checks that the controller manager does not crash within "duration"
+func CheckForControllerManagerHealthy(duration time.Duration) error {
+	var PID string
+	cmd := "sudo docker ps | grep k8s_kube-controller-manager | cut -d ' ' -f 1"
+	for start := time.Now(); time.Since(start) < duration; time.Sleep(5 * time.Second) {
+		result, err := SSH(cmd, GetMasterHost()+":22", TestContext.Provider)
+		if err != nil || result.Code != 0 {
+			// We don't necessarily know that it crashed, pipe could just be broken
+			LogSSHResult(result)
+			return fmt.Errorf("master unreachable after %v", time.Since(start))
```
Comment (msau42) [inline test/e2e/framework/util.go]: It's either we couldn't ssh to the master, or the command returned a non-zero code.

**Comment by msau42** [comment]
/lgtm

Thanks!

File: test/e2e/framework/util.go [hunk 11]
```diff
@@ -3920,6 +3920,33 @@ func WaitForControllerManagerUp() error {
 	return fmt.Errorf("waiting for controller-manager timed out")
 }
 
+// CheckForControllerManagerHealthy checks that the controller manager does not crash within "duration"
+func CheckForControllerManagerHealthy(duration time.Duration) error {
+	var PID string
+	cmd := "sudo docker ps | grep k8s_kube-controller-manager | cut -d ' ' -f 1"
+	for start := time.Now(); time.Since(start) < duration; time.Sleep(5 * time.Second) {
+		result, err := SSH(cmd, GetMasterHost()+":22", TestContext.Provider)
```
Comment (sttts) [inline test/e2e/framework/util.go]: is SSH still state of the art to access the master in e2e tests? I remember that we ported a lot of SSH calls to privileged pods long ago.

Comment (davidz627) [reply test/e2e/framework/util.go]: It looks like all the related functionality (and other functionality that needs info from master) in this file is using SSH calls. For example RestartControllerManager(),  WaitForControllerManagerUp(), etc. Could you point me to an example that uses privileged pods for similar functionality? I am curious as to how that works.

File: test/e2e/framework/util.go [hunk 12]
```diff
@@ -3920,6 +3920,33 @@ func WaitForControllerManagerUp() error {
 	return fmt.Errorf("waiting for controller-manager timed out")
 }
 
+// CheckForControllerManagerHealthy checks that the controller manager does not crash within "duration"
+func CheckForControllerManagerHealthy(duration time.Duration) error {
+	var PID string
+	cmd := "sudo docker ps | grep k8s_kube-controller-manager | cut -d ' ' -f 1"
```
Comment (jeffvance) [inline test/e2e/framework/util.go]: How long can we assume docker?

File: test/e2e/framework/volume_util.go [hunk 13]
```diff
@@ -492,3 +492,15 @@ func InjectHtml(client clientset.Interface, config VolumeTestConfig, volume v1.V
 	err = WaitForPodSuccessInNamespace(client, injectPod.Name, injectPod.Namespace)
 	Expect(err).NotTo(HaveOccurred())
 }
+
+func CreateGCEVolume() (*v1.PersistentVolumeSource, string) {
```
Comment (jeffvance) [inline test/e2e/framework/volume_util.go]: Just fyi, [_persistent_volumes-gce.go#L86_](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/persistent_volumes-gce.go#L86) could now call this func.
