### PR TITLE
Fix the issue of slow startup of the systemd watchdog

### LINKED ISSUE #132107: Systemd watchdog starts late
### What happened?

It looks like the systemd watchdog implemented in https://github.com/kubernetes/kubernetes/pull/127566/ starts a little late. I observed a situation when kubelet registration was slow and it caused the watchdog to kill the kubelet due to lack of notifications.

### What did you expect to happen?

watchdog should start as soon as possible to ensure that it only checks what is designed to check and does not depend on the initialization speed.

### How can we reproduce it (as minimally and precisely as possible)?

I didn't try but should be straightforward.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by zhifei92**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix the issue where kubelet's slow startup causes it to be mistakenly killed by the watchdog. 

#### Which issue(s) this PR is related to:
Fixes https://github.com/kubernetes/kubernetes/issues/132107

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by zhifei92** [comment]
Hello @SergeyKanzhelev, let me briefly describe my approach: I will start the watchdog before creating any of kubelet's dependencies (at that point, there will be no health checks, so the watchdog will always report a healthy status). Then, I will add the health check items before the syncLoop starts. Do you have any better suggestions?

**Comment by zhifei92** [comment]
The failed CI will be fixed once this PR is accepted.

File: pkg/kubelet/watchdog/watchdog_linux.go [hunk 1]
```diff
@@ -104,25 +104,29 @@ func NewHealthChecker(syncLoop syncLoopHealthChecker, opts ...Option) (HealthChe
...
 
+func (hc *healthChecker) AddHealthCheckers(syncLoop syncLoopHealthChecker, checkers []healthz.HealthChecker) {
+	// The health checks performed by checkers are the same as those for "/healthz".
+	hc.checkers = []healthz.HealthChecker{
+		healthz.PingHealthz,
+		healthz.LogHealthz,
+		healthz.NamedCheck("syncloop", syncLoop.SyncLoopHealthCheck),
+	}
+
+	hc.checkers = append(hc.checkers, checkers...)
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/watchdog/watchdog_linux.go]: is there any locking needed?

File: pkg/kubelet/watchdog/watchdog_linux.go [hunk 2]
```diff
@@ -104,25 +104,29 @@ func NewHealthChecker(syncLoop syncLoopHealthChecker, opts ...Option) (HealthChe
...
 		Steps:    2,
 	}
-	hc.checkers = append(hc.checkers, checkers...)
 	hc.retryBackoff = retryBackoff
 	hc.interval = watchdogVal / 2
 
 	return hc, nil
 }
 
+func (hc *healthChecker) AddHealthCheckers(syncLoop syncLoopHealthChecker, checkers []healthz.HealthChecker) {
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/watchdog/watchdog_linux.go]: the semantic of this is not clear. Typically `Add` will be ok to use multiple times. This one is more like `Initialize` or `Enable`

File: pkg/kubelet/watchdog/watchdog_linux_test.go [hunk 3]
```diff
@@ -85,7 +85,7 @@ func TestNewHealthChecker(t *testing.T) {
 				enabledErr: tt.mockErr,
 			}
 
-			_, err := NewHealthChecker(&mockSyncLoopHealthChecker{}, WithWatchdogClient(mockClient))
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/watchdog/watchdog_linux_test.go:88]: add test to ensure it runs without any checkers added.

**Comment by SergeyKanzhelev** [comment]
> Hello @SergeyKanzhelev, let me briefly describe my approach: I will start the watchdog before creating any of kubelet's dependencies (at that point, there will be no health checks, so the watchdog will always report a healthy status). Then, I will add the health check items before the syncLoop starts. Do you have any better suggestions?

Yeah, I think it is a safest approach

File: pkg/kubelet/watchdog/watchdog_linux.go (hunk 1 above)
Comment (zhifei92) [reply pkg/kubelet/watchdog/watchdog_linux.go]: Yes, locking is required.

File: pkg/kubelet/watchdog/watchdog_linux.go (hunk 2 above)
Comment (zhifei92) [reply pkg/kubelet/watchdog/watchdog_linux.go]: Fixed

**Comment by SergeyKanzhelev** [comment]
Please ping when this is ready for the next review

**Comment by zhifei92** [comment]
> Please ping when this is ready for the next review

Please continue the review.

File: cmd/kubelet/app/server.go [hunk 4]
```diff
@@ -603,6 +604,17 @@ func getReservedCPUs(machineInfo *cadvisorapi.MachineInfo, cpus string) (cpuset.
...
 func run(ctx context.Context, s *options.KubeletServer, kubeDeps *kubelet.Dependencies, featureGate featuregate.FeatureGate) (err error) {
+	var healthChecker watchdog.HealthChecker
+	if utilfeature.DefaultFeatureGate.Enabled(features.SystemdWatchdog) {
+		// NewHealthChecker returns an error indicating that the watchdog is configured but the configuration is incorrect,
+		// the kubelet will not be started.
+		healthChecker, err = watchdog.NewHealthChecker()
+		if err != nil {
+			return fmt.Errorf("create health checker: %w", err)
+		}
+		healthChecker.Start(ctx)
```
Comment (SergeyKanzhelev) [inline cmd/kubelet/app/server.go:615]: Do we need a `Start` to be a separate method? Should we just start it from constructor?

File: cmd/kubelet/app/server.go [hunk 5]
```diff
@@ -891,7 +903,7 @@ func run(ctx context.Context, s *options.KubeletServer, kubeDeps *kubelet.Depend
 		klog.InfoS("Failed to ApplyOOMScoreAdj", "err", err)
 	}
 
-	if err := RunKubelet(ctx, s, kubeDeps); err != nil {
+	if err := RunKubelet(ctx, s, kubeDeps, healthChecker); err != nil {
```
Comment (SergeyKanzhelev) [inline cmd/kubelet/app/server.go]: why not add `healthChecker` to the `kubeDeps`? Am I missing something?

File: pkg/kubelet/watchdog/watchdog_linux.go [hunk 6]
```diff
@@ -104,25 +99,39 @@ func NewHealthChecker(syncLoop syncLoopHealthChecker, opts ...Option) (HealthChe
...
+	defaultCheckers := []healthz.HealthChecker{
+		healthz.PingHealthz,
+		healthz.LogHealthz,
+		healthz.NamedCheck("syncloop", syncLoop.SyncLoopHealthCheck),
+	}
+
+	var combined []healthz.HealthChecker
+	combined = append(combined, defaultCheckers...)
+	combined = append(combined, checkers...)
+	hc.checkers.Store(combined)
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/watchdog/watchdog_linux.go:125]: if we assign the whole collection here, does it need to be atomic? Since we are not modifying the collection that another thread may be iterating, than just assignment may be fine?

Comment (zhifei92) [reply pkg/kubelet/watchdog/watchdog_linux.go:125]: > if we assign the whole collection here, does it need to be atomic? Since we are not modifying the collection that another thread may be iterating, than just assignment may be fine?

Sure, atomic operations are still necessary. Even if modifications are not made directly on the original slice, as long as the variable can be accessed by multiple goroutines simultaneously (for example, one goroutine is reading the health checker list to perform checks while another is calling SetHealthCheckers to update the list), there will be a data race.

File: cmd/kubelet/app/server.go (hunk 5 above)
Comment (zhifei92) [reply cmd/kubelet/app/server.go]: > why not add `healthChecker` to the `kubeDeps`?

We should definitely add the healthChecker to kubeDeps. Thanks for catching that!

File: cmd/kubelet/app/server.go (hunk 4 above)
Comment (zhifei92) [reply cmd/kubelet/app/server.go:615]: > Do we need a `Start` to be a separate method? Should we just start it from constructor?

Agree with you. There's no need to separate Start in the current scenario. However, passing context and starting the service in the constructor may not be a good practice.

**Comment by zhifei92** [comment]
@SergeyKanzhelev this PR has been updated and  I have responded to some of your comments. Could you please take a look? Thanks!

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve
/retest
