### PR TITLE
Non-zero cfs quota period duration requires feature flag

### LINKED ISSUE #94686: CustomCPUCFSQuotaPeriod feature is required for using cpuCFSQuotaPeriod in kubelet config
See https://github.com/kubernetes/kubernetes/issues/79833 for more context.

**What happened**:

When you set `cpuCFSQuota: true` and `cpuCFSQuotaPeriod: 10ms`, you'd expect container cfs quota period to be 10000. However, unless you also set `CustomCPUCFSQuotaPeriod: true` in the feature flags, the quota value will be silently ignored.

**What you expected to happen**:

At least a warning be logged if the feature is not enabled but `cpuCFSQuotaPeriod` is set.

**How to reproduce it (as minimally and precisely as possible)**: 

https://github.com/kubernetes/kubernetes/issues/79833#issue-464575246

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by karan**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Validates that the feature flag is set if `CPUCFSQuotaPeriod` is specified in kubelet config.

**Which issue(s) this PR fixes**:

Fixes #94686

**Special notes for your reviewer**:

`CPUCFSQuotaPeriod` is defaulted to 100ms. So if that's set, then we do not enforce this validation.

**Does this PR introduce a user-facing change?**:

```release-note
Require feature flag CustomCPUCFSQuotaPeriod if setting a non-default cpuCFSQuotaPeriod in kubelet config.
```

### CODE REVIEW

File: pkg/kubelet/apis/config/validation/validation.go [hunk 1]
```diff
@@ -60,6 +65,9 @@ func ValidateKubeletConfiguration(kc *kubeletconfig.KubeletConfiguration) error
 	if kc.HealthzPort != 0 && utilvalidation.IsValidPortNum(int(kc.HealthzPort)) != nil {
 		allErrors = append(allErrors, fmt.Errorf("invalid configuration: HealthzPort (--healthz-port) %v must be between 1 and 65535, inclusive", kc.HealthzPort))
 	}
+	if !localFeatureGate.Enabled(features.CPUCFSQuotaPeriod) && (kc.CPUCFSQuotaPeriod != zeroDuration && kc.CPUCFSQuotaPeriod != metav1.Duration{Duration: 100 * time.Millisecond}) {
```
Comment (mtaufen) [inline pkg/kubelet/apis/config/validation/validation.go:68]: nit: don't think we need the extra parens around `kc.CPUCFSQuotaPeriod != zeroDuration && kc.CPUCFSQuotaPeriod != metav1.Duration{Duration: 100 * time.Millisecond}`

File: pkg/kubelet/apis/config/validation/validation.go [hunk 2]
```diff
@@ -31,6 +32,10 @@ import (
 	kubetypes "k8s.io/kubernetes/pkg/kubelet/types"
 )
 
+var (
+	zeroDuration = metav1.Duration{}
```
Comment (mtaufen) [inline pkg/kubelet/apis/config/validation/validation.go:36]: Is this already defined elsewhere?

File: pkg/kubelet/apis/config/validation/validation_test.go [hunk 3]
```diff
@@ -115,9 +121,9 @@ func TestValidateKubeletConfiguration(t *testing.T) {
 		RegistryPullQPS:             -10,
 		HairpinMode:                 "foo",
 		NodeLeaseDurationSeconds:    -1,
-		CPUCFSQuotaPeriod:           metav1.Duration{Duration: 0},
+		CPUCFSQuotaPeriod:           metav1.Duration{Duration: 100},
```
[the remark this answers is not in the document]
Comment (karan) [reply pkg/kubelet/apis/config/validation/validation_test.go:124]: I made it explicitly 100 ms. This is to test the case where the default value is specified and so the validation should succeed.

File: pkg/kubelet/apis/config/validation/validation.go (hunk 1 above)
Comment (karan) [reply pkg/kubelet/apis/config/validation/validation.go:68]: Yeah I put it there for my clarity. Removed it.

File: pkg/kubelet/apis/config/validation/validation.go (hunk 2 above)
Comment (karan) [reply pkg/kubelet/apis/config/validation/validation.go:36]: A couple of places but it's local to those packages. It's the default value so I didn't want to introduce another dependency.

Comment (mtaufen) [reply pkg/kubelet/apis/config/validation/validation.go]: k sg

File: pkg/kubelet/apis/config/validation/validation.go [hunk 4]
```diff
@@ -60,6 +66,9 @@ func ValidateKubeletConfiguration(kc *kubeletconfig.KubeletConfiguration) error
 	if kc.HealthzPort != 0 && utilvalidation.IsValidPortNum(int(kc.HealthzPort)) != nil {
 		allErrors = append(allErrors, fmt.Errorf("invalid configuration: HealthzPort (--healthz-port) %v must be between 1 and 65535, inclusive", kc.HealthzPort))
 	}
+	if !localFeatureGate.Enabled(features.CPUCFSQuotaPeriod) && kc.CPUCFSQuotaPeriod != zeroDuration && kc.CPUCFSQuotaPeriod != defaultCFSQuota {
```
Comment (mtaufen) [inline pkg/kubelet/apis/config/validation/validation.go:69]: Thinking about this a little more, if 100ms is the default, then why is zeroDuration an exception to the validation?

Comment (karan) [reply pkg/kubelet/apis/config/validation/validation.go:69]: True - that's also covered by the next validation anyways. Will remove that check.
