### PR TITLE
DRA device taints: fix some race conditions

### LINKED ISSUE #130940: [Flaking Test] UT TestEviction/update
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/129458/pull-kubernetes-unit/1902685080560603136

### Which tests are flaking?

TestEviction/update

### Since when has it been flaking?

3/20/2025

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Reason for failure (if possible)

Running `stress ./devicetainteviction.test -test.run TestEviction ` will sometimes give me the following error:
```
E0320 13:12:56.440978   95961 panic.go:262] "Observed a panic" panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" stacktrace=<
        goroutine 204 [running]:
        k8s.io/apimachinery/pkg/util/runtime.logPanic({0x42ead10, 0xc000486210}, {0x3956c00, 0x5d55bf0})
                /home/maciej/workspace/k8s/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:132 +0xdd
        k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x42ead10, 0xc0004861e0}, {0x3956c00, 0x5d55bf0}, {0x0, 0x0, 0x7f3a8a61d700?})
                /home/maciej/workspace/k8s/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:107 +0x185
        k8s.io/apimachinery/pkg/util/runtime.HandleCrashWithLogger({{0x42f3238?, 0xc0000d1140?}, 0xc000b0b647?}, {0x0, 0x0, 0x0})
                /home/maciej/workspace/k8s/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:91 +0x11c
        panic({0x3956c00?, 0x5d55bf0?})
                /home/maciej/.gvm/gos/go1.24.1/src/runtime/panic.go:792 +0x132
        k8s.io/kubernetes/pkg/controller/tainteviction.(*TimedWorkerQueue).UpdateWork(0xc000473ec0, {0x42eb3b0, 0xc000025b80}, 0xc0004861b0, {0xc1ef1f721a44b59d, 0x1179909f, 0x5dad420}, {0xc1ef1f721382b7eb, 0xab792ed, 0x5dad420})
                /home/maciej/workspace/k8s/src/k8s.io/kubernetes/pkg/controller/tainteviction/timed_workers.go:148 +0x1cc
        k8s.io/kubernetes/pkg/controller/devicetainteviction.(*Controller).Run.func1({{{0x3d86ba3, 0x7}, {0x3d85ed5, 0x6}}, {0x3d84bce, 0x4}}, {0x0?, 0x0?, 0x5dad420?})
                /home/maciej/workspace/k8s/src/k8s.io/kubernetes/pkg/controller/devicetainteviction/device_taint_eviction.go:349 +0x1f2
        k8s.io/kubernetes/pkg/controller/devicetainteviction.(*Controller).handlePod(0xc00085b0e0, 0xc0003f3b08)
                /home/maciej/workspace/k8s/src/k8s.io/kubernetes/pkg/controller/devicetainteviction/device_taint_eviction.go:864 +0x3e3
        k8s.io/kubernetes/pkg/controller/devicetainteviction.(*Controller).handlePodChange(0xc00085b0e0, 0x0, 0xc0003f3b08)
                /home/maciej/workspace/k8s/src/k8s.io/kubernetes/pkg/controller/devicetainteviction/device_taint_eviction.go:796 +0x546
        k8s.io/kubernetes/pkg/controller/devicetainteviction.(*Controller).Run.func7({0x3d4ce40, 0xc0003f3b08})
                /home/maciej/workspace/k8s/src/k8s.io/kubernetes/pkg/controller/devicetainteviction/device_taint_eviction.go:426 +0x12a
        k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
                /home/maciej/workspace/k8s/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/controller.go:257
        k8s.io/client-go/tools/cache.(*processorListener).run.func1(0xc000b0bf1f, 0xc00002a8c0, {0x3a74900, 0xc0003b3140})
                /home/maciej/workspace/k8s/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/shared_informer.go:1077 +0x1fb
        k8s.io/client-go/tools/cache.(*processorListener).run(0xc00002a8c0)
                /home/maciej/workspace/k8s/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/shared_informer.go:1087 +0x5f
        k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
                /home/maciej/workspace/k8s/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x87
        created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start in goroutine 93
                /home/maciej/workspace/k8s/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:70 +0xe5
 >
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x29d21cc]

goroutine 204 [running]:
k8s.io/apimachinery/pkg/util/runtime.handleCrash({0x42ead10, 0xc0004861e0}, {0x3956c00, 0x5d55bf0}, {0x0, 0x0, 0x7f3a8a61d700?})
        /home/maciej/workspace/k8s/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:114 +0x23a
k8s.io/apimachinery/pkg/util/runtime.HandleCrashWithLogger({{0x42f3238?, 0xc0000d1140?}, 0xc000b0b647?}, {0x0, 0x0, 0x0})
        /home/maciej/workspace/k8s/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/runtime/runtime.go:91 +0x11c
panic({0x3956c00?, 0x5d55bf0?})
        /home/maciej/.gvm/gos/go1.24.1/src/runtime/panic.go:792 +0x132
k8s.io/kubernetes/pkg/controller/tainteviction.(*TimedWorkerQueue).UpdateWork(0xc000473ec0, {0x42eb3b0, 0xc000025b80}, 0xc0004861b0, {0xc1ef1f721a44b59d, 0x1179909f, 0x5dad420}, {0xc1ef1f721382b7eb, 0xab792ed, 0x5dad420})
        /home/maciej/workspace/k8s/src/k8s.io/kubernetes/pkg/controller/tainteviction/timed_workers.go:148 +0x1cc
k8s.io/kubernetes/pkg/controller/devicetainteviction.(*Controller).Run.func1({{{0x3d86ba3, 0x7}, {0x3d85ed5, 0x6}}, {0x3d84bce, 0x4}}, {0x0?, 0x0?, 0x5dad420?})
        /home/maciej/workspace/k8s/src/k8s.io/kubernetes/pkg/controller/devicetainteviction/device_taint_eviction.go:349 +0x1f2
k8s.io/kubernetes/pkg/controller/devicetainteviction.(*Controller).handlePod(0xc00085b0e0, 0xc0003f3b08)
        /home/maciej/workspace/k8s/src/k8s.io/kubernetes/pkg/controller/devicetainteviction/device_taint_eviction.go:864 +0x3e3
k8s.io/kubernetes/pkg/controller/devicetainteviction.(*Controller).handlePodChange(0xc00085b0e0, 0x0, 0xc0003f3b08)
        /home/maciej/workspace/k8s/src/k8s.io/kubernetes/pkg/controller/devicetainteviction/device_taint_eviction.go:796 +0x546
k8s.io/kubernetes/pkg/controller/devicetainteviction.(*Controller).Run.func7({0x3d4ce40, 0xc0003f3b08})
        /home/maciej/workspace/k8s/src/k8s.io/kubernetes/pkg/controller/devicetainteviction/device_taint_eviction.go:426 +0x12a
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnAdd(...)
        /home/maciej/workspace/k8s/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/controller.go:257
k8s.io/client-go/tools/cache.(*processorListener).run.func1(0xc000b0bf1f, 0xc00002a8c0, {0x3a74900, 0xc0003b3140})
        /home/maciej/workspace/k8s/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/shared_informer.go:1077 +0x1fb
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00002a8c0)
        /home/maciej/workspace/k8s/src/k8s.io/kubernetes/staging/src/k8s.io/client-go/tools/cache/shared_informer.go:1087 +0x5f
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        /home/maciej/workspace/k8s/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:72 +0x87
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start in goroutine 93
        /home/maciej/workspace/k8s/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/util/wait/wait.go:70 +0xe5
```

I didn't get that error from CI, though it also asks for investigation. 

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind bug
/kind failing-test

#### What this PR does / why we need it:

The code was merged yesterday and didn't work reliably (see commit messages for details). We either need to fix it before it gets released or revert. Reverting would be harder and put other pending PRs at risk because of the API changes.

#### Which issue(s) this PR fixes:

Fixes #130940

#### Special notes for your reviewer:

```console
$ go test -c ./pkg/controller/devicetainteviction && stress ./devicetainteviction.test
5s: 0 runs so far, 0 failures
10s: 0 runs so far, 0 failures
15s: 36 runs so far, 0 failures
...
3m50s: 792 runs so far, 0 failures
3m55s: 792 runs so far, 0 failures
4m0s: 827 runs so far, 0 failures
^C
```

While at it, waiting for a condition is now done with consistently (no pun intended - or is it?) with ktesting.Eventually + gomega. It's failure messages are a bit more informative than testify's.

#### Does this PR introduce a user-facing change?

No additional release note, code wasn't released yet.

```release-note
NONE
```

/assign @nojnhuh @soltysh

### CODE REVIEW

File: pkg/controller/devicetainteviction/device_taint_eviction_test.go [hunk 1]
```diff
@@ -494,6 +498,24 @@ func TestHandlers(t *testing.T) {
...
+			initialState: state{
+				pods:            []*v1.Pod{unscheduledPodWithClaimName},
+				slices:          []*resourceapi.ResourceSlice{sliceTainted, slice2},
+				allocatedClaims: []allocatedClaim{{ResourceClaim: inUseClaim, evictionTime: &taintTime}},
+				evicting:        []evictAt{{newObject(podWithClaimName), taintTime.Time}},
+			},
+			events: []any{
+				// Normally the scheduler shouldn't schedule when there is a taint,
+				// but perhaps it didn't know yet.
+				[]any{update(unscheduledPodWithClaimName, podWithClaimName)},
```
Comment (nojnhuh) [inline pkg/controller/devicetainteviction/device_taint_eviction_test.go:511]: nit: if there's only one event, we could remove the inner `[]any{}` wrapping:
```suggestion
				update(unscheduledPodWithClaimName, podWithClaimName),
```

File: pkg/controller/devicetainteviction/device_taint_eviction_test.go [hunk 2]
```diff
@@ -494,6 +498,24 @@ func TestHandlers(t *testing.T) {
 			// At the moment, the code reliably cancels right away.
 			wantEvents: []*v1.Event{cancelPodEviction},
 		},
+		"evict-pod-after-scheduling": {
+			initialState: state{
+				pods:            []*v1.Pod{unscheduledPodWithClaimName},
+				slices:          []*resourceapi.ResourceSlice{sliceTainted, slice2},
+				allocatedClaims: []allocatedClaim{{ResourceClaim: inUseClaim, evictionTime: &taintTime}},
+				evicting:        []evictAt{{newObject(podWithClaimName), taintTime.Time}},
```
Comment (nojnhuh) [inline pkg/controller/devicetainteviction/device_taint_eviction_test.go:506]: Is the idea with this test that the pod should not be queued for eviction at first, but then is after the pod is updated? I see this test pass even without the NodeName check otherwise.

**Review by nojnhuh — COMMENTED** [review]
Overall LGTM, maybe found one small issue with the unit tests.

**Comment by nojnhuh** [comment]
I wouldn't block on either of those comments.

/lgtm

File: pkg/controller/devicetainteviction/device_taint_eviction_test.go (hunk 1 above)
Comment (pohly) [reply pkg/controller/devicetainteviction/device_taint_eviction_test.go]: Fixed and [pushed](https://github.com/kubernetes/kubernetes/compare/6f7a997ae23ca98a3dc9a157c8d6f42cfbdaceba..cfb9486417d28304049a97cd4464dd8a9069406d).

File: pkg/controller/devicetainteviction/device_taint_eviction_test.go (hunk 2 above)
Comment (pohly) [reply pkg/controller/devicetainteviction/device_taint_eviction_test.go]: Oh, right, I need to remove the initial evicting state. Then it fails without the `oldPod.Spec.NodeName == newPod.Spec.NodeName`.

Fixed.

**Comment by pohly** [comment]
/assign @jpbetz 

For approval. @soltysh seems to be out already.

**Comment by pohly** [comment]
/priority critical-urgent

Flake in pull/ci-kubernetes-unit.

/triage accepted

**Review by nojnhuh — APPROVED** [review]
/lgtm

File: pkg/controller/devicetainteviction/device_taint_eviction.go [hunk 3]
```diff
@@ -319,7 +320,8 @@ func New(c clientset.Interface, podInformer coreinformers.PodInformer, claimInfo
 }
 
 // Run starts the controller which will run until the context is done.
-func (tc *Controller) Run(ctx context.Context) {
+// An error is returned for startup problems.
+func (tc *Controller) Run(ctx context.Context) error {
```
Comment (soltysh) [inline pkg/controller/devicetainteviction/device_taint_eviction.go:324]: This is breaking the general approach that `Run` is not returning errors. None of our controller's `Run` does so. In your case you're adding event handlers in `Run` but that should happen in `New`. Although looking at the controller this will require a major rewrite :disappointed:

**Review by soltysh — APPROVED** [review]
/label tide/merge-method-squash
/lgtm 
/approve
to get the flake fixed, at least for now...

**Comment by pohly** [comment]
/remove-label tide/merge-method-squash

Each commit is self-contained, let's keep them separate.

File: pkg/controller/devicetainteviction/device_taint_eviction.go (hunk 3 above)
Comment (pohly) [reply pkg/controller/devicetainteviction/device_taint_eviction.go:324]: Other controllers also fail in Run. They just hide it in their own code, some with error logging, some without:

https://github.com/kubernetes/kubernetes/blob/03e818744a8f92eb87155f2576dad982da7e6a43/pkg/controller/tainteviction/taint_eviction.go#L298-L301

https://github.com/kubernetes/kubernetes/blob/03e818744a8f92eb87155f2576dad982da7e6a43/pkg/controller/storageversiongc/gc_controller.go#L103-L106

Admittedly the setup procedure in this case in Run has more error paths (most of them very unlikely!). But in return you can call New and discard the result without any resource leaks (goroutines, registered informers). That is not true for the other controllers. Let's discuss more face-to-face...
