### PR TITLE
kubeadm upgrade: fix dry run of backing up kubelet config file

### LINKED ISSUE #2796: fix failing dryrun e2e job
some of our recent changes broke the dryrun e2e

https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-dryrun-latest

tip: to see what commits was it one can click a red box and drag to a green box. i am currently on mobile and can't do that.

we should try to fix this before xmas and not having any failing tests during the holidays...preferably since folks are not around.

@pacoxu @SataQiu @chendave

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind bug
#### What this PR does / why we need it:

```
[upgrade] Skipping phase. Not a control plane node.
[upgrade] backing up kubelet config file to /etc/kubernetes/tmp/kubeadm-kubelet-config4028019749/config.yaml
rename /etc/kubernetes/tmp/kubeadm-upgrade-dryrun1808990387/config.yaml /etc/kubernetes/tmp/kubeadm-kubelet-config4028019749/config.yaml: no such file or directory
error backing up the kubelet config file
```

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubeadm/issues/2796

#### Special notes for your reviewer:
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-dryrun-latest
https://github.com/kubernetes/kubernetes/pull/114330#issuecomment-1354315864

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

File: cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go [hunk 1]
```diff
@@ -78,9 +78,13 @@ func runKubeletConfigPhase() func(c workflow.RunData) error {
...
+		if !dryRun {
+			fmt.Printf("[upgrade] backing up kubelet config file to %s\n", dest)
+			if err := os.Rename(src, dest); err != nil {
+				return errors.Wrap(err, "error backing up the kubelet config file")
+			}
+		} else {
+			fmt.Printf("[upgrade] Would back up kubelet config file to %s\n", dest)
 		}
 		// Store the kubelet component configuration.
 		if err = kubeletphase.WriteConfigToDisk(&cfg.ClusterConfiguration, kubeletDir, data.PatchesDir(), data.OutputWriter()); err != nil {
```
Comment (chendave) [inline cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go:90]: Can you pls check this for dry-run as well?

File: cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go [hunk 2]
```diff
@@ -78,9 +78,13 @@ func runKubeletConfigPhase() func(c workflow.RunData) error {
...
-		fmt.Printf("[upgrade] backing up kubelet config file to %s\n", dest)
-		if err := os.Rename(src, dest); err != nil {
-			return errors.Wrap(err, "error backing up the kubelet config file")
+		if !dryRun {
+			fmt.Printf("[upgrade] backing up kubelet config file to %s\n", dest)
+			if err := os.Rename(src, dest); err != nil {
+				return errors.Wrap(err, "error backing up the kubelet config file")
+			}
+		} else {
+			fmt.Printf("[upgrade] Would back up kubelet config file to %s\n", dest)
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go:87]:
```suggestion
			fmt.Printf("[dryrun] Would back up kubelet config file to %s\n", dest)
```
i think we should have [dryrun] for consistency.
q: do we have words after the ] starting with uppercase (w vs W)? might be a good idea to correct these in ghe new backup code printfs too.

File: cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go (hunk 1 above)
Comment (chendave) [reply cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go:90]: okay, I think the original logic is that write the config to a fake dir if it's dry run. If we agree that original logic is okay, there is no need to distinguish the dry-run or not for backing up and write config.

so, I think,
- we don't need this change and do all those thing in the fake dir if it is dry-run mode.
- don't create the fake dir (as we won't use it), and just print instead of action if it's dry-run mode.

File: cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go (hunk 2 above)
Comment (pacoxu) [reply cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go:87]: It seems all `fmt.Printf("[upgrade] ` are starting with uppercase.

**Comment by chendave** [comment]
Just a quick note, I am okay to this change since I just noticed this blocks the job of kinder, we can revisit this after the holiday.

File: cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go (hunk 2 above)
Comment (neolit123) [reply cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go]: ik

File: cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go:90]: we can get away with not writing the backup file during dryrun and just print the message..."would..."

but if we are writing backup of manifest files during kubeadm upgrade dryrun we might also want to keep this kubelet backup writing during dryrun for consistency.

File: cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go (hunk 2 above)
Comment (pacoxu) [reply cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go]: image

Updated.
But, we should keep it consistent to start with uppercase.

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

File: cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go (hunk 1 above)
Comment (chendave) [reply cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go:90]: I went through the relevant code, and confirm that
- the manifest files will be written to the /tmp dir if upgrading a node with dry-run mode.
- this is needed since kubeadm would print the content of the manifest or kubelet conf if it's dry-run mode, this requires that the config or manifest files should be written to the /tmp dir beforehand.

Comment (neolit123) [reply cmd/kubeadm/app/cmd/phases/upgrade/node/kubeletconfig.go:90]: right, i forgot about that.

still not clear to what is best, but if you have a pr in mind just send it please.
