### PR TITLE
fix kubectl rolling update empty file cause panic issue

### LINKED ISSUE #29398: rolling-update with empty file panics
For example
```
> touch empty
> kubectl rolling-update rcname  -f empty

panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x19dca80, 0xc82000e0d0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
k8s.io/kubernetes/pkg/kubectl/cmd.RunRollingUpdate(0xc8204c6200, 0x7fda65fb6198, 0xc820090008, 0xc820324800, 0xc8200a4690, 0x1, 0x5, 0xc82029f380, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/rollingupdate.go:220 +0x46ee
k8s.io/kubernetes/pkg/kubectl/cmd.NewCmdRollingUpdate.func1(0xc820324800, 0xc8200a4690, 0x1, 0x5)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubectl/cmd/rollingupdate.go:86 +0x7d
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc820324800, 0xc8200a4640, 0x5, 0x5, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:565 +0x85a
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc8200d2000, 0xc820324800, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:651 +0x55c
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(0xc8200d2000, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:610 +0x2d
k8s.io/kubernetes/cmd/kubectl/app.Run(0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/app/kubectl.go:32 +0xf0
main.main()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:28 +0x28
```

### PR DESCRIPTION
**Pull request by adohe-zz**
``` release-note
Fix issue with kubectl panicing when passed files that do not exist.
```

Fix #29398 
@pwittrock @justinsb ptal. This just fix on the cmd layer, I am thinking whether we should return err from marshal&unmarshal if the reader is empty.

### CODE REVIEW

**Comment by dims** [comment]
@AdoHe "return err from marshal&unmarshal if the reader is empty." sounds like the right thing to do (for folks who are using the API directly)

File: pkg/kubectl/cmd/rollingupdate.go [hunk 1]
```diff
@@ -220,6 +220,9 @@ func RunRollingUpdate(f *cmdutil.Factory, out io.Writer, cmd *cobra.Command, arg
 			if len(list.Items) > 1 {
 				return cmdutil.UsageError(cmd, "%s specifies multiple items", filename)
 			}
+			if len(list.Items) == 0 {
+				return cmdutil.UsageError(cmd, "please make sure %s is not empty file", filename)
```
Comment (pwittrock) [inline pkg/kubectl/cmd/rollingupdate.go]: nit: `please make sure %s exists and is not empty`

**Comment by AdoHe** [comment]
@pwittrock updated, ptal.
