### PR TITLE
Backoff only when failed pod shows up

### LINKED ISSUE #59918: Jobs - takes a while to update job status if job succeeds after retrying many times
/kind bug

**What happened**:

Create a job that will fail many times, but eventually succeeds.

After the job's pod succeeds, it takes a long time to update the job status.

**What you expected to happen**:

After the job's pod succeeds, the job's status is updated immediately.

**How to reproduce it (as minimally and precisely as possible)**:

Create a simple configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: result
data:
  result: failure
```

Create a job that runs a pod that fails based on the value of the configmap:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
spec:
  backoffLimit: 100
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - command:
        - sh
        - -c
        - if [ "${RESULT}" = "failure" ]; then exit 1; fi
        image: busybox
        imagePullPolicy: IfNotPresent
        name: testjob
        env:
        - name: RESULT
          valueFrom:
            configMapKeyRef:
              name: result
              key: result
```

Let the job fail a few times
After about a minute or so, edit the configmap and change the value of its `result` key:

```
kubectl edit cm/result
```

Wait for the job to launch a pod that succeeds
```
kubectl get pods -w
```

Wait for the job to be updated based on the success of the pod
```
kubectl get jobs -w
```

There is about a 5 min wait between the time the pod succeeds and the job's status is updated.

**Anything else we need to know?**:

The job controller immediately gets a pod updated event, which results in the `enqueueController` method getting called.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L263

The `enqueueController` method applies a backoff based on how many times the job has been retried:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/job/job_controller.go#L352-L361

This seems wrong. The backoff should be applied to pod creation and not to handling an update event from an existing pod.

### PR DESCRIPTION
**Pull request by soltysh**
**What this PR does / why we need it**:
Upon introducing the backoff policy we started to delay sync runs for the job when it failed several times before. This leads to failed jobs not reporting status right away in cases that are not related to failed pods, eg. a successful run. This PR ensures the backoff is applied only when `updatePod` receives a failed pod.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #59918 #59527

/assign @janetkuo @kow3ns 

**Release note**:
```release-note
None
```

### CODE REVIEW

**Comment by soltysh** [comment]
@janetkuo @kow3ns not sure if we want to have this for 1.10, I'll mark it as such, but feel free to drop it from there.

**Comment by soltysh** [comment]
Fixed the bazel update.

File: pkg/controller/job/job_controller.go [hunk 1]
```diff
@@ -341,16 +350,23 @@ func (jm *JobController) updateJob(old, cur interface{}) {
...
-		utilruntime.HandleError(fmt.Errorf("Couldn't get key for object %+v: %v", job, err))
+		utilruntime.HandleError(fmt.Errorf("Couldn't get key for object %+v: %v", obj, err))
 		return
 	}
 
-	// Retrieves the backoff duration for this Job
-	backoff := getBackoff(jm.queue, key)
+	var backoff time.Duration
+	if immediate {
+		backoff = time.Duration(0)
```
Comment (clamoriniere1A) [inline pkg/controller/job/job_controller.go]: I think that forcing the backoff value to 0 will only do half of the job because it didn't clear the counter of the previous failures in the rateLimitedQueue.

what do you think about the following code?
```
if immediate {
  jm.queue.Forget(key)
}
backoff := getBackoff(jm.queue, key)
```

**Comment by jdumars** [comment]
If this gets an LGTM ASAP we can get this into 1.10.

File: pkg/controller/job/job_controller.go (hunk 1 above)
Comment (soltysh) [reply pkg/controller/job/job_controller.go]: sgtm

**Comment by soltysh** [comment]
Comments addressed. 
@clamoriniere1A @janetkuo @kow3ns ptal

File: pkg/controller/job/job_controller.go [hunk 2]
```diff
@@ -242,15 +246,19 @@ func (jm *JobController) updatePod(old, cur interface{}) {
 		return
 	}
 
-	labelChanged := !reflect.DeepEqual(curPod.Labels, oldPod.Labels)
+	// the only time we want the backoff to kick-in, is when the pod failed
+	immediate := true
+	if curPod.Status.Phase == v1.PodFailed {
+		immediate = false
+	}
```
Comment (janetkuo) [inline pkg/controller/job/job_controller.go]: nit: 
```go
immediate := curPod.Status.Phase != v1.PodFailed
```

File: pkg/controller/job/job_controller.go [hunk 3]
```diff
@@ -341,15 +350,19 @@ func (jm *JobController) updateJob(old, cur interface{}) {
...
+	key, err := controller.KeyFunc(obj)
 	if err != nil {
-		utilruntime.HandleError(fmt.Errorf("Couldn't get key for object %+v: %v", job, err))
+		utilruntime.HandleError(fmt.Errorf("Couldn't get key for object %+v: %v", obj, err))
 		return
 	}
 
-	// Retrieves the backoff duration for this Job
+	if immediate {
+		jm.queue.Forget(key)
```
Comment (janetkuo) [inline pkg/controller/job/job_controller.go]: Just to confirm, this will cause `backoff == time.Duration(0)`, right?

File: pkg/controller/job/job_controller_test.go [hunk 4]
```diff
@@ -1338,3 +1339,70 @@ func TestJobBackoffReset(t *testing.T) {
...
+			manager.jobStoreSynced = alwaysReady
+			queue := &fakeRateLimitingQueue{}
+			manager.queue = queue
+			sharedInformerFactory.Batch().V1().Jobs().Informer().GetIndexer().Add(job)
+
+			queue.requeues = tc.requeues
+			newPod.Status.Phase = tc.phase
+			manager.updatePod(oldPod, newPod)
+
+			if queue.duration.Nanoseconds() != tc.backoff {
```
Comment (janetkuo) [inline pkg/controller/job/job_controller_test.go]: nit: It's probably simpler to move `DefaultJobBackOff.Nanoseconds()` here

File: pkg/controller/job/job_controller_test.go [hunk 5]
```diff
@@ -1338,3 +1339,70 @@ func TestJobBackoffReset(t *testing.T) {
...
+		// expectation
+		backoff int64
+	}{
+		"1st failure": {0, v1.PodFailed, int64(0) * DefaultJobBackOff.Nanoseconds()},
+		"2nd failure": {1, v1.PodFailed, int64(1) * DefaultJobBackOff.Nanoseconds()},
+		"3rd failure": {2, v1.PodFailed, int64(2) * DefaultJobBackOff.Nanoseconds()},
+		"1st success": {0, v1.PodSucceeded, int64(0) * DefaultJobBackOff.Nanoseconds()},
+		"2nd success": {1, v1.PodSucceeded, int64(0) * DefaultJobBackOff.Nanoseconds()},
+		"1st running": {0, v1.PodSucceeded, int64(0) * DefaultJobBackOff.Nanoseconds()},
+		"2nd running": {1, v1.PodSucceeded, int64(0) * DefaultJobBackOff.Nanoseconds()},
```
Comment (janetkuo) [inline pkg/controller/job/job_controller_test.go]: running cases and success cases are the same?

**Comment by jdumars** [comment]
@janetkuo when satisfied, could you add the LGTM so it ships in 1.10? Thanks!

File: pkg/controller/job/job_controller.go (hunk 3 above)
Comment (soltysh) [reply pkg/controller/job/job_controller.go]: Yes, this will remove the key from the queue which will result in a fresh add with a zero backoff.

File: pkg/controller/job/job_controller_test.go (hunk 5 above)
Comment (soltysh) [reply pkg/controller/job/job_controller_test.go]: Yes they are, but I've decided to put them for clarity :-)

**Comment by soltysh** [comment]
@janetkuo nits addressed, ptal

**Comment by jdumars** [comment]
Hi @janetkuo could you PTAL so we can wrap this up for 1.10? Thanks!

**Review by janetkuo — APPROVED** [review]
