### PR TITLE
show pod Status as phase Failed or Succeeded if it has deletionTimestamp

### LINKED ISSUE #1595: kubectl: Pod with deletionTimestamp shown as Terminating after Failed/Succeeded
### What happened?

A pod with a finalizer and a deletion timestamp is listed as "Terminating" in kubectl get and describe, even after the phase is Failed/Succeeded

### What did you expect to happen?

The phase Failed or Succeeded to be shown

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a long running pod with a finalizer
2. Issue a pod delete
3. Use `kubectl get -o wide` or `kubectl describe` to see the pod.

### Anything else we need to know?

This causes confusion, as the Pod doesn't account for any resource usage when its Failed or Succeeded.
This should be backported to all supported versions.

### Kubernetes version

<details>

master

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### LINKED ISSUE #120207: kubectl: Pod with deletionTimestamp shown as Terminating after Failed/Succeeded
### What happened?

A pod with a finalizer and a deletion timestamp is listed as "Terminating" in kubectl get and describe, even after the phase is Failed/Succeeded

### What did you expect to happen?

The phase Failed or Succeeded to be shown

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a long running pod with a finalizer
2. Issue a pod delete
3. Use `kubectl get -o wide` or `kubectl describe` to see the pod.

### Anything else we need to know?

This causes confusion, as the Pod doesn't account for any resource usage when its Failed or Succeeded.
This should be backported to all supported versions.

### Kubernetes version

<details>

master

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by lowang-bh**
#### What type of PR is this?
/kind bug
/kind cleanup

#### Which issue(s) this PR fixes:
Fixes kubernetes/kubectl#1595

#### Does this PR introduce a user-facing change?
```release-note
kubectl: Show the Pod phase in the STATUS column as 'Failed' or 'Succeeded' when the Pod is terminated
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by lowang-bh** [comment]
Hi, @alculquicondor plz help to review this pr, thanks.

**Review by kannon92 — COMMENTED** [review]
/sig cli

**Comment by alculquicondor** [comment]
I'll defer to the owners of the CLI

File: pkg/printers/internalversion/printers.go [hunk 1]
```diff
@@ -955,6 +956,9 @@ func printPod(pod *api.Pod, options printers.GenerateOptions) ([]metav1.TableRow
 		reason = "Unknown"
 	} else if pod.DeletionTimestamp != nil {
```
Comment (brianpursley) [inline pkg/printers/internalversion/printers.go:957]: Instead of setting the reason to "Terminating" and then changing it back, what about simplifying the if condition to only evaluate to true when the reason should be set to "Terminating", something like this?

```
	} else if pod.DeletionTimestamp != nil && pod.Status.Phase == api.PodRunning {
		reason = "Terminating"
	}
```

**Review by brianpursley — CHANGES_REQUESTED** [review]
Sorry for the delay in reviewing this PR.

We should try to keep the status shown by the printer consistent with what is shown in `kubectl describe`.

Can you make a similar change here, to only show "Terminating" as the status if the pod is running? 

https://github.com/kubernetes/kubernetes/blob/3236891023c991f1b66a49b8c9f6331ed6b4a690/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L814-L815

**Comment by kaisoz** [comment]
I suggest rephrasing the release note (user-facing change) to something like 

`kubectl: Show the Pod phase in the STATUS column as 'Failed' or 'Succeeded' when the Pod is terminated`

since `Terminating` is shown when the pod has a `deletionTimestamp` but its phase is `Running`.  WDYT?

File: pkg/printers/internalversion/printers.go (hunk 1 above)
Comment (brianpursley) [reply pkg/printers/internalversion/printers.go:957]: Already does it here I think:
https://github.com/kubernetes/kubernetes/blob/028b457cb5b5e536f8dc4cdc50bc5a90af294a98/pkg/printers/internalversion/printers.go#L868-L871

At this point in the function, we are overriding the default reason, so there should be no need to set it again.

Comment (kaisoz) [reply pkg/printers/internalversion/printers.go:957]: > Already does it here I think:
> 
> https://github.com/kubernetes/kubernetes/blob/028b457cb5b5e536f8dc4cdc50bc5a90af294a98/pkg/printers/internalversion/printers.go#L868-L871
> 
> At this point in the function, we are overriding the default reason, so there should be no need to set it again.

Ahh missed that, sorry you are right 🤦🏻

Comment (lowang-bh) [reply pkg/printers/internalversion/printers.go:957]: > Instead of setting the reason to "Terminating" and then changing it back, what about simplifying the if condition to only evaluate to true when the reason should be set to "Terminating", something like this?
> 
> ```
> 	} else if pod.DeletionTimestamp != nil && pod.Status.Phase == api.PodRunning {
> 		reason = "Terminating"
> 	}
> ```

I try to change to this and my test assert that pod with `Succeed` phase and a `Completed` container reason didn't show `Succeed`
image

File: pkg/printers/internalversion/printers_test.go [hunk 2]
```diff
@@ -1523,6 +1524,78 @@ func TestPrintPod(t *testing.T) {
...
+							RestartCount: 0,
+							State:        api.ContainerState{Terminated: &api.ContainerStateTerminated{Reason: "Completed", ExitCode: 0}},
+						},
+					},
+				},
+			},
+			[]metav1.TableRow{{Conditions: podSuccessConditions, Cells: []interface{}{"test18", "0/1", "Completed", "0", "<unknown>"}}},
+		},
+		{
+			// Test pod condition running with deletion
```
Comment (mimowo) [inline pkg/printers/internalversion/printers_test.go:1582]: Add an analogous test for a Pending deleted pod.

File: pkg/printers/internalversion/printers.go [hunk 3]
```diff
@@ -953,7 +954,7 @@ func printPod(pod *api.Pod, options printers.GenerateOptions) ([]metav1.TableRow
 
 	if pod.DeletionTimestamp != nil && pod.Status.Reason == node.NodeUnreachablePodReason {
 		reason = "Unknown"
-	} else if pod.DeletionTimestamp != nil {
+	} else if pod.DeletionTimestamp != nil && podPhase == api.PodRunning {
```
Comment (mimowo) [inline pkg/printers/internalversion/printers.go:957]: I'm wondering what the status is in the case of a `Pending`, can we add a test? I think it makes sense to still return `Terminating` . Note that a pending deleted pod may take minutes to be in that state if deleted while pulling a large image.

File: staging/src/k8s.io/kubectl/pkg/describe/describe.go [hunk 4]
```diff
@@ -808,7 +808,7 @@ func describePod(pod *corev1.Pod, events *corev1.EventList) (string, error) {
 		}
 		printLabelsMultiline(w, "Labels", pod.Labels)
 		printAnnotationsMultiline(w, "Annotations", pod.Annotations)
-		if pod.DeletionTimestamp != nil {
+		if pod.DeletionTimestamp != nil && pod.Status.Phase == corev1.PodRunning {
```
Comment (mimowo) [inline staging/src/k8s.io/kubectl/pkg/describe/describe.go:811]: Should we also include Pending here for consistency?

Comment (lowang-bh) [reply staging/src/k8s.io/kubectl/pkg/describe/describe.go]: Done.

File: pkg/printers/internalversion/printers.go (hunk 3 above)
Comment (lowang-bh) [reply pkg/printers/internalversion/printers.go]: Done.

File: staging/src/k8s.io/kubectl/pkg/describe/describe.go [hunk 5]
```diff
@@ -811,7 +811,7 @@ func describePod(pod *corev1.Pod, events *corev1.EventList) (string, error) {
 		}
 		printLabelsMultiline(w, "Labels", pod.Labels)
 		printAnnotationsMultiline(w, "Annotations", pod.Annotations)
-		if pod.DeletionTimestamp != nil {
+		if pod.DeletionTimestamp != nil && (pod.Status.Phase == corev1.PodRunning || pod.Status.Phase == corev1.PodPending) {
```
Comment (mimowo) [inline staging/src/k8s.io/kubectl/pkg/describe/describe.go:814]: Do we have some unit tests for describe we could extend with this change?

File: staging/src/k8s.io/kubectl/pkg/describe/describe_test.go [hunk 6]
```diff
@@ -107,6 +109,49 @@ func TestDescribePod(t *testing.T) {
 	}
 }
 
+func TestDescribePodPhase(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (lowang-bh) [reply staging/src/k8s.io/kubectl/pkg/describe/describe_test.go]: Done.

File: staging/src/k8s.io/kubectl/pkg/describe/describe_test.go [hunk 7]
```diff
@@ -85,25 +85,58 @@ func TestDescribePod(t *testing.T) {
...
+			wantOutput: []string{"pod2", "ns2", "Succeeded"},
+		},
+		{
+			name: "pod3", namespace: "ns3", phase: "Failed",
+			wantOutput: []string{"pod3", "ns3", "Failed"},
+		},
+		{
+			name: "pod4", namespace: "ns4", phase: "Running",
+			wantOutput: []string{"pod4", "ns4", "Terminating (lasts 10y)", "Termination Grace Period", "1234s"},
+		},
```
Comment (mimowo) [inline staging/src/k8s.io/kubectl/pkg/describe/describe_test.go:122]: nit: the test case seems conceptually as the test case 1. Can we just extend asserts for test case 1?

File: pkg/printers/internalversion/printers.go [hunk 8]
```diff
@@ -988,7 +989,7 @@ func printPod(pod *api.Pod, options printers.GenerateOptions) ([]metav1.TableRow
 
 	if pod.DeletionTimestamp != nil && pod.Status.Reason == node.NodeUnreachablePodReason {
 		reason = "Unknown"
-	} else if pod.DeletionTimestamp != nil {
+	} else if pod.DeletionTimestamp != nil && (podPhase == api.PodRunning || podPhase == api.PodPending) {
```
Comment (mimowo) [inline pkg/printers/internalversion/printers.go:992]: nit: can we use `!util.IsPodPhaseTerminal` [here](https://github.com/kubernetes/kubernetes/blob/9e2075b3c87061d25759b0ad112266f03601afd8/pkg/api/v1/pod/util.go#L317)? This will better reflect the intention and simplify the code, but maybe there is some issue with using the package form kubectl (not sure, to be tested).

File: staging/src/k8s.io/kubectl/pkg/describe/describe.go (hunk 5 above)
Comment (mimowo) [inline staging/src/k8s.io/kubectl/pkg/describe/describe.go:814]: Same, could we use `!util.IsPodPhaseTerminal` [here](https://github.com/kubernetes/kubernetes/blob/9e2075b3c87061d25759b0ad112266f03601afd8/pkg/api/v1/pod/util.go#L317)?

**Review by mimowo — COMMENTED** [review]
LGTM, two remaining nits

File: staging/src/k8s.io/kubectl/pkg/describe/describe.go (hunk 5 above)
Comment (lowang-bh) [reply staging/src/k8s.io/kubectl/pkg/describe/describe.go:814]: `!util.IsPodPhaseTerminal` is not just `PodRunning` or `PodPending`, is that ok?

Comment (mimowo) [reply staging/src/k8s.io/kubectl/pkg/describe/describe.go:814]: It only differs by the Unknown which is depracated for a long time already: https://github.com/kubernetes/kubernetes/blob/c8a51aaffc94da6e7a66d8984890d3111e361a54/pkg/apis/core/types.go#L2777-L2793, so I wouldn't worry about it, and would prefer keeping the code simple.

File: staging/src/k8s.io/kubectl/pkg/describe/describe_test.go (hunk 7 above)
Comment (lowang-bh) [reply staging/src/k8s.io/kubectl/pkg/describe/describe_test.go]: Done

**Comment by mimowo** [comment]
@lowang-bh please investigate the issue with the pull-kubernetes-dependencies build, if there is some deeper issue I'm ok with replicating this function locally, but maybe there is a quick fix.

**Comment by mimowo** [comment]
@lowang-bh I consulted the build issue with @deads2k and we cannot add dependency from the staging area to k/k. Please create the local copy of the function, but lowercase to do not export if not needed.

**Review by mimowo — COMMENTED** [review]
/lgtm
Thanks!

File: staging/src/k8s.io/kubectl/pkg/describe/util.go [hunk 9]
```diff
@@ -0,0 +1,25 @@
...
+limitations under the License.
+*/
+
+package describe
+
+import v1 "k8s.io/api/core/v1"
+
+// IsPodPhaseTerminal returns true if the pod's phase is terminal.
+// copied from k8s.io/kubernetes/pkg/api/v1/pod
+func isPodPhaseTerminal(phase v1.PodPhase) bool {
```
Comment (ardaguclu) [inline staging/src/k8s.io/kubectl/pkg/describe/util.go:23]: I think, we don't need this new package. It is only used by one place in `describe` and the logic is pretty simple. What about;

```go
if pod.DeletionTimestamp != nil && phase != v1.PodFailed && phase != v1.PodSucceeded {
```

**Review by ardaguclu — COMMENTED** [review]
Overall looks good to me. Dropped one comment. I'd like to have another review from @brianpursley, when he has a chance.

File: staging/src/k8s.io/kubectl/pkg/describe/util.go (hunk 9 above)
Comment (lowang-bh) [reply staging/src/k8s.io/kubectl/pkg/describe/util.go:23]: The original code is `if pod.DeletionTimestamp != nil && (pod.Status.Phase == corev1.PodRunning || pod.Status.Phase == corev1.PodPending) ` and @mimowo think it is not simple enougth. You can check that in comments.

Comment (mimowo) [reply staging/src/k8s.io/kubectl/pkg/describe/util.go:23]: I was rather exploring other options, I like the proposal `&& phase != v1.PodFailed && phase != v1.PodSucceeded`. We can also employ it in the other place.

Comment (ardaguclu) [reply staging/src/k8s.io/kubectl/pkg/describe/util.go:23]: As `printers` can access `"k8s.io/kubernetes/pkg/api/v1/pod"`, it is better to use it as is.

Comment (lowang-bh) [reply staging/src/k8s.io/kubectl/pkg/describe/util.go:23]: > As `printers` can access `"k8s.io/kubernetes/pkg/api/v1/pod"`, it is better to use it as is.

 CI `pull-kubernetes-dependencies` will failed.  `"k8s.io/kubernetes/pkg/api/v1/pod"` is only used under `/pkg/` dir. There is also a internal package in `staging/src/k8s.io/endpointslice/util/controller_utils.go`

Comment (ardaguclu) [reply staging/src/k8s.io/kubectl/pkg/describe/util.go:23]: I'm just saying that the current code changes in this PR for `pkg/printers/internalversion/printers.go` is ok

Comment (ardaguclu) [reply staging/src/k8s.io/kubectl/pkg/describe/util.go:23]: @lowang-bh once we remove this staging/src/k8s.io/kubectl/pkg/describe/util.go file and use it inline, I think we are ready to go?

Comment (lowang-bh) [reply staging/src/k8s.io/kubectl/pkg/describe/util.go]: done.

**Review by mimowo — COMMENTED** [review]
/lgtm

**Comment by ardaguclu** [comment]
Thank you
/approve
