### PR TITLE
Use TCP instead of ICMP to check outbound connectivity

### LINKED ISSUE #75172: Network internet test for pod fails on azure
**Which jobs are failing**:
N/A
**Which test(s) are failing**:
```
[sig-network] Networking should provide Internet connection for containers [Feature:Networking-IPv4]
```
**Since when has it been failing**:
Ever
**Reason for failure**:
Vm on Azure with no public IP assigned aren't able to perform a `ping` command to the internet.

**Anything else we need to know**:
```golang
It("should provide Internet connection for containers [Feature:Networking-IPv4]", func() {
	By("Running container which tries to ping 8.8.8.8")
	framework.ExpectNoError(
	framework.CheckConnectivityToHost(f, "", "ping-test", "8.8.8.8", framework.IPv4PingCommand, 30))
})
```
The test (see [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/networking.go#L48)) tries to test the internet connection for a pod by pinging 8.8.8.8. 
But azure does not provide ICMP support for VM without a public IP therefore this test cannot succeed.(see [Azure docs](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections))

A fix would be to change the test method to a tcp request instead of a ping request (the test already performs a http get to google.com in its BeforeSuite (see [here](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/networking.go#L38)))
```golang
BeforeEach(func() {
	// Assert basic external connectivity.
	// Since this is not really a test of kubernetes in any way, we
	// leave it as a pre-test assertion, rather than a Ginko test.
	By("Executing a successful http request from the external internet")
	resp, err := http.Get("http://google.com")
	if err != nil {
		framework.Failf("Unable to connect/talk to the internet: %v", err)
	}
	if resp.StatusCode != http.StatusOK {
		framework.Failf("Unexpected error code, expected 200, got, %v (%v)", resp.StatusCode, resp)
	}
})
```

### PR DESCRIPTION
**Pull request by saiyan86**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation

/kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR updates the networking e2e test on Azure to use ```nc``` instead of ```ping``` for IPv4 tests. This is because Azure's LB drops ICMP packets for security reasons. 

**Which issue(s) this PR fixes**:

Fixes #75172

**Special notes for your reviewer**:

This PR only includes fix for IPv4 test, because the current busybox image doesn't have ```nc``` support for IPv6. Will prepare an image with ```nc``` support for IPv6 and update the rest tests in the future.

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by feiskyer — COMMENTED** [review]
Since ping is not supported for Azure LB ips, the change is required for running those tests on Azure

/lgtm

**Comment by saiyan86** [comment]
sig/network

**Comment by saiyan86** [comment]
@bowei Could you please take a look? You wrote the original tests 😄

File: test/e2e/network/networking.go [hunk 1]
```diff
@@ -47,14 +47,21 @@ var _ = SIGDescribe("Networking", func() {
...
 	ginkgo.It("should provide Internet connection for containers [Feature:Networking-IPv4]", func() {
 		ginkgo.By("Running container which tries to ping 8.8.8.8")
-		framework.ExpectNoError(
-			framework.CheckConnectivityToHost(f, "", "ping-test", "8.8.8.8", framework.IPv4PingCommand, 30))
+		if !framework.ProviderIs("azure") {
+			framework.ExpectNoError(
+				framework.CheckConnectivityToHost(f, "", "ping-test", "8.8.8.8", framework.IPv4PingCommand, 30))
+		} else {
+			framework.ExpectNoError(
+				framework.CheckConnectivityToHost(f, "", "ping-test", "8.8.8.8", framework.IPv4NcCommand, 30))
```
Comment (bowei) [inline test/e2e/network/networking.go]: seems complex to have the ProviderIs("azure") logic in two places. Is it possible to make it so that is all encapsulated in CheckConnectivityToHost?

Comment (saiyan86) [reply test/e2e/network/networking.go]: This is just for readability. I pass in ```framework.IPv4NcCommand``` here so that ppl will know the actual command being used without checking ```framework.CheckConnectivityToHost```. But I can certainly put them altogether in ```framework.CheckConnectivityToHost```. What do you think?

File: test/e2e/framework/util.go [hunk 2]
```diff
@@ -4447,12 +4449,22 @@ const (
...
+		command = []string{
+			string(pingCmd),
+			"-c", "3", // send 3 pings
+			"-W", "2", // wait at most 2 seconds for a reply
+			"-w", strconv.Itoa(timeout),
+			host,
+		}
+	} else {
+		command = []string{
+			string(pingCmd),
```
Comment (andrewsykim) [inline test/e2e/framework/util.go]: This pattern seems really awkward to me. We're passing in a generic `PingCommand` type but we are then trying to pass in differing arguments into it.

File: test/e2e/framework/util.go [hunk 3]
```diff
@@ -4438,6 +4438,8 @@ const (
 	IPv4PingCommand PingCommand = "ping"
 	// IPv6PingCommand is a ping command for IPv6.
 	IPv6PingCommand PingCommand = "ping6"
+	// IPv4NcCommand is a nc command for IPv4
+	IPv4NcCommand PingCommand = "nc"
```
Comment (andrewsykim) [inline test/e2e/framework/util.go]: `nc` is not a ping command, does it belong in this type?

File: test/e2e/network/networking.go (hunk 1 above)
Comment (andrewsykim) [reply test/e2e/network/networking.go]: Agreed with @bowei, maybe a function (e.g. connectivtyCommand) and pass the returned slice of strings representing commands into `CheckConnectivityToHost` instead of trying to fit `nc` into `PingCommand`. Thoughts?

File: test/e2e/framework/util.go (hunk 2 above)
Comment (saiyan86) [reply test/e2e/framework/util.go]: I encaped all implementation details in ```CheckConnectivityToHost``` now.

File: test/e2e/network/networking.go (hunk 1 above)
Comment (saiyan86) [reply test/e2e/network/networking.go]: I encaped all implementation details in ```CheckConnectivityToHost``` now. Thanks for the comments!

File: test/e2e/framework/util.go (hunk 3 above)
Comment (saiyan86) [reply test/e2e/framework/util.go]: Separated it out.

File: test/e2e/framework/util.go [hunk 4]
```diff
@@ -4442,19 +4452,44 @@ const (
...
+	// IPv4NcCommand is a nc command for IPv4
+	IPv4NcCommand NcCommand = "nc"
+)
+
 // CheckConnectivityToHost launches a pod to test connectivity to the specified
 // host. An error will be returned if the host is not reachable from the pod.
 //
 // An empty nodeName will use the schedule to choose where the pod is executed.
-func CheckConnectivityToHost(f *Framework, nodeName, podName, host string, pingCmd PingCommand, timeout int) error {
+func CheckConnectivityToHost(f *Framework, nodeName, podName, host string, ipProto IPProtocol, timeout int) error {
```
Comment (andrewsykim) [inline test/e2e/framework/util.go]: I don't think it makes sense for framework functions to have `IsProvider` checks. It makes reasoning about the e2e test unless you peak into the implementation details of `CheckConnectivityToHost`.  I think it would be cleaner if we just had two separate e2e tests, the existing one can just be skipped for Azure and the new one only runs for Azure (and possibly future providers that also block ICMP).

Comment (andrewsykim) [reply test/e2e/framework/util.go]: With that said, I would also prefer to avoid `ProviderIs` checks in the e2e code base _if possible_, we're already trying to decouple provider code from e2e tests (https://github.com/kubernetes/kubernetes/issues/75604) and adding more checks like this adds more friction on that effort.

Comment (saiyan86) [reply test/e2e/framework/util.go]: @bowei What's your input on this? For #75604 I think it makes sense but I don't want to be blocked on that just yet. Once we have a solution for #75604 I can always follow the new pattern and change this.

Comment (saiyan86) [reply test/e2e/framework/util.go]: @andrewsykim Can you suggest a way to change this? This change is suggested by @bowei . I'd like to make the change after we all agree on the solution...

Comment (bowei) [reply test/e2e/framework/util.go]: That is a good point about keeping things provider agnostic in the framework if possible.

It would be a bigger effort, but ideally you would have a provider agnostic tools interface (e.g. with Ping(), etc) and the test would inject a provider specific "tools" struct to handle these callouts.
That would be the way I'd go, to keep things contained and easier to reason about.

Comment (feiskyer) [reply test/e2e/framework/util.go]: @bowei good idea, but it's still a long way to that. Another interface or framework is required.

Before that, what do you suggest for workarounds? `ProviderIs` is still the easiest way, right?

Comment (saiyan86) [reply test/e2e/framework/util.go]: @bowei I think we should bring your idea up in the next sig-testing/sig-network meeting and break the problem down. But getting that done may take weeks to months. I'd prefer to have a workaround for now and cleanup everything gradually once everybody gets assigned a piece of work. What do you think?

Comment (andrewsykim) [reply test/e2e/framework/util.go]: The `ProviderIs` check is fine IMO, it's where we do the check that is problematic I think. It's cleaner to do to have two separate functions in this case, `CheckICMPConnectivityToHost` and `CheckTCPConnectivityToHost` and vary the call based on the provider from the test (`test/e2e/network/networking.go`) not the framework itself.

Comment (saiyan86) [reply test/e2e/framework/util.go]: @andrewsykim I agree. That's exactly what I was thinking when I did the first commit. I'll wait for @bowei and @feiskyer 's input on this.

Comment (thockin) [reply test/e2e/framework/util.go]: Why do we need a provider test?  Can we just switch to NC for everyone?

Comment (saiyan86) [reply test/e2e/framework/util.go]: That'd be the cleanest solution!! I just don't know if you guys would be OK with it. If so, I'll just switch to NC for everyone.

Comment (andrewsykim) [reply test/e2e/framework/util.go]: The value of ping test is being able to validate that the LB is reachable regardless of the backend state. I see value in having both cases test but nc working would have overlapping validations with ping.

File: test/e2e/network/networking.go [hunk 5]
```diff
@@ -48,13 +48,13 @@ var _ = SIGDescribe("Networking", func() {
 	ginkgo.It("should provide Internet connection for containers [Feature:Networking-IPv4]", func() {
 		ginkgo.By("Running container which tries to ping 8.8.8.8")
 		framework.ExpectNoError(
-			framework.CheckConnectivityToHost(f, "", "ping-test", "8.8.8.8", framework.IPv4PingCommand, 30))
+			framework.CheckConnectivityToHost(f, "", "ping-test", "8.8.8.8", framework.IPv4, 30))
```
Comment (andrewsykim) [inline test/e2e/network/networking.go]: In the description you mentioned:

>This PR updates the networking e2e test on Azure to use nc instead of ping for IPv4 tests. This is because Azure's LB drops ICMP packets for security reasons.

But this test is only validating that pod inside the cluster can ping an external IP, nothing goes through LB unless I'm missing something

**Comment by thockin** [comment]
I don't think it's reasonable to assume ICMP will always work.  If we can
use TCP instead, I think we'd be better.  Am I missing something?

**Comment by andrewsykim** [comment]
I'm assuming that `nc` would break for an LB with no valid backends yet, would that break some tests? maybe? Just something to consider. 

I'm also realizing now that this PR is not actually changing any LB tests, it's only testing pod -> external IP connectivity in which case I don't see the difference in using ICMP or TCP.

File: test/e2e/network/networking.go (hunk 5 above)
Comment (andrewsykim) [reply test/e2e/network/networking.go]: Oh, is it because you want to use `CheckConnectivityToHost` in your custom Azure tests? Can you just create a new method local to your tests in that case?

**Comment by saiyan86** [comment]
Exactly. This PR is only testing pod -> external IP connectivity. Also, @thockin has a valid point. TCP should be supported all the time, but we can't assume the same for ICMP.

**Comment by andrewsykim** [comment]
Gotcha. For the LB case I agree that we can't assume ICMP will work (not sure why I thought this was an LB test in the first place). For connectivity from pod ->  external, ICMP is much more common, especially something like 8.8.8.8 like we're testing here. With the current state of the PR using nc, we're also harding coding the port/protocol which is not any better IMO. We can pass in all the necessary parameters (protocol and port) but that's not as simple as just passing in the address. Just my 2 cents, in the end I don't think it changes the test behavior all that much. Will defer to Tim :)

**Comment by thockin** [comment]
Now I am confused.  The PR comment says "Azure's LB drops ICMP", but this test is only testing external connectivity via ping, nothing to do with LBs.

So why are we making this change?

Also agree that if we change this anyway, we should pass the host and port number.

**Comment by saiyan86** [comment]
> Now I am confused. The PR comment says "Azure's LB drops ICMP", but this test is only testing external connectivity via ping, nothing to do with LBs.
> 
> So why are we making this change?
> 
> Also agree that if we change this anyway, we should pass the host and port number.

Azure LB drops ICMP packets for both inbound and outbound connections. Therefore this PR uses ```nc``` instead of ```ping```.  [Use port pings instead of ICMP to test Azure VM connectivity](https://blogs.msdn.microsoft.com/mast/2014/06/22/use-port-pings-instead-of-icmp-to-test-azure-vm-connectivity/)

**Comment by saiyan86** [comment]
@thockin any idea?

**Comment by saiyan86** [comment]
@thockin ping

**Comment by andrewsykim** [comment]
Need clarification for "Azure LB drops ICMP packets". I have a feeling that "Azure LB" is not the term we are used to when referring to other environments. My initial thoughts were that it is an L4 load balancer for clusters (i.e. when using `Service Type=LoadBalancer`) but it seems in the Azure case it is actually a VM proxy for all ingress/egress traffic. Is that assumption correct?

**Comment by saiyan86** [comment]
> Need clarification for "Azure LB drops ICMP packets". I have a feeling that "Azure LB" is not the term we are used to when referring to other environments. My initial thoughts were that it is an L4 load balancer for clusters (i.e. when using `Service Type=LoadBalancer`) but it seems in the Azure case it is actually a VM proxy for all ingress/egress traffic. Is that assumption correct?

It's called Azure Software Load Balancer, equivalent to AWS's ELB/GCP's CLB.

**Comment by andrewsykim** [comment]
> It's called Azure SLB(Software Load Balancer), equivalent to AWS's ELB/GCP's CLB.

The test this PR changes doesn't test AWS ELB or GCP CLB though, this is external connectivity from a VM only.

**Comment by saiyan86** [comment]
> > It's called Azure SLB(Software Load Balancer), equivalent to AWS's ELB/GCP's CLB.
> 
> The test this PR changes doesn't test AWS ELB or GCP CLB though, this is external connectivity from a node (i.e. Azure VM) only.

That‘s exactly why I have ```ProviderIs("azure")``` in the first place.

**Comment by andrewsykim** [comment]
That was the source of confusion, you are referring to AWS ELB & GCP CLB but this test doesn't touch that regardless of protocol :)

**Comment by saiyan86** [comment]
> That was the source of confusion, you are referring to AWS ELB & GCP CLB but this test doesn't touch that regardless of protocol :)

Let me summarize the purpose of this change here.
Without this change, the outbound connectivity test on Azure uses ICMP, which is dropped by SLB. This makes the test fails on Azure all the time. This change is proposed only to address this problem. By using ```nc```, it uses TCP instead of ICMP, and Azure SLB will permit such traffic and let the test pass.

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/pull/79243 - can you please coordinate?

File: test/e2e/framework/util.go (hunk 4 above)
Comment (johnbelamaric) [reply test/e2e/framework/util.go]: I don't think we want to use `nc` because IIRC it does not exist for Windows hosts. We should use the agnhost image, proably, with either `curl` or a new Go-based command that makes an HTTP connection. This will avoid all platform and provider-specific issues.

**Comment by johnbelamaric** [comment]
@saiyan86 as mentioned I don't think `nc` is available in Windows containers so let's use `curl` or a new command to agnhost, I think that would be cleanest. This is what we do for conformance tests (though this will never be one because at least for now Internet access is not allowed for those).

See https://github.com/kubernetes/kubernetes/tree/master/test/images/agnhost

**Comment by saiyan86** [comment]
> @saiyan86 as mentioned I don't think `nc` is available in Windows containers so let's use `curl` or a new command to agnhost, I think that would be cleanest. This is what we do for conformance tests (though this will never be one because at least for now Internet access is not allowed for those).
> 
> See https://github.com/kubernetes/kubernetes/tree/master/test/images/agnhost

Thanks for bringing this up. ```nettest``` from ```agnhost``` seems to be the right tool for this. I'll take a look a prepare a new commit with ```agnhost```.

**Comment by aojea** [comment]
@saiyan86 I think that this can benefit from the IP family detection mechanism once it merges to avoid using labels on the text description
https://github.com/kubernetes/kubernetes/pull/80398

File: test/e2e/framework/util.go [hunk 6]
```diff
@@ -4432,6 +4432,16 @@ func getKubeletPods(c clientset.Interface, node, resource string) (*v1.PodList,
 	return result, nil
 }
 
+// IPProtocol is the type to hold IP protocol.
+type IPProtocol string
```
Comment (aojea) [inline test/e2e/framework/util.go]: We don´t need this if we merge https://github.com/kubernetes/kubernetes/pull/80398/

File: test/e2e/framework/util.go [hunk 7]
```diff
@@ -4442,19 +4452,44 @@ const (
 	IPv6PingCommand PingCommand = "ping6"
 )
 
+// NcCommand is the type to hold nc command
+type NcCommand string
+
+const (
+	// IPv4NcCommand is a nc command for IPv4
+	IPv4NcCommand NcCommand = "nc"
```
Comment (aojea) [inline test/e2e/framework/util.go]: the nc version included in `agnhost` support both IPv4 and IPv6

File: test/e2e/framework/util.go [hunk 8]
```diff
@@ -4442,19 +4452,44 @@ const (
...
+			"-W", "2", // wait at most 2 seconds for a reply
+			"-w", strconv.Itoa(timeout),
+			host,
+		}
+		if ipProto == IPv6 {
+			command[0] = string(IPv6PingCommand)
+		}
+	} else {
+		command = []string{
+			string(IPv4NcCommand),
```
Comment (aojea) [inline test/e2e/framework/util.go]: the nc command included in agnhost will work for ipv4 and ipv6

File: test/e2e/framework/util.go (hunk 6 above)
Comment (saiyan86) [reply test/e2e/framework/util.go]: That'd be great

File: test/e2e/framework/util.go (hunk 7 above)
Comment (saiyan86) [reply test/e2e/framework/util.go]: Got it. Will use ```nc``` from ```agnhost```.

File: test/e2e/framework/util.go (hunk 4 above)
Comment (aojea) [reply test/e2e/framework/util.go]: agnhost has both nc and curl commands

File: test/e2e/framework/util.go (hunk 6 above)
Comment (aojea) [reply test/e2e/framework/util.go]: it was merged , you can use `framework.TestContext.IPFamily`

**Comment by saiyan86** [comment]
@johnbelamaric Could you please take a look? This tests are updated to use ```agnhost``` image.

File: test/e2e/framework/util.go (hunk 6 above)
Comment (saiyan86) [reply test/e2e/framework/util.go]: Is it OK to assume ```framework.TestContext.IPFamily``` is always set to either ```ipv4``` or ```ipv6```?

File: test/e2e/framework/util.go [hunk 9]
```diff
@@ -208,6 +208,9 @@ var (
 	// BusyBoxImage is the image URI of BusyBox.
 	BusyBoxImage = imageutils.GetE2EImage(imageutils.BusyBox)
 
+	// AgnHostImage is the image URI of AgnHost
+	AgnHostImage = imageutils.GetE2EImage(imageutils.Agnhost)
```
Comment (johnbelamaric) [inline test/e2e/framework/util.go]: Why do we need a var for this? it's only used once

**Review by johnbelamaric — CHANGES_REQUESTED** [review]
There is no need for a type for the command, just seems to add complexity for no real reason. I understand you were following the ping example, but that looks questionable to me in any case. From what I can tell, ping is no longer used after this PR merges. So everything related to it should just be stripped out. Also there is no real need for a var for AgnhostImage if you are just using it once, just use the value directly.

File: test/e2e/framework/util.go (hunk 9 above)
Comment (saiyan86) [reply test/e2e/framework/util.go]: It was used in multiple places. I replaced them all with this var

File: test/e2e/framework/util.go [hunk 10]
```diff
@@ -474,7 +475,7 @@ func ProxyMode(f *Framework) (string, error) {
 			Containers: []v1.Container{
 				{
 					Name:    "detector",
-					Image:   imageutils.GetE2EImage(imageutils.Agnhost),
+					Image:   AgnHostImage,
 					Command: []string{"/bin/sleep", "3600"},
```
Comment (aojea) [inline test/e2e/framework/util.go]: `agnhost` image seems to have a `pause` command for this purpose, instead using sleep https://github.com/kubernetes/kubernetes/tree/master/test/images/agnhost#pause

File: test/e2e/framework/util.go [hunk 11]
```diff
@@ -2876,29 +2877,32 @@ func UnblockNetwork(from string, to string) {
...
 	contName := fmt.Sprintf("%s-container", podName)
 
-	command := []string{
-		string(pingCmd),
-		"-c", "3", // send 3 pings
-		"-W", "2", // wait at most 2 seconds for a reply
-		"-w", strconv.Itoa(timeout),
-		host,
+	var command []string
+	if TestContext.IPFamily == "ipv4" {
```
Comment (aojea) [inline test/e2e/framework/util.go]: I think that we don´t need to differentiate here, nc seems to work for both families, no need to specify -6 as a parameter, at least in my tests

```
/ # nc -vz -w 2 2001:db8:1::1 22
Connection to 2001:db8:1::1 22 port [tcp/ssh] succeeded!
/ # nc -vz -w 2 172.17.0.1 22
Connection to 172.17.0.1 22 port [tcp/ssh] succeeded!
```

However, if you still want to differentiate I suggest to not rely in the TestContext.IPFamily here, and use the `host string` to detect the IP family, i.e using this function https://github.com/kubernetes/utils/blob/6c36bc71fc4aeb1f49801054e71aebdaef1fbeb4/net/net.go#L119

Comment (saiyan86) [reply test/e2e/framework/util.go]: Thanks! I already combined the two commands together.

File: pkg/kubelet/util/sliceutils/sliceutils.go [hunk 12]
```diff
@@ -53,6 +53,9 @@ func (s PodsByCreationTime) Less(i, j int) bool {
 type ByImageSize []kubecontainer.Image
 
 func (a ByImageSize) Less(i, j int) bool {
+	if a[i].Size == a[j].Size {
```
Comment (aojea) [inline pkg/kubelet/util/sliceutils/sliceutils.go]: just curious, why is this needed?

File: test/e2e/framework/util.go (hunk 6 above)
Comment (aojea) [reply test/e2e/framework/util.go]: is it right now, but it can change if we want to consider `dual-stack` as an IPFamily, I would be conservative and don assume it

File: pkg/kubelet/util/sliceutils/sliceutils.go (hunk 12 above)
Comment (saiyan86) [reply pkg/kubelet/util/sliceutils/sliceutils.go]: Oh it seems to be a mistake in the merging process. Thanks for pointing it out.

**Comment by johnbelamaric** [comment]
I'm not sure it's a good idea to change all the references to `framework.ServeHostnameImage`, rather than just changing that constant to refer to agnhost. But I'll defer someone from the framework side for that.

**Comment by saiyan86** [comment]
> I'm not sure it's a good idea to change all the references to `framework.ServeHostnameImage`, rather than just changing that constant to refer to agnhost. But I'll defer someone from the framework side for that.

Removed those parts. Will submit another PR if needed.

**Comment by johnbelamaric** [comment]
/remove-area apiserver cloudprovider code-generation dependency ipvs kubeadm kubectl kubelet release-eng
/remove-kind api-change
/remove-sig api-machinery apps cli cloud-provider cluster-lifecycle instrumentation node release scheduling storage

**Comment by johnbelamaric** [comment]
/approve
for networking but someone else needs to do framework

**Comment by saiyan86** [comment]
@andrewsykim Could you please take a look? Thanks!

File: test/e2e/framework/util.go [hunk 13]
```diff
@@ -2876,29 +2879,19 @@ func UnblockNetwork(from string, to string) {
...
-func CheckConnectivityToHost(f *Framework, nodeName, podName, host string, pingCmd PingCommand, timeout int) error {
+func CheckConnectivityToHost(f *Framework, nodeName, podName, host string, port, timeout int) error {
 	contName := fmt.Sprintf("%s-container", podName)
 
 	command := []string{
-		string(pingCmd),
-		"-c", "3", // send 3 pings
-		"-W", "2", // wait at most 2 seconds for a reply
+		"nc",
+		"-vz",
```
Comment (oomichi) [inline test/e2e/framework/util.go]: `-u` option is not specified, so TCP is always used instead of ICMP and UDP, right?

**Review by oomichi — COMMENTED** [review]
Most part is good for me, just few questions.

File: test/e2e/framework/util.go [hunk 14]
```diff
@@ -474,8 +477,8 @@ func ProxyMode(f *Framework) (string, error) {
 			Containers: []v1.Container{
 				{
 					Name:    "detector",
-					Image:   imageutils.GetE2EImage(imageutils.Agnhost),
-					Command: []string{"/bin/sleep", "3600"},
+					Image:   AgnHostImage,
+					Command: []string{"pause"},
```
[the remark this answers is not in the document]
Comment (saiyan86) [reply test/e2e/framework/util.go]: The ```AgnHostImage``` has this [```pause```](https://github.com/kubernetes/kubernetes/tree/master/test/images/agnhost#pause) binary specifically for this.

[the remark this answers is not in the document]
Comment (saiyan86) [reply test/e2e/framework/util.go]: **pause**
It will pause the execution of the binary. This can be used for containers which have to be kept in a Running state for various purposes, including executing other agnhost commands.

Usage:

    kubectl exec test-agnhost -- /agnhost pause

File: test/e2e/framework/util.go (hunk 13 above)
Comment (saiyan86) [reply test/e2e/framework/util.go]: Yes. By default is TCP.

File: test/e2e/framework/util.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (oomichi) [reply test/e2e/framework/util.go]: I got it, thanks for your explanation.

File: test/e2e/framework/util.go (hunk 13 above)
Comment (oomichi) [reply test/e2e/framework/util.go]: Then the PR title should be `Use TCP instead of ICMP to check outbound connectivity` without `UDP`.

Comment (saiyan86) [reply test/e2e/framework/util.go]: Thanks for the suggestion. I have changed the PR title. Will submit another PR is UDP is needed later.

**Comment by oomichi** [comment]
Thanks for updating

/approve
