### PR TITLE
check the job owner reference in the cronjob reconcile loop

### LINKED ISSUE #120181: job executions started manually for a cronjob are marked as unexpected
### What happened?

We have a custom resource with a name - `Foo`
We have a CronJob named - `Foo`

Now, we have a job whose owner refernce is set to the custom resource name - `Foo`. We have noticed that the job when stopped (suspended) basically causes an event/warning - "[UnexpectedJob](https://github.com/kubernetes/kubernetes/blob/8b132ea40a250e9acf08ab2fadb9a8c2fd811d74/pkg/controller/cronjob/cronjob_controllerv2.go#L444C39-L444C55)" for the given job execution.

[syncCronJob](https://github.com/kubernetes/kubernetes/blob/8b132ea40a250e9acf08ab2fadb9a8c2fd811d74/pkg/controller/cronjob/cronjob_controllerv2.go#L422C25-L422C36) is trying to reconcile the job because it thinks that it is owned by the CronJob. Probably because of "[getJobsToBeReconciled](https://github.com/kubernetes/kubernetes/blob/8b132ea40a250e9acf08ab2fadb9a8c2fd811d74/pkg/controller/cronjob/cronjob_controllerv2.go#L252C25-L252C46)", at this [line](https://github.com/kubernetes/kubernetes/blob/8b132ea40a250e9acf08ab2fadb9a8c2fd811d74/pkg/controller/cronjob/cronjob_controllerv2.go#L264C3-L264C110).

### What did you expect to happen?

The `syncCronJob` should not try to reconcile the job because it is not owned by the CronJob. 

**Proposed Solution**: [syncCronJob](https://github.com/kubernetes/kubernetes/blob/8b132ea40a250e9acf08ab2fadb9a8c2fd811d74/pkg/controller/cronjob/cronjob_controllerv2.go#L422C25-L422C36) should not reconcile the job, since it is owned by the CronJob. The `getJobsToBeReconciled` method should match the `name` and the `kind` of the job. The `kind` in the case of a cronjob would be `CronJob`.

### How can we reproduce it (as minimally and precisely as possible)?

- Run a job execution using the same CRD used to create a cronjob.
- Once the job execution starts, stop (suspend) it.
- We would start getting events of type `Warning` with reason - `UnexpectedJob`.
- Stop a job execution that was triggered due to the cronjob itself and we would not see warnings for this stopped job execution.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"08d3594304660f86cfbd17bbb862041b4b75fe6c", GitTreeState:"clean", BuildDate:"2023-02-08T17:22:59Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
N\A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by kei01234kei**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Because the cronjob controller needs to check the owner reference of the job to fix #120181 .
#### Which issue(s) this PR is related to:
Fixes #120181 

#### Does this PR introduce a user-facing change?

```release-note
Fixed the wrong cause of the UnexpectedJob event/warning by checking the owner reference of the job correctly in the cron job controller.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/cronjob/cronjob_controllerv2.go [hunk 1]
```diff
@@ -262,10 +262,16 @@ func (jm *ControllerV2) getJobsToBeReconciled(cronJob *batchv1.CronJob) ([]*batc
...
 	for _, job := range jobList {
 		// If it has a ControllerRef, that's all that matters.
-		if controllerRef := metav1.GetControllerOf(job); controllerRef != nil && controllerRef.Name == cronJob.Name {
-			// this job is needs to be reconciled
-			jobsToBeReconciled = append(jobsToBeReconciled, job)
+		controllerRef := metav1.GetControllerOf(job)
+		if controllerRef == nil {
+			continue
+		}
+		refedCronJob := jm.resolveControllerRef(job.Namespace, controllerRef)
```
Comment (atiratree) [inline pkg/controller/cronjob/cronjob_controllerv2.go]: @kei01234kei thanks for picking this issue again.

FYI, from my last [review](https://github.com/kubernetes/kubernetes/pull/120184#discussion_r1352558833):

> the name of the cronjob has to be taken into account. Please add tests that have multiple cronjobs in the store to be sure we are not filtering jobs of other cronjobs in this place

We could also approach this problem differently. It might be better to use an indexer. It would be a bit similar to what we did in Jobs:  https://github.com/kubernetes/kubernetes/pull/132305

**Review by atiratree — COMMENTED** [review]
/triage accepted
/priority backlog
/ok-to-test

File: pkg/controller/cronjob/cronjob_controllerv2.go (hunk 1 above)
Comment (kei01234kei) [reply pkg/controller/cronjob/cronjob_controllerv2.go]: > We could also approach this problem differently. It might be better to use an indexer. It would be a bit similar to what we did in Jobs: https://github.com/kubernetes/kubernetes/pull/132305

The idea of using the indexer to find jobs to be reconciled is good! Thank you for telling me that.
We no longer need to use `List(labels.Everything())`, which puts a load on etcd.
I modified the code.
[use indexer to get jobs to be reconciled](https://github.com/kubernetes/kubernetes/pull/133313/commits/9265457156e7613c134f73a109fc0d552701bb2c)

File: pkg/controller/cronjob/cronjob_controllerv2.go [hunk 2]
```diff
@@ -229,6 +252,23 @@ func (jm *ControllerV2) sync(ctx context.Context, cronJobKey string) (*time.Dura
 	return nil, syncErr
 }
 
+func (jm *ControllerV2) getCronJobJobsByIndexer(cronJob *batchv1.CronJob) ([]*batchv1.Job, error) {
+	jobsForCronJob := []*batchv1.Job{}
```
Comment (atiratree) [inline pkg/controller/cronjob/cronjob_controllerv2.go]:
```suggestion
	var jobsForCronJob []*batchv1.Job
```
better to keep a nil reference in case there are no jobs

File: pkg/controller/cronjob/cronjob_controllerv2.go [hunk 3]
```diff
@@ -229,6 +252,23 @@ func (jm *ControllerV2) sync(ctx context.Context, cronJobKey string) (*time.Dura
...
+	jobs, err := jm.jobIndexer.ByIndex(jobControllerUIDIndex, string(cronJob.UID)) // なぜ cronjob の uid と job を検索できているのか
```
Comment (atiratree) [inline pkg/controller/cronjob/cronjob_controllerv2.go]: I suppose this is not intentional, but let's stick to English ;)

File: pkg/controller/cronjob/cronjob_controllerv2.go [hunk 4]
```diff
@@ -99,12 +104,14 @@ func NewControllerV2(ctx context.Context, jobInformer batchv1informers.JobInform
...
 		cronJobControl: &realCJControl{KubeClient: kubeClient},
 
-		jobLister:     jobInformer.Lister(),
 		cronJobLister: cronJobsInformer.Lister(),
 
 		jobListerSynced:     jobInformer.Informer().HasSynced,
 		cronJobListerSynced: cronJobsInformer.Informer().HasSynced,
-		now:                 time.Now,
+
+		jobIndexer: jobInformer.Informer().GetIndexer(),
```
Comment (atiratree) [inline pkg/controller/cronjob/cronjob_controllerv2.go]: nit: it might be better to move this about the `synced` block to first read the prerequisites that we need to sync the cache for

File: pkg/controller/cronjob/cronjob_controllerv2_test.go [hunk 5]
```diff
@@ -1670,107 +1669,6 @@ func TestControllerV2UpdateCronJob(t *testing.T) {
 	}
 }
 
-func TestControllerV2GetJobsToBeReconciled(t *testing.T) {
```
Comment (atiratree) [inline pkg/controller/cronjob/cronjob_controllerv2_test.go:1673]: I think there is no harm in keeping this test. We just need to consider the UIDs now.

**Review by atiratree — COMMENTED** [review]
Couple of nits, but lgtm overall. Thanks for rewriting it to informers.

File: pkg/controller/cronjob/cronjob_controllerv2_test.go (hunk 5 above)
Comment (kei01234kei) [reply pkg/controller/cronjob/cronjob_controllerv2_test.go:1673]: Do you mean we would be better off adding the test for `getCronJobJobsByIndexer`?
If you do, I think it is a redundant test because the test for `getCronJobJobsByIndexer` is almost the same as the test of the `ByIndex` method, and the `ByIndex` method is already tested. 🤔

File: pkg/controller/cronjob/cronjob_controllerv2.go (hunk 4 above)
Comment (kei01234kei) [reply pkg/controller/cronjob/cronjob_controllerv2.go]: Exactly. I modified the code.
Thank you.
[move jobIndexer place](https://github.com/kubernetes/kubernetes/pull/133313/commits/95f283a58a88770d9821bf8e4c0a3c654ef972a0)

File: pkg/controller/cronjob/cronjob_controllerv2.go (hunk 3 above)
Comment (kei01234kei) [reply pkg/controller/cronjob/cronjob_controllerv2.go]: Sorry. I forgot to delete the Japanese comment 😱
I modified the code.
[delete unnecessary comment](https://github.com/kubernetes/kubernetes/pull/133313/commits/64787dba39624913c45c4fc2d839c8f6205862c7)

File: pkg/controller/cronjob/cronjob_controllerv2_test.go (hunk 5 above)
Comment (atiratree) [reply pkg/controller/cronjob/cronjob_controllerv2_test.go:1673]: Yes, it would be mostly for checking the continuity of the existing functionality and testing the bug that we are fixing.

On the other hand I agree that the current implementation is quite simple so I do not have a strong opinion here.

**Comment by atiratree** [comment]
/approve
/lgtm
/label tide/merge-method-squash

/hold
cc @soltysh for visibility

File: pkg/controller/cronjob/cronjob_controllerv2.go [hunk 6]
```diff
@@ -99,12 +104,14 @@ func NewControllerV2(ctx context.Context, jobInformer batchv1informers.JobInform
 		jobControl:     realJobControl{KubeClient: kubeClient},
 		cronJobControl: &realCJControl{KubeClient: kubeClient},
 
-		jobLister:     jobInformer.Lister(),
 		cronJobLister: cronJobsInformer.Lister(),
 
+		jobIndexer: jobInformer.Informer().GetIndexer(),
```
Comment (soltysh) [inline pkg/controller/cronjob/cronjob_controllerv2.go:109]: Move this down after you add the indexer.

File: pkg/controller/cronjob/cronjob_controllerv2.go [hunk 7]
```diff
@@ -125,6 +132,22 @@ func NewControllerV2(ctx context.Context, jobInformer batchv1informers.JobInform
 		},
 	})
 
+	err := jm.jobIndexer.AddIndexers(cache.Indexers{
```
Comment (soltysh) [inline pkg/controller/cronjob/cronjob_controllerv2.go]:
```suggestion
	err := jobInformer.Informer().AddIndexers(cache.Indexers{
```

File: pkg/controller/cronjob/cronjob_controllerv2.go [hunk 8]
```diff
@@ -197,7 +220,7 @@ func (jm *ControllerV2) sync(ctx context.Context, cronJobKey string) (*time.Dura
 		return nil, err
 	}
 
-	jobsToBeReconciled, err := jm.getJobsToBeReconciled(cronJob)
+	jobs, err := jm.getCronJobJobsByIndexer(cronJob)
```
Comment (soltysh) [inline pkg/controller/cronjob/cronjob_controllerv2.go]: Don't change the name of the variable, please. It helps with understanding what the code does.

**Review by soltysh — COMMENTED** [review]
Somewhat stylistic changes and one important about return type in the indexer, but I'd like to see them applied before merging this.

/lgtm cancel

File: pkg/controller/cronjob/cronjob_controllerv2.go (hunk 8 above)
Comment (kei01234kei) [reply pkg/controller/cronjob/cronjob_controllerv2.go]: Thank you. I modified the code.
[jobs -> jobsjobsToBeReconciled](https://github.com/kubernetes/kubernetes/pull/133313/commits/81926febfb5c4f10b3016279f0669b967a9bdde2)

File: pkg/controller/cronjob/cronjob_controllerv2.go [hunk 9]
```diff
@@ -197,7 +220,7 @@ func (jm *ControllerV2) sync(ctx context.Context, cronJobKey string) (*time.Dura
 		return nil, err
 	}
 
-	jobsToBeReconciled, err := jm.getJobsToBeReconciled(cronJob)
+	jobsjobsToBeReconciled, err := jm.getCronJobJobsByIndexer(cronJob)
```
Comment (soltysh) [inline pkg/controller/cronjob/cronjob_controllerv2.go]:
```suggestion
	jobsToBeReconciled, err := jm.getCronJobJobsByIndexer(cronJob)
```
:wink:

File: pkg/controller/cronjob/cronjob_controllerv2.go (hunk 6 above)
Comment (soltysh) [reply pkg/controller/cronjob/cronjob_controllerv2.go:109]: This one still holds, move this down after we add the indexer.

**Review by soltysh — COMMENTED** [review]
Two more nits and it's good to go.

**Comment by kei01234kei** [comment]
I was so busy that I was not able to check this PR yesterday. 😭
Sorry.

File: pkg/controller/cronjob/cronjob_controllerv2.go (hunk 9 above)
Comment (kei01234kei) [reply pkg/controller/cronjob/cronjob_controllerv2.go]: This is typo. I modified the code.
Thank you.
[fix var name](https://github.com/kubernetes/kubernetes/pull/133313/commits/a15f7879a13b75f50ac0572355b6635f81783336)

File: pkg/controller/cronjob/cronjob_controllerv2.go (hunk 6 above)
Comment (kei01234kei) [reply pkg/controller/cronjob/cronjob_controllerv2.go:109]: > Move this down after you add the indexer.

Thanks for the suggestion. Can I ask the reasoning for moving this down after adding the indexer?

From a functional perspective (e.g., preventing bugs or improving performance), I don't see a necessity for this change. However, if it's for better code readability, I'm happy to follow your direction.

Comment (soltysh) [reply pkg/controller/cronjob/cronjob_controllerv2.go:109]: Readability is the main reason. Either move down, or if you want to keep the current form, make sure to use `jobIndexer` variable below when adding the indexer.

**Review by soltysh — APPROVED** [review]
/lgtm
/hold cancel
