### PR TITLE
package log runner as part of Kubernetes releases

### LINKED ISSUE #106101: Remove deprecate klog flag usage from windows cluster setup
/kind feature

Hey, in K8s 1.23 we are planning to deprecate multiple klog flags. [KEP-2845](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md)

Deprecated flags: `--log-dir`, `--log-file`, `--log-flush-frequency`, `--logtostderr`, `--alsologtostderr`, `--one-output`, `--stderrthreshold`, `--log-file-max-size`, `--skip-log-headers`, `--add-dir-header`, `--skip-headers`, `--log-backtrace-at`

One of the alpha milestones is requires us to remove usage of deprecated flags within K8s repo. Examples found for windows 
* [ ] https://github.com/kubernetes/kubernetes/blob/ec8e6e877899442da9eb0c87a9612cb4dc20373a/cluster/gce/util.sh#L892
* [ ] https://github.com/kubernetes/kubernetes/blob/ec8e6e877899442da9eb0c87a9612cb4dc20373a/cluster/gce/util.sh#L938

/sig windows
/wg structured-logging

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

kube-log-runner was formerly known as go-runner when it was originally introduced
in https://github.com/kubernetes/kubernetes/pull/90804.
It was moved to kubernetes/release/images/build/go-runner later but is now
needed again in Kubernetes itself as replacement for the deprecated --log-file
klog feature: when bringing up a Windows node, kube-proxy.exe and kubelet.exe must be wrapped
with the helper binary to redirect output.
    
It got renamed to avoid a naming conflict with
test/conformance/image/go-runner.
    
Other downstream Kubernetes users may have a similar need, therefore it makes
sense to provide a pre-built binary.

#### Which issue(s) this PR fixes:
Fixes #106101

#### Does this PR introduce a user-facing change?

```release-note
action required: [kube-log-runner](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/component-base/logs/kube-log-runner) is included in release tar balls. It can be used to replace the deprecated `--log-file` parameter.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/2845
```

### CODE REVIEW

File: cmd/kube-runner/go-runner.go [hunk 1]
```diff
@@ -0,0 +1,123 @@
+/*
+Copyright 2020 The Kubernetes Authors.
```
Comment (pohly) [inline cmd/kube-runner/go-runner.go:2]: This is the original go-runner.go from @dims. I kept the file name, but perhaps I should better rename also it to kube-runner.go?

**Comment by BenTheElder** [comment]
We should really have this de-duped vs https://github.com/kubernetes/release/tree/master/images/build/go-runner

I don't think it makes sense to have two versions of this, maybe we can just publish the one in kubernetes/release somewhere and optionally also include that in our release tarballs?

See also: https://github.com/kubernetes/release/pull/2301

cc @serathius

**Comment by pohly** [comment]
> We should really have this de-duped vs https://github.com/kubernetes/release/tree/master/images/build/go-runner

Agreed. But before worrying about how to do that, I wanted to first check that:
- adding a new binary to the release tar balls is acceptable
- that it solves the problem with Window GCE clusters

> I don't think it makes sense to have two versions of this, maybe we can just publish the one in kubernetes/release somewhere and optionally also include that in our release tarballs?

"Publish the one in kubernetes/release" - do you mean source code or binaries?

My gut feeling is that sharing source code via go.mod dependencies might be simpler, but I haven't tried it.

**Comment by BenTheElder** [comment]
> "Publish the one in kubernetes/release" - do you mean source code or binaries?

A binary, right now I think only the distroless based image is published but we could publish a binary as well (and potentially re-publish it with kubernetes releases)

One thing we have to be careful of: These things are an API in the images they wind up in where users may explicitly set the entrypoint, so at the very least if we pick a new name for either of these we need to add a symlink in the images.

I'm not sure what's best here. I wish we'd kept more of this in-repo and avoided the duplicate naming to begin with 🙃

**Comment by pohly** [comment]
> A binary, right now I think only the distroless based image is published but we could publish a binary as well (and potentially re-publish it with kubernetes releases)

I'm currently leaning the other way: let's publish the source code as part of k/k and then pick that up in k/release via `go install` when building the image. Having the source in k/k allows us to use the normal build and publishing rules and it matches user expectations about where to find Kubernetes code.

Downloading a precompiled sounds like it will be more work.

Here's a more complete proposal:
- let's stick with `flag`-style single-dash parameters (instead of `pflag` double-dash): simpler binary, compatible with current go-runner
- `kube-log-runner` as full name: `kube-runner` is still vague
- hosted under `staging/src/k8s.io/component-base/logs/kube-log-runner`: that's better than in-tree because `go install k8s.io/component-base/logs/kube-log-runner` will be more efficient; a separate repo would be overkill

**Comment by pohly** [comment]
Not having a `kubelet.log` under artifacts is normal for the `pull-kubernetes-e2e-windows-gce`, it also behaves that way without these changes (https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/106090/pull-kubernetes-e2e-windows-gce/1455962754056720384/artifacts/e2e-3032f9a532-95646-windows-node-group-2nqm/).

**Comment by pohly** [comment]
I think this worked as intended.

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/106123/pull-kubernetes-e2e-windows-gce/1455925818994724864/artifacts/e2e-7d7d9eefc0-95646-windows-node-group-f4fn/serial-1.log shows that kubelet and kube-proxy get started via kube-runner.

**Comment by pohly** [comment]
@BenTheElder : regarding de-duplication - once this PR is merged and in a Kubernetes release, I will work on removing the code from k/release.

**Comment by BenTheElder** [comment]
I think we should get agreement from more folks first, so we don't keep going in circles on this one.

**Comment by pohly** [comment]
Yes, let's keep this open. @dims will have time to comment on Monday.

FWIW, the PR currently implements my proposal above (kube-log-runner as name, hosted in component-base/logs).

**Comment by serathius** [comment]
/milestone v1.23
This is part of work on deprecating KEP, we need to merge it to provide users an alternative to klog flags for writing files.

**Comment by pohly** [comment]
@vishh: may I have your approval for the `cluster/gce` part of this PR?

**Comment by pohly** [comment]
/hold

Let's make sure we have sufficient feedback (@dims, @BenTheElder?) before merging.

**Comment by dims** [comment]
/retest
/approve
/lgtm

yes, +1 to ask @BenTheElder to peek as well.

**Comment by pohly** [comment]
I just learned that vishh is not active anymore, but Ben can cover `hack`.

/assign @mtaufen @wojtek-t

For approval of the `cluster/gce` changes.

**Comment by pohly** [comment]
The [previous](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106123/pull-kubernetes-e2e-windows-gce/1456185099228811264) run for pull-kubernetes-e2e-windows-gce and the current commit successfully brought up a cluster and only had some individual test failures, which seems to be [normal](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-windows-gce).

The [latest](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106123/pull-kubernetes-e2e-windows-gce/1458849488494923776) retest failed early with "You do not have access/write permission on kubernetes-release-pull".

**Comment by pohly** [comment]
Looks like @BenTheElder is out and we should get this merged before the code freeze, so:

/hold cancel
