### PR TITLE
Fixed skipping valid volume plugins when another plugin has an error

### LINKED ISSUE #106696: Valid FlexVolume Plugin skipped if another plugin is missing and then added
### What happened?

When kubelet is running if you create two volume plugin directories here: /usr/libexec/kubernetes/kubelet-plugins/volume/exec

/usr/libexec/kubernetes/kubelet-plugins/volume/exec/cifs
/usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds

You will see these expected logs:

```
[Error creating Flexvolume plugin from directory jsi~cifs, skipping. Error: unexpected end of JSON input, Error creating Flexvolume plugin from directory nodeagent~uds, skipping.

driver-call.go:267] Failed to unmarshal output for command: init, output: "", error: unexpected end of JSON input
FlexVolume: driver call failed: executable: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds/uds
```

Now if you copy over the cifs plugin file to cifs directory and then copy the uds plugin the errors go away. The pods using the uds volume will function but any pods attempting to use the cifs volume will fail with the following error from kubelet:

desiredStateOfWorld. err=failed to get Plugin from volumeSpec for volume "pv" err=no volume plugin matched

Restarting kubelet fixes this problem as then both plugins are present and properly added.

### What did you expect to happen?

A functional volume plugin should be added to kubelet even if another volume plugin is missing or invalid. Fixing the invalid volume plugin currently only adds the one that was invalid and fixed and other valid plugins that were previously present are skipped.

### How can we reproduce it (as minimally and precisely as possible)?

Start kubelet service on a node.

Create two directories for two flex volume plugins in the /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ directory.

Eg. nodeagent~uds and cifs

Kubelet logs will now start complaining that the plugins are missing.

Add the files to the plugin folders and then start a pod using the plugin.

Notice that only the last plugin file copied is available to be used by pods. The first plugin added will generate this error if used by a volume "err=no volume plugin matched"

### Anything else we need to know?

Performing a touch on the folder of the missing plugin will cause kubelet to properly index it.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Local kube cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux kube-master 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by scottnice**
Fixed issue in plugin.go where valid plugin events would be skipped if any plugin had an error. This meant that valid plugins would never be installed if another was in an error state as the events fired only once.

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
This PR allows valid flex volume plugins to be added even if another plugin is missing or invalid. This is needed because often time pods will mount and add their own flex volume plugins but before they add the file in their init container they will create an empty directory for the plugin via a volume on the node. This directory will be picked up by the flex volume probe as a watch event, but will create an error as no file exists in the folder yet. If this happens while another valid file exists and is ready to be added that valid plugin will be forever skipped until either another event fires (folder date change) or kubelet is restarted.
#### Which issue(s) this PR fixes:

Fixes #106696

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/volume/plugins.go [hunk 1]
```diff
@@ -746,11 +746,10 @@ func (pm *VolumePluginMgr) logDeprecation(plugin string) {
...
 func (pm *VolumePluginMgr) refreshProbedPlugins() {
 	events, err := pm.prober.Probe()
-	if err != nil {
-		klog.ErrorS(err, "Error dynamically probing plugins")
-		return // Use cached plugins upon failure.
-	}
 
+	// because the probe function can return a list of valid plugins
+	// even when an error is present we still must add the plugins
+	// or they will be skipped because each event only fires once
```
Comment (mattcary) [inline pkg/volume/plugins.go:752]: This breaks the prober api, however:

```
type DynamicPluginProber interface {
	Init() error

	// If an error occurs, events are undefined.
	Probe() (events []ProbeEvent, err error)
}
```

Maybe the current implementation happens to work and return valid events, at least on the error you see, but there's no guarantee a different error would't return undefined events that would cause bad behavior when iterating through them.

Also, flexvolumes are deprecated in 1.23 and I don't know what the plan for 1.24 is going to be---are we tearing out the code? @xing-yang 

/cc @xing-yang

Comment (scottnice) [reply pkg/volume/plugins.go:752]: Right, my code is relying on an implementation specific detail of flexVolumeProber. I suppose I should update the flexVolumeProber to return failed events instead of an error aggregate when individual plugins fail.

Comment (scottnice) [reply pkg/volume/plugins.go:752]: On second thought if the plugin is skipped then no error should be generated and no event either.

Comment (mattcary) [reply pkg/volume/plugins.go:756]: Maybe ping Xing on slack (xyang on kubernetes slack) and see if she has more of an opinion around the flexvolume stuff.

Comment (xing-yang) [reply pkg/volume/plugins.go:756]: Looks like the implementation of flexVolumeProber is not consistent with the definition of the Prober api.

Since FlexVolume is deprecated in 1.23, I think non-critical bugs should not be fixed any more. Looks like this problem has a workaround. We don't have an immediate plan to remove the FlexVolume code as there are still lots of people using it.

Comment (scottnice) [reply pkg/volume/plugins.go:756]: After the pods are stuck in pending due to failed mounts because the plugins are not yet registered, restarting kubelet will fix the issue. The issue with this work around is that you first have to figure out what's causing the mount failure and then you have make sure that all other plugins are present before kubelet restart. Sometimes pods will dynamically add flex driver volume plugins an example of this is calico, which is how I originally found this issue.

The prober api does not allow to my knowledge a way to associate a specific error to a specific plugin while allowing other plugins to be successfully added. Currently any detected failure will mean no volume plugins can be installed until the broken plugin is fixed. Even a restart will not fix this issue.

Comment (xing-yang) [reply pkg/volume/plugins.go:756]: @jsafrane Can you take a look

Comment (scottnice) [reply pkg/volume/plugins.go:756]: /cc @jsafrane

Comment (jsafrane) [reply pkg/volume/plugins.go:756]: I don't think this has a good workaround - a faulty flex plugin can break registration of all other flex plugins on the same node. Kubelet restart may not help. Question is, how to fix it nicely.

`Prober` interface is used only in tests and here to collect flex volume drivers.
`Probe()` is really simple and it calls either `probeMap` or `probeAll`. They both check **all** flex drivers (either collected from inotify events or read from `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/`) and collects **all** errors.

[`probeAll` can also return an error when the initial `ReadDir` of the directory with drivers fails, but that's IMO fine, it will return empty list of drivers].

IMO it's OK to change description of `Probe()` that it collects as many drivers as it can and returns errors for the rest. Leave the rest of this PR as it is.

Comment (jsafrane) [reply pkg/volume/plugins.go:756]: BTW, would it be possible to add an unit test to ensure `Probe()` behaves as described above?

Comment (scottnice) [reply pkg/volume/plugins.go:756]: @jsafrane I will update the `Probe()` comment to reflect the functionality. I will add or update a test in the `flexVolumeProber` tests to ensure that it behaves as described above.

Comment (scottnice) [reply pkg/volume/plugins.go:756]: @jsafrane added a unit test and updated the api comment

**Comment by jsafrane** [comment]
/approve
Giving @mattcary @msau42 @xing-yang chance to review + comment. To me it looks good.

**Comment by mattcary** [comment]
/lgtm

Thanks for bearing with us!
