### PR TITLE
Handle Empty clusterCIDR

### LINKED ISSUE #36652: kube-proxy cannot set iptables rules for services
**Kubernetes version** (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.0+a16c0a7", GitCommit:"a16c0a7f71a6f93c7e0f222d961f4675cd97a46b", GitTreeState:"not a git tree", BuildDate:"2016-11-08T01:00:01Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.2", GitCommit:"cfdaf18277e1ebaa28fcdaed1160a0243eb81be1", GitTreeState:"clean", BuildDate:"2016-10-27T22:10:26Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**:
x86_64
- **OS** (e.g. from /etc/os-release):
Ubuntu 16.04
- **Kernel** (e.g. `uname -a`):
4.4.0-38-generic
- **Install tools**:
downloaded tarball from github and installed it manually

**What happened**:
Installed kubernetes on fresh ubuntu machine.  Everthing was fine.  all services started up.  I wanted to install a service of type "NodePort" (see below) but the service was not accessable.  I checked the kube-proxy logs and it gave me errors (see also below).

service:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/external-traffic: OnlyLocal
  creationTimestamp: 2016-11-11T14:51:01Z
  name: py3-tornado-sample
  namespace: default
  resourceVersion: "4216"
  selfLink: /api/v1/namespaces/default/services/py3-tornado-sample
  uid: 432109bc-a81e-11e6-8450-6c626da071ed
spec:
  clusterIP: 192.168.0.55
  ports:
  - nodePort: 35166
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: py3-tornado-sample
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```
errors from kube-proxy:
```
Nov 11 16:11:01 XXXXXXXX kube-proxy[26731]: E1111 16:11:01.985452   26731 proxier.go:1282] Failed to execute iptables-restore: exit status 2 (Bad argument `KUBE-SVC-574IYFDEANSYIEBF'
Nov 11 16:11:01 XXXXXXXX kube-proxy[26731]: Error occurred at line: 33
Nov 11 16:11:01 XXXXXXXX kube-proxy[26731]: Try `iptables-restore -h' or 'iptables-restore --help' for more information.
Nov 11 16:11:01 XXXXXXXX kube-proxy[26731]: )
```

**How to reproduce it** (as minimally and precisely as possible):
Install kubernetes 1.5.0-alpha.2 on a ubuntu machine with kube-proxy set to iptables mode, launch a service of type NodePort.

I don't know what else might help you, please ask if you need further information on the issue, and I'll be happy to give more Info.

### PR DESCRIPTION
**Pull request by mandarjog**
**What this PR does / why we need it**:
Handles empty clusterCIDR by skipping the corresponding rule.

**Which issue this PR fixes** 
fixes #36652

**Special notes for your reviewer**:
1. Added test to check for presence/absence of XLB to SVC rule
2. Changed an error statement to log rules along with the error string in case of a failure; This ensures that full debug info is available in case of iptables-restore errors.

Empty clusterCIDR causes invalid rules generation.
Fixes issue #36652

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/36833)

### CODE REVIEW

File: pkg/proxy/iptables/proxier_test.go [hunk 1]
```diff
@@ -696,9 +696,21 @@ func TestOnlyLocalLoadBalancing(t *testing.T) {
...
+	onlyLocalNodePorts(t, fp, ipt, false)
+}
+
 func TestOnlyLocalNodePorts(t *testing.T) {
 	ipt := iptablestest.NewFake()
 	fp := NewFakeProxier(ipt)
+	onlyLocalNodePorts(t, fp, ipt, true)
+}
+
+func onlyLocalNodePorts(t *testing.T, fp *Proxier, ipt *iptablestest.FakeIPTables, shouldLBTOSVCRuleExist bool) {
```
Comment (bprashanth) [inline pkg/proxy/iptables/proxier_test.go]: can you just check the fp.clusterCIDR and get rid of the last bool arg?

**Review by bprashanth — COMMENTED** [review]
Didn't you mention that you were writing an e2e for this (iptables-restore --test)? or do you want to send a follow up, or file a bug and we'll add it sometime since it sounds useful to detect a bad configuration and explicitly warn

**Comment by mandarjog** [comment]
I will open an issue and handle it there separately.

I started it but realized it is more work  than I thought.

Regards, 
Sent from my Ericsson Blaze

Mandar U Jog

**Comment by bprashanth** [comment]
LGTM thanks

**Comment by mandarjog** [comment]
@bprashanth  Thanks,  Tests passed.
