### PR TITLE
Ensure Kubelet always reports terminating pod container status

### LINKED ISSUE #58711: kubelet: invalid pod phase transition from Failed to Succeeded
xref https://github.com/openshift/origin/issues/17595

I haven't found a trivial reproducer for this yet.

~~I've pasted the node log entries of a single pod and its containers that exhibit this issue:
https://paste.fedoraproject.org/paste/DMlfGbbi~WiezZFBIAv-zw~~

If you search for "updated successfully", you can see the transition from Running -> Failed -> Succeeded.

I've tracked it as far as this
```I0110 14:05:35.238295   25503 generic.go:147] GenericPLEG: 4602f268-f60f-11e7-a2fa-0e70c83f826c/2ba70598ffa93e42963715706bc71c1e45bfc15078a1050dfb86b1cb3889bb14: exited -> non-existent
I0110 14:05:35.737387   25503 kuberuntime_manager.go:853] getSandboxIDByPodUID got sandbox IDs ["98289fc433f806147102f804d9c74461bfa32f7753b9701b0b98448c9cee6636"] for pod "deployment-simple-1-deploy_extended-test-cli-deployment-bwrns-v9htn(4602f268-f60f-11e7-a2fa-0e70c83f826c)"
I0110 14:05:35.768105   25503 generic.go:380] PLEG: Write status for deployment-simple-1-deploy/extended-test-cli-deployment-bwrns-v9htn: &container.PodStatus{ID:"4602f268-f60f-11e7-a2fa-0e70c83f826c", Name:"deployment-simple-1-deploy", Namespace:"extended-test-cli-deployment-bwrns-v9htn", IP:"", ContainerStatuses:[]*container.ContainerStatus{}, SandboxStatuses:[]*runtime.PodSandboxStatus{(*runtime.PodSandboxStatus)(0xc4215960f0)}} (err: <nil>)
I0110 14:05:35.768606   25503 kubelet_pods.go:1349] Generating status for "deployment-simple-1-deploy_extended-test-cli-deployment-bwrns-v9htn(4602f268-f60f-11e7-a2fa-0e70c83f826c)"
I0110 14:05:35.770208   25503 status_manager.go:367] Status Manager: adding pod: "4602f268-f60f-11e7-a2fa-0e70c83f826c", with status: ('\x06', {Succeeded [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2018-01-10 14:05:11 +0000 UTC PodCompleted } {Ready False 0001-01-01 00:00:00 +0000 UTC 2018-01-10 14:05:34 +0000 UTC PodCompleted } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2018-01-10 14:05:11 +0000 UTC  }]   172.18.7.132 10.128.0.86 2018-01-10 14:05:11 +0000 UTC [] [{deployment {nil nil &ContainerStateTerminated{ExitCode:0,Signal:0,Reason:,Message:,StartedAt:0001-01-01 00:00:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,ContainerID:,}} {nil nil nil} false 0 openshift/origin-deployer:db2450c docker://sha256:44bccf94b5a66881265a32c508f8a162f371196480af7912cbac923418a2b02f docker://2ba70598ffa93e42963715706bc71c1e45bfc15078a1050dfb86b1cb3889bb14}] BestEffort}) to podStatusChannel
I0110 14:05:35.770317   25503 status_manager.go:146] Status Manager: syncing pod: "4602f268-f60f-11e7-a2fa-0e70c83f826c", with status: (6, {Succeeded [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2018-01-10 14:05:11 +0000 UTC PodCompleted } {Ready False 0001-01-01 00:00:00 +0000 UTC 2018-01-10 14:05:34 +0000 UTC PodCompleted } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2018-01-10 14:05:11 +0000 UTC  }]   172.18.7.132 10.128.0.86 2018-01-10 14:05:11 +0000 UTC [] [{deployment {nil nil &ContainerStateTerminated{ExitCode:0,Signal:0,Reason:,Message:,StartedAt:0001-01-01 00:00:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,ContainerID:,}} {nil nil nil} false 0 openshift/origin-deployer:db2450c docker://sha256:44bccf94b5a66881265a32c508f8a162f371196480af7912cbac923418a2b02f docker://2ba70598ffa93e42963715706bc71c1e45bfc15078a1050dfb86b1cb3889bb14}] BestEffort}) from podStatusChannel
I0110 14:05:35.784935   25503 status_manager.go:479] Status for pod "deployment-simple-1-deploy_extended-test-cli-deployment-bwrns-v9htn(4602f268-f60f-11e7-a2fa-0e70c83f826c)" updated successfully: (6, {Phase:Succeeded Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-01-10 14:05:11 +0000 UTC Reason:PodCompleted Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-01-10 14:05:34 +0000 UTC Reason:PodCompleted Message:} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2018-01-10 14:05:11 +0000 UTC Reason: Message:}] Message: Reason: HostIP:172.18.7.132 PodIP:10.128.0.86 StartTime:2018-01-10 14:05:11 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:deployment State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:0,Signal:0,Reason:,Message:,StartedAt:0001-01-01 00:00:00 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,ContainerID:,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:openshift/origin-deployer:db2450c ImageID:docker://sha256:44bccf94b5a66881265a32c508f8a162f371196480af7912cbac923418a2b02f ContainerID:docker://2ba70598ffa93e42963715706bc71c1e45bfc15078a1050dfb86b1cb3889bb14}] QOSClass:BestEffort})
```

Note the `ContainerStatuses:[]*container.ContainerStatus{}` is the pod status returned by `GetPodStatus()` in `(g *GenericPLEG) updateCache`. Somehow `generateAPIPodStatus()` corrupts this into a pod status with `Succeeded` phase.

This is part of an overall faulty assumption in the code we can rebuild the pod status, along with all the container status, from scratch at any time as long as the pod sandbox exists.  We need to be individually patching ContainerStatuses, as to not corrupt the status of containers that no longer exist in the runtime.

@dashpole @derekwaynecarr @kargakis @tnozicka 

/sig node

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes #58711

The kubelet must not allow a container that was reported failed in a restartPolicy=Never pod to be reported to the apiserver as success. If a client deletes a restartPolicy=Never pod, the dispatchWork and status manager race to update the container status. The shortcut detection for pods in the Succeeded or Failure phases did not ensure all containers had reported status, and combined with the TerminatePod method handling unrecognized containers as terminated with exitCode 0 the Kubelet could report to the apiserver that all container status was “success”.  On the next sync to the apiserver the status of the pod could then be reset to Succeeed which is a violation of the guarantees around terminal phase. A higher level controller watching this could see "pod succeeded" instead of "pod failed", causing it to incorrectly take action based on perceived success.

We should not invoke TerminatePod until the Kubelet has cleaned up and reported all container status, regardless of phase. We should guard against terminate pod accidentally being invoked when no container status is available by reporting 137 as the exit code instead of exit code 0 (never report success when we don't know something succeeded).  The kubelet will consider any container without the `waiting` or `terminated` state to be still running, like it does for other operations.

Adds an e2e test that detects reporting success when the container failed.

/kind bug

```release-note
Terminating a restartPolicy=Never pod no longer has a chance to report the pod succeeded when it actually failed.
```

### CODE REVIEW

**Comment by smarterclayton** [comment]
Still need to check log output of the running cluster under test to verify dispatchWork is being invoked to sync pods that are on the apiserver but terminal (from reading the code I expect it to)

**Comment by smarterclayton** [comment]
After thinking about this more I need to change this up - we have to invoke the worker as long as any container is running, and so podTerminal is too aggressive to bypass.

**Comment by sftim** [comment]
I hope it's OK to
/retest

**Comment by smarterclayton** [comment]
That's a legitimate flake error, although it should never happen either.  Probably will be a separate bug:

```
pod pod-submit-status-2-21 on node e2e-1c8de79c3b-674b9-minion-group-9q19 container unexpected exit code 128: start=2020-02-23 23:52:44 +0000 UTC end=2020-02-23 23:52:44 +0000 UTC reason=ContainerCannotRun message=OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/f727fb86-18c0-406b-96b3-b6a950000f88/volumes/kubernetes.io~secret/default-token-kj42r\\\" to rootfs \\\"/var/lib/docker/overlay2/4f2e4e9bfe2e62719d04b85e7b24f0603ad1d6c2238b3cccdf8bb052db6dc28f/merged\\\" at \\\"/var/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"stat /var/lib/kubelet/pods/f727fb86-18c0-406b-96b3-b6a950000f88/volumes/kubernetes.io~secret/default-token-kj42r: no such file or directory\\\"\"": unknown
```

from https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88440/pull-kubernetes-e2e-gce/1231718114933084162/

This new test will have to tolerate that failure type

**Comment by mattjmcnaughton** [comment]
cc @Joseph-Irving I haven't totally dug into this yet, but just wanted to put this on your radar, in case it adds a new place we need to consider sidecar containers.

**Comment by smarterclayton** [comment]
/assign @yujuhong @derekwaynecarr 

The shortcut for terminal phase pods (restart never / succeeded or failed) resulted in the dispatchWork loop terminating the pods early before the container status shows up.  We assumed that phase = succeeded meant that all container status was available, but it does not because of the phase transition limitations we put in (you can't change phases), and so it looks like steps were:

1. Restart never pod container exists with failure
2. Pod transitions to failed
3. Somehow container status disappears / is temporarily removed from the cache
4. dispatchWork invoked, container status for the pod not available
5. dispatchWork sees pod in terminal phase, terminates pod, no cache data available, containers are reported empty.

This PR changes dispatchWork to not return until all container status is available, regardless of phase.  There should be a separate bug where we find out why 3 happens.  The e2e test will stress test whether this is anything other than a transient flake (I don't have any evidence from runs so far that we lose the container status permanently, it looks like an intermittent thing).  Even if we fix 3, we still need this change to ensure we don't regress in the future (a pod that never gets deleted because container status never gets reported is a kubelet sync bug anyway, the container has to get put into waiting in that case).

**Comment by smarterclayton** [comment]
Another note, the test tracks end to end completion time and the p99 is pretty bad for some of these:

```
I0224 18:07:05.511] Feb 24 18:03:00.802: INFO: Pod pod-submit-status-2-21 timings total=14.353891848s t=975ms run=0s execute=0s
I0224 18:07:05.512] Feb 24 18:03:01.917: INFO: Pod pod-submit-status-0-22 timings total=5.413535246s t=866ms run=0s execute=0s
I0224 18:07:05.512] Feb 24 18:03:09.090: INFO: Pod pod-submit-status-1-15 timings total=1m37.777955529s t=1.496s run=0s execute=0s
```

^ 7x the mean

```
I0224 18:07:05.516] Feb 24 18:03:09.540: INFO: Pod pod-submit-status-0-23 timings total=7.623252204s t=1.497s run=0s execute=0s
I0224 18:07:05.517] Feb 24 18:03:19.821: INFO: Pod pod-submit-status-0-24 timings total=10.28055788s t=1.916s run=3s execute=0s
I0224 18:07:05.517] Feb 24 18:03:23.348: INFO: Pod pod-submit-status-1-16 timings total=14.25860125s t=483ms run=0s execute=0s
I0224 18:07:05.517] Feb 24 18:03:24.217: INFO: Pod pod-submit-status-2-22 timings total=23.414825916s t=1.301s run=0s execute=0s
I0224 18:07:05.517] Feb 24 18:03:32.899: INFO: Pod pod-submit-status-2-23 timings total=8.681682689s t=1.182s run=0s execute=0s
I0224 18:07:05.518] Feb 24 18:03:36.359: INFO: Pod pod-submit-status-0-25 timings total=16.53851347s t=268ms run=0s execute=0s
I0224 18:07:05.518] Feb 24 18:03:40.978: INFO: Pod pod-submit-status-1-17 timings total=17.629175598s t=611ms run=0s execute=0s
I0224 18:07:05.518] Feb 24 18:03:45.916: INFO: Pod pod-submit-status-0-26 timings total=9.556987168s t=1.108s run=0s execute=0s
I0224 18:07:05.519] Feb 24 18:03:50.583: INFO: Pod pod-submit-status-1-18 timings total=9.605853776s t=449ms run=0s execute=0s
I0224 18:07:05.519] Feb 24 18:03:51.026: INFO: Pod pod-submit-status-2-24 timings total=18.127108709s t=1.927s run=3s execute=0s
I0224 18:07:05.519] Feb 24 18:03:52.850: INFO: Pod pod-submit-status-2-25 timings total=1.824027303s t=358ms run=0s execute=0s
I0224 18:07:05.519] Feb 24 18:03:59.675: INFO: Pod pod-submit-status-2-26 timings total=6.82429607s t=1.266s run=0s execute=0s
I0224 18:07:05.519] Feb 24 18:03:59.735: INFO: Pod pod-submit-status-0-27 timings total=13.818424798s t=993ms run=0s execute=0s
I0224 18:07:05.520] Feb 24 18:04:05.627: INFO: Pod pod-submit-status-2-27 timings total=5.952501588s t=1.668s run=0s execute=0s
I0224 18:07:05.521] Feb 24 18:04:09.633: INFO: Pod pod-submit-status-1-19 timings total=19.049117395s t=282ms run=0s execute=0s
I0224 18:07:05.521] Feb 24 18:04:14.228: INFO: Pod pod-submit-status-0-28 timings total=14.493471328s t=1.37s run=0s execute=0s
I0224 18:07:05.521] Feb 24 18:04:16.787: INFO: Pod pod-submit-status-1-20 timings total=7.153933896s t=1.092s run=0s execute=0s
I0224 18:07:05.522] Feb 24 18:04:18.545: INFO: Pod pod-submit-status-2-28 timings total=12.918099721s t=1.217s run=0s execute=0s
I0224 18:07:05.523] Feb 24 18:04:25.929: INFO: Pod pod-submit-status-1-21 timings total=9.142110155s t=1.227s run=0s execute=0s
I0224 18:07:05.523] Feb 24 18:04:30.857: INFO: Pod pod-submit-status-2-29 timings total=12.311490426s t=1.715s run=0s execute=0s
I0224 18:07:05.523] Feb 24 18:04:31.981: INFO: Pod pod-submit-status-0-29 timings total=17.752403829s t=999ms run=0s execute=0s
I0224 18:07:05.523] Feb 24 18:04:40.438: INFO: Pod pod-submit-status-0-30 timings total=8.456489372s t=767ms run=0s execute=0s
I0224 18:07:05.524] Feb 24 18:04:40.532: INFO: Pod pod-submit-status-2-30 timings total=9.675446682s t=885ms run=0s execute=0s
I0224 18:07:05.524] Feb 24 18:04:53.216: INFO: Pod pod-submit-status-2-31 timings total=12.68309672s t=450ms run=0s execute=0s
I0224 18:07:05.529] Feb 24 18:05:00.710: INFO: Pod pod-submit-status-1-22 timings total=34.781454908s t=1.858s run=0s execute=0s
I0224 18:07:05.529] Feb 24 18:05:04.089: INFO: Pod pod-submit-status-2-32 timings total=10.873328002s t=165ms run=0s execute=0s
I0224 18:07:05.529] Feb 24 18:05:19.127: INFO: Pod pod-submit-status-0-31 timings total=38.689119748s t=910ms run=0s execute=0s
I0224 18:07:05.529] Feb 24 18:05:27.168: INFO: Pod pod-submit-status-1-23 timings total=26.457137718s t=1.505s run=0s execute=0s
I0224 18:07:05.530] Feb 24 18:05:36.038: INFO: Pod pod-submit-status-0-32 timings total=16.911280002s t=854ms run=0s execute=0s
I0224 18:07:05.530] Feb 24 18:05:38.233: INFO: Pod pod-submit-status-1-24 timings total=11.065221015s t=1.48s run=0s execute=0s
I0224 18:07:05.530] Feb 24 18:05:46.835: INFO: Pod pod-submit-status-1-25 timings total=8.602103531s t=1.282s run=0s execute=0s
I0224 18:07:05.530] Feb 24 18:05:59.951: INFO: Pod pod-submit-status-1-26 timings total=13.115994805s t=707ms run=0s execute=0s
I0224 18:07:05.530] Feb 24 18:06:18.669: INFO: Pod pod-submit-status-1-27 timings total=18.71729618s t=1.647s run=2s execute=0s
I0224 18:07:05.531] Feb 24 18:06:28.570: INFO: Pod pod-submit-status-1-28 timings total=9.901381073s t=1.569s run=0s execute=0s
I0224 18:07:05.531] Feb 24 18:06:42.077: INFO: Pod pod-submit-status-1-29 timings total=13.507146184s t=809ms run=0s execute=0s
I0224 18:07:05.531] Feb 24 18:06:47.067: INFO: Pod pod-submit-status-1-30 timings total=4.989684469s t=840ms run=0s execute=0s
I0224 18:07:05.531] Feb 24 18:06:55.707: INFO: Pod pod-submit-status-1-31 timings total=8.639814656s t=940ms run=0s execute=0s
I0224 18:07:05.531] Feb 24 18:07:04.775: INFO: Pod pod-submit-status-1-32 timings total=9.068308862s t=1.711s run=0s execute=0s
```

**Comment by smarterclayton** [comment]
```
I0224 18:01:32.511354    1371 kuberuntime_manager.go:721] Creating sandbox for pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)"
I0224 18:01:33.675240    1371 kubelet.go:1923] SyncLoop (DELETE, "api"): "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)"
I0224 18:01:33.677273    1371 kubelet.go:2009] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" has completed execution and should be deleted from the API server: update
I0224 18:01:35.182315    1371 plugins.go:406] Calling network plugin kubenet to set up pod "pod-submit-status-1-15_pods-2025"
I0224 18:01:35.192300    1371 kubenet_linux.go:722] Adding pods-2025/pod-submit-status-1-15 to 'kubenet-loopback' with CNI 'loopback' plugin and runtime: &{ContainerID:f33160054236679592c4670582b265d26db0a061b4b2e41f1e55b7e5f640b5c7 NetNS:/proc/110373/ns/net IfName:lo Args:[] CapabilityArgs:map[] CacheDir:/var/lib/cni/cache}
I0224 18:01:35.203531    1371 kubenet_linux.go:722] Adding pods-2025/pod-submit-status-1-15 to 'kubenet' with CNI 'bridge' plugin and runtime: &{ContainerID:f33160054236679592c4670582b265d26db0a061b4b2e41f1e55b7e5f640b5c7 NetNS:/proc/110373/ns/net IfName:eth0 Args:[] CapabilityArgs:map[] CacheDir:/var/lib/cni/cache}
I0224 18:01:35.316532    1371 manager.go:950] Added container: "/kubepods/burstable/pod5827f9b8-4635-49da-9035-b3c2c5629224/f33160054236679592c4670582b265d26db0a061b4b2e41f1e55b7e5f640b5c7" (aliases: [k8s_POD_pod-submit-status-1-15_pods-2025_5827f9b8-4635-49da-9035-b3c2c5629224_0 f33160054236679592c4670582b265d26db0a061b4b2e41f1e55b7e5f640b5c7], namespace: "docker")
I0224 18:01:35.402299    1371 kubenet_linux.go:486] SetUpPod took 219.955995ms for pods-2025/pod-submit-status-1-15
I0224 18:01:35.411431    1371 kuberuntime_manager.go:735] Created PodSandbox "f33160054236679592c4670582b265d26db0a061b4b2e41f1e55b7e5f640b5c7" for pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)"
I0224 18:01:35.466057    1371 kuberuntime_manager.go:754] Determined the ip [10.64.1.124] for pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" after sandbox changed
I0224 18:01:35.466611    1371 kuberuntime_manager.go:791] Creating container &Container{Name:busybox,Image:docker.io/library/busybox:1.29,Command:[/bin/false],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{cpu: {{5 -3} {<nil>} 5m DecimalSI},memory: {{10485760 0} {<nil>} 10Mi BinarySI},},},VolumeMounts:[]VolumeMount{VolumeMount{Name:default-token-gm6vf,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} in pod pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)
I0224 18:01:35.525755    1371 desired_state_of_world_populator.go:276] Removing volume from desired state for volume "default-token-gm6vf" (UniqueName: "kubernetes.io/secret/5827f9b8-4635-49da-9035-b3c2c5629224-default-token-gm6vf") pod "pod-submit-status-1-15" (UID: "5827f9b8-4635-49da-9035-b3c2c5629224")
I0224 18:01:35.551785    1371 kuberuntime_container.go:150] Generating ref for container busybox: &v1.ObjectReference{Kind:"Pod", Namespace:"pods-2025", Name:"pod-submit-status-1-15", UID:"5827f9b8-4635-49da-9035-b3c2c5629224", APIVersion:"v1", ResourceVersion:"28401", FieldPath:"spec.containers{busybox}"}
I0224 18:01:35.552814    1371 kubelet_pods.go:139] container: pods-2025/pod-submit-status-1-15/busybox podIPs: ["10.64.1.124"] creating hosts mount: true
I0224 18:01:35.553567    1371 event.go:278] Event(v1.ObjectReference{Kind:"Pod", Namespace:"pods-2025", Name:"pod-submit-status-1-15", UID:"5827f9b8-4635-49da-9035-b3c2c5629224", APIVersion:"v1", ResourceVersion:"28401", FieldPath:"spec.containers{busybox}"}): type: 'Normal' reason: 'Pulled' Container image "docker.io/library/busybox:1.29" already present on machine
I0224 18:01:35.632831    1371 kubelet_pods.go:1121] Killing unwanted pod "pod-submit-status-1-15"
I0224 18:01:35.657729    1371 plugins.go:420] Calling network plugin kubenet to tear down pod "pod-submit-status-1-15_pods-2025"
I0224 18:01:35.677673    1371 kubenet_linux.go:740] Removing pods-2025/pod-submit-status-1-15 from 'kubenet-loopback' with CNI 'loopback' plugin and runtime: &{ContainerID:f33160054236679592c4670582b265d26db0a061b4b2e41f1e55b7e5f640b5c7 NetNS:/proc/110373/ns/net IfName:lo Args:[] CapabilityArgs:map[] CacheDir:/var/lib/cni/cache}
I0224 18:01:35.740901    1371 event.go:278] Event(v1.ObjectReference{Kind:"Pod", Namespace:"pods-2025", Name:"pod-submit-status-1-15", UID:"5827f9b8-4635-49da-9035-b3c2c5629224", APIVersion:"v1", ResourceVersion:"28401", FieldPath:"spec.containers{busybox}"}): type: 'Normal' reason: 'Created' Created container busybox
I0224 18:01:35.771739    1371 kubenet_linux.go:740] Removing pods-2025/pod-submit-status-1-15 from 'kubenet' with CNI 'bridge' plugin and runtime: &{ContainerID:f33160054236679592c4670582b265d26db0a061b4b2e41f1e55b7e5f640b5c7 NetNS:/proc/110373/ns/net IfName:eth0 Args:[] CapabilityArgs:map[] CacheDir:/var/lib/cni/cache}
I0224 18:01:35.898496    1371 manager.go:1007] Destroyed container: "/kubepods/burstable/pod5827f9b8-4635-49da-9035-b3c2c5629224/f33160054236679592c4670582b265d26db0a061b4b2e41f1e55b7e5f640b5c7" (aliases: [k8s_POD_pod-submit-status-1-15_pods-2025_5827f9b8-4635-49da-9035-b3c2c5629224_0 f33160054236679592c4670582b265d26db0a061b4b2e41f1e55b7e5f640b5c7], namespace: "docker")
I0224 18:01:35.923639    1371 kubenet_linux.go:582] TearDownPod took 265.394164ms for pods-2025/pod-submit-status-1-15
I0224 18:01:35.937900    1371 kuberuntime_manager.go:930] getSandboxIDByPodUID got sandbox IDs ["f33160054236679592c4670582b265d26db0a061b4b2e41f1e55b7e5f640b5c7"] for pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)"
I0224 18:01:36.382950    1371 event.go:278] Event(v1.ObjectReference{Kind:"Pod", Namespace:"pods-2025", Name:"pod-submit-status-1-15", UID:"5827f9b8-4635-49da-9035-b3c2c5629224", APIVersion:"v1", ResourceVersion:"28401", FieldPath:"spec.containers{busybox}"}): type: 'Warning' reason: 'Failed' Error: failed to start container "busybox": Error response from daemon: OCI runtime create failed: container_linux.go:341: creating new parent process caused "container_linux.go:1923: running lstat on namespace path \"/proc/110373/ns/ipc\" caused \"lstat /proc/110373/ns/ipc: no such file or directory\"": unknown
E0224 18:01:36.382981    1371 pod_workers.go:191] Error syncing pod 5827f9b8-4635-49da-9035-b3c2c5629224 ("pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)"), skipping: failed to "StartContainer" for "busybox" with RunContainerError: "failed to start container \"a481861b6f5ceec104d47f64fa37ed0a64c77140235148d3d98447ef697bf6ab\": Error response from daemon: OCI runtime create failed: container_linux.go:341: creating new parent process caused \"container_linux.go:1923: running lstat on namespace path \\\"/proc/110373/ns/ipc\\\" caused \\\"lstat /proc/110373/ns/ipc: no such file or directory\\\"\": unknown"
I0224 18:01:36.383989    1371 generic.go:386] PLEG: Write status for pod-submit-status-1-15/pods-2025: &container.PodStatus{ID:"5827f9b8-4635-49da-9035-b3c2c5629224", Name:"pod-submit-status-1-15", Namespace:"pods-2025", IPs:[]string{}, ContainerStatuses:[]*container.ContainerStatus{(*container.ContainerStatus)(0xc000a961c0)}, SandboxStatuses:[]*v1alpha2.PodSandboxStatus{(*v1alpha2.PodSandboxStatus)(0xc000ebcd80)}} (err: <nil>)
I0224 18:01:36.384066    1371 kubelet.go:1952] SyncLoop (PLEG): "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)", event: &pleg.PodLifecycleEvent{ID:"5827f9b8-4635-49da-9035-b3c2c5629224", Type:"ContainerDied", Data:"f33160054236679592c4670582b265d26db0a061b4b2e41f1e55b7e5f640b5c7"}
I0224 18:01:36.384098    1371 kubelet.go:2009] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" has completed execution and should be deleted from the API server: sync
I0224 18:01:36.384204    1371 kubelet_pods.go:1359] Generating status for "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)"
I0224 18:01:36.384233    1371 helpers.go:81] Already ran container "busybox" of pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)", do nothing
I0224 18:01:39.759913    1371 status_manager.go:563] Patch status for pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" with "{\"metadata\":{\"uid\":\"5827f9b8-4635-49da-9035-b3c2c5629224\"},\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"Initialized\"},{\"type\":\"Ready\"},{\"type\":\"ContainersReady\"},{\"type\":\"PodScheduled\"}],\"conditions\":[{\"lastProbeTime\":null,\"lastTransitionTime\":\"2020-02-24T18:01:32Z\",\"status\":\"True\",\"type\":\"Initialized\"},{\"lastProbeTime\":null,\"lastTransitionTime\":\"2020-02-24T18:01:32Z\",\"message\":\"containers with unready status: [busybox]\",\"reason\":\"ContainersNotReady\",\"status\":\"False\",\"type\":\"Ready\"},{\"lastProbeTime\":null,\"lastTransitionTime\":\"2020-02-24T18:01:32Z\",\"message\":\"containers with unready status: [busybox]\",\"reason\":\"ContainersNotReady\",\"status\":\"False\",\"type\":\"ContainersReady\"}],\"containerStatuses\":[{\"image\":\"docker.io/library/busybox:1.29\",\"imageID\":\"\",\"lastState\":{},\"name\":\"busybox\",\"ready\":false,\"restartCount\":0,\"started\":false,\"state\":{\"waiting\":{\"reason\":\"ContainerCreating\"}}}],\"hostIP\":\"10.40.0.3\",\"startTime\":\"2020-02-24T18:01:32Z\"}}"
I0224 18:01:39.759983    1371 status_manager.go:570] Status for pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" updated successfully: (1, {Phase:Pending Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:32 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:32 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:32 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:31 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.40.0.3 PodIP: PodIPs:[] StartTime:2020-02-24 18:01:32 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:busybox State:{Waiting:&ContainerStateWaiting{Reason:ContainerCreating,Message:,} Running:nil Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:docker.io/library/busybox:1.29 ImageID: ContainerID: Started:0xc002ba7189}] QOSClass:Burstable EphemeralContainerStatuses:[]})
I0224 18:01:39.760097    1371 kubelet_pods.go:948] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" is terminated, but some containers have not been cleaned up: {ID:{Type:docker ID:a481861b6f5ceec104d47f64fa37ed0a64c77140235148d3d98447ef697bf6ab} Name:busybox State:exited CreatedAt:2020-02-24 18:01:35.610071243 +0000 UTC StartedAt:2020-02-24 18:01:35.610071243 +0000 UTC FinishedAt:2020-02-24 18:01:35.610071243 +0000 UTC ExitCode:128 Image:busybox:1.29 ImageID:docker-pullable://busybox@sha256:e004c2cc521c95383aebb1fb5893719aa7a8eae2e7a71f316a4410784edb00a9 Hash:2873044230 RestartCount:0 Reason:ContainerCannotRun Message:OCI runtime create failed: container_linux.go:341: creating new parent process caused "container_linux.go:1923: running lstat on namespace path \"/proc/110373/ns/ipc\" caused \"lstat /proc/110373/ns/ipc: no such file or directory\"": unknown}
I0224 18:01:39.988401    1371 kubelet.go:1920] SyncLoop (RECONCILE, "api"): "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)"
I0224 18:01:51.421702    1371 kubelet.go:1971] SyncLoop (SYNC): 1 pods; pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)
I0224 18:01:51.421911    1371 kubelet.go:2009] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" has completed execution and should be deleted from the API server: sync
I0224 18:01:51.887031    1371 status_manager.go:563] Patch status for pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" with "{\"metadata\":{\"uid\":\"5827f9b8-4635-49da-9035-b3c2c5629224\"}}"
I0224 18:01:51.887073    1371 status_manager.go:570] Status for pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" updated successfully: (3, {Phase:Pending Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:32 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:32 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:32 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:31 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.40.0.3 PodIP: PodIPs:[] StartTime:2020-02-24 18:01:32 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:busybox State:{Waiting:&ContainerStateWaiting{Reason:ContainerCreating,Message:,} Running:nil Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:docker.io/library/busybox:1.29 ImageID: ContainerID: Started:0xc002360038}] QOSClass:Burstable EphemeralContainerStatuses:[]})
I0224 18:01:51.887294    1371 kubelet_pods.go:948] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" is terminated, but some containers have not been cleaned up: {ID:{Type:docker ID:a481861b6f5ceec104d47f64fa37ed0a64c77140235148d3d98447ef697bf6ab} Name:busybox State:exited CreatedAt:2020-02-24 18:01:35.610071243 +0000 UTC StartedAt:2020-02-24 18:01:35.610071243 +0000 UTC FinishedAt:2020-02-24 18:01:35.610071243 +0000 UTC ExitCode:128 Image:busybox:1.29 ImageID:docker-pullable://busybox@sha256:e004c2cc521c95383aebb1fb5893719aa7a8eae2e7a71f316a4410784edb00a9 Hash:2873044230 RestartCount:0 Reason:ContainerCannotRun Message:OCI runtime create failed: container_linux.go:341: creating new parent process caused "container_linux.go:1923: running lstat on namespace path \"/proc/110373/ns/ipc\" caused \"lstat /proc/110373/ns/ipc: no such file or directory\"": unknown}
I0224 18:01:59.563980    1371 status_manager.go:563] Patch status for pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" with "{\"metadata\":{\"uid\":\"5827f9b8-4635-49da-9035-b3c2c5629224\"}}"
I0224 18:01:59.564167    1371 status_manager.go:570] Status for pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" updated successfully: (4, {Phase:Pending Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:32 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:32 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:32 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:31 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.40.0.3 PodIP: PodIPs:[] StartTime:2020-02-24 18:01:32 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:busybox State:{Waiting:&ContainerStateWaiting{Reason:ContainerCreating,Message:,} Running:nil Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:docker.io/library/busybox:1.29 ImageID: ContainerID: Started:0xc0017b59d8}] QOSClass:Burstable EphemeralContainerStatuses:[]})
I0224 18:01:59.564470    1371 kubelet_pods.go:948] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" is terminated, but some containers have not been cleaned up: {ID:{Type:docker ID:a481861b6f5ceec104d47f64fa37ed0a64c77140235148d3d98447ef697bf6ab} Name:busybox State:exited CreatedAt:2020-02-24 18:01:35.610071243 +0000 UTC StartedAt:2020-02-24 18:01:35.610071243 +0000 UTC FinishedAt:2020-02-24 18:01:35.610071243 +0000 UTC ExitCode:128 Image:busybox:1.29 ImageID:docker-pullable://busybox@sha256:e004c2cc521c95383aebb1fb5893719aa7a8eae2e7a71f316a4410784edb00a9 Hash:2873044230 RestartCount:0 Reason:ContainerCannotRun Message:OCI runtime create failed: container_linux.go:341: creating new parent process caused "container_linux.go:1923: running lstat on namespace path \"/proc/110373/ns/ipc\" caused \"lstat /proc/110373/ns/ipc: no such file or directory\"": unknown}
I0224 18:02:04.019475    1371 kubelet_pods.go:948] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" is terminated, but some containers have not been cleaned up: {ID:{Type:docker ID:a481861b6f5ceec104d47f64fa37ed0a64c77140235148d3d98447ef697bf6ab} Name:busybox State:exited CreatedAt:2020-02-24 18:01:35.610071243 +0000 UTC StartedAt:2020-02-24 18:01:35.610071243 +0000 UTC FinishedAt:2020-02-24 18:01:35.610071243 +0000 UTC ExitCode:128 Image:busybox:1.29 ImageID:docker-pullable://busybox@sha256:e004c2cc521c95383aebb1fb5893719aa7a8eae2e7a71f316a4410784edb00a9 Hash:2873044230 RestartCount:0 Reason:ContainerCannotRun Message:OCI runtime create failed: container_linux.go:341: creating new parent process caused "container_linux.go:1923: running lstat on namespace path \"/proc/110373/ns/ipc\" caused \"lstat /proc/110373/ns/ipc: no such file or directory\"": unknown}
I0224 18:02:16.432349    1371 kubelet_pods.go:948] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" is terminated, but some containers have not been cleaned up: {ID:{Type:docker ID:a481861b6f5ceec104d47f64fa37ed0a64c77140235148d3d98447ef697bf6ab} Name:busybox State:exited CreatedAt:2020-02-24 18:01:35.610071243 +0000 UTC StartedAt:2020-02-24 18:01:35.610071243 +0000 UTC FinishedAt:2020-02-24 18:01:35.610071243 +0000 UTC ExitCode:128 Image:busybox:1.29 ImageID:docker-pullable://busybox@sha256:e004c2cc521c95383aebb1fb5893719aa7a8eae2e7a71f316a4410784edb00a9 Hash:2873044230 RestartCount:0 Reason:ContainerCannotRun Message:OCI runtime create failed: container_linux.go:341: creating new parent process caused "container_linux.go:1923: running lstat on namespace path \"/proc/110373/ns/ipc\" caused \"lstat /proc/110373/ns/ipc: no such file or directory\"": unknown}
I0224 18:02:29.628947    1371 kubelet_pods.go:948] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" is terminated, but some containers have not been cleaned up: {ID:{Type:docker ID:a481861b6f5ceec104d47f64fa37ed0a64c77140235148d3d98447ef697bf6ab} Name:busybox State:exited CreatedAt:2020-02-24 18:01:35.610071243 +0000 UTC StartedAt:2020-02-24 18:01:35.610071243 +0000 UTC FinishedAt:2020-02-24 18:01:35.610071243 +0000 UTC ExitCode:128 Image:busybox:1.29 ImageID:docker-pullable://busybox@sha256:e004c2cc521c95383aebb1fb5893719aa7a8eae2e7a71f316a4410784edb00a9 Hash:2873044230 RestartCount:0 Reason:ContainerCannotRun Message:OCI runtime create failed: container_linux.go:341: creating new parent process caused "container_linux.go:1923: running lstat on namespace path \"/proc/110373/ns/ipc\" caused \"lstat /proc/110373/ns/ipc: no such file or directory\"": unknown}
I0224 18:02:40.074346    1371 kubelet_pods.go:948] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" is terminated, but some containers have not been cleaned up: {ID:{Type:docker ID:a481861b6f5ceec104d47f64fa37ed0a64c77140235148d3d98447ef697bf6ab} Name:busybox State:exited CreatedAt:2020-02-24 18:01:35.610071243 +0000 UTC StartedAt:2020-02-24 18:01:35.610071243 +0000 UTC FinishedAt:2020-02-24 18:01:35.610071243 +0000 UTC ExitCode:128 Image:busybox:1.29 ImageID:docker-pullable://busybox@sha256:e004c2cc521c95383aebb1fb5893719aa7a8eae2e7a71f316a4410784edb00a9 Hash:2873044230 RestartCount:0 Reason:ContainerCannotRun Message:OCI runtime create failed: container_linux.go:341: creating new parent process caused "container_linux.go:1923: running lstat on namespace path \"/proc/110373/ns/ipc\" caused \"lstat /proc/110373/ns/ipc: no such file or directory\"": unknown}
I0224 18:02:49.281867    1371 kubelet_pods.go:948] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" is terminated, but some containers have not been cleaned up: {ID:{Type:docker ID:a481861b6f5ceec104d47f64fa37ed0a64c77140235148d3d98447ef697bf6ab} Name:busybox State:exited CreatedAt:2020-02-24 18:01:35.610071243 +0000 UTC StartedAt:2020-02-24 18:01:35.610071243 +0000 UTC FinishedAt:2020-02-24 18:01:35.610071243 +0000 UTC ExitCode:128 Image:busybox:1.29 ImageID:docker-pullable://busybox@sha256:e004c2cc521c95383aebb1fb5893719aa7a8eae2e7a71f316a4410784edb00a9 Hash:2873044230 RestartCount:0 Reason:ContainerCannotRun Message:OCI runtime create failed: container_linux.go:341: creating new parent process caused "container_linux.go:1923: running lstat on namespace path \"/proc/110373/ns/ipc\" caused \"lstat /proc/110373/ns/ipc: no such file or directory\"": unknown}
I0224 18:02:58.054182    1371 kubelet_pods.go:948] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" is terminated, but some containers have not been cleaned up: {ID:{Type:docker ID:a481861b6f5ceec104d47f64fa37ed0a64c77140235148d3d98447ef697bf6ab} Name:busybox State:exited CreatedAt:2020-02-24 18:01:35.610071243 +0000 UTC StartedAt:2020-02-24 18:01:35.610071243 +0000 UTC FinishedAt:2020-02-24 18:01:35.610071243 +0000 UTC ExitCode:128 Image:busybox:1.29 ImageID:docker-pullable://busybox@sha256:e004c2cc521c95383aebb1fb5893719aa7a8eae2e7a71f316a4410784edb00a9 Hash:2873044230 RestartCount:0 Reason:ContainerCannotRun Message:OCI runtime create failed: container_linux.go:341: creating new parent process caused "container_linux.go:1923: running lstat on namespace path \"/proc/110373/ns/ipc\" caused \"lstat /proc/110373/ns/ipc: no such file or directory\"": unknown}
I0224 18:03:08.336402    1371 status_manager.go:563] Patch status for pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" with "{\"metadata\":{\"uid\":\"5827f9b8-4635-49da-9035-b3c2c5629224\"}}"
I0224 18:03:08.336626    1371 status_manager.go:570] Status for pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" updated successfully: (4, {Phase:Pending Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:32 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:32 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:32 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-24 18:01:31 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.40.0.3 PodIP: PodIPs:[] StartTime:2020-02-24 18:01:32 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:busybox State:{Waiting:&ContainerStateWaiting{Reason:ContainerCreating,Message:,} Running:nil Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:docker.io/library/busybox:1.29 ImageID: ContainerID: Started:0xc0017b59d8}] QOSClass:Burstable EphemeralContainerStatuses:[]})
I0224 18:03:08.670314    1371 kubelet.go:1923] SyncLoop (DELETE, "api"): "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)"
I0224 18:03:08.670522    1371 kubelet.go:2009] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" has completed execution and should be deleted from the API server: update
I0224 18:03:09.053933    1371 status_manager.go:583] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" fully terminated and removed from etcd
I0224 18:03:09.075163    1371 kubelet.go:1917] SyncLoop (REMOVE, "api"): "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)"
I0224 18:03:09.077291    1371 kubelet.go:2115] Failed to delete pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)", err: pod not found
I0224 18:08:21.604965    1371 request.go:556] Throttling request took 194.39205ms, request: GET:https://35.233.200.62/api/v1/namespaces/pods-2025/pods/pod-submit-status-1-15
I0224 18:08:21.725409    1371 status_manager.go:543] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" does not exist on the server
I0224 18:08:22.181110    1371 status_manager.go:543] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" does not exist on the server
I0224 18:08:22.816549    1371 status_manager.go:543] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" does not exist on the server
I0224 18:08:25.604995    1371 request.go:556] Throttling request took 145.439704ms, request: GET:https://35.233.200.62/api/v1/namespaces/pods-2025/pods/pod-submit-status-1-15
I0224 18:08:25.817121    1371 status_manager.go:543] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" does not exist on the server
I0224 18:08:43.805004    1371 request.go:556] Throttling request took 65.338323ms, request: GET:https://35.233.200.62/api/v1/namespaces/pods-2025/pods/pod-submit-status-1-15
I0224 18:08:43.879467    1371 status_manager.go:543] Pod "pod-submit-status-1-15_pods-2025(5827f9b8-4635-49da-9035-b3c2c5629224)" does not exist on the server
```

**Comment by smarterclayton** [comment]
With a little bit of debugging, we tracked the unusually long termination intervals to runtime errors reported by the container runtime and added to the reasonCache - the status manager won't allow the pod to be deleted until the reasonCache is empty for a particular pod, but Update() is only called once and so the pod lingers until the reasonCache gets cleaned up.

The reasonCache is only cleared at the end of `syncPod`, but we exit early when a pod is being deleted.  So reasonCache never gets cleared if any sync pod results with errors are present.

**Comment by smarterclayton** [comment]
Looks like there is another place where pods are being left lingering: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/88440/pull-kubernetes-e2e-gce/1232382646156267520/artifacts/e2e-e567ad950e-674b9-minion-group-rq5w/kubelet.log and pod-submit-status-2-1 takes 1m8s to run to completion, so there's another path besides reason cache that takes too long.  Investigating.

**Comment by smarterclayton** [comment]
In https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88440/pull-kubernetes-e2e-gce/1232476723350605825/ one of the nodes seemed to become highly backed up in PLEG and in status channel:

```
E0226 02:14:10.685432    1379 generic.go:276] event channel is full, discard this relist() cycle event
I0226 02:14:10.901909    1379 status_manager.go:448] Skipping the status update for pod "hostpath-symlink-prep-provisioning-2059_provisioning-2059(81ad4a79-f582-420e-8fed-c6c28250138d)" for now because the channel is full; status: {Phase:Succeeded Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 02:12:12 +0000 UTC Reason:PodCompleted Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 02:12:12 +0000 UTC Reason:PodCompleted Message:} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 02:12:12 +0000 UTC Reason:PodCompleted Message:} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 02:12:12 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.40.0.4 PodIP:10.64.2.158 PodIPs:[{IP:10.64.2.158}] StartTime:2020-02-26 02:12:12 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:init-volume-provisioning-2059 State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:0,Signal:0,Reason:Completed,Message:,StartedAt:2020-02-26 02:12:37 +0000 UTC,FinishedAt:2020-02-26 02:12:37 +0000 UTC,ContainerID:docker://31d64c0d841e47354dbe5d3795f2c9893c6c09c1430c9cf035618a4f225a808b,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:busybox:1.29 ImageID:docker-pullable://busybox@sha256:e004c2cc521c95383aebb1fb5893719aa7a8eae2e7a71f316a4410784edb00a9 ContainerID:docker://31d64c0d841e47354dbe5d3795f2c9893c6c09c1430c9cf035618a4f225a808b Started:0xc001f3a0b8}] QOSClass:BestEffort EphemeralContainerStatuses:[]}
```

with thousands of events.  That led to the d300123cf7d3d697895b749f9328b299eb822fb2 which empties the podStatusChannel right before we call syncBatch, since syncBatch should process everything we would handle in the channel anyway.

Still looking to identify other places where the PLEG loop drops out.

**Comment by smarterclayton** [comment]
Also in https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/88440/pull-kubernetes-e2e-gce/1232476723350605825/artifacts/e2e-691e38dd38-674b9-minion-group-pjtv/kubelet.log for pod pod-submit-status-2-6 it takes an unusually long time to clean up the terminated sandbox container if it fails to start (i.e. the container shouldn't be in our status, but we're waiting for it to be purged in order to complete deletion):

```I0226 01:57:54.868640    1388 config.go:412] Receiving a new pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:54.873612    1388 kubelet.go:1914] SyncLoop (ADD, "api"): "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:54.878717    1388 kubelet.go:1489] DEBUG: syncPod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:54.878769    1388 kubelet_pods.go:1359] Generating status for "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:54.879291    1388 cgroup_manager_linux.go:276] The Cgroup [kubepods burstable podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237] has some missing paths: [/sys/fs/cgroup/systemd/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/hugetlb/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/cpuset/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/memory/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/pids/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237]
I0226 01:57:54.879425    1388 cgroup_manager_linux.go:276] The Cgroup [kubepods burstable podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237] has some missing paths: [/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/hugetlb/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/systemd/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/memory/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/pids/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/cpuset/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237]
I0226 01:57:54.880273    1388 cgroup_manager_linux.go:276] The Cgroup [kubepods burstable podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237] has some missing paths: [/sys/fs/cgroup/memory/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/hugetlb/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/pids/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/systemd/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/cpuset/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237]
I0226 01:57:54.884198    1388 desired_state_of_world_populator.go:344] Added volume "default-token-48pt4" (volSpec="default-token-48pt4") for pod "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237" to desired state.
I0226 01:57:54.890382    1388 volume_manager.go:372] Waiting for volumes to attach and mount for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:54.890515    1388 factory.go:177] Factory "docker" was unable to handle container "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237"
I0226 01:57:54.890577    1388 factory.go:166] Error trying to work out if we can handle /kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237: /kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 not handled by systemd handler
I0226 01:57:54.890592    1388 factory.go:177] Factory "systemd" was unable to handle container "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237"
I0226 01:57:54.890605    1388 factory.go:177] Factory "containerd" was unable to handle container "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237"
I0226 01:57:54.890618    1388 factory.go:173] Using factory "raw" for container "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237"
I0226 01:57:54.891098    1388 manager.go:950] Added container: "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237" (aliases: [], namespace: "")
I0226 01:57:54.891618    1388 handler.go:325] Added event &{/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 2020-02-26 01:57:54.885064017 +0000 UTC containerCreation {<nil>}}
I0226 01:57:54.891677    1388 container.go:467] Start housekeeping for container "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237"
I0226 01:57:54.956325    1388 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-48pt4" (UniqueName: "kubernetes.io/secret/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237-default-token-48pt4") pod "pod-submit-status-2-6" (UID: "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237")
I0226 01:57:54.985358    1388 desired_state_of_world_populator.go:344] Added volume "default-token-48pt4" (volSpec="default-token-48pt4") for pod "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237" to desired state.
I0226 01:57:55.057377    1388 reconciler.go:254] Starting operationExecutor.MountVolume for volume "default-token-48pt4" (UniqueName: "kubernetes.io/secret/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237-default-token-48pt4") pod "pod-submit-status-2-6" (UID: "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237")
I0226 01:57:55.057502    1388 reconciler.go:269] operationExecutor.MountVolume started for volume "default-token-48pt4" (UniqueName: "kubernetes.io/secret/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237-default-token-48pt4") pod "pod-submit-status-2-6" (UID: "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237")
I0226 01:57:55.057689    1388 secret.go:183] Setting up volume default-token-48pt4 for pod d19a0cf1-9f23-4c35-9ac6-9b70a01f5237 at /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4
I0226 01:57:55.058085    1388 empty_dir_linux.go:94] Statfs_t of /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4: {Type:61267 Bsize:4096 Blocks:24717112 Bfree:23911590 Bavail:23907494 Files:6258720 Ffree:6162834 Fsid:{Val:[1288470601 -506857373]} Namelen:255 Frsize:4096 Flags:4128 Spare:[0 0 0 0]}
I0226 01:57:55.058140    1388 empty_dir.go:274] pod d19a0cf1-9f23-4c35-9ac6-9b70a01f5237: mounting tmpfs for volume wrapped_default-token-48pt4
I0226 01:57:55.058167    1388 mount_linux.go:134] Mounting cmd (systemd-run) with arguments ([--description=Kubernetes transient mount for /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4 --scope -- mount -t tmpfs tmpfs /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4])
I0226 01:57:55.074215    1388 atomic_writer.go:177] pod pods-6969/pod-submit-status-2-6 volume default-token-48pt4: performed write of new data to ts data directory: /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4/..2020_02_26_01_57_55.309755273
I0226 01:57:55.074328    1388 operation_generator.go:650] MountVolume.SetUp succeeded for volume "default-token-48pt4" (UniqueName: "kubernetes.io/secret/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237-default-token-48pt4") pod "pod-submit-status-2-6" (UID: "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237")
I0226 01:57:55.190930    1388 volume_manager.go:403] All volumes are attached and mounted for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:55.190994    1388 kuberuntime_manager.go:422] No sandbox for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" can be found. Need to start a new one
I0226 01:57:55.191017    1388 kuberuntime_manager.go:650] computePodActions got {KillPod:true CreateSandbox:true SandboxID: Attempt:0 NextInitContainerToStart:nil ContainersToStart:[0] ContainersToKill:map[] EphemeralContainersToStart:[]} for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:55.191098    1388 kuberuntime_manager.go:659] SyncPod received new pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)", will create a sandbox for it
I0226 01:57:55.191112    1388 kuberuntime_manager.go:666] Stopping PodSandbox for "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)", will start new one
I0226 01:57:55.191141    1388 kuberuntime_manager.go:721] Creating sandbox for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:55.193730    1388 docker_service.go:474] Setting cgroup parent to: "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237"
I0226 01:57:55.258890    1388 status_manager.go:563] Patch status for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" with "{\"metadata\":{\"uid\":\"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237\"},\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"Initialized\"},{\"type\":\"Ready\"},{\"type\":\"ContainersReady\"},{\"type\":\"PodScheduled\"}],\"conditions\":[{\"lastProbeTime\":null,\"lastTransitionTime\":\"2020-02-26T01:57:54Z\",\"status\":\"True\",\"type\":\"Initialized\"},{\"lastProbeTime\":null,\"lastTransitionTime\":\"2020-02-26T01:57:54Z\",\"message\":\"containers with unready status: [busybox]\",\"reason\":\"ContainersNotReady\",\"status\":\"False\",\"type\":\"Ready\"},{\"lastProbeTime\":null,\"lastTransitionTime\":\"2020-02-26T01:57:54Z\",\"message\":\"containers with unready status: [busybox]\",\"reason\":\"ContainersNotReady\",\"status\":\"False\",\"type\":\"ContainersReady\"}],\"containerStatuses\":[{\"image\":\"docker.io/library/busybox:1.29\",\"imageID\":\"\",\"lastState\":{},\"name\":\"busybox\",\"ready\":false,\"restartCount\":0,\"started\":false,\"state\":{\"waiting\":{\"reason\":\"ContainerCreating\"}}}],\"hostIP\":\"10.40.0.3\",\"startTime\":\"2020-02-26T01:57:54Z\"}}"
I0226 01:57:55.258968    1388 status_manager.go:570] Status for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" updated successfully: (1, {Phase:Pending Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.40.0.3 PodIP: PodIPs:[] StartTime:2020-02-26 01:57:54 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:busybox State:{Waiting:&ContainerStateWaiting{Reason:ContainerCreating,Message:,} Running:nil Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:docker.io/library/busybox:1.29 ImageID: ContainerID: Started:0xc002d896a9}] QOSClass:Burstable EphemeralContainerStatuses:[]})
I0226 01:57:55.281910    1388 kubelet.go:1927] SyncLoop (RECONCILE, "api"): "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:55.669589    1388 generic.go:155] GenericPLEG: d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1: non-existent -> exited
I0226 01:57:55.719121    1388 kuberuntime_manager.go:930] getSandboxIDByPodUID got sandbox IDs ["ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1"] for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:55.878282    1388 factory.go:173] Using factory "docker" for container "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1"
I0226 01:57:55.884471    1388 docker_sandbox.go:756] Will attempt to re-write config file /var/lib/docker/containers/ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1/resolv.conf with:
I0226 01:57:55.884686    1388 plugins.go:406] Calling network plugin kubenet to set up pod "pod-submit-status-2-6_pods-6969"
I0226 01:57:55.885724    1388 manager.go:950] Added container: "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1" (aliases: [k8s_POD_pod-submit-status-2-6_pods-6969_d19a0cf1-9f23-4c35-9ac6-9b70a01f5237_0 ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1], namespace: "docker")
I0226 01:57:55.886092    1388 handler.go:325] Added event &{/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1 2020-02-26 01:57:55.203558463 +0000 UTC containerCreation {<nil>}}
I0226 01:57:55.886929    1388 container.go:467] Start housekeeping for container "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1"
I0226 01:57:55.891833    1388 generic.go:386] PLEG: Write status for pod-submit-status-2-6/pods-6969: &container.PodStatus{ID:"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237", Name:"pod-submit-status-2-6", Namespace:"pods-6969", IPs:[]string{}, ContainerStatuses:[]*container.ContainerStatus{}, SandboxStatuses:[]*v1alpha2.PodSandboxStatus{(*v1alpha2.PodSandboxStatus)(0xc003bcfaa0)}} (err: <nil>)
I0226 01:57:55.892162    1388 kubelet.go:1959] SyncLoop (PLEG): "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)", event: &pleg.PodLifecycleEvent{ID:"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237", Type:"ContainerDied", Data:"ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1"}
I0226 01:57:55.892335    1388 kubelet_pods.go:1359] Generating status for "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:55.892529    1388 kubelet.go:2261] DEBUG: cleanUpContainersInPod "pod-submit-status-2-6" "ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1" isEvicted=false notRunning=false
I0226 01:57:55.892639    1388 kubelet.go:2263] DEBUG: cleanUpContainersInPod "pod-submit-status-2-6" "ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1" num=0 removeall=false
W0226 01:57:55.892755    1388 pod_container_deletor.go:75] Container "ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1" not found in pod's containers
I0226 01:57:55.899546    1388 kubenet_linux.go:722] Adding pods-6969/pod-submit-status-2-6 to 'kubenet-loopback' with CNI 'loopback' plugin and runtime: &{ContainerID:ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1 NetNS:/proc/91149/ns/net IfName:lo Args:[] CapabilityArgs:map[] CacheDir:/var/lib/cni/cache}
I0226 01:57:55.906990    1388 kubenet_linux.go:722] Adding pods-6969/pod-submit-status-2-6 to 'kubenet' with CNI 'bridge' plugin and runtime: &{ContainerID:ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1 NetNS:/proc/91149/ns/net IfName:eth0 Args:[] CapabilityArgs:map[] CacheDir:/var/lib/cni/cache}
I0226 01:57:55.982140    1388 kubelet.go:1930] SyncLoop (DELETE, "api"): "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:55.982453    1388 kubelet.go:2018] Pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" has completed execution and should be deleted from the API server: update
I0226 01:57:56.043190    1388 kuberuntime_manager.go:735] Created PodSandbox "ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1" for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:56.046013    1388 kuberuntime_manager.go:754] Determined the ip [10.64.1.75] for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" after sandbox changed
I0226 01:57:56.046526    1388 kuberuntime_manager.go:791] Creating container &Container{Name:busybox,Image:docker.io/library/busybox:1.29,Command:[/bin/false],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{cpu: {{5 -3} {<nil>} 5m DecimalSI},memory: {{10485760 0} {<nil>} 10Mi BinarySI},},},VolumeMounts:[]VolumeMount{VolumeMount{Name:default-token-48pt4,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} in pod pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)
I0226 01:57:56.050349    1388 kuberuntime_container.go:150] Generating ref for container busybox: &v1.ObjectReference{Kind:"Pod", Namespace:"pods-6969", Name:"pod-submit-status-2-6", UID:"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237", APIVersion:"v1", ResourceVersion:"24680", FieldPath:"spec.containers{busybox}"}
I0226 01:57:56.050589    1388 kubelet_pods.go:139] container: pods-6969/pod-submit-status-2-6/busybox podIPs: ["10.64.1.75"] creating hosts mount: true
I0226 01:57:56.051184    1388 event.go:278] Event(v1.ObjectReference{Kind:"Pod", Namespace:"pods-6969", Name:"pod-submit-status-2-6", UID:"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237", APIVersion:"v1", ResourceVersion:"24680", FieldPath:"spec.containers{busybox}"}): type: 'Normal' reason: 'Pulled' Container image "docker.io/library/busybox:1.29" already present on machine
I0226 01:57:56.053644    1388 docker_service.go:474] Setting cgroup parent to: "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237"
I0226 01:57:56.090284    1388 desired_state_of_world_populator.go:276] Removing volume from desired state for volume "default-token-48pt4" (UniqueName: "kubernetes.io/secret/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237-default-token-48pt4") pod "pod-submit-status-2-6" (UID: "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237")
I0226 01:57:56.161117    1388 event.go:278] Event(v1.ObjectReference{Kind:"Pod", Namespace:"pods-6969", Name:"pod-submit-status-2-6", UID:"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237", APIVersion:"v1", ResourceVersion:"24680", FieldPath:"spec.containers{busybox}"}): type: 'Normal' reason: 'Created' Created container busybox
I0226 01:57:56.167101    1388 status_manager.go:563] Patch status for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" with "{\"metadata\":{\"uid\":\"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237\"}}"
I0226 01:57:56.167332    1388 status_manager.go:570] Status for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" updated successfully: (2, {Phase:Pending Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.40.0.3 PodIP: PodIPs:[] StartTime:2020-02-26 01:57:54 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:busybox State:{Waiting:&ContainerStateWaiting{Reason:ContainerCreating,Message:,} Running:nil Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:docker.io/library/busybox:1.29 ImageID: ContainerID: Started:0xc000fa3c08}] QOSClass:Burstable EphemeralContainerStatuses:[]})
I0226 01:57:56.169077    1388 kubelet_pods.go:953] Pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" is terminated, but some volumes have not been cleaned up
I0226 01:57:56.184225    1388 reconciler.go:196] operationExecutor.UnmountVolume started for volume "default-token-48pt4" (UniqueName: "kubernetes.io/secret/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237-default-token-48pt4") pod "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237" (UID: "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237")
I0226 01:57:56.184548    1388 subpath_linux.go:213] Cleaning up subpath mounts for /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volume-subpaths/default-token-48pt4
I0226 01:57:56.184631    1388 util.go:253] Tearing down volume default-token-48pt4 for pod d19a0cf1-9f23-4c35-9ac6-9b70a01f5237 at /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4
I0226 01:57:56.184726    1388 empty_dir_linux.go:94] Statfs_t of /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4: {Type:16914836 Bsize:4096 Blocks:957062 Bfree:957059 Bavail:957059 Files:957062 Ffree:957053 Fsid:{Val:[0 0]} Namelen:255 Frsize:4096 Flags:4128 Spare:[0 0 0 0]}
I0226 01:57:56.184870    1388 mount_linux.go:201] Unmounting /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4
I0226 01:57:56.197585    1388 operation_generator.go:775] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237-default-token-48pt4" (OuterVolumeSpecName: "default-token-48pt4") pod "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237" (UID: "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237"). InnerVolumeSpecName "default-token-48pt4". PluginName "kubernetes.io/secret", VolumeGidValue ""
I0226 01:57:56.285102    1388 reconciler.go:319] Volume detached for volume "default-token-48pt4" (UniqueName: "kubernetes.io/secret/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237-default-token-48pt4") on node "e2e-691e38dd38-674b9-minion-group-pjtv" DevicePath ""
E0226 01:57:56.414044    1388 remote_runtime.go:222] StartContainer "5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003" from runtime service failed: rpc error: code = Unknown desc = failed to start container "5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4\\\" to rootfs \\\"/var/lib/docker/overlay2/ade3696a84ccbc72ae0de2d8253dc9f4e44c6f2c87e9d792d48875e3144f24a0/merged\\\" at \\\"/var/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"stat /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4: no such file or directory\\\"\"": unknown
E0226 01:57:56.414153    1388 kuberuntime_manager.go:801] container start failed: RunContainerError: failed to start container "5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4\\\" to rootfs \\\"/var/lib/docker/overlay2/ade3696a84ccbc72ae0de2d8253dc9f4e44c6f2c87e9d792d48875e3144f24a0/merged\\\" at \\\"/var/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"stat /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4: no such file or directory\\\"\"": unknown
I0226 01:57:56.414189    1388 kubelet.go:1694] DEBUG: kl.reasonCache.Update for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)": <nil>
I0226 01:57:56.414212    1388 kubelet.go:1696] DEBUG: - "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)": &container.SyncResult{Action:"KillPodSandbox", Target:"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237", Error:error(nil), Message:""}
I0226 01:57:56.414242    1388 kubelet.go:1696] DEBUG: - "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)": &container.SyncResult{Action:"CreatePodSandbox", Target:"pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)", Error:error(nil), Message:""}
I0226 01:57:56.414269    1388 kubelet.go:1696] DEBUG: - "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)": &container.SyncResult{Action:"ConfigPodSandbox", Target:"ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1", Error:error(nil), Message:""}
I0226 01:57:56.414298    1388 kubelet.go:1696] DEBUG: - "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)": &container.SyncResult{Action:"StartContainer", Target:"busybox", Error:(*errors.errorString)(0xc00036ae10), Message:"failed to start container \"5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003\": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused \"process_linux.go:449: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/overlay2/ade3696a84ccbc72ae0de2d8253dc9f4e44c6f2c87e9d792d48875e3144f24a0/merged\\\\\\\" at \\\\\\\"/var/run/secrets/kubernetes.io/serviceaccount\\\\\\\" caused \\\\\\\"stat /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4: no such file or directory\\\\\\\"\\\"\": unknown"}
I0226 01:57:56.414392    1388 kubelet.go:1705] DEBUG: syncPod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" complete
E0226 01:57:56.414420    1388 pod_workers.go:191] Error syncing pod d19a0cf1-9f23-4c35-9ac6-9b70a01f5237 ("pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"), skipping: failed to "StartContainer" for "busybox" with RunContainerError: "failed to start container \"5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003\": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused \"process_linux.go:449: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/overlay2/ade3696a84ccbc72ae0de2d8253dc9f4e44c6f2c87e9d792d48875e3144f24a0/merged\\\\\\\" at \\\\\\\"/var/run/secrets/kubernetes.io/serviceaccount\\\\\\\" caused \\\\\\\"stat /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4: no such file or directory\\\\\\\"\\\"\": unknown"
I0226 01:57:56.414472    1388 event.go:278] Event(v1.ObjectReference{Kind:"Pod", Namespace:"pods-6969", Name:"pod-submit-status-2-6", UID:"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237", APIVersion:"v1", ResourceVersion:"24680", FieldPath:"spec.containers{busybox}"}): type: 'Warning' reason: 'Failed' Error: failed to start container "busybox": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4\\\" to rootfs \\\"/var/lib/docker/overlay2/ade3696a84ccbc72ae0de2d8253dc9f4e44c6f2c87e9d792d48875e3144f24a0/merged\\\" at \\\"/var/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"stat /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4: no such file or directory\\\"\"": unknown
I0226 01:57:56.770596    1388 factory.go:166] Error trying to work out if we can handle /kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003: error inspecting container: <nil>
I0226 01:57:56.770765    1388 factory.go:177] Factory "docker" was unable to handle container "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003"
I0226 01:57:56.770922    1388 factory.go:166] Error trying to work out if we can handle /kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003: /kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003 not handled by systemd handler
I0226 01:57:56.771033    1388 factory.go:177] Factory "systemd" was unable to handle container "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003"
I0226 01:57:56.773306    1388 factory.go:166] Error trying to work out if we can handle /kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003: failed to load container: container "5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003" in namespace "k8s.io": not found
I0226 01:57:56.773470    1388 factory.go:177] Factory "containerd" was unable to handle container "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003"
I0226 01:57:56.773579    1388 factory.go:173] Using factory "raw" for container "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003"
W0226 01:57:56.773899    1388 container.go:412] Failed to create summary reader for "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003": none of the resources are being tracked.
I0226 01:57:56.774043    1388 manager.go:950] Added container: "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003" (aliases: [], namespace: "")
I0226 01:57:56.774254    1388 handler.go:325] Added event &{/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003 0001-01-01 00:00:00 +0000 UTC containerCreation {<nil>}}
I0226 01:57:56.774389    1388 manager.go:1007] Destroyed container: "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003" (aliases: [], namespace: "")
I0226 01:57:56.774482    1388 handler.go:325] Added event &{/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003 2020-02-26 01:57:56.774475087 +0000 UTC m=+1186.846644681 containerDeletion {<nil>}}
I0226 01:57:56.774587    1388 container.go:467] Start housekeeping for container "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003"
I0226 01:57:56.833604    1388 kubelet_pods.go:1121] Killing unwanted pod "pod-submit-status-2-6"
I0226 01:57:56.842381    1388 plugins.go:420] Calling network plugin kubenet to tear down pod "pod-submit-status-2-6_pods-6969"
I0226 01:57:56.846430    1388 kubenet_linux.go:740] Removing pods-6969/pod-submit-status-2-6 from 'kubenet-loopback' with CNI 'loopback' plugin and runtime: &{ContainerID:ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1 NetNS:/proc/91149/ns/net IfName:lo Args:[] CapabilityArgs:map[] CacheDir:/var/lib/cni/cache}
I0226 01:57:56.897215    1388 kubelet_pods.go:1740] Orphaned pod "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237" found, removing pod cgroups
I0226 01:57:56.933200    1388 pod_container_manager_linux.go:170] Attempt to kill process with pid: 91149 from cgroup: [kubepods burstable podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237]
I0226 01:57:56.933557    1388 pod_container_manager_linux.go:179] successfully killed all unwanted processes from cgroup: [kubepods burstable podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237]
I0226 01:57:56.954905    1388 kubenet_linux.go:740] Removing pods-6969/pod-submit-status-2-6 from 'kubenet' with CNI 'bridge' plugin and runtime: &{ContainerID:ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1 NetNS:/proc/91149/ns/net IfName:eth0 Args:[] CapabilityArgs:map[] CacheDir:/var/lib/cni/cache}
I0226 01:57:57.013580    1388 generic.go:155] GenericPLEG: d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1: exited -> running
I0226 01:57:57.013857    1388 generic.go:155] GenericPLEG: d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003: non-existent -> unknown
I0226 01:57:57.012588    1388 manager.go:1007] Destroyed container: "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1" (aliases: [k8s_POD_pod-submit-status-2-6_pods-6969_d19a0cf1-9f23-4c35-9ac6-9b70a01f5237_0 ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1], namespace: "docker")
I0226 01:57:57.014255    1388 handler.go:325] Added event &{/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237/ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1 2020-02-26 01:57:57.014243226 +0000 UTC m=+1187.086412834 containerDeletion {<nil>}}
I0226 01:57:57.014524    1388 manager.go:1007] Destroyed container: "/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237" (aliases: [], namespace: "")
I0226 01:57:57.014661    1388 handler.go:325] Added event &{/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 2020-02-26 01:57:57.014653505 +0000 UTC m=+1187.086823104 containerDeletion {<nil>}}
I0226 01:57:57.215859    1388 kuberuntime_manager.go:930] getSandboxIDByPodUID got sandbox IDs ["ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1"] for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:57.326492    1388 generic.go:386] PLEG: Write status for pod-submit-status-2-6/pods-6969: &container.PodStatus{ID:"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237", Name:"pod-submit-status-2-6", Namespace:"pods-6969", IPs:[]string{}, ContainerStatuses:[]*container.ContainerStatus{(*container.ContainerStatus)(0xc002965b20)}, SandboxStatuses:[]*v1alpha2.PodSandboxStatus{(*v1alpha2.PodSandboxStatus)(0xc004018000)}} (err: <nil>)
I0226 01:57:57.326590    1388 kubelet.go:1959] SyncLoop (PLEG): "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)", event: &pleg.PodLifecycleEvent{ID:"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237", Type:"ContainerStarted", Data:"ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1"}
I0226 01:57:57.326627    1388 kubelet.go:2018] Pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" has completed execution and should be deleted from the API server: sync
I0226 01:57:57.327050    1388 kubelet.go:1489] DEBUG: syncPod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:57.327082    1388 kubelet_pods.go:1359] Generating status for "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:57.327159    1388 helpers.go:85] Already ran container "busybox" of pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)", do nothing
I0226 01:57:57.596159    1388 status_manager.go:563] Patch status for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" with "{\"metadata\":{\"uid\":\"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237\"}}"
I0226 01:57:57.596504    1388 status_manager.go:570] Status for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" updated successfully: (3, {Phase:Pending Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.40.0.3 PodIP: PodIPs:[] StartTime:2020-02-26 01:57:54 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:busybox State:{Waiting:&ContainerStateWaiting{Reason:ContainerCreating,Message:,} Running:nil Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:docker.io/library/busybox:1.29 ImageID: ContainerID: Started:0xc001500878}] QOSClass:Burstable EphemeralContainerStatuses:[]})
I0226 01:57:57.597965    1388 kubelet_pods.go:948] Pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" is terminated, but some containers have not been cleaned up: {ID:{Type:docker ID:5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003} Name:busybox State:exited CreatedAt:2020-02-26 01:57:56.072517814 +0000 UTC StartedAt:2020-02-26 01:57:56.072517814 +0000 UTC FinishedAt:2020-02-26 01:57:56.072517814 +0000 UTC ExitCode:128 Image:busybox:1.29 ImageID:docker-pullable://busybox@sha256:e004c2cc521c95383aebb1fb5893719aa7a8eae2e7a71f316a4410784edb00a9 Hash:711205015 RestartCount:0 Reason:ContainerCannotRun Message:OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4\\\" to rootfs \\\"/var/lib/docker/overlay2/ade3696a84ccbc72ae0de2d8253dc9f4e44c6f2c87e9d792d48875e3144f24a0/merged\\\" at \\\"/var/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"stat /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4: no such file or directory\\\"\"": unknown}
I0226 01:57:57.670424    1388 kubelet.go:1586] DEBUG: syncPod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" complete
I0226 01:57:58.363726    1388 generic.go:155] GenericPLEG: d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1: running -> exited
I0226 01:57:58.385509    1388 kuberuntime_manager.go:930] getSandboxIDByPodUID got sandbox IDs ["ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1"] for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:58.393205    1388 generic.go:386] PLEG: Write status for pod-submit-status-2-6/pods-6969: &container.PodStatus{ID:"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237", Name:"pod-submit-status-2-6", Namespace:"pods-6969", IPs:[]string{}, ContainerStatuses:[]*container.ContainerStatus{(*container.ContainerStatus)(0xc0008a82a0)}, SandboxStatuses:[]*v1alpha2.PodSandboxStatus{(*v1alpha2.PodSandboxStatus)(0xc000d30600)}} (err: <nil>)
I0226 01:57:58.393430    1388 kubelet.go:1959] SyncLoop (PLEG): "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)", event: &pleg.PodLifecycleEvent{ID:"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237", Type:"ContainerDied", Data:"ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1"}
I0226 01:57:58.393479    1388 kubelet.go:2018] Pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" has completed execution and should be deleted from the API server: sync
I0226 01:57:58.393602    1388 kubelet_pods.go:1359] Generating status for "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:58.393677    1388 kubelet.go:2261] DEBUG: cleanUpContainersInPod "pod-submit-status-2-6" "ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1" isEvicted=false notRunning=true
I0226 01:57:58.393691    1388 kubelet.go:2263] DEBUG: cleanUpContainersInPod "pod-submit-status-2-6" "ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1" num=1 removeall=true
I0226 01:57:58.393740    1388 kuberuntime_container.go:869] Removing container "5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003"
I0226 01:57:58.639942    1388 kubelet.go:1927] SyncLoop (RECONCILE, "api"): "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:58.661987    1388 status_manager.go:563] Patch status for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" with "{\"metadata\":{\"uid\":\"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237\"},\"status\":{\"containerStatuses\":[{\"containerID\":\"docker://5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003\",\"image\":\"busybox:1.29\",\"imageID\":\"docker-pullable://busybox@sha256:e004c2cc521c95383aebb1fb5893719aa7a8eae2e7a71f316a4410784edb00a9\",\"lastState\":{},\"name\":\"busybox\",\"ready\":false,\"restartCount\":0,\"started\":false,\"state\":{\"terminated\":{\"containerID\":\"docker://5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003\",\"exitCode\":128,\"finishedAt\":\"2020-02-26T01:57:56Z\",\"message\":\"OCI runtime create failed: container_linux.go:349: starting container process caused \\\"process_linux.go:449: container init caused \\\\\\\"rootfs_linux.go:58: mounting \\\\\\\\\\\\\\\"/var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4\\\\\\\\\\\\\\\" to rootfs \\\\\\\\\\\\\\\"/var/lib/docker/overlay2/ade3696a84ccbc72ae0de2d8253dc9f4e44c6f2c87e9d792d48875e3144f24a0/merged\\\\\\\\\\\\\\\" at \\\\\\\\\\\\\\\"/var/run/secrets/kubernetes.io/serviceaccount\\\\\\\\\\\\\\\" caused \\\\\\\\\\\\\\\"stat /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4: no such file or directory\\\\\\\\\\\\\\\"\\\\\\\"\\\": unknown\",\"reason\":\"ContainerCannotRun\",\"startedAt\":\"2020-02-26T01:57:56Z\"}}}],\"phase\":\"Failed\"}}"
I0226 01:57:58.662224    1388 status_manager.go:570] Status for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" updated successfully: (4, {Phase:Failed Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.40.0.3 PodIP: PodIPs:[] StartTime:2020-02-26 01:57:54 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:busybox State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:128,Signal:0,Reason:ContainerCannotRun,Message:OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4\\\" to rootfs \\\"/var/lib/docker/overlay2/ade3696a84ccbc72ae0de2d8253dc9f4e44c6f2c87e9d792d48875e3144f24a0/merged\\\" at \\\"/var/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"stat /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4: no such file or directory\\\"\"": unknown,StartedAt:2020-02-26 01:57:56 +0000 UTC,FinishedAt:2020-02-26 01:57:56 +0000 UTC,ContainerID:docker://5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:busybox:1.29 ImageID:docker-pullable://busybox@sha256:e004c2cc521c95383aebb1fb5893719aa7a8eae2e7a71f316a4410784edb00a9 ContainerID:docker://5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003 Started:0xc0015009d9}] QOSClass:Burstable EphemeralContainerStatuses:[]})
I0226 01:57:58.662584    1388 kubelet_pods.go:948] Pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" is terminated, but some containers have not been cleaned up: {ID:{Type:docker ID:5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003} Name:busybox State:exited CreatedAt:2020-02-26 01:57:56.072517814 +0000 UTC StartedAt:2020-02-26 01:57:56.072517814 +0000 UTC FinishedAt:2020-02-26 01:57:56.072517814 +0000 UTC ExitCode:128 Image:busybox:1.29 ImageID:docker-pullable://busybox@sha256:e004c2cc521c95383aebb1fb5893719aa7a8eae2e7a71f316a4410784edb00a9 Hash:711205015 RestartCount:0 Reason:ContainerCannotRun Message:OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4\\\" to rootfs \\\"/var/lib/docker/overlay2/ade3696a84ccbc72ae0de2d8253dc9f4e44c6f2c87e9d792d48875e3144f24a0/merged\\\" at \\\"/var/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"stat /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4: no such file or directory\\\"\"": unknown}
```

We could have exited here, but ContainerDied hasn't been returned yet by the PLEG, BUT the container never started, so it seems like ContainerDied should have been fired much earlier (at `E0226 01:57:56.414044`).  Do we have enough info at the time StartContainer returns the error to know for sure the container never started?

```
I0226 01:57:58.787185    1388 kubelet_pods.go:1121] Killing unwanted pod "pod-submit-status-2-6"
I0226 01:57:59.440726    1388 generic.go:155] GenericPLEG: d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003: unknown -> non-existent
I0226 01:57:59.445945    1388 kuberuntime_manager.go:930] getSandboxIDByPodUID got sandbox IDs ["ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1"] for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:59.453701    1388 generic.go:386] PLEG: Write status for pod-submit-status-2-6/pods-6969: &container.PodStatus{ID:"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237", Name:"pod-submit-status-2-6", Namespace:"pods-6969", IPs:[]string{}, ContainerStatuses:[]*container.ContainerStatus{}, SandboxStatuses:[]*v1alpha2.PodSandboxStatus{(*v1alpha2.PodSandboxStatus)(0xc003bcea20)}} (err: <nil>)
I0226 01:57:59.454998    1388 kubelet.go:1959] SyncLoop (PLEG): "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)", event: &pleg.PodLifecycleEvent{ID:"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237", Type:"ContainerDied", Data:"5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003"}
I0226 01:57:59.455061    1388 kubelet.go:2018] Pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" has completed execution and should be deleted from the API server: sync
I0226 01:57:59.456079    1388 kubelet_pods.go:1359] Generating status for "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:57:59.458006    1388 kubelet.go:2261] DEBUG: cleanUpContainersInPod "pod-submit-status-2-6" "5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003" isEvicted=false notRunning=true
I0226 01:57:59.458031    1388 kubelet.go:2263] DEBUG: cleanUpContainersInPod "pod-submit-status-2-6" "5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003" num=0 removeall=true
I0226 01:57:59.458074    1388 kubelet.go:1966] DEBUG: sync "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237" ignored ContainerRemoved
I0226 01:58:01.414682    1388 status_manager.go:563] Patch status for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" with "{\"metadata\":{\"uid\":\"d19a0cf1-9f23-4c35-9ac6-9b70a01f5237\"}}"
I0226 01:58:01.414744    1388 status_manager.go:570] Status for pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" updated successfully: (6, {Phase:Failed Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason: Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason:ContainersNotReady Message:containers with unready status: [busybox]} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2020-02-26 01:57:54 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.40.0.3 PodIP: PodIPs:[] StartTime:2020-02-26 01:57:54 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:busybox State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:128,Signal:0,Reason:ContainerCannotRun,Message:OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4\\\" to rootfs \\\"/var/lib/docker/overlay2/ade3696a84ccbc72ae0de2d8253dc9f4e44c6f2c87e9d792d48875e3144f24a0/merged\\\" at \\\"/var/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"stat /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4: no such file or directory\\\"\"": unknown,StartedAt:2020-02-26 01:57:56 +0000 UTC,FinishedAt:2020-02-26 01:57:56 +0000 UTC,ContainerID:docker://5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:busybox:1.29 ImageID:docker-pullable://busybox@sha256:e004c2cc521c95383aebb1fb5893719aa7a8eae2e7a71f316a4410784edb00a9 ContainerID:docker://5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003 Started:0xc0035f2058}] QOSClass:Burstable EphemeralContainerStatuses:[]})
I0226 01:58:01.415255    1388 cgroup_manager_linux.go:276] The Cgroup [kubepods burstable podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237] has some missing paths: [/sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/hugetlb/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/systemd/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/cpuset/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/memory/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237 /sys/fs/cgroup/pids/kubepods/burstable/podd19a0cf1-9f23-4c35-9ac6-9b70a01f5237]
I0226 01:58:01.701789    1388 kubelet.go:1930] SyncLoop (DELETE, "api"): "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:58:01.701872    1388 kubelet.go:2018] Pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" has completed execution and should be deleted from the API server: update
I0226 01:58:01.865584    1388 status_manager.go:583] Pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" fully terminated and removed from etcd
```

Deletion complete

```
I0226 01:58:01.875377    1388 kubelet.go:1924] SyncLoop (REMOVE, "api"): "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)"
I0226 01:58:01.875453    1388 kubelet.go:2124] Failed to delete pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)", err: pod not found
I0226 01:58:03.073560    1388 kubelet_volumes.go:145] Orphaned pod "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237" found, removing
I0226 01:58:03.684554    1388 status_manager.go:536] Status for pod "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237" is up-to-date; skipping
I0226 01:58:03.701065    1388 status_manager.go:536] Status for pod "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237" is up-to-date; skipping
I0226 01:58:03.928554    1388 status_manager.go:543] Pod "pod-submit-status-2-6_pods-6969(d19a0cf1-9f23-4c35-9ac6-9b70a01f5237)" does not exist on the server
I0226 01:58:06.398544    1388 kuberuntime_gc.go:165] Removing sandbox "ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1"
I0226 01:58:07.306332    1388 generic.go:155] GenericPLEG: d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/ce429e73d5297c9f6b9a7677daac7a78c2d1892095dbac354f0c8c0ed9fa74e1: exited -> non-existent
I0226 01:58:07.306785    1388 generic.go:377] PLEG: Delete status for pod "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237"
I0226 01:58:07.306966    1388 kubelet.go:1966] DEBUG: sync "d19a0cf1-9f23-4c35-9ac6-9b70a01f5237" ignored ContainerRemoved
```

**Comment by tedyu** [comment]
```
E0226 01:57:56.414044    1388 remote_runtime.go:222] StartContainer "5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003" from runtime service failed: rpc error: code = Unknown desc = failed to start container "5c3ff805bec3aff116c440e5a5960061e3c6bc69a8574a929efd9c1fe5e92003": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4\\\" to rootfs \\\"/var/lib/docker/overlay2/ade3696a84ccbc72ae0de2d8253dc9f4e44c6f2c87e9d792d48875e3144f24a0/merged\\\" at \\\"/var/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"stat /var/lib/kubelet/pods/d19a0cf1-9f23-4c35-9ac6-9b70a01f5237/volumes/kubernetes.io~secret/default-token-48pt4: no such file or directory\\\"\"": unknown
```
We should take a closer look at the above.
I checked the kubelet.log from https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/88542/pull-kubernetes-e2e-gce/1232427530389032960/artifacts/e2e-02b8ef7c2e-674b9-minion-group-gc1l/ (for my PR), there was no such error.

**Comment by tedyu** [comment]
```
+                       case <-syncTicker:
+                               klog.V(5).Infof("Status Manager: syncing batch")
+                               // remove any entries in the status channel since the batch will handle them
```
Probably the log level should be 4 so that we can see it in kubelet.log

I wonder why the select is embedded in for - it seems redundant looking at the enclosing wait.Forever()

**Comment by smarterclayton** [comment]
> I wonder why the select is embedded in for - it seems redundant looking at the enclosing wait.Forever()

wait.Forever is much more expensive than a for loop.  Using it that way is not intended.

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -2001,18 +2001,22 @@ func (kl *Kubelet) syncLoopIteration(configCh <-chan kubetypes.PodUpdate, handle
...
-		if pod.DeletionTimestamp != nil {
-			// If the pod is in a terminated state, there is no pod worker to
-			// handle the work item. Check if the DeletionTimestamp has been
-			// set, and force a status update to trigger a pod deletion request
-			// to the apiserver.
-			kl.statusManager.TerminatePod(pod)
-		}
+	// check whether we are ready to delete the pod from the API server (all status up to date)
+	podTerminal, containersTerminal, podWorkerTerminal := kl.podAndContainersAreTerminal(pod)
+	if pod.DeletionTimestamp != nil && podTerminal && containersTerminal {
```
Comment (rphillips) [inline pkg/kubelet/kubelet.go]: pod.DeletionTimestamp is returned as true in podTerminal. Is checking for the pod.DeletionTimestamp != nil superfluous here?

Comment (sjenning) [reply pkg/kubelet/kubelet.go]: i think it is the other way around.  `podTerminal` is not needed because if `pod.DeletionTimestamp != nil` then `podTerminal` is `true`.

File: pkg/kubelet/status/status_manager.go [hunk 2]
```diff
@@ -160,13 +160,20 @@ func (m *manager) Start() {
...
 	// syncPod and syncBatch share the same go routine to avoid sync races.
 	go wait.Forever(func() {
-		select {
-		case syncRequest := <-m.podStatusChannel:
-			klog.V(5).Infof("Status Manager: syncing pod: %q, with status: (%d, %v) from podStatusChannel",
-				syncRequest.podUID, syncRequest.status.version, syncRequest.status.status)
-			m.syncPod(syncRequest.podUID, syncRequest.status)
-		case <-syncTicker:
-			m.syncBatch()
+		for {
```
Comment (sjenning) [inline pkg/kubelet/status/status_manager.go]: for anyone wondering about this https://github.com/kubernetes/kubernetes/pull/88440#issuecomment-591468035

File: pkg/kubelet/kubelet.go (hunk 1 above)
Comment (smarterclayton) [reply pkg/kubelet/kubelet.go]: No, success or failed containers are also terminal.

Comment (smarterclayton) [reply pkg/kubelet/kubelet.go]: Pod is requested for deletion is one type of terminal behavior.  A pod has to be terminal and requested for deletion and all containers are stopped before we signal final deletion

Comment (smarterclayton) [reply pkg/kubelet/kubelet.go]: I think we can exclude it.

**Comment by rphillips** [comment]
changes lgtm... CI errors appear to be unrelated.

/retest

**Comment by smarterclayton** [comment]
/retest

Looks like containerd cleared up in master

**Comment by smarterclayton** [comment]
Any other comments?

**Comment by sjenning** [comment]
/lgtm
thanks :+1:

**Comment by tedyu** [comment]
It seems the new test was flaky:

https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/88440/pull-kubernetes-e2e-gce/1234735682883162112/

**Comment by smarterclayton** [comment]
```
test/e2e/node/pods.go:212
Mar  3 07:43:08.896: 2 errors:
pod pod-submit-status-1-1 on node e2e-6440a61dec-674b9-minion-group-drb0 container unexpected exit code 128: start=2020-03-03 07:39:55 +0000 UTC end=2020-03-03 07:39:55 +0000 UTC reason=ContainerCannotRun message=OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/7dec24ca-d350-4d24-af2a-f1729f037175/volumes/kubernetes.io~secret/default-token-446w6\\\" to rootfs \\\"/var/lib/docker/overlay2/94008c54a23378b9e19595121123bb421f44ac3497fc5b79a9d85d2ad17c1c18/merged\\\" at \\\"/var/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"stat /var/lib/kubelet/pods/7dec24ca-d350-4d24-af2a-f1729f037175/volumes/kubernetes.io~secret/default-token-446w6: no such file or directory\\\"\"": unknown
pod pod-submit-status-1-12 on node e2e-6440a61dec-674b9-minion-group-drb0 container unexpected exit code 128: start=2020-03-03 07:42:26 +0000 UTC end=2020-03-03 07:42:26 +0000 UTC reason=ContainerCannotRun message=OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/9a10bd5e-c30c-43f3-b52d-f6fb7988bd11/volumes/kubernetes.io~secret/default-token-446w6\\\" to rootfs \\\"/var/lib/docker/overlay2/c7869c25916031b3bd469e9cfe8213e75417a2819eef9fb3d636a378e73e22fa/merged\\\" at \\\"/var/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"stat /var/lib/kubelet/pods/9a10bd5e-c30c-43f3-b52d-f6fb7988bd11/volumes/kubernetes.io~secret/default-token-446w6: no such file or directory\\\"\"": unknown
test/e2e/node/pods.go:422
```

is a flake in the kubelet and CRI, not in this test (which exposes the underlying issue). I'll be filing a separate bug for that.

**Comment by smarterclayton** [comment]
The flake is due to a race condition in the kubelet (which is not new) where a pod is created and then deleted, and then the StartContainer call races with the volume teardown call.  This is in innate race that cannot be solved without preventing volume teardown in parallel with container shutdown (which is not really desirable).

```
I0302 21:30:30.265017    1377 kubelet.go:1923] SyncLoop (DELETE, "api"): "pod-submit-status-2-13_pods-4011(35388651-357f-4eb8-81b6-06abccf6878f)"
...
I0302 21:30:30.309766    1377 event.go:278] Event(v1.ObjectReference{Kind:"Pod", Namespace:"pods-4011", Name:"pod-submit-status-2-13", UID:"35388651-357f-4eb8-81b6-06abccf6878f", APIVersion:"v1", ResourceVersion:"16511", FieldPath:"spec.containers{busybox}"}): type: 'Normal' reason: 'Created' Created container busy
box
...
I0302 21:30:30.379716    1377 operation_generator.go:776] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/35388651-357f-4eb8-81b6-06abccf6878f-default-token-km4qf" (OuterVolumeSpecName: "default-token-km4qf") pod "35388651-357f-4eb8-81b6-06abccf6878f" (UID: "35388651-357f-4eb8-81b6-06abccf6878f").
 InnerVolumeSpecName "default-token-km4qf". PluginName "kubernetes.io/secret", VolumeGidValue ""
...
E0302 21:30:30.564236    1377 remote_runtime.go:222] StartContainer "b3db92a88c7e11e4938a1f86dcfe2716b1becee8fb7652c108ae76b8d9c3286d" from runtime service failed: rpc error: code = Unknown desc = failed to start container "b3db92a88c7e11e4938a1f86dcfe2716b1becee8fb7652c108ae76b8d9c3286d": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/35388651-357f-4eb8-81b6-06abccf6878f/volumes/kubernetes.io~secret/default-token-km4qf\\\" to rootfs \\\"/var/lib/docker/overlay2/adfb5696a6fced834ff284b5b8cca971bd7abb372e2079507a721f7998ea021d/merged\\\" at \\\"/var/run/secrets/kubernetes.io/serviceaccount\\\" caused \\\"stat /var/lib/kubelet/pods/35388651-357f-4eb8-81b6-06abccf6878f/volumes/kubernetes.io~secret/default-token-km4qf: no such file or directory\\\"\"": unknown
```

This is definitely not introduced by this PR, this PR exposes the flakiness of it.  It looks ~1/5.  I think we can file the bug, merge this, and then either temporarily accept the failure or dig into it.

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/issues/88766, I'll explicitly handle this failure mode in this PR.

**Comment by smarterclayton** [comment]
Pushed a change to the PR that explicitly ignores bug #88766 failure mode

**Comment by smarterclayton** [comment]
/retest

(unrelated)

**Comment by smarterclayton** [comment]
The kind issues are interesting, investigating

/hold

**Comment by smarterclayton** [comment]
Found one bug in this PR (fixed earlier) where the wrong default status was being used on init containers (the for loop in defaulting was moving over containers but tried to set initContainer).

Still on hold while I investigate the panic flake (which is not happening anymore after a rebase, so I'm not sure what could have caused it).

**Comment by smarterclayton** [comment]
/hold cancel

The related panic stopped occurring (it was consistent until I rebased and then cleared).  The flake for the 128 exit code is handled in the test and is no longer flaking.

Would appreciate a final pass (will keep rerunning for other flakes, but has been clean beyond those).
