### PR TITLE
GCE: Handle missing subnet for legacy networks and auto networks with unique subnet names

### LINKED ISSUE #53409: GCE: ILB sync fails for legacy networks and auto networks with unusual subnet names
/kind bug

**What happened**:
Since the addition of internal IP reservation, syncing of internal load balancers will fail on legacy networks or automatic networks with subnets generated with a trailing hash.

**What you expected to happen**:
ILB sync occurs

/assign
/sig network
/area platform/gce

### PR DESCRIPTION
**Pull request by nicksardo**
Fixes #53409

/assign @bowei 

Tested on three GKE clusters with automatic, manual, and legacy networks.

**Release note**:
```release-note
GCE: Fixes ILB sync on legacy networks and auto networks with unique subnet names
```

### CODE REVIEW

File: pkg/cloudprovider/providers/gce/gce.go [hunk 1]
```diff
@@ -629,6 +652,20 @@ func getProjectIDInURL(urlStr string) (string, error) {
 	return "", fmt.Errorf("could not find project field in url: %v", urlStr)
 }
 
+// getRegionInURL parses full resource URLS and shorter URLS
+// https://www.googleapis.com/compute/v1/projects/myproject/regions/us-central1/subnetworks/a
+// projects/myproject/regions/us-central1/subnetworks/a
+// All return "us-central1"
+func getRegionInURL(urlStr string) (string, error) {
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/gce.go]: Unit test?

File: pkg/cloudprovider/providers/gce/gce.go [hunk 2]
```diff
@@ -422,6 +424,22 @@ func CreateGCECloud(config *CloudConfig) (*GCECloud, error) {
 		subnetURL = config.SubnetworkURL
 	} else if config.SubnetworkName != "" {
 		subnetURL = gceSubnetworkURL(config.ApiEndpoint, netProjID, config.Region, config.SubnetworkName)
+	} else {
+		n, err := getNetwork(service, netProjID, lastComponent(networkURL))
+		if err != nil {
+			return nil, fmt.Errorf("could not retrieve network %v, err: %v", networkURL, err)
+		}
+
+		if len(n.IPv4Range) > 0 {
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/gce.go]: // Legacy networks have a non-empty IPv4Range

File: pkg/cloudprovider/providers/gce/gce.go [hunk 3]
```diff
@@ -422,6 +424,22 @@ func CreateGCECloud(config *CloudConfig) (*GCECloud, error) {
...
+			// If legacy network, accept missing subnet
+			isLegacyNetwork = true
+		} else if !n.AutoCreateSubnetworks {
+			// If manual network, fail because no subnet is specified
+			return nil, fmt.Errorf("no subnet specified in cloud provider config despite the network %q being manual.", networkURL)
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/gce.go]: "manual networks require specifying a subnet'

File: pkg/cloudprovider/providers/gce/gce.go [hunk 4]
```diff
@@ -687,6 +729,15 @@ func getZonesForRegion(svc *compute.Service, projectID, region string) ([]string
 	return zones, nil
 }
 
+func findSubnetForRegion(subnetURLs []string, region string) string {
+	for _, url := range subnetURLs {
+		if thisRegion, err := getRegionInURL(url); err == nil && thisRegion == region {
```
Comment (bowei) [inline pkg/cloudprovider/providers/gce/gce.go]: you are eating `err` here...

File: pkg/cloudprovider/providers/gce/gce.go [hunk 5]
```diff
@@ -422,6 +424,23 @@ func CreateGCECloud(config *CloudConfig) (*GCECloud, error) {
...
+			return nil, fmt.Errorf("could not retrieve network %v, err: %v", networkURL, err)
+		}
+
+		// Legacy networks have a non-empty IPv4Range
+		if len(n.IPv4Range) > 0 {
+			// If legacy network, accept missing subnet
+			isLegacyNetwork = true
+		} else {
+			// Try to find the subnet in the list of subnets
+			subnetURL = findSubnetForRegion(n.Subnetworks, config.Region)
```
Comment (nicksardo) [inline pkg/cloudprovider/providers/gce/gce.go]: @bowei Originally, I threw an error if no subnet is specified and n.AutoCreateSubets is false. Given what we just saw for auto networks converted to manual networks, I removed the error.

Comment (nicksardo) [reply pkg/cloudprovider/providers/gce/gce.go]: Let me know if you disagree or have a better idea.

**Comment by nicksardo** [comment]
/cc @MrHohn 
Would appreciate more eyes if possible.

File: pkg/cloudprovider/providers/gce/gce.go [hunk 6]
```diff
@@ -397,31 +398,49 @@ func CreateGCECloud(config *CloudConfig) (*GCECloud, error) {
...
-		}
-		networkURL = gceNetworkURL(config.ApiEndpoint, netProjID, networkName)
-	} else if config.NetworkURL != "" {
+	if config.NetworkURL != "" {
 		networkURL = config.NetworkURL
-	} else {
+	} else if config.NetworkName != "" {
 		networkURL = gceNetworkURL(config.ApiEndpoint, netProjID, config.NetworkName)
+	} else {
+		glog.Warningf("No network name or URL specified.")
```
Comment (nicksardo) [inline pkg/cloudprovider/providers/gce/gce.go]: Did two things in this area:
- Reversed the order of conditions.
- Removed the `getNetworkNameViaAPICall` invocation because I highly doubt it works.

File: pkg/cloudprovider/providers/gce/gce.go [hunk 7]
```diff
@@ -397,31 +398,49 @@ func CreateGCECloud(config *CloudConfig) (*GCECloud, error) {
...
 	} else if config.SubnetworkName != "" {
 		subnetURL = gceSubnetworkURL(config.ApiEndpoint, netProjID, config.Region, config.SubnetworkName)
+	} else {
+		// Attempt to determine the subnetwork in case it's an automatic network.
+		// Legacy networks will not have a subnetwork, so subnetworkURL should remain empty.
+		if networkName := lastComponent(networkURL); networkName != "" {
+			if n, err := getNetwork(service, netProjID, networkName); err != nil {
+				// Gracefully fail because kubelet calls CreateGCECloud without any config, and API
+				// calls will fail coming from minions.
+				glog.Warningf("could not retrieve network %q in attempt to determine if legacy network or see list of subnets, err %v", networkURL, err)
```
Comment (nicksardo) [inline pkg/cloudprovider/providers/gce/gce.go]: Changed the logic to gracefully fail because we need to handle the kubelet case: network name is known but the minion has no GCE permissions.

File: pkg/cloudprovider/providers/gce/gce.go (hunk 6 above)
Comment (MrHohn) [inline pkg/cloudprovider/providers/gce/gce.go]: What happens in this case, should we return error? Or is the `subnetURL` below all we need?

Comment (nicksardo) [reply pkg/cloudprovider/providers/gce/gce.go]: Depends on what the user of this package wants to do. Kubelet inits the cloud provider but only uses a static function that's not related to networking. 

I'm not convinced that we can return an error here and not have this bite us in the future.

Comment (bowei) [reply pkg/cloudprovider/providers/gce/gce.go]: Kubelet's use of cloud provider seems to be unnecessary. But does it make sense to have a cloud provider be initialized but not fully functional?

Comment (nicksardo) [reply pkg/cloudprovider/providers/gce/gce.go]: It's indeed unnecessary, but we have to live with it for now.  Since gce.conf is not passed to kubelet, the cloudprovider is already mostly defunct. `CreateGCECloud` needs to not throw an error despite the lack of functionality. Meanwhile, ideally we *do* throw an error if we get into a defunct state for service/ingress controller. I don't think there's a great answer here until we limit the consumers of cloudprovider.

I'm hesitant to return an error here because I'm worried about the case of the metadata API call not returning the network name. This would cause kubelet to not start.

File: pkg/cloudprovider/providers/gce/gce.go (hunk 7 above)
Comment (MrHohn) [inline pkg/cloudprovider/providers/gce/gce.go]: nit: could -> Could

**Review by MrHohn — APPROVED** [review]
LGTM, just feel like the logic to get URLs is surprisingly dedicated...

File: pkg/cloudprovider/providers/gce/gce.go (hunk 7 above)
Comment (nicksardo) [reply pkg/cloudprovider/providers/gce/gce.go]: Fixed
