### PR TITLE
Revert "kubeadm: fix a bug where the uploaded kubelet configuration in kube-system/kubelet-config ConfigMap does not respect user patch"

### LINKED ISSUE #3008: kubeadm: uploaded kubelet configuration with patch affects joining of other nodes without patches
edit neolit123:

PRs:
- https://github.com/kubernetes/kubernetes/pull/123093
- https://github.com/kubernetes/kubernetes/pull/123108
- https://github.com/kubernetes/kubernetes/pull/123107
- https://github.com/kubernetes/kubernetes/pull/123106

-------
### What happened?

`kubeadm init phase upload-config kubelet` phase takes into account `kubeletconfiguration` patches. Thus, it overrides the values in `KubeletConfiguration` passed in `kubeadm --config`.

This affects joining of other nodes that do not have patches. The result of installation depends on the order of nodes added via `kubeadm init/join`.

This behavior appeared after https://github.com/kubernetes/kubernetes/pull/115575 in Kubernetes >= 1.27

### What did you expect to happen?

`upload-config kubelet` phase is expected to do not take into account `kubeletconfiguration` patches, as much as, for example, `upload-config kubeadm` does not take into account patches for control plane components.

### How can we reproduce it (as minimally and precisely as possible)?

Case 1:

Install cluster with two nodes configuring `serializeImagePulls` property of KubeletConfiguration as an example.

1. Create patch file `kubeletconfiguration.yaml` on Node 1 that sets `serializeImagePulls:` **true**
2. Add Node 1 using `kubeadm init --config` passing KubeletConfiguration with `serializeImagePulls:` **false**
3. Add Node 2 using `kubeadm join`.

Expected result:
1. Node 1 has `serializeImagePulls:` **true**
2. Node 2 has `serializeImagePulls:` **false**

Actual result:

Both nodes have `serializeImagePulls:` **true**.

Case 2:

The same as Case 1 but nodes are added in the reverse order.

1. Create patch file `kubeletconfiguration.yaml` on Node 1 that sets `serializeImagePulls:` **true**
2. Add Node 2 using `kubeadm init --config` passing KubeletConfiguration with `serializeImagePulls:` **false**
3. Add Node 1 using `kubeadm join`.

Expected result = Actual result:
1. Node 1 has `serializeImagePulls:` **true**
2. Node 2 has `serializeImagePulls:` **false**

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.8", GitCommit:"66fee42707cd7f5a89f1987f7cb81b02dd19161c", GitTreeState:"clean", BuildDate:"2023-11-15T16:59:43Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.8", GitCommit:"66fee42707cd7f5a89f1987f7cb81b02dd19161c", GitTreeState:"clean", BuildDate:"2023-11-15T16:50:09Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
On premise installation
</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux k8s-control-plane-1 5.15.0-92-generic kubernetes/kubernetes#102-Ubuntu SMP Wed Jan 10 09:33:48 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd=1.6.12-0ubuntu1~22.04.3
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
revert kubeadm: fix a bug where the uploaded kubelet configuration in `kube-system/kubelet-config` ConfigMap does not respect user patch

#### Which issue(s) this PR fixes:

Fixes kubernetes/kubeadm#3008

#### Does this PR introduce a user-facing change?

```release-note
fixes a 1.27.0+ regression in kubeadm: do not upload kubelet patch configuration into `kube-system/kubelet-config` ConfigMap
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/phases/upgrade/postupgrade.go [hunk 1]
```diff
@@ -61,7 +61,7 @@ func PerformPostUpgradeTasks(client clientset.Interface, cfg *kubeadmapi.InitCon
 	}
 
 	// Create the new, version-branched kubelet ComponentConfig ConfigMap
-	if err := kubeletphase.CreateConfigMap(&cfg.ClusterConfiguration, patchesDir, client); err != nil {
+	if err := kubeletphase.CreateConfigMap(&cfg.ClusterConfiguration, client); err != nil {
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/upgrade/postupgrade.go:64]: with the original PR were we trying to fix a bug or a problem in e2e tests?
i'm trying to understand what implications does this have on upgrades too.
i guess on upgrade if the user passes --patches they would only apply on the local upgraded node, which is expected.
i.e. not apply the patch on the CM.

**Review by neolit123 — COMMENTED** [review]
/lgtm
/hold

should we backport to 1.27, 1.28, 1.29?
users have a workaround to just always apply a patch on all nodes.
tentative +1 for backport

/cc @pacoxu

File: cmd/kubeadm/app/phases/upgrade/postupgrade.go (hunk 1 above)
Comment (SataQiu) [reply cmd/kubeadm/app/phases/upgrade/postupgrade.go:64]: I think yes, the upgrade also does not require applying these patches to the global ConfigMap.
/retest
