### PR TITLE
Make iptables and ipvs modes of kube-proxy MASQUERADE --random-fully if possible

### LINKED ISSUE #76699: Slow connect (TCP retransmits) via NodePort
**What happened**:
In out archutecture we have some kinda external (out-of-cluster) Ingress Controller, based on HAProxy + self-written scripts for Kubernetes service discovery (2 instances). ~60 Kubernetes services exposed via NodePort on 8 Kubernetes nodes. Each node runs kube-proxy in iptables mode.

Everything worked fine. But after cluster got more load (HTTP requests per second / concurrent connections), we are experiencing slow connects to services exposed via NodePort because of TCP retransmits.

For now have 4k RPS / 80k concurrent peak. TCP retransmits starts at ~1k RPS / 30k concurrent.

But most strange thing in this situation - retransmit count not same for haproxy/kube-node pair.
For example, haproxy1 have retransmits from kube-nodes 1,2,3 and 8, but haproxy2 have almost zero retransmits from that nodes. Instead haproxy2 have retransmits from kube-nodes 4,5,6 and 7. As you can see, it is like mirrored.

See attachments for clarification. HAProxy configured with 100ms connect timeout, so it redispatches connection on timeout.
haproxy1
haproxy2

**What you expected to happen**:
No TCP retransmits, fast connects.

**How to reproduce it (as minimally and precisely as possible)**:
Commit 50-60 deployments + NodePort-exposed services on few nodes. Load with 1k+ RPS, 30k+ concurrent cons. Observe slow connects (1s, 3s, 6s...)

**Anything else we need to know?**:
Intercluster communication via flannel w/o cni in hostgw mode.

Tried different sysctls on nodes and haproxies. Tried ipvs mode and got much more TCP retransmits.
Also tried with iptables 1.6.2 with latest flanneld to fix NAT bugs according to this article: https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02

For test installed on kube-nodes out-of-cluster reverse-proxy to pass traffic from outside to kubernetes services and pods - no problems. Also no problems with HostPort-exposed services.

**Environment**:
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:39:52Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
Masters: 5 x kvm VMs 16.04.6 LTS (Xenial Xerus) / 4.15.0-45-generic.
Nodes: Baremetall Supermicro Intel(R) Xeon(R) CPU E5-2695 / 128 Gb RAM
- OS (e.g: `cat /etc/os-release`):
Prod nodes: `16.04.6 LTS (Xenial Xerus)`
Test node: `Debian GNU/Linux 9 (stretch)`
- Kernel (e.g. `uname -a`):
Prod nodes: `Linux hw-kube-n1.alaps.kz.prod.bash.kz 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
Test node: `Linux hw-kube-n8.--- 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux`
- Install tools:
Mix of hard way / ansible.
- Others:
Don't know if it is kube-proxy / iptables problem or maybe I'm just missing some sysctls / kernel params.

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR makes kube-proxy in iptables or ipvs mode include `--random-fully` in the iptables rule it emits to `-j MASQUERADE`, if the local version of iptables supports that additional flag.  This greatly reduces the problems caused by a Linux kernel bug that bites when multiple flows are started at the same time.  Due to this kernel bug the flows can get mapped to the same port, and all but one of them will suffer packet drops.  This flag makes the port choice fully random, greatly reducing the probability of this port collision and consequent packet drop.

**Which issue(s) this PR fixes**:

Fixes #76699

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-network-bugs

File: pkg/proxy/iptables/proxier.go [hunk 1]
```diff
@@ -772,12 +788,19 @@ func (proxier *Proxier) syncProxyRules() {
...
 	// value should ever change.
-	writeLine(proxier.natRules, []string{
+	masqRule := []string{
 		"-A", string(kubePostroutingChain),
 		"-m", "comment", "--comment", `"kubernetes service traffic requiring SNAT"`,
 		"-m", "mark", "--mark", proxier.masqueradeMark,
 		"-j", "MASQUERADE",
-	}...)
+	}
+	if proxier.masqueradeRandomFully {
```
Comment (cmluciano) [inline pkg/proxy/iptables/proxier.go]: Please add an e2e to be sure this is parsed correctly when this feature is enabled

**Review by cmluciano — CHANGES_REQUESTED** [review]

File: pkg/proxy/iptables/proxier.go [hunk 2]
```diff
@@ -308,6 +313,16 @@ func NewProxier(ipt utiliptables.Interface,
 		klog.Warning("missing br-netfilter module or unset sysctl br-nf-call-iptables; proxy may not work as intended")
 	}
 
+	masqueradeRandomFully := false
+	iptVersionString, err := ipt.GetVersion()
+	if err == nil {
+		iptVersion, err := utilversion.ParseGeneric(iptVersionString)
```
[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply pkg/proxy/iptables/proxier.go]: I am having trouble understanding the words here; this line invokes a different function than line 317.  Can you please elaborate on the problem?

File: pkg/proxy/iptables/proxier.go (hunk 1 above)
Comment (MikeSpreitzer) [reply pkg/proxy/iptables/proxier.go]: The existing code will log an error if there is any problem with any rule.

Are there already e2e test(s) that exercise kube-proxy and check that this error is not logged?  If so, then this is already covered.  If not, is it fair to ask for this PR to introduce that?

File: pkg/proxy/iptables/proxier.go [hunk 3]
```diff
@@ -308,6 +313,16 @@ func NewProxier(ipt utiliptables.Interface,
 		klog.Warning("missing br-netfilter module or unset sysctl br-nf-call-iptables; proxy may not work as intended")
 	}
 
+	masqueradeRandomFully := false
+	iptVersionString, err := ipt.GetVersion()
```
[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply pkg/proxy/iptables/proxier.go]: yes.  Done.

File: pkg/proxy/iptables/proxier.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (cmluciano) [reply pkg/proxy/iptables/proxier.go]: I got my lines confused. I meant to comment on L318-328 where we run ParseGeneric a few times in different nested ifs. Can we consolidate these lines and utilize something like [version.Compare](https://github.com/kubernetes/apimachinery/blob/master/pkg/util/version/version.go#L308). It might just be me but I got a little lost walking through all of these nested conditions. I also had to reread the final comparison on L326 a few times before I understood that we are setting that flag to true based on the other conditions. 

Perhaps @dcbw or @danwinship will have other thoughts on if it looks ok to them.

File: pkg/proxy/iptables/proxier.go (hunk 1 above)
Comment (cmluciano) [reply pkg/proxy/iptables/proxier.go]: That may be the case, could you reference the kube-proxy test that leverages this generated code for the test cases

I'm mainly trying to find unit test that just validates the expected lines added by this flag or an e2e that enables the flag and ensures the baseline iptables functionality is correct. I can imagine that having the e2e for the scale tests would be useful to see if we can replicate the issue without this flag enabled.

Comment (danwinship) [reply pkg/proxy/iptables/proxier.go]: The code isn't that confusing, though maybe it would be nice to just have `pkg/util/iptables/` just check the version once and export a bunch of variables like `SupportsCheck` and `SupportsRandomFully` for everyone else to use.

File: pkg/proxy/iptables/proxier.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply pkg/proxy/iptables/proxier.go]: @cmluciano : in lines 318--328 there are two different strings parsed with `utilversion.ParseGeneric`.  We coud remove one of those by using `version.Compare` --- which does a parse internally --- instead of `version.AtLeast`.

[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply pkg/proxy/iptables/proxier.go]: @danwinship : it looks like https://github.com/kubernetes/kubernetes/pull/78547#discussion_r296884083 was intended to be attached here, right?

I am a little surprised that `pkg/util/iptables` does not cache the version string.  Is that deliberate preparation for coping with live kernel patching?  Should we continue to eschew caching the version string and things derived from it for that reason?

There is no direct external consumer for the "supports check" bit, so "SupportsRandomFully" (data bit or query function) would be the first of its kind.

[the remark this answers is not in the document]
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go]: > @danwinship : it looks like [#78547 (comment)](https://github.com/kubernetes/kubernetes/pull/78547#discussion_r296884083) was intended to be attached here, right?

oops. yes

> I am a little surprised that `pkg/util/iptables` does not cache the version string. Is that deliberate preparation for coping with live kernel patching?

Nothing so planned. Originally it was only needed in one place. Later whoever added the second usage must have felt it would be easier to just call the "get version" function again rather than cache it. it's not like it takes that long to run "`iptables --version`", and you only end up doing it a few times anyway...

> There is no direct external consumer for the "supports check" bit, so "SupportsRandomFully" (data bit or query function) would be the first of its kind.

There are external consumers (like `pkg/proxy/iptables/proxier.go`), they just have to implement it by getting the iptables version and manually comparing it against `utiliptables.MinCheckVersion`...

File: pkg/proxy/iptables/proxier.go (hunk 1 above)
Comment (MikeSpreitzer) [reply pkg/proxy/iptables/proxier.go]: On the original point, of testing:

1. I added a unit test that the generated `-j MASQUERADE` includes `--random-fully` _if_ the iptables version supports it.

2. The existing e2e tests surely test that all the generated rules parse, for the version of iptables where the tests run.  If any rule does not parse then none are installed, which causes massive damage --- for example, no client will be able to reach the `kubernetes` Service.

File: pkg/proxy/iptables/proxier.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (MikeSpreitzer) [reply pkg/proxy/iptables/proxier.go]: I have refactored, consolidating the version string parsing and comparison logic.

**Comment by cmluciano** [comment]
Can you run ./hack/update-bazel.sh

**Comment by MikeSpreitzer** [comment]
@danwinship , @cmluciano : I think I have addressed all the comments.  Look good?

**Comment by cmluciano** [comment]
thanks for consolidating and adding the unit test

/lgtm

**Comment by vllry** [comment]
LGTM for what it's worth

/sig network

File: pkg/util/iptables/iptables.go [hunk 4]
```diff
@@ -129,6 +129,39 @@ const WaitSecondsMinVersion = "1.4.22"
 const WaitString = "-w"
 const WaitSecondsValue = "5"
 
+// MinMasqueradeFullyVersion is the minimum iptables version that supports the `--random-fully` modifier on `-j MASQUERADE`
+const MinMasqueradeRandomFullyVersion = "1.6.2"
+
+type TestOutcome struct {
+	Answer bool
+	Err    error
```
Comment (danwinship) [inline pkg/util/iptables/iptables.go]: er... no. Just use a multiple-value return from `VersionStringIsAtLeast`

**Review by danwinship — CHANGES_REQUESTED** [review]

File: pkg/util/iptables/iptables.go (hunk 4 above)
Comment (MikeSpreitzer) [reply pkg/util/iptables/iptables.go]: What is bad about defining a return type?  It has the advantage that a caller that wants just one member can make the call and select the member all in one expression; a multiple-value return forces the caller to write something more long-winded.

Comment (MikeSpreitzer) [reply pkg/util/iptables/iptables.go]: At https://github.com/kubernetes/kubernetes/blob/655de9c860f1658ec86ded978dc99de8038e5c17/pkg/proxy/iptables/proxier_test.go#L376 you can see an example of the advantage of returning one struct rather than multiple values.

Comment (danwinship) [reply pkg/util/iptables/iptables.go]: It's non-go-like. But anyway, this is why I was saying we should do all the version checks once at the beginning and then just have "SupportsCheck()", "SupportsRandomFully()" etc methods. Then you don't need to worry about returning errors, because that will already have been dealt with a long time before.

#80368 refactors the utiliptables version checking and gets rid of `GetVersion()`. Originally it added a `SupportsCheck()` to replace it before we realized we didn't even need that. But you could set a `runner.supportsRandomFully` variable when first creating the object, and have a `SupportsRandomFully()` method that just returns that. (This also keeps all of the knowledge of specific version numbers inside utiliptables rather than having its consumers need to know them.)

Comment (MikeSpreitzer) [reply pkg/util/iptables/iptables.go]: I see.  It looks like #80368 is establishing some groundwork to build on.

**Review by danwinship — CHANGES_REQUESTED** [review]
Mostly looks good

**Comment by danwinship** [comment]
/lgtm
but we're going to need a kubelet owner now too... sorry

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by MikeSpreitzer** [comment]
How are those job failures even possible?  The same commit passed those jobs earlier.  And the line numbers in the complaints do not match the line numbers in the code!

**Comment by MikeSpreitzer** [comment]
@danwinship : I had to rebase, so this needs LGTM again.

**Comment by alvaroaleman** [comment]
@MikeSpreitzer Is it possible to file an exception request for this to still get it into 1.16? IMHO this is a pretty important fix.

**Comment by MikeSpreitzer** [comment]
I am not sure.  Where is that process defined?

**Comment by MikeSpreitzer** [comment]
Note also that this PR does not have a KEP, I thought it was too small a thing for that.

**Comment by cblecker** [comment]
What is the current minimum supported version of iptables? This change would require it to be at least 1.6.2, as that is when this feature/flag was introduced to iptables.

**Comment by MikeSpreitzer** [comment]
@cblecker : this PR does not add any requirement.  As suggested in the title, the `--random-fully` flag is only issued if it is supported.

**Comment by cblecker** [comment]
Ah yes, I see that now.

Should we make this bit of magic discoverable in some way? I don’t see any log messages (even at debug) if it doesn’t enable random-fully.. I see this potentially making things difficult from the sysadmin perspective.. you magically just get a different functionality based on the version of iptables you’re running.

**Comment by MikeSpreitzer** [comment]
Dang, I suppose a revision is needed.  A log entry seems the most direct approach.  What V level would you recomend?  As it is once per startup, I think something prominent like 2 or 3 would be appropriate.

**Comment by cblecker** [comment]
If it's run once, I'd be okay with a V(2). If this iptables feature is fixing a bug, as a sysadmin, I'd want to know if we are falling back to not enabling it because the iptables version is too old.

**Comment by MikeSpreitzer** [comment]
Hmm, now that I think about it, there are two cases: when the feature is supported and when it is not.  How about a V(3) when good and a warning when bad?

**Comment by cblecker** [comment]
That works too. Less concerned about logs for the "good" state (if we log this, V(3) sounds right to me), but having something prominent for the not working state I think is important.

The question on an V(2) info vs a warning for me would be: warning should be a call to action, that even though things are working, the sysadmin *needs* to do something. A V(2) info is more just like.. here's a bit of info if you end up going looking for it. Is the bug bad enough that we need that call to action?

**Comment by MikeSpreitzer** [comment]
OK, right, I think the case of low iptables version should be a matter of info rather than a call to action.  So V(2) for bad, V(3) for good.

**Comment by MikeSpreitzer** [comment]
OK, I just force-pushed that revision.

**Comment by cblecker** [comment]
/lgtm
/approve

@lachie83 My concerns have been fully addressed.

**Comment by MikeSpreitzer** [comment]
@cblecker : thanks!

**Comment by MikeSpreitzer** [comment]
Dang!  I had to push another revision to fix a mis-spelling.

**Comment by MikeSpreitzer** [comment]
@cblecker

**Comment by MikeSpreitzer** [comment]
thanks again!

**Comment by lachie83** [comment]
Does this fix address a bug that was introduced by an enhancement in 1.16? If not, are you planning on getting this cherry-picked in the current supported releases?

**Comment by MikeSpreitzer** [comment]
@lachie83 : the bug that this fixes was reported in April, but has been around longer than that.  This is a work-around for a Linux kernel deficiency or bug that has been there forever (as far as I know).  Yes, cherry-picking this to supported releases would be good.  Regarding risks: this is the usual work-around for the kernel issue, and I am not aware of any reported problems with this work-around.

**Comment by MikeSpreitzer** [comment]
@lachie83, another thought regarding risks: I am not sure how `-j MASQUERADE --random-fully` behaves when the kernel is running low on available ports; there could be a risk there.

**Comment by dannyk81** [comment]
@lachie83 @MikeSpreitzer I'd also comment that this flag has become standard (for a while now) in recent releases of CNI plugins such as Calico and Flannel that create iptables rules.

Calico: https://github.com/projectcalico/felix/pull/1901
Flannel: https://github.com/coreos/flannel/pull/1040

**Comment by MikeSpreitzer** [comment]
Also FYI: Here is an explanation of the problem and how `--random-fully` works around it: https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02 .  The code cited in reference (3) includes the loop at https://github.com/torvalds/linux/blob/24de3d377539e384621c5b8f8f8d8d01852dddc8/net/netfilter/nf_nat_proto_common.c#L87-L94 , which answers the question of how `--random-fully` reacts to high utilization of the port range: no worse than the alternatives.  The only difference is where the search starts.

**Comment by MikeSpreitzer** [comment]
That same code structure is in the latest kernel in the 4.X line.
The 5.X line is different.

**Comment by lachie83** [comment]
Thanks for the updates. Can we get issue https://github.com/kubernetes/kubernetes/issues/76699 appropriately labelled with the correct priority from sig-network so that I can evaluate the urgency of getting this milestoned in 1.16?

**Comment by MikeSpreitzer** [comment]
@lachie83 : can you please elaborate on what that means / how to get it done?

**Comment by MikeSpreitzer** [comment]
BTW, on further investigation: it looks like in the 5.X kernel they have made this randomization the normal behavior; the `--random-fully` option is still accepted but no longer makes a difference.
