### PR TITLE
fix cluster-info dump error

### LINKED ISSUE #65221: kubectl cluster-info dump doesn't appear to work after kubeadm install
/kind bug

**What happened**:
Installed k8s using kubeadm, and added the admin config as described. When asking for a `kubectl cluster-info dump` I get

```
error: missing apiVersion or kind and cannot assign it; no kind is registered for the type core.NodeList
```

**What you expected to happen**:

To get a cluster info dump

**How to reproduce it (as minimally and precisely as possible)**:
With the following kubeadm.conf
```
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  advertiseAddress: 0.0.0.0
networking:
  serviceSubnet: fd00:1234::/64
kubernetesVersion: 1.11.0-beta.2
cloudProvider: external
featureGates:
  CoreDNS: false

criSocket: /var/run/containerd/containerd.sock
```

run

```
$ sudo kubeadm init --config=kubeadm.conf
$ mkdir -p $HOME/.kube
$ sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
$ sudo chown $(id -u):$(id -g) $HOME/.kube/config
$ kubectl cluster-info
$ kubectl cluster-info dump
```

**Anything else we need to know?**:
Running containerd 

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-beta.2", GitCommit:"be2cfcf9e44b5162a294e977329d6c8194748c4e", GitTreeState:"clean", BuildDate:"2018-06-07T16:21:58Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-beta.2", GitCommit:"be2cfcf9e44b5162a294e977329d6c8194748c4e", GitTreeState:"clean", BuildDate:"2018-06-07T16:13:01Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Brightbox
- OS (e.g. from /etc/os-release):
Ubuntu 18.04 LTS
- Kernel (e.g. `uname -a`):
Linux srv-i4r66 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
kubeadm version: &version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0-beta.2", GitCommit:"be2cfcf9e44b5162a294e977329d6c8194748c4e", GitTreeState:"clean", BuildDate:"2018-06-07T16:19:15Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
- Others:
containerd github.com/containerd/containerd v1.1.1-rc.1 cbef57047e900aeb2bafe7a634919bec13f4a2a5

### PR DESCRIPTION
**Pull request by ChiuWang**
**Which issue(s) this PR fixes** :
Fixes #65221 

**Release note**:
```release-note
fix cluster-info dump error
```

### CODE REVIEW

**Comment by charrywanganthony** [comment]
@juanvallejo @deads2k PTAL :smile_cat:

File: pkg/kubectl/cmd/clusterinfo_dump.go [hunk 1]
```diff
@@ -116,16 +112,30 @@ func setupOutputWriter(dir string, defaultWriter io.Writer, filename string) io.
 	return file
 }
 
-func (o *ClusterInfoDumpOptions) Complete(f cmdutil.Factory, cmd *cobra.Command) error {
-	printer, err := o.PrintFlags.ToPrinter()
-	if err != nil {
+func printJson(obj runtime.Object, w io.Writer) error {
```
Comment (juanvallejo) [inline pkg/kubectl/cmd/clusterinfo_dump.go]: We should be using our printing stack, not circumventing it via special-cases in individual commands.
The overall problem appears to be that this command is sending internal objects to the printer.
These objects do not have a defined GroupVersionKind, so the printer refuses to print them.

To allow this command to work with the printer, we can re-work this command to work with external versions of objects: https://gist.github.com/juanvallejo/031d20ab40488c98c81b9928c5a5e753 (make sure you are up to date with latest master before applying)

**Review by juanvallejo — CHANGES_REQUESTED** [review]

**Comment by ming19871211** [comment]
Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: i/o timeout
Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ

**Review by juanvallejo — APPROVED** [review]

**Comment by juanvallejo** [comment]
@charrywanganthony Thanks

/lgtm
cc @soltysh for approval

File: pkg/kubectl/cmd/clusterinfo_dump.go [hunk 2]
```diff
@@ -45,19 +47,20 @@ type ClusterInfoDumpOptions struct {
 	AllNamespaces bool
 	Namespaces    []string
 
-	Timeout          time.Duration
-	Clientset        internalclientset.Interface
-	Namespace        string
-	RESTClientGetter genericclioptions.RESTClientGetter
-	LogsForObject    polymorphichelpers.LogsForObjectFunc
+	Timeout             time.Duration
+	Clientset           corev1client.CoreV1Interface
```
Comment (soltysh) [inline pkg/kubectl/cmd/clusterinfo_dump.go]: I prefer `CoreClient`.

File: pkg/kubectl/cmd/clusterinfo_dump.go [hunk 3]
```diff
@@ -45,19 +47,20 @@ type ClusterInfoDumpOptions struct {
...
+	ExtensionsClientset extensionsv1client.ExtensionsV1beta1Interface
```
Comment (soltysh) [inline pkg/kubectl/cmd/clusterinfo_dump.go]: `DaemonSet`, `ReplicaSet` and `Deployment` are part of `apps/v1` since 1.10 at least. It's about time we switch commands to use the GA version.

**Review by soltysh — CHANGES_REQUESTED** [review]
Since you touched it, please update the client to use apps/v1

File: pkg/kubectl/cmd/clusterinfo_dump.go (hunk 3 above)
Comment (juanvallejo) [reply pkg/kubectl/cmd/clusterinfo_dump.go]: @charrywanganthony You'd need to switch out extensionsv1client for `appsv1client "github.com/openshift/client-go/apps/clientset/versioned/typed/apps/v1"`

Comment (charrywanganthony) [reply pkg/kubectl/cmd/clusterinfo_dump.go]: @juanvallejo WIP but `openshift/client-go` seems only have function for deployment `func (c *AppsV1Client) DeploymentConfigs(namespace string)` did i miss something?

Comment (juanvallejo) [reply pkg/kubectl/cmd/clusterinfo_dump.go]: @charrywanganthony sorry about that, the actual import path for the appsv1 client is `"k8s.io/client-go/kubernetes/typed/apps/v1"`

Comment (charrywanganthony) [reply pkg/kubectl/cmd/clusterinfo_dump.go]: @juanvallejo  @soltysh modified.

File: pkg/kubectl/cmd/clusterinfo_dump.go [hunk 4]
```diff
@@ -47,7 +48,8 @@ type ClusterInfoDumpOptions struct {
 	Namespaces    []string
 
 	Timeout          time.Duration
-	Clientset        kubernetes.Interface
+	AppsClientset    appsv1client.AppsV1Interface
```
Comment (soltysh) [inline pkg/kubectl/cmd/clusterinfo_dump.go]: Similarly `AppsClient` is the preferred name.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by charrywanganthony** [comment]
@juanvallejo @soltysh done.

**Comment by mkumatag** [comment]
I'm not sure how this one got skipped! very important feature in case of sos report.! don't we have any proper testcases to cover this scenario?

**Comment by mkumatag** [comment]
can someone help to cherrypick this to 1.11 release?
