### PR TITLE
Fixing EndpointSlice port validation

### LINKED ISSUE #84388: EndpointSlice breaks for services with long port names, which are legal on the Service
**What happened**:
No endpoints created in the EndpointSlice for my service due to the port on the service being too long. Logs show:
```
1 endpointslice_controller.go:229] Error syncing endpoint slices for service "istio-system/istio-pilot", retrying. Error: Error updating istio-pilot-g9hz4 EndpointSlice for Service istio-system/istio-pilot: EndpointSlice.discovery.k8s.io "istio-pilot-g9hz4" is invalid: ports[3].name: Invalid value: "http-legacy-discovery": must be no more than 15 characters
```

EndpointSlice created has no endpoint:
```
addressType: IP
apiVersion: discovery.k8s.io/v1alpha1
endpoints: null
kind: EndpointSlice
metadata:
  creationTimestamp: "2019-10-25T16:39:21Z"
  generateName: istio-pilot-
  generation: 1
  labels:
    kubernetes.io/service-name: istio-pilot
  name: istio-pilot-g9hz4
  namespace: istio-system
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: istio-pilot
    uid: a2b2ea09-541e-437b-adca-e4668ad0f875
  resourceVersion: "841"
  selfLink: /apis/discovery.k8s.io/v1alpha1/namespaces/istio-system/endpointslices/istio-pilot-g9hz4
  uid: a655116b-e6e8-450b-ada2-7497e47f9661
ports: null
```

**What you expected to happen**:
Service that works with Endpoints should work with EndpointSlice. If this is intentional, it should be clearly documented

**How to reproduce it (as minimally and precisely as possible)**:
Create a service with a long port name

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16
- Cloud provider or hardware configuration: kind

### PR DESCRIPTION
**Pull request by robscott**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This fixes EndpointSlice port validation to match the corresponding validation used by [Endpoints](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L5447) and [Services](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L4102) (`validation.IsDNS1123Label()`). It was previously using `validation.IsValidPortName()` which is used in other places like NetworkPolicy and Service `intOrStr` ports, but unfortunately should not have been used here.

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/84388

**Does this PR introduce a user-facing change?**:
```release-note
Fixed EndpointSlice port name validation to match Endpoint port name validation (allowing port names longer than 15 characters)
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
- Enhancement Issue: https://github.com/kubernetes/enhancements/issues/752

/sig network
/priority important-soon
/cc @liggitt @howardjohn

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

File: pkg/apis/discovery/validation/validation.go [hunk 1]
```diff
@@ -131,8 +131,8 @@ func validatePorts(endpointPorts []discovery.EndpointPort, fldPath *field.Path)
 		idxPath := fldPath.Index(i)
 
 		if len(*endpointPort.Name) > 0 {
-			for _, msg := range validation.IsValidPortName(*endpointPort.Name) {
-				allErrs = append(allErrs, field.Invalid(idxPath.Child("name"), endpointPort.Name, msg))
+			for _, msg := range validation.IsDNS1123Label(*endpointPort.Name) {
```
Comment (liggitt) [inline pkg/apis/discovery/validation/validation.go]: `allErrs = append(allErrs, apivalidation.ValidateDNS1123Label(...`

**Comment by liggitt** [comment]
need to update the API docs on the v1alpha1 EndpointPort Name field to match the docs for the ServicePort Name field

**Comment by liggitt** [comment]
is there a project or umbrella issue tracking bugs/PRs that block moving endpointslice to beta?

**Comment by robscott** [comment]
@liggitt I don't think I have permission to create a project to track this. Of course I've been tracking the deliverables we committed to in the KEP here: https://github.com/kubernetes/kubernetes/pull/84390. And then the enhancement issue is tracking most things related to EndpointSlices here https://github.com/kubernetes/enhancements/issues/752. Would be happy to add a list of blocking bugs to the beta PR, or if there's a way to track everything in a project that would also be great.

File: pkg/apis/discovery/validation/validation.go (hunk 1 above)
Comment (robscott) [reply pkg/apis/discovery/validation/validation.go]: How would I do that while maintaining the other information that I'm adding within the loop? `IsDNS1123Label` only returns a slice of strings as error messages, and in this loop I'm adding the `field.Invalid` error type, the path of this invalid port name, and the value that is invalid, all in addition to the actual message returned from `IsDNS1123Label`. This is the only way I've seen it done elsewhere, but admittedly this pattern is only really used in the core validation package other than this.

Comment (liggitt) [reply pkg/apis/discovery/validation/validation.go]: ValidateDNS1123Label constructs the Invalid field errors, using the field path you pass in

Comment (liggitt) [reply pkg/apis/discovery/validation/validation.go]: See use in validating endpoint ports here:

https://github.com/kubernetes/kubernetes/blob/b6bf0d6d8e2f19cf6b7840a7443e0e892da7697d/pkg/apis/core/validation/validation.go#L5447

Comment (robscott) [reply pkg/apis/discovery/validation/validation.go]: That's actually a helper function within the core validation package that calls the function I'm using `validation.IsDNS1123Label` (https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/validation.go#L118). It felt strange to require the core validation package here for that helper func, and overkill to rewrite that function here. Should I require the core validation package here to use that helper function?

**Comment by robscott** [comment]
@liggitt mind adding another lgtm on this PR? Apparently I forgot to update generated proto the first time.
