### PR TITLE
Make kubectl edit not convert GV on edits

### LINKED ISSUE #23378: autoscaling/v1 groupversion does not work well with validation/edit/export
As noted here: https://github.com/openshift/origin/issues/8213

Attempting to create the following HPA:

``` yml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: test-autoscaler 
spec:
  scaleRef:
    kind: DeploymentConfig 
    name: frontend 
    apiVersion: v1
  minReplicas: 1 
  maxReplicas: 10  
```

We get the following error:

``` sh
$ kubectl create -f hpa.yaml
kubectl create --validate=false -f hpa.yaml
The HorizontalPodAutoscaler "test-autoscaler" is invalid.

* spec.scaleRef.kind: Required value
* spec.scaleRef.name: Required value
```

This doesn't make sense as the values that seem to be missing in fact are in the YAML -- the issue is that `scaleRef` is the name of the reference in the `extensions/v1beta1` groupversion, whereas `scaleTargetRef` is the name in `autoscaling/v1`.

Attempting `kubectl edit` and making any change to the HPA will result in:

```
$ kubectl edit hpa test-autoscaler
error: apiVersion should not be changed
```

even if no changes to `apiVersion` field were made

Furthermore, when exporting using `kubectl get -o yaml`, the groupversion emitted is `extensions/v1beta1` even if the HPA was originally created as `autoscaling/v1` - this may be the desired behavior but it is suprising nonetheless.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.1588+e44c8e6661c931", GitCommit:"e44c8e6661c931f7fd434911b0d3bca140e1df3a", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0-36-g4a3f9c5", GitCommit:"4c91857", GitTreeState:"not a git tree"}
```

/cc @liggitt @DirectXMan12

### PR DESCRIPTION
**Pull request by DirectXMan12**
Previously, kubectl edit was using a decoder to load in edits that
converted to the internal version.  It would then re-encode this
decoded value to produce a patch.  However, if you were editing
in the object in a GroupVersion that was not the internal version,
this would cause the kubectl edit command to attempt to produce
a patch which changed the GroupVersion, which would fail.

Now, we use a plain deserializer instead, so no conversion or
defaulting occurs when loading in the edited file.

Ref #23378

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @stevekuznetsov cc @AdoHe

File: pkg/kubectl/cmd/edit.go [hunk 1]
```diff
@@ -120,12 +120,18 @@ func RunEdit(f *cmdutil.Factory, out, errOut io.Writer, cmd *cobra.Command, args
 		return err
 	}
 
+	// NB: we use `f.Decoder(false)` to get a plain deserializer for
```
Comment (ncdc) [inline pkg/kubectl/cmd/edit.go]: I would suggest moving this comment to immediately before the f.Decoder(false) line.

Comment (DirectXMan12) [inline pkg/kubectl/cmd/edit.go]: I would, but I didn't want to have a large block comment in the middle of a struct instantiation.  WDYT?

Comment (ncdc) [inline pkg/kubectl/cmd/edit.go]: I don't think that's an issue. If the comment isn't living right next to this line, I could foresee someone changing it back to true without noticing the comment.

Comment (DirectXMan12) [inline pkg/kubectl/cmd/edit.go]: ACK

**Comment by brendandburns** [comment]
Over to @janetkuo since she knows this code better than I do.

**Comment by janetkuo** [comment]
@k8s-bot e2e test this issue: #IGNORE (Build step 'Execute shell' marked build as failure?)

**Comment by janetkuo** [comment]
@k8s-bot node e2e test this

**Comment by janetkuo** [comment]
@DirectXMan12 Do you plan to solve the get/validation issue in this PR too? If not, the "fixes" keyword needs to be removed from the PR description. Otherwise the issue will be closed.

**Comment by DirectXMan12** [comment]
@janetkuo I recall not being able to reproduce the validation issue, just the edit issue (which is why, IIRC, I put it as fixes).  I'll double-check that.

**Comment by DirectXMan12** [comment]
@janetkuo just double checked, and I was able to repeat the validation "issue", although I'm not entirely certain it's an issue -- if you don't explicitly pass `--validate=false`, you get a nice message about how you are missing `scaleTargetRef`.  It appears to only be if you explicitly pass `--validate=false`, at which point kubectl happily converts to the internal version and submits the request.

**Comment by janetkuo** [comment]
Let's merge this first and keep the issue open then.
