### PR TITLE
set default value of KUBE_MASTER_URL to empty in e2e test

### LINKED ISSUE #12661: e2e testing against local cluster failed to create clientset
**What happened**:

e2e framework failed to create client against local cluster
```
May 14 11:16:30.663: INFO: >>> kubeConfig: /var/run/kubernetes/admin.kubeconfig
F0514 11:16:30.665844  135309 e2e.go:81] Error loading client: host must be a URL or a host:port pair: "https://"
```
**What you expected to happen**:

e2e testing used to load kubeconfig and talk to local cluster successfully

**How to reproduce it (as minimally and precisely as possible)**:

follow https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md#local-clusters:

```
$ go get -u k8s.io/test-infra/kubetest
$ cd $GOPATH/src/k8s.io/kubernetes
$ git fetch upstream
$ git checkout upstream/master
$ make clean all
$ sudo PATH=$PATH hack/local-up-cluster.sh
```
in another terminal
```
$ kubetest --build # this is not necessary because we did `make all` before
$ export KUBECONFIG=/var/run/kubernetes/admin.kubeconfig
$ kubetest --provider=local --test --test_args="--ginkgo.focus=Secrets"
```

**Please provide links to example occurrences, if any**:

**Anything else we need to know?**:

[TestContext.KubeConfig](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/util.go#L2005) seems to be set successfully, but restconfig.Host is somehow set to `https://`. Loading the same kubeconfig with a [standalone client](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/examples/out-of-cluster-client-configuration/main.go) succeeded.

### PR DESCRIPTION
**Pull request by langyenan**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
kubeconfig is correctly set, but e2e test failed to create clientset

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/test-infra/issues/12661

**Special notes for your reviewer**:
`KUBE_MASTER_URL` is set to `https://` when `KUBE_MASTER_IP` is not set, kubeconfig configuration is then overrided with `https://` in the code below:

https://github.com/kubernetes/kubernetes/blob/9790262f128aa9d27733dac46619af1d18459439/test/e2e/framework/util.go#L918

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: hack/ginkgo-e2e.sh [hunk 1]
```diff
@@ -74,7 +74,12 @@ else
     prepare-e2e
 
     detect-master >/dev/null
-    KUBE_MASTER_URL="${KUBE_MASTER_URL:-https://${KUBE_MASTER_IP:-}}"
+
```
Comment (cblecker) [inline hack/ginkgo-e2e.sh]: Something like this would be simpler:
```suggestion
    KUBE_MASTER_URL="${KUBE_MASTER_URL:-}"
    if [[ -z "${KUBE_MASTER_URL:-}" && -n "${KUBE_MASTER_IP:-}" ]]
      KUBE_MASTER_URL="https://${KUBE_MASTER_IP}"
    fi
```

Comment (langyenan) [reply hack/ginkgo-e2e.sh]: That's true, thanks!
