### PR TITLE
fix panic with SIGSEGV in kubeadm certs check-expiration

### LINKED ISSUE #124120: panic with SIGSEGV in kubeadm certs check-expiration
### What happened?

```
$ kubeadm certs check-expiration 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16c0556]

goroutine 1 [running]:
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/renewal.fileExists({0xc000501360?, 0x1c1ab60?})
        cmd/kubeadm/app/phases/certs/renewal/readwriter.go:74 +0x56
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/renewal.(*kubeConfigReadWriter).Exists(0x1c1ab60?)
        cmd/kubeadm/app/phases/certs/renewal/readwriter.go:124 +0x1e
k8s.io/kubernetes/cmd/kubeadm/app/phases/certs/renewal.(*Manager).CertificateExists(0x21f6180?, {0x1f0b722, 0xa})
        cmd/kubeadm/app/phases/certs/renewal/manager.go:325 +0x4a
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdCertsExpiration.func1(0xc0005c1400?, {0x3259d80?, 0x4?, 0x1f03ff0?})
        cmd/kubeadm/app/cmd/certs.go:403 +0x234
github.com/spf13/cobra.(*Command).execute(0xc000004600, {0x3259d80, 0x0, 0x0})
        vendor/github.com/spf13/cobra/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00027d800)
        vendor/github.com/spf13/cobra/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(0x21f5ee0?)
        vendor/github.com/spf13/cobra/command.go:992 +0x13
k8s.io/kubernetes/cmd/kubeadm/app.Run()
        cmd/kubeadm/app/kubeadm.go:50 +0x155
main.main()
        cmd/kubeadm/kubeadm.go:25 +0x13
$
```
When the command is run with superuser privileges, it prints the requested information.
### What did you expect to happen?

Print a warning that files could not be read due to insufficient permission, or that information was missing (e.g., when the /etc/kubernetes directory is not initialized).
When the directory is readable, it works as expected:
```
$ kubeadm certs check-expiration
CERTIFICATE                          EXPIRES   RESIDUAL TIME   CERTIFICATE AUTHORITY   EXTERNALLY MANAGED
!MISSING! admin.conf                                                                   
!MISSING! apiserver                                                                    
!MISSING! apiserver-etcd-client                                                        
!MISSING! apiserver-kubelet-client                                                     
!MISSING! controller-manager.conf                                                      
!MISSING! etcd-healthcheck-client                                                      
!MISSING! etcd-peer                                                                    
!MISSING! etcd-server                                                                  
!MISSING! front-proxy-client                                                           
!MISSING! scheduler.conf                                                               

CERTIFICATE AUTHORITY      EXPIRES   RESIDUAL TIME   EXTERNALLY MANAGED
!MISSING! ca                                         
!MISSING! etcd-ca                                    
!MISSING! front-proxy-ca                             
$ 
```
where OS and kubeadm version detail was:
```
$ uname -a
Linux z620 6.8.0-11-generic #11-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb 14 00:29:05 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/os-release
PRETTY_NAME="Ubuntu Noble Numbat (development branch)"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.8", GitCommit:"fc11ff34c34bc1e6ae6981dc1c7b3faa20b1ac2d", GitTreeState:"clean", BuildDate:"2024-03-15T00:05:37Z", GoVersion:"go1.21.8", Compiler:"gc", Platform:"linux/amd64"}
```

### How can we reproduce it (as minimally and precisely as possible)?

Issue the command `kubeadm certs check-expiration` as a normal user when the directory /etc/kubernetes/pki exists but not readable.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
The connection to the server my-private-host:6443 was refused - did you specify the right host or port?
```

</details>

### Cloud provider

<details>
Bare metal
</details>

### OS version

<details>

```console
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux acs-clb16jm33b70349 5.15.0-101-generic #111-Ubuntu SMP Tue Mar 5 20:16:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.3", GitCommit:"6813625b7cd706db5bc7388921be03071e1a492d", GitTreeState:"clean", BuildDate:"2024-03-15T00:06:16Z", GoVersion:"go1.21.8", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Install tools

<details>
apt-get install kubeadm (source repo: k8s.io)
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #124120

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: fix panic in the command "kubeadm certs check-expiration" when "/etc/kubernetes/pki" exists but cannot be read.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/release-note-edit

```release-note
kubeadm: fix panic in the command "kubeadm certs check-expiration" when "/etc/kubernetes/pki" exists but cannot be read.
```

File: cmd/kubeadm/app/phases/certs/renewal/readwriter_test.go [hunk 1]
```diff
@@ -239,7 +239,7 @@ func TestFileExists(t *testing.T) {
 	}
 	for _, tt := range tests {
 		t.Run(tt.name, func(t *testing.T) {
-			if got := fileExists(tt.filename); got != tt.want {
+			if got, _ := fileExists(tt.filename); got != tt.want {
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/certs/renewal/readwriter_test.go:242]: after this change there is a missing unit test case for the `return false, err` return of `func fileExists(filename string) (bool, error) {` but i don't insist of adding it.

we could use os.Chmod() or a os.WriteFile with a restrictive FileMode, but then this test will not work on Windows, i think.

so fine to leave this test case out for now.

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve
/triage accepted
/priority important-longterm

thanks for the quick fix.

**Comment by neolit123** [comment]
let's see if this can be added in 1.30.0

/milestone v1.30

**Comment by neolit123** [comment]
please send backport PRs for 1.29, 1.28, 1.27

https://kubernetes.io/releases/
