### PR TITLE
Retry assigning CIDRs

### LINKED ISSUE #28879: If CIDRAllocator fails to update CIDR in Node object it won't retry.
Currently CIDRAllocator observes only Node creations and deletions. When Node is created it tries to assign a CIDR to it. If it fails for any reason (no available CIDRs, run out of Node update retries) it won't ever retry, as the Node won't be "created" again. We need to add a mechanism for retrying assignments in such cases.

cc @kubernetes/goog-control-plane

### PR DESCRIPTION
**Pull request by gmarek**
Fix #28879, ref #29064

cc @bgrant0607 @bprashanth @alex-mohr

### CODE REVIEW

File: pkg/controller/node/cidr_allocator.go [hunk 1]
```diff
@@ -139,11 +162,19 @@ func (r *rangeAllocator) occupyCIDR(node *api.Node) error {
...
+		return nil
+	}
+	if !r.leaseNode(node.Name) {
+		glog.V(2).Infof("Node %v is already in a process of CIDR assignment.", node.Name)
+		return nil
+	}
 	if node.Spec.PodCIDR != "" {
 		return r.occupyCIDR(node)
 	}
 	podCIDR, err := r.cidrs.allocateNext()
```
Comment (dims) [inline pkg/controller/node/cidr_allocator.go]: Quick question : when `r.cidrs.allocateNext()` returns an error, we don't call `r.releaseNode(node.Name)`. Is this by design?

Comment (gmarek) [inline pkg/controller/node/cidr_allocator.go]: This is still WIP PR:)

Comment (dims) [inline pkg/controller/node/cidr_allocator.go]: haha. i am just learning by reviewing, so feel free to tell me to go away :)

File: pkg/controller/node/cidr_allocator.go [hunk 2]
```diff
@@ -122,7 +129,24 @@ func NewCIDRRangeAllocator(client clientset.Interface, clusterCIDR *net.IPNet, s
 	return ra, nil
 }
 
+func (r *rangeAllocator) leaseNode(nodeName string) bool {
```
Comment (wojtek-t) [inline pkg/controller/node/cidr_allocator.go]: nit: I understand your motivation of calling it "lease", but to be honest, it would be much simpler to follow if you call those methods:
"insertNodeInProcessing"
"deleteNodeInProcessing"

WDYT?

File: pkg/controller/node/cidr_allocator.go [hunk 3]
```diff
@@ -139,11 +163,19 @@ func (r *rangeAllocator) occupyCIDR(node *api.Node) error {
 // AllocateOrOccupyCIDR looks at the given node, assigns it a valid CIDR
 // if it doesn't currently have one or mark the CIDR as used if the node already have one.
 func (r *rangeAllocator) AllocateOrOccupyCIDR(node *api.Node) error {
+	if node == nil {
+		return nil
+	}
+	if !r.leaseNode(node.Name) {
```
Comment (wojtek-t) [inline pkg/controller/node/cidr_allocator.go]: Please add a WARNING comment that anyone adding some "return" statements to this method should think about releasing the node.

File: pkg/controller/node/cidr_allocator.go [hunk 4]
```diff
@@ -217,9 +250,13 @@ func (r *rangeAllocator) updateCIDRAllocation(data nodeAndCIDR) error {
 	}
 	if err != nil {
 		recordNodeStatusChange(r.recorder, node, "CIDRAssignmentFailed")
-		glog.Errorf("CIDR assignment for node %v failed: %v. Releasing allocated CIDR", data.nodeName, err)
-		if releaseErr := r.cidrs.release(data.cidr); releaseErr != nil {
-			glog.Errorf("Error releasing allocated CIDR for node %v: %v", data.nodeName, releaseErr)
+		// We accept the fact that we may leek CIDRs here. This is safer than releasing them in case when we don't know
```
Comment (wojtek-t) [inline pkg/controller/node/cidr_allocator.go]: nit: can you make those comments fit the lines?

File: pkg/controller/node/nodecontroller.go [hunk 5]
```diff
@@ -244,6 +244,26 @@ func NewNodeController(
 					glog.Errorf("Error allocating CIDR: %v", err)
 				}
 			},
+			UpdateFunc: func(_, obj interface{}) {
+				node := obj.(*api.Node)
+				// If the PodCIDR is not empty we either:
+				// - already processed a Node that already had a CIDR after NC restarted (cidr is marked as used),
```
Comment (wojtek-t) [inline pkg/controller/node/nodecontroller.go]: nit: can you make those comments fit the lines?

File: pkg/controller/node/cidr_allocator.go (hunk 2 above)
Comment (gmarek) [inline pkg/controller/node/cidr_allocator.go]: Done-ish

File: pkg/controller/node/cidr_allocator.go (hunk 3 above)
Comment (gmarek) [inline pkg/controller/node/cidr_allocator.go]: Done.

File: pkg/controller/node/nodecontroller.go [hunk 6]
```diff
@@ -244,6 +244,26 @@ func NewNodeController(
...
+				// - already processed a Node successfully and allocated a CIDR for it (cidr is marked as used),
+				// - already processed a Node but we did saw a "timeout" response and request eventually got through
+				//   in this case we haven't released the allocated CIDR (cidr is still marked as used).
+				// There's a possible error here:
+				// - NC sees a new Node and assigns a CIDR X to it,
+				// - Update Node call fails with a timeout,
+				// - Node is updated by some other component, NC sees an update and assigns CIDR Y to the Node,
+				// - Both CIDR X and CIDR Y are marked as used in the local cache, even though Node sees only CIDR Y
+				// Restart of NC fixes the issue.
```
Comment (wojtek-t) [inline pkg/controller/node/nodecontroller.go]: Please state explicitly that the problem is that in memory an unoccupied CIDR is marked as occupied, which prevents it from being allocated to something. But the state of the cluster itself is correct.

File: pkg/controller/node/cidr_allocator.go (hunk 4 above)
Comment (gmarek) [inline pkg/controller/node/cidr_allocator.go]: Done.

File: pkg/controller/node/nodecontroller.go (hunk 6 above)
Comment (gmarek) [inline pkg/controller/node/nodecontroller.go]: Done.

File: pkg/controller/node/nodecontroller.go (hunk 5 above)
Comment (gmarek) [inline pkg/controller/node/nodecontroller.go]: Done.

**Comment by wojtek-t** [comment]
LGTM

**Comment by bprashanth** [comment]
Have grokked the fix yet (too early), do we need to cherry pick this? @roberthbailey

**Comment by gmarek** [comment]
verification fix

File: pkg/controller/node/cidr_allocator.go [hunk 7]
```diff
@@ -217,9 +252,14 @@ func (r *rangeAllocator) updateCIDRAllocation(data nodeAndCIDR) error {
 	}
 	if err != nil {
 		recordNodeStatusChange(r.recorder, node, "CIDRAssignmentFailed")
-		glog.Errorf("CIDR assignment for node %v failed: %v. Releasing allocated CIDR", data.nodeName, err)
-		if releaseErr := r.cidrs.release(data.cidr); releaseErr != nil {
-			glog.Errorf("Error releasing allocated CIDR for node %v: %v", data.nodeName, releaseErr)
+		// We accept the fact that we may leek CIDRs here. This is safer than releasing
```
Comment (bgrant0607) [inline pkg/controller/node/cidr_allocator.go]: s/leek/leak/

**Comment by roberthbailey** [comment]
@gmarek does this need a cherry pick into the 1.3 branch?

**Comment by fabioy** [comment]
@gmarek Ping on this. If this is needed for 1.3, please create a cherrypick PR. Thanks.

**Comment by wojtek-t** [comment]
@fabioy - @gmarek is on vacation until end of week. If you think this should be cherrypicked, I can create a PR tomorrow.

**Comment by fabioy** [comment]
@wojtek-t This can wait. I was wondering if this needed to be in for 1.3.3, but it doesn't seem like it. I can put it on the next patch release.

**Comment by fabioy** [comment]
@gmarek,@wojtek-t Please create a cherrypick PR for this. Thank you.
