### PR TITLE
Make nodeports scheduling plugin restartable initContainer aware

### LINKED ISSUE #132037: kube-scheduler does not consider hostPort ports used by initContainers when scheduling
### What happened?

When running two pods that both use hostNetwork and have sidecar initContainers (restartPolicy: Always) using the same port, kube-scheduler allows the pods to be scheduled on the same node.



### What did you expect to happen?

kube-scheduler does not schedule these two pods on the same node, following the behavior for pods using hostNetwork ports via a main container.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a kind cluster: `kind create cluster`.  The cluster only has one node.
2. Apply p1:
   ```
   apiVersion: v1
   kind: Pod
   metadata:
     name: p1
   spec:              
     hostNetwork: true
     dnsPolicy: ClusterFirstWithHostNet
     initContainers:
     - name: init
       restartPolicy: Always    
       image: python:3.12                                                                                                                                                                                                            
       command:
       - /bin/bash
       - -c
       - python -m http.server 8081
       ports:
       - containerPort: 8081
     containers:
     - name: main
       image: python:3.12
       command:
       - /bin/bash
       - -c
       - sleep 10000
   ```
3. Apply p2:
   ```
   apiVersion: v1
   kind: Pod
   metadata:
     name: p2
   spec:
     hostNetwork: true
     dnsPolicy: ClusterFirstWithHostNet
     initContainers:
     - name: init
       restartPolicy: Always    
       image: python:3.12                                                                                                                                                                                                            
       command:
       - /bin/bash
       - -c
       - python -m http.server 8081
       ports:
       - containerPort: 8081
     containers:
     - name: main
       image: python:3.12
       command:
       - /bin/bash
       - -c
       - sleep 10000
   ```
4. p2 is scheduled (and crashing because p1 is already using the port).


### Anything else we need to know?

kube-scheduler already accounts for hostNetwork ports used by main containers.  For example:

1. Create a kind cluster: `kind create cluster`.  The cluster only has one node.
2. Apply p1:
   ```
   apiVersion: v1
   kind: Pod
   metadata:
     name: p1
   spec:              
     hostNetwork: true
     dnsPolicy: ClusterFirstWithHostNet
     containers:
     - name: main
       image: python:3.12
       command:
       - /bin/bash
       - -c
       - python -m http.server 8081
       ports:
       - containerPort: 8081
   ```
3. Apply p2:
   ```
   apiVersion: v1
   kind: Pod
   metadata:
     name: p2
   spec:
     hostNetwork: true
     dnsPolicy: ClusterFirstWithHostNet
     containers:
     - name: main
       image: python:3.12
       command:
       - /bin/bash
       - -c
       - python -m http.server 8081
       ports:
       - containerPort: 8081
   ```
4. p2 is not scheduled: `Warning  FailedScheduling  3m7s  default-scheduler  0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.9
Kustomize Version: v5.4.2
Server Version: v1.31.1
```

</details>


### Cloud provider

<details>
local kind cluster
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by avrittrohwer**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Fixes a bug where hostPorts used by restartable initContainers are not considered by the nodeports scheduling plugin.

#### Which issue(s) this PR fixes:

Fixes #132037

#### Special notes for your reviewer:

This was just the simplest proof-of-concept for fixing the bug, happy to changes in approach

#### Does this PR introduce a user-facing change?

```release-note
Extends the nodeports scheduling plugin to consider hostPorts used by restartable init containers.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/integration/scheduler/scheduler_test.go [hunk 1]
```diff
@@ -638,3 +638,177 @@ func TestNodeEvents(t *testing.T) {
...
+	if err := testutils.DeletePod(testCtx.ClientSet, i2.Name, testCtx.NS.Name); err != nil {
+		t.Errorf("Pod %v did not delete: %v", i2.Name, err)
+	}
+	// 9.2 verify c3 is scheduled
+	err = testutils.WaitForPodToScheduleWithTimeout(testCtx.Ctx, testCtx.ClientSet, c3, time.Second*5)
+	if err != nil {
+		t.Errorf("Pod %s didn't schedule: %v", c3.Name, err)
+	}
+
+	// Clean up
```
Comment (toVersus) [inline test/integration/scheduler/scheduler_test.go:809]: nit: Since we're not running multiple test cases using table-driven testing, cleanup might not be necessary here.

File: pkg/scheduler/framework/plugins/nodeports/node_ports.go [hunk 2]
```diff
@@ -69,6 +69,16 @@ func (pl *NodePorts) Name() string {
 func getContainerPorts(pods ...*v1.Pod) []*v1.ContainerPort {
 	ports := []*v1.ContainerPort{}
 	for _, pod := range pods {
+		for j := range pod.Spec.InitContainers {
```
[the remark this answers is not in the document]
Comment (SergeyKanzhelev) [reply pkg/scheduler/framework/plugins/nodeports/node_ports.go:72]: I would suggest we make a first PR with only restartable init containers. So it can be cherry-picked to 1.33 if we decide to. And more controversial second PR to do it for all init containers. wdyt?

[the remark this answers is not in the document]
Comment (toVersus) [reply pkg/scheduler/framework/plugins/nodeports/node_ports.go:72]: > Have you tried if kubelet will be even OK with the host port on an init container?

I tried the following Pod manifest to test if hostPort works in an init container.

```yaml
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: init-container-hostport-check
spec:
  terminationGracePeriodSeconds: 3
  hostNetwork: true
  initContainers:
  - name: check-hostport
    image: curlimages/curl:8.7.1
    env:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    command:
    - /bin/sh
    - -c
    - |
      echo "Starting test server on port 8080..."
      nohup sh -c "while true; do echo -e 'HTTP/1.1 200 OK\n\nHello' | nc -l -p 8080; done" &
      sleep 2
      echo "Checking hostPort access via Node IP: \$NODE_IP"
      for i in \$(seq 1 10); do
        echo "Attempt \$i..."
        if curl -sSL -m 2 "http://\$NODE_IP:8080"; then
          echo "hostPort is reachable!"
          exit 0
        fi
        echo "hostPort not reachable yet..."
        sleep 1
      done
      echo "hostPort check failed after 10 attempts"
      exit 1
    ports:
    - containerPort: 8080
      hostPort: 8080
  containers:
  - name: sleep
    image: busybox:1.36
    command:
    - sleep
    - infinity
EOF
```

And it worked, so hostPort is supported even for regular init containers.

```console
❯ stern .
+ init-container-hostport-check › sleep
+ init-container-hostport-check › check-hostport
init-container-hostport-check check-hostport Starting test server on port 8080...
init-container-hostport-check check-hostport Checking hostPort access via Node IP: 192.168.97.2
init-container-hostport-check check-hostport Attempt 1...
init-container-hostport-check check-hostport GET / HTTP/1.1
init-container-hostport-check check-hostport Host: 192.168.97.2:8080
init-container-hostport-check check-hostport User-Agent: curl/8.7.1
init-container-hostport-check check-hostport Accept: */*
init-container-hostport-check check-hostport
init-container-hostport-check check-hostport Hello
init-container-hostport-check check-hostport hostPort is reachable!
- init-container-hostport-check › check-hostport

❯ kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
init-container-hostport-check   1/1     Running   0          3m9s
```

[the remark this answers is not in the document]
Comment (toVersus) [reply pkg/scheduler/framework/plugins/nodeports/node_ports.go:72]: > yes, a small back compat issue though. If one would use host port for the duration of a init container, assuming it will never run again while some other Pod is running. This will break that scenario.

Yeah, with regular init containers, the behavior can be unreliable depending on timing, which makes things tricky. We need to take into account whether the initContainer is actually running, but the question is whether it's worth doing something that complex for the benefit it provides.

> I would suggest we make a first PR with only restartable init containers. So it can be cherry-picked to 1.33 if we decide to. And more controversial second PR to do it for all init containers. wdyt?

If it's going to be backported, I agree that.

[the remark this answers is not in the document]
Comment (SergeyKanzhelev) [reply pkg/scheduler/framework/plugins/nodeports/node_ports.go:72]: > We need to take into account whether the initContainer is actually running, but the question is whether it's worth doing something that complex for the benefit it provides.

I do not suggest to account for this. I am mostly concerned that something that can be scheduled today will not be able to be scheduled if we will add this check for init containers. So we will break backward compatibility. I *think* it is ok for 1.34, but backporting to 1.33 will be a problem.

File: pkg/scheduler/framework/plugins/nodeports/node_ports_test.go [hunk 3]
```diff
@@ -143,6 +143,33 @@ func TestNodePorts(t *testing.T) {
 			name:             "UDP hostPort conflict due to 0.0.0.0 hostIP",
 			wantFilterStatus: framework.NewStatus(framework.Unschedulable, ErrReason),
 		},
+		{
```
[the remark this answers is not in the document]
Comment (avrittrohwer) [reply pkg/scheduler/framework/plugins/nodeports/node_ports_test.go:145]: yup, removed

File: pkg/scheduler/framework/plugins/nodeports/node_ports.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (avrittrohwer) [reply pkg/scheduler/framework/plugins/nodeports/node_ports.go]: Updated to only consider initContainers with restartPolicy: Always

File: test/integration/scheduler/scheduler_test.go (hunk 1 above)
Comment (avrittrohwer) [reply test/integration/scheduler/scheduler_test.go]: Removed

File: pkg/scheduler/util/utils.go [hunk 4]
```diff
@@ -187,3 +187,38 @@ func As[T any](oldObj, newobj interface{}) (T, T, error) {
 	}
 	return oldTyped, newTyped, nil
 }
+
+// GetHostPorts returns the used host ports of pod containers and sidecar initContainers.
+func GetHostPorts(pod *v1.Pod) []v1.ContainerPort {
```
Comment (SergeyKanzhelev) [inline pkg/scheduler/util/utils.go:193]: maybe for now we can add a note that we do not consider regular init containers to make it explicit.

**Review by SergeyKanzhelev — COMMENTED** [review]
this lgtm, but somebody from sig scheduling need to take a look

File: pkg/scheduler/util/utils.go (hunk 4 above)
Comment (avrittrohwer) [reply pkg/scheduler/util/utils.go:193]: Changed to "GetHostPorts returns the used host ports of pod containers and initContainers with restartPolicy: Always."

**Comment by SergeyKanzhelev** [comment]
/retitle Make nodeports scheduling plugin restartable initContainer aware

**Comment by SergeyKanzhelev** [comment]
/lgtm

/assign @dims 

as per bot suggestion

**Comment by dims** [comment]
@kubernetes/sig-scheduling-leads can one of you take a pass at this as well?

**Comment by SergeyKanzhelev** [comment]
@kubernetes/sig-scheduling-leads also would you be OK with the cherry-pick of this to 1.33?

I think the right course of actions:

1. Merge and cherry-pick this PR.
2. Enforce hostPorts for regular init containers in 1.34.

File: pkg/scheduler/framework/plugins/nodeports/node_ports.go [hunk 5]
```diff
@@ -51,7 +51,7 @@ const (
 	ErrReason = "node(s) didn't have free ports for the requested pod ports"
 )
 
-type preFilterState []*v1.ContainerPort
+type preFilterState []v1.ContainerPort
```
Comment (macsko) [inline pkg/scheduler/framework/plugins/nodeports/node_ports.go:54]: Is there a reason for this change (removal of pointer)?

File: pkg/scheduler/util/utils.go [hunk 6]
```diff
@@ -187,3 +187,39 @@ func As[T any](oldObj, newobj interface{}) (T, T, error) {
 	}
 	return oldTyped, newTyped, nil
 }
+
+// GetHostPorts returns the used host ports of pod containers and
+// initContainers with restartPolicy: Always.
+func GetHostPorts(pod *v1.Pod) []v1.ContainerPort {
+	ports := []v1.ContainerPort{}
```
Comment (macsko) [inline pkg/scheduler/util/utils.go]: You don't need to initialize the slice:
```suggestion
	var ports []v1.ContainerPort
```

File: pkg/scheduler/util/utils.go [hunk 7]
```diff
@@ -187,3 +187,39 @@ func As[T any](oldObj, newobj interface{}) (T, T, error) {
...
+	if pod == nil {
+		return ports
+	}
```
Comment (macsko) [inline pkg/scheduler/util/utils.go:197]: Isn't this check redundant?

File: test/integration/scheduler/scheduler_test.go [hunk 8]
```diff
@@ -638,3 +638,171 @@ func TestNodeEvents(t *testing.T) {
...
 }
+
+func TestConflictingHostPorts(t *testing.T) {
+	// The test verifies that pods with conflicting hostPorts are not scheduled
+	// on the same node. It tests conflicting hostPorts used by both containers
+	// and initContainers block scheduling (container blocks container,
+	// container blocks initContainer, initContainer blocks initContainer,
+	// initContainer blocks container).
+	//
+	// The scenario we are testing is the following:
```
Comment (macsko) [inline test/integration/scheduler/scheduler_test.go]: Maybe add a step with regular InitContainers - those which HostPorts are unsupported by NodePorts plugin? Is it possible to add it?

File: test/integration/scheduler/scheduler_test.go [hunk 9]
```diff
@@ -638,3 +638,171 @@ func TestNodeEvents(t *testing.T) {
...
+				HostPort:      8001,
+				Protocol:      v1.ProtocolTCP,
+			},
+		},
+	}))
+	if err != nil {
+		t.Fatalf("Failed to create Pod c1: %v", err)
+	}
+	// 1.3 verify c1 is scheduled
+	err = testutils.WaitForPodToScheduleWithTimeout(testCtx.Ctx, testCtx.ClientSet, c1, time.Second*5)
```
Comment (macsko) [inline test/integration/scheduler/scheduler_test.go]:
```suggestion
	err = testutils.WaitForPodToScheduleWithTimeout(testCtx.Ctx, testCtx.ClientSet, c1, 5*time.Second)
```

File: pkg/scheduler/framework/types_test.go [hunk 10]
```diff
@@ -2172,3 +2172,331 @@ func TestNodeInfoKMetadata(t *testing.T) {
 		tCtx.Fatalf("unexpected output:\n%s", output)
 	}
 }
+
+func TestUpdateUsedPorts_PodAdd(t *testing.T) {
+	testCases := []struct {
```
Comment (macsko) [inline pkg/scheduler/framework/types_test.go:2177]: Please add a case like:
```go
		{
			ports: HostPortInfo{},
			pod: st.MakePod().
				ContainerPort([]v1.ContainerPort{
					{
						ContainerPort: 8001,
						Protocol:      v1.ProtocolTCP,
					}}).
				Obj(),
			want: HostPortInfo{},
		},
```

Comment (macsko) [reply pkg/scheduler/framework/types_test.go:2177]: And add a similar one to PodRemove test

**Comment by macsko** [comment]
> would you be OK with the cherry-pick of this to 1.33?

Are those InitContainers with HostPorts a pretty new feature or this bug just got discovered now after a few releases? And is it that serious that we should consider cherry-picking it?

File: pkg/scheduler/framework/plugins/nodeports/node_ports.go (hunk 5 above)
Comment (avrittrohwer) [reply pkg/scheduler/framework/plugins/nodeports/node_ports.go:54]: The original code for getContainerPorts returned back pointers into the passed v1.Pod object but this made the looping logic more complicated:

`container := &pod.Spec.Containers[j]`, `ports = append(ports, &container.Ports[k])`

Because ContainerPort has only scalar fields and none of the other uses of preFilterState needed pointers I felt it was simpler to just return them back as values

File: pkg/scheduler/util/utils.go (hunk 7 above)
Comment (avrittrohwer) [reply pkg/scheduler/util/utils.go:197]: Without this check, `for _, c := range pod.Spec.InitContainers` results in a nil pointer dereference if pod is nil

**Comment by SergeyKanzhelev** [comment]
> > would you be OK with the cherry-pick of this to 1.33?
> 
> Are those InitContainers with HostPorts a pretty new feature or this bug just got discovered now after a few releases? And is it that serious that we should consider cherry-picking it?

My understanding is that init containers may have a host port, but was always ignored for this check. Sidecar (restartable) init containers were GA'd in 1.33. My thinking it that since sidecars are new, we can backport the fix with very small risk to 1.33. Enforcing this check on regular init containers sounds like a bigger risk so I think we should not cherry pick and enforce in 1.34 only. Maybe even with the separate feature gate in case it will break something big time.

File: test/integration/scheduler/scheduler_test.go (hunk 9 above)
Comment (avrittrohwer) [reply test/integration/scheduler/scheduler_test.go]: Changed.

File: test/integration/scheduler/scheduler_test.go (hunk 8 above)
Comment (avrittrohwer) [reply test/integration/scheduler/scheduler_test.go]: I refactored this to be table-driven and added non-restartable initContainer test cases.

File: pkg/scheduler/util/utils.go (hunk 6 above)
Comment (avrittrohwer) [reply pkg/scheduler/util/utils.go]: Changed.

File: pkg/scheduler/framework/types_test.go (hunk 10 above)
Comment (avrittrohwer) [reply pkg/scheduler/framework/types_test.go:2177]: Added

**Comment by SergeyKanzhelev** [comment]
/kind api-change

marking as API change to highlight the fact of possible back compat issue

**Comment by SergeyKanzhelev** [comment]
@macsko please re-review.

File: pkg/scheduler/util/utils.go (hunk 7 above)
Comment (macsko) [reply pkg/scheduler/util/utils.go:197]: In what scenarios a pod could be nil here?

File: pkg/scheduler/framework/plugins/nodeports/node_ports.go (hunk 5 above)
Comment (macsko) [reply pkg/scheduler/framework/plugins/nodeports/node_ports.go:54]: Probably, we should try to check if this change (and the whole PR) won't visibly regress the performance of the scheduler, especially in scenarios that don't use those restartable init containers.

**Comment by macsko** [comment]
> My thinking it that since sidecars are new, we can backport the fix with very small risk to 1.33.

Yes, we could do this, but we need to be extra careful if this change won't cause any performance regression (what I mentioned in one comment). After verifying this, we could cherry-pick.

File: pkg/scheduler/util/utils.go (hunk 7 above)
Comment (avrittrohwer) [reply pkg/scheduler/util/utils.go:197]: I'm not sure if pod would ever be nil, but why would we leave the possibility of a panic in the scheduler?

File: pkg/scheduler/framework/plugins/nodeports/node_ports.go (hunk 5 above)
Comment (avrittrohwer) [reply pkg/scheduler/framework/plugins/nodeports/node_ports.go:54]: I'm not familiar with the scheduler codebase but I do see there are scheduler perf integration tests.  Do they run in the ci automatically?

Comment (macsko) [reply pkg/scheduler/framework/plugins/nodeports/node_ports.go:54]: Okay, I verified the performance using scheduler_perf (had to test on a new test case, since we don't have any for NodePorts at the moment). There is no regression (even the actual version is slightly faster), so we can leave this part as it is.

File: pkg/scheduler/util/utils.go (hunk 7 above)
Comment (macsko) [reply pkg/scheduler/util/utils.go:197]: There are many possibilities of panic in the scheduler and we aren't able to handle all of them. It's also not necessary, if we could clearly see (and test) that some fields will be always non-nil, such as this pod that is passed by pointer to avoid copying the fields. We can keep this check, but I don't see a point - the code will panic even before it reach this line.

**Comment by macsko** [comment]
> we need to be extra careful if this change won't cause any performance regression

I verified and there isn't any performance regression, so I think we could cherry-pick this change.

**Comment by SergeyKanzhelev** [comment]
/assign @dims

as per bot suggestion for test changes

**Comment by avrittrohwer** [comment]
@SergeyKanzhelev looks like someone needs to add the lgtm label to be able to merge
