### PR TITLE
Fix local storage test failures

### LINKED ISSUE #50128: Failure cluster [e37e44...] failed 88 builds, 2 jobs, and 8 tests over 1 days
##### Error text:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/persistent_volumes-local.go:121
Test Panicked
/usr/local/go/src/runtime/panic.go:489
```
##### Failure cluster statistics:
8 tests failed,    2 jobs failed,    88 builds failed.
Failure stats cover 1 day time range '3 Aug 2017 03:31 UTC' to '4 Aug 2017 03:31 UTC'.
##### Top failed tests by jobs failed:

| Test Name | Jobs Failed |
| --- | --- |
| [sig-storage] PersistentVolumes-local [Feature:LocalPersistentVolumes] [Serial] when one pod requests one prebound PVC should be able to mount and read from the volume using one-command containers | 2 |
| [sig-storage] PersistentVolumes-local [Feature:LocalPersistentVolumes] [Serial] when one pod requests one prebound PVC should be able to mount and write to the volume using one-command containers | 2 |
| [sig-storage] PersistentVolumes-local [Feature:LocalPersistentVolumes] [Serial] when one pod requests one prebound PVC should be able to mount volume and read from pod1 | 2 |

##### Top failed jobs by builds failed:

| Job Name | Builds Failed | Latest Failure |
| --- | --- | --- |
| ci-kubernetes-e2e-gci-gce-alpha-features | 46 | [4 Aug 2017 02:47 UTC](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/14033) |
| ci-kubernetes-e2e-gce-alpha-features | 42 | [4 Aug 2017 03:00 UTC](https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-alpha-features/13991) |

[Current Status](https://go.k8s.io/triage#e37e4489a00086b50245)

### PR DESCRIPTION
**Pull request by msau42**
**What this PR does / why we need it**:
Fixed a few issues:
- CI environment on GCE cannot resolve node names, need to use IPs.  Use a different SSH wrapper that will get the IPs from the node object.
- Use hostdir instead of containerdir now that commands are executed directly on the host, instead of through a container.
- Get the PVC object again after it is bound so that it has the PV name.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #50128

**Release note**:
NONE

/release-note-none
/sig storage

### CODE REVIEW

**Comment by msau42** [comment]
cc @ianchakeres

File: test/e2e/storage/persistent_volumes-local.go [hunk 1]
```diff
@@ -459,14 +462,21 @@ func createLocalPod(config *localTestConfig, volume *localTestVolume) (*v1.Pod,
...
 	return writeCmd, readCmd
 }
 
+// Create command to verify that the file doesn't exist
+// to be executed via SSH on the node with the local PV
+func createFileDoesntExistCmd(testFileDir string, testFile string) string {
+	testFilePath := filepath.Join(testFileDir, testFile)
+	return fmt.Sprintf("[ ! -e %s ]", testFilePath)
+}
+
```
Comment (jingxu97) [inline test/e2e/storage/persistent_volumes-local.go]: what is the difference between this command and the previous read command?

**Comment by ianchakeres** [comment]
I executed the local e2e tests and they are all passing with the updated code in this PR.

/lgtm

```
$ NUM_NODES=1 KUBE_FEATURE_GATES="PersistentLocalVolumes=true" go run hack/e2e.go -- -v --up
<snip>
$ go run hack/e2e.go -- -v --test --test_args="--ginkgo.focus=\[Feature:LocalPersistentVolumes\]"
<snip>
Ran 8 of 641 Specs in 388.086 seconds
SUCCESS! -- 8 Passed | 0 Failed | 0 Pending | 633 Skipped PASS

Ginkgo ran 1 suite in 6m29.355789568s
Test Suite Passed
2017/08/07 16:18:31 util.go:133: Step './hack/ginkgo-e2e.sh --ginkgo.focus=\[Feature:LocalPersistentVolumes\]' finished in 6m31.484227074s
2017/08/07 16:18:31 e2e.go:80: Done
```

File: test/e2e/storage/persistent_volumes-local.go (hunk 1 above)
Comment (msau42) [inline test/e2e/storage/persistent_volumes-local.go]: So in the successful case, the read command has a non-zero return code because the file doesn't exist.  But the `IssueSSH` function validates that the return code is 0, so it returns an error.  Instead of refactoring the `IssueSSH` command, I decided to rework the command we pass in so that it returns a 0 return code if the file doesn't exist.

**Comment by ddysher** [comment]
LGTM
