### PR TITLE
scheduler: fix race condition during cache refresh

### LINKED ISSUE #106545: kube-scheduler has race conditions during cache refresh
### What happened?
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/eventhandlers.go#L212
if oldPod.UID != newPod.UID {
		sched.deletePodFromCache(oldObj)
		sched.addPodToCache(newObj)
		return
	}
Both deletePodFromCache and addPodToCache operate on the internal cache of the scheduler, and will grab and release the lock respectively.
Here should be the scenario where the POD is deleted and created in a very short time, the scheduler will be merged into a POD update event to trigger the cache update. However, because it is not an atomic operation, another POD scheduling may be triggered between delete and add, resulting in an error in the calculation of the node resource plug-in, and no resources are actually available after the POD is scheduled to the node.

### What did you expect to happen?

Keep atomic operations and eliminate competition. 

### How can we reproduce it (as minimally and precisely as possible)?

Code analysis

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
v1.22.1
</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by binacs**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Avoid [issue](https://github.com/kubernetes/kubernetes/issues/106545) by moving the location of this code logic:

```go
	if oldPod.UID != newPod.UID {
		sched.deletePodFromCache(oldObj)
		sched.addPodToCache(newObj)
		return
	}
```

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/106545

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```docs
NONE
```

### CODE REVIEW

File: pkg/scheduler/internal/cache/cache.go [hunk 1]
```diff
@@ -513,15 +513,34 @@ func (cache *schedulerCache) UpdatePod(oldPod, newPod *v1.Pod) error {
...
+		// then add the new Pod.
+		if oldPod.UID != newPod.UID {
+			newKey, err := framework.GetPodKey(newPod)
+			if err != nil {
+				return err
+			}
+			if err := cache.removePod(oldPod); err != nil {
+				return err
+			}
+			delete(cache.podStates, key)
```
Comment (tanjing2020) [inline pkg/scheduler/internal/cache/cache.go:527]: Should we add "delete(cache.assumedPods, key)"

Comment (BinacsLee) [reply pkg/scheduler/internal/cache/cache.go:527]: PTAL at line 515.

File: pkg/scheduler/internal/cache/cache.go [hunk 2]
```diff
@@ -513,15 +513,34 @@ func (cache *schedulerCache) UpdatePod(oldPod, newPod *v1.Pod) error {
...
-			klog.ErrorS(nil, "SchedulerCache is corrupted and can badly affect scheduling decisions")
-			os.Exit(1)
-		}
-		if err := cache.updatePod(oldPod, newPod); err != nil {
-			return err
+		// A Pod delete event followed by an immediate Pod add event may be merged
+		// into a Pod update event. In this case, we should invalidate the old Pod, and
+		// then add the new Pod.
+		if oldPod.UID != newPod.UID {
+			newKey, err := framework.GetPodKey(newPod)
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/cache.go:520]: It looks like we are duplicating code. I would like to avoid that.

I think the functions `removePod`, `addPod`, `updatePod` are badly named. They should be `removePodFromNode`, `addPodToNode` and `updatePodInNode` respectively. Then, we can have new functions for `addPod` and `removePod` that include handling the `podStates` and `assumedPods`.

File: pkg/scheduler/eventhandlers.go [hunk 3]
```diff
@@ -203,15 +203,7 @@ func (sched *Scheduler) updatePodInCache(oldObj, newObj interface{}) {
...
-
-	// A Pod delete event followed by an immediate Pod add event may be merged
-	// into a Pod update event. In this case, we should invalidate the old Pod, and
-	// then add the new Pod.
-	if oldPod.UID != newPod.UID {
-		sched.deletePodFromCache(oldObj)
-		sched.addPodToCache(newObj)
-		return
-	}
+	klog.V(3).InfoS("Update event for scheduled pod", "oldPod", klog.KObj(oldPod), "newPod", klog.KObj(newPod))
```
[the remark this answers is not in the document]
Comment (BinacsLee) [reply pkg/scheduler/eventhandlers.go]: Thanks for reminding ^ ^

File: pkg/scheduler/internal/cache/cache.go (hunk 2 above)
Comment (BinacsLee) [reply pkg/scheduler/internal/cache/cache.go]: I agree with you.

At the same time, I *prefer* to keep the operations of `assumedPods` outside these `addPod` / `removePod` / `updatePod` functions. Emm, I think it would be a little strange to handle `assumedPod` in these functions.

And I have finished the code refactoring, PTAL ^ ^

Comment (alculquicondor) [reply pkg/scheduler/internal/cache/cache.go]: Not really, having them in there would help consistency.

Comment (BinacsLee) [reply pkg/scheduler/internal/cache/cache.go]: @alculquicondor done, PTAL.

File: pkg/scheduler/internal/cache/cache.go [hunk 4]
```diff
@@ -462,6 +445,58 @@ func (cache *schedulerCache) removePod(pod *v1.Pod) error {
 	return nil
 }
 
+// Assumes that lock is already acquired.
+func (cache *schedulerCache) addPod(pod *v1.Pod, key string, isAssumedPod bool) {
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/cache.go:449]: nit: `isAssumed`

File: pkg/scheduler/internal/cache/cache.go [hunk 5]
```diff
@@ -744,12 +769,7 @@ func (cache *schedulerCache) cleanupAssumedPods(now time.Time) {
 }
 
 func (cache *schedulerCache) expirePod(key string, ps *podState) error {
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/cache.go:771]: just get rid of this function

File: pkg/scheduler/internal/cache/cache.go [hunk 6]
```diff
@@ -462,6 +445,58 @@ func (cache *schedulerCache) removePod(pod *v1.Pod) error {
...
+	// then add the new Pod.
+	if oldPod.UID != newPod.UID {
+		// When the UID is different, we add the new Pod with the `newKey`
+		newKey, err := framework.GetPodKey(newPod)
+		if err != nil {
+			return err
+		}
+		key = newKey
+	}
+	cache.addPod(newPod, key, false)
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/cache.go:481]: Doesn't `addPod` already create a new `podState`? So deadline is already nil.

File: pkg/scheduler/internal/cache/cache.go [hunk 7]
```diff
@@ -477,22 +512,13 @@ func (cache *schedulerCache) AddPod(pod *v1.Pod) error {
...
-			// Clean this up.
-			if err = cache.removePod(currState.pod); err != nil {
-				klog.ErrorS(err, "Error occurred while removing pod")
-			}
-			cache.addPod(pod)
 		}
-		delete(cache.assumedPods, key)
-		cache.podStates[key].deadline = nil
-		cache.podStates[key].pod = pod
+		if err = cache.updatePod(currState.pod, pod, key); err != nil {
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/cache.go:516]: I'm not convinced that this yields the same result. I think you shouldn't try to use `updatePod` here.

**Comment by alculquicondor** [comment]
Any change to event handlers is high risk. Can you respond to https://github.com/kubernetes/kubernetes/issues/106545#issuecomment-984989173 so that we can asses the impact of the bug? I'm not convinced is important for the majority of users.

@Huang-Wei could you also take a look?

File: pkg/scheduler/eventhandlers.go [hunk 8]
```diff
@@ -203,18 +203,10 @@ func (sched *Scheduler) updatePodInCache(oldObj, newObj interface{}) {
...
 	}
-
-	// A Pod delete event followed by an immediate Pod add event may be merged
-	// into a Pod update event. In this case, we should invalidate the old Pod, and
-	// then add the new Pod.
-	if oldPod.UID != newPod.UID {
-		sched.deletePodFromCache(oldObj)
-		sched.addPodToCache(newObj)
-		return
-	}
```
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/eventhandlers.go:214]: I'd expect this PR to focus on eliminating the potential racing (very rare although). To ensure not cause regression, clear the old UID in podStates properly.

File: pkg/scheduler/internal/cache/cache.go (hunk 7 above)
Comment (BinacsLee) [reply pkg/scheduler/internal/cache/cache.go:509]: > 

Thanks a lot for pointing out. Let's dig into the details.

Firstly, the `addPodToNode` and `removePodFromNode`  functions will do these things:

- `addPodToNode`:  add pod to node and modify the **nodeInfoListItem**.
- `removePodFromNode`: delete pod from node and modify the **nodeInfoListItem**.

Secondly, let's analyze two cases:

| Cases                                                        | Before Editing                                               | After Editing                                                | Same Result ?                                                |
| ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ |
| **Case 1:**<br> `currState.pod.Spec.NodeName != pod.Spec.NodeName` | **Step 1:** delete the oldPod from **node**  <br>**Step 2:** add the newPod to **node** <br>**Step 3:** delete the key from `assumedPods` and reset the `podStates` | One `updatePod` means:<br>**Step 1:** delete the oldPod from **cache** (not only **node** but also  `assumedPods`  and `podStates`) <br/>**Step 2:** add the newPod to cache (not only **node** but also `podStates`) | **Yes**<br>- `assumedPods`: same (both delete the key)<br>- `podStates`:  same (both set the value of `podStates[key]` to newPod)<br>- `nodeInfoListItem`: same (both modify the `nodeInfoListItem`) |
| **Case 2:**<br> `currState.pod.Spec.NodeName == pod.Spec.NodeName` | **Step 1:** delete the key from `assumedPods` and reset the `podStates` | One `updatePod` means:<br/>**Step 1:** delete the oldPod from **cache** (not only **node** but also  `assumedPods`  and `podStates`) <br/>**Step 2:** add the newPod to cache (not only **node** but also `podStates`) | **Not completely**<br>- `assumedPods`: same (both delete the key)<br/>- `podStates`:  same (both set the value of  `podStates[key]` to newPod)<br/>- `nodeInfoListItem`: **different** (After editing we will modify the `nodeInfoListItem` in `removePod` and `addPod`, while before editing we won't) |

The question is:

Should we always update the `nodeInfoListItem` when we handling add event of an assumed pods?

> Before editing, we won't update the `nodeInfoListItem` when `currState.pod.Spec.NodeName == pod.Spec.NodeName` .

- If the answer is YES, there is no problem after editing.
- Otherwise, we shouldn't use `updatePod` here.

File: pkg/scheduler/eventhandlers.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (BinacsLee) [reply pkg/scheduler/eventhandlers.go:214]: > 

Thank you very much for your description.

Before submitting this PR, I have checked the related issue(https://github.com/kubernetes/kubernetes/issues/85726) and PR(https://github.com/kubernetes/kubernetes/pull/91126).

To clarify: I didn't delete the code, I just moved it to `schedulerCache.updatePod` (line 469) so that the cache can be accessed safely.

Let's go through the current code workflow (in this PR) with  `Update Event` :

- the **first** one is {old UID -> new UID} as the pod is recreated in master scheduler, while at the same time, the standby scheduler lost network connection to API Server. 
  ===> **unchanged**

- so when the standby scheduler becomes the new master, the pod update event would cache.go#UpdatePod() -> cache.updatePod(). In this case, **we use the oldPod's UID as the key to check weather the pod exists and delete the oldPod, while adding the newPod with newPod's UID [*newKey*].**
   ===> **changed: `podStates` will not hold the oldPod's UID but the newPod's UID as the key.**

- next the pod gets deleted, and the **second** pod update (b/c deletionTimeStamp is set) is delivered. This time, it's {new UID -> new UID}. And when it hits cache.go#UpdatePod(), **`podStates` has hold the newPod's UID as the key.**
  ===> **changed: we can handle this update correctly.** 

- then when the pod gets deleted physically, cache#RemovePod() gets called. **Cause podStates has hold the newPod's UID as the key, we can delete the newPod by the newPod's UID.** 
  ===> **changed: we can handle this delete correctly.**

File: pkg/scheduler/internal/cache/cache.go [hunk 9]
```diff
@@ -518,10 +537,9 @@ func (cache *schedulerCache) UpdatePod(oldPod, newPod *v1.Pod) error {
 			klog.ErrorS(nil, "SchedulerCache is corrupted and can badly affect scheduling decisions")
 			os.Exit(1)
 		}
-		if err := cache.updatePod(oldPod, newPod); err != nil {
+		if err := cache.updatePod(oldPod, newPod, key); err != nil {
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/cache.go:540]: Can we eliminate the `key` parameter as it can be obtained from the pod?

File: pkg/scheduler/internal/cache/cache.go [hunk 10]
```diff
@@ -462,6 +445,51 @@ func (cache *schedulerCache) removePod(pod *v1.Pod) error {
...
+		}
+		key = newKey
+	}
+	cache.addPod(newPod, key, false)
+	return nil
+}
+
+// Assumes that lock is already acquired.
+func (cache *schedulerCache) removePod(pod *v1.Pod, key string) error {
+	if err := cache.removePodFromNode(pod); err != nil {
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/cache.go:483]: `removePodFromNode()` is only used by this function, right? If so, flatten the logic reads better IMO. (you can add a comment btw)

File: pkg/scheduler/internal/cache/cache.go [hunk 11]
```diff
@@ -462,6 +445,51 @@ func (cache *schedulerCache) removePod(pod *v1.Pod) error {
...
+		return err
+	}
+	delete(cache.podStates, key)
+	if cache.assumedPods.Has(key) {
+		cache.assumedPods.Delete(key)
+	}
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/cache.go:489]: Just delete it unconditionally:

```suggestion
	delete(cache.assumedPods, key)
```

File: pkg/scheduler/internal/cache/cache.go [hunk 12]
```diff
@@ -462,6 +445,51 @@ func (cache *schedulerCache) removePod(pod *v1.Pod) error {
...
+	// into a Pod update event. In this case, we should invalidate the old Pod, and
+	// then add the new Pod.
+	if oldPod.UID != newPod.UID {
+		// When the UID is different, we add the new Pod with the `newKey`
+		newKey, err := framework.GetPodKey(newPod)
+		if err != nil {
+			return err
+		}
+		key = newKey
+	}
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/cache.go:476]: Given we're cleaning the podStates using the old pod's UID, this logic is not needed anymore. The newKey can be obtained from newPod.

File: pkg/scheduler/internal/cache/cache.go (hunk 6 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/cache/cache.go:477]: Why `isAssumed` is always false? Shouldn't we check if it exists in `assumedPods` every time?

File: pkg/scheduler/internal/cache/cache.go (hunk 7 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/cache/cache.go:509]: I don't think a generic update() rewards us significant benefits. In terms of case 2, which is the most common happy path, with current changes, we remove the pod and re-add the pod which imposes overhead unnecessarily.

File: pkg/scheduler/internal/cache/cache.go [hunk 13]
```diff
@@ -477,22 +505,13 @@ func (cache *schedulerCache) AddPod(pod *v1.Pod) error {
...
+			klog.ErrorS(err, "Error occurred while updating pod")
+		}
 	case !ok:
 		// Pod was expired. We should add it back.
-		cache.addPod(pod)
-		ps := &podState{
-			pod: pod,
-		}
-		cache.podStates[key] = ps
+		cache.addPod(pod, key, false)
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/cache.go:514]: False `isAssumed` indicates we don't care about whether it exits in assumedPods or not, right?

(BTW: I'd suggest looking through all usages of addPod() and check if the value of `isAssumed` is passed in properly)

**Review by Huang-Wei — COMMENTED** [review]
Thanks for the explanation. Some comments below.

BTW: please address comments by appending new commits.

File: pkg/scheduler/internal/cache/cache.go (hunk 9 above)
Comment (BinacsLee) [reply pkg/scheduler/internal/cache/cache.go]: Sure, of course

File: pkg/scheduler/internal/cache/cache.go (hunk 10 above)
Comment (BinacsLee) [reply pkg/scheduler/internal/cache/cache.go:478]: Yes, `removePodFromNode` is only used by `removePod` for now. But I’d like to keep this function for consistency and it may be good for more detailed unit test.

File: pkg/scheduler/internal/cache/cache.go (hunk 13 above)
Comment (BinacsLee) [reply pkg/scheduler/internal/cache/cache.go]: No. More precisely: As a function parameter (in `addPod`), `isAssumed` indicates whether the pod should be added to the `assumedPod`. **This value is `true` if and only if `addPod` is called in `AssumePod`, and the others are `false`.**

**Comment by BinacsLee** [comment]
Sorry for forced updating.

I have finished these changes, PTAL.

File: pkg/scheduler/internal/cache/cache.go (hunk 13 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/cache/cache.go]: I see, you want to use this parameter to assume the pod as an optional step. In this case, `assumePod` as the parameter names reads better. (assume as a verb)

Comment (BinacsLee) [reply pkg/scheduler/internal/cache/cache.go]: Absolutely right. And any other questions besides this? If not, I will squash these commits after work ^ ^

File: pkg/scheduler/eventhandlers.go [hunk 14]
```diff
@@ -203,18 +203,10 @@ func (sched *Scheduler) updatePodInCache(oldObj, newObj interface{}) {
...
+	klog.V(3).InfoS("Update event for scheduled pod", "pod", klog.KObj(oldPod))
```
Comment (Huang-Wei) [inline pkg/scheduler/eventhandlers.go:206]: Do we need this?

File: pkg/scheduler/internal/cache/cache.go (hunk 13 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/cache/cache.go]: I will take another look tomorrow.

File: pkg/scheduler/eventhandlers.go (hunk 14 above)
Comment (BinacsLee) [reply pkg/scheduler/eventhandlers.go:206]: I think so.

File: pkg/scheduler/eventhandlers_test.go [hunk 15]
```diff
@@ -224,6 +224,12 @@ func TestUpdatePodInCache(t *testing.T) {
 			}
 			sched.addPodToCache(tt.oldObj)
 			sched.updatePodInCache(tt.oldObj, tt.newObj)
+
+			if tt.oldObj.(*v1.Pod).UID != tt.newObj.(*v1.Pod).UID {
+				if pod, err := sched.SchedulerCache.GetPod(tt.oldObj.(*v1.Pod)); err == nil {
+					t.Errorf("Get pod UID %v from SchedulerCache but it should not happen", pod.UID)
+				}
+			}
```
Comment (Huang-Wei) [inline pkg/scheduler/eventhandlers_test.go:232]: We don't need this, do we?

**Review by Huang-Wei — COMMENTED** [review]
Some nits. LGTM otherwise.

File: pkg/scheduler/eventhandlers.go (hunk 14 above)
Comment (alculquicondor) [reply pkg/scheduler/eventhandlers.go:206]: You are right... every pod healthcheck causes an update, AFAIK. So probably too noisy. Can we make it v(4)?

File: pkg/scheduler/internal/cache/cache.go (hunk 10 above)
Comment (alculquicondor) [reply pkg/scheduler/internal/cache/cache.go:478]: we discourage unit test of low level functions, specially if they are only used by one other function.

I'm in favor of flattening too.

File: pkg/scheduler/internal/cache/cache.go [hunk 16]
```diff
@@ -521,7 +539,6 @@ func (cache *schedulerCache) UpdatePod(oldPod, newPod *v1.Pod) error {
 		if err := cache.updatePod(oldPod, newPod); err != nil {
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/cache.go:539]: isn't this now losing information about the podState if there was no change of UID?

File: pkg/scheduler/eventhandlers_test.go (hunk 15 above)
Comment (BinacsLee) [reply pkg/scheduler/eventhandlers_test.go:232]: > we want to check that the old pod was cleared from the cache.

+1

File: pkg/scheduler/internal/cache/cache.go (hunk 16 above)
Comment (BinacsLee) [reply pkg/scheduler/internal/cache/cache.go:530]: Yes, but since `!cache.assumedPods.Has(key)` I think there is no other information except the pod.

File: pkg/scheduler/internal/cache/cache.go (hunk 10 above)
Comment (BinacsLee) [reply pkg/scheduler/internal/cache/cache.go]: flatten done

File: pkg/scheduler/internal/cache/cache.go [hunk 17]
```diff
@@ -409,20 +403,17 @@ func (cache *schedulerCache) ForgetPod(pod *v1.Pod) error {
 	switch {
 	// Only assumed pod can be forgotten.
 	case ok && cache.assumedPods.Has(key):
-		err := cache.removePod(pod)
-		if err != nil {
+		if cache.removePod(pod); err != nil {
```
[the remark this answers is not in the document]
Comment (BinacsLee) [reply pkg/scheduler/internal/cache/cache.go]: done

**Comment by BinacsLee** [comment]
Squashed commits. Thanks for review! @Huang-Wei @alculquicondor

File: pkg/scheduler/internal/cache/cache.go [hunk 18]
```diff
@@ -432,33 +423,54 @@ func (cache *schedulerCache) addPod(pod *v1.Pod) {
 	cache.moveNodeInfoToHead(pod.Spec.NodeName)
 }
 
+// Assumes that lock is already acquired.
+func (cache *schedulerCache) addPod(pod *v1.Pod, assumePod bool) error {
+	key, err := framework.GetPodKey(pod)
+	if err != nil {
+		return err
+	}
+	cache.addPodToNode(pod)
```
Comment (Huang-Wei) [inline pkg/scheduler/internal/cache/cache.go:432]: Can you flatten addPodToNode() here? (same as removePodFromNode())

File: pkg/scheduler/internal/cache/cache.go (hunk 16 above)
Comment (Huang-Wei) [reply pkg/scheduler/internal/cache/cache.go:530]: agree.

**Review by Huang-Wei — COMMENTED** [review]
Ready to merge except for last nit.

File: pkg/scheduler/internal/cache/cache.go (hunk 16 above)
Comment (alculquicondor) [reply pkg/scheduler/internal/cache/cache.go:530]: Sounds good, thanks for checking.

With that simplification, everything looks pretty consistent and maintainable now.

**Comment by BinacsLee** [comment]
done, thanks for review.

**Comment by BinacsLee** [comment]
done, thanks for review. @Huang-Wei @alculquicondor

**Review by alculquicondor — COMMENTED** [review]
just nits

File: pkg/scheduler/internal/cache/cache.go [hunk 19]
```diff
@@ -409,56 +403,69 @@ func (cache *schedulerCache) ForgetPod(pod *v1.Pod) error {
 	switch {
 	// Only assumed pod can be forgotten.
 	case ok && cache.assumedPods.Has(key):
-		err := cache.removePod(pod)
-		if err != nil {
+		if err := cache.removePod(pod); err != nil {
```
[the remark this answers is not in the document]
Comment (BinacsLee) [reply pkg/scheduler/internal/cache/cache.go]: fixed

File: pkg/scheduler/internal/cache/cache.go [hunk 20]
```diff
@@ -409,56 +403,69 @@ func (cache *schedulerCache) ForgetPod(pod *v1.Pod) error {
 	switch {
 	// Only assumed pod can be forgotten.
 	case ok && cache.assumedPods.Has(key):
```
[the remark this answers is not in the document]
Comment (BinacsLee) [reply pkg/scheduler/internal/cache/cache.go]: fixed

**Comment by alculquicondor** [comment]
/approve

I leave the lgtm to @Huang-Wei

File: pkg/scheduler/internal/cache/cache.go (hunk 20 above)
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/internal/cache/cache.go]: @alculquicondor good catch.

**Comment by Huang-Wei** [comment]
/sig scheduling
(not sure why do-not-merge/needs-sig is still there)

/lgtm

Thanks @BinacsLee ! This PR not only eliminates the potential racing, but also improves the code readability and maintainability.

**Comment by BinacsLee** [comment]
I'm glad to do this ^ ^
