### PR TITLE
bubble up reason when killing container

### LINKED ISSUE #6532: Bubble up the reason for killing a container
The kubelet restarts containers when a liveness probe fails, but the events don't show this. This makes it hard to debug cases with bad liveness probes because it will appear like the container is crashing, docker logs won't show anything really wrong with the container, but the kubelet will keep restarting it. 

My events from a pod with a bad liveness probe:
```
  Tue, 07 Apr 2015 12:08:30 -0700	Tue, 07 Apr 2015 12:08:30 -0700	1	{kubelet 127.0.0.1}	spec.containers{nginx}			killing		Killing 0b7743acd1a5f54aeccf4fe16c8cfbaa5e935a541c2fca59150cc250f7035d4e
  Tue, 07 Apr 2015 12:08:31 -0700	Tue, 07 Apr 2015 12:08:31 -0700	1	{kubelet 127.0.0.1}	spec.containers{nginx}			created		Created with docker id 39e349fd00c1cbcbb25e588e29e70e2c12b2e7b9a8020e02fbe462ae9fa61ea1
  Tue, 07 Apr 2015 12:08:31 -0700	Tue, 07 Apr 2015 12:08:31 -0700	1	{kubelet 127.0.0.1}	spec.containers{nginx}			started		Started with docker id 39e349fd00c1cbcbb25e588e29e70e2c12b2e7b9a8020e02fbe462ae9fa61ea1
  Tue, 07 Apr 2015 12:09:00 -0700	Tue, 07 Apr 2015 12:09:00 -0700	1	{kubelet 127.0.0.1}	spec.containers{nginx}			killing		Killing 39e349fd00c1cbcbb25e588e29e70e2c12b2e7b9a8020e02fbe462ae9fa61ea1
  Tue, 07 Apr 2015 12:09:00 -0700	Tue, 07 Apr 2015 12:09:00 -0700	1	{kubelet 127.0.0.1}	spec.containers{nginx}			created		Created with docker id 9b2a0596d1c9a0badf0ac07e5a2d4d74e71e2654177be26217e5a376a8062ca4
  Tue, 07 Apr 2015 12:09:00 -0700	Tue, 07 Apr 2015 12:09:00 -0700	1	{kubelet 127.0.0.1}	spec.containers{nginx}			started		Started with docker id 9b2a0596d1c9a0badf0ac07e5a2d4d74e71e2654177be26217e5a376a8062ca4

```

I would find it easier if there was a reason in there like: the probe on ip:port/url failed

### PR DESCRIPTION
**Pull request by jiangyaoguo**
fix #6532

### CODE REVIEW

**Comment by dchen1107** [comment]
The Jenkins failure is caused by broken jenkin git workspace. Restart tests:

ok to test

**Comment by jiangyaoguo** [comment]
@k8s-bot ok to test

**Comment by feihujiang** [comment]
@k8s-bot ok to test

**Comment by feihujiang** [comment]
@k8s-bot test this please

**Comment by feihujiang** [comment]
@k8s-bot test this please

**Comment by jiangyaoguo** [comment]
@k8s-bot test this please

File: pkg/kubelet/dockertools/manager.go [hunk 1]
```diff
@@ -1450,8 +1450,11 @@ func (dm *DockerManager) killContainer(containerID kubecontainer.ContainerID, co
 	if !ok {
 		glog.Warningf("No ref for pod '%q'", name)
 	} else {
-		// TODO: pass reason down here, and state, or move this call up the stack.
-		dm.recorder.Eventf(ref, "Killing", "Killing with docker id %v", util.ShortenString(ID, 12))
+		message := fmt.Sprintf("Killing with docker id %v", util.ShortenString(ID, 12))
```
Comment (vishh) [inline pkg/kubelet/dockertools/manager.go]: nit: `Killing container`

File: pkg/kubelet/dockertools/manager.go [hunk 2]
```diff
@@ -1450,8 +1450,11 @@ func (dm *DockerManager) killContainer(containerID kubecontainer.ContainerID, co
 	if !ok {
 		glog.Warningf("No ref for pod '%q'", name)
 	} else {
-		// TODO: pass reason down here, and state, or move this call up the stack.
-		dm.recorder.Eventf(ref, "Killing", "Killing with docker id %v", util.ShortenString(ID, 12))
+		message := fmt.Sprintf("Killing container with docker id %v", util.ShortenString(ID, 12))
+		if reason != "" {
+			message = fmt.Sprintf("Killing container with docker id %v: %s", util.ShortenString(ID, 12), reason)
```
Comment (ashcrow) [inline pkg/kubelet/dockertools/manager.go]: nit: Don't recreate the formatted message. Add to it.

```go
message = fmt.Sprint(message, ": ", reason)
```

File: pkg/kubelet/dockertools/manager.go [hunk 3]
```diff
@@ -1336,7 +1336,7 @@ func (dm *DockerManager) KillPod(pod *api.Pod, runningPod kubecontainer.Pod) err
 			glog.Errorf("Failed tearing down the infra container: %v", err)
 			errs <- err
 		}
-		if err := dm.KillContainerInPod(networkContainer.ID, networkSpec, pod); err != nil {
+		if err := dm.KillContainerInPod(networkContainer.ID, networkSpec, pod, "Need to kill pod."); err != nil {
```
Comment (ashcrow) [inline pkg/kubelet/dockertools/manager.go]: nit: Is it worth logging a generic reason when there will be a log line stating that the pod was killed already?

Comment (jiangyaoguo) [inline pkg/kubelet/dockertools/manager.go]: This is for distinguishing killing container for restarting container and terminating whole Pod. From this point, it's not generic. We can get more details in log file but we can't get Pod delete  event now. I considered logging specific killPod reason also. But I found it had several kinds of reason and some killPod function call was caused by containerRuntime internal logic which may different between docker and rkt. So I logging a generic killPod reason for now. Surely logging specific killPod reason is better. I think we can record Pod create/delete event to improve it in future. What do you think?

Comment (ashcrow) [inline pkg/kubelet/dockertools/manager.go]: That makes sense. Can we make the ```reason``` a bit more descriptive noting that the pod is being killed and will [not] be restarted?

Comment (jiangyaoguo) [inline pkg/kubelet/dockertools/manager.go]: This pr focus on container killing reason. It describes details if container will be restart or re-created after being killed. "will not be restart" may be omitted.

Comment (ashcrow) [inline pkg/kubelet/dockertools/manager.go]: OK, if it is describing it somewhere else I don't see any issue.

**Comment by ashcrow** [comment]
Jenkins e2e error which seems unrelated:

```
Summarizing 1 Failure:

[Fail] Port forwarding With a server that expects a client request [It] should support a client that connects, sends no data, and disconnects [Conformance] 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/portforward.go:122
```

File: pkg/kubelet/dockertools/manager.go [hunk 4]
```diff
@@ -1434,8 +1434,11 @@ func (dm *DockerManager) killContainer(containerID kubecontainer.ContainerID, co
 	if !ok {
 		glog.Warningf("No ref for pod '%q'", name)
 	} else {
-		// TODO: pass reason down here, and state, or move this call up the stack.
-		dm.recorder.Eventf(ref, "Killing", "Killing with docker id %v", util.ShortenString(ID, 12))
+		message := fmt.Sprintf("Killing container with docker id %v", util.ShortenString(ID, 12))
+		if reason != "" {
+			message = fmt.Sprint(message, ": ", reason)
+		}
+		dm.recorder.Event(ref, "Killing", message)
```
Comment (vishh) [inline pkg/kubelet/dockertools/manager.go]: While you are at it can you make these reasons constants with some clarity on the semantic meaning of these reasons?

Comment (ashcrow) [inline pkg/kubelet/dockertools/manager.go]: @vishh are you suggesting moving the ```reasons``` into their constants and then documenting each constant to explain what it means in more depth? If so, :+1:.

Comment (jiangyaoguo) [inline pkg/kubelet/dockertools/manager.go]: @vishh @ashcrow As @vishh suggested, I have an idea about event in #16374. Could you spare a moment to give your opinion.

Comment (vishh) [inline pkg/kubelet/dockertools/manager.go]: Yes

**Comment by ashcrow** [comment]
@jiangyaoguo looks like a rebase is needed.

**Comment by jiangyaoguo** [comment]
@ashcrow @vishh rebased.

**Comment by ashcrow** [comment]
@jiangyaoguo @vishh not sure why @k8s-teamcity-mesosphere failed on the test.

**Comment by jiangyaoguo** [comment]
@ashcrow It seems the mesosphere failure is caused by some kind of timeout. After rebase, the failure gone.

**Comment by ashcrow** [comment]
@jiangyaoguo great!

@vishh when you have a few moments please take a look. This is ready for an official review.

**Comment by vishh** [comment]
LGTM. Thanks @jiangyaoguo!
