### PR TITLE
Fix flaky resource claim metrics test

### LINKED ISSUE #133304: Flake (?): [DRA] [Feature:DynamicResourceAllocation] [FeatureGate:DynamicResourceAllocation] Two resource Kubelet Plugins [Serial] must provide metrics
### Which jobs are failing?

Seen once so far: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/133299/pull-kubernetes-node-e2e-crio-cgrpv1-dra/1950483959242559488

```
[FAILED] metrics while pod is running
Expected
    <string>: KubeletMetrics
to match keys: {
[."dra_resource_claims_in_use"[<any>]:
	Expected
	    <string>: Sample
	to match fields: {
	.Value:
		Expected
		    <model.SampleValue>: 2
		to be ==
		    <int>: 1
	}
	, ."dra_resource_claims_in_use":
	unexpected element test-driver.cdi.k8s.io]
}
In [It] at: k8s.io/kubernetes/test/e2e_node/dra_test.go:558 @ 07/30/25 09:24:56.218
```

### Which tests are failing?

DRA e2e_node

### Since when has it been failing?

After merging some of the recent new features, but could also be a coincidence.

cc @yliaog @sunya-ch @KobayashiD27 

### Testgrid link

_No response_

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node
/wg device-management

### PR DESCRIPTION
**Pull request by Jpsassine**
#### What type of PR is this?
/kind bug
/kind flake

#### What this PR does / why we need it:
This PR fixes a flaky E2E node test, `[DRA] Two resource Kubelet Plugins [Serial] must provide metrics`, which was failing due to a race condition.

The preceding test, `should not add health status to Pod when feature gate is disabled`, was leaking an in-use ResourceClaim by not waiting for the Kubelet to unprepare the resources before exiting. This left the `dra_resource_claims_in_use metric` at a non-zero value, causing the subsequent metrics test to fail.

This commit makes the cleanup process synchronous. The test now deletes the pod and explicitly waits for the `NodeUnprepareResources` gRPC call to complete making sure resources are fully released before the test finishes.

Additionally, it fixes the cleanup logic in the `createHealthTestPodAndClaim` helper function to prevent a `DeviceClass` from being leaked.

#### Which issue(s) this PR is related to:
Fixes: #133304

#### Special notes for your reviewer:
N/A
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by Jpsassine** [comment]
cc. @pohly 
re #133304

File: test/e2e_node/dra_test.go [hunk 1]
```diff
@@ -1374,9 +1378,9 @@ func createHealthTestPodAndClaim(ctx context.Context, f *framework.Framework, dr
 	_, err := f.ClientSet.ResourceV1().DeviceClasses().Create(ctx, dc, metav1.CreateOptions{})
 	framework.ExpectNoError(err, "failed to create DeviceClass "+className)
 	ginkgo.DeferCleanup(func() {
-		err := f.ClientSet.ResourceV1().ResourceClaims(f.Namespace.Name).Delete(context.Background(), claimName, metav1.DeleteOptions{})
+		err := f.ClientSet.ResourceV1beta1().DeviceClasses().Delete(context.Background(), className, metav1.DeleteOptions{})
```
Comment (pohly) [inline test/e2e_node/dra_test.go]: Please keep using ResourceV1.

Comment (bart0sh) [inline test/e2e_node/dra_test.go]: nit: please use test context here and below.
```suggestion
		err := f.ClientSet.ResourceV1beta1().DeviceClasses().Delete(ctx, className, metav1.DeleteOptions{})
```

**Comment by SergeyKanzhelev** [comment]
/assign @pohly 

for reviews. Marking as waiting on author

File: test/e2e_node/dra_test.go (hunk 1 above)
Comment (Jpsassine) [reply test/e2e_node/dra_test.go]: I changed the cleanup to use ctx and noticed it started failing, however it works with background.  I think the lifecycle ctx is canceled before DeferCleanup is executed. I am keeping context.Background() since it works.

Comment (pohly) [reply test/e2e_node/dra_test.go]: You need to use `ginkgo.DeferCleanup(func(ctx context.Context) { ... })`

File: test/e2e_node/dra_test.go [hunk 2]
```diff
@@ -1384,9 +1388,9 @@ func createHealthTestPodAndClaim(ctx context.Context, f *framework.Framework, dr
 	_, err := f.ClientSet.ResourceV1().DeviceClasses().Create(ctx, dc, metav1.CreateOptions{})
 	framework.ExpectNoError(err, "failed to create DeviceClass "+className)
 	ginkgo.DeferCleanup(func() {
-		err := f.ClientSet.ResourceV1().ResourceClaims(f.Namespace.Name).Delete(context.Background(), claimName, metav1.DeleteOptions{})
+		err := f.ClientSet.ResourceV1().DeviceClasses().Delete(context.Background(), className, metav1.DeleteOptions{})
```
Comment (pohly) [inline test/e2e_node/dra_test.go]: This works, but it is better to use `func(ctx context.Context)` and that `ctx` here because then Ginkgo can control the duration of shutdown functions.

Comment (pohly) [reply test/e2e_node/dra_test.go]: @Jpsassine: this comment still needs to be addressed.

**Review by pohly — CHANGES_REQUESTED** [review]

**Review by pohly — APPROVED** [review]
/lgtm
/approve

**Comment by pohly** [comment]
/test pull-kubernetes-integration

Volume scheduling, known issue.

**Comment by pohly** [comment]
pull-kubernetes-node-e2e-containerd-2-0-dra-alpha-beta-features still fails: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/132927/pull-kubernetes-node-e2e-containerd-2-0-dra-alpha-beta-features/1966416644951511040
