### PR TITLE
[scheduler] avoid comparing function pointers in unit tests

### LINKED ISSUE #101657: Kubernetes scheduler unit test registry_test Failures with master go
#### What happened:
Below are the failures while running unit test **pkg/scheduler/framework/runtime/registry_test.go** with golang in master branch.
```
--- FAIL: TestMerge (0.00s)
    --- FAIL: TestMerge/valid_Merge (0.00s)
        registry_test.go:158: Merge(). Expected map[pluginFactory1:0x11607ea0 pluginFactory2:0x11607ed0]. Got map[pluginFactory1:0x11607e40 pluginFactory2:0x11607e70] instead.
    --- FAIL: TestMerge/Merge_duplicate_factories (0.00s)
        registry_test.go:158: Merge(). Expected map[pluginFactory1:0x11607f60]. Got map[pluginFactory1:0x11607f00] instead.
--- FAIL: TestRegister (0.00s)
    --- FAIL: TestRegister/valid_Register (0.00s)
        registry_test.go:207: Register(). Expected map[pluginFactory1:0x11607fc0]. Got map[pluginFactory1:0x11607f90] instead.
    --- FAIL: TestRegister/Register_duplicate_factories (0.00s)
        registry_test.go:207: Register(). Expected map[pluginFactory1:0x11608050]. Got map[pluginFactory1:0x11607ff0] instead.
--- FAIL: TestUnregister (0.00s)
    --- FAIL: TestUnregister/valid_Unregister (0.00s)
        registry_test.go:252: Unregister(). Expected map[pluginFactory2:0x116080e0]. Got map[pluginFactory2:0x116080b0] instead.
```
**Reference : https://github.com/golang/go/issues/45697#issuecomment-826007480**

**$ go version
go version devel go1.17-5daefc5363 Thu Apr 22 01:40:02 2021 +0000 linux/ppc64le**
Note: Occurs in x86 architecture as well.

#### What you expected to happen:
The tests should Pass as with stable go
```
[root@rajalakshmi1-workspace kubernetes]# go version
go version go1.16 linux/ppc64le
[root@rajalakshmi1-workspace kubernetes]# make test KUBE_RACE=-race WHAT=./pkg/scheduler/framework/runtime/ 2>&1 | tee pss.log
+++ [0422 09:55:38] Running tests without code coverage
ok      k8s.io/kubernetes/pkg/scheduler/framework/runtime       0.190s
[root@rajalakshmi1-workspace kubernetes]#
```

#### How to reproduce it (as minimally and precisely as possible):
git clone https://github.com/kubernetes/kubernetes.git
cd kubernetes
make test KUBE_RACE=-race WHAT=./pkg/scheduler/framework/runtime/

#### Environment:
Master branch of kubernetes repo.
https://github.com/kubernetes/kubernetes
OS: Linux
Observed failure on ppc64le and x86 architectures

**Below is the attached log:**
[fail.log](https://github.com/kubernetes/kubernetes/files/6404969/fail.log)

### PR DESCRIPTION
**Pull request by dims**
PluginFactory is a function that returns a plugin. We have been
comparing these functions in unit tests and it has worked so far, but
starts to fail in gotip/master.

Note from the golang team:
```
Func values are incomparable. It is true that you could get the PC
through reflection but it is still not expected to be compared. PCs
can change due to inlining, wrappers, etc., depending on the
compiler's details, which is subject to change.
```

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/101657

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/framework/runtime/registry_test.go [hunk 1]
```diff
@@ -93,22 +97,34 @@ func isRegistryEqual(registryX, registryY Registry) bool {
 		}
 	}
 
+	for name := range registryY {
```
Comment (ahg-g) [inline pkg/scheduler/framework/runtime/registry_test.go:100]: isn't this covered in the first loop above?

Comment (dims) [reply pkg/scheduler/framework/runtime/registry_test.go:100]: whoops yes!

File: pkg/scheduler/framework/runtime/registry_test.go [hunk 2]
```diff
@@ -76,7 +78,9 @@ func TestDecodeInto(t *testing.T) {
 func isRegistryEqual(registryX, registryY Registry) bool {
 	for name, pluginFactory := range registryY {
 		if val, ok := registryX[name]; ok {
-			if reflect.ValueOf(pluginFactory).Pointer() != reflect.ValueOf(val).Pointer() {
+			p1, _ := pluginFactory(nil, nil)
+			p2, _ := val(nil, nil)
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/runtime/registry_test.go:82]: A nit: as `pluginFactory` is from regY, so swap the naming of p1, p2 for readability? so that p1 is mapped to the entry in regX, and p2 is mapped to regY.

```go
p1, _ := val(nil, nil)
p2, _ := pluginFactory(nil, nil)
```
