### PR TITLE
fix kubelet iptables monitoring on dual-stack

### LINKED ISSUE #95369: [Failing Test] [sig-network] Networking should recreate its iptables rules if they are deleted [Disruptive]
**Which jobs are failing**:
ci-kubernetes-e2e-gci-gce-alpha-features

**Which test(s) are failing**:
Networking should recreate its iptables rules if they are deleted [Disruptive]

**Since when has it been failing**:
Commit 777e84e18
https://github.com/kubernetes/kubernetes/compare/7a5b058f2...777e84e18

**Testgrid link**:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features&sort-by-flakiness=

**Reason for failure**:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:428
Oct  7 12:11:49.214: kubelet did not recreate its iptables rules
Unexpected error:
    <*errors.errorString | 0xc00020a200>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
```

**Anything else we need to know**:
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1313800936056950784
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1313826354843619328

Possibly related to this? It's listed in the git diff https://github.com/kubernetes/kubernetes/pull/94474
/sig network

### PR DESCRIPTION
**Pull request by danwinship**
**What type of PR is this?**
/kind bug
/kind failing-test

**What this PR does / why we need it**:
e2e-gci-gce-alpha-features is failing since #94474 merged because of the stupid golang for loop vs closure thing, meaning the IPv4 canary ends up trying to reload rules using the IPv6 iptables client.

Additionally, on the CI hosts, there is no kernel support for ip6tables, so we're getting lots of errors about that. (#94474 originally had code to try to avoid spurious errors if ip6tables _wasn't installed_ but then we realized that basically all distros put iptables and ip6tables in the same package, so that will never happen. But we didn't consider this case.) So this changes kubelet so that if it fails to set up the IPv4/IPv6 iptables rules at startup, it won't set up a watcher loop either.

**Which issue(s) this PR fixes**:
Fixes #95369

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/sig network
/priority important-soon

### CODE REVIEW

File: test/e2e/network/networking.go [hunk 1]
```diff
@@ -477,7 +477,7 @@ var _ = SIGDescribe("Networking", func() {
 		// restart iptables"?). So instead we just manually delete all "KUBE-"
 		// chains.
 
-		ginkgo.By("dumping iptables rules on a node")
+		ginkgo.By("dumping iptables rules on node " + host)
```
Comment (aojea) [inline test/e2e/network/networking.go:480]: I would also log the result, so we can see what iptables rules are there
```
framework.Logf("host %s iptables rules, %s",  host, result)
```

File: pkg/kubelet/kubelet_network_linux.go [hunk 2]
```diff
@@ -47,14 +47,16 @@ func (kl *Kubelet) initNetworkUtil() {
...
+	for i := range iptClients {
+		iptClient := iptClients[i]
+		if kl.syncNetworkUtil(iptClient) {
+			go iptClient.Monitor(
+				utiliptables.Chain("KUBE-KUBELET-CANARY"),
+				[]utiliptables.Table{utiliptables.TableMangle, utiliptables.TableNAT, utiliptables.TableFilter},
+				func() { kl.syncNetworkUtil(iptClient) },
+				1*time.Minute, wait.NeverStop,
+			)
+		}
```
Comment (aojea) [inline pkg/kubelet/kubelet_network_linux.go:64]: I think we should log a warning to inform that we are not going to monitor this family, it is possible that the admin didn't know why is not working, so observing the log at least he has a clue and can install the missing kernel modules, per example, and restart kubelet

File: pkg/kubelet/kubelet_network_linux.go [hunk 3]
```diff
@@ -47,14 +47,16 @@ func (kl *Kubelet) initNetworkUtil() {
...
-		go iptClient.Monitor(
-			utiliptables.Chain("KUBE-KUBELET-CANARY"),
-			[]utiliptables.Table{utiliptables.TableMangle, utiliptables.TableNAT, utiliptables.TableFilter},
-			func() { kl.syncNetworkUtil(iptClient) },
-			1*time.Minute, wait.NeverStop,
-		)
+	for i := range iptClients {
+		iptClient := iptClients[i]
+		if kl.syncNetworkUtil(iptClient) {
+			go iptClient.Monitor(
```
Comment (aojea) [inline pkg/kubelet/kubelet_network_linux.go:58]: Since this only runs once, we can log to inform that the syncNetwork was succesfully on ipfamily X

Comment (aojea) [reply pkg/kubelet/kubelet_network_linux.go:58]: or maybe add it to the `syncNetworkUtil()` before returning?

**Comment by aojea** [comment]
lgtm
just adding more logging, because this is not easy to solve if it fails

File: test/e2e/network/networking.go (hunk 1 above)
Comment (danwinship) [reply test/e2e/network/networking.go:480]: But there are normally _a lot_ of iptables rules, and they're normally interesting for debugging.

Though I guess maybe since this is a `[Disruptive]` test and so only runs in periodics maybe we should err on the side of more pre-emptive debugging...

**Comment by danwinship** [comment]
/test pull-kubernetes-e2e-gce

because `e2e-gce-ubuntu-containerd` passed, but it's a very different environment and didn't hit the ip6tables bug

**Comment by aojea** [comment]
let see this one
/test pull-kubernetes-e2e-gce-alpha-features

File: test/e2e/network/networking.go (hunk 1 above)
Comment (aojea) [reply test/e2e/network/networking.go:480]: I didn't notice that you are already logging the `iptables-save -t nat` below, that should be enough

**Comment by aojea** [comment]
The test is passing on a node does not has ip6tables working

> I1008 12:47:47.403354    1475 factory.go:209] Factory "raw" can handle container "/system.slice/kmod-static-nodes.service", but ignoring.
E1008 12:47:47.403153    1475 kubelet_network_linux.go:78] Failed to ensure that nat chain KUBE-MARK-DROP exists: error creating chain "KUBE-MARK-DROP": exit status 3: ip6tables v1.6.2: can't initialize ip6tables table `nat': Table does not exist (do you need to ins

@danwinship this is ready to go, just remove the debug commit

**Comment by aojea** [comment]
/lgtm
/retest
unrelated failures

**Comment by aojea** [comment]
/assign @thockin 
for final approval

**Comment by dcbw** [comment]
@danwinship verify failure is legit, trailing whitespace:

```
+++ Running case: verify.gofmt 
+++ working dir: /home/prow/go/src/k8s.io/kubernetes
+++ command: bash "hack/make-rules/../../hack/verify-gofmt.sh"
diff -u ./test/e2e/network/networking.go.orig ./test/e2e/network/networking.go
--- ./test/e2e/network/networking.go.orig	2020-10-08 18:22:34.196558025 +0000
+++ ./test/e2e/network/networking.go	2020-10-08 18:22:34.196558025 +0000
@@ -534,7 +534,7 @@
 		})
 		if err != nil {
 			e2essh.LogResult(result)
-		}			
+		}
 		framework.ExpectNoError(err, "kubelet did not recreate its iptables rules")
 	})
 })
```

File: pkg/kubelet/kubelet_network_linux.go [hunk 4]
```diff
@@ -40,21 +40,29 @@ func (kl *Kubelet) initNetworkUtil() {
...
 
-	for _, iptClient := range iptClients {
-		kl.syncNetworkUtil(iptClient)
-		go iptClient.Monitor(
-			utiliptables.Chain("KUBE-KUBELET-CANARY"),
-			[]utiliptables.Table{utiliptables.TableMangle, utiliptables.TableNAT, utiliptables.TableFilter},
-			func() { kl.syncNetworkUtil(iptClient) },
-			1*time.Minute, wait.NeverStop,
-		)
+	for i := range iptClients {
```
Comment (dcbw) [inline pkg/kubelet/kubelet_network_linux.go:53]: `for i, iptClient := iptClients {`

Comment (aojea) [reply pkg/kubelet/kubelet_network_linux.go:53]: that was the bug, you have to capture the variable otherwise the closure function used in the `Monitor` take its reference, and in the next iteration changes it ... as result in a dual stack cluster, if IPv6 is the second family, the monitor only executes `syncNetworkUtil` for IPv6 ... at least is my understanding

File: test/e2e/network/networking.go [hunk 5]
```diff
@@ -532,6 +532,9 @@ var _ = SIGDescribe("Networking", func() {
 			}
 			return false, nil
 		})
+		if err != nil {
+			e2essh.LogResult(result)
+		}
```
Comment (aojea) [inline test/e2e/network/networking.go:537]: gofmt complains here
```
diff -u ./test/e2e/network/networking.go.orig ./test/e2e/network/networking.go
--- ./test/e2e/network/networking.go.orig	2020-10-08 18:22:34.196558025 +0000
+++ ./test/e2e/network/networking.go	2020-10-08 18:22:34.196558025 +0000
@@ -534,7 +534,7 @@
 		})
 		if err != nil {
 			e2essh.LogResult(result)
-		}			
+		}
 		framework.ExpectNoError(err, "kubelet did not recreate its iptables rules")
 	})
 })
```

Comment (aojea) [reply test/e2e/network/networking.go:537]: didn' t realize Dan already reported it sorry
https://github.com/kubernetes/kubernetes/pull/95378#issuecomment-705772125
