### PR TITLE
Fix strategic patch for list of primitive type with merge sementic

### LINKED ISSUE #35163: Strategic merge should support remove or replace items in a list of primitive type
Strategic merge, which is used mostly by `kubectl apply`, should support remove or replace items in a list of primitive type (e.g. string).
For now, it only support merge.

Original: #32398

### PR DESCRIPTION
**Pull request by mengqiy**
Fix strategic patch for list of primitive type when the patch strategy is `merge`.
Before: we cannot replace or delete an item in a list of primitive, e.g. string, when the patch strategy is `merge`. It will always append new items to the list.
This patch will generate a map to update the list of primitive type.
The server with this patch will accept either a new patch or an old patch.
The client will found out the APIserver version before generate the patch.

Fixes #35163, #32398

cc: @pwittrock @fabianofranz 

``` release-note
Fix strategic patch for list of primitive type when patch strategy is `merge` to remove deleted objects.
```

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/35647)

### CODE REVIEW

**Comment by ymqytw** [comment]
This change will break the current tests, since part of the format of the format has changed.
I will fix them and add new tests when everyone is happy with the change.

**Comment by ymqytw** [comment]
Currently the old the client will be able to talk to the new API server and the API server will behave the same when merging the patch.
But an old server will not accept a patch that generated by the new client. It will fail.
I can add some logic to let the `kubectl` get the API server version first before generating the patch, if we need.

**Comment by ymqytw** [comment]
@k8s-bot ok to test

**Comment by pwittrock** [comment]
@ymqytw Any idea why the tests failed?

**Comment by ymqytw** [comment]
I guess something went wrong with the test-infra, since I found many tests were failing because of `IsUp` or  `Up` exit with status 1.

**Comment by ymqytw** [comment]
@k8s-bot test this

**Comment by pwittrock** [comment]
@ymqytw  Let me know if I should take a look again

**Comment by ymqytw** [comment]
Create a issue #35936 for `pkg/client/record/events_cache.go` touched in this PR.

**Comment by ymqytw** [comment]
@k8s-bot cvm gke e2e test this

**Comment by ymqytw** [comment]
@pwittrock PTAL

**Comment by ymqytw** [comment]
@pwittrock I re-organized all the commits for easier review. But it seems changes in `patch_test.go` is too large, I'm not sure where can you review it.

**Comment by pwittrock** [comment]
Any idea what this is about?

>
error: Could not remove config section 'remote.bootstrap-upstream'

**Comment by ymqytw** [comment]
@pwittrock I don't know. But I have asked Jeff for help. I thinking he is looking into it now.

**Comment by ymqytw** [comment]
The update should fix the failure.

**Comment by ymqytw** [comment]
@k8s-bot gce etcd3 e2e test this

**Comment by pwittrock** [comment]
Review status: 0 of 24 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/kubectl/cmd/util/helpers.go, line 756 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVX7f78F8Q0725_Aj2i:-KVX7f78F8Q0725_Aj2j:b-x24mfn) ([raw file](https://github.com/kubernetes/kubernetes/blob/552af7dd296864f885ade6c57e73a88bcc652390/pkg/kubectl/cmd/util/helpers.go#L756)):*
> ```Go
> }
> 
> func TryToRunIfUseNewBehaviorForPatch(f Factory) (bool, error) {
> ```

Add comments explaining what this does and what it returns

---

*[pkg/kubectl/cmd/util/helpers.go, line 763 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVX7zIy7nuuisoiyonm:-KVX7zIzeeZxOqPopSe3:b8uurzu) ([raw file](https://github.com/kubernetes/kubernetes/blob/552af7dd296864f885ade6c57e73a88bcc652390/pkg/kubectl/cmd/util/helpers.go#L763)):*
> ```Go
> 			panicInfo := recover()
> 			if panicInfo != nil {
> 				ifUseNewPatchBehavior = true
> ```

Add a comment explaining why we use the newPatch for a panic

---

*[pkg/util/strategicpatch/patch.go, line 346 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KV7QZG3TkAvXkW6iGoy:-KV7QZG3TkAvXkW6iGoz:bo6skp4) ([raw file](https://github.com/kubernetes/kubernetes/blob/fd8ff449c3e4744145ab0d042a427fafe4cfc8b0/pkg/util/strategicpatch/patch.go#L346)):*
> ```Go
> 		originalString := fmt.Sprintf("%v", originalScalars[originalIndex])
> 		modifiedString := fmt.Sprintf("%v", modifiedScalars[modifiedIndex])
> 		if originalString > modifiedString {
> ```

Deep nesting of ifs like this is hard to follow.  Go style recommends checking for conditions to bail:

```go
// objects are identical
if originalString == modified {
  originalIndex++
  modifiedIndex++
  continue
}

if originalString > modifiedString {

} else {

} 

```

---

*[pkg/util/strategicpatch/patch.go, line 1393 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVX8GdpRqKpv50PvT4q:-KVX8GdpRqKpv50PvT4r:b3cjqdu) ([raw file](https://github.com/kubernetes/kubernetes/blob/552af7dd296864f885ade6c57e73a88bcc652390/pkg/util/strategicpatch/patch.go#L1393)):*
Add a comment explaining what this does.  The name is a bit confusing - calling it `DoesServerSupportPatchVersion` might help..  I would make the fn support different patch types and pass in what you want to know.

e.g. Create a type for StrategicMergePatchVersion (SMPV) and constant.

SMPatchVersion.1_5

and then pass in

>
DoesServerSupportSMPatchVersion(discoveryClient, SMPVersion.1_5)

Or even have it return the max patch version supported:

>
GetServerSupportedSMPatchVersion(discoveryClient) SMPatchVersion {
}

With an "Unknown" version for when we can't talk to the server

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647)*

**Comment by ymqytw** [comment]
Review status: 0 of 27 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/kubectl/cmd/util/helpers.go, line 756 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVX7f78F8Q0725_Aj2i:-KVbWPgKFqeSJbJ9Lh5S:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/552af7dd296864f885ade6c57e73a88bcc652390/pkg/kubectl/cmd/util/helpers.go#L756)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Add comments explaining what this does and what it returns
</details>
Done.

---

*[pkg/kubectl/cmd/util/helpers.go, line 763 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVX7zIy7nuuisoiyonm:-KVbWQ8KZ_FpBcCbfmma:b5kvyoh) ([raw file](https://github.com/kubernetes/kubernetes/blob/552af7dd296864f885ade6c57e73a88bcc652390/pkg/kubectl/cmd/util/helpers.go#L763)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Add a comment explaining why we use the newPatch for a panic
</details>
Don't need `panic-recover` any more. Fixed all the unit tests.

---

*[pkg/util/strategicpatch/patch.go, line 346 at r2](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KV7QZG3TkAvXkW6iGoy:-KVbWX99SRpuyDHtOhKa:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/fd8ff449c3e4744145ab0d042a427fafe4cfc8b0/pkg/util/strategicpatch/patch.go#L346)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Deep nesting of ifs like this is hard to follow.  Go style recommends checking for conditions to bail:
> 
> ```go
> // objects are identical
> if originalString == modified {
>   originalIndex++
>   modifiedIndex++
>   continue
> }
> 
> if originalString > modifiedString {
> 
> } else {
> 
> } 
> 
> ```
> 
</details>
Done.

---

*[pkg/util/strategicpatch/patch.go, line 1393 at r6](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVX8GdpRqKpv50PvT4q:-KVbWdZghBYgleJLgzYf:b-9ep5yb) ([raw file](https://github.com/kubernetes/kubernetes/blob/552af7dd296864f885ade6c57e73a88bcc652390/pkg/util/strategicpatch/patch.go#L1393)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Add a comment explaining what this does.  The name is a bit confusing - calling it `DoesServerSupportPatchVersion` might help..  I would make the fn support different patch types and pass in what you want to know.
> 
> e.g. Create a type for StrategicMergePatchVersion (SMPV) and constant.
> 
> SMPatchVersion.1_5
> 
> and then pass in
> 
> >
> DoesServerSupportSMPatchVersion(discoveryClient, SMPVersion.1_5)
> 
> Or even have it return the max patch version supported:
> 
> >
> GetServerSupportedSMPatchVersion(discoveryClient) SMPatchVersion {
> }
> 
> With an "Unknown" version for when we can't talk to the server
> 
> 
</details>
Done. I will try to update it to GetServerSupportedSMPatchVersion later today.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647)*

**Comment by ymqytw** [comment]
Update the code to use `GetServerSupportedSMPatchVersion()`

**Comment by ymqytw** [comment]
@pwittrock PTAL

**Comment by pwittrock** [comment]
Review status: 0 of 28 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/util/strategicpatch/patch.go, line 51 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KV_VSOjorMuAZm5LolP:-KV_VSOjorMuAZm5LolQ:b-2buxez) ([raw file](https://github.com/kubernetes/kubernetes/blob/b5ab1e022c1f6a4b478533f36da021ca5243dacc/pkg/util/strategicpatch/patch.go#L51)):*
We should call this something other than "New".  Maybe just 

>

---

*[pkg/util/strategicpatch/patch.go, line 258 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KV_VqNrWQgLcALt3c6G:-KV_VqNrWQgLcALt3c6H:b-csullu) ([raw file](https://github.com/kubernetes/kubernetes/blob/b5ab1e022c1f6a4b478533f36da021ca5243dacc/pkg/util/strategicpatch/patch.go#L258)):*
> ```Go
> 
> 			if fieldPatchStrategy == mergeDirective {
> 				patchValue, err := diffLists(originalValueTyped, modifiedValueTyped, fieldType.Elem(), fieldPatchMergeKey, ignoreChangesAndAdditions, ignoreDeletions, ifUseNewPatchBehavior)
> ```

We should refactor this later (not now).

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647)*

**Comment by pwittrock** [comment]
Still chewing through this.  Sorry for the delay.

---







*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-:-KVegXrkO4KGogXS6S7y:br9j4ev)*

**Comment by ymqytw** [comment]
*[pkg/util/strategicpatch/patch.go, line 51 at r3](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KV_VSOjorMuAZm5LolP:-KVeqMUFkOXF6xbk_OyD:b-6i5hu1) ([raw file](https://github.com/kubernetes/kubernetes/blob/b5ab1e022c1f6a4b478533f36da021ca5243dacc/pkg/util/strategicpatch/patch.go#L51)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> We should call this something other than "New".  Maybe just 
> 
> >
> 
</details>
It looks like you commented on `r3`, which is not the latest one.
We should be on `r14`.
There are no "New" now.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647)*

**Comment by pwittrock** [comment]
Review status: 0 of 28 files reviewed at latest revision, 18 unresolved discussions.

---

*[pkg/client/record/events_cache.go, line 248 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVes1ISxedDbdyrzUcJ:-KVes1ISxedDbdyrzUcK:b-5eu2l4) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/client/record/events_cache.go#L248)):*
> ```Go
> 		oldData, _ := json.Marshal(eventCopy2)
> 		// TODO: need to figure out if we need to let eventObserve() use the new behavior of StrategicMergePatch.
> 		// Currently default to old behavior now. Ref: issue #35936
> ```

@caesarxuchao What is the right thing to do here?

---

*[pkg/kubectl/cmd/annotate.go, line 199 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVerY_X5S5a4oesFavj:-KVerY_X5S5a4oesFavk:b-nljk9x) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/kubectl/cmd/annotate.go#L199)):*
> ```Go
> 	}
> 
> 	ifUseSMPatchVersion_1_5 := true
> ```

Explain why 1_5 is safe when using local.  Do we want to always default to the most recent version for local?  If so we should update this when we start to pass in the version instead of a boolean

---

*[pkg/kubectl/cmd/set/helper.go, line 123 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVerDIpKb-Ru1kI_5KU:-KVerDIpKb-Ru1kI_5KV:b-pch9tl) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/kubectl/cmd/set/helper.go#L123)):*
> ```Go
> // the changes in the object. Encoder must be able to encode the info into the appropriate destination type. If mutateFn
> // returns false, the object is not included in the final list of patches. If local is false, it will contact the server to
> // check which StategicMergePatchVersion to use. Otherwise, it will default to SMPatchVersion_1_5.
> ```

Why is this safe to do?  What does local mean?  Update the comment explaining the assumptions that make this the right choice.

---

*[pkg/util/strategicpatch/patch.go, line 49 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVemYCRmaO6yfZK_qr2:-KVemYCRmaO6yfZK_qr3:b7b2zwn) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L49)):*
> ```Go
> 	replaceDirective          = "replace"
> 	mergeDirective            = "merge"
> 	listOfPrimitivesDirective = "patch"
> ```

Should this be 

```go
mergePrimitivesListDirective = "mergeprimitiveslist"
```

---

*[pkg/util/strategicpatch/patch.go, line 340 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVenFSaN4xlTSs2uPei:-KVenFSaN4xlTSs2uPej:b4hdm2m) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L340)):*
> ```Go
> // Returns a (recursive) strategic merge patch that yields modified when applied to original,
> // for a pair of lists of scalars with merge semantics.
> func diffListsOfScalars(original, modified []interface{}, ignoreChangesAndAdditions, ignoreDeletions, ifUseSMPatchVersion_1_5 bool) (interface{}, error) {
> ```

Upon further thought, we should just pass in the version string maybe:

```go
supportedPatchVersion string
```

...

```go
switch supportedPatchVersion {
case supportedPatchVersion >= SMPatchVersion.1_5:
  // Support for merging maps introduced in the server in 1.5
 return patchPrimitiveSliceUsingMap(...)
default:
  return patchSliceIntoPrimitiveSliceUsingSlice(...)
}
```

---

*[pkg/util/strategicpatch/patch.go, line 340 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVenkqUSC82r5ftuM_a:-KVenkqUSC82r5ftuM_b:bfrsz8u) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L340)):*
> ```Go
> // Returns a (recursive) strategic merge patch that yields modified when applied to original,
> // for a pair of lists of scalars with merge semantics.
> func diffListsOfScalars(original, modified []interface{}, ignoreChangesAndAdditions, ignoreDeletions, ifUseSMPatchVersion_1_5 bool) (interface{}, error) {
> ```

Add comments for each of the args and explain what strategy is used.  This functions is getting hard to follow.  Consider splitting it into 2 functions, 1 for each of the strategies.

---

*[pkg/util/strategicpatch/patch.go, line 617 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVeqe3XJZ_1GsA4g_1w:-KVeqe3XJZ_1GsA4g_1x:b-7s6d17) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L617)):*
> ```Go
> 
> 		if v == listOfPrimitivesDirective {
> 			delete(original, directiveMarker)
> ```

Why are we doing this?  Add a comment explaining this line (like the ones above it).

---

*[pkg/util/strategicpatch/patch.go, line 699 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVej81CK8ftDbgD9tdz:-KVej81DaATdvHfA0iCT:b-l4v03t) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L699)):*
> ```Go
> // Merge two slices together. Note: This may modify both the original slice and
> // the patch because getting a deep copy of a slice in golang is highly
> // non-trivial.
> ```

Update comment on the method explaining the valid types for patch and behavior

---

*[pkg/util/strategicpatch/patch.go, line 707 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVejzlLoJIeU7O4vSWg:-KVejzlMmfP78nvFrk7g:bcs3qev) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L707)):*
> ```Go
> 
> 	if patchMap, ok := patch.(map[string]interface{}); ok {
> 		if directiveValue, ok := patchMap[directiveMarker]; ok && directiveValue == listOfPrimitivesDirective {
> ```

What is this statement for?  Add a comment

---

*[pkg/util/strategicpatch/patch.go, line 709 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVejjmfwWCDb8HWGxqO:-KVejjmfwWCDb8HWGxqP:b-6hvxkw) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L709)):*
> ```Go
> 		if directiveValue, ok := patchMap[directiveMarker]; ok && directiveValue == listOfPrimitivesDirective {
> 			return mergeSliceOfScalarsWithPatchMap(original, patchMap), nil
> 		}
> ```

What happens if the inner-if statement isn't executed?  Looks like it will cast to a slice which will panic right?

---

*[pkg/util/strategicpatch/patch.go, line 810 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVekaqZRdxLUq8NA5Jw:-KVekaqZRdxLUq8NA5Jx:b-4kyfht) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L810)):*
> ```Go
> }
> 
> func mergeSliceOfScalarsWithPatchMap(original []interface{}, patch map[string]interface{}) []interface{} {
> ```

Add a comment explaining how this is merged.  What are the markers in the patch map?  What is the strategy?

---

*[pkg/util/strategicpatch/patch.go, line 828 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVelNrOzdpbQu0uVs2w:-KVelNrOzdpbQu0uVs2x:b-dxdb9u) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L828)):*
Reads a bit awkward.  Maybe 

>
No action required to delete items that missing from the original slice.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647)*

**Comment by pwittrock** [comment]
*[pkg/util/strategicpatch/patch.go, line 656 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVetSWM5e747oxnLQUi:-KVetSWM5e747oxnLQUj:b-uuzst8) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L656)):*
> ```Go
> 		originalType := reflect.TypeOf(original[k])
> 		patchType := reflect.TypeOf(patchV)
> 		if originalType == patchType || (originalType != nil && patchType != nil && originalType.Kind() == reflect.Slice && patchType.Kind() == reflect.Map) {
> ```

This is a pretty dense statement.  Document what it means.  Consider pulling the bool statements into self-documenting variables.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647)*

**Comment by ymqytw** [comment]
Review status: 0 of 28 files reviewed at latest revision, 19 unresolved discussions.

---

*[pkg/kubectl/cmd/annotate.go, line 199 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVerY_X5S5a4oesFavj:-KVf4L9B1Pg331Hp1XgU:b-gwmuul) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/kubectl/cmd/annotate.go#L199)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Explain why 1_5 is safe when using local.  Do we want to always default to the most recent version for local?  If so we should update this when we start to pass in the version instead of a boolean
</details>
Updated the code. Only let the client contact server when it's non-local.
When it' local mode, the client just [update the annotation localy](https://github.com/kubernetes/kubernetes/blob/2f275ff330e50c911d0505cf2f2e9abb93fe0cb5/pkg/kubectl/cmd/annotate.go#L228) and print out the obj. In this cae, we don't need the SMPatchVersion at all

---

*[pkg/kubectl/cmd/set/helper.go, line 123 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVerDIpKb-Ru1kI_5KU:-KVfDRWE6kw2FS_lG-0h:b-o12e4b) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/kubectl/cmd/set/helper.go#L123)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Why is this safe to do?  What does local mean?  Update the comment explaining the assumptions that make this the right choice.
</details>
In local mode, the invokers  of`CalculatePatches()` are using the `Patch` filed only to check if there are changes. They don't apply the patch at all. So it should be safe to use defaulting in `CalculatePatches()` when in local mode.

---

*[pkg/util/strategicpatch/patch.go, line 49 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVemYCRmaO6yfZK_qr2:-KVfLSTN0uTOnOPy0_6F:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L49)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Should this be 
> 
> ```go
> mergePrimitivesListDirective = "mergeprimitiveslist"
> ```
</details>
Done.

---

*[pkg/util/strategicpatch/patch.go, line 340 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVenFSaN4xlTSs2uPei:-KVfpfreFkce246B1mVn:b-ynls93) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L340)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Upon further thought, we should just pass in the version string maybe:
> 
> ```go
> supportedPatchVersion string
> ```
> 
> ...
> 
> ```go
> switch supportedPatchVersion {
> case supportedPatchVersion >= SMPatchVersion.1_5:
>   // Support for merging maps introduced in the server in 1.5
>  return patchPrimitiveSliceUsingMap(...)
> default:
>   return patchSliceIntoPrimitiveSliceUsingSlice(...)
> }
> ```
> 
</details>
I guess you are saying `diffListsOfScalars`.
Done.

---

*[pkg/util/strategicpatch/patch.go, line 340 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVenkqUSC82r5ftuM_a:-KVfLFzs-Yd3c4zn-mzL:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L340)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Add comments for each of the args and explain what strategy is used.  This functions is getting hard to follow.  Consider splitting it into 2 functions, 1 for each of the strategies.
</details>
Done.

---

*[pkg/util/strategicpatch/patch.go, line 617 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVeqe3XJZ_1GsA4g_1w:-KVfcDwutVxB5Ul7MJd4:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L617)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Why are we doing this?  Add a comment explaining this line (like the ones above it).
</details>
Done.

---

*[pkg/util/strategicpatch/patch.go, line 656 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVetSWM5e747oxnLQUi:-KVfO3XDNRkrbKaq5nuo:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L656)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> This is a pretty dense statement.  Document what it means.  Consider pulling the bool statements into self-documenting variables.
</details>
Done.

---

*[pkg/util/strategicpatch/patch.go, line 699 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVej81CK8ftDbgD9tdz:-KVfeA8NUMGyRio0qQrO:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L699)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Update comment on the method explaining the valid types for patch and behavior
</details>
Done.

---

*[pkg/util/strategicpatch/patch.go, line 707 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVejzlLoJIeU7O4vSWg:-KVfepMpcl1FGa6GBLih:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L707)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> What is this statement for?  Add a comment
</details>
Done.

---

*[pkg/util/strategicpatch/patch.go, line 709 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVejjmfwWCDb8HWGxqO:-KVfer-jfu44eZyyk6lu:bi237u8) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L709)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> What happens if the inner-if statement isn't executed?  Looks like it will cast to a slice which will panic right?
</details>
Added an else clause to handle that case.

---

*[pkg/util/strategicpatch/patch.go, line 810 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVekaqZRdxLUq8NA5Jw:-KVfiuMPd7zwliapwd62:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L810)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Add a comment explaining how this is merged.  What are the markers in the patch map?  What is the strategy?
</details>
Done.

---

*[pkg/util/strategicpatch/patch.go, line 828 at r13](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647#-KVelNrOzdpbQu0uVs2w:-KVfhkfbt7M9sGD1Mtp5:b-896fix) ([raw file](https://github.com/kubernetes/kubernetes/blob/24ab1184683d5f97d32b74f9647ef5fd1442b9cc/pkg/util/strategicpatch/patch.go#L828)):*
<details><summary><i>Previously, pwittrock (Phillip Wittrock) wrote…</i></summary>
> Reads a bit awkward.  Maybe 
> 
> >
> No action required to delete items that missing from the original slice.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/kubernetes/35647)*

**Comment by ymqytw** [comment]
@k8s-bot gci gke e2e test this

**Comment by ymqytw** [comment]
@pwittrock PTAL

**Comment by ymqytw** [comment]
Rebased.

**Comment by pwittrock** [comment]
@AdoHe @fabianofranz  Hey Tony / Fabiano.  I am at Kubecon in SEA the next few days and dropped the ball on this.  Would either of you be willing to add yourself as an assignee and finish this review?  The context is that it fixes merging lists of primitive types (before it just appended, now it can delete items)

**Comment by AdoHe** [comment]
@pwittrock sure, I can help review this. This should be merged into 1.5, I will review today.

**Comment by AdoHe** [comment]
@ymqytw please rebase this anyway.

**Comment by ymqytw** [comment]
@AdoHe Rebased.

**Comment by ymqytw** [comment]
@AdoHe Rebased again.

File: pkg/kubectl/cmd/util/helpers.go [hunk 1]
```diff
@@ -725,3 +725,13 @@ func RequireNoArguments(c *cobra.Command, args []string) {
 		CheckErr(UsageError(c, fmt.Sprintf(`unknown command %q`, strings.Join(args, " "))))
 	}
 }
+
+// RunGetServerSupportedSMPatchVersion is a wrapper of GetServerSupportedSMPatchVersion(),
```
Comment (fabianofranz) [inline pkg/kubectl/cmd/util/helpers.go]: Comment must start with "GetServerSupportedSMPatchVersionFromFactory" for godoc.

File: pkg/util/strategicpatch/patch.go [hunk 2]
```diff
@@ -133,15 +144,15 @@ func RequireMetadataKeyUnchanged(key string) PreconditionFunc {
 }
 
 // Deprecated: Use the synonym CreateTwoWayMergePatch, instead.
-func CreateStrategicMergePatch(original, modified []byte, dataStruct interface{}) ([]byte, error) {
-	return CreateTwoWayMergePatch(original, modified, dataStruct)
+func CreateStrategicMergePatch(original, modified []byte, dataStruct interface{}, SMPatchVersion StrategicMergePatchVersion) ([]byte, error) {
```
Comment (fabianofranz) [inline pkg/util/strategicpatch/patch.go]: Same here.

File: pkg/util/strategicpatch/patch.go [hunk 3]
```diff
@@ -133,15 +144,15 @@ func RequireMetadataKeyUnchanged(key string) PreconditionFunc {
...
+	return CreateTwoWayMergePatch(original, modified, dataStruct, SMPatchVersion)
 }
 
 // CreateTwoWayMergePatch creates a patch that can be passed to StrategicMergePatch from an original
 // document and a modified document, which are passed to the method as json encoded content. It will
 // return a patch that yields the modified document when applied to the original document, or an error
 // if either of the two documents is invalid.
-func CreateTwoWayMergePatch(original, modified []byte, dataStruct interface{}, fns ...PreconditionFunc) ([]byte, error) {
+func CreateTwoWayMergePatch(original, modified []byte, dataStruct interface{}, SMPatchVersion StrategicMergePatchVersion, fns ...PreconditionFunc) ([]byte, error) {
```
Comment (fabianofranz) [inline pkg/util/strategicpatch/patch.go]: Same here.

File: pkg/util/strategicpatch/patch.go [hunk 4]
```diff
@@ -177,7 +188,7 @@ func CreateTwoWayMergePatch(original, modified []byte, dataStruct interface{}, f
 }
 
 // Returns a (recursive) strategic merge patch that yields modified when applied to original.
-func diffMaps(original, modified map[string]interface{}, t reflect.Type, ignoreChangesAndAdditions, ignoreDeletions bool) (map[string]interface{}, error) {
+func diffMaps(original, modified map[string]interface{}, t reflect.Type, ignoreChangesAndAdditions, ignoreDeletions bool, SMPatchVersion StrategicMergePatchVersion) (map[string]interface{}, error) {
```
Comment (fabianofranz) [inline pkg/util/strategicpatch/patch.go]: Same here.

File: pkg/util/strategicpatch/patch.go [hunk 5]
```diff
@@ -284,7 +307,7 @@ func diffMaps(original, modified map[string]interface{}, t reflect.Type, ignoreC
 
 // Returns a (recursive) strategic merge patch that yields modified when applied to original,
 // for a pair of lists with merge semantics.
-func diffLists(original, modified []interface{}, t reflect.Type, mergeKey string, ignoreChangesAndAdditions, ignoreDeletions bool) ([]interface{}, error) {
+func diffLists(original, modified []interface{}, t reflect.Type, mergeKey string, ignoreChangesAndAdditions, ignoreDeletions bool, SMPatchVersion StrategicMergePatchVersion) (interface{}, error) {
```
Comment (fabianofranz) [inline pkg/util/strategicpatch/patch.go]: Same here.

File: pkg/util/strategicpatch/patch.go [hunk 6]
```diff
@@ -315,27 +340,38 @@ func diffLists(original, modified []interface{}, t reflect.Type, mergeKey string
 
 // Returns a (recursive) strategic merge patch that yields modified when applied to original,
 // for a pair of lists of scalars with merge semantics.
-func diffListsOfScalars(original, modified []interface{}) ([]interface{}, error) {
-	if len(modified) == 0 {
+func diffListsOfScalars(original, modified []interface{}, ignoreChangesAndAdditions, ignoreDeletions bool, SMPatchVersion StrategicMergePatchVersion) (interface{}, error) {
```
Comment (fabianofranz) [inline pkg/util/strategicpatch/patch.go]: Same here.

File: pkg/util/strategicpatch/patch.go [hunk 7]
```diff
@@ -360,7 +446,7 @@ var errBadArgTypeFmt = "expected a %s, but received a %s"
 
 // Returns a (recursive) strategic merge patch that yields modified when applied to original,
 // for a pair of lists of maps with merge semantics.
-func diffListsOfMaps(original, modified []interface{}, t reflect.Type, mergeKey string, ignoreChangesAndAdditions, ignoreDeletions bool) ([]interface{}, error) {
+func diffListsOfMaps(original, modified []interface{}, t reflect.Type, mergeKey string, ignoreChangesAndAdditions, ignoreDeletions bool, SMPatchVersion StrategicMergePatchVersion) ([]interface{}, error) {
```
Comment (fabianofranz) [inline pkg/util/strategicpatch/patch.go]: Same here.

File: pkg/util/strategicpatch/patch.go [hunk 8]
```diff
@@ -1172,7 +1339,7 @@ func mapsOfMapsHaveConflicts(typedLeft, typedRight map[string]interface{}, struc
 // than from original to current. In other words, a conflict occurs if modified changes any key
 // in a way that is different from how it is changed in current (e.g., deleting it, changing its
 // value).
-func CreateThreeWayMergePatch(original, modified, current []byte, dataStruct interface{}, overwrite bool, fns ...PreconditionFunc) ([]byte, error) {
+func CreateThreeWayMergePatch(original, modified, current []byte, dataStruct interface{}, overwrite bool, SMPatchVersion StrategicMergePatchVersion, fns ...PreconditionFunc) ([]byte, error) {
```
Comment (fabianofranz) [inline pkg/util/strategicpatch/patch.go]: Same here.

**Review by fabianofranz — COMMENTED** [review]
A few comments. @pwittrock I don't think we can change assignees, would you mind adding both me and @AdoHe? We'll finish the review and get this in.

**Comment by ymqytw** [comment]
Addressed comments. Can someone tag a `v1.5` label?

**Comment by ymqytw** [comment]
@k8s-bot unit test this

**Comment by pwittrock** [comment]
@fabianofranz @AdoHe Thanks so much!

**Comment by ymqytw** [comment]
@k8s-bot unit test this

**Comment by fabianofranz** [comment]
Nice one @ymqytw! @pwittrock can you add the 1.5 label?

**Comment by fabianofranz** [comment]
@pwittrock ah, and looks like @k8s-merge-robot is not happy about the release note label. :)

**Comment by ymqytw** [comment]
Squashed commits for merging.

**Comment by ymqytw** [comment]
@k8s-bot test this

**Comment by ymqytw** [comment]
@k8s-bot unit test this
@k8s-bot node e2e test this

**Comment by ymqytw** [comment]
@saad-ali This is a bug-fixing PR for #35163, #32398 target for `v1.5`. @pwittrock and @fabianofranz can comfirm that.
We need to tag label `release note` and remove `do-not-merge` label.
It looks big, because the change in the test file is big.

**Comment by saad-ali** [comment]
> @saad-ali This is a bug-fixing PR for #35163, #32398 target for v1.5. @pwittrock and @fabianofranz can confirm that.
> We need to tag label release note and remove do-not-merge label.
> It looks big, because the change in the test file is big.

Ack, thanks!

File: pkg/kubectl/cmd/taint.go [hunk 9]
```diff
@@ -321,6 +321,11 @@ func (o TaintOptions) RunTaint() error {
 		return err
 	}
 
+	smPatchVersion, err := cmdutil.GetServerSupportedSMPatchVersionFromFactory(o.f)
```
Comment (smarterclayton) [inline pkg/kubectl/cmd/taint.go]: You cannot error and exit here - servers that don't export /version (for security reasons) are now broken.  All uses of this method must ignore errors.  This is a blocker for 1.5 @saad-ali

**Comment by pwittrock** [comment]
@smarterclayton Since this was already merged should we rollback?  Is it possible to reconcile your commands while still enabling STMRG patching lists of primitive types?

Would you recommend that we always send the new patch format and drop client/server backwards compatibility /  Make a best effort attempt to get the server version(s) and keep some backwards compatibility /  Leave it as is / Something else?

**Comment by ymqytw** [comment]
@smarterclayton If we encounter error when calling `GetServerSupportedSMPatchVersion()`, it's safe to default to the old behavior as v1.4 which won't break any older server. But it will leave apply broken for list of primitives.
What is the solution?

**Comment by pwittrock** [comment]
@smarterclayton WDYT of defaulting to the new patch version when we can't get the supported version from the server?  Is it safe to require that all servers will support the same STMRG version?  I am not sure if there is a perfect solution here and want to make sure we make a good set of tradeoffs.

**Comment by smarterclayton** [comment]
I'm ok with defaulting to the latest (if we are broken with the old way).
Just need a default and not to error out.

On Wed, Nov 16, 2016 at 11:31 AM, Phillip Wittrock <notifications@github.com

**Comment by bgrant0607** [comment]
@pwittrock @ymqytw Sorry I didn't think about this very hard before.

I don't like that the patch deviates from the schema of the resource. Among other things, that prevents us from using the schema validator on patches.

Was a parallel list considered instead?

Also, we need to update the existing SMP doc:
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#strategic-merge-patch

And ideally we'd write a more complete user-facing version of that section.

Also, I didn't have time to read the whole discussion, but I don't think it's valid to base any functionality on the release version. For instance, it's not clear to me that every use of Kubernetes source code is going to report the same release info. If we agree that this is the case, we need to document it in the api conventions.

**Comment by ymqytw** [comment]
> I don't think it's valid to base any functionality on the release version.

@bgrant0607 This part has been removed in #36916. In that PR, we change the behavior to:
first try the new patch, if it fails because the server don't recognize it, it will try the old patch.

**Comment by bgrant0607** [comment]
Thanks @ymqytw.

Also, `mergeprimitiveslist` deviates from our API conventions -- everything else in the API is camelCase or CamelCase. Since the other directives are lowercase, I'd expect `mergePrimitivesList`.

However, if we changed to parallel lists, we'd replace `mergeprimitiveslist`. For example, to delete one list entry from this:
```
finalizers: [ "A", "B", "C" ]
```
We could write something like:
```
"$deleteFromStringList/finalizers": ["C"]
```

**Comment by pwittrock** [comment]
This makes sense to me @ymqytw given that the 1.5 cut date is fast approaching, what is your confidence that we could change the implementation to match @bgrant0607 's suggestion before the deadline?

**Comment by ymqytw** [comment]
@pwittrock I can try to create a PR for review before thanksgiving.

**Comment by pwittrock** [comment]
Sounds good.  Otherwise we may need to consider rolling back the client changes.

**Comment by bgrant0607** [comment]
@pwittrock Is there a reason why we can't just rollback and try again in 1.6? What's blocked by this?

**Comment by bgrant0607** [comment]
With my proposed approach, I believe older apiservers would just ignore the additional directives, though we should confirm that is true.

**Comment by bgrant0607** [comment]
@ymqytw @pwittrock Please email sig-api-machinery to give them the opportunity to chime in before we merge the new approach.

**Comment by pwittrock** [comment]
@bgrant0607 Nothing is blocked by this.  The finalizers field in ObjectMeta were changed to use the a merge strategy, so this would be newly broken in 1.5.  @caesarxuchao, I believe that you indicated that this was acceptable for 1.5 - would you confirm?  If that is the case, rolling back the changes SGTM.

**Comment by caesarxuchao** [comment]
Rolling back is fine. The garbage collector does NOT use patch to update the finalizers.

**Comment by ymqytw** [comment]
@pwittrock I think we should try the new way in 1.6. It may be too risky to do that for 1.5. Since there is only 1 week left, because of the Thanksgiving holiday.
I'm reverting these PR now.

**Comment by pwittrock** [comment]
Agreed

**Comment by ymqytw** [comment]
Reverting related PRs in #37343.

**Comment by lavalamp** [comment]
Not that we should necessarily copy them, but mongo does it this way: https://docs.mongodb.com/manual/reference/operator/update/pull/

(I think 'pull' is a silly name for this.)

I do think $deleteFromStringList is overly specific, though. Perhaps 'primitive' instead of string?

**Comment by ymqytw** [comment]
@lavalamp I created a design doc PR #37652 for this. PTAL
