### PR TITLE
Exposing http.Client for configurable timeouts

### LINKED ISSUE #16793: Allow setting http request timeout in kubernetes client
I would like to set an http request timeout in the kubernetes Go client, however:

1. The underlying http client is not exposed.
2. Even if I access the underlying http client through an (admittedly inelegant) cast and set the timeout, requests fail because the Transport does not support the CancelRequest method.

The example below fails with `cannot make request: net/http: Client Transport of type *unversioned.userAgentRoundTripper doesn't support CancelRequest; Timeout not supported`

```go
package main

import (
        "fmt"
        k8sClient "k8s.io/kubernetes/pkg/client/unversioned"
        "net/http"
        "time"
)

func main() {
        client, err := k8sClient.NewInCluster()
        if err != nil {
                fmt.Printf("cannot create client: %s\n", err)
                return
        }
        httpClient, ok := client.RESTClient.Client.(*http.Client)
        if !ok {
                fmt.Println("cannot cast k8s client to http client")
        }
        httpClient.Timeout = time.Millisecond * 500
        if _, err := client.Services("default").Get("foo"); err != nil {
                fmt.Printf("cannot make request: %s\n", err)
        }
}
```

### PR DESCRIPTION
**Pull request by krousey**
fixes #16793

### CODE REVIEW

File: pkg/client/unversioned/restclient.go [hunk 1]
```diff
@@ -88,6 +89,9 @@ func (c *RESTClient) Verb(verb string) *Request {
 	if c.Throttle != nil {
 		c.Throttle.Accept()
 	}
+	if c.Client == nil {
+		return NewRequest(nil, verb, c.baseURL, c.apiVersion, c.Codec)
+	}
```
Comment (caesarxuchao) [inline pkg/client/unversioned/restclient.go]: Why do we need to make this a special case? Seems the next line will handle this case.

File: pkg/kubectl/cmd/apply_test.go [hunk 2]
```diff
@@ -220,7 +219,7 @@ func TestApplyNonExistObject(t *testing.T) {
 		Client: fake.HTTPClientFunc(func(req *http.Request) (*http.Response, error) {
 			switch p, m := req.URL.Path, req.Method; {
 			case p == pathNameRC && m == "GET":
-				return &http.Response{StatusCode: 404}, errors.NewNotFound("ReplicationController", "")
+				return &http.Response{StatusCode: 404, Body: ioutil.NopCloser(bytes.NewReader(nil))}, nil
```
Comment (caesarxuchao) [inline pkg/kubectl/cmd/apply_test.go]: Why do we need to change this?

File: pkg/client/unversioned/fake/fake.go [hunk 3]
```diff
@@ -28,15 +28,21 @@ import (
 	"k8s.io/kubernetes/pkg/runtime"
 )
 
-type HTTPClientFunc func(*http.Request) (*http.Response, error)
+func HTTPClientFunc(f func(*http.Request) (*http.Response, error)) *http.Client {
```
Comment (caesarxuchao) [inline pkg/client/unversioned/fake/fake.go]: Can we change the name of this function to something like "CreateHTTPClient"?

File: pkg/client/unversioned/restclient.go (hunk 1 above)
Comment (krousey) [inline pkg/client/unversioned/restclient.go]: `NewRequest` takes an interface as its first parameter. You can think of an interface as a tuple of value and the type of the value. `(v, t)`. A nil check against and interface(`intf == nil`) is only true if both `t` AND `v` are nil. `c.Client` is a nil value, but it has a type, `*http.Client`. So when we pass it, it is `(nil, *http.Client)`. The nil check in the request code doesn't catch this, tries to use it, then panics. To prevent this, we pass an untyped nil here so it gets `(nil, nil)` and the nil check in the request code works.

http://research.swtch.com/interfaces

**Comment by caesarxuchao** [comment]
I've done my pass. A few nits and questions.

File: pkg/kubectl/cmd/apply_test.go (hunk 2 above)
Comment (krousey) [inline pkg/kubectl/cmd/apply_test.go]: Because this now implements a [`http.RoundTripper`](https://golang.org/pkg/net/http/#RoundTripper) interface. The documentation states that you can't return both a response and an error. This was causing a test failure.

Also, the documentation for [`http.Response`](https://golang.org/pkg/net/http/#Response) guarantees that the body is non-nil. This was causing a panic because our client relies on this being non-nil.

File: pkg/client/unversioned/restclient.go (hunk 1 above)
Comment (caesarxuchao) [inline pkg/client/unversioned/restclient.go]: I see. Thank you for the detailed explanation.

Comment (krousey) [inline pkg/client/unversioned/restclient.go]: More info on how this usually bites people: https://golang.org/doc/faq#nil_error

File: pkg/kubectl/cmd/apply_test.go (hunk 2 above)
Comment (caesarxuchao) [inline pkg/kubectl/cmd/apply_test.go]: Ok. Just to confirm my understanding, the response returned by the APIServer will encode the error in the Body, so this problem won't occur, right?

Comment (krousey) [inline pkg/kubectl/cmd/apply_test.go]: Yea. If we wanted to simulate that here, we would populate Body with what APIServer would normally encode.

**Comment by caesarxuchao** [comment]
Thank you @krousey. LGTM.
