### PR TITLE
Do not leak files on iptables unit tests

### LINKED ISSUE #98947: unit tests leaving behind xtables.lock
**What happened**:

files like:
```
pkg/util/iptables/xtables-103516112.lock
pkg/util/iptables/xtables-103657263.lock
pkg/util/iptables/xtables-104036897.lock
```

are being created, I think from the "unit" tests.

**What you expected to happen**:

running tests should not leave files in tree, especially not tracked by git!

**How to reproduce it (as minimally and precisely as possible)**:

`make test`? I think?

**Anything else we need to know?**:

spotted in a PR commit https://github.com/kubernetes/kubernetes/pull/98946

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig network
/assign

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

If the iptables runner doesn't know if iptables restore supports the --wait flag, it creates a file mimicing the iptables behaviour, that uses this file to implement locking.

**Which issue(s) this PR fixes**:
Fixes #98947

-->
```release-note
NONE
```

### CODE REVIEW

File: pkg/util/iptables/iptables_test.go [hunk 1]
```diff
@@ -1049,6 +1049,8 @@ func TestRestoreAllWaitOldIptablesRestore(t *testing.T) {
 	if err == nil {
 		t.Errorf("expected failure")
 	}
+	// restore creates a file to mimic iptables lock if the runner restoreWaitFlag == 0
+	os.Remove(lockPath16x)
```
Comment (BenTheElder) [inline pkg/util/iptables/iptables_test.go:1053]: this should probably be in a defer?

**Comment by BenTheElder** [comment]
thanks, squash?

File: pkg/util/iptables/iptables_test.go (hunk 1 above)
Comment (aojea) [reply pkg/util/iptables/iptables_test.go:1053]: this is the last instruction :upside_down_face:

Comment (danwinship) [reply pkg/util/iptables/iptables_test.go:1053]: > this is the last instruction

yeah but it shouldn't be; if the `err == nil` case above gets hit then we wouldn't remove the file

likewise below

**Review by danwinship — CHANGES_REQUESTED** [review]

File: pkg/util/iptables/iptables_test.go (hunk 1 above)
Comment (BenTheElder) [reply pkg/util/iptables/iptables_test.go:1053]: Cleanup should nearly always be in a defer close to creating the resource because if anything panics in-between it will still run

Comment (thockin) [reply pkg/util/iptables/iptables_test.go:1053]: why only delete 16 and not 14 ?

Comment (aojea) [reply pkg/util/iptables/iptables_test.go:1053]: the problem is here https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/pkg/util/iptables/iptables_linux.go#L68-L85

the file for 16 is never removed once the test ends, 14 is a socket, so I assume that the test closes it indirectly when it ends

File: pkg/util/iptables/iptables_test.go [hunk 2]
```diff
@@ -1046,6 +1046,8 @@ func TestRestoreAllWaitOldIptablesRestore(t *testing.T) {
 
 	// Failure.
 	err = runner.Restore(TableNAT, []byte{}, FlushTables, RestoreCounters)
+	// restore creates a file to mimic iptables lock if the runner restoreWaitFlag == 0
+	defer os.Remove(lockPath16x)
```
Comment (thockin) [inline pkg/util/iptables/iptables_test.go:1050]: This should go at line 1029 - before `runner` is ever used.  Probably warrants a comment along the lines of:

```
// the lockPath14x is a UNIX socket which is cleaned up automatically on close, but the
// lockPath16x is a plain file which is not cleaned up.
```

File: pkg/util/iptables/iptables_test.go [hunk 3]
```diff
@@ -1133,6 +1138,8 @@ func TestRestoreAllGrabOldLock(t *testing.T) {
 	defer runLock.Close()
 
 	err = runner.RestoreAll([]byte{}, NoFlushTables, RestoreCounters)
+	// restore creates a file to mimic iptables lock if the runner restoreWaitFlag == 0
+	defer os.Remove(lockPath16x)
```
Comment (thockin) [inline pkg/util/iptables/iptables_test.go:1142]: Same comment as above, this should be at L 1115

**Review by thockin — COMMENTED** [review]
I had to spelunk thru Go's UNIX socket impl to understand.  Thanks for that.

**Review by thockin — COMMENTED** [review]
Thanks!

/lgtm
/approve

**Comment by aojea** [comment]
/retest
this is starting to flake again a lot

```
  test/e2e/network/endpointslice.go:167
Feb 11 07:33:10.356: FAIL: timed out waiting for Pods to have IPs assigned
Unexpected error:
    <*errors.errorString | 0xc0001f61d0>: {
        s: "timed out waiting for the condition",
    }
```

```
Feb 11 07:36:54.020: INFO: ExecWithOptions {Command:[/bin/sh -c curl -g --connect-timeout 5 http://172.18.0.2:54321/hostname] Namespace:hostport-1007 PodName:e2e-host-exec ContainerName:e2e-host-exec Stdin:<nil> CaptureStdout:true CaptureStderr:true PreserveWhitespace:false Quiet:false}
Feb 11 07:36:54.020: INFO: >>> kubeConfig: /root/.kube/kind-test-config
Feb 11 07:36:59.107: INFO: Can not connect from e2e-host-exec to pod(pod2) to serverIP: 172.18.0.2, port: 54321
Feb 11 07:36:59.107: FAIL: Failed to connect to exposed host ports

Full Stack Trace
```
