### PR TITLE
call unreserve plugin before record event

### LINKED ISSUE #79611: TestUnreservePlugin is flaky, again
**What happened**:
TestUnreservePlugin is flaky: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/79109/pull-kubernetes-integration/1145723758279921668/

**What you expected to happen**:
Test to always pass.

**How to reproduce it (as minimally and precisely as possible)**:
This is a flaky test, but the issue is that the unreserve plugin didn't get the change to execute before the test checked the unreserve call counter in the test. Assuming thread1 runs the scheduler, thread2 runs the tests, here is the sequence that caused this flake:

* thread2 creates a pod and blocks on a [scheduling error](https://github.com/kubernetes/kubernetes/blob/de8fb1c9f81b1bd48a0d25f866492acca2c199f0/test/integration/scheduler/framework_test.go#L589).
* thread1 tries to schedule the pod, executing the pre-bind plugin which denies the pod and [records a scheduling error](https://github.com/kubernetes/kubernetes/blob/de8fb1c9f81b1bd48a0d25f866492acca2c199f0/pkg/scheduler/scheduler.go#L574).
* thread2 gets unblocked before thread1 gets to [run unreserve plugins](https://github.com/kubernetes/kubernetes/blob/de8fb1c9f81b1bd48a0d25f866492acca2c199f0/pkg/scheduler/scheduler.go#L576). Thread2 checks the counters, throwing an error since unreserve plugin call counter didn't get to be incremented.

What we need is for the test to block until unreserve is called, not until we get a scheduling error.

/sig scheduling

### PR DESCRIPTION
**Pull request by danielqsj**
**What type of PR is this?**

/kind bug
/sig scheduling

**What this PR does / why we need it**:

Defer the record events is harmless and can make test case passed.

**Which issue(s) this PR fixes**:

Fixes #79611

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -552,7 +552,9 @@ func (sched *Scheduler) scheduleOne() {
 			if forgetErr := sched.Cache().ForgetPod(assumedPod); forgetErr != nil {
 				klog.Errorf("scheduler cache ForgetPod failed: %v", forgetErr)
 			}
-			sched.recordSchedulingFailure(assumedPod, permitStatus.AsError(), reason, permitStatus.Message())
```
Comment (draveness) [inline pkg/scheduler/scheduler.go]: Why not place this line before `return`?

File: pkg/scheduler/scheduler.go [hunk 2]
```diff
@@ -571,7 +573,9 @@ func (sched *Scheduler) scheduleOne() {
 			if forgetErr := sched.Cache().ForgetPod(assumedPod); forgetErr != nil {
 				klog.Errorf("scheduler cache ForgetPod failed: %v", forgetErr)
 			}
-			sched.recordSchedulingFailure(assumedPod, prebindStatus.AsError(), reason, prebindStatus.Message())
```
Comment (draveness) [inline pkg/scheduler/scheduler.go]: same here

File: pkg/scheduler/scheduler.go (hunk 1 above)
Comment (wgliang) [reply pkg/scheduler/scheduler.go]: @draveness 
`defer sched.recordSchedulingFailure(assumedPod, permitStatus.AsError(), reason, permitStatus.Message())` 
not equal to
`defer func() {
sched.recordSchedulingFailure(assumedPod, permitStatus.AsError(), reason, permitStatus.Message())
			}()`

First will execute immediately `sched.recordSchedulingFailure(assumedPod, permitStatus.AsError(), reason, permitStatus.Message())`

Comment (danielqsj) [reply pkg/scheduler/scheduler.go]: @wgliang do you prefer to use defer or change the sequence of these two lines ?

Comment (draveness) [reply pkg/scheduler/scheduler.go]: > `defer func() { sched.recordSchedulingFailure(assumedPod, permitStatus.AsError(), reason, permitStatus.Message()) }()`

I know the difference, just want to ensure it is on purpose.

Comment (wgliang) [reply pkg/scheduler/scheduler.go]: > @wgliang do you prefer to use defer or change the sequence of these two lines ?

@danielqsj I'm ok with that,but I want to know if make test case passed is a coincidence?

Comment (danielqsj) [reply pkg/scheduler/scheduler.go]: I test it several times, all passed.

Comment (ahg-g) [reply pkg/scheduler/scheduler.go]: I prefer to just call recordSchedulingFailure at the end before the return rather than doing the defer to simplify the code.

**Review by draveness — CHANGES_REQUESTED** [review]
/priority important-soon

Please address the comments and we are good to go.

**Comment by danielqsj** [comment]
@draveness @ahg-g @wgliang @bsalamat updated, PTAL

**Review by draveness — APPROVED** [review]
/lgtm

Thanks @danielqsj

**Review by bsalamat — COMMENTED** [review]
/lgtm
/approve

Thanks, @danielqsj!
