### PR TITLE
bugfix(hpa): introduce buildQuantity helper for consistent resource quantity

### LINKED ISSUE #130584: Incorrect m Suffix in Memory Values for kubectl get hpa
### What happened?

kubectl get hpa incorrectly appends m (millicores) to memory usage values. Memory should always be displayed in bytes, MiB, or GiB, never in "millibytes (m)". This issue also exists in the autoscaling/v2 API, suggesting a deeper problem beyond kubectl

 Affected Versions
Kubernetes Version: v1.29+
kubectl Version: v1.29+
Metrics Server: latest stable
Environment: Affects both on-prem and cloud-managed Kubernetes (e.g., AKS, EKS, GKE).

Deploy an HPA that scales based on memory usage:

yaml

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 325Mi
Apply the configuration:

sh

kubectl apply -f test-hpa.yaml
Check HPA details:

sh

kubectl get hpa test-hpa -n default
Observed Output:

bash

NAME      REFERENCE        TARGETS      MINPODS   MAXPODS   REPLICAS   AGE
test-hpa  Deployment/test  171502796800m/325Mi   1         10        2          10m
Problem: The value 171502796800m should not have m, as memory is measured in bytes.

Fetch raw API data:

kubectl get --raw "/apis/autoscaling/v2/namespaces/default/horizontalpodautoscalers/test-hpa" | jq
API Output (Incorrect format):

json
{
  "status": {
    "currentMetrics": [
      {
        "type": "Resource",
        "resource": {
          "name": "memory",
          "current": {
            "averageValue": "**172043468800m**"
          }
        }
      }
    ]
  }
}
🚨 Incorrect: The API also appends m, suggesting the issue is deeper than kubectl.

### What did you expect to happen?

Expected Behavior **Actual Behavior ( kubectl get hpa )
Memory should be displayed in MiB, GiB, or raw
bytes
Memory is displayed with an incorrect m suffix
Example: 171502796800 bytes = 163,599 MiB Shown incorrectly as 171502796800m
Consistent with Kubernetes documentation Misleading as "millibytes" (which is not a Kubernetes
unit)

### How can we reproduce it (as minimally and precisely as possible)?

refer

### Anything else we need to know?

_No response_

### Kubernetes version

 kubectl version
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.29.10
WARNING: version difference between client (1.31) and server (1.29) exceeds the supported minor version skew of +/-1

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by googs1025**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

This PR introduces a new helper function, buildQuantity in the HPA controller.

Previously, quantities were created inline using NewMilliQuantity directly, which made it harder to:
- Ensure consistency between CPU and memory handling

Now, all resource quantity creation goes through buildQuantity:
- For memory: raw bytes are converted to KiB and use BinarySI
- For CPU or other resources: milli-units are used with DecimalSI

#### Which issue(s) this PR is related to: 

Fix: https://github.com/kubernetes/kubernetes/issues/130584

#### Does this PR introduce a user-facing change?

```release-note
HPA status now displays memory metrics using Ki
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by googs1025** [comment]
before change: 
```bash
➜  ~ kubectl get hpa
NAME       REFERENCE                    TARGETS                              MINPODS   MAXPODS   REPLICAS   AGE
test-hpa   Deployment/test-deployment   cpu: 25%/50%, memory: 71421952/1Gi   1         10        1          4h
➜  ~ kubectl get hpa -oyaml
apiVersion: v1
items:
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"test-hpa","namespace":"default"},"spec":{"maxReplicas":10,"metrics":[{"resource":{"name":"cpu","target":{"averageUtilization":50,"type":"Utilization"}},"type":"Resource"},{"resource":{"name":"memory","target":{"averageValue":"1Gi","type":"AverageValue"}},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"test-deployment"}}}
    creationTimestamp: "2025-06-17T07:16:03Z"
    name: test-hpa
    namespace: default
    resourceVersion: "3841389"
    uid: b8b9a7d2-32e2-4b29-861c-7a489ecc5c5f
  spec:
    maxReplicas: 10
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
    - resource:
        name: memory
        target:
          averageValue: 1Gi
          type: AverageValue
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: test-deployment
  status:
    conditions:
    - lastTransitionTime: "2025-06-17T10:55:21Z"
      message: recommended size matches current size
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2025-06-17T11:06:24Z"
      message: the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: "2025-06-17T07:16:33Z"
      message: the desired count is within the acceptable range
      reason: DesiredWithinRange
      status: "False"
      type: ScalingLimited
    currentMetrics:
    - resource:
        current:
          averageUtilization: 25
          averageValue: 38m
        name: cpu
      type: Resource
    - resource:
        current:
          averageValue: "71421952"
        name: memory
      type: Resource
    currentReplicas: 1
    desiredReplicas: 1
    lastScaleTime: "2025-06-17T10:11:17Z"
kind: List
metadata:
  resourceVersion: ""

```

after changed: 

```bash
➜  ~ kubectl get hpa
NAME       REFERENCE                    TARGETS                              MINPODS   MAXPODS   REPLICAS   AGE
test-hpa   Deployment/test-deployment   cpu: 36%/50%, memory: 108236Ki/1Gi   1         10        1          4h2m
➜  ~ kubectl get hpa -oyaml
apiVersion: v1
items:
- apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"test-hpa","namespace":"default"},"spec":{"maxReplicas":10,"metrics":[{"resource":{"name":"cpu","target":{"averageUtilization":50,"type":"Utilization"}},"type":"Resource"},{"resource":{"name":"memory","target":{"averageValue":"1Gi","type":"AverageValue"}},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"test-deployment"}}}
    creationTimestamp: "2025-06-17T07:16:03Z"
    name: test-hpa
    namespace: default
    resourceVersion: "3841487"
    uid: b8b9a7d2-32e2-4b29-861c-7a489ecc5c5f
  spec:
    maxReplicas: 10
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
    - resource:
        name: memory
        target:
          averageValue: 1Gi
          type: AverageValue
      type: Resource
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: test-deployment
  status:
    conditions:
    - lastTransitionTime: "2025-06-17T10:55:21Z"
      message: recommended size matches current size
      reason: ReadyForNewScale
      status: "True"
      type: AbleToScale
    - lastTransitionTime: "2025-06-17T11:06:24Z"
      message: the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
      reason: ValidMetricFound
      status: "True"
      type: ScalingActive
    - lastTransitionTime: "2025-06-17T07:16:33Z"
      message: the desired count is within the acceptable range
      reason: DesiredWithinRange
      status: "False"
      type: ScalingLimited
    currentMetrics:
    - resource:
        current:
          averageUtilization: 36
          averageValue: 55m
        name: cpu
      type: Resource
    - resource:
        current:
          averageValue: 108236Ki
        name: memory
      type: Resource
    currentReplicas: 1
    desiredReplicas: 1
    lastScaleTime: "2025-06-17T10:11:17Z"
kind: List
metadata:
  resourceVersion: ""
```

File: pkg/controller/podautoscaler/horizontal_test.go [hunk 1]
```diff
@@ -5451,3 +5451,67 @@ func TestHPARescaleWithSuccessfulConflictRetry(t *testing.T) {
...
 }
+
+func TestBuildQuantity(t *testing.T) {
+	tests := []struct {
+		name         string
+		resourceName v1.ResourceName
+		rawProposal  int64
+		expected     resource.Quantity
+	}{
+		// --- Memory Tests ---
```
Comment (omerap12) [inline pkg/controller/podautoscaler/horizontal_test.go]: nit: this might be a bit redundant since the test name already makes it pretty clear what we're checking.

File: pkg/controller/podautoscaler/horizontal_test.go [hunk 2]
```diff
@@ -5451,3 +5451,67 @@ func TestHPARescaleWithSuccessfulConflictRetry(t *testing.T) {
...
+			rawProposal:  1000,
+			expected:     *resource.NewQuantity(1, resource.BinarySI), // 1Ki
+		},
+		{
+			name:         "Memory - 1000000 bytes → 1000Ki",
+			resourceName: v1.ResourceMemory,
+			rawProposal:  1000000,
+			expected:     *resource.NewQuantity(1000, resource.BinarySI), // 1000Ki
+		},
+		// --- CPU Tests ---
```
Comment (omerap12) [inline pkg/controller/podautoscaler/horizontal_test.go]: Same as above.

File: pkg/controller/podautoscaler/horizontal_test.go [hunk 3]
```diff
@@ -5451,3 +5451,67 @@ func TestHPARescaleWithSuccessfulConflictRetry(t *testing.T) {
...
+			rawProposal:  500,
+			expected:     *resource.NewMilliQuantity(500, resource.DecimalSI),
+		},
+		{
+			name:         "CPU - 1 milli-core",
+			resourceName: v1.ResourceCPU,
+			rawProposal:  1,
+			expected:     *resource.NewMilliQuantity(1, resource.DecimalSI),
+		},
+		// --- Custom Resource Tests ---
```
Comment (omerap12) [inline pkg/controller/podautoscaler/horizontal_test.go]: Same as above.

File: pkg/controller/podautoscaler/horizontal.go [hunk 4]
```diff
@@ -627,13 +628,28 @@ func (a *HorizontalController) computeStatusForResourceMetricGeneric(ctx context
...
 }
 
+// buildQuantity creates a resource.Quantity for HPA metrics based on the resource type.
+//
+// For memory, it converts bytes to KiB (by dividing by 1000) and uses BinarySI for display (Ki/Mi/Gi).
+// For CPU or other resources, it treats rawProposal as milli-units and uses DecimalSI (m).
+func buildQuantity(resourceName v1.ResourceName, rawProposal int64) resource.Quantity {
+	if resourceName == v1.ResourceMemory {
+		// Convert bytes to KiB
+		kib := rawProposal / 1000
```
Comment (omerap12) [inline pkg/controller/podautoscaler/horizontal.go]: I think this should be divided by 1024, not 1000

Comment (googs1025) [reply pkg/controller/podautoscaler/horizontal.go]: This is a very interesting question. 🤔  I looked at it for some time and found that the metrics are all obtained using the `MilliValue()`, so 1000 is not 1024 (binary). In addition, after debugging locally, I used /1000 and it was also the correct value.

https://github.com/kubernetes/kubernetes/blob/ced19ffab59fdc346318d1d0152581a1f213c711/pkg/controller/podautoscaler/horizontal.go#L602-L613

https://github.com/kubernetes/kubernetes/blob/ced19ffab59fdc346318d1d0152581a1f213c711/pkg/controller/podautoscaler/metrics/client.go#L110-L131


```bash
➜  ~ kubectl get PodMetrics
NAME                               CPU         MEMORY    WINDOW
test-deployment-6d56d679c5-4zmtl   28395987n   69600Ki   15.023s
```

```bash
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"test-hpa","namespace":"default"},"spec":{"maxReplicas":10,"metrics":[{"resource":{"name":"cpu","target":{"averageUtilization":50,"type":"Utilization"}},"type":"Resource"},{"resource":{"name":"memory","target":{"averageUtilization":50,"type":"Utilization"}},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"test-deployment"}}}
  creationTimestamp: "2025-06-17T14:45:26Z"
  name: test-hpa
  namespace: default
  resourceVersion: "3849312"
  uid: d3cd047c-54af-40fd-af10-2cc15011658e
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-deployment
status:
  conditions:
  - lastTransitionTime: "2025-06-17T14:46:37Z"
    message: the HPA controller was able to update the target scale to 3
    reason: SucceededRescale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2025-06-17T15:07:38Z"
    message: the HPA was able to successfully calculate a replica count from memory
      resource utilization (percentage of request)
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2025-06-17T14:46:52Z"
    message: the desired count is within the acceptable range
    reason: DesiredWithinRange
    status: "False"
    type: ScalingLimited
  currentMetrics:
  - resource:
      current:
        averageUtilization: 19
        averageValue: 29m
      name: cpu
    type: Resource
  - resource:
      current:
        averageUtilization: 106
        averageValue: 69600Ki
      name: memory
    type: Resource
  currentReplicas: 1
  desiredReplicas: 3
  lastScaleTime: "2025-06-17T15:07:38Z"
```

File: pkg/controller/podautoscaler/horizontal_test.go (hunk 1 above)
Comment (googs1025) [reply pkg/controller/podautoscaler/horizontal_test.go]: done

File: pkg/controller/podautoscaler/horizontal_test.go (hunk 2 above)
Comment (googs1025) [reply pkg/controller/podautoscaler/horizontal_test.go]: done

File: pkg/controller/podautoscaler/horizontal_test.go (hunk 3 above)
Comment (googs1025) [reply pkg/controller/podautoscaler/horizontal_test.go]: done

File: pkg/controller/podautoscaler/horizontal.go (hunk 4 above)
Comment (omerap12) [reply pkg/controller/podautoscaler/horizontal.go]: Thanks for the explanation. Yeah I think you are right :)

**Review by hashim21223445 — APPROVED** [review]

File: pkg/controller/podautoscaler/horizontal.go (hunk 4 above)
Comment (soltysh) [reply pkg/controller/podautoscaler/horizontal.go]: If the returned value from metrics client is `MiliValue()` the above example by @googs1025 clearly points to that, I don't think that dividing by 1000 is necessary here. You should just invoke `resource.NewMilliQuantity...` just like it was done previously. 

The one change I do agree with is the differentiation between memory (being `BinarySI`) and cpu (being `DecimalSI`) which matches what the metrics server returns here https://github.com/kubernetes-sigs/metrics-server/blob/55b4961bc1eceffd0a37809dc271e9ae38de9deb/pkg/storage/types.go#L63-L64.

Iow. I believe this method should look like this:
```golang
func buildQuantity(resourceName v1.ResourceName, rawProposal int64) resource.Quantity {
    format := resource.DecimalSI
	// to match what we return in the metrics server, see https://github.com/kubernetes-sigs/metrics-server/blob/55b4961bc1eceffd0a37809dc271e9ae38de9deb/pkg/storage/types.go#L63-L64
	if resourceName == v1.ResourceMemory {
		format = resource.BinarySI
	}
	return *resource.NewMilliQuantity(rawProposal, format)
}
```

File: pkg/controller/podautoscaler/horizontal_test.go [hunk 5]
```diff
@@ -5451,3 +5451,64 @@ func TestHPARescaleWithSuccessfulConflictRetry(t *testing.T) {
...
+	}
+
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			q := buildQuantity(tt.resourceName, tt.rawProposal)
+			if !q.Equal(tt.expected) {
+				t.Errorf("expected quantity %v, got %v", tt.expected.String(), q.String())
+			}
+		})
+	}
```
Comment (soltysh) [inline pkg/controller/podautoscaler/horizontal_test.go:5515]: This test isn't sufficient, since it passes with and without your change.

**Review by soltysh — CHANGES_REQUESTED** [review]

File: pkg/controller/podautoscaler/horizontal.go (hunk 4 above)
Comment (googs1025) [reply pkg/controller/podautoscaler/horizontal.go]: Thank you for the explanation. I test it locally and it will return correctly. 😄

File: pkg/controller/podautoscaler/horizontal_test.go (hunk 5 above)
Comment (googs1025) [reply pkg/controller/podautoscaler/horizontal_test.go:5515]: Modify it as follows:
```go
if !q.Equal(tt.expected) || (q.Format != tt.expected.Format) {
  t.Errorf("expected quantity %v (Format: %v), got %v (Format: %v)",
	  tt.expected.String(), tt.expected.Format,
	  q.String(), q.Format)
}
```

But I'm not sure if there are other ways to test 🤔

Comment (soltysh) [reply pkg/controller/podautoscaler/horizontal_test.go:5515]: Yup, this is better now.

**Review by soltysh — APPROVED** [review]
/approve

@omerap12 has the final tag

**Review by omerap12 — APPROVED** [review]
Thanks!
/lgtm
