### PR TITLE
kubelet: Remove false PLEG errors

### LINKED ISSUE #106265: Kubelet logging PLEG: Write status error when no errors have occured
### Which jobs are failing?

I install kubernetes 1.22.2
calico 3.20.2
centos 8.4
kernel 4.18

when I create some pod,and sawed that kubelet status had some error
```
Nov 09 21:31:25 sit-kubernetes-master-srv1 kubelet[112447]: E1109 21:31:25.927561  112447 kubelet/kubelet.go:1343] "Image garbage collection failed once. Stats initialization may not have completed yet" err="failed to get imageFs info: unable to find data in memory cache"
Nov 09 21:31:26 sit-kubernetes-master-srv1 kubelet[112447]: E1109 21:31:26.170721  112447 kubelet/kubelet.go:1991] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
Nov 09 21:31:26 sit-kubernetes-master-srv1 kubelet[112447]: E1109 21:31:26.226034  112447 pleg/generic.go:409] "PLEG: Write status" pod="kube-system/calico-node-kckfc" podStatus=&{ID:b03a3815-2fe5-41ac-8fa5-87917719ec78 Name:calico-node-kckfc Namespace:kube-system IPs:[] ContainerStatuses:[0xc00004ec40 0xc000d4e1c0 0xc000cd4460] SandboxStatuses:[&PodSandboxStatus{Id:1a61728396164c8f380eeffb86898352643c92f031deb4f640a7374ba9acb4ad,Metadata:&PodSandboxMetadata{Name:calico-node-kckfc,Uid:b03a3815-2fe5-41ac-8fa5-87917719ec78,Namespace:kube-system,Attempt:0,},State:SANDBOX_READY,CreatedAt:1636455144299450919,Network:&PodSandboxNetworkStatus{Ip:,AdditionalIps:[]*PodIP{},},Linux:&LinuxPodSandboxStatus{Namespaces:&Namespace{Options:&NamespaceOption{Network:NODE,Pid:CONTAINER,Ipc:POD,TargetId:,},},},Labels:map[string]string{controller-revision-hash: 69dfc55c65,io.kubernetes.pod.name: calico-node-kckfc,io.kubernetes.pod.namespace: kube-system,io.kubernetes.pod.uid: b03a3815-2fe5-41ac-8fa5-87917719ec78,k8s-app: calico-node,pod-template-generation: 1,},Annotations:map[string]string{kubernetes.io/config.seen: 2021-11-09T18:52:23.384861674+08:00,kubernetes.io/config.source: api,},RuntimeHandler:,}]}
Nov 09 21:31:26 sit-kubernetes-master-srv1 kubelet[112447]: E1109 21:31:26.234201  112447 pleg/generic.go:409] "PLEG: Write status" pod="kube-system/calico-kube-controllers-87d5f7dd7-x9pn4" podStatus=&{ID:72ada86f-a07c-48ab-b044-7a234cc69f9e Name:calico-kube-controllers-87d5f7dd7-x9pn4 Namespace:kube-system IPs:[] ContainerStatuses:[0xc00004e460] SandboxStatuses:[&PodSandboxStatus{Id:298cb28c22c6521f4757f0492e0a37b559bca6f761dcc509a8322f53f62a455e,Metadata:&PodSandboxMetadata{Name:calico-kube-controllers-87d5f7dd7-x9pn4,Uid:72ada86f-a07c-48ab-b044-7a234cc69f9e,Namespace:kube-system,Attempt:0,},State:SANDBOX_READY,CreatedAt:1636455310494553432,Network:&PodSandboxNetworkStatus{Ip:,AdditionalIps:[]*PodIP{},},Linux:&LinuxPodSandboxStatus{Namespaces:&Namespace{Options:&NamespaceOption{Network:NODE,Pid:CONTAINER,Ipc:POD,TargetId:,},},},Labels:map[string]string{io.kubernetes.pod.name: calico-kube-controllers-87d5f7dd7-x9pn4,io.kubernetes.pod.namespace: kube-system,io.kubernetes.pod.uid: 72ada86f-a07c-48ab-b044-7a234cc69f9e,k8s-app: calico-kube-controllers,pod-template-hash: 87d5f7dd7,},Annotations:map[string]string{kubernetes.io/config.seen: 2021-11-09T18:55:10.184562382+08:00,kubernetes.io/config.source: api,},RuntimeHandler:,}]}
```

my node and pod are all running
```
# kubectl get node
NAME     STATUS   ROLES    AGE     VERSION
ingress1  Ready    <none>   6h18m   v1.22.2
master1   Ready    <none>   8h        v1.22.2
node1      Ready    <none>   6h8m    v1.22.2
node2      Ready    <none>   6h1m    v1.22.2
node3      Ready    <none>   5h54m   v1.22.2

# kubectl get po -n kube-system
NAME                                      READY   STATUS    RESTARTS   AGE
calico-kube-controllers-87d5f7dd7-x9pn4   1/1     Running   0          3h9m
calico-node-bmqt4                         1/1     Running   0          3h9m
calico-node-gfjbn                         1/1     Running   0          3h9m
calico-node-j4bcj                         1/1     Running   0          3h9m
calico-node-kckfc                         1/1     Running   0          3h9m
calico-node-pkq4s                         1/1     Running   0          3h9m
coredns-75d4d9cf4-68rmm                   1/1     Running   0          3h1m
coredns-75d4d9cf4-lb8f4                   1/1     Running   0          3h1m
coredns-75d4d9cf4-wvzjf                   1/1     Running   0          3h1m

```

Is this a bug of 1.22.2 ？Can any one help me to resolv this problem,thanks!

### Which tests are failing?

kubelet had PLEG Write status error

### Since when has it been failing?

I installed the service in 3 hours

### Testgrid link

_No response_

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig

### PR DESCRIPTION
**Pull request by gjkim42**
#### What type of PR is this?

/kind cleanup
/kind regression

#### What this PR does / why we need it:

kubelet has generated error logs always when it calls `(*GenericPLEG).UpdateCache`.
This PR removes false error messages from kubelet logs so that users don't confuse about kubelet's health.

The log level of the messages converted to `Error` from `Info` after https://github.com/kubernetes/kubernetes/pull/98990.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/106265

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/release-note-none

### CODE REVIEW

**Comment by gjkim42** [comment]
/sig node
/cc @pacoxu @serathius @SergeyKanzhelev 

Could you PTAL?

**Review by ehashman — COMMENTED** [review]
/triage accepted
/lgtm

Great catch!

**Comment by gjkim42** [comment]
/assign @mrunalp 
Could you PTAL?
Thanks :)

**Review by 249043822 — APPROVED** [review]
/lgtm

File: pkg/kubelet/pleg/generic.go [hunk 1]
```diff
@@ -405,12 +405,18 @@ func (g *GenericPLEG) updateCache(pod *kubecontainer.Pod, pid types.UID) error {
 	// GetPodStatus(pod *kubecontainer.Pod) so that Docker can avoid listing
 	// all containers again.
 	status, err := g.runtime.GetPodStatus(pod.ID, pod.Name, pod.Namespace)
-	if klog.V(6).Enabled() {
-		klog.V(6).ErrorS(err, "PLEG: Write status", "pod", klog.KRef(pod.Namespace, pod.Name), "podStatus", status)
+	if err != nil {
+		if klog.V(6).Enabled() {
+			klog.V(6).ErrorS(err, "PLEG: Write status", "pod", klog.KRef(pod.Namespace, pod.Name), "podStatus", status)
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/pleg/generic.go:410]: not related to this PR, I wonder if this file needs to clean up how it logs the pod. Sometimes it's a `podUID`, sometimes `podID`, sometimes `Name` and `Namespace` combination.

Comment (gjkim42) [reply pkg/kubelet/pleg/generic.go:410]: Yes, the logs look somewhat inconsistent.

`klog.InfoS("SOME LOGS", "pod", klog.KObj(pod), "podUID", pod.UID)` looks good to me.

Comment (SergeyKanzhelev) [reply pkg/kubelet/pleg/generic.go:410]: will `klog.KObj(pod)` work? This is different pod type. I'm just not sure how KObj works.

Comment (pacoxu) [reply pkg/kubelet/pleg/generic.go:410]: > not related to this PR, I wonder if this file needs to clean up how it logs the pod. Sometimes it's a `podUID`, sometimes `podID`, sometimes `Name` and `Namespace` combination.

Align kubelet log for podID and Namespace.

**Comment by pacoxu** [comment]
/assign @mrunalp
for approval

**Comment by dims** [comment]
/assign @klueska 

@klueska @mrunalp this is ready for approval

**Review by mrunalp — APPROVED** [review]
