### PR TITLE
Get containerID from systemd-style cgroupPath in cri_stats_provider

### LINKED ISSUE #103366: No memory metrics from kubelet stats endpoint
#### What happened:
Since upgrading from Kubernetes `1.19.8` to `1.20.8` we no longer get memory metrics from the `/stats/summary` endpoint on `kubelet`.

Example:
```json
"memory": {
    "time": "2021-06-30T15:12:35Z",
    "availableBytes": 1073741824,
    "usageBytes": 0,
    "workingSetBytes": 0,
    "rssBytes": 0,
    "pageFaults": 0,
    "majorPageFaults": 0
}
```

#### What you expected to happen:
In our previous version, `1.19.8` we would get a response like the following that included utilisation metrics:

```json
"memory": {
    "time": "2021-06-30T14:18:35Z",
    "usageBytes": 45252608,
    "workingSetBytes": 35295232,
    "rssBytes": 32563200,
    "pageFaults": 1722682401,
    "majorPageFaults": 0
}
```

#### How to reproduce it (as minimally and precisely as possible):
Hit the `/stats/summary` endpoint of `kubelet` on a cluster running version `1.20.8`.

#### Environment:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: Provisioned on AWS with `kops`
- OS (e.g: `cat /etc/os-release`): Flatcar Container Linux by Kinvolk 2765.2.6 (Oklo)
- Kernel (e.g. `uname -a`): 5.10.43-flatcar

### PR DESCRIPTION
**Pull request by YanzhaoLi**
Because cgroupPath format isn't "xx/containerdID" when using systemd cgroup driver

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When using different cgroup drivers, the cgroupPath format are different. So the `cri_stats_provider` should handle all these cases of cgroupPath to extract containerID.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/103366

#### Does this PR introduce a user-facing change?

```release-note
Fix regression in 1.21 where memory metrics can be missing from kubelet stats
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/stats/cri_stats_provider.go [hunk 1]
```diff
@@ -826,7 +825,15 @@ func getCRICadvisorStats(infos map[string]cadvisorapiv2.ContainerInfo) map[strin
 		if !isPodManagedContainer(&info) {
 			continue
 		}
-		stats[path.Base(key)] = info
+		if len(info.Spec.Aliases) > 0 {
```
Comment (bobbypage) [inline pkg/kubelet/stats/cri_stats_provider.go:828]: I wonder maybe instead we need a special check for systemd cgroup driver like here instead:

https://github.com/kubernetes/kubernetes/blob/5be21c50c269fc1d28e0bd31ab9dcb572ae7fac5/pkg/kubelet/stats/cadvisor_stats_provider.go#L307-L314

It would be nice if can avoid using `info.Spec.Aliases` since as you mentioned behavior of containerd/crio/docker are different.

Comment (YanzhaoLi) [reply pkg/kubelet/stats/cri_stats_provider.go:828]: Really cool. Thanks @bobbypage . 
And since there're two kind of format of cgroupPath for systemd cgroup driver. I'll test with this kind of special check.

Comment (YanzhaoLi) [reply pkg/kubelet/stats/cri_stats_provider.go]: Hi @bobbypage , I just changed to code to extract id from systemd-style cgroup path. Please help review again.

File: pkg/kubelet/stats/cri_stats_provider.go [hunk 2]
```diff
@@ -826,7 +826,29 @@ func getCRICadvisorStats(infos map[string]cadvisorapiv2.ContainerInfo) map[strin
 		if !isPodManagedContainer(&info) {
 			continue
 		}
-		stats[path.Base(key)] = info
+		stats[extractIDFromCgroupPath(key)] = info
 	}
 	return stats
 }
+
+func extractIDFromCgroupPath(cp string) string {
```
Comment (ehashman) [inline pkg/kubelet/stats/cri_stats_provider.go:834]: Any reason not to use the full name here?

```suggestion
func extractIDFromCgroupPath(cgroupPath string) string {
```

**Review by ehashman — COMMENTED** [review]
/assign @bobbypage 
/priority important-soon
/triage accepted

/release-note-none

File: pkg/kubelet/stats/cri_stats_provider.go (hunk 2 above)
Comment (YanzhaoLi) [reply pkg/kubelet/stats/cri_stats_provider.go]: @ehashman  Changed as suggested.  And also fix test to generate containerdID by UUID without dash

File: pkg/kubelet/stats/cri_stats_provider.go [hunk 3]
```diff
@@ -826,7 +826,29 @@ func getCRICadvisorStats(infos map[string]cadvisorapiv2.ContainerInfo) map[strin
...
+		stats[extractIDFromCgroupPath(key)] = info
 	}
 	return stats
 }
+
+func extractIDFromCgroupPath(cgroupPath string) string {
+	//case0: /kubepods/burstable/pod2fc932ce-fdcc-454b-97bd-aadfdeb4c340/9be25294016e2dc0340dd605ce1f57b492039b267a6a618a7ad2a7a58a740f32
+	id := path.Base(cgroupPath)
+
+	//case1: "/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2fc932ce_fdcc_454b_97bd_aadfdeb4c340.slice/cri-containerd-aaefb9d8feed2d453b543f6d928cede7a4dbefa6a0ae7c9b990dd234c56e93b9.scope"
```
Comment (bobbypage) [inline pkg/kubelet/stats/cri_stats_provider.go:838]: I don't think this format is supported (it looks like mix between systemd and cgroupfs name) as you mentioned in https://github.com/kubernetes/kubernetes/issues/103366#issuecomment-889286696

cgroup driver between kubelet and container runtime should match, so I don't think this is a valid case that should be supported.

File: pkg/kubelet/stats/cri_stats_provider.go [hunk 4]
```diff
@@ -826,7 +826,29 @@ func getCRICadvisorStats(infos map[string]cadvisorapiv2.ContainerInfo) map[strin
...
+	const scopeSuffix string = ".scope"
+	if strings.HasSuffix(id, scopeSuffix) {
+		id = strings.TrimSuffix(id, scopeSuffix)
+	}
+	components := strings.Split(id, "-")
+	if len(components) > 1 {
+		id = components[len(components)-1]
+	}
+
+	//case2: "/kubepods-burstable-pod2fc932ce_fdcc_454b_97bd_aadfdeb4c340.slice:cri-containerd:db622e6f7b16079db56fd7814031f7e8fc78b3050c24fe2fc431beeebbeb1c8e"
```
Comment (bobbypage) [inline pkg/kubelet/stats/cri_stats_provider.go:848]: I'm a bit surprised by the format here. I was under previous assumption that the cgroup name should end in ".slice" as this is what  the `IsSystemdStyleName` logic has: https://github.com/kubernetes/kubernetes/blob/5be21c50c269fc1d28e0bd31ab9dcb572ae7fac5/pkg/kubelet/cm/cgroup_manager_linux.go#L132:6

/cc @haircommander @mrunalp who have more familiarity with systemd cgroup driver

Comment (YanzhaoLi) [reply pkg/kubelet/stats/cri_stats_provider.go:848]: @bobbypage  For the `.slice` suffix,  I think `IsSystemdStyleName` might only apply to PodID instead of ContainerID.
Here's an example of piece of `allInfos`
```
        "/kubepods-besteffort-pod172f50f4_10ce_4f06_af33_3e1f0716b2a0.slice:cri-containerd:fa98e6c3491302833bd4b68c9ca866569cc40e7858d5881501e84b4dad29e3bb": *{
                Spec: (*"k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerSpec")(0xc0023c97a0),
                Stats: []*k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerStats len: 2, cap: 2, [
                        *(*"k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerStats")(0xc0024070e0),
                        *(*"k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerStats")(0xc0024071d0),
                ],}, 
        "/kubepods.slice/kubepods-burstable.slice": *{
                Spec: (*"k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerSpec")(0xc0023c99e0),
                Stats: []*k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerStats len: 2, cap: 2, [
                        *(*"k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerStats")(0xc0024072c0),
                        *(*"k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerStats")(0xc0024073b0),
                ],}, 
        "/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod172f50f4_10ce_4f06_af33_3e1f0716b2a0.slice": *{
                Spec: (*"k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerSpec")(0xc0023c9320),
                Stats: []*k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerStats len: 2, cap: 2, [
                        *(*"k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerStats")(0xc002406d20),
                        *(*"k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerStats")(0xc002406e10),
                ],}, 
```

File: pkg/kubelet/stats/cri_stats_provider.go (hunk 3 above)
Comment (YanzhaoLi) [reply pkg/kubelet/stats/cri_stats_provider.go:838]: Hi @bobbypage , actually I am not sure whether this format is due to mix use of systemd and cgroupfs since I cannot reproduce this case now.

For the pod part `/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2fc932ce_fdcc_454b_97bd_aadfdeb4c340.slice`, it looks like a systemd driver. 

But for the container part `cri-containerd-aaefb9d8feed2d453b543f6d928cede7a4dbefa6a0ae7c9b990dd234c56e93b9.scope`, I am not sure how it is generated, because in the cgroupfs case, we didn't see `cri-containerd-` prefix or  `.scope` suffix

File: pkg/kubelet/stats/cri_stats_provider.go (hunk 4 above)
Comment (haircommander) [reply pkg/kubelet/stats/cri_stats_provider.go:848]: yeah I believe IsSystemdStyleName applies to the pod scope. Underneath the pod scope are the container slices. Interestingly, case 2 is the way the kubelet specifies to the CRI for a systemd scope. I believe the path always ends up being `.slice`. I would not expect the colon separated systemd slice description to leak to the cgroup heierarchy that cadvisor reads. @YanzhaoLi did you notice this happening?

Comment (YanzhaoLi) [reply pkg/kubelet/stats/cri_stats_provider.go:848]: `I believe the path always ends up being .slice (as in case 1)`: the pod path always ends up being `.slice` while the containerd path not. (In case1, it ends up being `.scope`)

` I would not expect the colon separated systemd slice description to leak to the cgroup heierarchy that cadvisor reads`: cadvisor can read all info correctly, but when storing the infos to map, it cannot extract the real containerID from systemd-style path https://github.com/kubernetes/kubernetes/blob/d4179be6117c8a17e4c22f3bd7f8aede407df440/pkg/kubelet/stats/cri_stats_provider.go#L814

File: pkg/kubelet/stats/cri_stats_provider.go (hunk 3 above)
Comment (YanzhaoLi) [reply pkg/kubelet/stats/cri_stats_provider.go]: Hi @bobbypage, I prefer to keep that case since we're not sure whether it's not a invalid case. And as suggested by @haircommander , I changed the code not to limit to suffix `.scope` but use `.` to split the key.

File: pkg/kubelet/stats/cri_stats_provider.go [hunk 5]
```diff
@@ -826,7 +826,30 @@ func getCRICadvisorStats(infos map[string]cadvisorapiv2.ContainerInfo) map[strin
...
+		stats[extractIDFromCgroupPath(key)] = info
 	}
 	return stats
 }
+
+func extractIDFromCgroupPath(cgroupPath string) string {
+	//case0: /kubepods/burstable/pod2fc932ce-fdcc-454b-97bd-aadfdeb4c340/9be25294016e2dc0340dd605ce1f57b492039b267a6a618a7ad2a7a58a740f32
+	id := path.Base(cgroupPath)
+
+	//case1: "/kubepods-burstable-pod2fc932ce_fdcc_454b_97bd_aadfdeb4c340.slice:cri-containerd:db622e6f7b16079db56fd7814031f7e8fc78b3050c24fe2fc431beeebbeb1c8e"
```
Comment (haircommander) [inline pkg/kubelet/stats/cri_stats_provider.go:838]: I'm still not personally convinced we need this case

Comment (YanzhaoLi) [reply pkg/kubelet/stats/cri_stats_provider.go:838]: - I am sure for the case1: `"/kubepods-burstable-pod2fc932ce_fdcc_454b_97bd_aadfdeb4c340.slice:cri-containerd:db622e6f7b16079db56fd7814031f7e8fc78b3050c24fe2fc431beeebbeb1c8e"` . 
    - Just did a live bug, here's the piece of output
```
   157:         allInfos, err := getCadvisorContainerInfo(p.cadvisor)
-> 158:         if err != nil {
   159:                 return nil, fmt.Errorf("failed to fetch cadvisor stats: %v", err)
   160:         }
   161:         caInfos := getCRICadvisorStats(allInfos)
   162:
(dlv) p allInfos
map[string]k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerInfo [
        "/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod50e56a8b_4a44_48d4_a1d8_f2a088697230.slice": *{
                Spec: (*"k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerSpec")(0xc0019959e0),
                Stats: []*k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerStats len: 2, cap: 2, [
                        *(*"k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerStats")(0xc001237860),
                        *(*"k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerStats")(0xc001237950),
                ],}, 
        "/kubepods-besteffort-pod172f50f4_10ce_4f06_af33_3e1f0716b2a0.slice:cri-containerd:fa98e6c3491302833bd4b68c9ca866569cc40e7858d5881501e84b4dad29e3bb": *{
                Spec: (*"k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerSpec")(0xc00148a7e0),
                Stats: []*k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerStats len: 2, cap: 2, [
                        *(*"k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerStats")(0xc0023d4000),
                        *(*"k8s.io/kubernetes/vendor/github.com/google/cadvisor/info/v2.ContainerStats")(0xc0023d40f0),
                ],}, 
```

- But I am not sure for the case2 since I cannot reproduce it anymore. (But I did notice it when debugging)
```
/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2fc932ce_fdcc_454b_97bd_aadfdeb4c340.slice/cri-containerd-aaefb9d8feed2d453b543f6d928cede7a4dbefa6a0ae7c9b990dd234c56e93b9.scope
```

Comment (haircommander) [reply pkg/kubelet/stats/cri_stats_provider.go:838]: well, you convinced me :smile:

Comment (bobbypage) [reply pkg/kubelet/stats/cri_stats_provider.go:838]: I tried to repro and print out `allInfos` in my environment and I'm getting examples of case2 (i.e. `/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podcd388b79_4555_4c44_8a68_f67b00538b93.slice/cri-containerd-6c0ab3f65ff9f6c4641efc26ea2ba5c6ffac7d1de684a6251bcd901c5eb6aa12.scope`) etc

Here is full dump: https://gist.githubusercontent.com/bobbypage/a701361188b53c8f34a7bcfdbdf71908/raw/ceba53a77820a948d34b908f1ff1ad2d300ea304/debug.txt

This is with both kubelet configured to use systemd cgroup driver as well as containerd configured to use systemd cgroup driver. 

I'm curious in what setup you got case1 (i.e. how is kubelet / containerd configured in terms of cgroup driver?). Is there a mismatch of driver usuage, i.e. kubelet using cgroupfs driver but containerd using systemd cgroup driver or vice versa in that case?

File: pkg/kubelet/stats/cri_stats_provider.go [hunk 6]
```diff
@@ -826,7 +826,30 @@ func getCRICadvisorStats(infos map[string]cadvisorapiv2.ContainerInfo) map[strin
...
 			continue
 		}
-		stats[path.Base(key)] = info
+		stats[extractIDFromCgroupPath(key)] = info
 	}
 	return stats
 }
+
+func extractIDFromCgroupPath(cgroupPath string) string {
+	//case0: /kubepods/burstable/pod2fc932ce-fdcc-454b-97bd-aadfdeb4c340/9be25294016e2dc0340dd605ce1f57b492039b267a6a618a7ad2a7a58a740f32
```
[the remark this answers is not in the document]
Comment (bobbypage) [reply pkg/kubelet/stats/cri_stats_provider.go:835]: (also might be worth to note in comment, case 0 == cgroupfs, case 1 == systemd cgroup driver, etc.

File: pkg/kubelet/stats/cri_stats_provider_test.go [hunk 7]
```diff
@@ -1072,3 +1073,28 @@ func TestGetContainerUsageNanoCores(t *testing.T) {
...
+	tests := []struct {
+		cgroupPath string
+		expected   string
+	}{
+		{
+			cgroupPath: "/kubepods/burstable/pod2fc932ce-fdcc-454b-97bd-aadfdeb4c340/9be25294016e2dc0340dd605ce1f57b492039b267a6a618a7ad2a7a58a740f32",
+			expected:   "9be25294016e2dc0340dd605ce1f57b492039b267a6a618a7ad2a7a58a740f32",
+		},
+		{
+			cgroupPath: "/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2fc932ce_fdcc_454b_97bd_aadfdeb4c340.slice/cri-containerd-aaefb9d8feed2d453b543f6d928cede7a4dbefa6a0ae7c9b990dd234c56e93b9.scope",
```
Comment (bobbypage) [inline pkg/kubelet/stats/cri_stats_provider_test.go:1087]: @haircommander does CRI-O cgroup naming also match this pattern?

File: pkg/kubelet/stats/cri_stats_provider_test.go [hunk 8]
```diff
@@ -696,7 +697,7 @@ func makeFakePodSandbox(name, uid, namespace string, terminated bool) *critest.F
 	if terminated {
 		p.PodSandboxStatus.State = runtimeapi.PodSandboxState_SANDBOX_NOTREADY
 	}
-	p.PodSandboxStatus.Id = string(uuid.NewUUID())
+	p.PodSandboxStatus.Id = strings.ReplaceAll(uuid.New().String(), "-", "")
```
[the remark this answers is not in the document]
Comment (YanzhaoLi) [reply pkg/kubelet/stats/cri_stats_provider_test.go:700]: containerID should not contain dash `-`.

File: pkg/kubelet/stats/cri_stats_provider.go (hunk 5 above)
Comment (YanzhaoLi) [reply pkg/kubelet/stats/cri_stats_provider.go:838]: For case1, both kubelet and containerd are configured to use systemd cgroup in my test. 
My environment is kubernetes 1.21.2 + containerd 1.4.6. 
And also I double checked
1. the kubelet log, it shows systemd cgroup driver.
```
container_manager_linux.go:283] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:remote CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:systemd 
```
2. for the containerd log, there's no error log about cgroup. Here's my configuration
```
version = 2

[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    sandbox_image = xx
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
    runtime_type = "io.containerd.runc.v2"
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true
```
but the `crictl info | grep system` shows
```
$ crictl info | grep system
    "systemdCgroup": false,
```
I am not sure whether containerd is really using the systemd_cgroup driver.

File: pkg/kubelet/stats/cri_stats_provider_test.go (hunk 7 above)
Comment (haircommander) [reply pkg/kubelet/stats/cri_stats_provider_test.go:1087]: yes!

Comment (haircommander) [reply pkg/kubelet/stats/cri_stats_provider_test.go:1087]: though obviously the Base is cri-o-$id.scope

File: pkg/kubelet/stats/cri_stats_provider.go (hunk 5 above)
Comment (YanzhaoLi) [reply pkg/kubelet/stats/cri_stats_provider.go]: It might be due to that in my environment, the kubelet and containerd process is not managed by systemd. 
And I tried in another environment with systemd managing kubelet and containerd, I got same cgroup path as you @bobbypage 

So I just removed the case1 check.`kubepods-besteffort-pod172f50f4_10ce_4f06_af33_3e1f0716b2a0.slice:cri-containerd:0db8ad3f044cd5b67a1be535368e804a5df42ae`

File: pkg/kubelet/stats/cri_stats_provider.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (YanzhaoLi) [reply pkg/kubelet/stats/cri_stats_provider.go]: Done

File: pkg/kubelet/stats/cri_stats_provider_test.go (hunk 7 above)
Comment (YanzhaoLi) [reply pkg/kubelet/stats/cri_stats_provider_test.go:1087]: Hi @bobbypage  @haircommander , will the suffix of systemd-style cgroupPath always be `.scope` ? If yes, I can add check like `if strings.HasSuffix(id, ".scope") `

Comment (bobbypage) [reply pkg/kubelet/stats/cri_stats_provider_test.go:1087]: I think so because runc will create an underlying systemd scope (https://www.freedesktop.org/software/systemd/man/systemd.scope.html) for the container -- https://github.com/opencontainers/runc/blob/master/docs/systemd.md

File: pkg/kubelet/stats/cri_stats_provider_test.go [hunk 9]
```diff
@@ -21,17 +21,18 @@ import (
...
 	"path/filepath"
 	"runtime"
+	"strings"
 	"testing"
 	"time"
 
 	gomock "github.com/golang/mock/gomock"
 	cadvisorfs "github.com/google/cadvisor/fs"
 	cadvisorapiv2 "github.com/google/cadvisor/info/v2"
+	"github.com/google/uuid"
```
Comment (bobbypage) [inline pkg/kubelet/stats/cri_stats_provider_test.go:31]: let's continue to use `k8s.io/apimachinery/pkg/util/uuid` as before?

**Comment by bobbypage** [comment]
Thanks for the updates! I think the fix looks good, LGTM. One small nit about unit test `uuid` package change and it might make sense to also check for `.scope` suffix as you mentioned in systemd case.

File: pkg/kubelet/stats/cri_stats_provider_test.go (hunk 9 above)
Comment (YanzhaoLi) [reply pkg/kubelet/stats/cri_stats_provider_test.go]: Changed as suggested.

Comment (YanzhaoLi) [reply pkg/kubelet/stats/cri_stats_provider_test.go]: And also added suffix check

**Comment by YanzhaoLi** [comment]
Hi @haircommander, do you know if there're cgroupPath like `XXX.slice.scope` ?  If yes, the container id should be `XXX` instead of `XXX.slice`, right? 

I got this question from a note here: https://github.com/opencontainers/runc/blob/master/docs/systemd.md
    -- "Next, prefix and name are used to compose the unit name, which is `<prefix>-<name>.scope`, unless name has `.slice` suffix, in which case prefix is ignored and the name is used as is."

**Comment by haircommander** [comment]
> Hi @haircommander, do you know if there're cgroupPath like `XXX.slice.scope` ? If yes, the container id should be `XXX` instead of `XXX.slice`, right?
> 
> I got this question from a note here: https://github.com/opencontainers/runc/blob/master/docs/systemd.md
> -- "Next, prefix and name are used to compose the unit name, which is `<prefix>-<name>.scope`, unless name has `.slice` suffix, in which case prefix is ignored and the name is used as is."

No, I believe a cgroup must either be a .slice or a .scope, so .slice.scope should be invalid

**Comment by haircommander** [comment]
/lgtm

Thanks @YanzhaoLi !

**Comment by bobbypage** [comment]
/lgtm

Thanks @YanzhaoLi for all your work debugging and fixing this! We should consider backporting this back to affected versions as well.

/assign @mrunalp 
for approvals

**Review by mrunalp — APPROVED** [review]

**Comment by tongpu** [comment]
@bobbypage Has there been any decision made regarding backporting this fix to all maintained and affected relases?

**Comment by varunjain0606** [comment]
As @tongpu pointed out, please let me know if there is a discussion on back-porting the changes to affected releases or at least for versions >= 1.20?

**Comment by CatherineF-dev** [comment]
Hi, if back-porting it into k8s 1.22, which branches should we back-porting into? v1.22.8 or v1.22.0-v1.22.8? Thanks!

cc @ehashman
