### PR TITLE
Set flag show-kind when getting multiple types

### LINKED ISSUE #65375: resource kinds are not shown by default when using kubectl get with custom categories
When using a category (other than `all` - which seems to exhibit the correct behavior, presumably due to special-casing) with `kubectl get`.

**What happened**:

Example: I created 3 CRDs and put them all in the `federation` category. You can see the definitions here:

<details>

```yaml
apiVersion: v1
items:
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    creationTimestamp: 2018-06-22T15:07:26Z
    generation: 1
    name: federatedreplicasetoverrides.federation.pmorie.toy
    namespace: ""
    resourceVersion: "316"
    selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/federatedreplicasetoverrides.federation.pmorie.toy
    uid: f9353caf-762d-11e8-81d6-68f728db1985
  spec:
    additionalPrinterColumns:
    - JSONPath: .metadata.creationTimestamp
      description: |-
        CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

        Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
      name: Age
      type: date
    group: federation.pmorie.toy
    names:
      categories:
      - federation
      kind: FederatedReplicaSetOverride
      listKind: FederatedReplicaSetOverrideList
      plural: federatedreplicasetoverrides
      singular: federatedreplicasetoverride
    scope: Namespaced
    validation:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
          status:
            type: object
        type: object
    version: v1beta1
    versions:
    - name: v1beta1
      served: true
      storage: true
  status:
    acceptedNames:
      categories:
      - federation
      kind: FederatedReplicaSetOverride
      listKind: FederatedReplicaSetOverrideList
      plural: federatedreplicasetoverrides
      singular: federatedreplicasetoverride
    conditions:
    - lastTransitionTime: 2018-06-22T15:07:26Z
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: null
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
    storedVersions:
    - v1beta1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    creationTimestamp: 2018-06-22T15:07:26Z
    generation: 1
    name: federatedreplicasetplacements.federation.pmorie.toy
    namespace: ""
    resourceVersion: "319"
    selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/federatedreplicasetplacements.federation.pmorie.toy
    uid: f939ec45-762d-11e8-81d6-68f728db1985
  spec:
    additionalPrinterColumns:
    - JSONPath: .metadata.creationTimestamp
      description: |-
        CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

        Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
      name: Age
      type: date
    group: federation.pmorie.toy
    names:
      categories:
      - federation
      kind: FederatedReplicaSetPlacement
      listKind: FederatedReplicaSetPlacementList
      plural: federatedreplicasetplacements
      singular: federatedreplicasetplacement
    scope: Namespaced
    validation:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
          status:
            type: object
        type: object
    version: v1beta1
    versions:
    - name: v1beta1
      served: true
      storage: true
  status:
    acceptedNames:
      categories:
      - federation
      kind: FederatedReplicaSetPlacement
      listKind: FederatedReplicaSetPlacementList
      plural: federatedreplicasetplacements
      singular: federatedreplicasetplacement
    conditions:
    - lastTransitionTime: 2018-06-22T15:07:26Z
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: null
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
    storedVersions:
    - v1beta1
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    creationTimestamp: 2018-06-22T15:07:26Z
    generation: 1
    name: federatedreplicasets.federation.pmorie.toy
    namespace: ""
    resourceVersion: "315"
    selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/federatedreplicasets.federation.pmorie.toy
    uid: f93373c9-762d-11e8-81d6-68f728db1985
  spec:
    additionalPrinterColumns:
    - JSONPath: .metadata.creationTimestamp
      description: |-
        CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.

        Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
      name: Age
      type: date
    group: federation.pmorie.toy
    names:
      categories:
      - federation
      kind: FederatedReplicaSet
      listKind: FederatedReplicaSetList
      plural: federatedreplicasets
      singular: federatedreplicaset
    scope: Namespaced
    validation:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
          status:
            type: object
        type: object
    version: v1beta1
    versions:
    - name: v1beta1
      served: true
      storage: true
  status:
    acceptedNames:
      categories:
      - federation
      kind: FederatedReplicaSet
      listKind: FederatedReplicaSetList
      plural: federatedreplicasets
      singular: federatedreplicaset
    conditions:
    - lastTransitionTime: 2018-06-22T15:07:26Z
      message: no conflicts found
      reason: NoConflicts
      status: "True"
      type: NamesAccepted
    - lastTransitionTime: null
      message: the initial names have been accepted
      reason: InitialNamesAccepted
      status: "True"
      type: Established
    storedVersions:
    - v1beta1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

</details>

I created examples as follows:

<details>

```yaml
apiVersion: federation.pmorie.toy/v1beta1
kind: FederatedReplicaSet
metadata:
  name: my-rs
spec:
  foo: bar
---
apiVersion: federation.pmorie.toy/v1beta1
kind: FederatedReplicaSetOverride
metadata:
  name: my-rs
spec:
  foo: bar
---
apiVersion: federation.pmorie.toy/v1beta1
kind: FederatedReplicaSetPlacement
metadata:
  name: my-rs
spec:
  foo: bar
```

</details>

When I run `kubectl get federation`, I see:

```
$ k get federation
NAME      AGE
my-rs     20m

NAME      AGE
my-rs     20m

NAME      AGE
my-rs     20m
```

Note that kind is not present in this output. You can see it with `--show-kind`, but it should be there by default:

```
$ k get federation --show-kind
NAME                                              AGE
federatedreplicaset.federation.pmorie.toy/my-rs   21m

NAME                                                      AGE
federatedreplicasetoverride.federation.pmorie.toy/my-rs   21m

NAME                                                       AGE
federatedreplicasetplacement.federation.pmorie.toy/my-rs   21m
```

**What you expected to happen**:

The expected output is:

```
$ k get federation
NAME                                              AGE
federatedreplicaset.federation.pmorie.toy/my-rs   21m

NAME                                                      AGE
federatedreplicasetoverride.federation.pmorie.toy/my-rs   21m

NAME                                                       AGE
federatedreplicasetplacement.federation.pmorie.toy/my-rs   21m
```

**How to reproduce it (as minimally and precisely as possible)**:

Use the enclosed CRD definitions and examples.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): master

/kind bug

### PR DESCRIPTION
**Pull request by yue9944882**
**What this PR does / why we need it**:

Set "--show-kind" flag if requesting multiple resource types.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #65375 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/kubectl/cmd/get/get.go [hunk 1]
```diff
@@ -219,7 +220,12 @@ func (o *GetOptions) Complete(f cmdutil.Factory, cmd *cobra.Command, args []stri
 
 	o.IncludeUninitialized = cmdutil.ShouldIncludeUninitialized(cmd, false)
 
-	if resource.MultipleTypesRequested(args) {
+	restConfig, err := f.ToRESTConfig()
+	if err != nil {
+		return err
+	}
+
+	if resource.MultipleTypesRequested(args) || resource.CustomResourceDefinitionRequested(crdclientset.NewForConfigOrDie(restConfig), args) {
```
Comment (nikhita) [inline pkg/kubectl/cmd/get/get.go]: instead of specifically checking if it is a category related to a CRD, I think we should instead check if it is a category after all.

Comment (nikhita) [reply pkg/kubectl/cmd/get/get.go]: something like this? https://github.com/nikhita/kubernetes/commit/1f7ec99f6cbb6aee61b5453c699648dd8f20d438

**Comment by nikhita** [comment]
We should also add a test.

**Comment by yue9944882** [comment]
@nikhita Thx a ton.

btw should we print the kinds on e.g. "kubectl get ingress,<catetory>". If so, we should looping over the args to check if any element is a category instead of `args[0]` the very first one. WDYT?

File: pkg/kubectl/genericclioptions/resource/builder.go [hunk 2]
```diff
@@ -1141,3 +1141,13 @@ func MultipleTypesRequested(args []string) bool {
 	}
 	return rKinds.Len() > 1
 }
+
+func AnyCategoryRequested(categoryExpander restmapper.CategoryExpander, args []string) bool {
+	for _, arg := range args {
+		_, ok := categoryExpander.Expand(arg)
```
Comment (nikhita) [inline pkg/kubectl/genericclioptions/resource/builder.go]: > btw should we print the kinds on e.g. "kubectl get ingress,[catetory]". If so, we should looping over the args to check if any element is a category instead of args[0] the very first one. WDYT?

We can always specify one category at a time. :)

So the category will always be `args[0]` and `len(args)==1`.

File: pkg/kubectl/cmd/get/get.go [hunk 3]
```diff
@@ -224,9 +225,12 @@ func (o *GetOptions) Complete(f cmdutil.Factory, cmd *cobra.Command, args []stri
 
 	o.IncludeUninitialized = cmdutil.ShouldIncludeUninitialized(cmd, false)
 
-	if resource.MultipleTypesRequested(args) {
+	discoveryClient, discoveryErr := f.ToDiscoveryClient()
+	if resource.MultipleTypesRequested(args) ||
+		(discoveryErr == nil && resource.AnyCategoryRequested(restmapper.NewDiscoveryCategoryExpander(discoveryClient), args)) {
```
Comment (nikhita) [inline pkg/kubectl/cmd/get/get.go]: The logic in `MultipleTypesRequested` still contains special casing for the `all` category. We can remove the special casing if we move the categories check inside that function.

Comment (nikhita) [reply pkg/kubectl/cmd/get/get.go]: Or we can remove the special casing there, but I guess it's better to have it all in the function?

**Comment by liggitt** [comment]
> Set "--show-kind" flag if any requested resource is a CRD

We don't want kubectl to treat CRDs specially. it should not be trying to determine if the requested resource is native or not. We still only want to force showing the kind if multiple resources are requested

**Comment by nikhita** [comment]
> We don't want kubectl to treat CRDs specially. 

@liggitt The title needs to be updated. This title was according to the original code (which has been force pushed over now).

**Comment by yue9944882** [comment]
@liggitt 

> @liggitt The title needs to be updated. This title was according to the original code (which has been force pushed over now).

SRY. I should have updated the title. Not treating CRD separately anymore but checking if the argument is of any category (including "all") via discovery mechanism.

**Comment by nikhita** [comment]
@yue9944882 can you update it to check for only a single category and add a test? thanks!

Something like https://github.com/nikhita/kubernetes/commit/1f7ec99f6cbb6aee61b5453c699648dd8f20d438#diff-5c5b79df741db38e16bbacdd1dea39eeR1113.

**Comment by yue9944882** [comment]
@nikhita Of course I'd happy to. I'm sort of busy handling something for my job.. 🤧Will update it later ASAP. Tomorrow maybe.

File: pkg/kubectl/cmd/get/get.go (hunk 3 above)
Comment (liggitt) [reply pkg/kubectl/cmd/get/get.go]: it would make more sense to remove the check from Complete(), and figure out how to get the info about whether multiple types were requested from the component that actually knows already, which is the resource builder in `Run()`, after `ResourceTypeOrNameArgs(...)` has been called

File: pkg/kubectl/cmd/get/get.go [hunk 4]
```diff
@@ -493,25 +496,8 @@ func (o *GetOptions) watch(f cmdutil.Factory, cmd *cobra.Command, args []string)
...
-		// infos returned by the builder. To handle this case, only fail if we
-		// have at least one info with a different GVK than the others.
-		for _, info := range infos {
-			if info.Mapping.GroupVersionKind != gvk {
-				uniqueGVKs++
-			}
-		}
-
-		if uniqueGVKs > 1 {
-			return i18n.Errorf("watch is only supported on individual resources and resource collections - %d resources were found", uniqueGVKs)
```
Comment (yue9944882) [inline pkg/kubectl/cmd/get/get.go]: This line looks strange to me. e.g. If a sequence of "A B A" is the input, the error msg will still be `3 resources were found`. So I simplify it.

**Comment by yue9944882** [comment]
@liggit @nikhita Thanks you. I tried to add a test for `kubectl get <category>`, but it seems a lot complicated because we don't support discovery for `fake.RESTClient`.🤕 Could you please shed some light on how to validate it's correctness for categories? Or do we really need it since that the change is so small.

File: pkg/kubectl/genericclioptions/resource/builder.go [hunk 5]
```diff
@@ -1110,10 +1110,6 @@ func HasNames(args []string) (bool, error) {
 
 // MultipleTypesRequested returns true if the provided args contain multiple resource kinds
 func MultipleTypesRequested(args []string) bool {
```
Comment (liggitt) [inline pkg/kubectl/genericclioptions/resource/builder.go]: we should be able to remove this method and the call to it completely

File: pkg/kubectl/cmd/get/get.go [hunk 6]
```diff
@@ -750,3 +736,28 @@ func maybeWrapSortingPrinter(printer printers.ResourcePrinter, sortBy string) pr
 	}
 	return printer
 }
+
+func multipleGVKsRequested(infos []*resource.Info) bool {
```
Comment (liggitt) [inline pkg/kubectl/cmd/get/get.go]: could simplify to:
```go
if len(infos) < 2 {
  return false
}
gvk := infos[0].Mapping.GroupVersionKind
for _, info := range infos {
  if info.Mapping.GroupVersionKind != gvk {
    return true
  }
}
return false
```

File: pkg/kubectl/cmd/get/get.go [hunk 7]
```diff
@@ -345,6 +345,9 @@ func (o *GetOptions) Run(f cmdutil.Factory, cmd *cobra.Command, args []string) e
 	if err != nil {
 		allErrs = append(allErrs, err)
 	}
+	if multipleGVKsRequested(infos) {
+		o.PrintFlags.EnsureWithKind()
```
Comment (liggitt) [inline pkg/kubectl/cmd/get/get.go]: don't mutate o.PrintFlags here, set a local withKind boolean, pass it into ToPrinter, and set it on the copy of the print flags inside that function

**Comment by liggitt** [comment]
> @liggitt @nikhita Thanks you. I tried to add a test for kubectl get <category>, but it seems a lot complicated because we don't support discovery for fake.RESTClient.🤕 Could you please shed some light on how to validate it's correctness for categories? Or do we really need it since that the change is so small.

we should ensure the discovery doc used for tests includes categories - https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/testing/fake.go#L441

**Comment by yue9944882** [comment]
@liggit PTAL :)

**Comment by liggitt** [comment]
/approve

looks good to me, thanks. go ahead and squash, then will lgtm
