### PR TITLE
Default cluster dns-domain to empty string in e2e_node suite

### LINKED ISSUE #98020: NodeFeature:SetHostnameAsFQDN failing in periodic node-kubelet-features-master job
**Which jobs are failing**:
[sig-node-kubelet/node-kubelet-features-master ](https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-features-master) 

**Which test(s) are failing**:
https://github.com/kubernetes/kubernetes/blob/23839ba6492a682d5011d112e3772d4f5978b2de/test/e2e_node/pod_hostnamefqdn_test.go

**Since when has it been failing**:
From about 9 hours ago.

**Testgrid link**:
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-features-master

**Reason for failure**:
Unknown. 

**Anything else we need to know**:
Along with this job, even [CRIO job](https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features) for `NodeFeatures` started failing with similar tests. 

While `node-kubelet-features-master` is failing, [node-kubelet-features-1.20](https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-features-1.20) is not failing indicating that something went in master in last 9 hours that's breaking the tests.

### PR DESCRIPTION
**Pull request by hasheddan**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

Changes default cluster DNS domain to empty string to align with the
default kubelet configuration value.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

**Which issue(s) this PR fixes**:

Fixes #98020 

**Special notes for your reviewer**:

Defaulting to `cluster.local` means that any consumer of the e2e node test suite must configure the kubelet cluster domain instead of using the default:
https://github.com/kubernetes/kubernetes/blob/5c58b222516c0c8547d2f699b7582db9df09df8d/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L299

xref https://github.com/kubernetes/kubernetes/pull/96315

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by SergeyKanzhelev — COMMENTED** [review]
/lgtm

File: test/e2e_node/e2e_node_suite_test.go [hunk 1]
```diff
@@ -84,7 +84,7 @@ func registerNodeFlags(flags *flag.FlagSet) {
 	flags.StringVar(&framework.TestContext.SystemSpecName, "system-spec-name", "", "The name of the system spec (e.g., gke) that's used in the node e2e test. The system specs are in test/e2e_node/system/specs/. This is used by the test framework to determine which tests to run for validating the system requirements.")
 	flags.Var(cliflag.NewMapStringString(&framework.TestContext.ExtraEnvs), "extra-envs", "The extra environment variables needed for node e2e tests. Format: a list of key=value pairs, e.g., env1=val1,env2=val2")
 	flags.StringVar(&framework.TestContext.SriovdpConfigMapFile, "sriovdp-configmap-file", "", "The name of the SRIOV device plugin Config Map to load.")
-	flag.StringVar(&framework.TestContext.ClusterDNSDomain, "dns-domain", "cluster.local", "The DNS Domain of the cluster.")
+	flag.StringVar(&framework.TestContext.ClusterDNSDomain, "dns-domain", "", "The DNS Domain of the cluster.")
```
Comment (oomichi) [inline test/e2e_node/e2e_node_suite_test.go:87]: Thanks for doing this.
I see the test failures like https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-features/1349429706050506752 as an example.
One of failed tests sets `hostFQDN` like https://github.com/kubernetes/kubernetes/blob/5c58b222516c0c8547d2f699b7582db9df09df8d/test/e2e_node/pod_hostnamefqdn_test.go#L117
If `framework.TestContext.ClusterDNSDomain` becomes empty like this PR, the hostFQDN becomes like `foo-pod.foo-subdomain.foo-ns.svc.` without `cluster.local`.
The FQDN is different from common cases I feel like https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
Can we enable`cluster.local` instead?

/cc @oomichi

Comment (hasheddan) [reply test/e2e_node/e2e_node_suite_test.go:87]: @oomichi we could, although I am hesitant to require that for these tests to run successfully as that is not the default for the kubelet. If we were to set to `cluster.local` we would do so here: https://github.com/kubernetes/test-infra/blob/c094f147c10f9b667472e81a5b36e12a61446e37/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L127

Comment (oomichi) [reply test/e2e_node/e2e_node_suite_test.go:87]: I see, thanks for your explanation.
I guess it is ideal to change the default value to "cluster.local" on kubelet side at the end of day, but current change is fine for me to solve test failure at this time.

/triage accepted
/lgtm

**Comment by hasheddan** [comment]
@klueska @mrunalp could I get one of y'all to take a quick look here?
