### PR TITLE
Fix Azure SLB support for multiple backend pools

### LINKED ISSUE #76687: SLB backend pools are empty if outbound rules are defined in a separate backend pool
**What happened**:

SLB backend pools are empty if outbound rules are defined in a separate backend pool.

This is because, although we added the check for not adding the backend pools from different LBs, the lbName is not checked:

https://github.com/kubernetes/kubernetes/blob/fe8cd08a1be83e659f6a51d70a5b35b329ba40cc/pkg/cloudprovider/providers/azure/azure_vmss.go#L783-L799

The new backend pool's lbName should be also checked in above codes.

**What you expected to happen**:

SLB backend pools should be updated correctly when outbound rules are defined in a separate backend pool.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/sig azure
/kind bug
/assign

### PR DESCRIPTION
**Pull request by feiskyer**
Azure VM and vmssVM support multiple backend pools for the same SLB, but
not for different LBs.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

SLB backend pools are empty if outbound rules are defined in a separate backend pool.

This is because, although we added the check for not adding the backend pools from different LBs, the lbName is not checked.

This PR fixes the issue by also checking the LB name.

**Which issue(s) this PR fixes**:

Fixes #76687

**Special notes for your reviewer**:

Should cherry pick to old releases.

**Does this PR introduce a user-facing change?**:

```release-note
Ensure the backend pools are set correctly for Azure SLB with multiple backend pools (e.g. outbound rules)
```

/kind bug
/sig azure
/priority critial-urgent

### CODE REVIEW

File: pkg/cloudprovider/providers/azure/azure_wrap.go [hunk 1]
```diff
@@ -336,3 +336,28 @@ func convertResourceGroupNameToLower(resourceID string) (string, error) {
 	resourceGroup := matches[1]
 	return strings.Replace(resourceID, resourceGroup, strings.ToLower(resourceGroup), 1), nil
 }
+
+// isBackendPoolOnSameLB checks whether newBackendPoolID is on the same load balancer as existingBackendPools.
+// Since both public and internal LBs are supported, lbName and lbName-internal are treated as same.
+func isBackendPoolOnSameLB(newBackendPoolID string, existingBackendPools []string) (bool, string, error) {
```
Comment (andyzhangx) [inline pkg/cloudprovider/providers/azure/azure_wrap.go]: could you add comments about returned lbName, looks like the returned lbName depends on whether match or not, a little tricky.

**Review by andyzhangx — COMMENTED** [review]
is it possible to combine the code change (use a standalone function?) under vmas and vmss, it's quite similar:
```
			newBackendPoolsIDs := make([]string, 0, len(newBackendPools))
			for _, pool := range newBackendPools {				for _, pool := range newBackendPools {
				backendPool := *pool.ID					if pool.ID != nil {
				matches := backendPoolIDRE.FindStringSubmatch(backendPool)						newBackendPoolsIDs = append(newBackendPoolsIDs, *pool.ID)
				if len(matches) == 2 {	
					lbName := matches[1]	
					if strings.HasSuffix(lbName, InternalLoadBalancerNameSuffix) == isInternal {	
						klog.V(4).Infof("Node %q has already been added to LB %q, omit adding it to a new one", nodeName, lbName)	
						return nil	
					}	
				}					}
			}				}
			isSameLB, oldLBName, err := isBackendPoolOnSameLB(backendPoolID, newBackendPoolsIDs)
			if err != nil {
				return err
			}
			if !isSameLB {
				klog.V(4).Infof("Node %q has already been added to LB %q, omit adding it to a new one", nodeName, oldLBName)
				return nil
			}
```

**Comment by feiskyer** [comment]
> is it possible to combine the code change (use a standalone function?) under vmas and vmss, it's quite similar

that's already done in func `isBackendPoolOnSameLB()`. The other parts couldn't be combined because of different data struct.

File: pkg/cloudprovider/providers/azure/azure_wrap.go (hunk 1 above)
Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_wrap.go]: it is the lb name of existingBackendPools, if the codes go to the last line, then newLBName is actually same with lbName.

Comment (feiskyer) [reply pkg/cloudprovider/providers/azure/azure_wrap.go]: Added the docs here.

**Comment by feiskyer** [comment]
@andyzhangx Addressed comments. PTAL

**Review by andyzhangx — APPROVED** [review]
/lgtm
