### PR TITLE
Kubeadm issue #3152 ControlPlane node setup failing with "etcdserver: can only promote a learner member"

### LINKED ISSUE #3152: ControlPlane node setup failing with "etcdserver: can only promote a learner member"
Hello

I am using CAPI to manage setting up new kubernetes clusters
In my environment I am encountering an issue where I try to setup a 3 node controlplane but get stuck after adding the second node.

In the kcp logs  this error repeats
```
E0121 13:25:32.061001       1 controller.go:316] "Reconciler error" err="failed to get etcdStatus for workload cluster obj-store-01: failed to create etcd client: etcd leader is reported as bc116290b8a83a52 with name \"obj-store-01-wchl9\", but we couldn't find a corresponding Node in the cluster" controller="kubeadmcontrolplane" controllerGroup="controlplane.cluster.x-k8s.io" controllerKind="KubeadmControlPlane" KubeadmControlPlane="minio-default/obj-store-01" namespace="minio-default" name="obj-store-01" reconcileID="75ed1ba2-fd8c-43a3-bd16-2ced8db56999"
```

The etcd member table looks like this
```
+------------------+---------+--------------------+-----------------------------+-----------------------------+------------+
|        ID        | STATUS  |        NAME        |         PEER ADDRS          |        CLIENT ADDRS         | IS LEARNER |
+------------------+---------+--------------------+-----------------------------+-----------------------------+------------+
| 785b2d66a9ca13ed | started | obj-store-01-gd6dn | https://SOME_IP:2380 | https://SOME_IP:2379 |      false |
| bc116290b8a83a52 | started | obj-store-01-wchl9 | https://SOME_OTHER_IP:2380 | https://SOME_OTHER_IP:2379 |      false |
+------------------+---------+--------------------+-----------------------------+-----------------------------+------------+
```

If i look at the cloud-init-output log for node obj-store-01-wchl9 it terminates with an error
```
[2025-01-21 12:14:31] {"level":"warn","ts":"2025-01-21T12:14:31.940653Z","logger":"etcd-client","caller":"v3@v3.5.10/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000d68c0/SOME_IP:2379","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: request timed out, waiting for the applied index took too long"}
[2025-01-21 12:14:37] {"level":"warn","ts":"2025-01-21T12:14:37.958044Z","logger":"etcd-client","caller":"v3@v3.5.10/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000d68c0/SOME_IP:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
[2025-01-21 12:14:45] {"level":"warn","ts":"2025-01-21T12:14:45.689035Z","logger":"etcd-client","caller":"v3@v3.5.10/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000d68c0/SOME_IP:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: can only promote a learner member"}
[2025-01-21 12:14:53] [kubelet-check] Initial timeout of 40s passed.
[2025-01-21 12:14:56] {"level":"warn","ts":"2025-01-21T12:14:56.933405Z","logger":"etcd-client","caller":"v3@v3.5.10/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000d68c0/SOME_IP:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: can only promote a learner member"}
[2025-01-21 12:15:10] {"level":"warn","ts":"2025-01-21T12:15:10.318514Z","logger":"etcd-client","caller":"v3@v3.5.10/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000d68c0/SOME_IP:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: can only promote a learner member"}
[2025-01-21 12:15:31] {"level":"warn","ts":"2025-01-21T12:15:31.439807Z","logger":"etcd-client","caller":"v3@v3.5.10/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000d68c0/SOME_IP:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: can only promote a learner member"}
[2025-01-21 12:16:03] {"level":"warn","ts":"2025-01-21T12:16:03.125611Z","logger":"etcd-client","caller":"v3@v3.5.10/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000d68c0/SOME_IP:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: can only promote a learner member"}
[2025-01-21 12:16:49] {"level":"warn","ts":"2025-01-21T12:16:49.883513Z","logger":"etcd-client","caller":"v3@v3.5.10/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000d68c0/SOME_IP:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: can only promote a learner member"}
[2025-01-21 12:18:02] {"level":"warn","ts":"2025-01-21T12:18:02.221299Z","logger":"etcd-client","caller":"v3@v3.5.10/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0000d68c0/SOME_IP:2379","attempt":0,"error":"rpc error: code = FailedPrecondition desc = etcdserver: can only promote a learner member"}
```
So it appears that we had added an etcd member as a learner and then were attempting to promote it.
One of the calls to promote times out but succeeded on the backend, causing all future calls to promote to fail

I found this recent PR that addresses a similar issue https://github.com/kubernetes/kubernetes/pull/127491 but would not address the problem I'm seeing

In the latest kubeadm the MemberPromote now looks like this
```
// MemberPromote promotes a member as a voting member. If the given member ID is already a voting member this method
// will return early and do nothing.
func (c *Client) MemberPromote(learnerID uint64) error {
    isLearner, err := c.isLearner(learnerID)
    if err != nil {
        return err
    }
    if !isLearner {
        klog.V(1).Infof("[etcd] Member %s already promoted.", strconv.FormatUint(learnerID, 16))
        return nil
    }

    klog.V(1).Infof("[etcd] Promoting a learner as a voting member: %s", strconv.FormatUint(learnerID, 16))
    cli, err := c.newEtcdClient(c.Endpoints)
    if err != nil {
        return err
    }
    defer func() { _ = cli.Close() }()

    // TODO: warning logs from etcd client should be removed.
    // The warning logs are printed by etcd client code for several reasons, including
    // 1. can not promote yet(no synced)
    // 2. context deadline exceeded
    // 3. peer URLs already exists
    // Once the client provides a way to check if the etcd learner is ready to promote, the retry logic can be revisited.
    var (
        lastError error
    )
    err = wait.PollUntilContextTimeout(context.Background(), constants.EtcdAPICallRetryInterval, constants.EtcdAPICallTimeout,
        true, func(_ context.Context) (bool, error) {
            ctx, cancel := context.WithTimeout(context.Background(), etcdTimeout)
            defer cancel()

            _, err = cli.MemberPromote(ctx, learnerID) <=== We need an are we promoted check here as well
            if err == nil {
                klog.V(1).Infof("[etcd] The learner was promoted as a voting member: %s", strconv.FormatUint(learnerID, 16))
                return true, nil
            }
            klog.V(5).Infof("[etcd] Promoting the learner %s failed: %v", strconv.FormatUint(learnerID, 16), err)
            lastError = err
            return false, nil
        })
    if err != nil {
        return lastError
    }
    return nil
}
```

What I would like to do is add an additional check within the `wait.PollUntilContextTimeout` func so that it checks if the member has been promoted before every attempt to promote. If the member has already been promoted it should return early
i.e. reuse this code from earlier in the function
```
isLearner, err := c.isLearner(learnerID)
    if err != nil {
        return err
    }
    if !isLearner {
        klog.V(1).Infof("[etcd] Member %s already promoted.", strconv.FormatUint(learnerID, 16))
        return nil
    }
```

Ideally etcd cluster wouldnt return a timeout message when the op actually succeeded, but I would like to add this extra check regardless as I think its fairly low risk. How would I go about adding it?

### PR DESCRIPTION
**Pull request by BernardMC**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fixes issues where kubeadm tries to promote a learner member that is already promoted
This can happen when a previous promote does not return a success but the promotion actually succeeded on 
the backend. This caused the script to eventually timeout and node bring up to fail
Also added an additional call to remove the member we failed to add if member promotion failed entirely

#### Which issue(s) this PR fixes:
https://github.com/kubernetes/kubeadm/issues/3152

Fixes https://github.com/kubernetes/kubeadm/issues/3152

#### Does this PR introduce a user-facing change?
NONE

```release-note
kubeadm: fixed issue where etcd member promotion fails with an error saying the member was already promoted
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/release-note-edit

```release-note
kubeadm: fixed issue where etcd member promotion fails with an error saying the member was already promoted
```

**Comment by neolit123** [comment]
@BernardMC please keep the commits squashed to 1.
note that any merge commits cannot be merged.

**Comment by neolit123** [comment]
please change this in the pr description

```
https://github.com/kubernetes/kubeadm/issues/3152

Fixes #
```

to be

```
Fixes https://github.com/kubernetes/kubeadm/issues/3152

```

**Review by neolit123 — COMMENTED** [review]
/cc @pacoxu 
ptal if possible.

@BernardMC please message here once the cla is approved.

File: cmd/kubeadm/app/util/etcd/etcd.go [hunk 1]
```diff
@@ -586,6 +595,11 @@ func (c *Client) MemberPromote(learnerID uint64) error {
 			return false, nil
 		})
 	if err != nil {
+		klog.V(5).Infof("[etcd] Failed to promote the learner %s before timeout. Attempting to remove learner member", strconv.FormatUint(learnerID, 16))
+		_, err = cli.MemberRemove(context.Background(), learnerID)
```
Comment (HirazawaUi) [inline cmd/kubeadm/app/util/etcd/etcd.go:599]: I understand that if promoting an etcd learner fails, we should remove the unstable member. But why don't we move the member removal action outside the `Client.MemberPromote` method, and when the `Client.MemberPromote` call fails, we invoke Client.RemoveMember to delete the member?

Since `Client.RemoveMember` contains retry mechanisms, it might better handle member removal failures. For example:
```
	err = etcdClient.MemberPromote(learnerID)
	if err != nil {
		klog.V(5).Infof("[etcd] Failed to promote the learner %s before timeout. Attempting to remove learner member", strconv.FormatUint(learnerID, 16))
		if _, removeErr := etcdClient.RemoveMember(learnerID); removeErr != nil {
			klog.V(5).Infof("[etcd] Removing the learner %s failed: %v", strconv.FormatUint(learnerID, 16), removeErr)
		}
		return err
	}
```

If you believe that removing the unstable member after a failed promote etcd learner is just a best-effort action and does not require retries, please add comments to clarify this behavior.

File: cmd/kubeadm/app/util/etcd/etcd.go [hunk 2]
```diff
@@ -576,6 +576,15 @@ func (c *Client) MemberPromote(learnerID uint64) error {
 			ctx, cancel := context.WithTimeout(context.Background(), etcdTimeout)
 			defer cancel()
 
+			isLearner, err := c.isLearner(learnerID)
+			if err != nil {
+				return false, err
+			}
+			if !isLearner {
+				klog.V(1).Infof("[etcd] Member %s already promoted.", strconv.FormatUint(learnerID, 16))
+				return false, nil
```
Comment (SataQiu) [inline cmd/kubeadm/app/util/etcd/etcd.go:585]: return `true` here?

File: cmd/kubeadm/app/util/etcd/etcd.go (hunk 1 above)
Comment (BernardMC) [reply cmd/kubeadm/app/util/etcd/etcd.go:599]: Yeah, I think it makes sense to make the remove call an explicit call from outside rather than inside the member promote

File: cmd/kubeadm/app/util/etcd/etcd.go (hunk 2 above)
Comment (BernardMC) [reply cmd/kubeadm/app/util/etcd/etcd.go]: Yup should be true

**Comment by BernardMC** [comment]
Sorry for any weirdness in thi PR git wise .. Im not used to forks and PR, I normally branch and merge...
but I think I have it right now .. a single commit

**Comment by HirazawaUi** [comment]
> Sorry for any weirdness in thi PR git wise .. Im not used to forks and PR, I normally branch and merge...
> but I think I have it right now .. a single commit

No need to sorry, thank you very much for your contribution. Please sign the EasyCLA so we can proceed with this PR.

**Comment by pacoxu** [comment]
You commit user `bconry` is not the github user name. This may fail the CLA.

File: cmd/kubeadm/app/util/etcd/etcd.go [hunk 3]
```diff
@@ -576,6 +576,15 @@ func (c *Client) MemberPromote(learnerID uint64) error {
 			ctx, cancel := context.WithTimeout(context.Background(), etcdTimeout)
 			defer cancel()
 
+			isLearner, err := c.isLearner(learnerID)
+			if err != nil {
+				return false, err
+			}
+			if !isLearner {
+				klog.V(1).Infof("[etcd] Member %s already promoted.", strconv.FormatUint(learnerID, 16))
```
Comment (pacoxu) [inline cmd/kubeadm/app/util/etcd/etcd.go:584]:
```suggestion
				klog.V(1).Infof("[etcd] Member %s was already promoted.", strconv.FormatUint(learnerID, 16))
```

**Comment by BernardMC** [comment]
> You commit user `bconry` is not the github user name. This may fail the CLA.

Yeah my global commit email was @vmware.com and I did not update it to @broadcom.com
I have done it now and resquashed the commits so hopefully just waiting for someone in my org to approve the CLA

**Comment by BernardMC** [comment]
@HirazawaUi @pacoxu I got my CLA resolved!

**Comment by HirazawaUi** [comment]
Did you miss the content mentioned comment?
ref: https://github.com/kubernetes/kubernetes/pull/130782#discussion_r1994571103

**Comment by BernardMC** [comment]
> Did you miss the content mentioned comment? ref: [#130782 (comment)](https://github.com/kubernetes/kubernetes/pull/130782#discussion_r1994571103)

I'll do a separate PR for that, since leaving a zombie etcd member issue isn't unique to this "learner already promoted" issue. I'm also not as familiar with that part of code yet 😊

**Review by pacoxu — COMMENTED** [review]
/lgtm

**Comment by pacoxu** [comment]
Since we missed the code freeze of v1.33, should we cherry-pick it after v1.33.0 release? @neolit123

**Comment by HirazawaUi** [comment]
> I'll do a separate PR for that, since leaving a zombie etcd member issue isn't unique to this "learner already promoted" issue. I'm also not as familiar with that part of code yet 😊

/lgtm

**Review by SataQiu — APPROVED** [review]

**Comment by neolit123** [comment]
> Since we missed the code freeze of v1.33, should we cherry-pick it after v1.33.0 release? @neolit123

sgtm

**Comment by BernardMC** [comment]
`Pending - Not mergeable. Must be in milestone v1.33.`
I see this, so are we waiting for v1.34 branch to exist and then merging it to that?

**Comment by neolit123** [comment]
since it's not a critical bug we should ideally wait for 1.33.0 to first release. then this pr will auto-merge in 1.34-pre.
at that point you can use the /hack/chery_pick_pull.sh script to send automated cherry picks for branches:
- release-1.33
- release-1.32
- release-1.31
- release-1.30

versions in support:
https://kubernetes.io/releases/

schedule for 1.33:
https://github.com/kubernetes/sig-release/tree/master/releases/release-1.33

**Comment by neolit123** [comment]
1.33.0 is out, this will merge soon when the queue is unblocked.

**Comment by nojnhuh** [comment]
@neolit123 @BernardMC Is there still a plan to backport this fix?

**Comment by neolit123** [comment]
> @neolit123 @BernardMC Is there still a plan to backport this fix?

backport PRs are welcome.
i thought @BernardMC is going to handle them, but anyone can do it, with the /hack/cherry-pick script

**Comment by neolit123** [comment]
nmv, i have some time today and will send the cherry picks.

**Comment by neolit123** [comment]
> nmv, i have some time today and will send the cherry picks.

done
- https://github.com/kubernetes/kubernetes/pull/132283
- https://github.com/kubernetes/kubernetes/pull/132282
- https://github.com/kubernetes/kubernetes/pull/132281
- https://github.com/kubernetes/kubernetes/pull/132280

**Comment by neolit123** [comment]
@carlory  could you please lgtm the other two prs as well.

**Comment by carlory** [comment]
Done
