### PR TITLE
Test on CRUD operations on RuntimeClasses API

### LINKED ISSUE #96524: Add conformance tests for RuntimeClass v1 API
Per the @liggitt comment in this PR https://github.com/kubernetes/kubernetes/pull/95718#issuecomment-725735634 conformance tests will regress because of a newly added Runtime Class GA v1 API is not covered with tests. Full comment:

Full comment:

> Does this have e2e coverage of all verbs on all endpoints of v1 RuntimeClasses (like [ea8f4cb](https://github.com/kubernetes/kubernetes/commit/ea8f4cb536718e2695a5c15362695767928fbc4c))? If not, this will appear as a regression in conformance coverage of GA endpoints. The expectation is that GA APIs have 100% e2e coverage via tests suitable to promote to conformance tests

/assign

More links:

- [apisnoop-conformance-gate](https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/apisnoop-conformance-gate/1326930505215512576#1:build-log.txt%3A442)
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements
- https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#promoting-tests-to-conformance

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
**What type of PR is this?**

/kind cleanup
/kind regression
/sig node

**What this PR does / why we need it**:
This PR added a test to be promoted to conformance that exercise  all CRUD operations of RuntimeClasses API.

**Which issue(s) this PR fixes**:
Related #96524

(The follow up PR that will promote the test to conformance will fix it)

**Special notes for your reviewer**:
Added comments needed for conformance, but keep it regular test for presubmits to run it.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

- KEP: https://github.com/kubernetes/enhancements/issues/585

```docs

```

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Test passes

```
I1113 09:11:42.088] [It]  [NodeConformance] should support RuntimeClasses API operations
I1113 09:11:42.089]   /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/runtimeclass.go:100
I1113 09:11:42.089] [1mSTEP[0m: getting /apis
I1113 09:11:42.089] [1mSTEP[0m: getting /apis/node.k8s.io
I1113 09:11:42.089] [1mSTEP[0m: getting /apis/certificates.k8s.io/v1
I1113 09:11:42.089] [1mSTEP[0m: creating
I1113 09:11:42.089] [1mSTEP[0m: watching
I1113 09:11:42.089] Nov 13 09:07:25.326: INFO: starting watch
I1113 09:11:42.089] [1mSTEP[0m: getting
I1113 09:11:42.089] [1mSTEP[0m: listing
I1113 09:11:42.090] [1mSTEP[0m: patching
I1113 09:11:42.090] [1mSTEP[0m: updating
I1113 09:11:42.090] Nov 13 09:07:25.350: INFO: waiting for watch events with expected annotations
I1113 09:11:42.090] [1mSTEP[0m: deleting
I1113 09:11:42.090] [1mSTEP[0m: deleting a collection
I1113 09:11:42.090] [AfterEach] [sig-node] RuntimeClass
```

File: test/e2e/common/runtimeclass.go [hunk 1]
```diff
@@ -84,6 +87,165 @@ var _ = ginkgo.Describe("[sig-node] RuntimeClass", func() {
 
 		expectPodRejection(f, e2enode.NewRuntimeClassPod(rcName))
 	})
+
+	/*
+		Release: v1.20
+		Testname: RuntimeClass API
+		Description:
+		The node.k8s.io API group MUST exists in the /apis discovery document.
```
Comment (mrunalp) [inline test/e2e/common/runtimeclass.go:95]: nit: exists -> exist

File: test/e2e/common/runtimeclass.go [hunk 2]
```diff
@@ -84,6 +87,165 @@ var _ = ginkgo.Describe("[sig-node] RuntimeClass", func() {
...
+			for _, version := range group.Versions {
+				if version.Version == rcVersion {
+					found = true
+					break
+				}
+			}
+			framework.ExpectEqual(found, true, fmt.Sprintf("expected RuntimeClass API version, got %#v", group.Versions))
+		}
+
+		ginkgo.By("getting /apis/certificates.k8s.io/" + rcVersion)
```
Comment (mrunalp) [inline test/e2e/common/runtimeclass.go:147]: certificates seems like a copy / paste remnant?

Comment (SergeyKanzhelev) [reply test/e2e/common/runtimeclass.go:147]: yes, fixing

**Comment by SergeyKanzhelev** [comment]
CC: @hh, @liggitt 

Should the process be merging it first and after that if it passes for a few days, send another PR that will change it to Conformance?

File: test/e2e/common/runtimeclass.go [hunk 3]
```diff
@@ -84,6 +87,165 @@ var _ = ginkgo.Describe("[sig-node] RuntimeClass", func() {
...
+	/*
+		Release: v1.20
+		Testname: RuntimeClass API
+		Description:
+		The node.k8s.io API group MUST exist in the /apis discovery document.
+		The node.k8s.io/v1 API group/version MUST exist in the /apis/mode.k8s.io discovery document.
+		The runtimeclasses resource MUST exist in the /apis/node.k8s.io/v1 discovery document.
+		The runtimeclasses resource must support create, get, list, watch, update, patch, delete, and deletecollection.
+	*/
+	ginkgo.It(" [NodeConformance] should support RuntimeClasses API operations", func() {
```
Comment (SergeyKanzhelev) [inline test/e2e/common/runtimeclass.go:100]: keeping it as a regular test for now. Also added `[NodeConformance]` so it will run during the PR validation

**Comment by hh** [comment]
Merge first, then we will need a separate promotion PR with the conformance metadata.

**Comment by jeremyrickard** [comment]
Exception request: https://groups.google.com/g/kubernetes-sig-node/c/UhZ7JgaeZPE
Exception Granted: Nov 13
/milestone v1.20

File: test/e2e/common/runtimeclass.go [hunk 4]
```diff
@@ -84,6 +87,165 @@ var _ = ginkgo.Describe("[sig-node] RuntimeClass", func() {
...
+		// Setup
+		rcVersion := "v1"
+		rcClient := f.ClientSet.NodeV1().RuntimeClasses()
+
+		rc := runtimeclasstest.NewRuntimeClass(f.UniqueName+"-handler", f.UniqueName+"-conformance-runtime-class")
```
Comment (derekwaynecarr) [inline test/e2e/common/runtimeclass.go:105]: as long as the handler is opaque to the conformance test and we do not drive any behavior implied to any specific handler, i am fine having this in conformance.  can we keep a note in the test that makes it clear that we should _never_ test a particular handler under conformance?

Comment (SergeyKanzhelev) [reply test/e2e/common/runtimeclass.go:109]: added the comment

Comment (tallclair) [reply test/e2e/common/runtimeclass.go:109]: this looks fine, but also note that there isn't any requirement that handlers be unique across runtime classes.

**Review by tallclair — COMMENTED** [review]
/lgtm
/approve

To unblock RuntimeClass to GA. It still strikes me as odd that we need to write out these tests in full, so we should make sure to deduplicate these in the future.

**Comment by dchen1107** [comment]
/lgtm
/approve

Thanks!
