### PR TITLE
fix(queue_test): make sure the first bind failure via counter

### LINKED ISSUE #120363: pull-kubernetes-integration: k8s.io/kubernetes/test/integration/scheduler: TestRequeueByBindFailure
### Which jobs are flaking?

pull-kubernetes-integration: k8s.io/kubernetes/test/integration: scheduler

### Which tests are flaking?

TestRequeueByBindFailure
```
    queue_test.go:494: Expect pod-1 to be rejected by the bind plugin
```

Running with stress reproduces the flake

```
go test -c ./test/integration/scheduler
stress ./scheduler.test -test.run TestRequeueByBindFailure
...
grep _test /var/folders/37/ns7gt60104scfm9fvg02p1jh00kjgb/T/go-stress-*
/var/folders/37/ns7gt60104scfm9fvg02p1jh00kjgb/T/go-stress-20230901T124754-2919326582:    queue_test.go:494: Expect pod-1 to be rejected by the bind plugin
/var/folders/37/ns7gt60104scfm9fvg02p1jh00kjgb/T/go-stress-20230901T124754-3259000657:    queue_test.go:494: Expect pod-1 to be rejected by the bind plugin
/var/folders/37/ns7gt60104scfm9fvg02p1jh00kjgb/T/go-stress-20230901T124754-4130805400:    queue_test.go:494: Expect pod-1 to be rejected by the bind plugin
```

### Since when has it been flaking?

Not sure, seeing a lot of retests on pull-kubernetes-integration

Bind logic in scheduler integration tests just changed 3 days ago in https://github.com/kubernetes/kubernetes/pull/114717, not sure if that's related 

### Testgrid link

_No response_

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-integration/1697624577007423488

### Relevant SIG(s)

/sig scheduling
/priority important-soon

cc @alculquicondor @kerthcet

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind flake
/priority important-soon
/triage accepted

#### What this PR does / why we need it:

In the past impl, if the scheduler works very quickly and the Pod scheduling has been done twice by executing L492, 
[L492 `PollUntilContextTimeout`](https://github.com/kubernetes/kubernetes/blob/ef7d4047025d0ce1e6428949b4c77afceedefbf8/test/integration/scheduler/queue_test.go#L492) cannot catch the moment of unschedulable state in pod-1 and this test fails.
This leads the flaky reported in #120363. 

#### Which issue(s) this PR fixes:

Fixes #120363

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
/assign @alculquicondor 

🙏

**Comment by alculquicondor** [comment]
/lgtm
Let's backport to all supported versions.

**Comment by sanposhiho** [comment]
Sure, will open cherry-pick.

File: test/integration/scheduler/queue_test.go [hunk 1]
```diff
@@ -488,16 +498,17 @@ func TestRequeueByBindFailure(t *testing.T) {
...
-		t.Fatalf("Expect pod-1 to be rejected by the bind plugin: %v", err)
+		t.Fatalf("Expect pod-1 to be scheduled by the bind plugin: %v", err)
 	}
 
-	// The pod should be enqueued to activeQ/backoffQ without any event.
-	// The pod should be scheduled in the second binding try.
-	err = wait.PollUntilContextTimeout(ctx, 200*time.Millisecond, wait.ForeverTestTimeout, false, testutils.PodScheduled(cs, ns, pod.Name))
-	if err != nil {
+	// Make sure the first binding trial was failed, and this pod is scheduled at the second trial.
+	if fakeBind.counter != 1 {
```
Comment (kerthcet) [inline test/integration/scheduler/queue_test.go:511]: Yes, this will make the test passed, but I still can't figure out why we failed in the previous PR. Because the pod status's condition is still `false` now.

E.g.
if we apply below codes in the end, we'll pass usually. 🤔
```
	err = wait.PollUntilContextTimeout(ctx, 200*time.Millisecond, wait.ForeverTestTimeout, false, testutils.PodSchedulingError(cs, ns, pod.Name))
	if err != nil {
		t.Fatalf("Expect pod-1 to be rejected by the bind plugin: %v", err)
	}
```

Comment (alculquicondor) [reply test/integration/scheduler/queue_test.go:511]: The PodScheduled condition is set to True by apiserver during Binding
https://github.com/kubernetes/kubernetes/blob/1a1a3d0a87530aea0294ce7ce91a79e7378b95a7/pkg/registry/core/pod/storage/storage.go#L244-L247

Comment (kerthcet) [reply test/integration/scheduler/queue_test.go:511]: Yes, so in this case, the assert should not pass(after binding), but actually, it will. Confused .. 
```
err = wait.PollUntilContextTimeout(ctx, 200*time.Millisecond, wait.ForeverTestTimeout, false, testutils.PodSchedulingError(cs, ns, pod.Name)) 
if err != nil { 
    t.Fatalf("Expect pod-1 to be rejected by the bind plugin: %v", err) 
}
```

Comment (alculquicondor) [reply test/integration/scheduler/queue_test.go:511]: Sometimes we were lucky and would be able to catch the intermediate state where the pod is unschedulable.

Hence why it was flaky.

Comment (kerthcet) [reply test/integration/scheduler/queue_test.go:511]: But even you sleep for a while ,we can still get the unschedulable state. I tested with the code here: dd5ee093cf0646423dd638bbc5088ba51ee822cb
