### PR TITLE
Fix the issue of slow creation of ResourceClaim in specific scenarios

### LINKED ISSUE #135835: Slow pod scheduling when ResourceClaimTemplate is created after pod creation due to exponential backoff
### What happened?

When a Pod references a `ResourceClaimTemplate` (RCT) that doesn't exist at pod creation time, and the RCT is created later, there can be significant delays before the pod gets scheduled.

**Root Cause:**

The ResourceClaim controller in kube-controller-manager uses `AddRateLimited()` when the referenced ResourceClaimTemplate is not found. This applies dual rate limiting:

1. **Exponential backoff (per-item):** `5ms × 2^failures`, capped at 1000 seconds
2. **Token bucket (global):** 10 QPS with 100-token burst

The final delay is `MAX(exponential_delay, token_bucket_delay)`.

**The Problem:**

When the ResourceClaimTemplate is eventually created, there is no mechanism to:
1. Notify the ResourceClaim controller to immediately reprocess waiting pods
2. Move affected pods from `unschedulablePods` queue back to `activeQ` in the scheduler

The pod must wait for its current backoff period to expire before the controller retries, which can be up to 1000 seconds if the pod has already failed multiple times.

### What did you expect to happen?

When a new `ResourceClaimTemplate` is created, pods that were waiting due to the missing template should be processed promptly (within seconds), not after potentially long backoff delays.

### How to reproduce it (as minimally and precisely as possible)?

1. Create a Pod that references a non-existent ResourceClaimTemplate:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test
    image: nginx
    resources:
      claims:
      - name: my-claim
  resourceClaims:
  - name: my-claim
    resourceClaimTemplateName: my-template  # Does not exist yet
```
2. Wait for several retry cycles (observe increasing backoff delays in controller logs)
3. Create the ResourceClaimTemplate:
```yaml
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: my-template
spec:
  spec:
    devices:
      requests:
      - name: device
        deviceClassName: example-class
```

### PR DESCRIPTION
**Pull request by Goend**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
A specific scenario can lead to significantly delayed ResourceClaim creation when the ResourceClaimTemplate is created after the Pod.

#### Which issue(s) this PR is related to:
Fixes https://github.com/kubernetes/kubernetes/issues/135835

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

File: pkg/controller/resourceclaim/controller.go [hunk 1]
```diff
@@ -955,6 +1014,23 @@ func owningPod(claim *resourceapi.ResourceClaim) (string, types.UID) {
...
+	pod, ok := obj.(*v1.Pod)
+	if !ok {
+		return []string{}, nil
+	}
+
+	keySet := sets.NewString()
+
+	for _, podClaim := range pod.Spec.ResourceClaims {
+		if podClaim.ResourceClaimTemplateName != nil {
+			keySet.Insert(*podClaim.ResourceClaimTemplateName)
```
Comment (pohly) [inline pkg/controller/resourceclaim/controller.go]: I think we need to include the namespace here. We could have pod1 in namespace1 and pod2 in namespace2, both waiting for template "foo". When "foo" gets created on namespace1, we only want to work on "pod1".

File: pkg/controller/resourceclaim/controller.go [hunk 2]
```diff
@@ -213,6 +237,41 @@ func NewController(
...
+	template, ok := obj.(*resourceapi.ResourceClaimTemplate)
+	if !ok {
+		// Not a template,return
+		logger.Error(nil, "enqueueResourceClaimTemplate called for unexpected object", "type", fmt.Sprintf("%T", obj))
+		return
+	}
+	if deleted {
+		// if template is deleted, we don't need to do anything
+		logger.V(6).Info("template got deleted", "template-name", template.Name)
+		return
```
Comment (pohly) [inline pkg/controller/resourceclaim/controller.go:247]: Instead of doing nothing for deletion, we can simply not call enqueueResourceClaimTemplate at all for delete events.

Updates are different: perhaps something was wrong with the old one such that creating the ResourceClaim failed, so it makes sense to try again immediately.

**Review by pohly — CHANGES_REQUESTED** [review]
Overall this looks good, thanks!

Can you add unit tests?

File: pkg/controller/resourceclaim/controller.go [hunk 3]
```diff
@@ -56,6 +57,9 @@ const (
 	// podResourceClaimIndex is the lookup name for the index function which indexes by pod ResourceClaim templates.
```
Comment (mounchin) [inline pkg/controller/resourceclaim/controller.go]: nit: should this be just `indexes by pod ResourceClaim`

File: pkg/controller/resourceclaim/controller.go [hunk 4]
```diff
@@ -213,6 +237,41 @@ func NewController(
...
+	objects, err := ec.podIndexer.ByIndex(podResourceClaimTemplateIndexKey, template.Name)
+	if err != nil {
+		logger.Error(err, "unable to list pods for claim template", "template-name", template.Name)
+		return
+	}
+	if len(objects) == 0 {
+		logger.V(6).Info("unrelated to any known pod", "template-name", template.Name)
+		return
+	}
+
```
Comment (mounchin) [inline pkg/controller/resourceclaim/controller.go:262]: Can we also add a log here to indicate that pods(also counts) are being enqueued due to this template add/update event

File: pkg/controller/resourceclaim/controller.go (hunk 1 above)
Comment (Goend) [reply pkg/controller/resourceclaim/controller.go]: Fixed. To avoid cross-namespace issues, the index has been updated to include the namespace for distinction.

File: pkg/controller/resourceclaim/controller.go (hunk 2 above)
Comment (Goend) [reply pkg/controller/resourceclaim/controller.go:247]: Removed.

File: pkg/controller/resourceclaim/controller.go (hunk 3 above)
Comment (Goend) [reply pkg/controller/resourceclaim/controller.go]: Fixed.

File: pkg/controller/resourceclaim/controller.go (hunk 4 above)
Comment (Goend) [reply pkg/controller/resourceclaim/controller.go:262]: Add logging when pods are re-enqueued due to template additions or updates.

File: pkg/controller/resourceclaim/controller.go [hunk 5]
```diff
@@ -213,6 +236,43 @@ func NewController(
...
 }
 
+func (ec *Controller) enqueueResourceClaimTemplate(logger klog.Logger, obj interface{}) {
+	if d, ok := obj.(cache.DeletedFinalStateUnknown); ok {
+		obj = d.Obj
+	}
+	template, ok := obj.(*resourceapi.ResourceClaimTemplate)
+	if !ok {
+		// Not a template,return
+		logger.Error(nil, "enqueueResourceClaimTemplate called for unexpected object", "type", fmt.Sprintf("%T", obj))
```
Comment (pohly) [inline pkg/controller/resourceclaim/controller.go]:
```suggestion
		runtime.HandlerErrorWithLogger(logger, nil, "enqueueResourceClaimTemplate called for unexpected object", "type", fmt.Sprintf("%T", obj))
```

master/contributors/devel/sig-instrumentation/logging.md#what-method-to-use

File: pkg/controller/resourceclaim/controller.go [hunk 6]
```diff
@@ -213,6 +236,43 @@ func NewController(
...
+		return
+	}
+
+	logger.V(6).Info("template add or updated", "template-namespace", template.Namespace, "template-name", template.Name)
```
Comment (pohly) [inline pkg/controller/resourceclaim/controller.go]:
```suggestion
	logger.V(6).Info("template added or updated", "template-namespace", template.Namespace, "template-name", template.Name)
```

File: pkg/controller/resourceclaim/controller.go [hunk 7]
```diff
@@ -213,6 +236,43 @@ func NewController(
...
+
+	//enqueue all pods with this template name
+	objects, err := ec.podIndexer.ByIndex(podResourceClaimTemplateIndexKey, fmt.Sprintf("%s/%s", template.Namespace, template.Name))
+	if err != nil {
+		logger.Error(err, "unable to list pods for claim template", "template-namespace", template.Namespace, "template-name", template.Name)
```
Comment (pohly) [inline pkg/controller/resourceclaim/controller.go]:
```suggestion
		runtime.HandleErrorWithLogger(logger, err, "unable to list pods for claim template", "resourceClaimTemplate", klog.KObj(template))
```

Please update all log calls where "template-namespace" and "template-name" are separate, see below, I've only made that change here.

File: pkg/controller/resourceclaim/controller.go [hunk 8]
```diff
@@ -213,6 +236,43 @@ func NewController(
...
+	if len(objects) == 0 {
+		logger.V(6).Info("unrelated to any known pod", "template-namespace", template.Namespace, "template-name", template.Name)
+		return
+	}
+
+	for _, object := range objects {
+		pod, ok1 := object.(*v1.Pod)
+		if !ok1 {
+			// Not a pod?!
+			logger.Error(nil, "enqueueResourceClaimTemplate called for unexpected object", "type", fmt.Sprintf("%T", obj))
```
Comment (pohly) [inline pkg/controller/resourceclaim/controller.go]: HandleErrorWithLogger again

File: pkg/controller/resourceclaim/controller.go [hunk 9]
```diff
@@ -213,6 +236,43 @@ func NewController(
...
+			return
+		}
+		logger.V(4).Info("some pods are being enqueued due to this template add/update", "template-namespace", template.Namespace, "template-name", template.Name, "pod-namespace", pod.Namespace, "pod-name", pod.Name)
+		ec.enqueuePod(logger, object, false)
```
Comment (pohly) [inline pkg/controller/resourceclaim/controller.go:275]: klog.KObj again for "pod"

File: pkg/controller/resourceclaim/controller_test.go [hunk 10]
```diff
@@ -498,6 +499,143 @@ func TestSyncHandler(t *testing.T) {
...
+							break
+						}
+					}
+				}
+			}
+			g.Expect(found).To(gomega.BeTrue(), "should find a pod with template %s in index for key %s", templateName, src)
+		}
+	}
+
+	var TmpNamespace string = "tmp"
```
Comment (pohly) [inline pkg/controller/resourceclaim/controller_test.go]:
```suggestion
	tmpNamespace := "tmp"
```

**Review by pohly — CHANGES_REQUESTED** [review]

File: pkg/controller/resourceclaim/controller.go (hunk 5 above)
Comment (Goend) [reply pkg/controller/resourceclaim/controller.go]: Fixed.

File: pkg/controller/resourceclaim/controller.go (hunk 6 above)
Comment (Goend) [reply pkg/controller/resourceclaim/controller.go]: Fixed.

File: pkg/controller/resourceclaim/controller.go (hunk 7 above)
Comment (Goend) [reply pkg/controller/resourceclaim/controller.go]: All Fixed.

File: pkg/controller/resourceclaim/controller.go (hunk 8 above)
Comment (Goend) [reply pkg/controller/resourceclaim/controller.go]: Fixed.

File: pkg/controller/resourceclaim/controller.go (hunk 9 above)
Comment (Goend) [reply pkg/controller/resourceclaim/controller.go:275]: has changed.

File: pkg/controller/resourceclaim/controller_test.go (hunk 10 above)
Comment (Goend) [reply pkg/controller/resourceclaim/controller_test.go]: has changed.

File: pkg/controller/resourceclaim/controller.go [hunk 11]
```diff
@@ -213,6 +236,47 @@ func NewController(
...
+	logger.V(6).Info("template added or updated", "resourceClaimTemplate", klog.KObj(template))
+
+	// Enqueue all pods with this template name
+	objects, err := ec.podIndexer.ByIndex(podResourceClaimTemplateIndexKey, fmt.Sprintf("%s/%s", template.Namespace, template.Name))
+	if err != nil {
+		runtime.HandleErrorWithLogger(logger, err, "unable to list pods for claim template", "resourceClaimTemplate", klog.KObj(template))
+		return
+	}
+	if len(objects) == 0 {
+		logger.V(6).Info("unrelated to any known pod", "resourceClaimTemplate", klog.KObj(template))
```
Comment (pohly) [inline pkg/controller/resourceclaim/controller.go]:
```suggestion
		logger.V(6).Info("ResourceClaimTemplate change unrelated to any known pod", "resourceClaimTemplate", klog.KObj(template))
```

File: pkg/controller/resourceclaim/controller.go [hunk 12]
```diff
@@ -213,6 +236,47 @@ func NewController(
...
+
+	for _, object := range objects {
+		pod, ok1 := object.(*v1.Pod)
+		if !ok1 {
+			// Not a pod?!
+			runtime.HandleErrorWithLogger(logger, nil, "enqueueResourceClaimTemplate called for unexpected object", "type", fmt.Sprintf("%T", obj))
+			return
+		}
+		logger.V(4).Info(
+			"some pods are being enqueued due to this template add/update",
```
Comment (pohly) [inline pkg/controller/resourceclaim/controller.go]:
```suggestion
			"Enqueuing pod due to ResourceClaim change",
```

Logging guidelines call for upper case at the start of a log message.

**Review by pohly — CHANGES_REQUESTED** [review]
Some more nits after another pass.

Can you squash into a single commit with `git rebase -i --keep-base`? I prefer force-push updates of a PR over adding "fix" commits.

File: pkg/controller/resourceclaim/controller.go (hunk 11 above)
Comment (Goend) [reply pkg/controller/resourceclaim/controller.go]: Fixed.
The inconsistent logging style was a problem throughout the entire file. Due to this, I expanded the scope of the modifications.

File: pkg/controller/resourceclaim/controller.go (hunk 12 above)
Comment (Goend) [reply pkg/controller/resourceclaim/controller.go]: Fixed.

File: pkg/controller/resourceclaim/controller.go (hunk 11 above)
Comment (pohly) [reply pkg/controller/resourceclaim/controller.go]: That's okay, thanks.

**Review by pohly — COMMENTED** [review]
/lgtm
/approve
