### PR TITLE
Managing nil pointer in VolumeManager

### LINKED ISSUE #108063: standalone kubelet panic because of nil pointer in VolumeManager
### What happened?

I tried to run a standalone kubelet (without kube-apiserver, so no kubeClient in kubelet), but there is a panic "invalid memory address or nil pointer dereference"

The corresponding logs:

```text
E0211 15:50:57.552748  794906 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 60 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3bd69e0, 0x72c4480})
	/home/xiejinwei/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00020ccc0})
	/home/xiejinwei/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
panic({0x3bd69e0, 0x72c4480})
	/home/xiejinwei/.gvm/gos/go1.17/src/runtime/panic.go:1038 +0x215
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).updateDevicePath(0xc00020ccc0, 0x24)
	/home/xiejinwei/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:590 +0x40
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).updateStates(0xc00020ccc0, 0xc00185fc68)
	/home/xiejinwei/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:621 +0x3e
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).syncStates(0xc00020ccc0)
	/home/xiejinwei/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:425 +0x1a5
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).sync(0x0)
	/home/xiejinwei/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:339 +0x50
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).reconciliationLoopFunc.func1()
	/home/xiejinwei/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:158 +0xd6
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000ee6f00)
	/home/xiejinwei/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x67
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x410c67, {0x4af7180, 0xc00034a960}, 0x1, 0xc00005e4e0)
	/home/xiejinwei/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00020ccc0, 0x5f5e100, 0x0, 0x0, 0x442ea5)
	/home/xiejinwei/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/xiejinwei/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).Run(0xc00020ccc0, 0x0)
	/home/xiejinwei/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:146 +0x45
created by k8s.io/kubernetes/pkg/kubelet/volumemanager.(*volumeManager).Run
	/home/xiejinwei/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/volume_manager.go:292 +0x35f

```

### What did you expect to happen?

I expect standalone kubelet to run without panic.

### How can we reproduce it (as minimally and precisely as possible)?

Run a standalone kubelet

### Anything else we need to know?

I think this is a problem of `kubelet` passing `kubeClient` into `VolumeManager` without checking if it is nil.

Related code snippet:

+ In `pkg/kubelet/kubelet.go`, `NewMainKubelet()` passed the nil `kubeClient` into `NewVolumeManager()`:

  https://github.com/kubernetes/kubernetes/blob/559b798e25c8f8a77d380af27e696f3a68341d7e/pkg/kubelet/kubelet.go#L799-L805

+ In `pkg/kubelet/volumemanager/volume_manager.go`, `NewVolumeManager()` passed the nil `kubeClient` into `reconciler`:
   https://github.com/kubernetes/kubernetes/blob/559b798e25c8f8a77d380af27e696f3a68341d7e/pkg/kubelet/volumemanager/volume_manager.go#L218-L220

+ In `pkg/kubelet/volumemanager/reconciler/reconciler.go`, `reconciler` used the nil `kubeClient` without checking:
  https://github.com/kubernetes/kubernetes/blob/a753dace544bbc64b4ea56c7e0adab174dbda62d/pkg/kubelet/volumemanager/reconciler/reconciler.go#L589-L590

### Kubernetes version

<details>

I'm only running kubelet, the kubelet version is `Kubernetes v1.22.7-rc.0.17+559b798e25c8f8-dirty
`

</details>

### Cloud provider

<details>

Not using cloud provider

</details>

### OS version

<details>

```console
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

</details>

### Install tools

<details>

I installed with source code, the tag is `release-1.22`

```console
git clone https://github.com/kubernetes/kubernetes.git
git fetch origin release-1.22
git checkout release-1.22
make WHAT=cmd/kubelet
cp ./_output/local/bin/linux/amd64/kubelet /usr/local/bin/kubelet
```

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

containerd 1.4.12

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by NikhilSharmaWe**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Standalone kubelet panics because of nil pointer in VolumeManager because of kubeClient's nil value. This PR works on it by changing the behavior of kubelet.
#### Which issue(s) this PR fixes:

Fixes #108063

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by NikhilSharmaWe** [comment]
@aojea Could you please review the change made for dealing with nil pointer in this case.

**Comment by NikhilSharmaWe** [comment]
@aojea Could you please review the change made for dealing with nil pointer in this case.

**Comment by NikhilSharmaWe** [comment]
@aojea Could you please review the change made for dealing with nil pointer in this case.

**Comment by aojea** [comment]
> @aojea Could you please review the change made for dealing with nil pointer in this case.

I'm not familiar with this logic and how kubelet should work on this case in standalone mode , this should be reviewed by Sig storage and node folks 
/Sig node
/Sig storage

File: pkg/kubelet/volumemanager/reconciler/reconciler.go [hunk 1]
```diff
@@ -604,7 +604,9 @@ func getDeviceMountPath(volume *reconstructedVolume) (string, error) {
 
 func (rc *reconciler) updateStates(volumesNeedUpdate map[v1.UniqueVolumeName]*reconstructedVolume) error {
 	// Get the node status to retrieve volume device path information.
-	rc.updateDevicePath(volumesNeedUpdate)
+	if rc.kubeClient != nil {
+		rc.updateDevicePath(volumesNeedUpdate)
+	}
```
Comment (gnufied) [inline pkg/kubelet/volumemanager/reconciler/reconciler.go:609]: I am not 100% sure if it is entirely safe to skip updating node objects silently and still do rest of reconstruction. We need to rethink about what volume-manager features are supposed to be working in standalone mode. Please see my comment - https://github.com/kubernetes/kubernetes/issues/108063#issuecomment-1063936254

Comment (NikhilSharmaWe) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go:609]: @gnufied
Does this statement
`If Kubelet is running in standalone mode, there is no apiserver and kubeClient should be nil.` of [this](https://github.com/kubernetes/kubernetes/issues/108063#issuecomment-1056064383) comment give the answer of  your question about **what volume-manager features are supposed to be working in standalone mode ?**

Comment (gnufied) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go:609]: It does not. I am waiting for some clarification from sig-node about, which volume features are available in standalone mode. Without understanding that - crashing the kubelet is better than silently incorrectly accounting volumes that are in-use by node.

**Comment by NikhilSharmaWe** [comment]
@gnufied Are there any updates regarding these changes.

**Comment by NikhilSharmaWe** [comment]
@gnufied Couple of tests are failing. What could be the reason behind it ?

**Comment by NikhilSharmaWe** [comment]
@gnufied Again a test is failing.

**Comment by NikhilSharmaWe** [comment]
@pacoxu Could you please take a look. The PR is automatically retesting when the last test fails.
