### PR TITLE
kubelet: assume that swap is disabled when /proc/swaps does not exist

### LINKED ISSUE #93913: Kubelet doesn't start on Linux kernels with CONFIG_SWAP=n
**What happened**:
Kubelet doesn't start during `kubeadm init`, journalctl shows:
`kubelet[17870]: F0812 02:15:15.717137   17870 server.go:274] failed to run Kubelet: open /proc/swaps: no such file or directory`

**What you expected to happen**:
Kubelet correctly identifies absence of `/proc/swaps` as "no swap present", kubelet service starts and `kubeadm init` can finish.

**How to reproduce it (as minimally and precisely as possible)**:
Build a Linux kernel with `CONFIG_SWAP=y`, install kubeadm, kubelet and try `kubeadm init`.

**Anything else we need to know?**:
No registered swap devices *or* a kernel without swap enabled both means that there is no swap space present. Kubectl successfully checks for the former case but throws an error on the later.
Failure to open `/proc/swaps` means *no swap*.

**Environment**:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}`
- Hardware configuration: `on-premises`
- OS: `Debian GNU/Linux bullseye/sid`
- Kernel: `Linux 5.8.0 monolithic kernel with CONFIG_SWAP=n`
- Install tools: `kubeadm`

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
kubelet: assume that swap is disabled when `/proc/swaps` does not exist

**Which issue(s) this PR fixes**:

Fixes #93913

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubelet: assume that swap is disabled when `/proc/swaps` does not exist
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/kubelet/cm/container_manager_linux.go [hunk 1]
```diff
@@ -216,17 +216,23 @@ func NewContainerManager(mountUtil mount.Interface, cadvisorInterface cadvisor.I
 
 	if failSwapOn {
 		// Check whether swap is enabled. The Kubelet does not support running with swap enabled.
-		swapData, err := ioutil.ReadFile("/proc/swaps")
+		swapFile := "/proc/swaps"
```
Comment (odinuge) [inline pkg/kubelet/cm/container_manager_linux.go:219]: You could maybe make this a constant and move it to the top of the file, but that is up to you.

**Review by odinuge — APPROVED** [review]
This looks good to me! Thanks!

/lgtm
/priority backlog
/retest

File: pkg/kubelet/cm/container_manager_linux.go (hunk 1 above)
Comment (SataQiu) [reply pkg/kubelet/cm/container_manager_linux.go:219]: Thanks @odinuge !  Your suggestion is good! 
But since it is only used in this function, so I prefer to keep it that way for now.

**Comment by SataQiu** [comment]
Hi @dims!  It looks like this PR has been approved. Can you help add a milestone label for this PR?
