### PR TITLE
Explicitly add iptables rule to allow healthcheck nodeport

### LINKED ISSUE #97225: healthCheckNodePort depends on the default iptables chain policy to be accessible externally
**What happened**:
When the default policy for filter table INPUT chain is DROP, external query on Service's "spec.healthCheckNodePort" is dropped.

**What you expected to happen**:
kube-proxy should manage iptable rules for "spec.healthCheckNodePort" similar to what it does for "NodePort". It also should ensure once "spec.healthCheckNodePport" is allocated, it's accessible regardless of the default policy on chains.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Service with "spec.externalTrafficPolicy" == "Local";
2. manually set the filter table INPUT chain default policy to "DROP"(this currently depends on the Node Image);
```
iptables -t filter -P INPUT DROP
```
3. curl the "spec.healthCheckNodePort" from any other host;

**Anything else we need to know?**:
No.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1+vmware.2", GitCommit:"9d9a7637ad75801f9296a1cebe63120c020305d4", GitTreeState:"clean", BuildDate:"2020-09-22T22:55:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="VMware Photon OS"
VERSION="3.0"
ID=photon
VERSION_ID=3.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
```
- Kernel (e.g. `uname -a`):
``` 
Linux tkg-cluster-wc-743-md-0-8bdb9cc86-z7qwd 4.19.145-2.ph3 #1-photon SMP Wed Sep 23 02:26:04 UTC 2020 x86_64 GNU/Linux
```
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by hanlins**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Explicitly add iptables rule to expose healthcheck nodeport in `filter` table.

**Which issue(s) this PR fixes**:

Fixes #97225 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fixed a bug that on k8s nodes, when the policy of INPUT chain in filter table is not ACCEPT, healthcheck nodeport would not work.
Added iptables rules to allow healthcheck nodeport traffic.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
As the [document](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip) says
> It only has an effect when type is set to LoadBalancer and externalTrafficPolicy is set to Local.

Need we check this before adding iptables rule ? 
(Just a question, I'm not quite sure about the behavior here. 😄)

**Comment by hanlins** [comment]
Hi @pacoxu, api-server will ensure `healthCheckNodePort` field is only set when the service is of type `LoadBalancer` and `externalTrafficPolicy` is `Local`. This is a spec I'm using:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment3
  labels:
    app: nginx3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx3
        #image: nginx:1.14.2
        image: us.gcr.io/google-containers/nginx
        ports:
        - containerPort: 80
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx3
spec:
  type: NodePort
  healthCheckNodePort: 30010
  externalTrafficPolicy: Local
  selector:
    app: nginx3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
```
And this is the error I got:
```
➜  ~ kubectl apply -f svc3.yaml
deployment.apps/nginx-deployment3 created
The Service "nginx3" is invalid: spec.healthCheckNodePort: Invalid value: 30010: HealthCheckNodePort can only be set on LoadBalancer service with ExternalTrafficPolicy=Local
```
That said I think we can safely assume that LB type and external traffic policy are set correctly if `healthCheckNodePort` is not zero.

**Comment by hanlins** [comment]
Hi @andrewsykim, in `filter` table here're the k8s related chains:
```
:KUBE-EXTERNAL-SERVICES - [0:0]
:KUBE-FIREWALL - [0:0]
:KUBE-FORWARD - [0:0]
:KUBE-KUBELET-CANARY - [0:0]
:KUBE-PROXY-CANARY - [0:0]
:KUBE-SERVICES - [0:0]
```
currently, I'm adding rules that accept inbound health check traffic in `KUBE-EXTERNAL-SERVICES` chain, which might not be appropriate. Which chain is suitable for the rule that accepts health check traffic? Or do we need to add a new chain in that table?

File: pkg/proxy/iptables/proxier.go [hunk 1]
```diff
@@ -1328,6 +1332,36 @@ func (proxier *Proxier) syncProxyRules() {
 			}
 		}
 
+		// Capture healthCheckNodePorts.
+		if svcInfo.HealthCheckNodePort() != 0 {
+			lps := getLocalPorts("tcp", "healthCheckNodePort", svcInfo.HealthCheckNodePort())
```
Comment (andrewsykim) [inline pkg/proxy/iptables/proxier.go:1337]: I don't think we need the OpenPortLocal logic between 1337 - 1352, the health check server binds to that port already which would conflict.

File: pkg/proxy/iptables/proxier.go [hunk 2]
```diff
@@ -1328,6 +1332,36 @@ func (proxier *Proxier) syncProxyRules() {
...
+						continue
+					}
+					replacementPortsMap[lp] = socket
+				}
+			}
+
+			// no matter if node has local endpoints, healthCheckEndpoints
+			// need to be exposed
+			writeLine(proxier.filterRules,
+				"-A", string(kubeExternalServicesChain),
```
Comment (andrewsykim) [inline pkg/proxy/iptables/proxier.go:1357]: KUBE-NODE-PORTS might make more sense here actually because healthCheckNodePort is technically still a "node port"

**Review by andrewsykim — COMMENTED** [review]
@hanlins can you also update IPVS proxier please? Similar iptables rules allowing the health check noder port should be sufficient

File: pkg/proxy/iptables/proxier.go (hunk 2 above)
Comment (hanlins) [reply pkg/proxy/iptables/proxier.go]: Yeah originally there's no `KUBE-NODE-PORT` chain in the `filter` table for both `iptables` and `ipvs` versions of the `kube-proxy`. Just FYI that this change will add the node port chain to the `filter` table.

File: pkg/proxy/iptables/proxier.go [hunk 3]
```diff
@@ -1337,6 +1337,19 @@ func (proxier *Proxier) syncProxyRules() {
 			}
 		}
 
+		// Capture healthCheckNodePorts.
+		if svcInfo.HealthCheckNodePort() != 0 {
+			// no matter if node has local endpoints, healthCheckEndpoints
+			// need to be exposed
```
[the remark this answers is not in the document]
Comment (hanlins) [reply pkg/proxy/iptables/proxier.go:1343]: good catch!

[the remark this answers is not in the document]
Comment (hanlins) [reply pkg/proxy/iptables/proxier.go:1343]: btw do we need to also filter based on the connection state? Like adding `-m conntrack –ctstate ESTABLISHED,RELATED,NEW`?

**Comment by hanlins** [comment]
@andrewsykim validated for both `ipvs` and `iptables` mode and worked, PTAL.

File: pkg/proxy/iptables/proxier.go (hunk 1 above)
Comment (hanlins) [reply pkg/proxy/iptables/proxier.go]: Removed, thanks.

File: pkg/proxy/iptables/proxier_test.go [hunk 4]
```diff
@@ -913,6 +913,50 @@ func TestNodePort(t *testing.T) {
 	}
 }
 
+func TestHealthCheckNodePort(t *testing.T) {
```
Comment (jayunit100) [inline pkg/proxy/iptables/proxier_test.go:916]: hiya @hanlins , looking at this unit test,  do we also need a `sig-network`  E2E for this? what E2Es break if this is not working ?

**Comment by jayunit100** [comment]
Youll need to rebase to 1 commit eventually, just Fyi :)

File: pkg/proxy/iptables/proxier_test.go (hunk 4 above)
Comment (hanlins) [reply pkg/proxy/iptables/proxier_test.go:916]: Oh true. I was thinking about it early today but don't know if there's a way to change the e2e VM settings? My concern is if I just modify the `INPUT` chain policy to `DROP` then we might lose ssh connection to that VM instantly and failed the test (and lose the VMs, maybe other risks). Also I would say if we change the chain policy to `DROP` then local pod to pod VM will break since there's no rule to allow traffic from/to `lo` interface. Personally that seems to be a bigger topic than just focusing on fixing the healthcheck node port issue, maybe we can create new issues to track them? Maybe one for adding a rule to enable traffic to/from `lo` interface, and the other to address the e2e test coverage, what's ur take? 😆

File: pkg/proxy/iptables/proxier_test.go [hunk 5]
```diff
@@ -2594,6 +2638,7 @@ func TestEndpointSliceE2E(t *testing.T) {
 :KUBE-SERVICES - [0:0]
 :KUBE-EXTERNAL-SERVICES - [0:0]
 :KUBE-FORWARD - [0:0]
+:KUBE-NODEPORTS - [0:0]
```
Comment (andrewsykim) [inline pkg/proxy/iptables/proxier_test.go:2641]: can we add a test like `TestEndpointSliceE2E` but with a Service with health check node ports? Will help compare the whole rule set

Comment (hanlins) [reply pkg/proxy/iptables/proxier_test.go:2641]: Good call, will do that.

File: pkg/proxy/iptables/proxier_test.go [hunk 6]
```diff
@@ -2731,4 +2731,66 @@ COMMIT
...
 }
 
+func TestHealthCheckNodePortE2E(t *testing.T) {
+	expectedIPTables := `*filter
+:KUBE-SERVICES - [0:0]
+:KUBE-EXTERNAL-SERVICES - [0:0]
+:KUBE-FORWARD - [0:0]
+:KUBE-NODEPORTS - [0:0]
+-A KUBE-SERVICES -m comment --comment "ns1/svc1 has no endpoints" -m tcp -p tcp -d 172.20.1.1/32 --dport 0 -j REJECT
+-A KUBE-NODEPORTS -m comment --comment "ns1/svc1 health check node port" -m tcp -p tcp --dport %d -j ACCEPT
```
Comment (andrewsykim) [inline pkg/proxy/iptables/proxier_test.go:2741]: This %d should be `30000`?

Comment (hanlins) [reply pkg/proxy/iptables/proxier_test.go]: Yeah maybe it's better just to check the raw iptables without using sprintf. Fixed.

File: pkg/proxy/iptables/proxier_test.go (hunk 4 above)
Comment (jayunit100) [reply pkg/proxy/iptables/proxier_test.go:916]: no need to make an e2e for it, i guess all that matters is... knowing which of the `sig-network` e2e's we can use to detect this regression?  

i bet  theres something that requires nodeport healthchecks (i.e. maybe in test/e2e/network/services.go) which demonstrates this bug ?

Comment (andrewsykim) [reply pkg/proxy/iptables/proxier_test.go:916]: We have quite a few e2es already on health check node port because it's required for any Service LB w/ externalTrafficPolicy=Local. The tricky part is testing this on a node using default `INPUT` policy of `DROP`.

File: pkg/proxy/iptables/proxier.go [hunk 7]
```diff
@@ -395,6 +395,7 @@ type iptablesJumpChain struct {
 var iptablesJumpChains = []iptablesJumpChain{
 	{utiliptables.TableFilter, kubeExternalServicesChain, utiliptables.ChainInput, "kubernetes externally-visible service portals", []string{"-m", "conntrack", "--ctstate", "NEW"}},
 	{utiliptables.TableFilter, kubeExternalServicesChain, utiliptables.ChainForward, "kubernetes externally-visible service portals", []string{"-m", "conntrack", "--ctstate", "NEW"}},
+	{utiliptables.TableFilter, kubeNodePortsChain, utiliptables.ChainInput, "kubernetes health check service portals", nil},
```
Comment (andrewsykim) [inline pkg/proxy/iptables/proxier.go:398]: Wondering if this should actually have `-m conntrack --ctstate NEW` since we only expect the incoming connections from external :thinking:

File: pkg/proxy/iptables/proxier_test.go [hunk 8]
```diff
@@ -2686,4 +2731,60 @@ COMMIT
 	assert.NotEqual(t, expectedIPTablesWithSlice, fp.iptablesData.String())
 }
 
+func TestHealthCheckNodePortE2E(t *testing.T) {
+	expectedIPTables := `*filter
+:KUBE-SERVICES - [0:0]
+:KUBE-EXTERNAL-SERVICES - [0:0]
+:KUBE-FORWARD - [0:0]
+:KUBE-NODEPORTS - [0:0]
+-A KUBE-SERVICES -m comment --comment "ns1/svc1 has no endpoints" -m tcp -p tcp -d 172.20.1.1/32 --dport 0 -j REJECT
```
Comment (andrewsykim) [inline pkg/proxy/iptables/proxier_test.go:2740]: Can we update this test to have actual endpoints?

File: pkg/proxy/iptables/proxier_test.go [hunk 9]
```diff
@@ -2686,4 +2731,60 @@ COMMIT
...
+
+	serviceName := "svc1"
+	namespaceName := "ns1"
+
+	svc := &v1.Service{
+		ObjectMeta: metav1.ObjectMeta{Name: serviceName, Namespace: namespaceName},
+		Spec: v1.ServiceSpec{
+			ClusterIP:             "172.20.1.1",
+			Selector:              map[string]string{"foo": "bar"},
+			Ports:                 []v1.ServicePort{{Name: "", TargetPort: intstr.FromInt(80), Protocol: v1.ProtocolTCP}},
```
Comment (andrewsykim) [inline pkg/proxy/iptables/proxier_test.go:2775]: add a node port here

**Review by andrewsykim — COMMENTED** [review]
minor comments on testing but I think this is looking good, could use a second review from other folks though. Maybe @aojea or @danwinship?

/assign
/triage accepted
/priority important-soon

File: pkg/proxy/iptables/proxier.go (hunk 7 above)
Comment (hanlins) [reply pkg/proxy/iptables/proxier.go:398]: I tried `--ctstate NEW` last week but it didn't work. I could try adding `ESTABLISHED` here.

Comment (andrewsykim) [reply pkg/proxy/iptables/proxier.go:398]: good point, we would need ESTABLISHED as well. let's leave it as-is for now

Comment (hanlins) [reply pkg/proxy/iptables/proxier.go:398]: Checked offline, for now just skip `ctstate` matching. Once we have thoroughly tested `kubeExternalServicesChain` and found the traffic is not working, then my take would be adding a dedicated rule in `INPUT` chain (or in `KUBE-SERVICES`) to accept the traffic in `ESTABLISHED` state.

File: pkg/proxy/iptables/proxier_test.go (hunk 8 above)
Comment (hanlins) [reply pkg/proxy/iptables/proxier_test.go]: Done

File: pkg/proxy/iptables/proxier_test.go (hunk 9 above)
Comment (hanlins) [reply pkg/proxy/iptables/proxier_test.go]: Done

File: pkg/proxy/iptables/proxier.go [hunk 10]
```diff
@@ -1337,6 +1338,19 @@ func (proxier *Proxier) syncProxyRules() {
 			}
 		}
 
+		// Capture healthCheckNodePorts.
+		if svcInfo.HealthCheckNodePort() != 0 {
+			// no matter if node has local endpoints, healthCheckEndpoints
```
Comment (andrewsykim) [inline pkg/proxy/iptables/proxier.go:1343]: healthCheckEndpoints -> healthCheckNodePorts

File: pkg/proxy/iptables/proxier.go [hunk 11]
```diff
@@ -1619,7 +1633,7 @@ func (proxier *Proxier) syncProxyRules() {
 
 	// Close old local ports and save new ones.
 	for k, v := range proxier.portsMap {
-		if replacementPortsMap[k] == nil {
+		if v != nil && replacementPortsMap[k] == nil {
```
Comment (andrewsykim) [inline pkg/proxy/iptables/proxier.go:1636]: was this causing a panic?

Comment (hanlins) [reply pkg/proxy/iptables/proxier.go:1636]: Yes, if add the `nodePort` in svc spec in that unit test.

Comment (hanlins) [reply pkg/proxy/iptables/proxier.go:1636]: Tried adding `nodePort` in `TestEndpointSliceE2E`, same panic.

File: pkg/proxy/iptables/proxier.go (hunk 10 above)
Comment (hanlins) [reply pkg/proxy/iptables/proxier.go:1343]: Thanks! Fixed.

File: pkg/proxy/iptables/proxier.go (hunk 11 above)
Comment (andrewsykim) [reply pkg/proxy/iptables/proxier.go:1636]: that makes sense, can you swap the check:
```
if replacementPortsMap[k] == nil && v != nil {
```

and put this change in a separate commit

Comment (hanlins) [reply pkg/proxy/iptables/proxier.go]: Oh fixed. Put it as the first commit and rebased the changes on top of that.

**Review by andrewsykim — COMMENTED** [review]
When a node's default `INPUT` chain policy is `DROP`, `nodePorts` work but `healthCheckNodePorts` doesn't so this feels like the right fix. I do wonder though where else in the iptable rules we may have missed corner cases when `DROP` is the default chain policy. It feels like most of what we have tested today assumes `ACCEPT` is always the default.  Something to dig into in follow-up PRs.

/approve
/lgtm

Thanks @hanlins

File: pkg/proxy/iptables/proxier.go [hunk 12]
```diff
@@ -1619,7 +1619,7 @@ func (proxier *Proxier) syncProxyRules() {
 
 	// Close old local ports and save new ones.
 	for k, v := range proxier.portsMap {
-		if replacementPortsMap[k] == nil {
+		if replacementPortsMap[k] == nil && v != nil {
```
Comment (aojea) [inline pkg/proxy/iptables/proxier.go:1636]: is this related to the PR?

Comment (hanlins) [reply pkg/proxy/iptables/proxier.go:1636]: I don't think so. With or without the PR, we could encounter panic here if we specify `nodePort` in unit tests, so I think we could handle it in the defensive way.

Comment (aojea) [reply pkg/proxy/iptables/proxier.go:1636]: :thinking: 
https://stackoverflow.com/a/42239079/7794348
> 
In Go, however, the function to be called by the Expression.Name() syntax is entirely determined by the type of Expression and not by the particular run-time value of that expression, including nil. In this manner, the invocation of a method on a nil pointer of a specific type has a clear and logical meaning. Those familiar with vtable[] implementations will find this odd at first, yet, when thinking of methods this way, it is even simpler and makes sense. Think of:

Comment (hanlins) [reply pkg/proxy/iptables/proxier.go:1636]: Well I think the root cause was [here](https://github.com/kubernetes/kubernetes/blob/v1.21.0-alpha.2/pkg/proxy/iptables/proxier_test.go#L464-L467):
```golang
// OpenLocalPort fakes out the listen() and bind() used by syncProxyRules
// to lock a local port.
func (f *fakePortOpener) OpenLocalPort(lp *utilproxy.LocalPort, isIPv6 bool) (utilproxy.Closeable, error) {
	f.openPorts = append(f.openPorts, lp)
	return nil, nil
}
```
The `fakePortOpener` in our test is returning `nil` for both `Closeable` and `error`, where our code made an assumption that if `error` is `nil`, then we should be able to close the `Closeable`. I can revert that change and just add a fake `Closeable` instead of returning nil to keep that assumption.

Comment (aojea) [reply pkg/proxy/iptables/proxier.go]: cool, you solved 2 issues in one
Thanks

**Comment by aojea** [comment]
@hanlins there are 3 xlock files in the PR, I think that are test leftovers

**Comment by aojea** [comment]
lgtm once the 3 files added are removed
```
 0  pkg/util/iptables/xtables-872506631.lock 
Viewed
Empty file.
 0  pkg/util/iptables/xtables-872723334.lock 
Viewed
Empty file.
 0  pkg/util/iptables/xtables-873186842.lock 
Viewed
```

**Comment by hanlins** [comment]
> @hanlins there are 3 xlock files in the PR, I think that are test leftovers
> 
> ```
> pkg/util/iptables/xtables-872506631.lock
> ```

My bad, removed.

**Comment by maplain** [comment]
LGTM and thx @hanlins for adding the missing piece!

**Comment by aojea** [comment]
/lgtm
Thanks

**Comment by aojea** [comment]
/assign @danwinship 
We need approval for the iptables part

File: pkg/proxy/iptables/proxier.go (hunk 7 above)
Comment (danwinship) [inline pkg/proxy/iptables/proxier.go:398]: You shouldn't need to add this; inbound connections already eventually pass through `kubeNodePortsChain` via the "tail-call" created at the end of `syncProxyRules`.

File: pkg/proxy/iptables/proxier.go [hunk 13]
```diff
@@ -1337,6 +1338,19 @@ func (proxier *Proxier) syncProxyRules() {
 			}
 		}
 
+		// Capture healthCheckNodePorts.
+		if svcInfo.HealthCheckNodePort() != 0 {
```
Comment (danwinship) [inline pkg/proxy/iptables/proxier.go:1342]: should go inside the `if svcInfo.NodePort() != 0` section

File: pkg/proxy/iptables/proxier_test.go (hunk 4 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier_test.go:924]: > My concern is if I just modify the INPUT chain policy to DROP then we might lose ssh connection to that VM instantly

You don't need to change the default `INPUT` chain policy, you can just do

    iptables -A INPUT -p tcp --dport <PORT> -j DROP

or whatever

File: pkg/proxy/ipvs/proxier.go [hunk 14]
```diff
@@ -106,6 +106,7 @@ var iptablesJumpChain = []struct {
 	{utiliptables.TableNAT, utiliptables.ChainPrerouting, kubeServicesChain, "kubernetes service portals"},
 	{utiliptables.TableNAT, utiliptables.ChainPostrouting, kubePostroutingChain, "kubernetes postrouting rules"},
 	{utiliptables.TableFilter, utiliptables.ChainForward, KubeForwardChain, "kubernetes forwarding rules"},
+	{utiliptables.TableFilter, utiliptables.ChainInput, KubeNodePortChain, "kubernetes health check rules"},
```
Comment (danwinship) [inline pkg/proxy/ipvs/proxier.go:109]: I'm less familiar with the IPVS rules but I believe the comment I made about iptables should apply here too

File: pkg/proxy/ipvs/proxier.go [hunk 15]
```diff
@@ -161,6 +163,7 @@ var ipsetInfo = []struct {
 	{kubeNodePortLocalSetUDP, utilipset.BitmapPort, kubeNodePortLocalSetUDPComment},
 	{kubeNodePortSetSCTP, utilipset.HashIPPort, kubeNodePortSetSCTPComment},
 	{kubeNodePortLocalSetSCTP, utilipset.HashIPPort, kubeNodePortLocalSetSCTPComment},
+	{kubeHealthCheckNodePortSet, utilipset.BitmapPort, kubeHealthCheckNodePortSetComment},
```
Comment (danwinship) [inline pkg/proxy/ipvs/proxier.go:166]: I'm not sure if you also need to add something to `ipsetWithIptablesChain`...

**Review by danwinship — CHANGES_REQUESTED** [review]

File: pkg/proxy/iptables/proxier.go (hunk 13 above)
Comment (andrewsykim) [reply pkg/proxy/iptables/proxier.go:1342]: Node ports are now optional for load balancers (see `spec.allocateLoadBalancerNodePorts`), so a separate check still makes sense since healthCheckNodePorts is always set regardless of whether node ports is enabled.

File: pkg/proxy/iptables/proxier_test.go (hunk 4 above)
Comment (andrewsykim) [reply pkg/proxy/iptables/proxier_test.go:924]: > iptables -A INPUT -p tcp --dport <PORT> -j DROP

This rule would conflict with the rules we add from kube-proxy though.

File: pkg/proxy/iptables/proxier.go (hunk 7 above)
Comment (andrewsykim) [reply pkg/proxy/iptables/proxier.go:398]: Is that still true when the default `INPUT` chain policy is `DROP`?

File: pkg/proxy/iptables/proxier_test.go (hunk 4 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier_test.go:924]: > This rule would conflict with the rules we add from kube-proxy though.

That's the goal! Add a rule (to the very end of the `INPUT` chain) that intentionally drops packets directed just at this health check port. (When you quoted my reply the "PORT" was missing, but the rule as I originally typed it was supposed to apply only to that particular part.) The new `-j ACCEPT` rule added by this PR should run before that rule gets hit, rendering it irrelevant.

Comment (andrewsykim) [reply pkg/proxy/iptables/proxier_test.go:924]: That depends on if we prepend or append though right? Do we always prepend filter rules?

File: pkg/proxy/iptables/proxier.go (hunk 7 above)
Comment (hanlins) [reply pkg/proxy/iptables/proxier.go:398]: I thought it would work without this rule in my early attempts but turned out it didn't. The fact is for `NodePort` services, the traffic was `DNAT`ted in `nat` table, basically in this order:
```
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A KUBE-SERVICES -d 10.102.149.66/32 -p tcp -m comment --comment "default/nginx cluster IP" -m tcp --dport 8080 -j KUBE-SVC-2CMXP7HKUVJN7L6M
-A KUBE-SVC-2CMXP7HKUVJN7L6M -m comment --comment "default/nginx" -j KUBE-SEP-V6JOQ423IM4BM4HR
-A KUBE-SEP-V6JOQ423IM4BM4HR -s 100.96.0.11/32 -m comment --comment "default/nginx" -j KUBE-MARK-MASQ
-A KUBE-SEP-V6JOQ423IM4BM4HR -p tcp -m comment --comment "default/nginx" -m tcp -j DNAT --to-destination 100.96.0.11:80
```
In the rules above, `100.96.0.11` is the `nginx` pod IP.
In `filter` table, the traffic is accepted by the `KUBE-FORWARD` chain, see the third rule:
```
➜  ~ iptables -L KUBE-FORWARD --line-n -v
Chain KUBE-FORWARD (1 references)
num   pkts bytes target     prot opt in     out     source               destination
1        0     0 DROP       all  --  any    any     anywhere             anywhere             ctstate INVALID
2        0     0 ACCEPT     all  --  any    any     anywhere             anywhere             /* kubernetes forwarding rules */ mark match 0x4000/0x4000
3      235 42692 ACCEPT     all  --  any    any     anywhere             anywhere             /* kubernetes forwarding conntrack pod source rule */ ctstate RELATED,ESTABLISHED
4        0     0 ACCEPT     all  --  any    any     anywhere             anywhere             /* kubernetes forwarding conntrack pod destination rule */ ctstate RELATED,ESTABLISHED
```
So, different from healthcheck nodeports, the traffic towards node ports got `DNAT`ted and instead of hitting `INPUT` chain, it will hit `FORWARD` chain. However health check node ports are listening on local addresses so the incoming packets will hit `INPUT` chain.

Before this change, there's no `KUBE-NODEPORTS` chain in the `filter` table at all, so whether the traffic is accepted or not is purely depending on the policy of `INPUT` chain. That's why we need to add a rule from `INPUT` chain to the newly added `KUBE-NODEPORTS` chain.

Speaking of the difference of node port traffic that is `DNAT`ted and the traffic towards health check endpoints that listens on local ports, I realized that if we have pods on `hostNetwork`, then node ports towards them won't work just like for health check node ports. I just validated that in my environment and the issue is really there, and I'm confident that I could fix that using the same approach just like for health check node port. I don't want to make more changes in the PR so maybe open an issue and fix it in another one, what do you guys think? @andrewsykim @danwinship ?

File: pkg/proxy/iptables/proxier.go (hunk 13 above)
Comment (hanlins) [reply pkg/proxy/iptables/proxier.go:1342]: Second to @andrewsykim, I think these are effectively the same, for now, `HealthCheckNodePort` will be non-zero only if the svc is of `LoadBalancer` type. And if the service is of `LoadBalancer` type, then it should have a non-zero `NodePort`. To me it's api-server's job to validate the spec and ensure all the svc proxy sees are valid (see my previous [comment](https://github.com/kubernetes/kubernetes/pull/97824#issuecomment-756515241)). If couple the logic here then if someday the validation logic changed, then we also need to fix it here.

File: pkg/proxy/ipvs/proxier.go (hunk 15 above)
Comment (hanlins) [reply pkg/proxy/ipvs/proxier.go:166]: Aha that's a tricky one, at first I thought I should add it here, but then I realized that `ipsetWithIptablesChain` is for `nat` table where we need to add it in `filter` table. I've already added the rule below:
```golang
       // Add rule to accept traffic towards health check node port
       utilproxy.WriteLine(proxier.filterRules,
               "-A", string(KubeNodePortChain),
               "-m", "comment", "--comment", proxier.ipsetList[kubeHealthCheckNodePortSet].getComment(),
               "-m", "set", "--match-set", proxier.ipsetList[kubeHealthCheckNodePortSet].Name, "dst",
               "-j", "ACCEPT",
       )
```

File: pkg/proxy/ipvs/proxier.go (hunk 14 above)
Comment (hanlins) [reply pkg/proxy/ipvs/proxier.go:109]: yeah same reason as my previous [comment](https://github.com/kubernetes/kubernetes/pull/97824#discussion_r568863008) why we need to keep this rule.

File: pkg/proxy/iptables/proxier.go (hunk 7 above)
Comment (aojea) [reply pkg/proxy/iptables/proxier.go:398]: I think that better to do that in a follow up PR,

File: pkg/proxy/iptables/proxier_test.go (hunk 4 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier_test.go:924]: The actual per-service rules get added to kubernetes-specific chains, not to the top-level `INPUT`, `OUTPUT`, etc, chains. We should be able to arrange for a single rule added by a test case to be added to the right place relative to the `-j KUBE-WHATEVER` rule in `INPUT`.

File: pkg/proxy/iptables/proxier.go (hunk 7 above)
Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:398]: Ah... there are two completely separate `KUBE-NODEPORTS` chains now... one in `-t nat` and one in `-t filter`

Comment (danwinship) [reply pkg/proxy/iptables/proxier.go:398]: ok, I think this is right, but don't use the word "portals" in the description. That's archaic pre-kube-1.0 terminology. Actually, just changing it to "ports" is probably what you meant anyway.

Comment (hanlins) [reply pkg/proxy/iptables/proxier.go]: Sure, changed here.

**Comment by andrewsykim** [comment]
@hanlins can you include in the release notes that this fix is only required when the default INPUT chain policy is not ACCEPT?

**Comment by hanlins** [comment]
@andrewsykim just rephrased, feel free to update it if needed!
