### PR TITLE
Taint node when initializing node.

### LINKED ISSUE #63897: Race condition when applying the unschedulable taint
The test job that runs regular e2e tests when all alpha features are enabled have been failing: https://k8s-testgrid.appspot.com/google-gce#gci-gce-alpha-enabled-default 

One thing I noticed is that many "kube-system" pods are scheduled onto the master node, causing the node to be overcommitted. The pods include, e.g., heapster, kube-dns, etc, even though the master was tained/marked as unschedulable. I took a closer look at the logs and this seemed to be caused by the new alpha feature to switch to using taints for unschedulable (#61161) -- The pods were scheduled to the master node *before* the controller manager tainted the node properly.

kube-controller-manager.log:
```
I0515 23:04:32.799346       1 controller_utils.go:248] Added [&Taint{Key:node.kubernetes.io/network-unavailable,Value:,Effect:NoSchedule,TimeAdded:2018-05-15 23:04:32.01059287 +0000 UTC m=+44.916948242,} &Taint{Key:node.kubernetes.io/unschedulable,Value:,Effect:NoSchedule,TimeAdded:2018-05-15 23:04:32.010593023 +0000 UTC m=+44.916948519,}] Taint to Node bootstrap-e2e-master
```

kube-scheduler.log
```
I0515 23:04:31.999793       1 factory.go:1392] Attempting to bind monitoring-influxdb-grafana-v4-5c64865875-klq9m to bootstrap-e2e-master
I0515 23:04:32.019916       1 factory.go:1392] Attempting to bind metrics-server-v0.2.1-7c6c844f97-wm9l2 to bootstrap-e2e-master
I0515 23:04:32.031312       1 factory.go:1392] Attempting to bind kube-dns-694c887f5f-4f6kj to bootstrap-e2e-master
I0515 23:04:32.041949       1 factory.go:1392] Attempting to bind heapster-v1.5.3-6f6f4c647f-866qv to bootstrap-e2e-master
I0515 23:04:32.061453       1 factory.go:1392] Attempting to bind l7-default-backend-5d5b9874d5-ltsq9 to bootstrap-e2e-master
I0515 23:04:32.081330       1 factory.go:1392] Attempting to bind event-exporter-v0.1.9-75857bbfd5-sgxdv to bootstrap-e2e-master
I0515 23:04:32.090780       1 factory.go:1392] Attempting to bind fluentd-gcp-scaler-7f76fb89d7-r8sr5 to bootstrap-e2e-master
```

/cc @bsalamat, @k82cn

### PR DESCRIPTION
**Pull request by k82cn**
Signed-off-by: Da K. Ma <klaus1982.cn@gmail.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #63897 

**Release note**:
```release-note
If `TaintNodesByCondition` enabled, taint node with `TaintNodeUnschedulable` when
initializing node to avoid race condition.
```

### CODE REVIEW

**Comment by k82cn** [comment]
@kubernetes/sig-node-pr-reviews , ping for review :)

**Review by feiskyer — COMMENTED** [review]
LGTM

@tallclair PTAL

File: pkg/kubelet/kubelet_node_status_test.go [hunk 1]
```diff
@@ -1580,3 +1584,78 @@ func TestValidateNodeIPParam(t *testing.T) {
...
+
+	var gotNode runtime.Object
+	kubeClient.AddReactor("create", "nodes", func(action core.Action) (bool, runtime.Object, error) {
+		createAction := action.(core.CreateAction)
+		gotNode = createAction.GetObject()
+		return true, gotNode, nil
+	})
+	kubeClient.AddReactor("*", "*", func(action core.Action) (bool, runtime.Object, error) {
+		return true, nil, fmt.Errorf("no reaction implemented for %s", action)
+	})
```
Comment (tallclair) [inline pkg/kubelet/kubelet_node_status_test.go]: Can you refactor some or all of this setup to a test helper that is reused by the different tests in this file?

File: pkg/kubelet/kubelet_node_status.go [hunk 2]
```diff
@@ -227,6 +227,18 @@ func (kl *Kubelet) initialNode() (*v1.Node, error) {
 		}
 		nodeTaints = append(nodeTaints, taints...)
 	}
+
+	// If TaintNodesByCondition enabled, taint node with TaintNodeUnschedulable when initializing
+	// node to avoid race condition; refer to #63897 for more detail.
+	if utilfeature.DefaultFeatureGate.Enabled(features.TaintNodesByCondition) {
+		if node.Spec.Unschedulable {
+			nodeTaints = append(nodeTaints, v1.Taint{
```
Comment (tallclair) [inline pkg/kubelet/kubelet_node_status.go]: Should this verify that nodeTaints doesn't already include Unschedulable before adding it?

File: pkg/kubelet/kubelet_node_status_test.go [hunk 3]
```diff
@@ -1580,3 +1584,78 @@ func TestValidateNodeIPParam(t *testing.T) {
...
+
+		// Reset kubelet status for each test.
+		kubelet.registrationCompleted = false
+
+		go func() {
+			kubelet.registerWithAPIServer()
+			done <- struct{}{}
+		}()
+		select {
+		case <-time.After(wait.ForeverTestTimeout):
```
Comment (tallclair) [inline pkg/kubelet/kubelet_node_status_test.go]: Is it likely that `registerWithAPIServer` will hang? If not I'd say let the test framework handle the timeout and avoid the complexity.

File: pkg/kubelet/kubelet_node_status_test.go (hunk 1 above)
Comment (k82cn) [reply pkg/kubelet/kubelet_node_status_test.go]: done

File: pkg/kubelet/kubelet_node_status_test.go (hunk 3 above)
Comment (k82cn) [reply pkg/kubelet/kubelet_node_status_test.go]: should not hang, removed :)

File: pkg/kubelet/kubelet_node_status.go (hunk 2 above)
Comment (k82cn) [reply pkg/kubelet/kubelet_node_status.go]: yes. updated :)

File: pkg/kubelet/kubelet_node_status.go [hunk 4]
```diff
@@ -227,6 +229,21 @@ func (kl *Kubelet) initialNode() (*v1.Node, error) {
...
+	unschedulableTaint := v1.Taint{
+		Key:    algorithm.TaintNodeUnschedulable,
+		Effect: v1.TaintEffectNoSchedule,
+	}
+
+	// If TaintNodesByCondition enabled, taint node with TaintNodeUnschedulable when initializing
+	// node to avoid race condition; refer to #63897 for more detail.
+	if utilfeature.DefaultFeatureGate.Enabled(features.TaintNodesByCondition) {
+		if node.Spec.Unschedulable &&
+			!taintutil.TaintExists(nodeTaints, &unschedulableTaint) {
```
Comment (tallclair) [inline pkg/kubelet/kubelet_node_status.go]: If the taint exists with a different effect, this will duplicate it. Granted, that's probably a bug anyway, but I think it's safer to just check for the key here (overwriting as necessary). Although actually, does the NodeRestriction controller allow the taint effect to be changed here?
@liggitt

File: pkg/kubelet/kubelet_node_status_test.go [hunk 5]
```diff
@@ -118,6 +122,18 @@ func applyNodeStatusPatch(originalNode *v1.Node, patch []byte) (*v1.Node, error)
...
+	return true, nil, fmt.Errorf("no reaction implemented for %s", action)
+}
+
+func addNotImplatedReaction(kubeClient *fake.Clientset) {
+	if kubeClient == nil {
+		return
+	}
+
+	kubeClient.AddReactor("*", "*", notImplemented)
+}
```
Comment (tallclair) [inline pkg/kubelet/kubelet_node_status_test.go]: Sorry for the confusion, I didn't mean these specific methods so much as all the test setup boilerplate. Especilally the mock cAdvisor, which is unrelated to the function being tested.

File: pkg/kubelet/kubelet_node_status.go (hunk 4 above)
Comment (liggitt) [reply pkg/kubelet/kubelet_node_status.go]: initialNode() is only used to create the node in initial registration. it does not update nodes.

File: pkg/kubelet/kubelet_node_status_test.go (hunk 5 above)
Comment (k82cn) [reply pkg/kubelet/kubelet_node_status_test.go]: Can we handle this in a separate PR? The `ImagesFSInfo` and `RootFSInfo` are different; it takes some time to go through all case to have a helper func for it.

File: pkg/kubelet/kubelet_node_status.go (hunk 4 above)
Comment (k82cn) [reply pkg/kubelet/kubelet_node_status.go]: > If the taint exists with a different effect, this will duplicate it. 

Yes, that up to user's setting; it's an valid case that user also add the effect, we only need to handle `NoSchedule` by kubelet.

> Although actually, does the NodeRestriction controller allow the taint effect to be changed here?

As liggitt@ said, `NodeRestriction controller` only reject node taints updates; this's accepted as creation :)

Comment (tallclair) [reply pkg/kubelet/kubelet_node_status.go]: If that's the case, then why check `TaintExists` at all here?

Comment (liggitt) [reply pkg/kubelet/kubelet_node_status.go]: They could've specified it explicitly in the initial taints flag

File: pkg/kubelet/kubelet_node_status_test.go [hunk 6]
```diff
@@ -126,6 +130,18 @@ func applyNodeStatusPatch(originalNode *v1.Node, patch []byte) (*v1.Node, error)
 	return updatedNode, nil
 }
 
+func notImplemented(action core.Action) (bool, runtime.Object, error) {
+	return true, nil, fmt.Errorf("no reaction implemented for %s", action)
+}
+
+func addNotImplatedReaction(kubeClient *fake.Clientset) {
```
Comment (mikedanese) [inline pkg/kubelet/kubelet_node_status_test.go]: spellcheck: Implated

**Review by mikedanese — COMMENTED** [review]
Looks good to me

**Comment by mikedanese** [comment]
Never mind, I guess an operator would remove this.

**Comment by k82cn** [comment]
ping for LGTM or any comments to follow up :)

File: pkg/kubelet/kubelet_node_status.go (hunk 4 above)
Comment (tallclair) [reply pkg/kubelet/kubelet_node_status.go]: Sorry, I'm confused... then couldn't this duplicate the taint specified from --register-with-taints?

Comment (k82cn) [reply pkg/kubelet/kubelet_node_status.go]: If it's duplicated, it'll not add it; that's why we check `TaintExists` :). And we only check against `unschedulableTaint`, which is handled `NodeLifeCycleController`; the other customized taint will follow the default Taint/Toleration behaviour :)

**Comment by k82cn** [comment]
@liggitt , @mikedanese , @tallclair  any more comments ?

File: pkg/kubelet/kubelet_node_status.go (hunk 4 above)
Comment (tallclair) [reply pkg/kubelet/kubelet_node_status.go]: To clarify:

1. Kubelet is started with `--register-with-taints=node.kubernetes.io/unschedulable=true:PreferNoSchedule`
2. This code checks for a taint with `node.kubernetes.io/unschedulable:NoSchedule`
3. No match is found, and the kubelet ends up with the duplicate taint `node.kubernetes.io/unschedulable:PreferNoSchedule` and `node.kubernetes.io/unschedulable:NoSchedule`

Comment (k82cn) [reply pkg/kubelet/kubelet_node_status.go]: @tallclair , `node.kubernetes.io/unschedulable:PreferNoSchedule` is used for priorities, and `node.kubernetes.io/unschedulable:NoSchedule` is used for predicates; so I think they're not duplicated; and `node.kubernetes.io/unschedulable:NoSchedule` will be removed when `.spec.unschedulable` is updated to `false`.
