### PR TITLE
Fix race between MountVolume and UnmountDevice

### LINKED ISSUE #65246: Second Pod Using Same PVC Fails WaitForAttach Flakily
The test `[sig-storage] CSI Volumes CSI plugin test using CSI driver: hostPath should provision storage` flakes very occasionally. Below are the findings of the circumstances of the flake.

During `testDynamicProvisioning` two pods are created in quick succession. The test flakes when the second Pod fails to come up.

The second pod fails to come up with error:
`MountVolume.WaitForAttach failed for volume "pvc-bc2294b873ef11e8" : resource name may not be empty`

Upon exploring the logs we discovered that there was only 1 Attach call made at the beginning, and one Detach call upon timeout of the test [See timestamps]:
```
I0613 19:00:41.888473       1 reconciler.go:291] attacherDetacher.AttachVolume started for volume "pvc-0c896e426f3c11e8" (UniqueName: "kubernetes.io/csi/csi-hostpath^0da20430-6f3c-11e8-a80a-0a580a40016c") from node "e2e-40645-674b9-minion-group-gz10" 
I0613 19:00:42.533343       1 operation_generator.go:335] AttachVolume.Attach succeeded for volume "pvc-0c896e426f3c11e8" (UniqueName: "kubernetes.io/csi/csi-hostpath^0da20430-6f3c-11e8-a80a-0a580a40016c") from node "e2e-40645-674b9-minion-group-gz10" 
I0613 19:15:52.528902       1 reconciler.go:233] attacherDetacher.DetachVolume started for volume "pvc-0c896e426f3c11e8" (UniqueName: "kubernetes.io/csi/csi-hostpath^0da20430-6f3c-11e8-a80a-0a580a40016c") on node "e2e-40645-674b9-minion-group-gz10" 
I0613 19:15:52.615262       1 operation_generator.go:1225] Verified volume is safe to detach for volume "pvc-0c896e426f3c11e8" (UniqueName: "kubernetes.io/csi/csi-hostpath^0da20430-6f3c-11e8-a80a-0a580a40016c") on node "e2e-40645-674b9-minion-group-gz10" 
I0613 19:15:53.367487       1 operation_generator.go:419] DetachVolume.Detach succeeded for volume "pvc-0c896e426f3c11e8" (UniqueName: "kubernetes.io/csi/csi-hostpath^0da20430-6f3c-11e8-a80a-0a580a40016c") on node "e2e-40645-674b9-minion-group-gz10" 
```

We tracked down the `resource name may not be empty` error to the likely culprit in func `waitForVolumeAttachmentInternal`:
```
attach, err := c.k8s.StorageV1beta1().VolumeAttachments().Get(attachID, meta.GetOptions{})
```
based on the error message returned. 

This is likely caused by `attachID`(string) being empty [uncomfirmed], which is what the Kubelet would get from the DevicePath field on the Node object. This DevicePath field is normally added on Attach and removed on Detach of the volume.

The DevicePath is clearly present on the Node when the first pod is being brought up. But it is possible that it is somehow missing or not able to be retrieved by the time the second Pod is starting up (and continues to be unavailable exhausting the 15m timeout on the test) even though no Detach operation was performed on the volume in the meantime (according to logs). We are currently unable to reproduce this flake on command and did all analysis based on logs from the two flakes we saw naturally occur in the 100s of runs performed of the test.

This flake was originally seen in #65064 and the test logs can be found here: https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/65064/pull-kubernetes-e2e-gce/40645/

**Environment**: GCE
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.975+98194b8630958e", GitCommit:"98194b8630958ee48db662f42404dc0bc6a2ed80", GitTreeState:"clean", BuildDate:"2018-06-19T18:16:46Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GCP
- OS (e.g. from /etc/os-release):
```
BUILD_ID=10323.64.0
NAME="Container-Optimized OS"
KERNEL_COMMIT_ID=94bdaa2af49562e7aba0168cae050911d105f5cb
GOOGLE_CRASH_ID=Lakitu
VERSION_ID=65
BUG_REPORT_URL=https://crbug.com/new
PRETTY_NAME="Container-Optimized OS from Google"
VERSION=65
GOOGLE_METRICS_PRODUCT_ID=26
HOME_URL="https://cloud.google.com/compute/docs/containers/vm-image/"
ID=cos
```
- Kernel (e.g. `uname -a`): `Linux e2e-test-dyzz-master 4.4.111+ #1 SMP Wed Mar 28 13:44:38 PDT 2018 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux`

/kind flake
/kind bug
/sig storage
/cc @msau42 @jingxu97 @saad-ali @verult

### PR DESCRIPTION
**Pull request by jsafrane**
When kubelet receives a new pod while UnmountDevice is in progress, it should not enqueue 
 MountVolume operation - the volume device is being unmounted right now.

In addition, don't clear devicePath after UnmountDevice, because subsequent MountDevice may need it.

/kind bug
/sig storage
Fixes #65246

**Does this PR introduce a user-facing change?**:

```release-note
Fixed kubelet reporting "resource name may not be empty" when mounting a volume very quickly after unmount.
```

### CODE REVIEW

**Comment by jsafrane** [comment]
@msau42 @gnufied @jingxu97 @saad-ali @pohly PTAL.

File: pkg/kubelet/volumemanager/reconciler/reconciler.go [hunk 1]
```diff
@@ -166,6 +166,10 @@ func (rc *reconciler) reconcile() {
 	// Ensure volumes that should be unmounted are unmounted.
 	for _, mountedVolume := range rc.actualStateOfWorld.GetMountedVolumes() {
 		if !rc.desiredStateOfWorld.PodExistsInVolume(mountedVolume.PodName, mountedVolume.VolumeName) {
+			if rc.operationExecutor.IsOperationPending(mountedVolume.VolumeName, nestedpendingoperations.EmptyUniquePodName) {
+				klog.V(5).Infof("Skipping UnmountVolume, device operation is in progress")
+				continue
```
Comment (pohly) [inline pkg/kubelet/volumemanager/reconciler/reconciler.go]: How is this different from the check that the executer will do internally? See here:
https://github.com/kubernetes/kubernetes/blob/b7e2980a57289a32a7dbc5165584a0b1a56c9dd9/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go#L94-L108

When I asked about it in https://github.com/kubernetes/kubernetes/issues/70319 and later in a CSI WG meeting, @saad-ali said that the executioner will prevent running multiple operations against the same volume in parallel.

It wasn't obvious how that works and I was still worried that the executioner would merely serialize operations. But after looking at the code above, my interpretation is that it will discard new operations *instead* of queuing them, so it should do something similar to what you propose here.

But I am not entirely sure - perhaps your check is stricter, or I misunderstood something.

Comment (jsafrane) [reply pkg/kubelet/volumemanager/reconciler/reconciler.go]: The difference is `podName` - (Un)MountDevice operation uses empty pod name, it's global for all pods, while (Un)MountVolume uses pod names. IMO, (volumeName, podName) is the primary key in the operation map, so multiple MountVolumes can run in parallel on the same volume.

**Comment by pohly** [comment]
Jan Šafránek <notifications@github.com> writes:
> The difference is `podName` - (Un)MountDevice operation uses empty pod
> name, it's global for all pods, while (Un)MountVolume uses pod
> names. IMO, (volumeName, podName) is the primary key in the operation
> map, so multiple MountVolumes can run in parallel on the same volume.

Then let me come back to my question from
https://github.com/kubernetes/kubernetes/issues/70319#issuecomment-436792272:
is there there ever a situation where there should be more than one
operation in flight *per volume*? Note that I meant "should be" as in
"should be allowed to be".

@saad-ali answer was no, but in practice it was allowed because the
check was was based on volume + pod. That check has been shown to be
insufficient for one case. Can we be sure that this case (which gets
addressed with your PR) is the only one?

I genuinely don't know.

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go [hunk 2]
```diff
@@ -568,7 +568,9 @@ func (asw *actualStateOfWorld) SetVolumeGloballyMounted(
 
 	volumeObj.globallyMounted = globallyMounted
 	volumeObj.deviceMountPath = deviceMountPath
-	volumeObj.devicePath = devicePath
+	if devicePath != "" {
+		volumeObj.devicePath = devicePath
+	}
```
Comment (gnufied) [inline pkg/kubelet/volumemanager/cache/actual_state_of_world.go]: Do we really need this? If we prevent concurrent operation on same volume - won't a pod that uses same volume will pretty much cause another `MountDevice` operation?

Comment (jsafrane) [reply pkg/kubelet/volumemanager/cache/actual_state_of_world.go]: Yes, we need it. Consider UnmountDevice is in progress and a new pod arrives.

1. UnmountDevice finishes. This calls `MarkDeviceAsUnmounted` which clears the devicePath, i.e. calls `SetVolumeGloballyMounted(..., devicePath="", ...)`
2. New MountDevice (WaitForAttach) starts and sees empty devicePath -> problems.

**Comment by jsafrane** [comment]
> is there there ever a situation where there should be more than one
operation in flight *per volume*? Note that I meant "should be" as in
"should be allowed to be".

I am not sure. However, in this case we did not see two operations in parallel, we saw UnmountDevice running and MountVolume enqueued. MountVolume was started after UnmountDevice finished and *that* is wrong - the device is not mounted, so MountVolume has nothing to bind-mount. We can:

* Either not enqueue MountVolume operation when UnmountDevice is in progress (that's this PR)
* Or update MountVolume operation to check if MountDevice was completed.

**Comment by pohly** [comment]
Jan Šafránek <notifications@github.com> writes:

>> is there there ever a situation where there should be more than one
> operation in flight *per volume*? Note that I meant "should be" as in
> "should be allowed to be".
>
> I am not sure. However, in this case we did not see two operations in
> parallel, we saw UnmountDevice running and MountVolume
> enqueued. MountVolume was started after UnmountDevice finished and
> *that* is wrong - the device is not mounted, so MountVolume has
> nothing to bind-mount. We can:
>
> * Either not enqueue MountVolume operation when UnmountDevice is in progress (that's this PR)
> * Or update MountVolume operation to check if MountDevice was
> completed.

Third option:
 * make the check in the executor stricter by only using the volume as
   key when checking for existing operations

The result in this case would have been that the MountVolume operation
would have been discarded by the executor itself, instead of having to
add that logic to the reconciler.

This would also catch other errors where operations are enqueued that
shouldn't be enqueued because the pending operation will change the
state of the world.

I'd expect the reconciler to simply re-create operations that are still
needed once the running operation is done.

But perhaps such a change has negative effects in cases where
(currently) pending or parallel operations are possible and
desirable. <shrug>

**Comment by jsafrane** [comment]
It seems I was wrong. Only one `MountVolume()` operation runs when multiple pods use the same volume, because pod name is not used in the operation name:

https://github.com/kubernetes/kubernetes/blob/954996e231074dc7429f7be1256a579bedd8344c/pkg/volume/util/operationexecutor/operation_executor.go#L742

So operation checks in this PR are useless and only `devicePath` check is needed. I reworked the PR, now it's one `if`.

**Comment by pohly** [comment]
Jan Šafránek <notifications@github.com> writes:
> So operation checks in this PR are useless and only `devicePath` check
> is needed. I reworked the PR, now it's one `if`.

Is the effect different from what I have in
https://github.com/kubernetes/kubernetes/pull/70746?

SetVolumeGloballyMounted is a function with poorly defined semantic, and
adding yet another special case doesn't make it better. IMHO deleting it
and moving the relevant code to MarkDeviceAsMounted and
MarkDeviceAsUnmounted is cleaner. Just my 2 cents of course, I don't
care which PR gets merged (if any).

**Comment by msau42** [comment]
Please add unit tests to this function and reconciler like I suggested here: https://github.com/kubernetes/kubernetes/pull/70746#discussion_r233228120

**Comment by jsafrane** [comment]
Unit test added. It fails without changes in `actual_state_of_world.go` and passes with them.

**Comment by gnufied** [comment]
/lgtm

but I also think that - we should also merge https://github.com/kubernetes/kubernetes/pull/71095 because while we have fixed one race here, not relying on `attachID` value present in actual state of the world, while calling `WaitForAttach` makes sense. Many other drivers as well discover the actual device path in `WaitForAttach` call itself.

**Comment by AishSundar** [comment]
@saad-ali @msau42 looks like this is ready for merge. let me know if you want help stamping it with 1.13 milestone

**Comment by gnufied** [comment]
Lets cherry-pick this to 1.12 and 1.11. @jsafrane @msau42 any objectios. I think this will also fix long standing bug https://github.com/kubernetes/kubernetes/issues/67342

**Comment by msau42** [comment]
sgtm

**Comment by dennis-benzinger-hybris** [comment]
Is there any chance of getting this merge to 1.10 ?

**Comment by jsafrane** [comment]
> Is there any chance of getting this merge to 1.10 ?

No, Kubernetes supports only 3 releases at time (1.11 - 1.13).

**Comment by dennis-benzinger-hybris** [comment]
Thanks @jsafrane. That confirms what I expected from reading the docs. I thought I'll ask nevertheless because apparently #72856 was merged to 1.10.

File: pkg/kubelet/volumemanager/cache/actual_state_of_world.go (hunk 2 above)
Comment (jingxu97) [reply pkg/kubelet/volumemanager/cache/actual_state_of_world.go]: sorry to put a comment this late. very good catch of this bug. I think to avoid such bugs, it is better to not reuse SetVolumeGloballyMounted for both MarkDeviceAsMounted and MarkDeviceAsUnmounted (this function just to set the bool globallyMounted to false so no need to pass devicePath or deviceMountPath)
