### PR TITLE
Fix race in informer

### LINKED ISSUE #27004: Race condition in Informer
### What's the issue?
Informer could end up in wrong state.

### Example?
I have been stress testing RC of 100 replicas. I kept deleting the pod and let RC recover it to 100. The program will do informer.store.List() to check if there are 100 pods. But at the end of day it returned more than 100 (e.g. 131), while listing directly from apiserver returned 100.

### Why?
Informer has a queue and a store (aka indexer) internally.
- The store relies on the queue to do blocking [pop()][1] and and then [updates itself][2] in [Process()][1].
- The queue (delta fifo) is used to queue events from watcher. For [each operation in reflector][3], e.g. Delete, we will [enqueue an event to the queue][4].
- However, in DeltaFIFO.Delete(), it will [check the store][5] first to see if it needs to send a delete event. **This logic is wrong because the queue and store are run concurrently. There could be an ADD event not processed by store yet thus queue won't enqueue DELETE event.**

[1]:https://github.com/kubernetes/kubernetes/blob/0d3be6a316b39a71b62d45272d339f7fa9162165/pkg/controller/framework/controller.go#L127-L128
[2]:https://github.com/kubernetes/kubernetes/blob/0d3be6a316b39a71b62d45272d339f7fa9162165/pkg/controller/framework/shared_informer.go#L200-L224
[3]:https://github.com/kubernetes/kubernetes/blob/0d3be6a316b39a71b62d45272d339f7fa9162165/pkg/client/cache/reflector.go#L384-L392
[4]:https://github.com/kubernetes/kubernetes/blob/0d3be6a316b39a71b62d45272d339f7fa9162165/pkg/client/cache/delta_fifo.go#L200
[5]:https://github.com/kubernetes/kubernetes/blob/0d3be6a316b39a71b62d45272d339f7fa9162165/pkg/client/cache/delta_fifo.go#L192-L198

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #27004

@smarterclayton @hongchaodeng @caesarxuchao

### CODE REVIEW

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please, issue: #27344

File: pkg/client/cache/fifo.go [hunk 1]
```diff
@@ -22,12 +22,15 @@ import (
 	"k8s.io/kubernetes/pkg/util/sets"
 )
 
+type PopProcessFunc func(interface{}) error
```
Comment (smarterclayton) [inline pkg/client/cache/fifo.go]: Go doc defining what this should do.

File: pkg/client/cache/fifo.go [hunk 2]
```diff
@@ -183,12 +186,12 @@ func (f *FIFO) GetByKey(key string) (item interface{}, exists bool, err error) {
 	return item, exists, nil
 }
 
-// Pop waits until an item is ready and returns it. If multiple items are
+// Pop waits until an item is ready and processes it. If multiple items are
 // ready, they are returned in the order in which they were added/updated.
-// The item is removed from the queue (and the store) before it is returned,
-// so if you don't successfully process it, you need to add it back with
+// The item is removed from the queue (and the store) before it is processed,
+// so if you don't successfully process it, it should be added back with
```
Comment (smarterclayton) [inline pkg/client/cache/fifo.go]: Add comment about how the process semantics work (i.e. anything passed to popprocessfunc is done under the lock and is safe, etc)

File: pkg/controller/service/servicecontroller.go [hunk 3]
```diff
@@ -184,29 +184,33 @@ func (s *ServiceController) init() error {
...
-			glog.Errorf("Failed to process service delta. Retrying in %s: %v", retryDelay, err)
-			go func(deltas cache.Deltas, delay time.Duration) {
-				time.Sleep(delay)
-				if err := serviceQueue.AddIfNotPresent(deltas); err != nil {
-					glog.Errorf("Error requeuing service delta - will not retry: %v", err)
-				}
-			}(deltas, retryDelay)
-		} else if err != nil {
-			runtime.HandleError(fmt.Errorf("Failed to process service delta. Not retrying: %v", err))
+		process := func(obj interface{}) error {
```
Comment (smarterclayton) [inline pkg/controller/service/servicecontroller.go]: nit, but this might be cleaner if it was 

```
serviceQueue.Pop(func(obj interface{}) error) {
  // body
}
```

More of a personal preference to avoid having to worry that process is used somewhere else.

File: pkg/controller/service/servicecontroller.go [hunk 4]
```diff
@@ -184,29 +184,33 @@ func (s *ServiceController) init() error {
...
+			deltas, ok := obj.(cache.Deltas)
+			if !ok {
+				glog.Errorf("Received object from service watcher that wasn't Deltas: %+v", obj)
```
Comment (smarterclayton) [inline pkg/controller/service/servicecontroller.go]: Can you switch these to `util.HandleError` while you are in here?

File: pkg/volume/util.go [hunk 5]
```diff
@@ -142,8 +142,9 @@ func (c *realRecyclerClient) WatchPod(name, namespace string, stopChannel chan s
 	cache.NewReflector(podLW, &api.Pod{}, queue, 1*time.Minute).RunUntil(stopChannel)
 
 	return func() *api.Pod {
-		obj := queue.Pop()
-		return obj.(*api.Pod)
+		var pod *api.Pod
+		queue.Pop(func(obj interface{}) error { pod = obj.(*api.Pod); return nil })
```
Comment (smarterclayton) [inline pkg/volume/util.go]: Pop returns an object - should we simply have Pop stop returning an object, or should we have two methods `Pop() interface{}` and `PopAndLock(func ...)`, or should we add a helper function which is a no-op `cache.Ok = func() {}`?

File: plugin/pkg/scheduler/scheduler_test.go [hunk 6]
```diff
@@ -232,7 +232,9 @@ func TestSchedulerForgetAssumedPodAfterDelete(t *testing.T) {
 			return nil
 		}},
 		NextPod: func() *api.Pod {
-			return queuedPodStore.Pop().(*api.Pod)
+			var pod *api.Pod
+			queuedPodStore.Pop(func(obj interface{}) error { pod = obj.(*api.Pod); return nil })
```
Comment (smarterclayton) [inline plugin/pkg/scheduler/scheduler_test.go]: I don't like this style much - I would prefer a clearer "return" path.

File: pkg/volume/util.go (hunk 5 above)
Comment (wojtek-t) [inline pkg/volume/util.go]: We can't really stop returning the object, because controller framework is using to requeue this object conditionally:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/framework/controller.go#L130

We may consider adding another parameter "enqueueOnError bool" to the signature.

File: pkg/client/cache/fifo.go (hunk 1 above)
Comment (wojtek-t) [inline pkg/client/cache/fifo.go]: done

File: pkg/client/cache/fifo.go (hunk 2 above)
Comment (wojtek-t) [inline pkg/client/cache/fifo.go]: done

File: pkg/controller/service/servicecontroller.go (hunk 3 above)
Comment (wojtek-t) [inline pkg/controller/service/servicecontroller.go]: done

File: pkg/controller/service/servicecontroller.go (hunk 4 above)
Comment (wojtek-t) [inline pkg/controller/service/servicecontroller.go]: done

File: plugin/pkg/scheduler/scheduler_test.go (hunk 6 above)
Comment (wojtek-t) [inline plugin/pkg/scheduler/scheduler_test.go]: What we can potentially do is to have both "Pop()" and "PodAndRunUnderLock(func)" methods.
However, this is risky, because there people will be using the former and we can face the same races again in the future.

What we can do is to have a helper function that would be doing roughly this. WDYT?

**Comment by wojtek-t** [comment]
@smarterclayton - comments answered - PTAL

File: plugin/pkg/scheduler/scheduler_test.go (hunk 6 above)
Comment (smarterclayton) [inline plugin/pkg/scheduler/scheduler_test.go]: Sure, that SGTM.  Just want to avoid the duplication.

File: pkg/client/cache/fifo.go [hunk 7]
```diff
@@ -22,12 +22,15 @@ import (
...
+
 // Queue is exactly like a Store, but has a Pop() method too.
 type Queue interface {
 	Store
 
-	// Pop blocks until it has something to return.
-	Pop() interface{}
+	// Pop blocks until it has something to process.
+	// It returns the object that was process and the result of processing.
+	Pop(PopProcessFunc) (interface{}, error)
```
Comment (xiang90) [inline pkg/client/cache/fifo.go]: I understand the intention. However, I dislike this interface change. I would still keep the Queue is a simple data structure without the ability to process the out-coming data. Is there anything prevent us from doing this outside the queue?

Comment (wojtek-t) [inline pkg/client/cache/fifo.go]: Unfortunately that's not going to happen. Basically the problem is that we need to sync between DeltaFIFO and "knownKeys" that is passed to it. If we don't change the interface like that, the locking will be spreaded all over the code everywhere.

Comment (xiang90) [inline pkg/client/cache/fifo.go]: @wojtek-t 

I understand the intention. However, as far as I can see we do not really need to change a lot of places if we try to approach this problem in a different way that solving it outside the queue. I may be wrong. And I am OK with this solution as a temp one.

So here is my thought:
We now try to force the dequeue operation and the processing of the dequeued item protected by a shared queue lock. To be more concrete, for the service controller it is its cache.

First, I do not believe this is not a good abstraction. Queue now needs to worry about the synchronization between internal and external objects.  Second, this does not prevent the synchronization problem to happen. The knowobject cache still can be accessed externally asynchronously. This solves today's issue in a not elegant way I think. 

Thus I dislike it. And I suggest to clean this whole thing up after 1.3 if we want to go this approach right now.

**Comment by smarterclayton** [comment]
As a minimal change to fix the p0 for 1.3 I'm ok with this, although I think we can potentially clean up the API to address @xiang90's concerns (i think forcing all the dependent code to change via an interface change is a good forcing function - the most important need right now is to stomp the race).

**Comment by smarterclayton** [comment]
LGTM.

File: pkg/client/cache/fifo.go (hunk 7 above)
Comment (wojtek-t) [inline pkg/client/cache/fifo.go]: I definitely agree that it's not an ideal solution. But fixing it properly can't be done within an hour or - it would require days, which we don't have before 1.3. And this is fixing the problem that we are facing now.
And I completely agree that fixing it properly after 1.3 is a good thing to do.

**Comment by wojtek-t** [comment]
>
As a minimal change to fix the p0 for 1.3 I'm ok with this, although I think we can potentially clean up the API to address @xiang90's concerns (i think forcing all the dependent code to change via an interface change is a good forcing function - the most important need right now is to stomp the race).

+100

**Comment by hongchaodeng** [comment]
The change should fix the problem.

Thanks @wojtek-t @smarterclayton @xiang90 for all the reasoning on this. The plan SGTM.

**Comment by xiang90** [comment]
@hongchaodeng Have you tried to apply this patch to the test that can reproduce the failure?

**Comment by hongchaodeng** [comment]
@xiang90 
The test won't work with this change, because everything is blocked and sleep. But that's expected and a good sign. If needed, I can redesign and write more tests to cover any potential races.

File: pkg/client/cache/fifo.go [hunk 8]
```diff
@@ -39,6 +44,16 @@ type Queue interface {
 	HasSynced() bool
 }
 
+// Helper function for popping from Queue.
+func Pop(queue Queue) interface{} {
```
Comment (lavalamp) [inline pkg/client/cache/fifo.go]: I don't understand how anyone using this helper function will not have the problem you're trying to prevent?

**Comment by lavalamp** [comment]
This sort of defeats the purpose of Pop, which is to keep the lock held as little as possible. I'm not sure how much contention this adds, or if our queues will still be able to keep up. If the scalability tests go red I will probably roll this back...

File: pkg/client/cache/fifo.go (hunk 8 above)
Comment (lavalamp) [inline pkg/client/cache/fifo.go]: I see, you're only using it for tests. Please update this comment or people are going to get bitten by this.

Comment (wojtek-t) [inline pkg/client/cache/fifo.go]: @lavalamp - since this is already merged and we probably need to fix some more issues - see https://github.com/kubernetes/kubernetes/issues/27004#issuecomment-225963877 (but those one are very local changes) I will update the comment in that PR tomorrow.

**Comment by wojtek-t** [comment]
@lavalamp @caesarxuchao - I looked into performance results after merging this PR and there is no effect. So this seems to be completely fine.

**Comment by lavalamp** [comment]
Great, thanks!
