### PR TITLE
Kubelet: support retrieving stats using UID of mirror pods

### LINKED ISSUE #5688: Kubelet fails to provide stats for static pods
Since static pods are now exposed via the apiserver, users (heapster) naturally expect kubelet to provide stats for the static pods.
This is breaking heapster.

cc @yujuhong

### PR DESCRIPTION
**Pull request by yujuhong**
Kubelet supports retrieving stats for pods/containers with and without UID.
This does not always work for the static pods because users may get the UIDs of
the mirror pods from the API server, and use them to query Kubelet. In this
case, Kubelet would fail to locate the containers due to mismatched UIDs.

This change adds a intenral mirror to static pod UID mapping and teaches all
public-facing functions to perform UID lookup before proceeding. This allows
users to use either mirror or static pod's UID to retrieve stats.

This fixes #5688

### CODE REVIEW

**Comment by yujuhong** [comment]
This PR is a bit cumbersome. The pod manager that I'm supposedly working on will help a lot.

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -2176,8 +2200,23 @@ func (kl *Kubelet) StreamingConnectionIdleTimeout() time.Duration {
 	return kl.streamingConnectionIdleTimeout
 }
 
+func (kl *Kubelet) getStaticPodUID(uid types.UID) (types.UID, bool) {
```
Comment (vmarmol) [inline pkg/kubelet/kubelet.go]: Lets document why this exists in case future readers get confused :)

File: pkg/kubelet/kubelet.go [hunk 2]
```diff
@@ -2176,8 +2200,23 @@ func (kl *Kubelet) StreamingConnectionIdleTimeout() time.Duration {
...
+	defer kl.podLock.RUnlock()
+	return kl.mirrorPods.GetStaticUID(uid)
+}
+
 // GetContainerInfo returns stats (from Cadvisor) for a container.
 func (kl *Kubelet) GetContainerInfo(podFullName string, uid types.UID, containerName string, req *cadvisorApi.ContainerInfoRequest) (*cadvisorApi.ContainerInfo, error) {
+
+	// If the UID belongs to a mirror pod, translate it to the UID of its
+	// static counterpart.
+	if uid != "" {
```
Comment (vmarmol) [inline pkg/kubelet/kubelet.go]: WDYT of doing this logic in getStaticPodUID() since we do the same thing in all callsites? Maybe getPodUID()

File: pkg/kubelet/mirror_manager.go [hunk 3]
```diff
@@ -123,16 +118,90 @@ func isMirrorPod(pod *api.Pod) bool {
...
+		mirrorPods.Insert(&pod)
+		if !isMirrorPod(&pod) {
 			filteredPods = append(filteredPods, pod)
 		}
 	}
-	return filteredPods, mirrorPods
+	return filteredPods, *mirrorPods
+}
+
+// This is not thread-safe to use alone.
```
Comment (vmarmol) [inline pkg/kubelet/mirror_manager.go]: nit: This is "thread-compatible". Internally we commonly use: thread-safe, thread-compatible, and thread-hostile. This article explains the definition of each: http://www.ibm.com/developerworks/library/j-jtp09263/

**Comment by vmarmol** [comment]
Yeah it does look a bit brittle, but I think we knew that coming into it. Looks good overall, minor comments. Thanks @yujuhong!

File: pkg/kubelet/kubelet.go (hunk 1 above)
Comment (yujuhong) [inline pkg/kubelet/kubelet.go]: Done.

File: pkg/kubelet/kubelet.go (hunk 2 above)
Comment (yujuhong) [inline pkg/kubelet/kubelet.go]: Done.

File: pkg/kubelet/mirror_manager.go (hunk 3 above)
Comment (yujuhong) [inline pkg/kubelet/mirror_manager.go]: Done. Thanks for the pointer!

**Comment by vmarmol** [comment]
LGTM, squash commits and we'll merge.

**Comment by erictune** [comment]
What is this for?

**Comment by vmarmol** [comment]
@erictune fixing #5688. Mirror pods fail getting stats today because they have a different UID than their static equivalent. This does the conversion in Kubelet API requests.

**Comment by erictune** [comment]
Who would get these stats?  If you say "master", then: isn't the new
direction to have kubelet post pod status to its master rather than having
the master poll for status?

**Comment by vmarmol** [comment]
Heapster uses this stats API

**Comment by yujuhong** [comment]
Squashed and rebased.

Shippable's complaints seem irrelevant though.
```
pkg/kubelet/container/fake_runtime.go:26:2: cannot find package "github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/volume" in any of:
	/home/shippable/.gvm/gos/go1.4/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/volume (from $GOROOT)
	/home/shippable/workspace/src/github.com/GoogleCloudPlatform/kubernetes/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/volume (from $GOPATH)
	/home/shippable/workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubelet/volume
```

**Comment by vmarmol** [comment]
@yujuhong yeah that seemed odd, I kicked it again and we'll see what it thinks.

**Comment by yujuhong** [comment]
@erictune, heapster queries kubelet directly for container info.

**Comment by vishh** [comment]
Thanks for the quick fix @yujuhong!

**Comment by yujuhong** [comment]
The head is broken :\ Other PRs are suffering too. This seems to be relevant to #5642.

**Comment by vmarmol** [comment]
:( @vishh do you know if anyone is working on a fix?

**Comment by yujuhong** [comment]
I uploaded one: #5743

**Comment by vmarmol** [comment]
Build is green! Merging.
