### PR TITLE
Fix problem in updating VolumeAttached in node status

### LINKED ISSUE #111000: Volumes may never be attached when detaching failed temporarily
### What happened?

Recently, the cpu load of my **kube-apiserver** gets higher after I expanded more pods and nodes into the cluster.

And I found that some volumes declared by pods could not be mounted after the restart of pods, even though the pods were successful scheduled. here's the kubectl describe information:

```
$kubectl describe pod chaos-bing-test-5-c0-2
Events:
  Type     Reason       Age    From                        Message
  ----     ------       ----   ----                        -------
  Normal   Scheduled    3m55s  default-scheduler           Successfully assigned default/chaos-bing-test-5-c0-2 to i22d01261.eu95sqa
  Warning  FailedMount  112s   kubelet, i22d01261.eu95sqa  Unable to mount volumes for pod "chaos-bing-test-5-c0-2_default(2680bd56-fd3a-11ec-8d16-70e28411919b)": timeout expired waiting for volumes to attach or mount for pod "default"/"chaos-bing-test-5-c0-2". list of unmounted volumes=[chaos-bing-test-5-c0-pvc]. list of unattached volumes=[chaos-bing-test-5-c0-pvc shm default-token-5js9b delta-config control-conf]
```

After checking the logs of **attach_detach_controller**, I found that in `reconcile.go`,`nodeStatusUpdater.UpdateNodeStatuses()` return an error, thus the `attacherDetacher.DetachVolume()` was skipped. That should be related to the high load on my **kube-apiserver** as it occasionally returns 500 http code (but this may not be the root cause). Here is the error message:

```
{"log":"I0705 12:10:07.634904       1 node_status_updater.go:86] Could not update node status for \"a13m05557.na61\"; re-marking for update. failed to patch status \"{\\\"status\\\":{\\\"volumesAttached\\\":null}}\" for node \"a13m05557.na61\": request declared a Content-Length of 35 but only wrote 0 bytes\n","stream":"stderr","time":"2022-07-05T12:10:07.634930166Z"}
{"log":"E0705 12:10:07.634925       1 reconciler.go:219] UpdateNodeStatuses failed while attempting to report volume as attached for volume \"pvc-751b518c-aa59-11ec-8772-7cd30ac02cb8\" (UniqueName: \"kubernetes.io/csi/csi-hostpath^79ff946c-aa59-11ec-8926-7cd30ab71afc\") on node \"a13m05557.na61\" : failed to patch status \"{\\\"status\\\":{\\\"volumesAttached\\\":null}}\" for node \"a13m05557.na61\": request declared a Content-Length of 35 but only wrote 0 bytes\n","stream":"stderr","time":"2022-07-05T12:10:07.634948215Z"}
```

**Here comes the problem:** 
In my opinion, the next loop of `reconcile()` would retry `nodeStatusUpdater.UpdateNodeStatuses()` and `attacherDetacher.DetachVolume()`, since the state of **actualStateOfWorld** is different from the state of **desiredStateOfWorld**. but it didn't happened.

By recording some additional logs, I notice that the pod was scheduled to the destination node by the scheduler right after above error message appeared, which cause `attach_detach_controller.go:podUpdate()` executed. That would write the volume info back to `desiredStateOfWorld.nodesManaged[NodeName].volumesToAttach[VolumeName]`. After that, the next loop of `reconcile()` would skip the detach operation for that volume, since **desiredStateOfWorld** was 'equal to' **actualStateOfWorld**. The log snippet is as follows:

```
...
I0706 14:44:19.597962       1 actual_state_of_world.go:384] Set detach request time to current time for volume kubernetes.io/csi/csi-hostpath^50aaebd1-b0ca-11ec-8c38-70e2840fcf1f on node "i22d01261.eu95sqa"
... 
// waiting unmount
...
E0706 14:44:31.992432       1 reconciler.go:218] UpdateNodeStatuses failed while attempting to report volume as attached for volume "pvc-500613f4-b0ca-11ec-9c0d-70e28411919b" (UniqueName: "kubernetes.io/csi/csi-hostpath^50aaebd1-b0ca-11ec-8c38-70e2840fcf1f") on node "i22d01261.eu95sqa" : failed to patch status \"{\\\"status\\\":{\\\"volumesAttached\\\":null}}\" for node \"i22d01261.eu95sqa\": request declared a Content-Length of 35 but only wrote 0 bytes\n"...
...
// my extra log shows the pod was scheduled at this time.
I0706 14:44:34.332395 call attach_detach_controller.go:podUpdate() and write desiredStateOfWorld.nodesManaged[nodeName].volumesToAttach[volumeName]
...
I0706 14:44:34.373217       1 reconciler.go:265] Volume attached--touching for volume "pvc-500613f4-b0ca-11ec-9c0d-70e28411919b" (UniqueName: "kubernetes.io/csi/csi-hostpath^50aaebd1-b0ca-11ec-8c38-70e2840fcf1f") from node "i22d01261.eu95sqa"
I0706 14:44:34.373217       1 reconciler.go:265] Volume attached--touching for volume "pvc-500613f4-b0ca-11ec-9c0d-70e28411919b" (UniqueName: "kubernetes.io/csi/csi-hostpath^50aaebd1-b0ca-11ec-8c38-70e2840fcf1f") from node "i22d01261.eu95sqa"
I0706 14:44:34.474256       1 reconciler.go:265] Volume attached--touching for volume "pvc-500613f4-b0ca-11ec-9c0d-70e28411919b" (UniqueName: "kubernetes.io/csi/csi-hostpath^50aaebd1-b0ca-11ec-8c38-70e2840fcf1f") from node "i22d01261.eu95sqa"
...
```

Finally, **attach_detach_controller** would not attach the volume neither, because the states of **desiredStateOfWorld** and **actualStateOfWorld** are the same. **attach_detach_controller** mistakenly thought the volume was attached, but it' not the case.

### What did you expect to happen?

when `nodeStatusUpdater.UpdateNodeStatuses()` fail, **attach_detach_controller** should retry to detach the volume until the the detach operation completed. However, it was interrupted by the update of **desiredStateOfWorld**.

### How can we reproduce it (as minimally and precisely as possible)?

`kubernetes/pkg/controller/volume/attachdetach/reconciler/reconciler.go:`
``` kubernetes/pkg/controller/volume/attachdetach/reconciler/reconciler.go
			klog.Errorf("force skip detaching")
			continue
			// Update Node Status to indicate volume is no longer safe to mount.
			err = rc.nodeStatusUpdater.UpdateNodeStatuses()
			if err != nil {
				// Skip detaching this volume if unable to update node status
				klog.Errorf(attachedVolume.GenerateErrorDetailed("UpdateNodeStatuses failed while attempting to report volume as attached", err).Error())
				continue
			}
```
1. Insert a log and `continue` before `rc.nodeStatusUpdater.UpdateNodeStatuses()`
2. Restart  a pod  mounting pv

Then you'll found log message "force skip detaching" would disappear after a few loops of `reconcile()`

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"archive", BuildDate:"2021-05-10T07:53:22Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

_No response_

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by 249043822**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #111000 and complete https://github.com/kubernetes/kubernetes/pull/104526

#### Special notes for your reviewer:
/cc @jingxu97 @gnufied @msau42 
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/volume/attachdetach/reconciler/reconciler.go [hunk 1]
```diff
@@ -251,6 +251,9 @@ func (rc *reconciler) reconcile() {
 			if err != nil {
 				// Skip detaching this volume if unable to update node status
 				klog.ErrorS(err, "UpdateNodeStatusForNode failed while attempting to report volume as attached", "volume", attachedVolume)
+				// Add volume back to ReportAsAttached if UpdateNodeStatusForNode call failed so that node status updater will add it back to VolumeAttached list.
+				// It is needed here too because DetachVolume is not call actually and we keep the data consistency for every reconcile.
+				rc.actualStateOfWorld.AddVolumeToReportAsAttached(attachedVolume.VolumeName, attachedVolume.NodeName)
```
Comment (jingxu97) [inline pkg/controller/volume/attachdetach/reconciler/reconciler.go:256]: The change looks good, the only small thing is that once calling AddVolumeToReportAsAttached, the statusUpdateNeeded will be set true, and node status will update again, but actually nothing has changed.

I think in the future we might rethink how to simply logic related update volume attached list, the current logic is proven to be error-prune.

**Comment by jingxu97** [comment]
@249043822 , thank you for the PR for fixing the issue! Do you think it is easy to add some sort of unit test about the behavior?

**Comment by jingxu97** [comment]
/lgtm

@gnufied could you help review and approve?

**Comment by 249043822** [comment]
> @249043822 , thank you for the PR for fixing the issue! Do you think it is easy to add some sort of unit test about the behavior?

I will see and try

**Comment by 249043822** [comment]
Added unit test, /cc @jingxu97 @gnufied again, thanks

File: pkg/controller/volume/attachdetach/reconciler/reconciler.go (hunk 1 above)
Comment (gnufied) [reply pkg/controller/volume/attachdetach/reconciler/reconciler.go:256]: It seems to me the problem is - `UpdateNodeStatusForNode` fails but `UpdateNodeStatuses` succeeds later on then, second time a detach is performed then `RemoveVolumeFromReportAsAttached` will fail because volume was previously removed from the list of `volumesToReportAsAttached` volumes. 

I wonder if a better fix here would be to return a different error from function `RemoveVolumeFromReportAsAttached` and if volume is already removed from list of `reportAsAttached` volumes then let the detach proceed. 

This would avoid the flapping of states that @jingxu97 talking about.

Comment (249043822) [reply pkg/controller/volume/attachdetach/reconciler/reconciler.go:256]: @gnufied I think what you said is another problem again, this problem should be as follows step:
1. Pod is deleting
2. remove volume from reportedAsAttached, so node status updater will
update volumeAttached list
3. `UpdateNodeStatusForNode ` fails but `UpdateNodeStatuses ` succeeds later on then
4. another pod is added which using the same volume on the same node
5. reconciler loops and it will NOT try to tigger detach anymore because asw is consistent with dsw

At this point, volume is still attached and in actual state, but
volumeAttached list in node status does not has this volume anymore, and
will block volume mount from kubelet.

Comment (gnufied) [reply pkg/controller/volume/attachdetach/reconciler/reconciler.go:256]: Hmm yeah I think this patch however does fix that error too. I agree with @jingxu97 that this logic is too error prone and should be simplified.

**Comment by jingxu97** [comment]
We need to cherrypick this fix @249043822

**Comment by arvindbd** [comment]
We are seeing this issue in 1.21.13. 
@249043822 Can this be backported to 1.21 as well? 🙏
