### PR TITLE
Differentiate between server error messages and client error messages in kubectl

### LINKED ISSUE #3937: kubectl should clarify whether errors are self-generated or as-reported-by-the-master
kubectl should clarify whether errors are self-generated or as-reported-by-the-master.  E.g., it's not clear whether the following means kubectl couldn't contact the master, or the master itself reported the error (which is what was happening in this case)

% gcloud preview container pods --cluster=${PROJECT} list
ERROR: F0129 10:20:43.796366   29535 get.go:158] 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

%

I'd propose adding some sort of prefix to the error message: "Master reported error 501: etc" but anything equivalent would be reasonable.

Part of #3936 tracking long-running cluster use.

### PR DESCRIPTION
**Pull request by brendandburns**
Closes https://github.com/GoogleCloudPlatform/kubernetes/issues/3937

### CODE REVIEW

**Comment by brendandburns** [comment]
ok, fixed the test, so much for refactoring on the fly while I'm in there...

**Comment by erictune** [comment]
@ghodss I can't assign this to you, but are you a good person to review this?

**Comment by jlowdermilk** [comment]
Reviewing.

File: pkg/kubectl/cmd/cmd.go [hunk 1]
```diff
@@ -331,7 +332,16 @@ func DefaultClientConfig(flags *pflag.FlagSet) clientcmd.ClientConfig {
 
 func checkErr(err error) {
```
Comment (jlowdermilk) [inline pkg/kubectl/cmd/cmd.go]: I recall a few people, (@smarterclayton and others) saying this pattern is bad and we should discontinue it. I'm personally fine with the pattern if it actually does error parsing work instead of just wrapping logfatal.

That being said, there is a duplicate declaration of checkErr in pkg/cmd/util/helpers.go (mea culpa; I was lazy and didn't want to sed across all occurrences). IMO, it should just be declared in pkg/cmd/util. Please add a TODO to move it there, and I will do so after merging this.

Comment (smarterclayton) [inline pkg/kubectl/cmd/cmd.go]: We're really trying to nuke this because it makes commands untestable in units.  Making it public is an implicit endorsement...

Comment (ghodss) [inline pkg/kubectl/cmd/cmd.go]: The abstraction of functionality to handle an error is not a problem - the problem is calling this functionality from all the various functions from which we call it. I added some comments on #2146 (the issue that I think you're referring to) to clarify. In this case we're abstracting out the program printing a specific kind of string and then fataling on error. As long as that's the same functionality that the util function provides, then it's okay to merge them, but I don't think having two of these functions is intrinsically an issue. Probably the naming could be improved... `fatalOnError` would be better.

Comment (ghodss) [inline pkg/kubectl/cmd/cmd.go]: Another reason it may not make sense to merge them is that the messages added here are specifically designed to be a kubectl enhancement - see #3937. They wouldn't necessarily make sense outside kubectl context.

File: pkg/client/request.go [hunk 2]
```diff
@@ -556,7 +562,8 @@ func (r *Request) transformResponse(resp *http.Response, req *http.Request) ([]b
 		// no-op, we've been upgraded
 	case resp.StatusCode < http.StatusOK || resp.StatusCode > http.StatusPartialContent:
 		if !isStatusResponse {
-			var err error = &UnexpectedStatusError{
+			var err error
+			err = &UnexpectedStatusError{
```
Comment (ghodss) [inline pkg/client/request.go]: Does this need to be changed? Just for my own education...

File: pkg/kubectl/cmd/cmd.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/kubectl/cmd/cmd.go]: Go has a pattern for handling errors.  We should be using it...  The command execution functions not returning an error is a quirk of commander, not a behavior we should be mimicking.

----- Original Message -----

Comment (jlowdermilk) [inline pkg/kubectl/cmd/cmd.go]: @smarterclayton, apologies if I'm being dense, but what is the pattern you are suggesting we use here? Log error and then return? Or are you suggesting that we fork/upstream commander's Run function to return an error and push error handling into the command framework?

Comment (smarterclayton) [inline pkg/kubectl/cmd/cmd.go]: Example:

```
func (f *Factory) NewCmdGet(out io.Writer) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "get [(-o|--output=)json|yaml|template|...] <resource> [<id>]",
		Short:   "Display one or many resources",
		Long:    get_long,
		Example: get_example,
		Run: func(cmd *cobra.Command, args []string) {
			RunGet(f, out, cmd, args)
		},
	}
        // ...
	return cmd
}
```

Should probably be

```
func (f *Factory) NewCmdGet(out io.Writer) *cobra.Command {
	cmd := &cobra.Command{
		Use:     "get [(-o|--output=)json|yaml|template|...] <resource> [<id>]",
		Short:   "Display one or many resources",
		Long:    get_long,
		Example: get_example,
		Run: func(cmd *cobra.Command, args []string) {
			err := RunGet(f, out, cmd, args)
			checkErr(err)
		},
	}
        // ...
	return cmd
}
```

There's no reason our code has to run inside of the Run() method.  That would then allow us to a) unit test RunGet (which we need to be able to do) and b) centralize all exit handling.

----- Original Message -----

Comment (jlowdermilk) [inline pkg/kubectl/cmd/cmd.go]: sgtm. The scope of this PR is addressing the sever-vs-client error origin (#3937). Are you ok with merging this as is and opening a separate issue for the (mostly mindless) task of converting all commands to use the above error handling pattern?

Comment (smarterclayton) [inline pkg/kubectl/cmd/cmd.go]: Its already covered in https://github.com/GoogleCloudPlatform/kubernetes/issues/2146

----- Original Message -----

File: pkg/kubectl/cmd/cmd.go [hunk 3]
```diff
@@ -331,7 +332,16 @@ func DefaultClientConfig(flags *pflag.FlagSet) clientcmd.ClientConfig {
...
 	if err != nil {
-		glog.FatalDepth(1, err.Error())
+		if errors.IsStatusError(err) {
```
Comment (smarterclayton) [inline pkg/kubectl/cmd/cmd.go]: Wait.... glog.Fatal from here is really bad.  We shouldn't have been doing that in the first place...

Comment (smarterclayton) [inline pkg/kubectl/cmd/cmd.go]: Oh wait, bad github diff (sorry, never mind)

File: pkg/client/request.go (hunk 2 above)
Comment (jlowdermilk) [inline pkg/client/request.go]: More of a style thing, I think. The pattern is to either declare a variable with `var name type` and assign to it later or let the compiler infer type by assigning with `name := `. Doing both in the same statement is unnecessary.

**Comment by jlowdermilk** [comment]
lgtm. I'm happy to merge this as is and pick up the follow up task to fix error returning for all commands (#2146, [comment](https://github.com/GoogleCloudPlatform/kubernetes/pull/5016#discussion_r25817768)). Will wait on lgtm from @smarterclayton before merging.

**Comment by smarterclayton** [comment]
LGTM
