### PR TITLE
kubelet: retry pod sandbox creation when containers were never created

### LINKED ISSUE #79398: kubelet won't retry PodSandbox creation for pods with restart policy "Never"
**What happened**:

If a pod's restart policy is "Never", and kubelet failed to create the PodSandbox (for whatever reason) once, the pod will be stuck at "ContainerCreating" forever.

**What you expected to happen**:
Since the user/application containers were never created, kubelet should retry the PodSandbox creation.

The fact that the pod remains in a ContainerCreating state while kubelet explicitly does nothing to resolve the situation also confuses the user.

**How to reproduce it (as minimally and precisely as possible)**:
I don't have an easy way to trigger a podsandbox creation failure off the top of my head, but this should be doable by messing with the CNI binaries/configurations.

**Anything else we need to know?**:

Relevant code snippet: 
https://github.com/kubernetes/kubernetes/blob/v1.16.0-alpha.0/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L474-L482

**Environment**:
- Kubernetes version (use `kubectl version`): Only checked the master branch (1.16), but all supported release branches should have the issue
- Cloud provider or hardware configuration: not relevant
- OS (e.g: `cat /etc/os-release`): not relevant
- Kernel (e.g. `uname -a`): not relevant
- Install tools:
- Network plugin and version (if this is a network-related bug): not relevant; though the initial PodSandbox creation failure could be caused by networking issues.
- Others:

### PR DESCRIPTION
**Pull request by yujuhong**
If kubelet never gets past sandbox creation (i.e., never attempted to
create containers for a pod), it should retry the sandbox creation on
failure, regardless of the restart policy of the pod.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change

/kind bug

> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #79398

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix a bug where kubelet would not retry pod sandbox creation when the restart policy of the pod is Never
```

### CODE REVIEW

**Comment by yujuhong** [comment]
The regression was introduced in 1.13. We need to patch 1.15, 1.14, and 1.13.

**Comment by yujuhong** [comment]
The original change was introduced in #68980  /cc @derekwaynecarr

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 1]
```diff
@@ -472,11 +472,15 @@ func (m *kubeGenericRuntimeManager) computePodActions(pod *v1.Pod, podStatus *ku
 	// If we need to (re-)create the pod sandbox, everything will need to be
 	// killed and recreated, and init containers should be purged.
 	if createPodSandbox {
-		if !shouldRestartOnFailure(pod) && attempt != 0 {
+		if !shouldRestartOnFailure(pod) && attempt != 0 && len(podStatus.ContainerStatuses) != 0 {
```
Comment (hex108) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: Should we also add check `len(podStatus.InitContainerStatuses) != 0`?

**Review by mattjmcnaughton — APPROVED** [review]
/lgtm

modulo the open question about init containers this looks good to me! Thanks for the quick fix and for adding a test case.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 1 above)
Comment (yujuhong) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: This is a kubelet's internal type; there's no initcontianerstatuses.

Comment (yujuhong) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go]: The unit tests added show that this would work for init containers too.

**Comment by dashpole** [comment]
/lgtm
Thanks for the fix!

**Comment by yujuhong** [comment]
/retest

Don't think this change would affect pull-kubernetes-kubemark-e2e-gce-big

**Comment by stamak** [comment]
sonobuoy e2e reports 
`[k8s.io] InitContainer [NodeConformance] should not start app containers and fail the pod if init containers fail on a RestartNever pod [Conformance]`
Could not ^^ be related to this changes in k8s 1.14.4?
Thx

**Comment by johnpipi** [comment]
from what version of kubernetes is this fix part of?

**Comment by ashb** [comment]
> from what version of kubernetes is this fix part of?

1.16+
