### PR TITLE
Fix: Clarify optional podSelector in NetworkPolicy docs and schema

### LINKED ISSUE #130896: Required field is not actually required
### What happened?

I am trying to solve the mystery of the "required" podSelector field in NetworkPolicy spec. It says that the field is "not optional" https://github.com/kubernetes/api/blob/c3130ba7ba2323372534032dd3153bf331fc59e2/networking/v1/types.go#L66-L68 but at the same time you can create a netpol without podSelector even being set, and it will be populated to the empty selector.
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#optional-vs-required says
> The API server should not allow POSTing or PUTing a resource with this (required) field unset.

The fun part is that multi-netpol has coped fields from the netpol https://github.com/k8snetworkplumbingwg/multi-networkpolicy/blob/master/pkg/apis/k8s.cni.cncf.io/v1beta2/types.go#L65C2-L65C55
and (because it is a crd?) it doesn't allow this filed to be unset and returns "The MultiNetworkPolicy is invalid: spec.podSelector: Required value"

### What did you expect to happen?

NetworkPolicy with empty podSelector to be rejected.
CRD and core APIs behave the same way.

### How can we reproduce it (as minimally and precisely as possible)?
netpol.yaml
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: egress-deny
spec:
  policyTypes:
  - Egress
```
```
$ kubectl apply -f netpol.yaml
networkpolicy.networking.k8s.io/egress-deny created
$ kubectl get networkpolicy -oyaml
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    ...
  spec:
    podSelector: {}
    policyTypes:
    - Egress
kind: List
metadata:
  resourceVersion: ""
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.32.1
Kustomize Version: v5.5.0
Server Version: v1.31.1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by tomoish**
Updates references and descriptions to reflect that `podSelector` in `NetworkPolicy` objects can be omitted, defaulting to matching all pods in the namespace.

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
- What this PR does
  - This PR addresses the documentation and schema inconsistencies regarding the `podSelector` field in Kubernetes `NetworkPolicy` objects. 

  - This change updates the documentation, OpenAPI specifications, Go structs, and generated Protobuf files to accurately reflect that `podSelector` is optional. When omitted, it defaults to an empty selector, which matches all pods within the policy's namespace.

- Why we need it.
Previous documentation and comments were misleading: they implied `podSelector` was required and only governed ingress behavior. This update aligns all docs, schemas, and code comments with the actual behavior—making `podSelector` optional and applicable to both ingress and egress.

#### Which issue(s) this PR fixes:

Fixes #130896

#### Does this PR introduce a user-facing change?

```release-note
 This PR corrects that documentation, making it clear to users that podSelector is optional and describes its default behavior.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/apis/networking/types.go [hunk 1]
```diff
@@ -53,8 +53,10 @@ type NetworkPolicySpec struct {
 	// The array of ingress rules is applied to any pods selected by this field.
 	// Multiple network policies can select the same set of pods. In this case,
 	// the ingress rules for each are combined additively.
-	// This field is NOT optional and follows standard label selector semantics.
-	// An empty podSelector matches all pods in this namespace.
+	// This field is optional. If it is not specified, it defaults to an empty selector,
+	// which matches all pods in this namespace.
+	// An explicitly specified empty selector also matches all pods.
+	// +optional
```
Comment (danwinship) [inline pkg/apis/networking/types.go:59]: Hm. I don't like talking about the default and then going back to add more detail about the non-default case.

Also, the existing text turns out to have _another_ bug; it shouldn't say "ingress rules" since this applies to egress as well.

So how about

```
	// podSelector selects the pods to which this NetworkPolicy object applies.
	// The array of rules is applied to any pods selected by this field. An empty
	// selector matches all pods in the policy's namespace.
	// Multiple network policies can select the same set of pods. In this case,
	// the ingress rules for each are combined additively.
	// This field is optional. If it is not specified, it defaults to an empty selector.
	// +optional
```

and then the same in the other copy.

**Comment by danwinship** [comment]
/lgtm
/approve
(but it's going to sit for a few days until the tree unfreezes for 1.33)

**Comment by danwinship** [comment]
/assign @thockin
for api (docs) approval

File: staging/src/k8s.io/api/networking/v1/types.go [hunk 2]
```diff
@@ -60,12 +60,13 @@ const (
...
+	// The array of rules is applied to any pods selected by this field. An empty
+	// selector matches all pods in the policy's namespace.
 	// Multiple network policies can select the same set of pods. In this case,
 	// the ingress rules for each are combined additively.
-	// This field is NOT optional and follows standard label selector semantics.
-	// An empty podSelector matches all pods in this namespace.
-	PodSelector metav1.LabelSelector `json:"podSelector" protobuf:"bytes,1,opt,name=podSelector"`
+	// This field is optional. If it is not specified, it defaults to an empty selector.
+	// +optional
+	PodSelector metav1.LabelSelector `json:"podSelector,omitempty" protobuf:"bytes,1,opt,name=podSelector"`
```
Comment (liggitt) [inline staging/src/k8s.io/api/networking/v1/types.go]: don't add `omitempty`, which has serialization implications, just add the `+optional` bit

Comment (tomoish) [reply staging/src/k8s.io/api/networking/v1/types.go]: @liggitt Thank you for your review. I've fixed it.

**Comment by danwinship** [comment]
/lgtm

> don't add `omitempty`, which has serialization implications, just add the `+optional` bit

does it really matter? it reads back the same way either way
