### PR TITLE
delete dependent pods for rs when deleting deployments

### LINKED ISSUE #44046: Deleting a deployment doesn't delete the pods
**BUG REPORT**:

**Kubernetes version**: 1.6.1

**Environment**:
- **Hardware configuration**: 2 identical machines, with i7-2600K CPUs and 4GB RAM.
- **OS**: CentOS 7
- **Kernel**: 3.10.0-514.10.2.el7.x86_64
- **Install tools**: KubeADM

**What happened**:
Deleting a deployment via the API with the DeleteOptions settings `orphanDependants: false` or `propagationPolicy: Background` deletes the Deployment and the replica set but NOT the pods.
Deleting it with the DeleteOptions setting `propagationPolicy: Foreground` works as intended.

**What you expected to happen**:
The replica set deletion should propagate to the pods. I've read that the garbage collection should work for Deployments in 1.6.

**How to reproduce it**:

```
kubectl create -f https://raw.githubusercontent.com/kubernetes/kubernetes.github.io/master/docs/concepts/workloads/controllers/nginx-deployment.yaml
curl -X DELETE localhost:8001/apis/extensions/v1beta1/namespaces/default/deployments/nginx-deployment -d '{"kind":"DeleteOptions","apiVersion":"v1","propagationPolicy":"Background"}' -H "Content-Type: application/json"
```

**Anything else we need to know**:
I am using the [Python Client](https://github.com/kubernetes-incubator/client-python/) and at the moment it only supports the orphanDependants option, since it's still at api version 1.5.

### PR DESCRIPTION
**Pull request by krmayankk**
Fix #44046, where user reported that the garbage collector didn't delete pods when a deployment was deleted with PropagationPolicy=Background.

### CODE REVIEW

File: pkg/controller/controller_ref_manager.go [hunk 1]
```diff
@@ -346,6 +346,7 @@ func (m *ReplicaSetControllerRefManager) AdoptReplicaSet(rs *extensions.ReplicaS
 	if err := m.canAdopt(); err != nil {
 		return fmt.Errorf("can't adopt ReplicaSet %v/%v (%v): %v", rs.Namespace, rs.Name, rs.UID, err)
 	}
+	rs.Finalizers = append(rs.Finalizers, metav1.FinalizerDeleteDependents)
```
Comment (kargakis) [inline pkg/controller/controller_ref_manager.go]: I think this update needs to be part of the patch.

**Comment by kargakis** [comment]
@krmayankk you'll also need to set the finalizer during creation of the RS. Also we need to verify either via an integration or e2e test that this is working.

File: pkg/controller/controller_ref_manager.go (hunk 1 above)
Comment (deads2k) [inline pkg/controller/controller_ref_manager.go]: @caesarxuchao I thought we did this finalizer manipulation in the REST storage layer.

Comment (caesarxuchao) [inline pkg/controller/controller_ref_manager.go]: We intend to set the Replicaset.ObjectMeta.Finalizer to DeletingDependents when deployment create/adopt the replicaset, otherwise we hit #44046.

@krmayankk we shouldn't change the object we get from the informer. We should send a patch to the apiserver here.

Comment (krmayankk) [inline pkg/controller/controller_ref_manager.go]: fixed

**Comment by krmayankk** [comment]
@kargakis @caesarxuchao is this the right place to add tests https://github.com/kubernetes/kubernetes/blob/master/test/e2e/deployment.go ?

**Comment by kargakis** [comment]
Since this needs testing API-wise only then try adding the test in https://github.com/kubernetes/kubernetes/tree/master/test/integration/deployment

**Comment by kargakis** [comment]
> you'll also need to set the finalizer during creation of the RS.

https://github.com/kubernetes/kubernetes/blob/249551461e038df9dae5e1a932334aa66a8dc701/pkg/controller/deployment/sync.go#L292-L297

**Comment by caesarxuchao** [comment]
I think you can just update the tests you wrote before: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/garbage_collector.go#L112

File: pkg/controller/controller_ref_manager.go [hunk 2]
```diff
@@ -349,7 +349,12 @@ func (m *ReplicaSetControllerRefManager) AdoptReplicaSet(rs *extensions.ReplicaS
 	// Note that ValidateOwnerReferences() will reject this patch if another
 	// OwnerReference exists with controller=true.
 	addControllerPatch := fmt.Sprintf(
-		`{"metadata":{"ownerReferences":[{"apiVersion":"%s","kind":"%s","name":"%s","uid":"%s","controller":true,"blockOwnerDeletion":true}],"uid":"%s"}}`,
+		`{"metadata":{
+			"ownerReferences":[{"apiVersion":"%s","kind":"%s","name":"%s","uid":"%s","controller":true,"blockOwnerDeletion":true}],
+			"uid":"%s",
+		    "finalizers": ["foregroundDeletion"],
```
Comment (caesarxuchao) [inline pkg/controller/controller_ref_manager.go]: Could you add/update unit test for the patch?

As @kargakis mentioned, could you also add the finalizer when the rs are created?

Comment (tnozicka) [inline pkg/controller/controller_ref_manager.go]: @krmayankk that trailing comma is invalid JSON

Comment (tnozicka) [inline pkg/controller/controller_ref_manager.go]: It might also be nice to substitute the magic value from `metav1.FinalizerDeleteDependents`

File: pkg/controller/deployment/sync.go [hunk 3]
```diff
@@ -294,6 +294,7 @@ func (dc *DeploymentController) getNewReplicaSet(deployment *extensions.Deployme
 			Name:            deployment.Name + "-" + podTemplateSpecHash,
 			Namespace:       namespace,
 			OwnerReferences: []metav1.OwnerReference{*newControllerRef(deployment)},
+			Finalizers:      []string{metav1.FinalizerDeleteDependents},
```
Comment (tnozicka) [inline pkg/controller/deployment/sync.go]: I don't think this can work unless https://github.com/kubernetes/kubernetes/pull/46500 is merged but I am willing to be proven wrong

**Review by tnozicka — CHANGES_REQUESTED** [review]
invalid JSON (+ maybe https://github.com/kubernetes/kubernetes/pull/46500)

**Comment by tnozicka** [comment]
@krmayankk should we delete the finalizer as well when doing ReleaseReplicaSet?

File: pkg/controller/controller_ref_manager.go (hunk 2 above)
Comment (krmayankk) [inline pkg/controller/controller_ref_manager.go]: thanks @tnozicka will fix this once i have figured out the tests.

**Comment by krmayankk** [comment]
@caesarxuchao could  you take a look at this ?

File: test/e2e/garbage_collector.go [hunk 4]
```diff
@@ -132,6 +132,15 @@ func verifyRemainingDeploymentsAndReplicaSets(
 		ret = false
 		By(fmt.Sprintf("expected %d Deploymentss, got %d Deployments", deploymentNum, len(deployments.Items)))
 	}
+	pods, err := clientSet.CoreV1().Pods(f.Namespace.Name).List(metav1.ListOptions{})
+	if err != nil {
+		return false, fmt.Errorf("Failed to list pods: %v", err)
+	}
+	if len(rsNum) == 0 && len(pods) != 0 {
```
Comment (caesarxuchao) [inline test/e2e/garbage_collector.go]: Can you plumb in the podNum and check if `len(pods)!=podNum`?

File: pkg/controller/controller_ref_manager.go [hunk 5]
```diff
@@ -349,7 +349,12 @@ func (m *ReplicaSetControllerRefManager) AdoptReplicaSet(rs *extensions.ReplicaS
 	// Note that ValidateOwnerReferences() will reject this patch if another
 	// OwnerReference exists with controller=true.
 	addControllerPatch := fmt.Sprintf(
-		`{"metadata":{"ownerReferences":[{"apiVersion":"%s","kind":"%s","name":"%s","uid":"%s","controller":true,"blockOwnerDeletion":true}],"uid":"%s"}}`,
+		`{"metadata":{
```
Comment (caesarxuchao) [inline pkg/controller/controller_ref_manager.go]: Could you fix the indention of the patch? Also it might be a good idea to add a unit test for the patch, i don't know if the patch system is picky on the indentions and newlines

File: pkg/controller/controller_ref_manager.go [hunk 6]
```diff
@@ -349,7 +349,12 @@ func (m *ReplicaSetControllerRefManager) AdoptReplicaSet(rs *extensions.ReplicaS
...
+			"ownerReferences":[{"apiVersion":"%s","kind":"%s","name":"%s","uid":"%s","controller":true,"blockOwnerDeletion":true}],
+			"uid":"%s",
```
Comment (kow3ns) [inline pkg/controller/controller_ref_manager.go]: I believe that PatchReplicaSet uses strategic merge patch. If this is the case, why do you reset the UID?

File: pkg/controller/controller_ref_manager.go (hunk 5 above)
Comment (krmayankk) [inline pkg/controller/controller_ref_manager.go]: fixed

Comment (krmayankk) [inline pkg/controller/controller_ref_manager.go]: for the unit tests i will try to find an example. Let me know if you have a pointer.

Comment (krmayankk) [inline pkg/controller/controller_ref_manager.go]: @caesarxuchao the e2e deployment test is failing to create rs. It seems my patch is wrong. The relevant failure logs here https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/45764/pull-kubernetes-e2e-kops-aws/25580/

**Comment by krmayankk** [comment]
@tnozicka i rebased your changes , but my e2e for deployment fails to create replica sets.

**Comment by kargakis** [comment]
@tnozicka ptal

File: test/e2e/garbage_collector.go [hunk 7]
```diff
@@ -132,6 +132,15 @@ func verifyRemainingDeploymentsAndReplicaSets(
 		ret = false
 		By(fmt.Sprintf("expected %d Deploymentss, got %d Deployments", deploymentNum, len(deployments.Items)))
 	}
+	pods, err := clientSet.CoreV1().Pods(f.Namespace.Name).List(metav1.ListOptions{})
+	if err != nil {
+		return false, fmt.Errorf("Failed to list pods: %v", err)
+	}
+	if len(rsNum) == 0 && len(pods) != podNum {
```
Comment (tnozicka) [inline test/e2e/garbage_collector.go]: @krmayankk 
`len(rsNum)` -  is type `int` - that can't work, right?
`len(pods)` - is type `*"k8s.io/kubernetes/pkg/api/v1".PodList` - I don't think this can work either 

I would suggest something like: `if rsNum == 0 && pods.Size() != podNum {`

Comment (kargakis) [inline test/e2e/garbage_collector.go]: podNum is already passed as zero. It seems you only need `if len(pods.Items) != podNum {`

Comment (kargakis) [inline test/e2e/garbage_collector.go]: Also you need to update the function comment.

File: pkg/controller/controller_ref_manager.go [hunk 8]
```diff
@@ -349,7 +349,7 @@ func (m *ReplicaSetControllerRefManager) AdoptReplicaSet(rs *extensions.ReplicaS
 	// Note that ValidateOwnerReferences() will reject this patch if another
 	// OwnerReference exists with controller=true.
 	addControllerPatch := fmt.Sprintf(
-		`{"metadata":{"ownerReferences":[{"apiVersion":"%s","kind":"%s","name":"%s","uid":"%s","controller":true,"blockOwnerDeletion":true}],"uid":"%s"}}`,
+		`{"metadata":{"ownerReferences":[{"apiVersion":"%s","kind":"%s","name":"%s","uid":"%s","controller":true,"blockOwnerDeletion":true}],"uid":"%s","finalizers": ["foregroundDeletion"]}}`,
```
Comment (kargakis) [inline pkg/controller/controller_ref_manager.go]: Can you indent the json for better readability?

Comment (caesarxuchao) [inline pkg/controller/controller_ref_manager.go]: Can you add a unit test to test the patch? Something similar to https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/garbagecollector/garbagecollector_test.go#L538-L588.

Comment (caesarxuchao) [inline pkg/controller/controller_ref_manager.go]: Also please update the godoc saying this function sets the finalizers.

**Comment by caesarxuchao** [comment]
It's compile error:
```
W0613 17:24:38.401] # k8s.io/kubernetes/test/e2e
W0613 17:24:38.402] test/e2e/garbage_collector.go:139: invalid argument rsNum (type int) for len
W0613 17:24:38.402] test/e2e/garbage_collector.go:139: invalid argument pods (type *"k8s.io/kubernetes/pkg/api/v1".PodList) for len
W0613 17:24:38.420] !!! [0613 17:24:38] Call tree:
```

**Comment by kargakis** [comment]
@krmayankk can you address the remaining comments? We really need to fix this for 1.7 and also backport to 1.6.

**Comment by krmayankk** [comment]
@kargakis addressing now. sorry for the delay

**Comment by kargakis** [comment]
Squash and this should be good to merge.

**Comment by caesarxuchao** [comment]
lgtm. Please squash. Thanks.

File: test/e2e/garbage_collector.go [hunk 9]
```diff
@@ -107,13 +107,14 @@ func newOwnerRC(f *framework.Framework, name string, replicas int32) *v1.Replica
 }
 
 // verifyRemainingDeploymentsAndReplicaSets verifies if the number
-// of the remaining deployment and rs are deploymentNum and rsNum.
-// It returns error if the communication with the API server fails.
+// of the remaining deployments, replica set and pods are deploymentNum,
+// rsNum and podNum. It returns error if the communication with the API
+// server fails.
 func verifyRemainingDeploymentsAndReplicaSets(
```
Comment (caesarxuchao) [inline test/e2e/garbage_collector.go]: Sorry i didn't notice this earlier, we should update the function name. verifyRemainingDeploymentsReplicaSetsPods? Or maybe just verifyRemainingObjects.

Comment (krmayankk) [inline test/e2e/garbage_collector.go]: fixed

**Comment by kargakis** [comment]
This is a bug we have in Deployments since 1.6 so manually approving to get it merged in time for 1.7. We also need to backport it in 1.6.

File: pkg/controller/controller_ref_manager.go [hunk 10]
```diff
@@ -350,7 +351,14 @@ func (m *ReplicaSetControllerRefManager) AdoptReplicaSet(rs *extensions.ReplicaS
 	// Note that ValidateOwnerReferences() will reject this patch if another
 	// OwnerReference exists with controller=true.
 	addControllerPatch := fmt.Sprintf(
-		`{"metadata":{"ownerReferences":[{"apiVersion":"%s","kind":"%s","name":"%s","uid":"%s","controller":true,"blockOwnerDeletion":true}],"uid":"%s"}}`,
+		`{
+			"metadata":
+			{	
+				"ownerReferences": [{"apiVersion":"%s","kind":"%s","name":"%s","uid":"%s","controller":true,"blockOwnerDeletion":true}],
+				"uid":"%s",
+				"finalizers": ["foregroundDeletion"]
```
Comment (caesarxuchao) [inline pkg/controller/controller_ref_manager.go]: Maybe in a followup we can make this line "finalizers": ["%s"] and supply metav1.FinalizerDeleteDependents.

**Comment by caesarxuchao** [comment]
@janetkuo could you approve the change? Thanks.

**Review by janetkuo — APPROVED** [review]

File: pkg/controller/controller_ref_manager.go (hunk 10 above)
Comment (krmayankk) [inline pkg/controller/controller_ref_manager.go]: will fix in a subsequent PR

Comment (liggitt) [inline pkg/controller/controller_ref_manager.go]: What does this mean? How does it make sense to create these with a foregroundDeletion finalizer and a default deletion propagation strategy of orphan? I never expected to see a foregroundDeletion finalizer on an object without a deletionTimestamp. @jwforres something like this might explain what you were seeing

Comment (caesarxuchao) [inline pkg/controller/controller_ref_manager.go]: Let's discuss in https://github.com/kubernetes/kubernetes/pull/44058#issuecomment-310230193. We need to pick the lesser of the two evils.
