### PR TITLE
federation: Fixing runtime-config support for federation-apiserver

### LINKED ISSUE #42587: federation: Disable batch and autoscaling group versions
Batch (jobs) and autoscaling (hpa) are enabled by default in federation-apiserver but the controllers for them were not merged before 1.6 code freeze. We need to disable the APIs.

cc @kubernetes/sig-federation-bugs

### PR DESCRIPTION
**Pull request by nikhiljindal**
Fixes https://github.com/kubernetes/kubernetes/issues/42587
Ref https://github.com/kubernetes/kubernetes/issues/38593

Fixing the broken `--runtime-config` flag support in federation-apiserver. Fixing the bugs and using it to disable batch and autoscaling groups. Users can enable them by passing `--runtime-config=apis/all=true` to federation-apiserver.
~This also includes a bug fix to kube-apiserver registry that allows users to disable api/v1 resources~

cc @kubernetes/sig-federation-pr-reviews

### CODE REVIEW

**Comment by nikhiljindal** [comment]
Adding 1.6 milestone as this is a bug fix to be included in 1.6. Let me know if anyone feels otherwise.

File: pkg/registry/batch/rest/storage_batch.go [hunk 1]
```diff
@@ -52,15 +54,21 @@ func (p RESTStorageProvider) NewRESTStorage(apiResourceConfigSource serverstorag
...
 func (p RESTStorageProvider) v1Storage(apiResourceConfigSource serverstorage.APIResourceConfigSource, restOptionsGetter generic.RESTOptionsGetter) map[string]rest.Storage {
-	version := batchapiv1.SchemeGroupVersion
-
 	storage := map[string]rest.Storage{}
+	p.AddV1JobsStorage(apiResourceConfigSource, restOptionsGetter, storage)
+	return storage
+}
+
+// Adds rest storage interfaces for v1/jobs resource to the given storage map.
+func (p RESTStorageProvider) AddV1JobsStorage(apiResourceConfigSource serverstorage.APIResourceConfigSource, restOptionsGetter generic.RESTOptionsGetter, storage map[string]rest.Storage) {
```
Comment (deads2k) [inline pkg/registry/batch/rest/storage_batch.go]: Don't mutate your args.  It makes for really confusing code.

Comment (deads2k) [inline pkg/registry/batch/rest/storage_batch.go]: This function shouldn't be making a decision about enablement.  You asked to add them, you should add them.

File: pkg/registry/core/rest/storage_core.go [hunk 2]
```diff
@@ -179,50 +175,90 @@ func (c LegacyRESTStorageProvider) NewLegacyRESTStorage(restOptionsGetter generi
 
 	serviceRest := service.NewStorage(serviceRegistry, endpointRegistry, ServiceClusterIPAllocator, ServiceNodePortAllocator, c.ProxyTransport)
 
-	restStorageMap := map[string]rest.Storage{
```
Comment (deads2k) [inline pkg/registry/core/rest/storage_core.go]: This change is really significant.  Disabling bits of the core API isn't a thing that was generally support before.  I remember the code only allowed it for extensions and even that was probably a mistake.

I don't think that you should be able to pick and choose from groups as a rule.

File: pkg/registry/core/rest/storage_core.go [hunk 3]
```diff
@@ -179,50 +175,90 @@ func (c LegacyRESTStorageProvider) NewLegacyRESTStorage(restOptionsGetter generi
...
-		"secrets":                       secretStorage,
-		"serviceAccounts":               serviceAccountStorage,
-		"persistentVolumes":             persistentVolumeStorage,
-		"persistentVolumes/status":      persistentVolumeStatusStorage,
-		"persistentVolumeClaims":        persistentVolumeClaimStorage,
-		"persistentVolumeClaims/status": persistentVolumeClaimStatusStorage,
-		"configMaps":                    configMapStorage,
-
-		"componentStatuses": componentstatus.NewStorage(componentStatusStorage{c.StorageFactory}.serversToValidate),
+	restStorageMap := map[string]rest.Storage{}
```
Comment (sttts) [inline pkg/registry/core/rest/storage_core.go]: If we need this logic, isn't there some generic way to express it other than turning this func into something unreadable?

File: pkg/registry/batch/rest/storage_batch.go [hunk 4]
```diff
@@ -52,15 +54,21 @@ func (p RESTStorageProvider) NewRESTStorage(apiResourceConfigSource serverstorag
...
+	version := batchapiv1.SchemeGroupVersion
 	if apiResourceConfigSource.ResourceEnabled(version.WithResource("jobs")) {
 		jobsStorage, jobsStatusStorage := jobstore.NewREST(restOptionsGetter)
 		storage["jobs"] = jobsStorage
 		storage["jobs/status"] = jobsStatusStorage
+	} else {
+		glog.V(1).Infof("Skipping disabled resource batch/v1/jobs")
```
Comment (sttts) [inline pkg/registry/batch/rest/storage_batch.go]: There should be some generic way to output these message, not one Infof for each resource.

File: pkg/registry/core/rest/storage_core.go (hunk 2 above)
Comment (deads2k) [inline pkg/registry/core/rest/storage_core.go]: The option may have parsed before, but this group has never actually respected individual enablement.  I don't think we should start now.

File: federation/cmd/federation-apiserver/app/federation.go [hunk 5]
```diff
@@ -22,20 +22,33 @@ import (
...
 
-func installFederationAPIs(g *genericapiserver.GenericAPIServer, optsGetter generic.RESTOptionsGetter) {
-	clusterStorage, clusterStatusStorage := clusteretcd.NewREST(optsGetter)
-	federationResources := map[string]rest.Storage{
-		"clusters":        clusterStorage,
-		"clusters/status": clusterStatusStorage,
+func installFederationAPIs(g *genericapiserver.GenericAPIServer, optsGetter generic.RESTOptionsGetter, apiResourceConfigSource storage.APIResourceConfigSource) {
+	groupName := federation.GroupName
+	if !apiResourceConfigSource.AnyResourcesForGroupEnabled(groupName) {
+		glog.V(1).Infof("Skipping disabled API group %q", groupName)
```
Comment (sttts) [inline federation/cmd/federation-apiserver/app/federation.go]: This also looks like a lot of boilerplate code that should be done in a generic way somehow. The previously completely declarative style with one InstallAPIGroup style turned into some complex logic for each group. This will drift apart pretty fast.

**Comment by liggitt** [comment]
cc @kubernetes/sig-api-machinery-pr-reviews

File: pkg/registry/batch/rest/storage_batch.go (hunk 1 above)
Comment (nikhiljindal) [inline pkg/registry/batch/rest/storage_batch.go]: I want a method that also has the check. Will renaming this to AddV1JobsStorageIfEnabled help?

File: pkg/registry/core/rest/storage_core.go (hunk 2 above)
Comment (nikhiljindal) [inline pkg/registry/core/rest/storage_core.go]: Why not? Core is too broad. I want to disable just ReplicationControllers for example.
runtime-config allows users to disable groups, group versions or specific resources.
It will be confusing if some groups allow disabling specific resources while some groups do not.
I think this group not allowing disabling specific resources was actually a bug.

Comment (nikhiljindal) [inline pkg/registry/core/rest/storage_core.go]: On more research and help from @liggitt What you are saying is correct: https://github.com/kubernetes/kubernetes/pull/42303#issuecomment-283230144. Will update the PR

**Comment by ethernetdan** [comment]
Removing PR from 1.6 milestone since code freeze has begun:
* If this is a bug fix, please label as `kind/bug` and reapply the milestone.
* If this is a feature for 1.6, an [exception](https://github.com/kubernetes/features/blob/master/EXCEPTIONS.md) should be filed for it before 11:00PM PST on 3/2. Note that most exceptions to code freeze are not accepted.
* If this is a feature for 1.7, feel free to add the 1.7 milestone to the PR.

/cc @kubernetes/release-team @kubernetes/kubernetes-release-managers

**Comment by calebamiles** [comment]
I would really like to move this PR into the next milestone @nikhiljindal. It did not have an `lgtm` by code freeze and there are existing questions to be addressed from the review. There is also no additional test coverage in the PR nor any mention of the specific tests that the PR is supposed to address as a bug fix. Please add this information when available. Thanks!

**cc: @ethernetdan, @kubernetes/kubernetes-release-managers**

File: federation/cmd/federation-apiserver/app/federation.go (hunk 5 above)
Comment (nikhiljindal) [inline federation/cmd/federation-apiserver/app/federation.go]: Agreed. Updated to move the boilerplate code into a common method.

File: pkg/registry/batch/rest/storage_batch.go (hunk 1 above)
Comment (nikhiljindal) [inline pkg/registry/batch/rest/storage_batch.go]: Updated to return the map

Comment (nikhiljindal) [inline pkg/registry/batch/rest/storage_batch.go]: reverted changes to registry

File: pkg/registry/batch/rest/storage_batch.go (hunk 4 above)
Comment (nikhiljindal) [inline pkg/registry/batch/rest/storage_batch.go]: Moved it to a common function

File: pkg/registry/core/rest/storage_core.go (hunk 2 above)
Comment (nikhiljindal) [inline pkg/registry/core/rest/storage_core.go]: Updated the PR to revert this change

File: pkg/registry/core/rest/storage_core.go (hunk 3 above)
Comment (nikhiljindal) [inline pkg/registry/core/rest/storage_core.go]: reverted changes in this file.

**Comment by nikhiljindal** [comment]
Thanks for the great comments @deads2k and @sttts 
Updated the code as per comments.

Have also reverted changes to registry or other kubernetes code. The changes now are only limited to federation. PTAL

File: federation/cmd/federation-apiserver/app/autoscaling.go [hunk 6]
```diff
@@ -21,24 +21,35 @@ import (
...
 
-func installAutoscalingAPIs(g *genericapiserver.GenericAPIServer, optsGetter generic.RESTOptionsGetter) {
-	hpaStorage, hpaStatusStorage := hpastorage.NewREST(optsGetter)
-
-	autoscalingResources := map[string]rest.Storage{
-		"horizontalpodautoscalers":        hpaStorage,
-		"horizontalpodautoscalers/status": hpaStatusStorage,
+func installAutoscalingAPIs(g *genericapiserver.GenericAPIServer, optsGetter generic.RESTOptionsGetter, apiResourceConfigSource storage.APIResourceConfigSource) {
+	groupName := autoscaling.GroupName
+	hpaStorageFn := func() map[string]rest.Storage {
```
Comment (sttts) [inline federation/cmd/federation-apiserver/app/autoscaling.go]: why a func? Why not just inline?

File: federation/cmd/federation-apiserver/app/autoscaling.go [hunk 7]
```diff
@@ -21,24 +21,35 @@ import (
...
 )
 
-func installAutoscalingAPIs(g *genericapiserver.GenericAPIServer, optsGetter generic.RESTOptionsGetter) {
-	hpaStorage, hpaStatusStorage := hpastorage.NewREST(optsGetter)
-
-	autoscalingResources := map[string]rest.Storage{
-		"horizontalpodautoscalers":        hpaStorage,
-		"horizontalpodautoscalers/status": hpaStatusStorage,
+func installAutoscalingAPIs(g *genericapiserver.GenericAPIServer, optsGetter generic.RESTOptionsGetter, apiResourceConfigSource storage.APIResourceConfigSource) {
+	groupName := autoscaling.GroupName
```
Comment (sttts) [inline federation/cmd/federation-apiserver/app/autoscaling.go]: Unnecessary variable. Only used once. Inline.

File: federation/cmd/federation-apiserver/app/core.go [hunk 8]
```diff
@@ -41,28 +42,56 @@ import (
...
+		}
+	}
+	configmapsStorageFn := func() map[string]rest.Storage {
+		configMapStore := configmapstore.NewREST(optsGetter)
+		return map[string]rest.Storage{
+			"configmaps": configMapStore,
+		}
+	}
+	eventsStorageFn := func() map[string]rest.Storage {
+		eventStore := eventstore.NewREST(optsGetter, uint64(s.EventTTL.Seconds()))
```
Comment (sttts) [inline federation/cmd/federation-apiserver/app/core.go]: are these having any side effects? Or why are they a func and not just vars?

File: federation/cmd/federation-apiserver/app/install.go [hunk 9]
```diff
@@ -0,0 +1,55 @@
...
+	"k8s.io/apiserver/pkg/server/storage"
+)
+
+// Function to get a map of resources and the corresponding storages.
+type getResourcesStorageFunc func() map[string]rest.Storage
+
+// Filters the resources from the given resources storage map to those that are enabled in the given apiResourceConfigSource.
+// resourcesStorageMap is expected to contain all resources in a group version.
+// Returns false if none of the resources are enabled and hence the whole group version should be disabled.
+func getEnabledResources(groupVersion schema.GroupVersion, resourcesStorageMap map[string]getResourcesStorageFunc, apiResourceConfigSource storage.APIResourceConfigSource) (bool, map[string]rest.Storage) {
```
Comment (sttts) [inline federation/cmd/federation-apiserver/app/install.go]: s/getE/e/. `get*` is a Go anti-pattern.

File: federation/cmd/federation-apiserver/app/server.go [hunk 10]
```diff
@@ -108,8 +111,7 @@ func Run(s *options.ServerRunOptions) error {
 		return err
 	}
 
-	// TODO: register cluster federation resources here.
-	resourceConfig := serverstorage.NewResourceConfig()
+	resourceConfig := getDefaultResourceConfig()
```
Comment (sttts) [inline federation/cmd/federation-apiserver/app/server.go]: s/getD/d/

File: test/integration/federation/server_test.go [hunk 11]
```diff
@@ -69,11 +76,32 @@ func TestRun(t *testing.T) {
...
-	testAPIGroup(t)
-	testAPIResourceList(t)
+	testAPIGroupList(t, expectedGroupVersions)
+	testAPIGroup(t, expectedGroupVersions)
+	testAPIResourceList(t, expectedGroupVersions)
+}
+
+// Verifies that all APIs are enabled when runtime config is set to all.
+func TestRunWithRuntimeConfigAll(t *testing.T) {
+	securePort = 6443 + 5
```
Comment (sttts) [inline test/integration/federation/server_test.go]: Use framework.LocalPort from https://github.com/kubernetes/kubernetes/pull/42278/files#diff-efb71138113f6fe331f73e11c05e323aR519

File: test/integration/federation/server_test.go [hunk 12]
```diff
@@ -256,7 +298,7 @@ func testCoreResourceList(t *testing.T) {
 	}
 	assert.Equal(t, "", apiResourceList.APIVersion)
 	assert.Equal(t, v1.SchemeGroupVersion.String(), apiResourceList.GroupVersion)
-	// Assert that there are exactly 7 resources.
+	// Assert that there are exactly 8 resources.
```
Comment (sttts) [inline test/integration/federation/server_test.go]: drop the comment. No additional info.

**Comment by sttts** [comment]
@nikhiljindal left another couple of comments. But it looks much better already 👍

File: federation/cmd/federation-apiserver/app/autoscaling.go (hunk 7 above)
Comment (nikhiljindal) [inline federation/cmd/federation-apiserver/app/autoscaling.go]: removed

File: federation/cmd/federation-apiserver/app/autoscaling.go (hunk 6 above)
Comment (nikhiljindal) [inline federation/cmd/federation-apiserver/app/autoscaling.go]: Yes it does need to be a func, but I wrote it that way because I had some future refactoring in mind where I want this to be shared between kubernetes and federation. A single function that returns the storage for a resource (for ex storages for hpa and its subresources in this case).
I didnt do that refactoring in this PR but I do have plans for a follow up PR.

So if you think this is bad, then I can change this to inline for now and will change them to funcs later.
But if its fine then I will like to keep them as is. Let me know.

File: federation/cmd/federation-apiserver/app/core.go (hunk 8 above)
Comment (nikhiljindal) [inline federation/cmd/federation-apiserver/app/core.go]: no side effect. same as above

File: federation/cmd/federation-apiserver/app/install.go (hunk 9 above)
Comment (nikhiljindal) [inline federation/cmd/federation-apiserver/app/install.go]: hmm hadnt realized that. Fixed. Any link to docs that say that this is an anti-pattern?

File: federation/cmd/federation-apiserver/app/server.go (hunk 10 above)
Comment (nikhiljindal) [inline federation/cmd/federation-apiserver/app/server.go]: fixed

File: test/integration/federation/server_test.go (hunk 12 above)
Comment (nikhiljindal) [inline test/integration/federation/server_test.go]: removed

File: test/integration/federation/server_test.go (hunk 11 above)
Comment (nikhiljindal) [inline test/integration/federation/server_test.go]: I will let that PR get merged and update this in a follow up PR? We have an open issue for that https://github.com/kubernetes/kubernetes/issues/42400

**Comment by nikhiljindal** [comment]
Thanks for the review. Updated code as per comments. PTAL

**Comment by marun** [comment]
I think #42278 should merge before this.

**Comment by nikhiljindal** [comment]
@marun I want to see #42278 get merged soon as well. But I dont think we should block bug fixes for it.

File: federation/cmd/federation-apiserver/app/install.go [hunk 13]
```diff
@@ -0,0 +1,55 @@
...
+	"k8s.io/apiserver/pkg/registry/rest"
+	"k8s.io/apiserver/pkg/server/storage"
+)
+
+// Function to get a map of resources and the corresponding storages.
+type getResourcesStorageFunc func() map[string]rest.Storage
+
+// Filters the resources from the given resources storage map to those that are enabled in the given apiResourceConfigSource.
+// resourcesStorageMap is expected to contain all resources in a group version.
+// Returns false if none of the resources are enabled and hence the whole group version should be disabled.
```
Comment (sttts) [inline federation/cmd/federation-apiserver/app/install.go]: the bool is equivalent to `len(enabledResources) == 0` ? I would just remove it.

File: federation/cmd/federation-apiserver/app/autoscaling.go (hunk 6 above)
Comment (sttts) [inline federation/cmd/federation-apiserver/app/autoscaling.go]: It's not bad, only looks like there is some reason like side-effects behind that is not obvious.

File: federation/cmd/federation-apiserver/app/install.go (hunk 9 above)
Comment (sttts) [inline federation/cmd/federation-apiserver/app/install.go]: https://golang.org/doc/effective_go.html#Getters

File: test/integration/federation/server_test.go (hunk 11 above)
Comment (sttts) [inline test/integration/federation/server_test.go]: If this is for 1.7, there is no hurry to get it merged. I would prefer to have this fixed to avoid flakes.

**Comment by sttts** [comment]
@nikhiljindal only a nit left about `len(enabledResources) == 0` and about the `localPort`. After that lgtm.

File: federation/cmd/federation-apiserver/app/install.go (hunk 13 above)
Comment (nikhiljindal) [inline federation/cmd/federation-apiserver/app/install.go]: Isnt it better to keep that logic in this function rather than requiring all callers to do that?

File: test/integration/federation/server_test.go (hunk 11 above)
Comment (nikhiljindal) [inline test/integration/federation/server_test.go]: I would like to get it in 1.6 if the release team agrees.
To clarify, this should not lead to flakes. Either the tests will always fail or pass.

File: federation/cmd/federation-apiserver/app/install.go (hunk 13 above)
Comment (sttts) [inline federation/cmd/federation-apiserver/app/install.go]: You have a point, this was meant to keep the other code clean. I am fine with it.

File: test/integration/federation/server_test.go (hunk 11 above)
Comment (sttts) [inline test/integration/federation/server_test.go]: If there is a follow-up soon'ish for master, I can live with it if it has to get into 1.6.

Comment (sttts) [inline test/integration/federation/server_test.go]: Or just cherry-pick https://github.com/kubernetes/kubernetes/pull/42278/commits/e51262888227119d1c2b1fe8c64cec209e254150 into your PR here and this is ready to go. Github will probably figure out the repeated commit itself.

**Comment by nikhiljindal** [comment]
Now that https://github.com/kubernetes/kubernetes/pull/42664 is in, this can wait till after 1.6

**Comment by nikhiljindal** [comment]
Rebased and updated to use the test fixture from https://github.com/kubernetes/kubernetes/pull/42278.
This should be ready to go now.
