### PR TITLE
Avoid overwriting podStatus ContainerStatuses in convertToAPIContainerStatuses

### LINKED ISSUE #94557: Pod stuck at "CreateContainerError" because of container name conflict
**What happened**:
One pod stuck at CreateContainerError and can't get recovered automatically. Kubelet log shows that the requested name (let's say Container_2) is already in use.

> E0608 20:22:04.227708    3818 remote_runtime.go:200] CreateContainer in sandbox "7ae6b14089ca17bb2a995b564effb2fb9d993832fb7bfee63a59ad4b243eec58" from runtime service failed: rpc error: code = Unknown desc = Error response from daemon: Conflict. The container name "/k8s_harbor-redis_harbor-master3-bg4tz_kube-system_1b086090-d37b-40f4-99b3-57046033770e_2" is already in use by container "94ffec110c0342db864efad67c8ca47661266677b921a98131e4b0b09434cc05". You have to remove (or rename) that container to be able to reuse that name

`docker ps` shows the Container_2 Running, and it's created before Container_1

> Container_1       10mins ago       Exited 
> Container_2       1 day ago    Up
> 

**What you expected to happen**:
This should never happen.

**How to reproduce it (as minimally and precisely as possible)**:
I wish i knew.

**Anything else we need to know?**:
I know this can be caused by time shifting,  [83050](https://github.com/kubernetes/kubernetes/issues/83050)
but I didn't find any time shifting sign in system log and chrony log, and there is no rebooting between the create timestamp of Container_1 and Container_2, so this should be caused by something else. This happens intermittently in our env,  like 3 times in half a year, and I didn't find any ime shifting sign each time.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:20:18Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2020-08-28T11:18:26Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
CentOS Linux release 7.5.1804 (Core)
- Kernel (e.g. `uname -a`):
Linux node-1 3.10.0-957.21.3.el7.x86_64 #1 SMP Wed Jul 17 06:57:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by Gandem**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

There is a race condition between the kubelet SyncLoop when the PLEG issues a ContainerDied event and the pod worker syncPod call.

This race condition is triggered by :

- In the SyncLoop, the call to cleanUpContainersInPod which in turn calls generateAPIPodStatus on a podStatus pointer fetched from the pod cache https://github.com/kubernetes/kubernetes/blob/7d176851f2c433f4301a64dfeb3b2626ca9c2f60/pkg/kubelet/kubelet.go#L2278-L2289
- In the pod workers, the call to syncPod which in turn also calls generateAPIPodStatus on a podStatus pointer fetched from the pod cache https://github.com/kubernetes/kubernetes/blob/7d176851f2c433f4301a64dfeb3b2626ca9c2f60/pkg/kubelet/kubelet.go#L1545-L1546
generateAPIPodStatus would eventually call convertToAPIContainerStatuses that sorts podStatus.ContainerStatuses in place. This is not a thread-safe operation, and when called concurrently, leads to the resulting podStatus.ContainerStatuses missing some entries and having some entries as duplicates.

At this point, the pod cache is containing a podStatus that is missing some containers statuses, thus computePodActions https://github.com/kubernetes/kubernetes/blob/7d176851f2c433f4301a64dfeb3b2626ca9c2f60/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L516 will try creating the missing containers.

However, as those containers may already be running, this leads the pod to be in CreateContainerError that does not recover until either the kubelet is restarted or another mechanism causes a refresh of the runtime state and a Set to the podCache.

**Which issue(s) this PR fixes**:

Fixes #94557

**Special notes for your reviewer**:

If testing is needed, would be glad to have pointers to add appropriate test cases to catch the issue! 

Also, I'm not very familiar to the codebase as this is my first contribution, so would be glad to modify my PR if there is a better way to fix the underlying issue. The suggested fix is non-invasive as it only avoids the sort in-place in the affected codepath (instead of, for instance adding a locking mechanism around what is fetched from the podCache).

We managed to track down and reproduce the issue as we were seeing `CreateContainerError` on pods containing multiple containers that were happening after Kubelet restarts. On a test cluster, we deployed the same setup, and forced a kubelet restart at least once every 20min until a `CreateContainerError` is encountered. All pods would eventually get stuck in `CreateContainerError` until the kubelet is restarted on the fleet.

We traced this down to duplicate and missing entries in `podStatus.ContainerStatuses`.

With the proposed patch, we didn't encounter `CreateContainerError` on restarting the kubelet anymore.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by mattjmcnaughton — COMMENTED** [review]
/ok-to-test

**Comment by mattjmcnaughton** [comment]
Also welcome to k8s :)

**Comment by Gandem** [comment]
> Also welcome to k8s :)

Thanks ! 🙂 

@mattjmcnaughton @Random-Liu @krmayankk anything needed on my side to get the PR reviewed or in a more reviewable state ?

File: pkg/kubelet/kubelet_pods.go [hunk 1]
```diff
@@ -1538,11 +1538,15 @@ func (kl *Kubelet) convertToAPIContainerStatuses(pod *v1.Pod, podStatus *kubecon
 		statuses[container.Name] = status
 	}
 
+	// Copy the slice before sorting it
+	containerStatusesCopy := make([]*kubecontainer.ContainerStatus, len(podStatus.ContainerStatuses))
+	copy(containerStatusesCopy, podStatus.ContainerStatuses)
```
Comment (krmayankk) [inline pkg/kubelet/kubelet_pods.go:1543]: - Took a quick look, the solution seems reasonable(), but so far , its hard for me to figure out if podStatus indeed is something that can be operated concurrently or is on the stack and not affected by syncLoops goroutines. 
- i also see a lack of tests for these functions

i will try to take another deeper look  by next week, if this hasnt been reviewed by someone more familiar with the code.

**Comment by Gandem** [comment]
@krmayankk @Random-Liu Did you get a chance to take a look at this 🙏 ?

**Comment by krmayankk** [comment]
@kubernetes/sig-node-bugs anyone else wants to review this ? This seems like a simple and reasonable fix to me 

@Gandem  are you still working on this ?can we add a test ?

**Comment by Gandem** [comment]
@krmayankk Yes, I'm still available to work on it. I'm not sure how to add a test that would catch the race condition, I would gladly look into it if someone can provide me some pointers on how it could be achievable.

**Comment by krmayankk** [comment]
> @krmayankk Yes, I'm still available to work on it. I'm not sure how to add a test that would catch the race condition, I would gladly look into it if someone can provide me some pointers on how it could be achievable.

Have you tried attending a sig-node meeting https://github.com/kubernetes/community/tree/master/sig-node ? This is another way to get some traction on this PR . I am happy to review this in more depth but would love to see someone closer to kubelet gives this a thumbs up

For test, i could write a scale test that exercises the race feature of go test and makes sure there is no crash

**Comment by ehashman** [comment]
@Gandem can you please rebase your PR so it can be reviewed? It is not mergeable in its current state.

**Comment by krmayankk** [comment]
> @krmayankk Yes, I'm still available to work on it. I'm not sure how to add a test that would catch the race condition, I would gladly look into it if someone can provide me some pointers on how it could be achievable.

Also this would be a good time to make sure there are UT's for the function being modified convertToAPIContainerStatuses and test them under go test --race

**Comment by Gandem** [comment]
@krmayankk @ehashman added a test (commit : https://github.com/kubernetes/kubernetes/pull/90216/commits/aa844e1521dcb15ae2d5205674bd298e316bdaa6) that triggers a data race on `master` with the `-race` flag, and doesn't trigger with the fix on this branch (tested locally by using `KUBE_RACE="-race"` per the bash test scripts). Any pointers to how to make the CI run it on race detection mode ? Can't seem to find anything related to that in https://github.com/kubernetes/community/blob/3c61bb0db08277d6f23d457927d3db628dbba350/contributors/devel/sig-testing/testing.md 🙂

**Comment by Gandem** [comment]
@krmayankk I've temporary reverted the race condition fix (which is https://github.com/kubernetes/kubernetes/pull/90216/commits/3d49941a43c0c1352794c4eb7b8a880de1309283), and it does seem that by default, all unit tests in the CI are executed with the `-race` flag, as the CI caught the data race : https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/90216/pull-kubernetes-bazel-test/1348618389525893120#1:build-log.txt%3A483

I've pushed force the the previous state, and can confirm that without the fix, the test fails (as shown by the link above), and with the fix, there is no data race and the test succeeds.

So the test works, anything else I should follow-up on for the PR to be reviewable/mergeable ? Thanks 🙇 !

**Comment by Gandem** [comment]
@krmayankk @Random-Liu PTAL 🙏

Should I attend a sig-node meeting to discuss this issue and ask for reviewers ?

**Comment by ehashman** [comment]
> Should I attend a sig-node meeting to discuss this pull request and ask for reviewers ?

It's better to poke people asynchronously or ask for review in #pr-reviews on Slack. This PR isn't closing an associated bug and doesn't have a priority assigned so it might be some time before it can get reviewed and approved as there is (unfortunately) a long backlog.

File: pkg/kubelet/kubelet_pods_test.go [hunk 2]
```diff
@@ -2613,3 +2614,29 @@ func TestGenerateAPIPodStatusHostNetworkPodIPs(t *testing.T) {
...
+			{Name: "containerA", CreatedAt: testTimestamp},
+			{Name: "containerB", CreatedAt: testTimestamp.Add(1)},
+		},
+	}
+
+	testKubelet := newTestKubelet(t, false)
+	defer testKubelet.Cleanup()
+	kl := testKubelet.kubelet
+
+	for i := 0; i < 2; i++ {
```
Comment (ehashman) [inline pkg/kubelet/kubelet_pods_test.go:2637]: Would increasing max `i` make it more likely we hit the race (and more likely this test ensures the right behaviour)?

**Review by ehashman — COMMENTED** [review]
This seems like a sensible and low-risk change to me, and the description seems related to some of the other issues I've been running into for the PodSync loop ala #98142 

@rphillips do you want to TAL?

File: pkg/kubelet/kubelet_pods_test.go (hunk 2 above)
Comment (Gandem) [reply pkg/kubelet/kubelet_pods_test.go:2637]: My understanding is that the Golang race detector uses pure happens-before detection. As there are no synchronisation events in the tested function (no locks, no channels, ...) each routine should have its own independent vector clock increased independently. As both will attempt to write to the impacted area of memory (`kubecontainer.PodStatus.ContainerStatuses`), I believe the race detector will catch the data race consistently. 

I've tried to reproduce locally by reverting the fix and running `go test ./pkg/kubelet/ -race -run TestConvertToAPIContainerStatusesDataRace` 100 times and it seems to catch the race every time.

Not an expert on the subject, happy to change it or discuss further if you'd like 🙂

**Comment by Gandem** [comment]
I _think_ this also matches with https://github.com/kubernetes/kubernetes/issues/94557 which describes pods stuck in `CreateContainerError` without any clock skew or time shift

File: pkg/kubelet/kubelet_pods_test.go (hunk 2 above)
Comment (fromanirh) [reply pkg/kubelet/kubelet_pods_test.go:2637]: This explanation matches my (admittedly limited) knowledge and is worth to be distilled in a comment right before the `for` loop because is most likely what any reader in the future is going to wonder. Another option is to just add a link to this github comment.

**Comment by fromanirh** [comment]
/lgtm
standard disclaimer: I've been looking into the pod lifecycle since some time but I can't claim expertise in this area.

this fix is self contained, makes sense in general and follows the design principles of the affected code path - see for example https://github.com/kubernetes/kubernetes/blob/v1.20.4/pkg/kubelet/kubelet_pods.go#L1543 - and in general mutating objects from caches is almost always a bad idea, or a bug. We have a clear reproducer with a solid rationale. For all these reasons, LGTM.

I suggested to distill the explanation behind the test in the testcode -not just in github- but that's minor.


That said, as previous comments noted, there could be an underlying design issue/possible improvement about why two goroutines wants to generate the status - it is probably better to do this once in a well defined place? However this change would deserve more discussion and I think it should be postponed. We can have this fix meanwhile.

**Comment by Gandem** [comment]
Thanks @fromanirh for the review 🙇 !

I've added a comment to sum-up the discussion about the test detection of the race condition. Please let me know if the wording matches your expectations, and whether there's anything else I can follow-up on 🙂

**Comment by fromanirh** [comment]
/lgtm
per motivations in https://github.com/kubernetes/kubernetes/pull/90216#issuecomment-789661394

**Comment by fromanirh** [comment]
I recommend another review/lgtm per motivations in https://github.com/kubernetes/kubernetes/pull/90216#issuecomment-789661394

**Comment by adamglt** [comment]
This is a super important issue for anyone relying on a large number of containers in a single pod (20-30+), I would guess you're much more likely to hit the race with a larger slice (we hit it daily).

It's not a common use-case for standard apps, more often seen in several Kubernetes-backed task runners (e.g.  https://github.com/tektoncd/pipeline/blob/main/pkg/entrypoint/entrypointer.go - runs a bunch of containers in a single pod and coordinates their start time via files)

@fromanirh @ehashman Can we help getting this merged somehow?

**Comment by fromanirh** [comment]
> This is a super important issue for anyone relying on a large number of containers in a single pod (20-30+), I would guess you're much more likely to hit the race with a larger slice (we hit it daily).
> 
> It's not a common use-case for standard apps, more often seen in several Kubernetes-backed task runners (e.g. https://github.com/tektoncd/pipeline/blob/main/pkg/entrypoint/entrypointer.go - runs a bunch of containers in a single pod and coordinates their start time via files)
> 
> @fromanirh @ehashman Can we help getting this merged somehow?

Yep, I'll raise this point and we'll get another review to move forward. This is totally on my radar.

File: pkg/kubelet/kubelet_pods.go [hunk 3]
```diff
@@ -1819,11 +1819,15 @@ func (kl *Kubelet) convertToAPIContainerStatuses(pod *v1.Pod, podStatus *kubecon
 		statuses[container.Name] = status
 	}
 
+	// Copy the slice before sorting it
+	containerStatusesCopy := make([]*kubecontainer.Status, len(podStatus.ContainerStatuses))
+	copy(containerStatusesCopy, podStatus.ContainerStatuses)
```
Comment (saschagrunert) [inline pkg/kubelet/kubelet_pods.go:1824]: I'm wondering if rw locking the slice would be better than making a whole copy. :thinking:

Comment (Gandem) [reply pkg/kubelet/kubelet_pods.go:1824]: Thanks for the review ! A couple of questions regarding a lock-based approach:
- The function / code path is supposed to be purely transformative and not alter the kubelet State (I suppose, including the podCache), should we change that assumption ? https://github.com/kubernetes/kubernetes/blob/v1.20.4/pkg/kubelet/kubelet_pods.go#L1540-L1542 
It would also potentially alter the assumption that callers should not modify objects from the pod cache https://github.com/kubernetes/kubernetes/blob/v1.20.4/pkg/kubelet/container/cache.go#L81-L88
- Where should the lock live ? Should we add an attribute `ContainerStatusesLock` to the pod status https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/runtime.go#L290-L304 / or higher on the podCache level ?

Comment (saschagrunert) [reply pkg/kubelet/kubelet_pods.go:1824]: > * The function / code path is supposed to be purely transformative and not alter the kubelet State (I suppose, including the podCache), should we change that assumption ? https://github.com/kubernetes/kubernetes/blob/v1.20.4/pkg/kubelet/kubelet_pods.go#L1540-L1542

I think so, since the assumption seems wrong with the `Sort()` call. We could also assume that the status is already sorted and move the sorting code to another code path, but this way we would still require the lock from what I can see.

>   It would also potentially alter the assumption that callers should not modify objects from the pod cache https://github.com/kubernetes/kubernetes/blob/v1.20.4/pkg/kubelet/container/cache.go#L81-L88
> * Where should the lock live ? Should we add an attribute `ContainerStatusesLock` to the pod status https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/runtime.go#L290-L304 / or higher on the podCache level ?

A higher lock would mean that we lock the whole `PodStatus`, right? I personally would prefer locking only the structure we need, which means the lock would be part of `PodStatus`.

**Comment by Gandem** [comment]
I've opened another PR with an alternative implementation using a lock on `ContainerStatuses`: https://github.com/kubernetes/kubernetes/pull/101744  

cc @saschagrunert @fromanirh @ehashman let me know if that works for you (opened it in another PR for clarity, but I can rebase it here and close the new PR if you prefer ! 🙏 )

**Comment by fromanirh** [comment]
> I've opened another PR with an alternative implementation using a lock on `ContainerStatuses`: #101744
> 
> cc @saschagrunert @fromanirh @ehashman let me know if that works for you (opened it in another PR for clarity, but I can rebase it here and close the new PR if you prefer ! pray )

In general I'm fine with the approach @saschagrunert suggested. I'll review the lock-based PR ASAP.

**Comment by Gandem** [comment]
While trying the different approaches and benchmarking them to list each one's pros and cons, I've spent some more time digging through the kubelet codebase, and found out that...

**The ContainerStatuses slice is already sorted from latest to earliest creation time.** In fact, it's sorted on creation in the kubelet generic runtime manager (which if I'm not mistaken seems to be the only supported runtime manager): https://github.com/DataDog/kubernetes/blob/v1.21.0/pkg/kubelet/kuberuntime/kuberuntime_container.go#L489 I couldn't find another place in the codebase where elements are inserted out of order in the `ContainerStatuses` slice, which means the slice is already sorted in `convertToAPIContainerStatuses`.

## Sorting an already sorted slice is NOT a no-op

The remaining question being: if the slice is already sorted, one would expect the sort to be a no-op, so why are we hitting the race condition there ? 

And the reason seems to be linked to Golang's implementation of `quickSort` : https://golang.org/src/sort/sort.go?s=6133:6158#L196. While testing empirically in the following playground: https://play.golang.org/p/MxVo19PGC1M, it looks like the sort is indeed a no-op when the slice has strictly less than 13 elements (you can remove the last element in the slice to test that assumption). However, when it has 13 elements or more, the sort would at least switch the `pivot` and the first element before switching them back. With 40 elements, the sort runs 6 operations on an already sorted array : https://play.golang.org/p/j4tPZT86At0.

This matches with our (and @adamglt's) observation that the race condition is more likely to happen with pods containing a large number of containers (20-30+ containers in a pod). And it does happen relatively often when that's the case (we were hitting it twice per day on fleets of ~150 pods with 16 containers each).

## Possible solutions

This means we have, at least, the following alternatives : 
1. **Remove the sort in `convertToAPIContainerStatuses`**: Rely on the fact that the `ContainerStatuses` slice is already sorted. We could add a test (and probably a comment) to `getPodContainerStatuses` to guarantee that the slice returned is always sorted. The drawback of this approach is that it introduces an implicit contract that container statuses are always sorted in the pod cache, which might be depended on in other places of the codebase (per [Hyrum's law](https://www.hyrumslaw.com/)).
2. **Check whether the slice is sorted, and if it's not run the sort**: Checking whether the slice is sorted should be relatively straightforward and `O(n)`
3. **Always run the sort**

If we want to go forward with either 2/ or 3/, we still need to fix the race condition caused by sorting the slice in-place. I've experimented and benchmarked three approaches to do that: 

a. **Copy the slice before sorting it** (which is the current method in https://github.com/kubernetes/kubernetes/pull/90216)
b. **Remove the sort and use a map** (`containerName -> []{creationTime, status}`) to keep the same behaviour. I didn't open a PR yet, but a PoC implementation can in found here : https://github.com/kubernetes/kubernetes/compare/master...DataDog:nayef/fix-container-statuses-race-map
c. **Add a lock**, which is implemented in https://github.com/kubernetes/kubernetes/pull/101744

## Benchmarks

As I've mentioned earlier, I've run a few benchmarks to determine the performance impact of each approach. The full benchmark code and results are available here : https://gist.github.com/Gandem/ee6dbc779b0d2c0544d62eed3eddefa3 Those benchmarks should of course be taken with a grain of salt: I don't suspect this part of the code being a performance bottleneck compared to, for instance, fetching the status from the container runtime, or the spec from the API server.

From the bench results, we can deduce that the lock-based approach is always the most performant one. 

When we have a **low** number of container statuses (which to my understanding should be the considered as the "normal" behaviour, and nominal usage of k8s), the `copy` based approach (`O(nlogn)`) is actually roughly ~50% **faster** than the `map` based approach (`O(n)`).

When we have a **high** number of statuses (for instance a container crashes often and older containers are not yet garbage collected) the `map` based approach is ~20% faster than the `copy` based one, however, it does noticeably more allocations.

## Conclusion

My personal take is that, although **(c - lock-based)** is the most performant approach in that codepath, I'd recommend against it for the cons listed in the following comment https://github.com/kubernetes/kubernetes/pull/101744#issuecomment-833383034.

I'd suggest moving forward with either **(1 - remove the sort)** or **(2 only sort when not sorted - a - copy based)**, depending on how much it's acceptable to rely on the implicit contract in the pod cache. I personally prefer the copy based approach over the `map` approach :
- When the sort happens (infrequently), in most cases, we will expect a low number of statuses, so it should be faster during nominal behaviour
- The code is simpler (no additional tricks / functions)
- It does less allocations (so less memory pressure)

@matthyx @fromanirh @saschagrunert I might have missed other pros/cons or alternatives, please let me know what you think ! Happy to hop on slack/video chat if you want to further discuss this.

**Comment by fromanirh** [comment]
@Gandem kudos for the impressive research. I'll have a deeper lock in the coming days to form an opinion myself.

**Comment by matthyx** [comment]
Maybe we could implement an ordered slice of `ContainerStatuses` to make sure it's always sorted, whatever the implementation of the runtime manager?

**Comment by matthyx** [comment]
@Gandem coming back to this, I think your first approach makes the most sense philosophically, as it takes a snapshot of all the statuses during the copy and treats them as a whole, no matter what happens to the cache in other goroutines during that time.
It also avoids the need for a lock.

**Comment by Gandem** [comment]
> Maybe we could implement an ordered slice of ContainerStatuses to make sure it's always sorted, whatever the implementation of the runtime manager?

I've thought about this quite a bit, and I'm not aware of any solution in Golang to enforce and guarantee that a slice is always sorted 😕  

My understanding is that if we define a custom type such as `type SortedContainerStatuses []*Status` (with a constructor that guarantees sorting), all functions/structs which would expect a `SortedContainerStatuses` will also accept an unsorted `[]*Status` (as the Go compiler will know both are the same type).

> I think your first approach makes the most sense philosophically, as it takes a snapshot of all the statuses during the copy and treats them as a whole

@matthyx Agreed, I'm definitely comfortable with merging this PR as-is if this seems reasonable for everyone. Conditional sorting (only sort if the slice isn't already sorted) does feel like a bit like premature optimisation in that case.

In any case, please let me know if I can help moving the fix forward !  🙇

**Comment by fromanirh** [comment]
> @Gandem coming back to this, I think your first approach makes the most sense philosophically, as it takes a snapshot of all the statuses during the copy and treats them as a whole, no matter what happens to the cache in other goroutines during that time.
> It also avoids the need for a lock.

I agree. I won't oppose the lock-based approach, but this is the approach I like most. Also, +1 to defer conditional sorting.

**Comment by Gandem** [comment]
I just saw the 👍 from @saschagrunert on the comments above, does this mean we're comfortable moving forward with this PR ? If so, please let me know how I can help !

Orthogonal question, as this issue has been there for a long time (we traced it back in v1.10 clusters), and is important for anyone relying on a large number of containers in a single pod (20-30+), should we backport the fix to all supported minors ?

**Comment by fromanirh** [comment]
> I just saw the +1 from @saschagrunert on the comments above, does this mean we're comfortable moving forward with this PR ? If so, please let me know how I can help !
> 
> Orthogonal question, as this issue has been there for a long time (we traced it back in v1.10 clusters), and is important for anyone relying on a large number of containers in a single pod (20-30+), should we backport the fix to all supported minors ?

My take (disclaimer: we will need the take of more expert folks in the cherry-picking management :) ) The fix we are discussing in this PR is minimal, self contained and it seems very low risk, so it seems a good candidate to be backported in all the relevant branches.

**Comment by Gandem** [comment]
Thank you 🙇  !

Is there anything I can do at this point to move the PR forward ? Should I tag `@sjenning` as an approver, as instructed by https://github.com/kubernetes/kubernetes/pull/90216#issuecomment-790638634 ?

**Comment by fromanirh** [comment]
/lgtm
since we kept the approach I LGTM'd in (https://github.com/kubernetes/kubernetes/pull/90216#issuecomment-796688675)

**Comment by Gandem** [comment]
I've just rebased the PR due to a test conflict in `kubelet_pods_test.go` (as mentioned https://github.com/kubernetes/kubernetes/pull/90216#issuecomment-875800654). It looks like this removed the LGTM label, @fromanirh would it be possible to add it again ? Thanks !

**Review by ehashman — COMMENTED** [review]
/lgtm

**Comment by ehashman** [comment]
It's unclear if after the latest pod lifecycle refactor, the race condition still exists. However,

> generateAPIPodStatus would eventually call convertToAPIContainerStatuses that sorts podStatus.ContainerStatuses in place. This is not a thread-safe operation, and when called concurrently, leads to the resulting podStatus.ContainerStatuses missing some entries and having some entries as duplicates.

is still true. `convertToAPIContainerStatuses` should be purely transformative and not mutate `podStatus`, so we should fix this.

/priority important-long-term
/remove-priority backlog

**Review by mrunalp — APPROVED** [review]

**Comment by zhouhaibing089** [comment]
Oops, sorry to jump into an old thread, but really, it is a bit unfortunate that this fix was not cherry-picked into release-1.21.
