### PR TITLE
do not return error if TearDownPod is called twice

### LINKED ISSUE #26199: kubenet:  failed to "TeardownNetwork"
Kubelet log is full of errors from tearing down network at HEAD. 

```
Failed killing the pod "e2e-test-nginx-job-96ib7": failed to "TeardownNetwork" for "e2e-test-nginx-job-96ib7_e2e-tests-kubectl-kuous" with TeardownNetworkError: "Failed to teardown network for pod \"963a42a1-21de-11e6-af3b-42010af00002\" using network plugins \"kubenet\": Error removing container from network: Failed to open /proc/0/ns/net: open /proc/0/ns/net: no such file or directory"
E0524 18:39:22.984933    3378 pod_workers.go:183] Error syncing pod d14ef1dc-21de-11e6-af3b-42010af00002, skipping: failed to "TeardownNetwork" for "pod-configmaps-d14e8c7a-21de-11e6-9f89-0242ac11000d_e2e-tests-configmap-razxa" with TeardownNetworkError: "Failed to teardown network for pod \"d14ef1dc-21de-11e6-af3b-42010af00002\" using network plugins \"kubenet\": Error removing container from network: Failed to open /proc/0/ns/net: open /proc/0/ns/net: no such file or directory"
```

From the log, a lot of them were the result of trying to access `/proc/0/ns/net`. Note that if you `docker inspect` an exited container, the returned PID will be 0. Therefore, my guess is that kubelet tried to tear down the network *after* the container has already exited. I didn't dig further.

@freehan could you take a look?

### PR DESCRIPTION
**Pull request by freehan**
fixes: #26199
cc: @dcbw

### CODE REVIEW

**Comment by freehan** [comment]
I just realized I made some mistake in this PR. Will come back with a better solution.

**Comment by freehan** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by alex-mohr** [comment]
buildcop says: appears to make network teardown in tests better.  p2.

**Comment by dcbw** [comment]
Yeah, lgtm.  Though I worry a bit about the network plugin being able to clean things up (like release address leases or clean up other network resources) if TearDownPod() is called but for whatever reason, the network namespace no longer exists.  Just because the namespace doesn't exist doesn't mean the plugin couldn't clean things that aren't dependent on the namespace up if it needed to.

**Comment by yujuhong** [comment]
@dcbw if the namespace is gone, what can be used for the plugin to identify things associated with the namespace?

**Comment by freehan** [comment]
Good point. ipam release ip based on container id. But for veth stuff, plugin can do nothing. 

So this might cause ip leaks if infra container dies before TearDownNetwork

**Comment by yujuhong** [comment]
@freehan do you want to hold this PR, while figuring out a way to address the potential IP leaks?

**Comment by freehan** [comment]
retitle PR 

@dcbw @yujuhong  PTAL

File: pkg/kubelet/network/kubenet/kubenet_linux.go [hunk 1]
```diff
@@ -339,7 +339,8 @@ func (plugin *kubenetNetworkPlugin) TearDownPod(namespace string, name string, i
 	}
 
 	// no cached CIDR is Ok during teardown
-	if cidr, ok := plugin.podCIDRs[id]; ok {
+	cidr, ok := plugin.podCIDRs[id]
```
Comment (yujuhong) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: why changing this?

Comment (yujuhong) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: uh....I just saw that `ok` is used below. Can we rename ok to `hasCIDR` or something more meaningful since it's not just used immediately?

File: pkg/kubelet/network/kubenet/kubenet_linux.go [hunk 2]
```diff
@@ -349,6 +350,11 @@ func (plugin *kubenetNetworkPlugin) TearDownPod(namespace string, name string, i
 		}
 	}
 	if err := plugin.delContainerFromNetwork(plugin.netConfig, network.DefaultInterfaceName, namespace, name, id); err != nil {
+		// This is to prevent returning error when TearDownPod is called twice on the same pod. This helps to reduce event pollution.
+		if !ok {
+			glog.Errorf("Failed to delete container which is not found in podCIDRs map: %v", err)
```
Comment (yujuhong) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: nit: Warning instead of Error

Comment (yujuhong) [inline pkg/kubelet/network/kubenet/kubenet_linux.go]: nit: Add "from network plugin" to not confuse readers who may think kubelet failed to remove the container.

**Comment by yujuhong** [comment]
Thanks for fixing this!

**Comment by a-robinson** [comment]
Manually merging small PRs while submit queue is down
