### PR TITLE
Fix int->string casts

### LINKED ISSUE #93407: The build failed for some tests while running make test fo GO version go1.15beta1
Test Failures are
```
FAIL    k8s.io/kubernetes/pkg/kubelet [build failed]
FAIL    k8s.io/kubernetes/pkg/kubelet/container [build failed]
FAIL    k8s.io/kubernetes/pkg/kubelet/network/dns [build failed]
FAIL    k8s.io/kubernetes/pkg/scheduler [build failed]
FAIL    k8s.io/kubernetes/vendor/k8s.io/client-go/plugin/pkg/client/auth/azure [build failed]
FAIL    k8s.io/kubernetes/vendor/k8s.io/client-go/tools/record [build failed]
FAIL    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/create [build failed]
FAIL    k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/drain [build failed]
FAIL    k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/gce [build failed]
FAIL
```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-alpha.0.300+ff33efc164e78d-dirty", GitCommit:"ff33efc164e78d12c2a250f901b6ec725184fd06", GitTreeState:"dirty", BuildDate:"2020-07-22T10:11:16Z", GoVersion:"go1.15beta1", Compiler:"gc", Platform:"linux/ppc64le"}
- Cloud provider or hardware configuration:
linux/ppc64le
- OS (e.g: `cat /etc/os-release`):
```NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.1:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
```
**Full logs of make file**
[make.log](https://github.com/kubernetes/kubernetes/files/4970250/make.log)

**Full Logs of make test**
[make_test.log](https://github.com/kubernetes/kubernetes/files/4970245/make_test.log)

Golang Location: https://dl.google.com/go/go1.15beta1.linux-ppc64le.tar.gz

### PR DESCRIPTION
**Pull request by liggitt**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes incorrect int->string casts, which result in a single-character rune string.

go1.15 flags these as build errors, but we should fix them even on earlier versions

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes/kubernetes/issues/93407

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

/cc @justaugustus

### CODE REVIEW

File: pkg/scheduler/scheduler.go [hunk 1]
```diff
@@ -607,13 +607,18 @@ func (sched *Scheduler) scheduleOne(ctx context.Context) {
...
 	// We breakdown the pod scheduling duration by attempts capped to a limit
 	// to avoid ending up with a high cardinality metric.
 	if p.Attempts >= 15 {
 		return "15+"
 	}
-	return string(p.Attempts)
+	if p.Attempts < 0 {
+		return "-"
+	}
+	return attempts[p.Attempts]
```
Comment (liggitt) [inline pkg/scheduler/scheduler.go:621]: cc @ahg-g 

avoided strconv here since it is expensive for frequently called paths

File: pkg/scheduler/scheduler.go [hunk 2]
```diff
@@ -607,13 +607,18 @@ func (sched *Scheduler) scheduleOne(ctx context.Context) {
 	}()
 }
 
+var attempts = []string{"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"}
```
Comment (adtac) [inline pkg/scheduler/scheduler.go:610]: Don't need the last element, will never be accessed.

File: pkg/scheduler/scheduler.go (hunk 1 above)
Comment (ahg-g) [reply pkg/scheduler/scheduler.go:621]: this is not called frequently, once per scheduled pod.

Comment (adtac) [reply pkg/scheduler/scheduler.go:621]: FWIW I don't think this codepath is executed that frequently; it's executed once per successfully scheduled pod, so IMO I prefer the simpler approach.

(Also, `Itoa` has a fast path for small ints: https://golang.org/src/strconv/itoa.go?s=784:824#L15)

Comment (liggitt) [reply pkg/scheduler/scheduler.go]: > `Itoa` has a fast path for small ints: https://golang.org/src/strconv/itoa.go?s=784:824#L15

ah, great... I cargo-culted this wisdom from our request metrics which log the response code which can be up in the 5xx range and exceeds the small number optimization

simplified back to strconv here

**Comment by liggitt** [comment]
verify failure, no logs

/retest

**Comment by liggitt** [comment]
> Pod pending timeout.

/retest

**Comment by justaugustus** [comment]
/retest
(pods pending timeout)

**Comment by justaugustus** [comment]
/retest
(pods pending timeout)
