### PR TITLE
Fix waitForScheduler in scheduer predicates e2e tests

### LINKED ISSUE #42691: e2e flaky: [k8s.io] SchedulerPredicates [Serial] validates that NodeSelector is respected if not matching [Conformance]
Sample failures: 

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/781

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduler_predicates.go:236
Expected
    <bool>: false
to equal
    <bool>: true
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:5082
```

@kubernetes/sig-scheduling-bugs

### PR DESCRIPTION
**Pull request by bsalamat**
**What this PR does / why we need it**: Fixes waitForScheduler in e2e to resolve flaky tests in scheduler_predicates.go

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #42691

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by davidopp** [comment]
Oh cool, I didn't know about observeEventAfterAction(). How did you find it??

**Comment by timothysc** [comment]
> Oh cool, I didn't know about observeEventAfterAction(). How did you find it?? 

@davidopp b/c I asked connor to follow the pattern of other tests when he wrote OIR.

**Comment by bsalamat** [comment]
@davidopp Tim pointed it out. :-)

@timothysc Sure. Makes sense. I will rebase after those PRs are merged.

File: test/e2e/scheduler_predicates.go [hunk 1]
```diff
@@ -506,7 +494,7 @@ var _ = framework.KubeDescribe("SchedulerPredicates [Serial]", func() {
 		By("Launching two pods on two distinct nodes to get two node names")
 		CreateHostPortPods(f, "host-port", 2, true)
 		defer framework.DeleteRCAndPods(f.ClientSet, f.InternalClientset, ns, "host-port")
-		podList, err := cs.Core().Pods(ns).List(metav1.ListOptions{})
+		podList, err := cs.CoreV1().Pods(ns).List(metav1.ListOptions{})
```
Comment (timothysc) [inline test/e2e/scheduler_predicates.go]: Is this change new in the api spec?

File: test/e2e/scheduler_predicates.go [hunk 2]
```diff
@@ -900,16 +886,37 @@ func getRequestedCPU(pod v1.Pod) int64 {
 	return result
 }
 
-func waitForScheduler() {
-	// Wait a bit to allow scheduler to do its thing
-	// TODO: this is brittle; there's no guarantee the scheduler will have run in 10 seconds.
-	framework.Logf("Sleeping 10 seconds and crossing our fingers that scheduler will run in that time.")
-	time.Sleep(10 * time.Second)
+func waitForScheduler(f *framework.Framework, PodName string, expectSuccess bool) {
+	framework.Logf("Waiting for scheduler...")
```
Comment (timothysc) [inline test/e2e/scheduler_predicates.go]: might want to add more description based on input.. Waiting for what?

**Review by timothysc — COMMENTED** [review]
minor comments, and it may need a rebase post connor's merge.

File: test/e2e/scheduler_predicates.go (hunk 1 above)
Comment (bsalamat) [inline test/e2e/scheduler_predicates.go]: Looks like it. Core() is deprecated and is an alias for CoreV1() now.

File: test/e2e/scheduler_predicates.go [hunk 3]
```diff
@@ -900,16 +886,37 @@ func getRequestedCPU(pod v1.Pod) int64 {
...
+	Expect(err).NotTo(HaveOccurred())
+	Expect(success).To(Equal(true))
+}
+
+func createPausePodAndWaitForScheduler(f *framework.Framework, conf pausePodConfig, expectSuccess bool) {
+	action := func() error {
+		_, err := f.ClientSet.CoreV1().Pods(f.Namespace.Name).Create(initPausePod(f, conf))
+		return err
+	}
+	predicate := scheduleFailure(conf.Name)
```
Comment (ConnorDoyle) [inline test/e2e/scheduler_predicates.go]: We should probably pull `scheduleFailure` and `scheduleSuccess` predicate factories out of `opaque_resource.go`.

File: test/e2e/scheduler_predicates.go [hunk 4]
```diff
@@ -900,16 +886,37 @@ func getRequestedCPU(pod v1.Pod) int64 {
...
 
-func waitForScheduler() {
-	// Wait a bit to allow scheduler to do its thing
-	// TODO: this is brittle; there's no guarantee the scheduler will have run in 10 seconds.
-	framework.Logf("Sleeping 10 seconds and crossing our fingers that scheduler will run in that time.")
-	time.Sleep(10 * time.Second)
+func waitForScheduler(f *framework.Framework, PodName string, expectSuccess bool) {
+	framework.Logf("Waiting for scheduler...")
+	action := func() error { // No action before waiting for Scheduler.
+		return nil
```
Comment (ConnorDoyle) [inline test/e2e/scheduler_predicates.go]: The action here should be to create the pod you expect to observe. Otherwise there is a race between starting the watch and scheduler binding.

The `observeEventAfterAction` function is supposed to take care of the rest of the ordering concerns (make sure the watch is alive before evaluating the `action` thunk.)

Side note: the sibling helper function for observing node updates has additional synchronization barriers to try to guarantee that interleaving. It's probably a good idea to bring them to parity by adding the informer started guard that is signaled from the first invocation of the underlying informer's watch.

**Review by ConnorDoyle — CHANGES_REQUESTED** [review]

File: test/e2e/scheduler_predicates.go (hunk 4 above)
Comment (ConnorDoyle) [inline test/e2e/scheduler_predicates.go]: In case it's not clear (on re-read). The racy ordering we'd want to avoid is: 1) create the pod 2) scheduler emits a binding (and event) 3) create the watch 4) event observer predicate times out

Comment (ConnorDoyle) [inline test/e2e/scheduler_predicates.go]: see https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/events.go#L43

Comment (bsalamat) [inline test/e2e/scheduler_predicates.go]: Thanks, Connor! I also realized the race issue when creating the PR, but the reason that I created this method is that at line 732, the test waits for scheduler after it removes a taint from a node. No pod is created in this case, but the race condition still exists.
I guess I can create another method similar to `createPausePodAndWaitForScheduler` that removes a taint and waits for scheduler. A better way is to write a function like `takeActionAndWaitForScheduler` that receives another function as one of its arguments, uses the function as `action` and then waits for scheduler. In our example, the action will be the removal of a taint from a node. What do you think?

Comment (ConnorDoyle) [inline test/e2e/scheduler_predicates.go]: Your suggestion could definitely work. I like the idea of doubling-down on the functional composition style of the event observer functions. You could have something like createPausePod() that returns a nullary action function and pass the result to waitForScheduler(). Similarly, your removeTaint() could return a different action function.

Comment (ConnorDoyle) [inline test/e2e/scheduler_predicates.go]: Another side-note, everything _might_ work as written if the informer gets enough recent events in the namespace to catch the event you're looking for. But it would be a coincidence based on undocumented behavior of the informer and IMO a potential source of future flakes.

Comment (ConnorDoyle) [inline test/e2e/scheduler_predicates.go]: Side note 3 (apologies): cached events, if they do occur, could cause false positives for the scheduleSuccess event predicate if pod names are not unique within the test run namespace. We should make sure pod names are not re-used for the lifetime of the namespace to avoid that problem.

Comment (bsalamat) [inline test/e2e/scheduler_predicates.go]: > cached events, if they do occur, could cause false positives for the scheduleSuccess event predicate if pod names are not unique within the test run namespace. We should make sure pod names are not re-used for the lifetime of the namespace to avoid that problem.

Great point. This is a bit concerning though. It will be hard to ensure that pod names won't be reused in future developments. Unfortunately, I don't have any good suggestion to solve this problem at the moment.

**Comment by timothysc** [comment]
You'll need to rebase this one due to the file shift.

**Comment by ethernetdan** [comment]
@bsalamat planning on getting this fix in time for 1.6?

**Comment by ConnorDoyle** [comment]
xref #43105 and #43107

**Comment by bsalamat** [comment]
@ethernetdan Yes, but I will need to wait for #43105 and #43107 to get merged first.

**Comment by ConnorDoyle** [comment]
IMO this isn't a 1.6 blocker, but just my 2 cents

**Comment by bsalamat** [comment]
I agree with Connor. This is not a blocker, but given that the issue improves robustness of scheduler tests, it would be nice to have in 1.6. We currently see occasional flakes (~1 failure a week) which we believe will be fixed by this PR.

**Comment by bsalamat** [comment]
@timothysc @ConnorDoyle Could you guys take another look please?

File: test/e2e/scheduling/predicates.go [hunk 5]
```diff
@@ -900,16 +892,38 @@ func getRequestedCPU(pod v1.Pod) int64 {
...
-func waitForScheduler() {
-	// Wait a bit to allow scheduler to do its thing
-	// TODO: this is brittle; there's no guarantee the scheduler will have run in 10 seconds.
-	framework.Logf("Sleeping 10 seconds and crossing our fingers that scheduler will run in that time.")
-	time.Sleep(10 * time.Second)
+// removeTaintFromNodeAction returns a closure that removes the given taint
+// from the given node upon invocation.
+func removeTaintFromNodeAction(cs clientset.Interface, nodeName string, testTaint v1.Taint) func() error {
+	return func() error {
+		framework.RemoveTaintOffNode(cs, nodeName, testTaint)
```
Comment (timothysc) [inline test/e2e/scheduling/predicates.go]: why does this return error, then it's always nil... Looks like there is a Failf buried there.

**Review by timothysc — CHANGES_REQUESTED** [review]

File: test/e2e/scheduling/predicates.go (hunk 5 above)
Comment (bsalamat) [inline test/e2e/scheduling/predicates.go]: The `action` that `common.ObserveEventAfterAction` takes must be of type 'func() error'. That's why this closure has that type. However, the method does error checking internally and does not return any error. I could rewrite another method similar to `framework.RemoveTaintOffNodes` that returns an error, but it would be mostly duplicate code.

Comment (ConnorDoyle) [inline test/e2e/scheduling/predicates.go]: Do you think creating a type alias `type Action func() error` would be more or less clear?

**Review by ConnorDoyle — APPROVED** [review]
/lgtm

File: test/e2e/scheduling/predicates.go (hunk 5 above)
Comment (timothysc) [inline test/e2e/scheduling/predicates.go]: +1 to alias but not needed now.  

/lgtm

**Review by timothysc — APPROVED** [review]

File: test/e2e/scheduling/predicates.go (hunk 5 above)
Comment (bsalamat) [inline test/e2e/scheduling/predicates.go]: Done

**Comment by bsalamat** [comment]
@timothysc I made the changes to add an alias. Could you please approve one more time?

File: test/e2e/scheduling/predicates.go [hunk 6]
```diff
@@ -41,6 +42,8 @@ const minPodCPURequest int64 = 500
 // variable set in BeforeEach, never modified afterwards
 var masterNodes sets.String
 
+type Action func() error
```
Comment (ConnorDoyle) [inline test/e2e/scheduling/predicates.go]: Shouldn't this live in test/e2e/common?

**Review by ConnorDoyle — CHANGES_REQUESTED** [review]

File: test/e2e/scheduling/predicates.go (hunk 6 above)
Comment (ConnorDoyle) [inline test/e2e/scheduling/predicates.go]: ^ besides that, lgtm

Comment (bsalamat) [inline test/e2e/scheduling/predicates.go]: Makes sense. Done.

**Comment by timothysc** [comment]
@k8s-bot gce etcd3 e2e test this
