### PR TITLE
fsquota: only generate pod uuid is nil

### LINKED ISSUE #107272: After kubelet restart, quota monitoring doesn't work for old pods.
### What happened?

The log below was added by myself to see the `GetMetrics` duration for empty dir.

> 12月 31 17:57:25 daocloud kubelet[726129]: I1231 17:57:25.254428  726129 volume_stat_calculator.go:141] Volume metrics for "data-test": %!s(float64=10.651979472)
> 12月 31 17:57:56 daocloud kubelet[726129]: I1231 17:57:56.013285  726129 volume_stat_calculator.go:141] Volume metrics for "data-test": %!s(float64=0.010684603)
> 12月 31 17:58:52 daocloud kubelet[726129]: I1231 17:58:52.068963  726129 volume_stat_calculator.go:141] Volume metrics for "data-test": %!s(float64=10.820351649)
> 12月 31 17:59:41 daocloud kubelet[726129]: I1231 17:59:41.360989  726129 volume_stat_calculator.go:141] Volume metrics for "data-test": %!s(float64=0.006106497)

I have two pods in the node and one is created after kubelet restart, the other was created before kubelet restarted.

```
12月 31 18:09:07 daocloud kubelet[726129]: I1231 18:09:07.905869  726129 quota_linux_common_impl.go:130] runXFSQuotaCommand /sbin/xfs_quota -t /tmp/mounts1045325910 -P/dev/null -D/dev/null -x -f /var/lib/kubelet -c quota -p -N -n -v -b 1048590
12月 31 18:09:07 daocloud kubelet[726129]: I1231 18:09:07.908269  726129 quota_linux_common_impl.go:137] runXFSQuotaCommand output "/dev/sdc                403992 9007199254740992 9007199254740992   00 [--------] /var/lib/kubelet\n"
12月 31 18:09:07 daocloud kubelet[726129]: I1231 18:09:07.909155  726129 quota_linux_common_impl.go:130] runXFSQuotaCommand /sbin/xfs_quota -t /tmp/mounts516467224 -P/dev/null -D/dev/null -x -f /var/lib/kubelet -c quota -p -N -n -v -i 1048590
12月 31 18:09:07 daocloud kubelet[726129]: I1231 18:09:07.910827  726129 quota_linux_common_impl.go:137] runXFSQuotaCommand output "/dev/sdc                500002          0          0   00 [--------] /var/lib/kubelet\n"
[root@daocloud ~]#
[root@daocloud ~]# time repquota -P /var/lib/kubelet -s -v
*** Report for project quotas on device /dev/sdc
Block grace time: 7days; Inode grace time: 7days
                        Space limits                File limits
Project         used    soft    hard  grace    used  soft  hard  grace
----------------------------------------------------------------------
volume1048591 --    790M 8388608T 8388608T          1001k     0     0
volume1048590 --    395M 8388608T 8388608T           501k     0     0
#0        --    364K      0K      0K           1271     0     0

*** Status for project quotas on device /dev/sdc
Accounting: ON; Enforcement: ON
Inode: #131 (2 blocks, 2 extents)

```
Two volumes above are for empty dir.
You can see the log above, `1048591` volume is not called quota_linux_common_impl.go and `1048590` volume is called by 
quota_linux_common_impl.go.

### What did you expect to happen?

Both empty dir should be monitored by quota as the quota monitoring as LocalStorageCapacityIsolationFSQuotaMonitoring is enabled and the pquota is enabled.

```
/dev/sdc /var/lib/kubelet xfs defaults,pquota 0 0
```

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: pod-test
  namespace: default
spec:
  containers:
  - args:
    - "100000"
    command:
    - sleep
    image: nginx:1.14.2
    imagePullPolicy: IfNotPresent
    name: nginx
    volumeMounts:
    - name: data-test
      mountPath: /data/test/
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "3Gi"
  volumes:
  - name: data-test
    emptyDir:
       sizeLimit: "2Gi"
```
Create a pod as above and run `seq -w 1 100000 | xargs -I {} sh -c 'mkdir -p z/{}/{}/{}/{} && echo xxx > z/{}/{}/{}/{}/{}'` under /data/test of the pod to generate about 1.9G data.

If we add some log/metrics for volume stats, we can see that the `stats` of the empty dir will cost only about 100ms or less to get the disk usage of this empty dir. If using `du` to get the disk usage of the folder above, it would cost about 10s.

Restart the kubelet.

We can see the disk-usage-stat is not using the quota.

If you create another pod like above, the new pod would use the quota and the old one is using `du` to get disk usage.

### Anything else we need to know?

N/A

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
vsphere
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

$ uname -a
# Linux daocloud 4.18.0-147.el8.x86_64 #1 SMP Wed Dec 4 21:51:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
calico
</details>

### LINKED ISSUE #112081: when updated ConfigMaps to pods，pod's filesystem by the Kubelet get errors
See #107329

OpenShift found issues rendering updated ConfigMaps to pods. When ConfigMaps get updated within the API, they do not get rendered to the resulting pod's filesystem by the Kubelet with the following error:

```
Aug 26 20:22:30 test1-lkz4t-master-1 kubenswrapper[1474]: E0826 20:22:30.751336    1474 nestedpendingoperations.go:335] Operation for "{volumeName:kubernetes.io/configmap/d381fba5-463d-420a-8ef2-ba4d9a94846d-trusted-ca-bundle podName:d381fba5-463d-420a-8ef2-ba4d9a94846d nodeName:}" failed. No retries permitted until 2022-08-26 20:24:32.751309823 +0000 UTC m=+2312.350897767 (durationBeforeRetry 2m2s). Error: MountVolume.SetUp
 failed for volume "trusted-ca-bundle" (UniqueName: "kubernetes.io/configmap/d381fba5-463d-420a-8ef2-ba4d9a94846d-trusted-ca-bundle") pod "insights-operator-5655ffbd97-x2gqw" (UID: "d381fba5-463d-420a-8ef2-ba4d9a94846d") : requesting quota on existing directory /var/lib/kubelet/pods/d381fba5-463d-420a-8ef2-ba4d9a94846d/volumes/kubernetes.io~configmap/trusted-ca-bundle but different pod be50da94-ebf1-4cb0-9e0b-2949fd2bed7b f9
8fa631-4940-4217-9b82-4e5ad6720238
```

We will need to backport to 1.25.

Pr is open to Move LocalStorageCapacityIsolationFSQuotaMonitoring back to Alpha. 

/sig node
/kind regression
/priority important-soon

__Originally posted by @rphillips in https://github.com/kubernetes/kubernetes/pull/112076__

@rphillips Would you link to openshift issue or give me more evidence or reproduce steps？

### PR DESCRIPTION
**Pull request by pacoxu**
#### What type of PR is this?
/kind bug

#### Which issue(s) this PR fixes:

Fixes #112081

#### Special notes for your reviewer:

The bug was caused by https://github.com/kubernetes/kubernetes/pull/107302 by me when I fixed https://github.com/kubernetes/kubernetes/issues/107272.

I updated the `pkg/volume/emptydir/empty_dir.go` part to fix the logic and add some comments in `pkg/volume/util/fsquota/project.go`.

#### Does this PR introduce a user-facing change?

```release-note
fix a 1.24 regression in kubelet: fix a bug of stoping rendering configmap when enabling fsquota monitoring
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by pacoxu** [comment]
/priority important-soon
I need do some more test on this later.

**Comment by pacoxu** [comment]
- Test failed [without this fix #112626](https://github.com/kubernetes/kubernetes/pull/112626): This is a test running with LocalStorageCapacityIsolationFSQuotaMonitoring to beta.  https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112626/pull-kubernetes-node-crio-cgrpv2-e2e/1572531675106119680/
- Test passed in this PR #112625: set LocalStorageCapacityIsolationFSQuotaMonitoring to beta  https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112625/pull-kubernetes-node-crio-cgrpv2-e2e/1572529867889577984/

This can prove that this can fix the regression.

**Comment by dims** [comment]
This PR has the label work-in-progress, please revisit to see if you still need this, please close if not

**Comment by pacoxu** [comment]
The bug was caused by https://github.com/kubernetes/kubernetes/pull/107302 by me when I fixed https://github.com/kubernetes/kubernetes/issues/107272.
/cc @jsafrane @dashpole 

I updated the `pkg/volume/emptydir/empty_dir.go` part to fix the logic and add some comments in `pkg/volume/util/fsquota/project.go`.

File: pkg/volume/util/fsquota/quota_linux.go [hunk 1]
```diff
@@ -304,7 +304,7 @@ func SupportsQuotas(m mount.Interface, path string) (bool, error) {
 // AssignQuota chooses the quota ID based on the pod UID and path.
 // If the pod UID is identical to another one known, it may (but presently
 // doesn't) choose the same quota ID as other volumes in the pod.
-func AssignQuota(m mount.Interface, path string, poduid types.UID, bytes *resource.Quantity) error { //nolint:staticcheck // SA4009 poduid is overwritten by design, see comment below
+func AssignQuota(m mount.Interface, path string, _ types.UID, bytes *resource.Quantity) error {
```
Comment (jsafrane) [inline pkg/volume/util/fsquota/quota_linux.go:307]: Please remove `poduid types.UID` parameter, the function is called only on few places.

File: pkg/volume/emptydir/empty_dir.go [hunk 2]
```diff
@@ -301,12 +302,17 @@ func (ed *emptyDir) assignQuota(dir string, mounterSize *resource.Quantity) erro
...
+			projid, err := fsquota.GetQuotaOnDir(ed.mounter, dir)
+			if err == nil && projid != common.BadQuotaID {
+				klog.V(4).Infof("emptydir trying to assign quota %v on %s", mounterSize, dir)
+				err := fsquota.AssignQuota(ed.mounter, dir, ed.pod.UID, mounterSize)
+				if err != nil {
+					klog.V(3).Infof("Set quota on %s failed %s", dir, err.Error())
+				}
+				return err
+			} else {
+				klog.V(4).Infof("Attempt to check quota on dir %s failed: %v", dir, err)
```
Comment (jsafrane) [inline pkg/volume/emptydir/empty_dir.go:314]: When `err == nil && projid == common.BadQuotaID`, this will log "`... failed: <nil>`", which is odd. In what cases can this happen and what does it mean to an user?

Comment (pacoxu) [reply pkg/volume/emptydir/empty_dir.go:314]: This seems to be impossible.
- `BadQuotaID QuotaID = 0`
image

```
if err == nil && projid != common.BadQuotaID {
```
can change to 
```
if err == nil {
```

Should I change it?

File: pkg/volume/util/fsquota/quota_linux.go (hunk 1 above)
Comment (pacoxu) [reply pkg/volume/util/fsquota/quota_linux.go:307]: Updated.

File: pkg/volume/emptydir/empty_dir.go (hunk 2 above)
Comment (jsafrane) [reply pkg/volume/emptydir/empty_dir.go:314]: Yes please, it would be more obvious.

Comment (pacoxu) [reply pkg/volume/emptydir/empty_dir.go:314]: Updated.

File: pkg/volume/emptydir/empty_dir.go [hunk 3]
```diff
@@ -301,12 +301,17 @@ func (ed *emptyDir) assignQuota(dir string, mounterSize *resource.Quantity) erro
 		if err != nil {
 			klog.V(3).Infof("Unable to check for quota support on %s: %s", dir, err.Error())
 		} else if hasQuotas {
-			klog.V(4).Infof("emptydir trying to assign quota %v on %s", mounterSize, dir)
-			err := fsquota.AssignQuota(ed.mounter, dir, ed.pod.UID, mounterSize)
-			if err != nil {
-				klog.V(3).Infof("Set quota on %s failed %s", dir, err.Error())
+			_, err := fsquota.GetQuotaOnDir(ed.mounter, dir)
+			if err == nil {
```
Comment (rphillips) [inline pkg/volume/emptydir/empty_dir.go:305]: It feels like the logic in this function is backwards to usual golang practices. The functionality doesn't look wrong; just had to read it twice and has nesting that doesn't need to be here.

wdyt  (pretty sure I preserved the logic, but please double check):

```golang
_, err := fsquota.GetQuotaOnDir(ed.mounter, dir)
if err != nil {
  klog.V(4).Infof("Attempt to check quota on dir %s failed: %v", dir, err)
  // this is not a fatal error so return nil
  return nil
}
klog.V(4).Infof("emptydir trying to assign quota %v on %s", mounterSize, dir)
if err := fsquota.AssignQuota(ed.mounter, dir, ed.pod.UID, mounterSize); err != nil {
  klog.V(3).Infof("Set quota on %s failed %s", dir, err.Error())
  return err
}
return nil
```

Comment (pacoxu) [reply pkg/volume/emptydir/empty_dir.go]: This can reduce one level of nesting. It looks better.

Updated.

**Comment by jsafrane** [comment]
/approve
From sig-storage perspective

**Comment by pacoxu** [comment]
I opened cherry-pick PRs for v1.24-v.26. Before that, I want to confirm if there are any CIs with this feature enabled are still failing. I need to add one if there is no such case.

**Comment by alex-matei** [comment]
It doesn't seem this patch fixes the issue.

GetQuotaOnDir call in emptyDir.assignQuota function doesn't do anything. It always returns QuotaID 0 (BadQuotaID) and error is nil if the folder doesn't have quota enabled. If quota is enabled the error is still nil, so the call and if seem unnecessary.

For pods with configmaps the problem still persists:

```
Feb 02 11:38:16 we-test-master-0 kubelet[166883]: E0202 11:38:16.389758  166883 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/configmap/2897430a-11ee-40cb-a35c-42698d4aba2c-settings-vol-config podName:2897430a-11ee-40cb-a35c-42698d4aba2c nodeName:}" failed. No retries permitted until 2023-02-02 11:40:18.389742605 +0000 UTC m=+1670.569255285 (durationBeforeRetry 2m2s). Error: MountVolume.SetUp failed for volume "settings-vol-config" (UniqueName: "kubernetes.io/configmap/2897430a-11ee-40cb-a35c-42698d4aba2c-settings-vol-config") pod "ama-logs-v9h8c" (UID: "2897430a-11ee-40cb-a35c-42698d4aba2c") : requesting quota on existing directory /mnt/kubelet/pods/2897430a-11ee-40cb-a35c-42698d4aba2c/volumes/kubernetes.io~configmap/settings-vol-config but different pod 8a83336a-fea5-4b8d-b9f9-9670bd8d5491 086871d7-c370-482b-bdb8-9db78173dab2
Feb 02 11:38:16 srvless-we-test-master-0 kubelet[166883]: I0202 11:38:16.389776  166883 event.go:294] "Event occurred" object="kube-system/ama-logs-v9h8c" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"settings-vol-config\" : requesting quota on existing directory /mnt/kubelet/pods/2897430a-11ee-40cb-a35c-42698d4aba2c/volumes/kubernetes.io~configmap/settings-vol-config but different pod 8a83336a-fea5-4b8d-b9f9-9670bd8d5491 086871d7-c370-482b-bdb8-9db78173dab2"
```

The code in AssignQuota still generates a new random UID on each call and it compares with the previous one.

After kubelet restart the code still generates an error in createProjectID on every invocation:

```
Feb 02 11:51:20 we-test-master-0 kubelet[207133]: E0202 11:51:20.047407  207133 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/configmap/2897430a-11ee-40cb-a35c-42698d4aba2c-osm-settings-vol-config podName:2897430a-11ee-40cb-a35c-42698d4aba2c nodeName:}" failed. No retries permitted until 2023-02-02 11:52:24.047399889 +0000 UTC m=+129.165734631 (durationBeforeRetry 1m4s). Error: MountVolume.SetUp failed for volume "osm-settings-vol-config" (UniqueName: "kubernetes.io/configmap/2897430a-11ee-40cb-a35c-42698d4aba2c-osm-settings-vol-config") pod "ama-logs-v9h8c" (UID: "2897430a-11ee-40cb-a35c-42698d4aba2c") : assign quota FAILED createProjectID /mnt/kubelet/pods/2897430a-11ee-40cb-a35c-42698d4aba2c/volumes/kubernetes.io~configmap/osm-settings-vol-config 0 failed attempt to reassign project ID for /mnt/kubelet/pods/2897430a-11ee-40cb-a35c-42698d4aba2c/volumes/kubernetes.io~configmap/osm-settings-vol-config
Feb 02 11:51:20 srvless-we-test-master-0 kubelet[207133]: I0202 11:51:20.047417  207133 event.go:294] "Event occurred" object="kube-system/ama-logs-v9h8c" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"osm-settings-vol-config\" : assign quota FAILED createProjectID /mnt/kubelet/pods/2897430a-11ee-40cb-a35c-42698d4aba2c/volumes/kubernetes.io~configmap/osm-settings-vol-config 0 failed attempt to reassign project ID for /mnt/kubelet/pods/2897430a-11ee-40cb-a35c-42698d4aba2c/volumes/kubernetes.io~configmap/osm-settings-vol-config"
```

File: pkg/volume/emptydir/empty_dir.go [hunk 4]
```diff
@@ -301,12 +301,18 @@ func (ed *emptyDir) assignQuota(dir string, mounterSize *resource.Quantity) erro
 		if err != nil {
 			klog.V(3).Infof("Unable to check for quota support on %s: %s", dir, err.Error())
 		} else if hasQuotas {
-			klog.V(4).Infof("emptydir trying to assign quota %v on %s", mounterSize, dir)
-			err := fsquota.AssignQuota(ed.mounter, dir, ed.pod.UID, mounterSize)
+			_, err := fsquota.GetQuotaOnDir(ed.mounter, dir)
```
Comment (alex-matei) [inline pkg/volume/emptydir/empty_dir.go:304]: This call and the check seems superfluous.

File: pkg/volume/util/fsquota/quota_linux.go [hunk 5]
```diff
@@ -319,11 +319,11 @@ func AssignQuota(m mount.Interface, path string, poduid types.UID, bytes *resour
 	// volumes in a pod, we can simply remove this line of code.
 	// If and when we decide permanently that we're going to adopt
 	// one quota per volume, we can rip all of the pod code out.
-	poduid = types.UID(uuid.NewUUID()) //nolint:staticcheck // SA4009 poduid is overwritten by design, see comment above
-	if pod, ok := dirPodMap[path]; ok && pod != poduid {
-		return fmt.Errorf("requesting quota on existing directory %s but different pod %s %s", path, pod, poduid)
+	volumeuid := types.UID(uuid.NewUUID())
```
Comment (alex-matei) [inline pkg/volume/util/fsquota/quota_linux.go:322]: This seems only a change of variable name, how does it fix the problem?
