### PR TITLE
Fix a bug that out-of-tree plugin is misplaced when using scheduler v1beta3 config

### LINKED ISSUE #108083: scheduler v1beta3 pre-appends an out-of-tree plugin instead of append
### What happened?

Out-of-tree plugin typically composes its scheduler ComponentConfig like:

```yaml
profiles:
- plugins:
    preFilter:
      enabled:
      - name: Foo
    filter:
      enabled:
      - name: Foo
```

recently I found that when this is applied into the latest v1beta3 config, `Foo` is pre-appended to the finalized plugin list - i.e., `{preFilter|filter}.enabled = "Foo, <default in-tree plugins>"`.

### What did you expect to happen?

Same as the behavior of v1beta1 and v1beta2, out-of-tree plugin should be placed **at the end** of the finalized pluginList, i.e., preFilter.enabled = "<default plugins>, Foo".

### How can we reproduce it (as minimally and precisely as possible)?

A unit test gist https://gist.github.com/Huang-Wei/09050a3b19e456ea837643f077ff2808 is created to reproduce this issue.

After `git apply` this diff, run `go test ./cmd/kube-scheduler/app/...`:

```
--- FAIL: TestSetup (4.57s)
    --- FAIL: TestSetup/out-of-tree_component_configuration_v1beta3 (0.39s)
        server_test.go:551: Unexpected plugins diff (-want, +got):   map[string]*config.Plugins{
              	"default-scheduler": &{
              		QueueSort: {Enabled: {{Name: "PrioritySort"}}},
              		PreFilter: config.PluginSet{
              			Enabled: []config.Plugin{
            + 				{Name: "Foo"},
              				{Name: "NodeAffinity"},
              				{Name: "NodePorts"},
              				... // 3 identical elements
              				{Name: "PodTopologySpread"},
              				{Name: "InterPodAffinity"},
            - 				{Name: "Foo"},
              			},
              			Disabled: nil,
              		},
              		Filter: config.PluginSet{
              			Enabled: []config.Plugin{
            + 				{Name: "Foo"},
              				{Name: "NodeUnschedulable"},
              				{Name: "NodeName"},
              				... // 11 identical elements
              				{Name: "PodTopologySpread"},
              				{Name: "InterPodAffinity"},
            - 				{Name: "Foo"},
              			},
              			Disabled: nil,
              		},
              		PostFilter: {Enabled: {{Name: "DefaultPreemption"}}},
              		PreScore:   {Enabled: {{Name: "TaintToleration"}, {Name: "NodeAffinity"}, {Name: "PodTopologySpread"}, {Name: "InterPodAffinity"}}},
              		... // 7 identical fields
              	},
              }
FAIL
FAIL	k8s.io/kubernetes/cmd/kube-scheduler/app	4.977s
?   	k8s.io/kubernetes/cmd/kube-scheduler/app/config	[no test files]
ok  	k8s.io/kubernetes/cmd/kube-scheduler/app/options	0.698s
?   	k8s.io/kubernetes/cmd/kube-scheduler/app/testing	[no test files]
FAIL
```

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# master
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind bug
/sig scheduling

#### What this PR does / why we need it:

When custom plugins are specified via regular extension points in v1beta3, the current logic places them at the head,, and then _appends_ internal default plugins (in `expandMultiPointPlugins()`).

However, the eventual order should be like this:

- part 1: plugins that are explicitly re-configured in multipoint (i.e., specified in both regular extension point and multipoint). Note their order should be intact as how they're configured in the regular extension point.
- part 2: plugins enabled in multipoint excluding the ones in part 1. These plugins can be:
  - defaulted in-tree plugin
  - out-of-tree plugin
- part 3: other plugins (excluded by part 1 & 2) in regular extension point. The category contains:
  - non-defaulted in-tree plugin
  - out-of-tree plugin

This PR changes the logic of `expandMultiPointPlugins()` to order the plugins when necessary.

#### Which issue(s) this PR fixes:

Fixes #108083

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug that out-of-tree plugin is misplaced when using scheduler v1beta3 config
```

### CODE REVIEW

**Comment by Huang-Wei** [comment]
With this PR, any testing plugin will be **appended** (not prepend) to the default plugins, that caused [an integration test failure](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/108613/pull-kubernetes-integration/1501674310475976704) cuz DefaultBind would fail (due to the testing context), that failed the pod's scheduling as well as further TestBind plugin's execution.

File: pkg/scheduler/framework/runtime/framework.go [hunk 1]
```diff
@@ -463,23 +490,52 @@ func (f *frameworkImpl) expandMultiPointPlugins(profile *config.KubeSchedulerPro
...
 		}
+
+		// Reorder plugins if needed. Here is the expected order:
+		// - part 1: overridePlugins. Their order stay intact as how they're specified in regular extension point.
+		// - part 2: multiPointEnabled - i.e., plugin defined in multipoint but not overriding regular extension point.
+		// - part 3: other plugins (excluded by part 1 & 2) in regular extension point.
+		newPlugins := reflect.New(reflect.TypeOf(e.slicePtr).Elem()).Elem()
+		// part 1
+		deletionCnt := 0
+		for i, name := range enabledSet.list {
```
Comment (Huang-Wei) [inline pkg/scheduler/framework/runtime/framework.go:519]: In Golang, the iteration order of a map is uncertain, and thus this PR introduces an orderedSet.

Another alternative is to use slice to replace enabledSet, but in that case, we need extra logic to deal with duplicated plugins.

**Comment by Huang-Wei** [comment]
@damemi This PR is ready for review.

File: pkg/scheduler/framework/runtime/framework.go [hunk 2]
```diff
@@ -417,16 +417,43 @@ func getScoreWeights(f *frameworkImpl, pluginsMap map[string]framework.Plugin, p
...
+func (os *orderedSet) insert(s string) {
+	os.set.Insert(s)
+	os.list = append(os.list, s)
+}
+
+func (os *orderedSet) has(s string) bool {
+	return os.set.Has(s)
+}
+
+func (os *orderedSet) delete(i int, s string) {
```
Comment (denkensk) [inline pkg/scheduler/framework/runtime/framework.go:438]: Small suggestion, it seems a bit strange that the user needs to know the index of the item to be deleted. This feels a bit inconsistent with the semantics of set.  

How about use a map `map[string]int` to replace `set` here?

File: pkg/scheduler/framework/runtime/framework.go [hunk 3]
```diff
@@ -463,23 +490,52 @@ func (f *frameworkImpl) expandMultiPointPlugins(profile *config.KubeSchedulerPro
...
 
 			// we only need to update the multipoint set, since we already have the specific extension set from above
-			multiPointEnabled.Insert(ep.Name)
+			multiPointEnabled.insert(ep.Name)
 
 			newPlugins := reflect.Append(plugins, reflect.ValueOf(pg))
 			plugins.Set(newPlugins)
 		}
+
+		// Reorder plugins if needed. Here is the expected order:
```
Comment (kerthcet) [inline pkg/scheduler/framework/runtime/framework.go:512]: It seems like we rearrange all the plugin orders here. So when ` len(profile.Plugins.MultiPoint.Enabled) > 0`, we no longer need above `updatePluginList` process anymore, right?  If this makes sense, we should merge them together.  https://github.com/kubernetes/kubernetes/blob/e9af39914797d40766b166e18dac3a441a2bf5d4/pkg/scheduler/framework/runtime/framework.go#L334-L338

**Comment by damemi** [comment]
Thanks for working on this @Huang-Wei, I will take add some review soon when I have a moment

File: pkg/scheduler/framework/runtime/framework.go (hunk 2 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/runtime/framework.go:438]: sgtm. Thanks.

File: pkg/scheduler/framework/runtime/framework.go (hunk 3 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/runtime/framework.go:512]: I still prefer to keep them separate. When `len(profile.Plugins.MultiPoint.Enabled) > 0`, it's not necessarily going to rearrange the plugins - e.g., all plugins defined in multipoint has been specified in the regular extension point.

File: pkg/scheduler/framework/runtime/framework.go [hunk 4]
```diff
@@ -417,16 +417,51 @@ func getScoreWeights(f *frameworkImpl, pluginsMap map[string]framework.Plugin, p
...
+	list        []string
+	deletionCnt int
+}
+
+func newOrderedSet() *orderedSet {
+	return &orderedSet{set: make(map[string]int)}
+}
+
+func (os *orderedSet) insert(s string) {
+	if _, found := os.set[s]; found {
```
Comment (kerthcet) [inline pkg/scheduler/framework/runtime/framework.go:431]: Reuse `has` method below.

File: pkg/scheduler/framework/runtime/framework.go [hunk 5]
```diff
@@ -463,23 +498,50 @@ func (f *frameworkImpl) expandMultiPointPlugins(profile *config.KubeSchedulerPro
...
+		// - part 3: other plugins (excluded by part 1 & 2) in regular extension point.
+		newPlugins := reflect.New(reflect.TypeOf(e.slicePtr).Elem()).Elem()
+		// part 1
+		for _, name := range enabledSet.list {
+			if overridePlugins.has(name) {
+				newPlugins = reflect.Append(newPlugins, reflect.ValueOf(pluginsMap[name]))
+				enabledSet.delete(name)
+			}
+		}
+		// enabledSet.isEmpty() implies part 3 is empty, so don't need to continue
```
Comment (kerthcet) [inline pkg/scheduler/framework/runtime/framework.go:532]: If I understood correctly, we can harmless remove https://github.com/kubernetes/kubernetes/blob/8ef5ccdad6bba8b664b51a8b29fd1a5ce396a59d/pkg/scheduler/framework/runtime/framework.go#L532-L535 and https://github.com/kubernetes/kubernetes/blob/897f2f78a5c7ff659dfce23f53dd36b9261a23c9/pkg/scheduler/framework/runtime/framework.go#L480-L481

After removal, program still behaves the same but more clearly to read. Separate the reading and writing process.

File: pkg/scheduler/framework/runtime/framework.go (hunk 4 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/runtime/framework.go:431]: done.

File: cmd/kube-scheduler/app/server_test.go [hunk 6]
```diff
@@ -154,6 +157,44 @@ profiles:
...
+      enabled:
+      - name: Foo
+    filter:
+      enabled:
+      - name: Foo
+`, configKubeconfig)), os.FileMode(0600)); err != nil {
+		t.Fatal(err)
+	}
+
+	// plugin config
```
Comment (kerthcet) [inline cmd/kube-scheduler/app/server_test.go:179]: nit: replace with `out-of-tree plugin config v1beta2`

File: pkg/scheduler/framework/runtime/framework.go [hunk 7]
```diff
@@ -463,23 +494,43 @@ func (f *frameworkImpl) expandMultiPointPlugins(profile *config.KubeSchedulerPro
...
 			// we only need to update the multipoint set, since we already have the specific extension set from above
-			multiPointEnabled.Insert(ep.Name)
+			multiPointEnabled.insert(ep.Name)
+		}
 
-			newPlugins := reflect.Append(plugins, reflect.ValueOf(pg))
-			plugins.Set(newPlugins)
+		// Reorder plugins. Here is the expected order:
+		// - part 1: overridePlugins. Their order stay intact as how they're specified in regular extension point.
+		// - part 2: multiPointEnabled - i.e., plugin defined in multipoint but not overriding regular extension point.
```
Comment (kerthcet) [inline pkg/scheduler/framework/runtime/framework.go:515]: s/not overriding/not overrided by/

**Comment by kerthcet** [comment]
Some nits, then LGTM. Left for @damemi for a further review.

File: pkg/scheduler/framework/runtime/framework.go (hunk 7 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/runtime/framework.go:515]: not really, it's the multi-point plugin overriding others instead of the other way around.

File: cmd/kube-scheduler/app/server_test.go (hunk 6 above)
Comment (Huang-Wei) [reply cmd/kube-scheduler/app/server_test.go:179]: will update along with other comments.

**Review by damemi — COMMENTED** [review]
Looks good to me overall. I think breaking the logic out into 3 distinct sets makes it a bit clearer how the precedence works
/approve

File: pkg/scheduler/framework/runtime/framework.go [hunk 8]
```diff
@@ -417,16 +417,47 @@ func getScoreWeights(f *frameworkImpl, pluginsMap map[string]framework.Plugin, p
...
 }
 
+type orderedSet struct {
+	set         map[string]int
+	list        []string
+	deletionCnt int
+}
+
+func newOrderedSet() *orderedSet {
+	return &orderedSet{set: make(map[string]int)}
```
[the remark this answers is not in the document]
Comment (kerthcet) [reply pkg/scheduler/framework/runtime/framework.go:427]: A nil slice is functionally equivalent to a zero-length slice. If we won't gone to use `Marshal` and `reflect. DeepEqual` with this field, freely to us. So I think we can omit it here.

File: pkg/scheduler/framework/runtime/framework.go (hunk 7 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/runtime/framework.go:515]: Correct, it's bi-directional. This may lead to less ambiguity?

```
// - part 2: multiPointEnabled - i.e., plugins defined in multipoint but not in regular extension point.
```

File: pkg/scheduler/framework/runtime/framework.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/framework/runtime/framework.go:427]: yup, we usually don't need to initialize a slice. And in terms of using a slice: `var s []string` are in favor of `s := []string`.

**Comment by Huang-Wei** [comment]
Commits squashed.

@damemi please take a another look when you get a chance.

**Comment by Huang-Wei** [comment]
@damemi could you please take another look?

**Comment by damemi** [comment]
Sorry @Huang-Wei, I only had those 2 nits. The rest looks good, thanks for fixing this
/lgtm

**Comment by kerthcet** [comment]
We should rebase the code as we changed the `PreFilterPlugin` interface days before.

**Comment by Huang-Wei** [comment]
@kerthcet @damemi could you please re-/lgtm?

**Comment by denkensk** [comment]
/lgtm 

Thanks. @Huang-Wei
