### PR TITLE
PodTopologySpread plugin now excludes terminatingPods

### LINKED ISSUE #86037: TopologySpreadConstraint not acting as expected
**How to reproduce it (as minimally and precisely as possible)**:
pre-requisites: a multi-az cluster, a deployment with 1 pod in each az.
1. apply a `topologySpreadConstraint` with `maxSkew=1` and `whenUnsatisfiable: DoNotSchedule`.
2. cordon the node(s) in 1 az.
3. delete the deployment's pod(s) from the cordoned az.

**What happened**:
A new pod was created and scheduled in a form that `number_of_pods_AZ_1 - number_of_pods_AZ_2 > maxSkew`

**What you expected to happen**:

I expected that a new pod will be created and be "stuck" in `pending` status as it shouldn't have nowhere be scheduled.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):
```NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2247.7.0
VERSION_ID=2247.7.0
BUILD_ID=2019-11-19-2251
PRETTY_NAME="Container Linux by CoreOS 2247.7.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
- Kernel (e.g. `uname -a`): 4.19.84-coreos
- Others: I created a [screen capture video](https://youtu.be/RiLNyW5D9rk) with how I reproduce the bug

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind feature
/sig scheduling

**What this PR does / why we need it**:

The background is discussed at #87632 

In short, all scheduler (filter) plugins take terminating Pods into consideration, however, for some particular case (e.g., PodTopologySpread), it may be reasonable to exclude the terminating Pods.

**Which issue(s) this PR fixes**:

Fixes #86037

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
PodTopologySpread plugin now excludes terminatingPods when making scheduling decisions.
```

/cc @ahg-g @alculquicondor

### CODE REVIEW

File: pkg/scheduler/framework/plugins/podtopologyspread/scoring.go [hunk 1]
```diff
@@ -135,6 +135,10 @@ func (pl *PodTopologySpread) PostFilter(
 			// <matchSum> indicates how many pods (on current node) match the <constraint>.
 			matchSum := int64(0)
 			for _, existingPod := range nodeInfo.Pods() {
+				// Bypass terminating Pod (see #87621).
+				if existingPod.DeletionTimestamp != nil || existingPod.Namespace != pod.Namespace {
```
Comment (skilxn-go) [inline pkg/scheduler/framework/plugins/podtopologyspread/scoring.go]: I'm curious about why the namespace is not checked before?

File: pkg/scheduler/scheduler_test.go [hunk 2]
```diff
@@ -1030,3 +1033,145 @@ func TestSchedulerBinding(t *testing.T) {
...
+			t.Fatalf("timeout waiting for p1 and p2 to be scheduled.")
+		}
+	}
+	p1Copy := p1.DeepCopy()
+	now := metav1.Now()
+	p1Copy.DeletionTimestamp = &now
+	// Simulate a Pod deletion operation - either by user or controller manager.
+	fakeWatch.Modify(p1Copy)
+	// p3 is simulated as a replacement Pod created by controller manager.
+	time.Sleep(time.Millisecond * 200)
```
Comment (Huang-Wei) [inline pkg/scheduler/scheduler_test.go]: Without this line, this UT may fail. It's because even if the AddEvent for p3 comes after UpdateEvent for p1, scheduleOne() (afterwards snapshot()) may happen before updatePodInCache()'s completion - as they're two goroutines. In that case, p3 can be either scheduled to node1 or node2, instead of being forced to scheduled to where p1 was scheduled.

This is not observed/reported in real usage yet, but it's technically possible.

File: pkg/scheduler/scheduler_test.go [hunk 3]
```diff
@@ -1030,3 +1033,145 @@ func TestSchedulerBinding(t *testing.T) {
...
+	p3 := st.MakePod().Name("p3").UID("p3").Label("foo", "").SpreadConstraint(
```
Comment (Huang-Wei) [inline pkg/scheduler/scheduler_test.go]: Maybe rename to `p1Backfill`.

File: pkg/scheduler/framework/plugins/podtopologyspread/scoring.go (hunk 1 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/podtopologyspread/scoring.go]: I have to admit it was a pre-existing bug...

Comment (skilxn-go) [reply pkg/scheduler/framework/plugins/podtopologyspread/scoring.go]: Got it.

File: pkg/scheduler/scheduler_test.go (hunk 2 above)
Comment (skilxn-go) [reply pkg/scheduler/scheduler_test.go]: Is 200ms enough for p3's update? Will this cause a flake test?

Comment (haosdent) [inline pkg/scheduler/scheduler_test.go]: Is `time.Sleep` necessary here?

File: pkg/scheduler/scheduler_test.go [hunk 4]
```diff
@@ -1030,3 +1033,145 @@ func TestSchedulerBinding(t *testing.T) {
 		})
 	}
 }
+
+type fakeBinder struct {
```
Comment (ahg-g) [inline pkg/scheduler/scheduler_test.go]: I think the test should be in filtering_test.go and scoring_test.go, this will allow us to avoid all those fakes and will make the tests a lot simpler (can be a case in the already existing tests).

File: pkg/scheduler/scheduler_test.go (hunk 2 above)
Comment (haosdent) [reply pkg/scheduler/scheduler_test.go]: Oh, saw your comment.

File: pkg/scheduler/scheduler_test.go (hunk 4 above)
Comment (Huang-Wei) [reply pkg/scheduler/scheduler_test.go]: Not really. The tests in filtering_test.go and scoring_test.go are based on a statically built snapshot, and then schedule a Pod to verify its result. While this test needs to test how the 3 goroutines (main scheduling, cache, schedulingQ) work together. So here I have to use a fake binder to set the pod.spec.nodeName manually, to mimic the v1.Binding behavior.

Comment (ahg-g) [reply pkg/scheduler/scheduler_test.go]: > The tests in filtering_test.go and scoring_test.go are based on a statically built snapshot, and then schedule a Pod to verify its result.

And that is enough to test whether or not the PodTopologySpread logic excludes terminating pods. Why do you need to create a full scheduler and all three routines to test that?

File: pkg/scheduler/scheduler_test.go (hunk 2 above)
Comment (Huang-Wei) [reply pkg/scheduler/scheduler_test.go]: Usually, it's enough as it's a unit test env. But anyway, let me make it more robust. PTAL.

**Comment by Huang-Wei** [comment]
/hold
for squashing commits later.

File: pkg/scheduler/framework/plugins/podtopologyspread/scoring.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/scheduler/framework/plugins/podtopologyspread/scoring.go]: Let's add a separate regression test for the namespace.

File: pkg/scheduler/scheduler_test.go (hunk 4 above)
Comment (alculquicondor) [reply pkg/scheduler/scheduler_test.go]: First of all, we should have a unit test for just "terminated pods" in filtering_test.go and scoring_test.go.

Now, this complex scenario that spans through a few cycles is more of integration test. A better place for it would be `test/integration/scheduler/priorities_test.go`. And then we don't need fakes. But... this might be an overkill.

That said, do we have any tests that make sure our cache stays up to date with apiserver updates? That seems useful, but definitely outside of the scope of this PR.

Comment (alculquicondor) [reply pkg/scheduler/scheduler_test.go]: It looks like we are lacking a bunch of unit tests for eventhandlers.go :(
But maybe we should handle this in integration directly. If you agree, I'll open an issue.

Comment (Huang-Wei) [reply pkg/scheduler/scheduler_test.go]: > And that is enough to test whether or not the PodTopologySpread logic excludes terminating pods. Why do you need to create a full scheduler and all three routines to test that?

It's true that from the code's coverage point of view, a unit test in filtering_test.go and scoring_test.go is enough. But that wouldn't reproduce the issue - that'd be merely based our debugging result and lack the whole context. I don't believe that'd be sufficient. And as I mentioned in https://github.com/kubernetes/kubernetes/pull/87845#discussion_r375111677, once we get a reporting saying that a new Pod's scheduling cycle can begin before a previous one's caching cycle, this test can quickly detect that and verify potential fix.
Also, we do have similar UTs exercising the full scheduler, but not fully adhere to the new framework. This test can work as a sample to refactor those tests.

An e2e test can work the same as this UT, but that's expensive.

> First of all, we should have a unit test for just "terminated pods" in filtering_test.go and scoring_test.go.

I can make it later once we got to a consensus on the necessity of whether we need this UT.

> Now, this complex scenario that spans through a few cycles is more of integration test.

I thought about an integration test also. However, it's challenging to simulate deleting a Pod while triggering an update event. As you know, in an integration test, there is no kubelet running, you can only "delete" a Pod using deletionGracePeriod=0.

> It looks like we are lacking a bunch of unit tests for eventhandlers.go :(

Probably, we can give a try. But according to my experiences, it'd easier to be covered in UT, using fake clientset and watch.

Comment (alculquicondor) [reply pkg/scheduler/scheduler_test.go]: > I thought about an integration test also. However, it's challenging to simulate deleting a Pod while triggering an update event. As you know, in an integration test, there is no kubelet running, you can only "delete" a Pod using deletionGracePeriod=0.

What if you do two separate `cs.CoreV1().Pods(ns).Delete`? One with a grace period and another without it. In that meantime, you wait for a scheduling cycle.

I still think we should have a true "unit" test that is not concerned about order of events, just the fact that terminated pods should be excluded. The thing is, I don't think we had a bug, but rather a new requirement. And this is independent of order of events, which is what we initially thought. It's just the deployments controller creating a new pod early (which is good for availability). We don't have bugs on how we are updating the pods when a pod is terminating. (We should have unit tests for this though, as I said before). But, if we truly believe that we need to cover this, we should have an E2E test (with the controllers and kubelets).

If we plan to add more "UTs" exercising a full scheduler, maybe we should have a folder just for them with some utilities (like the fake binder) in their own package.

Comment (Huang-Wei) [reply pkg/scheduler/scheduler_test.go]: > What if you do two separate cs.CoreV1().Pods(ns).Delete? One with a grace period and another without it. In that meantime, you wait for a scheduling cycle.

I guess the first one (with grace period) wouldn't work at all, but we can give a try, in terms of integration test.

> I still think we should have a true "unit" test that is not concerned about order of events, just the fact that terminated pods should be excluded.

It's what you mentioned as a pure UT in filtering_test.go & scoring_test.go, right? Sure, I can add it.

> We don't have bugs on how we are updating the cache when a pod is terminating (We should have unit tests for this though, as I said before)

There _may_ be a bug: as I mentioned earlier, we don't guarantee the cache's handling cycle on an old pod can finish **every time** before the new pod's scheduling cycle, even if controller manager and API server can guarantee the event of old pod will always be dispatched before the new pod. The case is kind like this:

- T1: old pod update event comes in. Then cache goroutine gets an update on old pod's update (spec.deletionTimestamp != nil)
- T2: new pod event comes in. Then schedulingQ pushes a new pod and Pop() it
- T3: main scheduling goroutine starts to do snapshot() on cache, and starts to schedule the new pod
- T4: cache goroutine finishes its cycle on old pod's update

I'm not sure in a real case it can happen, but in a UT, this can simulated b/c in T1, it doesn't immediately lock the cache. So I think the possibility is low, and in this UT, I intentionally wait for the cache cycle to be finished and push the new pod.

Comment (ahg-g) [reply pkg/scheduler/scheduler_test.go]: > It's what you mentioned as a pure UT in filtering_test.go & scoring_test.go, right? Sure, I can add it.

Yes, we should have that regardless, in addition to the one for pod namespace.

> There may be a bug: as I mentioned earlier, we don't guarantee the cache's handling cycle ...

We can certainly add tests to verify that the cache is updated properly and that whatever state in the snapshot is consistent, but all of this isn't related to how we implement the exclusion of terminating pods in the Plugin.

Comment (alculquicondor) [reply pkg/scheduler/scheduler_test.go]: > It's what you mentioned as a pure UT in filtering_test.go & scoring_test.go, right? Sure, I can add it.

Yes

> So I think the possibility is low, and in this UT, I intentionally wait for the cache cycle to be finished and push the new pod.

So you are saying this UT is not covering the sequence you described?

In any case, that should be covered in a separate unit test for the cache. Basically, a test that adds events and immediately after produces a snapshot, which should be consistent.

Comment (Huang-Wei) [reply pkg/scheduler/scheduler_test.go]: > Yes, we should have that regardless, in addition to the one for pod namespace.

Will do that.

> We can certainly add tests to verify that the cache is updated properly and that the snapshot state is consistent

It's just that it's _possible_ the cache cycle started, but hasn't reached to locking and update the cache in place; while the scheduling cycle starts, and lock the (stale) cache and schedule a new pod.

> but all of this isn't related to how we implement the exclusion of terminating pods in the Plugin.

Nope, this is not covered in this UT. Actually, that needs a "fix".

> So you are saying this UT is not covering the sequence you described?

It's not - it's intentionally waiting for cache cycle to be finished:

```go
// Simulate a Pod deletion operation - either by user or controller manager.
fakeWatch.Modify(p1Copy)
// Ensure p1Copy has been handled in cache.
wait.PollImmediate(100*time.Millisecond, time.Second, func() (bool, error) {
	p1InCache, err := cache.GetPod(p1Copy)
	return p1InCache.GetDeletionTimestamp() != nil, err
})
```

> In any case, that should be covered in a separate unit test for the cache. Basically, a test that adds events and immediately after produces a snapshot, which should be consistent.

We can pursue that, in another test along with a "fix".

Comment (alculquicondor) [reply pkg/scheduler/scheduler_test.go]: for a separate PR :)

Other than that, for this feature, I think we are good to go with a pure unit test.

Comment (Huang-Wei) [reply pkg/scheduler/scheduler_test.go]: > for a separate PR :)

SGTM. Will extract the complex UT in this PR to a separate one, and only focus on verifying the cache/snapshot consistency.

File: pkg/scheduler/framework/plugins/podtopologyspread/scoring_test.go [hunk 5]
```diff
@@ -429,6 +429,44 @@ func TestPodTopologySpreadScore(t *testing.T) {
 				{Name: "node-x", Score: 100},
 			},
 		},
+		{
+			name: "existing pods with mis-matched namespace do not count",
```
Comment (alculquicondor) [inline pkg/scheduler/framework/plugins/podtopologyspread/scoring_test.go]: nit: `in a different namespace`
Saying `mis-matched` sounds like it's a user error.

**Review by alculquicondor — COMMENTED** [review]
/lgtm

but just a minor nit.

File: pkg/scheduler/framework/plugins/podtopologyspread/scoring_test.go (hunk 5 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/podtopologyspread/scoring_test.go]: done.
