### PR TITLE
Skip updating scheduler cache on pod update if the node was deleted

### LINKED ISSUE #89552: Delete node causing scheduler crash
**What happened**:
If we delete node first, then remove pods on this node, the scheduler will crash in `RemovePod` function

**What you expected to happen**:
Not crashed

**How to reproduce it (as minimally and precisely as possible)**:
1. Create some pods on node A
2. kubectl delete node A
3. kubectl delete pods on node A

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16-1.18, even master
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by alculquicondor**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

/sig scheduling

Skip updating scheduler cache on pod update if the node was deleted. This can happen when events arrive out of order.
The fix doesn't skip updates on pods that might arrive before its node is created. There will always be a pod creation event first that would cause the cache to add a placeholder node.

Add unit test for out-of-order pod/node creation/removal.
This should help spot bugs when:
- Pod creation event arrives before node creation
- Node removal event arrives before corresponding pod removal.

**Which issue(s) this PR fixes**:

Fixes #89552

This only reproduced with at least 2 pods in the node being removed.

**Does this PR introduce a user-facing change?**:

```release-note
Fix scheduler crash when removing node before its pods
```

### CODE REVIEW

**Review by ahg-g — COMMENTED** [review]
tests are failing

File: pkg/scheduler/internal/cache/cache.go [hunk 1]
```diff
@@ -428,10 +428,16 @@ func (cache *schedulerCache) addPod(pod *v1.Pod) {
...
+		// The node might have been deleted already.
+		// This is not a problem in the case where an pod update arrives
+		// before the node creation, because we will always have a create pod event
+		// before that, which will create the placeholder node item.
+		return nil
+	}
 	if err := cache.removePod(oldPod); err != nil {
 		return err
 	}
-	cache.addPod(newPod)
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/cache.go:434]: Yeah, this was the mistake

**Comment by ahg-g** [comment]
we should backport this, right?

**Comment by alculquicondor** [comment]
Yes, I'm on it.
