### PR TITLE
`--force` only takes effect when `--grace-period=0`

### LINKED ISSUE #61374: `kubectl delete --force` doesn't work as expected
IMO it's surprising that `kubectl delete foo --force` does not force delete a resource. `--force` only takes effect when `--grace-period=0`. 

https://github.com/kubernetes/kubernetes/blob/7bcfbcd58515421d9756fc9bf89371c4e5257b2b/pkg/kubectl/cmd/delete.go#L211-L221

The description of `--force` reads this: `Immediate deletion of some resources may result in inconsistency or data loss and requires confirmation.`

We should make it more clear what `--force` does and even print warnings when `--force` is specified without `--grace-period=0`. 

@kubernetes/sig-cli-maintainers @smarterclayton

### PR DESCRIPTION
**Pull request by ChiuWang**
`kubectl delete` should warn when `force` is specified without `--grace-period=0`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #61374 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

File: pkg/kubectl/cmd/delete.go [hunk 1]
```diff
@@ -218,6 +218,10 @@ func (o *DeleteOptions) Validate(cmd *cobra.Command) error {
 			o.WaitForDeletion = true
 			o.GracePeriod = 1
 		}
+	} else {
+		if o.ForceDeletion {
+			return fmt.Errorf("--force should be specified with --grace-period=0")
```
Comment (dixudx) [inline pkg/kubectl/cmd/delete.go]: I'd prefer to print warnings instead of errors.

**Review by dixudx — CHANGES_REQUESTED** [review]

File: pkg/kubectl/cmd/delete.go (hunk 1 above)
Comment (charrywanganthony) [reply pkg/kubectl/cmd/delete.go]: @dixudx Done.

File: pkg/kubectl/cmd/delete.go [hunk 2]
```diff
@@ -218,6 +218,10 @@ func (o *DeleteOptions) Validate(cmd *cobra.Command) error {
 			o.WaitForDeletion = true
 			o.GracePeriod = 1
 		}
+	} else {
+		if o.ForceDeletion {
```
Comment (janetkuo) [inline pkg/kubectl/cmd/delete.go]: nit: just use `else if`

**Review by soltysh — CHANGES_REQUESTED** [review]
I'd prefer to update the command description, flag description and examples with information about the need for using both rather than throwing a warning at user.

**Comment by charrywanganthony** [comment]
@soltysh I will update the description part, but the warning seems necessary as well.

**Comment by soltysh** [comment]
> @soltysh I will update the description part, but the warning seems necessary as well.

ok

**Comment by janetkuo** [comment]
Suggest changing flag description as follows:

`--force`: **Only used when grace-period=0. If true, immediately remove resources from API and bypass graceful deletion. Note that i**mmediate deletion of some resources may result in inconsistency or data loss and requires confirmation. 

`--grace-period`: Period of time in seconds given to the resource to terminate gracefully. Ignored if negative. **Set to 1 for immediate shutdown. Can only be set to 0 when --force is true (force deletion).** 

cc @smarterclayton to review the flag description.

I also agree that a warning is necessary, since `kubectl delete --force` acts the same as `kubectl delete`, which may be surprising to users.

File: pkg/kubectl/cmd/delete.go [hunk 3]
```diff
@@ -218,6 +218,8 @@ func (o *DeleteOptions) Validate(cmd *cobra.Command) error {
 			o.WaitForDeletion = true
 			o.GracePeriod = 1
 		}
+	} else if o.ForceDeletion {
+		fmt.Fprintf(o.ErrOut, "warning: --force should be specified with --grace-period=0")
```
Comment (janetkuo) [inline pkg/kubectl/cmd/delete.go]: `warning: --force is ignored because --grace-period is not 0.\n`

To make it clear that `--force` doesn't do anything here and a normal delete operation is sent.

File: pkg/kubectl/cmd/delete.go [hunk 4]
```diff
@@ -218,6 +218,8 @@ func (o *DeleteOptions) Validate(cmd *cobra.Command) error {
 			o.WaitForDeletion = true
 			o.GracePeriod = 1
 		}
+	} else if o.ForceDeletion {
```
Comment (janetkuo) [inline pkg/kubectl/cmd/delete.go]: There's a function `printDeletion` that prints "resource foo deleted" after deletion operation is sent successfully. 

Would you change the operation to "force deleted" when `o.GracePeriod == 0`? So that `kubectl delete pod foo --grace-period=0 --force` prints `pod "foo" force deleted`.

Comment (charrywanganthony) [reply pkg/kubectl/cmd/delete.go]: @janetkuo  Modified.
cc @soltysh

**Review by soltysh — APPROVED** [review]
lgtm, I'll leave it for Janet or Clayton for final approval

**Review by janetkuo — APPROVED** [review]
