### PR TITLE
iSCSI plugin: Update devicepath with filepath.Glob result

### LINKED ISSUE #47253: iSCSI iSER mounting does use glob path for mount utilities
**Kubernetes version** (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-beta.1", GitCommit:"dfaba882698e26a47fb769be45fe5c048a9fe4ad", GitTreeState:"not a git tree", BuildDate:"2017-06-08T13:08:32Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.3", GitCommit:"0480917b552be33e2dba47386e51decb1a211df6", GitTreeState:"clean", BuildDate:"2017-05-10T15:38:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**Environment**:
- **Cloud provider or hardware configuration**: Bare-Metal, HP SE316M, 2x X5675, 144GB, iSCSI/RDMA/iSer
- **OS**: CentOS 7
- **Kernel**: Linux at-host-18 4.9.31 #1 SMP Wed Jun 7 22:40:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- **Install tools**: 
- **Others**:

**What happened**:
I want to mount a iSCSI volume via iSER (RDMA over Infiniband) in this case the iSCSI iface is "iser" and not tcp, therefore the glob path for device mount is selected (iscsi_util.go:215), which then is passed to the fsck and mount commands without globbing the path (e.g. calling filepath.Glob)

Therefore the iSCSI volume is not mounted and the pod cannot be started.

**Logs**:
```
Jun  9 16:59:35 at-host-18 kernel: sd 5:0:0:0: alua: supports implicit and explicit TPGS
Jun  9 16:59:35 at-host-18 kernel: sd 5:0:0:0: alua: device naa.600140581cc879dd8a646fb9d818e1cf port group 0 rel port 1
Jun  9 16:59:35 at-host-18 kernel: sd 5:0:0:0: alua: port group 00 state A non-preferred supports TOlUSNA
Jun  9 16:59:35 at-host-18 kernel: sd 5:0:0:0: alua: supports implicit and explicit TPGS
Jun  9 16:59:35 at-host-18 kernel: sd 5:0:0:0: alua: device naa.600140581cc879dd8a646fb9d818e1cf port group 0 rel port 1
Jun  9 16:59:35 at-host-18 kernel: sd 5:0:0:0: alua: port group 00 state A non-preferred supports TOlUSNA
Jun  9 16:59:35 at-host-18 kubelet: I0609 16:59:35.354226   18204 mount_linux.go:347] `fsck` error fsck from util-linux 2.23.2
Jun  9 16:59:35 at-host-18 kubelet: fsck.ext2: No such file or directory while trying to open /dev/disk/by-path/pci-*-ip-10.0.13.3:3260-iscsi-iqn.2017-01.at.cf-it.at-storage-01-lun-0
Jun  9 16:59:35 at-host-18 kubelet: Possibly non-existent device?
Jun  9 16:59:35 at-host-18 kubelet: E0609 16:59:35.358239   18204 mount_linux.go:122] Mount failed: exit status 32
Jun  9 16:59:35 at-host-18 kubelet: Mounting command: mount
Jun  9 16:59:35 at-host-18 kubelet: Mounting arguments: /dev/disk/by-path/pci-*-ip-10.0.13.3:3260-iscsi-iqn.2017-01.at.cf-it.at-storage-01-lun-0 /var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-iser/10.0.13.3:3260-iqn.2017-01.at.cf-it.at-storage-01-lun-0 ext4 [defaults]
Jun  9 16:59:35 at-host-18 kubelet: Output: mount: special device /dev/disk/by-path/pci-*-ip-10.0.13.3:3260-iscsi-iqn.2017-01.at.cf-it.at-storage-01-lun-0 does not exist
Jun  9 16:59:35 at-host-18 kubelet: E0609 16:59:35.362929   18204 mount_linux.go:406] Could not determine if disk "/dev/disk/by-path/pci-*-ip-10.0.13.3:3260-iscsi-iqn.2017-01.at.cf-it.at-storage-01-lun-0" is formatted (exit status 1)
Jun  9 16:59:35 at-host-18 kubelet: E0609 16:59:35.362987   18204 iscsi_util.go:301] iscsi: failed to mount iscsi volume /dev/disk/by-path/pci-*-ip-10.0.13.3:3260-iscsi-iqn.2017-01.at.cf-it.at-storage-01-lun-0 [ext4] to /var/lib/kubelet/plugins/kubernetes.io/iscsi/iface-iser/10.0.13.3:3260-iqn.2017-01.at.cf-it.at-storage-01-lun-0, error exit status 1
Jun  9 16:59:35 at-host-18 kubelet: E0609 16:59:35.363008   18204 disk_manager.go:51] failed to attach disk
Jun  9 16:59:35 at-host-18 kubelet: E0609 16:59:35.363022   18204 iscsi.go:247] iscsi: failed to setup
```

**What you expected to happen**:
To successfully mount the volume.

**How to reproduce it** (as minimally and precisely as possible):
Setup an iSCSI via RDMA (iSER) environment without multipath and try to mount a volume for a pod.

**Anything else we need to know**:
I believe it's just needed to add the globbing at line 259 like so:

devicePaths = append(devicePaths, filepath.Glob(devicePath))

As I'm not a go programmer and have no experience with it, probably somebody could create a commit which I would gladly test!

### PR DESCRIPTION
**Pull request by mtanino**
**What this PR does / why we need it**:

If iscsiTransport is not tcp, iSCSI plugin tries to
find devicepath using filepath.Glob but never updates
devicepath with the filepath.Glob result.

This patch fixes the problem.

**Which issue this PR fixes** : fixes #47253
**Special notes for your reviewer**:

**Release note**:

```release-note
Fix iSCSI iSER mounting.
```

### CODE REVIEW

**Comment by mtanino** [comment]
@rootfs @humblec @Thoro

File: pkg/volume/iscsi/iscsi_util.go [hunk 1]
```diff
@@ -89,20 +89,25 @@ func updateISCSINode(b iscsiDiskMounter, tp string) error {
 type StatFunc func(string) (os.FileInfo, error)
 type GlobFunc func(string) ([]string, error)
 
-func waitForPathToExist(devicePath string, maxRetries int, deviceTransport string) bool {
+func waitForPathToExist(devicePath *string, maxRetries int, deviceTransport string) bool {
 	// This makes unit testing a lot easier
```
Comment (rootfs) [inline pkg/volume/iscsi/iscsi_util.go]: validate devicePath != nil

File: pkg/volume/iscsi/iscsi_util.go [hunk 2]
```diff
@@ -89,20 +89,25 @@ func updateISCSINode(b iscsiDiskMounter, tp string) error {
...
 	return waitForPathToExistInternal(devicePath, maxRetries, deviceTransport, os.Stat, filepath.Glob)
 }
 
-func waitForPathToExistInternal(devicePath string, maxRetries int, deviceTransport string, osStat StatFunc, filepathGlob GlobFunc) bool {
+func waitForPathToExistInternal(devicePath *string, maxRetries int, deviceTransport string, osStat StatFunc, filepathGlob GlobFunc) bool {
 	for i := 0; i < maxRetries; i++ {
 		var err error
 		if deviceTransport == "tcp" {
-			_, err = osStat(devicePath)
```
Comment (rootfs) [inline pkg/volume/iscsi/iscsi_util.go]: validate devicePath != nil

File: pkg/volume/iscsi/iscsi_util.go [hunk 3]
```diff
@@ -89,20 +89,25 @@ func updateISCSINode(b iscsiDiskMounter, tp string) error {
...
 		} else {
-			fpath, _ := filepathGlob(devicePath)
+			fpath, _ := filepathGlob(*devicePath)
 			if fpath == nil {
 				err = os.ErrNotExist
+			} else {
+				// There might be a case that fpath contains multiple device paths if
+				// multiple PCI devices connect to same iscsi target. We handle this
+				// case at subsequent logic. Pick up only first path here.
+				*devicePath = fpath[0]
```
Comment (rootfs) [inline pkg/volume/iscsi/iscsi_util.go]: @mtanino @Thoro can you get a sample of /dev/disk/by-path/ and add to the comment? Would it be possible to sort the path and pick the first one? I am concerned if the path appears at non-deterministic order, there is a chance the devicePath is randomly chosen yet point to the same target, which could be a problem later for logout.

Comment (mtanino) [inline pkg/volume/iscsi/iscsi_util.go]: @Thoro 
Could you paste your result here? I don't have iSER device, so I can't.

Comment (mtanino) [inline pkg/volume/iscsi/iscsi_util.go]: I'm guessing this kind of results might be obtained.

- /dev/disk/by-path/pci-DEVICE1-ip-127.0.0.1:3260-iqn.2014-12.com.example:test.tgt00-lun-0
- /dev/disk/by-path/pci-DEVICE2-ip-127.0.0.1:3260-iqn.2014-12.com.example:test.tgt00-lun-0

**Comment by rootfs** [comment]
@k8s-bot ok to test
/approve

File: pkg/volume/iscsi/iscsi_util.go (hunk 2 above)
Comment (mtanino) [inline pkg/volume/iscsi/iscsi_util.go]: Done.

**Comment by mtanino** [comment]
- devicePath != nil check added to waitForPathToExist().

File: pkg/volume/iscsi/iscsi_util.go (hunk 3 above)
Comment (Thoro) [inline pkg/volume/iscsi/iscsi_util.go]: Path would look like that, the 

/dev/disk/by-path/pci-0000:06:00.0-ip-10.0.13.3:3260-iscsi-iqn.2017-01.at.cf-it.at-storage-01-lun-0

which corresponds to the Infiniband Adapter

06:00.0 InfiniBand: QLogic Corp. IBA7322 QDR InfiniBand HCA (rev 01)

**Comment by Thoro** [comment]
@rootfs @mtanino Confirmed working on my local install - no more errors!

**Comment by mtanino** [comment]
@Thoro 
Thanks!

@rootfs 
Is this proper to backport to v1.6?

**Comment by rootfs** [comment]
@Thoro do you need it in 1.6?

**Comment by Thoro** [comment]
@rootfs Nope, is missing the CHAP Auth anyways ;) - running my own from master

**Comment by rootfs** [comment]
@Thoro Happy bug reporting!

**Comment by mtanino** [comment]
@rootfs @Thoro 
Since this PR is bug fix, it's worthwhile to backport even if the reporter does not use it, IMO.

**Comment by mtanino** [comment]
@childsb @eparis @rootfs 
Could you add v1.7 milestone for this PR?
Thanks.

**Comment by mtanino** [comment]
@eparis
Thanks!
