### PR TITLE
Fix the job finished metric issue due to the final job status update occasionally failing

### LINKED ISSUE #112873: Occasional double counting of job completions in the `job_controller_job_finished_total` metric
### What happened?

Occasionally job completions are counted twice (or potentially multiple times?) in the  `job_controller_job_finished_total` metric.  This happens for about 20% of jobs, but may depend on the Job specificity, which results in an overestimation of the number of finished jobs.

### What did you expect to happen?

The `job_controller_job_finished_total` metric reflects the actual number of completed jobs.

### How can we reproduce it (as minimally and precisely as possible)?

1. Setup a kind cluster with prometheus monitoring stack (for example follow this: https://medium.com/@charled.breteche/kind-fix-missing-prometheus-operator-targets-1a1ff5d8c8ad).

2. Check the number of completed jobs by inspecting the `job_controller_job_finished_total` metric

3. Create and delete a job multiple times in a loop

Example job:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: indexed-job
  labels:
    jobgroup: indexedjob
spec:
  completions: 5
  parallelism: 3
  completionMode: Indexed
  template:
    metadata:
      labels:
        jobgroup: indexedjob
    spec:
      restartPolicy: Never
      initContainers:
      - name: input
        image: 'docker.io/library/bash'
        command:
        - "bash"
        - "-c"
        - |
          items=(foo bar baz qux xyz)
          echo ${items[$JOB_COMPLETION_INDEX]} > /input/data.txt
        volumeMounts:
        - mountPath: /input
          name: input
      containers:
      - name: 'worker'
        image: 'docker.io/library/busybox'
        command:
        - "rev"
        - "/input/data.txt"
        volumeMounts:
        - mountPath: /input
          name: input
      volumes:
      - name: input
        emptyDir: {}
```

Example repro script:
```python
import os, time

TMP_KUBE_BUILD = "/tmp/cmd-0123"

def exec_cmd(cmd):
    print("----")
    print(cmd)
    exitCode = os.system(cmd)
    print("exit code: ", exitCode)
    print("----")
    return exitCode

def is_complete():
    exec_cmd("kubectl get jobs | tee %s" % TMP_KUBE_BUILD)
    with open(TMP_KUBE_BUILD) as file:
        for line in file.readlines():
            if "indexed-job" in line and "5/5" in line:
                return True
        return False

def await_complete():
    is_complete_tmp = False
    while not is_complete_tmp:
        is_complete_tmp = is_complete()
        time.sleep(5.0)

if __name__ == "__main__":
    for i in range(1, 11):
        print("=============================== START: " + str(i))
        if exec_cmd("kubectl create -f job-indexed.yaml") != 0:
            continue
        await_complete()
        if exec_cmd("kubectl delete -f job-indexed.yaml") != 0:
            continue
        print("=============================== END: " + str(i))
```

4.. Check the number of completed jobs by inspecting the `job_controller_job_finished_total` metric and the job

### Anything else we need to know?

Yes, in the kube-controller-logs we find the following log lines which are related and probably indicate repeated updated which results in double counting.

```
E1005 07:37:12.511132       1 job_controller.go:545] syncing job: tracking status: removing uncounted pods from status: Operation cannot be fulfilled on jobs.batch "indexed-job": the object has been modified; please apply your changes to the latest version and try again
E1005 07:38:04.577649       1 job_controller.go:545] syncing job: tracking status: removing uncounted pods from status: Operation cannot be fulfilled on jobs.batch "indexed-job": the object has been modified; please apply your changes to the latest version and try again
```

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-09-01T23:30:43Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Reproducible with kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

It fixes the issue that finished jobs are occasionally double counted when the final job status update fails and
the main loop of the Job controller is repeated. This fix moves the update of the metric after the final job status update.

Note that, it is now possible that the metric can miss counting of a job finish if a controller crashes between the status
update and the record of the metric. However, this is less likely than the job status update fail, which can happen
due to a conflict.

#### Which issue(s) this PR fixes:

Fixes #112873

#### Does this PR introduce a user-facing change?

```release-note
Fix the occasional double-counting of the job_finished_total metric
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by mimowo** [comment]
This build shows a failure of the test:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112948/pull-kubernetes-e2e-kind/1579386748947927040
Note that, there is a difference between the test prepared for the review and the test used for reproduction - the test used for reproduction repeats the check many times to make a fail more likely.

File: pkg/controller/job/job_controller.go [hunk 1]
```diff
@@ -1613,6 +1621,13 @@ func countValidPodsWithFilter(job *batch.Job, pods []*v1.Pod, uncounted sets.Str
 	return result
 }
 
+func getCompletionMode(job *batch.Job) string {
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller.go:1624]: Add a comment that this is to be used as a metrics label value.

**Review by alculquicondor — COMMENTED** [review]
> I wasn't able to reproduce the issue in integration tests, as a conflict would not be triggered for the update operation
just by creating a job and marking it its pods as completed.

Did you try marking the pods as terminated in parallel?

It would be nice to cover this and other metrics in integration tests. But it can be handled in a follow up PR.

File: pkg/controller/job/job_controller.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/job/job_controller.go:1625]: Done

**Comment by mimowo** [comment]
> > I wasn't able to reproduce the issue in integration tests, as a conflict would not be triggered for the update operation
> > just by creating a job and marking it its pods as completed.
> 
> Did you try marking the pods as terminated in parallel?
> 
> It would be nice to cover this and other metrics in integration tests. But it can be handled in a follow up PR.

Actually, it turns out it can be reproduced with integration tests, not sure what I did wrong in the first attempt. Updated the PR.
When the new test fails it produces an error message like this (tested against the master version of job_controller):

`Unexepected metric delta for "job_finished_total" metric with labels map["completion_mode":"Indexed" "result":"succeeded"]. Got: 2, want: 1`

File: staging/src/k8s.io/component-base/metrics/testutil/metrics.go [hunk 2]
```diff
@@ -385,6 +385,19 @@ func GetGaugeMetricValue(m metrics.GaugeMetric) (float64, error) {
 	return metricProto.Gauge.GetValue(), nil
 }
 
+// GetCounterMetricValueWithLabels returns float64 value for the counter metric filtered by the label value mapping
+func GetCounterMetricValueWithLabels(counterVec *metrics.CounterVec, lvMap map[string]string) (float64, error) {
```
Comment (alculquicondor) [inline staging/src/k8s.io/component-base/metrics/testutil/metrics.go:389]: This doesn't need to be here. It can be on the `_test.go` file

File: staging/src/k8s.io/component-base/metrics/testutil/metrics.go [hunk 3]
```diff
@@ -385,6 +385,19 @@ func GetGaugeMetricValue(m metrics.GaugeMetric) (float64, error) {
...
+	counter, err := counterVec.GetMetricWith(lvMap)
```
Comment (alculquicondor) [inline staging/src/k8s.io/component-base/metrics/testutil/metrics.go:390]: you can use `counterVec.WithLabelValues` instead.

File: test/integration/job/job_test.go [hunk 4]
```diff
@@ -47,19 +47,167 @@ import (
...
+	"k8s.io/kubernetes/pkg/controller/job/metrics"
 	"k8s.io/kubernetes/pkg/features"
 	"k8s.io/kubernetes/test/integration/framework"
 	"k8s.io/utils/pointer"
 )
 
 const waitInterval = time.Second
 
+type metricLabelMapWithValue struct {
+	LabelsMap map[string]string
```
Comment (alculquicondor) [inline test/integration/job/job_test.go:67]: just `[]string` should be enough, but up to you.

File: test/integration/job/job_test.go [hunk 5]
```diff
@@ -47,19 +47,167 @@ import (
...
+	defer closeFn()
+	ctx, cancel := startJobControllerAndWaitForCaches(restConfig)
+	defer func() {
+		cancel()
+	}()
+
+	testCases := map[string]struct {
+		job                             *batchv1.Job
+		completionMode                  batchv1.CompletionMode
+		wantJobFinishedNumMetricValues  []metricLabelMapWithValue
```
Comment (alculquicondor) [inline test/integration/job/job_test.go:88]: why not just one?

```suggestion
		wantJobFinishedNumMetricValues  metricLabelMapWithValue
```

File: test/integration/job/job_test.go [hunk 6]
```diff
@@ -47,19 +47,167 @@ import (
...
+				}
+			}
+		})
+	}
+}
+
+func getCounterMetricValueForLabels(counterVec *basemetrics.CounterVec, metricLabelsToCompare []metricLabelMapWithValue) ([]metricLabelMapWithValue, error) {
+	result := make([]metricLabelMapWithValue, len(metricLabelsToCompare))
+	for i := range metricLabelsToCompare {
+		value, err := testutil.GetCounterMetricValueWithLabels(counterVec, metricLabelsToCompare[i].LabelsMap)
```
Comment (alculquicondor) [inline test/integration/job/job_test.go:199]:
```suggestion
		value := testutil.GetCounterMetricValue(counterVec.With(metricLabelsToCompare[i].LabelsMap))
```

File: test/integration/job/job_test.go [hunk 7]
```diff
@@ -47,19 +47,167 @@ import (
...
+					t.Errorf("Unexepected metric delta for %q metric with labels %q. Got: %v, want: %v", metrics.JobFinishedNum.Name, tc.wantJobFinishedNumMetricValues[i].LabelsMap, gotDelta, wantDelta)
+				}
+			}
+			for i := range tc.wantJobPodsFinishedMetricValues {
+				gotDelta := jobPodsFinishedAfter[i].Value - jobPodsFinishedBefore[i].Value
+				wantDelta := tc.wantJobPodsFinishedMetricValues[i].Value
+				if gotDelta != wantDelta {
+					t.Errorf("Unexepected metric delta for %q metric with labels %q. Got: %v, want: %v", metrics.JobPodsFinished.Name, tc.wantJobPodsFinishedMetricValues[i].LabelsMap, gotDelta, wantDelta)
+				}
+			}
```
Comment (alculquicondor) [inline test/integration/job/job_test.go:191]: can you replace these with cmp.Diff instead?

File: test/integration/job/job_test.go [hunk 8]
```diff
@@ -47,19 +47,167 @@ import (
...
+			validateJobPodsStatus(ctx, t, clientSet, jobObj, podsByStatus{
+				Active: int(*jobObj.Spec.Parallelism),
+				Ready:  pointer.Int32(0),
+			}, wFinalizers)
+			if err, _ := setJobPodsPhase(ctx, clientSet, jobObj, v1.PodSucceeded, int(*jobObj.Spec.Parallelism)); err != nil {
+				t.Fatalf("Failed setting phase %s on Job Pod: %v", v1.PodSucceeded, err)
+			}
+			validateJobSucceeded(ctx, t, clientSet, jobObj)
+
+			// record the metrics after the job is finished
```
Comment (alculquicondor) [inline test/integration/job/job_test.go:167]: You probably need to use `wait.Poll`, because it's not guaranteed that the metrics are updated right after the jobObj is up-to-date (the job sync could still be running)

File: staging/src/k8s.io/component-base/metrics/testutil/metrics.go (hunk 2 above)
Comment (mimowo) [reply staging/src/k8s.io/component-base/metrics/testutil/metrics.go]: Moved back to job_test.

File: staging/src/k8s.io/component-base/metrics/testutil/metrics.go (hunk 3 above)
Comment (mimowo) [reply staging/src/k8s.io/component-base/metrics/testutil/metrics.go]: Done

File: test/integration/job/job_test.go (hunk 4 above)
Comment (mimowo) [reply test/integration/job/job_test.go]: Adjusted to simplify as `[]string` is less repetitive.

File: test/integration/job/job_test.go (hunk 5 above)
Comment (mimowo) [reply test/integration/job/job_test.go]: Adjusted as job termination results in a metric bump for only one label combination.
For JobPodsFinished I prefer to keep a list as potentially the metric may be bumped both for failed and succeeded pods.

File: test/integration/job/job_test.go (hunk 6 above)
Comment (mimowo) [reply test/integration/job/job_test.go]: Simplified

File: test/integration/job/job_test.go (hunk 7 above)
Comment (mimowo) [reply test/integration/job/job_test.go]: Replaced

File: test/integration/job/job_test.go (hunk 8 above)
Comment (mimowo) [reply test/integration/job/job_test.go]: Indeed. I've never hit the issue until I injected a time.Sleep before recoring the metrics in job_controller. The test started to fail, so it could fail occasionally. Fixed.

File: test/integration/job/job_test.go [hunk 9]
```diff
@@ -47,19 +47,166 @@ import (
...
+	defer closeFn()
+	ctx, cancel := startJobControllerAndWaitForCaches(restConfig)
+	defer func() {
+		cancel()
+	}()
+
+	testCases := map[string]struct {
+		job                             *batchv1.Job
+		wantJobFinishedNumMetricDelta   metricLabelsWithValue
+		wantJobPodsFinishedMetricDeltas []metricLabelsWithValue
```
Comment (alculquicondor) [inline test/integration/job/job_test.go:88]: no test case has more than one delta, so why not just a single element?

File: test/integration/job/job_test.go [hunk 10]
```diff
@@ -47,19 +47,166 @@ import (
...
+	err := wait.PollImmediate(10*time.Millisecond, 10*time.Second, func() (bool, error) {
+		cmpErr = nil
+		metricValuesAfter, err := getCounterMetricValueForLabels(counterVer, wantMetricDeltas)
+		if err != nil {
+			return true, fmt.Errorf("Failed to collect the %q metric after the job is finished: %q", counterVer.Name, err)
+		}
+		for i := range wantMetricDeltas {
+			wantDelta := wantMetricDeltas[i].Value
+			gotDelta := metricValuesAfter[i].Value - metricValuesBefore[i].Value
+			if diff := cmp.Diff(wantDelta, gotDelta); diff != "" {
```
Comment (alculquicondor) [inline test/integration/job/job_test.go:180]: my suggestion is more like building an array of gotDelta, then do a single cmp.Diff with the `wantMetricDeltas`.

However, if you are going to get rid of the arrays altogether, that shouldn't be necessary.

File: test/integration/job/job_test.go (hunk 9 above)
Comment (mimowo) [reply test/integration/job/job_test.go]: I added originally a list cause I think it will be useful in the near future when it will be extending the metrics for pods - then a couple of label combinations might be bumped in a single sync. However, as you pointed out it is not needed for now, so let's complicate once needed.

**Review by alculquicondor — COMMENTED** [review]
Awesome
/lgtm
/approve

**Comment by mimowo** [comment]
Squashed changes

**Review by soltysh — APPROVED** [review]
/approve
