### PR TITLE
fix goroutine leaks in TestConfigurationChannels

### LINKED ISSUE #107089: goroutine leaks in TestConfigurationChannels
### What happened?

Two goroutines are leaked in [TestConfigurationChannels](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/config/config_test.go#L24-L34). 

The two goroutines are created inside function mux.Channel() ([line 77](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/config/config.go#L77)). They block at the range statement ([line 82](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/config/config.go#L82)) since the channel listenChannel is not closed in the unit test. 

However, wait.Until() is called with wait.NeverStop at line 77. Even though we close the channels returned by mux.Channel(), we still not resolve the leaked goroutines. 

### What did you expect to happen?

No goroutines are blocked when the test finishes. 

### How can we reproduce it (as minimally and precisely as possible)?

The bug can be easily reproduced by executing the unit test. 

### Anything else we need to know?

_No response_

### Kubernetes version

All recent versions (e.g., 00bbea47e85befa8bf90ac3e88e7bfa4f3886f88) have this problem. 

### Cloud provider

None

### OS version

_No response_

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by cyclinder**
Signed-off-by: cyclinder <qifeng.guo@daocloud.io>

#### What type of PR is this?

/kind bug
#### What this PR does / why we need it:
fix goroutine leaks in TestConfigurationChannels.
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/util/config/config_test.go#L24-L34
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/107089

#### Special notes for your reviewer:
We should consider whether it is appropriate to use wait.NeverStop here:
https://github.com/kubernetes/kubernetes/blob/13e97453f9024f347a40940f27630e62c4540fa5/pkg/util/config/config.go#L77
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/util/config/config.go [hunk 1]
```diff
@@ -74,7 +74,15 @@ func (m *Mux) Channel(source string) chan interface{} {
...
 	newChannel := make(chan interface{})
 	m.sources[source] = newChannel
-	go wait.Until(func() { m.listen(source, newChannel) }, 0, wait.NeverStop)
+
+	var stopCh <-chan struct{}
+	if len(stopChes) > 0 {
+		stopCh = stopChes[0]
+	} else {
+		stopCh = wait.NeverStop
+	}
```
Comment (ash2k) [inline pkg/util/config/config.go:83]: Rather than doing this for backwards compatibility, I wonder if it'd be cleaner to add a new method to the type. E.g. `ChannelWithContext(ctx context.Context, source string) chan interface{}`.

Comment (ash2k) [reply pkg/util/config/config.go:83]: Actually, this is not in library code (not in `staging`) so might just break the signature and update the callers.

Comment (cyclinder) [reply pkg/util/config/config.go:83]: hi @ash2k,  if we add a new method there, do we need to look at all callers?  If so, I would like the PR to add the new method and update `TestConfigurationChannels `. Then create a new PR to update all the callers. and decide whether they should call the new method or the old.

Comment (ash2k) [reply pkg/util/config/config.go:88]: I think we don't need yet another method, we can just change this one. The caller should always be responsible for stopping the goroutines they start, so a method without a way to stop them is a bad API. Hence, in my opinion, we should change this one rather just than adding a new one (change bad API to good API).

Comment (cyclinder) [reply pkg/util/config/config.go:88]: I found a lot of code in the kubelet that uses wait.NeverStop, which doesn't seem to care about stopping the goroutine. If we change this method to `ChannelWithContext(ctx context.Context, source string) chan interface`, we need to cancel this ctx somewhere uniformly, but I can't find the right place

**Comment by dims** [comment]
/assign @ash2k 

@ash2k please assign it back to me after you are happy with this

File: pkg/kubelet/config/config_test.go [hunk 2]
```diff
@@ -395,7 +433,10 @@ func TestPodUpdateAnnotations(t *testing.T) {
 }
 
 func TestPodUpdateLabels(t *testing.T) {
-	channel, ch, _ := createPodConfigTester(PodConfigNotificationIncremental)
+	ctx, cancel := context.WithCancel(context.TODO())
```
Comment (ash2k) [inline pkg/kubelet/config/config_test.go:436]: I think in tests here we can use `context.Background()` rather than `TODO()`?

File: pkg/util/config/config.go [hunk 3]
```diff
@@ -17,6 +17,7 @@ limitations under the License.
 package config
 
 import (
+	"golang.org/x/net/context"
```
Comment (ash2k) [inline pkg/util/config/config.go:20]:
```suggestion
	"context"
```

File: pkg/util/config/config.go (hunk 1 above)
Comment (ash2k) [reply pkg/util/config/config.go:69]: It's fine, we don't need to fix the world in this PR :)

File: pkg/util/config/config.go (hunk 3 above)
Comment (cyclinder) [reply pkg/util/config/config.go]: thanks, done

**Review by ash2k — APPROVED** [review]
/lgtm
/assign @dims

File: pkg/kubelet/kubelet.go [hunk 4]
```diff
@@ -271,22 +271,23 @@ func makePodSourceConfig(kubeCfg *kubeletconfiginternal.KubeletConfiguration, ku
 
 	// source of all configuration
 	cfg := config.NewPodConfig(config.PodConfigNotificationIncremental, kubeDeps.Recorder)
+	ctx := context.Background()
```
Comment (ash2k) [inline pkg/kubelet/kubelet.go:274]: Sorry, missed this one. It needs to be TODO so that it's replaced with a proper context in the future.
```suggestion
	ctx := context.TODO()
```
/remove lgtm

Comment (cyclinder) [reply pkg/kubelet/kubelet.go]: okay, I add a todo for it

**Comment by dims** [comment]
thanks @cyclinder and @ash2k. the unit test failure seems unrelated, right?

/approve

**Comment by cyclinder** [comment]
> thanks @cyclinder and @ash2k. the unit test failure seems unrelated, right?
> 
> /approve

yeah, retest was successful

**Comment by ash2k** [comment]
/lgtm

Thanks!
