### PR TITLE
Prevent Kubelet from getting stuck in DiskPressure when imagefs minReclaim is set

### LINKED ISSUE #99094: Kubelet stuck in DiskPressure when imagefs.minReclaim is set
##### Short version
When both `evictionSoft.imagefs.available` and `evictionMinReclaim.imagefs.available` parameters are set on Kubelet, they act as the upper and lower thresholds that define how the `DiskPressure` state is entered and exited. When trying to remediate a `DiskPressure`, Kubelet performs different operations to free up space. In order to decide if it has freed up enough, it compares the currently available disk space with the triggering threshold instead of the exiting threshold.

Kubelet ends up in a long lasting `DiskPressure` state which can only be left with Kubelet restart, or if by luck the Pods that were using disk space are rescheduled somewhere else.

##### Long version
Kubelet periodically does some housekeeping in order to ensure its node has enough resources available. If that isn’t the case, it tries to free up resources, updates the node’s condition (e.g. `DiskPressure`) and in last resort starts evicting Pods. By default, the housekeeping is done every 10 seconds for a set of “signals” which represent node level resources (e.g. `imagefs`, `nodefs`, `memory`, `pid`).

There are a couple of parameters that comes into play in this process and I'll ignore all but two for simplicity:
* *Signal thresholds*: defines at which point there is not enough of a resource available, e.g. `evictionSoft.imagefs.available`
* *Signal minimum reclaim*: how much resources Kubelet should aim to free up before a threshold is considered as not met. It’s the lower bound of an hysteresis, the threshold being the upper bound (e.g. `evictionMinReclaim.imagefs.available`)

The housekeeping is implemented in `eviction_manager.go func (m *managerImpl) synchronize()`

Here is my understanding of what this method does, filtering out what I think does matter in this issue:
1. Observe the signals (e.g. how much `imagefs` is available)
1. Compute a list of thresholds that are met (e.g. observed `imagefs.available` < `evictionSoft.imagefs.available`)
1. If there were thresholds met on a previous `synchronize()` run:
  a. Check if those previous threshold are still met taking the `minReclaim` into account. If `evictionSoft.imagefs.available` = 15% and `minReclaim = 10%`, our value to unmet the threshold is actually 25% percent `imagefs.available`
   b. Merge them with (2), the thresholds that are met from the new observation (1)
1. Filter out thresholds for which the individual grace period is not reached. They might be taken into account in another run if observed again.
1. Replace the previously met threshold with the new computed list of thresholds. Those met threshold are stored across runs.
1. If no threshold is not actually met, exits. If at least one is met, Kubelet has work to do!
Try to reclaim node level resources. In other terms, try to free up resources without having to evict any Pod. For `imagefs` that’s done by removing stopped containers, and unused images.
1. Make a new observation. If the threshold are not met anymore, ignoring `minReclaim`, exit with `eviction manager: able to reduce pressure without evicting pods.`
1. Evict Pods as last resort

Ignoring the `minReclaim` in (7) seems wrong. If the amount of resources freed is somewhere between `imagefs.available` and `imagefs.available+minReclaim`, Kubelet can get stuck. On the next `synchronize()` run, as part of (3a) the threshold taking `minReclaim` into account is not unmet. Therefore Kubelet tries again to free up node level resources in (6), eventually does nothing but exits (6) pretending it free up enough resources without doing anything.

[Taking minReclaim into account](https://github.com/openshift/origin/blob/e9f6f520e55ed5f257fdb3f44ce9bdcefda1ead8/vendor/k8s.io/kubernetes/pkg/kubelet/eviction/eviction_manager.go#L446) after having cleaned up the node and in order to decide if Pod eviction is the step, seems to do the trick.

#### What you expected to happen:
Kubelet should try to get out of a `DiskPressure` by evicting almost all Pods. In this case, it means it should try to evict Pods until the `minReclaim` threshold is reached and the `DiskPressure` can be removed. I expect Kubelet to stay in permanent `DiskPressure` only if the resources that are used are beyond its control.

#### How to reproduce it (as minimally and precisely as possible):

Preparation:
1. Choose a node with a `rootfs` different from `imagefs` (the problem might be the same when they are mixed but I didn't try)
1. Set `evictionMinReclaim.imagefs.available` to 15% and `evictionMinReclaim.imagefs.available` to 30% in the Kubelet’s configuration
1. Exec into a Pod running on that node, and use `dd` to write a file inside the container. The amount of data should be enough to bring the underlying `imagefs` disk at 86% usage
1. Wait for Kubelet to notice the threshold and to cleanup stopped containers and remove unused images
Remove your file. The node is now clean. Restart Kubelet and notice how it sees everything is normal

Getting Kubelet stuck:
1. Exec into your Pod and write a file to reach 86% `imagefs` usage again
1. Wait for Kubelet to notice, cleanup stopped containers and images. Since the cleanup was done in the preparation step a minute ago, there is almost nothing to be removed and your usage should stay more or less the same
1. Replace the Pod's file by a new one to reach between 55% and 85% disk usage. 
1. Observe how every 10 seconds, Kubelet pretends it was able to `reduce imagefs pressure without evicting pods`. 

The Node is stuck in `DiskPressure` until you restart Kubelet and it forgets it had to ensure there is at least `imagefs.available+minReclaim` available in `imagefs`.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.18.8
- Cloud provider or hardware configuration: vSphere
- OS (e.g: `cat /etc/os-release`): 18.04.2 LTS
- Kernel (e.g. `uname -a`): 4.15.0-130-generic

#### Final words
We have been running a slightly modified version of Kubelet on one of our clusters for the past 5 days, and since then we had no node staying in `DiskPressure` state for more than 20 minutes. From the disk usage graph, it looks like both image garbage collection and the disk pressure remedy operations are working properly. I'll open a PR with the little patch we're using.

### PR DESCRIPTION
**Pull request by maxlaverse**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
When trying to free up space in order to leave a DiskPressure, Kubelet does two consecutive actions:
1. Removing stopped containers and unused images
2. Evicting Pods

Between 1. and 2. there is an intermediate check to see if we're still under pressure. If we have free up enough disk space by cleaning up the node, there is no need to interrupt user workloads. The decision if enough disk space has been freed ignores the minimum amount of resource we aimed to free up.

This PR changes this behavior by taking it into account. Therefore, if 1. was not enough, Kubelet will start evicting Pods until it can leave the DiskPressure.

#### Which issue(s) this PR fixes:
Fixes #99094

#### Does this PR introduce a user-facing change?
```release-note
Prevent Kubelet stuck in DiskPressure when imagefs minReclaim is set 
```

### CODE REVIEW

**Comment by maxlaverse** [comment]
Tests are failing for a different reason. I'm giving it another try:
/test pull-kubernetes-e2e-kind

**Review by ehashman — CHANGES_REQUESTED** [review]
Hi @maxlaverse, can you please add a test for this? It's pretty puzzling that changing something from false to true would not cause any failures so it seems we're missing coverage.

**Comment by SergeyKanzhelev** [comment]
/assign @bobbypage

for resource management PR.

**Comment by maxlaverse** [comment]
Hey @bobbypage !
Kindly pinging you as I'm not sure if you're still waiting for a sign of me or just didn't have time to look up the PR yet.
I'm a bit confused by the Approval Notifier that says the PR is not approved, and later that it's approved by me.
I suppose yujuhong should only be assigned after you looked at the PR ?

File: pkg/kubelet/eviction/eviction_manager.go [hunk 1]
```diff
@@ -430,7 +430,7 @@ func (m *managerImpl) reclaimNodeLevelResources(signalToReclaim evictionapi.Sign
 		debugLogObservations("observations after resource reclaim", observations)
 
 		// determine the set of thresholds met independent of grace period
-		thresholds := thresholdsMet(m.config.Thresholds, observations, false)
+		thresholds := thresholdsMet(m.config.Thresholds, observations, true)
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/eviction/eviction_manager.go:433]: I think this change (`true` -> `false`) was introduced here: https://github.com/kubernetes/kubernetes/pull/59841/

It may have been the copy/paste error from this line (to include the call debug method):
https://github.com/kubernetes/kubernetes/blob/d7355278b34f1eb83ae537506de3a816ac925226/pkg/kubelet/eviction/eviction_manager.go#L272 or intentional. As part of that PR, the comment about the min reclaim was removed:

> `// evaluate all current thresholds to see if with adjusted observations, we think we have met min reclaim goals`

Can you please review the mentioned PR and check if any of bugs fixed in that one may come back. If everything is OK, can you please add the comment about min reclaim back.

(looking at code it feels that this is the right change. Cancelling lgtm to make sure that due diligence is made on the change source)

/lgtm cancel

CC: @dashpole

Comment (dashpole) [reply pkg/kubelet/eviction/eviction_manager.go:433]: This change also looks correct to me.  I can't think of why I would have intentionally changed that.

Comment (SergeyKanzhelev) [reply pkg/kubelet/eviction/eviction_manager.go:433]: /lgtm

Comment (maxlaverse) [reply pkg/kubelet/eviction/eviction_manager.go:434]: > It may have been the copy/paste error from this line 

That's a pretty good theory. I couldn't understand why the grace period was mentioned in this context. I adapted the corresponding comment accordingly.

I read PR [#59841](https://github.com/kubernetes/kubernetes/pull/59841) and its two referenced issues:
* [#46789](https://github.com/kubernetes/kubernetes/issues/46789): Kubelet was not taking into account the amount of disk space freed by container garbage collection when doing the intermediary check, which could lead to unnecessary evictions
* [#56573](https://github.com/kubernetes/kubernetes/issues/56573): Kubelet was not taking into account the amount of inodes freed by garbage collection when doing the intermediary check, which could lead to unnecessary evictions

Both are still solved by [#59841](https://github.com/kubernetes/kubernetes/pull/59841) which brings a more reliable way to measure how much Kubelet freed/have during this intermediary check, by doing a new observation. I went down the rabbit hole and followed a couple more issues and PRs. I should probably have stopped on the way since you added the lgtm label, and I realize @dashpole was involved in everything I read.

I understand the overall sequences of changes that led to where the code is today and I really think this boolean value is just a mistake.

**Review by mrunalp — APPROVED** [review]
