### PR TITLE
test/e2e/storage: fix output in case of failure and use another NFS mount option

### LINKED ISSUE #70239: [sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (default fs)] provisioning should provision storage with mount options failing on Fedora/RHEL and CRI-O
**Which jobs are failing**:

CRI-O job in our CI using kubernetes master tests

**Which test(s) are failing**:

[sig-storage] In-tree Volumes [Driver: nfs] [Testpattern: Dynamic PV (default fs)] provisioning should provision storage with mount options

**Since when has it been failing**:

since this PR has been merged: https://github.com/kubernetes/kubernetes/pull/69441

**Testgrid link**:

link to our job is here:

https://openshift-gce-devel.appspot.com/build/origin-federated-results/pr-logs/pull/kubernetes-sigs_cri-o/1870/test_pull_request_crio_e2e_fedora/1368/
https://openshift-gce-devel.appspot.com/build/origin-federated-results/pr-logs/pull/kubernetes-sigs_cri-o/1874/test_pull_request_crio_e2e_fedora/1380/
https://openshift-gce-devel.appspot.com/build/origin-federated-results/pr-logs/pull/kubernetes-sigs_cri-o/1874/test_pull_request_crio_e2e_rhel/1557/

**Reason for failure**:

we don't know the reason of the failure but it doesn't seem related to CRI-O. It's constantly reproducible also.

**Anything else we need to know**:

/cc @jberkus @mkimuram @msau42

/kind failing-test

### PR DESCRIPTION
**Pull request by runcom**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

- provide a command to output useful outputs when debugging a failing test
- use `relatime` instead of `nosuid` when checking nfs supported options (it fails on rhel/fedora otherwise)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #70239

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by runcom** [comment]
@msau42 @mkimuram @wongma7 @mrunalp PTAL

**Comment by mrunalp** [comment]
:+1:
cc: @smarterclayton

**Comment by runcom** [comment]
@mkimuram looks like `relatime` isn't on gce either, any chance that using just `proto=tcp` would still verify the test?

**Comment by runcom** [comment]
@mkimuram I've removed `relatime` waiting for your confirmation to see if it passes w/o nothing and verify the test

**Comment by mkimuram** [comment]
@runcom 

> I've removed relatime waiting for your confirmation to see if it passes w/o nothing and verify the test

This test should be still valid with one option, so just removing ```nosuid``` looks good to me.

**Comment by runcom** [comment]
Awesome, removed then, this should be good

File: test/e2e/storage/testsuites/provisioning.go [hunk 1]
```diff
@@ -279,6 +279,7 @@ func TestDynamicProvisioning(t StorageClassTest, client clientset.Interface, cla
 			// Get entry, get mount options at 6th word, replace brackets with commas
 			command += fmt.Sprintf(" && ( mount | grep 'on /mnt/test' | awk '{print $6}' | sed 's/^(/,/; s/)$/,/' | grep -q ,%s, )", option)
 		}
+		command += " || mount | grep 'on /mnt/test'; false"
```
Comment (mkimuram) [inline test/e2e/storage/testsuites/provisioning.go]: @runcom 

Shouldn't it be like below?

```
command += " || (mount | grep 'on /mnt/test'; false)"
```

Because it works as below:

```
$ true || echo false; false
$ echo $?
1
$ true || (echo false; false)
$ echo $?
0
$ false || (echo false; false)
false
$ echo $?
1
```

Also, if it works well, it would be better to try ```relatime```again.

Comment (runcom) [reply test/e2e/storage/testsuites/provisioning.go]: Good point, changing it again

**Comment by mkimuram** [comment]
@mrunalp 

It seems that all the tests have passed. And the code looks good to me. Could you lgtm, again?
