### PR TITLE
Remove checks for pods responding in deployment e2e tests

### LINKED ISSUE #39879: [k8s.io] Deployment deployment should support rollover {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-gke-release-1.5/3341/
Failed: [k8s.io] Deployment deployment should support rollover {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:77
Expected error:
    <*errors.errorString | 0xc420d3d760>: {
        s: "error waiting for deployment \"test-rollover-deployment\" status to match expectation: timed out waiting for the condition",
    }
    error waiting for deployment "test-rollover-deployment" status to match expectation: timed out waiting for the condition
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:598
```

Previous issues for this test: #26509 #26834 #29780 #35355

### PR DESCRIPTION
**Pull request by janetkuo**
Fixes #39879

Remove it because it caused deployment e2e tests sometimes timed out waiting for pods responding, and pods responding isn't related to deployment controller and is not a prerequisite of deployment e2e tests.

@kargakis

### CODE REVIEW

**Comment by kargakis** [comment]
Are these timeouts due to slow pulls?

**Comment by janetkuo** [comment]
@kargakis no, pods are already running.

**Comment by janetkuo** [comment]
> Are these timeouts due to slow pulls?

I believe not. The image `gcr.io/google_containers/nginx-slim:0.7` should already be pre-pulled.

**Comment by janetkuo** [comment]
I noticed that in one of the failed rollover test, we first create an RS with replicas=4 and wait for 5 mins for all pods to be running. Then it timed out because one of the pods (the last replica created) is pending. Can we mitigate flakiness by reducing the number of replicas? We always wait for 5 mins regardless of how many replicas there are.

**Comment by kargakis** [comment]
Agreed. Unless we are doing some sort of stress-testing the less replicas
these tests are using the better.

**Comment by janetkuo** [comment]
> the less replicas these tests are using the better.
Added 2nd commit for that

**Comment by fejta** [comment]
Janet and/or Michail will you please add yourself as approvers to OWNERS file?

We do not need to drag down your productivity by waiting for me to approve your PRs.

**Comment by janetkuo** [comment]
Filed #40957

**Comment by fejta** [comment]
Thanks!
/approve

File: test/e2e/deployment.go [hunk 1]
```diff
@@ -289,7 +289,7 @@ func testRollingUpdateDeployment(f *framework.Framework) {
 	_, err := c.Extensions().ReplicaSets(ns).Create(rs)
 	Expect(err).NotTo(HaveOccurred())
 	// Verify that the required pods have come up.
-	err = framework.VerifyPods(c, ns, "sample-pod", false, 3)
+	err = framework.VerifyPodsRunning(c, ns, "sample-pod", false, 3)
```
Comment (kargakis) [inline test/e2e/deployment.go]: Can use 1 replica

File: test/e2e/deployment.go [hunk 2]
```diff
@@ -458,7 +458,7 @@ func testRolloverDeployment(f *framework.Framework) {
 	// Create a deployment to delete nginx pods and instead bring up redis-slave pods.
 	// We use a nonexistent image here, so that we make sure it won't finish
 	deploymentName, deploymentImageName := "test-rollover-deployment", "redis-slave"
-	deploymentReplicas := int32(4)
+	deploymentReplicas := int32(3)
```
Comment (kargakis) [inline test/e2e/deployment.go]: Switch maxUnavailable to 0 and this to 1?

**Comment by kargakis** [comment]
A couple of comments - mind opening a follow-up issue and sweep the tests to reduce the replicas used wherever possible?

**Comment by kargakis** [comment]
A couple of comments - mind opening a follow-up issue to sweep the tests to reduce the replicas used wherever possible?

**Comment by kargakis** [comment]
Feel free to apply lgtm once you address the remaining comments

File: test/e2e/deployment.go (hunk 1 above)
Comment (janetkuo) [inline test/e2e/deployment.go]: Done

File: test/e2e/deployment.go (hunk 2 above)
Comment (janetkuo) [inline test/e2e/deployment.go]: Can't do this, since rollover test requires at least 3 replicas: it creates an RS first, then create a deployment that creates another RS, and then before the rolling update finishes, update deployment to create the third RS to rollover the first two versions

**Comment by janetkuo** [comment]
Addressed comments, applying tag

File: test/e2e/deployment.go (hunk 2 above)
Comment (kargakis) [inline test/e2e/deployment.go]: - RS-1 has one healthy replica
- D with maxUnavailable=0 creates RS-2 withone unhealthy replica. It shouldn't scale down RS-1 otherwise it violates availability.
- D is updated. RS-3 is scaled up to one. POD-3 becomes healthy, RS-2 and RS-1 are scaled down

Seems doable.

**Comment by kargakis** [comment]
@janetkuo looking at http://storage.googleapis.com/kubernetes-test-history/static/index.html apart from [1] all the other deployment-related tests seem to flake on "failed to wait for pods running" so this PR won't add much I think (we still check for running pods as before). I think there is more value in decreasing the number of replicas to the minimum possible for every test: https://github.com/kubernetes/kubernetes/issues/41063 and even more identify why 5m timeouts are not enough now. 

[1] [k8s.io] Deployment lack of progress should be reported in the deployment status

**Comment by janetkuo** [comment]
> identify why 5m timeouts are not enough now

It's likely caused by watch.Until being broken, filed #41112
