### PR TITLE
Be sure to update the status of StatefulSet even if the new replica creation fails

### LINKED ISSUE #108837: ReadyReplicas of StatefuleSetStatus is wrong when failed to create stateful pod
### What happened?

I create a ResourceQuota with two pods limit in my `test` namespace.
```
root@k8s-local-control-plane:/# kubectl get resourceQuota -n test -o wide
NAME       AGE   REQUEST     LIMIT
pods-two   67m   pods: 0/2
```
Then, I create a statefuleSet `busybox` with 3 replicas. As  expected, two pods are created  successfully, and the third pod failed to create.
```
root@k8s-local-control-plane:/# kubectl get po -n test
NAME        READY   STATUS    RESTARTS   AGE
busybox-0   1/1     Running   0          3m9s
busybox-1   1/1     Running   0          3m5s
```
But, the ReadyReplicas is not 2 ,but 1.
```
root@k8s-local-control-plane:/# kubectl get sts -o wide -n test
NAME      READY   AGE     CONTAINERS   IMAGES
busybox   1/3     4m53s   busybox      busybox:latest
root@k8s-local-control-plane:/# kubectl get sts busybox -n test -o=jsonpath="{.status.readyReplicas}"
1
```

### What did you expect to happen?

The ReadyReplicas is correct

### How can we reproduce it (as minimally and precisely as possible)?

1、Create a ResourceQuota with two pods limit in  a new namespace.
2、Create a statefulSet with 3 replicas 
3、Check if the ReadyReplicas of statefulSet matchs the number of stateful running pods.

### Anything else we need to know?

https://github.com/kubernetes/kubernetes/blob/816c97ab8cff8a1c72eccca1026f7820e93e0d25/pkg/controller/statefulset/stateful_set_control.go#L106-L114
1、According to the logic of the statefulSet controller, new pod created in current sync is not be immediately counted into the ReadyReplicas.
2、Failure to create pod will cause `updateStatefulSet` to return error,  then skip updating status.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-26T08:02:07Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-26T08:02:07Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>
kind v1.23.3
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by RyanAoh**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Be sure to update the status of StatefulSet even if the new replica creation fails

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kubernetes/issues/108837

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

File: pkg/controller/statefulset/stateful_set_control.go [hunk 1]
```diff
@@ -340,6 +330,20 @@ func (ssc *defaultStatefulSetControl) updateStatefulSet(
 		// If the ordinal could not be parsed (ord < 0), ignore the Pod.
 	}
 
+	// make sure to update the latest status even if there is an error later
+	defer func() {
+		// update the set's status
+		updateErr := ssc.updateStatefulSetStatus(ctx, set, &status)
+		if updateErr != nil && err == nil {
+			err = updateErr
```
Comment (alculquicondor) [inline pkg/controller/statefulset/stateful_set_control.go:338]: I'm not sure this variable `err` is capturing all the errors.

For example, line 428 instantiates a new variable.

I think the best way to capture the returning error is to name the return values in line 267.

**Review by gjkim42 — COMMENTED** [review]
Maybe I am wrong but... I think this may not be a safe approach.
This may override the previous complete status with the latest incomplete status.

**Comment by alculquicondor** [comment]
Define complete. Some pods could have been added or removed, so the old status is no longer accurate.

File: pkg/controller/statefulset/stateful_set_control.go (hunk 1 above)
Comment (alculquicondor) [reply pkg/controller/statefulset/stateful_set_control.go:338]: Are you sure this is the right variable? Line 269 might be covering it up.

Comment (RyanAoh) [reply pkg/controller/statefulset/stateful_set_control.go]: Hmm...I'm not really sure. It's ok in my tests. But it's definitely better to name it  another value.  I've change the code.

File: test/e2e/apps/statefulset.go [hunk 2]
```diff
@@ -20,6 +20,7 @@ import (
 	"context"
 	"encoding/json"
 	"fmt"
+	"k8s.io/apimachinery/pkg/api/resource"
```
Comment (alculquicondor) [inline test/e2e/apps/statefulset.go:23]: wrong import block

File: test/e2e/apps/statefulset.go [hunk 3]
```diff
@@ -1345,6 +1346,43 @@ var _ = SIGDescribe("StatefulSet", func() {
 			framework.ExpectNoError(err)
 		})
 	})
+
+	// add for issue: https://github.com/kubernetes/kubernetes/issues/108837
+	ginkgo.It("Be sure to update the status even if the new pod creation fails", func() {
```
Comment (alculquicondor) [inline test/e2e/apps/statefulset.go:1351]: Can you test this in integration tests instead of e2e? just because they are faster to run.

Comment (RyanAoh) [reply test/e2e/apps/statefulset.go]: I have updated the code to test it in integration tests. Please take a look. Thanks.

File: test/integration/statefulset/statefulset_test.go [hunk 4]
```diff
@@ -349,3 +362,111 @@ func setPodsReadyCondition(t *testing.T, clientSet clientset.Interface, pods *v1
 		t.Fatalf("failed to mark all StatefulSet pods to ready: %v", err)
 	}
 }
+
+// add for issue: https://github.com/kubernetes/kubernetes/issues/108837
+func TestStatefulSetStatusWithPodFail(t *testing.T) {
+	// Set up an API server
+	h := &framework.APIServerHolder{Initialized: make(chan struct{})}
+	s := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
+		<-h.Initialized
```
Comment (alculquicondor) [inline test/integration/statefulset/statefulset_test.go:371]: Why do you need this handler?

An alternative approach might be to just fail pod creations here. You could count how many of the pod creation requests are successful, and return failures after a threshold is reached.

Then you don't need all this quota controllers setup.

Comment (RyanAoh) [reply test/integration/statefulset/statefulset_test.go]: > An alternative approach might be to just fail pod creations here. You could count how many of the pod creation requests are successful, and return failures after a threshold is reached.

Thanks for your advice. I added an admission control to fail the pod creation.

File: pkg/controller/statefulset/stateful_set_control.go [hunk 5]
```diff
@@ -340,6 +330,23 @@ func (ssc *defaultStatefulSetControl) updateStatefulSet(
...
+		if statusErr == nil {
+			klog.V(4).InfoS("StatefulSet pod status", "statefulSet", klog.KObj(set),
+				"replicas", status.Replicas,
+				"readyReplicas", status.ReadyReplicas,
+				"currentReplicas", status.CurrentReplicas,
+				"updatedReplicas", status.UpdatedReplicas)
+		} else if updateErr == nil {
+			updateErr = statusErr
+		} else {
+			klog.Warningf("update status for statefulSet %v error: %s", klog.KObj(set), statusErr)
```
Comment (alculquicondor) [inline pkg/controller/statefulset/stateful_set_control.go:346]: Oops, just saw this now.

We discourage Warningf now: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#change-log-functions

File: pkg/controller/statefulset/stateful_set_control.go [hunk 6]
```diff
@@ -340,6 +330,23 @@ func (ssc *defaultStatefulSetControl) updateStatefulSet(
 		// If the ordinal could not be parsed (ord < 0), ignore the Pod.
 	}
 
+	// make sure to update the latest status even if there is an error later
+	defer func() {
+		// update the set's status
+		statusErr := ssc.updateStatefulSetStatus(ctx, set, &status)
+		if statusErr == nil {
+			klog.V(4).InfoS("StatefulSet pod status", "statefulSet", klog.KObj(set),
```
Comment (alculquicondor) [inline pkg/controller/statefulset/stateful_set_control.go:338]: Use active voice https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#change-log-functions

File: test/integration/statefulset/statefulset_test.go [hunk 7]
```diff
@@ -349,3 +352,50 @@ func setPodsReadyCondition(t *testing.T, clientSet clientset.Interface, pods *v1
...
+	)
+
+	ns := framework.CreateTestingNamespace("test-pod-fail", s, t)
+	defer framework.DeleteTestingNamespace(ns, s, t)
+
+	stopCh := runControllerAndInformers(ssc, informers)
+	defer close(stopCh)
+
+	sts := newSTS("sts", ns.Name, 4)
+	stss, _ := createSTSsPods(t, c, []*appsv1.StatefulSet{sts}, []*v1.Pod{})
```
Comment (alculquicondor) [inline test/integration/statefulset/statefulset_test.go:389]: Just call the client directly? We aren't benefiting much from this function.

File: test/integration/statefulset/statefulset_test.go [hunk 8]
```diff
@@ -349,3 +352,50 @@ func setPodsReadyCondition(t *testing.T, clientSet clientset.Interface, pods *v1
...
+	sts = stss[0]
+
+	if err := wait.PollImmediate(pollInterval, pollTimeout, func() (bool, error) {
+		newSTS, err := c.AppsV1().StatefulSets(sts.Namespace).Get(context.TODO(), sts.Name, metav1.GetOptions{})
+		if err != nil {
+			return false, err
+		}
+		return newSTS.Status.Replicas == int32(limitedPodNumber), nil
+	}); err != nil {
+		t.Fatalf("failed to verify .Status.Replicas is equal to expected replicas for sts %s: %v", sts.Name, err)
```
Comment (alculquicondor) [inline test/integration/statefulset/statefulset_test.go:399]: It would be useful to know what was the latest reported number.

File: pkg/controller/statefulset/stateful_set_control.go [hunk 9]
```diff
@@ -340,6 +330,23 @@ func (ssc *defaultStatefulSetControl) updateStatefulSet(
...
+		if statusErr == nil {
+			klog.V(4).InfoS("Updated status", "statefulSet", klog.KObj(set),
+				"replicas", status.Replicas,
+				"readyReplicas", status.ReadyReplicas,
+				"currentReplicas", status.CurrentReplicas,
+				"updatedReplicas", status.UpdatedReplicas)
+		} else if updateErr == nil {
+			updateErr = statusErr
+		} else {
+			klog.V(4).InfoS("Updated status error", "statefulSet", klog.KObj(set), "err", statusErr)
```
Comment (alculquicondor) [inline pkg/controller/statefulset/stateful_set_control.go:346]:
```suggestion
			klog.V(4).InfoS("Could not update status", "statefulSet", klog.KObj(set), "err", statusErr)
```

File: test/integration/statefulset/statefulset_test.go [hunk 10]
```diff
@@ -349,3 +352,57 @@ func setPodsReadyCondition(t *testing.T, clientSet clientset.Interface, pods *v1
...
+
+	ctx, cancel := context.WithCancel(context.Background())
+	defer cancel()
+	informers.Start(ctx.Done())
+	go ssc.Run(ctx, 5)
+
+	sts := newSTS("sts", ns.Name, 4)
+	_, err = c.AppsV1().StatefulSets(sts.Namespace).Create(context.TODO(), sts, metav1.CreateOptions{})
+	if err != nil {
+		t.Fatalf("Created statefuleSet %s error: %v", sts.Name, err)
```
Comment (alculquicondor) [inline test/integration/statefulset/statefulset_test.go:393]:
```suggestion
		t.Fatalf(Could not create statefuleSet %s: %v", sts.Name, err)
```

File: test/integration/statefulset/statefulset_test.go [hunk 11]
```diff
@@ -349,3 +352,57 @@ func setPodsReadyCondition(t *testing.T, clientSet clientset.Interface, pods *v1
...
+	controlPlaneConfig.GenericConfig.AdmissionControl = &fakePodFailAdmission{
+		limitedPodNumber: limitedPodNumber,
+	}
+	_, s, closeFn := framework.RunAnAPIServer(controlPlaneConfig)
+	defer closeFn()
+
+	config := restclient.Config{Host: s.URL}
+	c, err := clientset.NewForConfig(&config)
+	if err != nil {
+		t.Fatalf("Created clientset error: %v", err)
```
Comment (alculquicondor) [inline test/integration/statefulset/statefulset_test.go:369]:
```suggestion
		t.Fatalf("Could not create clientset: %v", err)
```

File: test/integration/statefulset/statefulset_test.go [hunk 12]
```diff
@@ -349,3 +352,57 @@ func setPodsReadyCondition(t *testing.T, clientSet clientset.Interface, pods *v1
...
+	var currentReplicas int32
+	if err := wait.PollImmediate(pollInterval, pollTimeout, func() (bool, error) {
+		newSTS, err := c.AppsV1().StatefulSets(sts.Namespace).Get(context.TODO(), sts.Name, metav1.GetOptions{})
+		if err != nil {
+			return false, err
+		}
+		currentReplicas = newSTS.Status.Replicas
+		return newSTS.Status.Replicas == int32(expectedReplicas), nil
+	}); err != nil {
+		t.Fatalf("Verify status for statefuleSet %s error: %v, current replicas: %d, excepted replicas: %d", sts.Name, err, currentReplicas, expectedReplicas)
```
Comment (alculquicondor) [inline test/integration/statefulset/statefulset_test.go:406]:
```suggestion
		t.Errorf("StatefulSet status has %d replicas, want replicas %d: %v", sts.Name, gotReplicas, wantReplicas, err)
```

**Review by alculquicondor — COMMENTED** [review]
/lgtm

**Review by janetkuo — APPROVED** [review]

File: pkg/controller/statefulset/stateful_set_control.go [hunk 13]
```diff
@@ -340,6 +330,23 @@ func (ssc *defaultStatefulSetControl) updateStatefulSet(
 		// If the ordinal could not be parsed (ord < 0), ignore the Pod.
 	}
 
+	// make sure to update the latest status even if there is an error later
+	defer func() {
```
Comment (soltysh) [inline pkg/controller/statefulset/stateful_set_control.go:334]: I have similar concerns wrt this approach outlined here: https://github.com/kubernetes/kubernetes/pull/112127#discussion_r979925952 before we start any backports I'd prefer we fix it the right way.
