### PR TITLE
Fix initializer_manager_test.go flake

### LINKED ISSUE #46631: [flake] pkg/kubeapiserver/admission/configuration TestConfiguration
Found in https://github.com/kubernetes/kubernetes/pull/46489

```
initializer_manager_test.go:110: case number of failures exceeds failureThreshold, but then get another success, expect ready, got: configuration is not ready
```

I can reproduce locally using golang.org/x/tools/cmd/stress

```
$ go test -i -o configuration.test k8s.io/kubernetes/pkg/kubeapiserver/admission/configuration
$ stress ./configuration.test -test.run TestConfiguration$

/tmp/go-stress979497321
--- FAIL: TestConfiguration (0.02s)
	initializer_manager_test.go:110: case number of failures exceeds failureThreshold, but then get another success, expect ready, got: configuration is not ready
FAIL


ERROR: exit status 1

202 runs so far, 1 failures
```

### PR DESCRIPTION
**Pull request by caesarxuchao**
Fixes https://github.com/kubernetes/kubernetes/issues/46631.

I reproduced the flake after 98 runs.

With the fix, it's not flaky in 1000 runs.

### CODE REVIEW

File: pkg/kubeapiserver/admission/configuration/initializer_manager_test.go [hunk 1]
```diff
@@ -105,6 +105,8 @@ func TestConfiguration(t *testing.T) {
 		manager.interval = 1 * time.Millisecond
 		manager.Run(mock.stopCh)
 		<-mock.stopCh
+		// sleep for another two intervals to give the manager enough time to digest the result returned by mock.
+		time.Sleep(2 * manager.interval)
```
Comment (lavalamp) [inline pkg/kubeapiserver/admission/configuration/initializer_manager_test.go]: This is not a good way to fix a flake. Maybe instead of letting the manager run, just call its sync method or whatever manually.

**Comment by lavalamp** [comment]
/lgtm
/approve

Thanks, much better!

**Comment by caesarxuchao** [comment]
@k8s-bot pull-kubernetes-e2e-gce-etcd3 test this

**Comment by caesarxuchao** [comment]
i'll add a priority label since it's fixing a flaky test.

**Comment by caesarxuchao** [comment]
@foxish do you know what priority label i should put on this flake fixing PR to let submit queue merge it quicker?

**Comment by smarterclayton** [comment]
@kubernetes/sig-testing-bugs did we drop the priority for flakes that are blocking the queue for it to move to the top of the queue?  This issue caused the last batch to flake, but we don't how to bump it.

**Comment by smarterclayton** [comment]
@k8s-oncall ^

**Comment by caesarxuchao** [comment]
@kubernetes/kubernetes-build-cops

**Comment by foxish** [comment]
Added queue/critical-fix to bump this up. Description of each label is in https://submit-queue.k8s.io/#/info

**Comment by smarterclayton** [comment]
Thanks, I never saw an update to the mar 21 discussion that said the old
labels don't work.  Do you mind reminding folks of this on kubernetes-dev?

On Fri, Jun 2, 2017 at 4:46 PM, Anirudh Ramanathan <notifications@github.com
