### PR TITLE
e2e: Wait for kube-root-ca.crt to be created

### LINKED ISSUE #107762: e2e test should wait for kube-root-ca.crt to be created in the namespace
> I did a trivial pass on 1.20 -> 1.23 e2e serial runs in openshift ci environments, and while I see the failed mount errors during test pod creation, all of them seemed to be associated with races between the test creating the secret/config map and the pod getting created (i.e. some background controller creates the items, the kubelet gets the pod before the background controller can create the object).  These were serial jobs, so the kubelet is fairly lightly loaded.
> 
> Comparing to the parallel tests which run more hot (cpu is typically maxed on workers or close to it), I still don't see any obvious inexplicable FailedMount errors - instead I see the more explicable ones which are related to e2e tests apparently not waiting for kube-root-ca.crt to be created in the namespace.  I'll separate that out into a different issue since it's more of a noise in e2e (reducing my ability to spot true failures).  If we got a fix for that it would likely improve the ability to spot this in ci clusters.
> 
> So at least from a scan of CI runs, I don't see strong evidence of this being triggered by our e2e tests in dense clusters.  Which means that its frequency is low and/or the scenario that triggers it isn't exercised by the kube e2e suite.
> 
> Absent an obvious reproducer, I'll poke at the code next.

_Originally posted by @smarterclayton in https://github.com/kubernetes/kubernetes/issues/105204#issuecomment-1021463140_

### PR DESCRIPTION
**Pull request by smarterclayton**
The change from service account secrets to projected tokens and the new dependency on kube-root-ca.crt to start pods with those projected tokens means that e2e tests can start before kube-root-ca.crt is created in a namespace. Wait for the default service account AND the kube-root-ca.crt configmap in normal e2e tests.

Also, it makes the wait for default service account secret EXPLICITLY check that it is the secret we expect, since anyone who automatically creates extra service account tokens in all namespaces could cause the wait to go too early.

We should have fixed this when we started adding kube-root-ca.crt, but a lot of these races are subtle flakes that don't pop up until long after or when we go log diving.

#### What type of PR is this?
/kind bug
/kind flake

#### Which issue(s) this PR fixes:

Fixes #107762

#### Does this PR introduce a user-facing change?

```release-note
e2e tests wait for kube-root-ca.crt to be populated in namespaces for use with projected service account tokens, reducing delays starting those test pods and errors in the logs.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
Clayton if you can add the Fixes: https://github.com/kubernetes/kubernetes/issues/107762  it can autoclose it :)

File: test/e2e/framework/util.go [hunk 1]
```diff
@@ -1243,53 +1263,50 @@ func RunCmdEnv(env []string, command string, args ...string) (string, string, er
...
-	for _, subset := range eps.Subsets {
-		for _, address := range subset.Addresses {
-			if address.IP != "" {
-				internalIPs = append(internalIPs, address.IP)
-			}
-		}
+	if len(eps.Subsets) != 1 || len(eps.Subsets[0].Addresses) != 1 {
+		Failf("There are more than 1 endpoints for kubernetes service: %+v", eps)
 	}
+	internalIP = eps.Subsets[0].Addresses[0].IP
```
Comment (aojea) [inline test/e2e/framework/util.go:1285]: ?? 
there can be multiple endpoints

Comment (smarterclayton) [reply test/e2e/framework/util.go:1285]: This is a bad merge from a branch, i'm fixing it.

Comment (aojea) [reply test/e2e/framework/util.go]: :smile:

File: test/e2e/framework/util.go [hunk 2]
```diff
@@ -321,6 +347,13 @@ func WaitForDefaultServiceAccountInNamespace(c clientset.Interface, namespace st
 	return waitForServiceAccountInNamespace(c, namespace, "default", ServiceAccountProvisionTimeout)
 }
 
+// WaitForDefaultServiceAccountInNamespace waits for the default service account to be provisioned
+// the default service account is what is associated with pods when they do not specify a service account
+// as a result, pods are not able to be provisioned in a namespace until the service account is provisioned
```
Comment (aojea) [inline test/e2e/framework/util.go:358]: copy paste issue

Comment (aojea) [reply test/e2e/framework/util.go:358]: you carried the comment from the other function to the new one

Comment (aojea) [reply test/e2e/framework/util.go:358]:
```suggestion
// WaitForKubeRootCAInNamespace waits for the kube-root-ca.crt configmap to be created in the namespace
```

File: test/e2e/framework/util.go [hunk 3]
```diff
@@ -296,31 +322,44 @@ func waitForServiceAccountInNamespace(c clientset.Interface, ns, serviceAccountN
 	}
 	ctx, cancel := watchtools.ContextWithOptionalTimeout(context.Background(), timeout)
 	defer cancel()
-	_, err := watchtools.UntilWithSync(ctx, lw, &v1.ServiceAccount{}, nil, serviceAccountHasSecrets)
```
Comment (liggitt) [inline test/e2e/framework/util.go:299]: now that admission no longer uses this, we should drop this wait entirely

Comment (smarterclayton) [reply test/e2e/framework/util.go:299]: I need to check whether anyone depends on the token or has an explicit wait then.

Comment (smarterclayton) [reply test/e2e/framework/util.go:299]: Looks like no one explicitly tries to read the default token in core e2e.

**Comment by smarterclayton** [comment]
/retest

Not certain failure is related, but think not.

**Comment by aojea** [comment]
if we really know or want to set the maximum time allowed to get the configmap configured we should add a specific test for that:

1. create X namespaces
2. measure the time to have the configmap with the root-ca in each namespace
3. check percentiles are below threshold or fail

I think that @wojtek-t have something similar for pods startup on sig-scalability

File: test/e2e/framework/framework.go [hunk 4]
```diff
@@ -248,6 +248,9 @@ func (f *Framework) BeforeEach() {
 			ginkgo.By("Waiting for a default service account to be provisioned in namespace")
 			err = WaitForDefaultServiceAccountInNamespace(f.ClientSet, namespace.Name)
 			ExpectNoError(err)
+			ginkgo.By("Waiting for kube-root-ca.crt to be provisioned in namespace")
+			err = WaitForKubeRootCAInNamespace(f.ClientSet, namespace.Name)
+			ExpectNoError(err)
```
Comment (pohly) [inline test/e2e/framework/framework.go:253]: Pet peeve of mine: the `err` is a pretty uninformative "timed out waiting for the condition", so without an additional message, a failure is just:
```
Apr 21 13:00:31.563: FAIL: Unexpected error:
    <*errors.errorString | 0xc00042cd80>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
```

I know because I am hitting this in one of my downstream test scenarios... :sweat_smile: 

Please always add an explanation when calling ExpectNoError.
