### PR TITLE
change the "too old resource version" error from NewInternalError to NewBadRequest

### LINKED ISSUE #14384: apiserver: too old resource version error reported with wrong type
```
I0922 10:29:36.108012       5 handlers.go:143] GET /api/v1/watch/nodes?fieldSelector=metadata.name%3De2e-scalability-minion-v2ke&resourceVersion=285860: (1.675017213s) 500
goroutine 1159865 [running]:
k8s.io/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc2ce615080, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/httplog/log.go:188 +0x9a
k8s.io/kubernetes/pkg/apiserver.writeJSON(0x1f4, 0x7f4c2d21b238, 0xc2080f7120, 0x7f4c2d21b9d0, 0xc23aef4900, 0x7f4c2d069698, 0xc2ce615080, 0x1)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:399 +0x2b7
k8s.io/kubernetes/pkg/apiserver.errorJSON(0x7f4c2d215f40, 0xc21679c560, 0x7f4c2d21b238, 0xc2080f7120, 0x7f4c2d069698, 0xc2ce615080, 0xc2b161b680)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:406 +0xab
k8s.io/kubernetes/pkg/apiserver.func·027(0xc2c8d634a0, 0xc2ce615140)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go:256 +0xc2a
github.com/emicklei/go-restful.func·009(0xc2c8d634a0, 0xc2ce615140)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:244 +0x41
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc2c8d63530, 0xc2c8d634a0, 0xc2ce615140)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:21 +0xa2
k8s.io/kubernetes/pkg/apiserver.func·003(0xc2c8d634a0, 0xc2ce615140, 0xc2c8d63530)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/apiserver/apiserver.go:61 +0x8b
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc2c8d63530, 0xc2c8d634a0, 0xc2ce615140)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/filter.go:19 +0x84
github.com/emicklei/go-restful.(*Container).dispatch(0xc2082a8090, 0x7f4c2d069698, 0xc2ce615080, 0xc284274f70)
	/go/src/k8s.io/kubernetes/Godeps/_workspace/src/github.com/emicklei/go-restful/container.go:246 +0xee3
github.com/emicklei/go-restful.*Container.(github.com/emicklei/go-restful.dispatch)·fm(0x7f4c2d069698, 0xc2ce615080, 0xc284274f70)
	/go/src/k8s.io/kubernetes/Godeps/_workspa [[kubelet/v1.1.0 (linux/amd64) kubernetes/09cf38e] 10.240.139.247:41331]
E0922 10:29:36.108127       5 errors.go:62] apiserver received an error that is not an unversioned.Status: too old resource version: 287512 (289102)
```

### PR DESCRIPTION
**Pull request by caesarxuchao**
fix #14384

cc @erictune

### CODE REVIEW

**Comment by caesarxuchao** [comment]
Sorry. I should have tested it locally first. I will fix it.

File: pkg/storage/watch_cache.go [hunk 1]
```diff
@@ -266,7 +266,7 @@ func (w *watchCache) GetAllEventsSinceThreadUnsafe(resourceVersion uint64) ([]wa
 		return result, nil
 	}
 	if resourceVersion < oldest {
-		return nil, errors.NewInternalError(fmt.Errorf("too old resource version: %d (%d)", resourceVersion, oldest))
+		return nil, errors.NewBadRequest(fmt.Sprintf("too old resource version: %d (%d)", resourceVersion, oldest))
```
Comment (wojtek-t) [inline pkg/storage/watch_cache.go]: To be honest - I'm not convinced about this change.
From the logic point of view - it's not a bad request - it's totally valid request.
It's the implementation limitation, that we cannot handle this request, because we don't have old enough data.

So for me it look more like "InternalError" - the request is correct - we just aren't good enough to serve it :)

Comment (bprashanth) [inline pkg/storage/watch_cache.go]: Yeah I don't think it's a bad request. Also I *think* InternalError will give you a stack trace in apiserver logs, I would like to avoid this if it's the case. I suggest 410 if it avoids the stack trace.

Comment (caesarxuchao) [inline pkg/storage/watch_cache.go]: Thanks @bprashanth. 410 seems to be most accurate one. Currently we don't have a NewGone method. I'll add one.

Comment (wojtek-t) [inline pkg/storage/watch_cache.go]: Yeah - 410 sounds good.

Comment (lavalamp) [inline pkg/storage/watch_cache.go]: Actually what do you guys think about "412 Precondition Failed"-- I think
410 Gone sounds much too permanent?

Comment (lavalamp) [inline pkg/storage/watch_cache.go]: "416 Requested Range Not Satisfiable" and "417 Expectation Failed" both
sound reasonable, too. Unfortunately all 3 are talking about *headers* and
we are doing this via a *query* parameter.

Comment (bprashanth) [inline pkg/storage/watch_cache.go]: As long as it's not one of the more frequently used return codes I don't have a preference. 404 is what you generally use for things like http://www.google.com/lkajsdlkf, and of course a 5xx means we messed up. I agree 410 is generally what one would apply for: I know for sure this resource used to exist, but it's been deleted, and for it to apply in this scenario the "resource" in question needs to be the in-memory watch window etcd has flushed.

**Comment by lavalamp** [comment]
OK, I guess let's go with 410 Gone. We can change it later if we get complaints. I don't know that we currently consider HTTP response codes part of our API, though perhaps we should.

File: pkg/api/unversioned/types.go [hunk 2]
```diff
@@ -162,6 +162,11 @@ const (
 	// Status code 409
 	StatusReasonConflict StatusReason = "Conflict"
 
+	// StatusReasonGone means the item is no longer available at the server and no
+	// forwarding address is known.
+	// Status code 410
+	StatusReasonGone StatusReason = "Gone"
```
Comment (caesarxuchao) [inline pkg/api/unversioned/types.go]: @lavalamp, this actually is an API change.

Comment (lavalamp) [inline pkg/api/unversioned/types.go]: Right, it's totally fine to add this status code to the api. The thing I was talking about was the range of codes we could possibly return from a given request. I don't think we consider that part of the API, or at least it's not written down places. I could be wrong?

Comment (caesarxuchao) [inline pkg/api/unversioned/types.go]: Hmm..Status code that will be sent by the server is listed In the api-converions doc, and 410 is not there. https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#http-status-codes. Does that make the status code part of the API?

**Comment by caesarxuchao** [comment]
@k8s-bot test this please.

File: pkg/api/unversioned/types.go (hunk 2 above)
Comment (lavalamp) [inline pkg/api/unversioned/types.go]: Good catch. Please include a change to that doc in this PR!

File: docs/devel/api-conventions.md [hunk 3]
```diff
@@ -547,6 +547,10 @@ The following HTTP status codes may be returned by the API.
   * * If updating an existing resource:
       * See `Conflict` from the `status` response section below on how to retrieve more information about the nature of the conflict.
       * GET and compare the fields in the pre-existing object, merge changes (if still valid according to preconditions), and retry with the updated request (including `ResourceVersion`).
+* `410 StatusGone`
+  * Indicates that the item is no longer available at the server and no forwarding address is known.
+  * Suggested client recovery behavior
+    * Do not retry. Fix the request.
```
Comment (caesarxuchao) [inline docs/devel/api-conventions.md]: The status code is added to the api-conventions.md. PTAL. I'll squash later.

**Comment by wojtek-t** [comment]
@caesarxuchao - LGTM

Can you please squash the commits? (I think that we should merge it finally).

**Comment by caesarxuchao** [comment]
Thanks @wojtek-t. Squashed. I'll ping lavalamp after the holiday.

**Comment by lavalamp** [comment]
LGTM. I'm pretty sure that clients (ours, at least) will treat this the same, as evidenced by the fact that you didn't update any client code, so there shouldn't be a compatibility problem.

**Comment by wojtek-t** [comment]
@k8s-bot unit test this please

**Comment by caesarxuchao** [comment]
@k8s-oncall, why did the bot merge this even if the unit test failed?

**Comment by caesarxuchao** [comment]
cc @eparis @ixdy

**Comment by ixdy** [comment]
#16662 also merged despite unit tests failing. I suspect mergebot is not looking at the unit tests result, which is worrying.

**Comment by eparis** [comment]
@ixdy Basically yes.  Merge bot looks a unit+e2e+travis when it decides to retest.  It only looks at e2e on the re-test.   I will switch it today to look at e2e+unit on retest.

**Comment by eparis** [comment]
(this logic was built back when we had shippable doing unit testing and didn't have a reasonable mechanism to retest)
