### PR TITLE
gce configure containerd default_runtime_name

### LINKED ISSUE #100978: [Failing Test] gce-ubuntu-containerd jobs failing
#### Which jobs are failing:
Both jobs are failing with the same error message.
pull-kubernetes-e2e-gce-ubuntu-containerd
gce-ubuntu-master-containerd

#### Which test(s) are failing:
Tests are not run as clusters fail to come up.

#### Since when has it been failing:
gce-ubuntu-master-containerd:  Cluster creations failures started 2021/04/09 05:09 AM PST.
pull-kubernetes-e2e-gce-ubuntu-containerd: Cluster creation failures started around 2021/04/08 3:15 AM PST
#### Testgrid link:
https://testgrid.k8s.io/google-gce#gce-ubuntu-master-containerd
https://testgrid.k8s.io/google-gce#pull-kubernetes-e2e-gce-ubuntu-containerd

#### Reason for failure:
Cluster creation script fails
```
error during ./hack/e2e-internal/e2e-up.sh: exit status 2
```

### PR DESCRIPTION
**Pull request by aojea**
The presubmit job ipull-kubernetes-e2e-gce-ubuntu-containerd is failing to complete the installation since we bumped the containerd version to 1.5.0

https://testgrid.k8s.io/google-gce#pull-kubernetes-e2e-gce-ubuntu-containerd&width=5

The health-monitor.sh script fails with:
```
time="2021-04-10T20:32:25Z" level=fatal msg="listing pod sandboxes: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
```

and containerd complains about: 
```
time="2021-04-10T20:32:25.933005839Z" level=warning msg="failed to load plugin io.containerd.grpc.v1.cri" error="invalid plugin config: no corresponding runtime configured in `runtimes` for `default_runtime_name`
```

/kind bug
```release-note
NONE
```

Fixes #100978

### CODE REVIEW

**Comment by aojea** [comment]
/assign @dims 
let's see if this solves the problem

File: cluster/gce/gci/configure-helper.sh [hunk 1]
```diff
@@ -3019,30 +3019,37 @@ EOF
     fi
   fi
   cat > "${config_path}" <<EOF
+version = 2
+# Kubernetes requires the cri plugin.
```
Comment (aojea) [inline cluster/gce/gci/configure-helper.sh:3023]: based on the containerd/containerd config for the same case
https://github.com/containerd/containerd/blob/261c107ffc4ff681bc73988f64e3f60c32233b37/contrib/gce/configure.sh

File: cluster/gce/gci/configure-helper.sh [hunk 2]
```diff
@@ -3019,30 +3019,37 @@ EOF
...
+required_plugins = ["io.containerd.grpc.v1.cri"]
```
Comment (dims) [inline cluster/gce/gci/configure-helper.sh:3024]: we don't need this line anymore i think (`required_plugins`)

Comment (aojea) [reply cluster/gce/gci/configure-helper.sh:3024]: there are more differences with the one that lives in containerd/containerd
let's get this fixed and follow up on another PR

Comment (dims) [reply cluster/gce/gci/configure-helper.sh:3024]: we can deal with this in another PR

File: cluster/gce/gci/configure-helper.sh (hunk 1 above)
Comment (dims) [reply cluster/gce/gci/configure-helper.sh:3023]: excellent!

Comment (dims) [reply cluster/gce/gci/configure-helper.sh:3023]: this will work with 1.4.x as well. also it's about time we moved to newer version of config.toml !!
