### PR TITLE
kubelet: add nil check for Node(Un)PrepareResources.

### LINKED ISSUE #124043: DRA: kubelet: crash when plugin returns nil UnprepareResourceResponse
### What happened?

protobuf doesn't require that objects get encoded when they are empty. This can lead to a nil pointer in https://github.com/kubernetes/kubernetes/issues/124042 (although that's probably an error because some information is needed) and in https://github.com/kubernetes/kubernetes/blob/20d0ab7ae808aaddb1556c3c38ca0607663c50ac/staging/src/k8s.io/kubelet/pkg/apis/dra/v1alpha3/api.pb.go#L255 (happened in practice).

The result is a crash of kubelet:
```
E0305 14:50:50.162844   10432 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 883 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3de2d20?, 0x6fc0d90})
	/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
	/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x6b
panic({0x3de2d20?, 0x6fc0d90?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
k8s.io/kubernetes/pkg/kubelet/cm/dra.(*ManagerImpl).UnprepareResources(0xc00097b998, 0xc000d48900)
	/go/src/kubernetes/pkg/kubelet/cm/dra/manager.go:375 +0x67c
k8s.io/kubernetes/pkg/kubelet/cm.(*containerManagerImpl).UnprepareDynamicResources(0xc00027f5c0?, 0x477a71c?)
	/go/src/kubernetes/pkg/kubelet/cm/container_manager_linux.go:1021 +0x22
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).UnprepareDynamicResources(...)
	/go/src/kubernetes/pkg/kubelet/kubelet.go:3055
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).SyncTerminatingPod(0xc0004e3000, {0xc0010b2510?, 0x24?}, 0xc000d48900, 0xed8569a108?, 0x0, 0x0)
	/go/src/kubernetes/pkg/kubelet/kubelet.go:2082 +0x1a0b
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).podWorkerLoop.func1({0x1, {0x0, {0x0, 0x0, 0x0}, 0xc000d48900, 0x0, 0x0, 0x0}}, 0xc0004c4dc0, ...)
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:1279 +0x17d
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).podWorkerLoop(0xc0010b2510?, {0xc0010b2510, 0x24}, 0x0?)
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:1288 +0x47b
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1()
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:950 +0x115
created by k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod in goroutine 230
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:945 +0x221b
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x209f8bc]

goroutine 883 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
	/go/src/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xcd
panic({0x3de2d20?, 0x6fc0d90?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
k8s.io/kubernetes/pkg/kubelet/cm/dra.(*ManagerImpl).UnprepareResources(0xc00097b998, 0xc000d48900)
	/go/src/kubernetes/pkg/kubelet/cm/dra/manager.go:375 +0x67c
k8s.io/kubernetes/pkg/kubelet/cm.(*containerManagerImpl).UnprepareDynamicResources(0xc00027f5c0?, 0x477a71c?)
	/go/src/kubernetes/pkg/kubelet/cm/container_manager_linux.go:1021 +0x22
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).UnprepareDynamicResources(...)
	/go/src/kubernetes/pkg/kubelet/kubelet.go:3055
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).SyncTerminatingPod(0xc0004e3000, {0xc0010b2510?, 0x24?}, 0xc000d48900, 0xed8569a108?, 0x0, 0x0)
	/go/src/kubernetes/pkg/kubelet/kubelet.go:2082 +0x1a0b
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).podWorkerLoop.func1({0x1, {0x0, {0x0, 0x0, 0x0}, 0xc000d48900, 0x0, 0x0, 0x0}}, 0xc0004c4dc0, ...)
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:1279 +0x17d
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).podWorkerLoop(0xc0010b2510?, {0xc0010b2510, 0x24}, 0x0?)
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:1288 +0x47b
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1()
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:950 +0x115
created by k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod in goroutine 230
	/go/src/kubernetes/pkg/kubelet/pod_workers.go:945 +0x221b
```

(from 1.29.1).

### What did you expect to happen?

No crash.

### How can we reproduce it (as minimally and precisely as possible)?

Run the DRA-enabled Akri plugin.

### Anything else we need to know?

Reported by @diconico07 in https://kubernetes.slack.com/archives/C0BP8PW9G/p1709647270084129

### Kubernetes version

Several, but we shouldn't (?) backport because it was alpha.

### Cloud provider

n/a

### OS version

_No response_

### Install tools

_No response_

### Container runtime (CRI) and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

### PR DESCRIPTION
**Pull request by bitoku**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

This PR fixes the issue that kubelet crashes when NodePrepareResources / NodeUnprepareResources returns nil value.

#### Which issue(s) this PR fixes:

Fixes #124043

#### Does this PR introduce a user-facing change?

```release-note
kubelet no longer crashes when a DRA driver returns a nil as part of the Node(Un)PrepareResources response instead of an empty struct (did not affect drivers written in Go, first showed up with a driver written in Rust).
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/cm/dra/manager.go [hunk 1]
```diff
@@ -171,6 +171,9 @@ func (m *ManagerImpl) PrepareResources(pod *v1.Pod) error {
 			if reqClaim == nil {
 				return fmt.Errorf("NodePrepareResources returned result for unknown claim UID %s", claimUID)
 			}
+			if result == nil {
+				return fmt.Errorf("NodePrepareResources returned nil result for claim %s/%s", reqClaim.Namespace, reqClaim.Name)
```
Comment (pohly) [inline pkg/kubelet/cm/dra/manager.go:175]: This is not an error. Just check for nil each time that `result` is used.

We need unit tests for both variants.

Comment (bitoku) [reply pkg/kubelet/cm/dra/manager.go:175]: ok.
what do you mean by both variants?

Comment (bitoku) [reply pkg/kubelet/cm/dra/manager.go:175]: I have a question. This is `NodePrepareResources` (not `NodeUnprepareResources`).

If `NodePrepareResources` successfully prepares the resources, there should be CDIDevices in result, and if it fails prepare the resources, there should be error in result.

In what case, nil result is acceptable?
I read https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/3063-dynamic-resource-allocation/README.md#nodeprepareresource but couldn't find any statement about that.

Comment (pohly) [reply pkg/kubelet/cm/dra/manager.go:175]: > what do you mean by both variants?

A response which maps to nil and a response which maps to an empty struct.

> In what case, nil result is acceptable?

I am unsure about a nil overall result. Perhaps play it safe and assume that nil is the same as the empty struct?

File: pkg/kubelet/cm/dra/manager.go [hunk 2]
```diff
@@ -379,7 +382,7 @@ func (m *ManagerImpl) UnprepareResources(pod *v1.Pod) error {
 			if reqClaim == nil {
 				return fmt.Errorf("NodeUnprepareResources returned result for unknown claim UID %s", claimUID)
 			}
-			if result.Error != "" {
+			if result != nil && result.Error != "" {
```
Comment (pohly) [inline pkg/kubelet/cm/dra/manager.go:385]: I just remembered that there is https://github.com/kubernetes/kubernetes/blob/f4e246bc93ffb68b33ed67c7896c379efa4207e7/staging/src/k8s.io/kubelet/pkg/apis/dra/v1alpha3/api.pb.go#L338

Using that would make the code a bit simpler.

**Comment by ffromani** [comment]
/triage accepted
/priority important-soon

setting same prio as parent issue; it seems there's consensus on the issue about this PR as a candidate fix.

File: pkg/kubelet/cm/dra/manager.go (hunk 1 above)
Comment (bart0sh) [reply pkg/kubelet/cm/dra/manager.go]: > I still think the empty result shouldn't be allowed

I don't think we need to be strict unless there is a valid reason for that. Even if plugin doesn't return cdi devices it doesn't always mean the resource (whatever it is) is not prepared.

File: pkg/kubelet/cm/dra/manager_test.go [hunk 3]
```diff
@@ -59,9 +69,14 @@ func (s *fakeDRADriverGRPCServer) NodePrepareResources(ctx context.Context, req
...
-	deviceName := "claim-" + req.Claims[0].Uid
-	result := s.driverName + "/" + driverClassName + "=" + deviceName
-	return &drapbv1.NodePrepareResourcesResponse{Claims: map[string]*drapbv1.NodePrepareResourceResponse{req.Claims[0].Uid: {CDIDevices: []string{result}}}}, nil
+
+	resp := s.prepareResourcesResponse
+	if resp == nil {
+		deviceName := "claim-" + req.Claims[0].Uid
+		result := s.driverName + "/" + driverClassName + "=" + deviceName
+		resp = &drapbv1.NodePrepareResourcesResponse{Claims: map[string]*drapbv1.NodePrepareResourceResponse{req.Claims[0].Uid: {CDIDevices: []string{result}}}}
+	}
```
Comment (bart0sh) [inline pkg/kubelet/cm/dra/manager_test.go:78]: @bitoku I'm not sure I understand this logic. Why do we store and use response of the previous call? Can you elaborate?

Comment (bart0sh) [reply pkg/kubelet/cm/dra/manager_test.go:78]: got it. Instead of setting it explicitly can we just pass expected response to the `setupFakeDRADriverGRPCServer` as a parameter?

Comment (bart0sh) [reply pkg/kubelet/cm/dra/manager_test.go:78]: My concern is inconsistency. So far we passed all required parameters to the `setupFakeDRADriverGRPCServer` and it worked just fine. Now we have two new setters and I don't see the reason. As both fields are pointers we can pass nil if one is not needed. 

> And if we move this logic to other place, we can no longer return the responsive value to the request and every test cases have to have the return value of the function.

I din't get this part, sorry. Can you elaborate?

Comment (bitoku) [reply pkg/kubelet/cm/dra/manager_test.go:78]: > I din't get this part, sorry. Can you elaborate?

Never mind.
I was worried it can't return the response according to the input `req`, but if we give the expected return value as an input, we don't have to care about it.

Fair enough. I will fix that. thank you!

**Comment by bart0sh** [comment]
/lgtm
/assign @klueska @mrunalp @derekwaynecarr @dchen1107 
for an approval

**Comment by pohly** [comment]
/release-note-edit ```kubelet no longer crashes when a DRA driver returns a nil as part of the NodeUnpublish response instead of an empty struct (did not affect drivers written in Go, first showed up with a driver written in Rust).```

**Comment by pohly** [comment]
/release-note-edit

```
kubelet no longer crashes when a DRA driver returns a nil as part of the NodeUnpublish response instead of an empty struct (did not affect drivers written in Go, first showed up with a driver written in Rust).
```

**Comment by pohly** [comment]
/release-note-edit
```
kubelet no longer crashes when a DRA driver returns a nil as part of the NodeUnpublish response instead of an empty struct (did not affect drivers written in Go, first showed up with a driver written in Rust).
```

**Comment by pohly** [comment]
@bitoku: the bot ignores my attempts to change the release note. Can you update it? Release notes should be understandable without having to guess where to find the issue and looking it up.

This is a candidate for back-porting to 1.30.

**Comment by bitoku** [comment]
@pohly done

**Review by mrunalp — APPROVED** [review]

**Comment by pohly** [comment]
Cherry-pick in https://github.com/kubernetes/kubernetes/pull/124410
