### PR TITLE
kube-proxy crash when load balancers use a different IP family

### LINKED ISSUE #73157: kube-proxy in ipv6 cluster with ipv4 "external-ip" for a service
**What happened**:
I have an ipv6-only cluster, and in that cluster one of the cloud provider systems created a LoadBalancer with an `EXTERNAL-IP` set to an ipv4 address. When this happened kube-proxy continually fails with errors such as:

```
E0122 06:42:12.851974       1 proxier.go:1335] Failed to execute iptables-restore: exit status 2 (ip6tables-restore v1.6.0: host/network `<REDACTED_EXTERNAL_IP>' not found
Error occurred at line: 50
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.

```

From the error here it seems that kube-proxy is blindly assuming all IPs that it gets for services etc. are ipv6, in this case it is ipv4 which is causing iptables to fail.

**What you expected to happen**:
I expected kube-proxy to not add the errant rule. Long-term once [dual-stack support ](https://github.com/kubernetes/enhancements/issues/563) is added this should be a moot point, but as of today since ipv6 only clusters are "supported" my expectation is that a single incorrect IP in a service shouldn't stop all kube-proxy rules from functioning.

**How to reproduce it (as minimally and precisely as possible)**:
Create an ipv6-only cluster and add a service with an External-IP which is ipv4

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.13.2
- Cloud provider or hardware configuration: digitalocean
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): `Linux k8s-test-master 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm
- Others:

### PR DESCRIPTION
**Pull request by aojea**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change

/kind bug

/kind cleanup

> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

kube-proxy, if detects its IP family, filters out the incorrect IP version of the services to avoid issues configuring the rules.

This commit fixes a bug that crashed kube-proxy on the environment with load balancers using different IP versions that the one used by kube-proxy. It was caused by not filtering out the IPs in the LoadBalancer Status Ingress field.

Also, I've just found that the function `FilterIncorrectIPVersion` doesn't have a unit test so we should add one.

**Which issue(s) this PR fixes**:

Fixes #73157

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
fix a bug in kube-proxy that caused it to crash when using load balancers with a different IP family
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: pkg/proxy/util/utils_test.go [hunk 1]
```diff
@@ -537,3 +537,52 @@ func TestShuffleStrings(t *testing.T) {
...
+	}{
+		{
+			ipString:        []string{"192.168.200.2", "192.1.34.23", "fd00:20::1", "2001:db9::3"},
+			isIPv6:          true,
+			expectCorrect:   []string{"fd00:20::1", "2001:db9::3"},
+			expectIncorrect: []string{"192.168.200.2", "192.1.34.23"},
+		},
+		{
+			ipString:        []string{"192.168.200.2", "192.1.34.23", "fd00:20::1", "2001:db9::3"},
+			expectCorrect:   []string{"192.168.200.2", "192.1.34.23"},
```
Comment (danwinship) [inline pkg/proxy/util/utils_test.go]: I think it would be clearer to explicitly specify `isIPv6: false` on the ipv4 tests. (Also maybe something like `wantIPv6` or `expectIPv6` or `keepIPv6`?)

otherwise looks good

**Comment by aojea** [comment]
/hold
I need to address Dan comments

File: pkg/proxy/util/utils_test.go (hunk 1 above)
Comment (aojea) [reply pkg/proxy/util/utils_test.go]: yeah, also will add a desc field to describe the test

Comment (aojea) [reply pkg/proxy/util/utils_test.go]: done

**Comment by aojea** [comment]
sorry for the changes, but since the fix to the bug is related to the unit test I prefer to submit only PR.
I will keep the hold until  I can test it locally, but is ready to review please take a look.

**Comment by aojea** [comment]
/hold cancel

the patch works
```
I0114 10:38:20.605719       1 server_others.go:79] IPv6 bind address (::), assume IPv6 operation
W0114 10:38:21.014615       1 server_others.go:369] Unknown proxy mode "", assuming iptables proxy
I0114 10:38:21.020153       1 node.go:135] Successfully retrieved node IP: 2001:db8:1::242:ac11:3
I0114 10:38:21.020176       1 server_others.go:150] Using iptables Proxier.
I0114 10:38:21.020371       1 server.go:580] Version: v1.18.0-alpha.1.633+8428af6fd79e1f-dirty
I0114 10:38:21.020712       1 conntrack.go:52] Setting nf_conntrack_max to 262144
I0114 10:38:21.021127       1 config.go:133] Starting endpoints config controller
I0114 10:38:21.021157       1 shared_informer.go:206] Waiting for caches to sync for endpoints config
I0114 10:38:21.021190       1 config.go:315] Starting service config controller
I0114 10:38:21.021310       1 shared_informer.go:206] Waiting for caches to sync for service config
E0114 10:38:21.023822       1 utils.go:221] 172.31.71.218 in externalIPs has incorrect IP version (service default/hello-world).
E0114 10:38:21.023876       1 utils.go:221] 2.2.2.2 in Load Balancer ingress IPs has incorrect IP version (service default/hello-world).
E0114 10:38:21.023938       1 utils.go:221] 6.6.6.6 in externalIPs has incorrect IP version (service default/testipv4).
E0114 10:38:21.024087       1 utils.go:221] 172.31.71.218 in externalIPs has incorrect IP version (service default/example-lb).
E0114 10:38:21.024105       1 utils.go:221] 5.5.5.5 in Load Balancer ingress IPs has incorrect IP version (service default/example-lb).
I0114 10:38:21.121394       1 shared_informer.go:213] Caches are synced for endpoints config 
I0114 10:38:21.121470       1 shared_informer.go:213] Caches are synced for service config 
```

**Comment by aojea** [comment]
@danwinship @thockin can you PTAL?

File: pkg/proxy/util/utils_test.go [hunk 2]
```diff
@@ -537,3 +537,66 @@ func TestShuffleStrings(t *testing.T) {
...
+			wantIPv6:        true,
+			expectCorrect:   []string{"fd00:20::1", "2001:db9::3"},
+			expectIncorrect: nil,
+		},
+	}
+
+	for i := range testCases {
+		correct, incorrect := FilterIncorrectIPVersion(testCases[i].ipString, testCases[i].wantIPv6)
+		if !reflect.DeepEqual(testCases[i].expectCorrect, correct) {
+			t.Errorf("Test %v failed: expected %v, got %v", testCases[i].desc, testCases[i].expectCorrect, correct)
```
Comment (andrewsykim) [inline pkg/proxy/util/utils_test.go]: If you wrap this in a `t.Run` you don't have to include the test description in the error
```go
for _, testcase := range testCases {
    t.Run(testcase.desc, func(t *testing.T) {
           <rest of test>...
    })         
}
```

File: pkg/proxy/service.go [hunk 3]
```diff
@@ -166,6 +166,20 @@ func (sct *ServiceChangeTracker) newBaseServiceInfo(port *v1.ServicePort, servic
 		if len(incorrectIPs) > 0 {
 			utilproxy.LogAndEmitIncorrectIPVersionEvent(sct.recorder, "loadBalancerSourceRanges", strings.Join(incorrectIPs, ","), service.Namespace, service.Name, service.UID)
 		}
+		// Obtain Load Balancer Ingress IPs
+		var ips []string
+		for _, ing := range service.Status.LoadBalancer.Ingress {
+			ips = append(ips, ing.IP)
+		}
+		correctIPs, incorrectIPs := utilproxy.FilterIncorrectIPVersion(ips, *sct.isIPv6Mode)
```
Comment (andrewsykim) [inline pkg/proxy/service.go]: Should we gate this with a `if len(ips) > 0`?

**Review by andrewsykim — COMMENTED** [review]
Left some minor comments

File: pkg/proxy/service.go (hunk 3 above)
Comment (aojea) [reply pkg/proxy/service.go]: yeah, good catch

File: pkg/proxy/util/utils_test.go (hunk 2 above)
Comment (aojea) [reply pkg/proxy/util/utils_test.go]: done

File: pkg/proxy/service_test.go [hunk 4]
```diff
@@ -173,8 +174,24 @@ func TestServiceToServiceMap(t *testing.T) {
 				}
 			}),
 			expected: map[ServicePortName]*BaseServiceInfo{
-				makeServicePortName("ns1", "load-balancer", "port3", v1.ProtocolUDP): makeTestServiceInfo("172.16.55.11", 8675, "UDP", 0),
-				makeServicePortName("ns1", "load-balancer", "port4", v1.ProtocolUDP): makeTestServiceInfo("172.16.55.11", 8676, "UDP", 0),
+				makeServicePortName("ns1", "load-balancer", "port3", v1.ProtocolUDP): makeTestServiceInfo("172.16.55.11", 8675, "UDP", 0, func(info *BaseServiceInfo) {
+					info.loadBalancerStatus = v1.LoadBalancerStatus{
```
Comment (thockin) [inline pkg/proxy/service_test.go]: This adds a lot of vertical space to an otherwise terse test, making it hard to read.  It seems this could be:

```
info.loadBalancerStatus.Ingress = []v1.LoadBalancerIngress{{IP: "10.1.2.4"}}
```

This applies to all cases and should make this already ridiculously long list a bit shorter

**Review by thockin — COMMENTED** [review]
Took me a minute to catch on, but seems OK.  Small request for formatting

**Comment by aojea** [comment]
/retest
```
[sig-storage] Projected downwardAPI should provide container's memory request [NodeConformance] [Conformance] expand_more	49s
[sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should support existing single file [LinuxOnly] expand_more	2m15s
[k8s.io] InitContainer [NodeConformance] should invoke init containers on a RestartNever pod [Conformance]
```

**Comment by thockin** [comment]
Thanks!

/lgtm
/approve
