### PR TITLE
Fixes to kubekins test-image, add makefile

### LINKED ISSUE #14781: Containerize verification checks, unit tests, and integration test
In the pull request Jenkins, we're running up to 8 instances of verification checks, build, unit tests, integration tests, and e2e tests.

Unfortunately, it seems like several of these components were not designed to run simultaneous to other tests on the same machine.

In particular, several unit tests seem to write to static file names in /tmp (or equivalent), which is a fairly easy fix. Some of the verification checks and the integration test start up etcd, however, and the etcd helper checks that only a single etcd binary is running on the host (and uses a static port for it).

For example:
```
Verifying ./hack/../hack/verify-generated-swagger-docs.sh
+++ [0929 12:56:12] Building go targets for linux/amd64:
    cmd/genswaggertypedocs
+++ [0929 12:56:12] Placing binaries
Generating swagger type docs for unversioned
Generating swagger type docs for v1
Generating swagger type docs for experimental/v1alpha1
+++ [0929 12:56:15] Building go targets for linux/amd64:
    cmd/kube-apiserver
+++ [0929 12:56:28] Placing binaries

etcd appears to already be running on this machine (7295 etcd) (or its a zombie and you need to kill its parent).


retry after you resolve this etcd error.

+++ [0929 12:56:29] Clean up complete
!!! Error in /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@5/hack/update-swagger-spec.sh:31
  '"${KUBE_ROOT}/hack/after-build/update-swagger-spec.sh" "$@"' exited with status 1
Call stack:
  1: /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@5/hack/update-swagger-spec.sh:31 main(...)
Exiting with status 1
!!! Error in /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@5/hack/update-generated-swagger-docs.sh:68
  '"${KUBE_ROOT}/hack/update-swagger-spec.sh"' exited with status 1
Call stack:
  1: /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@5/hack/update-generated-swagger-docs.sh:68 main(...)
Exiting with status 1
!!! Error in /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@5/hack/after-build/verify-generated-swagger-docs.sh:46
  '"${KUBE_ROOT}/hack/update-generated-swagger-docs.sh"' exited with status 1
Call stack:
  1: /jenkins-master-data/jobs/kubernetes-pull-build-test-e2e-gce/workspace@5/hack/after-build/verify-generated-swagger-docs.sh:46 main(...)
Exiting with status 1
!!! Error in ./hack/../hack/verify-generated-swagger-docs.sh:28
  '"${KUBE_ROOT}/hack/after-build/verify-generated-swagger-docs.sh" "$@"' exited with status 1
Call stack:
  1: ./hack/../hack/verify-generated-swagger-docs.sh:28 main(...)
Exiting with status 1
FAILED
```

```
+++ [0929 13:03:14] Building go targets for linux/amd64:
    cmd/integration
+++ [0929 13:03:31] Placing binaries

etcd appears to already be running on this machine (7295 etcd) (or its a zombie and you need to kill its parent).


retry after you resolve this etcd error.

+++ [0929 13:03:32] Integration test cleanup complete
```

We might be able to fix the etcd issue separately, or we can just figure out how to containerize all of these tests so they can't possibly interfere with each other.

Note that we're ignoring the exit status of the verification checks and unit/integration tests right now, so these etcd failures are effectively being ignored (though it is causing us to miss test coverage).

@kubernetes/goog-testing

### PR DESCRIPTION
**Pull request by j3ffml**
Fix issues, address comments from #16140. Also, closes #14781

@ixdy, to answer "why separate gotest-pr.sh"; tests run in container as root, so build/test output files in the workspace get owned by root as well. This requires extra cleanup steps I didn't want to reproduce for the `kubernetes-test-go` job, but I can if you think it's worth doing.

### CODE REVIEW

File: hack/jenkins/test-image/Makefile [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+
+container:
+	docker build -t gcr.io/google_containers/kubekins-test .
+	docker tag gcr.io/google_containers/kubekins-test gcr.io/google_containers/kubekins-test:$(TAG)
+
+push: container
+	gcloud docker push gcr.io/google_containers/kubekins-test # Push image tagged as latest to repository
+	gcloud docker push gcr.io/google_containers/kubekins-test:$(TAG) # Push version tagged image to repository (since this image is already pushed it will simply create or update version tag)
+
+clean:
```
Comment (ashcrow) [inline hack/jenkins/test-image/Makefile]: No clean?

Comment (jlowdermilk) [inline hack/jenkins/test-image/Makefile]: No generated files, so nothing to clean. Empty target is the pattern used [elsewhere](https://github.com/kubernetes/kubernetes/search?l=makefile&p=3&q=clean&type=Code&utf8=%E2%9C%93).

**Comment by jlowdermilk** [comment]
@k8s-bot unit test this

File: hack/jenkins/test-image/run.sh [hunk 2]
```diff
@@ -42,6 +38,10 @@ export KUBE_COVERPROCS=8
 export KUBE_INTEGRATION_TEST_MAX_CONCURRENCY=4
 export LOG_LEVEL=4
 
+./hack/build-go.sh
+godep go install ./...
+./hack/install-etcd.sh
```
Comment (ixdy) [inline hack/jenkins/test-image/run.sh]: maybe make this ./hack/install-etcd.sh || ./hack/travis/install-etcd.sh?

or we can cherrypick #15336 into release-1.0 and release-1.1.

File: hack/jenkins/test-image/run.sh [hunk 3]
```diff
@@ -42,6 +38,10 @@ export KUBE_COVERPROCS=8
...
+
 ./hack/verify-gofmt.sh
```
Comment (ixdy) [inline hack/jenkins/test-image/run.sh]: can we use verify-all.sh instead of listing each one individually? there are actually a few new verify-* checks missing from this list now. (and kubernetes-test-go is using verify-all.sh)

File: hack/jenkins/test-image/run.sh [hunk 4]
```diff
@@ -42,6 +38,10 @@ export KUBE_COVERPROCS=8
 export KUBE_INTEGRATION_TEST_MAX_CONCURRENCY=4
```
Comment (ixdy) [inline hack/jenkins/test-image/run.sh]: GitHub won't let me add a comment on the correct lines, but we don't need export KUBE_GOVERALLS_BIN="${GOPATH}/bin/goveralls" or export KUBE_COVERPROCS=8

File: hack/jenkins/test-image/run.sh (hunk 2 above)
Comment (jlowdermilk) [inline hack/jenkins/test-image/run.sh]: Unfortunately #15336 is only one of several changes in test scripts between 1.0/1.1 and head. We can either go through and cherrypick all the changes, or we can have a branch-specific `hack/jenkins/test-image/run.sh` for each branch that runs the version of verify* scripts that exist on the branch.

**Comment by ixdy** [comment]
I guess my uneasiness with having gotest.sh vs. gotest-pr.sh is that we have yet another place where the list of tests to run is specified, with a high probability that things will drift out of sync.

Eventually we should probably just make `kubernetes-test-go` use the containerized version. Then we can retire gotest.sh or whatever. (I guess gotest-dockerized.sh is a better name than gotest-pr.sh, in that case?)

File: hack/jenkins/test-image/run.sh (hunk 2 above)
Comment (ixdy) [inline hack/jenkins/test-image/run.sh]: another option (maybe this is getting into too much indirection?) is that this file calls hack/jenkins/gotest.sh (or equivalent).

the advantage there is that the list of tests run follows the branch, rather than using the same list across all builds. using the same run.sh for all branches means that we'll have to have special cases.

**Comment by jlowdermilk** [comment]
Please hold off reviewing further, I'm going to see if I can tweak this to make it run on branches with minimal cherrypicking.

**Comment by jlowdermilk** [comment]
Ok I think this is in a more reasonable state now, ptal. Should be able to cherrypick this onto 1.0 and 1.1 and just modify `hack/jenkins/test-dockerized.sh` to work for old script names.

Also cc @nikhiljindal for changes to `hack/verify-api-reference-docs.sh`

File: hack/jenkins/test-image/run.sh (hunk 4 above)
Comment (jlowdermilk) [inline hack/jenkins/test-image/run.sh]: Done.

**Comment by jlowdermilk** [comment]
@ixdy, I took your idea to rename the test script `gotest-dockerized.sh`. Once this is in, I'm happy to update `kubernetes-test-go` to use this version and retire `hack/jenkins/gotest.sh`

**Comment by nikhiljindal** [comment]
Changes to update-api-reference-docs LGTM.
Note that that script does not exist in 1.0 or 1.1

**Comment by jlowdermilk** [comment]
@nikhiljindal, yup, not planning on cherrypicking that script onto release branches; `test-dockerized.sh` will just call `verify-all.sh` to run whatever exists on the branch.

File: hack/verify-api-reference-docs.sh [hunk 5]
```diff
@@ -26,11 +26,16 @@ source "${KUBE_ROOT}/hack/lib/init.sh"
 kube::golang::setup_env
 
 API_REFERENCE_DOCS_ROOT="${KUBE_ROOT}/docs/api-reference"
+# We want to pass absolute dir to update-api-reference-docs.sh, but diff
+# against local path to dir. This only matters in the case where this
+# test is itself running inside a container (with the host docker mapped in).
+REPO_DIR=${REPO_DIR:-"${PWD}/${KUBE_ROOT}"}
```
Comment (caesarxuchao) [inline hack/verify-api-reference-docs.sh]: I thought ${KUBE_ROOT} will become an absolute path after running `source "${KUBE_ROOT}/hack/lib/init.sh"`, I guess this is not the case if you are running the script inside a container?

Comment (jlowdermilk) [inline hack/verify-api-reference-docs.sh]: You are correct, thanks for pointing out. As it was, this was broken when run standalone. Comment was a bit disingenuous, now describes the actual reason for using REPO_DIR if provided.

Comment (caesarxuchao) [inline hack/verify-api-reference-docs.sh]: Thanks for the fix.

**Comment by ixdy** [comment]
I think the test image needs `file` after #16160. It's otherwise failing builds, e.g. https://github.com/kubernetes/kubernetes/pull/16382#issuecomment-151951626

**Comment by ixdy** [comment]
wait, I see you did that now. nm.

**Comment by jlowdermilk** [comment]
@ixdy, already [added](https://github.com/kubernetes/kubernetes/pull/16287/files#diff-b0482323778c603f345a2233dfe79039R29), sorry it got lost in premature squash. Currently running version has it too.

**Comment by jlowdermilk** [comment]
@k8s-bot unit test this

File: hack/jenkins/test-dockerized.sh [hunk 6]
```diff
@@ -19,12 +19,13 @@ set -o nounset
 set -o pipefail
 set -o xtrace
 
+# Runs the unit and integration tests, production JUnit-style XML test reports
```
Comment (ixdy) [inline hack/jenkins/test-dockerized.sh]: nit: s/production/producing/

File: hack/verify-api-reference-docs.sh [hunk 7]
```diff
@@ -25,12 +25,18 @@ source "${KUBE_ROOT}/hack/lib/init.sh"
 
 kube::golang::setup_env
 
+
```
Comment (ixdy) [inline hack/verify-api-reference-docs.sh]: nit: this newline seems extraneous?

File: hack/verify-api-reference-docs.sh [hunk 8]
```diff
@@ -25,12 +25,18 @@ source "${KUBE_ROOT}/hack/lib/init.sh"
...
+# to the repo root if we are running this script from a container with
+# docker mounted in as a volume.
+REPO_DIR=${REPO_DIR:-"${KUBE_ROOT}"}
+ABS_OUTPUT_DIR="${REPO_DIR}/_tmp/api-reference"
 TMP_OUTPUT_DIR="${KUBE_ROOT}/_tmp/api-reference"
 TMP_ROOT="${KUBE_ROOT}/_tmp"
 
 # Generate API reference docs in tmp.
-"./hack/update-api-reference-docs.sh" "${TMP_OUTPUT_DIR}"
+"./hack/update-api-reference-docs.sh" "${ABS_OUTPUT_DIR}"
```
Comment (ixdy) [inline hack/verify-api-reference-docs.sh]: should we update all references to TMP_OUTPUT_DIR? (e.g. L43)

File: hack/jenkins/test-dockerized.sh (hunk 6 above)
Comment (jlowdermilk) [inline hack/jenkins/test-dockerized.sh]: fixed.

File: hack/verify-api-reference-docs.sh (hunk 8 above)
Comment (jlowdermilk) [inline hack/verify-api-reference-docs.sh]: The name was a bit misleading. They're actually both absolute paths, but we need to pass in a host-resolvable path to update-api-reference-docs.sh for this script to run in a container. Renamed to HOST_OUTPUT_DIR and added comment explaining why it's necessary.

There is a [comment](https://github.com/kubernetes/kubernetes/pull/16287/files#diff-b38b0e262cb33e5d5cf7c6269785a970R30) to this effect, but gotest-dockerized does a `docker run` with docker itself mounted into the container as a volume so that tests/scripts (running in a container) can use also launch containers. This particular script does a `docker run -v` and mounts a path under the repo directory. In order to do that, it has to use the host-resolvable repo path for the docker mount path. However the diff runs in the kubekins-test, so it should use the repo path resolvable from the container. If it helps, this is what's going on:

[host]
path to repo: `/home/me/kubernetes`
cmd:
```
    cd ~ kubernetes
    hack/jenkins/gotest-dockerized.sh 
    ...
    # launches kubekins-test container
```

[ inside kubekins-test container]
path to repo: `/go/src/k8s.io/kubernetes`
Note that the above path is mapped to `/home/me/kubernetes` on the host.
cmd:
```
  cd /go/src/k8s.io/kubernetes
  ...
  hack/verify-api-reference-docs.sh
  ...
  # launches gendocs container
```

[ inside gendocs container ]
path to output dir: `/output`
Note that `/output` is mapped to `/home/me/kubernetes/docs/api-reference` on the host, and `/go/src/k8s.io/kubernetes/docs/api-reference` inside kubekins-test.

   cmd:
```
   build/gen-swagger-docs.sh
```

Hope that makes sense. The inception is a bit tricky, so I've tried to leave comments explaining it.

**Comment by jlowdermilk** [comment]
@ixdy, comments addressed ptal.

**Comment by jlowdermilk** [comment]
@k8s-bot unit test this

File: hack/verify-api-reference-docs.sh [hunk 9]
```diff
@@ -26,11 +26,19 @@ source "${KUBE_ROOT}/hack/lib/init.sh"
 kube::golang::setup_env
 
 API_REFERENCE_DOCS_ROOT="${KUBE_ROOT}/docs/api-reference"
+# Use REPO_DIR if provided so we can set it to the host-resolvable path
+# to the repo root if we are running this script from a container with
+# docker mounted in as a volume.
+# We pass the host output dir to update-api-reference-docs.sh, but use
```
Comment (ixdy) [inline hack/verify-api-reference-docs.sh]: So I just want to fully understand what's happening here - HOST_OUTPUT_DIR and TMP_OUTPUT_DIR end up mapping to the same files always, even if the paths are different, all due to docker wonkiness?

File: hack/jenkins/test-dockerized.sh [hunk 10]
```diff
@@ -19,12 +19,13 @@ set -o nounset
 set -o pipefail
 set -o xtrace
 
+# Runs the unit and integration tests, producing JUnit-style XML test
+# reports in ${WORKSPACE}/_artifacts. This script is intended to be run from
```
Comment (ixdy) [inline hack/jenkins/test-dockerized.sh]: nit: here it's artifacts, not _artifacts.

File: hack/verify-api-reference-docs.sh (hunk 9 above)
Comment (jlowdermilk) [inline hack/verify-api-reference-docs.sh]: Correct. They point to the same files, you just need a different absolute path to resolve them on the host vs from inside the test container.

**Comment by ixdy** [comment]
LGTM, but please squash commits.

(A side note: Shippable currently tests 2 versions of Go. Do we want to keep testing 2 versions or only the latest?)

**Comment by jlowdermilk** [comment]
Squashed.

Regarding testing multiple versions, I think it's fine to just do 1.4 for now. We're in the process of bumping to 1.5 (#13838), so we'll probably care about testing 1.4, 1.5. We can accomplish that by building a second test-image with go 1.5.1 as the base image and modifying `gotest-dockerized.sh` to run the tests with both images. However I'd like to get this in as is, since it will make it easier to debug/fix the tests that are broken on 1.5.1.

**Comment by jlowdermilk** [comment]
@k8s-bot unit test this

**Comment by ixdy** [comment]
assuming Jenkins passes lgtm
