### PR TITLE
Namespace controller deletes pods last

### LINKED ISSUE #29308: e2e test flake: namespace xyz was not deleted within limit: timed out waiting for the condition, pods remaining: []
I've noticed at least 10 separate test flake issues open in which at least one failure looks like this:

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:128
Jul 20 11:12:15.579: Couldn't delete ns "e2e-tests-kubectl-2k86f": namespace e2e-tests-kubectl-2k86f was not deleted within limit: timed out waiting for the condition, pods remaining: []
```

Current list: https://github.com/kubernetes/kubernetes/issues?utf8=✓&q=is%3Aissue%20label%3Akind%2Fflake%20is%3Aopen%20%22was%20not%20deleted%20within%20limit%22

The 10 current issues (note that some are 'broken test run' issues and might have multiple failure causes):

#28827 
#28722 
#28656 
#28514 
#28440 
#28413 
#28383 
#27524 
#27503 
#26982

cc @derekwaynecarr @wojtek-t

### PR DESCRIPTION
**Pull request by derekwaynecarr**
I think this fixes https://github.com/kubernetes/kubernetes/issues/29308 or at least helps further reduce the incidence.

This PR changes the order in which namespace controller prioritizes resources for deletion.  It deletes all resources before deleting pods.  The rationale for this change is to broadcast deletion of controllers that spawn pods first rather than trip those controllers up into thinking they should spawn more pods which would increase the risk of causing races with the `NamespaceLifecycle` admission plug-in.  Many of those controllers also are not rate-limited in the face of rejection, so rather than promote a situation where they are rejected, we promote a situation that removes those things first.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/31917)

### CODE REVIEW

**Comment by ncdc** [comment]
Probably want a unit test for this?

**Comment by derekwaynecarr** [comment]
@ncdc ack - but need to go home right now, so I can do that in a follow-on or we can hold the PR.  I verified manually.

File: pkg/controller/namespace/namespace_controller_utils.go [hunk 1]
```diff
@@ -453,3 +456,20 @@ func estimateGracefulTerminationForPods(kubeClient clientset.Interface, ns strin
...
+func (list sortableGroupVersionResources) Len() int {
+	return len(list)
+}
+
+func (list sortableGroupVersionResources) Swap(i, j int) {
+	list[i], list[j] = list[j], list[i]
+}
+
+func (list sortableGroupVersionResources) Less(i, j int) bool {
+	return list[j].Group == "" && list[j].Resource == "pods"
```
Comment (lavalamp) [inline pkg/controller/namespace/namespace_controller_utils.go]: if there were multiple "pods" resources in the list, then this comparison broken. But there should only be one, so I guess it's OK. A test might be good?

**Comment by lavalamp** [comment]
LGTM

Looks important enough that I'll take a test in a followup.

File: pkg/controller/namespace/namespace_controller_utils.go (hunk 1 above)
Comment (wojtek-t) [inline pkg/controller/namespace/namespace_controller_utils.go]: Assuming that we don't have different versions of the same group and pods being registered in all those versions.
This is currently not the case, but I agree with @lavalamp that we probably need a test for it.

**Comment by wojtek-t** [comment]
LGTM

**Comment by wojtek-t** [comment]
>
Looks important enough that I'll take a test in a followup.

I agree with that. So I'm adding a label to have this in.
