### PR TITLE
Avoid duplicate Failed conditions in job status

### LINKED ISSUE #109904: Duplicate Failed condition in job status
### What happened?

If the user update job.status.conditions, duplicate condition:

image

### What did you expect to happen?

Only one Failed condition

### How can we reproduce it (as minimally and precisely as possible)?

- Create Job and wait it marked as Failed
- Update the Failed condition to False

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.12", GitCommit:"4bf2e32bb2b9fdeea19ff7cdc1fb51fb295ec407", GitTreeState:"clean", BuildDate:"2021-10-27T17:07:18Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug
/kind cleanup

#### What this PR does / why we need it:

Avoids creation of duplicate failed conditions (multiple conditions with the same type) for a job after a user changes the failed condition status to False. Such duplicate conditions are problematic for other places in the code of job_controller, which assume there is a single condition of a given type and return / process the first only.

#### Which issue(s) this PR fixes:

Fixes #109904

#### Special notes for your reviewer:

none

#### Does this PR introduce a user-facing change?

```release-note
Manual change of a failed job condition status to False does not result in duplicate conditions
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

none

### CODE REVIEW

File: pkg/controller/job/job_controller.go [hunk 1]
```diff
@@ -1205,7 +1205,16 @@ func (jm *Controller) enactJobFinished(job *batch.Job, finishedCond *batch.JobCo
 	if isIndexedJob(job) {
 		completionMode = string(*job.Spec.CompletionMode)
 	}
-	job.Status.Conditions = append(job.Status.Conditions, *finishedCond)
+	// append the finished condition or update if there was already a finished condition with non-true status
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller.go:1208]: Try using `ensureJobConditionStatus` directly. It's ok if the status is timestamps are overwritten.

File: pkg/controller/job/job_controller_test.go [hunk 2]
```diff
@@ -1864,6 +1864,49 @@ func TestSyncPastDeadlineJobFinished(t *testing.T) {
 	}
 }
 
+func TestSyncPastDeadlineForJobWithConditionStatusFalse(t *testing.T) {
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller_test.go:1867]:
```suggestion
func TestSingleJobFailedCondition(t *testing.T) {
```

And you can also add a comment on top of the function to roughly explain the scenario that the test is implementing.

File: pkg/controller/job/job_controller.go [hunk 3]
```diff
@@ -1652,17 +1652,15 @@ func errorFromChannel(errCh <-chan error) error {
...
-				list[i].LastTransitionTime = metav1.Now()
-				list[i].Reason = reason
-				list[i].Message = message
-				return list, true
-			}
-			return list, false
+	if condition := findConditionByType(list, cType); condition != nil {
+		if condition.Status != status || condition.Reason != reason || condition.Message != message {
+			condition.Status = status
+			condition.LastTransitionTime = metav1.Now()
```
[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/job/job_controller.go:1658]: I don't think I can as the `newCondition` is used to create a new condition instance, whereas the referenced green code (lines 1655-1658) are meant to update the pre-existing condition of a given type (cType).

File: pkg/controller/job/job_controller.go (hunk 1 above)
Comment (mimowo) [reply pkg/controller/job/job_controller.go]: done

File: pkg/controller/job/job_controller.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/job/job_controller.go:1658]: actually, it would be `*condition = *newCondition()`

That should replace every field, which is equivalent to what all these lines are doing.

File: pkg/controller/job/job_controller_test.go [hunk 4]
```diff
@@ -1864,6 +1867,93 @@ func TestSyncPastDeadlineJobFinished(t *testing.T) {
...
+	if len(failedConditions) != 1 {
+		t.Error("Unexpected number of failed conditions\n")
+	}
+	if failedConditions[0].Status != v1.ConditionTrue {
+		t.Errorf("Unexpected status for the failed condition. Expected: %v, saw %v\n", v1.ConditionTrue, failedConditions[0].Status)
+	}
+
+}
+
+func TestSyncJobPastDeadlineFailedConditionAdded(t *testing.T) {
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller_test.go:1913]: Isn't this already covered in existing tests?

File: pkg/controller/job/job_controller_test.go [hunk 5]
```diff
@@ -3140,11 +3230,7 @@ func TestEnsureJobConditions(t *testing.T) {
 			if len(gotList) != len(tc.expectList) {
 				t.Errorf("got a list of length %d, want %d", len(gotList), len(tc.expectList))
 			}
-			for i := range gotList {
-				// Make timestamps the same before comparing the two lists.
-				gotList[i].LastProbeTime = tc.expectList[i].LastProbeTime
-				gotList[i].LastTransitionTime = tc.expectList[i].LastTransitionTime
-			}
+			makeActualTimestampsAsExpected(gotList, tc.expectList)
```
Comment (alculquicondor) [inline pkg/controller/job/job_controller_test.go:3233]: this looks like a hack :)

instead, you can ignore the field when comparing using `cmp.Diff` below.

See cmpopts https://pkg.go.dev/github.com/google/go-cmp/cmp/cmpopts#IgnoreFields

File: pkg/controller/job/job_controller.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (mimowo) [reply pkg/controller/job/job_controller.go]: I see, adjusted. Experimenting with this comment actually has led to me discover a pretty serious bug introduced in one of the previous commits in this PR. Now it is fixed and test added in dfbef16cf5cdb33fc4497299e6c2be1db538f3b7.

File: pkg/controller/job/job_controller_test.go (hunk 4 above)
Comment (mimowo) [reply pkg/controller/job/job_controller_test.go:1913]: Actually, some pre-existing unit tests are failing (for example TestControllerSyncJob) when I remove the assignment "job.Status.Conditions, _ = ensureJobConditionStatus". Not sure how I missed this, I will remove the extra test.

File: pkg/controller/job/job_controller_test.go (hunk 5 above)
Comment (mimowo) [reply pkg/controller/job/job_controller_test.go]: Indeed, improved the comparison in the last commit

**Review by alculquicondor — COMMENTED** [review]
looks good.
Please squash

**Comment by mimowo** [comment]
Thank you @alculquicondor. Do you suggest to squash it on merge? If so please approve and hopefully I can proceed :). I guess I could also squash the commits prior to merge, but it would entail re-write of the branch history.

**Comment by alculquicondor** [comment]
I usually prefer to squash before merging. It leaves a cleaner commit message.

**Review by soltysh — APPROVED** [review]
/approve

**Comment by alculquicondor** [comment]
/retest

the details of the failure are not loading 🤔
