### PR TITLE
Proceed with deletion of rejected pods after Kubelet restart

### LINKED ISSUE #118472: Pod graceful deletion hangs if the kubelet already rejected that pod at admission time
### What happened?

We observed the following series of events:

1) Pod is created with some attributes that later result in the pod being rejected at kubelet admission time
2) The pod is scheduled to a node
3) The pod is gracefully deleted by a controller, i.e. a deletion timestamp is set on the pod
4) The pod is rejected at kubelet admission time
5) The pod never gets deleted and is stuck: despite having the deletion timestamp set. It seems that kubelet does not issue the final force delete for the pod.

This is problematic in many scenarios, but one specific case it was hit was when the pod is backed by a daemonset controller. This issue manifested in way where since the pod never got deleted in step 5 above, the daemonset controller did not create a new pod to run the on the node and thus node was was not running a replica of the daemonset controller pod.

This seems to a be regression in k8s 1.27, I was not able to repro this behavior in 1.26.

### What did you expect to happen?

It is expected at during the series of events above, after the pod is failed at kubelet admission time, since the pod has a deletion timestamp set, the kubelet should forcefully delete the pod. The pod should not hang in deletion forever. 

### How can we reproduce it (as minimally and precisely as possible)?

Create a 1.27 kind cluster:

```
kind delete cluster


kind_config="$(cat << EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
nodes:
# the control plane node
- role: control-plane
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "4"
        read-only-port: "10255"
EOF
)"

kind create cluster --config <(printf '%s\n' "${kind_config}") --image  kindest/node:v1.27.1@sha256:b7d12ed662b873bd8510879c1846e87c7e676a79fefc93e17b2a52989d3ff42b
```

Stop kubelet
```
$ docker exec -it kind-worker /bin/bash
root@kind-worker:/# systemctl stop kubelet
```

Create a pod bound to the node which will trigger a admission error. The below node selector label does not exist, so we expect that the pod should be rejected in admission.

```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleep-2
spec:
  nodeSelector:
    this-label: does-not-exist
  nodeName: "kind-worker"
  containers:
  - name: ubuntu
    image:  gcr.io/google-containers/ubuntu:14.04
    command: ["/bin/sleep"]
    args: ["infinity"]
    resources:
      requests:
        cpu: "1"
        memory: "10Mi"
      limits:
        cpu: "1"
        memory: "10Mi"
```

While kubelet is down issue a graceful deletion to set a deletion timestamp on the pod

```
kubectl delete pod ubuntu-sleep-2
```

Verify deletion timestamp is set (pod is pending)

```
$ k get pod ubuntu-sleep-2 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"ubuntu-sleep-2","namespace":"default"},"spec":{"containers":[{"args":["infinity"],"command":["/bin/sleep"],"image":"gcr.io/google-containers/ubuntu:14.04","name":"ubuntu","resources":{"limits":{"cpu":"1","memory":"10Mi"},"requests":{"cpu":"1","memory":"10Mi"}}}],"nodeName":"kind-worker","nodeSelector":{"cloud.google.com/gke-nodepool":"default-pool"}}}
  creationTimestamp: "2023-06-05T18:44:09Z"
  deletionGracePeriodSeconds: 30
  deletionTimestamp: "2023-06-05T18:44:58Z" <---- deletion timestamp is set
  name: ubuntu-sleep-2
  namespace: default
  resourceVersion: "570"
  uid: 5a8cbd76-f425-46a3-bffb-4cc4eec12557
spec:
  containers:
  - args:
    - infinity
    command:
    - /bin/sleep
    image: gcr.io/google-containers/ubuntu:14.04
    imagePullPolicy: IfNotPresent
    name: ubuntu
    resources:
      limits:
        cpu: "1"
        memory: 10Mi
      requests:
        cpu: "1"
        memory: 10Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5c69j
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kind-worker
  nodeSelector:
    cloud.google.com/gke-nodepool: default-pool
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-5c69j
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  phase: Pending
  qosClass: Guaranteed
```

Start kubelet
```
$ docker exec -it kind-worker /bin/bash
root@kind-worker:/# systemctl start kubelet
```

Observe pod status, the pod is now in failed phase (as expected).
```

$ k get pod ubuntu-sleep-2 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"ubuntu-sleep-2","namespace":"default"},"spec":{"containers":[{"args":["infinity"],"command":["/bin/sleep"],"image":"gcr.io/google-containers/ubuntu:14.04","name":"ubuntu","resources":{"limits":{"cpu":"1","memory":"10Mi"},"requests":{"cpu":"1","memory":"10Mi"}}}],"nodeName":"kind-worker","nodeSelector":{"cloud.google.com/gke-nodepool":"default-pool"}}}
  creationTimestamp: "2023-06-05T18:44:09Z"
  deletionGracePeriodSeconds: 30
  deletionTimestamp: "2023-06-05T18:44:58Z"
  name: ubuntu-sleep-2
  namespace: default
  resourceVersion: "653"
  uid: 5a8cbd76-f425-46a3-bffb-4cc4eec12557
spec:
  containers:
  - args:
    - infinity
    command:
    - /bin/sleep
    image: gcr.io/google-containers/ubuntu:14.04
    imagePullPolicy: IfNotPresent
    name: ubuntu
    resources:
      limits:
        cpu: "1"
        memory: 10Mi
      requests:
        cpu: "1"
        memory: 10Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5c69j
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kind-worker
  nodeSelector:
    cloud.google.com/gke-nodepool: default-pool
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-5c69j
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  message: 'Pod was rejected: Predicate NodeAffinity failed'
  phase: Failed
  reason: NodeAffinity
  startTime: "2023-06-05T18:44:52Z"

```

However, the `kubectl delete pod` hangs, the pod is never force deleted by kubelet.

### Anything else we need to know?

_No response_

### Kubernetes version

1.27

### Cloud provider

<details>
n/a
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by mimowo**
#### What type of PR is this?

/kind bug
/kind regression

#### Which issue(s) this PR fixes:

Fixes #118472

#### Does this PR introduce a user-facing change?

```release-note
Fix 1.27 regression with deletion of non-admissible pods that are deleted during Kubelet restart
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/status/status_manager.go [hunk 1]
```diff
@@ -898,12 +900,12 @@ func (m *manager) canBeDeleted(pod *v1.Pod, status v1.PodStatus, podIsFinished b
 		return false
 	}
 	// Delay deletion of pods until the phase is terminal.
-	if !podutil.IsPodPhaseTerminal(pod.Status.Phase) {
+	if !podutil.IsPodPhaseTerminal(status.Phase) {
```
Comment (bobbypage) [inline pkg/kubelet/status/status_manager.go:903]: Can you explain the rationale behind this change? Why should we look at `status.Phase` vs `pod.Status.Phase` and why are the different in the first place here? I think that's at the root of the issue here.

**Comment by bobbypage** [comment]
Thanks for adding the regression test and taking a stab at the fix! What do you think is proposed fix here? 

My initial look was that we are syncing all the pod status already [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go#L229-L230) but since in the issue the pod is rejected, there is no calls to `kl.statusManager.TerminatePod(pod)` because the pod did not complete `SyncTerminatingPod/SyncTerminatedPod` because it was not admitted in the first place. Is that part of the problem here?

File: pkg/kubelet/status/status_manager.go (hunk 1 above)
Comment (mimowo) [reply pkg/kubelet/status/status_manager.go:903]: > Can you explain the rationale behind this change? Why should we look at status.Phase vs pod.Status.Phase and why are they different in the first place here?

To restore the answer from `needsUpdate` (to return true as before this PR). Returning `pod.Status.Phase` or `status.Phase` does not matter when the function is called from `syncPod`, because the pod is already updated at this point: https://github.com/kubernetes/kubernetes/blob/8b7c7d783908efb53056fcae121ed18e117a8f2e/pkg/kubelet/status/status_manager.go#L849. I have missed the fact it makes a difference for the other path. In the other case the `pod.Status.Phase` returns `Pending` for a non-admissible pod created while the kubelet was down (as in the e2e test)

>  I think that's at the root of the issue here.

Not the entire issue. The second part of the fix is important, because `podIsFinished` returns false.

**Comment by mimowo** [comment]
> Thanks for adding the regression test and taking a stab at the fix! What do you think is proposed approach regarding the fix here?

Sure, I'm happy with this as a fix to restore the 1.26 behavior. 

> My initial look was that we are syncing all the pod status already [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go#L229-L230) however since in the issue the pod is rejected in pod admission, there are no calls to kl.statusManager.TerminatePod(pod) because the pod did not complete the usual SyncTerminatingPod/SyncTerminatedPod. Is that part of the problem here?

I think in the long-term it might be better to go through `syncTerminatingPod`. However, (1.) it was not going through it on 1.26 in this scenario, so it is not a regression, (2) the benefit of going through `syncTerminatingPod` for non-amissible pods is limited as they never had containers running.

**Comment by mimowo** [comment]
/test pull-kubernetes-node-kubelet-serial-containerd
re-run of an unrelated flaky test which also fails on other branches

File: pkg/kubelet/status/status_manager.go (hunk 1 above)
Comment (bobbypage) [reply pkg/kubelet/status/status_manager.go:903]: > I have missed the fact it makes a difference for the other path

What do you mean here by the other path? It seems to be that one of the surprises here is that within `needsUpdate` the pod (as fetched from pod manager) and status as passed to the function have different phase (i.e. the pod one is pending, the status is Failed).

Regarding the second part of the fix, why do we also need to consult the pod worker? Is it because `podIsFinished` is never true because no-one ever called `TerminatePod`?

Comment (mimowo) [reply pkg/kubelet/status/status_manager.go:903]: > What do you mean here by the other path? It seems to be that one of the surprises here is that within needsUpdate the pod (as fetched from pod manager) and status as passed to the function have different phase (i.e. the pod one is pending, the status is Failed).

I think it would also have a different phase on 1.26, can confirm. It is only in the `syncPod` that the `pod` object is updated based on the status after successful PATCH.

> Regarding the second part of the fix, why do we also need to consult the pod worker with m.podDeletionSafety.PodIsFinished? Is it because podIsFinished is never true because no-one ever called TerminatePod?

Yes, but `TerminatePod` wasn't called in 1.26, can double check.

**Comment by mimowo** [comment]
@bobbypage I would like to follow up with logs for this scenario.
Here is 1.26:
```
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.794570    1455 config.go:398] "Receiving a new pod" pod="default/ubuntu-sleep-2"
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.794704    1455 kubelet.go:2199] "SyncLoop ADD" source="api" pods="[kube-system/kube-proxy-clbzk default/ubuntu-sleep-2 kube-system/kindnet-rlbjw]"
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.795101    1455 predicate.go:129] "Predicate failed on Pod" pod="default/ubuntu-sleep-2" err="Predicate NodeAffinity failed"
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.795185    1455 event.go:294] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="NodeAffinity" message="Predicate NodeAffinity failed"
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.795504    1455 status_manager.go:552] "updateStatusInternal" version=1 pod="default/ubuntu-sleep-2" podUID=260a65aa-c6f3-442f-ae35-f792e5deb396 containers=""
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.795575    1455 status_manager.go:582] "Status Manager: adding pod with new status to podStatusChannel" pod="default/ubuntu-sleep-2" podUID=260a65aa-c6f3-442f-ae35-f792e5deb396 statusVersion=1 status={Phase:Failed Conditions:[] Message:Pod was rejected: Predicate NodeAffinity failed Reason:NodeAffinity NominatedNodeName: HostIP: PodIP: PodIPs:[] StartTime:2023-06-07 08:59:28 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[] QOSClass: EphemeralContainerStatuses:[]}
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.803309    1455 status_manager.go:186] "Status Manager: syncing pod with status from podStatusChannel" podUID=260a65aa-c6f3-442f-ae35-f792e5deb396 statusVersion=1 status={Phase:Failed Conditions:[] Message:Pod was rejected: Predicate NodeAffinity failed Reason:NodeAffinity NominatedNodeName: HostIP: PodIP: PodIPs:[] StartTime:2023-06-07 08:59:28 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[] QOSClass: EphemeralContainerStatuses:[]}
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.803353    1455 round_trippers.go:466] curl -v -XGET  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "User-Agent: kubelet/v1.26.4 (linux/amd64) kubernetes/f89670c" 'https://test1.26-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2'
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.805022    1455 round_trippers.go:553] GET https://test1.26-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2 200 OK in 1 milliseconds
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.805301    1455 request.go:1171] Request Body: {"metadata":{"uid":"260a65aa-c6f3-442f-ae35-f792e5deb396"},"status":{"qosClass":null,"startTime":"2023-06-07T08:59:28Z"}}
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.805336    1455 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubelet/v1.26.4 (linux/amd64) kubernetes/f89670c" 'https://test1.26-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2/status'
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.810962    1455 round_trippers.go:553] PATCH https://test1.26-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2/status 200 OK in 5 milliseconds
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.811374    1455 status_manager.go:719] "Patch status for pod" pod="default/ubuntu-sleep-2" podUID=260a65aa-c6f3-442f-ae35-f792e5deb396 patch="{\"metadata\":{\"uid\":\"260a65aa-c6f3-442f-ae35-f792e5deb396\"},\"status\":{\"qosClass\":null,\"startTime\":\"2023-06-07T08:59:28Z\"}}"
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.811417    1455 status_manager.go:728] "Status for pod updated successfully" pod="default/ubuntu-sleep-2" statusVersion=1 status={Phase:Pending Conditions:[] Message: Reason: NominatedNodeName: HostIP: PodIP: PodIPs:[] StartTime:2023-06-07 08:59:28 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[] QOSClass: EphemeralContainerStatuses:[]}
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.811445    1455 pod_startup_latency_tracker.go:162] "Mark when the pod was running for the first time" pod="default/ubuntu-sleep-2" rv="2739"
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.811460    1455 kubelet_pods.go:952] "Pod is terminated, but some containers are still running" pod="default/ubuntu-sleep-2"
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.811253    1455 kubelet.go:2212] "SyncLoop RECONCILE" source="api" pods="[default/ubuntu-sleep-2]"
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.904814    1455 projected.go:189] Setting up volume kube-api-access-g6knl for pod 260a65aa-c6f3-442f-ae35-f792e5deb396 at /var/lib/kubelet/pods/260a65aa-c6f3-442f-ae35-f792e5deb396/volumes/kubernetes.io~projected/kube-api-access-g6knl
Jun 07 08:59:28 test1.26-worker kubelet[1455]: 00000050  0e 75 62 75 6e 74 75 2d  73 6c 65 65 70 2d 32 22  |.ubuntu-sleep-2"|
Jun 07 08:59:28 test1.26-worker kubelet[1455]: E0607 08:59:28.997981    1455 projected.go:198] Error preparing data for projected volume kube-api-access-g6knl for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
Jun 07 08:59:28 test1.26-worker kubelet[1455]: I0607 08:59:28.998197    1455 event.go:294] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-api-access-g6knl\" : object \"default\"/\"kube-root-ca.crt\" not registered"
Jun 07 08:59:29 test1.26-worker kubelet[1455]: I0607 08:59:29.512179    1455 projected.go:189] Setting up volume kube-api-access-g6knl for pod 260a65aa-c6f3-442f-ae35-f792e5deb396 at /var/lib/kubelet/pods/260a65aa-c6f3-442f-ae35-f792e5deb396/volumes/kubernetes.io~projected/kube-api-access-g6knl
Jun 07 08:59:29 test1.26-worker kubelet[1455]: E0607 08:59:29.512262    1455 projected.go:198] Error preparing data for projected volume kube-api-access-g6knl for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
Jun 07 08:59:29 test1.26-worker kubelet[1455]: I0607 08:59:29.512407    1455 event.go:294] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-api-access-g6knl\" : object \"default\"/\"kube-root-ca.crt\" not registered"
Jun 07 08:59:29 test1.26-worker kubelet[1455]: I0607 08:59:29.512641    1455 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubelet/v1.26.4 (linux/amd64) kubernetes/f89670c" 'https://test1.26-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.176654d16fd5ec15'
Jun 07 08:59:29 test1.26-worker kubelet[1455]: I0607 08:59:29.517736    1455 round_trippers.go:553] PATCH https://test1.26-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.176654d16fd5ec15 200 OK in 5 milliseconds
Jun 07 08:59:30 test1.26-worker kubelet[1455]: I0607 08:59:30.518472    1455 projected.go:189] Setting up volume kube-api-access-g6knl for pod 260a65aa-c6f3-442f-ae35-f792e5deb396 at /var/lib/kubelet/pods/260a65aa-c6f3-442f-ae35-f792e5deb396/volumes/kubernetes.io~projected/kube-api-access-g6knl
Jun 07 08:59:30 test1.26-worker kubelet[1455]: E0607 08:59:30.518592    1455 projected.go:198] Error preparing data for projected volume kube-api-access-g6knl for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
Jun 07 08:59:30 test1.26-worker kubelet[1455]: I0607 08:59:30.518759    1455 event.go:294] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-api-access-g6knl\" : object \"default\"/\"kube-root-ca.crt\" not registered"
Jun 07 08:59:30 test1.26-worker kubelet[1455]: I0607 08:59:30.518904    1455 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubelet/v1.26.4 (linux/amd64) kubernetes/f89670c" 'https://test1.26-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.176654d16fd5ec15'
Jun 07 08:59:30 test1.26-worker kubelet[1455]: I0607 08:59:30.524768    1455 round_trippers.go:553] PATCH https://test1.26-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.176654d16fd5ec15 200 OK in 5 milliseconds
Jun 07 08:59:32 test1.26-worker kubelet[1455]: I0607 08:59:32.530778    1455 projected.go:189] Setting up volume kube-api-access-g6knl for pod 260a65aa-c6f3-442f-ae35-f792e5deb396 at /var/lib/kubelet/pods/260a65aa-c6f3-442f-ae35-f792e5deb396/volumes/kubernetes.io~projected/kube-api-access-g6knl
Jun 07 08:59:32 test1.26-worker kubelet[1455]: E0607 08:59:32.530864    1455 projected.go:198] Error preparing data for projected volume kube-api-access-g6knl for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
Jun 07 08:59:32 test1.26-worker kubelet[1455]: I0607 08:59:32.531030    1455 event.go:294] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-api-access-g6knl\" : object \"default\"/\"kube-root-ca.crt\" not registered"
Jun 07 08:59:32 test1.26-worker kubelet[1455]: I0607 08:59:32.531293    1455 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubelet/v1.26.4 (linux/amd64) kubernetes/f89670c" 'https://test1.26-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.176654d16fd5ec15'
Jun 07 08:59:32 test1.26-worker kubelet[1455]: I0607 08:59:32.536847    1455 round_trippers.go:553] PATCH https://test1.26-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.176654d16fd5ec15 200 OK in 5 milliseconds
Jun 07 08:59:36 test1.26-worker kubelet[1455]: I0607 08:59:36.555423    1455 projected.go:189] Setting up volume kube-api-access-g6knl for pod 260a65aa-c6f3-442f-ae35-f792e5deb396 at /var/lib/kubelet/pods/260a65aa-c6f3-442f-ae35-f792e5deb396/volumes/kubernetes.io~projected/kube-api-access-g6knl
Jun 07 08:59:36 test1.26-worker kubelet[1455]: E0607 08:59:36.555516    1455 projected.go:198] Error preparing data for projected volume kube-api-access-g6knl for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
Jun 07 08:59:36 test1.26-worker kubelet[1455]: I0607 08:59:36.555588    1455 event.go:294] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-api-access-g6knl\" : object \"default\"/\"kube-root-ca.crt\" not registered"
Jun 07 08:59:36 test1.26-worker kubelet[1455]: I0607 08:59:36.555925    1455 round_trippers.go:466] curl -v -XPATCH  -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubelet/v1.26.4 (linux/amd64) kubernetes/f89670c" -H "Accept: application/vnd.kubernetes.protobuf,application/json" 'https://test1.26-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.176654d16fd5ec15'
Jun 07 08:59:36 test1.26-worker kubelet[1455]: I0607 08:59:36.560194    1455 round_trippers.go:553] PATCH https://test1.26-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.176654d16fd5ec15 200 OK in 4 milliseconds
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.845334    1455 kubelet_getters.go:306] "Path does not exist" path="/var/lib/kubelet/pods/260a65aa-c6f3-442f-ae35-f792e5deb396/volumes"
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.845396    1455 kubelet_pods.go:978] "Pod is terminated and all resources are reclaimed" pod="default/ubuntu-sleep-2"
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.845408    1455 status_manager.go:675] "Status Manager: syncPod in syncbatch" podUID=260a65aa-c6f3-442f-ae35-f792e5deb396
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.845429    1455 kubelet_getters.go:306] "Path does not exist" path="/var/lib/kubelet/pods/260a65aa-c6f3-442f-ae35-f792e5deb396/volumes"
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.845457    1455 kubelet_pods.go:978] "Pod is terminated and all resources are reclaimed" pod="default/ubuntu-sleep-2"
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.845528    1455 round_trippers.go:466] curl -v -XGET  -H "User-Agent: kubelet/v1.26.4 (linux/amd64) kubernetes/f89670c" -H "Accept: application/vnd.kubernetes.protobuf,application/json" 'https://test1.26-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2'
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.847830    1455 round_trippers.go:553] GET https://test1.26-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2 200 OK in 2 milliseconds
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.848210    1455 request.go:1171] Request Body: {"metadata":{"uid":"260a65aa-c6f3-442f-ae35-f792e5deb396"},"status":{"message":"Pod was rejected: Predicate NodeAffinity failed","phase":"Failed","reason":"NodeAffinity"}}
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.848270    1455 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubelet/v1.26.4 (linux/amd64) kubernetes/f89670c" 'https://test1.26-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2/status'
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.852374    1455 round_trippers.go:553] PATCH https://test1.26-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2/status 200 OK in 4 milliseconds
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.852631    1455 status_manager.go:719] "Patch status for pod" pod="default/ubuntu-sleep-2" podUID=260a65aa-c6f3-442f-ae35-f792e5deb396 patch="{\"metadata\":{\"uid\":\"260a65aa-c6f3-442f-ae35-f792e5deb396\"},\"status\":{\"message\":\"Pod was rejected: Predicate NodeAffinity failed\",\"phase\":\"Failed\",\"reason\":\"NodeAffinity\"}}"
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.852672    1455 status_manager.go:728] "Status for pod updated successfully" pod="default/ubuntu-sleep-2" statusVersion=1 status={Phase:Failed Conditions:[] Message:Pod was rejected: Predicate NodeAffinity failed Reason:NodeAffinity NominatedNodeName: HostIP: PodIP: PodIPs:[] StartTime:2023-06-07 08:59:28 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[] QOSClass: EphemeralContainerStatuses:[]}
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.852723    1455 kubelet.go:2212] "SyncLoop RECONCILE" source="api" pods="[default/ubuntu-sleep-2]"
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.852738    1455 kubelet_getters.go:306] "Path does not exist" path="/var/lib/kubelet/pods/260a65aa-c6f3-442f-ae35-f792e5deb396/volumes"
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.852793    1455 kubelet_pods.go:978] "Pod is terminated and all resources are reclaimed" pod="default/ubuntu-sleep-2"
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.852889    1455 round_trippers.go:466] curl -v -XDELETE  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/vnd.kubernetes.protobuf" -H "User-Agent: kubelet/v1.26.4 (linux/amd64) kubernetes/f89670c" 'https://test1.26-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2'
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.859585    1455 kubelet.go:2215] "SyncLoop DELETE" source="api" pods="[default/ubuntu-sleep-2]"
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.859614    1455 pod_workers.go:585] "Pod is being synced for the first time" pod="default/ubuntu-sleep-2" podUID=260a65aa-c6f3-442f-ae35-f792e5deb396
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.859635    1455 pod_workers.go:625] "Pod is finished processing, no further updates" pod="default/ubuntu-sleep-2" podUID=260a65aa-c6f3-442f-ae35-f792e5deb396
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.862325    1455 round_trippers.go:553] DELETE https://test1.26-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2 200 OK in 9 milliseconds
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.862495    1455 kubelet.go:2209] "SyncLoop REMOVE" source="api" pods="[default/ubuntu-sleep-2]"
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.862528    1455 kubelet.go:2054] "Pod has been deleted and must be killed" pod="default/ubuntu-sleep-2" podUID=260a65aa-c6f3-442f-ae35-f792e5deb396
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.862544    1455 pod_workers.go:625] "Pod is finished processing, no further updates" pod="default/ubuntu-sleep-2" podUID=260a65aa-c6f3-442f-ae35-f792e5deb396
Jun 07 08:59:37 test1.26-worker kubelet[1455]: I0607 08:59:37.862622    1455 status_manager.go:757] "Pod fully terminated and removed from etcd" pod="default/ubuntu-sleep-2"
Jun 07 08:59:39 test1.26-worker kubelet[1455]: I0607 08:59:39.846698    1455 pod_workers.go:1272] "Pod has been terminated and is no longer known to the kubelet, remove all history" podUID=260a65aa-c6f3-442f-ae35-f792e5deb396
```
1.27.2 (broken):
```
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.224528     846 config.go:398] "Receiving a new pod" pod="default/ubuntu-sleep-2"
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.225204     846 kubelet.go:2343] "SyncLoop ADD" source="api" pods=[default/ubuntu-sleep-2 kube-system/kindnet-m42bp kube-system/kube-proxy-4r2vk]
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.225719     846 predicate.go:129] "Predicate failed on Pod" pod="default/ubuntu-sleep-2" err="Predicate NodeAffinity failed"
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.225748     846 status_manager.go:643] "updateStatusInternal" version=1 podIsFinished=false pod="default/ubuntu-sleep-2" podUID=4d0d06af-0a5d-4b03-8262-9fe8d1ec5aea containers=""
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.225897     846 event.go:307] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="NodeAffinity" message="Predicate NodeAffinity failed"
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.225894     846 round_trippers.go:466] curl -v -XGET  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "User-Agent: kubelet/v1.27.2 (linux/amd64) kubernetes/7f6f68f" 'https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2'
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.228108     846 round_trippers.go:553] GET https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2 200 OK in 2 milliseconds
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.229739     846 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubelet/v1.27.2 (linux/amd64) kubernetes/7f6f68f" 'https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2/status'
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.235162     846 round_trippers.go:553] PATCH https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2/status 200 OK in 5 milliseconds
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.235408     846 status_manager.go:830] "Patch status for pod" pod="default/ubuntu-sleep-2" podUID=4d0d06af-0a5d-4b03-8262-9fe8d1ec5aea patch="{\"metadata\":{\"uid\":\"4d0d06af-0a5d-4b03-8262-9fe8d1ec5aea\"},\"status\":{\"qosClass\":null,\"startTime\":\"2023-06-07T09:11:45Z\"}}"
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.235441     846 status_manager.go:839] "Status for pod updated successfully" pod="default/ubuntu-sleep-2" statusVersion=1 status={Phase:Pending Conditions:[] Message: Reason: NominatedNodeName: HostIP: PodIP: PodIPs:[] StartTime:2023-06-07 09:11:45 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[] QOSClass: EphemeralContainerStatuses:[] Resize:}
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.235459     846 pod_startup_latency_tracker.go:162] "Mark when the pod was running for the first time" pod="default/ubuntu-sleep-2" rv="917"
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.235470     846 status_manager.go:893] "Delaying pod deletion as the phase is non-terminal" phase=Failed pod="default/ubuntu-sleep-2" podUID=4d0d06af-0a5d-4b03-8262-9fe8d1ec5aea
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.235528     846 pod_startup_latency_tracker.go:102] "Observed pod startup duration" pod="default/ubuntu-sleep-2" podStartSLOduration=190.235498076 podCreationTimestamp="2023-06-07 09:08:35 +0000 UTC" firstStartedPulling="0001-01-01 00:00:00 +0000 UTC" lastFinishedPulling="0001-01-01 00:00:00 +0000 UTC" observedRunningTime="2023-06-07 09:11:45.235463526 +0000 UTC m=+1.087148444" watchObservedRunningTime="2023-06-07 09:11:45.235498076 +0000 UTC m=+1.087182994"
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.235688     846 kubelet.go:2356] "SyncLoop RECONCILE" source="api" pods=[default/ubuntu-sleep-2]
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: 00000050  0e 75 62 75 6e 74 75 2d  73 6c 65 65 70 2d 32 22  |.ubuntu-sleep-2"|
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: E0607 09:11:45.438549     846 projected.go:198] Error preparing data for projected volume kube-api-access-cl6z6 for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
Jun 07 09:11:45 test1.27-bad-worker kubelet[846]: I0607 09:11:45.438790     846 event.go:307] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-api-access-cl6z6\" : object \"default\"/\"kube-root-ca.crt\" not registered"
Jun 07 09:11:46 test1.27-bad-worker kubelet[846]: E0607 09:11:46.036954     846 projected.go:198] Error preparing data for projected volume kube-api-access-cl6z6 for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
Jun 07 09:11:46 test1.27-bad-worker kubelet[846]: I0607 09:11:46.037095     846 event.go:307] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-api-access-cl6z6\" : object \"default\"/\"kube-root-ca.crt\" not registered"
Jun 07 09:11:46 test1.27-bad-worker kubelet[846]: I0607 09:11:46.037265     846 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubelet/v1.27.2 (linux/amd64) kubernetes/7f6f68f" 'https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766557ce71e6a78'
Jun 07 09:11:46 test1.27-bad-worker kubelet[846]: I0607 09:11:46.042545     846 round_trippers.go:553] PATCH https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766557ce71e6a78 200 OK in 5 milliseconds
Jun 07 09:11:47 test1.27-bad-worker kubelet[846]: E0607 09:11:47.042696     846 projected.go:198] Error preparing data for projected volume kube-api-access-cl6z6 for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
Jun 07 09:11:47 test1.27-bad-worker kubelet[846]: I0607 09:11:47.042859     846 event.go:307] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-api-access-cl6z6\" : object \"default\"/\"kube-root-ca.crt\" not registered"
Jun 07 09:11:47 test1.27-bad-worker kubelet[846]: I0607 09:11:47.042968     846 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubelet/v1.27.2 (linux/amd64) kubernetes/7f6f68f" 'https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766557ce71e6a78'
Jun 07 09:11:47 test1.27-bad-worker kubelet[846]: I0607 09:11:47.048990     846 round_trippers.go:553] PATCH https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766557ce71e6a78 200 OK in 5 milliseconds
Jun 07 09:11:49 test1.27-bad-worker kubelet[846]: E0607 09:11:49.054711     846 projected.go:198] Error preparing data for projected volume kube-api-access-cl6z6 for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
Jun 07 09:11:49 test1.27-bad-worker kubelet[846]: I0607 09:11:49.054852     846 event.go:307] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-api-access-cl6z6\" : object \"default\"/\"kube-root-ca.crt\" not registered"
Jun 07 09:11:49 test1.27-bad-worker kubelet[846]: I0607 09:11:49.054957     846 round_trippers.go:466] curl -v -XPATCH  -H "Content-Type: application/strategic-merge-patch+json" -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "User-Agent: kubelet/v1.27.2 (linux/amd64) kubernetes/7f6f68f" 'https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766557ce71e6a78'
Jun 07 09:11:49 test1.27-bad-worker kubelet[846]: I0607 09:11:49.062608     846 round_trippers.go:553] PATCH https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766557ce71e6a78 200 OK in 7 milliseconds
Jun 07 09:11:53 test1.27-bad-worker kubelet[846]: E0607 09:11:53.078734     846 projected.go:198] Error preparing data for projected volume kube-api-access-cl6z6 for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
Jun 07 09:11:53 test1.27-bad-worker kubelet[846]: I0607 09:11:53.078883     846 event.go:307] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-api-access-cl6z6\" : object \"default\"/\"kube-root-ca.crt\" not registered"
Jun 07 09:11:53 test1.27-bad-worker kubelet[846]: I0607 09:11:53.079014     846 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubelet/v1.27.2 (linux/amd64) kubernetes/7f6f68f" 'https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766557ce71e6a78'
Jun 07 09:11:53 test1.27-bad-worker kubelet[846]: I0607 09:11:53.087478     846 round_trippers.go:553] PATCH https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766557ce71e6a78 200 OK in 8 milliseconds
Jun 07 09:11:54 test1.27-bad-worker kubelet[846]: I0607 09:11:54.236588     846 status_manager.go:893] "Delaying pod deletion as the phase is non-terminal" phase=Failed pod="default/ubuntu-sleep-2" podUID=4d0d06af-0a5d-4b03-8262-9fe8d1ec5aea
Jun 07 09:11:54 test1.27-bad-worker kubelet[846]: I0607 09:11:54.237128     846 status_manager.go:938] "Pod status is inconsistent with cached status for pod, a reconciliation should be triggered" pod="default/ubuntu-sleep-2" statusDiff=<
Jun 07 09:11:54 test1.27-bad-worker kubelet[846]: I0607 09:11:54.237271     846 round_trippers.go:466] curl -v -XGET  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "User-Agent: kubelet/v1.27.2 (linux/amd64) kubernetes/7f6f68f" 'https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2'
Jun 07 09:11:54 test1.27-bad-worker kubelet[846]: I0607 09:11:54.240236     846 round_trippers.go:553] GET https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2 200 OK in 2 milliseconds
Jun 07 09:11:54 test1.27-bad-worker kubelet[846]: I0607 09:11:54.240805     846 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubelet/v1.27.2 (linux/amd64) kubernetes/7f6f68f" 'https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2/status'
Jun 07 09:11:54 test1.27-bad-worker kubelet[846]: I0607 09:11:54.246179     846 round_trippers.go:553] PATCH https://test1.27-bad-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2/status 200 OK in 5 milliseconds
Jun 07 09:11:54 test1.27-bad-worker kubelet[846]: I0607 09:11:54.246469     846 status_manager.go:830] "Patch status for pod" pod="default/ubuntu-sleep-2" podUID=4d0d06af-0a5d-4b03-8262-9fe8d1ec5aea patch="{\"metadata\":{\"uid\":\"4d0d06af-0a5d-4b03-8262-9fe8d1ec5aea\"},\"status\":{\"message\":\"Pod was rejected: Predicate NodeAffinity failed\",\"phase\":\"Failed\",\"reason\":\"NodeAffinity\"}}"
Jun 07 09:11:54 test1.27-bad-worker kubelet[846]: I0607 09:11:54.246499     846 status_manager.go:839] "Status for pod updated successfully" pod="default/ubuntu-sleep-2" statusVersion=1 status={Phase:Failed Conditions:[] Message:Pod was rejected: Predicate NodeAffinity failed Reason:NodeAffinity NominatedNodeName: HostIP: PodIP: PodIPs:[] StartTime:2023-06-07 09:11:45 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[] QOSClass: EphemeralContainerStatuses:[] Resize:}
Jun 07 09:11:54 test1.27-bad-worker kubelet[846]: I0607 09:11:54.246548     846 kubelet.go:2356] "SyncLoop RECONCILE" source="api" pods=[default/ubuntu-sleep-2]
```
1.27 proposed fix:
```
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.158702     825 config.go:398] "Receiving a new pod" pod="default/ubuntu-sleep-2"
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.158813     825 kubelet.go:2409] "SyncLoop ADD" source="api" pods=["default/ubuntu-sleep-2","kube-system/kindnet-2lhld","kube-system/kube-proxy-5tdcv"]
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.159122     825 predicate.go:129] "Predicate failed on Pod" pod="default/ubuntu-sleep-2" err="Predicate NodeAffinity failed"
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.159158     825 status_manager.go:654] "updateStatusInternal" version=1 podIsFinished=false pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e" containers=""
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.159242     825 event.go:307] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="NodeAffinity" message="Predicate NodeAffinity failed"
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.159291     825 round_trippers.go:466] curl -v -XGET  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "User-Agent: kubelet/v1.28.0 (linux/amd64) kubernetes/e674ca2" 'https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2'
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.161378     825 round_trippers.go:553] GET https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2 200 OK in 2 milliseconds
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.163374     825 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubelet/v1.28.0 (linux/amd64) kubernetes/e674ca2" 'https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2/status'
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.167436     825 round_trippers.go:553] PATCH https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2/status 200 OK in 4 milliseconds
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.167574     825 kubelet.go:2422] "SyncLoop RECONCILE" source="api" pods=["default/ubuntu-sleep-2"]
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.167762     825 status_manager.go:841] "Patch status for pod" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e" patch="{\"metadata\":{\"uid\":\"12eee496-a525-4d3f-bc32-c4b6e022200e\"},\"status\":{\"qosClass\":null,\"startTime\":\"2023-06-07T09:28:58Z\"}}"
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.167788     825 status_manager.go:850] "Status for pod updated successfully" pod="default/ubuntu-sleep-2" statusVersion=1 status={"phase":"Pending","startTime":"2023-06-07T09:28:58Z"}
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.167812     825 pod_startup_latency_tracker.go:162] "Mark when the pod was running for the first time" pod="default/ubuntu-sleep-2" rv="711"
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: 00000050  0e 75 62 75 6e 74 75 2d  73 6c 65 65 70 2d 32 22  |.ubuntu-sleep-2"|
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: E0607 09:28:58.284210     825 projected.go:198] Error preparing data for projected volume kube-api-access-8st28 for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.284388     825 event.go:307] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-api-access-8st28\" : object \"default\"/\"kube-root-ca.crt\" not registered"
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: E0607 09:28:58.880848     825 projected.go:198] Error preparing data for projected volume kube-api-access-8st28 for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.881087     825 event.go:307] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-api-access-8st28\" : object \"default\"/\"kube-root-ca.crt\" not registered"
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.881454     825 round_trippers.go:466] curl -v -XPATCH  -H "Content-Type: application/strategic-merge-patch+json" -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "User-Agent: kubelet/v1.28.0 (linux/amd64) kubernetes/e674ca2" 'https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766566d61830059'
Jun 07 09:28:58 test1.27-fix-worker kubelet[825]: I0607 09:28:58.886624     825 round_trippers.go:553] PATCH https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766566d61830059 200 OK in 5 milliseconds
Jun 07 09:28:59 test1.27-fix-worker kubelet[825]: E0607 09:28:59.886809     825 projected.go:198] Error preparing data for projected volume kube-api-access-8st28 for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
Jun 07 09:28:59 test1.27-fix-worker kubelet[825]: I0607 09:28:59.887010     825 event.go:307] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-api-access-8st28\" : object \"default\"/\"kube-root-ca.crt\" not registered"
Jun 07 09:28:59 test1.27-fix-worker kubelet[825]: I0607 09:28:59.887112     825 round_trippers.go:466] curl -v -XPATCH  -H "User-Agent: kubelet/v1.28.0 (linux/amd64) kubernetes/e674ca2" -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/strategic-merge-patch+json" 'https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766566d61830059'
Jun 07 09:28:59 test1.27-fix-worker kubelet[825]: I0607 09:28:59.894713     825 round_trippers.go:553] PATCH https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766566d61830059 200 OK in 7 milliseconds
Jun 07 09:29:01 test1.27-fix-worker kubelet[825]: E0607 09:29:01.898322     825 projected.go:198] Error preparing data for projected volume kube-api-access-8st28 for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
Jun 07 09:29:01 test1.27-fix-worker kubelet[825]: I0607 09:29:01.898397     825 event.go:307] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-api-access-8st28\" : object \"default\"/\"kube-root-ca.crt\" not registered"
Jun 07 09:29:01 test1.27-fix-worker kubelet[825]: I0607 09:29:01.898576     825 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubelet/v1.28.0 (linux/amd64) kubernetes/e674ca2" 'https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766566d61830059'
Jun 07 09:29:01 test1.27-fix-worker kubelet[825]: I0607 09:29:01.903395     825 round_trippers.go:553] PATCH https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766566d61830059 200 OK in 4 milliseconds
Jun 07 09:29:05 test1.27-fix-worker kubelet[825]: E0607 09:29:05.919908     825 projected.go:198] Error preparing data for projected volume kube-api-access-8st28 for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
Jun 07 09:29:05 test1.27-fix-worker kubelet[825]: I0607 09:29:05.920089     825 event.go:307] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="FailedMount" message="MountVolume.SetUp failed for volume \"kube-api-access-8st28\" : object \"default\"/\"kube-root-ca.crt\" not registered"
Jun 07 09:29:05 test1.27-fix-worker kubelet[825]: I0607 09:29:05.920222     825 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubelet/v1.28.0 (linux/amd64) kubernetes/e674ca2" 'https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766566d61830059'
Jun 07 09:29:05 test1.27-fix-worker kubelet[825]: I0607 09:29:05.927101     825 round_trippers.go:553] PATCH https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/events/ubuntu-sleep-2.1766566d61830059 200 OK in 6 milliseconds
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.179054     825 status_manager.go:909] "The pod termination is finished as SyncTerminatedPod completes its execution" phase="Failed" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.179271     825 round_trippers.go:466] curl -v -XGET  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "User-Agent: kubelet/v1.28.0 (linux/amd64) kubernetes/e674ca2" 'https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2'
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.181888     825 round_trippers.go:553] GET https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2 200 OK in 2 milliseconds
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.182389     825 round_trippers.go:466] curl -v -XPATCH  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/strategic-merge-patch+json" -H "User-Agent: kubelet/v1.28.0 (linux/amd64) kubernetes/e674ca2" 'https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2/status'
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.189478     825 round_trippers.go:553] PATCH https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2/status 200 OK in 7 milliseconds
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.189723     825 kubelet.go:2422] "SyncLoop RECONCILE" source="api" pods=["default/ubuntu-sleep-2"]
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.189992     825 status_manager.go:841] "Patch status for pod" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e" patch="{\"metadata\":{\"uid\":\"12eee496-a525-4d3f-bc32-c4b6e022200e\"},\"status\":{\"message\":\"Pod was rejected: Predicate NodeAffinity failed\",\"phase\":\"Failed\",\"reason\":\"NodeAffinity\"}}"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.190041     825 status_manager.go:850] "Status for pod updated successfully" pod="default/ubuntu-sleep-2" statusVersion=1 status={"phase":"Failed","message":"Pod was rejected: Predicate NodeAffinity failed","reason":"NodeAffinity","startTime":"2023-06-07T09:28:58Z"}
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.190064     825 status_manager.go:909] "The pod termination is finished as SyncTerminatedPod completes its execution" phase="Failed" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.190177     825 round_trippers.go:466] curl -v -XDELETE  -H "Accept: application/vnd.kubernetes.protobuf,application/json" -H "Content-Type: application/vnd.kubernetes.protobuf" -H "User-Agent: kubelet/v1.28.0 (linux/amd64) kubernetes/e674ca2" 'https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2'
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.193812     825 kubelet.go:2425] "SyncLoop DELETE" source="api" pods=["default/ubuntu-sleep-2"]
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.193830     825 pod_workers.go:770] "Pod is being synced for the first time" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e" updateType="update"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.193842     825 pod_workers.go:965] "Notifying pod of pending update" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e" workType="terminated"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.193858     825 pod_workers.go:1232] "Processing pod event" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e" updateType="terminated"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.193881     825 kubelet.go:2135] "SyncTerminatedPod enter" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.193890     825 kubelet_pods.go:1535] "Generating pod status" podIsTerminal=true pod="default/ubuntu-sleep-2"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.193921     825 kubelet_pods.go:1548] "Got phase for pod" pod="default/ubuntu-sleep-2" oldPhase="Failed" phase="Pending"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.193927     825 kubelet_pods.go:1555] "Status manager phase was terminal, updating phase to match" pod="default/ubuntu-sleep-2" phase="Failed"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.193959     825 status_manager.go:654] "updateStatusInternal" version=2 podIsFinished=false pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e" containers="(ubuntu state=waiting previous=<none>)"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.193973     825 volume_manager.go:451] "Waiting for volumes to unmount for pod" pod="default/ubuntu-sleep-2"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.193996     825 volume_manager.go:480] "All volumes are unmounted for pod" pod="default/ubuntu-sleep-2"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.194003     825 kubelet.go:2149] "Pod termination unmounted volumes" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.194060     825 kubelet.go:2163] "Pod termination cleaned up volume paths" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.195154     825 kubelet.go:2185] "Pod termination removed cgroups" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.195186     825 status_manager.go:490] "TerminatePod calling updateStatusInternal" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.195210     825 status_manager.go:654] "updateStatusInternal" version=3 podIsFinished=true pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e" containers="(ubuntu state=terminated=137 previous=<none>)"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.195232     825 kubelet.go:2192] "Pod is terminated and will need no more status updates" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.195242     825 kubelet.go:2194] "SyncTerminatedPod exit" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.195265     825 pod_workers.go:1308] "Processing pod event done" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e" updateType="terminated"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.197008     825 round_trippers.go:553] DELETE https://test1.27-fix-control-plane:6443/api/v1/namespaces/default/pods/ubuntu-sleep-2 200 OK in 6 milliseconds
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.197155     825 kubelet.go:2419] "SyncLoop REMOVE" source="api" pods=["default/ubuntu-sleep-2"]
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.197208     825 kubelet.go:2248] "Pod has been deleted and must be killed" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.197241     825 pod_workers.go:842] "Pod is finished processing, no further updates" pod="default/ubuntu-sleep-2" podUID="12eee496-a525-4d3f-bc32-c4b6e022200e" updateType="kill"
Jun 07 09:29:07 test1.27-fix-worker kubelet[825]: I0607 09:29:07.197546     825 status_manager.go:879] "Pod fully terminated and removed from etcd" pod="default/ubuntu-sleep-2"
```

File: test/e2e_node/restart_test.go [hunk 2]
```diff
@@ -381,6 +381,69 @@ var _ = SIGDescribe("Restart [Serial] [Slow] [Disruptive]", func() {
...
+					Containers: []v1.Container{
+						{
+							Name:  podName,
+							Image: imageutils.GetPauseImageName(),
+						},
+					},
+				},
+			})
+			ginkgo.By("Stopping the kubelet")
+			startKubelet := stopKubelet()
```
Comment (SergeyKanzhelev) [inline test/e2e_node/restart_test.go:410]: cc: @ffromani @swatisehgal 

Since you are looking at kubelet restart scenarios.

I remember there were issues when kubelet would keep restarting by itself so we were not able to rely on the period of time without kubelet running. I don't remember details, hoping you might

**Comment by mimowo** [comment]
I had a chat with @bobbypage over the issue and PR. Here answering some of the questions from the meeting:

1. Isn’t podManager updated with `pod.Status.Phase=Failed`, so that on the next `syncBatch` we pass this awkward [check](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go#L901-L904), and delete can proceed?

Pod manager is indeed updated after the successful patch in `SyncLoop UPDATE`. So in the next `syncBatch` indeed we have `status.status.Phase=pod.Status.Phase=Failed`. However, `podIsFinished` is `false` in this case. Thus, the method `needsUpdate` returns what `canBeDeleted` returns, which returns `false` here: https://github.com/kubernetes/kubernetes/blob/0330fd91f4f49505c34ca32558b2ddad2635eb68/pkg/kubelet/status/status_manager.go#L910.

2. Why in the proposed fixed version `syncTerminatedPod` is invoked?

Because after the successful `PATCH` (setting the phase as Failed) we get `canBeDeleted` returns `true` (after consulting pod workers). So we invoke the DELETE: 
 https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go#L872.
 
 t triggers the `SyncLoop DELETE`: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2425-L2427. 
 
This in turn triggers the pod_workers `UpdatePod`, which schedules a new `syncTerminatedPod` as `finished: false` is set in this path since https://github.com/kubernetes/kubernetes/pull/117019 . This also explains the difference with 1.26.

**Comment by smarterclayton** [comment]
Is there a succinct summary of the series of operations that prevents SyncTerminatedPod from running?

**Comment by smarterclayton** [comment]
I'm seeing some comments in the thread that I wasn't certain of:

If the kubelet restarts and the pod fails admission this time around, the pod is still actually running, which means we should probably treat it as a runtime pod (terminate as fast as possible).  is that not happening?

File: pkg/kubelet/status/status_manager.go [hunk 3]
```diff
@@ -898,12 +900,12 @@ func (m *manager) canBeDeleted(pod *v1.Pod, status v1.PodStatus, podIsFinished b
...
 		klog.V(3).InfoS("Delaying pod deletion as the phase is non-terminal", "phase", status.Phase, "pod", klog.KObj(pod), "podUID", pod.UID)
 		return false
 	}
 	// If this is an update completing pod termination then we know the pod termination is finished.
-	if podIsFinished {
+	if podIsFinished || m.podDeletionSafety.PodIsFinished(pod) {
```
Comment (smarterclayton) [inline pkg/kubelet/status/status_manager.go:908]: Is there a place in status_manager_test to add a scenario driven unit test for this?  Would more clearly describe the issue.

File: pkg/kubelet/status/status_manager.go (hunk 1 above)
Comment (smarterclayton) [reply pkg/kubelet/status/status_manager.go:903]: Pod worker is authoritative for what the status of the pod is "if the kubelet was the one who started it".  After a restart, the apiserver / runtime are sources of truth for what the status of the pod is.  So the phase on the pod object passed to pod worker isn't really "truth".

We should be calling terminatepod on pods that can never run now but may have run before (i.e. killing the pod).  Only if we are 100% certain the pod could never have been run should we bypass the pod worker (and even then it is problematic).

**Comment by bobbypage** [comment]
@smarterclayton 

> Is there a succinct summary of the series of operations that prevents SyncTerminatedPod from running?

`SyncTerminatedPod` because this a new pod that is rejected at kubelet admission time. Since it rejected at kubelet admission time, there is no pod worker driving it. 

> Or is this a net new pod that comes in that should be deleted? If it's the latter, we may still have to ensure the solution fixes the former (because that can also happen due to changing kubelet flags, devices, etc)

This is addressing the second case, this is a new pod that comes in that kubelet sees for the first time after it is started. When kubelet first sees the pod, the pod already has a deletion timestamp set. The pod is rejected in kubelet admission time, but no-one ended up calling `TerminatePod` on it, so the status manager isn't allowed to delete the pod.

File: pkg/kubelet/status/status_manager.go (hunk 1 above)
Comment (bobbypage) [reply pkg/kubelet/status/status_manager.go:903]: That makes sense, I think one of the root issues in https://github.com/kubernetes/kubernetes/issues/118472 is that the pod was never admitted in the first place and is rejected by kubelet so it never ran. However, we never called `TerminatePod` on it, so it is blocking status manager to delete it.

I'm trying out an alternative approach of simply calling `TerminatePod` for pods rejected at kubelet admission time in https://github.com/kubernetes/kubernetes/pull/118599. Would be great @smarterclayton and @mimowo  feedback on that approach.

Comment (bobbypage) [reply pkg/kubelet/status/status_manager.go:903]: I was thinking about an alternative approach where we call `TerminatePod` if the pod is rejected at kubelet admission time.  I have a WIP here - https://github.com/kubernetes/kubernetes/pull/118599, would be great to both of your feedback.

Comment (mimowo) [reply pkg/kubelet/status/status_manager.go]: Pushed a commit to eliminate the spurious check.

File: pkg/kubelet/status/status_manager.go (hunk 3 above)
Comment (mimowo) [reply pkg/kubelet/status/status_manager.go:903]: not currently, but I have added a preliminary `TestSyncPodForDeletedPodThatIsNeverStartedByPodWorkers`. It mocks up the `podDeletionSafetyProvider.PodIsFinished` (but `NeverStarted` would be enough in this scenario).

**Comment by mimowo** [comment]
@bobbypage @smarterclayton modified the PR to use HandlePodCleanups. It is more code than the alternative approaches, but gives more control.

File: test/e2e_node/restart_test.go [hunk 4]
```diff
@@ -381,6 +381,146 @@ var _ = SIGDescribe("Restart [Serial] [Slow] [Disruptive]", func() {
...
+					},
+				},
+			})
+
+			ginkgo.By(fmt.Sprintf("Adding node label for node (%v) to allow admission of pod (%v/%v)", nodeName, f.Namespace.Name, podName))
+			e2enode.AddOrUpdateLabelOnNode(f.ClientSet, nodeName, nodeLabelKey, nodeLabelValueRequired)
+			ginkgo.DeferCleanup(func() { e2enode.RemoveLabelOffNode(f.ClientSet, nodeName, nodeLabelKey) })
+
+			// Create the pod bound to the node. It will remain in the Pending
+			// phase as Kubelet is down.
```
Comment (bobbypage) [inline test/e2e_node/restart_test.go:480]: This comment seems incorrect (maybe copied from the last test?) - the kubelet only is stopped after.

File: pkg/kubelet/status/status_manager.go [hunk 5]
```diff
@@ -899,12 +899,12 @@ func (m *manager) canBeDeleted(pod *v1.Pod, status v1.PodStatus, podIsFinished b
 	}
 	// Delay deletion of pods until the phase is terminal.
 	if !podutil.IsPodPhaseTerminal(pod.Status.Phase) {
-		klog.V(3).InfoS("Delaying pod deletion as the phase is non-terminal", "phase", status.Phase, "pod", klog.KObj(pod), "podUID", pod.UID)
+		klog.V(3).InfoS("Delaying pod deletion as the phase is non-terminal", "phase", pod.Status.Phase, "cachedPhase", status.Phase, "pod", klog.KObj(pod), "podUID", pod.UID)
```
Comment (bobbypage) [inline pkg/kubelet/status/status_manager.go:902]: It might be worth to add a godoc comment to this method to explain the difference between pod.Status and status (and where each ones comes from). i.e. pod.Status is coming from the pod manager (so desired state), while status is the kubelet local status.

File: pkg/kubelet/kubelet_pods.go [hunk 6]
```diff
@@ -1173,6 +1173,15 @@ func (kl *Kubelet) HandlePodCleanups(ctx context.Context) error {
 	metrics.RestartedPodTotal.WithLabelValues("true").Add(float64(restartCountStatic))
 	metrics.RestartedPodTotal.WithLabelValues("").Add(float64(restartCount))
 
+	// Complete termination of deleted pods that are not runtime pods (don't have
+	// running containers), are terminal, but are not known to pod workers.
```
Comment (bobbypage) [inline pkg/kubelet/kubelet_pods.go:1177]: s/but/and are not known

File: pkg/kubelet/kubelet_pods.go [hunk 7]
```diff
@@ -1173,6 +1173,15 @@ func (kl *Kubelet) HandlePodCleanups(ctx context.Context) error {
...
+	// The example is rejected pods. Triggering TerminatePod allows to proceed
```
Comment (bobbypage) [inline pkg/kubelet/kubelet_pods.go:1178]: An example is pods rejected during kubelet admission that have never started before (i.e. do not have an orphaned pod).

File: pkg/kubelet/kubelet_pods.go [hunk 8]
```diff
@@ -1245,6 +1254,36 @@ func (kl *Kubelet) HandlePodCleanups(ctx context.Context) error {
...
 }
 
+// Filters terminal pods with deletion timestamp which are not runtime pods
+func (kl *Kubelet) filterTerminalPodsToDelete(allPods []*v1.Pod, runningRuntimePods []*kubecontainer.Pod, workingPods map[types.UID]PodWorkerSync) map[types.UID]*v1.Pod {
+	terminalPodsToDelete := make(map[types.UID]*v1.Pod)
+	for _, pod := range allPods {
+		if pod.DeletionTimestamp == nil {
+			// skip pods which don't have a deletion timestamp
+			continue
+		}
```
Comment (bobbypage) [inline pkg/kubelet/kubelet_pods.go:1264]: Technically, we already have this check in canBeDeleted - https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go#L897-L899.

However, if we remove this check here, we may trigger calling `TerminatePod` multiple times for pods that don't have a deletion timestamp set. And it looks like we pass `forceUpdate=true` here [1], so we will always construct a new status. So I suppose it does make sense to keep this check here unless we want refactor `TerminatePod` to short circuit if there is no update, but that is a more invasive change.

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/status/status_manager.go#L489

**Comment by bobbypage** [comment]
Thanks for updating the PR with the HandlePodCleanups approach! A few small comments, but largely LGTM, thank you for adding the two regression tests to verify the behavior.

File: test/e2e_node/restart_test.go (hunk 2 above)
Comment (ffromani) [reply test/e2e_node/restart_test.go:410]: I'm trying to think but I can't remember anything major lately

File: pkg/kubelet/status/status_manager.go (hunk 1 above)
Comment (mimowo) [reply pkg/kubelet/status/status_manager.go]: Marking as resolved as this is outdated code change, as the current approach (of using HandlePodCleanups) does not modify this.

File: pkg/kubelet/status/status_manager.go (hunk 3 above)
Comment (mimowo) [reply pkg/kubelet/status/status_manager.go]: Marking as resolved as this is outdated code change, as the current approach (of using HandlePodCleanups) does not modify this.

File: test/e2e_node/restart_test.go (hunk 4 above)
Comment (mimowo) [reply test/e2e_node/restart_test.go:480]: Yes, cleaned up

File: pkg/kubelet/kubelet_pods.go (hunk 6 above)
Comment (mimowo) [reply pkg/kubelet/kubelet_pods.go]: Done

File: pkg/kubelet/kubelet_pods.go (hunk 7 above)
Comment (mimowo) [reply pkg/kubelet/kubelet_pods.go]: Used the text :)

File: pkg/kubelet/kubelet_pods.go (hunk 8 above)
Comment (mimowo) [reply pkg/kubelet/kubelet_pods.go:1265]: Yes, the idea is to avoid calling `TerminatePod` repeatedly without end (pod deletion). Still, it is possible that `TerminatePod` is called multiple times before the pod is deleted (if the deletion takes long, but this operation should generally be very fast).

File: pkg/kubelet/status/status_manager.go (hunk 5 above)
Comment (mimowo) [reply pkg/kubelet/status/status_manager.go]: I have inlined the comments next to the check and the log.

**Comment by mimowo** [comment]
> Thanks for updating the PR with the HandlePodCleanups approach! A few small comments, but largely LGTM, thank you for adding the two regression tests to verify the behavior.

@bobbypage thanks for reviewing, PTAL.

**Comment by mimowo** [comment]
@smarterclayton @bobbypage please continue with the review.

File: pkg/kubelet/kubelet_pods.go (hunk 8 above)
Comment (bobbypage) [reply pkg/kubelet/kubelet_pods.go:1265]: ack, that makes sense. Even if the termination takes longer, TerminatePod is re-entrant, so it should be fine.

**Comment by bobbypage** [comment]
LGTM from my side, thank you for adding the tests and iterating through multiple possible solutions. LGTM from my side

/lgtm

**Comment by bobbypage** [comment]
It would be great to @smarterclayton review here, Clayton can you please take a look and review this fix? Thank you!

/assign @smarterclayton

File: pkg/kubelet/kubelet_pods.go (hunk 8 above)
Comment (mimowo) [reply pkg/kubelet/kubelet_pods.go:1265]: I don't think there is an issue from performance pov. First, the path is only invoked for terminal pods with the deletionTimestamp. The only scenario that produces such pods is described in the bug and is when the pod is non-admissible, and deleted during kubelet restart. So, it seems very unlikely to have many of such pods. Second, the TerminatePod is very fast as there is no killing of containers. I this the only reason it could take close to 2s is when the Delete request is throttled by the QPS or P&F at the API server side. However, since 1.27 the QPS for kubelet is 50, so we should be able to delete around 100 such pods in the 2s interval.

File: pkg/kubelet/kubelet_pods.go [hunk 9]
```diff
@@ -1245,6 +1255,36 @@ func (kl *Kubelet) HandlePodCleanups(ctx context.Context) error {
...
+		if !kl.isAdmittedPodTerminal(pod) {
+			// skip non-terminal pods
+			continue
+		}
+		if _, knownPod := workingPods[pod.UID]; knownPod {
+			// skip pods known to pod workers
+			continue
+		}
+		if _, knownPod := kl.statusManager.GetPodStatus(pod.UID); !knownPod {
```
Comment (smarterclayton) [inline pkg/kubelet/kubelet_pods.go:1274]: Calling GetPodStatus twice (once in isAdmittedPodTerminal and once here) feels wierd.  The logic in isAdmittedPodTerminal doesn't feel special enough to be called.

Comment (smarterclayton) [reply pkg/kubelet/kubelet_pods.go:1274]: In general reconciliation loops should make one call to other components to resynchronize their state - when we do lots of incremental calls it tends to confuse the process.

File: pkg/kubelet/kubelet_pods.go [hunk 10]
```diff
@@ -1173,6 +1173,16 @@ func (kl *Kubelet) HandlePodCleanups(ctx context.Context) error {
...
 	metrics.RestartedPodTotal.WithLabelValues("").Add(float64(restartCount))
 
+	// Complete termination of deleted pods that are not runtime pods (don't have
+	// running containers), are terminal, and are not known to pod workers.
+	// An example is pods rejected during kubelet admission that have never
+	// started before (i.e. does not have an orphaned pod).
+	// Triggering TerminatePod allows to proceed with force-deletion of such pods.
+	for _, pod := range kl.filterTerminalPodsToDelete(allPods, runningRuntimePods, workingPods) {
+		klog.V(3).InfoS("Completing termination of terminal pods scheduled for deletion", "pod", klog.KObj(pod), "podUID", pod.UID)
+		kl.statusManager.TerminatePod(pod)
```
Comment (smarterclayton) [inline pkg/kubelet/kubelet_pods.go:1183]: Is this racy?  Since pod worker is async, a pod may have been added to the pod worker, but not propogated to status manager.  Is the race prevented because we filter out pods known to the pod worker?  Is there any way for this resync process to race with pods completing in the pod worker?

File: pkg/kubelet/kubelet_pods.go [hunk 11]
```diff
@@ -1245,6 +1255,36 @@ func (kl *Kubelet) HandlePodCleanups(ctx context.Context) error {
 	return nil
 }
 
+// Filters terminal pods with deletion timestamp which are not runtime pods
```
Comment (smarterclayton) [inline pkg/kubelet/kubelet_pods.go:1258]: Would prefer a slightly longer godoc that covers the full logic.

File: pkg/kubelet/kubelet_pods.go (hunk 9 above)
Comment (mimowo) [reply pkg/kubelet/kubelet_pods.go:1274]: Yeah, no need to call GetPodStatus twice. I think I will inline the `isAdmittedPodTerminal`, then remove this explicit check here.

File: pkg/kubelet/kubelet_pods.go (hunk 10 above)
Comment (mimowo) [reply pkg/kubelet/kubelet_pods.go:1183]: pods that aren't propagated to status manager would be eliminated by the GetPodStatus check. The main reason I have added it was to narrow down the scope just to the problematic pods. These are rejected pods, terminal, not added to pod workers, but added to status manager. I think skipping the check that the pod isn't it pod workers risks another scenario: that the pod's phase is changed to terminal by an external controller. In that case we still want to go through the syncTerminatingPod triggered by pod workers, so we don't want to interfere here in this scenario.

File: pkg/kubelet/kubelet_pods.go (hunk 8 above)
Comment (bobbypage) [reply pkg/kubelet/kubelet_pods.go:1265]: My concern here is that `TerminatePod` does call `updateStatusInternal` with `forceUpdate=true` (https://github.com/kubernetes/kubernetes/blob/2802bbce14ca32cddbd0d0567cd33fb435f445e6/pkg/kubelet/status/status_manager.go).

Since `forceUpdate=true`, we will skip [this](https://github.com/kubernetes/kubernetes/blob/2802bbce14ca32cddbd0d0567cd33fb435f445e6/pkg/kubelet/status/status_manager.go#L657-L660), and always create a new `versionedPodStatus` and trigger `syncBatch`. In `syncBatch` we send request to API-server which can take some time (throttling, P&F, etc). And since this is part of the `HandlePodCleanups` call, the time spent in `syncBatch` will block the main sync loop.

Another alternative would be to refactor `TerminatePod` and have a way to mark the pod as terminated asynchronously so we don't trigger `forceUpdate=true` and have the pod termination be handled in the next `syncBatch`, that way it won't block the main `HandlePodCleanup` loop.

Comment (mimowo) [reply pkg/kubelet/kubelet_pods.go:1265]: Thanks for pointing this out. I will think about how to make the refactoring small enough for cherry-pick. 

Maybe this is a level of complication at which it is just simpler to add rejected pods to pod workers as proposed here: https://github.com/kubernetes/kubernetes/pull/118614/files. One downside (but seems really small) is that such pods are going `syncTerminatingPods` which might not be necessary. 

wdyt?

Comment (mimowo) [reply pkg/kubelet/kubelet_pods.go:1265]: Another alternative (suggested by @bobbypage ) is to call 
`kl.podWorkers.UpdatePod(UpdatePodOptions{ Pod: pod, UpdateType: kubetypes.SyncPodKill })` from within `HandlePodCleanups` instead of calling `TerminatePod`. It will allow us to skip the `UpdatePod` on the next `HandlePodCleanups` as it will be added to pod workers. I will give it a try.

Comment (mimowo) [reply pkg/kubelet/kubelet_pods.go:1268]: I've tested it and it works really well, updated the PR. It also eliminates the need for statusManager lookup. Moreover, we don't need to check the DeletionTimestamp, though it still might be desired.

File: pkg/kubelet/kubelet_pods.go (hunk 11 above)
Comment (mimowo) [reply pkg/kubelet/kubelet_pods.go]: Added the godoc.

File: pkg/kubelet/kubelet_pods.go (hunk 10 above)
Comment (mimowo) [reply pkg/kubelet/kubelet_pods.go]: This is outdated since now I call 
```
kl.podWorkers.UpdatePod(UpdatePodOptions{
			UpdateType: kubetypes.SyncPodKill,
			Pod:        pod,
		})
```
this completely eliminates the need to check status manager.

**Comment by mimowo** [comment]
@bobbypage @smarterclayton ready for another pass. I've tested the latest version with 50 repeats of the new tests locally and there were no failures.

File: pkg/kubelet/kubelet_pods.go (hunk 8 above)
Comment (smarterclayton) [reply pkg/kubelet/kubelet_pods.go:1279]: This is awesome, and I'm glad it worked out cleanly (also it makes handlepodcleanups even simpler and that's a huge win).

I think checking the deletion timestamp is still ok.

**Comment by smarterclayton** [comment]
Looks good to me.  I don't have any substantitive comments on the tests, other than "you saw them fail if your fix is commented out"?

**Comment by mimowo** [comment]
> Looks good to me. I don't have any substantitive comments on the tests, other than "you saw them fail if your fix is commented out"?

The first test, for the main scenario, fails consistently without the fix. 

The second, for the non-admissible runtime pod, passes as it was already covered by HandlePodCleanups, but it seems valuable to test this non-obvious modification of the main scenario.

File: pkg/kubelet/kubelet_pods.go (hunk 8 above)
Comment (bobbypage) [reply pkg/kubelet/kubelet_pods.go:1279]: +1, I think calling into the pod worker having the regular `SyncTerminatedPod` flow is much cleaner approach here, glad that is working out!

**Comment by bobbypage** [comment]
Also lgtm on the changes, the change to use pod worker update with `SyncPodKill` is much cleaner then having to call into `TerminatePod` from within HandlePodCleanups.

The only thing I saw when testing out the changes [here](https://gist.githubusercontent.com/bobbypage/a6ff485744de4857837c5b6da8ebcadb/raw/6d1ed687c2c5e7411db799f95133c2b91e8800a9/gistfile0.txt) is there is a ~10s delay for the pod from the pod being rejected at kubelet to the pod being deleted on the apiserver. This is because the following flow happens:

(1) The pod is rejected by kubelet, the local status manager is updated with terminal phase
(3) We wait 10s until `syncBatch` completes in status_manager
(4) status manager sees that the local status is different then api status, it updates it failed
(5) HandlePodCleanups will run, be filtered as part of `filterTerminalPodsToDelete` and the SyncPodKill will be delivered to it.

IMO, the 10s latency is not big deal... it will reconcile eventually, but if we wanted it to update faster and reduce latency, I think if we also called `kl.podWorkers.UpdatePod(UpdatePodOptions` with `UpdateType: kubetypes.SyncPodKill` in `rejectPod` it would updated the status ~instantly, without waiting for the 10sec sync batch (i.e. as https://github.com/kubernetes/kubernetes/pull/118614/files). 

So maybe long term, we should do *both*, i.e. call `UpdatePod` in `HandlePodCleanups` and `rejectPod`. But I don't think should be blocking the PR (and can be handled as a followup) as the case here is not super common to hit in the first place, and the latency is not critical IMO.

**Comment by mimowo** [comment]
Thanks @bobbypage for the summary. The scenario is very unlikely, so I don't think 10s makes a difference, but it is a judgment call.  

I have looked if there are other scenarios possible to arrive with pods which satisfy the conditions: not runtime pods, terminal, with deletion timestamp and not in pod workers, but the scenario reported is the only I could come up with. This is probably because `rejectPod` is the only path in [HandlePodAdditions](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2519-L2596) which doesn't register the pod in pod workers.

So, this is why the fix https://github.com/kubernetes/kubernetes/pull/118614/files (to call SyncPodKIll from rejectPod( should also work. As for which one is better, the margins are small. The other fix reduces latency, but is specific to rejected pods, so potentially there might be a scenario we couldn't think about, which somehow bypasses `HandlePodAdditions`, but I couldn't find despite attempts. 

IIUC if we combine the two fixes, then the code in `HandlePodCleanups` is dead, so I would prefer to decide on one of the two approaches (unless we have a scenario to support the need for both). If we are fine with latency then the generic one is preferred for me, otherwise the fix on `rejectPod`. 

Let me know what you think, I'm out next week and will be back on the 5th of July.

**Comment by bobbypage** [comment]
Thanks @mimowo for the explanation, +1, I agree this scenario is super likely to be hit and the 10s latency is not critical, so I'm lgtm to go with this approach.

**Comment by smarterclayton** [comment]
Since we plan on pulling admission closer to pod worker anyway, rejection probably becomes a pod worker responsibility and that should fix the issue (but we still need resync for restarts anyway).

/lgtm too
/approve

**Comment by ccieliu** [comment]
Hi Team,

Same issue here, may i know the issue fixed in which release?

**Comment by mimowo** [comment]
> Same issue here, may i know the issue fixed in which release?

This was fixed in 1.28 (this PR), and cherry-picked on 1.27.4 in this PR https://github.com/kubernetes/kubernetes/pull/118841.

See in release notes: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md#changelog-since-v1273

"Fix deletion of non-admissible pods that are deleted during Kubelet restart (https://github.com/kubernetes/kubernetes/pull/118841, [@bobbypage](https://github.com/bobbypage)) [SIG Node and Testing]"

**Comment by ccieliu** [comment]
> > Same issue here, may i know the issue fixed in which release?
> 
> This was fixed in 1.28 (this PR), and cherry-picked on 1.27.4 in this PR #118841.
> 
> See in release notes: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.27.md#changelog-since-v1273
> 
> "Fix deletion of non-admissible pods that are deleted during Kubelet restart (#118841, [@bobbypage](https://github.com/bobbypage)) [SIG Node and Testing]"

Got it, thanks for your time and have a good day.
