### PR TITLE
Fix retry logic in DisruptionController

### LINKED ISSUE #82149: PodDisruptionBudget can be violated by disruption controller
**What happened**:
Evictions occasionally succeed despite exceeding their PodDisruptionBudget. 

**What you expected to happen**:
Evictions should fail once the PodDisruptionBudget is exhausted.

**How to reproduce it (as minimally and precisely as possible)**:

1. On a single-node cluster, create a delpoyment with 3 replicas.
2. Create a PodDisruptionBudget for the deployment with `minAvailable=1`
3. Cordon the node by setting `node.Spec.Unschedulable=true`
4. Iterate over pods and evict them. i.e.
```go
client.CoreV1().Pods(namespace).Evict(&policy.Eviction{
	ObjectMeta: metav1.ObjectMeta{
		Name:      podName,
		Namespace: namespace,
	},
	DeleteOptions: &metav1.DeleteOptions{},
})
```

The last eviction is expected to fail, but sometimes succeeds.

**Anything else we need to know?**:

The problem seems to happen in the disruption controller, where we update PDB status in a retry loop. The update could fail because the eviction handler [updated](https://github.com/kubernetes/kubernetes/blob/c80d2c228353e78c9b85bb43bddbf5f2917be4ba/pkg/registry/core/pod/storage/eviction.go#L229) the same PDB status. 

1. disruption controller starts to write an update
2. eviction handler decrements `PodDisruptionsAllowed`
3. disruption controller update fails
4. disruption controller fetches latest PDB object, then overwrites status with the values from step 1 above.
5. disruption controller update succeeds

https://github.com/kubernetes/kubernetes/blob/c80d2c228353e78c9b85bb43bddbf5f2917be4ba/pkg/controller/disruption/disruption.go#L776-L801

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.7
- Cloud provider or hardware configuration: GKE
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig api-machinery
/cc @mml @lavalamp

### PR DESCRIPTION
**Pull request by misterikkit**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

This changes the retry logic in DisruptionController so that it
reconciles update conflicts. In the old behavior, any pdb status update
failure was retried with the same status, regardless of error.

Now there is no retry logic with the status update. The error is passed
up the stack where the PDB can be requeued for processing.

If the PDB status update error is a conflict error, there are some new
special cases:
- failSafe is not triggered, since this is considered a retryable error
- the PDB is requeued immediately (ignoring the rate limiter) because we
  assume that conflict can be resolved by getting the latest version

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/kubernetes/issues/82149

**Special notes for your reviewer**:

I am uncertain whether bypassing the rate limiter is advisable.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by lavalamp** [comment]
thanks for the quick fix, but I think we also need a test?

File: pkg/controller/disruption/disruption_test.go [hunk 1]
```diff
@@ -1025,3 +1038,64 @@ func TestDeploymentFinderFunction(t *testing.T) {
 		})
 	}
 }
+
+func TestUpdatePDBStatusRetries(t *testing.T) {
```
Comment (lavalamp) [inline pkg/controller/disruption/disruption_test.go]: This test verifies that it retries on a conflict error, but nowhere is it made clear in the code or comments why this is important. Can you mention the race here and that this is just the simplest way of avoiding it?

Comment (misterikkit) [reply pkg/controller/disruption/disruption_test.go]: I've drastically revamped the test so that it asserts on the underlying bad behavior rather than how we fix it. PTAL

File: pkg/controller/disruption/disruption_test.go [hunk 2]
```diff
@@ -1025,3 +1039,144 @@ func TestDeploymentFinderFunction(t *testing.T) {
...
+			t.Fatalf("Failed to create pod: %v", err)
+		}
+	}
+
+	// Block until the fake clientset writes are observable in the informer caches.
+	// FUN FACT: This guarantees that the informer caches have updated, but it does
+	// not guarantee that informer event handlers have completed. Fortunately,
+	// DisruptionController does most of its logic by reading from informer
+	// listers, so this guarantee is sufficient.
+	if err := waitForCacheCount(dc.pdbStore, 1); err != nil {
```
Comment (tedyu) [inline pkg/controller/disruption/disruption_test.go]: Isn't this wait covered by the wait on line 1084 below ?

Comment (tedyu) [reply pkg/controller/disruption/disruption_test.go]: I ran the test without this wait and the test passed.

File: pkg/controller/disruption/disruption_test.go [hunk 3]
```diff
@@ -1025,3 +1039,144 @@ func TestDeploymentFinderFunction(t *testing.T) {
...
+	}
+
+	// Sync DisruptionController once to update PDB status.
+	if err := dc.sync(pdbKey); err != nil {
+		t.Fatalf("Failed initial sync: %v", err)
+	}
+
+	// Evict simulates the visible effects of eviction in our fake client.
+	evict := func(podNames ...string) {
+		// These GVRs are copied from the generated fake code because they are not exported.
```
Comment (tedyu) [inline pkg/controller/disruption/disruption_test.go]: Maybe extract the code till line 1125 in a helper for future code reuse

File: pkg/controller/disruption/disruption_test.go (hunk 2 above)
Comment (misterikkit) [reply pkg/controller/disruption/disruption_test.go]: The test is likely to be flaky without these waits.

File: pkg/controller/disruption/disruption_test.go (hunk 3 above)
Comment (misterikkit) [reply pkg/controller/disruption/disruption_test.go]: Are you referring to the evict function, or just the GVR constants? I would prefer to extract these in the future when we have a second or third call site.

The function could be extracted as a generic helper, but the current implementation is tightly coupled to this unit test. It both captures local variables from the surrounding scope and makes assumptions about the fake clientset that will be used.

Comment (tedyu) [reply pkg/controller/disruption/disruption_test.go]: refactoring in the future is fine.

**Comment by misterikkit** [comment]
friday ping

**Comment by misterikkit** [comment]
friendly honk

**Comment by lavalamp** [comment]
/lgtm
/approve

Thank you for the extensive test.

**Comment by b0b0haha** [comment]
I'am confiused about that why the disruption controller and evict handler can update the pdb status concurrently?
It seems when the disruption controller notice the pdb's update from the evict handler , it calls trySync() to update the pdb's PodDisruptionsAllowed again,
The original code below:

// refresh tries to re-GET the given PDB.  If there are any errors, it just
// returns the old PDB.  Intended to be used in a retry loop where it runs a
// bounded number of times.
func refresh(pdbClient policyclientset.PodDisruptionBudgetInterface, pdb *policy.PodDisruptionBudget) *policy.PodDisruptionBudget {
	newPdb, err := pdbClient.Get(pdb.Name, metav1.GetOptions{})
	if err == nil {
		return newPdb
	}
	return pdb

}

func (dc *DisruptionController) writePdbStatus(pdb *policy.PodDisruptionBudget) error {
	pdbClient := dc.kubeClient.PolicyV1beta1().PodDisruptionBudgets(pdb.Namespace)
	st := pdb.Status

	var err error
	for i, pdb := 0, pdb; i < statusUpdateRetries; i, pdb = i+1, refresh(pdbClient, pdb) {
		pdb.Status = st
		if _, err = pdbClient.UpdateStatus(pdb); err == nil {
			break
		}
	}

	return err
}
but the pdb's status has been updated by evict handler, why the evict handler can vilolate the pdb's minAvailable?
