### PR TITLE
Don't apply CNI to net=host pods

### LINKED ISSUE #19508: Poor handling of host-networked pods
Seen when running the kube-proxy as a pod with `NetworkMode == "host"`.

The CNI plugin attempts to retrieve the IP address of the kube-proxy pod, but fails to do so due to the lack of an eth0 interface.

```
Jan 11 22:25:22 node-2 kubelet[877]: E0111 22:25:22.305240     877 manager.go:377] NetworkPlugin cni failed on the status hook for pod 'kube-proxy-172.24.114.32' - invalid CIDR address: Device "eth0" does not exist.
```

I think the plugin interface shouldn't be trying to get the IP address of host networked pods, or if it does it should just be using the node's IP address or some other field, since "eth0" won't always exist on a given node.

Additionally, I've seen the CNI interface call the network plugin setup and teardown hooks for pods with `NetworkMode == "host"` - I suspect that this is a bug, and the plugin interface shouldn't be executing network plugins for these pods (since they share host networking).

### PR DESCRIPTION
**Pull request by thockin**
Fixes #19508

gratuitously stolen from @bprashanth

### CODE REVIEW

**Comment by bprashanth** [comment]
LGTM and thanks. @kubernetes/goog-node fyi this translates to 2 extra docker inspects per pod creation for CNI plugins (which will soon become the defacto standard for kubernetes networking), I don't think that's a problem.

File: pkg/kubelet/dockertools/manager.go [hunk 1]
```diff
@@ -2058,13 +2063,25 @@ func getPidMode(pod *api.Pod) string {
...
 	}
 	return ipcMode
 }
 
-// GetNetNs returns the network namespace path for the given container
-func (dm *DockerManager) GetNetNs(containerID kubecontainer.ContainerID) (string, error) {
+// IsUsingHostNetwork returns true if the provided container ID is using host
+// networking.  This method is used by network plugins to determine if a pod
+// requires additional setup. Pods running with host networking do not.
+func (dm *DockerManager) IsUsingHostNetwork(containerID kubecontainer.ContainerID) (bool, error) {
```
Comment (vishh) [inline pkg/kubelet/dockertools/manager.go]: Why do we get this information from docker? Doesn't the kubelet already know if a pod requested host networking from the Spec?

Comment (bprashanth) [inline pkg/kubelet/dockertools/manager.go]: Totally possible but you'd need to lookup the pod from the containerID passed in. Also isolation between the kubelet and the net plugin is desirable. I'm holding my nose about the networkHost interface as it is because it punches holes through the CNI interface, but we don't have a better way for now.

Comment (dchen1107) [inline pkg/kubelet/dockertools/manager.go]: I agreed that we don't have a better way for now, but disagree the argument of that this isolates between kubelet and net plugin. By design, container runtime should understand pod, and network namespace is setup for pod anyway. In this case, retrieve this information from Spec itself is way better than inspecting from docker container.

Comment (bprashanth) [inline pkg/kubelet/dockertools/manager.go]: Yeah things are too nascent right now to comment but that sounds reasonable. 

We could of couse not invoke the plugin for host network pods by putting code in the kubelet, I felt that was more icky.  We could also pass the host-network flag via env vars, another thing i'm not a huge fan of. 


I think ideally, we would not have a reverse channel from network plugin to kubelet. We exec the network plugin sending a json manifest through stdin, so that's a pretty hard boundry for isolation. The way we handle docker networking is essentially setup the interfaces for the pause container, and then join everything using `net=container:pause`, so really we're just handling setup for the single pause container.

Comment (vishh) [inline pkg/kubelet/dockertools/manager.go]: The reason I bring it up is that we are trying hard to isolate the runtime behind an API and the fact that the runtime details are exposed here makes it hard to support other runtimes in the future, like hyper.

@bprashanth: If you are saying that this is just an interim state, thats OK I guess (@dchen1107 WDYT?).
If this is *THE* API for now, I disagree.

File: pkg/kubelet/network/cni/cni.go [hunk 2]
```diff
@@ -106,10 +106,21 @@ func (plugin *cniNetworkPlugin) SetUpPod(namespace string, name string, id kubec
 	if !ok {
 		return fmt.Errorf("CNI execution called on non-docker runtime")
 	}
-	netns, err := runtime.GetNetNs(id.ContainerID())
+	hostNet, err := runtime.IsUsingHostNetwork(id.ContainerID())
```
Comment (vishh) [inline pkg/kubelet/network/cni/cni.go]: Why can't we pass in Pod object here which should ideally include the container ID of the infra container as well?

Comment (bprashanth) [inline pkg/kubelet/network/cni/cni.go]: you can, given the nature of the problem I'd defer the refactor (this is an interface shared with exec plugins)

Comment (vishh) [inline pkg/kubelet/network/cni/cni.go]: You said "exec". Why would a GO interface be linked to that?

**Comment by thockin** [comment]
This plugin interface is internal, but it is used by 3rd-parties (e.g.
openshift), so changing it is a little more delicate.  In the medium term,
I think this whole interface either goes away or perhaps gets significantly
more private, so changes are easier.

I think I like Prashanth's point this can be handled at a higher layer.
I'll check it that way.

**Comment by thockin** [comment]
Pushed with this at the manager level.  Let's see if tests pass :)

**Comment by bprashanth** [comment]
@kubernetes/goog-node tldr on network plugins history: 

1. It's not clear whether or not we can get all the information we need from the pod spec. In fact this is likely *not* going to be the case for all network plugins, because it doesn't make sense to surface something like the location of a network namespace (eg: /proc/netns/hash etc) into an api object.     

2. The Kubernetes network plugin should act as a middle man between the runtime and the api, not the runtime and the kubelet or any internal runtime objects the kubelet has. We're currently focusing on network plugins for docker, other runtimes may need to write their own (eg: rkt).

3. Pushing the pod up and down the network plugin is an unncessary burden, if 1 is true. The kubelet will need to invoke the plugin with some json. This is a clear statement of the networking properties, and has nothing to do with pods really. If a given runtime doesn't understand the json-stating-networking-properties, it will not network. 

4. There are escape hatches to tell plugins about things like pod name/namespace. 

@thockin build fail with
```
23:59:49 # k8s.io/kubernetes/pkg/kubelet/network/cni
23:59:49 _output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/network/cni/cni.go:109: runtime.GetNetNs undefined (type *dockertools.DockerManager has no field or method GetNetNs, but does have GetNetNS)
23:59:49 _output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/network/cni/cni.go:128: runtime.GetNetNs undefined (type *dockertools.DockerManager has no field or method GetNetNs, but does have GetNetNS)
23:59:49 !!! Error in /go/src/k8s.io/kubernetes/hack/lib/golang.sh:395
```

**Comment by vishh** [comment]
@bprashanth:
> It's not clear whether or not we can get all the information we need from the pod spec. In fact this is likely not going to be the case for all network plugins, because it doesn't make sense to surface something like the location of a network namespace (eg: /proc/netns/hash etc) into an api object.

If the net plugin infra takes care of some of the common operations like identifying the net ns of containers, that is fine. But that will require a new abstraction between the net plugin infra and the network plugins.

> The Kubernetes network plugin should act as a middle man between the runtime and the api, not the runtime and the kubelet or any internal runtime objects the kubelet has. We're currently focusing on network plugins for docker, other runtimes may need to write their own (eg: rkt).

Sure. If I parse correctly, you want to avoid creating new abstractions that are specific only to the kubelet. If that is true, then re-using Pod object along with necessary extensions is more flexible right?

> Pushing the pod up and down the network plugin is an unncessary burden, if 1 is true. The kubelet will need to invoke the plugin with some json. This is a clear statement of the networking properties, and has nothing to do with pods really. If a given runtime doesn't understand the json-stating-networking-properties, it will not network.

Agreed. But, do we want to stop the network plugins from performing smarter operations based on some of the fields in the PodSpec, like setting up QoS based on some annotations, etc? I'm diverging from the original comment at this point. Essentially, can the net plugin infra consume the PodSpec? It does not have to pass it down to the plugins. That will avoid unnecessary interactions with the runtime. In general, being runtime agnostic and being dependent only the Linux Apis for network plugins is ideal.

**Comment by bprashanth** [comment]
I see. Lets table the discussion till we have a kubernetes network plugin. 

For now, there is a format to communicate with plugins, it's json (the CNI spec), the kubelet will have to munge data from wherever it needs to, to create this json. The network plugin can do whatever it wants, including create a docker client or invoking nsenter to get more information. This is where we hope to be a few weeks from now.

**Comment by vishh** [comment]
ok. While reaching that goal, can we avoid the network plugin infra from
directly meddling with the runtime, since that is a piece of software we
develop and maintain?

**Comment by bprashanth** [comment]
We already have existing code that's been in from before the last release that uses the runtime for netns location, and it's a shared interface with the cni and exec plugins. But you're free to refactor, I probably won't have the cycles :)

File: pkg/kubelet/dockertools/manager.go [hunk 3]
```diff
@@ -1295,12 +1300,19 @@ func (dm *DockerManager) killPodWithSyncResult(pod *api.Pod, runningPod kubecont
 		result.AddSyncResult(containerResult)
 	}
 	if networkContainer != nil {
-		teardownNetworkResult := kubecontainer.NewSyncResult(kubecontainer.TeardownNetwork, kubecontainer.BuildPodFullName(runningPod.Name, runningPod.Namespace))
-		result.AddSyncResult(teardownNetworkResult)
-		if err := dm.networkPlugin.TearDownPod(runningPod.Namespace, runningPod.Name, kubecontainer.DockerID(networkContainer.ID.ID)); err != nil {
-			message := fmt.Sprintf("Failed to teardown network for pod %q using network plugins %q: %v", runningPod.ID, dm.networkPlugin.Name(), err)
-			teardownNetworkResult.Fail(kubecontainer.ErrTeardownNetwork, message)
-			glog.Error(message)
+		ins, err := dm.client.InspectContainer(networkContainer.ID.ID)
```
Comment (bprashanth) [inline pkg/kubelet/dockertools/manager.go]: you have access to the pod.Spec here too right?

**Comment by bprashanth** [comment]
Just the nit

File: pkg/kubelet/dockertools/manager.go [hunk 4]
```diff
@@ -924,7 +929,7 @@ func (dm *DockerManager) podInfraContainerChanged(pod *api.Pod, podInfraContaine
 		networkMode = dockerPodInfraContainer.HostConfig.NetworkMode
 	}
 	if pod.Spec.SecurityContext != nil && pod.Spec.SecurityContext.HostNetwork {
```
Comment (dcbw) [inline pkg/kubelet/dockertools/manager.go]: Can we just do something like:

func useHostNetwork(pod *api.Pod) bool {
	return pod.Spec.SecurityContext != nil && pod.Spec.SecurityContext.HostNetwork)
}

and then call useHostNetwork() from all the places that do the HostNetwork check?

File: pkg/kubelet/dockertools/manager.go [hunk 5]
```diff
@@ -1856,24 +1868,26 @@ func (dm *DockerManager) syncPodWithSyncResult(pod *api.Pod, _ api.PodStatus, po
...
-
-			// Delete infra container
-			killContainerResult := kubecontainer.NewSyncResult(kubecontainer.KillContainer, PodInfraContainerName)
-			result.AddSyncResult(killContainerResult)
-			if delErr := dm.KillContainerInPod(kubecontainer.ContainerID{
-				ID:   string(podInfraContainerID),
-				Type: "docker"}, nil, pod, message); delErr != nil {
-				killContainerResult.Fail(kubecontainer.ErrKillContainer, delErr.Error())
-				glog.Warningf("Clear infra container failed for pod %q: %v", format.Pod(pod), delErr)
+		if pod.Spec.SecurityContext != nil && !pod.Spec.SecurityContext.HostNetwork {
```
Comment (dcbw) [inline pkg/kubelet/dockertools/manager.go]: Is this really what you want here, or should it be:

if !pod.Spec.SecurityContext || !pod.Spec.SecurityContext.HostNetwork
 ?

File: pkg/kubelet/dockertools/manager.go [hunk 6]
```diff
@@ -1856,24 +1868,26 @@ func (dm *DockerManager) syncPodWithSyncResult(pod *api.Pod, _ api.PodStatus, po
...
+					Type: "docker"}, nil, pod, message); delErr != nil {
+					killContainerResult.Fail(kubecontainer.ErrKillContainer, delErr.Error())
+					glog.Warningf("Clear infra container failed for pod %q: %v", format.Pod(pod), delErr)
+				}
+				return
 			}
-			return
 		}
 
 		// Setup the host interface unless the pod is on the host's network (FIXME: move to networkPlugin when ready)
```
Comment (dcbw) [inline pkg/kubelet/dockertools/manager.go]: All the Hairpin mode stuff can go under the !HostNetwork check too, since it's only relevant when there is pod networking.

File: pkg/kubelet/dockertools/manager.go (hunk 5 above)
Comment (bprashanth) [inline pkg/kubelet/dockertools/manager.go]: you mean execute the plugin if the security context is nil? IIUC we default it anyway. Also how does this play with container security context? I think that just bubbles up to the pod.

File: pkg/kubelet/dockertools/manager.go (hunk 4 above)
Comment (dcbw) [inline pkg/kubelet/dockertools/manager.go]: Also, this doesn't cover the case where the podSpec has changed to !HostNetwork but docker is still on host network; is that a valid case?  Not that the original code covered that case either...

File: pkg/kubelet/dockertools/manager.go [hunk 7]
```diff
@@ -1295,12 +1300,19 @@ func (dm *DockerManager) killPodWithSyncResult(pod *api.Pod, runningPod kubecont
...
-		if err := dm.networkPlugin.TearDownPod(runningPod.Namespace, runningPod.Name, kubecontainer.DockerID(networkContainer.ID.ID)); err != nil {
-			message := fmt.Sprintf("Failed to teardown network for pod %q using network plugins %q: %v", runningPod.ID, dm.networkPlugin.Name(), err)
-			teardownNetworkResult.Fail(kubecontainer.ErrTeardownNetwork, message)
-			glog.Error(message)
+		ins, err := dm.client.InspectContainer(networkContainer.ID.ID)
+		if err != nil {
+			glog.Errorf("Error inspecting container %v: %v", networkContainer.ID.ID, err)
+			return
+		}
+		if ins.HostConfig.NetworkMode != namespaceModeHost {
```
Comment (dcbw) [inline pkg/kubelet/dockertools/manager.go]: Do we need to check for "ins.HostConfig != nil" here like other places do, or can we assume it exists?

**Comment by dcbw** [comment]
@thockin suggested cleanup on top of your patch:

https://github.com/dcbw/kubernetes/commit/9c1c9377bd12cec457f9a42a9953405ec6ba79b8

I'd squash them together when committing, if it looks OK.

File: pkg/kubelet/dockertools/manager.go (hunk 5 above)
Comment (dcbw) [inline pkg/kubelet/dockertools/manager.go]: Everywhere else checks whether pod.Spec.SecurityContext  is nil before accessing it, so I assume that should be accounted for here too, or the other locations should be changed.  If SecurityContext is allowed to be nil then we could fail to set up the container here.

Comment (bprashanth) [inline pkg/kubelet/dockertools/manager.go]: I agree we should check. Even if it's defaulted today and in previous versions it may not be in future versions.

Comment (bprashanth) [inline pkg/kubelet/dockertools/manager.go]: > Also how does this play with container security context?

Actually one isn't allowed to specify host networking in the container security context.

File: pkg/kubelet/dockertools/manager.go (hunk 3 above)
Comment (thockin) [inline pkg/kubelet/dockertools/manager.go]: pod might be nil.  I could test if it is not and use that instead, but why bother?

File: pkg/kubelet/dockertools/manager.go (hunk 7 above)
Comment (thockin) [inline pkg/kubelet/dockertools/manager.go]: yes.  Fixed in next push

File: pkg/kubelet/dockertools/manager.go (hunk 5 above)
Comment (thockin) [inline pkg/kubelet/dockertools/manager.go]: Good catch.  if SecurityContext is nil, HostNetwork is false implicitly.

File: pkg/kubelet/dockertools/manager.go (hunk 6 above)
Comment (thockin) [inline pkg/kubelet/dockertools/manager.go]: hairpin is already guarded

containerIP is the hostIP in this case

File: pkg/kubelet/dockertools/manager.go (hunk 4 above)
Comment (thockin) [inline pkg/kubelet/dockertools/manager.go]: We don't allow that change in an update

Comment (thockin) [inline pkg/kubelet/dockertools/manager.go]: This comparision is suspect, I'll file a different bug.

**Comment by thockin** [comment]
I'm stretched for time, so I'll leave the rebase alone, but I implemented some of it.  AFAIK all comments are addressed,

File: pkg/kubelet/dockertools/manager.go (hunk 6 above)
Comment (dcbw) [inline pkg/kubelet/dockertools/manager.go]: determineContainerIP() here cannot possibly return any interesting result here for two reasons:

1) if the network plugin wasn't called to set up the container, it seems really odd to ask the network plugin for the containers IP address.  Yes, this might work, but is really weird.

2) docker '--net=host' doesn't report any IP address for the container, so plugins that chain up to DockerManager.GetContainerIP() won't return anything either.

# sudo docker run --net=host -it dcbw/fedora-net /bin/bash
...
# sudo docker inspect 0a0685f13f6c | grep "NetworkMode\|IPAddress"
        "IPAddress": "",
        "SecondaryIPAddresses": null,
        "NetworkMode": "host",

while the patch LGTM now, I think there's definitely room for further optimization.  I'm happy to do that if you like.

**Comment by dcbw** [comment]
LGTM

**Comment by eparis** [comment]
@k8s-bot test this issue: #IGNORE

**Comment by dcbw** [comment]
@thockin what's the status on this one?  What else needs to happen to move it forward?

**Comment by bprashanth** [comment]
The submit queue should merge it automatically when its turn comes

**Comment by eparis** [comment]
well, we've got some jenkins problems, which are causing some submit-queue problems, which is why a bunch of PRs aren't even in the queue.  Hopefully my request to retest up there will get this, eventually, merged...

File: pkg/kubelet/dockertools/manager.go (hunk 3 above)
Comment (Random-Liu) [inline pkg/kubelet/dockertools/manager.go]: The pod could be nil indeed. I didn't noticed that before and it took me sometime to debug...
