### PR TITLE
fix: pods meeting qualifications for static placement when cpu-manager-policy=static should not have cfs quota enforcement

### LINKED ISSUE #70585: Disable cpu quota(use only cpuset) for pod Guaranteed
**What would you like to be added**:

Disable cpu quota when we use cpuset for guaranteed pods.

**Why is this needed**:

For now, kubelet default adds cpu quota and share for all cases when `cpuCFSQuota` is open, even if *cpuset* will be set in guaranteed pod case. 

However, this kind of use(cpuset with quota) may sometimes bring us cpu throttle time which we don't expect.

My question is why not make a `if` statement when we add cpuQuota config, if it's *guaranteed* case, just set `cpuQuota=-1`?

```
	if m.cpuCFSQuota {
		// if cpuLimit.Amount is nil, then the appropriate default value is returned
		// to allow full usage of cpu resource.
		cpuQuota, cpuPeriod := milliCPUToQuota(cpuLimit.MilliValue())
		lc.Resources.CpuQuota = cpuQuota
		lc.Resources.CpuPeriod = cpuPeriod
	}
``` 

/kind feature

### PR DESCRIPTION
**Pull request by scott-grimes**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:

When `cpu-manager-policy=static` and the qualifications for static cpu assignment are satisfied (i.e. Containers have `Guaranteed` QOS with integer CPU `requests`) cfs quota is disabled.

#### Which issue(s) this PR fixes:
Fixes #70585

#### Does this PR introduce a user-facing change?

```release-note
When cpu-manager-policy=static is configured containers meeting the qualifications for static cpu assignment (i.e. Containers with integer CPU `requests` in pods with `Guaranteed` QOS) will not have cfs quota enforced. Because this fix changes a long-established behavior, users observing a regressions can use the DisableCPUQuotaWithExclusiveCPUs feature gate (default on) to restore the old behavior. Please file an issue if you encounter problems and have to use the Feature Gate.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

When `cpu-manager-policy=static`:

1) container level cgroup: The container-level cpu limit per container (init, application, sidecar) is removed when the container has a dedicated CPU
2) pod level cgroup: The pod-level cpu limit is removed when **any** container  in the pod has a dedicated CPU

Note that containers (init, application, sidecar) within a pod are allocated a dedicated CPU when all of the following are true:

*    cpumanager policy is static
*    pod has QoS guaranteed
*    the container has integer cpu request

This logic is encapsulated in the static policy per

[kubernetes/pkg/kubelet/cm/cpumanager/policy_static.go](https://github.com/kubernetes/kubernetes/blob/02fd991c5b3d1b705658633a93f8d8aae2c694bb/pkg/kubelet/cm/cpumanager/policy_static.go#L457-L478)

```
 func (p *staticPolicy) guaranteedCPUs(pod *v1.Pod, container *v1.Container) int { 
 	if v1qos.GetPodQOS(pod) != v1.PodQOSGuaranteed { 
 		return 0 
 	} 
 	cpuQuantity := container.Resources.Requests[v1.ResourceCPU] 
 	// In-place pod resize feature makes Container.Resources field mutable for CPU & memory. 
 	// AllocatedResources holds the value of Container.Resources.Requests when the pod was admitted. 
 	// We should return this value because this is what kubelet agreed to allocate for the container 
 	// and the value configured with runtime. 
 	if utilfeature.DefaultFeatureGate.Enabled(features.InPlacePodVerticalScaling) { 
 		if cs, ok := podutil.GetContainerStatus(pod.Status.ContainerStatuses, container.Name); ok { 
 			cpuQuantity = cs.AllocatedResources[v1.ResourceCPU] 
 		} 
 	} 
 	if cpuQuantity.Value()*1000 != cpuQuantity.MilliValue() { 
 		return 0 
 	} 
 	// Safe downcast to do for all systems with < 2.1 billion CPUs. 
 	// Per the language spec, `int` is guaranteed to be at least 32 bits wide. 
 	// https://golang.org/ref/spec#Numeric_types 
 	return int(cpuQuantity.Value()) 
 } 
```

### CODE REVIEW

**Comment by ffromani** [comment]
Thanks for the PR!
There's complete consensus in sig-node this issue is real, but a (much needed) fix has a lot of implications to investigate. The most recent attempt is https://github.com/kubernetes/kubernetes/pull/117030
@scott-grimes perhaps you can comment about the pros/cons of this approach vs 117030?

**Comment by scott-grimes** [comment]
This PR is cleaner it's just [3 LOC](https://github.com/kubernetes/kubernetes/blob/bf9badb98bdd26cf6d7bfef0d21fc13805149b57/pkg/kubelet/cm/helpers_linux.go#L170-L174) to implement the logic in `pkg/kubelet/cm/helpers_linux.go`. No need to muck about with `internal_container_lifecycle_linux`, or have the original continer spawned with incorrect quota then a gap for the cm to rectify. The cgroup can just be spawned with `cpu.cfs_quota_us=-1` directly.

Also makes it clear that this policy is `experimental` and subject to change. The method used is only invoked in 3 places, so it will be far easier to mantain/revert/modify in future as additional cpu manager policies are implemented.

**Comment by ffromani** [comment]
/ok-to-test

I would very much like simpler code, but we had long, long debates about corner cases and avoid causing regressions; so I'd like to check we are covering all the flow we know about.
Do we cover these, for starters? https://github.com/kubernetes/kubernetes/pull/117030#issuecomment-1651644169

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 1]
```diff
@@ -665,7 +666,8 @@ func (m *kubeGenericRuntimeManager) computePodResizeAction(pod *v1.Pod, containe
 func (m *kubeGenericRuntimeManager) doPodResizeAction(pod *v1.Pod, podStatus *kubecontainer.PodStatus, podContainerChanges podActions, result kubecontainer.PodSyncResult) {
 	pcm := m.containerManager.NewPodContainerManager()
 	//TODO(vinaykul,InPlacePodVerticalScaling): Figure out best way to get enforceMemoryQoS value (parameter #4 below) in platform-agnostic way
-	podResources := cm.ResourceConfigForPod(pod, m.cpuCFSQuota, uint64((m.cpuCFSQuotaPeriod.Duration)/time.Microsecond), false)
+	cpuExperimentalManagerPolicyStatic := m.containerManager.GetNodeConfig().CPUManagerPolicy == string(cpumanager.PolicyStatic)
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:669]: I can see the intent, but cpumanager is GA, so adding back "Experimental" doesn't seem the best way forward to me; I'd prefer something like a feature gate to guard this fix (or any other alternate implementation). I asked sig-arch for input about adding feature gates in this context.

**Comment by ffromani** [comment]
/triage accepted
/priority important-longterm

alternate take wrt to https://github.com/kubernetes/kubernetes/pull/117030 .
we should converge toward a single solution. It would be really great to ensure e2e test coverage (in either approach!)

File: pkg/kubelet/cm/helpers_linux.go [hunk 2]
```diff
@@ -167,6 +167,12 @@ func ResourceConfigForPod(pod *v1.Pod, enforceCPULimits bool, cpuPeriod uint64,
 	// determine the qos class
 	qosClass := v1qos.GetPodQOS(pod)
 
+	// quota is not capped if cpu manager policy is static
+	// and pod meets qualifications for static assignment
+	if cpuExperimentalManagerPolicyStatic && qosClass == v1.PodQOSGuaranteed && cpuRequests % MilliCPUToCPU == 0 {
```
Comment (MarSik) [inline pkg/kubelet/cm/helpers_linux.go:172]: The condition for having pinned cpus is to use an integer value in the container's request. This condition would return true even for requests.cpu: 1.0, am I right?

I like it, because it is much simpler than my PR https://github.com/kubernetes/kubernetes/pull/117030 , however this was one of the review comments I had to resolve.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 1 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:669]: cool, lmk happy to swap to whatever verbiage they choose

File: pkg/kubelet/cm/helpers_linux.go (hunk 2 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/helpers_linux.go:172]: yessir! because we convert to mc first then look at the def this will handle all of the following cases
```
request: 1
request: 1000m
request: 1.0
```

Comment (scott-grimes) [reply pkg/kubelet/cm/helpers_linux.go:172]:
```
package main

import (
  "fmt"
  v1 "k8s.io/api/core/v1"
  "k8s.io/apimachinery/pkg/api/resource"
)

func computeCpuResourceQuantity(cpu string) resource.Quantity {
  res := v1.ResourceList{}
  res[v1.ResourceCPU] = resource.MustParse(cpu)
  return res["cpu"]
}

func main() {
  i := computeCpuResourceQuantity("1")
  j := computeCpuResourceQuantity("1.0")
  k := computeCpuResourceQuantity("1000m")
  fmt.Println(i.MilliValue())
  fmt.Println(j.MilliValue())
  fmt.Println(k.MilliValue())

}

```

**Comment by scott-grimes** [comment]
> I would very much like simpler code, but we had long, long debates about corner cases and avoid causing regressions; so I'd like to check we are covering all the flow we know about. Do we cover these, for starters? [#117030 (comment)](https://github.com/kubernetes/kubernetes/pull/117030#issuecomment-1651644169)

Ah mea culpa I was only looking at the pod-level cgroup. Pushed fix now to include fixes for the other cases from your link:

a) for guaranteed QoS pods which have at least one container which got exclusive CPU assignement:
*  ✅ disable the CPU quota for the pod (sandbox) cgroup 
*  ✅ disable the CPU quota for each container which have exclusive CPUs assigned
b)  ✅ DO NOT disable (keep existing behavior) the CPU quota for any other container (if present) which DO NOT have exclusive CPUs assigned. 


Note for (b) is [not possible](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed): for a pod to have `qos: Guaranteed` if ANY container has a container where the memory requests and limits are not set and equal to each other. 

```
For a Pod to be given a QoS class of Guaranteed:

    Every Container in the Pod must have a memory limit and a memory request.
    For every Container in the Pod, the memory limit must equal the memory request.
    Every Container in the Pod must have a CPU limit and a CPU request.
    For every Container in the Pod, the CPU limit must equal the CPU request.

These restrictions apply to init containers and app containers equally. [Ephemeral containers](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/) cannot define resources so these restrictions do not apply.
```

Is IS possible that a pod is created such that qos class is QoS class of Guaranteed but only a subset of containers should have their quotas lifted. 

```
# .e.g 
spec:
  containers:
  
- name: no-throttle
   resources:
     requests:
       memory: "1Gi"
       cpu: "1000m"
     limits:
       memory: "1Gi"
       cpu: "1000m"
- name: yes-throttle
   resources:
     requests:
       memory: "1Gi"
       cpu: "250m"
     limits:
       memory: "1Gi"
       cpu: "250m"
```

This PR takes this edge-case into account as well such that the matrix of cases for possible containers are:

| qos Guarenteed | staticCpuPolicyEnabled | ContainerHasIntCpuReuquest | Expectation |
| ❌  | ❌  | ❌  | `enforced` |
| ❌  | ❌  | ✅  | `enforced` |
| ❌  | ✅ | ❌  | `enforced` |
| ❌  | ✅ | ✅  | `enforced` |
| ✅ | ❌  | ❌  | `enforced` |
| ✅ | ❌  | ✅  | `enforced` |
| ✅ | ✅  | ❌  | `enforced` |
| ✅ | ✅  | ✅  | `NOT enforced` |



I'm having issues with the `kuberuntime_sandbox_linux_test` and `kuberuntime_manager_test` locally at the moment. will be easy enough to add full testing coverage for this after resolving

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 3]
```diff
@@ -157,6 +157,16 @@ func (m *kubeGenericRuntimeManager) generateLinuxContainerResources(pod *v1.Pod,
 		}
 	}
 
+	// cfs quota for container is not capped if
+	// 1. cpu manager policy is static
+	// 2. pod has quos PodQOSGuaranteed
+	// 3. container has integer cpu request
+	if m.containerManager.cpuExperimentalManagerPolicyStatic &&
+		kubeapiqos.GetPodQOS(pod) == v1.PodQOSGuaranteed &&
+		container.Resources.Requests.Cpu().MilliValue() % MilliCPUToCPU == 0 {
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:166]: this logic should really be in the cpumanager. In https://github.com/kubernetes/kubernetes/pull/117030 we check the container got exclusive cpu assigned; we can redo the math instead, there are pros/cons for both approaches, but we should not replicate the logic outside cpumanager.

**Comment by ffromani** [comment]
> > I would very much like simpler code, but we had long, long debates about corner cases and avoid causing regressions; so I'd like to check we are covering all the flow we know about. Do we cover these, for starters? [#117030 (comment)](https://github.com/kubernetes/kubernetes/pull/117030#issuecomment-1651644169)
> 
> Ah mea culpa I was only looking at the pod-level cgroup. Pushed fix now to include fixes for the other cases from your link:
> 
> a) for guaranteed QoS pods which have at least one container which got exclusive CPU assignement:
> 
>     * ✅ disable the CPU quota for the pod (sandbox) cgroup
> 
>     * ✅ disable the CPU quota for each container which have exclusive CPUs assigned
>       b)  ✅ DO NOT disable (keep existing behavior) the CPU quota for any other container (if present) which DO NOT have exclusive CPUs assigned.
> 
> 
> Note for (b) is [not possible](https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed): for a pod to have `qos: Guaranteed` if ANY container has a container where the memory requests and limits are not set and equal to each other.

You're right about the QoS criterias, but in order to get exclusive cpu assignment there's the further restriction that a container must ask an integral amount of CPUs; is possible for a container to ask, say, fro 250m of CPUs, and thus that specific container won't get exclusive CPUs. In this case, the same container should not have its quota unilimited.
I think this is pretty much what you indeed elaborate down below.

> Is IS possible that a pod is created such that the QoS class is Guaranteed but only a subset of containers should have their quotas lifted.

yep, that's the intent indeed.

> This PR takes this edge-case into account as well such that the matrix of cases for possible containers are:
> qos Guarenteed 	staticCpuPolicyEnabled 	ContainerHasIntCpuReuquest 	Expectation
> ❌ 	❌ 	❌ 	`enforced`
> ❌ 	❌ 	✅ 	`enforced`
> ❌ 	✅ 	❌ 	`enforced`
> ❌ 	✅ 	✅ 	`enforced`
> ✅ 	❌ 	❌ 	`enforced`
> ✅ 	❌ 	✅ 	`enforced`
> ✅ 	✅ 	❌ 	`enforced`
> ✅ 	✅ 	✅ 	`NOT enforced`

correct

> I'm having issues with the `kuberuntime_sandbox_linux_test` and `kuberuntime_manager_test` locally at the moment. will be easy enough to add full testing coverage for this after resolving

we also need some e2e test coverage.
I'll be pushing for a feature gate, will start the convo with sig-node leads ASAP.m Having a feature gate is likely the breakthrough we were looking for to fix this issue.

File: pkg/kubelet/cm/helpers_linux.go (hunk 2 above)
Comment (MarSik) [reply pkg/kubelet/cm/helpers_linux.go:172]: But that is exactly what is wrong wrt to the cpu manager logic. Only containers with an integer value "1" are pinned. "1.0" will not get pinned cpus.

Or course as long as the reviewers say that is ok I am happy with the simplification it brings.

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go [hunk 4]
```diff
@@ -51,7 +51,19 @@ func (m *kubeGenericRuntimeManager) calculateSandboxResources(pod *v1.Pod) *runt
...
-	return m.calculateLinuxResources(cpuRequest, lim.Cpu(), lim.Memory())
+
+	lcr := m.calculateLinuxResources(cpuRequest, lim.Cpu(), lim.Memory())
+	// cfs quota for container is not capped if
+	// 1. cpu manager policy is static
+	// 2. pod has quos PodQOSGuaranteed
+	// 3. container has integer cpu request
+	if m.containerManager.cpuExperimentalManagerPolicyStatic &&
+		kubeapiqos.GetPodQOS(pod) == v1.PodQOSGuaranteed &&
+		cpuRequest.MilliValue() % MilliCPUToCPU == 0 {
```
Comment (MarSik) [inline pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go:62]: I believe this is still disabling quota even when ContainerHasIntCpuReuquest is false.

File: pkg/kubelet/cm/helpers_linux.go (hunk 2 above)
Comment (ffromani) [reply pkg/kubelet/cm/helpers_linux.go:172]: this is why we should have consistent logic, best if in cpumanager (and we can totally do this) :)

**Comment by ffromani** [comment]
just to set expectations right: I for myself didn't make my mind yet between this PR and https://github.com/kubernetes/kubernetes/pull/117030 . Right now I want to unblock the feature gate conversation, which will benefit both efforts.

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go (hunk 4 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go:62]: last item in that if chain `cpuRequest.MilliValue() % MilliCPUToCPU == 0 ` should prevent that

Comment (ffromani) [reply pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go:62]: let's move the logic in the cpumanager, either with the current approach or checking if the container had exclusive cpu assignments. If we keep this logic, which I'm not against, let's add unit test coverage.

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go (hunk 3 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:166]: totally agree would like to see the logic in a single place. unfortunately there is no single shared method I see between sandbox config, pod resource config, and container resource configs.

# Pod Resources

LinuxContainerResources Quota for pod resources is computed in `cm.ResourceConfigForPod`. This method is called from several places, so the computation can't be moved "up" without duplicating the logic, and it can't be moved "down" further to another method because it's built in this method directly using the pod resources. 

```
cm.ResourceConfigForPod
  (constructs ResourceConfig directly from pod resources)
``

calls
* kubelet.SyncPod -> containermanager.EnsureExists -> containermanager.ResourceConfigForPod
* pkg/volume/emptydir/empty_dir
* kuberuntime.SyncPod -> kuberuntime.doPodResizeAction -> containermanager.ResourceConfigForPod

# Sandbox and Container Resources

Right now these are computed, both resources are fetched from `calculateLinuxResources` and then the quota is overwritten when the pinning qualifications are met.

```
calculateSandboxResources -> calculateLinuxResources
generateLinuxContainerConfig -> generateLinuxContainerResources -> calculateLinuxResources
```

# Single-Location Fix? 

The smoothest fix would be to modify `calculateLinuxResources`, that takes care of both container and sandbox computations. Then we could modify ResourceConfigForPod to use `calculateLinuxResources` instead of computing the values directly. The single method would then be used in all cases. could also lock that additional computation behind a feature gate

Comment (ffromani) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:166]: I'm thinking about adding the functionality to query if a pod got (or will get) exclusive CPU assignment in cpumanager, and calling cpumanager in the relevant flows. https://github.com/kubernetes/kubernetes/pull/117030 already does something like it.

Comment (ffromani) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:166]: `pkg/volume/emptydir/empty_dir` seems to be using `ResourceConfigForPod` only to compute in a consistent way the memory values. In this case we can just hardcoded to false the exclusive CPU assignment flag, with a note explaining why.

File: pkg/kubelet/cm/helpers_linux.go (hunk 2 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/helpers_linux.go:172]: its easy enough to check the precision if we wish to disallow "1.0" and only allow "1". let me know what is desired!

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go (hunk 4 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go]: done! will work on adding unit test coverage. let me know if we want to check precision of cpu such that "1" is pinned but "1.0" is not

**Comment by ffromani** [comment]
thanks for yout efforts and for addressing the comments @scott-grimes ! I will have another pass shortly

**Comment by scott-grimes** [comment]
at this point PR all logic is handled by single function

```
StaticCPUPolicyConditionsSatisfied(cpuManagerPolicyName string, podQos v1.PodQOSClass, cpuRequest *apiresource.Quantity) bool
```

in order to accomplish this the following changes were required:

1) addition of `cpuManagerPolicy` to `PodContainerManager` (required since `EnsureExists` only has visibility into pod spec and podContainerManagerImpl within pkg/kubelet/cm/pod_container_manager_linux.go
2) passing pod qos into calculateLinuxResources

(1) handles pod resources computation
(2) handles both container and sandbox computations 

so all use cases discussed above should be met. I've added unit tests as well (both for the logic within the cpu manager and up a level for computation of pod resources and in the kuberuntime for container resources). Unfortunately I'm having issues with the `FakeContainerManager` due to my ignorance around golang testing.

---

in [pkg/kubelet/kuberuntime/kuberuntime_container_linux_test.go](https://github.com/kubernetes/kubernetes/blob/dc397630f65933056a46200e99841bc5ec59c568/pkg/kubelet/kuberuntime/kuberuntime_container_linux_test.go#L473-L479) `TestCalculateLinuxResourcesWithStaticCpuPolicy` should iterate over the possible scenarios above for all combinations of policy enforcement, qos, and cpuRequest values. 

Because `calculateLinuxResources` does a lookup of the `m.containerManager.GetNodeConfig().CPUManagerPolicy` on the fly we need to be able to modify that during each test iteration. 


I'm getting
```
pkg/kubelet/kuberuntime/kuberuntime_container_linux_test.go:475:22: m.containerManager.NodeConfig undefined (type cm.ContainerManager has no field or method NodeConfig)
```

even though `NodeConfig` has been added to the FakeContainerManager struct [here](https://github.com/kubernetes/kubernetes/blob/dc397630f65933056a46200e99841bc5ec59c568/pkg/kubelet/cm/fake_container_manager.go#L46)


That method be re-written to be functional but it already does a few other lookups so I think at this point we're blocked on

1) featuregate
2) decision about use of precision (do we allow "1.0" or only "1")
3) unit test configuration for containerManager.NodeConfig

any pointers for overcoming the unit test issues much appreciated!

**Comment by ffromani** [comment]
/retest

likely a flake (which we should report)

**Comment by ffromani** [comment]
uhm, it's failing repeatedly in `kuberuntime`. Looks actually legit.

**Comment by scott-grimes** [comment]
/retest

pod scheduling timeout

**Comment by scott-grimes** [comment]
/retest

pull-kubernetes-e2e-kind-ipv6

`NoSNAT Should be able to send traffic between Pods without SNAT `

**Comment by ffromani** [comment]
sig-node feedback after mtg Oct 8, 2024: 
- The fix must be in effect iff there are CPU exclusively assigned to pod and the cpumanager policy is static (implied by exclusive cpu assignment)
- to address the concerns about unexpected side effects, the SIG agrees we can use a Feature Gate. (see: https://kubernetes.slack.com/archives/C5P3FE08M/p1727072265347319)
- the Feature Gate will start enabled, because we will merge a fix we will are confident about
- the Feature Gate will be time-bound, say +3 releases
- if we get issues related to the fix, we will iterate over the fix; affected users can use the Feature Gate to restore the old behavior
- if no issues reported in the allotted time, the Feature Gate will be locked to on and removed.
- we need to coordinate the two concurrent fixes being proposed: #117030 and #127525

**Comment by ffromani** [comment]
proposed feature gate name: `LegacyCPUQuotaManagement`

File: pkg/kubelet/cm/cpumanager/cpu_manager.go [hunk 5]
```diff
@@ -514,6 +518,17 @@ func findContainerStatusByName(status *v1.PodStatus, name string) (*v1.Container
 	return nil, fmt.Errorf("unable to find status for container with name %v in pod status (it may not be running)", name)
 }
 
+func StaticCPUPolicyConditionsSatisfied(cpuManagerPolicyName string, podQos v1.PodQOSClass, cpuRequest *apiresource.Quantity) bool {
```
Comment (ffromani) [inline pkg/kubelet/cm/cpumanager/cpu_manager.go:521]: I'd use the same API proposed here: https://github.com/kubernetes/kubernetes/pull/117030/files#diff-c11864857fa45d5c2d29c3a85d753ccd2db31cca1c7fa046b7144e71f6e59029R407

I'd be fine with a different implementation, but the information I'd like to expose is if there are exclusive CPUs assigned to the container, rather than redo this logic.

File: pkg/kubelet/cm/helpers_linux.go [hunk 6]
```diff
@@ -159,14 +164,16 @@ func ResourceConfigForPod(pod *v1.Pod, enforceCPULimits bool, cpuPeriod uint64,
 	cpuShares := MilliCPUToShares(cpuRequests)
 	cpuQuota := MilliCPUToQuota(cpuLimits, int64(cpuPeriod))
 
-	// quota is not capped when cfs quota is disabled
-	if !enforceCPULimits {
+	qosClass := v1qos.GetPodQOS(pod)
+
+	StaticCPUPolicyConditionsSatisfied := cpumanager.StaticCPUPolicyConditionsSatisfied(cpuManagerPolicy, qosClass, &cpuRequestQuantity)
```
Comment (ffromani) [inline pkg/kubelet/cm/helpers_linux.go:169]: likewise, I'd use here `cpumanager.PodContainsPinnedCpus(pod)`

File: pkg/kubelet/cm/helpers_unsupported.go [hunk 7]
```diff
@@ -46,7 +46,7 @@ func MilliCPUToShares(milliCPU int64) int64 {
 }
 
 // ResourceConfigForPod takes the input pod and outputs the cgroup resource config.
-func ResourceConfigForPod(pod *v1.Pod, enforceCPULimit bool, cpuPeriod uint64, enforceMemoryQoS bool) *ResourceConfig {
+func ResourceConfigForPod(pod *v1.Pod, enforceCPULimit bool, cpuPeriod uint64, enforceMemoryQoS bool, cpuManagerPolicy string) *ResourceConfig {
```
Comment (ffromani) [inline pkg/kubelet/cm/helpers_unsupported.go:49]: if we use the API `PodContainsPinnedCpus` (or something like it), we don't need a new parameter, and we have less coupling anyway.

**Review by ffromani — CHANGES_REQUESTED** [review]

File: pkg/kubelet/cm/helpers_unsupported.go (hunk 7 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/helpers_unsupported.go:49]: hmm one issue with relying on `PodContainsPinnedCpus` in cpu_manager is that ResourceConfigForPod as a function does not have access to the cpumanager state. If we go down that path then `ResourceConfigForPod` will sometimes return know-to-be-incorrect ResourceConfigs. That's not intuitive and will surely lead to errors down the road. I think it's cleaner if `ResourceConfigForPod` always returns what we expect the correct `ResourceConfig` to be given the current kubelet settings. 

I like the idea of a method `PodContainsPinnedCpus`, but we also need a way to determine prior to assignment if a pod *should* be allocated a pinned cpu so that the cgroup can be configured correctly from the get-go for both containers/sandbox etc

Comment (MarSik) [reply pkg/kubelet/cm/helpers_unsupported.go:49]: Yeah, that was the main implementation issue I had. So my implementation did this at runtime after the pinned container started. That was the "best" I could do to satisfy the request.

Comment (ffromani) [reply pkg/kubelet/cm/helpers_unsupported.go:49]: I'm still evaluating options. I agree about setting correct values from the beginning is strongly preferred.

Comment (ffromani) [reply pkg/kubelet/cm/helpers_unsupported.go:49]: Resuming this issue. I'm about to open the code, but if we are at the point on which we are creating the pod sandbox (for which we need the resource config), then the pod admission completed, then the cpumanager state is already set, then calling `PodContainsPinnedCpus` should return the correct thing. Anything I'm missing from this picture?

Comment (ffromani) [reply pkg/kubelet/cm/helpers_unsupported.go:49]: The following seems a promising way forward:
```
diff --git a/pkg/kubelet/cm/container_manager.go b/pkg/kubelet/cm/container_manager.go
index 70edb484109..4d7b8b6cd63 100644
--- a/pkg/kubelet/cm/container_manager.go
+++ b/pkg/kubelet/cm/container_manager.go
@@ -146,6 +146,9 @@ type ContainerManager interface {
 	// Updates returns a channel that receives an Update when the device changed its status.
 	Updates() <-chan resourceupdates.Update
 
+	// TODO
+	HasExclusiveCPUs(pod *v1.Pod) bool
+
 	// Implements the PodResources Provider API
 	podresources.CPUsProvider
 	podresources.DevicesProvider
diff --git a/pkg/kubelet/cm/container_manager_linux.go b/pkg/kubelet/cm/container_manager_linux.go
index 78d3366750e..d09f03acd02 100644
--- a/pkg/kubelet/cm/container_manager_linux.go
+++ b/pkg/kubelet/cm/container_manager_linux.go
@@ -363,7 +363,7 @@ func (cm *containerManagerImpl) NewPodContainerManager() PodContainerManager {
 			// cpuCFSQuotaPeriod is in microseconds. NodeConfig.CPUCFSQuotaPeriod is time.Duration (measured in nano seconds).
 			// Convert (cm.CPUCFSQuotaPeriod) [nanoseconds] / time.Microsecond (1000) to get cpuCFSQuotaPeriod in microseconds.
 			cpuCFSQuotaPeriod: uint64(cm.CPUCFSQuotaPeriod / time.Microsecond),
-			cpuManagerPolicy:  cm.GetNodeConfig().CPUManagerPolicy,
+			podCPUProvider:    cm,
 		}
 	}
 	return &podContainerManagerNoop{
@@ -371,6 +371,19 @@ func (cm *containerManagerImpl) NewPodContainerManager() PodContainerManager {
 	}
 }
 
+func (cm *containerManagerImpl) HasExclusiveCPUs(pod *v1.Pod) bool {
+	for _, container := range pod.Spec.Containers {
+		exclusiveCPUs := cm.cpuManager.GetExclusiveCPUs(string(pod.UID), container.Name)
+		if !exclusiveCPUs.IsEmpty() {
+			klog.V(4).InfoS("Pod contains container with pinned cpus", "podName", pod.Name, "containerName", container.Name)
+			return true
+		}
+	}
+
+	klog.V(4).InfoS("Pod contains no container with pinned cpus", "podName", pod.Name)
+	return false
+}
+
 func (cm *containerManagerImpl) InternalContainerLifecycle() InternalContainerLifecycle {
 	return &internalContainerLifecycleImpl{cm.cpuManager, cm.memoryManager, cm.topologyManager}
 }
diff --git a/pkg/kubelet/cm/container_manager_stub.go b/pkg/kubelet/cm/container_manager_stub.go
index 35aeee36724..b796e5dc263 100644
--- a/pkg/kubelet/cm/container_manager_stub.go
+++ b/pkg/kubelet/cm/container_manager_stub.go
@@ -190,6 +190,10 @@ func (cm *containerManagerStub) Updates() <-chan resourceupdates.Update {
 	return nil
 }
 
+func (cm *containerManagerStub) HasExclusiveCPUs(pod *v1.Pod) bool {
+	return false
+}
+
 func NewStubContainerManager() ContainerManager {
 	return &containerManagerStub{shouldResetExtendedResourceCapacity: false}
 }
diff --git a/pkg/kubelet/cm/container_manager_windows.go b/pkg/kubelet/cm/container_manager_windows.go
index 232d121223a..0d825e6b2e5 100644
--- a/pkg/kubelet/cm/container_manager_windows.go
+++ b/pkg/kubelet/cm/container_manager_windows.go
@@ -285,3 +285,7 @@ func (cm *containerManagerImpl) UnprepareDynamicResources(ctx context.Context, p
 func (cm *containerManagerImpl) PodMightNeedToUnprepareResources(UID types.UID) bool {
 	return false
 }
+
+func (cm *containerManagerImpl) HasExclusiveCPUs(pod *v1.Pod) bool {
+	return false
+}
diff --git a/pkg/kubelet/cm/fake_container_manager.go b/pkg/kubelet/cm/fake_container_manager.go
index f3f6c6eb509..3abe9c842a7 100644
--- a/pkg/kubelet/cm/fake_container_manager.go
+++ b/pkg/kubelet/cm/fake_container_manager.go
@@ -260,3 +260,7 @@ func (cm *FakeContainerManager) UpdateAllocatedResourcesStatus(pod *v1.Pod, stat
 func (cm *FakeContainerManager) Updates() <-chan resourceupdates.Update {
 	return nil
 }
+
+func (cm *FakeContainerManager) HasExclusiveCPUs(pod *v1.Pod) bool {
+	return false
+}
diff --git a/pkg/kubelet/cm/helpers_linux.go b/pkg/kubelet/cm/helpers_linux.go
index bd564d1398d..ebd19cc695b 100644
--- a/pkg/kubelet/cm/helpers_linux.go
+++ b/pkg/kubelet/cm/helpers_linux.go
@@ -25,10 +25,8 @@ import (
 
 	libcontainercgroups "github.com/opencontainers/runc/libcontainer/cgroups"
 	v1 "k8s.io/api/core/v1"
-	apiresource "k8s.io/apimachinery/pkg/api/resource"
 	"k8s.io/apimachinery/pkg/types"
 	utilfeature "k8s.io/apiserver/pkg/util/feature"
-	"k8s.io/kubernetes/pkg/kubelet/cm/cpumanager"
 
 	podutil "k8s.io/kubernetes/pkg/api/v1/pod"
 	"k8s.io/kubernetes/pkg/api/v1/resource"
@@ -120,7 +118,7 @@ func HugePageLimits(resourceList v1.ResourceList) map[int64]int64 {
 }
 
 // ResourceConfigForPod takes the input pod and outputs the cgroup resource config.
-func ResourceConfigForPod(pod *v1.Pod, enforceCPULimits bool, cpuPeriod uint64, enforceMemoryQoS bool, cpuManagerPolicy string) *ResourceConfig {
+func ResourceConfigForPod(pod *v1.Pod, enforceCPULimits bool, cpuPeriod uint64, enforceMemoryQoS bool) *ResourceConfig {
 	inPlacePodVerticalScalingEnabled := utilfeature.DefaultFeatureGate.Enabled(kubefeatures.InPlacePodVerticalScaling)
 	// sum requests and limits.
 	reqs := resource.PodRequests(pod, resource.PodResourcesOptions{
@@ -147,10 +145,8 @@ func ResourceConfigForPod(pod *v1.Pod, enforceCPULimits bool, cpuPeriod uint64,
 	cpuRequests := int64(0)
 	cpuLimits := int64(0)
 	memoryLimits := int64(0)
-	var cpuRequestQuantity apiresource.Quantity
 
 	if request, found := reqs[v1.ResourceCPU]; found {
-		cpuRequestQuantity = request
 		cpuRequests = request.MilliValue()
 	}
 	if limit, found := limits[v1.ResourceCPU]; found {
@@ -166,11 +162,9 @@ func ResourceConfigForPod(pod *v1.Pod, enforceCPULimits bool, cpuPeriod uint64,
 
 	qosClass := v1qos.GetPodQOS(pod)
 
-	StaticCPUPolicyConditionsSatisfied := cpumanager.StaticCPUPolicyConditionsSatisfied(cpuManagerPolicy, qosClass, &cpuRequestQuantity)
-
 	// quota is not capped when cfs quota is disabled,
 	// or if static cpu policy conditions are satisfied
-	if !enforceCPULimits || StaticCPUPolicyConditionsSatisfied {
+	if !enforceCPULimits {
 		cpuQuota = int64(-1)
 	}
 
diff --git a/pkg/kubelet/cm/helpers_linux_test.go b/pkg/kubelet/cm/helpers_linux_test.go
index b6ea8129b07..df36e4ade79 100644
--- a/pkg/kubelet/cm/helpers_linux_test.go
+++ b/pkg/kubelet/cm/helpers_linux_test.go
@@ -357,7 +357,7 @@ func TestResourceConfigForPod(t *testing.T) {
 
 	for testName, testCase := range testCases {
 
-		actual := ResourceConfigForPod(testCase.pod, testCase.enforceCPULimits, testCase.quotaPeriod, false, testCase.cmPolicy)
+		actual := ResourceConfigForPod(testCase.pod, testCase.enforceCPULimits, testCase.quotaPeriod, false)
 
 		if !reflect.DeepEqual(actual.CPUPeriod, testCase.expected.CPUPeriod) {
 			t.Errorf("unexpected result, test: %v, cpu period not as expected. Expected: %v, Actual:%v", testName, *testCase.expected.CPUPeriod, *actual.CPUPeriod)
diff --git a/pkg/kubelet/cm/helpers_unsupported.go b/pkg/kubelet/cm/helpers_unsupported.go
index c22d384b7ba..526dd8fd7db 100644
--- a/pkg/kubelet/cm/helpers_unsupported.go
+++ b/pkg/kubelet/cm/helpers_unsupported.go
@@ -20,7 +20,7 @@ limitations under the License.
 package cm
 
 import (
-	"k8s.io/api/core/v1"
+	v1 "k8s.io/api/core/v1"
 	"k8s.io/apimachinery/pkg/types"
 )
 
@@ -46,7 +46,7 @@ func MilliCPUToShares(milliCPU int64) int64 {
 }
 
 // ResourceConfigForPod takes the input pod and outputs the cgroup resource config.
-func ResourceConfigForPod(pod *v1.Pod, enforceCPULimit bool, cpuPeriod uint64, enforceMemoryQoS bool, cpuManagerPolicy string) *ResourceConfig {
+func ResourceConfigForPod(pod *v1.Pod, enforceCPULimit bool, cpuPeriod uint64, enforceMemoryQoS bool) *ResourceConfig {
 	return nil
 }
 
diff --git a/pkg/kubelet/cm/pod_container_manager_linux.go b/pkg/kubelet/cm/pod_container_manager_linux.go
index 69df8a5d779..541343aa6d7 100644
--- a/pkg/kubelet/cm/pod_container_manager_linux.go
+++ b/pkg/kubelet/cm/pod_container_manager_linux.go
@@ -37,6 +37,11 @@ const (
 	podCgroupNamePrefix = "pod"
 )
 
+// name TBD
+type podCPUProvider interface {
+	HasExclusiveCPUs(pod *v1.Pod) bool
+}
+
 // podContainerManagerImpl implements podContainerManager interface.
 // It is the general implementation which allows pod level container
 // management if qos Cgroup is enabled.
@@ -55,8 +60,8 @@ type podContainerManagerImpl struct {
 	// cpuCFSQuotaPeriod is the cfs period value, cfs_period_us, setting per
 	// node for all containers in usec
 	cpuCFSQuotaPeriod uint64
-	// cpuManagerPolicy is the cpu manager policy
-	cpuManagerPolicy string
+	// TODO
+	podCPUProvider podCPUProvider
 }
 
 // Make sure that podContainerManagerImpl implements the PodContainerManager interface
@@ -74,6 +79,10 @@ func (m *podContainerManagerImpl) Exists(pod *v1.Pod) bool {
 func (m *podContainerManagerImpl) EnsureExists(pod *v1.Pod) error {
 	// check if container already exist
 	alreadyExists := m.Exists(pod)
+	enforceCPULimits := m.enforceCPULimits
+	if m.podCPUProvider.HasExclusiveCPUs(pod) {
+		enforceCPULimits = false
+	}
 	if !alreadyExists {
 		enforceMemoryQoS := false
 		if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.MemoryQoS) &&
@@ -84,7 +93,7 @@ func (m *podContainerManagerImpl) EnsureExists(pod *v1.Pod) error {
 		podContainerName, _ := m.GetPodContainerName(pod)
 		containerConfig := &CgroupConfig{
 			Name:               podContainerName,
-			ResourceParameters: ResourceConfigForPod(pod, m.enforceCPULimits, m.cpuCFSQuotaPeriod, enforceMemoryQoS, m.cpuManagerPolicy),
+			ResourceParameters: ResourceConfigForPod(pod, enforceCPULimits, m.cpuCFSQuotaPeriod, enforceMemoryQoS),
 		}
 		if m.podPidsLimit > 0 {
 			containerConfig.ResourceParameters.PidsLimit = &m.podPidsLimit
diff --git a/pkg/kubelet/kuberuntime/kuberuntime_manager.go b/pkg/kubelet/kuberuntime/kuberuntime_manager.go
index 86f96565c3b..2f045335ab0 100644
--- a/pkg/kubelet/kuberuntime/kuberuntime_manager.go
+++ b/pkg/kubelet/kuberuntime/kuberuntime_manager.go
@@ -665,7 +665,11 @@ func (m *kubeGenericRuntimeManager) computePodResizeAction(pod *v1.Pod, containe
 func (m *kubeGenericRuntimeManager) doPodResizeAction(pod *v1.Pod, podStatus *kubecontainer.PodStatus, podContainerChanges podActions, result kubecontainer.PodSyncResult) {
 	pcm := m.containerManager.NewPodContainerManager()
 	//TODO(vinaykul,InPlacePodVerticalScaling): Figure out best way to get enforceMemoryQoS value (parameter #4 below) in platform-agnostic way
-	podResources := cm.ResourceConfigForPod(pod, m.cpuCFSQuota, uint64((m.cpuCFSQuotaPeriod.Duration)/time.Microsecond), false, m.containerManager.GetNodeConfig().CPUManagerPolicy)
+	enforceCPULimits := m.cpuCFSQuota
+	if m.containerManager.HasExclusiveCPUs(pod) {
+		enforceCPULimits = false
+	}
+	podResources := cm.ResourceConfigForPod(pod, enforceCPULimits, uint64((m.cpuCFSQuotaPeriod.Duration)/time.Microsecond), false)
 	if podResources == nil {
 		klog.ErrorS(nil, "Unable to get resource configuration", "pod", pod.Name)
 		result.Fail(fmt.Errorf("Unable to get resource configuration processing resize for pod %s", pod.Name))
diff --git a/pkg/volume/emptydir/empty_dir.go b/pkg/volume/emptydir/empty_dir.go
index 83d62977635..1d685ae83da 100644
--- a/pkg/volume/emptydir/empty_dir.go
+++ b/pkg/volume/emptydir/empty_dir.go
@@ -18,10 +18,11 @@ package emptydir
 
 import (
 	"fmt"
-	"k8s.io/kubernetes/pkg/kubelet/util/swap"
 	"os"
 	"path/filepath"
 
+	"k8s.io/kubernetes/pkg/kubelet/util/swap"
+
 	"k8s.io/klog/v2"
 	"k8s.io/mount-utils"
 	utilstrings "k8s.io/utils/strings"
@@ -123,7 +124,7 @@ func calculateEmptyDirMemorySize(nodeAllocatableMemory *resource.Quantity, spec
 	// determine pod resource allocation
 	// we use the same function for pod cgroup assignment to maintain consistent behavior
 	// NOTE: this could be nil on systems that do not support pod memory containment (i.e. windows)
-	podResourceConfig := cm.ResourceConfigForPod(pod, false, uint64(100000), false, "none")
+	podResourceConfig := cm.ResourceConfigForPod(pod, false, uint64(100000), false)
 	if podResourceConfig != nil && podResourceConfig.Memory != nil {
 		podMemoryLimit := resource.NewQuantity(*(podResourceConfig.Memory), resource.BinarySI)
 		// ensure 0 < value < size
```

Comment (ffromani) [reply pkg/kubelet/cm/helpers_unsupported.go:49]: in any case, we need to add the new feature gate

Comment (ffromani) [reply pkg/kubelet/cm/helpers_unsupported.go:49]: adding a sketch with a feature gate; needs more work, but this is the general idea
```
diff --git a/pkg/features/kube_features.go b/pkg/features/kube_features.go
index 11fb8d88055..8346db18792 100644
--- a/pkg/features/kube_features.go
+++ b/pkg/features/kube_features.go
@@ -938,6 +938,12 @@ const (
 	//
 	// Enables the image volume source.
 	ImageVolume featuregate.Feature = "ImageVolume"
+
+	// owner: @ffromani
+	// beta: v1.31
+	//
+	// Disable CPU Quota for pods which have exclusive CPUs allocated
+	DisableCPUQuotaWithExclusiveCPUs featuregate.Feature = "DisableCPUQuotaWithExclusiveCPUs"
 )
 
 func init() {
diff --git a/pkg/features/versioned_kube_features.go b/pkg/features/versioned_kube_features.go
index 6398233b835..2bee975f01f 100644
--- a/pkg/features/versioned_kube_features.go
+++ b/pkg/features/versioned_kube_features.go
@@ -435,4 +435,7 @@ var defaultVersionedKubernetesFeatureGates = map[featuregate.Feature]featuregate
 	KubeletRegistrationGetOnExistsOnly: {
 		{Version: version.MustParse("1.32"), Default: false, PreRelease: featuregate.Deprecated},
 	},
+	DisableCPUQuotaWithExclusiveCPUs: {
+		{Version: version.MustParse("1.32"), Default: true, PreRelease: featuregate.Beta},
+	},
 }
diff --git a/pkg/kubelet/cm/pod_container_manager_linux.go b/pkg/kubelet/cm/pod_container_manager_linux.go
index 541343aa6d7..af541d50f35 100644
--- a/pkg/kubelet/cm/pod_container_manager_linux.go
+++ b/pkg/kubelet/cm/pod_container_manager_linux.go
@@ -80,8 +80,10 @@ func (m *podContainerManagerImpl) EnsureExists(pod *v1.Pod) error {
 	// check if container already exist
 	alreadyExists := m.Exists(pod)
 	enforceCPULimits := m.enforceCPULimits
-	if m.podCPUProvider.HasExclusiveCPUs(pod) {
-		enforceCPULimits = false
+	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.DisableCPUQuotaWithExclusiveCPUs) {
+		if m.podCPUProvider.HasExclusiveCPUs(pod) {
+			enforceCPULimits = false
+		}
 	}
 	if !alreadyExists {
 		enforceMemoryQoS := false
diff --git a/pkg/kubelet/kuberuntime/kuberuntime_manager.go b/pkg/kubelet/kuberuntime/kuberuntime_manager.go
index 2f045335ab0..f3216f8111a 100644
--- a/pkg/kubelet/kuberuntime/kuberuntime_manager.go
+++ b/pkg/kubelet/kuberuntime/kuberuntime_manager.go
@@ -51,6 +51,7 @@ import (
 	"k8s.io/kubernetes/pkg/credentialprovider"
 	"k8s.io/kubernetes/pkg/credentialprovider/plugin"
 	"k8s.io/kubernetes/pkg/features"
+	kubefeatures "k8s.io/kubernetes/pkg/features"
 	"k8s.io/kubernetes/pkg/kubelet/cm"
 	kubecontainer "k8s.io/kubernetes/pkg/kubelet/container"
 	"k8s.io/kubernetes/pkg/kubelet/events"
@@ -666,8 +667,10 @@ func (m *kubeGenericRuntimeManager) doPodResizeAction(pod *v1.Pod, podStatus *ku
 	pcm := m.containerManager.NewPodContainerManager()
 	//TODO(vinaykul,InPlacePodVerticalScaling): Figure out best way to get enforceMemoryQoS value (parameter #4 below) in platform-agnostic way
 	enforceCPULimits := m.cpuCFSQuota
-	if m.containerManager.HasExclusiveCPUs(pod) {
-		enforceCPULimits = false
+	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.DisableCPUQuotaWithExclusiveCPUs) {
+		if m.containerManager.HasExclusiveCPUs(pod) {
+			enforceCPULimits = false
+		}
 	}
 	podResources := cm.ResourceConfigForPod(pod, enforceCPULimits, uint64((m.cpuCFSQuotaPeriod.Duration)/time.Microsecond), false)
 	if podResources == nil {
```

Comment (scott-grimes) [reply pkg/kubelet/cm/helpers_unsupported.go]: @ffromani done.

added feature gate, incorporated above changes to surface pinned cpus via new interface method. 

that takes care of all calls from within `ResourceConfigForPod`, which can remain untouched by this PR.

We still need some way to determine if the cfsQuota should be removed inside `calculateLinuxResources` as that's called from a number of other places. 

I've kept the `StaticCPUPolicyConditionsSatisfied` method (takes qos, cpu req, policyname), locked behind feature gate. I also swapped to use the same computation logic as the static policy so we're consistent in how we determine if a cpu request satsifies the policy constraints:

```
cpuRequest.Value()*1000 == cpuRequest.MilliValue()
```

let me know what you think

File: pkg/kubelet/cm/cpumanager/cpu_manager.go [hunk 8]
```diff
@@ -97,6 +97,9 @@ type Manager interface {
 	// GetAllCPUs returns all the CPUs known by cpumanager, as reported by the
 	// hardware discovery. Maps to the CPU capacity.
 	GetAllCPUs() cpuset.CPUSet
+
+	// Check whether any container within a pod uses exclusive cpus
+	PodContainsPinnedCpus(pod *v1.Pod) bool
```
Comment (ffromani) [inline pkg/kubelet/cm/cpumanager/cpu_manager.go:102]: Is this needed now? I think we want to use the equivalent `HasExclusiveCPUs` interface, if so we can drop this earlier suggestion

File: pkg/kubelet/cm/cpumanager/cpu_manager.go [hunk 9]
```diff
@@ -503,6 +519,16 @@ func (m *manager) reconcileState() (success []reconciledContainer, failure []rec
...
+func StaticCPUPolicyConditionsSatisfied(cpuManagerPolicyName string, podQos v1.PodQOSClass, cpuRequest *apiresource.Quantity) bool {
+	// returns true if
+	// 1. cpu manager policy is static
+	// 2. pod has quos PodQOSGuaranteed
+	// 3. container has integer cpu request
+	return cpuManagerPolicyName == string(PolicyStatic) &&
+		podQos == v1.PodQOSGuaranteed &&
+		cpuRequest.Value()*1000 == cpuRequest.MilliValue()
+}
+
```
Comment (ffromani) [inline pkg/kubelet/cm/cpumanager/cpu_manager.go:531]: this seems to be used only in tests (and it's stateless, which is good). If so, let's move it into test code.
I'm not convinced we _need_ it for tests, but let's start moving it there.

File: pkg/kubelet/cm/cpumanager/cpu_manager_test.go [hunk 10]
```diff
@@ -1470,3 +1470,93 @@ func TestCPUManagerGetAllocatableCPUs(t *testing.T) {
 		}
 	}
 }
+
+func TestStaticCPUPolicyConditionsSatisfied(t *testing.T) {
```
Comment (ffromani) [inline pkg/kubelet/cm/cpumanager/cpu_manager_test.go:1474]: if used only in tests, this set of tests is no longer needed

File: pkg/kubelet/cm/helpers_linux.go [hunk 11]
```diff
@@ -159,14 +160,14 @@ func ResourceConfigForPod(pod *v1.Pod, enforceCPULimits bool, cpuPeriod uint64,
 	cpuShares := MilliCPUToShares(cpuRequests)
 	cpuQuota := MilliCPUToQuota(cpuLimits, int64(cpuPeriod))
 
-	// quota is not capped when cfs quota is disabled
+	qosClass := v1qos.GetPodQOS(pod)
+
+	// quota is not capped when cfs quota is disabled,
+	// or if static cpu policy conditions are satisfied
```
Comment (ffromani) [inline pkg/kubelet/cm/helpers_linux.go:166]: this change seems to be unnecessary, we can (and should) minimize the changeset

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 12]
```diff
@@ -100,7 +101,7 @@ func (m *kubeGenericRuntimeManager) generateLinuxContainerResources(pod *v1.Pod,
 	if _, cpuRequestExists := container.Resources.Requests[v1.ResourceCPU]; cpuRequestExists {
 		cpuRequest = container.Resources.Requests.Cpu()
 	}
-	lcr := m.calculateLinuxResources(cpuRequest, container.Resources.Limits.Cpu(), container.Resources.Limits.Memory())
+	lcr := m.calculateLinuxResources(cpuRequest, container.Resources.Limits.Cpu(), container.Resources.Limits.Memory(), kubeapiqos.GetPodQOS(pod))
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:104]: here we have the pod for which the resources are been computed, so we can call `m.containerManager.HasExclusiveCPUs(pod)` and pass down the flag.

I need to review carefully the flow to check for possible issues but it seems doable.

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go [hunk 13]
```diff
@@ -51,7 +51,8 @@ func (m *kubeGenericRuntimeManager) calculateSandboxResources(pod *v1.Pod) *runt
 	if _, cpuRequestExists := req[v1.ResourceCPU]; cpuRequestExists {
 		cpuRequest = req.Cpu()
 	}
-	return m.calculateLinuxResources(cpuRequest, lim.Cpu(), lim.Memory())
+
+	return m.calculateLinuxResources(cpuRequest, lim.Cpu(), lim.Memory(), kubeapiqos.GetPodQOS(pod))
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go:55]: likewise, here we can call `m.containerManager.HasExclusiveCPUs(pod)` and pass down the flag

**Review by ffromani — COMMENTED** [review]
thanks for integrating my suggestions! now we can clean up a bit more.
Could you please split the changes on which you add the feature gate in its own commit and add `Co-authored-by: Francesco Romani <fromani@redhat.com>` so I can take care of the feature gate process?

File: pkg/kubelet/cm/cpumanager/cpu_manager.go (hunk 9 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/cpumanager/cpu_manager.go:531]: it is used within `calculateLinuxResources` to set resources.CpuQuota = int64(-1) at https://github.com/kubernetes/kubernetes/pull/127525/files/9037f77dada27c3fdcc6a26cda1db41cce1ade98#diff-f42b5c2632abe72391ae4fa91f7b51ebeb6266c7e10f6d6f472663cf97a493e8R249

instead of passing qos class into calculateLinuxResources we could compute that above and pass something like "cfsQuotaEnforced" to calculateLinuxResources to eliminate this

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go (hunk 12 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:104]: hmm assuming the cpu assignment occurs prior to generateContainerResources being called then yes, will swap out. this also removes need to have `StaticCPUPolicyConditionsSatisfied` defined and called within `calculateLinuxResources`

**Comment by ffromani** [comment]
thanks for the updates @scott-grimes . I will cleanup the unneeded labels added by previous bad rebase. Please do squash commits, in kubernetes we prefer to squash the fixing commits into the base commit rather than having them split. This will also make the review (much) easier as currently this PR holds 33 commits (!).

I'll have another pass later.

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 14]
```diff
@@ -100,7 +100,15 @@ func (m *kubeGenericRuntimeManager) generateLinuxContainerResources(pod *v1.Pod,
 	if _, cpuRequestExists := container.Resources.Requests[v1.ResourceCPU]; cpuRequestExists {
 		cpuRequest = container.Resources.Requests.Cpu()
 	}
-	lcr := m.calculateLinuxResources(cpuRequest, container.Resources.Limits.Cpu(), container.Resources.Limits.Memory())
+
+	// If pod has exclusive cpu and the container in question has integer cpu requests
+	// the cfs quota will not be enforced
+	enforceCfsQuota := true
+	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.DisableCPUQuotaWithExclusiveCPUs) && m.containerManager.HasExclusiveCPUs(pod) && container.Resources.Requests.Cpu().Value()*1000 == container.Resources.Requests.Cpu().MilliValue() {
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:107]: `HasExclusiveCPUs()` will return `true` if and only if the request value is integer, that's guaranteed and enforced by cpumanager, so we can remove that rendundant guard - and reduce the coupling between subsystems.

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 15]
```diff
@@ -244,6 +252,9 @@ func (m *kubeGenericRuntimeManager) calculateLinuxResources(cpuRequest, cpuLimit
 		cpuQuota := milliCPUToQuota(cpuLimit.MilliValue(), cpuPeriod)
 		resources.CpuQuota = cpuQuota
 		resources.CpuPeriod = cpuPeriod
+		if !enforceCpuLimit {
+			resources.CpuQuota = int64(-1)
+		}
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:257]: please move the code like this (grouping quota settings together)
```
resources.CpuQuota = cpuQuota
if !enforceCpuLimit {
		resources.CpuQuota = int64(-1)
}
resources.CpuPeriod = cpuPeriod
```
(quite) minor: we may want to flip the semantic of the new flag so we use positive conditions:
```
func (m *kubeGenericRuntimeManager) calculateLinuxResources(cpuRequest, cpuLimit, memoryLimit *resource.Quantity, disableCPUQuota bool) *runtimeapi.LinuxContainerResources {
     ...
    if disableCPUQuota {
        resources.CpuQuota = int64(-1)
    }
    ...
}
```

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go [hunk 16]
```diff
@@ -51,7 +52,14 @@ func (m *kubeGenericRuntimeManager) calculateSandboxResources(pod *v1.Pod) *runt
 	if _, cpuRequestExists := req[v1.ResourceCPU]; cpuRequestExists {
 		cpuRequest = req.Cpu()
 	}
-	return m.calculateLinuxResources(cpuRequest, lim.Cpu(), lim.Memory())
+
+	// If pod has exclusive cpu the sandbox will not have cfs quote enforced
+	enforceCfsQuota := true
+	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.DisableCPUQuotaWithExclusiveCPUs) && m.containerManager.HasExclusiveCPUs(pod) {
+		enforceCfsQuota = false
+	}
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go:60]: wrong indentation

**Review by ffromani — COMMENTED** [review]
thanks for the updates! minor comments inside.
Once these are addressed and once the commits are aggressively squashed, ideally down to two (everything but the feature gate, the feature gate, in any order among those) codewise LGTM.

In order to wrap up:
- let's run another pass to ensure all the changed paths are covered by the feature gate to ensure no regression if the feature gate is disabled
- let's look again at testing to get good coverage.
- let's think at at least 1 end-to-end (e2e) test, the more the better.

**Comment by scott-grimes** [comment]
@ffromani all issues addressed (minus the squash I'll do at very end). happy to build e2e test but unclear what best way to proceed here is. two questions. 

the first question is what kind of test(s) are desired: the changes impact the following functions:

`calculateLinuxResources` via
* `generateLinuxContainerConfig`
* `calculateSandboxResources`

`ResourceConfigForPod` via
*`computePodResizeAction`
* `EnsureExists`
* `Exists`

are you simply wanting to test `HasExclusiveCPUs` within `pkg/kubelet/cm/container_manager.go`?  or are you wanting a test like of the impacted functions like  https://github.com/kubernetes/kubernetes/blob/d0eb989ca421549d680add0b658e4f5fee8066dd/pkg/kubelet/kuberuntime/kuberuntime_container_linux_test.go#L1088 ?

the second question is that I'm unsure what the expected pattern is to mock `HasExclusiveCPUs()` during testing. any e2e test will require the containermanager return correct value for `HasExclusiveCPUs` but the FakeContainerManager always returns false

```
func (cm *FakeContainerManager) HasExclusiveCPUs(pod *v1.Pod) bool {
	return false
}
```

should the `HasExclusiveCPUs` be shimmed out ala https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container_linux_test.go#L1217-L1221 so it can be mocked only for testing purposes?

**Comment by ffromani** [comment]
@scott-grimes thanks for the updates. It seems CI is unhappy, could you PTAL?
about e2e test, I'd like something like `test/e2e_node/cpu_manager_test.go`. We should actually run pods and verify the cgroup settings and CPU assignment, at least a guaranteed pod, a bustable pod, a best-effort pod.

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go (hunk 15 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:256]: done

**Comment by scott-grimes** [comment]
@ffromani added e2e, a best-effort, burstable, and two guaranteed pods with/without pinning expected. is first attempt so any feedback appreciated

1) read through the [e2e framework](https://github.com/kubernetes-sigs/e2e-framework/blob/main/docs/design/README.md) but could not find out how to ensure these tests land on a node with the cpustatic policy enabled. Unclear how custom nodes are expected to be defined in/with https://pkg.go.dev/k8s.io/kubernetes/test/e2e/framework/node in conj w/ this test

2) https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/127525/pull-kubernetes-typecheck/1851668028081573888 is failing due to   
  a) `feature.DisableCPUQuotaWithExclusiveCPUs not found`
  b) `undefined: resourcehelper.PodResourcesOptions` 

(a) is cleared defined in the PR so not sure if the test is somehow picking up the version on master?

(b) is also very weird because this PR does not touch any of those lines, and PodResourcesOptions is defined at https://pkg.go.dev/k8s.io/kubernetes/pkg/api/v1/resource?

File: pkg/kubelet/cm/container_manager.go [hunk 17]
```diff
@@ -146,6 +146,9 @@ type ContainerManager interface {
 	// Updates returns a channel that receives an Update when the device changed its status.
```
Comment (ffromani) [inline pkg/kubelet/cm/container_manager.go:146]: please reword the commit message to describe the change (you'r not adding just "e2e tests").
Probably got garbled in the rebase/squash.

**Comment by ffromani** [comment]
once the e2e test is fixed/moved in the right place (`test/e2e_node`) we should be good to go

File: pkg/kubelet/cm/pod_container_manager_linux.go [hunk 18]
```diff
@@ -72,6 +74,10 @@ func (m *podContainerManagerImpl) Exists(pod *v1.Pod) bool {
 func (m *podContainerManagerImpl) EnsureExists(pod *v1.Pod) error {
 	// check if container already exist
 	alreadyExists := m.Exists(pod)
+	enforceCPULimits := m.enforceCPULimits
+	if m.podContainerManager.HasExclusiveCPUs(pod) {
```
Comment (ffromani) [inline pkg/kubelet/cm/pod_container_manager_linux.go:78]: let's add the feature gate check here:
```
if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.DisableCPUQuotaWithExclusiveCPUs) && m.podContainerManager.HasExclusiveCPUs(pod) {
    ...
```

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 19]
```diff
@@ -653,7 +653,11 @@ func (m *kubeGenericRuntimeManager) computePodResizeAction(pod *v1.Pod, containe
 func (m *kubeGenericRuntimeManager) doPodResizeAction(pod *v1.Pod, podStatus *kubecontainer.PodStatus, podContainerChanges podActions, result kubecontainer.PodSyncResult) {
 	pcm := m.containerManager.NewPodContainerManager()
 	//TODO(vinaykul,InPlacePodVerticalScaling): Figure out best way to get enforceMemoryQoS value (parameter #4 below) in platform-agnostic way
-	podResources := cm.ResourceConfigForPod(pod, m.cpuCFSQuota, uint64((m.cpuCFSQuotaPeriod.Duration)/time.Microsecond), false)
+	enforceCPULimits := m.cpuCFSQuota
+	if m.containerManager.HasExclusiveCPUs(pod) {
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:657]: let's add the feature gate check
```
if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.DisableCPUQuotaWithExclusiveCPUs) && m.containerManager.HasExclusiveCPUs(pod) {
    ...
```

Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:657]: done!

File: pkg/kubelet/cm/pod_container_manager_linux.go (hunk 18 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/pod_container_manager_linux.go:78]: done!

File: pkg/kubelet/cm/container_manager.go (hunk 17 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/container_manager.go:154]: done!

File: test/e2e_node/cpu_manager_test.go [hunk 20]
```diff
@@ -710,6 +774,21 @@ func runCPUManagerTests(f *framework.Framework) {
...
 	})
 
+	ginkgo.It("should not enforce CFS quota for containers with static CPUs assigned", func(ctx context.Context) {
+
+		newCfg := configureCPUManagerInKubelet(oldCfg,
+			&cpuManagerKubeletArguments{
+				policyName:                       string(cpumanager.PolicyStatic),
+				reservedSystemCPUs:               cpuset.New(0),
+				enableCPUManagerOptions:          true,
+				disableCPUQuotaWithExclusiveCPUs: true,
```
Comment (ffromani) [inline test/e2e_node/cpu_manager_test.go:784]: we would like another test (please pick the most fitting place here it fits, or feel free to create a new one if noone really fits) where we check that with the feature gate is disabled, no pod gets unlimited quota. Basically let's run all the cases you added but with the feature gate forced to off to ensure and verify users can get the old behavior.

Once that is done, the PR is ready.

**Review by ffromani — COMMENTED** [review]
thanks for your updates @scott-grimes! really some good work in there. I'm very happy with the shape of the current PR. Unfortunately due to the merge frenzy caused by the 1.32 code freeze, we need a last update, but it should be easy to add.
Since you need to resubmit anyway, please add negative test (please see inline comments) to ensure and verify users can get the old behavior using the feature gate if they really want so.

Once that, the PR is done, and thanks again for your awesome work so far!

Processwise, the merge is closed for eveything but critical fixes till the 1.33 cycle starts. We should aiming (and I'll be advocating for) an early merge once the 1.33 cycle opens.

I'm advising _against_ rebases to fix conflicts till the 1.33 cycle opens: that would be wasted work for the aforementioned reasons.

Really awesome work here @scott-grimes ! we're just 2 steps from reaching the goal line, looking forward to more contributions in the future!

**Comment by ffromani** [comment]
/retest

the windows lane is IIRC known broken /flaky and being fixed

**Comment by ffromani** [comment]
Uhm, the test failure look legit (= not a flake). I'll have a look.

File: test/e2e_node/cpu_manager_test.go [hunk 21]
```diff
@@ -710,6 +774,21 @@ func runCPUManagerTests(f *framework.Framework) {
 		runSMTAlignmentPositiveTests(ctx, f, smtLevel)
 	})
 
+	ginkgo.It("should not enforce CFS quota for containers with static CPUs assigned", func(ctx context.Context) {
+
+		newCfg := configureCPUManagerInKubelet(oldCfg,
+			&cpuManagerKubeletArguments{
+				policyName:                       string(cpumanager.PolicyStatic),
+				reservedSystemCPUs:               cpuset.New(0),
+				enableCPUManagerOptions:          true,
```
Comment (ffromani) [inline test/e2e_node/cpu_manager_test.go:783]: should not be related to the test failure, but you probably don't need to enable the options here

File: test/e2e_node/cpu_manager_test.go [hunk 22]
```diff
@@ -557,6 +559,68 @@ func runMultipleCPUContainersGuPod(ctx context.Context, f *framework.Framework)
 	waitForContainerRemoval(ctx, pod.Spec.Containers[1].Name, pod.Name, pod.Namespace)
 }
 
+func runCfsQuotaGuPods(ctx context.Context, f *framework.Framework) {
+	var err error
+	var ctnAttrs []ctnAttribute
+	var pod1, pod2, pod3 *v1.Pod
+	cfsCheckCommand := []string{"sh", "-c", "cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us && sleep 1d"}
```
Comment (ffromani) [inline test/e2e_node/cpu_manager_test.go:566]: this can be the culprit, we need to check the CI OS supports this path

Comment (ffromani) [reply test/e2e_node/cpu_manager_test.go:566]: KernelVersion:6.6.56+,OSImage:Container-Optimized OS from Google,ContainerRuntimeVersion:containerd://1.7.23,KubeletVersion:v1.32.0-beta.0.467+cc29a35d38dd82,KubeProxyVersion:v1.32.0-beta.0.467+cc29a35d38dd82,OperatingSystem:linux,Architecture:amd64,}

File: test/e2e_node/cpu_manager_test.go (hunk 20 above)
Comment (scott-grimes) [reply test/e2e_node/cpu_manager_test.go:784]: done!

File: test/e2e_node/cpu_manager_test.go (hunk 21 above)
Comment (scott-grimes) [reply test/e2e_node/cpu_manager_test.go:783]: removed!

File: pkg/kubelet/cm/container_manager_windows.go [hunk 23]
```diff
@@ -369,3 +369,7 @@ func (cm *containerManagerImpl) UnprepareDynamicResources(ctx context.Context, p
 func (cm *containerManagerImpl) PodMightNeedToUnprepareResources(UID types.UID) bool {
 	return false
 }
+
+func (cm *containerManagerImpl) HasExclusiveCPUs(pod *v1.Pod) bool {
+	return false
+}
```
[the remark this answers is not in the document]
Comment (scott-grimes) [reply pkg/kubelet/cm/container_manager_windows.go]: added!

File: test/e2e_node/cpu_manager_test.go (hunk 22 above)
Comment (ffromani) [reply test/e2e_node/cpu_manager_test.go:566]: ok, then maybe I'm off the mark. Didn't manage to debug the new tests myself yet.

**Review by ffromani — COMMENTED** [review]
/lgtm
/hold

let's iterate and fix the e2e tests. I will add again LGTM if code changes are needed (likely), then we can remove the hold and move on to the approver review (per standard k8s process). Once approved, the change will be merged.

**Comment by ffromani** [comment]
let's also address the CI complaints, the linter errors look legit

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go [hunk 24]
```diff
@@ -23,10 +23,10 @@ import (
 	v1 "k8s.io/api/core/v1"
 	"k8s.io/apimachinery/pkg/api/resource"
 	utilfeature "k8s.io/apiserver/pkg/util/feature"
-	runtimeapi "k8s.io/cri-api/pkg/apis/runtime/v1"
 	"k8s.io/kubernetes/pkg/features"
 
 	resourcehelper "k8s.io/component-helpers/resource"
+	runtimeapi "k8s.io/cri-api/pkg/apis/runtime/v1"
```
[the remark this answers is not in the document]
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go]: still needed, reverted this change looks like gofmt wanted to swap ordering based on previous work

**Comment by ffromani** [comment]
@scott-grimes hey! I'll have some time to play with the e2e test to troubleshoot it.
Could you please edit the release note block in your first message to mention the feature gate `DisableCPUQuotaWithExclusiveCPUs`?

Something like (feel free to amend/reword)
```
Because this fix changes a long-established behavior, users observing a regressions can use the DisableCPUQuotaWithExclusiveCPUs feature gate (default on) to restore the old behavior. Please file issues if you hit issues and have to use the Feature Gate.
```

File: test/e2e_node/cpu_manager_test.go (hunk 22 above)
Comment (ffromani) [reply test/e2e_node/cpu_manager_test.go:566]: Turns out that I was not off the mark too much: the path is for cgroup v1 tests. We default (and recommend) to v2, so I'd assume cgroup v2 in these tests.
Is not worth to check for cgroup v1 correctness. If the tests cover cgroup v2 that's good enough.

TL;DR: the tests are assuming cgroup v1. They must assume (and clearly state so, possibly with an explicit check) they run on a cgroup v2 machine.

**Comment by ffromani** [comment]
(copy-pasted as top-level comment for better visibility. Slightly rephrased.)
The main problem is the path we use in the test containers is for cgroup v1. Nowadays kubernetes defaults (and recommend) to v2, so I'd assume cgroup v2 in these tests.
Is not worth to check for cgroup v1 correctness. If the tests cover cgroup v2 that's good enough.

TL;DR: the tests are assuming cgroup v1. They must assume (and clearly state so, possibly with an explicit check, skipping the e2e test otherwise) they run on a cgroup v2 machine.

**Comment by ffromani** [comment]
thanks @scott-grimes the cgroup checks looks good now. There are few issues left, let's see them:
1. first, the kubelet will crash because the version of the Feature Gate (FG) doesn't match and the 1.33 cycle hasn't started yet. We can add the following commit marking it as WIP/DoNotMerge (DNM) and drop it once the 1.33 cycle starts. You will most likely have to push again anyway:
```
diff --git a/pkg/features/versioned_kube_features.go b/pkg/features/versioned_kube_features.go
index 04bbcae1627..93d96b156cb 100644
--- a/pkg/features/versioned_kube_features.go
+++ b/pkg/features/versioned_kube_features.go
@@ -833,6 +833,6 @@ var defaultVersionedKubernetesFeatureGates = map[featuregate.Feature]featuregate
 	},
 
 	DisableCPUQuotaWithExclusiveCPUs: {
-		{Version: version.MustParse("1.33"), Default: true, PreRelease: featuregate.Beta},
+		{Version: version.MustParse("1.32"), Default: true, PreRelease: featuregate.Beta},
 	},
 }
diff --git a/test/featuregates_linter/test_data/versioned_feature_list.yaml b/test/featuregates_linter/test_data/versioned_feature_list.yaml
index 741995d186c..aa41a760d5c 100644
--- a/test/featuregates_linter/test_data/versioned_feature_list.yaml
+++ b/test/featuregates_linter/test_data/versioned_feature_list.yaml
@@ -399,7 +399,7 @@
   - default: true
     lockToDefault: false
     preRelease: Beta
-    version: "1.33"
+    version: "1.32"
 - name: DisableKubeletCloudCredentialProviders
   versionedSpecs:
   - default: false
```
2. there's a bug in the FG enablement code, but it's trivial to fix:
```
diff --git a/test/e2e_node/cpu_manager_test.go b/test/e2e_node/cpu_manager_test.go
index 5d102ac37cc..4fbdf0e42c4 100644
--- a/test/e2e_node/cpu_manager_test.go
+++ b/test/e2e_node/cpu_manager_test.go
@@ -249,7 +249,7 @@ func configureCPUManagerInKubelet(oldCfg *kubeletconfig.KubeletConfiguration, ku
 	newCfg.FeatureGates["CPUManagerPolicyOptions"] = kubeletArguments.enableCPUManagerOptions
 	newCfg.FeatureGates["CPUManagerPolicyBetaOptions"] = kubeletArguments.enableCPUManagerOptions
 	newCfg.FeatureGates["CPUManagerPolicyAlphaOptions"] = kubeletArguments.enableCPUManagerOptions
-	newCfg.FeatureGates["DisableCPUQuotaWithExclusiveCPUs"] = kubeletArguments.enableCPUManagerOptions
+	newCfg.FeatureGates["DisableCPUQuotaWithExclusiveCPUs"] = kubeletArguments.disableCPUQuotaWithExclusiveCPUs
 
 	newCfg.CPUManagerPolicy = kubeletArguments.policyName
 	newCfg.CPUManagerReconcilePeriod = metav1.Duration{Duration: 1 * time.Second}
```
with the 2 above, the tests WORKSFORME! they run as expected on a development box of mine.

There are still some nice to have changes though:
3. I'd split the testcases in two `It` blocks, and use return guards instead of `if/else` blocks:
```
diff --git a/test/e2e_node/cpu_manager_test.go b/test/e2e_node/cpu_manager_test.go
index 8ef51801fff..ce1c96699f0 100644
--- a/test/e2e_node/cpu_manager_test.go
+++ b/test/e2e_node/cpu_manager_test.go
@@ -798,32 +798,37 @@ func runCPUManagerTests(f *framework.Framework) {
 	})
 
 	ginkgo.It("should not enforce CFS quota for containers with static CPUs assigned", func(ctx context.Context) {
-		if IsCgroup2UnifiedMode() {
-
-			newCfg := configureCPUManagerInKubelet(oldCfg,
-				&cpuManagerKubeletArguments{
-					policyName:                       string(cpumanager.PolicyStatic),
-					reservedSystemCPUs:               cpuset.New(0),
-					disableCPUQuotaWithExclusiveCPUs: true,
-				},
-			)
+		if !IsCgroup2UnifiedMode() {
+			e2eskipper.Skipf("Skipping since CgroupV2 not used")
+		}
 
-			updateKubeletConfig(ctx, f, newCfg, true)
-			runCfsQuotaGuPods(ctx, f, true)
+		newCfg := configureCPUManagerInKubelet(oldCfg,
+			&cpuManagerKubeletArguments{
+				policyName:                       string(cpumanager.PolicyStatic),
+				reservedSystemCPUs:               cpuset.New(0),
+				disableCPUQuotaWithExclusiveCPUs: true,
+			},
+		)
 
-			newCfg = configureCPUManagerInKubelet(oldCfg,
-				&cpuManagerKubeletArguments{
-					policyName:                       string(cpumanager.PolicyStatic),
-					reservedSystemCPUs:               cpuset.New(0),
-					disableCPUQuotaWithExclusiveCPUs: false,
-				},
-			)
+		updateKubeletConfig(ctx, f, newCfg, true)
+		runCfsQuotaGuPods(ctx, f, true)
+	})
 
-			updateKubeletConfig(ctx, f, newCfg, true)
-			runCfsQuotaGuPods(ctx, f, false)
-		} else {
+	ginkgo.It("should keep enforcing the CFS quota for containers with static CPUs assigned and feature gate disabled", func(ctx context.Context) {
+		if !IsCgroup2UnifiedMode() {
 			e2eskipper.Skipf("Skipping since CgroupV2 not used")
 		}
+
+		newCfg := configureCPUManagerInKubelet(oldCfg,
+			&cpuManagerKubeletArguments{
+				policyName:                       string(cpumanager.PolicyStatic),
+				reservedSystemCPUs:               cpuset.New(0),
+				disableCPUQuotaWithExclusiveCPUs: false,
+			},
+		)
+
+		updateKubeletConfig(ctx, f, newCfg, true)
+		runCfsQuotaGuPods(ctx, f, false)
 	})
 
 	f.It("should not reuse CPUs of restartable init containers", nodefeature.SidecarContainers, func(ctx context.Context) {
```

4. we can improve the cleanup so should the tests fail, they won't leak pods (yes, the `cpu_manager_test.go` is bad in this regard. Sad old story.)
```
From 85e59a65b8031a6c2aa1b342be2419f07b7f690f Mon Sep 17 00:00:00 2001
From: Francesco Romani <fromani@redhat.com>
Date: Mon, 18 Nov 2024 02:55:11 -0500
Subject: [PATCH 3/5] fix: cleanup

Signed-off-by: Francesco Romani <fromani@redhat.com>
---
 test/e2e_node/cpu_manager_test.go | 16 +++++++++++++++-
 1 file changed, 15 insertions(+), 1 deletion(-)

diff --git a/test/e2e_node/cpu_manager_test.go b/test/e2e_node/cpu_manager_test.go
index 4fbdf0e42c4..8ef51801fff 100644
--- a/test/e2e_node/cpu_manager_test.go
+++ b/test/e2e_node/cpu_manager_test.go
@@ -560,10 +560,24 @@ func runMultipleCPUContainersGuPod(ctx context.Context, f *framework.Framework)
 }
 
 func runCfsQuotaGuPods(ctx context.Context, f *framework.Framework, disabledCPUQuotaWithExclusiveCPUs bool) {
-
 	var err error
 	var ctnAttrs []ctnAttribute
 	var pod1, pod2, pod3 *v1.Pod
+	var cleanupPods []*v1.Pod
+
+	ginkgo.DeferCleanup(func() {
+		// waitForContainerRemoval takes "long" to complete; if we use the parent ctx we get a
+		// 'deadline expired' message and the cleanup aborts, which we don't want.
+		ctx2 := context.TODO()
+		ginkgo.By("by deleting the pods and waiting for container removal")
+		for _, cleanupPod := range cleanupPods {
+			framework.Logf("deleting pod: %s/%s", cleanupPod.Namespace, cleanupPod.Name)
+			deletePodSyncByName(ctx2, f, cleanupPod.Name)
+			waitForContainerRemoval(ctx2, cleanupPod.Spec.Containers[0].Name, cleanupPod.Name, cleanupPod.Namespace)
+			framework.Logf("deleted pod: %s/%s", cleanupPod.Namespace, cleanupPod.Name)
+		}
+	})
+
 	cfsCheckCommand := []string{"sh", "-c", "cat /sys/fs/cgroup/cpu.max && sleep 1d"}
 	defaultPeriod := "100000"
``` 

5. Now we can reorganize the `runCfsQuotaGuPods` function to do check step-by-step and to use the new cleanup code:
```
diff --git a/test/e2e_node/cpu_manager_test.go b/test/e2e_node/cpu_manager_test.go
index ce1c96699f0..4f6187b4aa1 100644
--- a/test/e2e_node/cpu_manager_test.go
+++ b/test/e2e_node/cpu_manager_test.go
@@ -591,6 +591,18 @@ func runCfsQuotaGuPods(ctx context.Context, f *framework.Framework, disabledCPUQ
 	pod1 = makeCPUManagerPod("gu-pod1", ctnAttrs)
 	pod1.Spec.Containers[0].Command = cfsCheckCommand
 	pod1 = e2epod.NewPodClient(f).CreateSync(ctx, pod1)
+	cleanupPods = append(cleanupPods, pod1)
+
+	ginkgo.By("checking if the expected cfs quota was assigned (GU pod, exclusive CPUs, unlimited)")
+
+	expectedQuota := "100000"
+	if disabledCPUQuotaWithExclusiveCPUs {
+		expectedQuota = "max"
+	}
+	expCFSQuotaRegex := fmt.Sprintf("^%s %s\n$", expectedQuota, defaultPeriod)
+	err = e2epod.NewPodClient(f).MatchContainerOutput(ctx, pod1.Name, pod1.Spec.Containers[0].Name, expCFSQuotaRegex)
+	framework.ExpectNoError(err, "expected log not found in container [%s] of pod [%s]",
+		pod1.Spec.Containers[0].Name, pod1.Name)
 
 	ctnAttrs = []ctnAttribute{
 		{
@@ -602,6 +614,15 @@ func runCfsQuotaGuPods(ctx context.Context, f *framework.Framework, disabledCPUQ
 	pod2 = makeCPUManagerPod("gu-pod2", ctnAttrs)
 	pod2.Spec.Containers[0].Command = cfsCheckCommand
 	pod2 = e2epod.NewPodClient(f).CreateSync(ctx, pod2)
+	cleanupPods = append(cleanupPods, pod2)
+
+	ginkgo.By("checking if the expected cfs quota was assigned (GU pod, limited)")
+
+	expectedQuota = "50000"
+	expCFSQuotaRegex = fmt.Sprintf("^%s %s\n$", expectedQuota, defaultPeriod)
+	err = e2epod.NewPodClient(f).MatchContainerOutput(ctx, pod2.Name, pod2.Spec.Containers[0].Name, expCFSQuotaRegex)
+	framework.ExpectNoError(err, "expected log not found in container [%s] of pod [%s]",
+		pod2.Spec.Containers[0].Name, pod2.Name)
 
 	ctnAttrs = []ctnAttribute{
 		{
@@ -613,35 +634,15 @@ func runCfsQuotaGuPods(ctx context.Context, f *framework.Framework, disabledCPUQ
 	pod3 = makeCPUManagerPod("non-gu-pod3", ctnAttrs)
 	pod3.Spec.Containers[0].Command = cfsCheckCommand
 	pod3 = e2epod.NewPodClient(f).CreateSync(ctx, pod3)
+	cleanupPods = append(cleanupPods, pod3)
 
-	ginkgo.By("checking if the expected cfs quota was assigned")
-
-	expectedQuota := "100000"
-	if disabledCPUQuotaWithExclusiveCPUs {
-		expectedQuota = "max"
-	}
-	expCFSQuotaRegex := fmt.Sprintf("^%s %s\n$", expectedQuota, defaultPeriod)
-	err = e2epod.NewPodClient(f).MatchContainerOutput(ctx, pod1.Name, pod1.Spec.Containers[0].Name, expCFSQuotaRegex)
-	framework.ExpectNoError(err, "expected log not found in container [%s] of pod [%s]",
-		pod1.Spec.Containers[0].Name, pod1.Name)
-
-	expectedQuota = "50000"
-	expCFSQuotaRegex = fmt.Sprintf("^%s %s\n$", expectedQuota, defaultPeriod)
-	err = e2epod.NewPodClient(f).MatchContainerOutput(ctx, pod2.Name, pod2.Spec.Containers[0].Name, expCFSQuotaRegex)
-	framework.ExpectNoError(err, "expected log not found in container [%s] of pod [%s]",
-		pod2.Spec.Containers[0].Name, pod2.Name)
+	ginkgo.By("checking if the expected cfs quota was assigned (BU pod, limited)")
 
 	expectedQuota = "50000"
 	expCFSQuotaRegex = fmt.Sprintf("^%s %s\n$", expectedQuota, defaultPeriod)
 	err = e2epod.NewPodClient(f).MatchContainerOutput(ctx, pod3.Name, pod3.Spec.Containers[0].Name, expCFSQuotaRegex)
 	framework.ExpectNoError(err, "expected log not found in container [%s] of pod [%s]",
 		pod3.Spec.Containers[0].Name, pod3.Name)
-
-	ginkgo.By("by deleting the pods and waiting for container removal")
-	deletePods(ctx, f, []string{pod1.Name, pod2.Name, pod3.Name})
-	waitForContainerRemoval(ctx, pod1.Spec.Containers[0].Name, pod1.Name, pod1.Namespace)
-	waitForContainerRemoval(ctx, pod2.Spec.Containers[0].Name, pod2.Name, pod2.Namespace)
-	waitForContainerRemoval(ctx, pod3.Spec.Containers[0].Name, pod3.Name, pod3.Namespace)
 }
 
 func runMultipleGuPods(ctx context.Context, f *framework.Framework) {
```

File: test/e2e_node/cpu_manager_test.go [hunk 25]
```diff
@@ -557,6 +559,92 @@ func runMultipleCPUContainersGuPod(ctx context.Context, f *framework.Framework)
 	waitForContainerRemoval(ctx, pod.Spec.Containers[1].Name, pod.Name, pod.Namespace)
 }
 
+func runCfsQuotaGuPods(ctx context.Context, f *framework.Framework, disabledCPUQuotaWithExclusiveCPUs bool) {
```
Comment (odinuge) [inline test/e2e_node/cpu_manager_test.go:562]: Can you add a check on the pod level cgroup here as well to be fully sure that behavior also works as expected on that level as well?

File: test/e2e_node/cpu_manager_test.go [hunk 26]
```diff
@@ -557,6 +559,92 @@ func runMultipleCPUContainersGuPod(ctx context.Context, f *framework.Framework)
...
+	})
+
+	cfsCheckCommand := []string{"sh", "-c", "cat /sys/fs/cgroup/cpu.max && sleep 1d"}
+	defaultPeriod := "100000"
+
+	ctnAttrs = []ctnAttribute{
+		{
+			ctnName:    "gu-container-cfsquota-disabled",
+			cpuRequest: "1",
+			cpuLimit:   "1",
```
Comment (odinuge) [inline test/e2e_node/cpu_manager_test.go:587]: Can you add another test with two containers here something like this;
```
ctnAttrs = []ctnAttribute{
		{
			ctnName:    "gu-container-int-values",
			cpuRequest: "1",
			cpuLimit:   "1",
		},
		{
			ctnName:    "gu-container-non-int-values",
			cpuRequest: "20m",
			cpuLimit:   "20m",
		},
	}
```

File: pkg/kubelet/cm/container_manager_linux.go [hunk 27]
```diff
@@ -365,14 +365,28 @@ func (cm *containerManagerImpl) NewPodContainerManager() PodContainerManager {
...
+			podContainerManager: cm,
 		}
 	}
 	return &podContainerManagerNoop{
 		cgroupRoot: cm.cgroupRoot,
 	}
 }
 
+func (cm *containerManagerImpl) HasExclusiveCPUs(pod *v1.Pod) bool {
+	for _, container := range pod.Spec.Containers {
```
Comment (odinuge) [inline pkg/kubelet/cm/container_manager_linux.go:378]: I think this _fine_ with me, but I don't fully remember _exactly_ how init contianers work with exclusive cpus, but I think here its pretty important to be consistent.

I think I'm happy with a pod where;
```
- Pod is A
  - initContainer B does NOT have exclusive CPU (cpu request+limit: 20m)
  - container C has exclusive CPU (cpu request+limit: 1)
```

to have;
```
- Pod level A has NO cpu limit
- initContainer B does have a cpu limit
- container C has NO cpu limit
```

However, I think in this state the current implementation here will also have no cpu limit on the init container even though it has a cpu limit. I think that is because the container level resource check for the init container is using this function that only loops over the actual container, and not init ones.

Sorry if this is already discussed.

File: pkg/kubelet/cm/container_manager_windows.go [hunk 28]
```diff
@@ -369,3 +369,16 @@ func (cm *containerManagerImpl) UnprepareDynamicResources(ctx context.Context, p
 func (cm *containerManagerImpl) PodMightNeedToUnprepareResources(UID types.UID) bool {
 	return false
 }
+
+func (cm *containerManagerImpl) HasExclusiveCPUs(pod *v1.Pod) bool {
+	for _, container := range pod.Spec.Containers {
```
Comment (odinuge) [inline pkg/kubelet/cm/container_manager_windows.go:374]: Should this also be hidden behind the `WindowsCPUAndMemoryAffinity` feature flag as some of the other code in this file is?

File: pkg/features/kube_features.go [hunk 29]
```diff
@@ -868,6 +868,12 @@ const (
 	//
 	// Enables specifying resources at pod-level.
 	PodLevelResources featuregate.Feature = "PodLevelResources"
+
+	// owner: @ffromani
+	// beta: v1.33
+	//
+	// Disable CPU Quota for pods which have exclusive CPUs allocated
```
Comment (odinuge) [inline pkg/features/kube_features.go:875]: Can you update this to be a bit more explicit about what it does. Its removing it on _both_ the container level and the pod level, and explain the way we end up dealing with the init containers.

I think personally we could have removed the cpu limit for all containers that have exclusive CPUs as well (but not neccecary the pod level), but we can also do that in a separate PR/feature.

**Review by odinuge — COMMENTED** [review]
Thanks for working on this. Some comments around tests and how init containers are going to work, but otherwise it seems very neat and concise!

Another topic is all the edge cases around vertical pod autoscaling, but I have very little context there - and the current logic looks sound.

File: pkg/kubelet/cm/container_manager_linux.go (hunk 27 above)
Comment (ffromani) [reply pkg/kubelet/cm/container_manager_linux.go:378]: Right, very good point about init containers. Need to have another pass about it and fully flesh it out.

File: pkg/kubelet/cm/container_manager_windows.go (hunk 28 above)
Comment (ffromani) [reply pkg/kubelet/cm/container_manager_windows.go:374]: I think this is unnecessary because if the  `WindowsCPUAndMemoryAffinity` is disabled, then we transparently use the FakeCPUManager which will always return empty for exclusive assignment. We waste some cpu cycles running the loop anyway, but this should not be a big deal

File: pkg/kubelet/cm/container_manager_linux.go (hunk 27 above)
Comment (ffromani) [reply pkg/kubelet/cm/container_manager_linux.go:378]: surely we will need to treat sidecar containers as app containers and extend `HasExclusiveCPUs` to deal with that (cc @SergeyKanzhelev )

File: pkg/features/kube_features.go (hunk 29 above)
Comment (ffromani) [reply pkg/features/kube_features.go:875]: Agreed about we should have a record of why we disable pod level/container level. We should also backlink the PRs on github and the issue for historical record

Comment (ffromani) [reply pkg/features/kube_features.go:875]: note: we want to remove the FG on 1.33+4 releases anyway, so this has to be placed somewhere is gonna be kept once the FG is removed.

File: test/e2e_node/cpu_manager_test.go (hunk 26 above)
Comment (scott-grimes) [reply test/e2e_node/cpu_manager_test.go:587]: done!

File: test/e2e_node/cpu_manager_test.go (hunk 25 above)
Comment (scott-grimes) [reply test/e2e_node/cpu_manager_test.go:562]: hmm from within a running container you'd need to do some weird workarounds to allow access to that cgroup and fetch the info. off top of my head to get the pod cgroup you'd need to: 

* hostpath mount `/sys/fs/cgrouop/kubepods.slice` to somewhere like `/kubepods-slice` going to have do some some unusual

to then determine the proper cgroup you'd need to know the container id and recurse up a directory. something like 
* add POD_NAME and POD_NAMESPACE as env var via downward api
* curl apiserver with SA token as cert, parse to find container id 
* `find` directory with corresponding id within `/kubepods-slice`
* requires corresponding role+rolebinding+sa associated with the given pod to allow querying pod info to obtain container id

---
1) is there any other way that we can think of that'd be easier?
2) are e2e tests allowed to do any of this? I recall reading somewhere that PSS are enforced which would restrict hostpath mounting entirely as an option?

File: pkg/kubelet/cm/pod_container_manager_linux.go [hunk 30]
```diff
@@ -72,6 +74,10 @@ func (m *podContainerManagerImpl) Exists(pod *v1.Pod) bool {
 func (m *podContainerManagerImpl) EnsureExists(pod *v1.Pod) error {
 	// check if container already exist
 	alreadyExists := m.Exists(pod)
+	enforceCPULimits := m.enforceCPULimits
```
[the remark this answers is not in the document]
Comment (scott-grimes) [reply pkg/kubelet/cm/pod_container_manager_linux.go:77]: done!

File: pkg/kubelet/cm/container_manager_linux.go (hunk 27 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/container_manager_linux.go:378]: commented in #70585, this is done matching existing logic of cpumanager `podGuaranteedCPUs` / `guaranteedCPUs`

File: test/e2e_node/cpu_manager_test.go [hunk 31]
```diff
@@ -557,6 +559,153 @@ func runMultipleCPUContainersGuPod(ctx context.Context, f *framework.Framework)
...
+	pod4 = e2epod.NewPodClient(f).CreateSync(ctx, pod4)
+	cleanupPods = append(cleanupPods, pod4)
+
+	ginkgo.By("checking if the expected cfs quota was assigned (GU pod, container 0 exclusive CPUs unlimited, container 1 limited)")
+
+	expectedQuota = "100000"
+	if disabledCPUQuotaWithExclusiveCPUs {
+		expectedQuota = "max"
+	}
+	expCFSQuotaRegex = fmt.Sprintf("^%s %s\n$", expectedQuota, defaultPeriod)
```
Comment (odinuge) [inline test/e2e_node/cpu_manager_test.go:670]: You should also check the `gu-container-non-int-values` container here to ensure its correct

File: test/e2e_node/cpu_manager_test.go (hunk 25 above)
Comment (odinuge) [reply test/e2e_node/cpu_manager_test.go:562]: I think you can start by looking at other test, like eg. this one;
https://github.com/kubernetes/kubernetes/blob/02fd991c5b3d1b705658633a93f8d8aae2c694bb/test/e2e_node/hugepages_test.go#L70

Its been a long time since I worked closely with the e2e tests, so things might have changes in the past year.


But overall, given the importance of this code, I very much would prefer if we tested this properly to avoid regressions or unintended behavior.

File: pkg/kubelet/cm/container_manager_linux.go [hunk 32]
```diff
@@ -365,14 +365,35 @@ func (cm *containerManagerImpl) NewPodContainerManager() PodContainerManager {
...
+			cpuCFSQuotaPeriod:   uint64(cm.CPUCFSQuotaPeriod / time.Microsecond),
+			podContainerManager: cm,
 		}
 	}
 	return &podContainerManagerNoop{
 		cgroupRoot: cm.cgroupRoot,
 	}
 }
 
+func (cm *containerManagerImpl) HasExclusiveCPUs(pod *v1.Pod) bool {
```
[the remark this answers is not in the document]
Comment (ffromani) [reply pkg/kubelet/cm/container_manager_linux.go:377]: how can we disable the quota just and only for the single container which requests exclusive CPUs?

[the remark this answers is not in the document]
Comment (odinuge) [reply pkg/kubelet/cm/container_manager_linux.go:377]: I think I'm just confused about the intention here, and I think its easier to discuss if the proposal here is explicitly and clearly defined in the PR description (also commented here; https://github.com/kubernetes/kubernetes/issues/70585#issuecomment-2511329396) so its easier to review. That way we can also enumerate all edge-cases and document them in tests. I'm probably missing some edge-cases here as well

**Comment by odinuge** [comment]
I did a quick test locally to ensure I understand the code correctly;
```bash
$ kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: alpine-reserved-cpu
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "1235"
    image: alpine
    name: one
    resources:
      limits:
        cpu: "1"
        memory: 100Mi
      requests:
        cpu: "1"
        memory: 100Mi
  - command:
    - sleep
    - "1235"
    image: alpine
    name: two
    resources:
      limits:
        cpu: 200m
        memory: 100Mi
      requests:
        cpu: 200m
        memory: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine-no-reserved-cpu
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - "1235"
    image: alpine
    name: one
    resources:
      limits:
        cpu: "2"
        memory: 100Mi
      requests:
        cpu: "1"
        memory: 100Mi
  - command:
    - sleep
    - "1235"
EOF

$ kubectl exec -it alpine-no-reserved-cpu -c one -- sh -x -c "cat /sys/fs/cgroup/cpuset.cpus; cat /sys/fs/cgroup/cpu.max"
+ cat /sys/fs/cgroup/cpuset.cpus
1-11
+ cat /sys/fs/cgroup/cpu.max
200000 100000

$ kubectl exec -it alpine-no-reserved-cpu -c two -- sh -x -c "cat /sys/fs/cgroup/cpuset.cpus; cat /sys/fs/cgroup/cpu.max"
+ cat /sys/fs/cgroup/cpuset.cpus
1-11
+ cat /sys/fs/cgroup/cpu.max
20000 100000

$ kubectl exec -it alpine-reserved-cpu -c one -- sh -x -c "cat /sys/fs/cgroup/cpuset.cpus; cat /sys/fs/cgroup/cpu.max"
+ cat /sys/fs/cgroup/cpuset.cpus
0
+ cat /sys/fs/cgroup/cpu.max
max 100000

$ kubectl exec -it alpine-reserved-cpu -c two -- sh -x -c "cat /sys/fs/cgroup/cpuset.cpus; cat /sys/fs/cgroup/cpu.max"
+ cat /sys/fs/cgroup/cpuset.cpus
1-11
+ cat /sys/fs/cgroup/cpu.max
max 100000
```

I think for the last command (`pod:alpine-reserved-cpu,container:two`) I would expect it to end up with `200000 100000` in `/sys/fs/cgroup/cpu.max`, because otherwise it will be able to run unbounded cpu-wise on all non-reserved cores on the machine.

File: test/e2e_node/cpu_manager_test.go (hunk 31 above)
Comment (scott-grimes) [reply test/e2e_node/cpu_manager_test.go:709]: resolved: see comment https://github.com/kubernetes/kubernetes/issues/70585#issuecomment-2518990304 had to split to check both pod-level cfs and container-level cfs

File: test/e2e_node/cpu_manager_test.go (hunk 25 above)
Comment (scott-grimes) [reply test/e2e_node/cpu_manager_test.go:596]: thanks! got it worked out - did hostpath mount of `/sys/fs/cgroup` plus downward api to surface pod uid makes it easy to find the pod's cpu.max 👍

**Comment by ffromani** [comment]
ok, failures in pull-kubernetes-node-kubelet-serial-cpu-manager  seems legit, we need to investigate. Perhaps the base image changed again

File: pkg/kubelet/cm/container_manager.go [hunk 33]
```diff
@@ -154,6 +154,12 @@ type ContainerManager interface {
...
 	Updates() <-chan resourceupdates.Update
 
+	// PodHasExclusiveCPUs returns true if the provided pod has containers with exclusive cpu
```
Comment (ffromani) [inline pkg/kubelet/cm/container_manager.go:157]: nit: if you resubmit, let's add rephrase as
```
PodHasExclusiveCPUs returns true if the provided pod has containers with exclusive CPUs,
this means that at least one sidecar container or one app container has exclusive CPUs allocated.
```

File: pkg/kubelet/cm/container_manager_linux.go [hunk 34]
```diff
@@ -365,14 +365,44 @@ func (cm *containerManagerImpl) NewPodContainerManager() PodContainerManager {
...
 	}
 	return &podContainerManagerNoop{
 		cgroupRoot: cm.cgroupRoot,
 	}
 }
 
+func (cm *containerManagerImpl) PodHasExclusiveCPUs(pod *v1.Pod) bool {
+	for _, container := range pod.Spec.InitContainers {
+		exclusiveCPUs := cm.cpuManager.GetExclusiveCPUs(string(pod.UID), container.Name)
+		if !exclusiveCPUs.IsEmpty() {
```
Comment (ffromani) [inline pkg/kubelet/cm/container_manager_linux.go:380]: I'm still inclined to `return true` if `!exclusiveCPUs.IsEmpty() && IsSidecar` (we need to use the appropriate function ofc)

File: pkg/kubelet/cm/container_manager_linux.go [hunk 35]
```diff
@@ -365,14 +365,44 @@ func (cm *containerManagerImpl) NewPodContainerManager() PodContainerManager {
...
+			return true
+		}
+	}
+	for _, container := range pod.Spec.Containers {
+		exclusiveCPUs := cm.cpuManager.GetExclusiveCPUs(string(pod.UID), container.Name)
+		if !exclusiveCPUs.IsEmpty() {
+			klog.V(4).InfoS("Pod contains container with pinned cpus", "podName", pod.Name, "containerName", container.Name)
+			return true
+		}
+	}
```
Comment (ffromani) [inline pkg/kubelet/cm/container_manager_linux.go:391]: I'd reimplement this block just calling `ContainerHasExclusiveCPUs`

File: pkg/kubelet/cm/container_manager_windows.go [hunk 36]
```diff
@@ -369,3 +369,32 @@ func (cm *containerManagerImpl) UnprepareDynamicResources(ctx context.Context, p
 func (cm *containerManagerImpl) PodMightNeedToUnprepareResources(UID types.UID) bool {
 	return false
 }
+
+func (cm *containerManagerImpl) PodHasExclusiveCPUs(pod *v1.Pod) bool {
```
Comment (ffromani) [inline pkg/kubelet/cm/container_manager_windows.go:373]: same comments per `_linux` counterpart. I wonder if we can generalize the function, e.g. moving into `helpers.go` and adding an interface as argument.

File: pkg/kubelet/cm/container_manager_windows.go [hunk 37]
```diff
@@ -369,3 +369,32 @@ func (cm *containerManagerImpl) UnprepareDynamicResources(ctx context.Context, p
...
+			klog.V(4).InfoS("Pod contains container with pinned cpus", "podName", pod.Name, "containerName", container.Name)
+			return true
+		}
+	}
+
+	klog.V(4).InfoS("Pod contains no container with pinned cpus", "podName", pod.Name)
+	return false
+}
+
+func (cm *containerManagerImpl) ContainerHasExclusiveCPUs(pod *v1.Pod, container *v1.Container) bool {
```
Comment (ffromani) [inline pkg/kubelet/cm/container_manager_windows.go:393]: ditto

**Review by ffromani — COMMENTED** [review]
mostly minor comments left, the sidecar treatment is the biggest remaining concern. I'll have another pass later to ensure that we only make changes when the FG is turned on.

Overall it looks pretty much LGTM once we clarify the sidecar treatment.

File: pkg/kubelet/cm/container_manager_windows.go (hunk 36 above)
Comment (ffromani) [reply pkg/kubelet/cm/container_manager_windows.go:373]: something like this:
```
diff --git a/pkg/kubelet/cm/container_manager.go b/pkg/kubelet/cm/container_manager.go
index d8c3428aa99..8e6cacce48c 100644
--- a/pkg/kubelet/cm/container_manager.go
+++ b/pkg/kubelet/cm/container_manager.go
@@ -26,6 +26,7 @@ import (
 
 	"k8s.io/apimachinery/pkg/types"
 	"k8s.io/apimachinery/pkg/util/sets"
+	"k8s.io/klog/v2"
 
 	// TODO: Migrate kubelet to either use its own internal objects or client library.
 	v1 "k8s.io/api/core/v1"
@@ -287,3 +288,34 @@ func containerDevicesFromResourceDeviceInstances(devs devicemanager.ResourceDevi
 
 	return respDevs
 }
+
+type cpuAllocationReader interface {
+	GetExclusiveCPUs(podUID, containerName string) cpuset.CPUSet
+}
+
+func podHasExclusiveCPUs(cr cpuAllocationReader, pod *v1.Pod) bool {
+	for _, container := range pod.Spec.InitContainers {
+		exclusiveCPUs := cr.GetExclusiveCPUs(string(pod.UID), container.Name)
+		if !exclusiveCPUs.IsEmpty() {
+			klog.V(4).InfoS("Pod contains container with pinned cpus", "podName", pod.Name, "containerName", container.Name)
+			return true
+		}
+	}
+	for _, container := range pod.Spec.Containers {
+		if containerHasExclusiveCPUs(cr, pod, &container) {
+			return true
+		}
+	}
+
+	klog.V(4).InfoS("Pod contains no container with pinned cpus", "podName", pod.Name)
+	return false
+}
+
+func containerHasExclusiveCPUs(cr cpuAllocationReader, pod *v1.Pod, container *v1.Container) bool {
+	exclusiveCPUs := cr.GetExclusiveCPUs(string(pod.UID), container.Name)
+	if !exclusiveCPUs.IsEmpty() {
+		klog.V(4).InfoS("Container has pinned cpus", "podName", pod.Name, "containerName", container.Name)
+		return true
+	}
+	return false
+}
diff --git a/pkg/kubelet/cm/container_manager_linux.go b/pkg/kubelet/cm/container_manager_linux.go
index 651f8181208..922a2566630 100644
--- a/pkg/kubelet/cm/container_manager_linux.go
+++ b/pkg/kubelet/cm/container_manager_linux.go
@@ -375,32 +375,11 @@ func (cm *containerManagerImpl) NewPodContainerManager() PodContainerManager {
 }
 
 func (cm *containerManagerImpl) PodHasExclusiveCPUs(pod *v1.Pod) bool {
-	for _, container := range pod.Spec.InitContainers {
-		exclusiveCPUs := cm.cpuManager.GetExclusiveCPUs(string(pod.UID), container.Name)
-		if !exclusiveCPUs.IsEmpty() {
-			klog.V(4).InfoS("Pod contains container with pinned cpus", "podName", pod.Name, "containerName", container.Name)
-			return true
-		}
-	}
-	for _, container := range pod.Spec.Containers {
-		exclusiveCPUs := cm.cpuManager.GetExclusiveCPUs(string(pod.UID), container.Name)
-		if !exclusiveCPUs.IsEmpty() {
-			klog.V(4).InfoS("Pod contains container with pinned cpus", "podName", pod.Name, "containerName", container.Name)
-			return true
-		}
-	}
-
-	klog.V(4).InfoS("Pod contains no container with pinned cpus", "podName", pod.Name)
-	return false
+	return podHasExclusiveCPUs(cm.cpuManager, pod)
 }
 
 func (cm *containerManagerImpl) ContainerHasExclusiveCPUs(pod *v1.Pod, container *v1.Container) bool {
-	exclusiveCPUs := cm.cpuManager.GetExclusiveCPUs(string(pod.UID), container.Name)
-	if !exclusiveCPUs.IsEmpty() {
-		klog.V(4).InfoS("Container has pinned cpus", "podName", pod.Name, "containerName", container.Name)
-		return true
-	}
-	return false
+	return containerHasExclusiveCPUs(cm.cpuManager, pod, container)
 }
 
 func (cm *containerManagerImpl) InternalContainerLifecycle() InternalContainerLifecycle {
diff --git a/pkg/kubelet/cm/container_manager_windows.go b/pkg/kubelet/cm/container_manager_windows.go
index fd72fcb9a25..336ace862fd 100644
--- a/pkg/kubelet/cm/container_manager_windows.go
+++ b/pkg/kubelet/cm/container_manager_windows.go
@@ -371,30 +371,9 @@ func (cm *containerManagerImpl) PodMightNeedToUnprepareResources(UID types.UID)
 }
 
 func (cm *containerManagerImpl) PodHasExclusiveCPUs(pod *v1.Pod) bool {
-	for _, container := range pod.Spec.InitContainers {
-		exclusiveCPUs := cm.cpuManager.GetExclusiveCPUs(string(pod.UID), container.Name)
-		if !exclusiveCPUs.IsEmpty() {
-			klog.V(4).InfoS("Pod contains container with pinned cpus", "podName", pod.Name, "containerName", container.Name)
-			return true
-		}
-	}
-	for _, container := range pod.Spec.Containers {
-		exclusiveCPUs := cm.cpuManager.GetExclusiveCPUs(string(pod.UID), container.Name)
-		if !exclusiveCPUs.IsEmpty() {
-			klog.V(4).InfoS("Pod contains container with pinned cpus", "podName", pod.Name, "containerName", container.Name)
-			return true
-		}
-	}
-
-	klog.V(4).InfoS("Pod contains no container with pinned cpus", "podName", pod.Name)
-	return false
+	return podHasExclusiveCPUs(cm.cpuManager, pod)
 }
 
 func (cm *containerManagerImpl) ContainerHasExclusiveCPUs(pod *v1.Pod, container *v1.Container) bool {
-	exclusiveCPUs := cm.cpuManager.GetExclusiveCPUs(string(pod.UID), container.Name)
-	if !exclusiveCPUs.IsEmpty() {
-		klog.V(4).InfoS("Container has pinned cpus", "podName", pod.Name, "containerName", container.Name)
-		return true
-	}
-	return false
+	return containerHasExclusiveCPUs(cm.cpuManager, pod, container)
 }
```

we can refine further but I won't, this PR should go in ASAP and the above (or any equivalent) is a nice enough tradeoff.

**Review by ffromani — COMMENTED** [review]
ok, re-verified all the logic is properly guarded by feature gate.
So to move forward we need
1. understand why the e2e test broke, possibly fix
2. clarify the sidecar handling (see inline comments)
3. iff you resubmit, please check other comments

once that is done, LGTM

**Comment by ffromani** [comment]
> ok, re-verified all the logic is properly guarded by feature gate. So to move forward we need
> 
>     1. understand why the e2e test broke, possibly fix
> 
>     2. clarify the sidecar handling (see inline comments)
> 
>     3. iff you resubmit, please check other comments
> 
> 
> once that is done, LGTM

ok, I can reproduce locally :) Will investigate

**Comment by ffromani** [comment]
this seems to fix for me (includes cosmetic chages), PTAL:

```
diff --git a/test/e2e_node/cpu_manager_test.go b/test/e2e_node/cpu_manager_test.go
index f06cef06c61..85ecb6fdad3 100644
--- a/test/e2e_node/cpu_manager_test.go
+++ b/test/e2e_node/cpu_manager_test.go
@@ -724,23 +724,24 @@ func runCfsQuotaGuPods(ctx context.Context, f *framework.Framework, disabledCPUQ
                },
        }
 
-       podCFSCheckCommand := []string{"sh", "-c", `cat $(find /sysfscgroup | grep "$(cat /podinfo/uid | awk 's/-/_/g').slice/cpu.max$") && sleep 1d`}
+       podCFSCheckCommand := []string{"sh", "-c", `cat /sysfscgroup/kubepods/pod$(cat /podinfo/uid )/cpu.max && sleep 1d`}
 
        pod5 := makeCPUManagerPod("gu-pod5", ctnAttrs)
        pod5.Spec.Containers[0].Command = podCFSCheckCommand
        pod5 = e2epod.NewPodClient(f).CreateSync(ctx, pod5)
        cleanupPods = append(cleanupPods, pod5)
-
        ginkgo.By("checking if the expected cfs quota was assigned to pod (GU pod, unlimited)")
 
        expectedQuota = "100000"
+
        if disabledCPUQuotaWithExclusiveCPUs {
                expectedQuota = "max"
        }
+
        expCFSQuotaRegex = fmt.Sprintf("^%s %s\n$", expectedQuota, defaultPeriod)
+
        err = e2epod.NewPodClient(f).MatchContainerOutput(ctx, pod5.Name, pod5.Spec.Containers[0].Name, expCFSQuotaRegex)
-       framework.ExpectNoError(err, "expected log not found in container [%s] of pod [%s]",
-               pod5.Spec.Containers[0].Name, pod5.Name)
+       framework.ExpectNoError(err, "expected log not found in container [%s] of pod [%s]", pod5.Spec.Containers[0].Name, pod5.Name)
 
        ctnAttrs = []ctnAttribute{
                {
@@ -760,9 +761,7 @@ func runCfsQuotaGuPods(ctx context.Context, f *framework.Framework, disabledCPUQ
        expectedQuota = "10000"
        expCFSQuotaRegex = fmt.Sprintf("^%s %s\n$", expectedQuota, defaultPeriod)
        err = e2epod.NewPodClient(f).MatchContainerOutput(ctx, pod6.Name, pod6.Spec.Containers[0].Name, expCFSQuotaRegex)
-       framework.ExpectNoError(err, "expected log not found in container [%s] of pod [%s]",
-               pod6.Spec.Containers[0].Name, pod6.Name)
-
+       framework.ExpectNoError(err, "expected log not found in container [%s] of pod [%s]", pod6.Spec.Containers[0].Name, pod6.Name)
 }
 
 func runMultipleGuPods(ctx context.Context, f *framework.Framework) {

```
If the above is indeed a good fix, what's left would be
1. clarify the sidecar handling (see inline comments)
2. iff you resubmit, please check other comments (mostly minor)

**Comment by ffromani** [comment]
correction: let's check the quota calculation. I think we need something like
```
[...]
        ginkgo.By("checking if the expected cfs quota was assigned to pod (GU pod, unlimited)")
 
       expectedQuota = "150000" // half a core plus a full core
[...]
```

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 38]
```diff
@@ -133,7 +133,14 @@ func (m *kubeGenericRuntimeManager) generateLinuxContainerResources(pod *v1.Pod,
...
 	memoryLimit := getMemoryLimit(pod, container)
 	cpuLimit := getCPULimit(pod, container)
-	lcr := m.calculateLinuxResources(cpuRequest, cpuLimit, memoryLimit)
+
+	// If pod has exclusive cpu and the container in question has integer cpu requests
+	// the cfs quota will not be enforced
+	disableCPUQuota := false
+	if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.DisableCPUQuotaWithExclusiveCPUs) && m.containerManager.ContainerHasExclusiveCPUs(pod, container) {
+		disableCPUQuota = true
+	}
```
Comment (haircommander) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:142]: this could be compressed into 
```
disableCPUQuota := utilfeature.DefaultFeatureGate.Enabled(kubefeatures.DisableCPUQuotaWithExclusiveCPUs) && m.containerManager.ContainerHasExclusiveCPUs(pod, container)
```

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go [hunk 39]
```diff
@@ -55,7 +55,14 @@ func (m *kubeGenericRuntimeManager) calculateSandboxResources(pod *v1.Pod) *runt
 	if _, cpuRequestExists := req[v1.ResourceCPU]; cpuRequestExists {
 		cpuRequest = req.Cpu()
 	}
-	return m.calculateLinuxResources(cpuRequest, lim.Cpu(), lim.Memory())
+
+	// If pod has exclusive cpu the sandbox will not have cfs quote enforced
+	disableCPUQuota := false
+	if utilfeature.DefaultFeatureGate.Enabled(features.DisableCPUQuotaWithExclusiveCPUs) && m.containerManager.PodHasExclusiveCPUs(pod) {
+		disableCPUQuota = true
+	}
```
Comment (haircommander) [inline pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go:63]: same as above

File: pkg/kubelet/cm/container_manager.go (hunk 33 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/container_manager.go:157]: resolved!

File: pkg/kubelet/cm/container_manager_linux.go (hunk 35 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/container_manager_linux.go:391]: done!

File: pkg/kubelet/cm/container_manager_windows.go (hunk 36 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/container_manager_windows.go:373]: reworked to add this!

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go (hunk 38 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:142]: added

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go (hunk 39 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go:63]: done!

File: pkg/kubelet/cm/container_manager_linux.go (hunk 34 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/container_manager_linux.go:380]: does the logic here not already match that? we're iterating directly over the `pod.Spec` which contains InitContainers and Containers (which includes both app and sidecar). 

The logic as-is also matches the logic used to assign static pods. If we change it here we would also need also modify https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cpumanager/policy_static.go#L480-L512

File: pkg/kubelet/cm/container_manager_windows.go (hunk 37 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/container_manager_windows.go:393]: done!

File: pkg/kubelet/cm/container_manager_linux.go (hunk 34 above)
Comment (ffromani) [reply pkg/kubelet/cm/container_manager_linux.go]: sidecar containers are indeed implemented as init container, but per our convo in the issue we should disable quota for app and sidecar containers, aren't we?
Thing is: a sidecar container is a init container (plus the `RestartPolicy=Always`) but not all init containers are sidecar containers, this is why I'm advocating for further filtering here as I described above.

[The link ](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cpumanager/policy_static.go#L480-L512) LGTM already, we are making logic to distinguish pure init vs sidecar containers.

File: pkg/features/kube_features.go [hunk 40]
```diff
@@ -856,6 +856,17 @@ const (
 	//
 	// Enables specifying resources at pod-level.
 	PodLevelResources featuregate.Feature = "PodLevelResources"
+
+	// owner: @ffromani
+	// beta: v1.33
+	//
+	// Disable CPU Quota for containers which have exclusive CPUs allocated.
+	// Disables pod-Level CPU Quota for pods containing at least one container with exclusive CPUs allocated
+	// Exclusive CPUs for a container (init, application, sidecar) are allocated when:
```
Comment (ffromani) [inline pkg/features/kube_features.go:865]: ok, we declare we want to do also for init containers, which I'm not sure it's worth it but should not be wrong either, so I'm neutral about it.

**Review by ffromani — COMMENTED** [review]
/lgtm

I have no issues disabling quota ALSO for init containers, even though I'm not fully convinced there's a strong use case for it. But to the best of my knowledge, is not wrong, so why not? we agreed anyway about a watch period for this change (this is why we have the feature gate!) so some tunings are already planned.

We iterated quite a bit over this fix and codewise looks fine to me now.
I think it's time to move ~on~ forward.

**Comment by ffromani** [comment]
because
```
 Summarizing 1 Failure:
  [FAIL] [sig-storage] In-tree Volumes [Driver: hostPathSymlink] [Testpattern: Inline-volume (default fs)] subPath [It] should support non-existent path [sig-storage]
  k8s.io/kubernetes/test/e2e/storage/drivers/in_tree.go:649 
```

**Comment by ffromani** [comment]
/cc @dchen1107 @SergeyKanzhelev @klueska 

could you PTAL from approver perspective?

File: pkg/kubelet/cm/container_manager.go [hunk 41]
```diff
@@ -212,6 +224,32 @@ func int64Slice(in []int) []int64 {
 	return out
 }
 
+func podHasExclusiveCPUs(cr cpuAllocationReader, pod *v1.Pod) bool {
+	for _, container := range pod.Spec.InitContainers {
+		exclusiveCPUs := cr.GetExclusiveCPUs(string(pod.UID), container.Name)
```
Comment (odinuge) [inline pkg/kubelet/cm/container_manager.go:229]: I think `pod.Spec.InitContainers` has the same type as `pod.Spec.Containers` so you should be able to reuse `containerHasExclusiveCPUs` here as well.

**Comment by odinuge** [comment]
One small comment, otherwise this looks good to me! Thanks!

**Comment by ffromani** [comment]
AI: @ffromani to open a website PR to document the FG

File: pkg/kubelet/cm/container_manager.go (hunk 41 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/container_manager.go]: resolved!

**Comment by ffromani** [comment]
/approve

I'm happy with the `k/kpkg/kubelet/cm` changes. We need other approvals anyway.

File: pkg/kubelet/cm/container_manager.go [hunk 42]
```diff
@@ -212,6 +224,30 @@ func int64Slice(in []int) []int64 {
...
+		}
+	}
+	klog.V(4).InfoS("Pod contains no container with pinned cpus", "podName", pod.Name)
+	return false
+}
+
+func containerHasExclusiveCPUs(cr cpuAllocationReader, pod *v1.Pod, container *v1.Container) bool {
+	exclusiveCPUs := cr.GetExclusiveCPUs(string(pod.UID), container.Name)
+	if !exclusiveCPUs.IsEmpty() {
+		klog.V(4).InfoS("Container has pinned cpus", "podName", pod.Name, "containerName", container.Name)
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/cm/container_manager.go:245]: how did you pick log level of `4`? This is typically above the default so no logs will be produced.

Maybe not here, but ideally we need to have a log message with the default severity that will allow to detect that the logic worked (and suggest to disable it if it broke anything).

File: pkg/features/kube_features.go [hunk 43]
```diff
@@ -862,6 +862,17 @@ const (
 	//
 	// Enables specifying resources at pod-level.
 	PodLevelResources featuregate.Feature = "PodLevelResources"
+
+	// owner: @ffromani
+	// beta: v1.33
+	//
+	// Disable CPU Quota for containers which have exclusive CPUs allocated.
```
Comment (SergeyKanzhelev) [inline pkg/features/kube_features.go:869]: Make sure the add "temporary allow to disable" wording. It MUST be clear that this is something that will not be allowed soon.

File: pkg/kubelet/cm/container_manager.go (hunk 42 above)
Comment (ffromani) [reply pkg/kubelet/cm/container_manager.go:245]: Fair enough, let's review the logging levels to enable users troubleshooting

File: pkg/kubelet/cm/pod_container_manager_linux.go [hunk 44]
```diff
@@ -73,6 +75,10 @@ func (m *podContainerManagerImpl) EnsureExists(pod *v1.Pod) error {
 	// check if container already exist
 	alreadyExists := m.Exists(pod)
 	if !alreadyExists {
+		enforceCPULimits := m.enforceCPULimits
+		if utilfeature.DefaultFeatureGate.Enabled(kubefeatures.DisableCPUQuotaWithExclusiveCPUs) && m.podContainerManager.PodHasExclusiveCPUs(pod) {
```
Comment (ffromani) [inline pkg/kubelet/cm/pod_container_manager_linux.go:79]: let's add a log entry here

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 45]
```diff
@@ -133,7 +133,11 @@ func (m *kubeGenericRuntimeManager) generateLinuxContainerResources(pod *v1.Pod,
 
 	memoryLimit := getMemoryLimit(pod, container)
 	cpuLimit := getCPULimit(pod, container)
-	lcr := m.calculateLinuxResources(cpuRequest, cpuLimit, memoryLimit)
+
+	// If pod has exclusive cpu and the container in question has integer cpu requests
+	// the cfs quota will not be enforced
+	disableCPUQuota := utilfeature.DefaultFeatureGate.Enabled(kubefeatures.DisableCPUQuotaWithExclusiveCPUs) && m.containerManager.ContainerHasExclusiveCPUs(pod, container)
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:139]: let's add a log entry here

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 46]
```diff
@@ -675,7 +675,11 @@ func (m *kubeGenericRuntimeManager) computePodResizeAction(pod *v1.Pod, containe
 func (m *kubeGenericRuntimeManager) doPodResizeAction(pod *v1.Pod, podContainerChanges podActions, result *kubecontainer.PodSyncResult) {
 	pcm := m.containerManager.NewPodContainerManager()
 	//TODO(vinaykul,InPlacePodVerticalScaling): Figure out best way to get enforceMemoryQoS value (parameter #4 below) in platform-agnostic way
-	podResources := cm.ResourceConfigForPod(pod, m.cpuCFSQuota, uint64((m.cpuCFSQuotaPeriod.Duration)/time.Microsecond), false)
+	enforceCPULimits := m.cpuCFSQuota
+	if utilfeature.DefaultFeatureGate.Enabled(features.DisableCPUQuotaWithExclusiveCPUs) && m.containerManager.PodHasExclusiveCPUs(pod) {
+		enforceCPULimits = false
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:680]: let's add a log entry here

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go [hunk 47]
```diff
@@ -55,7 +55,11 @@ func (m *kubeGenericRuntimeManager) calculateSandboxResources(pod *v1.Pod) *runt
 	if _, cpuRequestExists := req[v1.ResourceCPU]; cpuRequestExists {
 		cpuRequest = req.Cpu()
 	}
-	return m.calculateLinuxResources(cpuRequest, lim.Cpu(), lim.Memory())
+
+	// If pod has exclusive cpu the sandbox will not have cfs quote enforced
+	disableCPUQuota := utilfeature.DefaultFeatureGate.Enabled(features.DisableCPUQuotaWithExclusiveCPUs) && m.containerManager.PodHasExclusiveCPUs(pod)
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go:60]: let's add a log entry here

File: pkg/kubelet/cm/pod_container_manager_linux.go (hunk 44 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/pod_container_manager_linux.go:79]: added! (v=2)

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go (hunk 45 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:139]: added log entry (v=2) surfacing value of `disableCPUQuota` and pod

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 46 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:680]: added

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go (hunk 47 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go:60]: added

File: pkg/kubelet/cm/container_manager.go (hunk 42 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/container_manager.go:245]: kept specifics about container pinning at level `4`, added default (v=2) logging to convey when quota is deisabled

File: pkg/features/kube_features.go (hunk 43 above)
Comment (scott-grimes) [reply pkg/features/kube_features.go]: added!

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go (hunk 47 above)
Comment (ffromani) [reply pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go:60]: we can use a common format in all the places
```
klog.V(2).InfoS("Disabled CFS quota", "pod", klog.KObj(pod))
```

File: pkg/kubelet/cm/pod_container_manager_linux.go (hunk 44 above)
Comment (ffromani) [reply pkg/kubelet/cm/pod_container_manager_linux.go:79]: do we need to log the value of `unified` here?

File: pkg/kubelet/cm/container_manager.go [hunk 48]
```diff
@@ -212,6 +224,30 @@ func int64Slice(in []int) []int64 {
...
+		}
+	}
+	klog.V(4).InfoS("Pod contains no container with pinned cpus", "podName", pod.Name)
+	return false
+}
+
+func containerHasExclusiveCPUs(cr cpuAllocationReader, pod *v1.Pod, container *v1.Container) bool {
+	exclusiveCPUs := cr.GetExclusiveCPUs(string(pod.UID), container.Name)
+	if !exclusiveCPUs.IsEmpty() {
+		klog.V(2).InfoS("Container has pinned cpus", "podName", pod.Name, "containerName", container.Name)
```
Comment (ffromani) [inline pkg/kubelet/cm/container_manager.go:245]: for the reasons outlined above I think this should be reverted to V=4; we added the required logs with V=2, so we should be good.

**Review by ffromani — COMMENTED** [review]
thanks, let's clean up a bit, the CI seems unhappy anyway
LGTM overall and will re-add once cleanup is done

File: pkg/kubelet/cm/container_manager.go (hunk 48 above)
Comment (ffromani) [reply pkg/kubelet/cm/container_manager.go:245]: Still convinced because we can possibly emit a log per container with pinned CPUs, which is bordering "too much" (cc @SergeyKanzhelev )

File: pkg/kubelet/cm/pod_container_manager_linux.go [hunk 49]
```diff
@@ -73,6 +75,11 @@ func (m *podContainerManagerImpl) EnsureExists(pod *v1.Pod) error {
...
+			klog.V(2).InfoS("Removing CFS quota for pod", klog.KObj(pod))
+			enforceCPULimits = false
```
Comment (ffromani) [inline pkg/kubelet/cm/pod_container_manager_linux.go:81]: should read
```
klog.V(2).InfoS("Disabled CFS quota", "pod", klog.KObj(pod))
```

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 50]
```diff
@@ -133,7 +133,12 @@ func (m *kubeGenericRuntimeManager) generateLinuxContainerResources(pod *v1.Pod,
...
+	klog.V(2).InfoS("Removing CFS quota for pod:", disableCPUQuota, "for pod", klog.KObj(pod))
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:140]: should read:
```
klog.V(2).InfoS("Disabled CFS quota", "pod", klog.KObj(pod))
```

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 51]
```diff
@@ -675,7 +675,12 @@ func (m *kubeGenericRuntimeManager) computePodResizeAction(pod *v1.Pod, containe
...
+		klog.V(2).InfoS("Removing CFS quota for pod", klog.KObj(pod))
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go:681]: should read:
```
klog.V(2).InfoS("Disabled CFS quota", "pod", klog.KObj(pod))
```

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go [hunk 52]
```diff
@@ -55,7 +56,12 @@ func (m *kubeGenericRuntimeManager) calculateSandboxResources(pod *v1.Pod) *runt
...
+	klog.V(2).InfoS("Removing CFS quota for pod:", disableCPUQuota, "for pod", klog.KObj(pod))
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go:62]: should read:
```
klog.V(2).InfoS("Disabled CFS quota", "pod", klog.KObj(pod))
```

**Review by ffromani — COMMENTED** [review]
thanks, let's be consistent and we're there (LGTM+my approval)

File: pkg/kubelet/cm/pod_container_manager_linux.go (hunk 49 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/pod_container_manager_linux.go:81]: fixed

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go (hunk 50 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:140]: resolved

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 51 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_manager.go:681]: resolved

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go (hunk 47 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go:61]: added same format across all!

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go [hunk 53]
```diff
@@ -133,7 +133,12 @@ func (m *kubeGenericRuntimeManager) generateLinuxContainerResources(pod *v1.Pod,
 
 	memoryLimit := getMemoryLimit(pod, container)
 	cpuLimit := getCPULimit(pod, container)
-	lcr := m.calculateLinuxResources(cpuRequest, cpuLimit, memoryLimit)
+
+	// If pod has exclusive cpu and the container in question has integer cpu requests
+	// the cfs quota will not be enforced
+	disableCPUQuota := utilfeature.DefaultFeatureGate.Enabled(kubefeatures.DisableCPUQuotaWithExclusiveCPUs) && m.containerManager.ContainerHasExclusiveCPUs(pod, container)
+	klog.V(2).InfoS("Disabled CFS quota", "pod", klog.KObj(pod))
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:140]: ok, if you resubmit this should be like 
```
klog.V(2).InfoS("Enforcing CFS quota", "pod", klog.KObj(pod), "unlimited", disableCPUQuota)
```

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go [hunk 54]
```diff
@@ -55,7 +56,12 @@ func (m *kubeGenericRuntimeManager) calculateSandboxResources(pod *v1.Pod) *runt
 	if _, cpuRequestExists := req[v1.ResourceCPU]; cpuRequestExists {
 		cpuRequest = req.Cpu()
 	}
-	return m.calculateLinuxResources(cpuRequest, lim.Cpu(), lim.Memory())
+
+	// If pod has exclusive cpu the sandbox will not have cfs quote enforced
+	disableCPUQuota := utilfeature.DefaultFeatureGate.Enabled(features.DisableCPUQuotaWithExclusiveCPUs) && m.containerManager.PodHasExclusiveCPUs(pod)
+	klog.V(2).InfoS("Disabled CFS quota", "pod", klog.KObj(pod))
```
Comment (ffromani) [inline pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go:62]: ok, if you resubmit this should be like 
```
klog.V(2).InfoS("Enforcing CFS quota", "pod", klog.KObj(pod), "unlimited", disableCPUQuota)
```

**Review by ffromani — COMMENTED** [review]
/approve
/lgtm

There are 2 minor fixes missing but at this point I prefer not to resubmit _just because these_

File: pkg/kubelet/cm/container_manager.go (hunk 48 above)
Comment (scott-grimes) [reply pkg/kubelet/cm/container_manager.go]: reverted to v4. still helpful to have option for debugging this during featuregate period no?

**Comment by ffromani** [comment]
/approve

for
```
k/k/pkg/kubelet/cm
k/ktest/e2e_node
```

File: pkg/features/kube_features.go [hunk 55]
```diff
@@ -862,6 +862,21 @@ const (
...
+	// Disables CPU Quota for containers which have exclusive CPUs allocated.
+	// Disables pod-Level CPU Quota for pods containing at least one container with exclusive CPUs allocated
+	// Exclusive CPUs for a container (init, application, sidecar) are allocated when:
+	// (1) cpumanager policy is static,
+	// (2) the pod has QoS Guaranteed,
+	// (3) the container has integer cpu request.
+	// The expected behavior is that CPU Quota for containers having exclusive CPUs allocated is disabled.
+	// Because this fix changes a long-established (but incorrect) behavior, users observing
+	// any regressions can use the DisableCPUQuotaWithExclusiveCPUs feature gate (default on) to
+	// restore the old behavior. Please file issues if you hit issues and have to use this Feature Gate.
```
Comment (ffromani) [inline pkg/features/kube_features.go:878]: sig-node meeting 20250211: we somehow missed to add a note about removing the FG in Release+2, this would be 1.35. Let's add a line like
```
The Feature Gate will be locked to true and then removed in +2 releases (1.35) if there are no bug reported
```
once this is added we reached consensus about approving and merging

Comment (ffromani) [reply pkg/features/kube_features.go:878]: cc @SergeyKanzhelev @swatisehgal ^^^

**Review by swatisehgal — COMMENTED** [review]
> sig-node meeting 20250211: we somehow missed to add a note about removing the FG in Release+2, this would be 1.35. Let's add a line like
> 
> ```
> The Feature Gate will be locked to true and then removed in +2 releases (1.35) if there are no bug reported
> ```
> 
> once this is added we reached consensus about approving and merging

Thanks! Once we have the feature gate removal captured in the PR, LGTM from me!

File: pkg/kubelet/kuberuntime/kuberuntime_container_linux.go (hunk 53 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_container_linux.go:140]: done!

File: pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go (hunk 54 above)
Comment (scott-grimes) [reply pkg/kubelet/kuberuntime/kuberuntime_sandbox_linux.go:62]: done!

File: pkg/features/kube_features.go (hunk 55 above)
Comment (scott-grimes) [reply pkg/features/kube_features.go:878]: added!

**Comment by ffromani** [comment]
thanks for the quick update @scott-grimes ! LGTM and re-approved

**Comment by swatisehgal** [comment]
/assign @mrunalp 

for features approval

**Review by mrunalp — APPROVED** [review]

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Comment by ffromani** [comment]
it seems the bot was very slow to pick up approvals, but now it should be OK. Thanks everyone!
