### PR TITLE
fix ImageLocality plugin score is inconsistent

### LINKED ISSUE #116673: ImageLocality scored is inaccurate during 4 minutes after scheduler startup
### What happened?

The 8 of 10 nodes has same image that size is 4.09GB，but the score of ImageLocality is inconsistent during 4 minutes after 
scheduler startup. After 4 minutes, their scores are consistent.

the pod `bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq` and `ham-35878-202303152300-1-tklj4` use same image and only one container in pod.

```
node             has image
10.10.33.53   true
10.10.33.54   true
10.10.33.55   true
10.10.33.56   true
10.10.33.57   true
10.10.33.58   true
10.10.33.59   true
10.10.33.60   true
10.10.33.61   false
10.10.33.62  false
```

```
Log file created at: 2023/03/15 22:58:50
I0315 23:00:05.312827  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.57" score=100
I0315 23:00:05.312832  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.58" score=22
I0315 23:00:05.312837  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.61" score=0
I0315 23:00:05.312843  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.62" score=0
I0315 23:00:05.312848  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.56" score=47
I0315 23:00:05.312854  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.60" score=97
I0315 23:00:05.312859  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.54" score=100
I0315 23:00:05.312864  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.59" score=100
I0315 23:00:05.312869  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.53" score=100
I0315 23:00:05.312874  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.55" score=100

```

after 4minite
```
I0315 23:02:14.037872  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.58" score=100
I0315 23:02:14.037877  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.56" score=100
I0315 23:02:14.037882  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.57" score=100
I0315 23:02:14.037887  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.61" score=0
I0315 23:02:14.037892  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.62" score=0
I0315 23:02:14.037897  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.60" score=100
I0315 23:02:14.037902  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.54" score=100
I0315 23:02:14.037907  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.59" score=100
I0315 23:02:14.037914  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.53" score=100
I0315 23:02:14.037919  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.55" score=100
```

### What did you expect to happen?

ImageLocality score is alaway consistent

### How can we reproduce it (as minimally and precisely as possible)?

1. pull 4G image in some nodes
2. wait all node status containt that image
3. restart schedure and create pod that use 4G image
4. check the  scheduler log

### Anything else we need to know?

maybe reason is  get node info from snapshot https://github.com/kubernetes/kubernetes/blob/500bcf6c2b6f541afac3fbec1e05f5c315660fd6/pkg/scheduler/framework/plugins/imagelocality/image_locality.go#L55-L66

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:57:43Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:51:36Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
no
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by olderTaoist**
#### What type of PR is this?

/kind bug

the older manner is that update the `NodeInfo.ImageStates` field when receive add/update/delete event, but doesn't update

`ImageStates` of the exist `NodeInfo` when receive node add event, this manner cause inconsistent of ImageLocality plugin.

the new manner is that  update the `cache.imageStates` field when receive add/update/delete event,  update `ImageStates` 

of the exist `NodeInfo` according to `cache.imageStates` when beginning to schedule pod(in `UpdateSnapshot` function) 

#### Which issue(s) this PR fixes:

Fixes #116673

#### Does this PR introduce a user-facing change?
```release-note
Fixed inconsistency in the calculation of number of nodes that have an image, which affect the scoring in the ImageLocality plugin
```

### CODE REVIEW

File: pkg/scheduler/internal/cache/cache.go [hunk 1]
```diff
@@ -708,6 +710,24 @@ func (cache *cacheImpl) addNodeImageStates(node *v1.Node, nodeInfo *framework.No
 	nodeInfo.ImageStates = newSum
 }
 
+// updateNodeImageStates update node record from image entries having the node
+// in imageStates cache when receive node add/update/delete events.
+func (cache *schedulerCache) updateNodeImageStates(newNode *v1.Node) {
```
Comment (chendave) [inline pkg/scheduler/internal/cache/cache.go:715]: where is `schedulerCache`? this doesn't seems like compile-able.

Comment (olderTaoist) [reply pkg/scheduler/internal/cache/cache.go]: sorry，i cherry pick a commit base v1.23.6，now fix with cacheImpl struct

**Comment by olderTaoist** [comment]
It seems ready to merge, PTAL again @chendave

File: pkg/scheduler/internal/cache/cache.go [hunk 2]
```diff
@@ -708,6 +710,24 @@ func (cache *cacheImpl) addNodeImageStates(node *v1.Node, nodeInfo *framework.No
...
+// in imageStates cache when receive node add/update/delete events.
+func (cache *cacheImpl) updateNodeImageStates(newNode *v1.Node) {
+	for existNode := cache.headNode; existNode != nil; existNode = existNode.next {
+		node := existNode.info.Node()
+		if node == nil || node.Name == newNode.Name {
+			continue
+		}
+		newSum := make(map[string]*framework.ImageStateSummary)
+		for image := range cache.imageStates {
+			if cache.imageStates[image].nodes.Has(node.Name) {
```
Comment (chendave) [inline pkg/scheduler/internal/cache/cache.go:723]: why not just loop the map by k/v instead? so here you can deal with the value directly.

File: pkg/scheduler/internal/cache/cache.go [hunk 3]
```diff
@@ -708,6 +710,24 @@ func (cache *cacheImpl) addNodeImageStates(node *v1.Node, nodeInfo *framework.No
...
+				newSum[image] = cache.createImageStateSummary(cache.imageStates[image])
+			}
+		}
+		existNode.info.ImageStates = newSum
+	}
```
Comment (chendave) [inline pkg/scheduler/internal/cache/cache.go:728]: I don't quite understand the logic here, you are trying to update the cache with the value get from the cache, shouldn't this do by `addNodeImageStates` or `removeNodeImageStates` instead? Can you explain a little bit how this change fix the issue?

**Review by chendave — COMMENTED** [review]
Besides, this change needs some UT.

**Comment by olderTaoist** [comment]
> Besides, this change needs some UT.

now, i add UT

File: pkg/scheduler/internal/cache/cache.go (hunk 2 above)
Comment (olderTaoist) [reply pkg/scheduler/internal/cache/cache.go:723]: thanks for your suggestion

File: pkg/scheduler/internal/cache/cache.go (hunk 3 above)
Comment (olderTaoist) [reply pkg/scheduler/internal/cache/cache.go:728]: `addNodeImageStates` and `removeNodeImageStates ` just update the current node's imageState, but don't update    other node imageState with same image in current node.

File: pkg/scheduler/internal/cache/cache.go [hunk 4]
```diff
@@ -708,6 +710,24 @@ func (cache *cacheImpl) addNodeImageStates(node *v1.Node, nodeInfo *framework.No
 	nodeInfo.ImageStates = newSum
 }
 
+// updateNodeImageStates update node record from image entries having the node
+// in imageStates cache when receive node add/update/delete events.
+func (cache *cacheImpl) updateNodeImageStates(newNode *v1.Node) {
```
Comment (chendave) [inline pkg/scheduler/internal/cache/cache.go:715]: maybe this is a method that is called inside of `addNodeImageStates` or `removeNodeImageStates` as the second step to update other nodes' `imageState`?

**Review by chendave — COMMENTED** [review]
looks like a right fix to the issue by updating all nodes' image states, but the testcase is not intuitive enough to show score is now consistent.

cc to other reviews for thoughts. @kubernetes/sig-scheduling-misc

File: pkg/scheduler/internal/cache/cache.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/scheduler/internal/cache/cache.go:728]: -1

Every node should be treated independently for two reasons:
- performance: iterating over every node is expensive
- there is no guarantee that two images with the same name will have the same size in two different nodes

I say we close this PR and corresponding issue.

Comment (olderTaoist) [reply pkg/scheduler/internal/cache/cache.go:735]: > -1
> 
> Every node should be treated independently for two reasons:
> 
> * performance: iterating over every node is expensive
> * there is no guarantee that two images with the same name will have the same size in two different nodes
> 
> I say we close this PR and corresponding issue.

use [Parallelizer](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/parallelize/parallelism.go#L36) to improve performance. Besides, ImageLocality plugin does nothing to do with image size. as for the number of image in node status can use [nodeStatusMaxImages](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/) to limit

File: pkg/scheduler/internal/cache/cache_test.go [hunk 5]
```diff
@@ -2000,3 +2001,112 @@ func (cache *cacheImpl) getNodeInfo(nodeName string) (*v1.Node, error) {
 
 	return n.info.Node(), nil
 }
+
+func Test_cacheImpl_updateNodeImageStates(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (olderTaoist) [reply pkg/scheduler/internal/cache/cache_test.go:2005]: ImageLocality plugin use [sumImageScores](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/imagelocality/image_locality.go#L97) function to sumary score.  the function use [headNode](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/internal/cache/cache.go#LL70C3-L70C3).

File: pkg/scheduler/internal/cache/cache.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/scheduler/internal/cache/cache.go:735]: > there is no guarantee that two images with the same name will have the same size in two different nodes

Actually, scratch this. We are already making the assumption that all images have the same size in every node.

However, there is a more performant implementation that doesn't require going over all nodes:
get rid of `imageState` struct in the `cache` package and replace it with `framework.ImageStateSummary` (remove `Summary` from the name). Make sure all nodes point to the same `*framework.ImageState`. That way, you can increase the counter in one node, and it will affect all nodes.

Then, when grabbing a snapshot of the nodes, make sure to copy the values of `map[string]*framework.ImageState` so that we are not sharing the same pointers as the cache. Profit :)

Comment (olderTaoist) [reply pkg/scheduler/internal/cache/cache.go]: > > there is no guarantee that two images with the same name will have the same size in two different nodes
> 
> Actually, scratch this. We are already making the assumption that all images have the same size in every node.
> 
> However, there is a more performant implementation that doesn't require going over all nodes: get rid of `imageState` struct in the `cache` package and replace it with `framework.ImageStateSummary` (remove `Summary` from the name). Make sure all nodes point to the same `*framework.ImageState`. That way, you can increase the counter in one node, and it will affect all nodes.
> 
> Then, when grabbing a snapshot of the nodes, make sure to copy the values of `map[string]*framework.ImageState` so that we are not sharing the same pointers as the cache. Profit :)

thanks for your suggestion, i overridden implementation

File: pkg/scheduler/framework/types.go [hunk 6]
```diff
@@ -378,8 +378,15 @@ func getNamespacesFromPodAffinityTerm(pod *v1.Pod, podAffinityTerm *v1.PodAffini
 type ImageStateSummary struct {
 	// Size of the image
 	Size int64
-	// Used to track how many nodes have this image
-	NumNodes int
+	// A set of node names for nodes having this image present
+	Nodes sets.String
```
Comment (alculquicondor) [inline pkg/scheduler/framework/types.go:382]: Actually, let's keep track of both the set and the number of nodes in this object.

Then the function `ImageStateSummary.Clone` below can be renamed to `Snapshot` and only copy the number, but not the set, because that's all we need during a snapshot.

File: pkg/scheduler/framework/types.go [hunk 7]
```diff
@@ -587,6 +593,13 @@ func (n *NodeInfo) Clone() *NodeInfo {
 	if len(n.PodsWithRequiredAntiAffinity) > 0 {
 		clone.PodsWithRequiredAntiAffinity = append([]*PodInfo(nil), n.PodsWithRequiredAntiAffinity...)
 	}
+	if len(n.ImageStates) > 0 {
+		state := make(map[string]*ImageStateSummary)
```
Comment (alculquicondor) [inline pkg/scheduler/framework/types.go:597]:
```suggestion
		state := make(map[string]*ImageStateSummary, len(n.ImageStates))
```

**Review by alculquicondor — COMMENTED** [review]
A few more optimizations

**Comment by olderTaoist** [comment]
> Please add a release note

Sorry, i don't know how to add release note, although i already read [Adding Release Notes](https://www.kubernetes.dev/docs/guide/release-notes/). i try to use `krel release-notes --create-draft-pr` generate, but always fail

**Comment by alculquicondor** [comment]
You just edit the PR description, the block that starts with

```
```release-note
YOUR RELEASE NOTE HERE
```

File: pkg/scheduler/internal/cache/snapshot.go [hunk 8]
```diff
@@ -130,7 +130,7 @@ func getNodeImageStates(node *v1.Node, imageExistenceMap map[string]sets.Set[str
 		for _, name := range image.Names {
 			imageStates[name] = &framework.ImageStateSummary{
 				Size:     image.SizeBytes,
-				NumNodes: len(imageExistenceMap[name]),
```
[the remark this answers is not in the document]
Comment (olderTaoist) [reply pkg/scheduler/internal/cache/snapshot.go:133]: this is no need to get rid of this function.  the call relationship is `NewSnapshot` function  -> `createNodeInfoMap` function ->`getNodeImageStates` function,  param of [NewSnapshot](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/internal/cache/snapshot.go#LL56C6-L56C17) function just receive pods and nodes without cache struct. `NewSnapshot` just used in unit test

File: pkg/scheduler/framework/types.go [hunk 9]
```diff
@@ -380,6 +380,15 @@ type ImageStateSummary struct {
 	Size int64
 	// Used to track how many nodes have this image
 	NumNodes int
+	// A set of node names for nodes having this image present
+	Nodes sets.Set[string]
+}
+
+func (iss *ImageStateSummary) Snapshot() *ImageStateSummary {
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/framework/types.go:389]: Add a comment to this function too

File: pkg/scheduler/framework/types.go [hunk 10]
```diff
@@ -564,7 +571,6 @@ func (n *NodeInfo) Clone() *NodeInfo {
 		NonZeroRequested: n.NonZeroRequested.Clone(),
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/framework/types.go:575]: Can you do this? And update the comment.

**Review by alculquicondor — COMMENTED** [review]
/approve

Just add a couple of comments for the benefit of future readers of the code.

File: pkg/scheduler/internal/cache/cache.go [hunk 11]
```diff
@@ -70,7 +70,7 @@ type cacheImpl struct {
 	headNode *nodeInfoListItem
 	nodeTree *nodeTree
 	// A map from image name to its imageState.
```
Comment (chendave) [inline pkg/scheduler/internal/cache/cache.go:72]: A map from image name to its `ImageStateSummary`.

File: pkg/scheduler/internal/cache/cache.go [hunk 12]
```diff
@@ -691,17 +675,17 @@ func (cache *cacheImpl) addNodeImageStates(node *v1.Node, nodeInfo *framework.No
 			// update the entry in imageStates
```
Comment (chendave) [inline pkg/scheduler/internal/cache/cache.go:675]: s/imageStates/ImageStateSummary

**Review by chendave — COMMENTED** [review]
@olderTaoist can you pls rebase, is there any UT cover this change?

**Comment by kerthcet** [comment]
Can you add an explanation about what's the bug and how we solved it in the PR description, thanks. This is friendly for the future reader.

**Comment by alculquicondor** [comment]
This PR was almost ready. Please rebase so we can merge.

File: pkg/scheduler/internal/cache/cache.go (hunk 11 above)
Comment (olderTaoist) [reply pkg/scheduler/internal/cache/cache.go:72]: yeah, imageState need change to be ImageStateSummary

File: pkg/scheduler/internal/cache/cache.go (hunk 12 above)
Comment (olderTaoist) [reply pkg/scheduler/internal/cache/cache.go:675]: there is no need change to be ImageStateSummary,  imageStates just the field of cache struct

File: pkg/scheduler/framework/types.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (olderTaoist) [reply pkg/scheduler/framework/types.go:390]: done

**Comment by olderTaoist** [comment]
> Can you add an explanation about what's the bug and how we solved it in the PR description, thanks. This is friendly for the future reader.

done

**Comment by chendave** [comment]
/test pull-kubernetes-e2e-gce

there are still some pending nits to be cleanup, and as I said couple of times, this is a bug and we'd better to provide the testcase to verify the fixing, so that.

- prove this is a right fix
- prevent the similar issue to happen again, this will be guarded by the testcases.

But I understand this might depend on the bandwidth and some knowledge with the codebase.

/lgtm
/hold

feel free to lift the hold if you think this is ready to go.

File: pkg/scheduler/internal/cache/cache.go [hunk 13]
```diff
@@ -693,17 +677,17 @@ func (cache *cacheImpl) addNodeImageStates(node *v1.Node, nodeInfo *framework.No
...
 				cache.imageStates[name] = state
 			} else {
-				state.nodes.Insert(node.Name)
+				state.Nodes.Insert(node.Name)
 			}
-			// create the imageStateSummary for this image
+			// create the ImageStateSummary for this image
 			if _, ok := newSum[name]; !ok {
-				newSum[name] = cache.createImageStateSummary(state)
+				newSum[name] = state
```
Comment (kerthcet) [inline pkg/scheduler/internal/cache/cache.go:690]: IIUC, the problem we refer to the same state across nodeInfos is that we expose the entrance to modify the cache in scheduling cycle. It may lead to data race.

**Review by kerthcet — COMMENTED** [review]
I think we need unit test to prove that it fixed the bug.

File: pkg/scheduler/internal/cache/cache.go (hunk 13 above)
Comment (olderTaoist) [reply pkg/scheduler/internal/cache/cache.go:690]: there is no race, scheduler use `Snapshot` in scheduling cycle,  the `Snapshot` is updated  `UpdateSnapshot` function  that generate copy of NodeInfo according to cache when beginning to schedule pod.

**Comment by olderTaoist** [comment]
> I think we need unit test to prove that it fixed the bug.

done

**Comment by alculquicondor** [comment]
Almost every bug needs a release note, please add one.

Make sure that the release note explains the change from the perspective of an end-user that is not familiar with kube-scheduler code.

File: pkg/scheduler/framework/types.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/framework/types.go:576]: still not renamed :)

File: pkg/scheduler/schedule_one_test.go [hunk 14]
```diff
@@ -3085,6 +3087,174 @@ func TestPreferNominatedNodeFilterCallCounts(t *testing.T) {
...
+	}
+	tests := []struct {
+		name            string
+		pod             *v1.Pod
+		nodes           []*v1.Node
+		registerPlugins []st.RegisterPluginFunc
+		want            []framework.NodePluginScores
+	}{
+		{
+			name: "the score from Image Locality plugin",
```
Comment (alculquicondor) [inline pkg/scheduler/schedule_one_test.go:3160]: just one test case is enough?

File: pkg/scheduler/schedule_one_test.go [hunk 15]
```diff
@@ -3085,6 +3087,174 @@ func TestPreferNominatedNodeFilterCallCounts(t *testing.T) {
 	}
 }
 
+func TestImageLocalityPlugin(t *testing.T) {
```
Comment (alculquicondor) [inline pkg/scheduler/schedule_one_test.go:3090]: why here instead of the pkg/scheduler/framework/plugins/imagelocality package?

File: pkg/scheduler/internal/cache/cache.go
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/cache.go:1]: Ideally there should be some unit tests for this package too (independent of the imagelocality plugin)

**Review by alculquicondor — COMMENTED** [review]
/approve cancel

Thanks @kerthcet for pointing out the lack of testing here. I got too focused on the implementation that I forgot :)

**Comment by olderTaoist** [comment]
> Almost every bug needs a release note, please add one.
> 
> Make sure that the release note explains the change from the perspective of an end-user that is not familiar with kube-scheduler code.

just like fellow?
```release-note
Fix `NumNodes`  field of `NodeInfo.ImageStates` due to ImageLocality plugin score inconsistent
```

**Comment by olderTaoist** [comment]
> Almost every bug needs a release note, please add one.
> 
> Make sure that the release note explains the change from the perspective of an end-user that is not familiar with kube-scheduler code.

File: pkg/scheduler/internal/cache/cache.go (hunk 13 above)
Comment (kerthcet) [reply pkg/scheduler/internal/cache/cache.go:690]: Make sense, you added a new snapshot for ImageStateSummary. Thanks.

**Comment by alculquicondor** [comment]
> Fix `NumNodes`  field of `NodeInfo.ImageStates` due to ImageLocality plugin score inconsistent

That is a lot of implementation details. Something closer to the title is probably better:

```
Fixed inconsistency in the calculation of number of nodes that have an image, which affect the scoring in the ImageLocality plugin
```

**Review by alculquicondor — COMMENTED** [review]
Still missing tests for the internal/cache package.

**Comment by olderTaoist** [comment]
@alculquicondor @kerthcet @chendave Help to see what needs to be improved

File: pkg/scheduler/schedule_one_test.go (hunk 15 above)
Comment (alculquicondor) [reply pkg/scheduler/schedule_one_test.go:3090]: Can you move this to the imagelocality package?

File: pkg/scheduler/internal/cache/cache_test.go [hunk 16]
```diff
@@ -1081,48 +1081,59 @@ func buildNodeInfo(node *v1.Node, pods []*v1.Pod) *framework.NodeInfo {
...
+		"gcr.io/900:latest": int64(900 * mb),
+	}
+	node1 := st.MakeNode().Name("test-node-1").Capacity(resourceList1).Taints(taints).Images(imageStatus1)
+	node2 := st.MakeNode().Name("test-node-2").Capacity(resourceList2).Taints(taints).Images(imageStatus2)
+	node3 := st.MakeNode().Name("test-node-3").Capacity(resourceList1).Taints(taints).Images(imageStatus1)
+	node4 := st.MakeNode().Name("test-node-4").Capacity(resourceList2).Taints(taints).Images(imageStatus2)
 	tests := []struct {
-		node *v1.Node
-		pods []*v1.Pod
+		nodes map[string]*v1.Node
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/cache_test.go:1123]: it looks like this could be a slice instead

File: pkg/scheduler/internal/cache/cache_test.go [hunk 17]
```diff
@@ -1081,48 +1081,59 @@ func buildNodeInfo(node *v1.Node, pods []*v1.Pod) *framework.NodeInfo {
...
-					Taints: []v1.Taint{
-						{
-							Key:    "test-key",
-							Value:  "test-value",
-							Effect: v1.TaintEffectPreferNoSchedule,
-						},
-					},
-				},
-			},
+			nodes: map[string]*v1.Node{node1.GetName(): &node1.Node, node2.GetName(): &node2.Node,
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/cache_test.go:1127]: you can be more explicit:

```golang
nodes: []*v1.Node{
  st.MakeNode()...,
  st.MakeNode()...
}
```

This avoids having to jump from one line to another when reading tests https://enterprisecraftsmanship.com/posts/dry-damp-unit-tests/

File: pkg/scheduler/internal/cache/cache_test.go [hunk 18]
```diff
@@ -1081,48 +1081,59 @@ func buildNodeInfo(node *v1.Node, pods []*v1.Pod) *framework.NodeInfo {
...
+			Key:    "test-key",
+			Value:  "test-value",
+			Effect: v1.TaintEffectPreferNoSchedule,
+		},
+	}
+	fake80Image := "gcr.io/80:latest"
+	fake300Image := "gcr.io/300:latest"
+	imageStatus1 := map[string]int64{
+		fake80Image:     int64(80 * mb),
+		"gcr.io/80:v1":  int64(80 * mb),
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/cache_test.go:1109]: why mix constants and literals?
Choose one, but preferably literals (in tests)

File: pkg/scheduler/internal/cache/cache_test.go [hunk 19]
```diff
@@ -1214,34 +1206,48 @@ func TestNodeOperators(t *testing.T) {
 			logger, ctx := ktesting.NewTestContext(t)
 			ctx, cancel := context.WithCancel(ctx)
 			defer cancel()
-			expected := buildNodeInfo(test.node, test.pods)
-			node := test.node
+			expected := buildNodeInfo(&node1.Node, test.pods)
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/cache_test.go:1209]: why is this node special?
If anything, take it from the list instead.

File: pkg/scheduler/internal/cache/cache_test.go [hunk 20]
```diff
@@ -1214,34 +1206,48 @@ func TestNodeOperators(t *testing.T) {
...
+			}
 			for _, pod := range test.pods {
 				if err := cache.AddPod(logger, pod); err != nil {
 					t.Fatal(err)
 				}
 			}
+			for index := range expected.Node().Status.Images {
+				for _, name := range expected.Node().Status.Images[index].Names {
+					if imageState, ok := cache.imageStates[name]; ok {
+						expected.ImageStates[name] = imageState
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/cache_test.go:1224]: avoid automatic population of "expected" values. Instead, make the expectations part of the test table

File: pkg/scheduler/internal/cache/cache_test.go [hunk 21]
```diff
@@ -2002,6 +2016,31 @@ func makeBasePod(t testingMode, nodeName, objName, cpu, mem, extended string, po
 	return podWrapper.Obj()
 }
 
+func checkNumNodesOfImageState(nodes map[string]*framework.NodeInfo, imageNames ...string) bool {
```
Comment (alculquicondor) [inline pkg/scheduler/internal/cache/cache_test.go:2019]: this is too much logic again. Try to do direct comparisons.

**Comment by alculquicondor** [comment]
The runtime code LGTM overall.
The unit tests have too much processing. Adding more fields into the test table that explicitly tell which values we expect would help (instead of deducing them from code).

I have too much review load, so I'm reassigning this to
/assign @ahg-g 
/unassign

**Comment by olderTaoist** [comment]
> The runtime code LGTM overall. The unit tests have too much processing. Adding more fields into the test table that explicitly tell which values we expect would help (instead of deducing them from code).
> 
> I have too much review load, so I'm reassigning this to /assign @ahg-g /unassign

 i optimize unit test  according to suggestion,  @ahg-g @alculquicondor  @chendave PTAL

File: pkg/scheduler/schedule_one_test.go [hunk 22]
```diff
@@ -2660,6 +2662,73 @@ func TestZeroRequest(t *testing.T) {
...
+			},
+		},
+	}
+	pod1Spec := v1.PodSpec{
+		Containers: []v1.Container{
+			{
+				Image: "gcr.io/300",
+			},
+		},
+	}
```
Comment (ahg-g) [inline pkg/scheduler/schedule_one_test.go:2678]: those specs are used once, so just inline them instead of defining those variables.

File: pkg/scheduler/schedule_one_test.go [hunk 23]
```diff
@@ -2846,16 +2915,116 @@ func Test_prioritizeNodes(t *testing.T) {
 				{Name: "node2", Scores: []framework.PluginScore{}},
 			},
 		},
+		{
+			name: "the score from Image Locality plugin with image in all nodes",
+			pod:  &v1.Pod{Spec: podSpec},
```
Comment (ahg-g) [inline pkg/scheduler/schedule_one_test.go:2920]:
```suggestion
			pod:  &v1.Pod{Spec: v1.PodSpec{
		Containers: []v1.Container{
			{
				Image: "gcr.io/40",
			},
		},
	}},
```

File: pkg/scheduler/schedule_one_test.go [hunk 24]
```diff
@@ -2846,16 +2915,116 @@ func Test_prioritizeNodes(t *testing.T) {
...
+							Score: 5,
+						},
+					},
+					TotalScore: 5,
+				},
+			},
+		},
+		{
+			name: "the score from Image Locality plugin with image in partial nodes",
+			pod:  &v1.Pod{Spec: pod1Spec},
```
Comment (ahg-g) [inline pkg/scheduler/schedule_one_test.go:2967]:
```suggestion
			pod:  &v1.Pod{Spec: v1.PodSpec{
		Containers: []v1.Container{
			{
				Image: "gcr.io/300",
			},
		},
	}},
```

File: pkg/scheduler/internal/cache/cache_test.go [hunk 25]
```diff
@@ -1223,13 +1252,17 @@ func TestNodeOperators(t *testing.T) {
 				t.Error(err)
 			}
 			newNode, found := cachedNodes.nodeInfoMap[node.Name]
-			if !found || len(cachedNodes.nodeInfoMap) != 1 {
+			if !found || len(cachedNodes.nodeInfoMap) != len(tc.nodes) {
 				t.Errorf("failed to dump cached nodes:\n got: %v \nexpected: %v", cachedNodes, cache.nodes)
```
Comment (chendave) [inline pkg/scheduler/internal/cache/cache_test.go:1256]: pls update all those error msg, got is actually `cachedNodes.nodeInfoMap` and expected is `tc.nodes`

File: pkg/scheduler/internal/cache/cache_test.go [hunk 26]
```diff
@@ -1223,13 +1252,17 @@ func TestNodeOperators(t *testing.T) {
...
 			}
 			expected.Generation = newNode.Generation
-			if !reflect.DeepEqual(newNode, expected) {
+			if !reflect.DeepEqual(newNode, expected.Snapshot()) {
 				t.Errorf("Failed to clone node:\n got: %+v, \n expected: %+v", newNode, expected)
```
Comment (chendave) [inline pkg/scheduler/internal/cache/cache_test.go:1260]: update this as well.

File: pkg/scheduler/framework/types.go [hunk 27]
```diff
@@ -611,15 +624,15 @@ func (n *NodeInfo) Node() *v1.Node {
 	return n.node
 }
 
-// Clone returns a copy of this node.
-func (n *NodeInfo) Clone() *NodeInfo {
+// Snapshot returns a copy of this node.
```
Comment (chendave) [inline pkg/scheduler/framework/types.go:627]: ... except that `ImageStates` is copied without the `Nodes` field.

**Comment by ahg-g** [comment]
When you address any comments, please don't amend, otherwise it is hard to identify what changed from the last review. 

See https://github.com/kubernetes/community/blob/master/sig-scheduling/CONTRIBUTING.md#best-practices

File: pkg/scheduler/internal/cache/cache_test.go [hunk 28]
```diff
@@ -1066,54 +1066,86 @@ func TestForgetPod(t *testing.T) {
...
+						Size:  image.SizeBytes,
+						Nodes: sets.New[string](item.Name),
+					}
+					imageStates[name] = state
+				} else {
+					state.Nodes.Insert(item.Name)
+				}
+			}
+		}
+	}
```
[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/scheduler/internal/cache/cache_test.go:1074]: pls resolve the comments that you think you addressed just so we know which ones are done and which are still in progress

File: pkg/scheduler/internal/cache/cache_test.go (hunk 21 above)
Comment (ahg-g) [reply pkg/scheduler/internal/cache/cache_test.go:2017]: was this addressed?

**Comment by olderTaoist** [comment]
> When you address any comments, please don't amend, otherwise it is hard to identify what changed from the last review.
> 
> See https://github.com/kubernetes/community/blob/master/sig-scheduling/CONTRIBUTING.md#best-practices

will be many commits depend on review advice, then reset commits after reviewer approve?

**Comment by ahg-g** [comment]
> > When you address any comments, please don't amend, otherwise it is hard to identify what changed from the last review.
> > See https://github.com/kubernetes/community/blob/master/sig-scheduling/CONTRIBUTING.md#best-practices
> 
> will be many commits depend on review advice, then reset commits after reviewer approve?

Correct, at the end you squash when the last reviewer is done.

**Comment by olderTaoist** [comment]
> > > When you address any comments, please don't amend, otherwise it is hard to identify what changed from the last review.
> > > See https://github.com/kubernetes/community/blob/master/sig-scheduling/CONTRIBUTING.md#best-practices
> > 
> > 
> > will be many commits depend on review advice, then reset commits after reviewer approve?
> 
> Correct, at the end you squash when the last reviewer is done.

thanks, got it. i will do like that next pr

File: pkg/scheduler/framework/types.go [hunk 29]
```diff
@@ -433,8 +433,21 @@ func getNamespacesFromPodAffinityTerm(pod *v1.Pod, podAffinityTerm *v1.PodAffini
 type ImageStateSummary struct {
 	// Size of the image
 	Size int64
-	// Used to track how many nodes have this image
+	// Used to track how many nodes have this image, It is computed from the Nodes field below
+	// during the execution of Snapshot.
 	NumNodes int
+	// A set of node names for nodes having this image present. This field is used for
+	// keeping track of the nodes during update/add/remove events.
+	// This slice is not duplicated when calling Snapshot.
```
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/framework/types.go:441]: this is not fixed.

File: pkg/scheduler/framework/types.go [hunk 30]
```diff
@@ -433,8 +433,21 @@ func getNamespacesFromPodAffinityTerm(pod *v1.Pod, podAffinityTerm *v1.PodAffini
 type ImageStateSummary struct {
 	// Size of the image
 	Size int64
-	// Used to track how many nodes have this image
+	// Used to track how many nodes have this image, It is computed from the Nodes field below
+	// during the execution of Snapshot.
```
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/framework/types.go:437]: if this is not make sense to you, pls comment and response.

**Review by chendave — COMMENTED** [review]
Looks much closer, thanks @olderTaoist for the patient!

**Comment by olderTaoist** [comment]
please review again @chendave @ahg-g

**Comment by chendave** [comment]
@olderTaoist  pls address for all the existing comments first.

File: pkg/scheduler/framework/types.go [hunk 31]
```diff
@@ -448,8 +448,21 @@ func getNamespacesFromPodAffinityTerm(pod *v1.Pod, podAffinityTerm *v1.PodAffini
...
 	NumNodes int
+	// A set of node names for nodes having this image present. This field is used for
+	// keeping track of the nodes during update/add/remove events.
+	// This slice is not duplicated when calling Snapshot.
```
Comment (chendave) [inline pkg/scheduler/framework/types.go:456]: just remove this line, it's already clear to see it's won't be duplicated.
```suggestion

```

**Review by chendave — COMMENTED** [review]
Another round of review, and FYI, the code freezing is approaching, I noticed you have pushed some additional commits but they are not shown up here.

**Comment by olderTaoist** [comment]
> Another round of review, and FYI, the code freezing is approaching, I noticed you have pushed some additional commits but they are not shown up here.

i just squash commit as @ahg-g suggestion. there are no more change.

**Comment by olderTaoist** [comment]
@chendave @ahg-g Does this pr need to be adjusted?

**Comment by olderTaoist** [comment]
@chendave @ahg-g @alculquicondor  PATL

File: pkg/scheduler/framework/types.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/framework/types.go:472]: pls resolve these comments which you have addressed.

File: pkg/scheduler/framework/types.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/framework/types.go:659]: mark this as resolved pls.

File: pkg/scheduler/internal/cache/cache.go
Comment (chendave) [reply pkg/scheduler/internal/cache/cache.go:1]: Do you have some testcase created to address comments? @olderTaoist

File: pkg/scheduler/internal/cache/cache.go (hunk 12 above)
Comment (chendave) [reply pkg/scheduler/internal/cache/cache.go:677]: mark this as resolved as well pls.

File: pkg/scheduler/internal/cache/cache.go [hunk 32]
```diff
@@ -691,17 +675,17 @@ func (cache *cacheImpl) addNodeImageStates(node *v1.Node, nodeInfo *framework.No
...
-					size:  image.SizeBytes,
-					nodes: sets.New(node.Name),
+				state = &framework.ImageStateSummary{
+					Size:  image.SizeBytes,
+					Nodes: sets.New[string](node.Name),
 				}
 				cache.imageStates[name] = state
 			} else {
-				state.nodes.Insert(node.Name)
+				state.Nodes.Insert(node.Name)
```
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/internal/cache/cache.go:686]: Does that comment still stand?

File: pkg/scheduler/internal/cache/cache_test.go [hunk 33]
```diff
@@ -1188,34 +1209,44 @@ func TestNodeOperators(t *testing.T) {
...
 			expected.Generation = got.info.Generation
-			if diff := cmp.Diff(expected, got.info, cmp.AllowUnexported(framework.NodeInfo{})); diff != "" {
-				t.Errorf("Unexpected node info from cache (-want, +got):\n%s", diff)
+			if diff := cmp.Diff(got.info, expected, cmp.AllowUnexported(framework.NodeInfo{})); diff != "" {
+				t.Errorf("Failed to add node into scheduler cache (-want,+got):\n%s", diff)
+			}
+
+			// check imageState of NodeInfo with specific image when node added
+			if !checkNumNodesOfImageState(nodes, "gcr.io/80:latest", "gcr.io/300:latest") {
+				t.Error("image have different NumNodes")
```
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/internal/cache/cache_test.go:1252]: Did you address this comment?

File: pkg/scheduler/internal/cache/cache_test.go [hunk 34]
```diff
@@ -1976,6 +2015,28 @@ func makeBasePod(t testingMode, nodeName, objName, cpu, mem, extended string, po
...
+			if imageState == nil {
+				imageState = state
+				continue
+			}
+			if !reflect.DeepEqual(imageState, state) {
+				return false
+			}
+		}
+	}
+	return true
```
[the remark this answers is not in the document]
Comment (chendave) [reply pkg/scheduler/internal/cache/cache_test.go:2044]: Have you addressed this comment?

**Review by chendave — COMMENTED** [review]
It's quite a long time, but I still see some pending review comments there. I'd suggest to ask for review only in case all those comments are either addressed or replied.

**Comment by olderTaoist** [comment]
> It's quite a long time, but I still see some pending review comments there. I'd suggest to ask for review only in case all those comments are either addressed or replied.

all comment addressed, i just figured out how to mark comment as addressed

File: pkg/scheduler/framework/types.go [hunk 35]
```diff
@@ -638,15 +650,16 @@ func (n *NodeInfo) Node() *v1.Node {
 	return n.node
 }
 
-// Clone returns a copy of this node.
-func (n *NodeInfo) Clone() *NodeInfo {
+// Snapshot returns a copy of this node,
+// Except that ImageStates is copied without the Nodes field.
```
Comment (chendave) [inline pkg/scheduler/framework/types.go:654]:
```suggestion
// Snapshot returns a copy of this node, except that ImageStates is copied without the Nodes field.
```

File: pkg/scheduler/internal/cache/cache_test.go [hunk 36]
```diff
@@ -1976,6 +2022,28 @@ func makeBasePod(t testingMode, nodeName, objName, cpu, mem, extended string, po
...
+		for _, node := range nodes {
+			state, ok := node.ImageStates[imageName]
+			if !ok {
+				continue
+			}
+			if imageState == nil {
+				imageState = state
+				continue
+			}
+			if !reflect.DeepEqual(imageState, state) {
```
Comment (chendave) [inline pkg/scheduler/internal/cache/cache_test.go:2039]: same here.

File: pkg/scheduler/internal/cache/cache_test.go [hunk 37]
```diff
@@ -1095,7 +1131,7 @@ func TestNodeOperators(t *testing.T) {
 						UID:  types.UID("pod1"),
 					},
 					Spec: v1.PodSpec{
-						NodeName: nodeName,
+						NodeName: "test-node-1",
```
Comment (chendave) [inline pkg/scheduler/internal/cache/cache_test.go:1134]: revert the change in L1055 and use `nodeName` here instead.

File: pkg/scheduler/internal/cache/cache_test.go [hunk 38]
```diff
@@ -1224,12 +1258,16 @@ func TestNodeOperators(t *testing.T) {
...
 			newNode, found := cachedNodes.nodeInfoMap[node.Name]
-			if !found || len(cachedNodes.nodeInfoMap) != 1 {
-				t.Errorf("failed to dump cached nodes:\n got: %v \nexpected: %v", cachedNodes, cache.nodes)
+			if !found || len(cachedNodes.nodeInfoMap) != len(tc.nodes) {
+				t.Errorf("failed to dump cached nodes:\n got: %v \nexpected: %v", cachedNodes.nodeInfoMap, tc.nodes)
 			}
 			expected.Generation = newNode.Generation
-			if diff := cmp.Diff(expected, newNode, cmp.AllowUnexported(framework.NodeInfo{})); diff != "" {
-				t.Errorf("Unexpected clone node info (-want, +got):\n%s", diff)
+			if !reflect.DeepEqual(newNode, expected.Snapshot()) {
```
Comment (chendave) [inline pkg/scheduler/internal/cache/cache_test.go:1265]: I remember there is a suggestion to use `diff.cmp` in this sig, other reviewers should happy with this change.

File: pkg/scheduler/internal/cache/cache_test.go [hunk 39]
```diff
@@ -1278,9 +1320,13 @@ func TestNodeOperators(t *testing.T) {
 			if err != nil {
 				t.Fatal(err)
 			}
-			if cache.nodeTree.numNodes != 0 || len(nodesList) != 0 {
+			if cache.nodeTree.numNodes != len(tc.nodes)-1 || len(nodesList) != len(tc.nodes)-1 {
 				t.Errorf("unexpected cache.nodeTree after removing node: %v", node.Name)
 			}
+			// check imageState of NodeInfo with specific image when delete node
+			if !checkImageStateSummary(nodes, "gcr.io/80:latest", "gcr.io/300:latest") {
+				t.Error("image have different ImageStateSummary after remove node")
```
Comment (chendave) [inline pkg/scheduler/internal/cache/cache_test.go:1328]:
```suggestion
				t.Error("image have different ImageStateSummary after removing node")
```

**Review by chendave — COMMENTED** [review]
Generally LGTM.

Ideally, the fix in `pkg/scheduler/framework/types.go` and the refactoring around `snapshot` renaming along with the removing of `imageState` struct should be organized in different commits, the change like this is hard to review TBH.


pls double check the logic around this comments:
https://github.com/kubernetes/kubernetes/pull/116938/files#r1249435336

/cc @kubernetes/sig-scheduling-approvers 

for a double check and approval.

File: pkg/scheduler/framework/types.go (hunk 30 above)
[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/scheduler/framework/types.go:464]: In snapshot we are not cloning this map, and so the number of nodes may change during the scheduling cycle, right? if so, then in reality len(Nodes) and NumNodes is different.

**Review by ahg-g — COMMENTED** [review]
looks good to me, just change the DeepEqual to diff.cmp pls

**Comment by chendave** [comment]
/lgtm

thanks!
