### PR TITLE
Fix httplog not logging watch duration

### LINKED ISSUE #125614: kube-apiserver logs watch requests before they end in 1.30
### What happened?

In 1.30, WATCH request is logged immediately when a watch is opened, with very low latency. There appears to be no trace of when the watch ends. This significantly impacts debugging capability for issues with establishing watches. 

Example for consecutive watches on pods opened by kube-scheduler - each appears to be lasting 8-9 minutes, everything works in the cluster, but the latency doesn't match watch length, the request is logged immediately, and with `resp=0`:

```
I0620 12:33:17.389016      11 httplog.go:132] "HTTP" verb="WATCH" URI="/api/v1/pods?allowWatchBookmarks=true&fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed&resourceVersion=97186&timeout=9m12s&timeoutSeconds=552&watch=true" latency="470.891µs" userAgent="kube-scheduler/v1.30.2 (linux/amd64) kubernetes/85fad5b/scheduler" audit-ID="2cf3b6d8-8c04-4065-8bb8-ccd209f24063" srcIP="[::1]:60566" apf_pl="workload-high" apf_fs="kube-scheduler" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_init_latency="252.569µs" apf_execution_time="253.277µs" resp=0
...
I0620 12:42:29.390797      11 get.go:261] "Starting watch" path="/api/v1/pods" resourceVersion="135790" labels="" fields="status.phase!=Failed,status.phase!=Succeeded" timeout="6m10s"
I0620 12:42:29.391006      11 httplog.go:132] "HTTP" verb="WATCH" URI="/api/v1/pods?allowWatchBookmarks=true&fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed&resourceVersion=135790&timeout=6m10s&timeoutSeconds=370&watch=true" latency="629.842µs" userAgent="kube-scheduler/v1.30.2 (linux/amd64) kubernetes/85fad5b/scheduler" audit-ID="619843d2-3f2a-4c2e-960a-17eecc71695b" srcIP="[::1]:60566" apf_pl="workload-high" apf_fs="kube-scheduler" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_init_latency="299.938µs" apf_execution_time="300.55µs" resp=0
```

### What did you expect to happen?

Watches are usually long (~minutes). In 1.29 and earlier log looks like this:

```
I0620 12:30:26.940451      11 get.go:260] "Starting watch" path="/api/v1/pods" resourceVersion="93431" labels="" fields="status.phase!=Failed,status.phase!=Succeeded" timeout="8m18s"
...
I0620 12:38:44.940817      11 httplog.go:132] "HTTP" verb="WATCH" URI="/api/v1/pods?allowWatchBookmarks=true&fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed&resourceVersion=93431&timeout=8m18s&timeoutSeconds=498&watch=true" latency="8m18.00060226s" userAgent="kube-scheduler/v1.29.6 (linux/amd64) kubernetes/43a444e/scheduler" audit-ID="c39f0303-10ad-4b51-baf4-87c592fcb85e" srcIP="[::1]:39438" apf_pl="workload-high" apf_fs="kube-scheduler" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_init_latency="280.462µs" apf_execution_time="281.612µs" resp=200
```

### How can we reproduce it (as minimally and precisely as possible)?

Compare kube-apiserver log in 1.29 and 1.30.

### Anything else we need to know?

Log line examples are taken from passing runs of gce-scalabiltiy-100 tests: 
- https://testgrid.k8s.io/sig-scalability-gce#gce-cos-1.29-scalability-100 : https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-1-29/1803759918289784832
- https://testgrid.k8s.io/sig-scalability-gce#gce-cos-1.30-scalability-100 : https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-1-30/1803759918403031040

### Kubernetes version

Observed in 1.30.2 and 1.30.1. To be verified if present in 1.30.0..

### Cloud provider

N/A

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

### PR DESCRIPTION
**Pull request by linxiulei**
#### What type of PR is this?

/kind bug

#### Which issue(s) this PR fixes:

Fixes #125614

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: cmd/kube-scheduler/app/server.go [hunk 1]
```diff
@@ -283,7 +283,7 @@ func buildHandlerChain(handler http.Handler, authn authenticator.Request, authz
 	handler = genericapifilters.WithAuthentication(handler, authn, failedHandler, nil, nil)
 	handler = genericapifilters.WithRequestInfo(handler, requestInfoResolver)
 	handler = genericapifilters.WithCacheControl(handler)
-	handler = genericfilters.WithHTTPLogging(handler)
+	handler = genericfilters.WithHTTPLogging(handler, func(_ context.Context, f func()) { f() })
```
Comment (wojtek-t) [inline cmd/kube-scheduler/app/server.go:286]: This is very hard to think about what's happening.

Why can't we just do the following:
- change `withLogging` to do more-or-less exactly what's `ListResource` is doing [check if TaskFrom is non-nil and if so append to it]
- not change anything else...

Comment (linxiulei) [reply cmd/kube-scheduler/app/server.go:286]: > change withLogging to do more-or-less exactly what's ListResource is doing [check if TaskFrom is non-nil and if so append to it]

Actually my first attempt was like that. But it caused cycle import if we call TaskFrom in `httplog`. Let me try if I can work this around.

Comment (linxiulei) [reply cmd/kube-scheduler/app/server.go]: Not sure if it's an overkill to move routine filter in a separate directory to tackle the cycle import issue. But it should be what you suggested.

File: staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go [hunk 2]
```diff
@@ -125,10 +126,19 @@ func withLogging(handler http.Handler, stackTracePred StacktracePred, shouldLogR
...
+			if !logInRoutine {
+				rl.Log()
+			}
+		}()
 
 		w = responsewriter.WrapForHTTP1Or2(rl)
 		handler.ServeHTTP(w, req)
+
+		if routine.AppendTask(ctx, &routine.Task{Func: rl.Log}) {
+			logInRoutine = true
```
Comment (siyuanfoundation) [inline staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go:140]: can you explain a bit what would happen when `logInRoutine = true`?

Comment (linxiulei) [reply staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go:142]: We added a feature to run the watch serving in a separate goroutine to free stack memory allocated by Golang runtime (https://github.com/kubernetes/kubernetes/pull/120902). This code determines if it is the case and run the `rl.log()` at the end of the aforementioned goroutine.

I also added comment to explain that a bit. Thanks!

File: staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go [hunk 3]
```diff
@@ -125,10 +126,21 @@ func withLogging(handler http.Handler, stackTracePred StacktracePred, shouldLogR
 		rl := newLoggedWithStartTime(req, w, startTime)
 		rl.StacktraceWhen(stackTracePred)
 		req = req.WithContext(context.WithValue(ctx, respLoggerContextKey, rl))
-		defer rl.Log()
+		logInRoutine := false
```
Comment (wojtek-t) [inline staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go:129]: nit: I would switch to sth like;
```
var logFunc func()
logFunc = rl.Log
defer func() {
  if logFunc != nil {
    logFunc()
  }
}()
````

File: staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go [hunk 4]
```diff
@@ -125,10 +126,21 @@ func withLogging(handler http.Handler, stackTracePred StacktracePred, shouldLogR
...
+			if !logInRoutine {
+				rl.Log()
+			}
+		}()
 
 		w = responsewriter.WrapForHTTP1Or2(rl)
 		handler.ServeHTTP(w, req)
+
+		// log after the task is executed in the separate routine
+		// there is a task created in handler.ServeHTTP()
```
Comment (wojtek-t) [inline staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go:140]: Let's put more context into this comment - I don't think it clarifies enough for people not familiar with it.

// We need to ensure that the request is logged after it is processed.
// In case the request is executed in a separate goroutine (created via
// WithRoutine handler in the handler chain), we want the logging to
// happen in that goroutine too, so we append it to the task.

File: staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go [hunk 5]
```diff
@@ -125,10 +126,21 @@ func withLogging(handler http.Handler, stackTracePred StacktracePred, shouldLogR
...
+		if routine.AppendTask(ctx, &routine.Task{Func: rl.Log}) {
```
Comment (wojtek-t) [inline staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go:141]: Hmm - when calling AppendTask, the main function is not yet set, right?
So won't it be overwritten later anyway?

I would like to see test output to see we actually fixed the problem.

File: staging/src/k8s.io/apiserver/pkg/server/routine/routine.go [hunk 6]
```diff
@@ -35,6 +35,20 @@ func WithTask(parent context.Context, t *Task) context.Context {
 	return request.WithValue(parent, taskKey, t)
 }
 
+// AppendTask appends a task executed after completion of existing task.
+// It is a no-op if there is no existing task.
+func AppendTask(ctx context.Context, t *Task) bool {
```
Comment (wojtek-t) [inline staging/src/k8s.io/apiserver/pkg/server/routine/routine.go:40]: This deserves some unit test.

File: staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go (hunk 5 above)
Comment (linxiulei) [reply staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go:141]: the main function is already set in the handler.ServeHTTP() above. I did test it and saw logs:

```
I0629 09:31:28.480093  980427 get.go:261] "Starting watch" path="/api/v1/namespaces/default/configmaps" resourceVersion="2031772" labels="" fields="" timeout="32m26.197309045s"
I0629 09:31:32.709322  980427 routine.go:45] "HTTP" verb="WATCH" URI="/api/v1/namespaces/default/configmaps?resourceVersion=2031772&watch=true" latency="4.229978453s" userAgent="kubectl/v1.27.15 (linux/amd64) kubernetes/a62bdc4" audit-ID="00868cb3-d8d2-4f07-b6d3-808ca095fb32" srcIP="127.0.0.1:56660" apf_pl="global-default" apf_fs="global-default1" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_init_latency="578.4µs" apf_execution_time="579.83µs" resp=200
```

File: staging/src/k8s.io/apiserver/pkg/server/routine/routine.go (hunk 6 above)
Comment (linxiulei) [reply staging/src/k8s.io/apiserver/pkg/server/routine/routine.go:40]: Added

File: staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go (hunk 3 above)
Comment (linxiulei) [reply staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go]: Done

Comment (siyuanfoundation) [reply staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go]: this is much more clearer.

File: staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go (hunk 5 above)
Comment (wojtek-t) [reply staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go:146]: OK right - it's not called, but it's set.

File: staging/src/k8s.io/apiserver/pkg/server/routine/routine.go (hunk 6 above)
Comment (wojtek-t) [reply staging/src/k8s.io/apiserver/pkg/server/routine/routine.go:40]: You added unit test, but it's not testing the logic in this function.

I would like to see a unit test for the Append function itself.

**Comment by wojtek-t** [comment]
One more request for unit test - other than that LGTM

File: staging/src/k8s.io/apiserver/pkg/server/routine/routine.go (hunk 6 above)
Comment (linxiulei) [reply staging/src/k8s.io/apiserver/pkg/server/routine/routine.go:40]: I added `TestAppendTest`. Can you please clarify which logic is missed in that test?

https://github.com/kubernetes/kubernetes/pull/125626/files#diff-6fb1ba0a2fe370754b5df8125bd60ba5523c1266d4526f803a21eaee26db8d0eR47

Comment (wojtek-t) [reply staging/src/k8s.io/apiserver/pkg/server/routine/routine.go:40]: It doesn't call "AppendTask" function. I want the unit test to test exactly this function.

File: staging/src/k8s.io/apiserver/pkg/server/routine/routine_test.go [hunk 7]
```diff
@@ -0,0 +1,84 @@
...
+	_, err := http.Get(ts.URL)
+	if err != nil {
+		t.Errorf("got unexpected error on request: %v", err)
+	}
+	if !executed {
+		t.Error("expected to execute")
+	}
+}
+
+func TestAppendTest(t *testing.T) {
```
Comment (wojtek-t) [inline staging/src/k8s.io/apiserver/pkg/server/routine/routine_test.go:47]: nit: should probably be TestAppendTask

File: staging/src/k8s.io/apiserver/pkg/server/routine/routine.go (hunk 6 above)
Comment (linxiulei) [reply staging/src/k8s.io/apiserver/pkg/server/routine/routine.go:40]: Make sense. Changed.
