### PR TITLE
DRA: for delayed allocation, deallocate when no longer used

### LINKED ISSUE #118613: DRA: delayed allocation: deallocate after use
When a ResourceClaim:
- uses delayed allocation
- does not get created for a specific pod (i.e. not from a template)

then it currently gets allocated and remains allocated until:
- scheduling of a pod fails because the node originally chosen for the allocation isn't suitable, in which case the scheduler triggers deallocation via `claim.status.deallocationRequested`
- the user deletes the claim

What we want instead is that deallocation gets triggered when the last user of such an allocated claim gets removed from `claim.status.reservedFor`. To avoid races, deallocation must be done through `deallocationRequested`.

This can be implemented either as a controller or directly in the API server.

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

When a ResourceClaim:

- uses delayed allocation
- does not get created for a specific pod (i.e. not from a template)

then it currently gets allocated and remains allocated until:

- scheduling of a pod fails because the node originally chosen for the allocation isn't suitable, in which case the scheduler triggers deallocation via claim.status.deallocationRequested
- the user deletes the claim

What we want instead is that deallocation gets triggered when the last user of such an allocated claim gets removed from `claim.status.reservedFor`.

#### Which issue(s) this PR fixes:
Fixes #118613

#### Special notes for your reviewer:

A prior revision did this in the apiserver:
```patch
diff --git a/pkg/registry/resource/resourceclaim/strategy.go b/pkg/registry/resource/resourceclaim/strategy.go
index 1b65e87ade6..f82ac0253d4 100644
--- a/pkg/registry/resource/resourceclaim/strategy.go
+++ b/pkg/registry/resource/resourceclaim/strategy.go
@@ -124,6 +124,29 @@ func (resourceclaimStatusStrategy) GetResetFields() map[fieldpath.APIVersion]*fi
 func (resourceclaimStatusStrategy) PrepareForUpdate(ctx context.Context, obj, old runtime.Object) {
        newClaim := obj.(*resource.ResourceClaim)
        oldClaim := old.(*resource.ResourceClaim)
+
+       // When a ResourceClaim uses delayed allocation, then it makes sense to
+       // deallocate the claim as soon as the last consumer stops using
+       // it. This ensures that the claim can be allocated again as needed by
+       // some future consumer instead of trying to schedule that consumer
+       // onto the node that was chosen for the previous consumer. It also
+       // releases the underlying resources for use by other claims.
+       //
+       // This has to be triggered by the transition from "was being used" to
+       // "is not used anymore" because a DRA driver is not required to set
+       // `status.reservedFor` together with `status.allocation`, i.e. a claim
+       // that is "currently unused" should not get deallocated.
+       //
+       // This does not matter for claims that were created for a pod. For
+       // those, the resource claim controller will trigger deletion when the
+       // pod is done. However, it doesn't hurt to also trigger deallocation
+       // for such claims and not checking for them keeps this code simpler.
+       if len(oldClaim.Status.ReservedFor) > 0 &&
+               len(newClaim.Status.ReservedFor) == 0 &&
+               newClaim.Spec.AllocationMode == resource.AllocationModeWaitForFirstConsumer {
+               newClaim.Status.DeallocationRequested = true
+       }
+
        newClaim.Spec = oldClaim.Spec
 }
```

But that interfered with handling of a failed allocation attempts when a pod uses multiple claims because in contrast to what we do now (= let the kube-scheduler decide what to deallocate), the apiserver deallocated all claims when the kube-scheduler released the reservation for the in-flight pod.

#### Does this PR introduce a user-facing change?
```release-note
Dynamic resource allocation: when a claim uses "wait for first consumer" allocation (the default), then it will now get deallocated after it was used by a pod. That ensures that the next pod isn't affected by previous scheduling decision and that resources are not kept allocated unless really needed. If keeping a claim allocated is desired, use "immediate allocation".
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
- [KEP]: https://github.com/kubernetes/enhancements/issues/3063
```

### CODE REVIEW

File: pkg/controller/resourceclaim/controller.go [hunk 1]
```diff
@@ -456,6 +456,28 @@ func (ec *Controller) syncClaim(ctx context.Context, namespace, name string) err
...
+		// This has to be triggered by the transition from "was being used" to
+		// "is not used anymore" because a DRA driver is not required to set
+		// `status.reservedFor` together with `status.allocation`, i.e. a claim
+		// that is "currently unused" should not get deallocated.
+		//
+		// This does not matter for claims that were created for a pod. For
+		// those, the resource claim controller will trigger deletion when the
+		// pod is done. However, it doesn't hurt to also trigger deallocation
+		// for such claims and not checking for them keeps this code simpler.
+		if len(valid) == 0 &&
```
Comment (byako) [inline pkg/controller/resourceclaim/controller.go:476]: Can there be a situation when both `valid` and `claim.Status.ReservedFor` are empty, and the claim is still allocated? This check only happens in case there was a decrease of `ReservedFor`.

Comment (pohly) [reply pkg/controller/resourceclaim/controller.go:476]: Such a claim can exist, for example because a scheduling attempt didn't quite succeed. The current approach is to keep such claims allocated because the allocation might still be usable and let kube-scheduler explicitly trigger deallocation when it isn't.

**Review by byako — APPROVED** [review]
LGTM
