### PR TITLE
Fix resourcVersion = 0 in cacher

### LINKED ISSUE #13809: Regression: Watching without resourceVersion fails
At some point after kubernetes 1.0 watching without a resourceVersion has broken. This is a v1 API regression.

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #13809

cc @lavalamp @derekwaynecarr @smarterclayton @stefwalker

### CODE REVIEW

**Comment by liggitt** [comment]
Does this restore the previous behavior where you get modified events for all objects that exist when the watch was started?

**Comment by liggitt** [comment]
cc @stefwalter

**Comment by wojtek-t** [comment]
>
Does this restore the previous behavior where you get modified events for all objects that exist when the watch was started?

@lavalamp 
It doesn't (in fact I just noticed that it was the case before - btw it seems very misleading for me to have completely different behavior for resourceVersion = 0 and resourceVersion != 0).

But yeah... I will try to fix that.

**Comment by derekwaynecarr** [comment]
I spent more time debugging this to make sure I was not mistaken.

if I do the following direct to etcd on a running Kubernetes system:

```
curl '127.0.0.1:4001/v2/keys/registry?recursive=true&wait=true'
```

It waits until there was a node change event from Kubernetes, and only then returns the action for a Node update.  I do not get any other data in the system.  Meaning I do not get all the existing data.  

I think the change proposed here actually is consistent with the behavior that we used to have.

**Comment by wojtek-t** [comment]
@derekwaynecarr - I agree it's what etcd does (and I agree it's the most intuitive solution).
However, it's not what we had in v1.0 Kubernetes version (we had what @liggitt wrote above). So in my opinion we should restore it to the previous bahavior for backward compatibility. WDYT?

**Comment by derekwaynecarr** [comment]
@wojtek-t - I am testing what we actually had in 1.0 right now, will comment on original issue.

**Comment by smarterclayton** [comment]
We need to restore to the previous behavior - we can deprecate and remove
it for the v2 api if we can reach consensus for clients.  In the future,
the event history of an object could be very very long, so there are some
advantages to moving away from the list pattern.

On Mon, Sep 14, 2015 at 10:33 AM, Wojciech Tyczynski <
notifications@github.com> wrote:

> @derekwaynecarr <https://github.com/derekwaynecarr> - I agree it's what
> etcd does (and I agree it's the most intuitive solution).
> However, it's not what we had in v1.0 Kubernetes version (we had what
> @liggitt <https://github.com/liggitt> wrote above). So in my opinion we
> should restore it to the previous bahavior for backward compatibility. WDYT?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/13910#issuecomment-140099945>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by derekwaynecarr** [comment]
I tested on all the stuff in question as I was confused myself tracking etcd and kube versions.

see https://github.com/kubernetes/kubernetes/issues/13809#issuecomment-140107934

I think we need to special case resourceVersion=0 to internally kube does LIST and then WATCH from the last observed watch state to maintain consistency with 1.0 release.

**Comment by lavalamp** [comment]
Yeah, this is not the old behavior. IMO this behavior makes more sense, but since the point of this is to maintain compatibility, we should stick to the old behavior, which was list, send each item individually, then watch. With no way for user to tell where one ended and the other began.

**Comment by wojtek-t** [comment]
I agree - will fix that PR tomorrow.

**Comment by wojtek-t** [comment]
I've updated the PR to be compatible with what we have in v1.0.

PTAL

**Comment by stefwalter** [comment]
I can see items like this showing up from the watch now:

```
$ curl http://localhost:8080/api/v1/watch/nodes
{"type":"get","object":{"kind":"Node","apiVersion":"v1","metadata":{"name":"127.0.0.1","selfLink":"/api/v1/nodes/127.0.0.1","uid":"a3729acf-5b8f-11e5-86cb-10c37bdb8410","resourceVersion":"126","creationTimestamp":"2015-09-15T09:53:38Z","labels":{"kubernetes.io/hostname":"127.0.0.1"}},"spec":{"externalID":"127.0.0.1"},"status":{"capacity":{"cpu":"8","memory":"32817760Ki","pods":"40"},"conditions":[{"type":"Ready","status":"True","lastHeartbeatTime":"2015-09-15T09:58:09Z","lastTransitionTime":"2015-09-15T09:53:38Z","reason":"KubeletReady","message":"kubelet is posting ready status"}],"addresses":[{"type":"LegacyHostIP","address":"127.0.0.1"},{"type":"InternalIP","address":"127.0.0.1"}],"nodeInfo":{"machineID":"ef00b79be229463cbb844c3e715de96c\n\noxx","systemUUID":"60CAA732-DAD7-DD11-8C4C-10C37BDB8410","bootID":"cdfff127-3fe4-4b28-be19-8b344604dd0a","kernelVersion":"4.0.4-301.fc22.x86_64","osImage":"Fedora 22 (Twenty Two)","containerRuntimeVersion":"docker://1.7.1.fc22","kubeletVersion":"v1.1.0-alpha.1.722+0007794f68239f-dirty","kubeProxyVersion":"v1.1.0-alpha.1.722+0007794f68239f-dirty"}}}}
^C
```

I don't think "get" is a valid EventType. The docs say "the type of watch event; may be ADDED, MODIFIED, DELETED, or ERROR"

**Comment by wojtek-t** [comment]
Yes - I initially thought that it was the case before. Should be fixed now.

**Comment by stefwalter** [comment]
Works well now.

A tiny nit ... the previous behavior was to list the initial set of items with ```"MODIFIED"``` rather than ```"ADDED"```.

File: pkg/storage/watch_cache.go [hunk 1]
```diff
@@ -250,6 +250,20 @@ func (w *watchCache) GetAllEventsSinceThreadUnsafe(resourceVersion uint64) ([]wa
 	if size > 0 {
 		oldest = w.cache[w.startIndex%w.capacity].resourceVersion
 	}
+	if resourceVersion == 0 {
+		// resourceVersion = 0 means that we don't require any specific starting point
+		// and we would like to start watching from ~now.
+		// However, to keep backward compatibility, we additionally need to return the
+		// current state and only then start watching from that point.
+		//
+		// TODO: In v2 api, we should stop returning the current state
```
Comment (derekwaynecarr) [inline pkg/storage/watch_cache.go]: Open an issue to track change of WATCH behavior and and link to it here.

Reference the issue on the umbrella after https://github.com/kubernetes/kubernetes/issues/8190

File: pkg/storage/cacher_test.go [hunk 2]
```diff
@@ -302,6 +296,39 @@ func TestWatch(t *testing.T) {
 		}
 	}
 
+	// Now test watch from "now".
+	nowWatcher, err := cacher.Watch("pods/ns/foo", 0, storage.Everything)
```
Comment (derekwaynecarr) [inline pkg/storage/cacher_test.go]: I think we still need a test to test the too-old-error scenario when resourceVersion != 0

Is that covered elsewhere, it looked like previously we were using 0 as that test which is no longer valid.

Comment (wojtek-t) [inline pkg/storage/cacher_test.go]: Done.

File: pkg/storage/watch_cache.go (hunk 1 above)
Comment (wojtek-t) [inline pkg/storage/watch_cache.go]: Done.

**Comment by wojtek-t** [comment]
@derekwaynecarr - PTAL

**Comment by derekwaynecarr** [comment]
@k8s-bot test this

File: pkg/storage/watch_cache.go [hunk 3]
```diff
@@ -250,6 +250,20 @@ func (w *watchCache) GetAllEventsSinceThreadUnsafe(resourceVersion uint64) ([]wa
...
 		oldest = w.cache[w.startIndex%w.capacity].resourceVersion
 	}
+	if resourceVersion == 0 {
+		// resourceVersion = 0 means that we don't require any specific starting point
+		// and we would like to start watching from ~now.
+		// However, to keep backward compatibility, we additionally need to return the
+		// current state and only then start watching from that point.
+		//
+		// TODO: In v2 api, we should stop returning the current state - #13969.
+		allItems := w.store.List()
```
Comment (lavalamp) [inline pkg/storage/watch_cache.go]: Does this list go out to hit etcd? I guess it doesn't matter since this feature can't be used safely anyway, but if it doesn't go out to hit etcd there's no guarantee the combined state returned by the list would be a complete/correct one as of any particular resource version.

Comment (derekwaynecarr) [inline pkg/storage/watch_cache.go]: I believe that the List() will work against the current state in the backing cache.Store and not hit etcd.

Comment (smarterclayton) [inline pkg/storage/watch_cache.go]: Wait, why is this feature not safe?  The original implementation was safe -
we called etcd to do a list, then watched from the list timestamp.  How is
the new version less able to deliver safety?

On Tue, Sep 15, 2015 at 1:30 PM, Daniel Smith <notifications@github.com>
wrote:

> In pkg/storage/watch_cache.go
> <https://github.com/kubernetes/kubernetes/pull/13910#discussion_r39539558>
> :
>
> > @@ -250,6 +250,20 @@ func (w *watchCache) GetAllEventsSinceThreadUnsafe(resourceVersion uint64) ([]wa
> >  	if size > 0 {
> >  		oldest = w.cache[w.startIndex%w.capacity].resourceVersion
> >  	}
> > +	if resourceVersion == 0 {
> > +		// resourceVersion = 0 means that we don't require any specific starting point
> > +		// and we would like to start watching from ~now.
> > +		// However, to keep backward compatibility, we additionally need to return the
> > +		// current state and only then start watching from that point.
> > +		//
> > +		// TODO: In v2 api, we should stop returning the current state - #13969.
> > +		allItems := w.store.List()
>
> Does this list go out to hit etcd? I guess it doesn't matter since this
> feature can't be used safely anyway, but if it doesn't go out to hit etcd
> there's no guarantee the combined state returned by the list would be a
> complete/correct one as of any particular resource version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/pull/13910/files#r39539558>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

Comment (liggitt) [inline pkg/storage/watch_cache.go]: Right, I have the same question. I can tell @lavalamp doesn't like this method, but I haven't heard a concrete reason an internal list followed by watch is unsafe

Comment (derekwaynecarr) [inline pkg/storage/watch_cache.go]: I suspect he is referring to a potential race between the backing cache.Store and the watch cache.  So if the current items are enumerated from the cache.store, and a watch is initiated, its possible that in the time between that a change in etcd was missed.  I think to fix that you would need to know the resource version of the most recent item for when ```w.store.List()``` returned its value.

Comment (liggitt) [inline pkg/storage/watch_cache.go]: So before the watch cache was in place, it could have been safe (since we have a resourceVersion on the List we got from etcd)?

Comment (lavalamp) [inline pkg/storage/watch_cache.go]: I say it's not "safe" because at no point in time can the client be certain it has a complete or correct list. I get that for many uses this safety isn't important.

Comment (wojtek-t) [inline pkg/storage/watch_cache.go]: It is safe (due to how it is implemented).
Basically, the backing store contains a correct state at some point in time. The way it is implemented is that the cacher is locking watchCache, gets the state from that point in time (using list on the backing store) and starts watch from exactly that point. Every new watch event delivered to the backing store will be propagated to that watcher,
So there is no risk that some event will not be delivered.

Comment (wojtek-t) [inline pkg/storage/watch_cache.go]: <
I say it's not "safe" because at no point in time can the client be certain it has a complete or correct list. I get that for many uses this safety isn't important.

I don't understand it btw. It is guaranteed that this list is a correct list from some point in time (as long as we don't have multi-object transactions, which is true for now).

Comment (derekwaynecarr) [inline pkg/storage/watch_cache.go]: @wojtek-t  thank you for the clarification.

**Comment by derekwaynecarr** [comment]
LGTM

File: pkg/storage/watch_cache.go (hunk 3 above)
Comment (lavalamp) [inline pkg/storage/watch_cache.go]: Oh, I see! Yes, this sounds correct. In theory, etcd would provide the same
list at some resourceVersion. Thanks for explaining.

**Comment by wojtek-t** [comment]
@k8s-bot test this please
