### PR TITLE
pkg/kubelet: fix uint64 overflow when elapsed UsageCoreNanoSeconds exceeds 18446744073

### LINKED ISSUE #82195: CRI pod CPU metrics incorrect for pods with 20+ CPUs
**What happened**:
CRI CPU metrics are incorrect when using a large number of cores, due to a `uint64` overflow.

**What you expected to happen**:
CPU metrics should be correct for arbitrarily high numbers of cores.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a pod with 20 CPU units allocated, and fetch the CRI metrics. The metrics will be incorrect.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.4
- CRI: CRI-O

cc @paulnivin
cc @ashleykasim
/sig node
/sig scalability

### PR DESCRIPTION
**Pull request by paulnivin**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fixes a nanocore calculation overflow in the CRI stats provider when tens of CPUs are actively used by a container. The original calculation quickly exceeds MaxUint64 during the multiplication of the constant `uint64(time.Second/time.Nanosecond)` (1000000000). Moving the calculation to a float64 fixes the issue and maps to how nanocores are calculated elsewhere in kubernetes.

**Which issue(s) this PR fixes**:
Fixes #82195

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:
```docs
```

### CODE REVIEW

File: pkg/kubelet/stats/cri_stats_provider_test.go [hunk 1]
```diff
@@ -757,6 +757,7 @@ func makeFakeLogStats(seed int) *volume.Metrics {
 func TestGetContainerUsageNanoCores(t *testing.T) {
 	var value0 uint64
 	var value1 uint64 = 10000000000
+	var value2 uint64 = 188427786383
```
Comment (mattjmcnaughton) [inline pkg/kubelet/stats/cri_stats_provider_test.go]: Nit: Can you add a comment that `188446744073` is the limit for uint64 - I'm not sure how many devs would recognize that just based off the number?

**Review by mattjmcnaughton — APPROVED** [review]
Congrats on your first pr :)

/lgtm

Would love another pair of eyes from someone slightly more familiar with resource calculation.

**Comment by dashpole** [comment]
Good find!  This looks good after you address the outstanding comment above.

This should be cherry-picked to 1.15.
/priority important-soon

File: pkg/kubelet/stats/cri_stats_provider_test.go (hunk 1 above)
Comment (paulnivin) [reply pkg/kubelet/stats/cri_stats_provider_test.go]: This is just an arbitrarily large value that will trigger the overflow -- 100+ cores in use. The test fails without the included patch to the CRI stats provider. I'll add a comment.

Comment (vllry) [reply pkg/kubelet/stats/cri_stats_provider_test.go]: A comment would be good, but I would appretiate keeping the large number, as a generic safeguard against this class of bug.

Comment (paulnivin) [reply pkg/kubelet/stats/cri_stats_provider_test.go]: Left value as-is and added a comment.

**Comment by vllry** [comment]
This should also be cherry-picked to 1.14 after the merge thaw. If I understand correctly, this didn't exist prior to 1.14.

File: pkg/kubelet/stats/cri_stats_provider_test.go [hunk 2]
```diff
@@ -758,6 +758,9 @@ func TestGetContainerUsageNanoCores(t *testing.T) {
 	var value0 uint64
 	var value1 uint64 = 10000000000
 
+	// Test with a large container of 100+ CPUs
+	var value2 uint64 = 188427786383
```
Comment (odinuge) [inline pkg/kubelet/stats/cri_stats_provider_test.go]: Might be smart to run the assertions (as long as the ptrs are not null) with the values instead of the pointers, as test results like these don't make that much sense:

```
    cri_stats_provider_test.go:901:                                                                                                                                                                                                                                                                                                                        
                Error Trace:    cri_stats_provider_test.go:901                                                                                                                                                                                                                                                                                             
                Error:          Not equal:                                                                                                                                                                                                                                                                                                                 
                                expected: (*uint64)(0xc0001cc1d0)                                                                                                                                                                                                                                                                                          
                                actual  : (*uint64)(0xc0001cc520)    
```

This makes much more sense to me:
```
                                expected: 0x2bdf2bd88f                                                                                                                                                                                                                                                                                                     
                                actual  : 0x2bc5ac5800    
```

Out of scope of this PR tho.

**Review by odinuge — APPROVED** [review]
/lgtm

Nice work! I think using `float64` makes sense here. We _can_ swap the order of the calculation and keep uint64, but that will floor the intermediate results, and thus result in "wrong" values, so this approach is better.

ping @dashpole for approval. :smile:

**Comment by awprice** [comment]
@vllry I'm experiencing this in 1.13 with Kata containers. Manually applying this patch fixed CPU metrics for me.

**Comment by odinuge** [comment]
Hi @awprice 

This fix should be a part of the coming v1.16.1 release.

Since it looks like a problem that occurs for multiple people and the fix is relatively easy, I think this should be cherry-picked into the previous releases. Do you agree, and if so, can you do that @paulnivin?

The instructions on cherry-picking can be found here:
https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md

The list of the next patch-releases can be found here: https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md

**Comment by mattjmcnaughton** [comment]
On Thu, Oct 03, 2019 at 12:48:19AM -0700, Odin Ugedal wrote:
> Hi @awprice 
> 
> This fix should be a part of the coming v1.16.1 release.
> 
> Since it looks like a problem that occurs for multiple people and the fix is relatively easy, I think this should be cherry-picked into the previous releases. Do you agree, and if so, can you do that @paulnivin?
> 
> The instructions on cherry-picking can be found here:
> https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md
> 
> The list of the next patch-releases can be found here: https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md
> 
> -- 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/82300#issuecomment-537829442

+1 to a cherry-pick. However, I unfortunately think 1.13 is no longer supported
(double check me on this... it might have one more patch release), so the fixes
would only go to 1.14, 1.15, and 1.16.

**Comment by odinuge** [comment]
> I unfortunately think 1.13 is no longer supported
(double check me on this... it might have one more patch release)

Ref. https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md it looks like 1.13.12 will be the last patch release:

>1.13
>Next patch release is 1.13.12. This is expected to be the final release of the 1.13 branch.
> 
>Patch Release | Cherry-picks deadline | Target date
>-- | -- | --
>1.13.12 | 2019-10-11 | 2019-10-15

**Comment by mattjmcnaughton** [comment]
On Thu, Oct 03, 2019 at 09:21:54AM -0700, Odin Ugedal wrote:
> > I unfortunately think 1.13 is no longer supported
> (double check me on this... it might have one more patch release)
> 
> Ref. https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md it looks like 1.13.12 will be the last patch release:
> 
> >1.13
> >Next patch release is 1.13.12. This is expected to be the final release of the 1.13 branch.
> > 
> >Patch Release | Cherry-picks deadline | Target date
> >-- | -- | --
> >1.13.12 | 2019-10-11 | 2019-10-15
> 
> 
> 
> -- 
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/82300#issuecomment-538017960

Oh excellent!

**Comment by paulnivin** [comment]
> Since it looks like a problem that occurs for multiple people and the fix is relatively easy, I think this should be cherry-picked into the previous releases. Do you agree, and if so, can you do that @paulnivin?

While this fix is simple and straightforward, there are other parts of the CRI stats pipeline which depended on this overflow existing. https://github.com/kubernetes/kubernetes/pull/83504 and https://github.com/kubernetes/kubernetes/pull/83507 are needed in order to reliably use HPAs with with the CRI stats provider.
