### PR TITLE
kubeadm: Fix omitempty in v1beta2

### LINKED ISSUE #1358: Not possible to represent absence of Taints when marshalling kubeadm configuration
## Versions

kubeadm API v1alpha3 and v1beta1 (releases 1.11, 1.12, 1.13)

## What happened?
I wanted to use a Go program to generate kubeadm configuration, such that _no taints_ are applied to the node. I imported the kubeadm types, initialized an `InitConfiguration` struct, and set `NodeRegistration.Taints` to an empty slice. I then marshalled the struct YAML and wrote this to a configuration file. I observed that `NodeRegistration.Taints` was not present in the file. When I passed the configuration file to `kubeadm init`, I observed that kubeadm applied the default set of taints to the node.

## What you expected to happen?
The [Taints field is explained in the code as follows](https://github.com/kubernetes/kubernetes/blob/release-1.13/cmd/kubeadm/app/apis/kubeadm/v1beta1/types.go#L208):
> Taints specifies the taints the Node API object should be registered with. If this field is unset, i.e. nil, in the `kubeadm init` process it will be defaulted to []v1.Taint{'node-role.kubernetes.io/master=""'}. If you don't want to taint your master node, set this field to an empty slice, i.e. `taints: {}` in the YAML file. This field is solely used for Node registration.

I want to use the kubeadm types in a Go program and set the `Taints` field to an empty slice. However, when I marshal the struct, the field is omitted (because it is tagged `omitempty`).

## How to reproduce it (as minimally and precisely as possible)?
Here is a Go program that generates `InitConfiguration` with `NodeRegistration.Taints` set to an empty slice, then marshals the configuration to YAML, then unmarshals it into a fresh `InitConfiguration` struct.. Note that, in the fresh configuration struct, `NodeRegistration.Taints` is nil, _not_ an empty slice.

```
package main

import (
	"fmt"
	"log"

	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	kubeadm "k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1"
	"sigs.k8s.io/yaml"
)

func main() {
	// Create an InitConfiguration that sets taints to an empty slice
	srcConfig := kubeadm.InitConfiguration{
		TypeMeta: metav1.TypeMeta{
			Kind:       "InitConfiguration",
			APIVersion: "kubeadm.k8s.io/v1beta1",
		},
		NodeRegistration: kubeadm.NodeRegistrationOptions{
			// empty slice means no taints should be applied
			Taints: []v1.Taint{},
		},
	}
	b, err := yaml.Marshal(srcConfig)
	if err != nil {
		log.Fatal(err)
	}

	dstConfig := kubeadm.InitConfiguration{}
	err = yaml.Unmarshal(b, dstConfig)
	if err != nil {
		log.Fatal(err)
	}
	// Taints is not an empty slice
	fmt.Println(dstConfig.NodeRegistration.Taints == nil)
}

```
Output:
```
true
```

### PR DESCRIPTION
**Pull request by rosti**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

There are a couple of problems with regards to the `omitempty` in v1beta1:

- It is not applied to certain fields. This makes emitting YAML configuration files in v1beta1 config format verbose by both kubeadm and third party Go lang tools. Certain fields, that were never given an explicit value would show up in the marshalled YAML document. This can cause confusion and even misconfiguration.

- It can be used in inappropriate places. In this case it's used for fields, that need to be always serialized. The only one such field at the moment is `NodeRegistrationOptions.Taints`. If the `Taints` field is nil, then it's defaulted to a slice containing a single control plane node taint. If it's an empty slice, no taints are applied, thus, the cluster behaves differently. With that in mind, a Go program, that uses v1beta1 with `omitempty` on the `Taints` field has no way to specify an explicit empty slice of taints, as this would get lost after marshalling to YAML.

To fix these issues the following is done in this change:

- A whole bunch of additional omitemptys are placed at many fields in v1beta2.
- `omitempty` is removed from `NodeRegistrationOptions.Taints`
- A test, that verifies the ability to specify empty slice value for `Taints` is included.

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#1358
Refs kubernetes/enhancements#970 kubernetes/kubeadm#1439

**Special notes for your reviewer**:
/cc @kubernetes/sig-cluster-lifecycle-pr-reviews
/area kubeadm
/priority important-soon
/assign @fabriziopandini
/assign @timothysc
/assign @neolit123
/cc @dlipovetsky 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
thanks @rosti 
the diff LGTM.

**Review by dixudx — APPROVED** [review]
/lgtm

File: cmd/kubeadm/app/apis/kubeadm/v1beta2/types.go [hunk 1]
```diff
@@ -205,7 +205,7 @@ type NodeRegistrationOptions struct {
 	// Taints specifies the taints the Node API object should be registered with. If this field is unset, i.e. nil, in the `kubeadm init` process
 	// it will be defaulted to []v1.Taint{'node-role.kubernetes.io/master=""'}. If you don't want to taint your control-plane node, set this field to an
 	// empty slice, i.e. `taints: {}` in the YAML file. This field is solely used for Node registration.
-	Taints []v1.Taint `json:"taints,omitempty"`
+	Taints []v1.Taint `json:"taints"`
```
Comment (luxas) [inline cmd/kubeadm/app/apis/kubeadm/v1beta2/types.go]: why remove omitempty here?

**Review by luxas — COMMENTED** [review]
One unexpected change

**Comment by luxas** [comment]
Otherwise LGTM :+1:

File: cmd/kubeadm/app/apis/kubeadm/v1beta2/types.go (hunk 1 above)
Comment (dlipovetsky) [reply cmd/kubeadm/app/apis/kubeadm/v1beta2/types.go]: @luxas I think you may have missed the explanation in the PR description above. Here's an excerpt:

> It can be used in inappropriate places. In this case it's used for fields, that need to be always serialized. The only one such field at the moment is NodeRegistrationOptions.Taints. If the Taints field is nil, then it's defaulted to a slice containing a single control plane node taint. If it's an empty slice, no taints are applied, thus, the cluster behaves differently. With that in mind, a Go program, that uses v1beta1 with omitempty on the Taints field has no way to specify an explicit empty slice of taints, as this would get lost after marshalling to YAML.

Comment (luxas) [reply cmd/kubeadm/app/apis/kubeadm/v1beta2/types.go]: ah, ok, yeah I missed that :+1:
