### PR TITLE
Prevent panic in replica_set e2e

### LINKED ISSUE #22070: replica_set test panics.
*This might be fixed, haven't reproduced on latest upstream source. But in any case, I thought I'd create the issue.*

bug = **i assume any failure in e2es shouldnt be b/c of a panic.** ... I noticed a failure on Openshift today, which I think alludes to a possible issue in replica sets.

```
•! Panic [691.609 seconds]                                                                                                                                                                        [14/1963]
ReplicaSet
/home/fedora/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/replica_set.go:47
  should serve a basic image on each replica with a public image [Conformance] [It]
  /home/fedora/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/replica_set.go:39

  Test Panicked
  runtime error: invalid memory address or nil pointer dereference
  /usr/lib/golang/src/runtime/panic.go:423

  Full Stack Trace
  /home/fedora/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/replica_set.go:102 (0x69989d)
  /home/fedora/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/replica_set.go:38 (0x7adcaa)
  /home/fedora/gopath/src/github.com/openshift/origin/test/extended/util/test.go:105 (0x590cc7)
  /home/fedora/gopath/src/github.com/openshift/origin/test/extended/extended_test.go:24 (0x48a2e6)
  /usr/lib/golang/src/testing/testing.go:456 (0x484138)
  /usr/lib/golang/src/runtime/asm_amd64.s:1721 (0x4603f1)
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSGINKGO FIE{ReplicationController should serve a basic image on each replica with a public image [Conformance] [ReplicationController should serve a 
basic image on each replica with a public image [Conformance]] should serve a basic image on each replica with a public image [Conformance] false /home/fedora/gopath/src/github.com/openshift/origin/Godep
s/_workspace/src/k8s.io/kubernetes/test/e2e/rc.go 38 false}file has kubernetes/test/e2e in it
------------------------------
• [SLOW TEST:24.192 seconds]
ReplicationController
/home/fedora/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/rc.go:46
  should serve a basic image on each replica with a public image [Conformance]
  /home/fedora/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/test/e2e/rc.go:38
```

### PR DESCRIPTION
**Pull request by jayunit100**
should fix #22070

### CODE REVIEW

File: test/e2e/replica_set.go [hunk 1]
```diff
@@ -94,6 +94,9 @@ func ReplicaSetServeImageOrFail(f *Framework, test string, image string) {
 	label := labels.SelectorFromSet(labels.Set(map[string]string{"name": name}))
 
 	pods, err := podsCreated(f.Client, f.Namespace.Name, name, replicas)
+	if pods == nil || err != nil {
```
Comment (ihmccreery) [inline test/e2e/replica_set.go]: I'd just check `err != nil` here; I think you can safely assume that if there's no error, `pods` isn't nil, and if it is, that should be fixed in `podsCreated` or properly handled separately.

**Comment by jayunit100** [comment]
@ihmccreery how bout just an `expect`, then ...  That should be easy.  
This needs to be done in a few other places to ill try to craft a follow on PR thats a little broader

**Comment by bgrant0607** [comment]
LGTM
