### PR TITLE
clustertrustbundles: extend alpha for 2 more releases

### LINKED ISSUE #128607: [Failing Test] gce-cos-master-alpha-features - kubetest.Test
### Which jobs are failing?

* sig-release-master-blocking
* gce-cos-master-alpha-features

### Which tests are failing?

* [kubetest.Test](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1854110207110549504)

### Since when has it been failing?

* First flaky: Tue, 22 Oct 2024 08:14:43 -03
* Latest flaky: Wed, 06 Nov 2024 07:34:56 -03

### Testgrid link

* [https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features&exclude-non-failed-tests=](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features&exclude-non-failed-tests=)
* [https://storage.googleapis.com/k8s-triage/index.html?test=kubetest.Test](https://storage.googleapis.com/k8s-triage/index.html?test=kubetest.Test)

### Reason for failure (if possible)

```
	F 2024-11-06 07:34:56 -0300 -03 error during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Feature:(AdmissionW...=8 --report-dir=/logs/artifacts --disable-log-dump=true: exit status 1
	F 2024-11-06 07:04:56 -0300 -03 error during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Feature:(AdmissionW...=8 --report-dir=/logs/artifacts --disable-log-dump=true: exit status 1
	F 2024-11-06 05:28:56 -0300 -03 error during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Feature:(AdmissionW...=8 --report-dir=/logs/artifacts --disable-log-dump=true: exit status 1
	F 2024-10-22 16:15:43 -0300 -03 error during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Feature:(AdmissionW...=8 --report-dir=/logs/artifacts --disable-log-dump=true: exit status 1
	F 2024-10-22 14:15:43 -0300 -03 error during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Feature:(AdmissionW...=8 --report-dir=/logs/artifacts --disable-log-dump=true: exit status 1
	F 2024-10-22 12:15:46 -0300 -03 error during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Feature:(AdmissionW...=8 --report-dir=/logs/artifacts --disable-log-dump=true: exit status 1
	F 2024-10-22 10:14:43 -0300 -03 error during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Feature:(AdmissionW...=8 --report-dir=/logs/artifacts --disable-log-dump=true: exit status 1

```

### Relevant SIG(s)

/sig cloud-provider
cc @kubernetes/release-team-release-signal

### LINKED ISSUE #128656: pull-kubernetes-e2e-gce-cos-alpha-features: [sig-auth] [Feature:ClusterTrustBundle] [Feature:ClusterTrustBundleProjection]
### Which jobs are failing?

pull-kubernetes-e2e-gce-cos-alpha-features

### Which tests are failing?

[sig-auth] [Feature:ClusterTrustBundle] [Feature:ClusterTrustBundleProjection] *

See https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/128170/pull-kubernetes-e2e-gce-cos-alpha-features/1854429746889232384

### Since when has it been failing?

The oldest failing is Nov 06 16:08:00, no successful afterwards.

https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/128374/pull-kubernetes-e2e-gce-cos-alpha-features/1854057730449346560

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-gce-cos-alpha-features

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig

### PR DESCRIPTION
**Pull request by stlaz**
#### What type of PR is this?

/kind failing-test
/kind api-change

#### Which issue(s) this PR fixes:

Fixes #128656

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by aojea** [comment]
can you please explain how this fixes the test? just for my own education, the API server didn't have the corresponding API version?

**Comment by stlaz** [comment]
It looks like the kube-apiserver might be dropping APIs that are deprecated for 1.32, which would be the case of the ClusterTrustBundles. Moving the API 2 versions would then cause the apiserver to keep it.

Note that the original test failure was about multiple creations of a resource of the same name, meaning the API was in fact present. A move to running the tests as serial wouldn't cause the API to disappear, so something else must've happened.

I started a thread on Slack at [#sig-apimachinery](https://kubernetes.slack.com/archives/C0EG7JC6T/p1730975738928759) to confirm, there's also [another thread](https://kubernetes.slack.com/archives/C0EG7JC6T/p1730965005279489) that seems relevant.

**Comment by aojea** [comment]
Thanks, appreciate you adding this information to the PR so we can track this things

File: test/integration/clustertrustbundles/field_selector_test.go [hunk 1]
```diff
@@ -31,10 +31,6 @@ import (
 )
 
 func TestCTBSignerNameFieldSelector(t *testing.T) {
-	// KUBE_APISERVER_SERVE_REMOVED_APIS_FOR_ONE_RELEASE allows for APIs pending removal to not block tests
-	// TODO: Remove this line once certificates v1alpha1 types to be removed in 1.32 are fully removed
```
Comment (Jefftree) [inline test/integration/clustertrustbundles/field_selector_test.go:35]: cc @aaron-prindle @liggitt: We're extending the lifecycle of this API rather than removing it. Is this fine?

File: test/integration/clustertrustbundles/signer_name_change_forbidden_test.go [hunk 2]
```diff
@@ -32,10 +32,6 @@ import (
 )
 
 func TestCTBSignerNameChangeForbidden(t *testing.T) {
-	// KUBE_APISERVER_SERVE_REMOVED_APIS_FOR_ONE_RELEASE allows for APIs pending removal to not block tests
-	// TODO: Remove this line once certificates v1alpha1 types to be removed in 1.32 are fully removed
-	t.Setenv("KUBE_APISERVER_SERVE_REMOVED_APIS_FOR_ONE_RELEASE", "true")
```
Comment (liggitt) [inline test/integration/clustertrustbundles/signer_name_change_forbidden_test.go:37]: keep this in place until we actually remove the alpha serving code

File: test/integration/clustertrustbundles/admission_establishtrust_test.go [hunk 3]
```diff
@@ -37,9 +37,6 @@ import (
 // Verifies that the ClusterTrustBundle attest admission plugin correctly
 // enforces that a user has "attest" on the affected signer name.
 func TestCTBAttestPlugin(t *testing.T) {
-	// KUBE_APISERVER_SERVE_REMOVED_APIS_FOR_ONE_RELEASE allows for APIs pending removal to not block tests
-	// TODO: Remove this line once certificates v1alpha1 types to be removed in 1.32 are fully removed
-	t.Setenv("KUBE_APISERVER_SERVE_REMOVED_APIS_FOR_ONE_RELEASE", "true")
```
Comment (liggitt) [inline test/integration/clustertrustbundles/admission_establishtrust_test.go:42]: keep this in place until we actually remove the alpha serving code

**Comment by liggitt** [comment]
it's fine to extend the lifetime a bit as a stop-gap, keep the test constants in place

File: staging/src/k8s.io/api/certificates/v1alpha1/types.go [hunk 4]
```diff
@@ -23,6 +23,7 @@ import (
 // +genclient
 // +genclient:nonNamespaced
 // +k8s:prerelease-lifecycle-gen:introduced=1.26
+// +k8s:prerelease-lifecycle-gen:deprecated=1.34
```
Comment (Jefftree) [inline staging/src/k8s.io/api/certificates/v1alpha1/types.go:26]: This will bump the removal to v1.37. If we anticipate removing it sooner, would recommend decreasing this number.

Comment (liggitt) [reply staging/src/k8s.io/api/certificates/v1alpha1/types.go:26]: can do that as a follow-up... alphas can be removed in a single release with no notice if needed by policy
