### PR TITLE
test: wait for complete rollouts in WaitForDeploymentStatusValid

### LINKED ISSUE #34816: [k8s.io] Deployment scaled rollout deployment should not block on annotation check {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/32663/kubernetes-pull-build-test-gci-e2e-gce/2370/

Failed: [k8s.io] Deployment scaled rollout deployment should not block on annotation check {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:94
Expected error:
    <*errors.errorString | 0xc820ebadb0>: {
        s: "Observed 17 available replicas, less than min required 18",
    }
    Observed 17 available replicas, less than min required 18
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:1187
```

Happened on a presubmit run in #32663.

Previous issues for this test: #30100 #31810 #34331 #34717

### PR DESCRIPTION
**Pull request by 0xmichalis**
@kubernetes/deployment should fix https://github.com/kubernetes/kubernetes/issues/34816 once and forever

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/34942)

### CODE REVIEW

File: test/e2e/framework/util.go [hunk 1]
```diff
@@ -2896,7 +2896,18 @@ func WaitForDeploymentStatusValid(c clientset.Interface, d *extensions.Deploymen
 			Logf(reason)
 			return false, nil
 		}
-		return true, nil
+
+		// When the deployment status and its underlying resources reach the desired state, we're done
+		if deployment.Status.Replicas == deployment.Spec.Replicas &&
```
Comment (mfojtik) [inline test/e2e/framework/util.go]: i thought we have helper method for this

File: test/e2e/framework/util.go [hunk 2]
```diff
@@ -2896,7 +2896,18 @@ func WaitForDeploymentStatusValid(c clientset.Interface, d *extensions.Deploymen
...
+			deployment.Status.UpdatedReplicas == deployment.Spec.Replicas &&
+			deployment.Status.AvailableReplicas == deployment.Spec.Replicas {
+			return true, nil
+		}
+
+		reason = fmt.Sprintf("deployment status: %#v", deployment.Status)
```
Comment (mfojtik) [inline test/e2e/framework/util.go]: you don't need this var, just Logf

**Review by mfojtik — CHANGES_REQUESTED** [review]

File: test/e2e/framework/util.go (hunk 2 above)
Comment (kargakis) [inline test/e2e/framework/util.go]: I need it in case we timeout. Will be printed instead of "timed out waiting for the condition".

File: test/e2e/framework/util.go (hunk 1 above)
Comment (kargakis) [inline test/e2e/framework/util.go]: It's somewhere in the perma-failed PR i think:) I will refactor this once I get the API merged (so the impl will get its turn)

**Comment by mfojtik** [comment]
LGTM
