### PR TITLE
Fix issue with client rate limiter when polling

### LINKED ISSUE #121860: [sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling
### Which jobs are failing?

https://testgrid.k8s.io/sig-autoscaling-hpa#gce-cos-autoscaling-hpa-cpu
https://testgrid.k8s.io/sig-windows-master-release#capz-windows-containerd-master-serial-slow-hpa

### Which tests are failing?

Kubernetes e2e suite.[It] [sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) [Serial] [Slow] ReplicaSet with idle sidecar (ContainerResource use case) Should not scale up on a busy sidecar with an idle application [sig-autoscaling, Feature:HPA, Serial, Slow][Changes](https://github.com/kubernetes-sigs/cluster-api-provider-azure/compare/16170b72f...8a09a4233?)

Kubernetes e2e suite.[It] [sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) [Serial] [Slow] ReplicationController Should scale from 1 pod to 3 pods and then from 3 pods to 5 pods and verify decision stability [sig-autoscaling, Feature:HPA, Serial, Slow]

Kubernetes e2e suite.[It] [sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) [Serial] [Slow] ReplicationController Should scale from 5 pods to 3 pods and then from 3 pods to 1 pod and verify decision stability [sig-autoscaling, Feature:HPA, Serial, Slow]

Kubernetes e2e suite.[It] [sig-autoscaling] [Feature:HPA] [Serial] [Slow] Horizontal pod autoscaling (non-default behavior) with autoscaling disabled shouldn't scale down [sig-autoscaling, Feature:HPA, Serial, Slow]

Kubernetes e2e suite.[It] [sig-autoscaling] [Feature:HPA] [Serial] [Slow] Horizontal pod autoscaling (non-default behavior) with autoscaling disabled shouldn't scale up [sig-autoscaling, Feature:HPA, Serial, Slow]

Kubernetes e2e suite.[It] [sig-autoscaling] [Feature:HPA] [Serial] [Slow] Horizontal pod autoscaling (non-default behavior) with both scale up and down controls configured should keep recommendation within the range with stabilization window and pod limit rate [sig-autoscaling, Feature:HPA, Serial, Slow]

Kubernetes e2e suite.[It] [sig-autoscaling] [Feature:HPA] [Serial] [Slow] Horizontal pod autoscaling (non-default behavior) with both scale up and down controls configured should keep recommendation within the range over two stabilization windows [sig-autoscaling, Feature:HPA, Serial, Slow]

### Since when has it been failing?

11/3/2023

### Testgrid link

https://testgrid.k8s.io/sig-autoscaling-hpa#gce-cos-autoscaling-hpa-cpu

### Reason for failure (if possible)

  <*fmt.wrapError | 0xc000812080>: 
    client rate limiter Wait returned an error: context deadline exceeded
    {
        msg: "client rate limiter Wait returned an error: context deadline exceeded",
        err: <context.deadlineExceededError>{},
    }

### Anything else we need to know?

looks similiar to https://github.com/kubernetes/kubernetes/pull/121583/files

### Relevant SIG(s)

/sig autoscaling
/sig windows

### PR DESCRIPTION
**Pull request by jsturtevant**
#### What type of PR is this?
/kind failing-test

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/121860

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

/sig windows
/sig autoscaling

### CODE REVIEW

File: test/e2e/framework/autoscaling/autoscaling_utils.go [hunk 1]
```diff
@@ -506,7 +507,7 @@ func (rc *ResourceConsumer) WaitForReplicas(ctx context.Context, desiredReplicas
 // EnsureDesiredReplicasInRange ensure the replicas is in a desired range
 func (rc *ResourceConsumer) EnsureDesiredReplicasInRange(ctx context.Context, minDesiredReplicas, maxDesiredReplicas int, duration time.Duration, hpaName string) {
 	interval := 10 * time.Second
-	err := wait.PollUntilContextTimeout(ctx, interval, duration, true, func(ctx context.Context) (bool, error) {
+	gomega.Consistently(ctx, framework.HandleRetry(func(ctx context.Context) (bool, error) {
```
Comment (aojea) [inline test/e2e/framework/autoscaling/autoscaling_utils.go:510]: I´m not sure if this is dealing with the specific error from the bug you linked , @pohly knows better these functions

Comment (jsturtevant) [reply test/e2e/framework/autoscaling/autoscaling_utils.go:510]: followed https://github.com/kubernetes/kubernetes/pull/121583 as an example, which was fixing a similar error message. I wasn't sure I needed the `HandleRetry` here though

**Comment by jsturtevant** [comment]
`pull-kubernetes-e2e-autoscaling-hpa-cpu` is passing which was previously failing with the errors reported in CI

File: test/e2e/framework/autoscaling/autoscaling_utils.go [hunk 2]
```diff
@@ -520,15 +521,9 @@ func (rc *ResourceConsumer) EnsureDesiredReplicasInRange(ctx context.Context, mi
...
+			return true, nil // Expected number of replicas found. Continue polling until timeout.
 		}
-	})
-	// The call above always returns an error, but if it is timeout, it's OK (condition satisfied all the time).
-	if wait.Interrupted(err) {
-		framework.Logf("Number of replicas was stable over %v", duration)
-		return
-	}
-	framework.ExpectNoErrorWithOffset(1, err)
+	})).WithTimeout(duration).WithPolling(interval).Should(gomega.BeTrue())
```
Comment (pohly) [inline test/e2e/framework/autoscaling/autoscaling_utils.go:526]: When using `gomega.Consistently`, you are making a statement about some observable fact. The callback should only deliver that fact, the statement then should be (no pun intended) in the `Should`. That way you get all the advantages listed in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/writing-good-e2e-tests.md#polling-and-timeouts.

What that means here is:
- don't log inside the callback
- return a struct that contains the information that needs to be logged in case of a failure
- check that the state in that struct passes with a matcher; a custom matcher might be the easiest, but you can also compose one (`gomega.HaveField + gomega.BeNumerically`)

You also need to check error handling. Does `rc.GetReplicas` fail on errors? It would be better to return an error and let `Consistently` and `HandleRetry` deal with it.

Regarding `EnsureDesiredReplicasInRange`: that's inside a helper package. When it fails, we want to see where in the test it was used, not a failure inside the helper. See "The E2E framework therefore uses a different approach" in linked section.

Comment (jsturtevant) [reply test/e2e/framework/autoscaling/autoscaling_utils.go:526]: > You also need to check error handling. Does `rc.GetReplicas` fail on errors? It would be better to return an error and let `Consistently` and `HandleRetry` deal with it.

It doesn't look like it does.  It fails hard with in its helper function after making the API call. If I understand correctly that isn't following the pattern suggested here iether. 
 https://github.com/kubernetes/kubernetes/blob/1bb2773153d5d7395d445feb23171ad8b84afb13/test/e2e/framework/autoscaling/autoscaling_utils.go#L444-L452

Cleaning that up seems like a larger refactor, Is this something that can be a follow up? I am warry of making large changes before code freeze but would like to see these tests passing.

Comment (pohly) [reply test/e2e/framework/autoscaling/autoscaling_utils.go:526]: I'm okay with fixing this in a follow-up. But please create an issue and link to it in the code.

File: test/e2e/framework/autoscaling/autoscaling_utils.go (hunk 1 above)
Comment (jsturtevant) [reply test/e2e/framework/autoscaling/autoscaling_utils.go:510]: tracking feedback in https://github.com/kubernetes/kubernetes/pull/121861/files#r1392089576

File: test/e2e/framework/autoscaling/autoscaling_utils.go (hunk 2 above)
Comment (jsturtevant) [reply test/e2e/framework/autoscaling/autoscaling_utils.go]: I've updated based on your feedback (great docs btw).  I am not sure if the changes are what you had in mind but I think it is a bit closer to the approach suggested

File: test/e2e/framework/autoscaling/autoscaling_utils.go [hunk 3]
```diff
@@ -506,29 +507,16 @@ func (rc *ResourceConsumer) WaitForReplicas(ctx context.Context, desiredReplicas
...
-			return false, nil // Expected number of replicas found. Continue polling until timeout.
-		}
-	})
-	// The call above always returns an error, but if it is timeout, it's OK (condition satisfied all the time).
-	if wait.Interrupted(err) {
-		framework.Logf("Number of replicas was stable over %v", duration)
-		return
+	framework.Gomega().Consistently(ctx, func(ctx context.Context) int {
+		return rc.GetReplicas(ctx)
+	}).WithTimeout(duration).WithPolling(interval).Should(gomega.And(gomega.BeNumerically(">=", minDesiredReplicas), gomega.BeNumerically("<=", maxDesiredReplicas)))
```
Comment (pohly) [inline test/e2e/framework/autoscaling/autoscaling_utils.go:512]: This returns an error that would need to returned by `EnsureDesiredReplicasInRange`. As you are not doing that yet, capture it in `err` and check it below.

File: test/e2e/framework/autoscaling/autoscaling_utils.go [hunk 4]
```diff
@@ -506,29 +507,16 @@ func (rc *ResourceConsumer) WaitForReplicas(ctx context.Context, desiredReplicas
...
+
+	as, err := rc.GetHpa(ctx, hpaName)
+	if err != nil {
+		framework.Logf("Error getting HPA: %s", err)
+	} else {
+		framework.Logf("HPA status: %+v", as.Status)
```
Comment (pohly) [inline test/e2e/framework/autoscaling/autoscaling_utils.go:518]: The purpose of these log messages apparently was to have this information available in case of a test failure.

What I had in mind was something like this:
```
type state struct {
    replicas int
    as ...
}

framework.Gomega().Consistently(ctx, func(ctx context.Context) result {
...
})....Should(gomega.HaveField("replicas", omega.And(gomega.BeNumerically(">=", minDesiredReplicas), gomega.BeNumerically("<=", maxDesiredReplicas))))
```

Then when it fails, gomega dumps the entire state as part of the failure message. But the usability of that failure would have to be tested.

For now, keep this is as-is and add a `framework.ExpectNoError(err)` after it to check the result of `Consistently`.

**Review by pohly — CHANGES_REQUESTED** [review]

File: test/e2e/framework/autoscaling/autoscaling_utils.go (hunk 2 above)
Comment (jsturtevant) [reply test/e2e/framework/autoscaling/autoscaling_utils.go]: https://github.com/kubernetes/kubernetes/issues/121892

File: test/e2e/framework/autoscaling/autoscaling_utils.go (hunk 4 above)
Comment (jsturtevant) [reply test/e2e/framework/autoscaling/autoscaling_utils.go:519]: I put this at the end of the test so that we can dump the HPA Status

File: test/e2e/framework/autoscaling/autoscaling_utils.go (hunk 3 above)
Comment (jsturtevant) [reply test/e2e/framework/autoscaling/autoscaling_utils.go:512]: updated

**Comment by jsturtevant** [comment]
the tests passed but the log dump failed.

/retest

File: test/e2e/framework/autoscaling/autoscaling_utils.go (hunk 2 above)
Comment (carlory) [reply test/e2e/framework/autoscaling/autoscaling_utils.go]:
```go
// GetObject takes a get function like clientset.CoreV1().Pods(ns).Get
// and the parameters for it and returns a function that executes that get
// operation in a [gomega.Eventually] or [gomega.Consistently].
//
// Delays and retries are handled by [HandleRetry]. A "not found" error is
// a fatal error that causes polling to stop immediately. If that is not
// desired, then wrap the result with [IgnoreNotFound].
func GetObject[T any](get APIGetFunc[T], name string, getOptions metav1.GetOptions) GetFunc[T] {
	return HandleRetry(func(ctx context.Context) (T, error) {
		return get(ctx, name, getOptions)
	})
}
```

@pohly @jsturtevant How about this? It just need do some small changes in GetReplicas func.

```go
// GetReplicas get the replicas
func (rc *ResourceConsumer) GetReplicas(ctx context.Context) int {
	switch rc.kind {
	case KindRC:
		replicationController, err := framework.GetObject(rc.clientSet.CoreV1().ReplicationControllers(rc.nsName).Get, rc.name, metav1.GetOptions{})(ctx)
		framework.ExpectNoError(err)
		if replicationController == nil {
			framework.Failf(rcIsNil)
		}
		return int(replicationController.Status.ReadyReplicas)
```

File: test/e2e/framework/autoscaling/autoscaling_utils.go (hunk 4 above)
Comment (pohly) [reply test/e2e/framework/autoscaling/autoscaling_utils.go:519]: Right, that was the idea.

**Review by pohly — APPROVED** [review]
/lgtm
/approve

/assign @aojea 

For milestone.

This could be improved further, as discussed in this PR. I assume that @jsturtevant will remember that in a personal TODO list and might come back to it when there's no test freeze looming. We don't need to record such a TODO here or in an issue because it could also remain as-is.

**Comment by aojea** [comment]
We passed test freeze, does this qualify to merge at this stage?
@kubernetes/release-managers @liggitt do you know?

**Comment by xmudrii** [comment]
Pinging @kubernetes/release-team-leads as they're responsible for code/test freeze exceptions

**Comment by pohly** [comment]
I hadn't realized that @jsturtevant had already set the milestone. That probably should have been done last, right? Where can I read up on managing milestones?

**Comment by xmudrii** [comment]
@pohly That's kind of correct. However, the milestone can be set only after Release Team Leads approve an exception for the PR to get merged. I'm not sure if we have this somewhere else documented, but this document has some basic information about the process (it's more oriented towards SIG Release members though): https://github.com/kubernetes/sig-release/blob/master/releases/release_phases.md

**Comment by liggitt** [comment]
> We passed test freeze, does this qualify to merge at this stage? @kubernetes/release-managers @liggitt do you know?

I don't have context on the issue this is fixing, but in general, test-only fixes for flakes and failing tests that improve signal for release, whether in release-blocking or release-informing jobs, are ~always acceptable.

The test freeze deadline is more about expanding test coverage, or adding new tests, if I understand correctly.

**Comment by pohly** [comment]
I moved the discussion to https://kubernetes.slack.com/archives/C2C40FMNF/p1700057962137919 because it's more about the process and less about this particular PR.

**Comment by jsturtevant** [comment]
> This could be improved further, as discussed in this PR. I assume that @jsturtevant will remember that in a personal TODO list and might come back to it when there's no test freeze looming. We don't need to record such a TODO here or in an issue because it could also remain as-is.

@pohly I did create a follow up issue https://github.com/kubernetes/kubernetes/issues/121892.  Look like @carlory  would like to pick it up
