### PR TITLE
[FG:InPlacePodVerticalScaling] bug(quota): handle resources changed on resource quota filter

### LINKED ISSUE #127132: [FG:InPlacePodVerticalScaling] ResourceQuota unresponsive to scale-down
/kind bug

**TL;DR:**

If a pod's requests are scaled down with InPlacePodVerticalScaling, it can take a long time (up to 5 minutes by default) for resource quota to free the resources. If the pod is scaled back up in that window, the difference will be double-counted.

**Explanation:**

If a pod is resized, the resource quota admission controller relies on the [resource helper `resource.PodRequests`](https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/resource/helpers.go#L50) to determine the total request size. That function uses the maximum of the resource request (`.spec.containers[*].resources.requests`) and the allocated resources (`.status.containerStatuses[*].allocatedResources`).

In the event of scaling down, the allocated resource value will be larger, and therefore the value that is used to set the resource quota. This is working as intended, but the ResourceQuota controller should pick up the scale down once the Kubelet updates the allocated resources.

The resource quota's default filter function needs to be updated to consider updates to allocated resources:
https://github.com/kubernetes/kubernetes/blob/48d6d55a47ca8202692098639f7b3c76f107f46a/pkg/quota/v1/install/update_filter.go#L26-L33

Currently, the status update is ignored, so resource quota never sees the actual scale down, and the quota is only updated by the periodic resync.

/sig node
/milestone v1.32
/priority important-longterm

### PR DESCRIPTION
**Pull request by bouaouda-achraf**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:
Ensuring timely and accurate updates to resource quotas when pods are scaled down or up.

#### Which issue(s) this PR fixes:
*Automatically closes linked issue when PR is merged.
Usage: `Fixes https://github.com/kubernetes/kubernetes/issues/127132.

Fixes #

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

File: pkg/quota/v1/install/update_filter.go [hunk 1]
```diff
@@ -44,3 +52,17 @@ func DefaultUpdateFilter() func(resource schema.GroupVersionResource, oldObj, ne
...
 }
+
+// hasAllocatedResourcesChanged function to compare allocated resources in container statuses
+func hasAllocatedResourcesChanged(oldPod *v1.Pod, newPod *v1.Pod) bool {
+	if len(oldPod.Status.ContainerStatuses) != len(newPod.Status.ContainerStatuses) {
+		return false
+	}
+	for i, oldStatus := range oldPod.Status.ContainerStatuses {
+		newStatus := newPod.Status.ContainerStatuses[i]
+		if !reflect.DeepEqual(oldStatus.AllocatedResources, newStatus.AllocatedResources) {
```
Comment (bart0sh) [inline pkg/quota/v1/install/update_filter.go:63]: `DeepEqual` is quite heavy operation. Can we do this without using it?

File: pkg/quota/v1/install/update_filter.go [hunk 2]
```diff
@@ -30,6 +34,10 @@ func DefaultUpdateFilter() func(resource schema.GroupVersionResource, oldObj, ne
 		case schema.GroupResource{Resource: "pods"}:
 			oldPod := oldObj.(*v1.Pod)
 			newPod := newObj.(*v1.Pod)
+			// when AllocatedResources changed
+			if feature.DefaultFeatureGate.Enabled(features.InPlacePodVerticalScaling) && hasAllocatedResourcesChanged(oldPod, newPod) {
+				return true
+			}
```
Comment (bart0sh) [inline pkg/quota/v1/install/update_filter.go:40]: nit:
```suggestion
			if feature.DefaultFeatureGate.Enabled(features.InPlacePodVerticalScaling) {
			         // when AllocatedResources changed
			         return hasAllocatedResourcesChanged(oldPod, newPod) {
			}
```

Comment (bouaouda-achraf) [reply pkg/quota/v1/install/update_filter.go:40]: At your suggestion we will not execute the rest of the logic (next line): 
-> return core.QuotaV1Pod(oldPod, clock.RealClock{}) && !core.QuotaV1Pod(newPod, clock.RealClock{}) 
( when feature enabled and  NOT hasAllocatedResourcesChanged  -> need to check QuotaV1Pod oldPod and newPod )

Comment (bart0sh) [reply pkg/quota/v1/install/update_filter.go:40]: True. I take it back.

File: pkg/quota/v1/install/update_filter.go (hunk 1 above)
Comment (bouaouda-achraf) [reply pkg/quota/v1/install/update_filter.go]: fixed

File: pkg/quota/v1/install/update_filter.go [hunk 3]
```diff
@@ -44,3 +51,17 @@ func DefaultUpdateFilter() func(resource schema.GroupVersionResource, oldObj, ne
...
 }
+
+// hasAllocatedResourcesChanged function to compare allocated resources in container statuses
+func hasAllocatedResourcesChanged(oldPod *v1.Pod, newPod *v1.Pod) bool {
+	if len(oldPod.Status.ContainerStatuses) != len(newPod.Status.ContainerStatuses) {
+		return false
+	}
+	for i, oldStatus := range oldPod.Status.ContainerStatuses {
+		newStatus := newPod.Status.ContainerStatuses[i]
+		if !resourcehelper.EqualResourceList(oldStatus.AllocatedResources, newStatus.AllocatedResources) {
```
Comment (bart0sh) [inline pkg/quota/v1/install/update_filter.go:62]: Would `maps.Equal` work here?
```suggestion
		if !maps.Equal(oldStatus.AllocateResources, newStatus.AllocateResources) { 
```

Comment (bouaouda-achraf) [reply pkg/quota/v1/install/update_filter.go:62]: This won't work because maps.Equal doesn't handle equal semantic value. 
otherwise, I will modify the "Equal ResourceList" test case to test this scenario. 
( CPU: 1000m  == CPU:1 )

File: pkg/api/v1/resource/helpers.go [hunk 4]
```diff
@@ -227,6 +227,23 @@ func maxResourceList(list, newList v1.ResourceList) {
...
+	for key, valList := range list {
+		valNewList, found := newList[key]
+		if !found {
+			return false
+		}
+		if valList.Cmp(valNewList) != 0 {
+			return false
+		}
+	}
+	return true
```
Comment (bart0sh) [inline pkg/api/v1/resource/helpers.go:244]:
```suggestion
	return maps.EqualFunc(list, newList, func(val1, val2 resource.Quantity) bool {
		return val1.Equal(val2)
	})
```

File: pkg/api/v1/resource/helpers_test.go [hunk 5]
```diff
@@ -575,6 +575,77 @@ func getPod(cname string, resources podResources) *v1.Pod {
...
+			newList:     v1.ResourceList{},
+			expected:    true,
+		},
+	}
+	for _, tc := range testCases {
+		t.Run(tc.description, func(t *testing.T) {
+			result := EqualResourceList(tc.list, tc.newList)
+			if result != tc.expected {
+				t.Errorf("[%s] expected = %v, got %v", tc.description, tc.expected, result)
+			}
```
Comment (bart0sh) [inline pkg/api/v1/resource/helpers_test.go:644]:
```suggestion
                        assert.Equal(t, tc.expected, EqualResourceList(tc.list, tc.newList))
```

File: pkg/api/v1/resource/helpers_test.go [hunk 6]
```diff
@@ -575,6 +575,77 @@ func getPod(cname string, resources podResources) *v1.Pod {
 	}
 }
 
+func TestEqualResourceList(t *testing.T) {
+	testCases := []struct {
+		description string
+		list        v1.ResourceList
+		newList     v1.ResourceList
+		expected    bool
```
Comment (bart0sh) [inline pkg/api/v1/resource/helpers_test.go:583]: nit:
```suggestion
		list1                        v1.ResourceList
		list2                       v1.ResourceList
		expectedResult    bool
```

**Comment by tallclair** [comment]
This PR needs to be updated after https://github.com/kubernetes/kubernetes/pull/128377 merges. Quota should only look at `max(Container.Resources, ContainerStatus.Resources)`, not AllocatedResources.

File: pkg/api/v1/resource/helpers.go [hunk 7]
```diff
@@ -227,6 +228,13 @@ func maxResourceList(list, newList v1.ResourceList) {
 	}
 }
 
+// EqualResourceList compares two ResourceList maps for equality.
+func EqualResourceList(list1, list2 v1.ResourceList) bool {
```
Comment (tallclair) [inline pkg/api/v1/resource/helpers.go:232]: Can you just use `apiequality.Semantic.DeepEqual` instead?

File: pkg/quota/v1/install/update_filter.go (hunk 3 above)
Comment (tallclair) [inline pkg/quota/v1/install/update_filter.go:62]: This should compare the `Resources` field instead.
```suggestion
		if !resourcehelper.EqualResourceList(oldStatus.Resources, newStatus.Resources) {
```

Comment (bouaouda-achraf) [reply pkg/quota/v1/install/update_filter.go]: fixed

File: pkg/api/v1/resource/helpers.go (hunk 7 above)
Comment (bouaouda-achraf) [reply pkg/api/v1/resource/helpers.go]: fixed

File: pkg/quota/v1/install/update_filter.go [hunk 8]
```diff
@@ -44,3 +51,17 @@ func DefaultUpdateFilter() func(resource schema.GroupVersionResource, oldObj, ne
...
 	}
 }
+
+// hasResourcesChanged function to compare resources in container statuses
+func hasResourcesChanged(oldPod *v1.Pod, newPod *v1.Pod) bool {
+	if len(oldPod.Status.ContainerStatuses) != len(newPod.Status.ContainerStatuses) {
+		return false
+	}
+	for i, oldStatus := range oldPod.Status.ContainerStatuses {
+		newStatus := newPod.Status.ContainerStatuses[i]
```
Comment (tallclair) [inline pkg/quota/v1/install/update_filter.go:61]: You can't assume that the old ContainerStatuses were in the same order. Use `podutil.GetContainerStatus(newPod.Status.ContainerStatuses, oldStatus.Name)`

File: pkg/quota/v1/install/update_filter.go [hunk 9]
```diff
@@ -44,3 +51,17 @@ func DefaultUpdateFilter() func(resource schema.GroupVersionResource, oldObj, ne
 		return false
 	}
 }
+
+// hasResourcesChanged function to compare resources in container statuses
+func hasResourcesChanged(oldPod *v1.Pod, newPod *v1.Pod) bool {
```
Comment (tallclair) [inline pkg/quota/v1/install/update_filter.go:56]: Please add a unit test for this.

File: pkg/quota/v1/install/update_filter.go [hunk 10]
```diff
@@ -44,3 +51,17 @@ func DefaultUpdateFilter() func(resource schema.GroupVersionResource, oldObj, ne
...
+	if len(oldPod.Status.ContainerStatuses) != len(newPod.Status.ContainerStatuses) {
+		return false
+	}
+	for i, oldStatus := range oldPod.Status.ContainerStatuses {
```
Comment (tallclair) [inline pkg/quota/v1/install/update_filter.go:60]: Can you check `InitContainerStatuses` too? Sidecar support is in-flight, but if your PR merges first, it will just be a no-op.
https://github.com/kubernetes/kubernetes/pull/128367

File: pkg/quota/v1/install/update_filter.go (hunk 9 above)
Comment (bouaouda-achraf) [reply pkg/quota/v1/install/update_filter.go:57]: fixed

File: pkg/quota/v1/install/update_filter.go (hunk 10 above)
Comment (bouaouda-achraf) [reply pkg/quota/v1/install/update_filter.go]: fixed

File: pkg/quota/v1/install/update_filter.go (hunk 8 above)
Comment (bouaouda-achraf) [reply pkg/quota/v1/install/update_filter.go]: fixed

**Comment by bouaouda-achraf** [comment]
thank you @tallclair  and @bart0sh  for all your comments.
