### PR TITLE
Fix race condition in DRA health e2e test pod status update

### LINKED ISSUE #135317: [Flaky Test] [sig-node] E2eNode Suite.[It] [sig-node] [DRA] [Feature:DynamicResourceAllocation] [FeatureGate:DynamicResourceAllocation] Resource Health [Serial] should not add health status to Pod when feature gate is disabled
### Which jobs are flaking?

- master-informing
  - ci-node-e2e-containerd-1-7-dra

### Which tests are flaking?

- `E2eNode Suite.[It] [sig-node] [DRA] [Feature:DynamicResourceAllocation] [FeatureGate:DynamicResourceAllocation] Resource Health [Serial] should not add health status to Pod when feature gate is disabled`

### Since when has it been flaking?

- [2025-11-06 06:40:23 +0000 UTC](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-node-e2e-containerd-1-7-dra/1986322656760172544)
- [2025-11-09 00:43:25 +0000 UTC](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-node-e2e-containerd-1-7-dra/1987319988695863296)
- [2025-11-15 12:44:34 +0000 UTC](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-node-e2e-containerd-1-7-dra/1989675783022448640)

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#ci-node-e2e-containerd-1-7-dra

### Reason for failure (if possible)

```
{ failed [FAILED] failed to update Pod status with ResourceClaimStatuses: Operation cannot be fulfilled on pods "gate-disabled-pod": the object has been modified; please apply your changes to the latest version and try again
In [It] at: k8s.io/kubernetes/test/e2e_node/dra_test.go:1674 @ 11/15/25 13:02:35.668
}
```

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by harche**
#### What type of PR is this?
/kind flake

#### What this PR does / why we need it:
After creating the pod, the test immediately fetches and updates the pod status to add `ResourceClaimStatuses`. However, between the Get and UpdateStatus calls, the kubelet or other controllers may concurrently modify the pod. 

#### Which issue(s) this PR is related to:

Fixes : https://github.com/kubernetes/kubernetes/issues/135317 

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e_node/dra_test.go [hunk 1]
```diff
@@ -1665,13 +1665,18 @@ func createHealthTestPodAndClaim(ctx context.Context, f *framework.Framework, dr
...
+		podToUpdate, err := f.ClientSet.CoreV1().Pods(f.Namespace.Name).Get(ctx, createdPod.Name, metav1.GetOptions{})
+		if err != nil {
+			return err
+		}
+		podToUpdate.Status.ResourceClaimStatuses = []v1.PodResourceClaimStatus{
+			{Name: claimName, ResourceClaimName: &claimName},
+		}
+		_, err = f.ClientSet.CoreV1().Pods(f.Namespace.Name).UpdateStatus(ctx, podToUpdate, metav1.UpdateOptions{})
+		return err
+	}).WithContext(ctx).WithTimeout(10*time.Second).WithPolling(500*time.Millisecond).Should(gomega.Succeed(), "failed to update Pod status with ResourceClaimStatuses")
```
Comment (bart0sh) [inline test/e2e_node/dra_test.go]: Would it make sense to `Patch` claim status instead of updating pod? That would be simpler and would fix the race.

Comment (harche) [reply test/e2e_node/dra_test.go]: It could but I thought since this is just a test case having a simple get + update was a simpler pattern, I just followed the existing pattern in that file, e.g. https://github.com/kubernetes/kubernetes/blob/3025b0a7b4b9fba6110759e905346ead5c9c0720/test/e2e_node/dra_test.go#L1668

Comment (bart0sh) [reply test/e2e_node/dra_test.go]: Apparently that pattern causes test flake here and needs to be replaced by something else. Patch seems to be a good candidate in my opinion.

Comment (harche) [reply test/e2e_node/dra_test.go]: Thanks @bart0sh I have updated the PR.

File: test/e2e_node/dra_test.go [hunk 2]
```diff
@@ -1664,14 +1666,17 @@ func createHealthTestPodAndClaim(ctx context.Context, f *framework.Framework, dr
...
+	patch, err := json.Marshal(v1.Pod{
+		Status: v1.PodStatus{
+			ResourceClaimStatuses: []v1.PodResourceClaimStatus{
+				{Name: claimName, ResourceClaimName: &claimName},
+			},
+		},
+	})
+	framework.ExpectNoError(err, "failed to marshal patch for Pod status")
+	_, err = f.ClientSet.CoreV1().Pods(f.Namespace.Name).Patch(ctx, createdPod.Name, apitypes.StrategicMergePatchType, patch, metav1.PatchOptions{}, "status")
+	framework.ExpectNoError(err, "failed to patch Pod status with ResourceClaimStatuses")
```
Comment (bart0sh) [inline test/e2e_node/dra_test.go:1751]: This looks good, thank you!

BTW, would it be possible to simply include this Status into the pod , so we can create pod with the required status in one step? That would simplify the code even more and eliminate any possibility for the race.

Comment (harche) [reply test/e2e_node/dra_test.go:1751]: The `Status` subresource is ignored during Pod creation, the API server strips it out, so a separate patch/update to the status endpoint is required.

Comment (bart0sh) [reply test/e2e_node/dra_test.go:1751]: ok, makes sense. 

/lgtm

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve

**Comment by pohly** [comment]
> Fixes : https://github.com/kubernetes/kubernetes/issues/135317

Nit: please don't auto-close issues for flakes, we want to merge the PR and then close the issue after verifying that the jobs are really stable again.
