### PR TITLE
Prevent kube-proxy from panicing when sysfs is mounted as read-only.

### LINKED ISSUE #25543: Work around KubeProxy panic that makes Node's network not working
Currently a Docker bug may cause KubeProxy to crashloop thus making the Node unable to use cluster network, which in turn makes Pods scheduled on this Node unreachable.

To mitigate this issue we need to surface the information about problems with KubeProxy, that will allow scheduler to ignore given node when scheduling new Pods. ProblemAPI is going to address this kind of problems in the future, but we need a fix for the 1.3.

Either Kubelet or KubeProxy needs to update a NodeStatus with the information that Node networking is down. I suggests that we reuse NodeReady Condition for this, as this would make the rest of ControlPlane work out of the box. We will replace this fix with the ProblemAPI use in the future. @thockin @dchen1107 

Another option, which requires more work, is creating a completely new NodeCondition type to handle this case. This would require making Scheduler aware of this new Condition. @davidopp @bgrant0607 

@alex-mohr @wojtek-t @fgrzadkowski @zmerlynn

### PR DESCRIPTION
**Pull request by Random-Liu**
Fixes https://github.com/kubernetes/kubernetes/issues/25543.

This PR:
- Checks the permission of sysfs before setting conntrack hashsize, and returns an error "readOnlySysFSError" if sysfs is readonly. As I know, this is the only place we need write permission to sysfs, CMIIW.
- Update a new node condition 'RuntimeUnhealthy' with specific reason, message and hit to the administrator about the remediation.

I think this should be an acceptable fix for now.
Node problem detector is designed to integrate with different problem daemons, but **the main logic is in the problem detection phase**. After the problem is detected, what node problem detector does is also simply updating a node condition.

If we let kube-proxy pass the problem to node problem detector and let node problem detector update the node condition. It looks like an unnecessary hop. The logic in kube-proxy won't be different from this PR, but node problem detector will have to open an unsafe door to other pods because the lack of authentication mechanism.

It is a bit hard to test this PR, because we don't really have a bad docker in hand. I can only manually test it:
- If I manually change the code to let it return `"readOnlySysFSError`, the node condition will be updated:

```
  NetworkUnavailable    False   Mon, 01 Jan 0001 00:00:00 +0000     Fri, 08 Jul 2016 01:36:41 -0700     RouteCreated            RouteController created a route
  OutOfDisk         False   Fri, 08 Jul 2016 01:37:36 -0700     Fri, 08 Jul 2016 01:34:49 -0700     KubeletHasSufficientDisk    kubelet has sufficient disk space available
  MemoryPressure    False   Fri, 08 Jul 2016 01:37:36 -0700     Fri, 08 Jul 2016 01:34:49 -0700     KubeletHasSufficientMemory  kubelet has sufficient memory available
  Ready         True    Fri, 08 Jul 2016 01:37:36 -0700     Fri, 08 Jul 2016 01:35:26 -0700     KubeletReady            kubelet is posting ready status. WARNING: CPU hardcapping unsupported
  RuntimeUnhealthy  True    Fri, 08 Jul 2016 01:35:31 -0700     Fri, 08 Jul 2016 01:35:31 -0700     ReadOnlySysFS           Docker unexpectedly mounts sysfs as read-only for privileged container (docker issue #24000). This causes the critical system components of Kubernetes not properly working. To remedy this please restart the docker daemon.
  KernelDeadlock    False   Fri, 08 Jul 2016 01:37:39 -0700     Fri, 08 Jul 2016 01:35:34 -0700     KernelHasNoDeadlock         kernel has no deadlock
Addresses:      10.240.0.3,104.155.176.101
```
- If not, the node condition `RuntimeUnhealthy` won't appear.
- If I run the permission checking code in a unprivileged container, it did return `readOnlySysFSError`.

I'm not sure whether we want to mark the node as `Unscheduable` when this happened, which only needs few lines change. I can do that if we think we should.

I'll add some unit test if we think this fix is acceptable.

/cc @bprashanth @dchen1107 @matchstick @thockin @alex-mohr 

Mark P1 to match the original issue.
[Analytics]()

### CODE REVIEW

File: cmd/kube-proxy/app/conntrack.go [hunk 1]
```diff
@@ -46,3 +62,16 @@ func (realConntracker) SetTCPEstablishedTimeout(seconds int) error {
...
 	return sysctl.SetSysctl("net/netfilter/nf_conntrack_tcp_timeout_established", seconds)
 }
+
+// isSysFSWritable checks /proc/mounts to see whether sysfs is 'rw' or not.
+func isSysFSWritable() (bool, error) {
+	const (
+		permScript   = "cat /proc/mounts | grep sysfs | awk -F\"[@ ,]\" '{printf $4}'"
+		permWritable = "rw"
+	)
+	perm, err := exec.Command("sh", "-c", permScript).CombinedOutput()
```
Comment (dims) [inline cmd/kube-proxy/app/conntrack.go]: Dependency on multiple commands. Is it possible to re purpose the Mounter.List/listProcMounts code to do this? https://github.com/kubernetes/kubernetes/blob/f2ddd60eb9e7e9e29f7a105a9a8fa020042e8e52/pkg/util/mount/mount_linux.go#L174 (Was that already ruled out for some other reason?)

Comment (Random-Liu) [inline cmd/kube-proxy/app/conntrack.go]: @dims Thanks a lot~ Don't know we have this one. :)
Sure, I'll change to that!

**Comment by bprashanth** [comment]
Kube-proxy updating node status is making me think twice. Where do we draw the line? why not update node-status from kube-dns and all the other addons then? 

It's something I can live with, but if we're willing to distribute ownership of node status to all daemons, why did we write a centralized NPD? I can just write a daemon set for each problem that can potentially arise, run it in a loop to check that one problem, and have it write node status right? 

Are we confident this won't clobber some status update pushed by the kubelet (or the other way)?

File: cmd/kube-proxy/app/conntrack.go [hunk 2]
```diff
@@ -32,11 +34,25 @@ type Conntracker interface {
...
+	// Setting conntrack will fail when sysfs is readonly. When that happens, we don't set conntrack
+	// hashsize and return a special error readOnlySysFSError here. The caller should deal with
+	// readOnlySysFSError differently.
+	writable, err := isSysFSWritable()
+	if err != nil {
+		return err
+	}
+	if !writable {
+		return readOnlySysFSError
+	}
```
Comment (bprashanth) [inline cmd/kube-proxy/app/conntrack.go]: What happens if we just flare an event and carry on? do e2es pass? 
@thockin is the node really unusable if we can't set the table size?

**Comment by davidopp** [comment]
I suggest to modify the scheduler here
https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/scheduler/factory/factory.go#L434
to prevent the system from sending new pods to a node that has RuntimeUnhealthy condition.

File: cmd/kube-proxy/app/conntrack.go (hunk 2 above)
Comment (Random-Liu) [inline cmd/kube-proxy/app/conntrack.go]: As mentioned in https://github.com/kubernetes/kubernetes/pull/28697#issue-164584119:
> I'm not sure whether we want to mark the node as Unscheduable when this happened, which only needs few lines change. I can do that if we think we should.

We can mark the node as unschedulable.

**Comment by Random-Liu** [comment]
> why not update node-status from kube-dns and all the other addons then?

I think we may want to let the critical system daemons update **node problem** when it feels totally wrong with the node. The only thing is that node problem is expressed as `NodeCondition` in `NodeStatus`.
If we wrap the logic in a "Problem Client", and the system daemons don't need to care about who it is talking to, maybe things will become a little more clear? :)

> Why did we write a centralized NPD? I can just write a daemon set for each problem that can potentially arise, run it in a loop to check that one problem, and have it write node status right?

I think node problem detector is a component to integrate real problem daemons, such as kernel monitor, hardware checker or something. In the future, we may not want arbitrary pod updating to the apiserver, and we may not want to add a kernel monitor pod, cpu health checker pod... That's why we have node problem detector.

> Are we confident this won't clobber some status update pushed by the kubelet (or the other way)?

That's why we are using `Patch` instead of `UpdateStatus`.

File: cmd/kube-proxy/app/conntrack.go (hunk 1 above)
Comment (Random-Liu) [inline cmd/kube-proxy/app/conntrack.go]: Done.

**Comment by thockin** [comment]
I agree that we *probably* don't really want this logic distributed.  I think kubelet is responsible for the node, and anyone else should be reporting to Kubelet.  NPD is an extension of kubelet

File: cmd/kube-proxy/app/conntrack.go (hunk 2 above)
Comment (thockin) [inline cmd/kube-proxy/app/conntrack.go]: The node will be OK.  Kube-proxy will run, it will just be more likely to run out of conntrack entries.  It might also affect some of the conntrack-based UDP cleanup in the case of rapid re-use.

If we think that firing an event is actually enough signal for us to a) keep track of how often this occurs in our tests and b) help debug when a user gets a conntrack error, then that is certainly a lighter-weight solution

File: cmd/kube-proxy/app/server.go [hunk 3]
```diff
@@ -299,8 +300,22 @@ func (s *ProxyServer) Run() error {
 	// Tune conntrack, if requested
 	if s.Conntracker != nil {
 		if s.Config.ConntrackMax > 0 {
-			if err := s.Conntracker.SetMax(int(s.Config.ConntrackMax)); err != nil {
-				return err
+			err := s.Conntracker.SetMax(int(s.Config.ConntrackMax))
+			if err != nil {
+				if err.Error() != readOnlySysFSError.Error() {
```
Comment (thockin) [inline cmd/kube-proxy/app/server.go]: minor, but can't you just compare the error directly?  without .Error

**Comment by Random-Liu** [comment]
> I agree that we probably don't really want this logic distributed. I think kubelet is responsible for the node, and anyone else should be reporting to Kubelet. NPD is an extension of kubelet.

How about this? Ideally,
* On kube-proxy side, when it fails wrong with the node, it will report a problem with "node problem client".
* On node problem detector side, it should open a save door for other node daemons to report problems.

However, now we are lack of mechanism to prevent arbitrary pod from talking with node problem detector (we may need authentication or network policy to prevent inter-namespace communication https://github.com/kubernetes/kubernetes/issues/22469).
So as a temporary walk around, we'll let the "node problem client" talk with apiserver directly, and what the "node problem client" does is to set a node condition as we finalized in https://github.com/kubernetes/kubernetes/issues/23028.

**Comment by thockin** [comment]
We don't currently have any way to prevent a random pod from contacting the
apiserver or mounting the root filesystem, either...

**Comment by thockin** [comment]
I'm OK with that approach, for now, though, though "drop a file in a
directory" seems like an approriate API between kube-proxy and NPD.

What do you think about just sending an event and not carrying on?

File: cmd/kube-proxy/app/server.go (hunk 3 above)
Comment (Random-Liu) [inline cmd/kube-proxy/app/server.go]: ACK, will change this. I was confused. :P

**Comment by smarterclayton** [comment]
We do, it's just not enabled by default.  Both PodSecurityPolicy and the
authorization filters are sufficient.

**Comment by Random-Liu** [comment]
Offline discussed with @thockin, now kube-proxy only needs sysfs writable permission when configuring conntrack `hashsize`: https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/conntrack.go#L42. If it failed, it won't affect that much, so we can just report an event and move on.

Now, we'll send a node event when kube-proxy detects that `sysfs` is read-only.
```
1m          1m         1         e2e-test-lantaol-minion-group-iz4x   Node                  Warning   ReadOnlySysFS             {kube-proxy e2e-test-lantaol-minion-group-iz4x}   Kube-proxy can't apply system configuration properly, becasue docker unexpectedly mounts sysfs as read-only for privileged container (docker issue #24000). To remedy this please restart the docker daemon.
```

**Comment by davidopp** [comment]
Nit: that message is kinda long; people may not read all the way to the end, which has the important bit. Maybe consider
```
YOU MUST RESTART THE DOCKER DAEMON ON THIS NODE. Kube-proxy can't apply system configuration properly, due to docker issue #24000, which means networking on this node will not work properly.
```
or something like that.

File: cmd/kube-proxy/app/server.go [hunk 4]
```diff
@@ -299,8 +299,19 @@ func (s *ProxyServer) Run() error {
...
+					return err
+				}
+				// readOnlySysFSError is caused by a known docker issue (https://github.com/docker/docker/issues/24000),
+				// the only remediation we know is to restart the docker daemon.
+				// Here we'll send an node event with specific reason and message, the
+				// administrator should decide whether and how to handle this issue,
+				// whether to drain the node and restart docker.
+				// TODO(random-liu): Remove this when the docker bug is fixed.
+				s.Recorder.Eventf(s.Config.NodeRef, api.EventTypeWarning, err.Error(),
+					"Kube-proxy can't apply system configuration properly, becasue docker unexpectedly mounts sysfs as read-only for privileged container (docker issue #24000). To remedy this please restart the docker daemon.")
```
Comment (thockin) [inline cmd/kube-proxy/app/server.go]: typo: s/becasue/because/

Can we shorten this?  Maybe "Kube-proxy can't apply system configuration: /sys is read-only (docker issue #24000).  To remedy, restart docker."

**Comment by thockin** [comment]
thanks!  Just typos/text nits

File: cmd/kube-proxy/app/server.go (hunk 4 above)
Comment (Random-Liu) [inline cmd/kube-proxy/app/server.go]: ACK.

**Comment by Random-Liu** [comment]
@thockin @davidopp Addressed comments. Thanks for reviewing. :)

File: cmd/kube-proxy/app/conntrack.go [hunk 5]
```diff
@@ -32,11 +34,25 @@ type Conntracker interface {
...
 	glog.Infof("Setting nf_conntrack_max to %d", max)
 	if err := sysctl.SetSysctl("net/netfilter/nf_conntrack_max", max); err != nil {
 		return err
 	}
+	// sysfs is expected to be mounted as 'rw'. However, it may be unexpectedly mounted as
+	// 'ro' by docker because of a known docker issue (https://github.com/docker/docker/issues/24000).
+	// Setting conntrack will fail when sysfs is readonly. When that happens, we don't set conntrack
+	// hashsize and return a special error readOnlySysFSError here. The caller should deal with
+	// readOnlySysFSError differently.
+	writable, err := isSysFSWritable()
```
Comment (thockin) [inline cmd/kube-proxy/app/conntrack.go]: Would it be simpler if we simply captured and analyzed the error we get when the ioutil.WriteFile fails?

**Comment by thockin** [comment]
LGTM

File: cmd/kube-proxy/app/server.go [hunk 6]
```diff
@@ -299,8 +299,19 @@ func (s *ProxyServer) Run() error {
...
+				if err != readOnlySysFSError {
+					return err
+				}
+				// readOnlySysFSError is caused by a known docker issue (https://github.com/docker/docker/issues/24000),
+				// the only remediation we know is to restart the docker daemon.
+				// Here we'll send an node event with specific reason and message, the
+				// administrator should decide whether and how to handle this issue,
+				// whether to drain the node and restart docker.
+				// TODO(random-liu): Remove this when the docker bug is fixed.
+				const message = "RESTART DOCKER TO REMEDY. Kube-proxy can't apply system configuration: /sys is read-only (docker issue #24000)."
```
Comment (davidopp) [inline cmd/kube-proxy/app/server.go]: This message is missing why the user should care. I would suggest saying "Networking will not work properly on this node." in between those two sentences.

Comment (thockin) [inline cmd/kube-proxy/app/server.go]: It's not the case that networking won't work properly.  I just might break
down sooner (run out of conntrack entries).  BUt yeah, OK.

"DOCKER RESTART NEEDED (docker issue #24000): /sys is read-only: can't
raise conntrack limits, problems may arise later"

File: cmd/kube-proxy/app/conntrack.go (hunk 5 above)
Comment (Random-Liu) [inline cmd/kube-proxy/app/conntrack.go]: I've tried [`IsPermissions`](https://golang.org/pkg/os/#IsPermission), and it doesn't seem to work for read only file system error.
And parsing string seems to be a little more brittle than this one.

File: cmd/kube-proxy/app/server.go (hunk 6 above)
Comment (Random-Liu) [inline cmd/kube-proxy/app/server.go]: ACK.

**Comment by Random-Liu** [comment]
Just updated the message content, self apply LGTM according to https://github.com/kubernetes/kubernetes/pull/28697#issuecomment-231641625.
