### PR TITLE
periodically reload the cni plugin configuration

### LINKED ISSUE #28787: Allow CNI node agents to run in a DaemonSet
Host network pods should be able to be created before the container network exists. Pod syncs for pods on the container network should fail until the container network is configured.

cc @freehan @girishkalele

### PR DESCRIPTION
**Pull request by mikedanese**
Might fix #28787

### CODE REVIEW

File: pkg/kubelet/network/cni/cni.go [hunk 1]
```diff
@@ -79,15 +85,20 @@ func getDefaultCNINetwork(pluginDir, vendorCNIDirPrefix string) (*cniNetwork, er
...
 	for _, confFile := range files {
 		conf, err := libcni.ConfFromFile(confFile)
 		if err != nil {
 			glog.Warningf("Error loading CNI config file %s: %v", confFile, err)
 			continue
 		}
-		// Search for vendor-specific plugins as well as default plugins in the CNI codebase.
+
 		vendorCNIDir := fmt.Sprintf(VendorCNIDirTemplate, vendorCNIDirPrefix, conf.Network.Type)
+		// Search for vendor-specific plugins as well as default plugins in the CNI codebase.
```
Comment (freehan) [inline pkg/kubelet/network/cni/cni.go]: move this back

File: pkg/kubelet/network/cni/cni.go [hunk 2]
```diff
@@ -79,15 +85,20 @@ func getDefaultCNINetwork(pluginDir, vendorCNIDirPrefix string) (*cniNetwork, er
 		return nil, fmt.Errorf("No networks found in %s", pluginDir)
 	}
 
+	if pluginDir == "" {
```
Comment (freehan) [inline pkg/kubelet/network/cni/cni.go]: move this back?

File: pkg/kubelet/network/cni/cni.go [hunk 3]
```diff
@@ -53,24 +59,24 @@ type cniNetwork struct {
...
-		return configList
-	}
-	return append(configList, &cniNetworkPlugin{
-		defaultNetwork: network,
+	plugin := &cniNetworkPlugin{
+		defaultNetwork: nil,
 		execer:         utilexec.New(),
-	})
+	}
+
```
Comment (freehan) [inline pkg/kubelet/network/cni/cni.go]: add some comments like:

sync network config from pluginDir periodically to detect network config updates.

File: pkg/kubelet/network/cni/cni.go [hunk 4]
```diff
@@ -108,6 +119,15 @@ func (plugin *cniNetworkPlugin) Init(host network.Host, hairpinMode componentcon
 	return nil
 }
 
+func (plugin *cniNetworkPlugin) update(pluginDir, vendorCNIDirPrefix string) {
```
Comment (freehan) [inline pkg/kubelet/network/cni/cni.go]: update -> syncNetworkConfig

File: pkg/kubelet/network/cni/cni.go [hunk 5]
```diff
@@ -53,14 +59,18 @@ type cniNetwork struct {
...
 func probeNetworkPluginsWithVendorCNIDirPrefix(pluginDir, vendorCNIDirPrefix string) []network.NetworkPlugin {
 	configList := make([]network.NetworkPlugin, 0)
-	network, err := getDefaultCNINetwork(pluginDir, vendorCNIDirPrefix)
-	if err != nil {
-		return configList
-	}
-	return append(configList, &cniNetworkPlugin{
-		defaultNetwork: network,
+	plugin := &cniNetworkPlugin{
+		defaultNetwork: nil,
```
Comment (aaronlevy) [inline pkg/kubelet/network/cni/cni.go]: Not familiar with the caller mechanics of the network plugins, but this would seem to leave an opening for nil pointer dereference on calls to SetUpPod/TearDownPod, etc.

File: pkg/kubelet/network/cni/cni.go [hunk 6]
```diff
@@ -170,6 +189,24 @@ func (network *cniNetwork) addToNetwork(podName string, podNamespace string, pod
...
+	defer plugin.Unlock()
+	plugin.defaultNetwork = n
+}
+
+func (plugin *cniNetworkPlugin) Status() error {
+	if plugin.getDefaultNetwork() == nil {
+		return errors.New("cni config unintialized")
+	}
+	return nil
+}
```
Comment (aaronlevy) [inline pkg/kubelet/network/cni/cni.go]: Nit: these (*cniNetworkPlugin) methods are intermixed with (*cniNetwork) methods. Maybe move them inline with rest of calls.

File: pkg/kubelet/network/cni/cni.go (hunk 5 above)
Comment (aaronlevy) [inline pkg/kubelet/network/cni/cni.go]: Accidentally deleted previous comment, but at a glance this looks like it could result in nil pointer errors in calls to the NetworkPlugin methods. So maybe just validating this assumption is safe via tests, or maybe a nullPlugin which logs/returns errors on those same calls until a real plugin config is picked up .(or my reading of this is off).

Comment (mikedanese) [inline pkg/kubelet/network/cni/cni.go]: Ya... I think this problem exists in the master code. If getDefaultCNINetwork fails on the initial configuration (if the cni config isn't present on disk), it will be nil. In theory, network plugin users should be calling Status() before they use the network plugin but before this PR status always returns true so that cause will cause a nil ptr. @freehan what do you think?

File: pkg/kubelet/network/cni/cni.go (hunk 3 above)
Comment (mikedanese) [inline pkg/kubelet/network/cni/cni.go]: Done.

File: pkg/kubelet/network/cni/cni.go (hunk 5 above)
Comment (freehan) [inline pkg/kubelet/network/cni/cni.go]: kubelet will block sync pod if plugin Status returns error. We should double check Status in Setup/TearDown to add additional safeguard.

File: pkg/kubelet/network/cni/cni.go (hunk 6 above)
Comment (mikedanese) [inline pkg/kubelet/network/cni/cni.go]: Moved these guys up.

File: pkg/kubelet/network/cni/cni.go (hunk 5 above)
Comment (mikedanese) [inline pkg/kubelet/network/cni/cni.go]: Done.

Comment (aaronlevy) [inline pkg/kubelet/network/cni/cni.go]: Hmm. Wouldn't blocking sync pod defeat the goal of https://github.com/kubernetes/kubernetes-anywhere/issues/151

Comment (mikedanese) [inline pkg/kubelet/network/cni/cni.go]: No, I think this is correct. Creating a pod on the pod network should fail until cni is configured. However pods on the hostnetwork shouldn't be affected by this static check.

Comment (freehan) [inline pkg/kubelet/network/cni/cni.go]: Hmm... True... 

We can still block on Setup/TearDown and let sync pod starts.

Comment (aaronlevy) [inline pkg/kubelet/network/cni/cni.go]: @mikedanese I agree regarding podnetwork pods should fail until cni is configured -- and the network plugin daemonsets should use host-networking to skip this restriction.

However, I may be missing something, so if this works -- ignore me: 

In: 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2470 
wouldn't this always error (and skip pod sync) due to: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2920

Comment (mikedanese) [inline pkg/kubelet/network/cni/cni.go]: Ya.... thanks for pointing that out.

**Comment by luxas** [comment]
@freehan Any conclusion on this one?

**Comment by mikedanese** [comment]
@luxas it currently doesn't work correctly. I need to fix it up.

**Comment by luxas** [comment]
Okay, I'll wait. Things will be much better once we have this working.

File: pkg/kubelet/network/cni/cni.go (hunk 5 above)
Comment (mikedanese) [inline pkg/kubelet/network/cni/cni.go]: Ok, I no longer check initialization in the status. That should fix this issue I believe. The longterm fix is to decouple pod network and node network readiness in the runtime status check.

**Comment by mikedanese** [comment]
Ok, update, going to test now.

**Comment by mikedanese** [comment]
@matchstick this needs a new reviewer, is anyone picking up kubelet networking? if not, @aaronlevy or @luxas can probably review this. I pair programmed this with @freehan before he went on leave.

**Comment by matchstick** [comment]
Thanks @mikedanese. If @aaronlevy or @luxas can do the review that would be great.

File: pkg/kubelet/network/cni/cni.go [hunk 7]
```diff
@@ -53,14 +59,18 @@ type cniNetwork struct {
...
+		defaultNetwork: nil,
 		execer:         utilexec.New(),
-	})
+	}
+
+	plugin.syncNetworkConfig(pluginDir, vendorCNIDirPrefix)
+	// sync network config from pluginDir periodically to detect network config updates
+	go wait.Forever(func() {
+		plugin.syncNetworkConfig(pluginDir, vendorCNIDirPrefix)
+	}, 10*time.Second)
```
Comment (luxas) [inline pkg/kubelet/network/cni/cni.go]: nit: Do we have some common place to store loop intervals and timeouts?
Then this could be moved there... but that's not something that have to be done in this PR.

**Comment by luxas** [comment]
If you think https://github.com/kubernetes/kubernetes/pull/28178#discussion_r70345917 is resolved, then this LGTM. (Haven't manually tested it though, but all tests are green)

One problem I may think of yet is if the cni bridge already exists.
I've come across that, and in that case cni always throws an error both at init and when a pod should be started. We don't have to fix that here though...

**Comment by aaronlevy** [comment]
LGTM

**Comment by luxas** [comment]
@mikedanese I'm ready to let this though as soon as you have rebased

If this would make `v1.4,0-alpha.2`, then it would be great (cc @david-mcmahon)

**Comment by luxas** [comment]
Hmm, why is this `do-not-merge`?
cc @eparis that knows about the bot

Anyway, since it's LGTM, I'll apply the label.

**Comment by eparis** [comment]
@lavalamp @foxish @apelisse This is another PR which added `do-not-merge` and which both added and removed `retest-not-required-docs-only`. Neither of which makes any sense to me. What's the bot gotten up to while I've been on vacation?

**Comment by apelisse** [comment]
@eparis https://github.com/kubernetes/contrib/issues/1445

**Comment by bboreham** [comment]
FYI I have tested this via https://github.com/weaveworks/weave-kube - seems to do the job.

**Comment by caseydavenport** [comment]
FWIW - I've also tested this with Calico and all seems to work nicely.  Pretty cool!
