### PR TITLE
Make verify-typecheck.sh only check valid targets for a platform

### LINKED ISSUE #118020: verify-typecheck checks binaries that don't actually get built
In #118017 I tried to reorganize the kube-proxy build a bit, and ran into the problem that verify-typecheck failed because `cmd/kube-proxy` was no longer buildable on darwin/amd64 and darwin/arm64. This was surprising because we don't build kube-proxy on OS X.

It seems like verify-typecheck ought to be taking `KUBE_SUPPORTED_*_PLATFORMS` / `KUBE_*_TARGETS` from `hack/lib/golang.sh` into account when deciding what to check. There's no reason to be checking the OS X type compatibility of binaries that we don't build on OS X.

### PR DESCRIPTION
**Pull request by danwinship**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
`verify-typecheck.sh` currently makes sure that the entire tree builds on all supported platforms, even though we don't normally build some parts of it on some platforms. e.g., as noted in #118020, `verify-typecheck.sh` currently requires kube-proxy to be buildable on OS X, even though we don't normally build it there, and don't expect it to work there. As a result, the platform-related build tags on kube-proxy (and all the things it depends on) are wrong and can't be fixed (as seen in https://github.com/kubernetes/kubernetes/pull/120995#discussion_r1374955990).

This fixes it to only typecheck `KUBE_SERVER_TARGETS` on `KUBE_SUPPORTED_SERVER_PLATFORMS`, `KUBE_NODE_TARGETS` on `KUBE_SUPPORTED_NODE_PLATFORMS`, etc.

If you wanted to do some bash hacking you could probably make this more efficient by merging target groups together and only invoking `typecheck` once for each platform... but it's still pretty fast anyway...

I'm not sure it's testing all of the test-related directories it should be testing.

The integration with `verify-typecheck-providerless.sh` is a bit hacky...

#### Which issue(s) this PR fixes:
Fixes #118020

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/cc @BenTheElder

### CODE REVIEW

File: hack/verify-typecheck.sh [hunk 1]
```diff
@@ -28,13 +28,32 @@ kube::golang::verify_go_version
 
 cd "${KUBE_ROOT}"
 
+ret=0
+TYPECHECK_SERIAL="${TYPECHECK_SERIAL:-false}"
+
+SERVER_PLATFORMS=$(echo ${KUBE_SUPPORTED_SERVER_PLATFORMS[@]} | tr ' ' ',')
+CLIENT_PLATFORMS=$(echo ${KUBE_SUPPORTED_CLIENT_PLATFORMS[@]} | tr ' ' ',')
+NODE_PLATFORMS=$(echo ${KUBE_SUPPORTED_NODE_PLATFORMS[@]} | tr ' ' ',')
+TEST_PLATFORMS=$(echo ${KUBE_SUPPORTED_TEST_PLATFORMS[@]} | tr ' ' ',')
```
Comment (BenTheElder) [inline hack/verify-typecheck.sh:37]:
```suggestion
SERVER_PLATFORMS=$(echo "${KUBE_SUPPORTED_SERVER_PLATFORMS[@]}" | tr ' ' ',')
CLIENT_PLATFORMS=$(echo "${KUBE_SUPPORTED_CLIENT_PLATFORMS[@]}" | tr ' ' ',')
NODE_PLATFORMS=$(echo "${KUBE_SUPPORTED_NODE_PLATFORMS[@]}" | tr ' ' ',')
TEST_PLATFORMS=$(echo "${KUBE_SUPPORTED_TEST_PLATFORMS[@]}" | tr ' ' ',')
```

(and below for `${KUBE_SERVER_TARGETS[@]}`)

**Review by BenTheElder — COMMENTED** [review]
failing shellcheck lints on array expansion quoting but otherwise LGTM

**Comment by danwinship** [comment]
> failing shellcheck lints on array expansion quoting but otherwise LGTM

any comment on either of these things:

> I'm not sure it's testing all of the test-related directories it should be testing.
> 
> The integration with `verify-typecheck-providerless.sh` is a bit hacky...

In particular, I guess it's not covering `test/e2e_node` or `test/integration` now but I don't even know if we expect those to build on Windows? But adding more stuff to the "test" case is going to make the integration with `verify-typecheck-providerless.sh` even more hacky since it will have to explicitly `--ignore-dirs` each one, because `--ignore-dirs test` won't ignore subdirectories of `test/` explicitly specified on the command line, though maybe I should just fix that?

Also, if this is agreed to be the "right" way to run `typecheck` then maybe we should change the defaults there? (i.e., not default to all platforms and all files)

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Comment by BenTheElder** [comment]
> In particular, I guess it's not covering test/e2e_node or test/integration now but I don't even know if we expect those to build on Windows? But adding more stuff to the "test" case is going to make the integration with verify-typecheck-providerless.sh even more hacky since it will have to explicitly --ignore-dirs each one, because --ignore-dirs test won't ignore subdirectories of test/ explicitly specified on the command line, though maybe I should just fix that?

Yeah, it's gross but I think this is reasonable enough.
We _only_ effectively typecheck go here, so it's just a cheaper check to catch typical "forgot to define this for all platforms", we still depend on the real cross build to catch build issues.
I don't think we expect either to build on windows currently.

> Also, if this is agreed to be the "right" way to run typecheck then maybe we should change the defaults there? (i.e., not default to all platforms and all files)

Yeah, originally this tool aspired to be generic for re-use in other projects (After eliminating some minor kubernetes related workarounds) but we have no intention of doing that at this point.

**Comment by liggitt** [comment]
this PR let https://github.com/kubernetes/kubernetes/pull/122373 merge, which breaks local-up-cluster on darwin

**Comment by liggitt** [comment]
Proposed a revert in https://github.com/kubernetes/kubernetes/pull/122878
