### PR TITLE
Fixed subpath cleanup when /var/lib/kubelet is a symlink.

### LINKED ISSUE #68740: Pods stuck in Terminating status  when subpath volume is used
This is related to #65879 and #51835, but these issues contain several different bugs, so I am creating a new one.


**Steps to reproduce**:
1. `/var/lib/kubelet` must be a symlink somewhere else. If you don't have a symlink, then it's a different bug.

2. Run a pod with ConfigMap volume with SubPath:

```
$ kubectl create configmap my-config --from-literal=key1=config1 --from-literal=key2=config2

$ kubectl create -f - <<EOF                                                                                                                                                                                                                                                                                 
apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    name: test
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  containers:
    - image: gcr.io/google_containers/busybox
      command:
        - "/bin/sleep"
        - "10000"
      name: busybox
      volumeMounts:
        - name: vol
          mountPath: /mnt/test
          subPath: key1
  volumes:
      - name: vol
        configMap:
          name: my-config
EOF
```
3. (the pod should run just fine)
4. `kubectl delete pod`

-> The pod is Terminating forever

From the logs:

```
I0917 14:14:24.232902   16796 mount_linux.go:874] Cleaning up subpath mounts for /var/lib/kubelet/pods/eea7fdf2-ba83-11e8-983c-0800272fef8f/volume-subpaths/default-token-lsnlq
I0917 14:14:24.232923   16796 mount_linux.go:889] Cleaning up subpath mounts for container busybox
I0917 14:14:24.232997   16796 util.go:727] Tearing down volume default-token-lsnlq for pod eea7fdf2-ba83-11e8-983c-0800272fef8f at /var/lib/kubelet/pods/eea7fdf2-ba83-11e8-983c-0800272fef8f/volumes/kubernetes.io~secret/default-token-lsnlq
I0917 14:14:24.233015   16796 mount_linux.go:926] Cleaning up subpath mounts for subpath 0
E0917 14:14:24.235137   16796 nestedpendingoperations.go:267] Operation for "\"kubernetes.io/configmap/eea7fdf2-ba83-11e8-983c-0800272fef8f-vol\" (\"eea7fdf2-ba83-11e8-983c-0800272fef8f\")" failed. No retries permitted until 2018-09-17 14:14:24.734991273 +0000 UTC m=+321.207433155 (durationBeforeRetry 500ms). Error: "error cleaning subPath mounts for volume \"vol\" (UniqueName: \"kubernetes.io/configmap/eea7fdf2-ba83-11e8-983c-0800272fef8f-vol\") pod \"eea7fdf2-ba83-11e8-983c-0800272fef8f\" (UID: \"eea7fdf2-ba83-11e8-983c-0800272fef8f\") : error deleting /var/lib/kubelet/pods/eea7fdf2-ba83-11e8-983c-0800272fef8f/volume-subpaths/vol/busybox/0: remove /var/lib/kubelet/pods/eea7fdf2-ba83-11e8-983c-0800272fef8f/volume-subpaths/vol/busybox/0: device or resource busy"
```

You can see there is no "Unmounting /var/lib/kubelet/pods/eea7fdf2-ba83-11e8-983c-0800272fef8f/volume-subpaths/vol/busybox/0", so kubelet did not even try to unmount it.

**Environment**:
- Kubernetes version 1.9.x (and today's master).

/kind bug
/sig storage
@msau42, another subpath bug :-)

### PR DESCRIPTION
**Pull request by jsafrane**
**What this PR does / why we need it**:
kubelet should resolve symlinks before checking /proc/mounts or /proc/1/mountinfo, just in case /var/lib/kubelet itself is a symlink, 

Fixes #68740

**Release note**:

```release-note
Fixed pod cleanup when /var/lib/kubelet is a symlink.
```

/sig storage
@cofyc @msau42 @gnufied PTAL

### CODE REVIEW

File: pkg/util/mount/mount.go [hunk 1]
```diff
@@ -274,7 +279,7 @@ func IsNotMountPoint(mounter Interface, file string) (bool, error) {
 		return notMnt, mountPointsErr
 	}
 	for _, mp := range mountPoints {
-		if mounter.IsMountPointMatch(mp, file) {
+		if mounter.IsMountPointMatch(mp, resolvedFile) {
```
Comment (gnufied) [inline pkg/util/mount/mount.go]: err - tests may be?

Comment (jsafrane) [reply pkg/util/mount/mount.go]: That's the problematic part. e2e test would require changing /var/lib/kubelet into a symlink somehow.

**Comment by jsafrane** [comment]
I can see bunch of subpath tests failing, will investigate tomorrow.

File: pkg/util/mount/mount.go (hunk 1 above)
Comment (gnufied) [reply pkg/util/mount/mount.go]: Can we not write/update unit test for `IsNotMountPoint`, so as it considers symbolic links properly?

File: pkg/util/mount/mount.go [hunk 2]
```diff
@@ -251,9 +251,14 @@ func GetDeviceNameFromMount(mounter Interface, mountPath string) (string, int, e
 // It is more extensive than IsLikelyNotMountPoint
 // and it detects bind mounts in linux
 func IsNotMountPoint(mounter Interface, file string) (bool, error) {
+	// Resolve any symlinks in file, kernel would do the same and use the resolved path in /proc/mounts
+	resolvedFile, err := mounter.EvalHostSymlinks(file)
+	if err != nil {
+		return false, err
```
[the remark this answers is not in the document]
Comment (jsafrane) [reply pkg/util/mount/mount.go]: You're right, fixed.

I wonder why some code checks the returned bool without checking `err`...

File: pkg/util/mount/mount.go (hunk 1 above)
Comment (jsafrane) [reply pkg/util/mount/mount.go]: Proper IsNotMountPoint unit test would require mounting / bind-mounting stuff, which is impossible in an unit test. I could fake all this, but then it would just test very little piece of code and I don't think it's worth all the effort.

**Comment by jsafrane** [comment]
@saad-ali, this is a bugfix, can we get it into 1.12?

**Comment by dims** [comment]
cc @tpepper @guineveresaenger

**Comment by msau42** [comment]
Is this a 1.12 regression?

**Comment by jsafrane** [comment]
It's not 1.12 regression, it was broken by our security subpath patches in all branches.
