### PR TITLE
kubeadm: Utilize transport defaults from API machinery for http calls inside kubeadm

### LINKED ISSUE #324: Where does kubeadm take the proxy settings from?
It's not /etc/environment, it's not the current bash session that kubeadm is running in, it's not docker or kubelet environment. I verified this by setting `no_proxy` to a different value in all these instances. And for some reason after a `kubeadm init` it still continues to set another value for `no_proxy`. Restart, daemon-reload, restarting the services all doesn't change that fact.

Honestly it's really annoying that it only prints the line "the ip address fo.oo.ba.rr has a proxy set to blubb" instead of saying where it takes the value from. And why doesn't it simply read the value from /etc/environment, which is the one true source of truth when it comes to proxy setting, or the current bash session in which I call `kubeadm` which is the easiest place to make changes to?

What I expect would be something like this:

 1. kubeadm checks the current env variable `http_proxy`. (or `https_proxy` if secure communication is configured)
 1. kubeadm checks the current env variable `HTTP_PROXY` and **warns** if it is different.
 1. kubeadm checks `http_proxy` in /etc/environment. It **warns** if it is different.
 1. similar for upper case.
 1. if there is neither variable in neither context it assumes there is no proxy and **informs** about it.
 1. kubeadm writes the manifest files (I assume this is done before creating the docker containers) with the given proxy, giving preference to the process environment setting in lower case, then upper case, then lower case /etc/environment, then upper case /etc/environment.
 1. kubeadm starts the pods.
 1. kubeadm checks whether the controller-manager can talk to the api server. If it gets a "forbidden" or "timeout" it assumes the proxy settings are wrong and **erros**, calling a `kubeadm reset` internally.
 1. there is no event where it just waits forever without any output. It can at least reasonably well figure out if there are continuous errors in the logs of api-server and controller-manager, as well as whether there are any new logs for >= 10 minutes. And then it can error out with a corresponding error message.
 1. kubeadm internally **pre**pends the advertise address to all `no_proxy` settings (add the end it may get cut of). <-- Also it would be so much better to use a hostname if possible, since `no_proxy` is actually meant for names, not IPs.

I seriously can't express how many working hours it would save people in enterprise networks.

### PR DESCRIPTION
**Pull request by kad**
**What this PR does / why we need it**:
Default Go HTTP transport does not allow to use CIDR notations in
NO_PROXY variables, thus for certain HTTP calls that is done inside
kubeadm user needs to put explicitly multiple IP addresses. For most of
calls done via API machinery it is get solved by setting different Proxy
resolver. This patch allows to use CIDR notations in NO_PROXY variables
for currently all other HTTP calls that is made inside kubeadm.

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes kubernetes/kubeadm#324

**Special notes for your reviewer**:
Based on discussion in #52788, replacing this patch replacing all calls inside kubeadm that are done via DefaultTransport to explicitly defined and initialized with API machinery defaults Transport and http client.

**Release note**:
```release-note
- kubeadm now supports CIDR notations in NO_PROXY environment variable
```

### CODE REVIEW

**Comment by kad** [comment]
@luxas @liggitt please have a look at this PR as a replacement for opposed #52788

File: cmd/kubeadm/app/discovery/https/https.go [hunk 1]
```diff
@@ -29,7 +30,8 @@ import (
 // securely to the API Server using the provided CA cert and
 // optionally refreshes the cluster-info information from the cluster-info ConfigMap
 func RetrieveValidatedClusterInfo(httpsURL string) (*clientcmdapi.Cluster, error) {
-	response, err := http.Get(httpsURL)
+	client := &http.Client{Transport: netutil.SetOldTransportDefaults(&http.Transport{})}
```
Comment (liggitt) [inline cmd/kubeadm/app/discovery/https/https.go]: why not `SetTransportDefaults`?

**Comment by liggitt** [comment]
could have a kubeadm default client constructed using the cidr-supporting no-proxy rather than constructing one-off clients all over the place

also, is there a reason not to use `SetTransportDefaults`?

lgtm otherwise

File: cmd/kubeadm/app/discovery/https/https.go (hunk 1 above)
Comment (kad) [reply cmd/kubeadm/app/discovery/https/https.go]: SetTransportDefaults does http2 initialization, which in most cases here is not expected.
Even SetOldTransportDefaults does a bit more than expected, but setting defaults for Dialer and TLSHandshakeTimeout is safe enough to not be worried about.

**Comment by kad** [comment]
@liggitt regarding sharing one client: we have in places like etcd connection different settings for client applied (tls, timeouts). In all other places, I  think it is better for now keep as it is, rather than introduce global variable for kubeadm that would keep once constructed client.

**Comment by luxas** [comment]
@liggitt deferring this to your assessment

**Comment by kad** [comment]
@liggitt ping

**Comment by liggitt** [comment]
I think construction of ad-hoc clients throughout kubeadm, and use of SetOldTransportDefaults should be revisited, but this is a strict improvement over what currently exists

/lgtm

**Review by timothysc — APPROVED** [review]
/approve
