### PR TITLE
kubeadm: set pod-infra-container-image for the kubelet

### LINKED ISSUE #1003: kubeadm pulls pause on update and setup ignoring imageRepository: in config file
## What keywords did you search in kubeadm issues before filing this one?
pause
imageRepository

## Versions

**kubeadm version** (use `kubeadm version`): 1.11.0

**Environment**:
- **Kubernetes version** (use `kubectl version`): 1.11
- **Cloud provider or hardware configuration**:
- **OS** (e.g. from /etc/os-release):
- **Kernel** (e.g. `uname -a`):
- **Others**:

## What happened?
Setting up the cluster with config file and the following tag:
imageRepository: privateRegistry:5000/google-containers
worked except the pause image is always pulled from k8s.gcr.io/pause, ignoring the setting.
We set up the system by manually pulling pause (1.10 needs the pause-amd64:3.1) and retag it acoordingly.

We upgraded the cluster from 1.10 to 1.11 and had the same issue. The upgrade fails because pause can not be pulled. After pulling manually from privateRegistry:5000/pause:3.1 and retagging it to k8s.gcr.io:pause3.1, the controlplane comes up again.

So kubeadm does not respect the imageRepository, using private or proxy registries, regarding the pause image.

## What you expected to happen?
Using the proper configured image registry

## How to reproduce it (as minimally and precisely as possible)?
Try to set up k8s with kubeadm from private registry, using the imageRepository Tag

### PR DESCRIPTION
**Pull request by chuckha**
The kubelet allows you to set `--pod-infra-container-image`
(also called `PodSandboxImage` in the kubelet config),
which can be a custom location to the "pause" image in the case
of Docker. Other CRIs are not supported.

Set the CLI flag for the Docker case in flags.go using
WriteKubeletDynamicEnvFile().

This PR also cleans up some unwrapped errors.

**What type of PR is this?**
> Uncomment only one, leave it on its own line:
>
> /kind api-change
/kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:
This PR properly allows image repository to be passed to the kubelet for the sandbox image.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes kubernetes/kubeadm#1003

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Kubeadm now respects the custom image registry configuration across joins and upgrades. Kubeadm passes the custom registry to the kubelet for a custom pause container.
```

### CODE REVIEW

**Comment by chuckha** [comment]
/priority critical-urgent

(copying prio from bug https://github.com/kubernetes/kubeadm/issues/1003)

**Comment by chuckha** [comment]
docker images after an init:

```
812083501456.dkr.ecr.us-west-2.amazonaws.com/kube-proxy                v1.12.2             15e9da1ca195        9 days ago          96.5MB
812083501456.dkr.ecr.us-west-2.amazonaws.com/kube-apiserver            v1.12.2             51a9c329b7c5        9 days ago          194MB
812083501456.dkr.ecr.us-west-2.amazonaws.com/kube-controller-manager   v1.12.2             15548c720a70        9 days ago          164MB
812083501456.dkr.ecr.us-west-2.amazonaws.com/etcd                      3.2.24              3cab8e1b9802        6 weeks ago         220MB
812083501456.dkr.ecr.us-west-2.amazonaws.com/pause                     3.1                 da86e6ba6ca1        10 months ago       742kB
```

docker images after a join:
```
812083501456.dkr.ecr.us-west-2.amazonaws.com/pause        3.1                 da86e6ba6ca1        10 months ago       742kB
```

File: cmd/kubeadm/app/constants/constants.go [hunk 1]
```diff
@@ -250,6 +250,9 @@ const (
 	// PauseVersion indicates the default pause image version for kubeadm
 	PauseVersion = "3.1"
 
+	// DefaultPauseImageVersion indicates the default version for the pause image
+	DefaultPauseImageVersion = "3.1"
```
Comment (neolit123) [inline cmd/kubeadm/app/constants/constants.go]: seems to be duplicate of the above PauseVersion constant.

File: cmd/kubeadm/app/images/images_test.go [hunk 2]
```diff
@@ -128,6 +128,34 @@ func TestGetEtcdImage(t *testing.T) {
...
+		name     string
+		cfg      *kubeadmapi.ClusterConfiguration
+		expected string
+	}{
+		{
+			name: "pause image defined",
+			cfg: &kubeadmapi.ClusterConfiguration{
+				ImageRepository: "test.repo",
+			},
+			expected: "test.repo/pause:" + constants.DefaultPauseImageVersion,
```
Comment (neolit123) [inline cmd/kubeadm/app/images/images_test.go]: probably should be PauseVersion. same as GetPauseImage().

File: cmd/kubeadm/app/util/config/cluster.go [hunk 3]
```diff
@@ -93,7 +91,7 @@ func getInitConfigurationFromCluster(kubeconfigDir string, client clientset.Inte
 	// Also, the config map really should be KubeadmConfigConfigMap...
 	configMap, err := client.CoreV1().ConfigMaps(metav1.NamespaceSystem).Get(constants.KubeadmConfigConfigMap, metav1.GetOptions{})
 	if err != nil {
-		return nil, err
+		return nil, errors.Wrap(err, "failed to get config map")
```
Comment (neolit123) [inline cmd/kubeadm/app/util/config/cluster.go]: these Wrap calls are possibly outside of the scope of the PR?
but SGTM still.

File: cmd/kubeadm/app/cmd/phases/kubelet.go [hunk 4]
```diff
@@ -96,7 +97,8 @@ func runKubeletStart(c workflow.RunData) error {
 	// Write env file with flags for the kubelet to use. We do not need to write the --register-with-taints for the master,
 	// as we handle that ourselves in the markmaster phase
 	// TODO: Maybe we want to do that some time in the future, in order to remove some logic from the markmaster phase?
-	if err := kubeletphase.WriteKubeletDynamicEnvFile(&data.Cfg().NodeRegistration, data.Cfg().FeatureGates, false, data.KubeletDir()); err != nil {
+	pauseImage := images.GetPauseImage(data.Cfg().ClusterConfiguration.ImageRepository)
+	if err := kubeletphase.WriteKubeletDynamicEnvFile(&data.Cfg().NodeRegistration, data.Cfg().FeatureGates, pauseImage, false, data.KubeletDir()); err != nil {
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/phases/kubelet.go]: something that @rosti suggested was suggested in the original PR was that we should pass ClusterConfiguration instead of feature gates and pause image to WriteKubeletDynamicEnvFile:
https://github.com/kubernetes/kubernetes/pull/66798/files#r206508620

File: cmd/kubeadm/app/phases/kubelet/flags.go [hunk 5]
```diff
@@ -56,6 +57,7 @@ func WriteKubeletDynamicEnvFile(nodeRegOpts *kubeadmapi.NodeRegistrationOptions,
 	flagOpts := kubeletFlagsOpts{
 		nodeRegOpts:              nodeRegOpts,
 		featureGates:             featureGates,
+		pauseImage:               pauseImage,
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/kubelet/flags.go]: i guess we can keep featureGates and pauseImage as part of kubeletFlagsOpts, but obtain them from a ClusterConfiguration argument.

**Review by neolit123 — APPROVED** [review]
@chuckha thank you fixing this.
added a couple of comments about possible small changes.

File: cmd/kubeadm/app/images/images.go [hunk 6]
```diff
@@ -53,16 +53,19 @@ func GetEtcdImage(cfg *kubeadmapi.ClusterConfiguration) string {
 	return GetGenericImage(cfg.ImageRepository, constants.Etcd, etcdImageTag)
 }
 
+// GetPauseImage returns the image for the "pause" container
+func GetPauseImage(registry string) string {
```
Comment (rosti) [inline cmd/kubeadm/app/images/images.go]: My vision for the funcs in the images files is for them to take `ClusterConfiguration` and then figure out from there how to generate the image string. This way we can keep future changes to the way we generate the images to this file only.
I know, that this will look like an overkill for `GetPauseImage`, but I think, that this may have benefits in the future and will keep things consistent with the rest of the bunch here.

File: cmd/kubeadm/app/cmd/phases/kubelet.go (hunk 4 above)
Comment (rosti) [reply cmd/kubeadm/app/cmd/phases/kubelet.go]: In fact, we can replace the first three parameters with `InitConfiguration` here and move the `GetPauseImage` call to `WriteKubeletDynamicEnvFile`. This will have the benefit of tidying up the code and removing duplicate logic between here and `postupgrade.go`

**Review by rosti — COMMENTED** [review]
Overall looks OK. A few `errors.Wrap` and some empty lines removed from imports look like not belonging to this change.

**Comment by chuckha** [comment]
I'm not sure why github is still showing me the outdated comments but I think this is ready for another review @rosti @neolit123.

**Comment by neolit123** [comment]
> cmd/kubeadm/app/images/images_test.go:147:28: cannot use tc.cfg.ImageRepository (variable of type string) as *k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm.ClusterConfiguration value in argument to GetPauseImage

images_test needs an update.

**Review by neolit123 — APPROVED** [review]
thanks for the update @chuckha 
LGTM added one minor comment to fix CI.

**Comment by chuckha** [comment]
/test pull-kubernetes-integration
--

File: cmd/kubeadm/app/util/config/cluster.go (hunk 3 above)
Comment (timothysc) [reply cmd/kubeadm/app/util/config/cluster.go]: I will never complain about this...

**Review by timothysc — APPROVED** [review]
Nice work! 
/lgtm 
/approve

**Comment by chuckha** [comment]
@timothysc updated

**Comment by kevinbin** [comment]
not support contained CRI?

**Comment by rosti** [comment]
> not support contained CRI?

Currently, this option is only for Docker. If you use any other CRI you have to check with its documentation and pass an equivalent option manually.
