### PR TITLE
Get recent

### LINKED ISSUE #6537: Elasticsearch e2e test fails consistently due to duplicate log entries
e.g. http://kubekins.dls.corp.google.com/job/kubernetes-e2e-gce/4289/

### PR DESCRIPTION
**Pull request by yifan-gu**
Second take to fix #6537 caused by #6470

```
Ran 31 of 37 Specs in 1211.174 seconds
SUCCESS! -- 31 Passed | 0 Failed | 1 Pending | 5 Skipped watchEvents output: |
  Project: robust-chess-87305
  Zone: us-central1-b
  current-context: "robust-chess-87305_e2e-test-yifan"
```

@vmarmol @yujuhong @quinton-hoole

### CODE REVIEW

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -1114,15 +1118,20 @@ func (kl *Kubelet) computePodContainerChanges(pod *api.Pod, runningPod kubeconta
...
-		if err != nil {
-			glog.Errorf("Unable to get pod with name %q and uid %q info with error(%v)", podFullName, uid, err)
-		}
+
 	} else {
 		glog.V(2).Infof("No Infra Container for %q found. All containers will be restarted.", podFullName)
 		createPodInfraContainer = true
 	}
 
+	// Not use the cache here since we need the newest status to check
```
Comment (vmarmol) [inline pkg/kubelet/kubelet.go]: nit: "Do not use"...

File: pkg/kubelet/dockertools/fake_docker_client.go [hunk 2]
```diff
@@ -67,17 +68,51 @@ func (f *FakeDockerClient) AssertCalls(calls []string) (err error) {
 	return
 }
 
+func (f *FakeDockerClient) AssertCreated(created []string) error {
+	f.Lock()
+	defer f.Unlock()
+
+	if len(created) != len(f.Created) {
+		return fmt.Errorf("expected %d created, got %d", len(created), len(f.Created))
```
Comment (vmarmol) [inline pkg/kubelet/dockertools/fake_docker_client.go]: Lets also print the expected and actual slices

File: pkg/kubelet/kubelet_test.go [hunk 3]
```diff
@@ -3476,3 +3486,256 @@ func TestHostNetworkDisallowed(t *testing.T) {
...
+		{
+			// pod infra container
+			Names: []string{"/k8s_POD_foo_new_12345678_0"},
+			ID:    "9876",
+		},
+	}
+	fakeDocker.ExitedContainerList = []docker.APIContainers{
+		{
+			// format is // k8s_<container-id>_<pod-fullname>_<pod-uid>
+			Names: []string{"/k8s_succeeded." + strconv.FormatUint(dockertools.HashContainer(&containers[0]), 16) + "_foo_new_12345678_0"},
```
Comment (vmarmol) [inline pkg/kubelet/kubelet_test.go]: unrelated to PR and no action required: We really do need to make these types of objects easier to make...I think @yujuhong has filed something along those lines before.

File: pkg/kubelet/kubelet_test.go [hunk 4]
```diff
@@ -3476,3 +3486,256 @@ func TestHostNetworkDisallowed(t *testing.T) {
 		t.Errorf("expected pod infra creation to fail")
 	}
 }
+
+func TestSyncPodsWithRestartAlways(t *testing.T) {
```
Comment (vmarmol) [inline pkg/kubelet/kubelet_test.go]: We can probably parametrize these 3 tests and save on much of the boilerplate.

**Comment by vmarmol** [comment]
LGTM overall. Thanks for the tests!

@yujuhong PTAL if you have time.

**Comment by yifan-gu** [comment]
@vmarmol Merged into 1 test.

**Comment by vmarmol** [comment]
LGTM, thanks @yifan-gu!

**Comment by yifan-gu** [comment]
@vmarmol I am running e2e again. Please wait for my report :)

**Comment by yujuhong** [comment]
LGTM overall. Thanks for fixing this!

File: pkg/kubelet/kubelet_test.go [hunk 5]
```diff
@@ -3476,3 +3486,122 @@ func TestHostNetworkDisallowed(t *testing.T) {
...
+		},
+		{
+			api.RestartPolicyOnFailure,
+			[]string{"list", "list", "list", "inspect_container", "inspect_container", "inspect_container", "create", "start", "list", "inspect_container", "inspect_container", "inspect_container"},
+			[]string{"failed"},
+			[]string{},
+		},
+		{
+			api.RestartPolicyNever,
+			[]string{"list", "list", "list", "inspect_container", "inspect_container", "inspect_container", "stop", "list", "inspect_container", "inspect_container"},
```
Comment (yujuhong) [inline pkg/kubelet/kubelet_test.go]: Not really related to this PR. It'd be nice if we can minimize having to list every call to the fake docker client in so many tests. We need some intermediate level functions to verify the function calls, and we should in general try testing the higher-level function in kubelet_test.go and leave the rest to dockertools unit tests. That's why I suggested integration tests to begin with, but I'm happy that we finally have some tests for restart policies here :)

Comment (vmarmol) [inline pkg/kubelet/kubelet_test.go]: +1 these are such a pain and don't bring us much value.

**Comment by vmarmol** [comment]
@yifan-gu will wait on your green light

File: pkg/kubelet/kubelet_test.go (hunk 5 above)
Comment (yifan-gu) [inline pkg/kubelet/kubelet_test.go]: I am trying to add an integration test in following pr.

**Comment by yifan-gu** [comment]
@vmarmol 
```
Ran 33 of 39 Specs in 1252.259 seconds
SUCCESS! -- 33 Passed | 0 Failed | 1 Pending | 5 Skipped watchEvents output: |
  Project: robust-chess-87305
  Zone: us-central1-b
  current-context: "robust-chess-87305_e2e-test-yifan"
  Running: /home/yifan/another_gopher/src/github.com/GoogleCloudPlatform/kubernetes/cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/linux/amd64/kubectl --match-server-version get events --watch-only

```

**Comment by vmarmol** [comment]
Thanks @yifan-gu! Will wait for CIs.

**Comment by vmarmol** [comment]
Travis is green, merging.

File: pkg/kubelet/kubelet_test.go (hunk 5 above)
Comment (yifan-gu) [inline pkg/kubelet/kubelet_test.go]: Think the unit test is fine now since integration test also uses the fake docker.
But we should definitely figure out these painful verifyCall stuff. Maybe reduce the types of function calls by using fake container runtime will help somehow...
