### PR TITLE
Fix rolling-update rollback from an unavailable rc

### LINKED ISSUE #18530: Rolling update can't rollback with only 1 replica
I intentionally cause the rolling update to fail by specifying a non-existent image in the spec, so that it times out.

```
kubectl rolling-update copper -f iron.yml --update-period=1s --timeout=30s
error: timed out waiting for any update progress to be made

Created iron
Scaling up iron from 0 to 1, scaling down copper from 1 to 0 (keep 1 pods available, don't exceed 2 pods)
Scaling iron up to 1
```

rollback then fails with a timeout as well, despite the original replication controller having 1 healthy replica:

```
kubectl rolling-update copper -f iron.yml --update-period=1s --timeout=30s --rollback
error: timed out waiting for any update progress to be made

Setting "copper" replicas to 1
Continuing update with existing controller copper.
Scaling up copper from 1 to 1, scaling down iron from 1 to 0 (keep 1 pods available, don't exceed 2 pods)
```

This is on 1.1.2. I expect the rollback to succeed as the original rc (copper) has 1 healthy replica still.

### PR DESCRIPTION
**Pull request by jsravn**
Rolling back from a broken update with only one replica fails with a
timeout in the existing code.

The problem is the scale down logic does not consider unavailable
replicas in the old replication controller when calculating how much to
scale down by. This leads to an obvious problem with a single replica
when min unavailable is 1.

The fix is to allow scaling down all unavailable replicas in the old
controller, while still maintaining the min unavailable invariant.

Fix #18530

### CODE REVIEW

**Comment by jlowdermilk** [comment]
@k8s-bot ok to test

File: pkg/kubectl/rolling_updater.go [hunk 1]
```diff
@@ -306,8 +306,9 @@ func (r *RollingUpdater) scaleDown(newRc, oldRc *api.ReplicationController, desi
 	}
 	// The old controller is considered as part of the total because we want to
 	// maintain minimum availability even with a volatile old controller.
-	// Scale down as much as possible while maintaining minimum availability.
-	decrement := (oldAvailable + newAvailable) - minAvailable
+	// Scale down as much as possible while maintaining minimum availability
+	unavailableOldReplicas := oldRc.Spec.Replicas - oldAvailable
+	decrement := unavailableOldReplicas + (oldAvailable + newAvailable) - minAvailable
```
Comment (jlowdermilk) [inline pkg/kubectl/rolling_updater.go]: Should this just be `oldRc.Spec.Replicas + newAvailable - minAvailable`? The math is the same.

**Comment by jlowdermilk** [comment]
Thanks for the pr @jsravn. cc @ironcladlou

**Comment by jsravn** [comment]
@jlowdermilk I made the recommended change.

File: pkg/kubectl/rolling_updater_test.go [hunk 2]
```diff
@@ -692,6 +693,45 @@ func TestUpdate_progressTimeout(t *testing.T) {
 	}
 }
 
+func TestUpdate_canRollbackFromAFailedRcToAReadyRc(t *testing.T) {
```
Comment (ironcladlou) [inline pkg/kubectl/rolling_updater_test.go]: Were you unable to express this as a scenario in `TestUpdate`?

Comment (jsravn) [inline pkg/kubectl/rolling_updater_test.go]: I'll take a look. I assume it can't be because the test above it, `TestUpdate_progressTimeout`, is also a timeout scenario and not part of `TestUpdate`.

**Comment by jsravn** [comment]
@ironcladlou Made the change, thanks.

**Comment by ironcladlou** [comment]
@jsravn 
>Made the change, thanks.

Awesome, thank you!

**Comment by ironcladlou** [comment]
This lgtm

**Comment by jlowdermilk** [comment]
@jsravn, please squash commits.

**Comment by jsravn** [comment]
@jlowdermilk Squashed them.

**Comment by jlowdermilk** [comment]
Thanks, lgtm.

**Comment by nikhiljindal** [comment]
Thanks for fixing this @jsravn!
I think it will be good to cherrypick this in 1.1.
Can you please send a cherrypick request?
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/cherry-picks.md has the details.

**Comment by jsravn** [comment]
Will do.
