### PR TITLE
Validate minimum CPU limits to be >= 10m

### LINKED ISSUE #23113: Cgroup 'cpu.cfs_quota_us' error on container creation when CPU limit is low
After upgrading my environment from Kubernetes 1.1.8 to Kubernetes 1.2.0, I see pods creation failing with the following resource limits set:

```
        resources:
          limits:
            cpu: 5m
            memory: 25Mi
```

Translated to Docker container info:

| 1.1.8 | 1.2.0 |
| --- | --- |
| "Memory": 26214400, | "Memory": 26214400, |
| "MemoryReservation": 0, | "MemoryReservation": 0, |
| "CpuShares": 5, | "CpuShares": 5, |
| "CpuPeriod": 0, | "CpuPeriod": 100000, |
| "CpuQuota": 0, | "CpuQuota": 500, |

The error message is:

```
Cannot start container <sha>: [9] System error: write /sys/fs/cgroup/cpu,cpuacct/system.slice/docker-<sha>.scope/cpu.cfs_quota_us: invalid argument
```

I can reproduce this by creating containers manually:

```
$ docker run --rm --cpu-shares=5 --cpu-quota=0 --cpu-period=0 tianon/true
[exit code 0]
$ docker run --rm --cpu-shares=5 --cpu-quota=500 --cpu-period=100000 tianon/true
docker: Error response from daemon: Cannot start container <sha>: [9] System error: write /sys/fs/cgroup/cpu,cpuacct/docker/<sha>/cpu.cfs_quota_us: invalid argument.
[exit code 125]
```

Kubernetes should check that the defined CPU restrictions are valid before attempting to create containers.

### PR DESCRIPTION
**Pull request by vishh**
- Make kubelet default to 10ms for CPU quota if limit < 10m for
  backwards compat.
- Update documentation

Fixes #23113 

cc @bgrant0607

### CODE REVIEW

**Comment by vishh** [comment]
@k8s-bot test node e2e experimental

**Comment by vishh** [comment]
cc @derekwaynecarr @mrunalp

**Comment by mrunalp** [comment]
@vishh Not sure if you are allowing users to modify the period as it needs the same check, too.

File: pkg/api/validation/validation.go [hunk 1]
```diff
@@ -2346,6 +2356,7 @@ func ValidateResourceRequirements(requirements *api.ResourceRequirements, fldPat
 		if api.IsStandardResourceName(string(resourceName)) {
 			allErrs = append(allErrs, validateBasicResource(quantity, fldPath.Key(string(resourceName)))...)
 		}
+		allErrs = append(allErrs, validateContainerResourceLimits(string(resourceName), quantity, fldPath)...)
```
Comment (derekwaynecarr) [inline pkg/api/validation/validation.go]: I don't think this is right.

I agree we should check that you can't have a quota on limits.cpu that is < 10m, but this is not that...
I also think we should check in LimitRange validation that max[cpu] and default[cpu] cannot be < 10m.

**Comment by derekwaynecarr** [comment]
@mrunalp the period is fixed.

**Comment by mrunalp** [comment]
@derekwaynecarr Ack. The only thing that we really need to ensure is that neither are set to less than 1000 as final values.

File: pkg/api/validation/validation.go (hunk 1 above)
Comment (vishh) [inline pkg/api/validation/validation.go]: @derekwaynecarr: Are you suggesting disabling quota if limits < 10m?
I can add validation to limit ranges in this PR. Good point.

**Comment by vishh** [comment]
@derekwaynecarr: Chatted with @bgrant0607 offline. He suggested skipping the validation part since it is not worth the pain that validation will bring in - existing RCs might fail to work. The values we are dealing with is practically so small that just defaulting at the node is good enough.

PTAL.!

**Comment by vishh** [comment]
@k8s-bot test node e2e experimental

**Comment by derekwaynecarr** [comment]
This is LGTM to me as well
