### PR TITLE
Use multiple clients in load test to avoid "no cached connections" er…

### LINKED ISSUE #33711: [k8s.io] Load capacity [Feature:Performance] should be able to handle 30 pods per node {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-kubemark-500-gce/6275/

Failed: [k8s.io] Load capacity [Feature:Performance] should be able to handle 30 pods per node {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:206
scaling rc load-medium-rc-72 for the first time
Expected error:
    <*errors.errorString | 0xc82d911380>: {
        s: "error while scaling RC load-medium-rc-72 to 23 replicas: Scaling the resource failed with: Get https://104.197.104.157/api/v1/namespaces/e2e-tests-load-30-nodepods-3-7ya8x/replicationcontrollers/load-medium-rc-72: http2: no cached connection was available; Current resource version Unknown",
    }
    error while scaling RC load-medium-rc-72 to 23 replicas: Scaling the resource failed with: Get https://104.197.104.157/api/v1/namespaces/e2e-tests-load-30-nodepods-3-7ya8x/replicationcontrollers/load-medium-rc-72: http2: no cached connection was available; Current resource version Unknown
not to have occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/load.go:327
```

Previous issues for this test: #26544 #26938 #27595 #30146 #30469 #31374 #31427 #31433 #31589 #31981 #32257

### PR DESCRIPTION
**Pull request by wojtek-t**
Fix #33711

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/33733)

### CODE REVIEW

**Comment by gmarek** [comment]
Discussed IRL. We need to figure out how to don't share a transport between clients and change the logic from client per X nodes, to client per X controllers

**Comment by wojtek-t** [comment]
@gmarek - it should work now; PTAL;

**Comment by wojtek-t** [comment]
@timothysc - FYI

File: test/e2e/load.go [hunk 1]
```diff
@@ -218,6 +223,54 @@ func createNamespaces(f *framework.Framework, nodeCount, podsPerNode int) []*api
...
+			MaxIdleConnsPerHost: 100,
+			Dial: (&net.Dialer{
+				Timeout:   30 * time.Second,
+				KeepAlive: 30 * time.Second,
+			}).Dial,
+		})
+		// Overwrite TLS-related fields from config to avoid collision with
+		// Transport field.
+		config.TLSClientConfig = restclient.TLSClientConfig{}
+
```
Comment (gmarek) [inline test/e2e/load.go]: remove empty line

Comment (wojtek-t) [inline test/e2e/load.go]: done

Comment (wojtek-t) [inline test/e2e/load.go]: [this was a debug log - removed it]

File: test/e2e/load.go [hunk 2]
```diff
@@ -232,22 +285,30 @@ func computeRCCounts(total int) (int, int, int) {
...
 	configs := make([]*framework.RCConfig, 0)
 
 	smallRCCount, mediumRCCount, bigRCCount := computeRCCounts(totalPods)
-	configs = append(configs, generateRCConfigsForGroup(c, nss, smallRCGroupName, smallRCSize, smallRCCount, image, command)...)
-	configs = append(configs, generateRCConfigsForGroup(c, nss, mediumRCGroupName, mediumRCSize, mediumRCCount, image, command)...)
-	configs = append(configs, generateRCConfigsForGroup(c, nss, bigRCGroupName, bigRCSize, bigRCCount, image, command)...)
+
+	// Create a number of clients to better simulate real usecase
+	// where not everyone is using exactly the same client.
+	clients, err := createClients((smallRCCount + 19) / 20)
```
Comment (gmarek) [inline test/e2e/load.go]: why not create a constant `rcsPerClient` and have `(smallRCCount + mediumRCCount + bigRCCount + rcsPerClient - 1) / rcsPerClient` to make it configurable. Also this will make the math easier, as each of those clients will issue the same number of mutating requests.

Comment (wojtek-t) [inline test/e2e/load.go]: summing up small + medium + big doesn't make much sense, since we won't use more than first "small" anyway (those arrays are separate, so it will require changing other things, which would be unnecessary complication in my opinion).

Introduced constant.1

Comment (gmarek) [inline test/e2e/load.go]: I don't really understand 'separate arrays' comment. IIUC load test first generates all configs for small, medium and large RCs and append them together (`generateRCConfigs` function). Then we pass this single slice of configs to `createAllRC` that basically goes through it and for each config starts a goroutine.

Comment (wojtek-t) [inline test/e2e/load.go]: Yeah - but you are settig client during generating those configs, and they are generated separately.

Comment (gmarek) [inline test/e2e/load.go]: OK, I understand what you mean now. We might pass an offset to the function to make the client assignment really round-robin. Additional advantage we'd get from this would be that all the clients would be equally loaded (currently ones with smaller indices have more work to do), but it's probably not worth the complication. Add a TODO, or a comment that if someone finds current behavior problematic he should fix this.

Comment (wojtek-t) [inline test/e2e/load.go]: I pushed a new version - hopefully looks better now.
