### PR TITLE
Use monotonically increasing generation to prevent equivalence cache race

### LINKED ISSUE #67260: TestVolumeBindingRescheduling `out of sync; retrying` flakes
seeing `out of sync; retrying` errors in TestVolumeBindingRescheduling:

http://storage.googleapis.com/k8s-metrics/flakes-latest.json shows TestVolumeBindingRescheduling in the top 3 flakes for its job

https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/67207/pull-kubernetes-integration/22583/

```
E0810 14:10:47.907031   30434 factory.go:1409] Error scheduling volume-scheduling1250e95d-9ca7-11e8-ad13-0242ac110002/pod-reschedule-onclassadd-static: v1.PersistentVolume "pv-reschedule-onclassadd-static" is out of sync; retrying
E0810 14:10:47.908643   30434 factory.go:1409] Error scheduling volume-scheduling1250e95d-9ca7-11e8-ad13-0242ac110002/pod-reschedule-onclassadd-static: v1.PersistentVolume "pv-reschedule-onclassadd-static" is out of sync; retrying
E0810 14:10:47.910120   30434 factory.go:1409] Error scheduling volume-scheduling1250e95d-9ca7-11e8-ad13-0242ac110002/pod-reschedule-onclassadd-static: v1.PersistentVolume "pv-reschedule-onclassadd-static" is out of sync; retrying
E0810 14:10:47.912168   30434 factory.go:1409] Error scheduling volume-scheduling1250e95d-9ca7-11e8-ad13-0242ac110002/pod-reschedule-onclassadd-static: v1.PersistentVolume "pv-reschedule-onclassadd-static" is out of sync; retrying
I0810 14:10:47.928002   30434 pv_controller_base.go:287] Shutting down persistent volume controller
I0810 14:10:47.928033   30434 pv_controller_base.go:398] claim worker queue shutting down
I0810 14:10:47.928574   30434 pv_controller_base.go:341] volume worker queue shutting down
--- FAIL: TestVolumeBindingRescheduling (49.76s)
	volume_binding_test.go:344: Failed to schedule Pod "pod-reschedule-onclassadd-static": timed out waiting for the condition
```

@kubernetes/sig-storage-test-failures

### PR DESCRIPTION
**Pull request by cofyc**
**What this PR does / why we need it**:

Use monotonically increasing generation to prevent equivalence cache race.

Because invalidating predicate cache invalidates latest cache, but in-flight predicate goroutines may write stale results into cache. This may happen when events occur frequently:

| objectVersion | invalidation goroutine | predicate goroutine | cacheVersion | status |
| -- | -- | -- | -- | -- |
| v0 -> v1 | cache invalidated | begin to calculate result.v1 | cache.v0 | OK |
| v1 -> v2 | cache invalidated | begin to write result.v1 into cache | no cache | OK |
| v2 |  | result.v1 wrote into cache | cache.v1 | cache mismatch |

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #67260

**Special notes for your reviewer**:

**Release note**:

```release-note
Use monotonically increasing generation to prevent scheduler equivalence cache race.
```

### CODE REVIEW

**Comment by cofyc** [comment]
@kubernetes/sig-scheduling-pr-reviews 
/assign @msau42

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 1]
```diff
@@ -68,12 +68,16 @@ func NewCache() *Cache {
 type NodeCache struct {
 	mu    sync.RWMutex
 	cache predicateMap
+	// Flags which indicate if we received invalidation requests for each
+	// predicate during check was in flight.
+	receivedInvalidatioRequests map[string]bool
```
Comment (yastij) [inline pkg/scheduler/core/equivalence/eqivalence.go]: Rename to `receivedInvalidationRequests`

**Review by yastij — COMMENTED** [review]
Just a nit

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 2]
```diff
@@ -282,6 +291,7 @@ func (n *NodeCache) lookupResult(
 	n.mu.RLock()
 	defer n.mu.RUnlock()
 	value, ok = n.cache[predicateKey][equivalenceHash]
+	delete(n.receivedInvalidatioRequests, predicateKey)
```
Comment (misterikkit) [inline pkg/scheduler/core/equivalence/eqivalence.go]: It seems like anybody who does a lookup will clear the flag for that predicate, causing the next updater to assume that the cache has not been invalidated.

**Comment by misterikkit** [comment]
Hi, have you confirmed that this error can happen? Bonus points if you can add a test that triggers the error.

The reason I ask is that we tried to address this specific problem in https://github.com/kubernetes/kubernetes/pull/63040. Perhaps

/cc @bsalamat

File: pkg/scheduler/core/equivalence/eqivalence.go (hunk 1 above)
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: Fixed.

**Comment by cofyc** [comment]
@misterikkit Add a integration test in e3f6c61d10342cd218f8741ea403bc509c0a98e2.
This test will fail without this feature.

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 3]
```diff
@@ -282,6 +291,7 @@ func (n *NodeCache) lookupResult(
 	n.mu.RLock()
 	defer n.mu.RUnlock()
 	value, ok = n.cache[predicateKey][equivalenceHash]
+	delete(n.receivedInvalidationRequests, predicateKey)
```
Comment (resouer) [inline pkg/scheduler/core/equivalence/eqivalence.go]: `lookupResult` is in the critical path during scheduling, but this delete operation requires `mu.Lock()` instead of `mu.RLock()`.
 
We may need evaluation of performance impact here.

**Comment by misterikkit** [comment]
Just to add some more context, I believe you when you say this is a problem, but I don't believe this PR is the right fix. We tried to fix this exact problem in https://github.com/kubernetes/kubernetes/pull/63040, so my assumption is that something about that fix needs to be corrected.

**Review by misterikkit — COMMENTED** [review]
As I mentioned in other comments, I would like this fix to replace the fix for https://github.com/kubernetes/kubernetes/issues/62921

In particular, I think we should,
- add atomic generation numbers to the eCache
- snapshot the current generation numbers before snapshotting the scheduler cache
- compare generation number in snapshot to the live version before writing to eCache
- "undo" the fix from https://github.com/kubernetes/kubernetes/pull/63040 and https://github.com/kubernetes/kubernetes/pull/63895

Sorry that is a lot more work than your initial approach. Let me know if you need help with it. I am also available to chat if you want to discuss the fix.

**Comment by cofyc** [comment]
Thanks for clarification and the advice! I'll update this PR.

**Comment by bsalamat** [comment]
Thinking more about the solution that misterikkit outlined above last night, I am a bit worried that snapshotting the ecache might cause a noticeable slow down. We should measure performance impact of this solution.

**Comment by cofyc** [comment]
@misterikkit @bsalamat 

hi, I've updated PR to use solution that misterikkit outlined above. It's ready to review.

Because we don't have any mechanism to notify in-flight goroutine to exit on invalidation, the most important thing to prevent it from writing stale data into cache is we need some way to check the state is changed or not on write. There are two kinds of invalidation:

- invalidate predicate per node (`InvalidatePredicates`, `InvalidatePredicatesOnNode`)
- invalidate node (`InvalidateAllPredicatesOnNode`)

For invalidating predicate per node, add a generation for each predicate on node, increment it by 1 on invalidation, then we can check if there is invalidation happened for this predicate since last looked up.

For invalidating node, deleting node cache is enough. It is possible that in-flight predicate checker may write stale data into node cache, but node cache itself is deleted from equivalence cache. Even if node is added again shortly, scheduler will use fresh node cache next run.

I am not sure how to measure performance impact. Compared to `receivedInvalidationRequests`, it does not require RW lock on `lookupResult`, performance will not be significantly impacted in my opinion. 

Summary of changes:

- revert #63895
- revert part of #63040, `TestCacheInvalidationRace` kept and updated
  - my [integration test](https://github.com/cofyc/kubernetes/commit/d4b85b3001f4b4e603ac5182490fc71f52f6d147) is removed, it does almost the same thing as `TestCacheInvalidationRace`
- update `lookupResult` and `updateResult` to use generation

File: pkg/scheduler/core/equivalence/eqivalence.go (hunk 3 above)
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: With new solution misterikkit suggested, `RW` lock is not required now.

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 4]
```diff
@@ -258,6 +262,11 @@ func (n *NodeCache) updateResult(
 
 	n.mu.Lock()
 	defer n.mu.Unlock()
+	if received, ok := n.receivedInvalidationRequests[predicateKey]; ok && received {
```
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: `if !cache.IsUpToDate(nodeInfo)` is removed now, but `nodeInfo` argument is kept, because it's used in other places.

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 5]
```diff
@@ -300,6 +347,11 @@ func (n *NodeCache) invalidatePreds(predicateKeys sets.String) {
 	defer n.mu.Unlock()
 	for predicateKey := range predicateKeys {
 		delete(n.cache, predicateKey)
+		if _, ok := n.generations[predicateKey]; ok {
```
Comment (misterikkit) [inline pkg/scheduler/core/equivalence/eqivalence.go]: Similar to above, you can rely on the default map behavior here.
e.g.

```go
m := make(map[string]int)
fmt.Println(m) //  "map[]"
m["counter"]++
fmt.Println(m) // "map[counter:1]"
```

File: pkg/scheduler/core/equivalence/eqivalence_test.go [hunk 6]
```diff
@@ -190,31 +180,23 @@ func TestRunPredicate(t *testing.T) {
...
 			name:             "pod fits/cache miss",
 			pred:             mockPredicate{fit: true},
-			cache:            &upToDateCache{},
+			cache:            &schedulertesting.FakeCache{},
 			expectFit:        true,
 			expectCacheHit:   false,
 			expectCacheWrite: true,
 		},
-		{
-			name:             "pod fits/cache miss/no write",
```
Comment (misterikkit) [inline pkg/scheduler/core/equivalence/eqivalence_test.go]: Is there a new test that covers this scenario?

File: pkg/scheduler/core/generic_scheduler.go [hunk 7]
```diff
@@ -95,6 +95,7 @@ func (f *FitError) Error() string {
 type genericScheduler struct {
 	cache                    schedulercache.Cache
 	equivalenceCache         *equivalence.Cache
+	nodeCacheSnapshots       map[string]*equivalence.NodeCacheSnapshot
```
Comment (misterikkit) [inline pkg/scheduler/core/generic_scheduler.go]: I think this member should be named so it's clearly related to eCache. However, I am not convinced that we should have this.

The reason that we have `cachedNodeInfoMap` is so that we can avoid rebuilding a snapshot from scratch every time. In `UpdateNodeNameToInfoMap`, we check the generation ID and decide whether we need to DeepCopy the NodeInfo object. Since eCache snapshots are just generation IDs, the only thing you (potentially) avoid is map allocation. (might be worth benchmarking with and without...)

File: pkg/scheduler/core/generic_scheduler.go [hunk 8]
```diff
@@ -129,6 +130,11 @@ func (g *genericScheduler) Schedule(pod *v1.Pod, nodeLister algorithm.NodeLister
 		return "", ErrNoNodesAvailable
 	}
 
+	// Snapshot all predicate generations and references of node caches.
```
Comment (misterikkit) [inline pkg/scheduler/core/generic_scheduler.go]: It is important that this happens before we snapshot the regular cache. (`UpdateNodeNameToInfoMap` is not the best name for that...) Could you expand on this comment so that future readers know the order matters? (Maybe borrow wording from the deleted comments in factory.go.)

In case it is not clear, the reason we must have it this way is the following scenario.
1. snapshot cache
2. event arrives, updating cache and invalidating ecache
3. snapshot ecache
4. evaluate predicates
5. result is written to ecache... using stale info from the cache snapshot

File: pkg/scheduler/core/generic_scheduler.go [hunk 9]
```diff
@@ -564,7 +576,11 @@ func podFitsOnNode(
 			//TODO (yastij) : compute average predicate restrictiveness to export it as Prometheus metric
 			if predicate, exist := predicateFuncs[predicateKey]; exist {
 				if eCacheAvailable {
-					fit, reasons, err = nodeCache.RunPredicate(predicate, predicateKey, pod, metaToUse, nodeInfoToUse, equivClass, cache)
+					predicateGeneration := uint64(0)
```
Comment (misterikkit) [inline pkg/scheduler/core/generic_scheduler.go]: Since zero values are default, the preferred (canonical) way to write this is `var predicateGeneration uint64`.

File: pkg/scheduler/core/generic_scheduler.go [hunk 10]
```diff
@@ -564,7 +576,11 @@ func podFitsOnNode(
...
+					if predicateGenerations != nil {
```
Comment (misterikkit) [inline pkg/scheduler/core/generic_scheduler.go]: Actually, it's perfectly valid to do a lookup on a nil map. You will get the zero value.

File: pkg/scheduler/core/generic_scheduler_test.go [hunk 11]
```diff
@@ -1504,3 +1504,90 @@ func TestCacheInvalidationRace(t *testing.T) {
 		t.Errorf("Predicate should have been called twice. Was called %d times.", callCount)
 	}
 }
+
+// TestCacheInvalidationRace2 tests that cache invalidation is correctly handled
+// when an invalidation event happens during predicate is running.
```
Comment (misterikkit) [inline pkg/scheduler/core/generic_scheduler_test.go]: grammar nit: "during predicate is running" should be "while a predicate is running"

File: pkg/scheduler/core/generic_scheduler_test.go [hunk 12]
```diff
@@ -1504,3 +1504,90 @@ func TestCacheInvalidationRace(t *testing.T) {
...
+func TestCacheInvalidationRace2(t *testing.T) {
+	// Create a predicate that returns false the first time and true on subsequent calls.
+	podWillFit := false
```
Comment (misterikkit) [inline pkg/scheduler/core/generic_scheduler_test.go]: should this be in the var section?

File: pkg/scheduler/core/generic_scheduler_test.go [hunk 13]
```diff
@@ -1504,3 +1504,90 @@ func TestCacheInvalidationRace(t *testing.T) {
...
+	testPredicate := func(pod *v1.Pod,
+		meta algorithm.PredicateMetadata,
+		nodeInfo *schedulercache.NodeInfo) (bool, []algorithm.PredicateFailureReason, error) {
+		callCount++
+		var (
+			fit            bool
+			failureReasons []algorithm.PredicateFailureReason
+		)
+		if !podWillFit {
+			podWillFit = true
```
Comment (misterikkit) [inline pkg/scheduler/core/generic_scheduler_test.go]: You could shorten this function by moving once.Do to the top and returning inside the conditional statement.

**Review by misterikkit — COMMENTED** [review]
Looking pretty good. I made an initial pass over the code, but I haven't given it a thorough review yet.

**Comment by misterikkit** [comment]
To run the benchmarks, I suggest reading through https://github.com/kubernetes/kubernetes/pull/65714#issuecomment-410016382 to see the commands that @bsalamat  and @resouer were using, and tweak that as needed.

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 14]
```diff
@@ -206,10 +246,11 @@ type predicateResult struct {
 // RunPredicate returns a cached predicate result. In case of a cache miss, the predicate will be
 // run and its results cached for the next call.
 //
-// NOTE: RunPredicate will not update the equivalence cache if the given NodeInfo is stale.
+// NOTE: RunPredicate will not update the equivalence cache if generation does not match live version.
 func (n *NodeCache) RunPredicate(
```
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: Updated.

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 15]
```diff
@@ -262,6 +299,16 @@ func (n *NodeCache) updateResult(
 
 	n.mu.Lock()
 	defer n.mu.Unlock()
+	liveGeneration, ok := n.generations[predicateKey]
+	if !ok {
+		liveGeneration = 0
```
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: Updated. Didn't know this, thanks!

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 16]
```diff
@@ -262,6 +299,16 @@ func (n *NodeCache) updateResult(
...
+	}
+	if generation != liveGeneration {
+		// Generation of this predicate has been updated since we last looked
+		// up, this indicates that we received a invalidation request during
+		// this time. Cache may be stale, skip update.
+		return
```
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: Fixed. My merge mistake too.

File: pkg/scheduler/core/equivalence/eqivalence.go (hunk 5 above)
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: Fixed.

File: pkg/scheduler/core/equivalence/eqivalence_test.go (hunk 6 above)
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence_test.go]: This test is kept and updated now.
Found that `schedulercache.Cache` can be replaced by `generation` field.

File: pkg/scheduler/core/generic_scheduler.go (hunk 7 above)
Comment (cofyc) [reply pkg/scheduler/core/generic_scheduler.go]: I added this only to avoid map allocation. I'll do some benchmarks. By the way I'm trying to figure out is it possible to use sequence numbers to present predicate key, then we can use slices to store generations ids and predicate results also. In that case, performance will be much better.

File: pkg/scheduler/core/generic_scheduler.go (hunk 8 above)
Comment (cofyc) [reply pkg/scheduler/core/generic_scheduler.go]: Updated but not sure if it's good enough. Let me know if you have some suggestions about wording.

File: pkg/scheduler/core/generic_scheduler.go (hunk 10 above)
Comment (cofyc) [reply pkg/scheduler/core/generic_scheduler.go]: Updated, and put it into `nodeCache.RunPredicate(...)`.

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 11 above)
Comment (cofyc) [reply pkg/scheduler/core/generic_scheduler_test.go]: Updated.

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 12 above)
Comment (cofyc) [reply pkg/scheduler/core/generic_scheduler_test.go]: Yes, updated.

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 13 above)
Comment (cofyc) [reply pkg/scheduler/core/generic_scheduler_test.go]: Updated.

**Comment by resouer** [comment]
I've read thru this PR and it generally looks good. While my concern is also same with Bobby: what's the performance impact?

> maybe we can order predicates and use sequence numbers to represent predicate key internally?

AFAIK, predicates are already ordered, see: https://github.com/kubernetes/kubernetes/blob/5a16163c87fe2a90916a51b52771a668bcaf2a0d/pkg/scheduler/core/generic_scheduler.go#L558 

> With this, we can use slice (or array) to store predicate results and generations in equivalence cache. Accessing and copying items in slice have much better performance than map.

I will +1 for this idea. 

It's not a secret that Golang map access used in ecache is a issue, and as the result, ecache becomes slower when the predicate itself is pure mathematics operation. I am very interested for cheap predicates, when ecache=ture, benchmark results should be at least the same with ecache=false Could you please benchmark this as well? (No need to send out PR, just to see if it's worthy)

P.S. Please use the benchmarking command below with parameter change FYI:
```
make test-integration WHAT=./test/integration/scheduler_perf GOFLAGS="-v=1" KUBE_TEST_VMODULE="''" KUBE_TEST_ARGS="-bench=BenchmarkScheduling -cpuprofile=cpu-5000n-10000p.out"
```
```
diff --git a/test/integration/scheduler_perf/scheduler_bench_test.go b/test/integration/scheduler_perf/scheduler_bench_test.go
index fb28da4..f3bc6d8 100644
--- a/test/integration/scheduler_perf/scheduler_bench_test.go
+++ b/test/integration/scheduler_perf/scheduler_bench_test.go
@@ -35,10 +35,7 @@ import (
 // various quantities of nodes and scheduled pods.
 func BenchmarkScheduling(b *testing.B) {
 	tests := []struct{ nodes, existingPods, minPods int }{
-		{nodes: 100, existingPods: 0, minPods: 100},
-		{nodes: 100, existingPods: 1000, minPods: 100},
-		{nodes: 1000, existingPods: 0, minPods: 100},
-		{nodes: 1000, existingPods: 1000, minPods: 100},
+		{nodes: 5000, existingPods: 0, minPods: 10000},
 	}
 	setupStrategy := testutils.NewSimpleWithControllerCreatePodStrategy("rc1")
 	testStrategy := testutils.NewSimpleWithControllerCreatePodStrategy("rc2")
diff --git a/test/integration/util/util.go b/test/integration/util/util.go
index 705abbf..6b43520 100644
--- a/test/integration/util/util.go
+++ b/test/integration/util/util.go
@@ -95,7 +95,7 @@ func createSchedulerConfigurator(
 	informerFactory informers.SharedInformerFactory,
 ) scheduler.Configurator {
 	// Enable EnableEquivalenceClassCache for all integration tests.
-	utilfeature.DefaultFeatureGate.Set("EnableEquivalenceClassCache=true")
+	utilfeature.DefaultFeatureGate.Set("EnableEquivalenceClassCache=false")
 
 	return factory.NewConfigFactory(
 		v1.DefaultSchedulerName,
-- 
```

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 17]
```diff
@@ -70,15 +70,55 @@ func NewCache() *Cache {
...
+// NodeCacheSnapshot represents a snapshot of NodeCache reference and generations.
+type NodeCacheSnapshot struct {
+	NodeCache   *NodeCache
+	Generations map[string]uint64
+}
+
+// UpdateNodeCacheSnapshots update node cache snapshots for given nodes. Create node cache if does not exist.
+func (c *Cache) UpdateNodeCacheSnapshots(nodes []*v1.Node, snapshots map[string]*NodeCacheSnapshot) {
+	c.mu.Lock()
+	defer c.mu.Unlock()
```
Comment (resouer) [inline pkg/scheduler/core/equivalence/eqivalence.go]: In recent #66862, we've changed to use `sync.Map` for `Cache`, could you please rebase to latest HEAD and use this data structure?

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 18]
```diff
@@ -70,15 +70,55 @@ func NewCache() *Cache {
 type NodeCache struct {
 	mu    sync.RWMutex
 	cache predicateMap
+	// Generations for predicates, incremented on predicate invalidation.
+	// Created on first update. Use 0 if does not exist.
+	generations map[string]uint64
```
Comment (resouer) [inline pkg/scheduler/core/equivalence/eqivalence.go]: The typical comment style is: "generations is ..."

**Comment by misterikkit** [comment]
> P.S. Please use the benchmarking command below with parameter change FYI:

One of these days we should figure out how to make these parameters so we can run tests without carrying patches around.

File: pkg/scheduler/core/equivalence/eqivalence.go (hunk 18 above)
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: Updated.

File: pkg/scheduler/core/equivalence/eqivalence.go (hunk 17 above)
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: Found it's impossible to wrap more than 1 operations on map in a lock, e.g. updating and iterating.

In this snapshotting function, we need to create node cache if not found, then snapshot all node caches. I updated it to use `sync.Map` methods (see below), apparently it's not ok. 

- cannot wrap multiple update operations in one lock
- cannot wrap update operations with iterations in one lock

```
    for _, node := range nodes {
        if _, ok := c.Load(node.Name); !ok {
            c.LoadOrStore(node.Name, newNodeCache())
        }
    }
    c.Range(func(k, v interface{}) bool {
        name := k.(string)
        node := v.(*NodeCache)
        snapshot, ok := snapshots[name]
        if !ok {
            snapshot = &NodeCacheSnapshot{
                Generations: make(map[string]uint64, len(node.generations)),
            }
            snapshots[name] = snapshot
        }
        snapshot.NodeCache = node
        for k, v := range node.generations {
            snapshot.Generations[k] = v
        }
        return true
    })
```

Still using plain Go map with separate locking, what do you think? I think it gives us more freedom.

Comment (resouer) [reply pkg/scheduler/core/equivalence/eqivalence.go]: I'm totally OK with either way. The only concern will be performance decrease in machines with 8+ CPUs, let's see how the benchmark says :D

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 19]
```diff
@@ -63,15 +63,57 @@ func NewCache() *Cache {
...
 	return &NodeCache{
-		cache: make(predicateMap),
+		cache:       make(predicateMap),
+		generations: make(map[string]uint64),
 	}
 }
 
+// NodeCacheSnapshot represents a snapshot of NodeCache reference and generations.
+type NodeCacheSnapshot struct {
+	NodeCache   *NodeCache
```
Comment (bsalamat) [inline pkg/scheduler/core/equivalence/eqivalence.go]: Why do we need to store this pointer? We just need to snapshot the generation number.

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 20]
```diff
@@ -63,15 +63,57 @@ func NewCache() *Cache {
 type NodeCache struct {
 	mu    sync.RWMutex
 	cache predicateMap
+	// generations stores generation numbers for predicates, incremented on
+	// predicate invalidation. Created on first update. Use 0 if does not
+	// exist.
+	generations map[string]uint64
```
Comment (bsalamat) [inline pkg/scheduler/core/equivalence/eqivalence.go]: I think you can add the snapshot as a member of NodeCache.

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 21]
```diff
@@ -287,6 +330,7 @@ func (n *NodeCache) invalidatePreds(predicateKeys sets.String) {
 	defer n.mu.Unlock()
 	for predicateKey := range predicateKeys {
 		delete(n.cache, predicateKey)
+		n.generations[predicateKey]++
```
Comment (bsalamat) [inline pkg/scheduler/core/equivalence/eqivalence.go]: Also, at line 153, all predicates of a node are invalidated. We currently just delete the node from the cache. With this PR, we can no longer delete the node. We must keep the node, increment generation number of all the predicates and set the `predicateMap` to nil (or an empty map).

File: pkg/scheduler/core/generic_scheduler.go (hunk 7 above)
Comment (bsalamat) [reply pkg/scheduler/core/generic_scheduler.go]: I think if the snapshot was a member of equivalenceCache, you didn't need to pass it separately here.

**Review by bsalamat — COMMENTED** [review]
Thanks, @cofyc! I have several early comments.

File: pkg/scheduler/core/equivalence/eqivalence.go (hunk 19 above)
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: I have some explanations [here](https://github.com/kubernetes/kubernetes/pull/67308#issuecomment-414054511). For invalidating node, deleting node cache is not enough, because node is invalidated before `lookupResult`, a fresh node cache will be created in `lookupResult` and stale data will be written into it. To fix this, we can get node cache before snapshotting scheduler cache. If in-flight predicate checker write stale data into it, node cache itself can be removed from equivalence cache on invalidation, so scheduler will use fresh node cache next run.

I prefer this because 1) we don't need to store node cache forever even after node is deleted from cluster 2) checkNode needs to get node cache one by one, getting node cache pointers all at once does not add performance overhead.

File: pkg/scheduler/core/equivalence/eqivalence.go (hunk 20 above)
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: IIUC, snapshotting generations to current node cache, then in `updateResult` compare previous snapshotted generation with live generation?
It's ok, but requires us to make assumptions how functions are called.

**Comment by cofyc** [comment]
Here is my benchmark results, some are still work in progress. I reverted #66862 for this PR because [the reasons I listed here](https://github.com/kubernetes/kubernetes/pull/67308#discussion_r212554374).

## Benchmarks (WIP)

### Profile

Machine:

- CPUs: 8 x Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz

Benchmark configurations:

- BenchmarkScheduling: `{nodes: 5000, existingPods: 0, minPods: 10000}`
- BenchmarkSchedulingAntiAffinity: `{nodes: 2500, existingPods: 0, minPods: 5000}`

Benchmark command:

```
./hack/print-workspace-status.sh | grep '^gitCommit'
grep -o -P 'EnableEquivalenceClassCache=(true|false)' test/integration/util/util.go
make test-integration WHAT=./test/integration/scheduler_perf GOFLAGS="-v=1" KUBE_TEST_VMODULE="''" KUBE_TIMEOUT="--timeout 3600s" KUBE_TEST_ARGS="-bench=BenchmarkScheduling" | tee benchmark.log | grep -P '^(BenchmarkScheduling|ok)'
```

### N5000-P10000-ECACHE-ENABLED-PR67308

```
gitCommit 6b59be11821abf6c630f55c4759f43dc3afa83a8
EnableEquivalenceClassCache=true
BenchmarkScheduling/5000Nodes/0Pods-8         	   10000	  18826094 ns/op
BenchmarkSchedulingAntiAffinity/2500Nodes/0Pods-8         	    5000	  16425119 ns/op
ok  	k8s.io/kubernetes/test/integration/scheduler_perf	285.792s
```

### N5000-P10000-ECACHE-DISABLED-PR67308

```
gitCommit 6b59be11821abf6c630f55c4759f43dc3afa83a8
EnableEquivalenceClassCache=false
BenchmarkScheduling/5000Nodes/0Pods-8         	   10000	  11951690 ns/op
BenchmarkSchedulingAntiAffinity/2500Nodes/0Pods-8         	    5000	 142623149 ns/op
ok  	k8s.io/kubernetes/test/integration/scheduler_perf	848.066s
```

### N5000-P10000-ECACHE-ENABLED-MASTER

```
gitCommit 5b2a7c7347cf9ca86ef5dfaaea3e3aa4df3ae270
EnableEquivalenceClassCache=true
BenchmarkScheduling/5000Nodes/0Pods-8         	   10000	  15743979 ns/op
BenchmarkSchedulingAntiAffinity/2500Nodes/0Pods-8         	    5000	  14195174 ns/op
ok  	k8s.io/kubernetes/test/integration/scheduler_perf	243.524s
```

### N5000-P10000-ECACHE-DISABLED-MASTER

```
gitCommit 5b2a7c7347cf9ca86ef5dfaaea3e3aa4df3ae270
EnableEquivalenceClassCache=false
BenchmarkScheduling/5000Nodes/0Pods-8         	   10000	  11452931 ns/op
BenchmarkSchedulingAntiAffinity/2500Nodes/0Pods-8         	    5000	 130701043 ns/op
ok  	k8s.io/kubernetes/test/integration/scheduler_perf	659.675s
```

### N5000-P10000-ECACHE-ENABLED-PR67308-INTKEY (TODO)

### N5000-P10000-ECACHE-DISABLED-PR67308-INTKEY (TODO)

**Review by misterikkit — CHANGES_REQUESTED** [review]
Oops, I wrote these comments last week and forgot to hit send.

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 22]
```diff
@@ -70,15 +70,55 @@ func NewCache() *Cache {
...
 // newNodeCache returns an empty NodeCache.
 func newNodeCache() *NodeCache {
 	return &NodeCache{
-		cache: make(predicateMap),
+		cache:       make(predicateMap),
+		generations: make(map[string]uint64),
 	}
 }
 
+// NodeCacheSnapshot represents a snapshot of NodeCache reference and generations.
```
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: Updated.

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 23]
```diff
@@ -262,6 +295,14 @@ func (n *NodeCache) updateResult(
 
 	n.mu.Lock()
 	defer n.mu.Unlock()
+	liveGeneration := n.generations[predicateKey]
+	if generation != liveGeneration {
+		// Generation of this predicate has been updated since we last looked
```
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: oops, this comment is for my initial implementation, in which I cached generations in `lookupResult`. Fixed now.

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 24]
```diff
@@ -277,8 +318,8 @@ func (n *NodeCache) updateResult(
 		nodeInfo.Node().Name, predicateKey, podName, predicateItem)
 }
 
-// lookupResult returns cached predicate results and a bool saying whether a
-// cache entry was found.
+// lookupResult returns cached predicate results with a associated generation
```
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: Fixed.

**Comment by cofyc** [comment]
@misterikkit @bsalamat @resouer 

In my benchmark results, I've tried some alternative implementations:

### Use int key to present predicate key

File: pkg/scheduler/core/equivalence/eqivalence.go (hunk 20 above)
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: @misterikkit @resouer What do you think?

File: pkg/scheduler/core/equivalence/eqivalence.go (hunk 19 above)
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: @misterikkit @resouer What do you think?

**Comment by resouer** [comment]
Thanks for so much detailed benchmark.

One nits I need to amend is (sorry, just noticed it recently) the metrics calculation in `lookupResult` is not cheap, (see: #67857), so the result of ecache enabled is actually inaccurate, but it should not change the result as long as all the tests included the metrics patch. 

Personally, I am in favor of a seperate PR to use Integer as key of ecache, and would like to do a review :) (You can revert sync.Map there too)

> Another change in this implementation is to invalidate node cache instead of caching its pointer, but this requires to keep node cache even after node is removed from cluster

This does not seems to be a big problem to me.

 btw, using Integer as predicate key does not conflict with Bobby's suggestion, right?

**Comment by cofyc** [comment]
> btw, using Integer as predicate key does not conflict with Bobby's suggestion, right?

Yes, using Integer as predicate key is independent of all choices.

**Comment by cofyc** [comment]
hi, I pushed a new commit to address @bsalamat's suggestions. PTAL.

File: pkg/scheduler/core/generic_scheduler.go [hunk 25]
```diff
@@ -389,7 +401,9 @@ func (g *genericScheduler) findNodesThatFit(pod *v1.Pod, nodes []*v1.Node) ([]*v
 		}
 
 		checkNode := func(i int) {
-			var nodeCache *equivalence.NodeCache
+			var (
+				nodeCache *equivalence.NodeCache
```
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/core/generic_scheduler.go]: this place has been edited multiple times, no change now, I'll revert it to original state

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 26]
```diff
@@ -61,23 +68,56 @@ func NewCache() *Cache {
...
+	}
+}
+
+// Snapshot snapshots current generations of cache.
+func (c *Cache) Snapshot(nodes []*v1.Node) {
+	c.mu.Lock()
+	defer c.mu.Unlock()
+	for _, node := range nodes {
+		if _, exists := c.nodeToCache[node.Name]; !exists {
+			c.nodeToCache[node.Name] = newNodeCache()
```
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: I thought earlier we must make sure all nodes has node caches because equivalence cache may not have caches for [nodes listed from lister](https://github.com/kubernetes/kubernetes/blob/v1.13.0-alpha.0/pkg/scheduler/core/generic_scheduler.go#L115) and `checkNode` will get a fresh node cache to use. Invalidations happens after snapshotting and before node cache being created will be ignored. (This is what `TestCacheInvalidationRace` tests)

But I find now it's not necessary because we run predicates on nodes in scheduler cache not nodes listed from lister after [this PR](https://github.com/kubernetes/kubernetes/pull/66733/files#diff-c237cdd9e4cb201118ca380732d7f361L367). When a node is added into scheduler cache, [it will create node cache for it](https://github.com/kubernetes/kubernetes/blob/e124159990c6d22e9ca662ef35de5eeaef5d8956/pkg/scheduler/factory/factory.go#L856).

I'll update this and move `GetNodeCache()` before `schedulerCache.AddNode` in `configFactory. addNodeToCache()` to make sure node cache is created before being adding into schedule cache.

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 27]
```diff
@@ -61,23 +68,56 @@ func NewCache() *Cache {
...
+	return
 }
 
 // GetNodeCache returns the existing NodeCache for given node if present. Otherwise,
 // it creates the NodeCache and returns it.
 // The boolean flag is true if the value was loaded, false if created.
 func (c *Cache) GetNodeCache(name string) (nodeCache *NodeCache, exists bool) {
-	v, exists := c.LoadOrStore(name, newNodeCache())
-	nodeCache = v.(*NodeCache)
+	c.mu.Lock()
```
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: In earlier implementation, I need to create and snapshot node cache in one function, but `sync.Map` does not support more than 1 operations in one lock. I'll revert it back.

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 28]
```diff
@@ -249,6 +284,13 @@ func (n *NodeCache) updateResult(
...
 	defer n.mu.Unlock()
+	if (n.snapshotGeneration != n.generation) || (n.snapshotPredicateGenerations[predicateKey] != n.predicateGenerations[predicateKey]) {
+		// Generation of node or predicate has been updated since we last took
+		// a snapshot, this indicates that we received a invalidation request
+		// during this time. Cache may be stale, skip update.
+		metrics.EquivalenceCacheWrites.WithLabelValues("discarded_stale").Inc()
+		return
+	}
 	// If cached predicate map already exists, just update the predicate by key
 	if predicates, ok := n.cache[predicateKey]; ok {
```
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: oops, my mistake, updated

File: pkg/scheduler/core/generic_scheduler.go [hunk 29]
```diff
@@ -129,6 +129,18 @@ func (g *genericScheduler) Schedule(pod *v1.Pod, nodeLister algorithm.NodeLister
...
+	// IMPORTANT NOTE: We must snapshot equivalence cache before snapshotting
+	// scheduler cache, otherwise stale data may be written into equivalence
+	// cache, e.g.
+	// 1. snapshot cache
+	// 2. event arrives, updating cache and invalidating predicates or whole node cache
+	// 3. snapshot ecache
+	// 4. evaludate predicates
+	// 5. stale result will be written to ecache
+	if g.equivalenceCache != nil {
+		g.equivalenceCache.Snapshot(nodes)
```
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/core/generic_scheduler.go]: Updated.

File: pkg/scheduler/core/equivalence/eqivalence.go (hunk 26 above)
[the remark this answers is not in the document]
Comment (resouer) [reply pkg/scheduler/core/equivalence/eqivalence.go]: > I'll update this and move GetNodeCache() before schedulerCache.AddNode in configFactory. addNodeToCache() to make sure node cache is created before being adding into schedule cache.

This is what I'm thinking recently: we should try to avoid calling`GetNodeCache()` in any scheduling path as it holds a lock across nodes. You need to handle in node delete as well.

**Comment by bsalamat** [comment]
@cofyc Thanks a lot for running the benchmarks and collecting information for various implementation options. The performance improvement from the predicate int keys is great. I think we should use it instead of the current implementation.

File: pkg/scheduler/core/equivalence/eqivalence.go (hunk 26 above)
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: @resouer Thanks! We should invalidate node before removing it from scheduler cache.

**Comment by cofyc** [comment]
Any other concerns?

File: pkg/scheduler/factory/factory.go [hunk 30]
```diff
@@ -849,15 +843,17 @@ func (c *configFactory) addNodeToCache(obj interface{}) {
 		return
 	}
 
-	if err := c.schedulerCache.AddNode(node); err != nil {
-		glog.Errorf("scheduler cache AddNode failed: %v", err)
-	}
-
+	// NOTE: Because the scheduler uses equivalence caches for nodes, we need
```
Comment (bsalamat) [inline pkg/scheduler/factory/factory.go]: s/caches/cache/

File: pkg/scheduler/factory/factory.go [hunk 31]
```diff
@@ -970,15 +963,13 @@ func (c *configFactory) deleteNodeFromCache(obj interface{}) {
...
-	// version of equivalencePodCache, updates must be written to schedulerCache
-	// before invalidating equivalencePodCache.
-	if err := c.schedulerCache.RemoveNode(node); err != nil {
-		glog.Errorf("scheduler cache RemoveNode failed: %v", err)
-	}
+	// NOTE: Invalidate equivalence node cache first.
 	if c.enableEquivalenceClassCache {
 		c.equivalencePodCache.InvalidateAllPredicatesOnNode(node.GetName())
 	}
+	if err := c.schedulerCache.RemoveNode(node); err != nil {
```
Comment (bsalamat) [inline pkg/scheduler/factory/factory.go]: If remove must happen after the invalidation, it deserves a better comment.

**Review by bsalamat — COMMENTED** [review]
Thanks, @cofyc and sorry for the delay. It looks generally good. I have several minor comments.
I haven't looked at the tests yet.

File: pkg/scheduler/factory/factory.go (hunk 30 above)
Comment (cofyc) [reply pkg/scheduler/factory/factory.go]: fixed

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 32]
```diff
@@ -61,36 +74,78 @@ func NewCache() *Cache {
...
+	}
 	return
 }
 
+func (c *Cache) predicateKeysToIDs(predicateKeys sets.String) []int {
+	predicateIDs := make([]int, 0, len(predicateKeys))
+	for predicateKey := range predicateKeys {
+		if id, ok := c.predicateIDMap[predicateKey]; ok {
+			predicateIDs = append(predicateIDs, id)
+		}
```
[the remark this answers is not in the document]
Comment (cofyc) [reply pkg/scheduler/core/equivalence/eqivalence.go]: added

File: pkg/scheduler/factory/factory.go (hunk 31 above)
Comment (cofyc) [reply pkg/scheduler/factory/factory.go]: Sorry, I found I'm wrong with this part. All equivalence cache invalidations should be after resource objects are added, updated and deleted, then predicate functions will run and use new versions of resource objects. I revert this change.

By the way, there is no need to invalidate predicates for node after adding because no predicate functions will run on deleted node (we iterate on nodes in scheduler cache).

**Comment by cofyc** [comment]
@bsalamat Thanks, I pushed a new commit: https://github.com/kubernetes/kubernetes/pull/67308/commits/cc3b6d9da3e0d77b9e9376cbf39c5b1e7b7518b4.

File: pkg/scheduler/factory/factory.go (hunk 31 above)
Comment (bsalamat) [reply pkg/scheduler/factory/factory.go]: I agree with you that invalidation of eCache should happen after CUD operations on objects. The following diagram shows a scenario where the reverse order causes an issue. If invalidation happens first, we could snapshot eCache after the invalidation and then we snapshot the cache itself. A node is then removed/added/updated before we update eCache. We then would update eCache with stale information which is based on our latest snapshot of the cache taken before the node removal/addition/update:

```
------|-----------------|------------------|----------------|---------------|-------->
Invalidate eCache  Snapshot eCache   Snapshot Cache     Remove Node    Update eCache    
```

I think you should add this to the comment to document why the order is important.

File: pkg/scheduler/factory/factory.go [hunk 33]
```diff
@@ -849,15 +843,17 @@ func (c *configFactory) addNodeToCache(obj interface{}) {
...
 
-	if err := c.schedulerCache.AddNode(node); err != nil {
-		glog.Errorf("scheduler cache AddNode failed: %v", err)
-	}
-
+	// NOTE: Because the scheduler uses equivalence cache for nodes, we need
+	// to create it before adding node into scheduler cache.
 	if c.enableEquivalenceClassCache {
 		// GetNodeCache() will lazily create NodeCache for given node if it does not exist.
 		c.equivalencePodCache.GetNodeCache(node.GetName())
```
Comment (resouer) [inline pkg/scheduler/factory/factory.go]: Since we will init NodeCache here, it seems we don't need to call `g.equivalenceCache.GetNodeCache(nodeName)` in generic_scheduler?

Instead, we can only call sth like `g.equivalenceCache.LoadNodeCache()` there, only read operation. WDYT?

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 34]
```diff
@@ -35,20 +35,33 @@ import (
 	"github.com/golang/glog"
 )
 
+// nodeMap stores a *Cache for each node.
```
Comment (resouer) [inline pkg/scheduler/core/equivalence/eqivalence.go]: stores a *NodeCache

File: pkg/scheduler/core/equivalence/eqivalence.go [hunk 35]
```diff
@@ -61,36 +74,80 @@ func NewCache() *Cache {
...
-	cache predicateMap
+	mu                 sync.RWMutex
+	cache              predicateMap
+	generation         uint64
+	snapshotGeneration uint64
+	// predicateGenerations stores generation numbers for predicates, incremented on
+	// predicate invalidation. Created on first update. Use 0 if does not
+	// exist.
+	predicateGenerations         []uint64
+	snapshotPredicateGenerations []uint64
```
Comment (resouer) [inline pkg/scheduler/core/equivalence/eqivalence.go]: It would be better to include comments for all last three members, to make other developer's life easier.

**Review by resouer — COMMENTED** [review]
Just added several review comments, others look good, please take a look!

File: pkg/scheduler/factory/factory.go (hunk 31 above)
Comment (cofyc) [reply pkg/scheduler/factory/factory.go]: Added in https://github.com/kubernetes/kubernetes/pull/67308/commits/dd9d576e64f4536ffe8d9367d1d2edc90ee3d3ab.

There is no need to revert PR https://github.com/kubernetes/kubernetes/pull/63895/files, I'll rebase it when PR is done.

File: pkg/scheduler/scheduler.go [hunk 36]
```diff
@@ -329,9 +329,11 @@ func (sched *Scheduler) assume(assumed *v1.Pod, host string) error {
 	// If the binding fails, scheduler will release resources allocated to assumed pod
 	// immediately.
 	assumed.Spec.NodeName = host
-	// NOTE: Because the scheduler uses snapshots of SchedulerCache and the live
-	// version of Ecache, updates must be written to SchedulerCache before
-	// invalidating Ecache.
+	// NOTE: Updates must be written to scheduler cache before invalidating
```
Comment (bsalamat) [inline pkg/scheduler/scheduler.go]: I don't think this comment applies here.

Comment (cofyc) [reply pkg/scheduler/scheduler.go]: After assuming pod into scheduler cache, it will invalidate affected predicates in equivalence cache.
https://github.com/kubernetes/kubernetes/blob/8ece5d624ded4815655104d8a12712cfe6d8743e/pkg/scheduler/scheduler.go#L355-L363

**Review by bsalamat — APPROVED** [review]
Thanks, @cofyc!

/lgtm

**Review by bsalamat — COMMENTED** [review]
/lgtm
