### PR TITLE
GC: Fix re-adoption race when orphaning dependents.

### LINKED ISSUE #42639: Garbage collector should orphan RS created by deployment when deleteOptions.OrphanDependents is true
Instead, there are no RSs present.

from https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/42593/pull-kubernetes-e2e-gce-etcd3/21127/ 

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/garbage_collector.go:471
Mar  6 13:31:39.687: remaining rs post mortem: &v1beta1.ReplicaSetList{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"/apis/extensions/v1beta1/namespaces/e2e-tests-gc-bkl67/replicasets", ResourceVersion:"10566"}, Items:[]v1beta1.ReplicaSet(nil)}
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/garbage_collector.go:451
```

@kubernetes/sig-api-machinery-misc

### PR DESCRIPTION
**Pull request by enisoc**
**What this PR does / why we need it**:

The GC expects that once it sees a controller with a non-nil
DeletionTimestamp, that controller will not attempt any adoption.
There was a known race condition that could cause a controller to
re-adopt something orphaned by the GC, because the controller is using a
cached value of its own spec from before DeletionTimestamp was set.

This fixes that race by doing an uncached quorum read of the controller
spec just before the first adoption attempt. It's important that this
read occurs after listing potential orphans. Note that this uncached
read is skipped if no adoptions are attempted (i.e. at steady state).

**Which issue this PR fixes**:

Fixes #42639

**Special notes for your reviewer**:

**Release note**:
```release-note
```

cc @kubernetes/sig-apps-pr-reviews

### CODE REVIEW

File: pkg/controller/daemon/daemoncontroller.go [hunk 1]
```diff
@@ -501,7 +514,11 @@ func (dsc *DaemonSetsController) resolveControllerRef(namespace string, controll
 		// ControllerRef points to.
 		return nil
 	}
-	return ds
+	cp, err := api.Scheme.DeepCopy(ds)
+	if err != nil {
+		return nil
+	}
+	return cp.(*extensions.DaemonSet)
```
Comment (janetkuo) [inline pkg/controller/daemon/daemoncontroller.go]: Is this change required to fix the race issue or a separate thing?

Comment (enisoc) [inline pkg/controller/daemon/daemoncontroller.go]: The result of this function gets passed to the function that updates the DeletionTimestamp. To make sure all DaemonSet pointers are safe, I made deep copies at the points where they are retrieved from the cache.

**Review by 0xmichalis — COMMENTED** [review]
/approve

File: pkg/controller/daemon/daemoncontroller.go [hunk 2]
```diff
@@ -510,6 +527,10 @@ func (dsc *DaemonSetsController) manage(ds *extensions.DaemonSet) error {
 	if err != nil {
 		return fmt.Errorf("couldn't get node to daemon pod mapping for daemon set %q: %v", ds.Name, err)
 	}
+	// Check DeletionTimestamp again because it may have been refreshed by getNodesToDaemonPods().
+	if ds.DeletionTimestamp != nil {
```
Comment (kargakis) [inline pkg/controller/daemon/daemoncontroller.go]: Wouldn't it be simpler to consolidate all these checks into a single top-level check that gets called before everything else (code that adopts, manages, upgrades pods for a DS)?

File: pkg/controller/daemon/daemoncontroller.go [hunk 3]
```diff
@@ -763,6 +784,12 @@ func (dsc *DaemonSetsController) syncDaemonSet(key string) error {
 	if err != nil {
 		return fmt.Errorf("unable to retrieve ds %v from store: %v", key, err)
 	}
+	// DeepCopy so we don't mutate objects in the cache.
+	cp, err := api.Scheme.DeepCopy(ds)
```
Comment (smarterclayton) [inline pkg/controller/daemon/daemoncontroller.go]: This is likely a large performance change.  It's correct, but it's also really late to be significantly altering the controller impact like this.

**Comment by smarterclayton** [comment]
@wojtek-t this is likely to regress performance for these controllers (adding multiple deep copies, new live gets).  How do we ensure this change is measured?

File: pkg/controller/daemon/daemoncontroller.go (hunk 2 above)
Comment (caesarxuchao) [inline pkg/controller/daemon/daemoncontroller.go]: We need to refresh the DS to check its latest deletionTimestamp _**after**_ listing all pods (i.e., potential controllees) at line 476. We do have a top-level check [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/daemoncontroller.go#L780), but that's before the refresh. The newly added checks are using the refreshed value.

File: pkg/controller/daemon/daemoncontroller.go (hunk 3 above)
Comment (kargakis) [inline pkg/controller/daemon/daemoncontroller.go]: We can avoid deep-copying unconditionally. Simply get the live object before L807 where we do the initial deletiontimestamp!=nil check and check the live object instead of the cached object.

File: pkg/controller/daemon/daemoncontroller.go (hunk 2 above)
Comment (kargakis) [inline pkg/controller/daemon/daemoncontroller.go]: See my comment in https://github.com/kubernetes/kubernetes/pull/42938/files#r105728217 for what I mean by having a top-level catch-all check.

File: pkg/controller/daemon/daemoncontroller.go (hunk 3 above)
Comment (caesarxuchao) [inline pkg/controller/daemon/daemoncontroller.go]: Are you referring to this DeepCopy? We can use a boolean to record if the controller's DeletionTimestamp is nil, then we don't need to modify the controller object.

File: pkg/controller/daemon/update_test.go [hunk 4]
```diff
@@ -24,10 +24,10 @@ import (
 )
 
 func TestDaemonSetUpdatesPods(t *testing.T) {
-	manager, podControl, _ := newTestController()
+	ds := newDaemonSet("foo")
```
Comment (caesarxuchao) [inline pkg/controller/daemon/update_test.go]: Why are these test changes?

File: pkg/controller/daemon/daemoncontroller.go (hunk 2 above)
Comment (enisoc) [inline pkg/controller/daemon/daemoncontroller.go]: @kargakis The problem with fetching the live object once at the beginning is that we might encounter the following:

1. Fetch live controller object. DeletionTimestamp = nil
2. GC sets DeletionTimestamp != nil, and orphans one or more Pods.
3. Get list of Pods. See some orphans. Readopt.

@caesarxuchao suggested that the rule to prevent this is that you must refetch the controller object some time after you get the list of Pods. Maybe we could move the Pod list fetch to the top as well?

File: pkg/controller/daemon/update_test.go (hunk 4 above)
Comment (enisoc) [inline pkg/controller/daemon/update_test.go]: The code now reads from both the cache (lister) and the bare client, so we must include the controller object in both fakes. Previously, many tests only ever populated the cache because that's all that mattered.

File: pkg/controller/statefulset/stateful_set_control_test.go [hunk 5]
```diff
@@ -214,69 +214,6 @@ func TestStatefulSetControlReplacesPods(t *testing.T) {
...
-
-	// Delete the first pod.
-	spc.podsIndexer.Delete(pods[0])
-	pods, err = spc.podsLister.Pods(set.Namespace).List(selector)
-	if err != nil {
-		t.Error(err)
-	}
-
-	// The StatefulSet should update its replica count,
-	// but not try to fix it.
```
Comment (caesarxuchao) [inline pkg/controller/statefulset/stateful_set_control_test.go]: Why removing the test? The behavior described here looks reasonable.

Comment (caesarxuchao) [inline pkg/controller/statefulset/stateful_set_control_test.go]: nvm, i see you moved it.

Comment (enisoc) [inline pkg/controller/statefulset/stateful_set_control_test.go]: For the record, the reason I moved it is because there is now logic that handles DeletionTimestamp outside stateful_set_control. So I needed to promote the test to a higher level of abstraction (stateful_set itself).

File: pkg/controller/daemon/daemoncontroller.go (hunk 2 above)
Comment (kargakis) [inline pkg/controller/daemon/daemoncontroller.go]: @enisoc yes, I believe modeling this after what we do in the deployment controller is cleaner and easier to reason about:
- GET object from cache
- LIST all related objects
- Abort if parent is deleted. (+status update)
- Apply the business logic (scale up/down) (+status update)

Not sure if such a refactoring makes sense in this PR.

Comment (kargakis) [inline pkg/controller/daemon/daemoncontroller.go]: Btw, we can apply this in the Deployment controller because we already fetch all related objects before checking the timestamp.

**Comment by caesarxuchao** [comment]
@smarterclayton controllers will need to do an API call before updating objects anyway for HA use case, see https://github.com/kubernetes/kubernetes/issues/22007.

Also, we can reduce the number of API call by only make the call if the controller decides to adopt an orphan, that should be much rarer.

**Comment by enisoc** [comment]
@smarterclayton @caesarxuchao @janetkuo Please take another look. I have implemented an alternate approach that should not introduce performance regressions.

**Comment by kargakis** [comment]
@deads2k

**Comment by deads2k** [comment]
I'm not a fan of the expression, but it looks like it would work.

**Comment by ethernetdan** [comment]
@k8s-bot non-cri e2e test this

**Comment by marun** [comment]
@smarterclayton @caesarxuchao @janetkuo @wojtek-t This is a release blocker, PTAL.

**Comment by smarterclayton** [comment]
The performance concern is addressed.  I believe the logic is sound.  I don't have objections to this on the previous grounds, but I want another sign off on the code and the logic.

File: pkg/controller/replicaset/replica_set_test.go [hunk 6]
```diff
@@ -87,7 +89,7 @@ func skipListerFunc(verb string, url url.URL) bool {
 	if verb != "GET" {
 		return false
 	}
-	if strings.HasSuffix(url.Path, "/pods") || strings.HasSuffix(url.Path, "/replicasets") {
+	if strings.HasSuffix(url.Path, "/pods") || strings.Contains(url.Path, "/replicasets") {
```
Comment (janetkuo) [inline pkg/controller/replicaset/replica_set_test.go]: Why change this?

File: pkg/controller/daemon/daemoncontroller.go [hunk 7]
```diff
@@ -468,6 +470,16 @@ func (dsc *DaemonSetsController) getNodesToDaemonPods(ds *extensions.DaemonSet)
 	if err != nil {
 		return nil, err
 	}
+	// After listing children, but before performing adoption, we need to recheck
+	// whether the GC has marked us as deleted (see #42639).
+	// TODO: Remove this when GC prevents races via ObservedGeneration (#26120).
```
Comment (enisoc) [inline pkg/controller/daemon/daemoncontroller.go]: I think you were looking at an outdated commit. The current version of this PR does not introduce any new copies. Also based on discussion in #43032, it seems that the GC may never wait for ObservedGeneration.

File: pkg/controller/deployment/deployment_controller_test.go [hunk 8]
```diff
@@ -267,6 +282,30 @@ func TestSyncDeploymentDontDoAnythingDuringDeletion(t *testing.T) {
...
 }
 
+func TestSyncDeploymentDeletionRace(t *testing.T) {
+	f := newFixture(t)
+
+	d := newDeployment("foo", 1, nil, nil, nil, map[string]string{"foo": "bar"})
+	d2 := *d
+	// Lister (cache) says NOT deleted.
+	f.dLister = append(f.dLister, d)
+	// Bare client says it IS deleted. This should be presumed more up-to-date.
```
Comment (caesarxuchao) [inline pkg/controller/deployment/deployment_controller_test.go]: I use the words "being Deleted" to mean deletionTimestamp!=nil and "deleted" to mean the object is not visible via REST API anymore.

File: pkg/controller/deployment/deployment_controller_test.go [hunk 9]
```diff
@@ -190,15 +195,25 @@ func (f *fixture) newController() (*DeploymentController, informers.SharedInform
...
 
+func (f *fixture) runExpectError(deploymentName string) {
+	f.run_(deploymentName, true)
+}
+
 func (f *fixture) run(deploymentName string) {
+	f.run_(deploymentName, false)
+}
+
+func (f *fixture) run_(deploymentName string, expectError bool) {
```
Comment (enisoc) [inline pkg/controller/deployment/deployment_controller_test.go]: Go style does not use `_` for separating words, but sometimes it is used as a prefix or suffix to indicate "this is an internal implementation detail and you shouldn't usually access it directly". Since this is just a test, I didn't think it was worth trying to figure out a meaningful name to give `run_()`. I just needed to move it out of the way of the `run()` function that doesn't have the extra `bool`.

File: pkg/controller/controller_ref_manager.go [hunk 10]
```diff
@@ -342,3 +365,20 @@ func (m *ReplicaSetControllerRefManager) ReleaseReplicaSet(replicaSet *extension
...
+// The canAdopt() function calls getObject() to fetch the latest value,
+// and denies adoption attempts if that object has a non-nil DeletionTimestamp.
+func RecheckDeletionTimestamp(getObject func() (metav1.Object, error)) func() error {
+	return func() error {
+		obj, err := getObject()
+		if err != nil {
+			return fmt.Errorf("can't recheck DeletionTimestamp: %v", err)
+		}
+		if obj.GetDeletionTimestamp() != nil {
+			return fmt.Errorf("%v/%v has just been deleted at %v", obj.GetNamespace(), obj.GetName(), obj.GetDeletionTimestamp())
```
Comment (enisoc) [inline pkg/controller/controller_ref_manager.go]: From the user's perspective, it's already been deleted if it has a DeletionTimestamp. The fact that the object still exists is an implementation detail.

**Comment by caesarxuchao** [comment]
Could you also add a comment in the controllerRefManager saying something like "a new controllerRefManager is expected to be constructed for each sync loop"?

The code lgtm, i assumed the tests had not changed since last revision.

File: pkg/controller/replicaset/replica_set_test.go (hunk 6 above)
Comment (enisoc) [inline pkg/controller/replicaset/replica_set_test.go]: The fakeHandlers that use this skipListerFunc are really just looking for updates (PUT). I hit a case where due to the changes, an additional GET happened on a subresource of `/replicasets`, so I expanded the set of paths that get ignored.

File: pkg/controller/deployment/deployment_controller_test.go (hunk 8 above)
Comment (enisoc) [inline pkg/controller/deployment/deployment_controller_test.go]: I think both interpretations of "deleted" have merit. My interpretation is that some client already issued the DELETE request and it succeeded. Almost everything should consider a controller with non-nil DeletionTimestamp as not existing anymore, so calling it "deleted" in the past tense reinforces that.

File: pkg/controller/controller_ref_manager.go (hunk 10 above)
Comment (caesarxuchao) [inline pkg/controller/controller_ref_manager.go]: I use "is being deleted" in this case.

Users do need to distinguish if an object is "being deleted" or "has been removed from the storage". For example, in the former case, the name is held and a user cannot create an object of the same name. Also, in the context of deleting a pod, "deleted" indicates the resources held by the pod are released, while "being deleted" means kubelet is still reclaiming the resources.

**Comment by enisoc** [comment]
> Could you also add a comment in the controllerRefManager saying something like "a new controllerRefManager is expected to be constructed for each sync loop"?

Done.

**Comment by enisoc** [comment]
@k8s-bot non-cri node e2e test this

**Comment by janetkuo** [comment]
LGTM too

**Comment by marun** [comment]
@janetkuo Can you approve?
