### PR TITLE
Fix endpoints status out-of-sync when the pod state changes rapidly

### LINKED ISSUE #125638: The endpoint status does not update when the pod state changes rapidly.
### What happened?

image

----
t2
1. Pod update event: ready to notReady
2. syncService
3. currentEndpoints state(from lister: Ready) do not equal to  target state(notReady)
4. clientSet.Endpoints.Update: update etcd to notReady

----
t3
1. Pod update event : notReady to ready(<xxMS)
2. syncService
3. **currentEndpoints state(from lister: Ready) equal to  target state(ready)，do not update Endpoints**

----
----
t4
1. Endpoint update event:  update endpoint lister cache to notReady
----

### What did you expect to happen?

The status of the endpoint should match the status of the pod.

### How can we reproduce it (as minimally and precisely as possible)?

Make the Pod status change rapidly. 
Lowering the etcd push interval should make it easier to reproduce.

### Anything else we need to know?

_No response_

### Kubernetes version

v1.25.3

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by tnqn**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

When Pod state changes rapidly, endpoints controller may use outdated informer cache to sync Service. If the outdated endpoints appear to be expected by the controller, it skips updating it.

The commit fixes it by checking if endpoints informer cache is outdated when processing a service. If the endpoints is stale, it returns an error and retries later.

#### Which issue(s) this PR fixes:

Fixes #125638

#### Does this PR introduce a user-facing change?

```release-note
Fix endpoints status out-of-sync when the pod state changes rapidly
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/endpoint/endpoints_controller.go [hunk 1]
```diff
@@ -105,6 +105,9 @@ func NewEndpointController(ctx context.Context, podInformer coreinformers.PodInf
 	e.podsSynced = podInformer.Informer().HasSynced
 
 	endpointsInformer.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
+		UpdateFunc: func(old, cur interface{}) {
```
[the remark this answers is not in the document]
Comment (tnqn) [reply pkg/controller/endpoint/endpoints_controller.go:108]: I found this change would break a conformance test: ["should test the lifecycle of an Endpoint"](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/125675/pull-kubernetes-e2e-gce/1805301677411012608).
However, the conformance test itself seems contradictory with some logic of endpoints controller:
* The conformance test expects an Endpoint created without a Service to exist
* The `checkLeftoverEndpoints` function of endpoint controller triggers syncing all Endpoints except for those having leader election annotation and will cause Endpoints without Services to be deleted: https://github.com/kubernetes/kubernetes/blob/921fb0b7c5850db9b109f28dd669b81b1522e055/pkg/controller/endpoint/endpoints_controller.go#L561-L567

The conformance test gives an impression that an user created Endpoints (without a Service) can exist but it will be deleted once kube-controller-manager restarts or fails over.

[the remark this answers is not in the document]
Comment (tnqn) [reply pkg/controller/endpoint/endpoints_controller.go:108]: It seems the conformance test would fail as long as the controller watches endpoints update events.

I'm thinking another fix which doesn't affect the conformance test and could avoid doubling the work: we track the stale resource versions of endpoints after each successful endpoints update, use it to determine whether the endpoints in cache is stale when syncing it next time, and return error if it's stale and retry. (The reason why we don't track generation like endpointslice controller is endpoints doesn't have a generation.)

**Comment by aojea** [comment]
@tnqn sorry for being very picky but everytime we change something here there are always unexpected edge cases, I think that adding an integration test that reproduces the problem, we can do multiple transitions in parallel if necessary to increase the chances of getting an stale cache entry, will give us more confidence

https://github.com/kubernetes/kubernetes/blob/742b2f70b9e5c1ec03682ad25dc76fdcc7109310/test/integration/endpoints/endpoints_test.go#L38

**Comment by tnqn** [comment]
> @tnqn sorry for being very picky but everytime we change something here there are always unexpected edge cases, I think that adding an integration test that reproduces the problem, we can do multiple transitions in parallel if necessary to increase the chances of getting an stale cache entry, will give us more confidence

@aojea no problem, I will add one.

File: test/integration/endpoints/endpoints_test.go [hunk 2]
```diff
@@ -158,6 +160,141 @@ func TestEndpointUpdates(t *testing.T) {
...
+			NodeName: &pod.Spec.NodeName,
+			TargetRef: &v1.ObjectReference{
+				Kind:      "Pod",
+				Namespace: pod.Namespace,
+				Name:      pod.Name,
+				UID:       pod.UID,
+			},
+		},
+	}
+	for _, service := range services {
```
Comment (aojea) [inline test/integration/endpoints/endpoints_test.go:277]: we want to assert that the final state is the correct one, so we need to be sure that both updates are processed by the endpoints controller ... since we are adding 10 workers to the endpoint controller we can not use the trick we used in the test above ... maybe is just enough to store the resource version in line 242 and in this loop also validate that we are actually checking the new generated endpoint and not the old one

File: test/integration/endpoints/endpoints_test.go [hunk 3]
```diff
@@ -158,6 +160,141 @@ func TestEndpointUpdates(t *testing.T) {
...
+		if err != nil {
+			t.Fatalf("Failed to create service %s: %v", svc.Name, err)
+		}
+		services = append(services, svc)
+	}
+
+	for _, service := range services {
+		// Ensure the new endpoints are created.
+		if err := wait.PollUntilContextTimeout(tCtx, 1*time.Second, 10*time.Second, true, func(context.Context) (bool, error) {
+			_, err := client.CoreV1().Endpoints(ns.Name).Get(tCtx, service.Name, metav1.GetOptions{})
```
Comment (aojea) [inline test/integration/endpoints/endpoints_test.go:242]: we can record here the endpoint and its resource version map[string]string

File: test/integration/endpoints/endpoints_test.go [hunk 4]
```diff
@@ -158,6 +160,141 @@ func TestEndpointUpdates(t *testing.T) {
...
+		var endpoints *v1.Endpoints
+		if err := wait.PollUntilContextTimeout(tCtx, 1*time.Second, 10*time.Second, false, func(context.Context) (bool, error) {
+			endpoints, err = client.CoreV1().Endpoints(ns.Name).Get(tCtx, service.Name, metav1.GetOptions{})
+			if err != nil {
+				t.Logf("Error fetching endpoints: %v", err)
+				return false, nil
+			}
+			if len(endpoints.Subsets) == 0 {
+				return false, nil
+			}
```
Comment (aojea) [inline test/integration/endpoints/endpoints_test.go:287]: we may also validate here that this is actually a new endpoint and not the one in https://github.com/kubernetes/kubernetes/pull/125675/files#r1659774958

File: pkg/controller/endpoint/endpoints_controller.go [hunk 5]
```diff
@@ -555,6 +561,9 @@ func (e *Controller) syncService(ctx context.Context, key string) error {
 
 		return err
 	}
+	if !createEndpoints {
+		e.staleEndpointsTracker.Stale(currentEndpoints)
```
Comment (aojea) [inline pkg/controller/endpoint/endpoints_controller.go:565]: we need to store the version of the endpoint we just created or we have updated , lines 535 to 541 of the new change

```
	if createEndpoints {
		// No previous endpoints, create them
		_, err = e.client.CoreV1().Endpoints(service.Namespace).Create(ctx, newEndpoints, metav1.CreateOptions{})
	} else {
		// Pre-existing
		_, err = e.client.CoreV1().Endpoints(service.Namespace).Update(ctx, newEndpoints, metav1.UpdateOptions{})
	}
```

so get the newEndpoint object and store the resource version here in the tracked independently if we created or updated, as we don't want to process it again

File: test/integration/endpoints/endpoints_test.go (hunk 2 above)
Comment (tnqn) [reply test/integration/endpoints/endpoints_test.go:277]: If a worker is not fast enough to process the 1st Pod update before the informer receives the 2nd Pod update, it will not make any change to the endpoints, which is also expected. The 10 workers may behave in one of the following ways:
1. update the endpoints to not ready, then update the endpoints to ready
2. do not update the endpoints at all

File: pkg/controller/endpoint/endpoints_controller.go (hunk 5 above)
Comment (aojea) [reply pkg/controller/endpoint/endpoints_controller.go:565]: At least this how I read it in the endpointslice code, but I wonder now if we should return error if is stale and retrying

Comment (tnqn) [reply pkg/controller/endpoint/endpoints_controller.go:565]: I tried tracking the new endpoints's resource version, but it does resolve the problem or would introduce new problem:
1. If we skip processing a service when the received endpoints update matches the tracked one, it doesn't resolve the original problem because the real problem is that when the controller processes the 2nd pod update (from not ready to ready), it used the stale ready endpoints and skipped updating the endpoints to be ready. Skipping the endpoints event caused by the 1st process changes nothing.
2. If we enqueue the service anyway if the received endpoints update matches the tracked one, then the tracked version would be used to check if the current endpoints match it and the worker would return error if they don't match. But that would cause that once the endpoints is updated by others (user or another controller), this controller will never process it again as the resource version will never match again.

Unlike endpointslice controller, which processes a Service when the endpointslices are equal to or newer than the tracked ones, there is no generation in endpoints object, so we don't know whether an unmatched endpoints is newer or older than the tracked one.

Therefore, instead of tracking the new endpoints's resource version, the patch trackes the old endpoints's resource version. In `syncService`, if it sees the resource version again, it means the cache is out-of-date, and there is no point to proceed. If it sees a different resource version, it means either it has received the last update made by itself, or the endpoints has been updated by others, in either case it should process it.

File: test/integration/endpoints/endpoints_test.go (hunk 2 above)
Comment (aojea) [reply test/integration/endpoints/endpoints_test.go:277]: yeah, but what if you get if in case 1. you get the value previous to the change to endpoints not ready?

Comment (aojea) [reply test/integration/endpoints/endpoints_test.go:277]: maybe we just add a 1 second time.sleep and call it a day,

Comment (tnqn) [reply test/integration/endpoints/endpoints_test.go:277]: Right, the `immediate` parameter of `PollUntilContextTimeout` is set to false to make it wait 1s, but maybe it should just wait for 1s for all endpoints, instead of 1s per endpoints.
https://github.com/kubernetes/kubernetes/pull/125675/files#diff-1f68d7d5faf56609b098ea3c3d5a186183eb9b972ea54b28924eab2f99696621R279

Comment (tnqn) [reply test/integration/endpoints/endpoints_test.go:282]: updated

File: test/integration/endpoints/endpoints_test.go (hunk 4 above)
Comment (aojea) [reply test/integration/endpoints/endpoints_test.go:292]: comment no longer valid, please resolve

File: test/integration/endpoints/endpoints_test.go (hunk 3 above)
Comment (aojea) [reply test/integration/endpoints/endpoints_test.go:242]: comment no longer valid, please resolve

File: pkg/controller/endpoint/endpoints_controller.go [hunk 6]
```diff
@@ -555,6 +561,9 @@ func (e *Controller) syncService(ctx context.Context, key string) error {
 
 		return err
 	}
+	if !createEndpoints {
```
Comment (aojea) [inline pkg/controller/endpoint/endpoints_controller.go:564]:
```suggestion
        // if the current endpoint is updated we track the old resource version, so
        // if we obtain this resource version again from the lister we know is outdated
        // and we need to retry later to wait for the informer cache to be up to date
	if !createEndpoints {
```

File: pkg/controller/endpoint/endpoints_controller.go [hunk 7]
```diff
@@ -473,6 +477,8 @@ func (e *Controller) syncService(ctx context.Context, key string) error {
 				Labels: service.Labels,
 			},
 		}
+	} else if e.staleEndpointsTracker.IsStale(currentEndpoints) {
+		return fmt.Errorf("endpoints informer cache is out of date")
```
Comment (aojea) [inline pkg/controller/endpoint/endpoints_controller.go:481]:
```suggestion
		return fmt.Errorf("endpoints informer cache is out of date, old resource version for endpoint %s/%s", namespace,name)
```

File: pkg/controller/endpoint/endpoints_controller.go (hunk 5 above)
Comment (aojea) [reply pkg/controller/endpoint/endpoints_controller.go:565]: now I got it, thanks

File: test/integration/endpoints/endpoints_test.go [hunk 8]
```diff
@@ -158,6 +160,146 @@ func TestEndpointUpdates(t *testing.T) {
 
 }
 
+func TestEndpointWithMultiplePodUpdates(t *testing.T) {
```
Comment (aojea) [inline test/integration/endpoints/endpoints_test.go:163]:
```suggestion
// regression test for https://issues.k8s.io/125638
func TestEndpointWithMultiplePodUpdates(t *testing.T) {
```

This test is great, it reproduces the problem

**Comment by aojea** [comment]
overall LGTM just some comments to add more comments and may be better not to export the new tracker

It took me a while to get it but I think is correct, however, it is tricky so a few more eyes on this will be nice, @robscott @gauravkghildiyal we went through a similar one recently with the slice controller, can you PTAL?

File: pkg/controller/endpoint/endpoints_controller.go (hunk 7 above)
Comment (tnqn) [reply pkg/controller/endpoint/endpoints_controller.go:481]: updated

File: pkg/controller/endpoint/endpoints_controller.go (hunk 6 above)
Comment (tnqn) [reply pkg/controller/endpoint/endpoints_controller.go:564]: added, thanks

File: pkg/controller/endpoint/endpoints_tracker.go [hunk 9]
```diff
@@ -0,0 +1,64 @@
...
+import (
+	"sync"
+
+	v1 "k8s.io/api/core/v1"
+	"k8s.io/apimachinery/pkg/types"
+)
+
+// StaleEndpointsTracker tracks Endpoints and their stale resource versions to
+// help determine if an Endpoints is stale.
+type StaleEndpointsTracker struct {
```
[the remark this answers is not in the document]
Comment (tnqn) [reply pkg/controller/endpoint/endpoints_tracker.go:28]: updated

File: pkg/controller/endpoint/endpoints_tracker_test.go [hunk 10]
```diff
@@ -0,0 +1,51 @@
...
+			Addresses: []v1.EndpointAddress{{IP: "6.7.8.9", NodeName: &emptyNodeName}},
+			Ports:     []v1.EndpointPort{{Port: 1000}},
+		}},
+	}
+
+	assert.False(t, tracker.IsStale(endpoints), "IsStale should return false before the endpoint is staled")
+
+	tracker.Stale(endpoints)
+	assert.True(t, tracker.IsStale(endpoints), "IsStale should return true after the endpoint is staled")
+
```
[the remark this answers is not in the document]
Comment (tnqn) [reply pkg/controller/endpoint/endpoints_tracker_test.go:48]: added

**Comment by tnqn** [comment]
@aojea thanks for reviewing. I have resolved all comments.

**Comment by gauravkghildiyal** [comment]
Thanks @tnqn. The proposed solution makes sense to me. Appreciate your provided explanation in https://github.com/kubernetes/kubernetes/pull/125675#discussion_r1659808084

/lgtm

**Comment by chymy** [comment]
/lgtm
Our environment has happened several times.

**Comment by robscott** [comment]
Thanks @tnqn!

/hold cancel

**Comment by robscott** [comment]
Actually I guess @aojea said Friday, but I think we likely have enough reviewers that have signed off on this now, will defer to him.

/hold

**Comment by aojea** [comment]
> Actually I guess @aojea said Friday, but I think we likely have enough reviewers that have signed off on this now, will defer to him.
> 
> /hold

/hold cancel

There are 3 additional reviews, more than enough 😄

**Comment by liggitt** [comment]
For visibility, backports of this regressed 1.30.3+, 1.29.7+, and 1.28.12+ (see https://github.com/kubernetes/kubernetes/issues/127370).

Make sure we stick to the criteria for backports. Backporting changes which are not regression fixes or critical bugfixes as described in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#what-kind-of-prs-are-good-for-cherry-picks should be avoided. Every backport carries risk, and in this case, we made patch releases worse with a backport.
