### PR TITLE
Fix flag passing in CCM

### LINKED ISSUE #44: Consuming cloud-provider appears problematic in 1.20
I've just upgraded the Brightbox cloud-controller to 1.20 and, in common with the AWS updates, I found the new interfaces into the library to be problematic, and the sample 'main' code to not work as I'd expected. 

Primarily the call to s.Config appears to be too early and the command line flags have not been enumerated at that point, so version and help doesn't work and neither do command line flags. 

I had to rewrite the top level interface along the lines of the AWS controller and move the call to s.Config back within the Cobra command function. 

Of course it's possible I've completely misunderstood how this interface is supposed to work in its new configuration and if anybody can explain that I'd be grateful.

The code I ended up with is here: https://github.com/brightbox/brightbox-cloud-controller-manager/blob/8acb44fc63a74ca14c96daec039a4d2473881e52/app/cloudcontroller.go

Which is based on the AWS main file here: https://github.com/kubernetes/cloud-provider-aws/blob/3b384bb6e144446cb8015ab83269d6f99ac00898/cmd/aws-cloud-controller-manager/main.go

### PR DESCRIPTION
**Pull request by cici37**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
This PR is to fix flag passing issue in CCM.
Updated related integration test.
Added README file and update the sample code of nodeIPAMController.

**Which issue(s) this PR fixes**:
Fix https://github.com/kubernetes/cloud-provider/issues/44

Fixes #

**Special notes for your reviewer**:
What I did to further verify: 
Have a fake nodeIPAMController without any logic to verify the flags only
https://github.com/kubernetes/kubernetes/compare/master...cici37:testNodeIPAMConrtoller?expand=1
The first test case passed and second test case failed as expected with message:
`F0302 11:48:29.566100 1600649 testserver.go:245] NodeIPAM controller values are not properly set.`

Will have a separate PR to add additional integration test like I have above.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

**Review by andrewsykim — COMMENTED** [review]
/assign @nicolehanjing

File: cmd/cloud-controller-manager/main.go [hunk 1]
```diff
@@ -57,64 +55,51 @@ const (
...
-	}
 
-	cloud, err := cloudprovider.InitCloudProvider(cloudProviderName, c.ComponentConfig.KubeCloudShared.CloudProvider.CloudConfigFile)
-	if err != nil {
-		klog.Fatalf("Cloud provider could not be initialized: %v", err)
-	}
-	if cloud == nil {
-		klog.Fatalf("cloud provider is nil")
-	}
+	cloudInitializer := func(config *cloudcontrollerconfig.CompletedConfig) cloudprovider.Interface {
```
Comment (cheftako) [inline cmd/cloud-controller-manager/main.go:63]: I think the anonymous function makes this harder to read/understand. Can we move this out to its own named function?

File: cmd/cloud-controller-manager/main.go [hunk 2]
```diff
@@ -125,20 +110,20 @@ func main() {
...
-	})
 	if err := command.Execute(); err != nil {
 		os.Exit(1)
 	}
 }
 
-func startNodeIpamControllerWrapper(ccmconfig *cloudcontrollerconfig.CompletedConfig, nodeIPAMConfig nodeipamconfig.NodeIPAMControllerConfiguration, cloud cloudprovider.Interface) func(ctx genericcontrollermanager.ControllerContext) (http.Handler, bool, error) {
+func startNodeIpamControllerWrapper(completedConfig *cloudcontrollerconfig.CompletedConfig, cloud cloudprovider.Interface) app.InitFunc {
+	nodeIPAMConfig := nodeipamconfig.NodeIPAMControllerConfiguration{
+		ServiceCIDR:          "sample",
```
Comment (cheftako) [inline cmd/cloud-controller-manager/main.go:120]: Shouldn't we be showing how to wire the command line values into the config object?

File: cmd/cloud-controller-manager/main.go (hunk 1 above)
Comment (cici37) [reply cmd/cloud-controller-manager/main.go:63]: I was thinking to give cloud provider the power to initialize cloud with the cloud provider name they specified so put it in main.go.

Comment (cheftako) [reply cmd/cloud-controller-manager/main.go:63]: No objection to having the code in main.go. My objection is to having a disjoint section of anonymous code in the middle of this function when we're not executing it here or now. If we create a named function with this code in it, we can pass it later where we need it and the code will read more easily.

File: cmd/cloud-controller-manager/main.go (hunk 2 above)
Comment (cici37) [reply cmd/cloud-controller-manager/main.go]: Updated

File: cmd/cloud-controller-manager/main.go (hunk 1 above)
Comment (cici37) [reply cmd/cloud-controller-manager/main.go:64]: Totally make sense. Let me update. Thank you ^^

File: cmd/cloud-controller-manager/main.go [hunk 3]
```diff
@@ -125,20 +82,52 @@ func main() {
...
+	cloud.Initialize(config.ClientBuilder, make(chan struct{}))
+	// Set the informer on the user cloud object
+	if informerUserCloud, ok := cloud.(cloudprovider.InformerUser); ok {
+		informerUserCloud.SetInformers(config.SharedInformers)
+	}
+
+	return cloud
+}
+
+func startNodeIpamControllerWrapper(completedConfig *cloudcontrollerconfig.CompletedConfig, cloud cloudprovider.Interface) app.InitFunc {
```
Comment (andrewsykim) [inline cmd/cloud-controller-manager/main.go:119]: I feel like this function should be an exported function somewhere else. Feels like too much is leaking here for a main.go file.

File: cmd/cloud-controller-manager/main.go [hunk 4]
```diff
@@ -125,20 +82,52 @@ func main() {
...
-			return
-		}
-	})
 	if err := command.Execute(); err != nil {
 		os.Exit(1)
 	}
 }
 
-func startNodeIpamControllerWrapper(ccmconfig *cloudcontrollerconfig.CompletedConfig, nodeIPAMConfig nodeipamconfig.NodeIPAMControllerConfiguration, cloud cloudprovider.Interface) func(ctx genericcontrollermanager.ControllerContext) (http.Handler, bool, error) {
+func cloudInitializer(config *cloudcontrollerconfig.CompletedConfig) cloudprovider.Interface {
```
Comment (andrewsykim) [inline cmd/cloud-controller-manager/main.go:90]: Does this have to be in main.go?

Comment (cici37) [reply cmd/cloud-controller-manager/main.go:90]: It definitely could be put somewhere else. I was thinking to have all necessary code in main and cloud providers only have to pay attention to main.go. They definitely could rearrange the code. Would you think it would be better to have a separate file for those kind of func?

File: cmd/cloud-controller-manager/.import-restrictions [hunk 5]
```diff
@@ -1,6 +1,8 @@
 rules:
   - selectorRegexp: k8s[.]io/kubernetes
     allowedPrefixes:
+      - k8s.io/kubernetes/cmd/kube-controller-manager/app/options
```
Comment (cheftako) [inline cmd/cloud-controller-manager/.import-restrictions:4]: When we talked to @liggitt about these changes, one of the things which was brought up was clearly delineating the sample (what we expect cloud providers to copy) from the example (showing how to extend the sample to do things like add new controllers). This seems to emphasize the importance of separating the sample from the example. This *only* belongs in the example and should not be in the sample.

File: cmd/cloud-controller-manager/main.go (hunk 4 above)
Comment (cheftako) [reply cmd/cloud-controller-manager/main.go:90]: Guessing this would be lost objectionable in the "example". Clearly should not be in our sample.

File: cmd/cloud-controller-manager/.import-restrictions (hunk 5 above)
Comment (cheftako) [reply cmd/cloud-controller-manager/.import-restrictions:4]: Seems like we should have a README.md file in cmd/cloud-controller-manager which clearly states that this directory is an example (POC) of using the CCM extension mechanisms. Further that new cloud providers should copy the CCM from k8s.io/cloud-provider/sample/basic_main.go. Possibly even basic instructions for doing this.

File: cmd/cloud-controller-manager/main.go (hunk 3 above)
Comment (cheftako) [reply cmd/cloud-controller-manager/main.go:119]: +1, all for breaking the node ipam example code into its own file.

File: cmd/cloud-controller-manager/main.go (hunk 4 above)
Comment (cici37) [reply cmd/cloud-controller-manager/main.go:86]: Thanks for review. Added an README.md to further explain.

File: cmd/cloud-controller-manager/.import-restrictions (hunk 5 above)
Comment (cici37) [reply cmd/cloud-controller-manager/.import-restrictions:4]: Added README

File: cmd/cloud-controller-manager/main.go (hunk 3 above)
Comment (cici37) [reply cmd/cloud-controller-manager/main.go]: Updated

File: cmd/cloud-controller-manager/README.md [hunk 6]
```diff
@@ -0,0 +1,14 @@
+# cloud-controller-manager/example
```
Comment (andrewsykim) [inline cmd/cloud-controller-manager/README.md:1]: side note: this is starting to look like code we should eventually move to https://github.com/kubernetes/cloud-provider-sample in the future

**Review by andrewsykim — COMMENTED** [review]
@cici37 would it be possible to add a component test so we don't regress?

**Comment by cici37** [comment]
> Cici Huang would it be possible to add a component test so we don't regress?

I was looking into the possible way to address the test. Currently the startTestServer directly call Run func instead of NewCloudControllerManagerCommand(). It would be great if we have a test for cobra command. However, I did not find much good practice for that and `NewCloudControllerManagerCommand()` will do `os.Exit` which will also cause trouble on testing. I have a demo idea in the latest commit. Would you mind to share your thoughts on it? Thank you

**Comment by cici37** [comment]
@andrewsykim @cheftako @jpbetz 
I updated the integration test to fill the test gap and update the func accordingly. Would you please have a look at this PR when you have time? Thank you 🙏

**Review by jpbetz — CHANGES_REQUESTED** [review]

File: cmd/cloud-controller-manager/nodeipamcontroller.go [hunk 7]
```diff
@@ -45,6 +49,22 @@ const (
 	defaultNodeMaskCIDRIPv6 = 64
 )
 
+func startNodeIpamControllerWrapper(completedConfig *cloudcontrollerconfig.CompletedConfig, cloud cloudprovider.Interface) app.InitFunc {
+	fs := pflag.NewFlagSet("fs", pflag.ContinueOnError)
+	var nodeIPAMControllerOptions nodeipamcontrolleroptions.NodeIPAMControllerOptions
+	nodeIPAMControllerOptions.AddFlags(fs)
+	errors := nodeIPAMControllerOptions.Validate()
+	if len(errors) > 0 {
+		klog.Fatal("NodeIPAM controller values are not properly.")
```
[the remark this answers is not in the document]
Comment (cici37) [reply cmd/cloud-controller-manager/nodeipamcontroller.go]: Updated

File: staging/src/k8s.io/cloud-provider/app/controllermanager.go [hunk 8]
```diff
@@ -64,21 +64,33 @@ const (
 )
 
 // NewCloudControllerManagerCommand creates a *cobra.Command object with default parameters
-func NewCloudControllerManagerCommand(s *options.CloudControllerManagerOptions, c *cloudcontrollerconfig.Config, controllerInitializers map[string]InitFunc) *cobra.Command {
+func NewCloudControllerManagerCommand(s *options.CloudControllerManagerOptions, cloudInitializer InitCloudFunc, initFuncConstructor map[string]InitFuncConstructor, stopCh <-chan struct{}) *cobra.Command {
```
[the remark this answers is not in the document]
Comment (cici37) [reply staging/src/k8s.io/cloud-provider/app/controllermanager.go:67]: There are comments for InitCloudFunc and InitFuncConstructor where defined. 😊

File: staging/src/k8s.io/cloud-provider/app/controllermanager.go [hunk 9]
```diff
@@ -64,21 +64,33 @@ const (
...
 			verflag.PrintAndExitIfRequested()
 			cliflag.PrintFlags(cmd.Flags())
 
-			if err := Run(c.Complete(), controllerInitializers, wait.NeverStop); err != nil {
+			c, err := s.Config(ControllerNames(initFuncConstructor), ControllersDisabledByDefault.List())
+			if err != nil {
 				fmt.Fprintf(os.Stderr, "%v\n", err)
-				os.Exit(1)
+				return err
+				//os.Exit(1)
```
[the remark this answers is not in the document]
Comment (cici37) [reply staging/src/k8s.io/cloud-provider/app/controllermanager.go]: Updated

File: staging/src/k8s.io/cloud-provider/app/controllermanager.go [hunk 10]
```diff
@@ -64,21 +64,33 @@ const (
...
 			}
 
+			completedConfig := c.Complete()
+			cloud := cloudInitializer(completedConfig)
+			controllerInitializers := ConstructControllerInitializers(initFuncConstructor, completedConfig, cloud)
+
+			if err := Run(completedConfig, cloud, controllerInitializers, stopCh); err != nil {
+				fmt.Fprintf(os.Stderr, "%v\n", err)
+				return err
+				//os.Exit(1)
```
[the remark this answers is not in the document]
Comment (cici37) [reply staging/src/k8s.io/cloud-provider/app/controllermanager.go]: Updated

File: staging/src/k8s.io/cloud-provider/app/testing/testserver.go [hunk 11]
```diff
@@ -79,58 +82,94 @@ func StartTestServer(t Logger, customFlags []string) (result TestServer, err err
...
-	for _, f := range namedFlagSets.FlagSets {
-		fs.AddFlagSet(f)
-	}
-	fs.Parse(customFlags)
-	if s.SecureServing.BindPort != 0 {
-		s.SecureServing.Listener, s.SecureServing.BindPort, err = createListenerOnFreePort()
+
+	cloudInitializer := func(config *config.CompletedConfig) cloudprovider.Interface {
+		capturedConfig = *config
+		configDoneCh <- ""
```
[the remark this answers is not in the document]
Comment (cici37) [reply staging/src/k8s.io/cloud-provider/app/testing/testserver.go:93]: Added comments for configDoneCh

[the remark this answers is not in the document]
Comment (jpbetz) [reply staging/src/k8s.io/cloud-provider/app/testing/testserver.go:93]: As we discussed, I suspect you might be able to avoid sending a message on the channel here just to signal since closing a channel is already a signal that receivers can respond to.

File: staging/src/k8s.io/cloud-provider/app/controllermanager.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (jpbetz) [reply staging/src/k8s.io/cloud-provider/app/controllermanager.go:67]: As we discussed, more detail on what the map keys would have helped me understand this better. I agree that the existing godoc on InitCloudFunc is sufficient.

File: staging/src/k8s.io/cloud-provider/app/testing/testserver.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (cici37) [reply staging/src/k8s.io/cloud-provider/app/testing/testserver.go]: Updated. Thank you

File: staging/src/k8s.io/cloud-provider/app/controllermanager.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (cici37) [reply staging/src/k8s.io/cloud-provider/app/controllermanager.go:68]: Updated. Thank you

**Comment by jpbetz** [comment]
/lgtm

@cheftako would you have another look?

**Comment by cici37** [comment]
@jpbetz @cheftako The PR was updated. Would you please have a look when have time? Thank you😊

File: cmd/cloud-controller-manager/main.go [hunk 12]
```diff
@@ -42,79 +40,38 @@ import (
...
 	nodeipamconfig "k8s.io/kubernetes/pkg/controller/nodeipam/config"
 	// For existing cloud providers, the option to import legacy providers is still available.
 	// e.g. _"k8s.io/legacy-cloud-providers/<provider>"
 )
 
-const (
-	// cloudProviderName shows an sample of using hard coded parameter, please edit the value for your case.
-	cloudProviderName = "SampleCloudProviderName"
-)
+var nodeIPAMControllerConfiguration nodeipamconfig.NodeIPAMControllerConfiguration
```
[the remark this answers is not in the document]
Comment (jpbetz) [reply cmd/cloud-controller-manager/main.go]: I like the idea we discussed out-of-band about moving this into a struct in nodeipamcontroller.go so we don't need any globals.

File: staging/src/k8s.io/cloud-provider/app/controllermanager.go [hunk 13]
```diff
@@ -64,21 +65,32 @@ const (
 )
 
 // NewCloudControllerManagerCommand creates a *cobra.Command object with default parameters
-func NewCloudControllerManagerCommand(s *options.CloudControllerManagerOptions, c *cloudcontrollerconfig.Config, controllerInitializers map[string]InitFunc) *cobra.Command {
+// initFuncConstructor is a map of named controller groups (you can start more than one in an init func) paired to their InitFuncConstructor.
+func NewCloudControllerManagerCommand(s *options.CloudControllerManagerOptions, cloudInitializer InitCloudFunc, initFuncConstructor map[string]InitFuncConstructor, additionalFlags *pflag.FlagSet, stopCh <-chan struct{}) *cobra.Command {
```
[the remark this answers is not in the document]
Comment (cici37) [reply staging/src/k8s.io/cloud-provider/app/controllermanager.go]: Added. Thanks

File: cmd/cloud-controller-manager/main.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (cici37) [reply cmd/cloud-controller-manager/main.go]: Updated. Thanks

**Comment by cheftako** [comment]
/approve
Can we file an issue to look into @jpbetz idea for reworking the interface to make adding/removing controllers more intuitive?

**Comment by cici37** [comment]
> /approve
> Can we file an issue to look into Joe Betz idea for reworking the interface to make adding/removing controllers more intuitive?

Here is the issue: https://github.com/kubernetes/kubernetes/issues/99725  Thank you

**Comment by andrewsykim** [comment]
@cici37 can we backport this to v1.20 please? I think v1.20 cloud-provider is still broken without this fix. cc @nicolehanjing

**Comment by cici37** [comment]
> Cici Huang can we backport this to v1.20 please? I think v1.20 cloud-provider is still broken without this fix. cc Nicole Han

Thanks for the reminder: https://github.com/kubernetes/kubernetes/pull/100722
