### PR TITLE
Fix a flaky e2e test of Job completion

### LINKED ISSUE #86333: [Flaky test] [sig-apps] Job should run a job to completion when tasks sometimes fail and are not locally restarted
**Which jobs are flaking**:
pull-kubernetes-e2e-kind

**Which test(s) are flaking**:
* `[sig-apps] Job should run a job to completion when tasks sometimes fail and are not locally restarted`

**Testgrid link**:
https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-kind&include-filter-by-regex=Job.*completion

**Reason for failure**:

**Anything else we need to know**:
https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=Job%20should%20run%20a%20job%20to%20completion%20when%20tasks%20sometimes%20fail%20and%20are%20not%20locally%20restarted

/sig apps

### PR DESCRIPTION
**Pull request by tnqn**
**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
The test was flaky because it required the job succeeds 3 times with pseudorandom 50% failure chance within 15 minutes, while there is an exponential back-off delay (10s, 20s, 40s …) capped at 6 minutes before recreating failed pods. As 7 consecutive failures (1/128 chance) could take 20+ minutes, exceeding the timeout, the test failed intermittently because of "timed out waiting for the condition".

This PR forces the Pods of a Job to be scheduled to a single node and uses a hostPath volume instead of an emptyDir to persist data across new Pods.

**Which issue(s) this PR fixes**:

Fixes #86333

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs

```

### CODE REVIEW

File: test/e2e/apps/job.go [hunk 1]
```diff
@@ -112,21 +114,45 @@ var _ = SIGDescribe("Job", func() {
 	// Pods sometimes fail, but eventually succeed, after pod restarts
 	ginkgo.It("should run a job to completion when tasks sometimes fail and are not locally restarted", func() {
 		ginkgo.By("Creating a job")
-		// 50% chance of container success, local restarts.
+		// Success and failure alternate, no local restarts.
 		// Can't use the failOnce approach because that relies
 		// on an emptyDir, which is not preserved across new pods.
```
Comment (liggitt) [inline test/e2e/apps/job.go]: rather than an emptyDir or a http callback, can we force the jobs to be scheduled to a single node and use a hostPath volume instead of an emptyDir? cc @kubernetes/sig-storage-misc

File: test/e2e/apps/job.go [hunk 2]
```diff
@@ -112,21 +114,45 @@ var _ = SIGDescribe("Job", func() {
...
+				}
+			}
+			pods, err := jobutil.GetJobPods(f.ClientSet, f.Namespace.Name, job.Name)
+			if err != nil {
+				return false, fmt.Errorf("failed to get PodList for job %s in namespace: %s", job.Name, f.Namespace.Name)
+			}
+			for _, pod := range pods.Items {
+				if pod.Status.Phase == v1.PodRunning {
+					// Fail if numPods is odd, otherwise succeed.
+					cmd := fmt.Sprintf("curl -q -s --connect-timeout 2 http://%s/exit?code=%d", pod.Status.PodIP, numPods%2)
```
Comment (liggitt) [inline test/e2e/apps/job.go]: I don't think host curl invocations will work reliably across network topologies and node types. if the hostPath volume ends up not working out, and we need to do a network callback, I'd recommend using the `/api/v1/namespaces/$ns/pods/$pod:80/proxy/exit?code=%d` approach

Comment (liggitt) [reply test/e2e/apps/job.go]: > Fail if numPods is odd, otherwise succeed

it's not clear why this is correct

File: test/e2e/apps/job.go (hunk 1 above)
Comment (tnqn) [reply test/e2e/apps/job.go]: Good idea, I have updated in this way and verified it can work. PTAL.

File: test/e2e/apps/job.go (hunk 2 above)
Comment (tnqn) [reply test/e2e/apps/job.go]: The command was run in a agnhost pod so should work, but anyway I have changed to use hostPath volume and schedule Pods to a single Node as you suggested.

**Review by tnqn — COMMENTED** [review]
Thanks @liggitt for the suggestion. Updated and PTAL.

File: test/e2e/apps/job.go [hunk 3]
```diff
@@ -111,18 +110,20 @@ var _ = SIGDescribe("Job", func() {
...
-		// on an emptyDir, which is not preserved across new pods.
-		// Worst case analysis: 15 failures, each taking 1 minute to
-		// run due to some slowness, 1 in 2^15 chance of happening,
-		// causing test flake.  Should be very rare.
-		// With the introduction of backoff limit and high failure rate this
-		// is hitting its timeout, the 3 is a reasonable that should make this
-		// test less flaky, for now.
-		job := jobutil.NewTestJob("randomlySucceedOrFail", "rand-non-local", v1.RestartPolicyNever, parallelism, 3, nil, 999)
-		job, err := jobutil.CreateJob(f.ClientSet, f.Namespace.Name, job)
+		job := jobutil.NewTestJob("failOnce", "fail-once-non-local", v1.RestartPolicyNever, parallelism, completions, nil, backoffLimit, node.Name)
```
Comment (mattjmcnaughton) [inline test/e2e/apps/job.go]: Is it intentional that we are changing the value of `completions` and `backoffLimit` values here? My guess is that the change is intentional... from my reading of the comment, it seemed like we had to set some custom values for these because we couldn't rely on the `failOnce` approach. But I just want to double check.

File: test/e2e/apps/job.go [hunk 4]
```diff
@@ -111,18 +110,20 @@ var _ = SIGDescribe("Job", func() {
 
 	// Pods sometimes fail, but eventually succeed, after pod restarts
 	ginkgo.It("should run a job to completion when tasks sometimes fail and are not locally restarted", func() {
+		// One failure, then a success, no local restarts.
+		// We can't use the random failure approach, because JobController
+		// will throttle frequently failing Pods of a given Job, ramping
+		// up to 6 minutes between restarts, making test timeout due to
```
Comment (mattjmcnaughton) [inline test/e2e/apps/job.go]: Nit: This comment says `JobController` will throttle up to 6 minutes between restarts, while the above comment says the Kubelet will throttle up to 5 minutes before restarts. Is one of these more accurate that the other?

File: test/e2e/apps/job.go [hunk 5]
```diff
@@ -111,18 +110,20 @@ var _ = SIGDescribe("Job", func() {
...
+		// successive failures.
+		// Instead, we force the Job's Pods to be scheduled to a single Node
```
Comment (mattjmcnaughton) [inline test/e2e/apps/job.go]: I just want to confirm that making this change doesn't violate the spirit of the test:

The test description says `"it should run a job to completion when tasks sometimes fail and are not locally restarted."` Am I understanding correctly that the `not locally restarted` component refers to the `v1.RestartPolicyNever`? Or does `not locally restarted` mean that we want to ensure the pod is actually running on different nodes?

If the former is true, I agree with the approach you've taken. However, if the later is true, I worry that the changes made here may be violating the spirit of the test.

File: test/e2e/apps/job.go [hunk 6]
```diff
@@ -41,7 +42,7 @@ var _ = SIGDescribe("Job", func() {
 	// Simplest case: N pods succeed
 	ginkgo.It("should run a job to completion when tasks succeed", func() {
 		ginkgo.By("Creating a job")
-		job := jobutil.NewTestJob("succeed", "all-succeed", v1.RestartPolicyNever, parallelism, completions, nil, backoffLimit)
+		job := jobutil.NewTestJob("succeed", "all-succeed", v1.RestartPolicyNever, parallelism, completions, nil, backoffLimit, "")
```
Comment (mattjmcnaughton) [inline test/e2e/apps/job.go]: Nit: I think adding the `""` as the final argument harms the readability of `NewTestJob`. For someone seeing just the function call, its not clear what the purpose of `""` is.

I think there are a couple of options:

1. We could give `""` a descriptive variable name... for example:
```
runOnAnyNode := ""
job := jobutil.NewTestJob(...", runOnAnyNode)
```
2. We could define two separate functions - one for running a function on a random node and one for testing a job on a dedicated node. Then, only the tests which actually need to specify a specific node would need to concern themselves with this parameter. These separate functions could share code to decrease duplication.

**Review by mattjmcnaughton — COMMENTED** [review]
Cool! Thank you for your work squashing this flake :)

I left some comments - looking forward to discussing :)

File: test/e2e/apps/job.go (hunk 6 above)
Comment (tnqn) [reply test/e2e/apps/job.go]: Nice suggestion, I applied the second one, now only necessary invocation is affected.

File: test/e2e/apps/job.go (hunk 4 above)
Comment (tnqn) [reply test/e2e/apps/job.go]: The above "local restarts" test set `restartPolicy` as `OnFailure` so it's kubelet that recreates the failed **container**, its max backoff period is indeed 5 minutes:
https://github.com/kubernetes/kubernetes/blob/429ad7db4f9e5a645d562548f514be94cd717c6c/pkg/kubelet/kubelet.go#L137

The "no local restarts" test set `restartPolicy` as `Never` so it's `JobController` that recreates the failed **Pod** of a given Job, its max backoff period is 6 minutes:
https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#pod-backoff-failure-policy
https://github.com/kubernetes/kubernetes/blob/429ad7db4f9e5a645d562548f514be94cd717c6c/pkg/controller/job/job_controller.go#L60

File: test/e2e/apps/job.go (hunk 5 above)
Comment (tnqn) [reply test/e2e/apps/job.go]: According to the difference of the two tests that only `RestartPolicy` is changed, I think it's the former, I guess "locally restart" here means kubelet recreates the failed containers of the Pod locally:
`should run a job to completion when tasks sometimes fail and are locally restarted`
`should run a job to completion when tasks sometimes fail and are not locally restarted`

If my understanding is wrong, I guess we will have to use the http approach to conduct the Pod succeed and fail like my first approach did, but it looks not clear like the current one @liggitt suggested.

File: test/e2e/apps/job.go (hunk 3 above)
Comment (tnqn) [reply test/e2e/apps/job.go]: I checked the commit history of the test and found it was decreased to 3 to make is less flaky as the default completions 4 was harder to reach and it expected to fail many times when it depended on random failure approach:
https://github.com/kubernetes/kubernetes/commit/90e7b5ff4fa5dc481ac4367d743da0d9d3fd3bcb
https://github.com/kubernetes/kubernetes/commit/9991a88870a8b6674e46e64e5d91f5bc9ea720b8
So I think as it's going to be stable after switching to `failOnce` approach, better to keep unified arguments for the similar two cases. What do you think?

**Comment by tnqn** [comment]
Thanks @mattjmcnaughton for reviewing and the nice suggestion! I have updated, PTAL.

File: test/e2e/apps/job.go (hunk 5 above)
Comment (liggitt) [reply test/e2e/apps/job.go]: the containers are not locally restarted, they fail and drive completely new pods/containers

File: test/e2e/framework/job/fixtures.go [hunk 7]
```diff
@@ -54,7 +64,7 @@ func NewTestJob(behavior, name string, rPol v1.RestartPolicy, parallelism, compl
 						{
 							Name: "data",
 							VolumeSource: v1.VolumeSource{
-								EmptyDir: &v1.EmptyDirVolumeSource{},
+								HostPath: &v1.HostPathVolumeSource{Path: "/tmp"},
```
Comment (liggitt) [inline test/e2e/framework/job/fixtures.go]: this path should be scoped and made more narrow (e.g. `/tmp/job-e2e/$random-dir`), not expose all of /tmp to the pod (and leave the touch command below alone)

File: test/e2e/framework/job/fixtures.go [hunk 8]
```diff
@@ -88,12 +99,12 @@ func NewTestJob(behavior, name string, rPol v1.RestartPolicy, parallelism, compl
 		// Dividing by 16384 gives roughly 50/50 chance of success.
 		job.Spec.Template.Spec.Containers[0].Command = []string{"/bin/sh", "-c", "exit $(( $RANDOM / 16384 ))"}
 	case "failOnce":
-		// Fail the first the container of the pod is run, and
-		// succeed the second time. Checks for file on emptydir.
-		// If present, succeed.  If not, create but fail.
-		// Note that this cannot be used with RestartNever because
-		// it always fails the first time for a pod.
-		job.Spec.Template.Spec.Containers[0].Command = []string{"/bin/sh", "-c", "if [[ -r /data/foo ]] ; then exit 0 ; else touch /data/foo ; exit 1 ; fi"}
+		// Fail the Pod the first time it is run, and succeeds subsequently.
```
Comment (liggitt) [inline test/e2e/framework/job/fixtures.go]: revert these changes

File: test/e2e/framework/job/fixtures.go (hunk 7 above)
Comment (liggitt) [reply test/e2e/framework/job/fixtures.go]: also, should we only make this a HostPath volume if nodeName is set?

File: test/e2e/apps/job.go (hunk 4 above)
Comment (mattjmcnaughton) [reply test/e2e/apps/job.go]: Ah gotcha! This is great info - let's add it to the comment?

**Review by mattjmcnaughton — COMMENTED** [review]
Looking good!

I'll let @liggitt give the final sign off as I think he still has some requests. But outside of his requests, this looks good to me :)

Thanks!

File: test/e2e/framework/job/fixtures.go (hunk 7 above)
Comment (tnqn) [reply test/e2e/framework/job/fixtures.go]: Done

File: test/e2e/framework/job/fixtures.go (hunk 8 above)
Comment (tnqn) [reply test/e2e/framework/job/fixtures.go]: Done

File: test/e2e/apps/job.go (hunk 4 above)
Comment (tnqn) [reply test/e2e/apps/job.go]: Sorry, what info did you mean to add? The comment has included "kubelet will ... 5 minutes, JobController will ... 6 minutes", did you mean more details?

**Review by tnqn — COMMENTED** [review]
Thanks @liggitt, addressed your comments, PTAL.

**Comment by tnqn** [comment]
Failed on unrelated test: "should run the container as unprivileged when false [LinuxOnly] [NodeConformance] [Conformance] [It]"
/retest

**Comment by mattjmcnaughton** [comment]
> /retest

If It's helpful, you can run just `/test TEST_NAME` to only re-run a specific test. It'll give you quicker feedback and is also lighter load on CI :)

**Comment by liggitt** [comment]
`/retest` is fine, it only reruns failed jobs

**Comment by mattjmcnaughton** [comment]
On Mon, Dec 30, 2019 at 09:15:35AM -0800, Jordan Liggitt wrote:
> `/retest` is fine, it only reruns failed jobs
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kubernetes/kubernetes/pull/86627#issuecomment-569737928

Today I learned :) Thanks for the extra info! Ignore my previous comment than
haha...

**Comment by liggitt** [comment]
this approach looks good to me. cc @kubernetes/sig-storage-pr-reviews for a sanity check on the local volume approach with a job pinned to run on a single node

**Comment by liggitt** [comment]
(triggering additional test runs to exercise the solution)

/lgtm
/approve
/hold for sig-storage ack on approach

**Comment by gnufied** [comment]
Switching to hostpath will mean this test will not work on RHEL or any selinux enabled distros fwiw. We might have to parameterize the test so as pod can be made privileged optionally.

**Comment by tnqn** [comment]
> Switching to hostpath will mean this test will not work on RHEL or any selinux enabled distros fwiw. We might have to parameterize the test so as pod can be made privileged optionally.

Thanks @gnufied for the information! I referred to `"should support r/w [NodeConformance]"` test:
https://github.com/kubernetes/kubernetes/blob/9269b5d43053d792c163d49ee383cdf9d19cd80a/test/e2e/common/host_path.go#L68-L73
and parameterized the privileged mode. I see it doesn't check whether the node enables selinux but sets privileged mode for all linux distros so did the same, please see update at https://github.com/kubernetes/kubernetes/pull/86627/files#diff-013109664f231fa6c9512547c9933f89R113 and let me know if it makes sense to you.

**Comment by liggitt** [comment]
@gnufied can you verify the adjusted test will work properly?

**Comment by gnufied** [comment]
@liggitt I ran the test on Fedora and it appears to be running fine. lgtm
