### PR TITLE
kubeadm: fix inconsistent usage for --experimental-patches in join phases

### LINKED ISSUE #2435: inconsistent usage for --experimental-patches in join phases
as discovered in https://github.com/kubernetes/kubernetes/issues/100869

the `--experimental-patches` flag can be used with:
`kubeadm join phase control-plane-prepare all`

but not with:
`kubeadm join phase control-plane-join all`
it can only be passed explicitly to the sub-phase `etcd` like so:
`kubeadm join phase control-plane-join etcd --experimental-patches`

ref list of phases for join:
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/

https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/phases/join/controlplaneprepare.go#L81
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/phases/join/controlplanejoin.go#L46-L47

ideally we should have consistency here.

perhaps it is better to make parent phases receive the flag, to avoid users breaking a phase in sub-phases to pass a flag. breaking a phase in sub-phases can be difficult to maintain.

### PR DESCRIPTION
**Pull request by SataQiu**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
kubeadm: fix inconsistent usage for `--experimental-patches` in join phases
Enable '--experimental-patches' flag for 'kubeadm join phase control-plane-join all' command

#### Which issue(s) this PR fixes:

Fixes kubernetes/kubeadm#2435

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: enable '--experimental-patches' flag for 'kubeadm join phase control-plane-join all' command
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/cmd/phases/join/controlplanejoin.go [hunk 1]
```diff
@@ -38,16 +38,31 @@ var controlPlaneJoinExample = cmdutil.Examples(`
 `)
 
 func getControlPlaneJoinPhaseFlags(name string) []string {
-	flags := []string{
-		options.CfgPath,
-		options.ControlPlane,
-		options.NodeName,
-	}
-	if name == "etcd" {
```
Comment (neolit123) [inline cmd/kubeadm/app/cmd/phases/join/controlplanejoin.go:46]: isn't it simpler to just have this here?

```
if name == "etcd" || name == "all" {
```

Comment (SataQiu) [reply cmd/kubeadm/app/cmd/phases/join/controlplanejoin.go:46]: Yes, it is simpler! 
I originally referred to the format in `controlplaneprepare.go#getControlPlanePreparePhaseFlags` 😅

**Review by neolit123 — COMMENTED** [review]
thanks @SataQiu 

/lgtm
/approve
/triage accepted
/priority backlog
