### PR TITLE
[InPlacePodVerticalScaling] fix restore checkpoint bug: failed to verify pod status checkpoint checksum because of different behaviors of func Quantity.Marshal and Quantity.Unmarshal

### LINKED ISSUE #128375: [FG:InPlacePodVerticalScaling] failed to verify pod status checkpoint checksum because of different behaviors of func Quantity.Marshal and Quantity.Unmarshal
### What happened?

One line bug description: the content func [stateCheckpoint.storeState](https://github.com/kubernetes/kubernetes/blob/60c4c2b2521fb454ce69dee737e3eb91a25e0535/pkg/kubelet/status/state/state_checkpoint.go#L80) writes into the file /var/lib/kubelet/pod_status_manager_state is different from it func [stateCheckpoint.restoreState](https://github.com/kubernetes/kubernetes/blob/60c4c2b2521fb454ce69dee737e3eb91a25e0535/pkg/kubelet/status/state/state_checkpoint.go#L59) reads from the same file, which causes function [VerifyChecksum](https://github.com/kubernetes/kubernetes/blob/60c4c2b2521fb454ce69dee737e3eb91a25e0535/pkg/kubelet/status/state/checkpoint.go#L59) always fails for some format of Quantity value.

### What did you expect to happen?

Kubelet doesn't crash and can start normally

### How can we reproduce it (as minimally and precisely as possible)?

1. prepare a pod spec with content below
```yaml
{
  "apiVersion": "v1",
  "kind": "Pod",
  "metadata": {
    "name": "nginx2"
  },
  "spec": {
    "containers": [
      {
        "name": "nginx",
        "image": "nginx:1.14.2",
        "ports": [
          {
            "containerPort": 80
          }
        ],
        "resources": {
          "requests": {
            "cpu": "0.4",
            "memory": "1Gi"
          },
          "limits": {
            "cpu": "1.5",
            "memory": "1Gi"
          }
        }
      }
    ]
  }
}
```
2. copy the pod spec into dir /etc/kubernetes/manifest/ in master node
3. restart the kubelet systemctl restart kubelet
4. the kubelet will crash all the time until the file /var/lib/kubelet/pod_status_manager_state is deleted
5. error message would be like below
```text
Aug 10 04:39:38 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 10 04:39:38 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 10 04:39:38 minikube kubelet[1190750]:         k8s.io/kubernetes/cmd/kubelet/app/server.go:1239 +0x90
Aug 10 04:39:38 minikube kubelet[1190750]: created by k8s.io/kubernetes/cmd/kubelet/app.startKubelet in goroutine 1
Aug 10 04:39:38 minikube kubelet[1190750]:         k8s.io/kubernetes/pkg/kubelet/kubelet.go:1628 +0x658
Aug 10 04:39:38 minikube kubelet[1190750]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run(0x4000ccac08, 0x4000ca1140)
Aug 10 04:39:38 minikube kubelet[1190750]:         k8s.io/kubernetes/pkg/kubelet/status/status_manager.go:204 +0x28c
Aug 10 04:39:38 minikube kubelet[1190750]: k8s.io/kubernetes/pkg/kubelet/status.(*manager).Start(0x40007a3a70)
Aug 10 04:39:38 minikube kubelet[1190750]: goroutine 239 [running]:
Aug 10 04:39:38 minikube kubelet[1190750]: panic: could not restore state from checkpoint: checkpoint is corrupted, please drain this node and delete pod allocation checkpoint file "/var/lib/kubelet/pod_status_manager_state" before restarting Kubelet
Aug 10 04:39:38 minikube kubelet[1190750]: E0810 04:39:38.722303 1190750 status_manager.go:203] "Could not initialize pod allocation checkpoint manager, please drain node and remove policy state file" err="could not restore state from checkpoint: checkpoint is corrupted, please drain this node and delete pod allocation checkpoint file \"/var/lib/kubelet/pod_status_manager_state\" before restarting Kubelet"
```

## Root cause
The json marshal function of Quantity type will convert itself to CanonicalBytes
https://github.com/kubernetes/apimachinery/blob/95b78024e3feada7739b40426690b4f287933fd8/pkg/api/resource/quantity.go#L452C25-L452C41
But the json unmarshal function of Quantity type won't do that.
https://github.com/kubernetes/apimachinery/blob/95b78024e3feada7739b40426690b4f287933fd8/pkg/api/resource/quantity.go#L701
For some formats for Quantity value, the Quantity contents, wrote to and read from the same file, might be different.
For example, if the pod cpu request is defined as cpu: "0.4", the Quantity content is cpu:{{4 -1} {<nil>}  DecimalSI before writing it into the file, but the content is cpu:{{400 -3} {<nil>} 400m DecimalSI after reading from the same file.

According to the reason above, the function [VerifyChecksum](https://github.com/kubernetes/kubernetes/blob/60c4c2b2521fb454ce69dee737e3eb91a25e0535/pkg/kubelet/status/state/checkpoint.go#L59) might fail.

## Detailed test case
<details>

```go
=== RUN   Test_stateCheckpoint_storeState
=== RUN   Test_stateCheckpoint_storeState/format_0_-_cpu_1Ki
=== RUN   Test_stateCheckpoint_storeState/format_1_-_cpu_1Mi
=== RUN   Test_stateCheckpoint_storeState/format_2_-_cpu_1Gi
=== RUN   Test_stateCheckpoint_storeState/format_3_-_cpu_1Ti
=== RUN   Test_stateCheckpoint_storeState/format_4_-_cpu_1Pi
=== RUN   Test_stateCheckpoint_storeState/format_5_-_cpu_1Ei
=== RUN   Test_stateCheckpoint_storeState/format_6_-_cpu_1n
=== RUN   Test_stateCheckpoint_storeState/format_7_-_cpu_1u
=== RUN   Test_stateCheckpoint_storeState/format_8_-_cpu_1m
=== RUN   Test_stateCheckpoint_storeState/format_9_-_cpu_1k
=== RUN   Test_stateCheckpoint_storeState/format_10_-_cpu_1M
=== RUN   Test_stateCheckpoint_storeState/format_11_-_cpu_1G
=== RUN   Test_stateCheckpoint_storeState/format_12_-_cpu_1T
=== RUN   Test_stateCheckpoint_storeState/format_13_-_cpu_1P
=== RUN   Test_stateCheckpoint_storeState/format_14_-_cpu_1E
=== RUN   Test_stateCheckpoint_storeState/format_15_-_cpu_1
=== RUN   Test_stateCheckpoint_storeState/format_16_-_cpu_0.1Ki
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_17_-_cpu_0.1Mi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_18_-_cpu_0.1Gi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_19_-_cpu_0.1Ti
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_20_-_cpu_0.1Pi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_21_-_cpu_0.1Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_22_-_cpu_0.1n
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_23_-_cpu_0.1u
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_24_-_cpu_0.1m
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_25_-_cpu_0.1k
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_26_-_cpu_0.1M
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_27_-_cpu_0.1G
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_28_-_cpu_0.1T
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_29_-_cpu_0.1P
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_30_-_cpu_0.1E
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_31_-_cpu_0.1
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_32_-_cpu_0.03Ki
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_33_-_cpu_0.03Mi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_34_-_cpu_0.03Gi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_35_-_cpu_0.03Ti
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_36_-_cpu_0.03Pi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_37_-_cpu_0.03Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_38_-_cpu_0.03n
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_39_-_cpu_0.03u
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_40_-_cpu_0.03m
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_41_-_cpu_0.03k
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_42_-_cpu_0.03M
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_43_-_cpu_0.03G
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_44_-_cpu_0.03T
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_45_-_cpu_0.03P
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_46_-_cpu_0.03E
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_47_-_cpu_0.03
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_48_-_cpu_10Ki
=== RUN   Test_stateCheckpoint_storeState/format_49_-_cpu_10Mi
=== RUN   Test_stateCheckpoint_storeState/format_50_-_cpu_10Gi
=== RUN   Test_stateCheckpoint_storeState/format_51_-_cpu_10Ti
=== RUN   Test_stateCheckpoint_storeState/format_52_-_cpu_10Pi
=== RUN   Test_stateCheckpoint_storeState/format_53_-_cpu_10Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_54_-_cpu_10n
=== RUN   Test_stateCheckpoint_storeState/format_55_-_cpu_10u
=== RUN   Test_stateCheckpoint_storeState/format_56_-_cpu_10m
=== RUN   Test_stateCheckpoint_storeState/format_57_-_cpu_10k
=== RUN   Test_stateCheckpoint_storeState/format_58_-_cpu_10M
=== RUN   Test_stateCheckpoint_storeState/format_59_-_cpu_10G
=== RUN   Test_stateCheckpoint_storeState/format_60_-_cpu_10T
=== RUN   Test_stateCheckpoint_storeState/format_61_-_cpu_10P
=== RUN   Test_stateCheckpoint_storeState/format_62_-_cpu_10E
=== RUN   Test_stateCheckpoint_storeState/format_63_-_cpu_10
=== RUN   Test_stateCheckpoint_storeState/format_64_-_cpu_100Ki
=== RUN   Test_stateCheckpoint_storeState/format_65_-_cpu_100Mi
=== RUN   Test_stateCheckpoint_storeState/format_66_-_cpu_100Gi
=== RUN   Test_stateCheckpoint_storeState/format_67_-_cpu_100Ti
=== RUN   Test_stateCheckpoint_storeState/format_68_-_cpu_100Pi
=== RUN   Test_stateCheckpoint_storeState/format_69_-_cpu_100Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_70_-_cpu_100n
=== RUN   Test_stateCheckpoint_storeState/format_71_-_cpu_100u
=== RUN   Test_stateCheckpoint_storeState/format_72_-_cpu_100m
=== RUN   Test_stateCheckpoint_storeState/format_73_-_cpu_100k
=== RUN   Test_stateCheckpoint_storeState/format_74_-_cpu_100M
=== RUN   Test_stateCheckpoint_storeState/format_75_-_cpu_100G
=== RUN   Test_stateCheckpoint_storeState/format_76_-_cpu_100T
=== RUN   Test_stateCheckpoint_storeState/format_77_-_cpu_100P
=== RUN   Test_stateCheckpoint_storeState/format_78_-_cpu_100E
=== RUN   Test_stateCheckpoint_storeState/format_79_-_cpu_100
=== RUN   Test_stateCheckpoint_storeState/format_80_-_cpu_512Ki
=== RUN   Test_stateCheckpoint_storeState/format_81_-_cpu_512Mi
=== RUN   Test_stateCheckpoint_storeState/format_82_-_cpu_512Gi
=== RUN   Test_stateCheckpoint_storeState/format_83_-_cpu_512Ti
=== RUN   Test_stateCheckpoint_storeState/format_84_-_cpu_512Pi
=== RUN   Test_stateCheckpoint_storeState/format_85_-_cpu_512Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_86_-_cpu_512n
=== RUN   Test_stateCheckpoint_storeState/format_87_-_cpu_512u
=== RUN   Test_stateCheckpoint_storeState/format_88_-_cpu_512m
=== RUN   Test_stateCheckpoint_storeState/format_89_-_cpu_512k
=== RUN   Test_stateCheckpoint_storeState/format_90_-_cpu_512M
=== RUN   Test_stateCheckpoint_storeState/format_91_-_cpu_512G
=== RUN   Test_stateCheckpoint_storeState/format_92_-_cpu_512T
=== RUN   Test_stateCheckpoint_storeState/format_93_-_cpu_512P
=== RUN   Test_stateCheckpoint_storeState/format_94_-_cpu_512E
=== RUN   Test_stateCheckpoint_storeState/format_95_-_cpu_512
=== RUN   Test_stateCheckpoint_storeState/format_96_-_cpu_1000Ki
=== RUN   Test_stateCheckpoint_storeState/format_97_-_cpu_1000Mi
=== RUN   Test_stateCheckpoint_storeState/format_98_-_cpu_1000Gi
=== RUN   Test_stateCheckpoint_storeState/format_99_-_cpu_1000Ti
=== RUN   Test_stateCheckpoint_storeState/format_100_-_cpu_1000Pi
=== RUN   Test_stateCheckpoint_storeState/format_101_-_cpu_1000Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_102_-_cpu_1000n
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_103_-_cpu_1000u
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_104_-_cpu_1000m
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_105_-_cpu_1000k
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_106_-_cpu_1000M
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_107_-_cpu_1000G
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_108_-_cpu_1000T
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_109_-_cpu_1000P
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_110_-_cpu_1000E
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_111_-_cpu_1000
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_112_-_cpu_1024Ki
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_113_-_cpu_1024Mi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_114_-_cpu_1024Gi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_115_-_cpu_1024Ti
=== RUN   Test_stateCheckpoint_storeState/format_116_-_cpu_1024Pi
=== RUN   Test_stateCheckpoint_storeState/format_117_-_cpu_1024Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_118_-_cpu_1024n
=== RUN   Test_stateCheckpoint_storeState/format_119_-_cpu_1024u
=== RUN   Test_stateCheckpoint_storeState/format_120_-_cpu_1024m
=== RUN   Test_stateCheckpoint_storeState/format_121_-_cpu_1024k
=== RUN   Test_stateCheckpoint_storeState/format_122_-_cpu_1024M
=== RUN   Test_stateCheckpoint_storeState/format_123_-_cpu_1024G
=== RUN   Test_stateCheckpoint_storeState/format_124_-_cpu_1024T
=== RUN   Test_stateCheckpoint_storeState/format_125_-_cpu_1024P
=== RUN   Test_stateCheckpoint_storeState/format_126_-_cpu_1024E
=== RUN   Test_stateCheckpoint_storeState/format_127_-_cpu_1024
=== RUN   Test_stateCheckpoint_storeState/format_128_-_cpu_700Ki
=== RUN   Test_stateCheckpoint_storeState/format_129_-_cpu_700Mi
=== RUN   Test_stateCheckpoint_storeState/format_130_-_cpu_700Gi
=== RUN   Test_stateCheckpoint_storeState/format_131_-_cpu_700Ti
=== RUN   Test_stateCheckpoint_storeState/format_132_-_cpu_700Pi
=== RUN   Test_stateCheckpoint_storeState/format_133_-_cpu_700Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_134_-_cpu_700n
=== RUN   Test_stateCheckpoint_storeState/format_135_-_cpu_700u
=== RUN   Test_stateCheckpoint_storeState/format_136_-_cpu_700m
=== RUN   Test_stateCheckpoint_storeState/format_137_-_cpu_700k
=== RUN   Test_stateCheckpoint_storeState/format_138_-_cpu_700M
=== RUN   Test_stateCheckpoint_storeState/format_139_-_cpu_700G
=== RUN   Test_stateCheckpoint_storeState/format_140_-_cpu_700T
=== RUN   Test_stateCheckpoint_storeState/format_141_-_cpu_700P
=== RUN   Test_stateCheckpoint_storeState/format_142_-_cpu_700E
=== RUN   Test_stateCheckpoint_storeState/format_143_-_cpu_700
=== RUN   Test_stateCheckpoint_storeState/format_144_-_cpu_10000Ki
=== RUN   Test_stateCheckpoint_storeState/format_145_-_cpu_10000Mi
=== RUN   Test_stateCheckpoint_storeState/format_146_-_cpu_10000Gi
=== RUN   Test_stateCheckpoint_storeState/format_147_-_cpu_10000Ti
=== RUN   Test_stateCheckpoint_storeState/format_148_-_cpu_10000Pi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_149_-_cpu_10000Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_150_-_cpu_10000n
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_151_-_cpu_10000u
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_152_-_cpu_10000m
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_153_-_cpu_10000k
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_154_-_cpu_10000M
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_155_-_cpu_10000G
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_156_-_cpu_10000T
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_157_-_cpu_10000P
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_158_-_cpu_10000E
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_159_-_cpu_10000
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
--- FAIL: Test_stateCheckpoint_storeState (1.43s)
    --- PASS: Test_stateCheckpoint_storeState/format_0_-_cpu_1Ki (0.02s)
    --- PASS: Test_stateCheckpoint_storeState/format_1_-_cpu_1Mi (0.04s)
    --- PASS: Test_stateCheckpoint_storeState/format_2_-_cpu_1Gi (0.03s)
    --- PASS: Test_stateCheckpoint_storeState/format_3_-_cpu_1Ti (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_4_-_cpu_1Pi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_5_-_cpu_1Ei (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_6_-_cpu_1n (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_7_-_cpu_1u (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_8_-_cpu_1m (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_9_-_cpu_1k (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_10_-_cpu_1M (0.00s)
    --- PASS: Test_stateCheckpoint_storeState/format_11_-_cpu_1G (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_12_-_cpu_1T (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_13_-_cpu_1P (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_14_-_cpu_1E (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_15_-_cpu_1 (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_16_-_cpu_0.1Ki (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_17_-_cpu_0.1Mi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_18_-_cpu_0.1Gi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_19_-_cpu_0.1Ti (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_20_-_cpu_0.1Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_21_-_cpu_0.1Ei (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_22_-_cpu_0.1n (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_23_-_cpu_0.1u (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_24_-_cpu_0.1m (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_25_-_cpu_0.1k (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_26_-_cpu_0.1M (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_27_-_cpu_0.1G (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_28_-_cpu_0.1T (0.00s)
    --- FAIL: Test_stateCheckpoint_storeState/format_29_-_cpu_0.1P (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_30_-_cpu_0.1E (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_31_-_cpu_0.1 (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_32_-_cpu_0.03Ki (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_33_-_cpu_0.03Mi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_34_-_cpu_0.03Gi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_35_-_cpu_0.03Ti (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_36_-_cpu_0.03Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_37_-_cpu_0.03Ei (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_38_-_cpu_0.03n (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_39_-_cpu_0.03u (0.02s)
    --- FAIL: Test_stateCheckpoint_storeState/format_40_-_cpu_0.03m (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_41_-_cpu_0.03k (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_42_-_cpu_0.03M (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_43_-_cpu_0.03G (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_44_-_cpu_0.03T (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_45_-_cpu_0.03P (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_46_-_cpu_0.03E (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_47_-_cpu_0.03 (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_48_-_cpu_10Ki (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_49_-_cpu_10Mi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_50_-_cpu_10Gi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_51_-_cpu_10Ti (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_52_-_cpu_10Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_53_-_cpu_10Ei (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_54_-_cpu_10n (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_55_-_cpu_10u (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_56_-_cpu_10m (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_57_-_cpu_10k (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_58_-_cpu_10M (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_59_-_cpu_10G (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_60_-_cpu_10T (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_61_-_cpu_10P (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_62_-_cpu_10E (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_63_-_cpu_10 (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_64_-_cpu_100Ki (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_65_-_cpu_100Mi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_66_-_cpu_100Gi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_67_-_cpu_100Ti (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_68_-_cpu_100Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_69_-_cpu_100Ei (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_70_-_cpu_100n (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_71_-_cpu_100u (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_72_-_cpu_100m (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_73_-_cpu_100k (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_74_-_cpu_100M (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_75_-_cpu_100G (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_76_-_cpu_100T (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_77_-_cpu_100P (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_78_-_cpu_100E (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_79_-_cpu_100 (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_80_-_cpu_512Ki (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_81_-_cpu_512Mi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_82_-_cpu_512Gi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_83_-_cpu_512Ti (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_84_-_cpu_512Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_85_-_cpu_512Ei (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_86_-_cpu_512n (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_87_-_cpu_512u (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_88_-_cpu_512m (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_89_-_cpu_512k (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_90_-_cpu_512M (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_91_-_cpu_512G (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_92_-_cpu_512T (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_93_-_cpu_512P (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_94_-_cpu_512E (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_95_-_cpu_512 (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_96_-_cpu_1000Ki (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_97_-_cpu_1000Mi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_98_-_cpu_1000Gi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_99_-_cpu_1000Ti (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_100_-_cpu_1000Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_101_-_cpu_1000Ei (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_102_-_cpu_1000n (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_103_-_cpu_1000u (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_104_-_cpu_1000m (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_105_-_cpu_1000k (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_106_-_cpu_1000M (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_107_-_cpu_1000G (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_108_-_cpu_1000T (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_109_-_cpu_1000P (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_110_-_cpu_1000E (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_111_-_cpu_1000 (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_112_-_cpu_1024Ki (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_113_-_cpu_1024Mi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_114_-_cpu_1024Gi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_115_-_cpu_1024Ti (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_116_-_cpu_1024Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_117_-_cpu_1024Ei (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_118_-_cpu_1024n (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_119_-_cpu_1024u (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_120_-_cpu_1024m (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_121_-_cpu_1024k (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_122_-_cpu_1024M (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_123_-_cpu_1024G (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_124_-_cpu_1024T (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_125_-_cpu_1024P (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_126_-_cpu_1024E (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_127_-_cpu_1024 (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_128_-_cpu_700Ki (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_129_-_cpu_700Mi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_130_-_cpu_700Gi (0.02s)
    --- PASS: Test_stateCheckpoint_storeState/format_131_-_cpu_700Ti (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_132_-_cpu_700Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_133_-_cpu_700Ei (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_134_-_cpu_700n (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_135_-_cpu_700u (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_136_-_cpu_700m (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_137_-_cpu_700k (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_138_-_cpu_700M (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_139_-_cpu_700G (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_140_-_cpu_700T (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_141_-_cpu_700P (0.03s)
    --- PASS: Test_stateCheckpoint_storeState/format_142_-_cpu_700E (0.02s)
    --- PASS: Test_stateCheckpoint_storeState/format_143_-_cpu_700 (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_144_-_cpu_10000Ki (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_145_-_cpu_10000Mi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_146_-_cpu_10000Gi (0.02s)
    --- PASS: Test_stateCheckpoint_storeState/format_147_-_cpu_10000Ti (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_148_-_cpu_10000Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_149_-_cpu_10000Ei (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_150_-_cpu_10000n (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_151_-_cpu_10000u (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_152_-_cpu_10000m (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_153_-_cpu_10000k (0.02s)
    --- FAIL: Test_stateCheckpoint_storeState/format_154_-_cpu_10000M (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_155_-_cpu_10000G (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_156_-_cpu_10000T (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_157_-_cpu_10000P (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_158_-_cpu_10000E (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_159_-_cpu_10000 (0.02s)
FAIL

```
</details>

### Kubernetes version

The bug happened in version 1.28, but it will happen in latest version 1.31 too.

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by yunwang0911**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
Fix one bug of the feature `pod in-place resource resize, feature gate: InPlacePodVerticalScaling`
#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/128375

#### Special notes for your reviewer:
One line bug description: the content func [stateCheckpoint.storeState](https://github.com/kubernetes/kubernetes/blob/60c4c2b2521fb454ce69dee737e3eb91a25e0535/pkg/kubelet/status/state/state_checkpoint.go#L80) writes into the file `/var/lib/kubelet/pod_status_manager_state` is different from it func [stateCheckpoint.restoreState](https://github.com/kubernetes/kubernetes/blob/60c4c2b2521fb454ce69dee737e3eb91a25e0535/pkg/kubelet/status/state/state_checkpoint.go#L59) reads from the same file, which causes function [VerifyChecksum](https://github.com/kubernetes/kubernetes/blob/60c4c2b2521fb454ce69dee737e3eb91a25e0535/pkg/kubelet/status/state/checkpoint.go#L59) always fails for some format of Quantity value. It should only happen for static pods in static dir.

**How to reproduce? **

1. prepare a pod spec with content below
```json
{
  "apiVersion": "v1",
  "kind": "Pod",
  "metadata": {
    "name": "nginx2"
  },
  "spec": {
    "containers": [
      {
        "name": "nginx",
        "image": "nginx:1.14.2",
        "ports": [
          {
            "containerPort": 80
          }
        ],
        "resources": {
          "requests": {
            "cpu": "0.4",
            "memory": "1Gi"
          },
          "limits": {
            "cpu": "1.5",
            "memory": "1Gi"
          }
        }
      }
    ]
  }
}
```
2. copy the pod spec into dir `/etc/kubernetes/manifest/` in master node
3.  restart the kubelet `systemctl restart kubelet`
4.  the kubelet will crash all the time until the file `/var/lib/kubelet/pod_status_manager_state` is deleted
5. error message would be like below
```shell
Aug 10 04:39:38 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 10 04:39:38 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 10 04:39:38 minikube kubelet[1190750]:         k8s.io/kubernetes/cmd/kubelet/app/server.go:1239 +0x90
Aug 10 04:39:38 minikube kubelet[1190750]: created by k8s.io/kubernetes/cmd/kubelet/app.startKubelet in goroutine 1
Aug 10 04:39:38 minikube kubelet[1190750]:         k8s.io/kubernetes/pkg/kubelet/kubelet.go:1628 +0x658
Aug 10 04:39:38 minikube kubelet[1190750]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run(0x4000ccac08, 0x4000ca1140)
Aug 10 04:39:38 minikube kubelet[1190750]:         k8s.io/kubernetes/pkg/kubelet/status/status_manager.go:204 +0x28c
Aug 10 04:39:38 minikube kubelet[1190750]: k8s.io/kubernetes/pkg/kubelet/status.(*manager).Start(0x40007a3a70)
Aug 10 04:39:38 minikube kubelet[1190750]: goroutine 239 [running]:
Aug 10 04:39:38 minikube kubelet[1190750]: panic: could not restore state from checkpoint: checkpoint is corrupted, please drain this node and delete pod allocation checkpoint file "/var/lib/kubelet/pod_status_manager_state" before restarting Kubelet
Aug 10 04:39:38 minikube kubelet[1190750]: E0810 04:39:38.722303 1190750 status_manager.go:203] "Could not initialize pod allocation checkpoint manager, please drain node and remove policy state file" err="could not restore state from checkpoint: checkpoint is corrupted, please drain this node and delete pod allocation checkpoint file \"/var/lib/kubelet/pod_status_manager_state\" before restarting Kubelet"
```

**Root cause**
The json marshal function of Quantity type will convert itself to `CanonicalBytes`
https://github.com/kubernetes/apimachinery/blob/95b78024e3feada7739b40426690b4f287933fd8/pkg/api/resource/quantity.go#L452C25-L452C41
But the json unmarshal function of Quantity type won't do that.
https://github.com/kubernetes/apimachinery/blob/95b78024e3feada7739b40426690b4f287933fd8/pkg/api/resource/quantity.go#L701
For some formats for Quantity value, the Quantity contents, wrote to and read from the same file, might be different.
For example, if the pod cpu request is defined as `cpu: "0.4"`, the Quantity content is `cpu:{{4 -1} {<nil>}  DecimalSI` before writing it into the file, but the content is `cpu:{{400 -3} {<nil>} 400m DecimalSI` after reading from the same file.

According to the reason above, the function [VerifyChecksum](https://github.com/kubernetes/kubernetes/blob/60c4c2b2521fb454ce69dee737e3eb91a25e0535/pkg/kubelet/status/state/checkpoint.go#L59) might fail.

**Detailed test case**
<details>

```text
=== RUN   Test_stateCheckpoint_storeState
=== RUN   Test_stateCheckpoint_storeState/format_0_-_cpu_1Ki
=== RUN   Test_stateCheckpoint_storeState/format_1_-_cpu_1Mi
=== RUN   Test_stateCheckpoint_storeState/format_2_-_cpu_1Gi
=== RUN   Test_stateCheckpoint_storeState/format_3_-_cpu_1Ti
=== RUN   Test_stateCheckpoint_storeState/format_4_-_cpu_1Pi
=== RUN   Test_stateCheckpoint_storeState/format_5_-_cpu_1Ei
=== RUN   Test_stateCheckpoint_storeState/format_6_-_cpu_1n
=== RUN   Test_stateCheckpoint_storeState/format_7_-_cpu_1u
=== RUN   Test_stateCheckpoint_storeState/format_8_-_cpu_1m
=== RUN   Test_stateCheckpoint_storeState/format_9_-_cpu_1k
=== RUN   Test_stateCheckpoint_storeState/format_10_-_cpu_1M
=== RUN   Test_stateCheckpoint_storeState/format_11_-_cpu_1G
=== RUN   Test_stateCheckpoint_storeState/format_12_-_cpu_1T
=== RUN   Test_stateCheckpoint_storeState/format_13_-_cpu_1P
=== RUN   Test_stateCheckpoint_storeState/format_14_-_cpu_1E
=== RUN   Test_stateCheckpoint_storeState/format_15_-_cpu_1
=== RUN   Test_stateCheckpoint_storeState/format_16_-_cpu_0.1Ki
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_17_-_cpu_0.1Mi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_18_-_cpu_0.1Gi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_19_-_cpu_0.1Ti
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_20_-_cpu_0.1Pi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_21_-_cpu_0.1Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_22_-_cpu_0.1n
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_23_-_cpu_0.1u
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_24_-_cpu_0.1m
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_25_-_cpu_0.1k
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_26_-_cpu_0.1M
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_27_-_cpu_0.1G
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_28_-_cpu_0.1T
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_29_-_cpu_0.1P
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_30_-_cpu_0.1E
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_31_-_cpu_0.1
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_32_-_cpu_0.03Ki
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_33_-_cpu_0.03Mi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_34_-_cpu_0.03Gi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_35_-_cpu_0.03Ti
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_36_-_cpu_0.03Pi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_37_-_cpu_0.03Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_38_-_cpu_0.03n
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_39_-_cpu_0.03u
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_40_-_cpu_0.03m
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_41_-_cpu_0.03k
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_42_-_cpu_0.03M
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_43_-_cpu_0.03G
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_44_-_cpu_0.03T
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_45_-_cpu_0.03P
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_46_-_cpu_0.03E
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_47_-_cpu_0.03
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_48_-_cpu_10Ki
=== RUN   Test_stateCheckpoint_storeState/format_49_-_cpu_10Mi
=== RUN   Test_stateCheckpoint_storeState/format_50_-_cpu_10Gi
=== RUN   Test_stateCheckpoint_storeState/format_51_-_cpu_10Ti
=== RUN   Test_stateCheckpoint_storeState/format_52_-_cpu_10Pi
=== RUN   Test_stateCheckpoint_storeState/format_53_-_cpu_10Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_54_-_cpu_10n
=== RUN   Test_stateCheckpoint_storeState/format_55_-_cpu_10u
=== RUN   Test_stateCheckpoint_storeState/format_56_-_cpu_10m
=== RUN   Test_stateCheckpoint_storeState/format_57_-_cpu_10k
=== RUN   Test_stateCheckpoint_storeState/format_58_-_cpu_10M
=== RUN   Test_stateCheckpoint_storeState/format_59_-_cpu_10G
=== RUN   Test_stateCheckpoint_storeState/format_60_-_cpu_10T
=== RUN   Test_stateCheckpoint_storeState/format_61_-_cpu_10P
=== RUN   Test_stateCheckpoint_storeState/format_62_-_cpu_10E
=== RUN   Test_stateCheckpoint_storeState/format_63_-_cpu_10
=== RUN   Test_stateCheckpoint_storeState/format_64_-_cpu_100Ki
=== RUN   Test_stateCheckpoint_storeState/format_65_-_cpu_100Mi
=== RUN   Test_stateCheckpoint_storeState/format_66_-_cpu_100Gi
=== RUN   Test_stateCheckpoint_storeState/format_67_-_cpu_100Ti
=== RUN   Test_stateCheckpoint_storeState/format_68_-_cpu_100Pi
=== RUN   Test_stateCheckpoint_storeState/format_69_-_cpu_100Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_70_-_cpu_100n
=== RUN   Test_stateCheckpoint_storeState/format_71_-_cpu_100u
=== RUN   Test_stateCheckpoint_storeState/format_72_-_cpu_100m
=== RUN   Test_stateCheckpoint_storeState/format_73_-_cpu_100k
=== RUN   Test_stateCheckpoint_storeState/format_74_-_cpu_100M
=== RUN   Test_stateCheckpoint_storeState/format_75_-_cpu_100G
=== RUN   Test_stateCheckpoint_storeState/format_76_-_cpu_100T
=== RUN   Test_stateCheckpoint_storeState/format_77_-_cpu_100P
=== RUN   Test_stateCheckpoint_storeState/format_78_-_cpu_100E
=== RUN   Test_stateCheckpoint_storeState/format_79_-_cpu_100
=== RUN   Test_stateCheckpoint_storeState/format_80_-_cpu_512Ki
=== RUN   Test_stateCheckpoint_storeState/format_81_-_cpu_512Mi
=== RUN   Test_stateCheckpoint_storeState/format_82_-_cpu_512Gi
=== RUN   Test_stateCheckpoint_storeState/format_83_-_cpu_512Ti
=== RUN   Test_stateCheckpoint_storeState/format_84_-_cpu_512Pi
=== RUN   Test_stateCheckpoint_storeState/format_85_-_cpu_512Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_86_-_cpu_512n
=== RUN   Test_stateCheckpoint_storeState/format_87_-_cpu_512u
=== RUN   Test_stateCheckpoint_storeState/format_88_-_cpu_512m
=== RUN   Test_stateCheckpoint_storeState/format_89_-_cpu_512k
=== RUN   Test_stateCheckpoint_storeState/format_90_-_cpu_512M
=== RUN   Test_stateCheckpoint_storeState/format_91_-_cpu_512G
=== RUN   Test_stateCheckpoint_storeState/format_92_-_cpu_512T
=== RUN   Test_stateCheckpoint_storeState/format_93_-_cpu_512P
=== RUN   Test_stateCheckpoint_storeState/format_94_-_cpu_512E
=== RUN   Test_stateCheckpoint_storeState/format_95_-_cpu_512
=== RUN   Test_stateCheckpoint_storeState/format_96_-_cpu_1000Ki
=== RUN   Test_stateCheckpoint_storeState/format_97_-_cpu_1000Mi
=== RUN   Test_stateCheckpoint_storeState/format_98_-_cpu_1000Gi
=== RUN   Test_stateCheckpoint_storeState/format_99_-_cpu_1000Ti
=== RUN   Test_stateCheckpoint_storeState/format_100_-_cpu_1000Pi
=== RUN   Test_stateCheckpoint_storeState/format_101_-_cpu_1000Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_102_-_cpu_1000n
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_103_-_cpu_1000u
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_104_-_cpu_1000m
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_105_-_cpu_1000k
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_106_-_cpu_1000M
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_107_-_cpu_1000G
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_108_-_cpu_1000T
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_109_-_cpu_1000P
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_110_-_cpu_1000E
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_111_-_cpu_1000
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_112_-_cpu_1024Ki
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_113_-_cpu_1024Mi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_114_-_cpu_1024Gi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_115_-_cpu_1024Ti
=== RUN   Test_stateCheckpoint_storeState/format_116_-_cpu_1024Pi
=== RUN   Test_stateCheckpoint_storeState/format_117_-_cpu_1024Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_118_-_cpu_1024n
=== RUN   Test_stateCheckpoint_storeState/format_119_-_cpu_1024u
=== RUN   Test_stateCheckpoint_storeState/format_120_-_cpu_1024m
=== RUN   Test_stateCheckpoint_storeState/format_121_-_cpu_1024k
=== RUN   Test_stateCheckpoint_storeState/format_122_-_cpu_1024M
=== RUN   Test_stateCheckpoint_storeState/format_123_-_cpu_1024G
=== RUN   Test_stateCheckpoint_storeState/format_124_-_cpu_1024T
=== RUN   Test_stateCheckpoint_storeState/format_125_-_cpu_1024P
=== RUN   Test_stateCheckpoint_storeState/format_126_-_cpu_1024E
=== RUN   Test_stateCheckpoint_storeState/format_127_-_cpu_1024
=== RUN   Test_stateCheckpoint_storeState/format_128_-_cpu_700Ki
=== RUN   Test_stateCheckpoint_storeState/format_129_-_cpu_700Mi
=== RUN   Test_stateCheckpoint_storeState/format_130_-_cpu_700Gi
=== RUN   Test_stateCheckpoint_storeState/format_131_-_cpu_700Ti
=== RUN   Test_stateCheckpoint_storeState/format_132_-_cpu_700Pi
=== RUN   Test_stateCheckpoint_storeState/format_133_-_cpu_700Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_134_-_cpu_700n
=== RUN   Test_stateCheckpoint_storeState/format_135_-_cpu_700u
=== RUN   Test_stateCheckpoint_storeState/format_136_-_cpu_700m
=== RUN   Test_stateCheckpoint_storeState/format_137_-_cpu_700k
=== RUN   Test_stateCheckpoint_storeState/format_138_-_cpu_700M
=== RUN   Test_stateCheckpoint_storeState/format_139_-_cpu_700G
=== RUN   Test_stateCheckpoint_storeState/format_140_-_cpu_700T
=== RUN   Test_stateCheckpoint_storeState/format_141_-_cpu_700P
=== RUN   Test_stateCheckpoint_storeState/format_142_-_cpu_700E
=== RUN   Test_stateCheckpoint_storeState/format_143_-_cpu_700
=== RUN   Test_stateCheckpoint_storeState/format_144_-_cpu_10000Ki
=== RUN   Test_stateCheckpoint_storeState/format_145_-_cpu_10000Mi
=== RUN   Test_stateCheckpoint_storeState/format_146_-_cpu_10000Gi
=== RUN   Test_stateCheckpoint_storeState/format_147_-_cpu_10000Ti
=== RUN   Test_stateCheckpoint_storeState/format_148_-_cpu_10000Pi
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_149_-_cpu_10000Ei
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_150_-_cpu_10000n
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_151_-_cpu_10000u
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_152_-_cpu_10000m
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_153_-_cpu_10000k
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_154_-_cpu_10000M
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_155_-_cpu_10000G
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_156_-_cpu_10000T
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_157_-_cpu_10000P
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_158_-_cpu_10000E
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
=== RUN   Test_stateCheckpoint_storeState/format_159_-_cpu_10000
    state_checkpoint_test.go:82: failed to restore state: checkpoint is corrupted
--- FAIL: Test_stateCheckpoint_storeState (1.43s)
    --- PASS: Test_stateCheckpoint_storeState/format_0_-_cpu_1Ki (0.02s)
    --- PASS: Test_stateCheckpoint_storeState/format_1_-_cpu_1Mi (0.04s)
    --- PASS: Test_stateCheckpoint_storeState/format_2_-_cpu_1Gi (0.03s)
    --- PASS: Test_stateCheckpoint_storeState/format_3_-_cpu_1Ti (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_4_-_cpu_1Pi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_5_-_cpu_1Ei (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_6_-_cpu_1n (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_7_-_cpu_1u (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_8_-_cpu_1m (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_9_-_cpu_1k (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_10_-_cpu_1M (0.00s)
    --- PASS: Test_stateCheckpoint_storeState/format_11_-_cpu_1G (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_12_-_cpu_1T (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_13_-_cpu_1P (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_14_-_cpu_1E (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_15_-_cpu_1 (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_16_-_cpu_0.1Ki (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_17_-_cpu_0.1Mi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_18_-_cpu_0.1Gi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_19_-_cpu_0.1Ti (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_20_-_cpu_0.1Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_21_-_cpu_0.1Ei (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_22_-_cpu_0.1n (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_23_-_cpu_0.1u (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_24_-_cpu_0.1m (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_25_-_cpu_0.1k (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_26_-_cpu_0.1M (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_27_-_cpu_0.1G (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_28_-_cpu_0.1T (0.00s)
    --- FAIL: Test_stateCheckpoint_storeState/format_29_-_cpu_0.1P (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_30_-_cpu_0.1E (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_31_-_cpu_0.1 (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_32_-_cpu_0.03Ki (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_33_-_cpu_0.03Mi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_34_-_cpu_0.03Gi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_35_-_cpu_0.03Ti (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_36_-_cpu_0.03Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_37_-_cpu_0.03Ei (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_38_-_cpu_0.03n (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_39_-_cpu_0.03u (0.02s)
    --- FAIL: Test_stateCheckpoint_storeState/format_40_-_cpu_0.03m (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_41_-_cpu_0.03k (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_42_-_cpu_0.03M (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_43_-_cpu_0.03G (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_44_-_cpu_0.03T (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_45_-_cpu_0.03P (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_46_-_cpu_0.03E (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_47_-_cpu_0.03 (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_48_-_cpu_10Ki (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_49_-_cpu_10Mi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_50_-_cpu_10Gi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_51_-_cpu_10Ti (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_52_-_cpu_10Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_53_-_cpu_10Ei (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_54_-_cpu_10n (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_55_-_cpu_10u (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_56_-_cpu_10m (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_57_-_cpu_10k (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_58_-_cpu_10M (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_59_-_cpu_10G (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_60_-_cpu_10T (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_61_-_cpu_10P (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_62_-_cpu_10E (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_63_-_cpu_10 (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_64_-_cpu_100Ki (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_65_-_cpu_100Mi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_66_-_cpu_100Gi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_67_-_cpu_100Ti (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_68_-_cpu_100Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_69_-_cpu_100Ei (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_70_-_cpu_100n (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_71_-_cpu_100u (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_72_-_cpu_100m (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_73_-_cpu_100k (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_74_-_cpu_100M (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_75_-_cpu_100G (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_76_-_cpu_100T (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_77_-_cpu_100P (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_78_-_cpu_100E (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_79_-_cpu_100 (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_80_-_cpu_512Ki (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_81_-_cpu_512Mi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_82_-_cpu_512Gi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_83_-_cpu_512Ti (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_84_-_cpu_512Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_85_-_cpu_512Ei (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_86_-_cpu_512n (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_87_-_cpu_512u (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_88_-_cpu_512m (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_89_-_cpu_512k (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_90_-_cpu_512M (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_91_-_cpu_512G (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_92_-_cpu_512T (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_93_-_cpu_512P (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_94_-_cpu_512E (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_95_-_cpu_512 (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_96_-_cpu_1000Ki (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_97_-_cpu_1000Mi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_98_-_cpu_1000Gi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_99_-_cpu_1000Ti (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_100_-_cpu_1000Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_101_-_cpu_1000Ei (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_102_-_cpu_1000n (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_103_-_cpu_1000u (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_104_-_cpu_1000m (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_105_-_cpu_1000k (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_106_-_cpu_1000M (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_107_-_cpu_1000G (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_108_-_cpu_1000T (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_109_-_cpu_1000P (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_110_-_cpu_1000E (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_111_-_cpu_1000 (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_112_-_cpu_1024Ki (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_113_-_cpu_1024Mi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_114_-_cpu_1024Gi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_115_-_cpu_1024Ti (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_116_-_cpu_1024Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_117_-_cpu_1024Ei (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_118_-_cpu_1024n (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_119_-_cpu_1024u (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_120_-_cpu_1024m (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_121_-_cpu_1024k (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_122_-_cpu_1024M (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_123_-_cpu_1024G (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_124_-_cpu_1024T (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_125_-_cpu_1024P (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_126_-_cpu_1024E (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_127_-_cpu_1024 (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_128_-_cpu_700Ki (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_129_-_cpu_700Mi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_130_-_cpu_700Gi (0.02s)
    --- PASS: Test_stateCheckpoint_storeState/format_131_-_cpu_700Ti (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_132_-_cpu_700Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_133_-_cpu_700Ei (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_134_-_cpu_700n (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_135_-_cpu_700u (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_136_-_cpu_700m (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_137_-_cpu_700k (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_138_-_cpu_700M (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_139_-_cpu_700G (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_140_-_cpu_700T (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_141_-_cpu_700P (0.03s)
    --- PASS: Test_stateCheckpoint_storeState/format_142_-_cpu_700E (0.02s)
    --- PASS: Test_stateCheckpoint_storeState/format_143_-_cpu_700 (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_144_-_cpu_10000Ki (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_145_-_cpu_10000Mi (0.01s)
    --- PASS: Test_stateCheckpoint_storeState/format_146_-_cpu_10000Gi (0.02s)
    --- PASS: Test_stateCheckpoint_storeState/format_147_-_cpu_10000Ti (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_148_-_cpu_10000Pi (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_149_-_cpu_10000Ei (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_150_-_cpu_10000n (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_151_-_cpu_10000u (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_152_-_cpu_10000m (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_153_-_cpu_10000k (0.02s)
    --- FAIL: Test_stateCheckpoint_storeState/format_154_-_cpu_10000M (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_155_-_cpu_10000G (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_156_-_cpu_10000T (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_157_-_cpu_10000P (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_158_-_cpu_10000E (0.01s)
    --- FAIL: Test_stateCheckpoint_storeState/format_159_-_cpu_10000 (0.02s)
FAIL
```

</details>

#### Does this PR introduce a user-facing change?

```release-note
Fix the bug of InPlacePodVerticalScaling state un-marshalling. State stored in `/var/lib/kubelet/pod_status_manager_state` is now can always be read back after kubelet restart.

Action Required: Since the checkpoint format was changed to fix the issue, if you are using the feature `InPlacePodVerticalScaling`, please clean up the state file `/var/lib/kubelet/pod_status_manager_state` when upgrading the kubelet as failrue to do it will lead to incompatible state formats and kubelet's failure to start.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
None

### CODE REVIEW

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+			if err != nil {
+				t.Errorf("failed to set pod resource allocation: %v", err)
+			}
+			// store state
+			err = sc.storeState()
+			if err != nil {
+				t.Errorf("failed to store state: %v", err)
+			}
+			// reset cache
+			originCache := sc.cache
```
Comment (bart0sh) [inline pkg/kubelet/status/state/state_checkpoint_test.go:74]: I believe you should deep copy this, otherwise any change to underlying structures of sc.cache will change it, e.g. it will be cleaned by `sc.cache.ClearState()` below.

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+			}
+			// remove file ./stateDir/pod_state_checkpoint
+			err = checkpointManager.RemoveCheckpoint(checkpointName)
+			if err != nil {
+				t.Errorf("failed to remove checkpoint: %v", err)
+			}
+			err = sc.cache.SetPodResourceAllocation(tt.args.podResourceAllocation)
+			if err != nil {
+				t.Errorf("failed to set pod resource allocation: %v", err)
+			}
```
Comment (bart0sh) [inline pkg/kubelet/status/state/state_checkpoint_test.go:67]:
```suggestion
			require.NoError(t, err, "failed to set pod resource allocation") 
```

Comment (bart0sh) [reply pkg/kubelet/status/state/state_checkpoint_test.go:67]: please use `assert.NoError` or `require.NoError` to check errors.

File: pkg/kubelet/status/state/checkpoint.go [hunk 3]
```diff
@@ -46,6 +46,14 @@ func NewPodResourceAllocationCheckpoint() *PodResourceAllocationCheckpoint {
...
 	// make sure checksum wasn't set before so it doesn't affect output checksum
 	prc.Checksum = 0
+	data, err := json.Marshal(*prc)
+	if err != nil {
+		return nil, err
+	}
+	err = json.Unmarshal(data, prc)
+	if err != nil {
+		return nil, err
+	}
```
Comment (bart0sh) [inline pkg/kubelet/status/state/checkpoint.go:56]: This looks like a workaround to me. If you think `Quantity.Unmarshal ` doesn't un-marshal quantity correctly, you should fix `Quantity.Unmarshal`.

**Comment by bart0sh** [comment]
@yunwang0911 This reminds me https://github.com/kubernetes/kubernetes/issues/123552. To properly fix this, checksum should be calculated *after* marshalling, as we did in https://github.com/kubernetes/kubernetes/pull/126303.
However, it's not easy to do as explained in the https://github.com/kubernetes/kubernetes/issues/123552

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 1 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go]: Fixed. Thx

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 2 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go]: Replaced

File: pkg/kubelet/status/state/checkpoint.go (hunk 3 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/checkpoint.go:51]: Precisely speaking, the un-marshal function isn't incorrect, but the behaviors of function marshal and un-marshal are different: the marshal function will convert quantity to `Canonical Bytes`, but un-marshal function won't. Honestly speaking, I'm not sure whether we should fix `Quantity.Unmarshal`.

**Comment by yunwang0911** [comment]
> @yunwang0911 This reminds me #123552. To properly fix this, checksum should be calculated _after_ marshalling, as we did in #126303. However, it's not easy to do as explained in the #123552

@bart0sh  Thank you for your suggestion. I have updated the code. Please help to review again

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 4]
```diff
@@ -0,0 +1,105 @@
...
+	"github.com/stretchr/testify/require"
+
+	v1 "k8s.io/api/core/v1"
+	"k8s.io/apimachinery/pkg/api/resource"
+	"k8s.io/kubernetes/pkg/kubelet/checkpointmanager"
+)
+
+func Test_stateCheckpoint_storeState(t *testing.T) {
+	cache := NewStateMemory()
+	checkpointManager, _ := checkpointmanager.NewCheckpointManager(".")
```
Comment (bart0sh) [inline pkg/kubelet/status/state/state_checkpoint_test.go:16]: I don't think source tree is a good place to keep temporary test artifacts. Please, consider using temporary directory, e.g. [as it's implemented for DRA checkpoint tests](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/dra/state/checkpointer_test.go#L153-L166)

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 5]
```diff
@@ -0,0 +1,105 @@
...
+			if (suf == "E" || suf == "Ei") && (fact == "1000" || fact == "10000") {
+				// when fact is 1000 or 10000, suffix "E" or "Ei", the quantity value is overflow
+				// see detail https://github.com/kubernetes/apimachinery/blob/95b78024e3feada7739b40426690b4f287933fd8/pkg/api/resource/quantity.go#L301
+				continue
+			}
+			tests = append(tests, struct {
+				name string
+				args args
+			}{
+				name: fmt.Sprintf("format %d - cpu %s%s", j*len(suffix)+i, fact, suf),
```
Comment (bart0sh) [inline pkg/kubelet/status/state/state_checkpoint_test.go:45]: "cpu" is misleading here as the same resource is also used for memory. How about `fmt.Sprintf("resource: %s%s", fact, suf)` or something similar?

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 6]
```diff
@@ -0,0 +1,105 @@
...
+			err = checkpointManager.RemoveCheckpoint(checkpointName)
+			require.NoError(t, err, "failed to remove checkpoint")
+			err = sc.cache.SetPodResourceAllocation(tt.args.podResourceAllocation)
+			require.NoError(t, err, "failed to set pod resource allocation")
+			// store state
+			err = sc.storeState()
+			if err != nil {
+				t.Errorf("failed to store state: %v", err)
+			}
+			// deep copy cache
```
Comment (bart0sh) [inline pkg/kubelet/status/state/state_checkpoint_test.go:74]: Please, use deepcopy-gen, e.g. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/dra/state/state.go#L26

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 7]
```diff
@@ -0,0 +1,105 @@
...
+			originCache := NewStateMemory()
+			podAllocation := sc.cache.GetPodResourceAllocation()
+			originCache.SetPodResourceAllocation(podAllocation)
+			podResizeStatus := sc.cache.GetResizeStatus()
+			originCache.SetResizeStatus(podResizeStatus)
+
+			// reset cache
+			err = sc.cache.ClearState()
+			require.NoError(t, err, "failed to clear state")
+			// restore state
```
Comment (bart0sh) [inline pkg/kubelet/status/state/state_checkpoint_test.go:84]: this kind of comment doesn't bring much value as `sc.restoreState()` is quite self-explanatory. The same is true for most of other comments in this scope. Please, consider removing not needed ones.

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 8]
```diff
@@ -0,0 +1,105 @@
...
+					for name, quantity := range resourceList {
+						if !quantity.Equal(restoredCache.GetPodResourceAllocation()[podUID][containerName][name]) {
+							t.Errorf("restored pod resource allocation is not equal to original pod resource allocation")
+						}
+					}
+				}
+			}
+			// remove file ./pod_state_checkpoint
+			err = checkpointManager.RemoveCheckpoint(checkpointName)
+			require.NoError(t, err, "failed to remove checkpoint")
```
Comment (bart0sh) [inline pkg/kubelet/status/state/state_checkpoint_test.go:102]: The checkpoint file is explicitly removed before every test case. For cleanup you can defer this before the loop over test cases.

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 9]
```diff
@@ -0,0 +1,105 @@
...
+		}
+	}
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			// reset environment
+			err = sc.cache.ClearState()
+			require.NoError(t, err, "failed to clear state")
+			// remove file ./pod_state_checkpoint
+			err = checkpointManager.RemoveCheckpoint(checkpointName)
+			require.NoError(t, err, "failed to remove checkpoint")
```
Comment (bart0sh) [inline pkg/kubelet/status/state/state_checkpoint_test.go:66]: nit: please use empty lines to separate logically independent code, e.g.
```
			err = sc.cache.ClearState()
			require.NoError(t, err, "failed to clear state")

			err = checkpointManager.RemoveCheckpoint(checkpointName)
			require.NoError(t, err, "failed to remove checkpoint")
```

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 10]
```diff
@@ -0,0 +1,105 @@
...
+			err = sc.cache.SetPodResourceAllocation(tt.args.podResourceAllocation)
+			require.NoError(t, err, "failed to set pod resource allocation")
+			// store state
+			err = sc.storeState()
+			if err != nil {
+				t.Errorf("failed to store state: %v", err)
+			}
```
Comment (bart0sh) [inline pkg/kubelet/status/state/state_checkpoint_test.go:73]: `assert.NoError(t, err, "failed to store state")` is the same as above 3 lines. `require.NoError` is an equivalent to `t.Fail`

File: pkg/kubelet/status/state/checkpoint.go [hunk 11]
```diff
@@ -18,48 +18,62 @@ package state
...
-	return &PodResourceAllocationCheckpoint{
-		AllocationEntries:   make(map[string]map[string]v1.ResourceList),
-		ResizeStatusEntries: make(map[string]v1.PodResizeStatus),
+// Checkpoint represents a structure to store pod resource allocation checkpoint data
+type Checkpoint struct {
+	// Data is a JSON serialized checkpoint data
+	Data string `json:"data"`
+	// Checksum is a checksum of Data
+	Checksum checksum.Checksum `json:"checksum"`
+}
```
Comment (bart0sh) [inline pkg/kubelet/status/state/checkpoint.go:39]: Changing checkpoint format should not cause Kubelet failures. When older Kubelet creates checkpoint and then upgraded to the new version with this format, it will not start for the same reason as you're trying to fix with this PR.

**Comment by bart0sh** [comment]
@yunwang0911 
> Thank you for your suggestion. I have updated the code. Please help to review again

We're able to do it for DRA as it's in alpha state. For GA code you should take care of possible Kubelet upgrades and downgrades I guess.

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 4 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go:16]: updated

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 5 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go:45]: updated

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 6 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go:74]: Actually, `sc.cache.GetPodResourceAllocation()` and `sc.cache.GetResizeStatus()` already had the deep copy capability.
```golang
func (s *stateMemory) GetPodResourceAllocation() PodResourceAllocation {
	s.RLock()
	defer s.RUnlock()
	return s.podAllocation.Clone()
}
// Clone returns a copy of PodResourceAllocation
func (pr PodResourceAllocation) Clone() PodResourceAllocation {
	prCopy := make(PodResourceAllocation)
	for pod := range pr {
		prCopy[pod] = make(map[string]v1.ResourceList)
		for container, alloc := range pr[pod] {
			prCopy[pod][container] = alloc.DeepCopy()
		}
	}
	return prCopy
}
func (s *stateMemory) GetResizeStatus() PodResizeStatus {
	s.RLock()
	defer s.RUnlock()
	prs := make(map[string]v1.PodResizeStatus)
	for k, v := range s.podResizeStatus {
		prs[k] = v
	}
	return prs
}
// PodResizeStatus shows status of desired resize of a pod's containers.
type PodResizeStatus string
```

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 7 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go:84]: updated

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 8 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go:102]: Got it. Updated

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 9 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go:66]: updated

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 10 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go:73]: updated

**Comment by yunwang0911** [comment]
> @yunwang0911
> 
> > Thank you for your suggestion. I have updated the code. Please help to review again
> 
> We're able to do it for DRA as it's in alpha state. For GA code you should take care of possible Kubelet upgrades and downgrades I guess.

InPlacePodVerticalScaling feature gate seems also be in alpha state. If I'm wrong, please correct me

**Comment by bart0sh** [comment]
@yunwang0911 
> InPlacePodVerticalScaling feature gate seems also be in alpha state. If I'm wrong, please correct me

It is. I just don't know if this checkpoint is used only when the feature is enabled or it was introduced before the feature. Please, point me out to the code that introduced it.

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 6 above)
Comment (bart0sh) [reply pkg/kubelet/status/state/state_checkpoint_test.go:86]: I'm just wondering why do you need to clone the whole cache if you only want to veryfy that `PodResourceAllocation` data is the same as `tt.args.podResourceAllocation` after restoring state? Wouldn't it be enough to simply compare `restoredCache.GetPodResourceAllocation())` with `tt.args.podResourceAllocation` ?

**Comment by bart0sh** [comment]
@yunwang0911 You're right, this checkpoint is used only with `InPlacePodVerticalScaling` feature gate, so it's still possible to change its format.

**Comment by bart0sh** [comment]
/triage accepted
/priority important-longterm
/ok-to-test

@yunwang0911 please provide release note as changing checkpoint format is a user visible change. It'd also make sense to document somewhere that old format is not supported and can cause kubelet start issues.

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 5 above)
Comment (bart0sh) [reply pkg/kubelet/status/state/state_checkpoint_test.go]: How format `j*len(suffix)+i` is going to be used?

File: pkg/kubelet/status/state/checkpoint.go (hunk 11 above)
Comment (bart0sh) [reply pkg/kubelet/status/state/checkpoint.go:39]: It would be nice to test upgrade scenario, e.g. if Data has a new field(it could happen when Kubelet is upgraded), but the checkpoint is not(as it's created with older Kubelet, before the upgrade).

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 5 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go]: Sorry, I don't get your point. Could you please elaborate it?

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 6 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go:86]: Yeah, you are right. I should only compare them only. Let me update

File: pkg/kubelet/status/state/checkpoint.go (hunk 11 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/checkpoint.go:39]: Do you mean we should have a explicit test case to expose that state checkpoint will fail when Data has a new field, like Kubelet is upgraded?

Comment (bart0sh) [reply pkg/kubelet/status/state/checkpoint.go:39]: The point is that Kubelet shouldn't fail. The test case should demonstrate that Kubelet is able to read checkpoints created before Kubelet upgrades.

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 5 above)
Comment (bart0sh) [reply pkg/kubelet/status/state/state_checkpoint_test.go]: I think the number in the output doesn't bring a lot of value even not speaking about it correctness:
```
$ go test -v -run ^Test_stateCheckpoint_storeState$ k8s.io/kubernetes/pkg/kubelet/status/state | grep Test_ | tail -3
    --- PASS: Test_stateCheckpoint_storeState/#156_resource_-_10000T (0.00s)
    --- PASS: Test_stateCheckpoint_storeState/#157_resource_-_10000P (0.00s)
    --- PASS: Test_stateCheckpoint_storeState/#159_resource_-_10000 (0.00s)
```
And I'd propose to drop it, so the above output would look like this:
```
    --- PASS: Test_stateCheckpoint_storeState/resource_10000T (0.00s)
    --- PASS: Test_stateCheckpoint_storeState/resource_10000P (0.00s)
    --- PASS: Test_stateCheckpoint_storeState/resource_10000 (0.00s)
```
I'd even drop `resource`, but that's up to you.

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 12]
```diff
@@ -0,0 +1,128 @@
...
+			// deep copy cache
+			originCache := NewStateMemory()
+			podAllocation := sc.cache.GetPodResourceAllocation()
+			err = originCache.SetPodResourceAllocation(podAllocation)
+			require.NoError(t, err, "failed to set pod resource allocation")
+
+			err = sc.cache.ClearState()
+			require.NoError(t, err, "failed to clear state")
+
+			err = sc.restoreState()
```
Comment (bart0sh) [inline pkg/kubelet/status/state/state_checkpoint_test.go:111]: Would it be better to test `storeState` and `restoreState` separately, e.g. [as it's done for DRA](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/dra/state/checkpointer_test.go)

Comment (bart0sh) [reply pkg/kubelet/status/state/state_checkpoint_test.go:111]: This would make the tests easier to understand, wouldn't require deep copying and would help to avoid hidden issues that might be compensating each other when `storeState` and `restoreState` are called in the same test.

File: pkg/kubelet/status/state/checkpoint.go (hunk 11 above)
Comment (bart0sh) [reply pkg/kubelet/status/state/checkpoint.go:39]: @yunwang0911 here is an example of such a test case for DRA checkpointing: https://github.com/kubernetes/kubernetes/pull/126717

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 12 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go:111]: Actually, the tests are designed for verifying the whole flow, to make sure the content written to the file is the samw with the content read from the file. If we split them into separate test, the error might be hidden, just like the UT in description of this PR. https://github.com/kubernetes/kubernetes/pull/126620#issue-2459128710

Comment (bart0sh) [reply pkg/kubelet/status/state/state_checkpoint_test.go:111]: Well, generally unit tests are designed to test units. If you want to test whole worklow please provide e2e tests as well.

File: pkg/kubelet/status/state/checkpoint.go (hunk 11 above)
Comment (bart0sh) [reply pkg/kubelet/status/state/checkpoint.go:39]: This should be addressed. The rest of the PR looks good enough to me.

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 12 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go:111]: @bart0sh What do you think?

Comment (bart0sh) [reply pkg/kubelet/status/state/state_checkpoint_test.go:111]: It's up to you. I don't feel strongly about this.

File: pkg/kubelet/status/state/checkpoint.go (hunk 11 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/checkpoint.go:39]: @bart0sh I added another test case to test upgrade scenario. https://github.com/kubernetes/kubernetes/pull/126620/files#diff-ff3988755adc35924ce7f3bf6ffa770cd159b34af6428db5f0f9c461fd15234fR135
If I understand it wrong, please kindly correct me

File: pkg/kubelet/status/state/checkpoint.go [hunk 13]
```diff
@@ -18,48 +18,62 @@ package state
...
 
-// MarshalCheckpoint returns marshalled checkpoint
-func (prc *PodResourceAllocationCheckpoint) MarshalCheckpoint() ([]byte, error) {
-	// make sure checksum wasn't set before so it doesn't affect output checksum
-	prc.Checksum = 0
-	prc.Checksum = checksum.New(prc)
-	return json.Marshal(*prc)
+// UnmarshalCheckpoint unmarshals checkpoint from JSON
+func (cp *Checkpoint) UnmarshalCheckpoint(blob []byte) error {
+	return json.Unmarshal(blob, cp)
```
Comment (bart0sh) [inline pkg/kubelet/status/state/checkpoint.go:62]: Should UnmarshalCheckpoint verify the checksum?

File: pkg/kubelet/status/state/checkpoint.go [hunk 14]
```diff
@@ -18,48 +18,62 @@ package state
...
 import (
 	"encoding/json"
-
 	"k8s.io/api/core/v1"
 	"k8s.io/kubernetes/pkg/kubelet/checkpointmanager"
 	"k8s.io/kubernetes/pkg/kubelet/checkpointmanager/checksum"
 )
 
-var _ checkpointmanager.Checkpoint = &PodResourceAllocationCheckpoint{}
+var _ checkpointmanager.Checkpoint = &Checkpoint{}
```
Comment (bart0sh) [inline pkg/kubelet/status/state/checkpoint.go:26]: What's the purpose of this? Is it used anywhere?

File: pkg/kubelet/status/state/checkpoint.go [hunk 15]
```diff
@@ -18,48 +18,62 @@ package state
...
-func (prc *PodResourceAllocationCheckpoint) VerifyChecksum() error {
-	ck := prc.Checksum
-	prc.Checksum = 0
-	err := ck.Verify(prc)
-	prc.Checksum = ck
-	return err
+// GetPodResourceAllocationInfo returns Pod Resource Allocation info states from checkpoint
+func (cp *Checkpoint) GetPodResourceAllocationInfo() (*PodResourceAllocationInfo, error) {
+	var data PodResourceAllocationInfo
+	if err := json.Unmarshal([]byte(cp.Data), &data); err != nil {
```
Comment (bart0sh) [inline pkg/kubelet/status/state/checkpoint.go:74]: This un-marshals data without verifying checksum. Should cp.UnmarshalCheckpoint be called here instead?

File: pkg/kubelet/status/state/checkpoint.go (hunk 14 above)
Comment (bart0sh) [reply pkg/kubelet/status/state/checkpoint.go:26]: The same with `State` global variable in the beginning of the `checkpoint.go `

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 16]
```diff
@@ -0,0 +1,158 @@
...
+}
+
+func Test_stateCheckpoint_formatUpgraded(t *testing.T) {
+	// Based on the PodResourceAllocationInfo struct, it's mostly possible that new field will be added
+	// in struct PodResourceAllocationInfo, rather than in struct PodResourceAllocationInfo.AllocationEntries.
+	// Emulate upgrade scenario by pretending that `ResizeStatusEntries` is a new field.
+	// The checkpoint content doesn't have it and that shouldn't prevent the checkpoint from being loaded.
+	checkpointContent := `{"data":"{\"allocationEntries\":{\"pod1\":{\"container1\":{\"cpu\":\"1Ki\",\"memory\":\"1Ki\"}}}}","checksum":143149502}`
+	checkpoint := &Checkpoint{}
+	err := checkpoint.UnmarshalCheckpoint([]byte(checkpointContent))
```
Comment (bart0sh) [inline pkg/kubelet/status/state/state_checkpoint_test.go:142]: Can you use stateCheckpoint APIs here to cover a bit more functionality?

File: pkg/kubelet/status/state/checkpoint.go (hunk 13 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/checkpoint.go:62]: @bart0sh Per my understanding, we shouldn't verify the checksum in UnmarshalCheckpoint function. Since checkpoint interface provides separate function to verify checksum, we should keep it simple
```golang
// Checkpoint provides the process checkpoint data
type Checkpoint interface {
	MarshalCheckpoint() ([]byte, error)
	UnmarshalCheckpoint(blob []byte) error
	VerifyChecksum() error
}
```
Besides, the function `UnmarshalCheckpoint` is only invoked in the `GetCheckpoint` function, following the function `VerifyChecksum`. They are repeat if we verify checksum inside the function `UnmarshalCheckpoint`
```golang
// GetCheckpoint retrieves checkpoint from CheckpointStore.
func (manager *impl) GetCheckpoint(checkpointKey string, checkpoint Checkpoint) error {
	...
	err = checkpoint.UnmarshalCheckpoint(blob)
	if err == nil {
		err = checkpoint.VerifyChecksum()
	}
	return err
}
```
By the way, both cpu checkpoint and device checkpoint don't verify checksum inside function `UnmarshalCheckpoint`

File: pkg/kubelet/status/state/checkpoint.go (hunk 14 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/checkpoint.go:26]: To ensure struct `Checkpoint ` implement the interface `checkpointmanager.Checkpoint`.  Do you think it's unnecessary?

File: pkg/kubelet/status/state/checkpoint.go (hunk 15 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/checkpoint.go:74]: @bart0sh No, it shouldn't in my opinion.
Verifying checksum is necessary immediately after reading the checkpoint from the file, but this function is invoked at the situation that the checkpoint already is read into struct `Checkpoint`, which is in memory.
> file -> ① -> Checkpoint -> ② -> stateCheckpoint

It's necessary for procedure ① to verify checksum, but not for procedure ②.
And function `GetPodResourceAllocationInfo` is invoked at procedure ②. 
```golang
func (sc *stateCheckpoint) restoreState() error {
	...
        // procudure ① 
	if err = sc.checkpointManager.GetCheckpoint(sc.checkpointName, checkpoint); err != nil {
		if err == errors.ErrCheckpointNotFound {
			return sc.storeState()
		}
		return err
	}
        // procudure ②
	praInfo, err := checkpoint.GetPodResourceAllocationInfo()
	if err != nil {
		return fmt.Errorf("failed to get pod resource allocation info: %w", err)
	}
	...
}
```

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 16 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go:146]: Updated

File: pkg/kubelet/status/state/checkpoint.go (hunk 14 above)
Comment (bart0sh) [reply pkg/kubelet/status/state/checkpoint.go:26]: It is unnecessary from my pov, but it's not related to this PR, so let's keep it as it is.

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 16 above)
Comment (bart0sh) [reply pkg/kubelet/status/state/state_checkpoint_test.go:146]: Thanks. BTW, my suggestions to add checksum verification to the UnmarshallCheckpoint call were caused by this line as it was simply unmarshalling content without verification.

**Comment by bart0sh** [comment]
/lgtm
/assign @SergeyKanzhelev @mrunalp 
for approval

File: pkg/kubelet/status/state/checkpoint.go (hunk 3 above)
Comment (SergeyKanzhelev) [reply pkg/kubelet/status/state/checkpoint.go:51]: should we marshal -> unmarshal before calculating the checksum on write?

File: pkg/kubelet/status/state/checkpoint.go [hunk 17]
```diff
@@ -18,48 +18,62 @@ package state
...
-// NewPodResourceAllocationCheckpoint returns an instance of Checkpoint
-func NewPodResourceAllocationCheckpoint() *PodResourceAllocationCheckpoint {
-	//lint:ignore unexported-type-in-api user-facing error message
-	return &PodResourceAllocationCheckpoint{
-		AllocationEntries:   make(map[string]map[string]v1.ResourceList),
-		ResizeStatusEntries: make(map[string]v1.PodResizeStatus),
+// Checkpoint represents a structure to store pod resource allocation checkpoint data
+type Checkpoint struct {
+	// Data is a JSON serialized checkpoint data
+	Data string `json:"data"`
```
Comment (SergeyKanzhelev) [inline pkg/kubelet/status/state/checkpoint.go:36]: switching to untyped json doesn't seem like an improvement for me

**Comment by SergeyKanzhelev** [comment]
Release notes should be more end-user friendly and tell what was fixed and what to do:


``` release-notes
Fix the bug of InPlacePodVerticalScaling state un-marshalling. State stored in `/var/lib/kubelet/pod_status_manager_state` is now can always be read back after kubelet restart.

Action Required: Since the checkpoint format was changed to fix the issue, if you are using the feature `InPlacePodVerticalScaling`, please clean up the state file `/var/lib/kubelet/pod_status_manager_state` when upgrading the kubelet as failrue to do it will lead to incompatible state formats and kubelet's failure to start.
```

**Comment by yunwang0911** [comment]
> Release notes should be more end-user friendly and tell what was fixed and what to do:
> 
> ```
> Fix the bug of InPlacePodVerticalScaling state un-marshalling. State stored in `/var/lib/kubelet/pod_status_manager_state` is now can always be read back after kubelet restart.
> 
> Action Required: Since the checkpoint format was changed to fix the issue, if you are using the feature `InPlacePodVerticalScaling`, please clean up the state file `/var/lib/kubelet/pod_status_manager_state` when upgrading the kubelet as failrue to do it will lead to incompatible state formats and kubelet's failure to start.
> ```

@SergeyKanzhelev Thank you. This is really clear than the note I worte. Updated

File: pkg/kubelet/status/state/checkpoint.go (hunk 13 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/checkpoint.go:62]: @bart0sh What do you think?

Comment (bart0sh) [reply pkg/kubelet/status/state/checkpoint.go:62]: I'm ok with the current code.

File: pkg/kubelet/status/state/checkpoint.go (hunk 3 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/checkpoint.go:51]: @SergeyKanzhelev it works, but it more likes a workaround.

Comment (yunwang0911) [reply pkg/kubelet/status/state/checkpoint.go:51]: @SergeyKanzhelev I'm not sure about it. Both solutions can fix the issue

File: pkg/kubelet/status/state/checkpoint.go (hunk 11 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/checkpoint.go:39]: @SergeyKanzhelev In theory, this issue only affects static pods. Because the marshal and un-marshal will be invoked when the data is serialized and deserialized. Please correct me if I'm wrong.

**Comment by yunwang0911** [comment]
@bart0sh @SergeyKanzhelev Any other comment?

**Comment by yunwang0911** [comment]
@SergeyKanzhelev please take a look again, thanks. And please highlight comments which I didn't handle, in case I missed any comment

**Comment by SergeyKanzhelev** [comment]
/cc @tallclair 

Looks good to me. @tallclair please approve if looks good to you. Also just for awareness of inplaceupgrade-related PRs

**Comment by yunwang0911** [comment]
@tallclair any chance to review this PR?

**Comment by yunwang0911** [comment]
@tallclair Any comment?

**Comment by yunwang0911** [comment]
@vinaykul @iholder101 @tallclair could you please take a look?

File: pkg/kubelet/status/state/state_checkpoint.go [hunk 18]
```diff
@@ -61,40 +61,47 @@ func (sc *stateCheckpoint) restoreState() error {
...
-	checkpoint.ResizeStatusEntries = make(map[string]v1.PodResizeStatus)
-	for pUID, rStatus := range podResizeStatus {
-		checkpoint.ResizeStatusEntries[pUID] = rStatus
+	checkpoint, err := NewCheckpoint(&PodResourceAllocationInfo{
+		AllocationEntries:   podAllocation,
+		ResizeStatusEntries: podResizeStatus,
+	})
+	if err != nil {
+		klog.ErrorS(err, "Failed to create checkpoint")
+		return err
```
Comment (tallclair) [inline pkg/kubelet/status/state/state_checkpoint.go:102]: don't log errors that are being returned
```suggestion
		return fmt.Errorf("failed to create checkpoint: %w", err)
```

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 19]
```diff
@@ -0,0 +1,175 @@
+/*
+Copyright 2016 The Kubernetes Authors.
```
Comment (tallclair) [inline pkg/kubelet/status/state/state_checkpoint_test.go:2]: nit
```suggestion
Copyright 2024 The Kubernetes Authors.
```

File: pkg/kubelet/status/state/state_checkpoint_test.go
Comment (tallclair) [inline pkg/kubelet/status/state/state_checkpoint_test.go:1]: Thanks for adding the test!

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 20]
```diff
@@ -0,0 +1,175 @@
...
+			defer func() {
+				err = sc.checkpointManager.RemoveCheckpoint(sc.checkpointName)
+				require.NoError(t, err, "failed to remove checkpoint")
+			}()
+
+			err = sc.cache.SetPodResourceAllocation(tt.args.podResourceAllocation)
+			require.NoError(t, err, "failed to set pod resource allocation")
+
+			err = sc.storeState()
+			require.NoError(t, err, "failed to store state")
```
Comment (tallclair) [inline pkg/kubelet/status/state/state_checkpoint_test.go:107]: Wouldn't it be better to just call `sc.SetPodResourceAllocation(...)` directly? I think it does this internally.

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 21]
```diff
@@ -0,0 +1,175 @@
...
+	// create temp dir
+	testingDir, err := os.MkdirTemp("", "pod_resource_allocation_state_test")
+	if err != nil {
+		t.Fatal(err)
+	}
+	defer func() {
+		if err := os.RemoveAll(testingDir); err != nil {
+			t.Fatal(err)
+		}
+	}()
```
Comment (tallclair) [inline pkg/kubelet/status/state/state_checkpoint_test.go:41]: Shouldn't you keep this around until the end of the test? This is going to delete the directory as soon as `newTestStateCheckpoint` returns. Use `t.Cleanup(...)` instead

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 22]
```diff
@@ -0,0 +1,175 @@
...
+
+			defer func() {
+				err = sc.checkpointManager.RemoveCheckpoint(sc.checkpointName)
+				require.NoError(t, err, "failed to remove checkpoint")
+			}()
+
+			err = sc.cache.SetPodResourceAllocation(tt.args.podResourceAllocation)
+			require.NoError(t, err, "failed to set pod resource allocation")
+
+			err = sc.storeState()
```
Comment (tallclair) [inline pkg/kubelet/status/state/state_checkpoint_test.go:106]: Rather than all this mucking with the internal cache and state, I'd prefer to test the external interfaces here. In otherwords, something like this:

```go
testDir = getTestDir(t)
originalSC, err := NewStateCheckpoint(testDir, testCheckpoint)
require.NoError(t, err)

err = originalSC.SetPodResourceAllocation(tt.args.podResourceAllocation)
require.NoError(t, err)

actual := originalSC.GetPodResourceAllocation()
assert.Equal(t, tt.args.podResourceAllocation, actual)

// additional verification of originalSC.GetContainerResourceAllocation(...)

newSC := NewStateCheckpoint(testDir, testCheckpoint)
require.NoError(t, err)

actual = newSC.GetPodResourceAllocation()
assert.Equal(t, tt.args.podResourceAllocation, actual)

// aditional verification of newSC.GetContainerResourceAllocation(...)
```

File: pkg/kubelet/status/state/checkpoint.go [hunk 23]
```diff
@@ -18,48 +18,62 @@ package state
...
-// NewPodResourceAllocationCheckpoint returns an instance of Checkpoint
-func NewPodResourceAllocationCheckpoint() *PodResourceAllocationCheckpoint {
-	//lint:ignore unexported-type-in-api user-facing error message
-	return &PodResourceAllocationCheckpoint{
-		AllocationEntries:   make(map[string]map[string]v1.ResourceRequirements),
-		ResizeStatusEntries: make(map[string]v1.PodResizeStatus),
+// Checkpoint represents a structure to store pod resource allocation checkpoint data
+type Checkpoint struct {
+	// Data is a JSON serialized checkpoint data
+	Data string `json:"data"`
```
[the remark this answers is not in the document]
Comment (yunwang0911) [reply pkg/kubelet/status/state/checkpoint.go:36]: No particular reason, just following existing code in dra checkpoint [link](https://github.com/kubernetes/kubernetes/blob/ce47f7b416ff0e5a5c73d70e8dd3175ced5afaa9/pkg/kubelet/cm/dra/state/checkpoint.go#L34). What do you think? Which is better?

File: pkg/kubelet/status/state/checkpoint.go [hunk 24]
```diff
@@ -18,48 +18,62 @@ package state
...
 
-// NewPodResourceAllocationCheckpoint returns an instance of Checkpoint
-func NewPodResourceAllocationCheckpoint() *PodResourceAllocationCheckpoint {
-	//lint:ignore unexported-type-in-api user-facing error message
-	return &PodResourceAllocationCheckpoint{
-		AllocationEntries:   make(map[string]map[string]v1.ResourceRequirements),
-		ResizeStatusEntries: make(map[string]v1.PodResizeStatus),
+// Checkpoint represents a structure to store pod resource allocation checkpoint data
+type Checkpoint struct {
+	// Data is a JSON serialized checkpoint data
```
[the remark this answers is not in the document]
Comment (yunwang0911) [reply pkg/kubelet/status/state/checkpoint.go:35]: Ack

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 20 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go:107]: Yeah, I'll update it

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 21 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go:41]: Got it.

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 22 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go]: I updated the test function following the pattern above, but replaced the assert function by function below

```go
func verifyPodResourceAllocation(t *testing.T, expected, actual *PodResourceAllocation, msgAndArgs string) {
	for podUID, containerResourceList := range *expected {
		require.Equal(t, len(containerResourceList), len((*actual)[podUID]), msgAndArgs)
		for containerName, resourceList := range containerResourceList {
			for name, quantity := range resourceList.Requests {
				if !quantity.Equal((*actual)[podUID][containerName].Requests[name]) {
					t.Errorf(msgAndArgs)
				}
			}
		}
	}
}
```

Because reflect.DeepEqual won't call Quantity.Equal function internally, and `assert.Equal(t, tt.args.podResourceAllocation, actual)` will fail because of different formats of Quantity.

File: pkg/kubelet/status/state/checkpoint.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (tallclair) [reply pkg/kubelet/status/state/checkpoint.go:37]: `[]byte` seems more idiomatic, and makes the intent clearer. No strong preference though.

That said, a lot of this checkpoint code is identical to the DRA checkpoint, including this `Checkpoint` type. Should we just move all of this to the pkg/kubelet/checkpointmanager package?

File: pkg/kubelet/status/state/checkpoint.go [hunk 25]
```diff
@@ -18,48 +18,62 @@ package state
...
+	Data string `json:"data"`
+	// Checksum is a checksum of Data
+	Checksum checksum.Checksum `json:"checksum"`
```
[the remark this answers is not in the document]
Comment (tallclair) [reply pkg/kubelet/status/state/checkpoint.go:39]: Yeah, I guess this is fine.

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 26]
```diff
@@ -0,0 +1,177 @@
...
+			require.NoError(t, err)
+
+			actual := originalSC.GetPodResourceAllocation()
+			verifyPodResourceAllocation(t, &tt.args.podResourceAllocation, &actual, "stored pod resource allocation is not equal to original pod resource allocation")
+
+			newSC, err := NewStateCheckpoint(testDir, testCheckpoint)
+			require.NoError(t, err)
+
+			actual = newSC.GetPodResourceAllocation()
+			verifyPodResourceAllocation(t, &tt.args.podResourceAllocation, &actual, "stored pod resource allocation is not equal to original pod resource allocation")
```
Comment (tallclair) [inline pkg/kubelet/status/state/state_checkpoint_test.go:134]:
```suggestion
			verifyPodResourceAllocation(t, &tt.args.podResourceAllocation, &actual, "restored pod resource allocation is not equal to original pod resource allocation")
```

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 27]
```diff
@@ -0,0 +1,177 @@
...
+	// create temp dir
+	testingDir, err := os.MkdirTemp("", "pod_resource_allocation_state_test")
+	if err != nil {
+		t.Fatal(err)
+	}
+	t.Cleanup(func() {
+		if err := os.RemoveAll(testingDir); err != nil {
+			t.Fatal(err)
+		}
+	})
```
Comment (tallclair) [inline pkg/kubelet/status/state/state_checkpoint_test.go:43]:
```suggestion
	testingDir, err := getTestDir(t)
```

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 28]
```diff
@@ -0,0 +1,177 @@
...
+func Test_stateCheckpoint_formatUpgraded(t *testing.T) {
+	// Based on the PodResourceAllocationInfo struct, it's mostly possible that new field will be added
+	// in struct PodResourceAllocationInfo, rather than in struct PodResourceAllocationInfo.AllocationEntries.
+	// Emulate upgrade scenario by pretending that `ResizeStatusEntries` is a new field.
+	// The checkpoint content doesn't have it and that shouldn't prevent the checkpoint from being loaded.
+	sc := newTestStateCheckpoint(t)
+
+	// prepare old checkpoint, ResizeStatusEntries is unset,
+	// pretend that the old checkpoint is unaware for the field ResizeStatusEntries
+	checkpointContent := `{"data":"{\"allocationEntries\":{\"pod1\":{\"container1\":{\"requests\":{\"cpu\":\"1Ki\",\"memory\":\"1Ki\"}}}}}","checksum":1555601526}`
```
Comment (tallclair) [inline pkg/kubelet/status/state/state_checkpoint_test.go:148]: nit
```suggestion
	const checkpointContent = `{"data":"{\"allocationEntries\":{\"pod1\":{\"container1\":{\"requests\":{\"cpu\":\"1Ki\",\"memory\":\"1Ki\"}}}}}","checksum":1555601526}`
```

File: pkg/kubelet/status/state/state_checkpoint_test.go [hunk 29]
```diff
@@ -0,0 +1,177 @@
...
+				"container1": {
+					Requests: v1.ResourceList{
+						v1.ResourceCPU:    resource.MustParse("1Ki"),
+						v1.ResourceMemory: resource.MustParse("1Ki"),
+					},
+				},
+			},
+		},
+		ResizeStatusEntries: map[string]v1.PodResizeStatus{},
+	}
```
Comment (tallclair) [inline pkg/kubelet/status/state/state_checkpoint_test.go:171]: nit: move this to right after you define the marshalled checkpoint data, so it's easier to compare & clear that both need to be updated together.

File: pkg/kubelet/status/state/checkpoint.go [hunk 30]
```diff
@@ -18,48 +18,63 @@ package state
 
 import (
 	"encoding/json"
-
-	v1 "k8s.io/api/core/v1"
+	"fmt"
+	"k8s.io/api/core/v1"
```
[the remark this answers is not in the document]
Comment (yunwang0911) [reply pkg/kubelet/status/state/checkpoint.go:22]: `Applying suggestions on deleted lines is currently not supported.` I'm unable to commit this suggestion because of this reason. Let me update it.

File: pkg/kubelet/status/state/state_checkpoint_test.go (hunk 29 above)
Comment (yunwang0911) [reply pkg/kubelet/status/state/state_checkpoint_test.go:171]: updated

File: pkg/kubelet/status/state/checkpoint.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (yunwang0911) [reply pkg/kubelet/status/state/checkpoint.go:38]: > That said, a lot of this checkpoint code is identical to the DRA checkpoint, including this Checkpoint type. Should we just move all of this to the pkg/kubelet/checkpointmanager package?

Could we separate this into a different task? Since there are many checkpoints, cpu, memory, dra, device and status, refactoring the code will impact not only InPlacePodVerticalScaling feature gate.

[the remark this answers is not in the document]
Comment (yunwang0911) [reply pkg/kubelet/status/state/checkpoint.go:38]: What do you think? @tallclair

[the remark this answers is not in the document]
Comment (tallclair) [reply pkg/kubelet/status/state/checkpoint.go:38]: Yeah, sounds good. Can you file an issue and/or leave a TODO?
