### PR TITLE
kubeadm: switch to a local implementation of wrapped errors

### LINKED ISSUE #3205: replace usage of github.com/pkg/errors
as suggested by @HirazawaUi we are adding this issue to track formally the effort of replacing the usage of https://github.com/pkg/errors in kubeadm. the project is archive and unmaintained.

while that is not a big issue since it's a small project without notable bugs and security issues, we are facing the issue occasionally where kubeadm contributors are sending PRs trying to replace the usage with `fmt.Errorf` and `%w`.
it should be noted that `fmt.Errorf` and `%w` alone are not a direct replacement.

pkg/errors provides wrapping, unwrapping but also stack traces.
if we are to replace this library we would need a 1-to-1 replacement, i.e. adding some code in the kubeadm source tree under cmd/kubeadm/app/utils/errors/errors.go and ensuring there are unit tests that guarantee we are 1-to-1 compatible with what pkg/errors provides.

### PR DESCRIPTION
**Pull request by neolit123**
#### What type of PR is this?

/kind cleanup deprecation

#### What this PR does / why we need it:

pkg/errors is archived and while there is go-errors/errors as
an alternative, it lacks wraping methods. kubeadm has
specific neends and it's better to implement something
minimal locally instead of introducing another depedency.

- Implement basic wrapped errors and stack trace support.
cmd/kubeadm/app/util/errors.
- Remove unused error codes >1. At some point it seems we broke
these and 1 was returned for all error types.
- Remove the Error type in preflight and separate the printing
of '[preflight]' message and the error return from preflight
checks.
- Print an 'error:' prefix for all errors.

(second commit is a big diff)

- Replace usage of pkg/errors with the local util/errors.
- Run kinder/hack/orderimports tool from kubeadm repo to
order the imports in the source tree.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/3205

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: consistently print an 'error: ' prefix before errors.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: cmd/kubeadm/app/util/errors/errors.go [hunk 1]
```diff
@@ -0,0 +1,202 @@
...
+	"fmt"
+	"os"
+	"runtime"
+	"strconv"
+	"strings"
+)
+
+const (
+	// defaultErrorExitCode defines exit the code for failed action generally
+	defaultErrorExitCode = 1
```
Comment (neolit123) [inline cmd/kubeadm/app/util/errors/errors.go:36]: check the deleted util/error.go file.

we used to have code 2 and 3 for preflight and validation errors (implemented kind of hacky), but when i built kubeadm from master it always returned code 1. would appreciated if someone double checks as we don't want to break the return of error codes with this pr. seems like it was broken a long time ago?

what i did was:
- `kubeadm init` without `sudo` it errors and and then `echo $?` gives `1`.
 - pass a bad config to `kubeadm init --config`. that is supposed to return >1 code, but it again returns 1.

**Comment by neolit123** [comment]
external e2e passing
- https://github.com/neolit123/kubeadm-test/actions/runs/15444232632
- https://github.com/neolit123/kubeadm-test/actions/runs/15444227996

**Comment by neolit123** [comment]
/retest

```
=== Failed
=== FAIL: cmd/kubeadm/app/cmd/upgrade TestEnforceRequirements/Fail_pre-flight_check (0.18s)
[preflight] Running pre-flight checks.
[preflight] Some fatal errors occurred:
	[ERROR CoreDNSUnsupportedPlugins]: Get "http://localhost:8000/api/v1/namespaces/kube-system/configmaps/coredns?timeout=10s": dial tcp [::1]:8000: connectex: No connection could be made because the target machine actively refused it.
	[ERROR CoreDNSMigration]: Get "http://localhost:8000/api/v1/namespaces/kube-system/configmaps/coredns?timeout=10s": dial tcp [::1]:8000: connectex: No connection could be made because the target machine actively refused it.
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
    common_test.go:114: enforceRequirements returned unexpected error, expected: ERROR CoreDNSUnsupportedPlugins, got preflight checks failed
=== FAIL: cmd/kubeadm/app/cmd/upgrade TestEnforceRequirements (0.47s)
```

odd, seems to be reported from older commit in this PR.

**Review by SataQiu — COMMENTED** [review]
/approve

File: cmd/kubeadm/app/util/errors/errors.go [hunk 2]
```diff
@@ -0,0 +1,200 @@
...
+
+Unless required by applicable law or agreed to in writing, software
+distributed under the License is distributed on an "AS IS" BASIS,
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+
+// Package errors contains a local implementation of error wrapping
+// similar to https://github.com/pkg/errors.
```
Comment (HirazawaUi) [inline cmd/kubeadm/app/util/errors/errors.go]: I noticed this code isn't from github.com/pkg/errors, it's your own implementation. Do we need to mention that it resembles github.com/pkg/errors in certain aspects?

While reviewing some ancient PRs, I found that we used to have quite strict requirements regarding the attribution of code origins:
ref: https://github.com/kubernetes/kubernetes/pull/7936#discussion_r30364233

I believe if our implementation is significantly different from theirs, we can avoid mentioning github.com/pkg/errors here.

This isn’t critical, but it might avoid unnecessary complications. If I’m just overthinking it, we can skip this comment.

Comment (neolit123) [reply cmd/kubeadm/app/util/errors/errors.go]: i think the language of the comment is ok. mentioning that it's "similar" to pkg/errors gives attribution to the original project, but this is written from scratch and not forked as you can tell.

> https://github.com/kubernetes/kubernetes/pull/7936#discussion_r30364233

in that case the code was forked and it correctly landed under the third_party directory.

Comment (neolit123) [reply cmd/kubeadm/app/util/errors/errors.go]: i can update the comment to clarify it's written from scratch

edit: updated

Comment (HirazawaUi) [reply cmd/kubeadm/app/util/errors/errors.go]: /lgtm

File: cmd/kubeadm/app/util/errors/errors.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/util/errors/errors.go:36]: @SataQiu @HirazawaUi did you manage to double check?

Comment (HirazawaUi) [reply cmd/kubeadm/app/util/errors/errors.go:36]: Honestly, I'm quite surprised by this, I tried checkout to the release-1.16 branch, building kubeadm, and testing it. kubeadm init consistently returns exit code 1 when preflight checks fail, rather than 2 or 3.

This behavior might have been broken for years. If we need to salvage it, we can open another PR to restore the correct exit codes after this one is merged.
```
root@kind-control-plane:/# ./kubeadm init
I0605 13:24:03.997387    4408 version.go:251] remote version is much newer: v1.33.1; falling back to: stable-1.16
[init] Using Kubernetes version: v1.16.15
[preflight] Running pre-flight checks
	[WARNING FileExisting-socat]: socat not found in system path
[preflight] The system verification failed. Printing the output from the verification:
KERNEL_VERSION: 5.15.0-140-generic
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR Port-6443]: Port 6443 is in use
	[ERROR Port-10259]: Port 10259 is in use
	[ERROR Port-10257]: Port 10257 is in use
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
	[ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
	[ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
	[ERROR Swap]: running with swap on is not supported. Please disable swap
	[ERROR SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found in directory /lib/modules/5.15.0-140-generic\n", err: exit status 1
	[ERROR KubeletVersion]: the kubelet version is higher than the control plane version. This is not a supported version skew and may lead to a malfunctional cluster. Kubelet version: "1.33.0-alpha.1.2272+252a41079430bd" Control plane version: "1.16.15"
	[ERROR Port-10250]: Port 10250 is in use
	[ERROR Port-2379]: Port 2379 is in use
	[ERROR Port-2380]: Port 2380 is in use
	[ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
root@kind-control-plane:/# echo $?
1
root@kind-control-plane:/# ./kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.16-rc.0.1+18936c8b181de5-dirty", GitCommit:"18936c8b181de5701fba4f0b958317f9dbdab0a1", GitTreeState:"dirty", BuildDate:"2025-06-05T13:22:39Z", GoVersion:"go1.23.1", Compiler:"gc", Platform:"linux/arm64"}
```

Comment (neolit123) [reply cmd/kubeadm/app/util/errors/errors.go:36]: ok, thanks for checking. no, i think we should keep the error code of 1 for now unless users actually request this functionally for different error codes to be added. it would also need a cleaner design compared to how it was done before.

**Review by hashim21223445 — APPROVED** [review]
