### PR TITLE
Return error if get NodeStageSecret and NodePublishSecret failed

### LINKED ISSUE #61052: CSI volume plugin should report error when it can't fetch secrets.
CSI volume plugin only logs an error when it can't fetch secret referenced by NodeStageSecretRef or NodePublishSecretRef. It should return error instead, so user knows that something is wrong.

/sig storage
/assign
/kind bug

### PR DESCRIPTION
**Pull request by mlmhl**
**What this PR does / why we need it**:

Currently, if got NodeStageSecret  or NodePublishSecret failed, we just log the error and assume that there is no credential. I think we should report the error as if user specified these secret, they expect to apply some credentials.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #61052

**Release note**:

```release-note
Return error if get NodeStageSecret and NodePublishSecret failed in CSI volume plugin
```

/sig storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/approve
I let @vladimirvivien lgtm this PR

File: pkg/volume/csi/csi_util.go [hunk 1]
```diff
@@ -23,16 +23,16 @@ import (
 	"k8s.io/client-go/kubernetes"
 )
 
-func getCredentialsFromSecret(k8s kubernetes.Interface, secretRef *api.SecretReference) map[string]string {
+func getCredentialsFromSecret(k8s kubernetes.Interface, secretRef *api.SecretReference) (map[string]string, error) {
 	credentials := map[string]string{}
 	secret, err := k8s.CoreV1().Secrets(secretRef.Namespace).Get(secretRef.Name, meta.GetOptions{})
 	if err != nil {
 		glog.Warningf("failed to find the secret %s in the namespace %s with error: %v\n", secretRef.Name, secretRef.Namespace, err)
```
Comment (saad-ali) [inline pkg/volume/csi/csi_util.go]: Change `Warningf` to `Errorf`

File: pkg/volume/csi/csi_attacher.go [hunk 2]
```diff
@@ -318,6 +318,15 @@ func (c *csiAttacher) MountDevice(spec *volume.Spec, devicePath string, deviceMo
 	}
 	publishVolumeInfo := attachment.Status.AttachmentMetadata
 
+	nodeStageSecrets := map[string]string{}
+	if csiSource.NodeStageSecretRef != nil {
+		nodeStageSecrets, err = getCredentialsFromSecret(c.k8s, csiSource.NodeStageSecretRef)
+		if err != nil {
+			return fmt.Errorf("get secret %s/%s failed: %v",
```
Comment (saad-ali) [inline pkg/volume/csi/csi_attacher.go]: nit: `"fetching NodeStageSecretRef failed for secret %s/%s failed: %v`

File: pkg/volume/csi/csi_mounter.go [hunk 3]
```diff
@@ -153,6 +153,15 @@ func (c *csiMountMgr) SetUpAt(dir string, fsGroup *int64) error {
 
 	attribs := csiSource.VolumeAttributes
 
+	nodePublishSecrets := map[string]string{}
+	if csiSource.NodePublishSecretRef != nil {
+		nodePublishSecrets, err = getCredentialsFromSecret(c.k8s, csiSource.NodePublishSecretRef)
```
Comment (saad-ali) [inline pkg/volume/csi/csi_mounter.go]: nit: `"fetching NodePublishSecretRef failed for secret %s/%s failed: %v`

**Review by saad-ali — COMMENTED** [review]
Some nits, otherwise LGTM

File: pkg/volume/csi/csi_util.go (hunk 1 above)
Comment (mlmhl) [reply pkg/volume/csi/csi_util.go]: Fixed.

File: pkg/volume/csi/csi_attacher.go (hunk 2 above)
Comment (mlmhl) [reply pkg/volume/csi/csi_attacher.go]: Thanks for reminding, already fixed.

File: pkg/volume/csi/csi_mounter.go (hunk 3 above)
Comment (mlmhl) [reply pkg/volume/csi/csi_mounter.go]: Same as above.

**Comment by saad-ali** [comment]
Thanks!!

/lgtm
/approve

**Comment by saad-ali** [comment]
Please cherry pick back to 1.10 branch once this is merged.

**Comment by saad-ali** [comment]
@mlmhl Please cherry pick back to 1.10 branch.

**Comment by mlmhl** [comment]
@saad-ali   Thanks for reminding, the cherry pick PR has been submitted.
