### PR TITLE
Fix resizepolicy ephemeral container docs

### LINKED ISSUE #128384: API documentation incorrectly states that resizePolicy can be set to ephemeral containers
### What happened?

스크린샷 2024-10-27 172423
Based on the concept of `resizePolicy`, it is expected behavior that `resizePolicy` cannot be assigned to ephemeral containers, as they do not support resource requests or limits.

However, in the Kubernetes v1.31 API documentation, there is no clear indication that the `resizePolicy` option is disallowed for ephemeral containers, which may lead to confusion for users.
image
image

### `pkg/apis/core/validation/validation_test.go`
```go
func TestValidateEphemeralContainers(t *testing.T) {
...
...
...
	{
			"Container uses disallowed field: ResizePolicy",
			line(),
			[]core.EphemeralContainer{{
				EphemeralContainerCommon: core.EphemeralContainerCommon{
					Name:                     "resources-resize-policy",
					Image:                    "image",
					ImagePullPolicy:          "IfNotPresent",
					TerminationMessagePolicy: "File",
					ResizePolicy: []core.ContainerResizePolicy{
						{ResourceName: "cpu", RestartPolicy: "NotRequired"},
					},
				},
			}},
			field.ErrorList{{Type: field.ErrorTypeForbidden, Field: "ephemeralContainers[0].resizePolicy"}},
		}
	...
	...
	...
```
As shown in the code above, it is explicitly stated that `resizePolicy` cannot be assigned to ephemeral containers.
This restriction is not reflected in the API documentation, potentially leading users to believe they can apply `resizePolicy` to ephemeral containers. Including this limitation in the documentation would improve clarity and enhance the user experience.

### What did you expect to happen?

The Kubernetes v1.31 API documentation should clearly state that `resizePolicy` cannot be assigned to ephemeral containers, as they do not support resource requests or limits. This clarification would prevent users from mistakenly assuming that `resizePolicy` can be applied to ephemeral containers and help avoid configuration errors.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the Kubernetes v1.31 API documentation.
2. [Navigate to the section discussing `resizePolicy` for containers.](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#containerresizepolicy-v1-core)
3. [Review the documentation regarding ephemeral containers.](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#ephemeralcontainer-v1-core)
4. Observe that there is no mention or clarification that `resizePolicy` cannot be applied to ephemeral containers, leading to potential misunderstandings.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.1

```

</details>

### Cloud provider

<details>
On-Premises
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
RETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux masternode-virtual-machine 6.8.0-47-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct  2 16:16:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by cvan20191**
/kind documentation
This PR updates the API documentation for containers and ephemeral containers to clearly state that restricted fields are not allowed for ephemeral containers, matching validation logic and reviewer recommendations.
Fixes #128384
**What this PR does / why we need it:**
- Adds `// You cannot set this field on ephemeral containers.` to the doc comment for ALL restricted fields in ephemeral containers:
  - ResizePolicy
- Updates both `staging/src/k8s.io/api/core/v1/types.go` and `pkg/apis/core/types.go`
- Ensures documentation is clear and consistent with field validation and reviewer direction. This helps users avoid misconfiguration and aligns docs with code.
**Notes  for reviewer:**
- Changes are in both `staging/src/k8s.io/api/core/v1/types.go` and `pkg/apis/core/types.go`
- Ran `make update` to propagate changes to generated files (openapi specs, swagger, protobuf, etc.)
- All restricted fields now have consistent documentation style

```release-note
NONE
```

### CODE REVIEW

**Comment by cvan20191** [comment]
Adding release note to satisfy bot requirements.

```release-note
NONE
```

**Comment by cvan20191** [comment]
Adding release note to satisfy bot requirements.

```release-note
NONE
```

**Comment by cvan20191** [comment]
Hi, this PR has been open for a week and is waiting for /ok-to-test to start CI. Would someone from @kubernetes/sig-node-pr-reviews be able to help? Thank you!

File: pkg/apis/core/types.go [hunk 1]
```diff
@@ -4336,7 +4336,7 @@ type EphemeralContainerCommon struct {
 	// Optional: Defaults to the container runtime's default working directory.
 	// +optional
 	WorkingDir string
-	// Ports are not allowed for ephemeral containers.
+	// You cannot set this field on ephemeral containers.
```
Comment (liggitt) [inline pkg/apis/core/types.go]: prefer "This field cannot be set on ephemeral containers" over "You cannot set ..."

It's also ok to leave the existing documentation in place to explain the meaning of the field, and just add in the line about it not being able to be set

File: staging/src/k8s.io/client-go/applyconfigurations/core/v1/ephemeralcontainercommon.go [hunk 2]
```diff
@@ -73,29 +74,35 @@ type EphemeralContainerCommonApplyConfiguration struct {
 	Env []EnvVarApplyConfiguration `json:"env,omitempty"`
 	// Resources are not allowed for ephemeral containers. Ephemeral containers use spare resources
 	// already allocated to the pod.
+	// This field cannot be set on ephemeral containers.
```
Comment (ajaysundark) [inline staging/src/k8s.io/client-go/applyconfigurations/core/v1/ephemeralcontainercommon.go]: @cvan20191 Could you clean up your PR to address only for the resizePolicy as was the scope for this issue? Other fields already have doc comments clarifying their applicability to ephemeral containers.

Comment (cvan20191) [reply staging/src/k8s.io/client-go/applyconfigurations/core/v1/ephemeralcontainercommon.go]: Ok i can scope this PR to ResizePolicy only. 
But In the earlier PR for the same issue [(#[132981](https://github.com/kubernetes/kubernetes/pull/132981#discussion_r2248029663) @soltysh suggested aligning docs for all disallowed ephemeral container fields using allowedEphemeralContainerFields in pkg/apis/core/validation/validation.go. I’m happy to do that as a follow‑up to keep this PR small. Do you prefer the broader update here or in a separate PR. /cc @ajaysundark @liggitt @soltysh

**Comment by kannon92** [comment]
Thank you!

/lgtm

**Review by ajaysundark — APPROVED** [review]
