### PR TITLE
Fix mounting NFS resources in IPv6 bare-metal environment #101066

### LINKED ISSUE #101066: [sig-storage] [Driver: nfs] bare-metal IPv6 environment, pods fail to mount nfs storage resources
#### What happened:
In bare-metal IPv6 environment, any pod consuming `nfs` storage resource is not able to run. 

``` Events:
  Type     Reason       Age                 From               Message
  ----     ------       ----                ----               -------
  Normal   Scheduled    103s                default-scheduler  Successfully assigned default/nfs-busybox-6r96h to ipv6-control-plane
  
Warning  FailedMount  38s (x8 over 102s)  kubelet  MountVolume.SetUp failed for volume "nfs" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs fd00:10:96::4310:/ /var/lib/kubelet/pods/0a118c63-6933-4dc2-b676-619d2679797c/volumes/kubernetes.io~nfs/nfs
Output: mount.nfs: Failed to resolve server fd00: Name or service not known
```

#### What you expected to happen:
The storage should be consumable, and the pod should become in `running` status.

#### How to reproduce it (as minimally and precisely as possible):
Running the [nfs-example](https://github.com/kubernetes/examples/tree/master/staging/volumes/nfs) in a bare-metal IPv6 configurations. I have replaced the cloud-based storage resource with a `local-storage PV and PVC` mounted to a folder on my localhost. Steps alongside logs are below :- 

**$kubectl get svc**                
```
NAME         TYPE        CLUSTER-IP         EXTERNAL-IP   PORT(S)                      AGE
kubernetes   ClusterIP   fd00:10:96::1      <none>        443/TCP                      5m31s
nfs-server   ClusterIP   fd00:10:96::4310   <none>        2049/TCP,20048/TCP,111/TCP   3m43s 
```

**$kubectl describe svc nfs-server**
```
Name:              nfs-server
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          role=nfs-server
Type:              ClusterIP
IP:                fd00:10:96::4310
Port:              nfs  2049/TCP
TargetPort:        2049/TCP
Endpoints:         [fd00:10:244::5]:2049
Port:              mountd  20048/TCP
TargetPort:        20048/TCP
Endpoints:         [fd00:10:244::5]:20048
Port:              rpcbind  111/TCP
TargetPort:        111/TCP
Endpoints:         [fd00:10:244::5]:111
Session Affinity:  None
Events:            <none>
```

 **$kubectl describe pv nfs** 
```       
Name:            nfs
Labels:          <none>
Annotations:     pv.kubernetes.io/bound-by-controller: yes
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    
Status:          Bound
Claim:           default/nfs
Reclaim Policy:  Retain
Access Modes:    RWX
VolumeMode:      Filesystem
Capacity:        1Mi
Node Affinity:   <none>
Message:         
Source:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    fd00:10:96::4310
    Path:      /
    ReadOnly:  false
Events:        <none>
```

**$kubectl get pod -w**
```NAME               READY   STATUS    RESTARTS   AGE
nfs-server-vsj45   1/1     Running   0          4m18s
```

#### _now try to create a pod to consume the nfs server, through a `PV & PVC`_

```
$kubectl create -f nfs-busybox-rc.yaml 
replicationcontroller/nfs-busybox created
```

**$kubectl get pod -w**
```
NAME                READY   STATUS              RESTARTS   AGE
nfs-busybox-6r96h   0/1     ContainerCreating   0          69s
nfs-busybox-zljnl   0/1     ContainerCreating   0          69s
nfs-server-vsj45    1/1     Running             0          6m6s
```

**$kubectl describe pod nfs-busybox-6r96h**
```
Events:
  Type     Reason       Age                 From               Message
  ----     ------       ----                ----               -------
  Normal   Scheduled    103s                default-scheduler  Successfully assigned default/nfs-busybox-6r96h to ipv6-control-plane
  


Warning  FailedMount  38s (x8 over 102s)  kubelet            MountVolume.SetUp failed for volume "nfs" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs fd00:10:96::4310:/ /var/lib/kubelet/pods/0a118c63-6933-4dc2-b676-619d2679797c/volumes/kubernetes.io~nfs/nfs
Output: mount.nfs: Failed to resolve server fd00: Name or service not known
```
#### Anything else we need to know?:

I have built the master branch to make sure it was not fixed up to this moment.

### PR DESCRIPTION
**Pull request by Elbehery**
#### What type of PR is this?

/kind bug
/kind storage
/label nfs
/label ipv6

#### What this PR does / why we need it:

Fix mounting `nfs` volumes in `ipv6` environment. 

#### Which issue(s) this PR fixes:

Fixes #101066 

#### Special notes for your reviewer:
Enclose only ipv6 within `[ ]`.

```release-note
Fixed mounting of NFS volumes when IPv6 address is used as a server.
```

### CODE REVIEW

**Comment by Elbehery** [comment]
In addition to the testing procedure described in the `contribute` docs, I have tested it locally according to the reproducing steps described in #101066, below are the logs :- 

```
$kubectl get svc                
NAME         TYPE        CLUSTER-IP         EXTERNAL-IP   PORT(S)                      AGE
kubernetes   ClusterIP   fd00:10:96::1      <none>        443/TCP                      3h35m
nfs-server   ClusterIP   fd00:10:96::63f1   <none>        2049/TCP,20048/TCP,111/TCP   89s
```

```
$kubectl get pod -w                   
NAME                READY   STATUS              RESTARTS   AGE
nfs-busybox-ppv7h   0/1     ContainerCreating   0          2s
nfs-busybox-xqrqp   0/1     ContainerCreating   0          2s
nfs-server-x86wb    1/1     Running             0          2m34s
nfs-busybox-ppv7h   1/1     Running             0          7s
nfs-busybox-xqrqp   1/1     Running             0          8s
```

File: pkg/volume/nfs/nfs_test.go [hunk 1]
```diff
@@ -181,6 +181,22 @@ func TestPluginVolume(t *testing.T) {
 	doTestPlugin(t, volume.NewSpecFromVolume(vol))
 }
 
+func TestIPV6VolumeSource(t *testing.T) {
+	vol := &v1.Volume{
+		Name:         "vol1",
+		VolumeSource: v1.VolumeSource{NFS: &v1.NFSVolumeSource{Server: "0:0:0:0:0:0:0:1", Path: "/somepath", ReadOnly: false}},
+	}
+	doTestPlugin(t, volume.NewSpecFromVolume(vol))
```
Comment (jsafrane) [inline pkg/volume/nfs/nfs_test.go:189]: doTestPlugin does not test that the plugin added `[ ]` around the IP address, you need to add it there.

Comment (Elbehery) [reply pkg/volume/nfs/nfs_test.go:189]: fixed 👍🏽

Comment (Elbehery) [reply pkg/volume/nfs/nfs_test.go:189]: @jsafrane `nfsMounter` does not expose `server` field, so that I can assert upon it. 

I have been trying to find an interface implemented by `nfsMounter` that exposes the field, but I could not.  I can :- 

```
 func (nfsMounter *nfsMounter) getServer() string {
	return nfsMounter.server
}
```
What do u think ?

File: pkg/volume/nfs/nfs_test.go [hunk 2]
```diff
@@ -118,6 +119,18 @@ func doTestPlugin(t *testing.T, spec *volume.Spec) {
 	if mounter == nil {
 		t.Errorf("Got a nil Mounter")
 	}
+	if nfsm, ok := mounter.(*nfsMounter); ok {
```
Comment (Elbehery) [inline pkg/volume/nfs/nfs_test.go:122]: @jsafrane  I avoided changing anything in the `pkg` itself for testing, so i came up with this way, I hope it suffice

File: pkg/volume/nfs/nfs.go [hunk 3]
```diff
@@ -121,7 +122,10 @@ func (plugin *nfsPlugin) newMounterInternal(spec *volume.Spec, pod *v1.Pod, moun
 	if err != nil {
 		return nil, err
 	}
-
+	// wrap ipv6 into `[ ]`
+	if net.ParseIP(source.Server).To16() != nil {
+		source.Server = fmt.Sprintf("[%s]", source.Server)
+	}
```
Comment (aojea) [inline pkg/volume/nfs/nfs.go:128]: is ok to mutate the field?
should not be better to use something like 
```
        server := source.Server
	if net.ParseIP(source.Server).To16() != nil {
		server = fmt.Sprintf("[%s]", source.Server)
	}
```
and then assign server to the nfsMounter.server?

Comment (Elbehery) [reply pkg/volume/nfs/nfs.go:128]: I agree with you that it's better not to mutate, specially that `source.Server` is a `pointer`. 
However in this case, `source.Server` is returned from a private/helper, and the side-effects are bound to the function itself. 

But I agree with you its more safe, a fix on the way, thanks a lot for your review 🙏🏽

File: pkg/volume/nfs/nfs_test.go (hunk 2 above)
Comment (Elbehery) [reply pkg/volume/nfs/nfs_test.go:122]: @aojea  do you have a comment on this `mock` ? .. I tried to avoid adding a `method` just to assert `un-exported` field

Comment (aojea) [reply pkg/volume/nfs/nfs_test.go:122]: well, to be honest, the test has exactly the same code that the functionality, the only way to fail is if one of those diverge in the future :)

just throwing an idea, what if the fix goes here
https://github.com/kubernetes/kubernetes/blob/4f6c595240b2c2277482c8c10a3d1ad4a177b73e/pkg/volume/nfs/nfs.go#L258 

it seems a better place that current one , if IPv6 you build the source with brackets for the server.
This way, you can mock `nfsMounter.mounter.MountSensitiveWithoutSystemd(` 
https://github.com/kubernetes/kubernetes/blob/4f6c595240b2c2277482c8c10a3d1ad4a177b73e/pkg/volume/nfs/nfs.go#L191

and assert the server ip in `mountOptions`

https://github.com/kubernetes/kubernetes/blob/4f6c595240b2c2277482c8c10a3d1ad4a177b73e/pkg/volume/nfs/nfs.go#L264

Comment (Elbehery) [reply pkg/volume/nfs/nfs_test.go:122]: @aojea  this way, the fix will affect only the `mounter` when it is being `setUp` not `created`. 

The problem arose in the first place, when `pods` consuming `nfs` could not find the resource, and 
I searched the usage of both `setUp` which affects the mounter only when used. On the other hand, `newMounter` is used by `kubelet` so when the resource is actually allocated. 

Please correct me if I am wrong 🙏🏽

**Comment by Elbehery** [comment]
@aojea  I have applied your suggestions, with extra assertions 👍🏽

File: pkg/volume/nfs/nfs_test.go [hunk 4]
```diff
@@ -136,6 +136,23 @@ func doTestPlugin(t *testing.T, spec *volume.Spec) {
...
+	} else {
+		if mntDevs[0].Type != "nfs" {
+			t.Errorf("unexpected type of mounted devices. expected: %v, got %v", "nfs", mntDevs[0].Type)
+		}
+		src, _, _ := getVolumeSource(spec)
+		srvr := getServerFromSource(src)
+		expectedDevice := fmt.Sprintf("%s:%s", srvr, src.Path)
+		if mntDevs[0].Device != expectedDevice {
+			t.Errorf("unexpected nfs device, expected %q, got: %q", expectedDevice, mntDevs[0].Device)
+		}
```
Comment (jsafrane) [inline pkg/volume/nfs/nfs_test.go:154]: All these checks are good to have, but we do not test anywhere that `[]` was actually added. The test will pass even without it.

There are multiple ways how to solve it, I would probably add a new explicit `expectedDevice` argument to `doTestPlugin()` and did not calculate it inside. But you need to update all the unit tests :-\.

File: pkg/volume/nfs/nfs_test.go (hunk 1 above)
Comment (jsafrane) [reply pkg/volume/nfs/nfs_test.go:206]: I meant something like this:
```patch
--- a/pkg/volume/nfs/nfs_test.go
+++ b/pkg/volume/nfs/nfs_test.go
@@ -96,7 +96,7 @@ func TestRecycler(t *testing.T) {
        }
 }
 
-func doTestPlugin(t *testing.T, spec *volume.Spec) {
+func doTestPlugin(t *testing.T, spec *volume.Spec, expectedDevice string) {
        tmpDir, err := utiltesting.MkTmpdir("nfs_test")
        if err != nil {
                t.Fatalf("error creating temp dir: %v", err)
@@ -146,9 +146,6 @@ func doTestPlugin(t *testing.T, spec *volume.Spec) {
                if mntDevs[0].Type != "nfs" {
                        t.Errorf("unexpected type of mounted devices. expected: %v, got %v", "nfs", mntDevs[0].Type)
                }
-               src, _, _ := getVolumeSource(spec)
-               srvr := getServerFromSource(src)
-               expectedDevice := fmt.Sprintf("%s:%s", srvr, src.Path)
                if mntDevs[0].Device != expectedDevice {
                        t.Errorf("unexpected nfs device, expected %q, got: %q", expectedDevice, mntDevs[0].Device)
                }
@@ -203,7 +200,7 @@ func TestIPV6VolumeSource(t *testing.T) {
                Name:         "vol1",
                VolumeSource: v1.VolumeSource{NFS: &v1.NFSVolumeSource{Server: "0:0:0:0:0:0:0:1", Path: "/somepath", ReadOnly: false}},
        }
-       doTestPlugin(t, volume.NewSpecFromVolume(vol))
+       doTestPlugin(t, volume.NewSpecFromVolume(vol), "[0:0:0:0:0:0:0:1]:/somepath")
 }
 
 func TestIPV4VolumeSource(t *testing.T) {
```

(+ you need to update all other `doTestPlugin` calls)
This way you can explicitly specify that `[]` should be added to IPv6 addresses and not to ipv4.

Comment (Elbehery) [reply pkg/volume/nfs/nfs_test.go]: @jsafrane added in the last commit 👍🏽
