### PR TITLE
Rerun init containers when the pod needs to be restarted

### LINKED ISSUE #36485: Containers from init-containers section do not execute during node reboots
BUG REPORT
**Kubernetes version**
v1.4.3+coreos.0

**Environment**:
- **Cloud provider or hardware configuration**:
Bare metal CoreOS installation. 3 management nodes + 2 worker nodes.
- **OS** (e.g. from /etc/os-release):
`CoreOS stable (1185.3.0)`
- **Kernel** 
`4.7.3-coreos-r2`

**What happened**:
I added an `init-container` to the `kube-scheduler.yaml` file in `/etc/kubernetes/manifests` directory. It was executed once after the yaml file modification. When I rebooted the node running this POD, the POD was restarted but the `init-container` did not execute:

The kube-scheduler.yaml file:
```
apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
      {
        "image": "quay.io/coreos/hyperkube:v1.4.3_coreos.0",
        "name": "wait-for-master",
        "command": [ "/bin/bash", "-c", "while ! timeout 1 bash -c \"/kubectl --server=http://127.0.0.1:8080/ cluster-info\"; do sleep 1; done" ]
      }
    ]'
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: quay.io/coreos/hyperkube:v1.4.3_coreos.0
    command:
    - /hyperkube
    - scheduler
    - --master=http://127.0.0.1:8080
    - --leader-elect=true
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 1
```

The POD description after the node reboot:
```
Name:           kube-scheduler-10.54.147.6
Namespace:      kube-system
Node:           10.54.147.6/10.54.147.6
Start Time:     Wed, 09 Nov 2016 07:51:35 +0100
Labels:         <none>
Status:         Running
IP:             10.54.147.6
Controllers:    <none>
Init Containers:
  wait-for-master:
    Container ID:       docker://ff5ef0e759eb332c50fcc117a5758c41080835addbd76e33eb60cdde10d9587b
    Image:              quay.io/coreos/hyperkube:v1.4.3_coreos.0
    Image ID:           docker://sha256:5d3bc50f81574bc41952e13862b04b98f310ab60601ff990e7267a4ba5227e8b
    Port:
    Command:
      /bin/bash
      -c
      while ! timeout 1 bash -c "/kubectl --server=http://127.0.0.1:8080/ cluster-info"; do sleep 1; done
    State:                      Terminated
      Reason:                   Completed
      Exit Code:                0
      Started:                  Tue, 08 Nov 2016 14:17:27 +0100
      Finished:                 Tue, 08 Nov 2016 14:17:35 +0100
    Ready:                      True
    Restart Count:              0
    Volume Mounts:              <none>
    Environment Variables:      <none>
Containers:
  kube-scheduler:
    Container ID:       docker://03e40bb84d477e6a284c4bfdf677d15135fe78785b17ae62d09cd04063f81aec
    Image:              quay.io/coreos/hyperkube:v1.4.3_coreos.0
    Image ID:           docker://sha256:5d3bc50f81574bc41952e13862b04b98f310ab60601ff990e7267a4ba5227e8b
    Port:
    Command:
      /hyperkube
      scheduler
      --master=http://127.0.0.1:8080
      --leader-elect=true
    State:                      Running
      Started:                  Wed, 09 Nov 2016 07:51:36 +0100
    Last State:                 Terminated
      Reason:                   Error
      Exit Code:                2
      Started:                  Tue, 08 Nov 2016 20:50:42 +0100
      Finished:                 Wed, 09 Nov 2016 07:48:44 +0100
    Ready:                      True
    Restart Count:              4
    Liveness:                   http-get http://127.0.0.1:10251/healthz delay=15s timeout=1s period=10s #success=1 #failure=3
    Volume Mounts:              <none>
    Environment Variables:      <none>
Conditions:
  Type          Status
  Initialized   True 
  Ready         True 
  PodScheduled  True 
No volumes.
QoS Class:      BestEffort
Tolerations:    <none>
```

**How to reproduce it**
Create a pod with the `cloud-init` section and pin it to one node. Reboot the node several times and check if the `cloud-init` container was executed.

### PR DESCRIPTION
**Pull request by yujuhong**
Whenever pod sandbox needs to be recreated, all containers associated
with it will be killed by kubelet. This change ensures that the init
containers will be rerun in such cases.

The change also refactors the compute logic so that the control flow of
init containers act is more aligned with the regular containers. Unit
tests are added to verify the logic.

This fixes #36485

### CODE REVIEW

**Comment by yujuhong** [comment]
/cc @yifan-gu 
Still WIP; not a large-scale improvement, but at least this PR should make init containers work more similar to regular containers.

**Comment by dchen1107** [comment]
@yujuhong if @smarterclayton couldn't review it before 1.7 release, I am going review this pr right after 1.7 release. Is that ok with you?

**Comment by yujuhong** [comment]
> @yujuhong if @smarterclayton couldn't review it before 1.7 release, I am going review this pr right after 1.7 release. Is that ok with you?

This is for 1.8, so there is no rush.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 1]
```diff
@@ -394,141 +388,112 @@ func (m *kubeGenericRuntimeManager) podSandboxChanged(pod *v1.Pod, podStatus *ku
...
+	expectedHash := kubecontainer.HashContainer(container)
+	return expectedHash, containerStatus.Hash, containerStatus.Hash != expectedHash
+}
 
-	return initFailed
+func shouldRestartOnFailure(pod *v1.Pod) bool {
+	return pod.Spec.RestartPolicy != v1.RestartPolicyNever
 }
 
 // computePodContainerChanges checks whether the pod spec has changed and returns the changes if true.
```
Comment (smarterclayton) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: rename this as well

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 2]
```diff
@@ -394,141 +388,112 @@ func (m *kubeGenericRuntimeManager) podSandboxChanged(pod *v1.Pod, podStatus *ku
...
+		reason := ""
+		restart := shouldRestartOnFailure(pod)
+		if expectedHash, actualHash, changed := containerChanged(&container, containerStatus); changed {
+			reason = fmt.Sprintf("Container spec hash changed (%d vs %d).", actualHash, expectedHash)
+			// Restart regardless of the restart policy because the container
+			// spec changed.
+			restart = true
+		} else if liveness, found := m.livenessManager.Get(containerStatus.ID); found && liveness == proberesults.Failure {
+			// If the container failed the liveness probe, we should kill it.
+			reason = "container failed liveness probe."
```
Comment (smarterclayton) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: Should be capitalized like the other reasons

File: pkg/kubelet/kuberuntime/kuberuntime_container.go [hunk 3]
```diff
@@ -660,6 +655,36 @@ func (m *kubeGenericRuntimeManager) pruneInitContainersBeforeStart(pod *v1.Pod,
...
+	}
+	for name := range initContainerNames {
+		count := 0
+		for _, status := range podStatus.ContainerStatuses {
+			if status.Name != name || !initContainerNames.Has(status.Name) {
+				continue
+			}
+			// Purge all init containers that match this container name
+			glog.V(4).Infof("Removing init container %q instance %q %d", status.Name, status.ID.ID, count)
+			if err := m.runtimeService.RemoveContainer(status.ID.ID); err != nil {
```
Comment (feiskyer) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go]: Call `m.DeleteContainer()` instead, which also removes logs.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 4]
```diff
@@ -687,20 +639,10 @@ func (m *kubeGenericRuntimeManager) SyncPod(pod *v1.Pod, _ v1.PodStatus, podStat
 
 		// Successfully started the container; clear the entry in the failure
 		glog.V(4).Infof("Completed init container %q for pod %q", container.Name, format.Pod(pod))
-		return
-	}
-	if !done {
-		// init container still running
-		glog.V(4).Infof("An init container is still running in pod %v", format.Pod(pod))
-		return
```
Comment (feiskyer) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: Why this is removed? kubelet should wait all init containers finished before starting regular containers.

Comment (yujuhong) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: The `computePodActions` will NOT add any containers to start if init containers are still running. This way, we separate the compute logic and the actual operations.
You can check the unit tests and see those are included in the test cases.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 2 above)
Comment (yujuhong) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: Done

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 1 above)
Comment (yujuhong) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: Done

File: pkg/kubelet/kuberuntime/kuberuntime_container.go (hunk 3 above)
Comment (yujuhong) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go]: Good call. Updated.

File: pkg/kubelet/kuberuntime/kuberuntime_manager_test.go [hunk 5]
```diff
@@ -625,53 +659,396 @@ func TestSyncPodWithInitContainers(t *testing.T) {
...
+		SandboxID:         baseStatus.SandboxStatuses[0].Id,
+		ContainersToStart: []int{},
+		ContainersToKill:  map[kubecontainer.ContainerID]containerToKillInfo{},
+	}
+
+	for desc, test := range map[string]struct {
+		mutatePodFn    func(*v1.Pod)
+		mutateStatusFn func(*kubecontainer.PodStatus)
+		actions        podActions
+	}{
```
Comment (yujuhong) [inline pkg/kubelet/kuberuntime/kuberuntime_manager_test.go]: @smarterclayton @dchen1107, please read the description of the test cases and make sure they meet your expectation. Thanks!

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 4 above)
Comment (feiskyer) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: yep, thanks for explanation.

**Comment by feiskyer** [comment]
LGTM

File: pkg/kubelet/kuberuntime/kuberuntime_container.go [hunk 6]
```diff
@@ -638,19 +638,44 @@ func (m *kubeGenericRuntimeManager) pruneInitContainersBeforeStart(pod *v1.Pod,
...
+// Remove all init containres. Note that this function does not check the state
+// of the container because it assumes all init containers have been stopped
+// before the call happens.
+func (m *kubeGenericRuntimeManager) purgeInitContainers(pod *v1.Pod, podStatus *kubecontainer.PodStatus) {
+	initContainerNames := sets.NewString()
+	for _, container := range pod.Spec.InitContainers {
+		initContainerNames.Insert(container.Name)
+	}
+	for name := range initContainerNames {
+		count := 0
```
Comment (munnerz) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go]: From what I can see here, this 'count' variable never increments? It's printed below on L673, and in the previous implementation would be incremented on each iteration of the `podStatus.ContainerStatuses` loop.

I'm not particularly familiar with this bit of code, so I could be wrong. I'm currently attempting to port this patch to the 1.6 `dockertools` implementation.

Comment (yujuhong) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go]: Yes, the `count` should be incremented. Will do this later, after getting more comments. The variable is only used in the log message, so it does not affect the functionality of the code.

**Comment by yujuhong** [comment]
@dchen1107 @Random-Liu @smarterclayton PTAL.

**Comment by smarterclayton** [comment]
Tests look good to me.  This is generally LGTM, although I can do a deeper pass if necessary.

**Comment by yujuhong** [comment]
> Tests look good to me. This is generally LGTM, although I can do a deeper pass if necessary.

Thanks for the review! That's exactly what I needed from you and @dchen1107 

@feiskyer already took a pass and LGTM'd the PR. I'll keep the PR open for a couple more days because @Random-Liu mentioned that he may have time to look at it.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 7]
```diff
@@ -394,141 +388,112 @@ func (m *kubeGenericRuntimeManager) podSandboxChanged(pod *v1.Pod, podStatus *ku
...
 	}
-	changes.InitFailed = initFailed
 
+	// Number of running containers to keep.
+	keepCount := 0
 	// check the status of containers.
-	for index, container := range pod.Spec.Containers {
+	for idx, container := range pod.Spec.Containers {
 		containerStatus := podStatus.FindContainerStatusByName(container.Name)
+		// If container does not exist, or is not running, check whehter we
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: s/whehter/whether

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 8]
```diff
@@ -394,141 +388,112 @@ func (m *kubeGenericRuntimeManager) podSandboxChanged(pod *v1.Pod, podStatus *ku
...
+			reason = fmt.Sprintf("Container spec hash changed (%d vs %d).", actualHash, expectedHash)
+			// Restart regardless of the restart policy because the container
+			// spec changed.
+			restart = true
+		} else if liveness, found := m.livenessManager.Get(containerStatus.ID); found && liveness == proberesults.Failure {
+			// If the container failed the liveness probe, we should kill it.
+			reason = "Container failed liveness probe."
+		} else {
+			// Keep the container.
+			keepCount += 1
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: nit: `++`

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go [hunk 9]
```diff
@@ -587,7 +556,9 @@ func (m *kubeGenericRuntimeManager) SyncPod(pod *v1.Pod, _ v1.PodStatus, podStat
 	}
 
 	// Keep terminated init containers fairly aggressively controlled
-	m.pruneInitContainersBeforeStart(pod, podStatus, podContainerChanges.InitContainersToKeep)
+	// This is an optmization because container removals are typically handled
+	// by container garbage collector.
+	m.pruneInitContainersBeforeStart(pod, podStatus)
```
Comment (Random-Liu) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: We purge and prune, add an options seems cleaner.

File: pkg/kubelet/kuberuntime/kuberuntime_container.go [hunk 10]
```diff
@@ -620,7 +620,7 @@ func (m *kubeGenericRuntimeManager) killContainersWithSyncResult(pod *v1.Pod, ru
 // pruneInitContainers ensures that before we begin creating init containers, we have reduced the number
 // of outstanding init containers still present. This reduces load on the container garbage collector
 // by only preserving the most recent terminated init container.
-func (m *kubeGenericRuntimeManager) pruneInitContainersBeforeStart(pod *v1.Pod, podStatus *kubecontainer.PodStatus, initContainersToKeep map[kubecontainer.ContainerID]int) {
+func (m *kubeGenericRuntimeManager) pruneInitContainersBeforeStart(pod *v1.Pod, podStatus *kubecontainer.PodStatus) {
```
Comment (yujuhong) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go]: I disagree. I think it's clear what each function does with the current naming. Adding a boolean would make the function more complicated and harder to test.

File: pkg/kubelet/kuberuntime/kuberuntime_container.go [hunk 11]
```diff
@@ -638,19 +638,44 @@ func (m *kubeGenericRuntimeManager) pruneInitContainersBeforeStart(pod *v1.Pod,
 			if count == 1 {
 				continue
 			}
-			// if there is a reason to preserve the older container, do so
-			if _, ok := initContainersToKeep[status.ID]; ok {
+			// prune all other init containers that match this container name
+			glog.V(4).Infof("Removing init container %q instance %q %d", status.Name, status.ID.ID, count)
+			if err := m.DeleteContainer(status.ID); err != nil {
```
Comment (yujuhong) [inline pkg/kubelet/kuberuntime/kuberuntime_container.go]: You're right. Switching both to `m.removeContainer(status.ID.ID)` to make them consistent. I think we do need to clean up the log here since we don't do it anywhere else.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 7 above)
Comment (yujuhong) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: Fixed.

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 8 above)
Comment (yujuhong) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: I think both are perfectly fine unless this documented as convention(?)

File: pkg/kubelet/kuberuntime/kuberuntime_manager.go (hunk 9 above)
Comment (yujuhong) [inline pkg/kubelet/kuberuntime/kuberuntime_manager.go]: Still think it's clear to keep both functions.

**Comment by yujuhong** [comment]
@Random-Liu comments addressed. PTAL again, thanks

**Comment by yujuhong** [comment]
Pushed a new commit to address a bug @Random-Liu found (good catch!). Also added a new unit test for it.

**Comment by Random-Liu** [comment]
@yujuhong LGTM without full confidence. I could understand the current behavior, and it looks good. However, It's hard to figure out the original behavior, so I don't have full confidence that there won't be regression or behavior change.

**Comment by yujuhong** [comment]
Rebased and squashed the commits. 
Applying the lgtm label based on LGTMs from https://github.com/kubernetes/kubernetes/pull/47599#issuecomment-322915825 and https://github.com/kubernetes/kubernetes/pull/47599#issuecomment-322335233

**Comment by feiskyer** [comment]
@yujuhong Adds a release-note for this?
