### PR TITLE
kubelet: Mark new terminal pods as non-finished in pod worker

### LINKED ISSUE #116925: E2eNode Suite.[It] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] DevicePlugin [Serial] [Disruptive] Keeps device plugin assignments across pod and kubelet restarts
### Which jobs are failing?

New TestGrid alerts at [sig-node-release-blocking#node-kubelet-serial-containerd](https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-serial-containerd) since commit/f393e7da7.

### Which tests are failing?

Found 2 failing rows in node-kubelet-serial-containerd: 2 new, 0 other 2 new Test Failures in node-kubelet-serial-containerd.
Test [ci-kubernetes-node-kubelet-serial-containerd.Overall](https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-serial-containerd) has failed 3 times since it last passed at commit/0c62b122c. It started failing between commit/0c62b122c (Fri Mar 24 12:02 PDT) and commit/f393e7da7 (Fri Mar 24 16:03 PDT): .
Test [kubetest.Node Tests](https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-serial-containerd) has failed 3 times since it last passed at commit/0c62b122c. It started failing between commit/0c62b122c (Fri Mar 24 12:02 PDT) and commit/f393e7da7 (Fri Mar 24 16:03 PDT): .

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1640188846626836480
```


E2eNode Suite: [It] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] DevicePlugin [Serial] [Disruptive] Keeps device plugin assignments across pod and kubelet restarts expand_less | 5m0s
-- | --
{ failed [FAILED] Timed out after 300.001s. Expected success, but got an error:     <*errors.errorString \| 0xc001a780d0>:      expected v1alpha pod resources to be empty, but got non-empty resources: [&PodResources{Name:test-admit-pod,Namespace:localstorage-quota-monitoring-test-3367,Containers:[]*ContainerResources{&ContainerResources{Name:test-admit-pod,Devices:[]*ContainerDevices{},},},} &PodResources{Name:pod-29ef7b7f-9fc8-480d-bdb6-237dde51a0d4,Namespace:pod-conditions-4082,Containers:[]*ContainerResources{&ContainerResources{Name:web1,Devices:[]*ContainerDevices{},},},}]     {         s: "expected v1alpha pod resources to be empty, but got non-empty resources: [&PodResources{Name:test-admit-pod,Namespace:localstorage-quota-monitoring-test-3367,Containers:[]*ContainerResources{&ContainerResources{Name:test-admit-pod,Devices:[]*ContainerDevices{},},},} &PodResources{Name:pod-29ef7b7f-9fc8-480d-bdb6-237dde51a0d4,Namespace:pod-conditions-4082,Containers:[]*ContainerResources{&ContainerResources{Name:web1,Devices:[]*ContainerDevices{},},},}]",     } In [BeforeEach] at: test/e2e_node/device_plugin_test.go:110 @ 03/27/23 04:20:05.564 }


```

### Since when has it been failing?

Not sure

### Testgrid link

https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-serial-containerd

### Reason for failure (if possible)

suspect https://github.com/kubernetes/kubernetes/issues/116715

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node release

### PR DESCRIPTION
**Pull request by bobbypage**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

The pod worker may recieve a new pod which is marked as terminal in
the runtime cache. This can occur if a pod is marked as terminal and the
kubelet is restarted.

The kubelet needs to drive these pods through the termination state
machine. If upon restart, the kubelet receives a pod which is terminal
based on runtime cache, it indicates that pod finished
`SyncTerminatingPod`, but it did not complete `SyncTerminatedPod`. The
pod worker needs ensure that `SyncTerminatedPod` will run on these pods.
To accomplish this, set `finished=False`, on the pod sync status, to
drive the pod through the rest of the state machine.

This will ensure that status manager and other kubelet subcomponents
(e.g. volume manager), will be aware of this pod and properly cleanup
all of the resources of the pod after the kubelet is restarted.

While making change, also update the comments to provide a bit more
background around why the kubelet needs to read the runtime pod cache
for newly synced terminal pods.

This change fixes issue #116925. Also introduce a new regression test for
#116925 which restarts the kubelet while a pod is terminating and
ensures the pod is properly deleted. This test currently fails on master
without this change.

#### Which issue(s) this PR fixes:

Fixes #116925

#### Does this PR introduce a user-facing change?

```release-note
Kubelet terminates pods correctly upon restart, fixing an issue where pods may have not been fully terminated if the kubelet was restarted during pod termination.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/kubelet/pod_workers.go [hunk 1]
```diff
@@ -775,16 +775,23 @@ func (p *podWorkers) UpdatePod(options UpdatePodOptions) {
...
+					// This implies that this pod had already completed `SyncTerminatingPod` sometime in the past. The pod is likely being synced for the first time due to a kubelet restart.
+					// These pods need to complete SyncTerminatedPod to ensure that all resources are cleaned the status manager is aware of this pod.
+					// As a result, set finished: false, to ensure a Terminated event will be sent and `SyncTerminatedPod` will run.
 					status = &podSyncStatus{
 						terminatedAt:       now,
 						terminatingAt:      now,
 						syncedAt:           now,
 						startedTerminating: true,
-						finished:           true,
+						finished:           false,
```
Comment (smarterclayton) [inline pkg/kubelet/pod_workers.go:794]: Definitely wins kubelet code golf

**Comment by smarterclayton** [comment]
Looks correct, how flaky / racy is the e2e?  I really wish we could interpose a proxy to control api behavior.

File: test/e2e_node/restart_test.go [hunk 2]
```diff
@@ -265,5 +269,103 @@ var _ = SIGDescribe("Restart [Serial] [Slow] [Disruptive]", func() {
 				}
 			}
 		})
+		// Regression test for https://issues.k8s.io/116925
+		ginkgo.It("should delete pods which are marked as terminal and have a deletion timestamp set after restart", func(ctx context.Context) {
```
Comment (mimowo) [inline test/e2e_node/restart_test.go]: I think we should mark the test as Disruptive and Serial because it restarts Kubelet. In the past I observed that kubelet restarts make other tests fail occasionally.

File: test/e2e_node/restart_test.go [hunk 3]
```diff
@@ -265,5 +269,103 @@ var _ = SIGDescribe("Restart [Serial] [Slow] [Disruptive]", func() {
...
+					RestartPolicy:                 v1.RestartPolicyNever,
+					Containers: []v1.Container{
+						{
+							Name:    podName,
+							Image:   imageutils.GetE2EImage(imageutils.BusyBox),
+							Command: []string{"sh", "-c"},
+							Args: []string{`
+							_term() {
+								echo "Caught SIGTERM signal!"
+								sleep 5
```
Comment (mimowo) [inline test/e2e_node/restart_test.go]: Do we need this sleep? remove if not needed.

File: test/e2e_node/restart_test.go [hunk 4]
```diff
@@ -265,5 +269,103 @@ var _ = SIGDescribe("Restart [Serial] [Slow] [Disruptive]", func() {
...
+						framework.Logf("Observed Pod (%s/%s) in phase %v", pod.ObjectMeta.Namespace, pod.ObjectMeta.Name, pod.Status.Phase)
+						return false, nil
+					}
+					framework.Logf("Found Pod (%s/%s) in phase %v", pod.ObjectMeta.Namespace, pod.ObjectMeta.Name, pod.Status.Phase)
+					return found, nil
+				}
+				framework.Logf("Observed event: %+v", event.Object)
+				return false, nil
+			})
+			if err != nil {
```
Comment (mimowo) [inline test/e2e_node/restart_test.go:353]: use `framework.ExpectNoError` if possible

File: test/e2e_node/restart_test.go [hunk 5]
```diff
@@ -265,5 +269,103 @@ var _ = SIGDescribe("Restart [Serial] [Slow] [Disruptive]", func() {
...
+
+			ginkgo.By(fmt.Sprintf("Deleting the pod (%v/%v) to set a deletion timestamp", pod.Namespace, pod.Name))
+			time.Sleep(time.Second)
+			err = e2epod.NewPodClient(f).Delete(ctx, pod.Name, metav1.DeleteOptions{GracePeriodSeconds: &gracePeriod})
+			framework.ExpectNoError(err, "Failed to delete the pod: %q", pod.Name)
+
+			ctxUntil, cancel := context.WithTimeout(ctx, f.Timeouts.PodStart)
+			defer cancel()
+
+			ginkgo.By("Started watch for pods entering succeeded phase")
```
Comment (mimowo) [inline test/e2e_node/restart_test.go:337]: IIUC we are waiting for a specific pod here so I suggest to reflect this in the `ginkgo.By` comment.

File: test/e2e_node/restart_test.go [hunk 6]
```diff
@@ -265,5 +269,103 @@ var _ = SIGDescribe("Restart [Serial] [Slow] [Disruptive]", func() {
...
+			// As soon as the pod enters succeeded phase (detected by the watch above); kill the kubelet.
+			// This is a bit racy, but the goal is to stop the kubelet before the kubelet is able to delete the pod from the API-sever in order to repro https://issues.k8s.io/116925
+			ginkgo.By("Stopping the kubelet")
+			startKubelet := stopKubelet()
+			// wait until the kubelet health check will fail
+			gomega.Eventually(ctx, func() bool {
+				return kubeletHealthCheck(kubeletHealthCheckURL)
+			}, f.Timeouts.PodStart, f.Timeouts.Poll).Should(gomega.BeFalse())
+
+			framework.Logf("Starting the kubelet")
```
Comment (mimowo) [inline test/e2e_node/restart_test.go:367]: I think it would be cleaner to use `ginkgo.By` for consistency.

File: test/e2e_node/restart_test.go [hunk 7]
```diff
@@ -265,5 +269,103 @@ var _ = SIGDescribe("Restart [Serial] [Slow] [Disruptive]", func() {
...
+			startKubelet()
+
+			// wait until the kubelet health check will succeed
+			gomega.Eventually(ctx, func() bool {
+				return kubeletHealthCheck(kubeletHealthCheckURL)
+			}, f.Timeouts.PodStart, f.Timeouts.Poll).Should(gomega.BeTrue())
+
+			// after the kubelet is restarted, verify that the pod is deleted by the kubelet.
```
Comment (mimowo) [inline test/e2e_node/restart_test.go:375]: I would suggest to replace the comment with an actual step in ginkgo.By

File: test/e2e_node/restart_test.go [hunk 8]
```diff
@@ -265,5 +269,103 @@ var _ = SIGDescribe("Restart [Serial] [Slow] [Disruptive]", func() {
...
+							Image:   imageutils.GetE2EImage(imageutils.BusyBox),
+							Command: []string{"sh", "-c"},
+							Args: []string{`
+							_term() {
+								echo "Caught SIGTERM signal!"
+								sleep 5
+								exit 0
+							}
+							trap _term SIGTERM
+							while true; do sleep 5; done
```
[the remark this answers is not in the document]
Comment (bobbypage) [reply test/e2e_node/restart_test.go]: That's a good point and not necessary intentional :). It does not really matter for this test case, because if SIGTERM is sent, as soon as the sleep is finished (every 5sec), the term handler will run. 

In either case, it's unnecessary to wait for the sleep to be over, so I rewrote this to trap `SIGTERM` instead and `wait` on child sleep pid which results in the term trap being run immediately.

**Comment by bobbypage** [comment]
> Looks correct, how flaky / racy is the e2e? I really wish we could interpose a proxy to control api behavior.

The test is actually pretty reliable on master on catching the issue. I ran the e2e [10 times](https://gist.github.com/bobbypage/57151071a08bff3189880be7d7cda9b2) against master without the fix and it results in the test failing each time. I agree long term it would be nice if we could proxy the api-server and fake out certain responses, it would help to make tests like these more reliable.

File: pkg/kubelet/pod_workers.go [hunk 9]
```diff
@@ -775,16 +775,23 @@ func (p *podWorkers) UpdatePod(options UpdatePodOptions) {
...
+			// Check to see if the pod is not running and the pod is terminal; if this succeeds then record in the podWorker that it is terminated.
+			// This is needed because after a kubelet restart, we need to ensure terminal pods will NOT be considered active in Pod Admission. See http://issues.k8s.io/105523
+			// However, `filterOutInactivePods`, considers pods that are actively terminating as active. As a result, `IsPodKnownTerminated()` needs to return true and thus `terminatedAt` needs to be set.
 			if statusCache, err := p.podCache.Get(uid); err == nil {
 				if isPodStatusCacheTerminal(statusCache) {
+					// At this point we know:
+					// (1) The pod is terminal based on the config source.
+					// (2) The pod is terminal based on the runtime cache.
+					// This implies that this pod had already completed `SyncTerminatingPod` sometime in the past. The pod is likely being synced for the first time due to a kubelet restart.
+					// These pods need to complete SyncTerminatedPod to ensure that all resources are cleaned the status manager is aware of this pod.
```
Comment (mimowo) [inline pkg/kubelet/pod_workers.go:787]: I'm not sure how to interpret the last part of the sentence: "... the status manager is aware of this pod.". Please rephrase it or delete if not needed?

File: pkg/kubelet/pod_workers.go (hunk 1 above)
Comment (bobbypage) [reply pkg/kubelet/pod_workers.go:794]: haha, great to see it was a one-line change :)

File: test/e2e_node/restart_test.go [hunk 10]
```diff
@@ -265,5 +269,114 @@ var _ = SIGDescribe("Restart [Serial] [Slow] [Disruptive]", func() {
...
+			// wait until the kubelet health check will fail
+			gomega.Eventually(ctx, func() bool {
+				return kubeletHealthCheck(kubeletHealthCheckURL)
+			}, f.Timeouts.PodStart, f.Timeouts.Poll).Should(gomega.BeFalse())
+
+			framework.Logf("Starting the kubelet")
+			startKubelet()
+
+			// wait until the kubelet health check will succeed
+			gomega.Eventually(ctx, func() bool {
```
Comment (mimowo) [inline test/e2e_node/restart_test.go:371]: I'm wondering, the `updateKubeletConfig` in util.go does one more step when restarting the pod: https://github.com/kubernetes/kubernetes/blob/ad18954259eae3db51bac2274ed4ca7304b923c4/test/e2e_node/util.go#L225. Is it safe not to include this step here? Maybe we should consider refactoring the `updateKubeletConfig` code to reuse it for restart here even if there is no config change.

File: test/e2e_node/restart_test.go [hunk 11]
```diff
@@ -265,5 +269,114 @@ var _ = SIGDescribe("Restart [Serial] [Slow] [Disruptive]", func() {
 				}
 			}
 		})
+		// Regression test for https://issues.k8s.io/116925
```
Comment (mimowo) [inline test/e2e_node/restart_test.go:272]: I think the test should eventually be marked Disruptive and Serial as it restarts Kubelet.

**Review by mimowo — COMMENTED** [review]
LGTM overall, just nits in the comments and tests.

File: test/e2e_node/restart_test.go (hunk 3 above)
Comment (bobbypage) [reply test/e2e_node/restart_test.go]: It is not needed, I copied it over from other test, removed.

File: test/e2e_node/restart_test.go (hunk 6 above)
Comment (bobbypage) [reply test/e2e_node/restart_test.go:367]: Done (here and throughout).

File: test/e2e_node/restart_test.go (hunk 10 above)
Comment (bobbypage) [reply test/e2e_node/restart_test.go:371]: Thanks for the callout about that. I don't think it will matter too much because the poll for pod delete is 5 mins, so the node should become ready during this period. In either case, I agree it's better to be explicit about it and wait for node to become ready so added that.

I agree in the future we should refactor this shared logic out, I will look into a followup PR for that.

File: test/e2e_node/restart_test.go (hunk 11 above)
Comment (bobbypage) [reply test/e2e_node/restart_test.go:272]: This is already done, all the restart tests are marked as serial and disruptive - https://github.com/kubernetes/kubernetes/blob/2f6c4f5/test/e2e_node/restart_test.go#L70

File: test/e2e_node/restart_test.go (hunk 7 above)
Comment (bobbypage) [reply test/e2e_node/restart_test.go:375]: Done

File: test/e2e_node/restart_test.go (hunk 2 above)
Comment (bobbypage) [reply test/e2e_node/restart_test.go]: Yes, this is already done, please see https://github.com/kubernetes/kubernetes/pull/117019#discussion_r1162479722

File: pkg/kubelet/pod_workers.go (hunk 9 above)
Comment (bobbypage) [reply pkg/kubelet/pod_workers.go:787]: Reworded this, please take a look.

File: test/e2e_node/restart_test.go (hunk 10 above)
Comment (mimowo) [reply test/e2e_node/restart_test.go:368]: sgtm

File: pkg/kubelet/pod_workers.go (hunk 9 above)
Comment (mimowo) [reply pkg/kubelet/pod_workers.go]: sgtm

**Comment by bobbypage** [comment]
Thanks @mimowo and @smarterclayton for reviewing updated based on your comments.

**Comment by mimowo** [comment]
/lgtm
thank you for taking this!

File: test/e2e_node/restart_test.go [hunk 12]
```diff
@@ -265,5 +270,117 @@ var _ = SIGDescribe("Restart [Serial] [Slow] [Disruptive]", func() {
...
+		ginkgo.It("should delete pods which are marked as terminal and have a deletion timestamp set after restart", func(ctx context.Context) {
```
Comment (smarterclayton) [inline test/e2e_node/restart_test.go:274]: e2e serial run said this took only 5 seconds to complete.  That's... suspiciously fast.  Too fast?

Comment (bobbypage) [reply test/e2e_node/restart_test.go:274]: I updated the e2e test to remove the `sleep 5` from the SIGTERM handler so the container will exit right away (with success exit code) on SIGTERM. Here's the build logs, everything looks WAI:

```
[sig-node] Restart [Serial] [Slow] [Disruptive] Kubelet should delete pods which are marked as terminal and have a deletion timestamp set after restart
test/e2e_node/restart_test.go:274
  STEP: Creating a kubernetes client @ 04/11/23 09:42:21.496
  STEP: Building a namespace api object, basename restart-test @ 04/11/23 09:42:21.496
  Apr 11 09:42:21.500: INFO: Skipping waiting for service account
  STEP: Creating a pod (restart-test-806/terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650) with restart policy: Never @ 04/11/23 09:42:21.5
  STEP: Waiting for the pod (restart-test-806/terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650) to be running @ 04/11/23 09:42:21.504
  STEP: Deleting the pod (restart-test-806/terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650) to set a deletion timestamp @ 04/11/23 09:42:23.512
  STEP: Started watch for pod (restart-test-806/terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650) to enter succeeded phase @ 04/11/23 09:42:24.525
  I0411 09:42:24.525620    1061 retrywatcher.go:247] Starting RetryWatcher.
  STEP: Observed Pod (restart-test-806/terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650) in phase Running @ 04/11/23 09:42:24.528
  STEP: Found Pod (restart-test-806/terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650) in phase Succeeded @ 04/11/23 09:42:24.747
  STEP: Ended watch for pod entering succeeded phase @ 04/11/23 09:42:24.747
  STEP: Stopping the kubelet @ 04/11/23 09:42:24.747
  I0411 09:42:24.747491    1061 retrywatcher.go:147] "Stopping RetryWatcher."
  I0411 09:42:24.747584    1061 retrywatcher.go:281] Stopping RetryWatcher.
  Apr 11 09:42:24.761: INFO: Get running kubelet with systemctl:   UNIT                            LOAD   ACTIVE SUB     DESCRIPTION
    kubelet-20230411T085234.service loaded active running /tmp/node-e2e-20230411T085234/kubelet --kubeconfig /tmp/node-e2e-20230411T085234/kubeconfig --root-dir /var/lib/kubelet --v 4 --hostname-override n1-standard-2-cos-stable-105-17412-1-61-0b523e8d --container-runtime-endpoint unix:///run/containerd/containerd.sock --config /tmp/node-e2e-20230411T085234/kubelet-config --feature-gates=DisableKubeletCloudCredentialProviders=true,KubeletCredentialProviders=true --image-credential-provider-config=/tmp/node-e2e-20230411T085234/credential-provider.yaml --image-credential-provider-bin-dir=/tmp/node-e2e-20230411T085234 --kernel-memcg-notification=true --cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service

  LOAD   = Reflects whether the unit definition was properly loaded.
  ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
  SUB    = The low-level unit activation state, values depend on unit type.
  1 loaded units listed.
  , kubelet-20230411T085234
  W0411 09:42:24.792008    1061 util.go:477] Health check on "http://127.0.0.1:10248/healthz" failed, error=Head "http://127.0.0.1:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused
  STEP: Starting the kubelet @ 04/11/23 09:42:24.792
  W0411 09:42:24.809825    1061 util.go:477] Health check on "http://127.0.0.1:10248/healthz" failed, error=Head "http://127.0.0.1:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused
  STEP: After the kubelet is restarted, verify the pod (restart-test-806/terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650) is deleted by kubelet @ 04/11/23 09:42:26.813
  Apr 11 09:42:26.815: INFO: Waiting up to 3m0s for all (but 0) nodes to be ready
  STEP: Destroying namespace "restart-test-806" for this suite. @ 04/11/23 09:42:26.817
• [5.323 seconds]
```

And from the kubelet side, the pod is being handled correctly after restart: (Kubelet logs- https://gist.githubusercontent.com/bobbypage/f833a8a9bbfcb4e6af15b0953e560e89/raw/e7a82c0fca916dbbbaee0f799ccda7c131598127/gistfile0.txt)

Pod added for first time:

```
I0411 09:42:21.503828  141575 kubelet.go:2343] "SyncLoop ADD" source="api" pods=[restart-test-806/terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650]
```

Phase is updated to succeeded:

Delete is seen
```
I0411 09:42:24.515610  141575 kubelet.go:2359] "SyncLoop DELETE" source="api" pods=[restart-test-806/terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650]
```

SyncTerminatingPod runs:

```
I0411 09:42:24.515776  141575 kubelet.go:1943] "SyncTerminatingPod enter" pod="restart-test-806/terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650" podUID=b9b11ae3-4bcc-4ccc-937a-fa355e1c1866
```

```
I0411 09:42:24.734241  141575 kubelet.go:2029] "SyncTerminatingPod exit" pod="restart-test-806/terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650" podUID=b9b11ae3-4bcc-4ccc-937a-fa355e1c1866
```

Status is updated to succeeded 
```
I0411 09:42:24.746815  141575 status_manager.go:839] "Status for pod updated successfully" pod="restart-test-806/terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650" statusVersion=4 status={Phase:Succeeded Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2023-04-11 09:42:21 +0000 UTC Reason:PodCompleted Message:} {Type:Ready Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2023-04-11 09:42:24 +0000 UTC Reason:PodCompleted Message:} {Type:ContainersReady Status:False LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2023-04-11 09:42:24 +0000 UTC Reason:PodCompleted Message:} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2023-04-11 09:42:21 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.138.0.42 PodIP: PodIPs:[] StartTime:2023-04-11 09:42:21 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650 State:{Waiting:nil Running:nil Terminated:&ContainerStateTerminated{ExitCode:0,Signal:0,Reason:Completed,Message:,StartedAt:2023-04-11 09:42:21 +0000 UTC,FinishedAt:2023-04-11 09:42:24 +0000 UTC,ContainerID:containerd://909f4ece6fbf3d2920dc984354f79a94e598e77d583ba334d7cf24fa2dffb231,}} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:false RestartCount:0 Image:registry.k8s.io/e2e-test-images/busybox:1.29-4 ImageID:registry.k8s.io/e2e-test-images/busybox@sha256:2e0f836850e09b8b7cc937681d6194537a09fbd5f6b9e08f4d646a85128e8937 ContainerID:containerd://909f4ece6fbf3d2920dc984354f79a94e598e77d583ba334d7cf24fa2dffb231 Started:0xc0011cb439 AllocatedResources:map[] Resources:nil}] QOSClass:BestEffort EphemeralContainerStatuses:[] Resize:}
```

Kubelet restarts due to e2e test triggering restart as due to pod entering terminal phase:

```
I0411 09:42:24.874499  141807 flags.go:64] FLAG: --address="0.0.0.0"
```


Pod is added again after restart:

```
I0411 09:42:25.894460  141807 kubelet.go:2343] "SyncLoop ADD" source="api" pods=[restart-test-806/terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650]
I0411 09:42:25.894582  141807 pod_workers.go:770] "Pod is being synced for the first time" pod="restart-test-806/terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650" podUID=b9b11ae3-4bcc-4ccc-937a-fa355e1c1866 updateType="create"
```

Pod is deleted finally:

```
I0411 09:42:25.908268  141807 status_manager.go:868] "Pod fully terminated and removed from etcd" pod="restart-test-806/terminal-restart-pode7358abd-c6a2-4823-87b9-5dc93abe9650"
```

Comment (bobbypage) [reply test/e2e_node/restart_test.go:274]: Agree, it looks fast, but it looks WAI, I guess it's good see latency is down (even considering a kubelet restart in the middle of this test)!

Comment (mimowo) [reply test/e2e_node/restart_test.go:274]: Nice! It seems we should create a follow up Issue / PR to apply the same strategy to other tests which use sleep wait for SIGTERM.  Searching by "do sleep 5" I get hits in deleted_pods_test.go, node_shutdown_test.go, eviction_test.go, and system_node_critical_test.go

Comment (bobbypage) [reply test/e2e_node/restart_test.go:274]: Created followup issue for that - https://github.com/kubernetes/kubernetes/issues/117367

File: test/e2e_node/restart_test.go [hunk 13]
```diff
@@ -265,5 +270,117 @@ var _ = SIGDescribe("Restart [Serial] [Slow] [Disruptive]", func() {
...
+				WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
+					return f.ClientSet.CoreV1().Pods(f.Namespace.Name).Watch(ctx, options)
+				},
+			}
+
+			podsList, err := f.ClientSet.CoreV1().Pods(f.Namespace.Name).List(ctx, metav1.ListOptions{})
+			framework.ExpectNoError(err, "Failed to list pods in namespace: %s", f.Namespace.Name)
+
+			ginkgo.By(fmt.Sprintf("Deleting the pod (%v/%v) to set a deletion timestamp", pod.Namespace, pod.Name))
+			time.Sleep(time.Second)
```
Comment (smarterclayton) [inline test/e2e_node/restart_test.go:329]: What's this sleep for?

File: test/e2e_node/restart_test.go [hunk 14]
```diff
@@ -265,5 +270,117 @@ var _ = SIGDescribe("Restart [Serial] [Slow] [Disruptive]", func() {
...
+				}
+				ginkgo.By(fmt.Sprintf("Observed event: %+v", event.Object))
+				return false, nil
+			})
+			ginkgo.By("Ended watch for pod entering succeeded phase")
+			framework.ExpectNoError(err, "failed to see event that pod (%s/%s) enter succeeded phase: %v", pod.Namespace, pod.Name, err)
+
+			// As soon as the pod enters succeeded phase (detected by the watch above); kill the kubelet.
+			// This is a bit racy, but the goal is to stop the kubelet before the kubelet is able to delete the pod from the API-sever in order to repro https://issues.k8s.io/116925
+			ginkgo.By("Stopping the kubelet")
```
Comment (smarterclayton) [inline test/e2e_node/restart_test.go:357]: Better mechanism - put a finalizer on the pod at creation time.  Then remove the finalizer while the kubelet is stopped.  Then wait for the pod to be deleted.

Comment (bobbypage) [reply test/e2e_node/restart_test.go:357]: ah, that's a great idea to ensure that the kubelet will not be able to delete the pod and remove the raciness. Let me try it!

File: test/e2e_node/restart_test.go (hunk 13 above)
Comment (bobbypage) [reply test/e2e_node/restart_test.go:329]: This was copied over from here - https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/deleted_pods_test.go#L181-L182

I don't think we need it anymore, removed.

Comment (mimowo) [reply test/e2e_node/restart_test.go:329]: Oh, this one is tricky. The intention was to make sure that the trap `trap _term SIGTERM` is setup before deleting of the pod by the test code. There is a race actually, which can be seen if adding `sleep 10` before `trap _term SIGTERM` in the container code. Though, I think the race is very unlikely, it was proactive on my side, never hit a failure without putting the extra sleep in the container code.

Comment (mimowo) [reply test/e2e_node/restart_test.go:329]: I'm ok to delete the sleep. We can add it reactively if we face failures, or come up with a proper fix.

File: test/e2e_node/restart_test.go (hunk 14 above)
Comment (smarterclayton) [reply test/e2e_node/restart_test.go:357]: After discussion in chat there is an apparent bug in updating a deleting pod to remove a finalizer where it deletes the pod immediately, instead of waiting for grace period 0.  Given that this test is not too racy and we wish to backport this bug to previous releases and thus would like to minimize dependencies on other changes, for now we'll use the current mechanism and accept the potential for raciness.

We should open a follow up issue for the pod behavior we observed (and an e2e test!) and one to update tests like this.

**Comment by smarterclayton** [comment]
known flake

/retest

File: test/e2e_node/restart_test.go (hunk 14 above)
Comment (bobbypage) [reply test/e2e_node/restart_test.go:357]: Thanks @smarterclayton, will followup and create a new issue and reproducer for the issue regarding finalizer. Agreed that for now, we should stick with the current approach and update test when we will be able to use a finalizer.

File: test/e2e_node/restart_test.go (hunk 13 above)
Comment (mimowo) [reply test/e2e_node/restart_test.go:329]: FYI: https://github.com/kubernetes/kubernetes/pull/124396
