### PR TITLE
test: e2e: HPA ContainerResource - Lower requests b/c multiple containers will leave pending pods on existing test infra

### LINKED ISSUE #104427: New HPA ContainerResource e2e tests failing on Windows jobs
#### Which jobs are failing:

https://testgrid.k8s.io/sig-windows-master-release#aks-engine-windows-dockershim-serial-slow-master
https://testgrid.k8s.io/sig-windows-master-release#aks-engine-windows-containerd-serial-slow-master

#### Which test(s) are failing:

Kubernetes e2e suite.[sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) [Serial] [Slow] ReplicaSet with idle sidecar (ContainerResource use case) Should not scale up on a busy sidecar with an idle application
Kubernetes e2e suite.[sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) [Serial] [Slow] ReplicaSet with idle sidecar (ContainerResource use case) Should scale from 1 pod to 3 pods and from 3 to 5 on a busy application with an idle sidecar container

#### Since when has it been failing:

August 13th 2021
pr: https://github.com/kubernetes/kubernetes/pull/102666

#### Reason for failure:

feature is not turned on in api server

#### Anything else we need to know:

/sig windows
/assign
/triage accepted

### PR DESCRIPTION
**Pull request by jsturtevant**
#### What type of PR is this?
/kind failing-test

#### What this PR does / why we need it:
It lowers the requests for the HPA when testing the the side car resource consumption.  

The existing tests `Kubernetes e2e suite.[sig-autoscaling] [Feature:HPA] Horizontal pod autoscaling (scale resource: CPU) [Serial] [Slow] Deployment Should scale from 1 pod to 3 pods and from 3 to 5` works on the current infra with the same number for CPU requests.

Since the new tests adds a second container for each pod it double the amount of cpu required and causes the pod to go to pending and the test to timeout.  

#### Which issue(s) this PR fixes:

Fixes #104427

#### Special notes for your reviewer:

Another option considered was to increase the testing infra VM size. I assume other might have smaller sized vms for testing as well and this would break others.  This tests the same functionality but does so with out requiring a change infrastructure.

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

/sig testing
/sig autoscaling
/sig windows

### CODE REVIEW

**Comment by marosset** [comment]
I'm in favor of using the same values for Linux and Windows but if for some reason anyone objects we could leave the linux values as default and use these updated values if  `--node-os-distro=windows` is passed to e2e.test.

**Comment by bskiba** [comment]
@krzysied, @josephburnett would one of you be able to take a look?

File: test/e2e/autoscaling/horizontal_pod_autoscaling.go [hunk 1]
```diff
@@ -229,14 +229,14 @@ func scaleOnIdleSideCar(name string, kind schema.GroupVersionKind, checkStabilit
...
-		perContainerCPURequest:      500,
+		totalInitialCPUUsage:        125,
+		perContainerCPURequest:      250,
 		targetCPUUtilizationPercent: 20,
 		minPods:                     1,
 		maxPods:                     5,
 		firstScale:                  3,
 		firstScaleStasis:            stasis,
-		cpuBurst:                    700,
+		cpuBurst:                    500,
```
Comment (krzysied) [inline test/e2e/autoscaling/horizontal_pod_autoscaling.go:239]: Why every other value was divided by 2 and this one was changed differently?
(I understand it works anyway cause we set the max pods - I want to understand why "scaling" the test was not an option)

Comment (jsturtevant) [reply test/e2e/autoscaling/horizontal_pod_autoscaling.go:239]: maybe I miss understood this value, I though it was the amount of cpu put on to the pods to force scaling the pods.  I thought as long as this value is above the cpu request it would cause scaling.  Leaving it at 700 would work as well but I though should dial back to keep in line with other values.

> I want to understand why "scaling" the test was not an option

I don't understand what you mean by "scaling" the test?

Comment (jsturtevant) [reply test/e2e/autoscaling/horizontal_pod_autoscaling.go:239]: I confirmed this value is the amount of cpu to consume on the container: https://github.com/kubernetes/kubernetes/blob/f5e97186d297ee4d6254f634a591234ccdbe5ecb/test/e2e/autoscaling/horizontal_pod_autoscaling.go#L218

Comment (krzysied) [reply test/e2e/autoscaling/horizontal_pod_autoscaling.go:239]: I thought that burst number was calculated to trigger exactly 5 replicas (even if max pods number were higher). But it seems that it was previously adjusted for 7 replicas which is above the limit. My bad.

By "scaling" the test I meant diving each cpu value by 2, so the ratio will be conserved.

**Comment by jsturtevant** [comment]
/assign @bskiba 
for approval
