### PR TITLE
Fix stylistic isues with #5547. Closes #4910.

### LINKED ISSUE #4910: Limit number of pods that are allowed to run per machine
From the [networking notes](https://docs.google.com/document/d/1CIrbYl-tzu91sPNx43MoI6qhGSEm-mfqmQbl17M-1kI/edit) at the the 2015-02 kubernetes contributor conference.

### PR DESCRIPTION
**Pull request by davidopp**
@bgrant0607 @gmarek

### CODE REVIEW

File: cmd/kubelet/app/server.go [hunk 1]
```diff
@@ -108,7 +108,7 @@ type KubeletServer struct {
 	ContainerRuntime               string
 	DockerDaemonContainer          string
 	ConfigureCBR0                  bool
-	MaxPods                        int
+	Pods                        int
```
Comment (bgrant0607) [inline cmd/kubelet/app/server.go]: This could remain MaxPods. Also, it looks like indentation was changed -- needs gofmt if you change it.

File: cmd/kubelet/app/server.go [hunk 2]
```diff
@@ -227,7 +227,7 @@ func (s *KubeletServer) AddFlags(fs *pflag.FlagSet) {
 	fs.StringVar(&s.ContainerRuntime, "container_runtime", s.ContainerRuntime, "The container runtime to use. Possible values: 'docker', 'rkt'. Default: 'docker'.")
 	fs.StringVar(&s.DockerDaemonContainer, "docker-daemon-container", s.DockerDaemonContainer, "Optional resource-only container in which to place the Docker Daemon. Empty for no container (Default: /docker-daemon).")
 	fs.BoolVar(&s.ConfigureCBR0, "configure-cbr0", s.ConfigureCBR0, "If true, kubelet will configure cbr0 based on Node.Spec.PodCIDR.")
-	fs.IntVar(&s.MaxPods, "max_pods", 100, "Number of Pods that can run on this Kubelet.")
+	fs.IntVar(&s.Pods, "max-pods", 100, "Number of Pods that can run on this Kubelet.")
```
Comment (bgrant0607) [inline cmd/kubelet/app/server.go]: Thank you.

File: test/integration/scheduler_test.go [hunk 3]
```diff
@@ -146,7 +146,7 @@ func DoTestUnschedulableNodes(t *testing.T, restClient *client.Client, nodeStore
 		Spec:       api.NodeSpec{Unschedulable: false},
 		Status: api.NodeStatus{
 			Capacity: api.ResourceList{
-				"maxpods": *resource.NewQuantity(32, resource.DecimalSI),
+				"pods": *resource.NewQuantity(32, resource.DecimalSI),
```
Comment (bgrant0607) [inline test/integration/scheduler_test.go]: Why don't these use the ResourcePods constant?

File: plugin/pkg/scheduler/algorithm/predicates/predicates_test.go [hunk 4]
```diff
@@ -44,12 +44,12 @@ func (nodes FakeNodeListInfo) GetNodeInfo(nodeName string) (*api.Node, error) {
...
 }
 
-func makeResources(milliCPU int64, memory int64, maxPods int64) api.NodeResources {
+func makeResources(milliCPU int64, memory int64, pods int64) api.NodeResources {
 	return api.NodeResources{
 		Capacity: api.ResourceList{
 			"cpu":     *resource.NewMilliQuantity(milliCPU, resource.DecimalSI),
 			"memory":  *resource.NewQuantity(memory, resource.BinarySI),
-			"maxpods": *resource.NewQuantity(maxPods, resource.DecimalSI),
+			"pods": *resource.NewQuantity(pods, resource.DecimalSI),
```
Comment (bgrant0607) [inline plugin/pkg/scheduler/algorithm/predicates/predicates_test.go]: These should use the api.ResourceFoo constants, also.

**Comment by bgrant0607** [comment]
The API and flag changes LGTM, but you could revert the change to the internal Kubelet param.

**Comment by davidopp** [comment]
Addressed your suggestions; PTAL.

**Comment by bgrant0607** [comment]
LGTM, thanks much.
