### PR TITLE
vSphere: add token auth support for tags client

### LINKED ISSUE #75511: vSphere Cloud Provider does not support SAML auth tokens for tag-based node labeling
**What happened**:
The in-tree vpshere cloud provider does not support SAML auth tokens for the tag-based node labeling.   The provider relies on the [`withTagsClient` function](https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L1435) to authenticate with the vapi rest endpoints.  This function assumes that the `username` and `password` fields are set to a username and password.  In the case of SAML auth, these fields must be set to a cert and key, respectively.  The SAML auth setup is described here:  https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/saml-token-authentication.html

The vSphere cloud provider when not fetching tags uses a different auth handler which does properly handle SAML auth - https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vclib/connection.go#L91

So when using SAML auth tokens, the cloud provider is able to authenticate with the vSphere API to do things like identifying the vm from the uuid, but not able to authenticate with the vSphere API when fetching tags because it tries to use the cert and key as a basic auth username and password.

**What you expected to happen**:
The kubelet is able to acquire the tag-based labels for the node object using SAML token auth.

**How to reproduce it (as minimally and precisely as possible)**:
Set up SAML token authentication as described in the official docs: https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/saml-token-authentication.html

The kubelet logs indicate that zone info (from vm tags) cannot be retrieved due to an auth issue:
```
Mar 20 10:48:34 ul-lin-mast-8k kubelet[11752]: E0320 10:48:34.326226   11752 vsphere.go:1528] Get zone for node ul-lin-mast-8k: POST https://vcenterdo.arlington.predictivetechnologies.com:443/rest/com/vmware/cis/session: 401 Unauthorized
```

**Anything else we need to know?**:
Support for SSO in the govmomi vAPI was implemented here: https://github.com/vmware/govmomi/commit/54a181af415d37e446e71a07c93fb09fe2942720

**Environment**:
- Kubernetes version (use `kubectl version`):
1.14.0-beta.1
- Cloud provider or hardware configuration:
vSphere
- OS (e.g: `cat /etc/os-release`):
ubuntu 18.04

### PR DESCRIPTION
**Pull request by dougm**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

Support vSphere SAML token auth when using Zones.

**Which issue(s) this PR fixes**:

Fixes #75511

**Special notes for your reviewer**:

SAML auth support for the vCenter rest API endpoint came to govmomi a bit after Zone support came to vSphere Cloud Provider.

**Does this PR introduce a user-facing change?**:

```release-note
Support vSphere SAML token auth when using Zones
```

### CODE REVIEW

File: pkg/cloudprovider/providers/vsphere/vclib/connection.go [hunk 1]
```diff
@@ -123,9 +116,31 @@ func (connection *VSphereConnection) login(ctx context.Context, client *vim25.Cl
...
+	connection.credentialsLock.Lock()
+	defer connection.credentialsLock.Unlock()
+
+	signer, err := connection.Signer(ctx, client)
+	if err != nil {
 		return err
 	}
 
+	if signer == nil {
+		klog.V(3).Infof("SessionManager.Login with username '%s'", connection.Username)
```
Comment (neolit123) [inline pkg/cloudprovider/providers/vsphere/vclib/connection.go]: optionally `... username: %s`

File: pkg/cloudprovider/providers/vsphere/vclib/connection.go [hunk 2]
```diff
@@ -123,9 +116,31 @@ func (connection *VSphereConnection) login(ctx context.Context, client *vim25.Cl
...
+		return m.Login(ctx, neturl.UserPassword(connection.Username, connection.Password))
+	}
+
+	klog.V(3).Infof("SessionManager.LoginByToken with certificate '%s'", connection.Username)
```
Comment (neolit123) [inline pkg/cloudprovider/providers/vsphere/vclib/connection.go]: `SessionManager.LoginByToken for username: %s`?

**Review by neolit123 — COMMENTED** [review]
added minor, optional nits.

**Comment by dvonthenen** [comment]
Same for the comment/feedback on https://github.com/kubernetes/kubernetes/pull/75515/files#diff-28cf498e949ce852692c39ebc3d17818R142, does the value of Username contain the cert info? or the username?

If it contains the cert info, it's fine as is otherwise just a change to from certificate->Username. Other than that, this change is good!

File: pkg/cloudprovider/providers/vsphere/vclib/connection.go (hunk 1 above)
Comment (dougm) [reply pkg/cloudprovider/providers/vsphere/vclib/connection.go]: Do you mean remove the quotes?  It can be useful to quote values from config to see any leading/trailing whitespace.  But using `%q` is probably better for that.

**Comment by dougm** [comment]
@dvonthenen @neolit123 Username/Password fields can hold cert/key, this existing comment still applies: https://github.com/kubernetes/kubernetes/blob/d29afda3fabf27394313881b15250e5c2ade661b/pkg/cloudprovider/providers/vsphere/vclib/connection.go#L96-L98

File: pkg/cloudprovider/providers/vsphere/vclib/connection.go (hunk 1 above)
Comment (neolit123) [reply pkg/cloudprovider/providers/vsphere/vclib/connection.go]: yes, i guess `%q` is the alternative to `: %s`, if whitespace is to be tracked.

Comment (dougm) [reply pkg/cloudprovider/providers/vsphere/vclib/connection.go]: @neolit123 ok changed to `%q`

**Comment by dougm** [comment]
/assign @cblecker 
/assign @dims 

@cblecker @dims can you review the godeps update?

**Comment by cblecker** [comment]
/approve
for Godeps/
