### PR TITLE
e2e: node: cpumgr: cleanup after each test case

### LINKED ISSUE #130146: Failing test: CPU Manager [Serial] [Feature:CPUManager] With kubeconfig updated with static CPU Manager policy run the CPU Manager tests should not enforce CFS quota for containers with static CPUs assigned
### Which jobs are failing?

https://testgrid.k8s.io/sig-node-containerd#ci-cgroupv2-containerd-node-e2e-serial-ec2

### Which tests are failing?

CPU Manager [Feature:CPUManager] with static CPU manager policy

### Since when has it been failing?

02-12

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#ci-cgroupv2-containerd-node-e2e-serial-ec2

### Reason for failure (if possible)

_No response_

### Anything else we need to know?

_No response_

### Relevant SIG(s)

/sig node

### PR DESCRIPTION
**Pull request by ffromani**
Our CI machines happen to have 1 fully allocatable CPU for test workloads. This is really, really the minimal amount. But still should be sufficient for the tests to run the tests; the CFS quota pod, however, does create a series of pods (at time of writing, 6) and does the cleanup only at the very end the end. This means pods requiring resources accumulate on the CI machine node.

The fix implemented here is to just clean up after each subcase. Doing so the cpu test footprint is equal to the higher requirement (say, 1000 millicores) vs the sum of all the subcases requirements.

Doing like this doesn't change the test behavior, and make it possible to run it on very barebones machines.

#### What type of PR is this?

/kind cleanup
/kind failing-test

#### What this PR does / why we need it:
reduce the CPU footprint of node cpumanager cfs quota testcases, to avoid false negatives reds on CI

#### Which issue(s) this PR fixes:
Fixes #130146

#### Special notes for your reviewer:
N/A

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by ffromani** [comment]
note to self: it would be nice to move towards tabular tests. Here I'm intentionally narrowing down to the minimal (reasonnably clean) fix

**Comment by ffromani** [comment]
/test pull-kubernetes-node-kubelet-serial-containerd
/test pull-kubernetes-node-kubelet-serial-containerd-sidecar-containers
/test pull-kubernetes-node-kubelet-serial-cpu-manager
/test pull-kubernetes-node-kubelet-serial-hugepages
/test pull-kubernetes-node-kubelet-serial-memory-manager
/test pull-kubernetes-node-kubelet-serial-topology-manager

first thing first: no regressions

**Comment by ffromani** [comment]
/test pull-kubernetes-node-kubelet-serial-containerd

unrelated failure

File: test/e2e_node/cpu_manager_test.go [hunk 1]
```diff
@@ -596,17 +597,30 @@ func runCfsQuotaGuPods(ctx context.Context, f *framework.Framework, disabledCPUQ
 	var err error
 	var ctnAttrs []ctnAttribute
 	var pod1, pod2, pod3 *v1.Pod
-	var cleanupPods []*v1.Pod
+	podsToClean := make(map[apitypes.UID]*v1.Pod) // pod.UID -> pod
+
+	cleanupTestPod := func(ctx2 context.Context, pod *v1.Pod) {
```
Comment (swatisehgal) [inline test/e2e_node/cpu_manager_test.go:602]: Why restrict its scope to only this function? We could potentially use this in other places as well.

File: test/e2e_node/cpu_manager_test.go [hunk 2]
```diff
@@ -596,17 +597,30 @@ func runCfsQuotaGuPods(ctx context.Context, f *framework.Framework, disabledCPUQ
...
+		framework.Logf("deleting pod: %s/%s", pod.Namespace, pod.Name)
+		deletePodSyncByName(ctx2, f, pod.Name)
+		waitForContainerRemoval(ctx2, pod.Spec.Containers[0].Name, pod.Name, pod.Namespace)
+		framework.Logf("deleted pod: %s/%s", pod.Namespace, pod.Name)
+	}
+
+	deleteTestPod := func(pod *v1.Pod) {
+		// waitForContainerRemoval takes "long" to complete; if we use the parent ctx we get a
+		// 'deadline expired' message and the cleanup aborts, which we don't want.
```
Comment (swatisehgal) [inline test/e2e_node/cpu_manager_test.go:611]: Same as above?

File: test/e2e_node/cpu_manager_test.go [hunk 3]
```diff
@@ -596,17 +597,30 @@ func runCfsQuotaGuPods(ctx context.Context, f *framework.Framework, disabledCPUQ
...
+		cleanupTestPod(context.TODO(), pod)
```
Comment (swatisehgal) [inline test/e2e_node/cpu_manager_test.go:612]: What if there are failures in cleanup? With `context.TODO()` we could end up in indefinite waits in case of failures so perhaps it is better to use ` context .WithTImeout `with some reasonable timeout?

**Review by swatisehgal — COMMENTED** [review]
Overall LGTM

Left some minor comments/questions.

File: test/e2e_node/cpu_manager_test.go (hunk 1 above)
Comment (ffromani) [reply test/e2e_node/cpu_manager_test.go:602]: right, it's a pattern we have. Added another helper.

File: test/e2e_node/cpu_manager_test.go (hunk 2 above)
Comment (ffromani) [reply test/e2e_node/cpu_manager_test.go:611]: this one wants to be a closure thought because it manages the `podsToClean` map. I think most of the value comes from the previous helper anyway.

File: test/e2e_node/cpu_manager_test.go (hunk 3 above)
Comment (ffromani) [reply test/e2e_node/cpu_manager_test.go:612]: good point, waiting for hours just to see the lane fail is bad dev UX anyway. Adding a timeout.

**Comment by ffromani** [comment]
note to self: https://github.com/kubernetes/kubernetes/pull/127525#issuecomment-2606950229

**Comment by ffromani** [comment]
>pull-kubernetes-node-crio-cgrpv2-e2e

**Comment by ffromani** [comment]
the failure of the `pull-kubernetes-node-e2e-containerd-serial-ec2` lane seems real:
```
I0214 16:33:04.497614 26109 dump.go:53] At 2025-02-14 16:32:57 +0000 UTC - event for gu-pod4: {kubelet i-0c3cd180f6bd72e49} OutOfcpu: Node didn't have enough resource: cpu, requested: 1500, used: 0, capacity: 1000
```
more changes are needed

**Comment by ffromani** [comment]
/retest-required

the lane to focus on in the short term is `/test pull-kubernetes-node-e2e-containerd-serial-ec2`

**Comment by ffromani** [comment]
/retest-required

```
Kubernetes e2e suite: [It] [sig-cli] Kubectl client Simple pod should contain last line of the log 
```

**Comment by ffromani** [comment]
/test pull-kubernetes-integration

unrelated

**Comment by ffromani** [comment]
/test pull-kubernetes-node-e2e-containerd-serial-ec2

silly mistake, missing to include a case in the guard

**Comment by ffromani** [comment]
we're close to the final fix:
```
I0217 16:34:03.822014   23392 cpu_manager.go:178] "Detected CPU topology" topology={"NumCPUs":2,"NumCores":1,"NumUncoreCache":1,"NumSockets":1,"NumNUMANodes":1,"CPUDetails":{"0":{"NUMANodeID":0,"SocketID":0,"CoreID":0,"UncoreCacheID":0},"1":{"NUMANodeID":0,"SocketID":0,"CoreID":0,"UncoreCacheID":0}}}
I0217 16:34:03.822088   23392 policy_static.go:143] "Static policy created with configuration" options={"FullPhysicalCPUsOnly":false,"DistributeCPUsAcrossNUMA":false,"AlignBySocket":false,"DistributeCPUsAcrossCores":false,"StrictCPUReservation":false,"PreferAlignByUncoreCacheOption":false} cpuGroupSize=2
I0217 16:34:03.822134   23392 policy_static.go:180] "Reserved CPUs not available for exclusive assignment" reservedSize=1 reserved="0" reservedPhysicalCPUs="0-1"
```

so yes, CI machines have 2 cpus, and our detection logic in the test is still at fault

**Comment by ffromani** [comment]
the latest upload eventually fixed the cpumanager quota failures:
image

**Comment by ffromani** [comment]
none of the failures are related to cfs quota

**Comment by ffromani** [comment]
@swatisehgal (cc @kannon92 ) ready for review!

**Review by swatisehgal — COMMENTED** [review]
/lgtm

I am happy enough to proceed with this and would like to unblock the CI. There is some room for improvement as has been already captured in the PR but I am okay to defer that to a later stage.

/hold
to allow reviews from other reviewers

**Comment by ffromani** [comment]
hey folks, thanks for the reviews. Any remaining concerns or comments? otherwise I think we should remove the hold.
