### PR TITLE
fix: when PreFilter returns UnschedulableAndUnresolvable, copy the state in all nodes in statusmap

### LINKED ISSUE #119782: the preemption happens even when PreFilter returns UnschedulableAndUnresolvable
When PreFilter returns UnschedulableAndUnresolvable, we don't need to run the preemption, but currently we run.
This unexpected preemption could cause errors from the preemption by trying to read non-exist PreFilter data.

As @Huang-Wei pointed out ([ref](https://github.com/kubernetes/kubernetes/issues/119770#issuecomment-1666418637)), actually we didn't run the preemption in such cases in the past versions, but https://github.com/kubernetes/kubernetes/pull/110894 introduced this bug.

/kind bug 
/kind regression
/sig scheduling
/triage accepted
/priority important-soon

### PR DESCRIPTION
**Pull request by sanposhiho**
#### What type of PR is this?

/kind bug
/triage accepted
/priority important-soon

#### What this PR does / why we need it:

When PreFilter returns UnschedulableAndUnresolvable, we don't need to run the preemption, but we run. 
This unexpected preemption could cause errors from the preemption by trying to read non-exist PreFilter data.

As @Huang-Wei pointed out, we didn't run the preemption in such cases, but https://github.com/kubernetes/kubernetes/pull/110894 introduced this bug.

---

https://github.com/kubernetes/kubernetes/pull/119777 adds integ test for this scenario and https://github.com/kubernetes/kubernetes/pull/119780 proves this patch fixing the bug.

#### Which issue(s) this PR fixes:

Fixes: #119782

#### Special notes for your reviewer:

We should cherry-pick this to v1.26 and v1.27.

#### Does this PR introduce a user-facing change?

```release-note
Fixed a 1.26 regression scheduling bug by ensuring that preemption is skipped when a PreFilter plugin returns `UnschedulableAndUnresolvable`
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by sanposhiho** [comment]
will soon add UTs

**Review by Huang-Wei — COMMENTED** [review]
LGTM. Could you incorporate the integration test in (#119777) to this PR?

**Comment by sanposhiho** [comment]
Sure, added.

File: test/integration/scheduler/preemption/preemption_test.go [hunk 1]
```diff
@@ -111,18 +114,39 @@ func (fp *tokenFilter) Name() string {
...
+}
+
+type stateData struct{}
+
+func (sd *stateData) Clone() framework.StateData {
+	return sd
 }
 
 func (fp *tokenFilter) PreFilter(ctx context.Context, state *framework.CycleState, pod *v1.Pod) (*framework.PreFilterResult, *framework.Status) {
+	if pod.Name == fp.PreFilterTargetPodName && fp.PreFilterStatus.IsSkip() {
```
Comment (Huang-Wei) [inline test/integration/scheduler/preemption/preemption_test.go:138]: I think here we should only check is: (not quite a fan to check the pod name if we can achieve this by the following logic)

```go
if fp.PreFilterStatus.Code() == framework.UnschedulableAndUnresolvable || fp.PreFilterStatus.IsSkip() {
	return nil, fp.PreFilterStatus
}
```

File: test/integration/scheduler/preemption/preemption_test.go [hunk 2]
```diff
@@ -111,18 +114,39 @@ func (fp *tokenFilter) Name() string {
...
+		// not store stateData in CycleState when returning Skip.
+		// It shouldn't be problem because Filter shouldn't be called in preemption when PreFilter returned Skip.
+		// https://github.com/kubernetes/kubernetes/pull/119769
+		return nil, fp.PreFilterStatus
+	}
+
+	state.Write(tokenFilterName, &stateData{})
+
+	if pod.Name == fp.PreFilterTargetPodName {
```
Comment (Huang-Wei) [inline test/integration/scheduler/preemption/preemption_test.go:147]: ditto, I think we're able to get rid of `PreFilterTargetPodName`

File: test/integration/scheduler/preemption/preemption_test.go [hunk 3]
```diff
@@ -274,6 +301,32 @@ func TestPreemption(t *testing.T) {
...
+			pod: initPausePod(&testutils.PausePodConfig{
+				Name:      "preemptor-pod",
+				Namespace: testCtx.NS.Name,
+				Priority:  &highPriority,
+				Resources: &v1.ResourceRequirements{Requests: v1.ResourceList{
+					v1.ResourceCPU:    *resource.NewMilliQuantity(300, resource.DecimalSI),
+					v1.ResourceMemory: *resource.NewQuantity(200, resource.DecimalSI)},
+				},
+			}),
+			preemptedPodIndexes: map[int]struct{}{},
```
Comment (Huang-Wei) [inline test/integration/scheduler/preemption/preemption_test.go:328]: if this is nil, it seems the existing test logic is problematic: (w/o the fix, the test would also pass)

The `else` loop should be employing a "Eventually" semantics; ohterwise it would always pass. In other words, a) the `p` in else block should be obtained from api server and b) we should wait a bit to ensure the preemption doesn't happen. But this is an existing test issue.

```go
// Wait for preemption of pods and make sure the other ones are not preempted.
for i, p := range pods {
	if _, found := test.preemptedPodIndexes[i]; found { ... } else {
		if p.DeletionTimestamp != nil {
			t.Errorf("Didn't expect pod %v to get preempted.", p.Name)
		}
	}
}
```

**Comment by Huang-Wei** [comment]
Given the integration test has been wonky for a while, and the UT should suffice to verify the fix. I'm inclined with a separate PR to polish the integration test: including

1. correct its semantics first (mentioned in https://github.com/kubernetes/kubernetes/pull/119778#discussion_r1286249669)
2. add a new test to cover PreFilter plugin returning `UnschedulableAndUnresolvable`

File: pkg/scheduler/schedule_one.go [hunk 4]
```diff
@@ -437,6 +437,11 @@ func (sched *Scheduler) findNodesThatFitPod(ctx context.Context, fwk framework.F
...
 			return nil, diagnosis, s.AsError()
 		}
+		// All nodes will have the same status. Some non trivial refactoring is
+		// needed to avoid this copy.
+		for _, n := range allNodes {
+			diagnosis.NodeToStatusMap[n.Node().Name] = s
+		}
 		// Record the messages from PreFilter in Diagnosis.PreFilterMsg.
 		msg := s.Message()
 		diagnosis.PreFilterMsg = msg
```
Comment (alculquicondor) [inline pkg/scheduler/schedule_one.go:447]: Could this cause the message to be duplicated?

File: test/integration/scheduler/preemption/preemption_test.go [hunk 5]
```diff
@@ -100,8 +100,11 @@ func waitForNominatedNodeName(cs clientset.Interface, pod *v1.Pod) error {
 const tokenFilterName = "token-filter"
 
 type tokenFilter struct {
```
Comment (alculquicondor) [inline test/integration/scheduler/preemption/preemption_test.go:102]: Can you add a comment describing this plugin?

**Comment by alculquicondor** [comment]
+1 on a quick fix with UTs that can be merged ASAP.

**Comment by alculquicondor** [comment]
The effect here would be that the preemption fails with an error, causing the pod to be re-queued into backoff, instead of unschedulable. Correct?

File: pkg/scheduler/schedule_one.go (hunk 4 above)
Comment (Huang-Wei) [reply pkg/scheduler/schedule_one.go:447]: Good question. @sanposhiho could you double check the event/log is still rendered properly?

File: test/integration/scheduler/preemption/preemption_test.go (hunk 5 above)
Comment (Huang-Wei) [reply test/integration/scheduler/preemption/preemption_test.go:102]: Given it's likely this PR will proceed with UT only, I will add comment in #119769.

**Comment by Huang-Wei** [comment]
> The effect here would be that the preemption fails with an error, causing the pod to be re-queued into backoff, instead of unschedulable. Correct?

In most cases, yes - just unnecessary cycles spent on preemption which should have been avoided.

But, with a plugin returning UnschedulableAndResolvable in PreFilter, and due to the regression, preemption _may_ be able to find a node to host the pod by preempting pods (b/c [dryrun preemption runs Filter only](https://github.com/kubernetes/kubernetes/blob/37a9260d5c59f3daf383e7568a4264784f7be80e/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L189)). In this edge case, it'd cause unexpected disruption to existing pods.

**Comment by alculquicondor** [comment]
Hopefully we can merge before the rc.1 tomorrow

File: pkg/scheduler/schedule_one.go (hunk 4 above)
Comment (sanposhiho) [reply pkg/scheduler/schedule_one.go:448]: It's a good catch. I changed type.go so that we won't make duplicates in the message.

**Comment by sanposhiho** [comment]
@alculquicondor @Huang-Wei 
Sorry, I didn't have much time on this for a few days.

As suggested,
- add changes on type.go so that this PR won't make duplicates in the message.
  - + add test for this.
- remove the integration test change from this PR for now.

PTAL again

**Comment by Huang-Wei** [comment]
/release-note-edit ```release-note Fix a regression to ensure preemption is skipped when a PreFilter plugin returns UnschedulableAndUnresolvable```

**Comment by Huang-Wei** [comment]
@sanposhiho LGTM. Could you polish the release note a bit? like ^^

/lgtm

**Comment by sftim** [comment]
Changelog suggestion
```markdown
Fixed a scheduling bug by ensuring that preemption is skipped when a PreFilter plugin returns `UnschedulableAndUnresolvable`
```
