### PR TITLE
kubeadm: When etcd is listening on all interfaces, set the etcd probe to use loopback

### LINKED ISSUE #882: etcd health probe does not support server --listen-client-urls=https://0.0.0.0:2379
/kind bug
/area etcd
/priority important-soon

**kubeadm version** 1.10.0+

## What happened?
When defining `.Etcd.ExtraArgs["listen-client-urls"]` to configure etcd to listen on all interfaces, the etcdctl probe always times out causing the static pod etcd to eventually crashloop and make the cluster unusuable.

My use-case was exposing etcd for use by calico in a small multi-node cluster.
@mauilion also ran into this and proposed a patch in https://github.com/kubernetes/kubernetes/pull/63408

The workaround is to modify `/etc/kubernetes/manifests/etcd.yaml` after doing a normal kubeadm init:
```
sed -i 's|--listen-client-urls=https://127.0.0.1:2379|--listen-client-urls=https://0.0.0.0:2379|g' /etc/kubernetes/manifests/etcd.yaml
```

## What you expected to happen?
Since etcdctl does not support auto-correcting `0.0.0.0 -> 127.0.0.1` and `::0 -> ::1` we should should set the probe address to the respective loopback addr in the proper format.

## How to reproduce it (as minimally and precisely as possible)?
```bash
kubeadm init --config /dev/stdin << EOF
etcd:
  extraArgs:
    listen-client-urls: https://[::]:2379
EOF
```

#### Anything else we need to know?
~I believe we need to wrap the `net.IPv6loopback.String()` in brackets so that etcdctl can parse the probe address argument.~ From testing, it doesn't appear that etcdctl supports ipv6 endpoints.

### PR DESCRIPTION
**Pull request by stealthybox**
**What this PR does / why we need it**:
When constructing the etcd liveness probe, if the user passes an IPv4 or IPv6 address,
we set the `etcdctl` liveness probe to use the respective IPv4 or IPv6 loopback address for `--endpoints`.

The etcd probe is now always formatted with the https:// protocol and square brackets around the IP (required for IPv6 / compatible with IPv4).

`::1` is now also included in the etcd serving cert SAN by default.

/kind bug
/area kubeadm
/area etcd
/priority important-soon

/sig cluster-lifecycle
/assign @fabriziopandini

**Which issue(s) this PR fixes**
Fixes https://github.com/kubernetes/kubeadm/issues/882

**Special notes for your reviewer**:
```bash
root@vagrant:~# /vagrant/bin/882_kubeadm init --config /dev/stdin << EOF |& tail -n5
etcd:
  extraArgs:
    listen-client-urls: https://[::]:2379
EOF
I0603 19:52:15.666594   24743 tlsbootstrap.go:50] [bootstraptoken] configured RBAC rules to allow Node Bootstrap tokens to post CSRs in order for nodes to get long term certificate credentials
I0603 19:52:15.671424   24743 tlsbootstrap.go:72] [bootstraptoken] configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Node Bootstrap Token
I0603 19:52:15.674607   24743 tlsbootstrap.go:95] [bootstraptoken] configured RBAC rules to allow certificate rotation for all node client certificates in the cluster
I0603 19:52:15.677551   24743 clusterinfo.go:43] [bootstraptoken] creating the "cluster-info" ConfigMap in the "kube-public" namespace
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy
root@vagrant:~# cat /etc/kubernetes/manifests/etcd.yaml |grep -C4 listen
spec:
  containers:
  - command:
    - etcd
    - --listen-client-urls=https://[::]:2379
    - --advertise-client-urls=https://127.0.0.1:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
root@vagrant:~# cat /etc/kubernetes/manifests/etcd.yaml |grep -C4 etcdctl
      exec:
        command:
        - /bin/sh
        - -ec
        - ETCDCTL_API=3 etcdctl --endpoints=https://[::1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt
          --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key
          get foo
      failureThreshold: 8
      initialDelaySeconds: 15
```

**Release note**:
```release-note
kubeadm now configures the etcd liveness probe correctly when etcd is listening on all interfaces
```

### CODE REVIEW

File: cmd/kubeadm/app/util/staticpod/utils.go [hunk 1]
```diff
@@ -254,6 +254,12 @@ func GetProbeAddress(cfg *kubeadmapi.MasterConfiguration, componentName string)
 				}
 				// Return the IP if the URL contains an address instead of a name.
 				if ip := net.ParseIP(parsedURL.Hostname()); ip != nil {
+					// etcdctl doesn't support auto-converting zero addresses into loopback addresses
+					if ip.Equal(net.IPv4zero) || ip.Equal(net.IPv6zero) {
+						return "127.0.0.1"
```
Comment (kad) [inline cmd/kubeadm/app/util/staticpod/utils.go]: if we are in IPv6 configuration, better to use IPv6 loopback.

File: cmd/kubeadm/app/util/etcd/etcd_test.go [hunk 2]
```diff
@@ -84,6 +84,64 @@ spec:
...
+  namespace: kube-system
+spec:
+  containers:
+  - command:
+    - etcd
+    - --advertise-client-urls=https://10.0.5.5:2379
+    - --data-dir=/var/lib/etcd
+    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
+    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
+    - --listen-client-urls=https://[::0:0]:2379
```
Comment (kad) [inline cmd/kubeadm/app/util/etcd/etcd_test.go]: `https://[::]:2379`

**Review by luxas — APPROVED** [review]
Please fix @kad's comments

**Review by timothysc — APPROVED** [review]
/approve 

Please fix comment and @detiber - please weigh in too for lgtm.

File: cmd/kubeadm/app/util/staticpod/utils.go (hunk 1 above)
Comment (stealthybox) [reply cmd/kubeadm/app/util/staticpod/utils.go]: This is intentional.
IPv6 endpoints don't work /w etcdctl.
I couldn't find an upstream bug -- perhaps we should file one.

File: cmd/kubeadm/app/util/etcd/etcd_test.go (hunk 2 above)
Comment (stealthybox) [reply cmd/kubeadm/app/util/etcd/etcd_test.go]: This is also intentional.
It forces us to use `net.ParseIP()` because these are all equivalent:
```
0:0:0:0:0:0:0:0
::0:0:0:0:0
::0:0
::0
::
```

File: cmd/kubeadm/app/util/staticpod/utils.go (hunk 1 above)
Comment (stealthybox) [reply cmd/kubeadm/app/util/staticpod/utils.go]: this is commented in the line below

**Comment by stealthybox** [comment]
Thanks for the review @kad :+1: -- weighed in on the comments.
Please lmk if we need to clarify more in the code.

File: cmd/kubeadm/app/util/staticpod/utils.go (hunk 1 above)
Comment (detiber) [reply cmd/kubeadm/app/util/staticpod/utils.go]: So, I tested this locally and using ::1 appears to work for etcdctl v3.1.12.

When testing, I had originally just modified the etcd manifest for a kubectl-based install, but neglected to update the certificate to add the ipv6 loopback address and was seeing this error: `Error:  grpc: timed out when dialing`. Once I updated the etcd server certificate to include ::1 I was able to use etcdctl with `--endpoints https://[::1]:2379` without an issue.

**Comment by detiber** [comment]
lgtm, but would like to see the use of the ipv6 loopback in the healthcheck when the ipv6 unspecified address is provided.

File: cmd/kubeadm/app/util/staticpod/utils.go (hunk 1 above)
Comment (detiber) [reply cmd/kubeadm/app/util/staticpod/utils.go]: @stealthybox We should probably update `GetEtcdAltNames()` in [pki_helpers.go](https://github.com/kubernetes/kubernetes/blob/16c5804482027393d532c47731a48c012878470d/cmd/kubeadm/app/phases/certs/pkiutil/pki_helpers.go) to add the ipv6 loopback address by default as well.

File: cmd/kubeadm/app/util/etcd/etcd_test.go (hunk 2 above)
Comment (kad) [reply cmd/kubeadm/app/util/etcd/etcd_test.go]: I understand that those are equivalent, but what is the reason behind that particular notation ?

File: cmd/kubeadm/app/util/staticpod/utils.go (hunk 1 above)
Comment (stealthybox) [reply cmd/kubeadm/app/util/staticpod/utils.go]: @detiber Ah, that's totally the issue
I really struggled to determine what was wrong since it seems they removed the `--debug` flag

I'll fix this

File: cmd/kubeadm/app/util/etcd/etcd_test.go (hunk 2 above)
Comment (stealthybox) [reply cmd/kubeadm/app/util/etcd/etcd_test.go]: It prevents code that just does a string match on `::` or `::0` instead of parsing the IP and doing real equivalence.

If you'd like I can expand the test cases, but I figured that if I just add one, I should pick an edge case.

**Comment by dims** [comment]
/priority important-soon

Is this priority ok? please alter if you disagree (need one for the bot)

**Comment by jberkus** [comment]
Also needs a kind/ label

/kind bug

File: cmd/kubeadm/app/util/staticpod/utils.go (hunk 1 above)
Comment (detiber) [reply cmd/kubeadm/app/util/staticpod/utils.go]: @stealthybox I ended up figuring it out by using etcdctl v3.2.x and using the `--debug` flag :rofl:

**Comment by cjwagner** [comment]
There are multiple priority labels on this PR. The milestone maintainer is expecting exactly 1.

**Comment by stealthybox** [comment]
@kad @detiber @dixudx 
- added `::1` to the server SAN
- now returning `::1` in the ipv6 unspecified case
- formatted the probes to always use `https://[%s]:%d` for ipv6 compatibility
- added more tests to cover the v6 parsing cases

PTAL tyvm

**Review by dixudx — APPROVED** [review]
/lgtm
