### PR TITLE
Fix a regression that scheduler always go through all Filter plugins

### LINKED ISSUE #114509: kube-scheduler: Bring back the ability to stop at the first failed filter
#108829 changed the default behavior of scheduler framework's `RunFilterPlugins` - from stopping at the first failed filter to always running all filters. This change breaks Cluster Autoscaler at scale. Cluster Autoscaler imports the scheduler framework to simulate filters on artificial nodes. In a (pretty common) one-pod-per-node scenario, the number of `RunFilterPlugins` calls is ~quadratic wrt. the number of nodes needed for unschedulable pods - it can be a lot of calls. Before #108829, in such scenario the vast majority of `RunFilterPlugins` calls would stop at failing Fit or NodeAffinity filters, and not run the rest of them (e.g. PV-related filters). After the change, every call to `RunFilterPlugins` runs all filters, which completely breaks Cluster Autoscaler at scale (an example scenario of 300 1-pod-per-node pods and 200 node groups takes >10min in 1.24, and ~50s in <1.22).

Can we get the old behavior back? Or re-introduce the config option so that Cluster Autoscaler can set it accordingly? Ideally, we'd also like to get this backported as far as possible (the change was introduced in 1.24).

### PR DESCRIPTION
**Pull request by Huang-Wei**
#### What type of PR is this?

/kind regression
/sig scheduling

#### What this PR does / why we need it:

The scheduler is supposed to stop upon the first Filter failure, but now it functions to go through all Filter plugins without regard with previous Filter failures.

This is a regression introduced in v1.24.0.

#### Which issue(s) this PR fixes:

Fixes #114509

#### Does this PR introduce a user-facing change?

```release-note
Fix a 1.24 regression that the scheduler always goes through all Filter plugins.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/scheduler/framework/runtime/framework.go [hunk 1]
```diff
@@ -730,11 +730,10 @@ func (f *frameworkImpl) RunFilterPlugins(
 			if !pluginStatus.IsUnschedulable() {
 				// Filter plugins are not supposed to return any status other than
 				// Success or Unschedulable.
-				errStatus := framework.AsStatus(fmt.Errorf("running %q filter plugin: %w", pl.Name(), pluginStatus.AsError())).WithFailedPlugin(pl.Name())
-				return map[string]*framework.Status{pl.Name(): errStatus}
+				pluginStatus = framework.AsStatus(fmt.Errorf("running %q filter plugin: %w", pl.Name(), pluginStatus.AsError()))
 			}
 			pluginStatus.SetFailedPlugin(pl.Name())
-			statuses[pl.Name()] = pluginStatus
+			return map[string]*framework.Status{pl.Name(): pluginStatus}
```
Comment (ahg-g) [inline pkg/scheduler/framework/runtime/framework.go:736]: We don't need the `statuses` at all, just return nil at the end.

As a followup, we should remove the map completely, but lets leave it for now to make it easy to backport.

Comment (Huang-Wei) [reply pkg/scheduler/framework/runtime/framework.go:736]: > We don't need the statuses at all, just return nil at the end.

To fix the issue _only_, I'd like to leave all cleanup work in a follow-up. If we return nil, UTs need to be tweaked, but what concerned me more is the downstream users - like the users using v1.24 and suppose it's always returning a concrete map.

Comment (ahg-g) [reply pkg/scheduler/framework/runtime/framework.go:736]: ok, if that breaks the tests, then we can do that in a followup.

Comment (kerthcet) [reply pkg/scheduler/framework/runtime/framework.go:736]: FYI: changing the return type will also require to tweak codes in cluster-autoscaler.
