### PR TITLE
fix data race for Test_Run_Positive_VolumeMountControllerAttachEnabledRace

### LINKED ISSUE #102932: [Flaky unit test] Test_Run_Positive_VolumeMountControllerAttachEnabledRace data race
#### Which jobs are flaking:

`pull-kubernetes-unit`

#### Which test(s) are flaking:

`k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler: Test_Run_Positive_VolumeMountControllerAttachEnabledRace`

#### Testgrid link:

N/A

Triage instead: https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=unit%24&test=Test_Run_Positive_VolumeMountControllerAttachEnabledRace

#### Reason for failure:

Data race.
```
WARNING: DATA RACE
Write at 0x00c000642840 by goroutine 129:
  k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.Test_Run_Positive_VolumeMountControllerAttachEnabledRace.func2()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1838 +0x1e4
  k8s.io/kubernetes/pkg/volume/testing.(*FakeVolume).UnmountDevice()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/testing/testing.go:1101 +0x154
  k8s.io/kubernetes/pkg/volume/util/operationexecutor.(*operationGenerator).GenerateUnmountDeviceFunc.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go:908 +0x41b
  k8s.io/kubernetes/pkg/volume/util/types.(*GeneratedOperations).Run()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/util/types/types.go:79 +0x195
  k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:183 +0x159

Previous read at 0x00c000642840 by goroutine 22:
  k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.Test_Run_Positive_VolumeMountControllerAttachEnabledRace()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1864 +0x15f5
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202

Goroutine 129 (running) created at:
  k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:178 +0x572
  k8s.io/kubernetes/pkg/volume/util/operationexecutor.(*operationExecutor).UnmountDevice()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/volume/util/operationexecutor/operation_executor.go:902 +0x2d3
  k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).unmountDetachDevices()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:302 +0x3e3
  k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).reconcile()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:177 +0x54
  k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).reconciliationLoopFunc.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:151 +0x5b
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x75
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xba
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x114
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x8e
  k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).Run()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:146 +0x2f

Goroutine 22 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1238 +0x5d7
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1511 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1509 +0x612
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1417 +0x3b3
  main.main()
      _testmain.go:73 +0x236
```

#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

specific failure https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102354/pull-kubernetes-unit/1405153747843158016

### PR DESCRIPTION
**Pull request by njuptlzf**
#### What type of PR is this?
/kind flake
/kind failing-test

#### What this PR does / why we need it:
fix the DATA RACE of `generatedVolumeName`.
fix the DATA RACE of `testing.t`.

#### Which issue(s) this PR fixes:

Fixes #102932

#### Special notes for your reviewer:
NONE
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```
I can reproduce it by 
./stress -p 300 ./reconciler.test -test.run "Test_Run_Positive_VolumeMountControllerAttachEnabledRace"

### CODE REVIEW

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go [hunk 1]
```diff
@@ -1834,7 +1835,6 @@ func Test_Run_Positive_VolumeMountControllerAttachEnabledRace(t *testing.T) {
 	fakePlugin.UnmountDeviceHook = func(mountPath string) error {
 		// Act:
 		// 3. While a volume is being unmounted, add it back to the desired state of world
-		t.Logf("UnmountDevice called")
```
Comment (njuptlzf) [inline pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1837]:
```shell
WARNING: DATA RACE
Read at 0x00c000547cc3 by goroutine 85:
  testing.(*common).logDepth()
      /root/tools/go1163/src/testing/testing.go:759 +0x164
  testing.(*common).log()
      /root/tools/go1163/src/testing/testing.go:746 +0x8f
  testing.(*common).Logf()
      /root/tools/go1163/src/testing/testing.go:792 +0x21
  k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.Test_Run_Positive_VolumeMountControllerAttachEnabledRace.func2()
      /root/workspace/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1837 +0xea
  k8s.io/kubernetes/pkg/volume/testing.(*FakeVolume).UnmountDevice()
      /root/workspace/kubernetes/pkg/volume/testing/testing.go:1101 +0x154
  k8s.io/kubernetes/pkg/volume/util/operationexecutor.(*operationGenerator).GenerateUnmountDeviceFunc.func1()
      /root/workspace/kubernetes/pkg/volume/util/operationexecutor/operation_generator.go:936 +0x41b
  k8s.io/kubernetes/pkg/volume/util/types.(*GeneratedOperations).Run()
      /root/workspace/kubernetes/pkg/volume/util/types/types.go:79 +0x195
  k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run.func1()
      /root/workspace/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:183 +0x159

Previous write at 0x00c000547cc3 by main goroutine:
  testing.tRunner.func1()
      /root/tools/go1163/src/testing/testing.go:1180 +0x52c
  testing.tRunner()
      /root/tools/go1163/src/testing/testing.go:1197 +0x22a
  testing.runTests()
      /root/tools/go1163/src/testing/testing.go:1509 +0x612
  testing.(*M).Run()
      /root/tools/go1163/src/testing/testing.go:1417 +0x3b3
  main.main()
      _testmain.go:73 +0x236

Goroutine 85 (running) created at:
  k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run()
      /root/workspace/kubernetes/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:178 +0x572
  k8s.io/kubernetes/pkg/volume/util/operationexecutor.(*operationExecutor).UnmountDevice()
      /root/workspace/kubernetes/pkg/volume/util/operationexecutor/operation_executor.go:905 +0x2d3
  k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).unmountDetachDevices()
      /root/workspace/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:302 +0x3e3
  k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).reconcile()
      /root/workspace/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:177 +0x54
  k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).reconciliationLoopFunc.func1()
      /root/workspace/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:151 +0x5b
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1()
      /root/workspace/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x75
  k8s.io/apimachinery/pkg/util/wait.BackoffUntil()
      /root/workspace/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xba
  k8s.io/apimachinery/pkg/util/wait.JitterUntil()
      /root/workspace/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x114
  k8s.io/apimachinery/pkg/util/wait.Until()
      /root/workspace/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x8e
  k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).Run()
      /root/workspace/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:146 +0x2f
==================
```
fix DATA RACE of `tesing.t` for https://github.com/golang/go/blob/d19a53338fa6272b4fe9c39d66812a79e1464cd2/src/testing/testing.go#L1237-L1238

**Comment by njuptlzf** [comment]
Befor this pr:
```shell
# ./stress -p 300 ./reconciler.test -test.run "Test_Run_Positive_VolumeMountControllerAttachEnabledRace"
2h16m30s: 1089927 runs so far, 73 failures (0.01%)

/tmp# find /tmp/go-stress-20210701T014412* -type f |xargs grep "DATA"
/tmp/go-stress-20210701T014412-033946034:WARNING: DATA RACE
/tmp/go-stress-20210701T014412-213477365:WARNING: DATA RACE
/tmp/go-stress-20210701T014412-400779095:WARNING: DATA RACE
/tmp/go-stress-20210701T014412-512170394:WARNING: DATA RACE
/tmp/go-stress-20210701T014412-809148112:WARNING: DATA RACE
```

After this pr:
```shell
# ./stress -p 300 ./reconciler.test -test.run "Test_Run_Positive_VolumeMountControllerAttachEnabledRace"
1h35m25s: 783657 runs so far, 35 failures (0.00%)

# cat /tmp/go-stress-20210630T172003*|grep DATA
# 
```
Other problems are all because of 
```
E0701 02:37:20.808501   41250 reconciler.go:389] "Cannot get volumes from disk" err="open fake-dir: no such file or directory"

--- FAIL: Test_Run_Positive_VolumeMountControllerAttachEnabledRace (12.52s)
    reconciler_test.go:1837: UnmountDevice called
    reconciler_test.go:1650: Timed out waiting for volume "fake-plugin/fake-device1" to be attached.
FAIL
```
It should be `-p 300 ` which causes the operating system to fail to create a folder, not `DATA RACE`.

**Comment by njuptlzf** [comment]
Does this need to enter the 1.22 milestone? @BenTheElder

**Comment by pacoxu** [comment]
/assign @msau42 @jingxu97
Could you take a look?

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go [hunk 2]
```diff
@@ -1861,5 +1861,5 @@ func Test_Run_Positive_VolumeMountControllerAttachEnabledRace(t *testing.T) {
 	dsw.DeletePodFromVolume(podName, generatedVolumeName)
```
Comment (msau42) [inline pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1861]: Does this need to use the original name too?

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go [hunk 3]
```diff
@@ -1834,7 +1835,6 @@ func Test_Run_Positive_VolumeMountControllerAttachEnabledRace(t *testing.T) {
 	fakePlugin.UnmountDeviceHook = func(mountPath string) error {
 		// Act:
 		// 3. While a volume is being unmounted, add it back to the desired state of world
-		t.Logf("UnmountDevice called")
 		generatedVolumeName, err = dsw.AddPodToVolume(
```
Comment (msau42) [inline pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1838]: I prefer to have the callback use a local variable rather instead of changing the outer function.

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go (hunk 2 above)
Comment (njuptlzf) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1861]: I’m not an expert in volume, and it may take time to investigate.
But there is no data race here in the stress test.

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go (hunk 3 above)
Comment (njuptlzf) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1838]: Okay, I will change it to a local variable later.

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go (hunk 2 above)
Comment (249043822) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1861]: Actually no need, because ` dsw.DeletePodFromVolume(podName, generatedVolumeName)`  runs before `UnmountDeviceHook`,  use generatedVolumeNameCopy maybe still a good change

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go (hunk 3 above)
Comment (njuptlzf) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1840]: Done. No data race. The error and cause are the same as before.

```
# ./stress -p 300 ./reconciler.test -test.run "Test_Run_Positive_VolumeMountControllerAttachEnabledRace" 
35m10s: 280289 runs so far, 16 failures (0.01%)
# grep -r "Cannot get volumes from disk" /tmp/go-stress-20210716T123104* |wc -l
16
# grep -r "DATA" /tmp/go-stress-20210716T123104* |wc -l
0
```

Comment (njuptlzf) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1840]: go vet doesn't allow me to do this, `assignment copies lock value to tCopy: testing.T contains testing.common contains sync.RWMutex`
I will change the log output in the goroutine to klog later.

Comment (msau42) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1840]: Sorry can you clarify, are we able to have this inner function use a local variable for the `generatedVolumeName`?

Comment (njuptlzf) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1840]: I believe this is another solution to this problem. When the `generatedVolumeName ` is not written in the hook but a local variable is used, it is impossible to cause data race for the `generatedVolumeName`.

If you prefer your solution, I can modify it. :-)

File: pkg/kubelet/volumemanager/reconciler/reconciler_test.go [hunk 4]
```diff
@@ -1834,7 +1836,7 @@ func Test_Run_Positive_VolumeMountControllerAttachEnabledRace(t *testing.T) {
 	fakePlugin.UnmountDeviceHook = func(mountPath string) error {
 		// Act:
 		// 3. While a volume is being unmounted, add it back to the desired state of world
-		t.Logf("UnmountDevice called")
+		klog.InfoS("UnmountDevice called")
 		generatedVolumeName, err = dsw.AddPodToVolume(
```
Comment (249043822) [inline pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1840]: use this `generatedVolumeName ` a local variable,  and replace here `dsw.MarkVolumesReportedInUse([]v1.UniqueVolumeName{generatedVolumeName})`

Comment (njuptlzf) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go:1840]: It seems that everyone prefers to use local variables in this  hook, ok...

Comment (njuptlzf) [reply pkg/kubelet/volumemanager/reconciler/reconciler_test.go]: Done.

**Comment by 249043822** [comment]
the fix looks good.

**Comment by msau42** [comment]
/lgtm
/approve

Thank you!

**Comment by BenTheElder** [comment]
Thanks!
