### PR TITLE
kubeadm: update the IsPriviligedUser preflight check on Windows

### LINKED ISSUE #3053: kubeadm.exe fails on Windows Server 2022
BUG REPORT

## Versions

```
kubeadm version: &version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.4", GitCommit:"55019c83b0fd51ef4ced8c29eec2c4847f896e74", GitTreeState:"clean", BuildDate:"2024-04-16T15:05:51Z", GoVersion:"go1.21.9", Compiler:"gc", Platform:"windows/amd64"}
```

**Environment**:

Existing `kubeadm` cluster based on four Linux nodes running Ubuntu 22.04 as VMware VMs. Cluster works fine and everything is updated recently to Kubernetes version 1.29.4.

All nodes have 16 cores and 64 GB memory. They run `containerd` and networking is Calico. We use an external Ubuntu host running HA Proxy as a load balancer for the API server. The four node cluster works fine.

## What happened?

We need support for Windows containers as well, so I'm trying to add a Windows Server 2022 based host to the cluster. And this is where the fun starts. The new Windows host has 16 cores/64 GB as well, and it's running in the same VMware cluster.

I hope (and believe) I've done the preparation of the Win host properly - primarily based on documentation from these sources:

https://k8s-docs.netlify.app/en/docs/setup/production-environment/windows/user-guide-windows-nodes/
https://docs.tigera.io/calico/latest/getting-started/kubernetes/windows-calico/operator

But when I try to run

```
PS C:\Windows\system32> kubeadm join kube-cph.bogus.com:6443 --token ue62yc.ks285c6i4vr4cy1n --discovery-token-ca-cert-hash sha256:8deeb01d3a1a7fbad9d3708405c503d458f32beba5b36294a284cce8d46fbf1f
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR IsPrivilegedUser]: user is not running as administrator
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
```

I am running as a user with Admin permissions _and_ in a PowerShell session with elevated permissions. Every utility we can think of confirms that this is a session with full administrative rights.

If I ignore the error above, preflight will continue and emit a whole cascade of new errors, all Linux related and all showing clear signs that `kubeadm` believes it's running on Linux.

But nevertheless

```
kubeadm version: &version.Info{Major:"1", Minor:"29", GitVersion:"v1.29.4", GitCommit:"55019c83b0fd51ef4ced8c29eec2c4847f896e74", GitTreeState:"clean", BuildDate:"2024-04-16T15:05:51Z", GoVersion:"go1.21.9", Compiler:"gc", Platform:"windows/amd64"}
```

states that platform is "windows/amd64".

## What you expected to happen?

I would expect the node to join the cluster.

## How to reproduce it (as minimally and precisely as possible)?

Create a new Linux based `kubeadm` cluster. Verify that it runs fine. Setup a new Windows Server 2022 host with `containerd`. Try to add it to the cluster using `kubeadm join`.

## Anything else we need to know?

I have asked for help in the Slack channel "Kubernetes/kubeadm", but except for friendly interest I've had no response.

### PR DESCRIPTION
**Pull request by neolit123**
#### What this PR does / why we need it:

    Use GetCurrentProcessToken() instead of checking the groups of a user.

    The Go stdlib way of fetching the groups of an user appears
    to be failing on some Windows setups. Which could be a regression
    in later Go versions, or simply the code does not work on certain
    setups.

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubeadm/issues/3053

#### Does this PR introduce a user-facing change?

```release-note
kubeadm: improve the "IsPriviledgedUser" preflight check to not fail on certain Windows setups.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by neolit123** [comment]
/triage accepted
/priority backlog
/hold

/cc @jsturtevant @marosset 
PTAL for LGTM

**Comment by neolit123** [comment]
> pull-kubernetes-e2e-capz-windows-master — Job failed.   

but i don't see related errors to the preflight check IsPriviligedUser or this PR
 
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/124665/pull-kubernetes-e2e-capz-windows-master/1785959872680955904/artifacts/clusters/capz-conf-m8r2ay/machines/

File: cmd/kubeadm/app/preflight/checks_windows.go [hunk 1]
```diff
@@ -20,34 +20,20 @@ limitations under the License.
...
-	currUser, err := user.Current()
-	if err != nil {
-		return nil, []error{errors.Wrap(err, "cannot get current user")}
-	}
-
-	groupIds, err := currUser.GroupIds()
-	if err != nil {
-		return nil, []error{errors.Wrap(err, "cannot get group IDs for current user")}
+	var hProcessToken windows.Token
+	if err := windows.OpenProcessToken(windows.CurrentProcess(), windows.TOKEN_QUERY, &hProcessToken); err != nil {
```
Comment (jsturtevant) [inline cmd/kubeadm/app/preflight/checks_windows.go:30]: Might be good idea to call  `token.close` on this token or use https://pkg.go.dev/golang.org/x/sys/windows#GetCurrentProcessToken which states it doesn't need to be closed.

**Comment by jsturtevant** [comment]
Test passed the second time, I also saw that the Nodes came online the first time which means kubeadm worked.

File: cmd/kubeadm/app/preflight/checks_windows.go (hunk 1 above)
Comment (neolit123) [reply cmd/kubeadm/app/preflight/checks_windows.go]: great, i didn't notice that function earlier.
updated.
