### PR TITLE
Prevent stranding of partial load balancers resources

### LINKED ISSUE #7753: Target pool leak in GCE project running our jenkins e2e tests
All of our external load balancer tests failed for the better part of a day due to the GCE project that our tests run in hitting its quota for number of target pools. While the target pools have been deleted, the fact that we hit our quota indicates that there must be a leak somewhere, and we need to plug it.

### PR DESCRIPTION
**Pull request by a-robinson**
Will likely fix #7753, although the proof is in the pudding. Explanation of what this is doing in the [comment there](https://github.com/GoogleCloudPlatform/kubernetes/issues/7753#issuecomment-99520786).

@quinton-hoole

### CODE REVIEW

**Comment by mbforbes** [comment]
+cc @smarterclayton (openshift)

**Comment by a-robinson** [comment]
openstack != openshift, Max :)

cc @anguslees for openstack change

**Comment by a-robinson** [comment]
Passes LB e2es consistently

**Comment by mbforbes** [comment]
How embarrassing... that's what I get for attempting to triage during a meeting :-)

**Comment by smarterclayton** [comment]
:) I'd like to pretend like some marketing guy probably didn't anticipate that when the name was chosen, but I know better ;)

----- Original Message -----

File: pkg/cloudprovider/cloud.go [hunk 1]
```diff
@@ -66,7 +66,8 @@ type TCPLoadBalancer interface {
 	CreateTCPLoadBalancer(name, region string, externalIP net.IP, ports []int, hosts []string, affinityType api.AffinityType) (string, error)
 	// UpdateTCPLoadBalancer updates hosts under the specified load balancer.
 	UpdateTCPLoadBalancer(name, region string, hosts []string) error
-	// DeleteTCPLoadBalancer deletes a specified load balancer.
+	// DeleteTCPLoadBalancer deletes a specified load balancer. It should return
+	// nil if the load balancer specified already didn't exist.
 	DeleteTCPLoadBalancer(name, region string) error
```
Comment (quinton-hoole) [inline pkg/cloudprovider/cloud.go]: I'd suggest renaming to something like EnsureTCPLoadBalancerDeleted() to better advertise it's idempotence.

File: pkg/cloudprovider/openstack/openstack.go [hunk 2]
```diff
@@ -625,28 +626,41 @@ func (lb *LoadBalancer) UpdateTCPLoadBalancer(name, region string, hosts []strin
...
-	vip, err := getVipByName(lb.network, name)
-	if err != nil {
-		return err
+	vip, vipErr := getVipByName(lb.network, name)
+	vipExists := true
+	if vipErr != nil {
+		if vipErr != ErrNotFound {
+			return vipErr
+		}
+		vipExists = false
```
Comment (quinton-hoole) [inline pkg/cloudprovider/openstack/openstack.go]: minor nit: I'd prefer a single assignment statement as follows after the if statement, rather than both one before and one inside.  It feels a bit wierd to assign vipExists := true before we actually know whether or not it does.
Instead, you could just do this after the if statement.

vipExists = (vipErr == nil)

File: pkg/cloudprovider/openstack/openstack.go [hunk 3]
```diff
@@ -625,28 +626,41 @@ func (lb *LoadBalancer) UpdateTCPLoadBalancer(name, region string, hosts []strin
...
-		return err
+	pool, poolErr := pools.Get(lb.network, vip.PoolID).Extract()
+	poolExists := true
+	if poolErr != nil {
+		detailedErr, ok := poolErr.(*gophercloud.UnexpectedResponseCodeError)
+		if !ok || detailedErr.Actual != http.StatusNotFound {
+			return poolErr
+		}
+		poolExists = false
 	}
```
Comment (quinton-hoole) [inline pkg/cloudprovider/openstack/openstack.go]: Same nit as above.

File: pkg/cloudprovider/openstack/openstack.go [hunk 4]
```diff
@@ -625,28 +626,41 @@ func (lb *LoadBalancer) UpdateTCPLoadBalancer(name, region string, hosts []strin
...
 
 	// Ignore errors for everything following here
 
-	for _, monId := range pool.MonitorIDs {
-		pools.DisassociateMonitor(lb.network, pool.ID, monId)
+	if poolExists {
+		for _, monId := range pool.MonitorIDs {
+			pools.DisassociateMonitor(lb.network, pool.ID, monId)
+		}
+		pools.Delete(lb.network, pool.ID)
```
Comment (quinton-hoole) [inline pkg/cloudprovider/openstack/openstack.go]: I think that you need to return an error here if the pool deletion fails, so that you will retry again later?
I'm pretty sure that given the eventual consistency of the underlying GCE, a significant number of these pool deletions are going to fail because the monitor disassociation will not have completed under the hood yet.

**Comment by quinton-hoole** [comment]
The main feedback is that you need to retry pool deletion.  The other comments are cosmetic, and won't block merging.

File: pkg/cloudprovider/openstack/openstack.go (hunk 4 above)
Comment (a-robinson) [inline pkg/cloudprovider/openstack/openstack.go]: I'd think so as well, but I don't know why @anguslees originally wrote it this way, so I'm hesitant to change it, given that it looks to have been an intentional choice. It'd be nice if he could chime in, but otherwise I don't want to mess with it given that I have no way of testing it (since I don't have an openstack cluster).

**Comment by a-robinson** [comment]
Rebased and fixed all your comments except the pool error one.

File: pkg/cloudprovider/openstack/openstack.go (hunk 4 above)
Comment (quinton-hoole) [inline pkg/cloudprovider/openstack/openstack.go]: My apologies - I'd overlooked the fact that this was openstack and not GCE.

File: pkg/cloudprovider/openstack/openstack.go [hunk 5]
```diff
@@ -630,31 +631,43 @@ func (lb *LoadBalancer) UpdateTCPLoadBalancer(name, region string, hosts []strin
...
+		return vipErr
 	}
+	vipExists := (vipErr == nil)
 
-	pool, err := pools.Get(lb.network, vip.PoolID).Extract()
-	if err != nil {
-		return err
+	// It's ok if the pool doesn't exist, as we may still need to delete the vip
+	// (although I don't believe the system should ever be in that state).
+	pool, poolErr := pools.Get(lb.network, vip.PoolID).Extract()
```
Comment (anguslees) [inline pkg/cloudprovider/openstack/openstack.go]: If the above returned ErrNotFound, then vip.PoolID will be undefined here.

File: pkg/cloudprovider/openstack/openstack.go (hunk 4 above)
Comment (anguslees) [inline pkg/cloudprovider/openstack/openstack.go]: We need to delete the vip before the pool (otherwise the pool is still in use), and once the vip is deleted GetTCPLoadBalancerExists will indicate "does not exist", and we could potentially recreate another vip with the same name (and a new pool, also with the same name).  My intention (and the current code) was just to leak the pool object during partial failures (the "ignore errors following here" comment could have been clearer).

Now that we're looking at retrying the delete operation, we should definitely disassociate (and delete!) the monitors before attempting to remove the vip (partial failures will lead to missing health checks, but if DeleteLoadBalancer is retried then eventually we might delete everything successfully).  If the disassociate succeeds and the monitor delete fails, we're still leaking the monitor.

The pool is still awkward.  It is possible to lookup the pool by name (rather than ID), but the name is not necessarily unique - if we have already recreated a new LoadBalancer with the same name then we could delete the wrong pool.  With a bit more clarity around how k8s will interpret "Get" and "Create" when "Delete" fails we could assume the pool name is unique and use that to retry deleting the pool.

Less desirable alternatives might include trying to "unwind" and recreate the vip if there were failures deleting the pool (yuck); using OpenStack metadata to associate pool+monitor to original LB (I don't modify metadata anywhere else); or modifying k8s to allow cloud providers to store resource metadata somewhere within k8s (bigger change, but could also lead to performance improvements with object lookup).

File: pkg/cloudprovider/openstack/openstack.go [hunk 6]
```diff
@@ -630,31 +631,43 @@ func (lb *LoadBalancer) UpdateTCPLoadBalancer(name, region string, hosts []strin
...
+		err := vips.Delete(lb.network, vip.ID).ExtractErr()
+		if err != nil {
+			return err
+		}
 	}
 
 	// Ignore errors for everything following here
 
-	for _, monId := range pool.MonitorIDs {
-		pools.DisassociateMonitor(lb.network, pool.ID, monId)
```
Comment (anguslees) [inline pkg/cloudprovider/openstack/openstack.go]: Huh, it looks like I'm not deleting the monitor object at this point - that's a bug.

**Comment by quinton-hoole** [comment]
@a-robinson let me know when you're ready for a re-review.  Assigning to you until then.  It looks like you still need to address some of @anguslees openstack feedback.

Also, it would be good to get someone to test this on openstack before moreging.  Perhaps @anguslees can do that for us?

File: pkg/cloudprovider/openstack/openstack.go (hunk 4 above)
Comment (a-robinson) [inline pkg/cloudprovider/openstack/openstack.go]: Since a couple weeks ago, load balancers have been named using their service's UID, so there will never be name conflicts that enable reusing old pools. Given that, would you be ok with switching over to getting the pool by name? This would make the OpenStack behavior almost identical to the GCE behavior, meaning it'll be less likely to break in weird ways in the future.

In the meantime, I can have this function gracefully return nil if the vip doesn't exist. Once you've switched the pool lookups to be by name, we can go back to trying to delete the pool even if the vip has already been deleted.

How does that sound? I'll open up an issue for doing this work and for cleaning up the monitors that aren't currently being deleted.

**Comment by a-robinson** [comment]
Sorry about the delay, I had some other things float to the top of my priority queue this week. I think we should be fine with getting pools by name rather than ID, but have separated that out into issue #8352.

In the meantime, I've modified this PR to effectively maintain current behavior, just returning nil rather than an error if we attempt to delete a VIP that doesn't exist, paralleling what would happen if we first attempted to get load balancer before deleting it.

File: pkg/cloudprovider/openstack/openstack.go (hunk 4 above)
Comment (anguslees) [inline pkg/cloudprovider/openstack/openstack.go]: > Since a couple weeks ago, load balancers have been named using their service's UID, so there will never be name conflicts that enable reusing old pools.

(thinking)

What about:
- Create() creates pool successfully, fails to create vip, fails to delete new pool during unwind
- Create() now gets called again.

Do we now have a duplicate pool?  Or will Create() call Delete repeatedly in some way before reattempting the Create?

Comment (a-robinson) [inline pkg/cloudprovider/openstack/openstack.go]: The model I've used in the past (and now in the GCE implementation) is to ensure idempotency of each individual step. If we attempt to create a pool and one already exists with that name, we consider it a success and continue to the next step. That way, the service controller can keep retrying until the creation succeeds.

Effectively, we'd just have to check the return code from the pool creation attempt, and if it's an already-exists error, consider it a success.

Comment (anguslees) [inline pkg/cloudprovider/openstack/openstack.go]: (I'm really not trying to be awkward here)

OpenStack resource names are not unique, so we won't get an already-exists error at the underlying level.  We will have to search first, and then create - which is easy enough, but does leave a small race window that could result in duplicate pools.

I'm ok with all this btw.  I think there's still some hairy corner cases involving k8s restarts/etc that will result in odd/leaked resources, but I agree that the proposed change is better than the existing logic.

Comment (a-robinson) [inline pkg/cloudprovider/openstack/openstack.go]: Ah, I didn't realize that about Openstack. It does make this strategy a little less effective. I'm definitely open to alternative implementations, I just want to reduce the likelihood of leaked resources.

So long as having duplicate pools around doesn't break functionality, I'd expect we could also avoid stranding resources even in that rare case by deleting all pools with the UID-derived name when deleting the LB.

**Comment by a-robinson** [comment]
@quinton-hoole, are you alright with merging this?

**Comment by quinton-hoole** [comment]
Apologies for the delay.  I'll review it now.  Has this been tested on openstack yet, as per above comment?

**Comment by a-robinson** [comment]
No, I don't believe it has been tested on openstack, but @anguslees seems to be happy with it?

File: pkg/cloudprovider/openstack/openstack.go [hunk 7]
```diff
@@ -630,31 +631,49 @@ func (lb *LoadBalancer) UpdateTCPLoadBalancer(name, region string, hosts []strin
...
+	// already gone we can't attempt to delete the pool. We should instead look up
+	// the pool by name and attempt to delete it even if the VIP has already been
+	// deleted.
+	vip, vipErr := getVipByName(lb.network, name)
+	if vipErr == ErrNotFound {
+		return nil
+	} else if vipErr != nil {
+		return vipErr
+	}
+	vipExists := (vipErr == nil)
```
Comment (quinton-hoole) [inline pkg/cloudprovider/openstack/openstack.go]: I don't think that it's possible to get here without vipErr being nil, in which case vipExists is superfluous, right?

File: pkg/cloudprovider/openstack/openstack.go [hunk 8]
```diff
@@ -630,31 +631,49 @@ func (lb *LoadBalancer) UpdateTCPLoadBalancer(name, region string, hosts []strin
...
+			return poolErr
+		}
 	}
+	poolExists := (poolErr == nil)
 
 	// Have to delete VIP before pool can be deleted
-	err = vips.Delete(lb.network, vip.ID).ExtractErr()
-	if err != nil {
-		return err
+	if vipExists {
```
Comment (quinton-hoole) [inline pkg/cloudprovider/openstack/openstack.go]: See above.  Unless I'm confused, this change doesn't do anything, and just complicates the code.  But I have flu, so feel free to correct me if my head is confused.

File: pkg/cloudprovider/openstack/openstack.go [hunk 9]
```diff
@@ -630,31 +631,49 @@ func (lb *LoadBalancer) UpdateTCPLoadBalancer(name, region string, hosts []strin
...
+		}
 	}
 
 	// Ignore errors for everything following here
 
-	for _, monId := range pool.MonitorIDs {
-		pools.DisassociateMonitor(lb.network, pool.ID, monId)
+	if poolExists {
+		for _, monId := range pool.MonitorIDs {
+			// TODO: Delete the monitor, don't just disassociate it.
```
Comment (quinton-hoole) [inline pkg/cloudprovider/openstack/openstack.go]: If you're not going to fix this TODO in the current PR, best open a issue to track fixing it in a separate PR, lest it get lost.

**Comment by quinton-hoole** [comment]
Just two minor things left to check/fix, as far as I can see.

File: pkg/cloudprovider/openstack/openstack.go (hunk 9 above)
Comment (a-robinson) [inline pkg/cloudprovider/openstack/openstack.go]: It's included in https://github.com/GoogleCloudPlatform/kubernetes/issues/8352. I suppose I hadn't added the issue number to the TODO, though.

File: pkg/cloudprovider/openstack/openstack.go (hunk 8 above)
Comment (a-robinson) [inline pkg/cloudprovider/openstack/openstack.go]: #8352 will involve re-adding it back in almost immediately, so yes, this is dead code, but it'll be needed (hopefully) very soon. I thought leaving it in would make things easier on @anguslees, but I'll pull it out for him to add back (and add appropriate TODOs) so we can get this in.

**Comment by a-robinson** [comment]
Re-pushed the code with the vipExists logic torn out and TODOs clarified with the openstack issue number.

**Comment by quinton-hoole** [comment]
Have you performed a few runs of the services e2e tests against this code to confirm that:

1. They pass?
2. They don't leak GCE load balancer resources?

**Comment by quinton-hoole** [comment]
Can anyone explain why the v1.0 candidate milestone tag was removed from this one?  I don't think that we can launch without this, as all clusters that employ external load balancers on GCE will stop working properly within a few days, like our current soak test clusters.

**Comment by quinton-hoole** [comment]
Tentatively re-adding v1.0-candidate milestone until I understand why it's not v1.0 worthy.
