### PR TITLE
Fix [Failing Test] Security Context SupplementalGroupsPolicy [LinuxOnly] [Feature:SupplementalGroupsPolicy]

### LINKED ISSUE #137859: [Failing Test] Security Context SupplementalGroupsPolicy [LinuxOnly] [Feature:SupplementalGroupsPolicy]
### Failure cluster [b232bbd1aa2f0eafa12c](https://go.k8s.io/triage#b232bbd1aa2f0eafa12c)

Security Context SupplementalGroupsPolicy [LinuxOnly] [Feature:SupplementalGroupsPolicy]  when SupplementalGroupsPolicy was set to Merge in PodSpec when the container's primary UID belongs to some groups in the image it should add SupplementalGroups to them [LinuxOnly]

##### Error text:
```
[FAILED] Timed out after 60.001s.
Custom matcher failed for:
    <*v1.Pod | 0x10cac4bd6008>: 
        metadata:
          annotations:
            owner.test: k8s.io/kubernetes/test/e2e/common/node/security_context.go:947
          creationTimestamp: "2026-03-14T20:39:07Z"
          generation: 1
          labels:
            name: sppl-grp-plcy-c5d470fa-df08-4ba3-8dc3-6c6b933f35da
          managedFields:
          - apiVersion: v1
            fieldsType: FieldsV1
            fieldsV1:
              f:metadata:
                f:annotations:
                  .: {}
                  f:owner.test: {}
                f:labels:
                  .: {}
                  f:name: {}
              f:spec:
                f:containers:
                  k:{"name":"test-container"}:
                    .: {}
                    f:command: {}
                    f:image: {}
                    f:imagePullPolicy: {}
                    f:name: {}
                    f:resources: {}
                    f:terminationMessagePath: {}
                    f:terminationMessagePolicy: {}
                f:dnsPolicy: {}
                f:enableServiceLinks: {}
                f:nodeName: {}
                f:restartPolicy: {}
                f:schedulerName: {}
                f:securityContext:
                  .: {}
                  f:runAsUser: {}
                  f:supplementalGroups: {}
                f:terminationGracePeriodSeconds: {}
            manager: e2e_node.test
            op
```
#### Recent failures:
[3/18/2026, 12:29:40 PM ci-cos-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cos-containerd-node-e2e-features/2034306133916651520)
[3/18/2026, 11:28:49 AM ci-cos-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cos-containerd-node-e2e-features/2034290783070195712)
[3/18/2026, 10:28:00 AM ci-cos-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cos-containerd-node-e2e-features/2034275431024168960)
[3/18/2026, 9:26:43 AM ci-cos-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cos-containerd-node-e2e-features/2034260079988969472)
[3/18/2026, 8:25:40 AM ci-cos-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-cos-containerd-node-e2e-features/2034244728714694656)

/kind failing-test

/sig node

### PR DESCRIPTION
**Pull request by yangjunmyfm192085**
#### What type of PR is this?
/kind cleanup

#### Which issue(s) this PR is related to:

Fix #137859
#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: test/e2e/common/node/security_context.go [hunk 1]
```diff
@@ -822,6 +823,32 @@ var _ = SIGDescribe("Security Context", func() {
 	})
 
 	f.Context("SupplementalGroupsPolicy [LinuxOnly]", feature.SupplementalGroupsPolicy, func() {
+		requireContainerdVersion := func(ctx context.Context, givenVersion string) {
```
Comment (everpeace) [inline test/e2e/common/node/security_context.go]: I feel this check is too CRI runtime-specific (how about other CRI runtime?).

Kubelet does export `Node.Status.Features.SupplementalGroupsPolicy: true` field if the feature is available on the node. 

So, I would recommend to see this field to check the feature is available or not. (I removed the check actually here: https://github.com/kubernetes/kubernetes/pull/135088/changes#diff-a70b4798f11d121ae3b63a3378298d17e11ca892f4e83d8bfe77e3512c623289L795)

**Review by everpeace — COMMENTED** [review]
Thank you for the fix! I commented about how to check this feature's availability. PTAL.

File: test/e2e/common/node/security_context.go (hunk 1 above)
Comment (yangjunmyfm192085) [reply test/e2e/common/node/security_context.go]: Thanks for reminding me, I'll take a look.

File: test/e2e/common/node/security_context.go [hunk 2]
```diff
@@ -930,6 +942,9 @@ var _ = SIGDescribe("Security Context", func() {
 			ginkgo.When("if the container's primary UID belongs to some groups in the image", func() {
 				var pod *v1.Pod
 				ginkgo.BeforeEach(func(ctx context.Context) {
+					if !nodeSupportsSupplementalGroupsPolicy(ctx, f, pod.Spec.NodeName) {
+						e2eskipper.Skipf("scheduled node does not support SupplementalGroupsPolicy")
+					}
 					ginkgo.By("creating a pod", func() {
 						pod = e2epod.NewPodClient(f).CreateSync(ctx, mkPod(ptr.To(v1.SupplementalGroupsPolicyMerge)))
 					})
```
Comment (everpeace) [inline test/e2e/common/node/security_context.go]: pod creation is AFTER this check. So, `pod.Spec.NodeName` will always be empty.

So, I think 

- create pod first,
- it eventually asserts the pod is bound to the node.
- Then, we should check the feature availability.

**Review by everpeace — COMMENTED** [review]
@yangjunmyfm192085 
Thanks for the fix. But, I still see a timing problem. See my comment for detail 🙇

File: test/e2e/common/node/security_context.go (hunk 2 above)
Comment (yangjunmyfm192085) [reply test/e2e/common/node/security_context.go]: @everpeace Sorry for the oversight — my bad. 
I didn't notice that the `nodeSupportsSupplementalGroupsPolicy` check had already been moved before pod creation.
I've corrected it accordingly in the latest update.
Could you please take another look when you have time? Thanks again for pointing this out!

File: test/e2e/common/node/security_context.go [hunk 3]
```diff
@@ -959,6 +977,9 @@ var _ = SIGDescribe("Security Context", func() {
 					ginkgo.By("creating a pod", func() {
 						pod = e2epod.NewPodClient(f).CreateSync(ctx, mkPod(ptr.To(v1.SupplementalGroupsPolicyStrict)))
 					})
+					if !nodeSupportsSupplementalGroupsPolicy(ctx, f, pod.Spec.NodeName) {
+						e2eskipper.Skipf("scheduled node does not support SupplementalGroupsPolicy")
+					}
```
Comment (everpeace) [inline test/e2e/common/node/security_context.go:986]: We should have a caution in `SupplementalGroupsPolicy: Strict` case.

[`CreateSync` includes `WaitTimeoutForPodReadyInNamespace` internally](https://github.com/kubernetes/kubernetes/blob/e44526d045e66f6707005e9ee047be7327a71ab8/test/e2e/framework/pod/pod_client.go#L152). If a pod specifies `SupplementalGroupsPolicy: Strict` and the bound node does not support the feature, kubelet rejects creating the pod. (ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#implementations-supplementalgroupspolicy)

Thus, this test case will always fail in `pod = ...` line because this case sets `SupplementalGroupsPolicy: Strict` and the node does not support it.

So, I think we should change how to create and assert pod status as I did before:
https://github.com/kubernetes/kubernetes/pull/135088/changes#diff-a70b4798f11d121ae3b63a3378298d17e11ca892f4e83d8bfe77e3512c623289L961-L965

**Review by everpeace — COMMENTED** [review]
I commented in `SupplementalGroupsPolicy: Strict` case. PTAL.  Could you run `ci-cos-containerd-node-e2e-features` manually and make sure the test passed??

**Comment by yangjunmyfm192085** [comment]
> /test pull-cos-containerd-e2e-ubuntu-gce

@everpeace Is this test?

**Review by everpeace — COMMENTED** [review]
@yangjunmyfm192085 Thanks! LGTM!
/lgtm

**Review by SergeyKanzhelev — APPROVED** [review]
/lgtm
/approve
