### PR TITLE
kubeadm: fallback to a known etcd version if an unknown k8s version is passed

### LINKED ISSUE #2034: fallback to a known etcd version if an unknown k8s version is passed
during etcd upgrade kubeadm can fail with:
> unsupported or unknown Kubernetes version(1.19.0-alpha.0)

this can happen if a k8s version is passed that kubeadm still does not know about.
the errors originates for a map check, where a k8s version is mapped to an etcd version.

a desired fix here is convert this into a warning and fallback to the last known etcd version.
e.g. if k8s version is 1.19, but there is no etcd mapping for this version use the etcd version for 1.18.

example of the failure:
https://github.com/kubernetes/kubernetes/issues/88336

### PR DESCRIPTION
**Pull request by SataQiu**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
kubeadm: fallback to a known etcd version if an unknown k8s version is passed

**Which issue(s) this PR fixes**:

Fixes kubernetes/kubeadm#2034

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
kubeadm: upgrade supports fallback to the nearest known etcd version if an unknown k8s version is passed
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
thanks @SataQiu i will have a look later / when i can.

**Comment by neolit123** [comment]
minor typo in the release note:
> ...if a unknown k8s version is passed

File: cmd/kubeadm/app/phases/upgrade/staticpods.go [hunk 1]
```diff
@@ -283,7 +283,12 @@ func performEtcdStaticPodUpgrade(certsRenewMgr *renewal.Manager, client clientse
 	// Need to check currently used version and version from constants, if differs then upgrade
 	desiredEtcdVersion, err := constants.EtcdSupportedVersion(cfg.KubernetesVersion)
 	if err != nil {
-		return true, errors.Wrap(err, "failed to retrieve an etcd version for the target Kubernetes version")
+		fmt.Printf("[upgrade/etcd] WARNING: No recommended etcd for requested Kubernetes version (%s)\n", cfg.KubernetesVersion)
+		desiredEtcdVersion, err = constants.EtcdNearestVersion(cfg.KubernetesVersion)
+		if err != nil {
+			return true, errors.Wrap(err, "failed to retrieve an etcd version for the target Kubernetes version")
+		}
+		fmt.Printf("[upgrade/etcd] WARNING: Fallback to the nearest etcd (%s)\n", desiredEtcdVersion)
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/upgrade/staticpods.go]: `...nearest etcd version (%s)`

File: cmd/kubeadm/app/phases/upgrade/compute.go [hunk 2]
```diff
@@ -303,7 +303,11 @@ func getSuggestedEtcdVersion(kubernetesVersion string) string {
 	etcdVersion, err := kubeadmconstants.EtcdSupportedVersion(kubernetesVersion)
 	if err != nil {
 		fmt.Printf("[upgrade/versions] WARNING: No recommended etcd for requested Kubernetes version (%s)\n", kubernetesVersion)
-		return "N/A"
+		etcdVersion, err = kubeadmconstants.EtcdNearestVersion(kubernetesVersion)
+		if err != nil {
+			return "N/A"
+		}
+		fmt.Printf("[upgrade/versions] WARNING: Fallback to the nearest etcd (%s)\n", etcdVersion)
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/upgrade/compute.go]: `...nearest etcd version (%s)\n`

File: cmd/kubeadm/app/constants/constants_test.go [hunk 3]
```diff
@@ -198,6 +198,61 @@ func TestEtcdSupportedVersion(t *testing.T) {
 	}
 }
 
+func TestEtcdNearestVersion(t *testing.T) {
+	var tests = []struct {
+		kubernetesVersion string
+		expectedVersion   *version.Version
+		expectedError     error
```
Comment (neolit123) [inline cmd/kubeadm/app/constants/constants_test.go]: there should be at least one `expectedError != nil` case.

File: cmd/kubeadm/app/constants/constants_test.go [hunk 4]
```diff
@@ -198,6 +198,61 @@ func TestEtcdSupportedVersion(t *testing.T) {
...
+		},
+		{
+			kubernetesVersion: CurrentKubernetesVersion.String(),
+			expectedVersion:   version.MustParseSemantic(SupportedEtcdVersion[uint8(CurrentKubernetesVersion.Minor())]),
+			expectedError:     nil,
+		},
+	}
+	for _, rt := range tests {
+		t.Run(rt.kubernetesVersion, func(t *testing.T) {
+			actualVersion, actualError := EtcdNearestVersion(rt.kubernetesVersion)
```
Comment (neolit123) [inline cmd/kubeadm/app/constants/constants_test.go]: i think we can avoid checking the .Error() string output of the expected error.

the checks here can be:
```
if (actualError != nil) != (rt.expectedError != nil) {
	t.Fatalf("expected error %v, got %v", rt.expectedError, actualError)
}
if actualError != nil {
	return
}
if actualVersion.String() != rt.expectedVersion.String() {
	t.Errorf("expected version %s, got %s", rt.expectedVersion.String(), actionVersion.String())
}
```

File: cmd/kubeadm/app/constants/constants.go [hunk 5]
```diff
@@ -452,6 +452,39 @@ func EtcdSupportedVersion(versionString string) (*version.Version, error) {
...
+// EtcdNearestVersion returns the nearest version to officially supported version of etcd for a specific Kubernetes release
+// If the distance is same, it returns the newer version
+func EtcdNearestVersion(versionString string) (*version.Version, error) {
+	kubernetesVersion, err := version.ParseSemantic(versionString)
+	if err != nil {
+		return nil, err
+	}
+	kubernetesMinorVersion := uint8(kubernetesVersion.Minor())
+
+	key, distance, etcdNearestStringVersion := uint8(0), ^uint8(0), ""
```
Comment (neolit123) [inline cmd/kubeadm/app/constants/constants.go]: instead of calculating the distance between "versionString" and the desired version, can we just assume that the user wants a version older or newer than what we have in the map, because EtcdSupportedVersion() already failed.

```
EtcdNearestVersion(versionString string) (*version.Version, error) {
	kubernetesVersion, err := version.ParseSemantic(versionString)
	if err != nil {
		return nil, err
	}

	min, max := ^uint8(0), uint8(0)
	for k := range SupportedEtcdVersion {
		if k < min {
			min = k
		} else if k > max {
			max = k
		}
	}
	
	var nearest string	
	desiredVersion := uint8(kubernetesVersion.Minor())
	if desiredVersion < min {
		nearest = SupportedEtcdVersion[min]
	}
	nearest = SupportedEtcdVersion[max]

	etcdNearestVersion, err := version.ParseSemantic(nearest)
	if err != nil {
		return nil, err
	}
	return etcdNearestVersion, nil
}
```

File: cmd/kubeadm/app/constants/constants.go [hunk 6]
```diff
@@ -452,6 +452,39 @@ func EtcdSupportedVersion(versionString string) (*version.Version, error) {
 	return nil, errors.Errorf("unsupported or unknown Kubernetes version(%v)", kubernetesVersion)
 }
 
+// EtcdNearestVersion returns the nearest version to officially supported version of etcd for a specific Kubernetes release
+// If the distance is same, it returns the newer version
+func EtcdNearestVersion(versionString string) (*version.Version, error) {
```
Comment (neolit123) [inline cmd/kubeadm/app/constants/constants.go]: i'm fine with keeping this as a separate function for easier unit testing.

File: cmd/kubeadm/app/constants/constants_test.go [hunk 7]
```diff
@@ -198,6 +198,61 @@ func TestEtcdSupportedVersion(t *testing.T) {
...
 
+func TestEtcdNearestVersion(t *testing.T) {
+	var tests = []struct {
+		kubernetesVersion string
+		expectedVersion   *version.Version
+		expectedError     error
+	}{
+		{
+			kubernetesVersion: "1.10.0",
+			expectedVersion:   version.MustParseSemantic("3.2.24"),
```
Comment (neolit123) [inline cmd/kubeadm/app/constants/constants_test.go]: sadly, this will fail once we update the etcd struct.
the idea is to not make unit tests depend on version pinning.

one solution here is to make EtcdNearestVersion accept a source `map[uint8]string` map.

**Comment by SataQiu** [comment]
> minor typo in the release note:
> 
> > ...if a unknown k8s version is passed

Thank you for your careful review @Neolit123 !
Not sure what the correct grammar is. But I checked it on [https://www.nounplus.net/grammarcheck/](https://www.nounplus.net/grammarcheck/), its suggestion is `an unknown` 😟 

图片

File: cmd/kubeadm/app/constants/constants.go (hunk 5 above)
Comment (SataQiu) [reply cmd/kubeadm/app/constants/constants.go]: Your suggestion is very good. I have refactored this part of the code :)

**Comment by neolit123** [comment]
> Thank you for your careful review @neolit123 !
Not sure what the correct grammar is. But I checked it on https://www.nounplus.net/grammarcheck/, its suggestion is an unknown worried

huh, googling around for grammar suggests you are correct, because it does start with a vowel sound in prononciation - `uhn-nohn`.

it is however said `a university` instead of `an university` (`yoo-nuh-vur-si-tee`) and `y` is considered as a vowel only sometimes.
https://www.grammar.com/a-vs-an-when-to-use/

English is fun...

File: cmd/kubeadm/app/constants/constants_test.go [hunk 8]
```diff
@@ -149,50 +148,62 @@ func TestAddSelfHostedPrefix(t *testing.T) {
...
+		15: "3.3.10",
+		16: "3.3.17-0",
+		17: "3.4.3-0",
+		18: "3.4.3-0",
+	}
 	var tests = []struct {
 		kubernetesVersion string
 		expectedVersion   *version.Version
+		expectedWarning   error
 		expectedError     error
```
Comment (neolit123) [inline cmd/kubeadm/app/constants/constants_test.go]: i think we should just have `bool for `expectedWarning` and `expectedError`  here.
no need to verify the error types.

e.g.
```
if (actualWarning != nil) != rt.expectedWarning {
...
}
```

File: cmd/kubeadm/app/phases/upgrade/compute.go [hunk 9]
```diff
@@ -300,10 +300,13 @@ func minorUpgradePossibleWithPatchRelease(stableVersion, patchVersion *versionut
 }
 
 func getSuggestedEtcdVersion(kubernetesVersion string) string {
-	etcdVersion, err := kubeadmconstants.EtcdSupportedVersion(kubernetesVersion)
+	etcdVersion, warning, err := kubeadmconstants.EtcdSupportedVersion(kubeadmconstants.SupportedEtcdVersion, kubernetesVersion)
 	if err != nil {
 		fmt.Printf("[upgrade/versions] WARNING: No recommended etcd for requested Kubernetes version (%s)\n", kubernetesVersion)
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/upgrade/compute.go]: i think the pattern should be:
```
	etcdVersion, warning, err := constants.EtcdSupportedVersion(constants.SupportedEtcdVersion, cfg.KubernetesVersion)
	if err != nil {
		return true, errors.Wrap(err, "failed to retrieve an etcd version for the target Kubernetes version")
	}
	if warning != nil {
		fmt.Printf("[upgrade/etcd] %s\n", warning)
	}
```

[1]

File: cmd/kubeadm/app/images/images.go [hunk 10]
```diff
@@ -73,9 +73,12 @@ func GetEtcdImage(cfg *kubeadmapi.ClusterConfiguration) string {
 	}
 	// Etcd uses an imageTag that corresponds to the etcd version matching the Kubernetes version
 	etcdImageTag := constants.DefaultEtcdVersion
-	etcdVersion, err := constants.EtcdSupportedVersion(cfg.KubernetesVersion)
+	etcdVersion, warning, err := constants.EtcdSupportedVersion(constants.SupportedEtcdVersion, cfg.KubernetesVersion)
 	if err == nil {
 		etcdImageTag = etcdVersion.String()
+		if warning != nil {
+			klog.Warningln(warning)
+		}
```
Comment (neolit123) [inline cmd/kubeadm/app/images/images.go]: [1]

File: cmd/kubeadm/app/constants/constants_test.go [hunk 11]
```diff
@@ -149,50 +148,62 @@ func TestAddSelfHostedPrefix(t *testing.T) {
...
-				}
+			actualVersion, actualWarning, actualError := EtcdSupportedVersion(supportedEtcdVersion, rt.kubernetesVersion)
+			if (actualError != nil) != (rt.expectedError != nil) {
+				t.Fatalf("expected error %v, got %v", rt.expectedError != nil, actualError != nil)
+			}
+			if (actualWarning != nil) != (rt.expectedWarning != nil) {
+				t.Fatalf("expected warning %v, got %v", rt.expectedWarning != nil, actualWarning != nil)
+			}
+			if actualError == nil && actualVersion.String() != rt.expectedVersion.String() {
+				t.Errorf("expected version %s, got %s", rt.expectedVersion.String(), actualVersion.String())
```
Comment (neolit123) [inline cmd/kubeadm/app/constants/constants_test.go]: example given in [2]

File: cmd/kubeadm/app/constants/constants.go [hunk 12]
```diff
@@ -435,21 +435,50 @@ var (
...
+			return nil, nil, err
 		}
-		return etcdVersion, nil
+		return etcdVersion, nil, nil
 	}
-	return nil, errors.Errorf("unsupported or unknown Kubernetes version(%v)", kubernetesVersion)
+
+	// fallback to the nearest version
+	min, minEtcdStringVersion, max, maxEtcdStringVersion := ^uint8(0), "", uint8(0), ""
+	for k, v := range supportedEtcdVersion {
```
Comment (neolit123) [inline cmd/kubeadm/app/constants/constants.go]: see my example, you can find a matching version using the loop.
[3]

File: cmd/kubeadm/app/constants/constants.go [hunk 13]
```diff
@@ -435,21 +435,50 @@ var (
...
 	if err != nil {
-		return nil, err
+		return nil, nil, err
 	}
+	desiredVersion, etcdStringVersion := uint8(kubernetesVersion.Minor()), ""
 
-	if etcdStringVersion, ok := SupportedEtcdVersion[uint8(kubernetesVersion.Minor())]; ok {
-		etcdVersion, err := version.ParseSemantic(etcdStringVersion)
+	// found officially supported version in the list
+	if etcdStringVersion, ok := supportedEtcdVersion[desiredVersion]; ok {
```
Comment (neolit123) [inline cmd/kubeadm/app/constants/constants.go]: [3]

File: cmd/kubeadm/app/phases/upgrade/compute.go [hunk 14]
```diff
@@ -299,11 +317,13 @@ func minorUpgradePossibleWithPatchRelease(stableVersion, patchVersion *versionut
...
 }
 
-func getSuggestedEtcdVersion(kubernetesVersion string) string {
-	etcdVersion, err := kubeadmconstants.EtcdSupportedVersion(kubernetesVersion)
+func getSuggestedEtcdVersion(kubernetesVersion string) (string, error) {
+	etcdVersion, warning, err := kubeadmconstants.EtcdSupportedVersion(kubeadmconstants.SupportedEtcdVersion, kubernetesVersion)
 	if err != nil {
-		fmt.Printf("[upgrade/versions] WARNING: No recommended etcd for requested Kubernetes version (%s)\n", kubernetesVersion)
-		return "N/A"
+		return "N/A", errors.Wrap(err, "Couldn't retrieve an etcd version for the target Kubernetes version")
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/upgrade/compute.go]: errors should start with lowercase

File: cmd/kubeadm/app/constants/constants.go [hunk 15]
```diff
@@ -435,21 +436,45 @@ var (
...
+
+	if len(etcdStringVersion) == 0 {
+		if desiredVersion < min {
+			etcdStringVersion = supportedEtcdVersion[min]
+		}
+		if desiredVersion > max {
+			etcdStringVersion = supportedEtcdVersion[max]
 		}
-		return etcdVersion, nil
+		warning = fmt.Errorf("WARNING: Couldn't find officially supported version of etcd for Kubernetes %s, falling back to the nearest etcd version (%s)",
```
Comment (neolit123) [inline cmd/kubeadm/app/constants/constants.go]: `WARNING: Couldn't...` -> `could not...`

File: cmd/kubeadm/app/phases/upgrade/compute.go [hunk 16]
```diff
@@ -299,11 +317,13 @@ func minorUpgradePossibleWithPatchRelease(stableVersion, patchVersion *versionut
...
+	}
+	if warning != nil {
+		fmt.Printf("[upgrade/versions] %v\n", warning)
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/upgrade/compute.go]: i think we should use `klog.Warningln(...)` consistently for printing the warning.

File: cmd/kubeadm/app/phases/upgrade/staticpods.go [hunk 17]
```diff
@@ -281,10 +282,13 @@ func performEtcdStaticPodUpgrade(certsRenewMgr *renewal.Manager, client clientse
 	}
 
 	// Need to check currently used version and version from constants, if differs then upgrade
-	desiredEtcdVersion, err := constants.EtcdSupportedVersion(cfg.KubernetesVersion)
+	desiredEtcdVersion, warning, err := constants.EtcdSupportedVersion(constants.SupportedEtcdVersion, cfg.KubernetesVersion)
 	if err != nil {
 		return true, errors.Wrap(err, "failed to retrieve an etcd version for the target Kubernetes version")
 	}
+	if warning != nil {
+		fmt.Printf("[upgrade/etcd] %v\n", warning)
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/upgrade/staticpods.go]: [3]

**Comment by neolit123** [comment]
@SataQiu please mark the old comments before https://github.com/kubernetes/kubernetes/pull/88373#pullrequestreview-363041300 as resolved.

**Comment by SataQiu** [comment]
> @SataQiu please mark the old comments before [#88373 (review)](https://github.com/kubernetes/kubernetes/pull/88373#pullrequestreview-363041300) as resolved.

Thanks for your reminder! I have marked them. :)

File: cmd/kubeadm/app/phases/upgrade/compute.go [hunk 18]
```diff
@@ -299,11 +318,13 @@ func minorUpgradePossibleWithPatchRelease(stableVersion, patchVersion *versionut
...
 }
 
-func getSuggestedEtcdVersion(kubernetesVersion string) string {
-	etcdVersion, err := kubeadmconstants.EtcdSupportedVersion(kubernetesVersion)
+func getSuggestedEtcdVersion(kubernetesVersion string) (string, error) {
+	etcdVersion, warning, err := kubeadmconstants.EtcdSupportedVersion(kubeadmconstants.SupportedEtcdVersion, kubernetesVersion)
 	if err != nil {
-		fmt.Printf("[upgrade/versions] WARNING: No recommended etcd for requested Kubernetes version (%s)\n", kubernetesVersion)
-		return "N/A"
+		return "N/A", errors.Wrap(err, "could not retrieve an etcd version for the target Kubernetes version")
```
Comment (neolit123) [inline cmd/kubeadm/app/phases/upgrade/compute.go]: can we keep getSuggestedEtcdVersion to return only a string like it was before?

```
func getSuggestedEtcdVersion(kubernetesVersion string) (string, error) {
	etcdVersion, warning, err := kubeadmconstants.EtcdSupportedVersion(kubeadmconstants.SupportedEtcdVersion, kubernetesVersion)
	if err != nil {
		klog.Warningf("[upgrade/versions] could not retrieve an etcd version for the target Kubernetes version: %v", err)
		return "N/A"
	}
	if warning != nil {
		klog.Warningf("[upgrade/versions] %v", warning)
	}
	return etcdVersion.String()
}
```

this will keep GetAvailableUpgrades simple.

**Comment by neolit123** [comment]
this seems good to me. thanks.

/lgtm
/approve
