### PR TITLE
fix: allow job startTime updates on resume from suspended state

### LINKED ISSUE #134521: when resuming a suspended kubernetes job, unhandled error of job controller occured in the log of kube-controller-manager pod
### What happened?

try to resume a suspended job, there are repeated error logs:
error="syncing job: tracking status: adding  uncounted pods to status: Job.batch is invalid: status.startTime: Required value: startTime cannot be removed for unsuspended job"

Image

 as shown in the attached image.

### What did you expect to happen?

no error occur in log of  kube-controller-manager pod

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a kubernetes job. The job starts to run.
2. Suspend the job. The job is suspended.
kubectl patch job/myjob --type=strategic --patch '{"spec":{"suspend":true}}'
3. Resume the job.
kubectl patch job/myjob --type=strategic --patch '{"spec":{"suspend":false}}'

The commands to suspend / resume job are from the offical doc：https://kubernetes.io/docs/concepts/workloads/controllers/job/#suspending-a-job

### Anything else we need to know?

https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/batch/validation/validation.go#L699-L705
Doubt if it is caused by !ptr.Equal(oldJob.Status.StartTime, job.Status.StartTime).
when resume the job, job.Status.StartTime becomes current time which is differenent from oldJob.Status.StartTime although job.Status.startTime is not nil.
According to audit.log of API Server, when resume job, job controller request to change status.startTime to '2025-10-10T08:40:05Z' while the previous status.startTime returned by API Server is '2025-10-10T02:10:06Z'

### Kubernetes version

<details>

```console
$ kubectl version

Client Version: v1.32.1
Kustomize Version: v5.5.0
Server Version: 1.32.2
```

</details>

### Cloud provider

<details>
cluster created by kubeadm
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
Rocky Linux 9.4
$ uname -a
Linux 5.14.0

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by dejanzele**
#### What type of PR is this?

/kind bug
/sig apps

#### Which issue(s) this PR is related to:

Fixes https://github.com/kubernetes/kubernetes/issues/134521

KEP: https://github.com/kubernetes/enhancements/issues/4368

#### Special notes for your reviewer:

This is a blocker for promoting [Job API managed-by mechanism](https://github.com/kubernetes/enhancements/issues/4368) to GA.

#### Does this PR introduce a user-facing change?

```release-note
Fix the bug which could result in Job status updates failing with the error:
status.startTime: Required value: startTime cannot be removed for unsuspended job
The error could be raised after a Job is resumed, if started and suspended previously.
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
NONE
```

### CODE REVIEW

File: pkg/apis/batch/validation/validation.go [hunk 1]
```diff
@@ -698,7 +698,10 @@ func ValidateJobStatusUpdate(job, oldJob *batch.Job, opts JobStatusValidationOpt
 	if opts.RejectStartTimeUpdateForUnsuspendedJob {
 		// Note that we check `oldJob.Status.StartTime != nil` to allow transitioning from
 		// startTime = nil to startTime != nil for unsuspended jobs, which is a desired transition.
-		if oldJob.Status.StartTime != nil && !ptr.Equal(oldJob.Status.StartTime, job.Status.StartTime) && !ptr.Deref(job.Spec.Suspend, false) {
+		// Also allow startTime updates when Job is being resumed (transitioning from suspended to unsuspended).
+		isJobBeingResumed := ptr.Deref(oldJob.Spec.Suspend, false) && !ptr.Deref(job.Spec.Suspend, false)
```
Comment (mimowo) [inline pkg/apis/batch/validation/validation.go]: I suspect this is not going to help because spec is updated in a different request than status. I would suggest to start with a repro in an integration test.

Comment (soltysh) [reply pkg/apis/batch/validation/validation.go]: See my [comment](https://github.com/kubernetes/kubernetes/issues/134521#issuecomment-3431871441) maybe we could relax it such that you're able to clear start time, when a job is suspended. That should alleviate the above problem.

Comment (mimowo) [reply pkg/apis/batch/validation/validation.go]: The status.startTime field can already be cleared while the Job is suspended and Kueue is already leveraging it, see [here](https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/jobs/job/job_controller.go#L184-L192).

Yes we can consider automatic clearing of the `status.startTime` field inside the Job controller, I'm ok with that, but:
1. since 1.32 this suspend / resume is broken (requires clearing of status.startTime by user) so we need some solution which could be cherry-picked
2. the transition in the Job controller on resuming would still remain invalid [here](https://github.com/kubernetes/kubernetes/blob/e4d85d1c13b8f482ab19ccd367ffbb8879fb070b/pkg/controller/job/job_controller.go#L1047-L1059), if the users attempts to resume just after suspending the user request would still fail, and require retry.
3. it means an extra request by Job controller (OTOH this request needs to be sent by the user or orchestration currently anyway)

If the above are not an issue for backporting the fix, then I'm good with that.

Comment (mimowo) [reply pkg/apis/batch/validation/validation.go]: > the transition in the Job controller on resuming would still remain invalid here, if the users attempts to resume just after suspending the user request would still fail, and require retry.

Ah, I think I'm wrong here. The user request to set `spec.suspend=false` will not fail, but the following Job controller's request would still fail, if the request to clear status does not complete eariler.

So, handling the scenario when user resumes is still valid, and (I think) it should be done anyway, unless we would block user setting `spec.suspend=false` quickly, but this sounds like going beyond a fix.

Comment (soltysh) [reply pkg/apis/batch/validation/validation.go]: Clearing in the controller seems like a very contained and small fix that we can easily backport all the way down to 1.32 which we [actively support until end of 2025](https://kubernetes.io/releases/patch-releases/#1-32).

Comment (mimowo) [reply pkg/apis/batch/validation/validation.go]: I'm not sure if clearing will actually solve the problem without changes to the validation, consider the following:

0. Job starts and the `status.startTime` is set
1. user sets `suspend=true`
2. Job controller schedules syncJob and is going to set `status.startTime=nil`
3. user changes mind and sets `suspend=false` immediately after
4. the request by controller contructed in (2.) fails due to conflict (old ResourceVersion)
5. Job controller tries to update the `status.startTime` "on resume"
Issue: request in (5.) fails - and will keep failing, because the old `status.startTime` was never reset.

Now, setting (1.) and (3.) isn't so rare, in case of orchestration like Kueue the decision could be changed almost immediately sometimes (say high priority workload just finished).

So, I would argue we need changes to the validation logic anyway. Once we do changes to the validation logic the resetting of the status.startTime is not necessary, and we could consider as a separate improvement.

File: test/integration/job/job_test.go [hunk 2]
```diff
@@ -4095,6 +4095,83 @@ func TestSuspendJob(t *testing.T) {
...
+		t.Fatalf("Failed to create Job: %v", err)
+	}
+
+	// Set initial startTime (simulating job controller setting it when job starts).
+	originalStartTime := time.Date(2025, 10, 10, 2, 10, 6, 0, time.UTC)
+	job.Status.StartTime = &metav1.Time{Time: originalStartTime}
+	job, err = clientSet.BatchV1().Jobs(ns.Name).UpdateStatus(ctx, job, metav1.UpdateOptions{})
+	if err != nil {
+		t.Fatalf("Failed to set initial startTime: %v", err)
+	}
```
Comment (mimowo) [inline test/integration/job/job_test.go]: No need to update the status.starttime, it will be updated by the controller. Just wait until it is set

File: test/integration/job/job_test.go [hunk 3]
```diff
@@ -4095,6 +4095,83 @@ func TestSuspendJob(t *testing.T) {
...
+		Type:               batchv1.JobSuspended,
+		Status:             v1.ConditionTrue,
+		Reason:             "JobSuspended",
+		Message:            "Job suspended by user",
+		LastTransitionTime: metav1.Now(),
+	}}
+	job, err = clientSet.BatchV1().Jobs(ns.Name).UpdateStatus(ctx, job, metav1.UpdateOptions{})
+	if err != nil {
+		t.Fatalf("Failed to add JobSuspended condition: %v", err)
+	}
```
Comment (mimowo) [inline test/integration/job/job_test.go]: Why manipulating the condition? It will be set by the Job controller. 

I think ideally we have two versions of the test (might be test case matrix controlling that):
1. flips suspend -> true -> false immediately
2. flips suspend -> true, waits for status.startTime to be cleared -> true 

However, two requires controller change, it might be a separete PR

File: test/integration/job/job_test.go [hunk 4]
```diff
@@ -4095,6 +4095,83 @@ func TestSuspendJob(t *testing.T) {
...
+	// Update the JobSuspended condition from True to False.
+	for i := range job.Status.Conditions {
+		if job.Status.Conditions[i].Type == batchv1.JobSuspended {
+			job.Status.Conditions[i].Status = v1.ConditionFalse
+			job.Status.Conditions[i].Reason = "JobResumed"
+			job.Status.Conditions[i].Message = "Job resumed by user"
+			job.Status.Conditions[i].LastTransitionTime = metav1.Now()
+			break
+		}
+	}
```
Comment (mimowo) [inline test/integration/job/job_test.go]: No need to simulate, it will just happen by the Job controller. Instead wait until the condition is set.

File: pkg/apis/batch/validation/validation.go [hunk 5]
```diff
@@ -698,7 +698,15 @@ func ValidateJobStatusUpdate(job, oldJob *batch.Job, opts JobStatusValidationOpt
 	if opts.RejectStartTimeUpdateForUnsuspendedJob {
 		// Note that we check `oldJob.Status.StartTime != nil` to allow transitioning from
 		// startTime = nil to startTime != nil for unsuspended jobs, which is a desired transition.
-		if oldJob.Status.StartTime != nil && !ptr.Equal(oldJob.Status.StartTime, job.Status.StartTime) && !ptr.Deref(job.Spec.Suspend, false) {
+
+		// Detect job resume via condition changes (JobSuspended: True -> False)
+		// This handles the case where the controller updates status after the user has already
+		// changed spec.suspend=false, which is the scenario from https://github.com/kubernetes/kubernetes/issues/134521
+		isJobResuming := IsConditionTrue(oldJob.Status.Conditions, batch.JobSuspended) &&
+			!IsConditionTrue(job.Status.Conditions, batch.JobSuspended)
```
Comment (mimowo) [inline pkg/apis/batch/validation/validation.go]: I'm thinking it will be cleaner to move this condition under computation of RejectStartTimeUpdateForUnsuspendedJob, because:
1.the name RejectStartTimeUpdateForUnsuspendedJob wouldn't capture the extra check currently
2. it will be clear from the context that the fix is behind the JobManagedBy feature gate, now it feels disconnected

File: pkg/registry/batch/job/strategy.go [hunk 6]
```diff
@@ -380,6 +380,11 @@ func getStatusValidationOptions(newJob, oldJob *batch.Job) batchvalidation.JobSt
 		isReadyChanged := !ptr.Equal(oldJob.Status.Ready, newJob.Status.Ready)
 		isTerminatingChanged := !ptr.Equal(oldJob.Status.Terminating, newJob.Status.Terminating)
 		isSuspendedWithZeroCompletions := ptr.Equal(newJob.Spec.Suspend, ptr.To(true)) && ptr.Equal(newJob.Spec.Completions, ptr.To[int32](0))
+		// Detect job resume via condition changes (JobSuspended: True -> False)
+		// This handles the case where the controller updates status after the user has already
+		// changed spec.suspend=false, which is the scenario from https://github.com/kubernetes/kubernetes/issues/134521
+		isJobResuming := batchvalidation.IsConditionTrue(oldJob.Status.Conditions, batch.JobSuspended) &&
+			!batchvalidation.IsConditionTrue(newJob.Status.Conditions, batch.JobSuspended)
```
Comment (mimowo) [inline pkg/registry/batch/job/strategy.go]:
```suggestion
			batchvalidation.IsConditionFalse(newJob.Status.Conditions, batch.JobSuspended)
```
I would suggest to add the function if not present before

File: test/integration/job/job_test.go [hunk 7]
```diff
@@ -4095,6 +4095,83 @@ func TestSuspendJob(t *testing.T) {
 	}
 }
 
+// TestSuspendJobStartTimeValidation verifies that the job controller can update startTime
+// when resuming a suspended job (https://github.com/kubernetes/kubernetes/issues/134521).
+func TestSuspendJobStartTimeValidation(t *testing.T) {
```
Comment (mimowo) [inline test/integration/job/job_test.go]:
```suggestion
func TestStartTimeUpdateOnResume(t *testing.T) {
```

File: test/integration/job/job_test.go [hunk 8]
```diff
@@ -4095,6 +4095,83 @@ func TestSuspendJob(t *testing.T) {
...
+
+	job, err = clientSet.BatchV1().Jobs(ns.Name).Get(ctx, job.Name, metav1.GetOptions{})
+	if err != nil {
+		t.Fatalf("Failed to get Job: %v", err)
+	}
+	if getJobConditionStatus(ctx, job, batchv1.JobSuspended) != v1.ConditionFalse {
+		t.Fatalf("JobSuspended condition was not set to False")
+	}
+	if job.Status.StartTime == nil {
+		t.Fatalf("Job startTime was not set after resume")
```
Comment (mimowo) [inline test/integration/job/job_test.go]:
```suggestion
		t.Errorf("Job startTime was not set after resume")
```
nit, this is an assert. Fatalf iiuc is for setup, when continuing asserts wouldn't make sense

File: test/integration/job/job_test.go [hunk 9]
```diff
@@ -4095,6 +4095,83 @@ func TestSuspendJob(t *testing.T) {
...
+		Ready:       ptr.To[int32](0),
+		Terminating: ptr.To[int32](0),
+	})
+
+	job, err = clientSet.BatchV1().Jobs(ns.Name).Get(ctx, job.Name, metav1.GetOptions{})
+	if err != nil {
+		t.Fatalf("Failed to get Job: %v", err)
+	}
+	if getJobConditionStatus(ctx, job, batchv1.JobSuspended) != v1.ConditionFalse {
+		t.Fatalf("JobSuspended condition was not set to False")
```
Comment (mimowo) [inline test/integration/job/job_test.go]:
```suggestion
		t.Errorf("JobSuspended condition was not set to False")
```

**Review by mimowo — COMMENTED** [review]
LGTM overall, thank you.

File: test/integration/job/job_test.go (hunk 7 above)
Comment (mimowo) [inline test/integration/job/job_test.go]: I would also suggest to enable the JobManagedBy feature gate explicitly, even if now it is enabled by default.

**Review by mimowo — COMMENTED** [review]
/lgtm
I think this is minimal fix for the issue, as we discussed in https://github.com/kubernetes/kubernetes/pull/134769#discussion_r2451748349
 it may be beneficial to also clear the `status.startTime` along with setting JobSuspended condition. I'm ok to leave it as a follow up PR.

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Comment by mimowo** [comment]
Yes, the this code is specifically what we need to workaround currently in Kueue by clearing the status.startTime: https://github.com/kubernetes-sigs/kueue/blob/main/pkg/controller/jobs/job/job_controller.go#L184-L192
TBH it feels that clearing the status.startTime might be better fit for the new KEP rather than JobManagedBy KEP.

**Comment by soltysh** [comment]
> TBH it feels that clearing the status.startTime might be better fit for the new KEP rather than JobManagedBy KEP.

It definitely should not be part of JobManagedBy KEP, I still wonder though if the clearing part requires an actual KEP. The more I'm thinking about it, the more I'm inclined to say it's a bug that we've never fixed when working on [Job Suspension](https://github.com/kubernetes/enhancements/issues/2232)

File: test/integration/job/job_test.go (hunk 3 above)
Comment (dejanzele) [reply test/integration/job/job_test.go]: Sticking with 2. for now

Comment (mimowo) [reply test/integration/job/job_test.go]: sgtm, feel free to resolve

File: pkg/apis/batch/validation/validation.go (hunk 1 above)
Comment (mimowo) [reply pkg/apis/batch/validation/validation.go]: After discussing with @soltysh we decided here to move the discussion under the other PR, and here are the next plans summarized: https://github.com/kubernetes/kubernetes/pull/134980#discussion_r2481084339

Since the PR is also referenced in the global comment https://github.com/kubernetes/kubernetes/pull/134769#issuecomment-3469081491 I think we can resolve this one to avoid distractions

**Comment by mimowo** [comment]
@dejanzele please prepare cherrypicks
