### PR TITLE
fix node start time inconsistency in kubelet

### LINKED ISSUE #127841: kubelet GetBootTime() could drift backward for 1s
### What happened?

There are a few places in kubelet that calls `pkg/kubelet/util`.`GetBootTime()`. One such place is the kubelet `/stats/summary` endpoint where it's getting the node startTime: [ref](https://github.com/kubernetes/kubernetes/blob/v1.30.0/pkg/kubelet/server/stats/summary.go#L56)

And there's an issue in the [Linux implementation of `GetBootTime`](https://github.com/kubernetes/kubernetes/blob/v1.31.0/pkg/kubelet/util/boottime_util_linux.go#L30) that the result is not consistent: sometimes it could drift backwards for 1s. This caused problem in certain monitoring systems where the time series database expect timestamps to be monotonically increasing.****

### What did you expect to happen?

`GetBootTime()` to return consistent result everytime it runs, more specifically the kubelet `/stats/summary` endpoint returns a consistent node startTime when kubelet restarts.

### How can we reproduce it (as minimally and precisely as possible)?

do the following steps multiple times:

- restart kubelet
- do a http get on kubelet /stats/summary endpoint
- observe the `node`.`startTime` field in the response

you will see the node startTime could shift backwards for 1s in some cases.

You can also reproduce the issue by simply running the same `GetBootTime` logic multiple times:

```
cat get-boot-time.go 
package main

import (
	"fmt"
	"time"
	"golang.org/x/sys/unix"
)

func main() {
	// This is the same logic as `pkg/kubelet/util/boottime_util_linux.go`
	currentTime := time.Now()
	var info unix.Sysinfo_t
	if err := unix.Sysinfo(&info); err != nil {
		fmt.Errorf("error getting system uptime: %s", err)
		return
	}
	bootTime := currentTime.Add(-time.Duration(info.Uptime) * time.Second).Truncate(time.Second)
	fmt.Printf("bootTime: %s\n", bootTime)
	return
}

$ for i in {1..100} ; do go run get-boot-time.go ; done
bootTime: 2024-09-09 01:04:18 +0000 UTC
bootTime: 2024-09-09 01:04:18 +0000 UTC
bootTime: 2024-09-09 01:04:17 +0000 UTC    <--------- 1s backward drift
bootTime: 2024-09-09 01:04:18 +0000 UTC
 bootTime: 2024-09-09 01:04:18 +0000 UTC
bootTime: 2024-09-09 01:04:18 +0000 UTC
bootTime: 2024-09-09 01:04:18 +0000 UTC
```

### Anything else we need to know?

I think the cause is a combination of multiple factors:

(a) `currentTime := time.Now()` is represented in a sub-second unit
(b) `unix.Sysinfo.Uptime` has a unit in second
(c) GetBootTime() subtracts uptime from current time and then round to the earlier second with the `time`.`Truncate()` method

so the following situation could happen:

1. system actually starts at 0,
2. when kubelet calls GetBootTime(), currentTIme returns 10s 999ms 999us 999ns
3. then 1us later, sysInfo reports Uptime 11s
4. at the end GetBootTime would round (10.999999 - 11) and return -1s instead of the actual 0s

### One possible solution:

The drift always happen when Sysinfo.upTime increased by one second, so we could avoid it by: call the same GetBootTime() logic 3 times in a row, assuming each call finishes < 1s, then there will be for sure at least 2 times where Sysinfo.upTime agrees with each other. Then out of the 2 times, we use the GetBootTime() result from first one.

### Kubernetes version

all existing kubernetes versions

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by leonzz**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

Make kubelet report consistent start time at every restart.

See the linked issue for why we need it.

#### Which issue(s) this PR fixes:

Fixes #127841

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

### CODE REVIEW

File: pkg/kubelet/util/boottime_util_linux.go [hunk 1]
```diff
@@ -21,17 +21,26 @@ package util
...
-	"golang.org/x/sys/unix"
 )
 
-// GetBootTime returns the time at which the machine was started, truncated to the nearest second
+// GetBootTime returns the time at which the machine was started, truncated to the nearest second.
 func GetBootTime() (time.Time, error) {
 	currentTime := time.Now()
-	var info unix.Sysinfo_t
-	if err := unix.Sysinfo(&info); err != nil {
+	raw, err := os.ReadFile("/proc/uptime")
```
Comment (dims) [inline pkg/kubelet/util/boottime_util_linux.go:33]: Let's fall back to `unix.Sysinfo` if we can't get the info from the file for some reason or other.

**Review by kalvarahul — APPROVED** [review]

File: pkg/kubelet/util/boottime_util_linux.go [hunk 2]
```diff
@@ -21,13 +21,39 @@ package util
...
+	}
+	uptimeStr, _, found := strings.Cut(string(raw), " ")
+	if !found {
+		klog.Errorf("unexpected value from /proc/uptime: %s", raw)
+		return getBootTimeWithSysinfo()
+	}
+	uptime, err := strconv.ParseFloat(uptimeStr, 64)
+	if err != nil {
+		klog.Errorf("error parsing uptime %s: %s", uptimeStr, err)
+		return getBootTimeWithSysinfo()
```
Comment (aojea) [inline pkg/kubelet/util/boottime_util_linux.go:51]: this sounds very brittle can we have unit test for this?

Comment (leonzz) [reply pkg/kubelet/util/boottime_util_linux.go:51]: hmm yeah, the existing unit test only cares about getting a result so with this fall back behavior we don't know if the result is produced with /proc/uptime or unix.Sysinfo. How about further separating them into `func getBootTimeWithSysinfo()` and `func getBootTimeWithProcUptime()` so we can test them separately. Then in the entry point `func GetBooTime()` we just call out to the 2 methods. WDYT?

Comment (leonzz) [reply pkg/kubelet/util/boottime_util_linux.go]: k I updated the commit as described, so marking as resolved. Let me know if you have further comments-)

File: pkg/kubelet/util/boottime_util_linux.go [hunk 3]
```diff
@@ -21,17 +21,49 @@ package util
...
+	"strings"
 	"time"
 
 	"golang.org/x/sys/unix"
+	"k8s.io/klog/v2"
 )
 
-// GetBootTime returns the time at which the machine was started, truncated to the nearest second
+// GetBootTime returns the time at which the machine was started, truncated to the nearest second.
+// It uses /proc/uptime first, which is more accurate, and falls back to the less accurate
```
Comment (tallclair) [inline pkg/kubelet/util/boottime_util_linux.go:34]: What about using btime from /proc/stat? (https://man7.org/linux/man-pages/man5/proc_stat.5.html). That seems like it would be the most reliable and stable, since there's no race with reading the current time?

File: pkg/kubelet/util/boottime_util_linux.go [hunk 4]
```diff
@@ -21,17 +21,49 @@ package util
...
+// unix.Sysinfo if /proc/uptime failed.
 func GetBootTime() (time.Time, error) {
+	bootTime, err := getBootTimeWithProcUptime()
+	if err != nil {
+		klog.ErrorS(err, "Failed to get boot time from /proc/uptime. Will retry with unix.Sysinfo")
```
Comment (tallclair) [inline pkg/kubelet/util/boottime_util_linux.go:39]: How expected is this error? Given that there's a fallback, I wonder if this should be a lower verbosity.

**Review by tallclair — COMMENTED** [review]
Does this issue just show up on Kubelet restart? If not, maybe we should just cache the result of GetBootTime to prevent drift?

File: pkg/kubelet/util/boottime_util_linux.go (hunk 3 above)
Comment (leonzz) [reply pkg/kubelet/util/boottime_util_linux.go:34]: Do we know for sure if btime from /proc/stat is a better choice?

In the few systems I own, /proc/stat does look stable. 
But this [linux kernel getboottime comments](https://github.com/torvalds/linux/blob/v6.11/kernel/time/timekeeping.c#L2365-L2373), which is behind `/proc/stat`, makes me think it's not consistent either. In fact a quick search gives some super old reports of it drifting: [example 1](https://bugzilla.redhat.com/show_bug.cgi?id=132062)  [example 2](https://forums.gentoo.org/viewtopic-t-1039524-start-0.html)

If we don't know for sure, I tend to prefer /proc/uptime because it's in a much simpler format to parse, with just one line and 2 numbers.

File: pkg/kubelet/util/boottime_util_linux.go [hunk 5]
```diff
@@ -21,17 +21,49 @@ package util
...
+	return bootTime, nil
+}
+
+func getBootTimeWithProcUptime() (time.Time, error) {
+	currentTime := time.Now()
+	raw, err := os.ReadFile("/proc/uptime")
+	if err != nil {
+		return time.Time{}, fmt.Errorf("error getting system uptime: %w", err)
+	}
+	uptimeStr, _, found := strings.Cut(string(raw), " ")
```
[the remark this answers is not in the document]
Comment (leonzz) [reply pkg/kubelet/util/boottime_util_linux.go:51]: sounds good!  Didn't know about strings.Fields before, which looks like a better option to process space seperated stuff.
Will update the commit once the comment on /proc/stat is settled.

File: pkg/kubelet/util/boottime_util_linux.go (hunk 4 above)
Comment (leonzz) [reply pkg/kubelet/util/boottime_util_linux.go:39]: lowering to warning or info sounds good.  I think the error shouldn't be expected much, neither is it significant.
will do the update after the other comment on /proc/stat is settled.

**Comment by leonzz** [comment]
> Does this issue just show up on Kubelet restart? If not, maybe we should just cache the result of GetBootTime to prevent drift?

yes kubelet restart is the main concern.  kubelet /stat/summary only calls GetBootTime once during init and use the same value afterwards, so without restart the reporting is already consistent.

File: pkg/kubelet/util/boottime_util_linux.go (hunk 4 above)
Comment (leonzz) [reply pkg/kubelet/util/boottime_util_linux.go]: Done.

File: pkg/kubelet/util/boottime_util_linux.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (leonzz) [reply pkg/kubelet/util/boottime_util_linux.go]: Done

File: pkg/kubelet/util/boottime_util_linux.go (hunk 3 above)
Comment (tallclair) [reply pkg/kubelet/util/boottime_util_linux.go:34]: I don't know. I just noticed it when reading up on the proc man page for this PR. If the value is dependable, then I do think it seems preferable to the current approach since it doesn't have the issue with getting the current time. I won't block the PR on it though.

File: pkg/kubelet/util/boottime_util_linux.go [hunk 6]
```diff
@@ -21,17 +21,49 @@ package util
...
+	}
+	rawFields := strings.Fields(string(raw))
+	if len(rawFields) != 2 {
+		return time.Time{}, fmt.Errorf("unexpected value from /proc/uptime: %s", raw)
+	}
+	uptime, err := strconv.ParseFloat(rawFields[0], 64)
+	if err != nil {
+		return time.Time{}, fmt.Errorf("error parsing uptime %s: %w", rawFields[0], err)
+	}
+	return currentTime.Add(-time.Duration(uptime * float64(time.Second))).Truncate(time.Second), nil
```
Comment (tallclair) [inline pkg/kubelet/util/boottime_util_linux.go:59]: Would `Round` be more reliable than `Truncate` here?
```suggestion
	return currentTime.Add(-time.Duration(uptime * float64(time.Second))).Round(time.Second), nil
```

Comment (leonzz) [reply pkg/kubelet/util/boottime_util_linux.go:59]: I think they are the same in terms of reliability and consistency:  for `round`, the corner case happens around half seconds; for `truncate`, the corner case happens around whole seconds. If the true timestamps follow even distribution, then the chances of corner case happening should be the same.

I kept truncate because was the original behavior (cc @dashpole ), so node start time won't drift when upgrading to this new version of kubelet.

File: pkg/kubelet/util/boottime_util_linux.go (hunk 3 above)
Comment (leonzz) [reply pkg/kubelet/util/boottime_util_linux.go:34]: ACK. yeah I agree that it's more reliable even though it's also calculating by [subtracting uptime from current time](https://github.com/torvalds/linux/blob/v6.11/kernel/time/timekeeping.c#L2365-L2381), but the calculation happens in kernel, not our code. 

Also it's good practise to not recreate the same logic since the kernel provide an API directly.

let me update the commit to use `proc/stat`. The parsing is not as simple as `/proc/uptime` but not overly complex either.

File: pkg/kubelet/util/boottime_util_linux.go (hunk 6 above)
Comment (leonzz) [reply pkg/kubelet/util/boottime_util_linux.go]: Updated the change to use `/proc/stat` so this is no longer applicable.

B.T.W. the linue kernel calculation of boot time is [returning the second and discarding subsecond](https://github.com/torvalds/linux/blob/v6.11/fs/proc/stat.c#L175-L180), equivalent to our `truncate` here.

File: pkg/kubelet/util/boottime_util_linux.go (hunk 3 above)
Comment (leonzz) [reply pkg/kubelet/util/boottime_util_linux.go]: Done.

**Review by tallclair — APPROVED** [review]
/lgtm
/approve
