### PR TITLE
deflake e2e tests: CustomResourcePublishOpenAPI works for multiple CRDs of same group and version but different kinds

### LINKED ISSUE #131329: [Flake] CustomResourcePublishOpenAPI works for multiple CRDs of same group and version but different kinds
Failure is because of a conflict

> Kubernetes e2e suite: [It] [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for multiple CRDs of same group and version but different kinds [Conformance] expand_less	6s
{ failed [FAILED] failed to create CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io "e2e-test-crd-publish-openapi-2892-crds.crd-publish-openapi-test-common-group.example.com" already exists
In [It] at: k8s.io/kubernetes/test/utils/crd/crd_util.go:100 @ 04/15/25 22:02:04.353
}

Seen in https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/131015/pull-kubernetes-e2e-kind/1912261630285058048

apiserver logs in https://storage.googleapis.com/kubernetes-ci-logs/pr-logs/pull/131015/pull-kubernetes-e2e-kind/1912261630285058048/artifacts/kind-control-plane/pods/kube-system_kube-apiserver-kind-control-plane_6e89b7f598236e5454f132b90d21cd14/kube-apiserver/0.log.20250415-221412

CRD is added at

> 2025-04-15T22:02:02.619334978Z stderr F I0415 22:02:02.618455       1 httplog.go:134] "HTTP" verb="POST" URI="/apis/apiextensions.k8s.io/v1/customresourcedefinitions" latency="5.27573ms" userAgent="e2e.test/v1.34.0 (li
nux/amd64) kubernetes/f82a875 -- [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for multiple CRDs of same group and version but different kinds [Conformance]" audit-ID="c8f6cd97-7771-4
ee7-9921-e53cd35accb0" srcIP="172.18.0.1:40402" apf_pl="global-default" apf_fs="global-default" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_execution_time="4.667821ms" resp=201

conflict in

> 2025-04-15T22:02:04.352495982Z stderr F I0415 22:02:04.352291       1 httplog.go:134] "HTTP" verb="POST" URI="/apis/apiextensions.k8s.io/v1/customresourcedefinitions" latency="12.674401ms" userAgent="e2e.test/v1.34.0 (linux/amd64) kubernetes/f82a875 -- [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for multiple CRDs of same group and version but different kinds [Conformance]" audit-ID="6366bd78-ead3-46e9-8568-57ffb4e51c35" srcIP="172.18.0.1:54534" apf_pl="global-default" apf_fs="global-default" apf_iseats=1 apf_fseats=0 apf_additionalLatency="0s" apf_execution_time="11.38869ms" resp=409

The test seems to create two CRDs and the conflict seems to happen when the second CRD is installed

https://github.com/kubernetes/kubernetes/blob/44c230bf5c321056e8bc89300b37c497f464f113/test/e2e/apimachinery/crd_publish_openapi.go#L361-L367

/sig api-machinery
/kind flake

### PR DESCRIPTION
**Pull request by carlory**
#### What type of PR is this?

/kind flake

#### What this PR does / why we need it:

**test name: CustomResourcePublishOpenAPI works for multiple CRDs of same group and version but different kinds**

https://github.com/kubernetes/kubernetes/blob/44c230bf5c321056e8bc89300b37c497f464f113/test/e2e/apimachinery/crd_publish_openapi.go#L361-L367

**test name: works for multiple CRDs of same group but different versions**

https://github.com/kubernetes/kubernetes/blob/44c230bf5c321056e8bc89300b37c497f464f113/test/e2e/apimachinery/crd_publish_openapi.go#L328-L335

each test creates two CRDs and the conflict seems to happen when the second CRD is installed. 

The timeline of 4 events based on the kube-apiserver-audit.log.json. (test name: works for multiple CRDs of same group but different versions)

1. create the first crd 
    name: e2e-test-crd-publish-openapi-3386-crds.crd-publish-openapi-test-common-group.example.com
    userAgent: "e2e.test/v1.33.0 (linux/amd64) kubernetes/195803c -- [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for multiple CRDs of same group but different versions [Conformance]"
2. update crd status
    userAgent: "kube-apiserver/v1.33.0 (linux/amd64) kubernetes/195803c"
3. update crd status
    userAgent: "kube-apiserver/v1.33.0 (linux/amd64) kubernetes/195803c"
4. create the second crd 
    name: e2e-test-crd-publish-openapi-3386-crds.crd-publish-openapi-test-common-group.example.com (⚠️  AlreadyExists) 
    userAgent: "e2e.test/v1.33.0 (linux/amd64) kubernetes/195803c -- [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for multiple CRDs of same group but different versions [Conformance]"

The root cause is that generated suffix might be same value when create 2 crd  in one test .

https://github.com/kubernetes/kubernetes/blob/b53b9fb5573323484af9a19cf3f5bfe80760abba/test/utils/crd/crd_util.go#L49-L51

See [kube-apiserver-audit.log.json](https://github.com/user-attachments/files/19790061/kube-apiserver-audit.log.json) for details.

the audit log is taken from https://gcsweb.k8s.io/gcs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-gci-gce-coredns/1907945525429145600/artifacts/e2e-32942e7243-edcff-master/.

image

image

#### Which issue(s) this PR fixes:

Fixes #131329

#### Does this PR introduce a user-facing change?

```release-note
NONE
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by carlory** [comment]
image

https://gcsweb.k8s.io/gcs/kubernetes-ci-logs/pr-logs/pull/131015/pull-kubernetes-e2e-kind/1912261630285058048/

the kubernetes-ci-logs doesn't contains the file kube-apiserver-aduit.log when tests runs on a kind cluster. We have to try to get the aduit log from other jobs like ci-kubernetes-e2e-gci-gce-coredns via https://storage.googleapis.com/k8s-triage/index.html?text=

Is it possible to collect the kube-apiserver-audit.log from kind cluster and then upload it to the Artifacts dirctory? It is very useful for us to debug the test failure and find the root cause.

/cc @pohly @BenTheElder

**Comment by aojea** [comment]
> Is it possible to collect the kube-apiserver-audit.log from kind cluster and then upload it to the Artifacts dir? It is very useful for us to debug the test failure and find the root cause.

This job enables the audit logs in kind https://prow.k8s.io/view/gcs/kubernetes-ci-logs/logs/ci-audit-kind-conformance/1912345090584481792

File: test/utils/crd/crd_util.go [hunk 1]
```diff
@@ -69,6 +69,56 @@ func CreateMultiVersionTestCRD(f *framework.Framework, group string, opts ...Opt
...
+	}
+	return testcrd, nil
+}
+
+// genRandomCRD generates a random CRD name and kind based on the framework's base name and a random suffix.
+// It also sets the group to the provided value and sets the scope to NamespaceScoped. If no versions are provided via
+// the opts, it will create a default version "v1" with an allow-all schema.
+func genRandomCRD(f *framework.Framework, group string, opts ...Option) *apiextensionsv1.CustomResourceDefinition {
+	suffix := framework.RandomSuffix()
+	name := fmt.Sprintf("e2e-test-%s-%s-crd", f.BaseName, suffix)
```
Comment (aojea) [inline test/utils/crd/crd_util.go:119]: we have `UniqueName` just for this
```suggestion
	name := fmt.Sprintf("e2e-test-%s-%s-crd", f.UniqueName, suffix)
```

**Comment by carlory** [comment]
> can you explain better the reason on the flake in the description?

@aojea updated.

**Comment by carlory** [comment]
> This job enables the audit logs in kind https://prow.k8s.io/view/gcs/kubernetes-ci-logs/logs/ci-audit-kind-conformance/1912345090584481792

Can we apply the same audit configuration to other kind jobs, i.e., pull-kubernetes-e2e-kind?

File: test/utils/crd/crd_util.go [hunk 2]
```diff
@@ -69,6 +69,56 @@ func CreateMultiVersionTestCRD(f *framework.Framework, group string, opts ...Opt
...
+	return testcrd, nil
+}
+
+// genRandomCRD generates a random CRD name and kind based on the framework's base name and a random suffix.
+// It also sets the group to the provided value and sets the scope to NamespaceScoped. If no versions are provided via
+// the opts, it will create a default version "v1" with an allow-all schema.
+func genRandomCRD(f *framework.Framework, group string, opts ...Option) *apiextensionsv1.CustomResourceDefinition {
+	suffix := framework.RandomSuffix()
+	name := fmt.Sprintf("e2e-test-%s-%s-crd", f.UniqueName, suffix)
+	kind := fmt.Sprintf("e2e-test-%s-%s-crd", f.UniqueName, suffix)
```
Comment (carlory) [inline test/utils/crd/crd_util.go:120]: should the kind also be generated with `UniqueName`? cc @aojea

**Comment by aojea** [comment]
> The root cause is that generated suffix might be same value when create 2 crd in one test .

then , don't we need to fix `framework.RandomSuffix() ` to be really random ?

```diff
diff --git a/test/e2e/framework/util.go b/test/e2e/framework/util.go
index 7eed8e36751..7e6a27abbee 100644
--- a/test/e2e/framework/util.go
+++ b/test/e2e/framework/util.go
@@ -22,7 +22,6 @@ import (
        "encoding/json"
        "fmt"
        "io"
-       "math/rand"
        "net/url"
        "os"
        "os/exec"
@@ -40,6 +39,7 @@ import (
        apierrors "k8s.io/apimachinery/pkg/api/errors"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
        "k8s.io/apimachinery/pkg/fields"
+       apirand "k8s.io/apimachinery/pkg/rand"
        "k8s.io/apimachinery/pkg/runtime"
        "k8s.io/apimachinery/pkg/runtime/schema"
        "k8s.io/apimachinery/pkg/util/sets"
@@ -523,7 +523,7 @@ func LoadClientset() (*clientset.Clientset, error) {
 
 // RandomSuffix provides a random sequence to append to pods,services,rcs.
 func RandomSuffix() string {
-       return strconv.Itoa(rand.Intn(10000))
+       return strconv.Itoa(apirand.Intn(10000))
 }
 
 // StartCmdAndStreamOutput returns stdout and stderr after starting the given cmd.
```

**Comment by carlory** [comment]
> then , don't we need to fix framework.RandomSuffix()  to be really random ?

It is not 100% possible to avoid conflicts, so retry logic is still necessary. I'm not sure whether we should replace it with apirand. we doesn't observe any panic on rand yet.

**Comment by carlory** [comment]
> The possibility of a collision is 1/10000, right?

It's not truth. When using rand.Intn(10000) from Go’s math/rand package, you're generating pseudo-random integers in the range [0, 9999] — a total of 10,000 possible values. The possibility of a collision is related to the number of generated integers and the range of possible values. As you generate more numbers, the chance of at least one duplicate (collision) increases rapidly similar to the birthday paradox. 

The approximate probability of at least one collision is:

image

**Comment by carlory** [comment]
> The random number generator is seeded with apirand.

The same seed number will generate the same random numbers. So it will not change the possibility of a collision when using the different seed number. The only difference is the order of the random numbers generated.

**Comment by aojea** [comment]
we only generate 2 CRDs , so the probability of collision that cause the flake is that given one number we obtain the same number ... it is not about birthday paradox, it is about generating the same crd name

**Comment by Jefftree** [comment]
Is it the case that using UniqueName instead of BaseName we reduce the collision probability because randomization is done on the test level rather than the framework level? So we reduce the birthday paradox from 15 in the file to the maximum of 2 per test. We reduce the collision probability from $(1-{P(10000,15)}/{10000^{15}}) \approx$ 1%  ==> 1/10000 = 0.01%? That also seems good enough to me, but maybe make a note of this for future callers of `CreateTestCRD()`?

**Comment by aojea** [comment]
I'm a bit lost, where is 15 coming from?

```
grep -r CreateMultiVersionTestCRD test/
test/e2e/apimachinery/crd_selectable_fields.go:                 testcrd, err := crd.CreateMultiVersionTestCRD(f, "stable.example.com", func(crd *apiextensionsv1.CustomResourceDefinition) {
test/e2e/apimachinery/webhook.go:       return crd.CreateMultiVersionTestCRD(f, group, append([]crd.Option{func(crd *apiextensionsv1.CustomResourceDefinition) {
test/e2e/apimachinery/crd_conversion_webhook.go:                testcrd, err := crd.CreateMultiVersionTestCRD(f, "stable.example.com", func(crd *apiextensionsv1.CustomResourceDefinition) {
test/e2e/apimachinery/crd_conversion_webhook.go:                testcrd, err := crd.CreateMultiVersionTestCRD(f, "stable.example.com", func(crd *apiextensionsv1.CustomResourceDefinition) {
test/e2e/apimachinery/crd_publish_openapi.go:   crd, err := crd.CreateMultiVersionTestCRD(f, group, options...)
```

I may be mistakenly assume the problem is the seeding was not random enough to generate enough entropy.

Let's keep this simply and add the time unix nano to the suffix, so we only care about conflict when things are called at the exact same time that is very very very unlikely

```
suffix := fmt.Sprintf("%s-%x", framework.RandomSuffix(), time.Now().Unix())
```

File: test/utils/crd/crd_util.go [hunk 3]
```diff
@@ -47,9 +50,6 @@ type Option func(crd *apiextensionsv1.CustomResourceDefinition)
 
 // CreateMultiVersionTestCRD creates a new CRD specifically for the calling test.
 func CreateMultiVersionTestCRD(f *framework.Framework, group string, opts ...Option) (*TestCrd, error) {
-	suffix := framework.RandomSuffix()
```
Comment (aojea) [inline test/utils/crd/crd_util.go:50]:
```
suffix := fmt.Sprintf("%s-%x", framework.RandomSuffix(), time.Now().Unix()) 

```

this will be more than enough

**Comment by Jefftree** [comment]
> I'm a bit lost, where is 15 coming from?

I was looking specifically in `test/e2e/apimachinery/crd_publish_openapi.go` where `CreateMultiVersionTestCRD` is called within the [setupCRD()](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/crd_publish_openapi.go#L526) function and found 15 instances of that in the specific test file.

File: test/utils/crd/crd_util.go (hunk 3 above)
Comment (Jefftree) [reply test/utils/crd/crd_util.go:50]: If this retry logic is something we already do for namespaces, it seems fine use the same pattern for CRDs? Slight preference to just retry as that reduces flake chances to 0 rather than near 0 but will defer to @aojea

Comment (aojea) [reply test/utils/crd/crd_util.go:50]: fair

File: test/utils/crd/crd_util.go (hunk 2 above)
Comment (aojea) [reply test/utils/crd/crd_util.go:120]: let's try to keep the diff small, we can always iterate

**Comment by aojea** [comment]
/lgtm
/approve

Thanks for your patience and the constructive discussion
