### PR TITLE
Fix: Clean job tracking finalizer from orphan pods

### LINKED ISSUE #108645: JobTrackingWithFinalizers: Orphan pods might not get the finalizer cleared
### What happened?

I run into a situation where a pod didn't loose the finalizer, then it blocked the deletion of a namespace.

We do have an integration test for orphan pods
https://github.com/kubernetes/kubernetes/blob/425ff1c8e2d29874926abb7da37641cf785c4ff3/test/integration/job/job_test.go#L537

But I fear that it might not cover all cases

### What did you expect to happen?

Finalizer to always be removed

### How can we reproduce it (as minimally and precisely as possible)?

This is a theory, rather than a concrete set of steps:

1. Some pods of a job start.
2. A pod finishes (then it would get a deletion timestamp). Let's assume the job controller doesn't have time to count this pod.
3. A client deletes the job. The cascade would theoretically delete the pod, but since it already has a deletion timestamp, it's not updated again, so it doesn't have a chance to go to the work queue for orphan jobs.

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
1.23.4
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### PR DESCRIPTION
**Pull request by alculquicondor**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

When a job is deleted, we can run into an scenario where the job exists when we are processing a pod deletion event. By the time the job reconciler runs, which would have removed the finalizers, the job no longer exist. As a result, nothing removes the finalizers.

Also, since the default propagation for Job deletion is orphaning, a deleted Pod might still have a finalizer but not an owner reference. We should clean the finalizer in this case.

I added an integration test that catches the issue ~1/3 of the time. I had to add a GC into the mix and make the job-controller significantly slower.

The final solution looks like this:

1. on pod add/update:
	A. if no job ownerRef, remove finalizer if needed
	B. if job ownerRef and job does not exist in cache, remove finalizer if needed
2. on job delete (delete event with background)
	_means our cache knows the job is gone_
	enqueue all child pods of the deleted job, collapses to 1B case

#### Which issue(s) this PR fixes:

Fixes #108645

#### Special notes for your reviewer:

This needs to be backported to 1.23
Thanks @liggitt once more for brainstorming a solution with me.

#### Does this PR introduce a user-facing change?

```release-note
Fix a 1.23 regression where the job controller might not remove the job tracking finalizer from pods when deleting a job, or when the pod is orphan
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/controller/job/job_controller.go [hunk 1]
```diff
@@ -421,6 +419,22 @@ func (jm *Controller) updateJob(old, cur interface{}) {
 	}
 }
 
+// deleteJob enqueues the job and all the pods associated with it that still
+// have a finalizer.
+func (jm *Controller) deleteJob(obj interface{}) {
+	jm.enqueueController(obj, true)
+	jobObj := obj.(*batch.Job)
```
Comment (liggitt) [inline pkg/controller/job/job_controller.go:426]: this will panic on DeletedFinalStateUnknown events from the informer

**Comment by alculquicondor** [comment]
Oops, I broke a different test

/hold

File: pkg/controller/job/job_controller.go [hunk 2]
```diff
@@ -421,6 +423,33 @@ func (jm *Controller) updateJob(old, cur interface{}) {
 	}
 }
 
+// deleteJob enqueues the job and all the pods associated with it that still
+// have a finalizer.
+func (jm *Controller) deleteJob(obj interface{}) {
+	jm.enqueueController(obj, true)
```
Comment (liggitt) [inline pkg/controller/job/job_controller.go:429]: will enqueueController handle DeletedFinalStateUnknown objects correctly?

File: pkg/controller/job/job_controller.go [hunk 3]
```diff
@@ -421,6 +423,33 @@ func (jm *Controller) updateJob(old, cur interface{}) {
...
+			utilruntime.HandleError(fmt.Errorf("tombstone contained object that is not a job %+v", obj))
+			return
+		}
+	}
+	// Listing pods shouldn't really fail, as we are just querying the informer cache.
+	pods, _ := jm.podStore.Pods(jobObj.Namespace).List(labels.Everything())
+	for _, pod := range pods {
+		controllerRef := metav1.GetControllerOf(pod)
+		if (controllerRef == nil || controllerRef.UID == jobObj.UID) && hasJobTrackingFinalizer(pod) {
+			jm.enqueueOrphanPod(pod)
```
Comment (liggitt) [inline pkg/controller/job/job_controller.go:448]: are we relying on observing the job deletion to handle orphan pods correctly? what if the controller is down when the job is deleted and the pods are orphaned. does it remove finalizers correctly if it starts up and observes its finalizer on pods which aren't owned by a job?

File: pkg/controller/job/job_controller.go (hunk 2 above)
Comment (alculquicondor) [reply pkg/controller/job/job_controller.go:429]: yes :)

File: pkg/controller/job/job_controller.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/controller/job/job_controller.go:448]: That's the other fix in function `deletePod`. If it's not being deleted, it could still be adopted by other jobs.

I don't think I can enqueue the pod for finalizer removal in that scenario. This race condition could happen: `syncJob` for another job adopts it and adds a finalizer. `syncOrphanPod` runs and deletes the finalizer.

File: pkg/controller/job/job_controller.go [hunk 4]
```diff
@@ -421,6 +423,33 @@ func (jm *Controller) updateJob(old, cur interface{}) {
...
+			return
+		}
+		jobObj, ok = tombstone.Obj.(*batch.Job)
+		if !ok {
+			utilruntime.HandleError(fmt.Errorf("tombstone contained object that is not a job %+v", obj))
+			return
+		}
+	}
+	// Listing pods shouldn't really fail, as we are just querying the informer cache.
+	pods, _ := jm.podStore.Pods(jobObj.Namespace).List(labels.Everything())
```
Comment (soltysh) [inline pkg/controller/job/job_controller.go:444]: Why not using the job selector when listing pods? We don't need to be looking at all pods, especially that it already happens in `syncJob` when adopting pods.

File: pkg/controller/job/job_controller.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/controller/job/job_controller.go:448]: I realized that I'm contradicting myself in the comment above with respect to the current implementation.

I need to think about this more.

/hold

File: pkg/controller/job/job_controller.go (hunk 4 above)
Comment (alculquicondor) [reply pkg/controller/job/job_controller.go]: Done

File: pkg/controller/job/job_controller.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/controller/job/job_controller.go:462]: All good now
/hold cancel

File: pkg/controller/job/job_controller.go [hunk 5]
```diff
@@ -368,6 +366,10 @@ func (jm *Controller) deletePod(obj interface{}, final bool) {
 	controllerRef := metav1.GetControllerOf(pod)
 	if controllerRef == nil {
 		// No controller should care about orphans being deleted.
+		// But this pod might have belonged to a Job and the GC removed the reference.
+		if hasJobTrackingFinalizer(pod) {
```
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/controller/job/job_controller.go]: Ah, I think I understand the suggestion now. I added a variable for it.

File: pkg/controller/job/job_controller.go [hunk 6]
```diff
@@ -263,7 +261,12 @@ func (jm *Controller) addPod(obj interface{}) {
 		return
 	}
 
-	// Otherwise, it's an orphan. Get a list of all matching controllers and sync
+	// Otherwise, it's an orphan.
+	// Clean the finalizer.
+	if hasJobTrackingFinalizer(pod) {
+		jm.enqueueOrphanPod(pod)
```
Comment (liggitt) [inline pkg/controller/job/job_controller.go:267]: this is putting the pod into a different queue? will that remove the finalizer even if an ownerRef is added in the meantime by an adoption below?

File: pkg/controller/job/job_controller.go [hunk 7]
```diff
@@ -333,7 +336,12 @@ func (jm *Controller) updatePod(old, cur interface{}) {
 		return
 	}
 
-	// Otherwise, it's an orphan. If anything changed, sync matching controllers
+	// Otherwise, it's an orphan.
+	// Clean the finalizer.
+	if hasJobTrackingFinalizer(curPod) {
+		jm.enqueueOrphanPod(curPod)
```
Comment (liggitt) [inline pkg/controller/job/job_controller.go:342]: same question about async orphan pod handling removing the finalizer even if we add an ownerRef in the meantime?

File: pkg/controller/job/job_controller.go (hunk 6 above)
Comment (alculquicondor) [reply pkg/controller/job/job_controller.go:267]: No, during the sync, we check whether the owner ref and job exists again.

Comment (alculquicondor) [reply pkg/controller/job/job_controller.go:267]: See the update for `syncOrphanPod` below

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/triage accepted
/priority backlog
