### PR TITLE
Surface info of failed plugins during PreFilter, Filter and Permit

### LINKED ISSUE #94009: Avoid moving pods out of unschedulable status unconditionally
Currently we unconditionally move pods out of unschedulable status when an event happens. However, we can optimize this by setting some conditions for each event to avoid unnecessarily doing that:

1) PV, PVC, StorageClass or CSINode add/update: move only pods with a PVC.
2) Service add/update: only if ServiceAffinity plugin is enabled in one of the profiles
3) Node add/update: test the pods against the [kubelet admission logic](https://github.com/kubernetes/kubernetes/blob/3b5aedcef43fa01538518ecbc7de369b27ecd191/pkg/kubelet/lifecycle/predicate.go#L224), this include: NodeAffinity, NodeName NodePorts, NodeResources and TaintsTolerations filters.
4) Pod delete: keep it as is (spreading or affinity constraints must be tested, which is expensive to do)

This is necessary to avoid wasting scheduling cycles.

Related proposal: https://docs.google.com/document/d/1Dw1qPi4eryllSv0F419sKVbGXiPvSv6N_mJd6AVSg74/edit

/sig scheduling
/assign @adtac

### PR DESCRIPTION
**Pull request by Huang-Wei**
**What type of PR is this?**

/kind feature
/sig scheduling

**What this PR does / why we need it**:

Basically when running plugins, the info that records the Pod failed on which plugins gets thrown away, and a high-level `Status` is returned. To resolve #94009, we need to know (1) which plugins are interested in which cluster events, and (2) which plugins a queued Pod failed on. This PR tries to resolve the latter concern.

**Which issue(s) this PR fixes**:

Pre-PR of #94009.

**Special notes for your reviewer**:

This PR only starts with surfacing failed plugins of PreFilter, Filter and Permit, if deem needed, we will extend the scope to other plugins.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/scheduler/core/generic_scheduler.go [hunk 1]
```diff
@@ -140,7 +142,7 @@ func (g *genericScheduler) Schedule(ctx context.Context, fwk framework.Framework
 		return result, ErrNoNodesAvailable
 	}
 
-	feasibleNodes, filteredNodesStatuses, err := g.findNodesThatFitPod(ctx, fwk, state, pod)
+	feasibleNodes, filteredNodesStatuses, failedPlugins, err := g.findNodesThatFitPod(ctx, fwk, state, pod)
```
Comment (chendave) [inline pkg/scheduler/core/generic_scheduler.go:145]: Just a question, can we consolidate the `filteredNodesStatuses` and `failedPlugins` into one struct? so it will tell both the status and failed plugins for each node if the node doesn't fit.

Expose failed plugin is really a good idea, my recent idea to further improve pod preemption may benefit from these information.

Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler.go:145]: It looks good to me. I'm still working in progress, will continue work and see if other semantical similar parts can be consolidated.

**Comment by Huang-Wei** [comment]
/retest

@ahg-g @alculquicondor It's ready for review. This is the first PR to resolve #94009.

File: pkg/scheduler/framework/runtime/framework.go [hunk 2]
```diff
@@ -605,8 +607,9 @@ func (f *frameworkImpl) runPostFilterPlugin(ctx context.Context, pl framework.Po
 // and add the nominated pods. Removal of the victims is done by
 // SelectVictimsOnNode(). Preempt removes victims from PreFilter state and
 // NodeInfo before calling this function.
-func (f *frameworkImpl) RunFilterPluginsWithNominatedPods(ctx context.Context, state *framework.CycleState, pod *v1.Pod, info *framework.NodeInfo) *framework.Status {
+func (f *frameworkImpl) RunFilterPluginsWithNominatedPods(ctx context.Context, state *framework.CycleState, pod *v1.Pod, info *framework.NodeInfo) (*framework.Status, sets.String) {
```
Comment (ahg-g) [inline pkg/scheduler/framework/runtime/framework.go:610]: I don't expect that the plugin that fails in preemption will impact the re-queueing decision, so returning the set of failed plugins isn't necessary.

File: pkg/scheduler/core/generic_scheduler.go (hunk 1 above)
Comment (ahg-g) [reply pkg/scheduler/core/generic_scheduler.go:109]: I think we should add plugin name to status instead of carrying around a set.Strings of failedPlugins.

File: pkg/scheduler/framework/interface.go [hunk 3]
```diff
@@ -187,13 +188,19 @@ type PluginToStatus map[string]*Status
 
 // Merge merges the statuses in the map into one. The resulting status code have the following
 // precedence: Error, UnschedulableAndUnresolvable, Unschedulable.
-func (p PluginToStatus) Merge() *Status {
+// In addition to the merged status, it also returns a string set contains failed plugin names.
+func (p PluginToStatus) Merge() (*Status, sets.String) {
```
Comment (ahg-g) [inline pkg/scheduler/framework/interface.go:192]: If we add plugin name to status, then I would change merge such that the plugin name is the one that determined the code (line 207 below).

File: pkg/scheduler/framework/types.go [hunk 4]
```diff
@@ -96,6 +96,7 @@ type FitError struct {
 	Pod                   *v1.Pod
 	NumAllNodes           int
 	FilteredNodesStatuses NodeToStatusMap
+	FailedPlugins         sets.String
```
Comment (ahg-g) [inline pkg/scheduler/framework/types.go:99]: as mentioned above, lets add PluginName to Status.

File: pkg/scheduler/core/generic_scheduler.go (hunk 1 above)
Comment (chendave) [reply pkg/scheduler/core/generic_scheduler.go:109]: +1

File: pkg/scheduler/framework/runtime/framework.go (hunk 2 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/runtime/framework.go:610]: True, PostFilter don't need to return this. Will update.

File: pkg/scheduler/core/generic_scheduler.go (hunk 1 above)
Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler.go:109]: Actually, the first version I drafted was to embed failedPlugin into status. However, there are several cons:

- it turns out to have to impact a large amount of codebase
- some semantics like `status.merge()` need to revisit

The above aspect turned out to impact a large amount of codebase, and also error-prone. Moreover, it will evictable impact the existing downstream plugins.

Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler.go:109]: (FYI: efforts I tried but gave up: https://github.com/Huang-Wei/kubernetes/commit/0f08c594867049942c64ad437c35e2525da6619a#diff-3a4846227d655e390683e5e53ee7472696f9578dfd998a53393d7e8fc8678af5R107)

File: pkg/scheduler/framework/runtime/framework.go (hunk 2 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/runtime/framework.go:610]: Oh, RunFilterPluginsWithNominatedPods is both used in regular filtering and preemption cases, so it's still necessary to return the failed plugins.

image

Regarding the preemption case, the original FitError that embeds the failed plugins will be used, not the ones returned in the preemption path.

File: pkg/scheduler/framework/interface.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/scheduler/framework/interface.go:192]: One thing to keep in mind: in the scheduler, we generally only have one status, because we break at the first failure.
It's the cluster autoscaler that cares about running all plugins. However, the configuration is available in the policy API. It's not available in component config.

For the purpose of generality, shouldn't we keep all plugins, knowing that generally we only have one?

File: pkg/scheduler/framework/types.go (hunk 4 above)
Comment (alculquicondor) [reply pkg/scheduler/framework/types.go:99]: +1

File: pkg/scheduler/framework/interface.go (hunk 3 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:192]: > we generally only have one status, because we break at the first failure

True for non-Filter plugins. For Filter plugins, if no feasible node is found, we record the failures on each node, and return to generate an aggregated error.

File: pkg/scheduler/framework/types.go (hunk 4 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/types.go:99]: I tried but gave up this idea. Some reason explained in https://github.com/kubernetes/kubernetes/pull/98041#discussion_r561618149.

Another reason is: we're now using `Status` as the output of each extension point, as well as individual plugin. For most of the cases, we can directly use the `Status` returned from plugin as the result of extension point. However, for Filtering it's not the case - we merged N results into one:
 https://github.com/kubernetes/kubernetes/blob/44f8fcfe9482ecd6da7e9e88e0e25387ff2ef7fd/pkg/scheduler/framework/runtime/framework.go#L645

That means if we want to use a single `Status` to fit all cases, we have to embed a `[]Failure` to `Status`, and `Failure` to be a tuple with "reason" and "plugin". So a `Status` can be of 3 different styles:

- `len(failures) == 1` - result of a plugin, also act as result of non-FIlter extension point
- `len(failures) == N` - result of Fitler extension oint
- `len(failures) == 0` - abnormal error

I'm not a fan of this as it hides a lot of implicities inside the code.

And, even we go with this design, we still need to inject that status to FitError (or change the signature of sched.recordSchedulingFailure to accpect a Status).

So after considering all the things mentioned, I think the current approach is cleaner and results in way fewer code changes in both core and downstream. WDYT?

File: pkg/scheduler/framework/interface.go (hunk 3 above)
Comment (alculquicondor) [reply pkg/scheduler/framework/interface.go:192]: But in that case we don't use Merge.
Merge is used for failures on the same Node.

Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:192]: We did use:

https://github.com/kubernetes/kubernetes/blob/44f8fcfe9482ecd6da7e9e88e0e25387ff2ef7fd/pkg/scheduler/framework/runtime/framework.go#L644-L645

Comment (alculquicondor) [reply pkg/scheduler/framework/interface.go:192]: Those are results for one node.

Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:192]: You're right, I misread. Then actually this method only makes sense when `runAllFilters` is true.

**Comment by Huang-Wei** [comment]
I revised this PR to introduce `failedPlugin` to `Status`, it's employed with the following implicit semantics:

- If the code is Error, it's not necessary to include the "failedPlugin" value - as Error stands for an abnormal error, not functional error. Even if "failedPlugin" is specified, it won't be used.
- `Status` returned from PreFilter and Filter extension point is carried with the "failedPlugin"; we _may_ explore to expand to other extension points in the future.
- For backward compatibility, we don't rely on plugin developers to return a `Status` with "failedPlugin" field. The framework fills the "failedPlugin" field when needed.

@ahg-g @alculquicondor @chendave PTAL.

File: pkg/scheduler/core/generic_scheduler_test.go [hunk 5]
```diff
@@ -814,21 +827,25 @@ func TestFindFitAllError(t *testing.T) {
...
-	_, nodeToStatusMap, err := scheduler.findNodesThatFitPod(context.Background(), fwk, framework.NewCycleState(), &v1.Pod{})
+	_, diagnosis, err := scheduler.findNodesThatFitPod(context.Background(), fwk, framework.NewCycleState(), &v1.Pod{})
 
 	if err != nil {
 		t.Errorf("unexpected error: %v", err)
 	}
 
-	if len(nodeToStatusMap) != len(nodes) {
-		t.Errorf("unexpected failed status map: %v", nodeToStatusMap)
+	if len(diagnosis.NodeToStatusMap) != len(nodes) {
```
Comment (alculquicondor) [inline pkg/scheduler/core/generic_scheduler_test.go:836]: can we replace all these lines with a single `cmp.Diff` for diagnosis?

Or is this an instance of #94695?

File: pkg/scheduler/framework/interface.go [hunk 6]
```diff
@@ -199,6 +217,7 @@ func (p PluginToStatus) Merge() *Status {
 		}
 		if statusPrecedence[s.Code()] > statusPrecedence[finalStatus.code] {
 			finalStatus.code = s.Code()
+			finalStatus.failedPlugin = s.FailedPlugin()
```
Comment (alculquicondor) [inline pkg/scheduler/framework/interface.go:220]: Update comment to say that we only keep one that has the most relevant status.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go [hunk 7]
```diff
@@ -223,9 +224,13 @@ func (pl *DefaultPreemption) FindCandidates(ctx context.Context, state *framewor
...
 		return candidates, &framework.FitError{
-			Pod:                   pod,
-			NumAllNodes:           len(potentialNodes),
-			FilteredNodesStatuses: nodeStatuses,
+			Pod:         pod,
+			NumAllNodes: len(potentialNodes),
+			Diagnosis: &framework.Diagnosis{
+				NodeToStatusMap: nodeStatuses,
+				// Set FailedPlugins as empty as it won't be used on moving Pods.
+				FailedPlugins: make(sets.String),
```
Comment (alculquicondor) [inline pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:232]: Can we leave it nil?

File: pkg/scheduler/framework/types.go [hunk 8]
```diff
@@ -93,9 +93,9 @@ type WeightedAffinityTerm struct {
 
 // FitError describes a fit error of a pod.
 type FitError struct {
-	Pod                   *v1.Pod
-	NumAllNodes           int
-	FilteredNodesStatuses NodeToStatusMap
+	Pod         *v1.Pod
+	NumAllNodes int
+	Diagnosis   *Diagnosis
```
Comment (alculquicondor) [inline pkg/scheduler/framework/types.go:98]: this just contains 2 maps, so no need to make this a pointer. Saves one instantiation.

File: pkg/scheduler/framework/interface.go [hunk 9]
```diff
@@ -127,6 +135,16 @@ func (s *Status) Message() string {
 	return strings.Join(s.reasons, ", ")
 }
 
+// FailBy sets the given plugin name to s.failedPlugin.
+func (s *Status) FailBy(plugin string) {
```
Comment (ahg-g) [inline pkg/scheduler/framework/interface.go:139]: SetFailedPlugin is more idiomatic

File: pkg/scheduler/framework/interface.go [hunk 10]
```diff
@@ -106,9 +113,10 @@ const (
 // the reasons should explain why.
 // NOTE: A nil Status is also considered as Success.
 type Status struct {
-	code    Code
-	reasons []string
-	err     error
+	code         Code
+	reasons      []string
+	err          error
+	failedPlugin string
```
Comment (ahg-g) [inline pkg/scheduler/framework/interface.go:119]: can we have a comment documenting the expectations around this field since it may not always be set.

File: pkg/scheduler/framework/interface.go [hunk 11]
```diff
@@ -48,6 +49,12 @@ type PluginToNodeScores map[string]NodeScoreList
 // NodeToStatusMap declares map from node name to its status.
 type NodeToStatusMap map[string]*Status
 
+// Diagnosis records the details to diagnose a scheduling failure.
+type Diagnosis struct {
```
Comment (ahg-g) [inline pkg/scheduler/framework/interface.go:53]: should we have this in types.go with FitError since no framework interface actually return this type.

File: pkg/scheduler/framework/interface.go [hunk 12]
```diff
@@ -48,6 +49,12 @@ type PluginToNodeScores map[string]NodeScoreList
...
+	NodeToStatusMap NodeToStatusMap
+	FailedPlugins   sets.String
```
Comment (ahg-g) [inline pkg/scheduler/framework/interface.go:55]: where is this Set being used? I see it being populated, but not used.

File: pkg/scheduler/framework/runtime/framework.go [hunk 13]
```diff
@@ -429,6 +429,7 @@ func (f *frameworkImpl) RunPreFilterPlugins(ctx context.Context, state *framewor
 	for _, pl := range f.preFilterPlugins {
 		status = f.runPreFilterPlugin(ctx, pl, state, pod)
 		if !status.IsSuccess() {
+			status.FailBy(pl.Name())
```
Comment (ahg-g) [inline pkg/scheduler/framework/runtime/framework.go:432]: for the sake of completion, should we do that for other extension points, especially PostFilter and Premit?

File: pkg/scheduler/core/generic_scheduler_test.go [hunk 14]
```diff
@@ -702,9 +713,11 @@ func TestGenericScheduler(t *testing.T) {
...
 				Pod:         &v1.Pod{ObjectMeta: metav1.ObjectMeta{Name: "test-prefilter", UID: types.UID("test-prefilter")}},
 				NumAllNodes: 2,
-				FilteredNodesStatuses: framework.NodeToStatusMap{
-					"1": framework.NewStatus(framework.UnschedulableAndUnresolvable, "injected unschedulable status"),
-					"2": framework.NewStatus(framework.UnschedulableAndUnresolvable, "injected unschedulable status"),
+				Diagnosis: &framework.Diagnosis{
+					NodeToStatusMap: framework.NodeToStatusMap{
+						"1": framework.NewStatus(framework.UnschedulableAndUnresolvable, "injected unschedulable status"),
+						"2": framework.NewStatus(framework.UnschedulableAndUnresolvable, "injected unschedulable status"),
+					},
```
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler_test.go:720]: It's b/c the status is of type Error, and as I mentioned in https://github.com/kubernetes/kubernetes/pull/98041#issuecomment-765075279, the failedPlugin carried in an Error status won't help in moving pods between queues - Error is interpreted as a fault, not a regular FitError.

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 5 above)
Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler_test.go:836]: I can use `cmd.Diff`. Will update.

File: pkg/scheduler/framework/interface.go (hunk 10 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:119]: ok, will do.

File: pkg/scheduler/framework/interface.go (hunk 11 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:53]: SG.

File: pkg/scheduler/framework/interface.go (hunk 12 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:55]: True, it will be used in the following PR(s).

Upon recordingFailure(), if the error is of type FitError, the FailedPlugins will be injected into PodInfo. Then upon moving pods bwteeen internal queues, we have (1) the triggered cluster events, (2) registered map from event to plugins, and (3) failedPlugins carried by PodInfo. So we're able to tell whether to move a Pod(Info) or not.

Comment (ahg-g) [reply pkg/scheduler/framework/interface.go:55]: ah, but once policy is deprecated (and so the runAllPlugins flag), then we don't really need this because the FailedPlugin in status should suffice.

File: pkg/scheduler/framework/runtime/framework.go (hunk 13 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/runtime/framework.go:432]: For PostFilter, probably no. As it's more reasonable to return the "original" failure (in PreFilter or Filter) and rely upon that to decide moving a Pod or not.

For Permit, I think Permit more fits the coscheduling-like case that may depend on events  of particular custom resource to make it re-schedulable. And right now we're not open on that yet. So my idea was to be conservative until we open the registration for CRD.
However, I'm open to discussion. It seems enabling it is also harmless. It's just we should not wrap the permitStatus as plain error ([1], [2]) - otherwise the failedPlugin info gets lost. WDYT?

[1]: https://github.com/kubernetes/kubernetes/blob/7315c1f6ddf37e41ae7826a042d057d5f594c10c/pkg/scheduler/scheduler.go#L535
[2]: https://github.com/kubernetes/kubernetes/blob/7315c1f6ddf37e41ae7826a042d057d5f594c10c/pkg/scheduler/scheduler.go#L561

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/core/generic_scheduler_test.go:720]: aren't we building a `FitError` here?

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 5 above)
Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler_test.go:836]: Ah hold on, unexported fields are not comparable, I will leave it as is and revisit once a general compared for `Status` in ready.

Comment (alculquicondor) [reply pkg/scheduler/core/generic_scheduler_test.go:836]: That's what I thought. Leaving it for now is fine.

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler_test.go:720]: Ah, it should embed FailedPlugins. (sorry, misread with another test case)

It can pass is b/c the verifying logic is relaxed without checking the FailedPlugins field:

```go
			if err != test.wErr && !strings.Contains(err.Error(), test.wErr.Error()) {
				t.Errorf("Unexpected error: %v, expected: %v", err.Error(), test.wErr)
			}
```

As we have other tests covering the FailedPlugins part, do you prefer to leave it as is, or complement the wantErr obj and the testing logic?

File: pkg/scheduler/core/generic_scheduler.go [hunk 15]
```diff
@@ -198,8 +199,11 @@ func (g *genericScheduler) numFeasibleNodesToFind(numAllNodes int32) (numNodes i
 
 // Filters the nodes to find the ones that fit the pod based on the framework
 // filter plugins and filter extenders.
-func (g *genericScheduler) findNodesThatFitPod(ctx context.Context, fwk framework.Framework, state *framework.CycleState, pod *v1.Pod) ([]*v1.Node, framework.NodeToStatusMap, error) {
-	filteredNodesStatuses := make(framework.NodeToStatusMap)
+func (g *genericScheduler) findNodesThatFitPod(ctx context.Context, fwk framework.Framework, state *framework.CycleState, pod *v1.Pod) ([]*v1.Node, *framework.Diagnosis, error) {
+	diagnosis := &framework.Diagnosis{
+		NodeToStatusMap: make(framework.NodeToStatusMap),
+		FailedPlugins:   make(sets.String),
```
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler.go]: done.

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 5 above)
Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler_test.go:836]: Added a TODO at https://github.com/kubernetes/kubernetes/issues/94696#issuecomment-765701436.

File: pkg/scheduler/framework/interface.go (hunk 6 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:217]: done.

File: pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go (hunk 7 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go]: yes, we can.

File: pkg/scheduler/framework/types.go (hunk 8 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/types.go]: Changed to a value type.

File: pkg/scheduler/framework/interface.go (hunk 9 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go]: Done.

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/core/generic_scheduler_test.go:720]: I prefer we have the FailedPlugins part so that eventually we can move to cmp

[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler_test.go:720]: Fair enough. Let me complement that.

[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler_test.go]: Updated. To ensure correctness, I introduced `reflect.DeepEqual`. I added another TODO in #94696.

File: pkg/scheduler/framework/runtime/framework.go (hunk 13 above)
Comment (ahg-g) [reply pkg/scheduler/framework/runtime/framework.go]: I guess my suggestion is to set the plugin name wherever deterministic, whether or not it will be used downstream is a different discussion. In RunPermitPlugins for example, we return when the first plugin fails, so might as well set the plugin name. For RunPostFilterPlugins this is already done in Merge.

**Review by chendave — COMMENTED** [review]
LGTM otherwise.

File: pkg/scheduler/framework/interface.go (hunk 12 above)
Comment (ahg-g) [reply pkg/scheduler/framework/interface.go]: But then again, runAllPlugins is disabled by default and will eventually get deprecated. I think failedPlugin in status will probably be enough (in the worst case, if runAllPlugins is enabled, then moving pods back to the queue will simply be a little less efficient).

Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go]: Oh, you may misunderstand this: this FaieldPlugins actually is deduced from `NodeToStatusMap` like this:

```golang
for _, status := range nodeToStatusMap
    failedPlugins.Insert(status.FailedPlugin())
```

So its length equals to length of all nodes. No matter runAllPlugins is enabled or not, a single Fitler plugin return one status (for that node).

BTW: another thing I want to mentions is: given we always process one cluster event at a time, so if a Pod failed by multiple plugins (e.g., foo and bar), it's qualified to be moved once an event associated with foo **or** bar is triggered.

File: pkg/scheduler/framework/types.go [hunk 16]
```diff
@@ -106,7 +112,7 @@ const (
 // Error returns detailed information of why the pod failed to fit on each node
 func (f *FitError) Error() string {
 	reasons := make(map[string]int)
-	for _, status := range f.FilteredNodesStatuses {
+	for _, status := range f.Diagnosis.NodeToStatusMap {
```
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/framework/types.go:115]: We have FitError.Error() dumping more readable message, and from that we can tell which plugins failed the Pod, so probably we don't need to dump the failedPlugins again.

(Off the topic: it seems every call to FitError.Error() is iterating NodeToStatusMap, so maybe we should cache the processed msg to make it reusable)

File: pkg/scheduler/framework/interface.go (hunk 12 above)
Comment (ahg-g) [reply pkg/scheduler/framework/interface.go]: Ok, sounds good, sorry I misread the logic.

File: pkg/scheduler/core/generic_scheduler_test.go [hunk 17]
```diff
@@ -768,9 +797,21 @@ func TestGenericScheduler(t *testing.T) {
...
+					fitError.Diagnosis = test.diagnosisFn()
+				}
+			}
+
 			result, err := scheduler.Schedule(ctx, fwk, framework.NewCycleState(), test.pod)
-			if err != test.wErr && !strings.Contains(err.Error(), test.wErr.Error()) {
-				t.Errorf("Unexpected error: %v, expected: %v", err.Error(), test.wErr)
+			if err != test.wErr {
+				gotFitErr, gotOK := err.(*framework.FitError)
+				wantFitErr, wantOK := err.(*framework.FitError)
```
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler_test.go:809]: Thanks for the catch!

File: pkg/scheduler/framework/runtime/framework.go (hunk 13 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/runtime/framework.go]: @ahg-g I added failedPlugin to Permit(). Please take a look.

Given the PermitPlugin may return in the following paths:

1. immediately returned by PermitPlugin
1. timed out by framework
1. rejected by (another) PermitPlugin in subsequent scheduling cycles

we may have to change the interface `Reject(msg)` to `Reject(plugin, msg)` (or probably `Reject(msg, plugin ...string)`, but doesn't make a big difference IMO)

File: pkg/scheduler/framework/interface.go [hunk 18]
```diff
@@ -109,6 +109,10 @@ type Status struct {
 	code    Code
 	reasons []string
 	err     error
+	// failedPlugin is an optional field that records the plugin name a Pod failed by.
```
Comment (chendave) [inline pkg/scheduler/framework/interface.go:112]: update the comments on the `Status` struct to include this new optional field?

File: pkg/scheduler/framework/runtime/framework.go [hunk 19]
```diff
@@ -1028,7 +1032,9 @@ func (f *frameworkImpl) WaitOnPermit(ctx context.Context, pod *v1.Pod) (status *
 		if s.IsUnschedulable() {
 			msg := fmt.Sprintf("pod %q rejected while waiting on permit: %v", pod.Name, s.Message())
 			klog.V(4).Infof(msg)
-			return framework.NewStatus(s.Code(), msg)
+			finalStatus := framework.NewStatus(s.Code(), msg)
```
Comment (ahg-g) [inline pkg/scheduler/framework/runtime/framework.go:1035]: perhaps we should append the reasons we get from `s` instead of overriding it.

File: pkg/scheduler/framework/runtime/framework.go [hunk 20]
```diff
@@ -975,7 +977,9 @@ func (f *frameworkImpl) RunPermitPlugins(ctx context.Context, state *framework.C
 			if status.IsUnschedulable() {
 				msg := fmt.Sprintf("rejected pod %q by permit plugin %q: %v", pod.Name, pl.Name(), status.Message())
 				klog.V(4).Infof(msg)
-				return framework.NewStatus(status.Code(), msg)
+				s := framework.NewStatus(status.Code(), msg)
```
Comment (ahg-g) [inline pkg/scheduler/framework/runtime/framework.go:980]: ditto, we should append the reasons. I think this was implemented before we allowed multiple reasons in status.

File: pkg/scheduler/framework/interface.go [hunk 21]
```diff
@@ -127,6 +131,16 @@ func (s *Status) Message() string {
 	return strings.Join(s.reasons, ", ")
 }
 
+// SetFailedPlugin sets the given plugin name to s.failedPlugin.
+func (s *Status) SetFailedPlugin(plugin string) {
+	s.failedPlugin = plugin
```
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:136]: In theory yes, but in practice it is not that necessary because we don't call this on `nil` or a concrect `Success` status. (If deem needed, it's even more necessary to guard `AppendReason()` than this)

File: pkg/scheduler/framework/interface.go [hunk 22]
```diff
@@ -109,6 +109,10 @@ type Status struct {
 	code    Code
 	reasons []string
 	err     error
+	// failedPlugin is an optional field that records the plugin name a Pod failed by.
+	// It's only set by the framework when a Unschedulable or UnschedulableAndUnresolvable
```
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:113]: I read Error more as an abnormal fault, which is usually not associated with the plugin's semantics, such as "node not found", "internal labelSelector deducing error", etc. So my original idea was that for type of Error, we don't set failedPlugin, so in runtime:

- if a Pod returns error on **all** nodes, its aggregated failedPlugin set is nil, so we move this pod upon any cluster event unconditionally
- if a Pod return non-error on **some** nodes, we intersect the associated plugin name upon a cluster event with those failedPlugins

This may prevent intermittent internal errors from disabling the pod's move. WDYT?

[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/scheduler/framework/interface.go:113]: Just for the sake of separation of concerns, shouldn't the logic receiving the status decide how to deal with different codes?

File: pkg/scheduler/framework/runtime/framework.go (hunk 19 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/runtime/framework.go:1035]: I'm thinking that we can just log the message, and keep the reasons as is. Appending a reason like "reject pod ... by permit plugin" isn't that necessay. WDYT?

Comment (ahg-g) [reply pkg/scheduler/framework/runtime/framework.go:1035]: sounds good

File: pkg/scheduler/framework/interface.go (hunk 22 above)
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:113]: Hmm, even we set failedPlugin upon Error, that info wouldn't be carried all the way to the logic which decides to move pods or not:

Upon an error in (Pre)Filter, diagnosis will be discarded:

```go
	feasibleNodes, diagnosis, err := g.findNodesThatFitPod(ctx, fwk, state, pod)
	if err != nil {
		return result, err
	}
```

Moreover during Filter(), error would be immediately returned once we hit the first Error (other in-parallel FIlter() would cancel()). So even we carry the failedPlugin (on errro) all the way to Pod moving logic, this failedPlugin might be misleading.

File: pkg/scheduler/framework/interface.go (hunk 18 above)
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:112]: done.

File: pkg/scheduler/framework/interface.go (hunk 21 above)
[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/scheduler/framework/interface.go:136]: ok, we can do that as a follow up.

File: pkg/scheduler/framework/interface.go (hunk 22 above)
[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/scheduler/framework/interface.go:113]: But you have access to that when building the "diagnosis". In any case, my point is that "failed" != unschedulable. So  we either include all failure modes, or name the field to indicate its limited scope.

[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/framework/interface.go:113]: > In any case, my point is that "failed" != unschedulable.

That's a fair point. I think I will leave the failedPlugin in Status (more specifically, just Error, Unschedulable and UnschedulableAndUnresolvable, not including Success, Wait and Skip). And in diagnosis, I will rename failedPlugin to unschedulablePlugins.

File: pkg/scheduler/framework/runtime/framework.go (hunk 13 above)
Comment (ahg-g) [reply pkg/scheduler/framework/runtime/framework.go]: thanks.

File: pkg/scheduler/framework/interface.go (hunk 22 above)
[the remark this answers is not in the document]
Comment (ahg-g) [reply pkg/scheduler/framework/interface.go]: changing the name to unschedulablePlugins sounds good to me.

**Comment by ahg-g** [comment]
/lgtm
/approve
/hold

not sure if you are waiting for others, so holding.

**Comment by alculquicondor** [comment]
Giving a quick look after the fire has finished :)

File: pkg/scheduler/framework/interface.go (hunk 10 above)
Comment (alculquicondor) [reply pkg/scheduler/framework/interface.go:114]: should we just name it plugin? Still, with the expectation that it might be empty for Successful status

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (alculquicondor) [reply pkg/scheduler/core/generic_scheduler_test.go:774]: leave a TODO as comment in the code too.

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 5 above)
Comment (alculquicondor) [reply pkg/scheduler/core/generic_scheduler_test.go:897]: leave as comment in code

**Review by alculquicondor — COMMENTED** [review]
Is the PR description outdated? It seems that we did add it to Permit already.

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 14 above)
[the remark this answers is not in the document]
Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler_test.go:774]: Done.

File: pkg/scheduler/core/generic_scheduler_test.go (hunk 5 above)
Comment (Huang-Wei) [reply pkg/scheduler/core/generic_scheduler_test.go:897]: Done.

**Comment by Huang-Wei** [comment]
Thanks @ahg-g @alculquicondor @chendave all for the review!

/hold cancel
/retest
