### PR TITLE
Fix the race check after an overlapping deployment is deleted

### LINKED ISSUE #31502: [k8s.io] Deployment overlapping deployment should not fight with each other {Kubernetes e2e suite}
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/logs/kubernetes-e2e-gke/14117/

Failed: [k8s.io] Deployment overlapping deployment should not fight with each other {Kubernetes e2e suite}

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:91
Aug 26 01:50:15.974: Err : timed out waiting for the condition
. Failed to remove deployment first-deployment pods : &{TypeMeta:{Kind: APIVersion:} ListMeta:{SelfLink:/api/v1/namespaces/e2e-tests-deployment-wri5x/pods ResourceVersion:6932} Items:[{TypeMeta:{Kind: APIVersion:} ObjectMeta:{Name:second-deployment-2592319231-bzl0y GenerateName:second-deployment-2592319231- Namespace:e2e-tests-deployment-wri5x SelfLink:/api/v1/namespaces/e2e-tests-deployment-wri5x/pods/second-deployment-2592319231-bzl0y UID:f68dc8d0-6b69-11e6-9482-42010af00009 ResourceVersion:6137 Generation:0 CreationTimestamp:2016-08-26 01:49:13 -0700 PDT DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[name:redis pod-template-hash:2592319231] Annotations:map[kubernetes.io/created-by:{"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"e2e-tests-deployment-wri5x","name":"second-deployment-2592319231","uid":"f68a09b0-6b69-11e6-9482-42010af00009","apiVersion":"extensions","resourceVersion":"5927"}}
] OwnerReferences:[{APIVersion:extensions/v1beta1 Kind:ReplicaSet Name:second-deployment-2592319231 UID:f68a09b0-6b69-11e6-9482-42010af00009 Controller:0xc8201c295e}] Finalizers:[] ClusterName:} Spec:{Volumes:[{Name:default-token-lsx9v VolumeSource:{HostPath:<nil> EmptyDir:<nil> GCEPersistentDisk:<nil> AWSElasticBlockStore:<nil> GitRepo:<nil> Secret:0xc8208efce0 NFS:<nil> ISCSI:<nil> Glusterfs:<nil> PersistentVolumeClaim:<nil> RBD:<nil> Quobyte:<nil> FlexVolume:<nil> Cinder:<nil> CephFS:<nil> Flocker:<nil> DownwardAPI:<nil> FC:<nil> AzureFile:<nil> ConfigMap:<nil> VsphereVolume:<nil> AzureDisk:<nil>}}] InitContainers:[] Containers:[{Name:nginx Image:gcr.io/google_containers/nginx-slim:0.7 Command:[] Args:[] WorkingDir: Ports:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-lsx9v ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:<nil> ReadinessProbe:<nil> Lifecycle:<nil> TerminationMessagePath:/dev/termination-log ImagePullPolicy:IfNotPresent SecurityContext:<nil> Stdin:false StdinOnce:false TTY:false}] RestartPolicy:Always TerminationGracePeriodSeconds:0xc8201c2aa0 ActiveDeadlineSeconds:<nil> DNSPolicy:ClusterFirst NodeSelector:map[] ServiceAccountName:default NodeName:gke-jenkins-e2e-default-pool-5956466a-jwg0 SecurityContext:0xc8206458c0 ImagePullSecrets:[] Hostname: Subdomain:} Status:{Phase:Running Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-08-26 01:49:13 -0700 PDT Reason: Message:} {Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-08-26 01:49:15 -0700 PDT Reason: Message:} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2016-08-26 01:49:13 -0700 PDT Reason: Message:}] Message: Reason: HostIP:10.240.0.6 PodIP:10.180.0.83 StartTime:2016-08-26 01:49:13 -0700 PDT InitContainerStatuses:[] ContainerStatuses:[{Name:nginx State:{Waiting:<nil> Running:0xc820437c80 Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:true RestartCount:0 Image:gcr.io/google_containers/nginx-slim:0.7 ImageID:docker://sha256:a9bfbd3ba7f240fb561895271c875fe21722d30560e56dbf9598ffde1615d4dc ContainerID:docker://ad9ac6658d9fc363ed8675bd77db00698be2211fef16487ad58ea0bd7f23e62f}]}}]}
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/deployment.go:218
```

### PR DESCRIPTION
**Pull request by janetkuo**
**What this PR does / why we need it**: When deleting deployments in the "overlapping deployment" e2e test, we check that the deployment's RSes & Pods are deleted as well. However, other RSes and Pods (that matches this deployment's selector) may be created by overlapping deployments right after this one is deleted. So when we check that, we should ignore those created by overlapping deployments. 

**Which issue this PR fixes** _(optional, in `fixes #<issue number>(, #<issue_number>, ...)` format, will close that issue when PR gets merged)_: fixes #31502

**Special notes for your reviewer**:

**Release note**:

``` release-note
NONE
```

cc @kubernetes/deployment @pwittrock @kargakis

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes/32004)

### CODE REVIEW

File: test/e2e/deployment.go [hunk 1]
```diff
@@ -202,16 +211,38 @@ func stopDeployment(c *clientset.Clientset, oldC client.Interface, ns, deploymen
 	options := api.ListOptions{LabelSelector: selector}
 	rss, err := c.Extensions().ReplicaSets(ns).List(options)
 	Expect(err).NotTo(HaveOccurred())
-	Expect(rss.Items).Should(HaveLen(0))
+	// RSes may be created by overlapping deployments right after this deployment is deleted, ignore them
+	if len(overlapWith) == 0 {
+		Expect(rss.Items).Should(HaveLen(0))
+	} else {
+		ignoreOverlapRSes := []extensions.ReplicaSet{}
```
Comment (kargakis) [inline test/e2e/deployment.go]: We need a better name for this since these replica sets are not to be ignored. Same comment for pods below.

**Comment by janetkuo** [comment]
@kargakis I renamed `ignoreOverlapRSes` to `noOverlapRSes` (and so as Pods). PTAL

**Comment by kargakis** [comment]
@k8s-bot test this issue: #IGNORE
