### PR TITLE
Do not fail pod status update if failed to get host IP

### LINKED ISSUE #6046: HEAD: regression on updating pod status by kubelet
I suspected this is a regression introduced by #5854.

I observed a pod was restarted and stuck at PENDING phase for a long time (Don't know the reason why it is restarted at the first place, but that is a separate issue)

```
s$ cluster/kubectl.sh describe pods fluentd-to-elasticsearch-kubernetes-minion-p1yo
current-context: "golden-system-455_kubernetes"
Running: cluster/../cluster/gce/../../cluster/../_output/dockerized/bin/linux/amd64/kubectl describe pods fluentd-to-elasticsearch-kubernetes-minion-p1yo
Name:				fluentd-to-elasticsearch-kubernetes-minion-p1yo
Image(s):			kubernetes/fluentd-elasticsearch:1.3
Host:				kubernetes-minion-p1yo.c.golden-system-455.internal/
Labels:				<none>
Status:				Pending
Replication Controllers:	<none>
No events.
``` 

ssh to the machine, I found both containers are running happily on the machine:

```
root@kubernetes-minion-p1yo:/var/log# docker ps | grep 5169eea069716143d0008f516dcbbd78
237c0564dc61        kubernetes/fluentd-elasticsearch:1.3   "\"/bin/sh -c '/usr/   About an hour ago   Up About an hour                        k8s_fluentd-es.2a803504_fluentd-to-elasticsearch-kubernetes-minion-p1yo_default_5169eea069716143d0008f516dcbbd78_16f7e118   
77a783b14630        kubernetes/pause:go                    "/pause"               About an hour ago   Up About an hour                        k8s_POD.7c16d80d_fluentd-to-elasticsearch-kubernetes-minion-p1yo_default_5169eea069716143d0008f516dcbbd78_b720d442          
```

Checked kubelet's log, I found kubelet bailed out on generating PodStatus because the failure of retrieving HostIP:
```
E0327 07:16:33.924668    5671 kubelet.go:1211] Unable to generate status for pod with name "fluentd-to-elasticsearch-kubernetes-minion-p1yo_default" and uid "5169eea069716143d0008f516dcbbd78" info with error(Cannot get host IP: Host IP unknown; known addresses: [])
E0327 07:16:43.916851    5671 kubelet.go:1096] Unable to get pod with name "fluentd-to-elasticsearch-kubernetes-minion-p1yo_default" and uid "5169eea069716143d0008f516dcbbd78" info with error(Cannot get host IP: Host IP unknown; known addresses: [])
E0327 07:16:43.938975    5671 kubelet.go:1211] Unable to generate status for pod with name "fluentd-to-elasticsearch-kubernetes-minion-p1yo_default" and uid "5169eea069716143d0008f516dcbbd78" info with error(Cannot get host IP: Host IP unknown; known addresses: [])
E0327 07:16:53.923361    5671 kubelet.go:1096] Unable to get pod with name "fluentd-to-elasticsearch-kubernetes-minion-p1yo_default" and uid "5169eea069716143d0008f516dcbbd78" info with error(Cannot get host IP: Host IP unknown; known addresses: [])
E0327 07:16:53.943350    5671 kubelet.go:1211] Unable to generate status for pod with name "fluentd-to-elasticsearch-kubernetes-minion-p1yo_default" and uid "5169eea069716143d0008f516dcbbd78" info with error(Cannot get host IP: Host IP unknown; known addresses: [])
E0327 07:17:03.920752    5671 kubelet.go:1096] Unable to get pod with name "fluentd-to-elasticsearch-kubernetes-minion-p1yo_default" and uid "5169eea069716143d0008f516dcbbd78" info with error(Cannot get host IP: Host IP unknown; known addresses: [])
E0327 07:17:03.941227    5671 kubelet.go:1211] Unable to generate status for pod with name "fluentd-to-elasticsearch-kubernetes-minion-p1yo_default" and uid "5169eea069716143d0008f516dcbbd78" info with error(Cannot get host IP: Host IP unknown; known addresses: [])
```

I didn't look into with more detail yet. If no one pick up this tonight, I will take a look tomorrow morning.

### PR DESCRIPTION
**Pull request by fgrzadkowski**
This is similar how it used work in pod_cache.

This fixes #6046

@dchen1107

### CODE REVIEW

**Comment by zmerlynn** [comment]
LGTM

File: pkg/kubelet/kubelet.go [hunk 1]
```diff
@@ -1924,9 +1924,10 @@ func (kl *Kubelet) generatePodStatusByPod(pod *api.Pod) (api.PodStatus, error) {
 	podStatus.Host = kl.GetHostname()
 	hostIP, err := kl.GetHostIP()
 	if err != nil {
-		return api.PodStatus{}, fmt.Errorf("Cannot get host IP: %v", err)
+		glog.Errorf("Cannot get host IP: %v", err)
```
Comment (vmarmol) [inline pkg/kubelet/kubelet.go]: nit: Can specify for what pod?

**Comment by vmarmol** [comment]
LGTM, build is green.
