### PR TITLE
make reapers tolerate 404s on scaling down

### LINKED ISSUE #61748: test-cmd flake: error: could not fetch the scale for replicasets
Start seeing flake in test-cmd deployment tests since 3/26 https://k8s-testgrid.appspot.com/presubmits-kubernetes-blocking#pull-kubernetes-integration

The failure seems related to `scale` subresource?
```
test-cmd run_deployment_tests 26s
go run hack/e2e.go -v --test --test_args='--ginkgo.focus=test\-cmd\srun\_deployment\_tests$'
[...]
error: could not fetch the scale for replicasets.extensions nginx-deployment-747f8b5dd: replicasets/scale.extensions "nginx-deployment-747f8b5dd" not found
!!! [0327 00:27:29] Call tree:
!!! [0327 00:27:29]  1: /go/src/k8s.io/kubernetes/hack/make-rules/../../third_party/forked/shell2junit/sh2ju.sh:47 run_deployment_tests(...)
!!! [0327 00:27:29]  2: /go/src/k8s.io/kubernetes/hack/make-rules/../../third_party/forked/shell2junit/sh2ju.sh:112 eVal(...)
!!! [0327 00:27:29]  3: /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh:107 juLog(...)
!!! [0327 00:27:29]  4: /go/src/k8s.io/kubernetes/hack/make-rules/test-cmd-util.sh:5076 record_command(...)
!!! [0327 00:27:29]  5: hack/make-rules/test-cmd.sh:105 runTests(...)
```
Could #60455 be related?

cc @p0lyn0mial @kubernetes/sig-cli-bugs

### PR DESCRIPTION
**Pull request by deads2k**
fixes https://github.com/kubernetes/kubernetes/issues/61748

This fixes the scale client to return the actual API error, not a wrapped one.  It also updates scalers to do the same.  Then it fixes the reapers to tolerate 404s, since that means they achieved their objective.

/assign @janetkuo 
/assign @p0lyn0mial 

```release-note
NONE
```

### CODE REVIEW

File: pkg/kubectl/delete_test.go [hunk 1]
```diff
@@ -210,54 +210,54 @@ func TestReplicationControllerStop(t *testing.T) {
...
-			}
-		}
-		if test.ScaledDown {
-			scale, err := scaleClient.Scales(ns).Get(schema.GroupResource{Group: "", Resource: "replicationcontrollers"}, name)
-			if err != nil {
-				t.Error(err)
-			}
-			if scale.Spec.Replicas != 0 {
-				t.Errorf("a scale subresource has unexpected number of replicas, got %d expected 0", scale.Spec.Replicas)
+		t.Run(test.Name, func(t *testing.T) {
```
Comment (deads2k) [inline pkg/kubectl/delete_test.go]: Had a test issue and converted this to a table driven test.  Adding `?w=1` to the URL will make the diff easier

File: pkg/kubectl/scale.go [hunk 2]
```diff
@@ -87,30 +87,6 @@ func (pe PreconditionError) Error() string {
...
-
-const (
-	ScaleGetFailure ScaleErrorType = iota
-	ScaleUpdateFailure
-	ScaleUpdateConflictFailure
-)
-
-// A ScaleError is returned when a scale request passes
-// preconditions but fails to actually scale the controller.
-type ScaleError struct {
```
Comment (deads2k) [inline pkg/kubectl/scale.go]: I don't think that this wrapper added value, since we only special cased conflicts, which are easily identifiable.

File: staging/src/k8s.io/client-go/scale/client.go [hunk 3]
```diff
@@ -138,7 +138,7 @@ func (c *namespacedScaleClient) Get(resource schema.GroupResource, name string)
 		SubResource("scale").
 		Do()
 	if err := result.Error(); err != nil {
-		return nil, fmt.Errorf("could not fetch the scale for %s %s: %v", resource.String(), name, err)
```
Comment (deads2k) [inline staging/src/k8s.io/client-go/scale/client.go]: And this wrapping made it impossible to check the error types.  I really dislike golang errors

File: pkg/kubectl/scale.go (hunk 2 above)
Comment (p0lyn0mial) [reply pkg/kubectl/scale.go]: you are absolutely right.

**Comment by p0lyn0mial** [comment]
@deads2k  I really like the changes you have made.

File: pkg/kubectl/delete_test.go (hunk 1 above)
Comment (p0lyn0mial) [reply pkg/kubectl/delete_test.go]: I don't see the change made to the URL.

File: pkg/kubectl/delete.go [hunk 4]
```diff
@@ -368,7 +368,7 @@ func (reaper *JobReaper) Stop(namespace, name string, timeout time.Duration, gra
 	// TODO: handle overlapping jobs
 	retry := NewRetryParams(reaper.pollInterval, reaper.timeout)
 	waitForJobs := NewRetryParams(reaper.pollInterval, timeout)
-	if err = scaler.Scale(namespace, name, 0, nil, retry, waitForJobs); err != nil {
+	if err = scaler.Scale(namespace, name, 0, nil, retry, waitForJobs); err != nil && !errors.IsNotFound(err) {
```
Comment (janetkuo) [inline pkg/kubectl/delete.go]: I think this PR should focus on fixing the flake instead of refactoring Scaler. 

Would you keep the Scaler as-is, and check these returned error the way `DeploymentReaper` does, to see if it fixes the flake?
```go
iscaleGetErr, ok := err.(ScaleError)
if errors.IsNotFound(err) || (ok && errors.IsNotFound(scaleGetErr.ActualError)) {
// ...
```

Making the scale client to return the actual API error can be done in another PR.

**Review by janetkuo — COMMENTED** [review]
Did #60455 cause the flake? If so, why?

File: pkg/kubectl/delete.go (hunk 4 above)
Comment (deads2k) [reply pkg/kubectl/delete.go]: > Would you keep the Scaler as-is, and check these returned error the way DeploymentReaper does, to see if it fixes the flake?

It's actually pretty hard to reason about which places get "normal" errors and which don't.  I ended up doing this after messed up the change a couple times.



> Did #60455 cause the flake? If so, why?

I suspect it originated at the scale client errors instead of the non-scale client errors.

Comment (janetkuo) [reply pkg/kubectl/delete.go]: > It's actually pretty hard to reason about which places get "normal" errors and which don't. I ended up doing this after messed up the change a couple times.

Did you mean the returned error could be a 404, but is neither `errors.IsNotFound` nor `ScaleError`?

Comment (deads2k) [reply pkg/kubectl/delete.go]: > Did you mean the returned error could be a 404, but is neither errors.IsNotFound nor ScaleError?

Yeah.  It was when I started and I started peeling back layers until I found the scale client.

File: pkg/kubectl/delete_test.go (hunk 1 above)
Comment (janetkuo) [reply pkg/kubectl/delete_test.go]: Or just click "Ignore Spaces"

**Review by janetkuo — APPROVED** [review]

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by deads2k** [comment]
It failed on `k8s.io/kubernetes/test/integration/deployment TestDeploymentLabelAdopted`, not on the test-cmd flake

/retest

**Comment by janetkuo** [comment]
LGTM as well
