### PR TITLE
Fix LoadBalancer tests to be provider-agnostic

### LINKED ISSUE #124338: update load balancer e2e tests for legacy CloudProvider removal
Spun off from #122828.

Generic notes:
1. The "ESIPP" tests should be renamed to say "externalTrafficPolicy: Local" or something (AFAICT ESIPP stands for "External Source IP Preservation" but we don't use that acronym anywhere else),
2. Should revisit the use of `[Slow]`, which may not make sense for some of these. In particular, all of the jobs where we are intentionally, explicitly running LB tests (eg, all the ones with cloud-provider-kind) should probably run all of these tests.

----

These tests are GCE-specific and can be deleted:
- `Firewall rule control plane should not expose well-known ports`
  This makes various assertions about what ports in a cluster are accessible from outside the cluster. The specific details here are GCE-specific and this test has nothing to do with sig-network anyway. (Even if we wanted a non-GCE-specific version of this, it would belong to sig-security, not sig-network.)
- `Firewall rule [Slow] [Serial] should create valid firewall rules for LoadBalancer type service`
  Tests GCE-specific details of how cloud LBs are configured
- `Loadbalancing: L7 GCE [Slow] [Feature:NEG] .*`
  Tests GCE-specific "Network Endpoint Group" feature
- `LoadBalancers should be able to create an internal type load balancer [Slow]`
  Tests GCE-specific "internal load balancers"
- `Services GCE [Slow] should be able to create and tear down a standard-tier load balancer [Slow]`
  Tests GCE-specific network tiers feature

----

These tests are currently scheduled to be deleted because they have rules like `SkipUnlessProviderIs("gce", "aws", "azure")`, etc, but they need to be fixed to be "skip unless there is a cloud provider with LoadBalancer support" (cf #123714). (I guess we can probably just do "`[Feature:LoadBalancers]`"?) Although we will run them under cloud-provider-kind in our CI, the tests should also be runnable in other environments, so they should not make any provider-specific assumptions.

- `LoadBalancers should be able to preserve UDP traffic when server pod cycles for a LoadBalancer service on the same nodes`
- `LoadBalancers should not have connectivity disruption during rolling update with externalTrafficPolicy=Cluster [Slow]`
- `LoadBalancers should not have connectivity disruption during rolling update with externalTrafficPolicy=Local [Slow]`
- `LoadBalancers should be able to change the type and ports of a TCP service [Slow]`
  (includes a "bonus" GCE-specific test that can just be removed)
- `LoadBalancers should be able to change the type and ports of a UDP service [Slow]`
  (includes GCE-specific functionality but I think as with the TCP test that is a "bonus" test that can just be removed)
- `LoadBalancers should only allow access from service loadbalancer source ranges [Slow]`
- `LoadBalancers should be able to create LoadBalancer Service without NodePort and change it [Slow]`
- `LoadBalancers should be able to preserve UDP traffic when server pod cycles for a LoadBalancer service on different nodes`
- `LoadBalancers ESIPP [Slow] should work for type=LoadBalancer`
- `LoadBalancers ESIPP [Slow] should work for type=NodePort`
- `LoadBalancers ESIPP [Slow] should only target nodes with endpoints`
- `LoadBalancers ESIPP [Slow] should work from pods`
- `LoadBalancers ESIPP [Slow] should handle updates to ExternalTrafficPolicy field`
- `LoadBalancers should have session affinity work for LoadBalancer service with ESIPP on [Slow] [LinuxOnly]`
- `LoadBalancers should be able to switch session affinity for LoadBalancer service with ESIPP on [Slow] [LinuxOnly]`
- `LoadBalancers should have session affinity work for LoadBalancer service with ESIPP off [Slow] [LinuxOnly]`
- `LoadBalancers should be able to switch session affinity for LoadBalancer service with ESIPP off [Slow] [LinuxOnly]`

---

I'm not sure about these tests:

- `LoadBalancers should handle load balancer cleanup finalizer for service [Slow]`
  Not clear if the use of the `service.kubernetes.io/load-balancer-cleanup` finalizer on LB-type services is actually _required_ (as this test asserts) or merely expected
- `Loadbalancing: L7 GCE [Slow] [Feature:Ingress] should conform to Ingress spec`
  Tests GCE-specific Ingress provider. This is our only test of "ingress actually works". (There is a separate non-provider-specific "the ingress _API_ works" test.) In theory we could write a cloud-provider-kind-specific ingress test, but do we want to? Does SIG Network need to provide anything to allow ingress providers to test for conformance? If so, what? Is Ingress testing something that the Gateway WG is better positioned to handle?

/sig network
/cc @aojea

### PR DESCRIPTION
**Pull request by danwinship**
#### What this PR does / why we need it:
Drops all the provider checks from the LoadBalancer tests and instead just marks them all `[Feature:LoadBalancer]`. We will need corresponding updates in test-infra...

At the moment it doesn't make any attempt to distinguish between what different LoadBalancer-supporting platforms support (#123714). People who want to run them will have to just manually `--ginkgo.skip` the tests they can't pass for now.

(Note: originally this PR was about trying to get the LB tests to pass under cloud-provider-kind, but now it is just about re-enabling them on GCE.)

#### Which issue(s) this PR fixes:
Fixes #124338

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

/kind cleanup
/sig network
/priority important-soon
/assign @aojea

### CODE REVIEW

**Comment by danwinship** [comment]
```
 Summarizing 7 Failures:
  [FAIL] [sig-network] LoadBalancers [Feature:LoadBalancer] [It] should be able to preserve UDP traffic when server pod cycles for a LoadBalancer service on the same nodes [sig-network, Feature:LoadBalancer]
  k8s.io/kubernetes/test/e2e/network/loadbalancer.go:866
  [FAIL] [sig-network] LoadBalancers [Feature:LoadBalancer] [It] should be able to change the type and ports of a UDP service [Slow] [sig-network, Feature:LoadBalancer, Slow]
  k8s.io/kubernetes/test/e2e/network/service.go:591
  [FAIL] [sig-network] LoadBalancers ExternalTrafficPolicy:Local [Feature:LoadBalancer] [Slow] [It] should work for type=LoadBalancer [sig-network, Feature:LoadBalancer, Slow]
  k8s.io/kubernetes/test/e2e/network/loadbalancer.go:990
  [FAIL] [sig-network] LoadBalancers [Feature:LoadBalancer] [It] should be able to preserve UDP traffic when server pod cycles for a LoadBalancer service on different nodes [sig-network, Feature:LoadBalancer]
  k8s.io/kubernetes/test/e2e/network/loadbalancer.go:736
  [FAIL] [sig-network] LoadBalancers [Feature:LoadBalancer] [It] should have session affinity work for LoadBalancer service with Cluster traffic policy [Slow] [LinuxOnly] [sig-network, Feature:LoadBalancer, Slow]
  k8s.io/kubernetes/test/e2e/network/service.go:266
  [FAIL] [sig-network] LoadBalancers [Feature:LoadBalancer] [It] should be able to switch session affinity for LoadBalancer service with Local traffic policy [Slow] [LinuxOnly] [sig-network, Feature:LoadBalancer, Slow]
  k8s.io/kubernetes/test/e2e/network/service.go:266
  [FAIL] [sig-network] LoadBalancers [Feature:LoadBalancer] [It] should be able to switch session affinity for LoadBalancer service with Cluster traffic policy [Slow] [LinuxOnly] [sig-network, Feature:LoadBalancer, Slow]
  k8s.io/kubernetes/test/e2e/network/service.go:266 
```

So all of the UDP LoadBalancer tests failed (which is a known bug, https://github.com/kubernetes-sigs/cloud-provider-kind/issues/58), and most of the SessionAffinity tests. ("should have session affinity work for LoadBalancer service with Local traffic policy" passed, but none of the others did.)

**Comment by danwinship** [comment]
/test pull-kubernetes-e2e-kind-cloud-provider-loadbalancer
seeing if failures are consistent or flakes...

File: test/e2e/network/loadbalancer.go [hunk 1]
```diff
@@ -187,37 +173,8 @@ var _ = common.SIGDescribe("LoadBalancers", func() {
 		framework.ExpectNoError(err)
 
 		// Change the services to LoadBalancer.
-
-		// Here we test that LoadBalancers can receive static IP addresses.  This isn't
-		// necessary, but is an additional feature this monolithic test checks.
```
Comment (aojea) [inline test/e2e/network/loadbalancer.go:192]: this is 😬  thanks for removing it

File: test/e2e/network/loadbalancer.go [hunk 2]
```diff
@@ -377,54 +310,12 @@ var _ = common.SIGDescribe("LoadBalancers", func() {
 		framework.ExpectNoError(err)
 
 		// Change the services to LoadBalancer.
-
-		// Here we test that LoadBalancers can receive static IP addresses.  This isn't
```
Comment (aojea) [inline test/e2e/network/loadbalancer.go:381]: this is clearly copy paste

File: test/e2e/network/loadbalancer.go [hunk 3]
```diff
@@ -141,13 +133,7 @@ var _ = common.SIGDescribe("LoadBalancers", func() {
 	})
 
 	f.It("should be able to change the type and ports of a TCP service", f.WithSlow(), func(ctx context.Context) {
-		// requires cloud load-balancer support
-		e2eskipper.SkipUnlessProviderIs("gce", "gke", "aws")
-
 		loadBalancerLagTimeout := e2eservice.LoadBalancerLagTimeoutDefault
-		if framework.ProviderIs("aws") {
-			loadBalancerLagTimeout = e2eservice.LoadBalancerLagTimeoutAWS
```
Comment (danwinship) [inline test/e2e/network/loadbalancer.go:149]: hm... I guess we should probably use the larger value (TimeoutAWS) rather than the smaller one

**Comment by aojea** [comment]
great, we moved from
```
Kubernetes e2e suite: [It] [sig-network] LoadBalancers [Feature:LoadBalancer] should be able to preserve UDP traffic when server pod cycles for a LoadBalancer service on different nodes expand_more	3m18s
Kubernetes e2e suite: [It] [sig-network] LoadBalancers [Feature:LoadBalancer] should have session affinity work for LoadBalancer service with Cluster traffic policy [Slow] [LinuxOnly] expand_more	10m47s
Kubernetes e2e suite: [It] [sig-network] LoadBalancers ExternalTrafficPolicy:Local [Feature:LoadBalancer] [Slow] should work for type=LoadBalancer expand_more	1m20s
Kubernetes e2e suite: [It] [sig-network] LoadBalancers [Feature:LoadBalancer] should be able to preserve UDP traffic when server pod cycles for a LoadBalancer service on the same nodes expand_more	2m12s
Kubernetes e2e suite: [It] [sig-network] LoadBalancers [Feature:LoadBalancer] should be able to switch session affinity for LoadBalancer service with Local traffic policy [Slow] [LinuxOnly] expand_more	10m13s
Kubernetes e2e suite: [It] [sig-network] LoadBalancers [Feature:LoadBalancer] should be able to change the type and ports of a UDP service [Slow] expand_more	3m46s
Kubernetes e2e suite: [It] [sig-network] LoadBalancers [Feature:LoadBalancer] should be able to switch session affinity for LoadBalancer service with Cluster traffic policy [Slow] [LinuxOnly] expand_more
```

To only
```
Kubernetes e2e suite: [It] [sig-network] LoadBalancers [Feature:LoadBalancer] should be able to change the type and ports of a UDP service [Slow] expand_more	16m19s
Kubernetes e2e suite: [It] [sig-network] LoadBalancers ExternalTrafficPolicy:Local [Feature:LoadBalancer] [Slow] should work for type=LoadBalancer expand_more
```

This will not pass as the loadbalancer is type proxy, so it will always replace the source ip, we may try to use something like this https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_features/ip_transparency#original-source-listener-filter but it may not work in all environments

> Kubernetes e2e suite: [It] [sig-network] LoadBalancers ExternalTrafficPolicy:Local [Feature:LoadBalancer] [Slow] should work for type=LoadBalancer expand_more	


The UDP one fails because is waiting for a rejection and we have discussed the same for TCP, is not clear we can impose this behavior for loadbalancers in general)

https://github.com/kubernetes/kubernetes/blob/4878acc5e58268c2c59054dc25c8f53c6a861501/test/e2e/network/service.go#L609-L621

> [FAILED] UDP service 172.18.0.6:81 not rejected: timed out waiting for the condition

**Comment by aojea** [comment]
with 
```diff
diff --git a/test/e2e/network/loadbalancer.go b/test/e2e/network/loadbalancer.go
index e68e9153d11..08896bbecae 100644
--- a/test/e2e/network/loadbalancer.go
+++ b/test/e2e/network/loadbalancer.go
@@ -495,8 +495,8 @@ var _ = common.SIGDescribe("LoadBalancers", ginkgo.Serial, func() {
                err = udpJig.Scale(ctx, 0)
                framework.ExpectNoError(err)
 
-               ginkgo.By("looking for ICMP REJECT on the UDP service's LoadBalancer")
-               testRejectedUDP(udpIngressIP, svcPort, loadBalancerCreateTimeout)
+               ginkgo.By("UDP service's LoadBalancer should not be reachable")
+               testNotReachableUDP(udpIngressIP, svcPort, loadBalancerCreateTimeout)
 
                ginkgo.By("Scaling the pods to 1")
                err = udpJig.Scale(ctx, 1)
```

for the other test `should work for type=LoadBalancer` we should add a new Label as Feature:LoadbalancerL4 or Layer4 or something that indicates that the loadbalancer provisioned operates at L4

**Comment by danwinship** [comment]
> This will not pass as the loadbalancer is type proxy

The e2e test should check the LoadBalancerStatus and belatedly skip the test in that case. (If either `ingress.IPMode == v1.LoadBalancerIPModeProxy` or `ingress.IP == ""`)

**Comment by aojea** [comment]
great , those two tests that are failing now will be fixed once we make them aware of the proxy mode and we implement that in cloud-provider-kind

> Kubernetes e2e suite: [It] [sig-network] LoadBalancers ExternalTrafficPolicy:Local [Feature:LoadBalancer] [Slow] should work for type=LoadBalancer expand_more	1m32s
> Kubernetes e2e suite: [It] [sig-network] LoadBalancers ExternalTrafficPolicy:Local [Feature:LoadBalancer] [Slow] should handle updates to ExternalTrafficPolicy field expand_more

File: test/e2e/network/loadbalancer.go [hunk 4]
```diff
@@ -1284,6 +968,14 @@ var _ = common.SIGDescribe("LoadBalancers ExternalTrafficPolicy: Local", framewo
 			framework.ExpectNoError(err)
 		})
 
+		// FIXME: figure out the actual expected semantics for
+		// "ExternalTrafficPolicy: Local" + "IPMode: Proxy".
+		// https://issues.k8s.io/123714
+		ingress := &svc.Status.LoadBalancer.Ingress[0]
+		if ingress.IP == "" || (ingress.IPMode != nil && *ingress.IPMode == v1.LoadBalancerIPModeProxy) {
```
Comment (aojea) [inline test/e2e/network/loadbalancer.go:975]: Line 1028 should only do the check if is not proxy ... in that case I dont think we should skip the test though

Comment (aojea) [reply test/e2e/network/loadbalancer.go:975]: Line 1278 hsa another FIXME related

**Comment by aojea** [comment]
> Kubernetes e2e suite: [It] [sig-network] LoadBalancers [Feature:LoadBalancer] should only allow access from service loadbalancer source ranges [Slow]

can it be possible that when setting the proxy mode we are affecting this behavior?

File: test/e2e/network/loadbalancer.go (hunk 4 above)
Comment (danwinship) [reply test/e2e/network/loadbalancer.go:975]: The NodePort test (at line 1028) isn't even using a LoadBalancer service. (Yeah, the test case is in the wrong file.) It's connecting from a pod to a nodeport, so that's just exercising kube-proxy behavior... which we know has to work because otherwise this test wouldn't pass in the gce tests! Not sure what's going on here.

The line 1278 FIXME doesn't affect our CI, but I believe that test case would fail in a cluster running Cilium, because it goes out of its way to preserve the source IP even when it "doesn't have to", https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#client-source-ip-preservation

**Comment by danwinship** [comment]
Another possibility for the flakes is that we're hitting previously-untested kindnet behavior? Like, maybe some of the tests work when the pods are all on the same worker, but not when they're on different workers?

**Comment by aojea** [comment]
/test pull-kubernetes-e2e-kind-cloud-provider-loadbalancer
5 failures now :/

**Comment by dims** [comment]
@danwinship please re-add the entire `test/e2e/network/loadbalancer.go` back in this PR once https://github.com/kubernetes/kubernetes/pull/124519 lands. thanks!

File: test/e2e/network/loadbalancer.go [hunk 5]
```diff
@@ -926,7 +926,7 @@ var _ = common.SIGDescribe("LoadBalancers", feature.LoadBalancer, func() {
 	})
 })
 
-var _ = common.SIGDescribe("LoadBalancers ESIPP", feature.LoadBalancer, framework.WithSlow(), func() {
+var _ = common.SIGDescribe("LoadBalancers ExternalTrafficPolicy: Local", feature.LoadBalancer, framework.WithSlow(), func() {
```
Comment (danwinship) [inline test/e2e/network/loadbalancer.go:929]: (FTR I'm doing this now just to keep all (most?) of the renaming in one PR; I didn't want people updating their CI configs to skip all the "ESIPP" tests and then have us rename them later...)

**Comment by aojea** [comment]
@danwinship linter error

```
{ ScriptError 
test/e2e/network/loadbalancer.go:1453:6: ST1003: var previousHttpErrors should be previousHTTPErrors (stylecheck)
	var previousHttpErrors uint64 = 0
	    ^
test/e2e/network/loadbalancer.go:1500:3: ST1003: var currentHttpErrors should be currentHTTPErrors (stylecheck)
		currentHttpErrors := atomic.LoadUint64(&httpErrors)
		^
test/e2e/network/loadbalancer.go:1504:3: ST1003: var partialHttpErrors should be partialHTTPErrors (stylecheck)
		partialHttpErrors := currentHttpErrors - previousHttpErrors
		^
```

**Comment by danwinship** [comment]
@aojea what are you running the perf test for?
anyway, I think this is ready to merge?

**Comment by aojea** [comment]
> @aojea what are you running the perf test for?

wrong ones sorry, I wanted to check https://github.com/kubernetes/test-infra/pull/32585

/lgtm
/approve

Let's iterate
