### PR TITLE
AWS: Fix suspicious loop comparing permissions

### LINKED ISSUE #36902: Suspicious loop in k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go
Per #36858:

k8s.io/kubernetes/pkg/cloudprovider/providers/aws/aws.go:1923:3: the surrounding loop is unconditionally terminated (SA4004)

It does look very suspicious.

### PR DESCRIPTION
**Pull request by justinsb**
Because we only ever call it with a single UserId/GroupId, this would
not have been a problem in practice, but this fixes the code.

Fix #36902 

```release-note
NONE
```

### CODE REVIEW

**Comment by justinsb** [comment]
@k8s-bot pull-kubernetes-unit test this

File: pkg/cloudprovider/providers/aws/aws.go [hunk 1]
```diff
@@ -2034,13 +2034,18 @@ func ipPermissionExists(newPermission, existing *ec2.IpPermission, compareGroupU
...
+		found := false
 		for _, rightPair := range existing.UserIdGroupPairs {
 			if isEqualUserGroupPair(leftPair, rightPair, compareGroupUserIDs) {
-				return true
+				found = true
+				break
 			}
 		}
-		return false
+		if found == false {
```
Comment (jsafrane) [inline pkg/cloudprovider/providers/aws/aws.go]: I'd prefer `if !found`, it reads more naturally. Otherwise LGTM

Comment (justinsb) [inline pkg/cloudprovider/providers/aws/aws.go]: Agreed & fixed - thank you!

(BTW this isn't urgent because of how we call this, so I've marked it for 1.8)
