### PR TITLE
[kubelet] Allow priority to be set for kubelet process on Windows

### LINKED ISSUE #95735: /stats/summary endpoints failing with "Context Deadline Exceeded" on Windows nodes with very high CPU usage
**What happened**:
Windows nodes running with high (>90%) CPU usage are having calls to /stats/summary time out with "Context Deadline Exceeded".

When this happens metrics-server cannot gather accurate CPU/memory usage for the node or pods running on the node which results in
- HPA not functioning
- `kubectl top node/pod` returning <unknown> instead of values

**What you expected to happen**:
Windows nodes should be able to run with high CPU utilization without negatively impacting Kubernetes functionality

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a cluster with Windows Server 2019 nodes
1. Schedule CPU intensive workloads into cluster
   - ex: https://gist.github.com/marosset/ad8a9769bdbaa5229fb67cf249e2c1ff#file-iis-2019-burn-cpu-yaml
1. Scale workload to put node into high CPU state
1. Query node metrics with `kubectl top node`

**Anything else we need to know?**:
This issue appears to be easier to reproduce on 1.18.x nodes vs 1.16.x or 1.17.x nodes

Ex:
image
 
image

metrics-server logs show
E1020 10:58:24.539304       1 manager.go:111] unable to fully collect metrics: unable to fully scrape metrics from source kubelet_summary:akswin000000: unable to fetch metrics from Kubelet akswin000000 (10.240.0.115): Get https://10.240.0.115:10250/stats/summary?only_cpu_and_memory=true: context deadline exceeded

Kubelet logs show

```
E1002 00:26:59.894818    4680 remote_runtime.go:495] ListContainerStats with filter &ContainerStatsFilter{Id:,PodSandboxId:,LabelSelector:map[string]string{},} 
from runtime service failed: rpc error: code = Unknown desc = operation timeout: context deadline exceeded
```

```
E1002 00:43:44.801208    4680 handler.go:321] HTTP InternalServerError serving /stats/summary: Internal Error: failed to list pod stats: 
failed to list all container stats: rpc error: code = Unknown desc = operation timeout: context deadline exceeded
```

and

```
E1002 00:46:31.844828    4680 remote_runtime.go:495] ListContainerStats with filter &ContainerStatsFilter{Id:,PodSandboxId:,LabelSelector:map[string]string{},} 
from runtime service failed: rpc error: code = Unknown desc = operation timeout: context deadline exceeded
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.8
- Cloud provider or hardware configuration: AKS / Azure
- OS (e.g: `cat /etc/os-release`): WIndows Server 2019
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others: Docker EE version 19.3.11

### PR DESCRIPTION
**Pull request by ravisantoshgudimetla**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Introduce `windows-priorityclass` flag to set priority for the kubelet running on Windows nodes

**Which issue(s) this PR fixes**:

Partially Fixes #95735

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Add a new flag to set priority for the kubelet on Windows nodes so that workloads cannot overwhelm the node there by disrupting kubelet process.
```

**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.**:

```docs
Allow user to specify priority of the kubelet process on Windows nodes.
```

/sig windows
cc @marosset @jsturtevant

### CODE REVIEW

File: cmd/kubelet/app/options/osflags_windows.go [hunk 1]
```diff
@@ -24,4 +24,9 @@ import (
 
 func (f *KubeletFlags) addOSFlags(fs *pflag.FlagSet) {
 	fs.BoolVar(&f.WindowsService, "windows-service", f.WindowsService, "Enable Windows Service Control Manager API integration")
+	// The default priority class associated with any process in Windows is NORMAL_PRIORITY_CLASS. Keeping it as is
+	// to maintain backwards compatibility.
+	// Source: https://docs.microsoft.com/en-us/windows/win32/procthread/scheduling-priorities
+	fs.StringVar(&f.WindowsPriorityClass, "windows-priorityclass", "NORMAL_PRIORITY_CLASS",
+		"Set the PriorityClass associated with kubelet process")
```
Comment (jsturtevant) [inline cmd/kubelet/app/options/osflags_windows.go:31]: Could we give a pointer the available options?

**Comment by jsturtevant** [comment]
We should also add some documentation to [Windows docs](https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/) on how/why

**Comment by michmike** [comment]
Agree on the docs need asked by James. @ravisantoshgudimetla  can you also please add a small section, possibly under https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#memory-reservations-and-handling

**Comment by ravisantoshgudimetla** [comment]
Before this change:

```
gps | where {$_.name -eq 'kubelet'} | select name, priorityclass                                      
                                                                                                                                 
Name    PriorityClass                                                                                                            
----    -------------                                                                                                            
kubelet        Normal
```

After this change:
```
gps | where {$_.name -eq 'kubelet'} | select name, priorityclass                                      
                                                                                                                                 
Name    PriorityClass                                                                                                            
----    -------------                                                                                                            
kubelet   AboveNormal 
```

File: cmd/kubelet/app/options/osflags_windows.go (hunk 1 above)
Comment (ravisantoshgudimetla) [reply cmd/kubelet/app/options/osflags_windows.go]: Done

**Comment by ravisantoshgudimetla** [comment]
failure seems unrelated

/test pull-kubernetes-e2e-azure-disk-windows

**Comment by ravisantoshgudimetla** [comment]
Docs PR: https://github.com/kubernetes/website/pull/24843

**Review by ravisantoshgudimetla — COMMENTED** [review]
@jsturtevant and @michmike - Thank you for the reviews. I've updated the PR with changes suggested by you and opened a docs PR. PTAL

File: cmd/kubelet/app/init_windows.go [hunk 2]
```diff
@@ -19,14 +19,42 @@ limitations under the License.
...
+	return priorityClassMap[priorityClassName]
+}
+
+func initForOS(windowsService bool, windowsPriorityClass string) error {
+	priority := getPriorityValue(windowsPriorityClass)
+	if priority == 0 {
+		return fmt.Errorf("unknown priority class %s, valid ones are available at "+
+			"https://docs.microsoft.com/en-us/windows/win32/procthread/scheduling-priorities", windowsPriorityClass)
+	}
+	kubeletProcessHandle := windows.CurrentProcess()
```
Comment (marosset) [inline cmd/kubelet/app/init_windows.go:52]: Can we add an INFO log statement before calling SetPriorityClass?

**Review by marosset — COMMENTED** [review]
LGTM - added a comment for including a lot statement

File: cmd/kubelet/app/options/osflags_windows.go [hunk 3]
```diff
@@ -24,4 +24,10 @@ import (
 
 func (f *KubeletFlags) addOSFlags(fs *pflag.FlagSet) {
 	fs.BoolVar(&f.WindowsService, "windows-service", f.WindowsService, "Enable Windows Service Control Manager API integration")
+	// The default priority class associated with any process in Windows is NORMAL_PRIORITY_CLASS. Keeping it as is
+	// to maintain backwards compatibility.
+	// Source: https://docs.microsoft.com/en-us/windows/win32/procthread/scheduling-priorities
+	fs.StringVar(&f.WindowsPriorityClass, "windows-priorityclass", "NORMAL_PRIORITY_CLASS",
+		"Set the PriorityClass associated with kubelet process, the default ones are available at"+
```
Comment (jsturtevant) [inline cmd/kubelet/app/options/osflags_windows.go:31]:
```suggestion
		"Set the PriorityClass associated with kubelet process, the default ones are available at "+
```

File: cmd/kubelet/app/init_windows.go (hunk 2 above)
Comment (ravisantoshgudimetla) [reply cmd/kubelet/app/init_windows.go:52]: Done.

**Comment by ravisantoshgudimetla** [comment]
@marosset and @jsturtevant updated the PR, ptal.

File: cmd/kubelet/app/init_windows.go [hunk 4]
```diff
@@ -19,14 +19,44 @@ limitations under the License.
...
 )
 
-func initForOS(windowsService bool) error {
+// getPriorityValue returns the value associated with a Windows process priorityClass
+// Ref: https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/setpriority-method-in-class-win32-process
+func getPriorityValue(priorityClassName string) uint32 {
+	var priorityClassMap = map[string]uint32{
+		"IDLE_PRIORITY_CLASS":         uint32(64),
+		"BELOW_NORMAL_PRIORITY_CLASS": uint32(16384),
+		"NORMAL_PRIORITY_CLASS":       uint32(32),
```
Comment (derekwaynecarr) [inline cmd/kubelet/app/init_windows.go:39]: if i understand correctly, the preference is to have normal/above/high, but its not clear that there is an actual use case for below normal or idle or real time.  how are priority classes used by the containers themselves on windows?  are users able to define an associated priority or is it inferred?

File: cmd/kubelet/app/options/osflags_windows.go [hunk 5]
```diff
@@ -24,4 +24,10 @@ import (
 
 func (f *KubeletFlags) addOSFlags(fs *pflag.FlagSet) {
 	fs.BoolVar(&f.WindowsService, "windows-service", f.WindowsService, "Enable Windows Service Control Manager API integration")
+	// The default priority class associated with any process in Windows is NORMAL_PRIORITY_CLASS. Keeping it as is
+	// to maintain backwards compatibility.
+	// Source: https://docs.microsoft.com/en-us/windows/win32/procthread/scheduling-priorities
+	fs.StringVar(&f.WindowsPriorityClass, "windows-priorityclass", "NORMAL_PRIORITY_CLASS",
```
Comment (derekwaynecarr) [inline cmd/kubelet/app/options/osflags_windows.go:30]: this is fine for windows, i wonder if it would help to correlate the priority class of actual end-user workloads themselves so users can make an informed choice?  for example, 'the default priority class on windows containers is X and could be elevated or altered via Y'?

**Review by derekwaynecarr — APPROVED** [review]
i am fine with the change, i think our user doc should give a stronger recommendation on what priority class to assign relative to end-user workloads.

/approve
/lgtm

File: cmd/kubelet/app/init_windows.go (hunk 4 above)
Comment (ravisantoshgudimetla) [reply cmd/kubelet/app/init_windows.go:39]: >  how are priority classes used by the containers themselves on windows? are users able to define an associated priority or is it inferred?

Nope, it is always the default which is `Normal`

File: cmd/kubelet/app/options/osflags_windows.go (hunk 5 above)
Comment (ravisantoshgudimetla) [reply cmd/kubelet/app/options/osflags_windows.go:30]: As of now, I don't think we have a mechanism to surface the priority class of a process(container) on Windows node to end user. 

`'the default priority class on windows containers is X and could be elevated or altered via Y'?`

The only field I can think of in the pod spec is pod's priority class to express it, there are multiple ways to  modify the priority on the node but I am not sure if we need it at the moment unless you've a use-case in mind.
