### PR TITLE
Appended OS's environment variables to the ones configured in Credent…

### LINKED ISSUE #102750: CredentialProvider fails to read environment variable passed into the CredentialProviderConfig file
#### What happened:
I am attempting to pull an image from ECR using the new kubelet image credential provider feature which is an alpha features in Kubernetes v1.20. My CredentialProviderConfig file includes the environment variable AWS_PROFILE which resides in the default (~/.aws) directory. The profile references a `credential_process` which allows me to execute a binary that returns a set of temporary AWS credentials. When I try running a pod with a container from ECR, I see the following errors in the kubelet logs: 

```
Jun 09 21:47:05 ecr-kubelet-worker kubelet[225990]: E0609 21:47:05.229849  225990 plugin.go:198] Failed getting credential from external registry credential provider: error execing credential provider plugin ecr-credential-provider for image 820537372947.dkr.ecr.us-east-1.amazonaws.com/cats: exit status 1
Jun 09 21:47:05 ecr-kubelet-worker kubelet[225990]: E0609 21:47:05.597552  225990 remote_image.go:113] PullImage "820537372947.dkr.ecr.us-east-1.amazonaws.com/cats:v2" from image service failed: rpc error: code = Unknown desc = failed to pull and unpack image "820537372947.dkr.ecr.us-east-1.amazonaws.com/cats:v2": failed to resolve reference "820537372947.dkr.ecr.us-east-1.amazonaws.com/cats:v2": unexpected status code [manifests v2]: 401 Unauthorized
```

However, when I type the following into the command line on the kubelet: 

```
echo '{"kind": "CredentialProviderRequest", "apiVersion": "credentialprovider.kubelet.k8s.io/v1alpha1", "image": "820537372947.dkr.ecr.us-east-1.amazonaws.com/cats:v2"}' | AWS_PROFILE=default /usr/local/kubelet/bin/ecr-credential-provider get-credentials
```

I get the following response: 

```
{"kind":"CredentialProviderResponse","apiVersion":"credentialprovider.kubelet.k8s.io/v1alpha1","cacheKeyType":"Registry","cacheDuration":"21.6µs","auth":{"820537372947.dkr.ecr.us-east-1.amazonaws.com":{"username":"AWS","password":"eyJwYXlsb2FkIjoiak1RV0pidXpzVnRDd28wNHExdmlScmlwaVRLd3BOc25hejFlUktxVDlBOWZES0FVTjlsbkozSGl0TGh4OHhnejViU0xrRncxNGtaU3htd2R6Rks3MHNCd2FRL0M3eWdtSlVueGNrZGI0eWFjZUhIQ1NSbVZyMjNHam9VOE1yTjJadDdNUnprK0c0RzVWdmYrMVhjODdKdHhFNEZOTWU1dytoSjFRZXYydTlaNXBCVExhTHdaRDNxT0t4dk1aTi9iK0E5Vys2ajI0L1kxUGxER2wybnpoSWxDdFV3aXBxTDhaTS9MdzFwT1RmYmY1eXp6OFIxVDd0MUZvbER3SWVKNUNzQkZBQWZJanNITmpES2tTL3dYdXVlMDBOZGZNeVo2UHlPMjlVanBLdGdqMU8vZTBwZ0J4SzRGelpRVldROHE5Wk1paWtFL3BxRXMvZzN0WXNJcDhTalR6RkZqTys4UVB4WVdFZ2ZrVDFRcjZnbmtrOXZLRkdOSGd6SEV3Z0JMNUJQeDFReXpTSGJyNmlPMDd2Sjh1QzE3eHpITEZwcmpuR3o3T3AyQ1U3SFYydjVwSjdlNFM1d0Qrenljbk5NZFVabjBsQ2dzdlBpUGtuYkV5Rk1lZ050Y3dmM3JKdnNkSm5FZ3IrVGowTTlsdktTWHJBL3hGVW9vZXFQRFhQY2t4SlN6eXM2dkYvZGdXbWJZcXJPTW1jdnBaZ3VpUVo3aTF0NnZncEVIcUQ1RzIzbyt2UnlzQ1FjOElTNVRHVk1peDhGdXp1UjkyT0djbnhIVm85U0gzdWhVL096clZKdWJQQTdFcGJHTjJCM2lFUTFsaHBGeXdvdGtyNit2dFhvU01GSFBFeXFKQ2syL0VWTmphWi9Vb05ZS3JrL3hZYmJPS29UQmlpNUFrTkZDcE9IU1BqM1JVTHpQcXhJVCtPM2tkZ3ZwZ0RMSTI1c3AvYVVUV0Fpd21KYm5BZTFTR1RrdTcyOUk1cVY0bkxVdWtzK2Y0OEJqUlNXUlI0YWlqZnIxbFpLczBLRnlFTk16WkJvbGdBYWZMV01NNnEwaXlMd1Nzc1pJK2xPYmgxU3JUa3IwRFpYRDR4N05QQlN4RTByU1FmSDdzR1M3Y3VLbG85cUUrVDBMSGhxbE0velU1eDU2aTN5MkhZYnV5RDRlSHVvd1F5dVh6UTFRSXRhZDF3Q0U1blJCWjlOU1o1VDE1R1ZheklDcVFCbmFIaFl4WnZqemZuVm1vU1JrL0d1LzFESFU1c2c5U3Z0SXBkL0hXeFkxNXBTQk9nUHNaK2c5WTdOSXAyYXRHNEg0Qmh0eU40T215bm5VaGFOQjZPZU0xV3l3VFY1dXh5cHhINXk3STJwYkE4MDVMR1U4cGNzMGNvTU5Kbmdpam5aRGhzVDRhMisrS3F5d0VPaVpkZ29JZ0ZPdnFwWnIycEVuZlo2MUlEN2pjbjgwR0tMUExvalEzVGV4bjhtVFNINjhzS1l5ZHlyZGJ0MDg0bXZUbjEvNE1PeW9yOUVYeU9qMzY4UzZ2Sno1YmQ4dSsxc1Fva2lBb3FkNkIyWndLYm1QSWx4T0h6bVl1a3N6UGxnWDA1NFNQVUNNSGJJTjJacncxTmJIb3V1UXU1WFVjeGZPR2diK0g1bnBIL1VvTzJFdmR2T29TOWNlczBjMkNDU2hKbHY4MVE4ZUhGRExGRS9tajJaVkF6aFN1RXhsbTcvazlHaVJ0bW9JS3VISFBzRUhDVTRsQTBWVk1HNG44SFpEY1A3bWNrTTRCTS9ibmZTVXNabUc0ZjFEK29WdmpGQS9oWTQ3R0JrQmpVNGJ3OFRoeXprOXFxL2MxbE9tWDc4QllwUDRuMmdKbGd5M0wzcnFTMFBMc2xkNHZzZUFFSWRML29XdjlqZ2FWYjM4bHJuaEdHeTFXc09hOVJDWFMvWTRrc25vRGtnaHVmd1hGcHQveWE0d1VMcUtRL1d3bTZyZ2R0TEdGb3dPbERPOHY1cnZZWDY4WVNOSzFrcEJTcXZoak5haG5ZQU1pNEFrOXVGVFVqaDRDQmFLVTg4OFVYdUFBNERNbktMWEk0a29HK3pGK2ZVYVljOW52Vmo2dDZVdzFaQjFKTm5vNG00b1ZIUlo4U1E5c2g0Z2U3bFd4b2FiZVZxWDE0N0k4T0orZDV1L2g1MHdmWkRQT3AzZXViKzJzR28wZEl3SE5jM1lxREpBd0szSmltdFozakVJYldodmJzWUZUZzlFMkk5OUJqQ2ZnSWx6c092eXlxMXV2RW9DZ0RMN3ZySWI4amFaQWtsSDJWelQ5RUNzU3REc2J2K3ZuaGg4K2VaK2hnRzVOQXV2ZTRWL2NMVjZOL01KbzVadU1vMEg0THZyTnVRVDNXVlIzZjBqYnZlVmMrT2tyZWQxdEFOczdCUGJFdUlCZE5VaURMSmNpWkFJb3J6aGkvaDZxU3EzUE9Jc1pSencvczVBOCt0NERNQlptYXRsbDFZekJYV2EvN3pxbGVpZWlod01XU2ZqWUpDOTRVa1l1c3hkbjZCclJWVzhKNDdscHNqUVlNbG96V01raWRPalpIWUJqc0hVRXpVSytFdTdyQjQ2eDF6U2RkYSs5a3hZY0tXS1UxOUtKWTVQUTVUd1dVRXZKbXJna3dwZjdjZWRhTzFtWUwvZEpMK2ZMOFA4M09jMDJxSXJ0MzFRQUZRNGRmOFNkcmxCQVp4MExCQVdtTU0vd0RPTTJMNXlFckI0cVNTRXEvbHo4Rnc5RWFFTll3UW93N2hDQzFIRXZJSzZUWTQ1YXBZZU55clZ6UzFUUTJjSkVRWi9ZUGFlUVNFZVE1UEVnRkxpQ3RmdEhnPT0iLCJkYXRha2V5IjoiQVFFQkFIaHdtMFlhSVNKZVJ0Sm01bjFHNnVxZWVrWHVvWFhQZTVVRmNlOVJxOC8xNHdBQUFINHdmQVlKS29aSWh2Y05BUWNHb0c4d2JRSUJBREJvQmdrcWhraUc5dzBCQndFd0hnWUpZSVpJQVdVREJBRXVNQkVFRExzbWJPRldpeXcxbkhEVEVnSUJFSUE3RFVyUmcwd1ZWRlB4OFpGbkdQdkNGTVUwM21zQjZNTVZESUg5TnJLejN3Uy84L0NFZFQydy9RbEo4S1piaG1YNmlwdTl6RmNZdEQvOGFhRT0iLCJ2ZXJzaW9uIjoiMiIsInR5cGUiOiJEQVRBX0tFWSIsImV4cGlyYXRpb24iOjE2MjMzMTg2MTl9"}}}
```

It doesn't appear the environment variables in my Config are being passed to the Kubelet when it executes the ecr-credential-provider binary. 

Below is Config file: 

```
kind: CredentialProviderConfig
apiVersion: kubelet.config.k8s.io/v1alpha1
providers:
  - name: ecr-credential-provider
    matchImages:
    - "*.dkr.ecr.*.amazonaws.com"
    defaultCacheDuration: "12h"
    apiVersion: credentialprovider.kubelet.k8s.io/v1alpha1
    args:
     - get-credentials
    env:
    - name: "AWS_PROFILE"
      value: "default"
```

#### What you expected to happen:
I expect for the Kubelet to pass the environment variables in the Config file when it executes the ecr-credential-provider binary. 

#### How to reproduce it (as minimally and precisely as possible):
I am using KinD to test this feature. Here is my config: 

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
runtimeConfig:
  "api/alpha": "true"
name: ecr-kubelet
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer: 
      extraArgs:
        feature-gates: 'KubeletCredentialProviders=true'
  image: kindest/node:v1.20.7@sha256:e645428988191fc824529fd0bb5c94244c12401cf5f5ea3bd875eb0a787f0fe9
- role: worker
  image: kindest/node:v1.20.7@sha256:e645428988191fc824529fd0bb5c94244c12401cf5f5ea3bd875eb0a787f0fe9
  extraMounts:
  - hostPath: /Users/jicowan/go/bin
    containerPath: /usr/local/kubelet/bin
  - hostPath: /Users/jicowan/conf
    containerPath: /usr/local/kubelet/config
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration: 
      kubeletExtraArgs: 
        feature-gates: 'KubeletCredentialProviders=true'
        image-credential-provider-config: '/usr/local/kubelet/config/ecr.conf'
        image-credential-provider-bin-dir: '/usr/local/kubelet/bin/'
```

#### Anything else we need to know?:
No 

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration: None
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.10
- Kernel (e.g. `uname -a`): 5.10
- Install tools: KinD
- Network plugin and version (if this is a network-related bug):
- Others:

cc @ayberk @andrewsykim

### PR DESCRIPTION
**Pull request by n4j**
1. Appended OS's environment variables with the ones provided in the Credential Provider Config file
2. Wrote UnitTest cases to validate the above behaviour

#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
According to the behaviour described in the `kubelete-credential-provider` [documentation](https://kubernetes.io/docs/tasks/kubelet-credential-provider/kubelet-credential-provider/#configure-a-kubelet-credential-provider), the environment variables provided in the config file should be appended with the OS env vars.

However, this seems to be a missed out case and credential providers may fail to execute if `$PATH` and `$HOME` are missing.

This bug was verified for `ecr-credential-provider`

#### Which issue(s) this PR fixes:

Fixes https://github.com/kubernetes/kubernetes/issues/102750

#### Does this PR introduce a user-facing change?

```release-note
Fixed an issue which didn't append OS's environment variables with the one provided in Credential Provider Config file, which may lead to failed execution of external credential provider binary. 
See https://github.com/kubernetes/kubernetes/issues/102750
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

File: pkg/credentialprovider/plugin/config.go [hunk 1]
```diff
@@ -126,3 +137,54 @@ func validateCredentialProviderConfig(config *kubeletconfig.CredentialProviderCo
...
 	return allErrs
 }
+
+// appendSystemEnvVars appends provided array of strings of environment variables in the form of KEY=VALUE
+// with the env vars present in the config
+func appendSystemEnvVars(systemEnvVars []string, config *config.CredentialProvider) {
+	if config == nil {
+		return
+	}
+	configEnvVarNames := getEnvVarKeys(config.Env)
```
Comment (MorrisLaw) [inline pkg/credentialprovider/plugin/config.go:147]: Can config.Env ever be nil? Should that be checked?

Comment (n4j) [reply pkg/credentialprovider/plugin/config.go:147]: Hello @MorrisLaw , Thanks for taking out time to review this PR. 

Yes `config.Env` can be `nil` however `getEnvVarKeys` would return an empty map in that case and I verified that the final result would be that `CredentialProviderConfig` would only have system env vars.

Apparently, calling range on `nil` map results in an empty iteration - https://play.golang.org/p/jvhzUKKwMCO

Though I am prepared to check for `nil` in order to prevent code smell

**Comment by n4j** [comment]
triage/accepted

File: pkg/credentialprovider/plugin/config.go (hunk 1 above)
Comment (MorrisLaw) [reply pkg/credentialprovider/plugin/config.go:147]: Thanks for looking into that. It’s always good to confirm 😄 But yeah your approach seems reasonable 👍🏽

File: pkg/credentialprovider/plugin/config.go [hunk 2]
```diff
@@ -43,6 +45,15 @@ func readCredentialProviderConfigFile(configPath string) (*kubeletconfig.Credent
 		return nil, fmt.Errorf("error decoding config %s: %w", configPath, err)
 	}
 
+	// Append current system environment variables, to the ones configured in the
```
Comment (adisky) [inline pkg/credentialprovider/plugin/config.go:48]: Config file is read during registration of credential providers i.e during Kubelet start, any changes later to OS env variable will not be picked by exec plugin during execution, any reasons to not to do it at original place? https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/plugin/plugin.go#L348

Comment (n4j) [reply pkg/credentialprovider/plugin/config.go:48]: @adisky Sure makes sense, though my rationale was providing a `CredentialProviderConfig` is the job of `readCredentialProviderConfigFile` and all other functions are consumers of it.

If I am appending env vars in the `ExecPlugin` function then it's implied that `ExecPlugin` knows that env vars could be stale and this breaks the abstraction between `ExecPlugin` and `readCredentialProviderConfigFile`

At the moment, `ExecPlugin` does is just take the env vars present in the `CredentialProviderConfig` and execute it and I didn't want to break this contract.

I'll wait for the feedback from the other reviewers and if general consensus is to move it to `ExecPlugin` to inject latest env vars without having to perform a restart of the kubelet then I'll do it.

**Comment by n4j** [comment]
@thockin @smarterclayton Can anyone of you guys review this PR?

**Comment by n4j** [comment]
@adisky Can you accept the triage on this PR?

File: pkg/credentialprovider/plugin/config.go (hunk 2 above)
Comment (adisky) [reply pkg/credentialprovider/plugin/config.go:48]: @n4j I don't have any hard views here, was interested in rationale behind doing it here.

File: pkg/credentialprovider/plugin/config.go [hunk 3]
```diff
@@ -43,6 +45,15 @@ func readCredentialProviderConfigFile(configPath string) (*kubeletconfig.Credent
...
+	// credential provider file. Failing to do so may result in unsuccessful execution
+	// of the provider binary, see https://github.com/kubernetes/kubernetes/issues/102750
+	// Also, this behaviour is inline with Credential Provider Config spec
+	systemEnvVars := os.Environ()
```
Comment (andrewsykim) [inline pkg/credentialprovider/plugin/config.go:52]: Should we instead call `os.Environ()` and append it to `cmd.Env` at runtime instead of at start up? 

https://github.com/kubernetes/kubernetes/blob/9c7434bc4f30761cd679b96fd818aa68a9727d5d/pkg/credentialprovider/plugin/plugin.go#L348-L351

Comment (andrewsykim) [reply pkg/credentialprovider/plugin/config.go:52]: I'm guessing we're calling it at startup so it only needs to be loaded once?

Comment (n4j) [reply pkg/credentialprovider/plugin/config.go:52]: > @adisky Sure makes sense and I was under a dilemma of doing it in `ExecPlugin` v/s `readCredentialProviderConfigFile` and I was hoping to get some feedback on it. 
> 
> 
> 
> My rationale was providing a `CredentialProviderConfig` is the job of `readCredentialProviderConfigFile` and all other functions are consumers of it.
> 
> 
> 
> If I am appending env vars in the `ExecPlugin` function then it's implied that `ExecPlugin` knows that env vars could be stale and this breaks the abstraction between `ExecPlugin` and `readCredentialProviderConfigFile`
> 
> 
> 
> At the moment, `ExecPlugin` does is just take the env vars present in the `CredentialProviderConfig` and execute it and I didn't want to break this contract.
> 
> 
> 
> I'll wait for the feedback from the other reviewers and if general consensus is to move it to `ExecPlugin` to inject latest env vars without having to perform a restart of the kubelet then I'll do it.

@andrewsykim Above is my reason for putting it in readCredentialProviderConfigFile let me know your thoughts on this?

Comment (andrewsykim) [reply pkg/credentialprovider/plugin/config.go:52]: > At the moment, ExecPlugin does is just take the env vars present in the CredentialProviderConfig and execute it and I didn't want to break this contract.

Automatically injecting env vars into at start up has the equally suprising effect I think. From the consumer's perpective it is the same because it wasn't initially defined in `CredentialProviderConfig`. 

I'm personally on the fence about whether inheriting all of kubelet's env vars is the right approach, as opposed to requiring `CredentialProviderConfig` to explicitly set all the required values. Will think about this some more

Comment (n4j) [reply pkg/credentialprovider/plugin/config.go:52]: @andrewsykim I believe the behaviour of unioning system's env vars with config provided env var is part of the publicly documented [spec](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/types.go#L556) and there has to be some thought process in place behind this decision.

To make things more transparent I can log the env vars which are being passed to the credential binary and maybe I can even differentiate between system vars and config vars, this should help in troubleshooting if required.

Moreover, in my implementation config provided env vars always take priority over system provided ones giving a level of control to the end user

If it makes sense then you and I can have an offline discussion about it :)

Comment (andrewsykim) [reply pkg/credentialprovider/plugin/config.go:52]: > To make things more transparent I can log the env vars which are being passed to the credential binary and maybe I can even differentiate between system vars and config vars, this should help in troubleshooting if required.

This can be dangerous too since we can end up logging credentials.

> @andrewsykim I believe the behaviour of unioning system's env vars with config provided env var is part of the publicly documented spec and there has to be some thought process in place behind this decision.

This is fair, but the API is also alpha right now so we _can_ still change it.

Comment (n4j) [reply pkg/credentialprovider/plugin/config.go:52]: @andrewsykim Makes sense.

Do you want some time to think over the approach of unioning the vars?

One solution which I can see to handle issues like #102750 is to maybe only pass HOME and PATH env vars and document this behaviour.

Comment (n4j) [reply pkg/credentialprovider/plugin/config.go:52]: Hello @andrewsykim did you get a chance to look at the above?

Comment (n4j) [reply pkg/credentialprovider/plugin/config.go:52]: @andrewsykim Did you get a chance to look at the above comments?

Comment (andrewsykim) [reply pkg/credentialprovider/plugin/config.go:52]: Since we're likely not going to be promoting this feature to Beta this release I think we should defer this for v1.23 and revisit for Beta. Thoughts @adisky ?

**Comment by dims** [comment]
cc @deads2k @liggitt

@n4j cc'ing approvers from this directory, though to be fair, i did not assign to them as there is existing comments that this should wait for 1.23 ( https://github.com/kubernetes/kubernetes/pull/103231#discussion_r666320279 ) and other conversations that are not marked as resolved.

File: pkg/credentialprovider/plugin/config.go (hunk 3 above)
Comment (liggitt) [reply pkg/credentialprovider/plugin/config.go:52]: unioning/overlaying the default os envvars is what I expected (and is what client-go exec auth plugin does)

Comment (liggitt) [reply pkg/credentialprovider/plugin/config.go:52]: see

https://github.com/kubernetes/kubernetes/blob/e0a22acaa0c62f3e6f9dd37ab2a4e7d960528edc/staging/src/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go#L201

https://github.com/kubernetes/kubernetes/blob/e0a22acaa0c62f3e6f9dd37ab2a4e7d960528edc/staging/src/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go#L419

Comment (andrewsykim) [reply pkg/credentialprovider/plugin/config.go:52]: ^ thanks for the reference Jordan! Probably makes sense to follow same patterns as the client-go exec auth plugin in this case.

**Comment by adisky** [comment]
replying to https://github.com/kubernetes/kubernetes/pull/103231#discussion_r666320279
@n4j @andrewsykim If Kubernetes release policy permits, I am fine to land in 1.22. The feature is still in alpha so low risk code. and at the same it is  also not very critical, so fine if we want to wait for 1.23.

**Comment by andrewsykim** [comment]
I'd consider this a bug fix since the API docs say the kubelet env vars are appended, so I would like to see this land in v1.22, if not it should be cherry-picked anyways.

File: pkg/credentialprovider/plugin/config.go (hunk 3 above)
Comment (n4j) [reply pkg/credentialprovider/plugin/config.go:52]: @andrewsykim Now that we have decided to take it forward as a bug fix v1.22, are we good with the code changes or you would like me to refine it further?

File: pkg/credentialprovider/plugin/config_test.go [hunk 4]
```diff
@@ -231,7 +234,7 @@ providers:
 			}
 			defer os.Remove(file.Name())
 
-			_, err = file.WriteString(testcase.configData)
```
Comment (andrewsykim) [inline pkg/credentialprovider/plugin/config_test.go:234]: Instead of appending os.Environ into the test input, can we have a new field in testcases for "existing env vars", and then add a new testcase where test data contains an overlapping value with os env vars.

File: pkg/credentialprovider/plugin/config_test.go [hunk 5]
```diff
@@ -245,6 +248,19 @@ providers:
 				t.Error("expected error but got none")
 			}
 
+			if testcase.config != nil && authConfig != nil {
+				// append OS env vars and sort it
+				for i := range testcase.config.Providers {
+					appendSystemEnvVars(os.Environ(), &testcase.config.Providers[i])
```
Comment (andrewsykim) [inline pkg/credentialprovider/plugin/config_test.go:254]: Seems odd to be appending system env vars into the test data, this is data we should be testing against not mutating.

**Review by andrewsykim — COMMENTED** [review]
Some comments on testing

File: pkg/credentialprovider/plugin/config_test.go (hunk 5 above)
Comment (n4j) [reply pkg/credentialprovider/plugin/config_test.go:254]: @andrewsykim Agreed to your point, but if I don't perform this step then all the test cases would fail since `authConfig` would have env vars present in the system appended and `testcase.config` wouldn't.

**Comment by n4j** [comment]
/remove-sig api-machinery apps cli cloud-provider cluster-lifecycle instrumentation network release scalability scheduling storage

**Comment by n4j** [comment]
/remove-area apiserver  cloudprovider  code-generation  dependency  ipvs  kubeadm  kubectl  kubelet  provider/gcp  release-eng

File: pkg/credentialprovider/plugin/config.go (hunk 2 above)
Comment (liggitt) [reply pkg/credentialprovider/plugin/config.go:48]: I would not recommend mutating the read config here, but would construct this at invocation time.

I like the approach taken by client-go exec plugin that stubs an `environ func() []string` for testing and defaults it to `os.Environ`

I would also expect the envvars in the config file to be appended, which makes them take precedence over the os.Environ

File: pkg/credentialprovider/plugin/config_test.go (hunk 5 above)
Comment (liggitt) [reply pkg/credentialprovider/plugin/config_test.go:254]: I recommend following the approach taken by the client-go environment construction which stubs `environ `func() []string` for testing

**Comment by andrewsykim** [comment]
cc @DangerOnTheRanger

File: pkg/credentialprovider/plugin/config_test.go (hunk 5 above)
Comment (n4j) [reply pkg/credentialprovider/plugin/config_test.go]: @liggitt Done. 

Also, I have appended the env vars during the execution + I have stubbed couple of function calls in `execPlugin` to facilitate unit testing

**Comment by n4j** [comment]
@liggitt / @andrewsykim  PTAL

File: pkg/credentialprovider/plugin/plugin.go [hunk 6]
```diff
@@ -385,12 +391,27 @@ func (e *execPlugin) ExecPlugin(ctx context.Context, image string) (*credentialp
...
+
+	// Add all the environment variables configured in the plugin provider
+	// this will also override system env vars with the ones present in the
+	// config file giving config defined env vars a higher priority
 	for _, envVar := range e.envVars {
-		cmd.Env = append(cmd.Env, fmt.Sprintf("%s=%s", envVar.Name, envVar.Value))
+		envVars[envVar.Name] = envVar.Value
+	}
+
+	cmd.Env = []string{}
```
Comment (liggitt) [inline pkg/credentialprovider/plugin/plugin.go:404]: no need to parse into a map, just initialize `cmd.Env = e.environ()`, then append by ranging over envVars... later duplicate items in cmd.Env override

File: pkg/credentialprovider/plugin/plugin.go [hunk 7]
```diff
@@ -135,6 +135,10 @@ func newPluginProvider(pluginBinDir string, provider kubeletconfig.CredentialPro
 			pluginBinDir: pluginBinDir,
 			args:         provider.Args,
 			envVars:      provider.Env,
+			environ:      os.Environ,
+			run: func(cmd *exec.Cmd) error {
```
Comment (andrewsykim) [inline pkg/credentialprovider/plugin/plugin.go:139]: I think @liggitt's earlier comment here was to wrap `environ` into a function that returns []string, not a wrapper for `cmd.Run()`.
```
environ: func() []string {
     return os.enviorn()
}
```
And in the tests, you can stub out the `environ` field with a func that returns env vars you want for the tests

Comment (n4j) [reply pkg/credentialprovider/plugin/plugin.go:139]: @andrewsykim Yes `os.Environ` is stubbed and in the test cases it returns a `[]string`, however I needed to stub `exec.Run` as well to [validate](https://github.com/kubernetes/kubernetes/pull/103231/files#diff-bc8a0587b295cf65947e96a1f74138e15f41c01276d6af54d82e265a246d7ec8R843) the overlay results.

If there is a better approach then do let me know, cc: @liggitt

Comment (liggitt) [reply pkg/credentialprovider/plugin/plugin.go:139]: > however I needed to stub exec.Run as well to validate the overlay results.

I think you can unit test a computeEnv() method that does the overlay without stubbing all the way to Run

Comment (n4j) [reply pkg/credentialprovider/plugin/plugin.go:139]: @liggitt Let me know if the below approach is fine

`plugin.go`
```golang
func (e *execPlugin) ExecPlugin(ctx context.Context, image string) (*credentialproviderapi.CredentialProviderResponse, error) {
....
cmd.Env = mergeEnvVars(e.environ(), e.envVars);
err = cmd.Run()
...
}

func mergeEnvVars(osEnvVars []string, configEnvVars []config.ExecEnvVar) []string {
// merge env vars and return
}
```

Comment (n4j) [reply pkg/credentialprovider/plugin/plugin.go:139]: @liggitt ^^

Comment (liggitt) [reply pkg/credentialprovider/plugin/plugin.go:139]: sure

Comment (n4j) [reply pkg/credentialprovider/plugin/plugin.go]: @liggitt Done

**Comment by n4j** [comment]
> I'd consider this a bug fix since the API docs say the kubelet env vars are appended, so I would like to see this land in v1.22, if not it should be cherry-picked anyways.

@liggitt How do I get this merged in `v1.22` release?

**Comment by liggitt** [comment]
this can wait until master reopens for 1.23, and be picked to release-1.22 for 1.22.1 if needed

File: pkg/credentialprovider/plugin/plugin.go [hunk 8]
```diff
@@ -385,11 +387,17 @@ func (e *execPlugin) ExecPlugin(ctx context.Context, image string) (*credentialp
...
+	var configEnvVars []string
+	for _, v := range e.envVars {
+		configEnvVars = append(configEnvVars, fmt.Sprintf("%s=%s", v.Name, v.Value))
 	}
 
+	// Append current system environment variables, to the ones configured in the
+	// credential provider file. Failing to do so may result in unsuccessful execution
+	// of the provider binary, see https://github.com/kubernetes/kubernetes/issues/102750
+	// also, this behaviour is inline with Credential Provider Config spec
+	cmd.Env = mergeEnvVars(e.environ(), configEnvVars)
```
Comment (liggitt) [inline pkg/credentialprovider/plugin/plugin.go:399]: The unit test is only exercising mergeEnvVars, not the inputs to it given the `environ()` and `e.envVars` values.

Computing the env like this:
```
cmd.Env = e.computeEnv()
```

would let us put the entire implementation calling `environ()` call and appending `e.envVars` in a unit testable location.

**Comment by n4j** [comment]
@liggitt Since this PR was approved and the branch for `1.23` opened up it was auto merged, I can open a separate PR to fix the comments.

Thoughts?

**Comment by liggitt** [comment]
Sure, a follow up is fine

**Comment by brandond** [comment]
I'm having a hard time following the breadcrumbs here - did this ever get cleaned up and/or backported to 1.21 and 1.22?

**Comment by brandond** [comment]
@liggitt @n4j this is still broken on the older release branches, correct?

**Comment by liggitt** [comment]
yeah, this is only resolved in 1.23
